### ISSUE TITLE
For gke-large suite we have logs only from nodes from one node pool

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/test-infra#100]
In large clusters, we currently have move than one MIG. In particular, in GKE 2000-node clusters:
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-large-cluster
we have 2 node pools.

However, we have logs from nodes only from a single one. This is really painful for debugging...

@kubernetes/test-infra-maintainers

**Comment by wojtek-t** [comment]
@gmarek @zmerlynn

**Comment by spxtr** [comment]
Does that mean `detect-node-names` only detects one node pool?

**Comment by spxtr** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump.sh#L102

**Comment by ixdy** [comment]
Sure looks that way. Compare [GCE](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L296-L313) vs [GKE](https://github.com/kubernetes/kubernetes/blob/master/cluster/gke/util.sh#L265-L274).

Do we use `detect-nodes` or `detect-node-names` in any critical areas? Looks like it's just wrong for GKE with large clusters. @roberthbailey

**Comment by roberthbailey** [comment]
@fabioy 

Yeah, that's broken for any GKE clusters that have >1 node pool. `detect-node-instance-group` will take the list of multiple instance group URLs and just return the name of the last one in the list.

**Comment by fabioy** [comment]
I'll take this one.
