### ISSUE TITLE
decorated jobs provide insufficient information for debugging

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#10018]
Looking through all of the results on a job that plank mysteriously reported as failing, there is not even the prowjob ID in any of the files so I cannot easily view the podlogs in stackdriver.

We annotate the prow pods, but that's not particularly helpful after the pod is GCed. We should write more persistent metadata for decorated jobs

I'd also like to revisit the refs metadata, and possibly the fully resolved pod... bootstrap jobs have these and they've been very helpful when given a link to a job and asked about it..

/area prow
/cc @stevekuznetsov @fejta @krzyzacy @cjwagner 

xref: https://github.com/kubernetes/test-infra/pull/10016#issuecomment-435510599

**Comment by stevekuznetsov** [comment]
Why would that be helpful? There are two cases:

1. The `Pod` has not yet been garbage collected. In this case, it should be simple to find it:
  ```
  kubectl get pods --selector prow.k8s.io/job=name,prow.k8s.io/refs.pull=123
  ```
  (Aside: we should put the run ID in the labels, too)
2. The `Pod` no longer exists -- in which case, the ProwJob ID would not be super useful?
