### ISSUE TITLE
convert branch protector to a prowjob

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#10015]
currently it is a kubernetes cron, now that we have a trusted cluster it should be a prowjob so anyone can view logs

/cc @fejta 
/area prow
/kind enhancement

**Comment by BenTheElder** [comment]
the conversion between k8s cron and prow periodic cron should be easy but:
- we also need to get the job config map into the trusted cluster
- we need the prow bump script to bump the branch predictor config.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
This should be really simple, right?

**Comment by fejta** [comment]
Clone test-infra at head and read it from there rather than a configmap
