### ISSUE TITLE
Allow jobs to specify a namespace to schedule pods

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#10011]
Add a `Namespace` field to both `ProwJobSpec` (which specifies which namespace to create pod/build/etc resources) as well as in `JobBase` (aka `Presubmit`, `Postsubmit`, `Periodic`), which tells trigger and horologium how to populate `Spec.Namespace` in the ProwJobs it creates (via the standard config defaulting path)

This will be limited to controllers which use the official kubernetes client at first (aka the build controller) since our bespoke client is designed to work on a single namespace. Once we migrate plank to use the new controller it will have this ability as well.

Jobs that do not customize the namespace will continue to schedule in the `PodNamespace` like they do today.

ref https://github.com/kubernetes/test-infra/issues/8848 has some previous discussion about enabling this on the bespoke client for specific namespaces.

/cc @stevekuznetsov @cjwagner

**Comment by BenTheElder** [comment]
/kind enhancement
:+1:
