### ISSUE TITLE
Federated Testing guide references a missing file

### ISSUE THREAD

**Issue by chuckbutler** [kubernetes/test-infra#1003]
In the Federated Testing Guide, there is a reference to `hack/jenkins/e2e-runner.sh` and this file doesn't appear to exist in either the test-infra repository, nor does it reside in the prime Kubernetes repository.

For Information:

https://github.com/kubernetes/test-infra/blob/master/docs/federated_testing.md#run-the-e2e-tests-and-upload-results

Bullet point 2 calls out the script.  And further investigation yielded no joy

https://github.com/kubernetes/kubernetes/tree/master/hack/jenkins

**Comment by spxtr** [comment]
Related: #780.

**Comment by spxtr** [comment]
That script has moved to this repo and we version it separately from kubernetes.

**Comment by fejta** [comment]
/assign @krzyzacy 

Would you be willing to spruce up this page to provide better bootstrap info (and/or delete it)?

**Comment by spiffxp** [comment]
/close
Fixed by #5685
