### ISSUE TITLE
extraneous semicolon in Gopherage doodle

### ISSUE THREAD

**Issue by ibzib** [kubernetes/test-infra#10056]
The [Gopherage doodle](https://github.com/kubernetes/test-infra/blob/master/gopherage/README.md) contains an unidiomatic semicolon.
/assign @BenTheElder 
/joke

**Comment by BenTheElder** [comment]
EWONTFIX

This code is terrible and therefore the gopher is staring at it while clutching a `this is fine` mug. Which is what happens when we analyze our coverage data :^)
