### ISSUE TITLE
Rename fakegithub fields for clarity

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#10062]
This is to avoid confusion in tests:
- ExistingLabels --> RepoLabelsExisting
- LabelsAdded --> IssueLabelsAdded
- LabelsRemoved --> IssueLabelsRemoved

**Comment by anwaradil** [comment]
After switching to python 3 and upgrading pip.

Here is the issue I am seeing now 


bazel build //test-infra
ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: /Users/aadil/WORKSPACE (Is a directory)
ERROR: no such package 'external': Error encountered while dealing with the WORKSPACE file: /Users/aadil/WORKSPACE (Is a directory)
INFO: Elapsed time: 0.045s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by matthyx** [comment]
What is your Linux distribution? How did you install bazel, and what's the version?
Normally all dependencies, like python and co, are downloaded/installed/updated when you run bazel.
Are you behind a corporate proxy?

**Comment by anwaradil** [comment]
Thanks Matthias for reaching out, I am able to build now

I am able to build now
bazel build
INFO: Analysed 0 targets (2 packages loaded).
INFO: Found 0 targets...
INFO: Elapsed time: 36.221s, Critical Path: 0.63s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Here is the resolution 😊

I removed python 3.x completely
I was not able to build with python that was in my /usr/local/bin in  macOS
I did a fresh brew install of python2 and it worked



Thanks,
Anwar


________________________________

**Comment by anwaradil** [comment]
Please /assign this issue to me , I will take this as my first case

**Comment by matthyx** [comment]
It's impossible to assign an issue to a non-member... but consider it yours.
/remove-good-first-issue
/remove-help

**Comment by anwaradil** [comment]
Thank you! Is there a recommended procedure for pushing changes to the repo like pushing changes to a branch rather than master before making pull requests or any other recommendations? Any branch naming conventions?

**Comment by BenTheElder** [comment]
Just push to a branch on your fork, as long as you choose anything other than "master" it should work well, and the name won't be particularly important 😃

Thanks for your contribution :-)
