### ISSUE TITLE
Clean up more repo cruft / make repo navigable

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#10083]
We have a lot of cruft lingering around. Let's make the repo more organized.
Existing PRs: 
- eliminate jobs/ - @krzyzacy 
- eliminate jenkins/ - @krzyzacy, @BenTheElder 
  - we can move bootstrap.py into images/bootstrap.py
  - do something(?) with check_projects.py ... @krzyzacy 
- eliminate scenarios/ - @krzyzacy, @BenTheElder 
  - we can move this into images/kubekins-e2e instead
- place metrics collection projects into a shared top level dir (?) - @BenTheElder, @spiffxp 
  - `metrics/`,  `velodrome/`, `triage`, `kettle` -> `metrics/bigquery`, `metrics/velodrome` ...? something like that

In general test-infra is hard to navigate and intimidating to new contributors. We should organize things better and put `README.md`s in each dir to explain what they are, with a shorter top level overview of what goes where.

/kind cleanup
/sig contributor-experience
/assign

**Comment by BenTheElder** [comment]
> We can find another home for node configs, either burn into kubekins-e2e, or enforce node e2e job clone test-infra? cc @yujuhong @Random-Liu @yguo0905

even just somewhere in `config/` is better. `jobs/` is redundant and full of other cruft we should delete.

> we need to be careful as the path is hard-coded in entrypoint, in millions of images :-\

we'll want to remove it eventually anyhow...

> that script has an internal golang version replacement and we should retire it...

👍definitely sounds preferable, are you up for doing that?

> perferrably untouch them until roll them into kubetest-v2? (we can also move them around and patch up bootstrap.py..)

moving them (into the image(s)?) is what I had in mind, but removing them entirely eventually also works...

**Comment by krzyzacy** [comment]
> we'll want to remove it eventually anyhow...

My worry is... someone has some customized images (I believe there's a few out there) and suddenly they will all break :-) I'll say punt after the podutil migration is done, and we can remove it safely?

**Comment by BenTheElder** [comment]
Those people will have the same problem then unless they have also migrated :^) Fixing their images and recommending they migrate in the meantime shouldn't be a big deal. We'll have this risk as long as we support checking out test-infra and execing a script from it as the entrypoint..

**Comment by krzyzacy** [comment]
migrate to podutils means they will not checkout test-infra and run bootstrap by default :-)

**Comment by BenTheElder** [comment]
We can't know when everyone has migrated unless we like, make bootstrap
"phone home"...

**Comment by BenTheElder** [comment]
jobs/ is emptier now but not gone
jenkins/ will never go away 😛 
scenarios/ is not moving


I think probably the best option is to just close this and favor moving some stuff out of test-infra over time... like perhaps prow next.

**Comment by BenTheElder** [comment]
seems unlikely :|
