### ISSUE TITLE
further mitigate prowjob eviction

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#10085]
ref: https://github.com/kubernetes/kubernetes/issues/70708#issuecomment-436877788

right now we have: https://github.com/kubernetes/test-infra/blob/master/experiment/maintenance/enable_soft_eviction.py running on my workstation periodically.. that's clearly not good enough

we should come up with a better solution, at least running this in a trusted job / cron regularly

> image_gc_manager.go:300] [imageGCManager]: Disk usage on image filesystem is at 88% which is over the high threshold (85%). Trying to free 19773740646 bytes

....

> I1107 22:21:44.227153 435379 eviction_manager.go:358] eviction manager: must evict pod(s) to reclaim nodefs

We rescheduled a scalability job again.

/area prow
/priority important-longterm
/assign

**Comment by BenTheElder** [comment]
it turns out that node (`gke-prow-default-pool-3c8994a8-bckn`) actually has this configured:

`/etc/systemd/system/kubelet.service` ->
```
ExecStart=/home/kubernetes/bin/kubelet $KUBELET_OPTS --eviction-soft=nodefs.available<30% --eviction-soft-grace-per
iod=nodefs.available=2h
```

The problem is, this didn't prevent the pod from being evicted. cc @dashpole any ideas?
Can we GC images etc. without triggering pod eviction..?

**Comment by BenTheElder** [comment]
cc @AishSundar digging through the logs, this has happened to other jobs and our current mitigation is not really solving it it seems... also cc @krzyzacy :/

**Comment by BenTheElder** [comment]
Maybe. Even then we shouldn't be running out of space on the nodes. IIRC the boot disks are now 200GB, and scalability jobs request outsized resources, though they're not guaranteed QoS I think...

**Comment by dashpole** [comment]
can you configure image garbage collection?  https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/  The only issue with it is that if it can't gc any images when it is above the threshold, it will log a lot.

**Comment by BenTheElder** [comment]
from the docs, the image gc thresholds are deprecated in favor of just the soft / hard disk thresholds. We have the latter set.

**Comment by dashpole** [comment]
It is technically deprecated in favor of the hard eviction thresholds.  But it looks like for whatever reason, hard eviction is evicting anyways.  If you can link to the kubelet log from when this happened, I might be able to figure out why.  But making image gc kick in way before eviction is a sure way of making sure images are cleaned up pro-actively

**Comment by dashpole** [comment]
I don't expect it to be removed until we fix issues like this one.

**Comment by dashpole** [comment]
If it is removed, we would only do that once the --eviction-hard setting actually works for all cases.
