### ISSUE TITLE
Prow doesn't automatically apply language labels

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/test-infra#10097]
## This is a...

- [ ] Feature Request
- [x] Bug Report

## Problem

Prow doesn't automatically assign language labels to PRs in [k/website](https://github.com/kubernetes/website/pulls).

Per @cblecker in https://github.com/kubernetes/website/pull/10485#issuecomment-428312191:

> Based on what I understand you're doing, you could add this label section to the language-specific OWNERS files you're already creating to delegate approval permissions, and prow would label those PRs natively. No external application required!

Using the [example provided](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubectl/OWNERS) as a template, we added OWNERS files to each language subfolder:

- https://github.com/kubernetes/website/blob/master/content/en/OWNERS#L11
- https://github.com/kubernetes/website/blob/master/content/ja/OWNERS#L11
- https://github.com/kubernetes/website/blob/master/content/ko/OWNERS#L11
- https://github.com/kubernetes/website/blob/master/content/zh/OWNERS#L11

Subsequently, Prow has not applied any language labels to PRs with content changes in the relevant directories. For example:

- https://github.com/kubernetes/website/pull/10923/ (changes to `content/en/`)
- https://github.com/kubernetes/website/pull/10916/ (changes to `content/ko/`)

## Proposed solution

1. Provide guidance.

Should we be doing something differently? If we're doing something incorrectly, it's non-obvious to us. 

2a. Fix Prow.

:+1: 
   
2b. Decline to fix Prow. 

We'll re-enable the [kubernetes-docs-language-labeler](https://github.com/zparnold/kubernetes-docs-language-labeler). 
   
/area prow 
/sig docs 
/kind bug 
/priority important-soon 

/assign @cblecker @spiffxp

**Comment by BenTheElder** [comment]
First off, you write wonderful, detailed issues, thank you. :smile: 

It looks like the `owners-label` plugin is not enabled for kubernetes/website:

https://prow.k8s.io/plugins (look for owners-labels, click "details" for more info)
https://prow.k8s.io/plugins?repo=kubernetes%2Fwebsite (the plugin is not in the list for this repo)

I will PR a fix.

/assign

**Comment by zacharysarah** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/10099

**Comment by cblecker** [comment]
Thanks @bentheelder!
