### ISSUE TITLE
podutils: add a timestamp wrapper for build log?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#10100]
I can see this is useful for debugging, and is missing from bootstrap. thoughts?

/area prow
cc @cjwagner @stevekuznetsov @fejta @BenTheElder

**Comment by BenTheElder** [comment]
I would be somewhat surprised if this didn't already exist as a polished tool.

**Comment by krzyzacy** [comment]
thoughts? I think this is also a big difference between bootstrap and podutils

**Comment by stevekuznetsov** [comment]
You could append timestamps to newlines in a different implementation of the writer here:

https://github.com/kubernetes/test-infra/blob/master/prow/entrypoint/run.go#L89

However, if we want to get rid of `entrypoint` and the wrapper in general maybe we want a different approach?

**Comment by krzyzacy** [comment]
it's probably fine, nobody complaint yet

**Comment by BenTheElder** [comment]
check things like _this_ first maybe :^) https://unix.stackexchange.com/a/26797

**Comment by krzyzacy** [comment]
Also for k8s, ginkgo has a wrapper so now we actually have double timestamps which looks a bit odd...

**Comment by chaodaiG** [comment]
We have been waiting for this feature to migrate to podutil https://github.com/knative/test-infra/issues/265, and now are at a point where we have to migrate. The timestamp would be very helpful to us, and for @krzyzacy 's concern about double timestamp, may be there can be a boolean somewhere to make this optional?
/remove-lifecycle stale

**Comment by stevekuznetsov** [comment]
The idea is solid, the implementation should not be too hard. Do you think you could try a pull request to add it?

**Comment by chaodaiG** [comment]
Sounds good, I'll try to put up a pull request

**Comment by clarketm** [comment]
@chaodaiG - have you begun with the implementation? If not I can pick this up.

**Comment by chaodaiG** [comment]
@clarketm , it's not a top priority for us anymore, feel free pick it up

**Comment by clarketm** [comment]
@krzyzacy @stevekuznetsov 
Do we want this to be configurable via an entrypoint option? Also, should this be **enabled** by default?

**Comment by cjwagner** [comment]
> Do we want this to be configurable via an entrypoint option? Also, should this be **enabled** by default?

Since this is technically a breaking change it should be optional. Additionally if something is already printing timestamps we'd want to avoid printing them twice.
In practice it shouldn't break anyone though (hopefully no one is parsing logs...) and this would be generally useful so it might be appropriate to have it default to enabled?

**Comment by chizhg** [comment]
/reopen
/remove-lifecycle rotten

It looks this issue hasn't been fixed.

**Comment by howardjohn** [comment]
Can this be re-opened?

Not sure if this was known by everyone here since it wasn't called out - `kubectl logs --timestamp` currently already exists, so its possible we can do it without any sort of wrapper

**Comment by BenTheElder** [comment]
The uploaded logs are not collected via kubectl. The entrypoint wrapper
binary writes subprocess output to disk which is uploaded by the sidecar.

This could probably be a podutils option in any case, but you may have to
escalate out of band or implement this yourself if you need it.
