### ISSUE TITLE
ok-to-test should be reverted for new commits

### ISSUE THREAD

**Issue by suleymanakbas91** [kubernetes/test-infra#10118]
Currently, once someone from the trusted org comments `ok-to-test` to a PR, any upcoming commit will trigger the jobs. This could lead to security issues if the commits after `ok-to-test` comment introduce malicious code.

**Comment by matthyx** [comment]
Bug! I will look at it tomorrow morning.

**Comment by suleymanakbas91** [comment]
I know it'd be awfully inconvenient, but otherwise this would stay as a security vulnerability. I think this is a trade-off Prow admins should make between security and convenience, so how about making it configurable?

**Comment by cjwagner** [comment]
This is not a security vulnerability this is the intended behavior. `/ok-to-test` is designed to mark a PR as trusted and "ok to test" at any point in the future. We have a separate mechanism for triggering tests once, the `/test all` command. For convenience `/lgtm` also behaves like `/test all` on non-collaborator PRs.

Providing a configuration option to completely disable the `/ok-to-test` command for some or all repos might make sense though. That would restrict testing to collaborator PRs or one off test runs triggered by collaborators on non-collaborator PRs with `/test *`.

**Comment by BenTheElder** [comment]
if you only want to test the current commit you can comment `/test all` as a trusted commentor to test things once, instead of commenting `/ok-to-test`.

**Comment by BenTheElder** [comment]
It is definitely a trade-off, and I think we'd welcome a PR to make it configurable. As Cole mentioned a work-around for now is to use `/test all` instead.
