### ISSUE TITLE
branchprotector: recently added jobs are not updated

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#10114]
I recently added prowjobs for the [publishing-bot](https://github.com/kubernetes/publishing-bot) in https://github.com/kubernetes/test-infra/pull/9895 and [cluster-api-provider-digitalocean](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean) in https://github.com/kubernetes/test-infra/pull/9954.

The PR for cluster-api-provider-digitalocean was merged yesterday but the PR for publishing-bot was merged a week ago. For both these repos, I have noticed that the prowjobs don't show up as having the `required` status context.

This could lead to a PR getting merged if it gets `/lgtm` and `/approve` before all the tests run.

/kind bug

**Comment by nikhita** [comment]
cc @sttts 
for publishing bot

cc @xmudrii @alvaroaleman 
for cluster-api-provider-digitalocean

cc @cblecker 
since you mentioned on Slack that you saw something similar for https://github.com/kubernetes-sigs/yaml and https://github.com/kubernetes/klog.

cc @BenTheElder 
because you are working on https://github.com/kubernetes/test-infra/issues/10015

**Comment by nikhita** [comment]
Hmm, this is weird. https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/120 is not getting merged because the lint test keeps failing (this test won't pass until https://github.com/kubernetes/test-infra/pull/10113 is merged).

I also noticed that the lint test does not show as `required` and the https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes-sigs%2Fcluster-api-provider-digitalocean+author%3Axmudrii+head%3Adep-fix says `Unknown Merge Requirements`. Any ideas about how to make these jobs truly blocking?

**Comment by cblecker** [comment]
/assign @fejta 
/cc @cjwagner 

CC'ing Cole and assigning Erick as oncall. Can we get some eyes on this one this week? I'm not sure what broke that's preventing the branch protector from doing it's thing, especially if it's also impacting tide's merge requirements. Did the on-cluster config get corrupted somehow?

**Comment by cjwagner** [comment]
Hmm, I'm not sure what is wrong with the branch protector, I don't see any errors in the logs and it appears to be running regularly. The last time the branchprotector touched the digitalocean repo was on the 8th at 10:49am and the publishing-bot repo has never been touched.

The in cluster Prow config is exposed here and seems to be fine: https://prow.k8s.io/config

> Hmm, this is weird. kubernetes-sigs/cluster-api-provider-digitalocean#120 is not getting merged because the lint test keeps failing (this test won't pass until #10113 is merged).

Why is that behavior unexpected? That is the intended behavior unless `skip_unknown_contexts` is specified in the tide context config: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md#context-policy-options

**Comment by fejta** [comment]
Let me take a look...

**Comment by cblecker** [comment]
branch protection settings don't seem to be right for klog or yaml, still:
- https://github.com/kubernetes/klog/settings/branch_protection_rules/2611641
- https://github.com/kubernetes-sigs/yaml/settings/branch_protection_rules/2667334

**Comment by fejta** [comment]
We're not toggling whether to use all branches/all repos correctly

**Comment by cblecker** [comment]
Verified that the fix is working as expected.

Thanks so much, @fejta!

/close
