### ISSUE TITLE
Cat plugin is unusable.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#10110]
There is no way to specifically request GIF images even though https://thecatapi.com site [serves them](https://github.com/kubernetes/test-infra/pull/10109#issuecomment-437243660) and actually provides a way to [request them specifically](https://documenter.getpostman.com/view/5578104/RWgqUxxh#query-parameters).

/assign @michelle192837 @cjwagner 
/cc @BenTheElder @krzyzacy @fejta @ibzib 
/kind bug
/priority critical-urgent

**Comment by BenTheElder** [comment]
This plugin is literally unusable now.
/area prow

**Comment by krzyzacy** [comment]
also `/meow psychedelic` does not work anymore? (ref https://github.com/kubernetes-client/python/pull/673#issuecomment-437179170)

/meow
