### ISSUE TITLE
Make the links in prow responses configurable 

### ISSUE THREAD

**Issue by suleymanakbas91** [kubernetes/test-infra#10138]
**What would you like to be added**:

Currently, filing an issue and commands help links in prow responses are hardcoded [here](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/respond.go#L26). It would be nice to configure them to point our prow instance and our repo. 

**Why is this needed**:

To prevent users from ending up here for every question they have regarding our prow instance.

/kind feature

**Comment by BenTheElder** [comment]
/cc @cjwagner 
/area prow

imo this is a bug, agree we should fix this. we could do something like allow a cross-plugin config setting to specify the base URL to deck, and fallback to https://prow.k8s.io when unset to preserve existing functionality until everyone has configured this.

**Comment by ms4720** [comment]
Mind if I work on it?

**Comment by BenTheElder** [comment]
Please do!
/remove-help

**Comment by ms4720** [comment]
ok now I need to figure out how to do this, is there a getting started guide?

**Comment by idealhack** [comment]
related: https://github.com/kubernetes/test-infra/issues/9256

**Comment by suleymanakbas91** [comment]
/remove-lifecycle stale

Hi @ms4720, are you already addressing the issue? :)

**Comment by ms4720** [comment]
@suleymanakbas91 not in the next 4 weeks. Sorry things got in the way

**Comment by kasiakepka** [comment]
/remove-lifecycle stale 
Hi @ms4720, is there a chance that you will work on it in nearest future? :)

**Comment by ms4720** [comment]
> /remove-lifecycle stale
> Hi @ms4720, is there a chance that you will work on it in nearest future? :)

yes there is, not nearest but near is possible.  Sorry life got in the way
