### ISSUE TITLE
Rerun quick copy button errors out

### ISSUE THREAD

**Issue by amwat** [kubernetes/test-infra#10157]
**What happened**:
Clicking on the copy button in the rerun command errors out with 
```Uncaught ReferenceError: copyToClipboardWithToast is not defined at HTMLAnchorElement.onclick ((index):1)```
**What you expected to happen**:
The rerun command to be copied to clipboard.
**How to reproduce it (as minimally and precisely as possible)**:
go to https://prow.k8s.io/ , click on the rerun icon for any prowjob, click on the quick copy button.
**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/static/prow/prow.ts#L615

/kind bug

**Comment by BenTheElder** [comment]
I'm sorry for that terrible code. We should fix that. Will try to look soon.
