### ISSUE TITLE
Prow job started twice

### ISSUE THREAD

**Issue by mborsz** [kubernetes/test-infra#10188]
**What happened**:
The ci-kubernetes-e2e-gce-scale-performance job was started two times on 2018-11-16: at 21:40 CET, and 9:02 CET.

**What you expected to happen**:
Only single run to happen, the one at 9:02 CET which is specified in the job config.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/258
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/259

**Anything else we need to know?**:

/cc @wojtek-t 

/kind bug

**Comment by mborsz** [comment]
Thanks for the response. Is there any way to prevent rerunning test in case of pod eviction? This test is sharing gce project with other tests, so if it doesn't finish in time, other test will run and will break both of them.

**Comment by BenTheElder** [comment]
I don't think we have any functionality for that ourselves, but k8s pods might, k8s is rescheduling the pod after evicting it. cc @cjwagner

**Comment by cjwagner** [comment]
Based on the `plank` code, k8s actually marks the pod as failed when it is evicted and `plank` is responsible for the rescheduling. 
https://github.com/kubernetes/test-infra/blob/2946ed2b3cc74e8f1d91ee05687d209ac9b1b571/prow/plank/controller.go#L376-L378
It sounds like for some jobs we should instead be completing the ProwJob and setting it to `kube.ErrorState`. We could make this behavior configurable with an additional per job config field.

**Comment by BenTheElder** [comment]
SGTM, we'd definitely disable rescheduling for most scalability jobs. maybe `failOnEviction: true`? (naming is hard!)

**Comment by cjwagner** [comment]
`errorOnEviction` might be a bit more precise. I'll make a PR.
