### ISSUE TITLE
move federated test result config somewhere more prominent and make everything use it

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#102]
`jenkins/test-history/buckets.json` is sort-of the source of truth for which buckets we care about, except that there is also configuration in `gubernator/main.py`, `jenkins/test-history/gen_json.py`, the submit queue, and testgrid. (And maybe other places, who knows.)

It'd be nice if we moved the configuration somewhere more prominent (maybe even top-level?) and then got all of our tooling using it.

It should also be well-documented.

(It'd be a good idea to add owners for each of the various builds at that time, too.)

**Comment by fejta** [comment]
Shall we consider this closed?

**Comment by spxtr** [comment]
Yes. It's top-level and everyone uses it, I think.
