### ISSUE TITLE
Document limitations in naming prow jobs

### ISSUE THREAD

**Issue by suleymanakbas91** [kubernetes/test-infra#10209]
Using slashes `/` in job names cause problems like spyglass showing an empty page. It'd be nice have this and any other limitations in naming prow jobs documented somewhere.

**Comment by michal-hudy** [comment]
Consider also adding a check for names to the `k8s.io/test-infra/prow/cmd/checkconfig`.

**Comment by BenTheElder** [comment]
+1 for both, cc @cjwagner more prow docks and checkconfig? 🙃
