### ISSUE TITLE
Add non-active approvers as a field to owners files.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/test-infra#10226]
**What would you like to be added**:
Add a field to owner files for non-active approvers. 

These are people/leads/chairs that may need to perform periodic surgery on a given area and are well versed, but should not be assigned on a day-2-day basis.  

**Why is this needed**:
As part of repo addition to k8s-sigs, sig-leads are added to the approvers files for multiple reasons.  However, they should not be auto-assigned on a day-2-day basis. 

There are also folks who have rotated across the project over time, and they still may need to break-ties under certain conditions. 

/kind feature

**Comment by justaugustus** [comment]
+1 for this

**Comment by stevekuznetsov** [comment]
/cc @fejta @cjwagner @BenTheElder 
Does our current OWNERS impl (as rusty as it is) have enough flexibility to add this?

**Comment by cjwagner** [comment]
> Does our current OWNERS impl (as rusty as it is) have enough flexibility to add this?

I'm sure it is possible, but it would add more complexity to the existing heap of technical debt. It may be worth it to hack this in now, but we should consider rewriting some of the plugin first.

**Comment by nikhita** [comment]
> However, they should not be auto-assigned on a day-2-day basis.

Currently prow doesn't automatically assign users, only automatically request reviews from people.

Blunderbuss will look to request reviews from the list of `reviewers` mentioned in the OWNERS file, and if it can't find any reviewers it will fall back to the list of `approvers`. So one way to work around automatic review requests would be to listed as an approver but _not_ as a reviewer in the OWNERS file.

Having said that, prow can suggest that the author assign you if you are listed as an `approver` -- but fwiw it won't still automatically @-mention you in this case. :grimacing:

**Comment by nikhita** [comment]
/remove-lifecycle stale

cc @mrbobbytables 
since you had thoughts around this

**Comment by mrbobbytables** [comment]
Thanks for the poke @nikhita :)

It doesn't cover the exact use-case, but is targeted towards those that have shifted positions or not as active but still serve as domain experts. My thought was establishing a more formal _"emeritus"_ policy -- Get something down before kicking off a potential OWNERS audit. We have the concept of emeritus leads, and have used emeritus informally in a few OWNERS files already.

Commenting out or adding a new "emeritus" section leaves their names in the OWNERS file as a polite nod and reference. They can still be CC'ed etc for their opinion and it gives them an easy way back if their situation should change.

"emeritus" could also potentially become "non-active" in the future should that functionality be added to prow.

**Comment by nikhita** [comment]
Related https://github.com/kubernetes/kubernetes/issues/76269#issuecomment-483069884

**Comment by nikhita** [comment]
Related https://github.com/kubernetes/community/pull/3627

**Comment by fejta** [comment]
I'm against this in principle. 

Gaining the authority to make decisions should come paired with the burden of reviewing PRs related to those decisions. 

Otherwise there's no cost associated with being an approver and so it becomes a status symbol.

**Comment by spiffxp** [comment]
>So one way to work around automatic review requests would be to listed as an approver but not as a reviewer in the OWNERS file.

This is why there are many OWNERS files with the same people in `reviewers` and `approvers`, however this is no longer the case.

https://github.com/kubernetes/test-infra/blob/c045041c286768845a7deac3d9a301946d04547f/prow/plugins/config.go#L114-L118

Functionally, things used to behave as if this was set to `true`.  However, for the reasons @fejta described, prow.k8s.io is setup with the default of `false`.  This is a global setting that cannot be configured per-repo.  I think the `emeritus_approver` section added by @mrbobbytables is an adequate compromise if it's about needing someone with clout to weigh in.

/close
Please /reopen if you would like to take up with sig-contributor-experience whether there is a desire to "revert" and set this to `true`.  Another option may be to modify the config for this plugin such that it could be configured per-repo.
