### ISSUE TITLE
rename kubekins-e2e to something more accurate

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#10230]
**What would you like to be added**: rename kubekins-e2e

**Why is this needed**: Jenkins hasn't been involved for a long time, and this image is hardly just used for e2es

I propose `krte` - `K`ubernetes `R`un`T`ime `E`nvironment pronounced "kurt-ee", with a wink to Googlers :wink: 

This will follow through on its name, and be the standardized runtime environment for complex e2es, build etc. Simpler jobs should use smaller images provided by the user or from upstream sources eg `golang`.

The current image is most of the way to this, if not in name, and in need of some cleanup.

/assign
/assign @krzyzacy @ixdy 

/kind feature

**Comment by ixdy** [comment]
so many good puppers!

**Comment by BenTheElder** [comment]
might actually do something about this image as we move towards pod-utils ... common images do improve caching / start time...

**Comment by BenTheElder** [comment]
my actual plan is to make a cleaner pod-utils only image for kubetest2 jobs and let kubekins eventually die

**Comment by BenTheElder** [comment]
shrug
