### ISSUE TITLE
Prow constantly reruns successful tests and tide does not put PRs in merge pool

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#10244]
**What happened**:
Our approved PRs take multiple hours to merge.
All tests pass (takes half an hour), but instead of `tide` putting the PR into the merge pool, after several minutes Prow just starts all tests again. And again. And again. And again. 
See this PR for instance: https://gubernator.k8s.io/pr/kubeflow/pipelines/389 - the tests are rerun successfully 6+ times and the PR is still not in the merge pool.

It feels like the merge time is quadratic in number of approved PRs. It should be linear.
It also feels like tide waits for **all** tests to finish including the `skip_report` ones.

**What you expected to happen**:
I expect the tests to only run once after a code change before PR is moved to merge pool. I expect the tests run one time at max while in the merge pool.

**How to reproduce it (as minimally and precisely as possible)**:
Create long-running tests for your project.
Submit and approve 10 PRs.
Look how many times the tests run for each PR until it's merged. This number should be 1 or 2, but it is higher.

**Please provide links to example occurrences, if any**:
https://gubernator.k8s.io/pr/kubeflow/pipelines/389  and most other PRs in this repo.

**Anything else we need to know?**:

/kind bug

**Comment by Ark-kun** [comment]
@IronPan @vicaire @yebrahim @jlewi

**Comment by cjwagner** [comment]
Tide does not properly handle `run_after_success` jobs and we have decided not to include the PR to add support for them (https://github.com/kubernetes/test-infra/pull/8868) because we will be deprecating `run_after_success` as soon as the knative pipeline CRD is viable as a replacement. 
See the PR for details on why we chose not to go forward with `run_after_success`.
