### ISSUE TITLE
Migrate gce jobs to bootstrap

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1025]
For https://github.com/kubernetes/test-infra/issues/1021

https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml

Follow #1020

**Comment by krzyzacy** [comment]
start with gce ones

**Comment by krzyzacy** [comment]
only things left are one manual job and crit jobs, tracking by #1058
