### ISSUE TITLE
gubernator: support logs in nested directories

### ISSUE THREAD

**Issue by pohly** [kubernetes/test-infra#10289]
**What would you like to be added**:

When viewing test artifacts via the log view (for example, https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4398/nodelog), logs are only found if they are one level below the `artifacts` directory. This works:
* `artifacts/_sig-storage_CSI_Volumes_Driver_csi-hostpath-v0_Testpattern_Dynamic_PV_default_fs_subPath_should_unmount_if_pod_is_force_deleted_while_kubelet_is_down_Disruptive_Slow_/csi-hostpath-attacher-0-csi-attacher.log`

This doesn't:
* `artifacts/sig-storage/CSI_Volumes/Driver_csi-hostpath_v0/Testpattern_Dynamic_PV/default_fs_subPath/should_unmount_if_pod_is_force_deleted_while_kubelet_is_down_Disruptive_Slow_/csi-hostpath-attacher-0-csi-attacher.log`

What happens when creating such logs is that the UI displays just the top-level directories but not the files inside them.

The simplest solution would be to keep the current grouping in the UI (directory name in bold to group files, underneath each file in that directory with a checkmark) but search more thoroughly for log files and allow nested directories. Then at least looking at the "artifects" directory would become easier.

But users of the log viewer would still see quite a few files they have no interest in. So some UI redesign with nested grouping and deeper groups folded away by default would be needed to address that.

**Why is this needed**:

These logs for storage tests have proven to be very useful for analysing errors involving the various CSI sidecar containers, see for example https://github.com/kubernetes-csi/external-attacher/issues/102. But other groups now have to skip over a lot of files they have no interest, so moving them to sub-directories and UI enhancements to hide them by default would be useful.

/kind feature
/cc @msau42

**Comment by BenTheElder** [comment]
this would be a good feature for spyglass @Katharine @ibzib @paulangton 

currently gubernator is mostly in maintenance mode.

**Comment by Katharine** [comment]
I didn't even know gubernator had this feature.

Another one for the spyglass todo list.
