### ISSUE TITLE
Gubernator is showing merged PR as Needs Attention

### ISSUE THREAD

**Issue by jessiezcc** [kubernetes/test-infra#10295]
/kind bug
This happened with Knative Gubernator instance: https://gubernator.knative.dev/pr
I'm aware of previous filed bug https://github.com/kubernetes/test-infra/issues/1576, Knative Gubernator should already have that fix. 

Tracking bug on Knative: https://github.com/knative/test-infra/issues/283

**Comment by stevekuznetsov** [comment]
Gubernator is being deprecated.

/close
