### ISSUE TITLE
e2e coverage jobs are filling triage with noisy failures

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#10307]
https://storage.googleapis.com/k8s-gubernator/triage/index.html
<img width="1114" alt="screen shot 2018-12-02 at 4 44 06 pm" src="https://user-images.githubusercontent.com/49258/49347259-86412400-f651-11e8-99d6-3f88143ac9d8.png">

The scale of coverage failures makes it difficult to get a feel for how other failures are impacting overall test / project health.

We could adjust triage to ignore these results, or we could find a different way of signifying pass/fail for coverage.

/assign @Katharine

**Comment by Katharine** [comment]
That's impressive.

Short-term solution is probably just to set the coverage threshold to zero.
