### ISSUE TITLE
k8s-ci-robot says that a test has failed, but the test actually succeeded

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#10328]
**What happened**:

The k8s robot has added the following comment to my PR: https://github.com/kubeflow/pipelines/pull/461#issuecomment-444027099

The problem is that the "failed" build-image test it links to actually succeeded: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/461/build-image/792

Test name | Commit | Details | Rerun command
-- | -- | -- | --
presubmit-e2e-test | e1af66b | https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/461/presubmit-e2e-test/648| /test presubmit-e2e-test
build-image | 9b185ae | https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/461/build-image/792| /test build-image

https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/461/build-image/792

PR | Ark-kun: [WIP]Tests - reintegrate build-image stage back into test suites
-- | --
Result | SUCCESS

**What you expected to happen**:
I expect the robot to tell the truth.

**Please provide links to example occurrences, if any**:
https://github.com/kubeflow/pipelines/pull/461#issuecomment-444027099
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/461/build-image/792

/kind bug

**Comment by krzyzacy** [comment]
the prowjob is in failure state, can gcs upload failure cause we mark the prowjob as failed?

**Comment by stevekuznetsov** [comment]
Perhaps -- can you check the pod? In this case the GCS upload would have had to have failed for some artifact but not `finshed.json`

**Comment by krzyzacy** [comment]
yeah...

```
"failed to upload to GCS: failed to upload to GCS: encountered errors during upload: [[Post https://www.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json&projection=full&uploadType=multipart: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: net/http: TLS handshake timeout] [Post https://www.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json&projection=full&uploadType=multipart: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: net/http: TLS handshake timeout]]"   
```

**Comment by krzyzacy** [comment]
probably we shouldn't fail the job when job passed and gcs upload failed?

**Comment by stevekuznetsov** [comment]
yeah, we could make `sidecar` never fail

**Comment by BenTheElder** [comment]
I've encountered this before, forgot about this. Is anyone prepping a patch?

**Comment by Ark-kun** [comment]
Thanks for fixing this!

I wonder whether the problem is somehow related to the fact that that test suite exits immediately after start (exit 0)

**Comment by krzyzacy** [comment]
I think it's just a gcs flake. (also it's easier to drop a `/retest`)

**Comment by Ark-kun** [comment]
This should be fixed.
