### ISSUE TITLE
Resource usage for prow jobs

### ISSUE THREAD

**Issue by mborsz** [kubernetes/test-infra#10329]
**What would you like to be added**:
It would be nice to be able to see how much resources the prow job is consuming.
**Why is this needed**:

I have a suspicion that prow job ci-kubernetes-e2e-gce-scale-performance is cpu starved, e.g.: 'Deleting ReplicationController X took Y' measures time for simple apiserver call.
I see in build-log.txt
```
Nov 23 17:03:54.909: INFO: Deleting ReplicationController load-small-11795 took: 8.070090818s
```

while from kube-apiserver point of view, the request takes 35ms:
```
I1123 17:03:46.892825       1 wrap.go:47] DELETE /api/v1/namespaces/e2e-tests-load-30-nodepods-46-26q5b/replicationcontrollers/load-small-11795: (34.966128ms) 200 [e2e.test/v1.14.0 (linux/amd64) kubernetes/205eaee 35.193.86.240:44980]
```

Right now I have no tooling (I don't have access to prow cluster) to check resource usage and debug this.

/kind feature

**Comment by mborsz** [comment]
Thanks for the answer, Steve!

Sure, I'm aware of load metrics (for the cluster under test) emitted by scalability tests itself, but I'm rather interested in usage metrics for pod running test logic in prow cluster (as in scalability test it does some nontrivial work).

Let me ask the initial question in a slightly different way:

I see that we do set some resource requests for our ci-kubernetes-e2e-gce-scale-performance job:
https://github.com/kubernetes/test-infra/blob/f61cf6eab16515ffc32a85489d56847aee9f408a/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L289-L292

How can I check if they are correct? Is there any way to check what the actual usage was vs 6 cores set there?

**Comment by shyamjvs** [comment]
@stevekuznetsov I think @mborsz is asking for the resource usage of prow job pod itself (not the cluster under test - for which we already collect metrics in our e2es). This can affect tests.

**Comment by stevekuznetsov** [comment]
Ah, I see. I was thinking that would still have been incumbent on the API server under test and not the client, but I see what you mean. I think to access this specifically you'd need to query prometheus on the build cluster. To do that you'd want to ask the k8s-test-infra on-call or ask in #testing-ops on Slack.

/cc @BenTheElder

**Comment by BenTheElder** [comment]
@ixdy is oncall now :-)

Googlers also should have _read_ access to the clusters IIRC. oncall has write etc. (also obviously we'd like to open that up to more people, but we need more momentum in #k8s-infra-team for hosting this sort of thing and moving it over)

**Comment by BenTheElder** [comment]
We discussed exposing this info before, but @kargakis and @stevekuznetsov thought that might be sensitive IIRC. I'd have loved to see prow.k8s.io surface usage.

note that those requests are designed to be innaccurate though, they're meant to avoid expensive scalability jobs from being evicted by requesting outsized resources.

**Comment by kargakis** [comment]
A unique endpoint would be fine I think.
