### ISSUE TITLE
Add Issue Dashboard Page for SIGs

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#1033]
I got some informal feedback that being able to assign issues or test flakes to SIGs (instead of just individuals) would be beneficial and encourage issue triage.  I realize that github doesn't allow this, but we can and often do mention SIGs in the comments on issues.

Can you add a page to gubernator/PR Dashboard where people can view the issues where a specific SIG was mentioned.

@dashpole

**Comment by spxtr** [comment]
What about sig labels?

**Comment by grodrigues3** [comment]
good question.   Currently, there are not sig-labels, just teams, areas and components, and i'd hesitate to add another set of routing labels.  Having sig-labels certainly would make it easier to filter directly on github, but I think the existing workflow is to mentioned sigs in the comments/PR body.

**Comment by spxtr** [comment]
The only downside is that if someone mentions a sig that doesn't really apply then you can't really remove it.

Still SGTM.

**Comment by rmmh** [comment]
Do team and area labels not map to SIGs precisely? Why can't we make that work properly?

**Comment by spxtr** [comment]
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22%40kubernetes%2Fsig-testing%22 is pretty good, too.

**Comment by grodrigues3** [comment]
test

**Comment by grodrigues3** [comment]
@spxtr that looks like it might be good enough for now

**Comment by fejta** [comment]
testgrid.k8s.io -> click on the sig-foo button of interest
Alternatively
go.k8s.io/triage and click on the sig of interest
