### ISSUE TITLE
Move scalability jobs to boskos

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#10352]
Per discussion in https://github.com/kubernetes/test-infra/pull/10233:

There's always gonna be at most one scalability job running, so one shared resource should be sufficient.

cc @wojtek-t @BenTheElder 
/assign
/kind feature

**Comment by wojtek-t** [comment]
cc @mborsz @krzysied

**Comment by krzyzacy** [comment]
/assign @amwat 
🤦‍♂️ didn't have cycle, let's see if we can sneak this in before code freeze

**Comment by krzyzacy** [comment]
(Looks like scalability team gonna set up their own Prow instance and run jobs there, I'm gonna punt this one)
