### ISSUE TITLE
Replace gubernator links with spyglass links

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#10375]
We want to deprecate gubernator (except for its PR dashboard). Before we can do that, we need to:

- [x] Merge the PR history view (#10169)
- [x] Show pod logs as necessary even when given GCS URLs
- [x] Add testgrid integration (but do we really want to couple prow and testgrid? gubernator does this by reading the testgrid config proto...)
- [x] Add links to view artifacts
- [x] Improve the failed test display (at least make the failure text more legible)
- ~~[ ] Node log viewing?~~
- [x] For transitional purposes, add a link to gubernator

Anything I missed? We can already:

- [x] Show the build log
- [x] Show test results
- [x] Show build metadata
- [x] Show job histories

Some of these things are probably uncommon (node logs?) and at least initially are sufficiently served by the link to gubernator.

**Comment by spiffxp** [comment]
>Add testgrid integration (but do we really want to couple prow and testgrid? gubernator does this by reading the testgrid config proto...)

The current coupling may be ugly, there's probably a better way to do it that will require some rearchitecting, but the mapping from job <-> history of job runs (in testgrid form) is very useful.  I can quickly jump from how is _this_ run doing, to how have _all_ runs been doing

> Improve the failed test display (at least make the failure text more legible)

Agree.  I'm not sure how many people use the "click to see stdout/stderr" link, but if nothing else it's additional info captured in the junit file that could be displayed nicely

eg: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/17584#k8sio-summary-api-nodeconformance-when-querying-statssummary-should-report-resource-usage-through-the-stats-api

**Comment by spiffxp** [comment]
From my design nerd perspective, it doesn't appear dense enough.  Don't get me wrong, whitespace is good.  This doesn't feel like it's been put through a pass with that kind of eye though.

Text is small.  I see N different kinds of font styles.  It would be nice use a grid or something for consistent alignment
<img width="701" alt="screen shot 2018-12-07 at 11 08 00 am" src="https://user-images.githubusercontent.com/49258/49667589-683c4080-fa10-11e8-8184-b4c89cf37fdc.png">

**Comment by BenTheElder** [comment]
Yes... spyglass has basically no CSS yet because that comes after the
functionality works fully!
give me working podlogs cough @ibzib cough and I might take a look slash
poke @Katharine

**Comment by Katharine** [comment]
I'm pretty sure none of this has been put through any sort of pass beyond "yes, this is technically capable of rendering information from artifacts". There has been slightly more effort on the build logs.

**Comment by ibzib** [comment]
re metadata viewer, I put in #10406. I wouldn't say it looks _good_ now, but at least it's not spread out into different tables and cluttered with empty fields anymore.

**Comment by Katharine** [comment]
I did some work on the UI to prettify it in #10929 / #10932, which hopefully at least mostly resolves the broadest design complaints (@spiffxp):

![image](https://user-images.githubusercontent.com/110792/51708108-e14f2180-1fd7-11e9-80e0-cfefeeb39a04.png)

**Comment by spiffxp** [comment]
Will also want to update links in go.k8s.io/triage (test-infra/triage)

**Comment by Katharine** [comment]
This happened.
