### ISSUE TITLE
run_if_changed job required even if it does not match a changed path

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#10393]
We have a job that is [run_if_changed](https://github.com/openshift/release/blob/790ca22f741c181dfc4f6db377e11c4f52d3756b/ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml#L135) but shows up as required in a PR that does not touch the path required for the job to run.

See https://github.com/openshift/openshift-azure/pull/867

@stevekuznetsov @cjwagner 

/area prow
/kind bug

**Comment by stevekuznetsov** [comment]
It is required, but should be skipped. This is WAI

/close
