### ISSUE TITLE
prow: reply to PR with pass/fail status of merged postsubmit

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#10402]
Post-submit jobs that are tied to a PR should be able to post the results of the job back to the PR.

We do something similar for the `updateconfig` plugin, but job status (pass/fail) and a link to the job log should be something all postsubmits can do.

/kind feature

**Comment by aszecowka** [comment]
Do you plan to provide retest functionality for postsubmit jobs from PR view?

**Comment by alvaroaleman** [comment]
@krzyzacy Are you currently working on this?

**Comment by krzyzacy** [comment]
yes, I'm trying to migrate reporter to crier first. https://github.com/kubernetes/test-infra/pull/10675 and https://github.com/kubernetes/test-infra/pull/10818 are moving towards that. Once that's done technically we only need to enable Postsubmit to https://github.com/kubernetes/test-infra/blob/master/prow/github/reporter/reporter.go#L55 - will make a follow up PR in the week. (Friday afternoon? 😏 )

**Comment by krzyzacy** [comment]
Current status:

I added the report field for postsubmit jobs (not reporting by default), and found out the report lib need to be updated in order to update status on a BaseSHA instead of PullSHA.

Once it works I'll post the announcement and we have plan to switch on report for all postsubmit jobs and unify the report field in config with presubmit jobs.

**Comment by krzyzacy** [comment]
After https://github.com/kubernetes/test-infra/pull/11168, we will have postsubmit setting status context by default for all postsubmit jobs.

Currently the knative-postsubmit worked for test-infra repo.
![screenshot from 2019-02-06 14-38-46](https://user-images.githubusercontent.com/1108148/52454738-c1544d80-2b01-11e9-980c-bdda49afb92a.png)

Will implement comment on a commit & respond to trigger from a commit in the near future.

**Comment by cblecker** [comment]
/remove-lifecycle stale

Would still love to see a comment at some point.

**Comment by krzyzacy** [comment]
/unassign
/help

not actively working on this, posting a comment is trivial but we probably also want to handle retrigger a postsubmit job.

**Comment by stevekuznetsov** [comment]
We only need the comment on a failure, right?

**Comment by krzyzacy** [comment]
I think @fejta also wanted a trigger, or else we can just let it make the same comment as presubmit

**Comment by spiffxp** [comment]
Reporting status contexts to merge commits is a good start, but I would still rather see comments on the PR(s) in question for success or failure.  Specific use cases in mind:
- tell me when the PR that merged caused something to deploy
- tell me when the PR that merged caused something to get pushed

This would require at least some changes to crier's github reporter, which currently:
- always adds a status context (we might want this to be configurable)
- always uses a hardcoded commenting scheme (we might want report-on-success on a per-job basis, or we might want a per-job report template)

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/17142 looks like a good start

**Comment by spiffxp** [comment]
Where I experience this pain at the moment is getting random testgrid notifications for image-builder jobs that have failed.  It's not clear to me:
- what PR caused the job
- if the person who cares about that PR knows their changes haven't landed in a newly pushed image

A rough guess at scope:
```sql
#standardSQL
select
  job,
  trunc(countif(result = 'FAILURE')/count(*),4) as failure_rate,
  countif(result = 'FAILURE') as failed_runs,
  count(*) as runs
from
  `k8s-gubernator.build.all`
where
  started > TIMESTAMP('2020-10-01')
  -- assume most image-builder jobs follow this naming pattern
  and job like 'post-%push%'
group by
  job
order by
  failure_rate desc, runs desc
```
Dumped into [this google spreadsheet](https://docs.google.com/spreadsheets/d/1TWauyTkQ9dsx5LGEags2hdTmLDjxWdKIZNr_Zs_8GZU/edit#gid=0) (viewable to members of kubernetes-sig-testing@googlegroups.com)

17% failure rate for ~3000 image-builder jobs over the past 4 months

Could further refine by seeing how many jobs are re-ran against the same commit to get a sense of "is anyone noticing this"

**Comment by fejta** [comment]
Commits may or may not include a PR. I would prefer prow:
* Report postsubmit jobs to the commit, rather than the PR
  - This is already where we report the status
* Listen for comments added to the commit, allowing /retest, etc
* Potentially drop a note on the PR (once) noting that postsubmits were triggered at commit X

**Comment by oshoval** [comment]
Hi, seems it is closed without being merged?

```
    spec:
      containers:
      - name: <container-name>
        image: <container-image>
      report:
        comment:
          message: "The Prow job {{.Spec.Job}} on branch {{.Spec.Refs.BaseRef}} was {{if .Status.Success}}successful{{else}}unsuccessful{{end}}."
          always: true
```
would something like this work ?

or something like this 
https://github.com/istio/test-infra/pull/1404/files

**Comment by BenTheElder** [comment]
You can see what happens with _commits_ in postsubmit already.

As mentioned above, commits may not be 1:1 with PRs.

This is not currently planned, and prow has moved out to github.com/kubernetes-sigs/prow.

For current discussions, please use the prow issue tracker.
