### ISSUE TITLE
Make a new Prow logo

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#10414]
I've got a draft, but it should be touched up and formalized before use.

/area prow
/priority critical-urgent
/assign michelle192837

**Comment by michelle192837** [comment]
@cblecker @cjwagner

**Comment by cblecker** [comment]
@thockin Is there a specific procedure we should go through to have art (like a subproject logo) be kosher license wise? Or is a PR with the CC license enough?

@parispittman FYI — I’ll talk to you about this one out of band. I’d like to help sig-testing with this.

**Comment by cblecker** [comment]
This is in progress :)

**Comment by neolit123** [comment]
:tada: :+1:

**Comment by michelle192837** [comment]
Prow has and is using a new logo now ^^
