### ISSUE TITLE
Add Pony API

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#10415]
Extremely urgent, please add to Prow asap.

/assign fejta katharine
/area prow
/priority critical-urgent

**Comment by Katharine** [comment]
https://derpibooru.org/search.json?q=aspect_ratio.gte%3A0.5%2C+aspect_ratio.lte%3A2%2C+-webm&perpage=1&sf=random&filter_id=161841 should generate suitable ponies for this purpose.

Taking `search[0].representations.medium` from that gets you something like this:

![a random pony](https://derpicdn.net/img/2017/11/6/1579830/medium.png)

Or `small` is like this:

![a random pony](https://derpicdn.net/img/2017/11/6/1579830/small.png)

**Comment by BenTheElder** [comment]
I'm so glad we can efficiently close P0s like this even while we're all at KubeCon. Great work @Katharine :D

**Comment by dims** [comment]
Nice! :)

/pony

**Comment by Katharine** [comment]
Unfortunately, this is not yet deployed or enabled. However, I can imitate the bot to provide ponies:

[![](https://derpicdn.net/img/2017/1/5/1332886/small.png)](https://derpicdn.net/img/view/2017/1/5/1332886__safe_artist-colon-empyu_applejack_fluttershy_pinkie+pie_rainbow+dash_rarity_twilight+sparkle_chibi_cuddle+puddle_cuddling_cute_dashabetes_diap.png)

<details>
I am not actually a bot.
</details>

**Comment by ixdy** [comment]
an updated prow has been deployed.

**Comment by liztio** [comment]
![image](https://user-images.githubusercontent.com/33235082/50116245-a3f8b680-0217-11e9-8cac-01b20877ddd2.png)

**Comment by BenTheElder** [comment]
hotfix is in! we just need to deploy it

**Comment by liztio** [comment]
too soon, ci-robot :cry:
