### ISSUE TITLE
Prow issue:  k8s-ci-robot  suggests approver but does not accept them

### ISSUE THREAD

**Issue by giddel** [kubernetes/test-infra#10434]
https://github.com/helm/charts/pull/9967

k8s-ci-robot  suggests:

> We suggest the following additional approver: jackzampolin
> Needs approval from an approver in each of these files:  [stable/influxdb/OWNERS](https://github.com/helm/charts/blob/master/stable/influxdb/OWNERS)

But if I do so, the robot says:

> GitHub didn't allow me to assign the following users: jackzampolin.
> Note that only [helm members](https://github.com/orgs/helm/people) and repo collaborators can be assigned.

=> jackzampolin is the only approver in stable/influxdb/OWNERS  but no helm member.

How should I deal with it?

**Comment by fejta** [comment]
a) Look at /stable/OWNERS or /OWNERS
b) File an issue in the helm/charts repo they need to either: 1) remove jackzampolin from the owners file or 2) make them a repo collaborator or 3) add them as an org member.

**Comment by BenTheElder** [comment]
seems like the verify-owners plugin should help here, we might also need a
way to retro-actively scan a repo though...

**Comment by stevekuznetsov** [comment]
A CLI to verify existing owners would be useful! 
/remove-lifecycle rotten

**Comment by nikhita** [comment]
> A CLI to verify existing owners would be useful!

Closing in favour of https://github.com/kubernetes/test-infra/issues/5175
/close
