### ISSUE TITLE
hourly maintenance jobs are failing PR and CI jenkins

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1044]

**Comment by spxtr** [comment]
```
W1116 08:11:04.231] Error response from daemon: conflict: unable to delete 3e6e628140e9 (must be forced) - image is being used by stopped container cd1392970d26
W1116 08:11:04.231] Error response from daemon: conflict: unable to delete 83994c895f27 (must be forced) - image is being used by stopped container d6a0669e0a48
```

**Comment by spxtr** [comment]
```
$ docker ps
CONTAINER ID        IMAGE                                                       COMMAND                  CREATED             STATUS              PORTS                       NAMES
e607801eb926        gcr.io/k8s-testimages/kubekins-test:1.5-v20161109-d9a98f2   "bash -c 'cd kubernet"   17 minutes ago      Up 17 minutes                                   jovial_mcnulty
3b65f9cad9ed        kube-build:build-6034c62a06-4-v1.7.1-0                      "/rsyncd.sh"             2 weeks ago         Up 2 weeks          127.0.0.1:34147->8730/tcp   kube-rsync-6034c62a06-4-v1.7.1-0
975d88c1ae86        gcr.io/k8s-testimages/kubekins-test:1.5-v20161007-49d47fe   "bash -c 'cd kubernet"   2 weeks ago         Up 2 weeks                                      naughty_mcnulty
03210b33455e        kube-build:build-564a4f674b-4-v1.6.3-9                      "make cross"             4 weeks ago         Up 4 weeks                                      kube-build-564a4f674b-4-v1.6.3-9
```

**Comment by spxtr** [comment]
OK, they're fixed on post-submit but still broken on PR Jenkins, now because of a docker issue. Handing this off.

**Comment by fejta** [comment]
Think this might have caused problems re space issues?

**Comment by spxtr** [comment]
This should help issues with space, since it only deletes more things.

**Comment by fejta** [comment]
This still happening @rmmh?

**Comment by fejta** [comment]
/unassign @rmmh 
/assign @spxtr 

Looks like we have some agents where docker doesn't work. Will you investigate?

https://k8s-testgrid.appspot.com/maintenance#hourly&width=20
```
W0405 22:08:24.770] Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by spiffxp** [comment]
https://k8s-testgrid.appspot.com/maintenance#Summary
>3160 of 17143 (18.4%) failing in the past week; Last update: 06-30 09:11

**Comment by rmmh** [comment]
Should be fixed for now. This doesn't impact builds, since builds won't start on a node if 'docker ps' fails.

Occasionally the docker daemon becomes unresponsive on a node. We're running a very old docker (1.9.1), so there's probably been a few bug fixes since! Rebooting the associated jenkins VMs fixes it.

I have a small bash script to fix the issue, but I'm not going to bother committing it since the rate of attrition is low, it doesn't cause test failures, and we should eliminate Jenkins entirely Real Soon Now.
