### ISSUE TITLE
Kubetest doesn't work on OSX with --stage

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#10459]
When I try to run kubetest on mac with `--extract=local --stage=<some-gcs-path>` it fails to run because the [Stage() function](https://github.com/kubernetes/test-infra/blob/master/kubetest/stage.go#L70) calls [release/push-build.sh](https://github.com/kubernetes/release/blob/master/push-build.sh) and that [doesn't support OSX](https://github.com/kubernetes/release/blob/master/lib/common.sh#L27).

/kind bug
cc @krzyzacy @BenTheElder @dims

**Comment by shyamjvs** [comment]
it fails with this error:

```
readlink: illegal option -- e
usage: readlink [-n] [file ...]
```

because `readlink -f` isn't supported on OSX, but that is used [here](https://github.com/kubernetes/release/blob/master/push-build.sh#L92).

**Comment by shyamjvs** [comment]
From a high-level, there seem to be 2 options fmu:

- support OSX for release/push-build.sh script (which seems like a bunch of work)
- change kubetest to do push-build differently in case of OSX (seems easier option)

**Comment by dims** [comment]
@shyamjvs we can use the snippet from here - https://github.com/kubernetes/kubernetes/blob/master/hack/lib/init.sh#L104

`kube::readlinkdashf`

**Comment by shyamjvs** [comment]
Nice idea! I tried making such a change in the release/ scripts, but it seems like there are more dependencies going further that are incompatible (like use of `declare -A` which seems unsupported in OSX). Might be more work..

**Comment by shyamjvs** [comment]
cc @kubernetes/sig-release - for opinion

**Comment by BenTheElder** [comment]
IMO, this is a bug in k/release. --stage could really be called --push-build, it of course uses the official build push mechanism.

+1 for rewrite in go. Not sure who can own that though.

> change kubetest to do push-build differently in case of OSX (seems easier option

Why is that easier? We basically expose all the same knobs IIRC so we need to implement for Mac with matching behavior either way.

**Comment by shyamjvs** [comment]
I've taken a stab at fixing this in https://github.com/kubernetes/release/pull/657 - PTAL.
