### ISSUE TITLE
Smoke test for kops

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#1049]
@zmerlynn what do you think about the capability to have a basic e2e test for kops master?  I do not want it fired off every push, but basically, a bot command that will allow us to do a smoke test before a commit.  Not sure how ... you are the magician.  Maybe when we merge code into master?

We would need to build a custom nodeup as well, just pushing a script for that btw.

**Comment by zmerlynn** [comment]
It was next on my agenda after I resolved #1015. There's no reason not to run it on every PR - we're about to do that for every Kube PR, it makes sense to do it for every `kops` PR as well.

**Comment by chrislovecnm** [comment]
we need to talk image and nodeup, before enabling kops ;)

**Comment by zmerlynn** [comment]
@chrislovecnm: The `kops` CI build process is already rebuilding `nodeup` (we build the whole distribution), and we use that in our tests. As for image, that's harder, but if we had a `kops`-side PR builder and one were changing the default image, it would pick it up. (We don't test alternate deployment options yet; non-default are an option there, but we also need an HA build, etc.)

**Comment by zmerlynn** [comment]
This is done!
