### ISSUE TITLE
Planter Bazel rebuilds from scratch

### ISSUE THREAD

**Issue by milesmatthias** [kubernetes/test-infra#10493]
**What happened**: Each time I run a bazel command in planter, it is re-run from scratch.

**What you expected to happen**: I expected bazel to re-build only changed parts.

**How to reproduce it (as minimally and precisely as possible)**: I'm using planter to build a NodeJS image using [Bazel docker rules](https://github.com/bazelbuild/rules_docker#nodejs_image). Running `bazel run //src:image.tar` re-builds from scratch each time.

**Please provide links to example occurrences, if any**: None

**Anything else we need to know?**: I'm using planter at sha [a3314b](https://github.com/kubernetes/test-infra/commit/a3314bf11782b009b0dc20b4642db5122941953e) and planter-kubectl:0.19.2 image.

/kind bug

**Comment by BenTheElder** [comment]
planter does mount through the normal bazel cache location, it's possible to configure this to point elsewhere and break this though.

**Comment by BenTheElder** [comment]
Is the code you are building public? this might be tricky to dig into since there are a number of ways this can be configured etc.

**Comment by milesmatthias** [comment]
It's not public right now, but I can email you internally or follow up when it's OSS.
