### ISSUE TITLE
GCE PD CSI Pull test timing out at 10m even though timeout set to 20

### ISSUE THREAD

**Issue by davidz627** [kubernetes/test-infra#10542]
The timeout for this test I set to 20m:
https://github.com/kubernetes/test-infra/blob/74a6b442efb506394917e0629d9aae1b97114c15/config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml#L16

but it seems like the test is timing out on this pull after 10m causing test failures:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/211
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/211/pull-gcp-compute-persistent-disk-csi-driver-e2e/374/

Any ideas on why this might be happening?
/assign @krzyzacy 
/cc @BenTheElder @msau42 @saad-ali

**Comment by krzyzacy** [comment]
go test has a default 10min timeout :-)
/unassign

**Comment by davidz627** [comment]
I see, will fix on driver side, thanks!
/close
