### ISSUE TITLE
podutils: Add more verbose metadata 

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#10544]
**What would you like to be added**:
podutils jobs don't provide much in the way of metadata details in either their started or finished json files.

bootstrap + scenario example with metadata:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/72177/pull-kubernetes-verify/116969/finished.json

podutils example with very little metadata:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/72177/pull-kubernetes-typecheck/34990/finished.json

**Why is this needed**:
Of particular value would be the repo commits (what is HEAD of PR branch, and what is HEAD of base branch), and the infra-commit.

/kind feature
/area prow prow/pod-utilities

**Comment by cblecker** [comment]
cc: @BenTheElder @krzyzacy @stevekuznetsov

**Comment by BenTheElder** [comment]
@krzyzacy was looking into this. I've definitely held off migrating release blocking CI in particular while we sort this out. What's the current state Sen?

**Comment by spiffxp** [comment]
/milestone v1.14
hopefully?

ref: https://github.com/kubernetes/test-infra/issues/7364 (sortof a dupe?) and https://github.com/kubernetes/test-infra/issues/3412 (why not doc the metadata while we're at it)

**Comment by stevekuznetsov** [comment]
Yeah I would love to see a straightforward doc of what tools use what fields ... from my external viewpoint the metadata is a huge mess of legacy right now...

**Comment by stevekuznetsov** [comment]
And nobody ever helped me understand it two years ago in #3412

**Comment by krzyzacy** [comment]
I think two things:
- gubernator & spyglass will display the metadata. 
- you can also set custom column headers in testgrid from the metadata you have. 

You can put whatever fields you want there, and it is not a must-have today.

**Comment by krzyzacy** [comment]
Oh didn't read the issue body - we should have all the repo info in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/72529/pull-kubernetes-typecheck/35614/clone-records.json, maybe we can clean that up a little bit and display some info from there? @stevekuznetsov

**Comment by BenTheElder** [comment]
discussed a possible path forward on this today: we can put the resolved refs after checkout into the clone-records.json, thread here: https://kubernetes.slack.com/archives/CDECRSC5U/p1547584185236700

@cjwagner, thoughts on this? @stevekuznetsov seems OK with it, and I spoke to @krzyzacy about it.

**Comment by cjwagner** [comment]
👍
Would we then have `initupload` include the resolved refs from clone-records.json in started.json? Otherwise consumers will need to read clone-records.json in addition to started.json and finished.json.

**Comment by krzyzacy** [comment]
I'll backfill more data for now, and resolve https://github.com/kubernetes/test-infra/issues/10359 separately.

**Comment by krzyzacy** [comment]
Most of the metadata here is now backfilled in started.json, we still need to make downstream consume these. Maybe worth a separate issue.

/close
