### ISSUE TITLE
Prow issue: Wrong link in comment

### ISSUE THREAD

**Issue by quentinmit** [kubernetes/test-infra#10547]
The comment that @k8s-ci-robot leaves in response to `/close` on issues says:

> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).

But a) this comment was not left on a PR, and b) the link does not document `/close` (or `/reopen`). Perhaps there is a different link that documents issue-related commands?

**Comment by cjwagner** [comment]
> WDYT about passing in the Deck base URL for hook?

SGTM, but we might want to make it a config field instead so that it is easy for any Prow component to generate links to Deck (if it is deployed). That would be helpful for `tide` and reporting clients in `crier` in addition to `hook`.

**Comment by stevekuznetsov** [comment]
@midnightconman didn't you solve this recently?

**Comment by midnightconman** [comment]
What I committed should easily be enhanced to support this: https://github.com/kubernetes/test-infra/pull/11665

**Comment by stevekuznetsov** [comment]
@midnightconman do you want to take this issue on?

**Comment by midnightconman** [comment]
Sure :smile:

/assign
