### ISSUE TITLE
verify-owners: ensure every user is an org collaborator

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#10553]
https://github.com/kubernetes/kubernetes/issues/50048 and https://github.com/kubernetes/contrib/issues/2713 are issues about ensuring that every user in an OWNERS or OWNERS_ALIASES file is an org member or outside collaborator.

Rather than doing a manual scan occasionally, we could add this check to the `verify-owners` plugin and automate it.

If this sounds good, I can work on it.

/cc @cblecker @spiffxp @dims @cjwagner @BenTheElder 

/sig contributor-experience
/area prow
/kind feature

**Comment by ping035627** [comment]
I think it's a good idea! Thanks.

**Comment by stevekuznetsov** [comment]
This would potentially open the door to abuse so we'd have to cap the number of people we check when someone commits an OWNERS file, but otherwise sounds reasonable.

**Comment by cjwagner** [comment]
Capping the number of people we check wouldn't really be a barrier to abuse. It is still possible to just repeatedly push new commits to keep triggering validation. This is true for most all of our automation unfortunately.
A cap would still be good to avoid using all our tokens if/when big OWNERS file refactors happen, though.

**Comment by nikhita** [comment]
I couldn't get this working on a private repo, but wanted to test here just to make sure I'm not imagining this category for `/pony`...

/pony lgtm

**Comment by nikhita** [comment]
Just for the record - this was fixed in https://github.com/kubernetes/test-infra/pull/10741. :)

**Comment by Katharine** [comment]
@spiffxp If you can explain the difference between an lgtm pony and an approval pony, I will make `/pony approve` work. ;)

**Comment by matthyx** [comment]
Here too: https://github.com/kubernetes/test-infra/issues/8838#issuecomment-436075246

**Comment by matthyx** [comment]
@nikhita are you working on that issue?

**Comment by nikhita** [comment]
Created PR: https://github.com/kubernetes/test-infra/pull/12297

**Comment by nikhita** [comment]
/reopen

This was reverted in https://github.com/kubernetes/test-infra/pull/12402.

Created https://github.com/kubernetes/test-infra/pull/12460 to fix it and add the feature again.
