### ISSUE TITLE
Gke ci job doesn't clean up cluster when fails

### ISSUE THREAD

**Issue by krzysied** [kubernetes/test-infra#10561]
**What happened**:
Gke ci job failed (ci-kubernetes-e2e-gke-large-performance-regional), gke cluster remained. This is blocking resources, causing other ci jobs to fail.

**What you expected to happen**:
Job should always do the resource cleanup.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
[ci-kubernetes-e2e-gke-large-performance-regional/151/build-log.txt](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-large-performance-regional/151/build-log.txt)

**Anything else we need to know?**:

/kind bug
/sig scalability

**Comment by krzysied** [comment]
IIUC the problem has fallowing steps:
1. Creating cluster takes more than 30m.
2. Cluster creation operation (client side) times out. Script handles the timeout as an error.
3. Script tries to remove cluster. Operation is unsuccessful due to cluster still trying to be created.
4. Script finishes without cleaning up the cluster.

**Comment by wojtek-t** [comment]
I looked into internal GKE logs, and increasing timeout wouldn't help.
Creation of those cluster failed after almost two hours in the end.
That should be investigated separately (I will file internal bug for it), 

but here, the only possible solution to fix that for the future is:
- change the logic for deletion cluster to:
(1) check if error was "operation in progress"
(2) if so, retry

We won't be able to solve that differently.

**Comment by wojtek-t** [comment]
The two things that need to be fixed in Down() function:
https://github.com/kubernetes/test-infra/blob/master/kubetest/gke.go#L581
(1) delete clusters should be retried if the returned error was "operation in flight)
(2) the errors should probably be ignored if these were "not found" errors

@krzysied - will you be able to do that?

**Comment by BenTheElder** [comment]
There are no more GKE CI jobs in this repo.
