### ISSUE TITLE
Use a more semantic name for ProwJobs

### ISSUE THREAD

**Issue by fiunchinho** [kubernetes/test-infra#10564]
**What would you like to be added**:
The hook process receives the Github webhooks and uses the `X-GitHub-Delivery` header from the web hook HTTP request as identifier for the ProwJob that will be created. The name of the ProwJob will be re-used as the name of the job when using knative-agent.

It would be nice to have a more semantic name that helps debugging and identifying which repository triggered a ProwJob without having to inspect the ProwJob itself. Using a different schema for the name that contains not only a random generated string (like the `X-GitHub-Delivery` header), but also the repository and branch names, could help identify which one is the ProwJob that you are interested in, when listing ProwJobs.

**Why is this needed**:
It's hard to identify which ProwJob is related with my build, so it's hard to debug and to know what's going on. Deriving the name from the repository would improve the developer experience.

/kind feature

**Comment by fiunchinho** [comment]
I could fill a PR to fix this, but I want to hear your feedback first. Thanks

**Comment by BenTheElder** [comment]
Hmm? ProwJobs are all named with a UUID, I don't believe the GitHub event GUID is being used for that, only for metrics / logging.

We do however add labels to the ProwJobs related to their source. This is also exposed in the pod env.

**Comment by jglick** [comment]
Yes you can obtain the source information by looking up for example the labels `prow.k8s.io/refs.org` + `prow.k8s.io/refs.repo` + `prow.k8s.io/refs.pull`, which are usable in label selector queries; or by examining the `.spec.refs` or `.spec.build_spec.template.env` once a particular `ProwJob` has been selected for inspection. The point is that the `.metadata.name` is completely worthless for interactively diagnosing issues; for example `kubectl get prowjobs.prow.k8s.io` produces output whose only meaningful field is the age. A `name` which includes for example a sanitized version of the org + repo + branch/PR + `BUILD_ID` would make for far more comfortable debugging.

**Comment by BenTheElder** [comment]
`describe` or `get -o yaml` will produce more useful output, prowjobs are not always created from a repo so I don't think we want to switch the name generation just for that part. The names are intentionally UUIDs to be cross referenced with other data (like using the label selectors). Note that the ProwJob UUID should match the pod name.

/cc @cjwagner @stevekuznetsov

**Comment by stevekuznetsov** [comment]
I think we can also just add custom columns to the CRD so `kubectl get` is not useless:

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns

I'll tackle that

/assign
