### ISSUE TITLE
Prow suggests approver from wrong OWNERS file

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes/test-infra#10575]
**What happened**:
Created a PR where `approve` plugin [suggested an approver](https://github.com/kubernetes/cloud-provider-openstack/pull/416#issuecomment-450766190) from [`cloud-provider-openstack/OWNERS`](https://github.com/kubernetes/cloud-provider-openstack/blob/master/OWNERS), not [`cloud-provider-openstack/pkg/ingress/OWNERS`](https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/ingress/OWNERS), but correctly referenced the `cloud-provider-openstack/pkg/ingress/OWNERS` file in the _Needs approval from an approver in each of these files_ section.

**What you expected to happen**:
`approve` plugin suggests approvers from the correct OWNERS file

**How to reproduce it (as minimally and precisely as possible)**:
Create a PR with changes in _cloud-provider-openstack/pkg/ingress/_. 

Due to overlapping users in both `cloud-provider-openstack/OWNERS`  and `cloud-provider-openstack/pkg/ingress/OWNERS` this issue may not manifest in all cases

**Please provide links to example occurrences, if any**:
https://github.com/kubernetes/cloud-provider-openstack/pull/417#issuecomment-450775295
https://github.com/kubernetes/cloud-provider-openstack/pull/416#issuecomment-450766190

**Anything else we need to know?**:
In both linked instances it suggested me (@chaosaffe) as the approver as I am in `cloud-provider-openstack/OWNERS`... Otherwise I probably wouldn't have noticed the error

/kind bug

**Comment by stevekuznetsov** [comment]
I mean it's technically correct -- since you're an approver in the top-level, you can approve it as well. I wonder if we did that because we wanted to suggest an approver that wasn't already reviewing? I can't remember how that code went.

/area prow/hook
/cc @cjwagner

**Comment by chaosaffe** [comment]
I misunderstood the priorities of the files. I thought an OWNERS higher in the tree excluded OWNERS lower in the tree.
My apologies for the inconvenience, and thank you guys for all your amazing work! You help make working on Kubernetes a true joy!

**Comment by ixdy** [comment]
@chaosaffe FYI you can also set a `no_parent_owners` option if you'd like to exclude top-level owners, but it's `false` by default. https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners
