### ISSUE TITLE
Deck PR Status Dashboard doesn't match org-based Tide queries

### ISSUE THREAD

**Issue by chaosaffe** [kubernetes/test-infra#10574]
**What happened**:
PR's made in repositories where they are matched by `orgs`, i.e. [kubernetes-sigs](https://github.com/kubernetes-sigs/), show in the Deck [PR Status](https://prow.k8s.io/pr) dashboard with _No Tide query found_ despite having a configured [Tide query](https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L332-L395)

**What you expected to happen**:
Deck PR Status dashboard correctly matches org Tide query and shows label requirements

**How to reproduce it (as minimally and precisely as possible)**:
Use the PR Status dashboard with the query `is:pr state:open repo:kubernetes-sigs/cluster-api`

**Please provide links to example occurrences, if any**:
[PR Status dashboard for above query](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20repo%3Akubernetes-sigs%2Fcluster-api)

**Anything else we need to know?**:
After reviewing the relevant code and stepping through in-browser, it appears that the source data is correct, but orgs are not being matched by the [isMatched function](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/static/pr/pr.ts#L67-L70), which is transpiled to
```javascript
if (!(this.repos && -1 !== this.repos.indexOf(e.Repository.NameWithOwner) || this.orgs && -1 !== this.orgs.indexOf(e.Repository.Owner.Login) && this.excludedRepos && -1 === this.excludedRepos.indexOf(e.Repository.NameWithOwner)))
                return !1;
```
_[Source](https://prow.k8s.io/static/pr_bundle.min.js)_

/cc @cjwagner @Katharine 

/kind bug

**Comment by Katharine** [comment]
Fixed the mistake. Thanks for the report, and for the investigation!
