### ISSUE TITLE
Cannot merge PR

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/test-infra#106]
My PR #105 cannot be merged, because of some problems with CLA. Despite I work at google, bot added CLA:NO label, and manual modification of labels didn't make my PR merge-able.

CC @gmarek

**Comment by jszczepkowski** [comment]
CC @eparis

**Comment by eparis** [comment]
`cla: human-approved` is respected by the submit queue bot, but the google (internal) cla-bot goes not pay attention to that label. And the cla-bot is a complete black hole to me. I've yet to figure out who at google 'owns' that...

**Comment by ixdy** [comment]
This was working correctly. The commit was signed with an invalid email address.
