### ISSUE TITLE
No build log when pull jobs time out

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#1061]
Compare

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32577/pull-kubernetes-node-e2e/4945/

and

(jenkins) pull-kubernetes-node-e2e/4945/console

**Comment by krzyzacy** [comment]
cc @Random-Liu

**Comment by rmmh** [comment]
Does bootstrap.py not catch the SIGTERM and upload the logs? This used to work because Jenkins would upload finished.json after the build timed out, but if it times out like this it won't do the right thing.

**Comment by fejta** [comment]
Is this fixed?

**Comment by krzyzacy** [comment]
Did not check yet.. It should according to the logic, but need to find a timed-out build to verify.

**Comment by krzyzacy** [comment]
Not on Jenkins timeout :-(

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46823/pull-kubernetes-e2e-gce-etcd3/35722/ we definitely get logs :-)
