### ISSUE TITLE
k8s-ci-robot not automatically added as a participant to PR

### ISSUE THREAD

**Issue by tareks** [kubernetes/test-infra#10629]
**What happened**:
I might be missing something basic here, but a PR was created (https://github.com/helm/charts/pull/10237) but k8s-ci-robot did not seem to autojoin to annotate it.

**What you expected to happen**:
k8s-ci-robot should have be added as a participant and auto commented. It should have also added reviewers and suggested approvers.

**How to reproduce it (as minimally and precisely as possible)**:
Create a PR into the helm/charts repository. Note that this may be a one off.

**Please provide links to example occurrences, if any**:
https://github.com/helm/charts/pull/10237

**Anything else we need to know?**:
Please advise if the recommendation is to recreate the PR or if there's a way to get the robot added to an existing PR. Perhaps there's something I missed in the PR itself?

**Comment by tareks** [comment]
Note that this may not be a bug, but I haven't found anything in the docs yet that may indicate what I've missed out on..

**Comment by cjwagner** [comment]
This is likely a result of GitHub failing to deliver the webhook for the PR `open` event to Prow.
We see this every once in a while. If you are an admin of the `helm/charts` repo you can inspect the webhook delivery log and confirm that the webhook delivery failed.

We've tried to design Prow's plugins to have work-arounds for dropped webhooks in case they occur. Closing and reopening the PR should retrigger all the actions that should have run when the PR was opened.

**Comment by tareks** [comment]
Awesome, thanks for the tip. Closing and re-opening the PR seems to have brought the bot back to life.

Cheers!
