### ISSUE TITLE
Add documentation for the triage tool

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/test-infra#10659]
**What would you like to be added**:
More detailed documentation for the triage tool:

- where it's deployed
- how to use it
- how it integrates with other k8s tooling
- how to contribute to it

**Why is this needed**:
It would help contributors discover and be productive with [triage](go.k8s.io/triage) as part of their k8s CI toolkit.

**Comment by spiffxp** [comment]
/milestone v1.16
Worth addressing if someone wants to rewrite triage (ref: https://github.com/kubernetes/test-infra/issues/12508)
