### ISSUE TITLE
Update entrypoint/sidecar to handle build steps

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#10666]
Each Knative-build step becomes an init container. These run in sequence. As soon as one fails, pod execution halts. There is no way to define a build that includes the prow sidecar as a sidecar -- it becomes the last step. Therefore I need to ensure that:
* Once a step fails, all subsequent steps do nothing, but
* Regardless, the build runs every step so we get to the sidecar step at the end which uploads logs.

In order to accomplish this I plan to change:
* Entrypoint to decide whether it should run the step or skip it (based on whether a previous step failed)
  - If `--previous-marker` is non empty and the value is non-zero, then write 0 to marker-file and skipped to process-log
  - Otherwise run as normal
* prow/pod-utils/options to include an optional step name (defaulting to args when not set)
* Sidecar to accept a list of prow/pod-utils/options rather than just one
  - Wait for every marker-file rather than just the first one
  - Abort if any marker file is 130, else fail if any is non zero, else success
  - Combine all the process logs together into build-log.txt, while still uploading the logs for each step individually
  - Add a junit file that specifies info about each step (name, did it pass?, how long did it take?)
* Build controller
  - Replaces the command for each step with entrypoint and its options
  - Adds a sidecar step to the end, with all the entrypoint options

/assign

**Comment by stevekuznetsov** [comment]
This seems reasonable enough to me. For multiple containers, though there are wierd concurrency issues that come up -- your design evades those by chaining `init` containers

**Comment by fejta** [comment]
**Ideally** I wouldn't have to be chaining init containers :grin:

**Comment by stevekuznetsov** [comment]
Why not? If you have a set of serial steps, that's the best-practice approach in k8s right now for it
