### ISSUE TITLE
Prow: Run service sidecar for job tests

### ISSUE THREAD

**Issue by calvinmorrow** [kubernetes/test-infra#10665]
Looking into using Prow instead of a separate CI system we use today and hitting several blockers.

Currently several of our existing CI processes use some sort of "service" container for API or database testing.  IE: We run postgresql as a second container in the same pod or other services that emulate various CRUD APIs our applications use.  Even our existing build process usually runs DinD as a "sidecar" and then uses a standard Docker image for the "main" container to `docker build` against.  Prow is (limited?) only allowed to use a single container for each ProwJob and as such, our multi-container jobs have no endpoint to connect to.

Is there any particular workaround/way to run several containers simultaneously to achieve something similar to what we do today?  I've seen references in issues etc. of multi-container pods but I believe that's possibly just roadmap.
 
Are all ProwJobs currently self-contained in all the projects that use them?

On a related note, we ran into issues trying to decorate our pods with the intention of getting the source code checked out so we could run our own build process.  It wasn't clear that there's (as far as I can tell) an assume reliance on GKE for uploading logs etc. that we errored over before giving up and going down a different route (using Knative to run builds).

**Comment by stevekuznetsov** [comment]
@calvinmorrow sorry! This fell through the cracks

**Comment by stevekuznetsov** [comment]
Yes, right now we do not support mutli-container jobs. There is an open issue https://github.com/kubernetes/test-infra/issues/10946 to support using the cloning utility without the GCS bits.
