### ISSUE TITLE
Remove run_after_success support from prowjob

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#10680]
We will remove `run_after_success` in a future version of prow. These do not work correctly in a wide variety of edge cases, and we do not want/intent to ever support them.

In the future prow will support scheduling a single prowjob and waiting for it to complete, and this will result in scheduling a single pod/build/pipeline and waiting for it to complete.

People who need to schedule a tree of jobs should create a job of `knative-build` or in the near future `knative-pipeline` https://github.com/knative/build-pipeline or some other strategy.

/assign
/cc @stevekuznetsov @cjwagner

**Comment by stevekuznetsov** [comment]
;)

**Comment by stevekuznetsov** [comment]
I deserve the privilege after the last three weeks :D

**Comment by krzyzacy** [comment]
We still need to handle un-migrated jobs as they will just suddenly stop working

**Comment by stevekuznetsov** [comment]
This got implemented
/close
