### ISSUE TITLE
Gubernator logs for federation control plane components

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/test-infra#1069]
Gubernator's log viewer is awesome and alleviates many of the pains involved in debugging. Federation control plane components don't appear in those logs though. Add them to the logs list.

**Comment by fejta** [comment]
/unassign @rmmh 
/assign @madhusudancs 

Can you be more specific about this request?

The primary page only shows info from build-log.txt. The artifacts link shows all artifacts that were uploaded to gcs.

**Comment by madhusudancs** [comment]
> The primary page only shows info from build-log.txt. The artifacts link shows all artifacts that were uploaded to gcs.

I meant the logs uploaded to GCS and available in the artifacts/ directory. 

@perotinus fixed this in PR #2231 and https://github.com/kubernetes/kubernetes/pull/43028.
