### ISSUE TITLE
Account Lifecycle Management for AWS

### ISSUE THREAD

**Issue by liztio** [kubernetes/test-infra#10693]
**What would you like to be added**:

gcloud-like lifecycle management for AWS accounts. 

Proposed flow:
1. Job checks out clean AWS account from Boskos
2. Job does something with AWS account
3. Job checks account back in
5. (Optional) AWS account credentials reset to prevent long-running jobs from interfering with each othe
4. Boskos runs [awsweeper](https://github.com/cloudetc/awsweeper#supported-resources) or similar to make dirty AWS account clean

**Why is this needed**:

[cluster-lifecycle-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws) (hereafter CAPA) wants E2E jobs that test provisioning clusters on AWS. Unlike kops, we do not have a detailed log of what will be created by these jobs.

**Alternatives considered**:

* Jobs clean up their own tagged assets
    * asset tagging doesn't always happen at creation time
    * coding mistakes (this is CI!) could leak untagged assets
* Destroy whole accounts
    * destroying AWS accounts can take O(weeks)
* Destroying VPC associated with account
    * not all resources (e.g. SSH keypairs)
    * destroying VPC is difficult (have to manage dependencies)
* Use project-like container as on Azure and GCE
    * AWS doesn't have this feature :(
* Have CAPA keep a local log of assets created
    * coding mistakes could still leak resources
    * CAPA doesn't do this at the moment, would need to be net-new code
* Have CAPA log to S3 as Kops does
    * Would need to reconcile local CRD state with S3
    * still net-new code
* Have CAPA use cloud formation
    * Would require substantial rewrite of CAPA
    * deleting cloudformation stacks can be error prone, e.g. dependent resources may require retries

**Comment by timothysc** [comment]
> Boskos runs awsweeper or similar to make dirty AWS account clean 

@liztio - Any idea on the possible scaling limits here?
 
1. How many (sub)accounts can be created in time (T)?
2. How long does it take to clean up in time(T)? 
3. How long does it take to garbage collect failed deployments in time (T) 
...

**Comment by detiber** [comment]
> @timothysc
> 
> > How many (sub)accounts can be created in time (T)?
> 
> this is based on # of AWS accounts CNCF has available, as I understand it. I don't know how many there are.
> 

It *should* be possible to have subaccounts created if they have configured an Organization in the account, which would streamline the initial account creation: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_create.html

That said, I don't see a streamlined way of deleting accounts through an Organization, only closing which would leave a *ton* of closed accounts laying around for some indeterminate amount of time until they are garbage collected and will count against quota: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_close.html

**Comment by BenTheElder** [comment]
cc @krzyzacy 
also FYI to @justinsb

**Comment by liztio** [comment]
Some updates on tools. My initial thought was to use [awsweeper](https://github.com/kubernetes/test-infra/tree/master/maintenance/aws-janitor). It's pretty fit for purpose, but unfortunately vendoring at adds almost a million lines of code(!) because it pulls in all of Terraform. That's obviously not ideal.

I also considered [grafiti](https://github.com/coreos/grafiti). But That's a lot of complexity we don't really need: it's designed to clean up older resources that aren't being used, so it uses a mark-and-sweep methodology. We just want to delete _everything_, so that's just needless overhead.

My current plan is to rehabilitate our existing [aws-janitor](https://github.com/kubernetes/test-infra/tree/master/maintenance/aws-janitor). It's currently designed to delete resources based on a S3 blob, but I think switching that to "everything in an account" shouldn't be too hard. One unknown: It was disabled as a job in the past because of erroring out. Still trying to figure out what those are. Also need to know if I can replace the existing job all together or if I need to refactor in parallel.

**Comment by liztio** [comment]
Work today: 

Broke up monolithic AWS janitor into modules, so I can use it with boskos (#10707). That allows me to do a rough sketch of how the cleaner will work (#10713)

**Comment by liztio** [comment]
# Status Update

- [x] Generalize existing aws-janitor codebase to support cleaning arbitrary objects (#10707)
- [x] Add methods to list all objects in an account (#10908)
- [ ] Add client to poll Boskos for dirty accounts [based on existing GCE Janitor code](https://github.com/kubernetes/test-infra/blob/master/boskos/janitor/janitor.go#L100-L131)
- [ ] [Dockerfile for new cleaner](https://github.com/kubernetes/test-infra/blob/795cceb4ce411fa43933fb6534c208a6d470e1ab/boskos/janitor/Dockerfile)
- [ ] Deploy the Janitor
  - See [janitors.yam](https://github.com/kubernetes/test-infra/blob/a9c4e71ebcc22a353cb9032047ddec8f19c2d2f7/config/jobs/kubernetes/test-infra/janitors.yaml)
  - And [deployment.yaml](https://github.com/kubernetes/test-infra/blob/bc0ec4c7dde5dbb678eb1dc8c11c68e90a78d6a8/boskos/janitor/deployment.yaml)
- [ ] Add Boskos AWS resources
  - See [slack conversation](https://kubernetes.slack.com/archives/C09QZ4DQB/p1547148543350200) on who to talk to
- [ ] Add Boskos [checkout](https://github.com/kubernetes/test-infra/tree/master/boskos#post-acquire) / [checkin](https://github.com/kubernetes/test-infra/tree/master/boskos#post-release) to cluster-api-provider-aws [e2e jobs](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/scripts/ci-bazel-e2e.sh)

**Comment by justinsb** [comment]
The janitor issue should have been fixed in https://github.com/kubernetes/test-infra/pull/10619

I think using multiple accounts is a nice idea.  We should make sure that new accounts have enough quota - sometimes they can only launch a handful of t2 instances IIRC.

Note that kops doesn't have a detailed log of what is created.  Well, we can figure it out, but janitor doesn't use it - by design - it's designed to pick up anything that kops cleanup missed.  (For example, I think I've observed resources leaking when the e2e tests time out).

**Comment by rdodev** [comment]
I'll be looking at tasks which can be do in parallel here. Will probably start with creation of AWS accounts.

**Comment by liztio** [comment]
currently blocked on AWS credits for the CI accounts (https://kubernetes.slack.com/archives/C09QZ4DQB/p1547153577371900?thread_ts=1547148543.350200&cid=C09QZ4DQB)

**Comment by akutz** [comment]
Hi @liztio,

I'm trying to come up to speed on the proposed design and workflow. I have a few questions:

## q1
> 1. Job checks out clean AWS account from Boskos

Are these shared, repurposed accounts? What does _clean_ mean? That an account, perhaps used in a previous CI run, has been placed back into the pool, scrubbed of resources, and ready for re-use? Based on what you've discussed above, this seems to be correct. It looks like you found the creation of net-new sub-accounts to be too costly due to the time it takes to close such accounts and the reclamation of their associated resources.

## q2
It appears kind is being used to deploy the Kubernetes cluster on which Boskos and the CAPA build being tested are both deployed?

## q3
> Boskos runs [awsweeper](https://github.com/cloudetc/awsweeper#supported-resources) or similar to make dirty AWS account clean

I was under the impression that Boskos is basically an opinionated key/value store being used to track the assets created as part of CAPA e2e jobs. What part of Boskos is responsible for triggering `awsweeper`? Is this a pluggable part of Boskos? 

I think I need to better understand the part Boskos is playing in the overall workflow. I thought I understood it to be a sidecar registry -- a manifest where notes are recorded before or after each call that would mutate resources in some way. But as I read the above discussions and links, it seems like Boskos may actually be involved in these calls in some way -- as to say it is Boskos that is responsible for, as an example, creating an AWS instance or storage volume. This is obviously incorrect as I do not believe Boskos is part of CAPA, so it any record of CAPA-generated resources must be occurring outside of CAPA. I'm just confused as to where that connection is -- where the injection points are in the workflow that record what resources have been/will be created by CAPA and recorded into Boskos.

## q4
> My initial thought was to use [awsweeper](https://github.com/kubernetes/test-infra/tree/master/maintenance/aws-janitor). I

Have you considered Go modules in order to depend on the janitor without needing to vendor it? Obviously vendoring it is the only way to ensure the code can be built in an air gapped scenario, but Go modules does make building with dependencies easier than before.

Anyway, thank you @liztio. I'm sure I'll have more questions, but hopefully this will be a good starting point for understanding how completely out of my depth I am :)

**Comment by liztio** [comment]
> Hi @liztio,
> 
> I'm trying to come up to speed on the proposed design and workflow. I have a few questions:
> 
> ## q1
> > 1. Job checks out clean AWS account from Boskos
> 
> Are these shared, repurposed accounts? What does _clean_ mean? That an account, perhaps used in a previous CI run, has been placed back into the pool, scrubbed of resources, and ready for re-use? Based on what you've discussed above, this seems to be correct. It looks like you found the creation of net-new sub-accounts to be too costly due to the time it takes to close such accounts and the reclamation of their associated resources.

Your assumption is correct. Provisioning a new AWS account is a manual process, not an automated one. And cleaning up an AWS account takes on order of _months_ before the resources are released. It simply wasn't feasible. We will clean with the Janitor as best we can, and assume after that that the resources are "clean."

> ## q2
> It appears kind is being used to deploy the Kubernetes cluster on which Boskos and the CAPA build being tested are both deployed?

Now this is where things get extra confusing :) Boskos is deployed in the same cluster that _prow_ runs in. [Prow](https://github.com/kubernetes/test-infra/tree/master/prow) is Kubernetes' CI system. Individual CI jobs run as pods on this cluster. Boskos is already deployed and available in this cluster (as I understand it). Inside this pod we've been given by Prow, we then run kind to deploy docker. 

> ## q3
> > Boskos runs [awsweeper](https://github.com/cloudetc/awsweeper#supported-resources) or similar to make dirty AWS account clean
> 
> I was under the impression that Boskos is basically an opinionated key/value store being used to track the assets created as part of CAPA e2e jobs. What part of Boskos is responsible for triggering `awsweeper`? Is this a pluggable part of Boskos?

This was poor wording on my part. Boskos doesn't trigger anything. The janitor runs in a container elsewhere in the cluster, and periodically polls Boskos for any accounts that might be dirty. If nothing is available, the janitor sleeps.

> I think I need to better understand the part Boskos is playing in the overall workflow. I thought I understood it to be a sidecar registry -- a manifest where notes are recorded before or after each call that would mutate resources in some way. But as I read the above discussions and links, it seems like Boskos may actually be involved in these calls in some way -- as to say it is Boskos that is responsible for, as an example, creating an AWS instance or storage volume. This is obviously incorrect as I do not believe Boskos is part of CAPA, so it any record of CAPA-generated resources must be occurring outside of CAPA. I'm just confused as to where that connection is -- where the injection points are in the workflow that record what resources have been/will be created by CAPA and recorded into Boskos.

Yeah, this is my bad. Boskos is a service that is already deployed and running within Kubernetes' CI infrastructure that we will be leveraging. The injection point is simply that the prow jobs will have access to Boskos while they are running.

> ## q4
> > My initial thought was to use [awsweeper](https://github.com/kubernetes/test-infra/tree/master/maintenance/aws-janitor). I
> 
> Have you considered Go modules in order to depend on the janitor without needing to vendor it? Obviously vendoring it is the only way to ensure the code can be built in an air gapped scenario, but Go modules does make building with dependencies easier than before.

I don't really know anything about Go modules, if I'm honest. `test-infra` is a large repository owned by another team, and I don't know that I have the political capital to switch over to go modules - especially since aiui Kubernetes is fundamentally incompatible with the way go modules work. 

> Anyway, thank you @liztio. I'm sure I'll have more questions, but hopefully this will be a good starting point for understanding how completely out of my depth I am :)

**Comment by akutz** [comment]
Hi @liztio,

Thank you for your answers. They are most helpful! I think the largest misconception that I had was that you were deploying a cluster with Kind and then Boskos to it (as well as the CAPA bits being tested). I did not realize that Boskos was one of the components running on the singular Prow instance. I of course realized it was owned by test-infra, but I thought it was something some people used, but not necessarily a service running on Prow. Things are starting to make a lot more sense now :)

**Comment by akutz** [comment]
Hi @liztio,

> I did not realize that Boskos was one of the components running on the singular Prow instance.

I think there is an opportunity to update the test-infra docs to reflect that Boskos is an available components. I did a quick search on the repo, and Boskos is only mentioned twice in documentation outside of the `/boskos` sub directory:

1. [`kubetest` and dynamic project selection](https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md#dynamic-project-selection)
2. [The `boskos` label](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md#area/boskos)

There are also only two-three places Boskos is mentioned in YAML manifests in test-infra. 

My point is basically that while Boskos is a service available to jobs running on the singular Prow instance, one would be hard-pressed to know this from reading the documentation.

@spiffxp, am I missing something in the test-infra docs where Boskos is called out? It isn't in the [architecture diagram](https://github.com/kubernetes/test-infra/blob/master/docs/architecture.svg), but I'm not even sure if it should be. I'm just curious as to how one should learn about Boskos and its role in Prow jobs. If that onramp material is missing, maybe I could help create some of that as I'm currently attempting to familiarize myself with Boskos.

**Comment by spiffxp** [comment]
>Boskos is deployed in the same cluster that _prow_ runs in. [Prow](https://github.com/kubernetes/test-infra/tree/master/prow) is Kubernetes' CI system. Individual CI jobs run as pods on this cluster.

One nit: almost all prow jobs run as pods in a separate build cluster.  This provides an extra security boundary to prevent unintended access to certain secrets.

>@spiffxp, am I missing something in the test-infra docs where Boskos is called out? It isn't in the [architecture diagram](https://github.com/kubernetes/test-infra/blob/master/docs/architecture.svg), but I'm not even sure if it should be

The arch diagram is woefully out of date.  I tried walking through an update of how things are wired together at [SIG Testing Intro KubeCon Seattle 2018](https://www.youtube.com/watch?v=7-_O41W3FRU).  I never got as far as refining and crystallizing it into something I was comfortable calling a document.  We would be thrilled if you want to take a crack at that.

Boskos is not an essential part of prow, nor is it directly related to prow jobs, it's just something we needed for some of our e2e jobs to operate at this project's scale.  This is why it's mentioned in kubetest's docs.

**Comment by spiffxp** [comment]
/milestone clear
/assign @detiber @justinsb 
I think some of this work has been completed but it's unclear to me how much.  https://github.com/kubernetes/test-infra/pull/12538 makes me think there is more to do, can we get some help describing where we are and where we need to go?

**Comment by detiber** [comment]
@spiffxp That is correct, the AWS users which were provided were all provisioned from the same account instead of separate accounts. I know @justinsb was working to follow up with @idvoretskyi to resolve it.

**Comment by detiber** [comment]
I believe we can call this issue complete now.
/close
