### ISSUE TITLE
Unify (or remove?) started|finished|metadata.json data structures

### ISSUE THREAD

**Issue by ibzib** [kubernetes/test-infra#10699]
**What would you like to be ~added~ removed**:
Currently, the struct used to read/write `started|finished|metadata.json` is re-defined in _many_ places:
- https://github.com/ibzib/test-infra/blob/6c004fe3dd3e36612bbeb860193bd980440518cc/prow/sidecar/run.go#L176-L188
- https://github.com/ibzib/test-infra/blob/5b57a7ea791e09620380eae53cd51870390ecf2f/prow/initupload/run.go#L93-L102
- https://github.com/ibzib/test-infra/blob/5b57a7ea791e09620380eae53cd51870390ecf2f/testgrid/cmd/updater/main.go#L117-L142
- https://github.com/ibzib/test-infra/blob/fb15579aa707be08f3675b1f786ad81f6740141b/prow/deck/jobs/metadata.go#L19-L46

We at least need to DRY the Go definitions above. Alternatively, we could remove these special structs altogether and just upload pod specs for pod util jobs, but downstream consumers would probably have to support both sources if that's the case.

**Why is this needed**:
Having this many sources of truth makes maintenance unduly cumbersome (#10681, #10683).

/cc @stevekuznetsov @krzyzacy

**Comment by ibzib** [comment]
cf #3412

**Comment by krzyzacy** [comment]
following up https://github.com/kubernetes/test-infra/pull/10683#issuecomment-453260639:

I think derive everything from the podspec can be a good long term solution, just need to kill bootstrap first :-) Until that happens I think we still need to support backwards compatibility for all existing started/finished.json, and figure out who else is depending on these data. (It's more than our tools, there are other people who's parsing started/finished.json afaik... cc @wonderfly ), and of course we need to patch gubernator/kettle/testgrid/... which is non-trivial.

Also can artifact-uploader handle actual artifacts? Or we'll have both sidecar and a controller does gcsupload?

cc @cjwagner @fejta

**Comment by wonderfly** [comment]
If we are talking about unifying the go (re)definitions of these structs then I have no problem. As long as the json schema doesn't change in a backward incompatible way my code should be fine.
