### ISSUE TITLE
Write a GitHub Issue Gatherer to link issues to tests in TestGrid

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#10701]
With issue_state.proto out, it's now possible to write a tool that crawls GitHub issues for issues that mention a failing test, and write the info about that issue such that TestGrid can read it! (Or rather, it's ALMOST possible; this requires a small change internally as well to pick up the issue_state proto itself when updating dashboards).

Tagging this 'help-wanted' as it's a feature that 1) I currently don't have bandwidth for, but 2) a helpful contributor could tackle if they're so inclined. ^^ Feel free to ask questions or discuss the design for such a tool.

This should come with a proposal for a change in config.yaml for a more useful file_bug_template, so people monitoring TestGrid dashboards can easily manually-file a bug when a failure occurs, and that bug can be linked to the failing test.

/area testgrid
/help

**Comment by chases2** [comment]
I'm currently working on a solution for this feature. It consists of three parts described briefly in the readme, but the idea is as follows:

Part 1: "GitHub Issue Scraper": get data from GitHub API to a gostruct:
```
type GitHubIssue struct {
	IssueId     string
	Title       string
	Comments    []string
	Body        string
}
```

Part 2: "Target Identifier": get data from that struct to this struct/proto: [issue_state.pb.go](https://github.com/kubernetes/test-infra/blob/master/testgrid/issue_state/issue_state.pb.go)

Part 3: Write the proto so that TestGrid can consume it

**Comment by spiffxp** [comment]
/milestone v1.16
I believe this is intended for Q3 yes @michelle192837 ?

**Comment by michelle192837** [comment]
Correct! Sean's done a lot of the work to do this, need a few more adjustments to actually have it run and used.

**Comment by chases2** [comment]
pin: maintenance-ci-testgrid-config-upload

**Comment by chases2** [comment]
The pin is being picked up by Entomologist, and is now showing up on [Testgrid](https://testgrid.k8s.io/sig-testing-maintenance#testgrid-config-upload)

![Bug](https://user-images.githubusercontent.com/1386266/64279792-a82f4600-cf04-11e9-9795-2cfceefc3876.png)

There are many more enhancements to this process that can be made, but the feature is in place.
/close
