### ISSUE TITLE
Some plugin configuration is not displayed in plugin help information.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#10714]
**What happened**:
Multiple plugins are not exposing information about their current configuration via the PluginHelp structs as they should be.
**What you expected to happen**:
These plugins should expose config using the `PluginHelp.Config` field: https://github.com/kubernetes/test-infra/blob/fa2d9efca4e638ddc1e0499464b7ed116034806d/prow/pluginhelp/pluginhelp.go#L44-L47
- `lgtm`
- `updateconfig`
- `size` (Config is included in the wrong field.)

**Anything else we need to know?**:
This info will be used in the details sections here: https://prow.k8s.io/plugins

/area prow/plugins
/help

**Comment by ibrasho** [comment]
We don't have a way to set `updateconfig` configs per repo currently, do we?

**Comment by cjwagner** [comment]
> We don't have a way to set updateconfig configs per repo currently, do we?

No, currently the plugin assumes that it is only enabled on a single repository.

**Comment by matthyx** [comment]
These are the identified plugins:
- [ ] cat (critical one!)
- [ ] golint
- [ ] label
- [ ] lgtm
- [ ] size
- [ ] skip
- [ ] verify-owners
- [ ] wip-label

**Comment by matthyx** [comment]
Alright, so now I have a couple of plugins to fix regarding the validation of `enabledRepos`:
- [ ] approve
- [ ] blockade
- [ ] slackevents
- [ ] trigger
- [ ] welcome

**Comment by matthyx** [comment]
Thanks @fejta !
/close
