### ISSUE TITLE
Clarify instructions in  fejta-bot comments

### ISSUE THREAD

**Issue by MNF** [kubernetes/test-infra#10734]
I’ve received a [message from fejta-bot ](https://github.com/kubernetes/website/issues/10170#issuecomment-446553043) on 12 Dec 2018,
and [replied](https://github.com/kubernetes/website/issues/10170#issuecomment-446561494) 

> @fejta /remove-lifecycle stale.
> Please note that instructions are not clear. Where in GitHub could I specify /remove-lifecycle stale or /close ?

It seems that it didn’t work as in 30 days the new comment “rotten” was generated.

Now I found from examples in https://github.com/kubernetes/test-infra/issues/6083  
that instructions should be on separate lines

> /lifecycle frozen
> /remove-lifecycle stale

Could you please add to bot comment message, that 
 
> Mark the issue as fresh by creating **a new comment writing** /remove-lifecycle stale **on a separate line.**

It also will be good to include a link to document/wiki to describe all process, e.g.

`That's how it works: stale, rotten, close`

> https://github.com/kubernetes/test-infra/issues/6084#issuecomment-422604336

Also clarification how can user ”Send _feedback to sig-testing, kubernetes/test-infra and/or fejta_.” will be good.
What is sig-testing?
Is it https://github.com/kubernetes/test-infra/issues/new/choose? But it has not feedback option.
Is it  refer @fejta in the comment?

**Comment by idealhack** [comment]
Thanks for your feedback!

We can link to https://git.k8s.io/community/sig-testing refer to sig-testing.

You are welcome to create a PR to modify those comments in https://github.com/kubernetes/test-infra/blob/4da53f46e256ccb3c2b06406cf8df9923907de02/config/jobs/kubernetes/test-infra/fejta-bot-periodics.yaml :)

**Comment by fejta** [comment]
Yes, fejta refers to me.

Searching the web for "kubernetes sig-testing" provides a good link that provides a brief explanation as well as contact links.

Should probably link to https://prow.k8s.io/command-help, although that also does not mention that commands need to be on their own line. Change https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/template/command-help.html if you want to do that.

Another thing to realize here is that in the linked issue no one seems to think it is important to note that the cron format does not include seconds. Fighting the bots to keep the issue open will not cause someone to decide to fix it.
