### ISSUE TITLE
1.10 verify job is using wrong go version

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#10742]
/kind bug
/assign

CC @amwat 

we should fix this for https://github.com/kubernetes/kubernetes/pull/72860, we potentially have a small cherry pick that should bend the rules on patching old releases, this job needs fixing for that.

**Comment by cjwagner** [comment]
So the current status is that this is temporarily fixed until we re-bump the verify image, but we will wait to do that until we have deleted all the 1.10 jobs, correct?

**Comment by krzyzacy** [comment]
I think 1.10 is technically already out of support...

**Comment by amwat** [comment]
The 1.10 jobs are scheduled to be removed by 02/12 https://github.com/kubernetes/sig-release/tree/master/releases/release-1.14

**Comment by BenTheElder** [comment]
correct @cjwagner 
correct @krzyzacy, the release is out of support but we're looking at possibly allowing a final patch for this given the circumstances. will be discussed at SIG-release tomorrow
@amwat that should be plenty of time, and I'm going to bring up that timeline as an option for overall support as well. (probably not, but worth mentioning)

**Comment by BenTheElder** [comment]
this appears to be WAI now.
