### ISSUE TITLE
auto suggest subdir owners

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#10754]
**What would you like to be added**: A tool to inspect github data and propose filling out directory OWNERS entries for reviewers by looking at who _has_ been reviewing.

**Why is this needed**: I think a lot of the kubernetes project lacks much in the way of granular owners. granular owners can help with review assignment. We could probably somewhat automate auditing for directories without owners (EG probably all first level dirs should have some approvers...) and _suggesting_ options for that.

Inspired by #10747 

/priority backlog
/kind feature

**Comment by BenTheElder** [comment]
this is more of a wishlist entry than anything. I'm not suggesting anyone should go do this now, but this might eventually be something we could do to help avoid large all-top-level-owned projects.

**Comment by spiffxp** [comment]
linking to the issue I'm using as an umbrella for all things OWNERS/contributor-ladder related https://github.com/kubernetes/community/issues/1808

**Comment by stevekuznetsov** [comment]
What data would we look at? Commits? That can be done with some `git log` commands. Do we need GitHUB data?

**Comment by spiffxp** [comment]
>Do we need GitHUB data?

IMO, yes.  People who commit code all day long while ignoring pull requests are not the people I want owning things.

**Comment by dims** [comment]
@spiffxp Totally agree with you

**Comment by BenTheElder** [comment]
We lack bandwidth. Future features like this should be tracked at kubernetes/community (high level workflow discussions) or kubernetes-sigs/prow (prow feature requests / implementation discussions)
