### ISSUE TITLE
k8s-ci-robot applying incorrect labels

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/test-infra#10766]
See https://github.com/kubernetes/kubernetes/pull/72882.

1) Both `cncf-cla: yes` and `cncf-cla: no` labels applied at the same time.
2) Not applying `do-not-merge/cherry-pick-not-approved` even though it was a PR to a release branch. As a result, it merged without PRM's approval.

Not sure what caused it to malfunction in this case, but regarding (2), is there any reason merging relies on the lack of presence of negative label, rather than the presence of positive label? The latter seems safer.

**Comment by stevekuznetsov** [comment]
/cc @cjwagner 
The CNCF CLA labels come from a separate system, but this is definitely odd.

**Comment by BenTheElder** [comment]
historically there was also an alternative human-applied CLA confirmation for when the system was broken IIRC, but I don't think that's been used in a long time. positive label makes more sense to me, but in either case there's some inherent raciness with the merge robot and the PR state.

**Comment by aleksandra-malinowska** [comment]
I think it actually uses only positive label for CLA, since the check passed. But not for cherry-pick approval, so if bot stops applying negative label for any reason, things just start to merge to release branches the same way as to master.

As for race conditions, it seems like in this case the bot didn't add the negative cherry-pick label at all (or post a standard cherry-pick message, "this pr is not for master branch" etc etc), even though it had a couple of hours to do it before it was LGTMed and merged.

**Comment by BenTheElder** [comment]
the status drives the label (CNCF robot creates / updates the status, the event driver part of prow writes a label to match), and then the merge robot reads the positive label (had to check: https://github.com/kubernetes/test-infra/blob/da192baabd4c52e4a68b5c71bd39c5738928e110/prow/config.yaml#L399)

The event can be missed for the cherry pick. As for race conditions I was referring to the fact that EG if you comment `/hold` but the PR is already being considered for merge there's a window in which the merge robot will not pick up that change.

**Comment by cblecker** [comment]
The base branch was also changed *after* the PR was opened. I don't know if prow will react properly in that condition

**Comment by cblecker** [comment]
Also, there were a number of times labels were manually added, rather than using bot commands. There are race conditions in GitHub's UI. It is preferable to use the bot slash commands to modify labels, rather than the GitHub UI selector.

**Comment by BenTheElder** [comment]
:100: -- essentially the github web frontend seems to do a "Set" operation on the label list rather than just adding the labels, when you add or remove labels via the web-ui the robot may have changed labels since they were loaded into your browser and your change can undo them. Unfortunately the only good solution we know is to stick to the slash commands which operate via the API instead.

**Comment by stevekuznetsov** [comment]
This seems like this has been resolved?

/close
