### ISSUE TITLE
Tests fail after 55 minutes, but weren't hung

### ISSUE THREAD

**Issue by benmoss** [kubernetes/test-infra#10778]
**What happened**:
`pull-kubernetes-e2e-kops-aws` tests failed against [a PR](https://github.com/kubernetes/kubernetes/pull/72918) because the 55m timeout was reached. It appears that none of the tests had failed or hung, but just actually took this long to reach this point.

**What you expected to happen**:
The tests pass, the PR didn't change anything that should have caused them to fail

**How to reproduce it (as minimally and precisely as possible)**:
Looks like it's probably flaky, but I imagine it's happening somewhat often?

**Please provide links to example occurrences, if any**:
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72918/pull-kubernetes-e2e-kops-aws/119395/?log#log

**Comment by benmoss** [comment]
I saw https://github.com/kubernetes/test-infra/issues/9805, but unlike that one this test run doesn't seem to have a long hang anywhere in the test run.

**Comment by BenTheElder** [comment]
timeouts are intentional, we aren't going to run tests indefinitely.

**Comment by benmoss** [comment]
Yeah, I was uncertain what the thinking was there. If we don't want to budge on 55 minutes, then we have to figure out where the slowdowns are to stop this. Is there any work being tracked in that area? Seems like a big problem to tackle.

**Comment by BenTheElder** [comment]
following up on this, I think the kops testing itself is broken, bringing up some discussion in #sig-testing slack https://prow.k8s.io/?job=pull-kubernetes-e2e-kops-aws

I don't think its a test slowdown, this looks like a quota / provisioning issue, which we have with this presubmit frequently >.>

**Comment by BenTheElder** [comment]
to the other point: we do not want to make the presubmits any slower, but also I don't think that would fix this, it looks very much to be a bringup issue: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72862/pull-kubernetes-e2e-kops-aws/119421/

**Comment by benmoss** [comment]
Closing, since we think it's a kops-aws flakiness problem
