### ISSUE TITLE
Oops we accidentally rolled out implicit self approve to all repos

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#10794]
Issue for a retro based off of the [agenda item I rambled on at sig-contribex](https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/edit#)

Timeline:
- Dec 10: notify k-dev@ of k/community change https://groups.google.com/forum/#!msg/kubernetes-dev/oWbV6uiQMIM/0ku8cvSZBgAJ 
- Dec 10: not sure if this is the root cause PR? https://github.com/kubernetes/test-infra/pull/10435 
- cblecker rolled the change into test-infra
- Dec 19: last prow deploy before holiday lull https://github.com/kubernetes/test-infra/pull/10504 
- Jan 7: first prow deploy after holiday lull https://github.com/kubernetes/test-infra/pull/10532
- Dec 14: PR opened to change default settings for prow https://github.com/kubernetes/test-infra/pull/10435
- Jan 10: PR merged (reviewed by @cblecker @cjwagner) https://github.com/kubernetes/test-infra/pull/10435
- Jan 11: TODO: prow bump PR that landed the above PR
- Jan 15 reports of something amiss in #sig-testing
- Jan 15 Rollbackish PR (still not deployed) https://github.com/kubernetes/test-infra/pull/10782
- Jan 16: Notice no documentation on policy for rollback, how fast things should be rolled back etc
- This instance was completely unintentional -- no notification / communication sent out

What went well:

What went wrong:
- @stevekuznetsov's question of "why are these the _right_ defaults" went unanswered on https://github.com/kubernetes/test-infra/pull/10435

We will do as followup:
- @cblecker will followup with sig-docs on their specific automation needs https://github.com/kubernetes/community/issues/3100

/assign @cblecker @fejta @cjwagner @spiffxp

**Comment by Katharine** [comment]
> ??? - another change landed in test-infra that modified the default behavior to mimic the change

That was #10435 — it didn't merge until January 10th, and was then deployed on January 11th, which is the point at which the defualt changed.

**Comment by spiffxp** [comment]
/milestone clear
/close
@cblecker please reopen if you feel there is more to be done here
