### ISSUE TITLE
Create utility for using kubeconfig for creds instead of build-cluster

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#10821]
The build controller supports using the standard kubeconfig file that the official client uses. 

However, since prow.k8s.io uses a legacy build-cluster file it also supports adapting this into something the official client can understand:

https://github.com/kubernetes/test-infra/blob/accc8109e9529acaa064ae7df74cfe12d6cd0970/prow/cmd/build/main.go#L126-L194

It would be replace all the build-cluster credentials with kubeconfig files, aka:
* Take the conversion logic and make it into a utility that takes a build-cluster file as input and spits out a kubeconfig file as output (either standalone utility or extension to prow/cmd/mkbuild-cluster)
* Update prow/cmd/mkbuild-cluster utility to output a kubeconfig file and ensure that the creds are correct (plank & friends only support client cerfificate)

I'd assume that to be at least two PRs.

Even longer term we should either update the prow/kube client to support kubeconfig creds or more likely just switch out the client with the official client.

/help

**Comment by nzoueidi** [comment]
I am working on this. I will push a PR very soon.
/lifecycle active

**Comment by stevekuznetsov** [comment]
@nzoueidi how are you doing this? 

I think it would be much better to use Service Account and normal tokens rather than the certificate auth that is currently supported

**Comment by rverma-nikiai** [comment]
@nzoueidi @fejta how about mounting the kubeconfig file directly to components like plank. Even with that, another issue is the addition of exec utils like aws-iam-authenticator.  I believe we should be able to work around that by copying the binary using init container.

Also as per documentation 
```
Mount this secret into the prow components that need it (at minimum: plank, sinker and deck) and set the --build-cluster flag to the location you mount it at. 
```
I am wondering which other components may require to talk to external api server. I read that the prime motivation is to run trusted jobs in trusted environments.

**Comment by stevekuznetsov** [comment]
Mounting the kubeconfig via secret is appropriate. If we want to support third party auth we could either publish variants of the images with the appropriate binaries or as you say the deployments could use an init container to inject the binaries as needed.

**Comment by rverma-nikiai** [comment]
@nzoueidi We would love to help in early testing if you have some alpha build available for this.

**Comment by rverma-nikiai** [comment]
@fejta @stevekuznetsov Is it possible to use token-based authentication for prow client. I find that documentation only lists authentication by X509 certificates. If yes can you please give more details.
