### ISSUE TITLE
Propose enabling owners-label prow plugin for all kubernetes orgs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#10834]
**What would you like to be added**: Instead of enabling owners-label per-repo, let's enable it for all kubernetes orgs that we manage

**Why is this needed**: Auto-labeling PR's with the appropriate sig, wg, or area label can be really helpful for triage.  The other OWNERS-driven features are enabled by default everywhere, why not this?

This issue intended more to spark discussion about whether we have scalability or token concerns around this.  But also to ask sig-contribex what they think about this idea.

Also I don't know if "feature" really applies here, this is about deploying existing functionality, but I couldn't think of a better kind for it.

/sig contributor-experience
/sig testing
/area github-management

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/pull/9011#pullrequestreview-145402210
>it uses at least 3 API tokens for every PR update so we should probably only enable it where there are actually OWNERS files that would use it.

Curious if this is still the case today.  Are we token constrained?

**Comment by spiffxp** [comment]
/assign @cjwagner @cblecker 
for comment

**Comment by spiffxp** [comment]
Did we have ghproxy back then? Would ghproxy alleviate these concerns?

**Comment by cjwagner** [comment]
Token usage might be ok with ghproxy (especially with request coalescing). I think I can also make owners-label save some tokens in some more cases.
We should really switch some of the expensive maintenance jobs like branchprotector, label_sync, and peribolos to their own bot token (e.g. k8s-merge-robot). That would make token usage less of a concern overall.

Let me try to optimize owners-label a bit and then we can try enabling it more broadly.

**Comment by cblecker** [comment]
I'd suggest maybe we set up a new, better username for those jobs.. like k8s-admin-robot or something. I'd like to deprecate and strip back the old munger account. It's not in all the orgs either.

**Comment by cblecker** [comment]
But to not get sidetracked, If the token question is good, then I'd be good with a 72h working day notice on this. It shouldn't have negative impact, but people should just be aware. We have verify-owners on for all repos, right?

**Comment by nikhita** [comment]
This is done in https://github.com/kubernetes/test-infra/pull/10835.

/close
