### ISSUE TITLE
Prow should not require build clusters to use legacy authorization.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#10840]
**What would you like to be added**:
 Prow should support build clusters that don't have legacy authorization enabled. Specifically this means specifying RBAC rules in the build cluster and probably also switching all Prow components that talk to build clusters to use kubeconfigs.
I don't completely understand how the cluster external clients (in our case Prow's service components) identify themselves to the build cluster so that the correct RBAC rules can be applied.

**Why is this needed**:
This is needed so that we can stop using legacy authorization and take full advantage of RBAC for improved security. https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster
Presumably support for legacy authorization will be dropped at some point as well.

/cc @BenTheElder @utka @stevekuznetsov @fejta 
/area prow

**Comment by stevekuznetsov** [comment]
Yeah, how _are_ you authenticating to the external clusters?

**Comment by spiffxp** [comment]
/assign @stevekuznetsov 
you've removed the label and done nothing twice now, what's the plan here?

**Comment by clarketm** [comment]
Legacy authorization is **not** required for build clusters. For example, when I created the Istio build I explicitly *disabled* legacy authorization. Granted, currently we  use **one** kubeconfig/build-cluster entry for each build cluster and the auth credentials are *typically* given `cluster-admin` which is much more privileged than we need (#14907).  I expect the design proposal @stevekuznetsov is working on to change how we interact and authenticate/authorize to build clusters dramatically.

**Comment by cjwagner** [comment]
Closing this since we can both avoid legacy authorization and use RBAC. There are some additional improvements we could make as @clarketm pointed out, but this issue has been resolved.
