### ISSUE TITLE
prow/cat: 'no' keyword should always show grumpy cat

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#10845]
**What would you like to be added**:
Using the `/meow no` command should always display a picture of grumpy cat. Is there really a better way to say no to someone?

**Why is this needed**:
This is a silly question.

**Comment by nikhita** [comment]
lol...practically speaking, this would require a change to the cat api, right?

**Comment by Katharine** [comment]
Nah, we'd just need to explicitly catch "no" and point it at a hardcoded URL.

**Comment by nzoueidi** [comment]
I am working on this. I will push a PR soon.

**Comment by mirandachrist** [comment]
@nzoueidi are you still working on this? If not, I'd like to.

**Comment by nzoueidi** [comment]
yes @mirandachrist but if you would like you can take it, I will share with you my findings :)

**Comment by mirandachrist** [comment]
thanks @nzoueidi it'll be great for me to do as a first issue! If you have any tips or photo suggestions please let me know :)

**Comment by cblecker** [comment]
Closed in #12841. Thanks @mirandachrist!

/close
