### ISSUE TITLE
hook is down, the community sees this as a prow.k8s.io outage

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#10904]
Opening issue for timeline / retro / explanation of what happened and what the fix is

Looks like this is due to a bad prow config

/assign @BenTheElder 
since I see him taking it on in #testing-ops (not the on-call! thanks ben!)

**Comment by BenTheElder** [comment]
Leaving this open until we merge https://github.com/kubernetes/test-infra/pull/10911

**Comment by nikhita** [comment]
> Leaving this open until we merge #10911

PR has merged.

/close
