### ISSUE TITLE
k8s version sometimes not filled in during PR builds

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1091]
Seen in https://github.com/kubernetes/kubernetes/pull/36883 (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/36883/pull-kubernetes-e2e-kops-aws/20/):

```
W1116 12:38:36.666] + export 'E2E_OPT=  --kops-cluster aws-kops-agent-pr-47-0.test-aws.k8s.io  --kops-kubernetes-version https://storage.googleapis.com/kubernetes-release-pull/ci/pull-kubernetes-e2e-kops-aws/  --kops-nodes 4  --kops-state s3://k8s-kops-jenkins/'
```

**Comment by ixdy** [comment]
release-1.4 doesn't have `build-tools/util.sh`:
```
W1116 12:38:36.665] ++ source build-tools/util.sh
W1116 12:38:36.665] /var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/./test-infra/jenkins/../jobs/pull-kubernetes-e2e-kops-aws.sh: line 41: build-tools/util.sh: No such file or directory
W1116 12:38:36.665] + readonly version=
W1116 12:38:36.665] + version=
```

The curious thing is why this didn't immediately fail.

**Comment by ixdy** [comment]
oh, because `&&` overrides errexit.

**Comment by zmerlynn** [comment]
Yeah. I thought we were safe because https://github.com/kubernetes/kubernetes/pull/35453 was in, but I guess not.

**Comment by ixdy** [comment]
yeah, that only affects `master` and `release-1.5`.

**Comment by ixdy** [comment]
(and as soon as there's a new bazel release, it's going back to `build/`.)
