### ISSUE TITLE
Tide not merging PRs at k/dashboard repo

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/test-infra#10921]
**What happened**: Tide is not merging PRs at k/dashboard repo after changes done in https://github.com/kubernetes/test-infra/pull/10149.

**What you expected to happen**: PRs to be merged when Travis CI (only required check) will pass.

**How to reproduce it (as minimally and precisely as possible)**: Open https://github.com/kubernetes/dashboard/pull/3529. All checks are green and there is a message:

![image](https://user-images.githubusercontent.com/2823399/51663398-01bab400-1fb7-11e9-966e-7fe4c965daf5.png)

**Please provide links to example occurrences, if any**: https://github.com/kubernetes/dashboard/pull/3529

**Anything else we need to know?**: Do we need to add `/pr` to configuration file? Other repos seem to not use it.

We track it from https://github.com/kubernetes/dashboard/issues/3343.

**Comment by BenTheElder** [comment]
filed https://github.com/kubernetes/test-infra/pull/10922

**Comment by maciaszczykm** [comment]
@BenTheElder Thank you :)

**Comment by maciaszczykm** [comment]
It works 🎉
