### ISSUE TITLE
peribolos: support managing repo collaborators

### ISSUE THREAD

**Issue by munnerz** [kubernetes/test-infra#10924]
**What would you like to be added**:

I'd like to be able to manage individual repository collaborators using peribolos

**Why is this needed**:

Although individual repo permissions in kubernetes/* is discouraged, we at Jetstack want to be able to allow users outside of the `jetstack` org to be assigned issues/PRs. This also allows those users to add 'lgtm' to PRs and so on.

In order to manage this right now, we have to manually add people as read-only collaborators to our repository. This is tedious and error prone.

It'd be great if peribolos could be extended to support managing individual repositories as well as orgs 😄

**Comment by BenTheElder** [comment]
@fejta @cblecker

**Comment by cblecker** [comment]
Closing as dupe of #10501
