### ISSUE TITLE
Gubernator returns no matching index error

### ISSUE THREAD

**Issue by nghialv** [kubernetes/test-infra#10920]
**What happened**:
I have just deployed Gubernator on my GCP project but got the below internal error when access the test result.

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/f612b68945952bd1/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)

NeedIndexError: no matching index found.
The suggested index for this query is:
- kind: GHIssueDigest
  properties:
  - name: xref
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
@Katharine (sorry! This is what happens when you're too helpful 😅)

**Comment by Katharine** [comment]
This is interesting.

My _guess_ is that this error is occurring because you have no `GHIssueDigest` entities stored. As such, Cloud Datastore's automatic simple index on properties doesn't exist, and consequently it chokes when trying to perform the lookup.

Do you have any GHIssueDigest entities? You can check at https://console.cloud.google.com/datastore/entities;kind=GHIssueDigest when the correct GCP project is active. They should start existing after gubernator receives a webhook from a GitHub issue.

**Comment by nghialv** [comment]
Hi, @Katharine 
Thank for your quick reply.

> Do you have any GHIssueDigest entities?

Yes, I don't have any `GHIssueDigest` entity.

I just want to use Gubernator to show the test results stored in GCS.
I don't need Gubernator's PR Dashboard at this time, so I didn't configure the GitHub webhook.
Can I have another way to make Gubernator work without intergration with GitHub webhook?
(As I remember the previous version worked without GitHub webhook.)

Thank you.

**Comment by Katharine** [comment]
This lookup isn't actually for the PR dashboard, but instead for a feature that lists references to a given Gubernator page on a github issue… [as long as you're Kubernetes](https://github.com/kubernetes/test-infra/blob/9905a951df2f7bf45aa90bcb80c431d41b778f52/gubernator/github/classifier.py#L24). It won't work anywhere else.

Gubernator is in maintenance mode (in favour of ultimate replacement by prow's Spyglass), but this is a fairly silly bug that we may as well fix.

/assign

**Comment by nghialv** [comment]
Thanks for your sharing.

I have just tried to use `Spyglass` and I have to say that I love it. Written in golang, easy to deploy, GKE instead of App Engine. 
I will not close this issue because you added it to `v1.14`.

Thank you so much.

**Comment by spiffxp** [comment]
/close
closing because spyglass works
