### ISSUE TITLE
Use clonerefs without initupload or sidecar

### ISSUE THREAD

**Issue by mskonovalov** [kubernetes/test-infra#10946]
**What would you like to be added**:
We want to use PodUtils but without GCS part but it seems to be not possible as all pod utils are tightly connected and if I don't provide the GCS auth data init-uploadds fails.

**Why is this needed**:
We use test-infra outside of GCS

**Comment by stevekuznetsov** [comment]
What are you expecting to happen without GCS? Do you just want the cloning?

**Comment by mskonovalov** [comment]
Yep, we need only cloning and merging

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
/assign  @cjwagner 
xref #13561

**Comment by cjwagner** [comment]
> /remove-lifecycle stale
> /assign @cjwagner
> xref #13561

Hmm, the lifecycle label was applied, but I wasn't assigned 🤔 
/assign

**Comment by cjwagner** [comment]
This keeps going stale so I'm not sure if this is still something that is still cared about, but if it is, it can be achieved by specifying the `decoration_config.gcs_configuration.local_output_dir` ProwJob field. This copies the files to a local directory which may waste time and (temporarily) space if you don't care about the output at all, but it will avoid uploading to GCS.
/close
