### ISSUE TITLE
automate the build and push of the kubekins-e2e image

### ISSUE THREAD

**Issue by neolit123** [kubernetes/test-infra#10958]
**What would you like to be added**:
- automation of the build and push of the kubekins-e2e image when changes under certain paths happen. e.g. `/kubetest`.
- automatic retagging of jobs that use the image.

**Why is this needed**:
without such automation, after changes in kubekins contents the image has to be re-built and pushed on demand by a human.

/kind feature
/area images
/priority important-longterm
ticket requested by @BenTheElder

**Comment by BenTheElder** [comment]
/cc @krzyzacy 

then we can simplify the bump script ant let anyone file a bump :-)
the other images do not need to change very often

**Comment by krzyzacy** [comment]
:100: !!!

**Comment by krzyzacy** [comment]
Also note that kubekins image is built on top of bootstrap, so we need to be aware of bumping that as well..

Technically we can mimic the prow bump today now :-)

**Comment by krzyzacy** [comment]
done by @Katharine (thanks!)
