### ISSUE TITLE
/assign does not document that multiple users may be assigned

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#10978]
**What happened**: https://github.com/kubernetes/steering/pull/90#issuecomment-455354214 <-- lots of individual `/assign` comments @pwittrock 🙃 

**What you expected to happen**: https://prow.k8s.io/command-help#assign should make usage clear, it does not. Only assigning a single user is documented, and the `@` not being strictly necessary is not documented. We should document the multi-user `/assign user1 user2` form.

**How to reproduce it (as minimally and precisely as possible)**: look at the command help for `/assign`

**Please provide links to example occurrences, if any**: https://prow.k8s.io/command-help#assign

**Anything else we need to know?**: /shrug

BTW you can:
/assign @cjwagner bentheelder
/assign k8s-ci-robot

**Comment by fejta** [comment]
Technically all of this is documented on the left-most column: `/[un]assign [[@]...]`

**Comment by BenTheElder** [comment]
Fair, but it will be much more obvious if one of the examples and the detail text highlight this. Currently the command pattern column is the only thing that documents this.

**Comment by nikhita** [comment]
/remove-lifecycle stale
/good-first-issue

Would require an update here: 

https://github.com/kubernetes/test-infra/blob/e0dcd68dc8650cf7137d3fc7386c1c5b0d551a23/prow/plugins/assign/assign.go#L53

We can probably do the same for `/cc` as well.

**Comment by Biwwie** [comment]
I'll take care of this. Looks like the change needs to make the 

/cc consistent in documentation.
