### ISSUE TITLE
Rename SIG-Windows conformance to release on TestGrid

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/test-infra#10989]
Can we rename the "[Conformance acs-engine on Azure](https://testgrid.k8s.io/sig-windows#Conformance%20acs-engine%20on%20Azure)" dashboard to "SIG-Windows Release (Azure)"?

There's a few reasons for this:
- Testing is no longer just focused on the conformance tests - that's a separate task from graduating Windows support to stable. 
- We need to make sure it's easy to find the right release dashboard - see https://github.com/kubernetes/enhancements/pull/685#discussion_r251184122. The other test passes won't be required for v1.14 and the out-of-tree CRI/CNI plugins can be stabilized separately from Kubernetes releases.

When you're updating, can you also include the [SIG-Windows] tests? Those are also needed for the release and we'll be adding more during v1.14.

**Comment by BenTheElder** [comment]
sure, renaming is just a PR away, please do keep names accurate.
/assign @adelina-t @PatrickLang 

https://github.com/kubernetes/test-infra/tree/master/testgrid#configuration
/area jobs

FYI @spiffxp 
Please also consider:
- if this gets in a healthy state you should probably look to get it into one of the actual release team monitored dashboards
- for such monitoring, it will then need to include one for each active branch soon, master will not be the same as 1.14 even prior to release, and after release 1.14 will continue to need signal for patch releases

**Comment by adelina-t** [comment]
PR for this opened: https://github.com/kubernetes/test-infra/pull/11022

**Comment by adelina-t** [comment]
@PatrickLang For adding sig-windows tests we have PR: https://github.com/kubernetes/test-infra/pull/11023 

( I forgot to add node-os-distro when I changed the job def to include sig-windows )
