### ISSUE TITLE
Update the cla plugin to allow overriding the CLA check

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#11004]
**What would you like to be added**:

I think I'm asking for a `cncf-cla: yes` label to be applied via a bot command that is restricted to repo admins, in a way that wouldn't cause the check-cla plugin to race with with the linuxfoundation/cla status context

Alternatively, I'm asking for us to allow tide to look for a `cncf-cla: human-approved` label instead of `cncf-cla: yes`.  I think this would make for an ugly set of tide queries.

**Why is this needed**:

CLA Bot doesn't handle a number of cases, and trying to move code from one repo to another is only going to increase as we try to de-monorepo this project apart. 
 See [this sig-architecture@ thread](https://groups.google.com/forum/#!topic/kubernetes-sig-architecture/lohdOInzcuQ)

Manual merges should be exceptional behavior, this case is going to become more common over time

**Comment by spiffxp** [comment]
Example: https://github.com/kubernetes/enhancements/pull/725 - k8s-merge-robot hasn't signed the CLA

**Comment by spiffxp** [comment]
Example: https://github.com/kubernetes/community/pull/3001 - github user no longer has the e-mail address that was originally used to make the commit (this e-mail address was valid and had signed the CLA)

**Comment by spiffxp** [comment]
kubernetes/utils PRs merged manually because of the CLA:
- https://github.com/kubernetes/utils/pull/66
- https://github.com/kubernetes/utils/pull/65

**Comment by BenTheElder** [comment]
> Alternatively, I'm asking for us to allow tide to look for a cncf-cla: human-approved label instead of cncf-cla: yes. I think this would make for an ugly set of tide queries.

Might be too ugly in tide, but this is clearer than overriding imho, and we had this with the submit queue

**Comment by spiffxp** [comment]
Example: https://github.com/kubernetes/kubernetes/pull/73042#issuecomment-455724404 - anago hasn't signed the CLA
