### ISSUE TITLE
Integrate prow with resultstore

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#11009]
ResultStore is in EAP (early access preview), and we can get our projects whitelisted.

Create a utility which:
* takes a gcs://prefix/$job/$build as input,
* reads the metadata from started.json, finished.json and artifacts/**/junit*.xml
* creates a ResultStore invocation, targets, configurations, configuredtargets, actions with this data
* upload it into result store

Protos and service definitions: https://github.com/googleapis/googleapis/tree/master/google/devtools/resultstore

This will enable viewing logs similar to tensorflow: 
https://source.cloud.google.com/results/invocations/a72b1dc5-5ea4-4b98-95b2-5cd39b69618a/targets

Then we can:
* Update sidecar to upload to result store in addition to GCS
* Run a backfil mapreduce to export all our previous job results to ResultStore

**Comment by fejta** [comment]
Click the source.cloud.google.com link. It is a place to store job results and view the logs later. Think a hosted version of gubernator.

**Comment by stevekuznetsov** [comment]
How does this overlap with spyglass?

**Comment by fejta** [comment]
IMO the primary spyglass use case is for viewing in progress and/or recently completed job logs.

ResultStore is more like a GCS replacement, a hosted service option for archiving (and indexing) your job logs and associated metadata.

I can imagine a future where we allow spyglass to query ResultStore for results, rather than listing objects in GCS.
