### ISSUE TITLE
Hook Approve Plugin Doesn't Support Different Github URL

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11014]
**What would you like to be added**:
I would like the hook approve plugin to use the same `github-endpoint` provided to hook (via `--github-endpoint`)
**Why is this needed**:
I am unable to use the hook approve plugin on Github Enterprise without this functionality.

**Comment by midnightconman** [comment]
Here is a redacted example:

```
{"author":"secret","component":"hook","error":"failed to clone secret/secret: git cache clone error: exit status 128. output: Cloning into bare repository '/tmp/git880346570/secret/secret.git'...\nremote: Invalid username or password.\nfatal: Authenticatio
n failed for 'https://secret:secret@github.com/secret/secret'\n","event-GUID":"05a426e0-235f-11e9-8a57-40e0cc6a90a7","event-type":"pull_request","level":"error","msg":"Error handling PullRequestEvent.","org":"secret","plugin":"app
rove","pr":91,"repo":"secret","time":"2019-01-29T00:44:56Z","url":"https://github.private.com/secret/secret/pull/91"}
```

**Comment by midnightconman** [comment]
I am running hook version `gcr.io/k8s-prow/hook:v20190123-36919f3`

**Comment by stevekuznetsov** [comment]
Ah this is the `git` client -- This is being fixed in https://github.com/kubernetes/test-infra/pull/10129

**Comment by midnightconman** [comment]
Excellent, thank you... Can we close this issue?
