### ISSUE TITLE
build controller fails to sync builds running in the same cluster

### ISSUE THREAD

**Issue by osela** [kubernetes/test-infra#11029]
**What happened**:
I'm trying to create a knative-build presubmit job. All my prow components run in the default namespace and my prow config sets `pod_namespace: test-pods`. Once the github hook is received, the prow job is created but the build and the pods knative tries to create to run it start to get deleted and recreated multiple times. The prow job never succeeds nor fails, and stays in "triggered" state with "scheduling" as the description.
**What you expected to happen**:
The prow job to either succeed or fail.

Here is a section from the build controller logs:
```
time="2019-01-29T18:44:55Z" level=info msg="Create builds/default/test-pods/af0f1b59-23f4-11e9-a97f-6a90ac2156db"
time="2019-01-29T18:44:55Z" level=debug msg="createBuild(default,test-pods,af0f1b59-23f4-11e9-a97f-6a90ac2156db)"
time="2019-01-29T18:44:55Z" level=info msg="Update prowjobs/default/test-pods/af0f1b59-23f4-11e9-a97f-6a90ac2156db"
time="2019-01-29T18:44:55Z" level=debug msg="updateProwJob(af0f1b59-23f4-11e9-a97f-6a90ac2156db)"
time="2019-01-29T18:44:55Z" level=warning msg="/test-pods/af0f1b59-23f4-11e9-a97f-6a90ac2156db found in context  not default"
time="2019-01-29T18:44:55Z" level=info msg="Delete builds//test-pods/af0f1b59-23f4-11e9-a97f-6a90ac2156db"
time="2019-01-29T18:44:55Z" level=debug msg="deleteBuild(,test-pods,af0f1b59-23f4-11e9-a97f-6a90ac2156db)"
```

Trying to investigate the issue, I noticed that when the build controller runs with an in-cluster kube config, it uses `""` as the default context. This is the context it expects prow jobs to have, but the job context is set by its `Cluster` field, which is set to `"default"` by default.

I naively tried to change the default context to `"default"` by changing the following piece of code in prow/kube/config.go
```
configs := map[string]rest.Config{}
var defCtx *string
// This will work if we are running inside kubernetes
if localCfg, err := rest.InClusterConfig(); err != nil {
	logrus.Warnf("Failed to create in-cluster config: %v", err)
} else {
	defCtx = new(string)
	logrus.Info("* in-cluster")
	configs[*defCtx] = *localCfg
}
```

to this:
```
configs := map[string]rest.Config{}
var defCtx *string
// This will work if we are running inside kubernetes
if localCfg, err := rest.InClusterConfig(); err != nil {
	logrus.Warnf("Failed to create in-cluster config: %v", err)
} else {
        s := DefaultClusterAlias
	defCtx = &s
	logrus.Info("* in-cluster")
	configs[*defCtx] = *localCfg
}
```

and it seemed to solve my issue, but it's probably wrong as the given kubeconfig may contain a default context too.

**Comment by stevekuznetsov** [comment]
I have a fix for this exact issue in my client refactors

**Comment by fejta** [comment]
Can we make both "" and "default" have this config? Should cover both scenarios while we finish the transition to kubeconfig auth
