### ISSUE TITLE
[Question]How to execute kubetest

### ISSUE THREAD

**Issue by OlegLoewen** [kubernetes/test-infra#11038]
I'm confused which parameters need to be used for kubetest.

Currently, I'm testing multiple providers (azure, openstack, gce, aws, alicloud) as follows:

I turn up the cluster of desired provider by myself.
Then I run kubetest always in this manner (but different ginkgo focus):
```bash
kubetest --provider local --deployment local --test --check-version-skew false --test_args="--ginkgo.skip=Alpha|Experimental|Disruptive|Flaky|\[Driver --ginkgo.focus=\[sig-storage"
```

This execution runs fine as long as I only run conformance tests. However, currently I'm trying to investigate test coverage SIG groups one by one and facing some issues. Here are a few questions regarding the kubetest usage:

### **Kubetest results in  Error in ./hack/ginkgo-e2e.sh:143**
Often kubetest crashes with the following error message:
```
!!! Error in ./hack/ginkgo-e2e.sh:143
  Error in ./hack/ginkgo-e2e.sh:143. '"${ginkgo}" "${ginkgo_args[@]:+${ginkgo_args[@]}}" "${e2e_test}" -- "${auth_config[@]:+${auth_config[@]}}" --ginkgo.flakeAttempts="${FLAKE_ATTEMPTS}" --host="${KUBE_MASTER_URL}" --provider="${KUBERNETES_PROVIDER}" --gce-project="${PROJECT:-}" --gce-zone="${ZONE:-}" --gce-region="${REGION:-}" --gce-multizone="${MULTIZONE:-false}" --gke-cluster="${CLUSTER_NAME:-}" --kube-master="${KUBE_MASTER:-}" --cluster-tag="${CLUSTER_ID:-}" --cloud-config-file="${CLOUD_CONFIG:-}" --repo-root="${KUBE_ROOT}" --node-instance-group="${NODE_INSTANCE_GROUP:-}" --prefix="${KUBE_GCE_INSTANCE_PREFIX:-e2e}" --network="${KUBE_GCE_NETWORK:-${KUBE_GKE_NETWORK:-e2e}}" --node-tag="${NODE_TAG:-}" --master-tag="${MASTER_TAG:-}" --cluster-monitoring-mode="${KUBE_ENABLE_CLUSTER_MONITORING:-standalone}" --prometheus-monitoring="${KUBE_ENABLE_PROMETHEUS_MONITORING:-false}" --dns-domain="${KUBE_DNS_DOMAIN:-cluster.local}" ${KUBE_CONTAINER_RUNTIME:+"--container-runtime=${KUBE_CONTAINER_RUNTIME}"} ${MASTER_OS_DISTRIBUTION:+"--master-os-distro=${MASTER_OS_DISTRIBUTION}"} ${NODE_OS_DISTRIBUTION:+"--node-os-distro=${NODE_OS_DISTRIBUTION}"} ${NUM_NODES:+"--num-nodes=${NUM_NODES}"} ${E2E_REPORT_DIR:+"--report-dir=${E2E_REPORT_DIR}"} ${E2E_REPORT_PREFIX:+"--report-prefix=${E2E_REPORT_PREFIX}"} "${@:-}"' exited with status 1
Call stack:
  1: ./hack/ginkgo-e2e.sh:143 main(...)
Exiting with status 1
```
This error message is not very helpful, as I find. I pretty sure this error is a result of individual e2e tests. However,it comes to this crash no junit01.xml file is generated, which is crucial for my e2e test evaluations. 
- Is there a way to find out which e2e test is causing this error?
- How to get more error details?
- Is there a way to avoid this? Eventually by executing each test with an individual kubtest call?

## What impact does the provider parameter have?
Currently, I'm using `--provider local` for all clusters (azue, openstack, gce, aws). 
- What does this parameter do? 
- Do I need to state here the provider of the cluster?
  - There is no openstack provider, right?

## What impact does the deployment parameter have?
- If I turn up the cluster by myself, do I still need to provide this parameter?
  - If so, which value?

## Is there a way to reduce the CPU load?
Before I run kubetest I'm always running:
```
make WHAT=test/e2e/e2e.test
make WHAT=cmd/kubectl
make WHAT=vendor/github.com/onsi/ginkgo/ginkgo
```
Especially `make WHAT=test/e2e/e2e.test` takes a while. Is there a binary (environment specific) version somewhere located which can be downloaded?

Kind Regards,
Oleg

**Comment by BenTheElder** [comment]
you should consider `--provider=skeleton` instead, the local provider is actually a reference to hack/local-up-cluster.sh in kubernetes

/assign @krzyzacy

**Comment by krzyzacy** [comment]
haven't tried local deployer myself... so...
/assign @dims

**Comment by BenTheElder** [comment]
see EG this discussion: https://github.com/kubernetes/kubernetes/pull/73402#discussion_r251499949

_all_ of the tooling is long aware of "local" and makes assumptions that this means `hack/local-up-cluster.sh`. `skeleton` should not have any special assumptions anywhere AFAIK.

**Comment by BenTheElder** [comment]
(I cannot remember what all of the assumptions are, but I know there are at least some around log dumping, which kubetest does, along with e2e.test)

**Comment by OlegLoewen** [comment]
If I run kubtest --ginkgo-parallel, do I need to skip [Serial] e2e tests? 
If this is the case, than can I just append the e2e.log and junit files  auf serial and parallel runs and push them for testgrid? Or would these files then have an unaproriate format?

**Comment by BenTheElder** [comment]
> If I run kubtest --ginkgo-parallel, do I need to skip [Serial] e2e tests?

yes, technically you don't have to but they will be more likely to fail.

> If this is the case, than can I just append the e2e.log and junit files auf serial and parallel runs and push them for testgrid? Or would these files then have an unaproriate format?


testgrid can read many junit files, however it think the tests that don't execute in one run will be marked skipped so it will get a bit weird with both passed and skipped entries.

testgrid doesn't care about the log file, that's just for humans to understand the failures

**Comment by dims** [comment]
this is off to the weeds :)

/close
