### ISSUE TITLE
fejta-bot issue lifecycle management should be enabled on our other active orgs

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#11054]
Right now it's only enabled on @kubernetes, but we should do the same for @kubernetes-sigs, @kubernetes-incubator, @kubernetes-csi, and @kubernetes-client.

cc: @fejta @Atoms 
/sig contributor-experience

**Comment by cblecker** [comment]
also cc @spiffxp

**Comment by fejta** [comment]
Lol

**Comment by Atoms** [comment]
will there be some decision on this ? :)

**Comment by nikhita** [comment]
PR is here: https://github.com/kubernetes/test-infra/pull/12204

email to k-dev: https://groups.google.com/d/topic/kubernetes-dev/9ps8uNXJ10k/discussion
