### ISSUE TITLE
Deck should be (optionally?) dark themed

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#11064]
**What would you like to be added**:

Deck should have a dark mode!

Actually doing this sanely requires a bunch of CSS/HTML refactoring.

**Why is this needed**:

Spyglass is dark themed and consensus is that this is awesome. The clicking from the light-themed job list to the dark themed spyglass is, however, jarring.

/assign

**Comment by BenTheElder** [comment]
1000% yes <3

**Comment by Katharine** [comment]
/remove-lifecycle stale

one day.
