### ISSUE TITLE
Documetation about jobs is poor

### ISSUE THREAD

**Issue by mskonovalov** [kubernetes/test-infra#11080]
**What happened**:
Some fields are not documented at all:
e.g. `optional` here https://github.com/kubernetes/test-infra/blob/7681225dc7f0a14b1001b36597a42a8ed24b7b71/config/jobs/kubernetes/sig-aws/kops/kops-presubmits.yaml#L12 is not even mentioned in the docs https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md

Also it is not quite clear how are all these fields `always_run`, `optional`, `skip-report` are affect each other.

 In the doc:

> Before a PR is merged, Tide ensures that all jobs configured as required (with skip_report: false) in the presubmits part of the config.yaml file are passing against the latest base branch commit, rerunning the jobs if necessary.

but for my setup with `always_run=false` Tide doesn't retest the PR when master was moved

**What you expected to happen**:

Clear documentation about all fields and how they interfere with each other

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
BTW I think the current concept is that all the jobs are supposed to be run always: for each commit, during the merge, during batching and so on. But what if I want to have 2 types of jobs: 1st is required context (should be on branch protection) but skipped during the retest and branching and 2nd is executed only when PR is finished (so `always_run=false`) but also during the merge and batching. WDYT? is it achievable with this 3 fields `always_run`, `optional`, `skip-report` or is it a significant change to make it explicit?

**Comment by krzyzacy** [comment]
cc @stevekuznetsov @cjwagner

**Comment by stevekuznetsov** [comment]
This should be fixed with the new triggering section https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#standard-triggering-and-execution-behavior-for-jobs
