### ISSUE TITLE
branchprotector and label_sync are unsuably slow

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#11097]
Even if we put them behind `ghproxy`, the internal GitHub client doesn't take into account when tokens are actually used when it throttles requests, so for instance for our [branch protection](https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/periodic-branch-protector/) job we are at 2h40m and our [label sync](https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/periodic-label-sync/) we are at 50 minutes. We need to do something to make these tools faster.

Ideas:

 - make the client throttling token-aware to the proxy in front of it
 - make a stateful version of the tool that assumes it's the only thing managing labels/branch protection and only takes incremental action

/cc @cjwagner @fejta @BenTheElder @krzyzacy 
/area prow/branchprotector
/area label_sync

**Comment by cjwagner** [comment]
I thinking making `ghproxy` add a response header to requests that are served for free would be an easy way to handle this. When the client sees the header it can refund the throttling token used for the request.

**Comment by stevekuznetsov** [comment]
Wouldn't that make the throttler `ghproxy`-aware? Why would we prefer that over just refunding the throttle if we don't use a GitHub rate limit resource?

**Comment by fejta** [comment]
Yes, and I don't see an alternative. We don't know ahead of time whether get calls will get charged. 

The call is only free if both a) the object is cached and b) the object has not been modified since it was cached. Aka the first get call after a put is charged the same as a put.

**Comment by cjwagner** [comment]
There is also the case where the call is free because we coalesced the request with simultaneous requests for the same resource, but the reasoning is totally correct. The downstream client doesn't know how its request was fulfilled unless the proxy provides some additional signal.

**Comment by stevekuznetsov** [comment]
Our requests are not serial ... duh.

**Comment by stevekuznetsov** [comment]
:man_facepalming:
