### ISSUE TITLE
Version not showing up on "ci-" builds

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/test-infra#1112]
On the new "ci-" builds, e.g. [ci-kubernetes-e2e-gce-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-release-1.5), the "Version" in each of the "ci-" run is missing, for example see [ci-kubernetes-e2e-gce-release-1.5/62/](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-release-1.5/62/). So anago is having trouble finding a build for me to cut a beta.

Same thing is true for other test suites like [ci-kubernetes-e2e-gci-gce-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-release-1.5)

CC @fejta @ixdy @david-mcmahon @kubernetes/test-infra-admins

**Comment by fejta** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-release-1.5/62/artifacts/metadata.json -> null??

which is causing this to fire: https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py#L316

Trying to figure out why metadata.json is null...

**Comment by fejta** [comment]
Fix out for review and being tested in parallel.

**Comment by saad-ali** [comment]
Sweet
