### ISSUE TITLE
Reviewer suggestion is problematic when making sweep config changes

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#11138]
So currently whenever I bump kubekins image, blunderbuss would request review from @shyamjvs and @gyuho which might not be the correct behavior :-)

see https://github.com/kubernetes/test-infra/pull/11136
and https://github.com/kubernetes/test-infra/pull/11099
and many more :-)

It should probably request review from owners of config/, or top level owners?

cc @BenTheElder @fejta @cjwagner @stevekuznetsov

**Comment by BenTheElder** [comment]
this behavior does seems strangely specific, it seems to extremely reliably request those specific reviewers 🤷‍♂️
