### ISSUE TITLE
Hook Buildifier Plugin Help Not Working

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11137]
**What happened**:
In deck plugin help, buildifier plugin is not displayed. It shows the following error:
```
{"client":"plugin-help","component":"hook","level":"warning","msg":"No help is provided for plugin \"buildifier\".","time":"2019-02-05T22:53:21Z"}
```

**What you expected to happen**:
I expected to see plugin help for buildifier plugin.

**How to reproduce it (as minimally and precisely as possible)**:
Enable buildifier plugin, access plugin help in deck.

**Anything else we need to know?**:

**Comment by stevekuznetsov** [comment]
I see this intermittently as well
