### ISSUE TITLE
Have an e2e test for Prow?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#11157]
Today we can at least do:
- Kubetest up a cluster
- Deploy starter.yaml
- Wait for a few minutes?
- Make sure echo-test can finish, things are in right namespace, and nothing is crashing, more checks you can name, etc
- Dump logs from all controller pods

We also can add more complex deployment there, have pre-generated github secrets in the cluster and point to a non-important repo, make some fake PRs, @BenTheElder also have idea to have some bots randomly spamming in the repo and open a fake PR / make comments / do some review / lgtm / ... :smirk: 

@fejta @stevekuznetsov @cjwagner @spiffxp  thoughts?

**Comment by BenTheElder** [comment]
ER - to elaborate on "spamming" ...

We could do a ["subreddit simulator"](https://knowyourmeme.com/memes/sites/subreddit-simulator) but for github - an org simulator (hello @fejta and @fejtaverse)!

Only half serious, but it could be interesting to run a canary prow against a bot controlled github environment :^)

**Comment by stevekuznetsov** [comment]
I think I would like to see a more in-depth design proposal, the largest question for me in this process would be how we appropriately balance cost of implementation with benefits to the ecosystem. I would worry that it's hard to test the complexity of our deployments and config. As an example, both the OpenShift and CNCF Prow deployments have complex configurations and it's interesting to see how incidentally things that did not ever come up as failures for us managed to break in the CNCF deployment.

**Comment by BenTheElder** [comment]
Right, so actually running a prow somewhere that does _something_ and verifying that it works is a pretty easy smoke test though
- create prow deployment
- configure no-op job
- verify that the job runs

As for the github simulation, it's basically just some scheduled commentor robots for most of it. The expensive part is implementing validation of prow's behavior.

I have no intention of any variation of this currently, but I did want to share the idea at some point :-)

**Comment by krzyzacy** [comment]
Similar to k8s, we can have different e2e scenarios / different test cases for different deployments hopefully? If something happens that we didn't catch, we then can improve our e2e coverage to prevent similar thing from happening again?

> I think I would like to see a more in-depth design proposal

Just want a brief brainstorm first before dive too deep :-) Maybe one day we also want to consider version prow releases and have a status dashboard?

**Comment by stevekuznetsov** [comment]
> Right, so actually running a prow somewhere that does something and verifying that it works is a pretty easy smoke test though

Right, and it would not catch a lot of issues, so low development cost --> low reward IMO. Seems like a good idea, for what it's worth.

> Similar to k8s, we can have different e2e scenarios / different test cases for different deployments hopefully?

Right, this is the sliding scale of effort to reward I was talking about.
