### ISSUE TITLE
Support trigger | retest in gerrit

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#11162]
I think multiple people is asking about this -

I was kinda waiting for unify the interface between github/gerrit but that seems never gonna happen, maybe we should just implement a in-house version of comment handling for gerrit.

(Only for triggering, afaik. We don't need things like lgtm and label management yet)

cc @amwat @AishSundar @cjwagner @crimsonfaith91

**Comment by crimsonfaith91** [comment]
@krzyzacy For my use case, yes - only triggering for retest is required.
cc @mortent too.

**Comment by stevekuznetsov** [comment]
Didn't we just have a breakout session about a generic interface between social git hosting sites and Prow? Why do you think this won't happen?

**Comment by krzyzacy** [comment]
@stevekuznetsov obviously I missed that session - is there a meeting note?

**Comment by stevekuznetsov** [comment]
In our breakouts dir of GDrive: https://drive.google.com/open?id=1CSBLpp9EC-6F04bO_VcHwLM6sPYX9sWFrATQPWnrDUg

**Comment by AishSundar** [comment]
yes plz !!! for our need both but in that order :) 
(i) comment handling (/retest and /e2e-presubmit) 
(ii) label management 

(i) itself will be a huge improvement

**Comment by krzyzacy** [comment]
Our gerrit doesn't support webhooks which makes me :thinking: how it fits into Scallywag

**Comment by stevekuznetsov** [comment]
Scallywag wanted to both handle generic events coming in as well as generic api calls going out

**Comment by krzyzacy** [comment]
sg - I think depend on timeline we can decide if we want to implement a quick workaround first or not.

**Comment by AishSundar** [comment]
we would really appreciate a quick workaround first to unblock multiple usecases on our end. Due to lack of trigger support in Gerrit we are doing some wonky workarounds to trigger presubmits which makes developer workflow difficult.

**Comment by krzyzacy** [comment]
(this is currently deployed and should be functional, feel free to try out for gerrit users)

**Comment by crimsonfaith91** [comment]
@krzyzacy I tried with `/retest` and `retest`, but none triggers re-running of pre-submit tests. Is there a document that I can refer to?

**Comment by crimsonfaith91** [comment]
Oops, it should be `/test all` as we are merging GitHub and gerrit.
I verified that the command works!

**Comment by krzyzacy** [comment]
@crimsonfaith91 it supports `/test all` and `/test job-foo` now. `/retest` is not implemented.

(Keep the issue open as the PR has not been merged yet)

**Comment by krzyzacy** [comment]
/close

thanks @amwat !
