### ISSUE TITLE
Auto-bump kubetest

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#11177]
like what we do for prow - bump after each kubetest change

cc @BenTheElder @neolit123 @Katharine

**Comment by BenTheElder** [comment]
don't we already have an issue for this?

**Comment by neolit123** [comment]
i've added this:
https://github.com/kubernetes/test-infra/issues/10958

**Comment by krzyzacy** [comment]
lol yeah - didn't find that
