### ISSUE TITLE
Containerd node e2e test is failing.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/test-infra#11196]
It fails after https://github.com/kubernetes/test-infra/pull/11045.

It seems that GOPATH is not set. https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/containerd_cri/1043/pull-cri-containerd-node-e2e/1132/build-log.txt

**Comment by krzyzacy** [comment]
/assign @fejta 

hummmmm I guess.. the $GOPATH from entrypoint is not in the steps?

**Comment by krzyzacy** [comment]
I still feel we should not remove run_after_success that quickly before we properly migrated our users..
:man_shrugging: 

trying with https://github.com/kubernetes/test-infra/pull/11210

**Comment by Random-Liu** [comment]
@krzyzacy The test can run now, but the artifacts is not properly generated.
For example http://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/containerd_cri/1043/pull-cri-containerd-node-e2e/1144/artifacts/

**Comment by krzyzacy** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/containerd_cri/1048/pull-cri-containerd-node-e2e/1156 looks fine, recent runs of https://prow.k8s.io/?job=pull-cri-containerd-node-e2e looks like legit failures.
