### ISSUE TITLE
Prow schedules pods into service cluster

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#11204]
one thing I found out is there are hundreds of un-schedulable pods in the service cluster, trying to add more nodes, still investigating...

cc @spiffxp @Katharine @BenTheElder 

/assign

**Comment by krzyzacy** [comment]
We have workloads got scheduled to our service cluster which should not

**Comment by BenTheElder** [comment]
[triage ongoing in #testing-ops and offline between me, @krzyzacy @Katharine]

**Comment by BenTheElder** [comment]
AFAIK this is fixed now by rolling back, a notice was sent to Kubernetes-Dev last night.

**Comment by stevekuznetsov** [comment]
Fixed by #11209

**Comment by krzyzacy** [comment]
this is fixed in HEAD and reverted in k8s prow deployment, closing the issue.
