### ISSUE TITLE
prow: getting_started_deploy.md: changing config.yaml doesn't work

### ISSUE THREAD

**Issue by listx** [kubernetes/test-infra#11212]
**What happened**:

Tried to edit `config.yaml` as described here: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#add-more-jobs-by-modifying-configyaml

but then the config couldn't pass muster for checkconfig.

**What you expected to happen**:

Running
```
bazel run //prow/cmd/checkconfig -- --config-path=path-to/config.yaml
```

should be OK, but I get:

```
FATA[0000] Error loading Prow config.                    component=checkconfig error="no default decoration config provided for plank"
```

**How to reproduce it (as minimally and precisely as possible)**:
Just follow the instructions to https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#add-more-jobs-by-modifying-configyaml

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

Removing "decorate: true" from presubmits and postsubmits seems to make the error go away.

**Comment by stevekuznetsov** [comment]
@BenTheElder do we just want to suggest adding the stanza that is in your config? We'd want the bump scripts to update the image tags though

**Comment by BenTheElder** [comment]
Yeah I'm wondering if we should just put this in starter.yaml and make it get bumped along with prow.

**Comment by ixdy** [comment]
@stevekuznetsov what stanza were you talking about?

**Comment by stevekuznetsov** [comment]
This one:

https://github.com/kubernetes/test-infra/blob/563bcb31644e30832fe6a5019d6107d3ec49f07f/prow/config.yaml#L6-L19

**Comment by ixdy** [comment]
The issue I was actually running into is that we have the job configurations in a separate YAML (similar to the way it's done in k/t-i) and forgot to provide both `--config-path` and `--job-config-path` to `mkpj`.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle rotten
With @Katharine auto-bumper it should be trivial to update the image versions in this file to match those that are currently deployed.
