### ISSUE TITLE
Prometheus Metrics for Deck

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11223]
**What would you like to be added**:
I would like deck to expose prometheus metrics via promhttp and prometheus push. These metrics should include go metrics and application specific metrics, status codes of responses, duration, etc.

**Why is this needed**:
At the moment there are no prometheus metrics available for deck, so we are blind to interactions occuring at that layer.

**Comment by stevekuznetsov** [comment]
The next focus for my team will be fleshing these out, but do not expect pushgateway support.

/assign
/area prow/deck

**Comment by midnightconman** [comment]
Excellent, please let me know if I can help out.

**Comment by stevekuznetsov** [comment]
Specific metrics you'd like to see would be helpful, in case we don't think of everything you wanted! For a first pass I wanted to do user facing things like page loads, timing and errors.

**Comment by midnightconman** [comment]
@stevekuznetsov

Do you have an update on this for us? Would be nice to see some usage metrics from deck. :smile:

**Comment by stevekuznetsov** [comment]
As before, specific metrics you'd like to see would be useful. We're about one sprint away from prioritizing this, next sprint boundary is this upcoming week. So expect to see movement soon :)

**Comment by midnightconman** [comment]
Sweet, looking forward to it.

I would like to see status code counts by handler, duration histograms for requests and responses, response size histograms, and log file size histograms. Maybe some metrics from pr status, like github calls, retries, durations, etc.

**Comment by stevekuznetsov** [comment]
Implemented in 

#12839 #12958 #12624 #12786 

/close
