### ISSUE TITLE
Ability to Override prstatus Github API Endpoint

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11224]
**What would you like to be added**:
I would like the ability to override the static github api value in prstatus, so I can use prstatus with other github endpoints.

**Why is this needed**:
This is required if people would like to use prstatus with other github endpoints (like Github Enterprise).

**Comment by stevekuznetsov** [comment]
/area prow/deck

Adding this as a configuration option to deck SGTM

/cc @cjwagner @Katharine 

@midnightconman do you think you can take this one on?

**Comment by midnightconman** [comment]
I would love to, do you think we can add this to `config.yaml` and possibly as a root object? I was thinking something like this would be nice:

config.yaml
```
github:
  link-url: https://github.com
  api-link-url: https://api.github.com
```

Thoughts?

**Comment by stevekuznetsov** [comment]
Hmm. No strong feelings on it, but if we go that way we should remove the flags and use the config as one source of truth. Not sure how this would pay with the upcoming work to make social hosting sites generic.

**Comment by midnightconman** [comment]
Sounds good to me... I'll add it as a root object to config and we can chat about how we wan't to deprecate flags in the PR. Sound good?

**Comment by stevekuznetsov** [comment]
Would like @cjwagner to weigh in before you write code in case we aren't all in agreement on the direction

**Comment by cjwagner** [comment]
Switching from flags to config sounds fine to me. The API URL field will need to be a slice though to allow fallback endpoints to be specified as with the `--github-endpoint` flag.

**Comment by midnightconman** [comment]
Sweet :smile: I get started on this.

These particular options were meant for visual links, the specific example I am starting with is the `OWNERS` links that are commented back to github. Since these will be `final` links for user consumption, I thought it would be best to have a separate parameter. This separate parameter allows people to use whatever route url they like and still specify a sane final destination for user links.

For replacing github and git flag endpoints, I'll start with a slice for endpoint (rename it `api-endpoint`) and a url.URL for git endpoint (rename it endpoint).

Does that sound good? Also, how do we want to deprecate the flags?

**Comment by midnightconman** [comment]
This PR is related to this change: https://github.com/kubernetes/test-infra/pull/11486

**Comment by midnightconman** [comment]
After looking at this for a while, it seems the best course of action is to allow overriding of oauth2 `auth_url` and `token_url`... I have an issue open for this specific change: https://github.com/kubernetes/test-infra/issues/12312

**Comment by AWKIF** [comment]
/remove-lifecycle stale
Any news on this ?
