### ISSUE TITLE
Ability to Override approver Plugin Github Link URL

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11226]
**What would you like to be added**:
I would like the ability to override the github html link url that the approver `APPROVALNOTIFIER` plugin uses to create comments on github.

**Why is this needed**:
If people are using `approve` plugin with Github Enterprise, the OWNERS links it creates in comments are pointing to `github.com` endpoints.

**Comment by stevekuznetsov** [comment]
/area prow/hook

Adding this as a configuration option to the plugin SGTM

/cc @cjwagner

**Comment by stevekuznetsov** [comment]
@midnightconman do you think you can take this one on?

**Comment by midnightconman** [comment]
I can take this one too... I think it would be nice to be able to share the same setting for this and `prstatus`, how does that sound to you guys?

I was thinking about making this a root `config.yaml` object, something like:

config.yaml
```
github:
  link-url: https://github.com
  api-link-url: https://api.github.com
```

Thoughts?
