### ISSUE TITLE
dog test is hitting gcs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#11247]
Try to run [the dog test](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/dog/dog_test.go), it's trying to query gcs for this-is-fine images

**Comment by matthyx** [comment]
@krzyzacy can you elaborate a bit? Otherwise we should remove `help-wanted`...

**Comment by krzyzacy** [comment]
@matthyx try the test without internet, it would fail

**Comment by matthyx** [comment]
I'll look into it, poor doggo...

**Comment by spiffxp** [comment]
/assign @matthyx 
Thanks Matt!

**Comment by matthyx** [comment]
We have the same "issue" with cats, I will apply the same strategy if it's fine...
/meow
