### ISSUE TITLE
Running kubetest with precompiled kubectl

### ISSUE THREAD

**Issue by Mikulas** [kubernetes/test-infra#11254]
Currently `kubetest` fails with
> It looks as if you don't have a compiled kubectl binary
even when kubectl is in `client/bin/kubectl` (and in $PATH, but that is secondary issue).

This can be fixed user-side by putting the precompiled binary into `_output/bin` or other paths defined by https://github.com/kubernetes/kubernetes/blob/d0439d417b0563d44c65b6e400e2070964dea7d1/cluster/clientbin.sh#L86

Is there a reason kube-test requires a locally compiled binary? With the new containerized kubernetes build, it is quite hard to build a custom container with kubetest as it would require docker in docker during image build (which is not currently possible).

This is a followup to #8698

/sig contributor-experience
/kind documentation 
/area kubetest

**Comment by BenTheElder** [comment]
Cc @krzyzacy

kubectl requirements depend on the --deployment used FWIW, the newer ones behave differently.

**Comment by krzyzacy** [comment]
fwiw https://github.com/kubernetes/test-infra/blob/09eff5a3dc0f8bdf234ff32445056863ed6c49cf/kubetest/kind/kind.go#L364-L375 already handles using kubectl from $PATH

can you paste your logs for your use-case?

**Comment by Mikulas** [comment]
Sure, the full log is this:
```
+ export PATH=/src/kubernetes/client/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/src/kubernetes/client/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ which kubectl
/src/kubernetes/client/bin/kubectl
+ kubetest --test --provider=skeleton '--test_args=--ginkgo.focus=\[Conformance\]'
2019/02/13 12:11:05 process.go:153: Running: ./hack/e2e-internal/e2e-status.sh
Skeleton Provider: prepare-e2e not implemented
It looks as if you don't have a compiled kubectl binary

If you are running from a clone of the git repo, please run
'./build/run.sh make cross'. Note that this requires having
Docker installed.

If you are running from a binary release tarball, something is wrong.
Look at http://kubernetes.io/ for information on how to contact the
development team for help.
2019/02/13 12:11:05 process.go:155: Step './hack/e2e-internal/e2e-status.sh' finished in 97.2496ms
2019/02/13 12:11:05 main.go:297: Something went wrong: encountered 1 errors: [error during ./hack/e2e-internal/e2e-status.sh: exit status 1]
```

This is from latest kubetest from `go get -u k8s.io/test-infra/kubetest` and somewhat recent kubernetes 1.13.2.

Since creating the issue I've found that the kubectl is not the only required binary and the others are mostly not packaged with official releases. Even so, I believe the error message is misleading as I surely do have a kubectl binary (as shown by the which call).

Furthermore, contrary to the message, the binary release tarball of kubernetes no longer contains the binaries.

**Comment by Mikulas** [comment]
To be honest I'm not quite certain what the initial issue was.

/close
