### ISSUE TITLE
Where do I download kubernetes-test for linux/amd64?

### ISSUE THREAD

**Issue by OlegLoewen** [kubernetes/test-infra#11279]
Where do I download kubernetes-test for a specific operating system like linux/amd64?
I figured there is a kubernetes-test.tar.gz tar which contains all binaries (darwin/amd64, windows/amd64, linux/amd64, linux/arm64, ...): https://storage.googleapis.com/kubernetes-release/release/v1.13.3/kubernetes-test.tar.gz 

Unfortunately this file is **too large (1.23 GB)** to be downloaded periodically on new clusters to test (expensive).
Is there a way to download the kubernetes-test for the specific operating system instead all of them?

**Comment by neolit123** [comment]
there is ongoing effort to break the test tarball into smaller elements:
https://github.com/kubernetes/enhancements/issues/714
https://github.com/kubernetes/enhancements/pull/701

cc @ixdy 

AFAIK downloads such as this are WIP:
https://storage.googleapis.com/kubernetes-release/release/v1.13.3/kubernetes-test-linux-amd64.tar.gz

> Unfortunately this file is **too large (1.23 GB)** to be downloaded periodically on new clusters to test (expensive). Is there a way to download the kubernetes-test for the specific operating system instead all of them?

you can technically download once, extract relevant platform binaries and upload them to a storage location of your choice. then re-use only the binaries of interest, but but yes, this has to happen at least once per release.

**Comment by ixdy** [comment]
yep, we're planning to have platform-specific test tarballs starting with k8s 1.14 (though this is not yet implemented).

**Comment by ixdy** [comment]
going to close this as a dupe of kubernetes/enhancements#714; please follow that issue for updates.
/close

**Comment by ixdy** [comment]
@OlegLoewen just FYI, the CI jobs on the master branch of kubernetes are now producing arch-specific `kubernetes-test` tarballs. The next v1.14 beta release should also have these arch-specific tarballs available.

**Comment by OlegLoewen** [comment]
> @OlegLoewen just FYI, the CI jobs on the master branch of kubernetes are now producing arch-specific `kubernetes-test` tarballs. The next v1.14 beta release should also have these arch-specific tarballs available.

Great, thanks for the note. Looking forward for the first version which supports this.

**Comment by ixdy** [comment]
v1.14.0 has been released, which is the first release containing platform-specific test tarballs.

Instead of downloading [kubernetes-test.tar.gz](https://storage.googleapis.com/kubernetes-release/release/v1.14.0/kubernetes-test.tar.gz), you can now download [kubernetes-test-portable.tar.gz](https://storage.googleapis.com/kubernetes-release/release/v1.14.0/kubernetes-test-portable.tar.gz) (for the portable scripts and testing manifests) as well as [kubernetes-test-linux-amd64.tar.gz](https://storage.googleapis.com/kubernetes-release/release/v1.14.0/kubernetes-test-linux-amd64.tar.gz) (for platform-specific binaries).

**Comment by OlegLoewen** [comment]
> v1.14.0 has been released, which is the first release containing platform-specific test tarballs.
> 
> Instead of downloading [kubernetes-test.tar.gz](https://storage.googleapis.com/kubernetes-release/release/v1.14.0/kubernetes-test.tar.gz), you can now download [kubernetes-test-portable.tar.gz](https://storage.googleapis.com/kubernetes-release/release/v1.14.0/kubernetes-test-portable.tar.gz) (for the portable scripts and testing manifests) as well as [kubernetes-test-linux-amd64.tar.gz](https://storage.googleapis.com/kubernetes-release/release/v1.14.0/kubernetes-test-linux-amd64.tar.gz) (for platform-specific binaries).

Is there any guide which describe where to put these things to get kubetest running?
