### ISSUE TITLE
Linux foundation CLA bot malfunction 

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#1130]
https://github.com/kubernetes/kops/pull/950

I think asking for signing the CLA is sufficient ;) The bot tagged the PR 10+ times. Attack of the CLA bot

**Comment by foxish** [comment]
Looking into this. Haven't seen it elsewhere, and makes me wonder if it was a github glitch. We certainly don't fire off multiple messages unless we get multiple status events from the LF status. Perhaps we should check comments before posting a new one.

@chrislovecnm, does kops already have some bot running?

**Comment by foxish** [comment]
It looks like the robot had no privileges to write to the repo which caused the hiccup. This should be fixed now.
Before fix: https://github.com/kubernetes/kops/pull/952
After fix: https://github.com/kubernetes/kops/pull/953

We shouldn't be letting the presence of the label tell us whether we have dealt with the issue already. We can receive duplicate events and we should see if we have already commented on the PR to find out if we should comment again. Will track there in this issue.

**Comment by spxtr** [comment]
> We can receive duplicate events and we should see if we have already commented on the PR to find out if we should comment again.

Actually I'm not sure that's a great idea. Receiving duplicate events is so rare that I don't want to optimize around it. Other plugins don't bother, either.

Instead, it might be worth only posting the comment if the label is added correctly.

**Comment by sarahnovotny** [comment]
@foxish i think this is another issue of multiple notices -- https://github.com/kubernetes-incubator/service-catalog/pull/57

if it's not, we can escalate to CNCF as @arschles has signed the CCLA as a Deis employee.

**Comment by sarahnovotny** [comment]
for completeness, can you verify @arschles signature on the CNCF CCLA for Deis, @caniszczyk ?

**Comment by arschles** [comment]
Note that my account is under the aaron@deis.com email address

**Comment by caniszczyk** [comment]
He's there, but I believe he should login to http://identity.linuxfoundation.org/projects/cncf and make sure his github account is properly associated.

![screen shot 2016-11-29 at 2 44 21 pm](https://cloud.githubusercontent.com/assets/63777/20728259/7cde8606-b642-11e6-877e-9ababf13dd4a.png)

**Comment by arschles** [comment]
@caniszczyk see below for what happens when I try to associate my GH account

<img width="1017" alt="screen shot 2016-11-29 at 2 09 12 pm" src="https://cloud.githubusercontent.com/assets/70865/20731063/7b38eb16-b63d-11e6-9202-36a3ce02a59c.png">

I have a personal account (arschles@gmail.com) to which I've associated, then from which I removed, my GH account. Not sure if that could contribute to this issue.

**Comment by arschles** [comment]
@caniszczyk any progress on the above issue? Also, if there's a better issue on which I should discuss this, or if I should create a new issue just for this problem, please let me know. Thanks.

**Comment by rmmh** [comment]
This isn't happening anymore.
