### ISSUE TITLE
wrong version of kubekins-test image being used in PR and CI

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#1133]
`ci-kubernetes-test-go-release-1.4` has been continuously failing since https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go-release-1.4/8/, which correlates in time to when #1068 was merged.

It appears that all of the `ci-kubernetes-test-go` and `-verify` builds are using the 1.5 version of the `kubekins-test` image, whereas previously they were using version-specific versions.

As a result, verify/unit runs are now broken on everything before `release-1.5`. This is also hitting developers trying to cherry-pick to release branches, e.g. https://github.com/kubernetes/kubernetes/pull/36786#issuecomment-261689511.

We need to restore the previous behavior, possibly by looking at `git` tags to decide which image version to use.

cc @fejta @spxtr @krzyzacy @krousey

**Comment by ixdy** [comment]
we'll need to do something similar for `kubekins-e2e` soon, too.

**Comment by krzyzacy** [comment]
oh yep I closed that E2E image PR... I'll handle this tomorrow

**Comment by ixdy** [comment]
thanks @krzyzacy! feel free to assign me a PR to review and I'll prioritize it. (it's pretty important, since several unit/integration/verify jobs are testing the wrong thing right now.)
