### ISSUE TITLE
PR Dashboard doesn't work on private repo

### ISSUE THREAD

**Issue by mskonovalov** [kubernetes/test-infra#11365]
**What happened**:
PR Dashboard shows 0 PRs

**What you expected to happen**:
pr dashboard should show some PRs

**How to reproduce it (as minimally and precisely as possible)**:
Repository is private, 
org name starts with capital letter,
query from logs works on GH web UI

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
no errors in logs

```
{"client":"pr-status","component":"deck","level":"info","msg":"Search for query \"is:pr state:open author:mskonovalov repo:\"Canva/canva\"\" cost 1 point(s). 4999 remaining.","time":"2019-02-19T04:19:38Z"}
{"client":"pr-status","component":"deck","level":"info","msg":"Search for query \"is:pr state:open author:mskonovalov repo:\"Canva/canva\"\" cost 1 point(s). 4998 remaining.","time":"2019-02-19T04:19:46Z"}
{"client":"pr-status","component":"deck","level":"info","msg":"Search for query \"is:pr state:open author:mskonovalov repo:\"Canva/canva\"\" cost 1 point(s). 4997 remaining.","time":"2019-02-19T04:19:51Z"} 
```

**Comment by mskonovalov** [comment]
cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Looks like we might mishandle casing in our queries and/or config

/cc @cjwagner @Katharine
