### ISSUE TITLE
pull-kubernetes-kubemark-e2e-gce-big is running ginkgo but skipping all tests

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#11388]
Example: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73866/pull-kubernetes-kubemark-e2e-gce-big/38451/?log#log

> I0220 07:49:54.054] Ran 0 of 3004 Specs in 0.674 seconds
I0220 07:49:54.066] SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 3004 Skipped PASS

This doesn't seem right. Seems like either we're skipping tests we should run, or we're firing up the e2e suite without actually using it...

/kind bug
/area jobs
/assign @wojtek-t

**Comment by wojtek-t** [comment]
This is working as intended.
We recently switch scalability to the new framework (ClusterLoader). Scalability tests are no longer e2e-ginkgo tests. You can look into logs and you see things like this:
```
W0220 08:03:28.940] I0220 08:03:28.934457   94412 clusterloader.go:145] Test Finished
W0220 08:03:28.940] I0220 08:03:28.934463   94412 clusterloader.go:146]   Test: testing/density/config.yaml
W0220 08:03:28.952] I0220 08:03:28.934468   94412 clusterloader.go:147]   Status: Success
```

If it would be possible to skip firing up e2e suite, then it would be great - it's currently not possible.

**Comment by BenTheElder** [comment]
Huh? This is 100% possible, don't set `--test` if you aren't using ginkgo?
https://github.com/kubernetes/test-infra/blob/a6f65f395440df754f2ce8c7bd62e4f1a9c5485c/scenarios/kubernetes_e2e.py#L546

**Comment by krzyzacy** [comment]
```
--test=false --test_args=--ginkgo.focus=xxxx '--test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh' --test-cmd-args=cluster-loader2 --test-cmd-args=--nodes=500 --test-cmd-args=--provider=kubemark --test-cmd-args=--report-dir=/workspace/_artifacts --test-cmd-args=--testconfig=testing/density/config.yaml --test-cmd-args=--testconfig=testing/load/config.yaml --test-cmd-args=--testoverrides=./testing/load/kubemark/500_nodes/override.yaml --test-cmd-name=ClusterLoaderV2
```

that looks about right, except for `--test_args=--ginkgo.focus=xxxx`?

**Comment by BenTheElder** [comment]
@krzyzacy test-cmd should be totally orthogonal to ginkgo, this is almost definitely a bug.

we shouldn't be publishing ginkgo results when we don't run it, or paying the time to build / run it. :man_shrugging:

**Comment by BenTheElder** [comment]
if ginkgo runs `--test_args=--ginkgo.focus=xxxx` has to be set :confused: -- we should really disentangle this going forward with kubetest2... I don't yet understand why this needs to run ginkgo but I'm fairly certain that it should not.

**Comment by krzyzacy** [comment]
@wojtek-t I suggest we retire the --kubemark logic and move these into clusterloader, or we can safely remove the ginkgo call in https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L639-L649 now afaik?

**Comment by krzyzacy** [comment]
wait for a bump

**Comment by krzyzacy** [comment]
checked https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/75124/pull-kubernetes-kubemark-e2e-gce-big/40753/build-log.txt doesn't have the empty ginkgo call anymore
