### ISSUE TITLE
"broken test run" with no junit output should be logged separately

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#1138]
The following typically means there's an infrastructure problem:
"Run so broken it didn't make JUnit output!"

Whereas the following could mean a test suite setup or flakiness:
"Multiple broken tests:"

We mix them up in the same issue and it becomes difficult to untangle/triage the issues.

Can we please separate them? So the infrastructure issues can be quickly identified and closed and leave the flakiness in the test suite itself for others to triage?

Example : https://github.com/kubernetes/kubernetes/issues/34679

Thanks,
Dims

**Comment by fejta** [comment]
/assign
/close

We now create junit results in this scenario
