### ISSUE TITLE
Add prow job configs for container image promotion process

### ISSUE THREAD

**Issue by listx** [kubernetes/test-infra#11394]
The [OSS promoter](github.com/GoogleCloudPlatform/k8s-container-image-promoter) is ready to be used as part of a Prow job to handle Docker container image promotions for the community. Add prow configs that can handle presubmits/postsubmits from a repository that host promoter manifest files.

See https://docs.google.com/document/d/16VBfsFMynA7tObzuZGPpw-sKDKfFc_T5W_E4IeEIaOQ/edit# (Feb 20 2019 meeting notes).

**Comment by hh** [comment]
@thockin and @listx have you scheduled this?

If you schedule it starting after 5AM and ending before 7AM PST (my Saturday), I'd like to be part of that session.

**Comment by listx** [comment]
@hh Hi Hippie, I don't know how these sessions usually go down but I'm assuming it'll be like some sort of hackathon? And will we be using a zoom meeting...? FWIW I'll be online and available during your requested time zone on Friday.

**Comment by listx** [comment]
The PR for this is #11414

**Comment by listx** [comment]
Doh, forgot to close this with #11414 being merged.

/close
