### ISSUE TITLE
`/skip` plugin does not clear statuses of deleted (non-blocking) jobs (and tide blocks on it too!)

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#11391]
We removed a job yesterday. it was a non-blocking job [1]. however we are unable to clear the status(es) in existing PRs using `/skip`.

Also tide seems to be treating it as a required thing - `**tide ** Pending — Not mergeable. Job pull-kubernetes-local-e2e-containerized has not succeeded.`

[1] https://github.com/kubernetes/test-infra/pull/11338

**Comment by stevekuznetsov** [comment]
This is WAI -- those jobs do not exist in the config and we have no knowledge of them. We should use `migratestatus` to fix this instance and deploy the `status-reconciler` to not have to deal with this in the future.
