### ISSUE TITLE
CNFC-CLA Doesn't refresh on force push

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#1139]
Example seen here:

https://github.com/kubernetes/kops/pull/956

When the force push happens (with only authorized authors), the label is not refreshed.

@kris-nova

**Comment by chrislovecnm** [comment]
cc: @spxtr

**Comment by foxish** [comment]
I think this has to do with the Cncf cla status which the labeling bot relies on. Occasionally it happens that the status doesn't get refreshed. Will follow up with the LF.

**Comment by spiffxp** [comment]
Closing because the CNCF's CLAbot isn't under our control.  It's not presently open source (ref: https://github.com/cncf/foundation/issues/3) so I'm not sure what it's behavior is with regard to force pushes vs. additional comments on a PR / issue
