### ISSUE TITLE
agent-ctl.sh should specify --project and --zone for all gcloud calls

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#114]
Not sure how it even worked to start with.

**Comment by fejta** [comment]
Meh

**Comment by ixdy** [comment]
I think it's pretty dangerous that the script happens to use whatever project you happen to have set in your config.

**Comment by spxtr** [comment]
Or it should maybe check at the start if you are in `kubernetes-jenkins` or `kubernetes-jenkins-pull` and fail otherwise.
