### ISSUE TITLE
Repurpose k8s-merge-robot as k8s-github-robot

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#11402]
**What should be cleaned up or changed**:
Since we've turned down the submit queue, k8s-merge-robot has sat around basically unused.  It has a github token with the same privileges as k8s-ci-robot.  Let's use it for automation that manages github configuration, and leave the k8s-ci-robot token for prow's interactions with github related to CI.  This will give us some breathing room while we figure out other ways to mitigate our github token usage limits for prow.k8s.io (like using an app instead of personal access token)

Suggest:
- renaming k8s-merge-robot to k8s-github-robot
- create a suitable avatar that makes it clear it's the evil twin of k8s-ci-robot
- use k8s-github-robot's token for utilities such as:
  - peribolos
  - label_sync
  - branch-protector?
  - migratestatus
  - etc.

**Provide any links for context**:

**Comment by spiffxp** [comment]
I've successfully renamed k8s-merge-robot, we now have https://github.com/k8s-github-robot

**Comment by stevekuznetsov** [comment]
Let's call out `status-reconciler` specifically?

**Comment by stevekuznetsov** [comment]
All this SGTM

**Comment by spiffxp** [comment]
I accepted all of the org invites, so at this point k8s-github-robot's token should be good for things.  Now to see if it's even in the prow cluster to begin with

**Comment by spiffxp** [comment]
Checking in on label-sync first led me to https://github.com/kubernetes/test-infra/pull/11421

Take two...

**Comment by nikhita** [comment]
> renaming k8s-merge-robot to k8s-github-robot
> create a suitable avatar that makes it clear it's the evil twin of k8s-ci-robot

These are done

> use k8s-github-robot's token for utilities such as: 

Is this done?

**Comment by spiffxp** [comment]
/milestone v1.15
/assign @cjwagner 
We have talked about this a few times offline. I'm unable to push it forward directly myself.  Do we want to take care of this?  Should we include this in rate limit experiments mentioned in https://github.com/kubernetes/test-infra/issues/12510 ?

**Comment by cjwagner** [comment]
Yes, lets include `k8s-github-robot` in the rate limit experiments.
The main thing we need to do to set this up is configure a new ghproxy instance for use with this token. This shouldn't be too much work, but I'm trying to prioritize some other tasks and this is low priority so I'll probably return to this after Kubecon.

**Comment by spiffxp** [comment]
/area github-management
I think we should change the peribolos jobs to use this token

**Comment by nikhita** [comment]
> The main thing we need to do to set this up is configure a new ghproxy instance for use with this token. 

Happy to take this up, once https://github.com/kubernetes/test-infra/pull/13683 is merged since it does the same for @k8s-triage-robot.

/assign

**Comment by stevekuznetsov** [comment]
We're using one ghproxy for two robots, no issue

**Comment by spiffxp** [comment]
/assign @ameukam 
who has worked on setting up ghproxy for k8s-infra-prow-build-trusted ref: https://github.com/kubernetes/k8s.io/issues/843

We should deploy this token over there, create a canary job and verify that the proxy is being used instead of direct github access.  I would recoemmend a peribolos job in dry-run mode (run without a `--confirm` flag).

We can then migrate all github-related jobs to the k8s-infra trusted cluster.  Jobs that run there should live in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/wg-k8s-infra/trusted/wg-k8s-infra-trusted.yaml

Looking at https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml I think the jobs to migrated would be:
- post-org-peribolos
- ci-org-peribolos
- ci-test-infra-label-sync

I think these jobs should NOT be migrated even though they use ghproxy. They are more specific to prow.k8s.io and it probably makes more sense to keep using k8s-ci-robot
- ci-test-infra-branchprotector
- post-test-infra-reconcile-hmacs

**Comment by spiffxp** [comment]
I don't have access to secrets in the prow.k8s.io cluster, I will need to see if I can login as k8s-github-robot.

**Comment by ameukam** [comment]
> I don't have access to secrets in the prow.k8s.io cluster, I will need to see if I can login as k8s-github-robot.

@spiffxp Any update about this ?

**Comment by BenTheElder** [comment]
2020 is over 🙃

**Comment by spiffxp** [comment]
Having trouble digging up credentials for k8s-github-robot, I'll ping back here when I have more info

**Comment by spiffxp** [comment]
The test job is failing (whoops I must have missed the tab name): https://testgrid.k8s.io/sig-contribex-k8s-triage-robot#api-review-help

It seems like bad credentials? https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8s-triage-robot-testcomment/1418328613631037440

So I logged into k8s-triage-robot, and sure enough, no personal access tokens at all.

Created a new one, updated the secret, waiting for the next job run.

**Comment by spiffxp** [comment]
```
Failed run: encoutered 2 failures: [Failed to apply comment to kubernetes/test-infra#11402: the GitHub API request returns a 403 error: {"message":"Must have admin rights to Repository.","documentation_url":"https://docs.github.com/rest/reference/issues#create-an-issue-comment"} Failed to apply comment to kubernetes/org#2465: the GitHub API request returns a 403 error: {"message":"Must have admin rights to Repository.","documentation_url":"https://docs.github.com/rest/reference/issues#create-an-issue-comment"}]
```

**Comment by spiffxp** [comment]
Fixed the token, it needed `scope:public_repo`

The query also didn't include `repo:kubernetes/test-infra`, so it ended up commenting here: https://github.com/kubernetes/org/issues/2465#issuecomment-885372510

**Comment by spiffxp** [comment]
Orrrr apparently github's search returned one issue the first time, and two the second.  But that's it.  Should see no more spam at this point.

Opened https://github.com/kubernetes/test-infra/pull/22997 to switch all the fejta-bot jobs over to k8s-triage-robot

**Comment by spiffxp** [comment]
/reopen
Ugh. I've been commenting on the wrong issue this whole time. Will close the other issue about k8s-triage-robot later

**Comment by BenTheElder** [comment]
@ameukam where are we at on this?

**Comment by ameukam** [comment]
@BenTheElder we need to migrate the jobs listed in https://github.com/kubernetes/test-infra/issues/11402#issuecomment-709517484 to `k8s-infra-prow-build-trusted`. 

/milestone v1.25

**Comment by MadhavJivrajani** [comment]
We should be good to go here, the jobs listed in https://github.com/kubernetes/test-infra/issues/11402#issuecomment-709517484 are migrated to the new community clusters as well.

**Comment by MadhavJivrajani** [comment]
@ameukam please feel free to reopen if needed.
