### ISSUE TITLE
prow/blunderbuss: possibly use UserStatus?

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#11413]
**What would you like to be added**:
GitHub has a v4 API endpoint for `UserStatus`.. we could use this endpoint to see if `indicatesLimitedAvailability`, and use this as a weight when deciding who to assign new PRs to for review.

**Why is this needed**:
This allows folks to temporarily opt out of having new PRs assigned to them for review, hopefully increasing reviewer responsiveness by pushing reviews to folks who are around. This allows for people to take vacations 🌴.

**Comment by cblecker** [comment]
@nickvanw Any chance of UserStatus being available at any point on the v3 API? I see it's available in v4, but not v3 right now.

**Comment by nickvanw** [comment]
Hey @cblecker!

I don't have an ETA on UserStatus being available in v3, but I'll follow up today with the team that's responsible for the Status feature and see if I can get more information from them. I think this would be a fantastic use of this feature, and I hope that we can get you what you need to make it work!

**Comment by cblecker** [comment]
@nickvanw Any update on this? This would a potentially big improvement to our workflow.

**Comment by nickvanw** [comment]
Thanks for the ping @cblecker!

I don't have an easy update right now - I've engaged the team that's responsible for this feature on GitHub, but I don't know what their priority is on adding this to the REST API. I'll ping them again today. 

Beyond that, I think the easiest thing may be to involve the GraphQL API here to get the information immediately. I know it can be irritating to have to split the REST and GraphQL APIs, but it's the fastest way to get to this information right now. https://github.com/kubernetes/test-infra/pull/12348 seems like the easiest path forward for the time being.
