### ISSUE TITLE
Prow issue: Include blank line between <details> and text

### ISSUE THREAD

**Issue by eparis** [kubernetes/test-infra#1142]
See https://github.com/kubernetes/kubernetes/pull/37088#issuecomment-261837262 for example.

On chrome 56 and Firefox 49 on Linux when you expand the details the first link (the link back to the relevant comment) does not show up as a link and instead shows the `[ ]( )` stuff.

This is fixed if there is a newline between the <details> section and that first line of text.

**Comment by spxtr** [comment]
Thanks for opening the issue :)
