### ISSUE TITLE
prow.k8s.io is slow

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#11430]
Ever since we rolled out the latest version of prow, we've encountered some... problems.  Prow feels slow, takes a good bit to respond to random events, etc.

Let's talk about it!

Things I've heard of:
- pods were randomly unable to talk to each other at times 
- ... because the push_gateway component was eating ~400% CPU
- now it still seems to be slow, it seems to be all components
- we are suspicious of the generated client
- we are looking at bumping our nodes up to give us headroom while we diagnose what has changed and is going wrong

/assign @BenTheElder 
since you're on call

/assign @fejta @cjwagner 
since I believe you're looking at this as well

We want to get prow.k8s.io to HEAD instead of continually rolling it back to a pre-February version, so let's figure out what it takes.

**Comment by spiffxp** [comment]
/assign @Katharine 
also looking at reverting deck, apparently

**Comment by spiffxp** [comment]
/area prow
because why not

**Comment by fejta** [comment]
We rolled back to January - 

Merged: https://github.com/kubernetes/test-infra/pull/11429
Deployed: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/post-test-infra-deploy-prow/1019/?log#log

**Comment by spiffxp** [comment]
relevant slack threads: 
- #prow https://kubernetes.slack.com/archives/CDECRSC5U/p1550787869016400
- #testing-ops https://kubernetes.slack.com/archives/C7J9RP96G/p1550778390048700

**Comment by spiffxp** [comment]
http://velodrome.k8s.io/dashboard/db/monitoring?panelId=9&fullscreen&orgId=1&from=now-2d&to=now - shows tide processing times went wild

![screen shot 2019-02-21 at 2 43 27 pm](https://user-images.githubusercontent.com/49258/53206912-122a7280-35e7-11e9-9834-67e1e33b3210.png)

**Comment by BenTheElder** [comment]
prow workloads are on nodes with 2x the number of cores now

**Comment by BenTheElder** [comment]
resource usage appears to be nominal again, presubmit triggering for helm/charts is fixed.

**Comment by tpepper** [comment]
tide processing time in velodrome looks like it went back in line with historical trend

**Comment by fejta** [comment]
We're now running deck at HEAD of master without issue after:
* reverting the client refactor in deck
* doubling the cpu available to the cluster
* upgrading the version of GKE

**Comment by stevekuznetsov** [comment]
> Next will revert the client refactor in plank, followed by tide and then hook

Why?

**Comment by stevekuznetsov** [comment]
There is a known LOGICAL bug in `hook` for triggering. We do not currently have any known issues with `plank`. The `tide` issues for all we can tell are not related to the clients. It is not a good use of time to do that.

**Comment by fejta** [comment]
Primary goal for the day is:
a) Get all prow components at a Feb 22nd commit instead of Jan 25th
b) Get all prow component at the same commit
c) revert as much as possible to accomplish the above (and as little)

Once we've found a good Feb 22nd deployment, then start reintroducing things we had to revert.

**Comment by spiffxp** [comment]
[I gave kubernetes-dev@ a heads up](https://groups.google.com/forum/#!topic/kubernetes-dev/gjT5fpFlZx0), when we reach an all-clear state we should let them know

**Comment by neolit123** [comment]
cc

**Comment by fejta** [comment]
Yesterday the known problematic pieces were:
* Hook
* Tide
* Deck
* Our cluster

Current state is that cluster, deck and [now possibly tide](http://velodrome.k8s.io/dashboard/db/monitoring?panelId=9&fullscreen&orgId=1&from=now-2d&to=now) appear to be healthy at head.

**Comment by BenTheElder** [comment]
tide still looks good:
![image](https://user-images.githubusercontent.com/917931/53274929-f3db7a00-36ad-11e9-96a5-81f77a4da23b.png)

**Comment by cjwagner** [comment]
Update: We are now monitoring the effect of deploying this: https://github.com/kubernetes/test-infra/pull/11461
Once we've determined things are stable (lets give it 20 mins or so and keep an eye on CPU) we'll try to update hook to HEAD.

**Comment by cjwagner** [comment]
#11461 Seems to have deployed fine with the exception of a couple transient errors that don't appear to be related.

We're holding off on updating `hook` for the moment to address https://github.com/kubernetes/test-infra/pull/11460#issuecomment-466586230 and will instead update `horologium` to HEAD and monitor that.

**Comment by cjwagner** [comment]
`horologium`, `crier`, and `sinker` are all up to date now and seem to be healthy.

**Comment by cjwagner** [comment]
`hook` has been updated now and also seems to be healthy. ref: https://github.com/kubernetes/test-infra/pull/11464

Lets close this issue on Monday if things are still looking good. I'd like to validate everything under peak load to ensure we're in a healthy state.

**Comment by BenTheElder** [comment]
for future reference, this is a typical snapshot across the cluster:
```
NAME                                   CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
gke-prow-ghproxy-2cc2c707-n3p7         257m         3%        4466Mi          16%
gke-prow-n1-standard-8-24b71378-2kw2   84m          1%        2646Mi          9%
gke-prow-n1-standard-8-24b71378-g7bf   185m         2%        3987Mi          15%
gke-prow-n1-standard-8-24b71378-hbt0   205m         2%        3773Mi          14%
gke-prow-n1-standard-8-24b71378-l0s8   79m          0%        2123Mi          7%
gke-prow-n1-standard-8-24b71378-pt2v   275m         3%        4912Mi          18%
gke-prow-n1-standard-8-24b71378-q8s1   347m         4%        1948Mi          7%
gke-prow-n1-standard-8-24b71378-xkpt   219m         2%        4113Mi          15%
gke-prow-n1-standard-8-24b71378-z0c3   141m         1%        6647Mi          25%
```

<img width="1566" alt="screen shot 2019-02-22 at 7 57 18 pm" src="https://user-images.githubusercontent.com/917931/53281376-1f755900-36dc-11e9-87b2-01b2c3a10745.png">

logs look pretty fine.
we can't prove that helm/charts is fine after the hook update but we also have no proof that it's not 😛

**Comment by BenTheElder** [comment]
@cjwagner spotted a triggered presubmit in helm/charts 🎉

**Comment by spiffxp** [comment]
If we're happy with where prow is at @BenTheElder can you send a followup to [the k-dev@ thread](https://groups.google.com/forum/#!topic/kubernetes-dev/gjT5fpFlZx0)?

**Comment by fejta** [comment]
We should have all components at the same commit (and update them all concurrently) before we declare success

**Comment by BenTheElder** [comment]
doing the bump part first
https://github.com/kubernetes/test-infra/pull/11477

**Comment by cjwagner** [comment]
All components are at the same commit and we've updated them all concurrently without problem: https://github.com/kubernetes/test-infra/pull/11419

Lets consider this issue resolved.
