### ISSUE TITLE
Allow scraping github_token_count via prometheus

### ISSUE THREAD

**Issue by rmohr** [kubernetes/test-infra#11446]
**What would you like to be added**:

It would be great if it is possible to scrape `github_token_count` via prometheus from the `token-counter`.

**Why is this needed**:

Right now `github_token_count` seems to be the only metric which,for basic monitoring, is only served via influxdb to grafana. If that metric can be collected for prometheus, then influxdb would only be needed for long-time storage and related analysis.

**Comment by stevekuznetsov** [comment]
Totally -- we should be exposing this through `ghproxy`

**Comment by rmohr** [comment]
Sounds great. I added it to token-counter but I can move it to `ghproxy`. Would mean that the `token-counter` is then not needed at all.
