### ISSUE TITLE
Alerted on bot deployments

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/test-infra#1144]
Hello,

Is there anyway I can get pinged when we release new bot code? I can take care of letting the other kops maintainers know - and watching our stack..

But just wondering if there is a release email or anything in place yet I can get added to? 

Cheers

CC @sarahnovotny

**Comment by spxtr** [comment]
Whoops, sorry, this totally slipped under my radar. Are you still interested in this issue? We recently moved mungegithub into this repo, so all bot stuff happens here now.

**Comment by fejta** [comment]
Prow solves most of this, and we're slowly refactoring the submit queue to be org-wide
/cc @cjwagner
