### ISSUE TITLE
Prune test-infra GitHub teams and collaborators

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#11465]
**What should be cleaned up or changed**:
I would like to drop all use of collaborators in test-infra, and only use teams

I would like to prune team access to the following:
- `test-infra-admins` - admin access to the repo
- `test-infra-maintainers` - write access to the repo

I would like to drop the following teams in favor of `sig-testing-pr-reviews`
- `test-infra-reviewers`

I would like to prune membership of the `test-infra-admins` team to match the contents of kubernetes/test-infra/OWNERS

I would like to prune membership of the `test-infra-maintainers` team to match the contents of kubernetes/test-infra/OWNERS.  I'm halfway tempted to just get rid of it entirely, but we can consider that in a followup PR.

**Comment by spiffxp** [comment]
Survey of direct collaborators:

Either join as org members, or they won't be able to /lgtm, be /assign'ed, will need /ok-to-test, etc:

- @gaughen
- @lukaszgryglicki
- @nlandolfi
- @ostromart
- @yutongz

Either move to `test-infra-maintainers` or they'll lose direct write access.  I would default to the latter.

- @AishSundar
- @mithrav
- @paulangton 
- @sebastienvas 

No-op, they're already org members so they can be removed as direct collaborators today:

- @brahmaroutu
- @chrisglass
- @crimsonfaith91
- @ibzib
- @michelle192837
- @oomichi
- @philroche
- @qhuynh96
- @rcj4747

**Comment by cblecker** [comment]
Explicit +1

**Comment by spiffxp** [comment]
Doing the needful to remove direct collaborators

**Comment by spiffxp** [comment]
/close
All actions suggested in the issue description are complete
