### ISSUE TITLE
Deck Github Endpoint Flag

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11483]
**What would you like to be added**:
Most applications in prow allow overriding `github-endpoint` via flag provided in `flagutils`, like hook, plank, tide, branchprotector, etc.

I would like to be able to use this flag in deck.

**Why is this needed**:
Without this, we can't use ghproxy or a different github api endpoint in deck.

**Comment by stevekuznetsov** [comment]
Should be able to just use the utils in `deck` `main.go` right?

**Comment by midnightconman** [comment]
I am digging a little deeper on this, I think the problem is `pkg/ghclient` doesn't have functionality to change github endpoint, and ghclient is used by `prstatus`. Let me keep digging and see if this is still needed, to change prstatus github endpoint.
