### ISSUE TITLE
Docker node conformance dashboard pages are missing detailed test rows and result data

### ISSUE THREAD

**Issue by jeffqwb2017** [kubernetes/test-infra#11484]
**What happened**:  After docker PR  #11270 was merged by testgrid 
We found two major issues on final  dashboard page
**Actual Issue 1**. Look into the link below, the far left column only displays "overall" and missing the rest of the test rows 
 https://testgrid.k8s.io/sig-node-docker#ee17.06-node.e2e-ubuntu-k8s1.12
![overall column](https://user-images.githubusercontent.com/30056067/53293679-185a5380-378d-11e9-9dc4-fabbc998a94c.png)

**What you expected to happen**: We expect the first column including all other test rows similar to this screenshot 
![expected_testcolumn](https://user-images.githubusercontent.com/30056067/53293657-cf0a0400-378c-11e9-9368-bd50534531ec.png)

**Actual Issue 2**. docker node conformance page only served 4 results , whereas we actually provided 5-7 results in public bucket for each test combination.
 
![actual result](https://user-images.githubusercontent.com/30056067/53293706-a5051180-378d-11e9-9f0b-e51e26d11d8b.png)

**What you expected to happen**  we provided 7 results in public buckets , what causes data missing on final dashboard page?
https://console.cloud.google.com/storage/browser/k8s-conformance-docker/ci-kube-node-e2e-docker/ee17.06-ubuntu16.04-k8s1.12.x/?project=kube-node-e2e&organizationId=1030952953009

**How to reproduce it (as minimally and precisely as possible)**:
Click the link you should be able to see both issues i address above
https://testgrid.k8s.io/sig-node-docker#ee17.06-node-ubuntu16.04-k8s1.12

**Please provide links to example occurrences, if any**:
Same as above

**Comment by jeffqwb2017** [comment]
With my latest PR removing all column header settings. This problem remain active. Can anyone help to explain why this happen and how to fix that?

**Comment by Random-Liu** [comment]
It seems that prow does know how many test runs and how many are passing https://prow.k8s.io/view/gcs/k8s-conformance-docker/ci-kube-node-e2e-docker/ce18.09-ubuntu16.04-k8s1.13.x/1558028834

But the testgrid doesn't show test rows. @krzyzacy @BenTheElder Do you know why this happens?

**Comment by krzyzacy** [comment]
(Also replied in email)

Looks like your junit file is named as `junit__01.xml` which has two underscores, testgrid regex expects exactly one underscore.

Prow will swallow all *.xml files which is why it shows all results.

**Comment by jeffqwb2017** [comment]
Really appreciated your insights. This file name thing can be easily fixed
on my side before upload.

Jqi
