### ISSUE TITLE
Plugin config needs to use structs instead of pointers to structs

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#11517]
**What should be cleaned up or changed**:
Plugin config will ditch `omitempty` and use structs instead of pointers to structs.

**Provide any links for context**:
https://github.com/kubernetes/test-infra/issues/8193#issuecomment-466877677

**Comment by matthyx** [comment]
@cjwagner @stevekuznetsov now what do we do with the rest of the omitempty that are not slices?
```
	// Built-in plugins specific configuration.
	Approve                    []Approve              `json:"approve,omitempty"`
	UseDeprecatedSelfApprove   bool                   `json:"use_deprecated_2018_implicit_self_approve_default_migrate_before_july_2019,omitempty"`
	UseDeprecatedReviewApprove bool                   `json:"use_deprecated_2018_review_acts_as_approve_default_migrate_before_july_2019,omitempty"`
	Blockades                  []Blockade             `json:"blockades,omitempty"`
	Blunderbuss                Blunderbuss            `json:"blunderbuss,omitempty"`
	Cat                        Cat                    `json:"cat,omitempty"`
	CherryPickUnapproved       CherryPickUnapproved   `json:"cherry_pick_unapproved,omitempty"`
	ConfigUpdater              ConfigUpdater          `json:"config_updater,omitempty"`
	Golint                     Golint                 `json:"golint"`
	Heart                      Heart                  `json:"heart,omitempty"`
	Label                      Label                  `json:"label"`
	Lgtm                       []Lgtm                 `json:"lgtm,omitempty"`
	RepoMilestone              map[string]Milestone   `json:"repo_milestone,omitempty"`
	RequireMatchingLabel       []RequireMatchingLabel `json:"require_matching_label,omitempty"`
	RequireSIG                 RequireSIG             `json:"requiresig,omitempty"`
	Slack                      Slack                  `json:"slack,omitempty"`
	SigMention                 SigMention             `json:"sigmention,omitempty"`
	Size                       Size                   `json:"size"`
	Triggers                   []Trigger              `json:"triggers,omitempty"`
	Welcome                    []Welcome              `json:"welcome,omitempty"`
```

Namely:
- Blunderbuss
 - Cat
- CherryPickUnapproved
- ConfigUpdater
- Heart
- RequireSIG
- Slack
- SigMention

Maybe I should assess each of them separately and see which one is relevant...

**Comment by stevekuznetsov** [comment]
Even slices are fine -- if we ever actually serialize config, we could leave them. If they're not pointers, I don't think the churn is worth it? Would love to hear opinion from @cjwagner @fejta

**Comment by matthyx** [comment]
@cjwagner @fejta?

**Comment by cjwagner** [comment]
> Plugin config will ditch omitempty and use structs instead of pointers to structs.

I don't understand the benefit of getting rid of `omitempty`. It makes serialized config much easier to read. What is the downside of using it? Steve says `omitempty` works well without pointers: https://github.com/kubernetes/test-infra/pull/11538#issuecomment-468029644

**Comment by matthyx** [comment]
Alright then we keep things that way until I am done with #9757
