### ISSUE TITLE
Kubemark tests are missing logs from kubemark master

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/test-infra#11518]
The problem is that we are dumping logs from kubemark-master before we run clusterloader2 tests :-)
https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L662

This should be moved close where we down the kubemark master.

@kubernetes/sig-scalability-bugs

**Comment by krzyzacy** [comment]
did #11521 fix this?

**Comment by krzysied** [comment]
Yes, it did.

**Comment by krzyzacy** [comment]
thanks ^^
/close
