### ISSUE TITLE
fequent evicitions for bazel build pods in ciongke cluster

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/test-infra#1152]
build pods are frequently being evicted:
```
Status:         Failed
Reason:         Evicted
Message:        The node was low on compute resources.
    Requests:
      cpu:      100m
```

These pods are unlimited w.r.t. cpu and bazel will try to use all available resources. There will be other pods scheduled on this node (although there won't be other bazel pods). These pods run on 8 core machines and probably often go 10-80x over their cpu request. Will setting a higher cpu request with a limit lower the eviction frequency?

cc @vishh

**Comment by mikedanese** [comment]
Currently those pods are in the burstable cpu qos class and in the best effort mem qos class. @vishh is the percentage of burst (e.g. bursting %7000 over request) taken into account when eviction scoring?

**Comment by mikedanese** [comment]
We are still seeing evicitons after https://github.com/kubernetes/test-infra/pull/1154:
```
7851983367054065025                          0/1       Error       0          6m
2618764048067093662                          0/1       Error       0          9m
7295422770177261893                          0/1       Evicted     0          9m
8397220990306051092                          0/1       Evicted     0          9m
3139100283422494366                          0/1       Evicted     0          10m
4518440694718893838                          1/1       Running     0          10m
8782924101247167965                          1/1       Running     0          10m
2251745536499028803                          0/1       Evicted     0          11m
1974662793078122987                          0/1       Error       0          16m
6966556918630892164                          0/1       Evicted     0          16m
8844607703110017880                          0/1       Evicted     0          42m
```

**Comment by mikedanese** [comment]
The machines are n1-standard-8 (8 cpu, 30GiB of memory) and the build job will use as much resource as we give it.

**Comment by dchen1107** [comment]
#1154 is on the right direction here. The only other reason could cause eviction is disk. If the node is out-of-disk (usage or inode), Kubelet eviction manager could evict pods too. Unfortunately disk usage and inode are not first-class of the compute resource we support today, there is no qos class defined for this.

Can someone attach kubectl events or kubelet log so that we know which resource is at starvation here.

**Comment by mikedanese** [comment]
@dchen1107 Thanks! fixing the disk issue made this much better.
