### ISSUE TITLE
Ability to see private repositories in the PR status dashboard

### ISSUE THREAD

**Issue by bweston92** [kubernetes/test-infra#11523]
**What would you like to be added**:

The ability to see private repositories the OAuth token used to login into the PR status dashboard has access to.

**Why is this needed**:

Closed source projects want some of these amazing features too.

**Comment by stevekuznetsov** [comment]
This needs the PR dashboard to ask for a different set of scopes.

/area prow/deck

**Comment by bweston92** [comment]
Was there any progress on this? I know my PR was a fail. #11543
