### ISSUE TITLE
Write an integration test for crier/controller

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#11530]
/assign
/area prow/crier

**Comment by krzyzacy** [comment]
/remove-lifecycle stale
very close to be done

**Comment by krzyzacy** [comment]
thanks @chases2 !

/close

**Comment by krzyzacy** [comment]
(oops, haven't merged yet)
/unassign
/assign @chases2

**Comment by chases2** [comment]
#12691 merged; closing issue

**Comment by chases2** [comment]
#12691 merged; closing issue
/assign
