### ISSUE TITLE
Reintroduce the kops-aws job to sig-release dashboards

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/test-infra#11548]
The kops-aws job was removed from release blocking with https://github.com/kubernetes/test-infra/pull/11079 because it was failing due to account issues.

The job has been stable on the [sig-cluster-lifecycle-kops](https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kops#kops-aws) dashboard, is reintroduced as a presubmit job (https://github.com/kubernetes/test-infra/pull/11353) and offers useful information regarding the release.

Let's add it back to the dashboards that sig-release looks at. 

I have a slight preference for introducing it as release-informing (rather than -blocking) to begin with, and promote it to blocking if it's stable after 2 weeks. Reasoning: It flakes about 20% of the time at the moment, but I feel it checks release-blocking-job criteria otherwise (runs often enough and is fast enough).

/cc @spiffxp 
/cc @kubernetes/sig-release

**Comment by BenTheElder** [comment]
+1

> I have a slight preference for introducing it as release-informing (rather than -blocking) to begin with, and promote it to blocking if it's stable after 2 weeks. ...

SGTM, @spiffxp did we set the stable-time-length for promoting yet? I remember a similar discussion for kubeadm jobs.

**Comment by spiffxp** [comment]
/milestone v1.15
ref: https://github.com/kubernetes/test-infra/issues/11977

**Comment by jberkus** [comment]
/remove-lifecycle stale

Which Kops job are we talking about specifically here?  Looking at the test grid, the majority of Kops jobs are failing.
