### ISSUE TITLE
pr-history feedback: targets hard to click, columns missing timestamps

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#11549]
**What should be cleaned up or changed**:
The amount of whitespace in the boxes relative to the text makes it feel as though the targets are hard to hit since they're spread out.

I feel like the text could be larger in spyglass.  On the other hand, maybe this is necessary if there is a lot of PR history.

**Provide any links for context**:

gubernator (The 522 looks wrong here, let's ignore that):
![screen shot 2019-02-27 at 9 47 39 am](https://user-images.githubusercontent.com/49258/53511222-be9ba700-3a74-11e9-83d6-6d03214cb2c9.png)

spyglass:
![screen shot 2019-02-27 at 9 45 36 am](https://user-images.githubusercontent.com/49258/53511119-741a2a80-3a74-11e9-8b10-a7414e2f69cd.png)

/area prow/spyglass

**Comment by ibzib** [comment]
Re timestamps: I originally intended to show a tool tip with the date/time/commit message when hovering over commit hashes. I never figured out how to do that due to Github rate limiting.
