### ISSUE TITLE
1.14 Testgrid test jobs should match master, not 1.13

### ISSUE THREAD

**Issue by jberkus** [kubernetes/test-infra#11555]
@mariantalla @spiffxp @amwat etc.

The new 1.14 Testgrid Boards were created with a set of test jobs matching the 1.13 jobs.  This is wrong; the list of jobs for 1.14 should match master, as discussed at prior sig-release meetings and one Release Team meeting.  This means, among other things, Blocking and Informing, not Blocking and All.

I'd just swap out the test list, but since I don't know why the boards got created with the wrong list of jobs to begin with, I wanted to make sure first that it was an accident.

/area testgrid
/milestone v1.14
/kind cleanup

**Comment by krzyzacy** [comment]
oh dohhhh that's still not unified...

@jberkus the current workflow is we have a script to promote the version for all jobs, like:
1.10 -> 1.11
1.11 -> 1.12
1.12 -> 1.13
1.13 -> 1.14

Looks like that's not valid anymore and we should update the workflow in test-infra doc

**Comment by krzyzacy** [comment]
well - @jberkus I think the issue is still we don't have all equivalent jobs for master and release branches, aka `packages-pushed-master`, and we are still pending to remove kubeadm jobs from release-blocking dashboards.

**Comment by spiffxp** [comment]
I honestly forget if my blocking/informing proposal was meant to propogate to all boards or just master.  I will look.  I feel like linting this could help us catch it, if/when we are at a point where the job list is consistent.

**Comment by jberkus** [comment]
@krzyzacy so sounds like I need to do specific surgery on the 1.14 boards then?

**Comment by krzyzacy** [comment]
@jberkus there's already https://github.com/kubernetes/sig-release/issues/518 - and afaik the `packages-pushed-master` doesn't have a branch version for a reason? cc @neolit123

**Comment by jberkus** [comment]
@krzyzacy Take a look at the master boards, there's a LOT more changed than that.

**Comment by krzyzacy** [comment]
hummm sorry I was staring at the blocking dashboard - feel free to shuffle all the -all dashboard to become -informing I guess? (all - blocking = informing I assume)

**Comment by neolit123** [comment]
@jberkus 
> The new 1.14 Testgrid Boards were created with a set of test jobs matching the 1.13 jobs. This is wrong; the list of jobs for 1.14 should match master

given we already have a 1.14 k/k branch shouldn't we just match all 1.14 jobs to 1.14? here is a 1.14 job that runs against `release-1.14` file, or rather was resurrected yesterday.

> @jberkus there's already [kubernetes/sig-release#518](https://github.com/kubernetes/sig-release/issues/518) - and afaik the `packages-pushed-master` doesn't have a branch version for a reason? cc @neolit123

the packages-* jobs from sig-cluster lifecycle are jobs that run over the whole support skew...
these tests are so small that running them in separate jobs/pods is a complete waste.

just have them in a generic sig-release dashboard somewhere.
also they way the work is they check already existing artifacts, so it's not like they can "block" a release that is already out (packages were pushed).

**Comment by neolit123** [comment]
actually, packages-install-deb can catch a problem from CI packages too. :thinking: 

ok, i'm thinking about moving the packages* jobs to here:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#periodic-packages-pushed
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#periodic-packages-install-deb

https://k8s-testgrid.appspot.com/sig-release-misc

i also explained this here:
https://github.com/kubernetes/sig-release/issues/518#issuecomment-467169361

is `misc` a better home? any objections?

**Comment by neolit123** [comment]
https://github.com/kubernetes/test-infra/pull/11560

**Comment by jberkus** [comment]
@spiffxp we agreed in sig-release meeting that it would apply to the 1.14 boards, but that we'd decide later whether to push it down to the older boards.

This was also a follow-up to the 1.13 cycle, to clean up the boards, not just master but versioned.

**Comment by krzyzacy** [comment]
@jberkus so currently all branch dashboards are sorta unified - if we want to do sweeping changes I'd vote we still keep them consistent across old supported releases or else it will be painful when we bump for next release.

**Comment by jberkus** [comment]
Sen, I'm up for that, but I can't decide it unilaterally.

**Comment by jberkus** [comment]
@mariantalla @spiffxp @tpepper how can we move ahead on this?  I really don't like going into code freeze with the same mess of noncompliant tests we had in 1.13.

**Comment by mariantalla** [comment]
Hey, picking this up again (with the intention to make it for 1.14, but failing that let's try to have a way forward for 1.15)

I wonder if we can decouple the two; first, bring 1.14 to match master and then create a workflow for future releases.

I'm a bit worried about:
> currently all branch dashboards are sorta unified

@krzyzacy , if I got that right, does that mean that changing the 1.14 dashboards might affect 1.13 dashboards? If yes, in what way?

https://github.com/kubernetes/test-infra/pull/11370 seems to have created the 1.14 jobs - is the script that made the testgrid config changes somewhere in test-infra? 🤔[`bump_e2e_image.sh`](https://github.com/kubernetes/test-infra/blob/3d10a416d6d9c61e430d5c53d754afa0fceb7cca/experiment/bump_e2e_image.sh) seems to create the prow jobs but (as far as I can see) not the testgrid ones 👀

**Comment by krzyzacy** [comment]
> changing the 1.14 dashboards might affect 1.13 dashboards? If yes, in what way?

Not right now. But when we create 1.15 branch jobs, we are not doing that by deleting 1.11 and creating 1.15, we remap the dashboard from 1.11 -> 1.12, 1.12 -> 1.13, 1.13 -> 1.14, 1.14 -> 1.15

Feel free to do that for 1.14 for now, we can bikeshed older dashboards before 1.15 happens.

> bump_e2e_image.sh seems to create the prow jobs but (as far as I can see) not the testgrid ones eyes

that script bumps the image used in the job, which has nothing to do with testgrid :-)

**Comment by mariantalla** [comment]
I've just started (`started` being the keyword) work in https://github.com/kubernetes/test-infra/pull/11849 for 1.14 in specific. I think it will be a good exercise to do once manually and then consider automating for v1.15 onwards.

Other things on my list:
* Open issue for future non-master dashboards to match master dashboards (depending on how https://github.com/kubernetes/test-infra/pull/11849 goes too)

**Comment by spiffxp** [comment]
Not just testgrid configs, also job configs, we just bumped into an error with 1.13->1.14 missing a change in master (ref: https://github.com/kubernetes/test-infra/issues/11850)

**Comment by imkin** [comment]
Audited the PR https://github.com/kubernetes/test-infra/pull/10795/ and found that the other configs were fine except for the https://github.com/kubernetes/test-infra/issues/11850

Verfied the same in the master. Automation needs to change based on this but will do that async to this issue.

**Comment by spiffxp** [comment]
/milestone v1.15
ref: https://github.com/kubernetes/test-infra/issues/11977
