### ISSUE TITLE
Spyglass artifacts links don't always work

### ISSUE THREAD

**Issue by benmoss** [kubernetes/test-infra#11568]
**What happened**:
The artifacts link on my build (https://prow.k8s.io/view/gcs/pivotal-e2e-results/kubo-windows-2019/1551296176) 404s. I looked at Gubernator's link and it has a trailing slash on the end, which turns out to work. It seems like GCSWeb has some different behavior depending on whether the bucket is `jenkins-artifacts` or something else.

**How to reproduce it (as minimally and precisely as possible)**:
Click the artifacts link on a non-jenkins-artifacts build

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/5001
https://prow.k8s.io/view/gcs/pivotal-e2e-results/kubo-windows-2019/1551296176

/assign @Katharine

**Comment by Katharine** [comment]
I fixed spyglass to always end in a trailing slash in #11569. I'm not sure whether we want to keep this open for the weird gcsweb behaviour.

**Comment by stevekuznetsov** [comment]
I think that's enough of a fix
/close
