### ISSUE TITLE
deck search box does not update URL

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#11599]
**What happened**: type `ci-kubernetes-e2e-gke-large-performance-regional` into prow.k8s.io's jobs box, hit enter. The url will be https://prow.k8s.io/ instead of https://prow.k8s.io/?job=ci-kubernetes-e2e-gke-large-performance-regional

**What you expected to happen**: the url should reflect the selected job

**How to reproduce it (as minimally and precisely as possible)**: see what happened

**Please provide links to example occurrences, if any**: https://prow.k8s.io/

**Anything else we need to know?**: no

/area prow/deck

**Comment by BenTheElder** [comment]
cc @Katharine

**Comment by stevekuznetsov** [comment]
This got fixed
/close
