### ISSUE TITLE
Missing node-level logs for GCI-based tests

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#1160]
I was trying to debug flake test, but I found that Node logs are missing for GCI runs (http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/83/artifacts/). 

Randomly assigning @ixdy - please reassign if I'm wrong.

cc @mtaufen @vishh @kubernetes/test-infra-maintainers

**Comment by Random-Liu** [comment]
Dup to https://github.com/kubernetes/test-infra/issues/1149
