### ISSUE TITLE
The Ability to Override the ProwJob Status Url For Jenkins-Operator

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11619]
**What would you like to be added**:
I would like to be able to override the default prowJob status url that the jenkins-operator users (`testInfra`) that points at `"https://github.com/kubernetes/test-infra/issues"`. I would like to be able to make this point at the jenkins job url and build number.

**Why is this needed**:
This allows people to use the jenkins-operator and have a better experience in deck, where they can click on the job name and see the build results.

**Comment by stevekuznetsov** [comment]
That is only used when you fail to start a job, when there is no job to link to

**Comment by midnightconman** [comment]
Interesting, the build starts in Jenkins. I'll dig deeper and see what's going on. :smile:

**Comment by stevekuznetsov** [comment]
It would be good to look at the logs from `jenkins-operator`

**Comment by stevekuznetsov** [comment]
You need to make sure to expose all the parameters to the job so that Prow can set them -- if Prow can't set the build ID it can't find the job to link to a ProwJob after

**Comment by midnightconman** [comment]
Got this to work... you totally called the missing `BUILD_ID` parameter.

I would still like to be able to override this static endpoint, possibly to a different repo / org / etc. I opened this issue with a different idea in mind, but I still think this would be a good feature. 

Thoughts?
