### ISSUE TITLE
Checkconfig passes for invalid config

### ISSUE THREAD

**Issue by yb172** [kubernetes/test-infra#11621]
**What happened**:
I was setting up prow and configured `plugins.yaml` as described in "Getting started" guide. Plugins didn't work.
```
bazel run //prow/cmd/checkconfig -- --plugin-config=<path-to-plugins.yaml --config-path=<path-to-config.yaml>
```
haven't displayed any errors.

**What you expected to happen**:
List of specified plugins to start working or `checkconfig` to show that plugin contains error. 

**How to reproduce it (as minimally and precisely as possible)**:
 * Take any working config 
 * Make a typo in any of top level properties (e.g. `config_updater1`
 * Run `checkconfig`
No error messages will be shown. But if you update code to see what config was parsed you will see that `config_updater` section is empty.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by stevekuznetsov** [comment]
This is unfortunately something emergent from the YAML loading library. It is totally valid to turn on a plugin but not configure it to do anything, so unless we want a breaking change to that behavior there is no way for `checkconfig` to know that something is wrong.

/cc @cjwagner @fejta
