### ISSUE TITLE
Tide context status is missing from PRs

### ISSUE THREAD

**Issue by neolit123** [kubernetes/test-infra#11628]
**What happened**:
this PR is missing the GitHub CI status at the bottom - test jobs / CLA / tide:
https://github.com/kubernetes/kubernetes/pull/74933

**Comment by spiffxp** [comment]
Also apparently missing, this PR I just opened right now! https://github.com/kubernetes/test-infra/pull/11629

**Comment by spiffxp** [comment]
First report received in #sig-testing was https://github.com/kubernetes/kubernetes/pull/74721

**Comment by spiffxp** [comment]
/assign @amwat 
as test-infra oncall per go.k8s.io/oncall

**Comment by spiffxp** [comment]
Well, my PR merged once it got the appropriate labels at least: https://github.com/kubernetes/test-infra/pull/11629

**Comment by stevekuznetsov** [comment]
Yeah, status is user-facing only, won't affect `tide` actually merging

**Comment by spiffxp** [comment]
All three linked PR's now have tide status contexts, I don't think any corrective action has been taken, I'm now wondering if this is github instability (I definitely caught githubstatus.com looking degraded but they never opened an incident and it all looks green now)

**Comment by spiffxp** [comment]
Also worth noting: the PR's weren't "in the merge pool" when they were missing their contexts before.  They have since had the appropriate labels applied etc, and the tide status context appeared as "in merge pool"

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-soon
I'm dropping priority as all linked PR's no longer exhibit the problem, and tide has been merging PR's just fine https://github.com/kubernetes/kubernetes/commits?author=k8s-ci-robot

I'm leaving open because I still don't know exactly what happened.  I would suggest @fejta or @amwat fill in what they have found, and close if we find no further reports

**Comment by neolit123** [comment]
here is one:
https://github.com/kubernetes/kubernetes/pull/7495

it's approved and ready to merge.
but no indication if it passes tests...

**Comment by neolit123** [comment]
here is another one:
https://github.com/kubernetes/kubernetes/pull/74870

the status seems to disappear on random RPs.

**Comment by amwat** [comment]
Multiple things at play here: 
k/k tidepool is growing a lot as we are close to code freeze: https://prow.k8s.io/tide
tide is getting flagged by github abuse rate limits, being dicussed in [testing-ops](https://kubernetes.slack.com/archives/C7J9RP96G/p1551798955067800) now

**Comment by stevekuznetsov** [comment]
So the context is, per GitHub's API, posted to a commit. When a PR is updated, the new commit has no contexts. The status controller is degraded right now and operating very slowly, so that is why you are noticing PRs without the status context.

**Comment by spiffxp** [comment]
What I get from the above is that we should let people know that:
- we are hitting github abuse detection for Reasons (TM)
- everything is operating as best as it can
- the tide context may not be present or up to date

My total guess, is that I can also tell people:
- https://prow.k8s.io/pr dashboard can be used to see the status of your PR (including what tide is doing with it)

**Comment by spiffxp** [comment]
Notified [kubernetes-dev@](https://groups.google.com/d/msg/kubernetes-dev/HXJAXNOGqrg/RMGDTaFJAwAJ)

**Comment by spiffxp** [comment]
/close
This is no longer happening
