### ISSUE TITLE
spyglass: is there a way to show more user-friendly times?

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#11633]
I am seeing things like:

> Test started today at 1:36 PM is still running after 2m18.262251838s. (more info)

Can we get that as `2m18s` or something? Is that simple?

/cc @Katharine @BenTheElder 
/area prow/spyglass

**Comment by Katharine** [comment]
This comes from Go's default rendering of a Duration, which is not remotely customisable. 

That said, I hate it, so we should do something better at some point.

**Comment by stevekuznetsov** [comment]
Yeah IIRC there was some helper library in Docker or k8s for duration formatting

**Comment by BenTheElder** [comment]
you can round the duration before formatting

**Comment by BenTheElder** [comment]
https://golang.org/pkg/time/#Duration.Round

**Comment by Katharine** [comment]
I distinctly recall actually doing this, too, so I'm not sure why we're back to providing nanosecond resolution.

I am not a fan of the "1h23m7s" display either, though.

/pony shrug

**Comment by stevekuznetsov** [comment]
We could just always show nanoseconds from the epoch ;)
