### ISSUE TITLE
Prow is dropping too many webhooks

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#1163]
I was previously dropping 1 webhook every few hours. After yesterday, when I switched certain simple pods to run on the same nodes as my webhook listening pods the rate of dropped webhooks skyrocketed. This is unacceptable, and likely it's a kubernetes bug again. Next week I'll look into a repro and fix.

**Comment by saad-ali** [comment]
PR https://github.com/kubernetes/kubernetes/pull/37312 appears to be blocked by this issue? Is there a workaround?

**Comment by spxtr** [comment]
You can just ask for a retest manually.

**Comment by saad-ali** [comment]
Got it thanks.

**Comment by spxtr** [comment]
This is the same symptom that lead to https://github.com/kubernetes/kubernetes/issues/32415.

**Comment by spxtr** [comment]
Temporary fix: I have a VM running a very simple proxy on GCE that does retries on transport failure. We should be getting webhooks now every time, but there's still a real problem.

**Comment by spxtr** [comment]
OK, something was borked in the cluster. I recreated it in a new project and we're back to not dropping hooks.
