### ISSUE TITLE
spyglass: build log is cut off at the bottom

### ISSUE THREAD

**Issue by ibzib** [kubernetes/test-infra#11643]
**What happened**:
When I view a job that is still in progress in Spyglass and expand the build log, the bottom of the log sometimes gets cut off. 
![screenshot from 2019-03-05 15-55-03](https://user-images.githubusercontent.com/16039734/53845736-151a5100-3f5f-11e9-8f7d-74de48b53c7b.png)

/cc @Katharine

**Comment by Katharine** [comment]
Fixed by #11609 (but not deployed yet).
