### ISSUE TITLE
git client: log output contains password

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#11640]
When we log errors or warnings from the Git client and post the URL, we end up with the username and token of the bot in basic auth form in the url, in plain text

/cc @cjwagner @fejta

**Comment by cjwagner** [comment]
@stevekuznetsov This is fixed now right?

**Comment by stevekuznetsov** [comment]
I think this got lost in the larger `git` client work, so no. An example implementation of this is:

```go
type censoringFormatter struct {
	secret   string
	delegate logrus.Formatter
}

func (f *censoringFormatter) Format(entry *logrus.Entry) ([]byte, error) {
	for key, value := range entry.Data {
		if valueString, ok := value.(string); ok {
			if strings.Contains(valueString, f.secret) {
				entry.Data[key] = strings.Replace(valueString, f.secret, "xxx", -1)
			}
		}
	}
	return f.delegate.Format(entry)
}
```

If we integrate that with the secret loader we should be set

/remove-lifecycle rotten
/help
/good-first-issue
