### ISSUE TITLE
sinker failing to list jobs

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#11660]
/assign @krzyzacy 

```yaml
jsonPayload: {
  component:  "sinker"   
  error:  "the server could not find the requested resource (get prowjobs.prow.k8s.io)"   
  level:  "error"   
  msg:  "Error listing prow jobs."   
 }
```

Possible changes: ref https://github.com/kubernetes/test-infra/pull/11625

**Comment by fejta** [comment]
I suspect this has something to do with https://github.com/kubernetes/test-infra/pull/11547

**Comment by stevekuznetsov** [comment]
This is a GET, not a LIST, and it definitely looks like the client is being pointed at a cluster without the ProwJob installed (maybe the default build cluster?)

**Comment by krzyzacy** [comment]
hummm why it's only affecting sinker? because sinker is using the new client?

/unassign
/assign @stevekuznetsov @ccojocar

**Comment by fejta** [comment]
The issue here is that we're conflating two things:
* The context where prowjobs live
* The default contexts for resources created by prowjobs (pods, builds, etc).

The ProwJob context is:
* "" when running in cluster
* Otherwise the --kubeconfig's current context

The default context for resources is the "default" context

**Comment by stevekuznetsov** [comment]
So I have no idea where on earth the re-reverting is or whatever but as discussed in the past the current implementation is:

 - pass nothing, use the in-cluster context for the service cluster and the build cluster
 - pass a kubeconfig, use the default context for the service cluster and all others as build clusters
 - pass a specific infra context and a kubeconfig: use that context as the service cluster, all others as build clusters
 - pass a cluster yaml: overwrite build clusters (I think?)

We need to know what is the in-cluster context, specifically, to ensure that it is always used for the service cluster unless an explicit service context is pased

**Comment by stevekuznetsov** [comment]
If you had not reverted the client changes, the fix that merged would not have been necessary, either, for the `build` controller:

https://github.com/kubernetes/test-infra/blob/fb29628c016b10ecb981250be898d9130e488416/prow/flagutil/kubernetes_cluster_clients.go#L179-L185

**Comment by stevekuznetsov** [comment]
This is where we default to use the default _context_ for the infra cluster, if no specific _context_ was given

**Comment by stevekuznetsov** [comment]
Aaand that's the bug ... that change makes the default _context_ the default _alias_:

https://github.com/kubernetes/test-infra/blob/fb29628c016b10ecb981250be898d9130e488416/prow/kube/config.go#L45

**Comment by stevekuznetsov** [comment]
So. Fixes:

1. [revert](https://github.com/kubernetes/test-infra/pull/11663) the change
2. re-revert the client changes
3. everything works correctly

**Comment by stevekuznetsov** [comment]
We could perhaps also make a different fix that adds both the _alias_ and the _context_ to the mapping (which for all the above reasons is not a good idea) but _not_ change the default _context_ to be the default _alias_, then we would not need to do the re-revert. However, I don't see why we should not re-revert immediately.

**Comment by fejta** [comment]
The core problem is with the client refactor. If we want to revert, that is what we should revert.

Historically there were two valid scenarios:
1) Prow runs without --build-cluster and everything happens in cluster
2) Prow uses a --build-cluster flag, prowjobs are in cluster and everything else happens in the default context.

This refactor introduced a bunch of new behavior, such as:
* no longer requiring a default context, and trying to intuit its value from the in cluster or kubecfg's current context values.
* no longer requiring prowjobs to live in cluster, trying to intuit this value the kubecfg's current context.

**Comment by fejta** [comment]
> both the alias and the context

Alias and context are the same thing. Trying to think otherwise is a recipe for disaster.

**Comment by stevekuznetsov** [comment]
Then we need a separate means of loading clients for things that don't touch build clusters. In any case, `sinker` is fine and this issue is closed...

/close
