### ISSUE TITLE
Jenkins Bazel Build Failures

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#1166]
Example Failure:
https://github.com/kubernetes/kubernetes/pull/37311#issuecomment-262368510

However if you look at logs, the build seems to be running and not finished yet:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/37311/pull-kubernetes-bazel/7671011103186664108/
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/37311/pull-kubernetes-bazel/7671011103186664108

**Comment by saad-ali** [comment]
CC @mikedanese

**Comment by dims** [comment]
Here's how i went looking for recent failures:
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aopen+%22Jenkins+Bazel+Build%22+sort%3Aupdated-desc

**Comment by dchen1107** [comment]
This failure blocks several prs for 1.5 getting merged. Can we treat this as P0 blocker.

**Comment by ixdy** [comment]
@dchen1107 bazel isn't a blocking build.

**Comment by dims** [comment]
@mikedanese @derekwaynecarr this one may be a better example? https://github.com/kubernetes/kubernetes/pull/37305

**Comment by dims** [comment]
Derek shared another kind of failure:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32577/pull-kubernetes-bazel/3904481374297485778/

**Comment by dims** [comment]
@ixdy : it's not a "Queue blocking build" in http://submit-queue.k8s.io/#/e2e, but if things don't go green in the PR(s), they won't enter the submit queue. right?

**Comment by mikedanese** [comment]
@dims that's incorrect. submit-queue ignores this when merging PRs.

**Comment by dims** [comment]
@mikedanese ah! thanks. i did not know that

**Comment by mikedanese** [comment]
@dims, @derekwaynecarr 's failure will be fixed by https://github.com/mikedanese/gazel/pull/3/ . NIce bug!

**Comment by dims** [comment]
@mikedanese cool!

**Comment by mikedanese** [comment]
https://github.com/kubernetes/test-infra/pull/1167 should temporarily fix the OOMing.
