### ISSUE TITLE
Enable /milestone for k/website

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/test-infra#11687]
## What should be cleaned up or changed

Heya! 👋 It would be nice to enable `/milestone` commands for k/website. 

## Provide any links for context

Here's an [example](https://github.com/kubernetes/website/pull/13004#issuecomment-470148896) of someone trying (and failing) to assign a `/milestone`.

/area prow
/sig docs
/priority important-soon

**Comment by nikhita** [comment]
@zacharysarah You can create a team called `website-milestone-maintainers`, something like https://github.com/kubernetes/org/pull/624.

After that gets merged and the team is created, you can create a team like https://github.com/kubernetes/test-infra/pull/11829. The team should then be able to use the `/milestone` command. :)

**Comment by zacharysarah** [comment]
@nikhita Thanks! I think this looks like 3 PRs:

- Add a milestone team to k/website: https://github.com/kubernetes/website/pull/13287
- Add a milestone team to k/org: https://github.com/kubernetes/org/pull/628
- Add a team to k/test-infra: TBD

**Comment by nikhita** [comment]
> I think this looks like 3 PRs

The first one isn't really needed but it can be a good place to point someone out if they want to apply for this team. :)

And...I realized I wrote the same thing twice in my comment (?!) :woman_facepalming:

**Comment by nikhita** [comment]
Looks like this is done now? :)

**Comment by zacharysarah** [comment]
Indeed! Closing. 🙇
