### ISSUE TITLE
Deck no longer runs a server on port 8080 (locally)

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#11690]
As of #11659, Deck no longer runs an HTTP server on port 8080, and so serves no content. It does however serve /statusz (but nothing else) on port 8081.

As of #11682, Deck also no longer runs an HTTP server on port 8081. It does however serve pprof debug info (but nothing else) on port 8082.

Some quick testing suggests that only the first call to `http.ListenAndServe` works, and subsequent ones block forever as expected,but don't actually do anything.

I'm not currently sure whether this affects production or just running deck locally, and I also don't understand why this happens.

**Comment by stevekuznetsov** [comment]
That's weird, I was pretty certain that using a goroutine per port was the accepted way to do this>
