### ISSUE TITLE
BranchProtector Should Use ConfigAgent

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11727]
**What should be cleaned up or changed**:
Branchprotector should use prow configAgent instead of `*config.Config`. This will make branchprotector use the same mechanisms hook, deck, etc. use.

**Provide any links for context**:
- https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/protect.go#L96
- https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/protect.go#L143
- https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/protect.go#L168

/area prow/branchprotector

**Comment by stevekuznetsov** [comment]
`branchprotector` runs once to completion and is not a daemon, so it does not re-load config.

**Comment by stevekuznetsov** [comment]
The loading, etc, all uses the same library underneath

**Comment by midnightconman** [comment]
Having a different mechanism for jobs and services makes sense. Wouldn't it be nice to have one mechanism though? This way we wouldn't have to have different config declarations, depending on application type.

**Comment by midnightconman** [comment]
Is there a generic config type that will accept `*config.Getter` and `*config.Config`?

**Comment by stevekuznetsov** [comment]
We do -- the `config.Load` is the underlying mechanism they both share, the agent just makes that poll for changes to the file and reloadsi t

**Comment by midnightconman** [comment]
Thank you, it's working. Closing this issue.
