### ISSUE TITLE
Set --config-path on all deployments

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#11728]
Right now we default this value to "/etc/config/config.yaml", which feels too much like magic, only working when you create the right configmaps and mount them in the right place.

**Comment by fejta** [comment]
/help

This involves adding --config-path flag to deployments that use it https://github.com/kubernetes/test-infra/tree/master/prow/cluster

Then once that is deployed everywhere, setting the default value to ""

**Comment by stevekuznetsov** [comment]
Totally agree -- all defaults should be made explicit -- it helps a lot when someone changes the YAML

**Comment by stevekuznetsov** [comment]
You'd need to make a migration period for the default though :)

**Comment by hemanik** [comment]
I would like to work on this.

**Comment by fejta** [comment]
Go for it! 
/lifecycle active
