### ISSUE TITLE
New Prow Deployment: Missing default decorate configs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#11729]
When following https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md

The jobs referenced in https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#add-more-jobs-by-modifying-configyaml is using `decorate:true` but we didn't have a section about decorate configs? (afaik https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L1-L19 is required, or the configcheck call below will give `no default decoration config provided for plank`)

/area docs

cc @cjwagner @stevekuznetsov 
cc @verult who found the issue

**Comment by cjwagner** [comment]
Yeah we recently added a mention to this setup requirement in the [pod utility documentation](https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#how-to-configure), but we also need to something similar for `getting_started_deploy.md`.
