### ISSUE TITLE
Consolidate experimental scripts for test-infra automation

### ISSUE THREAD

**Issue by amwat** [kubernetes/test-infra#11730]
**What should be cleaned up or changed**:
Currently we need to run multiple scripts to in order to create/update new jobs during the k8s release, e.g. https://github.com/kubernetes/test-infra/pull/11370
As part of our test-infra automation plan https://github.com/kubernetes/test-infra/issues/10106 it would be great if we could combine those to be run from a single entrypoint.

**Provide any links for context**:
https://github.com/kubernetes/test-infra/blob/master/experiment/manage_release_versions.py
https://github.com/kubernetes/test-infra/blob/master/experiment/bump_e2e_image.sh
https://github.com/kubernetes/test-infra/blob/master/experiment/generate_tests.py
https://github.com/kubernetes/test-infra/blob/master/hack/update-config.sh

/cc @taragu @imkin @munnerz

**Comment by stevekuznetsov** [comment]
Write them in Go and load config first-class :)

**Comment by amwat** [comment]
/close
most of the test-infra tasks have been automated (https://github.com/kubernetes/sig-release/issues/631) . Thanks @Katharine!
