### ISSUE TITLE
smarter log highlighting in deck

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#11739]
**What would you like to be added**: It would be great if the log highlighter in deck / spyglass knew about some of the poor logging behavior in Kubernetes testing and avoided flagging relatively useless information, E.G. see:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/74394/pull-kubernetes-e2e-gce/72448/

**Why is this needed**: To make identifying causes of failed test jobs easier.

/area prow
/area prow/deck
/area prow/spyglass
cc @thockin @Katharine

**Comment by BenTheElder** [comment]
A suggestion from @Katharine:
- excessively long lines should not get highlighted

In general we could probably have a variant of the log renderer specifically for Kubernetes that handled our less-generic quirks, E.G. the ginkgo SUCCESS/FAILURE line would be nice to highlight.

A suggestion from me:
- I will PR the pod nanny which appears to be causing this blob to be highlighted because it spits out an error on startup (due to using glog before parsing flags).

**Comment by BenTheElder** [comment]
/assign @Katharine 

cc @stevekuznetsov @cjwagner

**Comment by stevekuznetsov** [comment]
FWIW right now `buildlog.highlightLines` accounts for ~25% of CPU utilization by `deck`

**Comment by stevekuznetsov** [comment]
I agree we should be smarter and IMO we should build in a number of different highlighters in Go, originally the thought was some metaprogramming or something via config but that has the potential to be less efficient

**Comment by BenTheElder** [comment]
+1 for that

also xref:
- https://github.com/kubernetes/kubernetes/pull/66515/files#r264935489
- https://github.com/kubernetes/autoscaler/issues/1786
- https://github.com/kubernetes/test-infra/pull/11740

**Comment by stevekuznetsov** [comment]
@Katharine your lens refactor will allow configurable regex, right?

**Comment by Katharine** [comment]
Already did, in fact

**Comment by stevekuznetsov** [comment]
:man_facepalming: 
/close
You rock
