### ISSUE TITLE
Move Config Flags To A FlagSet

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11731]
**What should be cleaned up or changed**:
It would be nice to move configuration flags to a flagset, like the `github` and `kubernetes` flagsets. This would allow applications to use a consistent mechanism for loading config related flags.

Like the following flags:
```
      fs.StringVar(&o.configPath, "config-path", "/etc/config/config.yaml", "Path to config.yaml.")
      fs.StringVar(&o.jobConfigPath, "job-config-path", "", "Path to prow job configs.")
      fs.StringVar(&o.pluginConfig, "plugin-config", "/etc/plugins/plugins.yaml", "Path to plugin config file.")
```

**Provide any links for context**:
- https://github.com/kubernetes/test-infra/blob/master/prow/flagutil/github.go
- https://github.com/kubernetes/test-infra/blob/master/prow/flagutil/k8s_client.go

**Comment by stevekuznetsov** [comment]
Some WIP work for that here, abandoned https://github.com/kubernetes/test-infra/pull/9701
