### ISSUE TITLE
Support kube-mesos

### ISSUE THREAD

**Issue by k82cn** [kubernetes/test-infra#1176]
**Description:**

[kube-mesos](https://github.com/kubernetes-incubator/kube-mesos-framework) did **NOT** change k8s's  user interface; so it's better to re-use kubernetes test-infra for it.

Furthermore, there's also some cases that similar with kube-mesos; so it's better to make it decouple with k8s, focus on k8s's user interface.

**Comment by fejta** [comment]
This looks dead.

Talk to @cjwagner if you still want this (submit queue, prow, etc)
