### ISSUE TITLE
Prow runs postsubmit jobs on branch that contain name of the target branch

### ISSUE THREAD

**Issue by atakanyenel** [kubernetes/test-infra#11779]
**What happened**:
we have a postsubmit job defined to `release` branch. To create new release, I created a branch called `release-0.1`, made a commit and created a PR to `release` branch. Prow took my commit to `release-0.1` branch as post submit and ran the job defined for the `release` branch. 

**What you expected to happen**: I expected prow to run post-submit job only with exactly matching branches.

**How to reproduce it (as minimally and precisely as possible)**: Have a post-submit job defined for `master`. Create a branch called `master-test` and push it. Prow will run the post submit job defined for `master` for `master-test` branch. 

**Anything else we need to know?**:
We believe it's because [this line](https://github.com/kubernetes/test-infra/blob/e808085f74d1f6f87820f56647f95f03d1bbfddf/prow/config/jobs.go#L221) does checks for contains instead of exact matching.

I believe this is a security issue as our `release` branch is protected by Github but now this protection is bypassed.

**Comment by fejta** [comment]
`^release$` will only match the release branch
