### ISSUE TITLE
pull-kubernetes-conformance-image-test gets stuck and does not report any results or artifacts

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#11814]
Looking at history:
https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=presubmit&job=pull-kubernetes-conformance-image-test

I have been trying to run the test by hand as well:
https://github.com/kubernetes/kubernetes/pull/75349#issuecomment-473749868

**Comment by dims** [comment]
cc @brahmaroutu 

/area conformance

**Comment by brahmaroutu** [comment]
I am not following what we should do as I thought stdout issue is fixed in PR #75121. The Job is skipping, @BenTheElder is there any configuration that need to be changed?
Once the job is added back we can know why it is erroring out, I guess.

**Comment by BenTheElder** [comment]
looks to me like the test logic doesn't work?

many many lines with:
`I0323 12:45:31.945] [12:45:31] Pod status is: Failed`
if we reach that state, shouldn't it exit with a failure instead of continuing to print this indefinitely?

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/75134/pull-kubernetes-conformance-image-test/41/

I can't tell why the pod is failed, but it looks like the kind cluster is up fine and the image built & loaded.

**Comment by dims** [comment]
@BenTheElder i thought we fixed it in https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/conformance-e2e.sh#L28-L31

**Comment by BenTheElder** [comment]
we probably also need to set timeouts on the jobs. trying a new job on 75134 with a `/test` command (which should replace the old one, and pick up those changes...)

**Comment by BenTheElder** [comment]
should be fixed
