### ISSUE TITLE
GCE/GCP job presets use deprecated GV "admissionregistration.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/test-infra#11850]
in the release 1.14 change log we have:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md

> The alpha Initializers feature, admissionregistration.k8s.io/v1alpha1 API version, Initializers admission plugin, and use of the metadata.initializers API field have been removed. Discontinue use of the alpha feature and delete any existing InitializerConfiguration API objects before upgrading. The metadata.initializers field will be removed in a future release. (#72972, @liggitt)

GCE jobs such as `pull-kubernetes-e2e-gce` still use:
`admissionregistration.k8s.io/v1alpha1`

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-gcp/sig-gcp-gce-config.yaml#L209

all jobs that use this GCE/GCP preset will pass `admissionregistration.k8s.io/v1alpha1=true` to the  `--runtime` flag of the api-server and will fail in the 1.14 branch.

e.g.:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/75489/pull-kubernetes-e2e-gce/72987/artifacts/e2e-72987-674b9-master/kube-apiserver.log

/assign @liggitt @spiffxp 
cc @hoegaarden

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/10795 was apparently supposed to catch this, looking...

**Comment by liggitt** [comment]
looks like https://github.com/kubernetes/test-infra/commit/b68f001e50aeed9e2203c658e1a9a5e81a6d9ff1#diff-c8e02b4dec1c4ef0c36b616538d00bb6 just copied 1.13-level job config into 1.14, instead of using the current master config that was fixed in https://github.com/kubernetes/test-infra/pull/10795
