### ISSUE TITLE
ProwJob Jenkins Agent Failover Selector

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#11859]
**What would you like to be added**:
I would like to be able to specify a failover jenkins selector to a prowJob, to run a jenkins job on a different jenkins incase the original jenkins is unreachable. I know there is retry logic, but it would be nice to be able to specify a different selector as well.

**Why is this needed**:
At the moment if a jenkins master is down and the retry count is exceeded, no additional steps will be taken. It would be nice if we could specify failover logic to try additional jenkins masters in the event the primary is unavailable.

**Comment by stevekuznetsov** [comment]
Could you do this with failover logic through HAProxy or Route 53 etc?

**Comment by midnightconman** [comment]
Maybe, wouldn't (proxying) logs get weird, in deck?

**Comment by stevekuznetsov** [comment]
I guess that depends on how your configure your failover. I feel like a robust approach would be to use currently available failover tools, instead of inventing our own.

/cc @cjwagner

**Comment by midnightconman** [comment]
I feel it is just an extension on the sharding mechanisms in place, mostly an additional selector slice and enhancing the retry logic to support slice iteration.

**Comment by midnightconman** [comment]
Do you guys not have trouble with single master failures for openshift?

**Comment by stevekuznetsov** [comment]
No, only legacy jobs are on Jenkins today but even when we ran all of our workloads there the failure mode is really soft -- jobs stack up in the queue as ProwJobs and when the master comes back up, `jenkins-operator` schedules them. There will be a delay but it was never hurting us too bad.

**Comment by stevekuznetsov** [comment]
I think the feature might be a bit harder -- we'd need to keep track of which worker we ended up scheduling too, right? For continued updates to the ProwJob as well as logs, etc

**Comment by midnightconman** [comment]
I have been using the jenkins-operator for a week or two now, it seems to handle retries nicely. I'll close this, maybe we can open it up again later.
