### ISSUE TITLE
Spyglass: avoid reading entire logs in to memory before displaying them

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#11854]
Currently we read entire log files into memory, then copy subsets of them into memory several more times, before we attempt to pass them back to the user, which given our love of logs in the hundreds or thousands of megabytes is not especially great for our memory usage.

Nothing about the processing we perform inherently precludes us from streaming log output directly from GCS to the browser: if we kept a rolling buffer of just the last n lines, we could emit those when we hit a match and need them for context.

In order to do this we will need to a) ensure we don't end up ungzipping entire files into memory (again, currently we do), and also b) rearrange the use of templates in the log viewer.

/area prow/deck

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

@Katharine is this still happening? I haven't seen sig-scalability complaining lately (lol)
