### ISSUE TITLE
prow/cmd/checkconfig should warn on external-plugins misspelling

### ISSUE THREAD

**Issue by orthros** [kubernetes/test-infra#11879]
**What would you like to be added**:

When running `bazel run //prow/cmd/checkconfig -- --plugin-config=path/to/plugins.yaml --config-path=path/to/config.yaml` as described in getting_started.md, it would be nice to warn the user if:

1. They do not have any `external_plugins` declared
or if
2. They have misspelled `external_plugins` as `external-plugins`

**Why is this needed**:

In the plugins guide as well as throughout the code there are references to the directory `external-plugins` as well as the `plugins.yaml` configuration option `external_plugins` (usually right next to each other). This makes it very easy for a developer to configure their external plugins with a misspelling ("-" instead of "_"), and not realize their mistake.

**Comment by stevekuznetsov** [comment]
I think checking for `"external-plugins"` will be handled by #10812

**Comment by spiffxp** [comment]
/close
Not sure when it was fixed, but as of today checkconfig will warn about unknown fields.
```
$ go run prow/cmd/checkconfig/main.go --config-path prow/config.yaml --plugin-config prow/plugins.yaml
# ...
{
  "component": "checkconfig",
  "file": "/Users/spiffxp/w/kubernetes/test-infra/prow/cmd/checkconfig/main.go:71",
  "func": "main.reportWarning",
  "level": "warning",
  "msg": "unknown fields present in prow/plugins.yaml: external-plugins",
  "time": "2019-07-23T17:04:01-07:00"
}
```
