### ISSUE TITLE
Provide nice way for ProwJobs to report to the GitHub Checks api

### ISSUE THREAD

**Issue by tmc** [kubernetes/test-infra#11889]
Is having prow assist in having ProwJobs report things like neutral issues via 
https://developer.github.com/v3/checks/runs/ in scope for this project or would that be up to a job author?

**Comment by stevekuznetsov** [comment]
We would need to refactor to allow Prow to run as a GitHub App, not using personal OAuth tokens. We're generally aware that this move is a good idea, but I'm not sure we have any immediate plans to do it. If we could figure out exactly what the migration would entail it would be easier to understand the work involved -- for instance, are all APIs we use today available for apps? 

/cc @cjwagner @fejta

**Comment by tmc** [comment]
Perhaps a more basic but related capability would be to have a job submit a custom comment to the relevant PR.

**Comment by stevekuznetsov** [comment]
What would you like to solve with a custom comment? Our artifact/job output viewer, `spyglass`, allows you to build custom views for your data. 

/cc @Katharine

**Comment by tmc** [comment]
Dropping links to ephemeral environments would be an example.

**Comment by DirectXMan12** [comment]
having an integrated "this is the test a thing failed on" without having to leave the GH API would be another nice feature, especially if a repo had nice linter integration.
