### ISSUE TITLE
store junit data in BigQuery and/or sqlite to make it really easy to query and generate reports

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/test-infra#119]
I think this would be very useful for investigation/exploration.

**Comment by rmmh** [comment]
SQLite would be more appropriate than BigQuery, given the small data volume.

Test-history could be modified to support this.

**Comment by fejta** [comment]
The gcloud team does this (mostly to track flakes), I'll send mail with some info

**Comment by fejta** [comment]
@rmmh should we close this out?

**Comment by rmmh** [comment]
Once the PR is created and merged, yes. :)

**Comment by fejta** [comment]
How about now :grin:

**Comment by rmmh** [comment]
Closed by #2156
