### ISSUE TITLE
Boskos is crashlooping

### ISSUE THREAD

**Issue by mborsz** [kubernetes/test-infra#11944]
**What happened**:

All scalability tests (likely all tests globally) are failing with error like:
```
W0326 09:24:07.951] 2019/03/26 09:24:07 main.go:308: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: Post http://boskos.test-pods.svc.cluster.local./acquire?type=scalability-project&state=free&dest=busy&owner=ci-kubernetes-e2e-gci-gce-scalability: dial tcp 10.63.250.132:80: i/o timeout
```

Boskos is crashlooping with error like:

```
maciejborsz@cloudshell:~ (k8s-prow-builds)$ kubectl logs -n test-pods boskos-0
{"error":"CustomResourceDefinition.apiextensions.k8s.io \"resources.boskos.k8s.io\" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion(nil): must have exactly one version marked as storage version, status.storedVersions: Invalid value: []string(nil): must have at least one stored version]","level":"fatal","msg":"unable to create a CRD client","time":"2019-03-26T09:44:13Z"}
maciejborsz@cloudshell:~ (k8s-prow-builds)$
```
**What you expected to happen**:

Boskos is running.

**How to reproduce it (as minimally and precisely as possible)**:
It is happening right in prow cluster.
**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/cc @fejta 
/cc @Katharine 
/cc @krzysied

**Comment by liggitt** [comment]
https://github.com/kubernetes/test-infra/commit/02110870507abdeb93dfd6205c70f82145f8993c#r32917192 looks like the root cause

**Comment by liggitt** [comment]
/priority critical-urgent

this is failing all e2e-gce jobs

**Comment by liggitt** [comment]
added version back in https://github.com/kubernetes/test-infra/pull/11947

**Comment by cjwagner** [comment]
This has been resolved. Postmortem: https://github.com/kubernetes/test-infra/pull/11955
