### ISSUE TITLE
Make branchprotector check if updates are needed applying branch protection policies.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#11989]
**What would you like to be added**:
`branchprotector` currently calls `UpdateBranchProtection` for every branch even if the branches are already up to date. It should instead fetch the current branch protection policy and see if updates are needed before calling `UpdateBranchProtection`.

**Why is this needed**:
This should dramatically improve the performance of `branchprotector` and ultimately save API tokens because the `ghproxy` cache will cache the branch policy lookups, fulfilling subsequent requests for free and without client throttling. The number of `UpdateBranchProtection` calls should also be greatly reduced because very little (if anything) changes between most `branchprotector` runs.

/assign @fejta 
/area prow/branchprotector

**Comment by stevekuznetsov** [comment]
Love it

**Comment by stevekuznetsov** [comment]
Not doing this currently makes branch protection effectively impossible to update on an as-needed basis. One tiny change has to run the entire 3+h job every time.
