### ISSUE TITLE
Owners File Recognition/Reward Bot

### ISSUE THREAD

**Issue by parispittman** [kubernetes/test-infra#11994]
**What would you like to be added**:
A bot that will be kicked off when a PR gets merged adding someone (individual; not an alias) to an owners file as a reviewer or approver. Content will be:

- a congratulations, 
- links to important documentation for reviewers/approvers like community expectations/responsibilities/tips, and 
- instructions on how to get a promo code to order a free contributor patch from the cncf store (email contributors@kubernetes.io with the PR link - or could this be automated too? :) ). 

**Why is this needed**:
we don't reward and recognize our contributors enough in a scalable way, especially our owners who do countless reviews, etc. we also need important community governance and operational docs to be surfaced to these folks.

**Comment by nikhita** [comment]
/sig contributor-experience

The plugin adds a "positive emoji" whenever an owner is added:

https://github.com/kubernetes/test-infra/blob/f7e3d4332d3531ad6507603554d438d84f2fd6e3/prow/plugins/heart/heart.go#L140-L148

I think this is a cool idea :) but just thinking out loud...would it be weird if we are removing more folks than adding? :see_no_evil: :thinking:

**Comment by nikhita** [comment]
>  instructions on how to get a promo code to order a free contributor patch from the cncf store

To be clear, this is only if the contributor doesn't already have the patch, right?

**Comment by parispittman** [comment]
they can collect more than one patch if they wish or ask for another item and if we have the inventory we can provide

**Comment by spiffxp** [comment]
/remove-lifecycle stale
linking to the issue I'm using as an umbrella for all things OWNERS/contributor-ladder related kubernetes/community#1808

**Comment by parispittman** [comment]
/remove-lifecycle stale

still needs to get done :)

**Comment by matthyx** [comment]
@nikhita @parispittman do you still need a hand at this?
Should it be a new plugin, or rename+modify `heart`?

**Comment by matthyx** [comment]
> Content will be:
> 
> * a congratulations,
> * links to important documentation for reviewers/approvers like community expectations/responsibilities/tips, and
> * instructions on how to get a promo code to order a free contributor patch from the cncf store (email [contributors@kubernetes.io](mailto:contributors@kubernetes.io) with the PR link - or could this be automated too? :) ).

@parispittman could you give an example... I think this should go to `config/prow/plugins.yaml`

@cjwagner do you think it's wise to reuse `heart.go` or should I put this in a different plugin?
I think it really depends if we wanna do something generic or specific to k/k

**Comment by cjwagner** [comment]
It seems like this should be easy to make configurable and generic for use outside k/k. I think this would be a reasonable extension to the `heart` plugin if you'd like to integrate there, but as Nikhita mentioned the logic for detecting additions to OWNERS is currently pretty simple and should probably be updated (e.g. distinguish adding users from adding labels).

**Comment by matthyx** [comment]
@cjwagner I wonder if it wouldn't be easier to react inside `verify-owners` as we already load the files and parse the added owners...
I also wonder whether we should not remove heart completely, even though it makes a simple example of a prow plugin.

**Comment by matthyx** [comment]
@parispittman and @nikhita, couple of questions:
- should we comment inside the PR adding the new reviewer/approver, or we contact them differently (mail, slack, …)?
- should we check whether the individual is a trusted user (i.e. member of the org)?
- should we add a specific label to the PR to identify the PRs later?
- what happens if the individual is moved from reviewer -> approver?
- what happens if the individual was already reviewer/approver elsewhere in the same repo?
- what happens if the PR is modified and no new owner is added, should we purge the welcome message?

**Comment by cjwagner** [comment]
> @cjwagner I wonder if it wouldn't be easier to react inside `verify-owners` as we already load the files and parse the added owners...

Sharing code with `verify-owners` would be fine, but I don't think we should add recognition/reward logic to the validation plugin, those a pretty different roles and it would be nice to enable/configure them separately

> I also wonder whether we should not remove heart completely, even though it makes a simple example of a prow plugin.

Unless it's too expensive, which I don't think is the case, I'd like to keep the `heart` plugin. It is simple and fun. I don't think deprecating and removing it would be a productive use of time.

> should we check whether the individual is a trusted user (i.e. member of the org)?

IIRC `verify-owners` will guarantee this and can be assumed to be enabled since `check-config` warns if `approve` or `blunderbuss` are enabled without it.

**Comment by matthyx** [comment]
@cjwagner I have started with something here: https://github.com/kubernetes/test-infra/pull/19449

**Comment by matthyx** [comment]
@parispittman any update on the text+links to include to the comment?

**Comment by parispittman** [comment]
DRAFT:

"Congratulations on the move up on the contributor ladder within the Kubernetes project! 

As a thank you for taking on this service, reach out to #sig-contribex for a special badge for upstream contributors. Check out the [role description](can we auto-link to the right section in community-membership.md depending on if they are going into reviewer or approver to the exact link - if not, just link to the general page?) to make sure you are in line with the duties and responsibilities set out. If for some reason you can't perform the duties associated, Emeritus is a great way to take a break! 

Next steps:
#sig-contribex for your badge [this should have a legit process TODO]
hang with us in #kubernetes-contributors
Review the community-membership.md doc for your role
Look over the related [governance](governance.md) docs; you're involved in the project more than a casual contributor now!"

what else?

**Comment by kikisdeliveryservice** [comment]
maybe `to make sure you are in line with the duties` -> `to confirm that you are able to fulfill the duties`?

**Comment by parispittman** [comment]
@matthyx I think we are finally ready!! LOL I cleaned up the content in the comment above. thank you so much for your patience and sticking with me :)

**Comment by matthyx** [comment]
> @matthyx I think we are finally ready!! LOL I cleaned up the content in the comment above. thank you so much for your patience and sticking with me :)

Let me rebase the PR and we can move on.

**Comment by matthyx** [comment]
I had to open another PR... Let's do it now!

**Comment by matthyx** [comment]
Woot woot @parispittman it's merged!
