### ISSUE TITLE
Demystify what is and is not supported in OWNERS filters

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#11998]
What's the current state of the `filters` block in the OWNERS file implementation? Does it support a fully nested OWNERS full config underneath?

**Comment by cjwagner** [comment]
The config allows for a fully nested OWNERS file under each filter, but the `approve` plugin does not properly handle `approvers` sections in filters besides the global `.*` filter.  IIRC at least one of `blunderbuss`'s reviewer selection algorithms suffers from a similar problem.
