### ISSUE TITLE
Teach podutils to upload files to GCS using gzip encoding

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12012]
Bootstrap has always done this as it reduces log download and upload size: https://github.com/kubernetes/test-infra/blob/3de81d83bb28507c397c6b12e3875fa4a160bf08/jenkins/bootstrap.py#L376

So our tooling like testgrid, spyglass, etc already know how to handle this. We just need to teach initupload and sidecar to upload using this format.

It is a somewhat nifty GCS feature where GCS will either send you the compressed or decompressed file depending on the client functionality: https://cloud.google.com/storage/docs/transcoding

**Comment by stevekuznetsov** [comment]
This got implemented by @wking
