### ISSUE TITLE
autobump failing

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12014]
https://testgrid.k8s.io/sig-testing-prow#autobump-prow

ERROR: /home/prow/go/src/github.com/kubernetes/test-infra/WORKSPACE:14:1: Traceback (most recent call last):
File "/home/prow/go/src/github.com/kubernetes/test-infra/WORKSPACE", line 14
versions.check(minimum_bazel_version = "0.23.0")
File "/root/.cache/bazel/_bazel_root/05618a594cb3499a4b912817865867cd/external/bazel_skylib/lib/versions.bzl", line 106, in versions.check
fail("Current Bazel version is {}; ex...))
Current Bazel version is 0.21.0; expected at least 0.23.0
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'go/deps.bzl': no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package

looks like we need a newer bazel image

**Comment by fejta** [comment]
Job definition is here, which shows the image it uses: https://github.com/kubernetes/test-infra/blob/9484b12ccfbfe0889a32f83badeaf26ffa9f4d0a/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L174-L183

The bazelbuild image is produced here: https://github.com/kubernetes/test-infra/tree/master/images/bazelbuild

**Comment by fejta** [comment]
So AKA this is about a) pushing versions of this image that use versions 0.23 and 0.24 versions of bazel and b) updating the job to use one of these images

**Comment by tony-yang** [comment]
New PR https://github.com/kubernetes/test-infra/pull/12016
