### ISSUE TITLE
milestones should rank higher in the submit queue

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#1201]
For example if we have 2 PR(s) with ["P3","v1.5"] or ["P2","v1.6"] 

Currently we are prioritizing the 1.6 above the 1.5... Can we please do the opposite?

**Comment by dims** [comment]
cc @saad-ali @rmmh

**Comment by saad-ali** [comment]
http://submit-queue.k8s.io/#/info Looks like "by design" the priority labels take precedence over milestone. We should change that. In the mean time we can manually bump the priority of 1.5 PRs

**Comment by rmmh** [comment]
Changing this might be a little tricky. In this case we want the 1.5 PRs to have higher priority, but if we change the logic in a simple way, just labelling your PR with *any* milestone will cause it to be treated as more important than a P0 issue.

**Comment by rmmh** [comment]
Duplicate of kubernetes/contrib#2083.
