### ISSUE TITLE
ghprbPullId no longer exported as just the number

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes/test-infra#1202]
Recently Charts CI started to fail because the ghprbPullId environment variable is now being set to the branch:commit. Is there another variable that holds the PR number?

```
ghprbPullId=master:14bee1e456c1789d1ebdfc2dc7e3ae2b9ea930ce,223:a5e1b12e9605de227f330a40a3dedcd5f1e5c6c2
```

Example: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/223/pull-charts-e2e/252/

**Comment by spxtr** [comment]
Oh, sorry about that. I'll get the fix out today.

**Comment by spxtr** [comment]
1. Add new env var `PULL_REFS` which contains the refs that are currently in `ghprbPullId` and `PULL_NUMBER`.
2. Switch all uses of `ghprbPullId` to either `PULL_REFS` or `PULL_NUMBER`, whichever is required.
3. Delete `ghprbPullId`.

**Comment by spxtr** [comment]
@viglesiasce `PULL_NUMBER` is just the number, please use that. While you're making this fix, I would appreciate if you could look for `ghprbTargetBranch` as well and replace that with `PULL_BASE_REF`. I'd like to get rid of `ghprb*` for good.

**Comment by viglesiasce** [comment]
Thanks @spxtr! Ill see if we have any ```ghprbTargetBranch``` lying around (I dont believe we do). 

We are however seeing an issue with Jenkins not cloning the correct master branch for PRs. For example https://github.com/kubernetes/charts/pull/223 is being tested against 14bee1e456 rather than the current master commit b5aa3f. Any ideas why that would be?

**Comment by spxtr** [comment]
Ooh, if that's caused by what I think it is then that's a pretty big issue, thanks for letting me know.

**Comment by spxtr** [comment]
#1251

**Comment by spxtr** [comment]
Please open another issue if you have further problems :)
