### ISSUE TITLE
blunderbuss should resolve aliases before picking from the set

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12022]
/area prow
/cc @cjwagner 
/help

https://github.com/kubernetes-sigs/krew-index/blob/master/OWNERS there's just one alias

however the alias has two people, so it should assign both people in the alias

https://github.com/kubernetes-sigs/krew-index/blob/master/OWNERS_ALIASES

Instead it seems to think the alias is equivalent to one person, and just picks one of them.

This further suggests that blunderbuss will disproportionately not assign people in aliases, putting undo burden on others.

```
jsonPayload: {
  author:  "gabeduke"   
  component:  "hook"   
  event-GUID:  "aecf1d70-5504-11e9-8b95-271e615c43c3"   
  event-type:  "pull_request"   
  level:  "warning"   
  msg:  "Not enough reviewers found in OWNERS files for files touched by this PR. 1/2 reviewers found."   
  org:  "kubernetes-sigs"   
  plugin:  "blunderbuss"   
  pr:  127   
  repo:  "krew-index"   
  url:  "https://github.com/kubernetes-sigs/krew-index/pull/127"   
 }
```

**Comment by fejta** [comment]
Code is here: https://github.com/kubernetes/test-infra/blob/master/prow/plugins/blunderbuss/blunderbuss.go

**Comment by nikhita** [comment]
> Instead it seems to think the alias is equivalent to one person, and just picks one of them.

I guess that's because @juanvallejo hadn't accepted the org membership request yet (only @ahmetb had), so it just requested review from one person.

**Comment by cjwagner** [comment]
That would explain it. We filter out non-collaborators since we can't assign or request reviews from them.
Forbidding non-collaborators from OWNERS files is something that `verify-config` could be updated to enforce: https://github.com/kubernetes/test-infra/issues/5175#issuecomment-427637685

/close
