### ISSUE TITLE
Stop posting "Skipped" statuses.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#12047]
ref: https://github.com/kubernetes/test-infra/pull/11333

We should be safe to configure trigger to stop posting "Skipped" statuses now that branchprotector has removed protection from all `run_if_changed` status contexts.

/cc @stevekuznetsov @fejta @spiffxp @cblecker

**Comment by stevekuznetsov** [comment]
@cjwagner let's do this?

/remove-lifecycle stale

**Comment by matthyx** [comment]
@cjwagner @stevekuznetsov Is it just to set `ElideSkippedContexts` in config(s)? Or do we want to get rid of the flag?

**Comment by cjwagner** [comment]
Just to set the `elide_skipped_contexts`. I just made the PR.
We can probably switch to defaulting to `elide_skipped_contexts: true` soon if we want, or remove the option altogether. I don't think there is any reason to use `elide_skipped_contexts: false` unless you are using branchprotector and haven't updated since February.
