### ISSUE TITLE
switch pull-kubernetes-godeps to `make verify WHAT=vendor` on master

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#12045]
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/godeps.yaml#L18-L31 calls `make verify WHAT=godeps staging-godeps godep-licenses`

After https://github.com/kubernetes/kubernetes/pull/74877 merges:
* staging-godeps no longer exists
* verify-godeps.sh is a shim that calls verify-vendor.sh
* verify-godep-licenses.sh is a shim that calls verify-vendor-licenses.sh

Since vendor verification now takes ~3 minutes instead of ~30, would it make sense to:
* fold vendor verification back into the pull-kubernetes-verify job
* limit the pull-kubernetes-godeps job to non-master release branches that still use godeps

once CI no longer calls verify-godeps / verify-godep-licenses, we can remove those shims

**Comment by cblecker** [comment]
It may still be worth keeping it separate, because it's a network-dependant job. If there is a network timeout, it would be advantageous to not have to retest the whole verify job.

https://github.com/kubernetes/test-infra/pull/12104 will branch the job for master.
