### ISSUE TITLE
Add a plugin that enforces "Fixes #ISSUENUMBER" string in PR

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#12041]
**What would you like to be added**:

A plugin that when activated checks if the body of a PR has a `fixes #123` string. If that is not the case, it adds a label that can be used to prevent tide from merging.  It should also be possible to overwrite that check with a command.

**Why is this needed**:

Makes enforcing to have an issue for PRs possible

**Comment by nikhita** [comment]
We have

https://github.com/kubernetes/test-infra/blob/c48de18590ee942f6548734f454b1e5113094ae8/prow/plugins/config.go#L228-L233

**Comment by alvaroaleman** [comment]
That will idd do once #12042 is in
