### ISSUE TITLE
PR title tooltips on tide-history page disappear when filter is modified.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#12081]
The PR title tooltips that appear when you hover over a PR number on the tide-history page do not work after editing the filter selection. The page has to be refreshed after the filter is modified in order for the tooltips to work again.

Example: 
1) Go to the following link and notice the hover tooltips on the PR numbers: https://prow.k8s.io/tide-history?repo=kubernetes%2Fk8s.io
1) Change the branch filter to select `master` and notice that the tooltips no longer appear on hover.
1) Refresh the page and see that the tooltips work again.

I'm not sure why this is happening, but I suspect it is a simple fix. @Katharine do you know what is going on here?

/area prow/deck

**Comment by stevekuznetsov** [comment]
xref #10605 ?

**Comment by Katharine** [comment]
/reopen
/remove-lifecycle rotten

pretty sure we never fixed this
