### ISSUE TITLE
terminateDupProwJobs uses the wrong abstractions

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12083]
`terminateDupProwJobs` needs:
* to be a stand-alone function, not part of the controller
* should not have `context` or `namespace` arguments, as these are immutable parts of the interface

The reconciler interface needs to
* add a `listJobs` (aka getProwJobs) method
* drop the `terminateDupProwJobs` method

`fakeReconciler` needs to define the `listJobs` method and drop its useless `terminateDupProwJobs` method.

`TestTerminateDupProwJobs` needs to take advantage of the `reconciler` interface and drop the `fake_buildset` interface.

/assign

**Comment by stevekuznetsov** [comment]
What do we need to list jobs for? Why do the controllers not call terminate on the list? I want to stop listing as much as possible, it's absolutely untenable. 90% of our API traffic on a large cluster with lots of other workloads comes from the LIST call to ProwJobs
