### ISSUE TITLE
Do a minor upgrade of all modules

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12107]
Ideally we get to a point where https://testgrid.k8s.io/sig-testing-maintenance#autoupdate-minor passes

Currently having to:
* Refactor our build controller to stop using the generated client fake (testing package changed)
* Replace 3 packages:
  - `k8s.io/client-go` to force a more recent commit than latest release - https://github.com/kubernetes/kubernetes/issues/76304
  - `Replace github.com/evanphx/json-patch` to force a more recent commit than latest release - https://github.com/evanphx/json-patch/issues/76 
  - `sigs.k8s.io/sturctured-merge-diff` to force an older commit that k/k uses - https://github.com/kubernetes/kubernetes/issues/76249

Current problem is that test-infra vendors knative/build and this uses the now-deleted `serializer.DirectCodecFactory`

/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/321/execroot/io_k8s_test_infra/vendor/github.com/knative/build/pkg/client/clientset/versioned/typed/build/v1alpha1/build_client.go:81:32: undefined: serializer.DirectCodecFactory

/cc @liggitt @smarterclayton 
https://github.com/kubernetes/kubernetes/pull/76098

This will cause `hack/e2e.go` -- which runs `go get -u k8s.io/test-infra` -- to fail whenever modules are turned on.

**Comment by liggitt** [comment]
will add back a type alias

**Comment by liggitt** [comment]
type alias in https://github.com/kubernetes/kubernetes/pull/76270
