### ISSUE TITLE
Add testgrid for Kubernetes deployable build on K8s/cloud-provider-gcp

### ISSUE THREAD

**Issue by cheftako** [kubernetes/test-infra#12127]
**What would you like to be added**:
Testgrid integration for  K8s/cloud-provider-gcp.
We added support for a Kubernetes deployable to GCE build with https://github.com/kubernetes/cloud-provider-gcp/pull/75.

**Why is this needed**:
We need testgrid integration as part of the cloud-provider extraction effort.
The cloud-provider-gcp build is intended to replace the in-tree GCE build.
We need an equivalent signal as to everything being working.

**Comment by amwat** [comment]
https://testgrid.k8s.io/provider-gcp-presubmits#cloud-provider-gcp-tests
