### ISSUE TITLE
Prow not working on new pr

### ISSUE THREAD

**Issue by garganubhav** [kubernetes/test-infra#12120]
Hi, I am trying to deploy prow manually as described here - https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md, but it does not work at all when I open a new pr. I can't see a size label as well as anything on my dashboard? I am doing it exactly as described in steps.
Thanks.

**Comment by garganubhav** [comment]
Hi, thanks for reply. 
Yes for first question. But nothing is shown on prow dashboard except echo test.
Headers
`Request URL: http://34.95.78.25
Request method: POST
content-type: application/x-www-form-urlencoded
Expect: 
User-Agent: GitHub-Hookshot/38ab7f6
X-GitHub-Delivery: fe43e610-5af9-11e9-8c76-109449048b0e
X-GitHub-Event: pull_request
X-Hub-Signature: sha1=33438b713e55ce36c85df81c97f723232aab5f9c`
Payload
`{
  "action": "opened",
  "number": 2,
  "pull_request": {
    "url": "https://api.github.com/repos/garganubhav/prow/pulls/2",
    "id": 268880545,
    "node_id": "MDExOlB1bGxSZXF1ZXN0MjY4ODgwNTQ1",
    "html_url": "https://github.com/garganubhav/prow/pull/2",
    "diff_url": "https://github.com/garganubhav/prow/pull/2.diff",
    "patch_url": "https://github.com/garganubhav/prow/pull/2.patch",
    "issue_url": "https://api.github.com/repos/garganubhav/prow/issues/2",
    "number": 2,
    "state": "open",
    "locked": false,
    "title": "dwsc",
    "user": {
      "login": "garganubhav",
      "id": 19604023,
      "node_id": "MDQ6VXNlcjE5NjA0MDIz",
      "avatar_url": "https://avatars0.githubusercontent.com/u/19604023?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/garganubhav",
      "html_url": "https://github.com/garganubhav",
      "followers_url": "https://api.github.com/users/garganubhav/followers",
      "following_url": "https://api.github.com/users/garganubhav/following{/other_user}",
      "gists_url": "https://api.github.com/users/garganubhav/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/garganubhav/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/garganubhav/subscriptions",
      "organizations_url": "https://api.github.com/users/garganubhav/orgs",
      "repos_url": "https://api.github.com/users/garganubhav/repos",
      "events_url": "https://api.github.com/users/garganubhav/events{/privacy}",
      "received_events_url": "https://api.github.com/users/garganubhav/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "",
    "created_at": "2019-04-09T19:02:16Z",
    "updated_at": "2019-04-09T19:02:16Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [

    ],
    "milestone": null,
    "commits_url": "https://api.github.com/repos/garganubhav/prow/pulls/2/commits",
    "review_comments_url": "https://api.github.com/repos/garganubhav/prow/pulls/2/comments",
    "review_comment_url": "https://api.github.com/repos/garganubhav/prow/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/garganubhav/prow/issues/2/comments",
    "statuses_url": "https://api.github.com/repos/garganubhav/prow/statuses/5f4762ba6ae9f48881b2b4b022de08a066423f2a",
    "head": {
      "label": "garganubhav:branch",
      "ref": "branch",
      "sha": "5f4762ba6ae9f48881b2b4b022de08a066423f2a",
      "user": {
        "login": "garganubhav",
        "id": 19604023,
        "node_id": "MDQ6VXNlcjE5NjA0MDIz",
        "avatar_url": "https://avatars0.githubusercontent.com/u/19604023?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/garganubhav",
        "html_url": "https://github.com/garganubhav",
        "followers_url": "https://api.github.com/users/garganubhav/followers",
        "following_url": "https://api.github.com/users/garganubhav/following{/other_user}",
        "gists_url": "https://api.github.com/users/garganubhav/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/garganubhav/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/garganubhav/subscriptions",
        "organizations_url": "https://api.github.com/users/garganubhav/orgs",
        "repos_url": "https://api.github.com/users/garganubhav/repos",
        "events_url": "https://api.github.com/users/garganubhav/events{/privacy}",
        "received_events_url": "https://api.github.com/users/garganubhav/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 180247654,
        "node_id": "MDEwOlJlcG9zaXRvcnkxODAyNDc2NTQ=",
        "name": "prow",
        "full_name": "garganubhav/prow",
        "private": true,
        "owner": {
          "login": "garganubhav",
          "id": 19604023,
          "node_id": "MDQ6VXNlcjE5NjA0MDIz",
          "avatar_url": "https://avatars0.githubusercontent.com/u/19604023?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/garganubhav",
          "html_url": "https://github.com/garganubhav",
          "followers_url": "https://api.github.com/users/garganubhav/followers",
          "following_url": "https://api.github.com/users/garganubhav/following{/other_user}",
          "gists_url": "https://api.github.com/users/garganubhav/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/garganubhav/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/garganubhav/subscriptions",
          "organizations_url": "https://api.github.com/users/garganubhav/orgs",
          "repos_url": "https://api.github.com/users/garganubhav/repos",
          "events_url": "https://api.github.com/users/garganubhav/events{/privacy}",
          "received_events_url": "https://api.github.com/users/garganubhav/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/garganubhav/prow",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/garganubhav/prow",
        "forks_url": "https://api.github.com/repos/garganubhav/prow/forks",
        "keys_url": "https://api.github.com/repos/garganubhav/prow/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/garganubhav/prow/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/garganubhav/prow/teams",
        "hooks_url": "https://api.github.com/repos/garganubhav/prow/hooks",
        "issue_events_url": "https://api.github.com/repos/garganubhav/prow/issues/events{/number}",
        "events_url": "https://api.github.com/repos/garganubhav/prow/events",
        "assignees_url": "https://api.github.com/repos/garganubhav/prow/assignees{/user}",
        "branches_url": "https://api.github.com/repos/garganubhav/prow/branches{/branch}",
        "tags_url": "https://api.github.com/repos/garganubhav/prow/tags",
        "blobs_url": "https://api.github.com/repos/garganubhav/prow/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/garganubhav/prow/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/garganubhav/prow/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/garganubhav/prow/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/garganubhav/prow/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/garganubhav/prow/languages",
        "stargazers_url": "https://api.github.com/repos/garganubhav/prow/stargazers",
        "contributors_url": "https://api.github.com/repos/garganubhav/prow/contributors",
        "subscribers_url": "https://api.github.com/repos/garganubhav/prow/subscribers",
        "subscription_url": "https://api.github.com/repos/garganubhav/prow/subscription",
        "commits_url": "https://api.github.com/repos/garganubhav/prow/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/garganubhav/prow/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/garganubhav/prow/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/garganubhav/prow/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/garganubhav/prow/contents/{+path}",
        "compare_url": "https://api.github.com/repos/garganubhav/prow/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/garganubhav/prow/merges",
        "archive_url": "https://api.github.com/repos/garganubhav/prow/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/garganubhav/prow/downloads",
        "issues_url": "https://api.github.com/repos/garganubhav/prow/issues{/number}",
        "pulls_url": "https://api.github.com/repos/garganubhav/prow/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/garganubhav/prow/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/garganubhav/prow/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/garganubhav/prow/labels{/name}",
        "releases_url": "https://api.github.com/repos/garganubhav/prow/releases{/id}",
        "deployments_url": "https://api.github.com/repos/garganubhav/prow/deployments",
        "created_at": "2019-04-08T23:23:24Z",
        "updated_at": "2019-04-08T23:23:27Z",
        "pushed_at": "2019-04-09T19:01:07Z",
        "git_url": "git://github.com/garganubhav/prow.git",
        "ssh_url": "git@github.com:garganubhav/prow.git",
        "clone_url": "https://github.com/garganubhav/prow.git",
        "svn_url": "https://github.com/garganubhav/prow",
        "homepage": null,
        "size": 3,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": null,
        "forks": 0,
        "open_issues": 2,
        "watchers": 0,
        "default_branch": "master"
      }
    },
    "base": {
      "label": "garganubhav:master",
      "ref": "master",
      "sha": "19fba7ddf938abb2c9954474360eeccc55403f80",
      "user": {
        "login": "garganubhav",
        "id": 19604023,
        "node_id": "MDQ6VXNlcjE5NjA0MDIz",
        "avatar_url": "https://avatars0.githubusercontent.com/u/19604023?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/garganubhav",
        "html_url": "https://github.com/garganubhav",
        "followers_url": "https://api.github.com/users/garganubhav/followers",
        "following_url": "https://api.github.com/users/garganubhav/following{/other_user}",
        "gists_url": "https://api.github.com/users/garganubhav/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/garganubhav/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/garganubhav/subscriptions",
        "organizations_url": "https://api.github.com/users/garganubhav/orgs",
        "repos_url": "https://api.github.com/users/garganubhav/repos",
        "events_url": "https://api.github.com/users/garganubhav/events{/privacy}",
        "received_events_url": "https://api.github.com/users/garganubhav/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 180247654,
        "node_id": "MDEwOlJlcG9zaXRvcnkxODAyNDc2NTQ=",
        "name": "prow",
        "full_name": "garganubhav/prow",
        "private": true,
        "owner": {
          "login": "garganubhav",
          "id": 19604023,
          "node_id": "MDQ6VXNlcjE5NjA0MDIz",
          "avatar_url": "https://avatars0.githubusercontent.com/u/19604023?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/garganubhav",
          "html_url": "https://github.com/garganubhav",
          "followers_url": "https://api.github.com/users/garganubhav/followers",
          "following_url": "https://api.github.com/users/garganubhav/following{/other_user}",
          "gists_url": "https://api.github.com/users/garganubhav/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/garganubhav/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/garganubhav/subscriptions",
          "organizations_url": "https://api.github.com/users/garganubhav/orgs",
          "repos_url": "https://api.github.com/users/garganubhav/repos",
          "events_url": "https://api.github.com/users/garganubhav/events{/privacy}",
          "received_events_url": "https://api.github.com/users/garganubhav/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/garganubhav/prow",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/garganubhav/prow",
        "forks_url": "https://api.github.com/repos/garganubhav/prow/forks",
        "keys_url": "https://api.github.com/repos/garganubhav/prow/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/garganubhav/prow/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/garganubhav/prow/teams",
        "hooks_url": "https://api.github.com/repos/garganubhav/prow/hooks",
        "issue_events_url": "https://api.github.com/repos/garganubhav/prow/issues/events{/number}",
        "events_url": "https://api.github.com/repos/garganubhav/prow/events",
        "assignees_url": "https://api.github.com/repos/garganubhav/prow/assignees{/user}",
        "branches_url": "https://api.github.com/repos/garganubhav/prow/branches{/branch}",
        "tags_url": "https://api.github.com/repos/garganubhav/prow/tags",
        "blobs_url": "https://api.github.com/repos/garganubhav/prow/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/garganubhav/prow/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/garganubhav/prow/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/garganubhav/prow/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/garganubhav/prow/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/garganubhav/prow/languages",
        "stargazers_url": "https://api.github.com/repos/garganubhav/prow/stargazers",
        "contributors_url": "https://api.github.com/repos/garganubhav/prow/contributors",
        "subscribers_url": "https://api.github.com/repos/garganubhav/prow/subscribers",
        "subscription_url": "https://api.github.com/repos/garganubhav/prow/subscription",
        "commits_url": "https://api.github.com/repos/garganubhav/prow/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/garganubhav/prow/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/garganubhav/prow/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/garganubhav/prow/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/garganubhav/prow/contents/{+path}",
        "compare_url": "https://api.github.com/repos/garganubhav/prow/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/garganubhav/prow/merges",
        "archive_url": "https://api.github.com/repos/garganubhav/prow/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/garganubhav/prow/downloads",
        "issues_url": "https://api.github.com/repos/garganubhav/prow/issues{/number}",
        "pulls_url": "https://api.github.com/repos/garganubhav/prow/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/garganubhav/prow/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/garganubhav/prow/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/garganubhav/prow/labels{/name}",
        "releases_url": "https://api.github.com/repos/garganubhav/prow/releases{/id}",
        "deployments_url": "https://api.github.com/repos/garganubhav/prow/deployments",
        "created_at": "2019-04-08T23:23:24Z",
        "updated_at": "2019-04-08T23:23:27Z",
        "pushed_at": "2019-04-09T19:01:07Z",
        "git_url": "git://github.com/garganubhav/prow.git",
        "ssh_url": "git@github.com:garganubhav/prow.git",
        "clone_url": "https://github.com/garganubhav/prow.git",
        "svn_url": "https://github.com/garganubhav/prow",
        "homepage": null,
        "size": 3,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": null,
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": null,
        "forks": 0,
        "open_issues": 2,
        "watchers": 0,
        "default_branch": "master"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/garganubhav/prow/pulls/2"
      },
      "html": {
        "href": "https://github.com/garganubhav/prow/pull/2"
      },
      "issue": {
        "href": "https://api.github.com/repos/garganubhav/prow/issues/2"
      },
      "comments": {
        "href": "https://api.github.com/repos/garganubhav/prow/issues/2/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/garganubhav/prow/pulls/2/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/garganubhav/prow/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/garganubhav/prow/pulls/2/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/garganubhav/prow/statuses/5f4762ba6ae9f48881b2b4b022de08a066423f2a"
      }
    },
    "author_association": "OWNER",
    "draft": false,
    "merged": false,
    "mergeable": null,
    "rebaseable": null,
    "mergeable_state": "unknown",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": false,
    "commits": 1,
    "additions": 228,
    "deletions": 0,
    "changed_files": 1
  },
  "repository": {
    "id": 180247654,
    "node_id": "MDEwOlJlcG9zaXRvcnkxODAyNDc2NTQ=",
    "name": "prow",
    "full_name": "garganubhav/prow",
    "private": true,
    "owner": {
      "login": "garganubhav",
      "id": 19604023,
      "node_id": "MDQ6VXNlcjE5NjA0MDIz",
      "avatar_url": "https://avatars0.githubusercontent.com/u/19604023?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/garganubhav",
      "html_url": "https://github.com/garganubhav",
      "followers_url": "https://api.github.com/users/garganubhav/followers",
      "following_url": "https://api.github.com/users/garganubhav/following{/other_user}",
      "gists_url": "https://api.github.com/users/garganubhav/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/garganubhav/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/garganubhav/subscriptions",
      "organizations_url": "https://api.github.com/users/garganubhav/orgs",
      "repos_url": "https://api.github.com/users/garganubhav/repos",
      "events_url": "https://api.github.com/users/garganubhav/events{/privacy}",
      "received_events_url": "https://api.github.com/users/garganubhav/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/garganubhav/prow",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/garganubhav/prow",
    "forks_url": "https://api.github.com/repos/garganubhav/prow/forks",
    "keys_url": "https://api.github.com/repos/garganubhav/prow/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/garganubhav/prow/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/garganubhav/prow/teams",
    "hooks_url": "https://api.github.com/repos/garganubhav/prow/hooks",
    "issue_events_url": "https://api.github.com/repos/garganubhav/prow/issues/events{/number}",
    "events_url": "https://api.github.com/repos/garganubhav/prow/events",
    "assignees_url": "https://api.github.com/repos/garganubhav/prow/assignees{/user}",
    "branches_url": "https://api.github.com/repos/garganubhav/prow/branches{/branch}",
    "tags_url": "https://api.github.com/repos/garganubhav/prow/tags",
    "blobs_url": "https://api.github.com/repos/garganubhav/prow/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/garganubhav/prow/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/garganubhav/prow/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/garganubhav/prow/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/garganubhav/prow/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/garganubhav/prow/languages",
    "stargazers_url": "https://api.github.com/repos/garganubhav/prow/stargazers",
    "contributors_url": "https://api.github.com/repos/garganubhav/prow/contributors",
    "subscribers_url": "https://api.github.com/repos/garganubhav/prow/subscribers",
    "subscription_url": "https://api.github.com/repos/garganubhav/prow/subscription",
    "commits_url": "https://api.github.com/repos/garganubhav/prow/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/garganubhav/prow/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/garganubhav/prow/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/garganubhav/prow/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/garganubhav/prow/contents/{+path}",
    "compare_url": "https://api.github.com/repos/garganubhav/prow/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/garganubhav/prow/merges",
    "archive_url": "https://api.github.com/repos/garganubhav/prow/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/garganubhav/prow/downloads",
    "issues_url": "https://api.github.com/repos/garganubhav/prow/issues{/number}",
    "pulls_url": "https://api.github.com/repos/garganubhav/prow/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/garganubhav/prow/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/garganubhav/prow/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/garganubhav/prow/labels{/name}",
    "releases_url": "https://api.github.com/repos/garganubhav/prow/releases{/id}",
    "deployments_url": "https://api.github.com/repos/garganubhav/prow/deployments",
    "created_at": "2019-04-08T23:23:24Z",
    "updated_at": "2019-04-08T23:23:27Z",
    "pushed_at": "2019-04-09T19:01:07Z",
    "git_url": "git://github.com/garganubhav/prow.git",
    "ssh_url": "git@github.com:garganubhav/prow.git",
    "clone_url": "https://github.com/garganubhav/prow.git",
    "svn_url": "https://github.com/garganubhav/prow",
    "homepage": null,
    "size": 3,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "forks": 0,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "garganubhav",
    "id": 19604023,
    "node_id": "MDQ6VXNlcjE5NjA0MDIz",
    "avatar_url": "https://avatars0.githubusercontent.com/u/19604023?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/garganubhav",
    "html_url": "https://github.com/garganubhav",
    "followers_url": "https://api.github.com/users/garganubhav/followers",
    "following_url": "https://api.github.com/users/garganubhav/following{/other_user}",
    "gists_url": "https://api.github.com/users/garganubhav/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/garganubhav/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/garganubhav/subscriptions",
    "organizations_url": "https://api.github.com/users/garganubhav/orgs",
    "repos_url": "https://api.github.com/users/garganubhav/repos",
    "events_url": "https://api.github.com/users/garganubhav/events{/privacy}",
    "received_events_url": "https://api.github.com/users/garganubhav/received_events",
    "type": "User",
    "site_admin": false
  }
}`

**Comment by stevekuznetsov** [comment]
Could you turn your `hook` log level to `debug` (in `config.yaml`) and post the logs from `hook`?

**Comment by garganubhav** [comment]
sorry, I don't see any `hook` key in config.yaml, I am following this https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#add-more-jobs-by-modifying-configyaml
