### ISSUE TITLE
Handling of vendor/.../OWNERS with rebases is annoying

### ISSUE THREAD

**Issue by danwinship** [kubernetes/test-infra#12136]
I keep getting automated review requests when people bump their kubernetes dependency in various openshift subprojects just because I'm listed as a reviewer in a few parts of the kubernetes tree.

eg, https://github.com/openshift/service-ca-operator/pull/40, https://github.com/openshift/kubernetes-autoscaler/pull/76, https://github.com/openshift/console-operator/pull/163, https://github.com/openshift/image-registry/pull/166, https://github.com/openshift/service-ca-operator/pull/16, https://github.com/openshift/cluster-api-provider-aws/pull/160. I don't even know what some of those projects do. They definitely don't want me reviewing their rebases.

In previous discussions of vendor-vs-OWNERS (eg, #3694, #6404) it was pointed out that obeying vendored OWNERS files can be useful because the people listed there are likely to be the people you want reviewing the change. But that only applies to the case of cherry-picking a single fix or making a small local change. In the case of a rebase, the review request is basically just saying "Hey, remember when we changed this code upstream a few months ago? Yeah, those were good times!"

So, ideas:
1. Ignore OWNERS under vendor/, despite the fact that sometimes it's useful not to
2. Ignore `reviewers` in OWNERS under vendor/, but still obey `approvers`?
3. Try to distinguish cherry-picks from rebases, and ignore vendored OWNERS on the latter? (Eg, if there are changes to `glide.yaml` or `Godeps.json` then ignore vendored OWNERS)
4. Start changing OWNERS files in kubernetes to use `sig-network-reviewers` rather than explicit lists of reviewers, so that submit-queue won't be able to see me there any more? :man_shrugging:

**Comment by stevekuznetsov** [comment]
Great questions, Dan.

/cc @cjwagner @fejta

**Comment by stevekuznetsov** [comment]
Didn't `kubernetes/kubernetes` just take a different approach to handling changes to `vendor/`? @liggitt @cblecker

**Comment by liggitt** [comment]
Not as relates to this. I wouldn't expect OWNERS files within a component inside vendor to do anything inside a repo.

**Comment by cblecker** [comment]
Well we moved to generate vendor using go modules instead of godep.. but other than that, we're not really doing anything different. IMO, OWNERS files in subdirs of vendor should be ignored. I know we have `OwnersDirBlacklist`, but I don't know if it'll do the trick:
https://github.com/kubernetes/test-infra/blob/ef11decebeaf73a4b0f5aeff44f0f348cf0eb8ec/prow/config/config.go#L112-L114

I know in k/k, we would want `vendor/OWNERS` respected, but not anything underneath it.

**Comment by danwinship** [comment]
> I know we have `OwnersDirBlacklist`, but I don't know if it'll do the trick:

> I know in k/k, we would want `vendor/OWNERS` respected, but not anything underneath it.

Putting `vendor` into `OwnersDirBlacklist` would make `vendor/OWNERS` be ignored too.

I can't figure out if doing

    filters:
      "vendor":
        approvers:
        - dep-approvers

in the top-level `OWNERS` would work as a replacement for `vendor/OWNERS`.

**Comment by cblecker** [comment]
The other way we could possibly do it is adding an option like `no_parent_owners` that would ignore any child owners files below that one. I don't know how complicated that would be code wise, though.

**Comment by cjwagner** [comment]
Easiest option might be to make `OwnersDirBlacklist` treat values as regular expressions instead of literal directory paths. That isn't technically backwards compatible, but I think it would be fine.
We could then add a `^/vendor/.+/` entry to `OwnersDirBlacklist` to ignore OWNERS files under `/vendor/` except for `/vendor/OWNERS`.

**Comment by cblecker** [comment]
I'm good with that approach too

**Comment by stevekuznetsov** [comment]
That's only backwards incompatible to people who have directories or files that are named valid regex, so I think that's fine
