### ISSUE TITLE
No periodic jobs are running since ~15:30 PST Apr 8th

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/test-infra#12130]
As an example scalability jobs:
https://testgrid.k8s.io/sig-scalability-gce#gci-gce-scalability

Both nothing fired in prow since then:
https://prow.k8s.io/?type=periodic

@kubernetes/sig-testing @kubernetes/test-infra-maintainers

**Comment by Katharine** [comment]
This was caused by reverting a PR that had created a bug. Ironically, the revert triggered the bug on our instance.

I've fixed the issue, and periodic jobs are now running as expected.
