### ISSUE TITLE
Unit test prow flags

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12137]
We should validate that flag values work as expected.

See https://github.com/kubernetes/test-infra/blob/86a523febb3c6af836859dda5624dcbea7204f7a/prow/cmd/build/main_test.go#L25-L66 for an example of what this will look like

Also likely will require passing in a flagset and args to the gather method: https://github.com/kubernetes/test-infra/blob/86a523febb3c6af836859dda5624dcbea7204f7a/prow/cmd/build/main.go#L72

P0
- [x] build
- [ ] crier
- [ ] deck
- [ ] hook
- [x] horologium
- [ ] plank
- [x] sinker
- [ ] tide

P1
- [ ] checkconfig
- [ ] clonerefs
- [ ] entrypoint
- [ ] gcsupload
- [ ] initupload
- [ ] sidecar

P2
- [ ] artifact-uploader
- [ ] branch-protector
- [ ] config-bootstrapper
- [ ] gerrit
- [ ] jenkins-operator
- [ ] status-reconciler
- [ ] sub

P3
- [ ] mkbuild-cluster
- [ ] mkpj
- [ ] mkpod
- [ ] peribolos
- [ ] phony
- [ ] tackle
- [ ] tot

/area prow

**Comment by fejta** [comment]
/help
/good-first-issue

Good opportunity to learn about various pieces of the system!

**Comment by hemanik** [comment]
@fejta, would like to pick this.

**Comment by chases2** [comment]
@yashbhutwala @fejta "Crier" is the only P0 command that hasn't been addressed left, correct?

**Comment by chases2** [comment]
@fejta Can we update the checkboxes to clarify which components still need tests?
