### ISSUE TITLE
PRs under Prow needs manual update with master after Branch protection enabled

### ISSUE THREAD

**Issue by mukesh-panigrahi** [kubernetes/test-infra#12218]
Hello I am working on setting up a Prow cluster recently, where I do a 'source to deploy' kind of thing with the app code.

One challenge I am facing (maybe I need to change some settings in prow or Github repo side) is when I raise multiple PRs, all my builds pass individually. I have branch protection enabled to the repo where I have checked the box for 'Require branches to be up to date before merging'. Once I merge a PR to master, I need to **manually update my all PRs**, which triggers the required Pre-submit jobs. I need to do this for all my open PRs whenever a merge is made which triggers all the previous passed jobs again.

I want to make sure my image created should contain all features of merged PRs before.

Is there a better way to handle this with Prow?

**Comment by stevekuznetsov** [comment]
Don't enable that feature. If the branch your PR is proposing cannot be automatically merged, it will require a rebase, if not, `git` will handle everything. The `tide` automation ensures that your commits are tested against the latest version of the target branch you're trying to merge into, which is a _stronger_ version of the "up to date" feature that GitHub has implemented, so the GitHub option is superfluous.

/cc @cjwagner

**Comment by cjwagner** [comment]
See number 5 here for more details: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/maintainers.md#best-practices

**Comment by mukesh-panigrahi** [comment]
Ok. Got it. will look into it.

One more quick query, is there any provision in prow where we can state the order of job to execute. 
Eg. if my job 1 succeeds (which is unconditional in nature) it should trigger my second job specified automatically. or before other way round if job 2 fails it should rerun job 1 followed by job 2.

I have few logics in my code, which makes sure that if last build was diverged from master, it should fail.
As of now I have to retrigger it by adding comments to rerun jobs.

**Comment by fejta** [comment]
Check out the tekton-pipeline agent that @ccojocar recently created. It allows a job to start pods after the first pod completes. Still need documentation

**Comment by stevekuznetsov** [comment]
@mukesh-panigrahi I will close this issue as it seems like you have gotten an answer to your question -- if you have more questions please feel free to re-open it and ask!

/close
