### ISSUE TITLE
gubernator per-PR display now a mess

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1223]
It looks like there's a column per run, vs compressing them at all. I assume this is because each job has changed to do its own merge or something. Can we maybe instead use the commit it's merging in (which would be more useful info anyways), rather than the ephemeral post-PR-merge commit?

![screen shot 2016-11-29 at 5 47 38 pm](https://cloud.githubusercontent.com/assets/4942464/20736538/1502e382-b65c-11e6-9e0e-f6ff6353c070.png)

**Comment by spxtr** [comment]
I think it's related to the change to always pass bootstrap the specific SHA of master and the PR. Not sure how it works, @rmmh probably knows.
