### ISSUE TITLE
Expose "Changed Files" Through Downward API to (Pre|Post)submit Jobs

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#12233]
**What would you like to be added**:
I would like to be able to see which files were changed in a PR in my post and presubmit jobs, if the job is using the `run_if_changed` option. I spoke with @stevekuznetsov and he would like this to be available through the downward api. :smile: 

**Why is this needed**:
This makes it _much_ easier for jobs to only act on changed assets, the first use case that comes to mind is package and deployment automation for helm charts. This feature would allow us to only package and deploy a changed chart and wouldn't require that we try to figure out which files changed via git / github api inside the container.

- https://github.com/kubernetes/test-infra/blob/master/prow/pod-utils/downwardapi/jobspec.go

**Comment by stevekuznetsov** [comment]
What format do you want them available in?

**Comment by midnightconman** [comment]
Ohh, that's an excellent question. I really only need to know which files have changed, not _how_ they have been patched, so I would be happy with a json array of changed files. I notice that this already exists: https://github.com/kubernetes/test-infra/blob/master/prow/github/types.go#L266 (PullRequestChange), which for my uses would be overkill.

I would love to have something in https://github.com/kubernetes/test-infra/blob/master/prow/pod-utils/downwardapi/jobspec.go , that included an array of changed files, something like this:

```
{
  "type": "postsubmit",
  "job": "job-name",
  "buildid": "0",
  "changedfiles": [
    "a.txt",
    "b.txt",
    "c/c.yaml",
    "d/d.yaml"
  ],
  "prowjobid": "uuid",
  "refs": {
    "org": "org-name",
    "repo": "repo-name",
    "base_ref": "base-ref",
    "base_sha": "base-sha"
  }
}
```

**Comment by adshmh** [comment]
I have started working on a PR for this. So far, adding the changed files to the `ProwJobSpec` seems like a "clean" solution to me, but it will involve changes in a few places as generated prow job specs need to be updated. This avoid introducing new dependencies in the `downwardapi` layer, as it simply copies the `Refs` struct from `ProwJobSpec`, perhaps with one or more new environment variables as well. Please advise whether this sounds reasonable or I should consider an alternative approach.

```
--- a/prow/apis/prowjobs/v1/types.go
+++ b/prow/apis/prowjobs/v1/types.go
@@ -494,6 +494,8 @@ type Pull struct {
        CommitLink string `json:"commit_link,omitempty"`
        // AuthorLink links to the author of the pull request.
        AuthorLink string `json:"author_link,omitempty"`
+       // ChangedFiles lists the files changed by the pull request
+       ChangedFiles []string `json:"changes"`
}

```

**Comment by stevekuznetsov** [comment]
Surfacing it at the `Pull` level through the `downwardapi` sounds like a good approach to me!

**Comment by Katharine** [comment]
Still need this for many reasons.

**Comment by Katharine** [comment]
/repo
/remove-lifecycle rotten

sigh.

**Comment by adshmh** [comment]
/remove-lifecycle stale
I have submitted #13731 and #12751 for this issue.
