### ISSUE TITLE
Simplify interface between bootstrap -> commands

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1225]
ref #250 and #1021 

We previously stored tons of complexity in jenkins. Our jobs required a huge number of commands, plugins, complicated and conditional steps. To resolve this we defined a simple interface that jenkins uses to run our jobs:
* `git clone http://github.com/kubernetes/test-infra`
* `jenkins/bootstrap.py --job=JOB --repo=k8s.io/kubernetes --pull=12345`

We then created the bootstrap.py to handle the following functionality:
* Checking out the repository in the correct state for the pull request
* Logging output produced by the job
* Exporting data about the run to gcs, such as the overall state, tests that ran, debugging artifacts, etc.

After we finish migrating upgrade jobs for https://github.com/kubernetes/test-infra/issues/1021 then all jobs will follow this simple pattern.

One unfortunate side effect of this migration is that we now have a few hundred bash scripts in test-infra/jobs/JOB.sh one for each job. These scripts are hermetic (they do not source other scripts) but this results in a lot of duplicate configuration.

In effect we have created very complicated JOB.sh scripts in exchange for simplifying our jenkins jobs. We will now simplify the interface between bootstrap.py --job=JOB and the commands it runs.

Instead of --job=JOB resulting in opening the test-infra/jobs/JOB.sh script, we will instead look for a test-infra/jobs/job.yaml file which follows this format:
```
process: kubekins-e2e
timeout: N  # minutes
args:
  owner: google  # 
  platform: gke  # 
  scenario: slow  # 
```

In other words each job will define two fields: a `process` string, a `timeout` float and a `args` mapping.  

The `process` string specifies how to enter the job. By default this will be the basename of an image to run on kubernetes, so `process: kubekins-e2e` will wind up doing something along the following lines: `kubectl run gcr.io/kubernetes-jenkins/kubekins-e2e:latest` however if `bootstrap.py --mode=local` is specified it would instead call `test-infra/images/kubekins-e2e/kubekins-e2e.sh`.

The `args` mapping specifies the arguments passed to the new container/process. So the `args: owner: google platform: gke scenario: slow` example above would result in `--owner=google --platform=gke --scenario=slow` passed to the kubekins-e2e container. In other words something along the following lines will happen: `kubectl run gcr.io/kubernetes-jenkins/kubekins-e2e:latest -- --owner=google --platform=gke --scenario=slow`

We will further define the expected args for the following job classes:
- build jobs (#1227)
- verify jobs (#1228)
- test-go jobs (#1229)
- e2e jobs (#1230)
- kubelet jobs (#1231)

We will also need to improve bootstrap:
- handle timeouts (#1226)

**Comment by ixdy** [comment]
@fejta might be worth creating a github project to track all of this, too.

**Comment by zmerlynn** [comment]
Can you make sure test owners / stakeholders are CC'd when the jobs are migrated, or work out a good plan for due diligence as the jobs are migrated? I didn't even see the `kops-build` job get migrated in #1182, and knowing it happened would've saved me some time when the `kops` jobs all started flaking. (maybe just a cc to @kubernetes/test-infra-maintainers?).

**Comment by krzyzacy** [comment]
Is it documented how to set up service account credential properly off a fresh checkout?

`git clone http://github.com/kubernetes/test-infra`
`jenkins/bootstrap.py --job=JOB --repo=k8s.io/kubernetes --pull=12345`

would give 

`IOError: [Errno Cannot find service account credentials] /Users/senlu/service-account.json: 'Create service account and then create key at https://console.developers.google.com/iam-admin/serviceaccounts/project'`

**Comment by krzyzacy** [comment]
And do we have kubectl ready on jenkins agents? Or we should bind it to kubekins image?

**Comment by krzyzacy** [comment]
The structure is done, #1230 will track rest of the jobs.
