### ISSUE TITLE
Add some notes correlating enabling plugins and GH token usage

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/test-infra#12266]
**What should be cleaned up or changed**:
Just a follow-up from @cjwagner's comment on #12247:
> Not strictly, but enabling the plugin without any blockades will still waste an API token because we have to check if the blocker label needs to be removed when no blockades are configured.
> 
> [test-infra/prow/plugins/blockade/blockade.go](https://github.com/kubernetes/test-infra/blob/894b7437551f33e6000d598b28f9ff865cd4a72a/prow/plugins/blockade/blockade.go#L140)
> 
> Line 140 in [894b743](/kubernetes/test-infra/commit/894b7437551f33e6000d598b28f9ff865cd4a72a)
> 
>  issueLabels, err := ghc.GetIssueLabels(org, repo, pre.Number) 
> 
> This is true for a number of plugins so typically we avoid enabling plugins in places they won't be used (e.g. enabling blockade globally for the `kubernetes` org instead of individual repos).
> FWIW the plugin can be enabled at the same time you configure the blockades so it doesn't require an additional PR if that is what you mean.
> 
> This won't be prohibitively expensive though so we can just go ahead and merge this. (After all the plugin will use even more tokens when blockades are configured for the repos and it actually has to do work.) This is more of general best practice to avoid wasting API tokens.
> Feel free to `/hold cancel`

Can we write a quick blurb that captures this info?

/area prow
/help

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

Alternatively, fix the base-case for plugins not to use tokens ;)
