### ISSUE TITLE
prow: review use of `ListStatus` endpoint

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#12265]
**What should be cleaned up or changed**:
The use of `github.ListStatuses` should be reviewed in each different place it's used, and a decision made on a case by case basis if it's better to keep `ListStatuses` or use `github.GetCombinedStatus` instead.

`ListStatuses` will list all status posted for a specific SHA. This will include all test failures, retests, and changed status contexts for a commit. This is useful if you want to see not only what the current status of a SHA is, but what the status context history is (e.g. checking how many times a test was retested at the same commit). This is a paginated call with 30 results per page.

`GetCombinedStatus` provides both an overall status for the PR (pending, failed, success), as well as the most current update of each context. If you don't care about the status context history for a commit, and instead only care what the status is *right now*, then this is a more efficient call. It returns a smaller result, matches what is in the UI, and is a paginated call with 100 results per page. If there are less than 100 unique contexts on commit, then this will be a single call/token.

**Provide any links for context**:
- List Statuses endpoint: https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref
- `ListStatuses` client function: https://github.com/kubernetes/test-infra/blob/91cb5e2cf715e0edcb9f223067e72b70b4b3a741/prow/github/client.go#L1282-L1300
- Combined Status endpoint: https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref
- `GetCombinedStatus` client function: https://github.com/kubernetes/test-infra/blob/91cb5e2cf715e0edcb9f223067e72b70b4b3a741/prow/github/client.go#L1470-L1489
- Example of moving a plugin from List -> Combined: https://github.com/kubernetes/test-infra/commit/fbaee4baab58c3c41f878678538ce8b472478301

**Comment by stevekuznetsov** [comment]
Depending on which direction things paginate, it's possible we get ghproxy to cache pages of the list call but since the combined status call will always be generated from the latest output it will not be cached unless nothing changed.

**Comment by cblecker** [comment]
Calls to ListStatuses are in reverse chronological order. So as soon as there is a new check, the content of the call will change, and the cache will be invalid.

**Comment by adshmh** [comment]
Perhaps this can be closed now that the PR has been merged.

**Comment by stevekuznetsov** [comment]
Yep! Thanks

/close
