### ISSUE TITLE
Migrate jobs to use RBE (and away from greenhouse)

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12282]
Right now some jobs use no remote caching, others use greenhouse.

Migrate all of this to use our RBE config.

`bazel test --config=remote --config=remote=fejta //...` (see our repo's [bazelrc](/.bazelrc)) will cause bazel to execute these builds remotely.

Work started: https://github.com/kubernetes/test-infra/pull/12072

/assign

test-infra jobs that should be on RBE

- [x] verify-gofmt.sh - https://github.com/kubernetes/test-infra/pull/12559
- [x] verify-labels.sh - https://github.com/kubernetes/test-infra/pull/12563
- [x] verify-govet.sh - https://github.com/kubernetes/test-infra/pull/12562
- [x] verify-github-spelling.sh - https://github.com/kubernetes/test-infra/pull/12561
- [x] verify-file-perms.sh - skip
- [x] verify-codegen.sh - https://github.com/kubernetes/test-infra/pull/12653

**Comment by spiffxp** [comment]
/area greenhouse
(the thing we're migrating away from)

maybe we need a bazel label
