### ISSUE TITLE
Use k8s-triage-robot in lieu of fejta-bot for kubernetes issue/pr commenter jobs

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#12296]
Background: @fejta-bot automatically marks issues as stale/rotten and closes them if they don't have any activity for certain number of days. It is an unprivileged user and is not a member of any of the Kubernetes GitHub orgs.

While enabling fejta-bot automation across all Kubernetes GitHub orgs, it was suggested to rename it to something "official": https://groups.google.com/d/topic/kubernetes-dev/9ps8uNXJ10k/discussion

This issue is to track discussing renaming fejta-bot -  what to rename it as or if we should use another account entirely - and making sure that this is rolled out across orgs.

/sig contributor-experience
/sig testing
/cc @cblecker @fejta @spiffxp

**Comment by fejta** [comment]
`serious-fejta-bot` with a grumpy cat partially converted into a robot for it's profile pic

**Comment by nikhita** [comment]
/assign

Assigning it to myself to try to move this along in contribex

**Comment by stevekuznetsov** [comment]
Any reason not to use one of the existing robots?

**Comment by spiffxp** [comment]
We need prow to react to the comments posted by these jobs, so it can't be @k8s-ci-robot.  We could maybe use @k8s-github-robot, but I would prefer using a bot that has no privileges.

**Comment by spiffxp** [comment]
You'll want to rename more than the account:
- https://testgrid.k8s.io/sig-testing-fejtabot
- https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/fejta-bot-periodics.yaml

Things @fejta-bot does:
- /lifecycle stale | /lifecycle rotten | /close
- /retest
- /check-cla
- comment that API review may be needed
- create github issues

Naming is hard, WDYT of either of these?
- @k8s-triage-robot
- @k8s-commenter-robot

**Comment by chris-short** [comment]
k8s-cuddle-bot
k8s-repo-sanity-bot
k8s-triage-bot

**Comment by justaugustus** [comment]
+1 to k8s-triage-[ro]bot!
Can probably dovetail with some of the stuff mentioned here: https://github.com/kubernetes/community/issues/3456

**Comment by dims** [comment]
+1 to k8s-triage-bot

**Comment by InAnimaTe** [comment]
fajita-bot

**Comment by nikhita** [comment]
+1 to k8s-triage-robot. Since we have `-robot` suffixes for our other bot accounts, using `-robot` feels consistent.

To be clear, this would be creating a new account instead of renaming the original one, right? I'm assuming @fejta would like to keep @fejta-bot around for testing, etc... @fejta can you confirm? :)

**Comment by spiffxp** [comment]
/area github-management

>To be clear, this would be creating a new account instead of renaming the original one, right? I'm assuming @fejta would like to keep @fejta-bot around for testing, etc... @fejta can you confirm? :)
 
I spoke offline with fejta last week and am confirming by proxy, as he's out this week

**Comment by spiffxp** [comment]
I've squatted on http://github.com/k8s-triage-robot, what needs to happen now is:
- an avatar
- making a token
- getting test-infra oncall to add the new secret to the cluster
- swapping the jobs to use the new token
- renaming the jobs / dashboards referenced above

note that fejta-bot is not a member of the org, doesn't have any privileges, doesn't need to have 2fa enabled; if we want that to change, I'd rather consider that out of scope here, and ask that those so motivated create a followup issue to

**Comment by nikhita** [comment]
> swapping the jobs to use the new token
renaming the jobs / dashboards referenced above

Created https://github.com/kubernetes/test-infra/pull/13683 to get the ball rolling

> an avatar

Do we know who created the avatar for @k8s-github-robot? It's pretty dope!

**Comment by spiffxp** [comment]
>Do we know who created the avatar for @k8s-github-robot? It's pretty dope!

👋 😄

**Comment by dankohn** [comment]
Some avatar ideas from @alexcontini

![image](https://user-images.githubusercontent.com/3083270/62311394-b8618a80-b459-11e9-8b9e-2511824cd5e0.png)

**Comment by nikhita** [comment]
/reopen

reverted in https://github.com/kubernetes/test-infra/pull/14548

**Comment by chris-short** [comment]
@spiffxp @nikhita Is there anything I can do to help push this forward?

**Comment by BenTheElder** [comment]
I don't have a strong opinion on this but the errors in https://github.com/kubernetes/test-infra/pull/14548#issuecomment-755628839 seem dubious. This issue should be pretty straightforward if someone wants to do it, otherwise we should probably close it out.

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/milestone v1.21
Agree this should be straightforward

**Comment by nikhita** [comment]
Closing due to age, we can reopen when we have bandwidth to revisit this.

**Comment by spiffxp** [comment]
/reopen
/assign
I'm willing to tackle this before v1.22 is released, or before v1.23 starts

**Comment by spiffxp** [comment]
Added the k8s-triage-robot token to k8s-infra-prow-build-trusted https://github.com/kubernetes/k8s.io/pull/2389

Next step is to try a sample job to make sure it works, then we can migrate the fejta-bot jobs

**Comment by spiffxp** [comment]
I originally posted more comments in the wrong issue (https://github.com/kubernetes/test-infra/issues/11402) so I'm copy-pasting them here

**Comment by spiffxp** [comment]
The test job is failing (whoops I must have missed the tab name): https://testgrid.k8s.io/sig-contribex-k8s-triage-robot#api-review-help

It seems like bad credentials? https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8s-triage-robot-testcomment/1418328613631037440

So I logged into k8s-triage-robot, and sure enough, no personal access tokens at all.

Created a new one, updated the secret, waiting for the next job run.

_Originally posted by @spiffxp in https://github.com/kubernetes/test-infra/issues/11402#issuecomment-885266205_

**Comment by spiffxp** [comment]
```
Failed run: encoutered 2 failures: [Failed to apply comment to kubernetes/test-infra#11402: the GitHub API request returns a 403 error: {"message":"Must have admin rights to Repository.","documentation_url":"https://docs.github.com/rest/reference/issues#create-an-issue-comment"} Failed to apply comment to kubernetes/org#2465: the GitHub API request returns a 403 error: {"message":"Must have admin rights to Repository.","documentation_url":"https://docs.github.com/rest/reference/issues#create-an-issue-comment"}]
```

_Originally posted by @spiffxp in https://github.com/kubernetes/test-infra/issues/11402#issuecomment-885274636_

**Comment by spiffxp** [comment]
Fixed the token, it needed `scope:public_repo`

The query also didn't include `repo:kubernetes/test-infra`, so it ended up commenting here: https://github.com/kubernetes/org/issues/2465#issuecomment-885372510

_Originally posted by @spiffxp in https://github.com/kubernetes/test-infra/issues/11402#issuecomment-885373671_

**Comment by spiffxp** [comment]
Orrrr apparently github's search returned one issue the first time, and two the second.  But that's it.  Should see no more spam at this point.

Opened https://github.com/kubernetes/test-infra/pull/22997 to switch all the fejta-bot jobs over to k8s-triage-robot

_Originally posted by @spiffxp in https://github.com/kubernetes/test-infra/issues/11402#issuecomment-885376865_

**Comment by spiffxp** [comment]
https://github.com/issues?q=involves%3Ak8s-triage-robot+archived%3Afalse+sort%3Aupdated-desc+ - so the bot is definitely commenting now

There are still some "failing" jobs on the dashboard
- https://testgrid.k8s.io/sig-contribex-k8s-triage-robot#stale - this is due to attempting to comment on a locked issue, so exclude those by default: https://github.com/kubernetes/test-infra/pull/23029
- https://testgrid.k8s.io/sig-contribex-k8s-triage-robot#secping - hasn't run yet, so I've triggered a re-run
- https://testgrid.k8s.io/sig-contribex-k8s-triage-robot#issue-creator - ditto

**Comment by spiffxp** [comment]
Opened a PR to bump jobs to use the latest commenter:
- https://github.com/kubernetes/test-infra/pull/23032

I think because I tried re-running the other two jobs (since I can't re-trigger them), they tried and failed against the wrong cluster again, and their interval might have reset.  In other words, may need to wait to sometime after 3pm PT to see if they go back to green

**Comment by spiffxp** [comment]
/milestone v.122
This has been completed
