### ISSUE TITLE
Migrate e2e jobs to yaml

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1230]
ref #1225

This interacts with `kubernetes/hack/e2e.go` `test-infra/jenkins/e2e-image/e2e-runner.sh` and `test-infra/jenkins/dockerized-e2e-runner.sh`

These jobs will expect three arguments:
* `--owner=O  # things owned by the executor such as gcp project, buckets, etc`
* `--platform=P  # things specific to the platform being tested, such as aws/gce, zone, etc`
* `--sceanrio=S  # things specific to the scenario such as ginkgo flags, etc`

`O` refers to a `O.env` file relative to `$HOME`
`P` refers to the prefix of a `P.env` file relative to `test-infra/platforms`
`S` refers to the prefix of a `S.env` file relative to `test-infra/scenarios`

**Comment by krzyzacy** [comment]
Just saw this.

I would assume `--owner=O` O being the username,
And `[job].yaml` point to a matching `[job].env` from somewhere like `test-infra/jobenv` automatically.

**Comment by krzyzacy** [comment]
only pr jobs left
