### ISSUE TITLE
Prow issue: Feature branches: Superpowers shouldn't be necessary to merge master into a feature branch

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#12303]
E.g., see https://github.com/kubernetes/kubernetes/pull/76902--even being in top level OWNERS isn't enough.

**Comment by stevekuznetsov** [comment]
Looks like the conformance test data directory has disallowed top level OWNERS from having powers there:

https://github.com/kubernetes/kubernetes/blob/c2254cf19a27adacbe61fd7505ee1a49d8292cb3/test/conformance/testdata/OWNERS#L5

Seems like you need to change that setting if you'd like top level OWNERS to approve there. Or, maybe that option should apply to all but the top-level OWNERS?

/cc @cjwagner @fejta 
/area prow
/kind question

**Comment by cjwagner** [comment]
> Or, maybe that option should apply to all but the top-level OWNERS?

I think the most common use case for `no_parent_owners` is to specifically avoid including the top level OWNERS so I don't think we should change the functionality.

If top level OWNERS should be able to approve that directory it should not have `no_parent_owners` set or the same users should be included in the testdata OWNERS files (perhaps via an OWNERS alias).

**Comment by fejta** [comment]
Not clear why a simple workaround is insufficient for a feature branch (don't you already disable branch protection?):

1) Click the merge button
2) Disable branch protection, rebase the feature branch and force push
3) Add yourself as an OWNER of that file in your feature branch
4) Get approval from Brian/Clayton

Not clear that the already over-complicated approval plugin should bear the additional burden of special casing feature branches given that:
* there seem to be satisfactory alternatives,
* feature branches are rarely used (there is exactly one active feature branch) and
* unique to (a small subset of) the kubernetes community.

**Comment by lavalamp** [comment]
> feature branches are rarely used

Keeping them hard to use will ensure that it stays that way :)

The issue is that the changes have *already been approved by the right people*, we are just merging them into another branch. It isn't a good use of those people's scarce time to approve them again. I could definitely add a bunch of people to a bunch of OWNERS files on the branch, but that makes it harder to merge back into master.

I actually don't think this needs to be different between feature and release branches, I don't think it needs a special case.
