### ISSUE TITLE
Deprecate old reviewer functionality in blunderbuss

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#12346]
Follow up to https://github.com/kubernetes/test-infra/pull/12345

cc: @stevekuznetsov @cjwagner

**Comment by cblecker** [comment]
/lifecycle stale
/help

This is now actionable!

**Comment by cblecker** [comment]
I mean
/remove-lifecycle stale

**Comment by cblecker** [comment]
/good-first-issue

This should be an easy one for someone to pick up. The old `file_weight_count` option can now be removed. 

https://github.com/kubernetes/test-infra/pull/12345 and https://github.com/kubernetes/test-infra/pull/6647 should have background on this.

**Comment by sladyn98** [comment]
I would like to take up this issue, any points on how to begin ?

**Comment by cblecker** [comment]
Take a look at the https://github.com/kubernetes/test-infra/pull/12345 PR that was referenced at the top. Now that the deprecation period has passed, we can remove the warning bits as well as the option. We should also add a note to ANNOUNCEMENTS.md saying it's now done.

**Comment by sladyn98** [comment]
So effectively we need to rid of the check, since its now invalid ? 
```
if b.FileWeightCount != nil && *b.FileWeightCount < 1 {
		return fmt.Errorf("invalid file_weight_count: %v (needs to be positive)", *b.FileWeightCount)
	}
```

**Comment by cblecker** [comment]
Not quite. `FileWeightCount` should be removed completely.

/remove-lifecycle stale

**Comment by michaelmdresser** [comment]
This appears to be addressed in https://github.com/kubernetes/test-infra/pull/17345

**Comment by michaelmdresser** [comment]
@fejta Looks like this be closed?

**Comment by cblecker** [comment]
It does. Thanks for checking it out @michaelmdresser !

/close
