### ISSUE TITLE
Request to bump the kubetest image

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/test-infra#12340]
There is an open issue #10958 to build and bump the images automatically, but unfortunately this has not been implemented yet.

Could we build and push a new image to pick up change #12234? Thanks.

/cc the current test-infra-oncall @fejta

**Comment by yujuhong** [comment]
Ping! Is there a fixed release schedule for the new kubetest image?
/cc @krzyzacy

**Comment by krzyzacy** [comment]
I think this is automated now? cc @Katharine

**Comment by Katharine** [comment]
They are pushed automatically, but the config references are not updated (I wrote a tool to update the references, but currently it is only run manually).

You can use image-bumper to update the references and submit a PR with the result. It doesn't require any Googler involvement.

**Comment by yujuhong** [comment]
PR: #12398

**Comment by yujuhong** [comment]
PR merged. Closing.
