### ISSUE TITLE
Status Reconciler breaks initial Prow deployment

### ISSUE THREAD

**Issue by rofuentes** [kubernetes/test-infra#12354]
**What happened**:
Initial prow deployment fails after addition of statusreconciler. Cluster is managed by GKE.

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.9-gke.5", GitCommit:"ec4023d951587cf6a4f95adf84e716dd11c3a6db", GitTreeState:"clean", BuildDate:"2019-04-04T02:34:14Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

** NOTE ** Also tested on v1.12.7 with same results

**What you expected to happen**:
Initial prow deployment should complete.

**How to reproduce it (as minimally and precisely as possible)**:
Example of failure:
$ git checkout 3ed05bc18903918035936dea31e82be952687518
Previous HEAD position was 9acd155b9 Bump prow from v20190419-321e4866f to v20190423-006066e40  
$ kubectl apply -f prow/cluster/starter.yaml
<...>
error: error validating "prow/cluster/starter.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector"
in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

Example of success:
$ git checkout 9acd155b966603a19ff55b9fb7816e857397b083
Previous HEAD position was 3ed05bc18 Merge pull request #12258 from stevekuznetsov/skuznets/deploy-status-reconciler
HEAD is now at 9acd155b9 Bump prow from v20190419-321e4866f to v20190423-006066e40
$ kubectl apply -f prow/cluster/starter.yaml

$ kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
deck-76dc8fb459-ctrns         0/1     Running   0          19s
deck-76dc8fb459-n7ffw         1/1     Running   0          19s
hook-796c5599c4-7wwjn         1/1     Running   0          19s
hook-796c5599c4-ghxgs         1/1     Running   0          19s
horologium-7489b9f646-xcvbx   1/1     Running   0          19s
plank-7bd6d6f945-gz52p        1/1     Running   0          19s
sinker-b7488ffb9-6lf2m        1/1     Running   0          19s
tide-6ddccd6b8b-zgp7k         1/1     Running   0          19s

Please see more output here:
https://gist.github.com/rofuentes/c686079012a87297c4eaf5a029bebbcd

**Comment by arturo-c** [comment]
Fixed in https://github.com/kubernetes/test-infra/issues/12354

**Comment by stevekuznetsov** [comment]
FWIW the `apps/v1` works for me on a k8s `kubernetes v1.11.0+d4cacc0` cluster
