### ISSUE TITLE
verify-owners: plugin should honor blacklists, exclude vendored directories by default

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#12407]
xref: https://github.com/kubernetes/test-infra/pull/12402#issuecomment-487722467

The feature added to check organization membership for users listed in OWNERS files is extremely valuable but suffers from two small bugs that make it difficult to use for projects that vendor other projects using OWNERS:

1. the `verify-owners` code does not traverse using the directory blacklist given to other plugins interacting with the OWNERS files like `approve`
2. the `verify-owners` code should be configured by default to ignore directories of vendored code

/cc @nikhita @cjwagner @fejta @cblecker

**Comment by cblecker** [comment]
One other thing that should probably be fixed in the next iteration.. we shouldn't @ mention folks who aren't in the org. If it's a typo or the person is unaffiliated, we don't want to drag them into mentions.

**Comment by nikhita** [comment]
I can work on fixing it...but I probably won't have time today.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/test-infra/pull/12460

**Comment by nikhita** [comment]
Another thing to fix with the next iteration: https://github.com/kubernetes/test-infra/pull/12460#issuecomment-493312129
