### ISSUE TITLE
Owners should be able to manually trigger periodic/post jobs

### ISSUE THREAD

**Issue by akutz** [kubernetes/test-infra#12426]
**What would you like to be added**:
Per this [Slack conversation](https://kubernetes.slack.com/archives/C09QZ4DQB/p1553307341750800?thread_ts=1553298938.731900&cid=C09QZ4DQB) between myself and @stevekuznetsov, it would be useful for Owners to manually trigger periodic/post jobs. One suggested solution is a self-service web portal that could be used to kick off the jobs.

**Why is this needed**:
Currently it is only possible to trigger pre-submit jobs manually via comments in GH issues. Combined with `always_run: false` and `skip_report: true`, it's possible to create pre-submit jobs and test them prior to promoting the jobs into production.

It is *not* currently possible to manually trigger periodic/post jobs, which makes it difficult to test the jobs in a staged manner. I learned the hard way that running images locally does not reflect the same environment as a Prow cluster. Presets, volume mounts, etc. can lead to unexpected failures.

**Comment by stevekuznetsov** [comment]
/area prow
This relates to the self-service epic, as well

**Comment by dims** [comment]
@stevekuznetsov how do we prevent people from kicking off the 5k job? :)

**Comment by stevekuznetsov** [comment]
My strawman implementation of this would be a self service web page with GitHub OAuth to log in -- so, if they can post `/test foo` to trigger a presubmit they can trigger the presubmit using the page. Kicking off postsubmit jobs would naturally fall to users who have at least write access to the repo. Periodics, I guess it would be admin, or we can check write access for the first `extra_refs`. But we'd need to hash this out and maybe have a couple configurable options.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

This will be done with the work from @mirandachrist  in #13321 

/assign @mirandachrist 
/milestone v1.16
