### ISSUE TITLE
deck: job overview infographic has timing wrong

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#12431]
The longest failure was 16min but the failure block is above 20min.

![Screenshot from 2019-04-30 17-00-56](https://user-images.githubusercontent.com/7328370/57000701-a37b0f80-6b69-11e9-9900-23636df578c4.png)

/cc @Katharine @smarterclayton 
/area prow/deck

**Comment by smarterclayton** [comment]
I think I capped vertical y axis increments at 5 or 10m, but it may be normalizing wrong.

/assign @smarterclayton

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
ping @smarterclayton
