### ISSUE TITLE
Testgrid shows tests as still running after weeks of having ended

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/test-infra#12449]
**What happened**:
Some of the https://testgrid.k8s.io/sig-release-master-upgrade jobs , ref https://github.com/kubernetes/kubernetes/issues/77232 , show runs from as far back as two weeks ago as still running.
However, after further inspection, these runs have all finished but their results are not properly being populated by testgrid.

**What you expected to happen**:
Testgrid should be able to detect and populate results regardless of how the run ended.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
See https://github.com/kubernetes/kubernetes/issues/77232

**Anything else we need to know?**:

/area testgrid
/milestone v1.15

**Comment by michelle192837** [comment]
Surprised we haven't encountered this before, honestly!

TestGrid has a field that isn't exposed atm for how long to look back for tests. I'll add support for it and add it to config.proto.

**Comment by michelle192837** [comment]
Hi, thanks for your patience! https://github.com/kubernetes/test-infra/tree/master/testgrid#long-running-tests has instructions on the field to add to get results better for long-running tests. (It should apply going forward; if you need to regenerate state completely, bump `days_of_results` in your test_group config by 1 (you can bump it back down later)).

**Comment by michelle192837** [comment]
/close

This should be fixed on TestGrid side, but please ping if you're still having issues with this. ^^
