### ISSUE TITLE
Implement triggering on source changes in prow

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#1246]
So that we can migrate https://github.com/krzyzacy/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-update-jenkins-jobs.yaml

And testgrid config upload job. Properly.

**Comment by fejta** [comment]
@krzyzacy for now you can migrate the job to here: https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci-commit.yaml (or use a similar pattern in a new maintenance-commit.yaml file)

@spxtr please triage/delegate/etc appropriately.

**Comment by spxtr** [comment]
This is done. You can now add jobs to postsubmit.yaml.
