### ISSUE TITLE
Project plugin incorrectly handles command with column name

### ISSUE THREAD

**Issue by taragu** [kubernetes/test-infra#12481]
**What happened**: Project plugin is not responding to commands with project name and column name as arguments. Example: https://github.com/kubeflow/community/issues/250

**What you expected to happen**: Project plugin should successfully add issue to project and column

/assign @taragu 
/sig testing

**Comment by mohammedzee1000** [comment]
I can confirm that this is a problem. It appears the plugin works only with project names without spaces, hyphens(`-`) etc.
https://github.com/openshift/odo/issues/1663

**Comment by mohammedzee1000** [comment]
@taragu

**Comment by mohammedzee1000** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/project/project.go#L39 that is regex that separates the comment out. While this should obviously fail if spaces are used in board name The strange thing this correctly extracts hyphens so wonder why hyphens don't get recognized:

https://regex101.com (golang matcher selected): 
### Match 1
Full match	0-18	/project ramu zora
Group 1.	9-13	ramu
Group 2.	14-18	zora
### Match 2
Full match	19-35	/project v1.1 ff
Group 1.	28-32	v1.1
Group 2.	33-35	ff
### Match 3
Full match	36-57	/project abc-xyz farz
Group 1.	45-52	abc-xyz
Group 2.	53-57	farz

**Comment by mohammedzee1000** [comment]
I think something like this could work for columns will multiple spaces.

Regex `(?m)^/project\s+('.*?'|".*?"|\S+)(?:\s+(.+?)\s*)?$`

### Matching examples:

```
Full match | 1-14 | /project ramu
Group 1. | 10-14 | ramu
Group 2. | 15-15
```

```
Full match | 1-20 | /project "ramu dsd"
Group 1. | 10-20 | "ramu dsd"
Group 2. | 21-21
```

```

Full match | 1-32 | /project "ramu dsd" forza zora
Group 1. | 10-20 | "ramu dsd"
Group 2. | 21-31 | forza zora


```

### Drawbacks
1. Project command will have to be the last line in a comment. Anything following it could possibly mess it up (further testing needed).
1. Following the above issue, a curious case If quotes are used but you dont want to give the third parameter is that giving even a single space makes it ignore 2nd word in quotes

Ex:

Full match | 1-22 | /project "ramu dsd"`<space>`
Group 1. | 10-15 | "ramu
Group 2. | 16-20 | dsd"

**Comment by taragu** [comment]
@mohammedzee1000 How about something like `/project project="ramu dsd" column="forza zora"`? this seems to be the safest but verbose

**Comment by mohammedzee1000** [comment]
I guess that could work, but then how would you clear?

**Comment by stevekuznetsov** [comment]
@cblecker @nikhita PTAL

**Comment by taragu** [comment]
@mohammedzee1000 for project clear, we can do `/project clear project="ramu dsd"`

**Comment by taragu** [comment]
FYI @brahmaroutu
