### ISSUE TITLE
prow: need a new plugin for editing Issue titles

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#12489]
Context:
https://groups.google.com/d/msg/kubernetes-sig-architecture/LYphMQLhu4w/oD-ErQjlBAAJ

Use Case: we need to allow all org members the ability to triage/review issues better. One aspect of triaging is fixing the Title of an Issue is to ensure that it is easy for folks to find the issue easily when browsing a list of issues so that the issue gets sufficient attention.

**Comment by dims** [comment]
cc @hemani19

**Comment by nikhita** [comment]
I think we should restrict editing titles to only repo collaborators (or to be precise, users considered trusted by the `trigger` plugin`) to avoid abuse of this command.

**Comment by nikhita** [comment]
cc @cblecker

**Comment by nikhita** [comment]
@hemani19 are you working on this?

**Comment by nikhita** [comment]
PR is here: https://github.com/kubernetes/test-infra/pull/12945

**Comment by nikhita** [comment]
Done in https://github.com/kubernetes/test-infra/pull/13088
