### ISSUE TITLE
Make e2e.go aware of timeout and handle correctly

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1250]
More complete fix for https://github.com/kubernetes/kubernetes/issues/37553

**Comment by fejta** [comment]
Zach's fix didn't work yesterday so we need to prioritize this one.

**Comment by zmerlynn** [comment]
It's easy enough to do another stop-gap fix for the previous issue, and less fickle for now. I put the script in the last commit if someone wants to take a crack and adding the `chmod` (but I'm not even supposed to be online right now).

**Comment by ixdy** [comment]
it occurs to me that #1270 might not be as urgent - @zmerlynn's fix probably didn't work because `cluster/log-dump.sh` was broken. With https://github.com/kubernetes/kubernetes/pull/37857 merged, Zach's fix might work.

**Comment by ixdy** [comment]
nope, I was wrong again. #1247 doesn't work because the kubernetes tarball is extracted inside the docker container, and so doesn't exist after timeout.

**Comment by fejta** [comment]
We now have the following timeout logic:
* `e2e.go` will `SIGTERM` the current running process after `KUBEKINS_TIMEOUT`
* `e2e.go` will `SIGKILL` all subprocesses 15m after `KUBEKINS_TIMEOUT`
* `dockerized-e2e-runner.sh` will delete the container after `DOCKER_TIMEOUT` which is at least 20m more than `KUBEKINS_TIMEOUT`
