### ISSUE TITLE
triage: avg job duration has grown from 20m to 35m in the past 2 weeks

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#12508]
https://testgrid.k8s.io/sig-testing-misc#triage&graph-metrics=test-duration-minutes&width=5

It's scheduled to run every 20m: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-periodics.yaml#L44

/area triage
/sig testing

**Comment by spiffxp** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-test-infra-triage/1120703225054367744/build-log.txt
```
I0423 15:03:04.191] Finished locally clustering 3100 unique tests (197948 failures) in 3m24s
I0423 15:12:30.789] Finished clustering 3100 unique tests (197948 failures) into 4659 clusters in 9m19s
I0423 15:14:38.549] Finished rendering results in 2m0s
```

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-test-infra-triage/1125766601568686084/build-log.txt
```
I0507 14:28:45.051] Finished locally clustering 3830 unique tests (472853 failures) in 8m25s
I0507 14:49:16.747] Finished clustering 3830 unique tests (470790 failures) into 6346 clusters in 20m14s
I0507 14:52:45.212] Finished rendering results in 3m10s
```

It's not immediately clear to me where the increased volume is coming from, and whether we should be telling someone to stop

**Comment by spiffxp** [comment]
I noticed this while saying I was going to keep an eye on whether https://github.com/kubernetes/test-infra/pull/12446 would change anything

**Comment by spiffxp** [comment]
/help
Would someone like to dig into test results and help us understand where the increased volume is coming from?

**Comment by tedyu** [comment]
```
470790 failures
```
Test failures more than doubled.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/12446 broke things, https://github.com/kubernetes/test-infra/pull/12535 got us back up and running

Now triage is taking ~40m, so it seems like the indirection added by `six` isn't really helping

IMO the question is whether this is a reasonable amount of data, or if we should be optimizing triage to handle this new volume of data

**Comment by spiffxp** [comment]
Aaaand it's on its way up to 60 minutes

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-test-infra-triage/1136770371005976577/build-log.txt
```
I0606 23:17:31.410] Finished locally clustering 4170 unique tests (380911 failures) in 10m36s
I0606 23:53:51.453] Finished clustering 4170 unique tests (378937 failures) into 6275 clusters in 36m7s
I0606 23:57:24.446] Finished rendering results in 3m19s
```

The total number of failures is slightly down from before, but the processing time is climbing.

I have two suggestions if anyone is willing:
- reduce the amount of text we're clustering, and see if we get comparable results in less time
- rewrite this in go

Or it could be something else entirely, I don't know

**Comment by spiffxp** [comment]
And now, for Reasons™, it appears as though it's trended back down to ~25m
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-test-infra-triage/1140739152367587328/build-log.txt
```
I0617 22:01:01.347] Finished locally clustering 3564 unique tests (279545 failures) in 5m35s
I0617 22:16:04.737] Finished clustering 3564 unique tests (268677 failures) into 5006 clusters in 14m51s
I0617 22:18:36.437] Finished rendering results in 2m22s
```

It's certainly correlated to the amount of failures that are being clustered.  It would be nice to know where the additional volume was coming from and where it's gone.  I currently have low confidence that the problem will just stay solved by itself.

It's unclear whether the types or kinds of failures specifically are pathological for clustering in some way.

I think both of the the suggestions above still stand, and am open to other suggestions for root-causing or optimizing this.
