### ISSUE TITLE
Support GitHub rate limiting experiments

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#12510]
ref: https://gist.github.com/rlinehan/9ace6c2558fce34b206feaf09c4cff32
ref: [kubernetes-sig-testing@ thread](https://groups.google.com/forum/#!topic/kubernetes-sig-testing/rkBNGv58ypc)

/assign @guineveresaenger 
cc @rlinehan @xuorig
as folks on the GitHub side

/assign @cjwagner @fejta
as folks on the Kubernetes side

We want to move forward with this so I'm opening this to track that it was done on our end. 
 What if anything do we need to do to support this?

As far as apps or accounts that we control, @k8s-ci-robot is really the only thing I can think of needing to flag in here.

We have other apps installed in our orgs (e.g. FOSSA, Octobox, Travis CI, etc), but it's unclear to me whether they should be part of this experiment

/sig testing
/priority important-soon

**Comment by spiffxp** [comment]
We would also like the @k8s-github-robot account to be flagged for this experiment

**Comment by stevekuznetsov** [comment]
Fine to flag @openshift-ci-robot and @openshift-merge-robot if you'd like

**Comment by rlinehan** [comment]
Thank you all for your willingness to help us out! As an update, we've just enabled this experiment for @k8s-ci-robot, @k8s-github-robot, @openshift-ci-robot, and @openshift-merge-robot. As mentioned before, we don't expect you to see anything different as a result of this experiment, but please reach out if you do see anything you're concerned about!

**Comment by nikhita** [comment]
Looks like this issue can be closed?
