### ISSUE TITLE
CAPA is deleting non-CAPA AWS resources

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#12527]
From CloudTrail, I can see that the capa-user-02 is deleting resources from running kops tests.

I believe that the capa users were all set up in the same account, but I think boskos is assuming that they are in isolated accounts.  As far as I can tell, they are merely different logins to the same account.

cc @idvoretskyi I believe you set up these capa users?  Did you set them up in separate AWS accounts, or did you set up separate logins in the same AWS account?

If they were created in the same account, I suggest we disable all the capa-users asap, and recreate them in separate accounts.

**Comment by idvoretskyi** [comment]
> did you set up separate logins in the same AWS account?

@justaugustus this, as this was requested initially.

**Comment by justinsb** [comment]
Cool - thanks for confirming @idvoretskyi ... the terminology is really difficult as I discovered trying to summarize this.  I've started calling them logins and accounts, and we're going to want logins on 10 different accounts (one login per account).  I sent you an email with the request!

**Comment by justaugustus** [comment]
@idvoretskyi -- I'm pretty sure that ping was for @justinsb, but just wanted to confirm.
(I don't have anything to do w.r.t. managing any of the capa infra at the moment.)

**Comment by detiber** [comment]
Now that I'm not trying to multi-task with meetings and I've had lunch, I think that "IAM user/credentials" might be the proper terminology.

**Comment by idvoretskyi** [comment]
@justaugustus lol, sorry, GitHub autocompletion ¯\_(ツ)_/¯

**Comment by chuckha** [comment]
It looks like the resolution to this is to get the aws users in their own accounts, is that right?

Sounds like something @idvoretskyi might be able to do?

cc @liztio

**Comment by idvoretskyi** [comment]
@liztio @chuckha If this is not urgent, I'm happy to help after KubeCon.

Also, we have already started the discussion with @justinsb about handling this in an efficient way.

**Comment by liztio** [comment]
Yeah, I think we can wait. I'm interested to hear what @justinsb's alternate solution is, too!

**Comment by idvoretskyi** [comment]
@liztio can you please email me (ihor at cncf.io) your detailed request of what specifically do you need (preferably using the AWS glossary - https://docs.aws.amazon.com/general/latest/gr/glos-chap.html, so we could avoid any terminology misunderstanding). I'm happy to discuss this via the email.

**Comment by justinsb** [comment]
I have now created these accounts, I think I need somebody to register them in boskos

**Comment by detiber** [comment]
@liztio @rdodev do either of you remember who did this originally?

**Comment by detiber** [comment]
Had a [discussion in #sig-testing regarding this](https://kubernetes.slack.com/archives/C09QZ4DQB/p1564165911066400) and `test-infra-oncall` will be able to assist today after lunch.

**Comment by detiber** [comment]
After discussing with @justinsb and hearing back from `test-infra-oncall`, I believe this has now been resolved.

Thank you to all involved in helping get this sorted out!
/close
