### ISSUE TITLE
Unable to get build output in Charts PR

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes/test-infra#1253]
After https://github.com/kubernetes/test-infra/pull/1251 we are no longer able to see build results and frankly I'm not even sure that they are being kicked off at all. 

Example:
https://github.com/kubernetes/charts/pull/223

Link from PR:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/223/pull-charts-e2e/269/

cc @spxtr

**Comment by viglesiasce** [comment]
From [here](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-charts-e2e/) it shows that build 269 is the last, but PR is now referencing 270+.

**Comment by krzyzacy** [comment]
hummm... latest is 271 but failed without upload logs seems

**Comment by spxtr** [comment]
`./test-infra/jenkins/bootstrap.py --job=pull-charts-e2e --repo=k8s.io/charts --pull=b5aa3fd38d257045a7d21cec334543b474a7952c:14bee1e456c1789d1ebdfc2dc7e3ae2b9ea930ce,223:a5e1b12e9605de227f330a40a3dedcd5f1e5c6c2 --root=/var/lib/jenkins/workspace/pull-charts-e2e/go/src`

**Comment by spxtr** [comment]
Whoops. Sorry about that... again.

Thanks for opening the issue, should be fixed now.

**Comment by viglesiasce** [comment]
Thanks @spxtr!!!
