### ISSUE TITLE
I am not able to view test results in testgrid

### ISSUE THREAD

**Issue by IamPrvn** [kubernetes/test-infra#12548]
I am populating this bucket with conformance test results:
https://console.cloud.google.com/storage/browser/k8s-conformance-oracle-cloud/cloud-provider-oci-oke/e2e-conformance-stable-1.12/

I believe they should appear here :
https://testgrid.k8s.io/conformance-oracle-cloud-infrastructure#OKE,%20v1.12%20(release)&width=90

First time I pushed/uploaded the results appeared but for the subsequent push/upload I am not able to see new test result columns. Can someone have a look? The tests artifacts are not stale.

**Comment by michelle192837** [comment]
Trying to see the results in Prow ('About' -> 'See these results in Prow') results in an error (https://prow.k8s.io/job-history/k8s-conformance-oracle-cloud/cloud-provider-oci-oke/e2e-conformance-stable-1.12). Can you double-check the format of your uploaded results?

**Comment by michelle192837** [comment]
Ah, nvm; these are manually uploaded so they're not from Prow, right?

**Comment by krzyzacy** [comment]
https://prow.k8s.io/view/gcs/k8s-conformance-oracle-cloud/cloud-provider-oci-oke/e2e-conformance-stable-1.12 works ^^

**Comment by michelle192837** [comment]
Thanks Sen!

I think the issue is that these were started May 5th, 11:53 PM PDT, but uploaded May 7th, 3:03 AM, which is more than 24 hours later (and therefore ignored by result processing). Easiest way to fix this is to bump `days_of_results` in your test_group by 1 to force TestGrid to collect things from scratch (feel free to bump it down later).

**Comment by IamPrvn** [comment]
Thanks @michelle192837 .

**Comment by IamPrvn** [comment]
@michelle192837 But the default test group has a value of 14 for days_of _results..https://github.com/kubernetes/test-infra/blob/master/testgrid/config.yaml#L14.
Isn't this default configuration supposed to be used for my test group config (for fields that I have not overwritten) ?

**Comment by IamPrvn** [comment]
@michelle192837 @spiffxp As suggested I tried to run the tests and push the results within 24 hours ( though I still feel that's not the root cause as the default `days_of_results` value should be honoured if not overwritten). I am still facing the same issue.
The below tests  were run/uploaded on 14th May '19.
https://console.cloud.google.com/storage/browser/k8s-conformance-oracle-cloud/cloud-provider-oci-oke/e2e-conformance-stable-1.12/1557807905/
Still I am unable to get the results appear in testgrid.
https://testgrid.k8s.io/conformance-oracle-cloud-infrastructure#OKE,%20v1.12%20(release)

**Comment by IamPrvn** [comment]
nvm, It took some time to start reflecting the results in testgrid. Closing the issue.
