### ISSUE TITLE
Update cat plugin to use the v1 thecatapi

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#12573]
https://docs.thecatapi.com/ has new functionality and a real json api that allows better searching by breed and category.

Here's our current usage: https://github.com/kubernetes/test-infra/tree/master/prow/plugins/cat

Goal would be to update it to use v1 rather than https://api.thecatapi.com/api/images/get

/help
/good-first-issue

**Comment by nikhita** [comment]
Somewhat related: https://github.com/kubernetes/test-infra/issues/10845, in case anyone wants to take it up.

**Comment by scottilee** [comment]
It looks like the code has already been updated to use the v1 API. Can someone close this?

**Comment by matthyx** [comment]
indeed
/close
