### ISSUE TITLE
Jenkins Status checks panel does not reflect actual job status

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#1258]
Please see https://github.com/kubernetes/kubernetes/pull/35272:

Jenkins GCE Node e2e and Jenkins unit/integration are marked as "Build Started" but the jobs are already finished.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/35272/pull-kubernetes-node-e2e/7207/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/35272/pull-kubernetes-unit/7268/

Quite sure i've seen this before.

**Comment by dims** [comment]
cc @rmmh @fejta @kubernetes/test-infra-maintainers

**Comment by spxtr** [comment]
I think this was my bad. I recreated the prow cluster yesterday at 12:30 or so, after waiting a little over a half-hour for old jobs to complete. I didn't realize how long our pre-submits take nowadays, so I probably cut off some.

Please reopen if you see it again.
