### ISSUE TITLE
Add SIG-specific triage labels to Prow

### ISSUE THREAD

**Issue by vllry** [kubernetes/test-infra#12594]
**What would you like to be added**:
Add SIG-specific labels to assist in sorting and finding triaged/untriaged issues. EG `needs-triage/<sig>`.

When SIG labels are added/removed, Prow should add/remove the corresponding triage labels.

Members can remove the triage label with a Prow command, to indicate triage has been done on behalf of that SIG.

**Why is this needed**:
In SIG-network, we've been using the `triage/unresolved` label for a few months to help burn through and stay on top of our backlog. The label is applied (via Prow via another bot) on new issues labelled `sig/network`, and members are asked to remove the label after the issue has been triaged.

This has worked great for network, but can't scale well to other SIGs. In an issue that encompasses multiple areas (EG [k/k issue 77135](https://github.com/kubernetes/kubernetes/issues/77135)), there are multiple areas of triage. If one reviewer removes the label after triaging on behalf of their sig, this in correctly indicates that all other involved SIGs have triaged.

**Alternatives**
Github project boards (EG [as used by the conformance WG](https://github.com/orgs/kubernetes/projects/9))

CC @kubernetes/sig-contributor-experience-feature-requests 
CC @justaugustus (on behalf of SIG-PM, which I can't find a handle for)

**Comment by nikhita** [comment]
Going to take a look at this issue, https://github.com/kubernetes/community/issues/3456 and https://github.com/kubernetes/community/issues/3455 after KubeCon. E_TOOMANYTHINGS before that. :grimacing:

**Comment by nikopen** [comment]
@vllry have a look at the above two tickets and also this: https://github.com/kubernetes/test-infra/pull/11818

it would be great to move them forward :)

/cc

**Comment by vllry** [comment]
Thanks, I'll look more into those proposals!

**Comment by nikopen** [comment]
closing in favor of a single label as in https://github.com/kubernetes/test-infra/pull/11818

/close

**Comment by justaugustus** [comment]
/remove-sig pm
/area enhancements

In progress in https://github.com/kubernetes/test-infra/pull/16298.
