### ISSUE TITLE
Add rebase command to prow

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/test-infra#12595]
**What would you like to be added**:

The idea is to be able to rebase the current PR with prow before doing the actual merge. Maybe a “rebase” setting on tide and an additional command like `/rebase` could be a good fit.

**Why is this needed**:

Merges with prow can currently make the master CI pipeline fail if two succeeding PRs are incompatible from a functional perspective.

**Comment by stevekuznetsov** [comment]
> Merges with prow can currently make the master CI pipeline fail if two succeeding PRs are incompatible from a functional perspective.

Could you go into a little bit more detail here?

Right now, `tide` can be configured to rebase PRs when merging them:

https://github.com/kubernetes/test-infra/blob/f5670a4ab1b73a14f15d58f378bfdfdd57c81123/prow/config/tide.go#L90-L92

When testing, the default behavior for `decorate: true` jobs is to create a branch that merges the commit of the PR branch and the target branch. Are you suggesting we rebase the user's PR branch first before testing it?

**Comment by saschagrunert** [comment]
> Are you suggesting we rebase the user's PR branch first before testing it?

Yes exactly, to the PRs merge base.

> Could you go into a little bit more detail here?

We had it recently that two PRs were tested fine but the first one made the second fail (only on the master branch, not in the PR). I would avoid this in the future somehow and I think prow could solve it by internally doing a rebase to the merge-base and reporting that the branch needs to be updated from a test perspective. Prow should somehow report that an rebase is ongoing in the background, but I'm not sure how to do this without confusing everyone.

**Comment by stevekuznetsov** [comment]
Let me do a quick example timeline:

1. PR 1 proposes commits to `master` at `sha-before`
2. PR 1 tests green against `master` at `sha-before`
3. PR 2 proposes commits to `master` at `sha-before`
4. PR 2 tests green against `master` at `sha-before`
5. PR 1 is approved and merges
5. `master` is now at `sha-after`
6. PR 2 is approved, tests against `master` at `sha-after`, fails
7. failing test results are reported to PR 2

Is this what you mean by failing on the master branch but not the PR? If someone were to manually `/test` in PR 2 after master branch is updated, they'd also see the tests fail.

Are you saying that you had a situation where the same set of commits, proposed as a merge to master on an old base, failed, but rebased, succeeded? Without any merge conflicts or edits necessary on the rebase? So, this fails:

```
master: A -- B -- C -- M
  pr-2:   `- Z -- Y -'
```

But this does not?

```
master: A -- B -- C ----------- M
  pr-2:            `- Z -- Y -'
```

**Comment by saschagrunert** [comment]
Thanks for your detailed explanations, I think I got it wrong. :pray: So the PR will be rebased to the target branch if `decorate: true`, right? Then this was the option I was looking for.

Closing this for now.

**Comment by kaovilai** [comment]
@stevekuznetsov 
> Are you saying that you had a situation where the same set of commits, proposed as a merge to master on an old base, failed, but rebased, succeeded? Without any merge conflicts or edits necessary on the rebase? So, this fails:
> 
> ```
> master: A -- B -- C -- M
>   pr-2:   `- Z -- Y -'
> ```
> 
> But this does not?
> 
> ```
> master: A -- B -- C ----------- M
>   pr-2:            `- Z -- Y -'
> ```

I have witness this behavior before where end to end tests can fail at least in my org repo that uses prow.

The logs of tests for the following
> PR 2 is approved, tests against master at sha-after, fails

still showed a test entry that had been removed in sha-after. https://github.com/openshift/oadp-operator/pull/727#issuecomment-1146353611

**Comment by kaovilai** [comment]
https://prow.ci.openshift.org/pr-history/?org=openshift&repo=oadp-operator&pr=727 shows that `e2e-<cloud-provider>` tests only pass after a [rebase](https://github.com/openshift/oadp-operator/pull/727#commits-pushed-0a3d874)

**Comment by kaovilai** [comment]
So ideally at least for my repos.. we would want ability to have prow rebase PRs automatically even if there are no conflicts.

**Comment by kaovilai** [comment]
We want ability to rebase prior to merging in order to clear some presubmit test scenarios.

**Comment by saschagrunert** [comment]
/reopen

Is it really not rebased before tested? This sounds like a bug to me.

**Comment by kaovilai** [comment]
This is not regarding merging cleanly. This is about updating the base that the test case in prow was running off of. The test triggered after sha-after in master did contain sha-before contents and caused presubmit test failure.

**Comment by stevekuznetsov** [comment]
That should simply be a race between the push of sha-after and the triggering of the job. A Prowjob will be started with a specific commit to test from the branch being merged into as well as the branch being merged. Can you please link to a job in question? We can investigate a) the refs being passed to run the job and b) the git commands used to create the code under test

**Comment by kaovilai** [comment]
This might be more of a openshift-ci-tools not working with /retest which I'm just guessing here.. the prowjob is reused without updating base ref if sha-after had been commited to master branch.

https://github.com/openshift/ci-tools/blob/a5ba2e7245eee5632e16076d88365af9d77307aa/cmd/ci-operator/main.go#L1841

PR linked here. https://github.com/kubernetes/test-infra/issues/12595#issuecomment-1225228397

We kept doing /retest but it wasn't going anywhere until rebase.

**Comment by stevekuznetsov** [comment]
No, that code is consuming the refs that Prow created when a user issued `/retest`, so it is downstream/derivative of what we're talking about in this issue. I'm going to need a specific pair of ProwJobs that you noticed this in, to determine if the one without a rebase really was running against the new HEAD or not.

**Comment by kaovilai** [comment]
based on deeper dive.. prowjob is correct at every point.. and every step ran a correct version from the prowjob. Time of failure of the jobs had distorted my view thinking this came from prow.

So we didn't have to rebase it seems.. but simply issue a new /retest.

So disregard the noise I made earlier. Feel free to re-close
