### ISSUE TITLE
Change frequency of soak-gce-federation-deploy job

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/test-infra#1260]
soak-gce-federation-deploy job has been changed to trigger everyday from every week in order to allow faster debugging. This is done in this PR [#1143].

we need to change it back to trigger every week, once the deployment is successful.

@madhusudancs

**Comment by madhusudancs** [comment]
Thanks @shashidharatd. 

Github won't let me assign this issue to @shashidharatd, so I am just putting my name in the "Assignees" section, but this is actually assigned to him.

**Comment by krzyzacy** [comment]
assume it's done?

**Comment by shashidharatd** [comment]
This issue was to remind us to change the frequency of soak test job and it is still not done. soak tests are not green yet for federation. request to please reopen this issue.

**Comment by madhusudancs** [comment]
May be reopen? It is still not done.

cc @shashidharatd
