### ISSUE TITLE
sig-release testgrid summaries having problems updating

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#12613]
**What happened**:
Went to look at release-related dashbaords after https://github.com/kubernetes/test-infra/pull/12608 merged

Summary pages look incomplete

**What you expected to happen**:

Summary pages to look the same as they did before (with a few jobs added)

**How to reproduce it (as minimally and precisely as possible)**:

Visit https://testgrid.k8s.io

**Please provide links to example occurrences, if any**:
- https://testgrid.k8s.io/sig-release-master-blocking - totally blank summary, all tabs present though
- https://testgrid.k8s.io/sig-release-master-informing - incomplete summary, the "GCE, master(dev)" tab isn't showing up in summary
- https://testgrid.k8s.io/sig-release-1.14-informing - currently giving "Server error: Unless this is a newly created dashboard, this should not happen. Please file a bug, noting the URL and time this occurred."

**Anything else we need to know?**:
slack discussion: https://kubernetes.slack.com/archives/C09QZ4DQB/p1557792264354500

apparently 
/assign @michelle192837 @Katharine

**Comment by michelle192837** [comment]
This may be complicated by/the fault of an update issue TestGrid's having right now. Still looking into that.

**Comment by Katharine** [comment]
sig-release-master-blocking and sig-release-1.14-informing are now populated and have correct sets of tabs.

sig-release-master-informing is still stale.

**Comment by spiffxp** [comment]
All three look good this morning
- https://testgrid.k8s.io/sig-release-master-blocking
- https://testgrid.k8s.io/sig-release-master-informing
- https://testgrid.k8s.io/sig-release-1.14-informing

Near as we can tell it's nothing on our end, sooo, magic.  Got it.

/close

**Comment by michelle192837** [comment]
TestGrid update slowness seems to have resolved itself as of 2-4 AM PDT, so...yeah, magic. -shrug-
