### ISSUE TITLE
./hack/update-bazel.sh behaves differently when creating a new file vs updating an existing one

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#12626]
**What happened**:

I created a new Go package and ran `./hack/update-bazel.sh`. The resulting file failed presubmits because lines were in the wrong order. I ran `./hack/update-bazel` again and it [switched the offending lines](https://github.com/kubernetes/test-infra/pull/12618/commits/3db4ced4531c69062135bf07c051ab51d1d07983), making the file valid.

**What you expected to happen**:

Running `update-bazel.sh` once should be sufficient

**How to reproduce it (as minimally and precisely as possible)**:

1. Add a new Go package
2. Run `./hack/update-bazel.sh` to create a new BUILD.bazel for it
3. Run `./hack/verify-bazel.sh` and observe it fail.

**Please provide links to example occurrences, if any**:

#12618

**Comment by matthyx** [comment]
From a quick test, that one seems fixed for me.
/close
