### ISSUE TITLE
e2e testing against local cluster failed to create clientset

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/test-infra#12661]
**What happened**:

e2e framework failed to create client against local cluster
```
May 14 11:16:30.663: INFO: >>> kubeConfig: /var/run/kubernetes/admin.kubeconfig
F0514 11:16:30.665844  135309 e2e.go:81] Error loading client: host must be a URL or a host:port pair: "https://"
```
**What you expected to happen**:

e2e testing used to load kubeconfig and talk to local cluster successfully

**How to reproduce it (as minimally and precisely as possible)**:

follow https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md#local-clusters:

```
$ go get -u k8s.io/test-infra/kubetest
$ cd $GOPATH/src/k8s.io/kubernetes
$ git fetch upstream
$ git checkout upstream/master
$ make clean all
$ sudo PATH=$PATH hack/local-up-cluster.sh
```
in another terminal
```
$ kubetest --build # this is not necessary because we did `make all` before
$ export KUBECONFIG=/var/run/kubernetes/admin.kubeconfig
$ kubetest --provider=local --test --test_args="--ginkgo.focus=Secrets"
```

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

[TestContext.KubeConfig](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2005) seems to be set successfully, but restconfig.Host is somehow set to `https://`. Loading the same kubeconfig with a [standalone client](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/examples/out-of-cluster-client-configuration/main.go) succeeded.

**Comment by matthyx** [comment]
+1

**Comment by xing-yang** [comment]
Hi @roycaihw, I ran into this problem as well.  I tried your workaround and it worked.  Are you working on a fix?  Thanks!

**Comment by langyenan** [comment]
@roycaihw @xing-yang Hi, I submitted a PR for this issue, I believe it will work for you

**Comment by roycaihw** [comment]
Sorry I didn't get the time to work on it. @langyenan That's awesome. Thank you!

/unassign
/assign @langyenan
