### ISSUE TITLE
The Ability To Specify Repositories Whitelist (only) in Yaml For label-sync

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#12667]
**What would you like to be added**:
I would like the ability to specify repositories whitelist (--only cli option) via yaml for label-sync. Preferably we would be able to specify this in the same yaml file we specify labels.  

**Why is this needed**:
It's difficult to programatically manage a large comma separated list of repositories, it's easier to manage a yaml array. It's also easier to read, here is an example:

flag
```
--only=\
  a/b, \
  a/c, \
  a/d
```

yaml
```
only:
  - a/b
  - a/c
  - a/d
```

**Comment by cblecker** [comment]
I'm not sure I'm sold on this. I can understand why that would be easier, but it doesn't align with how we've designed things (we don't have any other meta configuration in the yaml file, and it obfuscates the target into a config file, as opposed to flags).

**Comment by fejta** [comment]
What is the motivation for needing this vs using the --only flag? The expectation is that --only fields will be temporary.

**Comment by midnightconman** [comment]
I am trying to create a self-service onboarding experience for internal customers, where they would go to a portal (with github-oauth) and using their credentials automation would create a pull request to add their repository and organization to a shared config file that contains yaml describing the orgs and repos that are onboarded to label-sync.

At the moment, to do this, I would have to create a PR for the job specification and parse a comma separated list of orgs/repos. It would be much easier for me to describe this in yaml, rather than a comma separated list. It would also be nice to not change the job specification, but instead just change config items. One other application that is pretty similar that uses this approach is `branch-protector`.

What do you guys think? I am using label-sync as a prow-job with kubernetes agent.

**Comment by midnightconman** [comment]
@cblecker @fejta 

What's the verdict, does this make sense? Do you guys have a better suggestion?

**Comment by cblecker** [comment]
/remove-lifecycle rotten

@midnightconman I think we're going to have to go with a "no" on this. It doesn't really work with our current designs/needs in the kubernetes community.

A possible workaround would be using bash to inject the comma separated values from a file:
```
$ cat test.txt 
kubernetes
kubernetes/community
kubernetes/test-infra
$ cat test.txt | sed -e ':a' -e 'N;$!ba' -e 's/\n/,/g'
kubernetes,kubernetes/community,kubernetes/test-infra
```

Something like that would allow you to read the values in from a file, and then use `--only "$(cat repolist.txt | sed -e ':a' -e 'N;$!ba' -e 's/\n/,/g')"` in your command.

Sorry for the delay and lack of clarity around this.

/close
