### ISSUE TITLE
Update acs-engine to aks-engine

### ISSUE THREAD

**Issue by saiyan86** [kubernetes/test-infra#12709]
**What should be cleaned up or changed**:
For Azure related deployments, we should update acs-engine related parts to aks-engine.
**Provide any links for context**:
Like below line, we should update acs to aks.
https://github.com/kubernetes/test-infra/blob/95ef25d878a3b772d05236584c7cb16b845d5f8d/kubetest/azure.go#L48

**Comment by saiyan86** [comment]
I can do the cleanup if @ritazh thinks it's OK to proceed.

**Comment by ritazh** [comment]
Go for it @saiyan86! FYI @adelina-t

**Comment by adelina-t** [comment]
SGTM :)
