### ISSUE TITLE
Alternative to GCR hosted images for building/testing k8s

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#12725]
**What would you like to be added**:
An alternative way of getting docker images required by building and testing k/k and other repos (k/test-infra I think too).

**Why is this needed**:
Some companies we work in (for example mine!) do not allow accessing GCR registries through the corporate firewall In order to develop and test I need use my phone as a hotspot to download needed images locally...

**Possible solutions**:
- override image registry urls in build config?
- support loading tar.gz of released images from github.com/org/repo/releases

**Comment by matthyx** [comment]
As discussed at KubeCon Europe...
/cc @BenTheElder 
/cc @cjwagner

**Comment by BenTheElder** [comment]
I think this would need to be a kubernetes/kubernetes change, i'm also not sure but it _might_ support this already :sweat_smile:

**Comment by matthyx** [comment]
Yes, it seems we don't use any... 🎆 
If only we had the same everywhere !
But the change in k/k should come from sig-testing, no?

**Comment by BenTheElder** [comment]
> But the change in k/k should come from sig-testing, no?

no, that would be sig-release

**Comment by matthyx** [comment]
ok, I will create the issue in k/k and reach sig-release
thanks Ben!

**Comment by matthyx** [comment]
https://github.com/kubernetes/kubernetes/issues/78679
