### ISSUE TITLE
Spyglass cuts off parts of long lines

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#12731]
**What happened**:

Spyglass cuts off lines if they are too long, making it impossible to see the cut off part. Sample directly copied from the file in GCS:

```
time="2019-05-20T15:40:14Z" level=info msg="ClusterHealthStatus: \"{\\\"apiserver\\\":false,\\\"scheduler\\\":false,\\\"controller\\\":false,\\\"machineController\\\":false,\\\"etcd\\\":true,\\\"openvpn\\\":true,\\\"cloudProviderInfrastructure\\\":true,\\\"userClusterControllerManager\\\":false}\"" worker-name=1130494268687781889
```

In Spyglass it looks like this: 
![spyglass-long-lines](https://user-images.githubusercontent.com/6496100/58128008-fb5fe000-7c16-11e9-859a-895b03252edd.png)

It seems like the word gets cut at the end of the line, but the next word (that orginally was in the same line) gets displayed in another line in Spyglass

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/cc @Katharine

**Comment by stevekuznetsov** [comment]
Wait wasnt' there some weird `null` character thing doing this before? @alvaroaleman what version of `deck` are you on?

**Comment by alvaroaleman** [comment]
We are currently on `gcr.io/k8s-prow/deck:v20190513-95c7cbee2`
