### ISSUE TITLE
error during ./cluster/log-dump/log-dump.sh exit status 1

### ISSUE THREAD

**Issue by IamPrvn** [kubernetes/test-infra#12741]
I get the following error while running conformance tests using kubetest.

error during ./cluster/log-dump/log-dump.sh /builds/atd/oci_k8s_conformance_tests/conformance/k8s_release_stable-1.13/generated/_artifacts: exit status 1

The test suite passed but the log collection step failed, quick look into code does suggest that `skeleton` types are not a part of `node_ssh_supported_providers`, so ideally log collection from master and workers should have skipped.
https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L41
 
Additional Info -
We do not use prow CI , we run the jobs (test) in our own environment and push the results to gcp bucket.
One more observation, not sure whether it's important.
When I used to run the same test on my mac dump-logs didn't cause any nuisance. See these results 
https://prow.k8s.io/view/gcs/k8s-conformance-oracle-cloud/cloud-provider-oci-oke/e2e-conformance-stable-1.11/1557807885
The above issue  arises when we run the test on linux (ubuntu OS) dockers containers. See the results for ubuntu
https://prow.k8s.io/view/gcs/k8s-conformance-oracle-cloud/cloud-provider-oci-oke/e2e-conformance-stable-1.11/1558512756

**Comment by IamPrvn** [comment]
After triaging it further I got to following conclusions ;
When you run kubetest with skeleton provider `kubetest --provider skeleton --dump=<some_path>`, KUBERNETES_PROVIDER is not set, and when `DumpClusterLogs` test case is run (because dump flag is passed)  this unset variable causes the difference.
The code `[[ "${master_ssh_supported_providers}" =~ "${KUBERNETES_PROVIDER}" ]]` returns false in case of OSX while it returns true on linux. (https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L275) 

A simple test to crosscheck is to run `[[ "hello" =~ "" ]]` and then check `echo $?` in bash on both osx and linux. 
Since the above logic return true skeleton is supposed to be one of ssh_supported providers and thereby tries to fetch logs from master and nodes in which it fails.

Can anyone verify this ! @michelle192837 @spiffxp

**Comment by IamPrvn** [comment]
migrated the issue to kubernetes repo https://github.com/kubernetes/kubernetes/issues/78432

**Comment by BenTheElder** [comment]
btw are you setting the KUBERNETES_CONFORMANCE_TEST="y" ?

**Comment by BenTheElder** [comment]
ah moved to kubernetes
