### ISSUE TITLE
/skip command is not working as expected

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#12740]
**What happened**:

I ran an optional CI job on a PR, verified the particular tests in that job I was fixing passed, then wanted to merge my PR (despite there being other unrelated failures in the optional job).

I tried specifying `/skip` (and then `/skip [job name]`) to remove the failed CI status so my PR could merge, but nothing happened.

The job:
https://github.com/kubernetes/test-infra/blob/e96e1ab77b39c9385c1a58b37b51b97b4dcfc2dd/config/jobs/kubernetes/sig-gcp/sig-gcp-gce-config.yaml#L102-L111

The PR and skip comment: https://github.com/kubernetes/kubernetes/pull/78190#issuecomment-494659033

(After the `/skip` command failed to work, I also deleted the comments requesting `/test [job name]` in case that was preventing the removal, and re-issued `/skip`, with the same results)

**What you expected to happen**:

Failed CI status for optional jobs to be removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
We would like to see `hook` logs for the comment `494659033` to debug what happened here.

**Comment by michelle192837** [comment]
Interesting? Message on that was:

 jsonPayload: {
  author:  "liggitt"   
  component:  "hook"   
  event-GUID:  "86987920-7c53-11e9-964c-41b5b7ae1396"   
  event-type:  "issue_comment"   
  level:  "debug"   
  msg:  "Comment doesn't match any triggering regex, skipping."   
  org:  "kubernetes"   
  plugin:  "trigger"   
  pr:  78190   
  repo:  "kubernetes"   
  url:  "https://github.com/kubernetes/kubernetes/pull/78190#issuecomment-494659033"   
 }
 timestamp:  "2019-05-22T05:36:19Z"

**Comment by stevekuznetsov** [comment]
That's ok, it doesn't -- it's a skip command, not a trigger

**Comment by stevekuznetsov** [comment]
Actually, reading the code -- I was right the first time I tried to remember how this worked:

https://github.com/kubernetes/test-infra/blob/fb0685e8283ddf659079bb92c609c56c1089293b/prow/plugins/skip/skip.go#L130-L133

@cjwagner is this surprising?

**Comment by michelle192837** [comment]
Other log for that comment:

jsonPayload: {
  author:  "liggitt"   
  component:  "hook"   
  event-GUID:  "86987920-7c53-11e9-964c-41b5b7ae1396"   
  event-type:  "issue_comment"   
  level:  "debug"   
  msg:  "Filtered 86 jobs, found 0 to trigger and 0 to skip."   
  org:  "kubernetes"   
  plugin:  "skip"   
  pr:  78190   
  repo:  "kubernetes"   
  to-skip:  null   
  to-trigger:  null   
  url:  "https://github.com/kubernetes/kubernetes/pull/78190#issuecomment-494659033"   
 }

 timestamp:  "2019-05-22T05:36:20Z"

**Comment by stevekuznetsov** [comment]
Yeah so that confirms it, the status existed, was failed and was not handled by `trigger` otherwise, so `skip` ignored it because it was a required status (required-if-present)

**Comment by liggitt** [comment]
> because it was a required status (required-if-present)

how is that determined? is that an attribute of the job? I didn't see anything in the job spec that looked like it was required

**Comment by stevekuznetsov** [comment]
Yes, all statuses are required until they are not -- `optional: true` can be set on the job level. Please see the doc:

https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#requiring-job-statuses

**Comment by nikhita** [comment]
> Yes, all statuses are required until they are not -- optional: true can be set on the job level. 

Should this be closed as WAI?

**Comment by michelle192837** [comment]
Think that's fine. ^^

/close
