### ISSUE TITLE
Prow shouldn't crash when there is unrecognized job config

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#12759]
**What would you like to be added**:
Instead of crashing Prow, sending warnings if there is "bad" job config found

**Why is this needed**:
While testing jobs with `mkpj`, there is a chance that a "bad" job config is applied on Prow cluster, and this may cause `deck` and `horologium` stop working with error: `error listing prow jobs`. 
Example: https://github.com/knative/test-infra/issues/801
In above example`tide` also failed for related reason

**Comment by stevekuznetsov** [comment]
Perhaps, but if you cannot list anything you cannot do any work so there is little difference. The real issue was using a newer `mkpj` than the cluster version and the choice to make the duration string migration in a way that it was possible to crash. We've learned from that and we will not make that type of migration again. Versioned config nullifies the issue.

/cc @cjwagner

**Comment by stevekuznetsov** [comment]
More specifically, using `mkpj` under normal circumstances will never create a bad ProwJob

**Comment by chaodaiG** [comment]
Agree with using `mkpj` under normal circumstances would never create a bad ProwJob, giving the statement above that this kind of migration will never happen again.
The idea here is for making Prow more resilient, as there might be some other things happen, i.e. `kubectl apply` wrong file, or accidentally edited `mkpj` generated job config while inspecting it. Is it possible for `prowJobClient.List` return whatever jobs it found valid, and instead of failing fast, the caller executes these jobs, and spits out warning if there is any error? An example is horologuim: https://github.com/kubernetes/test-infra/blob/58b85f6993675120a07980a50201fa37c892b16f/prow/cmd/horologium/main.go#L126

**Comment by stevekuznetsov** [comment]
I don't think the generated CRD clients work like that, no.

**Comment by chaodaiG** [comment]
so it's the limitation here, right?
https://github.com/kubernetes/test-infra/blob/58b85f6993675120a07980a50201fa37c892b16f/prow/client/clientset/versioned/typed/prowjobs/v1/prowjob.go#L80

**Comment by stevekuznetsov** [comment]
Right, that's the lowest level of the generated typed clients.

**Comment by stevekuznetsov** [comment]
I don't think there is any actionable work here
/close
