### ISSUE TITLE
cherrypick: Bot ignores /cherrypick requests in initial PR comment

### ISSUE THREAD

**Issue by wking** [kubernetes/test-infra#12752]
**What happened**:

I had `/cherrypick release-4.1` in [a PR topic post][1], but the bot did not backport the PR after it landed.

**What you expected to happen**:

Cherry-pick bot to backport the PR after it landed.

[1]: https://github.com/openshift/origin/pull/22893#issue-281592199

**Comment by alvaroaleman** [comment]
Where you able to make any porgress here steve? Its pretty annoying :( But IIRC fixing this requires refactoring most of the plugin or did you come up with a better approach?

**Comment by stevekuznetsov** [comment]
I didn't end up working on this -- I think it should be easy to just accept more types of events like we do for other plugins?

**Comment by alvaroaleman** [comment]
It already has handling of both pull requests and issues, but when I looked at it I didn't see a way of fixing that without refactoring most of both handling parts.

**Comment by stevekuznetsov** [comment]
Right, that's what I had in mind.
