### ISSUE TITLE
pull-kubernetes-kubemark-e2e-gce-big is failing across PRs

### ISSUE THREAD

**Issue by vllry** [kubernetes/test-infra#12778]
pull-kubernetes-kubemark-e2e-gce-big has been failing for around 12 hours.

ClusterLoaderV2 fails.

```error during /go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --nodes=500 --provider=kubemark --report-dir=/workspace/_artifacts --testconfig=testing/density/config.yaml --testconfig=testing/load/config.yaml --testoverrides=./testing/load/kubemark/500_nodes/override.yaml: exit status 1```

EG:
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/74614/pull-kubernetes-kubemark-e2e-gce-big/1133047962729975808/
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78399/pull-kubernetes-kubemark-e2e-gce-big/1133082061221924864/
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78408/pull-kubernetes-kubemark-e2e-gce-big/1133126605133058052/

**Comment by liggitt** [comment]
Potential fix in https://github.com/kubernetes/perf-tests/pull/541

**Comment by hainesc** [comment]
I encounter the same problem
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/78009/pull-kubernetes-kubemark-e2e-gce-big/1133104206702448641/

**Comment by tao12345666333** [comment]
Maybe the same problem 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80134/pull-kubernetes-kubemark-e2e-gce-big/1150912885606584320/
