### ISSUE TITLE
ci-kubernetes-e2e-gce-multizone job is in inconsistent state

### ISSUE THREAD

**Issue by colhom** [kubernetes/test-infra#1277]
Tracking the log output of the job, I've narrowed https://github.com/kubernetes/kubernetes/issues/37025 down to a root cause in Kubernetes cluster code:

It turns out the `kube-down` framework is finding that other instances exist based on the fragile regexp logic the framework uses to discern ownership.

`REMAINING_MASTER_COUNT` is generated [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L1363-L1367), based on instances in the region which match a regexp based on `MASTER_NAME`.

Apparently `REMAINING_MASTER_COUNT != 0` for this particular regex, so the `kube-down` system interprets this as a cluster upgrade.... of course. The next step if `REMAINING_MASTER_COUNT>0` is to first call validate cluster, which occurs in [this block](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L1468-L1485). There is no cluster to validate in this case, so this ends badly.

As a potentially separate issue, `validate-cluster.sh` will continue to check the cluster state many, many times.

 When it finally fails for the last time, kube-down returns an error and the job fails before the new cluster can even come up.

I can't tell from the logs what the `MASTER_NAME` variable is, which is the basis for the [ownership regex](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L1533-L1535).

Once we have that information, maybe someone with GCE access ( @ixdy @spxtr ??) could help me debug this further?

**Comment by ixdy** [comment]
@krzyzacy can you assist?

**Comment by krzyzacy** [comment]
eh, what's needed here?

**Comment by colhom** [comment]
@krzyzacy can you tell me what the Jenkins job is seeing when it executes [this function](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L1363-L1367)

**Comment by colhom** [comment]
My hunch is that it's finding some instances that it shouldn't for whatever reason.

**Comment by krzyzacy** [comment]
the output will be `us-central1-a`

and full instance list dump is:
```
NAME                                ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP     STATUS
bootstrap-e2e-gce-multizone-master  us-central1-a  n1-standard-1               10.240.0.2   104.154.128.82  RUNNING
```

**Comment by colhom** [comment]
@krzyzacy could you tell me when that instance was first launched? If was more than, say a few days ago- go ahead and delete it.

**Comment by krzyzacy** [comment]
`2016-12-01T03:38:45.825-08:00`, not too old

**Comment by colhom** [comment]
@krzyzacy if that instance is still there, let's

* stop the jenkins job
* kill the instance
* start the jenkins job

That instance should only stick around for the duration of a single e2e test run- I feel there's a resource leak somewhere.

**Comment by krzyzacy** [comment]
it's still there, and jenkins job should be running cron-based.

I'll kill the instance, the next job should pop a new one.

**Comment by colhom** [comment]
@krzyzacy only worry there is that killing the master while a job is in progress has the potential to inflict further undefined state on our house of cards.

Honestly, we can reset the state of the account (as it's dedicated) pretty trivially if this goes more wrong. Bon voyage!

**Comment by colhom** [comment]
I mean project- not account. If this doesn't work for whatever reason- we should probably de-cron the jenkins job, destroy and re-create the project and see if that fixes it.

**Comment by krzyzacy** [comment]
@colhom em.. I feel like the better way should be clone a job, and run the job use bootstrap.py and make sure it works first? Since it's not a test-infra failure and manually doing things might not be a good idea. Maybe @madhusudancs or @krousey (build cop) can help?

**Comment by fejta** [comment]
Assigning to @madhusudancs and @krousey to help find someone to help

**Comment by madhusudancs** [comment]
@krzyzacy by clone a job, you also mean create a new project?

**Comment by krzyzacy** [comment]
@madhusudancs I guess I'm not very familiar with the context of this issue, I feel like you can create a new project/new jenkins job to collect the debug information you want?
