### ISSUE TITLE
Prow: readable log when List job failed parsing json

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#12784]
**What happened**:
The current log contains `unexpected character: �` when List job failed

**What you expected to happen**:
Log clearly specified which character is unexpected

**How to reproduce it (as minimally and precisely as possible)**:
Create a Prow job config that contains unparsable character (In the case above it was `s`)

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
Example log:
```
""prow/crier/controller.go:108: Failed to list *v1.ProwJob: v1.ProwJobList.Items: []v1.ProwJob: v1.ProwJob.Spec: v1.ProwJobSpec.DecorationConfig: v1.DecorationConfig.GracePeriod: readUint64: unexpected character: �, error found in #10 byte of ...|_period":"15s","time|..., bigger context ...|redentials_secret":"test-account","grace_period":"15s","timeout":"2h0m0s","utility_images":{"clonere|..." " 
```

**Comment by chaodaiG** [comment]
@krzyzacy , not really :)
 
It was something we discovered here: https://github.com/knative/test-infra/issues/801. tl;dr is a prowjob created with latest mkpj was not parsed by not that up-to-date Prow instance. The issue itself was fixed by updating Prow, but the debugging experience was not that smooth due to this unrecognized character

**Comment by krzyzacy** [comment]
@chaodaiG - the error message comes from https://github.com/kubernetes/client-go/blob/79226fe1949a01066ee9e3a3f4c53546d72e1194/tools/cache/reflector.go#L201 which is not part of prow controllers, so here's nothing really we can do (feel free to open another issue in that repo)

also we now publish official mkpj images together with prow controller images, you should probably run mkpj from that version instead :-)

**Comment by chaodaiG** [comment]
@krzyzacy , looks like different Prow components list jobs differently, for example, as one of the other components also failed, plank is not using the code path you linked above, instead it uses this: https://github.com/kubernetes/test-infra/blob/506a6dc713f5fb1598ba07307c214784519d56f2/prow/kube/client.go#L484

Thanks for the info regarding versioned mkpj, that's definitely what we need, will explore that for sure

**Comment by krzyzacy** [comment]
right - what I'm trying to say is the underlying error is generated from apiserver, not made up by Prow :-)

**Comment by stevekuznetsov** [comment]
Plank will migrate to use the clients soon, too.

**Comment by stevekuznetsov** [comment]
Since this is a message coming out of the APIServer we can't really do anything here -- I will note it looks like whatever log viewer you're using is rendering the bad character, as well. In light of this, I will close out this issue.

/close
