### ISSUE TITLE
Feature request: allow squashing on case-by-case basis

### ISSUE THREAD

**Issue by pmorie** [kubernetes/test-infra#12799]
**What would you like to be added**:

This request is to add the ability to be able to request squashing and resulting commit message on a case by case basis when a repo is not configured to automatically squash commits.

Example:

```
/squash "Commit message here"
```
Later, once the PR is satisfied, the commits are squashed and given the requested commit message.

**Why is this needed**:

In repos where the contributors do not want to a priori squash all commits in merged PRs, it would be very handy to be able to squash individual PRs and control the resulting commit message. This would save time and contributor effort.

**Comment by bobcatfish** [comment]
To add a little bit more context, auto squashed commit messages can often end up looking something like this:

```
WIP Fix the foobar

* got it mostly working
* fixed the foobar
* review feedback
* test
* shoot that didn't work
* fixy fixy
* more review feedback
```

We'd like to be able to:

1. use prow
2. make it easy for contributors to squash commits
3. maintain high commit message standards (https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

And on the subject of good commit message standards, I'd like to request a slightly different format than in @pmorie's example:

```
/squash
This is the subject line of the commit

This is the body of the commit message, where the line length is limited
and I make sure to explain some context, and maybe include relevant issues
such as Fixes #1235566
```

(i.e. a multi lline message - and bonus, this could be a cool place to in the future even add some automation around verifying the commit message! e.g. according to these standards https://chris.beams.io/posts/git-commit/)

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

Today it is possible to have a specific PR squash when merged by adding the [`tide/merge-method-squash` label](https://github.com/kubernetes/test-infra/blob/6a6ff8c636e7406c52213c70914eb66b84e0b947/label_sync/labels.yaml#L667-L673). What is the utility in using a `/squash` command to change the commit message, as opposed to just asking the developer to do this with `git` and push the new commit to their branch?

**Comment by stevekuznetsov** [comment]
I'll close this as it has no engagement and the tide merge method label solves the issue mostly.

/close
