### ISSUE TITLE
test-grid sort by failures doesn't always work

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#12804]
Example: https://testgrid.k8s.io/istio-postsubmits-master#integration-k8s-tests&sort-by-failures=

There are some failures at the top, then a bunch of green, then more failures at the bottom. This is especially bad because we expect failures at the top and assume all tests pass otherwise, so failures are missed.

I tried on chrome and firefox so I think it isn't a local issue

**Comment by spiffxp** [comment]
/area testgrid
/sig testing
/assign @michelle192837 
I believe this was an internal failure mode of testgrid, and think this is now addressed, but assigning to @michelle192837 to confirm

**Comment by michelle192837** [comment]
This is known but not addressed yet (I could not find out why on earth it's doing this :/). I think it's actually only on external because the frontend logic handling this is slightly different, but no idea on what the cause of the bug actually is.

**Comment by BenTheElder** [comment]
@howardjohn are you still seeing this? I _think_ the latest release fixes this. Worked with Michelle to rewrite the sort.
/assign

**Comment by howardjohn** [comment]
Seems to work!

**Comment by michelle192837** [comment]
Thanks again Ben for the fix! ^^
