### ISSUE TITLE
Crier doesn't pick up changes in the slack config without a restart

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#12818]
**What happened**:

Crier doesn't pick up changes in the the slack config without a restart

**What you expected to happen**:

Crier picking up changes in the slack config without a restart

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by krzyzacy** [comment]
is the slack config passed in as a flag or a config field?

**Comment by alvaroaleman** [comment]
Its part of the config: https://github.com/kubernetes/test-infra/blob/36fcb352330cee91aeb166ea46aa8a4d110c0d3b/prow/config/config.go#L83

So in theory shouldn't be a problem, I guess I did something stupid like passing in the config directly instead of a Getter when adding Slack support to crier

**Comment by krzyzacy** [comment]
yeah - https://github.com/kubernetes/test-infra/blob/c1df55548381e49ffde468860dcfc1f1f22555e8/prow/cmd/crier/main.go#L183
