### ISSUE TITLE
Set up alerting for prow metrics being out of bounds or entirely absent

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#12829]
We should have alerting for this, so we know when the world is :fire:

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

@Katharine there are measures of health between prometheus and the deployments it's scraping like [`up`](https://prometheus.io/docs/concepts/jobs_instances/) -- we can also add literal alerts for when scraping is working but no data is coming back (that's how the latest sinker issue manifested). Did you want an alert for [`absent`](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent) on every metric we publish?
