### ISSUE TITLE
strInSlice cleanup

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#12825]
**What should be cleaned up or changed**:
There's a number of places we have a little `strInSlice` helper function to give a true/false if a particular string is in a slice.

We should look at cleaning that up. Either we put that helper function in a single place, or wr just swap it out for the `sets` package as @stevekuznetsov suggests here: https://github.com/kubernetes/test-infra/pull/12817#discussion_r289502498

**Provide any links for context**:

https://git.k8s.io/apimachinery/pkg/util/sets

**Comment by pswica** [comment]
I gave this a shot in my PR above. Please let me know if there's anything else I should improve on (I'm still new to open source and this is my first contribution to test-infra)

**Comment by spiffxp** [comment]
/sig testing
/area prow
/close
Addressed by #12834 thanks @pswica!
