### ISSUE TITLE
Deploy monitoring-stack for prow

### ISSUE THREAD

**Issue by hongkailiu** [kubernetes/test-infra#12854]
**What would you like to be added**:
Add [monitoring-stack](https://github.com/coreos/prometheus-operator) including prometheus/alertmanager/grafana for [prow.k8s.io](https://prow.k8s.io/).

**Why is this needed**:
* Scrape prow components with [prometheus](https://prometheus.io/) to collect data provided by the endpoints which are already available.
* Oversee with [grafana](https://grafana.com/) dashboards how prow components are running on the (k8s-)cluster and fire alerts by [alertmanager](https://prometheus.io/docs/alerting/alertmanager/) when necessary, eg, some service is down or other conditions are satisfied.

Steps:

- [x] [Check prerequisites](https://github.com/coreos/prometheus-operator#prerequisites): k8s version >=1.8.0
- [x] [Deploy CRDs](https://github.com/coreos/prometheus-operator#customresourcedefinitions): `Prometheus`, `ServiceMonitor`, `PrometheusRule`, `Alertmanager`
- [x] Deploy `prometheus operator` and required `RBAC`
- [x] Deploy custom object: `Prometheus`
- [x] Deploy grafana
- [x] Expose the ingress via the vanity URL
- [x] Deploy dashboards
    - [x] use mixins: ~~blocked~~
    - [x] fix the repo name in `tide` board
    - [x] add `UID` into `ghproxy` board
- [x] Add services for prow components that have not had `/metrics` services yet
- [x] Update `config.yaml` to enable serving `/metrics`
- [x] Add  `ServiceMontors` for all prow-components
- [x] Deploy `ServiceMontors` for prometheus and grafana
- [x] grafana admin access issue: replicas=1
- [x] `https` only on grafana ingress: nginx is the only promising solution
- [x] Link in the bazel targets to apply all the monitoring objects with the normal Prow release target for `postsubmit`: [trails](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L32); [slack-discussion](https://kubernetes.slack.com/archives/CDECRSC5U/p1561058448274500)
- [x] Deploy `ServiceMontor` for alertmanager
- [x] Deploy custom object: `Alertmanager`
- [x] Add more alerts
- [x] Test firing alerts with AlertManager
- [x] Add readme to do the port-forwarding/proxy for alertmanager and prometheus to make them simpler
- [x] Decide if we want to HA grafana (view-only) and dev.monitoring.prow.k8s.io (admin): @Katharine and @stevekuznetsov are for this: We leave this as future work.

**Comment by hongkailiu** [comment]
tony-yang [7:04 PM]
1.13.5-gke.10

**Comment by stevekuznetsov** [comment]
Thought: a `bazel` target to do the port-forwarding/proxy for alertmanager and prometheus to make them simpler

**Comment by stevekuznetsov** [comment]
As well: link in the `bazel` targets to apply all the monitoring objects with the normal Prow release target for postsubmit

**Comment by hongkailiu** [comment]
Also need to find a convenient way to test queries:
* ingress for prometheus
* edit access (to a restricted set of people) to grafana (This might be preferable given the circumstance ^_^)

**Comment by hongkailiu** [comment]
monitoring.prow.k8s.io is not `https` yet.

**Comment by cjwagner** [comment]
SSL is working now, but is still optional. We need to force SSL redirection for HTTP requests to make it safe to use basic auth, but unfortunately this isn't possible to configure with ingress-gce: https://github.com/kubernetes/ingress-gce/issues/51

I think we'll need to add an nginx proxy solely for this purpose like we used to have to do for Prow before we added SSL redirection to `deck`. Grafana doesn't appear to have any SSL redirect or HSTS options.

**Comment by hongkailiu** [comment]
> SSL is working now, but is still optional.

Would `kubernetes.io/ingress.allow-http: "false"` help as described [51#issuecomment-335960782](https://github.com/kubernetes/ingress-gce/issues/51#issuecomment-335960782)?

**Comment by hongkailiu** [comment]
@cjwagner 
I would like to give another try of selling the idea of [mixins](https://grafana.com/blog/2018/09/13/everything-you-need-to-know-about-monitoring-mixins/) (or [jsonnet](https://jsonnet.org/)) for monitoring stack.

* reusable grafana dashboards: kind of more important when `deploy/grafana` has more than one replica (for HA). [Provisioning of dashborads via json files](https://grafana.com/docs/administration/provisioning/#dashboards) ensures the consistent view across grafana instances, comparing to editting via UI. We could still do the UI editting, only for debugging purpose. Once we think we should include some new panel or boards, we will generate the json file and provision it to all instances.
* it is kind of popular in the community, eg, [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin). Ease the code review too (to some extent ^_^ @stevekuznetsov can tell more on this point).
* dependency managerment: the underlying libs (eg, [grafana/grafonnet-lib](https://github.com/grafana/grafonnet-lib)) will be maintained by grafana gurus and the upgrade procedure should be more smooth when we decide to change the version of grafana in the future.

Let me know your decision.

**Comment by cjwagner** [comment]
> Would `kubernetes.io/ingress.allow-http: "false"` help as described [51#issuecomment-335960782](https://github.com/kubernetes/ingress-gce/issues/51#issuecomment-335960782)?

Unfortunately I think that would prevent cert-manager from completing the ACME challenge to refresh the SSL cert from letsencrypt. https://github.com/jetstack/cert-manager/issues/1366#issuecomment-463242495
Maybe if we don't use `certmanager.k8s.io/acme-http01-edit-in-place: "true"` cert-manager will still be able to compelete the ACME challenge using a temporary ingress, but I think that ingress would get a new IP...
@munnerz do you know if we can achieve this without adding an nginx proxy?

As far as mixins go, I'm happy to try them especially if they help with reusability, but I'm skeptical that reviewing serialized dashboard specification is going to be easier and more effective than just looking at the actual dashboard or that peer reviewing dashboard changes is worthwhile or necessary in the first place. So I'm fine with trying it out so long as we maintain a good development pattern for creating new dashboards with a UI and getting them deployed quickly and easily.

**Comment by hongkailiu** [comment]
@cjwagner Thanks. I will do a PR including the mixins and using jsonnet to generate json files.

This is how we organized mixins in our production:
https://github.com/openshift/release/tree/master/cluster/ci/monitoring/mixins

We keep both jsonnet and json files in the repo ... so if we want to review the json file directly, we can still do it.

We have also a presubmit job to generate the json file on the fly and compare if they are the same as the ones in the repo.

**Comment by hongkailiu** [comment]
https://kubernetes.slack.com/archives/C7J9RP96G/p1560993568155100

One grafana pod as a workaournd for admin login.

**Comment by spiffxp** [comment]
/milestone v1.16
checklist above is still incomplete, I'm assuming we have more to do here

**Comment by spiffxp** [comment]
Currently available at https://monitoring.prow.k8s.io/

**Comment by stevekuznetsov** [comment]
All we have left is the AlertManager deployment, then we're done!

**Comment by stevekuznetsov** [comment]
I have a series of PRs to show how to add:

 - a new metric: #13376 
 - a dashboard from it: #13386 
 - an alert: TODO

**Comment by hongkailiu** [comment]
Created https://github.com/kubernetes/community/issues/3902, requesting slack incoming webhook URL.

**Comment by hongkailiu** [comment]
The testing alerts ... https://kubernetes.slack.com/archives/C7J9RP96G/p1563469948355200

Some discussion on icon/username: https://kubernetes.slack.com/archives/C7J9RP96G/p1563471649359200
