### ISSUE TITLE
The PR status page is not loading.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#12852]
https://prow.k8s.io/pr does not load.
```
Uncaught ReferenceError: dialogPolyfill is not defined
    at pr_bundle.min.js:1
    at NodeList.forEach (<anonymous>)
    at window.onload (pr_bundle.min.js:1)
```

**Comment by cjwagner** [comment]
This also appears to affect https://prow.k8s.io/plugins and https://prow.k8s.io/command-help, but not quite as fatally.

**Comment by cjwagner** [comment]
It is looking pretty likely that https://github.com/kubernetes/test-infra/pull/12806 is the culprit. I'll rollback the last bump (https://github.com/kubernetes/test-infra/pull/12813) and that change.

**Comment by spiffxp** [comment]
/close
per above
