### ISSUE TITLE
Migrate non-Kubernetes repos off of prow.k8s.io

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#12863]
Currently, the Kubernetes community prow instance (prow.k8s.io) is supporting a number of non-Kubernetes project repositories. We need to migrate these off the Kubernetes community infrastructure ahead of moving our instance onto project owned infrastructure.

We should also stop adding any new repos/orgs to the prow.k8s.io instance that aren't directly involved with the Kubernetes project.

Currently, I see the following repos/orgs with configuration in config.yaml/plugins.yaml:
- [x] https://github.com/bazelbuild/rules_k8s
- [x] https://github.com/client-go/unofficial-docs (https://github.com/kubernetes/test-infra/pull/12870)
- [ ] https://github.com/google/cadvisor
- [x] https://github.com/kubeflow (ref: https://github.com/kubernetes/test-infra/issues/14343)
- [x] https://github.com/helm/charts (ref: https://github.com/kubernetes/test-infra/pull/19946)
- [ ] ~https://github.com/containerd/cri~ https://github.com/containerd/containerd
- [x] https://github.com/tensorflow/k8s (https://github.com/kubernetes/test-infra/pull/21591)
- [x] https://github.com/tensorflow/minigo (https://github.com/kubernetes/test-infra/pull/21591)
- [x] https://github.com/spxtr/envoy (https://github.com/kubernetes/test-infra/pull/18297)
- [x] https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress (https://github.com/kubernetes/test-infra/pull/26297)
- [ ] https://github.com/GoogleCloudPlatform/k8s-cluster-bundle
- [x] https://github.com/GoogleCloudPlatform/netd (https://github.com/kubernetes/test-infra/pull/26324)
- [ ] https://github.com/cncf/apisnoop (https://github.com/kubernetes/org/issues/4705)
- [x] https://github.com/cncf/k8s-conformance (https://github.com/kubernetes/test-infra/pull/18901)
- [x] https://github.com/apache-spark-on-k8s/spark-integration (https://github.com/kubernetes/test-infra/pull/21141)

cc: @kubernetes/k8s-infra-team @kubernetes/sig-testing @fejta @cjwagner @Katharine @krzyzacy @amwat @michelle192837

**Comment by cblecker** [comment]
cc @nikhita for client-go/unofficial-docs

**Comment by cblecker** [comment]
cc @Random-Liu for containerd/cri

**Comment by nikhita** [comment]
> cc @nikhita for client-go/unofficial-docs

This is not active and can be removed. :+1:

**Comment by krzyzacy** [comment]
For google owned projects' owners: feel free to migrate to https://github.com/GoogleCloudPlatform/oss-test-infra instead

**Comment by cblecker** [comment]
@krzyzacy Do we have owners/contacts for the google owned projects?

**Comment by krzyzacy** [comment]
@cblecker you can check 😂 I think it can fall back to us, or maybe @spiffxp can also help coordinate?

**Comment by cblecker** [comment]
Looking at the configs, we probably don't need to worry about cncf/apisnoop (CNCF project and only using meow/bark).

We also may want to keep helm/charts around as it is also a CNCF project and may provide valuable signal.

**Comment by spiffxp** [comment]
@clarketm posted the following over in https://github.com/kubernetes/test-infra/issues/16974#issuecomment-604709583

For each project we choose to migrate: a proposal to minimize risk of downtime is:
* Phase 1: migrating project to a dedicated build cluster (e.g. [Kubeflow Prow Migration](https://docs.google.com/document/d/17sA-rRBe30bM034nL353CgrXETfy2vMe2m_g_bB_ILY/edit#heading=h.fxpk50cps4zs))
* [Phase 2](https://docs.google.com/document/d/127tZg2T3_oVHCnCkAqC_zTNOgChV7EN_e1fj4bet3V4/edit): setup bot, webhooks, transfigure, and port Prow config, plugins, kubeconfig and jobs to new instance (ideally with support from tools offered by Prow).
* Phase 3:  miscellaneous cleanup task: delete artifacts, redefine cluster, rerun, and bot permissions, and copy over historical job results.

> **Caveat:** the above may not be comprehensive but it is what I have gathered from my experience with Prow migration thus far. Please provide input here or in [doc](https://docs.google.com/document/d/127tZg2T3_oVHCnCkAqC_zTNOgChV7EN_e1fj4bet3V4/edit).

**Comment by BenTheElder** [comment]
https://github.com/spxtr/envoy doesn't even exist anymore

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/12863#issuecomment-498749626
containerd/cri is also a CNCF project, and most of our k8s CI consumes this ultimately.

filed a PR to remove spxtr/envoy.

**Comment by BenTheElder** [comment]
cAdvisor filed https://github.com/GoogleCloudPlatform/oss-test-infra/pull/336 but it's going a bit stale.

**Comment by BenTheElder** [comment]
Without a deadline I don't think we're going to see movement on this.
I think netd is now gone for unrelated reasons https://github.com/kubernetes/test-infra/pull/18473

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/18901 takes care of cncf/k8s-conformance (updated description)

**Comment by Bobgy** [comment]
FYI, I'm working on https://github.com/kubernetes/test-infra/issues/14343 this week

**Comment by BenTheElder** [comment]
progress on kubeflow https://github.com/kubernetes/test-infra/issues/14343#issuecomment-767433178

**Comment by BenTheElder** [comment]
https://github.com/apache-spark-on-k8s/spark-integration in https://github.com/kubernetes/test-infra/pull/21141

**Comment by Bobgy** [comment]
Update, kubeflow is now completely off k8s prow.

**Comment by BenTheElder** [comment]
- https://github.com/kubernetes/test-infra/pull/21591 will remove tensorflow/minigo which is now archived.

- https://github.com/tensorflow/k8s is now https://github.com/kubeflow/tf-operator which is using the google tide robot and kubeflow prow bot.

**Comment by BenTheElder** [comment]
github.com/cncf/* have their own prow now I think? Except cncf/apisnoop is still using the kubernetes prow (e.g. see event here https://github.com/cncf/apisnoop/pull/508#event-4770605248) cc @hh @zachmandeville

github.com/GoogleCloudPlatform/* should be able to move to https://github.com/GoogleCloudPlatform/oss-test-infra prow instance, but it seems some of them have not. cc @chaodaiG @cjwagner @MrHohn 

https://github.com/containerd/cri (now actually https://github.com/containerd/containerd) & https://github.com/google/cadvisor kind of actually run e2e with our resources and probably won't be as easily moved. cc @dims

We could move https://github.com/google/cadvisor to https://github.com/GoogleCloudPlatform/oss-test-infra perhaps. cc @dashpole 

And https://github.com/bazelbuild seems to be just https://github.com/bazelbuild/rules_k8s? Probably also could go to https://github.com/GoogleCloudPlatform/oss-test-infra? cc @fejta

**Comment by dashpole** [comment]
cc @bobbypage

**Comment by BenTheElder** [comment]
/milestone clear
this didn't happen, and i'm not sure that anyone is working on this currently

**Comment by BenTheElder** [comment]
updated the checklist

**Comment by BenTheElder** [comment]
Filed issues with most of these, https://github.com/containerd/containerd is the one I'm least sure about how to proceed.

For Google projects we have other, more appropriate Prow instances now.

For CNCF there is an instance for the k8s-conformance repo, which apisnoop can probably move to.

I suppose containerd could maybe move to the CNCF instance, I think it's generally not in Kubernetes's interest to lose the e2e coverage there and I'm not sure we currently have the resources setup to run those on another instance.

**Comment by endocrimes** [comment]
I think containerd should probably stay as part of Kubernetes' prow instance for the short-medium term. We get a lot of value out of that infra/testing being shared, and complicating the updating of either is going to likely hurt us. Especially with how few people we have to work on it.

**Comment by dims** [comment]
subscribe @dims

**Comment by mikebrow** [comment]
subscribe @mikebrow

**Comment by Riaankl** [comment]
> #26297 for https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress
> 
> cc @Riaankl CNCF has a prow instance don't they, is there a reason apisnoop is on the k8s prow still?

This prow job is a release informing job that is not requiered at the moment. We can remove it.

**Comment by hh** [comment]
The two cncf/apisnoop prow.k8s.io jobs are not part of the cncf/k8s-conformance Certification program, they are part of the Kubernetes #sig-arch Conformance Subproject to ensure #sig-release has CI-Signal to GA API promotions that are not covered by Conformance tests.

See https://github.com/kubernetes/community/tree/master/sig-architecture#conformance-definition-1

This underlying data is also used by apisnoop.cncf.io, which is not there for CNCF Conformance program, but for ensuring the Kubernetes technical debt collections/reductions continue to occur and that all new GA APIs include Conformance coverage.

It's my take that these are best served by the Kubernetes community prow.k8s.io instance. Anything related to the cncf.io/ck program and cncf/k8s-conformance are already run on prow.cncf.io.

**Comment by BenTheElder** [comment]
> The two cncf/apisnoop prow.k8s.io jobs are not part of the cncf/k8s-conformance Certification program, they are part of the Kubernetes #sig-arch Conformance Subproject to ensure #sig-release has CI-Signal to GA API promotions that are not covered by Conformance tests.

The apisnoop _repo_ however runs on @k8s-ci-robot / prow.k8s.io, independent of jobs producing apisnoop data.

https://github.com/cncf/apisnoop/issues/548#issuecomment-1139145808

**Comment by BenTheElder** [comment]
It is probably advisable to not have k8s-ci-robot remain an org owner of CNCF, IMHO, it already has the keys to a _lot_.

**Comment by hh** [comment]
@BenTheElder removing all bot interactions other than trigger to support the K8s focus prow jobs here : https://github.com/kubernetes/test-infra/pull/26418/files#r883159775

**Comment by hh** [comment]
Currently @k8s-ci-robot only admin perms on the `cncf/apisnoop` repo specifically not the **cncf** org.

We could reduce the perms lower than admin as we now only need a trigger for the jobs, not the bot interactions.

![image](https://user-images.githubusercontent.com/31331/170601276-fb25dfb5-dd32-4043-9be0-de37209d6ee8.png)

**Comment by BenTheElder** [comment]
Why do we need trigger from the repo?
I don't see what these jobs are. 

I found some image pushing jobs, but that also means that more generally this repo is dependent on SIG k8s infra infrastructure for GCB + image hosting.

Seems like you're saying this project is really a subproject of SIG architecture, is there a reason it's not in kubernetes-sigs?

**Comment by khareyash05** [comment]
@BenTheElder is [https://github.com/GoogleCloudPlatform/k8s-cluster-bundle](https://github.com/GoogleCloudPlatform/k8s-cluster-bundle) open to work upon?

**Comment by BenTheElder** [comment]
cc @aojea @mpherman2 @cjwagner @michelle192837 

I think we should put a deadline on this and then just disable any remaining jobs, they can be spun back up on a different prow later. I've filed bugs with all the remaining repos that have lingered for approximately 1 year now ...

We can even call it something generous like EOY 2023, but this really needs to be finished so we can look to migrate prow.k8s.io to the community infrastructure now that we have the GCP run rate more reasonable.

**Comment by mrbobbytables** [comment]
+1 to deadline, and I think we should be more aggressive with the deadline than EOY. Like 3 months tops.

**Comment by BenTheElder** [comment]
I don't see prow.k8s.io migrating this year as we're still figuring out how to run CI on AWS and while the run rate is vastly improved we overspent earlier this year, so I'm ambivalent about how aggressive the deadline is. We have however had open bugs about this for over a year with each remaining project and this bug is nearly 4 years old.


I think we also need to revisit the exceptions permitted, if we're permitting apisnoop and containerd, then you might argue for cadvisor as a node dep.

**Comment by dims** [comment]
+1 to document and have a process around exceptions.

**Comment by BenTheElder** [comment]
Reached out to my best guess at current owners for cadvisor, rules_k8s, k8s-cluster-bundle.

**Comment by ameukam** [comment]
Apisnoop is currently in transition to be Kubernetes sub-project:
  - https://github.com/kubernetes/org/issues/4705

**Comment by BenTheElder** [comment]
Will be finishing this shortly https://groups.google.com/a/kubernetes.io/g/dev/c/p6PAML90ZOU

I think https://github.com/GoogleCloudPlatform/k8s-cluster-bundle is the main one remaining after api snoop, unless we change our minds about closely related projects like cAdvisor, containerd.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/32089/ should pretty much wrap this up

**Comment by BenTheElder** [comment]
https://github.com/google/cadvisor/issues/3116 is probably the one follow-up at this point, will track there.

**Comment by BenTheElder** [comment]
Note: https://groups.google.com/a/kubernetes.io/g/dev/c/p6PAML90ZOU

**Comment by BenTheElder** [comment]
Follow-up discussion in https://github.com/kubernetes/k8s.io/issues/7709

Currently there is only containerd/containerd actively running (cadvisor is non functional, others were removed).
