### ISSUE TITLE
Migrate scalability test to use dedicated build cluster

### ISSUE THREAD

**Issue by oxddr** [kubernetes/test-infra#12867]
**What should be cleaned up or changed**:
Migrate existing scalability tests to use dedicated build cluster on prow. 

**Provide any links for context**:
As a workaround to https://github.com/kubernetes/test-infra/issues/11594 we've setup a dedicated build cluster for scalability tests. 

/assign oxddr

**Comment by oxddr** [comment]
As of now this is blocked by https://github.com/kubernetes/perf-tests/issues/553

**Comment by spiffxp** [comment]
Where do we stand with this?

**Comment by oxddr** [comment]
Both tests (performance and correctness) for 5k nodes clusters has been migrated.

There was an open discussion about what to do with other, smaller scalability tests. I'll discuss this with other scalability folks and come back to you tomorrow.

**Comment by oxddr** [comment]
/close

As discussed offline with @wojtek-t and @mm4tt we are not migrating any other scalability test to a dedicated build cluster. The effort (e.g. setting up Boskos) is not worth gain (not sure if there is any).
