### ISSUE TITLE
Batch and Serial Submit Queue Jobs are not blocking on the same test suite

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#1287]
Essentially the batch jobs are merging away happily and the Serial runs are failing as expected because of [1]. Please see details below:

Batch is testing "pull-kubernetes-e2e-gke-gci" (Looking at list of tests in https://k8s-gubernator.appspot.com/pr/batch) Whereas
Serial is testing "ci-kubernetes-e2e-gci-gke" (Looking at list of tests http://submit-queue.k8s.io/#/e2e)

Those 2 are totally different. This is a big problem because currently ci-kubernetes-e2e-gci-gke is totally broken, please see url below:
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/

Take an example run:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gke-gci/7650/build-log.txt
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/894/build-log.txt

And you will see that the first build log shows
```
W1203 08:08:12.256] + go run /workspace/e2e.go --check_version_skew=false -v --dump=/workspace/_artifacts --up '--ctl=version --match-server-version=false' --down --test --test_args=--ginkgo.focus=Guestbook --timeout=55m
```
and the second build log shows
```
W1203 08:14:58.650] + go run /workspace/e2e.go -v --dump=/workspace/_artifacts --check_leaked_resources --up '--ctl=version --match-server-version=false' --down --test '--test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]' --timeout=50m
```

We should make both Serial and Batch runs to test the same thing!

[1] https://github.com/kubernetes/kubernetes/issues/32947

**Comment by dims** [comment]
cc @k8s-oncall @saad-ali @rmmh

**Comment by fejta** [comment]
What is happening is that the GKE job is usually but not always failing. And every few hours when the GKE job passes we merge a few things.

Today the GKE job passed at 9:15a, 4a, midnight and 11p PST. https://k8s-testgrid.appspot.com/google-gke#gci-gke&width=20

That aligns with when the mergebot was active: https://github.com/kubernetes/kubernetes/commits/master

So we should definitely fix the GKE job, but the evidence I have suggests the SQ and batched merges are behaving as designed (only merging when ci blocking jobs are passing, whether serial or batched)

**Comment by dims** [comment]
Ack @fejta closing the issue
