### ISSUE TITLE
k8s-ci-robot request for a kube member to verify if ok test can be misinterpreted

### ISSUE THREAD

**Issue by henrynash** [kubernetes/test-infra#1289]
As a newbie doing my first pull request, I misinterpreted this.  When it said:

"Can a kubernetes member verify that this patch is reasonable to test? "

...I thought it was asking ME if I thought another kube member would be able to easily look at my change and decide if it was OK to test. So I promptly added the "@k8s-bot ok to test" comment, only to be told, of course, that I wasn't the member you were looking for :-) Maybe it would be clearer if it said something like:

"Waiting for a kubernetes member to verify that this patch is reasonable to test"

..or something like that.

**Comment by spxtr** [comment]
Hopefully that's better. Thanks for opening the issue and feel free to open another if you have any more problems.
