### ISSUE TITLE
verify-codegen.sh fails with a open /tmp/somefile: read-only file system error

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#12901]
**What happened**:

When executing the `hack/verify-codegen.sh` script locally, it consistently fails with an error like this:

```
Updating codegen files...
Generating DeepCopy() methods...
F0605 14:36:04.128621      22 main.go:82] Error: Failed executing generator: some packages had errors:
errors in package "k8s.io/test-infra/prow/apis/prowjobs/v1":
open /tmp/codegen.gopath.KlBE/src/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go: read-only file system

FAIL: @io_k8s_test_infra//hack:verify-codegen (see /home/alvaro/.cache/bazel/_bazel_alvaro/f3a7714e143469246038f58052b577df/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/testlogs/external/io_k8s_test_infra/hack/verify-codegen/test.log)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/assign @fejta

**Comment by alvaroaleman** [comment]
Not sure if of relevante, but my `/tmp` is a ramdisk, as its the case on most never linux distributions:

```
$ mount|grep /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
```

**Comment by fejta** [comment]
Okay have a repo, will see if I can resolve today...
