### ISSUE TITLE
ci-k8sio-cip job does not get run

### ISSUE THREAD

**Issue by listx** [kubernetes/test-infra#12903]
**What happened**:

Looking at https://prow.k8s.io/?job=ci-k8sio-cip, the job is no longer running. Looks like Prow tries to start it for 1 hour roughly before killing it. No logs are available...

**What you expected to happen**:

These jobs have been running daily for a while now, up until May 31. https://k8s-testgrid.appspot.com/sig-release-misc#ci-k8sio-cip

**How to reproduce it (as minimally and precisely as possible)**:

These jobs are supposed to run daily; so far they have been failing for the past few days.

**Please provide links to example occurrences, if any**:

Here's a link to a job where it did run (failed): https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-k8sio-cip/1134540311595323392

**Anything else we need to know?**:
Job definition: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L832

**Comment by krzyzacy** [comment]
maybe poke oncall while the job stays in pending state, and we can investigate why the pod cannot start

**Comment by listx** [comment]
/cc @fejta 

poke

**Comment by Katharine** [comment]
This was caused by the secret being called `k8s-artifacts-prod-service-account-creds`, but the job expecting it to be `k8s-artifacts-prod-service-account`. I've renamed the secret, and it works now.

**Comment by dims** [comment]
Thanks @Katharine !!! 😍
