### ISSUE TITLE
API to Request a test run/fetch results

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/test-infra#12916]
**What would you like to be added**:

Some sort of API (e.g. a REST API) to trigger jobs runs and view results.

**Why is this needed**:

I'd like to experiment around with GitHub actions for parts of our test automation for KubeBuilder -- particularly, they give an easy way to submit stuff against the checks API, since all GitHub actions get a GitHub Apps token.  However, actually running CI in an action would be suboptiomal, so what I'd like to do is use actions to trigger test runs, slurp the results, and submit them to the checks API in an action.

This could also mostly be accomplished via Checks API integration, but doing that properly seems like it'd be a bit more involved (#11889)

**Comment by stevekuznetsov** [comment]
You could possibly do this if you had rights to `POST /prowjobs` but I would rather see Prow support checks API first-class instead.

**Comment by DirectXMan12** [comment]
I would as well, just figured I'd throw this out there as an option.
