### ISSUE TITLE
Allow configuring secrecy on Jobs themselves

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#12936]
**What would you like to be added**:

Currently if a job is secret is determined based on the Refs it has and if it has any ref on a repository that is marked as secret. This doesn't always work well, because some jobs, especially periodics, may not have any ref at all but could still be secret.

Hence it would be nice if Jobs themselve would have a `isSecret` field or something which if set to true results in the job not shown by a Deck instance that doesn't show secret repos.

**Why is this needed**:

**Comment by stevekuznetsov** [comment]
By what mechanism do you suggest doing this? Just a label on the job?

**Comment by alvaroaleman** [comment]
Intuitively I was assuming a new boolean property on the job, but I guess a label would work as well

**Comment by alvaroaleman** [comment]
This got fixed by https://github.com/kubernetes/test-infra/pull/13444.

Please keep in mind thought that only jobs read from the kubeapi get hidde, the whole setting is completely ignored when reading data from GCS: https://github.com/kubernetes/test-infra/issues/13528
