### ISSUE TITLE
Plugin that blocks merge when PR contains binary files

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#12941]
**What would you like to be added**:

A plugin that detects when a PR contains binary files and adds a label and a message if thats the case to bock the merge of the PR.

**Why is this needed**:
To avoid accidentally checking in binary which pollutes the git history

/assign

**Comment by cblecker** [comment]
I can see this being good, but also there are plenty of "binary" things you make want to commit (images), so it would need to be overridable.

Also may just be easier to do this through gitignore *shrug*

**Comment by alvaroaleman** [comment]
> I can see this being good, but also there are plenty of "binary" things you make want to commit (images), so it would need to be overridable.

Makes sense.

> Also may just be easier to do this through gitignore shrug

It is possible to configure gitignore to ignore binaries? Or what do you mean?

**Comment by cblecker** [comment]
Well if you know the names of the binaries that get generated you can just add those file paths to gitignore to ensure that you don't accidentally add them to the tree.

**Comment by alvaroaleman** [comment]
/reopen
/unassign

This would be really nice to have, right now I do unfortunately not have the time for it
