### ISSUE TITLE
Git Client Endpoint Override Flag

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#12944]
**What would you like to be added**:
I would like to be able to override the default git endpoint with a flag or config parameter. The current default value is hard coded via constant. 

**Why is this needed**:
Without this we are only able to use prow with github.com repositories, we are unable to use prow with GitHub Enterprise repositories.

**Comment by chases2** [comment]
I know that some of the components will accept --github-endpoint=<your_enterprise_endpoint> as a flag already; it's inherited from prow's GitHub API library.

Can you clarify which commands don't seem to honor that flag?

**Comment by midnightconman** [comment]
Here is the line for the constant in `prow/git/git.go`: https://github.com/kubernetes/test-infra/blob/master/prow/git/git.go#L36

```
const github = "github.com"
```

This and some other items in the `git` client would need to be changed to allow prow to clone repos using the prow git client.

Some apps/plugins that use this client specifically are:
- mergecommitblocker
- verify-owners
- size
- tide
- cherrypicker
- buildifier
- repoowners
- golint

This was a simple grep, there might be more that use `git` client. :man_shrugging:

**Comment by midnightconman** [comment]
> Can you clarify which commands or cases don't seem to honor that flag?

Ohh, just to call it out... this is for the `prow/git` client, not the `prow/github` client. :smile:

**Comment by stevekuznetsov** [comment]
Potentially required as a first step: #11248
