### ISSUE TITLE
exempt branches with a regex from branch protection

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#12954]
**What would you like to be added**:
Allow for the exemption of certain branches from branch protection, based on matching a regex.

**Why is this needed**:
This would allow for easy deletion of branch accidentally created via GitHub's edit UI, as well as branches created by bots (such as GitHub's dependabot)

**Comment by nikhita** [comment]
> This would allow for easy deletion of branch accidentally created via GitHub's edit UI, as well as branches created by bots (such as GitHub's dependabot)

If `enforce_admins: true` is not used, I think this can be done today as well i.e. we won't need to disable branch protection to delete a branch.

For example, I see the option to delete all branches here - https://github.com/kubernetes/publishing-bot/settings/branches

**Comment by cblecker** [comment]
@nikhita Those delete buttons are just to delete the branch protection rules themselves. The actual branch list is here: https://github.com/kubernetes/publishing-bot/branches. All the branches have the little lock symbol, and the trash can is greyed out.

**Comment by nikhita** [comment]
> Those delete buttons are just to delete the branch protection rules themselves. 

Ah, right! :woman_facepalming:
