### ISSUE TITLE
Deprecated experimental_remote_spawn_cache

### ISSUE THREAD

**Issue by amwat** [kubernetes/test-infra#12976]
Greenhouse uses deprecated (in bazel 0.24.0 https://github.com/bazelbuild/bazel/pull/7813 ) `--experimental_remote_spawn_cache`

https://github.com/kubernetes/test-infra/blob/master/images/bootstrap/create_bazel_cache_rcs.sh#L79

/cc @BenTheElder

**Comment by BenTheElder** [comment]
> This flag has already been enabled by default and deprecated for a while - there is no associated logic present, therefore removing it.

we can just remove the flag

**Comment by BenTheElder** [comment]
should be fixed by https://github.com/kubernetes/test-infra/pull/12977
