### ISSUE TITLE
label_sync not fully syncing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#13001]
**What happened**: @timothysc reported that https://github.com/kubernetes-sigs/cluster-api has ~1/2 of the labels not synced

**What you expected to happen**: the labels should be synced

**How to reproduce it (as minimally and precisely as possible)**: ...

**Please provide links to example occurrences, if any**: :man_shrugging: 

**Anything else we need to know?**: The job is here https://prow.k8s.io/?job=ci-test-infra-label-sync I can't discern anything useful from the logs so far. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-test-infra-label-sync/1138873066789539841

**Comment by BenTheElder** [comment]
per https://github.com/kubernetes/test-infra/blob/3b7178f54964d45426ef34d97ab725e5cd1d0ca3/label_sync/OWNERS#L5-L8

/assign @cblecker @spiffxp @fejta

**Comment by timothysc** [comment]
cc @timothysc

**Comment by spiffxp** [comment]
@timothysc what's an example of a label you're expecting to see synced that isn't?

**Comment by cblecker** [comment]
Yeah, I'm not sure I see any that aren't synced

Label list: https://github.com/kubernetes-sigs/cluster-api/labels

**Comment by timothysc** [comment]
folks manually added some of the labels, but if you look at the color coding it's all messed up.

**Comment by stevekuznetsov** [comment]
Which labels? Looking at the repo now no labels seem wrong. The job linked by Ben actually took no action to sync since everything seemed up-to-date as it was.

**Comment by timothysc** [comment]
all the area/* labels are green on capi, b/c someone manually added them.

**Comment by spiffxp** [comment]
I see, the request is for everything to be the same shade of blue.  The labels are specified to be a different color in labels.yaml, so the tool is WAI.  I opened https://github.com/kubernetes/test-infra/pull/13017 to fix the colors.

We don't really have anything in place to enforce label style conventions (or DRY up the config to reduce opportunities for entropy)

**Comment by timothysc** [comment]
Well the syncing wasn't working, so folks created labels, now the labels are all "special"

**Comment by spiffxp** [comment]
The labels are present in labels.yaml right now https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md#labels-that-apply-to-kubernetes-sigscluster-api-for-both-issues-and-prs

When the were added to labels.yaml (https://github.com/kubernetes/test-infra/pull/12949) they were added with custom colors.  The next run after merge mentions syncing those labels (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-test-infra-label-sync/1137106340364161024/build-log.txt)

So, WAI.  I think documenting / enforcing style conventions would be a good idea though

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/issues/13018 for style enforcement
