### ISSUE TITLE
kubetest work without needing to build or download kubernetes

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#13029]
**What would you like to be added**:

Make kubetest work when `--extract` and `--build` are not provided. Currently it would fail at this line:
https://github.com/kubernetes/test-infra/blob/befcf27357a9c85cbe97a93fdcd1bdf29da89028/kubetest/main.go#L211

**Why is this needed**:

In Prow instance set up in orgs other than kubernetes, kubernetes builds might not be necessarily needed, so it would be nice if kubetest can support this

**Comment by BenTheElder** [comment]
sen: are the kubetest owners interested in supporting this, or at least clarifying what is supported?

**Comment by krzyzacy** [comment]
Feel free to send PRs to make this to work with your use cases :-) There's nobody actively working on kubetest/kubetest2 right now.

**Comment by chaodaiG** [comment]
This is not a priority for us at the moment, and might not be in the future either. Since https://github.com/knative/test-infra/issues/1186 will likely move us away from using `kubetest`
