### ISSUE TITLE
spyglass: junit: UX for viewing output sometimes poor

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#13036]
On [this job page](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/23171/pull-ci-openshift-origin-master-unit/7794), there is a failed jUnit test:

![Screenshot from 2019-06-14 08-21-47](https://user-images.githubusercontent.com/7328370/59519862-a9a91f00-8e7d-11e9-82ef-2530b1e799d2.png)

However, that shows very little information and shows a link to see more. Clicking that, I get a new browser page with:

![Screenshot from 2019-06-14 08-22-02](https://user-images.githubusercontent.com/7328370/59519915-be85b280-8e7d-11e9-8ef0-db7000ea6988.png)

However, the jUnit test directly above that shows about ten times as much output to stdout/stderr without eliding or needing the click. What causes the difference in handling for these two cases?

/area prow/deck
/area prow/deck/spyglass
/cc @cjwagner @Katharine @fejta

**Comment by Katharine** [comment]
The dropdown you get is from the JUnit `<failure>` element; the link gives you the output from the JUnit `<system-out>` element. Ideally, your `<failure>` would contain a concise summary of the error. We don't show all of `<system-out>` directly because it is frequently very long and mostly irrelevant.

As for what causes your files to be generated that way, I cannot say.

**Comment by stevekuznetsov** [comment]
@Katharine thanks! As you note, our XML looks like:

```xml
<testcase name="TestCredentialsForSecrets" time="0">
    <failure message="=== RUN   TestCredentialsForSecrets
--- FAIL: Test ...">
        === RUN   TestCredentialsForSecrets
        --- FAIL: Test ...
    </failure>
    <system-out>
        === RUN   TestCredentialsForSecrets
        --- FAIL: TestCredentialsForSecrets (0.00s)
            credentials_test.go:22: open ../../../test/testdata/image-secrets.json: no such file or directory
    </system-out>
</testcase>
```
