### ISSUE TITLE
skip gce* tests when only k/cmd/kubeadm is touched

### ISSUE THREAD

**Issue by neolit123** [kubernetes/test-infra#13032]
so i had the idea for a while, to make the following jobs skip if a PR is only touching `cmd/kubeadm` in `kubernetes/kubernetes`.

```
pull-kubernetes-e2e-gce-100-performance
pull-kubernetes-e2e-gce
pull-kubernetes-e2e-gce-device-plugin-gpu
pull-kubernetes-kubemark-e2e-gce-big
```

my rationale is that these jobs run kube-up tests  on kubeadm deployer changes, which doesn't make sense. i think ideally we should skip them if the PR is **only** touching `cmd/kubeadm` and run `kind` presubmit instead.

this can be in place until kubeadm moves out of tree.

to my understanding negating a match however is not that easy.
[run_if_changed](https://github.com/kubernetes/test-infra/blob/master/prow/config/jobs.go#L207-L213) runs a job if one of the touched paths matches.

but you cannot use negative lookahead in golang `^((?!foo).)*$`,
which means that a new prow config field is required?

quick idea is: add `skip_if_only_changed` (not a great name) and error out if both that and `run_if_changed` are used.

#### so the tasks would be:
- extend prow to support such a functionality
- add the `skip_if_only_changed` fields to the above presubmit jobs + set `always_run: false`
- enable the kubeadm/kind presubmits to always run on `cmd/kubeadm` changes.

pros:
- skips running heavy tests on kubeadm PRs
- enables kubeadm presubmits

cons:
- complicates the prow config with additional regexp and fields.

@spiffxp please feel free to close if this is a no-go.

/assign @spiffxp @timothysc @neolit123
cc @fabriziopandini @BenTheElder 

/sig cluster-lifecycle
/sig testing
/kind feature
/priority backlog

**Comment by BenTheElder** [comment]
It's possible to accomplish this with a clever run_if_changed regex without lookahead :-)

I will say it has generally been a footgun to run tests based on file path regexes because they're generally not precise enough but this sounds simple enough.

**Comment by neolit123** [comment]
> It's possible to accomplish this with a clever run_if_changed regex without lookahead

i know, but from what i tested it ain't going to be pretty. :)

**Comment by BenTheElder** [comment]
from last time this came up:
https://play.golang.org/p/cmPlf-Ro_y9
```
# don't run if only docs/*
run_if_changed: (^[^d].*$)|(^.[^o].*$)|(^..[^c].*$)|(^...[^s].*$)|(^....[^/].*$)|(^[^d][^o][^c][^s]/.*$)
```

it's really not so bad, you just need a sliding window from the start over banning a single of the characters in it's position from the blacklisted prefix, and then the entire prefix.

**Comment by neolit123** [comment]
heh, starts to resemble [this](https://en.wikipedia.org/wiki/Brainfuck#Hello_World!)

**Comment by neolit123** [comment]
/close
moving kubeadm out instead.
