### ISSUE TITLE
Planter NOK with Podman instead of Docker on Fedora

### ISSUE THREAD

**Issue by vorburger** [kubernetes/test-infra#13044]
**What happened**:
Build Failures when running e.g. `../test-infra/planter/planter.sh bazel build //cmd/kubectl` [as suggested here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/bazel.md#planter) on a Fedora 30 with `podman` instead of `docker`.

**What you expected to happen**:
 I guess i expected build/run.sh as advertised in the README? smile

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Fedora 30 Server
1. sudo dnf install podman-docker
1. git clone https://github.com/kubernetes/test-infra.git
1. git clone https://github.com/kubernetes/kubernetes.git 
1. cd kubernetes
1. ../test-infra/planter/planter.sh bazel build //cmd/kubectl

There are probably a series of several (small) problems:

1. `Error: Invalid --security-opt 1: "label:disable"`
2. `Error: invalid option type "delegated"`

**Comment by vorburger** [comment]
> 1. Error: Invalid --security-opt 1: "label:disable"

seems to be related to https://github.com/containers/skopeo/issues/567, and #13045 fixes that for me.

> 2. Error: invalid option type "delegated"

probably related to https://github.com/containers/libpod/issues/3340

**Comment by BenTheElder** [comment]
> I guess i expected build/run.sh as advertised in the README? smile

?
---

Note that this is definitely not tested with podman and is mostly in maintenance mode, I no longer use this and ixdy no longer works on Kubernetes actively. We haven't seen terribly many active users of this tool. 
I would seriously consider https://github.com/bazelbuild/bazelisk moving forward if you're using linux. :sweat:

**Comment by BenTheElder** [comment]
is this still an issue? also not sure what the `build/run.sh` reference is.

**Comment by vorburger** [comment]
> Note that this is definitely not tested with podman and is mostly in maintenance mode, I no longer use this and ixdy no longer works on Kubernetes actively. We haven't seen terribly many active users of this tool.

OK, learning here.. I just blindly followed where First Contact README doc was taking me.

> I would seriously consider https://github.com/bazelbuild/bazelisk moving forward if you're using linux

interesting, didn't know. If I understand correctly, that just saves you the initial `dnf copr enable vbatts/bazel; sudo dnf install bazel`, am I getting this right, or is there more to it than that?  (The problems I ran into here were when initially trying to build K8s (itself, from source) inside a container. When I realized that was a path not much threaded, I've moved to building it on the host, and that, obviously, worked smoothly.)

> is this still an issue? 

I take absolutely no offense if you close this. It's not blocking me at all.

I'm hesitant to "just" close it myself already - because _Planter is (still) NOK with Podman instead of Docker on Fedora..._ :smile_cat: and Podman maintainers have been (very) reactive to fix related problems, note https://github.com/containers/libpod/issues/3340 and https://github.com/containers/buildah/issues/1675.

> also not sure what the `build/run.sh` reference is.

I meant [this here](https://github.com/kubernetes/kubernetes/blob/1493757d69a8e0032128a5dadc56b168b00a6519/build/README.md#key-scripts) but copy/pasted from another issue I had opened - ignore.

**Comment by BenTheElder** [comment]
> interesting, didn't know. If I understand correctly, that just saves you the initial dnf copr enable vbatts/bazel; sudo dnf install bazel, 

More than that, it's a launcher for various versions. You'll need to switch if you go to an older Kubernetes release for example. One of the main motivations for planter was trivially being able to use different versions.

> I'm hesitant to "just" close it myself already - because Planter is (still) NOK with Podman instead of Docker on Fedora... 😸 and Podman maintainers have been (very) reactive to fix related problems, note containers/libpod#3340 and containers/buildah#1675.

Sure, please keep it open until it is fixed. It looked like it might have been complete and there were no further comments :-)
