### ISSUE TITLE
prow: hook: poor ux with invalid /test and /retest commands

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#13059]
As a developer interacting with Prow,
I want to get feedback when I've issued a command that could not be parsed
So that I can fix my command and get the service to do what I intended

Examples of comment commands that should generate an error message in a comment response:

 - `/test` with no target
 - `/retest` with trailing words
 - `/test` with a target that is not recognized

/area prow/hook
/good-first-issue
/help
/cc @spiffxp @cblecker @nikhita

**Comment by cblecker** [comment]
Is this something the generic command framework would do? Is it worth waiting, or is this simple to do in trigger as it is?

**Comment by stevekuznetsov** [comment]
I think it would be better implemented with per-plugin logic anyway, I want to see something like:

> @user: to request testing, provide a test name like `/test test-name`

Or 

> @user: no test `fake-test` was found for the `oops` branch on this repo, please select a test from the following options
> - `unit`
> - `integration`

etc. 

The framework would have to expose hooks for intelligent responses, so the amount of work taken should be similar in both cases. Changing `trigger` to do this today should not be too hard.

**Comment by nikhita** [comment]
For anyone interested to take this up, the trigger plugin is here: https://github.com/kubernetes/test-infra/tree/master/prow/plugins/trigger

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/16926
/close
