### ISSUE TITLE
Prow Sub: Allow execute prowjob defined from payload

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#13076]
For trusted users, I want to allow us just craft a job config definition via pubsub payload, and run that job. Running existing periodics from existing config is pretty limited.

This will be guarded under a config flag.

cc @sebastienvas @fejta @cjwagner @stevekuznetsov in case you have concerns.
/assign

**Comment by stevekuznetsov** [comment]
Confused as to what the ask here is -- if we are trying to trigger new instances of a job to run, we should reuse the work that @mirandachrist is doing in `deck`.

If we want to run arbitrary ProwJobs, why not `mkpj`?

**Comment by krzyzacy** [comment]
^^ because I need to run it from somewhere that mkpj is not available :joy: And I also need wait for the result to come back

**Comment by stevekuznetsov** [comment]
So what are you actually suggesting? A new controller that subscribes to pub/sub and creates ProwJob as they come in? Could you use the `deck` API if it is built?

**Comment by krzyzacy** [comment]
I'm thinking of expanding https://github.com/kubernetes/test-infra/blob/master/prow/pubsub/subscriber/subscriber.go#L143 to take in a new event

**Comment by Katharine** [comment]
I am not excited about exposing the ability to create arbitrary jobs to the internet with any sort of security written by us in front of it, so I would oppose building a deck API that is capable of supporting the general version of this use-case.

**Comment by stevekuznetsov** [comment]
Aside from "create this arbitrary ProwJob YAML" -- supporting "re-run this job" or "run this job" via some authenticated endpoint is necessary for @mirandachrist work, are you opposed to that as well?

@krzyzacy I would rather not see this exposed via an API for `deck` as well as one over pub/sub

**Comment by krzyzacy** [comment]
Well... how about I step back, by just allowing pubsub to patch existing job configs via env vars

**Comment by stevekuznetsov** [comment]
What are you actually tying to achieve? Triggering new runs of periodics?

**Comment by krzyzacy** [comment]
from @sebastienvas that's already supported, I'm gonna just try it out.

@stevekuznetsov basically I need to trigger a periodic with generated args from other systems that cannot be hard-coded into the config

**Comment by Katharine** [comment]
> Aside from "create this arbitrary ProwJob YAML" -- supporting "re-run this job" or "run this job" via some authenticated endpoint is necessary for @mirandachrist work, are you opposed to that as well?

Tangential to this issue, but no, the risk is lower without the freedom of creating arbitrary jobs (but I do want to review every PR related to it - there are [important details] (https://github.com/kubernetes/test-infra/pull/12827#issuecomment-502850414))

**Comment by stevekuznetsov** [comment]
> basically I need to trigger a periodic with generated args from other systems that cannot be hard-coded into the config

So two comments:

1. If we want to support jobs that have trigger-time  parameters, we need to do that in its entirety and intentionally, with a design that would help the ecosystem adopt the new approach.
2. Due to the complexity of the details for the first point, when OpenShift needed these types of jobs we implemented our own code that creates ProwJobs using the appropriate credentials in the cluster that allow it to (the equivalent of `mkpj`). If we do not want to tackle the first point I would suggest that others who need this type of implementation also develop out-of-band. 

In general I do not really want to see a one-off approach to triggering some types of jobs in one manner via one controller as it makes interfacing with Prow less cohesive.

**Comment by krzyzacy** [comment]
needs better design & overall thoughts, retreat now
