### ISSUE TITLE
prow/owners-label: owners-label should respect OwnersDirBlacklist

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#13110]
**What happened**:
Similar to https://github.com/kubernetes/test-infra/pull/12460, `owners-label` should respect the OwnersDirBlacklist.

**What you expected to happen**:
Don't label a PR based on a vendor update.

**How to reproduce it (as minimally and precisely as possible)**:
vendor an owners file with a label statement

**Please provide links to example occurrences, if any**:
https://github.com/kubernetes/kube-state-metrics/pull/798

**Anything else we need to know?**:

**Comment by cjwagner** [comment]
If we make the `repoowners` package handle this when loading the OWNERS files then we won't have to update every consumer of OWNERS files.

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/12460. Tested in https://github.com/kubernetes/kubernetes/pull/80396.

/close
