### ISSUE TITLE
The tide "not mergeable" status should use a colon, not a full stop

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#13155]
Tide statuses read like "Not mergeable. Some explanation."

Aside from being poor grammar, it's also confusing - it suggests that it's not mergeable (e.g. due to a merge conflict) _and also_ "some explanation".

It should instead read "Not mergeable: some explanation." This makes it clear that the explanation is about why it's not mergeable. It also reads better.

**Comment by stevekuznetsov** [comment]
Currently that's to support the case where there is no reason, to allow the full reason to be `"Not mergeable."` Agreed that's suboptimal

**Comment by Katharine** [comment]
Should have logic to figure out the correct punctuation!

I filed this issue after someone was actually confused by it.

**Comment by Katharine** [comment]
Alternatively, always use a colon and default to "Not mergeable: ????", which is probably what the users are thinking anyway.

**Comment by cjwagner** [comment]
I wonder if status context description text will display emojis. Emojis don't need punctuation.

**Comment by Katharine** [comment]
I still care! This should not be hard to fix, either.

/remove-lifecycle stale
