### ISSUE TITLE
e2e.go can fail without creating junit failures

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1316]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress-release-1.5/852/

```
W1206 10:38:42.302] 2016/12/06 10:38:42 e2e.go:227: Something went wrong: encountered 1 errors: [error running get nodes: exit status 1]
```

However it looks like none of the test cases in https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress-release-1.5/852/artifacts/junit_runner.xml failed. We should ensure this doesn't happen.

**Comment by spxtr** [comment]
https://github.com/kubernetes/kubernetes/blob/master/hack/e2e.go#L294

This isn't `xmlWrap`ped.
