### ISSUE TITLE
Update pylint to latest python2 version (1.9.4)

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13163]
/help
/good-first-issue

1) Change
  -  https://github.com/kubernetes/test-infra/blob/4a79c95955a670b16d2c96d397860bf511645153/requirements.txt#L16
  - to https://pypi.org/project/pylint/1.9.4/ or a later version that works with 
2) `bazel test //hack:verify-pylint` and fix resulting lint errors

**Comment by clarketm** [comment]
`pylint` was upgraded to version `1.9.4` at commit 8b44ac45f32ed7efda0e6a9bb0aefb8b670db4ed

/close
