### ISSUE TITLE
Stop assigning suite failures to test-infra team

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1317]
If we have test cases, it isn't test-infra.

**Comment by fejta** [comment]
If there are N test cases run we should figure out the set of people assigned to those N bugs and assign the suite failure to them.

**Comment by krzyzacy** [comment]
should we add back owners for each job?

**Comment by fejta** [comment]
Sounds reasonable to me. Also somewhat orthogonal?

**Comment by krzyzacy** [comment]
not all jobs have owners, we need to make things up :-) we can discuss tomorrow

**Comment by fejta** [comment]
/unassign @rmmh 
/assign @cjwagner 
Solved, finally!
