### ISSUE TITLE
Use Bazelisk instead of bazel images in CI?

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#13187]
**What would you like to be added**:
If we used [Bazelisk](https://github.com/bazelbuild/bazelisk) in CI instead of using bazel images with a specific version of bazel we could more easily switch versions of bazel because our CI jobs would use the version defined in [`.bazelversion`](https://github.com/kubernetes/test-infra/blob/master/.bazelversion) without requiring an image bump.  If we cache the most recent bazel version in the image we'll still want to publish a new image with an updated cache, but jobs would not fail in the interim, just run more slowly. 

**Why is this needed**:
It isn't, but we've had a lot of problems with bazel versioning and this might help. This kind of smells, but it is something to consider.

@fejta @Katharine @stevekuznetsov @chases2

**Comment by BenTheElder** [comment]
Being able to file a PR to test arbitrary versions would be pretty nice. We could add bazelisk to the relevant images and just symlink `bazel` to `bazelisk` in PATH.

**Comment by BenTheElder** [comment]
I think we're not going to do this for now...
/close
