### ISSUE TITLE
Crier pubsub reporter adds gubernator link in GCS path

### ISSUE THREAD

**Issue by srinivashegde86** [kubernetes/test-infra#13211]
**What happened**:
GCS path in crier pubsub report has a gubernator link. Eg. "gcs_path":"gs://https://gubernator.knative.dev/build/knative-prow/logs/ci-knative-eventing-go-coverage/1140786425130651648/

**What you expected to happen**:
gubernator should not be present in the link. It should be:
"gcs_path":"gs://knative-prow/logs/ci-knative-eventing-go-coverage/1140786425130651648/

**How to reproduce it (as minimally and precisely as possible)**:
Read a message using the prow crier subscriber

**Anything else we need to know?**:
We found this when using the reporter in knative. We were using gubernator, but we are in the process of deprecating that and using spyglass.

**Comment by srinivashegde86** [comment]
This can also be prow.knative.dev, if one is using spyglass instead of gubernator

"gcs_path":"gs://https://prow.knative.dev/build/knative-prow/logs/ci-knative-eventing-go-coverage/1140786425130651648/

**Comment by krzyzacy** [comment]
@srinivashegde86 looks like https://github.com/kubernetes/test-infra/pull/11398 changed the behavior, I think you need to change that config field accordingly, in your repo.

**Comment by krzyzacy** [comment]
/unassign
cc alvaroaleman 
/assign srinivashegde86

**Comment by srinivashegde86** [comment]
We dont use job_url_config in our prow instance - https://github.com/knative/test-infra/blob/305effb104f097b12ccecabd0f5dfccfcbd2bf84/ci/prow/config.yaml#L21

**Comment by krzyzacy** [comment]
@srinivashegde86 which probably means it never worked? You can add `job_url_prefix_config` to your config and I bet it would fix your problem.

**Comment by krzyzacy** [comment]
cc @cjwagner

**Comment by cjwagner** [comment]
I think the issue is that this line is wrong, in particular if the job URL is generated from the report template instead of using a job url prefix: https://github.com/kubernetes/test-infra/blob/a38158ced61c30b36b77309babbeebd0dd438aac/prow/pubsub/reporter/reporter.go#L139
https://github.com/kubernetes/test-infra/blob/a38158ced61c30b36b77309babbeebd0dd438aac/prow/pjutil/pjutil.go#L265-L285

**Comment by krzyzacy** [comment]
emmm, but we haven't migrate away from report template yet
