### ISSUE TITLE
Make it easier to run bazel in a container

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13228]
For people who do not have or want access to an RBE cluster, bazel allows spawning into a docker container. This should produce more consistent results across machines as well as on/off rbe:

Most likely out of date docs here: https://docs.bazel.build/versions/master/remote-execution-sandbox.html

/help

**Comment by spiffxp** [comment]
/remove-help
It's unclear to me what you're asking for specifically here

We have https://github.com/kubernetes/test-infra/tree/master/planter, would this be about updating planter or doing something completely different?

**Comment by BenTheElder** [comment]
is this referring to bazel NOT in a container on the host but the actions running in a container as the sandbox mode?
