### ISSUE TITLE
Setup RBE for trusted jobs

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13232]
The caching we get with this is worth it. Also more secure as we run less stuff inside the containers

**Comment by BenTheElder** [comment]
SGTM - ping

**Comment by chases2** [comment]
@fejta Why is this on the oncall hotlist? This sounds like a major enhancement

**Comment by fejta** [comment]
You can take it off. Sitting around waiting for jobs to complete is the primary source of pain during my shifts, so I added it to mitigate that.

Other people seem to encounter other snags
