### ISSUE TITLE
Flakyness specification for prow

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/test-infra#13266]
**What would you like to be added**:

It would be awesome if jobs gets automatically retriggered if considered as flaky. So we could do an automatic retest with some spec addition like:
```
flakeAttempts: 3
```

WDYT?

**Why is this needed**:

Huge tests scenarios are sometimes flaky because of network issues, which can be hard to tackle. To avoid multiple `/retest`s on PRs, we could simply do that automatically. 😇

**Comment by spiffxp** [comment]
I would rather not encourage this pattern.  We should motivate people to fix or triage flakes away from the critical path, not just wait longer.

ref: https://github.com/kubernetes/kubernetes/issues/68091

**Comment by saschagrunert** [comment]
Okay closing as not wanted. :)
