### ISSUE TITLE
prow: hook: label plugin has bad UX when unsupported labels requested, no help text

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#13276]
The `/label` command is not exposed in the command help page. The list of examples should be updated here:

https://github.com/kubernetes/test-infra/blob/eb4a109306acfe76aa14676d91507fe313e7178e/prow/plugins/label/label.go#L69

When used with a label that is not supported by the explicit list, `/label` plugin does nothing -- it should instead comment back with an error and a list of possible labels. When we find no label or the label found does not match, we should comment:

https://github.com/kubernetes/test-infra/blob/eb4a109306acfe76aa14676d91507fe313e7178e/prow/plugins/label/label.go#L106-L108

https://github.com/kubernetes/test-infra/blob/eb4a109306acfe76aa14676d91507fe313e7178e/prow/plugins/label/label.go#L187-L190

/area prow/hook
/cc @cjwagner @fejta @Katharine @cblecker @nikhita @grodrigues3 

We need a UX type label.
/help
/good-first-issue

**Comment by nicoaragon** [comment]
Filed [test-infra/pull/14038](https://github.com/kubernetes/test-infra/pull/14038).
