### ISSUE TITLE
pull-test-infra-bazel failing verify-deps

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13281]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/test-infra/13279/pull-test-infra-bazel/1145773339738902529

github.com/jinzhu/now v0.0.0-20181116074157-8ec929ed50c3 // indirect

/cc @chases2 @cjwagner

**Comment by fejta** [comment]
Possibly fixed by https://github.com/kubernetes/test-infra/pull/13269

**Comment by chases2** [comment]
Fix #13269 seems to work locally; I'm pushing the merge to a previously-failing PR to see if it works there

**Comment by fejta** [comment]
/assign @justaugustus 
/close
Thanks!

**Comment by chases2** [comment]
Note:
#13214 [was failing](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/test-infra/13214/pull-test-infra-bazel/1145784157922660353) due to this issue, but is no longer failing after pushing the change commit
