### ISSUE TITLE
mkpj panics when more than one job has the same name

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#13280]
**What happened**:
```
mkpj --job integ-framework-k8s --config-path config.yaml
WARN[0000] empty -github-token-path, will use anonymous github client
panic: runtime error: index out of range

goroutine 1 [running]:
main.(*options).defaultPR(0xc0005411e8, 0xc000540f58, 0xc000055b90, 0x0)
        /usr/local/google/home/howardjohn/go/src/k8s.io/test-infra/prow/cmd/mkpj/main.go:70 +0x2b8
main.main()
        /usr/local/google/home/howardjohn/go/src/k8s.io/test-infra/prow/cmd/mkpj/main.go:256 +0x145f
```

**What you expected to happen**:
`mkpj` doesn't panic or fails graceful and indicates what I need to do. Is github token path required? Am I missing some other flag?

I installed with `go get -u k8s.io/test-infra/prow/cmd/mkpj`
The code crashing is the first line of this:

```go

func (o *options) defaultPR(pjs *prowapi.ProwJobSpec) error {
	if pjs.Refs.Pulls[0].Number == 0 { // CRASH HERE
		fmt.Fprint(os.Stderr, "PR Number: ")
		var pullNumber int
		fmt.Scanln(&pullNumber)
		pjs.Refs.Pulls[0].Number = pullNumber
		o.pullNumber = pullNumber
	}
	if pjs.Refs.Pulls[0].Author == "" {
		pr, err := o.getPullRequest()
		if err != nil {
			return err
		}
		pjs.Refs.Pulls[0].Author = pr.User.Login
	}
	if pjs.Refs.Pulls[0].SHA == "" {
		pr, err := o.getPullRequest()
		if err != nil {
			return err
		}
		pjs.Refs.Pulls[0].SHA = pr.Head.SHA
	}
	return nil
}
```

**Comment by howardjohn** [comment]
Passing ` --github-token-path secrets/.oauth-token` still gets the same crash

**Comment by bbguimaraes** [comment]
My guess is you have more than one job with that name, at least one of them being a pre-submit and one of another type.

https://github.com/kubernetes/test-infra/blob/a38158ced61c30b36b77309babbeebd0dd438aac/prow/cmd/mkpj/main.go#L195-L251

If the pre-submit is found first, `needsPR` will be set. When the other job with the same name is found, `pjs` will become a spec with no `Refs.Pulls` and cause L70 to fail.

`needsBaseRef` has the same problem.

**Comment by howardjohn** [comment]
You are right, I do have it in postsubmit and presubmit

**Comment by stevekuznetsov** [comment]
Yeah you should not have more than one job with the same name

**Comment by cjwagner** [comment]
> /cc @cjwagner we should just enforce unique names on config load -.-

https://github.com/kubernetes/test-infra/issues/9948
