### ISSUE TITLE
Enhance Command Arguments & Output To File in Entomologist

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#13305]
**What would you like to be added**:
[Entomologist](https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/entomologist) is a program in TestGrid that identifies particular GitHub comments and serializes that data and _sends it to GCS_ for consumption by TestGrid. It is designed to run either as a one-shot, or _once an hour_ until terminated.

There are two enhancements:
- [x] Modify the "output" argument so that you can put the serialized data on a local file instead of in the cloud. An example of this is in [Configurator](https://github.com/kubernetes/test-infra/blob/2451842221e3a5a7923b544e9a739f8c7ddb5881/testgrid/cmd/configurator/main.go#L64)
- [ ] Add an argument that allows you to specify how often the program polls

**Why is this needed**:
- Allowing a human to output the file to local disk will help with debugging the proto generation without "live-firing" into the cloud
- One hour was a blind guess based on how often GitHub tokens refresh. Actual production use may require tuning.  

/help-wanted
/good-first-issue

**Comment by fediazgon** [comment]
I would like to work on this one. Thank you very much for the detailed explanation.

/assign @fediazgon

**Comment by chases2** [comment]
Edit: #13512 partially resolves this issue; thanks!
