### ISSUE TITLE
Run Prow for project integration and unit testing (e.g yarn test)

### ISSUE THREAD

**Issue by gentitope** [kubernetes/test-infra#13345]
I need an idea on to integrate my project with prow for integration and unit testing.

**What would you like to be added**:

**Why is this needed**:

**Comment by cjwagner** [comment]
Please see the docs for [Prow](https://github.com/kubernetes/test-infra/tree/master/prow#documentation) and [creating ProwJobs](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md). If you have a question that the docs don't answer please open a more specific issue or reach out on the Kubernetes slack.
/close
