### ISSUE TITLE
Nested Virtualization Support for prow.k8s.io

### ISSUE THREAD

**Issue by moshloop** [kubernetes/test-infra#13341]
A number of different projects would benefit from nested virtualization (NV) support:

* https://github.com/kubernetes-sigs/image-builder
* https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm 
* https://github.com/kubernetes-sigs/kubespray - Currently using KubeVirt on packet
* https://github.com/kubernetes-sigs/node-feature-discovery ?

GCP does support [nested virtualization](https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances) so this is *technically* feasible.

The real question is if this is *practically* feasible, I see 3 potential options:

1) NV becomes a first-class citizen that any prow job can request - I think this would require a new GCP cluster managed by something like kops, (Unless GKE supports custom licensed images?)
2) NV becomes a second-class citizen on an external CI system like AppVeyor that supports NV already, managed and owned by test-infra
3) NV is unsupported and projects would need to manage and own it themselves

/cc @timothysc @justinsb

**Comment by timothysc** [comment]
@spiffxp @BenTheElder ?

**Comment by BenTheElder** [comment]
I don't run the clusters currently so I can't speak to that with any authority, but previously the response was only to use GKE because of time saved to the team running Prow.

This is in part why we have [kind](https://sigs.k8s.io/kind). @munnerz also used to run a Prow with nested virtualization for Jetstack and switched off of this because it had a lot of problems (eg you can leak resources easily).

Generally test-infra has preferred to keep things ~containerized for the reliable cleanup of resources (provided by Kubernetes of course...).

**Comment by BenTheElder** [comment]
When a job really does need a VM so far test-infra has recommended spinning up a GCE or AWS VM from the ProwJob as the project has separate ~reliable infrastructure to lease projects and nuke everything in them after the job is done. (see boskos/).

**Comment by stevekuznetsov** [comment]
Running nested virt using credentials to set it up in separate cloud computing infrastructure from the service/build clusters that Prow schedules to is possible today. Not sure this requires any changes to prow, even if the request is for nested virt on the build cluster itself.

**Comment by moshloop** [comment]
So this request would be for a *new* build cluster with nested virtualization - I think spinning up new VM's for each job kind of defeats the purpose of nested virtualization in the first place. 
Could we not create new boskos resource for this ?

**Comment by BenTheElder** [comment]
> So this request would be for a new build cluster with nested virtualization 

You'll need to get the prow.k8s.io oncall team to agree to this, or provide your own. I would bring this up in #testing-ops on the kubernetes slack.

> I think spinning up new VM's for each job kind of defeats the purpose of nested virtualization in the first place.

it of course depends on the use case. it might for yours, but it would still _work_ with what is available today.

> Could we not create new boskos resource for this ?

You'd need to come up with a pattern to manage this. boskos has a "janitor" for GCP projects / AWS regions /... today that knows to simply list and delete any sub-resource when the project / region / ... is done being used. With nested VMs that's going to be trickier unless you do something like only one VM to a machine which ... that's not much better than spinning up a VM remotely.

**Comment by moshloop** [comment]
> get the prow.k8s.io oncall team to agree to this

This doesn't need the same level of support as core prow jobs, I would be able to provide oncall with   a 1 - 2 business day response time. 

> only one VM to a machine

One Nested Virtualization Host (VM) per job and one host per GCP project would be fine as it would meet the primary goals:

a) Reduce the amount of boiler-plate / bootstrapping required to run a job required NV
b) Make running NV jobs fast by keeping a pool of pre-warmed vm's

**Comment by LorbusChris** [comment]
I'm still interested in this.
/reopen

**Comment by BenTheElder** [comment]
We're not going to do this on the default build nodes (it's not possible in
GKE AND we don't want to deal with leaked VMs), but you could spin up a GCE
vm with nested virt from a boskos project in your prowjobs and do whatever
you want there.
