### ISSUE TITLE
generate_tests.py has no verification test

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#13353]
**What would you like to be added**:
A test, similar to [verify-config](https://github.com/kubernetes/test-infra/tree/master/hack), that ensures that the jobs generated by [generate_tests.py](https://github.com/kubernetes/test-infra/blob/master/experiment/generate_tests.py) match the script's output.

**Why is this needed**:
It is possible to modify either the [tests](https://github.com/kubernetes/test-infra/issues/7180) or the [generated jobs](https://github.com/kubernetes/test-infra/pull/13205) without picking up on the discrepancy between the two.

Ensuring that our generated code matches the script generating it will prevent future modification issues.

**Comment by krzyzacy** [comment]
I think @Katharine migrated release-related jobs, and we've also migrated all image validation jobs to internal, maybe we can delete all associated code here? @yguo0905

**Comment by Katharine** [comment]
@krzyzacy We still use this, and the tests it generates.

**Comment by krzyzacy** [comment]
assume it still consumes https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml today, at least we can clean up the cos tests here :-) punt to @yguo0905

**Comment by yguo0905** [comment]
Yes, we can remove the cos jobs. The ubuntu ones need to remain there unless we have a way to give Canonical read access to the internal test results.

I'm not sure about the release jobs. For example, can https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml#L1041 be removed?

**Comment by krzyzacy** [comment]
> I'm not sure about the release jobs. For example, can https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml#L1041 be removed?

probably not, as @Katharine mentioned above

**Comment by spiffxp** [comment]
/remove-kind feature
/kind bug
I consider the fact that we don't have safeguards that prevent us from making mistakes on config changes to be a bug

/milestone v1.16
Adding safeguards would make config changes and self-service easier
