### ISSUE TITLE
/uncc does not seem to work

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#13359]
i tried `/uncc` in the following PR(s) and it does not seem to help clear me from the list of reviewers.

- https://github.com/kubernetes/kubernetes/pull/76798#issuecomment-509397574
- https://github.com/kubernetes/kubernetes/pull/74691#issuecomment-509396737
- https://github.com/kubernetes/klog/pull/74#issuecomment-509397679
- https://github.com/kubernetes/kubernetes/pull/76838#issuecomment-509265257
- https://github.com/kubernetes/kubernetes/pull/78799#issuecomment-509279722

We seem to be using this API for deleting Review Requests:
https://developer.github.com/v3/pulls/review_requests/#delete-a-review-request

Do we need to [delete](https://developer.github.com/v3/pulls/reviews/#delete-a-pending-review) or [dismiss](https://developer.github.com/v3/pulls/reviews/#dismiss-a-pull-request-review) a pending review as well? to clear me from the list of reviewers?

**Comment by cblecker** [comment]
That's because you've already left a review, so you *are* a reviewer.

**Comment by dims** [comment]
gotcha :)

/close
