### ISSUE TITLE
blunderbuss calculates leaf nodes incorrectly

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13362]
https://github.com/kubernetes/kubernetes/pull/79874 has a `k8s-ci-robot requested review from fejta and smarterclayton 18 hours ago` message.

This is deeply unfortunate as there are only changes to test/e2e/lifecycle/* and there is a test/e2e/lifecycle/OWNERS file. Why didn't we use it?

**Comment by fejta** [comment]
/good-first-issue

Ensure that if we only change files in kubernetes/kubernetes test/e2e/lifecycle/foo that we only use people in test/e2e/lifecycle/OWNERS to auto-assign reviewers and suggest approvers.

**Comment by fejta** [comment]
Sounds like this is because the `sig-cluster-lifecycle` alias doesn't exist.

**Comment by leprecaun405** [comment]
https://github.com/kubernetes/test-infra/issues/13362#issuecomment-509406668

**Comment by spiffxp** [comment]
/remove-good-first-issue
/remove-help
/close
seems like this was a case of bad data, not bad algorithm
