### ISSUE TITLE
Allow job configuration inside the tested repo

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13370]
/assign @alvaroaleman 
I'm creating a tracking issue for this, but am not working on it.  Assigning it to the person who suggested this and has been doing all of the work.

**What would you like to be added**:
In order to make job configuration atomic and easily discoverable, it should be possible to version it inside the tested repo. This is a feature already available on almost any other CI/CD platform like e.G. Jenkins, Gitlab, DroneCI, CircleCI, Travis or Buildkite.

KEP - https://github.com/kubernetes/enhancements/pull/1092
Sketch - https://github.com/kubernetes/test-infra/pull/13342
Epic doc - https://docs.google.com/document/d/1OtakuUaQ4jxJzkgBERJwsqIjNuriZQWIocth8_D1ZCg/edit#bookmark=id.sevcshu2ue95

- [x] Agree on a design
  - The trickiest part will be to agree on a design, as it will introduce additional complexity.
- [x] Figure out which things won't work anymore
  - Introducing this means certain functionalities like e.G. the Branchprotector can't work anymore. Find out what is affected.
- [x] Think about security implications and how to mitigate them
  - Adding this has security implications, because it means there is more than one repo where jobs can be added. Think about the security implications and how to minimize them.

**Comment by alvaroaleman** [comment]
We discussed some details of the [sketch pr](#13342) in the sig-testing weekly on July 16, 2019, namely:

* Currently, there is a helper func in the `PluginAgent` that fetches a PRs baseSHA and posts a comment to github if anything failed with accessing the `Presubmits` config
    * This is a weird place to have a helper func
    * All helpers should be in the `config` package
    * Instead of posting directly to github, we should have a `Presubmit` that runs `checkconfig` to find any  config errors
    * That Presubmit will have to clone the test-infra repo and the code repo
    * We should generate that presubmit at config load time, because its not optional when using `inrepoconfig`
    * Using a presubmit also eliminates the need to manage a status context that signals if the loading of the `inrepoconfig` worked
* Branchprotector right now basically ignores repos that have `inrepoconfig` enabled
    * Instead, it should just check out the branches and adds all config it finds there
    * if a pull removes a presubmit, $something will have to set the context to green to satisfy branchprotection
* Configuring branches on Presubmit
    * Presubmits allow to configure on which branches they run
    * `checkconfig` must verify that no such setting is set when they come from inside the repo, as the branch is implicit by the fact from which branch they were read
    * If there is any branch setting on presubmits that come from inside a repo, it must be discarded at load time
* Github status context reconciling
    * In the sketch, this is done by listing all contexts on all events that get handled by the `trigger` plugin
    *  This is too expensive tokenwise
    * Instead we need something that gets notified whenever config could have changed and then checks if that did happen without calling to Github
    * This means we need something that gets notified whenever the static config changed, the base of any PR changed or the head of any pr changed, then checks if the changes change config
    * Building this is a bit more effort
    * Status reconciling generally is considered to be best-effort, building this can be deferred to the very end 

Also it was agreed that on a high level, the added complexity needed for `inrepoconfig` seems to be fine.

Next steps will roughly be:
* Add the types and funcs in the `config` package with a no-op implemenation of `inrepoconfig`
* Move all components that access `Presubmit` config over to use that
* Implement `inrepoconfig`
* Extend `checkconfig` to cope with `inrepoconfig`

**Comment by alvaroaleman** [comment]
Badly worded PR description, I didn't intend to close this issue as its not done yet
/reopen

**Comment by howardjohn** [comment]
+1000 this would make my life so much easier. See https://github.com/istio/test-infra/issues/1734 for a forever growing list of times this would have saved me a few hours

**Comment by stevekuznetsov** [comment]
This is chugging along nicely!

**Comment by alvaroaleman** [comment]
@howardjohn and everyone else who might be interested: this is now implemented for Presubmits, check out the [docs](https://github.com/kubernetes/test-infra/blob/master/prow/inrepoconfig.md), try it out and let me know if you have any feedback :)

**Comment by eddycharly** [comment]
@alvaroaleman is there a plan to support Postsubmits also ?

**Comment by alvaroaleman** [comment]
> @alvaroaleman is there a plan to support Postsubmits also ?

I have created a ticket for this: https://github.com/kubernetes/test-infra/issues/15656

I haven't looked much into this but I _think_ it there is no reason why this can't be done. Its a bit of work as all code that uses Postsubmits needs to be touched, but should be easier than presubmits.

**Comment by alvaroaleman** [comment]
This is implemented for both Pre- and Postsubmits, see https://github.com/kubernetes/test-infra/blob/68cca07c3b5202fb9cfb1656e5ca23b615bddc0c/prow/inrepoconfig.md, hence I consider this done.
/close
