### ISSUE TITLE
unrecognized annotations are allowed in prowjob annotations

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13379]
**What happened**:
We checked in a bunch of prowjobs with an incorrect annotation "test-tab-name" instead of the intended "testgrid-tab-name"

**What you expected to happen**:
Have a presubmit fail on us because this was an unrecognized annotation

**How to reproduce it (as minimally and precisely as possible)**:
Add an unrecognized annotation to a prowjob and PR it in

**Please provide links to example occurrences, if any**:

ref: https://github.com/kubernetes/test-infra/pull/13205#discussion_r301822654

**Anything else we need to know?**:

This may be against the nature of annotations, which are supposed to be pretty ad-hoc.  It's not like we could use strict YAML parsing to error against these.  That said, I think that having a whitelist of known good annotations might be good for the sanity of job authors.  WDYT?

**Comment by spiffxp** [comment]
The annotations we currently use
```shell
$ for f in $(find config/jobs -type f -name '*.yaml'); do <$f yaml2json 2>/dev/null| gron 2>/dev/null; done | grep 'annotations\[' | sed -e 's/.*annotations\["\([^"]*\)".*/\1/' | sort | uniq -c
  24 fork-per-release
  10 fork-per-release-cron
  14 fork-per-release-generic-suffix
  17 fork-per-release-periodic-interval
   4 fork-per-release-replacements
 117 testgrid-alert-email
  15 testgrid-alert-stale-results-hours
 621 testgrid-dashboards
  15 testgrid-num-columns-recent
  17 testgrid-num-failures-to-alert
 537 testgrid-tab-name
```

**Comment by stevekuznetsov** [comment]
@spiffxp let it be known I find the length you went to not to use `jq` amusing ;)

**Comment by spiffxp** [comment]
Thank you @stevekuznetsov and @Katharine, I have been schooled. 

The Correct™ way was apparently
```sh
$ for f in $(find config/jobs -name '*.yaml'); do <$f yaml2json 2>/dev/null; done \
  | jq -s '.. | .annotations? | keys? | .[]' -r | sort | uniq -c
 209 description
  24 fork-per-release
  10 fork-per-release-cron
  14 fork-per-release-generic-suffix
  17 fork-per-release-periodic-interval
   4 fork-per-release-replacements
 118 testgrid-alert-email
  15 testgrid-alert-stale-results-hours
 623 testgrid-dashboards
  15 testgrid-num-columns-recent
  17 testgrid-num-failures-to-alert
 539 testgrid-tab-name
```
