### ISSUE TITLE
Generate metric for GitHub v4 API (graphql) token usage.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#13374]
Lets generate a prometheus metric for this like we do for v3 and create some graphs to display it. We should probably use the same mechanism for v3 and v4, but lets not have it live in Velodrome, I think this should be part of the new Prow metrics stack.

cc @stevekuznetsov @hongkailiu @Katharine

**Comment by hongkailiu** [comment]
I will take a look tomorrow.

**Comment by stevekuznetsov** [comment]
See also https://github.com/kubernetes/test-infra/pull/13182

**Comment by hongkailiu** [comment]
@cjwagner @stevekuznetsov 

I have some silly questions:
* Are we using the API both v3 and v4?
* how can we tell if v3/v4 of github api is being used? by url of the requests?

**Comment by stevekuznetsov** [comment]
> Are we using the API both v3 and v4?

Yep!

> how can we tell if v3/v4 of github api is being used for a http request? by url of the requests?

You can see from the doc for [v3](https://developer.github.com/v3/#schema) and [v4](https://developer.github.com/v4/guides/forming-calls/#the-graphql-endpoint) that the API URL roots are different. We also use separate client structures in this repository for v3 and v4:

https://github.com/kubernetes/test-infra/blob/ceab943bb9a9149109bd0866479536302539c21d/prow/github/client.go#L198-L209

https://github.com/kubernetes/test-infra/blob/ceab943bb9a9149109bd0866479536302539c21d/prow/github/client.go#L212

**Comment by spiffxp** [comment]
/sig testing
/area prow
is this also relevant to ghproxy?

**Comment by hongkailiu** [comment]
@spiffxp Yes, it is as far as i know.
The V4 of github API is used in ghproxy.

We are working on this. Hopefully, get something to review next week.

**Comment by stevekuznetsov** [comment]
It should have already been done, the logic to do it if in ghmetrics.go - but I wonder if we're routing v4 traffic through ghproxy.

**Comment by hongkailiu** [comment]
New panels are alive now.
https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1&refresh=1m

In order to see v4 samples in the dashboard, We need to route the v4 traffic to ghproxy.

**Comment by stevekuznetsov** [comment]
This is solved if you route v4 traffic through ghproxy
