### ISSUE TITLE
Post-Merge Hook/Action

### ISSUE THREAD

**Issue by nnordrum** [kubernetes/test-infra#13372]
**What would you like to be added**:
I would like some way of configuring an action _after_ an individual merge happens (I guess after the whole merge process is done would be nice too).

e.g.
1. Branch Master to temp branch
1. Merge target Branch to temp branch
1. proposed hook
1. Merge target Branch 2 to temp branch
1. proposed hook
1. Merge target Branch 3 to temp branch
1. proposed hook
1. Merge process is complete
1. (optional proposed hook at end)

**Why is this needed**:
Our large team has a sync point that they all commit a file at the "same" location and we rename it as part of the merge process. I don't see how this is done currently, but I could have missed it. Alternatively, we could make a custom merge strategy that does the moving, but I don't see where to configure that...

_Ideally_, would be nice to add a pre-process merge and pre-branch merge hooks as well... (I can submit a new PR for that/those if requested)

**Comment by stevekuznetsov** [comment]
Today, we support reacting to [push event webhooks](https://developer.github.com/v3/activity/events/types/#pushevent). Would that be appropriate to this request?

/cc @cjwagner @fejta

**Comment by nnordrum** [comment]
maybe? I think you still have the sync problem though, but I could be thinking about it too narrowly.

my gut says it doesn't because the sync points are different for each multi-branch build...

Specifically, we rename a sql file so flyway can process it, but (branches attempted to merge) * (time to build) > 24 hours, if there's no issues. We "regularly" select a greedy strategy that merges 20+ branches, and each build/test/etc. iteration is multiple hours.

A post-merge hook (or possibly a custom git merge strategy--I haven't looked at that yet) would be closest to what we have now, and I think it would be the most flexible.

Disclaimer: I know there's a lot of things we _should_ do, but we're here now...

**Comment by stevekuznetsov** [comment]
I'm not sure I understand what you mean by the sync problem, but you can configure a job today via Prow to run every time any merge happens to any branch on a repo.

**Comment by stevekuznetsov** [comment]
I'm not sure I understand what you mean by the sync problem, but you can configure a job today via Prow to run every time any merge happens to any branch on a repo.

**Comment by nnordrum** [comment]
Look at my example: when you submit a branch, it could get included at different points in the branch merge list of branches that are being merged in order to test it as one branch.

In that case, your branch could be number 3 in one consolidating the branches, 7 in another, and 15 in yet another. You wouldn't, at push time, be able to anticipate what number(s) the branch would be. You _have_ to do it _when_ you merge them together, since that's the only time when you _know_ what branches will be included and their order. 

If this doesn't make sense, I'll get on slack to reduce the cycle time since I'm explaining it poorly...

**Comment by spiffxp** [comment]
Prow has postsubmit jobs today (ref: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#how-to-configure-new-jobs), it seems like for your case you'd want to setup a postsubmit job that's pointed at your temp branch.  If you're looking to add a feature that sets up the temp branch and creates the job automagically, that's probably more complexity than we're willing to introduce within prow, but should be something you could script on top of what prow supports today.

**Comment by nnordrum** [comment]
@spiffxp: yeah, I talked to @stevekuznetsov on Slack about it and the post submit seems like it the way to go. We were doing everything "offline" (not using the GH API, just doing it though the CLI), so I was thinking a post submit wouldn't work, but provided we do a post submit and do the merging via API, it should work.

I still think it would be nice to have it, but I can use post submit and have the same effect.

**Comment by fejta** [comment]
This is solved by a postsubmits on the temp branch
/close
