### ISSUE TITLE
Prow issue: People in OWNERS files could not add LGTM

### ISSUE THREAD

**Issue by Aisuko** [kubernetes/test-infra#13396]
There is a PR in helm/charts. In my opinion, If my partner `jpoon ` add `/lgtm` label,  the PR would be merged. I'm sure that he was in the OWENERS file under approvers and reviewers. Is there has anything we should do?
https://github.com/helm/charts/pull/15354#issuecomment-510305070

**Comment by clarketm** [comment]
@Aisuko - It appears that your **OWNERS** file in the [`mysqlha`](https://github.com/helm/charts/blob/master/incubator/mysqlha/OWENERS) directory is misspelled **OWENERS** (note that there is an extra `E` in the filename). Try renaming that file

**Comment by nikhita** [comment]
Closing since the rename should fix this issue. :)

**Comment by Aisuko** [comment]
@clarketm Thanks for your quick reply I'm waiting for my PR merged which to fix the misspelled. 😄
