### ISSUE TITLE
Retire Travis

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#1342]
It's probably a good opportunity to clean up this mess too.
```
    - ./verify/verify-boilerplate.py
    - python -m unittest discover -s jenkins/test-history -p "*_test.py"
    - pylint jenkins/bootstrap.py  # TODO(fejta): all python files
    - pylint queue-health/graph/graph.py  # TODO(fejta): all python files
    - ./jenkins/bootstrap_test.py
    - nosetests --with-doctest jenkins/bootstrap.py
    - ./jenkins/diff-job-config-patch.sh
    - ./jenkins/diff-e2e-runner.sh
    - make -C gcsweb test
    - cd gubernator
    - ./test.sh --nologcapture
    - ./lint.sh
    - ../node_modules/.bin/mocha static/build_test.js
    - cd ..
    - gofmt -l .
    - go test k8s.io/test-infra/testgrid/config/...
    - chmod +x testgrid/jenkins_verify/verify.sh
    - ./testgrid/jenkins_verify/verify.sh
```

**Comment by spxtr** [comment]
The only remaining tests running on travis require docker. We could either use docker-in-docker with privileged containers, or else rewrite some shell scripts to not require docker.

```yaml
script:
    - ./jenkins/diff-job-config-patch.sh
    - ./jenkins/diff-e2e-runner.sh
    - ./testgrid/jenkins_verify/verify.sh
```

Of these, the only one I consider critical going forward is the `jenkins_verify` script. @krzyzacy we should take a stab at doing this with bazel.

**Comment by krzyzacy** [comment]
I can rewrite testgrid one by parse jenkins config without jenkins_job_builder, but `diff-job-config-patch.sh` might still be useful? How will we work around that

**Comment by spxtr** [comment]
Why not use jenkins job builder as an external `py_binary`?

I don't know about `diff-job-config-patch.sh`. Is it possible to do that without docker?

**Comment by krzyzacy** [comment]
I have vague painful memory that I screwed up to get jenkins job builder to work locally, but we can give another shot with bazel.

**Comment by BenTheElder** [comment]
It looks like the current state is that we're down to just:
```.yaml
script:
    - ./jenkins/diff-job-config-patch.sh
    - ./testgrid/jenkins_verify/verify.sh
```
I'm not sure if people are still using `diff-job-config-patch.sh` but it seems like the "jenkins_verify" script isn't doing anything particularly special that couldn't be done in prow, am I missing something?

**Comment by krzyzacy** [comment]
So they ensure 
- you don't do crazy stuff with Jenkins config
- all Jenkins jobs has a valid testgrid entry

we probably still want the coverage since we still *support* Jenkins

**Comment by BenTheElder** [comment]
It looks to me like it also checks prow jobs, but what about `./testgrid/jenkins_verify/verify.sh` needs to be run from travis (other than the current script using docker containers to run the go code)?

**Comment by BenTheElder** [comment]
Spoke to @krzyzacy, it sounds like we just need to leave these until Jenkins is gone (#3778) and then we can remove them.

**Comment by BenTheElder** [comment]
I intend to migrate us off of Travis by the end of the quarter. See [All Test on Prow Design Doc](https://docs.google.com/document/d/1ih0Pogkdyo8QwmJUkJd4pgqmXnPb6vZnUEyb8vhMjJg/edit#heading=h.x9snb54sjlu9) for the plan to move these docker-dependent jobs to Prow.

Also noting that Travis caused some annoying delays yesterday since Tide blocks on green status and Travis got stuck on yellow for many test-infra PRs at least.

**Comment by spxtr** [comment]
> Also noting that Travis caused some annoying delays yesterday since Tide blocks on green status and Travis got stuck on yellow for many test-infra PRs at least.

The submit queue actually has some logic to close and reopen PRs if travis is stuck. I don't plan on adding that to tide now, but it's interesting.

**Comment by kargakis** [comment]
> The submit queue actually has some logic to close and reopen PRs if travis is stuck. I don't plan on adding that to tide now, but it's interesting.

Closing+reopening PRs results in rerunning all tests. We wouldn't want to do that just for restarting travis. If tide knows what contexts are required, travis shouldn't be a problem.

**Comment by BenTheElder** [comment]
Done in #6305 :tada:
