### ISSUE TITLE
Found pkg/util/labels/.readonly, but files changed compared to "master" branch.Prow issue:

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [kubernetes/test-infra#13428]
Found pkg/util/labels/.readonly, but files changed compared to "master" branch.

pull-kubernetes-verify test failure ，but I check the pkg/util/labels/.readonly file is blank ，I want to know how to solve the problem。

**Comment by nikhita** [comment]
@ZP-AlwaysWin Do you mean in this PR https://github.com/kubernetes/kubernetes/pull/80095? Looks like tests are all green now. Do you think this issue can be closed? :)

**Comment by ZP-AlwaysWin** [comment]
> @ZP-AlwaysWin Do you mean in this PR [kubernetes/kubernetes#80095](https://github.com/kubernetes/kubernetes/pull/80095)? Looks like tests are all green now. Do you think this issue can be closed? :)

Yes，you are right。I have solved the problem ，Thank you very much ,I will closed the issue.

**Comment by nikhita** [comment]
Thanks @ZP-AlwaysWin!
