### ISSUE TITLE
Test result ingestion into BigQuery via Kettle is hiccuping increasingly frequently

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13432]
**What happened**:
http://velodrome.k8s.io/dashboard/db/bigquery-metrics?panelId=12&fullscreen&orgId=1&from=now-6M&to=now

Lots of alerts happening.  We've only had one or two weeks in Q2 where an alert hasn't fired.

**What you expected to happen**:

No alerts to fire.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

I suspect this isn't due to Kettle being written in python, but rather the pattern that Kettle follows.  It may require a redesign or rewrite but I'm not necessarily sure it's mandated that we switch languages for performance.  I suspect i/o is our problem here (due to unbounded growth of a sqlite database)

/area kettle
/area metrics

**Comment by spiffxp** [comment]
/priority important-soon
I am concerned this is going to tip over at some point

<img width="921" alt="Screen Shot 2019-08-14 at 1 05 16 PM" src="https://user-images.githubusercontent.com/49258/63052449-35e2bd00-be94-11e9-976b-f98dd3f8930e.png">

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
It's still hiccuping, but alerts are no longer firing as often
![Screen Shot 2019-12-12 at 3 03 38 PM](https://user-images.githubusercontent.com/49258/70756140-996ce200-1cf0-11ea-8e11-30e2aad6cb67.png)

**Comment by MushuEE** [comment]
@spiffxp thanks, will start looking into it.
/assign

**Comment by MushuEE** [comment]
Span is increasing deltas, not sure if kettle is taking longer to process all the data or not https://k8s-testgrid.appspot.com/sig-testing-misc#metrics-kettle

It might be worth it to start publishing the time that steps take to run within commands. Will add logging shortly

**Comment by MushuEE** [comment]
```
 resource: {…}  
 severity: "ERROR"  
 textPayload: "Traceback (most recent call last):
  File "/kettle/update.py", line 59, in <module>
    main()
  File "/kettle/update.py", line 47, in main
    call(bq_cmd + bq_ext + ' k8s-gubernator:build.week build_week.json.gz schema.json')
  File "/kettle/update.py", line 25, in call
    raise OSError('invocation failed')
OSError: invocation failed
" 
```
Seeing fairly frequent failure on build.week calls. Though there is not much more context...

**Comment by spiffxp** [comment]
Still seeing hiccups, but the duration has slowed

**Comment by MushuEE** [comment]
Thanks, I will check on the instances

**Comment by MushuEE** [comment]
Does appear we had another lockup
