### ISSUE TITLE
Phaino should respect Refs and ExtraRefs properly.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#13452]
Currently `phaino` just looks for a already checked out repo that matches each git ref specified by the job. Once it finds a matching repo is uses it as is without checking out the correct git refs.

Phaino should be updated to either check out the correct refs in these repos or (ideally) reuse the clonerefs container (or just its logic) to check out the repos at the correct refs just as we would in CI.

/help
/area prow/phaino
/area prow

cc @stevekuznetsov @fejta

**Comment by cjwagner** [comment]
Good thing our tools have sensible names so I never confuse them :upside_down_face:

**Comment by cjwagner** [comment]
This [PR](https://github.com/kubernetes/test-infra/pull/13561) may make this issue obsolete if we switch to recommending mkpod+kind instead of phaino+docker.

**Comment by fejta** [comment]
IMO phaino's behavior is a correct one for local workflows and pj-on-kind.sh can be used for a more realistic one
/close
