### ISSUE TITLE
kubetest doesn't work with modules

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/test-infra#13454]
**What happened**:

```shell
~ $ git clone https://github.com/kubernetes/kubernetes && cd kubernetes
~/kubernetes $ make 
<fine>
~/kubernetes $ make test-e2e
...
2019/07/15 23:34:53 util.go:46: Warning: Couldn't find directory src/k8s.io/kubernetes under any of GOPATH /go, defaulting to /go/src/k8s.io/kubernetes
2019/07/15 23:34:53 process.go:153: Running: make -C /go/src/k8s.io/kubernetes quick-release
make[1]: *** /go/src/k8s.io/kubernetes: No such file or directory.  Stop.
```

i.e. kubetest was flummuxed by my use of Go modules, despite k/k seeming to support them fine (AFAICT -- other basic tasks seem to work)

**What you expected to happen**:

```shell
~/kubernetes $ make test-e2e
2019/07/15 23:34:53 util.go:46: module k8s.io/kubernetes detected at ~/kubernetes, using that
```

i.e. kubetest to run `go mod edit -json` to see if we're currently in a module, and if that module is kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:

see "What happened"

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by spiffxp** [comment]
sig/testing

**Comment by DirectXMan12** [comment]
/remove-lifecycle stale

this'll be more relevant with go 1.13
