### ISSUE TITLE
Better local testing of decorated ProwJobs using Phaino.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#13475]
**What would you like to be added**:
Phaino currently constructs Docker commands to run a job locally based on the ProwJob spec instead of the decorated pod spec. This distinction results in decorated jobs behaving differently with Phaino than they do in CI. In particular:
- Git refs are not properly checked out
- $ARTIFACTS and $GOPATH are not provided.
- logs/metadata/artifacts are not exported.

I think the most complete way to address this and avoid skew in the future would be to add a "local" mode to the relevant pod utilities to make them copy to an output directory instead of uploading to GCS (or just skip upload and assume the directory where files are staged is an output directory). We can then update Phaino to use `mkpod` in addition to `mkpj` to get the decorated pod spec and then either:
1) Update Phaino to work with multiple containers
or
1) Update Phaino to use `kind` instead of docker.

This might be overkill though given that achieving the first two list items would otherwise only require some minor changes to Phaino and the third is not quite as important.

I do like the idea of having Phaino be a simple wrapper around `mkpj`, `mkpod`, and `kind` though. The requirements for that would be a local pod utility mode and the ability to mount volumes from the host into kind pods (this sounds easy?).

/assign
cc @fejta @stevekuznetsov @spiffxp

**Comment by spiffxp** [comment]
>I do like the idea of having Phaino be a simple wrapper around `mkpj`, `mkpod`, and `kind` though.

This would be awesome

/area prow
/area config
since it would make testing of job/config updates way easier

/milestone v1.16
if we end up not working on this we'll kick it out but I think you mentioned you had a sketch

**Comment by cjwagner** [comment]
> if we end up not working on this we'll kick it out but I think you mentioned you had a sketch

I've actually got a PR out now: https://github.com/kubernetes/test-infra/pull/13561
I still need to add tests and polish, but it is working already.
