### ISSUE TITLE
acs-engine deployer in kubetest should tag deployed resources

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/test-infra#13488]
**What would you like to be added**:

Ability to set tags on resource groups deployed using the acs-engine deployer in kubetest.

**Why is this needed**:

The Azure subscription used for sig-windows testing is also being used by sig-azure for their deployments. Tags would help in identifying which resource group belongs to which test. Also tags would facilitate cleanup of any resource group that may not be automatically deleted for any reason.

I do have some questions on the approach:

- what default tags should we support? timestamp , job name ?
- should we allow a list of custom tags sent via CLI ?

**Comment by adelina-t** [comment]
@ritazh  @andyzhangx

**Comment by ritazh** [comment]
I'm not aware of any tagging capability at the resource group level, but there is a way to add tags to the VMs via aks-engine using `customVMTags`. If we do plan to add tags to the resource group, we should add it to aks-engine.

cc @CecileRobertMichon in case we already have something I'm not aware of.

**Comment by CecileRobertMichon** [comment]
Rita is correct. The `customVMTags` apimodel property lets you tag the VMs deployed by aks-engine. To tag the resource group itself I suggest creating the RG before calling aks-engine and adding tags then (for example, with az cli `az group create --tags ...`). aks-engine does not create the resource group as part of the ARM template it generates, the group creation as part of the `deploy` command is just a convenience for users who don't have a pre-existing rg.

**Comment by CecileRobertMichon** [comment]
cc @chewong

**Comment by chewong** [comment]
Addressed by https://github.com/kubernetes/test-infra/pull/15064.

/close
