### ISSUE TITLE
prow: label "kind/api-change" isn't removed properly

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/test-infra#13526]
**What happened**:

I came across an issue that the label `kind/api-change` wasn't auto removed when the api changes are removed from that PR.

**What you expected to happen**:

`kind/api-change` is properly tagged/untagged.

**How to reproduce it (as minimally and precisely as possible)**:

(not sure it's a minimal precise one, but should be able to produce)

1. Create two PRs - PR1 contains api changes; PR2 is built on top of PR1, hence also has api changes.
2. Both PRs are labelled `kind/api-change` which is good.
3. PR1 gets merged to master
4. PR2 rebase master, so PR2 doesn't have api changes any more.
5. force push PR2
6. `kind/api-change` is still there in PR2.

**Please provide links to example occurrences, if any**:

Ref: https://github.com/kubernetes/kubernetes/pull/77760

**Anything else we need to know?**:

**Comment by spiffxp** [comment]
The owners-label plugin currently doesn't subtract any labels, because it doesn't keep track of which labels have been added to the issue by:
- the owners-label plugin
- humans via prow commands
- humans via manual label adds
- other prow plugins

So it's not immediately obvious which labels should be removed vs. left alone when a new commit is pushed

https://github.com/kubernetes/test-infra/blob/master/prow/plugins/owners-label/owners-label.go

**Comment by Huang-Wei** [comment]
Thanks for the explanation @spiffxp. So should I close it, or can it be an enhancement candidate?

**Comment by nikhita** [comment]
Some prior discussion on this: https://github.com/kubernetes/test-infra/issues/9934#issuecomment-434085682

From the previous thread:

> If this feature only makes sense for some labels we could add configuration to indicate which labels can be automatically removed?

`kind/api-change` is now used to signal PRs for API review:

https://github.com/kubernetes/test-infra/blob/91f4311b9a8195fd40fa519b4a3077f49ff3a8a4/config/jobs/kubernetes/test-infra/fejta-bot-periodics.yaml#L21-L29

Though I'm not entirely convinced this warrants additional logic.. the owners-label plugin is really simple right now. :)

@liggitt have there been cases of false positives before? if so, maybe it's worth adding it?

cc @cjwagner 

/sig contributor-experience

**Comment by liggitt** [comment]
api-change doesn't block anything, it's informative only. It's auto-added based on path, I believe. Auto-removing those labels could be tricky.

**Comment by nikhita** [comment]
> api-change doesn't block anything, it's informative only. It's auto-added based on path, I believe. Auto-removing those labels could be tricky.

:+1: let's close this for now, and reopen if we come across a case where auto-removal is functionally needed.

/close
