### ISSUE TITLE
metrics aren't updating since 2019-07-10

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13536]
**What happened**:
https://testgrid.k8s.io/sig-testing-misc#metrics-bigquery - went red as of 2019-07-10
http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1 - lines stop or panels are blank

**What you expected to happen**:
metrics to be up to date

**Anything else we need to know?**:
Pretty sure this was caused by https://github.com/kubernetes/test-infra/pull/13368
```
I0710 17:14:18.521] Call:  /workspace/./test-infra/jenkins/../scenarios/execute.py test-infra/metrics/bigquery.py -- --bucket=gs://k8s-metrics --backfill-days=90
W0710 17:14:18.551] Run: ('test-infra/metrics/bigquery.py', '--bucket=gs://k8s-metrics', '--backfill-days=90')
W0710 17:14:18.555] /usr/bin/env: 'python3': No such file or directory
```

/assign @clarketm

**Comment by clarketm** [comment]
@spiffxp - where is this code running and do you know how it is deployed?

**Comment by spiffxp** [comment]
This prowjob: https://github.com/kubernetes/test-infra/blob/24fcf19820b19d5903a8adda535b03c211d5f09c/config/jobs/kubernetes/test-infra/test-infra-periodics.yaml#L69-L99

And the image I assume is built from https://github.com/kubernetes/test-infra/tree/master/images/bigquery

**Comment by spiffxp** [comment]
/assign @cjwagner 
I think backfill should automatically be handled, but if there any questions

**Comment by clarketm** [comment]
@spiffxp - As an immediate fix I can revert the change then redeploy the image. What is the *project_id* in GCP to see the logs that you attached?

**Comment by clarketm** [comment]
@spiffxp - I likely just need to install python3 in the image, but best to revert ( #13540 ) the change until I can verify the build and deployment dependencies.
