### ISSUE TITLE
Jenkins Operator to Expose `label-selector` To Pushgateway

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#13569]
**What would you like to be added**:
I would like to be able to tell the difference between one `jenkins-operator` and another via a label... maybe `label-selector`. 

So a push-gateway job would have a `instance` and `label-selector` labels.

**Why is this needed**:
At the moment the only way to tell the difference between jenkins-operator is by parsing the instance label (this is not ideal and problematic).

**Comment by stevekuznetsov** [comment]
Pushgateway has been deprecated, you can now select on the job as you require.

/close
