### ISSUE TITLE
hack/verify-bazel is broken.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#13566]
**What happened**:
`bazel test //hack:verify-bazel` passes even though `bazel run //hack:update-bazel` produces the following changes:
wrote "prow/cluster/monitoring/BUILD.bazel"
wrote "prow/cluster/monitoring/mixins/prometheus/BUILD.bazel"

**What you expected to happen**:
The verify-bazel test should actually validate that update-bazel would have no effect.

**How to reproduce it (as minimally and precisely as possible)**:
Check out master and run the two commands.

/assign @Katharine @fejta @chases2

**Comment by fejta** [comment]
Why is this an issue rather than a PR?

**Comment by fejta** [comment]
There are mildly interesting bazely reasons for this
