### ISSUE TITLE
Should the "needs-sig" message stop mentioning github teams?

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13587]
**What should be cleaned up or changed**:

The `needs-sig` label gets applied with the following comment on issues in kubernetes/kubernetes:

>There are no sig labels on this issue. Please add a sig label by either:
>
>    1. mentioning a sig: `@kubernetes/sig-<group-name>-<group-suffix>`
>        e.g., `@kubernetes/sig-contributor-experience-<group-suffix>` to notify the contributor experience sig, OR
>
>    2. specifying the label manually: `/sig <group-name>`
>        e.g., `/sig scalability` to apply the `sig/scalability` label
>
>    Note: Method 1 will trigger an email to the group. See the [group list](https://git.k8s.io/community/sig-list.md).
>    The `<group-suffix>` in method 1 has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_.

I think we should stop mentioning the teams, and only suggest the `/sig` etc. commands.

The many-prefixed-teams are effectively deprecated https://github.com/kubernetes/community/issues/2324

**Provide any links for context**:

/sig contributor-experience

**Comment by nikhita** [comment]
> I think we should stop mentioning the teams, and only suggest the /sig etc. commands.

:+1:

**Comment by spiffxp** [comment]
I will admit, I don't have great data on who uses /sig vs. who uses teams.  I have seen some people use them, and they will notify members, but not everyone has them, and it's not clear to me how actively maintained they are.

**Comment by spiffxp** [comment]
/area config
this doesn't _live_ in the config dir (yet), but it's basically in reference to config for prow.k8.io rather than the functioning of the prow welcome plugin, so no prow label

**Comment by nikhita** [comment]
Since this sort of relates to github-related management, adding it to the project board so it is properly tracked.

/area github-management

**Comment by idealhack** [comment]
fixed by https://github.com/kubernetes/test-infra/pull/15399

/close
