### ISSUE TITLE
Support running kubetest on an existing GKE cluster

### ISSUE THREAD

**Issue by hantaowang** [kubernetes/test-infra#13589]
**What would you like to be added**:
Is it possible to have kubetest execute our gingko e2e tests on a preexisting GKe cluster without having to specify details about the cluster other than the kubeconfig? Our abstraction is that cluster up, down, and setup is handled independent of kubetest.

**Why is this needed**:
We recently switched some tests from running via gingko to invoking gingko through kubetest. This however broke our tests that run a 1.14 GKE cluster. Upon investigation, it seems that kubetest has a `--provider=gke` option but that forces you to set `--deployment=gke` as well. 

Setting that deployment flag complicates things as it then requires setting a ton of addition flags regarding the project, cluster name, network, topology, etc. It seems like these flags are used to ensure that the cluster specified exists and if not, then boots it. But because our tests ensure the cluster is booted before kubetest is invoked, it creates a lot of technical debt to unnecessarily pass those variables to kubetest. 

cc @davidz627 @jingxu97 @BenTheElder @krzyzacy

**Comment by krzyzacy** [comment]
See https://github.com/kubernetes/test-infra/blob/3fcdcc18e0b10352f5c75bdd49ef35ee03bf5e25/config/jobs/kubernetes/sig-gcp/sig-gcp-gke-config.yaml#L417-L444

You can always load a cluster from kubeconfig from a gcs bucket, like `--save=gs://kubernetes-e2e-soak-configs/ci-kubernetes-soak-gke-gci`

**Comment by hantaowang** [comment]
I'm not quite understanding how extending a soak cluster, using a kubeconfig from a bucket, or customizing the create command will help in my case. I already have the gke cluster created before the invocation of kubetest with the kubeconfig created and saved at the default location. kubetest won't start for gke unless I pass in a bunch of flags regarding the project, which is difficult for me to do.

**Comment by krzyzacy** [comment]
Assume you want to do this in CI, then I think the steps can be:

1. Create a cluster locally
2. Upload the kubeconfig to somewhere in gcs, grant prow SA access
3. Point kubetest to that kubeconfig location, and with --up=false and --down=false, with rest of the necessary flags

**Comment by davidz627** [comment]
@krzyzacy the kubeconfig can't be specified locally? It would be on the same machine that `kubetest` is run from.

**Comment by krzyzacy** [comment]
@davidz627 you want to do this locally or from CI? 

From locally you can simply follow https://kubernetes.io/blog/2019/03/22/kubernetes-end-to-end-testing-for-everyone/, you don't even need kubetest right?

```
Compiling and running the test suite
go test ./test/e2e -args -help is the fastest way to test that the test suite compiles.

Once it does compile and a cluster has been set up, the command go test -timeout=0 -v ./test/e2e -ginkgo.v runs all tests. In order to run tests in parallel, use the ginkgo -p ./test/e2e command instead.
```

**Comment by hantaowang** [comment]
We have a test framework that needs to rub locally and on orow. It builds our driver, brings up a gke or gce cluster, installs the driver and any special RBACs if necessary, and then invokes kubetest to run the e2e tests. 

Ideally we want every stage of that to be as independent of the provider as possible, and previously we used gingko instead of kubetest which allowed that. But kubetest gives some additional features that are nice, so we would like to use it, but now run into the issue that kubetest seems to be intimately tied with the provider. For GCE this seems to work fine without additional flag setting, but for GKE this appears to be quite annoying as we have to set many flags that breaks our abstraction. 

I am just wondering if there are kubetest functionality that is less tied with the provider and ideally can work off just a kubeconfig that is provided locally.

**Comment by krzyzacy** [comment]
This sounds reasonable if you can have a way to guarantee the cluster exists, feel free to make kubetest work the way you want it to be :-) 

also cc @RonWeber if kubetest2 can work with this scenario already

**Comment by msau42** [comment]
Does using --provider=skeleton help?

**Comment by krzyzacy** [comment]
(also cc @freehan who was trying to do the same thing a while back)

**Comment by freehan** [comment]
FYI, my commandline is something like this:

```
kubetest --test --test_args="--ginkgo.focus=SomeTest" --check-version-skew=false  --provider=gke --deployment=gke --gcp-node-image=0 --gcp-project=${project}--cluster=${name} --gcp-region=us-central1 --gcp-network=default --gke-environment=prod
```

**Comment by hantaowang** [comment]
I have a problem specifically with the gcp-project and gke-env flags. Although we can certainly work around passing that in, I just want to make sure there are really no ways to use gke without setting those two.

**Comment by msau42** [comment]
@hantaowang our test framework should know the project from boskos.  And the gke-env is something we'll may want too so we can test against staging vs prod

**Comment by hantaowang** [comment]
The project is a little tricky because then for non prow runs you need to either specify or discover the default project, which can be done. Env is something we can do as well by seeing if the `CLOUDSDK_API_ENDPOINT_OVERRIDES_CONTAINER` env var is set. So it is possible, but just wanted to see if it was the best solution.

@freehan, what nodes gcp-node-image=0 mean? I have been setting it to COS.

**Comment by hantaowang** [comment]
Resolved. Thanks all.
/close
