### ISSUE TITLE
Kubernetes scalbility tests use wrong branches

### ISSUE THREAD

**Issue by krzysied** [kubernetes/test-infra#13622]
The kubernetes scalability tests of older releases are using master branch:
- 1.12
- 1.13
- 1.14

**Comment by wojtek-t** [comment]
Do we have only stable1/2/3?
We should also have beta.

**Comment by krzysied** [comment]
Beta is working correctly: https://github.com/kubernetes/test-infra/blob/31231ad83b8264e7404183fa9b3e311193352580/config/jobs/kubernetes/sig-release/release-branch-jobs/1.15.yaml#L175

**Comment by wojtek-t** [comment]
Scalability seem to be only part of the issue - it seems to me that a bunch of other jobs are misconfigured too.
@kubernetes/sig-release @justaugustus
