### ISSUE TITLE
All CI jobs should firewall to master <-> jenkins-agent access only

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1368]
c.f. kubernetes/kubernetes#38709 and kubernetes/kops#1144. Any cluster testing either of these was wide open for a period of time, and it's totally likely we'll screw up (in the CI stream) on GCE as well. We should add another layer of protection here, as I did in kubernetes/kubernetes#38672 last night for `kops`.

**Comment by zmerlynn** [comment]
cc @kubernetes/sig-auth

**Comment by justinsb** [comment]
I think it remains a possible foot-gun, I believe kops & kube-up GCE have got it right, but not sure about other installers, nor about whether an issue is the right way to track a "checklist" that should be applied to each task.

**Comment by BenTheElder** [comment]
FWIW we no longer have Jenkins agents, I'm not sure how cleanly this will
map to Prow and I'm not sure how much of a problem this actually is.

**Comment by errordeveloper** [comment]
/lifecycle stale

If someone know this area well, please make a call on whether this issues should stay open.

**Comment by krzyzacy** [comment]
no more Jenkins and I don't think we want to work on this
