### ISSUE TITLE
Move pod-related logic from sinker into Plank

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#13706]
**What should be cleaned up or changed**:

Currently, Sinker does have some cleanup logic for Pods. This logic is specific to ProwJobs with the Kubernetes Agent. The result is that the behavior of Prow as a whole with regard to ProwJobs with the Kubernetes Agent is a combination of what Plank and Sinker do, which makes tests not reflective of it. Thus, we should move all logic related to Pods and the corresponding tests out of sinker and into Plank.

**Provide any links for context**:

* Pod-Related code in sinker: https://github.com/kubernetes/test-infra/blob/7390662904a6df2d576e37b1ed50e0297bbd2950/prow/cmd/sinker/main.go#L287-L351
* Plank: https://github.com/kubernetes/test-infra/tree/master/prow/plank

/help

**Comment by stevekuznetsov** [comment]
So are we expecting `sinker` to only handle ProwJob CRs after this

**Comment by alvaroaleman** [comment]
> So are we expecting sinker to only handle ProwJob CRs after this

Yes
