### ISSUE TITLE
retitle command does not work on merged pull requests

### ISSUE THREAD

**Issue by enj** [kubernetes/test-infra#13716]
**What happened**:

Using retitle on a merged PR does not update the title.

**What you expected to happen**:

The title is updated.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Please provide links to example occurrences, if any**:

https://github.com/openshift/library-go/pull/472

**Anything else we need to know?**:

N/A

**Comment by nikhita** [comment]
This would definitely be useful!

/assign
Created https://github.com/kubernetes/test-infra/pull/13722
