### ISSUE TITLE
Bugzilla plugin does not link external tracker when pull request is merged

### ISSUE THREAD

**Issue by enj** [kubernetes/test-infra#13717]
**What happened**:

Linked a PR to a bug after the PR had already merged.

**What you expected to happen**:

The bugzilla bug should be updated with the external tracker.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Please provide links to example occurrences, if any**:

https://github.com/openshift/library-go/pull/472

**Anything else we need to know?**:

N/A

**Comment by stevekuznetsov** [comment]
This got fixed.

/close
