### ISSUE TITLE
triage is failing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#13744]
the triage periodic is now failing continuously with errors https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-test-infra-triage/1157331701362331652
```
+ bq extract --compression GZIP --destination_format NEWLINE_DELIMITED_JSON k8s-gubernator:temp.triage gs://k8s-gubernator/triage_tests.json.gz
BigQuery error in extract operation: Error processing job
'k8s-gubernator:bqjob_r7ddb74232fc611d3_0000016c533a4156_1': Table
gs://k8s-gubernator/triage_tests.json.gz too large to be exported to a single
file. Specify a uri including a * to shard export. See 'Exporting data into one
or more files' in https://cloud.google.com/bigquery/docs/exporting-data.
```

https://prow.k8s.io/?job=ci-test-infra-triage
xref: https://github.com/kubernetes/test-infra/issues/13730

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-testing-misc#triage&width=5&graph-metrics=test-duration-minutes

this seems like a "bad data in" situation, what has been growing to trip us over this threshold?

**Comment by spiffxp** [comment]
/area triage
/sig testing
/priority critical-urgent
go.k8s.io/triage is going to be stale until this is fixed

**Comment by clarketm** [comment]
As the error suggests, bigquery doesn't allow extraction from a table to a *single* file if the table is **1GB+** and this table is just over that threshold.

We can extract to multiple files, but just need to ensure we aggregate before feeding to `summarizer.py` since it expects a single file.

```diff
- gs://k8s-gubernator/triage_tests.json.gz
+ gs://k8s-gubernator/triage_tests*.json.gz
```

![image](https://user-images.githubusercontent.com/9957358/62400080-dc44cf00-b532-11e9-81e8-9a3e3bdf7b2c.png)

**Comment by cjwagner** [comment]
> need to ensure we aggregate before feeding to `summarizer.py` since it expects a single file.

I don't think this is true? https://github.com/kubernetes/test-infra/blob/6a85e1e9718d1d43aaa4b756826b36e8d22eff71/triage/summarize.py#L563

**Comment by cjwagner** [comment]
Green run: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-test-infra-triage/1158455335996887042

**Comment by BenTheElder** [comment]
🎉
