### ISSUE TITLE
lgtm plugin should use trigger.TrustedUser

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#13740]
The lgtm plugin currently does a `IsCollaborator()` check to determine if a user can lgtm a PR or not. Which means that even if `only_org_members: true` is defined in the `trigger` config, outside collaborators are able to lgtm PRs.

To fix this, we should use `trigger.TrustedUser()` to determine whether a user is trusted or not.

Additionally, if `skip_collaborators: true` is configured, we can then skip the `trigger.TrustedUser()` check.

/sig contributor-experience
/cc @cblecker @spiffxp @alvaroaleman @stevekuznetsov 
related: https://github.com/kubernetes/test-infra/issues/13002

Happy to work on this if this makes sense.

**Comment by nikhita** [comment]
This is mainly concerning because doing a `/lgtm` can trigger tests.

**Comment by nikhita** [comment]
related: https://github.com/kubernetes/test-infra/issues/12785

**Comment by cblecker** [comment]
I just.. I really dislike the whole "trusted org" logic set. That the "trust" is somehow tied to not the org the actual repo is in. If that logic wasn't there, I wouldn't even have a second thought on this.

**Comment by cblecker** [comment]
ref: https://github.com/kubernetes/test-infra/blob/50224637179f0ba9d6bf257c28d21da5d319fa89/prow/plugins/trigger/trigger.go#L153-L185

**Comment by alvaroaleman** [comment]
> I just.. I really dislike the whole "trusted org" logic set. That the "trust" is somehow tied to not the org the actual repo is in. If that logic wasn't there, I wouldn't even have a second thought on this.

Thats a fair point but IMHO an orthogonal issue. The issue we have here is that we have code to determine if a user is trusted and the LGTM plugin does something that requires trust (starting tests) without calling into that code but instead using a different check.

Independently of what `TrustedUser` actually does and if that always makes sense, IMHO everything that starts tests on a PullRequest should call into it to check if the user who triggered the event is trusted.

**Comment by alvaroaleman** [comment]
I think this is somethings we still need to fix. There is no good reason to have different codepaths  to determine "trust" in different places.

Using/Not using the "trusted org" concept is completely orthogonal to this.
