### ISSUE TITLE
Cleaning-up snapshots created in test on regular basis

### ISSUE THREAD

**Issue by oxddr** [kubernetes/test-infra#13764]
Context: in scalability tests we ran Prometheus, which monitors cluster under the test. We've recently added an option to snapshot Prometheus disk, so we can use it afterwards for debugging. We haven't enable in smaller test (100 nodes), running more frequently because we're worried, that we eat up whole snapshot quota. Manual cleaning is not considered an option. 
For the record those tests use Boskos to supply the actual project. 

I'm curious if there is any mechanism allowing to automatically cleanup snapshots (or any GCP resources in general) after some period of time, let's say 14 or 30 days after they have been created. Ideally I am looking for something that would work with both Boskos-managed projects as well as regular GCP projects (we use one for 5k tests). 

Before creating something on our own I wanted to double check if there is an existing solution. 

/help
/sig scalability
cc @wojtek-t @mborsz @krzysied

**Comment by oxddr** [comment]
@krzyzacy do you have an idea whom to route this question to?

**Comment by krzyzacy** [comment]
boskos uses https://github.com/kubernetes/test-infra/blob/master/boskos/janitor/gcp_janitor.py to clean up gcp resources - maybe you can see if you can add your clean up logic into the script?
