### ISSUE TITLE
Gubernator should expose prow's in-progress log

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#1376]
For example, bazel builds have a log now on prow's UI (e.g. https://prow.k8s.io/log?pod=3332396015323763201). Gubernator should somehow know if this exists and embed it if so.

**Comment by spxtr** [comment]
I need to turn the log path from a random pod name to something Gubernator can create.

**Comment by ixdy** [comment]
Good point, I didn't realize that the prow build number is a different long string of numbers (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38736/pull-kubernetes-bazel/7218971568304669599/ in this case).

**Comment by spxtr** [comment]
It won't be too tricky to expose it at `/logs/7218971568304669599` or something like that which Gubernator has knowledge of. Just need to add the appropriate label in the appropriate place.

**Comment by rmmh** [comment]
If you can wire it through to started.json (the pod number), that would work too.

**Comment by rmmh** [comment]
I do prefer the alternative of labeling the pods build-path=33965/pull-kubernetes-e2e-gce-gci/9456 or something, so you can do a query with that directly.

**Comment by ixdy** [comment]
yeah, adding some field to `started.json` seems like the easiest way to tell Gubernator that a prow log exists. though I guess `started.json` is created by bootstrap, and I have no idea how it'd know it was running on prow, or how to find itself.

**Comment by spxtr** [comment]
I don't want it in `started.json` because the pod will go away after a day or two and that data will be meaningless.

**Comment by rmmh** [comment]
Fixed in #1453.

Kind of silly, since these jobs only take a couple minutes right now.
