### ISSUE TITLE
ghproxy: metrics: some variables may contain slashes

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#13789]
For variables like branch names or labels that contain slashes, the path is not simple:

```
/repos/openshift/knative-client/branches/pr/olm-fix-release-next/protection
/repos/openshift/origin/issues/23421/labels/do-not-merge/work-in-progress
```

We need a type of variable that allows slashes, I think. Crazy that GitHub API does this, their parsing code must be so complex.

/assign @techyx
/cc @cjwagner

**Comment by tehcyx** [comment]
Oh wow, this is unexpected. I'll look at what I can hack tomorrow for this.

**Comment by stevekuznetsov** [comment]
Eek, sorry on the name typo :|

**Comment by tehcyx** [comment]
I don’t think this is still an issue with the simplified path rework @stevekuznetsov ?
