### ISSUE TITLE
ability to subscribe to test grid board summary's failures

### ISSUE THREAD

**Issue by tpepper** [kubernetes/test-infra#13826]
**What would you like to be added**:
As a community member doing triage I regularly look at testgrid summary boards and visually scan for new failures.  I would like an email regarding state changes.

**Why is this needed**:
1) notifications are good
2) It is possible to get notifications for board tabs and for individual tests and this is commonly done.  But for example as a member of the patch release team, I'm watching all of sig-release-1.1.[345]-blocking|all|informing for failures.  Adding our team email to all of those tabs is going to be something like 300 lines of config patch, when it could be 9.  This is not only awkward and a large barrier to folks choosing to proactively monitor more, it is highly redundant and not highly maintainable.

**Comment by BenTheElder** [comment]
cc @michelle192837

**Comment by michelle192837** [comment]
/remove-lifecycle-stale

This is still a good request (though we probably want to move it to the new repo (https://github.com/GoogleCloudPlatform/testgrid)
