### ISSUE TITLE
Move knative/test-infra/tools/prow-auto-bumper over

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#13823]
**What would you like to be added**:
https://github.com/knative/test-infra/tree/master/tools/prow-auto-bumper

**Why is this needed**:
This prow auto bumper library can potentially be consumed by other prow instances that want auto bumping to stable Prow versions. Refactor this tool and push it to kubernetes/test-infra so that it can be easily consumed by others

**Comment by spiffxp** [comment]
/sig testing
/area prow
FYI @cjwagner
