### ISSUE TITLE
Skew tests do not process junit correctly

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1382]
https://k8s-testgrid.appspot.com/google-kubectl-skew#gce-1.4-1.5-cvm-kubectl-skew&include-filter-by-regex=%5EOverall%24%7CTest

**Comment by fejta** [comment]
I would expect testgrid to show test cases for this run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-latest-1.4-latest-1.5-cvm-kubectl-skew/787

**Comment by ixdy** [comment]
@fejta if you remove the *include-filter-by-regex* it looks fine - https://k8s-testgrid.appspot.com/google-kubectl-skew#gce-1.4-1.5-cvm-kubectl-skew

**Comment by fejta** [comment]
@rmmh not sure this is a helpful default

**Comment by fejta** [comment]
We need a breadcrumb of sorts to note when results are filtered out.
