### ISSUE TITLE
add README.md for experiment/

### ISSUE THREAD

**Issue by tpepper** [kubernetes/test-infra#13827]
**What should be cleaned up or changed**:
There is a lot in the experiment/ subdirectory and no README.md.  What's in this directory?  How/when do I propose/test potential changes on this code?

**Provide any links for context**:
If I understand https://github.com/kubernetes/test-infra/issues/2894#issuecomment-333265659 correctly experiment/test_config.yaml is where I'd attempt to modify config/jobs/kubernetes/generated/generated.yaml content, for example hoping to add an annotation "testgrid-alert-email: release-managers@kubernetes.io" line in sig-release-1.15-blocking, but this isn't documented.

**Comment by spiffxp** [comment]
/remove-kind cleanup
/kind documentation
FWIW for the generated jobs it may be more appropriate to add some comments here https://github.com/kubernetes/test-infra/tree/master/config/jobs#generated-jobs

**Comment by spiffxp** [comment]
/sig release
since what motivated this ask is code related to job generation that lands on release dashboards
/sig testing

**Comment by justaugustus** [comment]
/remove-lifecycle rotten
/lifecycle frozen
@kubernetes/sig-testing

**Comment by BenTheElder** [comment]
This directory is for experiments. There has been no guiding light to this other than acknowleding that code in this directory need not meet the full requirements that the rest of the repo might with regards to what code we host and the code review """standards""".

Feel free to propose guidelines for this, but imo we just need a file that says something like
```
# Experiment

This directory contains experiments, these are small shared projects that are not supported and do not necessarily meet the standards of the rest of the repo.
```

If I had to guess, this came about to mimic the Google mono-repo's "experiment" directory in which users can create their own directories and check in ~anything without the normal code review standards.

It's useful for collaboration on quick & dirty prototypes and tools.

**Comment by spiffxp** [comment]
The original ask that motivated this is now answered in https://github.com/kubernetes/test-infra/tree/master/config/jobs#generated-jobs

I opened https://github.com/kubernetes/test-infra/pull/15560 with something based off of @BenTheElder's comment
