### ISSUE TITLE
Gerrit reporter: provide way for custom gerrit message

### ISSUE THREAD

**Issue by maria-ignacio** [kubernetes/test-infra#13848]
Here's the function that generates the comment text:
https://github.com/kubernetes/test-infra/blob/master/prow/gerrit/reporter/reporter.go#L258

It would be helpful if you could generate a custom message that can enable you to provide more information other than just the success state and report url.

For example, I want to show users generated coverage test results which would be in the `artifacts` directory. Currently, finding these results would be convoluted because users would need to click on various links to see the results. However, it would be helpful if you could create a custom message for gerrit that can display a friendly link to the coverage results, making it much easier for users to access their coverage results

**Comment by krzyzacy** [comment]
cc @amwat @bjh83 

move discussion here - I think we can implement a coverage reporter, and maybe other projects can also be benefit from this.

cc @stevekuznetsov @cjwagner if this sounds reasonable to you

**Comment by BenTheElder** [comment]
bump

**Comment by steuhs** [comment]
My team have the same need. Do we have any plan to implement this?
