### ISSUE TITLE
Implement kubernetes job health dashboard

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13879]
Implement a dashboard that displays job health metrics related to release-blocking job criteria (ref: https://github.com/kubernetes/sig-release/issues/347) such that release-blocking status can be measured and enforced by humans

To quote https://github.com/kubernetes/sig-release/blob/master/release-blocking-jobs.md#release-blocking-criteria

>- It provisions clusters via open-source software instead of a hosted service
>- It finishes a run in 120 minutes or less
>- It runs at least every 3 hours
>- Is capable of passing 3 times in a row against the same commit
>- Is owned by a SIG that is responsive to addressing failures
>   - Represented by a configured testgrid alert email (enforced via presubmit)
>- It passes 75% of all of its runs in the past week (regardless of underlying commit(s)) and fails for no more than 10 runs in a row
>   - In the case of failures, there must be an issue in kubernetes/kubernetes detailing that there is at least one person from the owning SIG working to resolve the issue. Said issue must be acknowledged within a short period (i.e., a week) and resolved within a short period being acknowledged by the owning SIG (i.e., a week as well).

/assign
/area velodrome
/area metrics
/milestone v1.16
/priority important-soon
/sig testing
/sig release

This is related to https://github.com/kubernetes/test-infra/issues/6380 but is not intended to document merge-blocking criteria

This is related to https://github.com/kubernetes/test-infra/issues/10369 but not intended primarily for deflaking

**Comment by spiffxp** [comment]
Initial stab in https://github.com/kubernetes/test-infra/pull/13880

http://velodrome.k8s.io/dashboard/db/job-health-release-blocking?orgId=1
- ✅  _"It finishes a run in 120 minutes or less"_ - threshold on daily 99th percentile job duration is set to 120 min
- ✅  _"It runs at least every 3 hours"_ - threshold on avg interval between job starts is set to 3 hours
- 🔶 _"Is capable of passing 3 times in a row against the same commit"_ - displays daily job flake rate
  - will need to write a new query to count longest streak of passes against a single commit
- ✅ _"It passes 75% of all of its runs in the past week (regardless of underlying commit(s))"_ - displays daily job failure rate, and average over total time range
  - if we feel it's important we could try for a rolling 1 week average, unsure if it's possible/easier to do via influx query or bigquery
- ❌  _"and fails for no more than 10 runs in a row"_
  - will need to write a new query to count longest streak of passes against a single commit

Things I'm not happy with:
- although the data is present for all jobs, the list of jobs available to display is hardcoded in a grafana template variable; ideally it could populate this variable by querying an endpoint or database, e.g. "get me the list of all job names for this testgrid dashboard"
- it's based off of a daily query, so getting feedback on whether we fixed an issue takes a while
- it doesn't link to actionable next steps, e.g. "search for this flake on go.k8s.io/triage" or "see this github issue" etc.

**Comment by stevekuznetsov** [comment]
So I think we should wait on an implementation here unless we want to commit that hard-coded thing. We should also not put it into velodrome of all places ...

The appropriate approach here would be to expose the labels and annotations on a ProwJob via a synthetic metric. Please see `kube_pod_labels` for an example. This allows for joins and other more intricate selectors in PromQL and will automatically be derived from the source of truth, dynamically.

**Comment by stevekuznetsov** [comment]
Oh, yikes. It's SQL querying BigQuery?

**Comment by spiffxp** [comment]
@stevekuznetsov I think you're looking for something that is native to prow and works across all prow instances.  I'm focused solely on kubernetes' CI signal, and leveraging the infra we have in place.  I think it would be great for us to iterate toward something that works for all prows and doesn't rely on N external data sources, but I think it's useful to land this iteration first.

**Comment by spiffxp** [comment]
trying to understand the discrepancy between the failure rate showing the alpha job as 100% failing, and the continuous failures showing it as not failing (which testgrid agrees with)
![Screen Shot 2019-08-14 at 4 30 45 PM](https://user-images.githubusercontent.com/49258/63063313-faa2b700-beb0-11e9-9592-856fe6b32d54.png)

**Comment by spiffxp** [comment]
the discrepancy is now gone since I triggered a re-run of the metrics job, but there still seems to be some latency in the data that I don't fully grok right now, between:
- only rolling up jobs that have an end date
- jobs being in UTC time
- the date that's being stored in influx
- the way grafana is choosing to render that date

**Comment by spiffxp** [comment]
/remove-lifecycle stale

Unclear whether the community is getting any value out of this. One issue I have from a maintenance perspective is the list of jobs is hardcoded in the dashboard. Would prefer to have an endpoint we could hit to get back a list of values, specicially testgrid testgroup names by dashboard_tab.

**Comment by spiffxp** [comment]
Added http://velodrome.k8s.io/dashboard/db/job-health-release-informing
Updated http://velodrome.k8s.io/dashboard/db/job-health-release-blocking

**Comment by stevekuznetsov** [comment]
FYI @spiffxp if you wanted to do this using Prometheus metrics coming from Prow, we now support ProwJob labels and annotations on the state transition metrics, so you can do a query for, say, the success rate for ProwJobs with a specific annotation that may also be used to generate TestGrid dashboards.

**Comment by BenTheElder** [comment]
over what time window is the failure rate percentage computed? it does not match prow.k8s.io

**Comment by spiffxp** [comment]
/close
velodrome is down: https://github.com/kubernetes/test-infra/issues/16836
I've heard no complaints about this board's absence, so I can only presume it wasn't useful
