### ISSUE TITLE
metrics: use less cryptic flags for bq

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#13895]
**What should be cleaned up or changed**:

In metrics/bigquery.py, instead of `bq ... -n1234` use `bq ... --max_rows 1234`

**Provide any links for context**:

ref: https://github.com/kubernetes/test-infra/pull/13880#discussion_r313662479

/good-first-issue
/help
/sig testing
/area metrics
/milestone v1.16
/priority important-soon

**Comment by vamossagar12** [comment]
hi. I have assigned this issue to myself, but is it something which has been already fixed?

**Comment by spiffxp** [comment]
@vamossagar12 sorry, it lopoks like @Patil2099 is handling it over in https://github.com/kubernetes/test-infra/pull/13901

@Patil2099 can you assign yourself here?

**Comment by Patil2099** [comment]
It is already fixed

**Comment by Patil2099** [comment]
My pr will get merged once I squash my commits

**Comment by vamossagar12** [comment]
oh ok. that's what I had suspected. Thanks all :)

**Comment by nicoaragon** [comment]
Thank you, everyone!
What work is remaining to close this issue?

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/close
This was fixed by #14067
