### ISSUE TITLE
prow: bugzilla dependency reporting is confusing

### ISSUE THREAD

**Issue by danwinship** [kubernetes/test-infra#13919]
I linked a PR to a bug, and then prow complained (1) that the bug was in a state that it wasn't actually in, and (2) that it should have been in a state that it clearly shouldn't have been:

> This pull request references an invalid [Bugzilla bug](https://bugzilla.redhat.com/show_bug.cgi?id=1741499):
> 
> * expected dependent [Bugzilla bug](https://bugzilla.redhat.com/show_bug.cgi?id=1700431) to be in one of the following states: VERIFIED, RELEASE_PENDING, CLOSED (ERRATA), but it is ON_QA instead

Eventually I realized that the two "Bugzilla bug" links referred to different bugs, and that when it said "dependent Bugzilla bug", it meant "the bugzilla bug that the other previously-mentioned bugzilla bug depends on", **not** "the bugzilla bug that *this PR* depends on". It would be clearer if it said something like:

> * [bug 1741499](https://bugzilla.redhat.com/show_bug.cgi?id=1741499) depends on [bug 1700431](https://bugzilla.redhat.com/show_bug.cgi?id=1700431), which should be in one of the following states: VERIFIED, RELEASE_PENDING, CLOSED (ERRATA), but it is ON_QA instead.

/assign @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@danwinship will update. You can appreciate how "bug", "dependent bug" and "external bug" are not the clearest ... :man_facepalming:

**Comment by danwinship** [comment]
fixed by #13923
