### ISSUE TITLE
logs uploaded to GCS are not formatted in GMT time

### ISSUE THREAD

**Issue by calebamiles** [kubernetes/test-infra#1392]
Hello,

I attempted to run `hack/update_owners.py` on the 1.4 release branch and got the following traceback

```
Traceback (most recent call last):
  File "hack/update_owners.py", line 145, in <module>
    main()
  File "hack/update_owners.py", line 103, in main
    test_history = get_test_history(days_ago)
  File "hack/update_owners.py", line 39, in get_test_history
    resp = urllib2.urlopen(url)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

digging into things a little bit I saw that the generated log history URL was for tomorrow (16 December 2016) which makes sense given that

```python
    url = time.strftime(GCS_URL_BASE + 'logs/%Y-%m-%d.json',
                        time.gmtime(time.time() - days_ago * 24 * 60 * 60))
``` 

uses times in GMT which at the time I ran the script was tomorrow relative to my local time. Logs uploaded to GCS should probably be formatted in GMT. The referenced line above seems to have come in from https://github.com/kubernetes/kubernetes/commit/23fb96b01057e3d87bf23931bdda0c58a99acc36, however, the change to read test names from local files added in https://github.com/kubernetes/kubernetes/commit/78eeb76386707d8c02460e116526e1118910782f would certainly have helped this process. Not entirely sure what the correct thing to do here is.

**cc: @kubernetes/test-infra-maintainers**

**Comment by rmmh** [comment]
Why are you running hack/update_owners.py on the 1.4 branch?

**Comment by fejta** [comment]
Not clear if there is anything to do here... I don't understand when update_owners.py would upload to gcs.
