### ISSUE TITLE
Pony plugin: Cope with multiple requests in one comment

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#13938]
**What would you like to be added**:

Currently the pony plugin will only search for the first pony request it got in a comment, i.E. the comment:

```
/pony template
/pony boo
```

Will result in a "Couldn't find a pony for that query" and no `boo` pony which is disappointing. Instead, the pony plugin should look for both a `template` and a `boo` pony and post both of them or an error for each.

**Why is this needed**:

**Comment by fejta** [comment]
This requires updating https://github.com/kubernetes/test-infra/blob/4c871f02efffa9a6cd424644c0b0d1e8abe29907/prow/plugins/pony/pony.go#L128 and surrounding code to match N ponies instead of just 1. Probably should involve a ceiling on N.

Talk to @Katharine for any help

**Comment by agarg2008** [comment]
I don't think this has been finished yet and would like to work on it.
