### ISSUE TITLE
Able to run non-amd64 docker image (for cross-build) in prow environment

### ISSUE THREAD

**Issue by cofyc** [kubernetes/test-infra#13937]
**What would you like to be added**:

- do not cleanup bimft_misc
- or dedicated nodes for these jobs?

**Why is this needed**:

`image/bootstrap/runner.sh` will cleanup `binfmt_misc` at the end, so running jobs [which run non-amd64 docker image will fail](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_sig-storage-local-static-provisioner/135/pull-sig-storage-local-static-provisioner/1162200275243503618).

Why we need this feature: we need to run `apt-get` to install packages in non-amd64 docker image (`k8s.gcr.io/debian-base-${ARCH}:0.4.1`)

**Comment by BenTheElder** [comment]
we should really avoid using binfmt_misc on prow to begin with...

AFAICT it's not namespaced / kernel global, so if two jobs register entries on the same node simulataneously there will be issues...

cc @cblecker

**Comment by BenTheElder** [comment]
> Why we need this feature: we need to run apt-get to install packages in non-amd64 docker image (k8s.gcr.io/debian-base-${ARCH}:0.4.1)

can we avoid doing that part on prow? pre-publish the image with the packages, and then just do `FROM $image` ... `COPY binary` ... and build binaries with `GOARCH=foo go build ...` ?

**Comment by cofyc** [comment]
I need to run `apt-get install` to install extra packages. emm... start a VM (e.g. gce instance) in prow job to build images will work...

**Comment by cofyc** [comment]
Closing this in favor of alternatives.

**Comment by BenTheElder** [comment]
> I need to run apt-get install to install extra packages. 

Right, but how often do they change? If they aren't changing often it's more efficient anyhow to create an image like debian base with your extra packages via a seperate step, and then leverage that.

**Comment by cofyc** [comment]
thanks, that's a choice too.

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/14091
