### ISSUE TITLE
How do we want to handle Tekton versioning?

### ISSUE THREAD

**Issue by bobcatfish** [kubernetes/test-infra#13948]
**What would you like to be added**:

I'd like to figure out a process around keeping versions of Prow + Tekton Pipelines in sync. Some ideas:

- Update Prow's version of Tekton Pipelines with each release (happy to help with that!)
- Change Prow's usage of Tekton Pipelines so it is less tied to the version (e.g. Prow could use just raw json data so it doesn't need to know about the structure of the PipelineRun?)

**Why is this needed**:

In the context of https://github.com/tektoncd/pipeline/issues/922 (and thanks to https://github.com/tektoncd/pipeline/issues/1187 !) I was able to setup Prow + Tekton Pipelines, however one big issue I encountered was that the version of Tekton being vendored in for Prow is older (I think it's 0.2.0 but it also works up to 0.3.1 - specifically [the trigger field was removed](https://github.com/tektoncd/pipeline/pull/857) but in the version used by Prow it both has to be present and has to be set to `manual` (there might be a better way around this tho!).

We'd like to be able to use more recent versions of Tekton (if not HEAD) and trigger via Prow.

**Comment by vdemeester** [comment]
@bobcatfish see https://github.com/kubernetes/test-infra/pull/13719 (should bump to 0.6.0 :pray: )

**Comment by eddycharly** [comment]
@bobcatfish do you have any news about making prow + tekton with a higher version than 0.5.2 ?

**Comment by vdemeester** [comment]
@eddycharly I need to re-do https://github.com/kubernetes/test-infra/pull/14216 :angel:

**Comment by eddycharly** [comment]
@vdemeester 👍 
if you don't have time, maybe i can help, would be happy to contribute 😄

**Comment by vdemeester** [comment]
@eddycharly can be in separate pull requests, I even think it is better to have 2 separate PR. Removing the knative build dependency is the first step.

**Comment by eddycharly** [comment]
@vdemeester are there instructions to build the projects in the repository ?
i started changing things, trying to figure out how to build now...

**Comment by eddycharly** [comment]
`bazel build //prow/...` found the docs...

is it supposed to build on mac ?
```
ERROR: /private/var/tmp/_bazel_charlesbreteche/42dc72a11735a84e3aad14550c4ca981/external/org_golang_google_grpc/internal/syscall/BUILD.bazel:3:1: GoCompilePkg external/org_golang_google_grpc/internal/syscall/linux_amd64_
pure_stripped/go_default_library%/google.golang.org/grpc/internal/syscall.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/org_golang_google_grpc/internal/syscall/syscall_linux.go -src ... (remaining 19 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
        /private/var/tmp/_bazel_charlesbreteche/42dc72a11735a84e3aad14550c4ca981/sandbox/darwin-sandbox/5921/execroot/io_k8s_test_infra/external/org_golang_google_grpc/internal/syscall/syscall_linux.go: import of "golang
.org/x/sys/unix"
```

**Comment by eddycharly** [comment]
making progress : `bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //prow/...` works fine !

**Comment by eddycharly** [comment]
First step done https://github.com/kubernetes/test-infra/pull/15022
Now let's update tekton pipeline ;)

**Comment by eddycharly** [comment]
Here we go https://github.com/kubernetes/test-infra/pull/15072

**Comment by vdemeester** [comment]
@eddycharly Thanks :heart_eyes_cat:
