### ISSUE TITLE
agnhost 2.5 build/push needed

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#13967]
**What would you like to be added**:

A build/push of version 2.5 of the agnhost image (https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost#agnhost) is needed to include the changes from https://github.com/kubernetes/kubernetes/pull/81271 and https://github.com/kubernetes/kubernetes/pull/81314

**Why is this needed**:

e2e tests cannot use the new capabilities added to the agnhost image until the 2.5 version is built/pushed

/cc @jpbetz @kubernetes/sig-release

**Comment by jpbetz** [comment]
cc @bclau @spiffxp

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/13968#issuecomment-522694182

**Comment by BenTheElder** [comment]
done
/close

In the future I'm pretty sure anyone on the GKE team can do this, the project is `kubernetes-e2e-test-images` (= the GCR...) if you want to double check IAM.

**Comment by BenTheElder** [comment]
I'm adding some limited docs in #13968

**Comment by jpbetz** [comment]
Huge thanks for the image push

**Comment by jpbetz** [comment]
Looks like we're missing something:

e2e tests now fail on: https://github.com/kubernetes/kubernetes/blob/f4521bf5a21865738f49a1c73e6aa75200a99240/test/e2e/apps/rc.go#L52-L58

```
	ginkgo.It("should serve a basic image on each replica with a private image", func() {
		// requires private images
		framework.SkipUnlessProviderIs("gce", "gke")
		privateimage := imageutils.GetConfig(imageutils.Agnhost)
		privateimage.SetRegistry(imageutils.PrivateRegistry)
		TestReplicationControllerServeImageOrFail(f, "private", privateimage.GetE2EImage())
	})
```

Example failure:

 https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81497/pull-kubernetes-e2e-gce/1163559597798068226/

```
Failed: Failed to pull image "gcr.io/k8s-authenticated-test/agnhost:2.5": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/k8s-authenticated-test/agnhost:2.5 not found
```

Anyone know how to push the image to `k8s-authenticated-test` ?

**Comment by BenTheElder** [comment]
that image is not even in the manifests??
https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go

The registry is, but none of the images are listed there... is this documented anywhere?

**Comment by jpbetz** [comment]
With @BenTheElder's help, I've pushed images to `k8s-authenticated-test`:

```
make -C test/images all-push WHAT=agnhost REGISTRY=gcr.io/k8s-authenticated-test
```

Retesting now. Will follow up on process simplication on https://github.com/kubernetes/test-infra/issues/13968
