### ISSUE TITLE
agnhost build/release process documentation needed

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#13968]
**What should be cleaned up or changed**:

It is unclear how to make/test/deploy changes to the agnhost image, which is used for all e2e/conformance testing.

Can we add a section to the [readme](https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost#agnhost) telling devs:
1) how to make changes to the image
2) how to bump the version
3) host to test their changes to the image
4) how to request a build/push of the new version
5) host to bump the version used in e2e

/cc @spiffxp @kubernetes/sig-release @kubernetes/sig-testing 

**Provide any links for context**:

https://kubernetes.slack.com/archives/C2C40FMNF/p1566144183303200

https://github.com/kubernetes/kubernetes/pull/81271#issue-306307546:

> I am unfamiliar with how to test or publish the agnhost images.

https://github.com/kubernetes/kubernetes/pull/81271#issuecomment-520583605:

> So, first of all, since this changes webhook, we'll have to bump the image version. bump the version in test/images/agnhost/VERSION. Next, the agnhost version will also have to be bumped in test/utils/image/manifest.go.
>
> I don't think the image promotion automation finished yet, so someone who can build and push the image to gcr.io will have to build and push it.

**Comment by BenTheElder** [comment]
technical process:
`make -C test/images push WHAT=agnhost`

https://github.com/kubernetes/kubernetes/blob/master/test/images/Makefile

human process:
lol. this is another thing where there is none. A googler with access (= on GKE team) needs to be prodded. that should include you and @jpbetz 

This should be moved to https://github.com/kubernetes-sigs/k8s-container-image-promoter via wg-k8s-infra.

**Comment by liggitt** [comment]
> make -C test/images push WHAT=agnhost

does that do all the cross-build stuff necessary?

**Comment by BenTheElder** [comment]
yes, it should pick up
https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/BASEIMAGE
https://github.com/kubernetes/kubernetes/blob/master/test/images/image-util.sh#L41-L44

**Comment by liggitt** [comment]
ah, the [`ARCH ?= amd64`](https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/Makefile#L16) line in the makefile threw me off

**Comment by BenTheElder** [comment]
that tooling is pretty confusing, as per usual...

IMHO test/images is what needs the README, since currently this is setup to
apply to all test images.

**Comment by bclau** [comment]
I've written a ``README`` which covers the general building process for any image, including windows images, workarounds, etc. See here: https://github.com/kubernetes/kubernetes/pull/76838/files#diff-514135d132383981abd050d3e7dfc5ffR1

Regarding the version bump, I've added a short note here: https://github.com/kubernetes/kubernetes/pull/81008/files#diff-1c8a2ba0c34b8fc28df06b45859ebb6fR19

IMO, we could touch all the points noted in the issue in the ``test/images/README.md`` file, and we could start from the README I've written.

**Comment by jpbetz** [comment]
We also need to include the step of pushing the image to `k8s-authenticated-test` which is required by e2e, see https://github.com/kubernetes/test-infra/issues/13967#issuecomment-522773030

**Comment by mkumatag** [comment]
> I've written a `README` which covers the general building process for any image, including windows images, workarounds, etc. See here: https://github.com/kubernetes/kubernetes/pull/76838/files#diff-514135d132383981abd050d3e7dfc5ffR1
> 
> Regarding the version bump, I've added a short note here: https://github.com/kubernetes/kubernetes/pull/81008/files#diff-1c8a2ba0c34b8fc28df06b45859ebb6fR19
> 
> IMO, we could touch all the points noted in the issue in the `test/images/README.md` file, and we could start from the README I've written.

@bclau currently I see that https://github.com/kubernetes/kubernetes/pull/76838 is taking a lot of time, can we push README in a separate PR for improving the documentation?

**Comment by bclau** [comment]
> 
> 
> > I've written a `README` which covers the general building process for any image, including windows images, workarounds, etc. See here: https://github.com/kubernetes/kubernetes/pull/76838/files#diff-514135d132383981abd050d3e7dfc5ffR1
> > Regarding the version bump, I've added a short note here: https://github.com/kubernetes/kubernetes/pull/81008/files#diff-1c8a2ba0c34b8fc28df06b45859ebb6fR19
> > IMO, we could touch all the points noted in the issue in the `test/images/README.md` file, and we could start from the README I've written.
> 
> @bclau currently I see that [kubernetes/kubernetes#76838](https://github.com/kubernetes/kubernetes/pull/76838) is taking a lot of time, can we push README in a separate PR for improving the documentation?

Done: https://github.com/kubernetes/kubernetes/pull/81662
