### ISSUE TITLE
Teach prow to trigger testing when someone adds the ok-to-test label

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#13975]
See for example https://github.com/istio/api/pull/1037

If a non-org member sends a PR, prow waits until the PR has an `ok-to-test` label. This label tells prow that someone has determined that the PR is safe to run presubmits (aka is a real PR, not abuse). 

Normally people do this with an `ok-to-test` comment, which will add the label and trigger tests. However people can also just add the `ok-to-test` label. This currently requires them to also leave a `/test all` comment to trigger testing. 

It would be nice if we auto-trigger testing when someone (not the bot) adds this label.

https://github.com/kubernetes/test-infra/blob/d5fffa7adc656b799a9026b029d12544bfab7226/prow/plugins/trigger/generic-comment.go#L101-L106

https://github.com/kubernetes/test-infra/blob/d5fffa7adc656b799a9026b029d12544bfab7226/prow/plugins/trigger/generic-comment.go#L117

Here's a plugin that responds to label changes: https://github.com/kubernetes/test-infra/blob/9f0ac86fd0f4b96f5ca913fb120d2bb6a7c65ff7/prow/plugins/require-matching-label/require-matching-label.go

The trick here will be determining that the ok-to-test label was added, and only triggering tests on this event

/help
/good-first-issue

**Comment by vamossagar12** [comment]
@fejta , i have started making the changes for this PR. Wanted to ask, the plugin you have posted in the OP, shows required-matching-label plugin which responds to label changes. However, I see another plugin within trigger, which also, seems to respond to PullRequestActionLabeled events:

https://github.com/kubernetes/test-infra/blob/9f0ac86fd0f4b96f5ca913fb120d2bb6a7c65ff7/prow/plugins/trigger/pull-request.go#L92.

Infact, looks like the LGTM label handling is happening via this plugin. So, shouldn't this be the right place to add the test triggering flow?

**Comment by fejta** [comment]
Yes, SGTM.
