### ISSUE TITLE
Reboot jobs should be consistent between SIG-Release dashboards

### ISSUE THREAD

**Issue by jberkus** [kubernetes/test-infra#14017]
**What should be cleaned up or changed**:

Currently, ci-kubernetes-e2e-gce-cos-*-reboot is present in different dashboards depending on the Kubernetes release version:

* It's present as gce-cos-master-reboot in sig-release-master-informing
* It's present as gce-cos-k8sbeta-reboot in sig-release-1.16-blocking
* It's present as gce-cos-k8stable1-reboot in sig-release-1.15-blocking
* It's present as gce-cos-k8stable2-reboot in sig-release-1.14-blocking

There's a couple of problems with this:

1. The job is marked as informing in Master, but Blocking in the release versions.  It should not be inconsistent between release versions, lest the Release Team lose track of it.  Since this job does not currently have a responsive owner behind it (I believe, correct me on this), Informing is probably the correct location across all release versions.
2. A minor thing, but worth fixing if someone has to touch the same code: the naming scheme of stable1/stable2/stable3 counting backwards is not used by any other test job (and, for that matter, breaks links every time we rotate versions).  Ideally, the gce jobs would all use the nomenclature gce-cos-VERSION-reboot, e.g. gce-cos-1.15-reboot, to be consistent with how other release-versioned jobs are handled.

**Provide any links for context**:

* https://testgrid.k8s.io/sig-release-master-informing
* https://testgrid.k8s.io/sig-release-1.16-blocking
* https://testgrid.k8s.io/sig-release-1.15-blocking

**Comment by jberkus** [comment]
attn: @spiffxp @alejandrox1 @lachie83 @Katharine 

umbrella issue:
#11977 

additional refs:
https://github.com/kubernetes/test-infra/issues/9363#issuecomment-523594819

**Comment by tpepper** [comment]
I can understand a rationale for having meta naming such that big patches aren't needed so switch all the 1.12's to 1.13's as the "N-2" release moved from 1.12 to 1.13, and instead just patch the pointer.  But...

This has proved problematic and confusing.

I favor being explicit and naming like gce-cos-${VERSION}-reboot.  I believe the patches to handle the switching of the number will be very easy to review every three months and with that going forward there'd be no question anywhere about what version somebody's looking at, including in historical copy/pastes or screen shots.

**Comment by alejandrox1** [comment]
/remove-lifecycle stale
/priority important-soon
/milestone v1.18

this is a quick fix. we should be able to get this fixed soon(ish)

**Comment by spiffxp** [comment]
/close
Fixed by https://github.com/kubernetes/test-infra/pull/16742
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-reboot
