### ISSUE TITLE
kubernetes/community doesn't merge on lgtm tag

### ISSUE THREAD

**Issue by deads2k** [kubernetes/test-infra#1401]
We've moved docs into the `kubernetes/community` repo and we have an lgtm tag, but the bot isn't automatically merging them.

**Comment by deads2k** [comment]
I'm not sure if this is the right place for this issue, but I wasn't sure where else to place it.  Since kubernetes/community is the place proposals are getting merged, I'm assuming we're going to lock down who can manually merge pretty tightly.

**Comment by spxtr** [comment]
You'll need a [submit-queue](https://github.com/kubernetes/contrib/tree/master/mungegithub/submit-queue/deployment) if you want that behavior, and currently we only have one for a few repos. It's not trivial to set up for a new repo, but not *too* bad either. In the meantime, why not just lock down who can merge? The submit queue should only be necessary if you want sequential testing, which I don't think you need.
