### ISSUE TITLE
ci-benchmark-microbenchmarks job is continually failing

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#14011]
**What happened**:
https://testgrid.k8s.io/sig-scalability-benchmarks#microbenchmarks is continually failing

**What you expected to happen**:
for it not to fail

**Please provide links to example occurrences, if any**:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-microbenchmarks/1164240752918663169/build-log.txt

**Anything else we need to know?**:
There are lots of test results so it's unclear to me exactly what is failing

/sig scalability
/assign @wojtek-t 
sig-scalability job, please delegate as necessary

/sig testing
/assign @cjwagner 
in case it's something to do with the tool and not the tests

**Comment by cjwagner** [comment]
As the log indicates, the benchmark junit tools is successfully generating the junit results, but the benchmarks themselves are failing (exiting with status code 2).
The raw benchmark output points to build errors: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-microbenchmarks/1164277747950817282/artifacts/benchmark-log.txt

**Comment by wojtek-t** [comment]
This is duplicate of: https://github.com/kubernetes/kubernetes/issues/79464

**Comment by wojtek-t** [comment]
Closing as duplicate of kubernetes/kubernetes#79464
