### ISSUE TITLE
link to stdout from failed jobs does not open

### ISSUE THREAD

**Issue by bparees** [kubernetes/test-infra#14083]
**What happened**:
Looking at this job: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/6205

I clicked the "open stdout" link for one of the failed tests and i briefly saw a tab opened and then closed in firefox.  I see nothing happen at all in chrome.

In neither browser do i get a warning about popups being blocked, so it's not apparent why the link doesn't open.

**What you expected to happen**:

I expected a new tab to open w/ the stdout content.

**How to reproduce it (as minimally and precisely as possible)**:
See above.  reproduces every time.  Have confirmed w/ another user.

**Please provide links to example occurrences, if any**:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/6205

**Comment by droslean** [comment]
```
<a class="open-stdout" target="_self" href="https://prow.svc.ci.openshift.org/spyglass/lens/junit/iframe?req=%7B%22artifacts%22%3A%5B%22artifacts%2Fe2e-aws-upgrade%2Fjunit%2Fjunit_e2e_20190827-014439.xml%22%2C%22artifacts%2Fe2e-aws-upgrade%2Fjunit%2Fjunit_upgrades.xml%22%2C%22artifacts%2Fjunit_operator.xml%22%5D%2C%22index%22%3A1%2C%22src%22%3A%22gcs%2Forigin-ci-test%2Flogs%2Frelease-openshift-origin-installer-e2e-aws-upgrade%2F6205%22%7D&amp;topURL=https%3A//prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/6205&amp;lensIndex=1#">open stdout<i class="material-icons" style="font-size: 1em; vertical-align: middle; padding-left: 3px;">open_in_new</i></a>
```

The link looks suspicious. Is it supposed to be only `#`?

**Comment by clarketm** [comment]
@droslean  - `#` is an intentional dummy href; the [click handler](https://github.com/kubernetes/test-infra/blob/599c89c3cc90b749bf55a5d11a6caa6990d77aa5/prow/spyglass/lenses/junit/lens.ts#L37-L51) is handling the event.

**Comment by clarketm** [comment]
@bparees - can you replicate in an *incognito* tab? Some chrome extensions, such as adblockers, can block the blob object url.

**Comment by bparees** [comment]
disabling the ad blocker does seem to work, but only if you reload the page after disabling it (simply disabling it and then clicking the link does not work, which i think i tried before opening this issue).

given the prevalence of ad-blockers, it would still be nice to find a way to make this play nice w/ the common ones (ublock, adblock) though certainly i can whitelist now.

**Comment by clarketm** [comment]
@bparees - 👍. I can investigate *alternate* methods of displaying the `stdout` that plays nice with adblockers. In the meantime, whitelist may be the best bet.

**Comment by clarketm** [comment]
We do not plan to support workarounds for adblockers blocking blob urls. Disabling the adblocker is a sufficient resolution.

/close
