### ISSUE TITLE
Why not allow me to pull request after I have signed?

### ISSUE THREAD

**Issue by CandiceGuo** [kubernetes/test-infra#1409]
Why not allow me to pull request after I have signed?

**Comment by spxtr** [comment]
Are you referring to https://github.com/kubernetes/kubernetes.github.io/pull/1991? It looks like there are [three commits](https://github.com/kubernetes/kubernetes.github.io/pull/1991/commits) in that PR. You can see that the second is correct, but the first and last were made by a different git user. [This guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md) might help get you set up.

**Comment by CandiceGuo** [comment]
Thank you spxtr.
