### ISSUE TITLE
Qemu static registers to binfmt_misc which is still kernel globalkernel 

### ISSUE THREAD

**Issue by Sh4d1** [kubernetes/test-infra#14091]
**What happened**: When building multi arch containers, kernel fails to execute non amd64 binaries.

**What you expected to happen**: To work seemlessly

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

Use qemu static and register to binfmt_misc

**Anything else we need to know?**:
Context: https://kubernetes.slack.com/archives/C09QZ4DQB/p1566921207055100?thread_ts=1566921207.055100&cid=C09QZ4DQB

**Comment by BenTheElder** [comment]
@Katharine do you think we can just move this sort of building to GCB now?

**Comment by BenTheElder** [comment]
The answer is to use GCB. Contact wg-k8s-infra for setting this up.

I'll close this out after patching our CI scripts in this repo to not touch it either, but this should NOT be used on prow.k8s.io unless it is actually running in GCB via prow. Prow containers should not touch binfmt_misc.

**Comment by BenTheElder** [comment]
The other option is to cross compile and not use `RUN` when building images.

kind has images built this way here: 
https://github.com/kubernetes-sigs/kind/blob/90ea52098ffdc1ce0953ecc8c399e16f916174ef/images/haproxy/push-cross.sh

https://github.com/kubernetes-sigs/kind/blob/90ea52098ffdc1ce0953ecc8c399e16f916174ef/images/kindnetd/build.sh
