### ISSUE TITLE
[WIP] Remove old k8s client

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#14100]
**What should be cleaned up or changed**:
Refactor to remove all usage of old kube client [`./prow/kube/*`](https://github.com/kubernetes/test-infra/tree/master/prow/kube)

**Provide any links for context**:
https://github.com/kubernetes/test-infra/tree/master/prow/kube

**Comment by stevekuznetsov** [comment]
@clarketm I thought you had finished this one?

**Comment by clarketm** [comment]
I removed the old flags (#14080) and complete your initial work of migrating `plank`. `prow/kube/client.go` still has a few references in [prow/artifact-uploader](https://github.com/kubernetes/test-infra/blob/fc85258701afae82f59ec33a1c7f67652e1925f0/prow/artifact-uploader/controller.go#L56) and [prow/gerrit/adapter](https://github.com/kubernetes/test-infra/blob/fc85258701afae82f59ec33a1c7f67652e1925f0/prow/gerrit/adapter/adapter.go#L67) that I need to mitigate.
