### ISSUE TITLE
Image publishing jobs fail with cloud build quota errors

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#14107]
**What happened**:
TestGrid alerts for some of the image publishing jobs.
```
2019/08/21 17:20:58 Failed to push some images: [error running [gcloud builds submit --config kettle/cloudbuild.yaml --substitutions _GIT_TAG=v20190821-92d6d70 --project k8s-testimages --gcs-log-dir gs://k8s-testimages-scratch/logs --gcs-source-staging-dir gs://k8s-testimages-scratch/source gs://k8s-testimages-scratch/source/71e37026-b191-4853-8ebf-8b489fc2abd8.tgz]: exit status 1]
```

**Please provide links to example occurrences, if any**:

https://k8s-testgrid.appspot.com/sig-testing-images#kettle
https://k8s-testgrid.appspot.com/sig-testing-images#bootstrap
https://k8s-testgrid.appspot.com/sig-testing-images#velodrome
https://k8s-testgrid.appspot.com/sig-testing-images#image-builder

The errors for `kubekins-e2e` look unrelated and potentially resolved?
https://k8s-testgrid.appspot.com/sig-testing-images#kubekins-e2e

/assign @fejta @michelle192837 @Katharine

**Comment by fejta** [comment]
/kind oncall-hotlist

Looks like we don't have enough cloudbuild quota?

https://k8s-testgrid.appspot.com/sig-testing-images#velodrome
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-velodrome/1185703182316081152
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/post-test-infra-push-velodrome/1185703182316081152/artifacts/
https://storage.googleapis.com/kubernetes-jenkins/logs/post-test-infra-push-velodrome/1185703182316081152/artifacts/transform.log

```console
Created [https://cloudbuild.googleapis.com/v1/projects/k8s-testimages/builds/f146ba4a-6fe1-430b-a0de-1d5691f7d0f4].
Logs are available at [https://console.cloud.google.com/gcr/builds/f146ba4a-6fe1-430b-a0de-1d5691f7d0f4?project=597082399059].
ERROR: (gcloud.builds.submit) RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'cloudbuild.googleapis.com/get_requests' and limit 'GetRequestsPerMinutePerProject' of service 'cloudbuild.googleapis.com' for consumer 'project_number:684195865762'.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developer console API key
    url: https://console.developers.google.com/project/684195865762/apiui/credential
```

**Comment by fejta** [comment]
Katharine I assume this has been fixed?

**Comment by MushuEE** [comment]
@fejta Are we possibly still hitting [this](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-kettle/1282702600432521216)?

**Comment by fejta** [comment]
That link is definitely that error, yes
