### ISSUE TITLE
Too many different GCE projects

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/test-infra#1412]
Currently, we create a separate GCE project for each test suite.
The reason we want to do that is to prevent test from interfering each other, such as leaking VMs.

However, it also brought some management overhead:
* When we need to copy a bunch of test suites, for example for CRI, GCI validation, we have to create project one by one manually.
* We have to send out a lot of quota requests, which have already been complained by the internal quota approver.

Could we:
* Group test suites into several projects?
* Set different resource name or labels for different test suites, so that we can detect which test is leaking resource even in the same GCE project.

/cc @kubernetes/test-infra-maintainers

**Comment by mtaufen** [comment]
Could we just have a pool of projects and round-robin schedule test jobs on them?

**Comment by spxtr** [comment]
> Could we just have a pool of projects and round-robin schedule test jobs on them?

That's something we've been talking about for a long time. It's a good idea, but until fairly recently it was difficult to actually implement.
