### ISSUE TITLE
pull-kubernetes-conformance-image-test failing

### ISSUE THREAD

**Issue by aojea** [kubernetes/test-infra#14128]
**What happened**:

Bug with kind in master breaks the pull-kubernetes-conformance-image-test job
https://github.com/kubernetes/kubernetes/issues/82102

**What you expected to happen**:

pull-kubernetes-conformance-image-test running fine

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

https://testgrid.k8s.io/sig-testing-kind#conformance-image,%20master%20(dev)

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
is this fixed?

**Comment by BenTheElder** [comment]
I see some green runs
/close
