### ISSUE TITLE
Prow runs postsubmit tests as presubmit sometimes

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#14125]
We have presubmit and postsubmit tests (https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-postsubmits.yaml)

Usually presubmit tests run for PR branch commits and postsubmit tests run for master merges.

Sometimes though, the postsubmit test is executed for the PR and blocks attempts to merge the PR since the postsubmit test is only supposed to be run for master commits.
https://github.com/kubeflow/pipelines/pull/1984

```
kubeflow-pipeline-postsubmit — Job failed.
tide Pending — Not mergeable. Job kubeflow-pipeline-postsubmit has not succeeded.
```
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit/1166849049677008896

I expect postsubmit tests to only run post-submit.

How can we recover from this issue?

**Comment by stevekuznetsov** [comment]
Post-submits run when code is merged to the repo. You are making PRs from branches on the repo itself, not from a fork, and you have not configured the postsubmit to run on a particular branch or subsets of branches, so this is all working as expected. I would suggest, in the following order:

 - don't make branches on the repo itself to make PRs
 - use branch selectors on your presubmits and postsubmits

**Comment by Ark-kun** [comment]
> You are making PRs from branches on the repo itself, not from a fork

Oh, I see. Thanks for the explanation. I usually use forks, but just this time I used GitHub's editor.

TBH, I think this wasn't an issue before and I was able to create mergeable PRs from the main repo branches. But I cannot find any proof right now. So I'm closing the issue.

> I would suggest, in the following order:

>* don't make branches on the repo itself to make PRs
>* use branch selectors on your presubmits and postsubmits

Thanks for the suggestions.

**Comment by Ark-kun** [comment]
I've submitted the PR from a fork and yet the postsumbit test still runs: https://github.com/kubeflow/pipelines/pull/1990

**Comment by stevekuznetsov** [comment]
At some point you pushed that commit to the `kubeflow/pipelines` repo:

```
 jsonPayload: {
  component: "hook"   
  event-GUID: "4c00fd9e-ca89-11e9-9bce-b48d050a623e"   
  event-type: "push"   
  file: "prow/hook/events.go:218"   
  func: "k8s.io/test-infra/prow/hook.(*Server).handlePushEvent"   
  head: "abfc57232635749501295d23be5765de237381fe"   
  level: "info"   
  msg: "Push event."   
  org: "kubeflow"   
  ref: "refs/heads/avolkov/Testing---Fixed-the-comparison-bug-in-presubmit-test-script"   
  repo: "pipelines"   
 }
```

/close

**Comment by Ark-kun** [comment]
> At some point you pushed that commit to the `kubeflow/pipelines` repo:

Is that information a part of the commit or does Prow or GitHub remember that?

**Comment by Ark-kun** [comment]
>  ref: "refs/heads/avolkov/Testing---Fixed-the-comparison-bug-in-presubmit-test-script"

It's interesting since that branch no longer exists in that repo.
