### ISSUE TITLE
kubetest: unable to find `local-up-cluster.sh`

### ISSUE THREAD

**Issue by reith** [kubernetes/test-infra#14158]
By kubetest docs, I understand it should be installed from master and run on `kubernetes/kubernets` master even for testing other releases. I did so to run `1.13.6` cluster and it failed to run start-up cluster, complaining `hack/local-up-cluster.sh` file is not found. I suppose that file has existed since much before than `1.13.6`, am I correct?

**What happened**:
Got kubetest and `kubernetes/kubernetes` from master and tried to start `1.13.6` cluster by:
`$ kubernetes/kubernetes: kubetest --up --extract=v1.13.6 --deployment local`
kubetest downloaded release tarball and extracted but failed to run cluster-up script since it was not found:
`main.go:319: Something went wrong: starting e2e cluster: unable to find script hack/local-up-cluster.sh in directory /home/rei
th/projects/kubernetes/kubernetes`

**What you expected to happen**:
kubetest start 1.13.6 cluster for me.

**How to reproduce it (as minimally and precisely as possible)**:
`kubetest --up --extract=v1.13.6 --deployment local`

**Comment by dims** [comment]
`/home/reith/projects/kubernetes`  seems wrong. `kubernetes` should be in `$GOPATH/src/k8s.io/`

/close
