### ISSUE TITLE
Need SIG-Windows jobs for release-1.16 branch

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/test-infra#14150]
**What happened**:
SIG-Windows had jobs on the release-all dashboards for 1.14 and 1.15 that were green at release. Currently there's nothing for SIG-Windows on 1.16-release dashboards

**What you expected to happen**:
For 1.16, I mistakenly thought our job on master would be branched for `release-1.16` but that didn't happen.

**How to reproduce it (as minimally and precisely as possible)**:
https://testgrid.k8s.io/sig-release-1.16-all, search for Windows

**Anything else we need to know**:

I'll have a PR in a few minutes

cc @idealhack 

/sig windows
/milestone v1.16

**Comment by PatrickLang** [comment]
cc @adelina-t

**Comment by alejandrox1** [comment]
@PatrickLang where in https://testgrid.k8s.io/sig-windows could we find the jobs you want to promote ?

**Comment by PatrickLang** [comment]
@alejandrox1 maybe that's the root cause - we didn't have a test on release-1.16 yet since we were just looking at master branch for status

**Comment by PatrickLang** [comment]
cc @yujuhong @pjh - do you want to fork jobs for release-1.16 on gce too?

**Comment by alejandrox1** [comment]
@PatrickLang it could be but normally SIGs have the jobs on their dashboards (sig-windows in this case) and then we copy or replicate (depending on the job) these into the sig-release dashboards.

Could you all please create a list of the jobs you want to promote?

**Comment by yujuhong** [comment]
> cc @yujuhong @pjh - do you want to fork jobs for release-1.16 on gce too?

Yes, we do.

**Comment by Katharine** [comment]
If you want your job to be automatically forked, you need to include the [fork annotations](https://github.com/kubernetes/test-infra/tree/master/experiment/config-forker#supported-annotations). Otherwise you'll have to do it manually after the fact.

**Comment by idealhack** [comment]
I didn't have the whole picture on this, but it might be the problem that the job we want to fork does not have the `fork-per-release: "true"` annotation so that [config-forker](https://github.com/kubernetes/test-infra/tree/master/experiment/config-forker) can create one for every release branch.

/area release-eng
cc @kubernetes/release-engineering 
cc @Katharine

**Comment by idealhack** [comment]
@Katharine you beat me to it... thanks!

**Comment by justaugustus** [comment]
Hehe, I was just about to come here and say that! 😜

**Comment by alejandrox1** [comment]
@PatrickLang could you please add the same type of job you added in https://github.com/kubernetes/test-infra/pull/14151 to the release-informing dashboard, https://testgrid.k8s.io/sig-release-master-informing ? 
/reopen

**Comment by idealhack** [comment]
@PatrickLang Hi, I took a look at the [annotations](https://github.com/kubernetes/test-infra/tree/master/experiment/config-forker#supported-annotations) and your job configs again, it seems some differences between them make it a bit hard to be forked automatically.

**Comment by alejandrox1** [comment]
@idealhack could you provide anymore details?
what needs to be done for us to resolve this issue?

**Comment by idealhack** [comment]
@alejandrox1 to be clear, the annotations part is definitely not blocking 1.16, and we can resolve it later. I can come back with more details in a new issue and close this one.

**Comment by PatrickLang** [comment]
@alejandrox1 - are you ok to close this then? we can track the annotation in a new issue and merge that fix to master to be ready for 1.17

**Comment by justaugustus** [comment]
@PatrickLang -- this should stay open until we fix the 1.16 and add the annotations to the main job, so we don't miss it for 1.17.

**Comment by adelina-t** [comment]
/assign @adelina-t 

I'll do changes to the config so it supports annotations.

**Comment by alenkacz** [comment]
@justaugustus I think this got fixed for 1.17. Can we close this?

**Comment by PatrickLang** [comment]
/close
if it doesn't work for 1.18, will open new issue with specific failures
