### ISSUE TITLE
Provide a vendor directory to avoid downloading all go modules

### ISSUE THREAD

**Issue by aanm** [kubernetes/test-infra#14165]
**What would you like to be added**:

Add a `vendor/` with all `kubetest` dependencies.

**Why is this needed**:

To avoid downloading all go modules every time someone builds `kubetest` binary in a clean environment.

Alternatively, if `kubetest` binary would be available, in a docker image for example, that would also be great.

cc @fejta

**Comment by fisherxu** [comment]
+1

**Comment by aanm** [comment]
Also, to avoid this
```
14:02:39  go: finding gopkg.in/jcmturner/gokrb5.v7 v7.3.0
14:02:42  go: finding github.com/coreos/etcd v3.3.15+incompatible
14:06:57  go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/vagrant/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
14:06:57  	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
14:06:57  go get: error loading module requirements
14:06:57  2019/09/02 12:06:47 e2e.go:77: err: go get -u k8s.io/test-infra/kubetest: exit status 1
14:06:57  exit status 1
```

**Comment by fejta** [comment]
Please use the following:`GO111MODULE=on GOPROXY=https://proxy.golang.org GOSUMDB=sum.golang.org go get k8s.io/test-infra`

**Comment by aanm** [comment]
> Please use the following:`GO111MODULE=on GOPROXY=https://proxy.golang.org GOSUMDB=sum.golang.org go get k8s.io/test-infra/kubetest`
> 
> Note that all of this is the default go1.13 behavior: https://golang.org/doc/go1.13#modules

@fejta Thanks but it would be really really great if we could avoid downloading the dependencies each time we run our CI with kubetest.

**Comment by stevekuznetsov** [comment]
How are you installing kubetest? If you are cloning `test-infra` and expecting `vendor/` you're still technically downloading it on the fly.

**Comment by aanm** [comment]
> How are you installing kubetest? If you are cloning `test-infra` and expecting `vendor/` you're still technically downloading it on the fly.

@stevekuznetsov Technically yes, in 1 single command, but not depending for all other repositories in a go.mod to be up and running. Even having proxies still doesn't solve it, if proxies are not correctly configured they also fail. Basically, it's not possible to build k8s.io/test-infra at this moment:

With `GOPROXY=https://proxy.golang.org` (See https://github.com/golang/go/issues/34033)
```
go: finding github.com/pkg/profile v1.2.1
go get: upgrading gopkg.in/jcmturner/rpc.v1@v1.1.0: unexpected status (https://proxy.golang.org/gopkg.in/jcmturner/rpc.v1/@v/v1.1.1.info): 410 Gone
2019/09/06 00:36:23 e2e.go:77: err: go get -u k8s.io/test-infra/kubetest: exit status 1
```

Without `GOPROXY`
```
go: finding github.com/xdg/scram latest
go get: upgrading git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git ls-remote -q origin in /home/aanm/test/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
2019/09/06 00:40:57 e2e.go:77: err: go get -u k8s.io/test-infra/kubetest: exit status 1
```

**Comment by stevekuznetsov** [comment]
@fejta can speak to the policy better than I but I think we will be trying to follow Golang's best practices here, which is using `go mod` exclusively and without a vendor directory. I imagine fetch issues will get better as people become more and more reliant on this.

**Comment by fejta** [comment]
Can you provide more details about your environment?

```console
$ go version
go version go1.13rc1 linux/amd64
$ env | grep GO
GOPROXY=https://proxy.golang.org
GO111MODULE=on
GOSUMDB=sum.golang.org
$ go get k8s.io/test-infra/kubetest
go: finding k8s.io/test-infra latest
go: downloading k8s.io/test-infra v0.0.0-20190909200258-2bf494983c15
go: extracting k8s.io/test-infra v0.0.0-20190909200258-2bf494983c15
go: finding github.com/satori/go.uuid v0.0.0-20160713180306-0aa62d5ddceb
go: finding golang.org/x/crypto v0.0.0-20190510104115-cbcb75029529
go: finding k8s.io/api v0.0.0-20190816222004-e3a6b8045b0b
go: finding k8s.io/apimachinery v0.0.0-20190816221834-a9f1d8a9c101
go: finding golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a
go: finding golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3
go: finding golang.org/x/time v0.0.0-20181108054448-85acf8d2951c
go: finding golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
```

**Comment by fejta** [comment]
The main thing here is do not use `-u`.

We know minor module upgrades do not work well:
* With modules off you'll get random versions of everything, which will almost certainly fail.
* With modules on k8s.io/kubernetes (and potentially other indirect deps) will blow up the upgrade: https://github.com/kubernetes/kubernetes/issues/81878

**Comment by aanm** [comment]
@fejta Now it seems to be working, but this could be avoided by having a vendor directory in the repo.

(Also, you have `go1.13rc1` not `go1.13`)

**Comment by Random-Liu** [comment]
```
go get: upgrading k8s.io/api@v0.0.0: k8s.io/api@v0.0.0: reading https://proxy.golang.org/k8s.io/api/@v/v0.0.0.info: 410 Gone
...
reading https://proxy.golang.org/k8s.io/apimachinery/@v/v0.0.0.info: 410 Gone
go: finding github.com/modern-go/reflect2 v1.0.1
2019/09/19 15:24:12 e2e.go:77: err: go get -u k8s.io/test-infra/kubetest: exit status 1
exit status 1
...
```

> The main thing here is do not use -u.

It does work without `-u`.

However, please note that `hack/e2e.go` uses `-u` by default. https://github.com/kubernetes/kubernetes/blob/master//hack/e2e.go#L159
