### ISSUE TITLE
go get kubetest failing with "unable to access 'https://git.apache.org/thrift.git/'"

### ISSUE THREAD

**Issue by adisky** [kubernetes/test-infra#14164]
**What happened**:
To solve failures of openstack conformance test, i followed the approach from here
https://github.com/kubernetes/test-infra/issues/14070#issuecomment-525651839 

i tried to install kubetest
 `export GO111MODULE=on
 go get -u  k8s.io/test-infra/kubetest`
but it is failing with error
`go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f https://git.apache.org/thrift.git refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/ubuntu/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
go get: error loading module requirements
`
**What you expected to happen**:
 go get -u  k8s.io/test-infra/kubetest, should run successfully

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by adisky** [comment]
I also found this, while searching for the issue
https://github.com/jenkins-x/jx/issues/3320

**Comment by fisherxu** [comment]
+1

**Comment by fisherxu** [comment]
also met this error, suggest to add the vender folder

**Comment by gaopenghigh** [comment]
same error

**Comment by schrodit** [comment]
same on our side. 
We experience this since friday

**Comment by alejandrox1** [comment]
Updates from SIG-testing slack channel ( https://kubernetes.slack.com/archives/C09QZ4DQB/p1567498382002500 ):

> yeah they moved to github, we have the same problem on tekton, simplest fix is : https://github.com/tektoncd/cli/pull/260/files (without the need to rename imports)

> and there is no problem in the build running in CI, wondering why problem in our env

> CI sets GOPROXY=https://proxy.golang.org globally iirc, meaning the go module cache is probably saving you..

**Comment by fejta** [comment]
Please use a proxy to download deps, which you can do by either:
* Using  go 1.13 (which enables this by default), and/or
* `export GOPROXY=https://proxy.golang.org && export GOSUMDB=sum.golang.org && export GO111MODULE=on`

**Comment by dpandhi-git** [comment]
Had same error yesterday , make sure GO111MODULE=on so that new modules can be downloaded

**Comment by adisky** [comment]
> Please use a proxy to download deps, which you can do by either:
> 
> * Using  go 1.13 (which enables this by default), and/or
> * `export GOPROXY=https://proxy.golang.org && export GOSUMDB=sum.golang.org && export GO111MODULE=on`

@fejta Thanks, we are able to run kubetest with above settings

**Comment by alejandrox1** [comment]
iirc this has been resolved. But please feel free to reopen otherwise.
/close
