### ISSUE TITLE
Build/tests are failing due to conflicts, even when there is none. 

### ISSUE THREAD

**Issue by hpandeycodeit** [kubernetes/test-infra#14179]
**What happened**:

After I have resolved the conflicts, the tests are failing with conflict errors:

```
HEAD is now at 975d0736b3... Merge pull request #82267 from kad/issue-1769
$ git branch --force master 975d0736b35d966c50383f794c0114a34fbcd9e4
$ git checkout master
Switched to branch 'master'
$ git fetch https://github.com/kubernetes/kubernetes.git pull/81688/head
From https://github.com/kubernetes/kubernetes
 * branch                  refs/pull/81688/head -> FETCH_HEAD
$ git merge --no-ff 55a347361c9619431b3112dde1090b479dcfdfa6
Auto-merging pkg/volume/util/operationexecutor/operation_generator.go
CONFLICT (content): Merge conflict in pkg/volume/util/operationexecutor/operation_generator.go
Auto-merging pkg/kubelet/dockershim/security_context.go
Auto-merging pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go
CONFLICT (content): Merge conflict in pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go
Auto-merging pkg/kubelet/dockershim/network/cni/cni_test.go
CONFLICT (content): Merge conflict in pkg/kubelet/dockershim/network/cni/cni_test.go
Auto-merging pkg/kubelet/dockershim/docker_service.go
Auto-merging hack/.staticcheck_failures
CONFLICT (content): Merge conflict in hack/.staticcheck_failures
Auto-merging cmd/kubelet/app/server.go
Automatic merge failed; fix conflicts and then commit the result.
# Error: exit status 1

```

**What you expected to happen**:
It should be able to build/test the changes without any issues if there are no conflicts. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a PR with some conflicts, resolve them and push the changed to the last commit ( not a new commit)

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81688/pull-kubernetes-verify/1168951568754544640

**Anything else we need to know?**:
None

**Comment by BenTheElder** [comment]
sometimes right after pushing to github prow receives the old state. did this happen after retesting or only after the initial push?

**Comment by stevekuznetsov** [comment]
And the comment has stale results while new ones are running, too. I'd imagine this is due to poor UX from Prow, but not a bug
