### ISSUE TITLE
verify-owners: misleading error message

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#14201]
Currently the `verify-owners` plugin states that users must be members of the org:

https://github.com/kubernetes/test-infra/blob/4782ba3a238e4c52de4a39d4e4b25f0822dc61ef/prow/plugins/verify-owners/verify-owners.go#L46

When in reality it is using the `trigger.TrustedUser` call:

https://github.com/kubernetes/test-infra/blob/4782ba3a238e4c52de4a39d4e4b25f0822dc61ef/prow/plugins/verify-owners/verify-owners.go#L500

This uses the `trigger` configuration to do many checks, only one of which is the organization membership one, and only conditionally:

https://github.com/kubernetes/test-infra/blob/4782ba3a238e4c52de4a39d4e4b25f0822dc61ef/prow/plugins/trigger/trigger.go#L164-L194

We should make `trigger.TrustedUser` return a reason for not being trusted so that we can have correct messages.

/help-wanted

**Comment by nikhita** [comment]
Related issues: https://github.com/kubernetes/test-infra/issues/13740, https://github.com/kubernetes/test-infra/issues/13002

**Comment by stevekuznetsov** [comment]
@nikhita you are so fast! <3

**Comment by kikisdeliveryservice** [comment]
hi, could i work on this?

**Comment by stevekuznetsov** [comment]
@kikisdeliveryservice absolutely!

**Comment by cblecker** [comment]
@kikisdeliveryservice Is this something you're still looking to work on? :)

**Comment by kikisdeliveryservice** [comment]
@cblecker yes apologies, I have a wip that I will clean up and push a PR in the next few days

**Comment by sladyn98** [comment]
@stevekuznetsov Do we need to change the error message here or just add the reason as to why we arent trusted like not an org admin

**Comment by cblecker** [comment]
Fixed in #17658
