### ISSUE TITLE
override: allow top-level OWNERS to override contexts

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#14205]
Today the `override` plugin uses GitHub access control (repository admin) to determine if a user can use `/override`. The rest of Prow and the SIG in general wants to move away from using these access controls and having workflows that require more than read access, so we should use some other means of detecting this. For instance, we could use the top-level OWNERS files for a list of people who can `/override`.

/area hook
/cc @cblecker @nikhita @cjwagner @fejta

**Comment by cblecker** [comment]
Either that, or a GitHub team (that isn't necessarily tied to permissions).

**Comment by stevekuznetsov** [comment]
GitHub team might be a nice option but does not scale, implicit OWNERS will be less friction.

**Comment by nikhita** [comment]
Why not both :upside_down_face: 

We can have config options like `allow_top_level_owners` _and_ `github_teams` (containing info about team id and name) and the repo maintainers can decide which ones they'd like to use.

**Comment by nikhita** [comment]
And repo admins would have power to override implicitly too (existing behaviour)

**Comment by stevekuznetsov** [comment]
All three sounds good :)
