### ISSUE TITLE
Passed gce-master-scale-performance marked with "R", not colored green

### ISSUE THREAD

**Issue by oxddr** [kubernetes/test-infra#14218]
**What happened**:
[gce-master-scale-performance](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance) is marked with "R" in testgrid, but Prow shows it [passed](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1168932189639806976). 

**What you expected to happen**:
Test to be colored green. 

**How to reproduce it (as minimally and precisely as possible)**:
Not sure. 

**Please provide links to example occurrences, if any**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance on 09/03

**Anything else we need to know?**:

**Comment by chases2** [comment]
It looks like log exporting ran into some issues with this run. While it didn't fail your test, I suspect that it didn't correctly write the successful results of that test.

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1168932189639806976

**Comment by oxddr** [comment]
I don't know exactly how integration between testgrid and prow works. However logexporter is used only to dump logs from nodes, which are not used to determine test status. Prow displays this jobs as [SUCCESS](https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance). 

The only thing that differs from a run displayed correctly is missing tab "Prow Job YAML":
![missing](https://user-images.githubusercontent.com/30298753/64622777-277eb700-d3e8-11e9-9313-d61213225beb.png)
