### ISSUE TITLE
install prow using tackle stuck in 'Looking for prow's hook ingress URL'

### ISSUE THREAD

**Issue by iwasnobody** [kubernetes/test-infra#14213]
The k8s cluster is created using kops running in aws ec2.
The installation process stuck like following:

Prow will act as prow-ivan on github
Applying github token into oauth-token secret...secret/oauth-token created
Ensuring hmac secret exists at hmac-token...INFO[0009] Creating new hmac-token secret with random data... 
exists
Looking for prow's hook ingress URL... ......................................................................................................................................................

Is there something wrong with ingress?
root@ip-10-102-91-15:~/test-infra# kubectl get ing ing
NAME   HOSTS   ADDRESS   PORTS   AGE
ing        *                                  80          37m

**Comment by stevekuznetsov** [comment]
It doesn't look like your ingress has any address -- it might be misconfigured or you might need to wait for one to exist. More documentation is [here](https://docs.google.com/document/d/1f-mOhwFZ9Z6f7o8Ckg3Nq2A8eXU_H1yxRxURp8jOtRI/edit#).

**Comment by iwasnobody** [comment]
> It doesn't look like your ingress has any address -- it might be misconfigured or you might need to wait for one to exist. More documentation is [here](https://aws.amazon.com/blogs/opensource/kubernetes-ingress-aws-alb-ingress-controller/).

Yes. I use alb ingress controller. According to the user guide, the ingress need to have "kubernetes.io/ingress.class: alb" to tell the controller to create an aws alb for the ingress.
https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/

The ingress created by tackle doesn't have this annotation. Do you know how to tailor it to add the annotation when create the ingress?

**Comment by iwasnobody** [comment]
Or I have to use another ingress controller?

**Comment by stevekuznetsov** [comment]
I'm not certain -- I think the controller you are using would work, as well. I am not an expert on AWS ingresses, so I can't tell exactly why yours has no address yet.

**Comment by iwasnobody** [comment]
> I'm not certain -- I think the controller you are using would work, as well. I am not an expert on AWS ingresses, so I can't tell exactly why yours has no address yet.

I have got the alb created successfully by using kubectl edit ing ing and add necessary annotations.
But the prow still stuck in Looking for prow's hook ingress URL... , quite strange.

The alb is created in aws successfully and all the backend is healthy.

root@ip-10-102-91-15:~# kubectl get ing ing
NAME   HOSTS   ADDRESS                                                                          PORTS   AGE
ing        *       internal-cc111e9c-default-ing-3628-1969600427.ap-northeast-1.elb.amazonaws.com   80      130m

**Comment by stevekuznetsov** [comment]
If you stop the `tackle` tool and re-run it, what is the output?

**Comment by iwasnobody** [comment]
re-run doesn't solve the problem.

Do you know when will "Looking for prow's hook ingress URL" be success? What is the underline process like some pod will send GET request to the url to verify it?

**Comment by stevekuznetsov** [comment]
I am not sure, @fejta could know better -- source code is [here](https://github.com/kubernetes/test-infra/blob/a90ef96889f834c21309ce9278d67dae5bff536e/prow/cmd/tackle/main.go#L627)

**Comment by clarketm** [comment]
> I have got the alb created successfully by using kubectl edit ing ing and add necessary annotations. But the prow still stuck in Looking for prow's hook ingress URL... , quite strange.

@iwasnobody

The ingress spec is defined in the [`starter.yaml`](https://github.com/kubernetes/test-infra/blob/5798a46d058762df45bbfac6b86bfc61e7e6983b/prow/cluster/starter.yaml#L443-L462). In addition to `kubernetes.io/ingress.class: alb`, what `annotations` did you need to add to get the ingress created? Is your instance of Prow now functional with the manual edit of the `ing`?

**Comment by iwasnobody** [comment]
> > I have got the alb created successfully by using kubectl edit ing ing and add necessary annotations. But the prow still stuck in Looking for prow's hook ingress URL... , quite strange.
> 
> @iwasnobody
> 
> The ingress declaration is defined in the [`starter.yaml`](https://github.com/kubernetes/test-infra/blob/5798a46d058762df45bbfac6b86bfc61e7e6983b/prow/cluster/starter.yaml#L443-L462). In addition to `kubernetes.io/ingress.class: alb`, what `annotations` did you need to add to get the ingress created in AWS? Is your instance of Prow now functional with the manual edit of the `ing` metadata?

Prow not functional, still stuck in looking for prow's hook ingress URL.
There are many annotations you can add to tailor the config of AWS ALB. The following is what I added. Basically it includes specify the vpc subnet, security group, listen port, etc for the ALB.
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: sg-0c50ac217b097a0xx
    alb.ingress.kubernetes.io/subnets: subnet-0b8d4201b83a4axxe, subnet-0c9a13cdexx2c38dd,subnet-0193ffd22047dxx95

**Comment by iwasnobody** [comment]
@clarketm Just modify the starter.yaml to add the annotation, but still stuck.
Not quite understand what ingress url does tackle looking for. How to make this verification process pass?

**Comment by iwasnobody** [comment]
BTW, access the ALB can open the prow dashboard. Can I just cancel the "Looking for prow's hook ingress URL"? Will it missing install other components if I cancel it?

**Comment by clarketm** [comment]
@iwasnobody 

> How to make this verification process pass?

This is the *specific* [procedure](https://github.com/kubernetes/test-infra/blob/0708557a156535e88d67766c50b60d0b9cb04c3e/prow/cmd/tackle/main.go#L646-L707) that determines if an ingress is **detected** or not. It is interesting that the ingress is up and responsive, yet `tackle` is not detecting it.

> Can I just cancel the "Looking for prow's hook ingress URL"? Will it missing install other components if I cancel it?

The last major step after verifying ingress is [enabling the Github webhook](https://github.com/kubernetes/test-infra/blob/0708557a156535e88d67766c50b60d0b9cb04c3e/prow/cmd/tackle/main.go#L971) which is a vital step to a functional Prow setup. You can either try to follow the `enableHooks` function or add it manually to your Github org.

https://github.com/kubernetes/test-infra/blob/0708557a156535e88d67766c50b60d0b9cb04c3e/prow/cmd/tackle/main.go#L786-L848

![image](https://user-images.githubusercontent.com/9957358/64671242-a392f200-d41c-11e9-9a01-7ad7f5814992.png)

1. Set the **Payload URL** to the *ingress address* with `/hook` path (e.g. `http://35.244.210.98/hook`).
2. Set the **Secret** to the `hmac-token` secret in the cluster (e.g. `kubectl get secrets hmac-token -o jsonpath='{.data.hmac}' |  base64 -d`)

**Comment by iwasnobody** [comment]
worked after manually config github webhook. thx
