### ISSUE TITLE
Remove knative/build options/dependencies from prow

### ISSUE THREAD

**Issue by vdemeester** [kubernetes/test-infra#14217]
**What should be cleaned up or changed**:

Knative build ([`knative/build`](https://github.com/knative/build)) is now deprecated and read-only, hence not maintained anymore — see https://github.com/knative/build/issues/614 for the history.

Prow shouldn't rely on it as it is not maintained anymore, and should focus on [`tektoncd/pipeline`](https://github.com/tektoncd/pipeline) instead (which is kinda already the case as it is also supported in Prow). 

*Additionnaly, this would remove `github.com/knative/*` dependencies as `knative/build` didn't switch to those before being deprecated*.

/cc @bobcatfish @ImJasonH

**Provide any links for context**:

See https://github.com/kubernetes/test-infra/pull/14216#discussion_r321749573

**Comment by stevekuznetsov** [comment]
Alternatively, can we copy paste the client types from these third-party dependencies into `third_party/` to ensure that `prow` does not import the whole world and ameliorate all of our current issues re: imports?

/cc @cjwagner @cblecker @fejta

**Comment by vdemeester** [comment]
#15022 is merged, this can be closed
/close
