### ISSUE TITLE
Add a rerun button to Spyglass.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#14226]
## What would you like to be added:
We can now directly rerun ProwJobs from Prow's front page using GitHub oauth. This is feature is access through the rerun dialog that is exposed by clicking on one of the circular arrows on the left side of the page. See for yourself at https://prow.k8s.io

It would be super useful to expose this feature from the spyglass page since that is where job results are viewed and is almost certainly the most common way that devs use Deck.

## Why is this needed:

Currently there isn't an easy way to navigate from a spyglass page to the same job run on Decks front page. (This is a problem of its own, but it really only impacts the usability of the rerun button at this point.)  Devs need to use the filters on the front page to find matching jobs and even then there may be multiple runs of the job on the same commit that are not distinguishable from the UI.

@Katharine I think you are probably most familiar with this code. Do you think there are any 'gotchas' here regarding the oauth redirection?

cc @stevekuznetsov @fejta @alvaroaleman 
/help

**Comment by stevekuznetsov** [comment]
The other gotcha here is a "_re_run" button requires us to know the ProwJobSpec as resolved at run-time the first time around. We would need to upload those to GCS to get a _re_run button. A _run_ button, though, should be fine.

**Comment by alvaroaleman** [comment]
> The other gotcha here is a "_re_run" button requires us to know the ProwJobSpec as resolved at run-time the first time around

Isn't there the clonerefs json that can tell us? We could btw start just uploading the serialized ProwJob to avoid having different data structures on GCS that may or may not contain certain infos.

**Comment by stevekuznetsov** [comment]
I've been advocating for an upload of the full ProwJob YAML (and the Pod to boot) for a long time. I understand why there is this `{started,finished}.json` compatibility layer for jobs not using pod-utils and other systems like testgrid but I think Prow inside of it's own bubble should be uploading that data to better serve users in `deck`.

**Comment by cjwagner** [comment]
> The other gotcha here is a "_re_run" button requires us to know the ProwJobSpec as resolved at run-time the first time around. We would need to upload those to GCS to get a _re_run button. A _run_ button, though, should be fine.

I agree that reading the ProwJob spec from GCS would be nice, but we don't need that initially. We can do the same thing we are doing on the front page if the ProwJob resource is still available and just hide the link if it isn't like we do for the ProwJob YAML button on spyglass.

**Comment by matthyx** [comment]
@cjwagner do you still need help on this issue?

**Comment by cjwagner** [comment]
Sure, that would be great. We also now upload the ProwJob JSON so we can use that to rerun even after the ProwJob CRD has been GCed.

**Comment by Katharine** [comment]
We should not use the prowjobs stored in GCS for this, for security reasons.

In particular, I would have the following two concerns:

- Spyglass does restrict itself to any given sets of buckets or otherwise in GCS. You could trivially point it to a different location and ask it to rerun that job, giving you effectively the ability to run any arbitrary prowjob you like
- Jobs have the freedom to upload anything they like to anywhere in the storage bucket. This includes the ability to upload their own prowjobs, which again grants them the ability to run arbitrary prowjobs (and which would therefore effectively constitute privilege escalation).

Both of these issues are resolvable, but not trivially. We could also plausibly restrict what clusters you are permitted to rerun to from GCS, which could help some (at the cost of some convenience).

**Comment by spiffxp** [comment]
/remove-help
/assign @clarketm 
Please /unassign if I'm incorrect that you're planning on tackling

**Comment by clarketm** [comment]
Sure, I can work on this. How do we want to handle the security concerns @Katharine mentioned (https://github.com/kubernetes/test-infra/issues/14226#issuecomment-578938142) be addressed

**Comment by matthyx** [comment]
/remove-lifecycle stale
What's up with that one?

**Comment by alvaroaleman** [comment]
I don't think there are any blockers for this. Essentially, the spyglass page should show a re-run button just like the deck front page if we still have the prowjob resource in cluster. The security concerns were about using the prowjob from GCS where I agree that this might be problematic

**Comment by matthyx** [comment]
I am not familiar enough with web technologies to make that change...
/remove-lifecycle rotten
/help

**Comment by alvaroaleman** [comment]
I am confused, didn't we add this in https://github.com/kubernetes/test-infra/pull/22711 ? (But I don't see the button anywhere)

**Comment by chaodaiG** [comment]
Oh right, I totally missed #22711, this should be closed. 

I'm not seeing the button anywhere either, I'll open a bug instead

/close

**Comment by chaodaiG** [comment]
nvm, I saw the button now https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-addons/103/pull-cluster-addons-unit-test/1435246255381942272

![Screen Shot 2021-09-07 at 7 21 14 AM](https://user-images.githubusercontent.com/45011425/132361109-6d84e84a-7ff5-4276-9957-c39c47c56c1f.png)

probably was checking old jobs before. sorry for the noise

**Comment by YuviGold** [comment]
@chaodaiG a full explanation about when the button is shown can be found on this comment
https://github.com/kubernetes/test-infra/pull/22711/files#r660960346
