### ISSUE TITLE
Tide status controller: Don't report success status when test results are outdated

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#14233]
**What would you like to be added**:

The tide status controller to report "All tests have successful results and all labels are there, but this PR is waiting to get retested" as "Pending", not "Successful".

**Why is this needed**:

Currently, when a PR was successfully tested and has all required labels but is waiting to get retested, the tide status context is set to `successful`. This is confusing for users who don't know why their PR isn't getting merged.

**Comment by stevekuznetsov** [comment]
Will users _ever_ see a successful status in this case? Or will it just remain pending until they're merged?

**Comment by alvaroaleman** [comment]
> Will users ever see a successful status in this case? Or will it just remain pending until they're merged?

It will remain pending until its merged which is IMHO the correct behavior as "successful" means "ready to be merged" which is not actually true in the case of outdated tests.

**Comment by stevekuznetsov** [comment]
I guess to a Tide dev successful means "in the pool" but yes if we want to redefine that, I agree with you.

**Comment by cjwagner** [comment]
> Or will it just remain pending until they're merged?

It will actually remain pending forever since Tide doesn't try to set statuses on closed PRs.

**Comment by alvaroaleman** [comment]
/reopen
Badly worded PR message again, #14235 does not fix this but is a requirement to be able to fix this.

/assign
