### ISSUE TITLE
Add exceptions for prow plugins/Make prow work nicer with other bots

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/test-infra#14242]
**What would you like to be added**: We would like to be able to make exceptions for some plugins if the pull request is created by specific user (bot account in my case). 

If that is not possible I'd at least like `release-note-none` prevent prow from adding `do-not-merge/release-note-label-needed` (IMO this should be done anyways).

**Why is this needed**: We are using [Dependabot](https://dependabot.com/) to to keep our dependencies up to date. Each pull request that is created by the bot is marked with the `do-not-merge/release-note-label-needed` and besides that we need to manually execute the tests. That means if we would like to merge the dependency update pull request we need to execute each time following commands:

```
/lgtm
/approve
/test all
/release-note-none
```

We would like to use only `/lgtm` and `/approve` without tuning off the plugins like release notes for other users.

**Note:** Adding `release-note-none` label to bots configuration didn't help. The pull requests are still marked with `do-not-merge/release-note-label-needed`.
**Note:** We are not able to edit the bot's pull request body.

**Comment by maciaszczykm** [comment]
>If that is not possible I'd at least like release-note-none prevent prow from adding do-not-merge/release-note-label-needed (IMO this should be added anyways).

<img width="776" alt="Zrzut ekranu 2019-09-9 o 14 22 16" src="https://user-images.githubusercontent.com/2823399/64530428-6724a080-d30d-11e9-859c-cde9e9367a4e.png">

The picture might explain it better.

**Comment by stevekuznetsov** [comment]
Are you actually using the release note process for your org? Why not automate a release note that explains which dependencies were bumped? Or one that explicitly states nothing?

**Comment by alvaroaleman** [comment]
@stevekuznetsov yes we do use the release notes and as Marcin noted, its not possible to configure a PR template for dependabot, only labels.

Lowest hanging fruit here is definitely to make the release-note plugin respect an existing `release-note-none` label.
