### ISSUE TITLE
Cherrypicker docs: what events does it need access to?

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#14244]
Right now our config looks like:

```
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
```

When we apply a label, it will do a cherrypick only if the label is applied before the merge takes place. `/cherrypick` always works, even after merge. Do we need to add some event to get it to detect the label addition?

It would be great if this could be documented in https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/cherrypicker.

Thanks!

**Comment by stevekuznetsov** [comment]
I'm pretty sure the [name](https://github.com/kubernetes/test-infra/blob/5deb5b970e73cdd55b3068b9c50962e8657bdb23/prow/external-plugins/cherrypicker/server.go#L39) of the plugin is `cherrypick`, not `cherrypicker` -- that may be your issue?

```yaml
  - name: cherrypick
    events:
    - issue_comment
    - pull_request
```

**Comment by howardjohn** [comment]
@stevekuznetsov now I am a bit more confused, since it works with `cherrypicker` its just when the label is applied after merge it isn't handling this properly :confused:

**Comment by stevekuznetsov** [comment]
Or maybe that `name` is actually the name of the service in the cluster where events are sent -- so if you named it `cherrypicker` that would work. Sorry, gotta dust off the :spider_web: from this code ...

**Comment by stevekuznetsov** [comment]
But those two types of events are the only ones it would need -- Are there any errors in the logs? Maybe it's just not written to honor the label.
