### ISSUE TITLE
bug: prow dashboard reports duration for a short tests as 25h+

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#14259]
**What happened**:
On the page https://prow.istio.io/?job=ci-test-infra-branchprotector,  the duration ranges between 25h and 26h. The chart at the top shows the correct time, ~40s. Individual jobs on spyglass also report the correct time.

**What you expected to happen**:
Duration recorded correctly

**Comment by clarketm** [comment]
/close

Duplicate: #14250
Fixed: #14252

@howardjohn - The fix will be in tomorrow's Prow release.

**Comment by howardjohn** [comment]
nice, thanks!

**Comment by clarketm** [comment]
Prow was not released today, but this change will be in the *next* release.
