### ISSUE TITLE
Boskos Image Deployments Automation

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#14267]
**What would you like to be added**:
Boskos is a unique sort of image that we support because its image deployment and promotion to the next version are still largely manual.

**Why is this needed**:
Deployments need to be done manually (see #14266), often in response to issues, and it leaves us digging for which version is running or if/when it was updated.

/priority important-soon
/assign @clarketm

**Comment by clarketm** [comment]
Thanks to @fejta in #14276 this will be *bazelified*. I will create the postsubmit.
