### ISSUE TITLE
question: simplifying rerun_command/trigger

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#14265]
Copying https://github.com/istio/test-infra/issues/1762 over to here as suggested by @clarketm 

Prow has two fields:

```
   trigger: "(?m)qux test this( please)?" # Regexp, see discussion.
   rerun_command: "qux test this please"  # String, see discussion.
```

Say we have a job `unit-tests_istio_release-1.3`

Right now a user can `/test all`, `/retest`, `/test unit-tests_istio_release-1.3` and they will all trigger it.

A better UX would just be to type `/test unit-tests`

if we set `trigger: /test unit-tests` will this give us expected outcome? 

Specifically, will it be smart enough to not trigger the `unit-tests_istio_release-1.2` (different release) or `unit-tests_OTHERREPO_release-1.3` tests? And will `retest`/`test all` still work or do we need some crazy regex for those?

**Comment by cjwagner** [comment]
> if we set `trigger: /test unit-tests` will this give us expected outcome?
> 
> Specifically, will it be smart enough to not trigger the `unit-tests_istio_release-1.2` (different release) or `unit-tests_OTHERREPO_release-1.3` tests? And will `retest`/`test all` still work or do we need some crazy regex for those?

Yes, that should all work as you expect, thats exactly what these fields are for 😃 Note that if you specify a `trigger` regexp you also have to specify a `rerun_command` for Prow to suggest to users when the job fails.

**Comment by howardjohn** [comment]
thank you!
