### ISSUE TITLE
kubetest compile error

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/test-infra#14260]
**What happened**:

#14070 suggested to set `GO111MODULE=on`, while it's still failed with error:

```
export GO111MODULE=on
go run hack/e2e.go -- --test 

# k8s.io/test-infra/kubetest
/go/pkg/mod/k8s.io/test-infra@v0.0.0-20190909224254-31b4bf7cd817/kubetest/eks.go:131:2: cannot use dp (type *eksDeployer) as type ekstester.Deployer in return argument:
        *eksDeployer does not implement ekstester.Deployer (missing KubernetesClientSet method)
2019/09/10 05:23:24 e2e.go:77: err: go get -u k8s.io/test-infra/kubetest: exit status 2
exit status 1
```

**What you expected to happen**:

kubetest should be compiled successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by nilo19** [comment]
Try to fix in https://github.com/kubernetes/test-infra/pull/14261.
