### ISSUE TITLE
TestGrid Alerts on Staleness while disabled

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#14274]
**What happened**:
I got the following email (excerpt):
```
New Top Level Warning for sig-testing-images#bigquery:
Warning: Test results are stale (no results found).

There are no new failures since the last alert.


TestGrid Link: https://k8s-testgrid.appspot.com/sig-testing-images#bigquery
```

The test in question is stale, so it isn't displaying a failure. The test is configured as an [annotation](https://github.com/kubernetes/test-infra/blob/2da5e7991b3138db46e35af25077d35b94945a76/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L360-L365), not specifying a stale alerting data.

The [default value](https://github.com/kubernetes/test-infra/blob/2da5e7991b3138db46e35af25077d35b94945a76/config/testgrids/default.yaml#L14) for stale alerting is `0`, meaning "do not alert on staleness"

**What you expected to happen**:
Nothing

**How to reproduce it (as minimally and precisely as possible)**:
Root cause unknown; reproducing it might be difficult

**Please provide links to example occurrences, if any**:
See email excerpt above. No other reports seem to be similar to this.

**Anything else we need to know?**:

/priority backlog
/area testgrid
/assign
/assign @michelle192837

**Comment by michelle192837** [comment]
Welp, figured it out. Dashboard tab alerts do not actually care about that field!

**Comment by chases2** [comment]
Note: This occurred again with `https://k8s-testgrid.appspot.com/sig-testing-images#bootstrap`.

I'll need to do some research to figure out which tests are "infrequently-running" and should store more days, but it's at least these two.

**Comment by BenTheElder** [comment]
https://k8s-testgrid.appspot.com/sig-testing-images#kettle is now stale

I think @Katharine mentioned that the important bug here is that the job should be running ... ?

**Comment by Katharine** [comment]
> https://k8s-testgrid.appspot.com/sig-testing-images#kettle is now stale
> 
> I think @Katharine mentioned that the important bug here is that the job should be running ... ?

That's my reading comprehension fail - these particular jobs almost never run (but we should probably bump their retention...)

**Comment by Katharine** [comment]
> Note: This occurred again with [bootstrap](https://k8s-testgrid.appspot.com/sig-testing-images#bootstrap).
> 
> I'll need to do some research to figure out which tests are "infrequently-running" and should store more days, but it's at least these two.

All of the `sig-testing-images` dashboard is expected to be intermittent

**Comment by michelle192837** [comment]
Yeah, definitely bump the `days_of_results` for these jobs if you don't expect them to run frequently. Most jobs shouldn't go beyond 30 days unless they're very infrequent (so this qualifies).

**Comment by michelle192837** [comment]
This should be fixed, alerts won't fire for staleness unless `alert_stale_results_hours` is explicitly set.
