### ISSUE TITLE
//prow/interrupts:go_default_test is flaky

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14328]
/assign @stevekuznetsov 

`bazel test //prow/interrupts:go_default_test --runs_per_test=100` shows that this test will both pass and fail

/area prow

w/o RBE it looks like it will fail > 90% of the time (on my machine), on either go1.12.9 or go1.13
On RBE I'm having trouble completing it, seems to fail somewhat less frequently:

```console
$ bazel test //prow/interrupts:go_default_test --runs_per_test=20

INFO: Elapsed time: 10.590s, Critical Path: 9.42s
INFO: 84 processes: 44 remote cache hit, 40 remote.
INFO: Build completed, 1 test FAILED, 65 total actions
//prow/interrupts:go_default_test                                        FAILED in 10 out of 20 in 4.9s
  Stats over 20 runs: max = 4.9s, min = 2.5s, avg = 3.7s, dev = 0.7s

$ bazel test //prow/interrupts:go_default_test --runs_per_test=20
INFO: Elapsed time: 13.642s, Critical Path: 9.32s
INFO: 83 processes: 43 remote cache hit, 40 remote.
INFO: Build completed, 1 test FAILED, 64 total actions
//prow/interrupts:go_default_test                                        FAILED in 14 out of 20 in 4.9s
  Stats over 20 runs: max = 4.9s, min = 2.5s, avg = 3.5s, dev = 0.7s
```

This is at commit b6725b4398f67d47eb0ab860c17d135e3a90c86a

Error is:

```
==================== Test output for //prow/interrupts:go_default_test:
time="2019-09-13T22:52:58Z" level=info msg="Received signal." signal=hangup
time="2019-09-13T22:52:58Z" level=info msg="Interrupt received."
time="2019-09-13T22:52:58Z" level=info msg="Server shutting down..."
time="2019-09-13T22:52:58Z" level=warning msg="Timed out waiting for workers to gracefully terminate, exiting."
--- FAIL: TestInterrupts (1.35s)
    interrupts_test.go:182: server registered with ListenAndServe() was not cancelled on interrupt
    interrupts_test.go:188: server registered with ListenAndServeTLS() was not cancelled on interrupt
time="2019-09-13T22:52:58Z" level=info msg="Worker shutting down..."
time="2019-09-13T22:52:58Z" level=info msg="Server shutting down..."
FAIL
================================================================================
```

Example of flake in CI: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-test-infra-autoupdate-patch/1172526856373538829

**Comment by stevekuznetsov** [comment]
Hmm. I did this locally, too, since I knew it had a chance of flaking, but I had a good success rate. Do you have ideas on how we could improve it, other than adding really long wait times?

/cc @cjwagner

**Comment by stevekuznetsov** [comment]
There also seem to be other, odd errors using that (cool, heretofore unknown) feature of `bazel`:

```
time="2019-09-16T14:46:10Z" level=info msg="Server exited." error="listen tcp :9999: bind: address already in use"
```

Doesn't look like an error we would normally hit

**Comment by cjwagner** [comment]
> Do you have ideas on how we could improve it, other than adding really long wait times?

If we're checking to see if an asynchronous function completes in reaction to a signal I think our only option is to use a long wait time.

**Comment by stevekuznetsov** [comment]
This should be fixed -- couldn't get it to fail in a couple hundred of runs with the new waits.
/close
