### ISSUE TITLE
periobolos keep going on error

### ISSUE THREAD

**Issue by jlewi** [kubernetes/test-infra#14321]
**What would you like to be added**:
Right now peribolos aborts on errors. For example we see peribolos failing with a 404 (kubeflow/internal-acls#154)

```
{"component":"peribolos","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership\"}","file":"prow/cmd/peribolos/main.go:441","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(kubeflow, rem20806, false) failed","time":"2019-09-13T15:32:47Z"}
```
It looks like the 404 is caused because the account rem20806 doesn't exist.

As a result the sync aborts.

Would it be possible to keep going so that typos or users deleting their account doesn't break the sync?

**Comment by clarketm** [comment]
@jlewi
While `peribolos` does log an error it should **not** crash the sync: 
https://github.com/kubernetes/test-infra/blob/e1cbc3ccd91cdf2d1c229d61f996d12033a96500/prow/cmd/peribolos/main.go#L443-L447

> Note: using the *old* image you referenced this was not the case https://github.com/kubeflow/internal-acls/issues/154#issue-493386323 but with an up-to-date image this is the case https://github.com/kubeflow/internal-acls/issues/154#issuecomment-531289684
