### ISSUE TITLE
Ability to add team by name to rerun auth configuration

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#14336]
**What would you like to be added**:
Ability to accept **team** *by name* in rerun auth configuration. This can be an additional list item in the `rerun_auth_config` map (e.g. `github_team_names`). The Github API exposes an endpoint to [`Get team by name
`](https://developer.github.com/v3/teams/#get-team-by-name) so the lookup should be simple. The one additional piece of information needed to lookup a team *by name* is the **organization** (e.g. Istio), so the *value* added to the list can either be a map itself, or for simplicity, a string in the form: `org/slug` (e.g. `istio/wg-test-and-release-maintainers`).

**Current**
https://github.com/kubernetes/test-infra/blob/de955ac78f9928febbcef1631c6f298d07ba920d/prow/config.yaml#L47-L52

**Proposed**
> **Note:** we will *continue* to accept `github_team_ids` for back-compat.
```yaml
 rerun_auth_config: 
   github_users: 
     - mirandachrist 
     - clarketm 
   github_team_names: 
     - kubernetes/test-infra-admins 
```

**Why is this needed**:
It is much more *intuitive* to identify a team by its `name` rather than its `id`. Furthermore, it is easier to derive and manage a list of human-readable names than a list of ids. There are no obvious drawbacks to this proposal; since the organization is **included** in the string value, it is guaranteed to be a unique identifier. This merely adds the additional benefit of readability. We will *continue* to accept `github_team_ids` for back-compat.

/help
/good-first-issue

**Comment by vjdhama** [comment]
@clarketm I would like to pick this up. Would need some help though. Is it ok if I reach out on slack?

**Comment by clarketm** [comment]
@vjdhama
Great! Yes, feel free to reach out to me on slack if you have any questions.

**Comment by clarketm** [comment]
@vjdhama
It appears that a form of this has already been implemented, we are just not using it.
https://github.com/kubernetes/test-infra/blob/7a71340ed29351cb471527939025135bb863dc28/prow/apis/prowjobs/v1/types.go#L193
