### ISSUE TITLE
Revision link on deck has no href?

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#14388]
**What happened**:
Clicking revision link on a job (e.g. `master (f069632)` on https://prow.k8s.io/?job=post-test-infra-upload-testgrid-config) just links back to the same Prow status page (e.g. back to `https://prow.k8s.io/?job=post-test-infra-upload-testgrid-config`)

(Specifically, looks like that link is just an anchor with no href, `<a href="">master (f069632)</a>`).

**What you expected to happen**:
Links to a page in GitHub comparing PRs (like `master (e0a1e8e)` linking to `https://github.com/kubernetes/test-infra/compare/8d489a55140e...e0a1e8e0d0f9` on that same page)

**How to reproduce it (as minimally and precisely as possible)**:
Click `master (f069632)` on https://prow.k8s.io/?job=post-test-infra-upload-testgrid-config

**Please provide links to example occurrences, if any**:
`master (f069632)` on https://prow.k8s.io/?job=post-test-infra-upload-testgrid-config

**Anything else we need to know?**:
N/A

/area prow

**Comment by BenTheElder** [comment]
> Clicking revision link on a job (e.g. master (f069632) on https://prow.k8s.io/?job=post-test-infra-upload-testgrid-config) just links back to the same Prow status page (e.g. back to https://prow.k8s.io/?job=post-test-infra-upload-testgrid-config)

that looks to work correctly now?

**Comment by michelle192837** [comment]
Agreed, though it also definitely wasn't working when I filed. :/ I can try and check the code populating that link, and close if I don't see anything obvious?

**Comment by michelle192837** [comment]
This might just be when a base_link isn't populated for whatever reason? Can't reproduce atm and it doesn't seem to happen often, so closing for now.
