### ISSUE TITLE
Postsubmit jobs run on commits where they have been removed

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#14389]
**What happened**:
The job `post-test-infra-upload-testgrid-config` was triggered on a series of commits where that postsubmit job was removed [1]. This caused the job to fail, because it was running on a version of the codebase that it wasn't intended to. Similarly, the final run of `maintenance-ci-testgrid-config-upload` [2] ran on a commit where it was removed from the config.

**What you expected to happen**:
Postsubmit jobs to run only if they still exist in the submitted version of the code.

**How to reproduce it (as minimally and precisely as possible)**:
Delete a postsubmit job

**Please provide links to example occurrences, if any**:
1. `post-test-infra-upload-testgrid-config` [Spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-upload-testgrid-config/1174423924893552640), [Revision](https://github.com/kubernetes/test-infra/compare/8d489a55140e...e0a1e8e0d0f9)

2.  `maintenance-ci-testgrid-config-upload` [Spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/maintenance-ci-testgrid-config-upload/1174413484100685824), [Revision](https://github.com/kubernetes/test-infra/compare/71036659d320...f069632b87ea)

Also see Prow History for [`post-test-infra-upload-testgrid-config`](https://prow.k8s.io/?repo=kubernetes%2Ftest-infra&job=post-test-infra-upload-testgrid-config) and [`maintenance-ci-testgrid-config-upload`](https://prow.k8s.io/?repo=kubernetes%2Ftest-infra&job=maintenance-ci-testgrid-config-upload)

**Comment by stevekuznetsov** [comment]
Not sure this will be possible with our current architecture -- the config-updater is entirely async and there's no connection between loaded config and the repo it was loaded from :(

**Comment by alvaroaleman** [comment]
https://github.com/kubernetes/test-infra/issues/13370 would be the fix to this
