### ISSUE TITLE
Image publishing jobs incorrectly use the deployer credentials

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#14390]
**What happened**:
I noticed that all or nearly all of our image publishing jobs are using the same service account and token that we use for deploying Prow.
See jobs that mount `deployer-service-account`, but don't deploy to the Prow service cluster or build cluster: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml

**What you expected to happen**:
Instead of aggregating under all privileges we need under a single service account (and token!) and using that in many places, we should use a separate service account with appropriately scoped privileges.

cc @Katharine @fejta @clarketm @michelle192837

**Comment by Katharine** [comment]
This may well be easier to change in the other direction at this point - that service account now also has access to every k8s staging bucket, and is [automatically added to new ones](https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/lib.sh#L45).
