### ISSUE TITLE
Create go.k8s.io/oncall-hotlist

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#14393]
Should link to  https://github.com/kubernetes/test-infra/search?q=label%3Akind%2Foncall-hotlist+is%3Aopen&type=Issues

Looks like this requires changing: https://github.com/kubernetes/k8s.io/blob/575312dd25163f71730ab7a7955e3bb5eca1dca5/k8s.io/configmap-nginx.yaml#L236

**Comment by michelle192837** [comment]
This is done! http://go.k8s.io/oncall-hotlist. Closing for now, may want to adjust the link later though.
