### ISSUE TITLE
k/k config is confused about labels, prow is confusing about labels

### ISSUE THREAD

**Issue by danwinship** [kubernetes/test-infra#14420]
In https://github.com/kubernetes/kubernetes/issues/82799, someone said

    /sig cloud-provider provider-azure

to which the bot responded:

> The label(s) sig/provider-azure cannot be applied. These labels are supported: api-review, community/discussion, community/maintenance, community/question, cuj/build-train-deploy, cuj/multi-user, platform/aws, platform/azure, platform/gcp, platform/minikube, platform/other

which is kind of weird... where did that particular list of labels come from? (Answer: it seems like those are the labels that can *only* be applied via `/label` and not any other command? But that makes it a weird message in response to a `/sig` command.)

Eventually I figured out that the right syntax was

    /label platform/azure

Only to get an error again:

> The label(s) platform/azure cannot be applied. These labels are supported: api-review, community/discussion, community/maintenance, community/question, cuj/build-train-deploy, cuj/multi-user, platform/aws, platform/azure, platform/gcp, platform/minikube, platform/other

From skimming the source, it looks like this is because there isn't actually a `platform/azure` label in k/k currently.

So
1. The bot should not be claiming that there is a `platform/azure` label when there is not. (ie, it is configured wrong)
2. The bot should not be claiming that `platform/azure` is a supported label but `platform/azure` is not. (ie, it is behaving nonsensically in the face of its bad configuration)
3. The bot should not be giving a confusing `/label`-specific reply to a `/sig` command?

**Comment by stevekuznetsov** [comment]
@Katharine @cjwagner @fejta

**Comment by stevekuznetsov** [comment]
Related to #14161 ?

**Comment by stevekuznetsov** [comment]
Looks like we emit the error on every label attempt https://github.com/kubernetes/test-infra/issues/14421#issuecomment-533605124
