### ISSUE TITLE
A tool to bootstrap a GCP prow build cluster. 

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#14430]
**What would you like to be added**:
A robust tool to create and bootstrap a GCP prow `build` cluster. 
Options:
1. Golang CLI tool
2. Terraform definitions
3. Both

**Why is this needed**:
As a form of self-service to provide the neccessary tooling to assist developers with setting up a `build` cluster for their Prow jobs.

/assign

**Comment by matthyx** [comment]
Hi @clarketm do you still have some work to be done in this task? Do you need help?

**Comment by clarketm** [comment]
Hi @matthyx,

Sorry for the latent response. The effort to create a tool to bootstrap a GCP prow build cluster is partially complete (i.e. started) with this simple bash script: #14377 and the introduction of terraform: #14550.

Albeit, @cblecker mentioned a while back (https://github.com/kubernetes/test-infra/pull/14550#issuecomment-537264553) that the K8s community is driving an effort to standardize terraform, so this issue is obsolete.
