### ISSUE TITLE
sinker: leader election lost

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#14455]
```
{"component":"sinker","file":"prow/cmd/sinker/main.go:396","func":"main.(*controller).clean","level":"info","msg":"Deleted old completed pod.","pod":"e5f2c3cf-de9c-11e9-938b-0a58ac10983c","time":"2019-09-24T13:31:13Z"}
{"component":"sinker","file":"prow/cmd/sinker/main.go:421","func":"main.(*controller).clean","level":"info","msg":"Sinker reconciliation complete.","time":"2019-09-24T13:31:13Z"}
{"component":"sinker","file":"prow/cmd/sinker/main.go:195","func":"main.(*controller).Start","level":"info","msg":"Sync time: 5.231366902s","time":"2019-09-24T13:31:13Z"}
{"component":"sinker","error":"leader election lost","file":"prow/cmd/sinker/main.go:162","func":"main.main","level":"fatal","msg":"failed to start manager","time":"2019-09-24T13:33:34Z"}
```

/area prow/sinker
/assign @alvaroaleman 
/cc @cjwagner @fejta @petr-muller

**Comment by alvaroaleman** [comment]
@stevekuznetsov Yeah? That is the normal log you see when the thing gets stopped. What exactly is the unexpected behavior here?

**Comment by stevekuznetsov** [comment]
Oh, I thought that was a cause for the Pod failing. I just saw a failed Pod and a restart and this was the last line of logs. I would have expected to see the interrupts lib say we got SIGINT from the kubelet?

**Comment by alvaroaleman** [comment]
I can not tell you what stopped your sinker pod, but [the function that emits this error](https://github.com/kubernetes-sigs/controller-runtime/blob/c29fe2074af31528fec5afe54bd7e54464fd959c/pkg/manager/internal.go#L368) is called in a [defer statement by the leader election](https://github.com/kubernetes/kubernetes/blob/512eccac1f1d72d6d1cb304bc565c50d1f2e295e/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L199), hence you will see that error whenever a pod gets stopped.

I'll close this for now, just re-open it if you think there is something left to do here.
