### ISSUE TITLE
Federation e2e failure: wrong ci build version

### ISSUE THREAD

**Issue by colhom** [kubernetes/test-infra#145]
from kubernetes-e2e-gce-federation job logs

```sh
++ gsutil cat gs://kubernetes-release/ci/latest.txt
+ build_version=v1.3.0-beta.0
+ echo 'Using published version ci/v1.3.0-beta.0 (from ci/latest)'
+ fetch_tars_from_gcs ci v1.3.0-beta.0
+ local -r bucket=ci
+ local -r build_version=v1.3.0-beta.0
```

This is not the `build_version` that kubernetes-federation-build is pushing, which naturally causes the downstream kubernetes-e2e-gce-federation job to pull the wrong tarballs and fail.

I don't yet understand why this issue took so long to pop up, as the federation stuff has been merged for weeks and this started happening a few days ago.

**Comment by colhom** [comment]
I have a fix up in #146. I suspect some other build job is clobbering `gs://kubernetes-release/ci/latest.txt`

**Comment by nikhiljindal** [comment]
Re: why it did not happen before: We cut 1.3.0-beta.0 on friday.

**Comment by colhom** [comment]
@nikhiljindal I would think it's something related to the v1.3 beta cut as well. Anything that could result in job execution ordering as follows...:

```
kubernetes-federation-build
kubernetes-build (or any non-federation ci build)
kubernetes-e2e-gce-federation
```

Would result in `kubernetes-build` clobbering `kubernetes-federation-build's` ci tag in the storage bucket. 

For instance, adding more jenkins executors could cause this to happen. (Increased parallelism exposes a previously unseen race condition. Gasp)
