### ISSUE TITLE
integrate lgtm-tagging/SQ with GitHub reviews

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#1451]
Currently, if you use GitHub's review interface to approve a PR, it has no effect on whether that PR will be merged. If you approve a PR and comment in the review interface with `/lgtm`, it still has no effect, because review comments are treated differently from PR discussion comments.

It looks like GitHub now sends events for review comments (see for example [here](https://github-dot-k8s-gubernator.appspot.com/timeline?repo=kubernetes/kubernetes&number=37868) and [here](https://github-dot-k8s-gubernator.appspot.com/timeline?repo=kubernetes/test-infra&number=1434)). There's also a [preview API](https://developer.github.com/v3/pulls/reviews/) to get reviews.

Does it seem reasonable to add the lgtm tag when we receive a `state: "APPROVED"` review event, and remove it if we receive a `state: "CHANGES_REQUESTED"` review? I'm not sure what we want to do if someone first requests changes, and then someone else approves - should we require all reviewers to approve?

Some example reviews:
https://api.github.com/repos/kubernetes/kubernetes/pulls/37868/reviews
Changes requested:
```json
[
  {
    "id": 14596061,
    "user": {
      "login": "ixdy",
      "id": 8061296,
      "avatar_url": "https://avatars0.githubusercontent.com/u/8061296?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ixdy",
      "html_url": "https://github.com/ixdy",
      "followers_url": "https://api.github.com/users/ixdy/followers",
      "following_url": "https://api.github.com/users/ixdy/following{/other_user}",
      "gists_url": "https://api.github.com/users/ixdy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ixdy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ixdy/subscriptions",
      "organizations_url": "https://api.github.com/users/ixdy/orgs",
      "repos_url": "https://api.github.com/users/ixdy/repos",
      "events_url": "https://api.github.com/users/ixdy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ixdy/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "test, please ignore",
    "commit_id": "3113972d17dc0ee5669aea69a9689063f9861e56",
    "state": "CHANGES_REQUESTED",
    "html_url": "https://github.com/kubernetes/kubernetes/pull/37868#pullrequestreview-14596061",
    "pull_request_url": "https://api.github.com/repos/kubernetes/kubernetes/pulls/37868",
    "_links": {
      "html": {
        "href": "https://github.com/kubernetes/kubernetes/pull/37868#pullrequestreview-14596061"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/kubernetes/kubernetes/pulls/37868"
      }
    },
    "submitted_at": "2016-12-28T18:56:42Z"
  }
]
```

https://api.github.com/repos/kubernetes/test-infra/pulls/1434/reviews
Commented:
```json
  {
    "id": 14522709,
    "user": {
      "login": "ixdy",
      "id": 8061296,
      "avatar_url": "https://avatars0.githubusercontent.com/u/8061296?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ixdy",
      "html_url": "https://github.com/ixdy",
      "followers_url": "https://api.github.com/users/ixdy/followers",
      "following_url": "https://api.github.com/users/ixdy/following{/other_user}",
      "gists_url": "https://api.github.com/users/ixdy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ixdy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ixdy/subscriptions",
      "organizations_url": "https://api.github.com/users/ixdy/orgs",
      "repos_url": "https://api.github.com/users/ixdy/repos",
      "events_url": "https://api.github.com/users/ixdy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ixdy/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "has this been pushed yet?\r\n\r\nit looks like there is a conflict, too.",
    "commit_id": "f60fd35747b961a8c77843029e3ea2691041b491",
    "state": "COMMENTED",
    "html_url": "https://github.com/kubernetes/test-infra/pull/1434#pullrequestreview-14522709",
    "pull_request_url": "https://api.github.com/repos/kubernetes/test-infra/pulls/1434",
    "_links": {
      "html": {
        "href": "https://github.com/kubernetes/test-infra/pull/1434#pullrequestreview-14522709"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/kubernetes/test-infra/pulls/1434"
      }
    },
    "submitted_at": "2016-12-28T03:52:59Z"
  },
```

Approved:
```json
  {
    "id": 14595289,
    "user": {
      "login": "ixdy",
      "id": 8061296,
      "avatar_url": "https://avatars0.githubusercontent.com/u/8061296?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ixdy",
      "html_url": "https://github.com/ixdy",
      "followers_url": "https://api.github.com/users/ixdy/followers",
      "following_url": "https://api.github.com/users/ixdy/following{/other_user}",
      "gists_url": "https://api.github.com/users/ixdy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ixdy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ixdy/subscriptions",
      "organizations_url": "https://api.github.com/users/ixdy/orgs",
      "repos_url": "https://api.github.com/users/ixdy/repos",
      "events_url": "https://api.github.com/users/ixdy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ixdy/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "",
    "commit_id": "cb914b5fe78564fd4f21b4c35f2a47ad049bac7e",
    "state": "APPROVED",
    "html_url": "https://github.com/kubernetes/test-infra/pull/1434#pullrequestreview-14595289",
    "pull_request_url": "https://api.github.com/repos/kubernetes/test-infra/pulls/1434",
    "_links": {
      "html": {
        "href": "https://github.com/kubernetes/test-infra/pull/1434#pullrequestreview-14595289"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/kubernetes/test-infra/pulls/1434"
      }
    },
    "submitted_at": "2016-12-28T18:48:46Z"
  },
```

cc @kubernetes/sig-contributor-experience-misc

**Comment by ixdy** [comment]
I'm trying to understand what ["dismissing" a PR review](https://developer.github.com/v3/pulls/reviews/#dismiss-a-pull-request-review) is, and whether it's also something we'd need to handle. I'm not sure that it's exposed in the web UI.

**Comment by rmmh** [comment]
It wouldn't be hard to make "approval" set the LGTM label, which would make it flow easier for all the other tools that consume PRs through labels.

**Comment by spxtr** [comment]
It makes sense, but it's a little confusing because we're trying to make `/approve` mean something special too.

**Comment by ixdy** [comment]
a "meet halfway" solution might be to handle `/lgtm` or other actions in the review comment. kinda verbose, though.

**Comment by ixdy** [comment]
Hm, the Reviews API seems to be questionably stable.
```console
$ curl -sSH "Accept: application/vnd.github.black-cat-preview+json" https://api.github.com/repos/kubernetes/test-infra/pulls/1411/reviews | jq '.[].body'
""
""
""
""
""
""
""
""
""
""
""
""
""
""
$ curl -sSH "Accept: application/vnd.github.black-cat-preview+json" https://api.github.com/repos/kubernetes/test-infra/pulls/1434/reviews | jq '.[].body'
"has this been pushed yet?\r\n\r\nit looks like there is a conflict, too."
""
""
"/lgtm\r\n\r\n(ignore this additional comment, just trying to gather event info)"
```

The [events](https://github-dot-k8s-gubernator.appspot.com/timeline?repo=kubernetes/test-infra&number=1411) for kubernetes/test-infra#1411 look fine, though.

**Comment by thockin** [comment]
What happens if there are multiple assignees ?  Is it approved when one of
them approves?

**Comment by ixdy** [comment]
@thockin I think that's what currently happens with `/lgtm`. Not sure what the plan is for `/approved`.

**Comment by grodrigues3** [comment]
`/approved` is supposed to be on a file by file basis.  So if a PR is modifies files `a.go, b.go, and c.go` and bob is only an approver for `a.go, b.go` who writes `/approved`, then the PR will not be considered fully approved (the label will NOT be added) until an approver for `c.go` also writes `/approved`

**Comment by thockin** [comment]
Is there a kube-bot dictionary being written?

**Comment by grodrigues3** [comment]
not yet, but that makes a ton of sense.  especially with all the mungers and bot interactions that take place.  i'll add it to the K8s contribX [github project](https://github.com/kubernetes/contrib/projects/1) task list

**Comment by spxtr** [comment]
We might just want to rename `/approve` since it's going to be confusing next to GitHub's approval.

**Comment by spxtr** [comment]
> Is there a kube-bot dictionary being written?

k8s-ci-robot comments will link to https://github.com/kubernetes/test-infra/blob/master/prow/commands.md now.

**Comment by ixdy** [comment]
I'm still sad that GitHub's review approve doesn't do anything.

**Comment by fejta** [comment]
@rmmh tells me that github now sends webhooks for review comments. We can make gubernator, prow and/or mungegithub understand them, right?

**Comment by fejta** [comment]
/assign @cjwagner 
Is this something you're planning to work on?

**Comment by spiffxp** [comment]
/close
I think we've had this working for a while, though no actions based on comment vs. approval vs. request-changes.  eg: /lgtm works in reviews as of https://github.com/kubernetes/test-infra/pull/2970
