### ISSUE TITLE
CI signal: promote x.y-all stable jobs to informing dashboards

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/test-infra#14532]
There are a handful of jobs in the sig-release/x.y-all dashboards that are stable, present in other branches, and provide useful info. For example, in sig-release/1.16-all:
* https://testgrid.k8s.io/sig-release-1.16-all#node-kubelet-features-beta
* https://testgrid.k8s.io/sig-release-1.16-all#bazel-build-1.16
* https://testgrid.k8s.io/sig-release-1.16-all#bazel-test-1.16
* https://testgrid.k8s.io/sig-release-1.16-all#ci-kubernetes-bazel-build-1-16
* https://testgrid.k8s.io/sig-release-1.16-all#post-kubernetes-bazel-test-1-16

/cc @kubernetes/sig-release
/cc @kubernetes/release-team
/cc @justaugustus @alenkacz @jberkus
/assign
/kind cleanup
/priority important-soon
/milestone v1.17

**Comment by alenkacz** [comment]
@alejandrox1 are there currently any rules for promoting jobs to informing? Overall we want as much in informing as long as they prove stable in all in the longterm?

**Comment by jberkus** [comment]
+1

Part of the motivation for this issue is the we'd like to get rid of the -All dashboards, since nobody looks at them.
