### ISSUE TITLE
CI signal: move flaky jobs into informing dashboards and increase alert threshold

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/test-infra#14531]
`gce-cos-<branch>-default` has been creating many false alarms and the following two jobs often do so as well:

* gce-cos-<branch>-serial
* gce-cos-<branch>-slow

These usually fail between 30% to 50% of the time and often fire false alerts.
The proposed action items for this issue are:
1. increase `testgrid-num-failures-to-alert` to 6 in order to prevent false alerts (for this jobs it usually means that an alert will be sent after some 6+ hours)
2. move these jobs to informing dashboards. changes will have to be done in order for config-forker to also pick up these changes. 
3. Update the sig-release blocking criteria - empirically, a job that can stay below a 30% rate of flakyness is useful and doesn't cause a lot of false alerts. We should add this threshold and iterate (we have already started keeping track of this data).

**Additional information**:
* https://testgrid.k8s.io/sig-release-master-blocking
* https://testgrid.k8s.io/sig-release-1.16-blocking

/cc @kubernetes/sig-release 
/cc @kubernetes/release-team 
/cc @justaugustus @alenkacz @jberkus 
/assign
/kind cleanup
/priority important-soon
/milestone v1.17

**Comment by hasheddan** [comment]
Happy to take this one! @alejandrox1 for (2), do you mean that `fork-per-release: "true"` needs to be added to these jobs?

**Comment by alejandrox1** [comment]
Those jobs should already be configured to be generated by the config-forker, they are already in the previous release dashboards.
In order to move them, the testgrid tab will need to be changed and something from here, https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml , may also need to be changed.
We need to find all the places where the job name is mentioned and change accordingly is needed.

**Comment by jberkus** [comment]
+1 agreed.  We monitored jobs through the 1.16 cycle, and those jobs were consistently flaky.  Per the release blocking criteria (WIP), they should be demoted to Informing.

**Comment by justaugustus** [comment]
+1 for demotion!

**Comment by cpanato** [comment]
+1 thanks for doing that

**Comment by alejandrox1** [comment]
/lifecycle active
#14572
