### ISSUE TITLE
Allow kops jobs on CLI to use a custom Kubernetes build somehow

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1454]
This is a minor inconvenience.. you can easily run the job with `E2E_UP=false; E2E_DOWN=false` on an existing cluster (which you can bring up using a custom k8s build), but that doesn't help for e.g. e2e test development (because we'll still download kube binaries for the tests in `dockerized-e2e-runner.sh`. I think there's a solution here involving `JENKINS_USE_EXISTING_BINARIES`, but it may need a little more streamlining.

**Comment by fejta** [comment]
We can now use `kubetest --extract` to solve this
