### ISSUE TITLE
GINKGO_TOLERATE_FLAKES on postsubmit jobs?

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1456]
Is there a reason we don't enable this, especially for SQ blocking jobs? SQ blocking should be similar to PR builder (where this is enabled) for the need to re-test flakes.

**Comment by zmerlynn** [comment]
cc @kubernetes/test-infra-maintainers @lavalamp

**Comment by lavalamp** [comment]
Yes, we don't enable it in post-submit jobs because there's a separate flake mechanism already running there (comparing between runs). I don't think we should turn it on there, but maybe if we have an emergency flake problem we could think about it.

**Comment by zmerlynn** [comment]
Comparing between runs on the same job, or across jobs? I'm having a nasty issue where the AWS tests seem more flaky than the GCE tests, and I'm sure 90% of it is timing differences (I've corrected a couple of tests now that didn't bother waiting for pods to become ready, for instance, to counteract discrepancies in pull times), but as long as its monitoring a given test within the same job, I could still add it to the SQ.

**Comment by lavalamp** [comment]
It compares to previous runs within the test job.
