### ISSUE TITLE
Add Knative build controller to OSS-Test-infra prow instance

### ISSUE THREAD

**Issue by iamsubratp** [kubernetes/test-infra#14606]
**What would you like to be added**:
Add knative build controller to oss-test-infra prow instance.
**Why is this needed**:
We want to use knative build step functionality

**Comment by BenTheElder** [comment]
do you mean https://github.com/GoogleCloudPlatform/oss-test-infra? if so this issue should be filed there.

**Comment by iamsubratp** [comment]
yeah... sure will file it there and close this issue
