### ISSUE TITLE
Allow association of periodic jobs with a repository

### ISSUE THREAD

**Issue by Noremac201** [kubernetes/test-infra#14629]
**What would you like to be added**:
I believe this should be added so in the UI you can sort by repo and see all the periodic jobs that are associated with said repo. Otherwise you have to specifically search for the job name.

This could be done by having a label that Prow looks at specifically. e.g.
```
label:
    repo: 'my-repo'
```

**Why is this needed**:
Better per-repo health checks at a glance.
Better organization if Prow is split amongst teams.

**Comment by stevekuznetsov** [comment]
Right now we loosely support this by setting `extra_refs` but not in Deck. 
/cc @cjwagner @fejta @Katharine

**Comment by stevekuznetsov** [comment]
IMHO the `extra_refs` stuff is a hack and we should create a ref-driven periodic type that explicitly opts into being part of a repo

**Comment by alvaroaleman** [comment]
> IMHO the extra_refs stuff is a hack and we should create a ref-driven periodic type that explicitly opts into being part of a repo

WDYT about if a job has no `refs` but does have `extraRefs`, to change the logic in put `extraRefs[0]` in `refs` and strip it from `extra_refs`?

**Comment by fejta** [comment]
I would be interested in allowing people to group together related periodics. It would be useful to hand sig-foo a URL that says "here are all your sig-foo jobs".

This will most likely span repos, so I'm not sure that requiring periodics to pin to a repo is the right solution here.

**Comment by Noremac201** [comment]
That could also be extended to grouping presubmits and postsubmits as well
instead of just periodics; giving you a finer grained picture of a subset
of your tests at one time.

**Comment by stevekuznetsov** [comment]
Depending on _what_ you are trying to convey with those links, we are making good progress. Today, labels and annotations on a ProwJob are exposed via Prometheus so it's possible with `join()` to create a query that shows you metrics on a specific subset of jobs. If we expand `deck` to allow for overview pages on jobs with labels, that could bridge the rest of the gap, maybe? 

This is orthogonal from the "periodics-that-are-necessarily-related-to-repos-but-not-since-we're-hacking-extra-refs" issue, though ...

**Comment by alvaroaleman** [comment]
> This is orthogonal from the "periodics-that-are-necessarily-related-to-repos-but-not-since-we're-hacking-extra-refs" issue, though ...

Yeah, I think so, too. Doing something to make Deck show jobs that have no refs and len(extra_refs) > 0 when selecting the repo in extra_refs[0] would be pretty nice

**Comment by chaodaiG** [comment]
Actually it seems that we already have this, for example https://prow.k8s.io/?repo=kubernetes%2Ftest-infra&type=periodic shows periodic jobs associated with k8s/test-infra repo:
![Screen Shot 2021-11-09 at 8 39 39 AM](https://user-images.githubusercontent.com/45011425/140966362-e53fd6d2-de33-4248-83a4-1916e08f7d9c.png)

**Comment by alvaroaleman** [comment]
Yeah I added this in https://github.com/kubernetes/test-infra/pull/20507

**Comment by spiffxp** [comment]
/reopen
From the screenshot the repo isn't listed in the UI.  Seems like deck should be updated to parse the same field that's being used on the backend?

**Comment by chaodaiG** [comment]
my bad, I had scrolled down a little bit when I took screenshot to make it shorter. Retaken:

![Screen Shot 2021-11-09 at 1 55 04 PM](https://user-images.githubusercontent.com/45011425/141011173-367f7b5b-7419-471c-97f9-bfc912043665.png)

**Comment by alvaroaleman** [comment]
I think what @spiffxp means is that the "Repository" field in the job list does not have a value even though the filtering works. Not sure if that is strictly part of this issue or not but I suppose we could use the same logic we use for the filtering there?

**Comment by chaodaiG** [comment]
ah. I see.
