### ISSUE TITLE
Lots of kubernetes E2E tests are not executed by any specific test suite

### ISSUE THREAD

**Issue by tallclair** [kubernetes/test-infra#14647]
It's recently come to my attention that a lot of Kubernetes E2E tests aren't being run by _any_ jobs. These are typically `[Feature:_]` tests that aren't opted in to any jobs. I don't know the full history on all these tests, but I suspect many were added without realizing that the tests weren't being run in CI.

Examples include the `NodeAuthorization` and `NodeAuthenticator` features (https://github.com/kubernetes/kubernetes/pull/82551), and the `Seccomp` feature.

I'm not sure what the solution should be, but a good start would be to:
1. Somehow flag all tests that are not currently run by any jobs. It is currently difficult to even tell whether a test is being run, and if what jobs are running it.
2. Prevent tests from being added if they won't be run. I.e. a presubmit check that pulls the job configs, and checks whether any jobs would run the new tests.

**Comment by neolit123** [comment]
should such security features be tested in the sig-auth dashboard?
https://k8s-testgrid.appspot.com/sig-auth#Summary

it seems this dashboard includes tests defined here:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml

**Comment by stevekuznetsov** [comment]
/retitle Lots of kubernetes E2E tests are not executed by any specific test suite

**Comment by tallclair** [comment]
@neolit123 - That may be a path forward to unblock https://github.com/kubernetes/kubernetes/pull/82551, but it doesn't address the root issue that there are E2E tests that are completely ignored.

**Comment by tallclair** [comment]
/remove-lifecycle stale

This problem still exists without a general solution.

**Comment by neolit123** [comment]
/remove-lifecycle rotten

> Prevent tests from being added if they won't be run. I.e. a presubmit check that pulls the job configs, and checks whether any jobs would run the new tests.

usually tests are first added to k/k (suite) and then possibly enabled if focus fields on the job side in k/test-infra.
if the maintainers / contributors somehow miss the k/test-infra step, or if at some point the test-infra focus is removed the test will become unused.

> Somehow flag all tests that are not currently run by any jobs. It is currently difficult to even tell whether a test is being run, and if what jobs are running it.

i can imagine a html page that shows statistics of how many runs for a time window (W) certain tests have.
this might help us reduce overlap.
(not sure if supported already)

```
56 - test foo
34 - test bar
...all run tests for that period
...
```

the same page can support download machine readable file A.
then ginkgo can be used to dry-run / output all available tests into a machine readable file B.

comparing A to B would give results for which tests are not run for W.

**Comment by aojea** [comment]
maybe adding an optional job that runs all the Feature tests can give us some idea of the status
