### ISSUE TITLE
bazel failures without results

### ISSUE THREAD

**Issue by philips** [kubernetes/test-infra#1465]
Example https://github.com/kubernetes/kubernetes/pull/38167#issuecomment-268915896

![screen shot 2016-12-29 at 5 16 17 pm](https://cloud.githubusercontent.com/assets/33544/21558188/c066228e-cdea-11e6-8026-a04d655693b9.png)

cc @mikedanese

**Comment by fejta** [comment]
Related to https://github.com/kubernetes/test-infra/pull/1464 or https://github.com/kubernetes/test-infra/pull/1464 https://github.com/kubernetes/test-infra/pull/1462?

**Comment by philips** [comment]
@fejta I dunno, re-running the test now.

**Comment by spxtr** [comment]
No, it was https://github.com/kubernetes/test-infra/pull/1433
