### ISSUE TITLE
Handling one-off jobs

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#14655]
**What would you like to be added**:

A better way to manual or one-off jobs, or, if this already exists, some guidance on how to run these

**Why is this needed**:

We have some manual jobs we run, specifically for releasing a new version. So we would want to run a job the "build the release from SHA xyz" and then a few days later "publish the release xyz".

It seems there are two ways to do this:

* Manually create a Prowjob. This is error prone and requires highly privileged access to the cluster.
* Have a `run_if_changed` job 

The `run_if_changed` is problematic because it is easy to accidentally trigger this. For example, I add a comment to the file and suddenly I published a new release. Or, for a real world example, [reverting a commit leads to re-publishing a docker image with security patches](https://istio.io/news/2019/incorrect-sidecar-image-1.2.4/).

**Comment by stevekuznetsov** [comment]
Right now we're doing periodics scheduled `@yearly` and creating ProwJobs from those ...

**Comment by clarketm** [comment]
The only mechanisms that *I am aware of* for *event-based* Prowjob triggers (excluding the standard mechanisms of time, or Github event) are with using `run_if_changed` or manually creating and triggering the Prowjob. We could potentially create a Prow plugin where if the user issues a slash command (e.g. `/run release-istio-1.3.3`) then we run a Prowjob.
