### ISSUE TITLE
Expose prowjob metrics in a promhttp like fashion

### ISSUE THREAD

**Issue by rmohr** [kubernetes/test-infra#14672]
**What would you like to be added**:

Collect prowjob metrics like it is done with promhttp for REST applications to allow visualizing things like `job x failed y times and ran on avg 30 minutes until it failed`.

I suppose https://github.com/kubernetes/test-infra/tree/master/prow/cmd/exporter would be a good fit for these metrics.

**Why is this needed**:

This can help to identify issues:

 * how long are jobs pending? (e.g. new projects were on-boarded and they let other projects unintentionally starve)
 * identifying unusual long runs on jobs (can be hints for various issues in the cluster)
 * does a job very often fail at the same time? (can be a hint for various issues in the cluster)

and so on.

**Comment by alvaroaleman** [comment]
CC @xrstf
