### ISSUE TITLE
Start pulling stdout from junit in gubernator

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/test-infra#1468]
https://github.com/onsi/ginkgo/pull/318 was merged in order to allow having to look at logs to be irrelevant for most ginkgo e2e tests.  We should take advantage of it (I'll do a PR to kube to update ginkgo).

**Comment by spxtr** [comment]
IIUC we shouldn't need to do any changes to gubernator, but @rmmh will know for sure.

**Comment by rmmh** [comment]
Do you have an example failure?

**Comment by smarterclayton** [comment]
PR #1981

**Comment by fejta** [comment]
/assign @smarterclayton 
Looks like this PR is still alive (woo!)

**Comment by spiffxp** [comment]
/close
🌟  for @smarterclayton
