### ISSUE TITLE
 Acquiring project from boskos failing for scalability oss jobs

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/test-infra#14697]
Since yesterday all scalability jobs using boskos started to failing with this error:
```
main.go:319: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: resources not found
```

This has happened over 10 times since yesterday and it's causing release-blocking jobs to be failing consistently, e.g. https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-master-scalability-100

I would appreciate if someone having access to boskos logs could check why we request for project-type=scalability-project are failing with `resource not found`.

/priority critical-urgent

**Comment by fejta** [comment]
/kind oncall-hotlist

/assign @sebastienvas @krzyzacy 

Are is this expected?

```console
bash-3.2$ kubectl --context=prow-builds logs -l app=boskos -n test-pods
{"error":"Resource gpu-project not exist","level":"error","msg":"No available resource","time":"2019-10-10T16:34:42Z"}
{"error":"Resource gce-project not exist","level":"error","msg":"No available resource","time":"2019-10-10T16:34:43Z"}
{"level":"info","msg":"Updated resource k8s-jkns-e2e-gke-ci-canary","time":"2019-10-10T16:34:43Z"}
{"handler":"handleUpdate","level":"info","msg":"From 10.60.188.228:40078","time":"2019-10-10T16:34:43Z"}
{"handler":"handleStart","level":"info","msg":"From 10.61.17.230:54462","time":"2019-10-10T16:34:44Z"}
{"level":"info","msg":"Request for a free gce-project from ci-kubernetes-e2e-gci-gce-slow, dest busy","time":"2019-10-10T16:34:44Z"}
{"level":"info","msg":"Updated resource gce-up-c1-3-g1-4-up-mas","time":"2019-10-10T16:34:44Z"}
{"handler":"handleStart","level":"info","msg":"From 10.60.53.80:52630","time":"2019-10-10T16:34:44Z"}
{"level":"info","msg":"Request for a free gce-project from ci-kubernetes-e2e-autoscaling-vpa-actuation, dest busy","time":"2019-10-10T16:34:44Z"}
{"error":"Resource gce-project not exist","level":"error","msg":"No available resource","time":"2019-10-10T16:34:44Z"}
bash-3.2$ kubectl --context=prow-builds logs -l app=boskos-janitor -n test-pods
{"error":"no resource name kube-gke-upg-1-2-1-3-upg-clu-n","level":"warning","msg":"Update kube-gke-upg-1-2-1-3-upg-clu-n failed","time":"2019-10-10T16:34:59Z"}
{"error":"no resource name gke-up-c1-4-clat-up-mas","level":"warning","msg":"Update gke-up-c1-4-clat-up-mas failed","time":"2019-10-10T16:34:59Z"}
{"error":"no resource name gke-up-g1-2-c1-3-up-clu","level":"warning","msg":"Update gke-up-g1-2-c1-3-up-clu failed","time":"2019-10-10T16:34:59Z"}
{"error":"no resource name k8s-gci-gke-slow-1-5","level":"warning","msg":"Update k8s-gci-gke-slow-1-5 failed","time":"2019-10-10T16:34:59Z"}
```

**Comment by fejta** [comment]
http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1&from=1570120846878&to=1570725646878

**Comment by fejta** [comment]
What do these errors mean?

```yaml
{
 insertId: "ld746eg13kr670"  
 jsonPayload: {
  error: "no resource name k8s-jkns-gci-gke-serial-1-4"   
  level: "warning"   
  msg: "Update k8s-jkns-gci-gke-serial-1-4 failed"   
 }
 labels: {…}  
 logName: "projects/k8s-prow-builds/logs/boskos-janitor"  
 receiveTimestamp: "2019-10-10T18:26:27.814170080Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-10T18:26:24Z"  
}
```

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/pull/14598#event-2688265794 merged at Oct 4, 11:14a PST

**Comment by fejta** [comment]
So looks like we were missing a graph http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1&from=now-7d&to=now&panelId=8&fullscreen

**Comment by BenTheElder** [comment]
http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1&from=now-2d&to=now non-GKE projects look happier now but GKE dirty still looks to be climbing, do we need to do https://github.com/kubernetes/test-infra/pull/14708 for GKE as well?

**Comment by BenTheElder** [comment]
per @krzyzacy it seems cleaning up the new resource types (routers) is a lot slower, bumping the janitor replicas seems to have worked ref https://github.com/kubernetes/test-infra/pull/14708 by @fejta, sent a bump for the other GCP project (GKE project) janitor in https://github.com/kubernetes/test-infra/pull/14714

**Comment by BenTheElder** [comment]
from GKE dirty projects have dramatically dropped 145 to 3. I think we're good for now but probably will want https://github.com/kubernetes/test-infra/issues/14715

**Comment by fejta** [comment]
More work to do but as Ben says the outage is resolved.

**Comment by mm4tt** [comment]
Hey Folks, sad news, this is happening again

![TBW40hsV9eH](https://user-images.githubusercontent.com/2604887/66737933-89aa5c00-ee6d-11e9-9c36-3bb5ad371dd1.png)
```
W1014 07:16:27.337] 2019/10/14 07:16:27 main.go:319: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: resources not found
```

**Comment by alenkacz** [comment]
also happening here https://testgrid.k8s.io/sig-release-master-blocking#gci-gce-ingress - two jobs in release-master-blocking are affected by this so still pretty urgent.

**Comment by fejta** [comment]
Investigating...

**Comment by fejta** [comment]
Do I deleted some pods, which appears to have things healthy again:
http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1&from=now-2d&to=now

/assign @fejta @Katharine 

There might be fixes if we redeploy at head? It looks like we don't auto-upgrade boskos, which Katharine is working on. I'll look into manually bumping today.

Leaving open for now.

**Comment by mm4tt** [comment]
/reopen

It happens again for the presubmit scalability project pool - http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1&from=now-2d&to=now
![86Bbx5Cwn6f](https://user-images.githubusercontent.com/2604887/67949790-aaeaa680-fbe8-11e9-99ea-ede118398699.png)

```
W1031 13:04:02.620] 2019/10/31 13:04:02 main.go:737: provider gce, will acquire project type scalability-presubmit-project from boskos
W1031 13:09:08.874] 2019/10/31 13:09:08 process.go:96: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W1031 13:09:08.875] 2019/10/31 13:09:08 process.go:153: Running: bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"
W1031 13:09:09.253] 2019/10/31 13:09:09 process.go:155: Step 'bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"' finished in 378.46041ms
W1031 13:09:09.254] 2019/10/31 13:09:09 main.go:319: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: resources not found
```

This is affecting all k/k presubmits

**Comment by mm4tt** [comment]
Looks like it's getting better but still would be good for someone from test-infra to talk a look.

**Comment by BenTheElder** [comment]
is this still occurring? do we actually have enough capacity?

**Comment by mm4tt** [comment]
Good point, I think I might have misinterpreted the graphs. Looks like there are not many projects in the dirty state (which IIUC would mean that this issue is still occurring) but rather we have a lot in busy state and they often hit the total project capacity. Please confirm whether it makes sense and whether it would make sense to throw in more projects to the scalability presubmit pool

**Comment by BenTheElder** [comment]
I think that is the case then -- generally if the dirty state is piling up
there is some issue with the janitor, but many busy projects usually just
means high usage.

**Comment by fejta** [comment]
Also may need more janitor replicas: https://github.com/kubernetes/test-infra/blob/master/prow/cluster/boskos-janitor.yaml

**Comment by mm4tt** [comment]
Looks like the janitor's replicas has been bumped up in https://github.com/kubernetes/test-infra/pull/15188.
We can close this one once we add more projects to our presubmit pool.

**Comment by mm4tt** [comment]
Lost track of this one, we added more projects to the presubmit pool long time ago. Both our pools seem healthy as of now.
![rNJH5V1siew](https://user-images.githubusercontent.com/2604887/74715031-ff637180-522b-11ea-8b4e-844853a7d4b0.png)


/close

**Comment by BenTheElder** [comment]
https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1

![image](https://user-images.githubusercontent.com/917931/74772128-43fb0700-5244-11ea-90c0-037bc305d8ef.png)

this does not look healtthy to me

**Comment by fejta** [comment]
Some potential commits


commit d27cc139960d61f0f8f0549387f828baba5f4d40
Merge: 2c6e37d9d 7c0ac7837
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Tue Feb 18 03:03:29 2020 -0800

    Merge pull request #16335 from mm4tt/gce-100-containerd
    
    Add experimental gce-100-perf job with containerd enabled

commit 7c0ac78372e53c08664849d009a747cb6204f948
Author: Matt Matejczyk <mmat@google.com>
Date:   Tue Feb 18 11:20:14 2020 +0100

    Add experimental gce-100-perf job with containerd

commit 08bbe16ba159ed24d7afcaa1c1ffd6254dba990f
Author: Jakub Przychodzeń <jprzychodzen@google.com>
Date:   Tue Feb 18 11:12:46 2020 +0100

    [Access-tokens] Ramp up access-tokens test

commit 73cc13b034bf3fee7954aebb8597aa1feb2c7752
Merge: 51ad7a656 dfcf87cd4
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Mon Feb 17 03:45:28 2020 -0800

    Merge pull request #16248 from jkaniuk/perf-tests-presubmits
    
    Add presubmits for perf-tests release branches

commit 51ad7a656c8cc26cb239e3f0a97d57bab2ad6cf7
Merge: 865454508 5e3b4bed9
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Mon Feb 17 01:03:29 2020 -0800

    Merge pull request #16297 from jprzychodzen/at-roll-2
    
    [Access-tokens] Rollout access-tokens test to seconds set of jobs

**Comment by mm4tt** [comment]
We have two pools, one for continuous jobs and another for presubmits.

![SOojCcuzuHL](https://user-images.githubusercontent.com/2604887/74814129-f2f81b00-52f6-11ea-8030-144bdc276a6f.png)

The continuous one seems pretty healthy, but the presubmit looks even worse now.
Only one commit you listed touched presubmit jobs. I'll take a look. 

In the meantime, @jprzychodzen will add more projects to the presubmit pool to stop the bleeding.

**Comment by mm4tt** [comment]
Something seems off, we have 40 projects in the pool, as of now almost 100% seems to be busy.
But when I tried counting all running presubmit jobs I couldn't find more than 15:

![CoOR3dJF887](https://user-images.githubusercontent.com/2604887/74815189-145a0680-52f9-11ea-8a71-e545a0ba7d4d.png)
![fS4TmoGAZb6](https://user-images.githubusercontent.com/2604887/74815202-16bc6080-52f9-11ea-9a98-ed6e44a6ab75.png)
![cQBU97yLeLv](https://user-images.githubusercontent.com/2604887/74815221-1fad3200-52f9-11ea-9dfc-19974941a320.png)

Is it possible that boskos is somehow leaking the projects? Do we have any logs/metrics from boskos for our presubmit pool?

**Comment by mm4tt** [comment]
/cc @mborsz - scalability oncall
@fejta (test-infra) oncall is already assigned

**Comment by mborsz** [comment]
This can be caused by https://github.com/kubernetes/test-infra/issues/16338

**Comment by mm4tt** [comment]
The perf-test branch release presubmits have been added two days ago in https://github.com/kubernetes/test-infra/pull/16248
I don't see anything wrong with them but it looks like they are causing the problems, so maybe we should consider reverting that PR to potentially stop the bleeding

**Comment by jprzychodzen** [comment]
Adding new projects in #16358

**Comment by mm4tt** [comment]
To summarize the findings from https://github.com/kubernetes/test-infra/issues/16338.  Our understanding is that we have presubmit jobs for which prow is spawning pods continuously and they in turn eat up all the projects in the presubmit boskos pool. We'll try disabling these presubmits as a mitigation to unblock the k/k presubmits (currently all k/k PR are blocked by this).

**Comment by mm4tt** [comment]
Looks like our presubmit pool has recovered:

![HhmdNgCOkGS](https://user-images.githubusercontent.com/2604887/74914456-c1e51c80-53c2-11ea-8dca-9d0910daa85f.png)

One more thing before we close this bug. We added 5 new projects to the pool in https://github.com/kubernetes/test-infra/pull/16358 but most likely some boskos push or reload needs to happen before they get actually added. 

@fejta, is this something you could help us with?

**Comment by ixdy** [comment]
@mm4tt there's [a job](https://prow.k8s.io/job-history/kubernetes-jenkins/logs/post-test-infra-upload-boskos-config) that automatically updates the boskos configmap, but it looks like it's misconfigured:
https://github.com/kubernetes/test-infra/blob/47050c4743c0381165543bcc587a3094c2c5c179/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L617

Another change in `boskos/` just merged, so the config should be updated momentarily, but I'll fix the trigger for that job, too.

**Comment by ixdy** [comment]
fix for the config updater job: https://github.com/kubernetes/test-infra/pull/16395

**Comment by mm4tt** [comment]
Thanks @ixdy for taking a look and fixing the updater job. 
I can see that our presubmit pool has been updated with the 5 extra project. 
We can close this one.


/close
