### ISSUE TITLE
monitor boskos cleanup timing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#14715]
**What would you like to be added**: export and graph metrics for boskos cleanup timing

**Why is this needed**: so we can determine if this is increasing and we need to increase the janitor or fix boskos xref #14697 

Possibly this should also move to the new monitoring stack? cc @cjwagner @detiber 

/area boskos
/assign @krzyzacy 
cc @fejta @mm4tt

**Comment by cjwagner** [comment]
/cc @chaodaiG 
Is also working on boskos metric using the new monitoring stack.

**Comment by stevekuznetsov** [comment]
We have boskos metrics using the new stack... what do you mean? We should sync this week.

**Comment by ixdy** [comment]
Boskos is now using the Prow monitoring stack (#15344). I guess next thing is to expose cleanup timing metrics?

**Comment by ixdy** [comment]
@BenTheElder if you remember, is the intent here to track how long resources are in a given state (e.g. how long something remains as dirty before transitioning to free)? Or how long the actual cleanup itself takes? (Maybe both?)

**Comment by BenTheElder** [comment]
IIRC how long the cleanup takes, which we sometimes have issues with, but
both would be useful

**Comment by ixdy** [comment]
Moving this issue to https://github.com/kubernetes-sigs/boskos/issues/13.
/close
