### ISSUE TITLE
Testgrid output not showing test failures?

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1473]
This morning, I checked a pretty stock URL: https://k8s-testgrid.appspot.com/google-aws#kops-aws .. and all I'm seeing now is the results for `Overall`, nothing else:

![screenshot from 2017-01-03 11 29 44](https://cloud.githubusercontent.com/assets/4942464/21620188/ff38fcc8-d1a7-11e6-9bee-e33ebf57d9d7.png)

**Comment by spxtr** [comment]
https://k8s-testgrid.appspot.com/google-aws#kops-aws&show-stale-tests=

**Comment by zmerlynn** [comment]
Those tests are "stale" even though they were reported as short ago as midnight last night?

**Comment by fejta** [comment]
Stale is based on the number of columns, not time.

**Comment by rmmh** [comment]
d83882fae855231cb4bc21f4020bb1c27e0bd4e1 broke the test, since this tries to execute "blah"

    VAR=\
      blah

**Comment by rmmh** [comment]
Apparently the space is the problem?

    $ VAR= blah
    No command 'blah' found, did you mean:

**Comment by zmerlynn** [comment]
@rmmh: That change was irrelevant to the testgrid output.
@fejta: That's kind of a bad UI.

**Comment by zmerlynn** [comment]
(@rmmh: Thanks for the heads up. What actually broke the job at midnight was something else entirely, but the point of this bug is that there's plenty of data in here which was by no means "stale", and I wasn't expecting to need that filter so didn't even try.)

**Comment by fejta** [comment]
/unassign @rmmh 
/assign @michelle192837 
who is working on this

**Comment by krzyzacy** [comment]
things are migrated from bash world to scenarios, and testgrid looks fine now

**Comment by fejta** [comment]
Michelle's updating testgrid to make it obvious when results are hidden. Michelle feel free to leave this closed or `/reopen` if you prefer
