### ISSUE TITLE
Enable the slack reporter for k8s Prow Crier deployment

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#14740]
**What would you like to be added**:
Enable the slack reporter for k8s Prow Crier deployment, ref: #14736.
> [slack reporter docs](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/crier/README.md)

**Why is this needed**:
Enhanced test failure awareness via Slack channel notification.

/help
/good-first-issue

**Comment by helderjs** [comment]
Hi!

@clarketm 
I think I can help with this but I believe I need access to the cluster to create the secret (or someone needs to create it for me).

All the rest is about update https://github.com/kubernetes/test-infra/blob/6496538168bbd6a3aaa8b139a30d533a8943d2ee/prow/cluster/crier_deployment.yaml#L36 according to https://github.com/clarketm/kubernetes_test-infra/blob/b75a14a3781cc6b5b196b6d6328293a23938c2c1/prow/cmd/crier/README.md#slack-reporter

**Comment by clarketm** [comment]
Hi @helderjs,

I do not have full cluster access either. Please reach out to @cjwagner (or send a message to Kubernetes [#testing-ops](https://kubernetes.slack.com/messages/C7J9RP96G) slack channel to solicit help regarding secret creation). There may already be a token in the cluster. 

Regarding configuration, you are correct:
- [ ] Update [crier_deployment.yaml](https://github.com/kubernetes/test-infra/blob/6496538168bbd6a3aaa8b139a30d533a8943d2ee/prow/cluster/crier_deployment.yaml#L36) as delineated in the documentation. 
- [ ] Update [config.yaml]() with slack reporter configuration. We can probably use the same [configuration as Istio](https://github.com/istio/test-infra/blob/60a281cb5efd73c77fe6ff1b9a9d63b8dfb3ef91/prow/config.yaml#L60-L70) to start with.

**Comment by helderjs** [comment]
@clarketm PR is done. I'm trying to get someone to create the secret in the cluster.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/blob/e36eb04fdc6565d695a0086906ac5c92df7fb10b/prow/cluster/hook_deployment.yaml#L93

a token exists. need to verify that it's the correct one.

**Comment by clarketm** [comment]
@BenTheElder
You can verify the token here: https://api.slack.com/methods/chat.postMessage/test. We will need to ensure the `test-failures` channel exists first.

**Comment by BenTheElder** [comment]
yep, that token works with that API

**Comment by helderjs** [comment]
@clarketm @BenTheElder is the name of the secret as I defined `slack-token`?
also what about the channel? should I ask someone to create the `test-failures` channel or change the config to something else?

**Comment by clarketm** [comment]
> @clarketm @BenTheElder is the name of the secret as I defined `slack-token`?
> also what about the channel? should I ask someone to create the `test-failures` channel or change the config to something else?

@BenTheElder verified the token; `test-failures` channel, like you have configured, is fine. Reach out to Slack [#testing-ops](https://kubernetes.slack.com/messages/C7J9RP96G) regarding channel creation.
