### ISSUE TITLE
Checkconfig should not expect `trigger` to be enabled on gerrit repos.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#14743]
**What happened**:
The [checkconfig](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig) component expects every repo that specified a job to enable the trigger plugin and it checks this if plugins.yaml is provided. This isn't correct for gerrit repos.
```json
{"component":"checkconfig","file":"prow/cmd/checkconfig/main.go:76","func":"main.reportWarning","level":"warning","msg":"the following repos have jobs configured but do not have the trigger plugin enabled: repo: https://kunit-review.googlesource.com/linux","time":"2019-10-11T23:23:41Z"}
```
**What you expected to happen**:
checkconfig should not require `trigger` to be enabled for gerrit repos. Here is an example gerrit job https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/kunit-review.googlesource.com/linux/kunit-linux-config.yaml
I think the only way we can distinguish it as a gerrit job is the url instead of `<org>/<repo>` format used for GH repos. 
/help
/good-first-issue
cc @stevekuznetsov @krzyzacy

**Comment by hasheddan** [comment]
@cjwagner I am happy to take this one!

**Comment by e-blackwelder** [comment]
I'll look into this.
