### ISSUE TITLE
Add ability to control behavior of presubmit failure / success reporting with the Gerrit reporter

### ISSUE THREAD

**Issue by spew** [kubernetes/test-infra#14757]
**What would you like to be added**:

The ability control when a the success or failure of a presubmit job is reported. For example, reporting on first error, etc.

**Why is this needed**:

When running multiple presubmit jobs, for example, a "build" job and a "test" job, some jobs take much less time than others and it would be useful to get fast feedback and know if they failed right away before waiting for the longer running jobs to complete.

**Comment by stevekuznetsov** [comment]
I'm pretty certain this is already the behavior as written. @cjwagner @krzyzacy

**Comment by cjwagner** [comment]
This is in the context of the Gerrit reporter which behaves differently than the GitHub reporter.

**Comment by cjwagner** [comment]
Work around from @amwat:

> Combined reporting can be worked around by using two different labels configured via the  prow.k8s.io/gerrit-report-label label
(e.g. Code-Review for one job, Verified for the other, or can create a new label altogether) for the two presubmit jobs. 
> 
> Note that this will just result in the build job to report as soon as it finishes, it won't actually abort the other job (if that's what you meant by short circuit)
