### ISSUE TITLE
kops now prefers KOPS_BASE_URL to KOPS_URL

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#1478]
So I stole @zmerlynn 's idea of KOPS_URL, but I renamed it KOPS_BASE_URL for clarity.

We do recognize KOPS_URL still, so this isn't urgent, but it would be great to switch this to KOPS_BASE_URL.

cf https://github.com/kubernetes/kops/pull/1318#discussion_r94518376

Thanks @zmerlynn :-)

**Comment by krzyzacy** [comment]
looks like it's using it?

**Comment by zmerlynn** [comment]
Yup!
