### ISSUE TITLE
tide: excessive memory usage

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#14798]
We are seeing much larger memory consumption by `tide` than before:

![Screenshot from 2019-10-16 11-44-23](https://user-images.githubusercontent.com/7328370/66948915-75e82c80-f00a-11e9-9de5-27702d56080c.png)

This is the last bump [here](https://github.com/openshift/release/commit/c3532fdb305a4b46bb0ced77cbf56371a307704c) and does not seem co-located in time.

/cc @cjwagner @alvaroaleman

**Comment by stevekuznetsov** [comment]
While we have spikes sometimes, the new behavior is novel:

![Screenshot from 2019-10-16 12-00-55](https://user-images.githubusercontent.com/7328370/66950111-a0d38000-f00c-11e9-966d-8cbe5f29d91a.png)

We have not seen a large change in ProwJobs in the cluster:

![Screenshot from 2019-10-16 11-52-53](https://user-images.githubusercontent.com/7328370/66949502-8056f600-f00b-11e9-9a6a-a75f0b0d3507.png)

**Comment by stevekuznetsov** [comment]
Ahhh holy shit we're running two replicas of `tide`:

![Screenshot from 2019-10-16 12-03-02](https://user-images.githubusercontent.com/7328370/66950298-f019b080-f00c-11e9-84c3-99759804e8b3.png)

**Comment by stevekuznetsov** [comment]
We only are configured to run one, though ... https://github.com/openshift/release/blob/master/core-services/prow/03_deployment/tide.yaml#L35

**Comment by stevekuznetsov** [comment]
Only one pod is listed in the running phase at  once ... 

![Screenshot from 2019-10-16 12-13-21](https://user-images.githubusercontent.com/7328370/66951038-636ff200-f00e-11e9-8310-dd3d774547d4.png)

**Comment by stevekuznetsov** [comment]
OK let's forget all that... it was a bad average window. We *are* seeing abnormally high usage since the last bump.

![Screenshot from 2019-10-16 12-21-36](https://user-images.githubusercontent.com/7328370/66951603-9bc40000-f00f-11e9-9d46-911496a6f40e.png)

**Comment by stevekuznetsov** [comment]
And that was CPU, but we see it on memory, too: 

![Screenshot from 2019-10-16 12-25-24](https://user-images.githubusercontent.com/7328370/66951804-10973a00-f010-11e9-80e8-c99bd016949c.png)

**Comment by stevekuznetsov** [comment]
Migration from `gcr.io/k8s-prow/tide@sha256:56b9cbe11cd80b7cfda17d2c8e3574c0e7f10be99247a3045e5764ec4e4a0229` to `gcr.io/k8s-prow/tide@sha256:ff79563d7cd69e0567fd663defb325362f32c207db928880d67d380c273a55b7`

**Comment by alvaroaleman** [comment]
@stevekuznetsov Now that #14830 has merged, could you check if and how much impact that has on the cpu and memory consumption?

**Comment by stevekuznetsov** [comment]
@alvaroaleman it now seems like steady state is better but at startup we see a lot of load. Is that expected?

![Screenshot from 2019-11-06 05-26-04](https://user-images.githubusercontent.com/7328370/68302002-f3291f00-0055-11ea-8ea9-beeb58eede60.png)
![Screenshot from 2019-11-06 05-25-49](https://user-images.githubusercontent.com/7328370/68302003-f3291f00-0055-11ea-97b8-fa49c0c85950.png)

**Comment by alvaroaleman** [comment]
>  it now seems like steady state is better but at startup we see a lot of load. Is that expected?

Yes, because it has to deserialize all ProwJobs and run all of them through the indexing func

**Comment by stevekuznetsov** [comment]
Sounds good.
