### ISSUE TITLE
updateconfig: use a local clone to retrieve files, not the GitHub API

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#14795]
In the `updateconfig` plugin, we need to fetch the content of files before we upload them to the cluster inside of ConfigMaps. To encapsulate this behavior, we have an interface:

https://github.com/kubernetes/test-infra/blob/f63737a069e07158d0d98d2d0399fe00d0df6a68/prow/plugins/updateconfig/updateconfig.go#L76-L79

The implementation of this interface used by the plugin, however, uses GitHub to fetch the file contents:

https://github.com/kubernetes/test-infra/blob/f63737a069e07158d0d98d2d0399fe00d0df6a68/prow/plugins/updateconfig/updateconfig.go#L81-L88

It is possible, however, to simply load the files from disk if the appropriate version of the repository is checked out, as is done in the `config-bootstrapper`:

https://github.com/kubernetes/test-infra/blob/f63737a069e07158d0d98d2d0399fe00d0df6a68/prow/cmd/config-bootstrapper/main.go#L141-L147

The current behavior of `updateconfig` is problematic as its token use scales linearly with the number of files changed that need to be uploaded. This allows for inadvertent DoS of the system by changing a large number of configuration files at once. The `updateconfig` plugin should be updated to clone the repository at the version that was pushed and use the local checkout to populate file contents.

/cc @cjwagner 
/area prow/hook

**Comment by rajibmitra** [comment]
@stevekuznetsov  if I change the /updateconfig's gitHubFileGetter to  osFileGetter  , will it be able to 
use the local checkout to populate file contents ?

**Comment by stevekuznetsov** [comment]
You'll need to call `git.Clone()` first to populate the filesystem, then use the `osFileGetter`@
