### ISSUE TITLE
remove the usage of test_owners.* files in k/k and test-infra

### ISSUE THREAD

**Issue by neolit123** [kubernetes/test-infra#14839]
recently i set a PR that updates some test owners in k/k:
https://github.com/kubernetes/kubernetes/pull/83744#issuecomment-543288884

i noticed that the test/test_owners.{csv|json} files are quite out of date, so i started wondering if they are used.
https://github.com/kubernetes/kubernetes/blob/master/test/test_owners.csv
https://github.com/kubernetes/kubernetes/blob/master/test/test_owners.json

i found a legacy script in hack/ and though that perhaps they can be removed from k/k:
https://github.com/kubernetes/kubernetes/search?q=%22test_owners%22&unscoped_q=%22test_owners%22
the script fails locally for me.

but then i saw that test owners are also used in test-infra.
https://github.com/kubernetes/test-infra/search?q=%22test_owners%22&unscoped_q=%22test_owners%22

the issue-creator image uses a copy of the CSV file (last undated 2 years ago):
https://github.com/kubernetes/test-infra/tree/master/robots/issue-creator
https://github.com/kubernetes/test-infra/blob/5068c876e61fe13de9d4508be4dd4eab3d6abc2e/config/jobs/kubernetes/test-infra/fejta-bot-periodics.yaml#L287

there is also this script that downloads the k/k test_owners:
https://github.com/kubernetes/test-infra/blob/38069797866a890531b69a95e807c13388a558a5/triage/update_summaries.sh#L65-L72

so a question would be, can we deprecate test_owners files completely from both k/k and k/test-infra?

if not feasible i would like to at least PR the https://github.com/kubernetes/test-infra/blob/master/robots/issue-creator/test_owners.csv file to match the one from k/k or potentially always download the file from k/k instead?

/priority backlog
/kind cleanup
cc @fejta @cblecker

**Comment by cblecker** [comment]
My preference would be unwinding and removing test_owners, but I don't know if anyone else needs it

cc: @kubernetes/sig-testing @BenTheElder

**Comment by BenTheElder** [comment]
I tried to remove it recently and ran into these same problems and didn't have the bandwidth to go further.

**Comment by neolit123** [comment]
i have similar bandwidth issues.

but i think we can do this part at least:
> if not feasible i would like to at least PR the https://github.com/kubernetes/test-infra/blob/master/robots/issue-creator/test_owners.csv file to match the one from k/k or potentially always download the file from k/k instead?

to have the issue-creator use the same location?

**Comment by fejta** [comment]
I suspect some tool somewhere uses it, but I don't think this experiment has been successful. I'm supportive of ending it.

**Comment by neolit123** [comment]
sent PRs for both action items:
- https://github.com/kubernetes/test-infra/pull/14845
https://github.com/kubernetes/kubernetes/pull/84070

ideally the test-infra PR should merge first.

**Comment by neolit123** [comment]
PRs merged. closing.
