### ISSUE TITLE
Disable GINKGO_TOLERATE_FLAKES on kops-aws

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1484]
I'm turning this option on, for this job, until I can deflake this more. It's valuable to keep it SQ blocking, but the SQ flake detection doesn't seem to be catching enough.

**Comment by lavalamp** [comment]
This means stuff will have to fail 4 times in a row to block the queue...

**Comment by fejta** [comment]
Migrated to kops repo
