### ISSUE TITLE
Tide doesn't create jobs for Presubmits that were added after PR opening

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#14867]
**What happened**:

When working on https://github.com/kubernetes/test-infra/pull/14866, I noticed that if:

1. Someone creates a PR
1. That pr gets tested successfully but doesn't meet other merge requirements like labels
1. Someone adds a new mandatory presubmit
1. That PR gets all required labels

Tide will not create the missing job and instead just filter out the PR: https://github.com/kubernetes/test-infra/blob/1ae6e66ed69d04490af43af88b77e0767fc90c7e/prow/tide/tide.go#L590

**What you expected to happen**:

Tide to either:

* Ignore missing contexts that are managed by Prow when filtering PRs
* Create a job for the missing context

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/cc @cjwagner @stevekuznetsov

**Comment by stevekuznetsov** [comment]
You are supposed to be using the `status-reconciler`, which solves this gap.

**Comment by alvaroaleman** [comment]
> You are supposed to be using the status-reconciler, which solves this gap.

I see.
