### ISSUE TITLE
Remove TrustedOrg logic

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#14875]
Does anyone use this? We have it configured, but tbh, I don't think we need to.. we should just fall back on the "if you're in the org that the PR is against, then you're trusted. If you're not, you're not."

If we expand use of "TrustedUser" (e.g. #13740) then I'd like to keep it really simple/clear.

Thoughts?

cc: @kubernetes/sig-testing

**Comment by fejta** [comment]
Historically this was used to ensure that someone in the kubernetes or can run presubmits on a PR in a kubernetes-sigs repo.

**Comment by cblecker** [comment]
So as long as we're willing to accept that you need to be in k-sigs to test a PR, then we are fine?

**Comment by fejta** [comment]
Right

**Comment by cblecker** [comment]
Step 1: Deprecate field, add warning.
Step 2: Remove our reliance on this option.
Step 3 (January 2020): Completely remove option/related code.

Step 1 and 2 PR: https://github.com/kubernetes/test-infra/pull/14990

**Comment by munnerz** [comment]
😬 we use this as we add users to the `cert-manager` org in order to grant them permission to do things in the `jetstack/cert-manager` repository (as we cannot add people to our main org 🙈)

**Comment by cblecker** [comment]
@munnerz Is it not possible to add them as outside collabs with Read+ access on the repo itself?

**Comment by munnerz** [comment]
Yep this could be done - peribolos doesn't support repo-level permissions however, which is why we resolved to use an org... until the recently github changes to allow anyone that's commented on a PR to be assigned, we _also_ added them as readonly collaborators. But those changes now mean we only need them to be org members 😄

**Comment by munnerz** [comment]
(for `/lgtm` specifically - I am still unable to `/assign @some-org-member-that-has-not-commented`)

**Comment by BenTheElder** [comment]
@cblecker I just discovered this field was never removed :+)
