### ISSUE TITLE
Deck overview: Huge performance degradation 484b36c51 -> 7c8165546

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#14910]
**What happened**:

We upgraded our Prow setup from `v20190827-484b36c51` to `v20191022-7c8165546` and now suddenly loading the Deck overview is extremely slow. We currently have roughly 22k ProwJobs in the cluster. The culprit seems to be the `data.js`/`prowjobs.js` which took ~1s before and now needs ~10s. See the screenshots below for the info from the `network` tab of the chrome developer tools.

![deck-fast](https://user-images.githubusercontent.com/6496100/67278467-51d49180-f4c9-11e9-96e8-251af1eafdd8.png)
![deck-slow](https://user-images.githubusercontent.com/6496100/67278476-5436eb80-f4c9-11e9-8691-a39920d42458.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

CC @clarketm @Katharine 
/area prow/deck

**Comment by alvaroaleman** [comment]
What I find interesting though is that the prow.k8s.io instance has an even higher number of prowjobs but seems to be performing well. Is there anything else I can look at?

**Comment by clarketm** [comment]
It looks like most of the *additional* time is spent **waiting (TTFB)** (which is what the green segment indicates). This indicates that payload size (which should be ~same with `omit` directive) is not a factor.

@alvaroaleman 
If this long request latency consistently slow or only on initial version switch? I expect there is something else causing the slowness, but not sure what it is ATM.

**Comment by xmudrii** [comment]
@clarketm If by initial upgraded versions you think the first time loaded after upgrade to the new version, no. It has been very slow every time the page was loaded. The time needed to load the page was varying between 15 and 30 seconds for me.

**Comment by clarketm** [comment]
@xmudrii 
Are you using the default template which specifies an `omit` parameter to reduce size of response?
https://github.com/kubernetes/test-infra/blob/a1a5b03d5644aaf935fbb9aa833c94bfde013d30/prow/cmd/deck/template/index.html#L5

There is nothing immediately obvious on the [backend](https://github.com/kubernetes/test-infra/commit/448f6c5d0ec3e4123eb4bd32a7e893ea8b37918f#diff-91ff1bbeaa4f820afc3b9ebfd3607e61) from the switch to use `prowjobs.js` #14126 that would warrant such an increase increase in load time.

**Comment by xmudrii** [comment]
@clarketm I'm not sure about that, so I'll have to leave it to @alvaroaleman to confirm it. I think we use the default template. Looking at the inspect element/sources on Chrome, I can see the line like you posted. However, this is on the previous version we used, I can't test it with the latest one.

**Comment by alvaroaleman** [comment]
Yeah we do use the default template. Performance went back to normal, it seems this is only an issue when hitting a freshly created Deck replica but goes back to normal afterwards. Thanks for your help Travis.
