### ISSUE TITLE
Prow issue: helm/charts#17931 pull-chart-e2e failed repetitively

### ISSUE THREAD

**Issue by oke-py** [kubernetes/test-infra#14923]
https://github.com/helm/charts/pull/17931

build log
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/17931/pull-charts-e2e/1184811643536674818/

@zanhsieh said as below at https://github.com/helm/charts/pull/17931#issuecomment-542475973
> pull-charts-e2e test probably affected by prometheus chart due to it does not restrict which namespace it should fetch (in other words, each PR = 1 namespace and fetch all). I saw it ran 28h7m55s last night:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/helm_charts/17935/pull-charts-e2e/1183727888063533058/
> 
> Currently have no idea which sig channel to report and / or force stop this test.

How to resolve 17931 test failure?
How to stop 17935 test if it causes 17931 failure?

**Comment by stevekuznetsov** [comment]
I would look at the `git blame` for who wrote the test, looks like @krzyzacy did ages ago in dd9ac43082479ab73c1665592b32a8c4045f7c1a

**Comment by oke-py** [comment]
Thanks, and so what should be done? I'd like 17931 test to pass.
Is this a correct place to report?

**Comment by krzyzacy** [comment]
who's the owner of the repo? they should be owning the tests

**Comment by oke-py** [comment]
So, I should open an issue on [helm/charts](https://github.com/helm/charts) and the owner should resolve the problem, right?

**Comment by oke-py** [comment]
I'm not sure why, but helm/charts#17931 pull-chart-e2e passed and merged.
