### ISSUE TITLE
Test got terminated randomly after upgrading to gcr.io/k8s-testimages/kubekins-e2e:v20191017-ac4b4b5-master

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/test-infra#14938]
Right after the upgrade https://github.com/kubernetes/test-infra/commit/71aae2c3e826d617106fb400ad8bad4f2a35ebd6#diff-bc1a19dd8cab7a55902e9a81d5f4d935

The containerd windows test starts being randomly terminated in the middle of the test.
We start seeing this right after that image update.

**Comment by Random-Liu** [comment]
An example test failure https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-cri-validation-windows/1184908137358954497

And from the dashboard, we can see that the first failure started since 10-17 12:04, and the change was merged at 10-17 11:08.

**Comment by BenTheElder** [comment]
do you have a specific example?

**Comment by Random-Liu** [comment]
This seems to be a bash issue, there are some previous bug reports, haven't looked into them yet:
* https://github.com/nodejs/node/issues/19838
* https://github.com/nodejs/node-v0.x-archive/issues/3027

If it is a bash issue, it could be caused by the debian update from stretch to buster.

**Comment by Random-Liu** [comment]
Based on https://github.com/nodejs/node/issues/14752, it seems that something set the stdout to O_NONBLOCK mode.

The windows test runs a lot of gcloud ssh and gcloud scp command, and gcloud is also updated in that window:
```console
$ docker run --entrypoint=/bin/bash gcr.io/k8s-testimages/kubekins-e2e:v20191017-ac4b4b5-master gcloud version
Google Cloud SDK 267.0.0
alpha 2019.05.17
beta 2019.05.17
bq 2.0.49
core 2019.10.15
gsutil 4.44
kubectl 2019.09.22

$ docker run --entrypoint=/bin/bash gcr.io/k8s-testimages/kubekins-e2e:v20191012-482f444-master gcloud version
Google Cloud SDK 250.0.0
alpha 2019.05.17
beta 2019.05.17
bq 2.0.43
core 2019.06.07
gsutil 4.38
kubectl 2019.06.07
```

It seems very likely to be a bug in the new gcloud version that it sets the stdout to `O_NONBLOCK` mode.

I'll apply the fix https://github.com/uwcirg/truenth-portal/pull/2689 to the test for now to set the stdout back before the large `cat`.

**Comment by Random-Liu** [comment]
It does turn out that `O_NONBLOCK` is set by something https://github.com/containerd/cri/pull/1324:
```
+ python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'
2048
+ python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.
```

I highly suspect that it is gcloud.

Anyway, I think it is more a gcloud issue than a test-infra issue. I'll close this one for now. And for people who hits similar issue in the future, they can reference this issue to find a workaround.
