### ISSUE TITLE
Tide should limit time spent on GitHub queries when syncing

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#14949]
Recently we got a Tide sync error because the sync loop averaged > 2 min. for > 15 min. Syncing kubeflow/pipeline took ~48 min. total, delaying the overall sync.

Not urgent, since Tide recovered fine, but as @cjwagner noted Tide should have a timeout on queries to GitHub.

/area prow/tide

**Comment by cjwagner** [comment]
@michelle192837 Did you mean clones from GH? AFAICT all the GitHub API requests have timeouts.

**Comment by michelle192837** [comment]
I think cloning the repo, yeah.

**Comment by stevekuznetsov** [comment]
Could we please paste representative logs from `tide` to help isolate what, exactly, took 48 minutes?
