### ISSUE TITLE
Downgrade errors when attempting to parse a non-OWNERS file for owners

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#14950]
We log an error when trying to parse YAML headers for per-file OWNERS, but some files are just going to error on parsing (e.g. Hugo template files). Downgrade the error to an info log since the urgency doesn't warrant it (this will sometimes happen, but at info level we can search for it if we really need to).

/assign
/kind oncall-hotlist

**Comment by BenTheElder** [comment]
ping

**Comment by michelle192837** [comment]
I'll take a stab at this again.

**Comment by BenTheElder** [comment]
thanks!

**Comment by chases2** [comment]
@michelle192837 Has this issue been resolved?

**Comment by michelle192837** [comment]
Yup!
