### ISSUE TITLE
prow: welcome plugin shouldn't fire for org members

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#14979]
**What would you like to be added**:
If you are a TrustedUser (i.e. a member of the org), then the welcome plugin shouldn't fire it's welcome message.

A simple statement in https://github.com/kubernetes/test-infra/blob/c72e3b6bbabf6e16127c0d29e90ebaa1cc78949a/prow/plugins/welcome/welcome.go#L106 checking if the user is a TrustedUser and returning nil should suffice.

**Why is this needed**:
If it's a new repo, then even a long time kubernetes member won't have any PRs against it. So these users get a welcome message that they don't need.

/good-first-issue

**Comment by cblecker** [comment]
cc @nikhita @BenTheElder 
/area prow

**Comment by BenTheElder** [comment]
/shrug
sure
