### ISSUE TITLE
ci-kubernetes-build jobs re-run on the same git hash causes hash mismatches

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1499]
It's not clear to me why we re-ran this build, but this is not a good idea:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build/553/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build/554/

In anything diligently checking hashes, it will cause e2e failures. See e.g.: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1886/artifacts/ec2-35-162-137-2.us-west-2.compute.amazonaws.com/cloud-init-output.log

cc @kubernetes/test-infra-maintainers @justinsb @david-mcmahon

**Comment by zmerlynn** [comment]
Can we just switch the upload to `gsutil cp -n` (no clobber), vs whatever is done today? We really shouldn't need to override an existing build, and if we have to, we can either manually delete it or pass a flag.

**Comment by ixdy** [comment]
Jenkins is broken, film at 11.

From job/ci-kubernetes-build/553/pollingLog/:
```
Started on Jan 4, 2017 2:18:00 PM
Using strategy: Default
[poll] Last Built Revision: Revision 6b702115680cac7f55e0d106cbd2a99d783301aa (origin/master)
 > git --version # timeout=10
 > git -c core.askpass=true ls-remote -h https://github.com/kubernetes/kubernetes # timeout=10
Found 27 remote heads on https://github.com/kubernetes/kubernetes
[poll] Latest remote head revision on refs/heads/master is: cb78349735ee6e8740eec9d769ae12e9f1178a96
Done. Took 0.76 sec
Changes found
```

From job/ci-kubernetes-build/554/pollingLog/
```
Started on Jan 4, 2017 2:34:00 PM
Using strategy: Default
[poll] Last Built Revision: Revision 6b702115680cac7f55e0d106cbd2a99d783301aa (origin/master)
 > git --version # timeout=10
 > git -c core.askpass=true ls-remote -h https://github.com/kubernetes/kubernetes # timeout=10
Found 27 remote heads on https://github.com/kubernetes/kubernetes
[poll] Latest remote head revision on refs/heads/master is: cb78349735ee6e8740eec9d769ae12e9f1178a96
Done. Took 0.75 sec
Changes found
```

It built 6b702115680cac in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build/552/; I have no idea why 554 didn't notice 553's build.

**Comment by zmerlynn** [comment]
My suspicion is that this is causing some large portion of the remaining `kops-aws{,-updown}` flakes.

**Comment by justinsb** [comment]
Another instance of this in #1589 

719 vs 720

http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-build/719
`I0118 14:42:14.996] Start 719 at v1.6.0-alpha.0.3506+9dd96e31204ea8...`

(finished at 14:55:29, then 20 minutes later - maybe exactly 20 minutes later?)

http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-build/720
`I0118 15:16:48.186] Start 720 at v1.6.0-alpha.0.3506+9dd96e31204ea8...`


727 and 728 _also_ both built the same SHA.  728 again started pretty close to 20 minutes after 727 finished.

I checked the Jenkins job definition - LGTM (e.g. no time trigger): https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci-commit.yaml#L71-L77

But (clutching at straws here)... is it possible that the Jenkins job as defined in Jenkins still has a time trigger defined on it of 20 minutes idle (e.g. maybe we don't remove extra triggers when building the Jenkins jobs).  But this also doesn't make sense because if this were the case I would expect to see the job running regularly all night, and we don't.

Otherwise, Jenkins does have a logfile - any hints around 728?

But rather than grappling with jenkins: I think I like @zmerlynn 's proposed fix ... it might be easiest simply not to overwrite existing files.  

Alternatively: to insert the jenkins job into the build version (we're already inserting what looks like a random number `v1.6.0-alpha.0.3531+f90bb1772b833a` - I don't know where 3531 comes from.)

**Comment by spxtr** [comment]
Looks like it might be a bug in the git plugin on Jenkins. The last built revision didn't update and so it thought there were changes.

For 718
```
Started on Jan 18, 2017 1:38:00 PM
Using strategy: Default
[poll] Last Built Revision: Revision 5ca25bea211e3f75d915b64de862b289421c2699 (origin/master)
 > git --version # timeout=10
 > git -c core.askpass=true ls-remote -h https://github.com/kubernetes/kubernetes # timeout=10
Found 27 remote heads on https://github.com/kubernetes/kubernetes
[poll] Latest remote head revision on refs/heads/master is: 4520819df7a1746d4d64b46298831fa9222f190d
Done. Took 0.78 sec
Changes found
```
719
```
Started on Jan 18, 2017 2:26:00 PM
Using strategy: Default
[poll] Last Built Revision: Revision 4520819df7a1746d4d64b46298831fa9222f190d (origin/master)
 > git --version # timeout=10
 > git -c core.askpass=true ls-remote -h https://github.com/kubernetes/kubernetes # timeout=10
Found 27 remote heads on https://github.com/kubernetes/kubernetes
[poll] Latest remote head revision on refs/heads/master is: b29d9cdbcfd3f84e0d7574f51d552d5a71e7cfb6
Done. Took 0.71 sec
Changes found
```
720
```
Started on Jan 18, 2017 2:42:00 PM
Using strategy: Default
[poll] Last Built Revision: Revision 4520819df7a1746d4d64b46298831fa9222f190d (origin/master)
 > git --version # timeout=10
 > git -c core.askpass=true ls-remote -h https://github.com/kubernetes/kubernetes # timeout=10
Found 27 remote heads on https://github.com/kubernetes/kubernetes
[poll] Latest remote head revision on refs/heads/master is: 9dd96e31204ea8d3eb9a999ba1b08c5c0bf40688
Done. Took 0.75 sec
Changes found
```

**Comment by ixdy** [comment]
@spxtr how close is CI prow to working? Can we get it to trigger Jenkins builds on git changes instead of relying on the Jenkins git plugin?

**Comment by spxtr** [comment]
Oh, I see. 719 has https://github.com/kubernetes/kubernetes/commit/9dd96e31204ea8d3eb9a999ba1b08c5c0bf40688 in its changes but it has the head pointing to one commit before it, so then 720 thought that it was new even though it had already tested it. That's definitely a bug in the git plugin.

**Comment by spxtr** [comment]
> @spxtr how close is CI prow to working? Can we get it to trigger Jenkins builds on git changes instead of relying on the Jenkins git plugin?

I can trigger Jenkins builds on git changes, but I don't have any way of retriggering them if a build flakes or something.

**Comment by zmerlynn** [comment]
Honestly, a quick fix to this is to change the upload to no-overwrite instead. That's what I did in the kops repo because of this bug.

A more complicated fix is to change it to check before upload, and upload to a slightly different version (slap a counter on the semver extras) if it's already there.

**Comment by zmerlynn** [comment]
Are either one of these solutions more palatable? This needs to be fixed, as demonstrated by
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/2875/artifacts/ec2-174-129-133-66.compute-1.amazonaws.com/cloud-init-output.log and https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/2875/artifacts/ec2-174-129-133-66.compute-1.amazonaws.com/cloud-init-output.log, which caused a SQ blockage.

How about no-overwrite? It's an easy solution, and we can always destroy the artifacts if we really need to redrive a build.

**Comment by zmerlynn** [comment]
cc @krousey

**Comment by krousey** [comment]
This is blocking the queue for the second time today. What is the plan moving forward and what is the eta on that plan?

**Comment by rmmh** [comment]
`gsutil cp -n` sounds like a good fix to me.

**Comment by zmerlynn** [comment]
I'm actively working on fixing `push-build.sh` to skip overwrite, but the dev push case (private bucket, iterating) is kind of obnoxious for that case. I'll get something out soon.

**Comment by zmerlynn** [comment]
I'm inclined to just error out if the destination exists, but it will push the flake into the `kubernetes-build` job (where it belongs).

**Comment by ixdy** [comment]
I was going to suggest trying to upgrade some of the git/scm plugins on Jenkins, to see if that would fix the root cause, but given [this blog post](https://jenkins.io/blog/2017/01/17/scm-api-2/) I'm not very confident that Jenkins would still work after upgrading.

**Comment by zmerlynn** [comment]
https://github.com/kubernetes/release/pull/251
