### ISSUE TITLE
prow job inits error for private repo.

### ISSUE THREAD

**Issue by morvencao** [kubernetes/test-infra#14992]
**What happened**:

I have set up a prow cluster for public repos and private repos, the public repos and private repos are in different Github Org. The result is that prow jobs for public repos are running normally, while the prow jobs for private repos can't be initialized with the follow error:
```
{"command":"git fetch https://github.com/xxxxxx/xxxxxxxxxxxx.git --tags --prune","component":"clonerefs","error":"exit status 128","file":"prow/pod-utils/clone/clone.go:42","func":"k8s.io/test-infra/prow/pod-utils/clone.Run.func1","level":"info","msg":"Ran command","output":"fatal: could not read Username for 'https://github.com': No such device or address\n","time":"2019-10-28T03:32:15Z"}
{"component":"clonerefs","file":"prow/cmd/clonerefs/main.go:43","func":"main.main","level":"info","msg":"Finished cloning refs","time":"2019-10-28T03:32:15Z"}
```

Looks like the issue is caused by insufficient permission of github token that created for prow cluster and webhook, however, I havae double checked the github token have the permission of private repos, because I have checked all the option on `repo` section:
![image](https://user-images.githubusercontent.com/5468682/67653552-cce3ef00-f984-11e9-989c-ec4d629b912b.png)

Am I missing something? Appreciate it if anyone can help in this?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

IMO, another thing that matters is that while I add webhook for repos with `bazel`, I got error of 

```
INFO: Running command line: bazel-bin/experiment/add-hook/linux_amd64_stripped/add-hook '--hmac-path=github-webhook-secret' '--github-token-path=github-bot-token' --hook-url http://xxx.xxx.xxx.xxx/hook
INFO: Build completed successfully, 1 total action
INFO[0000] ListRepoHooks(myorg, myrepo)  client=github
INFO[0000] EditRepoHook(myorg, myrepo, 152785119)  client=github
INFO[0001] ListOrgHooks(myorg)                  client=github
FATA[0008] Could not apply hook to myorg: list: return code not 2XX: 404 Not Found
```

As you can see, `bazel` failed to list Github Org Webhook, but it can successfully add webhook for repo in that Org, is it the root cause of the prow jobs initializing error? How should address this issue?

/cc @gyliu513 @qiujian16

**Comment by gyliu513** [comment]
area/prow/clonerefs

**Comment by morvencao** [comment]
Found the root cause: I did't add `ssh-key` to the `ssh_key_secrets` field of the job decoration config, after configuring the job following the doc here: https://github.com/kubernetes/test-infra/blob/cab76bdbd3760143a7b45dc35cf0b4d8d43b6c77/prow/pod-utilities.md#how-to-configure

The prow jobs for private repos are starting running.
