### ISSUE TITLE
Plank hangs on errors and is not able to schedule further jobs

### ISSUE THREAD

**Issue by kasiakepka** [kubernetes/test-infra#15013]
**What happened**:
Plank started throwing "cannot unmarshal" ERRORs that were caused by faulty ProwJob configuration. ProwJob config was missing quotes as it was prepared manually. It of course affected Plank and basically whole Prow stropped working as Plank was stuck on erroneous job and couldn't schedule new jobs. After deleting Prowjob it all started working as expected.

**What you expected to happen**:
Plank is still able to schedule new jobs even if there is one unschedulable ProwJob with faulty configuration.

**How to reproduce it (as minimally and precisely as possible)**:
Create ProwJob that has invalid configuration and try to schedule another one.

**Please provide links to example occurrences, if any**:
Plank logs:
{"component":"plank","error":"error listing prow jobs: json: cannot unmarshal bool into Go struct field EnvVar.value of type string","level":"error","msg":"Error syncing.","time":"2019-10-29T09:33:59Z"}

**Anything else we need to know?**:
We are using quite an old Prow configuration however we plan to upgrade it soon.

**Comment by stevekuznetsov** [comment]
I'm not really sure what can be done here. Don't create ProwJobs that are invalid if possible -- using tools like `mkpj` makes that very difficult to do on accident.

At a high level we need to disallow those from being created and/or be more lenient on the client side. I believe newer k8s versions allow for more fully-fledged validation in the API server for CRDs, which will help. Not sure if we can change client behavior at all.

/cc @alvaroaleman @clarketm

**Comment by stevekuznetsov** [comment]
xref https://github.com/kubernetes/test-infra/issues/14925

**Comment by alvaroaleman** [comment]
@clarketm Have you checked if this is an issue with the generated cluentset we are currently using for Plank?

**Comment by kasiakepka** [comment]
Thanks! I see that we are the ones to blame, not `plank` .

**Comment by clarketm** [comment]
@alvaroaleman 
A fatal error still occurs with the generated client, albeit a different error message. 

**e.g.** 
```console
"error listing prow jobs: v1.ProwJobList.Items: []v1.ProwJob: v1.ProwJob.Spec: v1.ProwJobSpec.PodSpec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true}],"ima|..., bigger context ...|ww.google.com"],"env":[{"name":"EXAMPLE","value":true}],"image":"alpine","name":"","resources":{}}]}|..."
```

**Comment by clarketm** [comment]
Note: the scope of this issue to now minimized to service clusters as sync issues with *build* clusters will not longer cause a fatal sync crash. #15215

**Comment by cjwagner** [comment]
Dup of https://github.com/kubernetes/test-infra/issues/14925
/close
