### ISSUE TITLE
Override not allowed, even though username is listed in OWNERS

### ISSUE THREAD

**Issue by LorbusChris** [kubernetes/test-infra#15043]
**What happened**:
`@LorbusChris: LorbusChris unauthorized: /override is restricted to Repo administrators, approvers in top level OWNERS file.`

see https://github.com/openshift/machine-config-operator/pull/1220#issuecomment-548383786

**What you expected to happen**:
Prow let's me do the override 

**How to reproduce it (as minimally and precisely as possible)**:
In MCO repo, it's reproducible for my user on all PRs, another example: https://github.com/openshift/machine-config-operator/pull/1229#issuecomment-548364714

**Please provide links to example occurrences, if any**:
https://github.com/openshift/machine-config-operator/pull/1229#issuecomment-548364714
https://github.com/openshift/machine-config-operator/pull/1220#issuecomment-548383786

**Anything else we need to know?**:
Maybe it's casued by the upper case letters in my username?

**Comment by LorbusChris** [comment]
This is still an issue.

/remove-lifecycle stale

**Comment by BenTheElder** [comment]
/override works for me, with capitals in my username :-)

**Comment by BenTheElder** [comment]
it looks like you haven't been in owners since december? https://github.com/openshift/machine-config-operator/commit/9de14316ce7bb55290e1ed64a82507944637e413#diff-37ffc11190043a72e49391017a305d3a

**Comment by LorbusChris** [comment]
Note that the PRs I linked were on the `fcos` branch where I am still listed in the OWNERS file.
Other commands, e.g lgtm, work for me on that branch (but not `master` anymore obviously).

I'll try to override somewhere again shortly to verify this is still an issue.

**Comment by BenTheElder** [comment]
Appreciated, I've been using override intermittently on prow.k8s.io for some time including very recently without issue.

**Comment by LorbusChris** [comment]
@BenTheElder it's still not working for me: https://github.com/openshift/installer/pull/3563#issuecomment-625233729

(my username is present in OWNERS on that branch: https://github.com/openshift/installer/blob/fcos/OWNERS#L7)

**Comment by BenTheElder** [comment]
/area prow
cc @cjwagner @alvaroaleman

**Comment by alvaroaleman** [comment]
hm, I wonder if we do something wrong with the casing there? @petr-muller did you look into this one?

**Comment by petr-muller** [comment]
@alvaroaleman never got to this :( but casing is also what I suspected.

**Comment by alvaroaleman** [comment]
@LorbusChris are you able to `approve` on that branch? The override plugin is basically using the same code to get the owners as the approvers plugin, so this is somewhat surprising

**Comment by LorbusChris** [comment]
I haven't tried to approve anything explicitly lately, but `lgtm` definitely works and that has in my experience always led to the bot also applying `approve`, e.g. https://github.com/openshift/machine-config-operator/pull/1653

Should I try to explicitly do an `/approve`?

**Comment by LorbusChris** [comment]
`/approve` works for me as well: https://github.com/openshift/installer/pull/3572#issuecomment-626148905

**Comment by LorbusChris** [comment]
override still not works for me. (https://github.com/openshift/installer/pull/4054#issuecomment-674474673)
/remove-lifecycle stale

**Comment by BenTheElder** [comment]
Someone on the openshift side should look at the logs.
/uncc
