### ISSUE TITLE
1.17 jobs are using non-existent images.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#15045]
**What happened**:
This PR https://github.com/kubernetes/test-infra/pull/15023 bumped the release jobs and introduced the image `gcr.io/k8s-testimages/kubekins-e2e:v20191029-4802b07-1.17` to some of the job configs. This image doesn't appear to exist so jobs using it are getting stuck in the pod pending phase and eventually failing. Example image pull backoff error:
```
Failed to pull image "gcr.io/k8s-testimages/kubekins-e2e:v20191029-4802b07-1.17": rpc error: code = Unknown desc = failed to resolve image "gcr.io/k8s-testimages/kubekins-e2e:v20191029-4802b07-1.17": no available registry endpoint: gcr.io/k8s-testimages/kubekins-e2e:v20191029-4802b07-1.17 not found
```

**What you expected to happen**:
Either revert the PR or publish the image. I'd revert immediately, but I'm not sure if switching the release jobs back will cause problems. Please advise @Katharine @justaugustus 
/sig release

**Please provide links to example occurrences, if any**:
https://k8s-testgrid.appspot.com/sig-release-1.17-blocking#verify-1.17

**Comment by cjwagner** [comment]
Katharine advised that merging the daily bump PR should resolve this so I'm going to do that.

**Comment by justaugustus** [comment]
+1 to a bump instead of the revert!
ref Slack chat: https://kubernetes.slack.com/archives/C2C40FMNF/p1572538684094700

**Comment by cjwagner** [comment]
Bumping now: https://github.com/kubernetes/test-infra/pull/15030

**Comment by cjwagner** [comment]
I confirmed the new image tag exists.
