### ISSUE TITLE
New GCS bucket for ClusterAPI OpenStack conformance tests

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/test-infra#15081]
**What would you like to be added**:

I would like to have a new GCS bucket to store test results of conformance tests based on ClusterAPI OpenStack run in OpenLab (https://github.com/theopenlab/openlab-zuul-jobs).

**Why is this needed**:
See also: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/484

I read the instructions in [Contributing Test Results](https://github.com/kubernetes/test-infra/blob/master/docs/contributing-test-results.md). One of the first steps is to create a world-readable bucket, which I assume I don't have the rights to do. I also couldn't find any automation for this. In my understanding the flow is as follows:

* [x] designate point of contanct > sbueringer
* [ ] Create the bucket
* [ ] Run e2e tests & upload test results (would be done via OpenLab Zuul)
* [ ] Update `/kettle/buckets.yaml` and `/config/testgrids` via PR

A follow-up question would be how the service account is integrated into OpenLab Zuul.

**Comment by dims** [comment]
@sbueringer please see one of the recent PRs in kubernetes/k8s.io requesting a bucket. ( like https://github.com/kubernetes/k8s.io/pull/440 )

**Comment by sbueringer** [comment]
@dims this PR seems to add a staging bucket for provider-azure. We already have a bucket like this for "capi-openstack" which we are using for our images in GCR (if I understand it correctly). But the whole `ensure-staging-storage.sh` script seems to be only for staging buckets.

**Comment by dims** [comment]
@sbueringer guess then we need a new script similar to ensure-staging-storage.sh for the conformance results bucket?

**Comment by sbueringer** [comment]
@dims Not sure how all this works but here is a first try for a new script > https://github.com/kubernetes/k8s.io/pull/459

**Comment by dims** [comment]
@sbueringer that looks good! let's wait for folks to peek. i'll assign it

**Comment by sbueringer** [comment]
@thockin Is the script from here: https://github.com/kubernetes/k8s.io/pull/459 already actuated? 

I assume I should be able to see the project & bucket in Google Cloud?

**Comment by dims** [comment]
@sbueringer looks like all set ... i re-ran the script to confirm.

```
dims@dims-a01:~/go/src/k8s.io/k8s.io$ infra/gcp/ensure-conformance-storage.sh capi-openstack
Ensuring project exists: k8s-conform
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-conform/billingInfo
projectId: k8s-conform
Enabling the GCS API
Configuring conformance bucket for capi-openstack
Configuring bucket: gs://k8s-conform-capi-openstack
Ensuring the bucket exists and is world readable
Enabling Bucket Policy Only for gs://k8s-conform-capi-openstack...
No changes made to gs://k8s-conform-capi-openstack/
Ensuring the GCS bucket retention policy is set: k8s-conform
Setting Retention Policy on gs://k8s-conform-capi-openstack/...
Empowering GCS admins
Updated IAM policy for project [k8s-conform].
bindings:
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWeqXGP_x0=
version: 1
No changes made to gs://k8s-conform-capi-openstack/
No changes made to gs://k8s-conform-capi-openstack/
Empowering k8s-infra-conform-capi-openstack@kubernetes.io to GCS
No changes made to gs://k8s-conform-capi-openstack/
No changes made to gs://k8s-conform-capi-openstack/
Done
```

**Comment by dims** [comment]
i can see the bucket using https://console.cloud.google.com/storage/browser/k8s-conform-capi-openstack

thanks for making the changes needed @sbueringer 

/close

**Comment by sbueringer** [comment]
@dims Looks like they are accessing GCS in the cloud provider openstack acceptance test via a `key_json`. I guess they are doing it via a service account. Do you by any chance now how they created the service account or are there best practices?

**Comment by saschagrunert** [comment]
> @dims
> Looks like you're right I can see the bucket and write to it.
> 
> Looks like they are accessing GCS in the cloud provider openstack acceptance test via a `key_json`. I guess they are doing it via a service account. Do you by any chance now how they created the service account or are there best practices?

Do you find any solution to this? I'm basically facing the same problem right now :thinking:

**Comment by sbueringer** [comment]
@saschagrunert Nope, not yet :)

@dims *push* :)
