### ISSUE TITLE
[Question/Feature] Show skipped tests in test grid?

### ISSUE THREAD

**Issue by jlewi** [kubernetes/test-infra#15095]
Is it possible to show skipped tests in test grid? I currently have some tests that are expected to fail. They are reported as skipped in spyglass but don't show up in testgrid at all (i.e. there is no corresponding row).

Screenshots and other details in kubeflow/testing#517

I'm not sure if this is user error on my part or a limitation of testgrid.
Here's a sample junit file
https://storage.googleapis.com/kubernetes-jenkins/logs/kubeflow-periodic-master/1191448002699464704/artifacts/junit_kubeflow-periodic-master-kfctl-go-iap-4704-b6b0/junit_endpoint-is-ready-test-kfctl_gcp_iap.xml

```
<testsuite errors="0" failures="0" name="test_endpoint_is_ready_kfctl_gcp_iap" skips="1" tests="1" time="904.066">
<testcase classname="kfctl-go-iap" file="endpoint_ready_test.py" line="17" name="/kfctl-go-iap/test_endpoint_is_ready" time="902.8675365447998">
<skipped message="expected test failure"/>
</testcase>
</testsuite>
```

Ideally this expected failures would show up as a different color (orange?) to distinguish them from unexpected failures.

If the test passes I'd like to see that as a green or possibly some other color to indicate an unexpected pass

**Comment by michelle192837** [comment]
That's what I get for getting distracted in the middle of doing this!

There's some work to enable this in progress, I need to make a proto change then actually enable in production. After that's done, you'll just need to add a flag to your TestGrid config to opt in.

Are you okay copying this issue over to https://github.com/GoogleCloudPlatform/testgrid/issues?

**Comment by michelle192837** [comment]
/remove-lifecycle rotten

Last time I checked, this change will work when introduced, just need the time to do it and validate it works again.
