### ISSUE TITLE
Occasional ImagePullBackOff Errors when pulling large docker images

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#15102]
**What happened**:
Occasionally in jobs (e.g. [proxy-presubmit-release](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_proxy/2477/proxy-presubmit-release/109)) a ImagePullBackOff error occurs when pulling large images (~6 GB) from GCR (e.g. `gcr.io/istio-testing/prowbazel:0.5.14`).

```console
  Warning  Failed     48m (x2 over 48m)      kubelet, gke-prow-build-pool-290c2b15-wf0m  Error: ImagePullBackOff
  Normal   Pulling    47m (x3 over 54m)      kubelet, gke-prow-build-pool-290c2b15-wf0m  pulling image "gcr.io/istio-testing/prowbazel:0.5.14"
  Warning  Failed     45m (x3 over 51m)      kubelet, gke-prow-build-pool-290c2b15-wf0m  Failed to pull image "gcr.io/istio-testing/prowbazel:0.5.14": rpc error: code = Unknown desc = context canceled
  Warning  Failed     7m50s (x9 over 51m)    kubelet, gke-prow-build-pool-290c2b15-wf0m  Error: ErrImagePull
  Normal   BackOff    4m36s (x105 over 48m)  kubelet, gke-prow-build-pool-290c2b15-wf0m  Back-off pulling image "gcr.io/istio-testing/prowbazel:0.5.14"
```

**What you expected to happen**:
I expect an `ImagePullBackOff` error not to occur since the image is available and accessible (i.e. public).

**How to reproduce it (as minimally and precisely as possible)**:
1. Trigger a job with a large container image (~6 GB) (e.g. [proxy-presubmit-release](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_proxy/2477/proxy-presubmit-release/109))
2. Roughly *20%* of the time, the job will timeout as a result of an `ImagePullBackOff` (e.g. https://prow.istio.io/job-history/istio-prow/pr-logs/directory/proxy-presubmit-asan)

**Please provide links to example occurrences, if any**:
ref: kubernetes/kubernetes#59376

Slack convo: https://kubernetes.slack.com/archives/C7J9RP96G/p1572922607056000

**Comment by clarketm** [comment]
We reduced the container image size down to ~5.5 GB (while is still extremely large) and upgraded the GKE master and nodes to `1.13.11-gke.9` and interestingly the issue has stopped. If this resurfaces in the future then I will reopen.

**Comment by clarketm** [comment]
For **temporary** mitigation on specific nodes in a GKE cluster, I have been doing this:

```bash
read -r -d '' COMMAND <<EOF
sudo -u root sed -E -i '/--image-pull-progress-deadline/! s|(KUBELET_OPTS=")|\1--image-pull-progress-deadline=60m |' /etc/default/kubelet
sudo -u root systemctl restart kubelet
EOF

gcloud beta compute --project="$PROJECT" ssh --zone="$ZONE" "$NODE" --command="$COMMAND"
```

Of course, this will only apply to a specific node .

**Comment by fejta** [comment]
Have we seen this lately? Why can't we keep this closed?

**Comment by clarketm** [comment]
> Have we seen this lately? Why can't we keep this closed?

Yes, ~30% Istio/proxy jobs fail in this way until I updated the kubelet configuration in VMs manually as described above (or until the node was able to cache the image). While this is still a problem it is not a "k8s/test-infra" (or on-call) problem anymore.
