### ISSUE TITLE
Updateconfig plugin's ConfigFile and PluginFile options are ignored.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#15128]
**What happened**:
I noticed that these config fields don't appear to be respected anywhere anymore and should probably just be removed in favor of the more general configmap uploading mechanism that is actually respected.
https://github.com/kubernetes/test-infra/blob/b4d4c269cc70d558b4db7c0512c9d17f6ba0b304/prow/plugins/config.go#L437-L448

It looks like those fields are only referenced in one place to generate (potentially incorrect) plugin help information: https://github.com/kubernetes/test-infra/blob/b4d4c269cc70d558b4db7c0512c9d17f6ba0b304/prow/plugins/updateconfig/updateconfig.go#L50-L59

/help
/good-first-issue
/area prow/plugins

**Comment by mhamdisemah** [comment]
@cjwagner can i work in this issue ?

**Comment by cjwagner** [comment]
Of course!
/assign @mhamdisemah

**Comment by Divya063** [comment]
@mhamdisemah Are you still working on this?

**Comment by ChakshuGupta13** [comment]
> **What happened**:
> I noticed that these config fields don't appear to be respected anywhere anymore and should probably just be removed in favor of the more general configmap uploading mechanism that is actually respected.
> https://github.com/kubernetes/test-infra/blob/b4d4c269cc70d558b4db7c0512c9d17f6ba0b304/prow/plugins/config.go#L437-L448
> 
> It looks like those fields are only referenced in one place to generate (potentially incorrect) plugin help information:
> 
> https://github.com/kubernetes/test-infra/blob/b4d4c269cc70d558b4db7c0512c9d17f6ba0b304/prow/plugins/updateconfig/updateconfig.go#L50-L59
> 
> /help
> /good-first-issue
> /area prow/plugins

Hi @cjwagner 
I was just going through the issue and files related to it.

How is the following code is generating incorrect help information?
https://github.com/kubernetes/test-infra/blob/b4d4c269cc70d558b4db7c0512c9d17f6ba0b304/prow/plugins/updateconfig/updateconfig.go#L50-L59
If I removed the config fields, then how should I modify 'helpProvider'? Can elaborate a little bit more about your requirement?

**Comment by cjwagner** [comment]
> How is the following code is generating incorrect help information?

The help text it emits is not necessarily true. Those config fields are not used anywhere else so they could be set to anything and not have any effect on behavior. The actual source of truth appears to be the `ConfigUpdater.Maps` field.

> If I removed the config fields, then how should I modify 'helpProvider'?

You need to modify the `helpProvider` to properly describe the current configuration. So remove the misleading text about the config and plugin files and replace it with text that describes what the current configuration does.

For example, the help text to describe this Prow instance's `config_updater` config https://github.com/kubernetes/test-infra/blob/7e8cd997a5560c27f93d14ce0aa676873ca7484c/config/prow/plugins.yaml#L389-L403
would include something like:
> Files matching `label_sync/labels.yaml` are used to populate the `label-config` ConfigMap in the `test-pods` namespace.

for each of the entries.

**Comment by ChakshuGupta13** [comment]
> > How is the following code is generating incorrect help information?
> 
> The help text it emits is not necessarily true. Those config fields are not used anywhere else so they could be set to anything and not have any effect on behavior. The actual source of truth appears to be the `ConfigUpdater.Maps` field.
> 
> > If I removed the config fields, then how should I modify 'helpProvider'?
> 
> You need to modify the `helpProvider` to properly describe the current configuration. So remove the misleading text about the config and plugin files and replace it with text that describes what the current configuration does.
> 
> For example, the help text to describe this Prow instance's `config_updater` config
> 
> https://github.com/kubernetes/test-infra/blob/7e8cd997a5560c27f93d14ce0aa676873ca7484c/config/prow/plugins.yaml#L389-L403
> 
> 
> would include something like:
> > Files matching `label_sync/labels.yaml` are used to populate the `label-config` ConfigMap in the `test-pods` namespace.
> 
> for each of the entries.

Thanks @cjwagner 
For the explanation.
I have made some changes according to my understanding and sent a PR #16137
