### ISSUE TITLE
pull-kubernetes-integration master job using 1.14-level test image

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#15143]
**What happened**:
We switched the test images for kubernetes master to use go1.13.4 in https://github.com/kubernetes/test-infra/pull/15113

A corresponding change was made to require go1.13.4+ in integration tests in https://github.com/kubernetes/kubernetes/pull/82809

The resulting [presubmit pull-kubernetes-integration run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/82809/pull-kubernetes-integration/1191961293163073537/) failed with:
```
W1106 06:13:53.810] Status: Downloaded newer image for gcr.io/k8s-testimages/kubekins-test:1.14-v20190817-cc05229
W1106 06:13:59.884] + export PATH=/go/bin:/workspace/kubernetes/third_party/etcd:/usr/local/go/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
W1106 06:13:59.884] + PATH=/go/bin:/workspace/kubernetes/third_party/etcd:/usr/local/go/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
W1106 06:13:59.884] + go install k8s.io/kubernetes/vendor/gotest.tools/gotestsum
W1106 06:14:01.230] + export KUBE_RACE=-race
W1106 06:14:01.231] + KUBE_RACE=-race
W1106 06:14:01.231] + export KUBE_COVER=n
W1106 06:14:01.231] + KUBE_COVER=n
W1106 06:14:01.232] + export ARTIFACTS=/workspace/artifacts
W1106 06:14:01.232] + ARTIFACTS=/workspace/artifacts
W1106 06:14:01.232] + export KUBE_JUNIT_REPORT_DIR=/workspace/artifacts
W1106 06:14:01.232] + KUBE_JUNIT_REPORT_DIR=/workspace/artifacts
W1106 06:14:01.232] + export KUBE_KEEP_VERBOSE_TEST_OUTPUT=y
W1106 06:14:01.233] + KUBE_KEEP_VERBOSE_TEST_OUTPUT=y
W1106 06:14:01.233] + export KUBE_INTEGRATION_TEST_MAX_CONCURRENCY=4
W1106 06:14:01.233] + KUBE_INTEGRATION_TEST_MAX_CONCURRENCY=4
W1106 06:14:01.233] + export LOG_LEVEL=4
W1106 06:14:01.233] + LOG_LEVEL=4
W1106 06:14:01.234] + cd /go/src/k8s.io/kubernetes
W1106 06:14:01.234] + make generated_files
W1106 06:14:02.085] 
W1106 06:14:02.086] Detected go version: go version go1.12.9 linux/amd64.
W1106 06:14:02.086] Kubernetes requires go1.13.4 or greater.
W1106 06:14:02.086] Please install go1.13.4 or later.
```

**What you expected to happen**:

I expected the test images configured for master to be used by the integration jobs running against master.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

This may exist for other optional presubmits or post-submit jobs as well, this was just the one we observed the issue on.

/assign @BenTheElder

**Comment by BenTheElder** [comment]
Ideally we would get rid of kubekins-test going forward but apparently that never landed for integration. I eliminated it for the verify job previously. we have a prototype https://slack-redir.net/link?url=https%3A%2F%2Fprow.k8s.io%2Fview%2Fgcs%2Fkubernetes-jenkins%2Fpr-logs%2Fpull%2F46662%2Fpull-kubernetes-integration-podutil%2F1191963934244999168

some background: this is invoked via https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_verify.py which is a hold over from jenkins

**Comment by BenTheElder** [comment]
we're making some progress getting the podutils job running and eliminating kubekins-test from future versions of the integration job
/assign @liggitt 

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/82809/pull-kubernetes-integration-podutil/1192134279472091136

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/82809/pull-kubernetes-integration-podutil/1192134279472091136

it ran but did not pass.

the number of tests in the junit checks out versus https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84814/pull-kubernetes-integration/1192137425569189888/

**Comment by BenTheElder** [comment]
kubekins-test should be fully deprecated going forward after https://github.com/kubernetes/test-infra/pull/15144 (which is now in), we need to follow up with updating the ci periodics once the kubernetes go 1.13 PR lands and ensure that 1.17 will pick these up.

**Comment by spiffxp** [comment]
Is this still an issue?

**Comment by liggitt** [comment]
master was fixed in https://github.com/kubernetes/test-infra/pull/15144
1.17 was fixed in https://github.com/kubernetes/test-infra/pull/15156
1.16 was fixed in https://github.com/kubernetes/test-infra/pull/15637

This still applies for 1.15, afaik

**Comment by BenTheElder** [comment]
1.15 is on the way out. kubekins-test was eliminated.
