### ISSUE TITLE
Spyglass shows completed ProwJobs as running if finished.json is missing.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#15154]
**What happened**:
ProwJobs that fail to upload a `finished.json` file when they complete are incorrectly described as still running even though the ProwJob resource itself (you can view this with the `ProwJob YAML` button) indicates that the job has completed.
![Screenshot from 2019-11-06 15-15-50](https://user-images.githubusercontent.com/5334145/68346198-59d72880-00a8-11ea-9400-79a5f464e225.png)

**What you expected to happen**:
Spyglass' metadata lens should use (or fall back to) the ProwJob resource's start and completion times as the source of truth instead of using `started.json` and `finished.json` files.

**Anything else we need to know?**:
This obviously doesn't resolve the underlying problem of failing to upload `finished.json`, but it will improve the UX in the failure case and should allow basic metadata to be displayed for undecorated jobs so it seems worthwhile to me.

cc @Katharine @stevekuznetsov @fejta 
/help

**Comment by BenTheElder** [comment]
i wonder if maybe a prowjob finalizer in crier could ensure that finished.json exists for the case that the podutils failed to create one. that way we don't need deck changes AND it will work after the prowjob is GCed

**Comment by Katharine** [comment]
Depending on the prowjob resource doesn't work once the prowjob is cleaned up, and I don't think we want to increase the amount of weird special-case pulling-from-prow that spyglass does. I would prefer to see some prow component ensure that jobs always get useful information uploaded (as Ben suggests).

**Comment by Katharine** [comment]
/help cancel

Removing the label until we have consensus on how we want to handle this and because it's a more design-y question than I think we want to lump into the help wanted pile.
