### ISSUE TITLE
label_sync is failing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#15157]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-test-infra-label-sync/1192264870515445760

https://k8s-testgrid.appspot.com/sig-testing-misc#label_sync

from some of the logs
> {"component":"label_sync","file":"label_sync/main.go:358","func":"main.loadLabels.func1","level":"error","msg":"Failed listing labels for repo","org":"kubernetes-sigs","repo":"krew-ghsa-m9g4-7496-9p6f","time":"2019-11-07T01:18:11Z"}

> {"component":"label_sync","file":"label_sync/main.go:358","func":"main.loadLabels.func1","level":"error","msg":"Failed listing labels for repo","org":"kubernetes-sigs","repo":"krew-ghsa-m9g4-7496-9p6f","time":"2019-11-07T02:18:12Z"}

**Comment by BenTheElder** [comment]
cc @cjwagner @fejta 
this is a bit??
/are oncall-hotlist

**Comment by BenTheElder** [comment]
the live API results do not have this

https://api.github.com/orgs/kubernetes-sigs/repos
https://api.github.com/organizations/36015203/repos?page=2
https://api.github.com/organizations/36015203/repos?page=3

**Comment by BenTheElder** [comment]
@cblecker may know the root case. can't verify with the data I have access to naturally. API docs not surfacing anything helpful.

**Comment by cblecker** [comment]
/assign
Will look tomorrow

**Comment by BenTheElder** [comment]
I would be happy to write a fix for this given info about what differentiates this entry.
I can't see this entry on my account, but I could just login to k8s-ci-robot and check the API from that account.
