### ISSUE TITLE
Add configurable TTLs for completed ProwJob pods.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#15174]
Currently sinker exposes a `max_pod_age` field: https://github.com/kubernetes/test-infra/blob/0326e2563add4824108d877e5b2c9ce3eee594f2/prow/config/config.go#L474-L476

This field is kind of misleading and marginally useful. It is actually the maximum pod age for a completed ProwJob since we don't delete pods of running ProwJobs. This means that if `max_pod_age` is 30 mins and a job needs to run for 1 hour to complete, the pod __won't__ be garbage collected after 30 mins, but will be immediately garbage collected after 1 hour. If a job only needs to run for 5 mins it will complete and then won't be garbage collected for 25 more mins.
I don't think this is the behavior we really want since it makes our ability to debug a failed pod in the cluster dependent on the jobs duration.

Instead I think it would make more sense to have two configurable garbage collection grace periods that are measured from the pods completion time, not the start time. One for jobs that complete successfully and one for jobs that complete unsuccessfully (so that we can specify a longer GC grace period for failed pods).

/help 
cc @clarketm @stevekuznetsov @BenTheElder

**Comment by stevekuznetsov** [comment]
Do we want  a hard TTL at all? (Delete after N hours regardless of job state?)

**Comment by BenTheElder** [comment]
ideally we don't need to get pod logs from live pods, because that costs all of the disk space of the pod which is a major resource problem for us.

instead some component could record more things (eg the pod state before deletion)
