### ISSUE TITLE
Deck should warn about potentially risky reruns

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#15192]
Sometimes rerunning is unsafe for reasons that might surprise someone without the relevant context. This can lead to issues like #15165. We should add the ability to add risky-rerun flags to prowjobs, which the UI can then use before letting you perform a rerun.

/assign

**Comment by stevekuznetsov** [comment]
Perhaps -- this still won't help if someone accidentally or inadvertently changes the schedules. Using `boskos` to limit concurrency across many jobs by actually tying them together is a much more robust approach.

**Comment by Katharine** [comment]
The problem with that is that we don't want to limit concurrency; we want to run these jobs at exactly the specified time. Assorted assumptions exist around the jobs being run as scheduled, and interrupting that schedule is problematic. Limiting the cross-job concurrency would prevent the jobs from interfering, but would not solve the regularly scheduled job failing if an unexpected job was run before it.

There are also probably other jobs that should probably not be rerun (like the ones that publish code, perhaps). This is a useful thing to have either way.

**Comment by stevekuznetsov** [comment]
Could we opt these out of being able to be re-run?

**Comment by stevekuznetsov** [comment]
(instead of warning and letting someone override, just not allow it)

**Comment by Katharine** [comment]
We could, but I prefer letting a per-job explanation be shown. If we reject without explanation, a bunch of people have the ability to go do it anyway, and might do so given they don't know why the UI isn't letting them do it.

I trust everyone who has the button to do the right thing, provided they have enough information. This ensures everyone has enough information without unduly getting in their way.
