### ISSUE TITLE
Prow Hook component will not run in dryrun mode out of the box

### ISSUE THREAD

**Issue by Biwwie** [kubernetes/test-infra#15205]
**What happened**:
As a new developer, checking out master and running hook in dryrun mode will never work due to this change to error on client instantiation during hook startup
https://github.com/kubernetes/test-infra/pull/12024/files

**What you expected to happen**:
1) Hook dryrun mode should still run successfully
2) Any clients that are unable to run in dryrun should be mocked to behave correctly (read but no writes) in dryrun mode, see https://github.com/kubernetes/test-infra/blob/master/prow/flagutil/kubernetes_cluster_clients.go#L142

**How to reproduce it (as minimally and precisely as possible)**:
1) Clone Repo
2) Bazel run
`
bazel run //prow/cmd/hook -- --dry-run=true --deck-url=https://prow.k8s.io/ --port=8888 --config-path=/Users/billyngo/workspace/test-infra/config/prow/config.yaml --plugin-config=/Users/billyngo/workspace/test-infra/config/prow/plugins.yaml --hmac-secret-file=/Users/billyngo/workspace/secret --github-token-path=/Users/billyngo/workspace/secret3
`

**Please provide links to example occurrences, if any**:
Errors will occur for all the clients with the dryrun error check and output a similar error message
`
{"component":"hook","error":"no dry-run kubernetes client is supported in dry-run mode","file":"prow/cmd/hook/main.go:167","func":"main.main","level":"fatal","msg":"Error getting Kubernetes client for infrastructure cluster.","time":"2019-11-08T13:38:24-08:00"}
`

**Anything else we need to know?**:
Currently unable to run hook in dryrun mode unless local changes are made

**Comment by cjwagner** [comment]
Similarly `config-bootstrapper`'s dry-run mode is broken. The config-boostrapper has no use for a deck-url so it should not be a flag, yet alone a required one. This probably applies to most of our components. 
```
{"component":"config-bootstrapper","error":"a dry-run was requested but required flag -deck-url was unset","file":"prow/cmd/config-bootstrapper/main.go:83","func":"main.main","level":"fatal","msg":"Invalid options","time":"2019-12-06T01:00:50Z"}
```
