### ISSUE TITLE
Prow: Should branchcleaner be configurable not to clean certain branches?

### ISSUE THREAD

**Issue by hvaara** [kubernetes/test-infra#15224]
**What would you like to be added**:
I'd like to know if anyone thinks it's valuable to implement a configuration option in `branchcleaner` to leave certain branches. It' possible to use `branchprotector` to achieve similar behavior, so I wanted to get some feedback on this. If anyone thinks it's valuable I'd be interested in working on this.

**Why is this needed**:
`branchcleaner` might clean a branch that you want to have in your repo for various reasons.

/area prow

**Comment by Colstuwjx** [comment]
Hi @hvaara I do have this requirement. Think about the following scenario:

1. we're using gitlab-flow to manage development flow, and we have two branches `master` and `release`;
2. developers check out a new branch from the master branch, and implement some features and take PR to merge into master;
3. while the PR get merged, it would trigger a CD to staging environment, which is using the master branch code to deploy;
4. after QA confirmed it's ok to release to prod, we take another PR from `master -> release`, and that PR would carry a group of features and bug fixes which were already merged into master branch.

As you could see, if we enable branchcleaner plugin for the whole repo,  after the PR which is from master to release get merged, the prow bot would also delete the merged branch. It's definitely not expected result!!!

As a result, I hope the prow bot could support this scenario, allows to protect the master branch.
Thanks.

**Comment by Colstuwjx** [comment]
Since this issue has been closed, I'd like to file a new issue #23732, let's talk in new place.

**Comment by hvaara** [comment]
Kudos for picking up where I left off in #23732 and #23735, @Colstuwjx!
