### ISSUE TITLE
k8s-bot should skip the issues started with "WIP"

### ISSUE THREAD

**Issue by k82cn** [kubernetes/test-infra#1522]
According to the PR at https://github.com/kubernetes/community/pull/208 , the issues started with "WIP" are not ready for review or test; so for `k8s-bot`, it should skip those issues.

**Comment by spxtr** [comment]
Related to #500

**Comment by spxtr** [comment]
I'm actually not sure that it's a good idea to automatically skip testing for issues with "WIP" in the title. Often I put WIP in the title while I'm trying to get tests to pass!

**Comment by k82cn** [comment]
is there anyway for contributor to setup CI based on their own repo? So they can work on their forked repo, and create a PR when all test passed in their CI. that will also reduce email from k8s-bot :).

**Comment by krzyzacy** [comment]
setup CI sounds like a waste of resource, it might be easier that contributor run `bootstrap.py` locally with target test jobs and arguments and let it pass first?
