### ISSUE TITLE
invalid extra refs not caught in presubmit

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#15237]
**What happened**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeadm/1901/pull-kubeadm-kinder-upgrade-master/1194273587414962176

failed without any status / logs visible to the user.

tracked to https://prow.k8s.io/prowjob?prowjob=d1e91a78-055f-11ea-b1b3-9af1c2bbbc45 => this log in the build cluster:

```
[
 {
   "insertId": "134nphpfoc0y4h",
   "jsonPayload": {
     "func": "main.main",
     "component": "clonerefs",
     "msg": "Invalid options: sync config for kubernetes/kubeadm provided more than once",
     "level": "fatal",
     "file": "prow/cmd/clonerefs/main.go:36"
   },
   "resource": {
     "type": "container",
     "labels": {
       "zone": "us-central1-f",
       "pod_id": "d1e91a78-055f-11ea-b1b3-9af1c2bbbc45",
       "project_id": "k8s-prow-builds",
       "cluster_name": "prow",
       "container_name": "clonerefs",
       "namespace_id": "test-pods",
       "instance_id": "3591119778702311617"
     }
   },
   "timestamp": "2019-11-12T15:19:47Z",
   "severity": "ERROR",
   "labels": {
     "compute.googleapis.com/resource_name": "gke-prow-ssd-pool-1a225945-t5v8",
     "container.googleapis.com/pod_name": "d1e91a78-055f-11ea-b1b3-9af1c2bbbc45",
     "container.googleapis.com/stream": "stderr",
     "container.googleapis.com/namespace_name": "test-pods"
   },
   "logName": "projects/k8s-prow-builds/logs/clonerefs",
   "receiveTimestamp": "2019-11-12T15:20:25.391465027Z"
 }
]
```

to extra refs on the job:
https://github.com/kubernetes/test-infra/blob/6345d435b67643d1bcf6b0ebd641d4a8ca207630/config/jobs/kubernetes/kubeadm/kubeadm-presubmits.yaml#L33

We should not allow checking in invalid presubmit configs like this.

**What you expected to happen**:

test-infra presubmits should catch this invalid config.

**How to reproduce it (as minimally and precisely as possible)**:

write a prowjob for a repo that also clones the repo as an extra ref

**Please provide links to example occurrences, if any**:

https://github.com/kubernetes/test-infra/blob/6345d435b67643d1bcf6b0ebd641d4a8ca207630/config/jobs/kubernetes/kubeadm/kubeadm-presubmits.yaml#L33

**Anything else we need to know?**:

cc @neolit123 @cjwagner @stevekuznetsov

**Comment by stevekuznetsov** [comment]
This should be caught by `checkconfig`

**Comment by BenTheElder** [comment]
Is test-infra running this? I don't think this PR bypassed presubmits.

**Comment by stevekuznetsov** [comment]
Err sorry, that was not clear -- to fix this bug, the check should be added to `checkconfig`. I am surprised it does not already check for this in config loading validation.

**Comment by stevekuznetsov** [comment]
Yeah, looks like it's a runtime only check. Plumbing it through job validation looks messy but should be possible.

**Comment by BenTheElder** [comment]
ACK

**Comment by jingxu97** [comment]
I had a PR with extra refs in presubmit got merged without being caught.
