### ISSUE TITLE
can not ask k8s-bot to test although be added to whitelist

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/test-infra#1524]

**Comment by ixdy** [comment]
@NickrenREN can you please link to the PR where it's not working?

**Comment by NickrenREN** [comment]
@ixdy  thanks for reply
I can not ask k8s-bot to test
https://github.com/kubernetes/kubernetes/pull/39463
and my PR is not auto-tested either
https://github.com/kubernetes/kubernetes/pull/39514

**Comment by ixdy** [comment]
I don't think that a separate whitelist exists anymore; you just have to be a member of the org. @spxtr to confirm.
