### ISSUE TITLE
Prow issue: question about k8s-ci-robot

### ISSUE THREAD

**Issue by cbf123** [kubernetes/test-infra#15243]
Hi,

I'm trying to understand what I need to do in order to get rid of the "GitHub didn't allow me to request PR reviews from the following users" behaviour, as visible at https://github.com/kubernetes/kubernetes/pull/85133

I got a message in my email from notifications@github.com corresponding to the "/cc @cbf123" message.

I'm not a kubernetes member at present (I didn't think I had contributed enough yet to get two sponsors) but I've been reviewing and testing patches in a specific area.

Can you give me instructions on what I can do to ensure that I can be pinged to review PRs?

thanks!

**Comment by spiffxp** [comment]
/close
as this isn't a test-infra issue

You'll need to become a kubernetes org member to be assignable https://github.com/kubernetes/community/blob/master/community-membership.md#member
