### ISSUE TITLE
tide hits "description is too long" when updating its status

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/test-infra#15250]
**What happened**:

We're seeing log errors like these after today's Prow bump:

```
"status code 422 not one of [201], body:
{
   "message":"Validation Failed",
   "errors":[
      {
         "resource":"Status",
         "code":"custom",
         "field":"description",
         "message":"description is too long (maximum is 140 characters)"
      }
   ],
   "documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"
}
```

The actual call is logged like this:

```
CreateStatus(openshift, origin, 174f695392dabad6e653c39565ae328a7d86a8f3, {pending https://prow.svc.ci.openshift.org/pr?query=is%3Apr+repo%3Aopenshift%2Forigin+author%3Amfojtik+head%3Abump-library-go-observer Not mergeable. Waiting for retest of Jobs [ci/prow/images ci/prow/unit ci/prow/verify ci/prow/e2e-aws-serial ci/prow/e2e-cmd ci/prow/e2e-gcp ci/prow/e2e-gcp-upgrade] tide})
```

Where the description is:

```
Not mergeable. Waiting for retest of Jobs [ci/prow/images ci/prow/unit ci/prow/verify ci/prow/e2e-aws-serial ci/prow/e2e-cmd ci/prow/e2e-gcp ci/prow/e2e-gcp-upgrade]
```

Which is 165 characters. Looks like https://github.com/kubernetes/test-infra/pull/15078 is causing this and Tide will need to ellipsize the description when it is too long because we have too many test (or contexts too long).

/assign

**Comment by stevekuznetsov** [comment]
We already have an ellipsizing(???) Utility somewhere in tide, I think.

**Comment by alvaroaleman** [comment]
/assign cancel
@petr-muller I was thinking it would probably make sense to add a check in the github client for this case and make it cut and emit a debug-level log message?

**Comment by stevekuznetsov** [comment]
@alvaroaleman we should revert the PR so that we can deploy `tide` at HEAD without errors while we figure out a fix

**Comment by petr-muller** [comment]
#15258 is intentionally quite simple to be able to merge quickly, it can be made smarter as a followup.
