### ISSUE TITLE
Testgrid `windows-gce-serial` tests failed on cluster creation for long time

### ISSUE THREAD

**Issue by YangLu1031** [kubernetes/test-infra#15267]
**What happened**:
`windows-gce-serial` tests failed on cluster creation.
https://testgrid.k8s.io/google-windows#windows-gce-serial&width=20

**What you expected to happen**:
Cluster is up and run serial tests

**How to reproduce it (as minimally and precisely as possible)**:
https://testgrid.k8s.io/google-windows#windows-gce-serial&width=20

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-serial/1194717550349389827

**Anything else we need to know?**:
We are from `sig-windows` team needing this test result. Please let us know if anything we can do to fix it.

**Comment by BenTheElder** [comment]
Hi, do you have any reason to suspect this is a test-infra bug?
Otherwise, this should probably be in the kubernetes repo, filed against sig-windows?

**Comment by YangLu1031** [comment]
@BenTheElder Hi Ben, as I found `gce-windows-master` used the same k8s repo(`v1.18.0-alpha.0.670+dff236e3b29cda`) as `windows-gce-serial`, but it was up and running fine. 
logs:
Started: [gce-windows-master](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/1194226648531079170)
Not started: [windows-gce-serial](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-serial/1194232435919818753)

**Comment by pjh** [comment]
Failing -serial build-log:
```
Waiting up to 300 seconds for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This may time out if there was some uncaught error during start up.

...........................................[0;31mCluster failed to initialize within 300 seconds.[0m
Last output from querying API server follows:
-----------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (28) Connection timed out after 5000 milliseconds
```

Successful -master build-log:
```
Waiting up to 300 seconds for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This may time out if there was some uncaught error during start up.

............Kubernetes cluster created.
<trim>
[0;32mKubernetes cluster is running.  The master is running at:
[0;33m  https://35.230.82.16
[0;32mThe user name and password to use is located in /workspace/.kube/config.[0m
... calling validate-cluster
```

I don't know who is trying to curl, what they're trying to fetch and why it's failing.

**Comment by pjh** [comment]
I'm guessing that something is going wrong while initializing the master but I'm not sure what. I also have no idea why the master would be failing in the -serial job but not in our other jobs; I reviewed [windows-gce.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-windows/windows-gce.yaml) and I don't see any notable differences for the serial job.

Comparing the master artifacts from a [serial run](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-serial/1194717550349389827/artifacts/e2e-996a9f2e73-3ca4d-master/) vs a [working run](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/1194987758444089345/artifacts/e2e-657b18c10a-36623-master/), I see failures in a bunch of the files. For example in kube-master-installation.log I see:

```
Nov 13 20:48:35.142437 e2e-996a9f2e73-3ca4d-master configure.sh[748]: mv: cannot stat '/home/kubernetes/kubernetes/LICENSE': No such file or directory
Nov 13 20:48:35.142995 e2e-996a9f2e73-3ca4d-master systemd[1]: kube-master-installation.service: Main process exited, code=exited, status=1/FAILURE
Nov 13 20:48:35.143140 e2e-996a9f2e73-3ca4d-master systemd[1]: kube-master-installation.service: Failed with result 'exit-code'.
Nov 13 20:48:35.143708 e2e-996a9f2e73-3ca4d-master systemd[1]: Failed to start Download and install k8s binaries and configurations.
```

I'm not sure if this sheds any light on the cause or if it's a symptom of some failure much earlier. @yliaog @BenTheElder any ideas why the master might be failing only in this job?

**Comment by yliaog** [comment]
the serial test never succeeded in the job history, all the way back to Aug 16.

**Comment by yliaog** [comment]
cluster master brought up, three Windows nodes brought up, two other Linux nodes failed to be brough up

=================================================
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-serial/1194899427391705089/build-log.txt
Created [https://www.googleapis.com/compute/v1/projects/kubernetes-ingress/zones/us-west1-b/instanceGroupManagers/e2e-74560af593-3ca4d-minion-group].
NAME                               LOCATION    SCOPE  BASE_INSTANCE_NAME                 SIZE  TARGET_SIZE  INSTANCE_TEMPLATE                     AUTOSCALED
e2e-74560af593-3ca4d-minion-group  us-west1-b  zone   e2e-74560af593-3ca4d-minion-group  0     2            e2e-74560af593-3ca4d-minion-template  no
ERROR: (gcloud.compute.instance-groups.managed.wait-until-stable) Timeout while waiting for group to become stable.
able, current operations: creating: 2
Detected 4 ready nodes, found 4 nodes out of expected 6. Your cluster may not be fully functional.[0m
NAME                                           STATUS                     ROLES    AGE   VERSION
e2e-74560af593-3ca4d-master                    Ready,SchedulingDisabled   <none>   54m   v1.18.0-alpha.0.897+5dd641e45cc299
e2e-74560af593-3ca4d-windows-node-group-0h9f   Ready                      <none>   50m   v1.18.0-alpha.0.897+5dd641e45cc299
e2e-74560af593-3ca4d-windows-node-group-bhrq   Ready                      <none>   50m   v1.18.0-alpha.0.897+5dd641e45cc299
e2e-74560af593-3ca4d-windows-node-group-tc45   Ready                      <none>   50m   v1.18.0-alpha.0.897+5dd641e45cc299

**Comment by yliaog** [comment]
actually when i looked at more test runs, it turns out many test runs are good, i.e. the cluster has been created successfully, and tests are run on the cluster, and many of the tests have PASSED, e.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-serial/1195020730232737792

the problem is it is not *shown* the same way as other CI test results for some reason.
==========================================
For other CI test result like below (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/1194987758444089345), it shows:
JUnit
15/4828 tests failed
246/4828 tests passed
4567/4828 tests skipped
Build log
==================================
For the serial test, it shows only Build log section, no JUnit x/y tests failed/passed/skipped section.

@BenTheElder what could have caused this?

**Comment by BenTheElder** [comment]
https://testgrid.k8s.io/google-windows#windows-gce-serial&width=20 != https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/1194987758444089345

windows-gce-serial on testgrid goes to this prowjob https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-serial/1194899427391705089

there are no junit results being uploaded from the tests there https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-serial/1194899427391705089/artifacts/, just the one from kubetest (`junit_runner.xml`)

**Comment by BenTheElder** [comment]
files need to wind up in $ARTIFACTS to be uploaded.

**Comment by BenTheElder** [comment]
I would guess that the script in `      - --test-cmd=$GOPATH/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh` does not do this.

**Comment by yliaog** [comment]
Normally, here are the steps 1) finish run-e2e.sh 2) dump logs. In the serial case, the run-e2e.sh is not finished, and timed out, and forcefully shutdown. hence no logs.

below are the raw logs from a normal run:
==============================================================
2019/11/15 14:59:02 process.go:155: Step '/home/prow/go/src/k8s.io/gce-k8s-windows-testing/run-e2e.sh --ginkgo.focus=\[Conformance\]|\[NodeConformance\]|\[sig-windows\] --ginkgo.skip=\[LinuxOnly\]|\[Serial\]|\[Feature:.+\] --minStartupPods=8 --node-os-distro=windows' finished in 1h5m47.384677776s
2019/11/15 14:59:02 e2e.go:534: Dumping logs locally to: /logs/artifacts
2019/11/15 14:59:02 process.go:153: Running: ./cluster/log-dump/log-dump.sh /logs/artifacts
................................
2019/11/15 15:01:03 process.go:155: Step './cluster/log-dump/log-dump.sh /logs/artifacts' finished in 2m0.740182202s

**Comment by yliaog** [comment]
so the fix is to increase the timeout for the serial test

**Comment by BenTheElder** [comment]
I don't think that's the fix, the junit results should be written even on timeout normally.

run-e2e.sh should be configuring the result to go to $ARTIFACTS

**Comment by yliaog** [comment]
I compared the serial job YAML and non-serial job YAML, they are both using run-e2e.sh, the diff is simply the - --ginkgo-parallel=, which is 1 for serial case, and 8 for non-serial case. the other is timeout, 4h or serial case, and 2h or non-serial case.

**Comment by BenTheElder** [comment]
they're both probably wrong then, I'm fairly certain we don't have this
issue with timeouts in jobs that run e2e without this script

**Comment by yliaog** [comment]
https://testgrid.k8s.io/google-windows#windows-gce-serial shows results now

it timeouts after 4h, so still need to increase that timeout
