### ISSUE TITLE
Prow issue: CLA Signature Confirmation How-to is Very Vague

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#1527]
If the bot is looking for a comment that has text "I signed it!" and literally that text, nothing else, please be clear that this is necessary. I had a comment with that text and some other text, and it was not valid.

See: https://github.com/kubernetes/kubernetes/pull/39496

**Comment by spxtr** [comment]
@foxish

**Comment by foxish** [comment]
The bot is actually not looking for any text. It just needs a new comment to be posted, which is literally anything, in order to refresh status. The reason it didn't work at first may be that at the CNCF, the signing of the CLA had not yet propagated completely. I'll have them investigate this.

**Comment by stevekuznetsov** [comment]
I see.

**Comment by foxish** [comment]
/close

The text says:
> Once you've signed, please reply here (e.g. "I signed it!") and we'll verify. Thanks
It seems clear to me that the user can reply with anything really. The issue that @stevekuznetsov saw was because of latency and not because we do an exact text match.

**Comment by fejta** [comment]
Update the comment to note that that the system is eventually consistent and to wait N minutes between signing and commenting?

https://github.com/kubernetes/test-infra/blob/master/prow/plugins/cla/cla.go#L39

@stevekuznetsov would you be able/willing to send a PR to that effect? If not please /assign @fejta this issue to me.

**Comment by stevekuznetsov** [comment]
Sure, I can take a shot at it.

**Comment by stevekuznetsov** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/2423
