### ISSUE TITLE
Warn if PR has kind/deprecation label but no release note

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#15293]
Ref: https://github.com/kubernetes/test-infra/pull/15040#issuecomment-549438873

https://github.com/kubernetes/test-infra/pull/15040 adds the `kind/deprecation` label. We should also make sure that the bot warns if a PR has the `kind/deprecation` label but no release note. We could, perhaps, enforce this warning by removing the `kind/deprecation` label automatically with a comment if there is no release note.

/area prow
/sig contributor-experience

/cc @cblecker @justaugustus @jberkus @tpepper

**Comment by justaugustus** [comment]
@nikhita -- Thanks for opening this!
What about instead enforcing the release note with a `do-not-merge*` or `needs-*` label instead of dropping the `kind/deprecation` label in this instance?

**Comment by nikhita** [comment]
> What about instead enforcing the release note with a do-not-merge* or needs-* label instead of dropping the kind/deprecation label in this instance?

Lgtm.

**Comment by cblecker** [comment]
Talking to @nikhita, here's a new plan for this:
If the PR has `kind/deprecation` AND has `release-note-none`, then that is an invalid combination. We should then drop `release-note-none` and add `do-not-merge/release-note-needed`, and add a note to the PR of why we did this.

/help
