### ISSUE TITLE
TestGrid is not actually ignoring skipped statuses by default

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#15294]
Whee, faulty assumptions!

Recent change to TestGrid added opt-in skip statuses, except that skips weren't actually ignored by default. I added that change to default.yaml thinking it would apply, and forgot about another couple changes that would need to apply for this to actually go into effect.

Working on those, and will probably regenerate most if not all test groups to clean up TestGrid results.

**Comment by fejta** [comment]
/close
Resolved, thanks Michelle
