### ISSUE TITLE
Outage with Velodrome/boskos logs

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#15303]
**What happened**:
The Velodrome boskos dashboard is returning no data with the following response (in the red ! in the top-left):
```
504 Gateway Time-out

504 Gateway Time-out
nginx/1.10.1
```

**What you expected to happen**:
Data

**How to reproduce it (as minimally and precisely as possible)**:
Currently, visit [the dashboard](http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1&from=now-24h&to=now). I have confirmed the error is reproducible with different people.

**Please provide links to example occurrences, if any**:
http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1&from=now-24h&to=now

/kind oncall-hotlist

**Comment by chases2** [comment]
![image](https://user-images.githubusercontent.com/1386266/69173167-1622ec80-0ab4-11ea-8cf2-a72de786559f.png)

**Comment by cjwagner** [comment]
Boskos metrics are now at https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1
