### ISSUE TITLE
checkconfig returns error for valid config

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#15316]
**What happened**:
`checkconfig` returns an error for a valid config. More specifically, `checkUnknownFields(..)` returns *unknown* fields that are, in fact, *known*.
 
https://github.com/kubernetes/test-infra/blob/c730fab62edb4442547269b17e314b6dd861e925/prow/cmd/checkconfig/main.go#L402-L431

**What you expected to happen**:
A valid, functional configuration should be considered valid by `checkconfig`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a legacy [`slack_reporter`](https://github.com/istio/test-infra/blob/104369d76e8affc99f793cb6315f046ac22a2e7f/prow/config.yaml#L61-L71) field to your Prow configuration.
2. Run `checkconfig` with `--strict` and/or `--warnings=unknown-fields` warning enabled.

**Please provide links to example occurrences, if any**:
[example](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_test-infra/2102/pull-test-infra-prow-checkconfig/3124/build-log.txt)

**Comment by clarketm** [comment]
> Are you sure you're using an appropriate version of `checkconfig`? If the struct can be set, it should never have that issue so it makes me think you are using an old version of `checkconfig`.

We are using [`v20191115-8d288a842`](https://github.com/istio/test-infra/blob/104369d76e8affc99f793cb6315f046ac22a2e7f/prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml#L11).

It is worth mentioning that this same error occurs while running `checkconfig` locally against HEAD of `master` (i.e. 0c33278c38b087b40703cf3b059a4e288957a2ed).

```consle
$ bazel run //prow/cmd/checkconfig -- --config-path=/Users/clarketm/SourceCode/istio_test-infra/prow/config.yaml --strict --warnings=unknown-fields
```
```console
{"component":"checkconfig","file":"prow/config/config.go:1237","func":"k8s.io/test-infra/prow/config.parseProwConfig","level":"warning","msg":"The `plank.allow_cancellations` setting is deprecated. It will be removed and set to always true in March 2020","time":"2019-11-17T13:19:37-08:00"}
{"component":"checkconfig","file":"prow/config/config.go:1049","func":"k8s.io/test-infra/prow/config.(*Config).validateComponentConfig","level":"warning","msg":"slack_reporter will be deprecated on May 2020, and it will be replaced with slack_reporter_configs['*'].","time":"2019-11-17T13:19:37-08:00"}
{"component":"checkconfig","file":"prow/cmd/checkconfig/main.go:76","func":"main.reportWarning","level":"warning","msg":"unknown fields present in /Users/clarketm/SourceCode/istio_test-infra/prow/config.yaml: slack_reporter.channel, slack_reporter.job_states_to_report, slack_reporter.job_types_to_report, slack_reporter.report_template","time":"2019-11-17T13:19:37-08:00"}
{"component":"checkconfig","file":"prow/cmd/checkconfig/main.go:79","func":"main.reportWarning","level":"fatal","msg":"Strict is set and there were warnings","time":"2019-11-17T13:19:37-08:00"}
```

#### Links
- [Istio prow config](https://github.com/istio/test-infra/blob/104369d76e8affc99f793cb6315f046ac22a2e7f/prow/config.yaml#L61-L71)

**Comment by stevekuznetsov** [comment]
Copying over from that thread ... 

That is totally bizarre. I think we should reconsider the bespoke reflection-based code we have in there to check for bad fields. I don't think that it is worth the effort to maintain it over strict YAML loading as allowed by the library. The only reason I remember being given for the code as-is, was that the library only told you about one unknown field at once. At least it is more robust, I would expect. This code keeps biting us and I don't think it's given us much value...

@cjwagner @fejta

**Comment by afirth** [comment]
warns about `org:` too (peribolos)
```
docker run -it -v /home/afirth/git/github-automation:/tmp gcr.io/k8s-prow/checkconfig \
--plugin-config=/tmp/plugins.yaml \
--config-path=/tmp/config.yaml
{"component":"checkconfig","file":"prow/cmd/checkconfig/main.go:76","func":"main.reportWarning","level":"warning","msg":"unknown fields present in /tmp/config.yaml: orgs","time":"2020-01-15T14:20:29Z"}
```

**Comment by stevekuznetsov** [comment]
On Slack consensus was reached to remove the reflection-based validation and just to use the strict YAML loading -- @afirth do you want to take a stab at that?

**Comment by afirth** [comment]
> On Slack consensus was reached to remove the reflection-based validation and just to use the strict YAML loading -- @afirth do you want to take a stab at that?

Sure. Do we need a flag to leave the old unstrict behaviour? Looks pretty straightforward to rip out all the unknown field stuff, just not sure how others are using this

**Comment by afirth** [comment]
> On Slack consensus was reached to remove the reflection-based validation and just to use the strict YAML loading -- @afirth do you want to take a stab at that?

Sure. Do we need a flag to leave the old unstrict behaviour? Looks pretty straightforward to rip out all the unknown field stuff, just not sure how others are using this
