### ISSUE TITLE
Jenkins Verification build failed

### ISSUE THREAD

**Issue by NickrenREN** [kubernetes/test-infra#1538]
Verification build failed, and errors info as below:

I0107 14:16:02.801] Makefile:119: recipe for target 'verify' failed
W0107 14:16:02.901] make: *** [verify] Error 1
W0107 14:16:05.565] Traceback (most recent call last):
W0107 14:16:05.565]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 101, in <module>
W0107 14:16:05.566]     main(ARGS.branch, ARGS.script, ARGS.force)
W0107 14:16:05.566]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 85, in main
W0107 14:16:05.566]     'bash', '-c', 'cd kubernetes && %s' % script,
W0107 14:16:05.566]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 45, in check
W0107 14:16:05.566]     subprocess.check_call(cmd)
W0107 14:16:05.566]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0107 14:16:05.566]     raise CalledProcessError(retcode, cmd)
W0107 14:16:05.567] subprocess.CalledProcessError: Command '('docker', 'run', '--rm=true', '--privileged=true', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-verify/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-verify/go/src/k8s.io/kubernetes/_artifacts:/workspace/artifacts', '-e', 'KUBE_FORCE_VERIFY_CHECKS=n', '-e', 'KUBE_VERIFY_GIT_BRANCH=master', '-e', 'REPO_DIR=/var/lib/jenkins/workspace/pull-kubernetes-verify/go/src/k8s.io/kubernetes', 'gcr.io/k8s-testimages/kubekins-test:1.6-v20161205-ad918bc', 'bash', '-c', 'cd kubernetes && ./hack/jenkins/verify-dockerized.sh')' returned non-zero exit status 2
E0107 14:16:05.572] Build failed
I0107 14:16:05.572] process 32159 exited with code 1 after 21.0m
E0107 14:16:05.572] FAIL: pull-kubernetes-verify

I have no idea about the errs. Thanks

**Comment by ixdy** [comment]
@NickrenREN yeah, there is a lot of junk in that stacktrace, most of which is irrelevant to developers.

The actual error should've been printed before this stacktrace in the log.
