### ISSUE TITLE
prow: all components think their name is "image"

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#15385]
As of https://github.com/kubernetes/test-infra/pull/15320 all components think their name is `"image"` as that's what every component tells `prow_image` it is called:

https://github.com/kubernetes/test-infra/blob/c5d343529cab6e28abfeed56d1bd4839e442e597/prow/def.bzl#L28

Why does this happen today? Why is every image called `"image"`? How do application binaries inside of the container get their `$foo-app.binary` names?

/cc @cjwagner @fejta

**Comment by alvaroaleman** [comment]
This was fixed in https://github.com/kubernetes/test-infra/pull/16776
/close
