### ISSUE TITLE
Deck: configurable rerun auth

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#15415]
**What would you like to be added / Why is this needed**:

Today, the `deck` config supports only a  *single* `rerun_auth_config` - one that applies to *all* orgs and repos associated with a particular instance (including `hidden_repos` configured for any *private* deck instances). While the `rerun_auth_config` config can be *overridden* at the job-level, this is a major inconvenience to keep in-sync and scale as the quantity of jobs grow. 

Similar to what was done for [`slack_reporter`](https://github.com/kubernetes/test-infra/pull/15159), I propose a map-based configuration field (e.g. `rerun_auth_configs` - note the "s" suffix). The keys will be one of: `org`, `org/repo`, or `*` (wildcard) and the corresponding value will be a [`RerunAuthConfig`](https://github.com/kubernetes/test-infra/blob/93c6c43b21f60e4ff2f7955f6fd7660d2290c6bb/prow/config/config.go#L556) struct instance. I have found this pattern quite flexible and rather appealing to the general Prow user.

> **Note:** I do not see this as a *substitute* for https://github.com/kubernetes/test-infra/issues/15194 but rather as a *flexible*, *independent* compliment - opening up the robust feature of "configurable rerun" to *any* user, regardless of whether they use OWNERS files or not (e.g. Istio).

cc @stevekuznetsov @cjwagner 

Before implementing this solution, I would like to gauge if there are any caveats or alternatives we should consider first? This idea spawned from the feedback on: #15396

/help

**Comment by cjwagner** [comment]
Sounds reasonable to me. OWNERS files would be great to use as the source of truth, but that is a bit tricky to implement, and more importantly, not every Prow instance uses OWNERS files to control job config changes. So even if we do end up using OWNERS files for rerun auth we will still want a mechanism like this.
cc @Katharine for thoughts as well

**Comment by stevekuznetsov** [comment]
Agreed with Cole here. As written your proposal sounds awesome. +1 from me

**Comment by clarketm** [comment]
/remove-lifecycle stale

I will continue working on this soon.
