### ISSUE TITLE
Trigger job on branch deletion and/or pr termination ?

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/test-infra#15421]
Is it possible to trigger a job when a branch is deleted or a pull request is terminated (closed or merged) ?

That would be useful to cleanup resources that could have been created while the pull request was live. 

I think github sends the corresponding events but can we configure prow to trigger jobs when these events occur ?

/kind question

**Comment by stevekuznetsov** [comment]
Prow does not currently support this type of job triggering logic. I am unsure if it would make sense to add a generic "cleanup" type of job that's triggered like this, but some approaches you may use achieve something similar:

 - issue TTLs for your resources and remove the resources on expiry
 - require a heartbeat for resources from jobs using them and remove the resources if nothing is beating
 - write an external plugin to listen for pull request events and create ProwJobs as you expect

/cc @cjwagner @fejta

**Comment by eddycharly** [comment]
The use case is not really a cleanup of dangling resources.

Currently we deploy some branches to be tested by the business team so they can test the feature as it is developed.

Basically the preview environment has the same lifecycle as the branch, that's why i thought about triggering a job when the pull request is terminated (to tear down the preview environment).

For this reason the ttl is not really applicable.
The heartbeat can work but resources are not only resources in the kubernetes sense, it can be a database, a queue in rabbit, a bucket...

I will look at the external plugin solution, did you mean an external plugin for prow (like the needs-rebase plugin) or something completely external ?

Also, are you completely against the idea of supporting job triggers on pr termination events in prow, or is this something that could be accepted as a contribution ?

**Comment by fejta** [comment]
Is this still needed/wanted? 

So you want to trigger when a pull request is closed -- regardless of whether it merged?

**Comment by eddycharly** [comment]
/reopen

I don't need the feature anymore, but I reopen the issue because i think it should be nice to have.
Feel free to close it if you think it's useless.
