### ISSUE TITLE
maintenance-ci-aws-janitor has been failing since November 12

### ISSUE THREAD

**Issue by ncdc** [kubernetes/test-infra#15423]
**What happened**:
https://testgrid.k8s.io/sig-testing-maintenance#ci-aws-janitor has been failing since November 12.

**What you expected to happen**:
No failures.

**How to reproduce it (as minimally and precisely as possible)**:
Look at testgrid 😄 

**Please provide links to example occurrences, if any**:
Current failure as of issue creation time: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/maintenance-ci-aws-janitor/1199691318771585027

**Anything else we need to know?**:

**Comment by ncdc** [comment]
I'm going to look into this.

/assign
/lifecycle active

cc @detiber @dims @justinsb

**Comment by ncdc** [comment]
Here is the tail of the janitor execution output:

```
W1127 14:09:18.261] I1127 14:09:18.260191     235 route53.go:72] ignoring unmanaged name "api.internal.e2e-kops-aws.test-cncf-aws.k8s.io."
W1127 14:09:18.261] E1127 14:09:18.260424     235 set.go:116] 4 resources swept: [arn:aws:ec2:ap-southeast-1:768319786644:subnet/subnet-0e8a3f02ce123e0e0 arn:aws:ec2:ap-southeast-1:768319786644:security-group/sg-0cd7eafb8dc32e7e8 arn:aws:ec2:ap-southeast-1:768319786644:vpc/vpc-075a9e5b97cb4acd3 fakearn:elb:us-west-2:768319786644:api-e2e-kops-aws-ha-uswes-l3e4kr]
W1127 14:09:18.557] Traceback (most recent call last):
W1127 14:09:18.557]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W1127 14:09:18.557]     main(ARGS.env, ARGS.cmd + ARGS.args)
W1127 14:09:18.557]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W1127 14:09:18.557]     check(*cmd)
W1127 14:09:18.557]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W1127 14:09:18.557]     subprocess.check_call(cmd)
W1127 14:09:18.558]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W1127 14:09:18.558]     raise CalledProcessError(retcode, cmd)
W1127 14:09:18.558] subprocess.CalledProcessError: Command '('/aws-janitor', '--ttl=2h30m', '--path=s3://k8s-kops-prow/objs.json')' returned non-zero exit status 1
E1127 14:09:18.563] Command failed
I1127 14:09:18.564] process 234 exited with code 1 after 1.0m
E1127 14:09:18.564] FAIL: maintenance-ci-aws-janitor
```

The job is running in image from January from commit 57d0fe238f1aeea000e5cb6e1f5c07aab6af02d6. The call to `res.MarkComplete()` returns 4 for `swept`, and the process exits with code 1 because of this:

https://github.com/kubernetes/test-infra/blob/57d0fe238f1aeea000e5cb6e1f5c07aab6af02d6/maintenance/aws-janitor/main.go#L150-L151

**Comment by ncdc** [comment]
It looks like it's failing to delete the same 4 resources every time due to dependency violations:

```
W1127 14:08:55.891] W1127 14:08:55.890282     235 subnets.go:49] arn:aws:ec2:ap-southeast-1:768319786644:subnet/subnet-0e8a3f02ce123e0e0: deleting *ec2.Subnet: {
W1127 14:08:55.891]   AssignIpv6AddressOnCreation: false,
W1127 14:08:55.891]   AvailabilityZone: "ap-southeast-1c",
W1127 14:08:55.891]   AvailableIpAddressCount: 8169,
W1127 14:08:55.891]   CidrBlock: "172.20.32.0/19",
W1127 14:08:55.892]   DefaultForAz: false,
W1127 14:08:55.892]   MapPublicIpOnLaunch: false,
W1127 14:08:55.892]   State: "available",
W1127 14:08:55.892]   SubnetId: "subnet-0e8a3f02ce123e0e0",
W1127 14:08:55.892]   Tags: [
W1127 14:08:55.892]     {
W1127 14:08:55.892]       Key: "KubernetesCluster",
W1127 14:08:55.892]       Value: "e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io"
W1127 14:08:55.892]     },
W1127 14:08:55.892]     {
W1127 14:08:55.892]       Key: "Name",
W1127 14:08:55.892]       Value: "ap-southeast-1c.e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io"
W1127 14:08:55.893]     },
W1127 14:08:55.893]     {
W1127 14:08:55.893]       Key: "SubnetType",
W1127 14:08:55.893]       Value: "Public"
W1127 14:08:55.893]     },
W1127 14:08:55.893]     {
W1127 14:08:55.893]       Key: "kubernetes.io/role/elb",
W1127 14:08:55.893]       Value: "1"
W1127 14:08:55.893]     },
W1127 14:08:55.893]     {
W1127 14:08:55.893]       Key: "kubernetes.io/cluster/e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io",
W1127 14:08:55.893]       Value: "owned"
W1127 14:08:55.893]     }
W1127 14:08:55.894]   ],
W1127 14:08:55.894]   VpcId: "vpc-075a9e5b97cb4acd3"
W1127 14:08:55.894] }
W1127 14:08:56.198] W1127 14:08:56.198171     235 subnets.go:52] arn:aws:ec2:ap-southeast-1:768319786644:subnet/subnet-0e8a3f02ce123e0e0: delete failed: DependencyViolation: The subnet 'subnet-0e8a3f02ce123e0e0' has dependencies and cannot be deleted.
W1127 14:08:56.199] 	status code: 400, request id: 760877db-d44c-4e8e-8807-8f71856ef56d
W1127 14:08:57.060] W1127 14:08:57.059990     235 security_groups.go:67] arn:aws:ec2:ap-southeast-1:768319786644:security-group/sg-0cd7eafb8dc32e7e8: deleting *ec2.SecurityGroup: {
W1127 14:08:57.061]   Description: "Security group for nodes",
W1127 14:08:57.061]   GroupId: "sg-0cd7eafb8dc32e7e8",
W1127 14:08:57.061]   GroupName: "nodes.e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io",
W1127 14:08:57.061]   IpPermissionsEgress: [{
W1127 14:08:57.061]       IpProtocol: "-1",
W1127 14:08:57.061]       IpRanges: [{
W1127 14:08:57.061]           CidrIp: "0.0.0.0/0"
W1127 14:08:57.061]         }]
W1127 14:08:57.061]     }],
W1127 14:08:57.061]   OwnerId: "768319786644",
W1127 14:08:57.061]   Tags: [{
W1127 14:08:57.061]       Key: "Name",
W1127 14:08:57.062]       Value: "nodes.e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io"
W1127 14:08:57.062]     },{
W1127 14:08:57.062]       Key: "KubernetesCluster",
W1127 14:08:57.062]       Value: "e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io"
W1127 14:08:57.062]     },{
W1127 14:08:57.062]       Key: "kubernetes.io/cluster/e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io",
W1127 14:08:57.062]       Value: "owned"
W1127 14:08:57.062]     }],
W1127 14:08:57.062]   VpcId: "vpc-075a9e5b97cb4acd3"
W1127 14:08:57.062] }
W1127 14:08:57.357] W1127 14:08:57.356694     235 security_groups.go:93] arn:aws:ec2:ap-southeast-1:768319786644:security-group/sg-0cd7eafb8dc32e7e8: delete failed: DependencyViolation: resource sg-0cd7eafb8dc32e7e8 has a dependent object
W1127 14:08:57.358] 	status code: 400, request id: bc4f7483-acdf-48a2-8991-4acfff1e41c1
W1127 14:08:58.996] W1127 14:08:58.995509     235 vpcs.go:50] arn:aws:ec2:ap-southeast-1:768319786644:vpc/vpc-075a9e5b97cb4acd3: deleting *ec2.Vpc: {
W1127 14:08:58.996]   CidrBlock: "172.20.0.0/16",
W1127 14:08:58.996]   CidrBlockAssociationSet: [{
W1127 14:08:58.996]       AssociationId: "vpc-cidr-assoc-08b99f6825e5908c5",
W1127 14:08:58.996]       CidrBlock: "172.20.0.0/16",
W1127 14:08:58.996]       CidrBlockState: {
W1127 14:08:58.996]         State: "associated"
W1127 14:08:58.997]       }
W1127 14:08:58.997]     }],
W1127 14:08:58.997]   DhcpOptionsId: "default",
W1127 14:08:58.997]   InstanceTenancy: "default",
W1127 14:08:58.997]   IsDefault: false,
W1127 14:08:58.997]   State: "available",
W1127 14:08:58.997]   Tags: [{
W1127 14:08:58.997]       Key: "Name",
W1127 14:08:58.997]       Value: "e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io"
W1127 14:08:58.997]     },{
W1127 14:08:58.997]       Key: "kubernetes.io/cluster/e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io",
W1127 14:08:58.998]       Value: "owned"
W1127 14:08:58.998]     },{
W1127 14:08:58.998]       Key: "KubernetesCluster",
W1127 14:08:58.998]       Value: "e2e-kops-aws-vpc-cni.test-cncf-aws.k8s.io"
W1127 14:08:58.998]     }],
W1127 14:08:58.998]   VpcId: "vpc-075a9e5b97cb4acd3"
W1127 14:08:58.998] }
W1127 14:08:59.213] W1127 14:08:59.212562     235 vpcs.go:62] arn:aws:ec2:ap-southeast-1:768319786644:vpc/vpc-075a9e5b97cb4acd3: delete failed: DependencyViolation: The vpc 'vpc-075a9e5b97cb4acd3' has dependencies and cannot be deleted.
W1127 14:08:59.214] 	status code: 400, request id: bc6d53d7-b863-433f-bff7-24a7e7cd0f71
W1127 14:09:15.138] W1127 14:09:15.138321     235 elb.go:38] fakearn:elb:us-west-2:768319786644:api-e2e-kops-aws-ha-uswes-l3e4kr: deleting *elb.LoadBalancerDescription: {
W1127 14:09:15.139]   AvailabilityZones: ["us-west-2a","us-west-2b","us-west-2c"],
W1127 14:09:15.139]   CanonicalHostedZoneName: "api-e2e-kops-aws-ha-uswes-l3e4kr-1677089780.us-west-2.elb.amazonaws.com",
W1127 14:09:15.139]   CanonicalHostedZoneNameID: "Z1H1FL5HABSF5",
W1127 14:09:15.139]   CreatedTime: 2019-11-27 14:05:53.57 +0000 UTC,
W1127 14:09:15.139]   DNSName: "api-e2e-kops-aws-ha-uswes-l3e4kr-1677089780.us-west-2.elb.amazonaws.com",
W1127 14:09:15.139]   HealthCheck: {
W1127 14:09:15.140]     HealthyThreshold: 2,
W1127 14:09:15.140]     Interval: 10,
W1127 14:09:15.140]     Target: "SSL:443",
W1127 14:09:15.140]     Timeout: 5,
W1127 14:09:15.140]     UnhealthyThreshold: 2
W1127 14:09:15.140]   },
W1127 14:09:15.140]   Instances: [{
W1127 14:09:15.140]       InstanceId: "i-00cae7f5171978523"
W1127 14:09:15.141]     },{
W1127 14:09:15.141]       InstanceId: "i-07c59c71719494406"
W1127 14:09:15.141]     },{
W1127 14:09:15.141]       InstanceId: "i-0637f1daa02f64c1a"
W1127 14:09:15.141]     }],
W1127 14:09:15.141]   ListenerDescriptions: [{
W1127 14:09:15.141]       Listener: {
W1127 14:09:15.142]         InstancePort: 443,
W1127 14:09:15.142]         InstanceProtocol: "TCP",
W1127 14:09:15.142]         LoadBalancerPort: 443,
W1127 14:09:15.142]         Protocol: "TCP"
W1127 14:09:15.142]       }
W1127 14:09:15.142]     }],
W1127 14:09:15.142]   LoadBalancerName: "api-e2e-kops-aws-ha-uswes-l3e4kr",
W1127 14:09:15.143]   Policies: {
W1127 14:09:15.143] 
W1127 14:09:15.143]   },
W1127 14:09:15.143]   Scheme: "internet-facing",
W1127 14:09:15.143]   SecurityGroups: ["sg-03661e3993e4fd539"],
W1127 14:09:15.143]   SourceSecurityGroup: {
W1127 14:09:15.143]     GroupName: "api-elb.e2e-kops-aws-ha-uswest2.k8s.local",
W1127 14:09:15.144]     OwnerAlias: "768319786644"
W1127 14:09:15.144]   },
W1127 14:09:15.144]   Subnets: ["subnet-0d9ab632ca2ad8deb","subnet-0e5b75c6d93db07b3","subnet-0f85d3ddee7f9a107"],
W1127 14:09:15.144]   VPCId: "vpc-08909655ebcdb823a"
W1127 14:09:15.144] }
```

**Comment by ncdc** [comment]
Oddly, the ELB `fakearn:elb:us-west-2:768319786644:api-e2e-kops-aws-ha-uswes-l3e4kr` is consistently in the list of swept resources, but there's never an error logged that it couldn't be deleted.

**Comment by detiber** [comment]
Looks like https://github.com/kubernetes/test-infra/pull/15442 is related

**Comment by rifelpet** [comment]
This is also causing a [new E2E test I created](https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-vpc-cni) to fail because aws-janitor is not sweeping some resource that has an ENI with `sg-0cd7eafb8dc32e7e8` attached. [I asked in #testing-ops](https://kubernetes.slack.com/archives/C7J9RP96G/p1574777673233000) a while back but didn't get a response. My Route53 cleanup will help but I think it will continue to fail until we determine what this resource is that isn't being detected by aws-janitor. Is there someone with access to the AWS account that can see what is using that security group?

**Comment by ncdc** [comment]
@justinsb are you able to check the CloudTrail logs for why `elb:us-west-2:768319786644:api-e2e-kops-aws-ha-uswes-l3e4kr` isn't getting deleted? Also can you tell what the dependencies are that are keeping the other 3 resources from being deleted?

**Comment by ncdc** [comment]
I also wonder if it's worth updating the ci-aws-janitor job to use a newer version of the aws janitor?

**Comment by detiber** [comment]
> I also wonder if it's worth updating the ci-aws-janitor job to use a newer version of the aws janitor?

We'll need to if we want to pick up the changes from #15442 once it merges :)

**Comment by rifelpet** [comment]
Looking at the [available image tags](https://console.cloud.google.com/gcr/images/k8s-test-infra-aws/GLOBAL/aws-janitor?gcrImageListsize=30) it seems like the image is not build and pushed automatically, so we will need someone to build and push it now that #15442 is merged. Ideally it could happen automatically when there are new commits to `maintenance/aws-janitor` and then open a PR with the job update, similar to the autobump PRs for other images in this repo.

**Comment by detiber** [comment]
We should be building an image on post-submit albeit with a different repo/tag based on the [bazel config](https://github.com/kubernetes/test-infra/blob/master/boskos/BUILD.bazel#L21) and the [job config](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L178-L204), based on the latest [job run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-boskos/1201582235539476480#1:build-log.txt%3A142) the latest image should be: gcr.io/k8s-prow/boskos/aws-janitor:v20191202-3ab85226c

**Comment by rifelpet** [comment]
Great! Any reasons we shouldn't update the aws-janitor job to use this new image repo/tag? If not I can open a PR momentarily.

**Comment by detiber** [comment]
@rifelpet none that I can think of, I was avoiding it up until this point only because I didn't want to inadvertently affect the kops jobs :)

**Comment by rifelpet** [comment]
I'll take ownership for any kops issues :)

Opened #15451, we'll see if that takes care of these orphaned resources.

**Comment by rifelpet** [comment]
Now it seems like the job [isnt even running anymore](https://testgrid.k8s.io/sig-testing-maintenance#ci-aws-janitor). I'm able to pull the new image myself, so it's shouldn't be an auth issue. I asked again in #testing-ops so hopefully we find out soon.

**Comment by rifelpet** [comment]
It seems like the image built by bazel is specifically for the aws-janitor binary itself and doesn't have any of the log uploading support that the prow job relies on, typically with the "kubekins" image in other jobs:

https://github.com/kubernetes/test-infra/blob/abf99ad67d13e69cbc98ff55749d5f04a393e02c/config/jobs/kubernetes/test-infra/janitors.yaml#L9-L13

The new image is used by a Boskos Deployment, but I'm not sure how that relates to the prow job:

https://github.com/kubernetes/test-infra/blob/81bbae56a47e881543d0b9e0bb5108b3ac63692e/prow/cluster/boskos-janitor.yaml#L75-L97

I noticed one of the other janitor prow jobs just clones the test-infra repo and does a `go run` using the latest version of the code:

https://github.com/kubernetes/test-infra/blob/81bbae56a47e881543d0b9e0bb5108b3ac63692e/config/jobs/kubernetes/test-infra/janitors.yaml#L42-L58

Would we want to move towards that setup? I can't tell how the old aws-janitor image was built in order to support the `--bare --timeout --service-account --upload --scenario` flags used in the prow job, so I don't know how we should best replicate that behavior. Thoughts?

**Comment by detiber** [comment]
It looks like some of the arguments accepted by bootstrap.py (which is wrapped by both the referenced `runner.sh` and the `runner` script included in the base `gcloud-in-go` image used as a base for the `aws-janitor` image) no longer exist. It would probably be good to update the job to use the [pod utilities](https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md), especially for configuring the log uploading.

**Comment by rifelpet** [comment]
I'm hoping we can get #15475 merged soon to get these resources cleaned up and to avoid reoccurring git conflicts from the image updating PRs.

**Comment by rifelpet** [comment]
The job is now passing but the logs show that some resources are still failing to be deleted: 

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/maintenance-ci-aws-janitor/1207058854198644747

I think the job should fail if any resource deletions fail. I'll try to investigate more, but it would help immensely if we knew what was still using the subnet and security group.
