### ISSUE TITLE
How to enable PROW and Travis work together

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/test-infra#15420]
Travis now support multi-arch build https://docs.travis-ci.com/user/multi-cpu-architectures/ , this can make sure we can build binaries for different platforms with travis.

The question here does there are any comments or best practise to enable PROW and travis work together so that I can use travis to build multi-arch docker images and also run the CI/CD on Multiple CPU Architectures, any comments for this? Thanks!

**Comment by stevekuznetsov** [comment]
Prow and the legacy Travis may work together, just as Prow itself can be configured to talk to Kubernetes clusters across architectures and achieve a multi-arch approach as well. Travis using the (beta) GitHub actions API is _not_ yet supported. That deficiency is documented at oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: net/http: TLS handshake timeout]

**Comment by gyliu513** [comment]
Thanks @stevekuznetsov for the active response! So you mean that I can set up a **mixed** Kubernetes cluster which including x86, POWER, and Z CPU Architecture platforms, and config PROW use different  architectures to build? If so, does there are any document for the configuration?

**Comment by gyliu513** [comment]
FYI @morvencao @clyang82
