### ISSUE TITLE
Enable prow to report job failure metadata

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#15469]
Prow expects jobs to be solely responsible for uploading results. We provide podutils (via `decorate: true`) to help users handle the requirement with little effort, but for podutils to act it needs to a) run in the first place, and also b) not terminate unexpectedly.

In practice, many pods either never start or terminate unexpectedly, either due to pod misconfiguration (e.g. bad secret -> can't start) or due to node issues ("cannot create sandbox", containerd crashes, ...). These issues are impossible for end-users to debug, because none of the information is exposed to them. They are also hard to debug even with direct cluster access, because the pods are generally cleaned up within half an hour, after which you need to dig through kubelet logs to attempt to derive what happened. Additionally, the jobs appear to anything reading GCS to have never terminated (this is #15154).

**To improve this**, some prow component should optionally observe either a job failing or a pod terminating, and upload relevant information (particularly pod events and the pod state). It should also ensure that a `finished.json` exists.

I would imagine this feature could reasonably be part of crier - have uploading pod metadata (in a new file) to the locations that podutils would've uploaded to as an option on termination, as well as uploading a finished.json if one is missing.

**Comment by stevekuznetsov** [comment]
100% Agree. This was the thought behind `artifact-uploader` (in the Prow tree today). IMO we should upload the ProwJob and Pod YAML to GCS and then everyone downstream can digest that whichever way they like :)

**Comment by spiffxp** [comment]
Updated PR https://github.com/kubernetes/test-infra/pull/15785

**Comment by Katharine** [comment]
I did this!
