### ISSUE TITLE
verify-owners allowed adding a non-repo collaborator to helm/charts

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15494]
https://github.com/hakman/charts/commits/4bf26601862700c2da25a82a2ee5aa6f7a2c0edf/stable/sematext-agent/OWNERS

/area prow
/area prow/hook
/kind oncall-hotlist

See https://github.com/helm/charts/issues/19410 for more info

Looks like we added this plugin to helm/charts on Oct 2018: https://github.com/kubernetes/test-infra/commit/5c2d099897271a73cfae6d9fd4654adbf76dbcef

This OWNERS file was created Feb 12 of this year, latest edit was Jul 9 2019: https://github.com/hakman/charts/commits/4bf26601862700c2da25a82a2ee5aa6f7a2c0edf/stable/sematext-agent/OWNERS

**Comment by nikhita** [comment]
This isn't a bug, `helm/charts` explicitly opts into skipping the collaborator check:

https://github.com/kubernetes/test-infra/blob/d6d702584f4cf72e7addbdb442640d054c78cdc3/config/prow/plugins.yaml#L33-L35

https://github.com/kubernetes/test-infra/blob/d6d702584f4cf72e7addbdb442640d054c78cdc3/prow/plugins/verify-owners/verify-owners.go#L124-L129

/remove-kind bug

**Comment by nikhita** [comment]
> helm/charts explicitly opts into skipping the collaborator check

This was added in https://github.com/kubernetes/test-infra/pull/10164. @mattfarina is this something that is still desired for the helm/charts repo?

**Comment by nikhita** [comment]
Closing since this isn't a bug. Please reopen if the helm/charts configuration needs to be updated.

/close

**Comment by fejta** [comment]
This is a bug in helm/charts' config -- github disallows assigning people who are not involved in the repo in some way
