### ISSUE TITLE
Run kubernetes-e2e-gce-federation as part of tests that merge bot runs on each PR

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/test-infra#155]
This is to catch PRs that break federation tests.

cc @kubernetes/sig-testing @ixdy @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/26723

**Comment by nikhiljindal** [comment]
This is blocking https://github.com/kubernetes/contrib/pull/1198.

@kubernetes/sig-testing who can help while @ixdy is out?

**Comment by spxtr** [comment]
You'll need to make a PR adding a new entry to [this](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/kubernetes-pull.yaml) yaml file.

It looks like the federation tests take ~40 minutes to run on post-submit Jenkins. You'll have to cut out tests to get build + test time down to 30 minutes or so.

**Comment by nikhiljindal** [comment]
Is it possible to run federation-e2e suite only if there is a change in `federation/` directory?
That way only federation related PRs will be affected by the longer test running time, which might be acceptable?

**Comment by madhusudancs** [comment]
The trouble with watching for changes only in `federation` directory is, all our code is not in that directory. We use a ton of code from the packages outside and a change there could break us badly. See - https://github.com/kubernetes/kubernetes/pull/29123 for example. 

But having said that, having something that works is better than nothing. If it is easier to just watch for changes in the `federation` directory I think that should be a good start, but it is not worth building out the infrastructure for that if it doesn't exist already.

**Comment by nikhiljindal** [comment]
Agreed. Its better to have federation e2e tests running at least on PRs that change code in federation/ dir, while we figure out how to reduce the run time of our test suite.

**Comment by nikhiljindal** [comment]
Have sent https://github.com/kubernetes/test-infra/pull/335 so that anyone can type `@k8s-bot federation gce e2e test this` on any PR which will trigger federation tests with code in that PR. 

That should help decrease some pain
