### ISSUE TITLE
Every component prints out a plank.allow_cancellations deprecation message every 10 minutes

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#15502]
We're deprecating this option. Therefore we should only display a warning if they define a policy.

We should not force them to start setting it to true.

ref https://github.com/kubernetes/test-infra/pull/15150

/assign @fejta @alvaroaleman 
/kind oncall-hotlist

**Comment by fejta** [comment]
![allow_cancel](https://user-images.githubusercontent.com/940341/70277634-9bbac380-1767-11ea-9cc4-f00a5d6cbd5f.png)

**Comment by alvaroaleman** [comment]
> We should not force them to start setting it to true.

We don't, but changing the default is a backward-incompatible change and I do not want to do that without a grace period. During that grace period the warning is shown if the setting is not explicitly set to `true`.

**Comment by fejta** [comment]
Showing thousands of warnings about a default changing is bad behavior

**Comment by alvaroaleman** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/15522
/close
