### ISSUE TITLE
kubetest: Unable to connect to the server due to connection timeout after some amount of time

### ISSUE THREAD

**Issue by nan-yu** [kubernetes/test-infra#15504]
**What happened**:

I used `kubetest` to setup a cluster on GCE and run e2e test against the cluster. It was running okay initially. I can use `kubectl` to list all resources. After about 20 minutes or so, I was not able to connect to the server.
```
$ kubectl get nodes
Unable to connect to the server: dial tcp 104.154.211.234:443: connect: connection timed out
```
The apiserver log on the master looks okay to me.

**What you expected to happen**:

I should be able to connect to the server again using `kubectl`.

**How to reproduce it (as minimally and precisely as possible)**:

1. install `kubetest` with `test-infra` repo: `go install k8s.io/test-infra/kubetest`
2. build the kubernetes binary: `kubetest --build`
3. tear down any existing cluster: `kubetest --down`
4. start up a new cluster on GCE: `kubetest --up`
5. check the resources periodically: `kubectl get nodes` and eventually get timed out

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
kubetest only calls the cluster creation code from standard tools (in this case probably kube-up in kubernetes repo), so any bug is going to be there.

you should check the logs on the VM
