### ISSUE TITLE
Shall we add permission limit for subproject

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/test-infra#15527]
Hi team,

We have some [subprojects](https://github.com/kubernetes/community/blob/master/governance.md#subprojects) from our community, and sometimes the PR approver and reviewer for the subprojects is distinct with the main project, for example, our website docs owner is inside [OWNERS.md](https://github.com/kubernetes/website/blob/master/OWNERS) of the website root, and content/en has its own [OWNERS.md](https://github.com/kubernetes/website/blob/master/content/en/blog/OWNERS), what's more, blog under the content/en is another subproject, and it has its own [OWNERS](https://github.com/kubernetes/website/blob/master/content/en/blog/OWNERS).

The problem is, when someone submitted a PR for blog related issues, docs [OWNER](https://github.com/kubernetes/website/blob/master/OWNERS) and content/en [OWNER](https://github.com/kubernetes/website/blob/master/content/en/blog/OWNERS) could also do approve. This action is **NOT** suitable to the context, since the blog content is subproject from the website, and should be reviewed\approved from the blog subproject [OWNERS](https://github.com/kubernetes/website/blob/master/content/en/blog/OWNERS).

**What would you like to be added**:
For OWNERS.md, we could add some permission level limitations and overrides, such as the subproject things should **ONLY** be approved/reviewed by the subproject OWNERS.

**Why is this needed**:
Currently, we seems not limit to this, and the project OWNERS could do approve/review for subproject PRs without subproject OWNERS reviews. It would make our subproject messy, so we should enhance this level permission controls.

Thanks.

**Comment by alvaroaleman** [comment]
I believe this can be achieved already by setting `no_parent_owners: true` in the subprojects OWNERS file, ref: https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md

**Comment by Colstuwjx** [comment]
Awesome！
