### ISSUE TITLE
Confusing deprecation message on Prow job viewer

### ISSUE THREAD

**Issue by johngmyers** [kubernetes/test-infra#15530]
**What happened**:

Followed "Details" link from a Github check to the Prow job viewer. Read message at top of page "The old job viewer has been deprecated. If you need it, please contact #sig-testing on Slack." Took the implication that the page currently being viewed was deprecated and filed issue to update the Github check's link target.

**What you expected to happen**:

Page to not have misleading messages.

**How to reproduce it (as minimally and precisely as possible)**:

Navigate to a PR on a Kubernetes repo. Follow "Details" link for a Prow check. Read message at top of resulting page.

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kops/8035/pull-kops-bazel-test/1201690915463237633/

**Anything else we need to know?**:

**Comment by Katharine** [comment]
It's been long enough at this point that we should probably just kill the announcement entirely.

/assign
