### ISSUE TITLE
Prow issue:dns. Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.8.8.8 8.8.4.4

### ISSUE THREAD

**Issue by mdhamale** [kubernetes/test-infra#15552]
dns.go:135] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.8.8.8 8.8.4.4

**Comment by alvaroaleman** [comment]
The error you posted above is from the Kubelet and gets emitted when your hosts resolv.conf contains more than two nameservers: https://www.reddit.com/r/kubernetes/comments/7ruq0f/kubelet_nameserver_limits_were_exceeded/dszx5h5/

Closing this issue as I do not see a Prow bug here, feel free to re-open if I missed something.
/close
