### ISSUE TITLE
boskos: ranch: /acquire /update /reset and /release median response time is ~90 seconds

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#15557]
![boskos-server-dashboard](https://user-images.githubusercontent.com/7328370/70570028-f5e4cb80-1b4f-11ea-9e5a-45fe3082a026.png)

/area boskos
/cc @krzyzacy @sebastienvas

**Comment by stevekuznetsov** [comment]
```json
{"component":"boskos","file":"boskos/boskos.go:195","func":"main.handleAcquire.func1","handler":"handleStart","level":"info","msg":"From 172.16.74.74:33078","time":"2019-12-09T23:29:07Z"}
{"component":"boskos","file":"boskos/boskos.go:217","func":"main.handleAcquire.func1","level":"info","msg":"Request for a free gcp-quota-slice from -e8c8c, dest leased","time":"2019-12-09T23:29:07Z"}
{"component":"boskos","file":"boskos/boskos.go:238","func":"main.handleAcquire.func1","level":"info","msg":"Resource leased: {\"type\":\"gcp-quota-slice\",\"name\":\"01229229-ce89-4b67-b8d6-54537e57de01\",\"state\":\"leased\",\"owner\":\"-e8c8c\",\"lastupdate\":\"2019-12-09T23:29:08.296273508Z\",\"userdata\":{}}","time":"2019-12-09T23:29:08Z"}
```

I am having trouble finding logs that correspond with this behavior, makes me think it's something more pathological.

**Comment by stevekuznetsov** [comment]
No, looks like a bona fide slowness:

```json
{
  "msg": "Request for a free aws-quota-slice from ci-op-mcgczqp0-76f5e, dest leased",
  "time": "2019-12-10T14:43:41Z"
}
{
  "msg": "Resource leased: {\"type\":\"aws-quota-slice\",\"name\":\"8ccc9a07-ed5d-4584-b845-3773bc5da3ff\",\"state\":\"leased\",\"owner\":\"ci-op-mcgczqp0-76f5e\",\"lastupdate\":\"2019-12-10T14:45:05.631972956Z\",\"userdata\":{}}",
  "time": "2019-12-10T14:45:05Z"
}
```

**Comment by stevekuznetsov** [comment]
That means this has to be a slowdown in `ranch.Acquire()` or `json.Marshal()` as those are the only calls between those logs. I'd imagine it's the former.

**Comment by sebastienvas** [comment]
How many resources do you have ? are you using the latest version of boskos ?
@ixdy

**Comment by sebastienvas** [comment]
I am asking because a while back there was an issue when updating resources. We were updating all the resources every 10 minutes. Now we just add or delete when there is a config change. Because we lock all resources in Acquire, you might still notice this if you have a lot of resources, and a lot of users.As you know the locking mechanism does not scale, and might need some rework.

**Comment by stevekuznetsov** [comment]
We are running `v20191209-15bc10984` and have ~4000 resources:

```
$ kubectl get resources.boskos.k8s.io | wc -l
4208
```

**Comment by stevekuznetsov** [comment]
![Screenshot from 2019-12-10 14-55-03](https://user-images.githubusercontent.com/7328370/70576167-110a0800-1b5d-11ea-9cc6-69d5f371aaa9.png)

Average APIServer request latency for a boskos resource is ~0.05s. So if we're seeing 90+ seconds on a boskos client call, that would be ~2000 calls from `ranch` to the API per call from a lease client to `ranch`? That seems wild. We definitely don't have 2000 pending requests at a time, not that I can see.

**Comment by sebastienvas** [comment]
Maybe tweak your janitors and other boskos components to retry at bigger intervals ?

**Comment by stevekuznetsov** [comment]
The `boskos` request throughput is capped at one request every ~2.5 minutes ... is there some internal rate limiting going on?

**Comment by stevekuznetsov** [comment]
![Screenshot from 2019-12-10 14-58-48](https://user-images.githubusercontent.com/7328370/70576435-bd4bee80-1b5d-11ea-802b-06959afd265e.png)

**Comment by stevekuznetsov** [comment]
That's about one request every 20s

**Comment by ixdy** [comment]
@stevekuznetsov do you have any updated info based on the debugging logs you added?

**Comment by stevekuznetsov** [comment]
I needed to [log at `debug`](https://github.com/openshift/release/pull/6357) but I'm not seeing debug-level logs ...

**Comment by stevekuznetsov** [comment]
OK, so I gathered logs from 242 acquires given the logging that I added and I can comfortably say that we are not spending time there:

```
                         STAGE	MIN	MAX	AVG	STDEV
  Determined request priority.	0	0	0.00	0.00
   Considering 4207 resources.	0	12	0.79	0.98
            Updating resource.	0	12	0.79	0.98
         Cleaning up requests.	0	12	0.82	0.99
Successfully acquired resource.	0	12	0.82	0.99
                       overall	0	12	0.82	0.99
```

This was analyzed with the following script:

```py
#!/bin/env python

import json
from dateutil import parser
from statistics import mean, stdev

data = {} # entries by identifier
with open("/tmp/boskos.json.filtered") as raw:
	i = 0
	for line in raw:
		item = json.loads(line)
		identifier = "{}{}".format(item["identifier"], i/6)
		if identifier not in data:
			data[identifier] = {}
		data[identifier][item["msg"]] = item["time"]
		i += 1

order = [
	"Determining request priority...",
	"Determined request priority.",
	"Considering 4207 resources.",
	"Updating resource.",
	"Cleaning up requests.",
	"Successfully acquired resource.",
]


times = {} # time by step
for item in order[1:]:
	times[item] = []
times["overall"] = []

for identifier in data:
	entries = data[identifier]
	start = parser.parse(entries[order[0]])
	for item in order[1:]:
		times[item].append((parser.parse(entries[item]) - start).seconds)

	times["overall"].append((parser.parse(entries[order[-1]]) - start).seconds)

print("{:>30s}\t{}\t{}\t{}\t{}".format("STAGE", "MIN", "MAX", "AVG", "STDEV"))
for item in order[1:] + ["overall"]:
	print("{:>30s}\t{}\t{}\t{:2.2f}\t{:2.2f}".format(item, min(times[item]), max(times[item]), mean(times[item]), stdev(times[item])))
```

**Comment by stevekuznetsov** [comment]
FWIW the dataset I just analyzed goes from `2019-12-12T20:07:55Z` to `2019-12-12T22:07:33Z` -- here is the corresponding response time histogram

![boskos-server-dashboard2](https://user-images.githubusercontent.com/7328370/70755671-51998b00-1cef-11ea-8fc6-8cd3d10c411c.png)

**Comment by stevekuznetsov** [comment]
So this, plus the data that shows our QPS is basically flat-lined the whole day and shows no difference during times of peak use, brings me back to some rogue concurrency limiting code. Does that exist somewhere @sebastienvas @krzyzacy ?

**Comment by stevekuznetsov** [comment]
Ah, there is a global lock that serializes every single call. And `boskos` lists all possible resources from the server on every call, without an informer/lister or a cache. That would do it. Why don't we lock more granularly? We could shard locks by resource type and state.

**Comment by stevekuznetsov** [comment]
Alternatively we could probably come up with a design that lets `etcd` lock for us

**Comment by stevekuznetsov** [comment]
In case we needed the data ...

```
                            STAGE MIN   MAX   AVG   STDEV
       Acquiring resource lock... 65    104   91.9  10.4 
  Determining request priority... 0     0     0.0   0.0  
     Determined request priority. 0     1     0.7   0.5  
      Considering 4207 resources. 0     0     0.0   0.0  
               Updating resource. 0     0     0.0   0.0  
            Cleaning up requests. 0     0     0.0   0.0  
                          overall 65    105   92.6  10.4 

N=65
```

**Comment by ixdy** [comment]
ok, so we know that acquiring the resource lock is taking a long time. do we know what's holding it for so long? or is it just too much contention for the lock?

**Comment by ixdy** [comment]
maybe we should see if we can replicate this outside of production and try [profiling the locks](https://stackimpact.com/blog/detecting-lock-contention-in-go/).

**Comment by ixdy** [comment]
@stevekuznetsov I'm not exactly sure what your workloads look like, but it seems like `/reset` is very slow, even without any contention. Running in a kind cluster, it took about 38s to reset 100 resources (after acquiring the lock), so that's one place to continue investigation.

**Comment by stevekuznetsov** [comment]
We've not bumped `boskos` in four days. More data:

```
                            STAGE MIN   MAX   AVG   STDEV
       Acquiring resource lock... 0     634   70.9  56.9 
  Determining request priority... 0     2     0.0   0.1  
     Determined request priority. 0     69    1.1   3.2  
      Considering 4207 resources. 0     2     0.0   0.1  
               Updating resource. 0     7     0.1   0.3  
            Cleaning up requests. 0     1     0.0   0.0  
                          overall 0     658   72.1  58.4 

N=4215
```

Blocking profile from pprof:

[pprof.app.binary.contentions.delay.002.pb.gz](https://github.com/kubernetes/test-infra/files/3981071/pprof.app.binary.contentions.delay.002.pb.gz)

**Comment by stevekuznetsov** [comment]
... And of course there is nothing in that profile since we don't have it on. Turning it on: https://github.com/kubernetes/test-infra/pull/15653

IMO we shouldn't need to lock in `boskos`. The API server will serialize changes to the CRs and we could get away with intelligent retries.

**Comment by stevekuznetsov** [comment]
>  I'm not exactly sure what your workloads look like, but it seems like /reset is very slow, even without any contention.

@ixdy here's our `/reset` histogram over the last week -- 
![boskos-server-dashboard-reset](https://user-images.githubusercontent.com/7328370/71134112-e26ddc00-21b1-11ea-8635-25fa63aa0115.png)

The call does hold the lock, so I'm not sure what you mean by contention, but it's definitely slow.

**Comment by stevekuznetsov** [comment]
Given that there's a really clear cyclic pattern based on working hours I'm not really sure we will find anything more interesting than serialization of many requests being slow due to the global lock. I'll try to deploy the new pprof samplers and get a blocking profile, though.

**Comment by ixdy** [comment]
By "no contention" I mean nothing else was holding the lock in my simple local deployment; it simply takes a long time to reset each resource one-by-one. I guess this was also mentioned upthread.

If you have a bunch of resources that are getting periodically reaped, I could see that causing some of the delay. Deploying several reapers and janitors locally also killed performance for me (now requests take 4s, rather than <1s). Agree that we should get rid of the global lock.

**Comment by stevekuznetsov** [comment]
![Screenshot from 2019-12-19 11-01-13](https://user-images.githubusercontent.com/7328370/71201500-04696c00-224f-11ea-839e-d87f040a7acb.png)

[pprof.app.binary.contentions.delay.004.pb.gz](https://github.com/kubernetes/test-infra/files/3985211/pprof.app.binary.contentions.delay.004.pb.gz)

**Comment by stevekuznetsov** [comment]
![Screenshot from 2019-12-19 11-03-22](https://user-images.githubusercontent.com/7328370/71201584-3aa6eb80-224f-11ea-86d4-46befdc495c0.png)

**Comment by stevekuznetsov** [comment]
Nothing super surprising here ... this just reflects our request volumes 
![Screenshot from 2019-12-19 11-05-03](https://user-images.githubusercontent.com/7328370/71201708-73df5b80-224f-11ea-8145-92646aca732b.png)
