### ISSUE TITLE
New GCS bucket for CRI-O tests

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/test-infra#15569]
**What would you like to be added**:

I'd like to request a GCS bucket for running CRI-O (https://github.com/cri-o/cri-o) tests. We would run them in the first place inside the community cluster (packet.com) based on our self-deployed infrastructure. Afterwards we consider bringing them into Kubernetes, when stable over a certain amount of time.

**Why is this needed**:

It looks like that we have no chance to store artifacts without a GCS bucket.

Refers to https://github.com/kubernetes/test-infra/issues/15568

**Comment by dims** [comment]
request goes to kubernetes/k8s.io please see recent PRs that created buckets for pushing test results
