### ISSUE TITLE
[bootstrapper]Missing files in configmap

### ISSUE THREAD

**Issue by hongkailiu** [kubernetes/test-infra#15570]
The config is 
https://github.com/openshift/release/blob/5f828a8cc83715e19249f248f2be16b2f9dca5d3/core-services/prow/02_config/_plugins.yaml

When we have multi-file patterns for a configMap, `bootstrapper` did not pull all files into the configmap.

Example: `ci-operator-misc-configs`

This could be caused by
https://github.com/kubernetes/test-infra/pull/15507

**Comment by petr-muller** [comment]
This is the reproducing part of the config:

https://github.com/openshift/release/blob/5f828a8cc83715e19249f248f2be16b2f9dca5d3/core-services/prow/02_config/_plugins.yaml#L310-L320

To trip this bug, the config-updater must be configured to update a single CM with multiple patterns, one of which has `""` as a namespace, and another has an explicit namespace that is at the same time the default Prow job namespace.

The simplified config-bootstrapper is essentially this:

```go
for cm, data := range updateconfig.FilterChanges(pluginAgent.Config().ConfigUpdater, changes, logger) {
  if cm.Namespace == "" {
    cm.Namespace = configAgent.Config().ProwJobNamespace
  }
  updateconfig.Update(&updateconfig.OSFileGetter{Root: o.sourcePath}, configMapClient, cm.Name, cm.Namespace, data, bootstrapMode, nil, logger)
}
```
`updateconfig.FilterChanges` returns a map from a `(cluster, namespace, config map name)` triplet to the expected CM content. It's a map, so we iterate over triplet exactly once, but then we treat the `cm.Namespace == ""` in a special way, setting namespace field to some default. So when the following two triplets are returned by `FilterChanges`, the latter is modified to be the same like the first, leading to an `updateconfig.Update` being called for a single CM twice with a different expected content:
```
(cluster, default_prowjob_namespace, name)
(cluster, "", name)
```
After https://github.com/kubernetes/test-infra/pull/15507, the `updateconfig.Update` call removes keys from the CM on the cluster, if they are not present in current `data`, so the second call for a single CM removes all content that was present in the first call and is not present in the second.

**Comment by hongkailiu** [comment]
/close

fixed by https://github.com/kubernetes/test-infra/pull/15575
