### ISSUE TITLE
feature request: do not assign to WIP / DO-NOT-MERGE / draft PRs

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#15572]
**What would you like to be added**: For blunderbuss to only auto-assign to PRs once they are marked as mergeable.

**Why is this needed**: So PRs can be opened as WIP to allow showing what the PR would look like without actually bothering the eventual reviewers while the PR is being iteratively developed / tested.

It is a frequent pattern in kubernetes/kubernetes to open a WIP / do-not-merge PR to test something via the CI and get a linkable diff all in one, without the PR actually being intended for review yet. Often there is a comment explaining that the PR should not be reviewed.

It would be nice if we could just not assign people until after the PR is not a draft / WIP / "DO NOT MERGE".

/area prow
/area prow/hook

**Comment by coryrc** [comment]
If those keywords are detected, the WIP label could be applied automatically: https://github.com/kubernetes/test-infra/tree/master/prow/plugins/wip

And when the robot sees that label, choose not to add reviewers if there aren't any. When the label is removed, it could add reviewers IFF there aren't any reviewers already.

**Comment by stevekuznetsov** [comment]
@coryrc that is a good idea! One downside is that the `blunderbuss` plugin will get an event on the creation of all PRs, and we handle every event asynchronously for every plugin, so we cannot assume that the WIP label would already have been added by the time that `blunderbuss` was running. I think we would need to factor our code so that `blunderbusss` could also do the checks for draft/WIP itself.

**Comment by coryrc** [comment]
@stevekuznetsov Good approach. I will try coding this unless someone else plans to.
/assign @coryrc

**Comment by sftim** [comment]
/reopen
I'd like this feature
/remove-lifecycle rotten

**Comment by sftim** [comment]
You can now open a PR that is draft (in the GitHub API) from the start, so perhaps we could catch that case first?

**Comment by BenTheElder** [comment]
Currently draft PR = do not run tests, WIP = not considered for merge.

This sounds like a useful change but workflow change =>
/sig contributor-experience
