### ISSUE TITLE
GCE 1.14-1.16 tests fail to download latest k8s version

### ISSUE THREAD

**Issue by pierewoj** [kubernetes/test-infra#15580]
**What happened**:
Multiple 1.14-1.16 tests failing. Scalability ones:
* https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-1.16-scalability-100
* https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-1.15-scalability-100
* https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-cos-1.14-scalability-100

But also other, like:
* https://k8s-testgrid.appspot.com/sig-release-1.15-blocking#Conformance%20-%20GCE%20-%201.15

**What you expected to happen**:
I expected them to pass.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
At a first glance, seems like a bug in get-kube.sh KUBE_CI_VERSION_REGEX regex. K8s version.sh uses git version, and if last commit is tagged then the version might be in a slightly different format. There was release emails sent out yday so it might be related. However, I did not debug it further and have not confirmed that this is indeed the case.

**Comment by pierewoj** [comment]
this is not scalaiblity issue, other tests are also faling due to this issue:
https://k8s-testgrid.appspot.com/sig-release-1.15-blocking#Conformance%20-%20GCE%20-%201.15
https://k8s-testgrid.appspot.com/sig-release-1.15-blocking#gce-device-plugin-gpu-1.15
https://k8s-testgrid.appspot.com/sig-release-1.15-blocking#gce-cos-k8sstable2-ingress

/remove-sig scalability
/sig release

**Comment by alejandrox1** [comment]
For added context.. the interesting bit is in here
```
W1213 12:02:50.796] 2019/12/13 12:02:50 process.go:155: Step '/workspace/get-kube.sh' finished in 7.532053ms
W1213 12:02:50.796] 2019/12/13 12:02:50 extract_k8s.go:298: U=https://storage.googleapis.com/kubernetes-release-dev/ci R=v1.16.4-1+8aa1d9dd63e9a4 get-kube.sh failed: error during /workspace/get-kube.sh: exit status 1
...
W1213 12:02:51.803] 2019/12/13 12:02:51 process.go:153: Running: /workspace/get-kube.sh
W1213 12:02:51.810] Version doesn't match regexp
```
took the above from https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable1/1205457621247594502#1:build-log.txt%3A187

Looking at the current release markers
```
$ for suffix in beta stable1 stable2 stable3; do
>   echo ci/k8s-$suffix: $(gsutil cat gs://kubernetes-release-dev/ci/k8s-$suffix.txt);
> done
ci/k8s-beta: v1.17.1-beta.0.5+512f09638c517a
ci/k8s-stable1: v1.16.4-1+8aa1d9dd63e9a4
ci/k8s-stable2: v1.15.7-1+8f2d955e008dd5
ci/k8s-stable3: v1.14.10-1+6a71926e65a090
```

**Comment by alejandrox1** [comment]
The commit range in k/k for when tests began to fail doesnt show anything interesting but the test-infra one is here https://github.com/kubernetes/test-infra/compare/cf6fb4d2b...d6d702584

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/issues/86182#issuecomment-565204941

Something changed / went wrong when the latest point releases were cut

/assign @tpepper @justaugustus 
Who said they were looking into it

**Comment by justaugustus** [comment]
Closing to consolidate the conversation on https://github.com/kubernetes/kubernetes/issues/86182.
/close
