### ISSUE TITLE
pull-kubernetes-integration jobs should have fork annotations configured

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/test-infra#15638]
**What should be cleaned up or changed**:
I noticed on https://github.com/kubernetes/test-infra/pull/15637 that we're manually configuring the `pull-kubernetes-integration` and they look like good candidates to utilize the config-forker annotations instead.

**Provide any links for context**:
https://github.com/kubernetes/test-infra/pull/15637, https://github.com/kubernetes/test-infra/pull/15113, https://github.com/kubernetes/test-infra/pull/15156

/sig testing release
/area release-eng
/milestone v1.18
/kind cleanup
/assign
/priority important-longterm

**Comment by spiffxp** [comment]
/remove-lifecycle rotten

The pull-kubernetes-integration job has a `fork-per-release` annotation, it was used to create the v1.18 job.  I opened a PR to move the other release-branch jobs to their respective files which should close this out: https://github.com/kubernetes/test-infra/pull/17238
