### ISSUE TITLE
Some velodrome dashboards are timing out, make velodrome look non-functional

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#15644]
**What happened**:
Some velodrome dashboards appear to be not working, to the point that the list of dashboards is no longer populated

**What you expected to happen**:
Dashboards to work. If they didn't work, for the list of dashboards to be populated at least.

**How to reproduce it (as minimally and precisely as possible)**:
Dashboards that don't work:
- http://velodrome.k8s.io/dashboard/db/bazel-cache?refresh=1m&orgId=1
- http://velodrome.k8s.io/dashboard/db/github-cache?refresh=1m&orgId=1
- http://velodrome.k8s.io/dashboard/db/monitoring?orgId=1
- http://velodrome.k8s.io/dashboard/db/boskos-dashboard?orgId=1

Dashboards that work:
- http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1
- http://velodrome.k8s.io/dashboard/db/job-health-merge-blocking?orgId=1
- http://velodrome.k8s.io/dashboard/db/job-health-release-blocking?orgId=1
- http://velodrome.k8s.io/dashboard/db/job-health-release-informing?orgId=1

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
I think any dashboards except the bigquery ones are now superseded by dashboards on monitoring.prow.k8s.io, we should either drop the errant dashboards on velodrome or replace them with a text panel that points to their replacements

/sig testing
/area velodrome
/priority important-soon

**Comment by spiffxp** [comment]
bazel -> ???
github-cache -> https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1
monitoring -> https://monitoring.prow.k8s.io/d/d69a91f76d8110d3e72885ee5ce8038e/tide-dashboard?orgId=1
boskos -> https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1

**Comment by spiffxp** [comment]
The dashboards in question are having problems with the prometheus datasource, which is hooked up to velodrome's instance of prometheus

```
$ k config use-context gke_kubernetes-site_us-central1-a_utilicluster
$ k logs prometheus-kubernetes-2616881006-b8xfr -n velodrome
...
time="2019-12-11T15:34:42Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:548"
time="2019-12-11T15:34:57Z" level=error msg="Error while checkpointing: write /prometheus/heads.db.tmp: no space left on device" source="storage.go:1158"
```
... which appears to be out of disk space

**Comment by spiffxp** [comment]
Restarted prometheus pod, which I doubt will solve this, but has stopped timeouts long enough for me to do something from the admin console in grafana

I've updated the default dashboard for velodrome.k8s.io to be http://velodrome.k8s.io/dashboard/db/job-health-merge-blocking?orgId=1

**Comment by spiffxp** [comment]
http://velodrome.k8s.io/dashboard/db/bazel-cache?refresh=1m&orgId=1&from=now-90d&to=now - looks like we stopped gathering data around 2019-11-15

For the other dashboards, I've replaced them with text panels pointing to monitoring.prow.k8s.io

**Comment by spiffxp** [comment]
That's as far as I'm taking this for now.  It's likely going to timeout on the bazel dashboard again but the setup doesn't look amenable to volume resizing, and I'm not inclined to try doing potentially-destructive work today unless there's an urgent need for it

**Comment by stevekuznetsov** [comment]
We might also hit issues on monitoring -- we should deploy the proxy cache between grafana and prometheus so that our queries are simple.

**Comment by spiffxp** [comment]
/close
velodrome is down ref: https://github.com/kubernetes/test-infra/issues/16836
