### ISSUE TITLE
Velodrome does not capture merge data

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1568]
The merge rate fell to zero at the end of November: http://velodrome.k8s.io/dashboard/db/kubernetes-developer-velocity

**Comment by apelisse** [comment]
Yeah, I know, I removed it =)

**Comment by apelisse** [comment]
It's made on purpose and has been changed by #1094 

The data should be in the "prstats" series, with the value name "merged". Note that the difference with the former series is that this is the total count, while the other was a count of 1 when it happened.

**Comment by apelisse** [comment]
You should be able to get the same graph with that, but let me know if you want this to be reverted partially.

**Comment by fejta** [comment]
I mostly just think that graph is useless right now. Given that you changed how the data is stored, will you fix the graph to match it?
