### ISSUE TITLE
can't install kubetest

### ISSUE THREAD

**Issue by ozbillwang** [kubernetes/test-infra#15700]
**What happened**:

```
master $ go get -u k8s.io/test-infra/kubetest
package github.com/aws/aws-k8s-tester/ekstester: cannot find package "github.com/aws/aws-k8s-tester/ekstester" in any of:
        /usr/local/go/src/github.com/aws/aws-k8s-tester/ekstester (from $GOROOT)
        /opt/go/src/github.com/aws/aws-k8s-tester/ekstester (from $GOPATH)
```

**Anything else we need to know?**:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04

master $ kubectl get nodes
NAME     STATUS   ROLES    AGE   VERSION
master   Ready    master   30m   v1.17.0
node01   Ready    <none>   28m   v1.17.0
master $
```

**Comment by ozbillwang** [comment]
I also try with golang container, get same issue

```
$ cat Dockerfile
FROM golang:1.13
RUN go get -u k8s.io/test-infra/kubetest

$ docker build -t kubetest .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM golang:1.13
 ---> ed081345a3da
Step 2/2 : RUN go get -u k8s.io/test-infra/kubetest
 ---> Running in f131764f431e
package github.com/aws/aws-k8s-tester/ekstester: cannot find package "github.com/aws/aws-k8s-tester/ekstester" in any of:
	/usr/local/go/src/github.com/aws/aws-k8s-tester/ekstester (from $GOROOT)
	/go/src/github.com/aws/aws-k8s-tester/ekstester (from $GOPATH)
```

**Comment by danielvaughan** [comment]
I am experiencing a similar issue.
`
Linux version 4.15.0-72-generic (buildd@lcy01-amd64-026) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019
`
`kubectl get nodes
NAME   STATUS   ROLES    AGE   VERSION
pib    Ready    <none>   15d   v1.16.3-k3s.2
vm1    Ready    master   15d   v1.16.3-k3s.2
vm3    Ready    <none>   14d   v1.16.3-k3s.2
vm4    Ready    <none>   15d   v1.16.3-k3s.2
vm2    Ready    <none>   15d   v1.16.3-k3s.2
pid    Ready    <none>   14d   v1.16.3-k3s.2`

`go/src/k8s.io/test-infra/kubetest/eks.go:34:2: cannot find package "github.com/aws/aws-k8s-tester/ekstester" in any of:
	/usr/lib/go-1.10/src/github.com/aws/aws-k8s-tester/ekstester (from $GOROOT)
	/home/dvaughan/go/src/github.com/aws/aws-k8s-tester/ekstester (from $GOPATH)`

**Comment by mattjmcnaughton** [comment]
+1 I'm also unfortunately having the same issue when trying to use `go get -u`.

If its helpful, I worked around it by cloning the `test-infra` repo and then running `go install k8s.io/test-infra/kubetest`.

**Comment by ozbillwang** [comment]
Thanks, I can install now.

**Comment by danielvaughan** [comment]
I still have the problem. It looks like there was a rewrite of the  aws-k8s-tester in the last couple weeks that removed and renamed ekstester. See this commit: https://github.com/aws/aws-k8s-tester/commit/2e28fc402e559d4deccd08c072e5a97931e80929

**Comment by danielvaughan** [comment]
My bad - it looks like I was trying to build using go 1.10 without module support. Updated to 1.13 and now ok.

**Comment by gerrywastaken** [comment]
@ozbillwang this isn't wasn't fixed this is only a work around. I suggest reopening this.
```
go get k8s.io/test-infra/kubetest
package github.com/aws/aws-k8s-tester/ekstester: cannot find package "github.com/aws/aws-k8s-tester/ekstester" in any of:
	/usr/local/go/src/github.com/aws/aws-k8s-tester/ekstester (from $GOROOT)
	/home/gerry/go/src/github.com/aws/aws-k8s-tester/ekstester (from $GOPATH)
gerry@yox1:~/src/tools/misc$ go version
go version go1.13.6 linux/amd64
```

@danielvaughan I think you must have done something else to fix the issue as it still doesn't work on 1.13.6 (latest release right now).

**Comment by ozbillwang** [comment]
@gerrywastaken 

Did you see the Dockerfile i provide? follow it up, you shoukd be fine to install it

**Comment by torenware** [comment]
@ozbillwang How would I use this image to do a conformance test for my k8s cluster? Your image builds fine; I just don't see how to kick off a test run.
