### ISSUE TITLE
Docs-no-retest plugin should be deprecated

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#15737]
**What should be cleaned up or changed**:
The [`docs-no-retest`](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/docs-no-retest) plugin depends on [mungegithub](https://github.com/kubernetes/test-infra/pull/15709), which no longer exists in this repository.

It's also no longer needed as a plugin; Prow Jobs can be configured to only trigger when some subset of files changes.

It should, therefore, be deprecated and deleted.

**Comment by cblecker** [comment]
Thank you 🙏
