### ISSUE TITLE
Windows GCE tests are all failing to start clusters

### ISSUE THREAD

**Issue by pjh** [kubernetes/test-infra#15738]
Looking at https://testgrid.k8s.io/sig-windows#gce-windows-1.15&width=20, all test runs have been failing to start the cluster since 2019-12-18. Last passing run [here](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-stable2/1207469775299547138). Other Windows-GCE test jobs are also affected.

We did some refactoring in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-windows/windows-gce.yaml on that day and I expect this is the cause of the failures. I'm comparing the passing build log against a failing one from today, and I see:
  - `KUBELET_TEST_ARGS=--feature-gates=KubeletPodResources=false`, `KUBERNETES_NODE_PLATFORM=windows` and `KUBE_GCE_ENABLE_IP_ALIASES=true` are missing
  - This log line is missing: `Will download and extract kubernetes-node-windows-amd64.tar.gz from https://storage.googleapis.com/kubernetes-release-dev/ci/v1.15.8-beta.1.4+c53e0770eab343`
  - The actual failure point then seems to be:

```
  ... Starting cluster in us-west1-b using provider gce             
  ... calling verify-prereqs                                        
  ... calling verify-kube-binaries                                  
  ... calling verify-release-tars                                   
  !!! Cannot find kubernetes-node-windows-amd64.tar.gz
  ... calling kube-up                                               
  Project: gce-cvm-upg-1-4-1-3-ctl-skew
  Network Project: gce-cvm-upg-1-4-1-3-ctl-skew
  Zone: us-west1-b
  !!! Cannot find kubernetes-node-windows-amd64.tar.gz
  2020/01/03 00:16:16 process.go:155: Step './hack/e2e-internal/e2e-up.sh' finished in 726.956148ms
```

cc @YangLu1031

**Comment by pjh** [comment]
It looks like the environment variables set in [`preset-common-gce-windows`](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-windows/windows-gce.yaml#L3) are not being applied in the test job, but I have no idea why.

**Comment by pjh** [comment]
Ah, Yang pointed out that the master job is still working but the other jobs are failing. Looks like the [1.14](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/release-branch-jobs/1.14.yaml#L348), [1.15](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/release-branch-jobs/1.15.yaml#L357), etc. test jobs are configured by different yaml files. We need to update the presets in those other yaml files as well.

@YangLu1031 can you search test-infra for `preset-e2e-gce-windows` and add the new `preset-common-gce-windows` label in all those places as well?

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-windows#gce-windows-1.14&width=20
https://testgrid.k8s.io/sig-windows#gce-windows-1.15&width=20
https://testgrid.k8s.io/sig-windows#gce-windows-1.16&width=20
https://testgrid.k8s.io/sig-windows#gce-windows-1.17&width=20

have all started creating clusters and running tests again, calling this closed

/close
