### ISSUE TITLE
double presubmit triggering

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#15749]
**What happened**:

Prow ran presubmits twice simultaneously for a PR and merged it when one set passed then commented that the tests also failed...

**What you expected to happen**: We should not trigger presubmits doubly.

**How to reproduce it (as minimally and precisely as possible)**:

I _think_:
```
/lgtm
/ok-to-test
```
In one comment 🤷‍♂ 

**Please provide links to example occurrences, if any**:

https://github.com/kubernetes-sigs/kind/pull/1223#issuecomment-570653532

https://prow.k8s.io/?repo=kubernetes-sigs%2Fkind&pull=1223
https://prow.k8s.io/prowjob?prowjob=6df3a1a2-2e50-11ea-821b-5ef7b2587806
https://prow.k8s.io/prowjob?prowjob=6dc4568c-2e50-11ea-b3d2-d26d029d0afc

**Anything else we need to know?**:
testing-ops discussion https://kubernetes.slack.com/archives/C7J9RP96G/p1578076857024800
/area prow
/area prow/hook

**Comment by stevekuznetsov** [comment]
@BenTheElder can you paste `hook` logs for `trigger` plugin and the event GUID for that comment?

**Comment by BenTheElder** [comment]
there are event GUIDs in the prowjob links I think 

trigger logs
[container_cluster_name_prow__logs__2020-01-03T09-42.json.txt](https://github.com/kubernetes/test-infra/files/4020582/container_cluster_name_prow__logs__2020-01-03T09-42.json.txt)
