### ISSUE TITLE
Git cache can become corrupt and hence irrevocably unusable

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#15758]
It is possible for the git cache maintained by `prow/git.Client` to become corrupt. If this happens, it never recovers - all further operations for that repo that land on that pod will fail. This lead to `updateconfig` consistently failing due to a corrupt test-infra repo (it contained an empty file `FETCH_HEAD` and nothing else).

The git client should recover from corruption.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

@Katharine this seems important -- did we have a link to logs anywhere that detail how it got to this state?
