### ISSUE TITLE
Gubernator occasionally drops webhooks

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#1576]
This PR is merged: 

https://github.com/kubernetes/contrib/pull/2264

But it still shows up in my gubernator dashboard in the needs attention and outgoing sections.

![approvers_pr_gubernator](https://cloud.githubusercontent.com/assets/4854198/22036215/9779cbb6-dca7-11e6-93fe-b5d4f1fbe732.png)

**Comment by rmmh** [comment]
We could stuff the received message in a message queue, and then process updates separately. Retrying should handle the occasional out of memory conditions that break things currently.

**Comment by mtaufen** [comment]
Would it also work to just run a nightly cron that verifies the state machine behind PR dashboard is up-to-date with GitHub?

**Comment by liggitt** [comment]
what is the root cause? the dashboard missing events that would have flipped the state view to 'closed'?

**Comment by fejta** [comment]
Yes, gubernator misses a tiny fraction of events.

**Comment by fejta** [comment]
Add metrics for this?

**Comment by rmmh** [comment]
This should be fixed by #5721. I need to clean up the old stale PRs, though!

**Comment by fejta** [comment]
woo!
