### ISSUE TITLE
Add a Prow command to create branches

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/test-infra#15779]
## What to add

Consider adding a Prow command to create new branches.

## Why it matters

SIG Docs handles localizations for Kubernetes docs. 

When SIG Docs adds a new localization, we add the team's leaders to a [repo team with write permissions](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml#L260-L293) so that leaders can create long-running branches for team collaboration.

As the number of localizations increases, the number of people with write access to k/website also increases. This poses a security risk that worsens at scale. We've already seen two incidents in the past two months of contributors using write permissions to bypass Prow:

- https://github.com/kubernetes/org/pull/1293
- https://github.com/kubernetes/org/pull/1468

We need to minimize the number of people with write permissions to k/website while preserving the ability of localization teams to work on collaborative branches.

Thanks in advance for your consideration!

## Additional context

[#sig-docs Slack](https://app.slack.com/client/T09NY5SBT/C1J0BPD2M/thread/C1J0BPD2M-1578346017.080000)

cc @jimangel @kbarnard10 @cblecker

**Comment by justaugustus** [comment]
@zacharysarah -- This is timely! Releng is discussing possibilities here: https://github.com/kubernetes/release/issues/857

cc: @kubernetes/release-engineering

**Comment by zacharysarah** [comment]
This is still important.

/remove-lifecycle stale
/lifecycle frozen
/priority important-longterm

**Comment by cblecker** [comment]
/remove-lifecycle frozen

We haven't decided if/how we would do this, so it doesn't really qualify for frozen.

I'm not sure what the workflow would even look like for this.. we don't really do repo-scoped commands. They are all issue or PR scoped.

**Comment by stevekuznetsov** [comment]
If we implement branch creation as a plugin, we can just enable the plugin on a single repo.

**Comment by cblecker** [comment]
@stevekuznetsov That's not what I mean. I mean where would you issue the command to create a branch?
