### ISSUE TITLE
Gubernator seems... slow(?) in refreshing PR statuses

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/test-infra#15799]
**What happened**:
I'm not sure exactly what the refresh rate for Gubernator is, but lately it seems slower than usual
![Screenshot from 2020-01-07 14-10-46](https://user-images.githubusercontent.com/567897/71921823-9e8a4900-3157-11ea-9b5b-b2c7652183ac.png)

From a [merged PR](https://github.com/kubernetes/sig-release/pull/935) that has since left my queue.

There's also a PR that has been stuck in my "Incoming" section [since September](https://github.com/kubernetes/kubernetes/pull/82496#issuecomment-559758687).

**Comment by justaugustus** [comment]
Another example:
![Screenshot from 2020-01-20 22-12-09](https://user-images.githubusercontent.com/567897/72772477-00c06080-3bd2-11ea-961e-3b5b538c5677.png)

^^ an issue that was recently updated

![Screenshot from 2020-01-20 22-11-44](https://user-images.githubusercontent.com/567897/72772544-2b121e00-3bd2-11ea-9832-2371a77e2eac.png)

^^ my Gubernator listing of the issue around the same time (note my system time at the top of the screenshot)

**Comment by justaugustus** [comment]
+ Gubernator OWNERS:
/assign @ibzib @Katharine @rmmh @stevekuznetsov

**Comment by justaugustus** [comment]
I also noticed a PR assigned to me today that did not get picked up for review in Gubernator. :/

**Comment by BenTheElder** [comment]
I think @ibzib works on apache beam now, and @rmmh on mako.dev ... we should probably update owners 🙃

**Comment by BenTheElder** [comment]
Katharine is semi-moved on now (new team but still around ish), rrmh and ibzib seem much more moved on. PRing..
