### ISSUE TITLE
Add a prow job blacklist

### ISSUE THREAD

**Issue by Katharine** [kubernetes/test-infra#15856]
Sometimes I would like to be able to disable a bunch of prowjobs for infrastructure reasons (e.g. #15854). However, while finding the jobs may be relatively easy, actually disabling the jobs is difficult, because it requires editing large numbers of jobs, which may then fail tests because they're auto-generated, etc. Undoing the change may then also be a pain.

It would be easier to be able to just edit a list of jobs that prow should refuse to start under any circumstances.

/area prow

**Comment by BenTheElder** [comment]
@cjwagner thoughts?

**Comment by cjwagner** [comment]
Is the only benefit of this that we can disable periodic jobs without losing the history of when the last run was? Deleting jobs from config seems equally as difficult as declaring a blacklist.

**Comment by BenTheElder** [comment]
It's not equally difficult for sharded jobs I guess?
E.g. a broke presubmit?

**Comment by cjwagner** [comment]
Thats fair, but it still seems like it would be pretty easy to just delete all the shards? I don't change job config as much or at as large a scale as you or Katharine so I haven't really run into this pain point myself.

We could add a blacklist to the Prow config and make Tide, Horologium, and the trigger plugin respect it, but I'm wondering how helpful this would actually be so we can prioritize it against other work.

**Comment by BenTheElder** [comment]
I haven't actually needed this recently, and i'm not sure how much it would have helped in the past.

let's close it for now.
