### ISSUE TITLE
Failed kops runs due to hash mismatch / changing assets

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#1589]
We had two kops runs fail (in a row!) where the cloud-init-output.log indicated that the kubelet SHA was not matching:

2587 https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/2587/
2588 https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/2588/ 

This does happen when the builder changes the files while kops is running.  https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-build/

The time of run 720 matches very plausibly with the run time of 2587.  But for 2588, it started at the same time as 721, so should have booted before build 721 finished.

Also bizarre is that the expected sha and actual sha was the same for both runs.  Is there an HTTP proxy/cache which the tests are running through?

cc @zmerlynn

**Comment by fejta** [comment]
What makes the kops jobs fail when ci-kubernetes-build completes?

**Comment by fejta** [comment]
AKA ideally I would like/expect the kops deployment to be robust to build jobs running and completing concurrent with AWS jobs.

That seems like the simplest/best solution here.

**Comment by justinsb** [comment]
So my belief is that we are pushing different versions of e.g. kubelet to the same bucket.

`https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build/719/build-log.txt`

`https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build/720/build-log.txt`

Both upload to `gs://kubernetes-release-dev/ci/v1.6.0-alpha.0.3506+9dd96e31204ea8/bin/linux/amd64/kubelet`

When kops runs, it records the SHA of the kubelet at the source, and then it validates it when it downloads it on the nodes.  But minutes could pass in between kops starting the server and the instance starting up and downloading kubelet.  My belief is that the builder job is replacing kubelet (?) with a version with a different SHA, and thus causing kops to detect the mismatch and fail.

**Comment by ixdy** [comment]
Yes, Jenkins has been occasionally re-triggering builds at the same git commit recently, for reasons I don't understand. Because the build times are different, and because we embed build times in the binaries, the hashes of the binaries won't match.

**Comment by ixdy** [comment]
this is a dupe of #1499, I think

**Comment by justinsb** [comment]
Ah - it is a dup of #1499.  Thank you @ixdy 

I do agree that kops should probably tolerate this @fejta (e.g. SHA hashes are certainly much more valuable if we pull the file over HTTP), but OTOH I don't just want to sweep it under the rug!
