### ISSUE TITLE
Scaledown and dynamic resource lifetime is not enforced

### ISSUE THREAD

**Issue by chemikadze** [kubernetes/test-infra#15906]
**What happened**:

Change #13990 have broken support for dynamic resource lifetime and scaledown.

Previously, config was polled, resulting in periodic checks of dynamic resource lifetimes, playing enforcement role for them https://github.com/kubernetes/test-infra/blob/d319b3f3b92d51b0fcea77b199f39be68401b19a/boskos/ranch/storage.go#L291

After mentioned PR was merged, lifetime is enforced only when Ranch is restarted, or config is changed.

**What you expected to happen**:

Lifetimes should continue to be enforced, or if they are not supported any more - deprecated or removed.

**How to reproduce it (as minimally and precisely as possible)**:

Creating dynamic resource with short lifetime shows that resource is not deleted after expiration time.

**Please provide links to example occurrences, if any**:

n/a

**Comment by ixdy** [comment]
I started to look into this, and thought we could add back a periodic goroutine which would just look at dynamic resources and delete those that had expired, but I think this won't be a sufficient solution: if a config update removes a dynamic resource type, but there are currently dynamic resources that are leased, then we won't remove the DRLC when the config is processed. We would need to fully process the configuration again later to realized that we need to remove the DLRC and dynamic resources associated with the change.

Probably the best option is to partially roll back #13990, periodically parsing the configuration (though we can leave the on-changed bits). If locking everything every 10m is too much, we can reduce the frequency (or at least make it configurable).

**Comment by chemikadze** [comment]
Taking into account it's not very frequently used feature (I did not find real config with lifetimes being set in this repo, istio/test-infra or knative/test-infa), having periodic config updates disabled by default with ability to enable it would be a reasonable compromise.

**Comment by ixdy** [comment]
another option might be to add a way to mark DRLCs in lame-duck mode; we'd use them to continue to delete any existing dynamic resources, but not attempt to recreate any resources. Once all associated dynamic resources are deleted, they could be completely removed.

**Comment by ixdy** [comment]
I found a somewhat elegant way to do what I described in https://github.com/kubernetes/test-infra/issues/15906#issuecomment-577832602: when a DRLC is deleted, we can set its MinCount and MaxCount to 0. This will gracefully delete any associated dynamic resources, and once they're all gone, we can then deleted the DLRC, too.

**Comment by ixdy** [comment]
This issue is mostly concerned with dynamic resources, but there's an issue with static resources as well - if a static resource is removed from the config, but it's currently in use, it won't be deleted. But since we don't ever periodically resync the config, we may never delete that resource.
