### ISSUE TITLE
Allow Branches and SkipBranches for jobs in repo

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/test-infra#15913]
Currently, jobs defined in repo are not allowed to declare branches and skip branches patterns.

https://github.com/kubernetes/test-infra/blob/master/prow/config/inrepoconfig.go#L123-L140

This makes it difficult to version jobs that run only on specific branches.

I don't see any technical reason to forbid branches and skip branches for jobs in repo, allowing them would be useful to let the jobs evolve naturally in git, it could be modified, merged, reviewed, etc...

Maybe we could add a config element to enable/disable this behavior if needed.

**Comment by stevekuznetsov** [comment]
Not sure I follow -- the branch the job is configured in is the branch on which it runs. The file in `master` applies to `master` and `master` only.

/assign @alvaroaleman

**Comment by eddycharly** [comment]
Let’s put it simply, imagine you have a job that must run only on master.

When you create a branch from master, you’re not going to delete the job before pushing to the new branch right ?

It makes sense that the job exists in multiple branches even if it applies to only one.

**Comment by eddycharly** [comment]
@stevekuznetsov is it more clear ? Shall I go ahead and open a pr ?

This makes the feature pretty hard to use, especially with postsubmit jobs when not using forks.

**Comment by alvaroaleman** [comment]
Yeah, so while we initially assumed this doesn't make sense, Loodse also run into a need for this pretty quickly, as there the usecase of having a rolling release branch that gets forwarded from a different branch exists and the two do not have an identical job config.

IMHO we should loosen the validation and allow this, but make the `branches` property default to the current branch if unset. @stevekuznetsov do you have any objections to that?

CC @xrstf @kdomanski

**Comment by eddycharly** [comment]
@alvaroaleman i took a little time to work on this.

> make the branches property default to the current branch if unset

Can you elaborate on this ? Defaulting to the current branch or leaving it unset should not change anything as the job is coming from the current branch anyway, am i right ?

**Comment by alvaroaleman** [comment]
> Can you elaborate on this ? Defaulting to the current branch or leaving it unset should not change anything as the job is coming from the current branch anyway, am i right ?

The reason is that the validation verifies that there is only one job with a given name per org/repo/branch. But thinking about this, we do not have this info available anyways, so I guess making inrepoconfig jobs on any branch conflict with a job of the same name in the static config in any other branch is okay,

**Comment by eddycharly** [comment]
Thanks for your explanations.
Don't hesitate to comment on the PR https://github.com/kubernetes/test-infra/pull/16068
I simply removed the constraints on branches and skip branches.

**Comment by eddycharly** [comment]
Closed by https://github.com/kubernetes/test-infra/pull/16068
