### ISSUE TITLE
Boskos client ReleaseOne is not usable if process is restarted

### ISSUE THREAD

**Issue by chemikadze** [kubernetes/test-infra#15910]
**What happened**:

ReleaseOne performs local check for whether resource was allocated by same client previously, and fails if it was not. After release, it makes client forget such association.
Release is not doing checks and is not making sure that association is removed.

At the same time, all Allocate methods are adding associations. This means, there is no consistent way to release resource in case when client was recreated for some reason (for example, process restart). One known workaround to make sure object is released and there is no memory leak is to use Release if ReleaseOne failed to cover restart case, however quite error-prone without knowledge of internals.

**What you expected to happen**:

ReleaseOne not to fail if client state is out of sync or Release to clean up client state.

**How to reproduce it (as minimally and precisely as possible)**:

Create two boskos clients, allocate in one client, and run release from another client.

**Comment by ixdy** [comment]
Moving to https://github.com/kubernetes-sigs/boskos/issues/16.
/close
