### ISSUE TITLE
Prow shouldn't trigger jobs that need rebases

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#1597]
Having 8 failure comments because a PR doesn't merge cleanly is silly. It would be better to do the needs-rebase logic -- maybe pull it out of mungegithub?

**Comment by spxtr** [comment]
It's tricky to pull it entirely out of mungegithub because if master changes then we don't get an event for a PR that becomes unmergeable.

**Comment by fejta** [comment]
/assign @spxtr 

This seems out of date
