### ISSUE TITLE
boskos leased the same resource to two owners

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#15985]
**What happened**: Openshift reported that Boskos leased the same resource to two different jobs: https://github.com/openshift/release/issues/6795

We have a gratuitous amount of locking, so in theory this shouldn't happen, but I think I may have figured out what may have happened:

1. `/aquire` is called by two different jobs at the same time. We have a [global lock](https://github.com/kubernetes/test-infra/blob/5e7071bdbd0408d480d7cab02a5ff0757e945dae/boskos/ranch/ranch.go#L125), so at least one of these waits while the other proceeds.
1. The first job [gets all resources](https://github.com/kubernetes/test-infra/blob/5e7071bdbd0408d480d7cab02a5ff0757e945dae/boskos/ranch/ranch.go#L133), which involves [listing](https://github.com/kubernetes/test-infra/blob/5e7071bdbd0408d480d7cab02a5ff0757e945dae/boskos/crds/crd_storage.go#L74) all resources on the Kubernetes API server, then [converting](https://github.com/kubernetes/test-infra/blob/5e7071bdbd0408d480d7cab02a5ff0757e945dae/boskos/crds/crd_storage.go#L80) to `common.Item`.
1. It then selects a free resource, fills in fields, and [calls](https://github.com/kubernetes/test-infra/blob/5e7071bdbd0408d480d7cab02a5ff0757e945dae/boskos/ranch/ranch.go#L154) `r.Storage.UpdateResource`.
1. `UpdateResource` in turn [calls](https://github.com/kubernetes/test-infra/blob/5e7071bdbd0408d480d7cab02a5ff0757e945dae/boskos/ranch/storage.go#L101) `s.resources.Update`.
1. The CRD-based `Update` method first [gets](https://github.com/kubernetes/test-infra/blob/5e7071bdbd0408d480d7cab02a5ff0757e945dae/boskos/crds/crd_storage.go#L53) the current object from the Kubernetes API server, then [updates fields of this object locally using the item](https://github.com/kubernetes/test-infra/blob/5e7071bdbd0408d480d7cab02a5ff0757e945dae/boskos/crds/crd_storage.go#L57) before [updating the object](https://github.com/kubernetes/test-infra/blob/5e7071bdbd0408d480d7cab02a5ff0757e945dae/boskos/crds/crd_storage.go#L58) on the Kubernetes API server.
1. Assuming the update was successful, we release the lock and return the updated resource.

So what went wrong? I think the issue is in steps 2 and 5.

When we get resources from the Kubernetes API server, we convert them from Kubernetes objects to Boskos Items, but lose the `resourceVersion` in the process.
When we get the Kubernetes object again in step 5, we have no guarantees that we're actually updating the correct version of the object.

From reading the consistency guarantees of etcd, I think a perverse case could look like:
1. `/acquire` from owner 1 wins the lock and updates the resource in the API server.
1. `/acquire` from owner 2 then starts working. The initial list operation gets the old version of the Kubernetes object, but requesting the resource again while updating returns the new version of the Kubernetes object. Since we discarded the `resourceVersion`, we don't realize that we're updating the wrong version, and no conflict is reported.

cc @stevekuznetsov 

/area boskos

**Comment by alvaroaleman** [comment]
This shouldn't be possible to happen anymore now that https://github.com/kubernetes/test-infra/pull/16367 is in. Ranch now uses the CRD types internally and update requests with outdated RV will fail.

/close
