### ISSUE TITLE
Spyglass returns 403 for `static` files on private instance

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#16002]
**What happened**:
Spyglass is returning a **403** when fetching `static` files on a private Deck instance that is behind an oauth proxy for some ~non-Google~ users.

**What you expected to happen**:
I expect Spyglass to return a **200** when fetching `static` files, similar to the retrieval of other resources.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure an oauth proxy for a private Deck instance ([example](https://github.com/istio/test-infra/blob/830ea2859027294013b5340950a0fba8ca0b7a95/prow/cluster/deck_private_deployment.yaml)).
2. Ensure you are not signed in with a Github or Gmail account that may already have access to the logs/resources and are associated with Google employment. 
2. Navigate to a Spyglass view of a job (i.e. `/view/gcs/...`) .
3. Static files will not load; the error will be a **403**.

**Please provide links to example occurrences, if any**:
![Screen Shot 2020-01-23 at 2 16 45 PM](https://user-images.githubusercontent.com/9957358/73025460-80257e00-3de4-11ea-9e9b-234eaaa57e3e.png)
<img width="832" alt="Screen Shot 2020-01-23 at 2 17 20 PM" src="https://user-images.githubusercontent.com/9957358/73025461-80257e00-3de4-11ea-9ea8-1dcb414822a3.png">

/assign

**Comment by Katharine** [comment]
> I expect Spyglass to return a 200 and use a GCS credentials file (i.e. --gcs-credentials-file) where necessary when fetching static files, similar to the retrieval of other resources.

static files are not retrieved from GCS (or in any way related to GCS); they're served by deck and requested by simply including them with `<script>` tags, etc. It would not be meaningful to use GCS credentials here.

I imagine this is related to the (intentional) sandboxing of spyglass lenses.

**Comment by clarketm** [comment]
> > I expect Spyglass to return a 200 and use a GCS credentials file (i.e. --gcs-credentials-file) where necessary when fetching static files, similar to the retrieval of other resources.
> 
> static files are not retrieved from GCS (or in any way related to GCS); they're served by deck and requested by simply including them with `<script>` tags, etc. It would not be meaningful to use GCS credentials here.
> 

Thanks for the clarification. After looking at the code and seeing how the static files are served, I realize GCS auth is not to blame. I further edited the answer to make this more clear.

> I imagine this is related to the (intentional) sandboxing of spyglass lenses.

I am not sure what you mean by sandboxing here or why this specific issue is only affecting static files and only for non-Googlers on a particular Prow instance. Can you clarify a bit?

**Comment by Katharine** [comment]
Spyglass lenses are [sandboxed](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/template/spyglass.html#L42) to prevent them from breaking out of their sandbox (which ensures they only use the expected APIs and, once we have remote lenses, they cannot do anything too questionable).

A key part of this sandboxing is that they have a different origin (more specifically, it is `null`). I can imagine this causing issues trying to authenticate to the OAuth proxy — and indeed, there is a comment about cross-site requests running off the top of that screenshot.

I have no idea how this would relate to whether you are or are not a googler, though.

**Comment by Katharine** [comment]
The link goes to https://chromestatus.com/feature/5088147346030592, which says how cookies behave by default is switching in Chrome 80. The current release version is 79, so if they are using a canary version they would see new behaviour.

Perhaps you could try adjusting your proxy to specify `SameSite=None` on your cookies.

**Comment by clarketm** [comment]
> Spyglass lenses are [sandboxed](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/template/spyglass.html#L42), which ensures they only use the expected APIs and, once we have remote lenses, they cannot do anything too questionable.
> 
> A key part of this sandboxing is that they have a different origin (more specifically, it is `null`). I can imagine this causing issues trying to authenticate to the OAuth proxy — and, perhaps relatedly, there is a comment about cross-site requests running off the top of that screenshot. Just a guess though.
>
> says how cookies behave by default is switching in Chrome 80. The current release version is 79, so if they are using a canary version they might see new behaviour.
> 
> Perhaps you could try adjusting your proxy to specify `SameSite=None` on your cookies.

I think you are correct about the **403** being caused by the Oauth proxy. Indeed, setting `SameSite=None` sounds like a good idea as well. Also, upon further investigation, being a non-Googler appears to be a mere coincidence. I was able to reproduce this *exact* issue by *enabling* **Block third-party cookies** in Chrome on my machine.

![image](https://user-images.githubusercontent.com/9957358/73053418-89423980-3e3c-11ea-954e-9f66e74b61a5.png)

![image](https://user-images.githubusercontent.com/9957358/73053602-04a3eb00-3e3d-11ea-97a5-c0e40795869b.png)

**Comment by stevekuznetsov** [comment]
cc @petr-muller @droslean  -- they are using `spyglass` behind a Proxy

**Comment by afirth** [comment]
> The link in the screenshot goes to https://chromestatus.com/feature/5088147346030592, which says how cookies behave by default is switching in Chrome 80. The current release version is 79, so if they are using a canary version they might see new behaviour.
> 
> Perhaps you could try adjusting your proxy to specify `SameSite=None` on your cookies.

Thanks for the tip!
adding `OAUTH2_PROXY_COOKIE_SAMESITE:    none` for oauth2 proxy fixes this for chrome users.
