### ISSUE TITLE
peridoc kind ipv6 master jobs are not running since Jan 7th

### ISSUE THREAD

**Issue by aojea** [kubernetes/test-infra#16025]
**What happened**:

The periodic ipv6 kind jobs are not running 

https://testgrid.k8s.io/sig-testing-kind

It seems that his is happening since Jab 7th

https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-ipv6

This is a PR related at that time, but the other jobs that were modified are working 🤷‍♂ 

https://github.com/kubernetes/test-infra/pull/15798

**Comment by Katharine** [comment]
I've cleaned up all the `*kind*` jobs I could find that have been running since around then.

The root cause is a combination of @BenTheElder removing the dedicated nodepool they used to run in, and #16034, which prevents these stuck jobs from ever being cleaned up so they can be run again.

**Comment by aojea** [comment]
Thanks :smile:

**Comment by BenTheElder** [comment]
Thans!
