### ISSUE TITLE
boskos: changing type of a static resource in config doesn't update storage

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#16047]
**What happened**: 
We renamed the type of some of our static resources to work around a bug in the janitor.
(That bug: we had a group of projects that didn't end in `-project`, and thus the janitor was passing the wrong flag: https://github.com/kubernetes/test-infra/blob/761c11f53ddb7dde3fcc4073a7e3b9015554fe7f/boskos/janitor/janitor.go#L92-L99
)

After applying the config, the old type still remained in storage (in the Kubernetes objects).

**What you expected to happen**:
Boskos would update storage (in the Kubernetes objects) reflecting the new type. 

**How to reproduce it (as minimally and precisely as possible)**:
I wrote a simple unit test that reproduces this failure: https://github.com/ixdy/kubernetes-test-infra/commit/d6714a6559866b095c50437a98dc1e7be28ba932

It looks like when updating static resources, we just check to see whether the resources specified in the config exist in storage and vice-versa, only looking at the resource names. We do not consider that other metadata (such as type) may have changed.

Our planned workaround is to delete the resources from the config, then re-add them.

/area boskos

**Comment by ixdy** [comment]
> Our planned workaround is to delete the resources from the config, then re-add them.

This doesn't entirely work. If you just apply a config with the resources deleted, Boskos won't delete any that are in-use. To remove them, you'd need to explicitly delete them using kubectl.

**Comment by stevekuznetsov** [comment]
There are quite a lot of config renames/edits that do not get appropriately reflected in cluster state. Notably reducing the size of a dynamic resource used to not remove the CRDs? I think we might need to revisit how that code works.

**Comment by ixdy** [comment]
I think the issues with dynamic resources are described in #15906 (and hopefully fixed by #16021), but none of that touches static resources.

**Comment by ixdy** [comment]
Moving to https://github.com/kubernetes-sigs/boskos/issues/18.
/close
