### ISSUE TITLE
Branchprotector: allow force push

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#16077]
**What would you like to be added**:
A configuration option for [**branchprotector**](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/branchprotector) to grant all users with push access the ability to force-push to a protected branch by enabling `Allow force pushes`.

https://github.blog/changelog/2019-12-04-expanded-branch-protection-rules/

**Why is this needed**:
It offers flexibility in that it allows *trusted* users to force push to protected branches *if needed*. 

**e.g.**
I use branch protection on repo B and I have an automated job that mirrors (or rebases) repo A (and all its refs) to repo B on a daily cadence to ensure it is in sync and it needs to be able to rewrite history which requires a force push.

/help
/good-first-issue

**Comment by sergioescalanteIBM** [comment]
I'd like to work on this

**Comment by clarketm** [comment]
Thanks @sergioescalanteIBM!  

/assign @sergioescalanteIBM
/remove-help
