### ISSUE TITLE
gcsk8sreporter regularly can't find BuildID

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#16086]
**What happened**:
Frequent logs like this in Prow production:

```
jsonPayload: {
  component: "gcsk8sreporter"   
  file: "prow/crier/reporters/gcs/kubernetes/reporter.go:90"   
  func: "k8s.io/test-infra/prow/crier/reporters/gcs/kubernetes.(*gcsK8sReporter).Report"   
  level: "warning"   
  msg: "Not uploading "dd9368b3-4447-11ea-b7c6-361372b49446" (pull-cluster-api-provider-vsphere-e2e#) because we couldn't find a destination: cannot get job destination for job with no BuildID"   
 }
```

**Comment by stevekuznetsov** [comment]
BuildID is given to the job after it is created, when it starts to execute, are we racing with that?

**Comment by Katharine** [comment]
gcsk8sreporter only reports on terminated jobs, so this would require a job to reach termination and still not have a build ID.

Aborted jobs maybe?

**Comment by Katharine** [comment]
[that job](https://prow.k8s.io/prowjob?prowjob=dd9368b3-4447-11ea-b7c6-361372b49446) is indeed a) aborted, and b) lacking a build ID
