### ISSUE TITLE
Prow issue:

### ISSUE THREAD

**Issue by sovereignoshan** [kubernetes/test-infra#16081]
kubectl top nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get nodes.metrics.k8s.io)

**Comment by alvaroaleman** [comment]
This sounds more like its an error in your cluster rather than a prow issue, check `kubectl get apiservice` to find out whats up with your metrics service.

Closing this for now, feel free to open another issue if you find problems in Prow itself :)

/close
