### ISSUE TITLE
cannot run job with gke provider

### ISSUE THREAD

**Issue by cofyc** [kubernetes/test-infra#16092]
**What happened**:

cannot run e2e job with gke provider.

**What you expected to happen**:

e2e job should succeed.

**How to reproduce it (as minimally and precisely as possible)**:

start a kubetest job with following parameters:

```
--provder=gke
--extract=gke-latest
--gke-environment=staging
```

**Please provide links to example occurrences, if any**:

see recent `ci-kubernetes-e2e-gke-canary` jobs: https://prow.k8s.io/?job=ci-kubernetes-e2e-gke-canary.

`https://storage.googleapis.com/gke-release-staging/kubernetes/release/v1.15.8-gke.3/kubernetes.tar.gz` does not exist anymore.

**Anything else we need to know?**:

`--extract=gke-default` cannot work too, because `gs://kubernetes-release-dev/ci/latest-1.13.txt` is not available now.

```
2020/02/01 05:31:04 process.go:155: Step 'gcloud container get-server-config --project=yechengfu-1369 --zone=us-central1-f --format=value(defaultClusterVersion)' finished in 936.973563ms
2020/02/01 05:31:04 process.go:153: Running: gsutil cat gs://kubernetes-release-dev/ci/latest-1.13.txt
CommandException: No URLs matched: gs://kubernetes-release-dev/ci/latest-1.13.txt
2020/02/01 05:31:07 process.go:155: Step 'gsutil cat gs://kubernetes-release-dev/ci/latest-1.13.txt' finished in 2.269316722s
2020/02/01 05:31:07 main.go:316: Something went wrong: failed to acquire k8s binaries: error during gsutil cat gs://kubernetes-release-dev/ci/latest-1.13.txt: exit status 1
2020/02/01 05:31:07 e2e.go:82: err: exit status 1
```

xref: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/166

**Comment by krzyzacy** [comment]
Please consider use [kubetest2](https://github.com/kubernetes/test-infra/tree/master/kubetest2) instead, kubetest is mostly dead and not maintained.

cc @amwat
