### ISSUE TITLE
Configurator: non-deterministic output

### ISSUE THREAD

**Issue by clarketm** [kubernetes/test-infra#16110]
**What happened**:
Sometime after commit d5d7ce3eb0ffe35c899fe9358586cdffb6525899, when the `configurator` is run multiple times with the same input it produces non-deterministic `yaml` results. The output appears to be *semantically*-equivalent but not *byte*-equivalent, meaning the ordering is non-deterministic.  

**What you expected to happen**:
Idempotence (i.e. byte equivalence); multiple `configurator` invocations with the same inputs should produce the same output. Alternatively, provide a flag to lexicographically sort the results (e.g. `--sort`). 

**How to reproduce it (as minimally and precisely as possible)**:
Call `configurator` multiple times using the same inputs and compare the diff of the outputs.

```shell
# 1. setup
$ git clone https://github.com/istio/test-infra.git istio_test-infra
$ cd istio_test-infra
$ go get k8s.io/test-infra/testgrid/cmd/configurator@master

# 2. first run
$ go run k8s.io/test-infra/testgrid/cmd/configurator --prow-config prow/config.yaml --prow-job-config prow/cluster/jobs --output-yaml --yaml testgrid/default.yaml --oneshot --output testgrid/istio.gen-1.yaml

# 3. second run
$ go run k8s.io/test-infra/testgrid/cmd/configurator --prow-config prow/config.yaml --prow-job-config prow/cluster/jobs --output-yaml --yaml testgrid/default.yaml --oneshot --output testgrid/istio.gen-2.yaml

# 4. compare diff
$ diff --brief testgrid/istio.gen-1.yaml testgrid/istio.gen-2.yaml
> Files testgrid/istio.gen-1.yaml and testgrid/istio.gen-2.yaml differ
```

> **Note:** omit the `--brief` flag from the `diff` command in **step 4** for a comprehensive list of differences.

**Comment by chases2** [comment]
This is a known issue; see #13624

It's still affecting us, and affecting users of Transfigure (such as Istio) the most. I think a way to sort is probably the best way to resolve this, and I'm pretty sure that nothing else relies on the order of deserialization.

**Comment by clarketm** [comment]
/close
Duplicate of #13624
