### ISSUE TITLE
package github.com/googleapis/gnostic/OpenAPIv2: cannot find package 

### ISSUE THREAD

**Issue by zyc-ai** [kubernetes/test-infra#16116]
**What happened**:

package github.com/googleapis/gnostic/OpenAPIv2: cannot find package "github.com/googleapis/gnostic/OpenAPIv2" in any of:
        /usr/local/go/src/github.com/googleapis/gnostic/OpenAPIv2 (from $GOROOT)
        /home/zc/go/src/github.com/googleapis/gnostic/OpenAPIv2 (from $GOPATH)

**What you expected to happen**:

install

**How to reproduce it (as minimally and precisely as possible)**:

go get -u k8s.io/test-infra/prow/cmd/tackle && tackle

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by poothia** [comment]
it's breaking due to the change made in https://github.com/googleapis/gnostic/pull/155 . until this is fixed in client pin your go client to "k8s.io/client-go v0.17.0" in your go-mod.

**Comment by StarCoral** [comment]
I have same problem ,
and I tried the way from   @boyan-soubachov  [ googleapis/gnostic#155](https://github.com/googleapis/gnostic/pull/155)
use the command `go get github.com/googleapis/gnostic@v0.4.0` , and it can be solved.

Thank you!~

> it's breaking due to the change made in [googleapis/gnostic#155](https://github.com/googleapis/gnostic/pull/155) . until this is fixed in client pin your go client to "k8s.io/client-go v0.17.0" in your go-mod.

**Comment by boyan-soubachov** [comment]
Not a problem. I think the initial reason is that (mistakenly) running a ‘go get -u’ on your module that includes it forces an upgrade which moves gnostic to the incompatible version. IMO it would be good to update our dependency as a nice to have but that’s up to the kubernetes team to decide whether it’s worth it. 🙂

**Comment by divoxx** [comment]
We are also having this issue when building `k8s.io/apimachinery/` pinned to the `kubernetes-1.14.9` tag, since that's the kubernetes version we are working with (AWS EKS).

Since this is a breaking change with very wide surface, is it safe to assume the fix will be back ported to those `kubernetes-*` branches?

**Comment by nyetwurk** [comment]
```.go/pkg/mod/k8s.io/client-go@v0.17.11/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.5.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2```

```
        k8s.io/api v0.18.8
        k8s.io/apimachinery v0.18.8
        k8s.io/client-go v0.17.11
        k8s.io/utils v0.0.0-20200821003339-5e75c0163111 // indirect
```
```
	github.com/googleapis/gnostic v0.5.1 // indirect
```

Also doesn't work with v0.4

**Comment by BenTheElder** [comment]
Hi, this is the wrong repo to discuss how Kubernetes handles dependencies. 

1.14 is not supported by open source and hasn't been. In fact 1.16 just wrapped up.

This repo is not go getabble unfortunately. You need to clone the repo and build locally so the replace statements are respected.

**Comment by lboix** [comment]
Here is a workaround that could help, especially if you are using Kubernetes 1.14 : https://github.com/kubernetes/client-go/issues/741#issuecomment-807368949
