### ISSUE TITLE
Allow PR approvers to demand a squash-merge

### ISSUE THREAD

**Issue by thockin** [kubernetes/test-infra#16124]
**What would you like to be added**:

It would be nice to be able to review PRs as a series of commits, and decide "this should be squashed".  When I say `/approve` I could also say `/squash-on-merge` or something, which the merger process would respect and call the right GitHub API.

https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

**Why is this needed**:

I review a lot of PRs and often this would make my flow easier and avoid one round-trip with contributors.  If the commits all look good on their own, this ensures that nothing changes when it gets squashed.

For example: https://github.com/kubernetes/kubernetes/pull/87535 moves files and creates symlinks, which github does not detect as file-rename.  If this were 2 commits (1 to move files, 2 to add symlinks) it would be WAY easier to review.  I would just say `/squash-merge` and trust the bots for the rest.

xref #9514 but not the same

**Comment by stevekuznetsov** [comment]
This is currently possible by adding the `tide/merge-method-squash` label to the PR. Are you specifically looking for a comment-command to do this?

/cc @cjwagner

**Comment by cjwagner** [comment]
> Are you specifically looking for a comment-command to do this?

We could achieve this today with a `/label tide/merge-method-squash` command via the `label` plugin.

**Comment by thockin** [comment]
This is awesome!  I am going to save it as a canned response.

**Comment by thockin** [comment]
Woops!

https://github.com/kubernetes/kubernetes/pull/87535

@thockin: The label(s) /label tide/merge-method-squash cannot be applied. These labels are supported: api-review, community/discussion, community/maintenance, community/question, cuj/build-train-deploy, cuj/multi-user, platform/aws, platform/azure, platform/gcp, platform/minikube, platform/other

**Comment by cjwagner** [comment]
@thockin Looks like the label command isn't configured to support that label. I made a PR to add it to the config (https://github.com/kubernetes/test-infra/pull/16160), but it may cause problems if misused on repos that don't support the requested merge method so we should probably address that first. (ref: https://github.com/kubernetes/test-infra/issues/16159)

It looks like people have been using the label in some repos by applying it manually: https://github.com/search?q=org%3Akubernetes+label%3Atide%2Fmerge-method-squash&unscoped_q=label%3Atide%2Fmerge-method-squash
