### ISSUE TITLE
PR dashboard: Change sort order?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#1612]
I'd like to sort by "has been waiting for my attention longest" so that I give everyone equally bad service instead of randomly giving some people fast reviews and ignoring some people.

**Comment by lavalamp** [comment]
I'd also like to sort by size sometimes. (XS gets same-day service, etc)

**Comment by justaugustus** [comment]
this would be really cool to see!
/remove-lifecycle rotten

**Comment by BenTheElder** [comment]
Gubernator can sort by any of the columns now if you click the column headers

**Comment by justaugustus** [comment]
@BenTheElder cool beans!
In that case, can you or @lavalamp hit this with a `/close`?
