### ISSUE TITLE
PR dashboard: detect more forms of activity

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#1613]
I'm an assignee on a PR; I added a reviewer. The pr dashboard still lists me as needing to do something. I guess for now I'll just switch assignees completely.

**Comment by lavalamp** [comment]
(I was thinking that assignee maps to approver and reviewer maps to reviewer, but maybe that's not right)

**Comment by fejta** [comment]
We've been hesitant to integrate with the reviewer api because it is unstable. So we ignore it and only consider assignees.

**Comment by fejta** [comment]
We now integrate with the reviewer api
/assign @cjwagner
