### ISSUE TITLE
[Testgrid] Display k/perf-tests commit hash in scalability tests.

### ISSUE THREAD

**Issue by oxddr** [kubernetes/test-infra#16144]
**What would you like to be added**:
Display k/perf-tests commit hash in scalability tests, similarly to k/k and k/test-infra commit hashes 
![T8stDG9WpvE](https://user-images.githubusercontent.com/30298753/73858926-7f0b3c80-4839-11ea-916a-b1f19d9bdd02.png)

**Why is this needed**:
The same reason, why we display k/k and k/test-infra commit hash. It allows to quickly determine, which commit has been use

If this would a simple thing to do, I'd be happy to do it myself if given pointers. 
/help-needed

/area testgrid

**Comment by chases2** [comment]
I believe the configuration you're looking to change is the `ColumnHeader`, which is part of your tests' test group.

Depending on your current test's settings, you may need to add or manually configure your grid in [`config/testgrids`](https://github.com/kubernetes/test-infra/tree/master/config/testgrids). With more info on exactly which tests you want to modify, I can advise more, but this is where to start.

**Comment by chases2** [comment]
Detailed information on configurations and how TestGrid reacts to them can be found at that repo's [README](https://github.com/GoogleCloudPlatform/testgrid).
