### ISSUE TITLE
PR dashboard: PR shown in wrong state

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#1616]
https://github.com/kubernetes/kubernetes/pull/38950 shows as needing a review when it actually needs a rebase and shouldn't show at all for me.

**Comment by spxtr** [comment]
Possible doop of #1576

**Comment by lavalamp** [comment]
Is it possible the bot comments mess this up? I had a PR that was in state "address comments" when there were only bot comments.

**Comment by fejta** [comment]
/assign @rmmh 
Probably one of the myriad gubernator missed the webhook instances
