### ISSUE TITLE
Branchprotector exits when unable to protect a branch

### ISSUE THREAD

**Issue by tehcyx** [kubernetes/test-infra#16177]
**What happened**:
branchprotector exits, when a branch has a special character due to the query returning a 404, the code will actually just do a log.Fatalf and exit the process:
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/protect.go#L135

Furthermore in our case, we also had a leftover config skeleton of a repository that got recently deleted, that also ended up with an error. Failing on the same Fatalf line.

Due to recreation of the branchprotector pod, branches that should have postsubmit jobs running might be subject to not having them run at all (which we encountered on our instance).

**What you expected to happen**:
branchprotector logs a warning but does not shut down.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a branch in your repo, name it e.g. test_#123 and have org or repo level protection enabled.
```
branch-protection:
  protect: true
  orgs:
    cfgdef:
```
2. Add a non-existent repository to protection list. Might only work if the repo existed at one point.

**Please provide links to example occurrences, if any**:
```
{"component":"branchprotector","error":"update kyma-incubator: update kyma-dns-webhook: list branches: return code not 2XX: 404 Not Found","level":"error","msg":"0","time":"2020-02-06T22:00:13Z"}
{"component":"branchprotector","error":"update kyma-project/test-infra=prow_installer_#1556 protection to {\"required_status_checks\":{\"strict\":false,\"contexts\":[\"license/cla\",\"pre-test-infra-validate-configs\",\"pre-test-infra-validate-scripts\"]},\"enforce_admins\":null,\"required_pull_request_reviews\":{\"dismissal_restrictions\":{},\"dismiss_stale_reviews\":false,\"require_code_owner_reviews\":true,\"required_approving_review_count\":1},\"restrictions\":null} failed: status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3\"}","level":"error","msg":"1","time":"2020-02-06T22:00:13Z"}
{"component":"branchprotector","level":"fatal","msg":"Encountered 2 errors protecting branches","time":"2020-02-06T22:00:13Z"}
```
https://github.com/kyma-project/test-infra/issues/2010

**Anything else we need to know?**:
This might be related: #14858

**Comment by petr-muller** [comment]
Maybe I'm missing something, but can you elaborate how failing to set up branch protection causes postsubmits to not run?

**Comment by tehcyx** [comment]
As far as I understand, if branchprotector fails to update/setup branch protection, in our case the missing repo was in the list before another repo, the post-submit job is not registered and thus not run.

**Comment by petr-muller** [comment]
This should be unrelated. The branchprotector only commits the desired (describe in config file YAML) Branch Protection (the GH concept preventing force pushes and requiring checks to pass before merges ) rules to GitHub, it should not affect at all which jobs are executed.

**Comment by tehcyx** [comment]
Assume we can close this. I was under the impression it worked differently.
