### ISSUE TITLE
Use `Repo` struct instead of `org/repo` string

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#16223]
**What should be cleaned up or changed**:
Use `Repo` struct instead of `org/repo` string between test-infra components.

**Provide any links for context**:
https://github.com/kubernetes/test-infra/pull/16184#pullrequestreview-356477033

**Comment by matthyx** [comment]
@alvaroaleman I see `tide` relies a lot on "org/repo" strings... not sure we want to touch all that?
Also I will check if some parts of `hook` can be simplified with that struct.

**Comment by alvaroaleman** [comment]
> @alvaroaleman I see tide relies a lot on "org/repo" strings... not sure we want to touch all that?
Also I will check if some parts of hook can be simplified with that struct.

So without having looked at the tide code, the intuitive answer would be "Depends on if we ever split these". If we just always use `org/repo` strings everywhere and never split or join them, then its probably not worth the effort.

**Comment by matthyx** [comment]
I think we're done for now. Thanks for your help Alvaro!
