### ISSUE TITLE
Batch results should use https.

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1622]
_From @spxtr on December 6, 2016 21:44_

From https://github.com/kubernetes/contrib/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L176
```
  submit-queue.batch-url: http://prow.k8s.io/data.js
```

This should be https. Something strange happened last time we tried this.

_Copied from original issue: kubernetes/contrib#2131_

**Comment by foxish** [comment]
_From @rmmh on December 9, 2016 0:0_

It was unhappy with the letsencrypt provided cert:

    E1129 01:48:50.015240 1 submit-queue-batch.go:245] Error reading batch jobs from Prow URL https://prow.k8s.io/data.js
    x509: certificate signed by unknown authority

**Comment by foxish** [comment]
_From @spxtr on December 9, 2016 1:21_

It might work now that I'm using the full chain. I think previously I was just providing the cert. Not sure how to find out other than just trying it out.

**Comment by ixdy** [comment]
Is this still an issue?

**Comment by ixdy** [comment]
https://prow.k8s.io/data.js works in Chrome. Maybe the environment that SQ is running in doesn't recognize the CA certs?

**Comment by spiffxp** [comment]
Fixed by #2362
