### ISSUE TITLE
Mungegithub loop takes too long

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1623]
_From @foxish on November 1, 2016 20:7_

As we go over each issue in the bot's main loop, we go over issues like https://github.com/kubernetes/kubernetes/issues/33388 which has some 2500 comments, it spends some 20 seconds or so (and lots of API calls) to fetch comments.
Do we really need to look at these issues completely? 

cc @eparis 

_Copied from original issue: kubernetes/contrib#1967_

**Comment by foxish** [comment]
_From @apelisse on November 1, 2016 20:13_

I'll see if I have something smart to say in the next 24h :-)

**Comment by foxish** [comment]
_From @apelisse on November 2, 2016 16:22_

Yes, this is because of the flake nagger. It reads comments on issues. Not sure how to fix that right now.

**Comment by fejta** [comment]
/unassign @foxish 
/assign @apelisse 
who made this loop dramatically faster
