### ISSUE TITLE
[mungegithub] Autoclose Issues Without Routing Labels

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1626]
_From @grodrigues3 on December 22, 2016 0:4_

A Two Part Issue
Allow people to suggest area/labels or sig/labels when creating issues using issue template.  Something like 
`area-label: area/kubelet` or `sig-label:sig-cli` in the template could allow us to auto-detect routing labels

If issue opened, by member of org without routing label, auto-close and explain why.

_Copied from original issue: kubernetes/contrib#2199_

**Comment by fejta** [comment]
The `/area kubelet` commands exist
