### ISSUE TITLE
testgrid-config-upload job is failing

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#16268]
**What happened**:
[testgrid-config-upload](https://k8s-testgrid.appspot.com/sig-testing-maintenance#testgrid-config-upload) began failing again shortly after it was fixed.

[First Failure's Log](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-upload-testgrid-config/1227749503323344896)

**What you expected to happen**:
Passing jobs, uploaded configs

**Anything else we need to know?**:
Concurrent with #16264 merging; may be related.

/assign
/assign @fejta

**Comment by fejta** [comment]
Looks like a flake
