### ISSUE TITLE
milestones should rank higher in the submit queue

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1627]
_From @dims on November 28, 2016 19:59_

For example if we have 2 PR(s) with ["P3","v1.5"] or ["P2","v1.6"]

Currently we are prioritizing the 1.6 above the 1.5... Can we please do the opposite?

_Copied from original issue: kubernetes/contrib#2083_

**Comment by foxish** [comment]
_From @dims on November 28, 2016 19:59_

cc @saad-ali @rmmh

**Comment by foxish** [comment]
_From @dims on November 28, 2016 19:59_

Note from @rmmh 
@dims: can you refile that against contrib? https://github.com/kubernetes/contrib/blob/master/mungegithub/mungers/submit-queue.go#L1082  is the badness

**Comment by eparis** [comment]
We shouldn't be using priorities any more, although we should start using the `queue/*` labels.

**Comment by liggitt** [comment]
I do think milestones should be in the sort order, though... the submit queue seems to be ignoring them. I'd expect 1.6 PRs to come before PRs with no milestone associated

**Comment by fejta** [comment]
Similar to https://github.com/kubernetes/test-infra/issues/2035
