### ISSUE TITLE
`sig/onprem` label expired since 2019-12-17

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#16276]
**What should be cleaned up or changed**:
Should we remove `sig/onprem` label from label_sync?

**Provide any links for context**:
https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md#sig/onprem

> REMOVING. This will be deleted after 2019-12-17 00:00:00 +0000 UTC

**Comment by nikhita** [comment]
Done in https://github.com/kubernetes/test-infra/commit/ec0f09b3a6d26c404c6e27685e32d25aff43d276

/close
