### ISSUE TITLE
boskos: remove apiextensions/customresourcedefinitions rule from boskos ClusterRole

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#16281]
**What should be cleaned up or changed**:
Once Boskos no longer attempts to create the Boskos CRDs itself (i.e. #16266 has rolled out), we should remove that permission from its ClusterRole:
https://github.com/kubernetes/test-infra/blob/49ecce6586df439db2f4bdce4c4d6a3956e87d79/prow/cluster/boskos.yaml#L56-L58

The CRDs are now saved as YAMLs in the cluster deployment directory (#16267), which makes deployment and upgrades easier, and it also reduces the permissions we need to give to Boskos.

**Comment by riking** [comment]
Dependent PR is merged and seems rolled out.
