### ISSUE TITLE
Test-Infra-Push-Prow job broken

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#16303]
**What happened**:

https://prow.k8s.io/?job=post-test-infra-push-prow is pretty red

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/kind oncall-hotlist

**Comment by stevekuznetsov** [comment]
```
 2020/02/14 14:11:10 Successfully pushed Docker image to gcr.io/k8s-prow/grandmatriarch:latest-root
ERROR: (gcloud.auth.docker-helper) timed out
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach. 
```

**Comment by stevekuznetsov** [comment]
```
 2020/02/14 14:13:53 Error pushing image to gcr.io/k8s-prow-edge/issue-creator:latest: unable to push image to gcr.io/k8s-prow-edge/issue-creator:latest: error getting credentials - err: exit status 1, out: ``
ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
Please run:
  $ gcloud auth login
to obtain new credentials, or if you have already logged in with a
different account:
  $ gcloud config set account ACCOUNT
to select an already authenticated account to use. 
```

**Comment by stevekuznetsov** [comment]
https://github.com/kubernetes/test-infra/pull/16265/files ?

**Comment by fejta** [comment]
Suspect this job is DOSing the metadata server

**Comment by fejta** [comment]
We already have retries (and we are retrying): 

https://github.com/kubernetes/test-infra/blob/c71503f9a7646488b0bef5ac2d5ad485fb25e6ab/prow/push.sh#L69-L78

I'll file an internal bug around workload identity, but we should probably just make that job start using the secret file again until its resolved.

**Comment by alvaroaleman** [comment]
Seems to be fixed
/close
