### ISSUE TITLE
Mungegithub doesn't handle identical blocking and non-blocking jobs

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1630]
_From @apelisse on November 8, 2016 16:48_

If a job is both in the non-blocking queue and the blocking queue, everything starts acting funny (can someone say what's actually broken?).

We should probably:
- [ ] Validate/test that the configuration is sane as early as possible
- [ ] Act properly even if the configuration is slightly misleading: consider jobs in both lists to be blocking.

_Copied from original issue: kubernetes/contrib#2006_

**Comment by fejta** [comment]
We no longer support blocking jobs
