### ISSUE TITLE
prow retitle appends "\r" to the bug title

### ISSUE THREAD

**Issue by danwinship** [kubernetes/test-infra#16319]
When you use `/retitle` to retitle a PR, the PR will end up with a carriage return at the end of the title. This is not visible on the HTML page, but it shows up in the source, and in email related to the bug.

eg, https://github.com/openshift/sdn/pull/108 had the command [`/retitle Bug 1803149: Rebase SDN to kubernetes 1.17.2`](https://github.com/openshift/sdn/pull/108#issuecomment-586326644) run on it, and now you can see the CR in the source:

    danw@p50:~> curl -s -o- https://github.com/openshift/sdn/pull/108 | cat -v | grep js-issue-title
      <a class="js-issue-title css-truncate css-truncate-target link-gray-dark width-fit" href="#">Bug 1803149: Rebase SDN to kubernetes 1.17.2^M</a>

and also as "=0D" in emails related to the PR:

    Subject: Re: [openshift/sdn] Bug 1803149: Rebase SDN to kubernetes 1.17.2=0D (#108)

**Comment by alvaroaleman** [comment]
@danwinship while I can see the issue as you described in the PR you linked I can not see it on others that were retitled, i.E.:
```
$ curl -Ss https://github.com/kubernetes/test-infra/issues/16328| cat -v | grep js-issue-title
      <span class="js-issue-title">
  <a class="js-issue-title css-truncate css-truncate-target link-gray-dark width-fit" href="#">hook: re-evaluate cherry-pick labels when a base branch changes for a PR</a>

```

Do you have more examples of retitled PRs where this happened? I can not really see anything in the retitle plugins code (which is fairly simple) that would explain this.

**Comment by danwinship** [comment]
You know, I originally had "(sometimes?)" in the summary and then removed it...

searching my trash folder for "=0D", I also find:

https://github.com/openshift/cluster-network-operator/pull/466
https://github.com/openshift/sdn/pull/102
https://github.com/openshift/cluster-openshift-apiserver-operator/pull/296
https://github.com/openshift/cluster-network-operator/pull/401

and I see that in all of those cases, there were additional commands/comments after the `/retitle`, whereas in the one you pointed out the `/retitle` was the entire comment.
