### ISSUE TITLE
Docs about 'Contributing Test Results' should be improved

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes/test-infra#16333]
**What would you like to be added**:
We need to update [Contributing Test Results](https://github.com/kubernetes/test-infra/blob/92e4176fa4877ba1823eabfc576fe1665f8f3762/docs/contributing-test-results.md#contributing-test-results) process.

I think we should describe the following more details:
- How to request a new GCS bucket?
- How to run conformance tests with [kubetest](https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md) as well as dump logs to satisfied the [Gubernator's GCS Layout](https://github.com/kubernetes/test-infra/blob/master/gubernator/README.md#gcs-layout)?
- How to upload test results to a GCS bucket?
 
**Why is this needed**:
The current document is a little bit confusing for guys not familiar with testing matters.

I asked @BenTheElder and @dims for help in slack. And @BenTheElder also agrees to update relative documents. 
/help

**Comment by BenTheElder** [comment]
Running conformance tests is not kubetest specific and there is an official upstream guide for this.

Also the appropriate document for this context is here:
https://github.com/kubernetes/test-infra/tree/92e4176fa4877ba1823eabfc576fe1665f8f3762/testgrid/conformance#display-conformance-tests-with-testgrid

which is linked from [the relevant KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/0018-testgrid-conformance-e2e.md), and is up to date except for:
> How to request a new GCS bucket?

for which I'd love it if you could file an update given you're going through the wg-k8s-infra process.

**Comment by BenTheElder** [comment]
contributing test results is NOT for conformance tests, it's for people wishing to provide arbitrary testgrid results, for which they may need to provide their own bucket and may not be using kubetest at all (could be e.g. unit tests on another platform...)

I don't think that doc needs much updating, but it might also need a wg-k8s-infra / k8s.io pointer, and a pointer to this kep / the conformance results doc.

**Comment by RainbowMango** [comment]
> for which I'd love it if you could file an update given you're going through the wg-k8s-infra process.

Sure. I'd love to.

> it's for people wishing to provide arbitrary testgrid results, for which they may need to provide their own bucket

Does this mean if a project owned by [kubernetes org](https://github.com/kubernetes/) could request a free GCS bucket from the wg-k8s-infra process, and other projectes people need to provide create bucket by themselves?

I think this should be clarified.

**Comment by BenTheElder** [comment]
We've specifically been open to hosting conformance test results, but some
people are using testgrid with things that simply aren't kubernetes at all,
in which case we're probably not going to sponsor...

These docs are not really the place to get into that.

**Comment by RainbowMango** [comment]
@BenTheElder 
> How to request a new GCS bucket?

What to do next after [add a group](https://github.com/kubernetes/k8s.io/pull/580)?
I thought there may be a CI running somewhere that would help to create the bucket after that. 
But two days passed...

**Comment by BenTheElder** [comment]
I don't know with the new process, I've not had time to catch up on this yet.

**Comment by RainbowMango** [comment]
OK. Maybe @dims and @bartsmykla know. I'll ask at slack channel (wg-k8s-infra) as well.
