### ISSUE TITLE
[mungegithub] Modify mungegithub to use config files instead of command-line arguments.

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1633]
_From @foxish on July 21, 2016 3:7_

The number of command-line arguments is getting large and unwieldy. We should switch to reading config files instead.
It would also let us group these command-line options into logical sub-units which is currently not possible.

_Copied from original issue: kubernetes/contrib#1415_

**Comment by foxish** [comment]
_From @eparis on July 21, 2016 22:54_

I've not looked at it, but I know http://github.com/spf13/viper is supposed to help add config files on top of cobra/pflag...

**Comment by foxish** [comment]
@eparis I will take a look at that. Thanks!

**Comment by foxish** [comment]
I don't thing the current setup needs change and we don't gain much from config files. We can close this probably. WDYT @apelisse?

**Comment by apelisse** [comment]
I wondered the same when I read the title of the issue. I find config files more painful to maintain that command-line arguments. Everything is already in a config anyway, so we have the best of both worlds. Let's keep it like this.
