### ISSUE TITLE
verify-owners: checks out PR branch, instead of merging PR branch with base branch

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#16330]
**What happened**:
verify-owners checks out the PR branch when verifying the owners files and tests that, rather than merging the PR branch with the base branch, and then testing.

**What you expected to happen**:
verify-owners would merge the PR with the base branch, and check on the result. This is prevalent in the case that OWNERS_ALIASES are being used, and are modified between when the PR branch is created, but before the PR is merged.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a PR referencing an alias that doesn't exist
- Create the matching entry in OWNERS_ALIASES, and have that PR merge
- Attempt to /verify-owners on the first PR. It will not succeed, even though the alias exists in master

**Please provide links to example occurrences, if any**:
https://github.com/kubernetes/perf-tests/pull/1030

**Anything else we need to know?**:

Section of logic: 
https://github.com/kubernetes/test-infra/blob/92e4176fa4877ba1823eabfc576fe1665f8f3762/prow/plugins/verify-owners/verify-owners.go#L223-L241

Instead of using `CheckoutPullRequest` (in `prow/git/git.go`) we should be able to use `MergeAndCheckout` with the base/head of the PR to merge it and then test against that.

@cjwagner @stevekuznetsov @fejta: Is it worth possibly a new helper function like `CheckoutMergedPullRequest` that has just the PR input like `CheckoutPullRequest`, but uses `MergeAndCheckout` to merge the PR before returning the checked out branch?

**Comment by cjwagner** [comment]
> Is it worth possibly a new helper function like `CheckoutMergedPullRequest` that has just the PR input like `CheckoutPullRequest`, but uses `MergeAndCheckout` to merge the PR before returning the checked out branch?

Yes. When evaluating PR contents we rarely care about the unmerged PR branch, testing the merged state is almost always what we want. The function would need more than just the PR input though, it would also need the base branch commit SHA.
