### ISSUE TITLE
[Prow] Empty runs for pull-perf-tests-clusterloader2

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/test-infra#16338]
**What happened**:
I've created a PR kubernetes/perf-tests#1060 that triggered an an expected behavior from Prow. A number of 'empty' jobs were triggered , as seen on [testgrid](https://testgrid.k8s.io/presubmits-kubernetes-scalability#pull-perf-tests-clusterloader2) for 02-18.

This PR merges to non-master branch, release-1.17. Maybe this is related.

**What you expected to happen**:

Single job should be triggered.

**How to reproduce it (as minimally and precisely as possible)**:

No reproduction path.

kubernetes/perf-tests#1062 created in the same way did not trigger the same behavior.

**Please provide links to example occurrences, if any**:

 *  [testgrid](https://testgrid.k8s.io/presubmits-kubernetes-scalability#pull-perf-tests-clusterloader2)
 *  kubernetes/perf-tests#1060

**Anything else we need to know?**:

pull-perf-tests-clusterloader2 has another grey tests: 01-29.

/sig testing

**Comment by jprzychodzen** [comment]
Update:
kubernetes/perf-tests#1062 has triggered two presubmit runs:
 *  https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-perf-tests-clusterloader2/1229769652859572224
 *  https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-perf-tests-clusterloader2/1229767138370129920

These runs use different `- --extract=` flag and annotations

**Comment by mborsz** [comment]
I checked kube-apiserver's logs for 0b457c44-5258-11ea-bee6-7ae328210567 pod (from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/perf-tests/1062/pull-perf-tests-clusterloader2/1230047836310081537) run and it seems to be continuously created and then deleted by 'app.binary' user-agent.

Looks like a prow issue to me.

**Comment by jprzychodzen** [comment]
Update:
Now there is a number of grey tests in testgrid, probably related to this presubmit.

Possible reproduction behavior:
Create a PR to non-master branch that will trigger pull-perf-tests-clusterloader2, wait for first presubmit to succeed.

**Comment by mm4tt** [comment]
FTR, grey tests that Kuba mentioned:

![eJaCbFazMKt](https://user-images.githubusercontent.com/2604887/74824159-298a6180-5308-11ea-9487-72f0d8f0b2fb.png)

**Comment by BenTheElder** [comment]
So for https://github.com/kubernetes/perf-tests/pull/1062 there is a prow bug it seems causing the GC component (sinker) and the prowjob / pod runner (plank) to alternately clean up and then recreate the test pod.

the double triggering is probably a config issue though

cc @Katharine @fejta

**Comment by fejta** [comment]
I am going to manually delete these prowjobs so we stop recreating them

**Comment by fejta** [comment]
```console
$ kubectl --context=k8s-prow delete prowjobs 0b457c44-5258-11ea-bee6-7ae328210567 
prowjob.prow.k8s.io "0b457c44-5258-11ea-bee6-7ae328210567" deleted

$ kubectl --context=k8s-prow delete prowjobs 9a0b93a5-523d-11ea-8d34-5ea6e6c1117c
prowjob.prow.k8s.io "9a0b93a5-523d-11ea-8d34-5ea6e6c1117c" deleted
```
