### ISSUE TITLE
Support showing timestamps in logs

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#16354]
**What would you like to be added**:

Some way to see timestamps associate with test logs. This could be equivalent to `kubectl logs --timestamps`.

**Why is this needed**:

This will help analyze how much time is spent on different portions of test runs. Right now our jobs have a lot of `time foo` commands, which help, but its not ideal and requires foresight to put the `time` there.

This isn't a high priority but may be convenient to help figure out where time is spent during tests

**Comment by alvaroaleman** [comment]
Dupe of https://github.com/kubernetes/test-infra/issues/10100, closing so we keep the conversation around this in one place.
/close
