### ISSUE TITLE
Fix http-cache

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1638]
_From @grodrigues3 on January 12, 2017 0:19_

For the `ListComments()` function at least, the cache seems to return an incorrect list of IssueComments or no comments at all.  This can result in the k8s-merge-robot spamming an issue since it cannot see that it has already written to the issue.

_Copied from original issue: kubernetes/contrib#2288_

**Comment by rmmh** [comment]
I believe @grodrigues3 fixed the cache. It was using one cache entry for all comments AND for partial comments-- giving empty results sometimes when it asked for all of them.
