### ISSUE TITLE
[Question] How to build and run E2E performance tests on an existing Kubespray cluster ?

### ISSUE THREAD

**Issue by karim-manaouil** [kubernetes/test-infra#16389]
**What happened**:

I built the ginkgo, e2e.test and kubectl with:

```
make all WHAT=cmd/kubectl && \
make all WHAT=vendor/github.com/onsi/ginkgo/ginkgo && \
make all WHAT=test/e2e/e2e.test

```
When I run the performance tests with, I get the following error:

```
# ./_output/bin/e2e.test -- --host=http://127.0.0.1:8080 --provider=local --ginkgo.v=true --kubeconfig=/root/.kube/config --ginkgo.focus="Performance" --ginkgo.skip="Serial|Slow" --ginkgo.failFast=false

W0220 14:50:51.068979    5201 test_context.go:410] Unable to find in-cluster config, using default host : http://127.0.0.1:8080
I0220 14:50:51.069000    5201 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
Feb 20 14:50:51.069: INFO: The --provider flag is not set. Continuing as if --provider=skeleton had been used.
I0220 14:50:51.069138    5201 e2e.go:109] Starting e2e run "cb610a13-e541-4c0b-a3f1-65c369c2b543" on Ginkgo node 1
{"msg":"Test Suite starting","total":4037,"completed":0,"skipped":0,"failed":0}
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1582206649 - Will randomize all specs
Will run 4037 of 4814 specs

Feb 20 14:50:51.088: INFO: >>> kubeConfig: 
F0220 14:50:51.088943    5201 e2e.go:217] Error loading client: error creating client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**What you expected to happen**
Run the E2E performance tests and gather the results

**How to reproduce it (as minimally and precisely as possible)**:
Apply the previous instructions on a v1.17.0 git branch on a v1.17.0 running cluster built with Kubespray

**Anything else we need to know?**:
Kubernetes v1.17.0 deployed with Kubespray running on a bare-metal cluster (high end servers).
Building and running E2E done from a k8s.io/kubernetes@v1.17.0 

+ How much time the performance test takes on average ?

**Comment by BenTheElder** [comment]
you should file a bug against kubernetes or kubespray for this, this repo hosts tools used by the project which does not include kubespray or e2e.test (that's in kubernetes/kubernetes)

generally a KUBECONFIG file is used.
