### ISSUE TITLE
Have the bot apply sig label on sig mentions.

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1640]
_From @timothysc on January 13, 2017 21:49_

I know folks are working on new submission template but it would likely save a bunch of time if the bot just applied the sig label on the sig mention.  For those that can't label it allows them to reach the right audience most of the time.  

@kubernetes/sig-contributor-experience-misc 

_Copied from original issue: kubernetes/contrib#2302_

**Comment by foxish** [comment]
_From @spxtr on January 13, 2017 21:57_

This could be done pretty easily as a prow plugin.

**Comment by foxish** [comment]
_From @apelisse on January 13, 2017 22:1_

Yeah, just be careful because the github api will create the label that you apply if it doesn't exist. Meaning if you match @sig-.* and blindy add that label, then it will create stupid labels every time someone types @sig-$something_stupid.

**Comment by foxish** [comment]
_From @sig- on January 14, 2017 9:30_

Yeah, I don't know exactly what you're doing, but since it's apparently connected to GitHub you might want to double check that it doesn't give me a mention notification every time someone types @sig-$something_or_other 😜

**Comment by MrHohn** [comment]
What is the right syntax to apply sig label?
I saw `/sig-<some-github-team>` in [command.md](https://github.com/kubernetes/test-infra/blob/master/commands.md), but `/sig-network` didn't seem to work (kubernetes/kubernetes#44203)?

**Comment by grodrigues3** [comment]
@MrHohn I'll open a ticket to fix it.  We decided to make it apply on mentions (so @ sig-network-pr-reviews would use a regexp to pick out the network part and then hopefully apply the sig-network label).

Apparently that didn't work.

**Comment by MrHohn** [comment]
@grodrigues3 Thanks!
