### ISSUE TITLE
[mungebot] Autoclose PRs Without Release Note Label Set

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1641]
_From @grodrigues3 on December 22, 2016 0:4_

If PR opened without release note label set and PR author is member of org, auto close PR and explain how label can be set with PR template

_Copied from original issue: kubernetes/contrib#2200_

**Comment by rmmh** [comment]
Seems overly intrusive to me. Leaving a comment explaining that it needs a label is easier.

**Comment by grodrigues3** [comment]
Clarifications

1. This is for people in the org that open issues 
1. The issue template should allow people to set labels and prow should probably allow people to set labels with sig or area prefix

I understand that it seems intrusive, but it's way to ensure longterm, sustainable issue triage.  Everyone in the org should be routing labels.  With 50 new issues per day coming in and 5000+ in the backlog, it's not really optional.

**Comment by spxtr** [comment]
Leave a comment explaining how to set the appropriate labels, and only close the PR after a few days without.

It's way too annoying to have a PR closed immediately.

**Comment by grodrigues3** [comment]
I'm good with that.  Let's just make sure labels can be set both through prow commands as well as through the issue templates.  

And a timer before closing is fine with me.

**Comment by idvoretskyi** [comment]
Subscribed (as we need the similar for the features repo as well).

**Comment by fejta** [comment]
The /release-note and /release-note-none commands now exist in prow
