### ISSUE TITLE
SQ should indicate which commit statuses are preventing merge

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1643]
_From @ixdy on November 30, 2016 21:33_

It's not always obvious why SQ says "Github CI tests are not green." - e.g., it might be because a required status is missing, it might be because SQ is behind on its sync loop, or it might be a bug in SQ.

If we added the list of failing status(es), it would make it easier to understand how to fix a PR.

_Copied from original issue: kubernetes/contrib#2102_

**Comment by foxish** [comment]
_From @fejta on November 30, 2016 21:39_

@ixdy @foxish @eparis it sounds like at least some subset of you are aware of and/or working on this per https://github.com/kubernetes/kubernetes/pull/37413#issuecomment-264000592 

Can we get a new SQ build with this change? @rmmh can then redeploy the SQ with it.

**Comment by foxish** [comment]
_From @eparis on November 30, 2016 21:48_

That comment in 37413 was something different, but this is a good idea too....

**Comment by rmmh** [comment]
This is done-- the SQ says which non-green status is preventing a merge.
