### ISSUE TITLE
Protect more branches in k/website

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/test-infra#16458]
### What's the problem?

Branch protection for [k/website](https://github.com/kubernetes/website/branches/all?utf8=%E2%9C%93&query=release) is out of date. All release branches should be protected from force pushes, and the `dev-<x>` branch for the current release should be protected as well.

### What's the fix?

Update [branch protection for k/website](https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L254-L270) to include all `release-<x>` branches and the current dev branch, `dev-1.18`.

### Further discussion

There's a larger discussion about whether k/website needs to continue with default branch protection disabled, or whether to enable it. SIG chairs and nominal tech leads will discuss it at the next two weekly meetings (25 Feb 2020, 3 Mar 2020). I'd prefer to handle that as a separate PR while we protect branches now.

Relevant to #15449. 

/cc @jimangel @kbarnard10 
/sig docs

**Comment by jimangel** [comment]
/reopen

We should make sure this is in the docs handbook too

/cc @savitharaghunathan 
/milestone 1.19

**Comment by jimangel** [comment]
/remove-lifecycle-stale

@savitharaghunathan what do you think about this?

**Comment by jimangel** [comment]
/remove-lifecycle stale

... third time's a charm

**Comment by zacharysarah** [comment]
Selfishly, I’m glad we didn’t act on it because I had to force push an amended commit today. 😱
