### ISSUE TITLE
help:cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:

### ISSUE THREAD

**Issue by tanjunchen** [kubernetes/test-infra#16470]
see https://github.com/kubernetes/test-infra/tree/master/kubetest#installation
after running go install k8s.io/test-infra/kubetest

```
k8s-develop@ubuntu:~/goproject/src/k8s.io$ go install k8s.io/test-infra/kubetest
go: finding k8s.io/test-infra latest
go: downloading k8s.io/test-infra v0.0.0-20200225132449-8de034600dfd
go: extracting k8s.io/test-infra v0.0.0-20200225132449-8de034600dfd
go: finding github.com/Azure/azure-sdk-for-go v38.0.0+incompatible
go: finding github.com/Azure/azure-storage-blob-go v0.0.0-20190123011202-457680cc0804
go: finding github.com/aws/aws-k8s-tester v0.0.0-20190114231546-b411acf57dfe
go: finding github.com/aws/aws-sdk-go v1.27.4
go: finding github.com/pelletier/go-toml v1.3.0
go: finding github.com/Azure/azure-pipeline-go v0.1.9
go: finding golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
go: finding k8s.io/api v0.17.2
go: finding k8s.io/apimachinery v0.17.2
go: finding google.golang.org/grpc v1.24.0
go: finding golang.org/x/sys v0.0.0-20191210023423-ac6580df4449
go: finding google.golang.org/genproto v0.0.0-20191009194640-548a555dbc03
go: finding golang.org/x/net v0.0.0-20191119073136-fc4aabc6c914
build k8s.io/test-infra/kubetest: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
	github.com/Azure/go-autorest v11.1.2+incompatible (/home/k8s-develop/goproject/pkg/mod/github.com/!azure/go-autorest@v11.1.2+incompatible/autorest)
	github.com/Azure/go-autorest/autorest v0.9.5 (/home/k8s-develop/goproject/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.5)

```

**Comment by HtcOrange** [comment]
> see https://github.com/kubernetes/test-infra/tree/master/kubetest#installation
> after running go install k8s.io/test-infra/kubetest
> 
> ```
> k8s-develop@ubuntu:~/goproject/src/k8s.io$ go install k8s.io/test-infra/kubetest
> go: finding k8s.io/test-infra latest
> go: downloading k8s.io/test-infra v0.0.0-20200225132449-8de034600dfd
> go: extracting k8s.io/test-infra v0.0.0-20200225132449-8de034600dfd
> go: finding github.com/Azure/azure-sdk-for-go v38.0.0+incompatible
> go: finding github.com/Azure/azure-storage-blob-go v0.0.0-20190123011202-457680cc0804
> go: finding github.com/aws/aws-k8s-tester v0.0.0-20190114231546-b411acf57dfe
> go: finding github.com/aws/aws-sdk-go v1.27.4
> go: finding github.com/pelletier/go-toml v1.3.0
> go: finding github.com/Azure/azure-pipeline-go v0.1.9
> go: finding golang.org/x/crypto v0.0.0-20191206172530-e9b2fee46413
> go: finding k8s.io/api v0.17.2
> go: finding k8s.io/apimachinery v0.17.2
> go: finding google.golang.org/grpc v1.24.0
> go: finding golang.org/x/sys v0.0.0-20191210023423-ac6580df4449
> go: finding google.golang.org/genproto v0.0.0-20191009194640-548a555dbc03
> go: finding golang.org/x/net v0.0.0-20191119073136-fc4aabc6c914
> build k8s.io/test-infra/kubetest: cannot load github.com/Azure/go-autorest/autorest: ambiguous import: found github.com/Azure/go-autorest/autorest in multiple modules:
> 	github.com/Azure/go-autorest v11.1.2+incompatible (/home/k8s-develop/goproject/pkg/mod/github.com/!azure/go-autorest@v11.1.2+incompatible/autorest)
> 	github.com/Azure/go-autorest/autorest v0.9.5 (/home/k8s-develop/goproject/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.5)
> ```

Have you solved the problem? It seems that I meet the same problem. Look forward to your reply!

**Comment by tanjunchen** [comment]
@HtcOrange  Hello 
see https://github.com/kubernetes/test-infra/tree/master/kubetest#installation

![image](https://user-images.githubusercontent.com/19339970/76846837-1b365380-687c-11ea-95b4-48a731ea8193.png)


clone test-infra repo, cd kubetest , hope it is useful for you.
