### ISSUE TITLE
Allow protecting the tide github status context

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#16472]
**What would you like to be added**:
When reporting Prow jobs status for PRs in Github UI, also note whether it's required or optional as defined by Prow job itself

<img width="723" alt="Screen Shot 2020-02-25 at 8 08 33 AM" src="https://user-images.githubusercontent.com/45011425/75265812-47434500-57a6-11ea-974a-b0ce27513923.png">

**Why is this needed**:
This can help remove the ambiguity introduced by hidden `required` jobs that only required by `tide`but not explicitly marked as `required` by admins. Also, this will make it possible to only require `tide` as requirement

Related: https://github.com/knative/test-infra/issues/1742

**Comment by stevekuznetsov** [comment]
Looks like you have branch protection configured and it's clearly marking the job as required on the right of your screenshot -- is what you're asking for a separate feature?

**Comment by chaodaiG** [comment]
The example was from a PR in the current repo. The goal of this feature request is to make us being able to only add tide on branch protection instead of adding each individual job

**Comment by chaodaiG** [comment]
The example was from a PR in the current repo. The goal of this feature request is to make us being able to only add tide on branch protection instead of adding each individual job

**Comment by chaodaiG** [comment]
To be more clear, this is just a UI change request. As functionally we can already only add `tide` to branch protection, since `tide` already implicitly requires all jobs that are not marked `optional` to pass. So the ask is just labeling each job more explicitly in Github UI. 

IMHO this is achievable if the status updater already knows about `optional`, otherwise it may not worth the effort to wire them together

**Comment by alvaroaleman** [comment]
/retitle Allow protecting the tide github status context

> The example was from a PR in the current repo. The goal of this feature request is to make us being able to only add tide on branch protection instead of adding each individual job

This can be done today _but_ will result in an elevated error rate from tide, because the part that updates the status is async from the part that merges, which means that the merging may fail because the github status context wasn't updated yet.

Generally this is a huge +1 from me, as its conceptionally much saner than protecting each individual github status context, because that requires a giant amount of tokens and the settings are only eventual consistent with job config changes.

**Comment by chases2** [comment]
Related to this asynchronousness, sometimes PRs will merge before their tide status is updated. This leads to some PRs (like https://github.com/kubernetes/test-infra/pull/17874) that will merge even while the Tide status says the PR is "not mergeable". This has been observed to happen on multiple repositories.

/remove-lifecycle stale

**Comment by matthyx** [comment]
@alvaroaleman can I help here?

**Comment by alvaroaleman** [comment]
@matthyx yeah, sure. So the basic objective is that tide must set its status to `success` before merging. Additionally to not waste api tokens, the tide status controller should not do that a second time (ideally it will just ignore everything that merged).  For the status controller part it might be that there is nothing to do for that already, but not sure off of the top of my head.

**Comment by arturo-skydio** [comment]
Sorry @matthyx , not sure if you already started work, but my org and tide instance really needs this as well, so I created a PR #20892, and testing with this other setting we have #20679

**Comment by matthyx** [comment]
no problem...
/assign @arturo-skydio

**Comment by alvaroaleman** [comment]
FTR: Fixed in https://github.com/kubernetes/test-infra/pull/21650
