### ISSUE TITLE
Job pull-kubernetes-e2e-aks-engine-azure-windows is failing to find release tarball

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/test-infra#16482]
**What happened**:

the job `pull-kubernetes-e2e-aks-engine-azure-windows` is failing before it deploys the cluster

```
I1211 22:43:56.282] push-build.sh: BEGIN main on 77050ed9-1c66-11ea-bf17-aa448ceb0124 Wed Dec 11 22:43:56 UTC 2019
I1211 22:43:56.282] 
I1211 22:43:56.363] 
I1211 22:43:56.371] 
I1211 22:43:56.379] Signal ERR caught!
I1211 22:43:56.385] 
I1211 22:43:56.392] Traceback (line function script):
I1211 22:43:56.393] 131 main /go/src/k8s.io/release/push-build.sh
I1211 22:43:56.399] 
I1211 22:43:56.405] Exiting...
I1211 22:43:56.412] 
I1211 22:43:56.415] 
I1211 22:43:56.417] push-build.sh: DONE main on 77050ed9-1c66-11ea-bf17-aa448ceb0124 Wed Dec 11 22:43:56 UTC 2019 in 0s
W1211 22:43:56.518] tar (child): /go/src/k8s.io/kubernetes/_output/release-tars/kubernetes.tar.gz: Cannot open: No such file or directory
W1211 22:43:56.518] tar (child): Error is not recoverable: exiting now
W1211 22:43:56.518] tar: Child returned status 2
W1211 22:43:56.519] tar: Error is not recoverable: exiting now
W1211 22:43:56.519] 2019/12/11 22:43:56 process.go:155: Step '/go/src/k8s.io/release/push-build.sh --nomock --verbose --noupdatelatest --bucket=kubernetes-release-pull --ci --gcs-suffix=/pull-kubernetes-e2e-aks-engine-azure-windows --allow-dup' finished in 345.706315ms
```

**What you expected to happen**:

No failures deploying the cluster, test case results should be visible in gubernator

**How to reproduce it (as minimally and precisely as possible)**:

Add `/test pull-kubernetes-e2e-aks-engine-azure-windows` in a comment on a PR

**Please provide links to example occurrences, if any**:

PR: https://github.com/kubernetes/kubernetes/pull/86101

Results: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86101/pull-kubernetes-e2e-aks-engine-azure-windows/1204892424267108357/

Logs: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/86101/pull-kubernetes-e2e-aks-engine-azure-windows/1204892424267108357/build-log.txt

**Anything else we need to know?**:

/assign chewong
/sig windows
/area provider/azure

**Comment by chewong** [comment]
Looks like the problem disappeared. Closing this issue for now.
/close
