### ISSUE TITLE
Plank continuously re-syncs a pod that can't be created

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#16509]
Plank was unable to schedule a pod for a job that was trying to access a service account it couldn't access (`deployer`). The job was changed to no longer access the service account, but Plank is still failing to create the same pod with the same error on every sync loop.

Error:
```
 jsonPayload: {
  component: "plank"   
  error: "errors syncing: [error starting pod: pods "2d39b17d-57ac-11ea-a023-761c4a43a0d4" is forbidden: error looking up service account test-pods/deployer: serviceaccount "deployer" not found], errors reporting: []"   
  file: "prow/cmd/plank/main.go:149"   
  func: "main.main.func2"   
  level: "error"   
  msg: "Error syncing."   
 }
``` 

Discussed offline with Cole, it looks like Plank retries this error when it shouldn't (since the error isn't transient and we will not be able to start this pod ever).

/assign @cjwagner 

/area prow
/kind oncall-hotlist

**Comment by cjwagner** [comment]
This check is insufficient: https://github.com/kubernetes/test-infra/blob/50c1fdc2a988c9c19cdfb1537c4c3dfa9d46518e/prow/plank/controller.go#L517

We need to retry all non-4xx errors, not all non-422 errors. Request errors are unlikely to be transient and should cause the job to complete with the errored state.

**Comment by cjwagner** [comment]
`prowjob.prow.k8s.io "2d39b17d-57ac-11ea-a023-761c4a43a0d4" deleted`
