### ISSUE TITLE
All test runs under google-windows dashboard are failing since 02/19/2020

### ISSUE THREAD

**Issue by YangLu1031** [kubernetes/test-infra#16522]
**What happened**:
All the test runs under `google-windows` [dashboard](https://testgrid.k8s.io/google-windows#Summary&show-stale-tests=) are failing since 02-19-2020 during setup.
```
2020/02/20 01:28:54 process.go:153: Running: gcloud config set project gce-gci-upg-1-4-lat-ctl-skew
Updated property [core/project].
ERROR: gcloud crashed (MetadataServerException): HTTP Error 400: Bad Request
```
**What you expected to happen**:
Tests are running fine.

**How to reproduce it (as minimally and precisely as possible)**:
Go to https://testgrid.k8s.io/google-windows#Summary&show-stale-tests=

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1-17/1232945841803628546

**Anything else we need to know?**:
```
googlecloudsdk.core.credentials.gce.MetadataServerException: HTTP Error 400: Bad Request
```

**Comment by fejta** [comment]
The job provides explicit credentials:

`GOOGLE_APPLICATION_CREDENTIALS=/etc/service-account/service-account.json`

Therefore it needs to use those credentials, not grab credentials from the GCE VM, which it appears to be doing:

```  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 205, in GetCredentials
    cred = provider.GetCredentials(account)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 258, in GetCredentials
    return AcquireFromGCE(account)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 921, in AcquireFromGCE
    Refresh(credentials)```

The job should not implicitly depend on the characteristics of the VM as:
* The job may or may not run on a GCE VM
* The VM may or may not expose the metadata server
* The metadata server may or may not authenticate the same user as the explicitly provided credentials.

If you want it to depend on a metadata server instead of explicit credentials (which is a great idea if it runs on GKE, which is true for these jobs) then follow https://github.com/kubernetes/test-infra/tree/master/workload-identity:

* provide the job with a kubernetes service account,
* declaring which GCP service account the kubernetes service account should authenticate as
* Work with the owner of the GCP service account (most likely test-infra oncall) to ensure the kubernetes service account is authorized to act as the GCP service account.

**Comment by fejta** [comment]
An interesting bit here is that [despite](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1-17/1232945841803628546#1:build-log.txt%3A75) passing kubetest gcp credentials:

```
Run: ('kubetest', '--dump=/logs/artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--provider=gce', '--cluster=e2e-883c1ba842-6c91a', '--gcp-network=e2e-883c1ba842-6c91a', '--check-leaked-resources', '--extract=ci/latest-1.17', '--gcp-zone=us-west1-b', '--ginkgo-parallel=8', '--gcp-nodes=2', '--test-cmd=$GOPATH/src/k8s.io/windows-testing/gce/run-e2e.sh', '--test-cmd-args=--ginkgo.focus=\\[Conformance\\]|\\[NodeConformance\\]|\\[sig-windows\\] --ginkgo.skip=\\[LinuxOnly\\]|\\[Serial\\]|\\[Feature:.+\\] --minStartupPods=8', '--test-cmd-args=--node-os-distro=windows', '--timeout=120m')
```

It doesn't appear to be using them, and/or [they appear to be failing](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1-17/1232945841803628546#1:build-log.txt%3A81) when `Running: gcloud config set project k8s-boskos-gce-project-08` (perhaps gcloud falls back to the metadata server when the explict credentials are unauthorized?):

```
2020/02/27 08:29:38 process.go:153: Running: gcloud config set project k8s-boskos-gce-project-08
Updated property [core/project].
ERROR: gcloud crashed (MetadataServerException): HTTP Error 400: Bad Request
2020/02/27 08:29:39 process.go:155: Step 'gcloud config set project k8s-boskos-gce-project-08' finished in 789.6905ms
```

**Comment by fejta** [comment]
(I'm trying to dig into why kubetest isn't passing the credentials to gcloud correctly and/or why gcloud isn't using them, best as I can tell the job is doing the right thing here)

/area kubetest

**Comment by fejta** [comment]
Not sure why gcloud is failing to use `GOOGLE_APPLICATION_CREDENTIALS=/etc/service-account/service-account.json`

but kubetest should activate the service account before making `gcloud` calls:

https://github.com/kubernetes/test-infra/blob/da16e1b1780da64f9802c3538ccec06332e259e2/kubetest/main.go#L766-L779

bootstrap activates the service account (first line in the file) but that may not be relevant as the scenario overrides the environment:

https://github.com/kubernetes/test-infra/blob/da16e1b1780da64f9802c3538ccec06332e259e2/scenarios/kubernetes_e2e.py#L172

**Comment by pjh** [comment]
The tests were fixed, but they're not broken again as of 03-05 4:15PST. I'll use this issue to investigate.

/assign pjh

**Comment by pjh** [comment]
Probably the same as https://github.com/kubernetes/kubernetes/issues/88913.

**Comment by adelina-t** [comment]
@pjh It most definately is the same. We have it on flannel CI too.

**Comment by pjh** [comment]
/close

I'll check our test results again after https://github.com/kubernetes/kubernetes/pull/88917 goes in (thanks Adelina!).
