### ISSUE TITLE
Ensure merge-bot, prow and testgrid data match

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1654]
merge-bot has a list of blocking jobs
prow has a list of jobs it always runs
testgrid has a blocking job dashboard

We need a unit tests that fails if these lists do not match

**Comment by krzyzacy** [comment]
Prow job is checked [here](https://github.com/kubernetes/test-infra/blob/master/testgrid/jenkins_verify/jenkins_validate.go#L69-L73), I'll update the sq one to use config from PR.

**Comment by krzyzacy** [comment]
we will need to match periodic jobs and testgrid along the way of migration.
