### ISSUE TITLE
PR dashboard: display multiple needed things

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#1655]
I'd like to be able to tell at a glance if it "needs action" because of a rebase or because of something else. Also would be nice to know if it's waiting for permission to test.

**Comment by lavalamp** [comment]
Like, if it "needs review" because there was a rebase, I want to ignore that until the tests are also green.

**Comment by rmmh** [comment]
The orange circle indicates that there are pending tests. That should be enough to not look at PRs with trivial failures.

Do you want to just hide other people's PRs that aren't passing tests from your incoming queue?

**Comment by lavalamp** [comment]
Hm, it's complicated. The first time around I might want to look at it even if the tests aren't passing yet. After the first review round, though, I probably want to ignore until either the tests are passing or it's blocked on me answering a question about one of my comments.

**Comment by lavalamp** [comment]
Speaking of, if you could make it display how many rounds of review a PR has been through, that'd be really useful information. As the 2nd review is probably shorter.

And it'd also be great if it displayed whether I've started a review on github. I had one PR where I started and forgot to submit a review for a long time...

**Comment by fejta** [comment]
/assign @rmmh 

I think we've made a lot of progress here?
