### ISSUE TITLE
Prow issue:

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes/test-infra#16567]
Kubernetes dashboard not accessible

I have changed Dashboard service from CLusterIP to NodePort. Because of the thsis, I am able to access Dashboard using url: <masternode_IP>:<Node_Port_assigned> 

But this is working only in the master node.

When I try to access outside from a machine in the same LAN, I am getting "Page not found"

This is not the case with other services like databases, web apps, etc

**Comment by BenTheElder** [comment]
prow does not have any relationship to the kubernetes dashboard project.
