### ISSUE TITLE
Crier can not cope with multiple decoration configs that have different gcs credentials

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#16568]
**What happened**:

We have different GCS credentials for different buckets, but crier can at most use one via the `--gcs-credentials-file=` flag.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/assign

**Comment by Katharine** [comment]
This feels like an anti-pattern - could you not have it use a single service account that has all the access it uses?

**Comment by stevekuznetsov** [comment]
We considered that, @Katharine -- however, in almost all cases the separation of GCS credentials and buckets is in order to have a more highly privileged bucket (a la k8s/security) and I think creating a large blast radius via credentials kind of defeats the point there.

**Comment by Katharine** [comment]
I'm not sure it's any more defeated than having a bunch of credentials in the same place that sum to the same access.

**Comment by stevekuznetsov** [comment]
I guess if you mean a specific GCS credential which *only* `cier` uses, sure. However, that is still irritating if you have users self-managing their GCS buckets as some super-admin needs to aggregate credentials and users end up having to declare their GCS intent in two places (decoration config and `crier` deployment).

**Comment by alvaroaleman** [comment]
> I guess if you mean a specific GCS credential which only cier uses, sure. However, that is still irritating if you have users self-managing their GCS buckets as some super-admin needs to aggregate credentials and users end up having to declare their GCS intent in two places (decoration config and crier deployment).

IMHO thats normal, different roles need different permissions. And yeah, I tend to agree that at the point where we give crier multiple credentials, its not more secure than just giving it one credential that has the aggregated perms of the other creds. At most it would probably help with bugs in our code that result in uploads to multiple buckets, but that seems unlikely to me and probably doesn't justify the added complexity.

The other idea that came up was to add an optional label selector to crier so it can select/refuse based on org in our case. I am not super fond of this though, because it means we have to operate two criers and we have to duplicate whats in the decoration config in  label selector + matching gcs credential config on crier.

**Comment by alvaroaleman** [comment]
we ended up using one GCP account that has permissions on all buckets.
/close
