### ISSUE TITLE
Allow for organisation level jobs

### ISSUE THREAD

**Issue by telphan** [kubernetes/test-infra#16572]
**What would you like to be added**:

It would be great if one could define presubmit or/and postsubmit jobs at the organisation level. 

```
presubmits:
   org/:
```

**Why is this needed**:

This will significantly reduce the amount of duplication needed when defining common jobs across organisations.

**Comment by alvaroaleman** [comment]
Two main options come to mind, in no particular order:

a) During [config load](https://github.com/kubernetes/test-infra/blob/ca9526d747fd5d2866ba6a13956c82e7a6bd3c8a/prow/config/config.go#L721), do an API call to github, figure out all repos for all orgs that have org-wide jobs configured and populate the [`job config`](https://github.com/kubernetes/test-infra/blob/bd87a79d5e565ec12597baffc82d2a84880e519d/prow/config/config.go#L71) for all repos in the org with that. It would also need the [config agent](https://github.com/kubernetes/test-infra/blob/bd87a79d5e565ec12597baffc82d2a84880e519d/prow/config/agent.go#L70) to fetch the repos for the org, in case they changed.

Main drawbacks: Requires us to have a github client everywhere, we need to regularly do api calls and burn tokens, we are only eventual consistent with this approach

b) Extend the [`GetPresubmits`](https://github.com/kubernetes/test-infra/blob/ca9526d747fd5d2866ba6a13956c82e7a6bd3c8a/prow/config/config.go#L335) function to add jobs from the org.

MainDrawback: `GetPresubmits` wasn't intended to be used by everything, some parts of the code would end up stuffing a lot of nilpointers in it, as they do not have clients available (e.G. `checkconfig`)

**Comment by fejta** [comment]
I am not a huge fan of (a) -- repos may get created after we make the list, the bot may just have access to specific repos, the trigger plugin may just be enabled on specific repos.

**Comment by telphan** [comment]
@fejta what do you think of proposed option b?

**Comment by fejta** [comment]
Yes, (b) seems like the way to go here.
