### ISSUE TITLE
PR author becomes the bot when it's merged

### ISSUE THREAD

**Issue by chizhg** [kubernetes/test-infra#16618]
**What happened**:
For Knative projects, started from around 10AM PST. on Mar. 4th 2020, all PR authors became the `knative-prow-robot`, as shown in https://github.com/knative/serving/commits/master.

The PR author for Istio also changed to the bot, see https://github.com/istio/istio.io/commits/master.

**What you expected to happen**:
The PR author should still be the one who created the PR.

**Anything else we need to know?**:
This should be due to an API change in Github, but I wonder if the fix can be made in Tide.

/help
/area prow/tide

**Comment by clarketm** [comment]
The problem is apparently GitHub platform-wide and specific to squash merging. 

**e.g.**
- https://github.com/chdsbd/kodiak/issues/300
- https://github.com/isaacs/github/issues/1750

**Comment by alvaroaleman** [comment]
This behavior doesn't make any sense and is IMHO a github bug. Merging something doesn't make the merging account the author of the change.

**Comment by howardjohn** [comment]
This is really annoying. I think its a github bug.. look at https://github.com/envoyproxy/envoy/commits/master, thats not even a robot its just someone pressing "merge" on github and its accredited to him. I sent a ticket to github, not sure if it will change anything

**Comment by dims** [comment]
yep. https://twitter.com/andyhayden1/status/1235593402709716992?s=19

**Comment by clarketm** [comment]
Until GitHub fixes this bug, orgs/repos can follow this pattern in Tide as mitigation. https://github.com/istio/test-infra/pull/2464

**Comment by clarketm** [comment]
GH reverted the change. https://github.community/t5/How-to-use-Git-and-GitHub/Authorship-of-merge-commits-made-by-Github-Apps-changed/td-p/48797/page/2

/close
