### ISSUE TITLE
b.gcr.io/cloudsql-docker/gce-proxy needs to change

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#1670]
In `velodrom/mysql/sqlproxy.yaml`, we're referencing `b.gcr.io/cloudsql-docker/gce-proxy:1.05`. `gcr.io` is deprecating the `b.` access method, so this needs to come from somewhere else. Opening an upstream bug as well.

**Comment by zmerlynn** [comment]
https://cloud.google.com/container-registry/docs/support/deprecation-notices

c.f. https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/59

**Comment by apelisse** [comment]
Thanks for opening the bug!

**Comment by nathanjosiah** [comment]
This will stop working on [February 15](https://cloud.google.com/container-registry/docs/support/deprecation-notices), is there an ETA on this so that projects that are depending on this have time to migrate?

**Comment by zmerlynn** [comment]
Ah, I didn't notice https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases - there's already a new image.

**Comment by apelisse** [comment]
Cool, thanks @zmerlynn, I'll update

**Comment by apelisse** [comment]
Fixed by #1768
