### ISSUE TITLE
bazel test flake: AssertionError: 'gs://kubernetes-jenkins/logs/kubernetes-build-1.2/latest-build.txt' not found in []

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/test-infra#1671]
Bazel test continues to fail for #1662 , but the test failure doesn't see how it's related to the PR, which just adds a few new jobs.

Please advise if it's indeed related.

cc/ @SaiedKazemi

**Comment by wonderfly** [comment]
cc/ @krzyzacy Have you seen this before?

**Comment by spxtr** [comment]
#1667

**Comment by spxtr** [comment]
Fixed.
