### ISSUE TITLE
Mungebot: Allow commands anywhere in the comment

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#1673]
Currently, mungegithub will only parse commands that start a comment. You can't do the following:

> I approve this PR:
> /approve

As the `/approve` needs to begin the first line. 

This is related to #1672

**Comment by spxtr** [comment]
For prow I've been using regexs like `(?mi)^\/lgtm\r?$`. That is, multi-line case-insensitive `/lgtm` on its own line.

**Comment by apelisse** [comment]
Thanks for the pointer @spxtr. We had initially decided that it would be confusing to do so. It's time to change our mind ;-)
