### ISSUE TITLE
Prow command to list all possible tests to run on a PR

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#16765]
Crossposting this issue from https://github.com/knative/test-infra/issues/1805

> It's not obvious what tests I can run against a PR. I tend to go to the prow config in this repo but that's not ideal.
> 
> I'd be nice if prow have a command that would list all the tests.
- @dprotaso 
cc @chizhg 

Sounds like a really useful feature to have. 💯

**Comment by stevekuznetsov** [comment]
Possible dupe of https://github.com/kubernetes/test-infra/issues/13059

+100
