### ISSUE TITLE
Mungebot: It takes two cycles to get approved label detected

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#1676]
One cycle is used to see that the approval label should be added, and then it takes another cycle for the submit-queue to see the approved label. I know this problem already existed for lgtm, so we should just do the same.

**Comment by rmmh** [comment]
Can we reorder the mungers to make this happen in one cycle?

**Comment by apelisse** [comment]
That's what I had in mind tbh. I wanted to look at it ... Doing it now ...

Yeah, I think it should work. Let's just do that.
