### ISSUE TITLE
Mungebot: Update to APPROVALNOTIFIER comments are hard to notice

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#1680]
When someone types `/approve`, the comment (usually before that) is updated. It can be confusing as you may not notice the comment has been updated, and wonder if your command has done anything at all.

**Comment by apelisse** [comment]
@grodrigues3 sayd:

> /approve from a invalid approver results in the notification being updated.

**Comment by grodrigues3** [comment]
Sure, but if someone not in the OWNERS file as an approver writes "/approve" I still shouldn't update the comment

**Comment by apelisse** [comment]
I disagree, it will just do nothing? That's one way that we don't care about their opinion (which doesn't promote the idea that we appreciate people approving code, even if it's only informative)

**Comment by apelisse** [comment]
Fixed
