### ISSUE TITLE
velodrome.k8s.io is down

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#16836]
**What happened**:
We've received a few security vulnerability reports related to velodrome.k8s.io.  After some investigation there appears to be no quick way to workaround this, so we've taken it down for the time being.  It is unclear whether we have the bandwidth and demand to prioritize reimplementing velodrome.

**Comment by spiffxp** [comment]
it needs a rewrite to at least:
- uses a more modern version of grafana
- uses a more modern version of influxdb

Preferably it should:
- not actually use any of the code in velodrome/; we've just been using it as a grafana/influxdb stack
- not publicly expose influxdb (but allow metrics prowjobs to write data to influxdb)
- not allow grafana to write data to influxdb

Potentially it could:
- just not use influxdb at all (ie: use an existing cloud service instead)

**Comment by BenTheElder** [comment]
@spiffxp is there any plan to bring this back, at this point?

**Comment by MushuEE** [comment]
/close
Velodrome is now down premaritally (gone)
