### ISSUE TITLE
Approvers: make the approvers assignees for the PR and better blunderbuss integration

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#1687]
Do not implement until suggested approvers becomes deterministic (we currently choose a random subset of people that can approver every file in the PR).  See #1639 

- This may be confusing as the suggested approvers are NOT the only people that can approve the files (all approvers in OWNERs files up the tree can)
- May be confusing depending on whether we unassign approvers after they approve (it also could get annoying to assign and unassign constantly)

- Importantly, if blunderbuss assigns someone to review and that person also has the ability to approve, do NOT assign someone else.

**Comment by grodrigues3** [comment]
Fixed by #1729

**Comment by apelisse** [comment]
Looks that this could use more thought and a better implementation. We also probably need better testing for this code.

**Comment by grodrigues3** [comment]
Should help with PRs like 

https://github.com/kubernetes/kubernetes/pull/42415

which make a one line change but ping both thockin and brendanburns

It will still bother one of them

**Comment by grodrigues3** [comment]
we solved most of this
