### ISSUE TITLE
Can't go get add-hook

### ISSUE THREAD

**Issue by sfxworks** [kubernetes/test-infra#16886]
**What happened**:

Trying to run `go get -u k8s.io/test-infra/experiment/add-hook`

```
go get -u k8s.io/test-infra/experiment/add-hook
# k8s.io/client-go/transport
go\src\k8s.io\client-go\transport\round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool
go\src\k8s.io\client-go\transport\round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool
go\src\k8s.io\client-go\transport\round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool
go\src\k8s.io\client-go\transport\round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool
# k8s.io/test-infra/pkg/ghclient
go\src\k8s.io\test-infra\pkg\ghclient\wrappers.go:203:19: cannot use make([]github.RepoStatus, 0, len(statuses)) (type []github.RepoStatus) as type []*github.RepoStatus in assignment
go\src\k8s.io\test-infra\pkg\ghclient\wrappers.go:205:28: cannot use status.(github.RepoStatus) (type github.RepoStatus) as type *github.RepoStatus in append
```

**What you expected to happen**:
Builds/adds to path just fine

**How to reproduce it (as minimally and precisely as possible)**:
Try with `go version go1.14.1 windows/amd64` or `go version go1.14.1 linux/amd64` or `go version go1.13.4 windows/amd64`

**Comment by clarketm** [comment]
This is because `kubernetes/test-infra` uses replace directives in the `go.mod`. (ref: https://github.com/kubernetes/test-infra/issues/14712#issuecomment-541560441)

You can install `add-hook` using the following command:

```shell
git clone --depth=1 https://github.com/kubernetes/test-infra.git
cd test-infra/experiment/add-hook
go install
```

**Comment by sfxworks** [comment]
Ok, in this case, I got the command to run from this documentation here https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#add-the-webhook-to-github .  Unless I overlooked something, I can make a PR to update it and some of the others.

**Comment by clarketm** [comment]
A PR would be much appreciated, so the docs don't mislead others, thanks!

**Comment by clarketm** [comment]
Alternatively, you could install use [`gobin`](https://github.com/myitcv/gobin) which is a module-aware version of `go`.

**e.g.**

```shell
$ gobin k8s.io/test-infra/experiment/add-hook
```
