### ISSUE TITLE
PR Dashboard: Needs attention when it's LGTM

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#1694]
In the list below, 31783 is LGTM.  Why is it marked "Needs Attention"?

![image](https://cloud.githubusercontent.com/assets/3115/22270767/ff995af6-e245-11e6-8dd3-6d6f345cd4fe.png)

**Comment by lukaszgryglicki** [comment]
I will take a look on this, but this would be my first work on `gubernator` so it will take some time...

**Comment by lukaszgryglicki** [comment]
OK I have a working test infra...
First I see: `gubernator/github/classifier.py`: 
L397: `('needs review', 'waiting', lambda a, u: u == assignee and a in ('comment', 'label lgtm'))`

So assignee will be notified when lgtm label was added to PR.
But this is fine I suppose...

But the I see unconditional loop to notify approvers:
```
422     for approver in payload.get('approvers', []):
423         notify(approver, 'needs approval')
```
My guess is that it can be a cause..... but will check this.

**Comment by lukaszgryglicki** [comment]
I'm not a member, and actually want to become one, but don't know how.

**Comment by fejta** [comment]
Sent you an invite to collaborate on this repo

**Comment by lukaszgryglicki** [comment]
Thanks.

**Comment by lukaszgryglicki** [comment]
I've created PR for this, it will fix described behaviour, but I think that LGTM-em PRs actually should be visible in "Needs Attention".
Assume we have PR that is LGTM-ed.
Author makes some changes to it and pushes.
Then LGTM label is kinda outdated (some changes were made after LGTM), so assignees (reviewers) should take a look again.
And that was the case here imho.
PR here (but I think it needs discussion): https://github.com/kubernetes/test-infra/pull/2570
