### ISSUE TITLE
gcp_janitor deletes instances first causing some recreates 

### ISSUE THREAD

**Issue by oxddr** [kubernetes/test-infra#16965]
**What happened**:
gcp_janitor deleted all instances first. Some of them belonged to managed instance groups, so they were recreated and deleted few seconds later when IGM has been deleted. 

**What you expected to happen**:
Only non-managed `instances` should be deleted first or `managed instance groups` should be deleted before `instances`.

**How to reproduce it (as minimally and precisely as possible)**:
create clusters on GCE using kube-up and clean it up with gcp_janitor/

**Please provide links to example occurrences, if any**:
n/a

**Anything else we need to know?**:
\-

**Comment by ixdy** [comment]
Moving to https://github.com/kubernetes-sigs/boskos/issues/19.
/close
