### ISSUE TITLE
Migrate non-kubernetes orgs and repos off of prow.k8s.io

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#16974]
**What should be cleaned up or changed**:
We should stop accepting k8s-adjacent projects, and make prow.k8s.io an instance of prow responsible solely for the kubernetes project.  

Migrate non-kubernetes orgs and repos off of prow.k8s.io

Specifically:
- [ ] https://github.com/bazelbuild
- [ ] https://github.com/google/cadvisor
- [ ] https://github.com/kubeflow
- [ ] https://github.com/helm/charts
- [ ] https://github.com/containerd/cri
- [ ] https://github.com/tensorflow/k8s
- [ ] https://github.com/tensorflow/minigo
- [ ] https://github.com/spxtr/envoy
- [ ] https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress
- [ ] https://github.com/GoogleCloudPlatform/k8s-cluster-bundle
- [ ] https://github.com/GoogleCloudPlatform/netd
- [ ] https://github.com/cncf/apisnoop
- [ ] https://github.com/cncf/k8s-conformance

There's also the option of asking the maintainers of these projects to donate them to Kubernetes if a SIG is willing to take ownership (ref: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories)

**Provide any links for context**:

**Comment by clarketm** [comment]
For each project, if we choose to migrate a proposal to minimize risk of downtime is:
* Phase 1: migrating project to a dedicated build cluster (e.g. [Kubeflow Prow Migration](https://docs.google.com/document/d/17sA-rRBe30bM034nL353CgrXETfy2vMe2m_g_bB_ILY/edit#heading=h.fxpk50cps4zs))
* [Phase 2](https://docs.google.com/document/d/127tZg2T3_oVHCnCkAqC_zTNOgChV7EN_e1fj4bet3V4/edit) setup bot, webhooks, transfigure, and port Prow config, plugins, kubeconfig and jobs to new instance (ideally with support from tools offered by Prow).
* Phase 3  cleanup task; delete artifacts, redefine cluster, rerun, and bot permissions, and copy over historical job results.

> **Caveat:** the above may not be comprehensive but it is what I have gathered from my experience with Prow migration thus far. Please add input here or in [doc](https://docs.google.com/document/d/127tZg2T3_oVHCnCkAqC_zTNOgChV7EN_e1fj4bet3V4/edit).

**Comment by spiffxp** [comment]
/close 
closing in favor of https://github.com/kubernetes/test-infra/issues/12863
