### ISSUE TITLE
Prow vs GitHub Actions

### ISSUE THREAD

**Issue by dudicoco** [kubernetes/test-infra#16983]
Hi,

We are considering migrating from Jenkins to either Prow or GitHubs Actions.
I'm interested to hear about the pros and cons of each.

The main things that I can think of are:
1. Prow requires management and maintenance while GitHub Actions is a managed service.
2. GitHub Actions requires access to your environment (for example AWS and K8S cluster) which is less than ideal to give such powerful permissions to a third party vendor.

**Comment by sftim** [comment]
/triage support
?

**Comment by midnightconman** [comment]
I know it's not good form to comment on closed issues, but it makes more sense to try and reopen this then try and start a new issue.

Now that github enterprise 3.0 is in RC, github actions and packages will be coming to GHE soon. As such, we will be looking at leveraging github actions were we can. Using prow internally, this means we are interested in how prow can interact with github actions... has there been any thought to building a github actions operator or how prow might leverage github actions?

@stevekuznetsov you might know, or could you cc anyone that might know or be interested.

**Comment by midnightconman** [comment]
I'll go ahead and open a new issue also. 😸
