### ISSUE TITLE
prow.k8s.io boskos instance ran out of free resources

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#16987]
**What happened**:
Boskos resources started to get stuck in cleaning around 5:30am PT; by 6:24am boskos ran out of free resources 

https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1

This prevents all CI jobs that rely on boskos to fail

**Comment by spiffxp** [comment]
Workaround: https://github.com/kubernetes/test-infra/pull/16984
Update boskos: https://github.com/kubernetes/test-infra/pull/16985

**Comment by ixdy** [comment]
We appear to be recovering: https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1

**Comment by spiffxp** [comment]
Looks good.  Waiting for GCE project usage graph to return to normal before closing this

**Comment by spiffxp** [comment]
/close
<img width="1425" alt="Screen Shot 2020-03-27 at 12 40 36 PM" src="https://user-images.githubusercontent.com/49258/77793908-3184a200-7028-11ea-8607-6e782ba7ab64.png">

**Comment by droslean** [comment]
There are a lot of jobs that are still failing because of a lack of resources.
```console
W0327 22:46:13.232] ERROR: (gcloud.compute.instances.list) Some requests did not succeed:
W0327 22:46:13.232]  - Invalid value for field 'zone': 'us-west4-a'. Unknown zone.
W0327 22:46:13.232]  - Invalid value for field 'zone': 'us-west4-b'. Unknown zone.
W0327 22:46:13.232]  - Invalid value for field 'zone': 'us-west4-c'. Unknown zone.
W0327 22:46:13.232] 
```

@spiffxp Can you check? 
https://testgrid.k8s.io/sig-release-master-blocking
https://testgrid.k8s.io/sig-release-master-informing
https://testgrid.k8s.io/sig-release-1.18-blocking
https://testgrid.k8s.io/sig-release-1.18-informing

**Comment by spiffxp** [comment]
Looks like it resolved overnight
