### ISSUE TITLE
Prow deck stopped working for large jobs

### ISSUE THREAD

**Issue by mm4tt** [kubernetes/test-infra#17012]
Issue originally reported on Slack: https://kubernetes.slack.com/archives/C7J9RP96G/p1584958305001400

** How to reproduce **
Open any job from https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness, e.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1244233337581604864
The job page won't load, instead you'll see the following error
![ARKt3PwJTd6](https://user-images.githubusercontent.com/2604887/77904158-5bd29b80-7284-11ea-8fa6-98acbed11b4e.png)

@Katharine helped us to debug a similar issue for our internal prow instance and it turned out to be too short LB timeout. The deck needed 40+ seconds to load a test run while the LB timeout was only 30s. I expect this one to be a similar case. Changing the LB backend services timeout fixed the problem for our internal prow.

Not being able to see job results in prow makes it really hard for our oncall to do their job. I'd really appreciate if someone could help us here.

**Comment by oxddr** [comment]
@michelle192837 any chance you can have a look at this issue today? This affects our ability to debug scalability tests - we can't access logs via Prow.

**Comment by michelle192837** [comment]
Thanks for your patience! I updated the load balancer timeout manually, will see if that sticks and helps out.

**Comment by michelle192837** [comment]
Looks like this is (slowly) working now, I got https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1244957997189304325 to load eventually. Let us know if it stops working again!

**Comment by mm4tt** [comment]
Thanks a ton!
