### ISSUE TITLE
Add a prow controller manager binary

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#17024]
**What would you like to be added**:

A prow controller manager binary that contains:
* Sinker
* Plank
* Crier
* Jenkins opreator

Probably more in the future

**Why is this needed**:

The current design of "one binary per controller" has a set of drawbacks:
* It makes prow hard to debug for ppl that are not intimatedly familiar with its architecture
* It makes prow hard to setup, because a total of a billion flags has to be set properly
* It creates a needless amount of overhead on the apiserver due to zero cache sharing
* It increases the overhead for adding something to Prow

A sample of "Weird things we did because overhead of a new component is too high": The `abortDuplicates` functionality is in a library and imported by multiple agent implementations instead of having one controller that sets unneeded ProwJobs to aborted via a `spec` field and then have all the agents abort the test workloads based on that.

/area prow

**Comment by tehcyx** [comment]
Wouldn't it be better if that was handled similar to how hook plugins are handled right now, so that the proposed components would be plugins of a prow-controller-manager.

Thinking of that approach since not everyone is using e.g. crier, jenkins operator. Plank and sinker could be enabled by default and if someone wants more, enable more?

**Comment by alvaroaleman** [comment]
> Wouldn't it be better if that was handled similar to how hook plugins are handled right now, so that the proposed components would be plugins of a prow-controller-manager.

> Thinking of that approach since not everyone is using e.g. crier, jenkins operator. Plank and sinker could be enabled by default and if someone wants more, enable more?

Generally, adding flags to enable/disable certain controllers could make sense. IMHO all of the mentioned controllers should be enabled, they will not do anything if you don't use them.

**Comment by fejta** [comment]
Hook and deck have different availability requirements and therefore should remain separate. Merging the other stuff -- how about horologium? -- makes sense.

**Comment by alvaroaleman** [comment]
/remove-lifecycle-stale
This actually exists already at https://github.com/kubernetes/test-infra/blob/3c8c05e6db807a2edb26f354cfd069fea3e1080d/config/prow/experimental/controller_manager.yaml and currently contains the PlankV2 implementation
