### ISSUE TITLE
prow: make pprof and metrics port configurable

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/test-infra#17033]
**What would you like to be added**:
I would like to be able to configure the metrics and pprof port

**Why is this needed**:
It's not possible to run multiple prow components locally for development purposes because they are using the same metrics and pprof port. Adding a flag to these components to make it configurable should solve the problem.

**Comment by BenTheElder** [comment]
sounds reasonable to me, add some flags w/ defaults to the current values?
cc @stevekuznetsov @alvaroaleman

**Comment by alvaroaleman** [comment]
sure, sounds good to me

**Comment by sbueringer** [comment]
@BenTheElder @alvaroaleman added a PR to implement this issue.
