### ISSUE TITLE
PR author becomes the bot when it's merged

### ISSUE THREAD

**Issue by Arhell** [kubernetes/test-infra#17050]
**What happened**:
Today
The PR author for Istio also changed to the bot, see https://github.com/kubernetes/website/commits/master

**What you expected to happen**:
The PR author should still be the one who created the PR.

old issue #16618

**Comment by spiffxp** [comment]
I think this is WAI. https://github.com/kubernetes/test-infra/pull/16892 switched the merge method from squash to merge for kubernetes/website.  The bot is the author of the merge commit; the commits in the PR are untouched.

Do you have an example for istio?

**Comment by Arhell** [comment]
@spiffxp 
The problem is solved, everything works out fine.
Commit is visible on its creation day.

That is, he was on March 8, and stayed there and not as before on a current day

/close
