### ISSUE TITLE
Support reporting information from jobs to GitHub comments and annotations

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#17056]
**What would you like to be added**:

I would like a job to be able to trigger comments to the associated PR. I would imagine this would be similar to the lenses, where we would output some `github-comments.md` file and it would trigger the comments when the job completes.

**Why is this needed**:

The main case is warning/information messages about a job. For example, we currently have an optional job that just fails immediately and logs something like "WARNING: this will push to production in postsubmit". However, making a job fail is not great, especially if its a less severe warning. For example, we could report the difference in coverage, difference in benchmark times, whether the external API changed or not, etc.

cc @clarketm

**Comment by clarketm** [comment]
@Katharine 

Could you provide an estimate of how much effort this would take?

**Comment by howardjohn** [comment]
Forgot to mention, an alternative would be to have the job itself add the comment, but then the job becomes fairly complicated and requires priviledges

**Comment by BenTheElder** [comment]
we have jobs that comment with wholly-unprivileged secondary account(s) (@fejta-bot)

**Comment by brian-avery** [comment]
This feature would be awesome to have.

**Comment by spiffxp** [comment]
/sig testing
/remove-lifecycle rotten
/reopen

>This feature would be awesome to have.

Agreed, but we lack contributor bandwidth to do so.  Are you interested in working on this @brian-avery?

**Comment by pohly** [comment]
@rajaskakodkar : did you have a chance to look into implementing this?

To recap the discussion that you, @aojea and I had at KubeCon: the best approach seems to be to let Prow jobs produce artifact files with a certain naming scheme. Then the code that reports back to GitHub needs to check the gcp bucket of a finished job for such files, load them, and publish comments and annotations.

**Comment by rajaskakodkar** [comment]
@pohly I haven't gotten time to implement this but this is on my todo list and I should be able to get to this by next week. I'll post my updates here or raise a PR.

**Comment by BenTheElder** [comment]
Folks: before writing any code here please bring a design to SIG Testing for discussion, It's not clear to me that any prow owners have approved implementing this or weighed in how it might be done acceptably. (you can see who that is in `prow/OWNERS`)

**Comment by pohly** [comment]
There were several discussions around this on Slack and at KubeCon EU, but I agree, presenting to SIG Testing would be good to get everyone on the same page.

**Comment by pohly** [comment]
/retitle Support reporting information from jobs to GitHub comments and annotations

**Comment by BenTheElder** [comment]
ACK, usually a change of this scope results in an ask for a lightweight design doc (~google doc, not a full KEP) and some discussion around that before proceeding, typically posted back to the issue.

I just didn't want to see anyone put in a lot of work and then get blocked 😅

**Comment by BenTheElder** [comment]
We're not currently planning this, if there are further discussions please move to prow's dedicated repo at github.com/kubernetes-sigs/prow.
