### ISSUE TITLE
Make janitor handle CI jobs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#1706]
Currently it only handles a list of [pull projects](https://github.com/kubernetes/test-infra/blob/master/jobs/maintenance-pull-janitor.sh#L21-L32), open it to track this for ci projects support.

cc @ixdy if you know there's a list of ci projects we've created..

If not I'll try to iterate all the job script.

**Comment by fejta** [comment]
Read jobs/config.json to figure this out?

**Comment by krzyzacy** [comment]
PROJECT are within FOO.sh, or we want to put them out to config.json?

**Comment by ixdy** [comment]
The last time we tried to get the full list of projects, we just [searched for PROJECT= in the job yaml](https://github.com/kubernetes/test-infra/blob/master/jenkins/check_projects.py#L119).

**Comment by krzyzacy** [comment]
That looks super out-dated, hope nobody is using it...

A side question, I remember @spxtr once told me I should not delete old soak resource,  reason behind? I'm not very familiar with what soak job does.

**Comment by fejta** [comment]
Sen, you're deleting all the FOO.sh

**Comment by krzyzacy** [comment]
@fejta That's definitely true! I mean FOO.env!

**Comment by fejta** [comment]
True, good point. Is PROJECT=blah in foo.env the desired end state or an intermediate state?

I'd just request that you write this code (which is ideally more robust than a regex/grep) to work for where you want the future code to look like rather than where it is today.

Also stay aware of https://github.com/kubernetes/test-infra/issues/1531

**Comment by krzyzacy** [comment]
That's also a good point...

I wish there's some gcloud api can list all those for me (regex search k8s-jkns-e2e?), rather than do a file parsing.
