### ISSUE TITLE
Prow failed to execute properly gce-master-scale-performance on 04/01

### ISSUE THREAD

**Issue by oxddr** [kubernetes/test-infra#17067]
**What happened**:
Prow failed to execute properly `gce-master-scale-performance` on 04/01. Test ended up in a weird state:
1. started at Wednesday, April 1, 2020 5:02:14 PM and finished at Thursday, April 2, 2020 2:55:33 AM according to [started.json and finished.json](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1245396009266188301/). That's almost 3 hours earlier than usual
1. No other [artifacts](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1245396009266188301/) were saved except metadata JSONs. 
1. [build-log.txt](https://prow.k8s.io/log?id=1245396009266188301&job=ci-kubernetes-e2e-gce-scale-performance) contains only tiny portions of logs. 

**What you expected to happen**:
Prow should recorded full build-log.txt and more importantly execute test properly. 

I'd like to understand whether it was one-of thing or something to improve. Scalability tests are expensive and we run them rarely. Losing any run is a pain to us. 

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1245396009266188301

**Anything else we need to know?**:

/area prow
/sig scalability

**Comment by oxddr** [comment]
Assigning to test-infra oncall
/assign @BenTheElder

**Comment by BenTheElder** [comment]
> Prow should recorded full build-log.txt and more importantly execute test properly.

Prow fails to record these entries alll the time. This is a systemic issue, not something new.

It should at least record the pod info more reliably with some work @Katharine did. (click the "yaml" button on the prow.k8s.io page)

In this case it appears the pod never readied.

raw https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1245396009266188301/podinfo.json
