### ISSUE TITLE
Prow issue: broken link on issue message from "k8s-ci-robot" 

### ISSUE THREAD

**Issue by flaviamissi** [kubernetes/test-infra#17080]
**What happened**:

Clicked a link to "the contributor guide" posted in an issue message by the k8s-ci-robot and the link lead me to an anchor that no longer exists: https://git.k8s.io/community/contributors/guide/#issue-assignment-in-github.

**What you expected to happen**:

The link should redirect me to the correct document containing the anchor, which afaik is
https://git.k8s.io/community/contributors/guide/first-contribution.md#issue-assignment-in-github

**How to reproduce it (as minimally and precisely as possible)**:

Check out one of the bot's comments, [this is the one](https://github.com/kubernetes/kubernetes/issues/89016#issuecomment-601310494) where I noticed the issue, then click on "see the contributor guide" link.
Alternatively, one could check the link from the source code as well, which can be found [here](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/assign/assign.go#L192).

**Please provide links to example occurrences, if any**:

https://git.k8s.io/community/contributors/guide/first-contribution.md#issue-assignment-in-github

**Anything else we need to know?**:

I'll gladly send in a PR with the link update!

**Comment by nikhita** [comment]
@flaviamissi Thanks for catching that! :100: 

> I'll gladly send in a PR with the link update!

The source code you link mentioned in indeed the one that should be updated. Feel free to send a PR. :)

/sig contributor-experience
