### ISSUE TITLE
Fix config forker annotations in scalability jobs

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/test-infra#17097]
Our templates were incorrectly using perf-tests branches.See https://github.com/kubernetes/test-infra/pull/17089 for more context

We need to double check our templates to confirm that this won't happen in the future again.

/assign @jkaniuk 

/cc @mm4tt @kubernetes/sig-scalability-bugs

**Comment by jkaniuk** [comment]
We've decided to not automatically use perf-tests branches in presubmits, as creation of new perf-tests branch is a manual process and happens later than roll of kubernetes versions.

So presubmit flow right now is:
- k/k master jobs points to perf-tests/master

after forking:
- presubmit k/k/release-1.18 still point to perf-tests/master
- periodic on k/k/release-1.18 point to perf-tests/release-1.18 (triggering alerts)

manual work is needed:
- creation of new perf-tests branch to fix alerts
- when periodics are good - switching presubmits to release branch

**Comment by jkaniuk** [comment]
That last step is easy to forget unfortunately.
We have an internal issue (b/146629137) with reminder to update perf-tests branches.
Any idea how to do that better?

**Comment by wojtek-t** [comment]
Thanks for looking into it.

For now, I was simply manually cutting branches in github UI.
But maybe what we should do is to create a script that will:
- create branch
- file an issue (and assign it to whoever is running that script) to switch stuff in test-infra

It would make it much harder to forget about the second step.

**Comment by jkaniuk** [comment]
Looks like pull-kubernetes-kubemark-e2e-gce-big template is still broken (and 1.20 presubmit as well):

https://github.com/kubernetes/test-infra/blob/a112810d6a51fff217455593e6d085c5ab1e2a0a/config/jobs/kubernetes/sig-release/release-branch-jobs/1.20.yaml#L1309

**Comment by jkaniuk** [comment]
@marseel as an oncall

**Comment by jkaniuk** [comment]
They are definitely not good.

1.20 was fixed manually, but 1.21 is wrong

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/release-branch-jobs/1.21.yaml
```
   - base_ref: master
      org: kubernetes
      path_alias: k8s.io/perf-tests
      repo: perf-tests
```

I'm not sure how config forker works now, after switching to podutils.

We have `--repo=k8s.io/perf-tests=master -> --repo=k8s.io/perf-tests=release-{{.Version}}`
which is clearly wrong after switching to podutils.

We also have some config forker annotations missing. My previous comment suggested e.g. `pull-kubernetes-kubemark-e2e-gce-big` was wrongly set.

**Comment by jkaniuk** [comment]
/retitle Fix config forker annotations in scalability jobs

For reference:
https://github.com/kubernetes/test-infra/tree/master/releng/config-forker

**Comment by marseel** [comment]
Looks like my fix worked and version of perf-tests for https://github.com/kubernetes/test-infra/blob/aa59567d4dd30d97d5cee5c8b8c11a83cbe04714/config/jobs/kubernetes/sig-release/release-branch-jobs/1.23.yaml#L389
is correct.

/close
