### ISSUE TITLE
Allow owners files to reference groups of individuals defined within repo

### ISSUE THREAD

**Issue by cpoole** [kubernetes/test-infra#17099]
I understand why GitHub groups are not supported - the lack of audit trail is a legitimate and correct concern. However, groups or pattern matching is a sorely needed feature. 

**What would you like to be added**:
I would like to propose the creation of an OWNER_GROUPS file at the root of the repo that defines owners aliases that represent a list of GitHub users.

Then within the OWNERS file I could reference one of those groups.

for example
`OWNER_GROUPS`
```yaml
groups:
- name: reviewer-group-1
  members:
  - cpoole
  - johnDoe
  - sally
```

Then within an `OWNERS` file I can reference this group:

```yaml
approvers:
- @reviewer-group-1

```

**Why is this needed**:
I have the same group of people responsible for almost 20 different folders but because of how OWNERS works I must specify these people over and over. If one of them changes teams this is a herculean task - cruft accumulates rapidly. 

This looks straightforward to add. I can open a PR to address this if the maintainers are willing to consider the enhancement.

**Comment by alvaroaleman** [comment]
Unless I misunderstand this, this is already possible today by defining a group of ppl in an [`OWNERS_ALIASES` file](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners_aliases) and then referencing the name of the group in the `OWNERS` file

**Comment by cpoole** [comment]
:man_facepalming: you're totally right. Nevermind me.

Thanks!
