### ISSUE TITLE
AuditSink not work with service-name, work only with CLUSTER-IP with Falco 0.19 and k8s 1.17.4

### ISSUE THREAD

**Issue by degilq** [kubernetes/test-infra#17129]
AuditSink not work with service name, work only with CLUSTER-IP

I try with 

apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: falco-audit-sink
spec:
  policy:
    level: RequestResponse
    stages:
      - ResponseComplete
      - ResponseStarted
  webhook:
    throttle:
      qps: 10
      burst: 15
    clientConfig:
       service:
       namespace: falco
       name: FALCO-SERVICE-NAME
       port: 8765
       path: /k8s-audit

only work with

apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: falco-audit-sink
spec:
  policy:
    level: RequestResponse
    stages:
      - ResponseComplete
      - ResponseStarted
  webhook:
    throttle:
      qps: 10
      burst: 15
    clientConfig:
      url: "http://10.43.72.138:8765/k8s-audit"

**Comment by BenTheElder** [comment]
this is the wrong repo, this repo hosts tools used by the project, you want https://github.com/kubernetes/kubernetes
