### ISSUE TITLE
Prow issue: Cancel Cherry-Pick

### ISSUE THREAD

**Issue by andrewballantyne** [kubernetes/test-infra#17174]
Would like to request the ability to undo an accidental cherry-pick.

`/cherry-pick my-branch` creates the cherry-pick request for branch "my-branch"

`/cherry-pick cancel` creates another cherry-pick request for branch "cancel"

I looked around and I couldn't find any documentation for how to cancel a cherry-pick from the 
OpenShift Cherrypick Robot.

**Comment by clarketm** [comment]
You can delete the comment.
