### ISSUE TITLE
Update tekton pipelines to enable working with v1beta1

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/test-infra#17180]
Tekton pipelines have recently moved from `v1aplha1` to `v1beta1`.

Prow currently assumes pipeline specs in prow job are `v1alpha1` and using a `v1beta1` spec is not possible.

This issue should track tasks to be done in order to allow using Prow with different Tekton pipelines versions.

Implementation should take care of existing Prow jobs and provide a smooth transition path.

From the top of my head, list of things to do:
- [ ] Update tekton client code gen to support v1beta1 (https://github.com/kubernetes/test-infra/pull/17181)
- [ ] Detect supported pipeline versions in the pipeline controller
- [ ] Add support for pipeline version in pipeline controller
- [ ] Add support for multiple pipeline version in Prow jobs

If you think about something else, please comment, i will update the PR description.

**Comment by mikesplain** [comment]
@eddycharly Do you plan to pick this back up? I have a working branch of v1beta1 which includes some of your changes, I'm looking for the best way to move this forward.  Were you planning to support both initially?

**Comment by goern** [comment]
@harshad16 and I would be happy to test this out on OpenShift ;)
