### ISSUE TITLE
Configurator Test is unclear when adding tests to legacy-exempted groups

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#17193]
**What should be cleaned up or changed**:
The error message that results when adding TestGrid presubmits or references to legacy items is confusing, making completing [this TODO](https://github.com/kubernetes/test-infra/blob/9beef71a5dacf41b15fa1957b545922876ceb6a5/config/tests/testgrids/config_test.go#L346-L348) harder.

```
--- FAIL: TestKubernetesProwInstanceJobsMustHaveMatchingTestgridEntries (4.48s)
    config_test.go:444: Testgrid group cloud-provider-gcp-tests does not have a matching jenkins or prow job
FAIL
```

A clearer message pointing to the TODO may help continuous migration

**Provide any links for context**:
https://github.com/kubernetes/test-infra/pull/17184#issuecomment-612310949

/assign
/assign @spiffxp 
/help

**Comment by ZhiFeng1993** [comment]
@chases2  can I take this issue?
