### ISSUE TITLE
Gubernator should also show passed and skipped tests

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#172]
It can be helpful for determining whether a run passed because all tests actually passed or if many tests were skipped.

This can probably just be a smaller list at the bottom underneath any failures.

**Comment by rmmh** [comment]
I doubt the usefulness of showing skipped tests. Showing tests that succeeded sounds good.

**Comment by fejta** [comment]
Is there an ETA for fixing this? If not I would like to close it out.

**Comment by smarterclayton** [comment]
Can we display a count in the table at the top?

**Comment by smarterclayton** [comment]
I'm going to fix this now

**Comment by smarterclayton** [comment]
![result](https://www.dropbox.com/s/gwlsbdtcdykwnho/Screenshot%202017-08-15%2011.21.32.png?raw=1)

How about ^
