### ISSUE TITLE
testgrid conformance uploader doesn't handle partial results

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#17207]
**What happened**:

https://prow.k8s.io/view/gcs/ppc64le-kubernetes/logs/ci-conformance-kubernetes/90 is detected as passing despite being interrupted before completing tests

**What you expected to happen**:

this should be detected as failing

**How to reproduce it (as minimally and precisely as possible)**:

terminate ginkgo early and use that log

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/assign

**Comment by BenTheElder** [comment]
I don't have time to handle this right now, and this isn't used for any official results nor for any release blocking CI.

FYI though @dims

**Comment by dims** [comment]
Somewhat related to https://github.com/kubernetes/kubernetes/pull/89944 and https://github.com/onsi/ginkgo/issues/222 (leaving bread crumbs for myself)

**Comment by dims** [comment]
thanks for the heads up @BenTheElder

**Comment by BenTheElder** [comment]
I don't think i'm going to get to this anytime soon, this thing has relatively low usage and we're not really relying on the signal.
