### ISSUE TITLE
/retest command doesn't work if it's not the last line of PR comment

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#17218]
**What happened**:
Multiple commands in a single PR comment, `/retest` doesn't work if it's not the last line

**What you expected to happen**:
Each line is respected as it's own command

**How to reproduce it (as minimally and precisely as possible)**:
Open a PR, comment
```
/retest
/lgtm
```

**Please provide links to example occurrences, if any**:
https://github.com/knative/serving/pull/7607#pullrequestreview-393909183

**Anything else we need to know?**:
I think this is caused by multiple regex matching introduced in https://github.com/kubernetes/test-infra/pull/16926

**Comment by stevekuznetsov** [comment]
Another example here:
https://github.com/openshift/openshift-apiserver/pull/84#issuecomment-614679531

**Comment by adshmh** [comment]
Yes, my tests show the same. Will submit a PR to fix it.
