### ISSUE TITLE
Approvers: Machine-Readable Assignments

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#1727]
To integrate approvers into Gubernator, I need to parse the comments that the bot leaves. The format might not be stable, so  it should leave machine-readable (JSON?) comments, like so:

```
[APPROVALNOTIFIER] This PR is NOT APPROVED

Needs approval from an approver in each of these OWNERS Files:

test/OWNERS
We suggest the following people:
cc @someuser

<!-- META={"files": ["test/OWNERS"], "approvers": ["someuser"]} -->
```

Just having the unapproved files and suggested approvers should be sufficient for the dashboard.

**Comment by apelisse** [comment]
Should "approvers" contains the list of suggested people (that doesn't include people who have already approved)?

**Comment by rmmh** [comment]
Yes. You can probably leave off files as well for now-- it might be useful in the future, but not currently.

**Comment by grodrigues3** [comment]
cool cool.  I'll work on this

**Comment by grodrigues3** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/1823
