### ISSUE TITLE
collect data on which files conflict causing rebases

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#1728]
Anecdotally we know that rebases on generated code is painful, but we don't have data on what files are the worst offenders, or how frequently it really occurs.

GitHub exposes this data in the web UI, but it isn't accessible from the API.

Maybe the munger can screen-scrape the UI when it reports that a PR needs rebase? Or maybe it can calculate the conflict itself?

Not sure where we'd save the data for later analysis. Thoughts?

**Comment by spxtr** [comment]
> GitHub exposes this data in the web UI, but it isn't accessible from the API.

:rage: 

> Or maybe it can calculate the conflict itself?

We've ran into strange behavior where GitHub claims a merge conflict but then git merges just fine. We can calculate the list of changed files in the PR and the list of changed files in the target branch and just save their overlap. It's not perfect, but it should give us an idea.

**Comment by fejta** [comment]
We need to make progress on this, find and owner for it and/or close it.

**Comment by ixdy** [comment]
We've got a [script](https://github.com/kubernetes/test-infra/blob/master/experiment/find-merge-conflicts.sh) that does this now. There's no automation for it, though.

**Comment by spxtr** [comment]
We can run the script in a periodic job and shove the results in some database. Possibly rewrite it in go first.
