### ISSUE TITLE
test-infra postsubmits are broken

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#17298]
**What happened**:

The post-test-infra-push-prow fails consistently:
https://prow.k8s.io/?job=post-test-infra-push-prow

Error seems to be `Current Bazel version is 2.0.0; expected at least 2.2.0`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/cc @fejta

**Comment by spiffxp** [comment]
/area bazel
/cc @fejta 
`gcr.io/k8s-testimages/gcloud-bazel` needs to be updated to use bazel 2.2.0 (and then 2.2.0 images pushed and jobs updated) or https://github.com/kubernetes/test-infra/pull/17281 needs to be reverted

**Comment by fejta** [comment]
Best as I can tell all the failing jobs have been rerun: https://prow.k8s.io/?repo=kubernetes%2Ftest-infra&type=postsubmit
