### ISSUE TITLE
PR Dashboard: Explain what icons mean

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#1731]
My dashboard currently shows some red Xs and a yellow dot.  I think they encode something about PR state, but hovering over them shows nothing, and there's no legend.

Hover would be fine.

**Comment by mml** [comment]
Ping.  This is still true.

/remove-lifecycle rotten

**Comment by mml** [comment]
This is both a usability and an accesibility issue.  It deserves more attention.

@kubernetes/sig-testing-bugs

**Comment by BenTheElder** [comment]
Pretty sure these are the state of the PR's tests, (Red -> failed, Yellow -> incomplete, Green -> passing). Agree that this should be improved.
