### ISSUE TITLE
failed builds not showing up in test-grid

### ISSUE THREAD

**Issue by deads2k** [kubernetes/test-infra#1734]
I was trying to investigate the SQ block for this job https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/ (1625-1628 failing), but the test grid results stopped at 1624, https://k8s-testgrid.appspot.com/sq-blocking#node-kubelet .  

It used to be the case that test-grid showed the failures so that you could see the commits being used and track the problem back.  Can we get that feature back?

**Comment by deads2k** [comment]
@liggitt so we don't double open.

**Comment by ixdy** [comment]
looks fine now? sometimes the testgrid updater gets stalled for some reason. @krzyzacy

**Comment by krzyzacy** [comment]
It's about ~30min-1h late since it's trying to round-robin to catch up all the tests and these days there are more tests running, we are looking into speed the update process up. Seems it's caught up now, and each one has sort a different flake?
