### ISSUE TITLE
Add a positive reaction to expanding OWNERS

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1736]
Check out [test-infra/prow/plugins/heart/heart.go](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/heart/heart.go), which smiles at automatic merges.

I would love to see prow smile at all PRs which expand the OWNERS file, this will help nudge people to be more liberal about doing this activity.

Anyone interested in this quick task to help us empower the community?

cc @apelisse @grodrigues3

**Comment by alindeman** [comment]
I'll take a stab at this.

**Comment by fejta** [comment]
Awesome! Thank you very much :-)

**Comment by fejta** [comment]
Woo!!
