### ISSUE TITLE
Github token leaked in clone-log.txt

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/test-infra#17386]
When cloning a private repository, the Github token will appear in clear text in clone-log.txt file (uploaded in the logs bucket).

Here is an example of the log content (real token redacted):
```
# Cloning org/repo at master(3cecffcf737695e38c8aea5b6c04d24a1dd5223b)
# Checking out pulls:
#	14(43a3c6eaa8a416456619af8d5d29e36e088d40f7)
$ mkdir -p /home/prow/go/src/github.com/org/repo
$ git init
Initialized empty Git repository in /home/prow/go/src/github.com/org/repo/.git/
$ git config user.name ci-robot
$ git config user.email ci-robot@k8s.io
$ git fetch https://cf07....:x-oauth-basic@github.com/org/repo.git --tags --prune
From https://github.com/org/repo
 * branch            HEAD       -> FETCH_HEAD
$ git fetch https://cf07....:x-oauth-basic@github.com/org/repo.git master
From https://github.com/org/repo
```

It looks like the code responsible for this is here:

https://github.com/kubernetes/test-infra/blob/a5764e9eea3e155bc7084b0387479823b794baa3/prow/pod-utils/clone/clone.go#L124-L128

Is there something we can do to prevent this ?
Should this be considered a security risk ?

**Comment by droslean** [comment]
Even though we censored the actual secret in the logs, we still generating the `clone-records.json` file from the actual records serialized. see https://github.com/kubernetes/test-infra/blob/master/prow/clonerefs/run.go#L107-L114

**Comment by eddycharly** [comment]
Thanks for taking care of it !
