### ISSUE TITLE
Jenkins PR job details link url is wrong

### ISSUE THREAD

**Issue by colhom** [kubernetes/test-infra#174]
The `Details` link for PR e2e tests look like this:

`https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/$%7BghprbPullId%7D/kubernetes-pull-build-test-e2e-gce/$%7BBUILD_NUMBER%7D/`

It looks like the `BUILD_NUMBER` Jenkins parameter is not getting substituted in properly.

Reference PR: https://github.com/kubernetes/kubernetes/pull/26754

\cc @spxtr @fejta @ixdy

**Comment by ixdy** [comment]
it isn't resolved until the run actually starts. it should be resolved after that.

**Comment by colhom** [comment]
Yep, that's it.
