### ISSUE TITLE
Premature Docker service stopping in bootstrap

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/test-infra#17412]
https://github.com/kubernetes/test-infra/blob/56e63b79d2aa6dc65427bb195d728fcbbf6bdc96/images/bootstrap/runner.sh#L81

**What happened**:
I ran a Prow job using bootstrap on our internal SIG Scalability Prow cluster with `DOCKER_IN_DOCKER_ENABLED` env var set to `true`. To my surprise, Docker service was down (any `docker` CLI call resulted in a failure like `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`).

I believe the culprit is [this](https://github.com/kubernetes/test-infra/blob/56e63b79d2aa6dc65427bb195d728fcbbf6bdc96/images/bootstrap/runner.sh#L81) line - after starting Docker service, `cleanup_dind` function is called right after and it stops the service even before the job is started. IIUC, `cleanup_dind` was supposed to be called only after the job finishes (right [here](https://github.com/kubernetes/test-infra/blob/56e63b79d2aa6dc65427bb195d728fcbbf6bdc96/images/bootstrap/runner.sh#L113)).

**Comment by tosi3k** [comment]
Assigning current test-infra oncall.
/assign @michelle192837

**Comment by alvaroaleman** [comment]
Got fixed in https://github.com/kubernetes/test-infra/pull/17423

**Comment by BenTheElder** [comment]
I didn't see this bug, but it should both be cleaned up and the updated images widely rolled out

**Comment by BenTheElder** [comment]
this was tracked in https://github.com/kubernetes/kubernetes/issues/90568
