### ISSUE TITLE
mungegithub: Make approval label sticky

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#1743]
I'm proposing that we make the approval sticky, as in it stays if the code is modified/new code is pushed.

I think we have much more to win by trusting people than we have to lose by having to re-approve everything every time. Plus the approval is not "code" related, so I think this is pretty safe.

**Comment by apelisse** [comment]
cc @kubernetes/sig-contributor-experience-proposals @bgrant0607 @philips @grodrigues3

**Comment by apelisse** [comment]
@liggitt @calebamiles any opinion?

**Comment by fejta** [comment]
This sounds great to me. I assume we can add an /approve cancel type command?

**Comment by apelisse** [comment]
Yes
