### ISSUE TITLE
Allowing multiple containers in ProwJob pod spec

### ISSUE THREAD

**Issue by devbharat** [kubernetes/test-infra#17457]
**What would you like to be added**:
I am porting some tests to run with ProwJob and am unable to run a pod spec with more than 1 containers. This seems like a strange restriction, could someone explain why this exists?

**Why is this needed**:
The job is a server client application that is being tested in a pod, with each running in its own container in the pod.

**Comment by devbharat** [comment]
I am not sure why it(or did it?) labeled kind/festure, its related to prow.

**Comment by BenTheElder** [comment]
`kind/` is the label category, and the kind of issue is a feature request. this comes from the issue template.

----

AIUI prow does not intend to support this, that primary container _is_ the test, in which a special entrypoint is injected to monitor the test command output / exit code.

/area prow
/area prow/plank

cc @cjwagner @alvaroaleman

**Comment by alvaroaleman** [comment]
Yeah, this is not something that we want to add to plank.

The approach to offering this would be to use the pipeline controller in prow/cmd/pipeline and setting the `agent` on the job to `tekton-pipeline`. It natively supports this.

However, today the pipeline controller lacks some basic functionality like log publishing. All Prow deployments I know about only use `Plank` via the `kubernetes` agent and no one is currently working on improving the pipeline controller. 

cc @eddycharly as you did some work on the pipeline controller and can probably give more details on where it is today and what shortcomings exist.

**Comment by anthonyrtong** [comment]
Prow now supports adding multiple containers to the podspec.  You are required to enable decoration and to give each of the test containers unique names.  
/close
