### ISSUE TITLE
bugzilla: clone does not set subcomponent when necessary, message is unclear

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#17463]
See https://github.com/openshift/machine-api-operator/pull/579#issuecomment-621903082

The bugs are that we:

1. do not set the subcomponent when we need to
2. tell the user that the failure is for "bug 0" 

/assign @AlexNPavel

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/17483
/close
