### ISSUE TITLE
Pass OAuth token in ghclient to access GitHub Enterprise API Endpoint

### ISSUE THREAD

**Issue by stpabhi** [kubernetes/test-infra#17499]
**What happened**:

`{"component":"unset","error":"error getting bot name: fetching bot name from GitHub: status code 401 not one of [200], body: {\"message\":\"Must authenticate to access this API.\",\"documentation_url\":\"https://developer.github.com/enterprise/2.19/v3\"}","file":"/Users/stpabhi/go/src/k8s.io/test-infra/prow/cmd/deck/main.go:566","func":"main.prodOnlyMain","level":"fatal","msg":"Error getting Git client.","time":"2020-05-01T17:44:22-07:00"}`

**What you expected to happen**:

ghclient able to get bot name 

**Proposed Fix:**

Pass OAuth token [here](https://github.com/kubernetes/test-infra/blob/master/prow/github/client.go#L480)

```
client: &http.Client{
	Timeout:   maxRequestTime,
	Transport: &oauth2.Transport{Source: newReloadingTokenSource(getToken)},
},
```

**How to reproduce it (as minimally and precisely as possible)**:

Run deck with GitHub Enterprise endpoints

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

If this is a reasonable fix, i would like to open a PR

**Comment by alvaroaleman** [comment]
@stpabhi while not immediately obvious, we do set an auth header for the v3 calls as well: https://github.com/kubernetes/test-infra/blob/a551c344cc565d363e68cee05be831126847d33b/prow/github/client.go#L783

The api call you mentioned always requires a token and will never work anonymously, regadless of using Github enterprise or github.com.

What could be the cause of the issue you are seeing is that until recently we used `Authentication: Token << token >>` which might not work on github enterprise: https://github.com/kubernetes/test-infra/pull/17192

Can you check if you are still seeing that issue with a Prow version that has the aforementioned patch?

**Comment by stpabhi** [comment]
@alvaroaleman I'm using v20200424-22d77d1c9 tag.

I have found that the problem is domain redirection. Prow was configured with GHE endpoint A and apparently A redirects (301) to B which is the base_url. Looks like the header is being dropped upon redirection. 

I didn't realize the redirection and made the proposed changes and at the same time :( configured prow to use domain B (unknowingly).  

Thanks for the insight, It helped me find the real issue. We can close this issue.
