### ISSUE TITLE
Prow's /view is a slow to load GCE 5k results

### ISSUE THREAD

**Issue by mborsz** [kubernetes/test-infra#17505]
**What happened**:
I'm trying to debug failing gce 5000 nodes test, e.g.: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1256992291344617478

I noticed that it takes ~20 seconds to load a single page like that.
While the debugging failing test usually involves checking multiple test runs, this is quite inconvenient to wait for each view to load.
**What you expected to happen**:
I expected that this page would load in < 1s.
**How to reproduce it (as minimally and precisely as possible)**:
Just go to https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1256992291344617478
**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
I checked logs of deck component and it looks like most of the time we spend in fetching all files from GCE bucket.
```
{
  component: "deck"   
  duration: "25.539879839s"   
  file: "prow/spyglass/gcsartifact_fetcher.go:146"   
  func: "k8s.io/test-infra/prow/spyglass.(*GCSArtifactFetcher).artifacts"   
  level: "info"   
  msg: "Listed 55930 artifacts."   
 }
```

I checked a code and it looks like we fetch 55930 artifact names (which takes 23 seconds) to filter out ~8 files out of them:
https://github.com/kubernetes/test-infra/blob/2bf808d3b5658669f7b0a1bdf93d1c9b73938dd7/config/prow/config.yaml#L36-L60

I would like to improve this to make sig-scalability life easier. Any suggestion how to do that?

**Comment by mborsz** [comment]
I checked and Google Storage has no API that allows to fetch objects in given bucket that match some regexp (kind of expected). 

I was thinking about migrating out from regexp in `LensFileConfig` to something that can be easier handled by GCS API (e.g. prefix + extension filter or some globs?) and then for each lens, do a separate GCS API call that fetches required_files + optional_fields for that len.
 
@Katharine, WDYT?

**Comment by mborsz** [comment]
Alternatively, we can keep regexps, but say that only "filename" part of the object path will be matched, so e.g.:
* artifacts/junit.*.xml will match all junit*.xml files in artifacts/ directory instead of potentially matching all xml files in all junit* directories
* arti.*facts/*.xml will be prohibited
* .*/*.xml will be prohibited as well

This way, we can implement an optimization for GCS buckets with very nested structure (like ours) to recursively fetch data directly in:
* first in gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1256992291344617478/
* in gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1256992291344617478/artifacts/
this way we can skip fetching data for all nods (which is in some other directories).

**Comment by mborsz** [comment]
I discussed #17515 on chat with @Katharine and the feedback is that it's not viable option as there are some use cases when subdir regexp are needed.

The current idea is significantly simpler:
* update cloud.google.com/go/storage dependency so that it includes https://github.com/googleapis/google-cloud-go/commit/f9fc089da7b416e5cfb30c7f0bc9ce73fc68ed20
* use storage.Query.SetAttrSelection to fetch only names of the objects (we need only those)

This should cut down traffic, cpu load used on deserialization ~10x 

```bash
$ curl -s https://storage.googleapis.com/storage/v1/b/kubernetes-jenkins/o\?prefix\=logs/ci-kubernetes-e2e-gce-scale-performance/1256992291344617478/artifacts/ | wc -c
1414261
$ curl -s https://storage.googleapis.com/storage/v1/b/kubernetes-jenkins/o\?prefix\=logs/ci-kubernetes-e2e-gce-scale-performance/1256992291344617478/artifacts/\&fields\=kind,items\(name\) | wc -c
164997
```

**Comment by BenTheElder** [comment]
Katharine works in wearables now 🙃
cc @cjwagner

**Comment by spiffxp** [comment]
@mborsz I didn't realize you were blocked on https://github.com/kubernetes/test-infra/issues/17546 and ended up updating cloud.google.com/go for other reasons, you may be unblocked now?

**Comment by mborsz** [comment]
@spiffxp Thanks! This indeed unblocked me. I prepared https://github.com/kubernetes/test-infra/pull/19098

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/19098 is in?

**Comment by mborsz** [comment]
#19098 doesn't help that much unfortunately. The 5k result still takes O(tens seconds) to load.

**Comment by mborsz** [comment]
This has been fixed by migrating logs in 5k tests to a separate bucket
