### ISSUE TITLE
Horologium error - a dry-run was requested but required flag -deck-url was unset"

### ISSUE THREAD

**Issue by tseelbach** [kubernetes/test-infra#17503]
**What happened**:
I installed Prow using Manual process but horologium  pod fails to start.  Logs show this error:
{"component":"horologium","error":"a dry-run was requested but required flag -deck-url was unset","file":"prow/cmd/horologium/main.go:77","func":"main.main","level":"fatal","msg":"Invalid options","time":"2020-04-29T11:48:52Z"}

**What you expected to happen**:
I expected all pods to start

**How to reproduce it (as minimally and precisely as possible)**:
 I followed manual process: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#manual-deployment
On an existing OpenShift 4.3 cluster, so skipped that step. I created the secrets for hmac and oauth.
Then i cloned the repo (not listed in getting_started_deploy.md), and did
kubectl apply -f config/prow/cluster/starter.yaml

I see 2 problems. Missing address on ingress, and error starting horologium:

oc get deployments
NAME READY UP-TO-DATE AVAILABLE AGE
deck 2/2 2 2 21h
hook 2/2 2 2 21h
horologium 0/1 1 0 21h
plank 1/1 1 1 21h
sinker 1/1 1 1 21h
statusreconciler 1/1 1 1 21h
tide 1/1 1 1 21h

oc get pods
NAME READY STATUS RESTARTS AGE
deck-7b6f9f4bc9-4869q 1/1 Running 0 21h
deck-7b6f9f4bc9-tspkk 1/1 Running 0 21h
hook-55547d47f-dcqlk 1/1 Running 0 21h
hook-55547d47f-jpqlp 1/1 Running 0 21h
horologium-bb84b755-khqdn 0/1 CrashLoopBackOff 251 21h
plank-6976c7c6d4-sml5j 1/1 Running 0 21h
sinker-6cd9556c66-c6jvv 1/1 Running 0 21h
statusreconciler-69dccc5d47-xxc2s 1/1 Running 0 21h
tide-75789f48cc-jt5c4 1/1 Running 0 21h

[root@again-inf ~]# oc logs horologium-bb84b755-khqdn
{"component":"horologium","error":"a dry-run was requested but required flag -deck-url was unset","file":"prow/cmd/horologium/main.go:77","func":"main.main","level":"fatal","msg":"Invalid options","time":"2020-04-29T11:48:52Z"}

kubectl get ingress ing
NAME HOSTS ADDRESS PORTS AGE
ing * 80 21h

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
I'm a first time Prow user

**Comment by alvaroaleman** [comment]
Regarding dry-run, you just need to remove the flag like here: https://github.com/kubernetes/test-infra/pull/17470

Regarding the ingress, it depends on your Ingress controller implementation if an empty host will work but it seems on Openshift it does not. As I read its docs[1] you need to find out the basedomain set up in the cluster and then use a subdomain as the host in the ingress, something like:

```
DOMAIN="prow.$(kubectl get ingress.config.openshift.io cluster -o jsonpath='{.spec.domain}')"
kubectl get ingress ing -o json|jq ".spec.rules[0].host = \"$DOMAIN\""|kubectl apply -f -
```

[1] https://docs.openshift.com/container-platform/4.3/networking/ingress-operator.html

**Comment by tseelbach** [comment]
@alvaroaleman Thank you! 
Horologium starts, and the commands worked to set the host.  Console is up and the echo tests pass!

Note the readme says to look for IP, but I have host as you said, which is fine: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#get-ingress-ip-address
