### ISSUE TITLE
mungegithub: proposal: PRs from approvers automatically self-approve their packages

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#1751]
A PR from someone with approve rights on an affected package probably shouldn't need a second approval for those packages. Can the bot treat the PR as implicitly approved by the author for their packages?

cc @justinsb @brendandburns

**Comment by ixdy** [comment]
I think this is already done. @grodrigues3 @apelisse to confirm.

**Comment by grodrigues3** [comment]
yup done already.  not sure if it's deployed with this currently, but the code's written

**Comment by grodrigues3** [comment]
https://github.com/kubernetes/test-infra/pull/1730
