### ISSUE TITLE
Add data from PRs to 24 hr test history

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1754]
Right now we only aggregate results from the ci-* jobs. Would love to include information from the pull-* jobs as well.

* The dashboard is [here](http://storage.googleapis.com/kubernetes-test-history/static/index.html)
* Code that generates these pages is [here](https://github.com/kubernetes/test-infra/tree/master/jenkins/test_history).
* The CI configuration for this job is [here](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci-repo.yaml#L59) and [here](https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L238)

Other improvements are also welcome!

**Comment by fejta** [comment]
I suspect this work is

a) Adding gs://kubernetes-jenkins/pr-logs/pull to [buckets.yaml](https://github.com/kubernetes/test-infra/blob/master/buckets.yaml)
b) speeding up the whole process so it doesn't take a million years to complete
c) most likely by
  - actually adding gs://kubernetes-jenkins/pr-logs/directory to buckets.yaml
  - making the [GCSClient in gen_json.py](https://github.com/kubernetes/test-infra/blob/master/jenkins/test_history/gen_json.py#L49) aware of the pattern where instead of `gs://BASE/JOB` containing a list of `BUILD` folders, you instead have a bunch of `BUILD.txt` files ([example](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gke/10108.txt)) that contain the name of the `gs://OTHER_BASE/JOB/BUILD/` path that contains the actual data files we need to parse.

**Comment by grodrigues3** [comment]
@crimsonfaith91 this could be a good project as well

**Comment by crimsonfaith91** [comment]
I will start working on this issue. :)

**Comment by spxtr** [comment]
Note that it looks funky since we just got rid of merge-blocking jobs.

**Comment by fejta** [comment]
@crimsonfaith91 thanks! Sent you an invite to collaborate on this repo. Once you receive it you can `/assign` this issue to yourself.

**Comment by crimsonfaith91** [comment]
@fejta noted! i will work on this issue first. thanks! :)

**Comment by crimsonfaith91** [comment]
@fejta Do you mean changing [this](https://github.com/kubernetes/test-infra/blob/master/jenkins/test_history/gen_json.py#L151) when you mentioned `BUILD.txt`?

I apologize if it is not a good question. I am new to the Jenkins repo (and Python). Thanks! :)

**Comment by fejta** [comment]
Intent here is to note the differences:
* CI results use paths like `logs/JOB_NAME/BUILD_NUMBER` and in that folder is a bunch of files like `started.json`, `finished.json`, etc.
* PR results use paths like `pr-logs/directory/JOB_NAME` path has a `pr-logs/directory/JOB_NAME/BUILD_NUMBER.txt` file, the contents of which are a `gs://kubernetes-jenkins/pr-logs/PR_NUMBER/JOB_NAME/BUILD_NUMBER` that store a link to the actual `started.json` etc files

So we will need to make the `gen_json.py` file aware of this directory pattern -- read the poor man's symlink at `BUILD_NUMBER.txt` and read the actual path to get the json/junit files.

**Comment by crimsonfaith91** [comment]
thank you very much for the very detailed explanation! many thanks!

**Comment by crimsonfaith91** [comment]
@fejta I will get back to this when I resolve the inactive reviewer issue. Sorry for the delay!

**Comment by fejta** [comment]
Testgrid and triage sites have deprecated the 24 hr test history
