### ISSUE TITLE
Update cloud.google.com/go

### ISSUE THREAD

**Issue by mborsz** [kubernetes/test-infra#17546]
**What should be cleaned up or changed**:
Currently, this repo uses cloud.google.com/go library in version v0.44.3:
To implement some performance improvement in deck I need to update cloud.google.com/go library to version at least v0.49.0 (see https://github.com/kubernetes/test-infra/issues/17505#issuecomment-625190906 for context)

https://github.com/kubernetes/test-infra/blob/1e9aeb3e97e9d3dae74c3bb2d610e34dc0117a3d/go.mod#L10-L21

I tried few different approaches:
* I followed instruction on https://github.com/kubernetes/test-infra/blob/master/docs/dep.md and run `bazel run //:update-minor -- cloud.google.com/go`. It does change require section in go.mod file but it seems to have no effect as we use replace directive above.
* I also tried manually changing version of cloud.google.com/go in replace section in go.mod and then running hack/update-deps.sh (result in https://github.com/kubernetes/test-infra/pull/17545), but it fails with 
```
➜  test-infra git:(deps) bazel test //prow/spyglass/...
INFO: Build option --features has changed, discarding analysis cache.
ERROR: /home/maciejborsz/.cache/bazel/_bazel_maciejborsz/7f9c5525aa8b01aca8c5c6f1b6563c79/external/com_github_googlecloudplatform_testgrid/util/gcs/BUILD.bazel:3:1: no such package '@com_google_cloud_go//storage': BUILD file not found in directory 'storage' of external repository @com_google_cloud_go. Add a BUILD file to a directory to mark it as a package. and referenced by '@com_github_googlecloudplatform_testgrid//util/gcs:go_default_library'
ERROR: Analysis of target '//prow/spyglass:go_default_test' failed; build aborted: no such package '@com_google_cloud_go//storage': BUILD file not found in directory 'storage' of external repository @com_google_cloud_go. Add a BUILD file to a directory to mark it as a package.
INFO: Elapsed time: 3.613s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (232 packages loaded, 8203 targets configured)
FAILED: Build did NOT complete successfully (232 packages loaded, 8203 targets configured)
``` 

It looks like after updating cloud.google.com/go, hack/update-build migrates:
* //com_google_cloud_go//storage to //com_google_cloud_go_storage
* //com_google_cloud_go//pubsub to //com_google_cloud_go_pubsub
and some dependencies are still trying to use com_google_cloud_go directly.

This is a request for help: Is there any way in the current test-infra setup to update the version of cloud.google.com/go?
 
**Provide any links for context**:

**Comment by mborsz** [comment]
/assign @fejta 

@fejta, I see that you wrote https://github.com/kubernetes/test-infra/blob/master/docs/dep.md. Do you have any suggestion on how to proceed with this?

**Comment by spiffxp** [comment]
/close
Done in https://github.com/kubernetes/test-infra/pull/18000, cloud.google.com/go is now at v0.60.0
