### ISSUE TITLE
mkpj should not fail with anonymous github client

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#17550]
**What happened**:

While running:
`config/mkpj.sh --job=post-kubernetes-push-image-go-runner`

The following:
```
time="2020-05-07T15:26:28Z" level=warning msg="empty -github-token-path, will use anonymous github client"
Base ref (e.g. master): master
time="2020-05-07T15:29:11Z" level=info msg="GetRef(kubernetes, kubernetes, heads/master)" client=github
time="2020-05-07T15:29:12Z" level=debug msg="GetRef(kubernetes, kubernetes, heads/master) finished" client=github duration=215.385334ms
time="2020-05-07T15:29:12Z" level=fatal msg="failed to get base sha: status code 401 not one of [200], body: {\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}"
```

**What you expected to happen**:

I expect to be able to use mkpj on public repos without granting it any authentication.

**How to reproduce it (as minimally and precisely as possible)**:

Use mkpj without `--github-token-path`

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/area prow

**Comment by BenTheElder** [comment]
you can mitigate by temporarily writing a token to disk and then passing `--github-token-path`

for this script you probably want to put it in the repo and then do `$(pwd)/token`.

you should delete this though, do not leave an access token to your github sitting around on your local disk.

**Comment by alvaroaleman** [comment]
This one is really annoying.

**Comment by BenTheElder** [comment]
thank you!
