### ISSUE TITLE
Do not remove the LGTM label for trusted authors

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#1755]
.2) revert the anti-lgtm bot for a set of "trusted" authors (likely OWNERS)

And, regardless of which of the two we choose, we will implement a "btw, this was merged with changes" note.  We'll try to get the diff, but I'm not positive how easy it is to get the diff from github if the commit has changed.

Per https://groups.google.com/d/msg/kubernetes-dev/SxcnadJQcr0/0GDnkC90BwAJ

**Comment by spxtr** [comment]
> We'll try to get the diff, but I'm not positive how easy it is to get the diff from github if the commit has changed.

This might be tricky. The problem is that when people force-push or do a rebase, the original git commit drops out and gets garbage collected at some unspecified point. There might be some way around this or some guarantee on how long the old commit sticks around, but there might not.

**Comment by spiffxp** [comment]
at least in the web ui, force-pushes show up as new events, could we maybe use the API to just grab commits since the last LGTM label?  if it's a whole new patchset vs incremental diff, so be it?

**Comment by mtaufen** [comment]
@pkaminski I'm sure you're busy but hoping you can provide some insight :-). How does Reviewable produce a diff across PR revisions (including force-pushes)? Could the same technique be applicable here?

**Comment by pkaminski** [comment]
To summarize a bunch of fiddly code, Reviewable:

1. Remembers the commit SHAs for every revision captured by the review.
1. Creates a git ref (like a branch, but in a separate namespace) for every commit that was captured as a revision, ensuring that it doesn't get garbage collected by GitHub.
1. Uses the commit SHAs to fetch the corresponding git trees, figure out the relevant file SHAs, fetch the raw file contents, and run its own diff between them.

I'm sure you could reproduce this technique -- and I'm happy to provide more details if desired -- but it might be too much work depending on what you're trying to achieve.  BTW, I asked GitHub support previously and they declined to provide any guarantees, or even estimates, on how long it takes for a commit to get GC'd.

**Comment by fejta** [comment]
We need to find an owner, update and/or close

**Comment by spiffxp** [comment]
/area mungegithub
lgtm-after-commit munger

**Comment by kargakis** [comment]
Soon, something that will be handled by prow: https://github.com/kubernetes/test-infra/pull/3821
/area prow

**Comment by spiffxp** [comment]
/remove-lifecycle stale
Lots of wishes for something like this when I raised the idea of revoking direct write access to k/k https://github.com/kubernetes/kubernetes/issues/57667

**Comment by fejta** [comment]
How about if you own all the files you're modifying we don't remove the LGTM label?

**Comment by fejta** [comment]
/assign @hklai 
/remove-lifecycle rotten

Should we consider this fixed?

**Comment by hklai** [comment]
I plan to refine the trusted user definition to further reduce the scope from all org members. Will send another PR soon-ish.

**Comment by hklai** [comment]
https://github.com/kubernetes/test-infra/pull/10019 is merged and is deployed to Istio.

I think we can consider this as fixed now.
