### ISSUE TITLE
Bot feedback on `/test all` confusing when `/test all` does not trigger any jobs

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/test-infra#17580]
**What happened**:

We have a repo where all jobs are conditionally triggered:

```
always_run: false
run_if_changed: <regex>
```

Recently we had a PR which made a change such that no job matched the criteria, so no job was run by default. As documented in https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#standard-triggering-and-execution-behavior-for-jobs, `/test all` means "trigger all automatically triggered jobs", which for such PR means _trigger no jobs_ (no jobs are triggered automatically). The bot responded with "The specified target(s) for /test were not found." and "Use `/test all` to run all jobs."

**What you expected to happen**:
I expect the bot to at least hint that `/test all` does not really mean ALL jobs, but only those that would automatically be triggered, and also not provide the misleading "the specified target was not found" message 

**How to reproduce it (as minimally and precisely as possible)**:
`/test all` on a org/repo/branch which only has conditionally triggered jobs, but the PR does not trigger any of them,

**Please provide links to example occurrences, if any**:
https://github.com/openshift/installer/pull/3542#issuecomment-624550909

**Anything else we need to know?**:

**Comment by adshmh** [comment]
I will take a look and submit a PR to fix it.
