### ISSUE TITLE
Prow issue: how to get rid of `do-not-merge/invalid-commit-message`?

### ISSUE THREAD

**Issue by humblec** [kubernetes/test-infra#17588]
I am in process of migrating a repo and it fails on couple of commits as wrote here https://github.com/kubernetes-sigs/gluster-block-external-provisioner/pull/1#issuecomment-627873795. 

```
Keywords which can automatically close issues and at(@) mentions are not allowed in commit messages.

The list of commits with invalid commit messages:

    6f2a5c9 Add event list permission to ClusterRole
    7b42070 Make env also used while naming provisioner.

Instructions for interacting with me using PR comments are available here. If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository. I understand the commands that are listed here.
```

The questions are:
1) Its not clear what commit message string is causing this issue. Can you please let me know ? links are not helpful.
2) How to get rid of or make the flag silent ? any tricks for that ?

**Comment by petr-muller** [comment]
About 1) Both linked commits contain the `Fixes:` string, which is a "Keyword that can automatically close issues" (https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword -- part of the page linked by `Keywords`)

**Comment by humblec** [comment]
> About 1) Both linked commits contain the `Fixes:` string, which is a "Keyword that can automatically close issues" (https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword -- part of the page linked by `Keywords`)

Thanks @petr-muller ..  I see, I was looking at the commit title and not really into the message part. 
I will wait for second query to be addressed and proceed accordingly.  :) :+1:

**Comment by BenTheElder** [comment]
> How to get rid of or make the flag silent ? any tricks for that ?

We've banned it as a policy matter in the kubernetes orgs, it's turned on globally in our prow instance IIRC.

This has poor interaction with github. You can phrase it differently, or if you want your PR to close the issue you can put "fixes: #..." _in the PR body_ and NOT in the commit

**Comment by BenTheElder** [comment]
A PR to include a link to https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword or a doc outlining this would probably be most welcome
/area prow

**Comment by humblec** [comment]
> > How to get rid of or make the flag silent ? any tricks for that ?
> 
> We've banned it as a policy matter in the kubernetes orgs, it's turned on globally in our prow instance IIRC.
> 
> This has poor interaction with github. You can phrase it differently, or if you want your PR to close the issue you can put "fixes: #..." _in the PR body_ and NOT in the commit

@BenTheElder sure, but the concern here is, its on the commit which is part of the history. That said, the migration of the repo brought those intermediate commit in that form. I am wondering what should get priority here ie `unchanged history` or `the commit rule` :)..

**Comment by BenTheElder** [comment]
A repo admin can bypass this by removing the label and forcibly merge, which is what I'd expect during a repo migration for preserving history.

If the history is just from your own development, please update the commit message.

**Comment by humblec** [comment]
> A repo admin can bypass this by removing the label and forcibly merge, which is what I'd expect during a repo migration for preserving history.

Cool. Thanks for confirming @BenTheElder !
> 
> If the history is just from your own development, please update the commit message.

Unfortunately no, so let me go ahead with the first option :+1:

**Comment by nikhita** [comment]
@humblec :wave: can this issue be closed?

**Comment by humblec** [comment]
> @humblec wave can this issue be closed?

Yeah :hand: closing .. thanks all!
