### ISSUE TITLE
Include test-cmd output in testgrid

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/test-infra#1759]
Forked from https://github.com/kubernetes/kubernetes/issues/40521#issuecomment-275498724

Based on @ixdy's comment there, we need to produce machine parseable junit output in test-cmd to make this feasible.

cc @k8s-sig-testing-misc @fejta

**Comment by fejta** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/45196
