### ISSUE TITLE
prow: hook/trigger: failed to trigger a build and then gave up on everything

### ISSUE THREAD

**Issue by colemickens** [kubernetes/test-infra#1761]
1. I forced push to a PR.
2. Something (`crier`?) removed the build statuses for the old commit sha.
3. Wait
4. Observe that no new status has been reported, and that no builds are showing in `deck`.

It seems that there was a transient failure in kicking off one of the jobs and I'm guessing it just gave up:

Here's the logs:

`{"head":"98ace1c981bf5b7a6938d5c25b1ed49dc19df6ef","level":"info","msg":"Push event.","org":"colemickens","ref":"refs/heads/cmpr-test-kubernetes","repo":"acs-engine","time":"2017-01-31T00:43:59Z"}`
                                                                                                                                                   `{"author":"colemickens","level":"info","msg":"Pull request synchronize.","org":"colemickens","pr":29,"repo":"acs-engine","time":"2017-01-31T00:43:59Z","url":"https://github.com/colemickens/acs-engine/pull/29"}`

`{"author":"colemickens","level":"info","msg":"Starting all jobs for updated PR.","org":"colemickens","plugin":"trigger","pr":29,"repo":"acs-engine","time":"2017-01-31T00:44:00Z","url":"https://github.com/colemickens/acs-engine/pull/29"}`

`{"author":"colemickens","error":"response has status \"400 Bad Request\" and body \"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"the object provided is unrecognized (must be of type Job): couldn't get version/kind; json parse error: unexpected end of JSON input (\\u003cempty\\u003e)\",\"reason\":\"BadRequest\",\"code\":400}\n\"","level":"error","msg":"Error handling PullRequestEvent.","org":"colemickens","plugin":"trigger","pr":29,"repo":"acs-engine","time":"2017-01-31T00:45:59Z","url":"https://github.com/colemickens/acs-engine/pull/29"}`

**Comment by spxtr** [comment]
That's curious. What version of kubernetes?

**Comment by colemickens** [comment]
`v1.5.1`
