### ISSUE TITLE
pull-test-infra-gubernator is failing

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#17637]
**What happened**:
`pull-test-infra-gubernator` is failing on all runs: https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-test-infra-gubernator
https://testgrid.k8s.io/presubmits-test-infra#gubernator
```
Collecting soupsieve>1.2 (from beautifulsoup4->webtest->-r test_requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/3e/db/5ba900920642414333bdc3cb397075381d63eafc7e75c2373bbc560a9fa1/soupsieve-2.0.1.tar.gz (95kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-27P58i/soupsieve/setup.py", line 40, in <module>
        VER, DEVSTATUS = get_version()
      File "/tmp/pip-build-27P58i/soupsieve/setup.py", line 11, in get_version
        import importlib.util
    ImportError: No module named util
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-27P58i/soupsieve/
```
**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/test-infra/17600/pull-test-infra-gubernator/1262828448364105734

Assigning owners of PR dashboard / gubernator.
/assign @fejta @michelle192837 @chaodaiG @stevekuznetsov 
/area gubernator

**Comment by chaodaiG** [comment]
Couldn't repro this error locally by
```
pip install -r test_requirement.txt
```

The difference is that my `pip` version is 20.1.1, and the one used in prow is 8.1.1. So created a test PR with `pip install --upgrade pip` and it passed.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/test-infra/17653/pull-test-infra-gubernator/1263119883646799872 
https://github.com/kubernetes/test-infra/pull/17653

**Comment by chaodaiG** [comment]
The image used for this job `gcr.io/k8s-testimages/gubernator:0.4` was built in 2017, I think it could be fixed by rebuilt this image

**Comment by chaodaiG** [comment]
Created #17654
