### ISSUE TITLE
area/* and sig/* labels are not removed from PRs when they are not needed

### ISSUE THREAD

**Issue by chizhg** [kubernetes/test-infra#17645]
**What happened**:
When I worked on a PR in k8s test-infra, I made some mistake during rebase and pushed a lot of irrelevant changes, which exploded the labels on the PR. But after I corrected it and did a force push, the labels were not removed, though my PR did not contain those changes any more.

**What you expected to happen**:
The labels should be removed after the PR does not contain the relevant files changes.

**How to reproduce it (as minimally and precisely as possible)**:
Make some change on a PR that gets Prow adding some labels based on the `OWNERS` file, and then revert the change.

**Please provide links to example occurrences, if any**:
The example PR is https://github.com/kubernetes/test-infra/pull/17568.

/area prow

**Comment by BenTheElder** [comment]
it would be feasible enough to detect that a push removed the need to add these, but these labels can also be added manually or via commands, so it would be somewhat complex to get that correct (so as not to remove manually added labels) or we'd have to decide that we're OK with clobbering manually added labels.

cc @cblecker for behavior thoughts

**Comment by cblecker** [comment]
Yeah, unless we can figure out some way of saying "these ones are manual, and these ones are from owners files" then I think it might do more harm than good to clobber manually added labels.

**Comment by BenTheElder** [comment]
it should be possible to detect that I think, but you'd have to read in the PR events and compute what happened, I sort of doubt any of the prow maintainers are inclined to build this more complex version.

**Comment by cblecker** [comment]
That’s my feeling too. It’s annoying when a rebases goes sideways and you manually have to remove the labels, but probably not worth the effort to work around this IMO
