### ISSUE TITLE
Logs UX: Purple on grey might not be readable for everyone

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#17651]
![image](https://user-images.githubusercontent.com/1829149/82422192-feaec700-9a36-11ea-9603-795bbeab13f1.png)

**Comment by michelle192837** [comment]
/area prow/spyglass

That's pretty bad, yeah. :( Do you have a link to those logs as well?

**Comment by BenTheElder** [comment]
prow doesn't set purple on it's own IIRC, are your logs emitting terminal color codes?

**Comment by Ark-kun** [comment]
> prow doesn't set purple on it's own IIRC, are your logs emitting terminal color codes?

My bad. It's now pretty obvious Prow has nothing to do with that.
