### ISSUE TITLE
Approve label isn't cleaned when new changes are pushed to the PR.

### ISSUE THREAD

**Issue by oshoval** [kubernetes/test-infra#17698]
**What happened**:
A maintainer approved the PR.
I pushed new code, and the approve label wasnt cleaned.

**What you expected to happen**:
The approve label, as lgtm label should be cleaned upon pushing of new code.

**How to reproduce it (as minimally and precisely as possible)**:
Approve a PR, push new code, see the approve reminds intact.

**Please provide links to example occurrences, if any**:
https://github.com/kubevirt/kubevirt/pull/3392

**Anything else we need to know?**:
Nope, thanks

**Comment by alvaroaleman** [comment]
This is deliberate. `approve` signals that the codeowner is fine with the idea and approach of the change. `lgtm`, which gets cleaned up, signals that the implementation looks good.

**Comment by oshoval** [comment]
Thanks Alvaro,
Wondering if this behaviour is the desired in all projects?
For example what happens if there is approve, but later there is a shift in the direction that the PR implemented, which isn't liked by the maintainer,
so he must go manually and unapproved it.

Maybe its should be configurable ?

**Comment by alvaroaleman** [comment]
I am not a huge fan of the idea of making it configurable, we have too many knobs already. If you don't trust the person creating the PR to stick with the approach, don't `approve` it until its completely done.

**Comment by oshoval** [comment]
Ok, thanks Alvaro,
Closing.
