### ISSUE TITLE
prow when the account number is pure numbers, it will not work

### ISSUE THREAD

**Issue by 928234269** [kubernetes/test-infra#17706]
**What happened**:
my account number is pure numbers, when I use the /approve command, he does not take effect
**What you expected to happen**:
/approve takes effect
**How to reproduce it (as minimally and precisely as possible)**:
/approvers   
```
/approvers 
- 928234269
```
**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by petr-muller** [comment]
I think you'll need to make it a string in the OWNERS file YAML (because it is a string, just happening to consist of digits).

Ideally this should also be detected by the validate-owners plugin.,,

**Comment by 928234269** [comment]
> I think you'll need to make it a string in the OWNERS file YAML (because it is a string, just happening to consist of digits).
> 
> Ideally this should also be detected by the validate-owners plugin.,,
Thank you very much for your reply, already working. 
```
/approvers 
- "928234269"
```
