### ISSUE TITLE
Prow issue: "Skipping CI for Draft Pull Request" doesn't trigger tests once marked as ready

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#17713]
After a recent prow update, WIP PRs now get

```
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with /test all
```

as a comment and do not trigger tests

However, once the PR is marked as "Ready", tests are not automatically triggered. I would expected marking the PR as ready to trigger the tests rather than requiring a manual /test

**Comment by alvaroaleman** [comment]
@howardjohn this was only very recently fixed in https://github.com/kubernetes/test-infra/pull/17663 , do you have that change already?

**Comment by howardjohn** [comment]
verified this is fixed, thanks
