### ISSUE TITLE
node e2e tests - projects out of quota

### ISSUE THREAD

**Issue by karan** [kubernetes/test-infra#17714]
Many sig-node tests are failing consistently due to CPU exhaustion:

```
I0526 15:56:55.801] unable to create gce instance with running docker daemon for image ubuntu-gke-1804-1-16-v20200330.  could not create instance tmp-node-e2e-076c4ac7-ubuntu-gke-1804-1-16-v20200330: [&{Code:QUOTA_EXCEEDED Location: Message:Quota 'CPUS' exceeded.  Limit: 100.0 in region us-west1. ForceSendFields:[] NullFields:[]}]
```

They are tracked in https://docs.google.com/spreadsheets/d/1mEU8B2_PmMwwgp-_xnyp7QYMBwcLoA9NNlHwDyMvO0Y/edit#gid=0.

For one of the projects, looks like it's at 100 instances already:

```
$ gcloud compute instances list --project cri-containerd-node-e2e | wc -l
100
```

A good starting point will be to:

- get a list of all these projects
- inspect all tests using these projects and how many CPUs they need
- come up with a plan for getting out of this problem (we should definitely increase quota and/or shard across more projects and/or reduce resource usage by tests)

**Comment by MHBauer** [comment]
Also addresses exhaustion.

**Comment by karan** [comment]
Looking at the following:

Job | Link | Project
--- | --- | ---
containerd-node-e2e-1.2 | https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.2 | cri-containerd-node-e2e
containerd-node-e2e-1.3 | https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.3 | cri-containerd-node-e2e
containerd-node-features | https://testgrid.k8s.io/sig-node-containerd#containerd-node-features | cri-containerd-node-e2e
containerd-node-e2e-features-1.2 | https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-features-1.2 | cri-containerd-node-e2e
containerd-node-e2e-features-1.3 | https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-features-1.3 | cri-containerd-node-e2e
image-validation-node-e2e | https://testgrid.k8s.io/sig-node-containerd#image-validation-node-e2e | cri-containerd-node-e2e
image-validation-node-features | https://testgrid.k8s.io/sig-node-containerd#image-validation-node-features | cri-containerd-node-e2e
node-e2e | https://testgrid.k8s.io/sig-node-containerd#node-e2e | cri-containerd-node-e2e
node-e2e-benchmark | https://testgrid.k8s.io/sig-node-containerd#node-e2e-benchmark | cri-containerd-node-e2e
node-e2e-features | https://testgrid.k8s.io/sig-node-containerd#node-e2e-features | cri-containerd-node-e2e
node-e2e-flaky | https://testgrid.k8s.io/sig-node-containerd#node-e2e-flaky | cri-containerd-node-e2e
node-e2e-serial | https://testgrid.k8s.io/sig-node-containerd#node-e2e-serial | cri-containerd-node-e2e

All of them use the same project and the same region (us-west1-b). All of these run with n1-standard-1 and it seems like in the last couple of hours, it's been constantly at 100 CPU usage.

An easy fix would be to spread the tests over other regions as well (us-central1 has another 100 CPU quota.)

**Comment by spiffxp** [comment]
I would confirm whether those instances are from live running tests, or whether they're detritus left over from tests that couldn't ssh to the nodes they'd created and forgot to cleanup.  I LGTM'ed the PR to try a new region, if the reason is the latter, you may hit quota again. 

See https://github.com/kubernetes/kubernetes/issues/89892#issuecomment-613207624 where we tested this out by clearing out VM's for a project that appeared to have network issues

**Comment by MHBauer** [comment]
That's a great comment to look at, thanks!

**Comment by karan** [comment]
Seems like the quota issue is resolved and I'm seeing 4-6 VMs in the project right now. So doesn't seem like VMs are being orphaned.

The new issue issue is around docker not running (for which I'll cut a new issue).

**Comment by MHBauer** [comment]
I'm not sure this is quite finished, for https://testgrid.k8s.io/sig-node-containerd#pull-node-e2e
I see inuse addreses quota exceeded.

``
 I0604 19:06:58.636] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0604 19:06:58.636] >                              START TEST                                >
I0604 19:06:58.636] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0604 19:06:58.637] Start Test Suite on Host 
I0604 19:06:58.637] 
I0604 19:06:58.637] Failure Finished Test Suite on Host 
I0604 19:06:58.637] unable to create gce instance with running docker daemon for image ubuntu-gke-1804-1-15-v20200602.  could not create instance tmp-node-e2e-f2333f3a-ubuntu-gke-1804-1-15-v20200602: [&{Code:QUOTA_EXCEEDED Location: Message:Quota 'IN_USE_ADDRESSES' exceeded.  Limit: 69.0 in region us-west1. ForceSendFields:[] NullFields:[]}]
I0604 19:06:58.638] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I0604 19:06:58.638] <                              FINISH TEST                               <
I0604 19:06:58.638] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I0604 19:06:58.638] 
W0604 19:06:58.739] E0604 19:06:58.635696    5017 run_remote.go:779] Error deleting instance "tmp-node-e2e-f2333f3a-ubuntu-gke-1804-1-15-v20200602": googleapi: Error 404: The resource 'projects/k8s-c8d-pr-node-e2e/zones/us-west1-b/instances/tmp-node-e2e-f2333f3a-ubuntu-gke-1804-1-15-v20200602' was not found, notFound
W0604 19:06:58.836] E0604 19:06:58.836212    5017 run_remote.go:779] Error deleting instance "tmp-node-e2e-f2333f3a-cos-77-12371-284-0": googleapi: Error 404: The resource 'projects/k8s-c8d-pr-node-e2e/zones/us-west1-b/instances/tmp-node-e2e-f2333f3a-cos-77-12371-284-0' was not found, notFound
I0604 19:06:58.937] 
I0604 19:06:58.937] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0604 19:06:58.937] >                              START TEST                                >
I0604 19:06:58.937] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I0604 19:06:58.938] Start Test Suite on Host 
I0604 19:06:58.938] 
I0604 19:06:58.938] Failure Finished Test Suite on Host 
I0604 19:06:58.938] unable to create gce instance with running docker daemon for image cos-77-12371-284-0.  could not create instance tmp-node-e2e-f2333f3a-cos-77-12371-284-0: [&{Code:QUOTA_EXCEEDED Location: Message:Quota 'IN_USE_ADDRESSES' exceeded.  Limit: 69.0 in region us-west1. ForceSendFields:[] NullFields:[]}]
I0604 19:06:58.938] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I0604 19:06:58.939] <                              FINISH TEST                               <
I0604 19:06:58.939] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
```

**Comment by karan** [comment]
`--gcp-project=k8s-c8d-pr-node-e2e`

We should cut a new issue IMO and check all projects we use and their IP quota.

If we allow up to 100 VMs in a project, we should have at least that many IPs in quota as well.

**Comment by MHBauer** [comment]
I do not have any idea of how to do this project checking.

**Comment by dims** [comment]
We should get guidance from @spiffxp and @BenTheElder

**Comment by BenTheElder** [comment]
Aaron and I don't have much to do with this project currently, when SIGs ask for GCE quota we ask them to use the boskos pools to rent a project for one test run at a time, which makes cleanup very straightforward (destroy all project contents) and capacity planning easy (monitor how full / empty the pools are).

Using a single project is a bit of an anti-pattern.

**Comment by MHBauer** [comment]
So we need to figure out why it's tied to a specific gcp project, and figure out a way to nullify that requirement. Does that sound right?

**Comment by MHBauer** [comment]
And move to using a boskos pool for (any?/all?) tests that currently have a specific project/region? Cause yea, it would make sense to me that we don't care where these things run, just that they do.

**Comment by MHBauer** [comment]
Okay, thanks for the hint:
I see https://github.com/kubernetes/test-infra/issues/7769 and I will use https://github.com/kubernetes/test-infra/pull/8165 as reference and try to follow up.
