### ISSUE TITLE
maintenance-pull-janitor and maintenance-pull-scale-janitor still using bootstrap

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#17719]
**What should be cleaned up or changed**:
I'm attempting to update the various janitors that are using the `gcp_janitor.py` script inside the `boskos/` directory in preparation for removing boskos from test-infra (https://github.com/kubernetes/test-infra/issues/17614).

It looks like the `maintenance-pull-janitor` and `maintenance-pull-scale-janitor` jobs are still using bootstrap, which is apparently deprecated and no longer supported:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/maintenance-pull-janitor/1265432629549731842/
```
W0527 00:00:59.933] **************************************************************************
bootstrap.py is deprecated!
test-infra oncall does not support any job still using bootstrap.py.
Please migrate your job to podutils!
https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md
**************************************************************************
```

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/maintenance-pull-scale-janitor/1265430112350769153/
```
W0526 23:50:37.804] **************************************************************************
bootstrap.py is deprecated!
test-infra oncall does not support any job still using bootstrap.py.
Please migrate your job to podutils!
https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md
**************************************************************************
```

These should probably either be fixed or deleted.

(Also, maintenance-pull-janitor has been failing continuously for weeks: https://testgrid.k8s.io/sig-testing-maintenance#pull-janitor&width=5)

**Comment by BenTheElder** [comment]
What's the current status here?

**Comment by ixdy** [comment]
It appears that nothing has changed.
I ended up not deleting `gcp_janitor.py` from test-infra, so as to not break these jobs further, but at some point they should probably be updated to use the `gcp_janitor.py` from kubernetes-sigs/boskos instead, since that one is maintained.

**Comment by BenTheElder** [comment]
> ... but at some point they should probably be updated to use the gcp_janitor.py from kubernetes-sigs/boskos instead, since that one is maintained.

That seems important. Are you going to do this?

**Comment by ixdy** [comment]
I think first we'd need to convert these jobs to using podutils, as that would let us more easily clone a second git repository (kubernetes-sigs/boskos). I think there may have been other issues when I was investigating this in May, but I don't remember anymore.

This task is pretty far down my priority list right now, so I'm not sure when I'd get to it.

Given that these jobs have been pretty continuously failing (and seemingly nobody has noticed or complained), I'm not sure if it's even worth fixing them.

**Comment by ixdy** [comment]
Do we even need maintenance-pull-janitor anymore? shouldn't most of the PR jobs be using projects from Boskos, which are already cleaned up by the janitor?

I guess we need the pull-scale-janitor since there's still a single project that's shared for scale testing.

**Comment by BenTheElder** [comment]
There are a few PR jobs that are not using boskos still and aren't super easily moved.

People may not have visibility into "janitor failing == an issue somewhere else", so I'm not sure "no complaints" is a useful signal.

**Comment by ixdy** [comment]
I guess the first real step would be for someone to confirm that these jobs are still needed. Can you confirm we still need these jobs? Which PR jobs still need boskos, and which projects do they use? (For example, the maintenance-pull-janitor is currently failing to clean a project that no longer exists, which suggests the project lists are out of date. I don't have context on which projects would be appropriate to manage here.)

**Comment by BenTheElder** [comment]
IIRC it's supposed to auto-detect the projects itself?
We have poor visibility into this.

I was going to go ahead and port this to pod-utils as that's actually
generally pretty straightforward and I have less context on boskos changes.

>

**Comment by ixdy** [comment]
This issue depends on #20760.
