### ISSUE TITLE
Create a flaky-serial suite

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#1772]
per discussion, @saad-ali @fejta

**Comment by saad-ali** [comment]
+@jeffvance

**Comment by jeffvance** [comment]
According to [e2e doc](https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md#kinds-of-tests) [Flaky] supercedes [Serial]. I don't know if this means tests that must be run serially are run serially if the test is both `[Flaky]` and `[Serial]`. It seems reasonable to me that a test tagged as `[Serial]` should never be run in parallel ragardless of its other tags. It also seems reasonable that a test tagged `[Flaky]` should be assumed to also be serial.
