### ISSUE TITLE
`assign` plugin fails to assign to org members

### ISSUE THREAD

**Issue by hopkiw** [kubernetes/test-infra#17747]
**What happened**:
On our prow-managed repo, a PR assignment failed with the following message:
```
@YangLu1031: GitHub didn't allow me to request PR reviews from the following users: ningyang, pjh.

Note that only GoogleCloudPlatform members and repo collaborators can review this PR, and authors cannot review their own PRs.
```
pjh is a member of GoogleCloudPlatform, but ningyang is not. See https://github.com/orgs/GoogleCloudPlatform/people?query=ningyang

**What you expected to happen**:
PR should be assigned to ningyang and pjh for review

**How to reproduce it (as minimally and precisely as possible)**:
```
/cc @ningyang @pjh
```

**Please provide links to example occurrences, if any**:
https://github.com/GoogleCloudPlatform/guest-agent/pull/46

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
Not being able to assign non-org members is part of the GitHub api and not a Prow bug. Not sure why the assigment fir pjh failed. Are you sure he was an org member at the time that assignment failed?

**Comment by nikhita** [comment]
@hopkiw By any chance, did you mean to cc `ning-yang` instead of `ningyang`? I see places where the former github user has interacted on PRs in the GoogleCloudPlatform repo.

**Comment by hopkiw** [comment]
yes, i think that's true. you can see ning-yang interacts lower down in the example. but the issue is still overall that pjh didn't get assigned

**Comment by hopkiw** [comment]
/remove-lifecycle-stale

I think @fejta should own this bug, right?

**Comment by alvaroaleman** [comment]
/uncc
It wasn't clarified if there is actually a bug and my question didn't get answered, unsubscribing

**Comment by fejta** [comment]
This is not a prow bug.

This organization has configured the `default_repository_permission` for members as `none` rather than the default default of `read`.

In order for prow to assign someone, they need to be a repo collaborator and have at least read access.

https://docs.github.com/en/rest/reference/orgs#update-an-organization

**Comment by hopkiw** [comment]
thanks for explaining @fejta

**Comment by fejta** [comment]
Liam, btw in this particular issue it seems like the best way to address it is to make sure whoever you want to assign is part of a github group that is a member of the oss-test-infra repo. The [googlers](https://github.com/orgs/GoogleCloudPlatform/teams/googlers) group has read access to oss-test-infra so if the people make sure they are a member of that group, prow will be able to assign as expected.

This large group seems like the closest analogue to "allow everyone in the org to get assigned issues"
