### ISSUE TITLE
A single set of owners for /test/e2e

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1775]
We should have more granular ownership for the various tests in https://github.com/kubernetes/kubernetes/tree/master/test/e2e
Else, approvals are going to often get gated by the list of folks here: https://github.com/kubernetes/kubernetes/blob/master/test/OWNERS
Perhaps we should have directories for individual sets of tests and OWNERS files with people that maintain the feature being tested

cc @kubernetes/test-infra-maintainers @apelisse @grodrigues3

**Comment by fejta** [comment]
Expand the set of OWNERS? Feel free to add yourself and/or anyone else you feel will be appropriate!

**Comment by spxtr** [comment]
At some point we were discussing moving e2e tests into their own packages. So the volume tests would be under `test/e2e/volume` and so on. This was why we moved the framework into its own package iirc, but maybe that idea is abandoned.

Doing this would easily let us add OWNERS for each package, but it's probably not feasible in the short-term.

**Comment by fejta** [comment]
We moved most e2e tests to their own sub directory
