### ISSUE TITLE
Fall back to PR hash when merging fails? (pr-builder tests)

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/test-infra#1780]
One thing I've been seeing a lot lately is all tests failing because I need to rebase. I would like the PR-builder tests to run against the hash at the tip of my PR if the merge cannot complete automatically, so that I can still see whether they pass without having to rebase first. This is particularly annoying in frequently-edited files.

**Comment by fejta** [comment]
Great idea! What if we made it trivial to run PR tests before you create a PR and/or push your changes to github?

**Comment by mtaufen** [comment]
That could help. I'd definitely want to be able to launch the tests against a specific hash and then continue working on the branch locally. It would also be useful to have all the additional artifact collection that remote tests do, so maybe a way to easily launch remote tests against a branch from my fork? We would probably need to give everyone a quota for max concurrently-tested branches so it doesn't get too expensive.

**Comment by spiffxp** [comment]
/area prow
since prow's trigger is handling presubmits

I can see this being useful in offloading testing work to ci, but it's not going to help improve signal on PR's until they're mergeable anyway, so I don't know

**Comment by spxtr** [comment]
Related to #1597.

**Comment by fejta** [comment]
I think we should handle this by defining a way for trusted users to request arbitrary testing on prow...
/unassign @spxtr @rmmh 

Needs design
