### ISSUE TITLE
sig-node e2e failures due to docker daemon not running

### ISSUE THREAD

**Issue by karan** [kubernetes/test-infra#17815]
Some sig-node tests are failing consistently due to docker not running:

```
I0602 21:58:47.872] unable to create gce instance with running docker daemon for image cos-77-12371-274-0.  instance tmp-node-e2e-8a75d65f-cos-77-12371-274-0 not running docker daemon - Command failed: Client:
I0602 21:58:47.872]  Version:           19.03.1
I0602 21:58:47.872]  API version:       1.40
I0602 21:58:47.872]  Go version:        go1.11.2
I0602 21:58:47.872]  Git commit:        74b1e89
I0602 21:58:47.872]  Built:             Thu May 21 19:43:14 2020
I0602 21:58:47.873]  OS/Arch:           linux/amd64
I0602 21:58:47.873]  Experimental:      false
I0602 21:58:47.873] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I0602 21:58:47.873] 
```

Looking at the following tests:

Job | Link | Project
--- | --- | ---
containerd-node-e2e-1.2 | https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.2 | cri-containerd-node-e2e
containerd-node-e2e-1.3 | https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.3 | cri-containerd-node-e2e
containerd-node-e2e-features-1.3 | https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-features-1.3 | cri-containerd-node-e2e

They are tracked in https://docs.google.com/spreadsheets/d/1mEU8B2_PmMwwgp-_xnyp7QYMBwcLoA9NNlHwDyMvO0Y/edit#gid=0.

/kind cleanup
/sig node
/sig testing
/assign karan

**Comment by dims** [comment]
This is a containerd test. it should not depend on docker. right? HOWEVER :)

https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/runner/remote/run_remote.go#L668-L679

**Comment by dims** [comment]
trying something in https://github.com/kubernetes/kubernetes/pull/92204

**Comment by BenTheElder** [comment]
I don't think this is a test-infra bug. This sounds like a kubernetes bug (in the shell there)
