### ISSUE TITLE
add flexibility to OWNERS rules

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#1782]
Two separate feature requests:
1. Allow non-recursive OWNERS, e.g. we should support expanding the list of owners for the root Makefile or BUILD.bazel files without giving them OWNERS approval over the entire repo. Or maybe instead of non-recursive, allow specifying individual files?
2. Allow certain files to be ownerless, e.g. everyone should have approval to change anything under `hack/verify-flags/`.

**Comment by fejta** [comment]
Looks like we resolved most of these problems by using symlinks
