### ISSUE TITLE
gubernator reporting incorrectly 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/test-infra#1786]
Gubernator is incorrectly reporting information (https://k8s-gubernator.appspot.com/pr) user `timothysc` This is true for other folks as well.  

e.g. - it says https://github.com/kubernetes/kubernetes/pull/40735 "Needs Attention" 

When is was merged a while ago. 

/cc @jayunit100

**Comment by spxtr** [comment]
Probably dropped the webhook. @rmmh

**Comment by rmmh** [comment]
dupe of #1576
