### ISSUE TITLE
Consistent tide squash commit message when there's only one commit

### ISSUE THREAD

**Issue by Bobgy** [kubernetes/test-infra#17915]
**Current behavior**:
When tide is configured to `squash` by default.
If there are more than one commits in the PR, commits will be squashed and PR title will be used as the commit message.
However, if there's only one commit in the PR, e.g. https://github.com/kubeflow/pipelines/commit/7fbb7cae567d24e766ae851cc494b8db0f239e54 the commit will be untouched when merged.

**What would you like to be added**:
Even if there's only one commit in the PR, it should use PR title for the commit message.

**Why is this needed**:
To enforce consistent commit messages, so that they always come from PR title.

I'm proposing this because devs usually write arbitrary commit messages and rely on the auto squash feature to squash the commit as PR title. With current behavior, some commits will unexpectedly come from the commit message directly.

Also, I'm thinking about enforcing commit message using https://www.conventionalcommits.org/en/v1.0.0/ for kubeflow/pipelines repo, so that we can generate release notes with more metadata https://github.com/kubeflow/pipelines/issues/3920. This issue makes commit message somewhat unstable.

What do you think?

**Comment by Bobgy** [comment]
Hi @cjwagner, not sure if you are the right person. From similar issues, it seems you may know related context.

Would you mind taking a look? Thanks!

**Comment by cjwagner** [comment]
By default, Tide only specifies the requested merge type (merge/squash/rebase) when merging a PR and GitHub determines the commit title and body itself. This can be overridden with the `merge_commit_template` config field if you need more control over the commit text.
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md#general-configuration
https://godoc.org/k8s.io/test-infra/prow/config#Tide

**Comment by Bobgy** [comment]
Thanks @cjwagner! That answered my question perfectly.
