### ISSUE TITLE
containerd-e2e-gci broken recently

### ISSUE THREAD

**Issue by bsdnet** [kubernetes/test-infra#17929]
**What happened**:
On May 29, https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-gci started to fail when creating cluster. 

First failed log:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce/1270494318632636417/build-log.txt

Last Succeed log:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce/1270478968641818625/build-log.txt

**What you expected to happen**:
Succeed

**How to reproduce it (as minimally and precisely as possible)**:

After the last success run, it continuously failed.

**Please provide links to example occurrences, if any**:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce/1270494318632636417/build-log.txt

**Anything else we need to know?**:

Take a look, and looks the cluster master can't be reached. Wonder any test infra is changed recently.

**Comment by BenTheElder** [comment]
test-infra code doesn't control this.
looks like the bringup code in k/k is broken, I see various errors in:
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce/1272628002525548545/artifacts/bootstrap-e2e-master/

**Comment by bsdnet** [comment]
Thanks @BenTheElder 
I will take a look and see whether I can figure this out. 

BTW, how do you get the above gcsweb  link from the log?

**Comment by bsdnet** [comment]
Looks one docker image can't be loaded:
Jun 15 20:36:23.131370 bootstrap-e2e-master configure.sh[822]: Start loading kube-system docker images
Jun 15 20:36:23.131911 bootstrap-e2e-master configure.sh[822]: Try to load docker image file /home/kubernetes/kube-docker-files/kube-apiserver.tar
Jun 15 20:36:24.114453 bootstrap-e2e-master configure.sh[822]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Jun 15 20:36:29.161555 bootstrap-e2e-master configure.sh[822]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Jun 15 20:36:34.210794 bootstrap-e2e-master configure.sh[822]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Jun 15 20:36:39.260175 bootstrap-e2e-master configure.sh[822]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Jun 15 20:36:44.305765 bootstrap-e2e-master configure.sh[822]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Jun 15 20:36:44.307521 bootstrap-e2e-master configure.sh[822]: Fail to load docker image file /home/kubernetes/kube-docker-files/kube-apiserver.tar after 5 retries. Exit!!

**Comment by RobertKielty** [comment]
> Thanks @BenTheElder
> I will take a look and see whether I can figure this out.
> 
> BTW, how do you get the above gcsweb link from the log?

Hi Roy,

The gcsweblink can be found by clicking on the Artifacts link at the top of the ProwJob dashboard

Step by step for passers-by
1. Visit the tab in Test grid 
https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-gci
2. In Testgrid click on a **red cell** to view the Prow Job 
3. Click Artifacts at the top of page, then you will have access to all the things on that gcsweb link that @BenTheElder referenced

Hope this helps.

Rob

**Comment by bsdnet** [comment]
Thanks @RobertKielty  Figure it out.
Thanks @dims  to fix this. I did not get chance to root cause it yet. Thought I use 'docker load -i' and 
found both images are good :)
