### ISSUE TITLE
Allow InitContainers or similar pre-Job setup logic for ProwJobs

### ISSUE THREAD

**Issue by stone-z** [kubernetes/test-infra#17956]
**What would you like to be added**:

We would like to be able to re-use setup logic between ProwJobs using `initContainers` or a similar mechanism. 

**Why is this needed**:

Most of our test logic starts with the same setup and ends with the same tear-down. The tests themselves require different tools and use different programming languages, but they assume the same starting environment. We'd like to extract and standardize the environment creation logic for our teams so they don't have to consider it when writing tests. They could simply add an `initContainer` which handles our standard setup.

It looks like this is currently [not supported](https://github.com/kubernetes/test-infra/blob/master/prow/config/config.go#L1859) and with [understandable reason](https://github.com/kubernetes/test-infra/pull/7594#discussion_r180550536), but I was wondering if there was any inclination to move that direction or if Prow has a preferred mechanism to use instead.

**Comment by stone-z** [comment]
For those finding this issue, we wound up using [Tekton](https://tekton.dev/) to provide the setup and teardown logic we need. 

We use Prow primarily as the trigger, and the resulting ProwJob runs a Tekton pipeline.
We provide standard Tekton Tasks which our teams can re-use, and the teams can provide any additional functionality as their own Tekton Tasks.

You can find all this in our [test-infra](https://github.com/giantswarm/test-infra) repo.

**Comment by CatherineF-dev** [comment]
+1. Could we reconsider this request?
