### ISSUE TITLE
Improve cherry-pick process to better track them

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#1795]
Cherry-picks are hard to track. We don't know if they've been merged or not and where.

In order to improve this process, we want to add two new features to `prow`:
- Create a new command, maybe `/cherry-pick $release`, to automatically create a new issue (or PR) for that specific release. The goal is to have something we can track so that we don't forget it.
- Automatically write a comment describing the process above once the `cherrypick-candidate` and `cherrypick-approved` labels have been applied.

**Comment by grodrigues3** [comment]
cc @mwielgus

**Comment by mwielgus** [comment]
cc: @saad-ali

**Comment by apelisse** [comment]
cc @spxtr

**Comment by spxtr** [comment]
Sounds good to me. Both should be fairly straightforward prow commands, and I'd love to review the PRs.

The second will be easiest to start with.

**Comment by saad-ali** [comment]
This would make cherry picks even easier! And if there is a conflict `/cherry-pick $release` should post a comment on the original PR saying the author will have to manually create a cherry pick (using `hack/cherry...`) because of conflict.

**Comment by zmerlynn** [comment]
How is it broken? http://cherrypick.k8s.io is easy enough to use.

**Comment by fejta** [comment]
Does anyone know about this site? I sure didn't! Maybe update the comment to link to it?

**Comment by kargakis** [comment]
There is an external prow plugin that can be used to automate cherrypicks between `master` and release branches today: https://github.com/kubernetes/test-infra/tree/master/experiment/cherrypicker

**Comment by stevekuznetsov** [comment]
Should be much much easier with the cherry-picker robot

**Comment by spiffxp** [comment]
I think the open question is what labels if any should be used in conjunction with the cherrypicker bot to make a release branch manager's life easier

**Comment by spiffxp** [comment]
Other cherry pick improvement links:
- https://github.com/kubernetes/test-infra/issues/7332 - members should be able to add cherrypick-candidate label to PR's (I think the cherrypick bot obviates this?)
- https://github.com/kubernetes/test-infra/pull/7345 - move cherrypicker experiment to prow external plugin
- https://github.com/kubernetes/test-infra/pull/7393 - deploy cherrypicker external plugin as part of prow
- https://github.com/kubernetes/community/issues/994 - cherry picking to multiple release branches
- https://github.com/kubernetes/test-infra/issues/6908 - add milestones to cherrypicked PRs
- https://github.com/kubernetes/community/issues/1894 - docs are confusing...
- https://github.com/kubernetes/community/pull/1980 - ...so trying to clarify them
- https://groups.google.com/forum/#!topic/kubernetes-wg-contribex/XxYn02YQcV0 - @liggitt proposing changes to the cherrypick process to make it easier to track what has and hasn't been cherrypicked to which branches

**Comment by spiffxp** [comment]
More cherry pick improvement ideas:
- https://github.com/kubernetes/test-infra/issues/1828 - auto-approve cherrypick PR's if they're based off of approved PR's to master _(ed: I'm not sure I like this idea, but I'm linking it)_
- https://github.com/kubernetes/test-infra/pull/7653 - during v1.11 we disabled the cherrypick-auto-approve munger because it was confusing branch managers
- https://github.com/kubernetes/test-infra/issues/8691 - allow multiple branches from one `/cherrypick` command, or multiple `/cherrypick` commands in one comment

**Comment by spiffxp** [comment]
/lifecycle frozen
I'm freezing this as "yes we know cherry picking needs help"

**Comment by nikhita** [comment]
Related: https://github.com/kubernetes/test-infra/issues/9582.

Removing the help-wanted label because we still need consensus on how to proceed with overhauling cherrypicking.
/remove-help

/sig contributor-experience

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
I'm taking no action on this in ~2 years as a sign that it's no longer that important
