### ISSUE TITLE
kubetest command not found, even after successful installation of kubetest.

### ISSUE THREAD

**Issue by MadhuriDev** [kubernetes/test-infra#18033]
:~/go/src/k8s.io/test-infra$ go install ./kubetest
go: downloading github.com/aws/aws-sdk-go v1.31.12
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/docker/docker v1.4.2-0.20200203170920-46ec8731fbce
go: downloading github.com/Azure/azure-sdk-for-go v38.0.0+incompatible
go: downloading github.com/Azure/go-autorest v12.2.0+incompatible
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading sigs.k8s.io/boskos v0.0.0-20200526191642-45fc818e2d00
go: extracting github.com/spf13/pflag v1.0.5
go: extracting github.com/Azure/azure-storage-blob-go v0.8.0
go: extracting github.com/Azure/go-autorest v12.2.0+incompatible
go: downloading github.com/Azure/go-autorest/autorest v0.9.6
go: downloading golang.org/x/crypto v0.0.0-20200302210943-78000ba7a073
go: extracting github.com/Azure/go-autorest/autorest v0.9.6
go: downloading github.com/Azure/go-autorest/autorest/adal v0.8.2
go: extracting sigs.k8s.io/boskos v0.0.0-20200526191642-45fc818e2d00
go: downloading github.com/sirupsen/logrus v1.6.0
go: extracting golang.org/x/crypto v0.0.0-20200302210943-78000ba7a073
go: extracting github.com/docker/docker v1.4.2-0.20200203170920-46ec8731fbce
go: extracting github.com/Azure/go-autorest/autorest/adal v0.8.2
go: extracting github.com/sirupsen/logrus v1.6.0
go: downloading github.com/Azure/go-autorest/tracing v0.5.0
go: downloading k8s.io/apimachinery v0.17.3
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: extracting github.com/hashicorp/go-multierror v1.0.0
go: downloading golang.org/x/sys v0.0.0-20200610111108-226ff32320da
go: extracting github.com/Azure/go-autorest/tracing v0.5.0
go: extracting k8s.io/apimachinery v0.17.3
go: downloading github.com/Azure/go-autorest/autorest/date v0.2.0
go: extracting golang.org/x/sys v0.0.0-20200610111108-226ff32320da
go: extracting github.com/Azure/go-autorest/autorest/date v0.2.0
go: downloading github.com/satori/go.uuid v1.2.0
go: extracting github.com/satori/go.uuid v1.2.0
go: downloading github.com/pelletier/go-toml v1.6.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: extracting github.com/pelletier/go-toml v1.6.0
go: extracting github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/docker/go-connections v0.4.0
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/pkg/errors v0.9.1
go: extracting github.com/pkg/errors v0.9.1
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: extracting github.com/docker/go-connections v0.4.0
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
go: extracting github.com/opencontainers/image-spec v1.0.1
go: extracting github.com/docker/distribution v2.7.1+incompatible
go: downloading k8s.io/api v0.17.3
go: extracting github.com/opencontainers/go-digest v1.0.0-rc1
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading golang.org/x/net v0.0.0-20200301022130-244492dfa37a
go: extracting github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/Azure/go-autorest/logger v0.1.0
go: extracting github.com/Azure/go-autorest/logger v0.1.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190610004146-91bb50d98149
go: extracting golang.org/x/net v0.0.0-20200301022130-244492dfa37a
go: extracting github.com/mattn/go-ieproxy v0.0.0-20190610004146-91bb50d98149
go: downloading k8s.io/client-go v0.17.3
go: downloading github.com/google/uuid v1.1.1
go: extracting github.com/google/uuid v1.1.1
go: downloading google.golang.org/grpc v1.27.0
go: extracting google.golang.org/grpc v1.27.0
go: extracting k8s.io/api v0.17.3
go: downloading github.com/gogo/protobuf v1.3.1
go: extracting k8s.io/client-go v0.17.3
go: extracting github.com/gogo/protobuf v1.3.1
go: downloading google.golang.org/genproto v0.0.0-20190911173649-1774047e7e51
go: downloading github.com/golang/protobuf v1.3.4
go: extracting github.com/golang/protobuf v1.3.4
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/containerd/containerd v1.3.3
go: extracting github.com/docker/go-units v0.4.0
go: downloading github.com/imdario/mergo v0.3.8
go: extracting github.com/imdario/mergo v0.3.8
go: downloading k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: extracting github.com/containerd/containerd v1.3.3
go: extracting github.com/aws/aws-sdk-go v1.31.12
go: extracting k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: downloading k8s.io/klog v1.0.0
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: extracting k8s.io/klog v1.0.0
go: downloading github.com/googleapis/gnostic v0.3.1
go: extracting golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/google/gofuzz v1.1.0
go: extracting github.com/google/gofuzz v1.1.0
go: downloading sigs.k8s.io/yaml v1.2.0
go: extracting github.com/googleapis/gnostic v0.3.1
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: extracting sigs.k8s.io/yaml v1.2.0
go: downloading gopkg.in/yaml.v2 v2.2.8
go: extracting golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: downloading golang.org/x/text v0.3.2
go: extracting google.golang.org/genproto v0.0.0-20190911173649-1774047e7e51
go: extracting gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/jmespath/go-jmespath v0.3.0
go: extracting golang.org/x/text v0.3.2
go: extracting github.com/davecgh/go-spew v1.1.1
go: downloading github.com/json-iterator/go v1.1.9
go: extracting github.com/jmespath/go-jmespath v0.3.0
go: extracting gopkg.in/inf.v0 v0.9.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/json-iterator/go v1.1.9
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting github.com/Azure/azure-sdk-for-go v38.0.0+incompatible
go: downloading github.com/Azure/go-autorest/autorest/to v0.3.0
go: downloading github.com/Azure/go-autorest/autorest/validation v0.1.0
go: extracting github.com/Azure/go-autorest/autorest/to v0.3.0
go: extracting github.com/Azure/go-autorest/autorest/validation v0.1.0
go: finding github.com/Azure/azure-sdk-for-go v38.0.0+incompatible
go: finding github.com/Azure/azure-storage-blob-go v0.8.0
go: finding github.com/Azure/go-autorest/autorest v0.9.6
go: finding github.com/Azure/go-autorest/autorest/adal v0.8.2
go: finding github.com/Azure/go-autorest/autorest/to v0.3.0
go: finding github.com/Azure/go-autorest/autorest/validation v0.1.0
go: finding github.com/aws/aws-sdk-go v1.31.12
go: finding github.com/Azure/go-autorest/tracing v0.5.0
go: finding github.com/Azure/go-autorest/autorest/date v0.2.0
go: finding github.com/satori/go.uuid v1.2.0
go: finding github.com/docker/docker v1.4.2-0.20200203170920-46ec8731fbce
go: finding github.com/pelletier/go-toml v1.6.0
go: finding github.com/spf13/pflag v1.0.5
go: finding golang.org/x/crypto v0.0.0-20200302210943-78000ba7a073
go: finding github.com/Azure/go-autorest/logger v0.1.0
go: finding github.com/jmespath/go-jmespath v0.3.0
go: finding github.com/Azure/azure-pipeline-go v0.2.1
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding k8s.io/api v0.17.3
go: finding github.com/docker/go-connections v0.4.0
go: finding github.com/docker/distribution v2.7.1+incompatible
go: finding k8s.io/apimachinery v0.17.3
go: finding github.com/docker/go-units v0.4.0
go: finding k8s.io/client-go v0.17.3
go: finding github.com/opencontainers/image-spec v1.0.1
go: finding github.com/gogo/protobuf v1.3.1
go: finding github.com/mattn/go-ieproxy v0.0.0-20190610004146-91bb50d98149
go: finding github.com/containerd/containerd v1.3.3
go: finding github.com/opencontainers/go-digest v1.0.0-rc1
go: finding github.com/sirupsen/logrus v1.6.0
go: finding github.com/imdario/mergo v0.3.8
go: finding github.com/pkg/errors v0.9.1
go: finding github.com/golang/protobuf v1.3.4
go: finding google.golang.org/grpc v1.27.0
go: finding github.com/googleapis/gnostic v0.3.1
go: finding github.com/google/gofuzz v1.1.0
go: finding gopkg.in/inf.v0 v0.9.1
go: finding golang.org/x/sys v0.0.0-20200610111108-226ff32320da
go: finding google.golang.org/genproto v0.0.0-20190911173649-1774047e7e51
go: finding gopkg.in/yaml.v2 v2.2.8
go: finding sigs.k8s.io/boskos v0.0.0-20200526191642-45fc818e2d00
go: finding k8s.io/klog v1.0.0
go: finding golang.org/x/net v0.0.0-20200301022130-244492dfa37a
go: finding github.com/json-iterator/go v1.1.9
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding github.com/google/uuid v1.1.1
go: finding github.com/hashicorp/go-multierror v1.0.0
go: finding golang.org/x/text v0.3.2
go: finding sigs.k8s.io/yaml v1.2.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: finding golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: finding k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: finding github.com/hashicorp/errwrap v1.0.0

:~/go/src/k8s.io/test-infra$ kubetest
bash: kubetest: command not found

**Comment by amwat** [comment]
Doesn't look like there's a bug in building kubetest itself here.

If you want to execute `kubetest` by name, make sure that the install directory, most likely [$GOBIN](https://golang.org/cmd/go/#hdr-Compile_and_install_packages_and_dependencies), is in your [$PATH](https://en.wikipedia.org/wiki/PATH_(variable)). Alternatively, you can also invoke it by using the full absolute path.

/close
