### ISSUE TITLE
prow tests in kubeflow/pipelines repo flaky without test log

### ISSUE THREAD

**Issue by Bobgy** [kubernetes/test-infra#18067]
**What happened**:
Recently prow presubmit tests became very flaky (>50% failure rate) in kubeflow/pipelines repo.
The weird thing is that these failures all have no test log in prow. Also presubmit tests have been very stable (<5% flakiness rate) before the last 2 days.

**What you expected to happen**:
Tests shouldn't fail without log.

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure

**Please provide links to example occurrences, if any**:
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4065/kubeflow-pipeline-backend-test/1275698698256388101
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4065/kubeflow-pipeline-sample-test/1275698698256388099

**Anything else we need to know?**:

**Comment by Bobgy** [comment]
A even stranger thing is that, a test showed as succeeded in prow: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4065/kubeflow-pipeline-frontend-test/1275718328614129667, but prow bot commented that it failed:

kubeflow-pipeline-frontend-test | d331527 | link | /test kubeflow-pipeline-frontend-test

**Comment by BenTheElder** [comment]
for the second case the artifact / log upload sidecar failed, even though the tests passed.
/area prow
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4065/kubeflow-pipeline-frontend-test/1275718328614129667/podinfo.json
```json
			"containerStatuses": [
				{
					"name": "sidecar",
					"state": {
						"terminated": {
							"exitCode": 255,
							"reason": "Error",
							"startedAt": "2020-06-24T09:16:31Z",
							"finishedAt": "2020-06-24T09:31:21Z",
							"containerID": "docker://ddbff70a8c119923ec19c44605bdb9ffa4a47435fb2b9e1bb66b2eb08a8144ad"
						}
					},
					"lastState": {},
					"ready": false,
					"restartCount": 0,
					"image": "gcr.io/k8s-prow/sidecar:v20200623-9f5410055c",
					"imageID": "docker-pullable://gcr.io/k8s-prow/sidecar@sha256:f43e1c28a11b899d3c16186719a1be182607bdbafbfa9e7789ba3688130bdfd3",
					"containerID": "docker://ddbff70a8c119923ec19c44605bdb9ffa4a47435fb2b9e1bb66b2eb08a8144ad"
				},
```

**Comment by BenTheElder** [comment]
cc @cjwagner 
xref: https://github.com/kubernetes/test-infra/issues/14343

**Comment by Bobgy** [comment]
Thanks @BenTheElder! Was this caused by https://github.com/kubeflow/pipelines/issues/1653?

**Comment by jlewi** [comment]
@Bobgy I believe the prow pods should be running in a cluster in project kubeflow-ci. So you should be able to access the logs in stackdriver to see what's going on.

**Comment by BenTheElder** [comment]
I'm pretty sure this is caused by the pod utilities flaking and failing the job in a non user visible way (see above), however I'm cross referencing the fact that kubeflow shouldn't be on the Kubernetes / CNCF prow w/ support requests.

**Comment by Bobgy** [comment]
Thanks @BenTheElder and @jlewi!

Reading through above links, I understood the history now. I'll take a look at test pods in kubeflow-ci/kubeflow-testing cluster next time if it becomes flaky.

It seems the temporary issue has stopped happen, so I'm closing the issue now.
