### ISSUE TITLE
cherrypicker pushes the branch to the wrong repo

### ISSUE THREAD

**Issue by rmohr** [kubernetes/test-infra#18074]
**What happened**:

We updated the cherrypicker plugin from `gcr.io/k8s-prow/cherrypicker:v20200204-7e8cd997a` to `gcr.io/k8s-prow/cherrypicker:v20200623-9f5410055c`. It stopped working.

We see that the cherrypicker was no longer creating the cherrypick branch in the bot repo. Instead it created the branch in the main repo and then failed to create a PR:

Normally they get created in the `kubevirt-bot` repo: https://github.com/kubevirt-bot/kubevirt/tree/cherry-pick-3604-to-release-0.30 but we got https://github.com/kubevirt/kubevirt/tree/cherry-pick-3614-to-release-0.30.

The cherrypicker then failed to create a PR with:

```
@rmohr: new pull request could not be created: status code 422 not one of [201], body: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"head","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
```

Going back to the old version resolved the issue.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/18077
/close
