### ISSUE TITLE
Add ssm:*Session permission to capa-account* AWS user

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/test-infra#18075]
**What would you like to be added**:
Add ssm:StartSession and ssm:TerminateSession to AWS permissions for Cluster API

**Why is this needed**:
Cluster API Provider AWS does not provision a SSH bastion by default, so we have switched to using AWS SSM Session Manager for host connectivity to scrape instance logs, etc...

However, the ssm:StartSession permission is missing from the allowed permissions:

```
unable to start session: err=AccessDeniedException: User: arn:aws:iam::xxx:user/capa-account-2020-02-18-i is not authorized to perform: ssm:StartSession on resource: arn:aws:ec2:us-west-2:xxx:instance/i-0f379ed15c49bd641
```

cc @detiber

**Comment by detiber** [comment]
@randomvariable I believe this is a dup of https://github.com/kubernetes/test-infra/issues/17190, but we definitely need to follow up on it

**Comment by randomvariable** [comment]
Ah, sorry about that. My github search foo was bad .

/close
