### ISSUE TITLE
Upload Tekton's logs to GCS

### ISSUE THREAD

**Issue by zuiurs** [kubernetes/test-infra#18109]
**What would you like to be added**:

Feature of uploading logs to GCS when we use Tekton as ProwJob agent.

**Why is this needed**:

Now if we use Tekton as ProwJob agent, `sidecar` container is not injected, so the job's logs are not uploaded to GCS. We can see the logs using `tkn` or Tekton Dashboard, but Sinker cleans the ProwJob and the one's logs will be vanished. I don't think good that increase `max_prowjob_age` of Sinker setting because of persistence and resource efficiency.

Would you tell me any solution if it already exists?

**Comment by deedubs** [comment]
Couldn't prow use a mutating webhook to inject the sidecars into a pipeline run?
