### ISSUE TITLE
Takes long time to detect Pod create changes (Informer)

### ISSUE THREAD

**Issue by Mauttaram** [kubernetes/test-infra#18134]
**What happened**:

Used Kubernetes-template to detect changes and which uses Informers to detect changes.
We note that the time to detect a new pod that is running is around 25-40 seconds by informer.
Several times we see this error in the logs:
reflector.go:382] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to watch *v1.Pod: unknown (get pods)
**What you expected to happen**:
Expected to receive no errors
Expected that Shared Informer should not take 25-40secs to detect that a new pod has been created 
**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
Sorry but you have the wrong repo, this repo hosts tools used for the project itself. The informer code is in github.com/kubernetes/kubernetes
