### ISSUE TITLE
Cleanup label descriptions 

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#18147]
**What should be cleaned up or changed**:
Reconcile SIG and WG names in GitHub label descriptions with doc conventions:
- https://kubernetes.io/docs/contribute/style/style-guide/#kubernetes-io-word-list

e.g. instead of sig-foo, SIG Foo

**Provide any links for context**:
https://github.com/kubernetes/test-infra/pull/18063/files#r444610206

/good-first-issue
/cc @sftim @justaugustus

**Comment by kurokochin** [comment]
I'll help to work on this!
