### ISSUE TITLE
Add presubmits in testgrid for repos/modules

### ISSUE THREAD

**Issue by ZhiFeng1993** [kubernetes/test-infra#18159]
Below are all repos that don't have their presubmits in testgrid.
This issue is to track moving this down to just kubernetes-security/
```
var noPresubmitsInTestgridPrefixes = []string{
	"containerd/cri",
	"GoogleCloudPlatform/k8s-multicluster-ingress",
	"kubeflow/pipelines",
	"kubernetes-sigs/cluster-capacity",
	"kubernetes-sigs/gcp-compute-persistent-disk-csi-driver",
	"kubernetes-sigs/gcp-filestore-csi-driver",
	"kubernetes-sigs/kind",
	"kubernetes-sigs/kubebuilder-declarative-pattern",
	"kubernetes-sigs/scheduler-plugins",
	"kubernetes-sigs/service-catalog",
	"kubernetes-sigs/sig-storage-local-static-provisioner",
	"kubernetes-sigs/slack-infra",
	"kubernetes-sigs/testing_frameworks",
	"kubernetes/client-go",
	"kubernetes/cloud-provider-openstack",
	"kubernetes/dns",
	"kubernetes/enhancements",
	"kubernetes/ingress-gce",
	"kubernetes/kubeadm",
	"kubernetes/minikube",
	// This is the one entry that should be here
	"kubernetes-security/",
}
```
This used to be tracked in the code. Make it an independent issue for easier tracking.  
https://github.com/kubernetes/test-infra/blob/master/config/tests/testgrids/config_test.go

**Comment by BenTheElder** [comment]
I'm not sure why we'd want presubmits in testgrid.
Presubmits are very noisy and the heatmap in prow gives better insight (e.g. PRs that don't build are clearly distinct by runtime)

**Comment by BenTheElder** [comment]
cc @spiffxp

**Comment by chases2** [comment]
I got tripped up on this as well. Why do we want to display these tests on TestGrid? They run at variable frequencies against code that may not actually merge or work.

**Comment by spiffxp** [comment]
It's about ensuring that testgrid can be a consistent gateway to all jobs executed by prow.k8s.io, instead of sometimes having to go view prow's deck, or spyglass' job-history page.

Presubmits aren't guaranteed to pass reliably, but testgrid can still provide a useful visual signal if one set of tests starts failing consistently across presubmits

**Comment by chases2** [comment]
We discussed this during today's sig-testing meeting. We didn't come to a consensus, but I do want to note what I heard:

For adding all presubmits to TestGrid:
- Nicer contributor experience: we can say that "all Prow Jobs are (or should be) on TestGrid"
- Makes a history of presubmits easier to discover for more users (ex. if a presubmit gets much flakier)

Against requiring presubmits in TestGrid:
- Tests may run _very_ frequently, putting strain on TG's frontend
- Tuning staleness and pass/fail thresholds for alerting is too difficult to get good signal out of

**Comment by spiffxp** [comment]
/remove-lifecycle stale
>Against requiring presubmits in TestGrid:
>- Tests may run very frequently, putting strain on TG's frontend

Presubmits should default to shorter retention to avoid this strain

>-Tuning staleness and pass/fail thresholds for alerting is too difficult to get good signal out of

Maybe true, but I still think testgrid's summary view can provide me a better glance of "how are merge-blocking presubmits doing" vs looking at https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=presubmit at the moment:
- deck only shows 12h of history
- deck doesn't filter on annotations or labels, so can't filter down to jobs that correspond to a dashboard_tab

I think between configurator getting a little smarter about what kind of information is available from prow config and prow jobs, and possibly supporting multiple defaults, there's room for improvement.

**Comment by BenTheElder** [comment]
I'm not sure we should enforce presubmits in testgrid, I think it would be reasonable to just exclude presubmits from this check and require it for periodic / postsubmit

Periodic / postsubmit we don't want to run if nobody is watching. But presubmits report to PRs.

**Comment by spiffxp** [comment]
/reopen
/remove-lifecycle rotten
If we shouldn't enforce this, we should drop the test.  Or, finish implementing so there are no more special cases.  This middle ground is complexity that doesn't need to be present.
