### ISSUE TITLE
Custom SSH Port

### ISSUE THREAD

**Issue by henri9813** [kubernetes/test-infra#18153]
**What happened**:

During a test, i got this:

```
error dialing root@X.X.X.X:22: 'dial tcp 10.10.50.6:22: connect: connection refused', retrying
Jul  2 18:10:22.292: INFO: ssh root@10.10.50.6:22: command:   mount | grep b12411d3-1eb1-4b3a-8799-5734136775a6 | grep -v volume-subpaths
```

**What you expected to happen**:

My servers does not listen on port 22, but on a custom port.

I define the port to use in my ssh config file ( `~/.ssh/config` ) and the script should use it.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with non port 22 for ssh.

run the test

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
What test are you referring to?
This repo doesn't host any SSH tests...

**Comment by henri9813** [comment]
Hello

I run this:
```
K8S_VERSION=$(kubectl version -o json | jq -r '.serverVersion.gitVersion')
export KUBERNETES_CONFORMANCE_TEST=y
export KUBECONFIG="$HOME/.kube/config"



kubetest --provider=skeleton --test --test_args=”--ginkgo.focus=\[Conformance\]” --extract ${K8S_VERSION} | tee test.out

```

And during the test, it make some connection to other machines on port 22 for ssh.

Best regards.

**Comment by BenTheElder** [comment]
This issue should be filed against the Kubernetes repo, kubetest implements the test workflow but it does not implement the tests, which in this case are test/e2e/e2e.test from the main kubernetes repo.

You should also check if there's an existing issue
