### ISSUE TITLE
JUnit lense changes test-render order randomly

### ISSUE THREAD

**Issue by rmohr** [kubernetes/test-infra#18175]
**What happened**:

When I look at a job with multiple failures I see that the rendered tests are randomly changing their order on page reloads.

**What you expected to happen**:

Best for us would be if they keep the order which they have in the junit.xml. This makes it easy to log additional info for tests without having to create files with very interesting names.

**How to reproduce it (as minimally and precisely as possible)**:

Look for a job with multiple test failures and reload the page multiple times.

**Please provide links to example occurrences, if any**:

Here an example: https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3642/pull-kubevirt-e2e-k8s-1.17/1279367128155164672. Just reload the page a few times.

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
this is probably easy to fix but nobody is really working on this right now
/area prow
/help

**Comment by petr-muller** [comment]
There's https://github.com/kubernetes/test-infra/pull/19029 but it does not seem like a complete fix yet.
