### ISSUE TITLE
mungebot: Flake-manager is not running on kubernetes/kubernetes

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#1818]
I redeployed the submit-queue this morning, and it wouldn't start because of an error while initializing the flake-manager munger. Note that it is NOT because of a change in the repository (I tried to redeploy the previous version and it failed the same way).

Error (can't find it anymore) was along the line: 
> Failed to parse line 917, column 0, not enough field

**Comment by apelisse** [comment]
cc @grodrigues3 @eparis @rmmh @spxtr

**Comment by ixdy** [comment]
bad test owners line?

**Comment by apelisse** [comment]
Might be yeah

**Comment by apelisse** [comment]
is that line ok?

https://github.com/kubernetes/kubernetes/blob/master/test/test_owners.csv#L917

**Comment by ixdy** [comment]
No, it's missing a comma. Also, how did that get there?

**Comment by apelisse** [comment]
Do you mean? How did it pass the script that checks the syntax is correct?

**Comment by rmmh** [comment]
kubernetes/kubernetes#35950 is bad and needs to be reverted.

**Comment by ixdy** [comment]
That PR needs to be reverted, but it wasn't his fault. update_owners.py did the wrong thing.

**Comment by apelisse** [comment]
Also we need a script to check the syntax there ...

**Comment by rmmh** [comment]
hack/update_owners.py is fine. It was a bad merge. We need to make the verify check validate syntax.

**Comment by ixdy** [comment]
oh, I was looking at only one of the commits in that PR. yeah, the verify check needs to check syntax, though we'd also need to start running the check again in CI.

**Comment by ethernetdan** [comment]
Update: csv issue has been resolved, @apelisse is planning on reactivating tomorrow

**Comment by spiffxp** [comment]
closing, #2450 replaced flake-manager with issue-creator and triage-filer, which are still active today
