### ISSUE TITLE
Add reporting supports to multiple slack namespaces from a single instance of prow

### ISSUE THREAD

**Issue by amitkrout** [kubernetes/test-infra#18190]
**What would you like to be added**:
Add reporting supports to multiple slack namespaces (private and public) from a single instance of prow
**Why is this needed**:
Basically we use public slack channel https://openshiftdo.slack.com to communicate our stuff among the team. I can see the prow is only available with coreOS slack https://coreos.slack.com but i can not make use of the same prow instance for public slack one. 

So it would be great if the support is extended to multiple instance of slack namespace

**Comment by amitkrout** [comment]
cc @petr-muller

**Comment by petr-muller** [comment]
/reopen
/remove-lifecycle rotten

We'll want this
