### ISSUE TITLE
Adding new test reports from CNCF projects

### ISSUE THREAD

**Issue by Bowenislandsong** [kubernetes/test-infra#18237]
**What would you like to be added**:

I am not sure what is the qualifications for a project to get added to this test grid. I would like to add some of the test results from https://github.com/operator-framework/ a new CNCF project to the test grid.

In addition, I am also curious if there is a mechanism uploading test results from github workflow to the test grid.

**Why is this needed**:
I am interested to upload the test results for public flak analysis. This issue is to seek for confirmation that such PR adding test results would qualify.

Thank you

**Comment by bparees** [comment]
see https://github.com/openshift/ci-tools/tree/master/cmd/testgrid-config-generator

**Comment by Bowenislandsong** [comment]
thanks
/close
