### ISSUE TITLE
benchmarkjunit: allow streaming output to stdout

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#18267]
**What would you like to be added**:

It would be nice if benchmarkjunit can stream output to stdout. For example, something like `go run ./pkg/benchmarkjunit ./experiment/dummybenchmarks -l -` where output goes to stdout, and its not buffered.

**Why is this needed**:

This way when running we can see progress, rather than waiting for the entire test to finish.

**Comment by BenTheElder** [comment]
cc @cjwagner

**Comment by cjwagner** [comment]
Here's a PR: https://github.com/kubernetes/test-infra/pull/19042
