### ISSUE TITLE
Testgrid not showing tests that ran and have unit files

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/test-infra#1827]
See https://k8s-testgrid.appspot.com/google-node#kubelet-serial-gce-e2e for example.
Search for "DynamicKubelet". Nothing.
But go e.g. here https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/83/artifacts/junit_containervm01.xml and search for "DynamicKubelet" and you get:
```
<testcase name="[k8s.io] DynamicKubeletConfiguration [Feature:DynamicKubeletConfig] [Serial] [Disruptive] When a configmap called `kubelet-<node-name>` is added to the `kube-system` namespace The Kubelet on that node should restart to take up the new config" classname="E2eNode Suite" time="70.910405952"/>
```
which shows that the test ran.

This may or may not relate to having a `[Feature:.*]` tag in the test name.

/cc @kubernetes/test-infra-maintainers @ixdy

**Comment by krzyzacy** [comment]
cc @michelle192837

**Comment by krzyzacy** [comment]
ok..
```
<testcase name="[k8s.io] DynamicKubeletConfiguration [Feature:DynamicKubeletConfig] [Serial] [Disruptive] When a configmap called `kubelet-<node-name>` is added to the `kube-system` namespace The Kubelet on that node should restart to take up the new config" classname="E2eNode Suite" time="70.910405952"/>
```

and in which I bet <node-name> is screwed with junit parsing and results in a `k8s.io - node-name` entry in testgrid.

**Comment by fejta** [comment]
Is that valid xml?

**Comment by Random-Liu** [comment]
> in which I bet <node-name> is screwed with junit parsing and results in a k8s.io - node-name entry in testgrid.

Totally make sense to me. Will send a fix.

**Comment by krzyzacy** [comment]
@fejta I would wish stuff within quotes will be a string... but obviously not the case here :-(

**Comment by fejta** [comment]
@Random-Liu if you can change the test name that will definitely be the fastest option.

However I would still like to understand the core issue here -- we should be able to have a <> in the test case name. Are we doing a bad job serializing the xml file or parsing it? @rmmh @spxtr And is this our code or vendored code?

**Comment by ixdy** [comment]
Seems like the test name isn't being properly escaped in the junit. This is either a bug in Ginkgo or in the Go xml encoding library.

**Comment by fejta** [comment]
There's still the possibility that different systems disagree on what is/is not valid xml

**Comment by ixdy** [comment]
W3C makes it pretty clear that < shouldn't be in an attribute: https://www.w3.org/TR/xml/#syntax

**Comment by rmmh** [comment]
That's your browser interpreting the name. If you look at it raw, it's properly escaped:

          <testcase name="[k8s.io] DynamicKubeletConfiguration [Feature:DynamicKubeletConfig] [Serial] [Disruptive] When a configmap called `kubelet-&lt;node-name&gt;` is added to the `kube-system` namespace The Kubelet on that node should restart to take up the new config" classname="E2eNode Suite" time="70.910405952"></testcase>

**Comment by krzyzacy** [comment]
It shows up fine now, and we filed a bug against testgrid, close this here.
