### ISSUE TITLE
Updates to Coverage muddle Triage results with less-than useful info

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#18322]
**What should be cleaned up or changed**:
Due to the changes the went in with #18276 and #18182 that extended how coverage junit is built, we not see those failure overwhelming [triage](https://storage.googleapis.com/k8s-gubernator/triage/index.html). For now we should just remove these results and later determine if there is need / use in them being included.

The [TestGrid Dashboard](https://testgrid.k8s.io/sig-testing-canaries#ci-kubernetes-coverage-unit) should be used for now.

**Comment by michaelkolber** [comment]
Comment

**Comment by MushuEE** [comment]
/assign @michaelkolber 
trying now

**Comment by michaelkolber** [comment]
Seems to be working fine: https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=ci-kubernetes-coverage-unit

/close
