### ISSUE TITLE
Tide seems to wait for all batches to be finished before merging

### ISSUE THREAD

**Issue by rmohr** [kubernetes/test-infra#18334]
**What happened**:

I am not 100% sure, but it looks like tide waits for all triggered batch jobs to be finished before it merges a batch. This may make sense if a bigger batch than the already green batch is still running, but it looks like it even waits if the bigger batch is already green.

An example would be this batch merge on our Prow instance:

![batch_long_wait](https://user-images.githubusercontent.com/4534621/87639626-ce895900-c745-11ea-96c9-14a2832f8eba.png)

The 4 PR batch was done roughly 30 minutes after the second batch with 3PRs was triggered. It looks like it then still waited for the second batch to finish.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
So generally we priorize merging batches over triggering batches and merge a batch whenever it has passing tests:
https://github.com/kubernetes/test-infra/blob/5069c223d7711012639b131e84830d43b5a777f5/prow/tide/tide.go#L1251-L1267

The triggering of the batch in the middle doesn't really make sense to me.

cc @cjwagner any idea?

**Comment by alvaroaleman** [comment]
@rmohr can you provide all prowjob objects for both batches and ideally the tide logs?
