### ISSUE TITLE
Create a plugin that tests job changes

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#18338]
**What would you like to be added**:

A way to test job changes. Openshift does this via a CLI that checks out the config repo, finds changed jobs and creates a so-called "rehearse" job": https://github.com/openshift/ci-tools/tree/master/cmd/pj-rehearse. What openshift does is highly specific because many jobs there rely on configmaps that then also need to be deployed. This shouldn't be the case for most jobs of other prow instances.

So basically a plugin that on config-repo (test-infra in kube casse) PRs:
* Finds added/changed jobs
* Creates an instance of them and reports that back to the job change pr
* Potentially this needs opt out logic and/or a dedicated command to trigger this
* Some railguards i.E. create at most N rehearse jobs

**Why is this needed**:

Because currently job config changes are untestable if access to the prow.k8s.io build cluster is not given.

/area prow
/cc @BenTheElder @fejta

**Comment by BenTheElder** [comment]
We usually just ask that users create a manually triggered "canary" copy of
the job where risky changes are first trialed for things that depend on CI
resources.

For things that don't there's the local running options (mkpod, pj-on-kind,
phaino ...)

**Comment by alvaroaleman** [comment]
Yeah in my experience jobs that do not actually run in the real cluster are just different. `mkpod` requires to set up a different decoration config or know other intimate details. Many jobs generally assume the presence of certain secrets.

I just ran into the issue with my "increase CPU requests oh damn the cluster doesn't have nodes this size" change and since I am used to getting feedback on job changes, I wanted to leave the idea here.

I am not going to build this, it is just intended as an idea for the ppl that have to regularly deal with the fun of this.
