### ISSUE TITLE
[config-updater][metrics]prow_configmap_size_bytes is 0

### ISSUE THREAD

**Issue by hongkailiu** [kubernetes/test-infra#18347]
**What happened**:

The metric `prow_configmap_size_bytes` has `0` for some non-empty CMs.

![Screen Shot 2020-07-16 at 4 06 59 PM](https://user-images.githubusercontent.com/4013349/87717488-73278d00-c77e-11ea-8b2d-17d5c49a0d36.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by matthyx** [comment]
@hongkailiu are you still experiencing this behavior? Can you provide some links to prow configmaps?

**Comment by hongkailiu** [comment]
> @hongkailiu are you still experiencing this behavior? Can you provide some links to prow configmaps?

Sorry for my late reply.
It looks fine now.
<img width="1158" alt="Screen Shot 2021-03-24 at 3 28 55 PM" src="https://user-images.githubusercontent.com/4013349/112372155-cf4f9300-8cb5-11eb-8013-76c1d55b4b45.png">
