### ISSUE TITLE
pull-test-infra-gubernator	failing

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#18386]
From Job History, looks like it's been failing since the 17th (https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-test-infra-gubernator).

Example @ https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/18355/pull-test-infra-gubernator/1285260858326257665

/assign @fejta 
/area gubernator

**Comment by spiffxp** [comment]
Will be fixed by https://github.com/kubernetes/test-infra/pull/18391

**Comment by michelle192837** [comment]
Looks like this is still failing :(

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/18414/pull-test-infra-gubernator/1285989995366060032
https://github.com/kubernetes/test-infra/pull/18414

**Comment by michelle192837** [comment]
Oh, though there _are_ some passing runs, so it's not just failing.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/18448 should fix and cause future PRs to fail this check prior to merging

**Comment by spiffxp** [comment]
/close
Closing in favor of https://github.com/kubernetes/test-infra/issues/18770
