### ISSUE TITLE
Label plugin parsing problem ("The label(s) kind/ cannot be applied")

### ISSUE THREAD

**Issue by benmoss** [kubernetes/test-infra#18380]
**What happened**:
Comments to add labels to issues seem to occasionally parse incorrectly, making the Prow bot comment

> The label(s) kind/ cannot be applied, because the repository doesn't have them

It still does apply the expected labels.

**What you expected to happen**:
No complaint about a `kind/` label.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure. I checked the test cases and they seem to cover this, I think I need to see the raw GitHub comment body to be sure.

**Please provide links to example occurrences, if any**:
https://github.com/kubernetes-sigs/cluster-api/issues/3368#issuecomment-660311253
https://github.com/operator-framework/operator-sdk/issues/2876#issuecomment-617895480
https://github.com/kubernetes/kubernetes/pull/89323#issuecomment-602006978
https://github.com/kubernetes-sigs/cluster-api/issues/3395#issuecomment-663590737

**Comment by benmoss** [comment]
https://github.com/kubernetes-sigs/cluster-api/issues/3720#issuecomment-701442225 another one 😸

**Comment by nikhita** [comment]
This was fixed in https://github.com/kubernetes/test-infra/pull/19391 yesterday. The changes should get pulled in once https://github.com/kubernetes/test-infra/pull/19396 merged. :)

**Comment by nikhita** [comment]
Going to close this since https://github.com/kubernetes/test-infra/pull/19391 fixed it. Please reopen if needed!
