### ISSUE TITLE
e2e-down.sh is called 3 times in every e2 run

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/test-infra#1840]
While it is wasteful to run e2e-down.sh even twice in a single e2e run - once in the beginning before e2e-up.sh and once at the end after the tests, it is understandable why we are doing that. But e2e-down.sh is being called thrice in a single e2e run now - once in the beginning and twice at the end. This is causing a lot of pain for federation tests where we setup 3 clusters. This must be fixed.

cc @kubernetes/test-infra-maintainers @fejta

**Comment by krzyzacy** [comment]
I think twice in beginning & twice in the end, when I last noticed. @ixdy quick ideas?

**Comment by ixdy** [comment]
Fix [this TODO](https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L177-L179). Maybe detect if the normal teardown was run, and cancel the deferred teardown if so?
