### ISSUE TITLE
Slack reporter fails to report sometimes

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#18432]
Getting a couple of errors yesterday and today that the Slack reporter failed to report.

Within the last week, happened 5 times: twice at 2020-07-21 05:05:02.000 PDT, once at 2020-07-22 09:15:02.000 PDT, once at 2020-07-22 09:33:02.000 PDT, once at 2020-07-22 09:42:02.000 PDT

Example error:
```
jsonPayload: {
  component: "crier"   
  error: "failed to write Slack message: Post https://slack.com/api/chat.postMessage: connection error: PROTOCOL_ERROR"   
  file: "prow/crier/controller.go:277"   
  func: "k8s.io/test-infra/prow/crier.(*Controller).processNextItem"   
  jobName: "ci-cri-containerd-node-e2e-flaky"   
  jobStatus: "failure"   
  level: "error"   
  msg: "failed to report job"   
  prowjob: "default/72f4a835-cc32-11ea-8f9c-6aebfd5be0c2"   
  reporter: "slackreporter"   
 }
```
And looking at the logs for slackreporter doing things in the last 7 days, it looks like those are the only non-debug logs (no successful reports, from what I can see).

I saw that Alvaro and Chi have made recent updates to this code, so passing off to them. (Feel free to kick it back if you're sure your changes are not the cause!) 

/assign @alvaroaleman @chizhg 
/area prow prow/crier
/kind oncall-hotlist

**Comment by alvaroaleman** [comment]
@michelle192837 until proven otherwise, I would assume those were transient errors because sometimes using a network  goes wrong for arbitrary reason. Can you for one of those check the prowjob object in GCS and check on `.status.prev_report_states["slackreporter"]`? It will tell you the last job status that was reported successfully (if any). If that field has a value of `failure` for the job you pasted above, the reporting succeeded in a subsequent attempt.

**Comment by michelle192837** [comment]
If https://prow.k8s.io/prowjob?prowjob=982aec32-cc38-11ea-8f9c-6aebfd5be0c2 is the right kind of thing to check, then yup, looks like it has 'failure' there.

Ah, and looking at the slackreporter, looks like the only logs it'll print are debug or error level, so we don't expect any real logs on a success? (`crier` has logs for the failure to report, and then subsequent success reporting, so it does look fine I think).

Alright, think it is just transient then, thanks!
