### ISSUE TITLE
netd e2e tests failing

### ISSUE THREAD

**Issue by bcheung** [kubernetes/test-infra#18456]
**What happened**:
The [sig-network-netd dashboard](https://k8s-testgrid.appspot.com/sig-network-netd) shows that the e2e tests are failing. 

**Please provide links to example occurrences, if any**:
Seems like [this curl request](https://github.com/kubernetes/kubernetes/blob/8e5c02255cc62c504cb6e5ab8ded9df966ad9891/cluster/get-kube.sh#L246) fails due to a stale link shown in [these logs](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-containerd-gce-calico/1286399580006518786#1:build-log.txt%3A416).

**Anything else we need to know?**:
This seems to be the stale link: https://storage.googleapis.com/koonwah-repo-pub/devel/v1.11.2-beta.0.20+21777efd99bd59/kubernetes.tar.gz
Which is set in each of the jobs in [this config file](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-network/ci-e2e-gce-netd.yaml). 
Here is one of the specific lines that needs to be updated: https://github.com/kubernetes/test-infra/blob/12e538e12769d0e057de511f289a6197304ae7f5/config/jobs/kubernetes/sig-network/ci-e2e-gce-netd.yaml#L934
cc @AnishShah @anfernee

**Comment by BenTheElder** [comment]
Dupe https://github.com/kubernetes/kubernetes/issues/93377

Test-infra maintainers don't own Netd testing

**Comment by BenTheElder** [comment]
Per the other issue these jobs will be removed by the owners.
