### ISSUE TITLE
No method to track `/retest` usage, a helpful metric for flake indication in k8s

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#18450]
**What would you like to be added**:
A way to query and track how often `retest` and maybe some other triggers are called on k8s PRs.
 
**Why is this needed**:
As part of the effort to extend useful metrics around flake impact and shed some light on resource use caused by `retest`, it would be nice to have some tracking.

/assign

**Comment by nikhita** [comment]
@MushuEE Did you already have an approach in mind for this (I see that you assigned yourself). This looks like it could be a good candidate for devstats as well - https://github.com/cncf/devstats - and should be easier to handle there.

cc @LappleApple @mrbobbytables

**Comment by LappleApple** [comment]
Hi @nikhita, I've added this issue to my DevStats notes.

**Comment by MushuEE** [comment]
@LappleApple @nikhita I was looking at the `devstats` and reached out asking if we had those metrics already. I think Devstats is the best place for WebHook data. Keep me in the loop! I am working on flake reporting right now and would be happy to add whatever we need to start tracking `retest` metrics. Not sure how to do this yet however, need a little bit of time to dig deeper. @cjwagner, pointed me to devstats originally. I will start looking how to push metrics there. The [List](https://docs.google.com/document/d/1o5ncrY6lVX3qSNJGWtJXx2aAC2MEqSjnML4VJDrNpmE/edit?pli=1) of requested metrics looks long.

**Comment by nikhita** [comment]
> would be happy to add whatever we need to start tracking retest metrics. Not sure how to do this yet however, need a little bit of time to dig deeper. 

In the past, we've created an issue in the devstats repo asking for new dashboards/metrics and the maintainer has created them for us. @LappleApple has been representing kubernetes' feature requests and concerns to devstats these days, so I think she can probably point to next steps better. :)

**Comment by LappleApple** [comment]
Thank you @nikhita . Hi @MushuEE -- I've actually got a series of sessions on DevStats set up, first one was yesterday (three more scheduled). I'll send you the info (hopefully it's time zone-compatible) and you might consider joining us. :)

**Comment by MushuEE** [comment]
@LappleApple Thank you! Speaking with @BenTheElder it seems that the behavior of `/retest` might be quite a noisy metric and there might be some better metrics such as if tests change state after `/retest` is run on the same HASH. More direct flake indication. Apparently a lot of the `/retest`s are triggered automatically

**Comment by MushuEE** [comment]
Going to close this in favor of a future metrics effort
