### ISSUE TITLE
Bot did not add labels

### ISSUE THREAD

**Issue by calvinbui** [kubernetes/test-infra#18482]
**What happened**: The k8s-ci-robot did not add the necessary `Contributions Allowed` label to my PR @ https://github.com/helm/charts/pull/23292. It also missed the `size/M` label.

**What you expected to happen**: The `Contributions Allowed` and `size/M` labels to be added after the PR is created

**How to reproduce it (as minimally and precisely as possible)**: Created a PR from my fork to the Helm Charts repo. Nothing special.

**Please provide links to example occurrences, if any**: 
- Faulty PR: https://github.com/helm/charts/pull/23292
- Good PR: https://github.com/helm/charts/pull/23352
- PR Status: https://prow.k8s.io/pr?query=is%3Apr%20repo%3Ahelm%2Fcharts%20author%3Acalvinbui%20head%3Amysql-metricRelabelings

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
`Contributions Allowed` doesn't exist in this repository, I don't think our robots have anything to do with this.

**Comment by BenTheElder** [comment]
For that matter it doesn't exist in any Kubernetes repo https://cs.k8s.io/?q=Contributions%20Allowed&i=nope&files=&repos=

I think you need to file a bug with helm.

See also: https://github.com/kubernetes/test-infra/issues/12863

**Comment by BenTheElder** [comment]
checking a PR there, the @helm-bot account is responsible for this label https://github.com/helm/charts/pull/23367#event-3592087002

Helm is not part of the kubernetes project (IIRC they chose to leave to be a separate CNCF project), we don't own or maintain their robots.

**Comment by calvinbui** [comment]
i followed the link in the bot's comments to come to kubernetes/test-infra.

i'll open an issue back over in helm

![image](https://user-images.githubusercontent.com/3604363/88605161-7eeb4b80-d0bc-11ea-836b-dac0c0eb2b10.png)

**Comment by BenTheElder** [comment]
Gotcha, thanks!
Yeah, eventually that bot won't operate in that repo anymore, i'm not sure when we'll get work on https://github.com/kubernetes/test-infra/issues/12863

**Comment by mattfarina** [comment]
The _Contributions Allowed_ label is added by a bot on the Helm project. The Kubernetes automation, which we plan to use until the repo is deprecated this coming November, just happens to use that.
