### ISSUE TITLE
ci-test-infra-benchmark-demo spams triage dashboard

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#18480]
**What happened**:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1#d2fcbd76899acda45017

**What you expected to happen**:

i expect failures in triage to be things we legitimately need to look into

**How to reproduce it (as minimally and precisely as possible)**:

discover that this job exists while looking through our CI failures in go.k8s.io/triage

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
FYI @liggitt @spiffxp @MushuEE @michaelkolber

**Comment by BenTheElder** [comment]
also .. does a "demo" job need to run every 20 minutes ...?
https://github.com/kubernetes/test-infra/blob/691fd981fd87549368893aa960e2d1c36af4e38e/config/jobs/kubernetes/test-infra/test-infra-canaries.yaml#L15

**Comment by MushuEE** [comment]
Yeah a 10 min and 20 min canary seems excessive, was it designed to be an early/frequent warning system? Looks like it came to be from a big migration

**Comment by BenTheElder** [comment]
We should still do something about this issue.
I forget if we made the change to kettle... Even if we did we should probably reduce the frequency here.

cc @cjwagner @spiffxp

**Comment by michaelkolber** [comment]
We can do what we did with #18322 and add a condition to the SQL query, but I feel like the right way to do it would be to stop this test from reporting its failures to BigQuery? If that's possible.

**Comment by MushuEE** [comment]
So that is Kettle's job, uploading to BQ. We could include a list of exclusions for kettle? And remove them from Triage. Adding them in triage is just pushing them down the stack.

**Comment by MushuEE** [comment]
Also... for that benchmark job. Can we expect Fail/Error? Instead of letting them fail?

**Comment by MushuEE** [comment]
Ah ok so just found https://github.com/kubernetes/test-infra/blob/1f2f32cb9e0bffdb73252025887ffd3b82e2a12a/kettle/make_db.py#L170-L171

I will put up a PR to add both coverage and banchmark

**Comment by cjwagner** [comment]
> also .. does a "demo" job need to run every 20 minutes ...?
> https://github.com/kubernetes/test-infra/blob/691fd981fd87549368893aa960e2d1c36af4e38e/config/jobs/kubernetes/test-infra/test-infra-canaries.yaml#L15

It was handy when developing, but certainly excessive now. I'll file a PR to switch it to once a day (72x less frequently 🙂 ).

**Comment by MushuEE** [comment]
Can this be closed now?

**Comment by BenTheElder** [comment]
yes, it can (very belated!)
