### ISSUE TITLE
"Pod scheduling timeout." is displayed as a job failure without additional context by spyglass' metadata lens.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#18528]
**What happened**:
ProwJobs that error out due to "Pod scheduling timeout." are incorrectly described by the metadata lens:
```
Test started last Monday at 6:22 PM failed after 1m26s. (more info)
```
These failures are particularly opaque to users because no build log or pod info is available. The only way to determine that the job actually errored out due to a pod scheduling timeout instead of failing normally is to look at the ProwJob YAML/JSON and check the `status` section.

**What you expected to happen**:
The metadata lens should indicate the correct job state (`error` rather than `failure`) and it should include the status description ("Pod scheduling timeout.")

**How to reproduce it (as minimally and precisely as possible)**:
Create a ProwJob that can't be scheduled (e.g. requires more CPU than any node can provide) and try to run it.

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-conformance-kind-ga-only/1288101820190691330

/help
/area prow prow/deck prow/spyglass

**Comment by BenTheElder** [comment]
@hasheddan I think you fixed this in https://github.com/kubernetes/test-infra/pull/18537 ?

**Comment by hasheddan** [comment]
@BenTheElder a `failure` is still reported instead of `error` even though the appropriate hint is now being displayed. I have a follow up for that and may also see if I can surface a little more info to troubleshoot why a pod scheduling failure occurred 👍
