### ISSUE TITLE
Prow issue: broken link to a page with kubernetes members

### ISSUE THREAD

**Issue by php-coder** [kubernetes/test-infra#1853]
In the @k8s-ci-robot  message [you can't request testing unless you are a kubernetes member](https://github.com/kubernetes/kubernetes/pull/41190#issuecomment-278677087) a link to the page with list of kubernetes members is broken -- https://github.com/kubernetes/people

**Comment by spxtr** [comment]
Thanks, it should be https://github.com/orgs/kubernetes/people
