### ISSUE TITLE
Increase monitoring.prow.k8s.io retention to 1y

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#18546]
It has been set to 30d, which means we don't have the ability to look at trends over a full kubernetes release cycle, let alone comparing against a prior release cycle.

Trends I'm particularly interested in
- what's the size of the tide pool like over time?
- how many pods have hit error state over time?
- what's our boskos pool usage over time?

https://github.com/kubernetes/test-infra/pull/18545 increased to 90d

Will likely need to increase PV size to fit 1y of data.

/area prow

**Comment by BenTheElder** [comment]
cc @cjwagner @MushuEE

**Comment by MushuEE** [comment]
I am not super familiar with PVC using VCT, does that dynamically scale? I think I have only used the VolumeClaimTemplate in the context of StatefulSets
