### ISSUE TITLE
Make critical jobs Guaranteed Pod QOS: ci-kubernetes-build-fast

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#18578]
**What should be cleaned up or changed**:

This is part of https://github.com/kubernetes/test-infra/issues/18530

The following jobs should be Guaranteed Pod QOS, meaning they should have CPU and memory resource limits, and matching resource requests:
- ci-kubernetes-build-fast

These jobs run on (google.com only) k8s-prow-build, so @spiffxp has provided the following guess:
- suggest 6 cpu, 12Gi mem

General steps to follow:
- update the job definitions in [/config/jobs](/config/jobs) to have matching CPU and memory limits and requests
  - e.g. ([ci-kubernetes-e2e-gci-gce has a `resources:` field with matching entries](https://github.com/kubernetes/test-infra/blob/2eac54f721ed58479a3126e4f9ca5cbfcc73821b/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L357-L394))
- open a pull request, include a link to this issue and cc `@kubernetes/ci-signal` in the description
- keep an eye on the jobs for the next few days, and if they start failing more than usual, open followup pull requests to raise resources
  - can look at recent prow.k8s.io runs (e.g. https://prow.k8s.io/?job=ci-kubernetes-e2e-gci-gce)
  - can look at job history (e.g. https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce)
  - can look at testgrid dashboards (e.g. https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default)
- after the job has remained stable for a few days, declare victory

/sig testing
/sig release
/area jobs
/area release-eng

**Comment by spiffxp** [comment]
/reopen
Keeping open to confirm the job is still healthy

**Comment by ZhiFeng1993** [comment]
@spiffxp  I'll keep an eye on this job.

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-release-master-blocking#build-master-fast&graph-metrics=test-duration-minutes&width=20
- will want to keep an eye on jobs triggered since 2020-08-03 2:23pm PDT
- looking specifically not just for "already built, just used cached copy" invocations, but the longer 20-30m invocations that do an actual build

**Comment by spiffxp** [comment]
https://prow.k8s.io/tide-history?repo=kubernetes%2Fkubernetes&branch=master - whenever a `MERGE` event next happen here, the next build should be one of the longer invocations

**Comment by ZhiFeng1993** [comment]
Job has been passing in the past 1 hour(after the code got merged). 
https://prow.k8s.io/?job=ci-kubernetes-build-fast

**Comment by spiffxp** [comment]
/remove-help
since @ZhiFeng1993  has it

**Comment by hasheddan** [comment]
@ZhiFeng1993 noticed a timeout today: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build-fast/1290720926400253952

**Comment by ZhiFeng1993** [comment]
> @ZhiFeng1993 noticed a timeout today: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build-fast/1290720926400253952

Thanks for the heads-up. We merged the code yesterday and the job has been running ok for 20 hours. The 2 timeouts happened an hour ago. I'm not sure whether we need to change the config for this job. Will wait for more data.

**Comment by spiffxp** [comment]
The last three runs in a row have timed out.  Looking over the rest of the testgrid history, this isn't the first time we've seen this sort of behavior.  I think 30min is too tight of a timeout.  Going to bump to 40.

**Comment by hasheddan** [comment]
Thanks @spiffxp!

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/pull/18657 to address

**Comment by ZhiFeng1993** [comment]
/close

I think it's safe to close this one. cc. @RobertKielty

**Comment by RobertKielty** [comment]
Thank you @ZhiFeng1993 :) 
/close
