### ISSUE TITLE
establish test plan for sig-node-containerd

### ISSUE THREAD

**Issue by tpepper** [kubernetes/test-infra#18570]
**What should be cleaned up or changed**:
https://testgrid.k8s.io/sig-node-containerd failing tests and test variations need cleanup.

Around half of the board is failing completely.  Half of the remaining half is flakey.  And many of the remainder seem to not be curated for relevance.  Eg: The so-called "containerd-node-conformance" sounds good in name, but is testing containerd 1.2 against Kubernetes 1.15.  Do we care about 1.2 primarily?  Or 1.3?  Or just master?  Relative to which Kubernetes releases?  Relative to which cloud-providers and which operating systems?

**Provide any links for context**:
http://storage.googleapis.com/k8s-metrics/failures-latest.json
https://github.com/kubernetes/test-infra/pull/18569
https://github.com/kubernetes/test-infra/pull/18509#discussion_r463787590

/sig node

**Comment by alejandrox1** [comment]
/cc @kubernetes/sig-node-test-failures 
ptal

**Comment by bsdnet** [comment]
containerd 1.2/1.3 is still in production. We need to figure out what's the policy to retire some tests, for example containerd 1.2.
For the failing tests, we need to try our best to find out whether they provide useful signals. If not, good to remove in the meeting in case people knew how to fix those tests.

**Comment by adisky** [comment]
I did some research on [sig-containerd-dashboard](https://testgrid.k8s.io/sig-node-containerd)
https://docs.google.com/spreadsheets/d/1mN1fG0dq6t7dZTzl-g9fFNwFqD8XdbbKlr5D3R7BRzc/edit?usp=sharing

AFAIK We have following types of periodic tests for containerd, please refer above sheet for exact test-grid-dashboard tab name.
- **Kubernetes E2E**
Test grid dashboard name: containerd-e2e-*
```
k8s 1.15, containerd 1.2, cos
k8s 1.16, containerd 1.3,  cos
k8s Master, containerd Master, cos
k8s Master, containerd Master, ubuntu
```
- **Node Conformance**
 ```
k8s 1.16, containerd 1.3
k8s Master, containerd Master
```
- **Node Features**
```
k8s 1.15, containerd 1.2
k8s 1.16, containerd 1.3
k8s Master, containerd Master
```
- **Image Validation** 
```
k8s master, containerd master, k8s e2e, cos
k8s master, containerd master, k8s e2e, ubuntu
k8s master, containerd master, node e2e, cos
k8s master, containerd master, node e2e, ubuntu
```

- **Build Containerd**
```
master, 1.2, 1.3, cri master
```
- **Windows** 
(need to update)

- Kubernetes E2E with focus on features(ingress, multizone etc.)
```

**Comment by adisky** [comment]
based on the above analysis, following things we need to figure out

**Comment by SergeyKanzhelev** [comment]
cc: @dmcgowan

**Comment by adisky** [comment]
As discussed in SIG-node CI weekly meeting, 

Action Items:

- [ ] Start moving containerd jobs to sig-node-critical tab 
- [ ] Need to find any policy documented by kubernetes for containerd support versions, if not we need to define them.
- [ ] Define what jobs containerd owns/ what jobs k8s team owns
- [ ] Check for containerd build job removal.

**Comment by adisky** [comment]
> 
> - **Build Containerd**
> ```
> master, 1.2, 1.3, cri master
> ```

can someone from containerd give their inputs here? do we need to keep containerd periodic build jobs? https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/containerd.yaml#L42-L99

Also on what combination of k8s and containerd version we should run tests(K8s e2e, node conformance, node features)?

cc @dmcgowan @mikebrow

**Comment by SergeyKanzhelev** [comment]
/assign @knabben 

Let's write down a small proposal on which versions of Containerd we want to test on which versions of kubernetes and where to put these tests

**Comment by adisky** [comment]
from containerd repo https://github.com/containerd/cri#support-metrics
containerd 1.4 : k8s v1.19, v1.20
containerd 1.3 : k8s v1.15+
so i think we can test in following combinations
```
containerd 1.3 - k8s v1.18
containerd 1.4 - k8s v1.19
containerd 1.4 - k8s v1.20
```

**Comment by ehashman** [comment]
/remove-lifecycle stale

@adisky says that the testgrid tab has been cleaned up, there's a bit more follow-up to do before we can close this out: a few more jobs to clean out that are failing + ensuring we have all the combos above tested.
