### ISSUE TITLE
Make critical jobs Guaranteed Pod QOS: ci-kubernetes-build

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#18577]
**What should be cleaned up or changed**:

This is part of https://github.com/kubernetes/test-infra/issues/18530

The following jobs should be Guaranteed Pod QOS, meaning they should have CPU and memory resource limits, and matching resource requests:
- ci-kubernetes-build
- ci-kubernetes-build-1-19
- ci-kubernetes-build-stable1
- ci-kubernetes-build-stable2
- ci-kubernetes-build-stable3

These jobs run on (google.com only) k8s-prow-build, so @spiffxp has provided the following guess:
- 7 cpu (or as near 8 as you can get), slightly above 32 Gi mem (34?)

General steps to follow:
- update the job definitions in [/config/jobs](/config/jobs) to have matching CPU and memory limits and requests
  - e.g. ([ci-kubernetes-e2e-gci-gce has a `resources:` field with matching entries](https://github.com/kubernetes/test-infra/blob/2eac54f721ed58479a3126e4f9ca5cbfcc73821b/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L357-L394))
- open a pull request, include a link to this issue and cc `@kubernetes/ci-signal` in the description
- keep an eye on the jobs for the next few days, and if they start failing more than usual, open followup pull requests to raise resources
  - can look at recent prow.k8s.io runs (e.g. https://prow.k8s.io/?job=ci-kubernetes-e2e-gci-gce)
  - can look at job history (e.g. https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce)
  - can look at testgrid dashboards (e.g. https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default)
- after the job has remained stable for a few days, declare victory

/sig testing
/sig release
/area jobs
/area release-eng

**Comment by ZhiFeng1993** [comment]
https://prow.k8s.io/?job=ci-kubernetes-build

**Comment by spiffxp** [comment]
/remove-help
since @ZhiFeng1993  has it

**Comment by ZhiFeng1993** [comment]
/close

I think it's safe to close this one. cc. @RobertKielty

**Comment by spiffxp** [comment]
Looking at testgrids

https://testgrid.k8s.io/sig-release-master-blocking#build-master&graph-metrics=test-duration-minutes&width=20 - looks mostly ok

https://testgrid.k8s.io/sig-release-1.19-blocking#build-1.19&graph-metrics=test-duration-minutes&width=20 - same

https://testgrid.k8s.io/sig-release-1.18-blocking#build-1.18&graph-metrics=test-duration-minutes&width=20 - this concerns me
![Screen Shot 2020-08-12 at 3 22 21 PM](https://user-images.githubusercontent.com/49258/90074249-a5f66f80-dcaf-11ea-816e-e5442f8d29e0.png)

The two peaks on the right are what I think is "good" behavior... the job fails due to timeout for Reasons™, but there is a followup run that doesn't, and the build is available for use.

The two peaks on the _left_ don't have any runs after that are OK.  Did incomplete builds get published?

More importantly... is this new behavior? Or has this been happening prior to us setting resource constraints?

**Comment by spiffxp** [comment]
The resource limit changes merged 2020-08-03 4:20pm PDT

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build-stable1/1289866689743163392 - is an example of a build falling prey to this problem _before_ the change was deployed.  So I don't think this is new behavior

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/test-infra/issues/18808 to address the bad build job behavior

Given that it's pre-existing bad behavior, I'm willing to call this done

/close

**Comment by spiffxp** [comment]
Thanks @ZhiFeng1993 !
