### ISSUE TITLE
Make critical jobs Guaranteed Pod QOS: pull-kubernetes-bazel-build

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#18583]
**What should be cleaned up or changed**:

This is part of https://github.com/kubernetes/test-infra/issues/18530

The following jobs should be Guaranteed Pod QOS, meaning they should have CPU and memory resource limits, and matching resource requests:
- pull-kubernetes-bazel-build

These jobs run on (google.com only) k8s-prow-build, so @spiffxp has provided the following guess:
- suggest 4 cpu, slightly above 34 Gi (36?) mem

General steps to follow:
- update the job definitions in [/config/jobs](/config/jobs) to have matching CPU and memory limits and requests
  - e.g. ([ci-kubernetes-e2e-gci-gce has a `resources:` field with matching entries](https://github.com/kubernetes/test-infra/blob/2eac54f721ed58479a3126e4f9ca5cbfcc73821b/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L357-L394))
- open a pull request, include a link to this issue and cc `@kubernetes/ci-signal` in the description
- keep an eye on the jobs for the next few days, and if they start failing more than usual, open followup pull requests to raise resources
  - can look at recent prow.k8s.io runs (e.g. https://prow.k8s.io/?job=ci-kubernetes-e2e-gci-gce)
  - can look at job history (e.g. https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce)
  - can look at testgrid dashboards (e.g. https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default)
- after the job has remained stable for a few days, declare victory

/sig testing
/sig release
/area jobs
/area release-eng

**Comment by ZhiFeng1993** [comment]
@spiffxp  may I ask how did you make a guess for jobs running in `k8s-prow-build`? We don't have any external dashboard as `k8s-prow-build-infra`, right? Did you check on the Google cluster?

**Comment by spiffxp** [comment]
Correct, k8s-prow-builds is google.com only.  I looked at a similar dashboard, not identical.

**Comment by spiffxp** [comment]
/remove-help
as @ZhiFeng1993 has this

**Comment by ZhiFeng1993** [comment]
https://prow.k8s.io/?job=pull-kubernetes-bazel-build

**Comment by ZhiFeng1993** [comment]
so far so good.

**Comment by ZhiFeng1993** [comment]
/close

I think it's safe to close this one. cc. @RobertKielty

**Comment by spiffxp** [comment]
/close
Thanks @ZhiFeng1993 !
