### ISSUE TITLE
Make critical jobs Guaranteed Pod QOS: pull-kubernetes-integration

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#18593]
**What should be cleaned up or changed**:

This is part of https://github.com/kubernetes/test-infra/issues/18530

The following jobs should be Guaranteed Pod QOS, meaning they should have CPU and memory resource limits, and matching resource requests:
- pull-kubernetes-integration

These jobs run on (google.com only) k8s-prow-build, so @spiffxp has provided the following guess:
- suggest 7 cpu, slightly above 14 Gi (15?) mem

General steps to follow:
- update the job definitions in [/config/jobs](/config/jobs) to have matching CPU and memory limits and requests
  - e.g. ([ci-kubernetes-e2e-gci-gce has a `resources:` field with matching entries](https://github.com/kubernetes/test-infra/blob/2eac54f721ed58479a3126e4f9ca5cbfcc73821b/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L357-L394))
- open a pull request, include a link to this issue and cc `@kubernetes/ci-signal` in the description
- keep an eye on the jobs for the next few days, and if they start failing more than usual, open followup pull requests to raise resources
  - can look at recent prow.k8s.io runs (e.g. https://prow.k8s.io/?job=ci-kubernetes-e2e-gci-gce)
  - can look at job history (e.g. https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce)
  - can look at testgrid dashboards (e.g. https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default)
- after the job has remained stable for a few days, declare victory

/sig testing
/sig release
/area jobs
/area release-eng

**Comment by tpepper** [comment]
"integration-master" in `config/jobs/kubernetes/sig-testing/integration.yaml` from sig-release-master-blocking has 6 cpu and 20Gi mem and appears to be flaking with random-ish things not running, so I wonder if 7 cpu and 15Gi mem will suffice.  But let's see.

**Comment by spiffxp** [comment]
/remove-help
since @tpepper has it

**Comment by spiffxp** [comment]
/reopen
Holding open for soak time

**Comment by RobertKielty** [comment]
@hasheddan @spiffxp @tpepper 

It was difficult for me to gather a behavior change for better or worse here. 

Will close for now reopen if needed

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&graph-metrics=test-duration-minutes&width=3

/close
