### ISSUE TITLE
 ci-kubernetes-gce-conformance-latest unable to dump cluster logs because remote dir does not exist

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/test-infra#18647]
**What happened**:

`ci-kubernetes-gce-conformance-latest` failed on `DumpClusterLogs` because of the following:

```
I0804 17:37:49.388] Will upload results to gs://kubernetes-jenkins/logs using prow-build@k8s-infra-prow-build.iam.gserviceaccount.com
I0804 17:37:49.388] Upload result and artifacts...
I0804 17:37:49.388] Gubernator results at https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1290676129757138944
I0804 17:37:49.389] Call:  gsutil ls gs://kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1290676129757138944/artifacts
W0804 17:37:50.567] CommandException: One or more URLs matched no objects.
E0804 17:37:50.878] Command failed
I0804 17:37:50.878] process 14425 exited with code 1 after 0.0m
W0804 17:37:50.878] Remote dir gs://kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1290676129757138944/artifacts not exist yet
I0804 17:37:50.879] Call:  gsutil -m -q -o GSUtil:use_magicfile=True cp -r -c -z log,txt,xml /workspace/_artifacts gs://kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1290676129757138944/artifacts
I0804 17:38:06.229] process 14568 exited with code 0 after 0.3m
I0804 17:38:06.229] Call:  git rev-parse HEAD
W0804 17:38:06.233] fatal: not a git repository (or any of the parent directories): .git
E0804 17:38:06.233] Command failed
```

**What you expected to happen**:

Job to be able so successfully dump cluster logs.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1290676129757138944

**Anything else we need to know?**:

While this failure doesn't really reduce signal, it does cause a release blocking job to fail.

**Comment by hasheddan** [comment]
/cc @amwat 

Thought you might have some insight on this.

**Comment by amwat** [comment]
I think those failures have always been there (even when the jobs pass): e.g: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1290630579355652104

The only new error I see is a gcloud logging internal error: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1290676129757138944#1:build-log.txt%3A12703

let's monitor https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%20master to see if it might be a flake (I see an active 11.50 ) run going on.

**Comment by amwat** [comment]
The latest run seems to have passed: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1290721680875851776
