### ISSUE TITLE
release-blocking jobs must run in dedicated cluster: periodic-kubernetes-bazel-test

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#18652]
Part of https://github.com/kubernetes/test-infra/issues/18549

k8s-infra-prow-build doesn't have RBE, so this job needs to be configured not to use RBE (I proved this works and 
determined the resource limits that should be used in https://github.com/kubernetes/test-infra/pull/18607)

Per https://github.com/kubernetes/test-infra/pull/18613#issuecomment-668178288 it is important we keep some variant of "bazel test" running periodically in the k8s-prow-builds cluster

So, per https://github.com/kubernetes/test-infra/pull/18613#issuecomment-668703640 I suggested we rename jobs:
>- swap the names of the bazel-test jobs such that
>   - periodic-kubernetes-bazel-test-canary = the job that runs on k8s-prow-builds, uses RBE, and is on sig-testing-canaries dashboard
>   - periodic-kubernetes-bazel-test-master = the job that runs on k8s-infra-prow-build and is release-blocking

/sig testing
/sig release
/wg k8s-infra
/area jobs

/assign @ameukam 
assigning since @ameukam started down this path with https://github.com/kubernetes/test-infra/pull/18613

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/18613 landed 2020-08-05 ~5pm PT
![Screen Shot 2020-08-08 at 1 18 02 PM](https://user-images.githubusercontent.com/49258/89719093-98707b00-d979-11ea-9f2e-5be7ed344c03.png)

It's unclear how much compute the RBE variant of the job ended up consuming, but it looks like we run slower.  This is still well within release-blocking bounds, but good to know.

I missed that we changed the interval when we made this change, we should change that back.  And the release-branch variants need to be changed over as well.

**Comment by ameukam** [comment]
It's unclear to me what's the correct value to set for the interval of the release-branch variants. Is it still necessary to make this change?

**Comment by spiffxp** [comment]
>It's unclear to me what's the correct value to set for the interval of the release-branch variants. Is it still necessary to make this change?

Both jobs have a `fork-per-release-periodic-interval: 6h` annotation set, I think their intervals should be left as-is.

**Comment by spiffxp** [comment]
What needs to be done for the release-branch variants is removal of the `--config=remote` and `--remote_instance_name=...` flags so that their `args` look like the `args` of `periodic-kubernetes-bazel-test-master`

**Comment by spiffxp** [comment]
So right after https://github.com/kubernetes/test-infra/pull/18997 merged, release-1.18 thru release-1.16 versions of this job all started failing with
```
FAILED: //pkg/kubelet/oom:go_default_test (Summary)
      /bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/testlogs/pkg/kubelet/oom/go_default_test/test.log
      /bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/testlogs/pkg/kubelet/oom/go_default_test/test_attempts/attempt_1.log
      /bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/testlogs/pkg/kubelet/oom/go_default_test/test_attempts/attempt_2.log
INFO: From Testing //pkg/kubelet/oom:go_default_test:
==================== Test output for //pkg/kubelet/oom:go_default_test:
=== RUN   TestStartingWatcher
--- FAIL: TestStartingWatcher (0.00s)
    oom_watcher_linux_test.go:48: 
        	Error Trace:	oom_watcher_linux_test.go:48
        	Error:      	Received unexpected error:
        	            	open /dev/kmsg: no such file or directory
        	Test:       	TestStartingWatcher
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10c0bd5]
goroutine 20 [running]:
testing.tRunner.func1(0xc0001c2100)
	GOROOT/src/testing/testing.go:874 +0x69f
panic(0x11b04e0, 0x1b0f170)
	GOROOT/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/pkg/kubelet/oom.TestStartingWatcher(0xc0001c2100)
	pkg/kubelet/oom/oom_watcher_linux_test.go:49 +0x135
testing.tRunner(0xc0001c2100, 0x12eebf0)
	GOROOT/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:960 +0x652
================================================================================
```

The release-1.19 and main branches are fine.  Wonder if we need to cherry-pick something back?

**Comment by spiffxp** [comment]
In order to get the following back to passing:
- https://testgrid.k8s.io/sig-release-1.18-blocking#bazel-test-1.18
- https://testgrid.k8s.io/sig-release-1.17-blocking#bazel-test-1.17
- https://testgrid.k8s.io/sig-release-1.16-blocking#bazel-test-1.16

Opened cherrypicks for https://github.com/kubernetes/kubernetes/pull/90927
- releease-1.16: https://github.com/kubernetes/kubernetes/pull/94323
- releease-1.17: https://github.com/kubernetes/kubernetes/pull/94326
- releease-1.18: https://github.com/kubernetes/kubernetes/pull/94322

Opened cherrypicks for https://github.com/kubernetes/kubernetes/pull/86232
- release-1.16: https://github.com/kubernetes/kubernetes/pull/94324
- release-1.17: https://github.com/kubernetes/kubernetes/pull/94325

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-release-1.16-blocking#bazel-test-1.16 - cherry-picks for this branch have merged, all tests are green; the tab is still going to appear red / "failing" in summary until enough runs have happened to age out the oom_watcher test as stale (should be 10 IIRC)

**Comment by ameukam** [comment]
@spiffxp Is there still something to do here? 
Also Thanks for the help!

**Comment by spiffxp** [comment]
/close
Yeah this is done
