### ISSUE TITLE
go get failing with "multiple-value uuid.NewV1() in single-value context"

### ISSUE THREAD

**Issue by arturenault** [kubernetes/test-infra#18656]
**What happened**:
Trying to install kubetest with go get fails with the following error:
```
# k8s.io/test-infra/kubetest
/usr/local/google/home/arenault/knative-workspace/src/k8s.io/test-infra/kubetest/aksengine.go:315:46: multiple-value uuid.NewV1() in single-value context
/usr/local/google/home/arenault/knative-workspace/src/k8s.io/test-infra/kubetest/aksengine_helpers.go:334:67: multiple-value uuid.NewV1() in single-value context
```

**What you expected to happen**:
Successful installation of the package.

**How to reproduce it (as minimally and precisely as possible)**:
Navigate to directory outside of GOPATH (e.g. /tmp) and run `go get k8s.io/test-infra/kubetest`.

**Comment by arturenault** [comment]
Interestingly I was able to unblock myself by navigating to repo root (since go get had already cloned it) and running `go install ./kubetest` Something must be different in the go get environment that causes this issue... Can anyone else repro?

**Comment by BenTheElder** [comment]
kubetest already documents that you must do the clone and go install route.

The reason is that this repo uses `replace` in go.mod which is not respected during go get.

**Comment by BenTheElder** [comment]
kubetest2 will replace kubetest in the near future and will be go gettable.

https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md

**Comment by arturenault** [comment]
Thanks, I appreciate the explanation. Will keep an eye out for kubetest2.
