### ISSUE TITLE
[kubetest][gke] Timeout ignored in some functions

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/test-infra#18669]
In few places there are direct usages of `exec.Command`, instead of wrapping it in `control.FinishRunning`. Effectively timeout is ignored for those commands. We should verify if this is by design, and fix it if needed.

This can prevent releasing Boskos resources, as Boskos resource release is happening outside outside `run` function in `main`. However, if whole kubetest process will be removed, it can lock on resource.

/sig scalability

**Comment by BenTheElder** [comment]
cc @amwat

**Comment by amwat** [comment]
Do you have any link to a failure by any chance?
We use [reaper and janitor](https://github.com/kubernetes-sigs/boskos#other-components) in CI so as long as the [heartbeating](https://github.com/kubernetes/test-infra/blob/c1964ea60f1f7392aa01a0d30d4d4e65afdb1791/kubetest/main.go#L753-L759) stops when the process is killed the resources will be cleaned up.

**Comment by jprzychodzen** [comment]
Actually, this issue was discovered when searching for a resolution for some other, similar problem related to rescheduled pods in cluster. So it's more about increasing resilience, than having a particular error happened because of this code.

Regarding Reaper and Janitor - Yes, they kicked in, however they add extra ~30 minutes. The resource we are using is spare and we want to make a full utilization of it.

**Comment by amwat** [comment]
Yeah, makes sense. We should definitely track down such instances. 
/assign
