### ISSUE TITLE
establish image policy for GPU

### ISSUE THREAD

**Issue by vpickard** [kubernetes/test-infra#18702]
**What should be cleaned up or changed**:
We need to figure out and understand the image policy for GPU tests. It would be great to have someone familiar with this image to help us figure that out.

**Provide any links for context**:

Reference https://github.com/kubernetes/test-infra/pull/11876.

**Comment by vpickard** [comment]
@spiffxp @SergeyKanzhelev  Thanks for the pointer. Creating this issue so we don't forget about GPU images.

**Comment by bobbypage** [comment]
Fixed in https://github.com/kubernetes/kubernetes/issues/101558
