### ISSUE TITLE
Mark superseded comments as outdated

### ISSUE THREAD

**Issue by sftim** [kubernetes/test-infra#18757]
**What would you like to be added**:

When Prow comments on a pull request with, for example, a test status, and that comment supersedes a previous comment, mark the previous comment as outdated (hiding it by default).

**Why is this needed**:
Some pull requests get a long history of GitHub comments showing failed tests, flakes, removal of LGTM, addition of LGTM, etc. It's good to keep that history but also the most recent failed tests are probably more useful to report than the previous ones.

**Alternatives**:
Use the GitHub Checks API to report status, and don't report it via PR comments.

**Comments**:

I couldn't see a previous similar request; if I missed one, my apologies.

/kind feature

**Comment by sftim** [comment]
Also see issue #17056

**Comment by alvaroaleman** [comment]
@sftim prow actually does edit the test status comment and possibly removes it if there are no failures anymore. If there is ever more than one test status comment, that's a bug. Could you show some examples of outdated comments?

**Comment by sftim** [comment]
Ah, OK. I hadn't noticed the deletions because they don't leave a trace. Now I know that if I see an outdated comment it's either a bug or Prow is about to tidy up.

/close
