### ISSUE TITLE
Recurring prow log errors "Failed to clean up repo"

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#18768]
**What happened**: istio prow generates lots of recurring errors with error:
```
jsonPayload: {
  component: "hook"   
  error: "unlinkat /tmp/git236299396/.git: directory not empty"   
  file: "prow/config/inrepoconfig.go:76"   
  func: "k8s.io/test-infra/prow/config.defaultProwYAMLGetter.func1"   
  level: "error"   
  msg: "Failed to clean up repo."   
  repo: "istio/istio"   
 }
```

**What you expected to happen**: no errors

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
Check https://pantheon.corp.google.com/logs/viewer?project=istio-testing&minLogLevel=0&expandAll=false&timestamp=2020-08-10T18%3A45%3A25.475000000Z&customFacets=jsonPayload.level%2CjsonPayload.component%2CjsonPayload.msg&limitCustomFacetWidth=true&interval=CUSTOM&resource=container%2Fcluster_name%2Fprow&scrollTimestamp=2020-08-10T18%3A40%3A36.000000000Z&pli=1&rapt=AEjHL4OIudnQvHfkwsjeHVKiuCNtyCK-tlShRt38O1NCSXeK1nyc4TYLdL8D7C7VIIxwkX4_JCEZzEoIjZvVAJUWcTgRZHSklw&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22prow%22%0Aresource.labels.zone%3D%22us-west1-a%22%0Aresource.labels.pod_id%3D%22hook-7f87496b48-qb29h%22%0Aresource.labels.project_id%3D%22istio-testing%22%0Aresource.labels.container_name%3D%22hook%22%0Aresource.labels.instance_id%3D%22509889749234183265%22%0Aresource.labels.namespace_id%3D%22default%22%0Atimestamp%3D%222020-08-10T18%3A40%3A36.000000000Z%22%0AinsertId%3D%2210x1srgg2bi8ijd%22&dateRangeStart=2020-08-07T18%3A41%3A18.000Z&dateRangeEnd=2020-08-10T18%3A41%3A18.000Z

**Anything else we need to know?**:
The error comes from https://github.com/kubernetes/test-infra/blob/7ada03969d444ea084935fd465e50605b45d9284/prow/config/inrepoconfig.go#L74, as a best effort cleanup, maybe this should just be a `debug` logging?

**Comment by matthyx** [comment]
I have left this issue open, let's see if the git gc was the culprit!

**Comment by matthyx** [comment]
@chaodaiG do you see any improvement?

**Comment by chaodaiG** [comment]
It had disappeared from istio prow log since last week, I think it's fixed. Thank you @matthyx 

/close
