### ISSUE TITLE
Prow appears to merge before passing tests due to a Crier and Tide race 

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#18782]
I think there's a race condition where Crier marks GitHub's status as Mergeable at the same time that Tide tries to merge it.
If Tide wins, then Crier won't update a merged PR and it _appears_ that a PR has merged before all the GitHub statuses are green.

Note that this does not result in Tide merging a PR that shouldn't be merged; it seems to only affect the status contexts that appear.

Examples:
https://github.com/kubernetes/website/pull/22643
https://github.com/kubernetes/test-infra/pull/17874

Related Issues:
https://github.com/kubernetes/test-infra/issues/16472

**Comment by alvaroaleman** [comment]
This isn't crier, this is the tide status controller which runs independently of the tide sync controller and might not update the tide status to green before a PR gets merged, ref: https://github.com/kubernetes/test-infra/issues/16472#issuecomment-640874553
