### ISSUE TITLE
Test reported as failed despite all subtests passing

### ISSUE THREAD

**Issue by spencer-p** [kubernetes/test-infra#18798]
**What happened**:

The [pull-kubernetes-verify test reported failure despite 37/37 tests passing](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93762/pull-kubernetes-verify/1293351247897694208).

**What you expected to happen**:

It looks like the test should be marked as passing.

**How to reproduce it (as minimally and precisely as possible)**:

Perhaps by re-running the test on 9a076ff.

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93762/pull-kubernetes-verify/1293351247897694208

https://github.com/kubernetes/kubernetes/pull/93762

**Comment by BenTheElder** [comment]
> {"component":"entrypoint","file":"prow/entrypoint/run.go:247","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process gracefully exited before 15m0s grace period","severity":"error","time":"2020-08-12T03:21:08Z"}

This message in the logs indicates that the job actually timed out before completing, and exited due to the signal from the timeout.

Even if the test cases passed, there is cleanup etc. at the end, timing out is a failure.
