### ISSUE TITLE
Use different field names for the slack mergewarning config

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#18801]
**What should be cleaned up or changed**:
https://github.com/kubernetes/test-infra/blob/711fa0e9c594b8acd29cf730780d84beecc044f8/prow/plugins/config.go#L507-L516

- Instead of `WhiteList`, how about `ExemptUsers`
- Instead of `BranchWhiteList`, how about `ExemptBranches`

This will require code changes and config changes.  Suggest we deprecate the old fields and remove them at some later date, with an announcement in ANNOUNCEMENTS.md

**Provide any links for context**:

/wg naming
/help
/area prow

**Comment by BenTheElder** [comment]
/good-first-issue

To accomplish this: 
- PR # 1 ...
  - add the new fields adjacent to the old ones. 
  - Combine the contents into the new field at config loading time
  - update code reading these fields in memory to use the new fields
  - Add a note to the announcements about migrating
- PR # 2 ...
   - after prow.k8s.io has deployed your change (upgrades are roughly once a day on business days), switch our config to use the new fields
- PR # 3 ...
  - after some time we can circle back and delete the old fields

**Comment by spiffxp** [comment]
I missed #18995 and https://github.com/kubernetes/test-infra/pull/19000 ended up taking care of "PR # 2"

**Comment by spiffxp** [comment]
@cjwagner @alvaroaleman what sort of deadline seems reasonable for removing the old fields here? I noticed we didn't put an explicit date in ANNOUNCEMENTS.md, seems like 1-2 months is common

**Comment by cjwagner** [comment]
I think I usually do 3 months, but 1-2 months is probably ok too 🤷 
Making the deadline shorter increases the chance of breaking someone, but this would be a pretty easy fix and the failure mode of ignoring the exemption lists is increased security, not reduced.

**Comment by ajaygm** [comment]
Can someone please validate my understanding...
- Now's a good time to do PR # 3 mentioned at https://github.com/kubernetes/test-infra/issues/18801#issuecomment-673269771
- Need to remove all references / validations on old fields in PR #18946
- No changes from PR #19000 
- Still a "good first issue"

**Comment by alvaroaleman** [comment]
@ajaygm before we can remove anything, we need to set a deprecation timeline in prow/announcements.md

**Comment by justaugustus** [comment]
@alvaroaleman -- What are next steps now that the announcement has merged?

**Comment by alvaroaleman** [comment]
> @alvaroaleman -- What are next steps now that the announcement has merged?

Remove the old config options in January, as mentioned in the announcement

**Comment by ajaygm** [comment]
Stuff mentioned in https://github.com/kubernetes/test-infra/issues/18801#issuecomment-725797614 is what needs to be done and committed in Jan 2021.
@alvaroaleman can you confirm if that comment defines the work to be done correctly?

**Comment by alvaroaleman** [comment]
What needs to be done in Jan is to remove the deprecated options and everything that references it
