### ISSUE TITLE
Unable to clone submodules when using a cookiefile

### ISSUE THREAD

**Issue by MaxRenaud** [kubernetes/test-infra#18802]
**What happened**:
When cloning a repository with submodules, git fails to pull from the submodule repository since the "git config http.cookiefile " directive appears to only apply to the main repo and "git submodule update --init --recursive" ignores it

**What you expected to happen**:
I expect the git submodule to use the specified cookiefile

**How to reproduce it (as minimally and precisely as possible)**:
I am unable to post the full config here but this is how it can be reproduced:
- Create git repository "A"
- Create git repository "B"
- Make "B" a submodule of "A"
- Ensure that Both "A" and "B" require cookie authentication and use the same cookie
- Use Prow to clone "A" with a specified cookiefile. "A" will check out but "B" will fail since the cookie file isn't passed on.
$ git submodule update --init --recursive
Submodule 'B' (https://xxx.com/B) registered for path 'B'
Cloning into '/home/prow/go/src/xxx/A/B'...
fatal: could not read Username for 'https://xxx': No such device or address
fatal: clone of 'https://xxx/B' into submodule path '/home/prow/go/src/xxx/A/B' failed
Failed to clone 'B'. Retry scheduled

**Please provide links to example occurrences, if any**:
None that I can share.
If you are a Google employee looking at this, please contact me and I can show an internal example.

**Anything else we need to know?**:
The container was instantiated by Prow. Both repositories are on the same [Git on Borg](https://opensource.google/docs/glossary/#gitonborg). I'm able to clone both repos individually so it's not a permission/ACL issue.

**Comment by fejta** [comment]
Here is where we configure the cookiefile:

https://github.com/kubernetes/test-infra/blob/738aa93ddd5d8a03efe3d89cdde26ccaa303dece/prow/pod-utils/clone/clone.go#L183-L185

Here is where we init the submodule:

https://github.com/kubernetes/test-infra/blob/738aa93ddd5d8a03efe3d89cdde26ccaa303dece/prow/pod-utils/clone/clone.go#L281

One idea would change the cookiefile to set either `--global` or `--system`

Another idea is to mark these as [active](https://git-scm.com/docs/gitsubmodules#_active_submodules) and enable [worktreeConfig](https://git-scm.com/docs/git-worktree#_configuration_file)

Do we need to provide this as a knob? What side effects would there be to just always setting `--global`?
