### ISSUE TITLE
testgrid tab groups for sig-node informing/blocking jobs

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/test-infra#18826]
`Problem we are solving: if a person is not a part of SIG node - can I ask quickly whether things are OK now or not?`

**What should be cleaned up or changed**:
Add a testgrid tab-group config consisting of existing jobs used for determining whether sig-node tests are in good condition.

We want two new top-level testgrid tab groups:
 1. one for informing (maybe pull/pr/presubmits?)
 2. one to match blocking (ci/periodics?)
   - master
   - appropriate release versioned

Here are some examples from existing testgrid groups,

for pr presubmits: 
https://testgrid.k8s.io/presubmits-kubernetes-nonblocking

for blocking:
https://testgrid.k8s.io/presubmits-kubernetes-blocking
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-node-e2e

--
These are the same job showing up multiple test groups, as an example of that this can be done
https://testgrid.k8s.io/sig-release-master-blocking
https://testgrid.k8s.io/sig-release-master-blocking#node-kubelet-master
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-master

--
https://testgrid.k8s.io/sig-release-1.19-blocking
https://testgrid.k8s.io/sig-release-1.19-blocking#node-kubelet-1.19
+ other versioned releases

**Provide any links for context**:
https://docs.google.com/document/d/1fb-ugvgdSVIkkuJ388_nhp2pBTy_4HEVg5848Xy7n5U/edit#
Go to 2020-08-10 meeting notes, look for
`Problem we are solving: if a person is not a part of SIG node - can I ask quickly whether things are OK now or not?`

/cc @vpickard @SergeyKanzhelev @dims

**Comment by alejandrox1** [comment]
> We want two new top-level testgrid tab groups:
>
> 1. one for informing (maybe pull/pr/presubmits?)
> 2. one to match blocking (ci/periodics?)

I think it would be better to organize jobs by whether they should be used to gauge the quality of kubernetes/kubelet, i.e., a blocking job would mean that the job is maintained and if a failure occurs there then something must be fixed.
For anon-blocking job, it could be that it is a "work in progress" and a job failure (or a test failure) does not reflect on the quality of kubernetes/kubelet/etc.

**Comment by MHBauer** [comment]
I think I confused the issue by mentioning periodics and pulls. I should not have done that.

I agree with the "quality" metric, but I'm not sure we can successfully define it. 

https://github.com/kubernetes/test-infra/pull/18831#issuecomment-674221926 might have a more concrete proposal of the process we want to follow.

**Comment by MHBauer** [comment]
Okay, #18831 ended by creating two new tabs
 - a [release-blocking](https://testgrid.k8s.io/sig-node-release-blocking#Summary) group to copy the existing release-blocking jobs
 - a [critical](https://testgrid.k8s.io/sig-node-critical) importance group, with some minimal config. Two jobs from other tabs as an example of how to add.

What else to add to critical? 

Seems we also want a grab-bag of `WIP -> blocking`, but it would be best to be concrete as far as what jobs to include.

Node also has some responsibility for a pull job for merge-blocking. I don't want to include that in release blocking, because it would often be failing due to PRs.

**Comment by SergeyKanzhelev** [comment]
> What else to add to critical?
> 
> Seems we also want a grab-bag of `WIP -> blocking`, but it would be best to be concrete as far as what jobs to include.

On the meeting we discussed this question. There were a few suggestions - based on people commitment to maintain, based on stability. But in the end we agreed that the approach should be to include all the tests that are well understood and testing features meaningful for large population of users. Long term goal is to have all tests target to be in "critical" tab. But they can start with alpha tab or feature tab.

Now how to approach it in real life. There are some tabs that probably can be taken "as is" to critical. And I feel they are not controversial. Like "https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-master". I wonder if this specific tab needs a better description on the purpose of the tab and which tests should be added there. 

TopologyManager and CPU Manager were discussed and it seems that they might be used by smaller population of users. But the discussion during the meeting was that it is a feature we have in k8s and need to either care about it as critical or not have the feature. So agreement was it does fit the bar of being in critical dashboard.

What do you think?

**Comment by ehashman** [comment]
@MHBauer what's going on with this issue? Would you like to do the work or are you interested in us finding an assignee?
