### ISSUE TITLE
Remove preset-service-account label for jobs

### ISSUE THREAD

**Issue by anthonyrtong** [kubernetes/test-infra#18867]
**What should be cleaned up or changed**:

Right now, we use set the **preset-service-account:** "true" in order to provide credentials for the job.  It would be safer and better practice to not use the infrastructure credentials for jobs and instead use a GKE workload identity and other valid credentials for RBE authentication.

We are using this in a majority of test-infra jobs.  For example: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml

**Comment by BenTheElder** [comment]
This won't work for some e2e tests that actually consume keys.
