### ISSUE TITLE
e2e testing for the charts repo

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#1887]
### Problem

Charts can break because of changes to their spec, or due to changes to upstream k8s.
Example issues in the past: 
- alpha vs. beta annotations for PVCs: https://github.com/kubernetes/charts/issues/116
- Set imagePullPolicy in init-containers in charts: https://github.com/kubernetes/charts/issues/307

### Proposed Solution 

* System tests for each chart's correctness (to be written by chart authors). example: https://github.com/kubernetes/charts/pull/609
* Running these chart-level system tests against each change in kubernetes/kubernetes.

This is the basic flow for running tests on [each chart](https://github.com/kubernetes/charts/tree/master/stable) (there are around 50 now):

1. `helm install --name=<release-name> --wait .`
1.  `helm test <release-name>`
1. test pod is launched and runs tests
1. test pod may output [TAP](https://testanything.org/), or simply an exit code
    * We will have a way to differentiate between tests which output TAP, and those which fail with an error code.
1. We parse the output and display the results in the testgrid while also filing flakes in the repository

cc @spxtr @michelleN

**Comment by spxtr** [comment]
It sounds like you need a job that is running continuously that uses bootstrap to checkout the charts repo, and then

1. uses [kubetest](https://github.com/kubernetes/test-infra/tree/master/kubetest) (formerly hack/e2e.go) to turn up a k8s cluster at the latest version,
1. runs the tests from the charts repo,
1. tears down the cluster,
1. places JUnit artifacts in a place that bootstrap picks up.

Fortunately, we already have the cluster turnup and teardown logic handled. This might be as simple as adding charts-testing-capability to kubetest, in which case steps 1-3 can be done in one go.

You'll want to produce JUnit output since all of our test infra understands it.

The job can run on Jenkins for now and migrate with the rest of the e2e jobs.

cc @krzyzacy @fejta

**Comment by foxish** [comment]
@spxtr It sounds like this will work well for us. I can take care of transforming the TAP output/error codes into JUnit output. 
Can you elaborate a bit more on "adding charts-testing-capability to kubetest"? Will we need to introduce a new component there?

**Comment by spxtr** [comment]
In kubetest we have a [deployer](https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L391) interface that lets us deploy using kops or kubernetes anywhere. Possibly we should add a `tester` interface or something like that that specify how to test.

**Comment by foxish** [comment]
I just tried using the --repo flag with bootstrap. It appears that bootstrap checks the repository out to my local file system, and then launches a docker container "kubekins-e2e" that actually runs the kubetest binary. Do I need to do something special to make the locally checked out copy of the repo accessible within the docker container running kubetest? It is not very evident to me how I can use the two together.

**Comment by spxtr** [comment]
cc @fejta @krzyzacy

**Comment by foxish** [comment]
Part of this item is complete. The job is ci-kubernetes-charts-gce and it can be found at: https://k8s-testgrid.appspot.com/kubernetes-apps

**Comment by foxish** [comment]
The script has been merged. However, I don't have sufficient visibility to know what it's doing under the hood, within kubetest. The test passes (https://k8s-testgrid.appspot.com/kubernetes-apps) but the junit output that I'm generating is not being parsed. Can you help @spxtr @krzyzacy @fejta

**Comment by foxish** [comment]
The tests are now being run: 
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-charts-gce/2811
* Testgrid: https://k8s-testgrid.appspot.com/kubernetes-apps#charts-gce

Closing this issue
