### ISSUE TITLE
Artifacts link supports for s3/aws

### ISSUE THREAD

**Issue by hktime** [kubernetes/test-infra#18900]
**What would you like to be added**:
We have been using prow with s3 for a few months, everything seems nice. But the artifacts link in the deck spyglass page appears to only support for gcswebPrefix. Does this link supports for s3.

![image](https://user-images.githubusercontent.com/11371168/90587261-89a48680-e20b-11ea-9f02-01c43f410b5f.png)

**Why is this needed**:
S3 support in prow should be complete.

**Comment by alvaroaleman** [comment]
This should work by setting `gcs_browser_prefix` for spyglass as described here: https://github.com/kubernetes/test-infra/blob/859d15fc4364265500611c3c137d6dd610dafbcf/prow/spyglass/README.md#L40

**Comment by hktime** [comment]
Thanks a lot. Maybe what I said is not very clear. 
I have set the gcs_browser_prefix options, so this link is visible in the spyglass page. 
But I am using s3 instead of gcs, gcs browser is unavailable. Clicking this link only get a "404 not found" response.
What I'm talking about is gcsweb should support all kinds of storage, as a very useful tool.

**Comment by midnightconman** [comment]
I hate to hop on a closed issue, but does anyone use the artifacts option with aws and s3? I looked around for some opensource s3 "directory style" viewers and I couldn't find anything.

**Comment by Rajalakshmi-Girish** [comment]
@hktime were you able to handle artifacts from your s3 storage?
@alvaroaleman Ideally, a proper browser prefix to s3, assigned to `gcs_browser_prefix` should work. Can you please confirm?
