### ISSUE TITLE
multiple prowjobs failed with no status text or comment

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#18918]
**What happened**:

This:
<img width="820" alt="Screen Shot 2020-08-19 at 9 30 39 PM" src="https://user-images.githubusercontent.com/917931/90717026-4e35a680-e263-11ea-936c-a8b75d16d2b9.png">

- no status link or message
- no failure comment

Unclear why these failed.

I also can't tell if I get to the PR history page via another job https://prow.k8s.io/pr-history/?org=kubernetes-sigs&repo=kind&pr=1796

**What you expected to happen**:

I should be able to see why a test failed.

**How to reproduce it (as minimally and precisely as possible)**:

Unclear

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/pr-history/?org=kubernetes-sigs&repo=kind&pr=1796

**Anything else we need to know?**:

/area prow

**Comment by BenTheElder** [comment]
/assign @cjwagner 
possibly a recent regression? I have seen plenty of scheduling timeouts etc. recently but not something like this until today.

**Comment by alvaroaleman** [comment]
The jobs are all in `aborted` state :thinking:

**Comment by BenTheElder** [comment]
Possibly because I just merged the PR? (We didn't need the results anyhow, it was a docs only change, and PR volume is low enough that tide isn't a big concern).

When I opened the issue none of the job pages had any useful details either.

**Comment by cjwagner** [comment]
Merging the PR caused the remaining jobs to be aborted: https://github.com/kubernetes/test-infra/blob/2efbce017d1a6413667320cd8f979fd40b8ac7b5/prow/plugins/trigger/pull-request.go#L144-L145

It is strange that the pods did eventually run and fail even though the description is "Job triggered" which suggests plank never reached the point of creating a pod. Perhaps we failed to update the PJ after creating the pod, but I don't see any errors from plank in the past 24hrs, nor do I see any errors related to that PR. 
I'm not sure what caused the behavior you saw before merging; it is a bit difficult to debug now given that the jobs were aborted by merging and the logs show nothing wrong. If you see another occurrence of this please let me know.

**Comment by BenTheElder** [comment]
wish we had a prow "audit log" for API calls.

will keep an eye out.
