### ISSUE TITLE
spyglass: Include junit's classname in UI.

### ISSUE THREAD

**Issue by EricEdens** [kubernetes/test-infra#18929]
(I'm happy to help with implementation; this request is to discuss whether the feature is desirable, and if so, how it should look when it's finished.)

**Problem**:
spyglass displays the test's name (via junit), but doesn't include its class. Sometimes the same test name is used in multiple classes.

**What would you like to be added**:
The ability to differentiate between tests with the same name. A couple of ideas:
1. In the UI, prepend the class name to the test name.
   - This could happen always, or only when there's a collision.
2. Group results by class name

**Why is this needed**:
The current workaround is to visually inspect the junit XML files.

**Comment by chizhg** [comment]
Big +1 to this.
We also have tests that have the same name but are under different packages, including the class name in the UI would definitely help to differentiate them.

/area prow/spyglass
