### ISSUE TITLE
go: error loading module requirements

### ISSUE THREAD

**Issue by zyc-ai** [kubernetes/test-infra#18959]
**What happened**:

```
go: error loading module requirements
```

**What you expected to happen**:

work

**How to reproduce it (as minimally and precisely as possible)**:

```
go get -u k8s.io/test-infra/prow/cmd/tackle
```

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by fejta** [comment]
Remove the `-u`, kubernetes modules have issues auto updating.

**Comment by zyc-ai** [comment]
> Remove the `-u`, kubernetes modules have issues auto updating.

It's now `cannot find package "gomodules.xyz/jsonpatch/v2"`
