### ISSUE TITLE
Move heapster/cadvisor resources into their own project

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#190]
I believe these have some special vms, etc. Lets move them to their own project.

**Comment by fejta** [comment]
But first we need to address https://github.com/kubernetes/test-infra/issues/189

**Comment by fejta** [comment]
Jeff what's left to do here?

**Comment by ixdy** [comment]
Someone needs to look at the tests and see if they are creating any resources in GCP (and if so, make sure they're using their own projects).

**Comment by ixdy** [comment]
Yeah, this is still not fixed. We have special snowflake `e2e-cadvisor` VMs in both `kubernetes-jenkins` and `kubernetes-jenkins-pull` which probably need to be migrated to their own projects.
cc @timstclair @vishh

**Comment by fejta** [comment]
/assign @timstclair @vishh @ixdy 

Will the three of be able to resolve this during the 1.7 timeframe?

Otherwise I woud like to delete these VMs and jobs in July.

**Comment by fejta** [comment]
We should delete these VMs soon

**Comment by krzyzacy** [comment]
cc @dashpole cadvisor also still have a Jenkins VM, while we are going to kill Jenkins soon

**Comment by fejta** [comment]
Will delete these jobs as soon as we're out of 1.9 freeze

**Comment by BenTheElder** [comment]
re-ping @dashpole for cadvisor jobs deletion warning ^

**Comment by BenTheElder** [comment]
@dashpole and I discussed this today. I will assist him with looking at migrating cadvisor to Prow soonish, nobody wants to run a jenkins cluster :+)
When we do we will see if it is possible to move the heapster jobs in the same fashion.

**Comment by krzyzacy** [comment]
kubernetes-jenkins is wiped and I'll close this

**Comment by BenTheElder** [comment]
Cadvisor at least definitely has their resources in their own project now
as well (@dashpole owns this)
