### ISSUE TITLE
status-reconciler gets confused when jobs for different branches have the same name

### ISSUE THREAD

**Issue by rmohr** [kubernetes/test-infra#19005]
**What happened**:

We had a job on master which was optional, non-reporting and alwaysrun. It also got forked to two release branches. Finally we made it required and reporting on master. This seemed to confuse status-reconciler. It was comparing the optional release-branch job with the job on master. Therefore it always thought that the last saved state had the job as not required, since it compared the master-job with the release-job.

statusreconciler recreated the jobs on every reconcile loop again and again.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

I am not entirely sure in which direction this should be solved. Discussing this with @alvaroaleman and @stevekuznetsov, they tend to think that jobs should just never have the same name. On the other hand kubernetes/sig-release uses this right now, and it seems to be the only way to keep consistent status context namings across branches, since @alvaroaleman meant that duplicating status contexts is prohibited now.

**Comment by alvaroaleman** [comment]
>  and it seems to be the only way to keep consistent status context namings across branches, since @alvaroaleman meant that duplicating status contexts is prohibited now.

No. The only thing that is enforced is that there is at most one job per org/repo/branch for a given status context

**Comment by rmohr** [comment]
> No. The only thing that is enforced is that there is at most one job per org/repo/branch for a given status context

Ah fine, then just going with unique names and explicitly setting the contexts sounds like the way to go.
