### ISSUE TITLE
Bugs in Crier gcsk8sreporter result in stuck pods

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#19015]
**What happened**:

If for whatever reason the Crier gcsk8sreporter  doesn't remove its finalizer but reports success, we end up with stuck pods because nothing ever cleans up that finalizer.

While ending up in this situation in the first place is a bug, we should handle this case better by making something else (sinker?) detect this condition, log an error and clean up.

/area prow
/area prow/crier

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/pull/18952 for the PR that introduced the finalizer
