### ISSUE TITLE
kubetest mishandles SIGINT

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#1906]
I start to run e2e tests:
```console
$ $GOPATH/bin/kubetest --test -v --test_args=--ginkgo.focus=.*Rescheduler.*
```

I then `^C` to cancel running tests.
`kubetest` exits and returns me to the console, but `hack/ginkgo-e2e.sh` and subprocesses (like `ginkgo`) continue to run.

The same issue exists if I interrupt `kubetest --up`.

**Comment by ixdy** [comment]
maybe related to #39041

**Comment by fejta** [comment]
This still doesn't work

**Comment by cpanato** [comment]
I can try this one 😄

**Comment by ixdy** [comment]
any progress on this?

**Comment by cpanato** [comment]
@ixdy I did not have time and it gets lost in my items. However, I can come back to this. I have some questions regarding kubetest, who is the best contact to clarify?

i apologize for this taking too much time

**Comment by cpanato** [comment]
almost there. fighting to spin the cluster in my local machine

**Comment by cpanato** [comment]
PR: https://github.com/kubernetes/test-infra/pull/7447
