### ISSUE TITLE
Migrate merge-blocking jobs to dedicated cluster: pull-kubernetes-bazel-test

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#19070]
**What should be cleaned up or changed**:

This is part of #18550

To properly monitor the outcome of this, you should be a member of k8s-infra-prow-viewers@kubernetes.io.  PR yourself into https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml#L603-L628 if you're not a member.

Migrate pull-kubernetes-bazel-test to k8s-infra-prow-build by adding a `cluster: k8s-infra-prow-build` field to the job:
- Make sure any release-branch variants are also updated
- Reference this issue, but do not "fix" it; instead leave this open to monitor the behavior of the job before/after
- Here's an example PR that did this for pull-kubernetes-integration: https://github.com/kubernetes/test-infra/pull/18814

NOTE: migrating this job is not as straightforward as some of the other #18550 issues, because:
- other flags need to be removed to migrate it off of RBE
```
- --config=remote
- --remote_instance_name=projects/k8s-prow-builds/instances/default_instance
```
- its behavior off of RBE may be substantially different or consume more resources than with RBE (ref: https://docs.bazel.build/versions/master/remote-execution.html)

Once the PR has merged, note the date/time it merged.  This will allow you to compare before/after behavior.

Things to watch for the job
- https://prow.k8s.io/?job=pull-kubernetes-bazel-test
  - does the job start failing more often?
  - does the job start going into error state?
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-bazel-test&graph-metrics=test-duration-minutes
  - does the job duration look worse than before? spikier than before?
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-bazel-test
  - do more failures show up than before?
- https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-bazel-test
  - (can be used to answer some of the same questions as above)
- [metrics explorer: CPU limit utilization for `pull-kubernetes-bazel-test` for 6h](https://console.cloud.google.com/monitoring/metrics-explorer?project=k8s-infra-prow-build&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22kubernetes.io%2Fcontainer%2Fcpu%2Flimit_utilization%5C%22%20resource.type%3D%5C%22k8s_container%5C%22%20metadata.user_labels.%5C%22prow.k8s.io%2Fjob%5C%22%3Dmonitoring.regex.full_match(%5C%22pull-kubernetes-bazel-test%5C%22)%22,%22minAlignmentPeriod%22:%2260s%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22groupByFields%22:%5B%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%226h%22%7D%7D)
  - is the job wildly underutilizing its CPU limit? if so, perhaps tune down (if uncertain, post evidence in this issue and ask)
  - (it will probably be helpful to look at different time resolutions like 1h, 6h, 1d, 1w)
- [metrics explorer: Memory limit utilization for `pull-kubernetes-bazel-test` for 6h](https://console.cloud.google.com/monitoring/metrics-explorer?authuser=1&project=k8s-infra-prow-build&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22kubernetes.io%2Fcontainer%2Fmemory%2Flimit_utilization%5C%22%20resource.type%3D%5C%22k8s_container%5C%22%20metadata.user_labels.%5C%22prow.k8s.io%2Fjob%5C%22%3Dmonitoring.regex.full_match(%5C%22pull-kubernetes-bazel-test%5C%22)%22,%22minAlignmentPeriod%22:%2260s%22,%22unitOverride%22:%221%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22groupByFields%22:%5B%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%226h%22%7D%7D)
  - is the job wildly underutilizing its memory limit? if so, perhaps tune down (if uncertain, post evidence in this issue and ask)
  - (it will probably be helpful to look at different time resolutions like 1h, 6h, 1d, 1w)

Things to watch for the build cluster
- [prow-build dashboard 1w](https://console.cloud.google.com/monitoring/dashboards/custom/10925237040785467832?project=k8s-infra-prow-build&timeDomain=1w)
  - is the build cluster scaling as needed? (e.g. maybe it can't scale because we've hit some kind of quota)
  - (it will probably be helpful to look at different time resolutions like 1h, 6h, 1d, 1w)
- [prowjobs-experiment 1w](https://console.cloud.google.com/monitoring/dashboards/custom/10925237040785467832?project=k8s-infra-prow-build&timeDomain=1w)
  - (shows resource consumption of all job runs, pretty noisy but putting this here for completeness)

Keep this open for at least 24h of weekday PR traffic.  If everything continues to look good, then this can be closed.

/wg k8s-infra
/sig testing
/area jobs

**Comment by spiffxp** [comment]
/assign

Starting with a canary job to explore if/how different the presubmit runs off of RBE: https://github.com/kubernetes/test-infra/pull/19069

For the release-blocking / CI variant of this job, we found the job took longer to run: https://github.com/kubernetes/test-infra/issues/18652#issuecomment-670970119

There are also a number of release-branch-specific bug fixes that need to be cherry-picked back to support each release-branch variant running off of RBE: https://github.com/kubernetes/test-infra/issues/18652#issuecomment-683216349

**Comment by spiffxp** [comment]
It's also worth keeping an eye on progress on https://github.com/kubernetes/kubernetes/pull/93605

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/pull/93605 has merged, and we started to see 3 consecutive failures in the CI jobs which don't run in RBE.  Those flakes have since been addressed, but I think that's the cue to start moving on this again

**Comment by spiffxp** [comment]
Test durations look roughly equivalent between these two jobs that run `bazel test` without RBE, but the CI job is requesting 7 cpu while the PR job is requesting 4.  I'd like to stick with 4 for the non-canary job and see how it behaves with real PR traffic.
- https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-bazel-test-canary
- https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master

**Comment by spiffxp** [comment]
PR merged 2020-09-09 11:30pm PT, job has started failing a lot more and duration is up near 1h

So, let's bump CPU and see if it's more of the same.  If so, I think we're encountering many more flakes with https://github.com/kubernetes/kubernetes/pull/93605 merged

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/93605 bumped to run each test 3x. That didn't increase runtime in the RBE config, but apparently that was because the work was being done off machine in parallel.

The post-submit that is not running in RBE takes ~3x as long (~45 minutes vs ~15 minutes), so the 3x run seems to affect local runtime linearly (which makes sense).

**Comment by spiffxp** [comment]
Duration going up linearly makes sense, it's the volume of flakes that bothers me.  Let's see if raising CPU via https://github.com/kubernetes/test-infra/pull/19179 helps with that

**Comment by spiffxp** [comment]
I'm not actually sure whether we're being smart about which tests get run or not

https://github.com/kubernetes/test-infra/pull/19179 merged at 8:30am PT today, looks like it's making a difference
![Screen Shot 2020-09-10 at 10 59 26 AM](https://user-images.githubusercontent.com/49258/92777113-b94f3600-f354-11ea-8fe9-2d26b8f08c9c.png)

I'll tee up dropping the runs to 2 but would like to wait a but more to see what the failure/flake rate looks like as-is

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/94699 for running 2 instead of 3 times

**Comment by spiffxp** [comment]
/close
Calling this done
