### ISSUE TITLE
Autobumper fails with expected a consistent version for all \"gcr.io/k8s-prow/\" images, but found multipl

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#19085]
**What happened**:

Run the autobumper for openshift, it fails with

```
time="2020-09-01T17:27:04Z" level=fatal msg="Failed to push changes." error="Expected a consistent version for all \"gcr.io/k8s-prow/\" images, but found multiple: map[v20200526-f1438e04b0:true v20200901-ec959b81e7:true]"
```

**What you expected to happen**:

It to not fail

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

I think this is because of some recent changes by @cjwagner . However its essentially an upstream error (the postsubmit didn't push all images for some reason) so I am not sure if we should error out downstream? Is there anything downstream consumers can do about this?

/area prow
/cc @cjwagner

**Comment by BenTheElder** [comment]
See also #19086 for the upstream push issue

**Comment by alvaroaleman** [comment]
Turns out this was because we still had the old location for boskos, causing the bumper to update from there and the latest boskos version in the prow bucket is much older than the latest prow version there.
