### ISSUE TITLE
sig-testing-prow#push-prow showing consitent auth failures

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19086]
**What happened**:
The [sig-testing-prow#push-prow](https://k8s-testgrid.appspot.com/sig-testing-prow#push-prow) job has had several failures in the last week with complaints in the logs about `goauth`
```
ERROR: (gcloud.auth.docker-helper) You do not currently have an active account selected.
Please run:
  $ gcloud auth login
to obtain new credentials.
If you have already logged in with a different account:
    $ gcloud config set account ACCOUNT
to select an already authenticated account to use.
```

The job appears to go through several retries before attempting to publish images and fails.
Jobs:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1300469619961630722
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1300808670669443072
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1300837358240796673
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1299068753975185410
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1296601962518679552

**What you expected to happen**:
Images are pushed successfully.

**How to reproduce it (as minimally and precisely as possible)**:
(Unsure) It is passing more frequently than not. 

**Please provide links to example occurrences, if any**:
(above)
**Anything else we need to know?**:

/cc @cjwagner

**Comment by chases2** [comment]
Is this issue still occurring? I feel like I would have run into it while bumping prow this morning.

**Comment by chases2** [comment]
The push-prow job had this failure, but then succeeded.
TestGrid: https://k8s-testgrid.appspot.com/sig-testing-prow#push-prow
Failing Job: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1321547288694231040
Succeeding Job (right after): https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1321611482189795328

**Comment by MushuEE** [comment]
@chases2 Looks like we saw it again 11/10: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1326295001029677056

**Comment by MushuEE** [comment]
again: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1327277149471641600
@fejta, do we have a prow TL with Cole gone for a bit?

**Comment by chaodaiG** [comment]
This happened on 12/10 again, twice in a row
https://kubernetes.slack.com/archives/CDECRSC5U/p1607624425279000

**Comment by fejta** [comment]
Things seem fine lately: https://k8s-testgrid.appspot.com/sig-testing-prow#push-prow
