### ISSUE TITLE
approval plugin comment should not suggest assigning approvers without getting a review first

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#19112]
This makes the reiviewer/approver distinction nearly useless because people `/assign` like the comment suggests as soon as they see it.

Nowhere in the large body of text about approval does it suggest that you should let someone review before assigning an approver.

/sig contributor-experience.

**Comment by mrbobbytables** [comment]
I agree =/  often reviewers are just short circuited and jump right to approvers.

/sig contributor-experience

**Comment by BenTheElder** [comment]
It even says in the message (emphasis is original, not mine)

> To complete the pull request process, please assign **bentheelder**
> You can assign the PR to them by writing `/assign @bentheelder` in a comment when ready.

We basically suggest that they should be doing this next with a flash bold message right near the top.

**Comment by BenTheElder** [comment]
@mrbobbytables what do you think about us deferring posting this message until after the PR has an LGTM label?

this does not seem to be working 🤔 

I think we hit contributors with waaaay too much text on opening a PR, so we get selective reading.
