### ISSUE TITLE
Prow UI: browser navigation doesn't work between search filters

### ISSUE THREAD

**Issue by e-blackwelder** [kubernetes/test-infra#19110]
### Reproduction Steps:
One (of many) examples:
- Open https://prow.k8s.io/ in a new tab
- In the "all states" filter, select "error"...
- Notice the URL now says https://prow.k8s.io/?state=error (and the results are filtered)
- Press the browser "back" button...

### Expected behavior:
... Your browser navigates back to the default (no filters selected) search results.

### Actual behavior:
... You're taken completely away from Prow, instead.

### Why is this needed:
- Updating the URL _without_ adding an item to the browser's navigation/history is misleading, producing a bad user experience
- Navigating forwards/backwards between filter options is more easily done by the browser's built-in navigation features than by clicking around inside Prow
- Leaving Prow is probably not intended (but will be commonplace to new users)

**Comment by MushuEE** [comment]
https://github.com/browserstate/history.js maybe?

**Comment by e-blackwelder** [comment]
It seems like the implementation decision was deliberate:
https://github.com/kubernetes/test-infra/search?q=replaceState&type=Code

... Specifically: using [History.replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) (over [History.pushState()](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState)).

I don't know the reason why it was done that way.

**Comment by alvaroaleman** [comment]
This is super annoying and offhand I can not think of a reason why we would deliberately want that. @cjwagner @stevekuznetsov do you remember anything? If not, can we change it?

**Comment by cjwagner** [comment]
I don't know the rationale behind that decision. No blocker from me here.
