### ISSUE TITLE
Retain LGTM through squashes

### ISSUE THREAD

**Issue by sftim** [kubernetes/test-infra#19147]
**What would you like to be added**:
If a PR has /lgtm and is squashed, retain the _LGTM_ label.

**Why is this needed**:
Suggested:
> Ideally the bot would be able to recognize when the PR was squashed and retain the LGTM

in https://github.com/kubernetes/test-infra/issues/9514#issue-362712616

For extra credit: also detect a fast-forward followed by a squash where the fast-forward only includes commits on the main line of the PR's base branch. So if I `git rebase master && git push --force-with-lease` _and_ this creates no merge conflicts, then also retain _LGTM_. This one's quite a bit harder I suspect.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/6353
this is supposed to exist IIRC but may be bugged

**Comment by alvaroaleman** [comment]
This does already exist (and to my knowledge it works) but needs to be enabled by adding a section for your repo here https://github.com/kubernetes/test-infra/blob/ea69abcaae93e9c9034378e60dfd821f22cb718a/config/prow/plugins.yaml#L130 and setting `store_tree_hash: true`

**Comment by MushuEE** [comment]
Does the `tide/merge-method-squash` label also remove lgtm?

**Comment by BenTheElder** [comment]
no, but that's not really comparable, because you get a naive squash commit
as opposed to local squash where you can actually do a fixup / edit the
commit message to make sense and drop any noise like "commit 2 == fix the
thing"

**Comment by sftim** [comment]
https://github.com/kubernetes/test-infra/issues/19147#issuecomment-693006340 implies there's nothing to do.

/close

Thanks @alvaroaleman

**Comment by habibrosyad** [comment]
Just curious, why `store_tree_hash` isn't enabled by default (or to be specific in k/k), and it seems the only repo using it here is k/website? 

My case is at some point there is a PR, already has lgtm and approved labels, but due to code freeze cannot be merged. After the freeze lifted up, there was a conflict because of other PRs which merged first, therefore needs rebase. Force pushed and then lost the lgtm label (which is somehow hard to get again 😆).

**Comment by thockin** [comment]
re: rebase - it's hard to prove a rebase was successful without running tests again.  I think the best case is when I can prove that NOTHING CHANGED except commit structure.  In that case you can bypass CI and retain LGTM.

For example: `find . -not \( -type d -name .git -prune \) -type f | xargs cat | md5sum` takes < 3 seconds to run

**Comment by alvaroaleman** [comment]
> re: rebase - it's hard to prove a rebase was successful without running tests again. I think the best case is when I can prove that NOTHING CHANGED except commit structur

That is in my understanding what the tree hash that is used to potentially retain the LGTM does
