### ISSUE TITLE
Sinker stopped deleting pods after prow bump

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#19157]
**What happened**:
Sinker stopped deleting pods after bumping prow https://github.com/kubernetes/test-infra/pull/19105

**What you expected to happen**:
Sinker work properly

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by chaodaiG** [comment]
Reverting the bump for now: https://github.com/kubernetes/test-infra/pull/19156

**Comment by chaodaiG** [comment]
The reverted changes are: https://github.com/kubernetes/test-infra/compare/b5ff4681c3...94d8b4dfcd

**Comment by chaodaiG** [comment]
Based on sinker logs, there was no error listing pods or deleting pods, so it seems like the problem is at listing pods, which could possibly related to https://github.com/kubernetes/test-infra/pull/19090
+ @alvaroaleman for insights

**Comment by fejta** [comment]
> The reverted changes are: b5ff468...94d8b4d

Try and use a PR next time :)

**Comment by chaodaiG** [comment]
/reopen

This appeared after the bump today

**Comment by alvaroaleman** [comment]
Fixed in #19194 
/close
