### ISSUE TITLE
Crier: gerrit reporter delayed by 50 minutes, and duplicate reporting

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#19161]
**What happened**:
After bumping prow from https://github.com/kubernetes/test-infra/compare/967ee0e48b...b5ff4681c3, crier gerrit reporter reported on gerrit label ~50 minutes after all jobs voting for the label finished. Also, the reporter reported N times the same message when there are N jobs voting on the same label

**What you expected to happen**:
Crier gerrit reporter delay no more than a couple of minutes, and no duplicate reports

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
After filtering all the changes between the bump, the most relevant PR is https://github.com/kubernetes/test-infra/pull/18950

**Comment by chaodaiG** [comment]
cc @alvaroaleman

**Comment by chaodaiG** [comment]
cc @cjwagner

**Comment by alvaroaleman** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/19171
/close
