### ISSUE TITLE
/lgtm should assign me if I'm not assigned

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#1916]
The reason I didn't implement this in the first place was because then just anyone could say `/lgtm` from an alt account and merge their own terrible code. Now that approvers are in place, if I type `/lgtm` and I'm not an assignee, should k8s-ci-robot assign me and apply lgtm?

I'd be happy to write the code, just want to make this issue for discussion.

@apelisse @kubernetes/sig-contributor-experience-feature-requests

**Comment by apelisse** [comment]
cc @grodrigues3 

I still don't think it's a good idea. We want to grow the list of reviewers, we don't want it to be infinite.
If I'm an approver of the code in my PR, I can still get it merged by `/lgtm`-ing from my alt-account, and completely pass through review.

**Comment by krzyzacy** [comment]
If I have the permission to assign myself, then assign myself? Is it possible to check that?

**Comment by ixdy** [comment]
@apelisse I'm not sure whether that's actually an issue. If you're listed as an approver for some code, we already assume you're a good actor and won't abuse those privileges.

**Comment by apelisse** [comment]
Agreed, but I still believe we should expect lgtm from someone with experience with the code.

**Comment by grodrigues3** [comment]
I'm okay with this contingent on:

1. Authors cannot `lgtm` their own code
1. `/lgtm` can only be written by people listed as "reviewers" in an ancestral owners file (i.e. you can only be assigned and lgtm if you are in an owners file as a reviewer)

This requires more logic and prow having some understanding of owners files.

**Comment by apelisse** [comment]
Absolutely, the next step forward here would be to have OWNERS logic in prow.

**Comment by spxtr** [comment]
That sounds great to me. After I've finished my current project I'd like to add a git clone to the plugin client that has the PR fetched when they're called.

**Comment by apelisse** [comment]
Yeah, I think we could do tons of sweet things with a copy of the repo.

**Comment by spxtr** [comment]
@k8s-bot tell me a joke

**Comment by bgrant0607** [comment]
I commented on this in the PR:

https://github.com/kubernetes/test-infra/pull/2118#issuecomment-285467089
