### ISSUE TITLE
Job not triggered when using regex in branches.

### ISSUE THREAD

**Issue by elfinhe** [kubernetes/test-infra#19229]
**What happened**:

We are following this doc (https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md) to configure a prow job to use Regex to match multiple branches.
```
postsubmits:
  org/repo:
  - branches:             # Regexps, only run against these branches.
    - release-1.7-pdn
    - release-1.7.*-pdn
    decorate: true        # As for periodics.
    spec: {}              # As for periodics.
    max_concurrency: 10   # Run no more than this number concurrently.
    name: bar-job         # As for periodics.
```
And expect the job would be triggered on release-1.7.1-pdn, but turned out not. Then we switch back to use non-regex:

```
postsubmits:
  org/repo:
  - branches:             # Regexps, only run against these branches.
    - release-1.7-pdn
    - release-1.7.1-pdn
    decorate: true        # As for periodics.
    spec: {}              # As for periodics.
    max_concurrency: 10   # Run no more than this number concurrently.
    name: bar-job         # As for periodics.
```
Then the job was triggered.

**What you expected to happen**:
The job can be triggered by specifying regex on branches.

**Comment by matthyx** [comment]
@elfinhe this is strange as I cannot reproduce it here (ie test works as expected):
https://github.com/kubernetes/test-infra/compare/master...matthyx:19229

Could you give a more accurate version of your config?

**Comment by matthyx** [comment]
@elfinhe ping?

**Comment by elfinhe** [comment]
Thanks @matthyx, the prow config is internal and I am not allowed to copy the full text. Do you have some thoughts which field I should look at?

**Comment by matthyx** [comment]
Could you check if your code is like my attempt to reproduce, if not tell me how to change it:
https://github.com/kubernetes/test-infra/compare/master...matthyx:19229

**Comment by elfinhe** [comment]
verified that this was a misconfig in our internal prow config generation. Sorry for creating this false alarm.

Thanks @matthyx for being on top of this issue.
