### ISSUE TITLE
Prow's PR history page doesn't properly identify commit until job completes.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#19232]
**What happened**:
Job runs seem to always appear in the "Unknown" column until the job completes.
<img width="1311" alt="Screen Shot 2020-09-15 at 5 22 01 PM" src="https://user-images.githubusercontent.com/5334145/93277990-412fa880-f778-11ea-86ea-649145187a08.png">

**What you expected to happen**:
Jobs should be listed under the correct column while they are still running.

**How to reproduce it (as minimally and precisely as possible)**:
1. Find a running presubmit job: https://prow.k8s.io/?type=presubmit&state=pending
1. Then click the "PR History" button and notice the job(s) in the "Unknown" column.

**Please provide links to example occurrences, if any**:
Any examples I link won't be useful once the job completes. Use the reproduction steps above to find a live example.

/help
/good-first-issue
/area prow prow/deck

**Comment by Rustin-Liu** [comment]
Can I working on this?

**Comment by petr-muller** [comment]
Nobody assigned it to themselves yet and it's `help wanted` so sure, go ahead!

**Comment by vicsufer** [comment]
Hi @Rustin-Liu are you still working on it? I'd like to give it a try if not.
