### ISSUE TITLE
Triggering image build job on new tags.

### ISSUE THREAD

**Issue by prameshj** [kubernetes/test-infra#19242]
Support for building images from k8s.io/dns was added in - https://github.com/kubernetes/test-infra/pull/17123
The build job runs everytime there is a new PR merged into master branch. The _GIT_TAG is of the form - "v20200416-1.15.12-2-g232a189"
This is the cloudbuild yaml - https://github.com/kubernetes/dns/blob/master/cloudbuild.yaml

I want to configure this so that, when there is a new tag added to the repo, a build id triggered with _GIT_TAG=<value of the newly added tag>
Is this supported? 
I am able to manually submit a build with the tag value like:
```
gcloud builds submit ~/src/k8s.io/dns --config cloudbuild.yaml --substitutions _PULL_BASE_REF=master,_GIT_TAG=1.15.14 --project k8s-staging-dns --gcs-log-dir gs://k8s-staging-dns-gcb/logs --gcs-source-staging-dir gs://k8s-staging-dns-gcb/source
```
It would be great to automate this.
Any thoughts on how to achieve this?

@fejta @listx

**Comment by justaugustus** [comment]
I think adding a SemVer regex in the `branches` list of your jobs should work.

ref: https://github.com/kubernetes/test-infra/blob/f316ca27125ebdcfe93ef92cc9cd119269f09fad/config/jobs/image-pushing/k8s-staging-cluster-api.yaml#L14
