### ISSUE TITLE
Use alternate names for blacklist/whitelist in prow

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#19264]
**What should be cleaned up or changed**:
There are sundry files within prow that can probably use more specific terms, or the generic terms "allowlist/denylist"

```
$ ag -l whitelist\|blacklist prow | sort
prow/ANNOUNCEMENTS.md # ignore, deprecation announcements
prow/cmd/exporter/collector.go
prow/cmd/exporter/collector_test.go
prow/cmd/hook/main.go
prow/cmd/status-reconciler/main.go # offending flag has been deprecated
prow/cmd/status-reconciler/main_test.go
prow/config/config.go
prow/config/prow-config-documented.yaml
prow/hook/hook_test.go
prow/plugins/approve/approve_test.go
prow/plugins/blunderbuss/blunderbuss_test.go
prow/plugins/config.go
prow/plugins/lgtm/lgtm_test.go
prow/plugins/plugin-config-documented.yaml
prow/plugins/verify-owners/verify-owners.go
prow/plugins/verify-owners/verify-owners_test.go
prow/repoowners/repoowners.go
prow/repoowners/repoowners_test.go
```

EDIT: pulling up from https://github.com/kubernetes/test-infra/issues/19264#issuecomment-767913564

All instances of `whitelist` have been removed from prow (thanks @chases2!).  `blacklist` appears in two config fields that would need to be deprecated:

- [ ] `OwnersDirBlackList`, in the Prow config
- [ ] `LabelsBlacklist`, in the Prow plugins config

**Provide any links for context**:

/area prow
/wg naming
/sig testing

**Comment by justaugustus** [comment]
Needs a rec proposed for replacement.
cc: @kubernetes/wg-naming

**Comment by justaugustus** [comment]
For ADR:
/assign @celestehorgan 

For advice on impl:
/assign @justaugustus

**Comment by justaugustus** [comment]
ADR up for review: https://github.com/kubernetes/community/pull/5341

**Comment by chases2** [comment]
I went through the files in the prow dir and renamed the easier ones. I managed to remove all of the instances of "whitelist", but "blacklist" has two configurations that would need to be deprecated:

- [ ] `OwnersDirBlackList`, in the Prow config
- [ ] `LabelsBlacklist`, in the Prow plugins config

Also notable:
- The file ANNOUNCEMENTS.md contains deprecation announcements, which shouldn't be changed.
- status-reconciler has already had its flag deprecated, with a tombstone date of June 1st.
    - [ ] After June 1st, delete the flag

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/18801 (covered slack mergewarning plugin)

**Comment by chaodaiG** [comment]
#21577 and #21580 are for deprecating the remaining two "blacklist" config fields

**Comment by spiffxp** [comment]
/milestone v1.23
/remove-lifecycle stale
I think what is keeping this open is that we are waiting to run down the deprecation clock so we can remove the old fields

**Comment by spiffxp** [comment]
Deprecation clock has passed, if someone is interested in removing support for the old fields as documented here:
https://github.com/kubernetes/test-infra/blob/530961d60201d967c9123baa2089045870344bc2/prow/ANNOUNCEMENTS.md#L184-L187

**Comment by BenTheElder** [comment]
/lifecycle frozen
/good-first-issue
https://github.com/kubernetes/test-infra/issues/19264#issuecomment-937352372 should be pretty straightforward, this ought to be a decent starter issue.

You will need to remove the deprecated fields and there associated code, and perhaps double check if we've missed any documentation references. There also needs to be a note in the announcements that they are now removed.

**Comment by BenTheElder** [comment]
wg/naming was dissolved.
Clearing assignees so it's clear that no-one is working on this.

If anyone is interested, please feel free to reach out to me or @chaodaiG, we can help answer any questions.

**Comment by adhishmeena** [comment]
Hi , @chaodaiG Please share the update regarding this issue. I would like to work on this issue

**Comment by BenTheElder** [comment]
Hi all, please feel free to work on this. You don't need to ask us for permission, but you might want to coordinate to avoid overlapping work.

I think this is almost done, but not fully removed yet https://cs.k8s.io/?q=blacklist&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra

**Comment by harshitasao** [comment]
@adhishmeena If that's okay with you, I'll go ahead and work on this.

**Comment by harshitasao** [comment]
Hey @BenTheElder, I have made changes to all the required files. However, 
1. I'm not sure if I should remove the code or modify it [here](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/status-reconciler/main.go#:~:text=%7D-,if%20len(o.addedPresubmitBlacklist.Strings())%20%3E%200,%7D,-return%20nil).


![fq1](https://user-images.githubusercontent.com/84518563/168454777-1c5540ef-53c5-45f4-b805-549ff28392dc.png)

2. Also, I'm not sure how to make changes to [this](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/status-reconciler/main.go#:~:text=func%20(o%20*options)%20getDenyList,%7D) function.


![fq2](https://user-images.githubusercontent.com/84518563/168454928-90fc4f34-89ff-4b14-99ea-f6689cd0dee5.png)

Can you please help me out? 
Thank you.

**Comment by BenTheElder** [comment]
1) should be removed when the blacklist field is removed since there's no longer another flag to be exclusive with

2) should remove the second line of the method appending.

**Comment by harshitasao** [comment]
Thank you so much.

**Comment by harshitasao** [comment]
@BenTheElder, can you please suggest where I should put the note in the [ANNOUNCEMENTS.md](https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md)
Thank you.

**Comment by BenTheElder** [comment]
Under "Breaking Changes" since it is still a breaking change to remove them.
The entries are chronological with the current entry at the top. The prow versions are date + commit hash.

**Comment by Atharva-Shinde** [comment]
if there's still some work remaining, I would like to work on this

**Comment by CypherpunkSamurai** [comment]
Hello Everyone, Is this issue still active?

I'm new to open-source and would like to contribute to this issue :)

**Comment by spiffxp** [comment]
/close
Only mentions left are in job configs or announcements describing the migration to allowlist/denylist
```
$ rg -il 'blacklist|whitelist'
config/jobs/kubernetes/sig-scalability/sig-scalability-presets.yaml
config/jobs/kubernetes-sigs/node-feature-discovery/node-feature-discovery-postsubmits.yaml
prow/ANNOUNCEMENTS.md
```
