### ISSUE TITLE
Setup postsubmit job to auto deploy triage's frontend

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#19324]
**What should be cleaned up or changed**:
The actual html page that lives at `go.k8s.io/triage` is manually updated by humans running `make push-static`.  We should have prow do this for us in a postsubmit.  It should run in the test-infra-trusted cluster with an appropriate service account

**Provide any links for context**:
Noticed we auto deploy the image, but not the page while reviewing: https://github.com/kubernetes/test-infra/pull/19300

/sig testing
/area triage

**Comment by BenTheElder** [comment]
This is already setup? I worked on this.

**Comment by spiffxp** [comment]
/close
That you did! Done in https://github.com/kubernetes/test-infra/pull/18733
