### ISSUE TITLE
~Jan 2021: enable storage-bucket validation by default

### ISSUE THREAD

**Issue by e-blackwelder** [kubernetes/test-infra#19366]
Storage bucket validation was introduced in #18001. It is currently opt-in only (via deck configuration).

Validation should be enabled by default -- but no sooner than ~Jan 2021. (This grace period allows Prow instance maintainers time to inspect logs and configure additional allowed storage buckets.)

**Comment by matthyx** [comment]
/remove-lifecycle stale
@e-blackwelder ping I think you can enable it now by default

**Comment by matthyx** [comment]
@alvaroaleman what do you think?

**Comment by alvaroaleman** [comment]
Yeah, we can enable it by default
