### ISSUE TITLE
gs://cel-conformance/test-logs unable to be parsed correctly and are Artifact-less 

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19376]
**What happened**:
Kettle is unable to parse xml for all of these jobs: 

gs://cel-conformance:
  contact: "JimLarson"
  prefix: "cel:"
```
ERROR:root:error on gs://cel-conformance/test-logs/20191030050108
Traceback (most recent call last):
  File "make_json.py", line 280, in make_rows
    yield rowid, row_for_build(path, started, finished, results)
  File "make_json.py", line 220, in row_for_build
    for test in parse_junit(result):
  File "make_json.py", line 192, in parse_junit
    suite_name = testsuite.attrib['name']
KeyError: 'name'
```
**What you expected to happen**:
If the xml exists it should be properly formed. Though I can't find the xml that is in the process of attempting to be parsed yet.
[job link](https://prow.k8s.io/view/gcs/cel-conformance/test-logs/20191030050108)
/cc @JimLarson

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/assign
/area kettle

**Comment by JimLarson** [comment]
Our conformance dashboard update pipeline has been down for a while as we debug a configuration change. Since it might be affecting you, I'll roll back that change and see if that gets you working again.

**Comment by JimLarson** [comment]
Reverted. Let me know if that fixes your issue.

**Comment by MushuEE** [comment]
@JimLarson thank you, I will give it a try later and see if it is. The fix should probably be in the service though. It should not be getting to the point that is parses non-existent xml

**Comment by MushuEE** [comment]
@JimLarson do you still have need to track these jobs in BQ? Because kettle goes back in time it still fails for all the existing jobs in this state. I still need a fix on kettle end but would be nice to remove the bucket searching if they are not needed in tracking any longer
