### ISSUE TITLE
Sinker error in oss-prow: `Failed to remove kubernetesreporter finalizer`

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#19382]
Seeing some sinker issues in oss-prow (for https://github.com/GoogleCloudPlatform/oss-test-infra).

```
jsonPayload: {
  cluster: ""   
  component: "sinker"   
  file: "prow/cmd/sinker/main.go:499"   
  func: "main.podNeedsKubernetesFinalizerCleanup"   
  level: "error"   
  msg: "BUG: Pod for prowjob still had the prow.x-k8s.io/gcsk8sreporter finalizer after completing and being successfully reported by the gcsk8sreporter reporter"   
  pj: "eeece533-01aa-11eb-9637-466410b1a561"   
 }
```

```
jsonPayload: {
  cluster: ""   
  component: "sinker"   
  error: "failed to patch pod: pods "eeece533-01aa-11eb-9637-466410b1a561" is forbidden: User "system:serviceaccount:default:sinker" cannot patch resource "pods" in API group "" in the namespace "test-pods""   
  file: "prow/cmd/sinker/main.go:395"   
  func: "main.(*controller).clean"   
  level: "error"   
  msg: "Failed to remove kubernetesreporter finalizer"   
  pj: "eeece533-01aa-11eb-9637-466410b1a561"   
 }
```

CC'ing Alvaro and Cole who I think have some context on these failures previously.

/cc @alvaroaleman @cjwagner 
/area prow
/area prow/sinker

**Comment by alvaroaleman** [comment]
What prow version is this? There were some issue in this in older prow versions but (to my knowlege) they are all fixed in a current version.

The second error just means that sinker does not have `PATCH` permissions for pods but needs them

**Comment by michelle192837** [comment]
sinker (and other components I believe) are running on the `v20200921-becd8c9356` image?

**Comment by alvaroaleman** [comment]
okay, that version should not have any bugs anymore there, hm.

**Comment by cjwagner** [comment]
We just need to update this list: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/f53df41a49966a29d728430e33eabbe6a3114ea2/prow/oss/cluster/sinker.yaml#L67-L68
to match this list: https://github.com/kubernetes/test-infra/blob/7f22698becb0092f6f41e92725e3c73962d16cf9/config/prow/cluster/sinker_rbac.yaml#L50-L54
(I'm dealing with some issues with my dev environment at the moment, otherwise I'd have made a quick PR.)

**Comment by michelle192837** [comment]
Thanks all! I can make that PR in a bit then. ^^

**Comment by michelle192837** [comment]
Ah sorry, forgot to update. I think oss-prow is fine now, I have not seen the error reoccur in recent logs. I'll close this particular issue since it's not causing a problem for us anymore.

Also fine with the log level for that message being downgraded!
