### ISSUE TITLE
Rename gci to cos

### ISSUE THREAD

**Issue by bsdnet** [kubernetes/test-infra#19384]
**What should be cleaned up or changed**:

There are a lot of places, in both code and dashboard, naming COS as GCI, which confuses community since most people is aware of Google Container Optimized OS, but not its early name GCI.

It will be nice to rename gci to cos slowly from UI to code.

**Provide any links for context**:

$ git grep gci |wc -l
802

The strategy can be that to change kubetest/extract_k8s.go first, and make cos/gci co-exist for a while, and update test-infra correspondingly. Then remove gci totally after a while.

**Comment by knabben** [comment]
@bsdnet @BenTheElder there are some tabs like *containerd-e2e-gci-1.3* in the *sig-node-containerd* for example, 

One of the difference is the GCP image == gci, are these jobs running in an old image as well? In these cases, only renaming is enough?

* --gcp-node-image=gci *

**Comment by BenTheElder** [comment]
cos is a symlink to gci, actually
https://github.com/kubernetes/kubernetes/tree/master/cluster/gce

**Comment by knabben** [comment]
> cos is a symlink to gci, actually https://github.com/kubernetes/kubernetes/tree/master/cluster/gce

Now the last statement of the issue description makes sense.

**Comment by bsdnet** [comment]
> @bsdnet @BenTheElder there are some tabs like _containerd-e2e-gci-1.3_ in the _sig-node-containerd_ dashboard, for example with this pattern, and one of the difference is the GCP image (gci):
> 
> _--gcp-node-image=gci_
> 
> Are these jobs running in an old image? In this cases, only renaming should be enough?

No, they are running on latest COS image. There is some tricks like what @BenTheElder  mentioned, some directories are symlinked.

**Comment by knabben** [comment]
https://docs.google.com/document/d/1KlnfvQ_OPkrty5DvKHmeEMTKMpaVK-ioHgDOpVFRrkA

After some conversation with Roy, I created a proposal for the sig-node rename here. The https://github.com/kubernetes/test-infra/pull/20351 is the first step here.

cc @BenTheElder @bsdnet

**Comment by bsdnet** [comment]
I will take a look at the doc @knabben

**Comment by BenTheElder** [comment]
From SIG testing POV the name change sounds good but we don't really have the bandwidth to focus on this and IMHO I consider the VM image naming SIG node or at least the Google Node team.
