### ISSUE TITLE
sig-node-cos dashboard proposal

### ISSUE THREAD

**Issue by knabben** [kubernetes/test-infra#19401]
**What should be cleaned up or changed**:

In order to clean up gci in favor of cos:

There's a bunch of containerd-e2e-gci* tabs in the *sig-node-containerd* dashboard, they are running an old CI image (kubetest-e2e), the goal strategy is to divide and conquer, so we will probably have a clear view of what needs to go in a separated board. 

Here is a list of the jobs could be in the separated dashboard:

```
 containerd-e2e-gci-1.2
 containerd-e2e-gci-1.3
 e2e-gci-alpha-features
 e2e-gci-device-plugin-gpu
 e2e-gci-flaky
 e2e-gci-ingress
 e2e-gci-ip-alias
 e2e-gci-multizone
 e2e-gci-proto
 e2e-gci-reboot
 e2e-gci-serial
 e2e-gci-slow
 soak-gci-gce
```

**Provide any links for context**:

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/containerd.yaml

**Comment by bsdnet** [comment]
@knabben  gci is the early name of COS. The test is not old image, and just the naming.
I suggest that we can move them into a separate dashboard

**Comment by knabben** [comment]
> I suggest that we can move them into a separate dashboard

The proposal of the issue is to move in a new dashboard under sig-node, do you have any other in mind for these gci jobs?

**Comment by bsdnet** [comment]
The first step should be consolidated them into a dashboard like sig-node-cos.
sig-node-cos
* containerd-e2e-cos-1.2
*  containerd-e2e-cos-1.3
*  e2e-cos-alpha-features
* e2e-cos-device-plugin-gpu
* e2e-cos-flaky
* e2e-cos-ingress
 * e2e-cos-ip-alias
 * e2e-cos-multizone
 * e2e-cos-proto
 * e2e-cos-reboot
 * e2e-cos-serial
 * e2e-cos-slow
 * soak-cos-gce

Then we can start from there.  At least, this will not cause confusion and clarify a lot of things.
