### ISSUE TITLE
GCSweb manifest for prow.k8s.io  not in git

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#19407]
**What happened**:

It seems there is no gcsweb manifest for prow.k8s.io in the test-infra repo, even though its clearly setup at https://gcsweb.k8s.io/gcs/kubernetes-jenkins/

**What you expected to happen**:

To find a gcsweb manifest in this repo

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/area prow/config

**Comment by spiffxp** [comment]
It's over here https://github.com/kubernetes/k8s.io/tree/master/gcsweb.k8s.io

**Comment by alvaroaleman** [comment]
ah okay, out of curiosity, why is it in a different repo and not part of the autobumping?

**Comment by BenTheElder** [comment]
It doesn't run as part of the google.com infrastructure, unlike prow.k8s.io's primary clusters and the targets being bumped.

github.com/kubernetes/k8s.io hosts manifests for the things running on CNCF infrastructure, including also CNCF build cluster + boskos + the literal k8s.io + k8s.gcr.io + ...
