### ISSUE TITLE
Kettle google-cloud-sdk should not need force pinning.

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19414]
**What should be cleaned up or changed**:
#19369 was added to deal with #19365 
```
BigQuery error in load operation: Could not connect with BigQuery server due to:
RedirectMissingLocation('Redirected but the response is missing a Location:
header.',)
```

The pinning of the version should be a short term fix.

**Provide any links for context**:

**Comment by MushuEE** [comment]
Revert #19415 on close

**Comment by BenTheElder** [comment]
🛸 scanning for signs of life 🛸

**Comment by MushuEE** [comment]
This will take a little digging, but I will circle back. I found this issue even internal. 
/remove-lifecycle stale

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/21120 actually fixed here I think?

**Comment by MushuEE** [comment]
@BenTheElder Correct I believe it no longer needs to be back pinned as the issue was fixed.
