### ISSUE TITLE
Flake: ERROR: An error occurred during the fetch of repository 'bazel-base'

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19416]
**What happened**:
[Failure:](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/19415/pull-test-infra-bazel/1311455481528586240)
```
ERROR: An error occurred during the fetch of repository 'bazel-base':
ERROR: /home/prow/go/src/github.com/kubernetes/test-infra/testgrid/cmd/transfigure/BUILD.bazel:3:1: //testgrid/cmd/transfigure:image depends on @bazel-base//image:image in repository @bazel-base which failed to fetch. no such package '@bazel-base//image': Pull command failed: 2020/10/01 00:00:23 Running the Image Puller to pull images from a Docker Registry...
ERROR: Analysis of target '//prow:release' failed; build aborted: no such package '@bazel-base//image': Pull command failed: 2020/10/01 00:00:23 Running the Image Puller to pull images from a Docker Registry...
```
Seen in #17643 and #17534
**What you expected to happen**:
No failure on pull
**How to reproduce it (as minimally and precisely as possible)**:
Unknown
**Please provide links to example occurrences, if any**:
Above
**Anything else we need to know?**:

/kind flake
/cc @spiffxp

**Comment by BenTheElder** [comment]
The more general bug here is image pulling can flake. I don't think there's not much we can do in this repo. https://github.com/bazelbuild/rules_docker/issues/673
