### ISSUE TITLE
Hacktoberfest triage

### ISSUE THREAD

**Issue by sftim** [kubernetes/test-infra#19420]
**What would you like to be added**:
Add a new triage label for drive-by, poor quality pull requests masquerading as contributions. Potentially, add automation to act on that label (eg: post explanatory comment, add `invalid` label, close issue).

**Why is this needed**:
Digital Ocean offer T-shirts to anyone making a high quality contribution to open source projects during October. Unfortunately, this promotion is also open to people making low quality spammy contributions to open source projects.
Digital Ocean's brand for this is [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

As a community, we believe that [inclusive is better than exclusive](https://github.com/kubernetes/community/blob/master/values.md#inclusive-is-better-than-exclusive) and we do welcome PRs from anyone willing to sign the CLA; however, we also “value time spent automating repetitive work more highly than toil”.
The more popular that Hacktoberfest becomes the more effort will be required for triage of the low quality contributions.

**Comment by sftim** [comment]
Some context, a selection of PRs against [k/website](https://github.com/kubernetes/website/):
https://github.com/kubernetes/website/pulls?q=is%3Apr+Hacktoberfest

**Comment by nikhita** [comment]
We've reached out to DO about this and we are waiting for their response. Depending on their response, we can look at adding an `invalid` label just for October (i.e. we remove the label after October).

cc @mrbobbytables 

/sig contributor-experience

**Comment by markyjackson-taulia** [comment]
Thank you for this!

**Comment by MushuEE** [comment]
They should make it only about planting trees and not the T-Shirt.

**Comment by nikhita** [comment]
Hacktoberfest is now opt-in and we are not going participating - https://groups.google.com/g/kubernetes-dev/c/jDp34QS38iw/m/kgoVNz7sCgAJ

Closing this issue :)
