### ISSUE TITLE
plank: Reconciler error not finding pod

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#19426]
**What happened**:

Plank reconciler error with message:
```
jsonPayload: {
level: "error"
controller: "plank"
name: "99481f9e-03f7-11eb-9ee9-2af320b50223"
msg: "Reconciler error"
namespace: "default"
stacktrace: "github.com/go-logr/zapr.(*zapLogger).Error
	external/com_github_go_logr_zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90"
logger: "controller-runtime.controller"
error: "pods "99481f9e-03f7-11eb-9ee9-2af320b50223" not found"
ts: 1601570601.1900854
}
```

While at the same time plank deleted and created the same pod:
![Screen Shot 2020-10-01 at 10 23 43 AM](https://user-images.githubusercontent.com/45011425/94842672-8555b680-03d0-11eb-9976-c38c14ce1bf3.png)

**What you expected to happen**:
Not quite sure about the order. Is plank reconciler error the result of planking deleting the pod? Or it's the other way around? 

Also, this pod is a working pod that runs prow jobs, is plank responsible for deleting the pod?

**How to reproduce it (as minimally and precisely as possible)**:

See stackdriver log: https://pantheon.corp.google.com/logs/query;query=jsonPayload.controller%3D%22plank%22%0AjsonPayload.name%3D%2299481f9e-03f7-11eb-9ee9-2af320b50223%22%0A;timeRange=2020-10-01T15:22:15.305Z%2F2020-10-01T17:22:15.305Z;summaryFields=jsonPayload%252Flevel,jsonPayload%252Fcomponent,jsonPayload%252Fmsg:false:32:beginning?scrollTimestamp=2020-09-10T18:01:26.000000000Z&project=k8s-prow

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by chaodaiG** [comment]
cc @alvaroaleman in case you know more

**Comment by alvaroaleman** [comment]
@chaodaiG thats an internal link I can't access, what was the reason the pod got deleted?

**Comment by alvaroaleman** [comment]
The pod here got evicted from the node, in which case we silently replace it by first deleting it and then re-creating it in the next iteration: https://github.com/kubernetes/test-infra/blob/f2a89bbd48432579922ae1c8edc8ace85d5fc825/prow/plank/reconciler.go#L329-L354 The only bug here is that we do not properly cope with 404 when deleting. We apparently got two events, deleted the pod on the first event, didn't have the pod as deleted in our cache when processing the second event, deleted it again and got that error.
