### ISSUE TITLE
Extending CI support to s390x

### ISSUE THREAD

**Issue by gajju26** [kubernetes/test-infra#1943]
I had opened an issue https://github.com/kubernetes/kubernetes/issues/39229 for extending CI support to s390x. From that issue I came to know that using kubeadm I will join s390x node to Kubernetes cluster of CI and the attached node will be used for CI.  From the same thread I also came to know that this process is not completed yet and migration of jobs to use kubernetes pods is in progress. I would like to contribute in this activity. I have been going through some documentation to understand this process and if I am not wrong for Kubernetes CI bazel is the tool that is being used. Can anyone tell me bazel is the pre-requisite for Kubernets CI on s390x.  If yes then  "bazel build //..."  and  "bazel test //..."  commands should pass on s390x?

**Comment by gajju26** [comment]
@fejta for Kubernetes CI do you have any idea the commands "bazel build //..." and "bazel test //..."  should pass ?

**Comment by ixdy** [comment]
@gajju26 in kubernetes, bazel doesn't really work for anything besides linux/amd64 right now.
