### ISSUE TITLE
Build logs for image-builder GCB jobs remain stuck in GCB

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#19436]
**What happened**:
People with (no-variants?) image-builder jobs have (occasionally?) been unable to access build logs for their job via spyglass.  Instead, contributors have to use their membership in a @kubernetes.io group and view the logs directly in GCB, or bug someone with access to GCB to do so.

**What you expected to happen**:
The intended path, AFAIK, is for image-builder to download logs as artifacts into GCS for consumption/display by spyglass and other publicly accessible means.  

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1311413810094936064
  - successful build, has variants
  - has variants
  - https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1311413810094936064/artifacts/ has output from gcb for each variant
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1311017772431446016
  - failed build, has variants

**How to reproduce it (as minimally and precisely as possible)**:
Not sure offhand.  Opening this to flag the issue, because I've seen questions come up from time to time in #testing-op

**Please provide links to example occurrences, if any**:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-descheduler-push-images/1312031935203119104
  - successful build, no variants
  - https://storage.googleapis.com/kubernetes-jenkins/logs/post-descheduler-push-images/1312031935203119104/artifacts/build.log - "Logs are available at [https://console.cloud.google.com/cloud-build/builds/dfde06e2-c40e-4953-a595-16e29f3e2bc4?project=1009880777024]" - the logs at that uri are what we actually want
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-aws-push-images/1312024880396374016
  - same behavior, different repo
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-scheduler-plugins-push-images/1311031861232799744
  - failed build, no variants
  - directly in spyglass / build-log.txt: "Logs are available at [https://console.cloud.google.com/cloud-build/builds/3e838419-baa1-46ed-a980-a95dd21b6147?project=96918712006]"  - these are what we actually want
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-test-images/1309411632278933504
  - same behavior, different repo
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-kubekins-e2e/1311017772431446016

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
I thought we downloaded these into $ARTIFACTS?

**Comment by claudiubelu** [comment]
FWIW, the post-kubernetes-push-e2e-test-images job has been split into multiple, smaller images (one per image), also increasing the images covered in the process.

Now, with these jobs, we don't seem to have the same issue of not having the image building logs. Here's an example: https://storage.googleapis.com/kubernetes-jenkins/logs/post-kubernetes-push-e2e-sample-apiserver-test-images/1341141540679979008/artifacts/build.log

**Comment by claudiubelu** [comment]
This is no longer an issue. We can directly access the job logs by going to the job artifacts: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-agnhost-test-images/1440368845050089472

/close
