### ISSUE TITLE
Provide command args for prow jobs' chatOps command

### ISSUE THREAD

**Issue by raghurps** [kubernetes/test-infra#19456]
**What would you like to be added**:
Functionality to provide args to prowjobs as part of chatOps command.
e.g. `/test myJob --run-suite=e2e --debug`
Translate these args to job spec by appending these args.

**Why is this needed**:
Consider a scenario where I have 100 test suites.

If I want to trigger each suite separately, I may have to add 100 preSubmit jobs in config.yaml or my repo's `.prow.yaml` which makes the yaml file huge and there is a lot of repetition too.

**Comment by matthyx** [comment]
@raghuP9 how do you see this working?
Should I blindly accept and merge all args provided after `myJob` to the ProwJob spec?
Maybe some sort of **safelist** and **blocklist** to give more flexibility to prow admins?

**Comment by raghuP9** [comment]
> @raghuP9 how do you see this working?
> Should I blindly accept and merge all args provided after `myJob` to the ProwJob spec?
> Maybe some sort of **safelist** and **blocklist** to give more flexibility to prow admins?

Yes, having a **safelist** or **blocklist** of args along with their acceptable/un-acceptable values in ProwJob spec will solve this issue to some extent.

**Comment by matthyx** [comment]
sorry, I won't have time for that...
/unassign
/help
