### ISSUE TITLE
release-blocking jobs must run in dedicated cluster: ci-kubernetes-build-fast

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#19484]
**What should be cleaned up or changed**:

This is part of #18549 

To properly monitor the outcome of this, you should be a member of k8s-infra-prow-viewers@kubernetes.io.  PR yourself into https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml#L603-L628 if you're not a member.

NOTE: I am not tagging this as "help wanted" because it is blocked on https://github.com/kubernetes/k8s.io/issues/846.  Here is my guess at how we could do this:
- create a duplicate job that pushes to the new bucket writable by k8s-infra-prow-build
- ensure it's building and pushing appropriately
- update a release-blocking job to pull from the new bucket
- if no problems, roll out changes progressively
  - a few more jobs in release-blocking
  - all jobs in release-blocking that use this job's results
  - a job that still runs in the "default" cluster
  - all jobs that use this job's results
- rename jobs / get rid of the job that runs on the "default" cluster

It will be helpful to note the date/time that PR's merge.  This will allow you to compare before/after behavior.

Things to watch for the job
- https://prow.k8s.io/?job=ci-kubernetes-build-fast
  - does the job start failing more often?
  - does the job start going into error state?
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#ci-kubernetes-build-fast&graph-metrics=test-duration-minutes
  - does the job duration look worse than before? spikier than before?
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=ci-kubernetes-build-fast
  - do more failures show up than before?
- https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/ci-kubernetes-build-fast
  - (can be used to answer some of the same questions as above)
- [metrics explorer: CPU limit utilization for `ci-kubernetes-build-fast` for 6h](https://console.cloud.google.com/monitoring/metrics-explorer?project=k8s-infra-prow-build&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22kubernetes.io%2Fcontainer%2Fcpu%2Flimit_utilization%5C%22%20resource.type%3D%5C%22k8s_container%5C%22%20metadata.user_labels.%5C%22prow.k8s.io%2Fjob%5C%22%3Dmonitoring.regex.full_match(%5C%22ci-kubernetes-build-fast%5C%22)%22,%22minAlignmentPeriod%22:%2260s%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22groupByFields%22:%5B%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%226h%22%7D%7D)
  - is the job wildly underutilizing its CPU limit? if so, perhaps tune down (if uncertain, post evidence in this issue and ask)
  - (it will probably be helpful to look at different time resolutions like 1h, 6h, 1d, 1w)
- [metrics explorer: Memory limit utilization for `ci-kubernetes-build-fast` for 6h](https://console.cloud.google.com/monitoring/metrics-explorer?authuser=1&project=k8s-infra-prow-build&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22kubernetes.io%2Fcontainer%2Fmemory%2Flimit_utilization%5C%22%20resource.type%3D%5C%22k8s_container%5C%22%20metadata.user_labels.%5C%22prow.k8s.io%2Fjob%5C%22%3Dmonitoring.regex.full_match(%5C%22ci-kubernetes-build-fast%5C%22)%22,%22minAlignmentPeriod%22:%2260s%22,%22unitOverride%22:%221%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22groupByFields%22:%5B%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%226h%22%7D%7D)
  - is the job wildly underutilizing its memory limit? if so, perhaps tune down (if uncertain, post evidence in this issue and ask)
  - (it will probably be helpful to look at different time resolutions like 1h, 6h, 1d, 1w)

Things to watch for the build cluster
- [prow-build dashboard 1w](https://console.cloud.google.com/monitoring/dashboards/custom/10925237040785467832?project=k8s-infra-prow-build&timeDomain=1w)
  - is the build cluster scaling as needed? (e.g. maybe it can't scale because we've hit some kind of quota)
  - (it will probably be helpful to look at different time resolutions like 1h, 6h, 1d, 1w)
- [prowjobs-experiment 1w](https://console.cloud.google.com/monitoring/dashboards/custom/10925237040785467832?project=k8s-infra-prow-build&timeDomain=1w)
  - (shows resource consumption of all job runs, pretty noisy but putting this here for completeness)
- https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1

Keep this open for at least 24h of weekday PR traffic.  If everything continues to look good, then this can be closed.

/wg k8s-infra
/sig testing
/area jobs

**Comment by spiffxp** [comment]
/sig release
FYI @kubernetes/release-engineering

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/19487 created a canary job

Next steps to take are spelled out in https://github.com/kubernetes/k8s.io/issues/846#issuecomment-705722852

Is the job working?  If so, it's time to switch other jobs to use the new path

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-release-master-informing#build-master-fast-canary&graph-metrics=test-duration-minutes&width=5 is green, and its durations are comparable to https://testgrid.k8s.io/sig-release-master-blocking#build-master-fast&graph-metrics=test-duration-minutes&width=5

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/19620 updated kubetest to add a `--extract-ci-bucket` flag

https://github.com/kubernetes/test-infra/pull/19632 updates a job to use the new kubetest without the flag to verify nothing breaks

Next PR will add `--extract-ci-bucket k8s-release-dev` to migrate a job to use the results of the canary job added in https://github.com/kubernetes/test-infra/pull/19487

**Comment by spiffxp** [comment]
Now that https://github.com/kubernetes/test-infra/pull/19634 has confirmed the new bucket works, we should migrate any jobs that use `--extract=ci/latest-fast` using the same approach.

Then confirm migrated jobs still work.

Then delete the original job and rename the canary.

Then this is done

**Comment by cpanato** [comment]
@spiffxp I will update the ci-kubernetes-build-fast job

**Comment by cpanato** [comment]
@spiffxp I will update the ci-kubernetes-build-fast job

**Comment by justaugustus** [comment]
/reopen

Reopening this to keep an eye on it, given https://github.com/kubernetes/test-infra/pull/19841.
/assign @justaugustus @cpanato

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/pull/19871 to enforce jobs should be using the k8s-release-dev bucket if they're using `ci/latest-fast`; caught one outlier

I'm ready to call this done unless there are any remaining concerns

**Comment by spiffxp** [comment]
/close
There have been no concerns raised
