### ISSUE TITLE
Mentioning an issue or PR id in the title of a different PR creates merge problems

### ISSUE THREAD

**Issue by sftim** [kubernetes/test-infra#19492]
**What happened**:
@annajung [mentioned](https://github.com/kubernetes/test-infra/issues/17893#issuecomment-702216428) that issue and PR numbers in PR titles cause problems for SIG Docs' release team.

**What you expected to happen**:
It should not be possible to command Prow to create a commit that Prow then considers unacceptable. Alternatively, it _is_ possible but you have to explicitly opt-in to the problem.

**How to reproduce it (as minimally and precisely as possible)**:
(untested)
Start from the _master_ branch
Create a new branch with changes and create a pull request targeting _master_
Ensure that the title (not commit message, title) of the PR includes a `#` followed by numbers, that Prow will later reject as looking like an issue or PR number if that commit is merged back in.

**Please provide links to example occurrences, if any**:
https://github.com/kubernetes/website/pull/24408#event-3850971874

**Anything else we need to know?**:
Seen on [k/website](https://github.com/kubernetes/website) during a merge into the branch for the upcoming (v1.20) release.

/area prow
/kind bug
This is split off from #17893

**Comment by sftim** [comment]
PR #19491 covers similar ground

**Comment by nikhita** [comment]
I'll cover this in https://github.com/kubernetes/test-infra/pull/19491 :smile: 

/assign
