### ISSUE TITLE
Prow job pages don't load properly when opened in the background

### ISSUE THREAD

**Issue by bgilbert** [kubernetes/test-infra#19499]
**What happened**:

When I open multiple Prow job pages in background tabs, and then switch to them later, the job info has not loaded.

![image](https://user-images.githubusercontent.com/361374/95504284-8fe8f080-097a-11eb-8f40-3668fac349ec.png)

**What you expected to happen**:

Job details load properly.

**How to reproduce it (as minimally and precisely as possible)**:

Control-click [this link](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/1314172806597971968) multiple times, wait for the tabs to finish loading, then switch to them.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

This is consistently reproducible on my Fedora 31 system, in Firefox but not in Chrome.  Reloading the page in the foreground causes it to load successfully.

**Comment by stevekuznetsov** [comment]
I swear we had this reported before, too -- it's only on Fedora IIRC and nobody had any clue as to why this happened. cc @alvaroaleman @Katharine

**Comment by alvaroaleman** [comment]
This only happens in firefox and not in chrome.

**Comment by bgilbert** [comment]
Still happening.

/remove-lifecycle stale

**Comment by bgilbert** [comment]
Still happening on Firefox 86.

/remove-lifecycle stale

**Comment by LorbusChris** [comment]
still happening with Firefox 88

/remove-lifecycle stale

**Comment by bgilbert** [comment]
This seems to be fixed for me in Firefox 94 on Fedora 35.

**Comment by petr-muller** [comment]
Wow. YES! This really looks fixed!

**Comment by LorbusChris** [comment]
Can confirm as well! :tada:

**Comment by bgilbert** [comment]
Awesome!  I'll close this out.
