### ISSUE TITLE
Plank errors listing pods cause plank to try to recreate pods for all running ProwJobs.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#19534]
**What happened**:
Plank failed to list pods and proceeded to try to create a pod for every running ProwJob that it failed to list pods for. This resulted in many `pod <pod-name> already exists` errors.

**What you expected to happen**:
If Plank fails to list pods for a build cluster, ProwJobs from that build cluster should be ignored for that sync loop.

/help

**Comment by cjwagner** [comment]
> We could add a check to only create pods when getting them before that returns a 404? The cache not being synced returns a distinct error.

That sounds sensible to me.

**Comment by matthyx** [comment]
No longer an issue with the `prow-controller-manager`.
/close
