### ISSUE TITLE
Spyglass page keeps spinning when it loads an extra large buildlog file

### ISSUE THREAD

**Issue by chizhg** [kubernetes/test-infra#19555]
**What happened**:
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_serving/9790/pull-knative-serving-istio-stable-no-mesh/1315859761295527938 keeps spinning when it tries loading the buildlog file. From the debug window, the request is returning a 502 error:
![image](https://user-images.githubusercontent.com/19399934/95909009-aadcab80-0d52-11eb-8718-9c81220fdcad.png)

**What you expected to happen**:
It should either be able to load the buildlog, or give an explicit message that the buildlog could not be loaded due to some reason.

**How to reproduce it (as minimally and precisely as possible)**:
Try opening https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_serving/9790/pull-knative-serving-istio-stable-no-mesh/1315859761295527938 in the browser.

**Anything else we need to know?**:
1. The build-log.txt file is pretty large (more than 150MB) - https://storage.googleapis.com/knative-prow/pr-logs/pull/knative_serving/9790/pull-knative-serving-istio-stable-no-mesh/1315859761295527938/build-log.txt
2. The Spyglass `size_limit` for Knative Prow is set to `500MB` - https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/knative/config.yaml#L54, so it shouldn't be bounded by the size limit setting.

/help
/kind bug

**Comment by vicsufer** [comment]
May I give this a try even if this is not a good-first-issue? @BenTheElder @chizhg

**Comment by chizhg** [comment]
Sure, pleas feel free to pick it up. Thanks @vicsufer !

cc @e-blackwelder for awareness here.

**Comment by vicsufer** [comment]
Hi @chizhg @e-blackwelder, I opened the link from prow.knative.dev and indeed the build-log.txt isn't showed in the spyglass. However I'm not being able to reproduce this behavior using prow as it is setup in this repository.

First I've used prow.k8s.io as a passthrough to the mentioned  build-log.txt and, the log doen't show but neither does the spinner, so the log surpassing the maxSize is correctly detected. https://prow.k8s.io/view/gs/knative-prow/pr-logs/pull/knative_serving/9790/pull-knative-serving-istio-stable-no-mesh/1315859761295527938

I've also built this repository in my local and increase the maximum size configuration, and it seems to work.

I've tested this with Chromium and Firefox, can you provide some details about the browser you use?

My guesses are that there are some changes in between this repository and the running prow in knative, or it is browser related. If it its one of these I'm not sure if I'll be suitable to help further.

**Evidences:**
**_Using prow.k8s.io as a passthrough with not increased size:_**
![image](https://user-images.githubusercontent.com/15276132/97219674-9a084d00-17ca-11eb-866d-2e5790a70efe.png)
**_Using localhost to increase max-size:_**
![image](https://user-images.githubusercontent.com/15276132/97219333-25cda980-17ca-11eb-904a-742b84ee6432.png)

**Comment by chizhg** [comment]
Hi @vicsufer , thanks for the investigations here! And sorry for the late response.

I did some test, it looks the reason for the difference between Knative and k8s Prow is Knative Prow is setting the size_limit as [500MB](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/knative/config.yaml#L54), while k8s Prow is setting it as [100MB](https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L46). If I change the size_limit for Knative Prow also to 100MB, it will have the same behavior.

**Comment by BenTheElder** [comment]
500MB is ... quite a lot?
Improving the behavior here sounds nice but I'd probably be inclined to suggest looking at why the log is so enourmous first tbh.

**Comment by chizhg** [comment]
We've already reduced the log size a lot for Knative, so it's not an issue for Knative now.
