### ISSUE TITLE
TODOs for sig-auth-serviceaccount-admission-controller-migration upgrade test 

### ISSUE THREAD

**Issue by zshihang** [kubernetes/test-infra#19575]
**What should be cleaned up or changed**:

- use sig auth mailing list as `testgrid-alert-email`
- use release/stable-x.y as extracts
- lower frequency to 1/day

**Provide any links for context**:

**Comment by BenTheElder** [comment]
still TODO?

**Comment by liggitt** [comment]
yup - https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-auth/serviceaccount-admission-controller-migration-config.yaml
