### ISSUE TITLE
Remove the dependency on knative.dev/pkg

### ISSUE THREAD

**Issue by slinkydeveloper** [kubernetes/test-infra#19583]
**What should be cleaned up or changed**:

This module has a dependency on knative.dev/pkg, generating a circular dependency in knative dependency tree:

> knative.dev/pkg -> knative.dev/test-infra -> k8s.io/test-infra -> knative.dev/pkg

We should look at removing it, since this is causing issues with our go mod resolution

**Provide any links for context**:

* Usage: https://github.com/kubernetes/test-infra/search?q=knative.dev%2Fpkg
* test-infra issue: https://github.com/knative/test-infra/issues/2414

/assign

**Comment by howardjohn** [comment]
I vaguely recall looking into this and while the usage seems minimal there are also major indirect dependencies on it. I could be remembering wrong though.

**Comment by slinkydeveloper** [comment]
Yeah it seems minimal. I'm gonna try to remove it, let's see what comes out of it

**Comment by howardjohn** [comment]
What I mean is even if you remove it from the go.mod, the go.mod imports tekton which imports knative so it will still be imported

**Comment by slinkydeveloper** [comment]
Ah I didn't get it, so we have this cycle too?

> knative.dev/pkg -> knative.dev/test-infra -> k8s.io/test-infra -> github.com/tektoncd/pipeline -> knative.dev/pkg

**Comment by slinkydeveloper** [comment]
/unassign

I think we solved the dependency cycle from the knative side, somebody can confirm?

**Comment by alvaroaleman** [comment]
@slinkydeveloper how was it solved on knative side?

**Comment by slinkydeveloper** [comment]
pkg doesn't depend on test-infra anymore

**Comment by alvaroaleman** [comment]
Ok, I can not verify that for you but I have no reason not to believe that. This doesn't actually fix the issue as titled, but seems it obsoletes it, I'll close it anyways (feel free to reopen if you disagree).

/close
