### ISSUE TITLE
Verify-owners plugin does not remove the do-not-merge label if PR is updated to remove all OWNERS files.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#19607]
**What happened**:
1. A PR included the creation of some invalid OWNERS files (approvers who were not members).
1. The [verify-owners](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/verify-owners) plugin added the `do-not-merge/invalid-OWNERS-file`
1. The PR was updated to remove all the OWNERS files.
1. The verify-owners plugin did not remove the do-not-merge label because there were no OWNERS file changes in the PR so it never ran validation.

**What you expected to happen**:
PRs that have the `do-not-merge/invalid-OWNERS-file` label should always be validated by the verify-owners plugin when they change even if they no longer have OWNERS file changes so that we can remove the do-not-merge label when needed.

**Please provide links to example occurrences, if any**:
https://github.com/GoogleCloudPlatform/oss-test-infra/pull/554#issuecomment-710343565

/help
/good-first-issue

**Comment by matthyx** [comment]
Oh wow, never thought about that one...
@joostas let me know if you need a hand at this one!

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/19691
/close
