### ISSUE TITLE
Only notify final test failure to PR author, not every participant

### ISSUE THREAD

**Issue by resouer** [kubernetes/test-infra#1962]
Now we have k8s-ci-robot which can generate a nice `test(s) failed` matrix, this is great. 

But another issue I can see here is when tests fail, all participants of this PR will continually receive notification email per test failure until all tests passed.  

**The problem:**

This makes:
1. Reviewers feel annoyed.
2. PR authors have to manually ping reviewers back since all their previous discussion will be drowned by those test failure mails.

This problem get worse when reviewers are rely on emails to manager their reviews. (which is the common case AFIK)

**What I suggest:**

1. Only sent out a "final" result of tests failure matrix, instead of one email per test failure.
2. (Better) Only sent out (1) email to PR author, reviewers has no reason to care the test failures.
3. (Optional) Automatic ping reviewers back when all tests have passed

**Comment by spxtr** [comment]
Lets continue discussing in #1723.
