### ISSUE TITLE
Allow setting draft status via Prow

### ISSUE THREAD

**Issue by sftim** [kubernetes/test-infra#19627]
**What would you like to be added**:
I'd like approvers (maybe reviewers too?) to be able to ask Prow to convert a PR to draft

**Why is this needed**:
In [k/website](https://github.com/kubernetes/website), SIG Docs sees a pattern each release cycle where people open placeholder PRs that are marked as placeholders in the PR title and description, but that's not copied to metadata (GitHub API, and labels) because to GitHub and Prow that's a valid PR ready for review.

To make it easier to distinguish reviewable PRs from those that are still WIP, allow people to tell Prow to mark the PR as draft (which will then also add the WIP label).

This is a nice-to-have enhancement, it's not vital.

**Comment by matthyx** [comment]
@BenTheElder do you see it with a `/draft` comment?

**Comment by BenTheElder** [comment]
@matthyx I have no opinion on this and I haven't really worked on prow much for for some time (@cjwagner's team owns prow on the google side). Labeling this issue as area/prow actually allows me to more narrowly review issues I might be more likely to work on 🙃

**Comment by MushuEE** [comment]
Actually doesn't look like even the v4 GraphQL has the option yet to support updating PR to draft:  You can only [create](https://docs.github.com/en/free-pro-team@latest/graphql/reference/input-objects#createpullrequestinput) one as draft via API

[Update](https://docs.github.com/en/free-pro-team@latest/graphql/reference/input-objects#updatepullrequestinput)
