### ISSUE TITLE
Add configuration for prow plugin's respond

### ISSUE THREAD

**Issue by hi-rustin** [kubernetes/test-infra#19629]
**What would you like to be added**:
Could we add some configurations to the https://github.com/kubernetes/test-infra/blob/6ad9eb5f38fc7ca9867b2700f1eced5a2e5454ff/prow/plugins/respond.go#L30

and 

https://github.com/kubernetes/test-infra/blob/6ad9eb5f38fc7ca9867b2700f1eced5a2e5454ff/prow/plugins/respond.go#L27

**Why is this needed**:

Because I want to use these plugins in my project or community, but we have different links and documentation. So I hope it can be a config.

If this is possible, I would be happy to help.

**Comment by hi-rustin** [comment]
@BenTheElder  @fejta @stevekuznetsov  Do you have any suggestions?

**Comment by BenTheElder** [comment]
Some similar messages have been made configurable before but the decision is up to the prow owners https://github.com/kubernetes/test-infra/blob/master/prow/OWNERS

**Comment by matthyx** [comment]
@hi-rustin this is not quite as easy as it sounds...
These 2 are consts defined for the whole prow plugins, so if you want to make them configurable they need to be parameterized in `test-infra/prow/plugins/config.go` with a default value reflecting the current links.
As @BenTheElder said, some plugins have this link configurable (like `approve`) and therefore you will have to migrate by supporting both configs for a while and then finally only use the common one.
You can work on that if you want, I can help you.
/assign @hi-rustin

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/19965 is this sufficient?

**Comment by hi-rustin** [comment]
> #19965 is this sufficient?

It feels like all the plugins have to be modified, and I want to put the configuration in config and pass it to each plugin to use. I don't know if this is possible?

**Comment by BenTheElder** [comment]
I think the ones in the issue body were done, as for others I don't see why not but I won't personally be approving them.

**Comment by hi-rustin** [comment]
@fejta @alvaroaleman  What do you think?

**Comment by hi-rustin** [comment]
> as for others I don't see why not but I won't personally be approving them (see prow OWNERS)

Because contributors may open detail, they will be directed to https://go.k8s.io/bot-commands. But may actually use not k8s prow but their own deployment.
