### ISSUE TITLE
status-reconciler triggers new jobs that would not be triggered because of `run_if_changed`

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/test-infra#19642]
**What happened**:

We had a user reporting that a job does not trigger on a PR while being triggered before. We discovered the [job has a restrictive regex in run_if_changed](https://github.com/openshift/release/blob/db2a0b6a118789e94004cdbd348cd8b933f693e0/ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml#L856) `^(openshift-hack/images/hyperkube)$` which rules out the  actually changed file `openshift-hack/images/hyperkube/Dockerfile.rhel` so the job was not triggered correctly.

After that, we discovered that `status-reconciler` was the thing that once triggered the test on the PR, apparentlyu not respecting the `run_if_changed` regex after the [PR](https://github.com/openshift/release/pull/12618) adding the job merged:

```json
{
   "client":"trigger",
   "component":"status-reconciler",
   "container_name":"statusreconciler",
   "file":"prow/plugins/trigger/trigger.go:294",
   "func":"k8s.io/test-infra/prow/plugins/trigger.RunRequested",
   "host":"ip-10-0-128-213",
   "level":"info",
   "msg":"Starting pull-ci-openshift-kubernetes-master-e2e-azure-upgrade build.",
   "multiline_tag":"F",
   "object_uid":"fb5d6784-5c6c-4add-a9cb-0537d04c0fb5",
   "pod_name":"statusreconciler-784ff5b879-ft7wt",
   "pod_namespace":"ci",
   "severity":"info",
   "source_type":"kubernetes",
   "stream":"stderr",
   "time":"2020-10-14T10:53:29Z"
}
```

**What you expected to happen**:
Jobs to be triggered by status-reconciler only on PRs that would trigger them automatically.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
Since we may care more about status-reconciler issues in the context of renaming jobs to follow github branch renames (ref: https://github.com/kubernetes/org/issues/2222#issuecomment-769195281)

**Comment by spiffxp** [comment]
/sig testing
/remove-lifecycle rotten
/reopen
AFAIK this is still an issue
