### ISSUE TITLE
metadata and output of ci-audit-kind-conformance job should match structure of existing e2e test run jobs

### ISSUE THREAD

**Issue by zachmandeville** [kubernetes/test-infra#19658]
**What happened**:
A new test run job has been created here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-audit-kind-conformance
It's intended to be mostly similar to the job [ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce), but running kind and with adjustments to its audit policy to include endpoints skipped in this latter job. 

While setup differently, the structure of its output is meant to be the same, so that  tools like APISnoop can pull in audit logs from this new job to get a more comprehensive view of conformance coverage.

Currently, there are missing or incomplete files in this new job so that it's structure is noticeably different from the standard run.  This blocks APISnoop from pulling in its logs, and signals that the output of the job is not matching its intention.

**What you expected to happen**:
- a **JobResultsCache.json should be included** in the storage bucket holding the output of the test runs.
- in the output of a job, its **finished.json should include metadata**
 
**How to reproduce it (as minimally and precisely as possible)**:
- Visit the list of job runs on prow, and click  a successful one
   - [job runs of ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce)
   - [job runs of new ci-audit-kind-confomrance](https://prow.k8s.io/job-history/kubernetes-jenkins/logs/ci-audit-kind-conformance)
- compare the list of files generated between successful jobs in the respective buckets.  Links to useful examples are included below.

- **jobResultsCache.json**
  - [example from ci-kubernetes-e2e-gci-gce](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/jobResultsCache.json)
  - [404 from ci-audit-kind-conformance](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-audit-kind-conformance/jobResultsCache.json)
- **finished.json**
   - [...gci-gce example](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1318989898744598528/finished.json)
   - [audit-kind-conformance example](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-audit-kind-conformance/1318743775454957568/finished.json)

**Comment by BenTheElder** [comment]
This is the difference between the deprecated jenkins/bootstrap.py and the prow/ pod-utilities (`decorate: true`). Relying on jobResultsCache and the additional data in finished.json is not supported.

**Comment by hh** [comment]
Is there a way to port this feature from `jenkins/bootstrap.py` or is it an architectural change?

**Comment by hh** [comment]
The main use case for us currently is being able to detect the latest successful job run.
Is there another way to retrieve this info?
