### ISSUE TITLE
pull-test-infra-bazel broken

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#19662]
Related: https://github.com/bazelbuild/continuous-integration/issues/1055

**What happened**:

pull-test-infra-bazel permanently fails with:
```
ERROR: /home/prow/go/src/github.com/kubernetes/test-infra/hack/BUILD.bazel:16:1:  failed (Exit 34): UNAVAILABLE: HTTP/2 error code: NO_ERROR
```

Samples:
* https://github.com/kubernetes/test-infra/pull/19647
* https://github.com/kubernetes/test-infra/pull/19655
* https://github.com/kubernetes/test-infra/pull/19659

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by rifelpet** [comment]
[My PR](https://prow.k8s.io/pr-history/?org=kubernetes&repo=test-infra&pr=19652) was failing with this same issue about 15 hours ago. Retrying it now and it appears to be [stuck](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/19652/pull-test-infra-bazel/1319254306397884416).

There are other PRs with [jobs in the same state](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/19656/pull-test-infra-bazel/1319239467524952064) as well.

**Comment by thejoycekung** [comment]
Similar issues happening for the `periodic-kubernetes-bazel-build-master` job - kubernetes#95795

**Comment by fejta** [comment]
This looks related to RBE. One option is to reduce paralleism. A second is to turn off RBE. Going to try out both approaches.

**Comment by spiffxp** [comment]
FWIW

**pull-test-infra-bazel** uses RBE (but perhaps without a remote cache)
- first failing job started 2020-10-21 20:39 UTC (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/19651/pull-test-infra-bazel/1319015417548640256)
- pull-test-infra-bazel runs in the default build cluster (there is no `cluster:` field)
- the --config=ci flag here... https://github.com/kubernetes/test-infra/blob/d0a341486174028a3f6267cbad5e4a40d45758dc/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L18
- means these bazel settings should be used... https://github.com/kubernetes/test-infra/blob/d0a341486174028a3f6267cbad5e4a40d45758dc/.bazelrc#L23-L71
- which means bazel ends up using RBE (though it does not have a `remote_cache` setting)

**periodic-kubernetes-bazel-build-master** uses RBE (with an RBE-provided remote cache)
- first failing job started 2020-10-21 20:20 UTC (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-build-master/1319010405707681792)
- periodic-kubernetes-bazel-build-master also runs in default
- also sets a --config=ci flag here... https://github.com/kubernetes/test-infra/blob/3d3b325c98b739b526ba5d93ce21c90a05e1f46d/config/jobs/kubernetes/sig-testing/bazel-build-test.yaml#L180
- which uses these bazel settings... https://github.com/kubernetes/kubernetes/blob/ededd08ba131b727e60f663bd7217fffaaccd448/build/root/.bazelrc#L55-L90
- which means bazel ends up using RBE

**pull-kubernetes-bazel-build** uses RBE
- first failing job started 2020-10-21 20:28 UTC (https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-bazel-build/1319012327537774592)

**periodic-kubernetes-bazel-test-master** does not use RBE
- has remained passing
- another difference: runs in k8s-infra-prow-default cluster

**Comment by fejta** [comment]
Here is the RBE issue to follow: https://github.com/bazelbuild/continuous-integration/issues/1055

**Comment by BenTheElder** [comment]
still broken, but seems to be a different issue https://github.com/kubernetes/test-infra/issues/19667
