### ISSUE TITLE
Document Approvers/Owners Process

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#1966]
Need some longterm explanation of how to add approvers and reviewers and who can approve.

(A lot can be reused from the design document)

**Comment by spiffxp** [comment]
For reference, where's the design doc?  Most I could find from a cursory google was https://github.com/kubernetes/community/blob/master/contributors/devel/owners.md

**Comment by grodrigues3** [comment]
Shared with kubernetes-dev. 

https://docs.google.com/document/d/1xmAa6ZyRiHiubWdJumO2wKRiz0zyMxHkgT65Qf0njts/edit#

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/approvers/README.md

**Comment by spiffxp** [comment]
approval now also requires a linked issue: https://github.com/kubernetes/test-infra/issues/2868

**Comment by spiffxp** [comment]
PR docs currently don't reference need for linked issue: https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md

**Comment by kargakis** [comment]
cc: @stevekuznetsov

**Comment by spiffxp** [comment]
https://github.com/kubernetes/community/pull/873

**Comment by spiffxp** [comment]
Calling this done with the linked PR
