### ISSUE TITLE
Pod-Util BQ job supported flake query

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19666]
**What would you like to be added**:
Current [flake queries](https://github.com/kubernetes/test-infra/blob/master/metrics/configs/flakes-config.yaml) exclude pod-utils job recently added to BQ by kettle. The query needs to be updated to support fetching of not only past jobs but new `bootstrap` jobs and new `decorated` jobs. 

**Why is this needed**:
As a follow up to #19592. Without adding this feature there is no visibility into metric on Pod-Util jobs which is the new conical job type (post bootstrap deprecation). 

# Notes + TODO:
The current flake query involves four stages of queries
> From inside create [
>- job,
>- build_consistency (percentage of runs that did not flake),
>- commit_consistency (percentage of commits that did not flake),
>- flakes (times job flaked),
>- runs (times job ran),
>- commits (commits tested),
> -tests (array of flaked tests in the job)]
>> From inside create [
>>- job, 
>>- commit, 
>>- flaked (if not all passed), 
>>- passed, runs (as int), 
>>- tests (ordered by number of failures)]
>>> From inside create [
>>>- job, 
>>>- commit, 
>>>- sum(`SUCCESS` result), 
>>>- count (all result), 
>>>- tests (array of all tests)]
>>>>Select from the week table where `version` (null for decorated) is not 'unknown' AND (ci job OR it was a serial PR job as is defined by `repos`) AND in last 7 days. ![image](https://user-images.githubusercontent.com/7189267/96927902-a27c2300-146c-11eb-9dbe-bdaa87f1ef36.png) Create something of the following:
>>>>- job, 
>>>>- kind(`pull` or `ci`, version (needs to be updated for both version and repo_commit (decorated), 
>>>>- commit (hash pulled from repos or version), 
>>>>- result, 
>>>>- test (tuple of tests)]

  
Some of these fields exist in `decorated` and not in `bootstrap` and vice versa. All need jobs being updated (new kettle)
- [x] TODO: Update Production Kettle now that staging is stable and tested

Because old jobs will not be updated with new fields, the query must support BOTH old schema and new [schema](https://github.com/kubernetes/test-infra/blob/master/kettle/schema.json) with respective fields being updated from the two job types.
- [x] TODO: Breakdown the current query elements and validate that they collect both `decorated` and `bootstrap` jobs and pass them up the query chain as expected. (You might want to pick a job of each type and start with those to validate each step without to much noise from other jobs) 

/assign
/area kettle
/area metrics
/cc @spiffxp @BenTheElder @amwat @cjwagner

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/14643 for umbrella / parent issue

**Comment by MushuEE** [comment]
Example Pod-Util Flake: [ci-test-infra-bazel](https://github.com/kubernetes/test-infra/blob/f27a4061f856cde48a7f1f6e51af66c87fe569a3/config/jobs/kubernetes/test-infra/test-infra-periodics.yaml#L2)
[Prow](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-test-infra-bazel)

Example Bootstrap Flake: [ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://github.com/kubernetes/test-infra/blob/3d3b325c98b739b526ba5d93ce21c90a05e1f46d/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L607) <- Example of job with no Repo_commit or repo
[Prow](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-defaul)

These will be the two jobs I build the new query around to validate they both bubble up.
