### ISSUE TITLE
Kettle new xml parse traceback on 'testsuite" tag

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19682]
**What happened**:
Prod Kettle 10/25: 
```
ERROR:root:error on gs://kubernetes-jenkins/pr-logs/pull/81478/pull-kubernetes-e2e-gce-rbe/1162056366320259075
Traceback (most recent call last):
  File "make_json.py", line 282, in make_rows
    yield rowid, row_for_build(path, started, finished, results)
  File "make_json.py", line 222, in row_for_build
    for test in parse_junit(result):
  File "make_json.py", line 187, in parse_junit
    name = child.attrib['name']
KeyError: 'name'
```
**What you expected to happen**:
No traceback on this form of xml. When I try to access this data I get:
```
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/81478
```
>failed to get job history: failed to locate build data: failed to read pr-logs/directory/81478/latest-build.txt: creating reader for object pr-logs/directory/81478/latest-build.txt: storage: object doesn't exist

Seems that job no longer exists. This causes kettle to hang.
**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
/area kettle
/assign

**Comment by spiffxp** [comment]
Maybe related: I see nothing in testgrid for this job? https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-rbe

**Comment by MushuEE** [comment]
> Maybe related: I see nothing in testgrid for this job? https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-rbe

Seems like I can't even find that job in prow anymore.

**Comment by MushuEE** [comment]
Maybe after https://github.com/kubernetes/test-infra/pull/18027, they stopped running and the results have timed out? @BenTheElder

**Comment by spiffxp** [comment]
I think the testgrid issue is related but orthogonal, turns out there are more jobs affected, so I opened https://github.com/kubernetes/test-infra/issues/19696
