### ISSUE TITLE
Certain kubernetes presubmit jobs are missing testgrid results

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#19696]
**What happened**:

The following tabs in https://testgrid.k8s.io/presubmits-kubernetes-blocking have no results:
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce-100-performance
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-node-e2e
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce-network-proxy-http-connect
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce-ubuntu-containerd

However:
- the summary tab lists a non-zero number of columns and cells for these jobs https://testgrid.k8s.io/presubmits-kubernetes-blocking#Summary
- prow's history view for e.g. pull-kubernetes-node-e2e shows successful runs https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e
- other testgrid tabs do display results, e.g. https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind

**What you expected to happen**:

Results to appear on testgrid

**How to reproduce it (as minimally and precisely as possible)**:

Visit any of the above links

**Please provide links to example occurrences, if any**:

See above

**Anything else we need to know?**:

~I suspect this may be related to requiring or assuming that JUnit testsuites have a name attribute~

EDIT: This appears to be an issue with the new golang-based updater (ref: https://github.com/GoogleCloudPlatform/testgrid/issues/211)

The workaround for now is to add `&grid=old` to the end of a dashboard link, e.g. https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&grid=old

/area testgrid
/area prow

**Comment by spiffxp** [comment]
e.g. https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/91592/pull-kubernetes-node-e2e/1320790491167461376/artifacts/junit_runner.xml this testsuite doesn't have a `name` attribute

**Comment by MushuEE** [comment]
Job history here looking scary....
![image](https://user-images.githubusercontent.com/7189267/97354021-08442280-1852-11eb-9d53-41370e693129.png)

**Comment by MushuEE** [comment]
#19721

**Comment by spiffxp** [comment]
Unfortunately #19787 hasn't fixed it.  It may be that bad data needs to age out of the 14 day window, but I'd rather we make our code resilient to bad data if that's the case.

Known good: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind - expect non-empty, get non-empty
![Screen Shot 2020-11-04 at 9 06 34 PM](https://user-images.githubusercontent.com/49258/98188764-a040ac80-1ee1-11eb-947c-d9f1773edb33.png)
expect non-zero summary, get non-zero summary
![Screen Shot 2020-11-04 at 9 08 03 PM](https://user-images.githubusercontent.com/49258/98188869-d4b46880-1ee1-11eb-9515-f23de95ec0f6.png)

Known bad: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-node-e2e - expect non-empty, get empty
![Screen Shot 2020-11-04 at 9 07 31 PM](https://user-images.githubusercontent.com/49258/98188831-c23a2f00-1ee1-11eb-8be3-b748ebb5a62e.png)
expect non-zero summary, get non-zero summary
![Screen Shot 2020-11-04 at 9 07 47 PM](https://user-images.githubusercontent.com/49258/98188851-cb2b0080-1ee1-11eb-9dc1-46ef9bf98b3d.png)

Since the summary is non-zero, I think the next step would be to track down logs for the updater testgrid component.

@michelle192837 @fejta any ideas?

**Comment by spiffxp** [comment]
Test results do show up in https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-node-e2e&grid=old

Test results are missing from https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-node-e2e&grid=beta

**Comment by spiffxp** [comment]
Looks like this is a problem with the new updater https://github.com/GoogleCloudPlatform/testgrid/issues/211

**Comment by michelle192837** [comment]
From quick investigation, I'm not seeing any obvious errors in logs; it appears that the state is being processed and written to GCS, it's just got nothing. :/

If Erick doesn't get to this first, I'll try to run this locally with some more debugging to figure out what's going on.

(For the Summary, I'm pretty sure that the Summarizer summarizes based on the old state at the moment, especially since it's used universally now and the OSS Updater is not.)

**Comment by spiffxp** [comment]
/close
All of the example dashboards now display results as expected.  Fixed by https://github.com/GoogleCloudPlatform/testgrid/pull/277
