### ISSUE TITLE
Pod Utilities should collect and upload pod logs as artifacts

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/test-infra#19703]
**What would you like to be added**:

Pod utilities automatically dump all pod specs to artifacts/pods_info. (BTW, I was unable to find the code that does that)
It would be great to have logs for those pods as well.

**Why is this needed**:

This would be really useful for debugging.

**Comment by alvaroaleman** [comment]
> Pod utilities automatically dump all pod specs to artifacts/pods_info

They do? Where?

> It would be great to have logs for those pods as well.

Pod utilities are used to wrap one pod and will upload loads for that one pod

**Comment by Ark-kun** [comment]
I'm sorry. I got confused - it was a feature on our side.
