### ISSUE TITLE
Assess what cmv/gci tests are required for presubmit

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/test-infra#1972]
We have tests for combinations of (gke, gce) and (gci, cvm) in the presubmit suites. Since we have CI coverage for all of them, and rarely a PR would break only cvm or gci, we should consider removing some of them to conserve resources.

/cc @mtaufen @dchen1107 @spxtr

**Comment by spxtr** [comment]
Note that it doesn't just conserve resources, although that's important too. There's also just a baseline flake rate for all e2e suites, and adding new duplicates multiplies the chance of hitting a flake.
