### ISSUE TITLE
preset-e2e-scalability-periodics-master preset could be erroneously pulled into CI jobs for new minor release

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/test-infra#19727]
`preset-e2e-scalability-periodics-master` preset was introduced here:
https://github.com/kubernetes/test-infra/pull/19710/commits/2bc42f63dbbc80c6e20bc5652becdefae66a04b3

When set of jobs for future k8s minor will be created by forking current master jobs, that preset could be pulled in as well which will break assumptions.

Forking during release is done by: https://github.com/kubernetes/test-infra/tree/master/releng/config-forker
with configuration for automatic replacements like `master -> beta` or custom like:
```
    fork-per-release-replacements: "--extract=ci/latest-fast -> --extract=ci/latest-{{.Version}}, gce-100Nodes-master -> gce-100Nodes-{{.Version}}, --repo=k8s.io/perf-tests=master -> --repo=k8s.io/perf-test
``` 

It should be ensured that after such forking, master preset is replaced with specific minor version like `preset-e2e-scalability-periodics-1.20`

/assign @tosi3k 
@wojtek-t

**Comment by tosi3k** [comment]
We'd need to change the forker as well to handle this. Function handling periodics forking currently performs substitutions only for the args of containers included in the job as well as the tags (see https://github.com/kubernetes/test-infra/blob/e77594eb706652194e5aa1c34cdace2ef4ad4cc0/releng/config-forker/main.go#L106,L161)

I see two possible approaches here:
1. modify the logic of `generatePeriodics` function to additionally handle the labels of the job,
2. add logic for field deletions with some `fork-per-release-deletions` annotation handling.

No. 2. is probably a bit more elegant and might become useful in other scenarios in the future as well.
