### ISSUE TITLE
Release Note Matcher Update

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#1974]
Looks like there's one additional case for the release note matcher.
If you click github's button for inserting code, you get:
`NONE`

which looks exactly like

```NONE``` which comes in our issue template, but there are three sets of backticks in our template and only one in the one allowed by github.

Can we update the regex to also match github's single backtick?

Example of it not working.

https://github.com/kubernetes/kubernetes/pull/41660

**Comment by ixdy** [comment]
I think the issue template uses
``` 
```release-note
```
which is subtly different.

The [`relnotes` script](https://github.com/kubernetes/release/blob/master/relnotes) only supports ` ```release-note`, and given that it uses a terrifying few lines of `sed`, would not be easy to fix...

**Comment by rmmh** [comment]
The relnotes script is out of date currently. `release-note-label.go` is what does the labeling, using this regex:

```go
	noteMatcherRE = regexp.MustCompile(`(?s)(?:Release note\*\*:\s*(?:<!--[^<>]*-->\s*)?` + "```(?:release-note)?|```release-note)(.+?)```")
```

I'm willing to punt on this if it's the *only* instance where this occurred.
