### ISSUE TITLE
Prow plugin local test instruction doesn't work

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#19778]
**What happened**:

Followed instruction of testing a plugin locally at https://github.com/kubernetes/test-infra/tree/master/prow/cmd/phony#running-a-github-event-manager. But the following command:

```
go run prow/cmd/hook/main.go
--deck-url=<production deck URL>
--config-path=config/prow/config.yaml
--plugin-config=config/prow/plugins.yaml
--hmac-secret-file=path/to/hmac
--github-token-path=path/to/github-token
```

failed with error:

```
{"component":"unset","error":"no dry-run kubernetes client is supported in dry-run mode","file":"/Users/chaodai/go/src/k8s.io/test-infra/prow/cmd/hook/main.go:169","func":"main.main","level":"fatal","msg":"Error getting Kubernetes client for infrastructure cluster.","severity":"fatal","time":"2020-10-30T08:58:14-07:00"}
```

**What you expected to happen**:

The command runs without problem

**How to reproduce it (as minimally and precisely as possible)**:

Run the `go run` command mentioned above

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

Wondering if it's necessary to use kubeconfig in hook, since hook doesn't alter `hmac-token` secret, can we mount it on hook instead?

**Comment by chaodaiG** [comment]
CC @chizhg

**Comment by chaodaiG** [comment]
Should we just drop the requirement of `dryrun` must resolve kube client? Or somehow improve the workflow to create a kind cluster instead?

+ @alvaroaleman  for thoughts

**Comment by alvaroaleman** [comment]
Not sure, today its just broken. The controller-runtime client has a dry run wrapper, we could replace the current typed clients with it, then this would work again: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/dryrun.go

Just not giving any client will result in panics. We could probably return a fake client as well I guess.
