### ISSUE TITLE
Can we add branch configuration to hook?

### ISSUE THREAD

**Issue by hi-rustin** [kubernetes/test-infra#19795]
**What would you like to be added**:

I hope that `hook` only work on some branches, not all branches by default.

**Why is this needed**:

Maybe a configuration for hook.

**Comment by BenTheElder** [comment]
[area/config is for config/, i.e. our configuration, this is just area/prow]

**Comment by BenTheElder** [comment]
Large amounts of what hook does are not specific to branches at all, I don't think this really makes sense. Specific things e.g. test jobs can be disabled by branch.

**Comment by hi-rustin** [comment]
> Large amounts of what hook does are not specific to branches at all, I don't think this really makes sense. Specific things e.g. test jobs can be disabled by branch.

Got it. Thanks~
