### ISSUE TITLE
Replace merge-blocking needs-foo labels with do-not-merge/needs-foo

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#19805]
**What should be cleaned up or changed**:

There are two benign-looking grey labels that prevent PR's to kubernetes/kubernetes from merging: `needs-kind` and `needs-sig`.  They aren't prefixed with `do-not-merge/` nor are they colored the same red color as other merge-blocking labels.

This can cause contributors to miss the fact that there are yet more labels that need to be added to satisfy merge conditions.  For example, this critical revert PR sat for a few hours https://github.com/kubernetes/kubernetes/pull/96108

We should:
- replace `needs-kind` with `do-not-merge/needs-kind` on PR's, colored the same as other do-not-merge labels
- replace `needs-sig` with `do-not-merge/needs-sig` on PR's, colored the same as other do-not-merge labels
- continue using the non-prefixed labels for issues

The process to roll this out looks like:
- create the new labels for kubernetes/kubernetes, update automation to also exclude the new labels
- update automation to apply the new labels
- manually remove the old labels from PR's
- update any docs that reference `needs-kind` or `needs-sig` in the context of PR's, leave docs alone that mention them in the context of issues

**Provide any links for context**:

**Comment by spiffxp** [comment]
/sig release
since I think release team is the reason these labels are merge-blocking to begin with

**Comment by tpepper** [comment]
Sounds good to me.  More consistent, more visually noticeable.  Still have the problem of people not always being clear on who owns next action fixing toward merge-ability, but that is described by the bot.

**Comment by spiffxp** [comment]
Once https://github.com/kubernetes/test-infra/pull/19827 merges:
- verify new labels have been added (next run of https://testgrid.k8s.io/sig-testing-misc#label_sync)
- remove needs-kind label from PR's to kubernetes
- verify new do-not-merge/needs-kind label is added
- remove needs-sig label from PR's to kubernetes
- verify new do-not-merge/needs-sig label is added
- followup PR: drop needs-kind and needs-sig from tide and fejta-bot queries

**Comment by spiffxp** [comment]
labels have been applied
- https://github.com/kubernetes/kubernetes/pull/96237 - example PR that has red do-not-merge/needs-kind applied from the start
- https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes%2Fkubernetes+author%3Ajingxu97+head%3Anov%2Fkonnect - shows do-not-merge/needs kind as blocking (not red though, I think this won't pick up until a new version of prow is deployed)

**Comment by spiffxp** [comment]
I have manually removed `needs-sig` from a few PR's in kubernetes/kubernetes but it's not clear to be that `do-not-merge/needs-sig` is being appropriately re-applied

**Comment by justaugustus** [comment]
Does the label re-check trigger on comment?

**Comment by spiffxp** [comment]
> Does the label re-check trigger on comment?

Not on comment.  It should be retriggering on label add or remove
https://github.com/kubernetes/test-infra/blob/8d585302d29aa62eb0c5d46ace32447d7563942a/prow/plugins/require-matching-label/require-matching-label.go#L38-L43

But for example I removed needs-sig on https://github.com/kubernetes/kubernetes/pull/95266 30min and the new label hasn't been added.

I can see the new labels are getting added/removed appropriately for new PRs.

I will sweep through manually for now so as not to block PR's that have added `kind/` or `sig/` labels but aren't seeing their `needs-kind` or `needs-sig` labels removed.

**Comment by spiffxp** [comment]
`needs-sig`
- [kubernetes/kubernetes open PRs with `needs-sig` that should have `do-not-merge/needs-sig` instead](https://github.com/kubernetes/kubernetes/pulls?q=label%3Aneeds-sig+-label%3Ado-not-merge%2Fneeds-sig+is%3Aopen+sort%3Aupdated-desc+-label%3Acommittee%2Fcode-of-conduct+-label%3Acommittee%2Fsteering+-label%3Acommittee%2Fproduct-security+-label%3Asig%2Fapi-machinery+-label%3Asig%2Fapps+-label%3Asig%2Farchitecture+-label%3Asig%2Fauth+-label%3Asig%2Fautoscaling+-label%3Asig%2Fcli+-label%3Asig%2Fcloud-provider+-label%3Asig%2Fcluster-lifecycle+-label%3Asig%2Fcontributor-experience+-label%3Asig%2Fdocs+-label%3Asig%2Finstrumentation+-label%3Asig%2Fmulticluster+-label%3Asig%2Fnetwork+-label%3Asig%2Fnode+-label%3Asig%2Frelease+-label%3Asig%2Fscalability+-label%3Asig%2Fscheduling+-label%3Asig%2Fsecurity+-label%3Asig%2Fservice-catalog+-label%3Asig%2Fstorage+-label%3Asig%2Ftesting+-label%3Asig%2Fui+-label%3Asig%2Fusability+-label%3Asig%2Fwindows+-label%3Awg%2Fapi-expression+-label%3Awg%2Fiot-edge+-label%3Awg%2Fk8s-infra+-label%3Awg%2Fmultitenancy+-label%3Awg%2Fnaming+-label%3Awg%2Fpolicy+-label%3Awg%2Fresource-management+-label%3Awg%2Fcomponent-standard+) - apply `do-not-merge/needs-sig` and remove `needs-sig`
- [kubernetes/kubernetes open PRs that have `needs-sig`](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aopen+label%3Aneeds-sig) - thanks to the above, these are known to have a `sig/`,`wg/` or `committee/` label so do not need `do-not-merge/needs-sig`; just remove `needs-sig`

**Comment by spiffxp** [comment]
`needs-kind`
- [kubernetes/kubernetes open PRs with `needs-kind` that should have `do-not-merge/needs-kind` instead](https://github.com/kubernetes/kubernetes/pulls?q=label%3Aneeds-kind+-label%3Ado-not-merge%2Fneeds-kind+is%3Apr+is%3Aopen+sort%3Aupdated-desc+-label%3Akind%2Fapi-change+-label%3Akind%2Fbug+-label%3Akind%2Fcleanup+-label%3Akind%2Fdeprecation+-label%3Akind%2Fdesign+-label%3Akind%2Fdocumentation+-label%3Akind%2Ffailing-test+-label%3Akind%2Ffeature+-label%3Akind%2Fflake+-label%3Akind%2Fregression+-label%3Akind%2Fsupport) - apply `do-not-merge/needs-kind` and remove `needs-kind`
- [kubernetes/kubernetes open PRs that have `needs-kind`](https://github.com/kubernetes/kubernetes/pulls?q=label%3Aneeds-kind+is%3Apr+is%3Aopen+sort%3Aupdated-desc) - thanks to the above, these are known to have a `kind/` label so do not need `do-not-merge/needs-kind`; just remove `needs-kind` (this didn't returns any PRs)

**Comment by spiffxp** [comment]
> followup PR: drop needs-kind and needs-sig from tide and fejta-bot queries

Opened https://github.com/kubernetes/test-infra/pull/19848, which will close this issue when merged
