### ISSUE TITLE
ci-kubernetes-e2e-gce-scale-performance is continuously testing the same, stale k8s version since 10-29

### ISSUE THREAD

**Issue by mborsz** [kubernetes/test-infra#19838]
**What happened**:
Starting from
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1321859659652403200

all ci-kubernetes-e2e-gce-scale-performance runs are using stale k8s version v1.20.0-beta.0.54+2729b8e3751434.

Moreover, the commit number on https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance seems to be changing and it doesn't match the actual version that is being tested:
![image](https://user-images.githubusercontent.com/2559168/98100225-d6a20b80-1e90-11eb-8499-6f28362b62c4.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
e.g. the latest run https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1323762317799723008
**Anything else we need to know?**:

https://github.com/kubernetes/test-infra/pull/19660 is most likely a culprit which moves fast builds from kubernetes-release-dev which is used by the job to k8s-release-dev.

/cc @mm4tt 
/cc @wojtek-t 
/cc @cpanato 
/cc @justaugustus

**Comment by mborsz** [comment]
Yes, this is https://github.com/kubernetes/test-infra/pull/19660 for sure which migrates the test builds to k8s-release-dev. The question is if we should switch our jobs to k8s-release-dev or rollback that change? I don't think I have enough context to make that decision so I asked this question in #19660.

**Comment by mborsz** [comment]
https://github.com/kubernetes/test-infra/issues/19839 for showing right version on testgrid

**Comment by mm4tt** [comment]
Thanks, Maciek. Great finding!

We discovered only by a sheer luck. If Maciek wasn't debugging some other issue today, we might have missed that change for weeks and it would render our scale tests useless.
@justaugustus, can we do something to make sure it doesn't happen again? For example, could you let us know ever time you're making this kind of change to the build pipeline?

**Comment by wojtek-t** [comment]
/assign @justaugustus 

Stephen - as you mentioned on slack - I'm assigning it to you]
However, my suspicion would be that it's not only about scalability tests - it's probably touching many more tests.

**Comment by justaugustus** [comment]
PR opened to revert the change: https://github.com/kubernetes/test-infra/pull/19841
Slack discussion here: https://kubernetes.slack.com/archives/C2C40FMNF/p1604488277091500

**Comment by justaugustus** [comment]
FYI @kubernetes/ci-signal

**Comment by wojtek-t** [comment]
It's fixed at least for scalability tests - closing. Thanks for fixing Stephen!

/close

**Comment by justaugustus** [comment]
Thanks for reporting back on your side, @wojtek-t!

For completeness, dropping a snippet of the PR description in from https://github.com/kubernetes/test-infra/pull/19841:

> As we continue to migrate release-blocking jobs to a dedicated K8s Infra
> cluster, jobs that use the latest-fast marker need to extract builds
> from `gs://k8s-release-dev`, which is the K8s Infra equivalent of
> `gs://kubernetes-release-dev`.
> 
> A new flag (`--extract-ci-bucket=k8s-release-dev`) was added to support
> this transitional use case, so we employ it here.
> 
> This is part of migrating release-blocking jobs to K8s Infra (ref: #19484, #18549).

I'll plan to send a note out to the broader community early next week (by then, the remaining changes should have died down).

/sig release testing scalability
/area release-eng
