### ISSUE TITLE
Testgrid should show version of binary fetched by --extract flag

### ISSUE THREAD

**Issue by mborsz** [kubernetes/test-infra#19839]
**What would you like to be added**:
I would like to see a new column header in testgrid showing actual kubernetes version that is being tested when --extract= option is used in the test.

The testgrid config has a columnheader field that can be used for this purpose (https://godoc.org/github.com/GoogleCloudPlatform/testgrid/pb/config#TestGroup), but it's not possible to use it our prowjobs as they are using annotation-based testgrid configuration (like testgrid-dashboards, testgrid-num-failures-to-alert).

This is a feature request to add a new annotation that can be used to add `job-version` to the testgrid view.

**Why is this needed**:
In https://github.com/kubernetes/test-infra/issues/19838 the ci-kubernetes-e2e-gce-scale-performance test started continuously testing the same, stale k8s version  (v1.20.0-beta.0.54+2729b8e3751434), while the commit number in testgrid was progressing: 

![image](https://user-images.githubusercontent.com/2559168/98105480-5aabc180-1e98-11eb-9079-c2c69ff608f6.png)

See https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance

We found this issue by an accident, when I was debugging why https://github.com/kubernetes/kubernetes/pull/96117 hasn't been rolled out to our tests. I would like to see some column that will make it clear that we are testing the same version continuously and that will be more meaningful than master's commit in this context.

**Comment by MushuEE** [comment]
Would it be better to migrate this issue to https://github.com/GoogleCloudPlatform/testgrid?

**Comment by MushuEE** [comment]
Does https://github.com/GoogleCloudPlatform/testgrid/blob/master/config.md#column-headers enable you to do what you are looking for? 

Within the finished.json I see:
```
  "metadata": {
    "repo-commit": "eca53507be3d9008ff6d4cb776c02733a1ea898b", 
    "repos": {
      "k8s.io/kubernetes": "master", 
      "k8s.io/perf-tests": "master"
    }, 
    "infra-commit": "ab50c5702", 
    "repo": "k8s.io/kubernetes", 
    "job-version": "v1.20.0-beta.1.129+eca53507be3d90", 
    "pod": "820efc68-1f88-11eb-a4fe-eec30b56844c", 
    "revision": "v1.20.0-beta.1.129+eca53507be3d90"
  }
```
Do any of those work?

**Comment by mborsz** [comment]
Yes, columnheader with `job-version` works just fine, but there is no option to use testgrid's columnheader feature using annotation config we have in this repo. As mentioned in the first comment, this is a feature request to add support for annotation-based columnheader converter:

> The testgrid config has a columnheader field that can be used for this purpose (https://godoc.org/github.com/GoogleCloudPlatform/testgrid/pb/config#TestGroup), but it's not possible to use it our prowjobs as they are using annotation-based testgrid configuration (like testgrid-dashboards, testgrid-num-failures-to-alert).
> 
> This is a feature request to add a new annotation that can be used to add `job-version` to the testgrid view.

> Would it be better to migrate this issue to https://github.com/GoogleCloudPlatform/testgrid?

Correct me, if I'm wrong, but it looks like the prowjobs's annotation -> testgrid config converter is specific to this repo: https://github.com/kubernetes/test-infra/blob/c7564c10dab81a5ccf2c83f3efbaeacf11c472ca/testgrid/cmd/configurator/prow.go#L50

/cc @michelle192837

**Comment by MushuEE** [comment]
@mborsz I see, I misunderstood. Thanks

**Comment by michelle192837** [comment]
Yup, translating Prow jobs to TestGrid config is specific to this repo, though it's also fine to file the issue in https://github.com/GoogleCloudPlatform/testgrid (a lot of the config marshalling code is over there).

With respect to this ask, we can think about it, but at some point configuration starts getting away from fields that are easy to add in Configurator. Column headers, for instance, are not a simple scalar field, they are a repeated field that _should_ be a oneof, and I'm wary about trying to manage that or similar things in configuration.

That said, I think feel free to add this particular case to https://github.com/kubernetes/test-infra/blob/master/testgrid/cmd/configurator/prow.go? We also might have a relatively lightweight solution for more complicated configs in a bit, but I need to test if it works with Prow-based TestGrid config too.

**Comment by spiffxp** [comment]
/reopen
/sig testing
/sig scalability
related:
- https://github.com/kubernetes/test-infra/issues/20650
- https://github.com/kubernetes/test-infra/issues/20886
