### ISSUE TITLE
Add monitoring for autobump

### ISSUE THREAD

**Issue by mpherman2** [kubernetes/test-infra#19875]
**What would you like to be added**:
We should add some monitoring for autobump (for k8s prow and other tools that get autobumped in the future)

**Why is this needed**:
It failed silently for a week. We would like to notice this sooner.

/area prow

**Comment by MushuEE** [comment]
Mind linking to failures?

**Comment by mpherman2** [comment]
@chaodaiG can you link the failures you saw this week?

**Comment by chaodaiG** [comment]
https://testgrid.k8s.io/googleoss-test-infra#autobump-prow
See the streak of failures from 10/28 to 11/02

Example job: https://prow.k8s.io/view/gcs/oss-prow/logs/ci-oss-test-infra-autobump-prow/1323325406178185216

**Comment by mpherman2** [comment]
I believe this has been resolved, and testgrid alerts have been added for all of the bump jobs.
