### ISSUE TITLE
PR Dashboard: Show usernames associated with most recent comments

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/test-infra#1988]
Show usernames associated with comments since my most recent reply would be slightly more informative than "Address Comments" and would make it easier to batch attention on PRs (especially ones with longer-running discussions). 

It would also be useful to see a timestamp of the least-recent unaddressed comment, so I don't batch at too great a time interval. 

I don't want to clutter the dashboard, maybe this would be useful in a tool-tip when you hover over "Address Comments"?

**Comment by fejta** [comment]
Update and/or close and/or add help-wanted?

**Comment by mtaufen** [comment]
I'm going to close it. This isn't really that important.
