### ISSUE TITLE
Decide how to integrate results from CNI providers into testgrid

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/test-infra#19883]
**What would you like to be added**:

@aojea @alejandrox1 @eth0XFEED  should probably connect around how we can make it easy to contribute CNI test results .  

- Antonio is prototyping this for ovn-kubernetes
- I think me (@jayunit100) and @abhiraut can make sure antrea/calico are both part of the test matrix since we use those regularly 
- @aanm might want to help on the cilliim end (I can help with that to)

**Why is this needed**:

CNI test results are all over the map and its not always clear which ones support the Network Policy API to what extent.  Since every cluster uses a CNI we need to have clear signal at least on major providers, and make it easy for providers to share and contribute to the overall health of the NetworkPolicy test matrix

**Comment by BenTheElder** [comment]
> Since every cluster uses a CNI

ahem, kubenet? :-)

> we need to have clear signal at least on major providers, and make it easy for providers to share and contribute to the overall health of the NetworkPolicy test matrix

This is not generally something we do, we expect tests upstream to test _the Kubernetes API and components_ and if one of the vendor implementations of some extension point is failing the tests _that's their problem_.

Anyone is free to provide results to testgrid following the existing guides, in this form nothing should be special here.

**Comment by aojea** [comment]
The idea I have is to contribute the results of the different CIs , at least is what I m going to do for ovn-kube

https://github.com/kubernetes/test-infra/blob/master/docs/contributing-test-results.md

**Comment by jayunit100** [comment]
Yup just centralizing the dialogue for how we advise folks to do this, I think all on the same page.
Antonio has a GCE job I think in progress for calico

**Comment by jayunit100** [comment]
https://github.com/kubernetes/test-infra/pull/19817 xref, using GCE with the calico network policy provider
