### ISSUE TITLE
Ordering Git PR Failures

### ISSUE THREAD

**Issue by dashpole** [kubernetes/test-infra#1989]
Just an Idea, I don't even know if this is possible.  
I was helping a newer member of the team debug their PR, and had the opportunity to watch their thought process, and compare it with how I would debug their PR.

They saw this, which had a number of failures.
![screenshot from 2017-02-23 09 26 35](https://cloud.githubusercontent.com/assets/3262098/23270907/4f8acc90-f9aa-11e6-8172-03ffc9b7dfaf.png)

As you can see, one of the failures is the unit/integration tests.  As someone who has debugged a number of PRs, I immediately knew this was likely the culprit, but this wasn't obvious to a newcomer, who was looking through the build log on one of the other tests.

In general, unit test failures will almost always cause other tests to fail.  If possible, I would suggest ordering tests from lowest level to highest level.  Start with Bazel, Verification, and Unit tests.  Then move to node tests, generic e2e tests, and finally provider-specific tests.  Or at the very least, place Bazel, Verification, and Unit tests at the top.

If we cant change the ordering, could the bot post a "likely culprit"  along with the test failures?  Or make one of the names red?  Here is the "bot" I am referencing:
![screenshot from 2017-02-23 09 40 25](https://cloud.githubusercontent.com/assets/3262098/23271449/43fe96e8-f9ac-11e6-9dcc-8422cf42de06.png)

cc: @kubernetes/test-infra-maintainers @fejta

**Comment by spxtr** [comment]
I don't think we have control over the order of the check marks, but we do have control over the order in the comment. When every PR fails it's usually because a change doesn't build, or the PR needs a rebase. We should handle both of these cases in a less-spammy way.

**Comment by rmmh** [comment]
Handling the "Everything failed because it needs a rebase" case cleanly would help a lot.

**Comment by fejta** [comment]
@BenTheElder is refactoring most of these jobs to trigger after we successfully build, which should help make this more obvious
