### ISSUE TITLE
approved label is automatically added

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/test-infra#19896]
**What happened**:
Github keeps adding approved label recently for cloud-provider-openstack repo (https://github.com/kubernetes/cloud-provider-openstack), if the PR is submitted by a person who has approve permission.

I proposed a PR https://github.com/kubernetes/test-infra/pull/19824 trying to fix but it's not working, e.g. this PR https://github.com/kubernetes/cloud-provider-openstack/pull/1310 is submitted today, but the approved label was still added.

**What you expected to happen**:
Github doesn't add approved label automatically like before.

**How to reproduce it (as minimally and precisely as possible)**:
An authorized person submits a PR will trigger github adding the approved label.

**Please provide links to example occurrences, if any**:
https://github.com/kubernetes/cloud-provider-openstack/pull/1310

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
@lingxiankong the `approved` label gets automatically added whenever the PR author is approver for the relevant area, unless you set `require_self_approval: true`. See https://prow.k8s.io/plugins for details
