### ISSUE TITLE
Don't leave 7 "ok to test?" messages on every PR

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#199]
I think each PR builder job leaves a comment saying this. We should not do this, it looks ridiculous...

**Comment by spxtr** [comment]
I agree, but we don't have a choice: https://github.com/jenkinsci/ghprb-plugin/issues/292

**Comment by eparis** [comment]
we could extend the munger's comment-deleter to remove 3 of them....

**Comment by spxtr** [comment]
Done :)
