### ISSUE TITLE
Hook errors on invalid revision ranges

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#19908]
Seeing a number of errors since this morning from hook, about trying to search invalid revision ranges. For example:

```
jsonPayload: {
  ...
  component: "hook"   
  error: "error verifying if merge commits exist between 0ad06e991ab0d0708593e3e6415c521c6b76b7d1 and 6b87936f38e698f6c1a05cce5688d6222e5b526c: exit status 128. output: fatal: Invalid revision range 0ad06e991ab0d0708593e3e6415c521c6b76b7d1..6b87936f38e698f6c1a05cce5688d6222e5b526c
"   
  ...
 }
```

```
jsonPayload: {
  ...
  component: "hook" 
  error: "error verifying if merge commits exist between 4926beedf9420e872a4e5943a33d343cb52c77de and 560397e0600a7ef36995b6c097e8ca5d1c54850a: exit status 128. output: fatal: Invalid revision range 4926beedf9420e872a4e5943a33d343cb52c77de..560397e0600a7ef36995b6c097e8ca5d1c54850a
"
  ...
 }
```

The error format is always the same but the errors themselves are not consistent on the revision range searched (though it looks like some revisions pop up multiple times?)

/area prow
/area prow/hook

/assign @fejta

**Comment by michelle192837** [comment]
This started happening, so far as I can tell, sporadically since 04:08:33.000 PST this morning.

**Comment by michelle192837** [comment]
This seems to be happening in kubernetes/kubernetes only (I think because it has the `mergecommitblocker` plugin enabled), but it doesn't appear to be consistent on a particular PR. I'm also not finding anything suspicious when checking some of the revisions mentioned in the error.

This timing isn't correlated with a Prow release, so far as I can tell, so I think I will consider this non-release-blocking and release k8s-prow later today.

**Comment by spiffxp** [comment]
Maybe related, or another symptom of the underlying issue: https://github.com/kubernetes/test-infra/issues/19910

**Comment by alvaroaleman** [comment]
> Maybe related, or another symptom of the underlying issue: #19910

Yeah, its the same issue, we use `CheckoutPullRequest` and if it was the first push and githubs post-receive hook to create the virtual ref failed, the virtual ref won't exist. We should probably make that func also take a sha instead of a PR number and then fetch & checkout that sha

**Comment by chaodaiG** [comment]
This was fixed by https://github.com/kubernetes/test-infra/pull/19928

/close
