### ISSUE TITLE
Provide [VM] image with the CONFIG_NUMA_EMU enabled

### ISSUE THREAD

**Issue by cynepco3hahue** [kubernetes/test-infra#19902]
**What would you like to be added**:
The image with the kernel that compiled with the  `CONFIG_NUMA_EMU=y`.

**Why is this needed**:
Under the sig-node, we have components(CPU manager, device manager, topology manager, and memory manager in the future) that should be tested on the multi NUMA machines. Currently, the GCE does not support creating instances with the custom CPU topology, so the only option for us is to use [fake NUMA](https://www.kernel.org/doc/Documentation/x86/x86_64/fake-numa-for-cpusets), the problem that it requires the kernel to be compiled with the `CONFIG_NUMA_EMU=y`.

**Comment by bsdnet** [comment]
We will take a look at next COS release on cos-dev channel

**Comment by cynepco3hahue** [comment]
> We will take a look at next COS release on cos-dev channel

A lot of thanks!

**Comment by BenTheElder** [comment]
This isn't *really* something this repo does, but I don't know where better to track it.

**Comment by bsdnet** [comment]
The kernel configuration should be enabled in image 

https://cloud.google.com/container-optimized-os/docs/release-notes#cos-dev-88-15978-0-0

**Comment by bsdnet** [comment]
```
$ zcat /proc/config.gz |grep EMU
CONFIG_HPET_EMULATE_RTC=y
CONFIG_X86_VSYSCALL_EMULATION=y
CONFIG_NUMA_EMU=y
CONFIG_LEGACY_VSYSCALL_EMULATE=y
CONFIG_IA32_EMULATION=y
# CONFIG_NET_IPGRE_DEMUX is not set
# CONFIG_NET_VENDOR_EMULEX is not set
# CONFIG_THERMAL_EMULATION is not set
# CONFIG_RTC_INTF_DEV_UIE_EMUL is not set
```

**Comment by bsdnet** [comment]
```
$ cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
GOOGLE_CRASH_ID=Lakitu
KERNEL_COMMIT_ID=179ce8ac3e0563cdcf8fd505027149667643d3fc
VERSION=88
VERSION_ID=88
BUILD_ID=15978.0.0
```
