### ISSUE TITLE
Enforce / monitor / document version marker usage

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/test-infra#19922]
**What would you like to be added**:

sig-release maintains [`build`](https://testgrid.k8s.io/sig-release-master-blocking#build-master) and [`fast-build`](https://testgrid.k8s.io/sig-release-master-blocking#build-master-fast) jobs to periodically build and publish kubernetes artifacts. These jobs also update their respective [version markers](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/kubernetes-versions.md#ci). When other jobs run, they determine the version of Kubernetes to download by fetching the latest version marker for a particular version. Some of these jobs use the latest "fast" version and some use just the latest. In practice, the only time we need to use a non-fast version is when we are testing an os/arch combo other than `linux/amd64`, but there are a number of jobs that use non-fast version even though it is not required (example: https://github.com/kubernetes/kubernetes/issues/96463#issuecomment-725478355).

**Why is this needed**:

Using a non-fast build is not necessarily wrong, but it does result in a stale build being used when a perfectly valid new one is available. We should always use fast-build when appropriate. However, it is difficult to enforce this as the version marker being used is not always surfaced in the prowjob config. In order to enforce usage of a particular version marker, jobs must utilize frameworks such as [kubetest](https://github.com/kubernetes/test-infra/tree/master/kubetest) where the version is selected in a standardized manner.

Work in this area is related to https://github.com/kubernetes/release/issues/1711 and https://github.com/kubernetes/community/pull/5014.

/cc @justaugustus @saschagrunert @kubernetes/release-engineering 
/assign

**Comment by justaugustus** [comment]
This also has some heavy overlap/interaction with [assessing the version markers in release branch job configs](https://github.com/kubernetes/sig-release/issues/850), so assigning myself as well.

/assign
/remove-kind feature
/kind cleanup
/sig release
/area release-eng

**Comment by justaugustus** [comment]
Also of note: migrating release-blocking jobs to K8s Infra (ref: #19484, #18549).

**Comment by spiffxp** [comment]
/priority important-soon
Version markers are off again

stable1 should be v1.20, since it's the most recent release
```
$ gsutil cat gs://kubernetes-release-dev/ci/k8s-stable1.txt
v1.19.8-rc.0.74+2fffed102ddbb6
```
This means "master/stable1" skew jobs that think they're going most-recent release to master (v1.20/v1.21), are in fact skewing by two versions (v1.19/v1.21)

beta should either not be used by any current jobs (it is), or should point to v1.21
```
$ gsutil cat gs://kubernetes-release-dev/ci/k8s-beta.txt
v1.20.3-rc.0.77+e4f2398716b35
```

`stable3` points to v1.17 (which has fallen out of support), and we've still got some leftover generated 1.17 jobs showing up on testgrid

**Comment by spiffxp** [comment]
Markers in k8s-release-dev were rolled forward, markers in kubernetes-release-dev were not.  PR to address here: https://github.com/kubernetes/test-infra/pull/20887

**Comment by spiffxp** [comment]
/close
@hasheddan @justaugustus Can you articulate the work being asked for here in separate issues? This has fallen stale twice now.  I don't think it's actionable enough and am inclined to close it in favor of consolidating "version marker" discussion in https://github.com/kubernetes/sig-release/issues/850

I parse two things:
1. only jobs using non-linux/amd64 arch need the cross build, everything else should use the fast build
2. there some are some jobs that don't surface which version marker they use

Depending on what sort of policy you want out of 1, it could be enforced by the same test that enforces `--extract=ci/latest-fast` for anything on release-master-blocking or release-master-informing

2 is likely to go perma-stale unless there's a list or way of identifying these jobs
