### ISSUE TITLE
Ghproxy running out of github tokens in a hour

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#19931]
**What happened**:

Prometheus alertmanager alerted on Slack that ghproxy had ran out of github tokens in an hour: https://kubernetes.slack.com/archives/C7J9RP96G/p1605176151126600

**What you expected to happen**:

Ghproxy doesn't use that much github tokens

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1&refresh=1m&from=now-2d&to=now&var-token=d69e38ccf1047da629fdf26bd711e6a22bcb99f1096a64e6c7fe0366e0e3ca7b&var-path=%2Forganizations%2F:orgId%2Fmembers&var-status=200&var-range=30m

**Anything else we need to know?**:

**Comment by chaodaiG** [comment]
Probably related: https://kubernetes.slack.com/archives/CDECRSC5U/p1605194754195400

This was 4 hours after tide merging queue for k8s/kubernetes spiking https://monitoring.prow.k8s.io/d/d69a91f76d8110d3e72885ee5ce8038e/tide-dashboard?orgId=1

**Comment by chaodaiG** [comment]
This could also be possibly related to https://github.com/kubernetes/test-infra/issues/19910 and https://github.com/kubernetes/test-infra/issues/19908, the first one was mitigated by https://github.com/kubernetes/test-infra/pull/19928. So bumping prow might help here

**Comment by stevekuznetsov** [comment]
You should be able to use the Grafana dashboard to dig into exactly which API calls the specific OAuth token and Prow component is making.

**Comment by chaodaiG** [comment]
Good point, `/repos/:owner/:repo/pulls/:pullId` is on the top
![Uploading Screen Shot 2020-11-12 at 9.59.09 AM.png…]()

**Comment by mpherman2** [comment]
/remove-lifecycle stale

Looks like this is still happening

**Comment by chases2** [comment]
This issue is pretty old and doesn't seem to be occurring any longer. Closing for now, but will update if things change this week.
