### ISSUE TITLE
Kettle entering CrashLoopBackOff with "Bad GCS path" 

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19961]
**What happened**:
11/16 Checked on state of Kettle, Looks like starting 11/11 errors started occurring in `make_db.py`
![image](https://user-images.githubusercontent.com/7189267/99285546-8447df80-27ec-11eb-818c-fbc1f2c14ac8.png)
```
"20.16user 18.85system 0:37.85elapsed 103%CPU (0avgtext+0avgdata 1465472maxresident)k
"
```
```
Traceback (most recent call last):
  File "make_db.py", line 346, in <module>
    OPTIONS.junit)
  File "make_db.py", line 310, in main
    threads, client_class)
  File "make_db.py", line 246, in get_builds
    for n, (build_dir, started, finished) in enumerate(builds_iterator):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
ValueError: Bad GCS path
Command exited with non-zero status 1
20.74user 22.63system 0:42.67elapsed 101%CPU (0avgtext+0avgdata 1465524maxresident)k
0inputs+88outputs (0major+603132minor)pagefaults 0swaps
+ time python3 make_db.py --buckets buckets.yaml --junit --threads 32
Traceback (most recent call last):
  File "/kettle/update.py", line 59, in <module>
    main()
  File "/kettle/update.py", line 29, in main
    call('time python3 make_db.py --buckets buckets.yaml --junit --threads 32')
  File "/kettle/update.py", line 25, in call
    raise OSError('invocation failed')
OSError: invocation failed
```

Unsure if this is a CPU limit/memory issue or if it is another failure.

**What you expected to happen**:
make_db to pass successfully 

**How to reproduce it (as minimally and precisely as possible)**:
Start kettle prod container. 

**Please provide links to example occurrences, if any**:
https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22g8r%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22kettle%22%0A%22%2B%22;timeRange=2020-11-08T17:10:19.418Z%2F2020-11-16T17:10:19.418215Z;summaryFields=true:true:32:beginning?scrollTimestamp=2020-09-08T13:49:38.595881274Z&dateRangeUnbound=both&project=k8s-gubernator
**Anything else we need to know?**:

/cc @spiffxp @amwat 
/assign

**Comment by MushuEE** [comment]
Kettle restarts cycles at 1am, it looks like after a restart cycle something changed that started triggering crashes. This will also impact 
/area triage
/area kettle
results

**Comment by MushuEE** [comment]
Bad path it is looking for is `kubeflow-pipeline-backend-test/*` it is for some reason not prepended with the `gs://` parts. 
I do not know what caused this.
Workers are attempting to run: `WORKER_CLIENT.get_started_finished(job, build)` 
Which should make the build_dir `self.get('%s/directory/%s/%s.txt' % (self.jobs_dir, job, build)).strip()` this implies that there is no `gs://` in jobs_dir

here job=`kubeflow-pipeline-backend-test` and build = `some number`

This behavior implies `build_dir` is not correct or nil which can be caused by `if 400 <= resp.status_code < 500 and resp.status_code != 429:`

**Comment by MushuEE** [comment]
Now seeing `Bad path: /started.json, should start with 'gs://'`
This proves that `build_dir` is none. 
calling `get` with `gs://kubernetes-jenkins/pr-logs/directory/kubeflow-pipeline-backend-test/1326401600935170048.txt`
`bucket, path = ['kubernetes-jenkins', 'pr-logs/directory/kubeflow-pipeline-backend-test/1326401600935170048.txt']`

```
>>> x._request("kubernetes-jenkins/o/pr-logs%2Fdirectory%2Fkubeflow-pipeline-backend-test%2F1326401600935170048.txt", {'alt': 'media'}, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in _request
  File "/usr/lib/python3/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by MushuEE** [comment]
Looks like the issue might be in decoding the json from the path: 
```
>>> url = 'https://www.googleapis.com/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fdirectory%2Fkubeflow-pipeline-backend-test%2F1326401600935170048.txt'
>>> y.get(url, params=params, stream=False)
<Response [200]>
>>> x.json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Seems like this is an artifact of `params={'alt': 'media'}` << what is this??

**Comment by MushuEE** [comment]
Here is the <buildID.>txt
```
{
  "kind": "storage#object",
  "id": "kubernetes-jenkins/pr-logs/directory/kubeflow-pipeline-backend-test/1326401600935170048.txt/1605074104192362",
  "selfLink": "https://www.googleapis.com/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fdirectory%2Fkubeflow-pipeline-backend-test%2F1326401600935170048.txt",
  "mediaLink": "https://www.googleapis.com/download/storage/v1/b/kubernetes-jenkins/o/pr-logs%2Fdirectory%2Fkubeflow-pipeline-backend-test%2F1326401600935170048.txt?generation=1605074104192362&alt=media",
  "name": "pr-logs/directory/kubeflow-pipeline-backend-test/1326401600935170048.txt",
  "bucket": "kubernetes-jenkins",
  "generation": "1605074104192362",
  "metageneration": "1",
  "contentType": "text/plain; charset=utf-8",
  "storageClass": "STANDARD",
  "size": "0",
  "md5Hash": "1B2M2Y8AsgTpgAmY7PhCfg==",
  "crc32c": "AAAAAA==",
  "etag": "COqaxv7m+ewCEAE=",
  "timeCreated": "2020-11-11T05:55:04.192Z",
  "updated": "2020-11-11T05:55:04.192Z",
  "timeStorageClassUpdated": "2020-11-11T05:55:04.192Z",
  "metadata": {
    "x-goog-meta-link": "gs://kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4751/kubeflow-pipeline-backend-test/1326401600935170048"
  }
}
```
You can look at the media link to see it is empty. We use this to get the build dir. Which happens to also be accessible by `["x-goog-meta-link"]` which I hope will work in all cases

**Comment by MushuEE** [comment]
It is actually unclear to me why pr builds would ever have a [different path](https://github.com/kubernetes/test-infra/blob/2ae2b484ec8e6ee42d399b842a0d18d19fb8441a/kettle/make_db.py#L160-L163) to the artifacts. I might just be able to remove that option for the build dir being build from the <buildid>.txt

**Comment by amwat** [comment]
I don't think that run was a legitimate run and from the [job history page](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/kubeflow-pipeline-backend-test?buildId=1326401600935170048) looks like it doesn't any of the corresponding info. the full link is just `https://prow.k8s.io/view/gs/kubernetes-jenkins`

I think we should just ignore such builds in kettle.

**Comment by MushuEE** [comment]
@amwat I think you are correct. Looks like there is a decent bit of cleanup I might be able to do. Trying to figure out what is most worth it in the short term. I don't want to silence legitimate builds but also don't want to cause catastrophic failure on single build pulls.

**Comment by amwat** [comment]
To be clear, there was an associated legitimate build https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4751/kubeflow-pipeline-backend-test/1326401600935170048

but whatever uploaded it to the directory seems to have weirded out (and worth investigating)

https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/directory/kubeflow-pipeline-backend-test

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/directory/kubeflow-pipeline-backend-test/1326401600935170048.txt

 but kettle should not need to worry about this and should safely skip over such builds (and definitely as a fix to bring kettle back up and running).

**Comment by MushuEE** [comment]
It is currently back up with a fix, will put up one when I am more confident I didn't break something. Lots of moving parts
