### ISSUE TITLE
Prow issue:/sig kubernetes

### ISSUE THREAD

**Issue by popooja-8** [kubernetes/test-infra#19964]
I am installing 3 node k8s cluster, calico will be stable for 1 or 2 days, again after that it goes down. After describing POD it says BGP not established, but Internal IPs are pinging.(after rebooting calico will come up, but again it goes down, rebooting as rework is not possible since some of the suites are running in background).

**Comment by BenTheElder** [comment]
This doesn't appear to be an issue with prow, we don't provide support for Kubernetes or Calico in this repo, this repo is for the CI tooling.
