### ISSUE TITLE
[ci-test-infra-autoupdate-patch] job stuck in pending or failing

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#19979]
**What happened**:
[ci-test-infra-autoupdate-patch](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-test-infra-autoupdate-patch) 
![image](https://user-images.githubusercontent.com/7189267/99563657-55fa0980-297e-11eb-93e8-9772d3647563.png)
Job is continuously failing or producing no results. This causes paring errors in Kettle (how it was found).

**What you expected to happen**:
Job to be stable

**How to reproduce it (as minimally and precisely as possible)**:
<View Prow>

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
> Job is continuously failing or producing no results. This causes paring errors in Kettle (how it was found).

Why does that cause errors in kettle? Jobs do sometimes continuously fail.

In this case it appears that some types need updating / manual library upgrades are necessary instead of automatic upgrades:
> prow/spyglass/lenses/junit/lens.go:161:23: cannot assign *junit.Suites to suites (type junit.Suites) in multiple assignment

**Comment by MushuEE** [comment]
IIRC it was creating empty `json` results and kettle was failing on parse attempts. That issue was fixed but the stuck pending I think is still an issue

**Comment by BenTheElder** [comment]
I think this was @fejta's project, actually?

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/reopen
Job is currently failing https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-autoupdate-patch/1425473394320609280
