### ISSUE TITLE
Improve "Jenkins overloaded" error message.

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#1998]
The current message says "try again later", but according to @foxish I don't actually need to "try again".  The robot should try again for me.

Can we clarify the error message so contributors don't think they need to do anything?

**Comment by rmmh** [comment]
Not sure what @foxish meant, you *do* actually need to take some action to trigger a new build in the future.

**Comment by foxish** [comment]
I meant to say that ideally, we shouldn't have to retrigger those tests manually, not that there is no need for that today. :)

**Comment by mml** [comment]
Oh, OK.  Then my request is to plug in one of those beautiful tables that includes a crib sheet with the correct bot command to request each test.

**Comment by smarterclayton** [comment]
Yes - that's incredibly painful to guess (I have a cheat sheet i reference)...

**Comment by krzyzacy** [comment]
this message is gone
