### ISSUE TITLE
cannot approve sig-cli PR

### ISSUE THREAD

**Issue by adohe** [kubernetes/test-infra#19997]
Hi guys, I am a member of sig-cli-maintainers，but seems I cannot approve PR with sig/cli label, for more info can refer: https://github.com/kubernetes/kubernetes/pull/96702

**Comment by ajaygm** [comment]
Hi @adohe 
No offenses, but are you sure you are a member of the team `sig-cli-maintainers`. When I look at [your profile page](https://github.com/adohe?tab=overview&from=2020-10-01&to=2020-10-31) it doesn't show you as a member of any organisation and shows... 
> Joined GitHub
> on September 22, 2020

I'm not sure, but you might be able to check this by going to the URL: https://github.com/orgs/kubernetes/teams/sig-cli-maintainers

Check if you get the following message when you go to https://github.com/orgs/kubernetes/teams/
> You’re not a member of any teams in this organization.

**Comment by adohe** [comment]
Hi @ajaygm 
Thanks for confirming this. I checked this URL: https://github.com/orgs/kubernetes/teams/sig-cli-maintainers/members, and I am sure I am a member of team `sig-cli-maintainers`, TonyAdo is me :). Also when I visit https://github.com/orgs/kubernetes/teams/ I can see I am still a member of sig-cli related teams. I think there might be some mistakes, as I lost my github id for some reason a while ago, and with the help of Github Support team, I register a new account with the same email address, this may has some help information for this issue.

**Comment by ajaygm** [comment]
If I understood correctly you are saying: https://github.com/adohe is the same as https://github.com/tonyado 
In that case do you think your new id `adohe` should be added to the team now? Or should the approve plugin be able to handle this type of configuration?

BTW: Even that id `tonyado` doesn't show as member of Kubernetes :confused:

**Comment by adohe** [comment]
Actually TonyAdo is just a user name not github id, if u check this URL: https://github.com/orgs/kubernetes/teams/sig-cli-maintainers/members, u can see there is a member named TonyAdo with github id: `adohe`, that's me :) I don't know how the approve plugin work, seems it has some input problem with the plugin.

BTW: I am emeritus lead of sig-cli, I am not sure whether this has effect.

**Comment by ajaygm** [comment]
Hi @adohe 
I finally found the answer to your query. Your id has been moved into emeritus section of the file...
https://github.com/kubernetes/kubernetes/blob/ad2bf99f9b8f27113cd3b0c9e0ad72e568947e43/OWNERS_ALIASES#L207-L208

The description of [Emeritus approver](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#emeritus) says that these users can't approve requests. You might have to get yourself back into the approvers list to be able to approve pull requests.

**Comment by adohe** [comment]
Really appreciate your help @ajaygm and thanks very much 👍
