### ISSUE TITLE
Move pull-kubernetes-e2e-gce-device-plugin-gpu to k8s infra

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/test-infra#20006]
**What should be cleaned up or changed**:

Currently [pull-kubernetes-e2e-gce-device-plugin-gpu](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cloud-provider/gcp/gpu/gcp-gpu-presubmits.yaml) does not run on community infra, making it difficult to troubleshoot and leads to divergence in behavior from the release-blocking presubmit. It should follow the migration of the periodic, which was accomplished in https://github.com/kubernetes/test-infra/issues/18579

**Provide any links for context**:

This became an issue in https://github.com/kubernetes/kubernetes/pull/96553
Slack conversation: https://kubernetes.slack.com/archives/C0BP8PW9G/p1605802045171300

/assign

**Comment by RenaudWasTaken** [comment]
Adding @kewu1992 to this thread, here is what he found:


> I tried to reproduce the problem by installing the 418.67 driver on a GCE VM based on the cos-77-12371-1079-0 image. But I couldn't reproduce the issue. The installation succeeded with no error. 
> 
> Regarding the error (error: 'NV_BUILD_MODULE_INSTANCES' is not defined) you posed, we have seen this before. It happened when trying to install drivers older than 440 on the 5.4 kernel. However, cos-77 is based on the 4.19 kernel rather than 5.4. This suggests that the test may use an incorrect COS version.
> 
> Another thing is that you mentioned the precompiled driver was not selected and it falled back to driver compilation, this is also not expected. As you posted, the https://storage.googleapis.com/nvidia-drivers-us-public/nvidia-cos-project/77/tesla/418_00/418.67/NVIDIA-Linux-x86_64-418.67_77-12371-1079-0.cos does exist. In my reproduction, the installer was able to find and use the 418.67 precompiled drivers. This also suggests the cos version or GPU driver version used in the test may be incorrect.
> 
> I think the next step is to confirm the COS version that the test is using. Both the configured version and the one actually shown in the OS (`cat /etc/lsb-release`). I have a feeling that the root cause might be the OS got auto-updated to the newer COS version during reboot.

**Comment by BenTheElder** [comment]
note that this presubmit should be optional / non-blocking now (not sure if it was when this was filed), but it should still move.

**Comment by hasheddan** [comment]
Sorry for the delay here! Should be able to get this moved over ASAP

**Comment by BenTheElder** [comment]
no worries, just scanning through our issue tracker 😅
