### ISSUE TITLE
Cluster API jobs should not be on release master boards

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/test-infra#20016]
**What should be cleaned up or changed**:

Currently two CAPI jobs run on `master-informing`:
- `capa-conformance-v1alpha3-k8s-master`
- `capg-conformance-v1alpha3-k8s-master`

However, these jobs are currently running against the `release-1.19` branch. It does not make sense to have jobs running against older stable versions on the current `master` board.

**Provide any links for context**:

Dashboard: https://testgrid.k8s.io/sig-release-master-informing
Context:
- #19752 
- kubernetes/kubernetes#96055
- https://github.com/kubernetes/test-infra/pull/20003

**Comment by CecileRobertMichon** [comment]
> However, these jobs are currently running against the release-1.19 branch

Looks like `capa-conformance-v1alpha3-k8s-master` is running against k8s master https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-aws/cluster-api-provider-aws-periodics.yaml#L235-L238

**Comment by hasheddan** [comment]
@CecileRobertMichon ah good catch! I was looking at the wrong periodic

**Comment by sedefsavas** [comment]
Kubernetes version we are running in the conformance workload cluster is defined by e2e_conf.yaml IIRC: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/f9b3593c998fd9896c7a79ab41d9542fd98ea6b8/test/e2e/data/e2e_conf.yaml#L110

So does this mean we are not actually running conformance against master?

**Comment by CecileRobertMichon** [comment]
@sedefsavas for conformance the k8s version is being overridden here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/f9b3593c998fd9896c7a79ab41d9542fd98ea6b8/test/e2e/suites/conformance/conformance_test.go#L62

**Comment by BenTheElder** [comment]
🛸 scanning for signs of life 🛸

**Comment by BenTheElder** [comment]
he's dead, jim
