### ISSUE TITLE
Prow issue: Allow re-test for flakes for approved/lgtm'd PR

### ISSUE THREAD

**Issue by mikebryant** [kubernetes/test-infra#2007]
This PR was approved & LGTM'd: https://github.com/kubernetes/kubernetes/pull/41501#issuecomment-282272108

Testing failed due to a flake (presumably, since it was a pure docs change)

Would it make sense to allow retesting of these by the PR author, if the PR's been approved and(/or?) lgtm'd. If the code's acceptable for merging it's presumably acceptable for re-testing

**Comment by spxtr** [comment]
I think once the PR has "ok to test" then the author can request a retest. @rmmh added that functionality in 392471a987761e2517d997889b8e5b70a9444635. Is it broken?

**Comment by spxtr** [comment]
Oh, it looks like LGTM should count as "ok to test" here.

**Comment by mikebryant** [comment]
I guess I wasn't trying `ok to test`, I was trying the one I was directed to by this comment: https://github.com/kubernetes/kubernetes/pull/41501#issuecomment-282169996

-- but I guess I would expect any testing command to work

**Comment by spxtr** [comment]
They'll work now that someone said "ok to test" on the PR. It's a bug on our side that LGTM triggers tests once but doesn't allow you to request testing.
