### ISSUE TITLE
Kubelet Node E2E Lock Contention job

### ISSUE THREAD

**Issue by knabben** [kubernetes/test-infra#20105]
**What would you like to be added**:
Kubelet Node E2E lock contention test
 
**Why is this needed**:
In order to graduate the --exit-on-lock-contention and --lock-file Kubelet flags, a suite running E2E tests for them needs to be created.

Ref https://github.com/kubernetes/kubernetes/pull/96775

**Comment by ehashman** [comment]
Is this still relevant?

**Comment by ehashman** [comment]
cc @ike-ma
