### ISSUE TITLE
verify whether v1.20 bazel image acts as bazelisk

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#20101]
**What should be cleaned up or changed**:
- Decide whether or not we're going to proceed with per-kubernetes-release-branch variants of `gcr.io/k8s-testimages/launcher.gcr.io/google/bazel` going forward
- If yes, update https://github.com/kubernetes/test-infra/blob/master/images/bazel/variants.yaml to build new images
- Update 1.20 job configs to use the `kubernetes-1.20` tag instead of the `kubernetes-master` tag introduced as a workaround in https://github.com/kubernetes/test-infra/pull/20100

**Provide any links for context**:
Investigation here: https://github.com/kubernetes/kubernetes/issues/97025#issuecomment-737529349

/sig testing
/sig release
/area releng
FYI @kubernetes/release-engineering

**Comment by spiffxp** [comment]
In discussing with @amwat we believe that the version of `bazel` used in the `kubernetes-master` image is effectively `bazelisk`, meaning it will automatically download and use whatever version of bazel is specified in `.bazelversion` for the repo under build/test.

This means that we may not actually need the added complexity of branch-specific builds of this bazel image.  We could continue to maintain the existing split of one bazel image for pre-1.20 jobs, and the current bazel image for 1.20+ jobs.

Does someone want to verify this?

**Comment by saschagrunert** [comment]
I agree that not adding more complexity to the branch logic is something I would prefer.

WDYT @hasheddan ?

**Comment by saschagrunert** [comment]
> Does someone want to verify this?

/help

**Comment by spiffxp** [comment]
/retitle verify whether v1.20+ bazel image acts as bazelisk

**Comment by amwat** [comment]
IIRC Bazel will respect whatever version is specified in `.bazelversion` **if that binary already exists** and will error out with installation instructions otherwise. OTOH bazelisk will silently download it if it doesn't exist .

which is what we do in `variants.yaml` currently with `BAZEL_VERSION` and `OLD_BAZEL_VERSION`

ref: https://github.com/kubernetes/test-infra/pull/16910#issuecomment-603430509

**Comment by BenTheElder** [comment]
kubernetes v1.21+ does not have bazel, so at most this is relevant to v1.20
/retitle verify whether v1.20 bazel image acts as bazelisk

https://github.com/kubernetes/test-infra/issues/20101#issuecomment-778478840 still seems important.

**Comment by BenTheElder** [comment]
I don't think we need to do anything further here. This image will not be relevant in ~2 releases time, in the meantime we should manage it as-is and not invest in it further for the purposes of Kubernetes.
