### ISSUE TITLE
Label cla/linuxfoundation is failing to be created 

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes/test-infra#20112]
**What happened**:
On PR https://github.com/kubernetes-sigs/node-feature-discovery/pull/409 
![image](https://user-images.githubusercontent.com/15933089/101016533-ec116080-3536-11eb-8757-b489921bd74f.png)

the user @marquiz who has CLA, created a PR, the check says is ok, but the PR is not getting labeled `cla/linuxfoundation` so `tide` is blocked waiting on the label

**What you expected to happen**:
`cla/linuxfoundation` label to be added to the PR authored by a CLA authorized user

**Comment by cblecker** [comment]
`/check-cla` exists for this use case. It was already run on that PR, and that PR is now merged :)

/close
