### ISSUE TITLE
kubemark uses the --check_version_skew

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2012]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2805?log#log

https://github.com/kubernetes/test-infra/pull/2009

**Comment by fejta** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2806

**Comment by fejta** [comment]
#2014 should resolve this. I'm going to wait for the non-critical kubemark jobs to pass on this image and then unpin the critical job.

**Comment by fejta** [comment]
Looks like kubetest makes assumptions about PWD that are not correct for kubemark jobs, fixing in #2015, testing in canary now

**Comment by fejta** [comment]
Example: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2810

**Comment by fejta** [comment]
Woo! https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2811

**Comment by krzyzacy** [comment]
:+1:
