### ISSUE TITLE
gci-qa-* jobs broken due to newline in image name

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/test-infra#2020]
All gci-qa-* jobs started to fail with an error that seems to suggest there's a newline char at the end of image name.

```
I0224 10:58:17.749] Creating minions.
W0224 10:58:18.622] Attempt 1 to create bootstrap-e2e-minion-template
W0224 10:58:18.958] WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
W0224 10:58:19.073] ERROR: (gcloud.compute.instance-templates.create) Could not fetch image resource:
W0224 10:58:19.073]  - Invalid value 'gci-base-58-9313-0-0
W0224 10:58:19.073] '. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?'  <=== Might be a newline char here
```

Could be related to #1657. @fejta Does it ring a bell to you?

Log for the last run: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gci-qa-master/5446/build-log.txt

**Comment by wonderfly** [comment]
cc/ @kubernetes/goog-image

**Comment by wonderfly** [comment]
Ping. This line, and may others, does include a newline at the end.

`b, err := combinedOutput(exec.Command("gcloud", "compute", "images", "describe-from-family", family, fmt.Sprintf("--project=%v", p), "--format=value(name)"))`

And because env vars were all quoted in e2e.sh, the newline char was preserved. I'd say the same for this line https://github.com/kubernetes/test-infra/pull/1657/files?diff=split#diff-1436ef97d6fb8da7bafb5dfc2b1da103R299

**Comment by wonderfly** [comment]
cc/ @krzyzacy

**Comment by fejta** [comment]
Thanks, just noticed this as well! Fixing in https://github.com/kubernetes/test-infra/pull/2040
