### ISSUE TITLE
ci-test-infra-triage is failing with an "index out of bounds" issue

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#20259]
Example Log: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-test-infra-triage/1338998617725210624

Current TG: https://testgrid.k8s.io/sig-testing-misc#triage

It looks like it's been failing regularly for the past day and a half; I think that this is going to result in some staleness issues with the triage dashboard

**Comment by spiffxp** [comment]
I think this is because kettle hasn't updated anything since ~December 1st.  https://github.com/kubernetes/test-infra/pull/20091 may unblock

However, we should still make the triage code robust to zero results

**Comment by spiffxp** [comment]
https://testgrid.k8s.io/sig-testing-misc#triage has been green since it's got data to cluster again

https://github.com/kubernetes/test-infra/pull/20409 fixes the index out of range that was causing triage to fail with zero builds
