### ISSUE TITLE
ci-kubernetes-e2e-windows-gce jobs not setting up Windows nodes

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/test-infra#20285]
**What happened**:
The `ci-kubernetes-e2e-windows-gce-1909` and `ci-kubernetes-e2e-windows-gce-2019` jobs on SIG Release/master-informing board are currently failing because its cluster isn't setting up the Windows nodes. 

From [this run last week](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1909/1337549648977465344):
```
Waiting for 6 ready nodes. 3 ready nodes, 3 registered. Retrying.
Detected 3 ready nodes, found 3 nodes out of expected 6. Your cluster may not be fully functional.
NAME                                     STATUS                     ROLES    AGE   VERSION
e2e-6b1885b066-d872a-master              Ready,SchedulingDisabled   <none>   25m   v1.21.0-alpha.0.279+0e2bf1e49f704b
e2e-6b1885b066-d872a-minion-group-fwnn   Ready                      <none>   25m   v1.21.0-alpha.0.279+0e2bf1e49f704b
e2e-6b1885b066-d872a-minion-group-xw17   Ready                      <none>   25m   v1.21.0-alpha.0.279+0e2bf1e49f704b
2020/12/12 00:39:59 process.go:155: Step './hack/e2e-internal/e2e-up.sh' finished in 29m56.183405269s
```

**What you expected to happen**:

From [the last successful run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019/1337521212468760576):
```
Waiting for 6 ready nodes. 3 ready nodes, 6 registered. Retrying.
Found 6 node(s).
NAME                                           STATUS                     ROLES    AGE     VERSION
e2e-73378c628b-4bd70-master                    Ready,SchedulingDisabled   <none>   4m14s   v1.21.0-alpha.0.273+7c60d8e1080100
e2e-73378c628b-4bd70-minion-group-pb4q         Ready                      <none>   3m50s   v1.21.0-alpha.0.273+7c60d8e1080100
e2e-73378c628b-4bd70-minion-group-vdt3         Ready                      <none>   3m48s   v1.21.0-alpha.0.273+7c60d8e1080100
e2e-73378c628b-4bd70-windows-node-group-099c   Ready                      <none>   23s     v1.21.0-alpha.0.273+7c60d8e1080100
e2e-73378c628b-4bd70-windows-node-group-lvhx   Ready                      <none>   20s     v1.21.0-alpha.0.273+7c60d8e1080100
e2e-73378c628b-4bd70-windows-node-group-pfp2   Ready                      <none>   23s     v1.21.0-alpha.0.273+7c60d8e1080100
```

**Please provide links to example occurrences, if any**:
TestGrid links: 
- https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-master
- https://testgrid.k8s.io/sig-release-master-informing#gce-windows-1909-master

I've linked 2 Spyglass occurrences above for the 1909 job, but here is a third: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019/1339652292328034304

**Anything else we need to know?**:
Logging this in k/test-infra since I figured this probably has more to do with the infra. Let me know if this belongs in k/k instead.

From the prow job config from the last successful run and the first failure there seems to be no major differences (they use the same kubekins image).

Curiously, the versions of these jobs that are running on the [1.20-informing](https://testgrid.k8s.io/sig-release-1.20-informing) board don't seem to have this problem (they're a little flaky, but not failing outright).

/sig windows

**Comment by BenTheElder** [comment]
@kubernetes/sig-windows-bugs

**Comment by thejoycekung** [comment]
Closing this because it's no longer happening
