### ISSUE TITLE
1.6 Release Testing Infrastructure

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/test-infra#2029]
The [1.6 branch](https://github.com/kubernetes/kubernetes/tree/release-1.6) has been cut and we're off! Let's get the release infra going so we can be confident in the quality of the release.

I'm going to send an email to SIG leads to find out what additional tests we should be running and will update this when I hear back.

The following tests should be setup to be run on the 1.6 release branch:
### Build / Verify
- [x] `ci-kubernetes-build-1.6` (Build)
- [x] `ci-kubernetes-verify-release-1.6` (Verify)
- [x] `ci-kubernetes-test-go-release-1.6` (Unit Test)
- [x] `ci-kubernetes-federation-build-1.6` (Federation Build)

### E2E
- [x] `ci-kubernetes-e2e-gce-release-1.6` (GCE)
- [x] `ci-kubernetes-e2e-gci-gce-release-1.6` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gke-release-1.6` (GKE)
- [x] `ci-kubernetes-e2e-gci-gke-release-1.6` (GCI-GKE)
- [x] `ci-kubernetes-e2e-aws-release-1.6` (AWS) #2092

### Slow
- [x] `ci-kubernetes-e2e-gce-slow-release-1.6` (GCE)
- [x] `ci-kubernetes-e2e-gci-gce-slow-release-1.6` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gke-slow-release-1.6` (GKE)
- [x] `ci-kubernetes-e2e-gci-gke-slow-release-1.6` (GCI-GKE)

### Serial
- [x] `ci-kubernetes-e2e-gce-serial-release-1.6` (GCE)
- [x] `ci-kubernetes-e2e-gci-gce-serial-release-1.6` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gke-serial-release-1.6` (GKE)
- [x] `ci-kubernetes-e2e-gci-gke-serial-release-1.6` (GCI-GKE)

### Federation
- [x] `ci-kubernetes-e2e-gce-federation-release-1.6` (GCE)

### Alpha
- [x] `ci-kubernetes-e2e-gce-alpha-features-release-1.6` (GCE)
- [x] `ci-kubernetes-e2e-gci-gce-alpha-features-release-1.6` (GCI-GCE)

### Scalability
- [x] `ci-kubernetes-e2e-gce-scalability-release-1.6` (GCE)
- [x] `ci-kubernetes-e2e-gci-gce-scalability-release-1.6` (GCI-GCE)

### Ingress
- [x] `ci-kubernetes-e2e-gci-gce-ingress-release-1.6` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gci-gke-ingress-release-1.6` (GCI-GKE)

### Reboot
- [x] `ci-kubernetes-e2e-gce-reboot-release-1.6` (GCE)
- [x] `ci-kubernetes-e2e-gci-gce-reboot-release-1.6` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gke-reboot-release-1.6` (GKE)
- [x] `ci-kubernetes-e2e-gci-gke-reboot-release-1.6` (GCI-GKE)

### Soak
- [x] `ci-kubernetes-soak-gce-1.6-deploy` (GCE)
- [x] `ci-kubernetes-soak-gce-1.6-test` (GCE)
- [x] `ci-kubernetes-soak-gci-gce-1.6-deploy` (GCI-GCE)
- [x] `ci-kubernetes-soak-gci-gce-1.6-test` (GCI-GCE)

### Node
- [x] `ci-kubernetes-node-kubelet-1.6`

### Testgrid
- [x] Create new page for 1.6 release
- [x] Populate page with results from the tests above

**Comment by ethernetdan** [comment]
Creating this issue to track ongoing work - @ixdy mind updating this as progress is made?

**Comment by ixdy** [comment]
We're going to need upgrade/skew jobs too - are we tracking that in a separate issue?

**Comment by ethernetdan** [comment]
@ixdy about to create it now 😊

**Comment by ethernetdan** [comment]
@dchen1107 are there additional Node suites that should be included for 1.6?

**Comment by ixdy** [comment]
Starting to create jobs.
http://k8s-testgrid.appspot.com/release-1.6-all and http://k8s-testgrid.appspot.com/release-1.6-blocking will get updated with jobs as I add them.

**Comment by ixdy** [comment]
Looking at [the release infra](https://github.com/kubernetes/release/blob/master/lib/releaselib.sh#L100-L117), it looks like the jobs we need running to cut a release are
* Main Job
  * ci-kubernetes-e2e-gce-release-1.6
* Secondary Jobs
  * ci-kubernetes-e2e-gce-serial-release-1.6                                                                                                    
  * ci-kubernetes-kubemark-5-gce-release-1.6                                           
  * ci-kubernetes-e2e-gce-reboot-release-1.6                                           
  * ci-kubernetes-e2e-gce-scalability-release-1.6                                      
  * ci-kubernetes-test-go-release-1.6                                                  
  * ci-kubernetes-cross-build-release-1.6                                              
  * ci-kubernetes-e2e-gke-serial-release-1.6                                           
  * ci-kubernetes-e2e-gke-release-1.6                                                  
  * ci-kubernetes-e2e-gke-slow-release-1.6

Incidentally, ci-kubernetes-cross-build-release-1.6 looks like a bug - we do have a cross-build job already, but it doesn't have "cross-" in the name,

**Comment by ixdy** [comment]
GKE jobs are all created, but they are currently failing due to a configuration error. I think this has been fixed, and hopefully they should start passing by EOD.

**Comment by ixdy** [comment]
Open questions:
* Do we need a kubemark job?
* Do we need non-cri jobs?

**Comment by ixdy** [comment]
All projects on this list are created, I think. I'd appreciate assistance in making sure things appear to be working. @marun

**Comment by ixdy** [comment]
Need someone to triage http://k8s-testgrid.appspot.com/release-1.6-blocking#Summary but I think my work here is done.
