### ISSUE TITLE
Migrate sig-network jobs to podutils

### ISSUE THREAD

**Issue by rikatz** [kubernetes/test-infra#20324]
**What should be cleaned up or changed**: Change sig-network jobs to use podutils

**Provide any links for context**: https://gist.github.com/dims/c1296f8ed42238baea0a5fcae45f4cf4#file-notes-md

**Comment by rikatz** [comment]
@aojea wanna close this one and wait like...3 months and we can start migrating again?

**Comment by aojea** [comment]
since you already migrated one, and podutils fixed the problems with the graphs, I think we can go ahead ... if there are volunteers to do it, I have low bandwidth these days :)

**Comment by rikatz** [comment]
me and @jayunit100 will volunteer some folks ;x

@mattfenwick @knabben let's put this in our backlog. But I can deal with that also tomorrow :)

**Comment by knabben** [comment]
I can help in the effort to migrate them.. maybe split the workload
I'm curious about this migration procedure.

**Comment by rikatz** [comment]
yes, let's talk about that on sunday triage party, sounds good?

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/reopen
Would be cool to see https://github.com/kubernetes/test-infra/pull/20864 picked back up and use this as a pilot to write a guide on migrating from bootstrap to pod-uytils

**Comment by aojea** [comment]
> I can help in the effort to migrate them.. maybe split the workload
> I'm curious about this migration procedure.

@rikatz @knabben things changed since this comment, right ?

/help wanted
