### ISSUE TITLE
No SNAT tests  on calico GCE don't pass

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/test-infra#20321]
**What happened**:

Looks like the "No SNAT" semantic on GCE with calico as the policy provider doesn't pass.
Curious about
- is this because GCE doesn't support the No SNAT mode ? 
- is it somehow related to running calico on top of GCE ?

Likely the former.

To investigate, I ran calico on kind 5 times in a row with this test:

```
KUBECONFIG=/Users/jayunit100/.kube/config .//_output/local/go/bin/e2e.test --ginkgo.focus="without SNAT" --dump-logs-on-failure=false
``` 

And it ALWAYS passed.  So I suspect its GCE related. 

**What you expected to happen**:

The `No SNAT` test would pass on GCE / calico networkpolicy jobs

**How to reproduce it (as minimally and precisely as possible)**:

Run the test-infra networkpolicy job, but remove the `SNAT` ginkgo.skip field

**Comment by BenTheElder** [comment]
This repo is the wrong place to ask for GCE networking help 🙃 , this seems like a bug for k/k or k/cloud-provider-gcp
