### ISSUE TITLE
Test grid is showing Internal Error for ppc64le-conformance

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/test-infra#20335]
**What happened**: The test grid dashboard that displays results of ppc64le-conformance is showing Internal Error.
https://testgrid.k8s.io/sig-node-ppc64le#conformance

**What you expected to happen**:
The results should be updated with the latest data from GCS.
**_https://testgrid.k8s.io/sig-node-ppc64le#conformance&grid=old is showing the updated runs._**

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/conformance-ppc64le#Periodic%20ppc64le%20conformance%20test%20on%20local%20cluster
https://testgrid.k8s.io/conformance-ppc64le#Periodic%20ppc64le%20conformance%20test%20on%20local%20cluster%20with%20containerd%20as%20runtime

**Anything else we need to know?**:
This error is observed after the below PR which was submitted for customizing the column headers.
https://github.com/kubernetes/test-infra/pull/20282
As the test grid dashboard says, also tried to reduce the days_of_results to 7 rather than the default value of 15
https://github.com/kubernetes/test-infra/pull/20303
But even this didn't help!

**Comment by Rajalakshmi-Girish** [comment]
![image](https://user-images.githubusercontent.com/63038004/102962127-235aa800-450c-11eb-86e4-ee5b62f2f605.png)

**Comment by Rajalakshmi-Girish** [comment]
@fejta Any pointers, please?

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag ^^

**Comment by fejta** [comment]
The updater doesn't like this result and its empty junit artifact from Dec 18: https://prow.k8s.io/view/gcs/ppc64le-kubernetes/logs/periodic-kubernetes-conformance-test-ppc64le/1339908369233743872

**Comment by fejta** [comment]
I have a PR that fixes it. If you are available now and interested in reviewing it feel free to head on over and do so :) otherwise will try and get it reviewed tomorrow.

**Comment by Rajalakshmi-Girish** [comment]
Thanks for the quick fix! 👍

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> I have a PR that fixes it. If you are available now and interested in reviewing it feel free to head on over and do so :) otherwise will try and get it reviewed tomorrow.

I walked through the PR. It seems correct to me.

**Comment by Rajalakshmi-Girish** [comment]
@fejta Even the merge of the above PR doesn't seem to fix the internal error. The error still exists.

**Comment by dims** [comment]
@Rajalakshmi-Girish i think @fejta was talking about https://github.com/GoogleCloudPlatform/testgrid/pull/317 :)

**Comment by fejta** [comment]
That change has merged but it hasn't been deployed to production yet.

**Comment by Rajalakshmi-Girish** [comment]
I see the internal error gone and the latest results are displayed. Thanks @fejta 
![image](https://user-images.githubusercontent.com/63038004/103121967-76676300-46a4-11eb-85e9-1ff988b4d458.png)
