### ISSUE TITLE
1.6 Upgrade Testing Infrastructure

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/test-infra#2034]
In an addendum to #2029, setting up upgrade infra.

The following upgrade tests should run on the 1.6 release branch:
### kubectl Skew - Upwards
- [x] `kubernetes-e2e-gce-1.5-1.6-cvm-kubectl-skew`(GCE)
- [x] `kubernetes-e2e-gce-1.5-1.6-gci-kubectl-skew` (GCI-GCE)
- [x] `kubernetes-e2e-gke-1.5-1.6-cvm-kubectl-skew` (GKE)
- [x] `kubernetes-e2e-gke-1.5-1.6-gci-kubectl-skew` (GCI-GKE)

### kubectl Skew - Downwards
- [x] `kubernetes-e2e-gce-1.6-1.5-cvm-kubectl-skew` (GCE)
- [x] `kubernetes-e2e-gce-1.6-1.5-gci-kubectl-skew` (GCI-GCE)
- [x] `kubernetes-e2e-gke-1.6-1.5-cvm-kubectl-skew` (GKE)
- [x] `kubernetes-e2e-gke-1.6-1.5-gci-kubectl-skew` (GCI-GKE)

### Upgrade - 1.5 to 1.6
- [x] `kubernetes-e2e-gce-1.5-1.6-upgrade-cluster` (GCE)
- [x] `kubernetes-e2e-gke-container_vm-1.5-container_vm-1.6-upgrade-cluster` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-gci-1.6-upgrade-cluster` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.5-gci-1.6-upgrade-cluster` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-container_vm-1.6-upgrade-cluster` (GCI-GKE → GKE)

### Upgrade - 1.5 to 1.6 (New)
- [x] `kubernetes-e2e-gce-1.5-1.6-upgrade-cluster-new` (GCE)
- [x] `kubernetes-e2e-gke-container_vm-1.5-container_vm-1.6-upgrade-cluster-new` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-gci-1.6-upgrade-cluster-new` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.5-gci-1.6-upgrade-cluster-new` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-container_vm-1.6-upgrade-cluster-new` (GCI-GKE → GKE)

### Upgrade - 1.5 to 1.6 (Master)
- [x] `kubernetes-e2e-gce-1.5-1.6-upgrade-master` (GCE)
- [x] `kubernetes-e2e-gke-container_vm-1.5-container_vm-1.6-upgrade-master` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-gci-1.6-upgrade-master` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.5-gci-1.6-upgrade-master` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-container_vm-1.6-upgrade-master` (GCI-GKE → GKE)

### Upgrade - 1.4 to 1.6
- [x] `kubernetes-e2e-gke-container_vm-1.4-container_vm-1.6-upgrade-cluster` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.4-gci-1.6-upgrade-cluster` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.4-gci-1.6-upgrade-cluster` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.4-container_vm-1.6-upgrade-cluster` (GCI-GKE → GKE)

### Upgrade - 1.4 to 1.6 (New)
- [x] `kubernetes-e2e-gke-container_vm-1.4-container_vm-1.6-upgrade-cluster-new` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.4-gci-1.6-upgrade-cluster-new` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.4-gci-1.6-upgrade-cluster-new` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.4-container_vm-1.6-upgrade-cluster-new` (GCI-GKE → GKE)

### Upgrade - 1.4 to 1.6 (Master)
- [x] `kubernetes-e2e-gke-container_vm-1.4-container_vm-1.6-upgrade-master` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.4-gci-1.6-upgrade-master` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.4-gci-1.6-upgrade-master`(GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.4-container_vm-1.6-upgrade-master` (GCI-GKE → GKE)

**Comment by ethernetdan** [comment]
@saad-ali do we need downgrade testing for 1.6?

**Comment by ixdy** [comment]
kubectl skew jobs are running: http://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#Summary

**Comment by ixdy** [comment]
Did we intentionally exclude 1.4 - 1.6 GCE upgrade jobs from this list? @pwittrock

**Comment by ixdy** [comment]
cc @skriss

**Comment by skriss** [comment]
The 1.3 - 1.5 GCE jobs were excluded last time around per https://groups.google.com/forum/#!topic/kubernetes-release/g_aUkjw_E38

So I don't think they're critical, but nice-to-have
