### ISSUE TITLE
HTTP perf-dash should redirect to HTTPS instead of returning 404

### ISSUE THREAD

**Issue by adtac** [kubernetes/test-infra#20359]
**What happened**: http://perf-dash.k8s.io returns 404.

**What you expected to happen**: It should redirect to https://perf-dash.k8s.io instead.

**How to reproduce it (as minimally and precisely as possible)**: Go to http://perf-dash.k8s.io on your browser.

cc @mborsz

**Comment by BenTheElder** [comment]
perf-dash isn't hosted in this repo, it's hosted in https://github.com/kubernetes/k8s.io, you won't get good visibility for this here.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/k8s.io/search?q=perf-dash + https://github.com/kubernetes/perf-tests/tree/master/perfdash

since this is a bug in the source, filed against the latter
