### ISSUE TITLE
failing containerd test

### ISSUE THREAD

**Issue by vteratipally** [kubernetes/test-infra#20374]
**What happened**:
Test failing https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-gci

**What you expected to happen**:

the test should run successfully, the issue is that the containerd package couldn't be downloaded. 
error log
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce/1344800943668989952/artifacts/bootstrap-e2e-master/containerd-installation.log

**How to reproduce it (as minimally and precisely as possible)**:
curl -f --ipv4 --retry 6 --retry-delay 3 --silent --show-error https://storage.googleapis.com/cri-containerd-staging/containerd/latest

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce/1344800943668989952

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
Please file these bugs against containerd or Kubernetes or whatever repo is under test unless you suspect a bug in the CI system, this repo is for the infrastructure itself.

It appears this is fixed.
