### ISSUE TITLE
kubekins-e2e:v20201225-59e70a3-master used in test contains WIP code that is not submitted

### ISSUE THREAD

**Issue by mborsz** [kubernetes/test-infra#20403]
**What happened**:

When I was reading logs for https://prow.k8s.io/log?container=test&id=1347195315899338752&job=ci-kubernetes-e2e-gci-gce-scalability I noticed that it starts with:
```
Cloning into 'test-infra'...
From https://github.com/kubernetes/test-infra
 * branch                  refs/pull/20273/head -> FETCH_HEAD
Note: checking out 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 3c2c301ec4 Make it possible to override --logexporter-gcs-path
(...)
I0107 14:56:25.560] Image: gcr.io/k8s-testimages/kubekins-e2e:v20201225-59e70a3-master
```

Those lines are a part of https://github.com/kubernetes/test-infra/pull/20273 PR I was playing with last month. For some reason this has been included in kubekins-e2e image, without being submitted.

**What you expected to happen**:
Not submitted code is not included in live kubekins-e2e image.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/log?container=test&id=1347195315899338752&job=ci-kubernetes-e2e-gci-gce-scalability

**Anything else we need to know?**:

Most likely, my experimental bootstrap image has been included in the kubekins-e2e build (I'm sorry for that, I haven't expected that any bootstrap image can be included, I expected rather a process where some automatic tool builds new bootstrap image from known state).

@fejta @chases2 @kadirselcuk

How to fix that?
I'm thinking about triggering new bootstrap image build (with master), then update kubekins-e2e.

**Comment by mborsz** [comment]
I triggered a build of `gcr.io/k8s-testimages/bootstrap:v20210107-d5c67a7c21` from master branch   (at d5c67a7c21 commit).

It has finished now:
```
2021/01/07 16:27:42 Successfully built image: gcr.io/k8s-testimages/bootstrap:v20210107-d5c67a7c21 gcr.io/k8s-testimages/bootstrap:latest
```

Can you help me with releasing this?

**Comment by mborsz** [comment]
Or we can use 'gcr.io/k8s-testimages/bootstrap:v20210108-5927ee692c' which includes submitted #20276

**Comment by fejta** [comment]
> Please provide links to example occurrences, if any: https://prow.k8s.io/log?container=test&id=1347195315899338752&job=ci-kubernetes-e2e-gci-gce-scalability

These logs don't exist. Please provide a deck link and reopen.

**Comment by fejta** [comment]
Also please note:

```
W0108 15:02:38.893] **************************************************************************
bootstrap.py is deprecated!
test-infra oncall does not support any job still using bootstrap.py.
Please migrate your job to podutils!
https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md
**************************************************************************
```

Finally the most recent versions of these jobs https://testgrid.k8s.io/google-gce#gce-cos-master-scalability-100 no longer use this commit:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1347598028030087168 shows `"infra-commit": "3c2c301ec",` (artifacts -> finished.json)

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1347660928375590912 shows `  "infra-commit": "6d943af9d", `

**Comment by mborsz** [comment]
Thanks, it seems to be OK now.

We know that bootstrap.py is deprecated, the work I'm doing is to unblock migration out of bootstrap (see https://github.com/kubernetes/test-infra/issues/20275).
