### ISSUE TITLE
prow: add a Helm chart

### ISSUE THREAD

**Issue by colemickens** [kubernetes/test-infra#2041]
Even if it's just local to the test-infra repo, it might be nice to have a Helm chart for the prow components.

If there's interest, I can add this. I've written a Chart before with the parameterization that I think I'd want for Prow (things like needing to interpolate the DOMAIN name into the Ingress objects for places that are not using gce ingress controller, etc).

**Comment by spxtr** [comment]
I'm not very familiar with Helm, but it sounds like a great idea.

**Comment by cblecker** [comment]
A helm chart for this would be great! I can help review it if you need another set of eyes with helm experience :)

**Comment by colemickens** [comment]
Since a related issue was closed and in case someone else wants to look into this... I'm not actively working on this right now. If that changes, I'll update this comment/thread.

**Comment by kargakis** [comment]
Helm charts are fine but please don't make this the only way to install prow.

**Comment by spxtr** [comment]
@kargakis out of interest, 1) what is lacking with helm that makes you say this, and 2) what other installation method would you like to see?

**Comment by kargakis** [comment]
Helm adds additional dependencies on the cluster (Tiller). The current installation of k8s manifests is OK, once we have [native k8s Templates](https://github.com/kubernetes/community/blob/548eb7292d45a4af78e0141d33094130dfe6080a/contributors/design-proposals/templates.md), that could also be an option.

**Comment by kargakis** [comment]
https://github.com/samsung-cnct/prow-chart

**Comment by rverma-nikiai** [comment]
@fejta can we reopen this, currently, we don't have any community prow chart. There is one actively maintained by Cloudbees https://github.com/jenkins-x-charts/prow, along with their custom images as well as that had some dependency on their project exposecontroller.
