### ISSUE TITLE
client-go and boskos imports lead to go.mod replace hacks

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#20421]
**What should be cleaned up or changed**:

The go.mod file imports client-go@v11, but replaces it. The result is anyone importing k8s.io/test-infra needs to do the same - essentially we are polluting the downstream entire golang ecosystem, and propagating this `replace` requirement. In go 1.16, `go install` doesn't work if a go.mod has `replace` in it as well, making it even more annoying.

The fix, however, is not trivial. k8s.io/test-infra depends on sigs.k8s.io/boskos, and sigs.k8s.io/boskos depends on k8s.io/test-infra. This means we need both dependencies to change at the same time to break the "poisoned" client-go@v11 version.

I don't know a good way to actually change these in tandem. Its easy locally with temporary `replace ..` directives. Otherwise, it seems like it may require to push a broken commit of one of the repos, referring to the not-yet-existing fixed version of the other, but I am not sure that would actually work in practice.

Another alternative is to not have a circular dependency, by dropping one of the imports or merging to a monorepo. I am not sure the work involved there though.

**Provide any links for context**:

Similar issue: https://github.com/knative/test-infra/issues/2414

**Comment by howardjohn** [comment]
test-infra depends on boskos only for `kubetest`. It seems there is a kubetest2 in its own repo, so one option is to move out kubetest, or remove it if its been replaced with kubetest2.

Boskos deps:
```
$ rg --no-filename --no-line-number k8s.io/test-infra | sort | uniq -c | rg -v v0.0.0 | sort
      1         "k8s.io/test-infra/prow/config/secret"
      1         "k8s.io/test-infra/prow/flagutil"
      1         "k8s.io/test-infra/prow/simplifypath"
      2         "k8s.io/test-infra/pkg/flagutil"
      2         "k8s.io/test-infra/prow/pjutil"
      2         prowflagutil "k8s.io/test-infra/prow/flagutil"
      3         "k8s.io/test-infra/prow/config"
      3         "k8s.io/test-infra/prow/interrupts"
      3         prowmetrics "k8s.io/test-infra/prow/metrics"
      8         "k8s.io/test-infra/prow/logrusutil"
```
Seem more involved, but also mostly just smaller utilities that could probably be dropped with some investment

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/boskos/issues/89
https://github.com/kubernetes/test-infra/pull/20422#issuecomment-871735014

**Comment by BenTheElder** [comment]
This one is somewhat involved in the ecosystem here and doesn't necessarily have the most straightforward solution so I am *not* tagging this "good first issue", however it's something we should do that nobody has committed to yet, I doubt anyone will commit to soon (understaffed area for sure) and might be an interesting project if someone feels up to it.

You'll need to disentangle the imports between these projects by finding a way to split up the modules/dependencies without breaking any of the existing builds. There are multiple possible approaches discussed across the linked threads.

**Comment by stevekuznetsov** [comment]
The dependency from the `boskos` client back to `test-infra` is through the auto-reloading secret manager, which is fairly useless for one-shot client uses like `kubetest`. We could just factor the `boskos` client to accept a generator for it's credentials and use the secret agent where necesssary (but not in kubetest)

**Comment by howardjohn** [comment]
Can this be re-opened?

**Comment by munnerz** [comment]
I think I've got a very simple solution for this...

/assign

**Comment by munnerz** [comment]
Opened #26956
