### ISSUE TITLE
Link test failures from Gubernator to issue search

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/test-infra#2043]
Most times when I am checking to see whether something is a flake, I end up having to go back to the Kubernetes Git repo, search for the name of the test, and see whether a flake issue already so I can comment on it.  It would be a usability win to have a link from every test failure that punts the user to kubernetes/kubernetes issue search with the search input pre-filled with the test name (since search isn't perfect, it's likely the user will want to change the search afterwards, but this would reduce the amount of manual navigation).

1. See test failed in GitHub PR
2. Click link for test failure
3. See a test case failed that I don't recognize
4. Copy name of test (fiddly because it is a link) 
5. Navigate to GitHub.com/kubernetes/kubernetes
6. Paste test name into search bar
7. Dig through issues until I find a match.

This could replace 4-6 (which takes 10-15s when debugging a single PR, or many minutes if debugging lots of jobs)

**Comment by fejta** [comment]
Please update and/or close

**Comment by smarterclayton** [comment]
I think this is still relevant.  Not sure the exact mechanism that will be best, but should be cheap.
