### ISSUE TITLE
gcb-docker-gcloud: support docker-cli 20.10

### ISSUE THREAD

**Issue by chewong** [kubernetes/test-infra#20443]
Is there any plan to support docker-cli 20.10 within gcb-docker-gcloud container?

**Comment by BenTheElder** [comment]
I would imagine the intent should be to match whatever server version GCB is shipping. This image is also not with a current owner I think hhttps://github.com/kubernetes/test-infra/commits/master/images/gcb-docker-gcloud

**Comment by spiffxp** [comment]
/close
The image was most recently rebuilt via https://github.com/kubernetes/test-infra/pull/22977

Since the image in question is based on golang, which is based on debian, we're using whatever upstream provides.

```
$ docker run -ti --rm --entrypoint /usr/bin/docker gcr.io/k8s-testimages/gcb-docker-gcloud version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.5
 Git commit:        f0df35096d5f5e6b559b42c7fde6c65a2909f7c5
 Built:             Sun Jun  6 00:08:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```
