### ISSUE TITLE
Kettle Metrics Enhancment

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#20455]
**What would you like to be added**:
The current Kettle [Build Object](https://github.com/kubernetes/test-infra/blob/master/kettle/schema.json) is limited to parsing `started.json` and `finished.json`. However, there is quite a lot of additional data that could prove useful, especially given the ability to build DataStudio Dashboards (See #20067 ). 

Some fields of note that could be useful from parsing [`podinfo.json`](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_vsphere-csi-driver/558/pull-vsphere-csi-driver-verify-fmt/1349069445066133504/podinfo.json):
- pod.metadata.annotations.testgrid-dashboards Ex: `"presubmits-test-infra"`
- pod.metadata.annotations.testgrid-tab-name
- pod.metadata.namespace
- pod.metadata.annotations.testgrid-alert-email

** Each of these would be nullable and ignored if not present

With Kettle in flux, now is also a good time to make some changes in how the Job artifacts are collected and parsed to make the process cleaner and more robust.

To properly traverse this space we should build some CUJs that cover the breath of K8s community members. With a solid understanding of needs, we can tailor the metrics collection to meet those needs/asks.

**Why is this needed**:
This would greatly expand the range of metrics we can build upon. I would also create a framework to more easily add metrics in the future.

/assign
/cc @amwat @spiffxp @cjwagner @RobertKielty

**Comment by spiffxp** [comment]
/assign
I mentioned a few ideas verbally today, I'll jot them down here later

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/issues/20886 is one of them

A more generic approach that would satisfy this is plumbing through the tag(s) of the container(s) run as part of the job
