### ISSUE TITLE
gce e2e federation tests broken

### ISSUE THREAD

**Issue by csbell** [kubernetes/test-infra#2046]
Issued k8s-bot federation gce e2e test this and build wants to execute build-federation.sh which doesn't exist in the test-infra repo.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41942/pull-kubernetes-federation-e2e-gce/44/

cc: @nikhiljindal

**Comment by krzyzacy** [comment]
dup https://github.com/kubernetes/test-infra/issues/2074
