### ISSUE TITLE
Please add search functionality on testgrid for individual test names

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#20524]
**What would you like to be added**:

Somewhat related to #14018, a thing I have struggled with is trying to locate the results of a particular test in testgrid. I often don't know what the job is, only the failing test name. I can sometimes find it via a go.k8s.io/triage search, but that only works if the test is failing; sometimes I just want the logs of a successful test run for investigation purposes.

**Why is this needed**:

It is really hard to lifecycle individual tests and find data on how they're working when I don't know the job a given test is under. There are so many jobs that I can't just click on each to hunt for it.

**Comment by MushuEE** [comment]
This might be best migrated to an issue in https://github.com/GoogleCloudPlatform/testgrid

Could you give me an example of a failing test that you would like to find? I am curious if I would be able to leverage our BigQuery table to reverse search for a job a test is associated with. If I can, I should be able to write a quick tool to perform the reverse search.

**Comment by spiffxp** [comment]
/area testgrid
/assign @chases2 @michelle192837 @fejta 
Yeah this is probably a testgrid-specific issue, but as grant said there may be something k8s-specific we can do sooner without testgrid

**Comment by fejta** [comment]
Take the deck link like https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ubuntu2-k8sbeta-slow/1352338019012579328/ and click on "testgrid", which will take you to https://testgrid.k8s.io/sig-release-generated#gce-ubuntu2-k8sbeta-slow


https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/1352231310218760192 goes to https://testgrid.k8s.io/sig-release-1.20-blocking#gce-cos-k8sbeta-default etc

**Comment by ehashman** [comment]
@fejta I don't think that addresses what I'm looking for: I want to be able to search in testgrid for a given test name, and find the jobs/grids it's part of. For example, I know I care about the results of the e2e test *"[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container"*. I *could* search for it here: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=never%20report%20success%20for%20a%20pending%20container

But I actually want to pull some test logs from *successful* runs, which won't show up there. So if the test never fails between the various UIs I can't find the jobs it's part of.

**Comment by fejta** [comment]
How do you know you care about "[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container"?

Because you have a deck link:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=never%20report%20success%20for%20a%20pending%20container

Open any of the latest failure links:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-proto/1352333739027337216

Click on testgrid:

https://testgrid.k8s.io/sig-node-containerd#e2e-cos-proto

**Comment by fejta** [comment]
The above is available now and mostly gets the job done. AKA this debugging use case is supported:

* I am root causing a bug about FOO failing that includes a link to an example failure. I want to get to the history of FOO from that failure.

On the other hand, testgrid is not optimized to answer the following type of question:
* I want to type FOO and find every possible prow job that runs a job that contains FOO

**Comment by ehashman** [comment]
> On the other hand, testgrid is not optimized to answer the following type of question:
> 
>     * I want to type FOO and find every possible prow job that runs a test that contains FOO

Yes, I know it's not optimized for this... this is my feature request. It's fine to close this as WONTFIX, but I just want to make sure that we're clear on what I'm asking for :)

It is really hard to pull CI logs for *passing* tests and right now that is a thing that I need!
