### ISSUE TITLE
Update auto-prioritization to use new labels

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2053]
The flake manager in mungegithub seems to still use the old convention (e.g. `priority/p0` instead of `priority/critical-urgent`.  

Might be as simple as just changing

https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/sync/issue-sync.go#L52

@calebamiles @ethernetdan @idvoretskyi

**Comment by bgrant0607** [comment]
All automatically filed issues should use priority/failing-test. If we can distinguish whether it's a flake or not, it should also be labeled kind/flake.

**Comment by Sevii** [comment]
I have opened a PR to address the labeling change from P0/2/3 => priority/critical-urgent/... in flake-manager.go and issue-sync.go. #2107

**Comment by Sevii** [comment]
I made another PR which should produce the desired behavior. It ignores the auto-prioritization code in flake-manager.go.
@grodrigues3 
https://github.com/kubernetes/test-infra/pull/2222
