### ISSUE TITLE
Match bot retest labels and Jenkins status values to be identical

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/test-infra#2059]
When a job fails, it would be convenient if the retest command was something I could cut and paste from the GitHub PR status.

For instance, instead of the GitHub status saying `Jenkins GCE Node e2e`, maybe it should say `k8s-bot node e2e`, with the kick instruction being `@k8s-bot node e2e test this`.  That would remove the need to have to look up the name in the prow config file, as well as the need to have the separate column for it in the results.  It's hard to understand why we need display names for these (when the job name and the kick string could be identical in most cases).

**Comment by krzyzacy** [comment]
there's instruction you can copy/paste from the k8s-bot comment?

**Comment by fejta** [comment]
/assign

FYI we are slowly making this change.

**Comment by fejta** [comment]
Unit tests now validate that a) the context matches the job name and b) `@k8s-bot job-name test this` reruns the job
