### ISSUE TITLE
Prow: malformed prowjob should have been GCed

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#20595]
**What happened**:

A malformed prowjob that would have never been scheduled a pod due to a typo in `cluster` field, has been hanging around for more than 4 days, and prow-controller-manager keeps on reporting errors on this prowjob.

**What you expected to happen**:

The prowjob should have been GCed earlier, maybe the same as max pod age (48 hours)?

**How to reproduce it (as minimally and precisely as possible)**:

Create a prowjob with `cluster` defined to be a cluster not exist.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by chaodaiG** [comment]
An initial thought, as discussed with @cjwagner , is that sinker can delete prowjob whose age is over the max prowjob age. Quoted from offline discussion:

```
PJ **runtime** should really be controlled with the decoration timeout and graceperiod since that can be configured granularly. The max PJ age is to allow the PJ resources to exist beyond the lifetime of the pod.
```

**Comment by chaodaiG** [comment]
CC @cjwagner @alvaroaleman

**Comment by alvaroaleman** [comment]
I would argue this is working as intended. Maybe it is not a typo and someone is planning on adding that cluster? Prow can't know and should IMHO not make assumptions

**Comment by chaodaiG** [comment]
Agree that prow shouldn't make assumptions. This behavior of a prowjob hanging for more than 4 days, however, is concerning. I still think it should be GCed automatically instead of prow operator manually remove them.

**Comment by alvaroaleman** [comment]
>  This behavior of a prowjob hanging for more than 4 days, however, is concerning. I still think it should be GCed automatically instead of prow operator manually remove them.
Well, Sinker will eventually do that.

We could probably fix this TODO to make it spam the log less: https://github.com/kubernetes/test-infra/blob/e3a8e137c7b928824d358ee55be35806f7aaa8fa/prow/plank/reconciler.go#L552-L553

**Comment by chaodaiG** [comment]
Agreed that fixing this TODO will do, so I'm onboard with it. @cjwagner what do you think?

**Comment by cjwagner** [comment]
> > This behavior of a prowjob hanging for more than 4 days, however, is concerning. I still think it should be GCed automatically instead of prow operator manually remove them.
> 
> Well, Sinker will eventually do that.

@alvaroaleman That doesn't seem to be the case. The PJ was older than the max PJ age and sinker didn't GC it. That does not seem to be WAI to me, why would we allow PJs to persist beyond the max PJ age in this scenario?

**Comment by alvaroaleman** [comment]
> The PJ was older than the max PJ age and sinker didn't GC it. That does not seem to be WAI to me, why would we allow PJs to persist beyond the max PJ age in this scenario?

Ah, that wasn't clear from the description. That is a bug in sinker then.

**Comment by chaodaiG** [comment]
> > The PJ was older than the max PJ age and sinker didn't GC it. That does not seem to be WAI to me, why would we allow PJs to persist beyond the max PJ age in this scenario?
> 
> Ah, that wasn't clear from the description. That is a bug in sinker then.

My bad, should have put this in bug body instead of the first comment

**Comment by alvaroaleman** [comment]
/reopen
Presumably the "job with invalid cluster doesn't get GCd" issue still exists
