### ISSUE TITLE
RBE bazel jobs are timing out

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#20628]
**What happened**:

There are several prow jobs started failing timing out after 2 hours, inspecting the logs and they were hanging at bazel test phase.

https://testgrid.k8s.io/sig-release-master-blocking#bazel-build-master
https://prow.k8s.io/?repo=kubernetes%2Ftest-infra&job=pull-test-infra-integration
https://prow.k8s.io/?repo=kubernetes%2Ftest-infra&job=pull-test-infra-bazel

One noticeable common factor among them is the usage of RBE

**Comment by chaodaiG** [comment]
CC @fejta

**Comment by fejta** [comment]
Lots of CI uses bazel, and bazel almost always uses RBE.

**Comment by cjwagner** [comment]
Some more ongoing examples:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/20619/pull-test-infra-bazel/1354526643548327936
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/20619/pull-test-infra-integration/1354526643657379840

**Comment by chaodaiG** [comment]
Not using RBE in https://github.com/kubernetes/test-infra/pull/20626 can make `pull-test-infra-integration` job [pass](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/20626/pull-test-infra-integration/1354541217169281024), while the same job is now consistently timing out in other PRs https://prow.k8s.io/?repo=kubernetes%2Ftest-infra&job=pull-test-infra-integration

**Comment by CecileRobertMichon** [comment]
running into this in #20630

**Comment by alvaroaleman** [comment]
This appears to block all merges into this repo, last merge was 9 hours ego and there is a bunch of merge-eligible PRs stuck in retesting: https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+is%3Aopen+label%3Aapproved+label%3Algtm+-label%3A%22do-not-merge%2Fhold%22

**Comment by justaugustus** [comment]
FYI @kubernetes/release-engineering

**Comment by chaodaiG** [comment]
Current hypothesis is different bazel versions in k8s/test-infra and k8s/kubernetes caused confusion to RBE, and #20632 is an attempt to fix

**Comment by chaodaiG** [comment]
Seeing tests reliably going through now:
https://prow.k8s.io/?repo=kubernetes%2Ftest-infra&job=pull-test-infra-integration
https://prow.k8s.io/?repo=kubernetes%2Ftest-infra&job=pull-test-infra-bazel

**Comment by chaodaiG** [comment]
The root cause of this problem was still not very clear, but according to RBE team it's possible that one of their dependencies had a bad release which was mitigated yesterday.

Checked again and all affected tests are passing now, so closing this bug.

/close
