### ISSUE TITLE
Prow's unit tests assume `master` as the default branch which is not true for newer versions of git.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#20627]
**What happened**:
Newer versions of `git` default to naming the initial branch `main` rather than `master`.
Prow unit tests make assumptions about the default branch name so most unit tests involving git result in errors like the following:
- `Error checking out master: /usr/bin/git [checkout master]: exit status 1, error: pathspec 'master' did not match any file(s) known to git`
- `failed to get baseSHA: /usr/bin/git [rev-parse master]: exit status 128, fatal: ambiguous argument 'master': unknown revision or path not in the working tree.`

**What you expected to happen**:
See the slack discussion here: https://kubernetes.slack.com/archives/CDECRSC5U/p1611770593024000
In particular, from @alvaroaleman:
> in [that stackoverflow](https://stackoverflow.com/questions/42871542/how-can-i-create-a-git-repository-with-the-default-branch-name-other-than-maste/42871621#42871621) they mention that you can explicitly specific that branch as arg to git init via --initial-branch=name. Since we apparently make assumptions about that branches name, passing that arg when doing git init sounds like a good idea to me

**How to reproduce it (as minimally and precisely as possible)**:
Update to a new version of git or configure the global `init.defaultBranch` configuration option to `main` rather than master and then run the Prow unit tests.

cc @alvaroaleman

**Comment by alvaroaleman** [comment]
Fixed in #20730
/close
