### ISSUE TITLE
GCE jobs should  store coredns logs

### ISSUE THREAD

**Issue by JornShen** [kubernetes/test-infra#20659]
**What happened**:

In some failed task of network, they refer to dns effective.  like some case about externalName type service.
But we can't see any logs about dns in prow.k8s.io artifacts. This will block us to locate the problems sometimes.

jobs like 

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1350010433976668160

**What you expected to happen**:

we can see detailed dns logs in jobs presentation prow.k8s.io artifacts.

dns logs open method ref:  https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#

ref issue: https://github.com/kubernetes/kubernetes/issues/98104

**Comment by JornShen** [comment]
ping @aojea

**Comment by aojea** [comment]
@BenTheElder @spiffxp can you tell us if:

1. is ok to implement it
2. give us some guidance to where this has to be implemented, I think it should be in k/k/hack, but I´m not sure

**Comment by BenTheElder** [comment]
I could've sworn we dumped all pod-logs ...

https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh <-- most likely starting somewhere from this script.

**Comment by aojea** [comment]
/assign @JornShen 
:)

**Comment by BenTheElder** [comment]
SIG scalability will probably have thoughts on the implications of changing log dumping, I forget if this script is still used in scale jobs. cc @wojtek-t

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/98591#discussion_r569184958 ... I forgot scalability was moving this to test-infra. we maybe should get an area label for this.

**Comment by spiffxp** [comment]
/sig testing
/sig scalability
/reopen
/remove-lifecycle rotten
Not clear to me whether this was ever resolved
