### ISSUE TITLE
How to interpret testgrid overall build failure

### ISSUE THREAD

**Issue by dguendisch** [kubernetes/test-infra#20662]
**What happened**:
[Gardener](https://github.com/gardener/gardener) reports conformance tests (and others) since some years into testgrid for various cloudproviders and various k8s versions.
We noticed recently that while all single tests are green, the overall test result in testgrid is marked as `Failed` (since a few days or weeks), see e.g. https://testgrid.k8s.io/conformance-gardener#Gardener,%20v1.20%20AWS but the same pattern is true for all of our reportings on any cloudprovider and k8s version.
I'm not aware of any changes in our test infrastructure or reporting.
Can you help me to understand the reason for marking the overall tests as `Failed`?

**What you expected to happen**:
Overall tests marked as `Passed` when all single tests are `Passed`

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/conformance-gardener#Gardener,%20v1.20%20AWS
https://testgrid.k8s.io/conformance-gardener#Gardener,%20v1.19%20GCE
https://testgrid.k8s.io/conformance-gardener#Gardener,%20v1.18%20Azure
...

**Anything else we need to know?**:

**Comment by michelle192837** [comment]
Sorry to miss this! I think this is clearer now with the new updater (see the message now on the Overall row that notes `finished.json missing "passed"`), so it sounds like your finished.json file needs to report the pass/fail status of the job (see something like https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-cni-amazon-vpc/1390384696189259776/finished.json), and it should be fixed!
