### ISSUE TITLE
divide up job scripts into subdirectories

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#2067]
There are too many files in the [jobs/](https://github.com/kubernetes/test-infra/tree/master/jobs) directory. It's hard to find the configurations I care about.

**Comment by ixdy** [comment]
A proposal: create `ci`, `pull`, and `maintenance` subdirectories of `jobs/`.

Under `ci` and `pull`, create repo subdirectories (like `kubernetes`, `test-infra`, etc).

Move job scripts into the respective subdirectories, removing the `{ci,pull,maintenance}-{repo}-prefix`.

For example, `jobs/ci-kubernetes-e2e-gce.env` becomes `jobs/ci/kubernetes/jobs/e2e-gce.env`, `jobs/pull-test-infra-bazel.sh` becomes `jobs/pull/test-infra/bazel.sh`, and `jobs/maintenance-hourly.sh` becomes `jobs/maintenance/hourly.sh`.

(The maintenance jobs are actually kinda weird, since we have things like `maintenance-pull-clean-ssh-keys.sh` - should that go into `maintenance/` or `pull/`? I'd vote for `maintenance/`.)

Thoughts?

**Comment by fejta** [comment]
Sounds fine to me

**Comment by krzyzacy** [comment]
seems this is moving towards get away from env files (to kubetest flags) + generate all the configs. the subdir is not likely going to happen.
