### ISSUE TITLE
Prow issue:[kubernetes/release]pull-release-verify failed

### ISSUE THREAD

**Issue by houfangdong** [kubernetes/test-infra#20681]
I submitted a PR:[debian-base](https://github.com/kubernetes/release/pull/1880), but the error shows that it seems to be caused by a network problem, please have a look. The PR link is:
[pull-release-verify](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/release/1880/pull-release-verify/1355840123509411840)
Please help me, thanks
/sig testing
/area prow
@krzyzacy
@BenTheElder

**Comment by houfangdong** [comment]
Check the log for ./hack/verify-go-mod.sh update failed，具体失败命令为：
![image](https://user-images.githubusercontent.com/60801291/106384259-d0c2b480-6404-11eb-9e1a-10331b90a8d7.png)

**Comment by houfangdong** [comment]
The problem has been solved, see [#1885](https://github.com/kubernetes/release/pull/1885) for details, please close this problem.thanks
/sig testing
/area prow

**Comment by BenTheElder** [comment]
/close
(You can do this yourself)
If a test fails once please try /retest

**Comment by houfangdong** [comment]
@BenTheElder
Ok i see, thanks.

**Comment by houfangdong** [comment]
@BenTheElder
Ok i see, thanks
