### ISSUE TITLE
GitHub Actions Support in Prow?

### ISSUE THREAD

**Issue by midnightconman** [kubernetes/test-infra#20713]
Now that github enterprise 3.0 is in RC, github actions and packages will be coming to GHE soon. As such, we will be looking at leveraging github actions where we can. Using prow internally, this means we are interested in how prow can interact with github actions... has there been any thought to building a github actions operator or how prow might leverage github actions?

**Comment by alvaroaleman** [comment]
What would a github actions operator do?

Tide already respects the result of github actions. Be aware though that they do not have any kind of retesting mechanics. If you create a PR that passes tests and the base branch changing in an incompatible way, you will end up with broken code. This is the main reason we discourage using them.

/area prow

**Comment by fisherxu** [comment]
> Tide already respects the result of github actions.

@alvaroaleman The project I maintained are using prow-bot and github action, but I found that when maintainer add `lgtm+approve` lables, tide will merge the pr though github action failed.

![image](https://user-images.githubusercontent.com/28776356/111722902-ac7c4380-889d-11eb-9680-56122b491572.png)

Our tide image version is as above, could I know when the version supports github action?

**Comment by alvaroaleman** [comment]
I can not tell you offhand what version exactly started supporting it, but what you have is from October 2020 and thus too old. Please just update your tide to a current version
