### ISSUE TITLE
creating test jobs is painful and a drain on productivity

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#2072]
My goal was to create several new e2e jobs for the release-1.6 branch. I compiled the basic list from
https://github.com/kubernetes/test-infra/issues/2029, the [release infra scripts](https://github.com/kubernetes/release/blob/master/lib/releaselib.sh#L100-L117), and my general intuition about which jobs would be easiest to start running.

I've gathered here a rough overview of my process, along with questions and frustrations I encountered along the way.

Two notes:
* As an experiment, and because I've only vaguely been following the bootstrap migration work, I acted as though I had very limited or no knowledge of the test infrastructure. Many of my questions here are phrased in that mindset.
* I spent over an hour and a half creating 8 new e2e release jobs, which is at least an hour too long. I am a bit frustrated. :)

The process:
1. From [last week's PR](https://github.com/kubernetes/test-infra/pull/2033) I know that I need to add e2e jobs to [bootstrap-ci.yaml](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml).
To add the jobs, I find the corresponding `release-1.5` job, create a new 1.6 section, copy-paste, and then replace `1.5` with `1.6`.
  a. This feels very error-prone.
  b. Why do I have to specify `job-name`? It looks like it's exactly the same as the group except that `ci-` is prefixed. Can't the tooling figure this out?
  c. Why are there two timeouts (`jenkins-timeout` and `timeout`)?
  d. How do I know these timeout values are correct? (I did a manual spot check against the `master` branch jobs, and they appear to be the same, so I guess they're OK.)
  e. The `frequency` is the same for all of these jobs. Why isn't it a default, or at least something I can specify for the whole group at once?
  f. What is `json`? It seems like every job sets this to `1` - why is this here at all?
  g. I really wish I could specify one `trigger-job` for the whole group rather than repeating myself.

2. Next I need to add entries to [`config.json`](https://github.com/kubernetes/test-infra/blob/master/jobs/config.json).
  a. YAML and JSON? Why can't we be consistent?
  b. I don't really know what any of this is, so I'm just going to copy-paste existing jobs.
  c. This file seems even more redundant than the Jenkins config. At least I can write a short script to save me time and manually paste in:
  ```shell
JOBS=$(git diff master jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml | grep "^+ \+job-name:" | sed "s/^.*: \(.*\)$/\1/")
for job in $JOBS; do
  cat << EOF
"$job": {
  "scenario": "kubernetes_e2e",
  "args": [
    "--env-file=platforms/gce.env",
    "--env-file=jobs/$job.env"
  ]
},

EOF
done
```
  d. This really feels like something the tooling should automatically figure out.
  e. I want to add a comment to section off these jobs, but I can't, because JSON. Ugh.

3. OK, on to the .env files, one for each of 8 jobs.
  a. Now ENV? Yet another format I need to understand.
  b. The `jobs/` directory is terrifying and difficult to navigate (#2067). It doesn't help that GitHub truncates everything because the filenames are too long.
  c. I have no idea what I'm doing, so I just manually copy each of the `release-1.5` .env file to a `release-1.6` version, and then update `JENKINS_PUBLISHED_VERSION` and `PROJECT` for each.
  d. Why is `JENKINS_PUBLISHED_VERSION` duplicated across all of these? Seems like we should set this once, or it should figure it out from the `-release-1.6` in the name.
  e. There's yet **another** timeout value? What is `KUBEKINS_TIMEOUT` and why is it different from the others?
  f. I then compare the `release-1.6` env files against the version from `master`, trying to resolve mysterious inconsistencies:
  g. Do we need to run in [etcd v2 mode](https://github.com/kubernetes/test-infra/blob/a6537175efea26329a8222444c31ecffe4a73c66/jobs/ci-kubernetes-e2e-gce.env#L11-L14)?
  h. Where does [`ENABLE_GARBAGE_COLLECTOR=true`](https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gce-serial.env#L2) come from? The git blame doesn't help much; I have to track it back through #1737 to `jobs/ci-kubernetes-e2e-gce-serial.sh`, and then through #1059 to `jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml` to find that it was originally added in #391. (I really only knew about the last step because I've worked on test-infra.)
   i. Where does [`KUBE_GCE_ZONE=europe-west1-c`](https://github.com/kubernetes/test-infra/blob/a621353356bbe1301ac361105bc2b64ccb16f905/jobs/ci-kubernetes-e2e-gce-slow.env#L4) come from? Do we need it? It's a similar git blame story: through #1737 to `jobs/ci-kubernetes-e2e-gce-slow.sh`, then through #1059 to `jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml`, then through #117 to `jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e.yaml`, where finally I get to #82 which has an explanation of its origin. I add a comment to the original .env files.
   j. Do I need these `NUM_NODES` and `GINKGO_PARALLEL_NODES` values? No idea.

4. Next, updating testgrid's `config.yaml` (back to YAML!). From last week's work, I know that this bit is also very scriptable and is low-hanging fruit for automation:
  a. For new test groups:
```shell
jq -r 'keys | .[] | select(startswith("ci")) | select(endswith("release-1.6")) | select(contains("e2e")) | @text "- name: \(.)\n  gcs_prefix: kubernetes-jenkins/logs/\(.)"' jobs/config.json
```
  b. For new dashboard tabs: 
```shell
jq -r 'keys | .[] | select(startswith("ci")) | select(endswith("release-1.6")) | select(contains("e2e")) | @text "  - name: \(.)\n    test_group_name: \(.)"' jobs/config.json
```
  c. I manually paste these into the testgrid config, and shorten the `name` in the dashboard tabs to remove `ci-kubernetes` and `release-`.

5. Time to create projects! Also thankfully somewhat scriptable, using the internal script to create projects:
```shell
git diff master jobs/ | grep +PROJECT | cut -d= -f2 | xargs -i path/to/script --some --args --project={}
```
  Some iterations of this fail, because I used `-1.6` in the project name instead of `-1-6`. This whole process is error-prone.

6. Send off PR, merge, and hope it all works. It'll take hours before I know if these jobs are working properly.

7. Cry about the fact that I have to do this for dozens more jobs.

In my ideal world, this would all be a 1-line config change like [enabling code freeze](https://github.com/kubernetes/test-infra/commit/d5b0d1b07beebc0d8b501f0ec9a8c2b652fef59a).

I should be able to tell our tooling that I want to enable build, unit, and e2e tests on a release branch, and it should figure out the rest.

**Comment by ixdy** [comment]
Creating release jobs is probably uniquely painful compared to just creating one or two additional feature jobs, but it shouldn't be this bad.

**Comment by krzyzacy** [comment]
I'm up for moving everything into one single config file, and all systems can understand.

Maybe we can let prow and testgrid learn about config.json (which can turn into a yaml file, if we hates json)?

**Comment by ixdy** [comment]
One config file doesn't help significantly if you still need to copy/paste/edit repeatedly within that file.

**Comment by krzyzacy** [comment]
I'm going to make prow periodic job understand which branch to run, so that'll reduce some future bleeding. But I feel like adding a new feature suite is still need to go through the process.

**Comment by ixdy** [comment]
I think the core issue is that implementation details of the CI system should be minimally visible to users (i.e. folks trying to add/edit jobs, like me in this issue).

If I just want to setup a job to run  some e2e tests, I should be able to specify a branch and which tests I want to run, and the tooling should figure out the rest, without me being a human code generator.

**Comment by krzyzacy** [comment]
Yeah that makes sense.

**Comment by smarterclayton** [comment]
Awesome write up, helped me understand better how to read them

**Comment by fejta** [comment]
/assign @yguo0905

Please update and/or close

**Comment by yguo0905** [comment]
Implemented in https://github.com/kubernetes/test-infra/issues/2894.

**Comment by krzyzacy** [comment]
some point is still valid - with boskos and not require `*.env` it's less painful now - still need to finish migrate with stable-x aliases.

**Comment by spiffxp** [comment]
I agree this was an awesome write up and things have also seriously improved / changed since then.  Do we have or want a guide for the state of things now?

**Comment by BenTheElder** [comment]
See #4794 for no more YAML *and* JSON (not yet, but I'm tackling this one slowly).
I think most of this is still more or less just as frustrating. I know @krzyzacy really want to see this improved but since it works now this is somewhat lower priority. Shedding Jenkins + Mungegithub would help.

**Comment by spiffxp** [comment]
Right, IMO the set of people that need to make or add jobs is small enough that tribal knowledge transfer is probably fine, given the fixed bandwidth that we have.  I'll open an issue for the stable-X stuff if there isn't one by the time I get there

**Comment by krzyzacy** [comment]
yeah I haven't got the chance to do the rest of stable-X stuff yet :-( definitely shoot me an issue
