### ISSUE TITLE
Branchprotector error

### ISSUE THREAD

**Issue by peterfeifanchen** [kubernetes/test-infra#20727]
**What happened**:
We are using branch protector in knative test-infra.

**What you expected to happen**:
That it runs the same as the K8S branch protector. Except with our config file https://github.com/knative/test-infra/blob/master/config/branch_protector/rules.yaml

**How to reproduce it (as minimally and precisely as possible)**:
This isn't really reproduceable by you guys since you do not run branch protector with knative-prow-robot, but I am just looking for some pointers as to what might be the cause of this problem (e.g., what permission is needed to modify branch protection on a repo, how that works etc.), so we can check our prow-robot to see what it doesn't have or what the problematic repo isn't set to.

**Please provide links to example occurrences, if any**:
https://storage.googleapis.com/knative-prow/logs/ci-knative-test-infra-branchprotector/1357029771720003584/build-log.txt

**Anything else we need to know?**:
I think we have a misconfiguration of https://github.com/knative-prow-robot which we use to run these jobs with its github token. But it is hard to pinpoint from the error message what we need to do to fix this (it just says cannot update the branch protection on knative-sandbox/net-ingressv2.

**Comment by petr-muller** [comment]
@peterfeifanchen 

It's not a problem on the knative-sandbox/net-ingressv2 repo, it's on `knative/.github` one (there's an error happening in the middle of the log, and the last line is just a summary of all problems encountered).

```json
{
   "component":"branchprotector",
   "file":"prow/cmd/branchprotector/protect.go:97",
   "func":"main.(*Errors).add",
   "level":"info",
   "msg":"update knative: update .github: update master from protected=false: get policy: knative/.github=master defines a policy, which requires protect: true",
   "severity":"info",
   "time":"2021-02-03T18:40:54Z"
}
```

The error in general means that

**Comment by peterfeifanchen** [comment]
Thanks, yea we eventually figured out that was the issue. It's been fixed now. Thanks!
