### ISSUE TITLE
Prow components periodically refresh build clusters

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#20745]
**What would you like to be added**:

Prow components that interact with build clusters refresh build clusters periodically, like every 5 minutes.

**Why is this needed**:

Prow components only load build clusters once on start up, and keep going when certain build cluster is not loaded. This generally works fine in cases where build clusters are not reachable before of either wrong config or cluster decommissioned. But in cases where the build cluster was not available because of master node upgrade, the build cluster will not work. This problem can be fixed by asking prow components to sync every so often.

**Comment by chaodaiG** [comment]
CC @alvaroaleman @cjwagner @fejta

**Comment by alvaroaleman** [comment]
We already watch the kubeconfigs and will restart on changes: https://github.com/kubernetes/test-infra/pull/20408

Could that cover your usecase? The main issue is that there is no existing upstream machinery to reload anything other than a tokenfile during runtime.

**Comment by chaodaiG** [comment]
I'm afraid that #20408 is not sufficient for our use case. IIUC #20408 reloads kubeconfigs when there is any value change in the kubeconfig, aka someone updated secret/kubeconfig. The problem we encountered was that after restart(normally after prow bump), when the deployment(s) try to load build clusters, one of them was not reachable(i.e. the api server of the build cluster was undergoing an upgrade, which made it temporarily not reachable), thus that specific build cluster was considered bad, and prow will not be able to do anything to it, including scheduling pods, GC, etc. This prow instance is not bumped as frequent as k8s prow, so this problem could last a few days unless someone noticed and report.

It's sad that there is no existing upstream machinery, would still be nice if we could figure out something else to trigger this kind of reloading.

**Comment by alvaroaleman** [comment]
We have a metric for errors there though somewhere, and we have an alert in openshift for when it's non-zero

**Comment by chaodaiG** [comment]
This looks good enough for now, can you upstream this alert?

**Comment by chaodaiG** [comment]
/remove-lifecycle stale

It's not feasible to accomplish this. We'll need to set up alert with GCP monitoring stack, @cjwagner for awareness.

**Comment by chaodaiG** [comment]
/close
this was actually fixed by https://github.com/kubernetes/test-infra/pull/25834
