### ISSUE TITLE
Configurator only respects the root default.yaml, not local default.yaml

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#20756]
**What happened**:
Configurator, currently being used to manage the TestGrid configuration at testgrid.k8s.io via [this script](https://github.com/kubernetes/test-infra/blob/master/testgrid/config-upload.sh), is uploading configurations with defaults populated by the root default file only.

**What you expected to happen**:
Configurator should upload a TestGrid configuration with default settings based on local default.yaml files.

**How to reproduce it (as minimally and precisely as possible)**:
Run `./testgrid/config_upload.sh` with the current checked-in configuration

**Please provide links to example occurrences, if any**:
Kubevirt default settings: https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubevirt/default.yaml
Kubevirt loaded configuration: https://testgrid.k8s.io/q/config/kubevirt-periodics/periodic-kubevirt-e2e-k8s-prev

**Anything else we need to know?**:
Necessary improvements to yamlcfg libraries in TestGrid:
https://github.com/GoogleCloudPlatform/testgrid/issues/7

/cc @michelle192837 @mpherman2 @fgimenez

**Comment by chases2** [comment]
The flow here is convoluted, since Configurator is being used both to move settings from Kubevirt's Prow instance to the k8s/test-infra repository (via Transfigure) and to upload from that repository to cloud.

I see two ways forward:
1) Change Configurator to have a "seek default" flag instead of a specific default, and ensure that Transfigure does not apply defaults while ./config-upload.sh does.
2) Replace our use of Transfigure with a [config-merger](https://github.com/GoogleCloudPlatform/testgrid/pull/349), leaving Kubevirt to run Configurator on their own Prow instance with their own default settings.

**Comment by spiffxp** [comment]
>Change Configurator to have an "apply default" flag instead of a specific default, and ensure that Transfigure does not apply defaults while ./config-upload.sh does.

Instead of a new flag, if we dropped the assumption in this if, not specifying `--default path/to/default.yaml` would mean "don't apply defaults"
https://github.com/kubernetes/test-infra/blob/9188da5e58d4d947b23cef3b863e340092e24d5c/testgrid/cmd/configurator/main.go#L103-L106

**Comment by fgimenez** [comment]
/assign 
/remove-help

I'd like to give it a try, will follow @spiffxp suggestion and ping you when ready :)

**Comment by spiffxp** [comment]
@fgimenez I'm happy to make suggestions, but you should definitely get approval from @chases2 or @chaodaiG on this PR.  If we consider flags as api, this would be a breaking change, and they will better understand the implications.
