### ISSUE TITLE
[BUG] Deck is NOT working properly after the new changes.

### ISSUE THREAD

**Issue by droslean** [kubernetes/test-infra#20751]
We recently bump prow to run with changes including in https://github.com/kubernetes/test-infra/compare/567fc1ab64...b06ec788ea and it caused `deck` to stop being functional.

```sh
$ curl https://prow.ci.openshift.org/static/prow_bundle.min.js
404 page not found
```

/cc @kubernetes/test-infra-admins @kubernetes/test-infra-maintainers

**Comment by alvaroaleman** [comment]
Bisect shows its 81c5adb48839d6af0e96b07ba2956f7b727f8c94

**Comment by chaodaiG** [comment]
@fejta , the bazel 3.4.1 PR and seemed affecting deck

**Comment by chaodaiG** [comment]
Bumped k8s prow https://github.com/kubernetes/test-infra/pull/20741 after reverting of #20651, everything looks fine to me

**Comment by droslean** [comment]
It seems that https://github.com/kubernetes/test-infra/commit/4d6791131bd487a3b9c0375dfff7c5c46328d06c broke it again.

**Comment by droslean** [comment]
Error from browsers console:
```sh
Uncaught SyntaxError: import declarations may only appear at top level of a module
```

**Comment by alvaroaleman** [comment]
@fejta next time you introduce this, can you please start a deck instance built with the new bazel version (locally via docker or behind a canary ingress in your production) and click through it to make sure that we do not break it a third time?

**Comment by cjwagner** [comment]
Trying again: https://github.com/kubernetes/test-infra/pull/20824

**Comment by alvaroaleman** [comment]
everything appears to be working now, thanks!
/close
