### ISSUE TITLE
Migrate jobs away from deprecated bootstrap usage

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#20760]
This is an umbrella issue to track migrating job configs away from bootstrap and instead use [pod-utils](https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md).

Bootstrap has been deprecated for a few years at this point, and jobs that use bootstrap.py have been unsupported by test-infra-oncall for at least 1.5 years (ref: https://github.com/kubernetes/test-infra/pull/14392).  Pod-utils are the documented and supported way of writing prowjobs: https://github.com/kubernetes/test-infra/tree/master/config/jobs#job-cookbook

One way to be helpful: PR in a guide on how to do this!  Relevant content to source from:
- @dims put together a guide https://gist.github.com/dims/c1296f8ed42238baea0a5fcae45f4cf4
- @rikatz went through this for pull-kubernetes-node-e2e
  - https://github.com/kubernetes/test-infra/pull/19942
  - https://github.com/kubernetes/test-infra/pull/19947
  - https://github.com/kubernetes/test-infra/pull/19948
  - https://github.com/kubernetes/test-infra/pull/19949
  - https://github.com/kubernetes/test-infra/pull/19951

Another way to help: produce a tool, script or dashboard that keeps track of what has and has not been migrated.  We could either link to its results from this issue, or periodically update this issue with the results.

The most concrete way to help: migrate the jobs you or your SIG owns

/lifecycle frozen
/priority important-longterm
/sig testing
Once we have tracking of which sigs own jobs that use bootstrap, we can tag with appropriate sigs.
/area jobs
/area bootstrap
/area prow/pod-utils
/help

**Comment by spiffxp** [comment]
As an FYI, jobs that migrate away from bootstrap will lack an Infra-Commit column in testgrid: https://github.com/kubernetes/test-infra/issues/20650.  This is not a blocker to migration, and is probably a good thing (one less thing to bisect).

I strongly suspect kubernetes/test-infra code being checked out in a job's container isn't actually necessary for the vast majority of jobs that make the switch away from bootstrap.

**Comment by spiffxp** [comment]
Things to help track our status:
- https://github.com/kubernetes/test-infra/pull/20825 added tests to log jobs that are deprecated
- https://github.com/kubernetes/test-infra/pull/22838 added summary lines to a number of tests

**Comment by dims** [comment]
xref: https://github.com/kubernetes/test-infra/issues/30846

**Comment by dims** [comment]
@spiffxp will be proud of us :) https://github.com/kubernetes/test-infra/issues/30846

/close
