### ISSUE TITLE
mungebot/approval: cc only applicable approvers

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#2076]
In https://github.com/kubernetes/kubernetes/pull/39678#issuecomment-282847125, the bot cc'd me as a suggested approver, but the only relevant directory I could approve (`hack/`) was already approved. `pkg/` still needed approval, but I'm not an approver there.

**Comment by ixdy** [comment]
cc @apelisse @grodrigues3

**Comment by apelisse** [comment]
I think this will be fixed by #1846

**Comment by apelisse** [comment]
will it @grodrigues3 ?

**Comment by ixdy** [comment]
related: if a PR is already approved, don't CC any additional suggested approvers.
