### ISSUE TITLE
E2E test images: httpd images failed to push to staging

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/test-infra#20884]
**What happened**:

The Image Builder postsubmit jobs ``post-kubernetes-push-e2e-httpd-test-images`` and ``post-kubernetes-push-e2e-new-httpd-test-images`` are failing with a 401 Unauthorized error while trying to push to ``gcr.io/k8s-staging-e2e-test-images``.

**What you expected to happen**:

It should have been able to push the images.

**How to reproduce it (as minimally and precisely as possible)**:

Rerun the jobs.

**Please provide links to example occurrences, if any**:

[1] https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-httpd-test-images
[2] https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-httpd-new-test-images
[3] https://testgrid.k8s.io/sig-testing-images#kubernetes-e2e-windows-servercore-cache

**Anything else we need to know?**:

Worth noting that the job passed on 2021.02.09, but failed on 2021.02.15. The prow job config is fine, running the ``k8s-staging-e2e-test-images.sh`` script that generated the job reveals no diff.

Additionally, on 2021.02.11 the ``kubernetes-e2e-windows-servercore-cache`` job passed [3], a job which is similarly defined to the other 2 jobs.

**Comment by spiffxp** [comment]
In case the problem is with the k8s-staging-e2e-test-images project, I looked at other jobs that push to that
- http push worked 2020-02-09: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-httpd-test-images/1359074409377173504
- agnhost push worked 2020-02-12 (last friday): https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-agnhost-test-images/1360291867010273280
- http push failed 2020-02-15 https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-httpd-test-images/1361473175191293952

No job other than http have run since agnhost last passed, so it's tough to isolate to "the http jobs" vs. "all jobs pushing to this project"

**Comment by spiffxp** [comment]
Nothing merged to https://github.com/kubernetes/test-infra/commits/master/config/jobs/image-pushing in between last pass / first fail

**Comment by spiffxp** [comment]
Things merged to https://github.com/kubernetes/k8s.io that could have changed something:
- 2020-02-12 -  https://github.com/kubernetes/k8s.io/pull/1639 - removed windows-img-promoter-cert secrets (manually: https://github.com/kubernetes/k8s.io/issues/1638#issuecomment-777609605) (I thought these were unused though?)
- 2020-02-12 - https://github.com/kubernetes/k8s.io/pull/1643 - vulndash related stuff was removed (should be completely unrelated to image builds)
- 2020-02-11  - https://github.com/kubernetes/k8s.io/pull/1631 - prow build clusters moved to release channels (seems unlikely, cluster version remains unchanged at v1.16 (ref: https://github.com/kubernetes/k8s.io/issues/1541#issuecomment-781399870))

**Comment by spiffxp** [comment]
I saw cluster-api-aws recently push an image, so using them as a known-good

```bash
bad="e2e-test-images"
good="cluster-api-aws"

for s in "${bad}" "${good}"; do 
  p="k8s-staging-${s}"
  output="iam-${s}.txt"
  (
    for b in $(gsutil ls -p "${p}"); do
      gsutil iam get "${b}" | jq 'del(.etag)'
    done
    gcloud --format=json projects get-iam-policy "${p}" | jq 'del(.etag)'
  ) > "${output}"
  num=$(gcloud projects describe k8s-infra-prow-build "--format=value(projectNumber)")
  sed -i.bak -e "s/${s}/subproject/g;s/${num}/123456789/g" "${output}"
  rm -f "${output}.bak"
done

diff -y -W 100 iam-{${bad},${good}}.txt
```

no diff in gcs iam; the e2e project appears to have additional role bindings, but how would that restrict access?
```
{						    {
      "members": [				      "members": [
        "serviceAccount:service-456067983721@ |	        "serviceAccount:service-433651898792@
      ],				      <
      "role": "roles/containerregistry.Servic <
    },					      <
    {					      <
      "members": [			      <
        "serviceAccount:service-456067983721@ <
      ],					      ],
      "role": "roles/containerscanning.Servic	      "role": "roles/containerscanning.Servic
    },						    },
    {						    {
      "members": [				      "members": [
        "serviceAccount:456067983721-compute@ |	        "serviceAccount:433651898792-compute@
        "serviceAccount:456067983721@cloudser |	        "serviceAccount:433651898792@cloudser
        "serviceAccount:service-456067983721@ |	        "serviceAccount:service-433651898792@
      ],					      ],
      "role": "roles/editor"			      "role": "roles/editor"
    },						    },
    {						    {
      "members": [				      "members": [
        "user:davanum@gmail.com"		        "user:davanum@gmail.com"
      ],					      ],
      "role": "roles/owner"			      "role": "roles/owner"
    },						    },
    {						    {
      "members": [				      "members": [
        "serviceAccount:456067983721@cloudbui <
      ],				      <
      "role": "roles/secretmanager.secretAcce <
    },					      <
    {					      <
      "members": [			      <
        "group:k8s-infra-staging-subproject@k	        "group:k8s-infra-staging-subproject@k
      ],					      ],
      "role": "roles/serviceusage.serviceUsag	      "role": "roles/serviceusage.serviceUsag
    },						    },
```

**Comment by spiffxp** [comment]
retrying the gcb build of this image that worked last week https://console.cloud.google.com/cloud-build/builds;region=global/818e9010-29ad-4fa2-ab81-7547c6f1c0c8?project=k8s-staging-e2e-test-images

**Comment by spiffxp** [comment]
that worked, which leads me to believe a change introduced by https://github.com/kubernetes/kubernetes/pull/99030 is the culprit

**Comment by claudiubelu** [comment]
> 
> 
> that worked, which leads me to believe a change introduced by [kubernetes/kubernetes#99030](https://github.com/kubernetes/kubernetes/pull/99030) is the culprit

I wonder how. The changes in that PR affects Windows, since those changes are made into the ``Dockerfile_windows`` files. The only change outside of those files are the ``VERSION`` files, which changed ``2.4.38-alpine`` to ``2.4.38-1``. Note that the failure ocucrs *before* getting to the Windows images, it fails on the ``linux/amd64`` image, which is the first one in the list.

**Comment by spiffxp** [comment]
I can't find a reference for this but I'm wondering if the docker registry api doesn't like that tag format?

**Comment by spiffxp** [comment]
https://docs.docker.com/engine/reference/commandline/tag/#extended-description
>A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

which makes it sound like the new tag would be valid

**Comment by claudiubelu** [comment]
I was able to build and push ``claudiubelu/httpd:2.4.38-1``, which includes ``claudiubelu/httpd:2.4.38-1-linux-amd64``: https://paste.ubuntu.com/p/G5ydg43RZm/ (the logs from the first images were cut)

**Comment by spiffxp** [comment]
Going to try messing with the source file contents and submitting builds manually
```bash
# get the source
mkdir -p gcb && cd gcb
gsutil cp gs://k8s-staging-e2e-test-images-gcb/source/1612863662.49-29f09d2c41c5417f952f03585182c7aa.tgz .
tar xvzf 1612863662.49-29f09d2c41c5417f952f03585182c7aa.tgz && rm 1612863662.49-29f09d2c41c5417f952f03585182c7aa.tgz
# make a change
vi test/images/httpd/VERSION
# try running a build with the change
tar -czf ../spiffxp-http-gcb.tgz *
gsutil cp ../spiffxp-http-gcb.tgz gs://k8s-staging-e2e-test-images-gcb/source/
gcloud builds submit \
  --verbosity debug \
  --config /Users/spiffxp/w/kubernetes/kubernetes/test/images/cloudbuild.yaml \
  --substitutions _PULL_BASE_REF=master,_WHAT=httpd,_GIT_TAG=v20210218-v1.21.0-alpha.3-197-g9e5fcc49ec5 \
  --project k8s-staging-e2e-test-images \
  --gcs-log-dir gs://k8s-staging-e2e-test-images-gcb/logs \
  --gcs-source-staging-dir gs://k8s-staging-e2e-test-images-gcb/source \
  gs://k8s-staging-e2e-test-images-gcb/source/spiffxp-http-gcb.tgz
```

**Comment by spiffxp** [comment]
Same result (same SHA as before)
```
#5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/httpd:2.4.38-monkeys-linux-amd64
#5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/httpd:2.4.38-monkeys-linux-amd64 0.3s done
#5 ERROR: failed commit on ref "manifest-sha256:ec099bd94d243bcfba864acbeaf87ab38e6b4a67c25d8508103e0ad96446d84c": unexpected status: 401 Unauthorized
```

**Comment by spiffxp** [comment]
trying a different image
```
vi test/images/nginx/VERSION #
# submit with _WHAT=nginx
```
yields a similar error
```
#5 pushing layers 0.0s done
#5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/nginx:1.14-monkeys-linux-amd64
#5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/nginx:1.14-monkeys-linux-amd64 0.3s done
#5 ERROR: failed commit on ref "manifest-sha256:a2d0ea7d3550b0853d04263025e6cfcc353f3e102fe725d19b9fc51282603f02": unexpected status: 401 Unauthorized
```

**Comment by spiffxp** [comment]
Using source file from "good" build (gs://k8s-staging-e2e-test-images-gcb/source/1612863662.49-29f09d2c41c5417f952f03585182c7aa.tgz)

Manually submitting with no changes works

Changing to push nginx with new version
```
vi test/images/nginx/VERSION
# submit with _WHAT=nginx
```
yields a similar error
```
#5 exporting to image
#5 exporting layers done
#5 exporting manifest sha256:a2d0ea7d3550b0853d04263025e6cfcc353f3e102fe725d19b9fc51282603f02 0.0s done
#5 exporting config sha256:f4ac389d78cd8be151962a9fc7227b3b23862d9040eeb0686158a3229da60022 0.0s done
#5 pushing layers 0.1s done
#5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/nginx:1.14-monkeys-linux-amd64
#5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/nginx:1.14-monkeys-linux-amd64 0.3s done
#5 ERROR: failed commit on ref "manifest-sha256:a2d0ea7d3550b0853d04263025e6cfcc353f3e102fe725d19b9fc51282603f02": unexpected status: 401 Unauthorized
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = failed commit on ref "manifest-sha256:a2d0ea7d3550b0853d04263025e6cfcc353f3e102fe725d19b9fc51282603f02": unexpected status: 401 Unauthorized
make: *** [Makefile:43: all-build-and-push] Error 1
```

so... new tag, unchanged manifest = error... is this working as intended, or should we be allowing this?

**Comment by spiffxp** [comment]
https://cloud.google.com/container-registry/docs/access-control#permissions_and_roles 

my guess now is that `update` or `delete` permissions may be missing, if someone wants to take a look through https://github.com/kubernetes/k8s.io/blob/main/infra/gcp/ensure-staging-storage.sh and files it sources, a PR would be appreciated

**Comment by spiffxp** [comment]
Per https://cloud.google.com/container-registry/docs/gcr-service-account, the GCR service account for staging projects today may be overprivileged:
- `service-{project_id}@containerregistry.iam.gserviceaccount.com` should have role `roles/containerregistry.ServiceAgent`
- `service-{project_id}@containerregistry.iam.gserviceaccount.com` should NOT have role `roles/editor`

Per https://cloud.google.com/container-registry/docs/access-control#permissions_and_roles, the following are required for "Push (write) and pull (read) images for existing registry hosts in a project"
- storage.objects.create
- storage.objects.delete
- storage.objects.get
- storage.objects.list
- storage.objects.update

The bucket permissions are for "Add a registry to a project by pushing the first image to the registry host", which I think the k8s-infra staging project script does.

I used https://cloud.google.com/iam/docs/troubleshooting-access to gather permissions for different accounts against the gcs bucket backing gcr.io/k8s-staging-e2e-test-images (ref: https://gist.github.com/spiffxp/0110b663a229ebda1e805d92b23e646b)

| permission | email | access |
| --- | --- | --- |
| storage.buckets.delete         | 456067983721@cloudbuild.gserviceaccount.com                       | UNKNOWN_INFO_DENIED  |
| storage.buckets.get            | 456067983721@cloudbuild.gserviceaccount.com                       | GRANTED              |
| storage.buckets.update         | 456067983721@cloudbuild.gserviceaccount.com                       | UNKNOWN_INFO_DENIED  |
| storage.objects.create         | 456067983721@cloudbuild.gserviceaccount.com                       | GRANTED              |
| storage.objects.delete         | 456067983721@cloudbuild.gserviceaccount.com                       | GRANTED              |
| storage.objects.get            | 456067983721@cloudbuild.gserviceaccount.com                       | GRANTED              |
| storage.objects.list           | 456067983721@cloudbuild.gserviceaccount.com                       | GRANTED              |
| storage.objects.update         | 456067983721@cloudbuild.gserviceaccount.com                       | GRANTED              |
| storage.buckets.delete         | service-456067983721@gcp-sa-cloudbuild.iam.gserviceaccount.com    | UNKNOWN_INFO_DENIED  |
| storage.buckets.get            | service-456067983721@gcp-sa-cloudbuild.iam.gserviceaccount.com    | GRANTED              |
| storage.buckets.update         | service-456067983721@gcp-sa-cloudbuild.iam.gserviceaccount.com    | UNKNOWN_INFO_DENIED  |
| storage.objects.create         | service-456067983721@gcp-sa-cloudbuild.iam.gserviceaccount.com    | GRANTED              |
| storage.objects.delete         | service-456067983721@gcp-sa-cloudbuild.iam.gserviceaccount.com    | GRANTED              |
| storage.objects.get            | service-456067983721@gcp-sa-cloudbuild.iam.gserviceaccount.com    | GRANTED              |
| storage.objects.list           | service-456067983721@gcp-sa-cloudbuild.iam.gserviceaccount.com    | GRANTED              |
| storage.objects.update         | service-456067983721@gcp-sa-cloudbuild.iam.gserviceaccount.com    | GRANTED              |
| storage.buckets.delete         | service-456067983721@containerregistry.iam.gserviceaccount.com    | GRANTED              |
| storage.buckets.get            | service-456067983721@containerregistry.iam.gserviceaccount.com    | GRANTED              |
| storage.buckets.update         | service-456067983721@containerregistry.iam.gserviceaccount.com    | GRANTED              |
| storage.objects.create         | service-456067983721@containerregistry.iam.gserviceaccount.com    | GRANTED              |
| storage.objects.delete         | service-456067983721@containerregistry.iam.gserviceaccount.com    | GRANTED              |
| storage.objects.get            | service-456067983721@containerregistry.iam.gserviceaccount.com    | GRANTED              |
| storage.objects.list           | service-456067983721@containerregistry.iam.gserviceaccount.com    | GRANTED              |
| storage.objects.update         | service-456067983721@containerregistry.iam.gserviceaccount.com    | UNKNOWN_INFO_DENIED  |

I'm going to try adding `storage.objects.update` for the GCR service account

**Comment by spiffxp** [comment]
Give GCR's SA `roles/storage.objectAdmin` directly on the gcr.io bucket
```
$ gsutil iam ch serviceAccount:service-456067983721@containerregistry.iam.gserviceaccount.com:objectAdmin gs://artifacts.k8s-staging-e2e-test-images.appspot.com
```

**Comment by spiffxp** [comment]
Giving GCB's SA `roles/storage.legacyBucketOwner` directly on the gcr.io bucket to give it `storage.buckets.update`
```
gsutil iam ch serviceAccount:456067983721@cloudbuild.gserviceaccount.com:legacyBucketOwner gs://artifacts.k8s-staging-e2e-test-images.appspot.com
```
The only other storage role with `storage.buckets.update` is `roles/storage.admin`, which also has `storage.buckets.delete` (which I'm trying to avoid)

**Comment by spiffxp** [comment]
I'm now beginning to wonder if something about `docker buildx --output=type=registry` is not using the appropriate auth?

**Comment by spiffxp** [comment]
Looks like this bug [pusher does not authenticate properly for gcr"](https://github.com/containerd/containerd/issues/4622), present in containerd 1.4.3 (which is what `docker version` is dumping for this job)

- Fix landed for containerd master 2020-12-16 (https://github.com/containerd/containerd/pull/4854)
- Was cherry-picked back to release/1.4 2020-01-14 (https://github.com/containerd/containerd/pull/4942)
- PR to pull into buildkit still in draft (https://github.com/moby/buildkit/pull/1921)

**Comment by spiffxp** [comment]
/assign @claudiubelu 
I need to move on to other stuff for a few days.  Do you think it'd be possible to workaround by having `buildx` not push, and using something else instead (maybe regular `docker`?)

**Comment by BenTheElder** [comment]
multi-arch images built as multi-arch by buildkit can only be exported with pushing last I checked :|
https://github.com/docker/buildx/issues/59

I think _maybe_ you can build the image without setting `--load` or `--push` (which will warn but build them to the cache) and then one by one `--load` them and construct a manifest list or something but ... that's kludge.

you could push to a local registry and then pull and repush them.

for k/k's core image builds we are moving to buildx but we are NOT using it for the multi-arch manifests yet, just the same build patterns as before (and using `--load`)

**Comment by chewong** [comment]
AFAIK the only `--output` option when building Windows images on a Linux machine with buildx is `type=registry`. We won't able to load them unless we have a remote Windows docker host.

**Comment by BenTheElder** [comment]
> AFAIK the only --output option when building Windows images on a Linux machine with buildx is type=registry. 

That's not incompatibile with a local registry.

> We won't able to load/pull them unless we have a remote Windows docker host.

I don't think that's the case. You can pull docker images that are not for the host platform.

**Comment by chewong** [comment]
That's not the case for Windows images :/ 
```
docker pull mcr.microsoft.com/windows/nanoserver                                                                                                                                1 ↵ chuwon@CHINMAY-LAPTOP
Using default tag: latest
latest: Pulling from windows/nanoserver
bce2fbc256ea: Downloading
6f2071dcd729: Downloading
image operating system "windows" cannot be used on this platform
```

**Comment by claudiubelu** [comment]
> 
> 
> I'm now beginning to wonder if something about `docker buildx --output=type=registry` is not using the appropriate auth?

Then, why now? We have built and pushed all the current images like this and it worked.


> 
> 
> multi-arch images built as multi-arch by buildkit can only be exported with pushing last I checked :|
> [docker/buildx#59](https://github.com/docker/buildx/issues/59)
> 

That's what I knew too. It might be possible to push Linux images built with ``docker buildx`` (not sure, will have to check), but if I remember correctly, I couldn't refer to the Windows images built with ``docker buildx``. Will have to recheck this to refresh my memory.

> I think _maybe_ you can build the image without setting `--load` or `--push` (which will warn but build them to the cache) and then one by one `--load` them and construct a manifest list or something but ... that's kludge.
> 

Currently, we are setting the flag ``--output=type=registry``, which is equivalent to the ``--push`` flag, according to ``docker buildx`` help. You can build Windows images with ``--load`` or ``--output=type=docker``, but as I've mentioned, I couldn't refer to the Windows images afterwards. To be fair, I didn't investigate this too much since ``output=type=registry`` was already solving this anyways.

**Comment by claudiubelu** [comment]
I have been looking into it for a bit. So, the ``--output=type=registry`` is the only viable solution for us, considering we also want the Windows images there. It is a known fact that you simply cannot have Windows images in a "normal docker" on a Linux:

```
Currently, multi-platform images cannot be exported with the docker export type. The most common usecase for multi-platform images is to directly push to a registry (see registry).
```

From my experiments is that ``docker buildx build --output=type=docker`` the other Linux images can actually be referenced locally through ``docker images`` and so on, but not the Windows images. Trying to build the Windows images with docker buildx and the output type=docker, we can see that it actually tries to import into Docker images:

```
...

#7 [stage-2 2/2] COPY --from=nginx-source /nginx /usr/share/nginx
#7 sha256:976b1d0a846ad8f0a65631c26f8a46b2cf6e0ab117a8375e4ed5ee28a25d5e98
#7 DONE 0.1s

#8 exporting to oci image format
#8 sha256:69a2560eef4d3ece902c3b5149d142e9bd132f25db0bc9e35b94201534c415d2
#8 exporting layers
#8 exporting layers 0.5s done
#8 exporting manifest sha256:a175d01afdf166f7e46d7bc9d476ec43a4168426ff44fc2f3d4b8b6868f78756 0.0s done
#8 exporting config sha256:c106fccad57d1974e08505450c0203aac62d6d081de621f2f5b84534d0db8da6 done
#8 sending tarball
#8 sending tarball 4.7s done
#8 DONE 5.2s

#9 importing to docker
#9 sha256:8026238f638c17bcfbf7d41b163286c4f4f6ef72fb77b67cec9833d16ae7a9fb
#9 DONE 0.0s
/workspace/kubernetes/test/images
```

There's no error printed, but it doesn't end up in docker images. I've also tried to build the Windows images with output type=oci, which generated a .tar file. You can actually import it locally with ``docker import image.tar``, but inspecting the imported image [1], you can see that it sets the os/arch type to ``linux/amd64``, which is not quite right. Other than that, it can be seen that the User, env variables (including the ``PATH``) are stripped away, which is problematic. Trying to import the image with ``--platform "windows/amd64"`` we can see:

```
docker import --platform "windows/amd64" claudiubelu-nginx-1.14-1-windows-amd64-20H2.tar claudiubelu/nginx:1.14-1-windows-amd64-20h2
Error response from daemon: operating system is not supported
```

Which confirms that ``docker buildx build --output=type=docker`` probably encountered the same issue. Furthermore, having Windows images on a Linux node has been a pretty frequent question. I this this covers the reason nicely [2].

So, I still think ``--output=type=registry`` is the way to go. ``--output=type=oci`` or tar could work, but then we'd have to push them to the registry ourselves, which is supposed to be docker's / buildx's purpose in the first place.

[1] https://paste.ubuntu.com/p/m2tmX3yGMW/
[2] https://forums.docker.com/t/docker-daemon-on-ubuntu-pull-windows-containers-or-create-my-own/28823/6


> 
> 
> [docker/buildx#327](https://github.com/docker/buildx/issues/327) looks like what we're experiencing
> 
>     * Cause is present in 1.4.3 (which is what `docker version` is dumping for this job) ([containerd/containerd#4622](https://github.com/containerd/containerd/issues/4622))
> 
>     * Fix landed for containerd master 2020-12-16 ([containerd/containerd#4854](https://github.com/containerd/containerd/pull/4854))
> 
>     * Was cherry-picked back to release/1.4 2020-01-14 ([containerd/containerd#4942](https://github.com/containerd/containerd/pull/4942))
> 
>     * PR to pull into buildkit still in draft ([moby/buildkit#1921](https://github.com/moby/buildkit/pull/1921))
> 
> 
> This seems to have affected other registries such as quay.io, ghcr.io, etc. It looks like google artifact registry may be working? But migrating to that may be non-trivial (ref: [kubernetes/k8s.io#1343](https://github.com/kubernetes/k8s.io/issues/1343))

Oh. That might be it. It might be because the **exact** same hash is being pushed.

I have been looking into it for a bit. So, the ``--output=type=registry`` is the only viable solution for us, considering we also want the Windows images there. It is a known fact that you simply cannot have Windows images in a "normal docker" on a Linux 

> 
> 
> [docker/buildx#327](https://github.com/docker/buildx/issues/327) looks like what we're experiencing
> 
>     * Cause is present in 1.4.3 (which is what `docker version` is dumping for this job) ([containerd/containerd#4622](https://github.com/containerd/containerd/issues/4622))
> 
>     * Fix landed for containerd master 2020-12-16 ([containerd/containerd#4854](https://github.com/containerd/containerd/pull/4854))
> 
>     * Was cherry-picked back to release/1.4 2020-01-14 ([containerd/containerd#4942](https://github.com/containerd/containerd/pull/4942))
> 
>     * PR to pull into buildkit still in draft ([moby/buildkit#1921](https://github.com/moby/buildkit/pull/1921))
> 
> 
> This seems to have affected other registries such as quay.io, ghcr.io, etc. It looks like google artifact registry may be working? But migrating to that may be non-trivial (ref: [kubernetes/k8s.io#1343](https://github.com/kubernetes/k8s.io/issues/1343))

Oh. That might be it.

> 
> 
> Using source file from "good" build (`gs://k8s-staging-e2e-test-images-gcb/source/1612863662.49-29f09d2c41c5417f952f03585182c7aa.tgz`)
> 
> Manually submitting with no changes works
> 
> Changing to push nginx with new version
> 
> ```
> vi test/images/nginx/VERSION
> # submit with _WHAT=nginx
> ```
> 
> yields a similar error
> 
> ```
> #5 exporting to image
> #5 exporting layers done
> #5 exporting manifest sha256:a2d0ea7d3550b0853d04263025e6cfcc353f3e102fe725d19b9fc51282603f02 0.0s done
> #5 exporting config sha256:f4ac389d78cd8be151962a9fc7227b3b23862d9040eeb0686158a3229da60022 0.0s done
> #5 pushing layers 0.1s done
> #5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/nginx:1.14-monkeys-linux-amd64
> #5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/nginx:1.14-monkeys-linux-amd64 0.3s done
> #5 ERROR: failed commit on ref "manifest-sha256:a2d0ea7d3550b0853d04263025e6cfcc353f3e102fe725d19b9fc51282603f02": unexpected status: 401 Unauthorized
> ------
>  > exporting to image:
> ------
> failed to solve: rpc error: code = Unknown desc = failed commit on ref "manifest-sha256:a2d0ea7d3550b0853d04263025e6cfcc353f3e102fe725d19b9fc51282603f02": unexpected status: 401 Unauthorized
> make: *** [Makefile:43: all-build-and-push] Error 1
> ```
> 
> so... new tag, unchanged manifest = error... is this working as intended, or should we be allowing this?

Right, ``gcr.io/k8s-staging-e2e-test-images/nginx:1.14-monkeys-linux-amd64`` and ``gcr.io/k8s-staging-e2e-test-images/nginx:1.14-alpine-linux-amd64`` has the same sha, which is identical to ``nginx:1.14-alpine`` since the image was mirrored. I had the same sha on my own registry as well. So, it should work if we generate a new sha then. We could make a trivial change in the Dockerfile:

```
diff --git a/test/images/nginx/Dockerfile b/test/images/nginx/Dockerfile
index 3983b7c4f24..9a0c8ffb425 100644
--- a/test/images/nginx/Dockerfile
+++ b/test/images/nginx/Dockerfile
@@ -15,3 +15,5 @@
 # NOTE(claudiub): Noop. We're just mirroring the image to staging.
 ARG BASEIMAGE
 FROM $BASEIMAGE
+
+LABEL image_version="1.14-1"
```

Building this, I then get the sha:

```
docker pull claudiubelu/nginx:1.14-1-linux-amd64
1.14-1-linux-amd64: Pulling from claudiubelu/nginx
bdf0201b3a05: Already exists
3d0a573c81ed: Already exists
8129faeb2eb6: Already exists
3dc99f571daf: Already exists
Digest: sha256:ebf4de42b3d660133f6f7d0feddabe31a44d07ed55f59471fd2072b0d8e8afae
```

Which is now different from the previous ``a2d0ea7d3550b0853d04263025e6cfcc353f3e102fe725d19b9fc51282603f02``. Being a different sha, it should be pushable. If we look at the prow job history, we'd see that the httpd and nginx inage jobs worked exactly once: when the images dockerhub images were mirrored for the first time. This doesn't affect pushing images to dockerhub, I would have encountered this issue too before.

IMO, we could go ahead with this fix, making a note in the ``README.md`` too, and push on the fix to merge on docker.

**Comment by spiffxp** [comment]
Thank you for looking into this in-depth @claudiubelu 

>Being a different sha, it should be pushable. If we look at the prow job history, we'd see that the httpd and nginx inage jobs worked exactly once: when the images dockerhub images were mirrored for the first time 
>[...] IMO, we could go ahead with this fix, making a note in the README.md too, and push on the fix to merge on docker.

Yeah, doing something to artificially change the SHA sounds like the right call here.  It's not "right" but it's very simple/contained.  Maybe revisit if we're having to do this too often.

https://github.com/kubernetes/test-infra/issues/20884#issuecomment-785322762 would probably be the next step up, stand up a local registry for docker buildx to push to (https://docs.docker.com/registry/deploying/), then push from that to the final destination without buildx.

**Comment by spiffxp** [comment]
/reopen
I'd like for us to close this once we've confirmed images got pushed

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/commit/be2a2988a0c6b5f0b66e4ebdc335fc1318e029ca is the commit postsubmits are reporting to
- failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-busybox-test-images/1366557273911988224
- failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-httpd-new-test-images/1366557274046205952 (... sigh, and this one seems like the exact same error message as before @claudiubelu )

**Comment by claudiubelu** [comment]
It seems that it was succesful for the following images:

glusterdynamic-provisioner: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-glusterdynamic-provisioner-test-images/1366557273958125568
httpd: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-httpd-test-images/1366557274016845824
nginx: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-nginx-test-images/1366557274096537600
nginx-new: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-nginx-test-images/1366557274096537600
perl: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-perl-test-images/1366557274436276224

It seems that it failed for:

busybox: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-busybox-test-images/1366557273911988224
httpd-new: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-httpd-test-images/1366557274016845824


It seems that for the httpd-new image, it generated the same SHA:

```
 #5 exporting to image
#5 exporting layers done
#5 exporting manifest sha256:00c98fa2a69a9f208dd7238549587df778f584ea4d56a0deb977c4ae4b1f6352 0.0s done
#5 exporting config sha256:6b84c32240b147c355e6400fc17e7bb7111cf6687ced6e75a3ad3ff1b2aaf8dc done
#5 pushing layers 0.0s done
#5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/httpd:2.4.39-1-linux-amd64
#5 pushing manifest for gcr.io/k8s-staging-e2e-test-images/httpd:2.4.39-1-linux-amd64 0.2s done
#5 ERROR: failed commit on ref "manifest-sha256:00c98fa2a69a9f208dd7238549587df778f584ea4d56a0deb977c4ae4b1f6352": unexpected status: 401 Unauthorized 
```

This sha already exists:

```
docker pull gcr.io/k8s-staging-e2e-test-images/httpd:2.4.39-alpine-linux-amd64
2.4.39-alpine-linux-amd64: Pulling from k8s-staging-e2e-test-images/httpd
050382585609: Pull complete
231e07644ff6: Pull complete
1eeb2e94cd0a: Pull complete
8cc6fadd0bd1: Pull complete
5f4e88dd5259: Pull complete
Digest: sha256:00c98fa2a69a9f208dd7238549587df778f584ea4d56a0deb977c4ae4b1f6352
Status: Downloaded newer image for gcr.io/k8s-staging-e2e-test-images/httpd:2.4.39-alpine-linux-amd64
```

Somehow, I missed adding the label to the Dockerfile... oups! Sent a PR here: https://github.com/kubernetes/kubernetes/pull/99631

For the busybox image, it failed on the Windows images, I'll take a look at that. But the idea worked. :)

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-longterm
/milestone v1.22
I think this is still relevant, but I don't think we urgently need to do anything to solve this anymore, correct @claudiubelu?  

If we don't need to solve, I'd rather wait for the fix to come to us.

AFAICT the latest release of moby/buildkit still lacks the fix, as does `docker buildx`
- https://github.com/containerd/containerd/pull/4942 landed 2020-01-14
- https://github.com/moby/buildkit/releases/tag/v0.8.3 is the latest release of moby/buildkit
- https://github.com/moby/buildkit/blob/v0.8.3/go.mod uses a fork based on https://github.com/containerd/containerd/commit/0edc412565dcc6e3d6125ff9e4b009ad4b89c638 which was 2020-11-17, and does not include https://github.com/containerd/containerd/pull/4854
- https://github.com/docker/buildx/blob/v0.5.1/go.mod also uses the same commit of container

But I suspect it's coming soon:
- https://github.com/containerd/containerd/releases/tag/v1.5.0 was released 4 days ago
- https://github.com/moby/buildkit/pull/2102 landed in moby/buildkit shortly thereafter
- https://github.com/docker/buildx/blob/master/go.mod currently pulls in 0.8.2-xxx of buildkit, and 1.5.0-beta4 of containerd

The alternative would be someone taking on the work of using unreleased code.

**Comment by spiffxp** [comment]
I'm kicking this off the wg-k8s-infra project board since it seems like no action required on our part

**Comment by spiffxp** [comment]
/remove-area prow
/area artifacts
This also doesn't specifically have to do with prow.  I'm not entirely sure it even belongs in this repo, but I'll leave it in tagged with artifacts for now, since the issue is with pushing multi-arch artifacts to k8s.gcr.io that are built with a broken `docker buildx`

**Comment by spiffxp** [comment]
/area images
The actual dependency will need to come in through the image used by https://github.com/kubernetes/kubernetes/blob/master/test/images/cloudbuild.yaml

So like a PR to update this: https://github.com/kubernetes/test-infra/blob/97239cd4768fd4aa391c351314f66689dcc34e9e/images/gcb-docker-gcloud/Dockerfile#L44-L48

And a subsequent PR to kubernetes/kubernetes to update cloudbuild.yaml

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/pull/22977 to take a crack at bumping buildx to the latest release to see if this fixes this issue

**Comment by claudiubelu** [comment]
> 
> 
> Opened #22977 to take a crack at bumping buildx to the latest release to see if this fixes this issue

Did this fail since then? I thought we solved this a few months ago. The issue was that the same SHA couldn't be pushed again, so we added a label in the images / dockerfiles. Haven't seen it fail since.

**Comment by spiffxp** [comment]
>The issue was that the same SHA couldn't be pushed again

This is what I'm trying to prove is fixed.  We should never have had to do the workaround in the first place.

**Comment by claudiubelu** [comment]
The issue has been resolved some time ago. We have promoted httpd images since this was open, and the last job was green as well: https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-httpd-test-images

/close
