### ISSUE TITLE
Kubetest for GKE should support --autoprovisioning-config-file upon cluster creation

### ISSUE THREAD

**Issue by BigDarkClown** [kubernetes/test-infra#20883]
**What would you like to be added**:

Some GKE cluster creation arguments, such as `--autoprovisioning-config-file`, require creating a file containing desired config first, and then providing the filename during cluster creation. There is currently no way to provide this config and put it into file which could be provided during cluster creation.

**Why is this needed**:

Some NAP settings are configurable only via this argument. One of them is `diskSizeGb`, which determines the disk size of nodes in nodepools created by NAP. Default value of 100GB is too high for use cases involving thousands of nodes, so it would be nice to have this property configurable via a flag in `kubetest/gke.go`.

**Comment by amwat** [comment]
For advanced use cases (such as this) we already expose a way to customize the create call

https://github.com/kubernetes/test-infra/blob/da3e82a55e41120ea0355a9e59bc57dc2b012d83/kubetest/gke.go#L53

Can you try to see if that works for your use case?

**Comment by BigDarkClown** [comment]
I have tried this approach, but it does not address the core of the problem I have. Yes, I can provide a flag this way, but **first** I have to create a file containing configuration that will be passed with that flag. So basically I would need to have some additional way to pass a NAP configuration into the file that `gke-create-command` can access.

**Comment by amwat** [comment]
Still not sure I understand completely, does an existing file on disk from wherever you are invoking kubetest not work?
shouldn't be any different from passing each argument individually to kubetest and then kubetest creating that same file.
