### ISSUE TITLE
Make it clear which version of kubetest or kubetest2 is being used

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#20886]
We may have `deprecated` kubetest, but it's still in use.  Whatever we do here should support `kubetest2` or be included in `kubetest2`

https://github.com/kubernetes/kubernetes/pull/96987#issuecomment-780646063 is an example of confusion over the fact that changes to `kubetest` don't take effect until job configs are updated to a new image (e.g. `kubekins`)

We could stand to document how changes flow a better.  But it might help for troubleshooting if we make it clearer what version of kubetest is being used.

Ideas include:
- log the version kubetest was built at
- have kubetest log its version
- store version info as an artifact
- include kubetest's version in `metadata.json` so it can be displayed as a custom testgrid column (maybe related to https://github.com/kubernetes/test-infra/issues/20650)

**Comment by BenTheElder** [comment]
cc @amwat

**Comment by spiffxp** [comment]
/remove-help
Please ping with any questions if you need help

**Comment by amwat** [comment]
> Whatever we do here should support kubetest2 or be included in kubetest2

tracked here: https://github.com/kubernetes-sigs/kubetest2/issues/108

**Comment by supriya-premkumar** [comment]
Hi @spiffxp, apologies for the delay. I have this WIP [PR](https://github.com/kubernetes-sigs/kubetest2/pull/111)
I will revive the PR and work on this one. Thank you 🙏🏽

**Comment by spiffxp** [comment]
/milestone v1.23
What remains to be done here? I swear I talked about this last meeting and have already forgotten the things we linked through to discover that there was still work to actually add it to `metadata.json` and setup testgrid column headers

**Comment by amwat** [comment]
We still need to add a testgrid column-header in https://github.com/kubernetes/test-infra/blob/master/config/testgrids/default.yaml#L10

to read https://github.com/kubernetes/test-infra/pull/21276/files#diff-71dd7bf85cfecc6c2c2fa0956ad5f182433bcc0f287aaa83f2052eb3f8ba9710R525

(probably we should consider an agnostic name to also cover kubetest2)

I also have a PR open to square off the kubetest2 parts https://github.com/kubernetes-sigs/kubetest2/pull/162
