### ISSUE TITLE
Prow/spyglass/junit lense: not able to handle large number of junit result files in GCS

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#20954]
**What happened**:

When there are lots of junit result files, i.e. 1000 of them, even if each file only contains single test case, spyglass would not be able to load it.

**What you expected to happen**:

Spyglass can handle large number of files.

**How to reproduce it (as minimally and precisely as possible)**:

Run a prowjob that generates large number of junit results files.

**Please provide links to example occurrences, if any**:

Experiment PR: https://github.com/kubernetes/test-infra/pull/20953
Spyglass link that has this trouble: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/20953/pull-test-infra-bazel/1364012873247887360

**Anything else we need to know?**:

This is probably intended. If that's the case, should there be a `num_limit` like `size_limit` here https://github.com/kubernetes/test-infra/blob/4ffadaa6a42566050fd5f69c1930c5440d32d6fa/config/prow/config.yaml#L46?

**Comment by chaodaiG** [comment]
/area prow
CC @cjwagner @fejta @michelle192837 @alvaroaleman

**Comment by chaodaiG** [comment]
Was expecting to debug with runlocal but could not repro locally. 

![Screen Shot 2021-02-22 at 8 38 17 PM](https://user-images.githubusercontent.com/45011425/108802848-ff3c3700-754d-11eb-9913-56a9b0dd956f.png)

Note that runlocal with anonymous GCS authentication failed rendoring spyglass page with:
```
error rendering spyglass page: error when resolving real path gs/kubernetes-jenkins/pr-logs/pull/test-infra/20953/pull-test-infra-bazel/1364012873247887360: Get "https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/test-infra/20953/pull-test-infra-bazel/1364012873247887360.txt": oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "reauth related error (invalid_rapt)",
  "error_subtype": "invalid_rapt"
}
```
Didn't figure out how to fix that so passed in my own gcs credential for runlocal, not sure whether this matters or not.

**Comment by alvaroaleman** [comment]
@chaodaiG is this an issue you actually encountered somewhere or just something you figured could happen?

I suppose we can parallelize the fetching to some degree, if the wallclock time of fetching is the issue.

**Comment by chaodaiG** [comment]
@alvaroaleman , this was observed by one of our users on our internal prow instance, repro it here just for illustrating the problem.

As far as I can tell the fetching of artifacts is already parallelized https://github.com/kubernetes/test-infra/blob/1da5e48e74af998daa92ea9ad5c135bd28feef45/prow/spyglass/lenses/junit/lens.go#L146, my suspicion was GCS throttling but there is no evidence yet.

**Comment by chaodaiG** [comment]
One more experiment: combining the junit results in https://github.com/kubernetes/test-infra/pull/20969 and spyglass rendered junit section pretty fast https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/20969/pull-test-infra-bazel/1364256884990676992
