### ISSUE TITLE
somehow indicate which JUnit file a test failure came from

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#210]
Motivating example: unit/integration test runs like https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/27600/kubernetes-pull-test-unit-integration/32233 have multiple JUnit files, with associated "verbose output" text files that can help debug test failures.

Rather than searching through each file, it'd be nice to know which one to go to for the verbose output. (Maybe even link directly to that file if it exists? May be getting too specific though.)

**Comment by fejta** [comment]
Thoughts on this?

**Comment by rmmh** [comment]
This is done, Gubernator now links to the XML file for each failure
