### ISSUE TITLE
`needs-rebase` application is delayed, only seems to be triggered on comment

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#21006]
**What happened**:

For many PRs in k/k that I've triaged, there were conflicts present for days, but the needs-rebase label is not getting applied automatically. The bot only seems to apply it upon prompting.

**What you expected to happen**:

`needs-rebase` should be applied as soon as a merge conflict is present (with some reasonable buffer).

**How to reproduce it (as minimally and precisely as possible)**:

Here's an example of something that needs a rebase but is missing the label: https://github.com/kubernetes/kubernetes/pull/88172

**Please provide links to example occurrences, if any**:

- https://github.com/kubernetes/kubernetes/pull/92888#issuecomment-762539759
- https://github.com/kubernetes/kubernetes/pull/98825
- https://github.com/kubernetes/kubernetes/pull/99000
- etc.

**Anything else we need to know?**:

Right now, when we put a comment to trigger the bot into adding a needs-rebase label, it resets the stale/rotten timer on PRs with "activity". Ideally we'd like a way to avoid that.

**Comment by alvaroaleman** [comment]
The basic issue is that a state change to needs-rebase doesn't have an event associated, as its the result of the base branch changing (usually). So the only way to figure this out is to scan all PRs, which is expensive in terms of github api quota.

What happens today is that we check all PRs every 24 hours for this: https://github.com/kubernetes/test-infra/blob/ae42f5b65b6577cf20f0c58d238d96524ab6927c/prow/external-plugins/needs-rebase/main.go#L73

I would assume that the plugin [gets heavily throttled when it does its check](https://github.com/kubernetes/test-infra/blob/ae42f5b65b6577cf20f0c58d238d96524ab6927c/prow/external-plugins/needs-rebase/main.go#L108) and Prow gets bumped before it makes much progress, resulting in a reset of the 24h timer. This would also explain why it usually does something on the weekend (no bumps, so even if slow, it makes so progress). Maybe just reduce that interval to 12h?

**Comment by ehashman** [comment]
I'm certain that PRs are currently being missed right now. The example PR of https://github.com/kubernetes/kubernetes/pull/88172 has needed a rebase for well over 24h -- I think the incompatible change was made 5mo ago.

**Comment by ehashman** [comment]
https://github.com/kubernetes/kubernetes/pull/68726 another example of a PR that needed a rebase for months but it only got applied after an action (in this case, me closing the PR)

**Comment by nikhita** [comment]
another example - https://github.com/kubernetes/kubernetes/pull/98334

cc @pacoxu
