### ISSUE TITLE
tide not looking for PR created by GitHub App?

### ISSUE THREAD

**Issue by goern** [kubernetes/test-infra#21025]
**What happened**:
We have a certain category of PR being created by a GitHub App, https://github.com/marketplace/khebhut Therefore the user creating the PR is `"user.login": "khebhut[bot]"`, the corresponding GitHub query seems to require `author:app/khebhut`. 

Tide is not finding this kind of PR.

**What you expected to happen**:

Tide should figure out that the PR has been create by a [bot] and therefore prepend app/ to the user.login and strip [bot] from the user.login

**How to reproduce it (as minimally and precisely as possible)**:

have a GitHub app open a PR

**Please provide links to example occurrences, if any**:

https://github.com/pulls?q=is%3Apr+repo%3AAICoE%2Fsefkhet-abwy+author%3Aapp%2Fkhebhut+head%3Av0.21.0 

**Anything else we need to know?**:
no ;) thanks for all the work!

**Comment by alvaroaleman** [comment]
@goern can you please link to the tide query you have set up? The PRs you linked to have a tide status context, indicating everything works as expected

**Comment by hi-rustin** [comment]
No problem for me, works fine. Please see: https://github.com/ti-community-infra/tichi/pull/360

Maybe it's a problem with your configuration.

**Comment by goern** [comment]
@alvaroaleman  tide config is at https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/cnv-prod/config.yaml#L103

the PR have been merged by humans, as tide did do... 

@hi-rustin I think we are running basically the same config, wdyt?

**Comment by hi-rustin** [comment]
As an example: this repository configuration of yours: https://github.com/thoth-station/thoth-application/blob/fa28df9327aeb9577f498ff23dc719e07d95116e/prow/overlays/cnv-prod/config.yaml#L246

But this [PR](https://github.com/thoth-station/user-api/pull/1286) of yours doesn't pass these required tests, so tide can't merge the pr for you.

**Comment by alvaroaleman** [comment]
@goern none of your queries reference an author in any way, hence Tide is not going to include an author in the query, hence whatever your issue, its unrelated to the PR being created by a bot account. Additionally, PRs created by bots generally do work, see for example https://github.com/openshift/assisted-installer/pull/149

**Comment by goern** [comment]
thanks for the second and third pair of eyes. I'll have another look at the conditions! Maybe 

@alvaroaleman I am still unsure why https://prow.operate-first.cloud/pr?query=is%3Apr%20repo%3AAICoE%2Fsefkhet-abwy%20author%3Akhebhut%20head%3Av0.21.0 is not giving any PR but https://prow.operate-first.cloud/pr?query=is%3Apr%20repo%3AAICoE%2Fsefkhet-abwy%20author%3Aapp%2Fkhebhut%20head%3Av0.21.0 does, and it ok as it is.

**Comment by alvaroaleman** [comment]
@goern Presumably because that query has `head:v0.21.0` in it which is unlikely to match more than one pr unless you created more than one pr from head:v0.21.0. Your app demands access to private repos though, so I am most certainly not going to install it on my gh account.
