### ISSUE TITLE
prometheus-operator log noise in prow.k8s.io

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#21091]
**What happened**:

Lots of logs like:

> 2021-03-01 12:29:01.044 PST
github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:237: Failed to list *v1beta2.StatefulSet: the server could not find the requested resource

**What you expected to happen**:

We should run a version that is not failing to list / not spamming the logs

**How to reproduce it (as minimally and precisely as possible)**:

check the logs for the prow.k8s.io services cluster, filter for warning+

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
/area prow

**Comment by chaodaiG** [comment]
This was fixed by upgrading prometheus operator to new version, see https://github.com/kubernetes/test-infra/issues/21138#issuecomment-794050016 for context
