### ISSUE TITLE
Add new key/value pairs in cluster-api vsphere provider secret

### ISSUE THREAD

**Issue by srm09** [kubernetes/test-infra#21099]
**What would you like to be added**:
I would like to add two new key/value pairs to the `clusterapi-provider-vsphere-ci-prow` secret. It is a public/private key pair that needs to be used in tests.

**Why is this needed**:
We are enabling log collection for the e2e test suite in [kubernetes-sigs/cluster-api-provider-vsphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere). This requires a key pair to be used while deploying the testing resources. This will then be used to ssh into the instances and collect required log info.

**Comment by fejta** [comment]
`secret/clusterapi-provider-vsphere-ci-prow configured`

**Comment by srm09** [comment]
Reusing this same issue to add more key/value pairs to the Cluster API vSphere provider secret:

Need to add a few more values to the `clusterapi-provider-vsphere-ci-prow` secret.

**Comment by fejta** [comment]
applied again

**Comment by BenTheElder** [comment]
Appears to be done.
Please /reopen or file a new one if I got this wrong.
