### ISSUE TITLE
Update the secret value in cluster-api-provider-digitalocean-token

### ISSUE THREAD

**Issue by prksu** [kubernetes/test-infra#21111]
**What would you like to be added**:

I would like to update the secret value in the `cluster-api-provider-digitalocean-token` secret. It's digital ocean access token that used for cluster-api-provider-digitalocean and kops CI

**Why is this needed**:

Our CI was failing since 2-18 https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-digitalocean#periodic-conformance-v1alpha3
The error is auth problems, after discussing with other maintainers we decide to update the secret.

/cc @fejta

**Comment by fejta** [comment]
Secret has been applied to the cluster

**Comment by prksu** [comment]
/close

Thanks @fejta
