### ISSUE TITLE
Testgrid complains on "podinfo.json" not found and marks conformance tests as failed

### ISSUE THREAD

**Issue by dguendisch** [kubernetes/test-infra#21126]
**What happened**:
[Gardener](https://github.com/gardener/gardener) reports conformance tests (and others) since some years into testgrid for various cloudproviders and various k8s versions.
Since yesterday all of our conformance tests are marked as failed because of a test named `Pod` and the error `podinfo.json not found...`
See e.g. https://testgrid.k8s.io/conformance-all#Gardener,%20v1.20%20AWS

What's the issue with the tests and what is this presumably new `Pod` test (not marked as conformance) about?

**What you expected to happen**:
Tests to be marked as succeeded when all conformance tests passed.

cc @schrodit

**Comment by thejoycekung** [comment]
This is also happening on the [Conformance - Openstack](https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20OpenStack) job as well. 

/area provider/openstack

**Comment by thejoycekung** [comment]
for visibility: 
/remove-area provider/openstack
/cc @kubernetes/provider-openstack-misc

**Comment by BenTheElder** [comment]
`podinfo.json` is an artifact prow produces about the pod it ran tests in. asking the testgrid owners about this.

**Comment by BenTheElder** [comment]
see: https://github.com/GoogleCloudPlatform/testgrid/issues/393

**Comment by dguendisch** [comment]
I see that GoogleCloudPlatform/testgrid#393 got fixed by adding the option to disable the prow analysis with https://github.com/GoogleCloudPlatform/testgrid/pull/396
Does that mean I could just add `disable_prowjob_analysis: true` to every entry like [this one](https://github.com/kubernetes/test-infra/blob/master/config/testgrids/conformance/conformance-all.yaml#L25)?
In the same line, could I add this config as well [here](https://github.com/kubernetes/test-infra/blob/master/config/testgrids/gardener/config.yaml) or probably on a more global place?

**Comment by chases2** [comment]
If there's a subdirectory of them, it might make sense to add a default.yaml in a subdirectory, but this isn't working right yet. See https://github.com/kubernetes/test-infra/issues/20756

**Comment by dguendisch** [comment]
Hmm, I added the respective line `disable_prowjob_analysis: true` with https://github.com/kubernetes/test-infra/pull/21280 which got merged on 10th March. However e.g. our AWS testresults from today 11th March still show the failing pod info row: https://testgrid.k8s.io/conformance-gardener#Gardener,%20v1.20%20AWS
@chases2: am I missing something? Or just need to wait longer?

**Comment by dguendisch** [comment]
@chrigl did it work for you to disable the prow analysis row on openstack tests?
@chases2 as written above, disabling doesn't seem to work. Any idea what's wrong?

**Comment by chases2** [comment]
I think we need to update TestGrid to v0.0.55 to start recognizing and serializing the option.

Change: https://github.com/GoogleCloudPlatform/testgrid/commit/5f5f56bab5a9f507366bd102455ddf7921fdc5e4
Update PR: https://github.com/kubernetes/test-infra/pull/21400

**Comment by dguendisch** [comment]
Seems that the above mentioned update was done and everything (`disable_prowjob_analysis: true`) works now as expected.
/close
