### ISSUE TITLE
For upgrade tests, retain logs prior to upgrade

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#2112]
[etcd.log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gci-latest-rollback-etcd/51/artifacts/bootstrap-e2e-master/etcd.log) is the etcd log from an etcd rollback test.  Since we blow away the master, it's only the portion of log lines from after the upgrade.  But lines from the first master can sometimes help debugging, too.  Can we retain these?  I guess it might need a hook within the test specifying when the right time is to save the logs.

cc @krousey @wojtek-t

**Comment by ixdy** [comment]
seems somewhat related to https://github.com/kubernetes/kubernetes/issues/18432.

In https://github.com/kubernetes/kubernetes/pull/20102 we added a `framework.CoreDump` call before/after resizing nodes. Maybe we can do something similar here?

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing-misc

**Comment by mml** [comment]
Yeah.  This is a specific case of kubernetes/kubernetes#18432.

**Comment by fejta** [comment]
test-infra will upload whatever is in the `_artifacts` dir, and gubernator &c will show whatever is uploaded to GCS.

IMO this seems like a kubernetes/kubernetes change to the test infra there.
