### ISSUE TITLE
Make #prow-alerts less noisy

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#21138]
> /cc @spiffxp @cjwagner @stevekuznetsov 
> 
> 
> 
> The current change proposes to send these to `prow-alerts` channel instead of `testing-ops` to avoid spamming the latter and make it less valuable. However currently `prow-alerts` is pretty spammy, are we sure the current alerts are looked at?

I think we should vastly increase the threshold for or remove the ghproxy alerts entirely. Informational alerts are good, but those seem to be pure noise that be adequately tracked via ghproxy graphs

But I don't think that precludes adding these to that channel

__Originally posted by @spiffxp in https://github.com/kubernetes/test-infra/pull/21136#issuecomment-789999648__

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/21192 merged, need to see if these changes are live yet. The channel still has a bunch of ghproxy alerts

**Comment by chaodaiG** [comment]
The changes from https://github.com/kubernetes/test-infra/pull/21192 are not live yet, the config from the PR was applied, but somehow it didn't land on prometheus alerter, so it's still using the old configmap. The weird thing is that `kind: PrometheusRule` in the cluster was updated with the new values from #21192, but the configmap `prometheus-prow-rulefiles-0` which was mounted on prometheus pod was not updated (It should have been generated from `PrometheusRule`.)

My suspicion was that previous upgrade https://github.com/kubernetes/test-infra/pull/20456 and the revert https://github.com/kubernetes/test-infra/pull/20457 had messed up something. Planning to roll forward with https://github.com/kubernetes/test-infra/pull/20484 to see if this can be fixed

cc @cjwagner for awareness

**Comment by chaodaiG** [comment]
There are recurring errors in prometheus operator:
```
E0309 15:27:16.435071       1 reflector.go:134] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:237: Failed to list *v1beta2.StatefulSet: the server could not find the requested resource
```

v1beta2 was deprecated in k8s v1.16 per https://www.pulumi.com/docs/reference/pkg/kubernetes/apps/v1beta2/statefulset/#statefulset, so actually it has nothing to do with the previous upgrade and revert, and I think the correct fix is actually pull prometheus operator forward to make it compatible with k8s v1.16

**Comment by chaodaiG** [comment]
This was done
/close
