### ISSUE TITLE
Decouple test image bumping from prow bumping

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#21137]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99655/pull-kubernetes-unit/1367006331575209984
=> prowjob yaml button =>
https://prow.k8s.io/prowjob?prowjob=cb9cbe1e-7bed-11eb-97bd-22fa521bf179
=> look for image: =>
gcr.io/k8s-testimages/kubekins-e2e:v20210226-c001921-master

yeah that's not going to have the go1.16, looks like we haven't had a prow bump since 02/26

we need to decouple these update loops (images for prow itself, test images) as we discussed at the last SIG testing. cc @spiffxp

__Originally posted by @BenTheElder in https://github.com/kubernetes/kubernetes/pull/99655#issuecomment-789494480__

**Comment by BenTheElder** [comment]
cc @chaodaiG

**Comment by chaodaiG** [comment]
cc @mpherman2 as well

**Comment by spiffxp** [comment]
Pulling out of https://github.com/kubernetes/test-infra/pull/21144#pullrequestreview-604489193

One question for followup: is there some way we could have merges of just these autobump PRs alert to slack?

A longer term thing: someplace to see all deploys and all config changes pushed to prow.k8s.io to aid "what changed when"

But for now being filter down just to "big PRs that change a lot" matches the current experience people are used to. I'd rather not take away what they're used to before having something better.

**Comment by spiffxp** [comment]
Let's figure out what it would look like to hand this off to community.  My sketch:
- if they can, community members in appropriate OWNERS can approve these now
- wait until after code freeze, formally handoff ASAP
- use existing groups (ci-signal or release-eng) or use this to bootstrap a prowjob-oncall
- making sure the group knows
  - start with empty oncall field and hardcode ping to appropriate github team?
  - move to something generated by and stored in community
- document that this is how jobs configs are bumped for prow.k8s.io (a linkable subheading of https://github.com/kubernetes/test-infra/tree/master/config/jobs if there isn't a better place)

**Comment by spiffxp** [comment]
/reopen
the job landed, but there's still more to do

**Comment by chaodaiG** [comment]
Also https://github.com/kubernetes/test-infra/pull/21144 probably had left out some of the images in prow jobs that's part of prow but not `gcr.io/k8s-testimages`. I will take a look at the new bumping PRs generated and see what's missing

**Comment by BenTheElder** [comment]
@chaodaiG this was completed right?

**Comment by chaodaiG** [comment]
Yep it was completed

**Comment by BenTheElder** [comment]
Thank you!

**Comment by spiffxp** [comment]
/reopen
Handoff never happened as described in https://github.com/kubernetes/test-infra/issues/21137#issuecomment-790905960

**Comment by spiffxp** [comment]
FYI @kubernetes/release-engineering

**Comment by justaugustus** [comment]
For SIG Release: I'm happy to have @kubernetes/release-managers in this approval group

**Comment by spiffxp** [comment]
Thanks to the following PRs:
- https://github.com/kubernetes/test-infra/pull/23602
- https://github.com/kubernetes/test-infra/pull/23610
- https://github.com/kubernetes/org/pull/2979
- https://github.com/kubernetes/test-infra/pull/23644
- https://github.com/kubernetes/test-infra/pull/23736

We now autobump job images and automatically deploy the change twice a day (if there are any changes to deploy):
- https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Ak8s-infra-ci-robot+is%3Aclosed++label%3Askip-review
- https://testgrid.k8s.io/sig-testing-prow#autobump-prowjobs-for-auto-deploy

**Comment by spiffxp** [comment]
/close
Announcement: https://groups.google.com/g/kubernetes-dev/c/aBzQQw8KgUU/m/wnOtP5vjDAAJ
