### ISSUE TITLE
peribolos: expired/failed invitations are treated as active

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#21140]
When a user's invitation to join an org is expired (they have seven days to accept it), the invitation becomes failed. `peribolos` today treats this as if the invitation were active, and continues to "wait" for the user to accept it. Ideally we'd re-send it.

/area prow/peribolos

**Comment by alvaroaleman** [comment]
Duplicate of https://github.com/kubernetes/test-infra/issues/20872
/close
