### ISSUE TITLE
prow PR history page may go off screen with no scrollbar

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#21150]
**What happened**: https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=99012 goes off screen

**What you expected to happen**: there should be a horizontal scrollbar when it doesn't fit in the image

**How to reproduce it (as minimally and precisely as possible)**: open any PR history page in a sufficiently small browser window.

**Please provide links to example occurrences, if any**: https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=99012

**Anything else we need to know?**:

/area prow
/area prow/deck

**Comment by BenTheElder** [comment]
The code for this is in [prow/cmd/deck](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/deck), specifically [prow/cmd/deck/template/job-history.html)](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/template/job-history.html).

This is probably a pretty good first issue.

**Comment by alvaroaleman** [comment]
@BenTheElder I do have a horizontal scrollbar in both chrome and firefox, do you maybe have a screenshot or sth?

<img width="1909" alt="scrollbar" src="https://user-images.githubusercontent.com/6496100/109975828-0f2fe580-7cc9-11eb-85da-e7fd1a50c977.png">

**Comment by BenTheElder** [comment]
ah so, the scrollbar is auto-hiding (blame mac?)
not a big deal for vertical scroll but for horizontal scroll that's problematic using a mouse and/or there's not an expecation that it would scroll.
testgrid has the same "issue".

sorry for the noise.
