### ISSUE TITLE
Sidecar doesn't properly handle best effort upload and races with entrypoint.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#21167]
We've recently had multiple presubmits report failure in spyglass and finished.json even though they were actually aborted due to more recent commits being pushed. The ProwJob resource disagrees with finished.json and properly indicates the aborted state.

I think we are encountering this race: https://github.com/kubernetes/test-infra/blob/2a5710e4ad2ee2942634c60e5c0f753f4012a877/prow/sidecar/run.go#L90-L95

This option is designed to help mitigate when used in conjunction with an appropriate graceperiod timeout: https://github.com/kubernetes/test-infra/blob/2a5710e4ad2ee2942634c60e5c0f753f4012a877/prow/sidecar/options.go#L50-L77

However, the option is always set to false, we don't have a way to configure it: https://github.com/kubernetes/test-infra/blob/276f55e384c73100f0a3c2e8f27cf126104f93d6/prow/pod-utils/decorate/podspec.go#L723

<hr>

I think the comment describing the race is misleading and the logic could be improved here. In particular we don't actually try to perform the upload twice if an interrupt is received, we just immediately begin the upload then terminate. I would expect sidecar to immediately begin the upload, but then check/wait for the marker files to be written, and reupload when the markers are present.
Based on the comment this sounds like what was actually intended.

/help

**Comment by viveksyngh** [comment]
I would like to work on this issue

**Comment by stevekuznetsov** [comment]
I think that's what the behavior did when I originally wrote it @cjwagner lol. Perhaps that's been broken since. Unfortunately hard to e2e test this component.

**Comment by stevekuznetsov** [comment]
@viveksyngh sure thing - shoot me an /assign and I'll review when you are ready

**Comment by stevekuznetsov** [comment]
Actually @cjwagner as of https://github.com/kubernetes/test-infra/pull/20923 we should intelligently set the Pod's `terminationGracePeriodSeconds` to be larger than the `entrypoint`'s grace period, so perhaps it would be safe to default to ignoring interrupts if we think that the default buffer we add is enough to do the upload.

**Comment by cjwagner** [comment]
> so perhaps it would be safe to default to ignoring interrupts if we think that the default buffer we add is enough to do the upload.

That would be one way to mitigate this problem and it would probably be sufficient most of the time, but I don't think it is as robust as doing a best effort upload then continuing to wait and try the real upload. The double upload seems strictly better since it ensures that we upload something even if the main upload takes too long to complete.

**Comment by viveksyngh** [comment]
I have opened a draft MR to #21644 to address this, where I am adding a field in DecorationConfig to allow configuring IgnoreInterrupts for sidecar. Please let me know if I am moving in right direction here.
