### ISSUE TITLE
HMAC reconciler does not exit non-zero on failure => Postsubmit succeeds on failure.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#21171]
**What happened**:
The [HMAC reconciler](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/hmac) encountered an error, but the postsubmit job still succeeded: https://oss-prow.knative.dev/view/gs/oss-prow/logs/post-oss-test-infra-reconcile-hmacs/1367626368740757504

**What you expected to happen**:
If any errors occur that cannot be recovered from, the tool should exit with a non-zero exit code so that the postsubmit ProwJob reports failure.

/help
/good-first-issue

**Comment by MadhavJivrajani** [comment]
Hi! I'd like to work on this if possible 😄 
/assign
