### ISSUE TITLE
Coverage Job in constant fail state due to go_test

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#21190]
**What happened**:
The `ci-kubernetes-coverage-unit` job executes coverage for all `*_test.go` under k8s root. If a test fails, the whole job fails. There are several tests I see failing: [Job](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-coverage-unit/1367751836915732480)

I plan to 1) Always pass the coverage Job, within the TestGrid results we should see "pass/fail" coverage data. That is meant to be actionable. 

2) I will look into the test failures and see where they originate from and if there is work to be done on stability. 

**What you expected to happen**:
Coverage should surface coverage numbers and not corrupt Triage results with mass failures.

**How to reproduce it (as minimally and precisely as possible)**:
Run `make test KUBE_COVER=y KUBE_COVER_REPORT_DIR="${ARTIFACTS}" KUBE_TIMEOUT="--timeout=300s"` within k8s and see if tests fail.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

/area metrics
/sig testing
/cc @liggitt @spiffxp

**Comment by BenTheElder** [comment]
> Coverage should surface coverage numbers and not corrupt Triage results with mass failures.

why is triage corrupted by mass failures? are tests failing more often under coverage?
shouldn't we fix the tests? or exclude the junit from triage?

**Comment by MushuEE** [comment]
I had blanked that we have previously seen this and these jobs should be excluded but are not, making a new issues for the kettle exclude failure.
