### ISSUE TITLE
[Kettle] Exclude Job list not excluding results

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#21193]
**What happened**:
Kettle has a job exclusion list: https://github.com/kubernetes/test-infra/tree/master/kettle#adding-buckets

Jobs in this list should not be added to metrics, however they are: ci-kubernetes-coverage-unit

**What you expected to happen**:
ci-kubernetes-coverage-unit job is not included in metrics values

**How to reproduce it (as minimally and precisely as possible)**:
View BQ table for job results and see the ci-kubernetes-coverage-unit job is being uploaded.

**Please provide links to example occurrences, if any**:
`SELECT * FROM `k8s-gubernator.build.day` where job = "ci-kubernetes-coverage-unit" LIMIT 1000` 

**Anything else we need to know?**:
/assign

**Comment by BenTheElder** [comment]
@MushuEE did you already fix this?

**Comment by MushuEE** [comment]
It has a temporary fix from the Triage side. We were going back and forth on where the exclusion should be: Should kettle pick up everything and Triage filters or vice versa. Will close for now
