### ISSUE TITLE
Regression in e2e-runner.sh

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/test-infra#2120]
After refreshing my inherited image (ci-kubernetes-e2e-kubeadm), I started getting `e2e-runner.sh` errors:

    W0303 22:30:00.903] /workspace/e2e-runner.sh: line 119: syntax error near unexpected token `fi'

It looks like this was introduced in https://github.com/kubernetes/test-infra/commit/4f0029329e4892236bfdfa15714333711d158c56, by inserting an extra `fi`.

**Comment by fejta** [comment]
Among other things I fix this in https://github.com/kubernetes/test-infra/pull/2110

**Comment by pipejakob** [comment]
Ah, good deal. Thanks.

**Comment by fejta** [comment]
Fixed
