### ISSUE TITLE
Consider using internal packages to clarify test-infra API boundaries

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#21268]
I didn't know about `internal`, thats neat.

> If test-infra was now talking a stance of "We put everything we don't explicitly consider an api in an internal package" the realistic result might be that we end up copying code and extending it downstream instead of contributing upstream.

I can imagine the flip side of this. Code is already being extended downstream instead of upstreaming changes, right? It just involves importing external dependencies rather than copying. I would think using internal packages would promote more upstream contributions rather than out-of-tree extensions.
Being able to distinguish source that we don't want to have used elsewhere would make upstream development a lot easier. Today it is unclear when libraries are used externally and the libraries that are typically weren't designed with that in mind (some were explicitly against that such as Prow's `github` package), so avoiding breaking downstream consumers is difficult and we are accumulating technical debt in the process as we add new functions while maintaining existing ones rather than refactoring.

I don't think "We put everything we don't explicitly consider an api in an internal package" would actually be limiting either. For example, if we did put everything that is not an explicit API in an internal package that wouldn't preclude us from making explicit APIs as needed and moving code out of internal. This would just help us make intentional decisions about libraries that are consumed externally and ensure there is code review with that decision in mind. I would like to see a smaller external API surface area, but labeling code that is part of that surface area is the more pressing issue for me.

Doing this retrospectively might be prohibitively difficult and disruptive, but I'd like some way to mitigate this issue going forward at least.

__Originally posted by @cjwagner in https://github.com/kubernetes/test-infra/pull/20353#issuecomment-794356540__

**Comment by spiffxp** [comment]
/assign @cjwagner @alvaroaleman 
/sig testing 
I have no strong opinion here but felt like this was worth breaking out into its own issue

**Comment by BenTheElder** [comment]
KIND uses `internal` to pretty good effect. Currently where we are at:
- the CLI / binary app logic is importable
- the APIs the binary app / CLI commands depend on directly are importable
- any further implementation detail packages breaking up that logic are generally in `internal` subtrees
- some of the code is internal to a specific subtree, not available to the rest of the repo. e.g. cluster creation is broken into many subpackages, but is not exposed to say, the packages that build kubernetes source

Given the code is open source, someone can always copy out the relevant bits if they want, but sending a clear signal about the packages you intend to support and versioning them is worthwhile IMO. It's freeing to feel safe heavily refactoring internal APIs at any time.

Go does this itself, e.g. https://github.com/golang/go/tree/master/src/cmd/internal

Internal is also pretty handy within any sort of monorepo to isolate portions of the repo. Being able to break up a package into smaller packages is useful for compile times, code organization, etc. Starting out as an internal subtree means you can go ahead and break up this package without committing to any new APIs.

https://golang.org/doc/go1.4#internalpackages

**Comment by spiffxp** [comment]
/reopen
/remove-lifecycle rotten
I think this is still relevant, and a good idea.  That said, the lack of attention means maybe everyone else is happy with the status quo, and prow's entire surface area as public API
