### ISSUE TITLE
Make the sig-windows-gce tests green.

### ISSUE THREAD

**Issue by jeremyje** [kubernetes/test-infra#21260]
**What should be cleaned up or changed**:
Test Grid for sig-windows-gce is fairly red. We are unblocked to move forward with the fixes to clean up the redness since the repo lists have stablized.

**Provide any links for context**:
https://testgrid.k8s.io/sig-windows-gce

**Comment by BenTheElder** [comment]
Usually we track test / job health in https://github.com/kubernetes/kubernetes FWIW (the CI signal team in particular files bugs there / keeps tabs on these).

**Comment by jeremyje** [comment]
They are pretty green at this point so I'm closing this issue.
