### ISSUE TITLE
Extra newlines in jobResultsCache.json

### ISSUE THREAD

**Issue by jbeda** [kubernetes/test-infra#2130]
I'm seeing stuff like this:
```
  {
    "buildnumber": "4950", 
    "job-version": "v1.7.0-alpha.0.284+5c3791b9e01edd\n", 
    "version": "v1.7.0-alpha.0.284+5c3791b9e01edd\n", 
    "result": "SUCCESS", 
    "passed": true
  }, 
```
in `gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gce/jobResultsCache.json`

**Comment by ixdy** [comment]
already fixed by https://github.com/kubernetes/test-infra/pull/2079.

**Comment by ixdy** [comment]
and https://github.com/kubernetes/release/pull/267 should partially work around the issue.

**Comment by jbeda** [comment]
See also the fix in https://github.com/kubernetes/release/pull/271.
