### ISSUE TITLE
Support Multiple Commits for Audit Updates (and other pr-creator based periodic jobs)

### ISSUE THREAD

**Issue by hh** [kubernetes/test-infra#21303]
**What would you like to be added**:

Logic for updating existing PRs created with `pr-creator`

**Why is this needed**:

For jobs like https://github.com/kubernetes/k8s.io/pull/1755#issuecomment-792419733
The pr is created, but any subsequent changes are force pushed, resulting in a single commit without the history over time as the periodic runs again.

Ideally we would check to see if a PR exists, to fetch and check out the branch it is based on, and add a single commit of the changes to the existing PR.

**Comment by hh** [comment]
Current logic:

**Comment by hh** [comment]
Current logic:
https://github.com/kubernetes/test-infra/blob/1061699111447f6f6d2d360d063af5b8e6948d63/config/jobs/kubernetes/wg-k8s-infra/trusted/wg-k8s-infra-trusted.yaml#L54-L88

**Comment by hh** [comment]
Current logic:
https://github.com/kubernetes/test-infra/blob/1061699111447f6f6d2d360d063af5b8e6948d63/config/jobs/kubernetes/wg-k8s-infra/trusted/wg-k8s-infra-trusted.yaml#L54-L88

**Comment by hh** [comment]
/remove-lifecycle rotten
Still useful for audit jobs, just been low priority.

**Comment by spiffxp** [comment]
/sig testing
I'm tempted to close this as out of scope, as I suspect it's up to the script that invokes this to decide what the commits should look like.  The tool you're referencing here is responsible for "should I open or bump a PR", not necessarily "what should be in this PR?"

Will revisit on a pass for prioritization
