### ISSUE TITLE
Prow log errors: Failed to create k8s-tpu-operator pipeline client

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#21317]
**What happened**:

Seeing repeated errors in k8s prow log:

```
jsonPayload: {
func: "main.main"
msg: "Failed to create k8s-tpu-operator pipeline client"
component: "pipeline"
file: "prow/cmd/pipeline/main.go:160"
level: "fatal"
error: "Get "https://35.227.184.110/apis/tekton.dev/v1alpha1/pipelineruns?limit=1": dial tcp 35.227.184.110:443: i/o timeout"
}
resource: {
type: "k8s_container"
labels: {
pod_name: "prow-pipeline-5bb7586468-cccl5"
namespace_name: "default"
project_id: "k8s-prow"
container_name: "pipeline"
location: "us-central1-f"
cluster_name: "prow"
}
```

**Comment by chaodaiG** [comment]
This is actually causing prow-pipeline pod crashlooping:
```
prow-pipeline-5bb7586468-cccl5             0/1     CrashLoopBackOff   253        22h
```

**Comment by chaodaiG** [comment]
The build cluster named `k8s-tpu-operator` isn't reachable to other prow components as well, very likely the cluster was not reachable from prow any more. Pipeline shouldn't crashloop when this happened, #21318 to make it not panic.

Not sure which team owns `k8s-tpu-operator`.

**Comment by cjwagner** [comment]
@yguo0905 Deleted the cluster. I don't see any job config for that cluster so we should probably remove the kubeconfig entry now.

**Comment by chaodaiG** [comment]
> @yguo0905 deleted the cluster. I don't see any job config for that cluster so we should probably remove the kubeconfig entry now.

Done, deleted it from kubeconfig, @yguo0905 please let us know if this is still needed

**Comment by chaodaiG** [comment]
Pipeline stopped crashlooping after this, mark it fixed for now
/close
