### ISSUE TITLE
Add /remove-(approve|lgtm|hold) commands

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#21356]
/remove hold

__Originally posted by @ameukam in https://github.com/kubernetes/k8s.io/pull/1732#issuecomment-797680434__

Made me realize for these labels that while we do have "/foo cancel" as a consistent option, adding support for "/remove-foo" would be more consistent with other labels (priority, sig, lifecycle, area, etc)

/assign @cjwagner @chaodaiG @alvaroaleman 
WDYT? Don't want to tag with /help until we agree it's worth doing

/area prow
/sig testing
/priority backlog
/kind cleanup

**Comment by spiffxp** [comment]
Also FYI @nikhita since you've been looking at /approve lately

**Comment by alvaroaleman** [comment]
From a technical standpoint there are no reasons not to do this. I personally think that its perfectly fine to have all of "/remove $command", "/un$command", "/$command cancel" and that it has the advantage that ppl will in 99% of the cases intuitively use one of those choices even if they didn't know it existed ahead of time.

But I also seem to remember that someone found it important that there is exactly one way to do these things. Maybe @fejta or @cblecker ?

**Comment by fejta** [comment]
We started with `/lgtm cancel`. This did not work with variable commands like `/sig <variable>`. Thus `/remove-sig <variable>`. Having everything support `/remove-command` seems like a reasonable idea, since I see that always makes sense.

I would also support retiring `/lgtm cancel` etc in favor of the more universal `/remove-lgtm` pattern, and doing this for all commands.

I see the main goal here to do something consistently and efficiently. Not the end of the world if we consistently support more than 1 way of invoking a command, but efficiency is easy to implement and support. It also comes with a clear limiting principle.

Without a limiting principle we are likely to forever find reasonable reasons to support N+1 ways of doing the same thing (like this request, for example). This seems like an inefficient use of time and complexity.

**Comment by nikhita** [comment]
I'm good with this. :+1: 

> Without a limiting principle we are likely to forever find reasonable reasons to support N+1 ways of doing the same thing (like this request, for example).

For the limiting principle, we could maybe keep it simple to:
-  `/$command` and `/remove-$command` for all commands.
- `/un$command` and `/$command cancel` only for commands where it makes sense

cc @mrbobbytables

**Comment by mrbobbytables** [comment]
+1 This seems like a pretty reasonable request.

**Comment by spiffxp** [comment]
> I would also support retiring /lgtm cancel etc in favor of the more universal /remove-lgtm pattern, and doing this for all commands.

Maybe someday. For now I feel like too many humans have the other variants baked into muscle-memory. I'd rather respect that, but stop the bot from suggesting them. Stats on usage could inform when to retire, which is a heavier lift for now.

**Comment by nikhita** [comment]
> Don't want to tag with /help until we agree it's worth doing

I see lots of +1s and we've had a slew of new contributors showing up in sig-contribex so I'd like to label this as help-wanted.
/help

If you are a new contributor picking up this issue, here's how you can go about this.

**What needs to be done**:

If a GitHub comment contains (at least one of) the following text on a new line:
  - `/remove-approve` - the `approved` label should be removed
  - `/remove-lgtm` - the `lgtm` label should be removed
  - `/remove-hold` - the `do-not-merge/hold` label should be removed

**Background**:

- Each such slash command (like `/lgtm`, `/approve` and `/hold`) are written as [plugins](https://github.com/kubernetes/test-infra/tree/master/prow/plugins) in prow. If you look at the code for the [lgtm](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/lgtm), [approve](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/approve) and [hold](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/hold) plugins, you'll notice that they follow a similar pattern.
- The list of all such slash commands and their usage can be found at https://prow.k8s.io/command-help
- The commands for each plugin to get triggered on are defined as a regular expressions - https://github.com/kubernetes/test-infra/blob/e9bafa1cc6be4c8fae4046cef5aeccaa28b3a648/prow/plugins/hold/hold.go#L43
- To ensure that the `lgtm`, `approve` and `hold` plugins get triggered on the `/remove-*` pattern, these regular expressions need to be updated.

**Changes to make**:

The following steps walkthrough the `hold` plugin. Make similar changes to the `lgtm` and `approve` plugins too.

- Update the regular expression for the command: 
https://github.com/kubernetes/test-infra/blob/e9bafa1cc6be4c8fae4046cef5aeccaa28b3a648/prow/plugins/hold/hold.go#L43

- Update the help text:
https://github.com/kubernetes/test-infra/blob/e9bafa1cc6be4c8fae4046cef5aeccaa28b3a648/prow/plugins/hold/hold.go#L57-L63

- Add tests for the `/remove-hold` command in https://github.com/kubernetes/test-infra/blob/master/prow/plugins/hold/hold_test.go

If you have any questions or need help, feel free to ping me on the _#sig-testing_ channel on slack.

**Comment by MadhavJivrajani** [comment]
Hi! I'd like to take this up if possible :smile:

**Comment by spiffxp** [comment]
/unassign @cjwagner @alvaroaleman @fejta 
Thanks for the input!
