### ISSUE TITLE
Support Full Set of Repository Permissions in Peribolos

### ISSUE THREAD

**Issue by brian-avery** [kubernetes/test-infra#21380]
**What would you like to be added**:

Kubernetes currently only supports a limited permission set of GitHub repository permissions (admin/read/write/none vs read/triage/write/maintain/admin). According to https://github.blog/2019-10-03-delegate-responsibilities-with-expanded-repository-permissions/, the more fine grained read/triage/write/maintain/admin should have been available to repositories October 3, 2019. I can also see this reflected in the manual configuration available via the GitHub website. 

I found https://github.com/kubernetes/test-infra/issues/14325, which did some investigation, but that went stale. In that issue, the problem seemed to be that Peribolos didn't support the GitHub v4 API at that point, but the Peribolos documentation says it supports it now.  Also, the GitHub documentation doesn't seem to indicate that these permission levels are limited to v4 anymore.

 Revisiting the permission levels to see if this is something that would now be considered. Happy to do the work myself, but I wanted to see if there was any feedback before I went ahead. Thanks!

**Why is this needed**:

I would like to be able to take advantage of the `triage` user level in my Peribolos configuration.

**Comment by brian-avery** [comment]
Looking at https://github.com/kubernetes/test-infra/blob/a675586d4b45d86181bb31f8c196540daa15c26e/prow/github/client.go#L3331, this now returns separates triager and maintainer: 

```
    "permissions": {
            "pull": false,
            "triage": true,
            "push": false,
            "maintain": false,
            "admin": false
        }
```

**Comment by MadhavJivrajani** [comment]
Hey! I'd like to work on this if possible :smile:

**Comment by brian-avery** [comment]
Thanks @MadhavJivrajani :)
