### ISSUE TITLE
Plugin-help cannot be served when plugins are enabled for organizations with many repos.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#21426]
**What happened**:
Generating plugin-help information currently requires listing all repos in organizations that have plugins configured in order to allow complete plugin-help information to be generated for every repo. This is problematic when organizations have huge numbers of repos which may be the case if plugins are configured for such an org, but webhooks are only enabled for some repos in the org. For example, the https://oss-prow.knative.dev instance serves repos in the `GoogleCloudPlatform` and `google` organizations.

**What you expected to happen**:
Plugin help to be served even if plugins are configured for a large organization.

**How to reproduce it (as minimally and precisely as possible)**:
Configure plugins for a large GitHub organization (with or without setting up webhooks) and try to access plugin help via the `/plugins` or `/command-help` Deck paths.

**Please provide links to example occurrences, if any**:
https://oss-prow.knative.dev/plugins

**Anything else we need to know?**:
The original issue is here and has more details: https://github.com/GoogleCloudPlatform/oss-test-infra/issues/362

**Comment by petr-muller** [comment]
/remove-lifecycle stale

We still suffer from this :(
