### ISSUE TITLE
Per-Provider Post-Up Setup

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#2143]
In the `kops` testing, we're currently disabling NodePort testing, c.f. https://github.com/kubernetes/kops/issues/775 . I just added the `-slow` tests as well, and there's more of these issue. Essentially, all of the providers do some tiny amount of post-deployment setup to "ready" the cluster for e2e testing, but because `kops` is outside the normal `kube-up` framework, all `kops` deployments are as a customer would have them.

I see a couple of options here:
1. We add a function in the `kubetest` kops deployment that handles the post-deployment configuration. This could call a kops function, but likely as not, we'd just thunk out to the AWS CLI, or pull in the AWS SDK to kubetest (yay?).
1. We find a better way to test these things that would actually work in an as-deployed environment
1. We tag anything that needs special cluster setup and filter the tag out for `kops` testing. This has obvious coverage issues, but lets us filter the tag without specially calling out NodePort.

Thoughts from @kubernetes/sig-testing-misc?

**Comment by zmerlynn** [comment]
cc @justinsb

**Comment by spiffxp** [comment]
In the abstract, post-up seems like a valid hook.  But I question why this wouldn't just be a modification to the existing deployer's "up"

I am firm believer that `e2e.go -test` should "just work" without any additional configuration save for credentials, at least for conformance tests, so as to support the testing of clusters deployed with tools other than `kube-up/kops/kube-anywhere`

**Comment by zmerlynn** [comment]
@spiffxp: Then you're seemingly opting for (2) above, which is to say "tests should work on the default setup"?

**Comment by zmerlynn** [comment]
To be fair, this is my general desire as well - and I believe everything tagged with `[Conformance]` actually obeys this. I'd almost rather flip this on its head and first implement (3) with a `[SpecialSetup]` tag, then rewrite the tests if possible (i.e. (3) then (2)).

**Comment by spiffxp** [comment]
Yeah, I guess I'm opting for 2.  Or asking that we find a better way than `[TestTags:ParsedViaRegex]` to classify these things.

Varying levels of fidelity here:
- allow tests to introspect cluster for its capabilities, and test appropriately?
- allow tests to compare the cluster's cloud provider against a hardcoded list of capabilities? (this seems roughly where we're at re: tests that require ssh)
- same as above but s/cloud-provider/e2e-deployer so it's passed vs. introspected
- create a general purpose tag that indicate non-conformant/non-standard setup (we tried using `Feature:` for this, it's grown past this scope now)
- *mumbles something about feature flags*

I'm open to whatever solves `kops`'s immediate need, just pointing out it's not unique.

**Comment by zmerlynn** [comment]
Heh, c.f. https://github.com/kubernetes/kubernetes/issues/2953 .. which we haven't implemented.

**Comment by bgrant0607** [comment]
FWIW, I made some comments about feature flags in the layers doc:
https://docs.google.com/document/d/1XkjVm4bOeiVkj-Xt1LgoGiqWsBfNozJ51dyI-ljzt1o/edit#

**Comment by fejta** [comment]
/assign @zmerlynn 

I believe you added this logic to kubetest? Can we close if so?
