### ISSUE TITLE
@io_k8s_repo_infra//hack:update-deps breaks go.sum if the local Go version is too old

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#21463]
**What happened**:
Running "update-deps" with an out-of-date local Go version breaks go.sum.

**What you expected to happen**:
Bazel should use the version of go specified in the workspace configuration. The local version of Go shouldn't leak into the tests.

**How to reproduce it (as minimally and precisely as possible)**:
```
gvm use go1.13.2
git checkout master
bazel run @io_k8s_repo_infra//hack:update-deps
bazel test @io_k8s_repo_infra//hack:verify-deps
```

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/21400/pull-test-infra-bazel/1372991937589547008

**Anything else we need to know?**:
The diff (shown in the log above) contains many lines in go.sum of rewrites of this form:
```
-cloud.google.com/go/logging v1.0.0 h1:kaunpnoEh9L4hu6JUsBa8Y20LBfKnCuDhKUgdZp7oK8=
 cloud.google.com/go/logging v1.0.0/go.mod h1:V1cc3ogwobYzQq5f2R7DS/GvRIrI4FKj01Gs5glwAls=
```

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/assign @fejta 
Please close or find someone more suitable to assign bazel-related issues

**Comment by fejta** [comment]
This is intended behavior: https://github.com/bazelbuild/rules_go#initial-project-setup
