### ISSUE TITLE
The failure caused by the newly added tests might be skipped

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/test-infra#2148]
While looking into https://github.com/kubernetes/kubernetes/issues/42597, I found surprisely while the test failed, but testgrid still reports it passed:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/5097

Looks like it might be the regression caused by https://github.com/kubernetes/test-infra/pull/2142

**Comment by ixdy** [comment]
I think that might be intentional - we re-run tests if they fail, and only fail the run if they fail every time, rather than flaking once.

**Comment by ixdy** [comment]
https://github.com/kubernetes/kubernetes/blob/aa454ec740ed8985df2a07d2966c69e8adcc023b/hack/ginkgo-e2e.sh#L33-L34

Some jobs (e.g. `ci-kubernetes-e2e-kops-aws` set `GINKGO_TOLERATE_FLAKES=y`).
