### ISSUE TITLE
ci-kubernetes-e2e-windows-gce-2019 and ci-kubernetes-e2e-windows-gce-2004 failing outside of test results

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/test-infra#21491]
**What happened**:
These two jobs on TestGrid are marked as "failing" even when it seems their tests are all green.

**What you expected to happen**:
When the run is green, I expect the job to be marked as passing.

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2004-master
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-master

**Anything else we need to know?**:

/sig windows

**Comment by BenTheElder** [comment]
They're actually failing. The ones without any failing test results failed the job overall because they timed out before completing. You can see this clicking through to the run results and expanding the logs.
