### ISSUE TITLE
Some PRs from dependabot contain GitHub keywords in commit message

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/test-infra#21534]
**What would you like to be added**:
Can we exclude `do-not-merge/invalid-commit-message` check for PRs from dependabot?

**Why is this needed**:
AngularJS and some packages has `@` in its name.
So their PRs for update such packages are labeled as `do-not-merge/invalid-commit-message`.

https://github.com/kubernetes/dashboard/pull/5929
https://github.com/kubernetes/dashboard/commit/8d90e140fc1343182dda7c7b5985239fcb763d7b

**Comment by BenTheElder** [comment]
We don't allow these commits for a reason ... However I don't think the matching is correct here, while e.g.
`@kubernetes/sig-apps-misc` is a valid in-org team reference (if unquoted in this comment it will ping the team, not sure about in commits though) which is similar to `@angular/platform-browser` I don't think github supports these in commits.

If github doesn't support team mentions in commits, we can update the check to allow the case of ~team mention (contains `/`) versus a user mention. It doesn't appear to be doing so there but we should experiment with an in-org mention in a test somewhere.

Reason: see e.g. discussion here https://github.com/python/miss-islington/issues/270

**Comment by BenTheElder** [comment]
If we were to make an exception rather than (potentially, once verified) more accurate matching, this would require approval from SIG Contributor Experience as a workflow change.

**Comment by shu-mutou** [comment]
@BenTheElder Thank you for your explanations!!

I'm not sure why no mentions to myself were sent from above PR comments, but no mentions were sent by commit messages in that PR.

**Comment by shu-mutou** [comment]
dependabot may assume only user mention, and not take into account teams.
https://github.com/dependabot/dependabot-core/issues/3378#issuecomment-809326939

They would fix this issue.

**Comment by shu-mutou** [comment]
BTW, dependabot replaces `@user` to `@<U+200B>user`, i.e. inserts ZERO WIDTH SPACE. ZERO WIDTH SPACE is acceptable for us?
https://github.com/dependabot/dependabot-core/blob/e7c1929d7f850f8516311cc41753958cb6b980d2/common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb#L140

**Comment by shu-mutou** [comment]
BTW, dependabot replaces `@user` to `@<U+200B>user`, i.e. inserts ZERO WIDTH SPACE. ZERO WIDTH SPACE is acceptable for us?
https://github.com/dependabot/dependabot-core/blob/e7c1929d7f850f8516311cc41753958cb6b980d2/common/lib/dependabot/pull_request_creator/message_builder/link_and_mention_sanitizer.rb#L140

**Comment by BenTheElder** [comment]
Thanks for looking into this more!
That's a fun approach on their end, I think we are similarly just trying to prevent mentions, so we can update the bot to recognize real mentions vs these.

**Comment by BenTheElder** [comment]
I think we should update prow to understand that `@<U+200B>` is OK, and then let https://github.com/dependabot/dependabot-core/issues/3378#issuecomment-809326939 track fixing the teams bit on the dependabot side.

/help
/good-first-issue

this is a pretty simple PR, https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/prow/plugins/invalidcommitmsg/invalidcommitmsg.go#L66

+ add some test cases to cover this in https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/prow/plugins/invalidcommitmsg/invalidcommitmsg_test.go

**Comment by bhumijgupta** [comment]
@BenTheElder I would like to pick this up

**Comment by BenTheElder** [comment]
please do! we are in #sig-testing and #prow of the kubernetes slack if you have any questions :-)

**Comment by bhumijgupta** [comment]
Thanks.
/assign @bhumijgupta

**Comment by bhumijgupta** [comment]
> I think we should update prow to understand that @<U+200B> is OK

@BenTheElder @shu-mutou https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/prow/plugins/invalidcommitmsg/invalidcommitmsg.go#L66
 The above regex should not match for mentions with `@\u200b` as tested in this [golang playground](https://play.golang.org/p/LHRxyz5KuBB).

I can add a test at https://github.com/kubernetes/test-infra/blob/1f3edddfe487b7df5714dbd9de3b2ed6e691485e/prow/plugins/invalidcommitmsg/invalidcommitmsg_test.go#L98-L107 to make sure that it remains the same

**Comment by BenTheElder** [comment]
Sounds good, thank you!

**Comment by shu-mutou** [comment]
Since it is unlikely that dependabot will fix this issue, I thought about rewriting the commit message with github action etc.
But if we rewrite the PR from dependabot, dependabot will not automatically rebase it.
After all, PR from dependabot needs to be excluded from the InvalidCommitMessage check, I think.
Thanks!

**Comment by BenTheElder** [comment]
I don't know that we want to special case an account like this, I think that's something Prow is unlikely to want to deal with and sort of feels wrong.

Especially if dependabot actually manages to mention a team or user. When something like this merges in Kubernetes then it gets merged into forks and every fork merge notifies those affected. I just received another wave of these last night from commits that predate the community enacting this measure.
