### ISSUE TITLE
Add a prefix in front of the title of PR created by autobump

### ISSUE THREAD

**Issue by Mini256** [kubernetes/test-infra#21540]
❤️ Thank you for noticing this issue.

**What would you like to be added**:

Add a prefix in front of the title of PR created by `autobump` , for example: `build: Bump prow from v20210323-4a95c1446c to v20210325-ad0e6d1480`, and allow users to configure it through environment variables.

https://github.com/kubernetes/test-infra/blob/17edd25671538ee0df8f730af734dee889991efa/prow/cmd/autobump/autobump.sh#L62

**Why is this needed**:

When I use `autobump` to update my Prow instance, `autobump` will submit a PR with a title like `Bump prow from v20210323-4a95c1446c to v20210325-ad0e6d1480`, which cannot pass the check of `Semantic Pull Request` action.

**Comment by BenTheElder** [comment]
Changing the format would break our searches for these and we don't use semantic titles ourselves, but if you made it optional in such a way that it didn't change the title for our usage I think this would be accepted.

Something like this would do nothing when not set:
`"${AUTOBUMP_TITLE_PREFIX:+"${AUTOBUMP_TITLE_PREFIX} "}Bump .."`
