### ISSUE TITLE
pod-utils: dependent environment variables break JSON encoding

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#21541]
When we run the `entrypoint` and `sidecar`, we pass them the command and arguments from the user's container spec in the job configuration. If a user is using k8s environment variable dependencies or interpolation in the arguments for their container, the `$(varname)` form will exist in the `$ENTRYPOINT_OPTIONS` variable in the decorated Pod that we POST to the API. Kubernetes will then interpolate the `$(varname)` form inside of the environment variable value, and it's possible for the resulting interpolated string to no longer be valid JSON. [Here](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1375153882254020608/prowjob.json) is a repoducer.

/cc @alvaroaleman @cjwagner 
/area prow/pod-utils
/area prow/pod-utils/entrypoint

I'm not entirely sure how to handle this.

**Comment by alvaroaleman** [comment]
In theory we could add a validation that generates a job pod, iterates the env vars for those containers and fails when `ENTRYPOINT_OPTIONS` contains a `$(iterated-env-var)` substring. Seems a bit complicated though.

**Comment by stevekuznetsov** [comment]
It also doesn't fail in *all* cases - many, many jobs are using such variables that expand inside of `$ENTRYPOINT_OPTIONS` without breaking the JSON serialization.
