### ISSUE TITLE
How difficult would it be to use patch release milestones

### ISSUE THREAD

**Issue by calebamiles** [kubernetes/test-infra#2154]
I think it would be nice to begin to depreciate the [`next-candidate`](https://github.com/kubernetes/kubernetes/milestone/17) milestone which seems to also serve as a graveyard for forgotten issues. Given that the current tooling for creating patch releases is still keyed off of the minor release branch and uses cherry pick labels to move PRs into patch releases I am wondering how much work would be involved in using granular patch release milestones rather than the previous minor release milestone.

**Comment by fejta** [comment]
Maybe file this in the release repo if you still want it?
