### ISSUE TITLE
prow: override: use test names, not status contexts

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#21556]
Today, users interact with Prow jobs by using `/test <name>`. However, administrators must use `/override <context>` even when the context is not the test name. We should allow `/override` to use test names as that's what users are familiar with.

/cc @bparees 

WDYT @cjwagner @chaodaiG @alvaroaleman ?

**Comment by alvaroaleman** [comment]
This is pretty much an openshift-exclusive problem, because for everyone else these two are the same

**Comment by alvaroaleman** [comment]
One issue with using the test name is that we might not know what context it belongs to when its different from the context

**Comment by stevekuznetsov** [comment]
There is nothing in Prow itself that requires that  the two be the same, so it's a Prow generic problem. We know exactly what the name (er, the part of the regex used in `/test`) is, so we should be able to definitively map from that to the context, no?

**Comment by alvaroaleman** [comment]
Not always, the job might not exist anymore for example

**Comment by stevekuznetsov** [comment]
Do we allow `/override` for contexts we don't know we own today? Seems like a bug TBH

**Comment by stevekuznetsov** [comment]
Turns out no, we [don't](https://github.com/kubernetes/test-infra/pull/21557#issuecomment-809533615) - so there is no gap there.

**Comment by alvaroaleman** [comment]
> Turns out no, we don't - so there is no gap there.

It was only refused because that status was a success already. But yeah you are right, we do require the job to exist: https://github.com/kubernetes/test-infra/blob/b5982ab9e3e2cdd0546573401cd96da671adb392/prow/plugins/override/override.go#L385

**Comment by cjwagner** [comment]
> > Turns out no, we don't - so there is no gap there.
> 
> It was only refused because that status was a success already. But yeah you are right, we do require the job to exist:
> 
> https://github.com/kubernetes/test-infra/blob/b5982ab9e3e2cdd0546573401cd96da671adb392/prow/plugins/override/override.go#L385

We __do not__ require the job to exist. We just don't create a ProwJob if we can't find one with that status context. The status context on GitHub is overwritten either way.

**Comment by YuviGold** [comment]
Multiple times I mistakenly hit one convention instead of the other convention for both of the commands.
Could both of the commands support both ways? Full name and the short name.

[override reference](https://github.com/openshift/assisted-service/pull/1454#issuecomment-813989940)
[test refference](https://github.com/openshift/assisted-service/pull/1454#issuecomment-813990800)

**Comment by stevekuznetsov** [comment]
Ok so overall ... we expect users to use `/override` for contexts that Prow owns, no? Users interact with contexts via the names they use `/test` with. In the prow.k8s.io case, these are also the context names, but nothing in Prow requires that to be the case. If we ask users to write test names, it should always be correct unless we really care about the case where users use `/override` to touch contexts that Prow did not create?

**Comment by cjwagner** [comment]
> unless we really care about the case where users use `/override` to touch contexts that Prow did not create

That case does come up occasionally and it useful to have `override` to handle it, but I agree with everything said here. Could we make the change you are describing, but continue to support the old behavior by supporting both of the following commands?
- `/override <job-name>`
-  `/override-context <context-name>`

**Comment by alvaroaleman** [comment]
Do we need distinct commands? We could maybe check if a failed context `context-name` exists, if yes, override it. If not but a job with the name exists, override the job. Otherwise we will break this for users that are used to the current behavior

**Comment by stevekuznetsov** [comment]
I'm happy to continue supporting the old behavior, so

```
/override <token>
```

Will search:

1. job names
2. contexts on the PR

This is only available to root approvers on the repo so I can't see a downside to letting them strong-arm a context Prow does not own (kind of weird our token has the power to change those tbh)

**Comment by YuviGold** [comment]
I would like to pick this up
/assign
