### ISSUE TITLE
retest command doesn't re-run failed github actions

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/test-infra#21581]
**What would you like to be added**:

`/retest` kicks off failed GitHub actions that appear in the PR checks 

**Why is this needed**:

I think Github ACLs are a bit wonky and sometimes PR authors can't re-trigger these failed workflows (unless they push fake commits). Or other times I'd like to re-run the actions and cannot.

**Comment by stevekuznetsov** [comment]
Prow doesn't own the actions, this seems like it could be surprising for users.

**Comment by petr-muller** [comment]
I think `/retest` caring only about Prowjobs is a relict from before actions when the "other" checks were coming from other CI systems like Travis CI when there was no API to retrigger such external jobs. With GH actions, I think it may be reasonable for `/retest` to trigger them too b/c the interface is clear and Prow can be reasonably expected to interact with GH on behalf of the user, I guess?

I'm slightly worried about making the UX consistent thought, I think we'd need to think about extending `/test` to trigger GH actions too, it would be surprising if the commands had different capabilities.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/20713

**Comment by shinigambit** [comment]
Is this expected to change the behavior of the trigger plugin or is it a new plugin specialized in triggering Github actions?

**Comment by dprotaso** [comment]
@shinigambit should this issue be closed now that the PR has merged?

**Comment by shinigambit** [comment]
@dprotaso I think in the general case yes, but it still needs to be enabled via plugin configuration, I can do just that for Knative

**Comment by dprotaso** [comment]
sweet - I'll make a downstream issue
/close

**Comment by chaodaiG** [comment]
@shinigambit , thank you for the contribution! Now that it's live, would you mind also update https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md to reflect this new feature?
