### ISSUE TITLE
Prow reports results across PRs

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/test-infra#21606]
**What happened**:

- The PR https://github.com/kubernetes/kubernetes/pull/100717 was a cherry-pick targeting the master branch, which got not merged.
- The PR https://github.com/kubernetes/kubernetes/pull/100718 got created directly afterwards, pointing to the correct `release-1.21` branch.

Now prow reports the failing tests from #100717 to the newly created PR #100718, for example this run:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100717/pull-kubernetes-unit/1377302568320897024

This forces us to override the context of those tests, otherwise we would not be able to merge.

**What you expected to happen**:

Prow should not report the failing tests from the closed PRs to the new one.

**How to reproduce it (as minimally and precisely as possible)**:

I think @dims can provide more input here, but I guess creating two cherry-picks in order (where the first one targets `master` and gets closed after triggering the tests) should cause the issue.

**Please provide links to example occurrences, if any**:

n/a

**Anything else we need to know?**:

n/a

**Comment by alvaroaleman** [comment]
That is not a bug, that is how the github api works. Github statues are scoped to a commit sha and both these PRs have the same head commit sha, so the status appears on both of them. Even we cleared it again, we would clear it on both, there isn't really anything that can be done about this.

**Comment by BenTheElder** [comment]
We also need to be running these tests on this branch, the test config needs to be properly forked on setting up the release branch. Seems we have some issues with that still.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/21633

**Comment by BenTheElder** [comment]
(prow is WAI, see above, job config tracked in the new issue linked above)
