### ISSUE TITLE
Windows jobs on master/1.21-informing are timing out

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/test-infra#21615]
**What happened**:
ci-kubernetes-e2e-windows-gce-2004
ci-kubernetes-e2e-windows-gce-2019
ci-kubernetes-e2e-windows-gce-20h2
ci-kubernetes-e2e-windows-gce-2004-1-21
ci-kubernetes-e2e-windows-gce-2019-1-21
ci-kubernetes-e2e-windows-gce-20h2-1-21

are all timing out. On the master side, they are timing out at 3h (recently bumped from 2h on this PR: https://github.com/kubernetes/test-infra/pull/21584); on the 1.21 side, they are timing out at 2h.

**What you expected to happen**:
I suspect that these jobs should not be taking this long to run, as similar jobs from 1.20 and 1.19 take less than half the time.

For example, these take ~1h30m to run:
- [ci-kubernetes-e2e-windows-gce-2019-1-20](https://testgrid.k8s.io/sig-release-1.20-informing#gce-windows-2019-1.20)
  - this run took 1h20m: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019-1-20/1377214071648030720
- [ci-kubernetes-e2e-windows-gce-2019-1-19](https://testgrid.k8s.io/sig-release-1.19-informing#gce-windows-2019-1.19)
  - this run took 1h14m: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019-1-19/1377663123665719296

If the jobs on master and 1.21 _are_ supposed to be taking this long to run, perhaps we should just keep bumping the timeout. But the fact that they take so much longer than the 1.20 and 1.19 jobs seems rather suspicious.

**Please provide links to example occurrences, if any**:
Here's one example from each job I listed as timing out:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1377600712464142336
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019/1377544085862092800
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1377582841705009152
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004-1-21/1377614550152515584
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019-1-21/1377614550123155456
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2-1-21/1377614550139932672

**Anything else we need to know?**:
Slack thread where this was brought up: https://kubernetes.slack.com/archives/C0SJ4AFB7/p1617134401088100

/sig windows
/cc @spiffxp 
(thank you for offering to help out!)

**Comment by pjh** [comment]
Thanks Joyce. https://github.com/kubernetes/test-infra/pull/21642 may help reduce the duration of these test jobs, but we still need to look into why the 1.21 jobs are taking longer than the 1.20 jobs.

**Comment by thejoycekung** [comment]
@pjh It looks like #21640 helped a bit -- all the tests actually finish within 3h now but the job is having trouble cleaning up/exiting? Looks like it hits the 3h15m timeout (the extra "grace period") while exiting.

Examples:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1379177283335491584#1:build-log.txt:17736
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1379159414811922432#1:build-log.txt:17516

**Comment by dims** [comment]
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2004-master and https://testgrid.k8s.io/sig-release-master-informing#gce-windows-20h2-master are both under an hour and half (latest run). no?

**Comment by thejoycekung** [comment]
@dims yeah, you're right. I don't know what happened but between these two runs the runtime seemed to be halved ...? The first one ran at 5PM EDT which was after #21640 merged, so it was already skipping the Slow tests too.

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1379177283335491584
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1379237933680168960

...

oh, actually I see the problem. That PR about Device Plugin merged during that time period -- you can see the test takes 2h on this run 😅 : https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1379159414811922432

**Comment by dims** [comment]
@thejoycekung yep :) thanks to @claudiubelu

**Comment by claudiubelu** [comment]
I've also sent a PR here: https://github.com/kubernetes/test-infra/pull/21785

The issue has already been addressed on master, the test has been tagged with ``[Feature:GPUDevicePlugin]``, and most tests are already skipping Feature tests, but that's not the case for 1.21. The PR above addresses this issue.
