### ISSUE TITLE
1.21 release branch is missing presubmits

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#21633]
https://github.com/kubernetes/test-infra/issues/21606#issuecomment-812094062

sorry I don't have time to dig into this, I need to wrap up some other things and then I'm OOO for a week, but I want to make sure this is tracked.

/sig release
/area jobs
/priority critical-urgent

**Comment by justaugustus** [comment]
@kubernetes/release-managers -- Someone please volunteer to investigate, assign yourself, and treat this as your highest (SIG Release) priority this week.

**Comment by cpanato** [comment]
I will work on that
/assign

**Comment by cpanato** [comment]
jobs are running now 
see a PR for example: https://github.com/kubernetes/kubernetes/pull/101385

**Comment by cpanato** [comment]
i guess we can close it now, if it is missing more jobs we can reopen or create a new issue
/close

**Comment by puerco** [comment]
Awesome job, thanks @cpanato  :D :tada:

**Comment by BenTheElder** [comment]
thank you!!
