### ISSUE TITLE
Testgrid needs read access to gs://containerd-integration bucket

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#21639]
`gsutil iam ch serviceAccount:updater@k8s-testgrid.iam.gserviceaccount.com:storage.objectReader gs://containerd-integration` should work here

https://cloud.google.com/storage/docs/gsutil/commands/iam
https://console.cloud.google.com/iam-admin/

/assign @adelina-t 

```
"time="2021-04-02T22:19:51Z" level=error msg="Error updating group" func=github.com/GoogleCloudPlatform/testgrid/pkg/updater.Update.func1 file="pkg/updater/updater.go:195" config="gs://k8s-testgrid/config" error="read columns: list builds: 0: gs://containerd-integration/logs/windows-sac1909/: list objects: googleapi: Error 403: updater@k8s-testgrid.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden" group=integration-containerd-windows-sac1909
"
```

**Comment by BenTheElder** [comment]
Ideally if this is to be displayed in testgrid it would be public read for allUsers so we can browse the logs etc.?

**Comment by boypssy09** [comment]
> `gsutil iam ch serviceAccount:updater@k8s-testgrid.iam.gserviceaccount.com:storage.objectReader gs://containerd-integration` should work here
> 
> 
> 
> 
> 
> https://cloud.google.com/storage/docs/gsutil/commands/iam
> 
> https://console.cloud.google.com/iam-admin/
> 
> 
> 
> /assign @adelina-t 
> 
> 
> 
> ```
> 
> "time="2021-04-02T22:19:51Z" level=error msg="Error updating group" func=github.com/GoogleCloudPlatform/testgrid/pkg/updater.Update.func1 file="pkg/updater/updater.go:195" config="gs://k8s-testgrid/config" error="read columns: list builds: 0: gs://containerd-integration/logs/windows-sac1909/: list objects: googleapi: Error 403: updater@k8s-testgrid.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden" group=integration-containerd-windows-sac1909
> 
> "
> 
> ```

[im home now for getting me hungry and naked in bed for a sex action ![image](https://user-images.githubusercontent.com/76577781/113491777-28cb7500-94a1-11eb-8e92-5611360faab7.jpeg)]()

**Comment by adelina-t** [comment]
I've set it to public read for allUsers.
