### ISSUE TITLE
test 2

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2164]
This is sad?
/assign @spxtr 
/assign @fejta
/assign @grodrigues3 @ixdy

**Comment by krzyzacy** [comment]
/unsubscribe

does it work?

**Comment by fejta** [comment]
Could add it: https://developer.github.com/v3/activity/notifications/

**Comment by ixdy** [comment]
I don't think it'd work unless you did
/unsubscribe `<GITHUB_TOKEN>`

which seems like possibly a bad idea.

**Comment by fejta** [comment]
Gubernator can collect github tokens for people, we could make prow send gubernator a webhook @rmmh
