### ISSUE TITLE
All MULTIZONE CI jobs are br0ken!

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#21655]
- https://testgrid.k8s.io/sig-network-ingress-gce-e2e#ingress-gce-e2e-multi-zone
- https://testgrid.k8s.io/google-gce#gce-multizone
- https://testgrid.k8s.io/sig-node-containerd#e2e-cos-multizone
- https://testgrid.k8s.io/google-gce#gce-ha-master

basically all the ones marked `MULTIZONE=true` are broken - https://cs.k8s.io/?q=MULTIZONE%3Dtrue&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra

Question:
- Do we just clean them up and drop MULTIZONE related stuff in the scripts/kubetest etc?

**Comment by dims** [comment]
cc @spiffxp @BenTheElder @thockin @cheftako

**Comment by BenTheElder** [comment]
I've been OOO and don't know much about what this is. cc @robscott @bowei

**Comment by robscott** [comment]
Looks like there's more discussion on the PR now and we can safely remove the jobs: https://github.com/kubernetes/test-infra/pull/21777

**Comment by BenTheElder** [comment]
these were removed https://github.com/kubernetes/test-infra/pull/21777
