### ISSUE TITLE
Prow alertmanager config defined with alertmanagerconfig CR

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#21665]
**What would you like to be added**:

https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md#alertmanagerconfig-resource

**Why is this needed**:

Prow alertmanager config is currently defined as plain text in a Secret as https://github.com/kubernetes/test-infra/blob/57ec97633d831fef328116fe3b3592a62f2d54d3/config/prow/cluster/monitoring/alertmanager-prow_secret.yaml, this is suboptimal as there are secret values in this plain text which cannot be source controlled, which makes the deployment of this config manual. This process is tedious and error prone.

To make our lives easier, we should use alertmanagerconfig CR, which can reference the secret value from in cluster secret, and thus making it possible to automatically deploy the entire monitoring stack

**Comment by chaodaiG** [comment]
cc @cjwagner

**Comment by spiffxp** [comment]
/sig testing
/remove-lifecycle rotten
@chaodaiG I think you're now working on a solution that doesn't use alertmanager? We should probably close this if so

**Comment by chaodaiG** [comment]
yes, this is obsolete now
/close
