### ISSUE TITLE
[Kettle] Failing to encode error ascii

### ISSUE THREAD

**Issue by MushuEE** [kubernetes/test-infra#21674]
**What happened**:
We are now catching the `<p>Your client has issued a malformed or illegal request.  <ins>That\u2019s all we know.</ins>` error however Kettle hits an alternate error when trying to encode this issue to report and skip.

```
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That\u2019s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That\u2019s all we know.</ins>
```
Causes `UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 1671: ordinal not in range(128)` 

/area kettle
/assign

**Comment by spiffxp** [comment]
/sig testing
It's not clear to me whether we're still seeing this
