### ISSUE TITLE
Grafana dashboard doesn't show github token usage on v4 api

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#21681]
**What happened**:

As pointed out by Alvaro in https://github.com/kubernetes/test-infra/pull/21661, that
https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1&refresh=1m doesn't show v4 api usage

**What you expected to happen**:

grafana dashboard should show the usage to help debugging

/area prow

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/sig testing
/area ghproxy
is this still relevant with a move away from grafana? AIUI this is more about what metrics get exposed by ghproxy
