### ISSUE TITLE
Test failures aggregated across different suites

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#2169]
I find http://storage.googleapis.com/kubernetes-test-history/static/index.html very useful.
However, it would be nice to also be able to search/list by test names, and have the test failures show up.

For example:

```
+---------------------------+---------------------------------------------+
|                           |                                             |
|                           |                                             |
|  StatefulSet foo test     |  ci-kubernetes-e2e-gce-statefulset (10/50 fail)
|                           |  ci|gci-gke-serial (10/12 fail)             |
|                           |  ci-something (0/100 fail)                  |
|                           |                                             |
|  StatefulSet bar test     |  ci-kubernetes-e2e-gce-statefulset (1/5 fail)
|                           |  ci-release-1.5 (20/50 fail)                |
|                           |                                             |
+---------------------------+---------------------------------------------+

```

While we're at it, a short URL for http://storage.googleapis.com/kubernetes-test-history/static/index.html would be awesome too :)

cc @fejta @spxtr @rmmh

**Comment by krzyzacy** [comment]
in the [triage dashboard](https://storage.googleapis.com/k8s-gubernator/triage/index.html) it will show a test failure across different jobs:

For instance
```
1349 [k8s.io] StatefulSet [k8s.io] Deploy clustered applications [Feature:StatefulSet] [Slow] should creating a working mysql cluster ▼
    477 ci-kubernetes-e2e-non-cri-gce-statefulset ►
    451 ci-kubernetes-e2e-gci-gce-statefulset ►
    421 ci-kubernetes-e2e-gce-statefulset ►
```

is this the same thing you are asking for?

**Comment by foxish** [comment]
Yes, that is very close to what I was looking for. Thanks. We should have short links and better discoverability for these. I don't think a lot of people know of its existence.

**Comment by krzyzacy** [comment]
This is fairly new, we will advertise the new goodies :-)

**Comment by ixdy** [comment]
Short links exist: https://go.k8s.io/test-history and https://go.k8s.io/triage

But agree that they need better visibility.

**Comment by foxish** [comment]
Closing. Thanks @fejta for making the announcement!
