### ISSUE TITLE
ci-kubernetes-e2e-windows-containerd-gce* is not really testing containerd

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#21710]
https://github.com/kubernetes/test-infra/pull/21705 surfaces the issue 

/assign @ibabou 
cc @Random-Liu @marosset

**Comment by ibabou** [comment]
@dims I'll be sending a fix for the containerd installation. Setting a pipeline to have it retrieve the tar through another GKE bucket.

**Comment by dims** [comment]
@ibabou how is this new GKE bucket updated? is this a CI job in containerd project? 

I am ok to doing something quick for now, but i would like to ensure that all the bits are visible and in the hands of the community

cc @mikebrow @SergeyKanzhelev @Random-Liu @marosset

**Comment by ibabou** [comment]
> @ibabou how is this new GKE bucket updated? is this a CI job in containerd project?
> 
> I am ok to doing something quick for now, but i would like to ensure that all the bits are visible and in the hands of the community
> 
> cc @mikebrow @SergeyKanzhelev @Random-Liu @marosset

@dims, I sent a PR with an update to temporary pull the tar from github directly. Sorry haven't able to get to this early morning!

I was planning to have it kept similar to other add-ons, under gke-release bucket (or a similar one). But I agree with the point here, it's better to keep the OSS with some CI that's accessible by the community. I'll follow-up on this sometime next week, and check with Sergey. At least this should unblock the test job for now.

**Comment by dims** [comment]
thanks a ton @ibabou!

**Comment by dims** [comment]
https://testgrid.k8s.io/sig-node-containerd#gce-windows-2019-containerd-master
https://testgrid.k8s.io/sig-node-containerd#gce-windows-2019-containerd-1.21

Both are back on their feet with containerd 1.4.4

/close
