### ISSUE TITLE
cherrypick plugin doesn't response to all commands in a github comment

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/test-infra#21714]
**What happened**:
cherry-pick plugin didn't detect multiple uses of `/cherry-pick` command in the same message

ie. from https://github.com/knative/serving/pull/11127#issuecomment-814917770
```
/cherry-pick release-0.22
/cherry-pick release-0.21
```
**What you expected to happen**:
It would schedule two cherry picks

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
/area prow
/help
Possibly a duplicate of https://github.com/kubernetes/test-infra/issues/21684

**Comment by matthyx** [comment]
I think it's clear:
https://github.com/kubernetes/test-infra/blob/ef7abaaa70ae3626c5243a117d1d6955e56d4c08/prow/external-plugins/cherrypicker/server.go#L292

I'll do that.
