### ISSUE TITLE
Inrepoconfig supports periodic jobs

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#21729]
**What would you like to be added**:

Inrepoconfig supports presubmit and postsubmit at the moment, would like to understand what would it take to make it also support periodic jobs.

**Why is this needed**:

So that prow clients don't need to create two PRs for new repos, or the same job that need to be ran in both pre/post submit and periodics.

**Comment by chaodaiG** [comment]
/area prow

CC @cjwagner @alvaroaleman for inputs

**Comment by alvaroaleman** [comment]
The issue is that that the event (a timer) that causes us to load the job config and then trigger the job is part of said config itself. In the case of presubmit and postsubmit, the event is unrelated to the job, so its not a problem there.

We would probably need to listen to all push events and whenever one happens, check if there is a new config and if yes load it? Probably not impossible, but seems difficult and I am not sure about the benefit.

**Comment by chaodaiG** [comment]
> I am not sure about the benefit.

The immediate benefit is related to github private repo, we are planning to support a github private repo on a public prow instance with the `hidden_repo` feature in deck, and inrepoconfig is preferred because the repo owners don't want to expose any of their prow jobs, and the only thing missing here is the support of periodic jobs.

In the other hand, as I mentioned in the description, it's cumbersome to create two pull requests updating prow jobs in the repo where prow service cluster is configured and in their own repo.

**Comment by chaodaiG** [comment]
> We would probably need to listen to all push events and whenever one happens, check if there is a new config and if yes load it?

If I understand correctly, this means: 
- scrape every time horologium runs
- query for the commit hash of default branch for each repo that enabled inrepoconfig
- load the config if there is a new commit from last run

Sounds not too terrible to me, and I think it's doable. Is there any other foreseeable concern other than triggering?

**Comment by alvaroaleman** [comment]
> scrape every time horologium runs

This isn't doable, because horologium runs every 30 seconds and would need to fetch
* All branches of all repos
* Check if the file exists
* Load it

**Comment by chaodaiG** [comment]
Totally agreed! What I typed was not actually what I thought 😢 , fingers moved too fast..

What's in my mind was a separate goroutine doing this update loop, which of course will cause delay, but I guess it's bearable if it's a couple of minutes delay. Hopefully this wouldn't be too much of a burden for github token

**Comment by chaodaiG** [comment]
> All branches of all repos

It's nice to allow periodic in different branch, but might not be preferable, it's:
- too expensive for prow
- duplicate prow jobs in different branches might make sense but not always desirable imo

So I would prefer enforce periodic jobs in default branch only

**Comment by alvaroaleman** [comment]
> What's in my mind was a separate goroutine doing this update loop, which of course will cause delay, but I guess it's bearable if it's a couple of minutes delay. Hopefully this wouldn't be too much of a burden for github token

That could work (modulo potential token issues, but you could use a GH app which gives you a lot more tokens to alleviate that). Thinking about this some more, having only horologium have an up-to-date job config might cause some issues (e.G. you can not restart them from deck). Maybe a new component that updates a configmap would be preferrable?

> So I would prefer enforce periodic jobs in default branch only

from a user perspective, that is not what I would expect. Maybe make it configurable?

**Comment by chaodaiG** [comment]
> Maybe a new component that updates a configmap would be preferrable?

Yeah if we want to be more correct and more resilient in general then this seems like the approach to go, might run into configmap 1Mb size limit though. Will need to think more on this front.

> e.G. you can not restart them from deck

IIUC restarting from deck just means kubectl apply the same prowjob CR, which is pretty much what horologium does, and seems to me will work, could you elaborate a bit more why you don't think so?

> So I would prefer enforce periodic jobs in default branch only
> > from a user perspective, that is not what I would expect. Maybe make it configurable?

Configurable makes sense to me. The detailed logic of how to dedup prowjobs that have the same cloneref, and would we expect repo owners to clean up prow jobs from stale branches will need to be fleshed out later

**Comment by alvaroaleman** [comment]
> Yeah if we want to be more correct and more resilient in general then this seems like the approach to go, might run into configmap 1Mb size limit though. Will need to think more on this front.

I don't think this is any better or worse than getting the data from a config file in the config repo. It can be gzipped, that helps a lot. We are still having issues with this in Openshift and are contemplating to find/build a sidecar that keeps a clone current instead of putting the config in configmaps.

> IIUC restarting from deck just means kubectl apply the same prowjob CR, which is pretty much what horologium does, and seems to me will work, could you elaborate a bit more why you don't think so?

Yeah you are right, I always confuse this.

> Configurable makes sense to me. The detailed logic of how to dedup prowjobs that have the same cloneref, and would we expect repo owners to clean up prow jobs from stale branches will need to be fleshed out later

Yeah. Maybe a small proposal would be nice though?

**Comment by chaodaiG** [comment]
/remove-lifecycle stale
we still need this

**Comment by kiruh** [comment]
It would be really useful.
