### ISSUE TITLE
Remove canonical dashboard

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#21736]
Need i say more? (see below)

![image](https://user-images.githubusercontent.com/23304/114195906-e382c980-991e-11eb-91aa-8179855848d5.png)

**Comment by dims** [comment]
This is even worse! :( https://testgrid.k8s.io/sig-release-generated#Summary

**Comment by BenTheElder** [comment]
cc @spiffxp

**Comment by BenTheElder** [comment]
+1

**Comment by BenTheElder** [comment]
I agree we should do this. but also
/priority backlog

**Comment by dims** [comment]
cc @alxchalkias

**Comment by dims** [comment]
Done!
