### ISSUE TITLE
Deck warning "failed to get job history ... context cancelled"

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#21738]
**What happened**:

Recurring warnings in prow logs:
```
jsonPayload: {
component: "deck"
handler: "/job-history"
msg: "failed to get job history: failed to get build ids: failed to list keys: context canceled"
func: "main.handleJobHistory.func1"
url: "/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-ubuntu-containerd"
level: "warning"
file: "prow/cmd/deck/main.go:909"
}
```

**What you expected to happen**:

If this is a prow warning that worths prow oncall attention, then it should be surfaced as warning log in prow. In this case `context cancelled` to me means user closed or refreshed the job history page and caused this, which shouldn't be a warning in prow log.

/area prow
/kind oncall-hotlist

**Comment by spiffxp** [comment]
/sig testing
/assign @chaodaiG 
as current test-infra-oncall

is this still relevant?

**Comment by chaodaiG** [comment]
yes it's still relevant

**Comment by fejta** [comment]
We can distinguish types of context errors:

```golang
err := ctx.Err()
switch {
case  errors.Is(err, context.DeadlineExceeded):
  // too slow
case errors.Is(err, context.Canceled):
  // intentionally canceled
default:
  // some other error
}
```
