### ISSUE TITLE
Copy-pasteable command to rerun all failing tests

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2174]
/assign @spxtr 

When I see something like the following:

@fejta: The following test(s) **failed**:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
Jenkins unit/integration | a904aa7824b5462147574469788953d45744f9dc | [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/37868/pull-kubernetes-unit/21247/) | `@k8s-bot unit test this`
pull-kubernetes-e2e-gce-canary | a904aa7824b5462147574469788953d45744f9dc | [link](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/37868/pull-kubernetes-e2e-gce-canary/2/) | `@k8s-bot pull-kubernetes-e2e-gce-canary test this`

[Full PR test history](https://k8s-gubernator.appspot.com/pr/37868). [Your PR dashboard](https://k8s-gubernator.appspot.com/pr/fejta). Please help us cut down on flakes by linking to an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/prow/commands.md).
</details>

I would like there to be a line like this that I can copy and paste:
```
@k8s-bot unit test this
@k8s-bot pull-kubernetes-e2e-gce-canary test this
```

This will make it really easy to rerun a bunch of jobs caused by flakes that do not require me to push a new commit.

**Comment by krzyzacy** [comment]
@k8s-bot retest this

**Comment by fejta** [comment]
That is an equally good if not better solution

**Comment by spxtr** [comment]
We could add `/retest`, but we have to think about it a little bit.

`/retest all`? `/retest failed`? `/retest pull-kubernetes-e2e-gce pull-kubernetes-bazel`?

**Comment by thockin** [comment]
please make it a string that does not need me to name the specific tests, so I can save it as a pre-written response in GH.

**Comment by spxtr** [comment]
Done by #2908
