### ISSUE TITLE
Declarative administration for github repos

### ISSUE THREAD

**Issue by ameukam** [kubernetes/test-infra#21774]
**Why is this needed**:

Currently, any request for a new github repo on https://github.com/kubernetes/org/ is handled manually by the Github Admins. It would be great to see those requests managed in the same way as the contributors.

/assign @cblecker @nikhita 
cc @mrbobbytables @spiffxp

**Comment by nikhita** [comment]
Peribolos does support creating repos: https://github.com/kubernetes/test-infra/blob/925c28cd81fa0de9d55230a717ff37fd3e4aac93/prow/cmd/peribolos/main.go#L875

We create repos using a template repo today - https://github.com/kubernetes/kubernetes-template-project - so would need to check if the API supports template repos and if this can be integrated into peribolos.
