### ISSUE TITLE
Deprecate 'gcs/' storage provider suffix

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#21793]
**What should be cleaned up or changed**:
Configuring the 'gcs/' storage provider suffix in the job url prefix is deprecated since September 2020

**Provide any links for context**:
https://github.com/kubernetes/test-infra/blob/40c5a1d1b758201872804ec32ebad03845cffd47/prow/config/config.go#L1538-L1543

**Comment by sbueringer** [comment]
Good point. I'll take a look
/assign

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/pull/21071
