### ISSUE TITLE
needs-rebase add label and comment on closed PR

### ISSUE THREAD

**Issue by hi-rustin** [kubernetes/test-infra#21815]
**What happened**:
needs-rebase add label and comment on closed PR

https://github.com/pingcap/dm/pull/1595#issuecomment-820344537

**What you expected to happen**:
Do not respond to a PR that has been closed.
https://github.com/pingcap/dm/pull/1595#issuecomment-820344537

**Anything else we need to know?**:

needs-rebase verison: v20210315-198593ae42

**Comment by matthyx** [comment]
This is very weird, since the query should only get open PRs:
https://github.com/kubernetes/test-infra/blob/f8a90c0f33ec96557a56c4137a54effeaa71dcb1/prow/external-plugins/needs-rebase/plugin/plugin.go#L127

**Comment by BenTheElder** [comment]
github querying can return stale results, it happens sometimes to the kubernetes project, probably due to the scale.

**Comment by BenTheElder** [comment]
Perhaps the plugin should actually check that the PR is actually still open before taking action.
