### ISSUE TITLE
Increase AWS limits in some regions

### ISSUE THREAD

**Issue by hakman** [kubernetes/test-infra#21817]
Duplicating https://github.com/kubernetes/k8s.io/issues/1921 in hope that it gets more traction here and maybe a solution

> I can't confirm this because I do not have access to the AWS accounts used by prow jobs, but I believe that some AWS regions have lower resource limits than others.
> 
> Example VPC limits being reached in [ap-southeast-1a](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-kubernetes-aws/1381638281560592384#1:build-log.txt%3A569), [eu-central-1a](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-kubernetes-aws/1381463978663743488#1:build-log.txt%3A494), [eu-north-1a](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-kubernetes-aws/1381454454682816512#1:build-log.txt%3A487), and [eu-west-1a](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-kubernetes-aws/1381436067751661568#1:build-log.txt%3A504).
> 
> `W0412 16:10:28.895604 10570 executor.go:139] error running task "VPC/e2e-be8b7a2dfe-ff1eb.test-cncf-aws.k8s.io" (5m18s remaining to succeed): error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.`
> 
> I know that in the past we have increased the service limits in some regions and zones but it would be nice to have those limits be increased consistently. New regions will be added, new AWS accounts will be added; there are many opportunities for these limits to drift. Tools like [cloud custodian](https://cloudcustodian.io/docs/aws/examples/accountservicelimit.html) can increase limits automatically.

/cc @justinsb @BenTheElder @rifelpet

**Comment by BenTheElder** [comment]
I have no access to this.

**Comment by BenTheElder** [comment]
Also: increasing resource limits would be an issue for k8s.io, test-infra is not where these resources are managed.

Let's keep this in the original issue please.

**Comment by BenTheElder** [comment]
re-raised to wg-k8s-infra

**Comment by hakman** [comment]
Thanks @BenTheElder
