### ISSUE TITLE
Failed to visit prow console after installed prow in openshift or kind

### ISSUE THREAD

**Issue by wewang58** [kubernetes/test-infra#21826]
What happened:
When installed prow in openshift(version:4.8), using the file: https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter-s3.yaml, cannot visit prow console via" prow.wewang.com", return 404
$ oc get pods
NAME                                      READY   STATUS    RESTARTS   AGE
crier-5cdc8c68f9-zslnw                    1/1     Running   0          64s
deck-cbc5994f9-8mpzr                      0/1     Running   0          75s
deck-cbc5994f9-d7hwb                      0/1     Running   0          75s
ghproxy-8564fcb476-x64hz                  1/1     Running   0          68s
hook-5fbd7946b9-thxqd                     1/1     Running   1          68s
hook-5fbd7946b9-z9fv5                     1/1     Running   1          68s
horologium-c55996b49-kqw2m                1/1     Running   0          72s
minio-77d8c77bcb-wcm7x                    1/1     Running   0          63s
prow-controller-manager-f4dc56dc6-dg9bf   1/1     Running   0          67s
sinker-6b857d85f5-qhjjk                   1/1     Running   0          72s
statusreconciler-6ff6d579d4-kkbcg         1/1     Running   0          65s
tide-79c5cb877d-55st6                     1/1     Running   0          66s

$ oc get ingress -n prow
NAME   CLASS    HOSTS             ADDRESS   PORTS     AGE
prow   <none>   prow.wewang.com             80, 443   87s

$ oc get svc -n prow
NAME      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
deck      ClusterIP   xx.xxx.xx.xx     <none>        80/TCP            93s
ghproxy   ClusterIP   xxx.30.xxx.134   <none>        80/TCP,9090/TCP   84s
hook      ClusterIP   xxx.xxx.xxx.247   <none>        8888/TCP          94s
minio     ClusterIP   xxx.30.xx.169    <none>        80/TCP            78s
tide      ClusterIP   xxx.30.xxx.56    <none>        80/TCP            92s

$ oc describe ingress -n prow
Name:             prow
Namespace:        prow
Address:          
Default backend:  deck:80   xx.xx.2.xx:8080,xx.xxx.xxx.115:8080)
TLS:
  prow-ingress-tls terminates prow.wewang.com
Rules:
  Host             Path  Backends
  ----             ----  --------
  prow.wewang.com  
                   /       deck:80     xx.128.xx.33:8080,xx.131.xxx.115:8080)
                   /hook   hook:8888   xx.xxx.xx.31:8888,xx.xx.2.28:8888)
Annotations:       cert-manager.io/cluster-issuer: letsencrypt-staging
Events:            <none>

$oc logs -f pod/deck-cbc5994f9-8mpzr -n prow
{"agent":"tide","component":"deck","error":"Get \"http://tide/\": dial tcp xxx.xx.xxx.56:80: connect: connection refused","file":"prow/cmd/deck/tide.go:122","func":"main.fetchTideData","level":"info","msg":"Failed 3 retries fetching Tide data before success: Get \"http://tide/\": dial tcp xxx.30.xx.56:80: connect: connection refused.","severity":"info","time":"2021-04-16T05:51:32Z"}

What you expected to happen:
It could be visited prow console

How to reproduce it (as minimally and precisely as possible):
Always
Please provide links to example occurrences, if any:

Anything else we need to know?:

**Comment by BenTheElder** [comment]
kind is for local clusters, so a domain like `prow.wewang.org` is not going to work in kind. 
you should see https://kind.sigs.k8s.io/docs/user/ingress/

Can't speak as to openshift
/kind support
/area prow

**Comment by wewang58** [comment]
@BenTheElder  Thanks your response, Now I already installed GKE, and using starter-s3.yaml to create a prow in GKE, should i also need to install cert-manager and add annotation in ingress manifest, so i can visit a domain like "prow.wewang.com"  right?
Maybe you are not responsible for it, but i don't know who i can ask, thanks in advance.
here's steps info
```
Applying github token into oauth-token secret...W0510 15:06:12.316128   10395 helpers.go:567] --dry-run=true is deprecated (boolean value) and can be replaced with --dry-run=client.
secret/oauth-token created
Ensuring hmac secret exists at hmac-token...INFO[1896] Creating new hmac-token secret with random data... 
exists
Looking for prow's hook ingress URL... .......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................```
seems something wrong with my ingress, so cannot visit prow's hook.

**Comment by wewang58** [comment]
@BenTheElder  I will close the issue, and open a new issue for GKE.

**Comment by BenTheElder** [comment]
I am not, but you can always ask the community and eventually someone should respond. I can't handle everything myself 🙃
