### ISSUE TITLE
remote JobConfig

### ISSUE THREAD

**Issue by neolit123** [kubernetes/test-infra#21859]
might have been discussed in the past, but i could not find any tickets for this.

**What would you like to be added**:

allow having a folder in test-infra that contains a YAML file that contains a list of YAML URLs to fetch from another repository.

there could be a specifically named file such as `remote-jobs.yaml` that the prow config directory parser recognizes and loads additional jobs from URLs in that file. then validates them and merges them with the rest of the files in the same directory:

```
type RemoteJobConfig struct {
    RemoteJobURLs []string `json:"remoteJobURLs"`
}
```

```
# remote-jobs.yaml
remoteJobURLs:
- https://git.k8s.io/foo/bar1.yaml
- https://git.k8s.io/foo/bar2.yaml
```

**Why is this needed**:

not strictly needed, but it reduces the amount of PRs that have to be sent to the test-infra repository.
for example, the common pattern in updating a test today is to have a change in tooling / scripts in repository `foo` and also having a PR for test-infra updating prow jobs. this means 2 PRs in most cases.

### security

- maintain a whitelist of trusted repositories or umbrella github orgs
- cap the limit of the remote files to N bytes. `Content-Length` in the response header can be inspected prior to download. download progress can be interrupted after N bytes.

### remote agent watch

currently prow has an [agent](https://github.com/kubernetes/test-infra/blob/2ae6e67a50abc7f4ef757b1f0271d31d53108ca7/prow/config/agent.go) that watches directories for changes and reloads the config from there. these are fairly frequent.

if remote watches are to be added they must use a less frequent method and check something like the `etag` from the response header for a URL.

/kind feature
/area prow config

**Comment by alvaroaleman** [comment]
@neolit123 I believe [inrepoconfig[(https://github.com/kubernetes/test-infra/blob/master/prow/inrepoconfig.md) would serve your usecase. Ppl didn't want it for prow.k8s.io due to security concerns though: https://github.com/kubernetes/test-infra/issues/15676

**Comment by BenTheElder** [comment]
As @alvaroaleman mentioned this exists already for other prows to use but we will not be enabling it in prow.k8s.io because it bypasses our config presubmits used for security etc.

This can be reconsidered when the project / community finish migrating to CNCF clusters, at which point it will be trickier to figure out who should decide this, but in the meantime the cluster still runs largely on google.com resources where the oncall team has expressed not being comfortable with this.

It may also become more viable when some of alvaro's other work lands to allow us to restrict config further with built in functionality. But currently what any individual config file can do is too unrestricted without our presubmits.

**Comment by neolit123** [comment]
understood. thanks for the replies.
i actually saw `Inrepoconfig` while searching for existing features, but didn't not check its readme.

and yes, i think we do need this for the k8s prow, eventually as it will help with noise reduction and extra work.

> It may also become more viable when some of alvaro's other work lands to allow us to restrict config further with built in functionality. But currently what any individual config file can do is too unrestricted without our presubmits.

true, some sort of additional restriction / policy must apply for these it seems.

one argument for the current setup, is that someone could "hack" a bash script in a stale k8s org repo and start mining crypto from it. the existing config presubmits cannot catch that. one would likely have to examine the cluster behavior / resource consumption and it might still remain fairly hidden.

**Comment by BenTheElder** [comment]
That's one vector yes, we basically assume this has happened.

This is why some jobs are isolated to certain clusters.

But further someone could send a PR to kubeadm to add a blocking presubmit to test infra.

Or any excessive resource usage (e.g. declaring 10000 kubeadm presubmit asking for 8 cores each), which the admin team then has no recourse for and poor visibility into.

We have presubmits over the configuration for good reason. We need more of that, not zero.

**Comment by BenTheElder** [comment]
Tightening the policy around what jobs are allowed is actually something SIG testing is working on this quarter.

**Comment by alvaroaleman** [comment]
> But further someone could send a PR to kubeadm to add a blocking presubmit to test infra.

That is not possible, no, you can only define jobs for the repo the config is in.

> Or any excessive resource usage (e.g. declaring 10000 kubeadm presubmit asking for 8 cores each), which the admin team then has no recourse for and poor visibility into.

These things would be easy to validate (and they are not currently being validated for the config in here). Adding tight valdiation for this is an easy thing to do, so if there was a set of things you would like to see (e.G. max number of pods + max cpu + max mem across all jobs per repo) to feel comfortable, that is easy to do.

My understanding from the previous dicsusion was that this isn't wanted for as long as google manages prow.k8s.io regardless of validation.
