### ISSUE TITLE
Clean up load balancers in janitor

### ISSUE THREAD

**Issue by krousey** [kubernetes/test-infra#2188]
I've noticed that some projects have hit quota limits due to load balancers not being cleaned.

**Comment by krousey** [comment]
cc @spxtr

**Comment by krzyzacy** [comment]
@krousey can you give me a sample so I can verify

**Comment by krzyzacy** [comment]
Ok, I think the reason is I cannot find any api for load-balancer, from https://cloud.google.com/sdk/gcloud/reference/compute/ ?

**Comment by krousey** [comment]
Looking into it, it seems to be a combination of

  - Static IPs
  - Target Pools
  - Forwarding Rules
  - HTTP Health checks
 

Looking over this, it seems the janitor has these. I just have projects that are accumulating them quicker than janitor mops them up.

**Comment by krzyzacy** [comment]
hummm one thing might be, http-proxy is cleaned up but not https-proxy, and it drags all the dependent resources, I'll make the change.

Maybe give me the name of the project, and I can double-check the log.
