### ISSUE TITLE
nslookup for Jenkins executors

### ISSUE THREAD

**Issue by colhom** [kubernetes/test-infra#219]
We had some e2e tests failing due to `nslookup` not being available to the e2e framework. 

Install `bind-utils` package (or equivalent) on the Jenkins worker machines and/or within the e2e running container image?
 
\cc @nikhiljindal @mml 

ref kubernetes/kubernetes#28030

**Comment by ixdy** [comment]
Added into kubernetes/kubernetes/pull/27798.

**Comment by colhom** [comment]
Thanks @ixdy!

**Comment by ixdy** [comment]
Image has been updated. Note that PR Jenkins isn't using the container for e2e tests yet. I should fix that.

**Comment by ixdy** [comment]
actually that's a lie. it hasn't been merged yet.

**Comment by fejta** [comment]
Is this merged now?

**Comment by ixdy** [comment]
yep.
