### ISSUE TITLE
Can deck get  jobs' logs in minio not gcs

### ISSUE THREAD

**Issue by gamestart** [kubernetes/test-infra#21906]
**What happened**:
The prow status dashboard cannot show job logs, when i click the "Job History" i get the message "failed to get job history: could not instantiate storage bucket: bucket "prow-logs" not in allowed list ([s3://prow-logs]); you may allow it by including it in `deck.additional_allowed_buckets`"

**What you expected to happen**:
Just show the Job History

**How to reproduce it (as minimally and precisely as possible)**:
I deployed by the file 
https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter-s3.yaml

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

How can I config the file
`default_decoration_configs: "*": gcs_configuration: bucket: s3://prow-logs path_strategy: explicit s3_credentials_secret: s3-credentials` ? or change the deck config ?

**Comment by sbueringer** [comment]
@alvaroaleman has any new validation been added which broke this? :) I'm running basically the same config as described above with an older Prow version.

**Comment by alvaroaleman** [comment]
> @alvaroaleman has any new validation been added which broke this? :) I'm running basically the same config as described above with an older Prow version.

Yep :) Working on a PR. It was off by default before.
