### ISSUE TITLE
Smoke test deck in prow integration test

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#21908]
**What would you like to be added**:

Prow integration test deploys prow components in kind cluster, which should be able to be used for smoke testing deck, by deploying deck in kind cluster and curl the deck frontend to make sure it's not crashing.

**Why is this needed**:

See https://kubernetes.slack.com/archives/CDECRSC5U/p1618858118103100

### Changes Required

* Add `deck` at [`testimage-push`](https://github.com/kubernetes/test-infra/blob/f9fb6d28ebbcf77dc0b99d741b8df5f5d85c739e/prow/BUILD.bazel#L66) target, so that deck is pushed to `localhost:5000` registry
* Deploy deck during integration test https://github.com/kubernetes/test-infra/blob/f9fb6d28ebbcf77dc0b99d741b8df5f5d85c739e/prow/test/integration/setup-cluster.sh#L33, and cleanup `deck` after integration test https://github.com/kubernetes/test-infra/blob/f9fb6d28ebbcf77dc0b99d741b8df5f5d85c739e/prow/test/integration/cleanup.sh#L23
* Add deck deployment yaml at https://github.com/kubernetes/test-infra/tree/master/prow/test/integration/prow/cluster, so that the deployment works. This might be the trickiest part:
  * `deck_service.yaml` and `deck_rbac.yaml` can be symlinks from https://github.com/kubernetes/test-infra/tree/master/config/prow/cluster.
  * `deck_deployment.yaml` will at least requires changing image registry to `localhost:5000` like https://github.com/kubernetes/test-infra/blob/f9fb6d28ebbcf77dc0b99d741b8df5f5d85c739e/prow/test/integration/prow/cluster/hook_deployment.yaml#L41.
  * deck depends on `oauth-token`, `oauth-config`, `cookie-secret`, these very likely are not required for deck main page, so they might be mocked with any value, the format can be found at https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/prow/cmd/deck/github_oauth_setup.md.
  * `github-endpoint` should be changed to `fakeghserver`, which was from https://github.com/kubernetes/test-infra/tree/master/prow/test/integration/fakeghserver.

**Comment by BenTheElder** [comment]
@chaodaiG please check https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md#help-wanted, this could do with a little more detail as a help-wanted issue (e.g. pointers to the relevant sources and docs)

**Comment by chaodaiG** [comment]
> @chaodaiG please check https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md#help-wanted, this could do with a little more detail as a help-wanted issue (e.g. pointers to the relevant sources and docs)

Added more details, hopefully can help

**Comment by fgimenez** [comment]
/assign
/remove-help

I like to give this one a try :)
