### ISSUE TITLE
need way to remove `do-not-merge` label.

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#2196]
On https://github.com/kubernetes/kubernetes/pull/41581#issuecomment-285175154 I LG'd a PR that didn't yet have a release-note label. The bot yelled at me and then added `do-not-merge`.

If I don't have write access to the repo, I can fix the release note label (with /release-note-none), but then I'm stuck, since I can't remove `do-not-merge`.
I'm guessing the bot doesn't auto-remove it because it doesn't know why `do-not-merge` was added (since it can be added by humans too).

**Comment by spxtr** [comment]
You are correct about why I didn't make it remove `do-not-merge`. The munger shouldn't add `do-not-merge`, it just shouldn't merge if it hasn't got a release note label.

**Comment by MrHohn** [comment]
I also wish this could be fixed sooner, have a similar stuck PR here kubernetes/kubernetes#42757 :(

**Comment by ixdy** [comment]
@MrHohn yeah, workaround for now is "find someone with repo write access".

**Comment by lukaszgryglicki** [comment]
Working on that.

**Comment by krzyzacy** [comment]
@lukaszgryglicki you want to join org from the bot link first :-)

**Comment by lukaszgryglicki** [comment]
Yea. I'll wait for @grodrigues3 invitation, while working on this locally. This would be my first issue so I need some time to figure things out.

**Comment by lukaszgryglicki** [comment]
This is ready actually - but I must figure out how to create PR first. And also add some nasty edge cases. Will probably finish tomorrow.

**Comment by lukaszgryglicki** [comment]
Created 1st PR, not sure if this is correct or not.
I was requested to sign CLA - done.
Also this pr doesn't need release notes imho:
https://github.com/kubernetes/test-infra/pull/2456
