### ISSUE TITLE
Clusters are not turned down in case of failure.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#22]
This may be OK for small clusters that are running all the time, but is a pain for huge clusters running once a week. We should, at least, have a flag that will allow for cluster deletion on failure.

cc @wojtek-t @fejta @ixdy

**Comment by spxtr** [comment]
Related to https://github.com/kubernetes/kubernetes/pull/24739 ?

**Comment by gmarek** [comment]
It's still not done: http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-e2e-gce-enormous-cluster/122/

**Comment by spxtr** [comment]
We tried to, but were denied:

```
Bringing down cluster
09:24:31 ERROR: (gcloud.compute.instance-groups.managed.delete) Some requests did not succeed:
09:24:31  - Rate Limit Exceeded
```

**Comment by spxtr** [comment]
This was immediately after doing `cluster/log-dump.sh`. Perhaps I set the thread-count too high?
