### ISSUE TITLE
I should be able to /assign and /lgtm in the same comment

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#2200]
In lieu of fixing #1916, I'd at least expect a comment like
```
/assign
/lgtm
```
to work, but it [apparently does not](https://github.com/kubernetes/kubernetes/pull/42231#issuecomment-285207670).

**Comment by ixdy** [comment]
/unassign

argh

**Comment by fejta** [comment]
Sounds like you want https://github.com/kubernetes/test-infra/pull/2118

**Comment by ixdy** [comment]
yes, I do! I thought that was blocked on prow understanding OWNERS.

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/pull/250#issuecomment-286905508
