### ISSUE TITLE
Clarify Implications and Workflow for ok-to-test

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#22077]
Given the recent [abuse of pre-submit actions in GitHub](https://it.slashdot.org/story/21/04/05/0230229/github-is-investigating-crypto-mining-campaign-abusing-its-server-infrastructure) I wonder if we can have a high-level conversation about the `ok-to-test` label, community, and how we expect a workflow here to look.

Today Prow exposes two workflows for new contributors to have their PRs tested: an explicit `/ok-to-test` comment from a contributor that allows indefinite testing and individual `/test` commands which fire off one-shot tests. In a practical sense, given the occurrence of flakes in presubmit flows as well as in jobs started by `tide`, I am not sure that it's effective or useful to use the `/test` comment flow to get a PR merged in many projects.

The binding, future-looking implementation of `/ok-to-test` could lead to abusive behavior, however, as the user may change the content of their PR at will once tests have been allowed.

Are there other options? What exactly is the set of users who are _not_ trusted when they submit a PR, but become trusted forever once they have their code reviewed once?

/cc @bparees @alvaroaleman @petr-muller @cblecker @BenTheElder @cjwagner @spiffxp @fejta

**Comment by bparees** [comment]
an option to have /ok-to-test get cleared if the PR is updated seems like a good compromise.  (or a new label that has that functionality)

that way you get unlimited testing on your PR to deal with flakes, but if you change your PR, someone has to reconfirm you're not doing bad things.

**Comment by alvaroaleman** [comment]
> an option to have /ok-to-test get cleared if the PR is updated seems like a good compromise. (or a new label that has that functionality)

That is achieved through `/test all` by someone trusted (although a bit less obvious). `/retest` won't work then though (but we might be able to change that?)

**Comment by bparees** [comment]
> That is achieved through /test all by someone trusted (although a bit less obvious). 

are you telling me that if i put "/test all" on a pr that "needs-ok-to-test", those tests will be rerun until successful?

**Comment by bparees** [comment]
(my impression was that `/test all` was a one-shot thing, it'll run all the tests, but if any of them fail(potentially due to unrelated flakes), someone needs to put another `/test all` on the PR)

**Comment by alvaroaleman** [comment]
> are you telling me that if i put "/test all" on a pr that "needs-ok-to-test", those tests will be rerun until successful?

No, one shot I believe (But not 100% sure either, would need to check the code)

**Comment by bparees** [comment]
>  No, one shot I believe (But not 100% sure either, would need to check the code)

then it's not the same as what i proposed

**Comment by stevekuznetsov** [comment]
/retitle  Clarify Implications and Workflow for ok-to-test

**Comment by stevekuznetsov** [comment]
Any variation on `/test <thing>` is a one-shot trigger.

**Comment by fejta** [comment]
I like the idea of having an option to ensure that:

a) The `ok-to-test` label was added after the most recent push to the PR
b) Removing the `ok-to-test` label when new commits are pushed to the PR

I'd want this to either be the default or only behavior.


OTOH empirically the current behavior has proven sufficient to mitigate against this type of problem. But I would still prefer a safer default configuration for people to start with.

**Comment by alvaroaleman** [comment]
https://github.com/kubernetes/test-infra/issues/22077#issuecomment-832107261 sounds good. One important technical detail to keep in mind: Removing the label will race with triggering the tests, so if we do this, it will end up being more complicated than just "remove label on push".

**Comment by stevekuznetsov** [comment]
`ok-to-test` being sticky to a commit SGTM as well
