### ISSUE TITLE
Prow inrepoconfig: jobs definition in multiple files

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#22072]
**What would you like to be added**:

Prow inrepoconfig supports multiple files instead of only `prow.yaml` file. One option is a directory called `.prow` under the root level.

**Why is this needed**:

- Single file is sufficient for a small repo with small number of prow jobs that can be easily managed
- Single file is not very friendly with repo that has long history and lots of prow jobs.
- Also not possible to do fine grained OWNERS control on prow jobs.

The changes required to make this work, should be:
- Other than look for `.prow.yaml` file in the repo, also look for `.prow` directory, which happens in https://github.com/kubernetes/test-infra/blob/ad136bc20c7f33eedb546cd799ccdf04f47bddb9/prow/config/inrepoconfig.go#L34
- Also remember to update `checkconfig` if required at https://github.com/kubernetes/test-infra/blob/master/prow/cmd/checkconfig/main.go#L155
- Documentation would also need to be updated https://github.com/kubernetes/test-infra/blob/master/prow/inrepoconfig.md#L32

**Comment by chaodaiG** [comment]
cc @cjwagner , @alvaroaleman : is there anything blocking us from doing so?

**Comment by alvaroaleman** [comment]
I don't think so, this seems pretty straight forward

**Comment by chaodaiG** [comment]
/good-first-issue
/help

Instructions will be added slightly later

**Comment by chaodaiG** [comment]
Instructions added

**Comment by fgimenez** [comment]
/assign
/remove-help

I'd like to give it a try, @chaodaiG will let you know how it goes :)
