### ISSUE TITLE
Run gazelle using bazel

### ISSUE THREAD

**Issue by dhiller** [kubernetes/test-infra#22104]
**What would you like to be added**:

Ability to run gazelle with `bazel run //:gazelle`

I found it surprising that I had to run gazelle without using bazel, while the contributors guide says `bazel test` and `bazel build` are the way to build and test. I figure there must be a reason for this?

**Why is this needed**:

Usability improvement for updating bazel build files.

**Comment by spiffxp** [comment]
/sig testing
/assign @fejta 
please re-assign to someone more appropriate to handle bazel-related support

**Comment by fejta** [comment]
You're expected to run `hack/update-deps.sh` or `hack/update-bazel.sh` which among other things runs gazelle.
