### ISSUE TITLE
`do-not-merge/needs-sig` Not Removed After Sig

### ISSUE THREAD

**Issue by fenngwd** [kubernetes/test-infra#22139]
**What happened**:
`do-not-merge/needs-sig` can not be removed after added sig label.
**What you expected to happen**:
After using `sig` command, `do-not-merge/needs-sig` should be removed from labels.

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/kubernetes/kubernetes/pull/101690

**Please provide links to example occurrences, if any**:
https://github.com/kubernetes/kubernetes/pull/101690

**Anything else we need to know?**:
This is my first contribution to Kubernetes, maybe there are some mistakes in workflow. Please help me to figure this out. Thanks!

**Comment by BenTheElder** [comment]
> /remove do-not-merge/needs-sig

This is not a valid command. https://prow.k8s.io/command-help has valid commands

https://github.com/kubernetes/kubernetes/pull/101690#event-4743948649 it was manually fixed here.

Sometimes webhooks are dropped and this happens. I don't think prow provides a good option to reconcile this when it happens, but I'm not sure. 

cc @cjwagner

**Comment by cjwagner** [comment]
> Sometimes webhooks are dropped and this happens. I don't think prow provides a good option to reconcile this when it happens, but I'm not sure.

Yeah I don't think we have a `/check-sig` command or anything like that to force revalidation. The logic for adding the `do-not-merge/needs-sig` is actually separate from the logic for adding sig labels and doesn't handle any commands currently.

One option might be to `/remove-sig network` then `/sig network` in a follow up comment?

**Comment by BenTheElder** [comment]
Would a /check-sig be accepted? This seems like it could make a pretty good help-wanted issue.

Alternatively: is label data only in the event that changes the labels? If not can we have a request to update that plugin to watch more generally for the current label set and remove or add the label as necessary?

Theoretically this can also happen the opposite way currently where we fail to add the needs label when sig(s) are removed?

**Comment by cjwagner** [comment]
> Would a /check-sig be accepted? 

Well the `needs-sig` label is managed by the [`require-matching-label` plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/require-matching-label) which can be configured for arbitrary label sets, not just the SIG labels. (See the [k8s-prow config here](https://github.com/kubernetes/test-infra/blob/d14ff9c886b7e6152e2a89dc89e34ccae9ce5e55/config/prow/plugins.yaml#L490)) So I don't think we'd want a command named `/check-sig`, but something more generic like `/check-required-labels` would be good.

> Alternatively: is label data only in the event that changes the labels?

Yes, the webhook payload sets a `label` field for PR events of type `labelled` or `unlabelled`. The plugin tries to be API rate limit efficient by only fetching more info for events that could be relevant.

> Theoretically this can also happen the opposite way currently where we fail to add the needs label when sig(s) are removed?

Yes that is entirely possible unfortunately. Dropped webhooks are not good, it would be great if we could query the API for failed webhook deliveries periodically, but thats still not available as far as I know.

**Comment by BenTheElder** [comment]
`/check-required-labels` seems like a good help-wanted task then.

**Comment by cjwagner** [comment]
> `/check-required-labels` seems like a good help-wanted task then.

I opened https://github.com/kubernetes/test-infra/issues/22208. I'll close this bug in favor of that feature request.
/close

**Comment by BenTheElder** [comment]
Thanks cole!
