### ISSUE TITLE
Tide can quickly fill GH limit on statuses on SHA 

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/test-infra#22143]
**What happened**:

When a repo is (mis-?)configured in a way that a PR can become Tide-mergeable (necessary labels are present, all tests pass, etc) but not GH-mergeable, for example by requiring "At least 1 approving review is required by reviewers with write access." on GH level, then Tide will attempt to merge it and fails, updating the `tide` status on the PR every time, fairly quickly reaching the limit GH has on the number of statuses on a single SHA. In our case, it looks like the limit was reached in ~19 hours:

https://github.com/open-cluster-management/policy-collection/pull/110

Prow hitting this limit on contexts is a fairly pathological state: the PR cannot be retested and it seems that Tide would not even merge it because it is not able to update its status..

**What you expected to happen**:

Do not update `tide` status a thousand times to `success`

**How to reproduce it (as minimally and precisely as possible)**:

1. Set custom merge critera on a repo
2. Make a PR TIde-mergeable but not GH-mergeable
3. Wait

**Please provide links to example occurrences, if any**:

https://github.com/open-cluster-management/policy-collection/pull/110

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
@petr-muller so the issue is that we set it unconditionally and we should be checking if its already set first?
