### ISSUE TITLE
Testgrid complains on "podinfo.json" not found and marks conformance tests as failed

### ISSUE THREAD

**Issue by dguendisch** [kubernetes/test-infra#22140]
**What happened**:
Basically the very same thing happens again starting with tests from today as explained in https://github.com/kubernetes/test-infra/issues/21126
Tests are being marked as failed because of some `podinfo.json` missing (we're not runnign our tests via prow).

Back then this was fixed in testgrid by allowing jobs to disable the pod row config (https://github.com/GoogleCloudPlatform/testgrid/issues/393) which we did.

However since today the same issue appears again, e.g. https://testgrid.k8s.io/conformance-gardener#Gardener,%20v1.17%20GCE

**What you expected to happen**:
Tests to be marked as succeeded when all conformance tests passed.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

cc @schrodit 

/area testgrid

**Comment by irbekrm** [comment]
Similar for us- it starts appearing again for jobs for which the GCS reporter is enabled (we have it installed) https://testgrid.k8s.io/jetstack-cert-manager-previous#ci-cert-manager-previous-bazel

**Comment by BenTheElder** [comment]
cc @michelle192837 @chases2

**Comment by adelina-t** [comment]
Similar to us, for externally run jobs ( not via prow ): windows-containerd-integration ( https://testgrid.k8s.io/sig-windows-containerd-runtime-signal#win-2004-containerd-master-integration ). We have the `disable_prowjob_analysis` field set.

**Comment by michelle192837** [comment]
Sorry to miss this! I took a look at all these tabs, and for some reason it seems like none of them have `disable_prowjob_analysis` in the resolved configuration ("About" -> "View Configuration", e.g. https://testgrid.k8s.io/q/config/sig-windows-containerd-runtime-signal/win-2004-containerd-master-integration), despite having it set in the YAML (https://github.com/kubernetes/test-infra/search?q=disable_prowjob_analysis)...

Ah, but Configurator lives here and the version of TestGrid in this repo hasn't caught the new field, so it's not being picked up. Lemme see if I can update it.

@chases2
