### ISSUE TITLE
Certificate for the monitoring domain has expired.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#22147]
The certificate for the monitoring domain expired somehow. It seems like the problem was detected according to the SLO graphs, but we did not receive an automated alert for some reason.
https://monitoring.prow.k8s.io
cc @chaodaiG @fejta @mpherman2

**Comment by chaodaiG** [comment]
```
$ ping monitoring.prow.k8s.io
PING monitoring.prow.k8s.io (130.211.20.136): 56 data bytes
64 bytes from 130.211.20.136: icmp_seq=0 ttl=58 time=20.691 ms
64 bytes from 130.211.20.136: icmp_seq=1 ttl=58 time=16.047 ms
64 bytes from 130.211.20.136: icmp_seq=2 ttl=58 time=16.114 ms
```
Seems like still reachable, might explain why automated alerts were not fired

**Comment by chaodaiG** [comment]
![Screen Shot 2021-05-11 at 11 06 57 AM](https://user-images.githubusercontent.com/45011425/117863832-09b2c680-b249-11eb-9a85-0d6ec9aec762.png)

So yeah it did fired but not routed correctly, I'll take a look at the alerting part

**Comment by cjwagner** [comment]
According to the blackbox prober the certificate was valid up until 2:53am on May 1st.

**Comment by chaodaiG** [comment]
Inspecting load balancer of grafana https://pantheon.corp.google.com/net-services/loadbalancing/details/http/k8s-um-prow-monitoring-grafana--3a93fcce573ea69e?project=k8s-prow&tab=details&duration=PT1H, there are 3 certificates attached:

![Screen Shot 2021-05-12 at 11 14 41 AM](https://user-images.githubusercontent.com/45011425/118024228-4e0a9900-b313-11eb-94e5-a0034cfa24a2.png)

The first 2 are both valid certs while the last one expires  Jan 9, 2020, 1:46:27 PM

**Comment by chaodaiG** [comment]
The manifest of the expired cert looks like:
```
DNS Hostnames	 monitoring.prow.k8s.io
Expires	   Jan 9, 2020, 1:46:27 PM
Serial Number	  <HIDDEN>
Certificate Issuer	 Let's Encrypt Authority X3
```

While the first two certs are managed with the field of:
```
Certificate Type	  MANAGED
```

**Comment by chaodaiG** [comment]
It's using the correct cert now, https://monitoring.prow.k8s.io works fine for me now

**Comment by chaodaiG** [comment]
The cert was added back and it's down again

**Comment by chaodaiG** [comment]
Deleted the cert and it was created by `service-684195865762@container-engine-robot.iam.gserviceaccount.com` again and re-attached to the LB. It's pretty mystery now what has driven the recreation of the cert, also mystery why it only affects grafana LB but not prow deck LB

**Comment by chaodaiG** [comment]
The ingress had run into a bad state and I’m working on fixing it (reverting PR won’t help here). In the meanwhile please use monitoring.prow-canary.k8s.io until further notice

**Comment by chaodaiG** [comment]
The symptom was gone, I think it was fixed by https://github.com/kubernetes/test-infra/pull/22187
/close
