### ISSUE TITLE
Don't make a comment if the PR is already approved.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2215]
I make a PR that touches files that I own. The approval munger should add the `approved` label and not say anything. I don't want a giant comment saying "this PR is approved!" See [this comment](https://github.com/kubernetes/kubernetes/pull/42855#issuecomment-285525176) for an example, although it may get deleted at some point.

Also, once the last person says `/approve`, it should remove the old comment. PRs are noisy enough already.

/assign @apelisse @grodrigues3

**Comment by apelisse** [comment]
IXDY Has APPROVED!!!!

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque viverra non erat id consectetur. Suspendisse gravida tincidunt aliquam. Duis sit amet arcu et risus fermentum eleifend. Cras congue fringilla nibh, nec venenatis odio molestie ut. Proin facilisis dolor id odio egestas vestibulum. Pellentesque euismod eros eget magna pharetra, vel congue massa venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer ac ligula eros.

Maecenas non turpis in tellus pellentesque mollis. Nullam fringilla porttitor metus gravida efficitur. Nunc vel erat ligula. Phasellus id tellus sed lectus euismod iaculis sed vel arcu. Phasellus efficitur consequat lacus, at porta enim blandit eu. Duis erat leo, congue vehicula tempus quis, luctus eu odio. Donec velit augue, sagittis ac viverra non, lacinia ut nulla. Praesent fermentum mauris eu est condimentum, nec condimentum tortor auctor. Fusce laoreet blandit enim faucibus fringilla. Nunc porttitor risus massa, eget sollicitudin quam sagittis quis. Maecenas tincidunt, enim ac congue auctor, eros odio molestie urna, a feugiat nisl nisi quis risus. Nunc finibus, dolor sed mattis malesuada, diam lectus molestie massa, vel pharetra justo sem vel ante. Vestibulum consequat urna lorem, eget tempor turpis pulvinar blandit.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus facilisis, nisi sit amet auctor efficitur, justo neque tristique metus, eu accumsan erat sem nec velit. Etiam libero lorem, iaculis sed congue non, ullamcorper maximus lectus. Nullam condimentum mauris sapien, non semper justo malesuada eget. Etiam libero arcu, fringilla nec imperdiet in, mollis eu odio. Morbi lacinia pharetra orci, vitae sollicitudin erat laoreet a. Fusce rhoncus est id ornare ornare.

In ultricies, nunc ornare pellentesque convallis, elit metus viverra metus, sit amet scelerisque turpis nisi sit amet magna. Aliquam tortor lorem, venenatis eu scelerisque sed, hendrerit a massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer id ipsum mattis, molestie diam quis, gravida dolor. Nullam sed vestibulum turpis, non facilisis nibh. Nulla facilisis ullamcorper accumsan. Quisque arcu elit, efficitur sit amet dignissim vitae, bibendum sit amet justo. Ut non augue quis magna imperdiet mollis quis in risus. Praesent a porttitor velit, dictum volutpat nisl. Ut dictum elit eu dapibus porta. Duis viverra tempor erat, eu porttitor ex facilisis et. Aliquam suscipit placerat metus, eget hendrerit est auctor et. Phasellus consectetur augue magna, ac convallis arcu porttitor ut. Mauris vehicula mauris eu fermentum luctus. In hac habitasse platea dictumst. Duis pellentesque nunc quis eleifend pellentesque.

Etiam ullamcorper diam non blandit hendrerit. Vestibulum nisi sapien, elementum in ipsum non, ultrices laoreet ipsum. Praesent tempus neque vel urna ultrices, vitae volutpat mi mollis. Vestibulum eget volutpat lorem. Sed sit amet lectus orci. Proin sapien ligula, pulvinar sed nibh ut, auctor tincidunt lorem. Maecenas dapibus nulla ac nibh iaculis, ut iaculis diam luctus. Nulla non justo ultricies, fringilla augue at, viverra risus. Vivamus ut magna lectus. Duis vel est egestas, rhoncus ante vel, gravida eros. Vivamus faucibus, urna at auctor rutrum, augue tortor lobortis ex, at egestas ligula orci nec dolor. Proin interdum dictum lorem, sit amet sagittis nulla tincidunt et. Aenean tincidunt tellus sit amet quam auctor, quis tristique eros rutrum. Praesent ut ligula bibendum, scelerisque turpis eget, dapibus ex. Integer pulvinar congue lorem, lacinia volutpat sem ullamcorper ut.

Etiam sagittis est odio, sed dapibus tellus pellentesque sit amet. In hac habitasse platea dictumst. Nunc interdum pretium eleifend. Sed ut justo vel felis gravida pharetra. Nunc vel faucibus justo, vel commodo enim. Praesent blandit ante libero, non volutpat sem lobortis vel. Donec ut massa at lorem accumsan pharetra. Nam non dui a justo posuere accumsan. Aenean laoreet purus condimentum arcu maximus, et facilisis dui sollicitudin. Integer iaculis tincidunt dapibus. Donec imperdiet eleifend lorem, ut efficitur ligula blandit ut. Curabitur consequat purus id efficitur dapibus.

Ut accumsan, mauris non iaculis eleifend, orci odio dapibus augue, sed congue lectus nunc ac elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque neque ante, lobortis quis magna in, accumsan sollicitudin est. Sed elementum pulvinar sodales. Ut posuere tristique tellus, sed aliquam magna feugiat in. Phasellus fermentum pharetra magna vitae consequat. Curabitur finibus magna sagittis tortor condimentum tempor. Proin semper suscipit sollicitudin. Mauris porttitor enim vitae euismod tempor. Vivamus vulputate tortor quam, pretium lacinia nisl euismod et. Vestibulum eu leo id justo accumsan porttitor. Mauris eu pretium orci, sit amet aliquam diam. Mauris purus erat, pretium at sagittis ut, tempus nec lorem. Curabitur diam mi, pretium et rhoncus eu, efficitur id tellus.

Nunc tempus cursus sem, in lacinia felis suscipit semper. Nulla malesuada augue ipsum, in egestas velit varius id. Sed risus nisi, sollicitudin eu massa sit amet, rhoncus gravida sapien. Pellentesque ante massa, porta non erat vitae, elementum elementum velit. Sed elementum felis in est mollis, in faucibus lorem fermentum. Suspendisse tincidunt quam nulla, mattis euismod urna laoreet eget. Vestibulum sagittis augue fermentum dui porta convallis. Cras posuere placerat mattis. Fusce vel tempus elit. Quisque pellentesque neque augue. Donec nec ipsum vestibulum, lacinia enim a, vulputate risus. Quisque faucibus quis urna at fermentum. Pellentesque ut metus lorem. Fusce faucibus vitae lectus eu ultrices. Morbi sagittis scelerisque blandit. Proin lacinia erat eros, in lacinia ipsum gravida et.

Nulla rhoncus quam odio, vitae mollis libero faucibus rhoncus. Mauris varius gravida justo. Proin dapibus lectus in neque mattis, id fringilla leo pellentesque. Nulla tristique commodo massa, a bibendum ex vestibulum a. Ut congue porttitor lobortis. Pellentesque quis interdum mauris, ac lobortis diam. Quisque vel enim molestie enim hendrerit vehicula sed non ex. Duis ullamcorper, tellus ut consectetur porta, eros dolor aliquet nisl, eget tincidunt quam nibh vitae elit. Vivamus ac odio sed nisl fringilla consequat quis et tortor. Curabitur sem ex, varius ullamcorper sollicitudin et, gravida at tortor. Nam condimentum vehicula dui at dapibus.

Donec ultrices consequat fringilla. Sed lorem tortor, euismod eget interdum eu, hendrerit eget tortor. Aliquam eu quam vitae ex dapibus dictum. Nunc sit amet eleifend velit, ac placerat nibh. Duis rutrum orci eget porttitor mattis. Duis vel iaculis nibh, a ultricies orci. Donec leo enim, sagittis id ipsum vel, sagittis aliquam sem. Phasellus nec neque ac turpis posuere tempor. Nullam accumsan erat a bibendum cursus. Aenean ac urna hendrerit, scelerisque felis venenatis, iaculis odio. Vestibulum rutrum, lectus a imperdiet semper, nisi arcu vulputate lorem, eu eleifend nunc ex porta dui. Morbi eleifend ex id sem iaculis lobortis.

In quis dignissim felis. Donec neque lacus, iaculis quis quam vel, facilisis lobortis nulla. Cras volutpat non mauris consequat bibendum. Pellentesque sodales, sapien ut auctor mollis, mi mauris feugiat velit, ut auctor ex urna ac leo. Suspendisse potenti. Fusce ultricies blandit interdum. Praesent tempor augue luctus justo venenatis, in dictum magna dignissim. Nulla in nisl elit. Aenean sem dolor, elementum at dolor ac, commodo pulvinar metus. Suspendisse potenti. Morbi posuere interdum arcu quis ultrices. Morbi faucibus eleifend nisi non tincidunt.

Aenean porttitor posuere tincidunt. In rhoncus posuere massa, id commodo libero auctor in. Quisque gravida molestie ex in congue. Duis id venenatis felis. Vivamus accumsan eu tellus at auctor. Curabitur fringilla sollicitudin nunc, nec ornare erat eleifend ut. Sed non est dignissim, hendrerit mauris quis, molestie lacus. Pellentesque turpis lorem, elementum ac velit id, ullamcorper aliquet mi. Sed pharetra tellus purus, eu lacinia nisl sollicitudin at. Etiam placerat pulvinar metus, vel finibus augue consectetur eu. Nulla ac massa non ligula ultricies sollicitudin.

Praesent fermentum non sem scelerisque vestibulum. Ut felis lectus, bibendum sit amet eleifend in, pretium volutpat sem. Fusce eget nisl at augue scelerisque semper. Vivamus pellentesque vitae odio nec hendrerit. Integer vulputate arcu ac dui consequat dictum. Donec sed molestie odio. Sed auctor lacus arcu, a pellentesque ante blandit vitae. Morbi vitae ex porta, aliquet lorem vitae, blandit libero. Nam aliquet est dolor, in posuere erat tempor quis. Vivamus tempor vulputate enim rhoncus accumsan. Phasellus sed tincidunt neque.

Fusce finibus lorem a enim mattis hendrerit. Quisque rhoncus quis nisi ac elementum. Nam tincidunt augue et dui faucibus, et maximus augue ultricies. Etiam laoreet leo felis, quis varius nibh interdum nec. Nullam a molestie augue. Vivamus convallis mattis neque, nec lobortis enim tincidunt vitae. Curabitur auctor diam faucibus vehicula pretium. Morbi commodo mi vel nulla consequat malesuada. Quisque auctor varius libero, sed imperdiet nisl. Mauris commodo mi scelerisque felis malesuada mollis. Maecenas scelerisque eros quis ipsum scelerisque venenatis. Ut iaculis vel dui quis laoreet. Donec vel neque suscipit, posuere neque nec, hendrerit justo. Curabitur at augue ut mi ornare semper ac in lectus. Nunc quis magna placerat lacus lobortis volutpat.

Nulla facilisis aliquam nibh, nec accumsan neque mollis eu. Aenean diam leo, rutrum ut sem ut, varius imperdiet tellus. Aenean a massa sem. Donec nec nunc maximus, cursus lectus at, aliquet nibh. Nam et eleifend nibh. Pellentesque ut tellus ac odio pretium faucibus. Duis pretium nisi augue, a gravida eros convallis at. Aenean et odio id ex imperdiet pharetra. In varius odio vel dui interdum mattis. Aliquam interdum leo ut eros aliquet auctor. In hac habitasse platea dictumst. Ut porttitor, neque eu suscipit tincidunt, purus nibh molestie dolor, non congue massa magna in lectus. Nam vulputate sed lacus at iaculis. Cras enim lacus, facilisis ut mattis in, bibendum et magna. Curabitur egestas nisl nec felis accumsan, at volutpat arcu ullamcorper. Cras ac leo ex.

Nulla justo mauris, posuere a massa eget, hendrerit suscipit quam. Suspendisse ac enim ante. Sed rutrum ligula in mollis ullamcorper. Cras posuere nisl auctor mattis sagittis. Praesent id nibh in dui convallis sagittis id ullamcorper elit. Vivamus sed vulputate urna, eget scelerisque neque. Integer pharetra purus sit amet risus malesuada egestas. Donec vehicula ornare est nec convallis. Curabitur ac est sit amet nisl tempor aliquam vitae vitae turpis. Quisque bibendum sagittis orci.

In ultrices justo et mollis vehicula. Mauris ultrices lobortis odio vel dapibus. Duis massa ipsum, maximus et bibendum vel, fringilla sit amet ligula. Aliquam sapien diam, varius id blandit scelerisque, dapibus eget nunc. Fusce semper nisi sed leo lobortis varius. Mauris auctor, lorem et consectetur pulvinar, tortor orci finibus urna, vitae malesuada nibh ex ut mi. Integer pellentesque luctus ante, non finibus sapien faucibus sed. Aenean gravida elit massa, quis pellentesque nisi eleifend vel.

Morbi mollis odio diam, vitae sagittis ante pretium non. Nam congue cursus euismod. Duis nec ornare turpis. Ut id ipsum velit. Aenean odio mauris, hendrerit interdum hendrerit ac, viverra vel lorem. Donec arcu elit, malesuada a risus quis, vestibulum suscipit dolor. Praesent efficitur metus urna, sit amet blandit odio eleifend sed. Morbi sagittis diam urna, placerat convallis elit fermentum nec. Pellentesque vitae maximus nisl. Sed a pretium sapien. Aliquam id scelerisque erat. Cras luctus, odio vel scelerisque aliquet, quam nibh mollis massa, non finibus metus est quis odio.

**Comment by apelisse** [comment]
Would it make sense to just hide the biggest part of the message under \<detail\>?

**Comment by apelisse** [comment]
Does [this](https://github.com/kubernetes/kubernetes/pull/43096#issuecomment-286564463) look better? We still have to somehow update the message in case the file list has changed.

**Comment by apelisse** [comment]
@ixdy @spxtr

**Comment by ixdy** [comment]
Does it need to comment if it's approved? IMO the only time it should comment is if there's some action a human needs to make. (We don't make a comment when all tests pass, for comparison.)

**Comment by apelisse** [comment]
Yeah I think it's nice to be able to check who has approved what. Should we add a new comment when it's not approved, and edit the last comment when it's finally approved?

**Comment by spxtr** [comment]
Nice, the `<details>` bit makes it a lot better.

I still agree with Jeff that if there is no action for a human to take then it should make no comment/delete the old comment.

**Comment by grodrigues3** [comment]
It's hard to notice a comment that was edited vs deleting the old one and creating a new one.  I think the new comment style is much less noisy and I'm fine with it as is
