### ISSUE TITLE
Cannot visit prow dashboard via ingress after installing prow in GKE

### ISSUE THREAD

**Issue by wewang58** [kubernetes/test-infra#22154]
**What would you like to be added:**
Cannot  visit prow deck after installing prow with the command "bazel run //prow/cmd/tackle", according to https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#tackle-deployment, Should need other steps?

**Why is this needed:**
Can visit prow dashboard via ingress.

Here's log: 
```
Type the name of any zone, including ones not in this truncated list
Select zone [us-east1-b]: 
WARNING: If `--issue-client-certificate` is specified but `--enable-basic-auth` or `--username` is not, our API will treat that as `--no-enable-basic-auth`.
WARNING: Starting in January 2021, clusters will use the Regular release channel by default when `--cluster-version`, `--release-channel`, `--no-enable-autoupgrade`, and `--no-enable-autorepair` flags are not specified.
WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Starting with version 1.18, clusters will have shielded GKE nodes by default.
WARNING: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s). 
WARNING: Starting with version 1.19, newly created clusters and node-pools will have COS_CONTAINERD as the default node image when no image type is specified.
Creating cluster wewang-prow in us-east1-b... Cluster is being health-checked (master is healthy)...done.                                                                                                                                    
Created [https://container.googleapis.com/v1/projects/wewang-312207/zones/us-east1-b/clusters/wewang-prow].
To inspect the contents of your cluster, go to: https://console.cloud.google.com/kubernetes/workload_/gcloud/us-east1-b/wewang-prow?project=wewang-312207
kubeconfig entry generated for wewang-prow.
NAME         LOCATION    MASTER_VERSION   MASTER_IP      MACHINE_TYPE  NODE_VERSION     NUM_NODES  STATUS
wewang-prow  us-east1-b  1.18.17-gke.100  34.xx.196.xxx  e2-medium     1.18.17-gke.100  3          RUNNING
Applying admin role bindings (to create RBAC rules)...
W0512 16:33:24.922512   17563 helpers.go:567] --dry-run=true is deprecated (boolean value) and can be replaced with --dry-run=client.
clusterrolebinding.rbac.authorization.k8s.io/prow-admin created
Deploying prow...

Apply starter.yaml from [github upstream]: /home/wewang/work/qe-ci-bot/starter-s3.yaml
namespace/prow created
configmap/plugins created
secret/github-token created
secret/hmac-token created
configmap/config created
customresourcedefinition.apiextensions.k8s.io/prowjobs.prow.k8s.io created
deployment.apps/hook created
service/hook created
deployment.apps/sinker created
deployment.apps/deck created
service/deck created
deployment.apps/horologium created
deployment.apps/tide created
service/tide created
ingress.extensions/prow created
deployment.apps/statusreconciler created
namespace/test-pods created
serviceaccount/deck created
rolebinding.rbac.authorization.k8s.io/deck created
rolebinding.rbac.authorization.k8s.io/deck created
role.rbac.authorization.k8s.io/deck created
role.rbac.authorization.k8s.io/deck created
serviceaccount/horologium created
role.rbac.authorization.k8s.io/horologium created
rolebinding.rbac.authorization.k8s.io/horologium created
serviceaccount/sinker created
role.rbac.authorization.k8s.io/sinker created
role.rbac.authorization.k8s.io/sinker created
rolebinding.rbac.authorization.k8s.io/sinker created
rolebinding.rbac.authorization.k8s.io/sinker created
serviceaccount/hook created
role.rbac.authorization.k8s.io/hook created
rolebinding.rbac.authorization.k8s.io/hook created
serviceaccount/tide created
role.rbac.authorization.k8s.io/tide created
rolebinding.rbac.authorization.k8s.io/tide created
serviceaccount/statusreconciler created
role.rbac.authorization.k8s.io/statusreconciler created
rolebinding.rbac.authorization.k8s.io/statusreconciler created
persistentvolumeclaim/ghproxy created
deployment.apps/ghproxy created
service/ghproxy created
deployment.apps/prow-controller-manager created
serviceaccount/prow-controller-manager created
role.rbac.authorization.k8s.io/prow-controller-manager created
role.rbac.authorization.k8s.io/prow-controller-manager created
rolebinding.rbac.authorization.k8s.io/prow-controller-manager created
rolebinding.rbac.authorization.k8s.io/prow-controller-manager created
deployment.apps/crier created
serviceaccount/crier created
role.rbac.authorization.k8s.io/crier created
role.rbac.authorization.k8s.io/crier created
rolebinding.rbac.authorization.k8s.io/crier created
rolebinding.rbac.authorization.k8s.io/crier created
persistentvolumeclaim/minio created
secret/s3-credentials created
secret/s3-credentials created
deployment.apps/minio created
service/minio created
Checking github credentials...
Store your GitHub token in a file e.g. echo $TOKEN > /path/to/github/token
Input /path/to/github/token to upload into cluster: /home/wewang/work/qe-ci-bot/token
INFO[0728] User()                                        client=github
Prow will act as qe-robot on github
Applying github token into oauth-token secret...W0512 16:46:16.589060   20497 helpers.go:567] --dry-run=true is deprecated (boolean value) and can be replaced with --dry-run=client.
secret/oauth-token created
Ensuring hmac secret exists at hmac-token...INFO[0733] Creating new hmac-token secret with random data... 
exists
Looking for prow's hook ingress URL... ...................................................................................................................................................................................................^C
```
And get ingress url, no address, also cannot visit prow.wewang.com url.
[root@wangwen test-infra]# kubectl get pod -n prow
NAME                                      READY   STATUS    RESTARTS   AGE
crier-59d977c755-dwtb2                    1/1     Running   0          3m53s
deck-989c4d99d-7f64v                      1/1     Running   0          4m20s
deck-989c4d99d-zljrk                      1/1     Running   0          4m20s
ghproxy-55479476b8-gmvkz                  1/1     Running   0          4m2s
hook-6dbb8ffc4f-jqqq8                     1/1     Running   0          3m52s
hook-6dbb8ffc4f-m8krn                     1/1     Running   0          3m52s
horologium-59749bcb4f-lvv8b               1/1     Running   0          4m18s
minio-5b4b6bc44b-vzn9z                    1/1     Running   0          3m46s
prow-controller-manager-67fdb76b4-lchsx   1/1     Running   0          3m59s
sinker-6c5c5f44fd-nrv4j                   1/1     Running   0          4m11s
statusreconciler-869cd9449d-c484t         1/1     Running   0          4m4s
tide-798b9f98fb-cp2hn                     1/1     Running   3          4m7s
[root@wangwen test-infra]# kubectl get ingress -n prow
NAME   CLASS    HOSTS             ADDRESS   PORTS   AGE
prow   <none>   prow.wewang.com             80      4m38s

# kubectl logs -f pod/deck-989c4d99d-7f64v -n prow
time="2021-05-12T10:07:22Z" level=info msg="Spyglass registered viewer buildlog with title Build Log."
time="2021-05-12T10:07:22Z" level=info msg="Spyglass registered viewer coverage with title Coverage."
time="2021-05-12T10:07:22Z" level=info msg="Spyglass registered viewer html with title HTML."
time="2021-05-12T10:07:22Z" level=info msg="Spyglass registered viewer junit with title JUnit."
time="2021-05-12T10:07:22Z" level=info msg="Spyglass registered viewer links with title Debugging links."
time="2021-05-12T10:07:22Z" level=info msg="Spyglass registered viewer metadata with title Metadata."
time="2021-05-12T10:07:22Z" level=info msg="Spyglass registered viewer podinfo with title Job Pod Info."
time="2021-05-12T10:07:22Z" level=info msg="Spyglass registered viewer restcoverage with title REST API coverage report."
{"component":"deck","file":"prow/kube/config.go:87","func":"k8s.io/test-infra/prow/kube.LoadClusterConfigs","level":"info","msg":"Loading cluster contexts...","severity":"info","time":"2021-05-12T10:07:22Z"}
{"client":"github","component":"deck","file":"prow/github/client.go:719","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"User()","severity":"info","time":"2021-05-12T10:07:22Z"}
{"Lens":"metadata","component":"deck","file":"prow/spyglass/lenses/common/common.go:66","func":"k8s.io/test-infra/prow/spyglass/lenses/common.NewLensServer","level":"info","msg":"Adding handler for lens","severity":"info","time":"2021-05-12T10:07:22Z"}
{"Lens":"buildlog","component":"deck","file":"prow/spyglass/lenses/common/common.go:66","func":"k8s.io/test-infra/prow/spyglass/lenses/common.NewLensServer","level":"info","msg":"Adding handler for lens","severity":"info","time":"2021-05-12T10:07:22Z"}
{"Lens":"junit","component":"deck","file":"prow/spyglass/lenses/common/common.go:66","func":"k8s.io/test-infra/prow/spyglass/lenses/common.NewLensServer","level":"info","msg":"Adding handler for lens","severity":"info","time":"2021-05-12T10:07:22Z"}
{"Lens":"podinfo","component":"deck","file":"prow/spyglass/lenses/common/common.go:66","func":"k8s.io/test-infra/prow/spyglass/lenses/common.NewLensServer","level":"info","msg":"Adding handler for lens","severity":"info","time":"2021-05-12T10:07:22Z"}
{"agent":"tide","component":"deck","error":"Get \"http://tide/\": dial tcp 10.15.255.xx:80: connect: connection refused","file":"prow/cmd/deck/tide.go:122","func":"main.fetchTideData","level":"info","msg":"Failed 3 retries fetching Tide data before success: Get \"http://tide/\": dial tcp 10.15.255.xx:80: connect: connection refused.","severity":"info","time":"2021-05-12T10:09:09Z"}

**Comment by wewang58** [comment]
@BenTheElder  Hi, if I visit a domain(prow.wewang.com) in GKE cluster, still need do others like kind cluster? can you guide me how to do, or others can guide me, thanks so much.

**Comment by BenTheElder** [comment]
/area prow
/kind support

Sorry I don't really work on prow anymore and I don't have time to debug this for you at the moment. The prow docs should cover this setup.

**Comment by chaodaiG** [comment]
I believe tackle uses either `starter_gcs.yaml` or `starter_s3.yaml` as documented https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#update-the-sample-manifest, and I'm afraid that they have been out of sync with some of the recent improvements/bug fixes/deprecations. Add @cjwagner and @alvaroaleman for more insights

**Comment by alvaroaleman** [comment]
This all is way too little information and this is more about generic kube debugging than Prow specifically.

1. Is there a running deck pod?
2. Is there a deck service and does it have endpoints?
3. Is there an ingress that points to the deck service?
4. Does your DNS correctly point to the address of the Ingress?

**Comment by cjwagner** [comment]
There does appear to be a running deck pod based on the output you shared, but otherwise we'd still need the rest of the data Alvaro requested. I also agree that this is more generic kube debugging rather than a Prow question.
You could also try to use `kubectl proxy` or a `curl` pod to access deck. Whether or not that works could tell you something. https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls

**Comment by wewang58** [comment]
> This all is way too little information and this is more about generic kube debugging than Prow specifically.
> 
> 1. Is there a running deck pod?
> 2. Is there a deck service and does it have endpoints?
> 3. Is there an ingress that points to the deck service?
> 4. Does your DNS correctly point to the address of the Ingress?

1. Yes, there's a deck pod
# kubectl get pods -n prow
NAME                                      READY   STATUS    RESTARTS   AGE
crier-59d977c755-bn4f4                    1/1     Running   0          4m2s
deck-989c4d99d-8dkz8                      1/1     Running   0          4m28s
deck-989c4d99d-fkjgc                      1/1     Running   0          4m28s
ghproxy-55479476b8-6hppb                  1/1     Running   0          4m10s
hook-6dbb8ffc4f-7m7hc                     1/1     Running   0          4m1s
hook-6dbb8ffc4f-9p4t9                     1/1     Running   0          4m1s
horologium-59749bcb4f-dwm9p               1/1     Running   0          4m27s
minio-5b4b6bc44b-62z2h                    1/1     Running   0          3m55s
prow-controller-manager-67fdb76b4-g8zh5   1/1     Running   0          4m7s
sinker-6c5c5f44fd-bqrn5                   1/1     Running   0          4m19s
statusreconciler-869cd9449d-kndd7         1/1     Running   0          4m12s
tide-798b9f98fb-c4722                     1/1     Running   2          4m15s

2.  and deck service has endpoints
# kubectl get svc -n prow
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
deck      ClusterIP   10.xx.253.71    <none>        80/TCP            11m
ghproxy   ClusterIP   10.xx.250.xx  <none>        80/TCP,9090/TCP   10m
hook      ClusterIP   10.xx.250.xx    <none>        8888/TCP          11m
minio     ClusterIP   10.xx.249.xx   <none>        80/TCP            10m
tide      ClusterIP   10.xx.245.xx    <none>        80/TCP            10m
# kubectl describe svc/deck -n prow
Name:              deck
Namespace:         prow
Labels:            <none>
Annotations:       <none>
Selector:          app=deck
Type:              ClusterIP
IP:                10.xx.253.71
Port:              <unset>  80/TCP
TargetPort:        8080/TCP
Endpoints:         10.xx.0.4:8080,10.xx.1.8:8080
Session Affinity:  None
Events:            <none>

3.  there's an ingress points to the deck service, but said type of service should be "NodePort" or "LoadBalancer"
# kubectl get ingress -n prow
NAME   CLASS    HOSTS             ADDRESS   PORTS   AGE
prow   <none>   prow.wewang.com             80      13m

# oc describe ingress/prow -n prow
Name:             prow
Namespace:        prow
Address:          
Default backend:  deck:80 (10.xx.0.4:8080,10.xx.1.8:8080)
Rules:
  Host             Path  Backends
  ----             ----  --------
  prow.wewang.com  
                   /       deck:80 (10.xx.0.4:8080,10.xx.1.8:8080)
                   /hook   hook:8888 (10.xx.0.3:8888,10.xx.2.8:8888)
Annotations:       cert-manager.io/cluster-issuer: letsencrypt-staging
Events:
  Type     Reason     Age                  From                     Message
  ----     ------     ----                 ----                     -------
  Normal   Sync       2m4s (x4 over 13m)   loadbalancer-controller  Scheduled for sync
  Warning  Translate  2m4s (x19 over 13m)  loadbalancer-controller  Translation failed: invalid ingress spec: service "prow/deck" is type "ClusterIP", expected "NodePort" or "LoadBalancer"; service "prow/hook" is type "ClusterIP", expected "NodePort" or "LoadBalancer"; service "prow/deck" is type "ClusterIP", expected "NodePort" or "LoadBalancer"
 
4. Does your DNS correctly point to the address of the Ingress?
Sorry, about the question, I don't know how to check it?

**Comment by wewang58** [comment]
Fyi, after kubectl proxy, can access proxy url, here are steps:
# kubectl cluster-info
Kubernetes master is running at https://34.xxx.xx.111
GLBCDefaultBackend is running at https://34.xx.xx.111/api/v1/namespaces/kube-system/services/default-http-backend:http/proxy
KubeDNS is running at https://34.xx.xx.111/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://34.xx.xx.111/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

#  kubectl proxy
Starting to serve on 127.0.0.1:8001

In another terminal, curl proxy url
#  curl http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/default-http-backend:http/proxy
# echo $?
0

**Comment by spiffxp** [comment]
/close
Please reopen if you have more information to provide.  We generally don't handle support requests here and encourage discussion on kubernetes.slack.com in the #prow channel.

**Comment by luukasmakila** [comment]
@wewang58 did you ever fix this?
