### ISSUE TITLE
Can we support ginkgo flag -untilItFails ?

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/test-infra#2217]
I want to run a e2e test until it fails, but found that the current e2e framework does not support the -untilItFails flag of ginkgo.
error:
Mar 10 23:27:56.452: INFO: Overriding default scale value of zero to 1
Mar 10 23:27:56.452: INFO: Overriding default milliseconds value of zero to 5000
flag provided but not defined: -ginkgo.untilItFails

**Comment by ixdy** [comment]
What command did you use to run tests?

**Comment by wanghaoran1988** [comment]
@ixdy go run hack/e2e.go -- -v --test --test_args="--ginkgo.focus=.*Pod.*should.*avoid.*to.*annotation.*  --ginkgo.untilItFails=true"

**Comment by wanghaoran1988** [comment]
close this, let's track here: https://github.com/kubernetes/kubernetes/issues/43026

**Comment by bsalamat** [comment]
Sorry, I didn't see this issue earlier. Otherwise, I wouldn't have created a duplicate.

**Comment by wanghaoran1988** [comment]
@bsalamat It really doesn't matter, cause in the different repo.
