### ISSUE TITLE
support github patch service https://ghproxy.com/https://patch-diff.githubusercontent.com/raw/jupyterlab/nbclassic/pull/52.patch

### ISSUE THREAD

**Issue by cailiang9** [kubernetes/test-infra#22201]
**What would you like to be added**:
support github patch service: https://ghproxy.com/https://patch-diff.githubusercontent.com/raw/jupyterlab/nbclassic/pull/52.patch

**Why is this needed**:
pull requests often need long time to be merged and released.  Sometimes PR can also be rejected.
using patch-diff service can speedup debugging and packaging based existing releases , for temporarily use.

**Comment by cailiang9** [comment]
NOT very sure if the request is posted at the right place. I mean the ghproxy.com could support this patch-diff endpoint.

**Comment by alvaroaleman** [comment]
Sorry, I don't understand what exactly you want to be changed where.

What should support the github patch service and what difference in behavior do you want to see after that support was added?

**Comment by cailiang9** [comment]
I want to wget https://patch-diff.githubusercontent.com/raw/jupyterlab/nbclassic/pull/52.patch but obviously blocked.
So can ghproxy.com support this so I can wget through https://ghproxy.com/https://patch-diff.githubusercontent.com/raw/jupyterlab/nbclassic/pull/52.patch ?

**Comment by BenTheElder** [comment]
> So can ghproxy.com support this so I can wget through https://ghproxy.com/https://patch-diff.githubusercontent.com/raw/jupyterlab/nbclassic/pull/52.patch ?

Ah, bit of confusion here: 

This repo has no involvement with https://ghproxy.com/

There is a different GitHub-API caching proxy implemented and used by `prow/` in this repo to avoid wasting repeated API calls (and therefore ratelimit) on cacheable results. It is not a user facing proxy.

Per the https://ghproxy.com/ footer, you want https://github.com/hunshcn/gh-proxy ("Github Project : hunshcn/gh-proxy")

**Comment by crn420** [comment]
https://patch-diff.githubusercontent.com/raw/automerge/automerge/pull/350.patch
