### ISSUE TITLE
after a push to an approved/lgtm'd branch, Prow auto-merges before github actions restarts

### ISSUE THREAD

**Issue by starpit** [kubernetes/test-infra#22231]
**What happened**:

https://github.com/kubernetes-sigs/kui/pull/7412

1) A branch with github actions test failures; but was approved and lgtmd.
2) Prow correctly does not merge, because of the failed test
3) Push update to branch
4) Briefly, github removes the actions failure/pending from the Checks!
5) Prow comes along and notices no unsatisfied checks, and auto-merges!

**What you expected to happen**:

Prow should not auto-merge, especially since we have indicated in our yaml entry for Kui that github actions is a merge prereq. The absence of any github actions checks (at all, which is our state 4) should indicate a do-not-merge state.

**How to reproduce it (as minimally and precisely as possible)**:

See the list above.

**Please provide links to example occurrences, if any**:

This has happened twice to us:

https://github.com/kubernetes-sigs/kui/pull/7304
https://github.com/kubernetes-sigs/kui/pull/7412

**Anything else we need to know?**:

n/a

**Comment by myan9** [comment]
our yaml entry in config: https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L579

**Comment by starpit** [comment]
Oh! So we don't have a merge prereq entry?

**Comment by BenTheElder** [comment]
> Briefly, github removes the actions failure/pending from the Checks!

Prow can't do much about that, if you want the checks to be explicitly required even when they are no present as a visible status you need to tell prow / explicitly configure the checks to be required.

Otherwise for all it knows the check was actually removed.

**Comment by starpit** [comment]
This makes sense. Is there an agreeable syntax for github actions status checks? It's a bit hard to intuit from github's UI. Is the prefix "test/" or "test /"? Or ... is there no standard prefix, and we have to hard-code the names of each of our github actions workflows?

For PRs in progress, we see "test / <workflow name>"; but for completed/merged PRs, the github UI just specifies the workflow name for each Check. Weird.

**Comment by BenTheElder** [comment]
> Or ... is there no standard prefix, and we have to hard-code the names of each of our github actions workflows?

I'm not sure tbh, prow can be configured to require github statuses but there's nothing specific to actions and I'm not sure how actions names them, nominally prow is designed to be used as the full CI system.

**Comment by alvaroaleman** [comment]
@starpit the name Prow sees is the name without the `test / ` prefix (that is the name of the suite), you can see it e.G. here: https://github.com/kubernetes-sigs/kui/runs/2613597850

The definitive way to see the same information as Prow does is to query the github api. You can use `curl` for that:
```bash
$ curl -Ss https://api.github.com/repos/kubernetes-sigs/kui/commits/2b221054ab88cca2c8d8f638b2ed53081f4a4592/check-runs|jq '.check_runs[]|.name'
"osx (12.x)"
"k8s-electron (12.x)"
"k8s-chaos (12.x)"
"k8s-browser (12.x)"
"bash-core-browser (12.x)"
"api-electron (12.x)"
"api-browser (12.x)"
"bash-electron (12.x)"
```

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/20713
