### ISSUE TITLE
Prow issue:

### ISSUE THREAD

**Issue by 00void00** [kubernetes/test-infra#22246]
Since, I am using the free tier, we will not pass the preflight checks, the preflight status. So, what I did was, I tried suppress those errors and those warnings using --ignore-preflight-errors=

but the error exists

**Comment by BenTheElder** [comment]
> Prow issue:
> Since, I am using the free tier, we will not pass the preflight checks, the preflight status.

Prow is not a paid service. There is no paid tier. Are you talking about something else ...?

> So, what I did was, I tried suppress those errors and those warnings using --ignore-preflight-errors=

`--ignore-preflight-errors` is a [kubeadm](https://github.com/kubernetes/kubeadm) flag. 
kubeadm is also not something with a paid tier.

> but the error exists

What error?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubeadm/issues/2479 duplicate issue. This issue is not related to prow and is not appropriate for this repo.
