### ISSUE TITLE
Objectively measure per-cloud-provider test setup quality

### ISSUE THREAD

**Issue by erictune** [kubernetes/test-infra#2224]
It seems like many flakes that create issues in http:///github.com/kubernetes/kubernetes are in fact test setup failures.

We should measure test setup quality reliability in a way that is independent of the actual test code.  
One possible implementation would be to have a test job that does cluster setup and tear down, but no test cases.  

Exactly how many of these to have is something that needs to be determined.  We probably need at least one per `KUBERNETES_PROVIDER` to start with.

Two things to do with this:

- if these fail often, then we need to ask the owner for the KUBERNETES_PROVIDER code to make it more reliable.
- when one of these fails, it is a strong signal that we don't want to file bugs for other test jobs at this same PR

@grodrigues3 @mtaufen

**Comment by spxtr** [comment]
I looked over a handful of flakes in the pull-kubernetes-e2e-gce-etcd3 suite, which is one of our flakiest. Only one would have been caught by a simple cluster setup and teardown.

* `Up` failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42988/pull-kubernetes-e2e-gce-etcd3/22043/
* `Test` failed, whatever that means: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42851/pull-kubernetes-e2e-gce-etcd3/21975
* `Test` failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42981/pull-kubernetes-e2e-gce-etcd3/22012/
* A few seemingly unrelated tests failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42854/pull-kubernetes-e2e-gce-etcd3/22034/
* Beforesuite: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42906/pull-kubernetes-e2e-gce-etcd3/22068/
* DNS failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42906/pull-kubernetes-e2e-gce-etcd3/22055/

**Comment by fejta** [comment]
Two pieces to this:
1) ensure that kubetest writes the --provider=FOO value into metadata.json
2) Add a https://github.com/kubernetes/test-infra/tree/master/metrics config which graphs Up for various jobs
3) Add this to velodrome

Will close this in 1.8 if it doesn't attract any interest/ownership
