### ISSUE TITLE
Fix Build Log Regex

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2225]
As I'm going through test flakes and trying to triage, I'm reviewing some of the build logs.  It's annoying to see things [like](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/789/?log#log):

`I0309 02:26:31.381] Mar  9 02:26:31.380: INFO: The status of Pod heapster-v1.3.0-beta.1-2135351031-t5hng is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed`

highlighted over and over.  The log level is info.  Can we change the regex or whatever does the highlighting to be a little smarter.

**Comment by fejta** [comment]
/area gubernator
/assign @kargakis @rmmh 

Fixed this regex a bit
