### ISSUE TITLE
tot: vended ID overflows int64

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#22256]
Found this issue in our logs:

```
unrecognized file name (expected <int64>.txt): pr-logs/directory/pull-ci-openshift-installer-master-e2e-crc/13728953029057617923.txt
```

This value overflows int64

**Comment by matthyx** [comment]
I think the fix would be to use `strconv.ParseUint` instead:
https://github.com/kubernetes/test-infra/blob/3efe91b8cdbf4a597b73d8547b62ddc522f9848b/prow/cmd/deck/job_history.go#L260

**Comment by matthyx** [comment]
/assign
This issue is being worked on by Mariana B.

**Comment by matthyx** [comment]
> @matthyx: GitHub didn't allow me to assign the following users: marianabocoi.
> 
> Note that only [kubernetes members](https://github.com/orgs/kubernetes/people), repo collaborators and people who have commented on this issue/PR can be assigned. Additionally, issues/PRs can only have 10 assignees at the same time.
> For more information please see [the contributor guide](https://git.k8s.io/community/contributors/guide/first-contribution.md#issue-assignment-in-github)

ah yeah, always forget this one...
/cc @marianabocoi

**Comment by marianabocoi** [comment]
Should this issue be closed? How do we check all is well now?
Poke @matthyx @BenTheElder @stevekuznetsov

/honk

**Comment by matthyx** [comment]
I think it won't close as an afterthought.
/close
