### ISSUE TITLE
Feature request: Track the order that tests ran in on a given node

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/test-infra#2226]
This would be useful for determining which tests interfere with other tests.

For example, some of the reboot tests do especially ugly things to take down a node (crash via intentional kernel panic, hard reboot, etc), and these can cause corruption that affects subsequent tests.

It would be *especially* useful to see failure rates for given orderings on go.k8s.io/triage.

**Comment by fejta** [comment]
/remove-area gubernator
/area testgrid
/unassign
/assign @michelle192837 

Maybe a sort by start time on testgrid?

**Comment by michelle192837** [comment]
Sorry, going through issues more now. I think this would be a good feature, just need to find time to add it. Some other metrics are also possible considerations for sorting, and I believe there has been some discussion on broadly allowing a customizable sort in the configuration, based on metrics reported from test logs.
