### ISSUE TITLE
Reset Kubernetes Prow PR Status token

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#22286]
From GitHub:
```
We noticed that an application, Kubernetes Prow PR Status, owned by an organization you are an admin of, kubernetes, used a token with an outdated format to access the GitHub API on May 20th, 2021 at 05:42 (UTC), with a user-agent header of deck.rerun/v20210519-86db8373d6.

In order to provide additional security benefits to all our customers, we recently updated the format of our API authentication tokens. We encourage you to reset any authentication tokens used by this app, as well as tokens used by any other apps you may have, with our reset token API.

Alternatively, you can prompt your users to step through the authorization flow again, as outlined in the docs for either GitHub Apps and OAuth Apps.

To understand more about this change and why it's important, visit https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats.

Thanks,
The GitHub Team
```

No rush on this (there is no security vulnerability, we're just using the old format), but could someone have a look at resetting our token?

**Comment by spiffxp** [comment]
/sig testing
/assign @cblecker 
are we still seeing this?
/assign @chaodaiG 
current test-infra-oncall, can you take a look at the token real quick and confirm whether we're still using an old format token?

**Comment by chaodaiG** [comment]
the token used in `deck` is called `oauth-token`, and value doesn't have any of the prefixes mentioned in https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/, so yes we are still on the old format
