### ISSUE TITLE
install_gcloud failing on kops/aws builds

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#2236]
Creating an issue to track this long standing problem.

Based on the command line, AFAICT, kops builds are using a different image - they do not have https://github.com/kubernetes/test-infra/pull/1657  So this may be fixed if we switch images.

Install gcloud fails with:

```
W0314 07:04:52.221] Performing post processing steps...
W0314 07:04:55.367] ............failed.
W0314 07:04:55.367] WARNING: Post processing failed.  Run `gcloud info --show-log` to view the failures.
W0314 07:04:55.367] 
W0314 07:04:55.367] Update done!
W0314 07:04:55.367] 
W0314 07:04:55.372] Traceback (most recent call last):
W0314 07:04:55.372]   File "//google-cloud-sdk/bin/bootstrapping/install.py", line 206, in <module>
W0314 07:04:55.372]     main()
W0314 07:04:55.373]   File "//google-cloud-sdk/bin/bootstrapping/install.py", line 191, in main
W0314 07:04:55.373]     sdk_root=bootstrapping.SDK_ROOT,
W0314 07:04:55.373] TypeError: UpdateRC() got an unexpected keyword argument 'completion_update'
I0314 07:04:55.473] 
I0314 07:04:55.474] This will install all the core command line tools necessary for working with
I0314 07:04:55.474] the Google Cloud Platform.
I0314 07:04:55.474] 
I0314 07:04:55.519] +++ exit code: 1
```

One possibility is that kubernetes_kops_aws.py has a different default tag:

kubernetes_kops_aws.py
```
PARSER.add_argument(
        '--tag', default='v20170207-9bbd5f41',
        help='Use a specific kubekins-e2e tag if set')
```

kubernetes.py
```
parser.add_argument(
        '--tag', default='v20170310-72232020', help='Use a specific kubekins-e2e tag if set')
```

cc @zmerlynn

**Comment by zmerlynn** [comment]
As predicted, someone bumped one of the tags without bumping the other. cc @krzyzacy - we need to figure out a way to get common constants at least between scenarios.

**Comment by krzyzacy** [comment]
that's that... hummm how to write the test for this

**Comment by fejta** [comment]
IMO shouldn't this be by design?

**Comment by fejta** [comment]
AKA if they are different scenarios we want the ability to update one image without impacting a different scenario we didn't test.

**Comment by krzyzacy** [comment]
@fejta we want to include the fix for gcloud update here though

**Comment by zmerlynn** [comment]
@fejta: We either need separate images entirely, in which case we should be using something other than the very difficult manual process we have, or we should be keeping things in lockstep. Until there's an automated build here and we can build images for different derivative easily (so e.g. we can have a base container and then spawn builds for all the remaining and bump tags), I don't think this is the right developer experience.

**Comment by krzyzacy** [comment]
aka kops image does not have https://github.com/kubernetes/test-infra/pull/1902 - I think the default tag should be the same, and we can allow overwrite tags, like https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L1582

**Comment by fejta** [comment]
Disagree the default should be the same until we have a way of testing it before updating the image.

**Comment by fejta** [comment]
IMO these should not be the same image, and these should not use the same version.

**Comment by zmerlynn** [comment]
Then we need automated build/test.

**Comment by zmerlynn** [comment]
I disagree with keeping them separate until that's done. :)

**Comment by fejta** [comment]
It isn't hard to build/test -- just create a canary job like we do for the main image.

Perhaps a good goal for 1.7 is to put all this into a single image and scenario?

**Comment by fejta** [comment]
Aka moving all the logic into kubetest

**Comment by zmerlynn** [comment]
Has the method for e2e image testing changed?

**Comment by fejta** [comment]
For the main image: commit code whenever you want, then when you're ready to release and image you make -C jenkins/e2e-image push && start the kubernetes-e2e-gce-canary job and wait for it to finish. If that works then you update the scenario label

**Comment by fejta** [comment]
This canary job does not cover the kops logic so this should not include updating the kops default label

**Comment by zmerlynn** [comment]
That's. ... not a good test. You're only testing GCE.

**Comment by zmerlynn** [comment]
The old PR builder test was much more coverage.

**Comment by zmerlynn** [comment]
There's way more than kops using the e2e-image with non-GCE logic.

**Comment by fejta** [comment]
Not really, the only difference between GKE and GCE is the environment variable you set.

**Comment by fejta** [comment]
The cluster it starts is dramatically difference but the kubekins delta is trivial

**Comment by fejta** [comment]
Basically 380 of our 400 e2e jobs just send slightly different env varibles to ginkgo and cluster up. We don't need to test all that nonsense before updating the image.

I'm not sure about the kops changes and what testing of that needs to happen to update the image.

**Comment by zmerlynn** [comment]
So why should the kops image not derive from a common base image? I feel like that forces everyone that comes along to build a new infrastructure from the ground up. And if you have a common base image, you need a better test.

**Comment by fejta** [comment]
It can, it just shouldn't update with the other images

**Comment by fejta** [comment]
(since the default test doesn't validate kops still works)

**Comment by fejta** [comment]
(also, note that we have some other jobs pinned to a specific image tag until after code freeze)

**Comment by krzyzacy** [comment]
It's possible to make a new kops-e2e image with https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/Dockerfile#L62, and move it out of kubekins-e2e

**Comment by zmerlynn** [comment]
@fejta: If you can't alter the base image and have the others pick up improvements, you have to file separate bugs / PRs like this one and everyone is solving the same problems multiple times.

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/5403

looks fine now

**Comment by justinsb** [comment]
Thank you all for fixing :-)
