### ISSUE TITLE
error running kubetest

### ISSUE THREAD

**Issue by SameerMahajan-GSLab** [kubernetes/test-infra#22378]
I followed instructions to run  kubetest. When I ran

bazel run //kubetest

**What happened**: I got an error stating

2021/06/01 05:52:36 main.go:327: Something went wrong: called from invalid working directory: must run from kubernetes directory root. current: /home/ubuntu/.cache/bazel/_bazel_ubuntu/0cf4f1410734a49015c86d59d449652a/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/bin/kubetest/kubetest_/kubetest.runfiles/io_k8s_test_infra

**What you expected to happen**: I was expecting kubetest to run

**How to reproduce it (as minimally and precisely as possible)**: Follow the instrctions

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
As the error says it must be called from the Kubernetes directory root. It's for testing Kubernetes. If you have some other use case I recommend https://github.com/kubernetes-sigs/kubetest2

Running under bazel is not going to work because the bazel sandbox interferes.

Note install instructions do not use bazel: https://github.com/kubernetes-sigs/kubetest2/blob/master/README.md

**Comment by SameerMahajan-GSLab** [comment]
@BenTheElder how exactly do I run it from kubernetes directory? When I run

bazel run //kubetest

from kubernetes folder I get error of:

ERROR: The 'run' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace

**Comment by BenTheElder** [comment]
> @BenTheElder how exactly do I run it from kubernetes directory? When I run

without bazel, bazel places it in the workspace. see installation guide in the README

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md

**Comment by BenTheElder** [comment]
I think https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md#installation and onwards covers this, feel free to reopen or file a new issue (or improve the docs!) if not.
