### ISSUE TITLE
/open to re-open issues

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2237]
Directly from a contributor:

> I did a bunch of /close and then I realized I had to reopen an issue -- apparently it's not possible?

@fejta

**Comment by dettervt** [comment]
If nobody wants to do this, I can.
It seems like it would just be a mirror of `prow/plugins/close`, and adding `OpenIssue` to `prow/github/client.go` with associated tests, right?

**Comment by spxtr** [comment]
Yep.

**Comment by grodrigues3** [comment]
@dettervt that'd be awesome.  Thanks

**Comment by dettervt** [comment]
Fixed in #2439 (and `commands.md` updated in #2497)

**Comment by cblecker** [comment]
/close
Thanks @dettervt :)

**Comment by cblecker** [comment]
/close
picky bot
