### ISSUE TITLE
Prow issue: Pods deployed through jenkins gets created in the kubernet cluster but gets terminated automatically.What may be the reason

### ISSUE THREAD

**Issue by rahul26ur** [kubernetes/test-infra#22407]

**Comment by BenTheElder** [comment]
I don't think there's enough to go on here. The prow jenkins integration doesn't itself create pods, does it? This is something your test is doing?

**Comment by midnightconman** [comment]
@BenTheElder is right, the jenkins-operator will just run existing jobs on a jenkins instance... can you give us more information on any errors you are seeing? Maybe look at the jenkins-operator log output and see what we see there?

**Comment by spiffxp** [comment]
/close
Please reopen if you have more information to provide
