### ISSUE TITLE
spyglass: missing allow-same-origin breaks viewer(s)

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#22417]
**What happened**:

The coverage result treemap viewer is broken due to:

> Uncaught SecurityError: Sandbox access violation: Blocked a frame at "null" from accessing a frame at "https://prow.k8s.io".  The frame requesting access is sandboxed and lacks the "allow-same-origin" flag.

**What you expected to happen**:

Deck/spyglass should function without errors. This is breaking the ability to click through the treemap, probably other things.

**How to reproduce it (as minimally and precisely as possible)**:

Visit prow.k8s.io, inspect a job results page.

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-coverage-unit/1400476832872009728

**Anything else we need to know?**:

/area prow
/area prow/deck
/area prow/spyglass

**Comment by MushuEE** [comment]
![image](https://user-images.githubusercontent.com/7189267/121071676-1ca3b280-c785-11eb-964a-b7407dd646df.png)

**Comment by fgimenez** [comment]
/assign
/remove-help

I'd like to give this one a try :) 

I have a question, according to https://github.com/kubernetes/test-infra/blob/master/prow/spyglass/write-a-lens.md#sandboxing, XHR requests to Deck should be restricted, would this change in the sandbox setting allow them?

**Comment by BenTheElder** [comment]
we should probably vet that the fix takes effect :-)

**Comment by fgimenez** [comment]
> we should probably vet that the fix takes effect :-)

makes sense :) is it already deployed?

**Comment by BenTheElder** [comment]
it should be by now? but it looks like the issue persists https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-coverage-unit/1458864415947362304

**Comment by BenTheElder** [comment]
the coverage viewer appears to still be broken 🤔  https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-coverage-unit/1491532856533454848

**Comment by fejta** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox

```
When the embedded document has the same origin as the embedding page, it is strongly discouraged to use both allow-scripts and allow-same-origin, as that lets the embedded document remove the sandbox attribute — making it no more secure than not using the sandbox attribute at all.
```

**Comment by BenTheElder** [comment]
The coverage viewer loads now, can't say why.

Seems like we should revert https://github.com/kubernetes/test-infra/pull/22921#issuecomment-1078440770

**Comment by fejta** [comment]
> we should revert https://github.com/kubernetes/test-infra/pull/22921#issuecomment-1078440770

Do we run any untrusted lenses? I am thinking a quick mitigation might be to make this configurable per lens, and off by default.

**Comment by BenTheElder** [comment]
As far as I know we don't, only lenses built into upstream prow. I'm not sure about other deployments.
