### ISSUE TITLE
Increase timeout on 1.6 master upgrade jobs

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/test-infra#2244]
Talking to @skriss it appears several of the the master upgrade jobs are timing out before completion.

I would recommend changing the timeout to 700+ minutes.

An example of this can be seen here: https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-gci-1.5-container_vm-1.6-upgrade-master

**Comment by ethernetdan** [comment]
@ixdy could you change this?

**Comment by ixdy** [comment]
#2247 sent, I just need someone to LG it
