### ISSUE TITLE
Jobs fail with an error "Job execution failed: Pod got deleted unexpectedly"

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/test-infra#22447]
**What happened**:

Some jobs, for example ci-kubernetes-node-kubelet-serial-cpu-manager and ci-kubernetes-node-kubelet-serial-hugepages fail with  "Job execution failed: Pod got deleted unexpectedly".  build-log.txt doesn't exists among job artifacts.

**What you expected to happen**:

Job should either fail or succeed and build-log.txt should clearly describe the test flow.

**How to reproduce it (as minimally and precisely as possible)**:

It's hard to reproduce as it happens quite rarely.

**Please provide links to example occurrences, if any**:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cpu-manager/1401392642746486784
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-hugepages/1401423093053788160

**Anything else we need to know?**:

the only error message I'was able to spot in this [podingo.json](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cpu-manager/1401392642746486784/podinfo.json) was this: 
```MountVolume.SetUp failed for volume \"service\" : failed to sync secret cache: timed out waiting for the condition```.
However, I don't see this kind of errors in the second failed job.

**Comment by cynepco3hahue** [comment]
@BenTheElder I unsure how can we check the real reason without access to CI infrastructure, do you know someone who can help and clarify the reason for the pod failure?
By default we request:
```
resources:
      requests:
        cpu: 250m
        memory: 1Gi
```
So the first thing that comes to my mind is the OOM issue.

**Comment by bart0sh** [comment]
@cynepco3hahue Can we use an instance with bigger amount of memory just to see if it helps?

both jobs (ci-*-cpu-manager and ci-*-hugepages) use the same ubuntu image, so it would be good to change both at the same time.

**Comment by cynepco3hahue** [comment]
@bart0sh If we are talking about OOM it will not help, because the pod can be killed anyway, we can try to change the guaranteed class, but it can affect other jobs.

**Comment by BenTheElder** [comment]
Workloads running on the wg-k8s-infra infrastructure are accessible via PR to the k8s.io repo.

The other legacy infra is primarily accessible to the test-infra oncall go.k8s.io/oncall, but I don't think they typically dig into individual jobs at this point unless there is evidence that prow is misbehaving.

The pod events with the secret cache sync timeout are odd but don't seem related to prow to me. I'm not sure they're particularly actionable for the oncall either.

**Comment by bart0sh** [comment]
For hugepages job we set CPU limit 10m and Memory limit 100Mi and we don't set requests.
What are CPU and memory defaults fro the jobs?

@cynepco3hahue it looks suspicious that only hugepages and cpu-manager jobs get deleted. I've looked at other sig-node jobs, but couldn't find any failing the same way. what's so special in these 2 jobs?

**Comment by bart0sh** [comment]
@cynepco3hahue I saw it in the test code: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/hugepages_test.go#L180

**Comment by cynepco3hahue** [comment]
But we are talking about the job pod, the pod that responsible to run tests and it the one that failed.

**Comment by bart0sh** [comment]
The prow job should not be different from other prow jobs. I thought there is something different in the tests that makes prow jobs pod deleted.

**Comment by BenTheElder** [comment]
I think there's a bit of confusion here.

Prow runs CI as pods in a fixed cluster used for this.

Those pods then spin up e.g. the node e2e test resources which may include a kubernetes cluster, on which test pods are dynamically scheduled by the test.

Prowjob pods are *not* test cases from kubernetes and those pods do not and should not run as pods in the prow clusters. Their requests / limits are not relevant. The requests / limits on the job pod configured here could be.

**Comment by bart0sh** [comment]
@BenTheElder thanks. Is there any reason that only pods spinning  hugepages and cpu-manager e2e tests got deleted?
Is it test infra configuration issue or it's somehow related to the e2e test configurations?

**Comment by BenTheElder** [comment]
> Is there any reason that only pods spinning hugepages and cpu-manager e2e tests got deleted?

I don't know. That requires further debugging and I've got other things on my plate.

> Is it test infra configuration issue or it's somehow related to the e2e test configurations?

The phrasing here is still somewhat ambiguous to me so let me try to rephrase:

It is *not* in any configuration in kubernetes/kubernetes, it is not in any internals of test/e2e. Those affect pods created on the cluster that is created _during_ the test, which has nothing to do with the prowjob pod. This disposable test cluster being tested by e2e is NOT the cluster hosting the logic that creates itself and runs the tests (the prow cluster).

It is likely something with the pod _running_ e2e.test / node e2e, which is configured in this repo.

It is possible that something with how the node e2e test is consuming too much resources, or configured differently with the mounts, etc. That would likely be in the config in this repo.

It's also possible that it's some issue with the cluster hosting the tests. However that seems unlikely as we've not seen this impacting other jobs and it is pretty much a large plain GKE cluster on the stable release track, just used to host build/test workloads.

**Comment by bart0sh** [comment]
> I don't know. That requires further debugging and I've got other things on my plate.

I'd be happy to help with this if you can elaborate a little bit on how to proceed. Should I request some rights to access prow cluster logs?

**Comment by BenTheElder** [comment]
I don't know that the cluster even has logs from that far back, and it's all passing now? https://prow.k8s.io/?job=ci-kubernetes-node-kubelet-serial-cpu-manager

You can't get access to the legacy cluster google setup at the cluster log level etc., only the oncall team (because it's an internal google.com GCP project). You can PR yourself to the wg-k8s-infra clusters/resources in the k8s.io repo, which the job may or may not be migrated to.

go.k8s.io/oncall => @michelle192837 could maybe take a look, but I'm not sure a pair of flakes from a week+ ago is worth their time. Jobs can be evicted or interrupted from time to time, it just comes with the territory of long-running Kubernetes pods. Prow will best-effort upload pod info there, which we did get, but the logs are easily lost when the pod is deleted and that's not a trivial bug / it's structural to the pod-utilities.

**Comment by bart0sh** [comment]
@BenTheElder 
> I don't know that the cluster even has logs from that far back, and it's all passing now? https://prow.k8s.io/?job=ci-kubernetes-node-kubelet-serial-cpu-manager

Both tests are passing most of the time. [Hugepages test](https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-hugepages) failed on 5th and 7th of June and 26 of May.

OK, if this is so hard to debug let's monitor this further. If it happens again periodically I'll try to contact oncall team.
Thank you for your help!

**Comment by BenTheElder** [comment]
Well FWIW I have spotted this issue elsewhere more recently https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance/1402563181775163392

So I'm going to raise it to the oncall team.

**Comment by bart0sh** [comment]
@BenTheElder Would it make sense to raise priority for this issue?

**Comment by BenTheElder** [comment]
I'm still not finding it very often, but changing the priority doesn't really "change the priority" anyhow 🙃 

@cjwagner took some action today, see this slack thread https://kubernetes.slack.com/archives/C7J9RP96G/p1623276124015100

**Comment by bart0sh** [comment]
Sounds promising. Let's see if it happens again after the action. If not - I'll close this issue.

**Comment by qaifshaikh** [comment]
@BenTheElder Is there a way to have prow retrigger jobs that fail with this error?

More context: We see this error quite often if the AZ runs out of spot instances. Looking for a way to have prow rerun such jobs

**Comment by BenTheElder** [comment]
I don't think so. You might find better luck filing another issue or asking on #prow kubernetes.slack.com though.

**Comment by bart0sh** [comment]
@qaifshaikh @BenTheElder It looks like infra changes fixed this issue. At least I don't see it happening anymore for ci-kubernetes-node-kubelet-serial-cpu-manager and ci-kubernetes-node-kubelet-serial-hugepages. Closing this issue.

**Comment by BenTheElder** [comment]
For the record this appears to have been an issue with the VMs in the prow cluster that were created in a certain time range, which was resolved by taking a cluster upgrade (which is one way to get all new node VMs).

The VM issue (with the E2 instance type) potentially caused long memory allocation delays / issues with the virtio memory balloon device used in these instances, we had many node VMs from that time range, the infra oncall team received an automated customer email from GCE support notifying https://github.com/kubernetes/test-infra/issues/22447#issuecomment-858435257, and @cjwagner initiated the upgrade.

It makes sense that this would break things like secret sync and would be cleared up now.

Cole forwarded me the customer notice, the relevant bit is:

> During the period between May 15, 2021, and May 30, 2021, Compute Engine E2 family VMs experienced an issue where Compute Engine’s software stack could cause issues with the initialization of the Virtio memory balloon device in the Linux kernel. We have since rolled back the problematic software on our side, but some VMs that were booted during this period will continue to be affected until they are rebooted or shut down.
> 
> The poorly performing balloon device from this issue can result in the guest kernel or associated applications taking roughly a minute to allocate memory until the balloon device can complete its operations.
