### ISSUE TITLE
Github throttler allows up to 2x hourly token budget in the first hour

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#22456]
**What happened**:

When set up, the github throttler will both fill up the `burst` channel entirely and start a goroutine to refill it. This allows up to 2x `hourly-tokens` usage in the first hour:
https://github.com/kubernetes/test-infra/blob/c868e582b681ad469d3fb6b3b407be4c610ca40f/prow/github/client.go#L527-L540

@fejta you introduced the throttler in https://github.com/kubernetes/test-infra/pull/5620 and @cjwagner you reviewed that change. Is this behavior intended? I find this very surprising.

/area prow
/area prow/github

**What you expected to happen**:

The github throttler to only start a goroutine to refill the budget but not fill up the `burst` channel entirely

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by cjwagner** [comment]
/assign
Good catch. I've thought about a few different ways to handle this and ended up with this: https://github.com/kubernetes/test-infra/pull/22489
