### ISSUE TITLE
/test all doesn't trigger non-automatically run jobs

### ISSUE THREAD

**Issue by YuviGold** [kubernetes/test-infra#22494]
**What would you like to be added**:
Either changing `/test all` to run all the available jobs or adding a new command to trigger all the available jobs.

**Why is this needed**:
At the moment, running `/test all` doesn't cover all the available jobs.
1. This is misleading. `all` keyword represents everything. Even the [Command Help](https://prow.k8s.io/command-help#test) page describes this operation as all test jobs, without any notes.
```
/test [\|all] | /test all/test pull-bazel-test | Manually starts a/all test job(s). Lists all possible job(s) when no jobs/an invalid job are specified.
```
2. Looking forward to scripts and scale - I wouldn't expect any contributor (or bot) to check every time all the possible jobs and then run them (let's say those jobs change frequently). In case the contributor wants to run everything - it should be everything available and not just automatically running.

**Comment by BenTheElder** [comment]
You can list all jobs by commenting `/test` and you can run the ones you want. 

`/test all` is just available to get fresh results for everything, not to trigger all possible jobs.

In Kubernetes we really would never want to enable this / would block this feature to to trigger all possible jobs. 

There are manually triggered jobs available if necessary that should not be arbitrarily triggered (e.g. larger cluster scale testing) without due consideration. We also have a _lot_ of them, and there's no good reason to be running all of them.

**Comment by YuviGold** [comment]
> You can list all jobs by commenting `/test` and you can run the ones you want.
> 
> `/test all` is just available to get fresh results for everything, not to trigger all possible jobs.
> 
> In Kubernetes we really would never want to enable this / would block this feature to to trigger all possible jobs.
> 
> There are manually triggered jobs available if necessary that should not be arbitrarily triggered (e.g. larger cluster scale testing) without due consideration. We also have a _lot_ of them, and there's no good reason to be running all of them.

@BenTheElder You're right. It could be really excessive and most of the time unwanted to run **everything**.

So I'd like two bring up 2 points:
- _Correction_: Fix the help description to point out not *all* the jobs are running when using **all**.
- _Enhancement_: It could be beneficial for both a contributor and a bot to run a group of tests.
Possible solutions - tests group tags; wildcards;
