### ISSUE TITLE
Prow issue: k8s-ci-robot responds to message to depandabot

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/test-infra#22491]
Like following:
![image](https://user-images.githubusercontent.com/12838129/121330237-ca16f180-c950-11eb-9400-3b5d4cf48359.png)

**Comment by alvaroaleman** [comment]
I'm afraid I'll have to close this one with an xkcd: ![xkcd](https://imgs.xkcd.com/comics/correlation.png)

Needs rebase got extended to comment with a dependabot-understandable rebase comment if the PR is from dependabot: https://github.com/kubernetes/test-infra/pull/22448

It happened to comment at approximately the same time as you did, but that was just a coincidence and not a reaction to your comment :)

/close
