### ISSUE TITLE
Can't silence job on slack reporter config

### ISSUE THREAD

**Issue by dhiller** [kubernetes/test-infra#22533]
**What happened**:

We were thinking that by overriding slack reporter config on the job level we could silence jobs by applying a job config like this:
```
  reporter_config:
    slack:
      job_states_to_report: []
```

**What you expected to happen**:
We expected the job to stop reporting. Unfortunately this doesn't work.

**How to reproduce it (as minimally and precisely as possible)**:

I've added a test case here: https://github.com/dhiller/test-infra/commit/9d96f46ffab22e0c800c87d3bf6ffbfb8ca4a981

Are we just using it wrong? Is there another way to silence a single job?

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by dhiller** [comment]
FYI @fgimenez @rmohr

**Comment by fgimenez** [comment]
Looks like everything is working as expected if we set `reporter_config.slack.job_states_to_report` to `[]` at the ProwJob level, can you please confirm @dhiller?

**Comment by dhiller** [comment]
Yes, can confirm that it now works as expected. Thanks!

/close
