### ISSUE TITLE
Missing logs from failed scalability test for konnectivity-agent

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/test-infra#22552]
**What happened**:
Recent test `ci-kubernetes-e2e-gce-scale-performance` failed because of restart of `konnectivity-agent`. There is only log showing that component failed liveness probe, but there are no component specific logs.

**What you expected to happen**:
There will be available logs to debug what happened with `konnectivity-agent`

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1404121865806417920

**Comment by wojtek-t** [comment]
@jkh52 @cheftako
