### ISSUE TITLE
PR revision tooltip isn't shown on Prow Status page after redraw

### ISSUE THREAD

**Issue by YuviGold** [kubernetes/test-infra#22567]
Continues https://github.com/kubernetes/test-infra/issues/22301

**What happened**:
When hovering above PR revisions on the main Prow Status page, the tooltip displaying the title of the PR is shown.
Afterward, in case filtering by any filter and causing the page to redraw itself - the tooltip won't work.

**What you expected to happen**:
As the tooltip is shown at first, it should work after filtering.

**How to reproduce it (as minimally and precisely as possible)**:
1. Goto Prow Status page filtered by presubmit jobs - https://prow.k8s.io/?type=presubmit
2. Try to hover above the revision links on the Revision column and see the tooltip is presented.
3. Goto the filter toolbar and try to change the filter and cause the page to redraw.
For example - choose type "all" and then go back to "presubmit"
4. Now once again try to hover above the revision links and see the tooltip isn't shown.

**Anything else we need to know?**:
The `redraw` function is called when the window reloads and each time a filter is chosen.
It seems that the current implementation just creates new rows with the same ProwJob info (title exists). Each new row gets a new ID. e.g. In case at the first time the row had attribute `pr-openshift/assisted-service-2014-tipID-1`  the next time after redraw it would be `pr-openshift/assisted-service-2014-tipID-2`
Additionally, the only difference between the rows DOM was `data-upgraded=",MaterialTooltip"` that's missing from the newly created row.

**Comment by YuviGold** [comment]
@cjwagner Maybe you know? You added the tooltip element on https://github.com/kubernetes/test-infra/pull/8791

**Comment by cjwagner** [comment]
I don't know sorry. This has been an issue for a while and manifests in a few places. These issues are likely the same root problem: 
- https://github.com/kubernetes/test-infra/issues/12081
- https://github.com/kubernetes/test-infra/issues/10605

**Comment by xinydev** [comment]
/assign

It needs to call `upgradeElement` after creating new DOM elements dynamically. I will create a PR to fix this.   

https://getmdl.io/started/index.html#dynamic
