### ISSUE TITLE
optimize triage job further

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#22577]
The job requests 7 CPU and 40Gi ram.

For this run:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-triage/1405025954731921408

> Test started today at 9:54 PM

I tracked down the VM and grabbed the monitoring:

<img width="811" alt="Screen Shot 2021-06-15 at 10 31 02 PM" src="https://user-images.githubusercontent.com/917931/122163170-93961680-ce29-11eb-96ca-4aca09164c23.png">

At this point the logs end with:
> I0616 05:21:31.323471     142 cluster.go:322] Finished clustering 4083 unique tests (947138 failures) into 3590 clusters in 14m6.864782035s
> I0616 05:21:31.323509     142 summarize.go:113] Rendering results...

So we can clearly see that during clustering it's saturating the available CPU pretty good.

But after clustering we drop down to about 1 core (~15% to ~16% utilization on an 8 core VM => ~1.2 to ~1.3 cores used on the VM, some of that is kubelet etc.).

Runs are taking around 40m total:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-test-infra-triage

So a significant amount of time is not the clustering, which is known to be parallel.

I haven't looked at the internals since the go rewrite but we can probably parallelize or otherwise optimize the rest of this work.

I'm finding for seeing if a tweak to fix https://github.com/kubernetes/kubernetes/issues/102887 worked that I wished to get results even faster. They're doing _way_ better than before the rewrite but I bet we can do better.

**Comment by BenTheElder** [comment]
> I0616 05:32:46.425292     142 summarize.go:162] Finished rendering results in 11m15.101763572s

from finished.json it finished at `Wed Jun 16 2021 05:34:05 GMT+0000` (converted the unix epoch timestamp)

and from these lines:
> Wed Jun 16 04:54:34 UTC 2021
> + bq --headless --format=json query --max_rows 1000000 'select

> I0616 04:59:04.024841     142 cluster.go:76] Clustering failures for 4083 unique tests...

we are spending ~5 minutes doing the initial bigquery etc.

So we're spending roughly:
- 5 min bq
- 15m clustering
- 11m rendering
- 2m uploading results

... which accounts for 33m, I'm missing ~6 minutes somewhere.

**Comment by pravarag** [comment]
@BenTheElder can I work on this issue and investigate more? Though I may have very less experience around test-infra but I can take-it up as a good learning if there is no hard-deadline 🙂

**Comment by BenTheElder** [comment]
hey, you certainly can :-) anyone can.

If you're looking for a starter issue though, you might try looking for "good first issue" labeled issues. We also maintain something of an index of these:
https://github.com/orgs/kubernetes/projects/52
https://github.com/orgs/kubernetes-sigs/projects/11

**Comment by BenTheElder** [comment]
Per above https://github.com/kubernetes/test-infra/issues/22577#issuecomment-862060159 and the original comment, if anyone wants to take this on I recommend looking at the "rendering" phase to start, I think naively that looks like biggest opportunity.
