### ISSUE TITLE
Feature Request: Prow: Pretty Human Readable Prow Errors

### ISSUE THREAD

**Issue by aryeh-looker** [kubernetes/test-infra#22572]
**What would you like to be added**:

Pretty printing for errors in from `checkconfig` and other prow-owned log messages. Example screenshot from current implementation:

![image](https://user-images.githubusercontent.com/12849602/122130528-9de5ef80-cdec-11eb-83ff-c6b76e53813b.png)

Ideal implementation would be to print something like this as it enhances readability:

```
{
    "component": "checkconfig",
    "error": "error validating .prow.yaml: failed to validate .prow.yaml: invalid presubmit job foo: decorated job containers must specify command and/or args",
    "file": "prow/cmd/checkconfig/main.go:224",
    "func": "main.main",
    "level": "fatal",
    "msg": "Validation failed",
    "severity": "fatal",
    "time": "2021-06-15T21:45:23Z"
}
```

**Why is this needed**:

Minor, but enhances readability.

**Comment by BenTheElder** [comment]
I don't think we should manipulate the format of the job's stdout/stderr / buildlog, I think that would be surprising.

You can output formatted errors by converting them to JUnit XML which this prow page, testgrid, and other tools can understand throughout our stack. 

I also recommend using a human readable format for logs aimed at humans, ideally checkconfig could use a different formatter in CI versus a running deployed prow component using json logs.

e.g. with go use [gotestsum](https://github.com/gotestyourself/gotestsum)

**Comment by aryeh-looker** [comment]
I'm realizing my message was unclear. To be more precise, I'm suggesting pretty-printing of errors from the prow YAML validation jobs.

**Comment by aryeh-looker** [comment]
i.e. in `checkconfig`, I believe https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig

**Comment by aryeh-looker** [comment]
Perhaps an option for `logrus.WithError` https://github.com/kubernetes/test-infra/blob/master/prow/cmd/checkconfig/main.go#L224

**Comment by aryeh-looker** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/checkconfig/main.go#L224

**Comment by BenTheElder** [comment]
ah, in that case yes I agree, though I might phrase it more like "use a human readable log formatter" since it's not so much errors as that all log lines are json 😅

**Comment by aryeh-looker** [comment]
Updated summary
