### ISSUE TITLE
Prow issue:E0617 13:24:06.106788       1 aws_manager.go:265] Failed to regenerate ASG cache: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.For verbose messaging see aws.Config.CredentialsChainVerboseErrors

### ISSUE THREAD

**Issue by prasanthteja** [kubernetes/test-infra#22596]

**Comment by prasanthteja** [comment]
I am facing this below  issue from autoscaler pod when upgraded EKS from 1.16 to 1.17

Error:

Failed to regenerate ASG cache: cannot autodiscover ASGs: NoCredentialProviders: no valid providers in chain. Deprecated.For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by BenTheElder** [comment]
aws_manager.go is not a part of this project.

prow does not deal with auto-scaling groups, credential providers, or AWS*

https://github.com/kubernetes/test-infra/blob/master/prow/README.md

* there's some S3 bucket support for log storage.
