### ISSUE TITLE
Federation PR e2e tests shouldn't fail when the clusters are being recycled.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/test-infra#2259]
Federated clusters required for federation PR e2e tests are recycled only once a day and it happens in the background. Any PR test that runs when the clusters are being recycled will fail. We need a locking mechanism to avoid these failures.

cc @csbell @kubernetes/sig-federation-bugs

**Comment by madhusudancs** [comment]
The job that recycles the federated clusters is time-triggered and runs as a CI job. The tests run in pull jobs. These two jobs run in two separate Jenkins instances and hence cannot be configured to block each other. 

The solution that I am working on right now uses GCS to hold the locks required to coordinate these two jobs. We already have a bucket in GCS where we store the shared state of these two jobs and the lock object is stored in that bucket. The CI job, also called the `deploy` job, begins by removing any existing `kubeconfig` object corresponding to the existing federated clusters. It then proceeds to check if there exists a non-empty object called `federated-clusters.lock`. The absence of such an object or an empty lock signals that the `deploy` job can proceed. The job blocks if it sees a non-empty `federated-clusters.lock` object and polls continuously until the content of the object is cleared.

The pull job begins by checking for the existence of `kubeconfig` object. The absence of `kubeconfig` blocks the pull job. However, if the `kubeconfig` object exists, it copies the object to its local directory and creates/updates the `federated-clusters.lock` object. The content of the update is just the build number followed by a line break. When the test completes, it removes this line from the lock object.

In order to ensure that the parallel PR jobs don't overwrite each other, we `read-modify-write` the lock object using the object's `generation`.

The goal is to build this logic into kubetest, particularly in the file where we implement federation specific up and down functions.

cc @ixdy @krzyzacy @fejta @csbell

**Comment by madhusudancs** [comment]
cc @nikhiljindal

**Comment by csbell** [comment]
A few comments/concerns:
* Do you foresee the deploy job be starved by an odd combination of insufficient poll frequency and constant pull jobs (particularly around release time?).
* Should the deploy job complain after being unable to see a free ``federated-clusters.lock`` ?
* Should the pull job put its build number and it time-of-day in there pr do you think just a build number is sufficient to trace back to start time by visiting a test grid? It's nice to be able to detect stuck locks. I'm sure that our first go at handling this will work but we may introduce bugs over time that leave the lock stuck.

**Comment by madhusudancs** [comment]
> Do you foresee the deploy job be starved by an odd combination of insufficient poll frequency and constant pull jobs (particularly around release time?).

This shouldn't happen. The very first thing that the `deploy` job does is to delete the `kubeconfig` file. Absence of this file blocks new `pull` jobs. So new pull jobs cannot be scheduled once the deploy job begins.

> Should the deploy job complain after being unable to see a free federated-clusters.lock ?

Yeah, good point. I will include this. It should time out after some point and just proceed. If the deploy job waits for 90 minutes then there must something wrong with the tests. The tests should have failed and freed the lock anyway. 

> Should the pull job put its build number and it time-of-day in there pr do you think just a build number is sufficient to trace back to start time by visiting a test grid? It's nice to be able to detect stuck locks. I'm sure that our first go at handling this will work but we may introduce bugs over time that leave the lock stuck.

Very good point. Did not consider this. Build numbers are unique and we can trace back to their start time. But that means we need to figure out a way to programmatically trace back. It is probably much simpler to record the timestamp along with the build number. It is also less work.

**Comment by spiffxp** [comment]
clearing out the v1.7 milestone, if this is going to be worked it can be added to another milestone
