### ISSUE TITLE
Re assign Labels sig/area to PRs is misleading. 

### ISSUE THREAD

**Issue by mcbenjemaa** [kubernetes/test-infra#22605]
**What happened**:
I have a PR that consists of updating dependencies, The Bot tries to assign sig labels from files that are changed!
But sometimes that's not Correct!
For example in my case, It assigns all the sigs that the dependency has changed in.
I assigned the correct sig, I thought that the Bot shouldn't re-assign the sig labels anymore, But it does  (on every commit basis! this is annoying).

**What you expected to happen**:
When I manually assigned a label the Bot should not re-assign labels.

**How to reproduce it (as minimally and precisely as possible)**:
Create a PR for example that change dependencies in every pkgs.
then create commit and manually assign sig label after that commit again and you notice that the Bot will re-assign labels again.

**Please provide links to example occurrences, if any**:
Example: kubernetes/kubernetes#102783

**Anything else we need to know?**:
/area prow

**Comment by BenTheElder** [comment]
So these labels come from the OWNERS files. If they're incorrect the OWNERS files should be updated.

The reason it happens again on every commit is that the set of files changed can change on every commit / push, so which OWNERS files are relevant is re-evaluated.

> The Bot tries to assign sig labels from files that are changed!
> But sometimes that's not Correct!

If we know that these are not correct, we should fix the incorrect data.

https://go.k8s.io/owners

**Comment by mcbenjemaa** [comment]
Thanks for the information. 

I just wanted to highlight if we can prevent this intended action, 

> The reason it happens again on every commit is that the set of files changed can change on every commit / push, so which OWNERS files are relevant is re-evaluated.

Since, I assigned the sig label manually then, The Bot shouldn't re-assign sig labels anymore or maybe ask for confirmation whether the new labels should be applied or not, and that's because as mentioned (I have set the sig label manually!)

Any idea!

**Comment by BenTheElder** [comment]
I will have to defer to others more current on Prow internals for this but I think it may be too expensive (in terms of GitHub API quota) to attempt to lookup if you've changed any of the labels prior to the push.

Also: you can put essentially any label in the OWNERS but we wouldn't probably want to allow you to do this for some labels.

Either way, changes in workflow behavior have to be approved by SIG contributor experience, this repo just implements some of them. Kubernetes/Community is the best place to file issues against contribex.

@kubernetes/sig-contributor-experience

**Comment by BenTheElder** [comment]
P.S. I agree this is frustrating but I highly suggest improving the labeling instead. The labels can even be configured to only apply to a specific regex instead of a folder (see the docs) so we could make them more accurate to begin with.

**Comment by mrbobbytables** [comment]
I agree with @BenTheElder - this is largely working as intended; we want to fix the OWNERS files so that they label items correctly.

> I will have to defer to others more current on Prow internals for this but I think it may be too expensive (in terms of GitHub API quota) to attempt to lookup if you've changed any of the labels prior to the push.

AFAIK, this is the case. It'd essentially mean we'd have to walk the comments of every PR each time theres a comment, push, or review and re-establish the state or engineer keeping track of state externally in a DB.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/close
Closing as working as intended.  If this is changing code that these sigs own, they should get labeled.  If the sig you care about is not getting auto-labeled, it should be added to the appropriate OWNERS file.  If the sig you care about is manually labeled, that label will stick around, since prow won't revert/remove labels that have already been applied when it auto-labels based on OWNERS files.
