### ISSUE TITLE
allow branchprotector to protect branches matching a certain regex

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/test-infra#22657]
**What would you like to be added**:

There only seems to be an exclude option - https://github.com/kubernetes/test-infra/blob/1bd2a72cbe81fde4066a0e96a3ac3d75027bc624/prow/config/branch_protection.go#L53-L55

It would be ideal if we could supply a 'include' regex

**Why is this needed**:

As we introduce automated tooling or in the case someone pushes branch by accident to a repo they become protected and it becomes cumbersome to delete those.

ie. ideally we want to only protected `main` and `release-*` branches - so our inclusion regex would be `release-.*|main`

**Comment by mcbenjemaa** [comment]
@BenTheElder When adding an Inclusion regex, and there's already excludes polices.
In that case,, the inclusion policies works whereas the exclude are ignored ? or what ?
Does it make sense though ?

**Comment by BenTheElder** [comment]
Hi: I'm just sweeping the issues in this repo. There are others better to handle Prow issues.

AIUI generally in prow both would be used together.

**Comment by alvaroaleman** [comment]
The idea sounds fine, but I would prefer if we make the `include` setting mutually exclusive with the `exclude` one
