### ISSUE TITLE
label plugin next steps

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2268]
- [x] Add it to k/k :)
- [x] Make it case-insenstive: `/priority p3` doesn't work, but it should probably add the `priority/P3` label.
- [x] [Make it work](https://github.com/kubernetes/test-infra/issues/2445) in issue and PR bodies when they open. Currently only works for issue comments. See the [assign](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/assign/assign.go) plugin for an example.
- [x] How do I remove a label?

/assign @grodrigues3

**Comment by cblecker** [comment]
Related to https://github.com/kubernetes/test-infra/pull/2023

**Comment by bgrant0607** [comment]
Note that numerical priorities are deprecated

**Comment by grodrigues3** [comment]
@foxish is Jun going to get started on this?

**Comment by foxish** [comment]
@crimsonfaith91 do you want to take a stab at this? It's a fairly self contained piece.

**Comment by crimsonfaith91** [comment]
Dear Anirudh,

  Sure! I will look at it asap! Thanks! :)

Regards,
Jun Xiang Tee
