### ISSUE TITLE
panic in kubetest

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#2269]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.5-gci-1.6-upgrade-master/34?log#log
```
W0315 13:44:55.361] panic: runtime error: invalid memory address or nil pointer dereference
W0315 13:44:55.361] [signal 0xb code=0x1 addr=0x0 pc=0x41cfdf]
W0315 13:44:55.361] 
W0315 13:44:55.362] goroutine 1 [running]:
W0315 13:44:55.362] panic(0x82f8e0, 0xc82001a140)
W0315 13:44:55.362] 	/usr/local/google/home/fejta/golang/1.6.2/go/src/runtime/panic.go:481 +0x3e6
W0315 13:44:55.362] main.output(0xc820145040, 0x0, 0x0, 0x0, 0x0, 0x0)
W0315 13:44:55.362] 	/usr/local/google/home/fejta/go-tools/src/k8s.io/test-infra/kubetest/util.go:191 +0x3ff
W0315 13:44:55.363] main.ListResources(0x0, 0x0, 0x0, 0x0, 0x0)
W0315 13:44:55.363] 	/usr/local/google/home/fejta/go-tools/src/k8s.io/test-infra/kubetest/e2e.go:302 +0xad
W0315 13:44:55.363] main.run.func12(0x0, 0x0)
W0315 13:44:55.363] 	/usr/local/google/home/fejta/go-tools/src/k8s.io/test-infra/kubetest/e2e.go:168 +0x3a
W0315 13:44:55.363] main.xmlWrap(0x8fc280, 0x12, 0xc8201cbad0, 0x0, 0x0)
W0315 13:44:55.363] 	/usr/local/google/home/fejta/go-tools/src/k8s.io/test-infra/kubetest/util.go:85 +0x5e
W0315 13:44:55.364] main.run(0x7f4c60faa000, 0xb04eb8, 0x0, 0x0, 0x100, 0x8b4a88, 0x4, 0x1, 0x7ffe7d7f1994, 0x15, ...)
W0315 13:44:55.364] 	/usr/local/google/home/fejta/go-tools/src/k8s.io/test-infra/kubetest/e2e.go:170 +0x192f
W0315 13:44:55.364] main.complete(0xc820118000, 0x0, 0x0)
W0315 13:44:55.364] 	/usr/local/google/home/fejta/go-tools/src/k8s.io/test-infra/kubetest/main.go:248 +0x967
W0315 13:44:55.364] main.main()
W0315 13:44:55.364] 	/usr/local/google/home/fejta/go-tools/src/k8s.io/test-infra/kubetest/main.go:186 +0x143
```

(also, go1.6.2? is that right?)

**Comment by krzyzacy** [comment]
/usr/local/google/home/fejta/golang/1.6.2

wait, did @fejta trigger it locally?

**Comment by ixdy** [comment]
@krzyzacy kubetest is prebuilt, so it's showing whatever @fejta has installed on his machine

**Comment by krzyzacy** [comment]
ah whoever built the image will have the prestige :-)

**Comment by fejta** [comment]
What happened to these 12 hours?

```
I0314 23:06:48.201] Mar 14 23:06:48.201: INFO: error: L7 controller failed to delete all cloud resources on time. timed out waiting for the condition
W0315 13:29:55.279] 2017/03/15 13:29:55 util.go:132: Interrupt testing after 15h0m0s timeout. Will terminate in another 15m
W0315 13:29:55.311] 2017/03/15 13:29:55 util.go:110: Step '/workspace/kubetest --test --test_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/latest-1.6 --upgrade-image=gci --v=true --check-version-skew=false' finished in 14h49m44.553097487s
```


https://github.com/kubernetes/test-infra/blob/bb0669b017507eb4a55e33cf73fa304f5211b6ce/kubetest/util.go

Shows L191 blew up here: `syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)`

I'm not going to wait until we have more instances of this to deal with it.

**Comment by ixdy** [comment]
It's not hard to find other instances of this panic - using the triage tool https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=Terminate%20testing%20after%2015m%20 yields a bunch like https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial-release-1.4/1063?log#log from yesterday.

**Comment by fejta** [comment]
Well from a triage point of view the job already timed out, so I'm struggling to find the motivation necessary to debug

**Comment by ixdy** [comment]
It suggests a latent bug that could cause issues elsewhere.

It looks like a race: we call `cmd.Output()` in a new goroutine, and then immediately select on the terminate channel. I'm guessing the command hasn't actually started yet by the time we try to kill it.

It also looks like we're not handling timeouts in upgrade tests correctly: if we get stuck in the first stage (upgrading the cluster) and kill it with a timeout, we then subsequently run e2e tests (and eventually hit the 15m extra timeout), rather than skipping e2e tests as we should.

**Comment by ixdy** [comment]
Panics in test infra also add unnecessary noise to the logs, which makes it harder to track down the actual failure.

**Comment by fejta** [comment]
You are right: it looks like the issue is that the command hasn't started yet.

However the problematic code only runs if we already timed out, so the build already failed.

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/pull/2338
