### ISSUE TITLE
CLA Plugin: Add support for EasyCLA

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/test-infra#22721]
**What would you like to be added**:

Add support to the [CLA Plugin](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/cla/) for [EasyCLA](https://docs.linuxfoundation.org/lfx/v/v2/easycla).

ref: https://github.com/kubernetes/org/issues/2778

**Why is this needed**:
The LF plans to deprecate the current CLA service used by the project. They would like to migrate us off the old plugin by the 2nd week of August. They are handling the migration of the user databases, but if we want our labels to reflect the state of the cla, the plugin will have to support the `EasyCLA` context. 

For migration purposes it'd be great if it could support both the current CLA and the future one in case there is a need to back out of the migration on their side.

Example EasyCLA status: 
https://api.github.com/repos/CNCF-EasyCLAV2-Test/Repository1/statuses/31eb937fb47d258b060a762165f293de6f99d191

---
/priority important-soon
/sig contributor-experience testing

**Comment by BenTheElder** [comment]
code: https://github.com/kubernetes/test-infra/tree/master/prow/plugins/cla

/help

**Comment by spiffxp** [comment]
/remove-help
Since this has been taken on by @MadhavJivrajani

**Comment by spiffxp** [comment]
What is left to do before we can call this done?

**Comment by mrbobbytables** [comment]
This is what I see at the moment as the current plan of action (please update if there is something else that should be done)
1) Enable EasyCLA as non-blocking org wide (accompanied by comms, was thinking of this/next week)
2) Assuming no issues are reported, we [pick a date not near any important milestone](https://www.kubernetes.dev/resources/release/#tldr) to coordinate the cut-over date. (thinking mid-october plenty of time before freeze, or right after freeze)
3) Three options for cut-over:
    1) Instruct everyone that they may need to refresh CLA status for their open PRs (easiest)
    2) Script hitting open PRs to refresh CLA status (moderate, IIRC @spiffxp / @cblecker you mentioned doing something like this in the past)
    3) Ensure functionality supporting both contexts is in place (#22742 - would need to be revisited)
4) On date of cut-over, CNCF performs a final sync and we flip to using the `EasyCLA` context instead of `cla/LinuxFoundation` (assuming we can't support both). If there is an issue, we revert to the old system. Anyone that signed up after cut over may have to sign the old CLA.


Potential issue:
- Mixed messaging regarding refreshing CLA status - Our tooling has its own message and command (`/check-cla`), EasyCLA has its own messaging and command (`/easycla`).  I have an inquiry out with the LF about this.

**Comment by mrbobbytables** [comment]
After discussion in today's GitHub management meeting, the potential problems between `/easycla` and `/check-cla` is a non-issue, the cla check should be fired automatically on any comment or update to the PR. The plan will now be:

1) Enable EasyCLA as non-blocking org wide next week (accompanied by comms)
2) Assuming no issues are reported, we cut-over after code freeze (Nov 16th). This means updating the current CLA plugin to look for `EasyCLA` instead of `cla/linuxfoundation`, removing our help text, and potentially updating it to also look for `/easycla` in the comments. The LF will also perform their final sync of the DBs between systems.
3) Given the time, most PRs should be updated with an `EasyCLA` status. We script hitting open PRs to refresh CLA status on the remaining PRs.

If there is an issue, we revert to the old system. Anyone that signed up after cut over may have to sign the old CLA.

**Comment by spiffxp** [comment]
The issue we're using to collect feedback on EasyCLA now that it's been enabled non-blocking: https://github.com/kubernetes/org/issues/3068

**Comment by mrbobbytables** [comment]
We have migrated over 👍 
- https://github.com/kubernetes/test-infra/pull/24844
- https://github.com/kubernetes/test-infra/pull/25136
- https://github.com/kubernetes/test-infra/pull/25138

Going to go ahead and close this out
