### ISSUE TITLE
Allow trusting a GH App bot-filed PRs enough to get them tested

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/test-infra#22731]
**What would you like to be added**:

GH apps can file PRs to repos, but because a GH app cannot be added as an org member or a collaborator (GH apps are not real users), it seems that we currently lack the way to "trust" Apps to get their PRs automatically tested, without needing a `/ok-to-test` by a kube member.

We could either have a config for this, or piggyback on some GH concept (trust an app if it's installed in an org?) Maybe we could do both.

**Why is this needed**:

Not having this feature makes automation scenarios harder

/area prow
/area prow/plugins

**Comment by alvaroaleman** [comment]
@cjwagner @chaodaiG objections against making this a `trustedApps` map orgOrRepo ->appNames config option?

**Comment by cjwagner** [comment]
> @cjwagner @chaodaiG objections against making this a `trustedApps` map orgOrRepo ->appNames config option?

No objection from me assuming the app name is a unique identifier.

**Comment by mdbooth** [comment]
/remove-lifecycle stale

Our use case for this is still very much alive. We would like to enable automatic testing of PRs opened by our bot.
