### ISSUE TITLE
CheckoutPullRequest方法fetch使用不对？

### ISSUE THREAD

**Issue by HQ1363** [kubernetes/test-infra#22755]
**What happened**:

本地在使用test-infra的prow工具时，对于prow/git/git.go文件里的CheckoutPullRequest方法，是否存在一处使用问题，如下：
```
// CheckoutPullRequest does exactly that.
func (r *Repo) CheckoutPullRequest(number int) error {
  r.logger.Infof("Fetching and checking out %s/%s#%d.", r.org, r.repo, number)
  if b, err := retryCmd(r.logger, r.dir, r.git, "fetch", r.base+"/"+r.org+"/"+r.repo, fmt.Sprintf("pull/%d/head:pull%d", number, number)); err != nil {
    return fmt.Errorf("git fetch failed for PR %d: %v. output: %s", number, err, string(b))
  }
  co := r.gitCommand("checkout", fmt.Sprintf("pull%d", number))
  if b, err := co.CombinedOutput(); err != nil {
    return fmt.Errorf("git checkout failed for PR %d: %v. output: %s", number, err, string(b))
  }
  return nil
}
```
如果采用上述姿势会报如下错误：
```
fatal: 'git@github.com/welliamcao/OpsManage' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
**Anything else we need to know?**:
上述代码块中的语句是否需要做如下替换：
```
retryCmd(r.logger, r.dir, r.git, "fetch", r.base+"/"+r.org+"/"+r.repo, fmt.Sprintf("pull/%d/head:pull%d", number, number))
==>
retryCmd(r.logger, r.dir, r.git, "fetch", r.base+":"+r.org+"/"+r.repo, fmt.Sprintf("pull/%d/head:pull%d", number, number))
```

**Comment by BenTheElder** [comment]
Prow by default uses HTTPS to clone in which case `"/"` is correct, this looks like an attempt at an SSH URL, how did you configure this?

Prow does have SSH cloning, and as far as I know it works correctly, you just need to configure it:

https://github.com/kubernetes/test-infra/blob/f0c722e28379af7007d5485096e353dd8c5bfdfc/prow/pod-utilities.md#how-to-configure

> Private repos need to do two things:
> - Add an ssh secret that gives the bot access to the repo to the build cluster and specify the secret name in the ssh_key_secrets field of the job decoration config.
> - Set the clone_uri field of the job spec to `git@github.com:{{.Org}}/{{.Repo}}.git`.

Public repos are cloned with HTTPS, unauthenticated.

**Comment by BenTheElder** [comment]
Feel free to reopen with more information or file a new issue. Closing due to lack of response.
