### ISSUE TITLE
Job history view should show batch jobs

### ISSUE THREAD

**Issue by YuviGold** [kubernetes/test-infra#22759]
**What happened**:
Job history view doesn't show batch jobs.
Spyglass's Job history link is pointing to the presubmit jobs 

**What you expected to happen**:
Job history view should be able to present only batches jobs or presubmits together with its batch jobs following the same job name.

**How to reproduce it (as minimally and precisely as possible)**:
1. Goto deck and choose "batch".
2. Pick a batch build and goto its spyglass view. e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-kind/1410623754769272832 ("batch" can be found in the spyglass URL)
3. Click on the Job History page and search for the above build ID. it cannot be found, neither any other batch jobs.

**Please provide links to example occurrences, if any**:
The Job History link should follow [GCS Bucket layout](https://github.com/kubernetes/test-infra/tree/master/gubernator#gcs-bucket-layout). Or, it would be even preferred to show both presubmit with batch jobs together on the same page. But it would require two paths to be fetched. One of the presubmit jobs and one of the batch jobs.

**Comment by BenTheElder** [comment]
This has never been a thing so I'd say it's not a bug, but it sounds like it could be a good feature.

cc @cjwagner @stevekuznetsov

**Comment by YuviGold** [comment]
I defined it as a bug since from Spyglass view of a batch job, when going to its job history - the batch job isn't shown at all.

The question is what should be the expected behavior?
Make batch jobs be shown separately from presubmit jobs (as they are actually located on different bucket paths) or presenting them together?
