### ISSUE TITLE
ApplyDefault doesn't allow setting arrays to empty when round tripping from golang -> yaml -> golang

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#22888]
**What happened**:
Defined slack reporter config in golang:
```go
&prowjob.ReporterConfig{
	Slack: &prowjob.SlackReporterConfig{
		JobStatesToReport: []prowjob.ProwJobState{},
	},
}
```
Later marshaled it to yaml, which end up like:
```yaml
    reporter_config:
      slack: {}
```

When this is then read into prow, JobStatesToReport will be `nil` (NOT `[]prowjob.ProwJobState{}`). This causes https://github.com/kubernetes/test-infra/blob/master/prow/apis/prowjobs/v1/types.go#L315 to get the setting from the parent.

The thing really confusing me: JobStatesToReport field has not changed for 12mos. https://github.com/kubernetes/test-infra/blame/69a9f34cd9c08cb1725d89e0d12f1ec2773f75b5/prow/apis/prowjobs/v1/types.go#L291

**What you expected to happen**:
I should be able to unset JobStatesToReport (or arrays in general) in this manner.

cc @chaodaiG 

A side note: `gopkg.in/yaml.v3` was recommended as a solution, but I do not think it is

Testing using different libraries:
```
    generate_test.go:37: k8s slack: {}
    generate_test.go:39: ghodss slack: {}
    generate_test.go:41: gopkg slack:
            channel: ""
            jobstatestoreport: []
            reporttemplate: ""
    generate_test.go:43: json {"slack":{}}
```

gopkg.in is wrong, IMO. It does not respect json tags on the struct. Therefor we end up with invalid YAML output - see jobstatestoreport, it isn't a valid ProwJob field

**Comment by howardjohn** [comment]
Even with giving the prow job yaml with explicit empty list, this still does not work

**Comment by chaodaiG** [comment]
Direct proof of roundtrip bug https://github.com/kubernetes/test-infra/pull/22900

**Comment by chaodaiG** [comment]
Briefly explaining what's happening in #22900:

```
reporter_config:
  slack:
    job_states_to_report: []
```
Unmarshal into `JobBase`, and get:
```
JobBase
{
	ReporterConfig: &prowapi.ReporterConfig
	{
		Slack: &prowapi.SlackReporterConfig
		{
			JobStatesToReport: []prowapi.ProwJobState{},
		},
},
```
Marshal into yaml then unmarshal back into `JobBase`, get:
```
JobBase
{
	ReporterConfig: &prowapi.ReporterConfig
	{
		Slack: &prowapi.SlackReporterConfig
		{
			JobStatesToReport: nil,
		},
},
```

**Comment by chaodaiG** [comment]
Boiled down to `omitempty` with slice caused this error. Created a much simpler repro and filed a bug in k8s-sigs/yaml repo: https://github.com/kubernetes-sigs/yaml/issues/56

**Comment by chaodaiG** [comment]
Got an answer from https://github.com/kubernetes-sigs/yaml/issues/56:

> This seems to be intended:

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.

> https://pkg.go.dev/encoding/json

[Job config](https://github.com/istio/test-infra/blob/9922d38ac6d89fb2a3921d8f2d9beb2aa69fa854/prow/cluster/jobs/istio/istio/istio.istio.master.gen.yaml#L265-L267):
```
reporter_config:
      slack:
        job_states_to_report: []
```

[Example prowjob run](https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-istiodless-mc-k8s-tests_istio_postsubmit/1415930690867826688):

```
reporter_config:
    slack: {}
```

Relavent event here:

1. trigger reads prowjob yaml from configmap, unmarshal into prowjob CR
2. trigger send prow job CR to api server

It's known that step 1 correctly captured `job_states_to_report` as empty slice, so the suspicion is around step 2. Possibly the call to api server involves a marshal and unmarshal?

cc @alvaroaleman and @cjwagner

**Comment by alvaroaleman** [comment]
So I guess our options are:
A) Not use `omitempty`
B) Treat empty/nil as equal? I think we have to differentiate that so not really an option, right?

**Comment by chaodaiG** [comment]
> So I guess our options are:
> A) Not use `omitempty`
> B) Treat empty/nil as equal? I think we have to differentiate that so not really an option, right?

yeah my feeling is also leaning towards A), citing you and @cjwagner here to make sure that I'm not missing important reasons of having `omitempty` defined on almost all prowjob fields

**Comment by alvaroaleman** [comment]
> yeah my feeling is also leaning towards A), citing you and @cjwagner here to make sure that I'm not missing important reasons of having omitempty defined on almost all prowjob fields

The reason for that is just storage size and performance, etcd has a total limit of how much data it can keep and having more data means (de-)serialization is more expensive in terms of memory/cpu/time. Since we need it here for functional reasons, removing it is fine IMHO.

**Comment by spiffxp** [comment]
@howardjohn are there more instances of this or can we consider this closed by https://github.com/kubernetes/test-infra/pull/22918 ?

**Comment by howardjohn** [comment]
I would not be surprised if there are more - I think any array with `omitempty` and ApplyDefaults checking for `nil` will be impacted. However, I only personally cared about the field fixed in https://github.com/kubernetes/test-infra/pull/22918 so haven't investigated beyond that. I would be happy to keep it open or closed.

**Comment by chaodaiG** [comment]
As mentioned in https://github.com/kubernetes-sigs/yaml/issues/56, this is WAI. Closing since https://github.com/kubernetes/test-infra/pull/22918 fixed this

/close
