### ISSUE TITLE
Recover PRs that spawned CI jobs but never got results reported

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/test-infra#22891]
**What would you like to be added**:

I'd like to have some mechanism to recover PRs from situation where they trigger CI jobs (and they get `pending` GH statuses), but then for some reason (it's rare but it happened for us) the results are never reported to GitHub as either passed or failed. It could be crier outages, accidents that delete `Prowjobs` from the cluster, etc.

RIght now this is possible to recover manually by using `/test all`, but many users are conditioned to `/retest` which does not re-trigger pending jobs.

I think a reasonable solution could be `/retest` being smart enough to inspect whether there is a job actually running behind a `pending` GH status and triggering a job if not.
Even smarter would be something that would proactively detect this (no prowjob running && gh status is pending) and acted on it, by e.g. marking that status as failed, but I'm not sure how realistic is that.

Alternatively, we could do what manual `/refresh` does more often to improve the chances of avoiding the failure mode.

**Why is this needed**:
This resolves the sitiation where a PR is essentially "stuck" until someone happens to know the `/test all` command or users push to a PR. Improves the UX of a certain failure state of Prow.

**Comment by BenTheElder** [comment]
Do you think the users that don't know /test all will know /retest?

We post information about commands automatically to PRs from new users (welcome bot) but if people don't read it for one I don't know that we can do much.

**Comment by petr-muller** [comment]
> Do you think the users that don't know /test all will know /retest? 

At least in our org, this is very common. People rerun failed jobs all the time, but trigger all of them very rarely (they get triggered automatically). Increasing awareness, making docs better is useful, but still requires someone to go and fixup the "stuck" PR manually after first noticing it's actually stuck. Automated recovery of pending prowjobs would be useful.

But I agree, this may be too complicated for the small benefit it brings.
