### ISSUE TITLE
triage: go.k8s.io/triage fails to render in Google Chrome due to excessively large cluster data

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#22906]
**What happened**:

> Loading... parsing 0MB.

console:

```
VM106:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at interactive.js:338
(anonymous) @ interactive.js:338
setTimeout (async)
(anonymous) @ interactive.js:337
req.onload @ interactive.js:291
load (async)
get @ interactive.js:290
getData @ interactive.js:326
load @ interactive.js:365
(anonymous) @ index.html?test=Pods should support pod readiness gates:81
```

**What you expected to happen**:

results should load

**How to reproduce it (as minimally and precisely as possible)**:

load https://go.k8s.io/triage

**Please provide links to example occurrences, if any**:

https://go.k8s.io/triage

**Anything else we need to know?**:

https://kubernetes.slack.com/archives/C09QZ4DQB/p1625957726455500

**Comment by BenTheElder** [comment]
cc @spiffxp @MushuEE

**Comment by spiffxp** [comment]
/assign
I'll take a look

**Comment by spiffxp** [comment]
Hey so, when I visited go.k8s.io/triage, it counted up as far as 600MB before dropping to 0.  That is way, way too high.

I think it's ingesting some poison data (aka data that doesn't cluster well and is causing it to slow way down)
![Screen Shot 2021-07-15 at 11 44 24 AM](https://user-images.githubusercontent.com/49258/125840846-0db5686d-aca5-4cad-af58-aa4495cbffcd.png)

**Comment by spiffxp** [comment]
Let's choose a known good/bad
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-triage/1412216912305197056 - 2021-07-05, seems good
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-triage/1415707578314264576 - 2021-07-15, latest bad

Some choice lines from each log
```
good-build-log.txt
122:Operation completed over 17 objects/267.6 MiB.
4088:I0706 01:20:17.561731     141 cluster.go:148] Finished locally clustering 3912 unique tests (1646334 failures) in 7m15.500468367s
31434:I0706 01:27:05.893098     141 cluster.go:322] Finished clustering 3912 unique tests (1605090 failures) into 3595 clusters in 6m48.331330116s
31436:I0706 01:37:30.856375     141 summarize.go:162] Finished rendering results in 10m24.963227678s

bad-build-log.txt
130:Operation completed over 21 objects/423.3 MiB.
5780:I0715 16:41:47.902850     142 cluster.go:148] Finished locally clustering 5519 unique tests (1965545 failures) in 15m43.101649281s
40597:I0715 17:30:58.467614     142 cluster.go:322] Finished clustering 5519 unique tests (1888136 failures) into 4944 clusters in 49m10.562568486s
40599:I0715 17:52:43.354063     142 summarize.go:162] Finished rendering results in 21m44.886376366s
```

```
$ for x in good bad; do grep cluster.go:121 $x-build-log.txt | cut -d, -f3-9 | sort > $x-failures.txt; done
$ comm -23 good-failures.txt bad-failures.txt | wc -l
     735
$ comm -12 good-failures.txt bad-failures.txt | wc -l
    3177
```

So while the total volume of failures went up by ~1.5 the number of unique-to-bad failures is... pretty high.  Maybe we could find out what those tests are, when they were introduced, etc.

**Comment by spiffxp** [comment]
My "i just want a plot" foo is weak, tried out `termeter` this time.

Another way of visualizing this is looking at the size of files in gs://k8s-gubernator/triage/history; this is the most recent 180 days, right is most recent
![Screen Shot 2021-07-15 at 12 33 33 PM](https://user-images.githubusercontent.com/49258/125846855-d395cbb1-dfc1-4d2d-bb69-c3356dc591be.png)

So that first big jump on the right was May 14-15 range
```
   4829053  2021-05-12T23:31:26Z  gs://k8s-gubernator/triage/history/20210512.json
   4745150  2021-05-13T23:33:46Z  gs://k8s-gubernator/triage/history/20210513.json
   4497433  2021-05-14T23:51:59Z  gs://k8s-gubernator/triage/history/20210514.json
  13895380  2021-05-15T23:51:48Z  gs://k8s-gubernator/triage/history/20210515.json
  14337723  2021-05-16T23:16:36Z  gs://k8s-gubernator/triage/history/20210516.json
  17188088  2021-05-17T23:42:09Z  gs://k8s-gubernator/triage/history/20210517.json
```

Then it starts really taking off around July 6-7 range
```
  17713852  2021-07-05T23:56:56Z  gs://k8s-gubernator/triage/history/20210705.json
  14753725  2021-07-06T23:28:56Z  gs://k8s-gubernator/triage/history/20210706.json
  20646365  2021-07-07T23:21:37Z  gs://k8s-gubernator/triage/history/20210707.json
  27095119  2021-07-08T23:59:25Z  gs://k8s-gubernator/triage/history/20210708.json
  28079189  2021-07-09T22:55:53Z  gs://k8s-gubernator/triage/history/20210709.json
```

And I won't plot it, but for historical context this is way over anything previously seen as far as triage's output

**Comment by spiffxp** [comment]
Sorting purely by number of tests, it seems like `[sig-storage]` is our winner for largest increase in number of unique test failures that weren't happening 10 days ago.
```
$ comm -12 good-failures.txt bad-failures.txt | cut -d\  -f1-2 | uniq -c | sort -rg | head -n 20
 992  [sig-storage]
 219  k8s.io/kubernetes/pkg/apis/core/validation
 214  [sig-node]
 180  [sig-network]
 138  [OSPolicies]
 122  [GuestPolicies]
 120  k8s.io/kubernetes/test/integration/auth
 116  [k8s.io]
 110  [sig-api-machinery]
 105  [sig-apps]
  58  k8s.io/kubernetes/test/integration/scheduler_perf
  56  [sig-cli]
  50  k8s.io/kubernetes/vendor/k8s.io/api
  40  [OSPatch]
  36  k8s.io/kubernetes/pkg/registry/core/service/storage
  34  [sig-autoscaling]
  33  verify
  30  External
  26  k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration/conversion
  23  [sig-scheduling]
```

I mean... OK.  Chasing down the forensics is fun, but I have to admit I'm not actually sure how to mitigate this right now. I'm not sure it's reasonable to exclude tests by name, for example.

If it's possible or makes sense I'm wondering if it's time to do the brute force thing of capping off clustering past a certain time limit.  That might lose some low-qty but high-specificity clusters that are valuable.  But it's better than the nothing we're seeing right now

**Comment by BenTheElder** [comment]
It would be good to check in with sig storage about this spike though, because any mitigation we induce like "cap the time" can still leave clustering the remaining data impacted (in terms of latency, throughput, or the job failing when this gets even worse).

**Comment by lambdanis** [comment]
It looks fixed? No idea what happened, but I can search https://go.k8s.io/triage without issues now.

> Hey so, when I visited go.k8s.io/triage, it counted up as far as 600MB before dropping to 0. That is way, way too high.
Now it's showing 692.83MB FYI... And working 🤷‍♀️

**Comment by lambdanis** [comment]
Update: it's working in Firefox, not working in Chrome.

**Comment by BenTheElder** [comment]
I see it crash at 760+ MB now

**Comment by BenTheElder** [comment]
FWIW Safari also works, though the page load is not smooth, also due to the ~1GB payload I got a warning at the top of the tab from safari about excessive memory usage.

**Comment by BenTheElder** [comment]
It also looks like the actual data transfer for failure_data.json is a mere 54.3MB but with a > 17x compression factor (gzip) it expands to ~960 MB in memory now ...

**Comment by BenTheElder** [comment]
I think maybe this is related https://github.com/kubernetes/kubernetes/issues/103822

**Comment by BenTheElder** [comment]
Safari on macOS still seems to render this, but that's not a great answer for those not using a mac. It is > 1GB uncompressed now.

**Comment by BenTheElder** [comment]
It has gone back down to 45.73MB loaded / 885.4 MB in memory. I see it working in Firefox and Safari but not Google Chrome.

Time is trending down for the update job as well:
<img width="1259" alt="Screen Shot 2021-07-30 at 3 23 23 PM" src="https://user-images.githubusercontent.com/917931/127717359-65142e8e-f6c7-4b0e-89bc-7e0d50355c64.png">

**Comment by BenTheElder** [comment]
It's dropped by another 100mb or so to 39.9MB compressed / 778.8MB uncompressed, this may resolve itself.

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/23135 probably the reason the size went down.

**Comment by BenTheElder** [comment]
this renders in google chrome post #23135

**Comment by BenTheElder** [comment]
It's baaaack

**Comment by spiffxp** [comment]
I decided to dig into the data to see what was so large about it anyway
```bash
gsutil cp gs://k8s-triage/history/20211007.json .
<20211007.json jq keys
# [
#   "builds",
#   "clustered"
# ]
<20211007.json jq .clustered > 20211007.clustered.json
<20211007.json jq .builds > 20211007.builds.json
ls -lh 20211007*
# -rw-r--r--  1 spiffxp  primarygroup    18M Oct  7 15:30 20211007.builds.json
# -rw-r--r--  1 spiffxp  primarygroup   953M Oct  7 15:32 20211007.clustered.json
# -rw-r--r--  1 spiffxp  primarygroup   954M Oct  7 15:23 20211007.json
```

OK, it's the clustered data.  

Looking at the data a bit, it's a giant array of cluster objects.  Let's split those into their own JSON files and see if any stand out.
```bash
mkdir -p clusters
i=0; 
time <20211007.clustered.json jq -c --stream 'fromstream(1|truncate_stream(inputs))' \
  | while read -r x; do 
      echo $x > clusters/$i.json; 
      i=$(( i + 1 )); 
    done

# real	37m57.041s
# user	25m59.247s
# sys	17m47.116s
```

Which clusters are largest?
```
$ ls -lrSh clusters | grep M
# ...
-rw-r--r--  1 spiffxp  primarygroup    10M Oct  7 16:54 3449.json
-rw-r--r--  1 spiffxp  primarygroup    10M Oct  7 17:01 3885.json
-rw-r--r--  1 spiffxp  primarygroup    10M Oct  7 16:55 3629.json
-rw-r--r--  1 spiffxp  primarygroup    11M Oct  7 16:31 2940.json
-rw-r--r--  1 spiffxp  primarygroup    12M Oct  7 16:56 3646.json
-rw-r--r--  1 spiffxp  primarygroup    14M Oct  7 16:57 3677.json
-rw-r--r--  1 spiffxp  primarygroup    16M Oct  7 16:54 3459.json
-rw-r--r--  1 spiffxp  primarygroup    16M Oct  7 16:57 3678.json
-rw-r--r--  1 spiffxp  primarygroup    17M Oct  7 16:58 3691.json
-rw-r--r--  1 spiffxp  primarygroup    19M Oct  7 17:03 3913.json
-rw-r--r--  1 spiffxp  primarygroup    19M Oct  7 17:00 3878.json
-rw-r--r--  1 spiffxp  primarygroup    23M Oct  7 17:03 3896.json
-rw-r--r--  1 spiffxp  primarygroup    25M Oct  7 16:59 3831.json
-rw-r--r--  1 spiffxp  primarygroup    27M Oct  7 17:02 3893.json
-rw-r--r--  1 spiffxp  primarygroup    27M Oct  7 16:59 3830.json
-rw-r--r--  1 spiffxp  primarygroup    31M Oct  7 16:53 3403.json
-rw-r--r--  1 spiffxp  primarygroup    33M Oct  7 17:01 3888.json
-rw-r--r--  1 spiffxp  primarygroup    33M Oct  7 17:01 3880.json
-rw-r--r--  1 spiffxp  primarygroup    34M Oct  7 16:56 3657.json
```

IMO even 1MB+ of data for a given cluster is excessive, let alone 10MB+.  It's worth noting all of these large clusters are in the 3000's, and the total number of clusters in this data is 3977.  Given that clusters are sorted by largest number of failure occurrences, these are least likely to be seen / sought by contributors.

We're truncating failure text to 10K when clustering, so where is this coming from?

```
$ <clusters/3449.json jq '.text | length'
10330061
```

Ah.  It turns out we're rendering an example of failure text for each cluster, and we're not truncating that.  We should.

I've opened https://github.com/kubernetes/test-infra/pull/23952 to start with truncating it to 100K (an arbitrary guess)
