### ISSUE TITLE
check_projects.py runs too fast

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/test-infra#2291]
When I run check_projects.py after a while I start to see a bunch of these errors:

```
ERROR: gcloud crashed (BadStatusCodeError): HttpError accessing <https://cloudresourcemanager.googleapis.com/v1/projects/kubernetes-scale:setIamPolicy?alt=json>: response: <{'content-length': '566', ..., 'content-type': 'application/json; charset=UTF-8'}>, content <{
  "error": {
    "code": 429,
    "message": "Insufficient tokens for quota 'WriteGroup' and limit 'CLIENT_PROJECT-100s' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:32555940559'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/32555940559/apiui/credential"
          }
        ]
      }
    ]
  }
}
>

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
 could not update kubernetes-scale
```

It looks like we are hitting the rate limits of making IAM calls. We should add a rate limiter to the python script to slow it down a bit and keep ourselves under the limit. 

/cc @fejta

**Comment by fejta** [comment]
Just rerun the script a few times.

Imo not worth the investment making a script love this more robust given that we only run it one a year.

**Comment by roberthbailey** [comment]
Well, given how much drift we are seeing, we should be running it a lot more often. We should chat with @Kashomon to discuss how we can build some automation to manage these project permissions rather than re-running this script all the time.

**Comment by ixdy** [comment]
It looks like the main problem is that the script we use to create jenkins projects doesn't set the correct defaults.

**Comment by fejta** [comment]
We run this script less than 10x/year. The effort required to fix this is better spent elsewhere (like on better test failure notifications, for example).
