### ISSUE TITLE
`▶ Details` blocks should hint about expanding or not be used as much.

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#22911]
**What would you like to be added**:

These are relatively un-styled on github.com and may not be obvious to expand.

A lot of bot comments hide the really useful details on how to deal with a problem behind these.

We should consider not using these or at least making their own usage more obvious.
 
**Why is this needed**:

I haven't really seen `<details>` blocks used on the web, certainly not unstyled, and I'm observing what I strongly suspect to be new users not expanding and reading these. I suspect that at least some of them would read these but aren't figuring out that they need to click on the `▶`

@kubernetes/sig-contributor-experience

**Comment by MadhavJivrajani** [comment]
/assign

@BenTheElder I think changing `Details` to something along the lines of `Click here for more details` might help. Not sure if we should remove the `<details>` block,  mainly because too much text in a comment can also cause non-attention to the info provided ("too much text" is again subjective). WDYT?

**Comment by nikhita** [comment]
@MadhavJivrajani It might be helpful to get data on which prow plugins use `Details` today. This can help us identify areas of friction in a much clearer way.

**Comment by spiffxp** [comment]
/sig contributor-experience
@BenTheElder do you have a list of comments that use this and which ones should be changed?

**Comment by MadhavJivrajani** [comment]
From what I could tell, the following use `<details>` blocks:
- `assign`
- `blockade`
- `bugzilla`
- `buildifier`
- `cat`
- `cla`
- `dco`
- `dog`
- `golint`
- `goose`
- `help`
- `invalidcommitmsg`
- `label`
- `lgtm`
- `lifecycle`
- `milestone`
- `override`
- `pony`
- `project`
- `releasenote`
- `retitle`
- `shrug`
- `sigmention`
- `skip`
- `trick-or-treat`
- `trigger`
- `updateconfig`
- `verify-owners`
- `yuks`

**Comment by BenTheElder** [comment]
As noted above there are a *lot* of these. I don't have a list, I'm looking for input on the concept.

I've never seen the unstyled <details> block anywhere else on the web myself and I can't say that I've seen any other GitHub automation use it. I suspect that without a demonstration or prior experience people probably just never read any of the contents which makes it somewhat less useful.

But it's hard to tell for sure and I'm not sure what we should do instead. In emails these aren't collapsed IIRC so it might make sense to stop using them at all.


I wouldn't ask anyone to move forward on this without more input on what the solution should be from contribex etc.
