### ISSUE TITLE
ci-kubernetes-node-swap-fedora job failing to run on ssh command

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#22964]
**What happened**:

```
 W0721 14:19:08.668] E0721 14:19:08.667840    6410 ssh.go:116] failed to run SSH command: out: prow@34.83.103.131: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

**What you expected to happen**:

Tests to run.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-fedora/1417848497146695680

**Please provide links to example occurrences, if any**:

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora

**Anything else we need to know?**:

/sig node
/kind failing-test
cc @ike-ma

**Comment by BenTheElder** [comment]
Has anyone tested that this VM image supports ssh? IIRC for ssh to work the way the tooling is doing it the VM must be running both sshd and the agent to inject keys.

More generally has this e2e configuration been tested outside of CI in any way?

**Comment by ike-ma** [comment]
This image was tested manually during development, and in presubmit. I'm not sure about the e2e-ci. 

```
ARTIFACTS="${TMPDIR}" JENKINS_GCE_SSH_PRIVATE_KEY_FILE="${SSH_KEY}" KUBE_SSH_USER=core \
/usr/local/google/home/ikema/go-k8s-oss/bin/kubetest \
  --up \
  --down \
  --test \
  --provider=gce \
  --deployment=node \
  --gcp-project="${PROJECT}" \
  --gcp-zone="${ZONE}" \
  '--node-test-args=--feature-gates=DynamicKubeletConfig=true,LocalStorageCapacityIsolation=true --container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--fail-swap-on=false --cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service --non-masquerade-cidr=0.0.0.0/0" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"' \
  "--node-args=--image-config-file="${IMAGE_CONFIG_OUT} \
  --node-tests=true \
  '--test_args=--nodes=1 --focus="\[NodeAlphaFeature:NodeMemorySwap\]" --skip="\[Flaky\]"' \
  '--timeout=300m' 2>&1 | tee -i "${TMPDIR}/build-log.txt"
```

I remember I need to login to Fedora machine as `core` user to ssh into it. 

From the error message, it seems the execution user is `prow`

**Comment by ike-ma** [comment]
Compare to the presubmit CI: https://github.com/kubernetes/test-infra/pull/22453/commits/9180f79054a261371d1ab746acaacb8b1f4a039a#diff-9495ba672589316a9265fd090ecb9c3c74fd414a11386acafda27df4bd409409R632

The e2e CI missed `- --env=KUBE_SSH_USER=core`: https://github.com/kubernetes/test-infra/pull/22809/commits/cdea53836c06503f6186b235b15be2790babde37
