### ISSUE TITLE
How to test a postsubmits job in kind?

### ISSUE THREAD

**Issue by yuswift** [kubernetes/test-infra#22963]
By referring to [using-pj-on-kindsh](https://github.com/kubernetes/test-infra/blob/master/prow/build_test_update.md#using-pj-on-kindsh), I can test a presubmits job in kind(e.g. go build). Here comes the question, in the postsubmits job, I need to build images and push images. But the pod is running in kind, which means I can't use `docker build`. Are there any other solutions to implement  that, I really don't want to test the postsubmits job in the real prow environment. Any suggestions would be appreciated!
/help

**Comment by BenTheElder** [comment]
> But the pod is running in kind, which means I can't use docker build

Running in kind has nothing to do with it. prow.k8s.io and many other clusters also run containerd based nodes and you cannot rely on mounting the host socket if you wish to remain portable.

If you must use "docker build" you can run docker in docker (insecure like kind) or run it in some external environment (e.g. by submitting a cloud build, which is how we push images). Alternatively you can use something like `ko`.

**Comment by yuswift** [comment]
> > But the pod is running in kind, which means I can't use docker build
> 
> Running in kind has nothing to do with it. prow.k8s.io and many other clusters also run containerd based nodes and you cannot rely on mounting the host socket if you wish to remain portable.
> 
> If you must use "docker build" you can run docker in docker (insecure like kind) or run it in some external environment (e.g. by submitting a cloud build, which is how we push images). Alternatively you can use something like `ko`.

Thanks.
/close
