### ISSUE TITLE
Openshift Prow issue: ci/prow/e2e-metal-ipi-ovn-ipv6 required

### ISSUE THREAD

**Issue by lmzuccarelli** [kubernetes/test-infra#22999]
I'm seeing a failure on this test  ci/prow/e2e-metal-ipi-ovn-ipv6 — Job failed. I noticed it is marked required, is it possible to remove the required "label"

**Comment by BenTheElder** [comment]
This repo only hosts the tooling sources and prow.k8s.io, not openshift configuration. You should probably file a bug there.

Generally if a job is marked required that is intended and you should try to get it to pass (comment /retest, check the failure logs against your code).

A repo administrator / the owners of the config can change if the job is required or bypass the setting.

**Comment by lmzuccarelli** [comment]
@BenTheElder Thanks for the help

**Comment by BenTheElder** [comment]
BTW these configs appear to be in https://github.com/openshift/release, thanks @jeefy
