### ISSUE TITLE
Prow integration test: smoke testing tide

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#23025]
**What would you like to be added**:

Prow integration test deploys prow components in kind cluster, which should be able to be used for smoke testing tide, by deploying tide in kind cluster and checking that tide merges a PR on fake github server.

**Why is this needed**:

https://kubernetes.slack.com/archives/C09QZ4DQB/p1627313972056200

### Changes Required

* Add `tide` at [`testimage-push`](https://github.com/kubernetes/test-infra/blob/f9fb6d28ebbcf77dc0b99d741b8df5f5d85c739e/prow/BUILD.bazel#L66) target, so that tide is pushed to `localhost:5000` registry
* Deploy tide during integration test https://github.com/kubernetes/test-infra/blob/f9fb6d28ebbcf77dc0b99d741b8df5f5d85c739e/prow/test/integration/setup-cluster.sh#L33, and cleanup `tide` after integration test https://github.com/kubernetes/test-infra/blob/f9fb6d28ebbcf77dc0b99d741b8df5f5d85c739e/prow/test/integration/cleanup.sh#L23
* Add tide deployment yaml at https://github.com/kubernetes/test-infra/tree/master/prow/test/integration/prow/cluster, so that the deployment works. Modifications involve:
  * `tide_service.yaml` and `tide_rbac.yaml` can be symlinks from https://github.com/kubernetes/test-infra/tree/master/config/prow/cluster.
  * `tide_deployment.yaml` will at least requires changing image registry to `localhost:5000` like https://github.com/kubernetes/test-infra/blob/f9fb6d28ebbcf77dc0b99d741b8df5f5d85c739e/prow/test/integration/prow/cluster/hook_deployment.yaml#L41.
  * `github-endpoint` should be changed to `fakeghserver`, which was from https://github.com/kubernetes/test-infra/tree/master/prow/test/integration/fakeghserver.
  * `--history-uri` and `--status-path` are both GCS paths, which is not preferred for integration tests, they can be changed to local path which is supported https://github.com/kubernetes/test-infra/blob/17297acb70dcdfe555ce08bb7fe07dbff817d43e/prow/io/opener.go#L211. Need to remember mounting a volume for this purpose.
* Existing fake github server only implemented partial github APIs, will need to add APIs that tide uses at https://github.com/kubernetes/test-infra/tree/master/prow/test/integration/fakeghserver

**Comment by chaodaiG** [comment]
/area prow
/help
cc @YuviGold

**Comment by YuviGold** [comment]
Seems like this was already resolved as part of https://github.com/kubernetes/test-infra/pull/22582

**Comment by chaodaiG** [comment]
> Seems like this was already resolved as part of #22582

That's correct!

**Comment by fgimenez** [comment]
> Seems like this was already resolved as part of #22582

In #22582 tide is deployed to prevent deck from complaining but nothing else, I think that the check for tide merging a PR on fake github server is missing, is that correct?

**Comment by YuviGold** [comment]
> > Seems like this was already resolved as part of #22582
> 
> In #22582 tide is deployed to prevent deck from complaining but nothing else, I think that the check for tide merging a PR on fake github server is missing, is that correct?

Yes, that's correct. We should have tide integration tests as well.

**Comment by fgimenez** [comment]
> Yes, that's correct. We should have tide integration tests as well.

Cool thx! @YuviGold I'd love to give it a try, is it ok if I pick it up, or do you want to work on it yourself?

**Comment by YuviGold** [comment]
@fgimenez Let me give it a shot. It will help me understand some internals :)

**Comment by fgimenez** [comment]
/assign @YuviGold 
/remove-help

> @fgimenez Let me give it a shot. It will help me understand some internals :)

Absolutely! feel free to ping if you have any questions, will try to help if I can :)

**Comment by YuviGold** [comment]
Hey guys,
I started to work on having an integration test to verify `tide`, but unfortunately got stuck when queries from tide got to the `fakeghserver` returned empty. (although debug prints could show data from `fakeghserver` is sent back as expected)
The big issues here is the first time the GitHub v4 API (GraphQL) is being tested as part of the integration tests. if someone wanna give a hand or take it from here is more than welcome
WIP can be seen here https://github.com/kubernetes/test-infra/compare/master...YuviGold:tide-smoke-test

@chaodaiG WDYT maybe we can merge part of it so not all the work will go to waste even if it's not being used? 
for example, having the functionality to create pull requests as part of the `fakeghserver` and also configuring `tide` with correct deployment variables in order to create tide queries

**Comment by YuviGold** [comment]
I opened a related ticket on the GitHub v4 API lib https://github.com/shurcooL/githubv4/pull/90

**Comment by chaodaiG** [comment]
I think it's a good idea to merge the portion that can be used, please make sure leave good comments on this part and link here
