### ISSUE TITLE
Indicate optional job on retest comment

### ISSUE THREAD

**Issue by YuviGold** [kubernetes/test-infra#23062]
**What would you like to be added**:
When the retest help message is shown, it should indicate what jobs are required and what are not.

**Why is this needed**:
On https://github.com/kubernetes/test-infra/pull/22850 the `/retest-required` command was introduced.
Now whenver the retest comment is presented, it suggests to use either the `/retest` command to run everything or the `/retest-required` to run only the mandatory jobs. But it isn't clear which jobs are required and which are optional.

e.g.
Current comment - https://github.com/openshift/assisted-service/pull/2263#issuecomment-888958497

New comment - 
```
Test name | Commit | Details | Required | Rerun command
-- | -- | -- | -- | --
ci/prow/e2e-metal-assisted-olm | c5bb910 | link | X | /test e2e-metal-assisted-olm
ci/prow/e2e-metal-assisted | c5bb910 | link | V | /test e2e-metal-assisted
ci/prow/e2e-metal-assisted-operator-ztp | c5bb910 | link | V | /test e2e-metal-assisted-operator-ztp

```

**Comment by spiffxp** [comment]
/sig testing
/close
fixed by https://github.com/kubernetes/test-infra/pull/23016

**Comment by spiffxp** [comment]
/assign @YuviGold 
(who ended up fixing this, thanks!)

**Comment by YuviGold** [comment]
@spiffxp actually this is a different issue.
You're talking about https://github.com/kubernetes/test-infra/issues/23014 which requested the **test help command** to distinct between the available jobs.
This issue is about making the **retest help command** clearer. Since the `/retest-required`  command was introduced by @alvaroaleman , it's unclear which command calls which failing jobs.

e.g. in here, it's not clear which jobs are required and which are optional.
![Screenshot from 2021-08-10 09-33-01](https://user-images.githubusercontent.com/29873449/128819391-dced8726-ed25-4338-af65-3c19226085ec.png)

I'd like to reopen it as this information is still missing.
/reopen

**Comment by YuviGold** [comment]
The new retest help message works :)
![Screenshot from 2021-09-11 21-10-19](https://user-images.githubusercontent.com/29873449/132957253-ea3bf941-8469-4bb5-91fe-93a6b5758e62.png)

**Comment by YuviGold** [comment]
Code got reverted due to resources consumption on https://github.com/kubernetes/test-infra/pull/23599
Details can be viewed on the original PR.
I am going to see if this feature can be achieved using Prowjob annotation as @cjwagner suggested on https://github.com/kubernetes/test-infra/pull/23484#issuecomment-919412357
