### ISSUE TITLE
Format of LOG_DUMP_EXTRA_FILES is inconsistent between log-dump.sh and logexporter

### ISSUE THREAD

**Issue by mborsz** [kubernetes/test-infra#23092]
**What happened**:

While log-dump.sh expects LOG_DUMP_EXTRA_FILES to be space-separated: 
https://github.com/kubernetes/test-infra/blob/9ba1a2baaf8e00f05f17e62b9bd1e43e8f387786/logexporter/cluster/log-dump.sh#L325

logexporter expects this flag to be comma-separated (see https://pkg.go.dev/github.com/spf13/pflag#StringSlice):
https://github.com/kubernetes/test-infra/blob/9ba1a2baaf8e00f05f17e62b9bd1e43e8f387786/logexporter/cmd/main.go#L44

This basically means that there is no good way to providing more than one value to that flag that would be universally accepted by all both log-dump.sh script and logexporter.

We should unify this.

**Comment by spiffxp** [comment]
/sig testing
/sig scalability
IIRC this is where logexporter originated
