### ISSUE TITLE
`cluster` and `repo` in `plank.default_decoration_config_entries[].config` don't support regexes

### ISSUE THREAD

**Issue by LorbusChris** [kubernetes/test-infra#23096]
**What happened**:
The plank README (https://github.com/kubernetes/test-infra/blob/master/prow/plank/README.md#configuration) states regexes are supported in the `plank.default_decoration_config_entries[].config.cluster` and `plank.default_decoration_config_entries[].config.repo` fields, but looking at the code it doesn't look like they actually are:
https://github.com/kubernetes/test-infra/blob/8f639d55cbd9aeeaabb4e8f35042b6b9f94d1dd6/prow/config/config.go#L567-L572

**What you expected to happen**:
Regex string values are supported in the `plank.default_decoration_config_entries[].config.cluster` and `plank.default_decoration_config_entries[].config.repo`

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
- the  `matches` function runs before `validateComponentConfig()` is called, i.e. the `repo` and `cluster` field values in `default_decoration_config_entries` aren't validated before they are matched against.
- terrible solution for the `cluster` field that I'm not going to PR:
```go
// matches returns true if all the filters for the entry match a job.
func (d *DefaultDecorationConfigEntry) matches(repo, cluster string) bool {
	repoMatch := d.OrgRepo == "" || d.OrgRepo == "*" || d.OrgRepo == repo || d.OrgRepo == strings.Split(repo, "/")[0]
	var clusterMatch bool
	if d.Cluster == "" || d.Cluster == "*" {
		clusterMatch = true
	} else {
		clusterRegex, err := regexp.Compile(d.Cluster)
		if err != nil {
			clusterMatch = false
		} else {
			clusterMatch = clusterRegex.MatchString(cluster)
		}
	}
	return repoMatch && clusterMatch
}
```

**Comment by alvaroaleman** [comment]
@cjwagner should we just update the readme?

**Comment by LorbusChris** [comment]
I really think this should be properly fixed as matching cluster names against simple strings can force the config to become repetitive very quickly.

**Comment by cjwagner** [comment]
> @cjwagner should we just update the readme?

Yes we should update the README. This was an intentional decision, see the discussion here: https://github.com/kubernetes/test-infra/pull/20656#discussion_r573027022

If regex matching is desired please add new `cluster_re` and `repo_re` fields as mentioned there. We don't want to treat `cluster` and `repo` as regex because that would be inconsistent with the rest of the Prow config and also a breaking change.
