### ISSUE TITLE
Add a "TL;DR" equivalent of good-first-issue/help-wanted criteria in bot comment prompt for these issues

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/test-infra#23129]
**What should be cleaned up or changed**:
Currently, when an issue is created that is marked as `good-first-issue`, `help-wanted`: the bot prompts the user by providing a [link](https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md#good-first-issue) to the set of criteria to be met for an issue to qualify as a `good-first-issue` or a `help-wanted` issue.

Currently what is happening is that, quite a few good-first-issues/help-wanted issues are being created across many repositories, but for a lot of them don't provide enough for a new contributor/beginner to get started, or even ask relevant questions for further clarification. This often leads to folks reaching out asking for help, and I try and look at the issue and leave a few comments or remove the label and ping the author asking them to provide more context/info and then feel free to re-apply the label. But this isn't the best solution.

On bringing this up in the contribex meeting, there were a few ideas:
- A new issue template for good-first-issues/help-wanted issues
  - This might not work out since a lot of issues get converted to good-first-issues after some discussion has taken place, and the inverse is also true, i.e. some issues end up not being a good-first-issue after further discussion
- Update the bot's prompt to include a summary of the points that the link provided reads. 
  - This helps not only when an issue is converted to a good-first-issue or un-marked as one, but also increases visibility of criteria to the author than a hyperlink. 
  - Along with this "TL;DR", the link will still be provided.

It would look something like this:
Currently:
```
@command-issuer:
This request has been marked as suitable for new contributors.

Please ensure the request meets the requirements listed here<link>.

If this request no longer meets these requirements, the label can be removed
by commenting with the /remove-good-first-issue command.
```
After updating:
```
@command-issuer:
This request has been marked as suitable for new contributors.

Please ensure the request has:
- *No Barrier To Entry*
- *A Solution Explained*
- *Provides Context*
- *Identifies Relevant Code*
- *Ready to Test*

For more information on these criteria, please see here<link>.

If this request no longer meets these requirements, the label can be removed
by commenting with the /remove-good-first-issue command.
```

This will not fully alleviate the issue at hand, but would definitely increase the visibility of the criteria for such issues.

---

I can work on this after getting some feedback (if any).
/assign
/area prow
/area github-management
/sig contributor-experience
/cc @mrbobbytables @nimbinatus @jberkus @nikhita 

Thanks!

**Comment by jberkus** [comment]
/lgtm

solution was discussed and approved at SIG-Contribex meeting.
