### ISSUE TITLE
Do not merge PR if not all reviewers approved it

### ISSUE THREAD

**Issue by piosz** [kubernetes/test-infra#2322]
PRs pretty often has more than one reviewer/approver. When one of them has enough permissions and writes /lgtm /approve, the PR will be queued for merge without waiting for the others.

cc @fgrzadkowski

**Comment by krzyzacy** [comment]
Isn't this the right behavior?

**Comment by piosz** [comment]
There is of course no the right answer here. It's different from what we have internally. My personal feeling is that if you assign 2 people as reviewers you want LGTM from them. Otherwise you would just cc them.

**Comment by krzyzacy** [comment]
As a reviewer if I want other people to also take a look I normally would express LG without write the command, and let other reviewers have the final judgement?

@grodrigues3 @apelisse probably can give a better explanation.

**Comment by grodrigues3** [comment]
yeah, i've seen that as the convention.

People generally write `LGTM but i'll wait for @otherUser's comments first`

**Comment by piosz** [comment]
So basically the difference here is who should be responsible for defining the list of required/sufficient reviewers - in the current state this is up to reviewers. With what I proposed this can be both: PR author by assigning a set of people and reviewer who can remove some of them from the list and grant lgtm/approve.

**Comment by fejta** [comment]
+1 to Garrett's comments.

Do we have empirical evidence of a problem that is occurring that this would solve?

Also, if we do have examples I would suggest we first try to address this problem by clarifying proper PR etiquette to the people involved.

This creates the same result without risking unintended side effects (such as slowing down other PRs). It also allows us to invest the time we might spend implementing this complicated behavior into solving some of our many other problems.
