### ISSUE TITLE
Node testgrid dashboard cleanup

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#23231]
**What should be cleaned up or changed**:

As discussed in the [SIG Node CI Subproject meeting](https://docs.google.com/document/d/1fb-ugvgdSVIkkuJ388_nhp2pBTy_4HEVg5848Xy7n5U/edit#bookmark=id.9bmalcqmp7z) today and last week, our testgrid dashboards are a bit of a mess:

![Screenshot at 2021-08-12 12-14-04](https://user-images.githubusercontent.com/4706131/129255763-ba133c19-44fd-4e98-bea8-3b819c1cdda9.png)

Here is our cleanup plan:

- [x] Move all `pr-*` jobs across various tabs into a new `sig-node-presubmits` tab
- [x] Consider consolidating redundant tabs (e.g. `sig-node-containerd` and `sig-node-containerd-io`)
- [x] Remove double listed jobs to ensure they are filed in the right place (e.g. release-blocking jobs are already in `sig-node-release-blocking` and don't also need to be included under `sig-node-kubelet`)

**Provide any links for context**:

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-master

/cc @adisky @matthyx @ipochi 
/sig node

**Comment by matthyx** [comment]
Here is the list of all dashboards (sorted):
```
dashboard_groups:
- name: sig-node
  dashboard_names:
    - sig-node-cadvisor
    - sig-node-containerd
    - sig-node-containerd-io # jobs in containerd/containerd repository
    - sig-node-cos
    - sig-node-cri
    - sig-node-cri-o
    - sig-node-cri-tools
    - sig-node-critical # This dashboard contains jobs that sig-node has deemed critical to the greater operation of the sig. They should always be green.
    - sig-node-kubelet
    - sig-node-node-feature-discovery
    - sig-node-node-problem-detector
    - sig-node-ppc64le
    - sig-node-presubmits
    - sig-node-release-blocking # This is a replica of sig-node jobs that are release blocking.
    - sig-node-security-profiles-operator
```

**Comment by adisky** [comment]
`sig-node-critical` has only one job containerd node conformance https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubernetes/sig-node/config.yaml#L22, is this critical tab needed now considering we have containerd mandatory presubmit job?

**Comment by adisky** [comment]
Also should we also think about removing windows jobs from `sig-node-containerd`  tab? 
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-windows/windows-gce.yaml#L405

**Comment by matthyx** [comment]
Agree with both... @ehashman wdyt?

**Comment by SergeyKanzhelev** [comment]
the idea of critical tab was a stepping stone to promote to release blocking as far as I remember. It didin't work as was intended

I'd vote for removing windows from containerd. But let's ping @marosset on the PR

**Comment by adisky** [comment]
> the idea of critical tab was a stepping stone to promote to release blocking as far as I remember. It didin't work as was intended

Thanks for letting us know about this!! Lets keep it as it is.

> I'd vote for removing windows from containerd. But let's ping @marosset on the PR

for windows, lets wait for @marosset feedback

**Comment by marosset** [comment]
I'm OK with removing the windows tabs from `sig-node-containerd`.
We have Windows + containerd tests running as part of the SIG-Windows release informing dashboard https://testgrid.k8s.io/sig-windows-signal.

Since these are GCE jobs I'd like like either @pjh or @ibabou to ACK this

**Comment by ibabou** [comment]
I'm okay with removing the windows tabs from there. ACK. Having those as part of sig-windows-gce & sig-windows-*-release is sufficient.

**Comment by pjh** [comment]
+1, removing those Windows jobs from `sig-node-containerd` SGTM.

**Comment by adisky** [comment]
Thanks for the inputs from windows team, Now we have two items that need PR

- [ ] remove windows jobs from containerd dashboard https://testgrid.k8s.io/sig-node-containerd
e.g. remove containerd dashboard from here https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-windows/windows-gce.yaml#L405, This has to be done for other windows jobs in containerd dashboard as well
- [ ] move double listed jobs to ensure they are filed in the right place (e.g. release-blocking jobs are already in sig-node-release-blocking and don't also need to be included under sig-node-kubelet)
here remove jobs present in [release-blocking dashboard](https://testgrid.k8s.io/sig-node-release-blocking) from other sig node dashboards

you can use this https://cs.k8s.io/?q=node-kubelet-master&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra to search for jobs and dashboard.

**Comment by Debanitrkl** [comment]
I can work on with the PR regarding removing windows jobs from containerd dasboard

**Comment by rayandas** [comment]
Hey @adisky I can work on the second item (move double listed jobs to ensure they are filed in the right place).

**Comment by adisky** [comment]
Thanks @Debanitrkl @rayandas Thanks for taking this up
/assign @Debanitrkl @rayandas for the two items mentioned above

**Comment by Rajalakshmi-Girish** [comment]
Can someone please suggest the right place to have the `unit-tests` tab which is currently under `sig-node-ppc64le`? https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests

This test grid seems essential to track k8s unit test failures on ppc64le.
cc @ehashman @SergeyKanzhelev @matthyx

**Comment by Rajalakshmi-Girish** [comment]
> Can someone please suggest the right place to have the `unit-tests` tab which is currently under `sig-node-ppc64le`? https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests
> 
> This test grid seems essential to track k8s unit test failures on ppc64le. cc @ehashman @SergeyKanzhelev @matthyx

@spiffxp @mkumatag

**Comment by mkumatag** [comment]
> > Can someone please suggest the right place to have the `unit-tests` tab which is currently under `sig-node-ppc64le`? https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests
> > This test grid seems essential to track k8s unit test failures on ppc64le. cc @ehashman @SergeyKanzhelev @matthyx
> 
> @spiffxp @mkumatag

not sure either, wondering if we can add to some of the periodic jobs run(don't really know where are they??), worst case - lets create a new group called `ibm` like other groups we have in the testgrid.

**Comment by ehashman** [comment]
I have a couple more small PRs and then I think this is done.

#25497 #25496
