### ISSUE TITLE
Evaluate and improve node test-infra resource utilization

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#23232]
**What should be cleaned up or changed**:

We've received a few alerts recently on SIG Node project quota nearly being exhausted (e.g. https://kubernetes.slack.com/archives/C0BP8PW9G/p1628705424155600 https://kubernetes.slack.com/archives/C0BP8PW9G/p1628135137090800)

![Screenshot at 2021-08-12 12-22-55](https://user-images.githubusercontent.com/4706131/129256497-044dcf40-b8bf-4f6f-8db1-ac311ee60de4.png)

We seem to have significantly increased utilization over the past couple weeks: https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?panelId=9&fullscreen&orgId=1&from=1625124653988&to=1628779811679

Let's evaluate our current inventory of test jobs and see what we can consolidate or remove for cost savings, as [discussed at SIG Node CI](https://docs.google.com/document/d/1fb-ugvgdSVIkkuJ388_nhp2pBTy_4HEVg5848Xy7n5U/edit#bookmark=id.f8kr3n4hgwdj) today.

Expected outcome: we remove and consolidate some jobs to improve our utilization and reduce costs.

**Provide any links for context**:

/cc @BenTheElder @SergeyKanzhelev 
/sig node

**Comment by BenTheElder** [comment]
FWIW as well resources available I would tag in WG/SIG k8s infra. 
Also xref: https://github.com/kubernetes/k8s.io for projects (it's split, boskos definition is in test-infra IIRC but the projects themselves are there, like boskos is SIG Testing but the projects are ??)
