### ISSUE TITLE
gubernator: please link to jobs configs and cloud console for the project

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#2326]
This would speed up debugging a bit.  E.g. in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-1.5-downgrade-cluster/113 I would like to observe the running test, so I need to go find the job config to find the name of the project, then examine that project.  A direct link (to both) would be great.

**Comment by rmmh** [comment]
The build log has the lines:

    I0323 04:18:56.611] PROJECT=k8s-gce-dg-1-6-1-5-dwngr-clu

That could be easily linked to the cloud console. Do you still want to look at the scenario data otherwise?

**Comment by lukaszgryglicki** [comment]
I can work on it but I would need more details, like example links to generate etc.

**Comment by rmmh** [comment]
Note that job configs are now available in [artifacts/prow_podspec.yaml](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/25380/artifacts/prow_podspec.yaml).
