### ISSUE TITLE
boskos: node-e2e pool is getting exhausted

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#23291]
**What happened**:

Alerts have been firing in #testing-ops more frequently over time:

>[FIRING:1] Resource exhausted (0% free) (node-e2e-project 104.197.27.114:9090 prow-monitoring/prow high node-e2e-project)
>@test-infra-oncall The Boskos resource "node-e2e-project" has been exhausted (currently 0% free). See the Boskos resource usage dashboard.

**What you expected to happen**:

For boskos not to run out of capacity

**How to reproduce it (as minimally and precisely as possible)**:

Wait for the project to receive enough traffic

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

The node-e2e pool was an arbitrary pool made during a time when node-e2e jobs were pinned to a single GCP project that was shut down for security concerns.  There is nothing special about how the projects within it are configured.  We decided to use a pool rather than pin to a project, and opted for a new `node-e2e` pool rather than the main `gce` pool in case more projects got flagged for security concerns, so as to minimize the blast radius.

It now appears that there is more traffic or there are more jobs using this pool, and we're starting to run out of capacity more frequently. 

![Screen Shot 2021-08-18 at 6 43 13 AM](https://user-images.githubusercontent.com/49258/129908873-1b999870-55b4-4cd3-bc14-5601cea36c8b.png)
(from: https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?panelId=9&fullscreen&orgId=1&from=now-30d&to=now)

Since the `node-e2e` pool was initially created by arbitrarily stealing projects from the `gke` pool, it makes sense to do so again to grow the capacity of the pool. Alternatively, we should get rid of the `node-e2e` pool and dump everything back into the larger `gce` pool.

/area boskos
/sig node
/sig testing
/priority critical-urgent

**Comment by spiffxp** [comment]
Opting to grow the pool: https://github.com/kubernetes/test-infra/pull/23292

**Comment by ameukam** [comment]
Related : https://github.com/kubernetes/test-infra/issues/23232.

**Comment by ehashman** [comment]
Discussed previously at [SIG Node CI 08/12](https://docs.google.com/document/d/1fb-ugvgdSVIkkuJ388_nhp2pBTy_4HEVg5848Xy7n5U/edit#bookmark=id.f8kr3n4hgwdj).

/assign @SergeyKanzhelev

**Comment by spiffxp** [comment]
I tried a PR to steal from gke projects and add to node but it didn't appear to get picked up by boskos. I think some manual intervention may be required

**Comment by spiffxp** [comment]
Honestly I would avoid using the node pool and go back to using the normal gce pool unless or until you find there's something special you need that merits a separate pool

**Comment by ehashman** [comment]
@SergeyKanzhelev to follow up with @BenTheElder and team to look into getting rid of the separate node e2e pool.

**Comment by spiffxp** [comment]
I'm getting the ball rolling on migrating away from the node pool with https://github.com/kubernetes/test-infra/pull/23777

**Comment by spiffxp** [comment]
/help

Steps to close this out should be pretty straightforward:
- [ ] remove `--gcp-project-type=node-e2e-project` from any job configs that use it
- [ ] make sure the resulting jobs aren't broken (or at least, behaving no differently than before)
- [ ] once no more jobs use it, remove the `node-e2e-project` pool from `config/prow/cluster/boskos-resources.yaml`

I would recommend not doing everything in one big blast unless you're prepared to babysit a lot of jobs all at once. This is part of why I started with only a few jobs in the PR linked above

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind failing-tests

(removing from sig nod bugs dashboard)

**Comment by ehashman** [comment]
given https://github.com/kubernetes/test-infra/issues/23291#issuecomment-929486402

since we're not done and we probably don't want to be changing jobs this late in the release,
/milestone v1.24

**Comment by SergeyKanzhelev** [comment]
this looks to be ok now:

![image](https://user-images.githubusercontent.com/9950081/149590392-f11d2b77-ec07-47e3-ae90-2b1411fba1fc.png)

/close

please re-open if still needed

**Comment by ameukam** [comment]
/reopen

The issue came back.


>[[FIRING:1] Resource exhausted (0% free) (gce-project 35.225.208.117:9090 prow-monitoring/prow high gce-project)]>>(http://alertmanager-prow-1:9093/#/alerts?receiver=slack-alerts)
[@test-infra-oncall](https://kubernetes.slack.com/admin/user_groups) The Boskos resource "gce-project" has been exhausted (currently 0% free). See the [Boskos resource usage dashboard](https://monitoring.prow.k8s.io/d/wSrfvNxWz/boskos-resource-usage?orgId=1).

**Comment by ehashman** [comment]
@ameukam that's a different pool than the one reported in the issue (node-e2e-project). I believe we've moved everything out of that already.

Let's create a new issue if we have a new pool exhaustion.

/close
