### ISSUE TITLE
Duplicate slack reports

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#23315]
**What happened**:

All slack reports are now sent 2x

**What you expected to happen**:

Reports are sent 1x

**How to reproduce it (as minimally and precisely as possible)**:

Look at `#test-failures` in Istio slack I suppose..

**Please provide links to example occurrences, if any**:
![2021-19-08_09-40-28](https://user-images.githubusercontent.com/623453/130108861-e306858c-ca8d-4960-a3b6-f99b2f88dec3.png)

First occurance is 3:17 PM on 8/18/2021. We bumped from f9d80a9dc8 to b81cb0bc7b at 1:35 pm the same day

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
@howardjohn the last change to crier was made on aug 3 (1388b400445f81ceaf5deea18d2d9fa269f4623b). Do you by change maybe have multiple replicas of crier running? It doesn't use leader election

**Comment by cjwagner** [comment]
There is only 1 replica and `--slack-workers=1`. The logs don't seem to show any duplicated reporting.  Example logs from reporter="slackreporter":
>D 2021-08-19T17:28:20Z Determined should report
I 2021-08-19T17:28:20Z Will report state 
I 2021-08-19T17:28:21Z Reported job(s), now will update pj(s). 
I 2021-08-19T17:28:21Z Successfully updated report state on prowjob
