### ISSUE TITLE
Override branch protected required status checks

### ISSUE THREAD

**Issue by YuviGold** [kubernetes/test-infra#23340]
**What would you like to be added**:
Allow using the `/override` command to required status checks.

**Why is this needed**:
Currently, the override plugin looks only on ongoing commit statuses.
In case there is a required status check configured that doesn't appear under the commit statuses then it's impossible to override it.

e.g.
In the following example, Jenkins is configured as a required status check.
But Jenkins didn't return any result to the commit so it doesn't appear under statuses.
![Screenshot from 2021-08-23 13-59-48](https://user-images.githubusercontent.com/29873449/130491291-b3eca54c-f97a-40b1-af07-a2f030d7381d.png)

```bash
➜  test-infra git:(master) ✗ gh api "repos/openshift/assisted-service/statuses/8f2dc726627f0d2df0d32f4bdc27ebd33667f011" | jq '.[].context' | sort -u
"ci.ext.devshift.net PR build"
"ci/prow/ci-index"
"ci/prow/e2e-metal-assisted"
"ci/prow/e2e-metal-assisted-kube-api"
"ci/prow/e2e-metal-assisted-operator-ztp"
"ci/prow/images"
"ci/prow/lint"
"ci/prow/subsystem-aws"
"ci/prow/subsystem-kubeapi-aws"
"tide"
```
vs.
```bash
➜  test-infra git:(master) ✗ gh api "repos/openshift/assisted-service/branches/master" | jq '.protection.required_status_checks.contexts'
[
  "ci.ext.devshift.net PR build",
  "continuous-integration/jenkins/pr-merge",
  "ci/prow/lint",
  "ci/prow/ci-index",
  "ci/prow/images"
]
```

**Comment by petr-muller** [comment]
I don't think we should grow Prow's scope to manage non-Prow results (I [elaborated](https://github.com/kubernetes/test-infra/pull/23342#issuecomment-904049156) on the linked PR)

**Comment by fejta** [comment]
> In the following example, Jenkins is configured as a required status check. But Jenkins didn't return any result to the commit so it doesn't appear under statuses.

a) You can resolve this by using prow instead of jenkins to trigger jobs.
b) It seems like jenkins shoul be responsible for correctly reporting its status (including providing the ability to manually override)

**Comment by YuviGold** [comment]
> > In the following example, Jenkins is configured as a required status check. But Jenkins didn't return any result to the commit so it doesn't appear under statuses.
> 
> a) You can resolve this by using prow instead of jenkins to trigger jobs.
> b) It seems like jenkins shoul be responsible for correctly reporting its status (including providing the ability to manually override)

@fejta 
a. Sure. But that's another discussion.
(1) Although it's optimal that all the jobs would be centralized; It's reasonable that a repository that interacts with different tools to have multiple contexts from different CI instances.
(2) For an ongoing project to transform fully to Prow takes a lot of time. This feature could allow this change to be more gradual.

b. Of course. But sometimes it doesn't due to  outages. In that case when the branch is being required and protected than there's no way even for a user with write permissions to push a PR (since it's blocked by GitHub).
The override plugin can solve that as it does any other failure.

For example, we recently had issues with 1. proxy webhooks errors. 2. credentials gettings revoked. 3.   Jenkins is down for maintenance.
All of those could cause PRs to get stuck. Fixing those outages take time while a maintainer could override a valid context so it won't get blocked.
