### ISSUE TITLE
lgtm and release note commands race

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#2336]
In https://github.com/kubernetes/kubernetes/pull/43601, I wrote:
```
@k8s-bot ok to test
/lgtm
/release-note-none
```

The /lgtm command LGTM'd the PR, and assigned it to me, but the /release-note-none command didn't take because I wasn't assigned yet. I was able to do /release-note-none in the next command once it was assigned to me.

**Comment by grodrigues3** [comment]
@Sevii can you fix this?

**Comment by spxtr** [comment]
I think we can just remove the requirement to be assigned to set a release-note, and instead just require you be an org member. That wasn't a very good requirement in the first place.

**Comment by Sevii** [comment]
@grodrigues3 I can take a look later today.

**Comment by Sevii** [comment]
@spxtr I created a PR  (https://github.com/kubernetes/test-infra/pull/2508) to remove the requirement to be assigned or a reviewer. I am not sure if this will handle the requirement to be an org member, I will need to find that functionality.
