### ISSUE TITLE
testcase `pull-kubernetes-typecheck` failed more frequently 

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/test-infra#23374]
**What happened**:
Hi, I'm not familiar with test-infra. But as the title described, I found `pull-kubernetes-typecheck` failed more frequently. I run `make verify WHAT="gofmt typecheck"` locally, it passed however. 

**What you expected to happen**:
Tests success.

**How to reproduce it (as minimally and precisely as possible)**:
/test pull-kubernetes-typecheck

**Please provide links to example occurrences, if any**:
prow: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104247/pull-kubernetes-typecheck/1430759600583348224
testgrid: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-typecheck

**Anything else we need to know?**:
None.

**Comment by danmillwood** [comment]
Incase this is related, I wanted to mention it here.  Im setting up a development environment for Kubernetes.  The development guide recommends a linux with at least 8Gb memory.  When I run 'make verify' the following 3 tests all fail with out of memory 

hack/make-rules/../../hack/verify-typecheck-dockerless.sh
hack/make-rules/../../hack/verify-typecheck-providerless.sh
hack/make-rules/../../hack/verify-typecheck.sh

I tried increasing the VM memory to 16Gb and that got the first two to pass, but the last still fails. 
This is with go 1.17 and compiling master branch

**Comment by liggitt** [comment]
reducing parallelism seems like a good short-term mitigation

**Comment by kerthcet** [comment]
> Incase this is related, I wanted to mention it here. Im setting up a development environment for Kubernetes. The development guide recommends a linux with at least 8Gb memory. When I run 'make verify' the following 3 tests all fail with out of memory
> 
> hack/make-rules/../../hack/verify-typecheck-dockerless.sh
> hack/make-rules/../../hack/verify-typecheck-providerless.sh
> hack/make-rules/../../hack/verify-typecheck.sh
> 
> I tried increasing the VM memory to 16Gb and that got the first two to pass, but the last still fails.
> This is with go 1.17 and compiling master branch

have you tried

**Comment by saschagrunert** [comment]
kubernetes/kubernetes#104608 got merged, do we wanna wait for https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-typecheck if it looks greener in the near future?

**Comment by BenTheElder** [comment]
worth re-checking: we're on go1.18 now
