### ISSUE TITLE
Testgrid for pull-kubernetes-unit doesn't load

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/test-infra#23425]
This URL: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit
fails with the message: `Internal Error: Refresh, and file an issue if problem persists. (Your table may be too big; consider lower `days_of_results` or `enable_test_methods = false`).`

I've also tried https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit&exclude-non-failed-tests=&enable_test_methods=false&days_of_results=1
But same results, although I admit I'm not sure if the URL is correct.

**Comment by BenTheElder** [comment]
The table is too big. See also: https://github.com/kubernetes/test-infra/issues/22744

Testgrid is not terribly useful for presubmits (they're too noisy with broken code etc. and there's no way to correlate that sort of thing)

Now that kettle is fixed, you should use https://go.k8s.io/triage to look at presubmit flakiness etc. instead. (or https://prow.k8s.io for a quick look at recent pass rate for a weak proxy)

**Comment by BenTheElder** [comment]
https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=pull-kubernetes-unit

**Comment by MikeSpreitzer** [comment]
https://github.com/kubernetes/test-infra/#test-result-dashboards still points people at testgrid.

**Comment by BenTheElder** [comment]
TestGrid is great for historical results over time for periodic / post-submit testing. It is not particularly useful for presubmits.

**Comment by BenTheElder** [comment]
PRs welcome to adjust the table size for these dashboards, or to attempt to make the Kubernetes unit test junit results have a collapsed set of entries.

AIUI Testgrid will not be expanding memory allocation to handle these amusingly large tables.
