### ISSUE TITLE
Prow agents images for ppc64le throw "no such file or directory" error

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/test-infra#23449]
**What happened**:
There is a failure to bring up pod-utilty containers on the `ppc64le` architecture with the newly built images for `ppc64le`
ref: https://github.com/kubernetes/test-infra/pull/23293
Below is the error from Prow while the new ppc64le images are used for pod-utilities.

Image: `gcr.io/k8s-prow/initupload:v20210830-fcbb70627f-ppc64le`
```
Warning  Failed     65s   kubelet            Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/initupload": stat /initupload: no such file or directory: unknown

```

**What you expected to happen**:
The pod-utility containers should comeup as it comesup with amd image `gcr.io/k8s-prow/initupload:v20210830-fcbb70627f`

**How to reproduce it (as minimally and precisely as possible)**:
Try running a container using one of the image `gcr.io/k8s-prow/initupload:v20210830-fcbb70627f-ppc64le` and get into it to find the details of binary file `/initupload`.
**Image: gcr.io/k8s-prow/initupload:v20210830-fcbb70627f-ppc64le**
```
[root@rajalakshmi-workspace1 ~]# docker run --entrypoint "/bin/sh" -it gcr.io/k8s-prow/initupload:v20210830-fcbb70627f-ppc64le
/app/prow/cmd/initupload/app-ppc64le.binary.runfiles/io_k8s_test_infra # cd /
/ # file initupload
/bin/sh: file: not found
/ # apk add file
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/ppc64le/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/ppc64le/APKINDEX.tar.gz
(1/2) Installing libmagic (5.40-r1)
(2/2) Installing file (5.40-r1)
Executing busybox-1.33.1-r3.trigger
OK: 35 MiB in 33 packages
/ # file initupload
initupload: broken symbolic link to /app/prow/cmd/initupload/app.binary
/ # file /app/prow/cmd/initupload/app.binary
/app/prow/cmd/initupload/app.binary: cannot open `/app/prow/cmd/initupload/app.binary' (No such file or directory)
/ # ldd /initupload
/lib/ld-musl-powerpc64le.so.1: cannot load /initupload: No such file or directory
/ #
```
**But for image `gcr.io/k8s-prow/initupload:v20210830-fcbb70627f`**

```
[root@afferent1 ~]# docker run --entrypoint "/bin/sh" -it gcr.io/k8s-prow/initupload:v20210830-fcbb70627f
/app/prow/cmd/initupload/app.binary.runfiles/io_k8s_test_infra # cd /
/ # file --help
/bin/sh: file: not found
/ # apk add file
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libmagic (5.38-r0)
(2/2) Installing file (5.38-r0)
Executing busybox-1.31.1-r16.trigger
OK: 12 MiB in 17 packages
/ # file /initupload
/initupload: symbolic link to /app/prow/cmd/initupload/app.binary
/ # file /app/prow/cmd/initupload/app.binary
/app/prow/cmd/initupload/app.binary: symbolic link to /app/prow/cmd/initupload/app.binary.runfiles/io_k8s_test_infra/prow/cmd/initupload/app.binary_/app.binary
/ # file /app/prow/cmd/initupload/app.binary.runfiles/io_k8s_test_infra/prow/cmd/initupload/app.binary_/app.binary
/app/prow/cmd/initupload/app.binary.runfiles/io_k8s_test_infra/prow/cmd/initupload/app.binary_/app.binary: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=redacted, not stripped
/ #  ldd /initupload
/lib/ld-musl-x86_64.so.1: /initupload: Not a valid dynamic program
/ #
```

**Link to example occurrence**:
https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/periodic-golang-master-build-ppc64le/1432726261699973120
The above job used the fat manifest image from private repo `quay.io/powercloud/initupload`. We pulled the upstream image `gcr.io/k8s-prow/initupload:v20210830-fcbb70627f-ppc64le` and pushed it to our repo as we needed a fat manifest image for our prow infra.

**Anything else we need to know?**:
Would be good to also have a manifest image upstream, so that it can be used in prow infrastructure that use common config for multi-arch build clusters.

**Comment by mkumatag** [comment]
I see a similar behaviour for the arm as well!
```
/ # ls -l /initupload
lrwxrwxrwx    1 root     root            35 Jan  1  1970 /initupload -> /app/prow/cmd/initupload/app.binary
/ # ls -l /app/prow/cmd/initupload/app.binary
ls: /app/prow/cmd/initupload/app.binary: No such file or directory
/ # ls -l /app/prow/cmd/initupload/app-arm64.binary
lrwxrwxrwx    1 root     root           123 Jan  1  1970 /app/prow/cmd/initupload/app-arm64.binary -> /app/prow/cmd/initupload/app-arm64.binary.runfiles/io_k8s_test_infra/prow/cmd/initupload/app-arm64.binary_/app-arm64.binary
/ #
```

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag any update on this? Please see if we need to tag someone to get attention :)

**Comment by mkumatag** [comment]
> @mkumatag any update on this? Please see if we need to tag someone to get attention :)

no updates from me,! we need a bazel expert here! :) @BenTheElder @spiffxp @fejta any help is appreciated :)

**Comment by spiffxp** [comment]
I am unfortunately not a bazel expert

We'd be interested in help on how best to build prow's images without the use of bazel: https://github.com/kubernetes/test-infra/issues/23832

**Comment by mkumatag** [comment]
> I am unfortunately not a bazel expert
> 
> We'd be interested in help on how best to build prow's images without the use of bazel: https://github.com/kubernetes/test-infra/issues/23832

Awesome.. looking forward to see this happening,..

**Comment by BenTheElder** [comment]
images are built without bazel. unclear impact to this issue.

**Comment by BenTheElder** [comment]
The build has been completely replaced? Is this still an issue? Has anyone verified this?

**Comment by mkumatag** [comment]
> The build has been completely replaced? Is this still an issue? Has anyone verified this?

@Rajalakshmi-Girish can you check if this issue still exist?

**Comment by Rajalakshmi-Girish** [comment]
Yes, the agent images are working fine now.
https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/periodic-golang-master-build-ppc64le/1522393698980073472 is the successful job on our internal prow with ppc64le build cluster.
