### ISSUE TITLE
needs-rebase label not being applied

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#2346]
@fejta noted on kubernetes-dev (https://groups.google.com/d/msg/kubernetes-dev/YNHR4YZa9y4/-bLFgaSRCQAJ) that there was an issue with the needs-rebase label

I noticed that there were PRs with the opposite problem now (actually needs a rebase, but lacks the label):
- https://github.com/kubernetes/kubernetes/pull/42288
- https://github.com/kubernetes/kubernetes/pull/43551

**Comment by cblecker** [comment]
It seems as soon as I commented on these issues identifying they need a rebase, the bot got the event and commented about the rebase. Very strange.

**Comment by spxtr** [comment]
@apelisse made the bot react to issues when they change, which makes it much snappier but sometimes leads to it only noticing things like this when you add a comment or otherwise update the issue.

**Comment by cblecker** [comment]
I can see this possibly being a pain point though, as if:
- a PR is pending LGTM
- gets the LGTM
- immediately needs a rebase which forces that LGTM off

Wouldn't that really slow down the process, especially for first time contributors?

**Comment by apelisse** [comment]
@spxtr , I'd really like to see needs-rebase label being set/unset by prow instead.
is there an event that we receive when mergeability is computed?

**Comment by spxtr** [comment]
GitHub does not send an event. The only way to do it is to periodically poll all PRs, which is why it makes sense to leave it as a munger

**Comment by cblecker** [comment]
Perhaps then maybe a "cron" type logic that polls all PRs once every 24 hours for changes, plus the current logic of re-polling on action?

**Comment by apelisse** [comment]
Yeah, I'll probably just end-up implementing that anyway. Retry everything after 24h.

Would you be interested in working on that feature cblecker?

If you are, you can look at [mungegithub/github/github.go#L2138](/kubernetes/test-infra/blob/master/mungegithub/github/github.go#L2138), we have a `config.since` member that stores the last time we ran the loop. We could reset that to `time.Time{}` every day (and maybe also reset `extraIssues`/`HookHandler`).

**Comment by lukaszgryglicki** [comment]
I have an idea:
Status/Label `needs-rebase` can only change when base/master branch changes.
Why not check for merges for `master` branch (via WebHooks) and on every merge to `master` check all open PRs for `needs-rebase` label and update it if needed (add or remove)?

I can work on this.

**Comment by lukaszgryglicki** [comment]
Some initial work on this (test coverage + few changes needed to handle merged, mergeable, status fields from PullRequestEvent json payload).
No PR created yet, I'll continue work on that tomorrow.
Link: https://github.com/kubernetes/test-infra/compare/master...lukaszgryglicki:lukaszgryglicki-2346-needs-rebase-label

**Comment by spxtr** [comment]
> Why not check for merges for `master` branch (via WebHooks) and on every merge to `master` check all open PRs for `needs-rebase` label and update it if needed (add or remove)?

Two caveats I think:

1. We only have 5000 API tokens per hour. If we have to check every PR individually then with hundreds of open PRs we are going to have to be very careful about token usage. If the `mergeable` attribute is a part of the `GET /repos/:owner/:repo/pulls` list then we're okay, but otherwise this is pretty much a non-start.
1. `mergeable` takes a few moments to update after master changes. It is set to `null` in the meantime, and we'll have to retry.

**Comment by lukaszgryglicki** [comment]
I've already seen problem nr 2 in `mungegithub`'s IsMergeable.
I'll check nr 1 tomorrow (specially `GET /repos/:owner/:repo/pulls`) to see if `mergeable` is here.

My idea was to use `GitHub.FindIssues` with `"is:open is:pr label:lgtm` query.
And then I was planning to iterate such PRs and check if their `mergeable` and `needs-rebase` are synced.

Anyway - suggestions welcomed, I'm done for a day, so will investigate tomorrow.

**Comment by cblecker** [comment]
This leaves out PRs that aren't LGTM yet, which runs into the situation I described [here](https://github.com/kubernetes/test-infra/issues/2346#issuecomment-289833773).

**Comment by lukaszgryglicki** [comment]
I see, and without adding lgtm to FindIssues query there will be a lot of PRs to process.
So I'll check `GET /repos/:owner/:repo/pulls` if I have required info there.
Or eventually I will ahve to revert to `mungegithub` approach and play with checking frequency.

Not sure yet (one of my first tasks) how mony api points is consumed by single` FindIssues` call.
And then I have issues list returned, that I need to iterate.
Not sure if I will have mergeable flag then, or if I would have to call `GetPullRequest` on all of them to get deetails..... 
Another problem is that mergeable can be nil so we would have to wait....
Maybe we should react on PR merged to master with some delay, like background job or spawn mungegithug somehow after say 2 minutes....

All suggestions welcomed becaus eI'm not yet that familiar with `test-infra` so maybe just point me to the right direction and let me know if my proposed ideas are totally wrong.

**Comment by spxtr** [comment]
[FindIssues](https://developer.github.com/v3/search/#search-issues) hits the [search API](https://developer.github.com/v3/search/) so you're limited to 30 requests per minute, but it can return up to 1000 items at a time.

**Comment by spxtr** [comment]
> Maybe we should react on PR merged to master with some delay, like background job or spawn mungegithug somehow after say 2 minutes....

Prow runs plugins in separate goroutines, so it's fine to just wait for a minute before asking about mergeability.

**Comment by xiangpengzhao** [comment]
FYI, these PRs  need rebase, but lack the label:
https://github.com/kubernetes/kubernetes/pull/48237
https://github.com/kubernetes/kubernetes/pull/46913
https://github.com/kubernetes/kubernetes/pull/46598

**Comment by apelisse** [comment]
Yeah, I'll try to submit a dumb pr to fix that today

**Comment by xiangpengzhao** [comment]
Thanks @apelisse! PRs have conflicting files without notifying contributors is not so good an experience:)

**Comment by apelisse** [comment]
Should be fixed.
