### ISSUE TITLE
Post http://cherrypicker "connection refused"

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#23527]
Seeing repeating errors in prow log:

```
component: "hook"
error: "Post "http://cherrypicker": dial tcp 10.111.255.241:80: connect: connection refused"
event-GUID: "bc8c7ab0-117d-11ec-96b5-a44cde3aa62f"
event-type: "pull_request"
external-plugin: "cherrypicker"
file: "prow/hook/server.go:225"
func: "k8s.io/test-infra/prow/hook.(*Server).demuxExternal.func1"
level: "error"
msg: "Error dispatching event to external plugin."
```

**Comment by alvaroaleman** [comment]
What does the cherrypicker log say? I tried to find them in the cloud console with `jsonPayload.component: cherrypicker` but that didn't yield anything :(

**Comment by chaodaiG** [comment]
`kubectl get pods` returns no cherrypick pods,  let me see what's going on

**Comment by chaodaiG** [comment]
ah
```
$ kubectl get deployment cherrypicker -oyaml
account default/cherrypicker: serviceaccount "cherrypicker" not found'
```

**Comment by alvaroaleman** [comment]
That is weird, supposively cole fixed that with https://github.com/kubernetes/test-infra/pull/23517

**Comment by chaodaiG** [comment]
yeah, this is weird, the change from the fix was clearly applied by https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-deploy-prow/1435773000631717888, not sure why it's still on old config

**Comment by chaodaiG** [comment]
https://github.com/kubernetes/kubernetes/issues/76367#issuecomment-481689160

> This is unfortunate, but both fields are honored because of a name change around the 1.0 timeframe. the deprecated serviceAccount field can be removed if a new apiVersion of pods is introduced, but until then, clearing a service account on an existing object requires explicitly setting both serviceAccount: "" and serviceAccountName: ""

**Comment by chaodaiG** [comment]
seems easy enough, I'll create a PR :)

**Comment by chaodaiG** [comment]
The deployment was fixed, and cherrypicker still crashlooping:
```
{"component":"cherrypicker","error":"failed to get git authentication: error getting bot name: fetching bot name from GitHub: status code 401 not one of [200], body: {\"message\":\"Requires authentication\",\"documentation_url\":\"https://docs.github.com/rest/reference/users#get-the-authenticated-user\"}","file":"prow/external-plugins/cherrypicker/main.go:108","func":"main.main","level":"fatal","msg":"Error getting Git client.","severity":"fatal","time":"2021-09-09T17:34:30Z"}
```

**Comment by alvaroaleman** [comment]
It works: https://github.com/kubernetes-sigs/controller-runtime/pull/1640#issuecomment-916333626
/close
