### ISSUE TITLE
Remove non-alpha features from job ci-kubernetes-e2e-gci-gce-alpha-features

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/test-infra#23642]
**What should be cleaned up or changed**:
Jobs [`ci-kubernetes-e2e-gci-gce-alpha-features`](https://github.com/kubernetes/test-infra/blob/c22abc29319ca84054c05b326abf41a722c10d49/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L584) and [`pull-kubernetes-e2e-gce-alpha-features`](https://github.com/kubernetes/test-infra/blob/c22abc29319ca84054c05b326abf41a722c10d49/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L375) run for several features which are no longer in alpha status. Cleaning up the features requires:
1. Updating the job configurations to no longer focus non-alpha features.
2. (Optional, up to discussion) Adding new alpha features which should be tested by these jobs.
3. Ensuring the job is running properly. 

**Provide any links for context**:
Here are all the features tested by both jobs, together with its status and KEP link:

Feature | Status | KEP Link
----|----|----
ServiceAccountIssuerDiscovery | Stable | https://github.com/kubernetes/enhancements/issues/1393
StorageVersionAPI | **Alpha** | https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2330-migrating-api-objects-to-latest-storage-version 
Audit | Stable | https://github.com/kubernetes/enhancements/issues/22
PodPreset | **Alpha** | https://github.com/kubernetes/enhancements/issues/162
RunAsGroup | Stable | https://github.com/kubernetes/enhancements/issues/213
TTLAfterFinished | Stable | https://github.com/kubernetes/enhancements/issues/592
NodeLease | Stable | https://github.com/kubernetes/enhancements/issues/589
CSIStorageCapacity | Beta | https://github.com/kubernetes/enhancements/issues/1472
GenericEphemeralVolume | Stable | https://github.com/kubernetes/enhancements/issues/1698
DaemonSetUpdateSurge | Beta | https://github.com/kubernetes/enhancements/issues/1591
CrossNamespacePodAffinity | Beta | https://github.com/kubernetes/enhancements/issues/2249

**Comment by mmiranda96** [comment]
Additionally, we could try to onboard jobs listed on https://github.com/kubernetes/kubernetes/issues/104556

**Comment by mmiranda96** [comment]
/help
/good-first-issue

This might require some discussion, but the required changes are relatively easy.

**Comment by rayandas** [comment]
Hey @mmiranda96 I am totally new here. Can I take this up? Will look into what all is required and come up with questions.

**Comment by mmiranda96** [comment]
Sure @rayandas, feel free to take it and ask anything. Thanks!

**Comment by rayandas** [comment]
@mmiranda96 Thanks.

**Comment by rayandas** [comment]
Hi @mmiranda96 I took a good look on this issue today.
So as part of the cleanup, we have to remove non-alpha features which are in `test_args` from both `ci-kubernetes-e2e-gci-gce-alpha-features` and `pull-kubernetes-e2e-gce-alpha-features` jobs right?

For the below task, is there is there a list of features that should be tested by these jobs?
> Adding new alpha features which should be tested by these jobs.

**Comment by mmiranda96** [comment]
That's correct @rayandas. The main part of this task is removing the features from the test arg `ginkgo.focus`. 

As for the alpha features, it would make sense to do the following:
1. Retrieve all features that are in alpha status. For this, you can access [1.23 enhacement tracking](https://docs.google.com/spreadsheets/d/1P1J1QpayRmh2SNjs8T-wBCb6SgEOdWTRQ7MBol7yibk/edit#gid=0) (for context on this, I found this tracker on the homepage of [kubernetes/enhacements](https://github.com/kubernetes/enhancements)).
2. From those alpha features, filter the ones that make sense to be tested in this job. I'm not entirely sure what's the best approach here. I'm adding `sig-release`, since these jobs are owned by the release team.

/sig release

For now, I'd recommend only removing non-alpha features. Once we get an input from the release team, we can decide which new alpha features to include.

A helpful note: both jobs run the same set of tests. However, `ci-kubernetes-e2e-gci-gce-alpha-features` runs as a periodic job, while `pull-kubernetes-e2e-gce-alpha-features` runs as a presubmit job.

**Comment by rayandas** [comment]
Sure @mmiranda96. I will raise a PR for now after removing non-alpha features.

**Comment by mmiranda96** [comment]
Reopening since this is only fixed partially.
/reopen

**Comment by jnbhavya** [comment]
@mmiranda96 can i take this issue as i am new here i would love to take this issue

**Comment by mmiranda96** [comment]
Hi @jnbhavya. Thanks for your interest. Steps 1 and 3 have already been completed by https://github.com/kubernetes/test-infra/pull/23845. There is still some uncertainty on which jobs should be included for step 2. 

I'll bring up this topic on this week's Node CI meeting and update with the proper information. Until then, I'll suggest you wait.

**Comment by jnbhavya** [comment]
@mmiranda96 thanks

**Comment by mmiranda96** [comment]
That's right @jnbhavya. I would recommend searching under [test/e2e_node](https://github.com/kubernetes/kubernetes/tree/master/test/e2e_node) which tags should be included.

**Comment by jainbhavya65** [comment]
Sure @mmiranda96. I will raise a PR for now after add alpha features in pull-kubernetes-e2e-gce-alpha-features job.
Please look into it if any changes required let me know thanks.

**Comment by jainbhavya65** [comment]
@mmiranda96 Hey can you please look into it?

**Comment by mmiranda96** [comment]
Apologies, I missed it last week. I've replied in the PR, please take a look.

**Comment by jainbhavya65** [comment]
@mmiranda96 can you please give lgtm again

**Comment by jainbhavya65** [comment]
@mmiranda96 is that PR merge after testing

**Comment by mmiranda96** [comment]
@jainbhavya65 I've added the suggested approver, as I'm only a member and cannot grant approve to PRs. Also, please let's keep the conversation on the PR.
