### ISSUE TITLE
Time zone in testgrid is ambiguous

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#2364]
It's not clear to me that testgrid uses Pacific time. Ideally, the time zone should be configurable.

**Comment by krzyzacy** [comment]
or use local time?

**Comment by kargakis** [comment]
Yes

**Comment by spiffxp** [comment]
is this still locked to pacific time? I'm in pacific so I can't tell...

**Comment by michelle192837** [comment]
I believe it is, yes.

**Comment by spiffxp** [comment]
Using my current east coast superpowers I can confirm that yes, it's still locked to pacific time

**Comment by spiffxp** [comment]
/remove-lifecycle stale
@fejta @michelle192837 is this something a contributor outside of google can accomplish? otherwise I'm not sure the `help wanted` label belongs here

**Comment by michelle192837** [comment]
Not at the moment, unless someone wants to implement it as a Chrome extension that changes all the time-related column headers (which I'm going to guess, is a no).

**Comment by michelle192837** [comment]
I can update the column header tooltip to display what the timezone is, if that's a good bandaid. (It will always be pacific until configurable timezones are a thing, but at least it'll be displayed).

**Comment by michelle192837** [comment]
Okay, I'm going to look into 1) updating that tooltip to say PST/PDT (as noted above), and per a suggestion from @neolit123, 2) look into a frontend option to display times according to the user's brower's timezone. (Probably as a toggle, at least to start).

**Comment by neolit123** [comment]
i think a toggle should be the ideal option here - e.g. "show local times"
and the non-local times should be UTC, which can be used in case folks need to talk about a certain tests across different TZs.

**Comment by michelle192837** [comment]
Bleh, it's been a while. Some stuff (like a cold and some other work) hit, but I want to get a look at this by Friday if it's an easy-enough change.

**Comment by jdunphy** [comment]
Even simply listing the timezone next to the stamps would be helpful for context.

**Comment by krzyzacy** [comment]
/unassign
cc @tony-yang who might be interested

**Comment by fejta** [comment]
GST

**Comment by tony-yang** [comment]
At the moment, I think the underlying time format should still be stored in PST due to historical reason. I will be looking into adding the timezone label to the header/tooltip and also displaying local time based on location, as per @michelle192837 suggested above.

**Comment by tony-yang** [comment]
The timezone label is now live for Testgrid. Time displayed on the UI should now have the label PDT. Coming up next is the ability to choose the timezone (between local time and Pacific Time) using a toggle button on the UI as well as a setting in the config file. The default timezone label will change to local time, with the ability to opt-out to Pacific Time.

**Comment by neolit123** [comment]
@tony-yang 
thanks for working on this.

i think i see a new problem related to the commit SHA:
![commit-sha](https://user-images.githubusercontent.com/331852/55154323-3127a180-515d-11e9-9758-2dcc9077a73d.png)

https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-master

**Comment by michelle192837** [comment]
That tooltip is hardcoded and I think needs to be swapped out (for Build ID?)

**Comment by tony-yang** [comment]
@neolit123 Thanks for bringing that issue up. We have also noticed that problem on many of our views. As Michelle commented, we are still deciding on how to proceed with the overflow content as well as the incorrect tooltip. We are definitely tracking this issue and will keep everyone posted. Cheers.

**Comment by tony-yang** [comment]
The timezone toggle switch (located beside the `Graph` button) and an option in config named `display_local_time` are now live. By default local time is turned on. Users can either switch back to PST during the session by clicking the toggle switch, or make a permanent switch using the config by setting the `display_local_time` attribute to `true` or `false`.

**Comment by matthyx** [comment]
@tony-yang so this issue can be closed?

**Comment by tony-yang** [comment]
@matthyx Yes, this issue can be closed. Unfortunately I don't have the permission to do so. I'll check with Michelle, or anyone with the right permission, please feel free to close this issue. Thanks.

**Comment by michelle192837** [comment]
/close

Thanks Tony! :D
