### ISSUE TITLE
[approvers] Don't Notify Approver Until After LGTM

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2366]
Approvers is intended to be a lightweight mechanism, but mentioning approvers immediately, they are subscribed to the issue and get all the review and discussion comments.

Potentially, wait to cc the approver until lgtm is applied.

**Comment by apelisse** [comment]
Did you receive that many complaints? if the scope of approval and lgtm is so distinct, then you should be able to get one and then the other. Can we unsubscribe the approver when he approves? :D

**Comment by ixdy** [comment]
I would much appreciate it if I wasn't cc'd as an approver until LGTM.

**Comment by spxtr** [comment]
I don't like the idea, because it means PRs will take strictly longer to merge.

**Comment by ixdy** [comment]
is that true? I generally don't approve PRs until they've been LG'd. I'm not sure what others do, though.

**Comment by grodrigues3** [comment]
> Can we unsubscribe the approver when he approves?

This doesn't solve the problem of the approver receiving all of the comments/discussion up until approval.  I think you're imaging a situation where an approvers right away and is unbothered.  Seems annoying to get a whole thread about something you're not very interested in.

> I don't like the idea, because it means PRs will take strictly longer to merge.

I'm inclined to agree with @ixdy , but we have no data to back this up one way or another (that's another problem).  I'd like to encourage authors/reviewers to reach out to any of the owners if the cc'd owner is unresponsive.

**Comment by rmmh** [comment]
Gubernator is now properly parsing the approval blocks, so the dashboard will properly show PRs that need your approval.

However, the bot *also* assigns the approvers, meaning they receive all the notification spam. What if we just removed the assignment portion?

**Comment by ixdy** [comment]
does the bot assign approvers? or just cc them?

**Comment by grodrigues3** [comment]
I think it just cc's them. @apelisse made some changes recently though.

**Comment by grodrigues3** [comment]
@kubernetes/sig-contributor-experience-feature-requests @Sevii @lukaszgryglicki 

This is a pretty simple one which could really improve our contributor's experience.

**Comment by grodrigues3** [comment]
@crimsonfaith91 

You could also try this one out

**Comment by crimsonfaith91** [comment]
Noted. I will have a look at it asap.

**Comment by bgrant0607** [comment]
@spxtr @apelisse Yes, I complained shortly after the approval mechanism was turned on, and so did @thockin.

A direct result of the current approach is that I blackhole all github notifications, which I'm sure makes it take longer for PRs to merge than if I could actually pay attention to github notifications.

In addition to waiting until LGTM, we want the bot to not notify the approver at all, but post the approver suggestion to the author and/or reviewer. Something like (thanks to Tim for text): "This needs approval, we recommend thockin - assign it to him with a comment when you're ready"

**Comment by crimsonfaith91** [comment]
PR can be found here: https://github.com/kubernetes/test-infra/pull/2538

**Comment by spiffxp** [comment]
Closing this issue as done, see any recent PR in kubernetes/kubernetes for examples of what @k8s-merge-robot now says
