### ISSUE TITLE
`push-prow` is flaky

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#23671]
The [sig-testing push-prow job](https://testgrid.k8s.io/sig-testing-prow#push-prow) is flaky: it will occasionally time out pushing its images ([log](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-push-prow/1440009914314395648)), but then succeed again a little later. It seems to be happening regularly about once a day.

Its alert configuration is tight ([any failure sends an alert](https://testgrid.k8s.io/q/config/sig-testing-prow/push-prow)), since its an important job for our infrastructure. Maybe just allowing this flakiness and reducing the alert sensitivity is correct?

**Comment by cjwagner** [comment]
This has been effectively mitigated by running the job on a dedicated node: https://github.com/kubernetes/test-infra/pull/23549
