### ISSUE TITLE
do-not-merge shouldn't apply to release-note label issues

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#2368]
Currently, if a PR is /lgtm'd without a proper release note label, mungegithub will apply `do-not-merge` to the PR so the correct release note label can be applied before merging. However, `do-not-merge` cannot be removed by contributors without write access, even if the release note label is fixed. As `do-not-merge` can mean other things, it can't be safely automatically removed.

I suggest:
- `do-not-merge` should not be applied by mungegithub
- `release-note-label-needed` should make a PR ineligible for merge from submit-queue's prospective. This way, not having the right release label would have the same effect.

**Comment by ixdy** [comment]
basically #2196, though your summary is worded better

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
So this changes were requested (here: https://github.com/kubernetes/test-infra/pull/2456#issuecomment-293693766)
- make sure that munger will not merge if there is `release-note-needed` Label
- release-note munger will not apply `do-not-merge` (unconditionally? just remove that functionality)? 

wip.

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by cblecker** [comment]
Fixed by #4196
/close

**Comment by cblecker** [comment]
p.s. thanks @stevekuznetsov !
