### ISSUE TITLE
Assign plugin should post a helpful comment when target is not an org member

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2369]
https://github.com/kubernetes/kubernetes/issues/42569#issuecomment-290505425

```
{
  level: "error"    
  repo: "kubernetes"    
  org: "kubernetes"    
  plugin: "assign"    
  pr: 42569    
  error: "cannot assign shiywang"    
  author: "enisoc"    
  msg: "Error handling IssueCommentEvent."    
  url: "https://github.com/kubernetes/kubernetes/issues/42569#issuecomment-290505425"    
 }
```
/assign @fejta

**Comment by krzyzacy** [comment]
because shiywang is not an org member? like I cannot manually assign this issue to him

**Comment by spxtr** [comment]
It should comment back saying "such-and-such is not an org member so I can't assign"

**Comment by lukaszgryglicki** [comment]
@grodrigues3 I'll work on this. May take a little time because this will be my first work on kubernetes/test-infra.

**Comment by krzyzacy** [comment]
oh, already done.

/close

**Comment by lukaszgryglicki** [comment]
Ok will pick up other then.
