### ISSUE TITLE
TestGrid updates stopped

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#23720]
From digging around on random dashboards, looks like TestGrid updates on testgrid.k8s.io stopped around midnight-ish on 09-22.

This doesn't seem to correspond with a TestGrid release (latest push was 09-10 image, https://github.com/GoogleCloudPlatform/testgrid/pull/685). Logs seem to indicate that the updater is up and scheduling updates, but isn't getting around to writing any state.

Investigating.

/area testgrid

**Comment by michelle192837** [comment]
/sig testing

We have a lot of CrashLoopBackOff errors for the updater specifically, but I think other components are running just fine.

**Comment by michelle192837** [comment]
With resource adjustments for deployments (thanks @fejta !), looks like the updater's caught up and groups are updated (from a few random checks). Think we can call this fixed now.

**Comment by stbenjam** [comment]
TY @michelle192837 and @fejta !!
