### ISSUE TITLE
Keep kubekins-e2e experimental up-to-date with kubetest2

### ISSUE THREAD

**Issue by amwat** [kubernetes/test-infra#23727]
**What would you like to be added**:
A mechanism to ensure jobs using `kubekins-e2e-...-experimental` have the latest kubetest2 binaries.

**Why is this needed**:
Currently kubetest2 binaries are baked into the experimental kubekins image through variants: https://github.com/kubernetes/test-infra/blob/3c3d64f398a5e4f324200d25183c98a4bfa842ac/images/kubekins-e2e/variants.yaml#L8
https://github.com/kubernetes/test-infra/blob/3c3d64f398a5e4f324200d25183c98a4bfa842ac/images/kubekins-e2e/Dockerfile#L101-L107

But the image is only updated whenever the image push postsubmit on test-infra runs:
https://github.com/kubernetes/test-infra/blob/3c3d64f398a5e4f324200d25183c98a4bfa842ac/config/jobs/image-pushing/k8s-staging-test-infra.yaml#L198

Dependencies like `kubetest` are ensured to be latest by way of being **in-tree**
https://github.com/kubernetes/test-infra/blob/3c3d64f398a5e4f324200d25183c98a4bfa842ac/config/jobs/image-pushing/k8s-staging-test-infra.yaml#L206

Out-of-tree Boskos didn't need something similar since it's mostly consumed as a client library.

**Note:** this is especially applicable to the experimental image where we want to have latest binaries, other variants can use stable tags.

**Options:**
1) Have a periodic image-pushing job (which could additionally perform smart checks to push a new image only if necessary)
2) Have a script baked into kubekins-e2e which fetches latest binaries at runtime
3) Inline bash similar to how we ensure latest kind binaries https://github.com/kubernetes/test-infra/blob/689941423e01abb85b7ca6b9e317e3d035c60098/config/jobs/kubernetes/sig-testing/kubernetes-kind-presubmits.yaml#L24
4) Manually update `variants.yaml` to newer commits as and when needed

cc @BenTheElder @spiffxp @dims 

ref: https://github.com/kubernetes/test-infra/pull/23707#issuecomment-926157298
xref: https://github.com/kubernetes/enhancements/tree/master/keps/sig-testing/2464-kubetest2-ci-migration#graduation-criteria

**Comment by dims** [comment]
@amwat i like 3 as it is explicit and not hidden. also because we have had success with this pattern with `kind` already.

**Comment by spiffxp** [comment]
I also like 3 for an "ensure latest" pattern.  Option 4 could be automated if we had something akin to generic-autobumper but for commits instead of image tags.

**Comment by spiffxp** [comment]
That said I'll approve https://github.com/kubernetes/test-infra/pull/23860 which is option 4 for now since it unblocks
