### ISSUE TITLE
test jobs reporting overall success and individual test failures

### ISSUE THREAD

**Issue by liggitt** [kubernetes/test-infra#2372]
Seeing output like this, which looks suspicious:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/43835/pull-kubernetes-e2e-gce-gci/23926/

Is it correct to get a test failure and have overall success somehow?

**Comment by fejta** [comment]
What do the logs say? I bet this is about flakes

**Comment by liggitt** [comment]
```
I0330 17:01:37.365] Summarizing 1 Failure:
I0330 17:01:37.366] 
I0330 17:01:37.366] [Fail] [k8s.io] Kubectl client [k8s.io] Kubectl describe [It] should check if kubectl describe prints relevant information for rc and pods [Conformance] 
I0330 17:01:37.366] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1644
I0330 17:01:37.366] 
I0330 17:01:37.366] Ran 288 of 600 Specs in 1354.369 seconds
I0330 17:01:37.366] SUCCESS! -- 288 Passed | 0 Failed | 0 Pending | 312 Skipped 
```

**Comment by liggitt** [comment]
does ginkgo do auto-retry?

**Comment by fejta** [comment]
Yes. If you look at the vars one of then is to retry failing tests to mitigate against flakes

**Comment by liggitt** [comment]
ah, ok. still disconcerting (wish the output was clearer that the test got retried and passed), but glad to know failures still fail the job
