### ISSUE TITLE
Identifying build system for replacing bazel in test-infra

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#23796]
**What would you like to be added**:

Identifying another build system for replacing bazel in test-infra.

**Why is this needed**:

Test-infra repo is a Go centric repo, as of today 77.8% of the source code in this repo is Go, followed by 7.1% of python. Bazel as current build tool, however isn't working really great with Golang, and can sometimes delay the development (for example https://github.com/kubernetes/test-infra/pull/23693). This was due to the fact:

- rules_go and other rules don't follow/update go.mod
- Sometimes don't use the same libraries as in go.mod

For Go build and test we can use native Go toolchains, which should be sufficient for our use case.

**What will be missed (Problems to be solved)**

- Bazel caching in CI, namely RBE for speeding up incremental tests in CI
- Tests results in junit format
- Rules for python and typescript
- Prow images building rules
- Cluster ops rules

**Comment by chaodaiG** [comment]
@fejta @spiffxp @alvaroaleman @stevekuznetsov @cjwagner for awareness

**Comment by alvaroaleman** [comment]
Love the idea of getting rid of bazel :) Is the idea here to just replace bazels go build and test or is it to replace bazel entirely?

**Comment by spiffxp** [comment]
FWIW, some of the @kubernetes/release-engineering folks have been experimenting with `mage` as an alternative to `make`: https://magefile.org/

**Comment by chaodaiG** [comment]
> Is the idea here to just replace bazels go build and test or is it to replace bazel entirely?

I'm inclined to replace entirely to avoid maintaining two systems

**Comment by alvaroaleman** [comment]
> I'm inclined to replace entirely to avoid maintaining two systems

Ah ok, then this would probably mean setting something up in parallel for now and gradually migrating components over?

We have a bunch of binaries that are just go, those should be relatively easy. Then there is stuff like Deck, which uses typescript and go, that will be a bit more difficult. I don't know the python components, so not sure how difficult or not that is going to be.

> Bazel caching in CI, namely RBE for speeding up incremental tests in CI

There was at some point a proposal for a cache that would be using object storage and be able to be used for the gocache. This never actually happened though. Do you know what k/k ended up doing, was the standard `go build/test` quick enough to not bother with the problem at all?

> Tests results in junit format

Other projects I've worked on use [gotestsum](https://github.com/gotestyourself/gotestsum) for this

Realistically I would assume there will not be a build system that replaces bazel but rather a collection of Makefiles and/or scripts that glue language- or task-specific tooling together.

> FWIW, some of the @kubernetes/release-engineering folks have been experimenting with mage as an alternative to mak

What is the advantage over `Make`? I like that `make` is something pretty much everyone has on their computer.

**Comment by chaodaiG** [comment]
> Do you know what k/k ended up doing, was the standard go build/test quick enough to not bother with the problem at all?

My local `go test` is normally pretty fast, so I'm not so worried about Go toolchains. + @BenTheElder here for a lazy answer for k/k solution

**Comment by BenTheElder** [comment]
> My local go test is normally pretty fast, so I'm not so worried about Go toolchains. + @BenTheElder here for a lazy answer for k/k solution

We've not wound up pushing forward with any go cache work for k/k because the slowest thing we do with go by far is run unit tests, and go (and bazel!) will not cache with the race detector enabled, and we decided that we prefer to have the race detector as it catches real bugs ... 

For other things the speed difference is negligible enough due to thinks like the overhead of downloading WORKSPACE.

Mostly it is fast enough.

In kind and kubetest2 we've prototyped some make + shell stuff to automatically manage using the correct go version similar to .bazel-version and rules_go toolchains, and a set some go flags to make things reproducible. It's not a lot of code. I think I commented it pretty well: https://github.com/kubernetes-sigs/kind/blob/8efc3707674fc5f2bcb85bc623ddc5639c992eea/Makefile

NOTE: I think in the latest go ldflags `-buildid=` may no longer be necessary and you just need `-trimpath` + disable CGO + fixed go version.

**Comment by chaodaiG** [comment]
Thank you @BenTheElder !

Took a look at both [kind](https://github.com/kubernetes-sigs/kind/blob/8efc3707674fc5f2bcb85bc623ddc5639c992eea/Makefile) and  [k/k](https://github.com/kubernetes/kubernetes/blob/bceefb7a86cfcfe040deabdce6f0955757deb80f/Makefile), my feeling is that k/k is more complex than what we need, and the build rules for kind seem fit pretty well with our use case for Go.

**Comment by chaodaiG** [comment]
Since #25373  from 6 days ago, prow images were built using ko instead bazel. No major regression yet, a few minor issues were discovered:
- `user-agent` and Version not set, fixed in https://github.com/kubernetes/test-infra/pull/25401
- Downstream tool depends on absolute paths of static files in deck changed to be under `/var/run/ko`

Breaking changes were mentioned in https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md.

Right now bazel test is still required presubmit test, just in case that there is anything major coming up. Planning to remove it from presubmit test next Monday if nothing major is reported by then

**Comment by chaodaiG** [comment]
Stop gating with bazel test https://github.com/kubernetes/test-infra/pull/25519

**Comment by chaodaiG** [comment]
Now that it's landed
/close
