### ISSUE TITLE
release-note label not being applied correctly

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#2379]
I created two PRs recently (https://github.com/kubernetes/kubernetes/pull/43927 and https://github.com/kubernetes/kubernetes/pull/43928) with blank `release-note` sections.

I expected this to add the `release-note` label to the PRs, as I think was the behavior in the past, but the munger instead tagged these as `release-note-label-needed`.

If this is now the expected behavior, we need to update the PR template.
@kubernetes/sig-contributor-experience-bugs 

(It's also possible the bot got confused because these are non-cherrypick PRs against release branches?)

**Comment by grodrigues3** [comment]
Should it be `release-note-none`

> `regexp.MustCompile(`(?s)(?:Release note\*\*:\s*(?:\s*)?` + "```(?:release-note)?|```release-note)`

I think @rmmh updated the regexp for matching this most recently.  Any ideas?

**Comment by ixdy** [comment]
It definitely should not be `release-note-none` - I didn't put NONE in the release note field.

**Comment by grodrigues3** [comment]
The current encoding does not match the template

https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/PULL_REQUEST_TEMPLATE.md

And the current implementation says that an empty release note section in the template should result in `release note needed `label.

https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/release-note-label.go#L187
