### ISSUE TITLE
Build and test Typescript without bazel

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#23829]
**What would you like to be added**:

Build and test Typescript without bazel, the related bazel rules are:

- nodejs_binary
- nodejs_test
- ts_library
- jasmine_node_test
- rollup_bundle
- genrule

Things to be considered:

- This will need to co-exist with current bazel rules for a short while, delete Typescript build/test targets from bazel once this confirmed working
- Test driven by make rule and bash scripts
- Ensure hermetic testing, including fixed tools version, like node, yarn, jasmine ([source of tools](https://github.com/bazelbuild/rules_nodejs/blob/3.1.0/package.json))
- Artifacts generated for serving prow UI
- Test results are in junit results format

**Why is this needed**:

This is part of #23796 

**Recommended testing approach**:
- Make test invokable by `make test`
- Create a PullRequest with change, manually run job by commenting `/test pull-test-infra-test-beta`
- [Optional]: if there is any tool that needs to exist in test image, update image at https://github.com/kubernetes/test-infra/blob/6e0d21ee50d690c8f78239257f588021d2ed57b5/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L145

/sig testing
/help

**Comment by chaodaiG** [comment]
Did some quick search on github, this repo testing using yarn and jasmine might help: https://github.com/radanalyticsio/equoid-ui#client-tests

**Comment by BenTheElder** [comment]
I started on this, there is an official docker image we can use.

One issue is that our node stuff is generally pretty out of date, e.g. we can get tslint working but it turns out it's actually deprecated ... 🙃 

I am starting with tslint, when we get the mechanics in place for that we should have a path to expand it to the other rules, and it aligns with the progress migrating the other linters https://github.com/kubernetes/test-infra/issues/23897

**Comment by BenTheElder** [comment]
Also today we rely on the default version of npm, yarn etc. in bazel so it took a bit to track those down, and we don't specify them anywhere. We will probably need an analogue of .go-version but for the node docker image.

**Comment by BenTheElder** [comment]
We wound up just putting a fixed node image version in a run-in-node-container.sh script in https://github.com/kubernetes/test-infra/pull/24491, which seems to be fine.

**Comment by chaodaiG** [comment]
This was done, bazel not fully deprecated here as it's still building prow images as part of it. Will close this once prow images are not built from bazel

**Comment by chaodaiG** [comment]
After #25373 prow images are built without bazel
/close
