### ISSUE TITLE
Remove custom projects from SIG Node test manifests

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#23822]
**What should be cleaned up or changed**:

SIG Infra has identified the following GCP projects that they'd like to retire:

- [ ] k8s-jkns-pr-node-e2e: https://cs.k8s.io/?q=k8s-jkns-pr-node-e2e&i=nope&files=&excludeFiles=&repos=
- [ ] cri-containerd-node-e2e: https://cs.k8s.io/?q=cri-containerd-node-e2e&i=nope&files=&excludeFiles=&repos=
- [ ] K8s-cri-containerd: house of bucket gs://cri-containerd-testing : https://cs.k8s.io/?q=cri-containerd-staging&i=nope&files=&excludeFiles=&repos=

SIG Node should remove these explicit projects from jobs wherever possible. A project should be automatically generated/selected. (see e.g. https://github.com/kubernetes/test-infra/pull/23777/files#diff-9495ba672589316a9265fd090ecb9c3c74fd414a11386acafda27df4bd409409)

**Provide any links for context**:

See also https://github.com/kubernetes/k8s.io/issues/1469

/sig node k8s-infra

**Comment by ameukam** [comment]
We should firstly identity those master-{blocking,informing} and migrate them before the rest.

**Comment by spiffxp** [comment]
Related: https://github.com/kubernetes/test-infra/issues/23291

Don't ask for a node-e2e project, the default gce-project type should be enough

**Comment by ameukam** [comment]
> @ameukam I took a good look on this issue today, also rest of the issues and PRs that were mentioned. So we need to remove the listed projects from jobs, is that correct?

We also want to migrate the release-blocking prowjobs to the community-owned build clusters by adding

`cluster: k8s-infra-prow-build`
 
to the spec of the prowjob.

>  And I should raise different PRs for each project cleanup right? Apologies if I miss something or wrong somewhere. I am still new in these areas.

I would advise doing a few jobs per PR so I can easily monitor the jobs after the flag is dropped and also to start with the periodics.

@ehashman Ouf of curiosity, why do we need a specific bucket (`cri-containerd-staging`) for the E2E containerd tests ?

**Comment by rayandas** [comment]
@ameukam I've raised a PR after identifying master-{blocking,informing} jobs to the community-owned build cluster.
Let me know if it looks good then I will remove the WIP.

**Comment by ameukam** [comment]
> @ameukam I've raised a PR after identifying master-{blocking,informing} jobs to the community-owned build cluster. Let me know if it looks good then I will remove the WIP.

@rayandas `k8s-infra-prow-build-trusted` is also part of the community-owned infrastructure. There is no need to make changes for the jobs using this cluster.

**Comment by rayandas** [comment]
Hello @ameukam Now I got the requirements here. I just updated the PR for `k8s-jkns-pr-node-e2e` and will start working on migrating `cri-containerd-node-e2e` (https://cs.k8s.io/?q=--gcp-project%3Dcri-containerd-node-e2e&i=nope&files=&excludeFiles=&repos=) and raise a different PR (I will also include the community own infrastructure).

Though I need some clarification on this part, like how should I approach and that sort.

> K8s-cri-containerd: house of bucket gs://cri-containerd-testing : https://cs.k8s.io/?q=cri-containerd-staging&i=nope&files=&excludeFiles=&repos=

**Comment by rayandas** [comment]
It's partially done.
/reopen

**Comment by rayandas** [comment]
@ehashman Please reopen this issue. It's partially done. There will be two more PRs for this issue.
cc: @SergeyKanzhelev

**Comment by ehashman** [comment]
/milestone v1.24

didn't quite finish this and now we're deep in freeze

**Comment by rayandas** [comment]
> K8s-cri-containerd: house of bucket gs://cri-containerd-testing : https://cs.k8s.io/?q=cri-containerd-staging&i=nope&files=&excludeFiles=&repos=

The last part is left now.

/cc: @ameukam

**Comment by ehashman** [comment]
Quick inventory:

- https://github.com/kubernetes/test-infra/blob/ce6d91ae98fdbf730f3f1808466d7d81003f3616/config/jobs/kubernetes/sig-node/containerd.yaml#L902
- Four presubmits: https://github.com/kubernetes/test-infra/blob/ce6d91ae98fdbf730f3f1808466d7d81003f3616/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml
- Unclear what needs to be done for "K8s-cri-containerd: house of bucket gs://cri-containerd-testing"

**Comment by rayandas** [comment]
I will raise a PR to remove which are left.

**Comment by rayandas** [comment]
cri-containerd-node-e2e: https://github.com/kubernetes/test-infra/pull/24979
k8s-jkns-pr-node-e2e: https://github.com/kubernetes/test-infra/pull/24980

**Comment by rayandas** [comment]
@ameukam Could you please shed some light on the third task here whenever you get time?

**Comment by ameukam** [comment]
> @ameukam Could you please shed some light on the third task here whenever you get time?

@rayandas  Looking at https://cs.k8s.io/?q=gs%3A%2F%2Fcri-containerd-testing&i=nope&files=&excludeFiles=&repos=, I think jobs stopped use `k8s-cri-containerd` project. we can skip this task for the moment.

**Comment by ehashman** [comment]
@ameukam can this be closed? I think everything here we need to do is done?

**Comment by ameukam** [comment]
Some jobs still run on Google infrastructure : [https://cs.k8s.io/?q=gcp-project%3Dcri-c8d-pr-node-e2e&i=nope&files=&excludeFiles=&repos=](https://cs.k8s.io/?q=gcp-project%3Dcri-c8d-pr-node-e2e&i=nope&files=&excludeFiles=&repos=) but there are related to Containerd. We can close it.
