### ISSUE TITLE
prow: support/endorse method of duplicating specs

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/test-infra#2383]
When a prow job uses a custom spec, this particular bit of configuration can get very lengthy. When those jobs get duplicated to run variants of the same test, it involves a lot of [copy/pasting](https://github.com/kubernetes/test-infra/pull/2352/files) of these large specs that can be [error-prone](https://github.com/kubernetes/test-infra/pull/2246).

Duplicate specs could be avoided by using yaml's built-in anchor/reference features, but they aren't currently used in prow's config, and I've gotten pushback from starting to use them. Another possible solution would be to support a `spec-ref` field mutually exclusive with `spec` that could refer to another job whose `spec` should be duplicated.

I'm not looking for complicated inheritance schemes and overriding fields to be supported, but being able to refer to an existing spec instead of manually duplicating it would make `config.yaml` more succinct and easier to maintain jobs with many variants.

**Comment by spxtr** [comment]
Yep, this is something that @fejta and I talked about recently. We want to avoid the case where these have as much complexity as our JJB job configs did. I don't think we've settled on a final design yet.

**Comment by spxtr** [comment]
I endorse [PodPresets](https://kubernetes.io/docs/tasks/inject-data-application/podpreset/) whenever they go beta.
