### ISSUE TITLE
Building prow images without bazel

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#23832]
**What would you like to be added**:

Building prow images without bazel, the related bazel rules are:

- prow-image
- container-image
- go-image

Things to be considered:

- This will need to co-exist with current bazel rules for a short while, delete Prow images test targets from bazel once this confirmed working
- Building prow containers from [rules-docker](https://github.com/bazelbuild/rules_docker), under the hood using distroless language runtime
- Deck is a special case, images built with a set of rules including rollup_bundle, will likely benefit from #23829 
- `/images` don’t use bazel

**Why is this needed**:

This is part of #23796 

**Recommended testing approach**:
- Make test invokable by `make test`
- Create a PullRequest with change, manually run job by commenting `/test pull-test-infra-test-beta`
- [Optional]: if there is any tool that needs to exist in test image, update image at https://github.com/kubernetes/test-infra/blob/6e0d21ee50d690c8f78239257f588021d2ed57b5/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L145

/sig testing
/help

**Comment by chaodaiG** [comment]
Most of prow binaries are purely written in Go, the only known exception is `Deck`, where it has quite a few typescripts at [prow/cmd/deck/static](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/deck/static), so this work is probably better to be done after #23829 is landed.

**Comment by chaodaiG** [comment]
rules_docker achieves images building and pushing by a mixture of bazel rules and Go packages, for example https://github.com/bazelbuild/rules_docker/blob/master/container/go/cmd/join_layers/join_layers.go for creating image tarballs. It's not going to be an easy task using the same stack that rules_docker uses.

Alternatively, this can be achieved by Dockerfile + Makefile. Production prow images can be published with Google Cloud Build, and local developers will be given the option of building/pushing using local docker, which will also be used by prow integration tests which require pushing images to local registry(GCB doesn't support).

For Google Cloud Build, technically could reuse https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing, however it only supports a single image per job, which means lots of prow jobs just for pushing prow images. Might prefer creating a single cloudbuild.yaml for pushing all prow images.

**Comment by chaodaiG** [comment]
I'll start playing with images that are pure Golang

**Comment by chaodaiG** [comment]
@deepsm007 , in https://github.com/kubernetes/test-infra/pull/23414, multi-arch images were built and tagged separately for each arch. What's the advantage of this approach vs. single image supporting multi-arch? like passing `--platform=linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x` flag?

**Comment by deepsm007** [comment]
> @deepsm007 , in #23414, multi-arch images were built and tagged separately for each arch. What's the advantage of this approach vs. single image supporting multi-arch? like passing `--platform=linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x` flag?

When trying to build it locally we were facing a lot of challenges for s390x, so went ahead and started for ppc64le since those images were required for ibm cloud work. And after a lot of issues we were finally able to build it on local. No particular advantage here, its the urgency.

**Comment by chaodaiG** [comment]
Thank you! I'll give the single image approach a shot

**Comment by chaodaiG** [comment]
Attempted building pod utilities images using docker buildx with `platform=` flag, this is probably the easiest way of building multi-arch images. However I have also ran into trouble with s390x, probably the same reason as @deepsm007 had mentioned above. Document what I have seen so far:
- [Official docker image](https://hub.docker.com/_/docker) doesn't support buildx(ref: https://github.com/docker-library/docker/issues/313)
- gcb-docker-gcloud image from k8s/test-infra probably was created due to the reason above, which supports buildx.(Example: https://github.com/kubernetes/test-infra/blob/master/images/git/cloudbuild.yaml)
- buildx has complex overriding logic of env vars, it's recommended to [set `ARG TARGETOS`](https://github.com/docker/buildx/issues/242) but don't specify default value, so that correct GOARCH can be used

Ran into build error of
```
go: cloud.google.com/go@v0.81.0: Get "https://proxy.golang.org/cloud.google.com/go/@v/v0.81.0.mod": tls: invalid signature by the server certificate: ECDSA verification failure
```

Which only happened on s390x build.

I will stop digging the hole and instead focusing on building individually, just like how these images are built right now

**Comment by chaodaiG** [comment]
Decided to build prow images with ko, the work was done:
- https://github.com/kubernetes/test-infra/pull/25119
- https://github.com/kubernetes/test-infra/pull/25157
- https://github.com/kubernetes/test-infra/pull/25269
- https://github.com/kubernetes/test-infra/pull/25271
- https://github.com/kubernetes/test-infra/pull/25281
- https://github.com/kubernetes/test-infra/pull/25310
