### ISSUE TITLE
Allow injecting env variables to Prowjobs from GitHub

### ISSUE THREAD

**Issue by YuviGold** [kubernetes/test-infra#23846]
**What would you like to be added**:

Injecting environment variables for jobs from GitHub comments using the `trigger` plugin.

**Why is this needed**:

Instead of creating a new job for every permutation mode under test, it would be incredibly maintainer-friendly to change configuration via the comments interface.
For example, I have a simple test `foo` but it allows to have different configurations like `MODE=[A|B|C]`.
In order to have them all available as a presubmit job, it would require defining 3 different jobs and keep ongoing for future modes to come.

It would be nice if it would be possible to define a single job and afterward to change/override the environment variable.
e.g.

```
/test foo MODE=A  # Will trigger <foo> and will pass env variable <MODE> to be <A>
/test foo MODE=B  # Will trigger <foo> and will pass env variable <MODE> to be <B>
```

valid configurations would be available only from a well-defined accept-list so no malicious injections would be allowed.

**Comment by petr-muller** [comment]
Looks nice with manual triggers, but we would need to be careful when designing this. Jobs have properties like when they run automatically (`always_run`) and blocking (`optional`). These properties would then be properties of the variants (variable value vector permutations) and that gets messy fast.

**Comment by BenTheElder** [comment]
> In order to have them all available as a presubmit job, it would require defining 3 different jobs and keep ongoing for future modes to come.

yaml anchors work in prow's parser last I checked. ;-)

this seems like an extremely abusable feature, though perhaps the allow list is enough.

what about e.g. `/retest`?

I think you should bite the bullet and write 3 jobs, one of the kubernetes ecosystem yaml management tools can help (e.g. customize?) or something custom, we have some jobs that are auto-generated for this sort of problem.

**Comment by BenTheElder** [comment]
(the other reason to actually have distinct jobs is that they should report with distinct names, it is confusing to the PR author to have the test results all have the same name even though they're not running the same thing, I'm not aware of any other CI doing this)
