### ISSUE TITLE
k8s-cherrypick-bot does not identify v1.6.x milestones as release milestones

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#2386]
See for example https://github.com/kubernetes/kubernetes/pull/43978

**Comment by lukaszgryglicki** [comment]
Can You provide more details?
Like what should it do and what is the current state?

**Comment by spiffxp** [comment]
maybe @kubernetes/kubernetes-release-managers or @kubernetes/release-maintainers can chime in, but I'm not sure we use v1.x.y milestones at all, eg: https://github.com/kubernetes/kubernetes/milestones?state=closed

**Comment by enisoc** [comment]
The use of a v1.6.1 milestone was ad hoc and caused confusion, so we hopefully won't do it again. I suggest to close this.
