### ISSUE TITLE
Run linter tests without bazel

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#23897]
**What would you like to be added**:

Run linter tests without bazel, the related bazel rules are:

- verify-pylint
- verify-tslint
- update-tslint
- verify-codegen
- verify-spelling
- update-spelling
- verify-label
- pylint_bin
- verify-gopherage

Things to be considered:

- This will need to co-exist with current bazel rules for a short while, delete linter test targets from bazel once this confirmed working
- Test driven by make rule and bash scripts

**Why is this needed**:

This is part of #23796 

**Recommended testing approach**:
- Make test invokable by `make test`
- Create a PullRequest with change, manually run job by commenting `/test pull-test-infra-test-beta`
- [Optional]: if there is any tool that needs to exist in test image, update image at https://github.com/kubernetes/test-infra/blob/6e0d21ee50d690c8f78239257f588021d2ed57b5/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L145

/sig testing
/help-wanted

**Comment by chaodaiG** [comment]
As far as I can tell all linting targets are defined in https://github.com/kubernetes/test-infra/blob/master/hack/BUILD.bazel, went through the targets and migrated following targets to make rules:

- verify-codegen
- verify-spelling
- verify-labels
- verify-gofmt
- verify-golangci-lint

Remaining:

- verify-pylint. Better to be after https://github.com/kubernetes/test-infra/issues/23830
- verify-tslint. Better to be after https://github.com/kubernetes/test-infra/issues/23829
- verify-bazel. To be deprecated
- verify-boilerplate. Uses python, better to be after https://github.com/kubernetes/test-infra/issues/23830
- verify-deps. WIP https://github.com/kubernetes/test-infra/pull/24194, depends on gazelle deprecation
- verify-gopherage. Uses typescript, better after https://github.com/kubernetes/test-infra/issues/23829

**Comment by BenTheElder** [comment]
typescript progress https://github.com/kubernetes/test-infra/pull/24491

**Comment by BenTheElder** [comment]
updated checklist, tslint was https://github.com/kubernetes/test-infra/pull/24491 and boilerplate was https://github.com/kubernetes/test-infra/pull/24891.

**Comment by chaodaiG** [comment]
After #25373 prow images are built without bazel
/close
