### ISSUE TITLE
Fix or delete containerd 1.4 canary jobs

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/test-infra#23915]
**What should be cleaned up or changed**:
Some of the contained 1.4 canary jobs have been failing for some time now. Considering that we're working with containerd 1.5 (canaries will be provided by https://github.com/kubernetes/test-infra/pull/23215), it might make sense to either fix or delete containerd 1.4 canary jobs.

**Provide any links for context**:
This are the relevant links for the jobs:
Job name | Source code | TestGrid
----|----|----
`ci-containerd-build-1-4` | [sig-node-containerd.yaml#L33](https://github.com/kubernetes/test-infra/blob/3011f1d951e254c8484e3ab3b5c35480b9f03440/config/jobs/kubernetes/sig-k8s-infra/canaries/sig-node-containerd.yaml#L33) | [sig-node-containerd#containerd-build-1.4](https://testgrid.k8s.io/sig-node-containerd#containerd-build-1.4)
`ci-containerd-node-e2e-1-4` | [sig-node-containerd.yaml#L240](https://github.com/kubernetes/test-infra/blob/3011f1d951e254c8484e3ab3b5c35480b9f03440/config/jobs/kubernetes/sig-k8s-infra/canaries/sig-node-containerd.yaml#L240) | [sig-node-containerd#containerd-node-e2e-1.4](https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.4)
`ci-containerd-node-e2e-features-1-4` | [sig-node-containerd.yaml#L316](https://github.com/kubernetes/test-infra/blob/3011f1d951e254c8484e3ab3b5c35480b9f03440/config/jobs/kubernetes/sig-k8s-infra/canaries/sig-node-containerd.yaml#L316) | [sig-node-containerd#containerd-node-e2e-features-1.4](https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-features-1.4)

/sig node
/sig k8s-infra
/area config
/area jobs
/cc spiffxp
/assign @mmiranda96

**Comment by mmiranda96** [comment]
Additionally, we might need to delete duplicate canaries under [config/jobs/kubernetes/sig-k8s-infra/canaries/sig-node-containerd.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/canaries/sig-node-containerd.yaml).

**Comment by dims** [comment]
+1 from me :) 

/cc @adisky

**Comment by mmiranda96** [comment]
After some more digging, I found the following logs:
```
W1008 17:44:52.489] 2021/10/08 17:44:52 node.go:62: Noop - Node KubectlCommand()
W1008 17:44:52.489] 2021/10/08 17:44:52 node.go:53: Noop - Node Down()
W1008 17:44:52.489] 2021/10/08 17:44:52 node.go:34: Noop - Node Up()
W1008 17:44:52.489] 2021/10/08 17:44:52 node.go:48: Noop - Node TestSetup()
...
W1008 17:44:52.702] Trying to find master named 'bootstrap-e2e-master'
W1008 17:44:52.703] Looking for address 'bootstrap-e2e-master-ip'
...
W1008 17:44:53.746] ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
W1008 17:44:53.746]  - The resource 'projects/cri-containerd-node-e2e/regions/us-central1/addresses/bootstrap-e2e-master-ip' was not found
W1008 17:44:53.746] 
W1008 17:44:53.991] Could not detect Kubernetes master node.  Make sure you've launched a cluster with 'kube-up.sh'
```
From the nature of the node runner, it looks like it expects the cluster to be up. However, the cluster does not exist. Is this the correct scenario? Is there anything I'm missing?
