### ISSUE TITLE
kops jobs do not dump kube-scheduler, kube-ontroller-manager, kube-proxy, etc. logs

### ISSUE THREAD

**Issue by wongma7** [kubernetes/test-infra#2397]
For instance, in this random recent PR job https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/41929/pull-kubernetes-e2e-kops-aws/19348/build-log.txt we run cluster/log-dump.sh and get
```
I0403 16:01:41.664] Dumping master and node logs to /workspace/_artifacts
I0403 16:01:41.665] Copying 'kube-apiserver kube-scheduler rescheduler kube-controller-manager etcd etcd-events glbc cluster-autoscaler kube-addon-manager fluentd cloud-init-output' from ec2-54-67-111-203.us-west-1.compute.amazonaws.com
I0403 16:01:41.665] scp: /var/log/kube-scheduler.log: Permission denied
...
I0403 16:01:41.665] scp: /var/log/kube-controller-manager.log: Permission denied
...
I0403 16:01:41.667] scp: /var/log/kube-proxy.log: Permission denied
```

Here's what /var/log looks like in a kops cluster:
```
-r--------  1 root root              31705 Apr  3 22:46 kube-controller-manager.log
```
LOG_DUMP_SSH_USER is `admin`, who doesn't have permissions to read & copy the file.

This could be a kops issue, I don't know what the standard is for setting permissions on these log files.

**Comment by justinsb** [comment]
Trying out a `chmod -R a+r /var/log` in https://github.com/kubernetes/kubernetes/pull/44017

**Comment by wongma7** [comment]
change to cluster/log-dump fixed it, no more permission denied errors in recent jobs :)
