### ISSUE TITLE
Logs from Kubemark tests are no longer uploaded to GCS buckets on failure.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#24]
Which makes debugging of regressions way harder.

cc @fejta @ixdy @spxtr @wojtek-t

**Comment by spxtr** [comment]
For [this](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/3601?pli=1) recent failure I'm seeing logs for the master and one node.

**Comment by gmarek** [comment]
For this
<https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-kubemark-500-gce/3174/artifacts/?project=kubernetes-jenkins>
there's none.

**Comment by spxtr** [comment]
Looks like [these lines](https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e.yaml#L26-L31) aren't in the kubemark config, so it's not dumping logs on timeout.

**Comment by wojtek-t** [comment]
@spxtr - yes, we have logs from failed runs, but we don't have from timed-out ones.
Can you please prioritize it? It's really annoying for us.

**Comment by spxtr** [comment]
Should be fixed.
