### ISSUE TITLE
Federation e2e tests failing: pulling ci tarball from wrong bucket.

### ISSUE THREAD

**Issue by colhom** [kubernetes/test-infra#240]
From kubernetes-e2e-gce-federation logs:

```sh
+ local -r bucket=kubernetes-release-dev
++ gsutil cat gs://kubernetes-release-dev/ci/latest.txt
+ build_version=v1.4.0-alpha.0.1035+d30fd0cb0c23ab
+ echo 'Using published version kubernetes-release-dev/v1.4.0-alpha.0.1035+d30fd0cb0c23ab (from ci/latest)'
+ fetch_tars_from_gcs gs://kubernetes-release-dev/ci v1.4.0-alpha.0.1035+d30fd0cb0c23ab
+ local -r gspath=gs://kubernetes-release-dev/ci
+ local -r build_version=v1.4.0-alpha.0.1035+d30fd0cb0c23ab
+ echo 'Pulling binaries from GCS; using server version gs://kubernetes-release-dev/ci/v1.4.0-alpha.0.1035+d30fd0cb0c23ab.'
+ gsutil -mq cp gs://kubernetes-release-dev/ci/v1.4.0-alpha.0.1035+d30fd0cb0c23ab/kubernetes.tar.gz gs://kubernetes-release-dev/ci/v1.4.0-alpha.0.1035+d30fd0cb0c23ab/kubernetes-test.tar.gz .
Using published version kubernetes-release-dev/v1.4.0-alpha.0.1035+d30fd0cb0c23ab (from ci/latest)
Pulling binaries from GCS; using server version gs://kubernetes-release-dev/ci/v1.4.0-alpha.0.1035+d30fd0cb0c23ab.

```

It has pulled a tarball published by `kubernetes-build`, not `kubernetes-federation-build`.

That later causes this error:

```sh
FATAL: tagfile /workspace/kubernetes/hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/../federation/manifests/federated-image.tag does not exist. Make sure that you have run build/push-federation-images.sh
```

I've fixed this error once before ( #146 ) by having kubernetes-federation-build and kubernetes-e2e-gce-federation use an entirely separate ci bucket, so something must have changed since that last PR was merged.

\cc @quinton-hoole @nikhiljindal @ixdy @spxtr

**Comment by ixdy** [comment]
cc @zmerlynn

**Comment by zmerlynn** [comment]
Oh! Your build job is overwriting the new bucket! Thanks for this bug!

**Comment by zmerlynn** [comment]
Okay, I understand why this is corrupting the main kubernetes build pipeline now, that's cool. Now, how are you overriding what bucket gets pulled? Overriding `KUBE_GCS_RELEASE_BUCKET` in `federation` jobs? I'm going to need to change that after I reintroduce https://github.com/kubernetes/kubernetes/pull/28193.

**Comment by ixdy** [comment]
Yup: https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/kubernetes-build.yaml#L77

I forgot about this override too.

**Comment by zmerlynn** [comment]
BTW, this issue *should* actually be fixed right now, but I'm leaving it open because I plan to reintroduce the PRs that briefly caused it.
