### ISSUE TITLE
Issues with https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md

### ISSUE THREAD

**Issue by kvmware** [kubernetes/test-infra#24004]
Some issues observed while trying to go through the `Tackle deployment` section of the document.

1. Under `GitHub App` the `Single File: Read-Only` permission is suggested. This permission requires a path to the file and if not given fails silently when one clicks `Create GitHub App`. It fails by showing no form validation error and does not continue. One would have to create the app first then add the permissions to see a form validation error. A value for that input field should be specified in the instructions.
2. As pointed out in https://github.com/kubernetes/test-infra/issues/23975, `tackle` defaults to check for `python` on the path and fails if it does not find it. Would be nice to have a sequence such as check for `python`, `python3`, and finally `python2` before failing.
3. While running `$ bazel run //prow/cmd/tackle` the prompt `Apply starter.yaml from [github upstream]:` comes up which if one selects the default (presses enter) fails with:
```
The Ingress "prow" is invalid: spec.rules[0].host: Invalid value: "prow.<< your-domain.com >>": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
FATA[0399] Could not deploy prow                         error="exit status 1"
```
How to configure `starter.yaml` should be outlined before.
**At this point I switched to the `manual deployment` instructions**

**Comment by alvaroaleman** [comment]
@kvmware yeah I would suggest removing mentionings of it for now until someone steps up and adds some basic integration testing
