### ISSUE TITLE
Warning logs in prow: Unable to add nonexistent labels

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#24025]
**What happened**:

Saw warnings in prow log:

```
jsonPayload: {
author: "tpepper"
component: "hook"
event-GUID: "21f911c0-2b72-11ec-96d7-82f7eea93b77"
event-type: "pull_request"
file: "prow/plugins/owners-label/owners-label.go:120"
func: "k8s.io/test-infra/prow/plugins/owners-label.handle"
level: "warning"
msg: "Unable to add nonexistent labels: ["committee/conduct"]"
org: "kubernetes"
plugin: "owners-label"
pr: 6148
repo: "community"
url: "https://github.com/kubernetes/community/pull/6148"
}
```

Pretty sure that this error is a user error and already surfaced on the issue/PR where this happens. No reason to log warning in prow

**Comment by chaodaiG** [comment]
> Pretty sure that this error is a user error and already surfaced on the issue/PR where this happens. No reason to log warning in prow

correction: this error is not testable on a PR, and even if it does, it could also be broken if a label is deleted from a repo. So this is likely going to cause noise/confusion if surfaced on PR.

**Comment by mrbobbytables** [comment]
It was previously `committee/conduct` but it was changed to  `committee/code-of-conduct` 2 years ago. The OWNERS file needs updating.

ref:
https://github.com/kubernetes/test-infra/blob/2242e3ec6b91c4629f36635330143c8d558875c2/label_sync/labels.yaml#L132-L139

**Comment by listx** [comment]
@chaodaiG What are the next steps here?

**Comment by chaodaiG** [comment]
There is not much action we can take here. This will continue to surface in prow logs, due to the reason I mentioned above. We'll probably want to keep this issue open so that when later oncall see this error message in prow logs they won't panic :)

**Comment by listx** [comment]
/reopen

Keeping this issue open for oncall to not panic in case it surfaces again in Prow logs.
