### ISSUE TITLE
Prow error log: exceeded a secondary rate limit with GitHub

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#24024]
**What happened**:

Saw error log in prow.k8s.io:

```
jsonPayload: {
component: "tide"
error: "failed to query GitHub for prs: query 4, err: non-200 OK status code: 403 Forbidden body: "{\n  \"documentation_url\": \"https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits\",\n  \"message\": \"You have exceeded a secondary rate limit. Please wait a few minutes before you try again.\"\n}\n""
file: "prow/cmd/tide/main.go:215"
func: "main.sync"
level: "error"
msg: "Error syncing."
}
```

This is happening on both tide and needs-rebase

**Comment by listx** [comment]
What are the next steps for this bug (to prevent it from happening again in the future)?

**Comment by listx** [comment]
FWIW this is still happening... for the `needs-rebase` component.

```
{
  "insertId": "hb60zh5t7agwi45o",
  "jsonPayload": {
    "error": "non-200 OK status code: 403 Forbidden body: \"{\\n  \\\"documentation_url\\\": \\\"https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits\\\",\\n  \\\"message\\\": \\\"You have exceeded a secondary rate limit. Please wait a few minutes before you try again.\\\"\\n}\\n\"",
    "msg": "Encountered errors when querying GitHub but will process received results anyways",
    "level": "error",
    "func": "k8s.io/test-infra/prow/external-plugins/needs-rebase/plugin.HandleAll",
    "plugin": "needs-rebase",
    "component": "needs-rebase",
    "file": "prow/external-plugins/needs-rebase/plugin/plugin.go:157"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "location": "us-central1-f",
      "container_name": "needs-rebase",
      "project_id": "k8s-prow",
      "pod_name": "needs-rebase-5497778fbd-phzw9",
      "cluster_name": "prow",
      "namespace_name": "default"
    }
  },
  "timestamp": "2021-11-12T16:42:39Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/pod-template-hash": "5497778fbd",
    "k8s-pod/app": "needs-rebase",
    "compute.googleapis.com/resource_name": "gke-prow-e2-standard-8-7f275a2e-yz24"
  },
  "logName": "projects/k8s-prow/logs/stderr",
  "receiveTimestamp": "2021-11-12T16:42:42.691956166Z"
}
```

**Comment by jmguzik** [comment]
I just wanted to let all the interested in solving this issue now, I am currently tracing some of the problems related to this.
Some API violations are obvious, the component/plugin is getting or sending too much data in the loop without any sleep or throttle in a spawn of 1-2 seconds. According to the https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-abuse-rate-limits this is abusive behavior and should be limited, although exact conditions triggering such errors are not published. There is only a high-level list of potential problems.
I saw this problem in `blunderbuss` plugin which I am trying to debug, but also in `tide.go:481` and in `needs-rebase`. Some of those problems could be solved using a proxy, but not the cases where fresh data is probably needed (`needs-rebase` and `tide`). Alternative approaches may consider sleeping where we know we want to get more data in the loop (using multiple queries), short-term throttle calculation, or dynamic query (APIv4 violations), which will group some of the requests in batches. The last one is not fully supported by the graphql library prow is using and requires using reflect.
If someone is interested in exchanging experiences and discussing this issue, feel free to reach out to me.

**Comment by jmguzik** [comment]
In our prow installation, this problem was solved to some extent by applying an additional throttling mechanism in ghproxy. We can't afford to have timing values provided by GitHub API documentation (1-sec time spacing), but even values in this commit: https://github.com/openshift/release/pull/27470/commits/02f92a7370a8a3db7394266538ae775fc2d46fdb were able to reduce secondary API hits in our system.

**Comment by jmguzik** [comment]
As for `needs-rebase`, an additional cache with a retention period can be added, which should decrease the number of API hits (frequency). Please consult this commit to see how to apply: https://github.com/openshift/release/pull/26657/commits/7fa0682704aab2b7c33cf294f1f0dc85cb56725b
