### ISSUE TITLE
Lets remove some presubmits!

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2403]
The following presubmits currently run against every PR:

- `pull-kubernetes-bazel`
- `pull-kubernetes-unit`
- `pull-kubernetes-verify`
- `pull-kubernetes-e2e-gce`
- `pull-kubernetes-e2e-gce-etcd3`
- `pull-kubernetes-e2e-gce-gci`
- ~~`pull-kubernetes-e2e-gce-non-cri`~~ #2363
- `pull-kubernetes-e2e-kops-aws`
- `pull-kubernetes-kubemark-e2e-gce`
- `pull-kubernetes-node-e2e`
- ~~`pull-kubernetes-node-e2e-non-cri`~~ #2363

Now that 1.6 is out the door, which of these can we drop? Ideally we stop running all but one of `pull-kubernetes-e2e-gce`, `pull-kubernetes-e2e-gce-etcd3`, and `pull-kubernetes-e2e-gce-gci`.

cc @mtaufen, since you have more context than I do.

**Comment by krzyzacy** [comment]
I think all the non-cri ones will gone soon. https://github.com/kubernetes/test-infra/pull/2363

**Comment by apelisse** [comment]
Out of curiosity, why are we removing presubmits?

**Comment by fejta** [comment]
I only want to eliminate redundant testing. So we should pick a single flavor of `pull-kubernetes-e2e-gce` to run on presubmit. However all the others seem different enough to keep. I would also like to add a federation job.
