### ISSUE TITLE
[cherry-pick-bot] fails to create cherry-pick PRs for cluster-api release-1.0 branch

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/test-infra#24108]
**What happened**:

When we’re trying to cherry-pick a PR in kubernetes-sigs/cluster-api to the release-1.0 branch, we get an error that the Github token of the bot doesn’t have the `workflow` scope. This prevents the bot from creating the cherry-pick PR: https://github.com/kubernetes-sigs/cluster-api/pull/5406#issuecomment-948292902
It stills works for other branches like release-0.4.

**What you expected to happen**:

Should have just worked like for the release-0.4. branch: https://github.com/kubernetes-sigs/cluster-api/pull/5406#issuecomment-949840373

**How to reproduce it (as minimally and precisely as possible)**:
Just post a comment with `/cherrypick release-1.0` in https://github.com/kubernetes-sigs/cluster-api/pull/5406

**Anything else we need to know?**:

I think the issue is that the cherry-pick bot is **currently** using a GitHub token without the workflow scope (as documented in https://github.com/kubernetes/test-infra/blob/master/prow/external-plugins/cherrypicker/README.md).

Cherry-picks to older branches like release-0.4 don't have to create or update workflows and that's why they work in contrast to cherry-picks to release-1.0. I assume a while back the bot was running with a GitHub token with the `workflow` scope.

I'm not sure how the cherry-pick bot is deployed exactly but I think it needs a token which also contains the `workflow` scope.

xref: Slack thread: https://kubernetes.slack.com/archives/C7J9RP96G/p1634827485007700

**Comment by spiffxp** [comment]
I've updated the token used by the bot, please close when you've confirmed it works as expected

![Screen Shot 2021-11-01 at 8 52 46 AM](https://user-images.githubusercontent.com/49258/139701934-d3b459ef-bd78-4c1a-9f37-56a47992df49.png)

**Comment by sbueringer** [comment]
Thx, works again! :)

/close
