### ISSUE TITLE
Ci Bot Should Explain Retriggering Tests

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2411]
When the bot requires ok-to-test, it should also mention how to retrigger tests in the event of failure (flake or real failure) or in the event of new code pushed.

**Comment by spiffxp** [comment]
Prow now explains how to use `/retest` or `/test failing test` in its report comments. Can we close this?

/unassign spxtr
/assign grodrigues3

**Comment by grodrigues3** [comment]
@spiffxp Yes we can! 
/close
