### ISSUE TITLE
Find out a better way to use latest images

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/test-infra#24147]
This is a follow up from https://github.com/kubernetes/kubernetes/issues/105381

**What would you like to be added**:

Consider using pinned image versions and the update mechanism for SIG node tests instead of `image_family`.

**Why is this needed**:

Explicit PRs with the image update will allow to narrow the test failures to the image update faster, and simplify the pinning in case of a "bad" image.

/sig node
/sig testing

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten

@kubernetes/sig-testing where can I find information on how the prow robot that sends PRs like this (https://github.com/kubernetes/test-infra/pull/25426) is configured? I think it would be handy to update images versions the same way instead of using `image_family`.

**Comment by cjwagner** [comment]
> /remove-lifecycle rotten
> 
> @kubernetes/sig-testing where can I find information on how the prow robot that sends PRs like this (#25426) is configured? I think it would be handy to update images versions the same way instead of using `image_family`.

Check out the [`generic-autobumper` tool](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/generic-autobumper#autobumper).
