### ISSUE TITLE
Label Sync doesn't support github app id and cert?

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes/test-infra#24143]
**What would you like to be added**:
I've migrate my Prow to latest Github App authentication. It uses github app id and github app cert to build the client. 
Recently, I plan to use label sync to manage labels across our repos. I notice it still required oauth token which is probably the old way. 

https://github.com/kubernetes/test-infra/blob/ed15194a460c3f9f8b384d2c0189af9e043d5462/label_sync/main.go#L146

I would like to use id and secret for authentication instead since we don't use oauth token anymore. Can someone help verify if that's valid request?  If so, I can help on the implementation to offer this option. 

**Why is this needed**:

Help prow users who use Github App to leverage label sync tool

/cc @Summer-Field

**Comment by petr-muller** [comment]
I think https://github.com/kubernetes/test-infra/pull/24927 resolved this

/close
