### ISSUE TITLE
Merge type "merge" disallowed by repo settings

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes/test-infra#24141]
![image](https://user-images.githubusercontent.com/4739316/139007300-837bcd2d-6f99-494c-8898-51421fad9ce6.png)

**What happened**:
tide can not merge the PR because `Merge type "merge" disallowed by repo settings`. The weird thing is we does allow all merge option in the repo setting.

```
{"client":"github","component":"tide","controller":"status-update","file":"prow/github/client.go:889","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"CreateStatus(xxxxx, xxxxxx, 14b1d33fcaf7086cb68354a433c8ee7a0f55e57f, {error  Not mergeable. Merge type \"merge\" disallowed by repo settings tide})","severity":"info","time":"2021-10-26T09:25:12Z"}
```

![image](https://user-images.githubusercontent.com/4739316/139007234-580cae69-bc05-4d7d-863d-6142f186d9e0.png)

**What you expected to happen**:
tide should merge the PR and this should be allowed.

**How to reproduce it (as minimally and precisely as possible)**:
v20211022-effa07f2d2

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by RinkiyaKeDad** [comment]
+1 - we've been facing the same issue. Here's the [slack thread](https://kubernetes.slack.com/archives/CDECRSC5U/p1635260608036300) where we were discussing this.

**Comment by Jeffwan** [comment]
> +1 - we've been facing the same issue. Here's the [slack thread](https://kubernetes.slack.com/archives/CDECRSC5U/p1635260608036300) where we were discussing this.

Thanks for pointing to the discussion. Seems it's due to some recent change. Let me debug using same way as they suggest and report status back. I will also try earlier version to see what happens.

**Comment by ludydoo** [comment]
I am facing the same issue using a github app. 
If i GET a repo from github API using a personal access token, i get the allows_merge, allows_squash, etc.
If i GET a repo from github API usign a github installation token, i do not get the fields.
There's a difference between the two APIs ...

**Comment by Jeffwan** [comment]
I think I figure out the problem. 
When we enable github app, auth header is never set in the HTTP request. Based on the docs here, https://docs.github.com/en/rest/reference/repos#get-a-repository, we know that anonymous request won't give us fields like `allow_merge_commit`,`delete_branch_on_merge` etc. I think this is the major problem

1. tide needs to call `m.ghc.GetRepo` to render `repoMethods` map.
https://github.com/kubernetes/test-infra/blob/b6d9d6ba54c695ff3bb9fa96046f76c583575a67/prow/tide/tide.go#L684-L690

2.  GetRepo is implemented by a HTTP request.
https://github.com/kubernetes/test-infra/blob/b6d9d6ba54c695ff3bb9fa96046f76c583575a67/prow/github/client.go#L2498-L2513

3.  It call `authHeader` to retrieve token and build authorization header.
https://github.com/kubernetes/test-infra/blob/b6d9d6ba54c695ff3bb9fa96046f76c583575a67/prow/github/client.go#L1153-L1155

4. `getToken` provides the real token
https://github.com/kubernetes/test-infra/blob/b6d9d6ba54c695ff3bb9fa96046f76c583575a67/prow/github/client.go#L1217-L1226

5. If Github authentication is used, `GetToken` return empty value. 
https://github.com/kubernetes/test-infra/blob/b6d9d6ba54c695ff3bb9fa96046f76c583575a67/prow/github/client.go#L689-L692

**Comment by alvaroaleman** [comment]
@Jeffwan In the apps auth case, the `Authorization` token gets set in a http transport which is a layer below the Client: https://github.com/kubernetes/test-infra/blob/0b0e54bbe47590cd19958b5d223bac62a4c9d8c1/prow/github/app_auth_roundtripper.go#L135

**Comment by Jeffwan** [comment]
@alvaroaleman Thanks for the update. I can confirm updating permission address the issue. :D

**Comment by rexagod** [comment]
Hello @alvaroaleman. I'm getting this on all PRs open on `mcg-ms-console` (tracking PR: https://github.com/red-hat-storage/mcg-ms-console/pull/33). I've set admin rights for all OpenShift bots (Openshift CI, Openshift CI robot and Openshift Merge robot), but the error still persists.

Any clues?

**Comment by rexagod** [comment]
Also, can you provide a screenshot of the "Contents" section where this change needs to be made? I can't seem to find that.
