### ISSUE TITLE
Pinned jobs are not using gcloud's kubectl

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#2418]

**Comment by krzyzacy** [comment]
temporary fix with #2417, still watching it

**Comment by krzyzacy** [comment]
Seems still have other issues. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-test/1660

**Comment by jlowdermilk** [comment]
kube-system pods failing doesn't seem related to gcloud change.

**Comment by jlowdermilk** [comment]
It looks like this started failing 3/31. The gcloud failures were a shorter window that started later and was fixed by #2417 
https://k8s-testgrid.appspot.com/google-gke#gci-gke-test

**Comment by krzyzacy** [comment]
looks green now

**Comment by fejta** [comment]
Did we revert the Todo?

**Comment by jlowdermilk** [comment]
Turns out the GKE jobs were broken for a completely unrelated bug in master configuration that should be fixed now. cc @maisem

**Comment by krzyzacy** [comment]
do we still need to keep that env?

**Comment by jlowdermilk** [comment]
Yes, because the pinned (i.e. not-running-k8s-head) jobs are still not using gcloud's kubectl.

**Comment by spiffxp** [comment]
I can't tell whether this is done or still needs to be open, hoping @zmerlynn can fill in context.  It looks like the temporary workaround may have gotten removed in https://github.com/kubernetes/test-infra/pull/3818.  Looking at ci-kubernetes-e2e-gke-* logs it doesn't look like gcloud's kubectl component is installed.

**Comment by spiffxp** [comment]
Workaround added back per https://github.com/kubernetes/test-infra/pull/4751

So I'm guessing this hasn't been addressed then

**Comment by spiffxp** [comment]
Booleans are fun.  Actual workaround added back via #4755

**Comment by spiffxp** [comment]
Added to all 1.5 jobs via #4757

**Comment by spiffxp** [comment]
do we still need this?

**Comment by krzyzacy** [comment]
@jlowdermilk feel free to reopen if you still need this I guess
