### ISSUE TITLE
prow.k8s.io: show skip reason

### ISSUE THREAD

**Issue by pohly** [kubernetes/test-infra#24209]
**What would you like to be added**:

When an e2e test gets skipped with `e2eskipper.Skipf`, the reason passed to that function is visible in the JUnit file.  It would be nice to show that on prow.k8s.io.

**Why is this needed**:

It's not always obvious why certain tests didn't run in a job.

**Comment by NikhilSharmaWe** [comment]
@pohly I would like to collaborate to add this feature in prow.k8s.io. Could you please elaborate on how should we proceed for the purpose.

**Comment by pohly** [comment]
I can't provide guidance on this because I don't know how the code behind prow.k8s.io works. I think it can be found here: https://github.com/kubernetes/test-infra/tree/master/prow/spyglass
