### ISSUE TITLE
TestDiskCachePruning is flaky

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#24200]
Found it in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/24199/pull-test-infra-unit-test/1455313585742811136

local reproed by `go test -count=10 ./ghproxy -run=TestDiskCachePruning`

**Comment by BenTheElder** [comment]
another https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/24491/pull-test-infra-unit-test/1468352617385037824

**Comment by chaodaiG** [comment]
I'll give it a stab
/assign

**Comment by chaodaiG** [comment]
I think I have figured out what happened.

This line https://github.com/kubernetes/test-infra/blob/c2a2c9389e885065507750ebf16eaeebb53472a1/prow/github/app_auth_roundtripper.go#L84 was invoked twice, which generates a random string based on current timestamp, the value is rounded to second, so if the test happens around half of a second then it'll generated a different token, thus fail the test
