### ISSUE TITLE
aws-janitor fails a few times a day

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2421]
https://k8s-testgrid.appspot.com/sig-testing-misc#maintenance-aws-janitor

/assign @justinsb @zmerlynn @krzyzacy 

Anything we can do to improve the stability of the aws janitor?

**Comment by spiffxp** [comment]
https://k8s-testgrid.appspot.com/maintenance#Summary
>26 of 168 (15.5%) failing in the past week; Last update: 06-30 10:11

**Comment by fejta** [comment]
@kubernetes/sig-aws-misc 

Looks like this job is broken now with 
`W0128 06:27:34.033] F0128 06:27:34.032656     212 main.go:880] --path "s3://janitor-jenkins/objs.json" isn't a valid S3 path: AccessDenied: Access Denied`

/remove-lifecycle stale

**Comment by chrislovecnm** [comment]
Do we have logs when it fails, how do we diagnose this problem?

**Comment by krzyzacy** [comment]
a sample red: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/maintenance-ci-aws-janitor/10006, but I cannot tell what's the error, maybe it simply returns non-zero when cleaned up something

**Comment by zmerlynn** [comment]
Yes, it "fails" anytime it has to clean something up, as a heads up that
something is leaking.

**Comment by krzyzacy** [comment]
thanks @zmerlynn, then this is WAI, I'll close the issue

**Comment by zmerlynn** [comment]
Is it back to intermittent? If so, there may be a separate kops bug.

**Comment by krzyzacy** [comment]
it fails like once/twice a day - might be related to some busted kops jobs
