### ISSUE TITLE
soak tests do not like the --extract pattern

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2437]
/assign

Need to fix this scenario in kubetest

https://storage.googleapis.com/k8s-gubernator/triage/index.html#26d4b2bec93532ddfb75
https://storage.googleapis.com/k8s-gubernator/triage/index.html#6c99e8dd8714f28ee8b0

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gce-2-test/1912

**Comment by spiffxp** [comment]
https://k8s-testgrid.appspot.com/google-soak

I don't think this is an issue anymore?
