### ISSUE TITLE
Internal error in testgrid: Your table may be too big

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/test-infra#24373]
**What happened**:
I tried to load https://testgrid.k8s.io/sig-testing-canaries#ci-kubernetes-generate-make-test-count10 and it persistently showed me an error message.
<img width="1106" alt="Screen Shot 2021-11-16 at 11 10 15 AM" src="https://user-images.githubusercontent.com/14296719/142023276-0cc3416b-5599-48fd-b7c9-765c8e492111.png">

**What you expected to happen**:
No error message from the testgrid.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
this is a variant of https://github.com/kubernetes/test-infra/issues/23425, https://github.com/kubernetes/test-infra/issues/22744
