### ISSUE TITLE
Make Label Plugin work in issue and PR bodies when they open. 

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2445]
Currently only works for issue comments. 

See the assign plugin for an example.

**Comment by grodrigues3** [comment]
Jun Tee is working on this

**Comment by crimsonfaith91** [comment]
I am carrying out some tests on the pull request and issue features.
ignore the comments below.

**Comment by spxtr** [comment]
#2505 will be deployed soon.
