### ISSUE TITLE
Link to contributor cheatsheet from welcome message

### ISSUE THREAD

**Issue by sftim** [kubernetes/test-infra#24476]
**What would you like to be added**:
Create a short link to https://www.kubernetes.dev/docs/contributor-cheatsheet/, eg https://k8s.dev/contributor-cheatsheet, with a promise to keep that short link current.

Update the @k8s-ci-robot welcome message to link to that short link.

**Why is this needed**:
This will send more web traffic to https://k8s.dev/ _and_ help visitors find those docs, especially new contributors.

**Comment by Neilblaze** [comment]
@sftim is this up for grab? If yes, can you please let me know the process of shortening the given URL using `https://k8s.dev/<alias>`?

**Comment by sftim** [comment]
@Neilblaze you're welcome to work on this and I might find time to offer you help with that, but I couldn't make a promise to do so.

**Comment by Neilblaze** [comment]
> @Neilblaze you're welcome to work on this and I might find time to offer you help with that, but I couldn't make a promise to do so.

Thanks a ton! @sftim 😃

**Comment by Neilblaze** [comment]
@sftim would you mind sharing/pasting the URL endpoint where I can generate shortened URL's using `https://k8s.dev/` ?

For example, 

This link `https://www.kubernetes.dev/docs/contributor-cheatsheet/` has been shortened to `https://k8s.dev/contributor-cheatsheet`. But when I explored `https://k8s.dev/`, it redirects me to `https://www.kubernetes.dev/`

**Comment by sftim** [comment]
I wouldn't really call it an API @Neilblaze - it's a Git repository. https://github.com/kubernetes/contributor-site

Specifically, you can create a file in https://github.com/kubernetes/contributor-site/tree/master/static named `_redirects`. See https://docs.netlify.com/routing/redirects/

Part of this work needs to happen there, and part of it needs happen in the Prow side of things.

BTW, use a 302 code for shortened URLs (Netlify only supports a subset of the 3xx statuses available in HTTP).

**Comment by AvineshTripathi** [comment]
Hey @Neilblaze what is the current status of this issue, incase you need any help I'd be delighted to work with you
