### ISSUE TITLE
updateconfig plugin supports updating all Prow config files

### ISSUE THREAD

**Issue by chizhg** [kubernetes/test-infra#24485]
**What would you like to be added**:

`updateconfig` plugin supports an option to update all Prow config files

**Why is this needed**:

Sometimes the `updateconfig` plugin does not work after PR is merged, https://github.com/istio/test-infra/pull/3664 is one example. It could be possibly due to lost webhook events, but the root cause was unknown.

Since `updateconfig` plugin is doing incremental update, when such issue happened, the only way to re-apply the config changes is to revert the PR and re-submit it, which is tedious and can be hard to troubleshoot if there are a lot of config files and PRs for the repo. It'll be nice if `updateconfig` plugin supports an option to update all Prow config files, so that the configs are guaranteed to be eventually consistent when any files is changed.

/area prow

**Comment by petr-muller** [comment]
Check out https://github.com/kubernetes/test-infra/tree/master/prow/cmd/config-bootstrapper , I think it does what you need. We are running it in periodic and it works fine.

**Comment by chizhg** [comment]
Thanks for the suggestion! We have decided to run config-bootstrapper for Knative periodically and will track the issue at https://github.com/knative/test-infra/issues/3220.
