### ISSUE TITLE
Detect when maintainers review code that they last changed

### ISSUE THREAD

**Issue by sftim** [kubernetes/test-infra#24515]
**What would you like to be added**:
Send alerts (eg into Slack) for the case when a maintainer makes a change to a PR and then adds their own LGTM and approval for that change.

**Why is this needed**:
As a maintainer I can review someone else's PR, amend it (eg using the suggestions API + accepting the change), LGTM it, approve it and trigger a merge.
Sometimes this is reasonable - it makes sense for small changes. On the other hand, the change might have a big impact; GitHub's API doesn't check and nor does Prow.

I might also authorized to force-push to the _main_ branch - which triggers an alert. Pushing to some other branch and then merging to _main_ feels equivalently unusual but doesn't trigger an alert. I think we should set up that kind of alerting.

**Additional context**:
I know that [k/website](https://github.com/kubernetes/website/) doesn't have that alerting. Maybe the mechanism exists, I haven't spotted the docs, and then it needs enabling. If so, I'll raise a related enhancement to turn that alerting on for most _kubernetes_ repos (_kubernetes-sigs_ repo owners can decide if that's a thing they want)

**Comment by sftim** [comment]
/sig testing
/sig security

(IMO)

**Comment by alvaroaleman** [comment]
If someone has write permissions on a repo it is implicit that they can make changes that are not peer-reviewed. If that isn't wanted, they shouldn't have those permissions.

**Comment by sftim** [comment]
What I'm looking for here is a detective control, not a preventative control (we already have one for direct pushes to _main_).

**Comment by alvaroaleman** [comment]
Someone who has write perms can simply label prs manually, I don't think this is useful.

**Comment by sftim** [comment]
> Someone who has write perms can simply label prs manually, I don't think this is useful.

Hmm. I guess the way to enforce “you can't LGTM your own changes” would be a third detective control to highlight when someone has set LGTM manually.

It's good to trust repo owners. I think it's also good to highlight when repo owners use their special access, because it _should_ be unusual and it _should_ be justifiable.

**Comment by rikatz** [comment]
+1
We must give some transparency. I get myself from time to time adding lgtm label on some self small stuff in ingress-nginx. Although it's fine when doing some firefighting, giving the chance to other contribs to know we did this and that "no manual action will be done without auditing" and also gives the chance for a maintainer to justify why they did that. 

IMO this should be opt-in (as not all projects have "development" channels separated from users channels) but highly recommended.

**Comment by BenTheElder** [comment]
I think sticky approval in the face of editing owners files is honestly more concerning than this but we've previously opted not to worry about this https://github.com/kubernetes/test-infra/issues/9238

You pretty much need to trust folks with permission to approve PRs, and trust that they're keeping an eye on PR content carefully.
