### ISSUE TITLE
PR check stuck with "needs lgtm label" while label is present

### ISSUE THREAD

**Issue by agradouski** [kubernetes/test-infra#24518]
**What happened**:
PR in question: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/15

Note, that PR has been merged but _tide_ is still pending and claims that _lgtm_ label is missing.

**What you expected to happen**:
I expect _tide_ to rerun and confirm that PR has all required labels and is ready to merge.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Please provide links to example occurrences, if any**:
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/15

**Anything else we need to know?**:
None.

**Comment by alvaroaleman** [comment]
I don't see a "need lgtm label" in the linked PR and the tide status is green. The GitHub UI has some awful caching, maybe that is the issue?

**Comment by agradouski** [comment]
thanks for looking @alvaroaleman -- must have been a caching issue. 
closing this issue.
