### ISSUE TITLE
Allowances for non-Prow YAML in the ProwJob config directory tree.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#24537]
**Why is this needed**:

The newly added checkconfig validation of unknown fields in ProwJob config has helped us fix a number of problems, but we are unable to enable it everywhere we'd like due to conflicts with non-Prow YAML that exists in the ProwJob config directory tree. In particular this seems to come in two forms:
1. Non-Prow YAML files collocated with their related ProwJob config files.
e.g. Template files used for ProwJob config generation and K8s resource files associated with the jobs.
1. Non-Prow fields included in files with valid ProwJob config.
e.g. Extra fields to define YAML anchors and intentionally changing top level field names to disable parts of the config (`presubmits`->`presubmits_disabled`).

**What would you like to be added**:

I'd like to add some features to allow non-Prow YAML to be explicitly labelled as such so that it can be ignored by unknown field validation. I have an idea for each of the above cases:
1. Update directory walk in the config loading code for both JobConfig and in-repo config to ~check for a `# PROW IGNORE` comment on the first line of the file. Skip loading the file if it is found.~ respect `.prowignore` files that behave like `.gitignore` files.
1. Add a top level `prow-ignored` field to JobConfig and in-repo config that has type `json.RawMessage` to avoid parsing. Any YAML anchors can be defined here as could configuration that is intended to be disabled or for another tool.

Please let me know if you have any concerns or better ideas. I'll start with a quick PR for the second idea.
/assign @alvaroaleman @stevekuznetsov @chaodaiG

**Comment by listx** [comment]
> 1. Update directory walk in the config loading code for both JobConfig and in-repo config to check for a # PROW IGNORE comment on the first line of the file. Skip loading the file if it is found.

Another idea is to create a `.prowignore` file in the style of `.gitignore` or `.rgignore`. Takes more work but from the user perspective I think it would feel cleaner.

> intentionally changing top level field names to disable parts of the config (presubmits->presubmits_disabled)

At first glance I am hesitant to try to cater to this practice. Isn't this what YAML comments are for? Why aren't users simply commenting out the whole field/block?

**Comment by chaodaiG** [comment]
> At first glance I am hesitant to try to cater to this practice. Isn't this what YAML comments are for? Why aren't users simply commenting out the whole field/block?

yaml anchor will not work in comment, so this is not feasible. Same with .prowignore

**Comment by cjwagner** [comment]
> At first glance I am hesitant to try to cater to this practice. Isn't this what YAML comments are for? Why aren't users simply commenting out the whole field/block?

I agree that we don't need to cater to this and comments can certainly be used to disable, but comments don't solve the case of configuration meant for other tools or for fields used for YAML anchor definitions.

`.prowignore` is an interesting idea. Though I wonder if `.prowignore`  would be more confusing or non-obvious since it could be defined in another directory. Given that there are only a handful of files this might be overkill initially?

**Comment by stevekuznetsov** [comment]
You can put a `.gitignore` at any spot under the tree, so I don't see why a `.prowignore` would be different. I'm not very well versed in YAML anchors, but I'm surprised that they don't get .... consumed ? by the templating process and continue to exist in the final document. Is that really the intended behavior?

**Comment by listx** [comment]
> Given that there are only a handful of files this might be overkill initially?

Yes.

> I'm not very well versed in YAML anchors, but I'm surprised that they don't get .... consumed ? by the templating process and continue to exist in the final document. Is that really the intended behavior?

I assume this depends on the templating system used. Maybe there are some out there that prefer minimalism and do not expand all anchors/references.

**Comment by alvaroaleman** [comment]
> I assume this depends on the templating system used. Maybe there are some out there that prefer minimalism and do not expand all anchors/references.

Its part of yaml itself so unless we are writing a yaml parser I would think that those are never visible to us and get expanded during parsing?

**Comment by cjwagner** [comment]
> Is that really the intended behavior?

Yeah this has always been my experience with YAML anchors. Some more details: https://stackoverflow.com/questions/60992314/can-i-assign-a-yaml-anchor-without-assigning-it-to-a-key

The only option currently is to change the first use of the anchor to the explicit anchor definition rather than defining the anchor separately first.

**Comment by cjwagner** [comment]
I found a seemingly suitable library for working with `.gitignore` files. This entrypoint in particular looks like what we'd want for `.prowignore` files: https://github.com/denormal/go-gitignore/blob/ae8ad1d07817b3d3b49cabb21559a3f493a357a3/repository.go#L39

**Comment by cjwagner** [comment]
This has been resolved via the linked PRs.
