### ISSUE TITLE
submit-queue can not pick the approved / lgtm issue

### ISSUE THREAD

**Issue by k82cn** [kubernetes/test-infra#2454]
Hi team,

In https://github.com/kubernetes/kubernetes/pull/40800 , all test are green & passed; but submit queue still report `Required Github CI test is not green: Jenkins Bazel Build` and did not pick it up.

What can I do to correct it?

**Comment by fejta** [comment]
@spxtr make a comment on the issue to ensure the munger picks up the new state.

**Comment by spxtr** [comment]
I said "@k8s-bot bazel test this", it reran the test, and it didn't pick up the status...

**Comment by fejta** [comment]
Right that's because that comment invalidated the previous run

**Comment by k82cn** [comment]
thanks for your help, the PR was merged :).
