### ISSUE TITLE
Node needs jobs to test swap serial tests

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#24558]
**What would you like to be added**:

New presubmit and serial jobs, similar to the existing swap jobs, that test the serial suite with swap enabled.

**Why is this needed**:

This is needed to test functionality that requires serial e2es for swap support, as well as ensuring test stability with swap enabled for the serial suite.

See also https://github.com/kubernetes/kubernetes/pull/105271

/sig node
/cc @wgahnagl @mmiranda96

**Comment by ehashman** [comment]
We added presubmits in https://github.com/kubernetes/test-infra/pull/24919 but we also need postsubmits.

**Comment by ehashman** [comment]
/assign @mmiranda96 

will this be ready for test freeze tomorrow?

**Comment by mmiranda96** [comment]
@ehashman PR is out: #25865
