### ISSUE TITLE
test-infra pull-test-infra-integration required job is failing

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#24597]
**What happened**:

Job is failing on all runs afaict.

**What you expected to happen**:

Job should pass.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

See https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-test-infra-integration?buildId=1468663750969004032

https://testgrid.k8s.io/presubmits-test-infra#integration

It appears the first failure was around 8am PT on 12/08 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/24575/pull-test-infra-integration/1468615818689384448 and it's been failing since.

**Anything else we need to know?**:

/priority critical-urgent
/sig testing
/kind failing-test

**Comment by ehashman** [comment]
Might be fixed with https://github.com/kubernetes/test-infra/pull/24593

**Comment by justaugustus** [comment]
Thanks for opening this, @ehashman!
Slack investigation here: https://kubernetes.slack.com/archives/C09QZ4DQB/p1638987371146700

/assign @alvaroaleman @chaodaiG @michelle192837 
cc: @kubernetes/test-infra-maintainers

**Comment by ehashman** [comment]
/close

appears fixed!
