### ISSUE TITLE
Fix failing node CI jobs

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#24592]
**What happened**:

After the dockershim removal, many SIG Node jobs are failing to run.

**What you expected to happen**:

Jobs should run!

**How to reproduce it (as minimally and precisely as possible)**:

See https://testgrid.k8s.io/sig-node-kubelet

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

I will fix this by submitting migrations to CRI/removing tests when coverage already exists.

/sig node
/assign

**Comment by ameukam** [comment]
There are is a good chance https://github.com/kubernetes/test-infra/issues/23822 is part of it.
Also, is it possible to stop usage of ` gs://cri-containerd-testing` ?
