### ISSUE TITLE
Move Docker-based SIG Node performance tests to CRI

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#24619]
**What should be cleaned up or changed**:

ci-kubernetes-node-kubelet-performance-test runs on Docker:

https://github.com/kubernetes/test-infra/blob/659ec3e9040b028115bf1e4269a383a1200e79e0/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L734-L762

/sig node
/assign @SergeyKanzhelev

**Comment by Namanl2001** [comment]
can I take this up?

**Comment by SergeyKanzhelev** [comment]
> can I take this up?

Absolutely, this job is commented now and needs to be migrated: https://github.com/kubernetes/test-infra/blob/423db756f9dffceb1a90fa4814964533517774d7/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L117-L146
