### ISSUE TITLE
Move docker-based node presubmits to CRI

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#24620]
**What should be cleaned up or changed**:

SIG Node has a number of presubmit jobs that need to be migrated off Docker.

I suggest we declare bankruptcy, remove all Docker-based jobs, and add jobs back under the CRI as needed.

/sig node

**Comment by SergeyKanzhelev** [comment]
I agree with the proposal. Let's close the issue and only add jobs to presubmits as needed

/close

**Comment by ehashman** [comment]
@SergeyKanzhelev do we want to leave this open in order to track the removal? That hasn't been done yet.

/reopen

**Comment by SergeyKanzhelev** [comment]
/assign

I will create a checkboxes for all tests and we can get owners for each of them.

**Comment by matthyx** [comment]
@ehashman just to understand the process here... if I understand correctly:

1. delete all jobs with docker
2. wait for people to scream
3. add one-by-one upon request

So there is no communication to write to kubernetes-dev, which is the part I'm afraid to do?

**Comment by matthyx** [comment]
If that's "only" that, I can take care of it.

**Comment by matthyx** [comment]
as agreed...
/assign

**Comment by SergeyKanzhelev** [comment]
Check for serial presubmit (see [thread](https://kubernetes.slack.com/archives/C0BP8PW9G/p1641402411481500))

**Comment by matthyx** [comment]
/reopen
Will make sure I'm not missing any with `KUBE_CONTAINER_RUNTIME!=remote`.
Other strategy would be to open a PR and run all presubmits.

**Comment by matthyx** [comment]
> Other strategy would be to open a PR and run all presubmits.

https://github.com/kubernetes/kubernetes/pull/107506

**Comment by matthyx** [comment]
@ehashman after investigating my dummy PR, here are the propositions:

The following jobs are using dockershim and should be deleted:
- pull-kubernetes-e2e-gce-ubuntu
- pull-kubernetes-node-kubelet-eviction
- pull-kubernetes-node-kubelet-eviction-kubetest2
- pull-kubernetes-node-e2e-kubetest2
- pull-kubernetes-node-kubelet-serial-kubetest2
- pull-kubernetes-node-kubelet-serial
- pull-kubernetes-node-e2e-alpha
- pull-kubernetes-node-e2e
- pull-kubernetes-node-swap-ubuntu
- pull-kubernetes-node-e2e-podutil
- pull-kubernetes-node-e2e-alpha-kubetest2

Other jobs that are using dockershim but from a different sig, should I ask them to migrate or delete?
- pull-kubernetes-e2e-gce-large-performance
- pull-kubernetes-e2e-gce-iscsi-serial
- pull-kubernetes-e2e-gce-iscsi
- pull-kubernetes-e2e-aks-engine-gpu-windows-dockershim

And finally these are jobs that don't even start when you launch them, what to do with them?
- pull-kubernetes-node-kubelet-serial-cpu-manager
- pull-kubernetes-node-kubelet-serial-hugepages
- pull-kubernetes-node-kubelet-serial-memory-manager
- pull-kubernetes-node-kubelet-serial-topology-manager-kubetest2
- pull-kubernetes-node-kubelet-serial-cpu-manager-kubetest2
- pull-kubernetes-e2e-gce-correctness
- pull-kubernetes-e2e-gce-kubetest2

**Comment by matthyx** [comment]
@ehashman should I contact sig-cloud-provider for their dockershim presubmits?
