### ISSUE TITLE
Resource quota limit issues in AWS

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes/test-infra#24631]
**What happened**: The E2E tests in CAPA repo are failing because of insufficient EC2 instances, has anything changed recently wrt the resource quota limit in test-infra accounts?

**What you expected to happen**: The tests should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-aws#periodic-e2e-main

**Anything else we need to know?**:

**Comment by dims** [comment]
@Ankitasw is this what you were pointing to?

```
E1210 03:27:12.276946       1 awsmachine_controller.go:521]  "msg"="unable to create instance" "error"="failed to create AWSMachine instance: failed to run instance: VcpuLimitExceeded: You have requested more vCPU capacity than your current vCPU limit of 32 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.\n\tstatus code: 400, request id: b793a837-c3f5-4f19-9465-0fb47eb7284d"  
```

**Comment by dims** [comment]
@eddiezane @justinsb are probably folks who know about the AWS accounts in boskos and how they are configured. looking at urls like https://portal.nutanix.com/page/documents/kbs/details?targetId=kA00e000000buFnCAI#:~:text=You%20have%20requested%20more%20vCPU,a%20vCPU%20limit%20of%2032. it feels like the account limits need to be bumped

**Comment by Ankitasw** [comment]
> @Ankitasw is this what you were pointing to?

yes @dims, it is weird that we are facing this issue suddenly, coz these tests have been running in the pipe like forever, so wanted to know if something has been changed.
@eddiezane @justinsb can you please point out if any changes has been done recently, and how to overcome this issue from test-infra side?

**Comment by dims** [comment]
@Ankitasw there's another issue i dug up, please see https://github.com/kubernetes/k8s.io/issues/1921

**Comment by eddiezane** [comment]
Taking a look

/assign

**Comment by geoffcline** [comment]
Hi,

@bwagner5 does EC2 capacity stuff for AWS. I've asked him to look into this.

**Comment by Ankitasw** [comment]
Thanks @geoffcline. 
Hi @bwagner5, we are seeing that somehow the quota is getting reduced to [32](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e/1464065565801844736/artifacts/initial-resource-quotas.yaml) vCPUs for EC2 instances, and in few places we see it as [512](https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e/1469140416698781696/artifacts/initial-resource-quotas.yaml). Any reason why this quota difference we see in different accounts?

cc @sedefsavas

**Comment by eddiezane** [comment]
Talking with @Ankitasw tomorrow to narrow this down to the right sub accounts.

**Comment by eddiezane** [comment]
I have submitted requests to raise all AWS capa accounts to an on demand general instance vcpu limit of (at least) 128 as well as on demand gpu instance limit of 8.

**Comment by Ankitasw** [comment]
Thankyou for the support @eddiezane, let's wait for this week to close this issue as service requests might take time to be fulfilled. Post that I will monitor the pipeline to see if everything is ok and will close this issue.

**Comment by eddiezane** [comment]
These quotas requests should all be live now.

**Comment by BenTheElder** [comment]
FWIW: This repo only handles renting out of accounts for test purposes, the actual accounts are from https://github.com/kubernetes/k8s.io / SIG k8s infra.
