### ISSUE TITLE
Rename SIG Node periodic job names for consistency

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#24641]
**What should be cleaned up or changed**:

Let's choose a standardized naming scheme for our jobs, preferably ones that don't reference OS or container runtime.

**Provide any links for context**:

https://github.com/kubernetes/test-infra/issues/21430
https://github.com/kubernetes/test-infra/pull/24595#discussion_r767018782

/sig node

**Comment by NikhilSharmaWe** [comment]
@ehashman I would like to work on changing the SIG Node periodic job names for consistency according to appropriate pattern. I read the comments you mentioned but I am unable to understand fully about the issue. Could you please explain and elaborate on the issue.

**Comment by SergeyKanzhelev** [comment]
/reopen

I will work on this
