### ISSUE TITLE
Access to CI hyperkube container image

### ISSUE THREAD

**Issue by colhom** [kubernetes/test-infra#2467]
Reading through the GCE federation-e2e logs, I've noticed that kubefed pulls the hyperkube image from `gcr.io/k8s-jkns-e2e-gce-federation/hyperkube-amd64`. I'm currently working on implementing federation-e2e on AWS using kubefed, and have noticed that anonymous pull on that repo is forbidden.

Would it be possible to open up anonymous pull access to `gcr.io/k8s-jkns-e2e-gce-federation/hyperkube-amd64` (plus other architectures)? 

\cc @madhusudancs @zmerlynn

**Comment by madhusudancs** [comment]
I don't think it is dangerous to make these images world-readable. We were just being conservative. But the question is, how do you know which image tags you want? And what if that tag is not available?

**Comment by colhom** [comment]
@madhusudancs the image tag for the `hyperkube-amd64` image is generated by replacing `+` with `_` in the Kubernetes version. I'm not sure if it's guaranteed that the `hyperkube-amd64` image has been pushed by the time the e2e job gets kicked off. IIRC, it's pushed as part of the same build job that uploads the release bundle `kops-e2e` already consumes, in which case we should just be able to assume it's there already?

**Comment by madhusudancs** [comment]
>@madhusudancs the image tag for the hyperkube-amd64 image is generated by replacing + with _ in the Kubernetes version.

What I was asking was, how do you obtain the version string? 

> I'm not sure if it's guaranteed that the hyperkube-amd64 image has been pushed by the time the e2e job gets kicked off. IIRC, it's pushed as part of the same build job that uploads the release bundle kops-e2e already consumes, in which case we should just be able to assume it's there already?

Oh I see. This runs as part of kubernetes jenkins? That wasn't clear. If that's the case, it is not that difficult to block/trigger on the build job.

**Comment by colhom** [comment]
> how do you obtain the version string?

https://github.com/kubernetes/kubernetes/blob/master/federation/cluster/federation-up.sh#L49-L70

> This runs as part of kubernetes jenkins?

Eventually it will, I'm just building federation e2e into `scenarios/kubernetes_kops_aws.py` and doing testing by running the scenario file directly.

When it's running in jenkins, it should get triggered by the `kubernetes-federation-build` job. We should also version-lock the underlying cluster versions to something more sane than tip (latest alpha maybe?). We can take care of this by passing flags to the `kubernetes_kops_aws.py` scenario file, specifying the version for the underlying clusters and federation control plane separately.

Right now I just need to test both versions at the latest alpha to make sure my modifications to the testing framework are valid, then I'll move on the adding to jenkins jobs config to test commits/PRs.

**Comment by colhom** [comment]
@madhusudancs thanks for discussion/opening the image repo up. This is resolved now.
