### ISSUE TITLE
pull-test-infra-gubernator presubmit is consistently failing for all PRs

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/test-infra#24687]
**What happened**:

The `pull-test-infra-gubernator` job/presubmit is consistently failing for all PRs, therefore blocking them. It appears that there's some problem with Python dependencies. An example run can be found here: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/24683/pull-test-infra-gubernator/1471123708318846976

Here's a part of the log:

```
Collecting lazy-object-proxy (from astroid<1.5.0,>=1.4.5->pylint==1.6.4->-r test_requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/6f/3e/7c80e8536b9d5eb66e784fff4c359adf9e55b37460fd6928192256ba71f2/lazy-object-proxy-1.7.0.tar.gz (42kB)
...
      File "/tmp/easy_install-JsFNwm/setuptools_scm-6.3.2/setup.py", line 22
        f"{type(self).__name__} is forbidden, "
                                              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
```

**What you expected to happen**:

The `pull-test-infra-gubernator` job/presubmit is passing for all PRs.

**Please provide links to example occurrences, if any**:

#24683 but other PRs are affected as well.

**Anything else we need to know?**:

/priority critical-urgent
This is blocking Kubernetes 1.22.5 release scheduled for today.

cc: @kubernetes/release-engineering

**Comment by michelle192837** [comment]
Looks like this started failing between these two runs:

```
1470940785301000192 | #24679Update Prow to v20211214-938f24ffd3 (44cef0a) by k8s-ci-robot | Dec 14 18:17:01Dec 14 2021, 18:17:01 UTC-0800 | 9s | FAILURE
-- | -- | -- | -- | --
1470910530590871552 | #24679Update Prow to v20211214-938f24ffd3 (f5a546f) by k8s-ci-robot | Dec 14 16:16:45Dec 14 2021, 16:16:45 UTC-0800 | 1m12s | SUCCESS
```

e.g. on Dec. 14 between 8:16 and 10:17 am PST

I don't think this lines up with recent Prow/image bumps:
- https://github.com/kubernetes/test-infra/pull/24667
- https://github.com/kubernetes/test-infra/pull/24677
- https://github.com/kubernetes/test-infra/pull/24674

Looks like this might be from fetching a new version of a package; comparing the passing vs. failing runs above:

```
# Passing:
Collecting lazy-object-proxy (from astroid<1.5.0,>=1.4.5->pylint==1.6.4->-r test_requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/47/38/a1c09bf77d6a161bb42e8f81b6144e6e4e2d9b3eb32e0acad139033e8cb7/lazy_object_proxy-1.6.0-cp27-cp27mu-manylinux1_x86_64.whl (53kB)

# Failing:
Collecting lazy-object-proxy (from astroid<1.5.0,>=1.4.5->pylint==1.6.4->-r test_requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/6f/3e/7c80e8536b9d5eb66e784fff4c359adf9e55b37460fd6928192256ba71f2/lazy-object-proxy-1.7.0.tar.gz (42kB)
```

**Comment by michelle192837** [comment]
Oh ha, this might be relevant, unsure if we're using 2.7 or not.

https://pypi.org/project/lazy-object-proxy/

```
1.7.1 (2021-12-15)
Removed most of the Python 2 support code and fixed python_requires to require at least Python 3.6.

Note that 1.7.0 has been yanked because it could not install on Python 2.7. Installing lazy-object-proxy on Python 2.7 should automatically fall back to the 1.6.0 release now.

1.7.0 (2021-12-15)
Switched CI to GitHub Actions, this has a couple consequences:
Support for Python 2.7 is dropped. You can still install it there but it’s not tested anymore and Python 2 specific handling will be removed at some point.
Linux wheels are now provided in musllinux and manylinux2014 variants.
Fixed __index__ to fallback to int if the wrapped object doesn’t have an __index__ method. This prevents situations where code using a proxy would otherwise likely just call int had the object not have an __index__ method.
```

**Comment by mpherman2** [comment]
Seems like the problem comes from our use of an older version of pylint 
https://github.com/kubernetes/test-infra/blob/master/gubernator/test_requirements.txt
Not sure what is holding us to this specific version though

**Comment by michelle192837** [comment]
We really should update the pylint version :/ But in the meanwhile I think pinning to 1.6.0 will work.
