### ISSUE TITLE
Put k8s.io redirection under source control

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#247]
Lets address #195 by putting the redirector under source control.

**Comment by rmmh** [comment]
It's not just a redirector, it also is responsible for the `go get k8s.io/...` magic and several other important functions -- I've talked with @thockin about what's involved in getting this checked in and deployed in a better manner.

**Comment by rmmh** [comment]
Done! https://github.com/kubernetes/k8s.io/tree/master/k8s.io
