### ISSUE TITLE
Migrate "pull-kubernetes-local-e2e" job to use containerd 

### ISSUE THREAD

**Issue by adisky** [kubernetes/test-infra#24715]
**What should be cleaned up or changed**:
Currently "pull-kubernetes-local-e2e" uses [Kubekins image](https://github.com/kubernetes/test-infra/tree/master/images/kubekins-e2e) which has docker installed to run kubetest. There can be two ways this job can be migrated to use containerd

1. Migrate this job to use a new image which has containerd+docker already installed
2. Use the same Kubekins image enable containerd cri plugin and install CNI 

if we go by [2] should we enable plugin/install cni  in the image manifest or in the script? 

**Provide any links for context**:
https://github.com/kubernetes/kubernetes/pull/106909

**Comment by aojea** [comment]
there are also more jobs with the same issue

https://storage.googleapis.com/k8s-triage/index.html?text=error%20during%20.%2Fhack%2Fe2e-internal%2Fe2e-up.sh

kubelet fails to start with 
```
E1221 07:07:44.806631   12906 server.go:301] "Failed to run kubelet" err="failed to run Kubelet: using dockershim is not supported, please consider using a full-fledged CRI implementation"
kubelet.service: Main process exited, code=exited, status=1/FAILURE
kubelet.service: Failed with result 'exit-code'.
```

and the job fails with 
```
error during ./hack/e2e-internal/e2e-up.sh
```

**Comment by adisky** [comment]
@aojea I think that is a different issue, local provider is only being used in 1 CI job
local provider being used https://cs.k8s.io/?q=--provider%3Dlocal&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra
The other jobs are using gcp provider and for gcp images are available with containerd installed, so those jobs can be migrated

**Comment by BenTheElder** [comment]
defer to dims on local-up-cluster.sh changes, but generally not thrilled to add _even more_ things installed in the kubekins image, that image is a mess and I would like to see projects supply their own, saner images whenever possible 🙃 

kind has a somewhat more streamlined version (images/krte) if folks need a starting point to fork.

**Comment by dims** [comment]
+1 to start from `krte`

**Comment by adisky** [comment]
Creating the new image is not required now, added support to install cni in the script itself`local-up-cluster.sh`
https://github.com/kubernetes/kubernetes/pull/108160

**Comment by adisky** [comment]
Its done, the jobs is running now
/close
