### ISSUE TITLE
Request: GCE projects where we can bind serviceaccounts to project roles

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#24747]
**What would you like to be added**:

GCE test projects where we can add iam bindings to projects, supporting custom serviceaccounts.

**Why is this needed**:

kOps recently added support for minimal serviceaccounts & roles on GCE.  However, this broke our e2e testing, because we do not have permission to add IAM bindings to the GCE test projects (I believe).

An example error message from https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-gce-latest/1475825924208332800/build-log.txt: 
```
W1228 13:58:13.872939    5065 executor.go:139] error running task "ProjectIAMBinding/serviceaccount-nodes" (1m38s remaining to succeed): error updating IAM for project e2e-gce-gci-ci-slow-1-4: googleapi: Error 403: Policy update access denied., forbidden
```

The way it works currently is that we create two serviceaccounts per cluster (control-plane and node), and that we grant them project level permissions.  We use existing roles because of the problems of garbage collecting roles (cannot reuse same names within 7 days after deletion).  We also grant IAM permissions to the GCS bucket that stores state data (but that is not the problem here, at least)

**Comment by BenTheElder** [comment]
this issue should probably be filed in github.com/kubernetes/k8s.io to have the projects created under SIG-k8s-infra?
