### ISSUE TITLE
prow.k8s.io: build cluster failing to start jobs 

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/test-infra#24769]
Error looks like this:
> Init container clonerefs not ready: (state: terminated, reason: "StartError", message: "sandbox container \"db8503ac0fa3bfb581d5f1fc26d8a2e7bfba400aad57d6c301b2fa0a9ce8ee00\" is not running: Error on reading termination message from logs: failed to try resolving symlinks in path \"/var/log/pods/test-pods_c94dcab7-6d76-11ec-8803-caec37ec3803_7dca5dd8-c549-4781-b028-5ff6bac317b4/clonerefs/0.log\": lstat /var/log/pods/test-pods_c94dcab7-6d76-11ec-8803-caec37ec3803_7dca5dd8-c549-4781-b028-5ff6bac317b4/clonerefs/0.log: no such file or directory") Init container initupload not ready: (state: waiting, reason: "PodInitializing", message: "") Init container place-entrypoint not ready: (state: waiting, reason: "PodInitializing", message: "")

Example job [link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1478410097527885824)
For more, see: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-test-main

I also saw this in some other jobs, but capi-test-main is by far the worst.
Some other examples:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/5885/pull-cluster-api-verify-main/1478677479144034304
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/5905/pull-cluster-api-apidiff-main/1478675472421228544
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/5902/pull-cluster-api-verify-main/1478377392555692032
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/2996/pull-cluster-api-provider-aws-verify/1478342101140770816
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-cache/1478340638637297664
(Can be found by looking through jobs with 1-2s duration in https://prow.k8s.io/?state=failure)

xref:
* first thread in sig-testing: https://kubernetes.slack.com/archives/C09QZ4DQB/p1641316443192500
* now in testing-ops: https://kubernetes.slack.com/archives/C7J9RP96G/p1641379832054700

**Comment by sbueringer** [comment]
I checked a bunch of failed Jobs and also some of the successful runs of `periodic-cluster-api-test-mai` and it comes down to that the Jobs fail when they are running on node `prow-e2-default-pool-bdc23de7-sflz` and are successful otherwise.

**Comment by chaodaiG** [comment]
@sbueringer , thank you for the detailed analysis, it looks pretty obvious that there is a bad node in the build cluster.

Checked one of the jobs `pull-cluster-api-verify-main` at https://github.com/kubernetes/test-infra/blob/24bae60a3b244c2179afa9e619a55a974bff9802/config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits-main.yaml#L66, it doesn't define any build cluster, so it's running on the default build cluster from k8s-prow-builds project. I just labeled the node `prow-e2-default-pool-bdc23de7-sflz` to be removed, and things should not fail on this node now.

**Comment by sbueringer** [comment]
I agree. Thank you very much!

I'll close the issue, if it occurs again I'll reopen.

/close

**Comment by alculquicondor** [comment]
/reopen

This is happening quite often for our new sigs.k8s.io/kueue project

- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/81/pull-kueue-test-unit-main/1499045211047727104
- https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kueue/kueue-presubmits.yaml

Could it be the same problem?

**Comment by chaodaiG** [comment]
Two other instances:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/75/pull-kueue-test-unit-main/1499026982501879808
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/75/pull-kueue-test-unit-main/1498776330072756224

Clicking on `Pod` under `Job Pod Info` section, these jobs didn't run on the same node, so probably different reasons from last time

**Comment by sbueringer** [comment]
We also have a few failed ProwJobs like this across a few CAPI repos. 
I don't think the root cause is the same.

xref: https://kubernetes.slack.com/archives/CD6U2V71N/p1646162568073629

**Comment by chaodaiG** [comment]
Prow jobs listed under https://prow.k8s.io/?state=error are pretty much all failed with the same reason, there were 1141 jobs at the moment, which means 1141 jobs out of 20797 jobs in the past 48 hours were affected by this

**Comment by chaodaiG** [comment]
/assign
taking a quick look to check whether there is something suspicious

**Comment by chaodaiG** [comment]
Pick a job failed more recently https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-amzn2-k23-ko23-docker/1499486599044403200, relevant error logs (query https://cloudlogging.app.goo.gl/34dxJcGwGighXR9F7) are:


12:47:19.327 PST
```
No sandbox for pod "1df04b2e-9b33-11ec-8399-364cd92c8a37_test-pods(1b39fd71-6353-4f18-ae39-b049e1c999f3)" can be found. Need to start a new one
```

12:51:19.000 PST
```
"Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
```

12:51:34.000 PST (repeat every 15 seconds until time out)
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to reserve sandbox name "1df04b2e-9b33-11ec-8399-364cd92c8a37_test-pods_1b39fd71-6353-4f18-ae39-b049e1c999f3_0": name "1df04b2e-9b33-11ec-8399-364cd92c8a37_test-pods_1b39fd71-6353-4f18-ae39-b049e1c999f3_0" is reserved for "97960dfee758ec7c4329d21e96bfb1bdea8f4a6cda0fdff4ee52a758c12a50d9"
```

**Comment by chaodaiG** [comment]
Skimmed through a few failed jobs, noticed node names showing up repeatedly, so drilled a bit deeper into metrics https://cloudlogging.app.goo.gl/cpAwnhjjm93qpfh17, and found out that this did happen on a handful number of nodes:

![Screen Shot 2022-03-03 at 1 34 03 PM](https://user-images.githubusercontent.com/45011425/156656399-97d911fb-4a53-4745-ad88-b13e03bf5adb.png)

I'm deleting these nodes now

**Comment by chaodaiG** [comment]
Done marking these nodes from removal.
(Fun fact: there were several pods pending timing out on these nodes by the time I got to them)

**Comment by alculquicondor** [comment]
Any idea what could lead nodes to start failing?

**Comment by chaodaiG** [comment]
no idea, we don't have a good enough way of querying from all prow jobs yet
