### ISSUE TITLE
k8s TestGrid is not displaying complete results for ibm-unit-test-ppc64le tab

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/test-infra#24779]
**What happened**:
The test grid at https://k8s-testgrid.appspot.com/ibm-unit-tests-ppc64le#Periodic%20unit%20test%20suite%20on%20ppc64le is displaying results of only the last four days though it is supposed to display results of 15 days.

**What you expected to happen**:
The Dashboard is supposed to display the results of all 15 days.

**How to reproduce it (as minimally and precisely as possible)**:
Have a look at the above testgrid page.

**Please provide links to example occurrences, if any**:
https://k8s-testgrid.appspot.com/ibm-unit-tests-ppc64le#Periodic%20unit%20test%20suite%20on%20ppc64le

![image](https://user-images.githubusercontent.com/63038004/148162198-8bdcd4d1-0fcf-400d-819b-61854aaf2f40.png)

**Anything else we need to know?**:
Below were looked at:
1. There is no `days_of_results` specified for the test group `ppc64le-unit` at https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubernetes/sig-cloud-provider/ibm/config.yaml.
Hence it is supposed to pickup the common value of 15 days from https://github.com/kubernetes/test-infra/blob/master/config/testgrids/default.yaml#L6
2. Verified if the gs bucket gs://ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le has the log folders for past 15days. The logs are available for display.

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag ^^

**Comment by BenTheElder** [comment]
there's almost certainly too many rows. you can find other issues in this repo related to the kubernetes unit tests and testgrid

**Comment by Rajalakshmi-Girish** [comment]
> there's almost certainly too many rows. you can find other issues in this repo related to the kubernetes unit tests and testgrid

Have seen https://github.com/kubernetes/test-infra/issues/23425#issuecomment-974524375

Our job is a periodic one running at 3h intervals. At the moment, looks like it is not possible to view all the results of 15 days (8 runs each day)
It is currently displaying close to ~19 columns ( results of 2 and 1/2 days)

**Comment by BenTheElder** [comment]
> Have seen [#23425 (comment)](https://github.com/kubernetes/test-infra/issues/23425#issuecomment-974524375)

As far as I know this stands and is going to apply to most any tab with kubernetes unit tests. It can only handle a few columns because there are _so_ many rows in the current implementation.

Either the number of rows needs to be reduced, or we have to accept less columns.

Rows could be reduced by changing the kubernetes test output, or by patching testgrid.

AIUI one possible avenue is updating the component that takes junit in GCS => testgrid to group junit testsuites properly, right now it maps each case to a testsuite equivilant IIRC. I'm not sure if this would improve performance, but it would certainly make the page more managable to view.

That code is at https://github.com/GoogleCloudPlatform/testgrid/tree/master/cmd/summarizer IIRC ...

**Comment by Rajalakshmi-Girish** [comment]
> > Have seen [#23425 (comment)](https://github.com/kubernetes/test-infra/issues/23425#issuecomment-974524375)
> 
> As far as I know this stands and is going to apply to most any tab with kubernetes unit tests. It can only handle a few columns because there are _so_ many rows in the current implementation.
> 
> Either the number of rows needs to be reduced, or we have to accept less columns.
> 
> Rows could be reduced by changing the kubernetes test output, or by patching testgrid.
> 
> AIUI one possible avenue is updating the component that takes junit in GCS => testgrid to group junit testsuites properly, right now it maps each case to a testsuite equivilant IIRC. I'm not sure if this would improve performance, but it would certainly make the page more managable to view.
> 
> That code is at https://github.com/GoogleCloudPlatform/testgrid/tree/master/cmd/summarizer IIRC ...

/reopen

**Comment by Rajalakshmi-Girish** [comment]
The results of hardly only two days are displayed. Hence reopened this issue.
Must look into the summarizer and make testgrid to group junit testsuites.
Ref comment : https://github.com/kubernetes/test-infra/issues/24779#issuecomment-1006988506
@kishen-v ^^

**Comment by BenTheElder** [comment]
The unit tests report far too many results. I think they have to be consolidated at the source, because actually testgrid is hitting a memory limit here.

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish lets see how other folks are handling this and consolidate the results at the source as Ben mentioned.

**Comment by BenTheElder** [comment]
> @Rajalakshmi-Girish lets see how other folks are handling this and consolidate the results at the source as Ben mentioned.

I don't think anyone is currently, people just aren't inspecting kubernetes unit test results in testgrid in detail
