### ISSUE TITLE
Update value in cluster-api-provider-vsphere secret

### ISSUE THREAD

**Issue by srm09** [kubernetes/test-infra#24788]
**What would you like to be added**:
I would like to update the value for a existing key/value pair in the `clusterapi-provider-vsphere-ci-prow` secret. It is the vCenter URL that needs to be used in tests.

**Why is this needed**:
The path to the vCenter API has been replaced by a private IP address instead of the already existing public DNS route. This needs to be updated in the CI secret used by Prow.

**Comment by cjwagner** [comment]
Secret management in the Prow service cluster and default build cluster is now self service! Please check out the docs here: https://github.com/kubernetes/test-infra/blob/d16a6c88145bc62fafc1fa4bf6d571c46d64bc27/prow/prow_secrets.md#usage-prow-clients
