### ISSUE TITLE
Issue with SSH key on k8s-infra-prow-build cluster for CRI-O nodes

### ISSUE THREAD

**Issue by ehashman** [kubernetes/test-infra#24798]
**What happened**:

Every time we try to run CRI-O tests on the k8s-infra-prow-build cluster, SSH fails. Most recently:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107361/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1479158719756374016/#1:build-log.txt%3A327

```
W0106 18:45:27.531] I0106 18:45:27.530809    6869 ssh.go:120] Running the command ssh, with args: [-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR -i /workspace/.ssh/google_compute_engine core@35.203.133.173 -- sudo sh -c 'systemctl list-units  --type=service  --state=running | grep -e docker -e containerd -e crio']
W0106 18:45:27.942] E0106 18:45:27.942276    6869 ssh.go:123] failed to run SSH command: out: core@35.203.133.173: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
W0106 18:45:27.942] , err: exit status 255 
```

**What you expected to happen**:

Tests should successfully be able to ssh.

**How to reproduce it (as minimally and precisely as possible)**:

We've seen this every time we've tried to migrate CRI-O tests to this cluster, e.g. https://github.com/kubernetes/kubernetes/issues/102624 https://github.com/kubernetes/test-infra/pull/24591

I think there is an issue with the SSH key. We keep working around this by avoiding running CRI-O tests on this cluster. Can someone from SIG Infra help out?

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107361/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1479158719756374016/#1:build-log.txt%3A327

**Anything else we need to know?**:

/sig node k8s-infra

**Comment by BenTheElder** [comment]
SIG k8s-infra are most active in https://github.com/kubernetes/k8s.io where most of the infra is managed.

The ssh key itself shouldn't matter much, with correct setup the key should be added as trusted to the nodes when doing `gcloud compute ssh` as long as the GCP user has permission.

The same key should be used for other GCP ssh jobs, so I would imagine more likely this is an issue with the cri-o VM image not supporting the key agent or something.

**Comment by SergeyKanzhelev** [comment]
cc: @ameukam

**Comment by haircommander** [comment]
from what I can tell this was fixed by https://github.com/kubernetes/test-infra/pull/25080. Can this be closed @ehashman

**Comment by ehashman** [comment]
are we sure? the latest run failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1491479336685932544/

**Comment by haircommander** [comment]
oops, I was looking in the wrong place :upside_down_face:

**Comment by pacoxu** [comment]
Any update on this.

**Comment by ameukam** [comment]
> Any update on this

Still in investigation. we see different modes of failure between cgroupv1 and cgroupv2.

**Comment by haircommander** [comment]
Maybe we need to setup `prow` user on these VMs so fcos behaves more like cos?

**Comment by ehashman** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1499826327681765376/

Still failing :\

**Comment by ehashman** [comment]
Still doesn't appear to be working https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-node-kubelet-serial-crio-cgroupv2/1506314449798041600/

**Comment by saschagrunert** [comment]
> Still doesn't appear to be working https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-node-kubelet-serial-crio-cgroupv2/1506314449798041600/

@ameukam looking at those logs:
- Are `GCE_SSH_PUBLIC_KEY_FILE` (/etc/ssh-key-secret/ssh-public) and `JENKINS_GCE_SSH_PUBLIC_KEY_FILE` (/workspace/.ssh/google_compute_engine.pub) the same?
- Is `/etc/ssh-key-secret/ssh-public` automatically mounted into the GCE machine? Because we copy them in an startup systemd unit: https://github.com/kubernetes/test-infra/blob/657921483a72e4bab9b7478df4552019376750ea/jobs/e2e_node/crio/crio_serial.ign#L24

**Comment by saschagrunert** [comment]
Something like this may work: https://github.com/kubernetes/kubernetes/pull/108909

**Comment by ameukam** [comment]
@saschagrunert can confirm both are identical.

**Comment by ehashman** [comment]
This might get closed by the k/k PR, but we need to still update the cri-o jobs to set the env var.
