### ISSUE TITLE
Filtering meaningful handler executions from metrics in prow plugins

### ISSUE THREAD

**Issue by jmguzik** [kubernetes/test-infra#24832]
**What would you like to be added:**
I would like to have the possibility to optionally eliminate from prow hook plugins metrics (eg for hook  LGTM) the obvious return cases that do not provide much valuable information about the transition made (eg to the GH API).

**Example:**
If the execution lands in the below lines and returns `nil`, success will be reported but no actual job was done by the plugin handler.
https://github.com/kubernetes/test-infra/blob/ff46c2790d6d0f795a5aacaa96ecd307da230605/prow/plugins/lgtm/lgtm.go#L191-L204

I tried first to approach the problem by introducing metrics that will wrap actual transaction work. In the discussed example that would be the function handle:
https://github.com/kubernetes/test-infra/blob/ff46c2790d6d0f795a5aacaa96ecd307da230605/prow/plugins/lgtm/lgtm.go#L207

As @alvaroaleman correctly pointed out in the PR comment https://github.com/kubernetes/test-infra/pull/24825#issuecomment-1008936324 there are existing metrics, but in a different place:
https://github.com/kubernetes/test-infra/blob/0595b59c63b16e0a713d83cb486144032fc41f05/prow/githubeventserver/metrics.go#L35-L44

I would like to use them, but a modification of the interface between hook and plugin handlers would be needed. The plugin handler should inform hook that there was no meaningful work done for the handled case. The easiest way to achieve this would be to filter using a special type of error, which will basically say `NoMeaningfullWork`, instead of `nil`. Probably there are other alternatives to the solution as well.

**Why is this needed**:
Some of our LGTM and/or Approve executions take more than 10 mins. Observing the real transactions (the ones that go to the API at least once) would be a nice way to start working towards the solution. I would like to reuse existing metrics, at least for the histogram and successes/failures, that is why I am proposing the modification.

_**I am assigning only to get a potential opinion.**_
/assign @petr-muller @alvaroaleman @jmguzik

**Comment by petr-muller** [comment]
Adding a motivating example of the problem that we want to address. Let's say we are interested in `lgtm` plugin metrics. The plugin registers for comment events so our metrics suffer from the following:

1. 1000 comments across all PRs, issues etc
2. Only two of them say /lgtm or /lgtm cancel
3. 998 comments get "handled" by just running a  regex against the comment and deciding it is not an interesting comment. 2 comments with /lgtm both get rate limited and take 10 minutes, one of them fails
3. Our metrics say our failure rate is 0.001 and our handlers are very fast, but in reality our failure rate is 0.5 and our handlers are super-slow

**Comment by jmguzik** [comment]
@alvaroaleman would it be OK for you to add a special error type, or you would like to see a different implementation?

**Comment by alvaroaleman** [comment]
The filtering idea makes sense to me but abusing the error return for this does not sound like a good idea to me. An error should indicate that something went wrong, not having had any work to do is not an error.

**Comment by petr-muller** [comment]
I agree that using the error return value is a hack, but has a nice advantage of not needing to change the contract between hook and its plugins. How important is the stability of this interface? Do we need a second set of `RegisterXHandler` methods that would register handlers with different signatures, or is it acceptable to change the signatures of the existing handlers?

I guess the most straightforward solution would be to make the handlers return something like `(didSomethingUseful bool, err error)`. I have some ideas about tracking the GH API token consumption and GH API request rates of handlers, so it could be  reasonably future-proofed by making the return value a struct.

**Comment by jmguzik** [comment]
If the error type is out of scope, I would propose a struct as well, as it could be easily extended in the future.
