### ISSUE TITLE
Tide isn't enforcing GH actions set in the BP config.

### ISSUE THREAD

**Issue by ybettan** [kubernetes/test-infra#24921]
**What happened**:
1. BP config are set to require some GH workflows
2. GH workflow were failing on a PR
3. `lgtm` label was applied
4. `tide` merged the PR regardless of the failing GH workflows

**What you expected to happen**:
PR shouldn't be merged until the jobs are green

**How to reproduce it (as minimally and precisely as possible)**:
1. set a PR to a repo that runs both, Prow jobs and GH workflow
2. set BP config to enforce the GH workflow (I think the Prow jobs are enforced by default if not set as optional)
3. make the PR fail on the GH workflow and pass the Prow jobs
4. apply the `approved` and `lgtm` labels
5. see how tide merges the PR

**Please provide links to example occurrences, if any**:

Prow's BP configuration for the repo:
https://github.com/openshift/release/blob/47e70aee6f4bdf227194a64478c4c4a8c3e9471b/core-services/prow/02_config/openshift-psap/special-resource-operator/_prowconfig.yaml#L11-L12

BP rules from GH repo:
![image](https://user-images.githubusercontent.com/29724509/150113210-d7481164-e3b2-4b9e-8580-9d73b3d1440f.png)

PR check from another PR to show the `required` badge on the jobs:
![image](https://user-images.githubusercontent.com/29724509/150113321-43382286-039c-4451-8b56-6f81f24756c3.png)

The PR that was accidentally merged:
https://github.com/openshift-psap/special-resource-operator/pull/233

**Comment by BenTheElder** [comment]
https://github.com/openshift/release/blob/47e70aee6f4bdf227194a64478c4c4a8c3e9471b/core-services/prow/02_config/openshift-psap/special-resource-operator/_prowconfig.yaml#L11-L12

is missing `from-branch-protection: true` under tide config

/remove-kind bug
/kind support
/area prow
/area prow/tide

https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md

**Comment by petr-muller** [comment]
@BenTheElder we have that as a top-level setting in https://github.com/openshift/release/blob/47e70aee6f4bdf227194a64478c4c4a8c3e9471b/core-services/prow/02_config/_config.yaml#L270

**Comment by BenTheElder** [comment]
/remove-kind support
/kind bug
🙃 

cc @alvaroaleman

**Comment by alvaroaleman** [comment]
Yeah I saw this in Slack but I doubt I will have time to look into this in the near future. Some of the screenshots @ybettan showed in Slack also showed that branchprotection was there, but if that was indeed the case, Tide can not merge, github will just refuse the merge request. So at minimum, this would need a clear repro.

**Comment by ybettan** [comment]
The easiest way to reproduce that I can think of is to:
1. create a PR to [special-resource-operator](https://github.com/openshift-psap/special-resource-operator) which breaks the GH workflow but don't break the prow tests (I can help with that)
2. wait for all the Prow jobs to be green and keep on the GH workflows in red.
3. `lgtm` the PR
4. see how it gets merge
@alvaroaleman

**Comment by sftim** [comment]
#6289 is a related issue because (I think) if Tide were to set its own status and wait for that to pass before a merge was attempted, then you could set up Prow / Tide without an exemption from branch protections.

**Comment by sftim** [comment]
(that's not to disagree with the need for a clearly reproducible issue report)

**Comment by ybettan** [comment]
Just happened again https://github.com/openshift-psap/special-resource-operator/pull/252.

I don't know how to describe a simpler repo than I already did at https://github.com/kubernetes/test-infra/issues/24921#issuecomment-1019461688.

**Comment by ybettan** [comment]
Another wired thing that is happening is that even if the GHA passed and then I `lgtm` then the GHA (that were green a second a go) are marked as `skipped`.

**Comment by chaodaiG** [comment]
Took a quick look at the two occurrences, saw GitHub statuses of both "failed" and "skipped"   for the e2e-test GH action:

- https://github.com/openshift-psap/special-resource-operator/pull/233 
![Screen Shot 2022-09-06 at 8 08 16 AM](https://user-images.githubusercontent.com/45011425/188670953-022efac7-f244-4d5b-aaf9-433eb8bcbced.png)

- https://github.com/openshift-psap/special-resource-operator/pull/252 
![Screen Shot 2022-09-06 at 8 10 19 AM](https://user-images.githubusercontent.com/45011425/188671115-dfe4eee3-9354-4810-96cb-6f55233e8359.png)

I think what happened was that the "skipped" GH action runs were considered "NEUTRAL" by tide https://github.com/kubernetes/test-infra/blob/48ca42ffd12d572234f29e1fa3431455f416cb25/prow/tide/tide.go#L2072-L2074, and tide thinks "NEUTRAL" is equal to "SUCCESS" (which makes sense to me as skipped GH actions should not block). So the question is what caused those "skipped" status? @ybettan

**Comment by sbueringer** [comment]
Not sure if that's the case here, but one thing I observed is that when you have a matrix job strategy and one of the jobs fail the other ones are skipped: https://github.com/kubernetes-sigs/cluster-api/blob/2fb25ef8e337acd7c7efe866c041a7d8b40c2932/.github/workflows/golangci-lint.yml#L16-L19

(not 100% sure if the state is published like that in that case)

**Comment by chaodaiG** [comment]
> Not sure if that's the case here, but one thing I observed is that when you have a matrix job strategy and one of the jobs fail the other ones are skipped: https://github.com/kubernetes-sigs/cluster-api/blob/2fb25ef8e337acd7c7efe866c041a7d8b40c2932/.github/workflows/golangci-lint.yml#L16-L19
> 
> (not 100% sure if the state is published like that in that case)

this feels like to me like the root cause of this bug(tide lists prowjob for the PR, and picks the best results from them), not sure whether this logic also applies to other checks, I can take a further look at the corresponding tide logic later today to confirm.

**Comment by ybettan** [comment]
@chaodaiG Thanks for taking a look. I don't really know why those were skipped.

I think indeed when one of the jobs in the matrix fails, the the others are skipped.

**Comment by sbueringer** [comment]
Here is an example run: https://github.com/kubernetes-sigs/cluster-api/runs/8156194564?check_suite_focus=true

Logs say it is canceled. So really not sure if it's the same.
