### ISSUE TITLE
List of changes in a given build no longer visible

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#25]
I may be mistaken, but I don't see a list of changes that went in the given build. Now I see "No changes." even in weekly enormous-cluster runs (and I have hard time believing that there was no changes in last week).

cc @fejta @ixdy @spxtr @wojtek-t

**Comment by spxtr** [comment]
It still says it in the build job. I'm not sure how it was figuring it out for the e2e jobs, since they may or may not be triggered by a build.

**Comment by ixdy** [comment]
I don't think the e2e jobs ever showed changes. You could somewhat figure it out by looking at which `kubernetes-build` job triggered an e2e job and then see what changes affected each build, but that was (and is) pretty painful.

All that said, we collect the git sha1 for every e2e test run. It might be possible to have gubernator show the list of changes between runs. @rmmh

**Comment by gmarek** [comment]
There were at least a list of builds that went into the giver PR. I'm good with that.

**Comment by ixdy** [comment]
@gmarek http://goto.google.com/k8s-test/job/kubernetes-build/changes still shows a bunch of changes. What am I missing?

**Comment by ixdy** [comment]
enormous-cluster is triggered by a timer, not by builds, so it isn't going to show any builds that went into it. (I don't think it ever has?)

**Comment by gmarek** [comment]
All performance tests are timer-triggered - we changed that recently, but I wasn't aware that when we're triggered by timer we don't have a list of builds. Is there a reason why we can't have it?

**Comment by gmarek** [comment]
cc @lavalamp @roberthbailey

**Comment by spxtr** [comment]
The e2e jobs don't actually check out the git repo, and that "changes" section is generated by the git plugin. I don't know of an easy way to make it happen.

**Comment by lavalamp** [comment]
I think it used to say what builds were used, and that could be used to figure this out.

**Comment by ixdy** [comment]
right, changing the builds to be timer-triggered instead of build-triggered broke this functionality. AFAIK there's no way to get it back without going back to build-triggered.

**Comment by gmarek** [comment]
@ixdy @fejta I don't really know what to do with it. Is it hard to make it work with timer-triggered builds? It's annoying for me - I don't know about others: @wojtek-t @lavalamp @fgrzadkowski

**Comment by spxtr** [comment]
It's a pain to do with Jenkins, but I can make the testgrid have this functionality, where you can click and drag between two builds and it will open all commits between those builds in github. I haven't got this functionality working yet, but I think that's the best solution.

**Comment by gmarek** [comment]
+1

**Comment by lavalamp** [comment]
This seems to have been fixed? Am I crazy?

**Comment by spxtr** [comment]
> This seems to have been fixed? Am I crazy?

I'm not seeing any "recent changes" for e2e jobs.

**Comment by lavalamp** [comment]
Well, to be fair, there haven't been recent changes because the submit
queue hasn't been merging much.

**Comment by spxtr** [comment]
This is done for the testgrid. Click and drag between two columns to get the diff :)
