### ISSUE TITLE
[RFC] Better Handling Support Requests In k/k

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/test-infra#25048]
_Please note that this discussion is intended **only** for issues coming into k/k_

### What Is The Intent/Goal Here?

Setting the context for the "why"
The TL;DR of the intent of doing something like this is: better the experience of when an issue is autoclosed, more info and details below!

#### Current State

There are a non-trivial number of [support issues](https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fsupport) that are opened in k/k, ideally - support issues are to be raised in the [Kubernetes Community Forums](https://discuss.kubernetes.io/), but either due to less visibility or lack of awareness that the forums exist, these issues are opened in k/k. 

The support issue template in k/k links to the forums after https://github.com/kubernetes/community/issues/5261, but issues are still filed under `kind/bug`.

If opened in k/k, there might be some discussion that might or might not answer the author's query after which the issue continues to remain open. This is where the triage bot comes into play. If the author's query _was_ answered, then after 30 days, `lifecycle rotten` and autoclose occurs, which might not be so bad because the query is answered. But more often than not, the query isn't completely answered, after which autoclosing might cause friction or the author removes the lifecycle labels and the same thing might repeat. Additionally, the bot message being generic for issues/PRs does not provide enough information to the author for what they can do next to better reach out to folks for help.

Please note that these issues don't always stay open, sometimes the author ends up closing them, and some SIGs such as sig-node actively cleanup support requests as part of their triage processes.

#### Proposed Change

When an issue in k/k is marked as `kind/support`:
- The issue is automatically exempted from the issues the triage bot cares about for putting lifecycle labels
- The issue gets a fixed 30 day period after which it will be autoclosed
  - Why not close immediately? 
    - Because some issues might not be support-related at all ([example](https://github.com/kubernetes/kubernetes/issues/107818)), a good way to bring about that realization is to allow the conversation to happen for some amount of time. If within this time, it turns out that the issue might be a bug or a feature request, the label can be removed and the issue then follows the lifecycle of any other issue. 
    - Another reason is that the issue might just get enough support then and there from other folks in the community, and that should be allowed to happen.
- If `sig/foo` labels are applied on the issue that has a `kind/support` label, the bot comments with a link to the K8s slack as well as the relevant sig channels (based on the sig labels that exist) + `#kubernetes-users` along with links to the k/community READMEs for those sigs, so that the author is aware of what the potential next steps could be.
- When autoclosing after 30 days, instead of the generic message of "not enough contributors", we could provide a better-worded message (perhaps the [support template](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example)) with more context and information.

### Prior Work

There have been active discussions around this such as:
- Some of what I've described above has been discussed here: https://github.com/kubernetes/community/issues/5435
- Implementation similar to the bot labeling behavior described above: https://github.com/kubernetes/test-infra/pull/20868
- https://github.com/kubernetes/community/issues/5261

### Misc

This was discussed in the last contribex meeting, meeting notes can be found [here](https://docs.google.com/document/d/1CBz8qV_mD6rbDmTsMuosTOQGRXGhN3d8UrcULUI6Vkw/edit).

---

/cc @ehashman
author of original issue in k/community
/cc @kubernetes/owners 
/cc @jberkus @nimbinatus @parispittman @dims - fyi
/sig contributor-experience
/area github-management
/assign

**Comment by dims** [comment]
I'd support this change. If we can find a way to "move" this somewhere else, it would be great! (also may be we should look more at GH discussions?)

**Comment by jberkus** [comment]
+1 from me

**Comment by BenTheElder** [comment]
Might also be worth considering how to best handle redirecting confused users filing what are essentially really requests for support of various commercial offerings.
