### ISSUE TITLE
Containerd 1.4 ending it's support window, we may need to clean up jobs for it

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/test-infra#25095]
containerd 1.4 [end of life is Feb 3rd](https://github.com/containerd/containerd/blob/main/RELEASES.md#:~:text=February%203%2C%202022%20(Extended))

We will need to clean up jobs testing it as we only test supported versions in upstream.

Jobs:

- https://testgrid.k8s.io/sig-node-containerd#containerd-build-1.4
- https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.4
- https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-features-1.4
- https://testgrid.k8s.io/sig-node-cos#containerd-e2e-cos-1.4

/assign @qiutongs 

@qiutongs can you please take a look at this?

/sig node
/cc @mikebrow @dims @adisky

**Comment by dims** [comment]
yes please!

**Comment by SergeyKanzhelev** [comment]
closed via #25977
