### ISSUE TITLE
Prow issue: Can not set hostNetwork for static Pod to false. This results all static pods get same IP Address, which is misleading

### ISSUE THREAD

**Issue by rakarakhi** [kubernetes/test-infra#25130]
Can not set hostNetwork for static Pod to false. This results all static pods get same IP Address, which is misleading. I have created multiple clusters using kubeadm - all the clusters have same issue.

- As a try, I created backup of /etc/kubernetes/manifests/ folder and then changed all yaml file hostNetwork: false. The entire cluster broke. 
- Even restoring the original manifest folder did not solve the problem
- kubeadm, kubectl and kubelet version v1.19.00
- 
Option: is to use kubeadm reset to recover the cluster. And Kubernetes documentations are also not clear
Intention of choosing lower version is to perform Cluster Upgrade

**Comment by rakarakhi** [comment]
- /sig cluster-lifecycle

**Note: Ideally there should be a group for cluster provisioning tools - KubeAdm, Kops etc..**

**Comment by BenTheElder** [comment]
> Note: Ideally there should be a group for cluster provisioning tools - KubeAdm, Kops etc..

That's what sig cluster-lifecycle is, the list of groups is linked in the comment above:

> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

---

This repo is for the testing tools used by the project. Static pods are out of scope and prow does not manage static pods.

I think you should file an issue with https://github.com/kubernetes/kubeadm instead.
