### ISSUE TITLE
`github_token_usage` is not specific to rate limit scope

### ISSUE THREAD

**Issue by timebertt** [kubernetes/test-infra#25177]
/kind bug
/area metrics
/sig testing

**What happened**:

In our prow installation, we don't have as many github API calls. When our `triage-robot` jobs run (similar to [ci-k8s-triage-robot-close](https://github.com/kubernetes/test-infra/blob/baf109d9cfa315f1c5a20d669857e7719b0efa43/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-contribex-k8s-triage-robot.yaml#L93-L145)), they consume a few rate limit tokens from the search API rate limit for finding issues.
Note that the github search API has a custom rate limit of 30 requests per minute, which is different from the core API rate limit. See https://docs.github.com/en/rest/reference/search#rate-limit

The `github_token_usage` metric is updated on each call with the remaining available rate limit tokens from the `X-RateLimit-Remaining` header value, see https://github.com/kubernetes/test-infra/blob/806e6d5370b4f5699306ac9e78988f67fc13aa34/ghproxy/ghmetrics/ghmetrics.go#L108

If the jobs don't find any issues to comment on, the metrics jump to almost zero (i.e., the remaining tokens out of 30), which triggers alerts:
<img width="1455" alt="Screen Shot 2022-02-09 at 12 10 02" src="https://user-images.githubusercontent.com/46341950/153186830-a439b347-b397-4b56-88ba-aa45af83f9d8.png">

However, if the jobs find issues to comment on and do some `core` API calls, the metrics "stays up":
<img width="1443" alt="Screen Shot 2022-02-09 at 12 11 50" src="https://user-images.githubusercontent.com/46341950/153186978-824af834-0ace-424d-bf25-fc544229c799.png">

The root cause of this behavior is that the `github_token_usage` metric is not partitioned by the rate limit scope, i.e. does not consider the `x-ratelimit-resource` header.

**What you expected to happen**:

It should be possible to limit alerts on `github_token_usage` to a given rate limit scope, e.g. `core`.
Alerts for rate limits on the `search` API don't make any sense because the rate limit is reset every minute. Prow users rather want define metrics explicitly on the `core` API.

**How to reproduce it (as minimally and precisely as possible)**:

- run the `commenter` utility with a query, that doesn't find any issues (and hence does not comment on any issue) and use a personal access token for the job
- observe that the metric will "jump" to almost zero

**Please provide links to example occurrences, if any**:

We see, that this also happens on prow.k8s.io. But in this case, no alerts will be fired, as there are many requests to the core API in a short timeframe to "overwrite" the remaining rate limit tokens for the search queries.
For example, see https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?panelId=7&fullscreen&orgId=1&from=1644341863043&to=1644349912732&var-login=k8s-ci-robot&var-path=%2Forganizations%2F:orgId%2Fmembers&var-status=304&var-user_agent=cherrypicker&var-range=30m

<img width="1527" alt="Screen Shot 2022-02-09 at 12 19 24" src="https://user-images.githubusercontent.com/46341950/153189825-09dcad74-71c8-43a0-b50a-43a2ebc26a92.png">

**Anything else we need to know?**:

**Comment by timebertt** [comment]
cc @oliver-goetz

**Comment by cjwagner** [comment]
Thanks for finding the root cause of this, Tim!

**Comment by timebertt** [comment]
This is fixed by https://github.com/kubernetes/test-infra/pull/25702
/close
