### ISSUE TITLE
Document Approvers Mechanism

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2519]
We need to explain how the reviewers and approvers mechanism works.

Lots of things have been changed since the original implementations, but we should cover things like:

- OWNERS files (what's in them)
- blunderbuss and the mungebot (how reviewers get assigned)
- lgtm label, the `/lgtm` command and its effect on merging
- the approval mechanism; per file basis
- (approval-handler.go) approved label, the `/approve` command and its effect on merging

@crimsonfaith91

**Comment by crimsonfaith91** [comment]
Thanks for opening the issue for me. I will work on it based on your original file, and notify you when i complete the first draft. :)

**Comment by crimsonfaith91** [comment]
@grodrigues3 

I plan to include following sections for first draft:
(1) Problems
(2) OWNERS Files: what are the files, their roles
(3) Blunderbuss: high-level overview of algorithms involved in selecting approvers 
(4) LGTM Label: mechanism of /lgtm, effect on merging
(5) Approve Label: mechanism of /approve, effect on merging
(6) Approval Mechanism: a detailed example with steps involved
(7) Implementation Details: high-level overview of codes written for delivering Blunderbuss, /lgtm, and /approve

Is there any additional information that I need to include?

**Comment by grodrigues3** [comment]
Outline looks great.  Only a few comments. 
> (3) Blunderbuss: high-level overview of algorithms involved in selecting approvers
selecting reviewers.  (we have to be careful with the naming)

> (7) Implementation Details: high-level overview of codes written for delivering Blunderbuss, /lgtm, and /approve

Links to the code would probably be a good idea too.

**Comment by crimsonfaith91** [comment]
Having links to the code is a very good idea! With it, I can work on reducing description length to make the section more concise. :)
