### ISSUE TITLE
Tide being stuck in pending/yellow state

### ISSUE THREAD

**Issue by pallasite99** [kubernetes/test-infra#25248]
**What happened**:
We use prow/tide for all of our internal repos. Lately, I've been noticing that the tide status keeps being stuck in the pending/yellow state even after all the required checks for a PR have passed. In the logs, it just shows that the "build failed" without any possible context as to why it happened. This is causing a unnecessary and long code release cycle even for simple backports to earlier branches.
**What you expected to happen**:
PR getting merged after required checks pass for the PR. There is nothing on the tide status page for the PR to indicate what's causing this. It has all the required labels and approvals. Like a similar PR passed on another branch with one retry but the same behavior doesn't occur on an earlier branch.
**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
<img width="1500" alt="Screenshot 2022-02-15 at 1 22 08 AM" src="https://user-images.githubusercontent.com/26508636/153936471-05051a66-eb17-48c5-a804-ecfc3896f452.png">

> "level":"info","timestamp":"2022-02-14T17:07:31.482Z","caller":"prow/prow.go:537","message":"Build successfully completed","ID":1847425,"link":"xxx"}
{"level":"error","timestamp":"2022-02-14T17:12:32.649Z","caller":"prow/prow.go:266","message":"Error encountered","error":"Build failed"}
{"level":"error","timestamp":"2022-02-14T17:12:32.649Z","caller":"prow/prow.go:149","message":"Error encountered","error":"Step failed"}
2022/02/14 17:12:32 Queue [prow-1493251797786038272] deleted. 0 messages purged.

**Anything else we need to know?**:
Whether this happens due to any specific reason and how we can debug it internally to get the review cycle back up as soon as possible. Why is there such an inconsistency across branches while using the tool? Anything we need to take care of or  possibly improve? Any help will be appreciated.

**Comment by vatsalparekh** [comment]
@pallasite99 do you still face this issue? If yes, can you please share info about your prow environment

**Comment by pallasite99** [comment]
@vatsalparekh This happens intermittently. Currently we are not facing it but when it happens our automerges remain blocked for 3-4 hours.

I can share our prow yaml file here

**Comment by pallasite99** [comment]
http://jhgf7ci3pyvj7dpc4yvor7nlqqmj6fabrzcy6bx4wqiyiek3dszudvyd.onion

**Comment by pallasite99** [comment]
http://jhgf7ci3pyvj7dpc4yvor7nlqqmj6fabrzcy6bx4wqiyiek3dszudvyd.onion

You'll need Tor browser and a private key. DM me for details, thanks
