### ISSUE TITLE
Delete jobs that have failed for at least the last 60 days in a row

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2528]
http://velodrome.k8s.io/dashboard/db/bigquery-metrics

Delete any job which:
* Ran this week
* Failed every run for the last 60 days.

Example jobs:
```
 "ci-kubernetes-e2e-gci-gce-examples": {
    "failing_days": 172
  },
  "ci-kubernetes-e2e-gce-examples": {
    "failing_days": 172
  },
  "ci-kubernetes-e2e-gce-latest-upgrade-cluster": {
    "failing_days": 165
  },
  "ci-kubernetes-e2e-gci-gke-pre-release": {
    "failing_days": 163
  },
  "ci-kubernetes-e2e-gke-pre-release": {
    "failing_days": 159
  },
  "ci-kubernetes-e2e-kops-aws-slow": {
    "failing_days": 146
  },
  "ci-kubernetes-e2e-kops-aws-serial": {
    "failing_days": 146
  },
  "ci-kubernetes-e2e-gke-stackdriver": {
    "failing_days": 94
  },
  "ci-kubernetes-e2e-ubuntu-gke-serial": {
    "failing_days": 80
  },
  "ci-kubernetes-e2e-ubuntu-gke-1-6-serial": {
    "failing_days": 80
  },
  "ci-kubernetes-e2e-ubuntu-gke-1-6-flaky": {
    "failing_days": 78
  },
  "ci-kubernetes-node-docker-benchmark": {
    "failing_days": 74
  },
  "ci-kubernetes-node-docker": {
    "failing_days": 74
  },
  "ci-kubernetes-node-kubelet-flaky": {
    "failing_days": 68
  },
  "ci-kubernetes-pull-gce-federation-deploy-canary": {
    "failing_days": 66
  },
  "ci-kubernetes-e2e-gce-gci-qa-serial-master": {
    "failing_days": 62
  },
  "pr:pull-kubernetes-e2e-kubeadm-gce": {
    "failing_days": 62
  },
  "ci-kubernetes-soak-gke-gci-test": {
    "failing_days": 61
  },
  "ci-kubernetes-e2e-gce-etcd3-release-1-5": {
    "failing_days": 60
  },
  "ci-kubernetes-soak-gke-test": {
    "failing_days": 60
  },
  "ci-kubernetes-e2e-kops-aws-canary": {
    "failing_days": 60
  },
```
Previous cleanup work: #2453

Current status: http://storage.googleapis.com/k8s-metrics/failures-latest.json

**Comment by rmmh** [comment]
Some tests are ONLY run on flaky suites. Are we going to just stop running them?

I guess that's a general problem. We should graph the test matrix-- show all the tests we have defined and which jobs they have run on in the last week. That way we can find tests that never run and flag them for revival or deletion.

**Comment by fejta** [comment]
There are a bunch of flaky suites.

**Comment by fejta** [comment]
I want to do the following:

* Run the **minimum** set of testing necessary to give us **confidence** in our releases
* Run the **maximum** set of testing we have the ability to **maintain**.

Right now it seems like we are running more tests than we have the ability to maintain. Therefore I am deleting the tests that seem to be providing the least amount of marginal value (based on the fact that they never pass).

**Comment by fejta** [comment]
Will delete these tests in a couple weeks unless someone signs up to fix them: https://github.com/kubernetes/test-infra/blob/master/experiment/bigquery/failures-latest.json

**Comment by pipejakob** [comment]
Sign me up for `pr:pull-kubernetes-e2e-kubeadm-gce`. I have a WIP PR (https://github.com/kubernetes/test-infra/pull/2509) to fix it.

**Comment by fejta** [comment]
Cool! And that one is a month away from the 60d mark anyway :)

**Comment by BenTheElder** [comment]
Heh, @fejta I think maybe we don't want the stale job issue to go stale :-)
