### ISSUE TITLE
Replace cmd/marque with kube-lego?

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2529]
As noted in https://github.com/kubernetes/test-infra/issues/1792#issuecomment-285127813 and in #1718, `cmd/marque` is a bit of a problem. It hardcodes the URL and my email, and it assumes the secret already exists. This causes increased pain in getting the cluster set up and hinders new users of prow.

I could fix these problems in particular, but we should also consider [kube-lego](https://github.com/jetstack/kube-lego). It still says a requirement is "Non-production use case :laughing:". It has a [chart](https://github.com/kubernetes/charts/tree/master/stable/kube-lego) already, and seems to be widely adopted.

cc @colemickens

**Comment by ixdy** [comment]
and now kube-lego is deprecated. :(
https://github.com/kubernetes/test-infra/issues/6944

**Comment by colemickens** [comment]
Looks like `kube-lego` [is already being used](https://github.com/kubernetes/test-infra/pull/2535). The switch to `cert-manager` is pretty straightforward. I'm getting `prow` setup again for my personal cluster/projects, I'll see how hard it would be to switch instructions/code to use `cert-manager` instead of `kube-lego`.

**Comment by BenTheElder** [comment]
Yes we're using kube-lego pretty much everywhere, I'm in particular
concerned though that this seems to require helm to deploy which requires
you put tiller in your cluster *which itself* is by default insecure unless
you get TLS certs.... [1]

[1] https://docs.helm.sh/using_helm/#initialize-helm-and-install-tiller

**Comment by BenTheElder** [comment]
@munnerz what is the correct secure bootstrapping workflow here?
