### ISSUE TITLE
pull-kubernetes-integration exceeding two hour timeout

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/test-infra#25311]
**What happened**:

The pull-kubernetes-integration failed for cleanup? “Process did not exit before 15m0s grace”.
```
Cleaning up after docker
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
================================================================================
Done cleaning up after docker in docker.
{"component":"entrypoint","file":"prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15m0s grace period","severity":"error","time":"2022-02-16T20:53:22Z"}
{"component":"entrypoint","error":"os: process already finished","file":"prow/entrypoint/run.go:257","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Could not kill process after grace period","severity":"error","time":"2022-02-16T20:53:22Z"}
```

**What you expected to happen**:
pull-kubernetes-integration don't fail for cleanup.

**How to reproduce it (as minimally and precisely as possible)**:
NA

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107705/pull-kubernetes-integration/1494017767307743232

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
> Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.


This part is noise and happens in many jobs, it's fine and not the reason the job is failing, this happens _after_ the job times out, during a separate time limit for jobs to respond to SIGTERM upon reaching the main timeout.

The real problem is further up in the logs:

> {"Time":"2022-02-16T19:13:23.406045468Z","Action":"output","Package":"k8s.io/kubernetes/test/integration/statefulset","Test":"TestStatefulSetAvailable","Output":":map[] OwnerReferences:[{APIVersion:apps/v1 Kind:StatefulSet Name:sts UID:beb32bf3-8fd2-48ed-b9a8-be1978bfd7d5 Controller:0xc007ff28fe BlockOwnerDeletion:0xc007ff28ff}] Finalizers:[] ClusterName: ManagedFields:[]}.\n"}
> {"Time":"2022-02-16T19:13:23.4{"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2022-02-16T20:38:22Z"}

The integration tests took > 2h timeout.

Two hours is meant to be a beyond-reasonable limit for presubmits, 2 hours is absolutely not reasonable for PR testing.

The integration test is taking far too long here.

**Comment by pacoxu** [comment]
Just find it may be dupped with https://github.com/kubernetes/kubernetes/issues/107857

**Comment by BenTheElder** [comment]
let's track in https://github.com/kubernetes/kubernetes/issues/107857 👍 , there's more info and analysis there.
