### ISSUE TITLE
Remove reference to 'scalability' cluster from Prow cluster.

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/test-infra#25350]
**What should be cleaned up or changed**:
Cluster 'scalability' should be removed from Prow instance, as no ProwJobs are scheduled to run on this cluster.

Cluster had problems running simple ProwJobs (golang test) as it seems that there was some kind of key rotation as is now in broken state. This last job was migrated from 'scalability' cluster and it can be safely removed from pool of clusters available to Prow.

/sig k8s-infra
/sig scalability

**Comment by jprzychodzen** [comment]
CC'ing /sig scalability

**Comment by jprzychodzen** [comment]
/remove-lifecycle stale

@spiffxp Could you take a look? I'm not sure what are the exact knobs to remove cluster from the Prow.

**Comment by ameukam** [comment]
@chaodaiG possible for you to help ?

/sig testing
/area prow

**Comment by chaodaiG** [comment]
This is right now a manual process, I'll take care of it and update here.

**Comment by chaodaiG** [comment]
done, things look good so far. The `scalability` cluster is not associated with prow any more
