### ISSUE TITLE
Containerd E2E test fails with failed to load cni during init

### ISSUE THREAD

**Issue by ipochi** [kubernetes/test-infra#25372]
**What happened**:

Two unrelated docker based e2e tests were moved to containerd in separate PRs (https://github.com/kubernetes/test-infra/pull/25254, https://github.com/kubernetes/test-infra/pull/23243). 

Job links : 

https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-gce-e2e-lock-contention
https://k8s-testgrid.appspot.com/sig-node-containerd#node-kubelet-containerd-performance-test

Both the tests are continously failing with the same error mesage:

log snippet from containerd
```
Feb 22 14:31:42 tmp-node-e2e-1026ef4c-cos-89-16108-604-11 containerd[339]: time="2022-02-22T14:31:42.088924479Z"
level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" 
error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"
..
..
..
Feb 22 14:38:41 tmp-node-e2e-1026ef4c-cos-89-16108-604-11 containerd[339]: time="2022-02-22T14:38:41.086102911Z" 
level=info msg="No cni config template is specified, wait for other system components to drop the config."
```

kubelet.log also has the same messages regarding cni plugin not ready
```
I0222 14:38:54.019413    2109 kubelet.go:2323] "Container runtime status" status="Runtime Conditions: RuntimeReady=true reason: message:, NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
E0222 14:38:54.019441    2109 kubelet.go:2326] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
```

**What you expected to happen**:

The test to run successfully.

/cc: @Namanl2001 @adisky @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
what's the diff in test definition with one of the working jobs?

**Comment by ipochi** [comment]
> what's the diff in test definition with one of the working jobs?

What do you mean by test definition ?

**Comment by ipochi** [comment]
one of the tests mentioned here doesn't have 
```
--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/usr/bin/containerd --container-runtime-pid-file=
```

but the other one does yet it fails and it matches the one of the successful tests.

Same is with the name of test: one doesn't contain the prefix `-containerd-`, but other does.

**Comment by adisky** [comment]
@ipochi the CNI init error is resolved now, but tests are still failing and now both the tests have different errors
tracking node performance test here https://github.com/kubernetes/test-infra/issues/25430
tracking lock contention tests here https://github.com/kubernetes/kubernetes/issues/108348

**Comment by ipochi** [comment]
> @ipochi the CNI init error is resolved now, but tests are still failing and now both the tests have different errors
> tracking node performance test here https://github.com/kubernetes/test-infra/issues/25430
> tracking lock contention tests here https://github.com/kubernetes/kubernetes/issues/108348
> 

Hi @adisky 

Looking into it.

**Comment by ipochi** [comment]
https://github.com/kubernetes/kubernetes/issues/108348#issuecomment-1058933790

**Comment by ipochi** [comment]
https://github.com/kubernetes/test-infra/pull/25509

**Comment by pacoxu** [comment]
[kubelet-gce-e2e-lock-contention](https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-gce-e2e-lock-contention) is green now.
[node-kubelet-containerd-performance-test](https://k8s-testgrid.appspot.com/sig-node-containerd#node-kubelet-containerd-performance-test) failed but not for cni not ready
