### ISSUE TITLE
JENKINS_USE_EXISTING_BINARIES not set cwd properly

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#2537]
```
I0419 16:44:50.623] +++ [0419 16:44:50] Docker builds done
I0419 16:45:37.955] +++ [0419 16:45:37] Building tarball: final
I0419 16:45:37.955] +++ [0419 16:45:37] Building tarball: test
I0419 16:46:08.924] make: Leaving directory '/go/src/k8s.io/kubernetes'
W0419 16:46:09.024] 2017/04/19 16:46:08 util.go:131: Step 'make -C /go/src/k8s.io/kubernetes quick-release' finished in 7m58.321890948s
W0419 16:46:09.024] 2017/04/19 16:46:08 main.go:159: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0419 16:46:09.024] 2017/04/19 16:46:08 main.go:193: Something went wrong: called from invalid working directory: must run from kubernetes directory root: /workspace
W0419 16:46:09.025] +(/workspace/e2e-runner.sh:1): main(): chmod -R o+r /workspace/_artifacts
```

We used to `cd kubernetes`, i.e. https://github.com/kubernetes/test-infra/blob/a49cd103add1b312ee2b34405f5ba2a1d805e72c/jenkins/e2e-image/e2e-runner.sh#L402, seems we want to at least keep the behavior in JENKINS_USE_LOCAL_BINARIES case?

/assign @fejta 

cc @yguo0905

**Comment by fejta** [comment]
/assign @krzyzacy 

What command was used here? Please reassign to me with that info.

**Comment by krzyzacy** [comment]
anything uses [JENKINS_USE_LOCAL_BINARIES](https://github.com/kubernetes/test-infra/blob/5a7a07eb22801e4277333d719f998beeafe382da/jenkins/e2e-image/e2e-runner.sh#L83), it was a local job and probably already changed, but it can be reproduced by `--build` and `JENKINS_USE_LOCAL_BINARIES=y` in the job env.

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/blob/master/jobs/pull-kubernetes-e2e.env#L6 sets `JENKINS_USE_LOCAL_BINARIES=y` and this is used by all our PR jobs: https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L310

/unassign

Please give a more concrete example of a complete log, especially the kubetest command. A context-free snippet is not enough to debug.

I suspect that you're either not passing a --build or --extract=local command to kubetest.

Please `/assign` back to me if you still think there's something to fix, otherwise please close

**Comment by krzyzacy** [comment]
whoops @fejta I name the issue wrong, it was `JENKINS_USE_EXISTING_BINARIES`

`JENKINS_USE_EXISTING_BINARIES ` will not set the `--extract` flag in kubetest and try to use the existing binary after the `--build` flag

**Comment by krzyzacy** [comment]
/assign @fejta 

I think it's still a valid issue, the context is, for example, change `JENKINS_USE_LOCAL_BINARIES` to `JENKINS_USE_EXISTING_BINARIES` in [pull-kubernetes-e2e.env](https://github.com/kubernetes/test-infra/blob/master/jobs/pull-kubernetes-e2e.env#L6) and run any pull job locally without `--stage` flag.

Or we can retire the `JENKINS_USE_EXISTING_BINARIES` flag

**Comment by krzyzacy** [comment]
we are getting rid all those envs as well as e2e-runner.sh, so, meh
