### ISSUE TITLE
node-kubelet-containerd-performance-test failing on cos 89 

### ISSUE THREAD

**Issue by adisky** [kubernetes/test-infra#25430]
/sig node

**What happened**:
node-kubelet-containerd-performance-test failing on cos 89 
![image](https://user-images.githubusercontent.com/7712693/155667876-31725932-c385-4c56-b3f3-056a8c3ba5c7.png)

**What you expected to happen**:
Test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test

**Anything else we need to know?**:
This job is recently enabled on containerd 
https://github.com/kubernetes/test-infra/pull/25254

This is passing on Ubuntu

**Comment by Namanl2001** [comment]
> This is passing on Ubuntu

@adisky I observed that tests are getting skipped on ubnutu and eventually showing the success message, this can be confirmed from the [build logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-performance-test/1509717064682573824/build-log.txt)

```
ensure environment has enough CPU + Memory to run
Skipping Node Performance Tests due to lack of CPU. Required {{15 0} {<nil>} 15 DecimalSI} is less than capacity {{1 0} {<nil>} 1 DecimalSI}.
```

**Comment by Namanl2001** [comment]
@adisky on seeing the containerd logs (for both ubuntu and cos) it looks like cni plugin is not getting initialized 

ubuntu logs: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-performance-test/1511891723289104384/artifacts/n1-standard-16-ubuntu-gke-2004-1-20-v20210401-954fa4be/containerd.log

```
Apr 07 02:23:59 n1-standard-16-ubuntu-gke-2004-1-20-v20210401-954fa4be containerd[985]: time="2022-04-07T02:23:59.843081490Z" level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"
```

cos logs: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-performance-test/1511891723289104384/artifacts/n1-standard-16-cos-89-16108-604-31-75344b85/containerd.log

```
Apr 07 02:23:49 n1-standard-16-cos-89-16108-604-31-75344b85 containerd[516]: time="2022-04-07T02:23:49.250870137Z" level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"
```

I looked into the jobs config again but my 👀 are not able to find out anything odd 😅 
Help needed! Thanks 🤗

**Comment by SergeyKanzhelev** [comment]
btw, neither lock contention nor performance tests load CNI. Lock contention test work just because it doesn't ned CNI

**Comment by SergeyKanzhelev** [comment]
containerd-installation.log log is empty for both and not empty for other containerd jobs.

**Comment by SergeyKanzhelev** [comment]
in fact the same behavior is on other tests using these image files. This one works though: `/usr/local/google/home/skanzhelev/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/containerd-master/image-config.yaml`

init.yaml in test-infra seems to be old and may not even work.
