### ISSUE TITLE
Sanity check prow jobs

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2544]
/assign @spxtr 

Everything should define an --upload flag
Presubmits should use a --pull flag
config.json uses --mode=local

**Comment by fejta** [comment]
I think this may exist now?

**Comment by kargakis** [comment]
Can we make sure that the spec and the pullrefs field specifically is validated correctly? I want to avoid handling stuff like trailing commas elsewhere.

**Comment by krzyzacy** [comment]
I think :this-is-fine: now, our presubmit should catch all invalid prow configs
