### ISSUE TITLE
Peribolos latest image missing peribolos binary

### ISSUE THREAD

**Issue by harshad16** [kubernetes/test-infra#25440]
**What happened**:
Peribolos latest images seem to be broken.
`gcr.io/k8s-prow/peribolos:latest` 
tag: [f4aaa30e61b4](https://console.cloud.google.com/gcr/images/k8s-prow/global/peribolos@sha256:f4aaa30e61b4bfe7691792a57cab5e493ddd16a6a33e72efd2506683e9a3ecd7/details)

The image is erroring out by stating `/peribolos: not found`

```
/peribolos --config-path github-config.yaml --github-token-path /etc/github/oauth '--min-admins=[2](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_common/71/peribolos/1497321133840535552#1:build-log.txt%3A2)' '--maximum-removal-delta=0.15' '--require-self=true' --fix-org --fix-org-members --fix-repos --fix-teams --fix-team-members --fix-team-repos --allow-repo-archival
/bin/sh: /peribolos: not found
```

**What you expected to happen**:

Peribolos binary to be available in the image. 

**How to reproduce it (as minimally and precisely as possible)**:

Execute dry run wth peribolos latest image

**Please provide links to example occurrences, if any**:

https://github.com/operate-first/common/pull/71#issuecomment-1051284913
https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_common/71/peribolos/1497321133840535552

**Anything else we need to know?**:
Nope

**Comment by alvaroaleman** [comment]
@harshad16 the location of the binaries changed, see https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md?plain=1#L195

**Comment by harshad16** [comment]
Thank you @alvaroaleman 
Next time , i will make sure read the announcements before opening an issue :sweat_smile:
