### ISSUE TITLE
The deprecated list-team-members API will be removed by GitHub recently.

### ISSUE THREAD

**Issue by Mini256** [kubernetes/test-infra#25457]
**What happened**:

The deprecated list-team-members API will be removed recently.

https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/

**What you expected to happen**:

We need to update the list-team-members API:

https://github.com/kubernetes/test-infra/blob/master/prow/github/client.go#L3713

Affect plugins:

- [ ] [milestonestatus](https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/prow/plugins/milestonestatus/milestonestatus.go#L50)
- [ ] [milestone](https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/prow/plugins/milestone/milestone.go#L49)
- [ ] [override](https://github.com/kubernetes/test-infra/blob/c341b223083a7e5766be99620eba58cc3c8142f1/prow/plugins/override/override.go#L56)
- [ ] [peribolos](https://github.com/kubernetes/test-infra/blob/ee1e7c845bb25177944bb5de37545f007f529059/prow/cmd/peribolos/main.go#L219)
- [ ] [lgtm](https://github.com/kubernetes/test-infra/blob/4c6ee84840fa491b35be39d96d1cbb6bf8a7f824/prow/plugins/lgtm/lgtm.go#L138)
- [ ] [project](https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/prow/plugins/project/project.go#L59)

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by petr-muller** [comment]
Looking at our code, we'll need to adapt to the new interface, the existing signatures won't fly. Most of our client methods take (team) `id int`  and `org string` as parameters which does not have a direct analogy in the replacement API, so I think we should

1) Add the new set of methods that accept `teamSlug string` instead of `id`, using the `/orgs/:org/teams/:team_slug` API ( `RemoveTeamSlugRepo(teamSlug, org, repo string)` for `RemoveTeamRepo(id int, org, repo string)`)
2) Make the old methods temorarily, with a warning, `GetOrg`, read the id and use the `/organizations/:org_id/team/:team_id` API. This will hit GH API one more time over the current state but that should not be too big issue with ghproxy and we can eventually remove these methods after a deprecation period.

**Comment by smg247** [comment]
I'm going to take a swing at this one

**Comment by ericvn** [comment]
When trying to rerun a job from the Istio prow dashboard: https://prow.istio.io/?repo=istio%2Frelease-builder I end up seeing a message like:
```
Error checking if user can trigger job: GitHub failed to fetch members of team &{3281401 Maintainers maintainers Maintainers of the Istio project. closed pull}: return code not 2XX: 404 Not Found
```
I assume that is expected during the brownout and should be fixed with this issue.

**Comment by petr-muller** [comment]
@ericvn yes, getting 404s is consistent with what we saw

**Comment by ericvn** [comment]
Things are back today post their brownout. Hoping things will be fixed before their next one: March 8th.

**Comment by smg247** [comment]
This shouldn't have been closed yet. That was just the initial part, there are still other methods that need to be updated.

**Comment by ericvn** [comment]
Not sure this is directly related as it's failing after the brownout:
```
{"component":"unset","file":"/tmp/test-infra/prow/cmd/peribolos/main.go:215","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure istio members: status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","severity":"fatal","time":"2022-03-03T18:52:59Z"}
```

**Comment by smg247** [comment]
@ericvn it could be related to my change from yesterday, can you link me to the log that you see that in?

**Comment by ericvn** [comment]
@smg247 Actually, I'm now thinking it might be that we are using a really old test-infra commit in the build-tools container we have. I'm going to see about using a more recent version.  But, logs are here: https://storage.googleapis.com/istio-prow/logs/sync-org_community_postsubmit/1499457709760581632/build-log.txt

**Comment by smg247** [comment]
Okay, a tell tale sign that it _might_ be something with my recent change would be seeing:
`{"client":"github","component":"unset","file":"/home/prow/go/src/github.com/kubernetes/org/_output/tmp/test-infra/prow/github/client.go:3717","func":"k8s.io/test-infra/prow/github.(*client).ListTeamMembers","level":"warning","methodName":"ListTeamMembers","msg":"method is deprecated, and will result in multiple api calls to achieve result","severity":"warning","time":"2022-03-03T18:47:43Z"}`
in the logs. I don't see that in your logs, however.

Also, https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-org-peribolos/1499456183784706048 is passing.

**Comment by alvaroaleman** [comment]
SIdenote, they paused the sunset: https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/

**Comment by smg247** [comment]
Once https://github.com/kubernetes/test-infra/pull/25585 is merged everything will be done here except for the `project` plugin. This will be a more involved update as it will require a configuration update to include the slug. I am going to file an issue for that specifically as it is not something that I will be tackling.
