### ISSUE TITLE
test-infra-fuzz is always failing

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#25549]
Seemingly for various reasons:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/test-infra-fuzz/1501245940206407680#

https://testgrid.k8s.io/sig-testing-misc#test-infra-fuzz

/assign @mpherman2

**Comment by mpherman2** [comment]
Yea this job is running as an example of fuzz testing in action. It is failing because it is catching an example bug :)
