### ISSUE TITLE
kettle metrics are failing to upload because they are too old

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#25548]
Since around Feb 26/27: https://testgrid.k8s.io/sig-testing-misc#metrics-kettle&width=5

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/metrics-kettle/1501245940172853248#

/assign @BenTheElder

**Comment by BenTheElder** [comment]
not sure if related we noticed that prow history seems to be stale:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce

^shows feb 9th as most recent, but we are still running continuously, e.g. a result from today via testgrid:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1501283451163119616

testgrid: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default

**Comment by BenTheElder** [comment]
Checked https://console.cloud.google.com/kubernetes/deployment/us-west1-b/g8r/default/kettle/logs?project=k8s-gubernator:

Pod logs for gubernator deployment show it stopped logging `2022-02-6 18:01:50.014 PST`, pod is ready but the process seems to be stuck.

**Comment by BenTheElder** [comment]
Prior to hanging logs include numerous entries of more or less the same error:

> 2022-02-26 18:01:49.916 PST ERROR:root:failed to get tests for pull-cluster-api-provider-aws-build/1491876209225633792
> 2022-02-26 18:01:49.916 PST Traceback (most recent call last): File "make_db.py", line 216, in get_started_finished return WORKER_CLIENT.get_started_finished(job, build) File "make_db.py", line 172, in get_started_finished started = self.get(f'{build_dir}/started.json', as_json=True) File "make_db.py", line 86, in get bucket, prefix = self._parse_uri(path) File "make_db.py", line 80, in _parse_uri raise ValueError("Bad path: %s, should start with 'gs://'" % path) ValueError: Bad path: /started.json, should start with 'gs://'

And then two different entries:
> 2022-02-26 18:01:50.011 PST ERROR:root:Failed to decode request for https://www.googleapis.com/storage/v1/b/kubernetes-jenkins/o/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3194/pull-cluster-api-provider-aws-verify/1492203365331898368/started.json
>
> 2022-02-26 18:01:50.014 PST ERROR:root:Failed to decode request for https://www.googleapis.com/storage/v1/b/kubernetes-jenkins/o/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/3194/pull-cluster-api-provider-aws-verify/1492203365331898368/finished.json

[ no further entries ]

**Comment by BenTheElder** [comment]
Never managed to get useful debug info out of it, but I could see that all processes were in sleep state.

A SIGTERM to the main make_db process has it running again with new builds.

**Comment by BenTheElder** [comment]
https://testgrid.k8s.io/sig-testing-misc#metrics-kettle&width=5 is green again

will open an issue to track long term mitigation.
