### ISSUE TITLE
prow: Allow SIG notification on job failure

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/test-infra#2555]
It would be great if prow supported a mechanism to notify a group of people when a particular job fails. This could be sending an email to a configurable address, or preferably, filing a GitHub issue with a configurable group @-mentioned for visibility. An additional knob for setting the threshold of number of failures before the notification might prove useful, but I personally would rather notice if we had flaky tests that needed to be fixed.

My usecase is this: prow is used for kubeadm's postcommit and periodic end-to-end tests. Rather than relying on a human occasionally checking our testgrid entries to see if anything broke, I would like proactive notification so that someone from the SIG can triage the failure.

This is one of the proposed action items from the [kubeadm 1.6.0 postmortem](https://docs.google.com/document/d/1o-wJ39O8eqBxOCHgu0MGmgH4EdojzI3WlrsV3TVwhe0/edit?usp=sharing).

**Comment by michelle192837** [comment]
So for the two separate suggestions, with regards to TestGrid:

1) Email alerts are something I'll be working on adding in TestGrid (after some other work items), which should allow an email to be sent automatically when tests fail, with some configuration allowed.

2) For an auto-filled GitHub issue (which if I'm reading this correctly, would be auto-filing and tagging a test/config owner when failures occur?), that is being considered but is not a definite thing at the moment.

**Comment by pipejakob** [comment]
Great to hear that some of this work is already planned. And you're right, this doesn't have to be a prow-specific feature, so long as it's compatible with our prow-based jobs.

Is there a separate GitHub issue that this is duplicating for (1) that I should follow instead? And is it worthwhile to file a separate issue to track request (2)? I think email notifications will be a sufficient start, but GitHub issues would make tracking and management of failures much easier, especially if the system deduplicated repeated failures to a single tracking issue.

**Comment by rmmh** [comment]
It seems like the job is failing several times a day: https://k8s-testgrid.appspot.com/misc#kubeadm-gce

Would you want an issue opened for each failed build, or a comment posted on a single issue, or what?

**Comment by pipejakob** [comment]
Thanks for the heads-up on that, I hadn't even noticed the recent failures. It looks like the new flakes are a combination of timeouts and hitting the project quota ceiling (https://github.com/kubernetes/test-infra/pull/2558 opened).

In an ideal world, I would expect to have a single issue opened for the job, regardless of how many repeated failures. On each subsequent failure, the issue's description would be updated with whatever statistics we had about number of failures, percentage of failures over time, etc., so that the only comments on the issue would be made by humans who were discussing/fixing the failures. If someone closed the issue, the next failure would open a new one with all of the metrics reset to only include failures since the new issue had been opened.

Of course, any steps to get us incrementally closer to that direction would be greatly appreciated. I think a simple strategy of "only open an issue if one doesn't seem to be open for this job yet" would be a great initial approximation of the above. A second step might involve our bot automatically closing these issues once the job succeeds X times in a row, but I'm fine with closing them manually to avoid the behavior of people waiting around to see if problems fix themselves instead of aggressively pursuing flakes.

**Comment by michelle192837** [comment]
Good suggestions there, will take into consideration for autobug in future. ^^

In the meanwhile, I don't see an issue opened yet for either email notifications or autobug, so will track it here.

**Comment by luxas** [comment]
@michelle192837 Hi, could you give a short status update? Have you had time to look at this yet?
Thanks for volunteering to do this :)

**Comment by michelle192837** [comment]
Sorry for the delay on this! TestGrid has a newer release now, so I'm working this week on testing it works and hopefully enabling it if there are no weird email issues.

**Comment by luxas** [comment]
Awesome, thanks @michelle192837!
Any plans to include Slack notifications?

**Comment by kargakis** [comment]
Prow now supports a slack plugin, we could possibly enhance it to send notifications on job failures.

**Comment by spxtr** [comment]
That sounds like it will be very annoying.

**Comment by kargakis** [comment]
Yeah, it would be. Still, it would be nice to notify on certain occasions like when a job hasn't passed for some time.

**Comment by luxas** [comment]
I think a Slack integration there would be very helpful. SIGs may opt-in?

**Comment by fejta** [comment]
/area testgrid

I'm inclined to make solve this with testgrid and not prow. IMO is out of scope for prow. Thoughts?

**Comment by luxas** [comment]
@fejta I think I just read somewhere that prow now supports notifying about test failures to Slack...
Did I misunderstand that or...?

**Comment by pipejakob** [comment]
@fejta You're right. The jobs that I care about are run via prow, but so long as this support is added at some level that I can take advantage of, the specifics don't matter. I'll update the issue name/description to reflect that.

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/tree/master/testgrid/config#email-alerts
