### ISSUE TITLE
Tide can't handle OR operator for labels.

### ISSUE THREAD

**Issue by Wojciech-Chilinski** [kubernetes/test-infra#25602]
**What happened**:
According to documentation (https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md#queries) Tide queries should be an exact mapping of GitHub queries. While I'm able to create a GitHub query `label:teamA,teamB` (result is to present PR with label `TeamA` OR `TeamB`), the same tide label definition `- teamA,teamB` results in blocked PR. tide info: `Not mergeable. Needs teamA,teamB label.`

**What you expected to happen**:
Tide should behave exactly like the GitHub query engine.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create PR with label `teamA`
2. Configure tide:
```   tide:
      queries:
      - labels:
        - lgtm
        - approved
        - teamA,teamB
```
3. Check tide status

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
GitHub apis supports OR by using a comma-seperated list? This is new to me, do you have a reference?

**Comment by Wojciech-Chilinski** [comment]
https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-label
Last example
