### ISSUE TITLE
Prow issue: remove priority label if another priority label is added

### ISSUE THREAD

**Issue by xtuchyna** [kubernetes/test-infra#25631]
If e.g. priority `important-soon` is present in Issue, then adding other priority label (e.g. priority `important-longterm`) the old one should be removed, so that the Issue does not have two priority labels simultaneously 

### Example
See https://github.com/thoth-station/thoth-application/issues/1839#issuecomment-1068024066

**Comment by nikhita** [comment]
+1 to do this.

We already have an open issue for it though, so I'll close this one - https://github.com/kubernetes/test-infra/issues/6095

/close
