### ISSUE TITLE
Ability to read parameters with job name ,to utilise the job for testing with parameters

### ISSUE THREAD

**Issue by sumitchauhanJan** [kubernetes/test-infra#25654]
**What would you like to be added**:

We have api tests that are triggered once user comments /test smoke on PR request,but we want to make this job parametrised which will help run these test with some parameter .

E.g /test smoke skip

Here we can utilise skip keyword in our job and take action accordingly.

**Why is this needed**:

This would enable jobs to run on some user based run time condition helping in creating less jobs.

**Comment by sumitchauhanJan** [comment]
./sig api-machinery

**Comment by petr-muller** [comment]
Probably a dup of https://github.com/kubernetes/test-infra/issues/23846
