### ISSUE TITLE
Build gcb-docker-gcloud image failed with "ld-linux-x86-64.so.2: No such file or directory"

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes/test-infra#25698]
**What happened**:
I updated the golang version for gcb-docker-gcloud from 1.16.2 to 1.17.8 recently but I didn't realize that it would make the image build fail. I tried to debug it but cannot figure out. So I hope some expert can help. Thank you!
https://github.com/kubernetes/test-infra/pull/25680

The failure log is like this:
https://storage.googleapis.com/kubernetes-jenkins/logs/post-test-infra-push-gcb-docker-gcloud/1505001904793456640/build-log.txt

It says `Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /google-cloud-sdk/lib/third_party/google/protobuf/pyext/_message.cpython-39-x86_64-linux-gnu.so)`. I exec into the container and found that the lib is at `/lib64/ld-linux-x86-64.so.2`. So I tried `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib64` or directly link it to `/usr/lib`. Now this time it returns error message like:
```
terminate called after throwing an instance of 'std::system_error'
  what():  No error information
Aborted (core dumped)
```

**What you expected to happen**:
Image build works.

**How to reproduce it (as minimally and precisely as possible)**:
docker build the gcb-docker-gcloud image locally.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by lzhecheng** [comment]
@chaodaiG

**Comment by lzhecheng** [comment]
@BenTheElder @detiber could you please take a look?

**Comment by lzhecheng** [comment]
I think the change won't affect other images and old images can still be used. The only problem is that this bug needs to be solved before new image is created. So I haven't reverted the commit.

**Comment by BenTheElder** [comment]
sounds like glibc vs muslc. this change sounds broken. I don't particularly have time to investigate this at the moment, but please don't leave images in a broken state.

**Comment by RedShift1** [comment]
I experienced the same issue, it is due to an update in the Google Cloud SDK. Last version that works for me is 374, you can download it here: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-374.0.0-linux-x86_64.tar.gz

**Comment by BenTheElder** [comment]
https://github.com/GoogleCloudPlatform/cloud-sdk-docker is probably a good starting point to see what is wrong with alpine google-coud-sdk as they have official alpine + sdk images

**Comment by detiber** [comment]
It's been a while since I've done anything with this image, it was used by some of the cluster-api jobs when we originally put it together to facilitate the cluster-api image build jobs in gcb. Not sure if it's still in use. Maybe @dims @cpanato or @fabriziopandini would know?

I could probably dig back into it a bit next week if it's still an issue, though.

**Comment by shanproofpoint** [comment]
I also ran into this issue
Error loading shared library ld-linux-x86-64.so.2

**Comment by lzhecheng** [comment]
@shanproofpoint when did you test? It works now...

Everyone, this bug seems resolved yesterday. 
https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/267
