### ISSUE TITLE
prow shows tests passed even tough a test case failed

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/test-infra#2575]
From http://prow.k8s.io/?type=presubmit

<img width="1371" alt="screen shot 2017-04-25 at 11 35 40 am" src="https://cloud.githubusercontent.com/assets/10199099/25401846/b7b5598a-29ab-11e7-84f3-afdba02fbc62.png">

But looking at the logs, one test failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44139/pull-kubernetes-federation-e2e-gce/2090/.

Prow should hence have showed failed.

cc @kubernetes/test-infra-maintainers @kubernetes/sig-federation-misc @madhusudancs

**Comment by fejta** [comment]
Prow did the correct thing as the job exited with zero. Most likely this is because you asked ginkgo to ignore flakes:

```
I0425 07:15:24.206] GINKGO_TOLERATE_FLAKES=y
...
I0425 07:45:07.512] Test Suite Passed
I0425 07:47:27.527] process 5554 exited with code 0 after 32.1m
I0425 07:47:27.528] PASS: pull-kubernetes-federation-e2e-gce
```

**Comment by spxtr** [comment]
We have an option to retry tests a certain number of times to avoid failing the job if there is a flake. Note that gubernator also shows it as a success. There is a flag to ginkgo, `--flakeAttempts`.
