### ISSUE TITLE
unexpected failure report while all integration tests passed

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/test-infra#25778]
### Which jobs are failing?

Refer to this integration report https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108884/pull-kubernetes-integration/1507912814944063488

Although all the tests passed, but job is failed, I have met this for several times.

### Which tests are failing?

Integration tests.

### Since when has it been failing?

I have no idea.

### Relevant SIG(s)

/sig testing

**Comment by kerthcet** [comment]
> 

Thanks @dims .

**Comment by dims** [comment]
@kerthcet : https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108884/pull-kubernetes-integration/1507912814944063488 should now show the correct number of failures

thanks!

/close

**Comment by dims** [comment]
fixed in https://github.com/kubernetes/test-infra/pull/25786
