### ISSUE TITLE
Gubernator log viewer throws 500 for some tests

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/test-infra#2580]
Haven't seen a pattern but here is one instance where I consistently get 500: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44940/pull-kubernetes-federation-e2e-gce/2186/nodelog?junit=junit_05.xml&wrap=on

May be it is only federation tests because it has so much log data? This is kind of important for us, could someone take a look?

**Comment by krzyzacy** [comment]
`Exceeded soft private memory limit of 256 MB with 371 MB after servicing 73 requests total`

**Comment by madhusudancs** [comment]
How can we fix this?

**Comment by porridge** [comment]
If you need more data points, I'm getting the "Exceeded soft private memory limit" error consistently on https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/19

**Comment by porridge** [comment]
Can we bump the limit a little? This is quite annoying... ([Another example](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/46/))

**Comment by porridge** [comment]
I don't know if it's the same root cause, since the memory message does not appear, but for example https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/68 consistently returns a 500.

**Comment by stevekuznetsov** [comment]
Similar to #6092

**Comment by BenTheElder** [comment]
Soft memory limits are controlled by appengine. The only particularly
feasible way to not throw a trace here is to change appengine settings.
@rmmh any reason we can't increase the limit here?

**Comment by rmmh** [comment]
Those 500s are from listing taking too long.
