### ISSUE TITLE
node version is _ancient_

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#25811]
as a result we're also using a linter that doesn't really exist anymore, we should overhaul this

cc @chaodaiG 

previously we opted not to update due to landing https://github.com/kubernetes/test-infra/issues/23796 first with identical node

**Comment by BenTheElder** [comment]
/help

you can find the node version in run-in-node-container.sh, you'll need to update the version, then make sure the scripts invoking it still work and produce similar output that functions correctly, at minimum this will likely involve switching to a modern typescript linter.

**Comment by xiaoyang-sde** [comment]
Hi Benjamin! I would like to help to upgrade Node to `16.x` and migrate TSLint to ESLint (the details are described in #25896).

**Comment by BenTheElder** [comment]
sorry I've been ~unavailable, please do, you don't need permission to contribute 😅
