### ISSUE TITLE
Show per test consistency data in the test grid

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/test-infra#2581]
This data is already available in various forms in different places such as go.k8s.io/triage, https://github.com/kubernetes/test-infra/tree/master/experiment/bigquery, @fejta's "Top test failures" report to kubernetes-dev, etc. It will be really useful to consolidate this data on the test grid in a visualizable way. Options:
1. Color code the row heading corresponding to each test
2. Print the percentage in parenthesis in the row header
3. Add a separate column for this data.

**Comment by spxtr** [comment]
cc @michelle192837 @krzyzacy

**Comment by fejta** [comment]
Maybe we want to add support for a stats column?

**Comment by madhusudancs** [comment]
That will be useful too.
