### ISSUE TITLE
approve: only repo admin should be allowed to manually add `approved` label

### ISSUE THREAD

**Issue by Ressetkk** [kubernetes/test-infra#25815]
The `approve` plugin allows manual bypass of the approval flow by manually adding the `approved` label. The problem is that bypass can be abused by contributors when I want to enforce the Prow review flow on the repositories where I cannot really revoke the write permissions from the them because they work on feature branches.

Right now the plugin checks assumes that the label manually added by human is valid and approved. While it works when only handful of people has this permission, but if the workflow requires all contributors to have write access then everyone can approve their PRs, because they will be able to add the label as they please.

```go
// IsApproved returns a bool indicating whether the PR is fully approved.
// If a human manually added the approved label, this returns true, ignoring normal approval rules.
func (ap Approvers) IsApproved() bool {
	return ap.RequirementsMet() || ap.ManuallyApproved()
}
```

I looked at the code and identified a field `ManuallyApproved`. It's value is a function that returns true if PR was manually approved by human.
```go
	approversHandler.ManuallyApproved = humanAddedApproved(ghc, log, pr.org, pr.repo, pr.number, hasApprovedLabel)
```
Extending `humanAddedApproved()` looks like a good start. I think adding check if human who manually added the label is in the list of repo admins or(?) in the specific team. If not then the label is removed and the comment is created with contents
```
Only repository administrator can bypass the approval flow.
```

To not break the compatibility an option in the config can be added `bypass_approve_only_admins`. If set to false (default), the flow will be working as it is working right now.

/kind feature
/area prow
/area prow/plugins
/sig testing

**Comment by alvaroaleman** [comment]
@Ressetkk if you can manually apply labels you have write permissions for the repository, which also allows you to simply manually merge PRs, so I don't think this adds anything.

**Comment by alvaroaleman** [comment]
Also, even if we had this, the person could just constantly re-apply the label and the PR will eventually merge, as there is no synchronization between tide and hook and the approval plugin needs time to process the event, which allows for Tide to merge while the event is still being processed.

**Comment by alvaroaleman** [comment]
> Assuming I still want to use OWNERS with repo I cannot really revoke write access, which other ideas I can pick?

Sure you can, the concept of OWNERS files and the approve plugin is geared towards not requiring write access. If you choose to not use that and instead use GitHubs codeowners and that requires write access, there isn't really much Prow can do to help you.
