### ISSUE TITLE
retest not working for github workflow

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes/test-infra#25831]
Cluster API enabled triggering Github actions using retest https://github.com/kubernetes/test-infra/pull/25736 but the functionality doesn't seem to be working. 

**What happened**:
Added /retest comment to a PR with failing github actions. Most of the tests reran, but not the dependabot github workflow: https://github.com/kubernetes-sigs/cluster-api/pull/6357

**What you expected to happen**:
Expected all github workflows to rerun.

**How to reproduce it (as minimally and precisely as possible)**:
We have a PR at https://github.com/kubernetes-sigs/cluster-api/pull/6362 that we're keeping open to reproduce the issue.

**Comment by alvaroaleman** [comment]
What exactly should it have triggered in https://github.com/kubernetes-sigs/cluster-api/pull/6362 but didn't?

/cc @shinigambit

**Comment by killianmuldoon** [comment]
In that case I was expecting it to trigger `.github/workflows/verify.yml` but in other cases it was failing to trigger dependabot actions.

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/pull/24726#issuecomment-1084405644

I'm not sure if anyone is actively working on / using this functionality.

**Comment by killianmuldoon** [comment]
Testing this on https://github.com/kubernetes-sigs/cluster-api/pull/8844

CAPI has three actions here which are all failing on the PR:

1) PR Verify
2) Lint
3) Check markdown links

Currently it looks like `/retest` is working to trigger all three. I just took another look at the original problem, and it looks like it was only the dependabot workflow that wasn't triggered correct. I'll keep that PR open for a while to allow others to run `/retest` against it if they want. I'll have to get a dependabot PR to play with using `/retest` on those actions.
