### ISSUE TITLE
Sidecar should upload its own log

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#25854]
Otherwise, debugging issues with it is pretty hard.

/area prow
/area prow/decoration-utils

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by chaodaiG** [comment]
@alvaroaleman , are you planning to work on this? if not I might get someone to work on it

**Comment by alvaroaleman** [comment]
@chaodaiG not at the moment, feel free to assign it to someone

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/26476
