### ISSUE TITLE
Migrate TSLint (deprecated) to ESLint

### ISSUE THREAD

**Issue by xiaoyang-sde** [kubernetes/test-infra#25896]
**What should be cleaned up or changed**:

- Migrate TSLint to ESLint (TSLint has been [deprecated](https://www.npmjs.com/package/tslint))
  - Convert the rules in `tslint.json` to `eslintrc.js` with [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config)
  - Change TSLint to ESLint in `hack/make-rules/verify/tslint.sh`, `hack/make-rules/verify/all.sh` and `hack/BUILD.bazel` script

**Provide any links for context**:
- Migration guide provided by VS Code: https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration

**Comment by xiaoyang-sde** [comment]
I could help to work on the migration described in this issue.

**Comment by BenTheElder** [comment]
SGTM 👍 
cc @chaodaiG

**Comment by chaodaiG** [comment]
SGTM!

**Comment by boranx** [comment]
/assign 

Hey team :wave: I was looking for a good-first-issue, and came across this. I think I can offer a PR

**Comment by chaodaiG** [comment]
blocked by https://github.com/kubernetes/test-infra/issues/26959
