### ISSUE TITLE
Bootstrap setup_credentials happens after setup_root

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#2589]
This means that failing to pull the repo (in setup_root) means no results will be uploaded. This happens for PRs that have merge conflicts.

**Comment by fejta** [comment]
Any python experts want to work on this? Should be a quick fix!

**Comment by krzyzacy** [comment]
huh? it's more than flip the order of the two calls?

**Comment by fejta** [comment]
Not sure I haven't had the chance to look at it yet, just mentioning in case someone new in the community wants to work on this.

**Comment by fejta** [comment]
If no new community member picks this up I'll get to it eventually
