### ISSUE TITLE
Automatically analyze prow logs using a labeled failure dataset

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#25907]
Do you have a mouse? A human brain? And a desire to improve prow's build log error highlighting? If so then consider helping out!

Follow the instructions here: https://github.com/kubernetes/test-infra/pull/26047#issue-1210317900

Basically:
1) Open failures at https://prow.k8s.io/?state=failure
2) Find the failure, shift-click line numbers to highlight the start and end line that is most interesting
3) Click pin button on highlighted lines
4) ...
5) Profit!

Highlighting a failure can serve as an example of "given this input log, highlight these lines." If we collect some examples, we should be able to train a computer to recognize the patterns and do it for us for future failure logs.

---

People struggle to debug prow failures -- which messages are actual failures versus red herrings is a hard and time-consuming skill to learn.  Ideally we develop ways to bring people's attention to the relevant parts of a failure log as quickly and efficiently as possible.

Prow has two new features that may help in this regard:
1) Highlight and pin a range of log lines - https://github.com/kubernetes/test-infra/pull/25333
2) Request a configured service to choose the lines to highlight before/after load - https://github.com/kubernetes/test-infra/pull/25847

Currently the `buildlog` lens can be configured to focus on lines containing any number of regexes:
https://github.com/kubernetes/test-infra/blob/3ea0e0402f56805f427529b8d8a07c2c5cd68cb9/prow/spyglass/lenses/buildlog/lens.go#L52

And we will default to a minimal list of them:
https://github.com/kubernetes/test-infra/blob/3ea0e0402f56805f427529b8d8a07c2c5cd68cb9/prow/spyglass/lenses/buildlog/lens.go#L95

While this is better than nothing it has not been enormously successful:
1) It tends to produce a lot of false positives -- lots of informational messages, intermittent flakes that retried successfully, etc contain words like `ERROR:` and whatnot. Additionally there is often interesting context on lines before/after the regex match.
2) The list of regexes tends to be static and poorly maintained. Recently I personally went through and pinned a bunch of failures, and while doing so noticed some common patterns and updated the regex list:
https://github.com/kubernetes/test-infra/blob/3ea0e0402f56805f427529b8d8a07c2c5cd68cb9/config/prow/config.yaml#L57-L129
  However prior to a couple months ago this regex list has basically never changed: https://github.com/kubernetes/test-infra/blame/d17d065d917b3f76fbf857560df5d8238568a4d1~1/config/prow/config.yaml#L59-L67

So let's try a couple things:

a) Use the pinning features to develop a database of examples of what part of a failure log is interesting to highlight.
b) Train a natural language model against these examples, in the hopes that it will generalize to future, unseen failures. Use this as the analysis service.

Prow generates [thousands](https://prow.k8s.io/?state=failure) of failures every day. The pinning feature reduces the cost of labeling these failures with the range of lines we are interested in seeing. If we have a sufficient number of labeled examples, we should be able to teach a deep neural network to copy this behavior. Ideally it should generalize to future, unseen examples.

Once we have this dataset, there are a variety of possible types of deep learning architectures to train with. These have different trade-offs in terms of how much ML expertise, resources, training time, etc is required. Once we find one or more that work well, we can deploy it as the highlighting analysis service.

Ideally this creates a positive feedback loop:
1) We can attract/train people interested in applied ML
2) Develop a dataset of failure logs with the correct lines highlighted
3) Train models to identify which lines to highlight

As we increase our ML skills, we can improve our dataset and train increasingly advanced models. Our improved dataset should allow us to focus on increasingly challenging/ambiguous failures, which should attract better ML skills and models. Our improved modeling/training should develop our ML skills and help identify where our dataset needs attention. Continue to repeat this process.

Once we have something that starts to show promise, we can build a service around this model, that implements the highlight request/reponse json that the buildlog lens expects:

https://github.com/kubernetes/test-infra/blob/3bca11b84acfb4f660e20e8aecddbbc360c16706/prow/spyglass/lenses/buildlog/lens.go#L298-L318

Ideally this can become a useful solution that becomes generally accessible to all prow users.

This should hopefully help people find their failures quickly. We can spend less time searching through confusing logs and more time making the world a better place.

/assign

**Comment by Babapool** [comment]
Hi,I would love to help on this issue (I could click things😃). Thanks
