### ISSUE TITLE
Bazel build fails for target //prow/jira/go_default_library

### ISSUE THREAD

**Issue by brianmcarey** [kubernetes/test-infra#25938]
**What happened**:

Bazel build fails for target //prow/jira/go_default_library due to missing input file on latest default branch for test-infra (32d315498b4c813e0235ad4e951269908955618d)

`INFO: Analyzed target //prow/jira:go_default_library (131 packages loaded, 9153 targets configured).`
`INFO: Found 1 target...`
`ERROR: /test-infra/prow/jira/BUILD.bazel:3:11: //prow/jira:go_default_library: missing input file '//prow/jira:fake.go'`

**What you expected to happen**:
Bazel build completes successfully

**How to reproduce it (as minimally and precisely as possible)**:
1. Change to the prow/jira directory 
   `cd test-infra/prow/jira`
2. Run bazel build
   `bazel build go_default_library`

**Please provide links to example occurrences, if any**:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/2029/pull-project-infra-check-testgrid-config/1513815095593930752

**Anything else we need to know?**:
Bazel version 
`bazel --version
bazel 3.4.1
`

**Comment by chaodaiG** [comment]
> /cc @chaodaiG 
> Should we just remove all of bazel? We don't seem to check the build file generation anymore

Yep bazel rules are not relevant anymore, and it's on my backlog to remove all build files.

Now that this repo has been built and tested without bazel for quite a while, I think we are ready for this clean up. I will do it once I'm back in office next week

**Comment by BenTheElder** [comment]
/assign @chaodaiG 
cc

**Comment by chaodaiG** [comment]
Bazel rules are cleaned up from this repo via #26039, this issue is irrelevant any more.
/close
