### ISSUE TITLE
PR Dashboard: PR shows up in both Incoming and Outgoing list

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/test-infra#2594]
This is the PR: https://github.com/kubernetes/kubernetes/pull/44787

it showed at all three list and I "Ack"'ed the need attention one (I believe it didn't even need attention because I was the last one changing it).

**Comment by rmmh** [comment]
It's in your incoming because you self-assigned. I should make those exclusive.

**Comment by rmmh** [comment]
Fixed in #2596
