### ISSUE TITLE
bug: tackle install fails

### ISSUE THREAD

**Issue by RiRa12621** [kubernetes/test-infra#25950]
## Overview

Attempted to follow the tackle installation using the following:

https://github.com/kubernetes/test-infra/blob/83bf07dd99d23a5d6998490ec35240a4be895254/prow/getting_started_deploy.md?plain=1#L46

## Expected
`tackle` installed and ready to use#24882 

## Actual

```
$ go get -u k8s.io/test-infra/prow/cmd/tackle && tackle
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

with `go install`:

```
$ go install k8s.io/test-infra/prow/cmd/tackle@latest
go: downloading k8s.io/test-infra v0.0.0-20220413061046-83bf07dd99d2
go: k8s.io/test-infra/prow/cmd/tackle@latest (in k8s.io/test-infra@v0.0.0-20220413061046-83bf07dd99d2):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by alvaroaleman** [comment]
Yeah that doc is invalid and I am not sure anyone is maintaining tackle today. Feel free to update it and to mention that installing without cloning the repo won't work

**Comment by BenTheElder** [comment]
yeah, you'll need to do `go build` from a clone. it's not clear that this repo will be in a `go get`-able state again anytime soon if ever.

**Comment by RiRa12621** [comment]
@alvaroaleman i'm gonna try to come up with something. just running through a full attempt to capture all possible problems in one go
