### ISSUE TITLE
Add Command To Remove Sig Label

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2595]
For symmetry, if we allow people to add certain labels, we should make sure they can remove those labels as well.

Currently, people can add sig labels by mentioning the sig but they have no way of removing them.

@kubernetes/sig-contributor-experience-misc @fejta

**Comment by idvoretskyi** [comment]
+1. It's a useful enhancement.

**Comment by spiffxp** [comment]
/assign

taking a crack at this

**Comment by grodrigues3** [comment]
@spiffxp you rock!   Ping me on slack or email me directly if you have any questions or get stuck.

**Comment by grodrigues3** [comment]
Note that this is a weird one because we add the sig labels by inferring the sig from something like:

`@ kubernetes/sig-network-misc `

I'm not even sure what the appropriate syntax should be for removing it.  I'm all for symmetry, but anything symmetrical would 1) remention the sig that you are presumably trying to remove 2) probably retrigger an attempt at adding the label

So this may require reimplementation of inferring the label or changing the syntax of the label adding as well.

**Comment by fejta** [comment]
Also I would like to fix @kubernetes/sig-testing-misc to also work when I create the issue :)

**Comment by fejta** [comment]
@kubernetes/sig-contributor-experience-misc

**Comment by grodrigues3** [comment]
@spiffxp as per the google group `[discussion](https://groups.google.com/d/msgid/kubernetes-wg-contribex/CAOU1bzfef0uZU-%3D4K3O9pMh-PcjysGXAyUCqRg5DVb9X_Xwbnw%40mail.gmail.com?utm_medium=email&utm_source=footer)`

Can we also have the bot echo back the mentioned sig (if the commenter is not in the org) so that they receive a notification?

**Comment by kargakis** [comment]
Seems fixed?

**Comment by cblecker** [comment]
Yup, it sure is. Thanks @spiffxp!

/close
