### ISSUE TITLE
Upgrading from v20220416 to v20220418 breaks Spyglass

### ISSUE THREAD

**Issue by oliver-goetz** [kubernetes/test-infra#25998]
/area prow/deck
/area prow/spyglass

**What happened**:
Upgrading from [v20220416 to v20220418](https://github.com/gardener/ci-infra/pull/198) breaks Spyglass. All sections (build log, metadata) are loading forever. Thus, we reverted the update in our prow instance.
The same issue occurs on prow.k8s.io on any prowjob (like [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8s-infra-build-cluster-prow-build/1516348424427933696))

**What you expected to happen**:
Spyglass displaying metadata, build logs etc. 

**How to reproduce it (as minimally and precisely as possible)**:
Ongoing issue on prow.k8s.io

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8s-infra-build-cluster-prow-build/1516348424427933696

**Anything else we need to know?**:
These are log entries from our prow instance.
```
prow/deck-7d4df89cf6-6f2sc[deck]: {"component":"deck","duration":"29.678985ms","file":"k8s.io/test-infra/prow/spyglass/storageartifact_fetcher.go:166","func":"k8s.io/test-infra/prow/spyglass.(*StorageArtifactFetcher).artifacts","level":"info","msg":"Listed 8 artifacts.","severity":"info","time":"2022-04-19T08:57:11Z"}
prow/deck-7d4df89cf6-6f2sc[deck]: {"component":"deck","duration":"22.959587ms","file":"k8s.io/test-infra/prow/spyglass/lenses/common/common.go:235","func":"k8s.io/test-infra/prow/spyglass/lenses/common.FetchArtifacts","level":"info","msg":"Retrieved artifacts for gs/gardener-prow/pr-logs/pull/gardener_gardener/5806/pull-gardener-integration/1516335233065029635","severity":"info","time":"2022-04-19T08:57:11Z"}
prow/deck-7d4df89cf6-6f2sc[deck]: {"component":"deck","duration":"81.019552ms","file":"k8s.io/test-infra/prow/cmd/deck/main.go:1156","func":"main.renderSpyglass","handler":"/view","level":"info","msg":"Rendered spyglass views.","severity":"info","source":"gs/gardener-prow/pr-logs/pull/gardener_gardener/5806/pull-gardener-integration/1516335233065029635","time":"2022-04-19T08:57:11Z"}
prow/deck-7d4df89cf6-6f2sc[deck]: {"component":"deck","duration":"81.989689ms","endpoint":"/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5806/pull-gardener-integration/1516335233065029635","file":"k8s.io/test-infra/prow/cmd/deck/main.go:952","func":"main.handleRequestJobViews.func1","handler":"/view","level":"info","msg":"Loading view completed.","severity":"info","source":"gs/gardener-prow/pr-logs/pull/gardener_gardener/5806/pull-gardener-integration/1516335233065029635","time":"2022-04-19T08:57:11Z"}
prow/deck-7d4df89cf6-6f2sc[deck]: {"component":"deck","file":"k8s.io/test-infra/prow/simplifypath/simplify.go:48","func":"k8s.io/test-infra/prow/simplifypath.(*simplifier).Simplify","level":"debug","msg":"Path not handled. This is a bug, please open an issue against the kubernetes/test-infra repository with this error message.","path":"/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/5806/pull-gardener-integration/1516335233065029635","severity":"debug","time":"2022-04-19T08:57:11Z"}
```

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/compare/2d9ce8514f...9a5c901fc3 per linked PR, most of which are just config changes that wouldn't affect a second prow instance.

**Comment by alvaroaleman** [comment]
Let me manually check if #25969 is the issue. It seems unlikely but who knows

**Comment by fejta** [comment]
> It seems unlikely but who knows

Agree, but downgrading seems to have worked? But maybe that's because I power cycled the pods...

**Comment by fejta** [comment]
Suspect the bump is a red herring, I'm seeing some auth errors in deck, going to revert

**Comment by fejta** [comment]
Going back to v20220418-9a5c901fc3 caused spyglass to hang again, going to 0416 and things are working again. Reverting the deck sorting PR

**Comment by oliver-goetz** [comment]
Deck and Spyglass are working again with the new `v20220419-feb40d908d` builds.
Thanks for helping 😄 

/close
