### ISSUE TITLE
Modify Prow Services to insert `app.kubernetes.io` labels to objects it creates in Kubernetes

### ISSUE THREAD

**Issue by upodroid** [kubernetes/test-infra#26045]
**What would you like to be added**:
I'm rebuilding the [knative prow cluster](https://github.com/knative/test-infra/pull/3271) from scratch and having a hard time figuring out it which objects are created by prow which ones were created by humans.

There are standard labels widely used with Kubernetes to supply more information about k8s objects.

https://kubernetes.io/docs/reference/labels-annotations-taints/#app-kubernetes-io-component

**Why is this needed**:

It is much easier to understand and see which objects are owned/created by prow and which particular prow service is creating it.

**Comment by alvaroaleman** [comment]
Not sure if it is realistic to have this everywhere. You can use `managedFields` through something like [kubectl blame](https://github.com/knight42/kubectl-blame) or maybe even just check if the `kubectl.kubernetes.io/last-applied-configuration` is present if you just want to know "Was this created by kubectl or something else".

**Comment by sftim** [comment]
I like the idea of documenting this as good practice, even if we never 100% achieve that desired state.
