### ISSUE TITLE
Proposal: Standardize Repositories on Creation

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2606]
Great idea suggested by @thockin 

We could use script that creates repositories according some template.  For example:

1. Create the top level OWNERS files and ask how to populate it (reviewers, approvers) on creation
1. Create the repo maintainers
1. Automatically create kubernetes labels: e.g lgtm, approved, sig labels, area labels (may not need to be done depending on [this](https://github.com/kubernetes/test-infra/issues/2504))
1. Create any repo specific teams

Script might look something like
```
$ cd ~/src/kube-repo-tool

$ git fetch upstream && git rebase upstream/master

$ ./add-new-repo
New repo name: foobar
New repo admins (space separated): grod
New repo approvers (space separated): grod
New repo reviewers (space separated): apelisse thockin

Creating repo kubernetes/foobar ... done
Creating team foobar-admins ... done
Adding user grod ... done
Creating team foobar-maintainers ... done
Adding user grod ... done
Creating team foobar-reviewers ... done
Adding user grod ... done
Adding user apelisse ... done
Adding user thockin ... done
Adding to k8s-bot-config ... http://github.com/kubernetes/bot-config/pulls/12345
```

Request for feedback, comments?

**Comment by thockin** [comment]
It would be awesome if a bot was responsible for things like labels, and
all that config lived in github.  Change to config file, merge it, watch
labels get updated.

All I should need to add my repo to the bot is to add one line to a config
file.

**Comment by grodrigues3** [comment]
ContribX has someone working on that now:
https://github.com/kubernetes/test-infra/issues/2504

> All I should need to add my repo to the bot is to add one line to a config
> file.

Our intended implementation will be auto opt-in.  I.e. all repos created will inherit the standard labels by default.  We actually don't have a way to opt-out of this.  Can you imagine cases for repos in the k8s org that wouldn't want the standard subset?  In your repo, you could add labels to the set but you couldn't remove labels from the subset

**Comment by thockin** [comment]
Right now not all repos use the bots.  It's up for debate whether we should
just require it.

**Comment by fejta** [comment]
Is this alive? Is this part of kubernetes/repo-infra?

**Comment by kargakis** [comment]
cc: @stevekuznetsov
