### ISSUE TITLE
Prow issue:

### ISSUE THREAD

**Issue by ChihiroKitada** [kubernetes/test-infra#26073]
The following sample code may not be indented enough?

  - path: /v2
    pathType: Prefix
    backend:
      service:
        name: web2
        port:
          number: 8080

**Comment by BenTheElder** [comment]
> The following sample code may not be indented enough?

what sample code?

**Comment by BenTheElder** [comment]
This repo doesn't contain the substring `name: web2` https://cs.k8s.io/?q=name%3A%20web2&i=nope&files=&excludeFiles=&repos=

I think you've filed an issue with the wrong repo.
