### ISSUE TITLE
push gencred is failing continuously

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#26115]
https://testgrid.k8s.io/sig-testing-images#gencred

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-push-gencred/1518726974250422272

```
Step #0: go: updates to go.mod needed, disabled by -mod=readonly
Finished Step #0
ERROR
ERROR: build step 0 "golang:1.13-alpine" failed: step exited with non-zero status: 1
```

cc @chaodaiG

**Comment by chaodaiG** [comment]
/assign
I'll take a look

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-push-gencred/1519415495839715328

Confirmed green
