### ISSUE TITLE
HMAC reconciler continuously failing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#26116]
https://testgrid.k8s.io/sig-testing-prow#reconcile-hmacs

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-reconcile-hmacs/1519097214905880576

> {"component":"hmac","error":"error getting hmac secret \"hmac-token\": Get \"https://104.198.186.68/api/v1/namespaces/default/secrets/hmac-token\": dial tcp 104.198.186.68:443: i/o timeout","file":"k8s.io/test-infra/prow/cmd/hmac/main.go:142","func":"main.main","level":"fatal","msg":"Error getting the current hmac yaml.","severity":"fatal","time":"2022-04-26T23:33:56Z"}

/sig testing
/area prow

**Comment by cjwagner** [comment]
I've replaced the invalid credentials and the HMAC reconciler is now working again: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-reconcile-hmacs/1521250316111056896
/assign
/close
