### ISSUE TITLE
deck: Path not handled

### ISSUE THREAD

**Issue by hongkailiu** [kubernetes/test-infra#26141]
There are many of those (different paths) in deck's log.

{
	"component": "deck",
	"file": "k8s.io/test-infra/prow/simplifypath/simplify.go:48",
	"func": "k8s.io/test-infra/prow/simplifypath.(*simplifier).Simplify",
	"level": "debug",
	"msg": "Path not handled. This is a bug, please open an issue against the kubernetes/test-infra repository with this error message.",
	"path": "/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-azure-modern/1496462115936931840",
	"severity": "debug",
	"time": "2022-04-28T16:38:01Z"
}

But when I load it on browser, it works fine.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-azure-modern/1496462115936931840

This issue was detected while troubleshooting. Deck was slow to respond. Sometimes the frontend (haproxy) got timeout.
I cannot figure out if the "Path not handled" is the symptom or the cause.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
It means that the path simplifier that we use to remove variable content from paths used in metrics to avoid cardinality explosion doesn't have all paths and needs to be extended: https://github.com/kubernetes/test-infra/blob/59676552d477eec8cb5cc530c57e195833e3dd72/prow/cmd/deck/main.go#L224

**Comment by alvaroaleman** [comment]
Fixed by #26151
/close
