### ISSUE TITLE
Submitting an approve review response should lgtm+approve

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2621]
/cc @cjwagner

**Comment by spiffxp** [comment]
I have a problem with this as long as an approver's PR is implicitly approved.  I don't trust myself, and wouldn't want my PR's to get auto-approve+lgtm'ed without human review.

**Comment by fejta** [comment]
Hmm? This only impacts human reviews.

**Comment by fejta** [comment]
This is about when a human leaves a github review they can set it to one of three states: comment, request changes, approve. 

Right now we do not do anything with these states. We want to treat approve as equivalent to /lgtm and request changes as equivalent to /lgtm cancel

**Comment by spiffxp** [comment]
Totally misunderstood. Makes sense now

**Comment by cjwagner** [comment]
Automatically applying the `lgtm` label in this case makes sense, but the `approved` label cannot be applied until the PR is fully approved by enough OWNERS file `approvers`.
Using reviews to indicate approval from a user would also require the `trigger` plugin to list all reviews on a PR in addition to looking for `/approve` comments which would increase token usage substantially. A similar issue is raised here: https://github.com/kubernetes/test-infra/issues/3827

**Comment by fejta** [comment]
The approve comment is a native github feature. If we have to choose one we should favor the github feature over an `/approve` comment. I suspect we could do both.

I do not agree with you claim about excessive comment usage. It is rare that people add a `/lgtm` `/approve` `APPROVE` comment therefore the impact would be minimal.

**Comment by cjwagner** [comment]
Sorry, you are right, my second claim is totally not true. The `trigger` plugin has nothing to do with the approval process. I was confusing `/approve` with `/ok-to-test` somehow.
The approve plugin actually already lists reviews to look for `/approve` or `/lgtm` comments in them so it won't take any more tokens to make an `APPROVE` review indicate `/approve` from the review author.

The `lgtm` plugin can be updated to handle `pull_request_review` events and add the `lgtm` label where necessary.

Should we make a `CHANGES_REQUESTED` review mean `/approve cancel`, `/lgtm cancel`, or neither?

**Comment by fejta** [comment]
Yes, I would think `/approve cancel` `/lgtm cancel`

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/pull/7504#issuecomment-378030770
