### ISSUE TITLE
1.7 Upgrade Testing Infrastructure

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/test-infra#2625]
One of the takeaways from 1.6 retrospective is we should be setting upgrade testing up right after the last release so that we can catch regressions as they occur. 

The following upgrade tests should run on the master branch, and later 1.7 release branch once the branch is cut (based on https://github.com/kubernetes/test-infra/issues/2034 cc/ @ethernetdan)

### kubectl Skew - Upwards
- [x] `kubernetes-e2e-gce-1.6-master-cvm-kubectl-skew`(GCE)
- [x] `kubernetes-e2e-gce-1.6-master-gci-kubectl-skew` (GCI-GCE)
- [x] `kubernetes-e2e-gke-1.6-master-cvm-kubectl-skew` (GKE)
- [x] `kubernetes-e2e-gke-1.6-master-gci-kubectl-skew` (GCI-GKE)

### kubectl Skew - Downwards
- [x] `kubernetes-e2e-gce-master-1.6-cvm-kubectl-skew` (GCE)
- [x] `kubernetes-e2e-gce-master-1.6-gci-kubectl-skew` (GCI-GCE)
- [x] `kubernetes-e2e-gke-master-1.6-cvm-kubectl-skew` (GKE)
- [x] `kubernetes-e2e-gke-master-1.6-gci-kubectl-skew` (GCI-GKE)

### Upgrade - 1.6 to master
- [x] `kubernetes-e2e-gce-1.6-master-upgrade-cluster` (GCE)
- [x] `kubernetes-e2e-gke-container_vm-1.6-container_vm-master-upgrade-cluster` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.6-gci-master-upgrade-cluster` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.6-gci-master-upgrade-cluster` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.6-container_vm-master-upgrade-cluster` (GCI-GKE → GKE)

### Upgrade - 1.6 to master (New)
- [x] `kubernetes-e2e-gce-1.6-master-upgrade-cluster-new` (GCE)
- [x] `kubernetes-e2e-gke-container_vm-1.6-container_vm-master-upgrade-cluster-new` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.6-gci-master-upgrade-cluster-new` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.6-gci-master-upgrade-cluster-new` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.6-container_vm-master-upgrade-cluster-new` (GCI-GKE → GKE)

### Upgrade - 1.6 to master (Master)
- [x] `kubernetes-e2e-gce-1.6-master-upgrade-master` (GCE)
- [x] `kubernetes-e2e-gke-container_vm-1.6-container_vm-master-upgrade-master` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.6-gci-master-upgrade-master` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.6-gci-master-upgrade-master` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.6-container_vm-master-upgrade-master` (GCI-GKE → GKE)

### Upgrade - 1.5 to master
- [x] `kubernetes-e2e-gke-container_vm-1.5-container_vm-master-upgrade-cluster` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-gci-master-upgrade-cluster` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.5-gci-master-upgrade-cluster` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-container_vm-master-upgrade-cluster` (GCI-GKE → GKE)

### Upgrade - 1.5 to master (New)
- [x] `kubernetes-e2e-gke-container_vm-1.5-container_vm-master-upgrade-cluster-new` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-gci-master-upgrade-cluster-new` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.5-gci-master-upgrade-cluster-new` (GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-container_vm-master-upgrade-cluster-new` (GCI-GKE → GKE)

### Upgrade - 1.5 to master (Master)
- [x] `kubernetes-e2e-gke-container_vm-1.5-container_vm-master-upgrade-master` (GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-gci-master-upgrade-master` (GCI-GKE)
- [x] `kubernetes-e2e-gke-container_vm-1.5-gci-master-upgrade-master`(GKE → GCI-GKE)
- [x] `kubernetes-e2e-gke-gci-1.5-container_vm-master-upgrade-master` (GCI-GKE → GKE)

@krzyzacy I am assigning this to you since you are the Test Infra Lead for 1.7 release.

cc/ @kubernetes/kubernetes-release-managers @monopole upgrade testing lead, @grodrigues3

**Comment by dchen1107** [comment]
@grodrigues3 @calebamiles We should document this somewhere for future releases. Thanks!

**Comment by dchen1107** [comment]
I noticed that @ixdy already created some of tests I listed above. For example, https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.6-master-gci-kubectl-skew

**Comment by calebamiles** [comment]
ack on the need to document, @dchen1107.

**Comment by krzyzacy** [comment]
timeline?

ref https://github.com/kubernetes/features/blob/master/release-1.7/release-1.7.md

**Comment by krzyzacy** [comment]
1.5-master jobs should be fixed and we are having few first results.

@monopole https://k8s-testgrid.appspot.com/1.5-master-upgrade#gke-gci-1-5-cvm-master-upgrade-master is surprisingly green :-)

I'll close this
