### ISSUE TITLE
Prow issue: Bugzilla automation not working for bz due to group

### ISSUE THREAD

**Issue by perdasilva** [kubernetes/test-infra#26317]
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2020484 is in groups redhat and nec
PR: https://github.com/openshift/operator-framework-olm/pull/306
Error: [link](https://github.com/openshift/operator-framework-olm/pull/306#issuecomment-1126004552)

**Comment by perdasilva** [comment]
Anyone? This PR is blocked waiting for the valid-bug label

**Comment by droslean** [comment]
@perdasilva The plugin is working as expected. It seems that your bug is missing the `qe_staff` group.
