### ISSUE TITLE
ListTeamMembers method is deprecated, please use ListTeamMembersBySlug

### ISSUE THREAD

**Issue by chases2** [kubernetes/test-infra#26321]
Prow generates the following warning:

```
jsonPayload: {
...
file: "k8s.io/test-infra/prow/github/client.go:3854"
func: "k8s.io/test-infra/prow/github.(*client).ListTeamMembers"
level: "warning"
methodName: "ListTeamMembers"
msg: "method is deprecated, please use ListTeamMembersBySlug"
...
}
```
https://github.com/kubernetes/test-infra/blob/b1d2443b5af9405c54246ccd7c8fe58b3f21ecae/prow/github/client.go#L3846-L3855 just points to the method, not where the method is used. The message is emitted by the `hook` controller.

**Comment by smg247** [comment]
Could be from one of the usages in this old PR: https://github.com/kubernetes/test-infra/pull/25585

**Comment by chases2** [comment]
This warning is still occurring for some of our instances of Prow. Is there a decommissioning plan for this method?

**Comment by smg247** [comment]
We could get the aforementioned PR merged. There just appears to be no interest.

**Comment by listx** [comment]
I've reopened the PR.

**Comment by listx** [comment]
The PR has been merged.
