### ISSUE TITLE
Unknown field checks are not enabled for ProwJob configuration.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#26368]
**What should be cleaned up or changed**:
Prow's [`checkconfig`](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig) tool is responsible for presubmit validation of ProwJob configuration. It has an optional check for unknown fields in ProwJob config that can be enabled with `--warnings=unknown-fields-all`. We [currently do not have this check enabled](https://github.com/kubernetes/test-infra/blob/c930a1d5f949bb9212078a05442cd39ccaae8cf3/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L64-L71). 
As a result it is possible to add configuration that is not recognized by Prow, causing it to be silently ignored. Common examples of this are typos in a field name and incorrect indentation.

It would be great to enable this check across the repo, but before we can we must address all existing unknown fields.  To identify these problems, `checkconfig` can be run locally from the root of the repo using the following command (please update to a recent image tag):
```sh
docker run -i --rm -v "${PWD}:${PWD}" -w "${PWD}" gcr.io/k8s-prow/checkconfig:v20220518-4571841471 --config-path=config/prow/config.yaml --job-config-path=config/jobs --plugin-config=config/prow/plugins.yaml --strict --warnings=mismatched-tide-lenient --warnings=tide-strict-branch --warnings=needs-ok-to-test --warnings=validate-owners --warnings=missing-trigger --warnings=validate-urls --warnings=unknown-fields --warnings=duplicate-job-refs --warnings=unknown-fields-all
```
This runs checkconfig against the test-infra ProwJob config with all current checks and the additional `unknown-fields-all` check. You will see output like the following that identifies unknown fields until all instances have been fixed or removed:
```json
{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:90","func":"main.reportWarning","level":"warning","msg":"error unmarshaling config/jobs/kubernetes/generated/generated.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"resources\"","severity":"warning","time":"2022-05-19T18:24:57Z"}
{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:93","func":"main.reportWarning","level":"fatal","msg":"Strict is set and there were warnings","severity":"fatal","time":"2022-05-19T18:24:57Z"}
```
When all instances are fixed you will see something like this:
```json
{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:246","func":"main.main","level":"info","msg":"checkconfig passes without any error!","severity":"info","time":"2022-05-19T18:24:32Z"}
```

At that time we can add `- --warnings=unknown-fields-all` to the [presubmit](https://github.com/kubernetes/test-infra/blob/c930a1d5f949bb9212078a05442cd39ccaae8cf3/config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml#L51-L73) and [CI](https://github.com/kubernetes/test-infra/blob/c930a1d5f949bb9212078a05442cd39ccaae8cf3/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L789-L819) `checkconfig` jobs to enable this validation across the repo going forward.

/help-wanted
/good-first-issue
/area prow/checkconfig prow config

**Comment by rajibmitra** [comment]
I just checked with crane - the latest checkconfig image tag as of now - v20220525-90e1ebee08 
cmd used - crane ls gcr.io/k8s-prow/checkconfig

**Comment by asim-reza** [comment]
fix merged... 🎉
