### ISSUE TITLE
Close stale issues as `not-planned` (stale) via Prow Robot

### ISSUE THREAD

**Issue by JohnTitor** [kubernetes/test-infra#26380]
GitHub has added a new option to close issues, we can now choose the `not-planned` state reason for stale issues: https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/
And they said:

> We have added a new state_reason attribute to our REST API, GraphQL API and webhooks. These are currently in preview and will be fully shipped in the upcoming week.

So it should be possible to add this option when closing issues via Prow Robot in the near future.

Maybe it'd also be a good option like `/close not-planned` for duplicate/wont-fix issues.

**What would you like to be added**:

A functionality to close stale issues as `not-planned` (stale) via Prow Robot

**Why is this needed**:

Currently we have the `lifecycle/stale` label but it doesn't mean that filtering by it only shows stale issues, it can contain some resolved issues, e.g., https://github.com/kubernetes/test-infra/issues/24143, https://github.com/kubernetes/kubernetes/issues/108802
Instead, we will be able to filter by `reason:"not planned"`.

**Comment by BenTheElder** [comment]
We'll need consensus from contributor experience for workflow changes, before anyone moves to shipping this.

**Comment by BenTheElder** [comment]
#sig-contribex slack is the best way to get in touch usually, dropped a note.

**Comment by mrbobbytables** [comment]
I like the idea :)

**Comment by endocrimes** [comment]
This would potentially be super useful 👍

**Comment by hakman** [comment]
I like the idea too. Would be nice to go ahead with it as soon as possible to avoid confusion.

**Comment by jberkus** [comment]
+1 from me

**Comment by MadhavJivrajani** [comment]
I've created #26915 to add support for this. Once that is merged, I'll open up a PR to update the command to use `not-planned`, that the bot uses to close `rotten` issues:

https://github.com/kubernetes/test-infra/blob/4f44d233e10e624b912742793cf6548bfee8e10e/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-contribex-k8s-triage-robot.yaml#L173

**Comment by alculquicondor** [comment]
> Maybe it'd also be a good option like `/close not-planned` for duplicate/wont-fix issues.

Was this implemented too?

**Comment by MadhavJivrajani** [comment]
@alculquicondor, not yet.
Happy to bring it up in a future ContribEx meeting and get the ball rolling!

**Comment by alculquicondor** [comment]
That would be great, thanks :)
