### ISSUE TITLE
Can we update the tektoncd-pipeline version to use a more recent version?

### ISSUE THREAD

**Issue by qaifshaikh** [kubernetes/test-infra#26535]
**What would you like to be added**:
Update the tektoncd-pipeline version to use a more recent version?

**Why is this needed**:
Currently only support v0.10.1
While the recent version is v.0.36.x

**Comment by qaifshaikh** [comment]
Looking at the code, there aren't many places where `v1alpha1` is used, only 10. The first thing I wanted to try is to replace the client with `v1beta1` and see what breaks.
https://github.com/kubernetes/test-infra/search?q=TektonV1alpha1Client

**Comment by eddycharly** [comment]
IIRC it was not that simple, I remember I tried to move to v1beta1 and a few things introduced a breaking change. Don’t remember what though.
