### ISSUE TITLE
Support for secondary

### ISSUE THREAD

**Issue by MaxRenaud** [kubernetes/test-infra#26589]
**What would you like to be added**: Split presubmits into primary and secondary execution. An arbitrary ordinal order would also be acceptable.

**Why is this needed**:
When there's a variety of presubmits, it's likely that some tests will be cheap and quick to run while others might use a considerable amount of resources and time. For example, linting code vs e2e testing. 

The current behavior is to run all the tests in parallels, which can be wasteful if a linting issue is discovered and and E2E test runs regardless. Only running the E2E test when the easier tests have passed saves resources.

**How?**:
The simplest way to achieve this would be to add an execution order in the presubmit definition. When all jobs from the same priority pass, prow can then launch the second wave.

**Comment by BenTheElder** [comment]
prow had this, and removed it, it was called `run_after_success` https://github.com/kubernetes/test-infra/issues?q=is%3Aissue+run_after_success+is%3Aclosed

**Comment by MaxRenaud** [comment]
Thanks for the quick reply. I'll ping you 1:1 regarding a Google-specific problem.
