### ISSUE TITLE
Change Container Registry URL for Prow Image Scans

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/test-infra#26599]
**What should be cleaned up or changed**:

This line needs to updated to new URL for container registries: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-security-trusted.yaml#L69 as follows:

### Current

```
curl -Ls https://sbom.k8s.io/$(curl -Ls https://dl.k8s.io/release/latest.txt)/release | grep 'PackageName: k8s.gcr.io/' | awk '{print $2}' > images
```

### Proposed update

```
curl -Ls https://sbom.k8s.io/$(curl -Ls https://dl.k8s.io/release/latest.txt)/release | grep 'PackageName: registry.k8s.io/' | awk '{print $2}' > images

```

**Provide any links for context**:

This is making the prow job fail at the moment: https://testgrid.k8s.io/sig-security-snyk-scan#ci-kubernetes-snyk-master

/sig security
/good-first-issue

**Comment by upodroid** [comment]
/close

Please use these [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in your future PRs to autoclose linked issues.
