### ISSUE TITLE
Switch over to using stored service account credentials

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#266]
Rather than the default service account.

**Comment by wonderfly** [comment]
@fejta Many of GCI jobs started to fail because of the service account change: whatever new account is used needs to be added to the image_project.

What's new account for GCI jobs?

**Comment by ixdy** [comment]
@wonderfly the new account is kubekins@kubernetes-jenkins.iam.gserviceaccount.com.

We should probably use a different account for PR Jenkins, however, as I noted in https://github.com/kubernetes/test-infra/commit/972416fdd936cd8475c168cf9b84b66b0e82300b#commitcomment-18388887.
