### ISSUE TITLE
Ensure `gke-gcloud-auth-plugin` is installed on all images in this repo that ship gcloud SDK

### ISSUE THREAD

**Issue by upodroid** [kubernetes/test-infra#26609]
https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

If you have been using kubectl for GKE clusters recently, you might have seen this:

```
REDACTED  MCW0CDP3YY  ~  Desktop  Git  kn-test-infra   cosign-setup  3+  8⚑  SIGINT  $   k version
W0617 14:43:03.998659   88126 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```

The deprecations in [KEP 541](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/541-external-credential-providers) will take effect in the next release so lets get ahead of it. It will take a while for changes to trickle down to GKE.

Also, some images have been failing to build recently:
- protobuf needs python 3.7 (bigquery)

Initial set of images to fix:
- gcloud-bazel			
- gcloud-in-go
- bigquery #26610 	
- gcb-docker-gcloud #26616 	
- gcloud-terraform		
- kubekins-e2e

/assign
/sig testing
/kind cleanup

**Comment by lucasfcnunes** [comment]
Is this being enforced?
