### ISSUE TITLE
Allow each team control their PodPendingTimeout, PodRunningTimeout, and PodUnscheduledTimeout

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#26614]
**What would you like to be added**:

PodPendingTimeout, PodRunningTimeout, and PodUnscheduledTimeout to be configured differently based on org/repo/cluster.

**Why is this needed**:

These values are configured globally, and might not be most optimal for all teams, adjusting the values of these fields often need to get approvals from lots of stakeholders when the prow instance has many tenants.

One way of doing this, is to add these 3 fields to be part of [DefaultDecorationConfigEntry](https://github.com/kubernetes/test-infra/blob/959d4500863c43efa5cb45b49ba6d14c62441103/prow/config/config.go#L622), which already indexes by orgRepo and/or cluster. The [fuzz test](https://github.com/kubernetes/test-infra/blob/959d4500863c43efa5cb45b49ba6d14c62441103/prow/apis/prowjobs/v1/types_test.go#L325) probably also needs to updated If decided to go down this path

**Comment by chaodaiG** [comment]
@ArkaSaha30 , thank you for the interest, I have updated the issue description with my personal suggestion

**Comment by ArkaSaha30** [comment]
@chaodaiG Thanks a lot for updating the issue with the details. I am a little confused on the [fuzz test](https://github.com/kubernetes/test-infra/blob/959d4500863c43efa5cb45b49ba6d14c62441103/prow/apis/prowjobs/v1/types_test.go#L325) update part. The mentioned fuzz test is specific to the [DecorationConfig](https://github.com/kubernetes/test-infra/blob/959d4500863c43efa5cb45b49ba6d14c62441103/prow/apis/prowjobs/v1/types.go#L417) struct in `types.go`.
So I am trying to understand how we can add fuzz tests for the 3 timeout fields added as a part of [DefaultDecorationConfigEntry](https://github.com/kubernetes/test-infra/blob/959d4500863c43efa5cb45b49ba6d14c62441103/prow/config/config.go#L622) struct in `config.go`. 
Is it to be added in [config_test.go ](https://github.com/kubernetes/test-infra/blob/9799b82ab336876cd29a9afcb99166ffdfbd5d05/prow/config/config_test.go#L4828) ?

**Comment by chaodaiG** [comment]
Sorry I might have skipped one more step, Prow allows setting `DecorationConfig` on both prowjob yaml and prow config yaml, and the values of these two are merged at runtime by [ApplyDefault](https://github.com/kubernetes/test-infra/blob/959d4500863c43efa5cb45b49ba6d14c62441103/prow/apis/prowjobs/v1/types.go#L615) function, so please make sure update this function as well. For the fuzz testing I mainly mean that once the `ApplyDefault` function was updated we'll need to make sure that the fuzz test would not fail.

**Comment by amirrmonfared** [comment]
Hi @ArkaSaha30, are you working on this? If not please assign me.
Thanks a lot

**Comment by ArkaSaha30** [comment]
Hey @amirrmonfared , I got occupied with some other work due to which I could not make much progress with this. Please feel free to work on it.
Thank you.
/assign @amirrmonfared

**Comment by a-berahman** [comment]
Sorry for the back and fourth Pull requests, it was a problem from my local environment and CLA. I will handle it in the next one.

**Comment by lanycrost** [comment]
@a-berahman if you stopped work on this issue, I would like to take it
