### ISSUE TITLE
Update the table of Prometheus metrics collected by Prow

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#26640]
**What would you like to be added**:

https://github.com/kubernetes/test-infra/tree/master/prow/metrics#prometheus-metrics contains the list of Prometheus metrics collected by Prow, which has something but there are many more not listed there.

**Why is this needed**:

Would be nice to provide a full list of metrics that we support so that it's easier to understanding monitoring.

The metrics sent to prometheus are defined with something like `prometheus.NewGaugeVec(` as [pooledprs example](https://github.com/kubernetes/test-infra/blob/89af288344a5c9e2dd4789fd85c86cd35324fab7/prow/tide/tide.go#L222), all other metrics are defined somewhat similar to this syntax, so should be relatively easy to find all.

/help
/good-first-issue

**Comment by Ankit152** [comment]
Hey @chaodaiG! 🙂 
I am new to this repository and very excited to make my first contribution. Would you mind assigning this issue to me?

**Comment by Ankit152** [comment]
Hey @chaodaiG 😄 
I see there are promethues metrics present in the files under `prow/bugzilla`, `prow/cier`, `prow/cmd/exporter`, `prow/cmd/sinker`, `prow/gerrit/adapter`, `prow/gerrit/client`, `prow/github`, `prow/githubserver`, `prow/jenkins`, `prow/jira`, `prow/kube`, `prow/plugins`, `prow/pubsub/subscriber`, `prow/version`.
Should I also add them as well? Just clarifying my doubt before I proceed. 🙂

**Comment by chaodaiG** [comment]
> Hey @chaodaiG 😄 I see there are promethues metrics present in the files under `prow/bugzilla`, `prow/cier`, `prow/cmd/exporter`, `prow/cmd/sinker`, `prow/gerrit/adapter`, `prow/gerrit/client`, `prow/github`, `prow/githubserver`, `prow/jenkins`, `prow/jira`, `prow/kube`, `prow/plugins`, `prow/pubsub/subscriber`, `prow/version`. Should I also add them as well? Just clarifying my doubt before I proceed. 🙂

yeah I think it would be good to include them all

**Comment by Ankit152** [comment]
Added all of them! 🙂
