### ISSUE TITLE
Prow job, especially pull-kubernetes-bazel, seems always fail the first run? 

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#2666]
```
Cloning into 'test-infra'...
fatal: unable to access 'https://github.com/kubernetes/test-infra/': Could not resolve host: github.com
```
Seems not a github issue? Or that's coincide? Worth look at I guess.

/assign @spxtr

**Comment by spxtr** [comment]
I think we hit a rare bug where one of the nodes loses external connectivity but doesn't get kicked. I'll upgrade the nodes and that should fix it.

**Comment by krzyzacy** [comment]
The node is updated and seems fine now, let #2669 track auto upgrade.
