### ISSUE TITLE
Testgrid sometimes shows empty test result

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#2668]
On https://k8s-testgrid.appspot.com/canonical-kubernetes#gce-ubuntu, we don't get test results for run [333](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ubuntu/333), [309](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ubuntu/309), [308](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ubuntu/308). Take run 333 for example, it only says the build is still running but it's a previous run, and its [log bucket](https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ubuntu/333) only contains `started.json`. This happens periodically and it happens for other tests as well.

I don't have access to the prow logs. Any ideas why there're the empty results?

**Comment by yguo0905** [comment]
@fejta @krzyzacy

**Comment by fejta** [comment]
Most likely it timed out.

**Comment by ixdy** [comment]
It looks like something is wrong with prow. Lots of failures on http://prow.k8s.io/?type=periodic&job=ci-kubernetes-e2e-gce-ubuntu, things like

http://prow.k8s.io/log?pod=ci-kubernetes-e2e-gce-ubuntu-340
```
Log not found: response has status "400 Bad Request" and body "{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"ci-kubernetes-e2e-gce-ubuntu-340-0\" in pod \"ci-kubernetes-e2e-gce-ubuntu-340\" is not available","reason":"BadRequest","code":400}
"
```

and
http://prow.k8s.io/log?pod=ci-kubernetes-e2e-gce-ubuntu-341
```
Cloning into 'test-infra'...
fatal: unable to access 'https://github.com/kubernetes/test-infra/': Could not resolve host: github.com
```

**Comment by yguo0905** [comment]
Successful runs like [343](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ubuntu/343) and [342](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-ubuntu/342) took 22 minutes, while the timeout is set to 50 minutes in [job config](https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gce-ubuntu.env#L13) and [prow config](https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L958), so a timeout indicated an error either in test or prow who runs the tests. Is there a way to check the prow logs?

**Comment by yguo0905** [comment]
@ixdy, thanks. The failed 341 run is not shown in testgrid.

**Comment by ixdy** [comment]
@spxtr is upgrading the prow cluster to the latest Kubernetes release, which we expect to fix the issue.

**Comment by krzyzacy** [comment]
ref https://github.com/kubernetes/test-infra/issues/2666#issuecomment-299534904

**Comment by krzyzacy** [comment]
it's #2708, I'll close this one.
