### ISSUE TITLE
Add IBM Cloud resources to Boskos

### ISSUE THREAD

**Issue by Amulyam24** [kubernetes/test-infra#26717]
**What would you like to be added**:
We would like to add a few IBM Cloud resources to the Boskos resource pool

**Why is this needed**:
The resources would be used by projects in Kubernetes-sigs(cluster-api-provider-ibmcloud)

More context: 
We are looking for help in understanding these two areas: 

- Secret Manager(KES or ESO)
- Any ideas or recommended ways to update user data of the new boskos resources?

**Comment by Amulyam24** [comment]
We are planning to manage the secret used by the IBM Cloud janitor via the GCP Secret manager depicted in the overall flow below.
![Boskosflow-2](https://user-images.githubusercontent.com/30797554/179198673-248081cd-3b7b-45f9-b8f0-eadd5f098f8f.png)

We might need access to the Secret manager service in one of the projects being used for IBM Cloud related K8s upstream work.
Looking for suggestions on the same or let us know if there's a better way to handle this.

**Comment by BenTheElder** [comment]
I'm not involve with running prow on the google side [or any of the other test-infra anymore](https://twitter.com/BenTheElder/status/1551670320423059456?s=20&t=QoVdcIl14kJ_PA1_AmsdMA), but there's some docs for managing prow secrets with secret manager in this repo:

https://github.com/kubernetes/test-infra/blob/d16a6c88145bc62fafc1fa4bf6d571c46d64bc27/prow/prow_secrets.md


I have no idea what projects cluster API uses, I imagine someone who works on that project would know best.

----

With my SIG K8s Infra hat on: We strongly encourage donating resources through the CNCF for use by the project and managing them within the community. 

Past efforts with resources managed internally at a company leave poorly documented infrastructure with no community capacity to fix things, exacerbated by employee turnover.

SIG K8s Infra can probably advise more on how to manage that.

**Comment by Amulyam24** [comment]
> With my SIG K8s Infra hat on: We strongly encourage donating resources through the CNCF for use by the project and managing them within the community.
> 
> Past efforts with resources managed internally at a company leave poorly documented infrastructure with no community capacity to fix things, exacerbated by employee turnover.
> 
> SIG K8s Infra can probably advise more on how to manage that.

Hi @BenTheElder, thank you for the insights. Yes, we would like to know more on this, in terms of what is the process involved in donating resources to CNCF and on how they will be managed.

**Comment by BenTheElder** [comment]
> Yes, we would like to know more on this, in terms of what is the process involved in donating resources to CNCF and on how they will be managed.

For the donation process you'll have to talk to the CNCF, for how they'll be managed as Kubernetes project resources that's between you, the CNCF, and SIG k8s Infra, but boskos is one example of tooling we use for this. Most of the other infra management is in https://github.com/kubernetes/k8s.io cc @ameukam @dims (chairs)

**Comment by ameukam** [comment]
> > Yes, we would like to know more on this, in terms of what is the process involved in donating resources to CNCF and on how they will be managed.
> 
> For the donation process you'll have to talk to the CNCF, for how they'll be managed as Kubernetes project resources that's between you, the CNCF, and SIG k8s Infra, but boskos is one example of tooling we use for this. Most of the other infra management is in https://github.com/kubernetes/k8s.io cc @ameukam @dims (chairs)


@Amulyam24 For resources donation, please take a look at https://cncf.io/credits.

**Comment by ameukam** [comment]
cc @jeefy @hh please, can you provide guidance for resources donation to @Amulyam24 ? Thanks!

**Comment by hh** [comment]
We don't have IBM credit donations yet, but let me look into it.

**Comment by BenTheElder** [comment]
I don't think we should be extending boskos without resources, as-is boskos is basically in maintenance mode and barely staffed by anyone. We can figure out how to manage resources once we have them?
