### ISSUE TITLE
Recent changes broke loading of deck

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/test-infra#26868]
Some commit in 1211ccbc68..c85a2ec6dc broke deck for all Istio (prow.istio.io) pages.

We see the page load, but the logs/junit section is stuck spinning. Console:

![2022-07-20_08-52-31](https://user-images.githubusercontent.com/623453/180027928-d3519835-6abc-4a96-bd87-006e04b79178.png)

Deck logs show things like:
```
{
  "component": "deck",
  "file": "k8s.io/test-infra/prow/simplifypath/simplify.go:48",
  "func": "k8s.io/test-infra/prow/simplifypath.(*simplifier).Simplify",
  "level": "debug",
  "msg": "Path not handled. This is a bug, please open an issue against the kubernetes/test-infra repository with this error message.",
  "path": "/view/gs/istio-prow/pr-logs/pull/istio_istio/16602/integ-security-local-presubmit-tests-master/5395",
  "severity": "debug",
  "time": "2022-07-20T15:06:00Z"
}

```

although similar logs seem to appear after rollback as well.

**Comment by BenTheElder** [comment]
IIRC this was fixed? There was a race in the JS build, cc @chaodaiG

**Comment by chaodaiG** [comment]
yes it was fixed by https://github.com/kubernetes/test-infra/pull/26902

tracking issue: #26345

/close
