### ISSUE TITLE
prow: event json unmarshall fails

### ISSUE THREAD

**Issue by jfelten** [kubernetes/test-infra#2688]
I built prow into a helm chart and deployed it to a GKE cluster by modifying the prow/cluster settings.  It uses kube-lego to manage ssl certs.  Github events get posted to hook and receive a 200 response.  Hook fails to unmarshall the json payload (Issue Comments) with the following error:

{"error":"invalid character 'p' looking for beginning of value","level":"error","msg":"Error parsing event.","time":"2017-05-09T04:15:21Z"}

This error seems to be at test-infra/prow/cmd/hook/server.go line 87, but no events can be unmarshalled - not just issue comments.  These types of errors seem to be be tricky to debug, and I'm hoping someone may have encountered this before.

Request From github:
Headers
Request URL: https://prow.cnct.io/hook
Request method: POST
content-type: application/x-www-form-urlencoded
Expect: 
User-Agent: GitHub-Hookshot/0878b99
X-GitHub-Delivery: 1dda9280-346e-11e7-94a2-c1e4cebb8188
X-GitHub-Event: issue_comment
X-Hub-Signature: sha1=5a806a0de4c019dfb9d82c1c5431787732e3f292

Payload:
{
  "action": "created",
  "issue": {
    "url": "https://api.github.com/repos/samsung-cnct/prow-chart/issues/7",
    "repository_url": "https://api.github.com/repos/samsung-cnct/prow-chart",
    "labels_url": "https://api.github.com/repos/samsung-cnct/prow-chart/issues/7/labels{/name}",
    "comments_url": "https://api.github.com/repos/samsung-cnct/prow-chart/issues/7/comments",
    "events_url": "https://api.github.com/repos/samsung-cnct/prow-chart/issues/7/events",
    "html_url": "https://github.com/samsung-cnct/prow-chart/pull/7",
    "id": 227212764,
    "number": 7,
    "title": "test PR",
    "user": {
      "login": "samsungbot",
      "id": 27736568,
      "avatar_url": "https://avatars3.githubusercontent.com/u/27736568?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/samsungbot",
      "html_url": "https://github.com/samsungbot",
      "followers_url": "https://api.github.com/users/samsungbot/followers",
      "following_url": "https://api.github.com/users/samsungbot/following{/other_user}",
      "gists_url": "https://api.github.com/users/samsungbot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/samsungbot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/samsungbot/subscriptions",
      "organizations_url": "https://api.github.com/users/samsungbot/orgs",
      "repos_url": "https://api.github.com/users/samsungbot/repos",
      "events_url": "https://api.github.com/users/samsungbot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/samsungbot/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 5,
    "created_at": "2017-05-09T00:25:23Z",
    "updated_at": "2017-05-09T04:15:21Z",
    "closed_at": null,
    "pull_request": {
      "url": "https://api.github.com/repos/samsung-cnct/prow-chart/pulls/7",
      "html_url": "https://github.com/samsung-cnct/prow-chart/pull/7",
      "diff_url": "https://github.com/samsung-cnct/prow-chart/pull/7.diff",
      "patch_url": "https://github.com/samsung-cnct/prow-chart/pull/7.patch"
    },
    "body": ""
  },
  "comment": {
    "url": "https://api.github.com/repos/samsung-cnct/prow-chart/issues/comments/300056831",
    "html_url": "https://github.com/samsung-cnct/prow-chart/pull/7#issuecomment-300056831",
    "issue_url": "https://api.github.com/repos/samsung-cnct/prow-chart/issues/7",
    "id": 300056831,
    "user": {
      "login": "samsungbot",
      "id": 27736568,
      "avatar_url": "https://avatars3.githubusercontent.com/u/27736568?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/samsungbot",
      "html_url": "https://github.com/samsungbot",
      "followers_url": "https://api.github.com/users/samsungbot/followers",
      "following_url": "https://api.github.com/users/samsungbot/following{/other_user}",
      "gists_url": "https://api.github.com/users/samsungbot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/samsungbot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/samsungbot/subscriptions",
      "organizations_url": "https://api.github.com/users/samsungbot/orgs",
      "repos_url": "https://api.github.com/users/samsungbot/repos",
      "events_url": "https://api.github.com/users/samsungbot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/samsungbot/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-09T04:15:21Z",
    "updated_at": "2017-05-09T04:15:21Z",
    "body": "/assign jfelten\r\n"
  },
  "repository": {
    "id": 85747197,
    "name": "prow-chart",
    "full_name": "samsung-cnct/prow-chart",
    "owner": {
      "login": "samsung-cnct",
      "id": 11511065,
      "avatar_url": "https://avatars0.githubusercontent.com/u/11511065?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/samsung-cnct",
      "html_url": "https://github.com/samsung-cnct",
      "followers_url": "https://api.github.com/users/samsung-cnct/followers",
      "following_url": "https://api.github.com/users/samsung-cnct/following{/other_user}",
      "gists_url": "https://api.github.com/users/samsung-cnct/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/samsung-cnct/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/samsung-cnct/subscriptions",
      "organizations_url": "https://api.github.com/users/samsung-cnct/orgs",
      "repos_url": "https://api.github.com/users/samsung-cnct/repos",
      "events_url": "https://api.github.com/users/samsung-cnct/events{/privacy}",
      "received_events_url": "https://api.github.com/users/samsung-cnct/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": true,
    "html_url": "https://github.com/samsung-cnct/prow-chart",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/samsung-cnct/prow-chart",
    "forks_url": "https://api.github.com/repos/samsung-cnct/prow-chart/forks",
    "keys_url": "https://api.github.com/repos/samsung-cnct/prow-chart/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/samsung-cnct/prow-chart/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/samsung-cnct/prow-chart/teams",
    "hooks_url": "https://api.github.com/repos/samsung-cnct/prow-chart/hooks",
    "issue_events_url": "https://api.github.com/repos/samsung-cnct/prow-chart/issues/events{/number}",
    "events_url": "https://api.github.com/repos/samsung-cnct/prow-chart/events",
    "assignees_url": "https://api.github.com/repos/samsung-cnct/prow-chart/assignees{/user}",
    "branches_url": "https://api.github.com/repos/samsung-cnct/prow-chart/branches{/branch}",
    "tags_url": "https://api.github.com/repos/samsung-cnct/prow-chart/tags",
    "blobs_url": "https://api.github.com/repos/samsung-cnct/prow-chart/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/samsung-cnct/prow-chart/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/samsung-cnct/prow-chart/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/samsung-cnct/prow-chart/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/samsung-cnct/prow-chart/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/samsung-cnct/prow-chart/languages",
    "stargazers_url": "https://api.github.com/repos/samsung-cnct/prow-chart/stargazers",
    "contributors_url": "https://api.github.com/repos/samsung-cnct/prow-chart/contributors",
    "subscribers_url": "https://api.github.com/repos/samsung-cnct/prow-chart/subscribers",
    "subscription_url": "https://api.github.com/repos/samsung-cnct/prow-chart/subscription",
    "commits_url": "https://api.github.com/repos/samsung-cnct/prow-chart/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/samsung-cnct/prow-chart/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/samsung-cnct/prow-chart/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/samsung-cnct/prow-chart/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/samsung-cnct/prow-chart/contents/{+path}",
    "compare_url": "https://api.github.com/repos/samsung-cnct/prow-chart/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/samsung-cnct/prow-chart/merges",
    "archive_url": "https://api.github.com/repos/samsung-cnct/prow-chart/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/samsung-cnct/prow-chart/downloads",
    "issues_url": "https://api.github.com/repos/samsung-cnct/prow-chart/issues{/number}",
    "pulls_url": "https://api.github.com/repos/samsung-cnct/prow-chart/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/samsung-cnct/prow-chart/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/samsung-cnct/prow-chart/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/samsung-cnct/prow-chart/labels{/name}",
    "releases_url": "https://api.github.com/repos/samsung-cnct/prow-chart/releases{/id}",
    "deployments_url": "https://api.github.com/repos/samsung-cnct/prow-chart/deployments",
    "created_at": "2017-03-21T19:57:59Z",
    "updated_at": "2017-04-28T21:32:05Z",
    "pushed_at": "2017-05-09T00:25:24Z",
    "git_url": "git://github.com/samsung-cnct/prow-chart.git",
    "ssh_url": "git@github.com:samsung-cnct/prow-chart.git",
    "clone_url": "https://github.com/samsung-cnct/prow-chart.git",
    "svn_url": "https://github.com/samsung-cnct/prow-chart",
    "homepage": null,
    "size": 34,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Smarty",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1,
    "mirror_url": null,
    "open_issues_count": 1,
    "forks": 1,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "master"
  },
  "organization": {
    "login": "samsung-cnct",
    "id": 11511065,
    "url": "https://api.github.com/orgs/samsung-cnct",
    "repos_url": "https://api.github.com/orgs/samsung-cnct/repos",
    "events_url": "https://api.github.com/orgs/samsung-cnct/events",
    "hooks_url": "https://api.github.com/orgs/samsung-cnct/hooks",
    "issues_url": "https://api.github.com/orgs/samsung-cnct/issues",
    "members_url": "https://api.github.com/orgs/samsung-cnct/members{/member}",
    "public_members_url": "https://api.github.com/orgs/samsung-cnct/public_members{/member}",
    "avatar_url": "https://avatars0.githubusercontent.com/u/11511065?v=3",
    "description": "Samsung SDS Cloud Native Computing Team"
  },
  "sender": {
    "login": "samsungbot",
    "id": 27736568,
    "avatar_url": "https://avatars3.githubusercontent.com/u/27736568?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/samsungbot",
    "html_url": "https://github.com/samsungbot",
    "followers_url": "https://api.github.com/users/samsungbot/followers",
    "following_url": "https://api.github.com/users/samsungbot/following{/other_user}",
    "gists_url": "https://api.github.com/users/samsungbot/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/samsungbot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/samsungbot/subscriptions",
    "organizations_url": "https://api.github.com/users/samsungbot/orgs",
    "repos_url": "https://api.github.com/users/samsungbot/repos",
    "events_url": "https://api.github.com/users/samsungbot/events{/privacy}",
    "received_events_url": "https://api.github.com/users/samsungbot/received_events",
    "type": "User",
    "site_admin": false
  }
}

Response:
Headers
Alt-Svc: clear
Content-Length: 32
Content-Type: text/plain; charset=utf-8
Date: Tue, 09 May 2017 04:15:21 GMT
Via: 1.1 google

Body
Event received. Have a nice day.

**Comment by spxtr** [comment]
`content-type: application/x-www-form-urlencoded`

Try switching the webhook to send `application/json` instead. This is an option in the webhook settings.

**Comment by spxtr** [comment]
If that doesn't work, you can use `cmd/phony` to send example webhooks to your service as described under [How to test prow](https://github.com/kubernetes/test-infra/blob/cf2e25f1de32c99eba7f0054fb99e3b49a9e8a06/prow/README.md).

**Comment by jfelten** [comment]
Switching to application/json fixed it. - thanks for the help.
