### ISSUE TITLE
there should be a command to rerun GKE smoke tests only

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#269]
Moving here from kubernetes/contrib#1322

cc @fejta @ixdy

**Comment by eparis** [comment]
Any chance we can get some consistency in the names/retest triggers?
`Jenkins GKE smoke e2e ` should be `GKE smoke e2e test this` ? Something obvious?

| Jenkins Name        | Retest Command  |
| ------------- | ------------- |
|  Jenkins GCE Node e2e | gce node e2e test this |
| Jenkins GCE e2e | gce e2e test this |
| Jenkins GKE smoke e2e | gke smoke e2e test this |
| Jenkins unit/integration | unit test this |
| Jenkins verification | verification test this |

Should we drop the 'e2e' altogether?

| Jenkins Name        | Retest Command  |
| ------------- | ------------- |
|  Jenkins GCE Node e2e | gce node test this |
| Jenkins GCE e2e | gce test this |
| Jenkins GKE smoke e2e | gke smoke test this |
| Jenkins unit/integration | unit test this |
| Jenkins verification | verification test this |

What does 'smoke' really mean? Should it be in there at all? Should we re-name the status's? I'm hoping for some rationalization here...

**Comment by spxtr** [comment]
k8s-bot gke test this has worked for a while.
