### ISSUE TITLE
skipping nameprefix of some resource kinds 

### ISSUE THREAD

**Issue by hiteshgakhreja1234** [kubernetes/test-infra#26917]
Hi All

is it possible to have kustomization file avoid adding prefixes to few resources

service
configmap
storageclass

I tried using this link but this is not working
https://stackoverflow.com/questions/69882949/kustomize-namesuffix-skip-on-some-resources

I tried creating a configuration file in kustomize and try skip: true but still its not behaving as expected
hgakhrej@C02G104NMD6M configuration % cat kustomizeconfig/skip-secrets-prefix.yaml
namePrefix:

path: metadata/name
kind: Configmap
skip: true
path: metadata/name
apiVersion: v1
kind: Service
skip: true
I tried below example also but no luck
https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0519#preparation-step-resource0

Can anybody provide me some working example for this or any kind of workaround

**Comment by BenTheElder** [comment]
This issue is out of scope for this repo, I think you may want https://github.com/kubernetes-sigs/kustomize/issues
