### ISSUE TITLE
Add owners: [] list to config.json

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2696]
/cc @mtaufen 

We want every jobs in [config.json](jobs/config.json) to include a `"owners": ["sig-foo", "sig-bar"]` list.

Let's start by:
* Adding a `sig-UNCLAIMED` entry to each job
* Adding a unit test that validates that every job contains an `owners` key, and that only existing jobs use `sig-UNCLAIMED`.
* Send out mail asking each sig to go through the list of jobs, marking ones relevant to their sig.
* Delete any unclaimed jobs.

**Comment by fejta** [comment]
After we get this in we can work on infrastructure to automatically generate dashboards for each sig.

**Comment by mtaufen** [comment]
Should we call the field `sig-owners`, for future proofing?

We can just consider any job with the field omitted or left empty as unclaimed.

Do you want to add the test, since you probably understand the plumbing here far better than I do? I can handle reaching out to sigs once we have that.

**Comment by mtaufen** [comment]
One other thing we can do is list unclaimed jobs in your regular flaky test emails, people seem to be reading these so that might be a quick way to get attention on this.

**Comment by mtaufen** [comment]
https://github.com/kubernetes/test-infra/pull/2755

**Comment by mtaufen** [comment]
Remaining:
- send mail
- delete unclaimed jobs

I'll wait until just after the code freeze starts to do the first, people are probably too busy right now to audit their jobs.

**Comment by fejta** [comment]
There's work planned to move all jobs to shared jobs by sig

**Comment by BenTheElder** [comment]
This happened I believe, all jobs should have a sig owner now.
/close
