### ISSUE TITLE
pylint all files

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#2697]
See [`verify/verify-pylint.sh`](https://github.com/kubernetes/test-infra/blob/b737f83adf49261e90e16ed91ffcf1515a290133/verify/verify-pylint.sh). Run with [`bazel test //verify:verify-pylint`](https://github.com/kubernetes/test-infra/blob/b737f83adf49261e90e16ed91ffcf1515a290133/verify/BUILD#L32-L40).

**Comment by krzyzacy** [comment]
/assign
I would say mainly bootstrap_test.py...

**Comment by krzyzacy** [comment]
/unassign @michelle192837 
/assign @rmmh 

I'll clean up mungegithub, Ryan wanna clean up kettle?

**Comment by rmmh** [comment]
kettle cleanup is part of #2870

**Comment by BenTheElder** [comment]
Looks like the current status is everything except gubernator and mungegithub?
https://github.com/kubernetes/test-infra/blob/2dba2cb65ad7a34c3bcb6d2f12b26e0ab2f742fb/verify/verify-pylint.sh

**Comment by krzyzacy** [comment]
mostly https://github.com/kubernetes/test-infra/blob/2dba2cb65ad7a34c3bcb6d2f12b26e0ab2f742fb/mungegithub/issue-labeler/simple_app.py, I'm just lazy.

gubernator has it's own lint rule and run in a different test

**Comment by BenTheElder** [comment]
@krzyzacy so if I fix mungegithub's lints we can close this?

**Comment by krzyzacy** [comment]
yep
