### ISSUE TITLE
Move tooling to consume ginkgo json output instead of junit

### ISSUE THREAD

**Issue by aojea** [kubernetes/test-infra#26996]
> I appreciate that your downstream tooling can't handle all the information in the default JUnit file.  in part this is due to the (unfortunate) reality that the JUnit spec is fairly anemic and doesn't have a lot of rich structure.
> 
> With that said, I actually think you _do_ want to preserve all that additional information.  Consider, for a specific example, the flake we recently looked at in #111086 - some of the key pieces of information there were these 
> 
> ```
> 03:45:47.846: INFO: error deleting namespace csi-mock-volumes-6183: timed out waiting for the condition
> ```
> 
> info logs that were attached to _passing_ specs.
> 
> More broadly, my sense is that a complex integration test suite like the e2e suite can be super hard to debug - especially when running in parallel and having the potential for two running specs to have an unforeseen impact on each other.  Having information in an accessible format that will allow you to find correlations and extract clues for where to look next is important.
> 
> The JUnit format isn't great for that - especially if the tooling built on top of it simply can't handle the amount of data being generated.  So I'd recommend the following:
> 
> - keep just the truncated JUnit file that you've generated.  The use-case for this file is to populate downstream tooling and allow users to quickly understand if a suite failed and to get information about just the failing specs.
> - use ginkgo's `json-report` format to save an archive of the entire test run.  This will have a ton of detailed information.  The use-case here is to provide the possibility to dive deeper into the suite for debugging purposes.
> 
> Over time I could imagine building your own custom tooling/heuristics no top of the JSON format (e.g. something that detects whether or not there is an elevated rate of non-failing errors; or something that detects whether or not individual specs are taking longer to run than usual).
> 
> _Originally posted by @onsi in https://github.com/kubernetes/kubernetes/issues/111627#issuecomment-1202687756_

**Comment by aojea** [comment]
@chendave @pohly @BenTheElder @onsi 

I think that the principal consumers of the junit output are in this repo, but I'm not very familiar with them

**Comment by pohly** [comment]
We need a "why do want to do this", i.e. some specific use case that can be done with the JSON output and not with JUnit.

**Comment by aojea** [comment]
now that you mention it,  and after checking the kubernetes repo, the problem that we have is that junit is the standard output for all the test suites, not only e2e/ginkgo, integration and unit are being processed to junit ... if the json output is not standard , we can't unify all the tests suites :/

Maybe the json is great if we want to build new tools to help on debugging the e2e, but it seems hard to change current tooling
