### ISSUE TITLE
Monitoring for prow

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2699]
We need monitoring to ensure that periodic, presubmit, postsubmit jobs are running as specified.

**Comment by spxtr** [comment]
I played around with prometheus and it was pretty nice. Maybe something to look into once I'm back, but if someone wants to tackle in the next two weeks then feel free.

**Comment by kargakis** [comment]
https://github.com/kubernetes/test-infra/pull/4280 is a good start.

**Comment by kargakis** [comment]
I am interested in seeing the following metrics:
- number of total prowjobs
- number of prowjobs in every state
- number of call outs to jenkins per sync
- number of call outs to github per sync

All of the above metrics need to be exposed by plank and/or jenkins-operator. 

@Q-Lee

**Comment by kargakis** [comment]
More precisely

> number of call outs to jenkins per sync
> number of call outs to github per sync

Number of succeeded and failed calls per sync

**Comment by spiffxp** [comment]
fyi @stevekuznetsov since you mentioned an interest in prow healthchecks during today's sig-testing meeting

**Comment by stevekuznetsov** [comment]
Yep, we're tracking here and in some of the linked issues

**Comment by krzyzacy** [comment]
Add to the thread: I'm working on some plugin stats in https://github.com/kubernetes/test-infra/pull/5028

**Comment by kargakis** [comment]
Merged a basic set of metrics for the jenkins operator in https://github.com/kubernetes/test-infra/pull/5424 - exposing in https://github.com/kubernetes/test-infra/pull/5337

**Comment by kargakis** [comment]
More metrics added in https://github.com/kubernetes/test-infra/pull/5670

**Comment by kargakis** [comment]
I also just deployed a basic set of alerts to start with: https://github.com/openshift/release/pull/448

**Comment by fejta** [comment]
Where do we graph prow metrics? Velodrome?

**Comment by stevekuznetsov** [comment]
Right now we are using a Graphana deployment on our cluster, not sure these have been published on a dashboard on Velodrome yet but I'd image the config is the same? @karataliu

**Comment by stevekuznetsov** [comment]
@kargakis

**Comment by kargakis** [comment]
We don't use Grafana yet, reminds me that I need to put down a card about
creating a prow dashboard that aggregates all the metrics I recently added.
