### ISSUE TITLE
Tide should be more explicit when a PR has multiple tide/ labels

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#27001]
**What happened**:

- PR had both `tide/merge-method-squash` and `tide/merge-method-merge` label
- The PR had both approved and lgtm labels
- Tide refused to merge it, the GH status is "need approved, lgtm label"

**What you expected to happen**:

GH status should be more explicit on why it refused to fail, for example "multiple labels instructing merging methods"

**How to reproduce it (as minimally and precisely as possible)**:

Create a PR and apply those two mentioned labels

**Please provide links to example occurrences, if any**:

https://github.com/kubernetes/test-infra/pull/26934

**Anything else we need to know?**:

Removed one label and it started to work again

**Comment by jihoon-seo** [comment]
IMO it would also be great to make `tide/merge-method-*` labels cannot coexist among themselves (like `lifecycle/*` labels); 
I mean, for Prow to ensure every PR have no more than 1 `tide/merge-method-*` label. 😊
E.g., Prow removes previous `tide/merge-method-X` label when adding `tide/merge-method-Y` label.

**Comment by jmguzik** [comment]
The basic version was implemented and merged in https://github.com/kubernetes/test-infra/pull/28929.
If a more sophisticated mechanism is needed I would advise opening a feature card. I'll close that one.
/close
