### ISSUE TITLE
windows operational readiness initial runs

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/test-infra#27089]
per @marosset today in Sig-windows, https://docs.google.com/document/d/1Tjxzjjuy4SQsFSUVXZbvqVb64hjNAG5CQX8bK7Yda9w/edit# 

**What would you like to be added**:

Lets start implementing the windows operational readiness suites in here

**Why is this needed**:

To complete https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/2578-windows-conformance 

Ultimately, lets make sure we  upload these to  prow as well

**Comment by knabben** [comment]
job is running in the repo.

/close
