### ISSUE TITLE
Tests from perf-tests repo doesn't work

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/test-infra#2709]
Our tests from perf-tests repo doesn't work on prow:
https://k8s-testgrid.appspot.com/perf-tests#cluster-loader

I tried to debug them and have some finding but now need some help with how to fix them:
1. we need two different repos for the test to run: main kubernetes repo and perf-tests repo - it seems that fetching them works good.

2. however, in prow, fetching seem to go to a completely different place; I looked into the code and the reason is that we are not setting ```--root ``` flag in our job:
https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L1567

3. but the problem that I have with defining them is that without previous, we are generally setting:
```
--root=${{GOPATH}}/src"
```
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml#L10
and injecting appropriate GOPATH and GOROOT:
https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins/bootstrap-ci.yaml#L35

My problem is that in prow, GOPATH and GOROOT are not set (at least env doesn't show them at all).

Can we set GOPATH and GOROOT similarly to what we do currently? If so where can I do it?

@sjug @gmarek

**Comment by wojtek-t** [comment]
Also, can you point me where these:
```
WORKSPACE=/workspace/k8s.io/kubernetes
HOME=/workspace/k8s.io/kubernetes
```
are coming from?

**Comment by krzyzacy** [comment]
GOPATH should be /go/src by default.. which comes from [go image](https://github.com/kubernetes/test-infra/blob/master/jenkins/test-image/Dockerfile-1.4#L18)

WORKSPACE starts from https://github.com/kubernetes/test-infra/blob/master/jenkins/test-image/Dockerfile-1.4#L25, probably changed in bootstrap?

**Comment by wojtek-t** [comment]
> WORKSPACE starts from https://github.com/kubernetes/test-infra/blob/master/jenkins/test-image/Dockerfile-1.4#L25, probably changed in bootstrap?

Do you know where? I was trying to find it and only found that this is set to /workspace.

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py#L694 sets it, and probably checkout k8s changed cwd.

**Comment by ixdy** [comment]
I think the bug is [here](https://github.com/kubernetes/test-infra/blob/3c98e618da6f176a75a25b38a0949d4874fb7338/scenarios/kubernetes_e2e.py#L340-L355).

It makes sense to exclude GOPATH etc when the mode is `docker` (i.e. the scenario runs kubetest through docker), but not when the mode is `local` (i.e. when the scenario runs kubetest directly, as on prow).

**Comment by ixdy** [comment]
cc @fejta since he's in a TODO near there too :)
