### ISSUE TITLE
error during gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json: exit status 1

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#27157]
SOLUTION: See https://github.com/kubernetes/test-infra/issues/27157#issuecomment-1318950082 - thanks @chaodaiG !

notes from @liggitt on Nov 17:
- This just started happening again on 2022-11-16 - https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=error%20during%20gcloud%20auth%20activate-service-account
- Looks like it is failing ~20% of https://testgrid.k8s.io/google-gce#gce-containerd&width=20 runs
- Are particular nodes hitting the issue? looks like all the jobs in https://testgrid.k8s.io/google-gce#gce-containerd&width=20 are running on gke-prow-e2-default-pool-bdc23de7 nodepool ... did that node pool change configuration / version / etc?

Previous Issue body:
Example log:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/111859/pull-kubernetes-e2e-gce-storage-slow/1559899720485179392/build-log.txt

This is happening a lot across a variety of CI jobs. See chatter on #testing-ops as well ( https://kubernetes.slack.com/archives/C7J9RP96G/p1660676173294389 )

```
I0817 13:47:34.328] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0817 13:47:34.969] ERROR: (gcloud.auth.activate-service-account) There was a problem refreshing your current auth tokens: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
W0817 13:47:34.969] Please run:
W0817 13:47:34.969] 
W0817 13:47:34.969]   $ gcloud auth login
W0817 13:47:34.969] 
W0817 13:47:34.970] to obtain new credentials.
W0817 13:47:34.970] 
W0817 13:47:34.970] If you have already logged in with a different account:
W0817 13:47:34.970] 
W0817 13:47:34.970]     $ gcloud config set account ACCOUNT
W0817 13:47:34.970] 
W0817 13:47:34.970] to select an already authenticated account to use.
```

**Comment by dims** [comment]
cc @hakman @tobiasgiese @bobbypage @chaodaiG

**Comment by dims** [comment]
Looks like when this happened way back https://github.com/kubernetes/test-infra/issues/9373 @fejta had to `Replaced the service account`

**Comment by chaodaiG** [comment]
```
W0817 13:47:34.325] **************************************************************************
bootstrap.py is deprecated!
test-infra oncall does not support any job still using bootstrap.py.
Please migrate your job to podutils!
https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md
**************************************************************************
```
bootstrap.py was not equipped to work with workload identity, was long deprecated, should have been migrated to use pod utilities + workload identity, instructions to follow:
- https://github.com/kubernetes/test-infra/tree/master/workload-identity#migrate-prow-job-to-use-workload-identity
- https://gist.github.com/dims/c1296f8ed42238baea0a5fcae45f4cf4 from @dims

**Comment by dims** [comment]
@chaodaiG it happens in non-bootstrap.py jobs too, example:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/containerd_containerd/7304/pull-containerd-build/1559903840889737216/build-log.txt

**Comment by chaodaiG** [comment]
```
'[' -z /etc/service-account/service-account.json ']'
++ gcloud auth activate-service-account --key-file /etc/service-account/service-account.json --project=k8s-cri-containerd
```
remove the `preset-service-account` label from the job should fix

**Comment by dims** [comment]
@chaodaiG looks like there are tons of these jobs with that preset - https://cs.k8s.io/?q=preset-service-account&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra

Let me start with just the ones in `k8s-cri-containerd` project used by containerd.

**Comment by chaodaiG** [comment]
> looks like there are tons of these jobs with that preset - https://cs.k8s.io/?q=preset-service-account&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra

this is not surprising. Having someone to remember to manually rotate this every 80 days doesn't seem like a sustainable solution, so at this point I'm very curious to understand whether there is any job that has no choice but use this physical service account key file.

The second goal, is to figure out whether all these jobs are maintained or not

**Comment by dims** [comment]
@chaodaiG #27161 didn't help :( made the problem worse - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/containerd_containerd/7304/pull-containerd-build/1559968071509086208/build-log.txt

reverting now

**Comment by BenTheElder** [comment]
I don't think I have access to this infra anymore (different team now / different internal groups membership), or fejta (different company).

bootstrap => decorated should really happen but it's a pretty large lift, it might be automate-able but i'm not sure anyone here has bandwidth.

Thanks @chaodaiG @dims.

**Comment by chaodaiG** [comment]
@dims , I think the bash bug is fixed above, could you try re-apply the prowjob PR again?

**Comment by chaodaiG** [comment]
Cross-posting here:
![Screen Shot 2022-08-17 at 12 21 50 PM](https://user-images.githubusercontent.com/45011425/185225039-fbf93273-6c55-48bf-b874-c3cd48ad353c.png)

link: https://kubernetes.slack.com/archives/C7J9RP96G/p1660763919844109?thread_ts=1660758182.628529&cid=C7J9RP96G

**Comment by chaodaiG** [comment]
Documenting the GCP service account key info:
- The key belongs to pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com, and private key id starts with "529d" and ends with "8a47".
- So far the key is known to be stored in 'k8s-prow' and 'k8s-prow-builds' cluster, as a secret named `service-account`, the data is `service-account.json: <BASE64-ENCODED-KEY>` under `test-pods` namespace.

I'll rotate at these two places for now. Please update on this issue if the key is also used somewhere else.

**Comment by willie-yao** [comment]
We are also experiencing this issue with the `apidiff` test on Cluster API Provider Azure as of yesterday. The test marks itself as passed when experiencing this error. Here is the [build log](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/2567/pull-cluster-api-provider-azure-apidiff/1559975734661877760) for reference.

**Comment by chaodaiG** [comment]
manually rotated the secret:
1. Created a new key for pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com in UI
2. Run `k --context=k8s-prow-builds -ntest-pods create secret generic service-account --from-file=service-account.json=<DOWNLOADED_JSON_PATH> -oyaml --dry-run=client | k --context=k8s-prow-builds -ntest-pods apply -f -`
3. Run `k --context=k8s-prow -ntest-pods create secret generic service-account --from-file=service-account.json=<DOWNLOADED_JSON_PATH> -oyaml --dry-run=client | k --context=k8s-prow -ntest-pods apply -f -`

**Comment by dims** [comment]
thanks @chaodaiG, please see https://github.com/kubernetes/test-infra/pull/27169 for the reverts

**Comment by chaodaiG** [comment]
thank you @dims for playing with me all day long :)

**Comment by dims** [comment]
shadowing what you were doing was good experience @chaodaiG !! appreciate it.

**Comment by spiffxp** [comment]
@chaodaiG 
>I'm very curious to understand whether there is any job that has no choice but use this physical service account key file.

https://cs.k8s.io/?q=E2E_GOOGLE_APPLICATION_CREDENTIALS&i=nope&files=&excludeFiles=&repos=

IIRC there are some number of e2e jobs that need to provide a service account key to a gce pd driver deployed to the cluster under test.  The clusters these jobs stand up aren't guaranteed to be GKE clusters, so I'm not sure changing the gce pd driver deployment to use workload identity is an option.

From https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/docs/kubernetes/user-guides/driver-install.md#install-driver:
>The driver requires a service account that has the following permissions and roles to function properly:
> ```
> compute.instances.get
> compute.instances.attachDisk
> compute.instances.detachDisk
> roles/compute.storageAdmin
> roles/iam.serviceAccountUser
> ```

Replacing use of a shared service account key would involve jobs having to run something like the driver's [`setup-project.sh` script](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/setup-project.sh) prior to launching tests, which means permission to create a service account and service account keys in each project.  I think it's possible to provide jobs with this privilege via workload identity, but I forget if the churn/noise of key creation is the reason a shared account key was used in the first place.

cc @msau42 who I think is more familiar with this than I am

**Comment by chaodaiG** [comment]
@spiffxp , that's good to know, thanks! My feeling is that we'll probably need to rotate the key for a while until csi driver team figured out a way of using something like workload identity.

Created https://github.com/kubernetes/test-infra/pull/27202 as a first step for easier key rotation. Once it is merged then secret rotating will become:
- Create a new key
- Upload to GCS secret manager

**Comment by msau42** [comment]
cc @mattcary

**Comment by mattcary** [comment]
Sorry, I'm not following the suggested solution. These keys are for running tests in k8s-on-gce, so there is no workload identity. 

Since this is testing, a workaround is to give all nodes in the cluster cloud-platform scope and running them as a service account with the rbac @spiffxp mentioned above. We use this internally as we've locked down key downloads for google devs.

Would that be reasonable? Note this means that **any** pod running in such a cluster can create/delete disks, etc. Since it's a testing cluster it's probably ok.

I think this may be a some amount of work, depending if kubetest2 has plumbing for node scopes & service accounts during cluster-up.

**Comment by liggitt** [comment]
This just started happening again on 2022-11-16 - https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=error%20during%20gcloud%20auth%20activate-service-account

Looks like it is failing ~20% of https://testgrid.k8s.io/google-gce#gce-containerd&width=20 runs

**Comment by liggitt** [comment]
Are particular nodes hitting the issue? looks like all the jobs in https://testgrid.k8s.io/google-gce#gce-containerd&width=20 are running on gke-prow-e2-default-pool-bdc23de7 nodepool ... did that node pool change configuration / version / etc?

**Comment by chaodaiG** [comment]
As mentioned last time, the secret rotation is a little less risky now. So steps:

1. Create a new json key for pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
2. Create a new version of GCP secret `default-k8s-build-cluster-service-account-key` in `k8s-prow-builds` project, the value is the json key content from step 1
3. Wait a few seconds and the key is rotated

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

We're going to have this problem on a regular basis until we can migrate CI out of google.com, which won't be anytime this year given the kubernetes.io budget issues.

This appears to be happening again.

**Comment by mattcary** [comment]
Maybe we should just bring up clusters with the proper scoped access on all nodes.

The issue is not adding some new special permission in order to get the tests to run. The test is already running with sufficient permissions to create disks---it's creating a cluster after all.

The issue is just plumbing that permission through the k8s layer, which involves this sketchy SA key stuff.

Maybe we should remove the need for the SA key stuff and just give all nodes in the test cluster the permissive scope. Would that be easier in the long term?

**Comment by BenTheElder** [comment]
> Maybe we should remove the need for the SA key stuff and just give all nodes in the test cluster the permissive scope. Would that be easier in the long term?

Yes, *if* all other usage of the key were eliminated, which also includes migrating jobs from bootstrap.py to podutils, like:
https://gist.github.com/dims/c1296f8ed42238baea0a5fcae45f4cf4#file-notes-md

**Comment by BenTheElder** [comment]
(or maybe we can make a minor patch to bootstrap.py to enable workload identity support to speed things up ... not sure)

**Comment by mattcary** [comment]
The first step might be updating kubetest2 to be able to create GCE clusters with the right node scopes? I think that's necessary, and then it would allow migration job per job.

There are instructions [here](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/run-k8s-integration-local.sh#L88) for kubetest, although I'm not sure if those still work, and I think kubetest2 discourages passing through of env vars which means it needs some plumbing. But I'm not sure.

**Comment by listx** [comment]
I've followed https://github.com/kubernetes/test-infra/issues/27157#issuecomment-1318950082 and rotated the keys again. For posterity the steps were:

1. Go to the `kubernetes-jenkins-pull` project's GCP console. Click on `IAM & Admin` and then `Service Accounts`. Find the `pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com` entry in the list and create a new key for it. Create a new JSON key (private key) for `pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com`. This will download the key to your local disk.
2. Go to the `k8s-prow-builds` project GCP console. Go to `Security` -> `Secret Manager`. Then find `default-k8s-build-cluster-service-account-key` in the list. Now upload the JSON key from step 1 here as a new version for this secret. Behind the scenes, the kubernetes-external-secrets pod in the k8s-prow cluster will update this secret in O(seconds).

Note that these same steps were automated in https://github.com/kubernetes/test-infra/pull/28053 but the job has been unhealthy: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-test-infra-rotate-legacy-default-build-sa-json-key

I'll see if I can at least get that job past the exec error.

**Comment by listx** [comment]
OK so apparently https://github.com/kubernetes/test-infra/pull/28786 was not enough. Looks like there is yet another permissions issue: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-rotate-legacy-default-build-sa-json-key/1630742312172654592:

```
ERROR: (gcloud.iam.service-accounts.keys.create) PERMISSION_DENIED: Identity and Access Management (IAM) API has not been used in project 684195865762 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=684195865762 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

The project number is for `k8s-prow`. I need to go offline in a bit but just wanted to take a note of this so that I can address it tomorrow.

**Comment by listx** [comment]
I've enabled the API in the `k8s-prow` project and the job has succeeded: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-test-infra-rotate-legacy-default-build-sa-json-key/1630751309038620672

I can see in the Cloud Console that a new key has been created for `pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com`.

**Comment by BenTheElder** [comment]
THANK YOU @listx 🙏
