### ISSUE TITLE
Comment prompting sig mention does not cater for possibility that an issue owner is not able to mention the sig

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#2717]
The comment should show steps to assign the task of adding the sig mention to others if the issue owner (person opening the issue) is not able to add it.
@grodrigues3

**Comment by grodrigues3** [comment]
Sounds good to me.   Note that non-org members  can't mention sigs directly, but they will still be able to add a sig label based on this PR:

https://github.com/kubernetes/test-infra/pull/2637

**Comment by crimsonfaith91** [comment]
Great! I will start working on this issue. :)

**Comment by grodrigues3** [comment]
Wait, I thought the bot should chat back.  If you are not in the org and you type @ sig-network-pull-requests, the bot should recomment and the mention should work

**Comment by crimsonfaith91** [comment]
I see. In this case, should we still change the comment? I sent out a PR giving the users 3 options to add a sig label:

**Comment by grodrigues3** [comment]
a) and b) work well enough.  2 suggestions

1) Clarify that a) will trigger a notification to the team
1) List one team per sig that they can mention.

Something like.  You can type @kubernetes/sig-[TEAM_NAME]-misc where TEAM_NAME is replaced with one of the following:
node, network, api-machinery, etc.  

There is no autocomplete for non org members so having the list of teams would probably be helpful.

**Comment by crimsonfaith91** [comment]
Instead of listing the teams, perhaps we can add a link to: https://github.com/kubernetes/community/blob/master/sig-list.md

**Comment by grodrigues3** [comment]
SGTM

**Comment by foxish** [comment]
Is this done? Can we close this?

**Comment by crimsonfaith91** [comment]
it is done :)
