### ISSUE TITLE
Summary page does not work for sig-cli

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/test-infra#2718]
The summary page for sig-cli is missing most of the results

https://k8s-testgrid.appspot.com/sig-cli#Summary

**Comment by pwittrock** [comment]
cc @ixdy @mengqiy

**Comment by fejta** [comment]
I'm pretty sure it is working, just REALLY slowly. Largely because Sen has been changing the name of jobs
/cc @krzyzacy

**Comment by mengqiy** [comment]
@fejta I noticed that it will take days for the entries that have been added recently to show in the summary page. But I'm not sure why. Is it because it need to accumulate enough test results?

**Comment by fejta** [comment]
There's a bunch of silly technical reasons. Short version is the updater is unnecessarily dumb and slow. When we rename jobs it takes many days to finish updating, which causes the delay in updating the summaries. These are easier to talk about internally, since that portion of testgrid remains internal to Google.

**Comment by krzyzacy** [comment]
hummmm I don't think there's anything to do with the rename now.. that's couple months ago and is a one-time effect.. rename a few jobs is not going to have a large impact of update cycle, and other tabs are updating fine.

I'll check if there's a internal thread.

**Comment by mengqiy** [comment]
I just verified that the issue has been fixed.
/close

**Comment by fejta** [comment]
There's actually some stability issues here, which we're addressing internally.

**Comment by krzyzacy** [comment]
It's fixed internally :-)
