### ISSUE TITLE
Move `latest-build.txt` handling from prowjob sidecar to crier

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/test-infra#27219]
**What would you like to be added**:

Per title

**Why is this needed**:

Prow job pods are responsible for uploading jobs metadata, logs, and artifacts into storage, these require `storage.create` permission, which is relatively safe even if a prowjob accidentally gains the permission and writes something to the storage location where all Prowjobs logs and results are located. The only place where `storage.delete` is required is that the sidecar container is constantly updating the `latest-build.txt` file for a given job, this permission, however will result in much worse outcome if a prowjob accidentally gains and uses this permission.

Searched through Prow codebase and I was not able to find where `latest-build.txt` is used, so it probably is not very widely used in Prow. Crier handling this logic means that `latest-build.txt` would be updated even earlier than by prowjob itself, as it doesn't need to wait until the pod is provisioned.

/sig testing

**Comment by chaodaiG** [comment]
cc @cjwagner @alvaroaleman @michelle192837 @chases2 , WDYT?

**Comment by chaodaiG** [comment]
also kudos to @spiffxp for pointing this out on a separate thread. This is a great idea!

**Comment by alvaroaleman** [comment]
Doesn't storage.create mean you can "delete" content by writing a new empty file to an existing location?

**Comment by chaodaiG** [comment]
> Doesn't storage.create mean you can "delete" content by writing a new empty file to an existing location?

not actually in GCS, see https://cloud.google.com/storage/docs/access-control/iam-roles#standard-roles
![Screen Shot 2022-08-22 at 3 28 16 PM](https://user-images.githubusercontent.com/45011425/186029900-51c4bad1-8e00-4681-86ed-3ef5694cfbef.png)
