### ISSUE TITLE
When go-vet fails it isn't neatly highlighted in the gubernator output

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/test-infra#2725]
See:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45603/pull-kubernetes-verify/29184/

For example. Lots of spurious "error" messages are highlighted, but the actual problem is hidden behind some skipped lines.

**Comment by cblecker** [comment]
https://github.com/kubernetes/kubernetes/pull/45984 should fix this up, so the `FAILED` message from verify.sh will display if vet doesn't pass.
