### ISSUE TITLE
prow: badge.svg does not seem to work reliably

### ISSUE THREAD

**Issue by marquiz** [kubernetes/test-infra#27260]
**What happened**:

badge.svg is green/passing even if job is failing.

**What you expected to happen**:

badge.svg is red/failure if job is failing

**How to reproduce it (as minimally and precisely as possible)**:

At present, all jobs in of sig-node-cos are failing accoriding to the testgrid (https://testgrid.k8s.io/sig-node-cos). Take any one of them and the badge is still green/passing, e.g.:

https://prow.k8s.io/badge.svg?jobs=ci-cri-containerd-e2e-cos-gce

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/badge.svg?jobs=ci-cri-containerd-e2e-cos-gce

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
previously https://github.com/kubernetes/test-infra/issues/9628

I don't think anyone is working on this part of prow currently (I don't really work on prow at all anymore myself ...).
