### ISSUE TITLE
Prow will use it's configured AWS IAM credentials to return arbitrary file contents from S3 paths ending in '.txt'

### ISSUE THREAD

**Issue by dscofaws** [kubernetes/test-infra#27333]
**What happened**:

Prow as implemented in the current test-infra repo master branch contains a [route](https://github.com/kubernetes/test-infra/blob/a57f8abeb442eab70a13d2b1c25285a7beb7ed84/prow/cmd/deck/main.go#L692) for the path `/view/s3/path/to/file`.  The [request handler](https://github.com/kubernetes/test-infra/blob/a57f8abeb442eab70a13d2b1c25285a7beb7ed84/prow/cmd/deck/main.go#L931) makes a [call](https://github.com/kubernetes/test-infra/blob/a57f8abeb442eab70a13d2b1c25285a7beb7ed84/prow/cmd/deck/main.go#L938) to [renderSpyglass](https://github.com/kubernetes/test-infra/blob/a57f8abeb442eab70a13d2b1c25285a7beb7ed84/prow/cmd/deck/main.go#L959) which then calls calls [ResolveSymlink](https://github.com/kubernetes/test-infra/blob/a57f8abeb442eab70a13d2b1c25285a7beb7ed84/prow/cmd/deck/main.go#L963).  The basic function of [ResolveSymlink](https://github.com/kubernetes/test-infra/blob/a57f8abeb442eab70a13d2b1c25285a7beb7ed84/prow/spyglass/spyglass.go#L178) is to append `".txt"` to the supplied path, call `s3:GetObject` (or the GCS equivalent) on that path and interpret the results as a URL. If that URL parsing fails, the error message is [packed into a string and returned](https://github.com/kubernetes/test-infra/blob/a57f8abeb442eab70a13d2b1c25285a7beb7ed84/prow/spyglass/spyglass.go#L207). The problem is that this error message is of the form error `failed to parse URL: parse "<THE CONTENTS OF THE FILE>": net/url: invalid control character in URL`. This is a low severity confused deputy issue -- an arbitrary user can instruct prow to call `s3:GetObject` on any S3 path ending in `.txt` and return the contents. Since this call is made with prow's configured IAM credentials, arbitrary users can effectively call `s3:GetObject` as the prow IAM role.

The impact here is mitigated by having a tightly scoped role for Prow. However, other handlers in prow call `validateStoragePath` to prevent this issue, so `ResolveSymlink` (or something on the control flow path to it) should probably do the same.

**What you expected to happen**:

A call to `validateStoragePath` should occur before or within `ResolveSymlink`

**How to reproduce it (as minimally and precisely as possible)**:

Set up a public S3 bucket, add a file called `test.txt` that's less than 4k in size to that bucket.
On your local prow endpoint, go to the path `/view/s3/bucketname/test`
You will see the contents of `test.txt` displayed

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

Previously reported to security@, initial fix is via https://github.com/kubernetes/test-infra/pull/27249/ but from inspection, this does not look like it will solve the issue since `ResolveSymlink` is the function that causes the confused deputy issue and there is no call to `validateStoragePath` before or within `ResolveSymlink`.

**Comment by alvaroaleman** [comment]
/cc @chaodaiG 
Maybe it would be best to plug `validateStoragePath` into the `io.Opener` as that is the common code that is used for all object storage access?

**Comment by chaodaiG** [comment]
> /cc @chaodaiG Maybe it would be best to plug `validateStoragePath` into the `io.Opener` as that is the common code that is used for all object storage access?

this generally sounds good to me. My only concern is that I'm expecting pod-utils to also use `io.Opener` in the future, and I'm afraid that dealing with custom storage path in `inrepoconfig` will be a headache
