### ISSUE TITLE
Alerts for test-infra breakages

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#2740]
We should get alerts for lots of things:

- [ ] last successful merge time > 4 hrs (if queue is non-empty)
- [ ] last successful batch merge time > 4 hrs (if queue is non-empty)
- [ ] triage dashboard most recent build > 2 hrs old
- [ ] any presubmit job failure rate > 80% for last 10 builds

These should go to the [oncall](https://go.k8s.io/oncall) to be addressed quickly.

We can send email alerts to some test-infra-paging group. Stackdriver might be able to manage this, or maybe something else.

**Comment by spxtr** [comment]
Related to #2699 and #2739.

**Comment by BenTheElder** [comment]
we at least have some testgrid alerts now, we really ought to have a test-infra paging group too though and reconfigure things to go that way.
