### ISSUE TITLE
Unable to see logs from /log endpoint when pod is cleaned up

### ISSUE THREAD

**Issue by mohitsharma-in** [kubernetes/test-infra#27420]
**What would you like to be added**:
This will help in providing better user experience from deck in order to check logs 

**Why is this needed**:
When the pods are being cleaned up after completion, logs are not visible rather is shows 
`Log not found: pods "fe5f2481-2f30-11ed-a59e-fe72ba29f753" not found` 
Example: https://prow.k8s.io/log?job=ci-test-infra-prow-checkconfig&id=1567735727028965376

Logs are available on GCS 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-test-infra-prow-checkconfig/1567735727028965376/build-log.txt

Idea is to show logs on /log endpoint irrespective of pod is available or cleaned up 

https://github.com/kubernetes/test-infra/issues/27420#tasklist-block-09e8c859-3b33-48eb-b266-1086101e0970

**Comment by jbpratt** [comment]
Some additional information:

The `/log` handler is configured here
https://github.com/kubernetes/test-infra/blob/c2d8edcd1586aa11409dd167a5b2fd11bfc711e6/prow/cmd/deck/main.go#L448
which fetches job logs here
https://github.com/kubernetes/test-infra/blob/c2d8edcd1586aa11409dd167a5b2fd11bfc711e6/prow/cmd/deck/main.go#L1380
then grabbing the pod logs here
https://github.com/kubernetes/test-infra/blob/c2d8edcd1586aa11409dd167a5b2fd11bfc711e6/prow/deck/jobs/jobs.go#L250

**Comment by mohitsharma-in** [comment]
@jbpratt  Can you help me how it's done differently on lens
