### ISSUE TITLE
error unmarshaling config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"resources\"

### ISSUE THREAD

**Issue by asim-reza** [kubernetes/test-infra#27447]
### What happened:
***

Prow's [checkconfig](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig) tool is responsible for presubmit validation of ProwJob configuration. It has an optional check for unknown fields in ProwJob config that can be enabled with `--warnings=unknown-fields-all`.

As a result it is possible to add configuration that is not recognized by Prow, causing it to be silently ignored. Common examples of this are typos in a field name and incorrect indentation.

It would be great to enable this check across the repo, but before we can we must address all existing unknown fields. 

 `--warnings=unknown-fields-all` [was added to an optional job and merged](https://github.com/kubernetes/test-infra/pull/27391)

***
[checkconfig](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig) with --warnings=unknown-fields-all run locally with the following- 

`docker run -i --rm -v "${PWD}:${PWD}" -w "${PWD}" gcr.io/k8s-prow/checkconfig:v20220905-8bcebc6376 --config-path=config/prow/config.yaml --job-config-path=config/jobs --plugin-config=config/prow/plugins.yaml --strict --warnings=mismatched-tide-lenient --warnings=tide-strict-branch --warnings=needs-ok-to-test --warnings=validate-owners --warnings=missing-trigger --warnings=validate-urls --warnings=unknown-fields --warnings=duplicate-job-refs --warnings=unknown-fields-all`

returns error:

`{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"error unmarshaling config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"resources\"","severity":"warning","time":"2022-09-08T18:58:25Z"}
`

***

### What you expected to happen:
***
Output:
`{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:252","func":"main.main","level":"info","msg":"checkconfig passes without any error!","severity":"info","time":"2022-09-08T17:44:36Z"}`
***

### How to reproduce it (as minimally and precisely as possible):
***
run the following in the root locally

`docker run -i --rm -v "${PWD}:${PWD}" -w "${PWD}" gcr.io/k8s-prow/checkconfig:v20220905-8bcebc6376 --config-path=config/prow/config.yaml --job-config-path=config/jobs --plugin-config=config/prow/plugins.yaml --strict --warnings=mismatched-tide-lenient --warnings=tide-strict-branch --warnings=needs-ok-to-test --warnings=validate-owners --warnings=missing-trigger --warnings=validate-urls --warnings=unknown-fields --warnings=duplicate-job-refs --warnings=unknown-fields-all` 

***

### Proposed Fix:

Issue happens when `resources:` is scoped under `spec:` the error resolves if the `resources:`
are set under the `containers:` template ... The error resolves if the following diff is applied

***
```diff
index 817fb85df4..3f2680b19a 100644
--- a/config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml
+++ b/config/jobs/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/config.yaml
@@ -84,12 +84,12 @@ presubmits:
         # hack/verify-all.sh runs docker to validate the built docker images
         securityContext:
           privileged: true
-      resources:
-        requests:
-          # Peak usage was measured at 4.5 Gi
-          memory: "6000Mi"
-          # Peak cpu usage was measured at 2500m, average close to 1000m
-          cpu: 2000m
+        resources:
+          requests:
+            # Peak usage was measured at 4.5 Gi
+            memory: "6000Mi"
+            # Peak cpu usage was measured at 2500m, average close to 1000m
+            cpu: 2000m
     annotations:
       testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
       testgrid-tab-name: presubmit-gcp-compute-persistent-disk-csi-driver-verify
@@ -114,13 +114,13 @@ presubmits:
         # docker-in-docker needs privileged mode
         securityContext:
           privileged: true
-      resources:
-        requests:
-          # these are both a bit below peak usage during build
-          # this is mostly for building kubernetes
-          memory: "9000Mi"
-          # during the tests more like 3-20m is used
-          cpu: 2000m
+        resources:
+          requests:
+            # these are both a bit below peak usage during build
+            # this is mostly for building kubernetes
+            memory: "9000Mi"
+            # during the tests more like 3-20m is used
+            cpu: 2000m
     annotations:
       testgrid-dashboards: provider-gcp-compute-persistent-disk-csi-driver
       testgrid-tab-name: presubmit-gcp-compute-persistent-disk-csi-driver-kubernetes-integration



```

***

/sig testing

**Comment by asim-reza** [comment]
@davidz627
@mattcary
@msau42
@saad-ali
@saikat-royc



Hey! do you guys mind checking if the proposed solution is okay to push? Ill create a PR if so ✌🏼

**Comment by mattcary** [comment]
This LGTM---thanks for finding it! I bet we weren't actually applying those resources due to that indentation problem?

You can assign the PR to me. I'm not quite sure if I have test-infra approver power,  but I'll figure out who does.

**Comment by asim-reza** [comment]
yup if the resources aren't in place they dont get applied... but at some place container templates get resource limits/allocations so those would... 
Im working on fixing the script that auto-generates these till then we can patch these manually... Creating a PR
