### ISSUE TITLE
ClusterLoader tests are failing to find scripts

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/test-infra#2744]
All ClusterLoader tests are failing with the following error:
```
error starting /src/k8s.io/perf-tests/clusterloader/run-e2e.sh: fork/exec /src/k8s.io/perf-tests/clusterloader/run-e2e.sh: no such file or directory
```
See e.g.: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-perf-tests-e2e-gce-clusterloader/677

I spent some time trying to debug it and I realized, that in prow we are running scripts in "Local" mode (whereas in Jenkins we are running in "Docker" mode).
As a result, the "--mount-path" flags doesn't have any effect.

As a result, things like this:
https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L417

can't be done universally, because we don't really know the path.

I can workaround it in clusterloader test by attaching "/go" prefix and it will work, but that's not a universal fix, and we will face exactly the same issue e.g. when we will be migrating "charts" job to prow.

We need to have some story for it.

@kubernetes/test-infra-maintainers

**Comment by krzyzacy** [comment]
how about get `GOPATH` in kubetest, use `$GOPATH/src/k8s.io/perf-tests/clusterloader/run-e2e.sh`?

**Comment by wojtek-t** [comment]
That assumes that we are checkout-ing repos to ${GOPATH} - but maybe that's a sane assumption.
I think that will work from my perspective.

**Comment by krzyzacy** [comment]
It depends on what the `--root` flag you set to, which is `/go/src`, and it's only used by this test though.

**Comment by wojtek-t** [comment]
BTW - I tried this: https://github.com/kubernetes/test-infra/pull/2743/
and it seems it didn't take any effect, even though I built those new images:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-perf-tests-e2e-gce-clusterloader/835

Any thoughts why? What I did wrong?

**Comment by wojtek-t** [comment]
Actually, it seems that now it picked up the change:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-perf-tests-e2e-gce-clusterloader/836

but it still doesn't work. I will try again with the "${GOPATH}" and will add some more logs for debugging.

**Comment by wojtek-t** [comment]
I don't understand this at all.

Looking into logs from the last run, I'm seeing this:
```
W0512 19:00:58.654] 2017/05/12 19:00:58 util.go:198: Running: ls ${GOPATH}/src
W0512 19:00:58.654] 2017/05/12 19:00:58 util.go:200: Step 'ls ${GOPATH}/src' finished in 684.541Âµs
W0512 19:00:58.655] 2017/05/12 19:00:58 e2e.go:418: ls ${GOPATH}/src: 
W0512 19:00:58.655] 2017/05/12 19:00:58 util.go:198: Running: ls /go/src
W0512 19:00:58.655] 2017/05/12 19:00:58 util.go:200: Step 'ls /go/src' finished in 505.982Âµs
W0512 19:00:58.655] 2017/05/12 19:00:58 e2e.go:423: ls /go/src: 
W0512 19:00:58.656] 2017/05/12 19:00:58 util.go:198: Running: ls /go/src/k8s.io
W0512 19:00:58.656] 2017/05/12 19:00:58 util.go:200: Step 'ls /go/src/k8s.io' finished in 468.736Âµs
W0512 19:00:58.656] 2017/05/12 19:00:58 e2e.go:428: ls /go/src/k8s.io: 
W0512 19:00:58.656] 2017/05/12 19:00:58 util.go:198: Running: ls /go/src/k8s.io/perf-tests
W0512 19:00:58.656] 2017/05/12 19:00:58 util.go:200: Step 'ls /go/src/k8s.io/perf-tests' finished in 446.124Âµs
W0512 19:00:58.656] 2017/05/12 19:00:58 e2e.go:433: ls /go/src/k8s.io/perf-tests: 
```

Those are coming from here:
https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L416


At the same time at the beginning of logs, I'm seeing this:
```
I0512 18:54:15.330] Root: /go/src
I0512 18:54:15.330] Checkout: /go/src/k8s.io/kubernetes master
```

Those are coming from;
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-perf-tests-e2e-gce-clusterloader/864/build-log.txt

I have no idea how to proceed with it. It seems that at the same time the files are and aren't there.

@ixdy @fejta @krzyzacy - can someone please help me with debugging it? Where are those files and how can I access it?

**Comment by wojtek-t** [comment]
I'm also seeing this in the logs:
```
I0512 18:55:21.488] Extracting /go/src/k8s.io/kubernetes/kubernetes/client/kubernetes-client-linux-amd64.tar.gz into /go/src/k8s.io/kubernetes/kubernetes/platforms/linux/amd64
I0512 18:55:22.582] Add '/go/src/k8s.io/kubernetes/kubernetes/client/bin' to your PATH to use newly-installed binaries.
```
it cleearly shows that something should be under `/go/src` and now I don't understand it completely. I really need help with it.

**Comment by ixdy** [comment]
The `ls` commands are returning an error; the if statement is backwards (should be `err == nil`)
```golang
if out, err := output(exec.Command("ls ${GOPATH}/src")); err != nil {
	log.Printf("ls ${GOPATH}/src: %s", string(out))
} else {
	log.Printf("ls ${GOPATH}/src error: %v", err)
}
```

The particular issue here is that it should be `exec.Command("ls", "${GOPATH}/src")` etc.

I suspect the later failure is because you're using `${GOPATH}/path/to/script.sh`, but `exec.Command()` doesn't substitute variables AFAIK. You'll need to use `/go/path/to/script.sh` instead.

**Comment by wojtek-t** [comment]
@ixdy - ahh ok - that explains the first ls command. But that doesn't explain the second:
https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L422
which is doing "ls /go/src".

Maybe it should be "ls "/go/src" instead of "ls /go/src" ?

**Comment by wojtek-t** [comment]
Hmm - it has to be something specific to prow. I did `docker exec` into the container when it was running and got this:
```
root@ci-perf-tests-e2e-gce-clusterloader-887:/workspace# cat ${GOPATH}/src/k8s.io/perf-tests/clusterloader/run-e2e.sh
#!/bin/bash
...
```

So the files are where they expect to be. I don't know why running the script doesn't work...

**Comment by krzyzacy** [comment]
yeah looks like "ls" "/go/src" according to the [doc](https://golang.org/pkg/os/exec/#Command)

I don't think exec.Command expands ${GOPATH}, what if you try to append os.Getenv("GOPATH") rather than "${GOPATH}"? That should run the script..

**Comment by wojtek-t** [comment]
OK - so the thing with "os.Getenv()" did the trick. We are now step further.

Our current problem is that prow is based on Go 1.6.3, but we need Go 1.7.x. I will try to investigate if bumping it will be fine.

**Comment by wojtek-t** [comment]
@krzyzacy @fejta - I'm seeing that there are already base test-images using higher version of go here
https://github.com/kubernetes/test-infra/tree/master/jenkins/test-image

However, the test-e2e image (and thus also the prow image) is based on pretty old version (including Go 1.6.3):
https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/Dockerfile#L18

@krzyzacy @fejta - how can I list all the test-image that are already built? Is it possible to bump e2e-image to one of those?

**Comment by krzyzacy** [comment]
ahh, since we did not have the needs before...

You can view all the built images from k8s-testimages project, and feel free to create a new Dockerfile base off go 1.7 if you need it.

**Comment by wojtek-t** [comment]
> You can view all the built images from k8s-testimages project, and feel free to create a new Dockerfile base off go 1.7 if you need it.

Is it possible to check which image is built from which Go somehow?

I should be fine from both Go 1.7 and Go 1.8 (if such image exist).

**Comment by krzyzacy** [comment]
hummm, I think all kubekins-e2e is built with go 1.6.3 since https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/Dockerfile#L18 is pretty old... kubekins-test is tagged with release number, 1.5 and 1.6 uses go 1.7 and 1.7 uses go 1.8.

**Comment by wojtek-t** [comment]
@krzyzacy - thanks
I've just merged https://github.com/kubernetes/test-infra/pull/2756 - I hope that this should help.

**Comment by wojtek-t** [comment]
OK - with that change we seem to be able to compile everything we need.

We are hitting a different issue now, but that is now completely unrelated to test-infrastructure. So I'm closing this one.

Thanks for help everyone!
