### ISSUE TITLE
error unmarshaling config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-*.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"volumes\"

### ISSUE THREAD

**Issue by asim-reza** [kubernetes/test-infra#27448]
### What happened:
***

Prow's [checkconfig](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig) tool is responsible for presubmit validation of ProwJob configuration. It has an optional check for unknown fields in ProwJob config that can be enabled with `--warnings=unknown-fields-all`.

As a result it is possible to add configuration that is not recognized by Prow, causing it to be silently ignored. Common examples of this are typos in a field name and incorrect indentation.

It would be great to enable this check across the repo, but before we can we must address all existing unknown fields. 

 `--warnings=unknown-fields-all` [was added to an optional job and merged](https://github.com/kubernetes/test-infra/pull/27391)

***
[checkconfig](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig) with --warnings=unknown-fields-all run locally with the following- 

`docker run -i --rm -v "${PWD}:${PWD}" -w "${PWD}" gcr.io/k8s-prow/checkconfig:v20220905-8bcebc6376 --config-path=config/prow/config.yaml --job-config-path=config/jobs --plugin-config=config/prow/plugins.yaml --strict --warnings=mismatched-tide-lenient --warnings=tide-strict-branch --warnings=needs-ok-to-test --warnings=validate-owners --warnings=missing-trigger --warnings=validate-urls --warnings=unknown-fields --warnings=duplicate-job-refs --warnings=unknown-fields-all`

returns error:

`{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:91","func":"main.reportWarning","level":"warning","msg":"error unmarshaling config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-3.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"volumes\", error unmarshaling config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"volumes\", error unmarshaling config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-0.yaml: error unmarshaling JSON: while decoding JSON: json: unknown field \"volumes\"","severity":"warning","time":"2022-09-08T18:58:25Z"}
`

Files throwing errors:
`config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-3.yaml`
`config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml`
`config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-0.yaml`

***

### What you expected to happen:
***
Output:
`{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:252","func":"main.main","level":"info","msg":"checkconfig passes without any error!","severity":"info","time":"2022-09-08T17:44:36Z"}`
***

### How to reproduce it (as minimally and precisely as possible):
***
run the following in the root locally

`docker run -i --rm -v "${PWD}:${PWD}" -w "${PWD}" gcr.io/k8s-prow/checkconfig:v20220905-8bcebc6376 --config-path=config/prow/config.yaml --job-config-path=config/jobs --plugin-config=config/prow/plugins.yaml --strict --warnings=mismatched-tide-lenient --warnings=tide-strict-branch --warnings=needs-ok-to-test --warnings=validate-owners --warnings=missing-trigger --warnings=validate-urls --warnings=unknown-fields --warnings=duplicate-job-refs --warnings=unknown-fields-all` 

***

### Proposed Fix:

Issue happens when `volumes:` is scoped under `spec:` the error resolves if the `volumes:`
are set under the `containers:` template ... The error resolves if the following diff is applied

***
```diff
index ad9b55f5f2..0afad92a9e 100644
--- a/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-3.yaml
+++ b/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-3.yaml
@@ -78,13 +78,13 @@ periodics:
           secretKeyRef:
             name: cluster-lifecycle-github-token
             key: cluster-lifecycle-github-token
-  volumes:
-  - name: cluster-lifecycle-github-token
-    secret:
-      secretName: cluster-lifecycle-github-token
-      items:
-      - key: cluster-lifecycle-github-token
-        path: cluster-lifecycle-github-token
+    volumes:
+    - name: cluster-lifecycle-github-token
+      secret:
+        secretName: cluster-lifecycle-github-token
+        items:
+        - key: cluster-lifecycle-github-token
+          path: cluster-lifecycle-github-token
   annotations:
     testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.3
     testgrid-tab-name: capi-verify-book-links-release-0-3
diff --git a/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml b/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml
index 36e229a2e9..cfb67afc67 100644
--- a/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml
+++ b/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml
@@ -127,13 +127,13 @@ periodics:
           secretKeyRef:
             name: cluster-lifecycle-github-token
             key: cluster-lifecycle-github-token
-  volumes:
-  - name: cluster-lifecycle-github-token
-    secret:
-      secretName: cluster-lifecycle-github-token
-      items:
-      - key: cluster-lifecycle-github-token
-        path: cluster-lifecycle-github-token
+    volumes:
+    - name: cluster-lifecycle-github-token
+      secret:
+        secretName: cluster-lifecycle-github-token
+        items:
+        - key: cluster-lifecycle-github-token
+          path: cluster-lifecycle-github-token
   annotations:
     testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.4
     testgrid-tab-name: capi-verify-book-links-release-0-4
...skipping...
diff --git a/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml b/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml
index 36e229a2e9..cfb67afc67 100644
--- a/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml
+++ b/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-0-4.yaml
@@ -127,13 +127,13 @@ periodics:
           secretKeyRef:
             name: cluster-lifecycle-github-token
             key: cluster-lifecycle-github-token
-  volumes:
-  - name: cluster-lifecycle-github-token
-    secret:
-      secretName: cluster-lifecycle-github-token
-      items:
-      - key: cluster-lifecycle-github-token
-        path: cluster-lifecycle-github-token
+    volumes:
+    - name: cluster-lifecycle-github-token
+      secret:
+        secretName: cluster-lifecycle-github-token
+        items:
+        - key: cluster-lifecycle-github-token
+          path: cluster-lifecycle-github-token
   annotations:
     testgrid-dashboards: sig-cluster-lifecycle-cluster-api-0.4
     testgrid-tab-name: capi-verify-book-links-release-0-4
diff --git a/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-0.yaml b/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-0.yaml
index b2e3ace4b8..9752aa9ecf 100644
--- a/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-0.yaml
+++ b/config/jobs/kubernetes-sigs/cluster-api/cluster-api-periodics-release-1-0.yaml
@@ -172,13 +172,13 @@ periodics:
           secretKeyRef:
             name: cluster-lifecycle-github-token
             key: cluster-lifecycle-github-token
-  volumes:
-  - name: cluster-lifecycle-github-token
-    secret:
-      secretName: cluster-lifecycle-github-token
-      items:
-      - key: cluster-lifecycle-github-token
-        path: cluster-lifecycle-github-token
+    volumes:
+    - name: cluster-lifecycle-github-token
+      secret:
+        secretName: cluster-lifecycle-github-token
+        items:
+        - key: cluster-lifecycle-github-token
+          path: cluster-lifecycle-github-token
   annotations:
     testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.0
     testgrid-tab-name: capi-verify-book-links-release-1-0


```

***

/sig testing

**Comment by asim-reza** [comment]
@CecileRobertMichon
@davidewatson
@detiber
@fabriziopandini
@justinsb
@sbueringer
@timothysc
@vincepri

Hey! do you guys mind checking if the proposed solution is okay to push? Ill create a PR if so ✌🏼

**Comment by sbueringer** [comment]
Sounds good. Please only assign me on the pr. I'll approve
