### ISSUE TITLE
deprecated field: maintainers_id is configured for repo_milestone, maintainers_team should be used instead"

### ISSUE THREAD

**Issue by asim-reza** [kubernetes/test-infra#27457]
### What happened:
***

Prow's [checkconfig](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig) tool is responsible for presubmit validation of ProwJob configuration. It has an optional check for unknown fields in ProwJob config that can be enabled with `--warnings=unknown-fields-all`.

As a result it is possible to add configuration that is not recognized by Prow, causing it to be silently ignored. Common examples of this are typos in a field name and incorrect indentation.

It would be great to enable this check across the repo, but before we can we must address all existing unknown fields. 

 `--warnings=unknown-fields-all` [was added to an optional job and merged](https://github.com/kubernetes/test-infra/pull/27391)

***
[checkconfig](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/checkconfig) with --warnings=unknown-fields-all run locally with the following- 

`docker run -i --rm -v "${PWD}:${PWD}" -w "${PWD}" gcr.io/k8s-prow/checkconfig:v20220905-8bcebc6376 --config-path=config/prow/config.yaml --job-config-path=config/jobs --plugin-config=config/prow/plugins.yaml --strict --warnings=mismatched-tide-lenient --warnings=tide-strict-branch --warnings=needs-ok-to-test --warnings=validate-owners --warnings=missing-trigger --warnings=validate-urls --warnings=unknown-fields --warnings=duplicate-job-refs --warnings=unknown-fields-all`

returns errors:

`{"component":"checkconfig","file":"k8s.io/test-infra/prow/logrusutil/logrusutil.go:128","func":"k8s.io/test-infra/prow/logrusutil.ThrottledWarnf","level":"warning","msg":"deprecated field: maintainers_id is configured for repo_milestone, maintainers_team should be used instead","severity":"warning","time":"2022-09-09T02:27:22Z"}`

`{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:94","func":"main.reportWarning","level":"fatal","msg":"Strict is set and there were warnings","severity":"fatal","time":"2022-09-09T02:27:23Z"}`

***

### What you expected to happen:
***
Output:
`{"component":"checkconfig","file":"k8s.io/test-infra/prow/cmd/checkconfig/main.go:252","func":"main.main","level":"info","msg":"checkconfig passes without any error!","severity":"info","time":"2022-09-08T17:44:36Z"}`
***

### How to reproduce it (as minimally and precisely as possible):
***
run the following in the root locally

`docker run -i --rm -v "${PWD}:${PWD}" -w "${PWD}" gcr.io/k8s-prow/checkconfig:v20220905-8bcebc6376 --config-path=config/prow/config.yaml --job-config-path=config/jobs --plugin-config=config/prow/plugins.yaml --strict --warnings=mismatched-tide-lenient --warnings=tide-strict-branch --warnings=needs-ok-to-test --warnings=validate-owners --warnings=missing-trigger --warnings=validate-urls --warnings=unknown-fields --warnings=duplicate-job-refs --warnings=unknown-fields-all` 

***

### Proposed Fix:

Issue occurs because the field `maintainers_id:` is depricated... the error resolves itself if the following diff is applied

***
```diff

index 987f3f57c7..2ddcdb46cf 100644
--- a/config/prow/plugins.yaml
+++ b/config/prow/plugins.yaml
@@ -484,67 +484,51 @@ repo_milestone:
     # You can curl the following endpoint in order to determine the github ID of your team
     # responsible for maintaining the milestones. You may need to specify the page number.
     # curl -H "Authorization: token <token>" "https://api.github.com/orgs/<org-name>/teams?page=N"
-    maintainers_id: 2460384
     maintainers_team: milestone-maintainers
     maintainers_friendly_name: Milestone Maintainers Team
   kubernetes-sigs/controller-runtime:
-    maintainers_id: 2785806
     maintainers_team: controller-runtime-maintainers
     maintainers_friendly_name: Controller Runtime Maintainers
   kubernetes-sigs/cluster-api:
-    maintainers_id: 3058957
     maintainers_team: cluster-api-maintainers
     maintainers_friendly_name: Cluster API Maintainers
   kubernetes-sigs/cluster-api-provider-aws:
-    maintainers_id: 2830895
     maintainers_team: cluster-api-provider-aws-maintainers
     maintainers_friendly_name: Cluster API Provider AWS Maintainers
   kubernetes-sigs/cluster-api-provider-azure:
-    maintainers_id: 3063852
     maintainers_team: cluster-api-provider-azure-maintainers
     maintainers_friendly_name: Cluster API Provider Azure Maintainers
   kubernetes-sigs/cluster-api-provider-digitalocean:
-    maintainers_id: 2978501
     maintainers_team: cluster-api-provider-digitalocean-maintainers
     maintainers_friendly_name: Cluster API Provider DigitalOcean Maintainers
   kubernetes-sigs/cluster-api-provider-gcp:
-    maintainers_id: 2829767
     maintainers_team: cluster-api-provider-gcp-maintainers
     maintainers_friendly_name: Cluster API Provider GCP Maintainers
   kubernetes-sigs/cluster-api-provider-nested:
-    maintainers_id: 4158805
     maintainers_team: cluster-api-provider-nested-maintainers
     maintainers_friendly_name: Cluster API Provider Nested Maintainers
   kubernetes-sigs/cluster-api-provider-vsphere:
-    maintainers_id: 2850058
     maintainers_team: cluster-api-provider-vsphere-maintainers
     maintainers_friendly_name: Cluster API Provider vSphere Maintainers
   kubernetes/community:
-    maintainers_id: 3169231
     maintainers_team: community-milestone-maintainers
     maintainers_friendly_name: Community Milestone Maintainers
   kubernetes/kops:
-    maintainers_id: 2060651
     maintainers_team: kops-maintainers
     maintainers_friendly_name: Kops Maintainers
   kubernetes/ingress-nginx:
-    maintainers_id: 2179129
     maintainers_team: ingress-nginx-maintainers
     maintainers_friendly_name: Ingress Nginx Maintainers
   kubernetes/org:
-    maintainers_id: 2842373
     maintainers_team: owners
     maintainers_friendly_name: GitHub Admin Team
   kubernetes/website:
-    maintainers_id: 3175912
     maintainers_team: website-milestone-maintainers
     maintainers_friendly_name: Website milestone maintainers
   kubernetes/kubeadm:
-    maintainers_id: 2195382
     maintainers_team: kubeadm-maintainers
     maintainers_friendly_name: Kubeadm maintainers
   kubernetes-sigs/kubebuilder:
-    maintainers_id: 2688053
     maintainers_team: kubebuilder-maintainers
     maintainers_friendly_name: Kubebuilder Maintainers




```

***

/sig testing

**Comment by asim-reza** [comment]
@alvaroaleman
@cblecker
@cjwagner
@fejta
@petr-muller
@stevekuznetsov

Hey! do you guys mind checking if the proposed solution is okay to push? Ill create a PR if so ✌🏼

**Comment by alvaroaleman** [comment]
No we can not just delete the maintainers_id. They would need to get migrated to the team name. Why does an unknown field check complain about a deprecated, but known field?

**Comment by asim-reza** [comment]
Do you mind walking me through the process of the migration? The tool spits out a warning and has a strict check so wouldn't pass unless fixed

**Comment by asim-reza** [comment]
Or just point me to the documentation if that's there

**Comment by asim-reza** [comment]
@alvaroaleman the error says use "member_team" instead as that is already there wouldnt it work just to remove the members_id?

**Comment by cblecker** [comment]
I [double checked](https://github.com/kubernetes/test-infra/blob/a926ce5587648cdcfff628d718791ea5c451037a/prow/plugins/milestone/milestone.go#L169-L174), and yes, if `maintainers_team` is set, we effectively ignore `maintainers_id`. We should be safe to remove `maintainers_id` from any `repo_milestone` team where `maintainers_team` is already set.
