### ISSUE TITLE
Deck's build log lens should fail gracefully on large build-log.txt files.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#27497]
**What happened**:
A large (e.g. >26MB) `build-log.txt` cannot be rendered by Spyglass' build log lens due to the file size. The lens shows the spinning loading symbol forever.

**What you expected to happen**:
I don't expect the lens to be able to highlight and render such a large file, but it should fail more gracefully. We should display an error if the file is large enough to have no chance of rendering in time and if a timeout is reached that should be displayed on the front end rather than spinning the loading symbol forever.

**How to reproduce it (as minimally and precisely as possible)**:
Create a job with lots of standard output.

/help-wanted

**Comment by Priyankasaggu11929** [comment]
/assign

I will try to take a look at this.

**Comment by MaxHorstmann** [comment]
/assign

poking a little

**Comment by MaxHorstmann** [comment]
See PR ^^ several suggestions for a better fix. @cjwagner thoughts?

**Comment by BenTheElder** [comment]
moved to https://github.com/kubernetes-sigs/prow/issues/176
