### ISSUE TITLE
[Question] Prow releases, changelog 

### ISSUE THREAD

**Issue by emirot** [kubernetes/test-infra#27536]
**What would you like to be added**:
- Clearer releases information

It's hard to find release versions for prow and the features contained in them or maybe I don't know where to look.
It's not in this repo and on https://pkg.go.dev/k8s.io/test-infra/prow?tab=versions only a few are shown.

For example I have a system running an old version of prow (v20200824-984c253809 ):
-I don't know for instance if `max_concurrency` option is present in that release or not.
There is no tag or release or branch in that repo so I don't know how to check.

Also what is the status of prow is it still developed and maintained?

**Comment by chaodaiG** [comment]
/sig testing

New features and breaking changes are announced at https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md

**Comment by BenTheElder** [comment]
until prow is moved out of the test-infra mono repo to https://github.com/kubernetes-sigs/prow (a large lift... there's another issue about this) we won't likely be tagging the package / repo with versions.

there are date-based docs in the announcements doc chao mentioned and the published builds are date-sha tagged, it's not ideal but it's what we have without those larger changes.

> Also what is the status of prow is it still developed and maintained?

Prow is a core component of the Kubernetes project's workflow and SIG testing will ensure that it remains maintained for that level of usage, but I can't speak to the level of support for external usage, which is more up to the current maintainers's interest and time. AFAICT the answer is: yes.
