### ISSUE TITLE
failures-latest.json is no longer being populated

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/test-infra#27648]
**What happened**:

This URL returns `null`:

https://storage.googleapis.com/k8s-metrics/failures-latest.json

**What you expected to happen**:

The URL used to contain a list of jobs that have been consistently failing. I can't find references in the github org to anything that would update this file, so I'm not sure what is wrong exactly.

**Comment by BenTheElder** [comment]
https://testgrid.k8s.io/sig-testing-misc#metrics-kettle

**Comment by BenTheElder** [comment]
it's failing because the big query table is too old again cc @spiffxp @MushuEE

**Comment by BenTheElder** [comment]
kettle is probably stuck again #25658

**Comment by BenTheElder** [comment]
Since [leaving EngProd](https://twitter.com/BenTheElder/status/1551670320423059456) I no longer have access to k8s-gubernator, I think someone with access just needs to kill the pod and let it restart.

We could probably automate periodically restarting it and get pretty far on that 😂

**Comment by michelle192837** [comment]
I've got access to k8s-gubernator, the issue is credentials apparently. Rotating them now since they're past expiration.

**Comment by michelle192837** [comment]
Cluster credentials rotated, but looks like kettle is having other issues after that:

```
WARNING: Could not open the configuration file: [/root/.config/gcloud/configurations/config_default].
ERROR: (bq) You do not currently have an active account selected.

Please run:
 $ gcloud auth login
to obtain new credentials.

If you have already logged in with a different account:
 $ gcloud config set account ACCOUNT
to select an already authenticated account to use.
```

**Comment by michelle192837** [comment]
Okay cool, looks like it's fine after some time of doing nothing (or someone else doing a mysterious fix 🤔 ). Think this is good for now.

**Comment by spiffxp** [comment]
/reopen
I'd like for us to hold this open until https://storage.googleapis.com/k8s-metrics/failures-latest.json is populated

**Comment by BenTheElder** [comment]
yeah, the job is still failing, i'm surprised kettle hasn't caught up by now if it's back on its feet

**Comment by michelle192837** [comment]
Thanks, that's a good point 😅 

Kettle logs have some errors with failing to parse particular files, but it seems to be doing work. Sampling of the errors (these all happen repeatedly in the last few hours):

```
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.googleapis.com. Connection pool size: 10

Traceback (most recent call last):
  File "/kettle/update.py", line 87, in <module>
    main()
  File "/kettle/update.py", line 50, in main
    call(f'time python3 make_db.py --buckets buckets.yaml --junit --threads {THREADS}')
  File "/kettle/update.py", line 44, in call
    raise OSError('invocation failed')
OSError: invocation failed

ERROR:root:failed to get tests for pull-aws-ebs-csi-driver-e2e-single-az/1559897961905786880

ERROR:root:Failed to decode request for https://www.googleapis.com/storage/v1/b/kubernetes-jenkins/o/logs/post-test-infra-upload-testgrid-config/1560337334568751104/finished.json
```

**Comment by spiffxp** [comment]
Not going to try and troubleshoot it right now but worth noting kettle is getting continually evicted as well.
```
$ k get pods
NAME                              READY   STATUS    RESTARTS   AGE
kettle-cc9cbb879-2lrss            0/1     Evicted   0          14h
kettle-cc9cbb879-5tcb9            1/1     Running   2          175m
kettle-cc9cbb879-hn966            0/1     Evicted   0          29h
kettle-cc9cbb879-jtkb5            0/1     Evicted   0          7h34m
kettle-cc9cbb879-mwpvg            0/1     Evicted   0          15h
kettle-cc9cbb879-nl42t            0/1     Evicted   0          9h
kettle-cc9cbb879-plbmq            0/1     Evicted   0          4h22m
kettle-cc9cbb879-z75zp            0/1     Evicted   0          18h
$ k get pod kettle-cc9cbb879-plbmq -o=yaml
# ...
status:
  message: 'The node was low on resource: memory. Container kettle was using 47954516Ki,
    which exceeds its request of 0. '
  phase: Failed
  reason: Evicted
  startTime: "2022-10-05T19:18:40Z"
```

Without looking deeper at all (no time today) I'm going to assume it's making progress on populating builds each time, but not getting to the "up and running, streaming from GCS pubsub" stage.

If it's still like this tomorrow and apparent that it's not making any progress, I can try looking deeper.

**Comment by michelle192837** [comment]
Oh thanks for catching that Aaron! (I'm going to be out a lot of tomorrow but I'm happy to pair on taking a look if you want).

Think it's worth turning on vertical autoscaling for this pod? Now that you point it out, whatever limits it has by default seem wrong.

**Comment by michelle192837** [comment]
Trying some adjustments to the pod/node pool, hopefully this'll get evicted less.

**Comment by michelle192837** [comment]
Cool, looks like https://storage.googleapis.com/k8s-metrics/failures-latest.json populates now!

**Comment by spiffxp** [comment]
Using https://storage.googleapis.com/k8s-triage/index.html as a check, it does indeed show failures as recently as today, so I _think_ we are current

That said, logs looking this make me question if we're up and running, or just caught up
```
297.95user 426.89system 1:15:45elapsed 15%CPU (0avgtext+0avgdata 8383764maxresident)k
76168616inputs+153208outputs (59major+4511974minor)pagefaults 0swaps
incremental progress gen #0
Upload complete.
Warnings encountered during job execution:

b'Error while reading data, error message: JSON parsing error in row starting at position 236244343: Parser terminated before end of string'

b'Error while reading data, error message: JSON parsing error in row starting at position 252399872: Parser terminated before end of string'

b'Error while reading data, error message: JSON parsing error in row starting at position 427541907: Parser terminated before end of string'

b'Error while reading data, error message: JSON parsing error in row starting at position 439661343: Parser terminated before end of string'

b'Error while reading data, error message: JSON parsing error in row starting at position 461004362: Parser terminated before end of string'

Waiting on bqjob_r7d46ea6722ca91ab_00000183af7afdc3_1 ... (86s) Current status: DONE
```

Let's hold this open until tomorrow and see if data remains up to date

**Comment by spiffxp** [comment]
/assign
(since I'm keeping an eye on it, but ❤️ @michelle192837 for doing the actual work)

**Comment by dims** [comment]
thanks @michelle192837 and @spiffxp

**Comment by spiffxp** [comment]
/close
Still seeing current data this morning, calling this done. Thanks @michelle192837 !

**Comment by BenTheElder** [comment]
thank you!!
