### ISSUE TITLE
PR with "Change requested" leads to Tide repeatedly attempting MERGE

### ISSUE THREAD

**Issue by sdowell** [kubernetes/test-infra#27750]
**What happened**:

For a Github PR that has passed all checks but has the `Change requested` state, Tide repeatedly attempts to MERGE but fails (presumably rejected by Github due to the `Change requested` state).

**What you expected to happen**:

I would expect Tide to be aware of the `Change requested` state and that it is blocking - and therefore not try to perform MERGE.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a pull request
- Request changes on the PR
- Pass all other checks (e.g. presubmits, lgtm, approve, etc)
- Observe that Tide repeatedly attempts to perform MERGE and fails

**Please provide links to example occurrences, if any**:

Here is an example PR and tide history:
- https://github.com/GoogleContainerTools/kpt-config-sync/pull/210
- https://oss.gprow.dev/tide-history?repo=GoogleContainerTools%2Fkpt-config-sync&branch=main&pull=210

**Anything else we need to know?**:
N/A

**Comment by jihoon-seo** [comment]
We might add some logic to Tide:
- [List reviews for a pull request](https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#list-reviews-for-a-pull-request)
- Check the `state` field of each review
- Do not try to merge when there is any `CHANGES_REQUESTED` state

**Comment by petr-muller** [comment]
We could also thing about handling the "Tide wants to merge but GitHub forbids it" situation in general. "Changes requested" is just one of the [branch protection mechanisms](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#about-branch-protection-settings) that can prevent merging.

**Comment by smg247** [comment]
> 

We recently encountered a situation where `tide` was unable to merge a PR due to the merge method not being allowed on the repo. As far as the user was aware, tide was just stuck. There was a log message like:
```
Tide needs to be configured to use the 'rebase' merge method for this repo or the repo needs to allow merge commits: Merge commits are not allowed on this repository.
```
We need to figure out a way to surface stuff like this to users on the 'PR Status' page, if not as a message on the PR itself.

**Comment by BenTheElder** [comment]
Prow moved out to it's own repo at https://sigs.k8s.io/prow

> I would expect Tide to be aware of the Change requested state and that it is blocking - and therefore not try to perform MERGE.

tide uses search queries to identify PRs, and pulling more state is expensive/slow and de-normalizing, I would expect "changes requested" to remove lgtm instead.

Kubernetes doesn't use blocking changes requested AFAIK, and we have limited bandwidth.

If you're still interested in this, please re-file in the prow repo.
