### ISSUE TITLE
PROW READMe Documentation , hyperlinks under the head "More Details" broken

### ISSUE THREAD

**Issue by miyadav** [kubernetes/test-infra#27778]
**What happened**:
Navigate to - https://pkg.go.dev/github.com/k8s-ci-robot/test-infra/prow#section-readme , click on links under the Head `More Details`
Getting 404 errors for all links.

**What you expected to happen**:
Navigate to the links successfully to read.

**How to reproduce it (as minimally and precisely as possible)**:
Go Here - https://pkg.go.dev/github.com/k8s-ci-robot/test-infra/prow#section-readme , click on Components , Plugins etc.
example error - https://github.com/k8s-ci-robot/test-infra/blob/d7867ec05b41/prow/prow/plugins/README.md ( 404ing)

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by alvaroaleman** [comment]
@miyadav you are looking at the godoc of a fork of test-infra, not sure how you ended up there but the correct link is https://pkg.go.dev/github.com/kubernetes/test-infra/prow#section-readme (notice the s/k8s-ci-robot/kubernetes/). There, the links are working from what I can tell.

/close
