### ISSUE TITLE
KeyError in scenarios/kubernetes_verify.py

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#2778]
Anago supports working on branches of the form [release-X.Y.Z](https://github.com/kubernetes/release/blob/master/docs/branching.md#branching-from-a-tag).

However, [tests on PRs targeting such a branch](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45905/pull-kubernetes-verify/30103/) fail like this:

```
I0516 12:38:52.104] Call:  /var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py --branch=release-1.6.3 --script=./hack/jenkins/verify-dockerized.sh
W0516 12:38:52.128] Traceback (most recent call last):
W0516 12:38:52.128]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 108, in <module>
W0516 12:38:52.128]     main(ARGS.branch, ARGS.script, ARGS.force)
W0516 12:38:52.128]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 61, in main
W0516 12:38:52.128]     tag = VERSION_TAG[BRANCH_VERSION.get(ver, ver)]
W0516 12:38:52.129] KeyError: '6.3'
```

Because this script does not expect three-part versions in release branch names:

https://github.com/kubernetes/test-infra/blob/2fb2060/scenarios/kubernetes_verify.py#L57

**Comment by fejta** [comment]
So we need to change `\.\d+` to `(\.\d+)+`? Any chance you can send a PR with the fix?
/assign @enisoc 

Or feel free to assign it back to me if you don't want to.
