### ISSUE TITLE
Document the meaning of all the control labels used by the submit queue

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#2780]
I.e. the ones at https://submit-queue.k8s.io/#/info

**Comment by mml** [comment]
I have a couple PRs in flight that merely add debug logging.  They are to help with one of the "biggest flakes" flakes.  Is there a `queue/*` label appropriate for these?

**Comment by fejta** [comment]
Awesome, thanks for adding that debugging PR! 

With batched merges &c the queue depth should be tiny, so please don't use `queue/*` labels as it just slows down the system. Eventually we plan to eliminate all of them.

**Comment by kargakis** [comment]
Seems fixed.
