### ISSUE TITLE
go.k8s.io/triage is clustering stack traces for kubernetes/kubernetes

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#27829]
**What happened**:

The failure text that is clustered together by go.k8s.io/triage has become (I suspect) less useful since ginkgo v2 was introduced into kubernetes/kubernetes

Compare the top failure cluster from https://storage.googleapis.com/k8s-triage/index.html?date=2022-07-01 (before ginkgo v2):
<img width="1105" alt="Screen Shot 2022-10-27 at 5 31 08 PM" src="https://user-images.githubusercontent.com/49258/198422006-f41abb95-14a1-4dde-b814-7c1efc8da43f.png">

To the top failure cluster in https://storage.googleapis.com/k8s-triage/index.html?date=2022-08-01 (after ginkgo v2):
<img width="1095" alt="Screen Shot 2022-10-27 at 5 29 02 PM" src="https://user-images.githubusercontent.com/49258/198421868-c53a3656-17bd-4fe5-97b4-8940da983863.png">

**What you expected to happen**:

For actual failure messages to be clustered together rather than stack traces

**Anything else we need to know?**:

The way data ends up on triage:
- junit.xml files land in GCS
- kettle parses the junit.xml files and stores results into k8s-gubernator:build bigquery tables (e.g. k8s-gubernator:build:all)
- triage queries k8s-gubernator:build:all for failures in the past 2 weeks, and clusters together the failure text

I suspect this is kettle incorrectly parsing XML produced by ginkgo v2. So not something that can retroactively fixed.  It is highly unlikely I'm going to have time to fix this.

So I would ask:
- do folks still find triage useful as is?
- if not, would it be possible to revert the changes made to junit.xml output from kubernetes/kubernetes e2e tests, so that we get failure text instead of stack traces?

/area triage
/area kettle

**Comment by spiffxp** [comment]
/sig testing
/area kettle
/area triage

FYI @pohly @aojea @chendave

**Comment by chendave** [comment]
I guess kettle should change it's way to parse the junit, get the failure reason from `message` attribute from `failure` element, something like this: https://github.com/GoogleCloudPlatform/testgrid/pull/838?

**Comment by pohly** [comment]
Prior discussion: https://app.slack.com/client/T09NY5SBT/C09QZ4DQB/thread/C09QZ4DQB-1664275370.463659

**Comment by pohly** [comment]
The question that I had in that Slack discussion for which the answer is still uncertain: do we want to cluster just by failure text or by failure text + stack backtrace? We can do the former now because ginkgo separates them.

The advantage is that the text that needs to be queried becomes smaller. However, the tool already was able to handle backtraces (including changes in line numbers) and the function names may help to identify a specific problem. I prefer to combine them, also when considering that we then don't need to make assumptions about what is where in the XML.

> if not, would it be possible to revert the changes made to junit.xml output from kubernetes/kubernetes e2e tests, so that we get failure text instead of stack traces?

Ginkgo v2 is now arguably more compliant with the (vague) JUnit spec. I don't think we should go back.

**Comment by pohly** [comment]
I think test-infra/kettle just [strips `system-out`](https://github.com/kubernetes/test-infra/blob/cb743c494eb5404ef9703a96122c6075f43f2234/kettle/make_db.py#L283-L294), then [dumps the entire remaining JUnit XML](https://github.com/kubernetes/test-infra/blob/cb743c494eb5404ef9703a96122c6075f43f2234/kettle/model.py#L104-L111) into the Big Query database. Does that sound right?

First observation: we already prune "system-out" when writing JUnit XML. It was used by Ginkgo V2 for additional information (like measurements) that we don't need. What's left is the log output of the test in "system-err" ([example](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/112923/pull-kubernetes-conformance-kind-ga-only-parallel/1585551102152019968/artifacts/junit_01.xml). Should kettle also strip that out?

For the failure text, I think the relevant code is here:
https://github.com/kubernetes/test-infra/blob/cb743c494eb5404ef9703a96122c6075f43f2234/kettle/make_json.py#L187-L193

Interpretation of the data happens for example in https://github.com/kubernetes/test-infra/blob/0b34ebbeafd76c48efa140c2d5b5f539c6bcbf9d/triage/summarize/text.go#L51-L110

Regarding "do folks still find triage useful as is?": just clustering by backtrace is not useful. Where I am undecided is how complete the failure message should be, i.e. how much information should it have.

When I look at https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112923/pull-kubernetes-conformance-kind-ga-only-parallel/1585551102152019968, I want the overview page to give me relevant information (i.e. a pod dump as in this case, although it could be formatted better), not just an "Expected an error to have occurred.  Got: nil". But if we put too much information there, clustering will not work anymore.

**Comment by pohly** [comment]
> Should kettle also strip that [system-err] out?

I'm confused about why it strips `system-out`. My initial guess was "because it stores the full JUnit", but that's not what then happens. Only selected fields get stored. So `system-out` should already get ignored by kettle, even without explicit code for it?!

**Comment by pohly** [comment]
See https://github.com/kubernetes/test-infra/issues/27829 for a potential solution.

**Comment by spiffxp** [comment]
>So system-out should already get ignored by kettle, even without explicit code for it?!

The thing to understand about kettle's code base is that it's been unstaffed for a long time.  Kettle also takes a very long time to deploy (well, come to steady state after loading everything).  So we've kind of adopted a "touch it as little as possible" stance to try and avoid breaking it.  There have been some efforts to make the codebase more reliable but we've never been able to sustain the effort.

>Where I am undecided is how complete the failure message should be, i.e. how much information should it have.

Me too.  We haven't had any time to look into how we might measure the effectiveness of clustering. I'm leaning towards "less is better" but I'll take this discussion over to https://github.com/kubernetes/test-infra/pull/27831

**Comment by spiffxp** [comment]
/reopen
I'm not sure merged PR's to kettle auto-deploy.  We should hold this open to see what the actual effect is in triage

**Comment by pohly** [comment]
It looks like this is resolved:

```
680 test failures (43 today) look like

test/e2e/storage/nfs_persistent_volume-disruptive.go:153
Jun 17 02:11:18.886: pod "pvc-tester-d54dz" is not Running: timed out while waiting for pod disruptive-pv-1165/pvc-tester-d54dz to be running
test/e2e/storage/nfs_persistent_volume-disruptive.go:185

```

And

```
711 test failures (40 today) look like 

test/e2e/windows/host_process.go:422
Jun 17 07:48:39.019: Expected
    <v1.PodPhase>: Failed
to equal
    <v1.PodPhase>: Succeeded
test/e2e/windows/host_process.go:480
```

**Comment by spiffxp** [comment]
Yeah just came here to say it should be up and running now, ref: https://github.com/kubernetes/test-infra/pull/27831#issuecomment-1310907343

I'm not happy with the amount of time triage is taking to update clusters, which maybe the stack traces are exacerbating, but I don't have time to look into it

Per https://github.com/kubernetes/test-infra/issues/27869#issuecomment-1310902224 expect triage to fall up to 6h out of date
