### ISSUE TITLE
Prow: add a REST API

### ISSUE THREAD

**Issue by listx** [kubernetes/test-infra#27824]
**What would you like to be added**:

I want the Prow service cluster to expose a web API so that I can programmatically trigger Prow jobs (or anything else I want to do in the future). We can currently programmatically trigger via Pub/Sub but doing it through an API would make it easier for clients.

**Why is this needed**:

Increase interoperability with other tools/services.

EDIT: I am currently working on this feature (I filed this issue for transparency).

Here is the [design doc](https://docs.google.com/document/d/1v77jp1Nb5C2C2-PdV02SGViO9CyZ9SvNxCPOHyIUQeo/edit?usp=sharing). You must be a member of dev@kubernetes.io to be able to comment on it.

https://github.com/kubernetes/test-infra/issues/27824#tasklist-block-6b8168fc-921e-4168-a743-0bca85ccc61c

**Comment by chaodaiG** [comment]
@roberthbailey fyi

**Comment by chaodaiG** [comment]
@RobertKielty fyi

**Comment by petr-muller** [comment]
I'm curious, isn't kubernetes API basically the thing? In OpenShift we have many things that programmatically trigger Prowjobs, and they all do it via kube API (by creating `Prowjob` resources in the cluster).

**Comment by listx** [comment]
> I'm curious, isn't kubernetes API basically the thing? In OpenShift we have many things that programmatically trigger Prowjobs, and they all do it via kube API (by creating `Prowjob` resources in the cluster).

The use case is for clients that do not have access to the Prow service cluster to trigger Prow jobs, just like how we have Sub set up (but instead of Pub/Sub we want to use HTTP).

**Comment by BenTheElder** [comment]
Are there any design details ..? 

Access to create prowjob CRs directly is a potential security risk and it's not obvious why both Pub/Sub and the Kubernetes API cannot be used.

**Comment by listx** [comment]
> Are there any design details ..?

I'll share a doc soon.
 
> Access to create prowjob CRs directly is a potential security risk

Right.

> and it's not obvious why both Pub/Sub and the Kubernetes API cannot be used.

Agreed. Any new Prow API work will not try to deprecate existing methods/solutions.

**Comment by listx** [comment]
Updated the original comment to include a link to the design doc.

**Comment by upodroid** [comment]
This is a nice feature to have. I wrote something that pulls info from the Prow but I'm parsing yaml instead of json. :( 

https://github.com/knative/test-infra/blob/main/tools/provenance-generator/pkg/parse.go#L90

**Comment by listx** [comment]
Relevant: [upstream issue](https://github.com/GoogleCloudPlatform/esp-v2/issues/674)

**Comment by jianzhangbjz** [comment]
Any updates? Thanks!

**Comment by listx** [comment]
This is currently blocked on figuring out how to test ESPv2 locally. Based on the upstream issue I linked it appears that the ESPv2 container must always talk to the Google Service Control API. We could try to run the [mock Service Control server](https://github.com/GoogleCloudPlatform/esp-v2/blob/master/tests/env/components/mock_service_control.go) but I haven't explored this due to other priorities.

**Comment by chizhg** [comment]
@listx Is there a doc for how to use the Prow APIs? I checked the links in this issue but didn't find the instruction doc.

**Comment by listx** [comment]
See https://docs.prow.k8s.io/docs/components/optional/gangway/
