### ISSUE TITLE
'undefined' should be highlighted in the the gubernator display

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/test-infra#2783]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/45903/pull-kubernetes-unit/30908/build-log.txt

gives an example of a hard to analyze output, the key text is:

```
W0516 12:44:55.020] # k8s.io/kubernetes/pkg/api/testing
W0516 12:44:55.021] pkg/api/testing/fuzzer.go:429: undefined: AzureDataDiskKind
W0516 12:44:55.021] pkg/api/testing/fuzzer.go:430: undefined: AzureSharedBlobDisk
```

But it wasn't highlighted.

**Comment by fejta** [comment]
/assign @rmmh 

Can we just disable all the highlighting and truncating? It has never provided me with any value.

**Comment by cblecker** [comment]
@fejta I just opened #2784 to add this to the list of highlight words

Speaking from the point of a newer contributor, highlighting words like "failed" and "error" really helps to pull out the important stuff when we have, in this case, an 1800+ line log file.

**Comment by fejta** [comment]
Agree, but the problem is that 99% of the lines with error and failed in them are red herrings.

**Comment by rmmh** [comment]
Yeah, and 99.9% of them without error and failed in them are totally useless. People that spend time reading logs seem to like the feature :)

**Comment by fejta** [comment]
And then misdiagnose the problem because we hide the actual error and highlight something useless like "couldn't delete network that doesn't exist"

**Comment by rmmh** [comment]
There are a lot of errors beyond just "undefined" that can cause the build to fail. We either need a more complete list of them, or we need some better marking when 'make test' fails.

For comparison, the bazel run of the same PR is easy to diagnose: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45903/pull-kubernetes-bazel/21331/

**Comment by rmmh** [comment]
There's some gap between what I see running 'make test' and what happens when the CI runs 'make test' that adds to the problems.

I see output like:
```
rmmh@rmmh:~/k8s$ make test
Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0516 15:56:31] Running tests without code coverage
# k8s.io/kubernetes/cmd/genutils
cmd/genutils/genutils.go:28: undefined: asdf
FAIL    k8s.io/kubernetes/cmd/genutils [build failed]
ok      k8s.io/kubernetes/cmd/gke-certificates-controller/app   7.625s
ok      k8s.io/kubernetes/cmd/hyperkube 1.463s
ok      k8s.io/kubernetes/cmd/kube-apiserver/app/options        0.760s
ok      k8s.io/kubernetes/cmd/kube-apiserver/app/preflight      0.048s
```

Which would be highlighted correctly.

**Comment by cblecker** [comment]
@fejta: The regex you call out above would work for go build issues, but I could see that highlighting lots of things from bash scripts and the like that we don't intend to be highlighted.

**Comment by fejta** [comment]
That's fine. It is already pretty clear we're not concerned much with false positive highlighting.

**Comment by brendandburns** [comment]
Personally, I find the highlighting useful (even with the noise)

I'd prefer to see gradual improvement in highlighting/truncation, rather than elimination.

Put another way, at least 90% of the time, when I open up the page, the right thing is highlighted.

In the cases where it's not, it's often one of 2-3 patterns that could be blacklisted.

**Comment by fejta** [comment]
Good feedback, thanks!
