### ISSUE TITLE
Prow assign plugin doesn't pick up organization membership

### ISSUE THREAD

**Issue by lbernick** [kubernetes/test-infra#27852]
**What happened**:

We are unable to /assign org members to pull requests.

**What you expected to happen**:

/assign @username will assign username to the pull request

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

- https://github.com/tektoncd/community/pull/866#issuecomment-1297324254
- https://github.com/tektoncd/community/pull/858#issuecomment-1297329264

Both these users are in the [TektonCD org](https://github.com/orgs/tektoncd/people).

**Anything else we need to know?**:

Tekton uses an inrepo prow config. Our prow dashboard is at https://prow.tekton.dev/. 

- our [prow config](https://github.com/tektoncd/plumbing/blob/main/prow/config.yaml)
- our [plugins](https://github.com/tektoncd/plumbing/blob/main/prow/plugins.yaml)
- our [prow installation](https://github.com/tektoncd/plumbing/blob/main/prow/prow.yaml)

**Comment by lbernick** [comment]
Actually looks like this repo is associated with sig testing, and sig k8s-infra is for migration to the CNCF.. please feel free to reassign since I'm not sure where this issue should go

/sig testing

**Comment by BenTheElder** [comment]
when prow comments:
> @lbernick: GitHub didn't allow me to assign the following users: xinruzhang.

That means it tried to assign the user and got a github API error that those users could not be assigned.

https://github.com/kubernetes/test-infra/blob/ee1e7c845bb25177944bb5de37545f007f529059/prow/plugins/assign/assign.go#L192

**Comment by lbernick** [comment]
Thanks @BenTheElder for your response and relabeling! Would it be possible to have the plugin comment display more granular information about the GitHub API error received? (I checked the controller logs and didn't see anything more informative than the message you linked.) Failing that I can try to figure out what API call the plugin is making and try it out myself-- but I'm not sure if I have the necessary permissions/creds access and if you have debugging suggestions that are a bit easier I will probably try those first.

**Comment by BenTheElder** [comment]
Assigning people to an issue takes write permission to the repo, I think.
I don't have access to this myself anymore and I can't definitively state what changes to prow would be approved either, but I think if there is more detail available the owners would probably be willing to include it in the comment, but I'm also not sure that the API does return more info, AIUI reading the code the error is basically "I couldn't assign this user" on the github side as well.

**Comment by BenTheElder** [comment]
It's possible this was a bug on github's side, we've seen some interesting things before where indexes are seemingly not up to date.

**Comment by lbernick** [comment]
> Assigning people to an issue takes write permission to the repo, I think.

I believe our credentials have write permissions to the repo, since we do successfully use the assign plugin on this repo w/ folks in our [maintainers/collaborators list](https://github.com/tektoncd/community/blob/eaa7738f5289b5a71dc5c3bd6c3e739ad90ce7f1/org/org.yaml#L463-L528) for this repo ([example](https://github.com/tektoncd/community/pull/820#issuecomment-1252597887)). The issue seems to be primarily with org members that aren't maintainers or collaborators for the repo. Reading [github docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users#about-issue-and-pull-request-assignees) it says "You can assign multiple people to each issue or pull request, including yourself, anyone who has commented on the issue or pull request, anyone with write permissions to the repository, and organization members with read permissions to the repository." Our repos are public (I would interpret this as "everyone has read permissions"), but I wonder if the assign plugin is checking to see whether the org members specifically have some additional permissions?

**Comment by BenTheElder** [comment]
> but I wonder if the assign plugin is checking to see whether the org members specifically have some additional permissions?

so from the code link above, that error message is posted when github returns an error. prow doesn't make any checks, it just tries to assign via the API and posts this comment if the API call fails due to github reporting the users couldn't be assigned.

the logic in the handler is just constructing the API call and handling the error from the call, it would be inefficient to make additional API calls to check the status of the user(s)

**Comment by lbernick** [comment]
ah of course-- that makes sense, sorry, I should have looked a bit more closely at the link.

I realized the issue is that we default to "None" permissions for org members instead of "Read" permissions. Truly a case of just needing to read the docs :)

**Comment by BenTheElder** [comment]
glad you found it! 😅

**Comment by BenTheElder** [comment]
Thanks for clarifying that 😄
