### ISSUE TITLE
Prow issue: Keep hitting a flake

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#2787]
I keep hitting this flake: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45721/pull-kubernetes-federation-e2e-gce/5138/. Noticed that most of the recently updated PRs are failing on this one. See also: https://github.com/kubernetes/kubernetes/issues/42072.

I mentioned this in  the sig-testing channel as well and wasn't sure if I should be mentioning in the above issue or create a new one in this repo but thought it would be better to document it here. :)

**Comment by fejta** [comment]
Moving issue to kubernetes repo and labelling with sig-federation

**Comment by nikhita** [comment]
@fejta Thank you!
