### ISSUE TITLE
Failed ci: Pod can not be created: create pod test-pod ... in cluster default: Unauthorized

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/test-infra#27919]
**What happened**:

``` console
Pod can not be created: create pod test-pod ... in cluster default: Unauthorized
```

Yesterday the CI was fine and today it reports this error.
I see that the ci image was updated yesterday by #27913, may be is this the reason?

**What you expected to happen**:

CI works normally

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes-sigs%2Fkwok+author%3Awzshiming+head%3Afeat%2Fcni

**Anything else we need to know?**:

#27913

**Comment by liggitt** [comment]
this is impacting multiple jobs, do we know what changed that caused this, and can that change be reverted?

**Comment by sbueringer** [comment]
Thank you very much!!
