### ISSUE TITLE
Cleanup duplicated periodics for cloud-provider-gcp

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/test-infra#27928]
**What should be cleaned up or changed**:

Periodic CI jobs for cloud-provider-gcp are duplicated due to adding/testing `--test-args=--enabled-volume-drivers=gcepd`.

We need to validate if the change has effect, and remove periodic duplication when not needed.

**Provide any links for context**:

Follow up to #26890

/assign @mattcary

**Comment by mattcary** [comment]
/remove lifecycle-stale

The in-tree gcepd tests are still being skipped, I'll dig into why that is. With the pd csi driver installed they should be run, as is supposed to be happening in the "with gce-pd" tests.

https://testgrid.k8s.io/provider-gcp-periodics#E2E%20Full%20-%20Cloud%20Provider%20GCP%20with%20GCE-PD%20-%20master&include-filter-by-regex=sig-storage

**Comment by mattcary** [comment]
/remove-lifecycle stale

It's still on my queue to go over these tests. We also have the default storage class tests that may be running in-tree to clean up.
