### ISSUE TITLE
ensure triage changes are approved by contribex leads

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#28021]
**What happened**:

https://github.com/kubernetes/test-infra/issues/27951 merged with lazy consensus.
This does not meet the bar contribex has set for workflow changes.

https://github.com/kubernetes/community/blob/master/sig-contributor-experience/charter.md#cross-cutting-and-externally-facing-processes

**What you expected to happen**:

We should ensure contribex signs off on workflow changes.

We have prior art with the prow plugin config and OWNERS for that file.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

Discussed with @cblecker, we will put in guard rails here.

/sig contributor-experience

**Comment by BenTheElder** [comment]
cc @kubernetes/sig-testing-leads FYI, I should have remembered, but some of you are new and newly granted approval over this repo, some changes require the above linked process.

FYI @dims @ameukam @thockin as well as additional test-infra root approvers by way of SIG K8s Infra oncall
https://github.com/kubernetes/test-infra/blob/f712886d6df2e18b8f9a4ff3b286fcec1ff2b8f3/OWNERS#L15


And additional root approvers in test-infra-oncall (Google) @listx @chases2 @mpherman2 @chaodaiG 
https://github.com/kubernetes/test-infra/blob/f712886d6df2e18b8f9a4ff3b286fcec1ff2b8f3/OWNERS#L14

**Comment by BenTheElder** [comment]
Prior art:
https://github.com/kubernetes/test-infra/blob/f712886d6df2e18b8f9a4ff3b286fcec1ff2b8f3/config/prow/OWNERS#L1-L4

This should probably be a contribex-leads alias and be scoped to the plugins file instead of all prowjobs. The same thing should be applied to the triage bot config.

**Comment by BenTheElder** [comment]
cc @nikhita

**Comment by nikhita** [comment]
/assign @MadhavJivrajani 
(ref: https://kubernetes.slack.com/archives/C1TU9EB9S/p1683818540227269)
