### ISSUE TITLE
Automate check_projects.py somehow

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#2802]
#2800 

/assign

**Comment by fejta** [comment]
1) Add a presubmit check that uses service account A to ensure that service account B is an owner of the all known projects
2) Create a postsubmit prow job that runs as service account B that ensures that all the expected grants are applied to known projects

**Comment by fejta** [comment]
However, we may want to run this internally for Google owned projects, since this is where we define the list of expected grants.

**Comment by krzyzacy** [comment]
external and internal has different default configs humm... maybe we need both

**Comment by fejta** [comment]
Seems less useful post boskos
