### ISSUE TITLE
prow documentation is difficult to follow now

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#28038]
1) we no longer have even a terse readme / landing page for "what is this directory" at all under https://github.com/kubernetes/test-infra/tree/master/prow

2) To find docs for a particular aspect now requires following many links and is not obvious, for example to find pod-utilities docs the path went from prow/README.md => pod-utilites.md to this:

    1. https://github.com/kubernetes/test-infra/tree/master/prow
    2. https://github.com/kubernetes-sigs/prow/blob/main/site/content/en/docs/Legacy%20Snapshot/prow/README.md
    4. https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md
    5. https://github.com/kubernetes-sigs/prow/blob/main/site/content/en/docs/Legacy%20Snapshot/prow/pod-utilities.md
    
    Probably we can cut out the intermediate linking back to the "deprecated" files at least?

3) We now have fancy rendered version (yay!), but none of these links reference that.

cc @listx

**Comment by listx** [comment]
> Probably we can cut out the intermediate linking back to the "deprecated" files at least?

Yes. Cross-referencing https://github.com/kubernetes-sigs/prow/issues/4#issuecomment-1311161805 which also suggested the same.

**Comment by jihoon-seo** [comment]
Hello all.

> We now have fancy rendered version (yay!), but none of these links reference that.

We might update the links in the tombstone files to point the rendered version, not the markdown file with GitHub UI, like:

```diff
[new migrated
-location](https://github.com/kubernetes-sigs/prow/tree/main/site/content/en/docs/Legacy%20Snapshot/prow/README.md).
+location](https://docs.prow.k8s.io/docs/legacy-snapshot/prow/readme/).
```

> Probably we can cut out the intermediate linking back to the "deprecated" files at least?

I opened a PR https://github.com/kubernetes-sigs/prow/pull/26 that might partially resolve this. PTAL!
