### ISSUE TITLE
Pinger should handle both IssueComment, PullRequestComment, and IssueEvent

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#2806]
Currently, pinger (under `mungegithub/mungers/matchers/comment/`) only handle IssueComment. It should handle PullRequestComment too.

**Comment by grodrigues3** [comment]
@apelisse says he wrote a PR that deals with this in an elegant way

**Comment by apelisse** [comment]
For the reference, https://github.com/kubernetes/contrib/pull/1659

**Comment by crimsonfaith91** [comment]
/assign @apelisse 
Thanks for helping out! :)
