### ISSUE TITLE
k8s-bot - how does it check whitelist?

### ISSUE THREAD

**Issue by techtonik** [kubernetes/test-infra#2812]
https://github.com/kubernetes/test-infra/tree/master/prow#bots-home - that's all documentation about bot behavior. How does it check who to react to? Where is the best place to document it?

**Comment by xiangpengzhao** [comment]
This doc list bot commands: https://github.com/kubernetes/test-infra/blob/master/commands.md. But seems like it doesn't answer your first question.

**Comment by techtonik** [comment]
Added to https://github.com/kubernetes/test-infra/pull/2816

**Comment by kargakis** [comment]
It is using the Github API to determine whether the commenter is a member of the org from where the notification comes from.

https://developer.github.com/v3/orgs/members/#check-membership
