### ISSUE TITLE
kops e2e testing is running two different tests

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#2814]
Example: https://github.com/kubernetes/kops/pull/2621

Two different e2e jobs are being called.  One is actually being ran, pull-kops-e2e-kubernetes-aws, and another never runs and is called "Jenkins Kubernetes AWS e2e".

This is blocking any merges for kops currently.

"Jenkins Kubernetes AWS e2e" is not automatically starting with org members, and running the bot command starts pull-kops-e2e-kubernetes-aws.

cc: @zmerlynn @fejta

**Comment by zmerlynn** [comment]
It looks like the "context" names provided by prow changed (@spxtr?). I'm fixing the lock on the branch.

**Comment by zmerlynn** [comment]
FWIW, the configuration that I'm fixing is here: https://github.com/kubernetes/kops/settings/branches/master (I believe you have access, @chrislovecnm ?)

**Comment by zmerlynn** [comment]
kubernetes/kops#2621 is still missing a review, but is green otherwise. Closing.

**Comment by chrislovecnm** [comment]
@zmerlynn no access ... admin only
