### ISSUE TITLE
k8s-bot doesn't tell me a joke...

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#2815]
@k8s-bot ok to test
otherwise
@k8s-bot tell me a joke :smiling_imp:

I ran above commands here: https://github.com/kubernetes/kubernetes/pull/46197#issuecomment-303013550

k8s-ci-bot just told me that `@xiangpengzhao: you can't request testing unless you are a kubernetes member.`. It didn't tell me a joke... Is it because there was an emoji in the command?

/cc @fejta

**Comment by xiangpengzhao** [comment]
@k8s-bot tell me a joke

**Comment by techtonik** [comment]
Related to #2812.

**Comment by xiangpengzhao** [comment]
For this issue, I think it's because the joke site is down. In the [code](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/yuks/yuks.go#L37), bot tries to get real joke from https://tambal.azurewebsites.net/joke/random. I visit this url in my browser, it gives me a ERR_TUNNEL_CONNECTION_FAILED error. We might need a more stable joke site...

**Comment by ixdy** [comment]
/assign @fejta 
P0 issue! :)

**Comment by krzyzacy** [comment]
@fejta please also find a funnir joke site instead, that's the real issue here :-)

**Comment by xiangpengzhao** [comment]
yeah, another joke site would be great!

and we can also modify the code a bit like this:

in the below code, if j.readJoke has an error, we don't return but set the resp to a default joke or something like "I don't have jokes now, you can tell me a joke if you have". WDYT? @fejta @ixdy @krzyzacy
```
	resp, err := j.readJoke()
	if err != nil {
		return err
	}
```

**Comment by fejta** [comment]
@k8s-bot tell me a joke

**Comment by fejta** [comment]
@k8s-bot tell me a joke

**Comment by sanadHaj** [comment]
@k8s-ci-robot tell me a joke
