### ISSUE TITLE
Append `X-GitHub-Api-Version` header to GitHub REST API calls

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/test-infra#28161]
/area prow

**What would you like to be added**:

Append `X-GitHub-Api-Version` header to GitHub REST API calls; like:

```
$ curl --header "X-GitHub-Api-Version:2022-11-28" https://api.github.com/zen
```

**Why is this needed**:

https://docs.github.com/en/rest/overview/api-versions?apiVersion=2022-11-28

> You must specify which REST API version to use whenever you make a request to the REST API.

> The GitHub REST API is versioned. The API version name is based on the date when the API version was released. For example, the API version 2022-11-28 was released on Mon, 28 Nov 2022.
> 
> Any breaking changes will be released in a new API version. Breaking changes are changes that can potentially break an integration. Breaking changes include:

Currently it seems that GitHub accepts REST API calls without `X-GitHub-Api-Version`,
but there might be possibility that someday GitHub refuses those calls.

And this change will explicitly clarify the GitHub API version that the [Prow GitHub client](https://github.com/kubernetes/test-infra/blob/master/prow/github/client.go) is using.

---

We might update Prow GitHub client to append the header to all REST API calls by adding some codes in `doRequest()`:
https://github.com/kubernetes/test-infra/blob/ca6fa9cca4d94116d2ec09dcfbb7ed73bb05bff7/prow/github/client.go#L1171-L1207

**Comment by Atharva-Shinde** [comment]
Hey, mind if I work on this :)

**Comment by petr-muller** [comment]
@Atharva-Shinde go for it!
