### ISSUE TITLE
Bots battle

### ISSUE THREAD

**Issue by techtonik** [kubernetes/test-infra#2817]
@k8s-ci-robot vs @k8s-bot - what's the difference?

Also, interesting to look at all bots in the garage, @k8s-cherrypick-bot, @k8s-merge-robot etc.

**Comment by ixdy** [comment]
@k8s-bot was one of the first, and I created it for Jenkins. I'd imagined that we'd use it for everything bot-related, but we ended up creating separate accounts for everything instead. Despite it being what everyone mentions, nothing actually uses that account anymore.

**Comment by techtonik** [comment]
It would be nice to have those species documented somewhere. @k8s-bot still works and responds to command, right? It just doesn't change issues - directs commands to other bots and their to their specific functions (CI, merge), is that right?

Is there a label for all bot related issues?

**Comment by xiangpengzhao** [comment]
Seems like @k8s-bot has retired?
