### ISSUE TITLE
Tide status on chosen PRs

### ISSUE THREAD

**Issue by Noamrok** [kubernetes/test-infra#28210]
**What would you like to be added**:

Hi,
It would be awesome if you can add the feature to apply Tide only to some PRs.
Now it is enabled per org/repo, on the whole repo, but we use the automerge ability only on some of the PRs in the repo, so the PRs we don't want to automerge have the Tide status pending on yellow and developers just ignore it.
You can add filtering based on PRs labels using regex.

**Why is this needed**:
the PRs which arent automerged will become cleaner and less confusing for the developers.

**Comment by petr-muller** [comment]
Personally, I'm not a fan of having that feature, feels like it adds complexity for a use case that does not sound too common.
