### ISSUE TITLE
/help command to list bot commands

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#2823]
There should be a `/help` command that lists bot commands and their usage.

**Comment by grodrigues3** [comment]
Let's see what listing all of them looks like.  If that's too much, just list some of the more commonly used ones (the triage ones and retrigger test ones for example) and link to the rest.

**Comment by techtonik** [comment]
I would also add some telegram interface to play and debug the bot with `/help` and friends to avoid tracker pollution.

**Comment by spiffxp** [comment]
Given that we have the bot(s) link to commands.md, do we still think this is needed?

**Comment by crimsonfaith91** [comment]
@spiffxp `/help` is not needed anymore. i will close this. :)
