### ISSUE TITLE
Testing for hotfix branches (release-X.Y.Z)

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#2824]
For the v1.6.4 release, we used a feature of anago to [branch from a previous patch release](https://github.com/kubernetes/release/blob/master/docs/branching.md#branching-from-a-tag), creating a `release-1.6.3` branch to exclude changes on the `release-1.6` branch since v1.6.3.

Unlike regular `release-X.Y` branches, the urgent nature of hotfix releases means we can't go through the usual flow to set up CI on the new branch. We should have a documented workflow for release managers to trigger one-off testing on `release-X.Y.Z` branches, based on the jobs that run for `release-X.Y`.

cc @david-mcmahon @ixdy

**Comment by fejta** [comment]
@kubernetes/sig-release-feature-requests 
Do we still need this?

**Comment by enisoc** [comment]
Yes, as long as we still intend to support hotfix releases, by which I mean those that exclude changes that already went into the release branch since the latest patch release.
