### ISSUE TITLE
How to deal with image push timeouts for multiple arch builds?

### ISSUE THREAD

**Issue by damemi** [kubernetes/test-infra#28258]
Hi, we have an image push postsubmit job for Descheduler at https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-descheduler.yaml

[This job](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-descheduler-push-images) builds images for multiple arches, and over the past year or so we've noticed an increasing number of timeouts leading to failed image builds. The timeouts don't seem to be due to any issue other than simply taking a long time to build each image.

We've tried increasing the timeout a few times but even at [30 minutes](https://github.com/kubernetes-sigs/descheduler/pull/1023) we're still getting failures (the latest increase comes after bumping our k8s dependencies, maybe related).

It seems clear that we should parallelize these builds, which we tried in https://github.com/kubernetes-sigs/descheduler/pull/1019 by making each arch its own gcb build stage. However, this didn't seem to have any effect.

Is there a recommended way to split up these builds? Any docs or examples would be helpful, thanks

cc @a7i @ingvagabund @knelasevero

**Comment by damemi** [comment]
/sig testing
(not sure which sig this falls under, since it's about the automated CI jobs I assumed sig-testing)

**Comment by BenTheElder** [comment]
> It seems clear that we should parallelize these builds, which we tried in https://github.com/kubernetes-sigs/descheduler/pull/1019 by making each arch its own gcb build stage. However, this didn't seem to have any effect.

GCB stages run in serial unless you set waitFor:

https://cloud.google.com/build/docs/configuring-builds/configure-build-step-order

**Comment by a7i** [comment]
> GCB stages run in serial unless you set waitFor:

Hi @BenTheElder as noted in the Issue, we tried this and it didn't reduce the duration https://github.com/kubernetes-sigs/descheduler/pull/1019

**Comment by BenTheElder** [comment]
GCB also has different machine sizes, but it takes time to spin up custom machine sizes.

I recommend doing multiple architectures in parallel using buildx and pushing a single multi-arch image directly, FWIW, but that may not improve cold build times.
