### ISSUE TITLE
Prow issue: Bad invalid commit message for npm dependencies

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/test-infra#28257]
I got this error message on:
https://github.com/kubernetes-client/javascript/pull/924

```
[Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.
```

But in npm libraries, the `@` character is used to indicate an organization, even the default kubernetes client uses it `@kubernetes/client-node`

**Comment by brendandburns** [comment]
Also, there's no way to disable this from re-applying repeatedly _very_ annoying.

See: https://github.com/kubernetes-client/javascript/pull/926

**Comment by BenTheElder** [comment]
`@kubernetes/client-node` could be a valid reference to a GitHub team like `@kubernetes/sig-testing`, which we *do not want* to let in a merged commit, because they will be pinged *every time* that commit is merged *even in forks* which is something you cannot disable in GitHub :/

The bot also blocks `fixes #1234` because of similar behavior (closing the issue) that happens even in people's forks.

Previously: https://github.com/kubernetes/test-infra/issues/21534, we asked GitHub if we could alter this comment

**Comment by BenTheElder** [comment]
/sig contributor-experience
(I think changing this behavior would count as a variant on #28021)

**Comment by mrbobbytables** [comment]
+1 to Ben's comment. I don't think this is something we want to change globally at least. 
We have provided feedback to GitHub about this in the past, but others see it as a positive thing =/

I could potentially see a repo+user exception, but i'd defer to sig-testing and the prow folk on it.

**Comment by brendandburns** [comment]
How about a per-user exception? All of the PRs in question are sent by @dependabot which is unlikely to include any other users in it's comments.

**Comment by brendandburns** [comment]
This continues to be a problem for the Javascript client as `@` syntax is quite prevalent in Javascript library names.

**Comment by BenTheElder** [comment]
Sorry about that, I agree we should add a user-exception for depdenabot. 

There's been some churn and I'm not sure who's most active on Prow at the moment, but if current owners agree I think we can file a help-wanted to add this and someone will pick it up. cc @chaodaiG @colew @listx

**Comment by listx** [comment]
@cjwagner not colew

**Comment by MadhavJivrajani** [comment]
Migrated issue: https://github.com/kubernetes-sigs/prow/issues/193
