### ISSUE TITLE
Migrate stuff out of e2e-runner.sh

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#2829]
We should update kubernetes_e2e.py to use kubetest flags directly:

- [x] `--up`
- [x] `--down`
- [x] `--dump`
- [x] `--extract`
- [x] `--skew`
- [x] `--save`
- [x] `--check-leaked-resources`
- [x] `--federation`
- [x] `--deployment`
- [x] `--test`
- [x] `--test_args`
- [x] `--upgrade_args`
- [x] `--kubemark`
- [x] `--charts`
- [x] `--perf-tests`
- [x] `--timeout`
- [x] `--publish`
- [x] `${E2E_OPT}`

/cc @krzyzacy @ixdy

**Comment by fejta** [comment]
I'll take:
`--publish`, `--timeout`, `--extract` and `--skew`

**Comment by krzyzacy** [comment]
/assign 
I'll start with:
`--up`, `--down`, `--test`, and `--federation`, `--kubemark`, `--charts`, `--perf-tests`

**Comment by fejta** [comment]
FYI this should all be done, although the kops scenario needs to be merged with kubernetes_e2e.py

**Comment by karataliu** [comment]
`e2e-runner.sh` shall also be removed?

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/pull/8636
