### ISSUE TITLE
lgtm logic for checking for permission looks bad and may have unexpected side-effect of assigning PR

### ISSUE THREAD

**Issue by dobesv** [kubernetes/test-infra#28335]
**What happened**:

I found that users were automatically assigned to a PR if they approved it, but I didn't really understand why

While investigating I found some kind of strange logic in the LGTM plugin:

```
	// either ensure that the commenter is a collaborator or an approver/reviewer
	if !isAuthor && !isAssignee && !skipCollaborators {
		// in this case we need to ensure the commenter is assignable to the PR
		// by assigning them
		log.Infof("Assigning %s/%s#%d to %s", org, repoName, number, author)
		if err := gc.AssignIssue(org, repoName, number, []string{author}); err != nil {
			log.WithError(err).Errorf("Failed to assign %s/%s#%d to %s", org, repoName, number, author)
		}
	} else if !isAuthor && skipCollaborators {
		// in this case we depend on OWNERS files instead to check if the author
		// is an approver or reviewer of the changed files
		log.Debugf("Skipping collaborator checks and loading OWNERS for %s/%s#%d", org, repoName, number)
		ro, err := loadRepoOwners(gc, ownersClient, org, repoName, number)
		if err != nil {
			return err
		}
		filenames, err := getChangedFiles(gc, org, repoName, number)
		if err != nil {
			return err
		}
		if !loadReviewers(ro, filenames).Has(github.NormLogin(author)) {
			resp := "adding LGTM is restricted to approvers and reviewers in OWNERS files."
			log.Infof("Reply to /lgtm request with comment: \"%s\"", resp)
			return gc.CreateComment(org, repoName, number, plugins.FormatResponseRaw(body, htmlURL, author, resp))
		}
	}
```

Issues here:

- Why does it assign the PR to the user who approved it exactly when checking collaborators?  It's strange and unexpeted
- If assigning the PR is actually desirable, why not do it when checking the owners file?
- Why is the OWNERS file only consulted if `skip_collaborators` is `true`?  Shouldn't it work both ways (either in OWNER or a collaborator)?
- None of this is documented in the little help blurb for the plugin

**Comment by BenTheElder** [comment]
/sig contributor-experience

> Why does it assign the PR to the user who approved it exactly when checking collaborators? It's strange and unexpeted

We assign approvers to PRs they approved. They may need to do further review if the PR is pushed again.
Why is this strange and unexpected?

Changing this would require approval from contributor experience through the workflow changes process.


> Why is the OWNERS file only consulted if skip_collaborators is true? Shouldn't it work both ways (either in OWNER or a collaborator)?

https://github.com/kubernetes/test-infra/blob/0de7d151067774eb85a87f41377d490c16369a0e/prow/plugins/plugin-config-documented.yaml#L555-L558

**Comment by dobesv** [comment]
> Why is this strange and unexpected?

It seems strange to have a side-effect as part of a check

> # SkipCollaborators disables collaborator cross-checks and forces both 
> # the approve and lgtm plugins to use solely OWNERS files for access 
> # control in the provided repos. 

This doesn't explain why OWNERS is not used *UNLESS* skip collaborators is set.

**Comment by dobesv** [comment]
I have a feeling this isn't going to a priority, though.  I just decided not to use this plugin since I can use github's built-in approval system and it works fine with tide.

**Comment by BenTheElder** [comment]
> This doesn't explain why OWNERS is not used UNLESS skip collaborators is set.

skip_collaborators is intended to bypass using collaborators

We allow people to note their approval if they are a collaborator even if they are not in a single OWNERS file, it just won't cause the PR to be `approved` label without a covering set of approvers.

**Comment by dobesv** [comment]
> all OWNERS are expected to be collaborators

If that's the case, why doesn't it assign to the collaborator when `skip_collaborators` is on, or at least try to?
