### ISSUE TITLE
Prow failing to assign reviewers with message about not being an org member despite being org members

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#28357]
**What happened**:

> @BenTheElder: GitHub didn't allow me to request PR reviews from the following users: alvaroaleman, chaodaiG, stevekuznetsov.
>
> Note that only [kubernetes members](https://github.com/orgs/kubernetes/people) and repo collaborators can review this PR, and authors cannot review their own PRs.

https://github.com/kubernetes/test-infra/pull/27034#issuecomment-1371436208

**What you expected to happen**:

Valid org members should be assigned

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

https://github.com/kubernetes/test-infra/pull/27034#issuecomment-1371436208

**Anything else we need to know?**:

/area prow

**Comment by BenTheElder** [comment]
The message really means the API call failed (see e.g. https://github.com/kubernetes/test-infra/issues/27852), but the question is why is the API call failing?

Someone with access will have to check prow logs

**Comment by michelle192837** [comment]
Not seeing any relevant errors in the k8s prow logs, or incidents from the GitHub API status page. Continuing to take a look.

**Comment by michelle192837** [comment]
Apologies for the PR noise!
- cc'ing myself (and other cc's) on that PR fails
- assigning myself works
- cc'ing myself on another PR works (https://github.com/kubernetes/test-infra/pull/28358)

**Comment by BenTheElder** [comment]
Can we see what github is returning?

**Comment by michelle192837** [comment]
Not so far as I know, but I think I can add additional logging for this case.

**Comment by michelle192837** [comment]
Yay, got an example of the error on that PR. (Still not observing it on anything else.

```
jsonPayload: {
  author: "michelle192837"
  component: "hook"
  event-GUID: "011efa50-9b5b-11ed-9d11-fd423e690dd2"
  event-type: "issue_comment"
  file: "k8s.io/test-infra/prow/plugins/assign/assign.go:155"
  func: "k8s.io/test-infra/prow/plugins/assign.handle"
  level: "info"
  msg: "Failed to add reviewer(s) to kubernetes/test-infra#27034: could not request a PR review from the following user(s): 
michelle192837; status code 422 not one of [201], body: {"message":"Validation Failed","errors":["Could not add requested reviewers to pull request."],"documentation_url":"https://docs.github.com/rest/reference/pulls#request-reviewers-for-a-pull-request"}."
  org: "kubernetes"
  plugin: "assign"
  pr: 27034
  repo: "test-infra"
  url: "https://github.com/kubernetes/test-infra/pull/27034#issuecomment-1400924455"
}
```

Not finding a lot on "Validation failed" so far, but it is a different error from the other examples I'm seeing of 422's (e.g. it's not the same error as when someone legitimately can't be added to the PR due to not being a collaborator or being the PR author).

**Comment by BenTheElder** [comment]
Interesting, maybe we need to file a ticket with GitHub? Sounds like it could be a bug on their end 🤔

**Comment by petr-muller** [comment]
Yeah, I searched a bit too and I haven't found anything useful. Ticket with GH seems reasonable.
