### ISSUE TITLE
Make Prow approve plugin less noisy (optionally)

### ISSUE THREAD

**Issue by dobesv** [kubernetes/test-infra#28362]
**What would you like to be added**:

As soon as a PR is opened Prow posts a message on the PR saying it is NOT APPROVED and which OWNERS files to look at and so on.  GitHub then emails the person who opened the PR and notifies them in the github app and slack and so on.

It would be nice to dial back the noise here while still getting the /lgtm and /approve workflow.

**Why is this needed**:

Prow will be easier to adopt if it is less annoying.

**Likely Solution**

Adding some options to the plugin to specify which notifications we want to display would solve the issue.

If there's a concern about users not knowing whether the PR is NOT APPROVED or they aren't sure which OWNERS files apply maybe there could be a command like `/check-approve-status` which tells it to post/update that notification.

**Comment by petr-muller** [comment]
Personally I'm not a fan of increasing code and configuration complexity to implement this.

**Comment by dobesv** [comment]
Actually I realized that I can just not use this plugin and use github's approval system instead, tide supports it.  So the whole point of this plugin is to be noisy like this, perhaps.
