### ISSUE TITLE
Cluster API CI alert mailing list is reused across providers

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes/test-infra#28364]
**What should be cleaned up or changed**:
CAPI CI alert mailing list  `sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io`  is used by core CAPI + couple of providers: 

- **[CAPDigital Ocean](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-digitalocean/cluster-api-provider-digitalocean-periodics.yaml#L31)**
- **[CAPG](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-gcp/cluster-api-provider-gcp-periodics-main.yaml#L80)**
- **[CAPO](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-openstack/cluster-api-provider-openstack-periodics.yaml#L45)** 
jobs, which makes the email alerts a bit noisy time to time (people getting alerts that are not relevant, e.g CAPI maintainers receiving alerts for CAPDO failing jobs).  

This has been brought up during the CAPI office hours on 4.1.2023 and discussed in the community. This issue is to discuss the problem with the maintainers of the above providers and ask them to move to a separate mailing list and use the current one only for core Cluster API.

**Provide any links for context**:
The maintainers of the above providers could either:

-  add a new group for their provider in k8s.io (see example of CAPA: https://github.com/kubernetes/k8s.io/pull/3396) and modify their jobs accordingly in this repo (example of CAPA: https://github.com/kubernetes/test-infra/pull/25267)
- drop the mailing list usage from their jobs in case the alerts are not needed and it was just a copy/paste of some early jobs. Because, AFAIU none of the provider maintainers are in the [current alert list](https://github.com/kubernetes/k8s.io/blob/main/groups/sig-cluster-lifecycle/groups.yaml#L27-L44).

**Comment by furkatgofurov7** [comment]
/cc @sbueringer @fabriziopandini @CecileRobertMichon @ykakarap 
also tagging relevant provider maintainers (please tag others if I missed some of them):
/cc @cpanato @richardcase @mdbooth @jichenjc

**Comment by sbueringer** [comment]
Thx for driving this.

This will significantly reduce noise for folks on the mailing list which are using it for core ClusterAPI :tada: 

+1 from my side

**Comment by richardcase** [comment]
+1 from my side as well.

In CAPA, we decided to do this for exactly the reason @sbueringer mentions, to reduce noise. I'll make these changes for CAPG (fyi @cpanato).

**Comment by ykakarap** [comment]
@furkatgofurov7 Thank you for driving this. 
+1 for keeping a dedicated mailing list for Core CAPI and reducing the noise.

**Comment by cpanato** [comment]
+1

**Comment by furkatgofurov7** [comment]
Hey folks,

Thanks for moving this effort forward, and looks like all providers are good except CAPDO, where only updating jobs seem to be missing (CAPDO alert group is already up 🎉 ).
 @cpanato just checking if you want to take care of it as well, otherwise, I am happy to update the corresponding jobs with the new alert group.

**Comment by sbueringer** [comment]
Thx everyone!!
