### ISSUE TITLE
[RFC] Add functionality to manually trigger merge-ability checks

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/test-infra#28374]
**What would you like to be added**:

I'd like to propose extending the `needs-rebase` plugin to include a command that would help trigger a check for merge-ability.
Maybe something along the lines of `/check-needs-rebase`?

**Why is this needed**:

Today, the `needs-rebase` plugin runs on commit changes, additionally it also runs periodically ([by default](https://github.com/kubernetes/test-infra/blob/0b5b883367ae31d28d08670e4dd343f04bd0bc0e/prow/external-plugins/needs-rebase/main.go#L75) 24 hours) and currently [every 6 hours](https://github.com/kubernetes/test-infra/blob/0b5b883367ae31d28d08670e4dd343f04bd0bc0e/config/prow/cluster/needs-rebase_deployment.yaml#L42).

As a result, if a merge conflict occurs in PR A due to merging of PR B, but for whatever reason, PR B is reverted, PR A is now good to go, but tide will still block merge on `needs-rebase`. AFAIK (and please correct me if I'm wrong), we can now do one of 2 things:
1. Do a dummy update and re-trigger the plugin to remove the label. A big downside is that this also re-runs all of the CI.
2. Wait for the next cycle of when this plugin does a sweep.

It might not be a very far fetched scenario where this might happen to a PR that is fixing some tests and/or a bug and is considered important-soon or maybe even critical-urgent. Leaving this aside, and just from a perspective of a better user experience, it would help to have some way to re-trigger the `needs-rebase` plugin.

/sig testing contributor-experience

**Comment by AvineshTripathi** [comment]
I don't know if this is the correct issue to tell this ;) 

Something weird that happened to me in one of my comms PR, so I had a PR open for a while and before it was merged there was repo name change which was not resolved in the PR. I thought that github should have notified me with a conflict which was not the case(maybe this can be case of repo name change because of which this happened).

On examining the branch after fetching new commits I found that if the PR was merged without adding latest commits then a whole new directory would get created with my changes 
PR https://github.com/kubernetes/community/pull/6817

**Comment by MadhavJivrajani** [comment]
@sharmaansh21 👋🏼 
Leaving some context and pointers:
- The `needs-rebase` plugin currently runs in 3 scenarios:
  1. When a pull request is created or re-opened or what is known as a `synchronise` event (see [here](https://github.com/kubernetes/test-infra/blob/0b5b883367ae31d28d08670e4dd343f04bd0bc0e/prow/external-plugins/needs-rebase/plugin/plugin.go#L73))
  2.  Every some-time-period, it lists pull requests and checks for mergability (see [here](https://github.com/kubernetes/test-infra/blob/0b5b883367ae31d28d08670e4dd343f04bd0bc0e/prow/external-plugins/needs-rebase/main.go#L75))
  3. Every time a comment is posted on a PR (see [here](https://github.com/kubernetes/test-infra/blob/ca16ba134c1762c1fff11a8d219a5a80faad39ca/prow/external-plugins/needs-rebase/main.go#L189)).

(iii) is what I missed while creating this issue. However, issue comments are only processed through a cache, meaning the issue comment will not be processed if the issue is in the cache. I'd still like to have a command that bypasses the cache and forces a check. Although Kubernetes does not make use of the cache feature, it would definitely be nice to have a way to manually trigger a check.

- What now needs to be done is we need to handle a comment event (that's already done [here](https://github.com/kubernetes/test-infra/blob/46bc8bfb52eaed83da54e43663d078a15b89eaab/prow/external-plugins/needs-rebase/plugin/plugin.go#L82)) on pull requests (for a comment like `/check-needs-rebase`).
  - Every time we get a comment, we check if the comment matches a command regex ([example](https://github.com/kubernetes/test-infra/blob/0b5b883367ae31d28d08670e4dd343f04bd0bc0e/prow/plugins/lgtm/lgtm.go#L49)), if it does, we `handle` it. If it doesn't we check the cache and follow the usual flow.

**Comment by MadhavJivrajani** [comment]
I'm not sure this is needed anymore, we can revisit it if needed.
