### ISSUE TITLE
[prow] Why doesn't /close handle PRs?

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/test-infra#2839]
I'm trying to close a PR assigned to me. `/close` did not do anything.

https://github.com/kubernetes/test-infra/blob/27540b574f70e4c25847e55de75b2212a18ecbba/prow/plugins/close/close.go#L47

It looks like this is by design. Why?

**Comment by grodrigues3** [comment]
/assign @fejta

I think he wrote this

**Comment by cblecker** [comment]
+1. It would be great if `/close` also supported PRs.

**Comment by fejta** [comment]
/unassign

Actually this is one of the original plugins Joe wrote back in November!

**Comment by spxtr** [comment]
We could remove that constraint, even if only for consistency. Authors of PRs can close their own PRs, but authors of issues cannot close their own issues.

**Comment by grodrigues3** [comment]
> but authors of issues cannot close their own issues.
Clarification, author's of issues cannot close their own issues with `/close`. The github UI provides that capability.

**Comment by spxtr** [comment]
> Clarification, author's of issues cannot close their own issues with `/close`. The github UI provides that capability.

Other way around. Authors of issues cannot close their own issues with the UI.

**Comment by cblecker** [comment]
@spxtr I'm not sure that's true. I just checked an issue I've opened against a non k8s repo I have zero permissions to, and I have a "Close Issue" button right beside the green comment button near the bottom.

**Comment by grodrigues3** [comment]
![image](https://cloud.githubusercontent.com/assets/4854198/26650308/d79d25ac-45fd-11e7-905c-79539afbcfff.png)

Verified: Using a brand-new github account with no permissions in the repo, I can close my own issue.

**Comment by xiangpengzhao** [comment]
Yes authors can close their own issues but not PRs. ref:#2863

**Comment by cblecker** [comment]
authors can close their own PRs with the github UI. `/close` doesn't work on PRs at all.
