### ISSUE TITLE
build-and-push-k8s-at-golang-tip broken after bootstrap update

### ISSUE THREAD

**Issue by Argh4k** [kubernetes/test-infra#28544]
**What happened**:
After an update to the bootstrap image (removing python2), build-and-push-k8s-at-golang-tip sig-scalability prowjob started on a step `COPY RELEASE`

**What you expected to happen**:
Removing python2 from bootstrap image does not break  build-and-push-k8s-at-golang-tip prowjob

**How to reproduce it (as minimally and precisely as possible)**:
The job is on the testgrid: https://k8s-testgrid.appspot.com/sig-scalability-golang#build-and-push-k8s-at-golang-tip

**Please provide links to example occurrences, if any**:
Same as above 

**Anything else we need to know?**:
It looks like this might be caused by an issue with gsutil after python2 is removed. Looking at the failures it seems to fail at this step: https://github.com/kubernetes/release/blob/master/push-build.sh#L947

I've created a PR to rollback bootstrap image for this job back (https://github.com/kubernetes/test-infra/pull/28543), but I think we should understand what is going on here.

**Comment by Argh4k** [comment]
@aojea @BenTheElder can you have a look at it?

**Comment by aojea** [comment]
Most probably some tooling is still not python3 compatible and breaks

I see two jobs failing, the one you mention

https://k8s-testgrid.appspot.com/sig-scalability-golang#build-and-push-k8s-at-golang-tip

```
push-build.sh: DONE main on f6c1eaa9-9d75-11ed-b1bb-1299ca1e1805 Thu Jan 26 13:15:35 UTC 2023 in 1m0s
make: *** [Makefile:31: push] Error 2
make: Leaving directory '/home/prow/go/src/k8s.io/perf-tests/golang'
Run: ('make', '--directory=/home/prow/go/src/k8s.io/perf-tests/golang')
Traceback (most recent call last):
  File "/workspace/scenarios/execute.py", line 50, in <module>
    main(ARGS.env, ARGS.cmd + ARGS.args)
  File "/workspace/scenarios/execute.py", line 41, in main
    check(*cmd)
  File "/workspace/scenarios/execute.py", line 30, in check
    subprocess.check_call(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '--directory=/home/prow/go/src/k8s.io/perf-tests/golang')' returned non-zero exit status 2.
+ EXIT_VALUE=1
```


and the kubemark one https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-5000&width=20

```
2023/01/25 11:13:42 main.go:328: Something went wrong: encountered 1 errors: [error during /workspace/log-dump.sh /logs/artifacts gs://k8s-infra-scalability-tests-logs/ci-kubernetes-kubemark-gce-scale/1618036365394448384: exit status 1]
Traceback (most recent call last):
  File "/workspace/scenarios/kubernetes_e2e.py", line 723, in <module>
    main(parse_args())
  File "/workspace/scenarios/kubernetes_e2e.py", line 569, in main
    mode.start(runner_args)
  File "/workspace/scenarios/kubernetes_e2e.py", line 228, in start
    check_env(env, self.command, *args)
  File "/workspace/scenarios/kubernetes_e2e.py", line 111, in check_env
    subprocess.check_call(cmd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('kubetest', '--dump=/logs/artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--provider=gce', '--cluster=kubemark-5000', '--gcp-network=kubemark-5000', '--extract=ci/latest', '--gcp-node-image=gci', '--gcp-node-size=e2-standard-8', '--gcp-nodes=84', '--gcp-project-type=scalability-project', '--gcp-zone=us-east1-b', '--kubemark', '--kubemark-nodes=5000', '--metadata-sources=cl2-metadata.json', '--test_args=--ginkgo.focus=xxxx', '--test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh', '--test-cmd-args=cluster-loader2', '--test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true', '--test-cmd-args=--experimental-prometheus-disk-snapshot-name=ci-kubernetes-kubemark-gce-scale-1618036365394448384', '--test-cmd-args=--experimental-prometheus-snapshot-to-report-dir=true', '--test-cmd-args=--nodes=5000', '--test-cmd-args=--provider=kubemark', '--test-cmd-args=--report-dir=/logs/artifacts', '--test-cmd-args=--testconfig=testing/load/config.yaml', '--test-cmd-args=--testconfig=testing/huge-service/config.yaml', '--test-cmd-args=--testconfig=testing/access-tokens/config.yaml', '--test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml', '--test-cmd-args=--testoverrides=./testing/experiments/ignore_known_kubemark_container_restarts.yaml', '--test-cmd-name=ClusterLoaderV2', '--timeout=1080m', '--logexporter-gcs-path=gs://k8s-infra-scalability-tests-logs/ci-kubernetes-kubemark-gce-scale/1618036365394448384')' returned non-zero exit status 1
+ EXIT_VALUE=1
+ set +o xtrace
Cleaning up after docker in docker.
====================================
```

It is interesting, the job seems to be migrated but doesn't have the `decorate: true` option

**Comment by Argh4k** [comment]
Kubemark-5000 job runs twice a day (at 00:01 and 16:01 UTC) on the odd days of each month. So it just did not run after the rollback from @BenTheElder. I would focus on the [build-and-push-k8s-at-golang-tip](https://k8s-testgrid.appspot.com/sig-scalability-golang#build-and-push-k8s-at-golang-tip)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28543#issuecomment-1405298454

**Comment by BenTheElder** [comment]
@aojea those tracebacks just show that the executed command failed, they're not python bugs.

gcloud sdk has supported python3 since 2019.

**Comment by aojea** [comment]
Yeah, thanks for confirming .

I'm not able to understand what is failing, then

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip/1618704126743416832 is running 🤞 

#28545 + #28546

**Comment by BenTheElder** [comment]
re: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1618277961440432128

Can't explain that yet, but when we updated these images we also picked up a new gcloud sdk, and I don't think the bootstrap image had been upgraded for some time.

I see:
> Uploading '/tmp/tmp.IauZYi4pIk/logs' to 'gs://k8s-infra-scalability-tests-logs/ci-kubernetes-kubemark-gce-scale/1618277961440432128'
> CommandException: One or more URLs matched no objects.
AccessDeniedException: 403 prow-build@k8s-infra-prow-build.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist).

Which sounds like an issue unrelated to python2 removal and possibly unrelated to the images at all.

**Comment by BenTheElder** [comment]
`ci-build-and-push-k8s-at-golang-tip` is back to breaking on:

```
Checking whether gs://k8s-infra-scale-golang-builds/ci/v1.23.0-alpha.2.111+5112d03e83f04b already exists: OK
- Copying artifacts to gs://k8s-infra-scale-golang-builds/ci/v1.23.0-alpha.2.111+5112d03e83f04b: FAILED
Signal ERR caught!
Traceback (line function script):
1621 main ../release/push-build.sh
```

It seems pretty unlikely that gsutil broke just for this specific `cp` call, but the timing is certainly suspicious. Chronologically on pass/fail boundaries:

✅  https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip/1616410561514311680
- image: gcr.io/k8s-staging-test-infra/bootstrap:v20221021-5771e8efb3 (digest: `sha256:4bf4459fbd1349804158e7645b4f515c1e7aa4b230b929df71d0fd75d25caa98`)

:x: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip/1616470960989278208
- image: gcr.io/k8s-staging-test-infra/bootstrap:v20230120-da7bf474ce (digest: `sha256:88e45751be728958c78981f2886b5f4fbf8878f37678c447ae08f336e6c7e7e0`)
- broken due to python vs python3 (`python` not found in path)
  - this issue since fixed by these scripts using python3 and being python3 compatible, and further by eliminating the usage of scenarios scripts from this job

✅ https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip/1617862474009153536
- image: gcr.io/k8s-staging-test-infra/bootstrap:v20221021-5771e8efb3 (digest: `sha256:4bf4459fbd1349804158e7645b4f515c1e7aa4b230b929df71d0fd75d25caa98`)


:x: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip/1618704126743416832
- image: gcr.io/k8s-staging-test-infra/bootstrap@sha256:88e45751be728958c78981f2886b5f4fbf8878f37678c447ae08f336e6c7e7e0
- broken due to mysterious gsutil cp error

5771e8efb3 is rather old, from October 20th, 2022 (and amusingly about a different python2to3).

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28553 will pin `ci-build-and-push-k8s-at-golang-tip` to the known passing image from  https://github.com/kubernetes/test-infra/commit/5771e8efb360fc6188c1f43c80b68d434efc83e3

**Comment by BenTheElder** [comment]
I think this is https://github.com/GoogleCloudPlatform/gsutil/issues/1663 (bug in `gsutil -m` in 5.18, hopefully fixed in 5.19, which is not in gcloud releases yet)

```console
$ docker run --rm --entrypoint=gsutil gcr.io/k8s-staging-test-infra/bootstrap:v20221021-5771e8efb3 version
gsutil version: 5.14

$ docker run --rm --entrypoint=gsutil gcr.io/k8s-staging-test-infra/bootstrap:v20230120-da7bf474ce version
gsutil version: 5.18

$ docker run --rm --entrypoint=gsutil gcr.io/k8s-staging-test-infra/bootstrap:v20230126-f1a4452ec1 version
gsutil version: 5.18
```

We can probably roll forward when that version is packaged in gcloud or else install a different gsutil version manually.

Expected to be in gcloud 416 per linked thread

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28554 should pin bootstrap to gcloud 413 with gsutil 5.17

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28553 + https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-build-and-push-k8s-at-golang-tip/1618732470478311424

prove it's related to the image change

https://github.com/kubernetes/test-infra/pull/28554 should fix the image

**Comment by BenTheElder** [comment]
should be resolved

**Comment by Argh4k** [comment]
Thank you @BenTheElder for driving this.
