### ISSUE TITLE
automatically re-run PR tests that fail due to flakes

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#2855]
Rough idea: if a PR test job fails, look at the failure reason(s) and compare against the top N [aggregated failures](https://storage.googleapis.com/k8s-gubernator/triage/index.html). If there's a match, consider the failure a flake and automatically re-run the test.

(We probably need some sort of big red button if the infra falls over for some reason. Or automatic limiting, or something like that.)

**Comment by spxtr** [comment]
@apelisse mentioned this a while ago.

**Comment by apelisse** [comment]
We over-zealously run tests. Especially for documentation/minor changes.

In *my* ideal world, we would run only the tests that are needed, and we would then, indeed, re-run failing tests a couple of times.

**Comment by spxtr** [comment]
Agreed. To start, we should try to resurrect #2414. I just haven't had time to do it. Maybe make that a help-wanted thing?

**Comment by apelisse** [comment]
It's very unclear what went wrong with #2414 though. Could you explain in the PR what happened and why it was reverted?

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/3764
