### ISSUE TITLE
Prow Fails if local DNS is not ready on startup

### ISSUE THREAD

**Issue by dobesv** [kubernetes/test-infra#28623]
**What happened**:

A number of jobs are failing with an error like:

```
ssh: Could not resolve hostname github.com: Try again
fatal: Could not read from remote repository.
```

This happens in different cases, but the one I am dealing with now is that it happens if the pod is launched on a node that just started and the node local DNS has not initialized.  Normally this is not a problem for kubernetes pods as they are built to be resilient against service failures, including DNS, and will retry or exit and be restarted.

Prow however does not restart these pods and does not retry the operation in case of DNS failure.

**What you expected to happen**:

Prow jobs should retry some number of times, either as part of the checkout job logic or just by exiting the pod and the pod is recreated, like how things are normally done in kubernetes.

**How to reproduce it (as minimally and precisely as possible)**:

It seems tricky to reproduce, but if you are able to run a prow job where DNS is not available, you will see it fail immediately instead of retrying.

**Comment by dobesv** [comment]
A workaround I am trying is to set `dnsPolicy: Default` on the prow jobs as this will use the host network DNS instead of cluster DNS, so it is almost certainly up and running as it is used to fetch the docker images.

It would be nice if I could set dnsPolicy globally for all prow jobs, maybe in `presets` ?

**Comment by droslean** [comment]
@dobesv Thanks for opening this issue. 

On first look, we could allow the user to specify the DNS policy under plank's global configuration.
ref: https://github.com/kubernetes/test-infra/blob/master/prow/config/config.go#L621-L686

or in general, if there can be a global configuration for all [podSpecs](https://pkg.go.dev/k8s.io/api/core/v1#PodSpec) that we generate on each prowjob, it will give the users more flexibility to control their prowjobs depending on their infrastructure. Node selectors, affinity, tolerations, and other infrastructure-important configurations, could be controlled globally by the users for all prowjobs.

My proposal will resolve more than this issue describes.
@petr-muller @BenTheElder @cjwagner @stevekuznetsov WDYT?

**Comment by BenTheElder** [comment]
> or in general, if there can be a global configuration for all [podSpecs](https://pkg.go.dev/k8s.io/api/core/v1#PodSpec) that we generate on each prowjob, it will give the users more flexibility to control their prowjobs depending on their infrastructure. Node selectors, affinity, tolerations, and other infrastructure-important configurations, could be controlled globally by the users for all prowjobs.

Yeah, in the past we would've seriously considered for example changing ndots on all our pods if it weren't such a massive config diff. The presets mechanism could be updated to support more fields, seeing as it no longer needs to match kubernetes (the kubernetes concept it matched was removed ...).

**Comment by petr-muller** [comment]
I see the `dnsPolicy` setting more like a workaround for the original issue. Feels like we could be a bit more robust and perhaps retry taking to GH.

**Comment by dobesv** [comment]
Yeah, actually I had opened a different issue w.r.t. `dnsPolicy` for that reason: https://github.com/kubernetes/test-infra/issues/28633

**Comment by dobesv** [comment]
Probably just if the checkout job had a retry with backoff it would do the trick, basically copy kubernetes retry logic for pods.

Although at that rate maybe just using kubernetes built-in restarting system might make sense, if whatever drawbacks it has that caused prow to disable it could be overcome in another way.

**Comment by BenTheElder** [comment]
> I see the dnsPolicy setting more like a workaround for the original issue. Feels like we could be a bit more robust and perhaps retry talking to GH.

This is fair, but it's worth noting that for jobs not trying to talk to in-cluster-services and just using prow as a general CI, doing the full 5-tier search path is slow and flaky and tuning ndots is a general useful knob for workloads that don't need it. Even for things that are talking within the cluster, you don't need ndots to be so high if you just use the full service path including namespace.

We've had to employ the FQDN workaround (if you call `foo.bar.baz.cluster.local.` then there's no search) which is harder to propagate to all network calls. (kubernetes test-infra currently does this for boskos)

It's a useful workaround that applies to more than just this issue, DNS calls in kubernetes can be flaky in part due to all the extra search traffic.

**Comment by dobesv** [comment]
> It's a useful workaround that applies to more than just this issue, DNS calls in kubernetes can be flaky in part due to all the extra search traffic.

Maybe it deserves its own issue, though, otherwise if this is closed with some other workaround your idea will be lost.

**Comment by dobesv** [comment]
e.g. https://github.com/kubernetes/test-infra/issues/28633

**Comment by dobesv** [comment]
> Using FQDN for clone hosts would probably help a lot

Can you clarify how that would help?  The issue here is that the `git clone` command fails because DNS is not ready.  

Some ideas I have that might work:

1. Retry the `git clone` if it fails, up to some limit, to allow for networking and DNS issues
2. Have the clonerefs wrapper wait for connectivity to github.com to be established (up to some time limit) before running `git` commands
3. Have another initContainer that runs prior to clonerefs that waits for network access to github.com to be working (could also wait for some other services in the future if that became interesting)

Any idea which of these might be acceptable if I was to work on one?  Or maybe something else?

**Comment by BenTheElder** [comment]
> The issue here is that the git clone command fails because DNS is not ready.

I don't think it's true that there's no DNS ready, this looks like it's flaking on in-cluster DNS which has an extensive search path that causes flakes.

Node local DNS takes over and replaces the existing DNS. If that's happening before ready then we should fix nose local DNS addon instead.

I think retry with back off up to a timeout would be accepted but what you're describing also sounds broken at the cluster level (vs the known flakiness of high ndots + search paths and the load on coreDNS, which node local DNS also attempts to alleviate). cc @aojea

**Comment by dobesv** [comment]
> If that's happening before ready then we should fix nose local DNS addon instead.

What I *think* I'm seeing is that the node local dns is just running as a normal pod, and there's no logic to prevent other pods from launching prior to node local dns being ready to serve requests.  Are you aware of a mechanism that should prevent pods from being started on a node prior to the node local DNS being ready?

**Comment by BenTheElder** [comment]
> What I think I'm seeing is that the node local dns is just running as a normal pod, and there's no logic to prevent other pods from launching prior to node local dns being ready to serve requests. Are you aware of a mechanism that should prevent pods from being started on a node prior to the node local DNS being ready?

kube-proxy often runs as a pod and so do CNI overlays, it could be done by tainting the node until it is ready.

But before node-local DNS runs, there should already be the DNS service that it replaces, something is wrong if that's not working.

The other thought I had is maybe node-local DNS starts intercepting DNS before it's actually listening?

**Comment by aojea** [comment]
This conversation is a bit complex to follow are we talking about install time of the cluster?
The DNS implementation is very specific of this cluster, but usually, it is deployed as a Service and the IP of this Service configured on the kubelet to set it as default nameserver for pods.
Services only forward traffic to Endpoints with Pods that are ready (there are certain fields that can override this behavior, but do not seem relevant here), if the no pod for the DNS service is ready , then the cluster has a bigger problem

**Comment by BenTheElder** [comment]
@aojea agreed ... I re-read this as during node bootstrap with node local DNS cache installed, rather than the cluster level DNS:
> [...] if the pod is launched on a node that just started and the node local DNS has not initialized [...]

For cluster level DNS we've seen issues with lots of search requests  => https://github.com/kubernetes/test-infra/issues/29317 and related issues + opting to install node local DNS (kubernetes's prow still runs the GKE node local DNS addon AFAIK).

With node local DNS, you can imagine during node bootstrap there is some issue where DNS is getting routed to node-local DNS but that service is not ready yet ... Which I would personally consider a bug in node local DNS.

Regardless, prow should be resilient to DNS flakes. Right now you may have to aw

**Comment by dobesv** [comment]
Yeah, I actually don't know how node-local-dns takes over the caching, I had assumed it went along the lines of putting localhost:53 in resolv.conf and letting node-local-dns listen on that port on each node.  It sounds like there might be more at play that is beyond my understanding currently.

Still, it would be nice to improve the resiliency of the prow utilities against temporary DNS issues.

**Comment by dobesv** [comment]
I was looking around and found there is actually already retry logic for the cloning logic:

https://github.com/kubernetes/test-infra/blob/master/prow/pod-utils/clone/clone.go#L198

Maybe just a matter of getting it to retry for longer?

**Comment by dobesv** [comment]
Possible fix here:

https://github.com/kubernetes/test-infra/pull/29324

**Comment by BenTheElder** [comment]
AFAICT node-local-dns installs iptables rules to capture DNS requests on startup but I didn't get much past that before getting interrupted. https://github.com/kubernetes/test-infra/pull/29324 seems reasonable.

**Comment by dobesv** [comment]
> AFAICT node-local-dns installs iptables rules to capture DNS requests on startup

Ah, interesting way of doing things.  Thanks for clarifying that.
