### ISSUE TITLE
/close should be able to close PR

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#2863]
I comment `/close` in my PR, nothing happens. Hope that it should be able to close PR, not only issue.

see https://github.com/kubernetes/kubernetes/pull/46478#issuecomment-304172240

**Comment by xiangpengzhao** [comment]
As per the code : https://github.com/kubernetes/test-infra/blob/master/prow/plugins/close/close.go#L47

Why don't we allow to close PR by `/close`?

```
	// Only consider open issues and new comments.
	if ic.Issue.State != "open" || ic.Issue.IsPullRequest() || ic.Action != "created" {
		return nil
	}
```

**Comment by krzyzacy** [comment]
Isn't it you can click the close button on your own PR?

**Comment by xiangpengzhao** [comment]
Yes, Sen, I can close my PR by clicking the close button. I thought `/close` command has the same behavior for both PR and issue :)

**Comment by fejta** [comment]
I see no reason to restrict this command to PRs. 

Author can click the close button. Not necessarily the assignee.

**Comment by xiangpengzhao** [comment]
Assignee might want close some dup PRs, or some wrong PRs such as https://github.com/kubernetes/kubernetes/pull/45470. But surely it's not so necessary.

/close :)

**Comment by krzyzacy** [comment]
@xiangpengzhao #2839 is still open, you can keep an eye on that one as well.

**Comment by xiangpengzhao** [comment]
Thanks Sen!
