### ISSUE TITLE
Ability to set labels / annotations on prow jobs using a preset

### ISSUE THREAD

**Issue by dobesv** [kubernetes/test-infra#28632]
**What would you like to be added**:

It would be nice to set labels on pods using a preset.  Currently I have to manually add certain labels to every prow job, in particular the label `cluster-autoscaler.kubernetes.io/safe-to-evict` to prevent the pod from being killed in order to scale down the cluster.

**Why is this needed**:

In our case we want to add labels to prevent the cluster autoscaler from terminating the pod as this leads to spurious failure states "The pod was deleted unexpectedly".  It would be nice to keep the ProwJob spec clean and apply this label to *all* pods created for prow jobs.

**Comment by petr-muller** [comment]
> In our case we want to add labels to prevent the cluster autoscaler from terminating the pod

This is a tangent to the RFE (which I'm not opposed to) but Prow labels its pod with `created-by-prow=true`, and you can set a PDB on it that prevents it from being reaped by the autoscaler.

**Comment by dobesv** [comment]
> you can set a PDB on it that prevents it from being reaped by the autoscaler

I was trying to figure this out.  It seems like if I setup a PDB that matches on a label like `created-by-prow=true` and set `minAvailable=1` then it would only require that at least one prow job was still running, rather than preventing any prow job from being disrupted.  e.g. if two prow jobs were running, it would allow one to be killed. 

It specifically says here you can only use an absolute minimum in cases where pods are created directly by a controller:

https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors

I guess I could set the PDB to say `minAvailable=9999` or something and that would prevent it from disrupting any pods (unless I really have > 9999 prow jobs running) 🤔 .  Hmm maybe something to try.

**Comment by petr-muller** [comment]
You can also set `maxUnavailable`. This is what we do in OpenShift: https://github.com/openshift/release/blob/master/clusters/build-clusters/common/assets/pdb.yaml

**Comment by dobesv** [comment]
The docs say:

> You can use a PDB with pods controlled by another type of controller, by an "operator", or bare pods, but with these restrictions:

> only .spec.minAvailable can be used, not .spec.maxUnavailable.
> only an integer value can be used with .spec.minAvailable, not a percentage.
> You can use a selector which selects a subset or superset of the pods belonging to a built-in controller. The eviction API will disallow eviction of any pod covered by multiple PDBs, so most users will want to avoid overlapping selectors. One reasonable use of overlapping PDBs is when pods are being transitioned from one PDB to another.

So I assumed I could not use `maxUnavailable: 0` for this.  Are the docs incorrect?  Or is there something else going on?

**Comment by petr-muller** [comment]
No idea about that, sorry. It seems to work for us.

**Comment by dobesv** [comment]
> It seems to work for us.

Huh, interesting.

**Comment by tnozicka** [comment]
Did PDB work for you eventually? I've not sure what happens in the end yet but I get a lot of these events
```
40s (x5 over 88s)   Warning   UnmanagedPods          PodDisruptionBudget/prow-pods              Pods selected by this PodDisruptionBudget (selector: &LabelSelector{MatchLabels:map[string]string{created-by-prow: true,},MatchExpressions:[]LabelSelectorRequirement{},}) were found to be unmanaged. As a result, the status of the PDB cannot be calculated correctly, which may result in undefined behavior. To account for these pods please set ".spec.minAvailable" field of the PDB to an integer value.
```

**Comment by dobesv** [comment]
I think in our case the PDB wouldn't help because the nodes were reclaimed by AWS whether we like it or not since they are spot instnace.  So I created a controller that restarts jobs if they are terminated unexpectedly.
