### ISSUE TITLE
Tests should be canceled after PR is closed

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#2864]
I close my PR one hour ago: https://github.com/kubernetes/kubernetes/pull/46478#event-1098280698

But k8s-ci-robot reported a test flake 28 minutes ago: https://github.com/kubernetes/kubernetes/pull/46478#issuecomment-304178784

So it seems like the tests still ran after the PR was closed.

**Comment by krzyzacy** [comment]
We can abort the test pod in prow, but I'm afraid that the actual test will still be running in the remote cluster.. Maybe we just don't report back if the PR is closed, but that might be misleading as well.

**Comment by spxtr** [comment]
If the PR is closed then we shouldn't report the result back, but we do still want to run the test. If we cancel the test itself then we'll leak our test cluster.

**Comment by xiangpengzhao** [comment]
Is there anyway to cancel the test and also tear down the test cluster?
