### ISSUE TITLE
Prow issue: k8s-ci-robot posts dead link in details section

### ISSUE THREAD

**Issue by simt2** [kubernetes/test-infra#2865]
In the details section of the comment k8s-ci-robot makes when tests failed, the link in the sentence "Instructions for interacting with me using PR comments are available here." is dead. It should probably link to `https://github.com/kubernetes/test-infra/blob/master/commands.md` and not `https://github.com/kubernetes/community/blob/master/contributors/devel/pull-request-commands.md`.

**Comment by krzyzacy** [comment]
@simt2 thanks, would you like to send a quick PR to fix the link?

**Comment by spiffxp** [comment]
As far as I know this has been fixed, eg:
- prow: https://github.com/kubernetes/kubernetes/pull/47179#issuecomment-307104316
- mungegithub: https://github.com/kubernetes/kubernetes/pull/47179#issuecomment-307156266
