### ISSUE TITLE
kubekins-e2e image - no buildx docker plugin

### ISSUE THREAD

**Issue by RyanStan** [kubernetes/test-infra#28655]
**What happened**:
On the [aws-efs-csi-driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver/), we've noticed that our testing infrastructure has begun failing due to `docker` missing the `buildx` plugin.  For example, [on this failed e2e test job](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-efs-csi-driver/903/pull-aws-efs-csi-driver-e2e/1622687143392448512), the error we see is 

```
 docker buildx build \
	--no-cache-filter=linux-amazon \
	--platform=linux/amd64 \
	--progress=plain \
	--target=linux-amazon \
	--output=type=docker \
	-t=607362164682.dkr.ecr.us-west-2.amazonaws.com/aws-efs-csi-driver:22523-linux-amd64-amazon \
	.
unknown flag: --no-cache-filter
See 'docker --help'.
Usage:  docker [OPTIONS] COMMAND
A self-sufficient runtime for containers 
```

I noticed that the kubekins-e2e images that [our presubmit jobs](https://github.com/kubernetes/test-infra/blob/f1a1b1dd48c5fbcb8c548a2935b882eb9223fdb9/config/jobs/kubernetes-sigs/aws-efs-csi-driver/aws-efs-csi-driver-presubmits.yaml) use was recently [bumped by this commit](https://github.com/kubernetes/test-infra/commit/f1a1b1dd48c5fbcb8c548a2935b882eb9223fdb9#diff-535e88d6c515efc70f12a1dd9dfd5a96ffade52dbc38f45a39b69fd7fe314fdc) to `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230206-d33fd1807d-master` (from `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230127-9396ca613c-master`)

**What you expected to happen**:
The buildx plugin to have been built into the `kubekins-e2e` image.

**How to reproduce it (as minimally and precisely as possible)**:
Doesn't work:
```
FROM gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230206-d33fd1807d-master
RUN docker buildx
```
Output: `docker: 'buildx' is not a docker command.`

Works: 
```
FROM gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230127-9396ca613c-master
RUN docker buildx
```
Output:  `Usage:  docker buildx [OPTIONS] COMMAND`

**Please provide links to example occurrences, if any**:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-efs-csi-driver/903/pull-aws-efs-csi-driver-e2e/1622687143392448512
- 
**Anything else we need to know?**:

**Comment by wongma7** [comment]
This should be fixed by https://github.com/kubernetes/test-infra/pull/28654 cc @BenTheElder could we keep this  issue open to track why d33fd1807d is missing buildx, will defer to you thank you!!

**Comment by BenTheElder** [comment]
also tracked in https://github.com/kubernetes/kubernetes/issues/115556

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28656 should add this to future images, but will need some more follow-up to rollout. in the meantime we reverted back to a prior image tag in #28654

**Comment by BenTheElder** [comment]
docker documented installing this plugin as a separate package 6 hours ago 😅  
buildx was previously included in the install when installing docker-ce.

Did not expect this particular in regular image updates, though we always expect that upgrading these can break something https://kubernetes.slack.com/archives/C09QZ4DQB/p1675709260771109

Sorry for the noise!



Should be fixed long term by #28656 and then rounds of tag updates

**Comment by BenTheElder** [comment]
new images blocked on https://github.com/kubernetes/test-infra/pull/28660 (yaml quoting bug ...)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28663 then we'll try upgrading CI to latest images again.

**Comment by BenTheElder** [comment]
upgraded in https://github.com/kubernetes/test-infra/pull/28659

should be good now 🤞
