### ISSUE TITLE
Add /sig-approved functionality

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#2869]
For the 1.7 release, the release team asked for a few things

- All PRs have an associated issue in the milestone (https://github.com/kubernetes/test-infra/issues/2868)
- All Issues have a sig label 
**- All Issues are approved by aforementioned sig by applying approved-for-milestone label**

Not all sig-leads have access to apply the approved-for-milestone label.  Let's add /sig-approved command to prow so that sig leads can apply the label.  

We can verify sig leads by adding them as a group to the OWNERS_ALIASES file in the main repo.

/assign

@dchen1107 @foxish @crimsonfaith91

**Comment by grodrigues3** [comment]
Making this a high priority since code freeze is Jun 01, and we'd like sigs to be able to start adding this lable ot their issues starting around then (or sooner)

**Comment by cblecker** [comment]
The other way to potentially track who should be able to apply the label would be to check github team membership.. @kubernetes/sig-leads or something:
https://developer.github.com/v3/orgs/teams/#get-team-membership

**Comment by grodrigues3** [comment]
@cblecker.  Teams allow for no auditing, and therefore we can't tell who added someone to the sig-leads team.  With the OWNERS_ALIASES file you'd have to submit a PR to get it merged.

**Comment by cblecker** [comment]
Good point 👍🏻

**Comment by xiangpengzhao** [comment]
This is code freeze of 1.8 now. Is this issue still relevant for.1.8?

**Comment by cblecker** [comment]
@grodrigues3 @jdumars may know

**Comment by jdumars** [comment]
We still need to ensure the approved-for-milestone label is added to issues, so AFAICT this is still valid for 1.8.

**Comment by spxtr** [comment]
Can you go into a little more detail about how this will impact regular workflows? Someone opens an issue: what happens next?

**Comment by jdumars** [comment]
@spxtr once an issue is added to the milestone, it becomes release-blocking until resolved or removed from the milestone.  The approved-for-milestone label is added as an acknowledgement by the SIG that it is indeed valid and release-blocking.  

1. Create issue
2. Add normal labels (kind, priority, SIG, area, etc.)
3. Add to the 1.8 milestone
4. Add approved-for-milestone so the bot doesn't kick it out of the milestone
