### ISSUE TITLE
Prow deck failed to show PR Status

### ISSUE THREAD

**Issue by TianxiangShen** [kubernetes/test-infra#28751]
**What happened**:
After I upgraded prow to newest version, Prow deck failed to show PR Status in `https://<prow-url>/pr`

I checked the Console of the webpage, I found error:
<img width="758" alt="Screen Shot 2023-02-14 at 5 12 29 PM" src="https://user-images.githubusercontent.com/36116932/218899530-566254d5-251b-45a8-a5d3-19d2728880f9.png">

After reviewed  `pr_bundle.min.js`, I found the issue is caused by `nil` value in `Pools` of  tideData:
https://github.com/kubernetes/test-infra/blob/ef2d1164707096131ff227118a617acf6fe7f601/prow/cmd/deck/static/pr/pr.ts#L437

tideData is loaded from `/tide.js` file. Here is what `/tide.js` looks like:
```
{
"Queries": [
  "is:pr state:open archived:false label:\"approved\" label:\"lgtm\" -label:\"do-not-merge\" -label:\"do-not-merge/blocked-paths\" -label:\"do-not-merge/hold\" -label:\"do-not-merge/invalid-owners-file\" -label:\"do-not-merge/work-in-progress\" -label:\"needs-rebase\" org:\"test-org\""
  ],
"TideQueries": [
  {
  "labels": [
  "approved",
  "lgtm"
  ],
  "missingLabels": [
    "do-not-merge",
    "do-not-merge/blocked-paths",
    "do-not-merge/hold",
    "do-not-merge/invalid-owners-file",
    "do-not-merge/work-in-progress",
    "needs-rebase"
    ],
"orgs": [
  "test-org"
]
}
],
"Pools": nil
}
```

So I kept checking how this `Pools` being updated and found the issue: 
https://github.com/kubernetes/test-infra/blob/ef2d1164707096131ff227118a617acf6fe7f601/prow/cmd/deck/main.go#L1305

This `poolsForDeck` varible initialized as nil, if there's no pools in tideAgent (for example my org doesn't have any pr that can be searched out by the tide Query), `poolsForDeck` will be returned in http Response as nil value. This caused the issue I saw.

My suggestion is to initialize the variable in another way to avoid the error:
```
poolsForDeck := []tide.PoolForDeck{}
```

**Comment by smg247** [comment]
I can't find how this could have been caused by https://github.com/kubernetes/test-infra/pull/28669 as the `tidePools` variable remains untouched in that PR, but I think the fix is pretty straightforward, and harmless. I will add a null check prior to filtering in the `createPRCardTitle` function.

**Comment by smg247** [comment]
@TianxiangShen, this should be fixed now. I can't confirm it as the problem isn't occurring in prow instances I have access to. Can you update to the latest version and confirm?

**Comment by TianxiangShen** [comment]
Hi @smg247, Thanks for the change. This issue didn't bring up from your pr [#28669](https://github.com/kubernetes/test-infra/pull/28669). It is because of [#26149](https://github.com/kubernetes/test-infra/pull/26149/files#diff-d40acdd2b1d895ddbecfd6a18c07251004492205b298f349bc60372bc59a78acR1289), the `poolsForDeck` variable initialized as null. I will check if your pr can resolve the issue, but I think it's better to resolve it from the source, which is that backend code. 
cc @chaodaiG
