### ISSUE TITLE
Support running e2e-node tests on ARM64 machine type

### ISSUE THREAD

**Issue by ike-ma** [kubernetes/test-infra#28888]
/sig node
/sig testing
/kind feature

**What would you like to be added**:

Run e2e-node test on ARM64-based machine.

**Why is this needed**:

Kubernetes began to support ARM64 as early as version 1.2, which was released in April 2016. Since then, Kubernetes has continued to improve its support for ARM64, and has been a fully supported architecture for a long time. 

Due to the lack of cloud resources for testing, ARM64 support was previously out of scope of sig-testing. With several cloud providers providing ARM64 machine type natively now, it is beneficial to leverage these resources available to ensure that the testing process is as comprehensive and effective as possible. Running e2e-node test on ARM64 based machine can help provide valuable signal to identify regression early, which can also improve the stability and reliability of the Kubernetes.

**Comment by SergeyKanzhelev** [comment]
/reopen 

for https://github.com/kubernetes/test-infra/pull/29192 tracking

**Comment by dims** [comment]
https://testgrid.k8s.io/amazon-ec2-node#Summary&width=20

/close
