### ISSUE TITLE
Running node e2e tests on AWS

### ISSUE THREAD

**Issue by upodroid** [kubernetes/test-infra#28899]
Kubelet and containerd e2e tests run on `google.com` GCP projects today and we would like to start running them on AWS as we have a lot of credits there and more importantly, eliminate GCE specific behaviors. Ideally, the only requirement is that the node is bootstrapped by cloud-init. The k/k repo will have cloud-provider specific code to create instances in GCP or AWS, or X, but it will bootstrap nodes from a standard cloud-init file per distribution.

All the kubelet/containerd tests are single node tests and much easier to refactor than https://github.com/kubernetes/kubernetes/issues/78995

Reading/background/relevant files:
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/e2e-node-tests.md
- https://github.com/kubernetes/test-infra/tree/master/jobs/e2e_node/containerd
- https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/containerd.yaml

Initial testing + Bug reports
https://github.com/kubernetes/kubernetes/issues/116114 AWS public AMI
https://github.com/kubernetes/kubernetes/issues/116112 GCE public Ubuntu Image

Next steps:
- Create an AWS account in k/k8s.io for kubelet/containerd test
- Merge https://github.com/kubernetes/kubernetes/pull/116236
- Merge https://github.com/containerd/containerd/pull/8170
- resolve the issues in k/k
- Merge https://github.com/kubernetes/test-infra/pull/28856
- Add new CI prow jobs
- Promote tests to pre-submits
- Promote tests to release blocking

/sig node
/sig k8s-infra

**Comment by upodroid** [comment]
There has been many changes since this issue was opened.

@dims @tzneal 

New plan:

- The AWS e2e test logic lives in https://github.com/kubernetes-sigs/provider-aws-test-infra
- We merged the first "canary" job https://github.com/kubernetes/test-infra/pull/29776
- Create a dedicated AWS account for node e2e tests(currently using the kops e2e account)
- Configure cross-account IRSA https://aws.amazon.com/blogs/containers/cross-account-iam-roles-for-kubernetes-service-accounts/
- These new jobs will run on the EKS clusters and can leverage IRSA to access this account.(boskos is not required as tests have `max_concurrency` set and thousands of instances can run in a single region with the correct limit updates)
- Using this k/k PR to test the jobs: https://github.com/kubernetes/kubernetes/pull/118626

**Comment by dims** [comment]
we have a bunch now 

https://testgrid.k8s.io/amazon-ec2-node#Summary&width=20

/close
