### ISSUE TITLE
Reduce the cost footprint from scalability tests

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/test-infra#28894]
It seems that as a project out spends are exceeding our budget and we need to reduce our costs.
This issue will be collecting the work we're doing for it in the area of scalability testing.

Few things that we're pursuing now are:
- [x] making 100-node presubmit tests optional instead of required (DONE in https://github.com/kubernetes/test-infra/pull/28889)
- [x] adjusting the frequency of 5k-node tests (https://github.com/kubernetes/test-infra/pull/28913)
- [x] removing some other less important jobs or adjusting their frequency (https://github.com/kubernetes/test-infra/pull/28895, https://github.com/kubernetes/test-infra/pull/28908, ...)

The first two have the biggest potential impact.
For 100-node presubmits we've done some probing of failing 100-presubmits and didn't find any case where it really caught a real problem anytime recently. While we would love to keep them, it's also obvious that the ROI here is not enough and as a result we will be making them option in the next hours.

For the next two items, we will be updating this issue soon.

@kubernetes/sig-scalability @shyamjvs @marseel @mborsz 

/king cleanup
/priority important-soon

**Comment by wojtek-t** [comment]
We did quite a bit here and we seem to be under control now. I'm closing it for now.

**Comment by BenTheElder** [comment]
Thank you! +1
