### ISSUE TITLE
Configured Tests Dashboard

### ISSUE THREAD

**Issue by smg247** [kubernetes/test-infra#28979]
**What would you like to be added**:
A new dashboard that lists all configured jobs in the Prow instance. It should be filterable by org and repo. It should show a prettified view of the yaml for the job. It should also link to the job-history page for each respective job.

**Why is this needed**:
Test maintainers need an easy way to see all of the jobs configured for a specific org or repo. 
There are a few issues with existing methods for seeing jobs:

- Looking through the config files isn't a good user experience
- Job-History is not easily navigable, and doesn't provide a list view
- Deck only shows jobs that have executed very recently

**Comment by petr-muller** [comment]
I have moved this to Prow, whatever gets built will likely start there:

https://github.com/kubernetes-sigs/prow/issues/208\

/close
