### ISSUE TITLE
Consider using ArgoCD to manage cluster state instead of `kubectl`

### ISSUE THREAD

**Issue by upodroid** [kubernetes/test-infra#29033]
We are deploying rather complicated applications to the prow-build clusters and would benefit greatly from using ArgoCD to deploy apps that are bundled as Helm charts instead of manually generating a yaml file from Helm chart.

I already do this today for the prow clusters that I managed for knative:
- https://github.com/knative/test-infra/issues/3363 argocd vs kubectl
- typical application deployment: https://github.com/knative/test-infra/pull/3399
- grafana stack: https://github.com/knative/test-infra/pull/3500

A list of apps that we plan on running on K8s clusters:
- ESO: https://github.com/kubernetes/k8s.io/pull/4930
- Kyverno
- Grafana
- and more

/sig testing
/sig k8s-infra

**Comment by BenTheElder** [comment]
> We are deploying rather complicated applications to the prow-build clusters and would benefit greatly from using ArgoCD to deploy apps that are bundled as Helm charts instead of manually generating a yaml file from Helm chart.

Eh, I greatly prefer the visibility of seeing exactly what manifests we're deploying checked into the repo and the ability to git revert those versus depending on external charts. You will find that the Kubernetes organization very rarely has anything helm related.

If we need to template things, we prefer declarative patches (e.g. kustomize).

Lack of prune is a valid issue, though rarely encountered. Moving to plain kubectl vs rules_k8s is a recent move that has not addressed this.

> Kyverno

I'm not sold that we should be deploying this in k8s prow yet tbh. Mutating admission webhooks should generally be avoided and are not the only way we can accomplish using mirrors.

EKS supports configuring containerd AFAIK we can relatively easily inject mirror config at the node level instead, which is generally a safer approach.

Currently aside from prow itself we depend on Grafana and ESO in the services cluster. These relatively rarely require updates.
