### ISSUE TITLE
Bot doesn't remove "needs-sig" after a sig label is added

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#2909]
Seems like bot currently adds `needs-sig` label automatically for those issues which don't have sig labels. However, bot doesn't remove `needs-sig` after a sig label is added for the issue. Issues have both `needs-sig` and `sig/foo` at the same time. It's not expected.

See example: https://github.com/kubernetes/kubernetes/issues/46736

/cc @fejta @krzyzacy

**Comment by xiangpengzhao** [comment]
Finally it does:
`k8s-merge-robot added the needs-sig label 2 hours ago`
`k8s-merge-robot removed the needs-sig label 37 minutes ago`

I don't know why it removes `needs-sig` so slowly...

**Comment by krzyzacy** [comment]
maybe munger is having a hard time

**Comment by crimsonfaith91** [comment]
Refer this: https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/sig-mention-handler.go

The delay may due to unexpected long period between two runs of the munger. I will get back to this after doing some research about it.

**Comment by xiangpengzhao** [comment]
seems like that bot works well now.
/close
