### ISSUE TITLE
Setup periodic scalability CI tests on AWS

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#29139]
Follows from discussion here - https://groups.google.com/g/kubernetes-sig-release/c/ShwzKuYoRAc/m/t6LvF7BQAgAJ

Let's use this issue to plan and track the tasks we need to get there. For the initial phase, we need to:

- [x] Find (or create) a CNCF-owned AWS account where we can run these jobs. From experience, doing this in a separate account from regular CI jobs is better w.r.t isolation, limits/throttling, etc
- [x] Get the account limits raised for various AWS resources/APIs we depend on (ec2, ENIs, EBS, IAM, etc)
- [x] Bring up a smaller-scale job first (say 100-node?) using the recommended way today for creating AWS test clusters (kops? we have other, possibly better, options too for scale-testing - [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws), [KIT](https://github.com/awslabs/kubernetes-iteration-toolkit))
- [x] Get the job to reliably pass. We can bump up the scale incrementally from there

cc @kubernetes/sig-scalability @kubernetes/sig-k8s-infra @kubernetes/sig-testing
cc @dims @wojtek-t @BenTheElder

**Comment by shyamjvs** [comment]
We need guidance/status quo for 1 and 3 from @kubernetes/sig-testing :)

**Comment by BenTheElder** [comment]
Hope I can help more here in the future, bit distracted with [the registry redirect](https://kubernetes.io/blog/2023/03/10/image-registry-redirect/).

>  Find (or create) a CNCF-owned AWS account where we can run these jobs. From experience, doing this in a separate account from regular CI jobs is better w.r.t isolation, limits/throttling, etc

We usually use a pool of sub-accounts that we rent from [boskos](https://github.com/kubernetes-sigs/boskos) as a way to ensure we can cleanup after CI runs. I think SIG K8s Infra can help with the accounts, and this pattern should be pretty well established for kOps and CAPA at least.

We'd still need K8s Infra to setup some new projects with higher quota in a distinct pool, but the project pool part should be ready to go, mainly just the quota part I think?

> Bring up a smaller-scale job first (say 100-node?) using the recommended way today for creating AWS test clusters (kops? we have other, possibly better, options too for scale-testing - [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws), [KIT](https://github.com/awslabs/kubernetes-iteration-toolkit))

I would **strongly** suggest starting with kOps:
- Integrates with our existing CI tooling including kubetest(2), boskos, etc.
- Existing fairly extensive and well kept CI signal on AWS and GCE, including at Kubernetes HEAD
- Members of the Kubernetes project can readily patch any issues
- Prior art running in Kubernetes/Kubernetes PR blocking CI for many years which worked well (until https://github.com/kubernetes/test-infra/issues/10043 in 2019)

**Comment by BenTheElder** [comment]
cc @hakman @johngmyers @justinsb @zetaab

**Comment by justinsb** [comment]
I'd be happy to work with you @shyamjvs to get scale testing running with kOps + AWS; we have a bunch of tests that run already.  It looks like the ones at k8s head broke literally today, so we'll have to dig into why (but that's probably a good reason why you don't want to start your own effort if your focus is on scalability not fixing random breakages!)

We can simply create a scenario that runs with 100 nodes, and see what breaks (e.g. we _might_ have quota already).  Which CNI/network configuration would we want to start with?  And if you have any ideas on machine sizes, then we can plug those in to create a one-off scenario [here](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/kops/build_jobs.py#L468-L476).  If we don't know, it's also fairly easy to iterate here.

Then absolutely we should make sure it runs against the new CNCF AWS account , make sure those have the higher limits etc.

**Comment by BenTheElder** [comment]
> Thanks Ben. So to clarify - we need either a new set of account pool with higher quotas or need to increase the quotas for every single account in the existing pool before we can run these tests? Would least resistance path be to provision a single new account (w/ higher quotas) and dedicate that for the scale tests instead?

In the past we've created a separate resource pool for highly-quota accounts on GCP and I think we should do that here. 

This makes it easier to track scale testing related spend and we have needed fewer accounts for this purpose than general e2e testing.

> Will need some help figuring out what's possible with kops vs not. Is sig-testing call good place to discuss this?

SIG testing could be a reasonable place for this, as passing config will also need flow through the CI tooling.

In the meantime:
https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#EtcdManagerSpec (Env)
and higher level:
https://kops.sigs.k8s.io/cluster_spec/#the-cluster-resource

**Comment by shyamjvs** [comment]
We discussed the above in last sig-scale meeting (30th Mar) - [meeting notes](https://docs.google.com/document/d/1hEpf25qifVWztaeZPFmjNiJvPo-5JX1z0LSvvVY5G2g/edit#heading=h.6p0lwiil2b44)

Summary of next steps:
- we decided to use separate boskos pool for scale jobs (1 or 2 should be enough for now) - @ameukam volunteered to help with this
- after that, we need to get some limit increases for those accounts (I'll help get the list for this)
- port the relevant configs defined [here](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-presets.yaml#L132) and [here](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-release-blocking-jobs.yaml#L98-L143) (from GCE scale job today) to the kops cluster
- switch the test cluster to use [aws vpc cni](https://github.com/aws/amazon-vpc-cni-k8s)
- switch from conformance to scalability e2e test suite
- (other supporting work around log upload to s3, ssh to apiservers, perfdash etc we need to figure out later)

**Comment by shyamjvs** [comment]
/assign @ameukam @justinsb @shyamjvs
(initial set of owners - I'll add more as the work evolves)

**Comment by dims** [comment]
@shyamjvs how many dedicated accounts do you need?

(from slack thread https://kubernetes.slack.com/archives/CCK68P2Q2/p1684337286675859)

**Comment by shyamjvs** [comment]
We just need 1 account to begin with for now.

**Comment by dims** [comment]
We have 2 accounts from line item # 1 with limits updated ( `k8s-infra-e2e-scale-boskos-001` and `k8s-infra-e2e-scale-boskos-002` )

details: https://kubernetes.slack.com/archives/CCK68P2Q2/p1684593816977859

Some follow ups pending with @ashishranjan738

**Comment by dims** [comment]
Looks like there's a Kops CI job definition here we may have started looking at for line item 3:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/kops/kops-periodics-scale.yaml#L6

**Comment by hakuna-matatah** [comment]
Current status for Scalability Tests runs on AWS:
Able to successfully setup Periodics for 5k measuring podslos on daily basis, which can be monitored here https://testgrid.k8s.io/kops-misc#ec2-master-scale-performance

Next things:
- Measure API Server SLOs at 5k Scale
- Add aws scalability tests to Perf-dash

**Comment by shyamjvs** [comment]
Looks like the 5k-node kops test has been failing for the past 10 days due to some issue during cluster creation - https://testgrid.k8s.io/kops-misc#ec2-master-scale-performance.

@hakuna-matatah or @mengqiy - could one of you open an issue against this repo for tracking the fixes?

**Comment by hakuna-matatah** [comment]
Thanks @shyamjvs. We are aware of this and looking into it as discussed internally. 
I have cut an [issue](https://github.com/kubernetes/test-infra/issues/31755) for tracking purposes.

**Comment by dims** [comment]
/close

https://testgrid.k8s.io/amazon-ec2-release#ec2-master-scale-performance&width=20
