### ISSUE TITLE
Bot should give a link of label list in the reply.

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#2915]
When an issue doesn't have a sig label after being created, k8s-merge-robot will give a reply as below.

See example: https://github.com/kubernetes/kubernetes/issues/46740#issuecomment-305365316

```
@k8s-merge-robot There are no sig labels on this issue. Please add a sig label by:
(1) mentioning a sig: @kubernetes/sig-<team-name>-misc
(2) specifying the label manually: /sig <label>

Note: method (1) will trigger a notification to the team. You can find the team list here.
```

It includes a link of team list, but doesn't have a link of label list. It should include a link https://github.com/kubernetes/kubernetes/labels so that issue creator or others can know what sig labels are there.

/cc @fejta @krzyzacy

**Comment by crimsonfaith91** [comment]
@xiangpengzhao Great idea!

**Comment by xiangpengzhao** [comment]
Thanks @crimsonfaith91 for the patch!
/close

**Comment by crimsonfaith91** [comment]
You are welcome :)
