### ISSUE TITLE
release-note-edit seems to be broken

### ISSUE THREAD

**Issue by jeremyrickard** [kubernetes/test-infra#29194]
**What happened**:

The `release-note-edit` command seems to not be working for cherry picks (maybe other PRs)

As an example, @bridgetkromhout  tried to edit the release note on this cherry pick but nothing updated.   It had to be manually updated.
https://github.com/kubernetes/kubernetes/pull/116360#issuecomment-1490768443

This seems to perhaps been broken for a bit, I found a mention from a while back:

https://kubernetes.slack.com/archives/C2C40FMNF/p1660238319348879

"The release-note-edit command doesn't seem to work"

**What you expected to happen**:

The release note is updated.

**How to reproduce it (as minimally and precisely as possible)**:

Use "/release-note-edit" on a cherry pick PR. 

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/commits/master/prow/plugins/releasenote/releasenote.go
