### ISSUE TITLE
Unable to load the prow job details page.

### ISSUE THREAD

**Issue by tvardema** [kubernetes/test-infra#29202]
**What happened**:
I tried looking through the build logs at this particular link:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-multiarch-master-nightly-4.13-ocp-e2e-ovn-remote-libvirt-s390x/1641335214116442112

The page loaded the sections and some text on the page, but it ultimately became unresponsive, and then would eventually throw the "Oh Snap, something went wrong" error page that Google Chrome displays when a page breaks.

**What you expected to happen**:
I expected the page to load and allow me to look through the build log and JUnit test failures/successes.

**How to reproduce it (as minimally and precisely as possible)**:
Copy and paste the link above in the browser.

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:
I've received vastly different experiences from different people while trying to understand the situation.  Some people don't even see the sections on the page (JUnit and Build Log), while others load the page successfully after a few minutes.

First image my colleague sent me when asking me if I knew what was wrong:
![image](https://user-images.githubusercontent.com/34040350/229170632-cb164630-0e37-48df-a25e-fc3d48d1a6c7.png)

My page while waiting for it to load:
<img width="2526" alt="image" src="https://user-images.githubusercontent.com/34040350/229170383-a8c057be-3581-47a8-bf00-631d6ae568c7.png">

Final page after it fails to load:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/34040350/229170141-c030e09d-a0a1-431a-83dc-a2dc205a7310.png">

**Comment by BenTheElder** [comment]
Hmm, someone with access to the openshift instance should probably take a look at the logs ...

I see stalled requests to the lenses and generally very responses from the server, it's possible this instance is overloaded?
