### ISSUE TITLE
AWS: `--kops-args` is not working

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#2920]
Trying to track down why; AFAICT it makes it into the docker run from kubernetes_kops_aws.py, but then the image doesn't apply the args.

I suspect we're not running the latest `kubekins-e2e` image.

**Comment by krzyzacy** [comment]
which job?

**Comment by justinsb** [comment]
`ci-kubernetes-e2e-kops-aws-weave`

I got tips from slack, and I'm trying to get calling kubetest working directly first, and then am planning on working my way "up" from there...

**Comment by spiffxp** [comment]
/close
I believe this has been addressed, please reopen if not

That said, FYI @justinsb the [kops-aws-weave](https://k8s-testgrid.appspot.com/google-aws#kops-aws-weave) job has been failing for the last ~month
