### ISSUE TITLE
Remove branch job for 1.23

### ISSUE THREAD

**Issue by cici37** [kubernetes/test-infra#29242]
**What should be cleaned up or changed**:
The branch job for 1.23 should be removed since 1.23 is EOL:
https://github.com/kubernetes/test-infra/pull/29172#issuecomment-1487516695

**Provide any links for context**:
It would be a followup work on: https://github.com/kubernetes/test-infra/pull/29172

/sig release
/assign @ramrodo

**Comment by BenTheElder** [comment]
Partially done in https://github.com/kubernetes/test-infra/pull/29387 ? cc @xmudrii @jeremyrickard

**Comment by xmudrii** [comment]
@BenTheElder I think that it should be completely done. Is there anything else that should be removed?

**Comment by ramrodo** [comment]
I think this issue is completely done now

**Comment by justaugustus** [comment]
Closed via https://github.com/kubernetes/test-infra/pull/29387.
/close
