### ISSUE TITLE
Make janitor record what resources are leaked

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#2925]
It is good to have janitor cleaning up leaked resource on projects. Though this somehow hides the error signal from us --- if resources are leaking someone (probably me :)) should fix it.

Do we have a way to track what resources are leaking on which projects? I think a daily report would probably be useful?

@krzyzacy

**Comment by krzyzacy** [comment]
yeah, currently basically you go through the logs from https://k8s-testgrid.appspot.com/maintenance#ci-janitor, search for `Deleted ` or something. It's running daily anyway. 

I'll try to generate some report out of it.
/assign
