### ISSUE TITLE
`Testgrid History for Job` link for ci-kubernetes-e2e-gce-serial always jumps to sig-cli

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#2926]
Example: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial

Clicked on `Testgrid History for Job` and it jumped to https://k8s-testgrid.appspot.com/sig-cli#gce-serial.

**Comment by MrHohn** [comment]
Now it jumps to https://k8s-testgrid.appspot.com/release-master-blocking#gce-serial instead.

I'm expecting it to be: https://k8s-testgrid.appspot.com/google-gce#gce-serial

**Comment by krzyzacy** [comment]
I think it jumps to first tab it can find if it has multiple. https://k8s-testgrid.appspot.com/release-master-blocking#gce-serial is fine, but maybe not the https://k8s-testgrid.appspot.com/sig-cli#gce-serial one.

/assign @rmmh
