### ISSUE TITLE
prow-controller-manager unable to get pods with starter manifests

### ISSUE THREAD

**Issue by lentzi90** [kubernetes/test-infra#29286]
**What happened**:

I deployed a new Prow instance based on the [starter-s3.yaml](https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/starter/starter-s3.yaml) manifests. It didn't work properly and `prow-controller-manager` was complaining about permissions:

```
{"component":"prow-controller-manager","file":"k8s.io/test-infra/prow/kube/config.go:76","func":"k8s.io/test-infra/prow/kube.LoadClusterConfigs","level":"info","msg":"Loading cluster contexts...","severity":"info","time":"2023-04-06T11:55:52Z"}
{"component":"prow-controller-manager","error":"failed pod resource authorization check: unable to \"get\" pods","file":"k8s.io/test-infra/prow/cmd/prow-controller-manager/main.go:180","func":"main.main","level":"error","msg":"Failed to construct build cluster managers. Please check that the kubeconfig secrets are correct, and that RBAC roles on the build cluster allow Prow's service account to list pods on it.","severity":"error","time":"2023-04-06T11:55:52Z"}
```

What I found was that it expect to be able to `get` pods. See [here](https://github.com/kubernetes/test-infra/blob/200aad376e4c4c4a59eb1c7a89482cfde336c5c6/prow/cmd/prow-controller-manager/main.go#L177). But the RBAC does not allow this:
https://github.com/kubernetes/test-infra/blob/200aad376e4c4c4a59eb1c7a89482cfde336c5c6/config/prow/cluster/starter/starter-s3.yaml#L1058-L1073

**What you expected to happen**:

The starter manifests should include enough RBAC privileges for prow-controller-manager to run.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy prow using the starter manifest following the getting started guide: https://docs.prow.k8s.io/docs/getting-started-deploy/

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by ionutbalutoiu** [comment]
I've also encountered this issue.

This is fixed by updating the role verbs, and I've submitted the fix via PR https://github.com/kubernetes/test-infra/pull/31370.
