### ISSUE TITLE
Job pull-npd-e2e-test failing: ssh: handshake failed

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/test-infra#29308]
**What happened**:
After updating the OS image family for job `pull-npd-e2e-test` to `cos-stable` (https://github.com/kubernetes/test-infra/pull/29263), test started failing with the following errors:

```
Error storing debugging data to test artifacts: [Error running command: {prow $NODE_IP curl http://localhost:20257/metrics   0 error getting SSH client to prow@$NODE_IP:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'}
Error running command: {prow $NODE_IP sudo journalctl -u node-problem-detector.service   0 error getting SSH client to prow@$NODE_IP:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'}
Error running command: {prow $NODE_IP sudo journalctl -k   0 error getting SSH client to prow@$NODE_IP:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'}
```
Everytime the scenario tries to execute a command, it fails to connect to the VM with this SSH handshake failure.

**What you expected to happen**:
Test does connect to the VM and successfully executes command..

**How to reproduce it (as minimally and precisely as possible)**:
Trigger job `pull-npd-e2e-test` in a PR under kubernetes/node-problem-detector.

**Please provide links to example occurrences, if any**:
See all failures starting April 13th:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-npd-e2e-test

**Anything else we need to know?**:
This issue is blocking new PRs to NPD repo.

This is an issue I saw in another place. OpenSSH deprecated using hash algorithm SHA-1 for method RSA in version 8.9 [release notes](https://www.openssh.com/txt/release-8.8). COS stable, which is COS M105 uses OpenSSH version 9.3:
```
$ ssh -V
OpenSSH_9.3p1, OpenSSL 1.1.1t  7 Feb 2023
```

If the test is trying to SSH to the VM using an RSA public key, it must not use SHA-1 as hashing algorithm (SHA-256 or SHA-512 should work). An other alternative is to switch to an elliptic curve key.

/sig node
/sig testing
/priority important-soon
/cc Random-Liu xmcqueen

**Comment by mmiranda96** [comment]
From [Slack thread](https://kubernetes.slack.com/archives/C09QZ4DQB/p1681519651162869):

If using the ssh preset,  the creds should be available inside the pod. So inline via env is not needed.

Ref:https://github.com/kubernetes/test-infra/blob/20764650d1ae688f3898fbb176717270209bcd29/config/prow/config.yaml#L830

**Comment by BenTheElder** [comment]
There's a fixed key used here (for insecure CI only) to avoid running out of space in GCE metadata, it's quite possible that key is using an algorithm that is no longer supported. Someone with access to the prow.k8s.io services cluster (http://go.k8s.io/oncall test-infra, not me) would have to update that particular secret AFAIK, as it doesn't have a secret manager instance. Alternatively someone would have to set up secret manager https://docs.prow.k8s.io/docs/prow-secrets/

**Comment by SergeyKanzhelev** [comment]
@mmiranda96 what are the next steps here?

**Comment by mmiranda96** [comment]
We need to rollback https://github.com/kubernetes/test-infra/pull/29330: `preset-k8s-ssh` means that the keys will be available, but the script uses different env variable names than the ones from the preset (`SSH_USER` and `SSH_KEY` instead of any from [here](https://github.com/kubernetes/test-infra/blob/20764650d1ae688f3898fbb176717270209bcd29/config/prow/config.yaml#L832).

We can also try Ben's suggestion, but I'm a bit unsure why other jobs use cos-stable and don't fail. Ideally we want to understand what do these do and do it here as well. I'll investigate a bit further on this.

**Comment by SergeyKanzhelev** [comment]
if you need the roolback happened - send the PR. But if it is broken either way it may not matter much. Please keep posted!

**Comment by mmiranda96** [comment]
I took a dive into the NPD E2E lib and it seems that when it executes SSH commands to the node, it does this through `golang.org/x/crypto/ssh` library. In the [version](https://github.com/kubernetes/node-problem-detector/blob/6e57ca6e6c0135ff4a73788e28563476ed9c9334/go.mod#L70) used on vendor (a very old one, I may say), the default hashing algorithm for RSA keys is indeed SHA1 ([source](https://github.com/kubernetes/node-problem-detector/blob/6e57ca6e6c0135ff4a73788e28563476ed9c9334/vendor/golang.org/x/crypto/ssh/keys.go#L975)), which is not supported in `cos-stable` (`cos-105-lts` at the time this comment is written).

In contrast, `remote_runner` (the library used for most E2E tests) runs the SSH command directly from the OS via `os.Exec` ([source](https://github.com/kubernetes/kubernetes/blob/e9e60316d303a17c81ed856d6c82a4823b4327f8/test/e2e_node/remote/ssh.go#L147), which delegates the hashing algorithm decision (as well as other nitty details) to the OS. I believe this is the reason why the other jobs are not failing while this one is.

In addition to rollbacking #29330, there are a couple of solutions I can think of:
1. Upgrade `golang.org/x/crypto/ssh` in kubernetes/kubernetes dependencies: risky, might break several things and in a way, falls out of scope for this fix.
2. Change `cos-stable` to an older version that still supports SHA1: easier solution, but would result in not using the latest image, and eventually we'll need to address this problem again.
3. Create new SSH keys (ECDSA, ideally) and upload them to the Prow cluster: best solution, but could cause issues if certain scenarios do not support ECDSA (unlikely).
4. Create new SSH keys and upload them to the Prow cluster, but not modify the existing `preset-k8s-ssh`: safest option, but might not be that clean.

**Comment by dims** [comment]
@mmiranda96  i am fine with option # 1 ( cc @liggitt )

**Comment by mmiranda96** [comment]
After double-checking, it seems that kubernetes/kubernetes uses `golang.org/x/crypto` `v0.6.0` ([source](https://github.com/kubernetes/kubernetes/blob/e9e60316d303a17c81ed856d6c82a4823b4327f8/go.mod#L79)), which does support SHA1 but prefers other algorithms, such as SHA256, for signing ([source](https://cs.opensource.google/go/x/crypto/+/refs/tags/v0.6.0:ssh/common.go;l=114))

It's just NPD that uses older version `v0.0.0-20200622213623-75b288015ac9` ([source](https://github.com/kubernetes/node-problem-detector/blob/6e57ca6e6c0135ff4a73788e28563476ed9c9334/go.mod#L70)), but this seems to be because it's using `k8s.io/kubernetes/kubernetes` `v1.14.6`.

If we can upgrade `golang.org/x/crypto` in NPD without needing to update other dependencies (such as `k8s.io/kuberentes/kubernetes`), this issue should be fixed.

What do we think about this?

**Comment by SergeyKanzhelev** [comment]
> If we can upgrade `golang.org/x/crypto` in NPD without needing to update other dependencies (such as `k8s.io/kuberentes/kubernetes`), this issue should be fixed.

Why wouldn't we upgrade the k/k reference to newer one from NPD?

**Comment by mmiranda96** [comment]
I sent a mitigation PR, will work on the long-term fix later.

/triage accepted
/assign @mmiranda96

**Comment by mmiranda96** [comment]
/close

This has been fixed now.
