### ISSUE TITLE
Prow: Use FQDN whenever possible

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#29317]
**What would you like to be added**:

Prow should be using FQDN for github.com etc. to avoid searching for `github.com.svc.local` etc. in the cluster. I can't think of any good reason not to do this and doing this will reduce pressure on the cluster DNS immensely.

We've also experimented with setting pod ndots:
 - potentially disruptive for e.g. clients of `boskos`, though we try to use FQDN there already
 - requires a TON of config noise if it isn't done by default in podutils, adding this to every job is impractical
 
And with using FQDN elsewhere (with good success) e.g. boskos.

**Why is this needed**:

To reduce DNS flakiness.

Breaking this off from https://github.com/kubernetes/test-infra/issues/28623

**Comment by sarab97** [comment]
@BenTheElder How can I start working on this?

**Comment by BenTheElder** [comment]
I think we should collect more input from Prow maintainers first on the base assumptions here. I spoke briefly to @cjwagner but we haven't heard from @droslean and others if there's a reason this would cause issues.

I think as long as we stick to obviously external domains (like github.com) and/or leave things configurable it should be fine, and in many cases I hope we just need to update prow.k8s.io's configuration.

If that holds, then it's a combination of updating defaults, code, and config in prow in all the components to prefer github.com => github.com. etc. 

Some References:
- https://en.wikipedia.org/wiki/Fully_qualified_domain_name
- https://github.com/coredns/coredns/issues/747

**Comment by sarab97** [comment]
@BenTheElder theres another thing I would like to point out in my company we went though the same process of changing all the domain to FQDN for same reasons to relieve pressure on kubedns and gain tiny performance boost. 

I was the one to do these changes and our observation was with domains of internal services on k8s we changed it to service based url and that worked flawlessly as all were on http. But for external domains when we appended the dot to convert them to FQDN. We faced lot of SSL errors causing us to revert the change. I speculate it might be incase of API the redirect were not working as expected and host with dot suffix didnt matched the host name on certificate hence the SSL error.
 In the end we only made changes to internel domains to make them service based FQDN. And external domains were left as is.

**Comment by BenTheElder** [comment]
> I was the one to do these changes and our observation was with domains of internal services on k8s we changed it to service based url and that worked flawlessly as all were on http. But for external domains when we appended the dot to convert them to FQDN. We faced lot of SSL errors causing us to revert the change. I speculate it might be incase of API the redirect were not working as expected and host with dot suffix didnt matched the host name on certificate hence the SSL error.
In the end we only made changes to internel domains to make them service based FQDN. And external domains were left as is.

This is an interesting point but Not an issue for `github.com.` at least.

```
$ curl -v https://github.com./
*   Trying 192.30.255.113:443...
* Connected to github.com. (192.30.255.113) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Unknown (8):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
*  start date: Feb 14 00:00:00 2023 GMT
*  expire date: Mar 14 23:59:59 2024 GMT
*  subjectAltName: host "github.com." matched cert's "github.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: github.com.]
* h2h3 [user-agent: curl/7.87.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x7f7cc280f000)
> GET / HTTP/2
> Host: github.com.
> user-agent: curl/7.87.0
> accept: */*
> 
< HTTP/2 301 
< content-length: 0
< location: https://github.com/
< 
* Connection #0 to host github.com. left intact
```

**Comment by petr-muller** [comment]
One thing to take into account (not sure about immediate impact, maybe there is none) is that GitHub may not necessarily be `github.com` but can be a Enterprise instance with a different url resolved by all kinds of internal DNSes.

**Comment by BenTheElder** [comment]
> One thing to take into account (not sure about immediate impact, maybe there is none) is that GitHub may not necessarily be github.com but can be a Enterprise instance with a different url resolved by all kinds of internal DNSes.

Good point, but even then:
- the user would be configuring some alternate got github.com. anyhow?
- even in their case FQDN probably makes sense.

I think we should:
1. Whenever we default to github.com, default to github.com. instead
2. In our own configurations, we should explicitly configure with github.com. (and any other hosts)
3. All of these are presumably still configurable, so users that do _actually_ use search paths or hijack github.com (!) can configure without FQDN

I'm not suggesting we should rewrite to FQDN, hopefully we don't need that anywhere and can accomplish this via config/defaults.
