### ISSUE TITLE
Prow with Minikube

### ISSUE THREAD

**Issue by gznznzjsn** [kubernetes/test-infra#29326]
How can I run Prow on local cluster with Minikube? The only suitable article I've found is [Deploying Prow in Minikube](https://medium.com/@Devopscontinens/deploying-prow-in-minikube-626a03c43b15), but, I guess, it is outdated.

**Comment by BenTheElder** [comment]
We usually use [KIND](https://kind.sigs.k8s.io/) when not using a "real" cluster, but prow has these somewhat general deployment docs:

- https://docs.prow.k8s.io/docs/getting-started-deploy/
- https://github.com/kubernetes/test-infra/tree/master/config/prow/cluster/starter
