### ISSUE TITLE
[Documentation] add doc regarding "Cancel pipeline when triggering a new test run"

### ISSUE THREAD

**Issue by emirot** [kubernetes/test-infra#29334]
**What would you like to be added**:
I ve seen that great new feature.
https://github.com/kubernetes/test-infra/pull/28809#issuecomment-1514094505

However I don't see this added to the doc I would love to know more about that.

**Comment by BenTheElder** [comment]
that would be https://github.com/kubernetes-sigs/prow

**Comment by jmguzik** [comment]
@emirot I am the author of the feature. What you would like to know? 
The feature is basically a bug fix for unwanted behavior. In the previous version, if you cancel a prowjob, the associated tekton run was still ongoing which is not correct and a waste of resources. In the corrected version of the pipeline controller, if you cancel a prowjob the associated tekton pipeline will also be canceled. You can still inspect the canceled pipeline, as it is not removed from the system.

In general, I agree documentation about "How to use pipeline controller" which is used for contacting tekton from prow should probably be added (don't look at me, I am not the author of the controller :) ), however, the PR you were referring is just a bugfix and I do not know what else could be described beyond that was said here.

**Comment by emirot** [comment]
@jmguzik 

Please let me know If I understand correctly, let's take that scenario:

- I do a PR with some changes the prow pre-submits jobs will trigger Tekton pipelines
- I do another commit on that PR and with the fix that you put in place, now previous Tekton pipelines running will be cancelled and new ones will be triggered. (which is great will save us a lot of resources) (before your change we will have both running)

However for a specific pipeline, I would like to keep the previous behavior is that possible ? via a flag maybe?

**Comment by jmguzik** [comment]
Your scenario is correct. It's according to the default behavior observed when interacting with prow, even without a pipeline controller. The specific case you are describing is not possible. You can always create and issue and/or contribute to implementing it, but I'd personally say it's not something that should be supported since this job is made obsolete by retesting/retriggering etc.

**Comment by jmguzik** [comment]
Whenever prowjob is canceled the pipeline will be canceled as well. So there is no distinct classification whether it is periodic, pre or postsubmit.
