### ISSUE TITLE
initupload could not read clone log, clonerefs probably fails and doesn't create /logs/clone.json

### ISSUE THREAD

**Issue by Chogos** [kubernetes/test-infra#29375]
**What happened**:
I've deployed a new prow instance on GKE and when running a job `initupload` fails with:

```
Terminated (Error - {"component":"initupload","error":"could not read clone log: open /logs/clone.json: no such file or directory","file":"k8s.io/test-infra/prow/cmd/initupload/main.go:45","func":"main.main","level":"fatal","msg":"Failed to initialize job","severity":"fatal","time":"2023-04-26T14:44:26Z"} ) at 2023-04-26 14:44:26 +0000 UTC with exit code 1
```

`clonerefs` exits with `0`:
```
Terminated (Completed) at 2023-04-26 14:44:26 +0000 UTC with exit code 0
```

I assume that I have an issue with the ssh key that I give in the decoration config, but the same key works in our other instance.
I've intentionally given it an invalid key and got the same result.
Locally running `clonerefs` with the same key works and using an invalid one gives me the error output from 
https://github.com/wingtra/test-infra/blob/update-prow-k8s-config/prow/clonerefs/run.go#L188

I'm a bit at a loss how to proceed. Any idea how to debug this further?

**What you expected to happen**:
Some kind of error output by `clonerefs`.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by raphael-stadler-wingtra** [comment]
@BenTheElder @alvaroaleman @aojea @cjwagner @pohly

How to proceed with the above mentioned problems? Is there another suggested workflow than opening a ticket here?
Thanks for your recommendations and your efforts!
