### ISSUE TITLE
k8s-merge-robot should wait for k8s-ci-robot to label

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#2938]
I create an issue https://github.com/kubernetes/kubernetes/issues/46822 and write `/sig api-machinery` in the content. I hope k8s-ci-robot label `sig/api-machinery` for the issue. After I submit the issue, k8s-ci-robot doesn't label it immediately. k8s-merge-robot detects the issue doesn't have a label so it replies to tell me to label the issue. It then labels the issue `needs-sig`. 

A moment later, k8s-ci-robot labels the issue `sig/api-machinery`. Now the issue has both `sig/api-machinery` and `needs-sig` at the same time. Another moment later, k8s-merge-robot detects the `sig/api-machinery` and then removes `needs-sig`.

k8s-merge-robot should wait for k8s-ci-robot for a short time. After then, if there is still no sig label, it goes on to do its work.

@krzyzacy @crimsonfaith91

**Comment by crimsonfaith91** [comment]
putting the munger that adds `needs-sig` label _after_ the munger for labelling the issue `sig/api-machinery` may solve this. i will ask around to see whether it is a viable solution for this.

**Comment by xiangpengzhao** [comment]
I haven't seen this again since the PR was created. Close for now.
