### ISSUE TITLE
Soak tests are failing: cluster not up

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/test-infra#2942]
https://k8s-testgrid.appspot.com/google-soak
Looks like the clusters are not up at all.

ref: https://github.com/kubernetes/kubernetes/issues/46794

**Comment by krzyzacy** [comment]
hummm when is the deployment happen?

I'll kick the deployment job manually.

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gce-deploy/31?log#log the last deployment job looks normal? Something screwed the cluster up?

**Comment by krzyzacy** [comment]
oh sorry, it was screwed before the fix of https://github.com/kubernetes/test-infra/pull/2903

**Comment by krzyzacy** [comment]
the jobs are running happily as usual
