### ISSUE TITLE
Prow: Re-Run Prowjob should not give choice between original and latest if they are the same

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/test-infra#29452]
**What would you like to be added**:

**Why is this needed**:

Right now, the `Re-Run ProwJob` UI dialog forces to choose between the original and the latest config of the ProwJob. In 99% of the cases, those are the same. If they are the same, that dialog should not appear.

**Comment by sladyn98** [comment]
@alvaroaleman I would like to give this issue a shot, can you give me some code pointers
