### ISSUE TITLE
PR Status Dashboard cant find private repos - Deck

### ISSUE THREAD

**Issue by CPinhoK** [kubernetes/test-infra#29535]
**What happened**:
After deploying prow using the starter-s3.yaml and following the instructions at https://docs.prow.k8s.io/docs/getting-started-deploy/
We setup a github OAuth app to enable the "PR Status" option in the dashboard, however this only allows it to find PRs from public repos, in the docs at https://docs.prow.k8s.io/docs/components/core/deck/github-oauth-setup/ its offered the option 
```
If Prow is expected to work with private repositories, add

scopes:
- repo
```
We added this parameter to the github-oauth-config secret but it doesn't seem to work

**Comment by BenTheElder** [comment]
> We added this parameter to the github-oauth-config secret but it doesn't seem to work

scopes don't go in the secret they go in the github oauth settings

https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps

**Comment by CPinhoK** [comment]
Thanks @BenTheElder  but there is no scopes option in the github oauth settings.

**Comment by CPinhoK** [comment]
I still was not able to find a option for scopes in a github-oauth settings.  @BenTheElder

**Comment by BenTheElder** [comment]
/remove-help

This doesn't meet the requirements
Further, this has been inactive and is not currently planned. The Kubernetes project does not use private repos so we're unlikely to prioritize this ourselves.

Prow is now at https://github.com/kubernetes-sigs/prow and further feature requests should be filed there.
