### ISSUE TITLE
Assign reviewer with `cc` command is not working with a comment in front of it

### ISSUE THREAD

**Issue by amirrmonfared** [kubernetes/test-infra#29563]
**What happened**:
I was trying to assign my teammate with the following command `/cc @myteammate with some comment` but it seems it will not work if you add a comment in front of it.

**What you expected to happen**:
I was expected to request a review from the assigned person

**How to reproduce it (as minimally and precisely as possible)**:
try to do this `/cc @myteammate with some comment` 
**Please provide links to example occurrences, if any**:
unfortunately, it happened in a private repo
**Anything else we need to know?**:
I found there is no test case to cover it so maybe we can fix this by providing a way to recognize the request and comment separately
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/assign/assign_test.go#L390

**Comment by smg247** [comment]
@amirrmonfared, this is pretty standard prow plugin behavior. I _think_ it should work as long as the `/cc` is at the beginning of any line in the comment, but none of the plugins parse commands out of any position in a line.

**Comment by amirrmonfared** [comment]
> this is pretty standard prow plugin behavior. I _think_ it should work as long as the `/cc` is at the beginning of any line in the comment, but none of the plugins parse commands out of any position in a line.

If it's standard behavior so please close this issue but if not and we should take care of it you can see for example in this PR where I requested review from you https://github.com/kubernetes-sigs/contributor-playground/pull/1086#issuecomment-1557148499

**Comment by BenTheElder** [comment]
Commands should start and end a line with no other text.

**Comment by BenTheElder** [comment]
This is also the behavior for most similar systems.

**Comment by BenTheElder** [comment]
We could consider more generally changing this, but I don't think we should, it will be difficult to disambiguate versus arguments. for example you can `/cc @foo @bar @baz` so we don't know if the other text are more users or just you saying something unrelated.

Using two lines works.
