### ISSUE TITLE
k8s-ci-bot doesn't always reiterate the mentions to trigger a notification

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#2956]
I want to mention a team `kubernetes/sig-testing-misc` at https://github.com/kubernetes/kubernetes/issues/43556#issuecomment-306022362 but it doesn't work.

It works well at https://github.com/kubernetes/kubernetes/issues/46359#issuecomment-306022569.

/assign @crimsonfaith91

**Comment by crimsonfaith91** [comment]
@xiangpengzhao When you type `@kubernetes/sig-testing-misc`, the bot will add a `sig/testing` label.

For https://github.com/kubernetes/kubernetes/issues/43556, the issue already has the `sig/testing` label **before** you typed `@kubernetes/sig-testing-misc`. Furthermore, you didn't write any message after `@kubernetes/sig-testing-misc`.

For https://github.com/kubernetes/kubernetes/issues/46359, the issue does not have the `sig/testing` label yet when you typed `@kubernetes/sig-testing-misc` **with** a message. Hence, the bot added the `sig/testing` label and reiterated your message.

**Comment by xiangpengzhao** [comment]
When I type `@kubernetes/sig-testing-misc`, what I want the bot to do is not labeling the issue. I want the bot to notify the team members to pay some attention to the issue. I think this shouldn't depend on that whether the issue already has a related label or not.

**Comment by cblecker** [comment]
Hmm.. seeing another occurrence of this here: https://github.com/kubernetes/community/pull/787#issuecomment-313550317

**Comment by cblecker** [comment]
This functionality was originally added in https://github.com/kubernetes/test-infra/pull/2662

**Comment by xiangpengzhao** [comment]
Thanks @cblecker !

Seems like remove the `continue` code block in [getRepeats](https://github.com/grodrigues3/test-infra/blob/master/prow/plugins/label/label.go#L131-L133) would be okay but I'm not sure.

cc @crimsonfaith91

**Comment by cblecker** [comment]
cc @grodrigues3

**Comment by xiangpengzhao** [comment]
fixed by #3398. Thanks!
/close
