### ISSUE TITLE
Add CNCF contact information to k8s-ci-robot CLA message

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#2962]
Exactly this text.

```
Please email the CNCF helpdesk at helpdesk@rt.linuxfoundation.org for support with the CLA.
```

Would also be nice to add that text to the FAQ https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ.

ref. kubernetes/kubernetes#42409
cc @cblecker

**Comment by cblecker** [comment]
Easily done, and you're right, is a good change.
/assign
