### ISSUE TITLE
cherrypick plugin doesn't response to all commands in a github comment

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/test-infra#29666]
**What happened**:
cherry-pick plugin didn't detect multiple uses of /cherry-pick command in the same message

ie. from https://github.com/knative/serving/pull/14028#issuecomment-1572058940
```
/cherry-pick release-1.10
/cherry-pick release-1.9
```

**What you expected to happen**:
It would create two cherry pick PRs

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

This was fixed but seems to have regressed
https://github.com/kubernetes/test-infra/issues/21684
https://github.com/kubernetes/test-infra/issues/21714

Knative is using 

```
      - name: cherrypicker
        image: gcr.io/k8s-prow/cherrypicker:v20230526-bc91fd978b
```

From: https://github.com/knative/infra/blob/main/prow/cluster/control-plane/500-cherrypicker.yaml

**Comment by BenTheElder** [comment]
cherrypick is now at https://github.com/kubernetes-sigs/prow/tree/main/cmd/external-plugins/cherrypicker

unfortunately github cannot move issues across repos, but if you're still interested, please re-file against the prow issue tracker, I'm working on closing out prow issues here
