### ISSUE TITLE
cos-93-lts is deprecated and out of service after October 2023

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/test-infra#29694]
**What should be cleaned up or changed**:

    image_family: cos-93-lts # deprecated after October 2023 (https://cloud.google.com/container-optimized-os/docs/release-notes)

**Provide any links for context**:

https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-serial-gce-e2e-cpu-manager is one case
- the cos-93-lts  is using containerd 1.4 which is installed with docker 20.10.3.

https://storage.googleapis.com/k8s-triage/index.html?job=pull-kubernetes-node-kubelet-serial-cpu-manager

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/pull/118021/pull-kubernetes-node-kubelet-serial-cpu-manager/1658364455777472512
```
W0516 07:04:59.849] test/e2e_node/e2e_node_suite_test.go:208
W0516 07:04:59.849] 
W0516 07:04:59.849]   [FAILED] Unexpected error:
W0516 07:04:59.849]       <*fmt.wrapError | 0xc000e6cae0>: 
W0516 07:04:59.849]       validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/containerd/containerd.sock": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService
W0516 07:04:59.849]       {
W0516 07:04:59.849]           msg: "validate service connection: validate CRI v1 runtime API for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService",
```
for containerd too old.

**Comment by pacoxu** [comment]
/sig node
/cc @SergeyKanzhelev @bobbypage 

deprecated message was added in https://github.com/kubernetes/test-infra/pull/24152

**Comment by SergeyKanzhelev** [comment]
/assign @mmiranda96 

can you please take a look?

**Comment by dims** [comment]
no more `cos-93-lts` https://cs.k8s.io/?q=cos-93-lts&i=nope&files=&excludeFiles=&repos=
