### ISSUE TITLE
The approval bot doesn't recognize references to other repos

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#2975]
Happened for instance in https://github.com/kubernetes/kubernetes/pull/46745#issuecomment-306377228, where there is a "fixes: " link to an issue in the kubeadm repo.

cc @dchen1107 @grodrigues3 @apelisse @kubernetes/sig-contributor-experience-bugs

**Comment by apelisse** [comment]
Yeah, sorry about that, we've made a fix quickly yesterday but couldn't find the time to redeploy the queue. I'll do it now.

**Comment by apelisse** [comment]
Fixed by #2968
