### ISSUE TITLE
Gubernator is turned down for two weeks and do we plan to revive it?

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/test-infra#29784]
https://github.com/kubernetes/test-infra/blob/35a0ce52940d6bfdc7f495ee2a9c6364992bf0e8/gubernator/README.md?plain=1#L1

https://groups.google.com/a/kubernetes.io/g/dev/c/SIpSxGqu_3Q

It seems to be related to a security issue. Do we plan to just close it or is there a fixed plan for the security problem?

**Comment by cblecker** [comment]
/sig testing
xref: https://github.com/kubernetes/k8s.io/issues/789
