### ISSUE TITLE
Update pinned image on Node jobs in sig-release

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/test-infra#29814]
**What should be cleaned up or changed**:
A couple of jobs are using a pinned old image `cos-85-13310-1041-9`. COS 85 has been deprecated for a while:
- [ci-kubernetes-e2e-gce-device-plugin-gpu-1-24](https://github.com/kubernetes/test-infra/blob/90217f9fcb6bd29cb4a18b371542a3d739573031/config/jobs/kubernetes/sig-release/release-branch-jobs/1.24.yaml#L60)
- [ci-kubernetes-e2e-gce-device-plugin-gpu-1-25](https://github.com/kubernetes/test-infra/blob/90217f9fcb6bd29cb4a18b371542a3d739573031/config/jobs/kubernetes/sig-release/release-branch-jobs/1.25.yaml#L60)

These jobs need to be updated to a more recent image, minimum an image from `cos-97-lts`. Ideally, it should even use to use an image family instead of a pinned image.

/kind cleanup
/sig node
/area testing
/priority important-soon

**Comment by kannon92** [comment]
/priority backlog

@mmiranda96 @SergeyKanzhelev Given that 1.24/1.25 are out of support, is this still necessary?

**Comment by mmiranda96** [comment]
I don't think so. Are the 1.24/1.25 jobs deleted now?

**Comment by kannon92** [comment]
yes, those are deleted. 

/close
