### ISSUE TITLE
Periodic job ci-node-e2e-crio-dra failing with "could not start the process: fork/exec --root=/go/src: no such file or directory" error

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/test-infra#29819]
**What happened**:

New periodic job [ci-node-e2e-crio-dra](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/dynamic-resource-allocation.yaml#L48) fails with hard to understand error:
```
could not start the process: fork/exec --root=/go/src: no such file or directory
```

**What you expected to happen**:

The job to run successfully or at least fail with enough information for further debugging.

**How to reproduce it (as minimally and precisely as possible)**:

Explore the latest job failure at https://k8s-testgrid.appspot.com/sig-node-dynamic-resource-allocation#ci-node-e2e-crio-dra

**Please provide links to example occurrences, if any**:

https://k8s-testgrid.appspot.com/sig-node-dynamic-resource-allocation#ci-node-e2e-crio-dra

**Anything else we need to know?**:

I'm most probably missing something really trivial in the job configuration that makes the CI machinery to consider first arg `--root=/go/src` as an executable path.

I've took [ci-crio-cgroupv1-node-e2e-conformance](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/crio.yaml#L2) job configuration as a base for the `ci-node-e2e-crio-dra` job
However, `ci-crio-cgroupv1-node-e2e-conformance` [works just fine](https://k8s-testgrid.appspot.com/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance) unlike `ci-node-e2e-crio-dra`

**Comment by pohly** [comment]
https://github.com/kubernetes/test-infra/blob/6f00dee98cf0e3a9832e20adc9a82d5e41b65be1/config/jobs/kubernetes/sig-node/dynamic-resource-allocation.yaml#LL58C1-L58C1 is in crio-dra but not in crio-e2e-conformance.

The YAML of the actual test pod is quite different:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-conformance/1669304183158738944
```
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - --root=/go/src
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-node-e2e-crio-dra/1669306950954782720

```
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /tools/entrypoint
    env:
    ...
        - name: ENTRYPOINT_OPTIONS
      value: '{"timeout":7200000000000,"grace_period":900000000000,"artifact_dir":"/logs/artifacts","args":["--root=/go/src","--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)","--timeout=90","--scenario=kubernetes_e2e","--","--deployment=node","--env=KUBE_SSH_USER=core","--gcp-project-type=node-e2e-project","--gcp-zone=us-west1-b","--node-test-args=--feature-gates=\"DynamicResourceAllocation=true\"
        --service-feature-gates=\"DynamicResourceAllocation=true\" --runtime-config=resource.k8s.io/v1alpha2=true
        --container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio
        --container-runtime-pid-file= --kubelet-flags=\"--cgroup-driver=systemd --cgroups-per-qos=true
        --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service\"
        --extra-log=\"{\\\"name\\\": \\\"crio.log\\\", \\\"journalctl\\\": [\\\"-u\\\",
        \\\"crio\\\"]}\"","--node-tests=true","--provider=gce","--test_args=--focus=\"\\[NodeFeature:DynamicResourceAllocation\\]\"
        --skip=\"\\[Flaky\\]\"","--timeout=65m","--node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1-serial.yaml"],"container_name":"test","process_log":"/logs/process-log.txt","marker_file":"/logs/marker-file.txt","metadata_file":"/logs/artifacts/metadata.json"}'
```

I would try to make the crio-dra job as similar to the working job, i.e. remove the (redundant?) `extra_refs`.

**Comment by BenTheElder** [comment]
this job is mixing `decorate: true` and also using bootstrap.py flags, it's not fully migrated to podutils.

**Comment by bart0sh** [comment]
@BenTheElder Thanks. It was my suspicions too that 'decorate' is a culprit. I'll try to remove it.
