### ISSUE TITLE
k8s-ci-robot cannot correctly remove the label related to the deleted code

### ISSUE THREAD

**Issue by rayowang** [kubernetes/test-infra#29856]
**What happened**:
It may be that I used git rebase improperly, which led to the introduction of a large number of new commits in my PR. At this time, k8s-ci-robot added a lot of labels related to these commit codes, but when I removed these incorrect commits Afterwards, k8s-ci-robot did not remove the related label.

**What you expected to happen**:

After removing the commit related to the labeled label, the previously labeled label should also be removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
https://github.com/kubernetes/kubernetes/pull/118636

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
This is not simple, because we have to make sure the label wasn't added by something else, e.g. a human requesting the label be added

**Comment by BenTheElder** [comment]
In any case, the code for this is now in a dedicated repo, if you're still interested in attempting to figure out how this could be done, please file an issue at https://github.com/kubernetes-sigs/prow
