### ISSUE TITLE
Enable go race detector for unit tests

### ISSUE THREAD

**Issue by aojea** [kubernetes/test-infra#29918]
It was enabled in https://github.com/kubernetes/test-infra/pull/29917 but had to be reverted in https://github.com/kubernetes/test-infra/pull/29917 because it uncovered new tests with races.

Opening the issue to not forget we must fix all races and enable the race detector in presubmits

**Comment by listx** [comment]
Link to some of the races that were detected (thanks @pohly for the example): https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/test-infra/29906/pull-test-infra-unit-test/1672049228827856896/build-log.txt. We can start by fixing these first.

**Comment by listx** [comment]
We now have https://testgrid.k8s.io/presubmits-test-infra#unit-test-race-detector-nonblocking&width=20 to look at. So far it looks like the prow/external-plugins/cherrypicker TestCherryPickOfCherryPickPRV2 test is failing, but I'm not sure how to fix it. I don't think there's an explicit race that's been detected, but the test seems to become flaky when we turn on the race detector.

**Comment by aojea** [comment]
race detector has a considerable penalty in performance, I would check if the test is making some assumptions on time and is failing because it is too slow now

**Comment by lubronzhan** [comment]
Any updates on this? I saw several consistent failure in different PR 
https://github.com/kubernetes/test-infra/pull/30308
https://github.com/kubernetes/test-infra/pull/30269
https://github.com/kubernetes/test-infra/pull/30325

**Comment by listx** [comment]
Yeah I'm now thinking that one way to fix this would be to modify the test jobs so that we exclude certain tests from being run together with the race detector (because trying to fix the race-detector-unfriendly jobs is rather time consuming and I don't think anyone has the bandwidth for it).

**Comment by pohly** [comment]
I've implemented something like that for Kubernetes integration tests: https://github.com/kubernetes/kubernetes/pull/116980/commits/f2a237a8039e3a96eca969e526dda15e23844048

**Comment by pohly** [comment]
No idea whether that is even remotely applicable to how test-infra runs unit tests...

**Comment by listx** [comment]
I think it is applicable. I haven't looked too deeply here but we should be able to basically break out the unit test invocation into 2 separate invocations. That seems to be what you're doing in the link you provided (thanks for the reference!).
