### ISSUE TITLE
Post-vsphere-csi-driver-deploy prow job is failing

### ISSUE THREAD

**Issue by chethanv28** [kubernetes/test-infra#29928]
**What happened**:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-vsphere-csi-driver-release jobs are failing and as a result of whiich the CSI images are not getting pushed to gcr.io/cloud-provider-vsphere/csi/release.
The failure observed in the jobs are:

```
The pod could not start because it could not mount the volume "cloud-provider-vsphere-e2e-config": secret "cloud-provider-vsphere-e2e-config" not found
```

prowjob_name: post-vsphere-csi-driver-deploy prowjob_config_url: https://git.k8s.io/test-infra/config/jobs/kubernetes-sigs/vsphere-csi-driver/vsphere-csi-driver.yaml

**What you expected to happen**:

https://git.k8s.io/test-infra/config/jobs/kubernetes-sigs/vsphere-csi-driver/vsphere-csi-driver.yaml should successfully build and push CSI images after new commits are merged to the repo: https://github.com/kubernetes-sigs/vsphere-csi-driver

**How to reproduce it (as minimally and precisely as possible)**:
Any new commit to the https://github.com/kubernetes-sigs/vsphere-csi-driver/commits/master repo will have a failed job

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/vmware-postsubmits-vsphere-csi-driver#post-vsphere-csi-driver-deploy
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-vsphere-csi-driver-release/1672470116366815232

**Anything else we need to know?**:
This is blocking CSI releases and new tags

**Comment by chethanv28** [comment]
cc: @divyenpatel

**Comment by rjsadow** [comment]
/assign 
Thanks @chethanv28 this is likely due to a migration to the eks cluster. I'll take a look and put out a fix a bit later today.

**Comment by chethanv28** [comment]
> /assign Thanks @chethanv28 this is likely due to a migration to the eks cluster. I'll take a look and put out a fix a bit later today.

Thanks for the quick response @rjsadow . We will look forward to the fix, as this is blocking vsphere-csi-driver build & image push.
