### ISSUE TITLE
Migrated prow jobs does not keep the Jenkins build number

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#2996]
Basically testgrid will not display newer entries. We should either somehow let tot start with a specific build id, or sort testgrid entries by build time?

The renamed jobs are fine.

ref https://github.com/kubernetes/test-infra/pull/2936

cc @wonderfly 
/assign
/assign @rmmh @spxtr

**Comment by wonderfly** [comment]
cc @kewu1992 Would this impact our release dashboard?

**Comment by rmmh** [comment]
Which jobs in particular are having problems?

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/google-gci-dev the ones without a dot

**Comment by kewu1992** [comment]
@krzyzacy What do you mean 'it won't display newer entries'? Does it mean it will start counting from 0?

**Comment by krzyzacy** [comment]
@kewu1992 yes, we are trying something

In the meantime you can mornitor jobs from places like:
http://prow.k8s.io/?type=periodic&job=ci-kubernetes-e2e-gce-gci-qa-m59
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-gci-qa-m59/?before=60

**Comment by krzyzacy** [comment]
thanks @rmmh, it should pick up the last build number now

**Comment by krzyzacy** [comment]
@rmmh it bumped back again 😢

**Comment by wonderfly** [comment]
Any updates on this?

**Comment by rmmh** [comment]
Renumbered again, should recover tonight.

**Comment by BenTheElder** [comment]
For future reference:
```
make -C prow get-cluster-credentials
kubectl run curl --image=radial/busyboxplus:curl -i --tty
[ root@curl-6896d87888-dxl6q:/ ]$ curl -X POST -d "5413" http://tot/vend/pull-kubernetes-cross
```
Is an easy way for those with access to the prow cluster to bump job=`pull-kubernetes-cross`, to id=`5413`.
