### ISSUE TITLE
enable needs-triage for cloud-provider-gcp doesn't work

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/test-infra#29975]
**What happened**:
In #29501 needs-triage label was added to kubernetes/cloud-provider-gcp repository, however it doesn't work.

**What you expected to happen**:

Issues like kubernetes/cloud-provider-gcp#560 and kubernetes/cloud-provider-gcp#574 shoud get `needs-triage` label.

**How to reproduce it (as minimally and precisely as possible)**:

Open new issue in kubernetes/cloud-provider-gcp repository.

**Please provide links to example occurrences, if any**:

Attempt to add label in #29501.

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
we'll probably need someone more familiar with the current state of prow.
sorry I've been out of office mostly, cc @cjwagner @listx

**Comment by BenTheElder** [comment]
best guess we missed enabling the plugin even though we configured it for the repo and the plugin isn't enabled across the whole org. (It probably should be?). will check.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/blob/d6896fe09d0b2c79f4f2c581583834f086774efb/config/prow/plugins.yaml#L1117

should be on for the whole org. hmm. might need someone with access to the cluster logs.

**Comment by BenTheElder** [comment]
seems to be https://github.com/kubernetes/test-infra/pull/30086

**Comment by BenTheElder** [comment]
it's fixed, sorry for the delay. https://github.com/kubernetes/cloud-provider-gcp/issues/579#event-9815147124
