### ISSUE TITLE
Prow issue: pull-kubevirt-fossa repeated failed

### ISSUE THREAD

**Issue by naiming-zededa** [kubernetes/test-infra#30005]
my PR: https://github.com/kubevirt/kubevirt/pull/9668, had test 'pull-kubevirt-fossa' repeated failed (after multiple /retest), and the errors I don't understand how can this related to the PR commit itself. Two errors lists, one is "Missing 'origin' git remote", and the other is "Could not find executable: `svn`", both of them I would link it is testing infra related, not specific to my code change in the PR above. Could you investigate the causes? thanks.

**Comment by BenTheElder** [comment]
That's not a problem with our CI tooling, that's a problem with kubevirt's usage of it. If their scripts are going to invoke svn / git they need to use images that contain them. Prow itself is not interacting with svn.

**Comment by BenTheElder** [comment]
Sorry, someone from kubevirt will have to investigate their configuration. Prow runs tests in containers and the command + image is user-supplied.
