### ISSUE TITLE
aws-load-balancer-controller-unit-test presubmit jobs failing

### ISSUE THREAD

**Issue by kishorj** [kubernetes/test-infra#30027]
**What happened**:
The aws-load-balancer-controller-unit-test presubmit jobs have been failing since the recent migration of the test jobs to eks cluster. Here is the error message:
```
The pod could not start because it could not mount the volume "coveralls": secret "k8s-aws-alb-ingress-coveralls-token" not found
```
Please copy the secret over to the new prow cluster or provide instructions to do so.

**What you expected to happen**:
Presubmit jobs are successful. 

**How to reproduce it (as minimally and precisely as possible)**:
All recent PRs are failing the presubmit step - https://github.com/kubernetes-sigs/aws-load-balancer-controller/pulls

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-load-balancer-controller/3274/pull-aws-load-balancer-controller-unit-test/1676652904175374336

**Anything else we need to know?**:

**Comment by upodroid** [comment]
Hi

You need to partially revert https://github.com/kubernetes/test-infra/pull/29879

The unit-test requires coveralls secret which isn't present on the EKS Cluster.

Thanks
