### ISSUE TITLE
Update Lgtm tooltip description to be consistent with the onboarding docs

### ISSUE THREAD

**Issue by Jaswir** [kubernetes/test-infra#30066]
Tooltip could say: "Looks good to me", a PR is ready to merge, that would fit with information on the onboarding docs: https://www.kubernetes.dev/docs/onboarding/04-issues-management/#/5

**Comment by Priyankasaggu11929** [comment]
Resolved by https://github.com/kubernetes/test-infra/pull/30065

/close
