### ISSUE TITLE
Mass job status change API

### ISSUE THREAD

**Issue by smg247** [kubernetes/test-infra#30108]
**What would you like to be added**:
A simple API to mass update statuses of jobs based on filtering criteria:

- cluster
- state
- started_after
- started_before
- job type

There would be a single endpoint that would accept the above criteria, and find and update all matching `ProwJobs` to the provided state.

**Why is this needed**:
OpenShift recently experienced an outage in one of the build clusters in our Prow instance. Due to this, we had a large number of jobs stuck in the `triggered` state. We could have made good use of something that allowed us to abort all of these jobs. I think a general purpose API to update the status of jobs would be useful for other purposes as well, but the most salient use case would be mass-abort by criteria.

**Comment by smg247** [comment]
It also might be useful if filtering could be done by `org` and `repo` as well.

**Comment by petr-muller** [comment]
@Prucek is working on this

**Comment by Prucek** [comment]
@petr-muller maybe we can close this issue here?, since it was recreated in the prow repo: https://github.com/kubernetes-sigs/prow/issues/115

**Comment by petr-muller** [comment]
/close

Sounds good!
