### ISSUE TITLE
Indicate clearly when the problem with the run was due to e2e-up.

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#3010]
As an example, see kubernetes/kubernetes#45135 reporting on https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41583/pull-kubernetes-e2e-gce-etcd3/27780/

I guess we already do indicate that the problem is due to e2e-up, but perhaps we could extract the key line?

```
I0428 10:58:48.942] �[0;33mDetected 4 ready nodes, found 4 nodes out of expected 5. Your cluster may not be fully functional.�[0m
```

**Comment by fejta** [comment]
kubetest does this now
