### ISSUE TITLE
RFC: mungegithub/prow: Have a checkbox list of reviewers "todo"

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#3023]
OK, Here's the idea. I'm tempted to have either `prow` or the `mungebot` post a message in each pull-requests giving reviewers a quick reminder of things that they should care about. Feel free to also discuss that potential list.

> Hey John, you have been assigned as a reviewer for this pull-request, here is a list of things to consider:
> - [ ] Errors are not capitalized and do not end with a period
> - [ ] Well tested?
> - [ ] E2E can be replaced with unit-tests?
>
> Also please refer to this [page](do-we-have-that?) for more information

We should probably have short sentences, maybe with links to actual documentation/guidelines. Can someone remind me where the guidelines are?

This is also inspired by https://github.com/kubernetes/kubernetes/issues/15863

**Comment by apelisse** [comment]
cc @thockin @spxtr

**Comment by spxtr** [comment]
> If you plan on reviewing golang code changes, please read [CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments) and [Effective Go](https://golang.org/doc/effective_go.html).

**Comment by spiffxp** [comment]
@kubernetes/sig-contributor-experience-proposals @kubernetes/sig-testing-proposals

**Comment by spiffxp** [comment]
> Doesn't add any new package level variables
> Doesn't add an init function

ref: https://groups.google.com/forum/#!topic/kubernetes-sig-testing/zVh200YpPac

I know at least the latter would be difficult to enforce unless we at least had special cases that are allowed, documented by issues.  eg: you can add a new prow plugin that uses `init` if you reference an issue that describes plans to remove that `init` pattern

**Comment by apelisse** [comment]
Well, I think the goal is to provide guidelines, not something we want to strictly enforce. The reason why we have human reviewers ;-)

**Comment by apelisse** [comment]
I've added current suggestions to the template

**Comment by stevekuznetsov** [comment]
Some of the specific code-level things like new globals or capitalized errors could be enforced with a linter based on [`go/ast`](https://golang.org/pkg/go/ast/) -- or, instead of enforcement, it could just flag issues for reviewers to look at.

**Comment by spiffxp** [comment]
@apelisse lol yeah I just meant making sure the intent was clear and bright-lining what the exceptions are

**Comment by fejta** [comment]
Having new issues post a blurb sounds useful (prow/plugins/advertise.go).

Making whatever code behavior we want into a presubmit check will be way more effective though (nobody reads docs).

**Comment by apelisse** [comment]
@fejta 100% agree with that. But there are things better done by humans

**Comment by stevekuznetsov** [comment]
Sorry, I know I'm coming in here from nowhere -- I mostly on testing for downstream OpenShift Origin. From my experience doing a similar thing, the list of things to do becomes useless for the majority of contributors that do more than the odd review. People very quickly learn to filter out lists they see everywhere. As the list grows it gets glossed over as a tl;dr more and more. 

The list here should use source parsing to give specific suggestions if the parsing is not good enough or has too many edge cases to be a hard presubmit check, otherwise it may very quickly become noise that does few people any good. 

`</unsolicited-advice>`
