### ISSUE TITLE
Project type `scalability-scale-project` can't be acquired from boskos in gce-master-scale-correctness and gce-master-scale-performance tests.

### ISSUE THREAD

**Issue by pawbana** [kubernetes/test-infra#30259]
**What happened**:
Tests  [gce-master-scale-correctness](https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness) and [gce-master-scale-performance](https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance) fail with `failed to prepare test environment: --provider=gce boskos failed to acquire project: resources not found` error.

**What you expected to happen**:
I expect tests to be able to acquire project type `scalability-scale-project` from boskos.

**How to reproduce it (as minimally and precisely as possible)**:
Run those test.

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1684972421649534976
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1684609962237497344

**Comment by ameukam** [comment]
`ci-kubernetes-e2e-gce-scale-performance` was able to acquire the gce resource. Currently with https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1686421842346119168
