### ISSUE TITLE
[Umbrella issue] Move prowjobs to k8s-infra-prow-build

### ISSUE THREAD

**Issue by ameukam** [kubernetes/test-infra#30277]
Move all the prowjobs running on the `default` cluster to `k8s-infra-prow-build`. 

Currently, there is some difficulty to identify those running e2e tests on GCP. 

Some of them uses specific credentials and are not eligilibe. Credentials are passed to those jobs are presets:

```
preset-do-credential-*
preset-aws-credential-*
preset-azure-*
```

/sig testing
/sig k8s-infra

**Comment by rjsadow** [comment]
Is there a point where we should add a check to require new jobs to define a community cluster to use?

**Comment by ameukam** [comment]
> Is there a point where we should add a check to require new jobs to define a community cluster to use? 

when we have no jobs running in the cluster `default`.

**Comment by BenTheElder** [comment]
We have other tracking issues, and we're not necessarily moving them to k8s-infra-prow-build

https://github.com/kubernetes/test-infra/issues/29722
