### ISSUE TITLE
Add CI to kubernetes/community

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#3034]
- [ ] Run sig docs generator golang unit tests (https://github.com/kubernetes/community/pull/726)
- [x] Run sig docs verify script (https://github.com/kubernetes/community/pull/847)

@kubernetes/sig-testing-misc @jamiehannaford @jbeda 
Ref: https://github.com/kubernetes/community/pull/707

**Comment by spiffxp** [comment]
ref #3675
this issue seems mostly related to prow instead of mungegithub, but if that gets turned up, we may want to use these jobs to gate certain PR's

**Comment by cblecker** [comment]
The `make verify` and `make test` Makefile rules are set up and working in kubernetes/community. We would just need the infra pieces to hook in and run them.

cc: @grodrigues3
