### ISSUE TITLE
Some jobs (at least kind ones) use the wrong `kubectl` version

### ISSUE THREAD

**Issue by aojea** [kubernetes/test-infra#30345]
Checking the build log it seems the `kubectl` used by the `entrypoint` container for the jobs is not using the compiled versions and most probable the one that comes installed in the `krte` image by `gcloud components install kubectl`

I could only verify that this happens with a few different kind jobs

```
WARNING: version difference between client (1.25) and server (1.29) exceeds the supported minor version skew of +/-1
+ kubectl patch -n kube-system daemonset/kube-proxy --type=json -p=[{"op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--v=4" }]
daemonset.apps/kube-proxy patched
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/119835/pull-kubernetes-e2e-kind/1688980783198375936/build-log.txt

**Comment by BenTheElder** [comment]
This is either a bug in the kind scripts or in the kubernetes/kubernetes scripts.

I thought? that the kubernetes/kubernetes ginkgo e2e script would locate the built kubectl and put it in path but maybe not.

Either way, the system kubectl isn't supposed to be used when running these jobs, the kubectl provided in KRTE is ~fine but it should be using the e2e-built kubectl for this use case.

/assign

**Comment by BenTheElder** [comment]
I think we can close this, after https://github.com/kubernetes-sigs/kind/pull/3328
