### ISSUE TITLE
Migrated Prow job failing

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#3038]
It seems that the gci-gke-ingress-release-1-6 job is failing consistently due to quota issues since being moved to Prow:

https://k8s-testgrid.appspot.com/release-1.6-blocking#gci-gke-ingress-1.6&width=20
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress-release-1-6/11

```
googleapi: Error 403: Quota 'BACKEND_SERVICES' exceeded. Limit: 5.0, quotaExceeded
```

It was passing before the move:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress-release-1.6/4598/finished.json

**Comment by enisoc** [comment]
@krzyzacy The symptoms seem similar to https://github.com/kubernetes/kubernetes/issues/43466.

**Comment by krzyzacy** [comment]
probably https://github.com/kubernetes/kubernetes/issues/47397

**Comment by krzyzacy** [comment]
let me check the project and do some cleanup

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-ingress-release-1-6/12 seems green now, but that ingress test might still leak resource until the actual issue is resolved. I'll close this, feel free to reopen if it fails again.

**Comment by enisoc** [comment]
Thanks @krzyzacy. For future reference, was it fixed because you did some cleanup? Or did it fix itself?

**Comment by krzyzacy** [comment]
yes - I ran `./jenkins/janitor.py --project=k8s-jkns-gci-gke-ingress-1-6 --hour=3`
