### ISSUE TITLE
Build Developer Image for Dev Containers / Github Codespaces

### ISSUE THREAD

**Issue by Sharpz7** [kubernetes/test-infra#30454]
https://github.com/kubernetes/kubernetes/issues/113019

Relating to this issue, and relating to the work in this fork (https://github.com/craiglpeters/kubernetes-devcontainer), I want to add a cloudbuild.yaml that is able to build and push the image based on what is in k/k master. 

From there we can expand to hit more usecases. There are some subtilties in terms of how the image is built (It does not use a Dockerfile, and instead uses devcontainers themselves, but we should be able to do this ourselves with https://github.com/devcontainers/cli and https://github.com/craiglpeters/kubernetes-devcontainer/blob/master/.github/workflows/devcontainer-build-and-push.yml as reference.

cc @dims @craiglpeters

**Comment by BenTheElder** [comment]
>  I want to add a cloudbuild.yaml that is able to build and push the image based on what is in k/k master.


It's not clear that SIG Testing should be funding resources for this particular development environment offering.

**Comment by Sharpz7** [comment]
Closing because the kubecross image can get the job done
