### ISSUE TITLE
bot doesn't always label "needs-sig" to issues which don't have sig label

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3058]
In this issue https://github.com/kubernetes/kubernetes/issues/47520, there is neither a "sig/foo" nor "needs-sig" label. There should be either of them.

/cc @crimsonfaith91

**Comment by crimsonfaith91** [comment]
The bot added it. The delay may due to submit queue order.

**Comment by xiangpengzhao** [comment]
I see that bot finally added `needs-sig` label 6 hours later after the issue was create...
