### ISSUE TITLE
Running queue-health containers as part of submit-queue to enable running against multiple repositories

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#306]
As part of https://github.com/kubernetes/contrib/issues/1304, we are trying to get the submit-queue to run against other kubernetes org repositories.
The _chart_ and _history file_ generation. would need to be run per submit-queue instance.

**Comment by foxish** [comment]
The idea so far is to run the queue-health container as part of the submit-queue deployment. Does that sound ok?
From a cursory look, some refactoring seems to be needed to accept some parameters as flags. I can send a PR for that.

cc @fejta

**Comment by fejta** [comment]
Yes putting the queue-health into the submit-queue deplyoment sgtm

**Comment by foxish** [comment]
On second thought, it doesn't look like the volume of incoming PRs to the other repositories is very high and we may not even use the bot to perform merges, which would mean the queue-health charts aren't necessary yet for the other repos. So, perhaps there is no need to merge the two for now.

**Comment by fejta** [comment]
Is this still happening?

**Comment by foxish** [comment]
@fejta Yes, I was a little sidetracked by other things. I'll get to this item again soon. It would now just be moving these containers into the submit-queue YAML and shouldn't be much effort.

**Comment by foxish** [comment]
@apelisse Would you be able to take this? There isn't much left to be done, except to add these jobs to mungegithub/submit-queue/deployment.yaml, and then killing the separate deployments from the util cluster.

**Comment by apelisse** [comment]
Yeah, please just let me know you would have 2 minutes to explain me what needs to be done :D

**Comment by apelisse** [comment]
OK, So it means you want to run [this container](https://github.com/kubernetes/test-infra/tree/master/queue-health) from within the submit-queue `deployment.yaml`?

**Comment by foxish** [comment]
@apelisse Yes, the grapher and poller containers should run as part of each submit-queue instance.

**Comment by apelisse** [comment]
I'll try to get this done when I have time :-)

**Comment by apelisse** [comment]
@foxish I'll try to deprecate that instead (and use velodrome)

**Comment by apelisse** [comment]
Feel free to close the issue, or keep it open until I have actually migrated ...
