### ISSUE TITLE
bot's comment is not so helpful

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3060]
>There are no sig labels on this issue. Please add a sig label by:
(1) mentioning a sig: @kubernetes/sig-<team-name>-misc
(2) specifying the label manually: /sig <label>
Note: method (1) will trigger a notification to the team. You can find the team list here and label list here

I saw some contributors comment `/sig sig/aws` to label an issue. It's an incorrect way. But per the bot's above comment `specifying the label manually: /sig <label>` and the [label list](https://github.com/kubernetes/kubernetes/labels) it provides, contributors will derive the incorrect way naturally.

Also, contributors might be confused by team-name. e.g. there is team `Cluster Lifecycle` in [team list](https://github.com/kubernetes/community/blob/master/sig-list.md), how to specify `@kubernetes/sig-<team-name>-misc` for this team? The correct way is `@kubernetes/sig-cluster-lifecycle-misc`, but contributors might try `@kubernetes/sig-Cluster Lifecycle-misc` which is incorrect.

**Comment by grodrigues3** [comment]
/assign @crimsonfaith91 
is this something you can work on?

**Comment by crimsonfaith91** [comment]
@grodrigues3 I would like to, but I am currently fully loaded on a main repo issue and the bot comment standardization test-infra PR. Will it be fine for me to look at this around 2 weeks from now?

**Comment by crimsonfaith91** [comment]
i will work on this. The new comment will give an example of how to mention a sig group and add a label.

There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:
(1) mentioning a sig: `@kubernetes/sig-<team-name>-misc`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e.g., **@kubernetes/sig-api-machinery-misc** for API Machinery
(2) specifying the label manually: `/sig <label>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e.g., **/sig-scalability** for sig/scalability

_Note: method (1) will trigger a notification to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels)_

**Comment by spxtr** [comment]
> (2) specifying the label manually: `/sig <label>`
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e.g., **/sig-scalability** for sig/scalability

`/sig scalability`?

**Comment by crimsonfaith91** [comment]
@spxtr yup! there was a typo. updated my comment with `/sig scalability`. thanks for pointing it out! :)

**Comment by crimsonfaith91** [comment]
There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br>(1) mentioning a sig: `@kubernetes/sig-<team-name>-misc`<br>_e.g., @kubernetes/sig-api-machinery-misc for API Machinery_<br>(2) specifying the label manually: `/sig <label>`<br>_e.g., /sig scalability for sig/scalability_<br><br>_Note: method (1) will trigger a notification to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels)_

**Comment by crimsonfaith91** [comment]
Add examples to sig-mention-handler munger's comment.
/close
