### ISSUE TITLE
We build 1.8.0-alpha which does not include 1.7 bits

### ISSUE THREAD

**Issue by timothysc** [kubernetes/test-infra#3063]
There are a number of weird deployment issues that come into play on version checks with this.  
https://github.com/kubernetes/kubernetes/pull/47438 

IMO we should never do this. 

/cc @dchen1107

**Comment by luxas** [comment]
@timothysc Could you move to kubernetes/release?

**Comment by timothysc** [comment]
Dawn asked me to open it here, but sure.
