### ISSUE TITLE
Simple page to view/display failures-latest.json

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#30646]
We have some good data here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

This json file is part of metrics we collect, info here:
https://github.com/kubernetes/test-infra/blob/master/metrics/README.md#metrics

We need a simple html page that displays the data as a table similar to something i generated by [hand here](https://github.com/kubernetes/test-infra/issues/29678#issue-1740417062):
![image](https://github.com/kubernetes/test-infra/assets/23304/181bf821-9584-4aad-8e88-7efb742ac3d0)

This will help make it easier to go and burndown these long suffering CI jobs that are broken (either fix it or remove it). 

Bonus points for
- creating URL(s) to the config definitions in test-infra (example url is `https://cs.k8s.io/?q=pull-kubernetes-node-kubelet-serial-cpu-manager&repos=kubernetes/test-infra` for the `pull-kubernetes-node-kubelet-serial-cpu-manager` job)
- creating URL(s) to the prow recent runs (example url is `https://prow.k8s.io/?job=pull-kubernetes-node-kubelet-serial-cpu-manager` for the same job above)

**Comment by dims** [comment]
Another bonus : Ability to sort the table - https://github.com/kubernetes/kubernetes/issues/118441#issuecomment-1711270183

**Comment by CIPHERTron** [comment]
> Another bonus : Ability to sort the table - [kubernetes/kubernetes#118441 (comment)](https://github.com/kubernetes/kubernetes/issues/118441#issuecomment-1711270183)

Sure. That would be easy to implement

The sort functionality will be based on the number of days failed right?

**Comment by dims** [comment]
Sort by days is fine. we can add Sort by name as well as a stretch goal

**Comment by CIPHERTron** [comment]
Here's a simple table to display the failures-latest.json [[GitHub Repo](https://github.com/CIPHERTron/failure-table)]
https://k8s-metrics-failures-latest.netlify.app

But when I try to fetch it from https://storage.googleapis.com/k8s-metrics/failures-latest.json, I am getting a CORS error. One way to override this is to create a proxy-server 🤔 

I'm now working on the bonus features 🙌🏻

**Comment by dims** [comment]
@CIPHERTron sorry CNCF primarily works with Apache License ... looks like you have marked your repo with a different license.

**Comment by dims** [comment]
We now have https://storage.googleapis.com/k8s-metrics/index.html
