### ISSUE TITLE
Remove trailing whitespace from jobs/config.json

### ISSUE THREAD

**Issue by mindprince** [kubernetes/test-infra#3067]
Currently, `jobs/config.json` has a lot of trailing whitespaces. You can't add new configs without the trailing whitespace because test fail when you do so. This is because `jobs/config_sort.py` produces json with trailing whitespace.

We need to update jobs/config_sort.py with the following diff to produce output with no trailing whitespace:
```diff
diff --git a/jobs/config_sort.py b/jobs/config_sort.py
index d9ff347f..fee0954d 100755
--- a/jobs/config_sort.py
+++ b/jobs/config_sort.py
@@ -30,7 +30,7 @@ def sort():
     with open(test_infra('jobs/config.json'), 'r+') as fp:
         configs = json.loads(fp.read())
         fp.seek(0)
-        fp.write(json.dumps(configs, sort_keys=True, indent=2))
+        fp.write(json.dumps(configs, sort_keys=True, indent=2, separators=(',', ': ')))
         fp.write('\n')
         fp.truncate()
```

Let me know if this is acceptable and I will send a PR.

**Comment by krzyzacy** [comment]
ah, thanks, I was wondering why

**Comment by krzyzacy** [comment]
also update https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap_test.py#L2241, and send the PR to my way :-)
