### ISSUE TITLE
trigger_github_workflows retriggers all workflows on retest instead of failed jobs

### ISSUE THREAD

**Issue by akhilerm** [kubernetes/test-infra#30713]
**What happened**:
We are using `trigger_github_workflows: true`  for containerd  to retrigger failed github action workflows using `/retest` command.
https://github.com/kubernetes/test-infra/blob/310ba8c07767fb2eda4d09a1d2d5126d949018e9/config/prow/plugins.yaml#L26-L29

But while commenting `/retest`, all the worflows are retriggered irrespective of whether its passed or failed. Ref https://github.com/containerd/containerd/pull/9087/checks.  It can be seen that all the jobs have an `Attempt #2`.  Another thing to note is that `Attempt #1` of all jobs are now marked as failed  even though if you check `Attemp #1` was successful (This can be verified by checking the status of individual jobs at the above link)

**What you expected to happen**:
Only failed github action workflows should have been retriggered. 

**How to reproduce it (as minimally and precisely as possible)**:
Faced the issue only once in containerd repo. Will update if any further occurences are shown w.r.t retest. 

**Please provide links to example occurrences, if any**:
https://github.com/containerd/containerd/pull/9087/checks

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
We're generally not using actions for blocking presubmits alongside prow in the Kubernetes project.
I'm not sure if anyone is on hand to debug issues like this.

**Comment by samuelkarp** [comment]
This happened again on https://github.com/containerd/containerd/pull/9300 and surprised me since I wasn't aware of https://github.com/kubernetes/test-infra/pull/29988.
