### ISSUE TITLE
bot doesn't allow collaborators to `/retest` their own PR

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3071]
@MikeSpreitzer is a collaborator. He tried to retest his PR but bot didn't allow to do this.

See: https://github.com/kubernetes/kubernetes/pull/47262#issuecomment-308505283

```
@MikeSpreitzer: you can't request testing unless you are a kubernetes member.
```

**Comment by spxtr** [comment]
The [community membership](https://github.com/kubernetes/community/blob/6f157597ea688f4b555f3335980963bb3b090a75/community-membership.md) page isn't super clear as to what is expected here, but I would expect a collaborator to be able to `/retest`.

**Comment by xiangpengzhao** [comment]
Yeah, collaborators should be able to `/retest` their PRs at least.

**Comment by cblecker** [comment]
The PR wasn't marked trusted. No kubernetes member had "ok to test" the PR. Looks like the PR ran a test on LGTM, but had never got the ok that the author could run their own testing.

**Comment by xiangpengzhao** [comment]
closing per Christoph's comment.
/close
