### ISSUE TITLE
prow expects to run on certain namespaces

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3073]
The prow components are expected to run in "default" and the pods used for running the tests in "test-pod".

https://github.com/kubernetes/test-infra/blob/05cd85204300986974625b8eadf40194657e9c83/prow/kube/types.go#L34-L35

Probably both should be configurable.

**Comment by spiffxp** [comment]
There's also [a hardcoded `NodeSelector`](https://github.com/kubernetes/test-infra/blob/master/prow/plank/controller.go#L335) for pods that plank creates, dunno if that should be its own issue

**Comment by spxtr** [comment]
> There's also [a hardcoded `NodeSelector`](https://github.com/kubernetes/test-infra/blob/master/prow/plank/controller.go#L335) for pods that plank creates, dunno if that should be its own issue

Lets just remove that. It was a bad decision.
