### ISSUE TITLE
Add presubmit gate to prevent new conformance test promotion without updating conformance metadata

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/test-infra#30770]
**What would you like to be added**:

A presubmit job to fail and provide instruction when conformance metadata is out of sync.

**Why is this needed**:

Tests get promoted in kubernetes/kubernetes/test/e2e without updating the conformance meta, this causes the community's conformance API tool suite [apisnoop.cncf.io](https://apisnoop.cncf.io) to be out of date and be less informative.
The gate will ensure that when a change comes in adding/modifying/removing an e2e test to be a conformance test that the author also updates the [k/k/test/conformance/testdata/conformance.yaml](http://git.k8s.io/kubernetes/test/conformance/testdata/conformance.yaml) is also updated.

---

related: https://github.com/cncf/apisnoop/issues/796

/assign

**Comment by BenTheElder** [comment]
we should be using https://github.com/kubernetes/test-infra/pull/30771#discussion_r1693519104
