### ISSUE TITLE
Post onboarding information for new contributors' first PR

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3083]
There are so many PRs named `Release 1.6` which are created by new contributors.

https://github.com/kubernetes/kubernetes/pull/47418
https://github.com/kubernetes/kubernetes/pull/46616
https://github.com/kubernetes/kubernetes/pull/45470
https://github.com/kubernetes/kubernetes/pull/45396
https://github.com/kubernetes/kubernetes/pull/45205
https://github.com/kubernetes/kubernetes/pull/44823
https://github.com/kubernetes/kubernetes/pull/44183
https://github.com/kubernetes/kubernetes/pull/43733
https://github.com/kubernetes/kubernetes/pull/43547
......

These PRs have the same name and the same info as below:
`xx wants to merge xx commits into master from release-1.6`

They're obviously created by some same mistake. The creator might haven't read the develop docs before they create the PR. They might not know where to find the docs.

We'd better let bot post some onboarding information when it detects a PR is created by a new contributor. So that they can know what's the correct process to create a PR. This will help them not  make mistake next time whether their first process is correct or not.

xref: 
https://github.com/kubernetes/contrib/issues/1090
https://github.com/kubernetes/kubernetes/issues/36596

/cc @bgrant0607 @ConnorDoyle @grodrigues3

**Comment by fejta** [comment]
How do we know if it is their first PR? Might make for an interesting `welcome` plugin (maintain a list of seen users?)

**Comment by BenTheElder** [comment]
I think the most workable solution right now is to make sure the default PR text points you to the contributor guide (which I think it already does now?)

AFAIK you can scrape GitHub for contributor data but there isn't a great way to check per user.
So we'd have to maintain a contributors database ourselves, which would probably be pretty clunky. Example of finding contributors [here](https://github.com/kubernetes/test-infra/blob/master/experiment/find_developers.py)

**Comment by bgrant0607** [comment]
Independently of detecting new contributors it may be useful to detect PRs to the wrong branch, PRs with excessive numbers of commits to the master branch, and other obvious mistakes.

**Comment by fejta** [comment]
PR Linter? I like it

**Comment by xiangpengzhao** [comment]
>Independently of detecting new contributors it may be useful to detect PRs to the wrong branch, PRs with excessive numbers of commits to the master branch, and other obvious mistakes.

Great idea!

**Comment by BenTheElder** [comment]
I don't think there's API access to this yet but they're definitely tracking first time contributors in the GitHub web interface now.

**Comment by BenTheElder** [comment]
This came up again in #sig-contribex slack today, I think we could do this if we:
- used a dedicated bot account to do the queries
- just loaded the first page of results from searching for the user's PRs in the repo

If the number of results is exactly one and there are no other pages, it's a new contributor. 

This would cost one extra token for every opened PR, which should definitely be very manageable on a dedicated account (it might even be manageable on the existing accounts?). Ex [for @nikhita's PRs in test-infra](https://developer.github.com/v4/explorer/?variables=%20%7B%0D%0A%20%20%22query%22%3A%20%22is%3A%20pr%20repo%3Akubernetes%2Ftest-infra%20author%3Anikhita%22%0D%0A%7D&query=query%20%28%24query%3A%20String%21%29%20%7B%0D%0A%20%20search%28query%3A%20%24query%2C%20type%3A%20ISSUE%29%20%7B%0D%0A%20%20%20%20issueCount%0D%0A%20%20%7D%0D%0A%20%20rateLimit%20%7B%0D%0A%20%20%20%20limit%0D%0A%20%20%20%20cost%0D%0A%20%20%20%20remaining%0D%0A%20%20%20%20resetAt%0D%0A%20%20%7D%0D%0A%7D%0D%0A) (currently 12):

<img width="1487" alt="screen shot 2018-07-10 at 7 50 21 pm" src="https://user-images.githubusercontent.com/917931/42548140-854e502a-847a-11e8-8bea-0b892be388f9.png">

**Comment by nikhita** [comment]
> . Ex for @nikhita's PRs in test-infra (currently 12)

That's weird because I only have 11 PRs in test-infra. All of them have been merged and none is open right now: https://github.com/kubernetes/test-infra/pulls?q=is%3Apr+author%3Anikhita+is%3Aclosed.

**Comment by BenTheElder** [comment]
Ah, there's a typo in that, there shouldn't be a space after `is:`, which is not restricting it to PRs, so it's actually counting commits.

**Comment by BenTheElder** [comment]
fixed example:
https://developer.github.com/v4/explorer/?variables=%20%7B%0D%0A%20%20%22query%22%3A%20%22is%3Apr%20repo%3Akubernetes%2Ftest-infra%20author%3Anikhita%22%0D%0A%7D&query=query%20%28%24query%3A%20String%21%29%20%7B%0D%0A%20%20search%28query%3A%20%24query%2C%20type%3A%20ISSUE%29%20%7B%0D%0A%20%20%20%20issueCount%0D%0A%20%20%7D%0D%0A%20%20rateLimit%20%7B%0D%0A%20%20%20%20limit%0D%0A%20%20%20%20cost%0D%0A%20%20%20%20remaining%0D%0A%20%20%20%20resetAt%0D%0A%20%20%7D%0D%0A%7D%0D%0A
<img width="1490" alt="screen shot 2018-07-10 at 8 45 14 pm" src="https://user-images.githubusercontent.com/917931/42549660-334e9854-8482-11e8-9017-6fc45a9ef4ba.png">

**Comment by stevekuznetsov** [comment]
Implemented in #8643 
/close

**Comment by BenTheElder** [comment]
/reopen
we still need to enable and validate this feature, I can do that today
then we'll want to track getting a real, good welcome message configured

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/9227 to enable testing this on test-infra

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/9231 did not work, I think 
[the query works](https://developer.github.com/v4/explorer/?variables=%20%7B%0D%0A%20%20%22query%22%3A%20%22is%3A%20pr%20repo%3Akubernetes%2Ftest-infra%20author%3Aameukam%22%0D%0A%7D&query=query%20%28%24query%3A%20String%21%29%20%7B%0D%0A%20%20search%28query%3A%20%24query%2C%20type%3A%20ISSUE%29%20%7B%0D%0A%20%20%20%20issueCount%0D%0A%20%20%7D%0D%0A%20%20rateLimit%20%7B%0D%0A%20%20%20%20limit%0D%0A%20%20%20%20cost%0D%0A%20%20%20%20remaining%0D%0A%20%20%20%20resetAt%0D%0A%20%20%7D%0D%0A%7D%0D%0A) but possibly we need to delay checking as the API does not immediately reflect this? we need to check for <= 1instead of exactly 1 :grimacing:

**Comment by BenTheElder** [comment]
filed a fix https://github.com/kubernetes/test-infra/pull/9232

**Comment by BenTheElder** [comment]
can confirm that this works now https://github.com/kubernetes/test-infra/pull/9350#issuecomment-420543641

**Comment by spiffxp** [comment]
What's keeping this open at this point?

**Comment by xiangpengzhao** [comment]
Seems like it's done. I'm okay to close it. @BenTheElder any other concerns ? Feel free to close it if needed.

**Comment by xiangpengzhao** [comment]
@BenTheElder is the plugin deployed in k/website? I don't see the onboarding info in https://github.com/kubernetes/website/pull/10712

**Comment by nikhita** [comment]
> is the plugin deployed in k/website?

@xiangpengzhao Nope, only test-infra.

https://github.com/kubernetes/test-infra/blob/c4ad32d6b0c33710684781dc081e6309c1866faa/prow/plugins.yaml#L207-L210

**Comment by xiangpengzhao** [comment]
Thanks @nikhita !

**Comment by BenTheElder** [comment]
poke! this plugin seems to be working pretty well where it is deployed, we just need to do https://github.com/kubernetes/test-infra/issues/9367#issuecomment-455818805 and then roll it out more widely

**Comment by BenTheElder** [comment]
this is basically done?

it might be rolled out more at some point, but the tooling is there and enabled for some repos at least.

**Comment by nikhita** [comment]
> this is basically done?

Yup. Thanks Ben and Guin! :)

/close

**Comment by BenTheElder** [comment]
FWIW last I saw still it was still not enabled generally.

**Comment by nikhita** [comment]
Will follow up on this next week

**Comment by nikhita** [comment]
> FWIW last I saw still it was still not enabled generally.

Thought so too....but turns out it is :P 

https://github.com/kubernetes/test-infra/blob/b23cfa09f0a7e71cebd9b92f85a6eae157f040b4/prow/plugins.yaml#L287-L294
