### ISSUE TITLE
Migrate CRI-O jobs to the community cluster

### ISSUE THREAD

**Issue by kannon92** [kubernetes/test-infra#30888]
xref #30886 

Community cluster migration seems to be an issue for CRI-O jobs.  @harche mentioned that he tried doing this a few years ago but there were some issues with SSH connection.  

> in past whenever we have moved the crio based jobs (FCOS vms) to the community cluster, for yet unknown reason the ssh to that test VM start to fail with the permission denied error. This happens only on the community cluster. I [attempted](https://github.com/kubernetes/test-infra/pull/22228) it about 2 years ago. But had to [revert it](https://github.com/kubernetes/test-infra/pull/22436) because of that ssh issue with the community cluster.

The error is similar to above.

Some of the presubmits are failing due to a partial migration.  

- https://testgrid.k8s.io/sig-node-presubmits#pr-node-memoryqos-cgrpv2
- https://testgrid.k8s.io/sig-node-presubmits#pr-node-crio-cgroupv1-node-e2e-features
- https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-swap-fedora-serial
- https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-crio-cgroupv1

**Comment by kannon92** [comment]
So I have an example presubmit for CRIO that is using the community cluster and it seems to be flaky.

https://testgrid.k8s.io/sig-node-presubmits#pr-node-crio-cgroupv1-node-e2e-features

It looks like sometimes it is able to connect to ssh but other times it can't.

**Comment by BenTheElder** [comment]
> It looks like sometimes it is able to connect to ssh but other times it can't.

Is it using a fixed key or generating one on the fly?

At least in the default cluster there's a general fixed ssh key secret for GCE that we use for throwaway test clusters in most e2e tests. IIRC this avoids issues with spamming the project metadata with keys (been a few years ...). It has to be mounted to a certain path to ensure `gcloud compute ssh` uses it.

**Comment by kannon92** [comment]
So here is my research.

It looks like all crio jobs in presubmit that use the new cluster have this [ignition file](https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/crio/crio_k8s_infra_prow_build.ign) and that does have a public ssh key.

We also set ```IGNITION_INJECT_GCE_SSH_PUBLIC_KEY_FILE``` on the presubmits.  

It looks like the periodics do not point to the new ignition file.  This does not explain why some of the presubmits seem to fail on connection while other times they succeed.

**Comment by dustymabe** [comment]
> It looks like all crio jobs in presubmit that use the new cluster have this [ignition file](https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/crio/crio_k8s_infra_prow_build.ign?rgh-link-date=2023-09-28T19%3A37%3A57Z) and that does have a public ssh key.

Are you talking about the `/etc/ssh-key-secret/ssh-public` entry in that Ignition file? AFAIK that path doesn't get picked up and used by anything so the contents of that file wouldn't end up in the authorized keys for the instance.

**Comment by dustymabe** [comment]
btw if I base64 decode

https://github.com/kubernetes/test-infra/blob/61f80eaf9972232b098f6d69a22ee277987927f5/jobs/e2e_node/crio/crio_k8s_infra_prow_build.ign#L63

I get:

```
$ echo -n 'R0NFX1NTSF9QVUJMSUNfS0VZX0ZJTEVfQ09OVEVOVA==' | base64 -d ; echo
GCE_SSH_PUBLIC_KEY_FILE_CONTENT
```

How does that work?

**Comment by dustymabe** [comment]
> How does that work?

ok looks like it's supposed to get substituted in by [this code](https://github.com/kubernetes/kubernetes/blob/bf1fa0c6691bb3bc6c5c03f900c53ed609e580a4/test/e2e_node/remote/gce/gce_runner.go#L424).

**Comment by kannon92** [comment]
I think a lot of this is due to some of the jobs have been migrated to use crio_k8s_infra_prow_build.ign but not all of them have.  

The proof I have:

https://testgrid.k8s.io/sig-node-presubmits#pr-crio-cgrpv2-gce-e2e and https://testgrid.k8s.io/sig-node-presubmits#pr-crio-gce-e2e were all migrated to use the community cluster.  

Each of these point to a image-config-cgrpv1-k8s-infra-prow-build and image-config-cgrpv2-k8s-infra-prow-build ignition files.

We will work on https://github.com/kubernetes/test-infra/pull/30916 to finish this move for the presubmits.  

Once that is complete, we can then start with the periodics.

**Comment by kannon92** [comment]
So I found out the ssh "magic" happens here:

```
    - name: authorized-key.service
      enabled: true
      contents: |
        [Unit]
        Description=Copy authorized keys
        Before=crio-install.service
        After=network-online.target

        [Service]
        Type=oneshot
        ExecStart=/bin/sh -c '\
          /usr/bin/mkdir -m 0700 -p /home/core/.ssh && \
          /usr/bin/cat /etc/ssh-key-secret/ssh-public \
            >> /home/core/.ssh/authorized_keys && \
          /usr/bin/chown -R core:core /home/core/.ssh && \
          /usr/bin/chmod 0600 /home/core/.ssh/authorized_keys'

        [Install]
        WantedBy=multi-user.target
```

We added this ssh command to the k8s-infra-prow-build ignition files  The ones that did not migrate do not have this.  

@BenTheElder would this explain the flakiness?

**Comment by dustymabe** [comment]
yeah, I still don't understand why that dance is needed.. You can just use a `passwd` stanza instead of writing a file and then having a service copy it into place:

```
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAA...
```

**Comment by dustymabe** [comment]
Did we get the underlying issue with the SSH access figured out?

**Comment by kannon92** [comment]
> Did we get the underlying issue with the SSH access figured out?

The main issue we see is that the ignition files that have the public ssh keys are required.  

The jobs that were failing didn't have this set up so they were failing.

**Comment by dustymabe** [comment]
> The jobs that were failing didn't have this set up so they were failing.

So the problem is understood and the fix is known now? No more mystery?

**Comment by saschagrunert** [comment]
I think we're done for now, other enhancements can be merged without that issue.

/close

**Comment by BenTheElder** [comment]
Glad you got this working, sorry I don't have any recollection of this "ssh key dance" 😅 
On some of the GCP provided images there's an agent that handles the metadata <> ssh keys IIRC, but that's not something anyone working on Kubernetes had anything to do with.
