### ISSUE TITLE
tide is not able to clone repo

### ISSUE THREAD

**Issue by goern** [kubernetes/test-infra#30913]
**What happened**:

`{"branch":"main","component":"tide","controller":"status-update","error":"failed to set up context register: failed to get presubmits: failed to clone repo for \"b4mad/op1st-emea-b4mad\": no ClientForWithRepoOpts implementation exists in the v1 repo client","file":"k8s.io/test-infra/prow/tide/status.go:436","func":"k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1","level":"error","msg":"getting expected status","org":"b4mad","pr":41,"repo":"op1st-emea-b4mad","severity":"error","sha":"b3949b1a578df7d5d67b57b52d9a5ed3cef7ea5d","time":"2023-09-29T07:04:38Z"}`

**What you expected to happen**:

Prow is running the presubmits

**How to reproduce it (as minimally and precisely as possible)**:

fork https://github.com/b4mad/op1st-emea-b4mad
create a PR against it

**Please provide links to example occurrences, if any**:

https://github.com/b4mad/op1st-emea-b4mad/pull/41

**Anything else we need to know?**:

**Comment by goern** [comment]
problem still persists with `gcr.io/k8s-prow/tide:v20231004-f64f17f7bb`. looking through the debug log of tide reveals:

```
{"component":"tide","fields.file":".prow.yaml","file":"k8s.io/test-infra/prow/config/inrepoconfig.go:252","func":"k8s.io/test-infra/prow/config.ReadProwYAML","level":"debug","msg":"Attempting to get inreconfigfile","repo":"b4mad/op1st-emea-b4mad","severity":"debug","time":"2023-10-05T07:01:50Z"}
{"component":"tide","file":"k8s.io/test-infra/prow/config/inrepoconfig.go:321","func":"k8s.io/test-infra/prow/config.DefaultAndValidateProwYAML","level":"debug","msg":"Successfully got 2 presubmits and 0 postsubmits.","repo":"b4mad/op1st-emea-b4mad","severity":"debug","time":"2023-10-05T07:01:50Z"}
{"branch":"main","component":"tide","controller":"status-update","error":"failed to set up context register: contexts op1st/prow/kustomize-build are defined as required and required if present","file":"k8s.io/test-infra/prow/tide/status.go:436","func":"k8s.io/test-infra/prow/tide.(*statusController).setStatuses.func1","level":"error","msg":"getting expected status","org":"b4mad","pr":41,"repo":"op1st-emea-b4mad","severity":"error","sha":"96b24bc00ae3f7068a0b45e0a4f786910f007699","time":"2023-10-05T07:01:50Z"}
```

I can not interpret these messages :/

**Comment by cjwagner** [comment]
I think bumping to `gcr.io/k8s-prow/tide:v20231004-f64f17f7bb` did fix the problem. The new error message indicates a legitimate configuration problem:
> contexts op1st/prow/kustomize-build are defined as required and required if present

**Comment by goern** [comment]
updated all image to `v20231011-acf4a2e26b`, prow seems to be operationa again. I did not identify a root cause.

thanks for taking a look!

/close
