### ISSUE TITLE
Expose git data to prow plugins

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#3092]
Some research I've been doing. I'm interested in any comments by parties interested in prow. @apelisse was interested at one point.

### Motivating use-cases:

1. The approval handler is currently done in mungegithub. It needs to list all changed files in a PR and use nearly OWNERS files to decide whether the PR is approved or not.
1. A gofmt/vet/lint plugin that comments on the diff in a PR. It needs exact diff information along with the full files, so that it can see the entire package but only comment on added lines.
1. The trigger plugin should use configuration checked into each repo under test so that changes can be tested in PRs.

### Solution 1: GitHub API alone

The GitHub API exposes low-level [git data](https://developer.github.com/v3/git/). To use this, we will need to reimplement much of git's friendly UX on top of it. To solve (2) above, we must do the following when a PR event comes in:

1. [Compare the PR head and merge base](https://developer.github.com/v3/repos/commits/#compare-two-commits). This gives us a list of files that are changed in the PR, along with the patches.
1. [Get each .go file](https://developer.github.com/v3/git/blobs/#get-a-blob) and decode. If we want to get the entire package instead of just changed files then we need to make several more API calls.
1. [Run them through golint](https://godoc.org/github.com/golang/lint#Linter.LintFiles). Because we only have individual files and not the whole package, we might get a spurious "set a package-level doc comment" if we set the confidence too low.
1.  Parse the patches from (1) and make a comment for any golint problems on added lines.

This is rather painful for plugin authors to understand. However, solving (3) above would be very easy with this method. It would just be a constant couple API calls per PR update.

### Solution 2: Keep a local git clone

Solving (2) now looks like this when a PR event comes in:

1. If we already have the repo cloned, do a fetch and make sure we have the HEAD commit from the PR.
2. Checkout a working tree, try to merge the PR.
3. Run the changed files through golint. Use standard git and unix tools to handle patches and so on.
4. Make comments.

This is tricky because we now need to keep a mirror git repository. All of a sudden we need to be careful about corrupt repos, garbage collection, and the other nuances of git. We need to very carefully control which operations we allow, since plugins run in parallel and so the git commands need to be thread-safe. This is simpler and more flexible for plugins, but more complicated to implement.

**Comment by apelisse** [comment]
We also have to consider future use-cases, beyond the current set of motivating use-cases.
Are we going to have more and more of these use-cases, and if so, how are these two solutions
going to scale? What other types of operations might be needed in the future?
Even if the number of use-cases stays low, one use-case that would need all the files in the 
repository could use all the token limit in one pass, even with proper caching of all operations.
Beyond the token limit, it would also most likely be extremely slow (`n` calls to the API rather 
than a single optimized `git fetch`).

> This is tricky because we now need to keep a mirror git repository. All of a sudden we need to be careful about corrupt repos, garbage collection, and the other nuances of git. We need to very carefully control which operations we allow, since plugins run in parallel and so the git commands need to be thread-safe. This is simpler and more flexible for plugins, but more complicated to implement.

There's much more than one way to address these concerns. I'd try to have each plugin properly isolated by giving them a fresh copy of the repository. Git [suggests](https://github.com/git/git/blob/826c06412e429a091d32d0e1b26e77da33fc1ce9/t/README#L171) using a `tmpfs` to run its suite of internal tests as it obviously make clones and other operations orders of magnitude faster. If that's not available, a local clone would still be much faster than running hundreds of requests to Github API.

**Comment by spxtr** [comment]
Agreed that solution 1 will probably not suffice.

> I'm not sure why we need to try to merge the PR here. Do we need write access to the repo? Because if we do, we have to discard the first solution.

We do need to merge locally so that we're testing the whole file as it is in the PR. You can't run `go vet` on a patch alone!

> If we want plugins to be able to change the repository locally, we could have each plugin make a `git-clone` copy of the repository.

I think that idea makes the most sense. It's not too expensive, especially if we can get away with a shallow clone and some automated cleanup.

**Comment by kargakis** [comment]
Cloning locally makes sense to me. We are doing git commit message validation on every PR and I could see that being moved into a prow plugin. Do prow plugins run in parallel? From a quick look I had, it seemed they didn't.

cc: @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Interesting idea -- would be extremely cool to factor in some of the other ideas that had been floating around in issues like https://github.com/kubernetes/test-infra/issues/3023 -- any tools based on parsing Go code could plug into this and make comments.

Re: `go vet` and `go lint` -- they both require `$GOPATH`-level scope (for instance, checks like [`unkeyed_composite_literals`](https://golang.org/cmd/vet/#hdr-Unkeyed_composite_literals) need the definition of the `struct` to work) so I think you _need_ a full checkout with dependencies and `$GOPATH` to get the best output from `vet` and `lint`.

**Comment by spxtr** [comment]
> We are doing git commit message validation on every PR and I could see that being moved into a prow plugin.

Sounds like a good motivating case number 4.

> Do prow plugins run in parallel? From a quick look I had, it seemed they didn't.

No, but we should be safe to do so. At least, I put [a comment](https://github.com/kubernetes/test-infra/blob/7865c6d09e2a1f9a20c49b5ade081010709534fc/prow/plugins/plugins.go#L65) saying that it should work.

**Comment by kargakis** [comment]
> No, but we should be safe to do so. At least, I put a comment saying that it should work.

Now they do: https://github.com/kubernetes/test-infra/pull/3159 :)

**Comment by spxtr** [comment]
> We are doing git commit message validation on every PR and I could see that being moved into a prow plugin.

This seems like it would be easiest with the GitHub API, not a local clone. I think you would just use [this API call](https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request) to get the commit messages for the PR.

**Comment by stevekuznetsov** [comment]
@spxtr our validation touches both the commit messages as well as their contents -- an example validation is that a commit touching vendored code for repo `X` declares itself as such in the message. Looks like you can grab [commits](https://developer.github.com/v3/git/commits/) [blobs](https://developer.github.com/v3/git/blobs/) and [trees](https://developer.github.com/v3/git/trees/) but it seems to me that a validator that a dev can use on their local checkout quickly and effectively is more useful than one doing so over the web and relying on GitHub.

**Comment by spxtr** [comment]
Oh I see. Yes, it makes sense to do a local clone for that case.

**Comment by spxtr** [comment]
See [this doc](https://docs.google.com/a/google.com/document/d/1lNWKNeDiHlyUlD_EcFH9EOLGDbnVKZv7yH2yO5YL0YU/edit?usp=sharing) for some more thoughts.
