### ISSUE TITLE
Centralized Prow configuration controller

### ISSUE THREAD

**Issue by droslean** [kubernetes/test-infra#30952]
**What would you like to be added**:
A controller that serves all prow and job YAML configurations. 

**Current State**
The config agent currently reloads files from local storage at every fixed interval, requiring configurations to be mounted to each Prow component.

**Proposed Change**
Introduce a dedicated controller to serve configurations, eliminating the need for local storage. The controller will use REST API or gRPC, with gRPC enabling event-based reloading.

**Implementation**
An extra option can be added to the config agent to switch between local and remote configuration loading, ensuring backward compatibility.

**Benefit**
This eliminates the need to mount configurations to each Prow component, simplifying the setup.

**Discussion Points**
We should consider any potential refactoring challenges or impacts this change might have on the existing system.

/cc @cjwagner @BenTheElder @stevekuznetsov @petr-muller @smg247 @jmguzik @hongkailiu

**Comment by stevekuznetsov** [comment]
What are the benefits to making configuration load a network hop versus a filesystem call? Naively, mounting in volumes sounds like a faster and less error-prone process - what do you envision Prow would do when the network flakes out and it can't reach the configuration server?

**Comment by BenTheElder** [comment]
If there's still interest we should re-file with https://github.com/kubernetes-sigs/prow

So far it seems like we haven't had the bandwidth.
