### ISSUE TITLE
Need 1.6 to master and 1.7 to master upgrade/skew tests

### ISSUE THREAD

**Issue by monopole** [kubernetes/test-infra#3099]
We're missing things in the gap between merges to master and rebasing to 1.7, so need the ->master tests in addition to the ->1.7 tests added in #3005

**Comment by monopole** [comment]
/assign @krzyzacy 

Thanks so much for your help!

**Comment by monopole** [comment]
Hi @dchen1107

**Comment by krzyzacy** [comment]
so, normally it's been created when we care about it, like when 1.8 approaches. I can create those once 1.7 are out.

**Comment by krzyzacy** [comment]
I'll switch 1.4-1.5/1.6 upgrade jobs over to 1.6/1.7-master after we lift code freeze.

**Comment by monopole** [comment]
Also, the idea about having tests configured with branch alias names is terrific - so we always have a latest-2 and latest-1 to master.

We'll need an obvious and indisputable way to be sure latest is what we think it should be.

**Comment by krzyzacy** [comment]
@monopole we can explicitly set name to be 1.6-master, or future 1.8-master on testgrid, even the job name is like k8s-stable2-k8s-dev.

**Comment by monopole** [comment]
I was referring to some vague means to alias branch names at the git level, not just a different name in the test-grid yaml.  Whatever works to avoid having to do those 40+ file pr's (e.g #3005) to get the tests we want with each release.  I'm sure you have a simpler idea to ease this :)

**Comment by krzyzacy** [comment]
yep, we should only need to change something in config.json in the future.

**Comment by krzyzacy** [comment]
I'll yield this to #3150
