### ISSUE TITLE
add nft package to CI images

### ISSUE THREAD

**Issue by danwinship** [kubernetes/test-infra#31009]
from https://github.com/kubernetes/kubernetes/pull/121046#issuecomment-1757357455

> The CI fails because `nft` is not installed, at least some of the jobs I checked
> 
> ```
> 2023-10-11T01:51:14.247153369Z stderr F E1011 01:51:14.247058       1 proxier.go:1421] "nftables sync failed" err="exec: \"nft\": executable file not found in $PATH"
> ```

/assign @aojea

**Comment by aojea** [comment]
@BenTheElder sig-network merged the [KEP for nftables kube-proxy](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3866-nftables-proxy) so I think is ok to add the userspace binary to kind image, WDYT?

**Comment by aojea** [comment]
hmm, it seems that is not a requirement for the host, since kube-proxy is deployed in its own container, we just need to update the distroless-iptables image https://github.com/kubernetes/kubernetes/pull/121046#issuecomment-1758565738

**Comment by BenTheElder** [comment]
we'd need it if kubelet has to make any rules, I haven't managed to read the KEP in detail yet.

also tbd re: kindnetd? I trust your judgement :-)

**Comment by aojea** [comment]
> also tbd re: kindnetd? I trust your judgement :-)

we are in YOLO mode

<img src="https://media2.giphy.com/media/3FTfPdXWJc02xBRWdg/giphy.gif"/>
