### ISSUE TITLE
Tide doesn't see `require_manually_triggered_jobs: true` and tries to merge PR when labels are set and tests are green

### ISSUE THREAD

**Issue by jmguzik** [kubernetes/test-infra#31050]
**What happened**:
When configuring branch protection settings like:
```
branch-protection:
  orgs:
    org:
      repos:
        repo:
          require_manually_triggered_jobs: true

```
tide is not aware of required context unless it's executed and seen by prow. That means tide tries to merge PR not taking into account branch protection settings.

**What you expected to happen**:
Tide should wait for required context and do not inform user that PR is in the merge pool.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure above in org/repo. Job should be marked as `always_run: false` and mandatory (without additional options like `skip_only_if_changed`).
2. rub branch protection
3. you will see that context is required by github to merge
4. tide after receiving all required labels and all required test except the context one will try to merge PR

**Please provide links to example occurrences, if any**:
can be observed in https://github.com/openshift/ci-tools

**Anything else we need to know?**:
/sig testing
/area prow
/area prow/tide

**Comment by oshoval** [comment]
Hi
Was this fixed or it is the case atm still ?
We are checking on kubevirt as well and will report
