### ISSUE TITLE
Follow-up of #3028, missing 1.7 blocking tests

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/test-infra#3109]
Follow-up of https://github.com/kubernetes/test-infra/pull/3028. We need to add these three tests into the 1.7 blocking tests once they are created:
```
kubelet-serial-gce-e2e-1-7
gke-gci-gpu-1-7
gce-gci-auth-1-7
```

**Comment by caesarxuchao** [comment]
@krzyzacy are you creating these three tests? Or do you know who's creating them? Thanks.

**Comment by krzyzacy** [comment]
ref https://github.com/kubernetes/test-infra/pull/3059

I can make a kubelet-serial job

I have no idea what is auth-1-7?

**Comment by david-mcmahon** [comment]
Whoever adds the new tests can simply add them to release blocking at the same time.

**Comment by krzyzacy** [comment]
@caesarxuchao do you mean `gci-gce-audit-release-1-7`?

**Comment by krzyzacy** [comment]
still needed or shall I close?

**Comment by caesarxuchao** [comment]
Closing.
