### ISSUE TITLE
[Failing Test] post-kubernetes-push-image-etcd

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/test-infra#31154]
### Which jobs are failing?

master-informing:
- post-kubernetes-push-image-etcd

### Which tests are failing?

Overall job

### Since when has it been failing?

First failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1718020233660207104

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#post-kubernetes-push-image-etcd

### Reason for failure (if possible)

```
ERROR: (gcloud.builds.submit) build 0bbd94cb-0c8b-41f0-9631-53590a87a4c7 completed with status "FAILURE"
```

Some additional suspicions:
```
/bin/bash: line 1: ./build.sh: No such file or directory
done
install: can't stat '/workspace/tmp.BbIfCf/etcd': No such file or directory
install: can't stat '/workspace/tmp.BbIfCf/etcdctl': No such file or directory
install: can't stat '/workspace/tmp.ilEfpe/etcd': No such file or directory
install: can't stat '/workspace/tmp.ilEfpe/etcdctl': No such file or directory

cp: cannot stat 'bin/arm64/etcd*': No such file or directory
....
```

### Relevant SIG(s)

/sig k8s-infra

**Comment by Vyom-Yadav** [comment]
As the Alpha 3 release cut is approaching (2nd Nov)
/priority critical-urgent

**Comment by pacoxu** [comment]
https://kubernetes.slack.com/archives/C2C40FMNF/p1698666130888699 discussion in slack.

> looks like the error is [gcr.io/k8s-staging-etcd/etcd:3.5.10-0-linux-amd64](http://gcr.io/k8s-staging-etcd/etcd:3.5.10-0-linux-amd64) is a manifest list

> [gcr.io/k8s-staging-etcd/etcd:3.5.10-0-linux-amd64](http://gcr.io/k8s-staging-etcd/etcd:3.5.10-0-linux-amd64) is a 
> manifest list
> make: *** [Makefile:223: push-manifest] Error 1
> ERROR
> ERROR: build step 0 “[gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20230623-56e06d7c18](http://gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20230623-56e06d7c18)” failed: step exited with non-zero status: 2

**Comment by ahrtr** [comment]
Most likely I am missing something... why there wasn't such failure previously when bumping etcd 3.5.9?

**Comment by pacoxu** [comment]
3.5.9 was built after https://github.com/kubernetes/kubernetes/pull/117999 was merged in May 2023. 

- https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd only have recent job history runs.

The job is run based on `gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20230623-56e06d7c18`. The image is build using 

https://github.com/kubernetes/test-infra/blob/660e090ae203d154852a4b412b78c4803b815e2f/images/gcb-docker-gcloud/Dockerfile#L33C90-L33C100

`docker-cli` version is not specified. 
I guess the docker version bumps in the recent half year. There are new releases and behavior change🤣

**Comment by ahrtr** [comment]
> `docker-cli` version is not specified.
> I guess the docker version bumps in the recent half year. There are new releases and behavior change

thx for the clarification.
