### ISSUE TITLE
Make a kubeadm test-grid tab

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#3120]
Now that we're adding more suites, it would be nice to get `kubeadm-gce` moved from the `misc` tab to a `kubeadm` or `sig-cluster-lifecycle` tab.

There also the other kubeadm jobs like `kubeadm-gce-1.6`, `kubeadm-gce-1.7` and `kubeadm-1.6-1.7` should be shown.

/assign @pipejakob @krzyzacy 
(whoever of you that have time to make this change)

cc @roberthbailey

**Comment by roberthbailey** [comment]
That seems reasonable. I'd also talked with @fejta about having a cluster-lifecycle-sig dashboard (or tab) in testgrid where we collect all of the test suites that the sig is responsible for in a single place.

**Comment by krzyzacy** [comment]
@luxas @roberthbailey it should be easy to do - just add couple row similar to https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml#L1886-L1889, just fill it up yourself and I can review your PR.

**Comment by roberthbailey** [comment]
@luxas - I had a WIP PR to do this as well. can you take a look before we mark this as complete?

**Comment by roberthbailey** [comment]
This is now done.
