### ISSUE TITLE
Org member cannot trigger prow for containerd

### ISSUE THREAD

**Issue by samuelkarp** [kubernetes/test-infra#31212]
**What happened**:
We've recently added @ruiwen-zhao to the containerd GitHub org (added October 31).  However, when he opens new PRs, @k8s-ci-robot still applies "needs-ok-to-test" and does not allow him to mark /ok-to-test.

**What you expected to happen**:
@ruiwen-zhao's PRs are automatically ok-to-test and he can mark PRs as /ok-to-test.

**How to reproduce it (as minimally and precisely as possible)**:
See https://github.com/containerd/containerd/pull/9357.

**Please provide links to example occurrences, if any**:
See https://github.com/containerd/containerd/pull/9357.

**Anything else we need to know?**:

**Comment by michelle192837** [comment]
I'm not seeing ruiwen-zhao in the containerd org (though I do see you), and I don't see it listed on their profile either (https://github.com/ruiwen-zhao). Did something else update the org membership unexpectedly?

**Comment by samuelkarp** [comment]
![image](https://github.com/kubernetes/test-infra/assets/737750/07d72fa5-0b24-4f96-8e94-6846bcce6041)

Org membership is showing up for me here.  @ruiwen-zhao did you mark your membership public?

**Comment by ruiwen-zhao** [comment]
It was private by default. I just marked it public. 

Was that the reason why @k8s-ci-robot didn't know I was a member?

**Comment by akhilerm** [comment]
I think there is some restriction on checking with membership of a user, if the membership is not public. Ref: https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#check-organization-membership-for-a-user. If the user is not public member, then only if the requestor is a member of the same organization it can see that user is a member.  Not sure if @k8s-ci-robot is a member of containred org.

**Comment by upodroid** [comment]
I don't think the bot is an owner of the org. @samuelkarp can you verify if the bot is an org owner? If not, please open an issue at kubernetes/org for @kubernetes/owners to accept the invite.

**Comment by samuelkarp** [comment]
@upodroid Does the bot need to be an owner or just a member?

**Comment by akhilerm** [comment]
@upodroid Does the bot need to be an owner?? Or just a member of the org?

**Comment by akhilerm** [comment]
@upodroid Just a member of the containerd org should be enough right? Why should the bot be the owner??

**Comment by upodroid** [comment]
It depends on what you want the bot to do. With the current set of plugins [enabled](https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml#L1557), owner isn't required.

**Comment by samuelkarp** [comment]
[This](https://github.com/kubernetes/test-infra/blob/efab5eef7a3e476e5f11e56a840a3864c4232731/config/prow/plugins.yaml#L1578-L1581) is really the set of enabled plugins; `containerd/cri` is an archived repository.

Is there a description of the plugins somewhere?  Separately from this issue, maybe we might enable more of them?

**Comment by upodroid** [comment]
The complete list and their required privileges aren't documented, this it the list we enable by default for kubernetes-sigs.

https://github.com/kubernetes/test-infra/blob/efab5eef7a3e476e5f11e56a840a3864c4232731/config/prow/plugins.yaml#L1357

Most of these should be safe to enable. I would do some prep work before enabling approve. Also prow has a dco plugin so you can use that instead of the cla plugin.

**Comment by samuelkarp** [comment]
Some of those names are pretty opaque (`cat`, `dog`, `pony`, `yuks`).  I'm curious if there's a description of what each of them do.

(We probably won't want the `dco` plugin; we handle that with our [project-checks action](https://github.com/containerd/project-checks) today.)

**Comment by upodroid** [comment]
https://prow.k8s.io/plugins

**Comment by samuelkarp** [comment]
> Looking at the prow code, [docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#list-organization-members](https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#list-organization-members) this the API call to get members which works if the bot if a member.

@dmcgowan Can we invite @k8s-ci-robot to the `containerd` org?

**Comment by samuelkarp** [comment]
Looks like @k8s-ci-robot is a member now (it auto-accepted?).

**Comment by akhilerm** [comment]
Its now working, I see that on https://github.com/containerd/containerd/pull/9378, the `needs-ok-to-test` is not applied and the presubmits have been triggered.

**Comment by samuelkarp** [comment]
Awesome!  Closing.
