### ISSUE TITLE
mkpod's nonLocalVolumes are not dealt when it is used in non-local mode

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/test-infra#31227]
**What happened**:
[`pj-on-kind.sh`](https://github.com/kubernetes/test-infra/blob/master/prow/pj-on-kind.sh) expects all Volume Sources to be present on the pointed cluster when run in nonlocal mode.

**What you expected to happen**:
Like the emptyDir or hostPath replacements for all volume sources are done in https://github.com/kubernetes/test-infra/blob/master/prow/cmd/mkpod/main.go#L162-L185, even when the localMode is false, it should be handled.

**How to reproduce it (as minimally and precisely as possible)**:
run `pj-on-kind.sh` in non local mode to push artifacts to GCS and have a secret as Volume mentioned in the config like in pj-on-kind.sh

**Comment by Rajalakshmi-Girish** [comment]
@stevekuznetsov Please look into this to confirm if this ask is a valid one.

**Comment by BenTheElder** [comment]
prow is now at https://github.com/kubernetes-sigs/prow

I'm not sure if this is valid, but the issue tracker for the prow repo will have better visibility if you're still interested, please re-file there.
