### ISSUE TITLE
Prow / commands don't work in Github review comments

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#3124]
See https://github.com/kubernetes/kubernetes/pull/47342#pullrequestreview-45229065 as an example

/assign @spiffxp

**Comment by cjwagner** [comment]
The `/lgtm` and `/approve` commands will be supported in review comments and bodies once #2970 is merged.

**Comment by spiffxp** [comment]
This has been live for a little bit

https://github.com/kubernetes/community/pull/732#pullrequestreview-46987138 - example of using /lgtm in an "approved" review comment

/close
