### ISSUE TITLE
Make the dashboards visible in the testgrid UI

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#3126]
ref: https://github.com/kubernetes/test-infra/pull/3125#issuecomment-309857191

I'd want the UI to look like this, simplified:

```
<blue boxes, dashboards>
<-- whitespace -->
<grey boxes, as-is now>
```

The links to the dashboards can be blue or whatever color but not gray

cc @roberthbailey @krzyzacy

**Comment by roberthbailey** [comment]
@luxas - do you mean on the pages where we see multiple rows of tabs or on the main landing page? I'd really like to see the dashboard groups on the main landing page (but I'm not sure if that is this issue or if I should file a separate one).

**Comment by krzyzacy** [comment]
@roberthbailey since the code of that part is not open sourced yet, you might want to file an internal issue

**Comment by roberthbailey** [comment]
I filed an internal bug.

**Comment by fejta** [comment]
Michelle do you still intend to color the dashboards like in https://k8s-testgrid.appspot.com/q/summary/sig-node?

**Comment by michelle192837** [comment]
Yup, just need to work myself up to puttering around with more CSS.

**Comment by michelle192837** [comment]
Have a change for this, should be pushed out next week.

**Comment by michelle192837** [comment]
This should be live!
