### ISSUE TITLE
/retest should only trigger failed actions

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/test-infra#31291]
**What would you like to be added**:

It's now possible with GitHub to re-run failed workflows - https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-failed-jobs-from-a-workflow-run

Currently `/retest` re-runs all the workflows since the above endpoint didn't exist when support for actions was added (https://github.com/kubernetes/test-infra/issues/21581).

**Why is this needed**:

In some scenarios retesting all workflows is very time consuming and not needed.

**Comment by liangyuanpeng** [comment]
Here is the PR of working for it and just merged.

- https://github.com/kubernetes/test-infra/pull/31132

/area prow

**Comment by petr-muller** [comment]
> Here is the PR of working for it and just merged.

/close

**Comment by dprotaso** [comment]
Awesome thanks - curious if any of you have encountered this related issue: https://github.com/kubernetes/test-infra/issues/31292
