### ISSUE TITLE
[flake] unit test TestAddWithParser

### ISSUE THREAD

**Issue by aojea** [kubernetes/test-infra#31313]
is this related?

> k8s.io/test-infra/prow/config/secret: TestAddWithParser/1 expand_less | 2s
> -- | --
> {Failed  === RUN   TestAddWithParser/1 === PAUSE TestAddWithParser/1 === CONT  TestAddWithParser/1 time="2023-XX-24TXX:X2:00Z" level=warning msg="Error loading secret file." error="stat /tmp/X742X67904: no such file or directory" secret-path=/tmp/X742X67904 time="2023-XX-24TXX:X2:00Z" level=warning msg="Error loading secret file." error="stat /tmp/3086003526: no such file or directory" secret-path=/tmp/3086003526     agent_test.go:169: expected value 2 from generator, got 1 time="X0X3-11-X4T11:1X:01Z" level=error msg="Error loading secret." error="strconv.Atoi: parsing \"not-a-number\": invalid syntax" secret-path=/tmp/TestAddWithParser0360X481105/001/secret --- FAIL: TestAddWithParser/1 (2.00s)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/31312/pull-test-infra-unit-test/1728007651314372608

_Originally posted by @aojea in https://github.com/kubernetes/test-infra/issues/31312#issuecomment-1825521902_

```
=== RUN TestAddWithParser/1
 === PAUSE TestAddWithParser/1
 === CONT TestAddWithParser/1
time="2023-XX-24TXX:X2:00Z" level=warning msg="Error loading secret file." error="stat /tmp/X742X67904: no such file or directory" secret-path=/tmp/X742X67904
time="2023-XX-24TXX:X2:00Z" level=warning msg="Error loading secret file." error="stat /tmp/3086003526: no such file or directory" secret-path=/tmp/3086003526
 agent_test.go:169: expected value 2 from generator, got 1
time="X0X3-11-X4T11:1X:01Z" level=error msg="Error loading secret." error="strconv.Atoi: parsing "not-a-number": invalid syntax" secret-path=/tmp/TestAddWithParser0360X481105/001/secret
 --- FAIL: TestAddWithParser/1 (2.00s)
```

**Comment by alculquicondor** [comment]
Also observed in #32339 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/32339/pull-test-infra-unit-test/1775523580885340160

**Comment by danilo-gemoli** [comment]
@MadhavJivrajani I haven't realized we were working on the same issue: https://github.com/kubernetes/test-infra/pull/32385.
I've refactored the test out, hopefully we won't hit the (same?) race condition again.

**Comment by BenTheElder** [comment]
This isn't a flake in test-infra anymore.

Unfortunately github can't transfer issues across repos, but we can re-file in prow if it's still flaking there
