### ISSUE TITLE
`gcsweb` is broken when running it without credentials

### ISSUE THREAD

**Issue by oliver-goetz** [kubernetes/test-infra#31349]
**What happened**:
Since PR #31241 was merged `gcsweb` does not work when you don't provide credentials.
Instead it shows this error message when you try to access it.
```
Error: error while processing object: googleapi: Error 403: Insufficient Permission, insufficientPermissions
```
We run `gcsweb` with a public GCS storage backend in a Gardener cluster which does not provide any default credentials. 

**What you expected to happen**:
`gcsweb` to work without specifying any credentials.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
Our gcsweb deployment: https://github.com/gardener/ci-infra/blob/master/config/prow/cluster/gcsweb_deployment.yaml

**Anything else we need to know?**:

**Comment by timebertt** [comment]
While looking into this, I realized that the gcloud/gcs client libraries always try to use [application default credentials](https://cloud.google.com/docs/authentication/application-default-credentials) unless authentication is disabled explicitly (using `option.WithoutAuthentication()`).
In your case where the cluster runs on GCP, gcsweb will use the metadata server to get a token for the service account attached to the instance (not done for new clusters created with the [`DisableGardenerServiceAccountCreation` feature gate](https://github.com/gardener/gardener-extension-provider-gcp/blob/ca6e519d8ae36c2c820d3117468ccb227e49aaba/pkg/features/features.go#L23-L26) enabled).

@oliver-goetz How is IAM configured for your GCS bucket?
In my naive thinking, all service accounts (including the one attached to your cluster's nodes) should be able to access your GCS bucket, if it is configured according to [this GCP guide](https://cloud.google.com/storage/docs/access-control/making-data-public#buckets) linked in the [prow docs](https://docs.prow.k8s.io/docs/getting-started-deploy/#configure-a-gcs-bucket) ([`allUsers`](https://cloud.google.com/iam/docs/overview#all-users) should include all service accounts?).

**Comment by oliver-goetz** [comment]
> While looking into this, I realized that the gcloud/gcs client libraries always try to use [application default credentials](https://cloud.google.com/docs/authentication/application-default-credentials) unless authentication is disabled explicitly (using `option.WithoutAuthentication()`). In your case where the cluster runs on GCP, gcsweb will use the metadata server to get a token for the service account attached to the instance (not done for new clusters created with the [`DisableGardenerServiceAccountCreation` feature gate](https://github.com/gardener/gardener-extension-provider-gcp/blob/ca6e519d8ae36c2c820d3117468ccb227e49aaba/pkg/features/features.go#L23-L26) enabled).
> 

The VMs do have a GCP service account. However, the `Cloud API access scopes` are restricted. `Storage` scope is disabled. The only active scope is `Compute Engine`.

> @oliver-goetz How is IAM configured for your GCS bucket? In my naive thinking, all service accounts (including the one attached to your cluster's nodes) should be able to access your GCS bucket, if it is configured according to [this GCP guide](https://cloud.google.com/storage/docs/access-control/making-data-public#buckets) linked in the [prow docs](https://docs.prow.k8s.io/docs/getting-started-deploy/#configure-a-gcs-bucket) ([`allUsers`](https://cloud.google.com/iam/docs/overview#all-users) should include all service accounts?).

There is an `allUsers` principal with `Storage Object Viewer` role in our GCS bucket.
