### ISSUE TITLE
Initializers should be run in an alpha aware serializer feature with the alpha gates

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/test-infra#3136]
Initializers (alpha in 1.7) need to run in serial because they disrupt other jobs, but we don't have a serial job for alpha specifically (that I could find).  Are we ok to add one?

**Comment by krzyzacy** [comment]
add it to https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gce-alpha-features-release-1-7.env?

**Comment by smarterclayton** [comment]
Ok, that's definitely serial?  I wasn't sure whether it was from the description.

**Comment by krzyzacy** [comment]
I think so, as long as it does not have `GINKGO_PARALLEL=y`
