### ISSUE TITLE
prow 'make *-deploy' should fail if not on branch synced with upstream master

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#3141]

**Comment by ixdy** [comment]
we did something similar in the release repo: https://github.com/kubernetes/release/blob/f77fcb6d2b23ebd0e2c471abffef59abf4746bd7/lib/gitlib.sh#L217-L238

**Comment by fejta** [comment]
I would expect to checkout prow at an old commit to rollback a bad push.

**Comment by spxtr** [comment]
I think the solution to this that we settled on was to limit the number of people with access to the prow cluster to a very small number. Those people have the power to do whatever they want.
