### ISSUE TITLE
Undesirable postsubmit pipeline cancellation

### ISSUE THREAD

**Issue by mlowery** [kubernetes/test-infra#31452]
Note: We run a fork of Prow that includes https://github.com/kubernetes/test-infra/pull/28809.

# Problem

Let's assume I have a postsubmit job that uses tekton agent to build an image. PR A merges. Postsubmit for A begins. Before postsubmit for A finishes, let's assume PR B merges. Postsubmit for A is canceled and the image for A is not built.

This cancellation seems to come from `abortDuplicatedProwJobs`.

# Potential Solution

`createProwJobIdentifier` could be changed to treat postsubmits differently like so:

```go
func createProwJobIdentifier(pj *prowjobv1.ProwJob) string {
	var additionalIdentifier string
	if pj.Spec.Refs != nil {
		var pulls []int
		for _, pull := range pj.Spec.Refs.Pulls {
			pulls = append(pulls, pull.Number)
		}
		sort.Ints(pulls)
		base := pj.Spec.Refs.BaseSHA
		if len(pj.Spec.Refs.Pulls) > 0 {
			base = pj.Spec.Refs.BaseRef
		}
		additionalIdentifier = fmt.Sprintf("%s/%s@%s %v", pj.Spec.Refs.Org, pj.Spec.Refs.Repo, base, pulls)
	}
	return fmt.Sprintf("%s %s", pj.Spec.Job, additionalIdentifier)
}
```

In this way, `abortDuplicatedProwJobs` will not match ProwJobs of the same name but with different BaseSHA (which will only be used in postsubmits).

# But...

A design where the pipeline controller preempts ProwJobs seems odd to me. Why is that the pipeline controller's duty? Seems like that should be in `reconciler`.

Additionally, https://github.com/kubernetes/test-infra/pull/28809 and the above `createProwJobIdentifier` change seem overly opinionated to me. What if I don't want preemption?

It seems that ProwJob needs an additional field, perhaps a string called `Spec.ConcurrencyDistinguisher`. The implicit distinguisher now is `pj1.Spec.Job == pj2.Spec.Job` perhaps represented by string `BySpecJob`. But what if there was another distinguisher `DeepEqual(pj1.Spec, pj2.Spec)`, perhaps represented by string `BySpec`? And where does the user specify that they want to allow preemption? Should that be a field too?

**Comment by jmguzik** [comment]
@mlowery this controller has many problems (well, it's buggy) and it's not actively developed as part of core prow. The best way to address your needs would be to open a PR with proposed changes.
> What if I don't want preemption?

You can add option for that. My motivation was to save $ and recreate prow native behavior. If you invoke /test all or change your commit, prow also cancels existing tests, all of them except tekton pipelines which seemed odd.
