### ISSUE TITLE
Prow issue: bot not merging PRs in cloud-provider-openstack

### ISSUE THREAD

**Issue by zetaab** [kubernetes/test-infra#31462]
We have few PRs that do have lgtm and approve labels. https://github.com/kubernetes/cloud-provider-openstack/pulls?q=is%3Apr+is%3Aopen+label%3Aapproved+label%3Algtm but the bot is not merging these.

https://github.com/kubernetes/cloud-provider-openstack/pull/2509 Pending — Not mergeable. Retesting 3 jobs.
https://github.com/kubernetes/cloud-provider-openstack/pull/2489 in merge pool but not progressing?
https://github.com/kubernetes/cloud-provider-openstack/pull/2478 labels added 2 days ago, still not merging?

**Comment by BenTheElder** [comment]
https://prow.k8s.io/tide

=>

https://prow.k8s.io/?repo=kubernetes%2Fcloud-provider-openstack

they're failing in CI

**Comment by BenTheElder** [comment]
Looks like your CI scripts require an individual PR_NUMBER which is not going to work for batch testing

**Comment by zetaab** [comment]
@BenTheElder do you have idea why we have not seen that bug before? That code is last time modified 2 years ago. Perhaps we did not have multiple PRs merging at the same before?

**Comment by BenTheElder** [comment]
Possibly, I also think prow might have a regression in falling back to serial testing, which we've seen before (it should be testing one PR alongside the batch and merging that one if the batch fails)

**Comment by zetaab** [comment]
thanks @BenTheElder

**Comment by dulek** [comment]
@BenTheElder: Seems like https://github.com/kubernetes/cloud-provider-openstack/blob/96f2edbfbac24e25660d809669f55c139f12edce/tests/ci-occm-e2e.sh#L34 was there all the time. Can you help me understand how the CI scripts should check out the PRs if no PULL_NUMBER is given?
