### ISSUE TITLE
ci-cos-cgroupv2-inplace-pod-resize-containerd-main-e2e-gce-serial is not triggered since Sep 2023

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/test-infra#31465]
**What happened**:

Periodic job [ci-cos-cgroupv2-inplace-pod-resize-containerd-main-e2e-gce-serial](https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-inplace-pod-resize-containerd-e2e-serial) is not triggered. Last time it was triggered was on 21st of September 2023.

**What you expected to happen**:

The job should be triggered regularly.

**How to reproduce it (as minimally and precisely as possible)**:

It's 100% reproducible, just look at the test grid.

**Please provide links to example occurrences, if any**:

[Test grid view for the job](https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-inplace-pod-resize-containerd-e2e-serial)

**Anything else we need to know?**:

Similar job [ ci-cos-cgroupv1-inplace-pod-resize-containerd-main-e2e-gce-serial](https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-inplace-pod-resize-containerd-e2e-serial) is triggered regularly.

**Comment by BenTheElder** [comment]
It's triggering, not triggering would be a major bug (please raise those to #testing-ops), it's just crashing right away due to invalid clone config.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/33120/files

**Comment by BenTheElder** [comment]
manually started a run with the new config https://prow.k8s.io/?job=ci-cos-cgroupv2-inplace-pod-resize-containerd-main-e2e-gce-serial

**Comment by BenTheElder** [comment]
It is running here https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-inplace-pod-resize-containerd-main-e2e-gce-serial/1816935026281943040
