### ISSUE TITLE
Upgrade tests should check the server version after upgrade

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/test-infra#3151]
Recently we discovered the upgrade tests were not actually upgrading the server before running the tests, rendering the test results meaningless.

After upgrading the server, and before running the e2e tests, the tests should run `kubectl version` and verify the server is at the correct version.

**Comment by ixdy** [comment]
@kubernetes/sig-testing-feature-requests

**Comment by ixdy** [comment]
This one is still kinda important and probably wants an owner.

/sig testing
/sig release

**Comment by krzyzacy** [comment]
I *think* we already have this?

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L202

**Comment by ixdy** [comment]
well, kind of. That doesn't appear to actually validate that the correct version is running.

**Comment by krzyzacy** [comment]
huh? ref https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-beta-upgrade-cluster/623

so we check version before upgrade:

```
I0831 08:24:34.824] Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-beta.0.792+0ee5de31ae2ebd", GitCommit:"0ee5de31ae2ebd8e711823edad54a5ef529678ee", GitTreeState:"clean", BuildDate:"2018-08-30T12:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
I0831 08:24:34.824] Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.3-beta.0.56+86c0fa1f8c360f", GitCommit:"86c0fa1f8c360fe93b6b10c1db31e9e442097985", GitTreeState:"clean", BuildDate:"2018-08-29T22:02:17Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
W0831 08:24:34.924] 2018/08/31 08:24:34 process.go:155: Step './hack/e2e-internal/e2e-status.sh' finished in 589.327324ms
```

and check again after upgrade:

```
I0831 09:07:32.615] Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.3-beta.0.56+86c0fa1f8c360f", GitCommit:"86c0fa1f8c360fe93b6b10c1db31e9e442097985", GitTreeState:"clean", BuildDate:"2018-08-29T22:18:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
I0831 09:07:32.615] Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-beta.0.792+0ee5de31ae2ebd", GitCommit:"0ee5de31ae2ebd8e711823edad54a5ef529678ee", GitTreeState:"clean", BuildDate:"2018-08-30T11:47:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
W0831 09:07:32.716] 2018/08/31 09:07:32 process.go:155: Step './hack/e2e-internal/e2e-status.sh' finished in 1.678796392s
```

with the skewed client version

so we want to add a comparison here between the server version we got, vs the k8s version we extract?

**Comment by ixdy** [comment]
We print out versions, yes, but I don't think we programatically verify that they changed.

This issue was filed after some time was wasted trying to figure out why tests were failing in an upgrade job, only to eventually discover that the job was misconfigured and an upgrade wasn't actually happening.

**Comment by spiffxp** [comment]
/milestone v1.13
Plan on working to at least parse out and display the skewed version in gubernator/testgrid.  While looking at that I will see if this is still needed

**Comment by spiffxp** [comment]
/unassign
in case someone else wants to give this a shot

/milestone someday
I'm not sure I can commit to this in v1.15 but I don't want to clear milestone just yet
