### ISSUE TITLE
Support assigning and closing in one comment

### ISSUE THREAD

**Issue by castrojo** [kubernetes/test-infra#3154]
It'd be nice to have

    /assign
    /close

That way I can work in one comment instead of adding noise with two. Thanks!

**Comment by spiffxp** [comment]
The way things are structured right now, this is unlikely.  The /assign and /close commands are implemented by different plugins.  The order of /commands within a message doesn't guarantee the order in which plow plugins are run against a given event.

As a workaround we could perhaps extend /close to a trusted group, denoted by eg: kubernetes org membership, team membership, inclusion in an OWNERS file, etc.

**Comment by spxtr** [comment]
We have `/assign` and `/lgtm` working in one command. The way it works is that `/lgtm` assigns you if you're not assigned. Similarly, we can make `/close` assign you if you're not assigned before closing.

**Comment by cblecker** [comment]
+1 to assign happening in the background on /close.

**Comment by spiffxp** [comment]
@spxtr that'll work, as long as successful assignment is a gate; don't want a drive-by mass-closing, and org membership implies at least some amount of trust
