### ISSUE TITLE
What is the replacement for prow_implicit_git_ref in new version of Prow and Tekton

### ISSUE THREAD

**Issue by opatil-vibrent** [kubernetes/test-infra#31564]
We were using old version of Tekton and Prow and in there we used to get the git PR branch name with the help of "prow_implicit_git_ref" variable. As this is deprecated in the newer versions we are not able to get the git PR branch name. "prow_implicit_git_ref" was internally passing the PR branch name to tekton pipelinerun.

What is the replacement variable for prow_implicit_git_ref in the new version? We are not able to get anything on the internet for this as well. Please help us here.

The Prow and Tekton versions we had earlier was
Prow v20201009
Tekton 0.23

Current versions are:
Prow v20231103
Tekton 0.39

**Comment by cizara** [comment]
@opatil-vibrent in the Tekton Pipeline or PipelineRun you have access to all these Prow variables: https://docs.prow.k8s.io/docs/jobs/#job-environment-variables

**Comment by BenTheElder** [comment]
Sorry, kubernetes does not use the tekton component.

You can file new issues with github.com/kubernetes-sigs/prow for better visibility if you're still interested in this, prow has it's own repo finally.
