### ISSUE TITLE
cla is a prow plugin (ie. optional) but the submit queue requires a cla label

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3156]
Approvals are also gated currently in the SQ but I expect it to turn into a prow plugin in the future. Both plugins are specific to kubernetes and may not be used elsewhere (eg. we don't use CLAs or approvals in Origin, at least today). In general, prow plugins can be disabled w/o the SQ knowing while it requires them. One solution is to pass the plugin config in the submit queue. If we don't expect more plugins to be hard dependencies for merges then they could just be flags in the SQ. Alternatives?

@spxtr

**Comment by spiffxp** [comment]
I think submit queue just looks for another status context, not the actual label itself?  We removed the cla munger a few weeks ago

**Comment by spiffxp** [comment]
eg: https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L31

**Comment by kargakis** [comment]
No, it looks for the [actual labels](https://github.com/kubernetes/test-infra/blob/47fbf22bf7a9a1081671c97865187f2f224f65d2/mungegithub/mungers/submit-queue.go#L955). I have verified this one during testing.
