### ISSUE TITLE
Request: cgroup v2 node pool in community clusters

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/test-infra#31572]
Currently `k8s-infra-prow-build` and `eks-prow-build-cluster` are still using cgroup v1, although many users should have already switched to cgroup v2.
It is still possible to create a custom cluster with Boskos, but this is often complicated and hard to test on laptop.

Any chance to have cgroup v2 node pool in community clusters, or just have a new cluster dedicated for cgroup v2?

**Comment by ameukam** [comment]
cc @BenTheElder

**Comment by kannon92** [comment]
In a sig-node meeting a few weeks back, we did talk about making cgroups v2 the default. cc @dchen1107 @SergeyKanzhelev 

It is possible to get a cgroupv2 cluster but you may have to target it specifically. We have examples of cgroupv2 jobs.

**Comment by dims** [comment]
fyi all the ci jobs wiht `al2023` in their names are cgroupsv2 

- https://testgrid.k8s.io/amazon-ec2-al2023
- https://testgrid.k8s.io/amazon-ec2-node

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

We're still going to want to sort this out at some point, eventually this will be the default even ...

**Comment by dims** [comment]
we have a lot of cgroupv2 jobs now ... https://prow.k8s.io/?job=*cgroupv2*

**Comment by BenTheElder** [comment]
> we have a lot of cgroupv2 jobs now ... https://prow.k8s.io/?job=*cgroupv2*

Yes, and that's probably more than enough for now, but at some point the prow clusters will also wind up migrating, and we could make sure kind etc are tested that way.

For now, I guess the cloudy E2E are enough and we can track this https://github.com/kubernetes/k8s.io/issues/5276 instead
