### ISSUE TITLE
prow/trigger: trusted org hard-coded to k8s

### ISSUE THREAD

**Issue by nlandolfi** [kubernetes/test-infra#3157]
When [checking if the user is a member of a trusted org](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/trigger/pr.go#L132), trigger uses a [`trustedOrg` constant](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/trigger/trigger.go#L31) which is hard-coded to `kubernetes`. 

Perhaps this should be a flag?

**Comment by spxtr** [comment]
Yes, this will happen in the Near Future. I prefer a config option to a flag. See #2566, #2721, and #2546.

**Comment by kargakis** [comment]
Done

/close
