### ISSUE TITLE
Plank reports need to be templatized

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3158]
Especially the link in the github context needs to point in the right direction.

See https://github.com/origin-prow/origin/pull/2#issuecomment-310658351

**Comment by kargakis** [comment]
@spxtr do you have a PR for the last part that's needed to change here? If not, I can pick it up this week.

**Comment by spxtr** [comment]
I have it pretty much ready to go. I'll open a PR today.

**Comment by spxtr** [comment]
Done.
