### ISSUE TITLE
Most testgrid jobs are failing due to connection refused to ghproxy.default.svc.cluster.local (cla, stale/rotten issues, etc.)

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes/test-infra#31618]
**What happened**:

Most of the triage-robot's jobs have been failing consistently for at least the last few weeks. I think failures go back to around 21 July 2023 based on searching all of GitHub for stale issue comments: https://github.com/issues?q=commenter%3Ak8s-triage-robot+%22After+30d+of+inactivity+since%22+

Every failure looks more or less like:
```
2024/01/12 22:20:30 main.go:206: Failed run: search failed: Get "http://ghproxy.default.svc.cluster.local/search/issues?...": dial tcp 10.7.254.218:80: connect: connection refused
```

**What you expected to happen**:

The jobs pass.

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

https://testgrid.k8s.io/sig-contribex-k8s-triage-robot

e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8s-triage-robot-stale-issues/1745931646969843712

**Anything else we need to know?**:

**Comment by aojea** [comment]
>  21 July 2023

this is a long time, @BenTheElder @ameukam rings a bell?

**Comment by ameukam** [comment]
> > 21 July 2023
> 
> this is a long time, @BenTheElder @ameukam rings a bell?

Looks ghproxy is done in the cluster involved. I'll take a look next week is no one beats me to it.

**Comment by nojnhuh** [comment]
@ameukam Have you had a chance to take a look at this?

**Comment by ameukam** [comment]
@nojnhuh https://github.com/kubernetes/k8s.io/pull/6296 should hopefully fix this. Thank you for reporting this.

**Comment by nojnhuh** [comment]
I see a number of green runs in row now. Thanks!

/close
