### ISSUE TITLE
Can the bot always tell me if it's my job to merge or not?

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#3162]
We have lots of repos now.  So many repos.  Sometimes I do one review on that repo and that's it.  It's hard to know what the rules are.  Do we need LGTM labels?  Is there a bot going to do the merge?  Am *I* (the assignee) expected to do the merge?

Can we have the bot maybe let me know when it's my job to merge?
Example PR that had me scratching my head for too long is https://github.com/kubernetes/community/pull/735

**Comment by cblecker** [comment]
@kubernetes/sig-contributor-experience-misc 
At the very least, it would be good to document which repos have a SQ as all others would need manual merging.

**Comment by rmmh** [comment]
If you don't see a status check from the submit queue, it won't merge it for you.

**Comment by spiffxp** [comment]
I would rather we follow the convention where each repo has a CONTRIBUTING.md file that describes how to contribute code to that repo

In the example PR's case, https://github.com/kubernetes/community/blob/master/CONTRIBUTING.md describes the (manual) process of contributing to the kubernetes/community repo.

In kubernetes/kubernetes' case... we have a not-so-great experience ("it's a big topic"? really?)

As far as documenting which repos have SQ pointed at them, we have https://github.com/kubernetes/test-infra/tree/master/mungegithub/submit-queue/deployment and as @rmmh said, SQ will let you know it's taking on merge duties by posting a "Submit Queue" status context on PR's.

Anyway, I'm inclined to close as working as advertised, and suggest @kubernetes/sig-contributor-experience-misc take a gander at various repos' CONTRIBUTING.md files for good and bad practices.  Please reopen if you disagree.

**Comment by mml** [comment]
> If you don't see a status check from the submit queue, it won't merge it for you.

It's the same question again... how would I know that?  We have a good opportunity to say "hey, by the way contributor person--and by the way assignee--, some human is going to have to merge this".  Or in the other case "just so you know, the robot will merge this when these status messages say it's ok".

@spiffxp in the long run, when those docs exist (which I agree they should), maybe we can just have the robot add a link to that very doc saying "hey, here's the process this PR's gonna follow... it's documented _here_"
