### ISSUE TITLE
Performance job for NFTables

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/test-infra#31620]
There were discussions in [NFTables KEP](https://github.com/kubernetes/enhancements/pull/3824#discussion_r1107584724) regarding performance comparison with IPTables proxy. 

We are looking out for a perf job for NFTables proxy but aren't sure about the size/scale of the cluster, load on the cluster, frequency of the job, and other things. Along with comparing the perf with IPTables, this will also help us compare perf with possible future optimizations within NFTables proxy.

[ci-kubernetes-e2e-gce-scale-performance](https://github.com/kubernetes/test-infra/blob/dd8dfec9b2dd99999a1187fe861c90a2694556d3/config/jobs/kubernetes/sig-scalability/sig-scalability-release-blocking-jobs.yaml#L59-L153) [tracks](https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Network&metricname=Load_NetworkProgrammingLatency&Metric=NetworkProgrammingLatency) `NetworkLatency`  and `NetworkProgrammingLatency` for IPTables proxy at scale, maybe we need similar metrics at a low scale? 

Opening up this issue for discussion.

/sig network
/sig scalability 

/cc. @danwinship @aojea @thockin

**Comment by aroradaman** [comment]
/cc. @ameukam

**Comment by aojea** [comment]
@npinaeva and I are working on this, no need to go to scale in a first iteration, we want to validate first the improvements of nftables over the well known iptables problems:, that are:
- programming latency: iptables-save and restore with large numbers of rules
- latency introduced caused by the linear search on the iptables rules

**Comment by aojea** [comment]
https://github.com/kubernetes/test-infra/pull/32431
