### ISSUE TITLE
"Details" link for "tide" check on GitHub PRs doesn't work for PRs authored by bot users

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes/test-infra#31694]
**What happened**:

e.g. For this dependabot PR: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4496

This link matches no PRs:

![image](https://github.com/kubernetes/test-infra/assets/16093815/5b0ee922-8d59-4548-b1ad-50782c12c370)
https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes-sigs%2Fcluster-api-provider-azure+author%3Adependabot+head%3Adependabot%2Fgithub_actions%2Factions%2Fcache-4.0.0

**What you expected to happen**:

The query should be updated to query for the user `app/dependabot` instead of `dependabot`:
https://prow.k8s.io/pr?query=is%3Apr%20repo%3Akubernetes-sigs%2Fcluster-api-provider-azure%20author%3Aapp%2Fdependabot%20head%3Adependabot%2Fgithub_actions%2Factions%2Fcache-4.0.0

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
Seems like a valid bug, would you mind re-filing this against https://github.com/kubernetes-sigs/prow ?

(unfortunately github's "transfer" functionality doesn't work across organizations)

**Comment by nojnhuh** [comment]
Will do, thanks!

**Comment by nojnhuh** [comment]
Moved this here: https://github.com/kubernetes-sigs/prow/issues/177

/close

**Comment by BenTheElder** [comment]
thanks!
