### ISSUE TITLE
Prow pod for scale tests are stuck eternally in running state and not reported back to Prow the final state.

### ISSUE THREAD

**Issue by hakuna-matatah** [kubernetes/test-infra#31769]
**What happened**:
The prow scale test pod here has been running for more than `16hrs` however ideally this particular scale tests runs roughly for around 4hrs. 
In this particular case, the prow scale test pod OOM'd out, I'm not sure if that is the reason why it kept reporting as `running` forever (19hrs) until I kicked off another test.

**What you expected to happen**:
I would expect the prow to report back failure or success instead of getting stuck eternally or until next test is kicked off to prow cluster. 

**How to reproduce it (as minimally and precisely as possible)**:
This happens inconsistently on scale tests, may be try to OOM out the prow test pod to see if it could get into this state.
For more context - https://github.com/kubernetes/k8s.io/issues/6303#issuecomment-1917401748

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16296/presubmit-kops-aws-scale-amazonvpc-using-cl2/1752113814377074688

**Anything else we need to know?**:

**Comment by xmudrii** [comment]
I think this is an issue with Prow and should be transferred to k-sigs/prow
