### ISSUE TITLE
Deal With Inactive Approvers and Approvers Updates

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#3178]
We need a solution similar to https://github.com/kubernetes/test-infra/pull/2795.

For PRs like this one: 

https://github.com/kubernetes/kubernetes/pull/45467

The author got LGTM relatively quickly but no approval for more than a month.  

In addition to pinging the author and helping them find additional approvers (which can be done automatically via the bot), we probably need some additional work for the approvers mechanism:

- [ ]  Define a policy for adding new approvers (and removing irrelevant ones)
- [ ] Carry out said policy to update the owners files
- [ ] Perhaps take into consideration number of existing PRs assigned to a given approver (not sure the mechanism for this) or pull out stats for individual approver latency (good for visibility and may be useful in a leaderboard-ish format)

Thoughts?

@kubernetes/sig-contributor-experience-feature-requests @janetkuo @crimsonfaith91 @apelisse

**Comment by crimsonfaith91** [comment]
@grodrigues3 Having a better policy for adding new approvers will be great! I think we can:
```
- consider number of existing PRs assigned to a given engineer
- if needed, assign to engineers who are owners of other but **closely relevant** files
```

**Comment by grodrigues3** [comment]
> (2) if needed, assign to engineers who are owners of other but closely relevant files

We should only assign people capable of approving (i.e. people in the correct owners files or further up the tree).  

Additionally, to clarify, I also talking about defining a policy for adding new approvers to the OWNERS files (not assigning additional approvers to issues).

**Comment by crimsonfaith91** [comment]
> Additionally, to clarify, I also talking about defining a policy for adding new approvers to the OWNERS files (not assigning additional approvers to issues).

As Kubernetes team is growing, perhaps we can have more junior engineers to deliver and review PRs. We can relax requirements to become an owner of a file.

Else, we can come out with a criteria that uses number of lines of **green** codes merged in determining new owners (i.e., weight large PRs more over small PRs).

**Comment by spxtr** [comment]
The issue in that PR was actually an unfortunately common one. There are a small number of developers on this project who have a million things assigned to them for review and approve. At the time I'm writing this, @lavalamp has [63 PRs assigned and 42 needing approval](https://k8s-gubernator.appspot.com/pr/lavalamp). That's obviously far too much for one person.

> Else, we can come out with a criteria that uses number of lines of **green** codes merged in determining new owners (i.e., weight large PRs more over small PRs).

Giving any weight to number of added lines of code is almost always a bad idea.

**Comment by crimsonfaith91** [comment]
@spxtr i agree that total number of green (not red) lines of codes merged is not a good indicator. It should still work better than total number of PRs merged though (inspired by `blunderbuss` codes).

i am on the same page with you it is _still not good enough_.

**Comment by janetkuo** [comment]
We can show PR authors a list of approvers that they can ping / assign for approval, or provide them a command to give up current assigned approver and find the next available one.

**Comment by spiffxp** [comment]
>Define a policy for adding new approvers (and removing irrelevant ones)

I will try tackling this under https://github.com/kubernetes/test-infra/issues/1966
