### ISSUE TITLE
Migrate remaining `sig-cloud-provider` jobs to community cluster

### ISSUE THREAD

**Issue by rjsadow** [kubernetes/test-infra#31795]
The following jobs still run on the default google owned cluster and need to be migrated to a community cluster

/sig testing
/sig k8s-infra
/sig cloud-provider

**alibaba-cloud-csi-driver**
- [x] pull-alibaba-cloud-csi-driver-verify-fmt | [Search Results](https://cs.k8s.io/?q=pull-alibaba-cloud-csi-driver-verify-fmt) |
- [x] pull-alibaba-cloud-csi-driver-verify-lint | [Search Results](https://cs.k8s.io/?q=pull-alibaba-cloud-csi-driver-verify-lint) |
- [x] pull-alibaba-cloud-csi-driver-verify-vet | [Search Results](https://cs.k8s.io/?q=pull-alibaba-cloud-csi-driver-verify-vet) |
- [x] pull-alibaba-cloud-csi-driver-verify-unit | [Search Results](https://cs.k8s.io/?q=pull-alibaba-cloud-csi-driver-verify-unit) |

**azurefile-csi-driver**
- [x] pull-azurefile-csi-driver-verify | [Search Results](https://cs.k8s.io/?q=pull-azurefile-csi-driver-verify) |
- [x] pull-azurefile-csi-driver-unit | [Search Results](https://cs.k8s.io/?q=pull-azurefile-csi-driver-unit) |
- [x] pull-azurefile-csi-driver-windows-build | [Search Results](https://cs.k8s.io/?q=pull-azurefile-csi-driver-windows-build) |

**azuredisk-csi-driver**
- [x] pull-azuredisk-csi-driver-verify | [Search Results](https://cs.k8s.io/?q=pull-azuredisk-csi-driver-verify) |
- [x] pull-azuredisk-csi-driver-unit | [Search Results](https://cs.k8s.io/?q=pull-azuredisk-csi-driver-unit) |
- [x] pull-azuredisk-csi-driver-windows-build | [Search Results](https://cs.k8s.io/?q=pull-azuredisk-csi-driver-windows-build) |
- [x] pull-azuredisk-csi-driver-verify-mainv2 | [Search Results](https://cs.k8s.io/?q=pull-azuredisk-csi-driver-verify-mainv2) |
- [x] pull-azuredisk-csi-driver-unit-mainv2 | [Search Results](https://cs.k8s.io/?q=pull-azuredisk-csi-driver-unit-mainv2) |
- [x] pull-azuredisk-csi-driver-windows-build-mainv2 | [Search Results](https://cs.k8s.io/?q=pull-azuredisk-csi-driver-windows-build-mainv2) |

**aws-iam-authenticator**
- [x] pull-aws-iam-authenticator-unit | [Search Results](https://cs.k8s.io/?q=pull-aws-iam-authenticator-unit) |

**gcp-compute-persistent-disk-csi-driver**
- [x] pull-gcp-compute-persistent-disk-csi-driver-e2e | [Search Results](https://cs.k8s.io/?q=pull-gcp-compute-persistent-disk-csi-driver-e2e) |

**Comment by Okabe-Junya** [comment]
Hi folks!!

I would like to contribute to k/test-infra and am interested in working on this issue :)

After reading some documentation for contributors, I would like to work on this issue.

**Comment by rjsadow** [comment]
Thanks for the help everyone!
