### ISSUE TITLE
k8s-ci-robot shouldn't label "sig/api-machinery" if k8s-merge-robot comments "@kubernetes/sig-api-machinery-misc"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3180]
k8s-merge-robot comments on every issues which don't have a sig label. The comment includes `e.g., @kubernetes/sig-api-machinery-misc for API Machinery`(this example was added in #3102 as suggested in #3060). This comment leads to k8s-ci-robot labels "sig/api-machinery" for every issues. This is not expected. We should find a better way to address it.

/cc @@grodrigues3 @spxtr @crimsonfaith91

**Comment by crimsonfaith91** [comment]
This has already been addressed by this PR: https://github.com/kubernetes/test-infra/pull/3174

**Comment by xiangpengzhao** [comment]
@crimsonfaith91 thanks for pointing it out. It would be great to merge it and deploy ASAP.

**Comment by crimsonfaith91** [comment]
got `lgtm` now.

**Comment by crimsonfaith91** [comment]
merged. i will ask around whether now is the right time to deploy the change.

**Comment by xiangpengzhao** [comment]
:+1:

**Comment by crimsonfaith91** [comment]
The change is merged, but we still need permission for deployment. i will follow closely on this.

**Comment by xiangpengzhao** [comment]
Seems like the issue still exists after the patch is deployed. See: https://github.com/kubernetes/kubernetes/issues/48020
@crimsonfaith91

**Comment by crimsonfaith91** [comment]
The change hasn't deployed yet. The test-infra team moves prow to another submit queue recently. I am not able to access it.

**Comment by crimsonfaith91** [comment]
Please follow this: https://github.com/kubernetes/kubernetes/issues/47941#issuecomment-310703871

I am not able to do anything until I obtain the access to the submit queue. I will inform you when it is deployed. Thanks!

**Comment by spxtr** [comment]
@krzyzacy please redeploy the submit queue when you get a change.

**Comment by crimsonfaith91** [comment]
@spxtr Thanks a lot!

**Comment by krzyzacy** [comment]
@spxtr I have no idea about submit-queue yet, I'll work with @cjwagner Monday. It probably should be documented somewhere so that we can all be able to do this.

**Comment by xiangpengzhao** [comment]
@crimsonfaith91 But I see that there is already quote for `@kubernetes/sig-api-machinery-misc` in the newest comment of k8s-merge-robot.
see: https://github.com/kubernetes/kubernetes/issues/48020#issuecomment-310838866

**Comment by xiangpengzhao** [comment]
The latest issue: https://github.com/kubernetes/kubernetes/issues/48025#issuecomment-310878746

**Comment by crimsonfaith91** [comment]
@xiangpengzhao Quotation should not trigger any sig mentioning. It means that it is due to another issue. I am investigating it now.
@spxtr @krzyzacy It looks like the changes have been deployed. Thanks for the help! :)

**Comment by crimsonfaith91** [comment]
@spxtr @krzyzacy 
It looks like the behavior is not due to sig-mention munger, but the regex for label plugins: https://github.com/kubernetes/test-infra/blob/master/prow/plugins/label/label.go#L47

Based on how the regex is written, a notification will be triggered even it is quoted or tailed with other words behind. I will get the regex fixed tomorrow. Thanks!

**Comment by crimsonfaith91** [comment]
I created another issue to discuss about the label plugin regex. For now, IMO it may be best to have:

There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br>(1) mentioning a sig: `@kubernetes/sig-<team-name>-misc`<br>e.g., `sig-api-machinery-misc` for API Machinery<br>(2) specifying the label manually: `/sig <label>`<br>e.g., `/sig scalability` for sig/scalability<br><br>_Note: method (1) will trigger a notification to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels)_

**Comment by xiangpengzhao** [comment]
agreed. This is also clear enough.

**Comment by crimsonfaith91** [comment]
yup! thanks!

**Comment by crimsonfaith91** [comment]
I went over PRs to remove unnecessary `api-machinery` label manually. It is great that the affected PRs are in small amount of number (going over the PRs took only 10 minutes). I will keep an eye on new PRs rolling out before #3201 is merged.

**Comment by crimsonfaith91** [comment]
Resolved! Final bot comment:

There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br>(1) mentioning a sig: `@kubernetes/sig-<team-name>-misc`<br>e.g., `@kubernetes/sig-api-machinery-*` for API Machinery<br>(2) specifying the label manually: `/sig <label>`<br>e.g., `/sig scalability` for sig/scalability<br><br>_Note: method (1) will trigger a notification to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels)_

**Comment by xiangpengzhao** [comment]
Great! It would make sig-api-machinery folks life happy:)
But I still doubt whether contributors know what the `*` represents in `@kubernetes/sig-api-machinery-*`...
Can we add something more, as below.
e.g., `@kubernetes/sig-api-machinery-*` for API Machinery, `*` can be `misc`, `bugs`, `test-failures`

We may also want to make the docs of sigs more clear.

**Comment by crimsonfaith91** [comment]
Good idea! There is another issue opened yesterday for this: https://github.com/kubernetes/test-infra/issues/3190

**Comment by xiangpengzhao** [comment]
:+1:
