### ISSUE TITLE
Customizable Folder/File Path for ProwJob inrepo Definitions

### ISSUE THREAD

**Issue by zppinho** [kubernetes/test-infra#31809]
**What would you like to be added**:
Currently Prow allows for the definition of Jobs in the same repository as the code ```Inrepoconfig``` and this can be done with a .prow directory or .prow.yaml file.
See [inrepoconfig](https://github.com/kubernetes/test-infra/blob/master/prow/config/inrepoconfig.go#L41)
We would like to have the possibility to choose the folder or file path where these Jobs can be defined 
e.g: ```.cicd/.prow/triggers.yaml```
This defnition could be set in the config.yaml of prow:
```
in_repo_config:
  enabled:
    org/repo: true
    triggers_path: ".cicd/.prow/"
```

**Why is this needed**:
This enables the centralization of all CI/CD definitions in a dedicated folder within the repository. Which enhances the overall readability of the repository, minimizing confusion for new developers.

**Comment by cfradewavecom** [comment]
+1

**Comment by BenTheElder** [comment]
If you're still interested in this feature please file with the project's newly split out repo at https://github.com/kubernetes-sigs/prow

Unfortunately don't think we have maintainers with the bandwidth for feature requests like this currently and Kubernetes intentionally does NOT use inrepoconfig ourselves for security reasons.
