### ISSUE TITLE
/ok-to-test does not work

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#3181]
/assign @crimsonfaith91

**Comment by spxtr** [comment]
Link to a failed invocation?

**Comment by crimsonfaith91** [comment]
this may be a failure (pointed out by @grodrigues3 ): https://github.com/kubernetes/test-infra/pull/3174
but `/ok-to-test` on a newer PR: https://github.com/kubernetes/test-infra/pull/3182, and it works (the bot replied).

i will sync with Garrett about this.

**Comment by crimsonfaith91** [comment]
closed due to no report of re-occurrence.
