### ISSUE TITLE
ci/prow/images and ci/prow/use-mta-runner are failing for all MTA PR's

### ISSUE THREAD

**Issue by sshveta** [kubernetes/test-infra#31877]
Example PR : https://github.com/konveyor/tackle-ui-tests/pull/951. 

For all other PR's as well these jobs are failing . Can someone take a look.
```[tasklist]
### Tasks
```

**Comment by BenTheElder** [comment]
Huh? We don't run CI for that project?

**Comment by BenTheElder** [comment]
https://github.com/konveyor/tackle-ui-tests/pull/951#issuecomment-1935021636
