### ISSUE TITLE
Let's not suggest -misc teams

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#3190]
In general, we'd prefer if people mentioning teams would mention them by using one of the following suffixes rather than misc:

1. bugs
1. feature-requests
1. pr-reviews
1. test-failures
1. proposals

Can we change the error message [here]( https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/sig-mention-handler.go#L105) to reflect this preference rather than suggesting the use of the misc suffix. 

@bgrant0607 @kubernetes/sig-contributor-experience-feature-requests

**Comment by crimsonfaith91** [comment]
@grodrigues3 Agreed! 

There are no sig labels on this issue. Please [add a sig label](https://github.com/kubernetes/test-infra/blob/master/commands.md) by:<br>(1) mentioning a sig: `@kubernetes/sig-<team-name>-<suffix>`<br>e.g., `sig-api-machinery-bugs` for API Machinery<br>(2) specifying the label manually: `/sig <label>`<br>e.g., `/sig scalability` for sig/scalability<br><br>_Note: Method (1) will trigger a notification to the team. You can find the team list [here](https://github.com/kubernetes/community/blob/master/sig-list.md) and label list [here](https://github.com/kubernetes/kubernetes/labels).<br>The suffix should be one of the follows:<br>1. bugs<br>2. feature-requests<br>3. pr-reviews<br>4. test-failures<br>5. proposals_

**Comment by cblecker** [comment]
While the other team aliases are more specific, I'm not sure they've quite got the adoption. For example, for our own contribex, hitting feature-requests hits 5 people, vs -misc that hits 21. This would be the same for sig-testing (7 vs 18).

Is there a way we could encourage adoption if we continue down this path? or is it preferred to just move to mentioning a user and it sends to an e-mail list path (which I believe had started to be implemented, but not sure if it was ever finished).

**Comment by xiangpengzhao** [comment]
I see user confused by the `*` : https://github.com/kubernetes/kubernetes/issues/48147#issuecomment-311454933

**Comment by crimsonfaith91** [comment]
@xiangpengzhao I was suggested to have `*`. Please refer PR #3232 why we decided to have `*`.

**Comment by bgrant0607** [comment]
@cblecker I could encourage adoption of other teams by deleting the misc teams. :-)

**Comment by bgrant0607** [comment]
And hitting more people is not a good thing. Hitting the RIGHT people is what's important.

**Comment by xiangpengzhao** [comment]
This was addressed. I'm going to
/close
this issue. Feel free to correct me if I'm wrong.
