### ISSUE TITLE
Cherry-picker should copy release notes

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/test-infra#31929]
**What would you like to be added**:

Copy release notes into the PR description.

**Why is this needed**:

To simplify release processes

**Comment by alculquicondor** [comment]
/area prow

Not sure which sig owns this

**Comment by alculquicondor** [comment]
cc @matthyx

**Comment by matthyx** [comment]
no problem, ping me for review/approval

**Comment by alculquicondor** [comment]
It looks like this is already done, and the problem was the manual cherry-picks

**Comment by trasc** [comment]
@alculquicondor @mimowo 

For the k/k behavior mentioned by @mimowo (getting the release note from the original PR) , it works there based on the fact that the cherry-pick script create the branch with the name "automated-cherry-pick-of-<PRNUM>" and are merged with "Merge" method resulting in a commit like `Merge pull request #<CP_PRNUM> from <some-repo>/automated-cherry-pick-of-#<ORIG_PR_NUM>-.....`

**Comment by alculquicondor** [comment]
I see. And the cherry-picker commit is quite different https://github.com/kubernetes-sigs/kueue/commit/9f9069fcfaf4f0219791605b480d34ecbccac912

Is it possible that we can inspect the PR description? https://github.com/kubernetes-sigs/kueue/pull/1713

**Comment by trasc** [comment]
The way it works now is to get all the possible PRs out of the commit message then get their description, not recursive.

One thing we can try is to change the merge method for the PRs created with the hack script.

**Comment by alculquicondor** [comment]
Ok, let's close this issue then. It's not related to the cherry-picker plugin in this repo.

/close
