### ISSUE TITLE
PR tests are triggered though it has "needs-ok-to-test" label

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3193]
See PR: https://github.com/kubernetes/kubernetes/pull/47968

It has a `needs-ok-to-test` label, but all it's tests are triggered. The result is `1 pending and 9 successful checks`.

@fejta @krzyzacy @crimsonfaith91

**Comment by xiangpengzhao** [comment]
Also, No member has triggered it by `@k8s-bot ok to test`.

**Comment by spxtr** [comment]
On that PR, I see in the logs that an org member said "@k8s-bot test this" in a comment and then later deleted the comment :)

**Comment by xiangpengzhao** [comment]
:+1: Thanks @spxtr!
But in this case I still wonder why the `needs-ok-to-test` label wasn't removed after `@k8s-bot test this` was commented. It should be, right?

**Comment by cblecker** [comment]
`@k8s-bot test this` kicks off a single round of testing. `@k8s-bot ok-to-test` marks the PR as trusted, so that the PR owner can kick off their own re-tests, and future commits will also be re-tested.

**Comment by xiangpengzhao** [comment]
Thanks for explanation, Christoph! Got it:)
Does it also mean that `@k8s-bot test this` will not remove `needs-ok-to-test` label but `@k8s-bot ok-to-test` will?

**Comment by xiangpengzhao** [comment]
Thanks Christoph!
