### ISSUE TITLE
Bot comment should not trigger any event mentioning a sig

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#3199]
Bot comment should not trigger any event that adds a sig label.

This should not occur: https://github.com/kubernetes/kubernetes/issues/48025
Relevant to this issue: https://github.com/kubernetes/test-infra/issues/3180

/assign @crimsonfaith91

**Comment by xiangpengzhao** [comment]
This was addressed. I'm going to
/close
this issue. Feel free to correct me if I'm wrong.
