### ISSUE TITLE
Evolve Mungegithub

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#3200]
This is a collection of items that if done to mungegithub will make it more reusable and easy to maintain over time. 

1. [x] Teach mungegithub to read config files rather than commandline options (https://github.com/kubernetes/test-infra/pull/3429)
2. [x] Switch to using helm and helm updates to deploy the application and configuration (https://github.com/kubernetes/test-infra/pull/3478)
3. [ ] Allow easy management of multiple mungegithub instances - use helm common charts
4. [ ] Create a release process for mungegithub (tags, release notes)
5. [ ] Use [spinnaker](https://www.spinnaker.io/) or [container builder](https://cloud.google.com/container-builder/docs/how-to/build-triggers) and set up a continuous deployment pipeline for mungegithub
6. [ ] Consider moving mungegithub to a separate org/repo (TBD)

Please feel free to suggest more items, or discuss.
/cc @yutongz @cjwagner @spxtr @rmmh @apelisse

**Comment by sebastienvas** [comment]
Could we have one instance for multiple repo. For istio, it seems that we would need 18 instances. It would be preferable to have a unique instance / config and have the tool generate the amount of required queues, etc...

**Comment by kargakis** [comment]
> Could we have one instance for multiple repo? For istio, it seems that we would need 18 instances. It would be preferable to have a unique instance / config and have the tool generate the amount of required queues, etc...

Related discussion in https://docs.google.com/document/d/1IHTBo6Ul6TtTD87u8OVXgt-NgjgNSzE5JQKlu7nWDmw/edit#

**Comment by foxish** [comment]
> Could we have one instance for multiple repo? For istio, it seems that we would need 18 instances. It would be preferable to have a unique instance / config and have the tool generate the amount of required queues, etc...
 
@sebastienvas,
The biggest limiting factor IMO is github token usage, and the kubernetes main repo (see [k8s-merge-bot statistics](http://velodrome.kubernetes.io/dashboard/db/monitoring)) already runs rather close to the limit. We need some work to enable better use of tokens. OTOH, it may not make sense to have a submit-queue and automatic merges for every repo, especially ones which see less activity. The Kubernetes project has the submit-queue enabled for just 4 of its 20+ repositories.

**Comment by sebastienvas** [comment]
@foxish, I am not having issues with token just yet, but I might as soon as I have prow and mungegithub set up. The repos with the most contributions are pilot, mixer, auth, gally and istio. And I understood that we need an instance per branch? so that would mean 10 instances.

**Comment by spiffxp** [comment]
@foxish that graph was bumped artificially high by bulk-lgtm, take a look again and you should see more representative usage (hat tip to @apelisse)

**Comment by foxish** [comment]
+1 awesome work @apelisse 

Makes sense I think, to have mungegithub spawn multiple threads and work on multiple repos. I'll add it to the list above. 
The only reason then to use multiple instances in this future world would be because we're hitting token limits.

**Comment by rmmh** [comment]
Right now the limitation is more that mungegithub has a lot of global state. A large refactor/rewrite would be necessary to make it work with multiple repos.

**Comment by foxish** [comment]
I believe we could accomplish quite a bit of that goal by having a higher level wrapper that spawns goroutines running the existing munging logic for different repos. I'm not sure how that would work with the caching etc. It would need some reworking, but with istio, we may be able to make it happen.

**Comment by foxish** [comment]
Just added https://github.com/kubernetes/test-infra/pull/3478 which adds a helm chart. I think the use of helm will reduce the burden of maintaining several of these (@sebastianvas, this was your primary concern), since it lets us templatize a tonne of things that are shared. I'm also planning on using a common-chart for the `image:tag` and other common fields that need to be shared across multiple deployments.

The next step I see is CD, and instead of spinnaker, I'm thinking of setting up build triggers on commits, using https://cloud.google.com/container-builder/docs/how-to/build-triggers and just having it run helm upgrade for us. PTAL.

**Comment by stevekuznetsov** [comment]
Not sure this is relevant in any way now as the `mungegithub` code is on its way to a graveyard.

/close
