### ISSUE TITLE
Dynamic scheduling of Prowjobs to clusters

### ISSUE THREAD

**Issue by danilo-gemoli** [kubernetes/test-infra#32039]
**What would you like to be added**:
I want to introduce a scheduler that dynamically dispatches ProwJobs across clusters.

**Why is this needed**:
Increase fault tolerance, reduce operation burden and CI costs.

Design doc [here](https://docs.google.com/document/d/10vj0zsmg5vqrfrTJ2hWen1Kf1es3ERZgRa6H_1YY1UI/edit#heading=h.rcwjfdjs3ra6).

/cc @petr-muller @stevekuznetsov @droslean @smg247 @jmguzik

**Comment by petr-muller** [comment]
/retitle Dynamic scheduling of Prowjobs to clusters

**Comment by stevekuznetsov** [comment]
I like the proposal and think the backwards-compatible and incremental process proposed is a great way forward/
