### ISSUE TITLE
rewrite kubernetes_build scenario to use kubetest instead of shell scripts

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#3207]
The `kubernetes_build` scenario is confusing, with a large number of mysterious flags and environment variables, and most of the real functionality is driven by a shell script in `kubernetes/kubernetes/hack/jenkins`.

We should rewrite this as a simple python script that wraps calls to `kubetest`.

**Comment by fejta** [comment]
I think this is done?

**Comment by ixdy** [comment]
we're not using kubetest, but I'm not sure we want to. things are at least a bit more maintainable now.
