### ISSUE TITLE
Branch protection rules prevent first PR of a merge-batch from being merged

### ISSUE THREAD

**Issue by oliver-goetz** [kubernetes/test-infra#32097]
**What happened**:
When `tide` is creating a new merge-batch it starts the required tests for the batch, but also trigger those tests for its member with the lowest PR number (PR 9200 in my screenshot below). 

![Screenshot 2024-02-28 at 16 14 50](https://github.com/kubernetes/test-infra/assets/47362717/ac1be350-7a84-45b3-b99a-f7989491ba9c)

`tide` starts merging the PRs directly when the tests for the `merge-batch` are completed.
If there are branch-protection rules those rules prevent the PR with the lowest number (PR 9200) from being merged until its individual tests succeeded.
This results in a race between both test runs. When the `merge-batch` test run wins, all PRs except the first are merged and the first PR becomes part of the next `merge-batch`.
It is likely that the merge-batch test run wins the race, because it is created first.

![Screenshot 2024-02-28 at 16 47 21](https://github.com/kubernetes/test-infra/assets/47362717/3002f588-33ec-434b-bc04-f25881901b98)

As you can see in tide history, poor PR 9200 already lost a couple of races and is still not merged yet.

![Screenshot 2024-02-28 at 17 56 15](https://github.com/kubernetes/test-infra/assets/47362717/1eb74ee9-c6d7-4a3e-8cb7-64f3d60568fc)

While I'm writing this issue, 9200 lost another race 😢 

**What you expected to happen**:
I except that all PRs of a merge-batch are merged by `tide` if the tests succeed.

I could imagine two approaches to solve the issue:
1. `tide` could wait until all tests of the single PR are finished too before it starts merging
2. `tide` could still merge directly when the tests of the merge-batch succeed. In this case it could overwrite the contexts of the tests of the single PR 

**How to reproduce it (as minimally and precisely as possible)**:

**Please provide links to example occurrences, if any**:
You could check the history of PR 9200 in our prow instance:
https://prow.gardener.cloud/tide-history?repo=gardener%2Fgardener&pull=9200

**Anything else we need to know?**:
I'm happy to implement a solution if we can agree on an approach.

**Comment by petr-muller** [comment]
Ouch, that's painful. Nice report :+1: 

Personally I like the second approach:

> tide could still merge directly when the tests of the merge-batch succeed. In this case it could overwrite the contexts of the tests of the single PR

When a batch passes, Tide could abort the individual jobs for the single PR and backfill their results from the jobs run within a batch. Not sure how feasible that is, but it feels better than waiting for the single PR (which may take more time and even fail in the presence of flakes)

**Comment by oliver-goetz** [comment]
Okay 👍 
I did not find the time yet, but maybe I can do something about it the next weeks 😅

**Comment by BenTheElder** [comment]
unfortunately github doesn't support migrating issues across organizations, this appears to be active? @oliver-goetz can you re-file this against kubernetes-sigs/prow, we're trying to consolidate prow issues there as part of the migration.

I dropped a ping in #prow slack to nudge re: reviewing your PR

**Comment by oliver-goetz** [comment]
Thanks @BenTheElder 😄 
I just re-filed this issue: https://github.com/kubernetes-sigs/prow/issues/209

/close

**Comment by BenTheElder** [comment]
Thanks!
