### ISSUE TITLE
Assign/CC doesn't work when there is trailing text

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/test-infra#32199]
I added a comment at the end of my assign command and oddly it didn't work

https://github.com/kubernetes-sigs/gateway-api/pull/2845#issuecomment-1984579155

```
/assign @some-user #...
```

I'd assume it would assign the issue to some-user - unsure if the regexp is too strict or not

**Comment by BenTheElder** [comment]
this is true of most prow commands I think? you generally need to move non-command input to another line

**Comment by dprotaso** [comment]
That's fair - I guess assign works without the `@` so it wouldn't know if a normal word is a comment or a user
