### ISSUE TITLE
prow: plank needn't depend on jenkins

### ISSUE THREAD

**Issue by nlandolfi** [kubernetes/test-infra#3221]
Presently, plank's [main function](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/plank/main.go#L47) uses a [jenkinsTokenFile](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/plank/main.go#L66) to construct a Jenkins client. I believe the jenkins client can be nil, and the jenkins functionality of plank effectively ignored. 

Is it reasonable to do something similar to...
```go
var jc *jenkins.Client

if jenkinsTokenFile != "" {
        logrus.Infof("Configuring Jenkins client...")
	if err != nil {
		logrus.WithError(err).Fatalf("Could not read token file.")
	}
	jenkinsToken := string(bytes.TrimSpace(jenkinsSecretRaw))

	jc = jenkins.NewClient(*jenkinsURL, *jenkinsUserName, jenkinsToken)
}
```

For istio, we don't need the Jenkins functionality, and would like if this was configurable. I could submit a CL for this if appropriate.

**Comment by spxtr** [comment]
I completely agree, and will gladly accept your PR. Please give `cmd/deck` the same treatment.

**Comment by spxtr** [comment]
Fixed. Thanks!
