### ISSUE TITLE
`Spyglass` doesn't load the build-log when the file is very large

### ISSUE THREAD

**Issue by smg247** [kubernetes/test-infra#32246]
**What happened**:
Spyglass doesn't load the 'Build Log' for an execution when the log is large. Instead it just spins until the browser kills it or the user gives up. Sometimes, it eventually loads, but after a very long time.

**What you expected to happen**:
The log will load within a reasonable amount of time.

**How to reproduce it (as minimally and precisely as possible)**:
Navigate [here](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-metal-ipi-upgrade-ovn-ipv6/1765598839164637184) and observe that the 'build log' section fails to load (or at least takes a very long time).

**Please provide links to example occurrences, if any**:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-metal-ipi-upgrade-ovn-ipv6/1765598839164637184

**Anything else we need to know?**:
I believe this is due to the warning/error highlighting logic. We should make no attempt at doing this with log files over a certain size (1MB? 50,000 lines?).

**Comment by smg247** [comment]
Perhaps we could just highlight errors/warnings found at the beginning and end of the logs in these cases. We could only look through the first and last 1,000 or so lines of the file.

**Comment by BenTheElder** [comment]
> I believe this is due to the warning/error highlighting logic. We should make no attempt at doing this with log files over a certain size (1MB? 50,000 lines?).

+1. We should also consider providing an error + log link over attempting to render it inline at all IMHO

**Comment by Vyom-Yadav** [comment]
+1 for this, I've also faced this

**Comment by BenTheElder** [comment]
Note: prow source code moved to kubernetes-sigs/prow and issues like this probably need to get re-filed there.

**Comment by BenTheElder** [comment]
Please file again in kubernetes-sigs/prow if you're still interested in discussing this. I think it's valid but ... prow also has limited maintainer bandwidth.
