### ISSUE TITLE
cherrypicker can't create cherry-pick if PR contains more that 300 files

### ISSUE THREAD

**Issue by dhiller** [kubernetes/test-infra#32405]
**What happened**:

We recently stumbled over our prow cherrypicker plugin [silently failing to create a cherry-pick from one of our pull requests](https://github.com/kubevirt/application-aware-quota/pull/33#issuecomment-2042092569) inside the [KubeVirt org](https://github.com/kubevirt). 

Partial error log (for brevity):
```
...
"component": "cherrypicker",
  "error": "failed to get patch: status code 406 not one of [200], body: {\"message\":\"Sorry, the diff exceeded the maximum number of files (300). Consider using 'List pull requests files' API or locallycloning the repository instead.\",\"errors\":[{\"resource\":\"PullRequest\",\"field\":\"diff\",\"code\":\"too_large\"}],\"documentation_url\":\"https://docs.github.com/rest/pulls/pulls#list-pull-requests-files\"}",
...
```

The [docs say the maximum for un-paginated access is `3000`](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files), where obviously it's "only" 300.

I didn't look at the code, but I suspect that authors did actively neglect the edge case of  > 3000 files, which should rarely happen, but did happen in our case.

**What you expected to happen**:

We expected a cherry-pick to be created on the PR after issuing the `/cherry-pick` command. 

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Please provide links to example occurrences, if any**:
https://github.com/kubevirt/application-aware-quota/pull/33#issuecomment-2042092569

**Anything else we need to know?**:
Apart from this issue I've [opened a discussion on GitHub](https://github.com/orgs/community/discussions/118311) in order to clarify whether it's an API or docs bug.

**Comment by BenTheElder** [comment]
We moved prow out to it's own repo earlier this year https://sigs.k8s.io/prow

This sounds like an ongoing issue, but not one the kubernetes project is experiencing (we don't use this plugin currently), would you mind re-filing it there? Thanks.
