### ISSUE TITLE
Approval munger spams merged PRs

### ISSUE THREAD

**Issue by eparis** [kubernetes/test-infra#3241]
I overwrote the approval label manually because the "no-issue" check (which FYI I still hate) wouldn't listen to the PR author. Now the munger is writing to the PR even though it is closed.

https://github.com/kubernetes/kubernetes/pull/47904#issuecomment-311611719

**Comment by spiffxp** [comment]
This may have been fixed by #3252

**Comment by spiffxp** [comment]
(though the safeguard of not hitting PR's that have been merged is still valid)

**Comment by fejta** [comment]
Fixed, and we're migrating approval to a prow plugin
/cc @kargakis @cjwagner
