### ISSUE TITLE
Failed job message persists in PR despite job not being triggered and retired

### ISSUE THREAD

**Issue by amirrmonfared** [kubernetes/test-infra#32438]
**What happened**:
I had failed job and it was configured to only be triggered if the yaml files are changed. After I have removed changes from yaml file and rebased and pushed the commit I saw the message include failure still is in the PR but the job has been retired. It's not a blocker but it will mislead the reviewer that has something is failed

**What you expected to happen**:
To remove the message related to the job that failed previously but was not triggered in the new commit.

**How to reproduce it (as minimally and precisely as possible)**:
Probably you can set a job to trigger on yaml changes like the configuration I mentioned below and then wait for it to fail, then rebase the commit and delete the changes on yaml file and push again.

```
    - agent: kubernetes
      always_run: false
      run_if_changed: "\\.(yaml|yml)$"
```

**Comment by BenTheElder** [comment]
Yes, this is a long known issue though I'm struggling to dig it up.

The code for this has moved to https://github.com/kubernetes-sigs/prow and in the future issues should be filed there.
