### ISSUE TITLE
bulk-lgtm is making to many github API calls

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#3249]
This is replacing/extending #2969.

I've tried to re-run bulk-lgtm with my own token and more debug (#3248), and clearly it's using too many tokens:
```
[github.go:2531] Munged 4903 modified issues. (0 because of status change)
[github.go:257] Made 760 API calls since the last Reset 1.219512 calls/sec
[mungegithub.go:76] Sleeping for 5m34.401511439s
```

760 API calls every 10 minutes, with mostly calls to `GetPR` that mostly misses the cache. The deployment doesn't use a `CacheDir` [anyway](https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/bulk-lgtm/deploy.yaml).

I'm very tempted to disable the service until this has been fixed.

**Comment by spiffxp** [comment]
OK, I wasn't sure if it was just me.  I noticed the github token usage graph has been maxing out pretty hard on weekday ever since bulk-lgtm was deployed

http://velodrome.k8s.io/dashboard/db/monitoring?from=now-90d&to=now

**Comment by cblecker** [comment]
Potentially dumb question: Because bulk-lgtm requires you to log into github, could it not use the logged in user's token instead of the system token? That would split up the calls so the bot tokens don't flood out.

**Comment by apelisse** [comment]
> OK, I wasn't sure if it was just me. I noticed the github token usage graph has been maxing out pretty hard on weekday ever since bulk-lgtm was deployed

I can't believe you knew that was it 😭

**Comment by apelisse** [comment]
@cblecker Yeah, IMO this could be written mostly with client-code/javascript here. I'm not sure what is the added value of the server so much.

**Comment by apelisse** [comment]
http://velodrome.kubernetes.io/dashboard/db/monitoring?from=now-2d&to=now is pretty much confirming.

**Comment by spiffxp** [comment]
Just to be explicit about it since the issue description indicates a "temptation" to disable the service, https://github.com/kubernetes/test-infra/issues/2969#issuecomment-314835934 indicates bulk-lgtm has since been disabled.

By disabled do we mean the files in https://github.com/kubernetes/test-infra/tree/master/mungegithub/bulk-lgtm aren't deployed to a cluster atm? Would we re-enable by deploying these?

**Comment by apelisse** [comment]
> By disabled do we mean the files in https://github.com/kubernetes/test-infra/tree/master/mungegithub/bulk-lgtm aren't deployed to a cluster atm?

Yes, [it](https://kubernetes.submit-queue.k8s.io/bulk-lgtm/) is not running.

> Would we re-enable by deploying these?

Yes, bug would reappear if redeployed.

**Comment by xiangpengzhao** [comment]
bulk-lgtm was removed in #4101.
So we can 
/close
this issue anyway.
