### ISSUE TITLE
The release note bot should ignore PRs cherrypicked to the earlier release

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#3256]
I don't know if this is useful, but when editing release notes, in the gdoc, I noticed 5-6 or so PRs, that was suggested for inclusion in the v1.7 noteworthy changes release notes, that had been cherrypicked into v1.6.
The policy IIRC is to have a release-note for all PRs that are gonna be cherrypicked to an earlier release, which means that those will naturally become a part of release notes for v1.7 with the current code.

Q: Do we think this is even a problem?

Q: Can/should we filter out PRs that have been cherrypicked earlier when aggregating notes to a new release?

**Comment by spiffxp** [comment]
>Q: Do we think this is even a problem?

Personally, no.  IMO it is correct that the release notes represent changes from 1.6.0->1.7.0, and it would be unexpected if they represented 1.6.6->1.7.0 (eg: or will it be 1.6.7 by the time 1.7.0 is cut?)

What do @kubernetes/sig-release-feature-requests and @kubernetes/sig-docs-maintainers think?

**Comment by spiffxp** [comment]
also FWIW this probably belongs in kubernetes/release, as that's where the `relnotes` script is

**Comment by kargakis** [comment]
Agreed with @spiffxp

**Comment by luxas** [comment]
Agreed, makes sense. Just a thought that needed validation. I have both good and bad ideas ;)
