### ISSUE TITLE
Document how batch merges work

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3258]
It is going to be really helpful for future interested parties to have a doc that breaks down how batch merges work. 

1. The SubmitQueue picks up mergeable PRs from Github
2. splice asks the SQ for mergeable PRs
3. splice creates a batch ProwJob
4. plank starts the actual pod/jj for the batch PJ
5. At least in the Jenkins case, it's up to the Jenkins job to pick up PULL_REFS, break that down in order to determine the PRs that need to be tested together, fetch+merge, profit. Haven't tested so I am not sure yet how this case is handled for pods.
6. pod/jj completes, plank moves PJ to completion
7. SQ asks deck for batch PJs, finds the complete batch PJ, merges every PR in the PJ iff none of the preconditions is violated eg. another commit has sneaked in master in the meantime.

**Comment by spiffxp** [comment]
Assuming we document how tide does its batch merges, I think this can be considered obviated by #3866

**Comment by stevekuznetsov** [comment]
There was extra complexity with the interaction between Prow and the SQ on this so more documentation would have been nice. Now that it's just `tide` handling things this is no longer really appropriate.

/close
