### ISSUE TITLE
Change etcd testgrid to points to etcd repo

### ISSUE THREAD

**Issue by ah8ad3** [kubernetes/test-infra#32660]
**What happened**:
File a bug in test grid of etcd robustness points to Kubernetes main repo which may not be ideal.

**What you expected to happen**:
It should create an issue on https://github.com/etcd-io/etcd/issues/ instead.

**How to reproduce it (as minimally and precisely as possible)**:
For example right click on a flaky and click `File a bug`,.

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/sig-etcd-robustness#ci-etcd-robustness-amd64 

**Anything else we need to know?**:
Talked with @serathius in robustness meeting and discuss it would be better to change the pointer.

**Comment by ah8ad3** [comment]
I have some free time, might look at the code to see if i can change it.

**Comment by ah8ad3** [comment]
Never mind it's js code. 
https://github.com/kubernetes/test-infra/blob/6a23f984a73c30c4ada98e7e4c6fa70cbbaf45f9/triage/render.js#L324

**Comment by BenTheElder** [comment]
triage is a different tool at https://go.k8s.io/triage

the bug template is configurable https://github.com/kubernetes/test-infra/blob/master/testgrid/config.md#linkbugregression-search-templates

**Comment by BenTheElder** [comment]
/sig etcd

cc @wenjiaswe

**Comment by siyuanfoundation** [comment]
fixed by https://github.com/kubernetes/test-infra/pull/32715 and https://github.com/kubernetes/test-infra/pull/32787
