### ISSUE TITLE
Reporting periodic jobs failures to slack channel after number of consequent failures

### ISSUE THREAD

**Issue by Sunnatillo** [kubernetes/test-infra#32687]
**What would you like to be added**:
We would like to add a Slack reporter for failed jobs to our cluster-api Slack channel. However, we are concerned about the potential for excessive notifications, as every failure would generate a message in the channel. It would be beneficial to implement a parameter similar to `testgrid-num-failures-to-alert:5 `for Slack reporters. Currently, this parameter only works for email notifications

**Why is this needed**:
To manage the frequency of Slack notifications by only sending alerts after a specified number of failures. This will reduce noise and prevent the Slack channel from becoming overwhelmed with failure messages.

**Comment by MadhavJivrajani** [comment]
Migrated issue: https://github.com/kubernetes-sigs/prow/issues/195
