### ISSUE TITLE
 metrics-bigquery constantly failing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#32864]
https://kubernetes.slack.com/archives/CCK68P2Q2/p1719520814917589

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/metrics-bigquery

https://testgrid.k8s.io/sig-testing-misc#metrics-bigquery

/assign
/assign @dims

**Comment by dims** [comment]
i think there's more stuff to do here @BenTheElder will poke at it tomorrow

**Comment by BenTheElder** [comment]
too many things to do :(
