### ISSUE TITLE
config/jobs: revert frequency of CLA bot to 10m

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/test-infra#32879]
We changed the frequency of the CLA bot to 24 hours to avoid spam while the EasyCLA migration was going on (https://github.com/kubernetes/test-infra/pull/29148)

Now that that is done, we should probably revert back to 10m to let the bot help commenting with `/easycla` and avoid having new contributors figure out how to recheck CLA status. 

### Here's what needs to be done

https://github.com/kubernetes/test-infra/blob/b89b3769f19b8f990a1ad64c547375373cca995e/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-contribex-k8s-triage-robot.yaml#L91-L92

Remove the `TODO` and change interval to `10m`

/sig contributor-experience
/good-first-issue

**Comment by MadhavJivrajani** [comment]
@anushkaguptaaa do you want to give this a shot?

**Comment by anushkaguptaaa** [comment]
Surely Madhav!! I'd love to.
/assign
