### ISSUE TITLE
k8s-merge-robot labels PR "release-note" even when the release note is "NONE"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3295]
When I fixed broken format in CHANGELOG, I found that there are several PRs which have label `release-note` but their release notes are just `NONE`. See:　https://github.com/kubernetes/kubernetes/pull/48328#issuecomment-312274073

One of the PRs is https://github.com/kubernetes/kubernetes/pull/45317. In its description, its release note is `NONE`, but bot still labeled `release-note` to it. It should label `release-note-none` but not. I guess the author wrote a non-`NONE` release note at first and then bot labeled `release-note`, and then the author edited the release note to be `NONE` finally, but the bot didn't recognize this. If it was this case, I think bot should remove `release-note` and label ~~`release-note`~~ `release-note-none` when it notices the release note template is edited to be `NONE`.

/cc @crimsonfaith91

**Comment by crimsonfaith91** [comment]
@spxtr A feedback regarding release-note prow plugin that you may be able to help with. :)

**Comment by kargakis** [comment]
It seems that the plugin today handles [only new comments](https://github.com/kubernetes/test-infra/blob/625ac8c55eaa2b44020805ff5304d3f6ad4e4418/prow/plugins/releasenote/releasenote.go#L66) and ignores edits.

**Comment by xiangpengzhao** [comment]
Thanks @kargakis!
It would be good to support handling edits.

**Comment by spiffxp** [comment]
I'm tacking on mungegithub since that's where the auto-labeling lives today, but leaving prow if this is in the interest of moving more of that logic to prow.
/area mungegithub

**Comment by spxtr** [comment]
[This block](https://github.com/kubernetes/test-infra/blob/7665825220ee57fe751f3017ba0b5447e2bd257c/mungegithub/mungers/release-note-label.go#L127-L130) appears to be the issue:
```go
if releaseNoteAlreadyAdded(obj) {
	r.ensureNoRelNoteNeededLabel(obj)
	return
}
```
If there is already a release note label then the munger quits right away.

**Comment by xiangpengzhao** [comment]
@spxtr any plan we want to fix this?

In https://github.com/kubernetes/kubernetes/pull/46079, I was asked to add a release note and then I edited the release notes from `NONE` to something else, but bot didn't change `release-note-none` to `release-note`. I hope it could detect edits.

**Comment by fejta** [comment]
Just add a /release-note-none comment

**Comment by xiangpengzhao** [comment]
@fejta What I need is a `/release-note` label, so I think you meant adding a `/release-note` comment :)

I commented it and it worked https://github.com/kubernetes/kubernetes/pull/46079#issuecomment-319247332. Thanks @fejta !
