### ISSUE TITLE
Add 1.7 to GKE Tab in Testgrid

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#3303]
In the https://k8s-testgrid.appspot.com/google-gke view, we have tabs for 1.5 and 1.6.  We should also include all the 1.7 tests

**Comment by krzyzacy** [comment]
@grodrigues3 after a second look, it does not have 1.6 jobs (except the ones validates ubuntu images), do we still expect all jobs to be there?

**Comment by krzyzacy** [comment]
@grodrigues3 maybe either ask someone cares about the gke dashboard (gke release manager?) to send a PR to customize this, or close it.

**Comment by grodrigues3** [comment]
@jlowdermilk

**Comment by jlowdermilk** [comment]
I just mentioned this to @fabioy a few minutes ago. We will get the tab updated.
