### ISSUE TITLE
Move GKE deployment from cluster/gke to kubetest 

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#3307]
As part of the effort to thin down https://github.com/kubernetes/kubernetes/tree/master/cluster, it's easy enough to just remove the whole `cluster/gke` directory by moving to a `kubetest` [deployer](https://github.com/kubernetes/test-infra/blob/0981cb3a959fc0c36a378d3201fa28c268054796/kubetest/main.go#L164), since `cluster/gke` is really only around for e2es.

**Comment by spiffxp** [comment]
@fejta FYI, created the area/kubetest label, seemed appropos
@zmerlynn I'll leave it to you whether you want to leave on the shrug
