### ISSUE TITLE
Is JENKINS_GCI_HEAD_IMAGE_FAMILY used?

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#3313]
As part of analyzing env variables used while working on #3307, I noticed that `JENKINS_GCI_HEAD_IMAGE_FAMILY` is provided but never consumed: https://github.com/search?q=org%3Akubernetes+JENKINS_GCI_HEAD_IMAGE_FAMILY&type=Code

Can I remove it?

cc @wonderfly @abgworrall @fejta

**Comment by fejta** [comment]
Should be converted into an arg in config.json to `--extract=gci/gci-canary`

Maybe something was missed during the conversion?

https://github.com/kubernetes/test-infra/commit/bfb5d9536ba48b4c1f3563e3b8c97c8816b32fb7#diff-6276ace2db72f1df8d04fb42c6989b69

**Comment by zmerlynn** [comment]
Probably?
https://github.com/kubernetes/test-infra/blob/c263222cdc3bb04daeed77c5a8afd8f676215e87/jobs/ci-kubernetes-e2e-gce-gci-ci-master.env
https://github.com/kubernetes/test-infra/blob/8e2bcd34e0cf9f8f27fbf238fdbebe2749da0c4e/jobs/config.json#L1432

**Comment by zmerlynn** [comment]
It also looks like any GKE use of this variable is invalid - `extract.py` isn't setting anything GKE cares about.

**Comment by wonderfly** [comment]
cc/ @kubernetes/goog-image 

I am surprised that both env vars had been replaced... Note that they served different purposes: `JENKINS_GCI_HEAD_IMAGE_FAMILY` says we want to use GCI's daily build as opposed to the hardcoded default as the base image, and `JENKINS_USE_GCI_VERSION` says that we want to use the image's builtin k8s to start the cluster. 

Looks like https://github.com/kubernetes/test-infra/blob/master/kubetest/extract.go has had both reimplemented, but apparently the migration for the `ci-kuber-netes-e2e-gce-gci-ci-*` jobs missed the gci image family part:  **They were supposed to have `--extract=gci/<gci-image-family>/<k8s-ci-version>`**. For example, `ci-kubernetes-e2e-gce-gci-ci-master` should have `--extract=gci/gci-canary/latest` while `ci-kubernetes-e2e-gce-gci-ci-release-1-5` should have `--extract=gci/gci-canary/latest-1.5`.

**Comment by wonderfly** [comment]
So I am afraid the gci-ci- jobs has been running with the wrong GCI images (or maybe even with Debian) for long...

**Comment by zmerlynn** [comment]
Fixed by #3390, thanks!
