### ISSUE TITLE
AWS 5k Scale tests are failing 

### ISSUE THREAD

**Issue by hakuna-matatah** [kubernetes/test-infra#33190]
**What happened**:

It appears that ASG is not be able to be created because of ASG with same name is in pending delete state.

```
W0801 10:46:37.053019   51575 autoscalinggroup.go:339] Skipping AutoScalingGroup nodes.scale-1000.periodic.test-cncf-aws.k8s.io: Delete in progress
W0801 10:46:37.931592   51575 executor.go:141] error running task "AutoscalingGroup/nodes.scale-1000.periodic.test-cncf-aws.k8s.io" (9m58s remaining to succeed): error creating AutoScalingGroup: AutoScalingGroup by this name already exists - A group with the name nodes.scale-1000.periodic.test-cncf-aws.k8s.io already exists and is pending delete.  Please wait until Autoscaling completes the deletion process before creating another group with the same name.
```

```
Skipping AutoScalingGroup nodes.scale-1000.periodic.test-cncf-aws.k8s.io: Delete in progress
W0801 10:56:29.070036   51575 executor.go:141] error running task "AutoscalingGroup/nodes.scale-1000.periodic.test-cncf-aws.k8s.io" (7s remaining to succeed): error creating AutoScalingGroup: AutoScalingGroup by this name already exists - A group with the name nodes.scale-1000.periodic.test-cncf-aws.k8s.io already exists and is pending delete.  Please wait until Autoscaling completes the deletion process before creating another group with the same name.
I0801 10:56:29.070075   51575 executor.go:171] Continuing to run 1 task(s)
Error: error running tasks: deadline exceeded executing task AutoscalingGroup/nodes.scale-1000.periodic.test-cncf-aws.k8s.io. Example error: error creating AutoScalingGroup: AutoScalingGroup by this name already exists - A group with the name nodes.scale-1000.periodic.test-cncf-aws.k8s.io already exists and is pending delete.  Please wait until Autoscaling completes the deletion process before creating another group with the same name.
```

**What you expected to happen**:
Scale test to succeed

**How to reproduce it (as minimally and precisely as possible)**:
Periodics scale tests are reproducing this for last couple of days

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1818950113440043008

**Anything else we need to know?**:

**Comment by hakuna-matatah** [comment]
cc: @hakman @dims

**Comment by hakuna-matatah** [comment]
i see a pattern that first run gets stuck in running state from UI and then consecutive run gets into this state of ASG resources not getting cleaned up.
Not sure how it can impact, give we also have Janitors running.

**Comment by dims** [comment]
There's nothing in the account/region - tried global view as well

![image](https://github.com/user-attachments/assets/2de66699-6d86-46fd-bf6c-b63a1753cf69)

**Comment by dims** [comment]
@hakuna-matatah since i can't find the ASG by that name, can you PR a change to this line - [https://github.com/kubernetes/test-infra/blob/5d0231fadaf3713102919a67edbf06efd1f1[…]bs/kubernetes/sig-scalability/sig-scalability-periodic-ec2.yaml](https://github.com/kubernetes/test-infra/blob/5d0231fadaf3713102919a67edbf06efd1f15403/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-ec2.yaml#L122)
to change it from scale-1000  to scale-5000 (since it's actually 5k tests and to see if that can get us past this problem)

**Comment by dims** [comment]
slack thread: https://kubernetes.slack.com/archives/CCK68P2Q2/p1722528460903749?thread_ts=1722526256.053579&cid=CCK68P2Q2

**Comment by hakuna-matatah** [comment]
https://github.com/kubernetes/test-infra/pull/33192

**Comment by dims** [comment]
for the 2 different runs .. ARNS for the ASG is different.

```
W0731 10:56:51.774682   50662 aws_cloud.go:942] Skipping ASG arn:aws:autoscaling:us-east-2:226543828060:autoScalingGroup:f461c8e5-e7d2-4b2c-9817-dae39f597527:autoScalingGroupName/nodes.scale-1000.periodic.test-cncf-aws.k8s.io (which matches tags): Delete in progress

W0801 10:56:40.378106   51612 aws_cloud.go:942] Skipping ASG arn:aws:autoscaling:us-east-2:226543828060:autoScalingGroup:6b15e04c-616c-4088-9e24-fd93cd33162c:autoScalingGroupName/nodes.scale-1000.periodic.test-cncf-aws.k8s.io (which matches tags): Delete in progress
```
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1818950113440043008/build-log.txt
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1818587581143584768/build-log.txt

**Comment by hakuna-matatah** [comment]
I have created clusters with ASG resources `nodes.scale-1000.periodic.test-cncf-aws.k8s.io` and `nodes.scale-5000.periodic.test-cncf-aws.k8s.io`    both seem to succeed fine now.

https://github.com/kubernetes/kops/pull/16718#issuecomment-2264139302

**Comment by hakuna-matatah** [comment]
For the successful run , it doesn't seem to find the previous cluster fmu based on my one off runs - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/16718/presubmit-kops-aws-small-scale-amazonvpc-using-cl2/1819123862298693632/build-log.txt

```
I0801 21:40:42.079495   49539 up.go:58] Cleaning up any leaked resources from previous cluster
W0801 21:40:42.225948   49539 state.go:46] failed to run /home/prow/go/src/k8s.io/kops/_rundir/a1b538d7-1567-40fe-a843-0c5d0c39d1e3/kops get cluster scale-1000.periodic.test-cncf-aws.k8s.io -ojson; stderr=I0801 21:40:42.089107   49566 featureflag.go:168] FeatureFlag "AWSSingleNodesInstanceGroup"=true
```

However from failed periodic run , it thinks previous cluster exists

```
I0731 10:10:23.017493   50327 up.go:58] Cleaning up any leaked resources from previous cluster
I0731 10:10:23.222655   50327 dumplogs.go:51] /home/prow/go/src/k8s.io/kops/_rundir/e9e8e2b0-7750-467c-a1dd-cd43b14c071d/kops toolbox dump --name scale-1000.periodic.test-cncf-aws.k8s.io --dir /logs/artifacts --private-key /tmp/kops/scale-1000.periodic.test-cncf-aws.k8s.io/id_ed25519 --ssh-user ubuntu
I0731 10:10:23.231909   50371 featureflag.go:168] FeatureFlag "AWSSingleNodesInstanceGroup"=true
W0731 10:10:49.443493   50371 toolbox_dump.go:172] cannot load kubeconfig settings for "scale-1000.periodic.test-cncf-aws.k8s.io": context "scale-1000.periodic.test-cncf-aws.k8s.io" does not exist
```
  
and keeps trying to ssh to the nodes and eventually times out after like 22 mins or so and defaults to kops delete cluster  to delete all resources associated to that cluster even before the new periodic run begins -  https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1818587581143584768/build-log.txt

**Comment by hakuna-matatah** [comment]
Basically when it run `kops get cluster scale-1000.periodic.test-cncf-aws.k8s.io -ojson` on failed clusters, it gets the response back but for successful runs it doesn't get any response , so it thinkx cluster doesn't exist and proceed to creation. 

**Successful run:** 
```
I0801 21:40:42.079495   49539 up.go:58] Cleaning up any leaked resources from previous cluster
W0801 21:40:42.225948   49539 state.go:46] failed to run /home/prow/go/src/k8s.io/kops/_rundir/a1b538d7-1567-40fe-a843-0c5d0c39d1e3/kops get cluster scale-1000.periodic.test-cncf-aws.k8s.io -ojson; stderr=I0801 21:40:42.089107   49566 featureflag.go:168] FeatureFlag "AWSSingleNodesInstanceGroup"=true
```

**Failed run:**
But failed cluster because it gets the response back it attempts to dump the logs and then delete the cluster 

```
I0801 10:33:07.021656   51363 dumplogs.go:99] /home/prow/go/src/k8s.io/kops/_rundir/283379e9-5d41-4330-b3ef-ce2251ecc31f/kops get cluster --name scale-1000.periodic.test-cncf-aws.k8s.io -o yaml
I0801 10:33:07.192647   51363 dumplogs.go:99] /home/prow/go/src/k8s.io/kops/_rundir/283379e9-5d41-4330-b3ef-ce2251ecc31f/kops get instancegroups --name scale-1000.periodic.test-cncf-aws.k8s.io -o yaml
I0801 10:33:07.676744   51363 down.go:66] /home/prow/go/src/k8s.io/kops/_rundir/283379e9-5d41-4330-b3ef-ce2251ecc31f/kops delete cluster --name scale-1000.periodic.test-cncf-aws.k8s.io --yes --interval=60s --wait=60m
```

**Comment by hakuna-matatah** [comment]
This could have happened if and only if previous run didn't clean up the `KOPS_STATE_STORE`.

I am thinking next run should probably succeed as test runs succeeded which means **KOPS_STATE_STORE** got back to clean state.

**Comment by hakuna-matatah** [comment]
What i just noticed is that it is reporting two separate runs instead of one everyday ? One in stuck running and followed by other failing.

Ideally it should be showing just one as we only schedule one run.

**Comment by hakuna-matatah** [comment]
From @xmudrii  from Slack chat, it appears the test-pod is being evicted in the middle of test run due to hitting storage limits on Host cluster.

![image (9)](https://github.com/user-attachments/assets/6d193bba-6f7e-4a2d-a2c4-ecaa3779ec20)
![image (10)](https://github.com/user-attachments/assets/c4726c35-f373-41fe-89bf-cb0215e2d312)

We will need to understand why its running out of storage since last 3 days suddenly.

**Comment by dims** [comment]
@hakuna-matatah in between the last good and first bad, we have the commits here - https://github.com/kubernetes/kops/compare/f19c837ed5...a4aaf897ca

we ended up going from 1.30.3 to 1.31/32 from the way the curl responds back to the version look up - https://github.com/kubernetes/kops/commit/29846697077df067b365c4e44240f31a18e12d41

one theory is that there's in a regression in there where the kube-proxy spews a LOT of logs which chews up the space on the test pod and causes the prow node kubelet to evict the test pod - https://github.com/kubernetes/kubernetes/pull/126519

evidence is the large 2+ GB files we see in the failed runs.

**Comment by hakuna-matatah** [comment]
>we ended up going from 1.30.3 to 1.31/32 from the way the curl responds back to the version look up 

Yup, we have decided to go from stable to latest last week so our CI will reflect the latest code changes like GCE. So, currently it is at 1.32.0-alpha last when I checked yesterday.


>one theory is that there's in a regression in there where the kube-proxy spews a LOT of logs which chews up the space on the test pod and causes the prow node kubelet to evict the test pod - https://github.com/kubernetes/kubernetes/pull/126519


Yup, i already made the [changes](https://github.com/kubernetes/kops/pull/16718/files) to test this theory, let's see 🤞 


>evidence is the large 2+ GB files we see in the failed runs.

I also think that we should also verify if we are pulling all the component logs from all nodes together locally onto `test-pod` to upload to `gcs/artifacts` , if so, we might run into this again with some other change in future, unless we fix logic to only pull them in batches so we don't ballon up the storage usage.

**Comment by hakuna-matatah** [comment]
>I also think that we should also verify if we are pulling all the component logs from all nodes together locally onto test-pod to upload to gcs/artifacts , if so, we might run into this again with some other change in future, unless we fix logic to only pull them in batches so we don't ballon up the storage usage.

Following up on my earlier [comment](https://github.com/kubernetes/test-infra/issues/33190#issuecomment-2266232463) . I think i may have figured it out.

It is executing tool box dump [here](https://github.com/kubernetes/kops/blob/master/tests/e2e/kubetest2-kops/deployer/dumplogs.go#L41-L46) which is basically after gathering logs  from all nodes from [here](https://github.com/kubernetes/kops/blob/master/cmd/kops/toolbox_dump.go#L234) , for each node, it looks like it is pulling the log files for all components of interest  [here](https://github.com/kubernetes/kops/blob/276d071e3c3888ea0ed2d3dcc8115d45c857bd07/pkg/dump/dumper.go#L354-L364) of a given node [here](https://github.com/kubernetes/kops/blob/276d071e3c3888ea0ed2d3dcc8115d45c857bd07/pkg/dump/dumper.go#L255) locally and create a file [here](https://github.com/kubernetes/kops/blob/276d071e3c3888ea0ed2d3dcc8115d45c857bd07/pkg/dump/dumper.go#L427-L443)


This is going to ballon up the storage space when these kind of [issues](https://github.com/kubernetes/kubernetes/pull/126519) occur even in future.

I see there is an option of using `max-nodes-to-dump` and we can limit to some smaller number let's say `5  nodes` to being with so that load tests are not sensitive to [issues](https://github.com/kubernetes/kubernetes/pull/126519) similar to these in future that may arise. wdyt ? @dims

**Comment by dims** [comment]
we are already setting `max-nodes-to-dump` to 10. +1 to make it configurable from test-infra yamls 

https://cs.k8s.io/?q=max-nodes-to-dump&i=nope&files=&excludeFiles=&repos=

**Comment by hakuna-matatah** [comment]
> we are already setting `max-nodes-to-dump` to 10. +1 to make it configurable from test-infra yamls 
> 
> 
> 
> https://cs.k8s.io/?q=max-nodes-to-dump&i=nope&files=&excludeFiles=&repos=


We only do that for GCE today not for AWS 😀 hence my earlier suggestion for AWS.

**Comment by dims** [comment]
Ah my bad. +1 to adopt for AWS too

**Comment by hakuna-matatah** [comment]
Looks like fix [here](https://github.com/kubernetes/kops/pull/16718) worked :D 
We got a green [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1819627967068770304)

**Comment by dims** [comment]
> Looks like fix https://github.com/kubernetes/kops/pull/16718 worked :D

very cool!

**Comment by dims** [comment]
other followups:

https://github.com/kubernetes/test-infra/pull/33214 ( Add a 500 node e2e-kops-aws-small-scale CI job )
https://github.com/kubernetes/kops/pull/16725 (add you / me as approver for the kops scalability script )
https://github.com/kubernetes/kubernetes/pull/126519 (reduce log verbosity - release blocker for v1.31)
