### ISSUE TITLE
Add --image to scenarios/kubernetes_e2e.py

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#3320]
We've added `--image-family` and `--image-project` to `scenarios/kubernetes_e2e.py` so that users can create jobs running against the latest OS image in a family. We'd like to support `--image` along with `--image-project`. This script can figure out what envs to use (`KUBE_GCE_NODE_IMAGE` or `KUBE_GKE_IMAGE_TYPE` or whatever) according to the cloud provider settings. And it would solve the confusion in https://github.com/kubernetes/test-infra/pull/3293#issuecomment-313245459.

/assign

**Comment by yguo0905** [comment]
@krzyzacy 

1. I see we have `--gcp-node-image` and `--gcp-master-image` defined in
https://github.com/kubernetes/test-infra/blob/177b5e1767bd079ced46ead81a8433a9a515cb6a/kubetest/main.go#L72 and https://github.com/kubernetes/test-infra/blob/177b5e1767bd079ced46ead81a8433a9a515cb6a/kubetest/main.go#L72
They set the `KUBE_NODE_OS_DISTRIBUTION` and `KUBE_MASTER_OS_DISTRIBUTION` env vars, which specifies the image **type** (e.g., `cos` and `ubuntu`). So we should rename them as `--gcp-node-image-type` and `--gcp-master-image-type`.

2. The actual image and the image project are set in scenario `kubernetes_e2e.py`
https://github.com/kubernetes/test-infra/blob/912411a296a0876ae539b04e4b1ad99f5d530d64/scenarios/kubernetes_e2e.py#L272-L273
Looks to me that we should pass them to `kubetest` via new flags `--gcp-node-image-name` and `--gcp-node-image-project` and let `kubetest` set the environment variables.

WDYT?

I see there're some moving parts like https://github.com/kubernetes/test-infra/blob/177b5e1767bd079ced46ead81a8433a9a515cb6a/kubetest/main.go#L607, so I'd like to what's the best practice for passing flags/envs for now.

**Comment by krzyzacy** [comment]
sure, or we should migrate those envs to e2e context flags?

**Comment by yguo0905** [comment]
What are the e2e context flags?

**Comment by krzyzacy** [comment]
(wrong account :-( ) nvm - they are not part of e2e and used in cluster config

`migrateGcpEnvAndOptions` is a temporary function for people are still using legacy global envs, feel free to refactor `KUBE_NODE_OS_DISTRIBUTION ` and `KUBE_MASTER_OS_DISTRIBUTION` to become better
