### ISSUE TITLE
open source testgrid updater, written in golang

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3323]

**Comment by spiffxp** [comment]
/unassign @Q-Lee 
/assign @michelle192837 
per sig-testing v1.9 roadmap

**Comment by spiffxp** [comment]
/milestone 1.12
Is this in use today? I see https://github.com/kubernetes/test-infra/blob/master/testgrid/cluster/updater_deployment.yaml

**Comment by michelle192837** [comment]
That is in progress still; tracking the overall work in #3324, but if that hits a roadblock will look at separating that out for use with the existing updater.

**Comment by spiffxp** [comment]
/milestone 2019-goals

It sure would be nice if we could do this in v1.14, but I'm going to defer to @michelle192837 to add back in to v1.14 milestone

**Comment by michelle192837** [comment]
Let's have this in the v1.17 milestone?

**Comment by fejta** [comment]
https://github.com/GoogleCloudPlatform/testgrid
/close
