### ISSUE TITLE
open source testgrid dashboard, written in golang

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3324]

**Comment by BenTheElder** [comment]
AFAIK this is still ongoing
/remove-lifecycle stale

**Comment by michelle192837** [comment]
This is still in progress; I'm actively working on it, and will update when the code is in a state to be open sourced (though it will need approval and validation after that before actually being publicly-viewable).

**Comment by michelle192837** [comment]
Not much to say, but progress has been made on this and it is still chugging along.

**Comment by rdrgmnzs** [comment]
Any more progress on this? Would love to have access to it for internal use.

**Comment by michelle192837** [comment]
Heya! Sorry about the lack of updates; this is slowly moving through bureaucracy internally, so I don't want to say much until I can say if it's approved for open sourcing officially. That said, while it's working its way through approvals I am still doing some other stuff to make sure it's ready for open sourcing to minimize approval -> release time.

Once approved, I'll update here, and there should be more publicly-visible progress I can give. ^^

**Comment by stevekuznetsov** [comment]
OK, sounds good! Just wanted to check if there was something easier than bugging you for updates :)

**Comment by michelle192837** [comment]
Nah, feel free to bug me for updates. ^^ But I'll try and make it so you don't have to as often.

**Comment by spiffxp** [comment]
/milestone 2019-goals

It sure would be nice if we could do this in v1.14, but I'm going to defer to @michelle192837 to add back in to v1.14 milestone

**Comment by spiffxp** [comment]
/milestone v1.16
/unassign @rmmh 
/assign @michelle192837 
to move to whichever milestone is most appropriate

**Comment by michelle192837** [comment]
Slating this for early next year.

/milestone v1.18
/milestone 2020-goals

**Comment by spiffxp** [comment]
/milestone 2020-goals
can only be in one milestone at a time, I made both of the ones you tried, but am using the less specific one for now

also I think we should use a different team for /milestone in this repo, or get you added to milestone-maintainers

**Comment by fejta** [comment]
https://github.com/GoogleCloudPlatform/testgrid/blob/master/standalone.md
