### ISSUE TITLE
hovering over testgrid cell displays test failure message

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3325]
@michelle192837 I assigned even though your name in our planning doc has question marks next to it, since you commented:
>This can be done via sponge property right now (categorized_fail), but I need to check if that actually works right now for external

Feel free to adjust/unassign as needed

**Comment by fejta** [comment]
Heh

**Comment by michelle192837** [comment]
Also adding Ryan who is prob. relevant to this.

**Comment by michelle192837** [comment]
/remove-lifecycle rotten

Not getting to this until later this year, but it's still a relevant feature.

**Comment by spiffxp** [comment]
/milestone 2019-goals
Taking a wild guess on timing here @michelle192837 please send to v1.13 if you think this release cycle is feasible

**Comment by michelle192837** [comment]
I am def. not going to have bandwidth for the rest of this year for this. :(

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
/close
I'm just going to close this, it's been over 3 years at this point
