### ISSUE TITLE
eliminate intermediary scripts underneath of kubetest

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3330]
eg: jenkins e2e-up, ginkgo-e2e.sh

**Comment by spiffxp** [comment]
not entirely the same thing, but ref: #3307 since it's attempting to remove at least some of the `cluster/gke/*.sh` goo

**Comment by zmerlynn** [comment]
Is anyone working on this? For the GKE work, I may need to add a flag to `kubetest` to bypass `ginkgo-e2e.sh` completely.

**Comment by spiffxp** [comment]
/assign @krzyzacy 
per v1.9 roadmap

**Comment by krzyzacy** [comment]
/remove-lifecycle rotten
we definitely still need this :-\

**Comment by chrislovecnm** [comment]
Just put in the same functionality for GCE - https://github.com/kubernetes/kubernetes/pull/61619

This allows for other installers that do not mimic kube-up and do not have to set env variables that kube-up.sh expects.

**Comment by spiffxp** [comment]
Honestly at this point it's unclear to me what the whole stack of python and shell is that's involved in running e2e tests.  I think the jenkins scripts are gone now, but kubetest still calls out to `hack/ginkgo-e2e.sh` for example.  Do we want to close this as too vaguely scoped?  Or is there a more concrete roadmap of simplification we could point to for definition of done?

**Comment by krzyzacy** [comment]
/remove-lifecycle stale

I think @justinsb was working on this and made some progress. Let's keep it.

**Comment by krzyzacy** [comment]
/assign @BenTheElder 

moving towards kubetest2 :-)

**Comment by BenTheElder** [comment]
moving to kubetest2 instead
