### ISSUE TITLE
Migrate all mungers out of mungegithub to prow plugins / periodic jobs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3331]
Umbrella issue.

Most of the mungers can be migrated to Prow plugins and respond to github webhook events but a few need to run periodically without having received an event. These should probably be implemented as kubernetes cron jobs.

---
EDIT: here's the munger list as of 2018-08-27

| munger | plan | status|
| --- | --- | --- |
| ~approval-handler~ | [prow/plugins/approve](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/approve) | done (#5115) |
| [assign-fixes](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/assign-fixes.go) | no replacement [3] | n/a |
| [block-path](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/block_paths.go) | [prow/plugins/blockade](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/blockade) | done  (#4944) |
| [blunderbuss](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/blunderbuss.go) | [prow/plugins/blunderbuss](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/blunderbuss) | done (#5547) |
| [check-labels](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/check-labels.go) | [label_sync](https://github.com/kubernetes/test-infra/tree/master/label_sync) | [done](https://github.com/kubernetes/test-infra/tree/master/label_sync) |
| ~bulk-lgtm~ | remove | done (#4101) |
| [cherrypick-auto-approve](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/cherrypick-auto-approve.go) | [1] |  |
| [cherrypick-clear-after-merge](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/cherrypick-clear-after-merge.go) | [1] |  |
| [cherrypick-must-have-milestone](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/cherrypick-must-have-milestone.go) | [1] |  |
| [cherrypick-queue](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/cherrypick-queue.go) | [1] |  |
| ~close-stale~ | [prow/plugins/lifecycle](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/lifecycle) + cron job | done (#5707) |
| [comment-deleter](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/comment-deleter.go) | no replacement [2] | n/a |
| [docs-need-no-retest](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/docs-no-retest.go) | [prow/plugins/docs-no-retest](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/docs-no-retest) | done (#4895) |
| ~flaky-job-reporter~ | [robots/issue-creator](https://github.com/kubernetes/test-infra/tree/master/robots/issue-creator) | done (#3970, #4450) |
| [inactive-review-handler](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/inactive-review-handler.go) | no replacement [3] | n/a |
| ~issue-creator~ | [robots/issue-creator](https://github.com/kubernetes/test-infra/tree/master/robots/issue-creator) | done (#3970, #4450) |
| [issue-triager](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/issue-categorizer.go) | no replacement [3] | n/a |
| [label-unapproved-picks](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/cherrypick-label-unapproved.go) | prow plugin | done (https://github.com/kubernetes/test-infra/pull/9128) |
| [lgtm-after-commit](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/lgtm_after_commit.go) | external prow plugin | done (https://github.com/kubernetes/test-infra/pull/6886) |
| [milestone-maintainer](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/milestone-maintainer.go) | prow plugin | in-progress (https://github.com/kubernetes/test-infra/pull/9158) |
| [needs-rebase](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/needs_rebase.go) | external plugin | done (#6022) |
| [nag-flake-issues](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/nag-flake-issues.go) | no replacement [3] | n/a |
| [old-test-getter](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/old-test-getter.go) | no replacement [3] | n/a |
| [owner-label](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/owner-label.go) | prow plugin | done (#6033) |
| [path-label](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/path_label.go) | prow plugin | done (#6033) |
| ~publisher~ | [kubernetes/publishing-bot](https://github.com/kubernetes/publishing-bot) | done |
| ~release-note-label~ | [prow/plugins/releasenotes](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/releasenote) | done (#4718) |
| [sig-mention-handler](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/sig-mention-handler.go) | [prow/plugins/requiresig](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/requiresig) |  done (#5662) |
| ~size~ | prow plugin | done (#3794, #4157) |
| [stale-green-ci](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/stale-green-ci.go) | no replacement [4] |  n/a |
| [stale-pending-ci](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/stale-pending-ci.go) | no replacement [3] | n/a |
| [submit-queue](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/submit-queue.go) | [prow/cmd/tide](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/tide) | in-progress (#3866) |
| ~triage-filer~ | robots/issue-creator | done (#3970, #4450) |

[1] - The cherrypick process on github should be rethought and simplified if possible.
[2] - The `comment-deleter` is no longer needed if plugins that create comments remove stale comments at that time.
[3] - The `assign-fixes`, `inactive-review-handler`, `issue-triager`, `old-test-getter`, `nag-flake-issues`, and `stale-pending-ci` are no longer in use so shouldn't be migrated unless they are needed.
[4] - The `stale-green-ci` munger could be reimplemented as a `commenter` job (eg: periodic-test-infra-retester) but we don't plan on adding this back unless it is sorely missed

**Comment by kargakis** [comment]
Is there an issue for migrating approvals into a prow plugin? Has anybody started working on that? I am interested in pursuing it next week.

**Comment by cjwagner** [comment]
I don't think there is an issue specific to that munger yet, just this issue. No one is working on migrating the approval-handler yet, so that would be great!

**Comment by spiffxp** [comment]
discussed during sig-testing today; some mungers can be moved out, some can't (or we'd like to obviate, eg: submit-queue for tide)

will update this issue with a full list

**Comment by stevekuznetsov** [comment]
We've got a migration of `docs-only-retest-not-required` incoming

**Comment by BenTheElder** [comment]
@spiffxp I think we can mark off the release note munger (?) :D

**Comment by cjwagner** [comment]
@BenTheElder Just deployed the changes :smile: I'll mark it.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/pull/5010 may end up being a suitable replacement for the existing cherry-pick mungers

**Comment by cjwagner** [comment]
The cherry-pick bot doesn't really replace the cherry-pick mungers because the mungers don't handle the creation of cherry-pick PRs.
However, the cherry-pick bot does replace the [hack/cherry_pick_pull.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh) script and will be much easier to use.

**Comment by spiffxp** [comment]
/assign @marun 
per sig-testing v1.9 roadmap

**Comment by spiffxp** [comment]
/remove-lifecycle stale
The above table has gone stale, I'll update it.  The submit queue still exists, so this isn't done yet

**Comment by nikhita** [comment]
@spiffxp The table needs an update for `label-unapproved-picks`. :)

Ref: https://github.com/kubernetes/test-infra/pull/9128

**Comment by spiffxp** [comment]
@nikhita done, and thanks again

**Comment by spiffxp** [comment]
/close
We have removed mungegithub https://github.com/kubernetes/test-infra/pull/9362
