### ISSUE TITLE
Grow prow to a second kubernetes provider, a second product

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3335]
@fejta I've assigned to you to provide some context, our planning doc didn't actually have an owner for this

I am under the impression that OpenShift is interested in this (viz @kargakis recent work), as well as istio (viz @nlandolfi and @sebastienvas commenting on some test-infra related issues).  I can speak for Samsung SDS being interested in this, though in v1.8 timeframe I'll likely be focusing more on repo management and automation, and less on job execution.

**Comment by fejta** [comment]
With OpenShift and Istio using prow I believe we can close this out
