### ISSUE TITLE
Migrate tooling off of gs://kubernetes-jenkins

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#33381]
Follow-up to the control plane migration (https://github.com/kubernetes/test-infra/issues/33350).

Tools like Kettle, TestGrid, and others read from gs://kubernetes-jenkins, but should switch to using the new bucket (gs://kubernetes-ci-logs) or something else if needed.

- [x] Ensure results from kubernetes-jenkins are synced to kubernetes-ci-logs (believe this is already done as part of the control plane migration?)
- [x] Migrate Kettle
- [x] Migrate TestGrid
- [x] Migrate other miscellaneous use
- [x] K8s Infra Prow writes to kubernetes-ci-logs instead of kubernetes-jenkins
- [x] Remove access permissions from kubernetes-jenkins
- [ ] Update references to kubernetes-jenkins across repos
  - [ ] kubernetes-sigs / prow
  - [ ] (any others?)
- [x] Ensure TTL for gs://kubernetes-jenkins
  - NOTE: Leave gs://kubernetes-jenkins (and its project) around to reserve the bucket name.

/assign
/sig testing

**Comment by michelle192837** [comment]
Kettle has had recent issues (see ?, ?)

Ref: https://github.com/kubernetes/test-infra/pull/33628

https://github.com/kubernetes/k8s.io/pull/7454 should hopefully fix this. (And I'll make the change in test-infra to match just in case, though it shouldn't change anything).

**Comment by BenTheElder** [comment]
I manually set a matching TTL on the new GCS bucket to match the old one (90d+ Age => delete)

We still need to set this in the terraform but I wanted to make sure we started aging out those old logs now as it's already like 200 TB.

**Comment by BenTheElder** [comment]
@upodroid plans to migrate the TTL to terraform (thanks!)

**Comment by michelle192837** [comment]
Existing lifecycle on gs://kubernetes-jenkins is also 90 days:

```
gcloud storage buckets describe gs://kubernetes-jenkins --format="default(lifecycle_config)"
lifecycle_config:
  rule:
  - action:
      type: Delete
    condition:
      age: 90
```

Migration happened August 21-ish, but log bucket migration happened later (largely early October) so things haven't hit TTL yet. We'll probably need to wait until ~January.

I don't have permissions to update gs://kubernetes-jenkins (just to view), so if we want to restrict permissions on it someone else will need to do it.

**Comment by BenTheElder** [comment]
> I don't have permissions to update gs://kubernetes-jenkins (just to view), so if we want to restrict permissions on it someone else will need to do it.

I don't either, following up internally.

From the OSS side, I think we can just let this TTL out, but it would be good to drop write permissions so we can be confident nobody will accidentally start using it again.

**Comment by BenTheElder** [comment]
/assign
working on dropping write permissions to gs://kubernetes-jenkins

we should also do the old scalability bucket alongside it

**Comment by BenTheElder** [comment]
I left read for now. For future reference kubernetes-engprod@ still contains @krzyzacy and Grant who have access as alternates if need be. Michelle doesn't have access. I do.

**Comment by BenTheElder** [comment]
I haven't spotted anything important in https://cs.k8s.io/?q=kubernetes-jenkins&i=nope&files=&excludeFiles=&repos=

**Comment by BenTheElder** [comment]
As needed, if it comes up, we can migrate, but a lot of these are historical.

**Comment by BenTheElder** [comment]
sig-scalability-logs was already empty, dropped IAM on that too
