### ISSUE TITLE
Redesign prow job configuration

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3338]
@spxtr going to leave it to you to flesh out what this means in a v1.8 scope

Things I've seen before:
- we'd like to invert from how-its-triggered/job to job/how-its-triggered https://github.com/kubernetes/test-infra/issues/2547
- ~~we know config.yaml is huge and could use yaml anchors to shorten it https://github.com/kubernetes/test-infra/pull/3272~~ Will not fix.
- we know config.yaml is huge and could use a tool to generate it https://github.com/kubernetes/test-infra/pull/3115
- we'd like to use PodPresets when they move out of alpha https://github.com/kubernetes/test-infra/issues/2383
- ~~we'd like to be able to configure plugins on a per-repo or per-org basis https://github.com/kubernetes/test-infra/issues/2546~~
- ~~we'd like more plugins than just trigger to use config.yaml (strictly speaking, this isn't job-related, and the groundwork for this is basically done with the addition of a triggers section https://github.com/kubernetes/test-infra/pull/2566)~~ Done, but in plugins.yaml.
- maybe something like jsonnet instead of yaml (can't find a reference off the top of my head)
- move job configurations to repos under test, like a prow equivalent ot `.travis.yaml` (https://github.com/kubernetes/test-infra/issues/3368)

**Comment by ixdy** [comment]
Limitations of the prow and bootstrap configuration are making it difficult to bazelify all of our jobs, since different branches (release-{1.6, 1.7, 1.8}, master) require different versions of bazel, and right now there's no way to use a different version of an image without copying all of the configs 3x (or 7x, if you include kubernetes-security).

This issue only discusses the prow configs, but we may also need to consider that `jobs/config.json` also needs specs for each named job.

**Comment by ixdy** [comment]
(and also testgrid)

**Comment by spiffxp** [comment]
every discussion I see of this talks about maintaining a consistent status quo to make it easier for us to one day do the refactor, that's why I bumped to 2018-goals... is there something we need to do in 1.9 timeframe to ease the bazel pain?

**Comment by BenTheElder** [comment]
@spiffxp we just forged ahead and forked the jobs with copy + paste and then I'm working to deprecate config.json as we move off of jenkins, the bazel jobs specify branch specific args in the podspec now. (https://github.com/kubernetes/test-infra/pull/4942 for the bootstrap tweak). This has worked OK so far.

**Comment by ixdy** [comment]
`config.yaml` is now so large that github doesn't expand diffs in PR reviews.

**Comment by ixdy** [comment]
If you try viewing the config on GitHub it bails after line 17375: https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml

**Comment by BenTheElder** [comment]
This is on our 2018 roadmap and @krzyzacy and I intend to come up with something. 

I want to explore what it would look like to have named first class objects for more things similar to how kubernetes handles its configuration. We'll definitely look into what we can do here soonish.

**Comment by spxtr** [comment]
Can we use podpresets yet? I thought those were supposed to have landed by now.

**Comment by BenTheElder** [comment]
> Can we use podpresets yet? I thought those were supposed to have landed by now.

Maybe, but even if they haven't we can implement something like this in Prow's config. I'd like to keep all of the state visible and reduce the number of files that need to be checked. I think we can probably move any number of highly redudnant sections to named / keyed objects.

**Comment by ixdy** [comment]
I just inadvertently broke pull-kubernetes-kubemark-e2e-gce, pull-kubernetes-e2e-kops-aws, and pull-kubernetes-e2e-gce-device-plugin-gpu in https://github.com/kubernetes/test-infra/pull/5990 because I'd assumed we were branching those jobs. We apparently aren't yet, and I'm not super excited about blowing up `config.yaml` even further.

**Comment by krzyzacy** [comment]
next step: split up prow/config.yaml

**Comment by krzyzacy** [comment]
next: invert trigger :-)

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

This needs a lot of thinking and I would love to see a series of breakout sessions or a meet-up for it this year :)

**Comment by spiffxp** [comment]
/lifecycle frozen
/milestone 2019-goals
because sure why not... 

Honestly, I'd like to understand what we concretely plan on doing, rather than perpetually holding open a "someday, we'll redesign this" issue.  You could say that about any of our code/config

The fact that we have split up jobs into N files across M directories seems like progress enough?  I know there are hopes and dreams of one day loading file(s) from the repo under test (a-la .travis.yaml) but we could just open that issue if/when we decide we want to head there?

**Comment by krzyzacy** [comment]
hopes and dreams and I think this is co-related with the trigger CRDs, once we have that we can just write configs as CRDs?

**Comment by krzyzacy** [comment]
/unassign

I'd say this not going to happen in the near future

**Comment by fejta** [comment]
/unassign
IMO we ought to close this for now. There isn't a clear direction we want to go yet so this isn't doing anything useful

**Comment by spiffxp** [comment]
/close
agreed
