### ISSUE TITLE
Dynamically load prow plugins (aka stop compiling into hook)

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3339]
ref: https://golang.org/pkg/plugin/

> Once multiple projects use prow we'll want a way for that project to customize their dev workflow without requiring us to ship a new version of prow.  It will also enable us to decouple prow the piece of infra from prow the way we use it on kubernetes.

As prior art, we're seeing other parts of kubernetes move to support out-of-tree plugins in an effort to keep in-tree development focused, while enabling third parties to add features at their own pace.

**Comment by fejta** [comment]
/assign @spxtr 
/unassign @cjwagner 

Joe does not want this to happen

**Comment by spxtr** [comment]
To be clear, I'm interested in a world where we can dynamically load plugins in a different sense: by making a service to implement the plugin. I don't like the idea of using go plugins though.

**Comment by kargakis** [comment]
> by making a service to implement the plugin

Sounds interesting. I've started working on a cherry-pick plugin that goes all the way until opening a PR and since it's really intrusive, I have opted on standing up a separate service for it but I am not sure how to integrate that with hook (likely will be its own thing initially).

**Comment by kargakis** [comment]
cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Do we expect `hook` to just look like a mux for GitHub webhook payloads at that point?

**Comment by kargakis** [comment]
I wouldn't expect every plugin to be its own service but allowing `hook` to act like a mux for cases where it makes sense, cases we don't want to bake stuff into `hook`, this sounds good to me.

**Comment by kargakis** [comment]
Can we brainstorm how this can be potentially achieved? Maybe, `hook` exposes a `/register` endpoint where plugin services send some kind of payload to to register themselves and once the registration is successful, `hook` starts [tee](https://en.wikipedia.org/wiki/Tee_(command))ing events?

**Comment by kargakis** [comment]
In a model where plugins need to register to `hook`, we will need a way to reregister them in case hook gets redeployed. Likely, a model where hook tries to figure out what plugin services exist is a better one.

**Comment by stevekuznetsov** [comment]
Are we going to constrain it to services it can reach in-cluster, or will we want to support any URL in general? We could just copy the configuration that GitHub itself uses to deliver webhooks -- inside of `hook`, configure a list of URLs+tokens to push to.

**Comment by kargakis** [comment]
> We could just copy the configuration that GitHub itself uses to deliver webhooks -- inside of hook, configure a list of URLs+tokens to push to.

I am sold. I will try to prototype this either today or tomorrow.

**Comment by spxtr** [comment]
We can store the remote plugins in a list in the config, and each plugin can have a service with the same name. Then, hook can just demux the webhook to each plugin service.
