### ISSUE TITLE
Integration testing and canary deployment of prow

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3340]
As potential prior art, there is talk of using spinnaker to make a deployment pipeline for mungegitub https://github.com/kubernetes/test-infra/issues/3200

We could consider leveraging helm charts to support this.

I believe we're currently auto-deploying config.yaml changes straight to prod assuming they validate by way of passing unit tests.  We may want to break that up a bit.

**Comment by fejta** [comment]
/unassign @spiffxp @spxtr 

Would definitely like to do this!

**Comment by kargakis** [comment]
I want to push this forward and shoot for delivering something in the 1.9 timeframe.

/assign

**Comment by kargakis** [comment]
/unassign

Need to wrap up metrics and alerts by the end of 17 ...
