### ISSUE TITLE
gcsweb images are not available in new container image repository

### ISSUE THREAD

**Issue by zimnx** [kubernetes/test-infra#33419]
**What happened**:

As recommended in Prow readme I used `us-docker.pkg.dev/k8s-infra-prow/images` repository for gcsweb. Contrary to other tools (ghproxy) gcsweb is not available in new location. 

**What you expected to happen**:

Use non-deprecated container image for all tooling around Prow. 

**How to reproduce it (as minimally and precisely as possible)**:

Browse:
https://console.cloud.google.com/artifacts/docker/k8s-infra-prow/us/images 
Notice missing `gcsweb`.

**Comment by BenTheElder** [comment]
GCSweb is not, strictly speaking, part of prow's images:

https://github.com/kubernetes/test-infra/tree/master/gcsweb

https://github.com/kubernetes-sigs/prow

**Comment by BenTheElder** [comment]
Also, FYI: https://github.com/kubernetes-sigs/prow/issues/113

**Comment by BenTheElder** [comment]
(staging registries are not meant to be consumed directly by third parties and this may break in the future, I recommend building your own and/or mirroring)
