### ISSUE TITLE
ci-kubernetes-e2e-kops-aws-release-1-7 is using the master branch images

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/test-infra#3343]
https://k8s-testgrid.appspot.com/release-1.7-blocking#aws-release-1-7&width=80

@krzyzacy @justinsb do you know if it's intentional?

cc @wojtek-t who will be the 1.7 patch release manager

**Comment by krzyzacy** [comment]
hummm seems I screwed it up
/assign
