### ISSUE TITLE
Expand metrics to include review round latency, review load distribution

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3345]

**Comment by fejta** [comment]
/unassign @cjwagner 

Should still do something about this...

**Comment by spiffxp** [comment]
@kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort  Is this something maybe better suited to being measured through http://devstats.k8s.io ?

**Comment by grodrigues3** [comment]
Yes devstats sounds like the right place for that.  And I think it makes an attempt and getting review load distribution.

Can you add your suggestion for review round latency to https://github.com/cncf/devstats as an issue?

I'll let you close this after you've moved the issue there.

**Comment by spiffxp** [comment]
@fejta @grodrigues3 can you two help me understand what "review round latency" is defined as in terms of github events?

**Comment by grodrigues3** [comment]
Strawman:

Time between commits and (first) non-author comment on a PR.

Does that work?

**Comment by kargakis** [comment]
> Time between commits and (first) non-author comment on a PR.

What if the PR is WIP for some time before the first review lands? We add a label for PRs marked as WIP (`do-not-merge/work-in-progress`), maybe we could also take that into account?

Also, we need to track whether requested reviewers are actually reviewing PRs.
