### ISSUE TITLE
Allow people outside of Google to be on test-infra rotation

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3349]
- What are the responsibilities of the test-infra rotation role
- What knowledge or experience is necessary to fulfill that role
- What capabilities or credentials are necessary to fulfill that role

**Comment by kargakis** [comment]
cc: @leifmadsen @stevekuznetsov

**Comment by madhusudancs** [comment]
cc @kubernetes/sig-federation-misc

**Comment by xiangpengzhao** [comment]
+1

**Comment by spiffxp** [comment]
/lifecycle frozen
The intent is to migrate from a google.com-owned GCP org to one that is owned by the CNCF.  At that point we are capable of adding people to support our infra, and we can iterate on what exactly "support" means and what requirements there are.

I've documented as best I can what test-infra we're running where on internal clusters.  Next step is to figure out a migration plan. https://github.com/kubernetes/test-infra/issues/5085

**Comment by BenTheElder** [comment]
/lifecycle frozen
this is pending on non-googlers having access to the infrastructure (pending the projects not being funded by being google.com org...), once we have something for that we can sort out the rotation details. until then they won't help much.

FWIW, I'm writing a doc with @amwat proposing how the infra-transition could work if funding etc. is sorted.

**Comment by spiffxp** [comment]
/lifecycle frozen
This is still relevant even if nothing's happening on it right now.  There are folks inside and outside Google making a push on the parts that come before this.  If it turns out there's a better repo to track this issue I'll move over there.  For now I'd rather this stay frozen.

**Comment by spiffxp** [comment]
(that was all me confirming that lifecycle labels get swapped out rather than stacked)

**Comment by spiffxp** [comment]
/wg k8s-infra
/milestone v1.16

Regardless of where prow.k8s.io lives, we need to be able to create and staff an on-call schedule in a way that can handle community members.  At present we use a google-internal tool to generate a rota based on fairness and people's calendars.

@rmmh attempted to rewrite the tool a while back, we could try picking that back up https://github.com/kubernetes/test-infra/pull/4688

We could have humans manually manage recurring events on a shared google calendar (this will be seen as toil)

Possible open source on-call things to examine:
- https://github.com/arachnys/cabot (last commit jan 30)
- https://github.com/openduty/openduty (last commit may 8)
- https://github.com/linkedin/oncall (last commit jun 18)

**Comment by cblecker** [comment]
The PST uses [Opsgenie](https://www.opsgenie.com/) via the CNCF for their rotation (another option).

We still also need the initial questions answered (what is on call responsible for, etc) and documented.

**Comment by BenTheElder** [comment]
Amongst other things, this is currently blocked by having enough headway on our GCP run rate to migrate the remaining infrastructure. I'm actively working in SIG K8s Infra on the cost reduction measure(s).

**Comment by dims** [comment]
Water under the bridge ! can we close this ?

**Comment by BenTheElder** [comment]
Yeah, let's close this, we're aiming to migrate the rest of prow to community infra by EOY and we'll revisit how best to handle staffing infra later.
