### ISSUE TITLE
Migrate to prow all jobs that do not require docker commands

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3356]
eg: kubemark uses a docker command

@krzyzacy I'm assuming this means migrate... from jenkins?  Also unclear if migrating to prow implies that there must be a scenario for it.  If not, maybe this is more a jenkins/prow-specific task than a scenarios-specific task?

**Comment by krzyzacy** [comment]
yeah, kops + soak + pr jobs left

**Comment by spiffxp** [comment]
aka kill jenkins, moving to v1.9

**Comment by krzyzacy** [comment]
/assign @BenTheElder 
definitely making progress here

**Comment by BenTheElder** [comment]
gce-gpu has been moved, federation just needs hyperkube / push-build sorted I think. there are definitely others.

**Comment by BenTheElder** [comment]
There should be more progress on making this default after the release is complete tomorrow hopefully :crossed_fingers:

**Comment by BenTheElder** [comment]
migrated etcd3 in https://github.com/kubernetes/test-infra/pull/5047

**Comment by BenTheElder** [comment]
@krzyzacy are there any left under this issues?

**Comment by krzyzacy** [comment]
yeah closing :-)
