### ISSUE TITLE
Decouple --build and --extract

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3357]
aka: e2e jobs --extract a --build job that finished a --stage to gcs, using prow's run_after_success pipelineing

Also cc'ing @david-mcmahon since you commented on the original planning doc item

**Comment by spiffxp** [comment]
This shows as finished in the v1.9 planning doc, I believe due to https://github.com/kubernetes/test-infra/pull/4105. Pinging @BenTheElder in case there's any more context I'm lacking here.

**Comment by BenTheElder** [comment]
Yes, this is pretty much done, we could do more to set up the repo with it though.
