### ISSUE TITLE
Refactor e2e env files to allow composition of (suite, provider/environment, account)

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3360]

**Comment by fejta** [comment]
Do we still want to do this?

**Comment by krzyzacy** [comment]
How useful is this? I think we can redesign when we overhaul prow configs. cc @BenTheElder (for job configs in the world of 2018 maybe)

**Comment by spiffxp** [comment]
/close
Given that we're taking a stab at removing .env files entirely via https://github.com/kubernetes/test-infra/issues/3362 I doubt this is useful.  We can always re-open if we change our minds.
