### ISSUE TITLE
Refactor suites to be specific to a SIG

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3361]

**Comment by fejta** [comment]
/unassign @krzyzacy 
/assign @rmmh 

Each sig now has a dashboard... Now need to refactor the jobs to only run the sig-specific jobs

**Comment by krzyzacy** [comment]
IMO that might not worth the resource - current schema with each sig use regex to filter out their own tests works out pretty well, do we really want to explode out num of jobs to be 10x?

**Comment by spiffxp** [comment]
Agree regexes seem to work alright.

SIG's need to see test cases failing that they don't own, for jobs they do own.  eg: sig-scalability needs to know if large clusters fail test cases owned by other sigs, sig-network needs to know if cluster configured with a feature they own fail the usual set of test cases, etc.

There are probably other issues open for this, but would rather see the gap closed on ownership of jobs (sigOwners: UNKNOWN) and tests (no [sig-foo] label on some e2e's, what about integration/unit tests, etc.)

**Comment by krzyzacy** [comment]
I don't think we want to do this anymore.
