### ISSUE TITLE
Request for a community owned GCP project for minikube

### ISSUE THREAD

**Issue by medyagh** [kubernetes/test-infra#33654]
Hello, minikube maintainer here, I would like to ask for a GCP project for minikube owned by the CNCF community, our release test infra is at a google owned project that we like to explore migrating it to CNCF-owned project, is this the right place to ask for it ?

**Comment by ameukam** [comment]
we don't provide dedicated projects for sub-projects. We instead provide build pools (through Kubetest2 + Boskos) where they can run their tests.

**Comment by BenTheElder** [comment]
[conversation is now at https://github.com/kubernetes/k8s.io/issues/7414]
