### ISSUE TITLE
Migrate job configuration out of test-infra, into repo under test

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3368]

**Comment by spxtr** [comment]
This is the idea to support the prow equivalent of `.travis.yml`, which lets us test presubmit config changes at the appropriate time.

**Comment by kargakis** [comment]
+1 on a `.prow.yml` file in the repo that is being tested.

**Comment by kargakis** [comment]
I guess such a file will have only presubmit/postsubmits for the repo. We still need a central config for periodics + all the infra configuration.

**Comment by alvaroaleman** [comment]
Prow now supports this: https://github.com/kubernetes/test-infra/blob/f421e19a48dc0578eaa937c7ce34927737caa40e/prow/inrepoconfig.md
