### ISSUE TITLE
Rewrite bootstrap in golang

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3370]
Just a small matter of running [py2go](https://github.com/jianyuan/py2go) and we can call this done, right? ;)

**Comment by spxtr** [comment]
Overlap with #3342 ?

**Comment by fejta** [comment]
They are orthogonal tasks

**Comment by fejta** [comment]
This is mostly to stimulate community participation of the checkout and upload logic.

**Comment by kargakis** [comment]
@stevekuznetsov @csrwng

**Comment by BenTheElder** [comment]
superceded by https://github.com/kubernetes/test-infra/issues/4871 which is tracking the rewrite and eventual switch :crossed_fingers: 
/close
