### ISSUE TITLE
can we move bootstrap.py out from jenkins/ into its own bootstrap/ dir?

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3371]
I don't have enough context with bootstrap to know how involved this would be (my guess is "very"), pinging @fejta and @krzyzacy since you've been most involved with changes in that area lately.

**Comment by krzyzacy** [comment]
yeah I think this would be a trivial change
/assign

**Comment by spiffxp** [comment]
/close
closing this in favor of #4871
