### ISSUE TITLE
Customized tests layout in testgrid

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#3374]
The Ubuntu image validation (https://k8s-testgrid.appspot.com/canonical-kubernetes) and the COS image validation (https://k8s-testgrid.appspot.com/cos-image-validation) include lots of tests since we'd like to test whether each image version works with each k8s version.

Given the large number of tests and the subtle differences in the test names, it's not easy to navigate to the test I want. It would be great if the tests can be shown as the following table.

|             | k8s-dev             | k8s-beta           | k8s-stable1 | k8s-stable2 | 
|-------------|---------------------|-------------------|------------|-----------|
| cos-dev     | default serial slow | default serial slow | default serial slow | n/a |
| cos-beta    | [default](https://k8s-testgrid.appspot.com/cos-image-validation#cosbeta-k8sdev-default) [serial](https://k8s-testgrid.appspot.com/cos-image-validation#cosbeta-k8sdev-serial) [slow](https://k8s-testgrid.appspot.com/cos-image-validation#cosbeta-k8sdev-slow) | default serial slow | default serial slow | n/a |
| cos-stable1 | default serial slow | default serial slow | default serial slow | default serial slow |
| cos-stable2 | n/a | default serial slow | default serial slow | default serial slow |

Is there a way to customized tests layout in testgrid?

More general, if we could have most of the test names standardized (https://github.com/kubernetes/test-infra/issues/2894), the testgrid would provide powerful ways (such as sorting and filtering fields, like cloud providers, images, k8s versions and test suites) to show and compare tests. For example, when I debug a serial test failure on Ubuntu image and k8s master, I'd like to quickly find the serial test that run on other images and/or a different k8s version, so that I can know if it's an image or k8s specific issue.

/cc @fejta @krzyzacy @abgworrall

**Comment by fejta** [comment]
/assign @michelle192837 
will you see if you can help Yang? Maybe tabgroups will help here?

**Comment by michelle192837** [comment]
I think DashboardGroups can help here somewhat, but the actual ask is more like 'I want to view this same test across multiple DashboardTabs', right?

I'm including this somewhat in some later improvements to the TestGrid summary, but I think the more powerful stuff requires some extra design + work. It is on the list for getting worked on at some point though since it's been requested before.

In the meanwhile, if it makes sense it might be possible to set up a tab with some combined test runs, which have labels differentiating which of the same test runs are run with which parameters (see test_name_config in the config for configuring the test name). If they're all on one tab, you can 'Group by Target' under 'Options' to get statuses of all the tests with different configurations.

**Comment by yguo0905** [comment]
@michelle192837, I think it's not about viewing the same test across mutliple tabs. Take https://k8s-testgrid.appspot.com/cos-image-validation for example. There are currently 33 tests, whose names are listed in **multiple lines** at the top of the page. What I'm suggesting is to reorganize the test name layout by putting the test names into the above **table**, so that we can easily find the test when we are on the `cos-image-validation` tab. And the same for the `canonical-kubernetes` tab.

The more general idea definitely needs a long term solution, which we could handle later.

**Comment by michelle192837** [comment]
Ah, I was referring to rows as tests and tests as tabs, so I think we're on the same-ish page. In that case, I think some possible options are:

- Wait for/Start building out the longer-term solution, which will allow for comparing more easily between the different tests/tabs

- Add [DashboardGroups](https://github.com/kubernetes/test-infra/blob/master/testgrid/config/config.yaml#L2961) and split these into more dashboards. For instance, say you make new dashboards by k8s channel (?), and group all those by cos image version (?), you could have groups/dashboards like so (with [] for the DashboardGroup names, and <> for the Dashboard names):

    <gce-cosdev>: [k8sdev] - default, slow, serial, [k8sbeta] - default, slow, serial, [k8sstable1] - default, slow, serial
    <gce-cosstable>: [k8sdev] - default, slow, serial, [k8sbeta] - default, slow, serial, [k8sstable1] - default, slow, serial
    ...
    etc.

- Combine the results of multiple tests/tabs into one test/tab, with labelling for which parameters are in effect (i.e. rows looking something like:

    [k8s.io] AppArmor load ... profile [gce-cosdev] [k8sdev-default]
    [k8s.io] AppArmor load ... profile [gce-cosdev] [k8sdev-slow]
    ...
    etc.

This will let you group rows with the same target, and include/exclude rows via filtering.

- Wait for a couple better [Summary](https://k8s-testgrid.appspot.com/cos-image-validation#Summary) options (like being able to filter down to just targets matching a given string), which will at least let you see the failures by configuration in an annoying way.

**Comment by krzyzacy** [comment]
ah missed this, dashboardgroup is definitely helpful for your case :-)

**Comment by yguo0905** [comment]
Sorry, got distracted by other things.

@michelle192837 and @krzyzacy, thanks for providing the solutions! I think dashboard_group is closer to what I need. As you suggested, I want to create the following dashboards `cosdev`, `cosbeta`, `cosstable1`, `cosstable2` and also `k8sdev`, `k8sbeta`, `k8sstable1`, `k8sstable2`. They are so many dashboards, so is there a way to only show the DashboardGroup at the top-level?

**Comment by fejta** [comment]
Yes, we plan on adding this feature during 1.8

**Comment by yguo0905** [comment]
Cool!

**Comment by yguo0905** [comment]
@michelle192837, @krzyzacy, @fejta, do we have an issue tracking the feature mentioned in https://github.com/kubernetes/test-infra/issues/3374#issuecomment-315486405?

**Comment by michelle192837** [comment]
Should be issue #3126.

**Comment by spiffxp** [comment]
The aformentioned issue has been deployed and closed.  We now have https://k8s-testgrid.appspot.com/sig-node-cos-image which is grouped under sig-node on https://k8s-testgrid.appspot.com/

@yguo0905 does this meet your needs, or are you thinking you'd like to keep this open until you've created a different dashboard scheme to take advantage of this?

**Comment by yguo0905** [comment]
It seems that multiple-level of groups is not supported, but I can make the sig-node-cos-image as a top level one and create subgroups under it, just like https://k8s-testgrid.appspot.com/canonical. Thanks!
