### ISSUE TITLE
Convert magic kubetest env to flags

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3375]
/area kubetest
/assign

Review whether we can do anything better with all the following:
- [ ] `NUM_NODES`
- [ ] `KUBEMARK_NUM_NODES`
- [ ] `KUBEMARK_MASTER_SIZE`
- [ ] `MASTER_SIZE`
- [x] `KUBEMARK_TEST_ARGS`
- [x] `PROJECT`
- [x] `ZONE`
- [x] `KUBERNETES_RELEASE_URL` (fine, set by kubetest)
- [ ] `KOPS_STATE_STORE`
- [ ] `AWS_SSH_KEY`
- [x] `CLOUDSDK_BUCKET`
- [ ] `GOOGLE_APPLICATION_CREDENTIALS`
- [x] `KUBERNETES_PROVIDER`
- [ ] `PRIORITY_PATH`
- [ ] `EXECUTOR_NUMBER`
- [ ] `NODE_NAME`
- [ ] `FEDERATION`
- [ ] `GOPATH`
- [ ] `HOME`
- [ ] `PATH`

```
kubetest/e2e.go:	cmdline := fmt.Sprintf("%s/src/k8s.io/perf-tests/clusterloader/run-e2e.sh", os.Getenv("GOPATH"))
kubetest/e2e.go:	if popN, err := pushEnv("NUM_NODES", os.Getenv("KUBEMARK_NUM_NODES")); err != nil {
kubetest/e2e.go:	if popM, err := pushEnv("MASTER_SIZE", os.Getenv("KUBEMARK_MASTER_SIZE")); err != nil {
kubetest/e2e.go:	test_args := os.Getenv("KUBEMARK_TEST_ARGS")
kubetest/extract.go:		p := os.Getenv("PROJECT")
kubetest/extract.go:		z := os.Getenv("ZONE")
kubetest/extract.go:	url := os.Getenv("KUBERNETES_RELEASE_URL")
kubetest/extract.go:	version := os.Getenv("KUBERNETES_RELEASE")
kubetest/kops.go:	kopsState       = flag.String("kops-state", os.Getenv("KOPS_STATE_STORE"), "(kops only) s3:// path to kops state store. Must be set. (This flag defaults to $KOPS_STATE_STORE, and overrides it if set.)")
kubetest/kops.go:	kopsSSHKey      = flag.String("kops-ssh-key", os.Getenv("AWS_SSH_KEY"), "(kops only) Path to ssh key-pair for each node. (Defaults to $AWS_SSH_KEY or '~/.ssh/kube_aws_rsa'.)")
kubetest/main.go:	p := os.Getenv("PROJECT")
kubetest/main.go:	if b := os.Getenv("CLOUDSDK_BUCKET"); b != "" {
kubetest/main.go:		defer os.Setenv(ccmsu, os.Getenv(ccmsu))
kubetest/main.go:	if k := os.Getenv("GOOGLE_APPLICATION_CREDENTIALS"); k != "" {
kubetest/main.go:	kp := os.Getenv("KUBERNETES_PROVIDER")
kubetest/main.go:	if p := os.Getenv("PRIORITY_PATH"); p != "" {
kubetest/main.go:		execNum := os.Getenv("EXECUTOR_NUMBER")
kubetest/main.go:		suffix := fmt.Sprintf("%s-%s", os.Getenv("NODE_NAME"), execNum)
kubetest/stage.go:	if os.Getenv("FEDERATION") == "true" {
kubetest/util.go:	p := []string{os.Getenv("GOPATH"), "src", "k8s.io"}
kubetest/util.go:	p := []string{os.Getenv("HOME")}
kubetest/util.go:	return os.Setenv("PATH", fmt.Sprintf("%v:%v", path, os.Getenv("PATH")))
```

**Comment by krzyzacy** [comment]
cc @shyamjvs 

So we need to make sure the wiped env is not used in k/k in future PRs :-)

**Comment by shyamjvs** [comment]
Yes, that's definitely needed.

**Comment by fejta** [comment]
ADDITIONAL_ZONES
ALLOWED_NOTREADY_NODES
APISERVER_TEST_ARGS
AWS_CONFIG_FILE
AWS_SHARED_CREDENTIALS_FILE
CLOUDSDK_API_ENDPOINT_OVERRIDES_CONTAINER
CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK
CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS
CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE
CLOUDSDK_CORE_PRINT_UNHANDLED_TRACEBACKS
CLUSTER_IP_RANGE
CMD_GROUP
CONTROLLER_MANAGER_TEST_ARGS
DOCKER_TEST_LOG_LEVEL
E2E_ZONES
ENABLE_BIG_CLUSTER_SUBNETS
ENABLE_CACHE_MUTATION_DETECTOR
ENABLE_CUSTOM_METRICS
ENABLE_GARBAGE_COLLECTOR
ENABLE_HOLLOW_NODE_LOGS
ENABLE_LEGACY_ABAC
ETCD_IMAGE
ETCD_VERSION
EVENT_PD
FEDERATION
FEDERATION_CLUSTERS
FEDERATION_DNS_ZONE_NAME
FEDERATION_HOST_CLUSTER_ZONE
FEDERATION_PUSH_REPO_BASE
GCLOUD
GINKGO_PARALLEL
GINKGO_PARALLEL_NODES
GINKGO_TEST_ARGS
GINKGO_TOLERATE_FLAKES
GKE_CREATE_FLAGS
HAIRPIN_MODE
HEAPSTER_MACHINE_TYPE
JENKINS_ENABLE_DOCKER_IN_DOCKER
JENKINS_GCI_HEAD_IMAGE_FAMILY
JENKINS_GCI_PATCH_K8S
JENKINS_PUBLISHED_VERSION
KOPS_DEPLOY_LATEST_KUBE
KOPS_DEPLOY_LATEST_URL
KOPS_E2E_CLUSTER_NAME
KOPS_LATEST
KOPS_PUBLISH_GREEN_PATH
KOPS_RUN_OBSOLETE_VERSION
KUBE_ADMISSION_CONTROL
KUBE_AUTOSCALER_ENABLE_SCALE_DOWN
KUBE_AUTOSCALER_MAX_NODES
KUBE_AUTOSCALER_MIN_NODES
KUBE_AWS_ZONE
KUBE_ENABLE_CLUSTER_AUTOSCALER
KUBE_ENABLE_CLUSTER_MONITORING
KUBE_FASTBUILD
KUBE_FEATURE_GATES
KUBE_GCE_ENABLE_IP_ALIASES
KUBE_GCE_NODE_IMAGE
KUBE_GCE_NODE_PROJECT
KUBE_GCI_VERSION
KUBE_GCS_UPDATE_LATEST
KUBE_GKE_ENABLE_KUBERNETES_ALPHA
KUBE_GKE_IMAGE_TYPE
KUBELET_TEST_LOG_LEVEL
KUBE_LOGGING_DESTINATION
KUBEMARK_MASTER_COMPONENTS_QPS_LIMITS
KUBEMARK_MASTER_ROOT_DISK_SIZE
KUBEMARK_MASTER_SIZE
KUBEMARK_NUM_NODES
KUBE_NODE_OS_DISTRIBUTION
KUBE_OS_DISTRIBUTION
KUBEPROXY_TEST_LOG_LEVEL
KUBE_REGISTRY
KUBE_SSH_USER
LOAD_TEST_THROUGHPUT
MACHINE_TYPE
MASTER_DISK_SIZE
MASTER_SIZE
MAX_INSTANCES_PER_MIG
MULTIZONE
NODE_ACCELERATORS
NODE_DISK_SIZE
NODE_SIZE
NUM_NODES
PREPULL_E2E_IMAGES
REGISTER_MASTER
SCHEDULER_TEST_ARGS
STACKDRIVER_API_ENDPOINT_OVERRIDE
STORAGE_BACKEND
STORAGE_MEDIA_TYPE
TEST_CLUSTER_DELETE_COLLECTION_WORKERS
TEST_CLUSTER_LOG_LEVEL
TEST_CLUSTER_MAX_REQUESTS_INFLIGHT
TEST_CLUSTER_RESYNC_PERIOD
TEST_ETCD_IMAGE
TEST_ETCD_VERSION
USE_KUBEFED
USE_REAL_PROXIER
