### ISSUE TITLE
Failing job post-kubetest2-push-binaries

### ISSUE THREAD

**Issue by elieser1101** [kubernetes/test-infra#33802]
**What happened**:
The `post-kubetest2-push-binaries` Job is failing

**What you expected to happen**:
Job succeeds

**How to reproduce it (as minimally and precisely as possible)**:
After merging stuff into kubetest2 we got the failing job

**Please provide links to example occurrences, if any**:
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/post-kubetest2-push-binaries
https://testgrid.k8s.io/sig-testing-kubetest2#post-kubetest2-push-binaries

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/33803#issuecomment-2482172671

**Comment by elieser1101** [comment]
Fixed by https://github.com/kubernetes-sigs/kubetest2/pull/284
