### ISSUE TITLE
Failing job ci-kubetest2-push-binaries

### ISSUE THREAD

**Issue by elieser1101** [kubernetes/test-infra#33803]
**What happened**:
The `ci-kubetest2-push-binaries` job is failing

**What you expected to happen**:
Job to succeed

**How to reproduce it (as minimally and precisely as possible)**:
Its a periodic job

**Please provide links to example occurrences, if any**:
https://testgrid.k8s.io/sig-testing-kubetest2#ci-kubetest2-push-binaries

**Comment by BenTheElder** [comment]
This is not a great place to file this sort of issue, it would be better to file it against the kubetest2 repo where the maintainers for that repo are watching

**Comment by aojea** [comment]
it seems the jobs times out in cloudbuild

> Your build timed out. Use the [--timeout=DURATION] flag to change the timeout threshold.

**Comment by aojea** [comment]
The cloudbuild seems to be here https://github.com/kubernetes-sigs/kubetest2/blob/master/hack/ci/push-binaries/cloudbuild.yaml

does it take more than 1 hour to build the binaries? @upodroid is a cloudbuild machine problem or a timeout problem?

**Comment by elieser1101** [comment]
Fixed by https://github.com/kubernetes-sigs/kubetest2/pull/284
