### ISSUE TITLE
Upgrade: 'dict object' has no attribute 'v1.30'

### ISSUE THREAD

**Issue by HolyDeusMe** [kubernetes/test-infra#33923]
Hello!
Im trying update my cluster from 1.29.10 to 1.30.5 and when to 1.31.4

I have some problem, please help me solve it:
`{{ etcd_supported_versions[kube_major_version] }}: 'dict object' has no attribute 'v1.30'. 'dict object' has no attribute 'v1.30'. {{ etcd_supported_versions[kube_major_version] }}: 'dict object' has no attribute 'v1.30'. 'dict object' has no attribute 'v1.30'\n\nThe error appears to be in '/root/kubespray/roles/download/tasks/prep_kubeadm_images.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Prep_kubeadm_images | Check kubeadm version matches kubernetes version\n  ^ here\n"`

git status
On branch release-2.25
I upload full error on file, where can be a problem?
[TASK [download  Prep_kubeadm_images.txt](https://github.com/user-attachments/files/18079278/TASK.download.Prep_kubeadm_images.txt)

**Comment by neolit123** [comment]
> '/root/kubespray/

try asking on the support channels or contact the kubespray maintainers.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
