### ISSUE TITLE
testgrid should show the new build SHA in upgrade test

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/test-infra#3392]
e.g., https://k8s-testgrid.appspot.com/1.6-1.7-upgrade

The UI shows the SHA of the old image. It's more useful if the UI instead shows the SHA of the image the cluster is upgraded to, because that's what the release team cares about.

cc @krzyzacy @ixdy

**Comment by ixdy** [comment]
FWIW Gubernator used to show both versions in the metadata at the top, but in some of the job config and test-infra refactoring, it seems like this functionality was lost.

**Comment by fejta** [comment]
Update this method to include both versions in the metadata.json, which will result in it getting exposed to both gubernator and testgrid
https://github.com/kubernetes/test-infra/blob/master/kubetest/main.go#L345

**Comment by spiffxp** [comment]
/area kubetest
per the above comment

**Comment by spiffxp** [comment]
@fejta which method, `writeMetadata()`?

**Comment by spiffxp** [comment]
/remove-lifecycle stale
this remains a pain point for consumers of testgrid during release

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/assign
I wrote a doc about figuring upgrade versions, it would be way nicer to make that doc smaller and say "just look at gubernator"

**Comment by ixdy** [comment]
/pony sad

someday someone will work on this.

**Comment by justaugustus** [comment]
/reopen
/priority important-soon
/area release-eng

@kubernetes/release-engineering -- Anyone interested in working on this?

**Comment by cpanato** [comment]
@justaugustus i can try this one if i get some initial guide, like where to start :)

**Comment by justaugustus** [comment]
Thanks Carlos! I personally just found this issue.

@spiffxp @fejta -- Can you provide some details on current state of affairs and what Carlos would need to work on this?

/assign @cpanato

**Comment by spiffxp** [comment]
This was primarily in reference to all of the jobs that now live here: https://testgrid.k8s.io/sig-release-orphaned

They are run via kubetest: https://github.com/kubernetes/test-infra/tree/master/kubetest#upgrade-skew-kubemark

Testgrid columns are defined in testgrid config.yaml like so: https://github.com/kubernetes/test-infra/blob/master/testgrid/config.md#column-headers

So the questions I can't answer off the top of my head and leave to you are:
- how can you identify the versions being upgraded (is it version files, is it api calls)
- where can you do this (is it a change in kubetest, is it a change in something kubetest kicks off)
- where can you store this data such that it ends up in the `metadata` section of `finished.json` (this one could probably use a docs PR when you find the answer)

**Comment by cpanato** [comment]
@spiffxp Thanks Aaron, since I'm quite new to the codebase I will ping you at slack to talk more, of course, if you agree on that :)

**Comment by BenTheElder** [comment]
until the rest is agreed there's nothing to do in kubetest, this metadata can just as easily come from the (rather broken) upgrade system.

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
/assign @BenTheElder 
putting this on your radar

**Comment by cpanato** [comment]
this is something we still want to do?
@BenTheElder @spiffxp

**Comment by BenTheElder** [comment]
IMHO both versions are under test and I think it's debateable which is primary.
I think both versions should be inspected if we're looking at either of them.
@amwat is mostly maintaining kubetest now, in bug-fix mode while we roll out kubetest2.

**Comment by spiffxp** [comment]
I don't have bandwidth for this, if nobody else does I guess we can let it age out.

This sort of thing remains something the release-team has the power to change if they want, see https://github.com/kubernetes/test-infra/blob/master/testgrid/config.md#column-headers for how to specify what data should appear in what column

It just requires the time to figure out how to get the versions you want, and to make sure they end up in metadata.json (or finished.json's metadata object)

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/test-infra/issues/20650 for another testgrid columne hygiene thing I think the community could help with
