### ISSUE TITLE
gsutil Incompatible Python version with gsutil in latest gcb-docker-gcloud image 

### ISSUE THREAD

**Issue by Prajyot-Parab** [kubernetes/test-infra#33921]
**What happened**:
gsutil cli execution failing with incompatible python version error within gcb-docker-gcloud image

```
# docker run -it gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241111-71c32dbdcc
72a1c197f016:/workspace# go version
go version go1.22.9 linux/amd64
72a1c197f016:/workspace# python --version
Python 3.12.7
72a1c197f016:/workspace# gsutil 
Error: gsutil requires Python version 2.7 or 3.5-3.11, but a different version is installed.
You are currently running Python 3.12
Follow the steps below to resolve this issue:
        1. Switch to Python 3.5-3.11 using your Python version manager or install an appropriate version.
        2. If you are unsure how to manage Python versions, visit [https://cloud.google.com/storage/docs/gsutil_install#specifications] for detailed instructions.
```

**What you expected to happen**:
gsutil cli execution to work smoothly.

**How to reproduce it (as minimally and precisely as possible)**:
```
# docker run -it gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241111-71c32dbdcc
xxxxxxx:/workspace# gsutil 
```

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

**Comment by BenTheElder** [comment]
Kubernetes isn't using this in a lot of places, where we are I don't think we're using gsutil vs just needing to push to GCR.

The sources are in https://github.com/kubernetes/test-infra/tree/master/images/gcb-docker-gcloud

What're you using this image for?

**Comment by mkumatag** [comment]
This image and gsutil is used in the capi projects, e.g: [cluster-api](https://github.com/kubernetes-sigs/cluster-api/blob/92e16dbdaead4dd3e1f9ebec2c0d395733d63d5f/Makefile#L1161), [cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/95b1622a8fb751b6d5b3ecbf8bc79fafc7c22eba/Makefile#L632), [cluster-api-provider-ibmcloud](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/64326020aa6ebac98f9f8a7918eb02ef425d843d/Makefile#L333) and mostly for pushing the artifacts to gcs bucket

**Comment by mkumatag** [comment]
> @mkumatag want to take a stab at fixing this?

lemme take a look at it.

**Comment by mkumatag** [comment]
Same issue is been discussed here in the gsutil project - https://github.com/GoogleCloudPlatform/gsutil/issues/1808

Tried rebuilding the image and fixed the issue(always installs the latest version Google Cloud SDK)

latest build:
```
25a98dc4712d:/workspace# gcloud --version
Google Cloud SDK 503.0.0
alpha 2024.12.06
beta 2024.12.06
bundled-python3-unix 3.11.9
core 2024.12.06
gke-gcloud-auth-plugin 0.5.9
gsutil 5.32
25a98dc4712d:/workspace# gsutil --version
gsutil version: 5.32
25a98dc4712d:/workspace# python -V
Python 3.12.8
25a98dc4712d:/workspace#
```


problematic build
```
root@mkumatag-exp:~/test-infra/images/gcb-docker-gcloud# docker run --entrypoint sh -ti gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241111-71c32dbdcc
/workspace # gcloud --version
Google Cloud SDK 500.0.0
alpha 2024.11.01
beta 2024.11.01
bundled-python3-unix 3.11.9
core 2024.11.01
gke-gcloud-auth-plugin 0.5.9
gsutil 5.31


To take a quick anonymous survey, run:
  $ gcloud survey

/workspace # gsutil --version
Error: gsutil requires Python version 2.7 or 3.5-3.11, but a different version is installed.
You are currently running Python 3.12
Follow the steps below to resolve this issue:
	1. Switch to Python 3.5-3.11 using your Python version manager or install an appropriate version.
	2. If you are unsure how to manage Python versions, visit [https://cloud.google.com/storage/docs/gsutil_install#specifications] for detailed instructions.
/workspace # python -V
Python 3.12.7
/workspace #
```

so just a image rebuild should solve this problem.

**Comment by BenTheElder** [comment]
Did we confirm this is working with the image from https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-test-infra-push-gcb-docker-gcloud/1868909720799023104 ?

**Comment by mkumatag** [comment]
> Did we confirm this is working with the image from https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-test-infra-push-gcb-docker-gcloud/1868909720799023104 ?

I can confirm this is working fine

```
root@mkumatag-exp:/home/cloudusr# docker run --entrypoint sh -ti gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241217-ff46a068cd
/workspace # python -V
Python 3.12.8
/workspace # gcloud --version
Google Cloud SDK 503.0.0
alpha 2024.12.06
beta 2024.12.06
bundled-python3-unix 3.11.9
core 2024.12.06
gke-gcloud-auth-plugin 0.5.9
gsutil 5.32
/workspace # gsutil --version
gsutil version: 5.32
/workspace #
```

**Comment by BenTheElder** [comment]
thank you!
