### ISSUE TITLE
Approved and lgtm'd PR should retest again automatically if tests failed due to flake

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3395]
https://github.com/kubernetes/kubernetes/pull/48410 is approved and lgtm'd. It ran `/test all [submit-queue is verifying that this PR is safe to merge]` to test all before merging but one of the tests failed due to flake. (pull-kubernetes-kubemark-e2e-gce). Then it hangs until I retest it.

It should be able to retest itself automatically in this case. Immediate retesting might not be neccesary. It can be triggered some hours later, e.g. 12 hours?

**Comment by kargakis** [comment]
If we are 100% sure it's a flake, it is fine to retrigger on the spot. Otherwise, I am not sure.

**Comment by xiangpengzhao** [comment]
Agreed. But it's hard for our lovely bots to be sure about that...

**Comment by spxtr** [comment]
@apelisse had this idea too. The idea is that if just one or two suites fail on a PR we should rerun them right away, once. Unfortunately, it's pretty tricky to do this properly.

**Comment by kargakis** [comment]
> Agreed. But it's hard for our lovely bots to be sure about that...

For example, doc changes that fail a test, eg. https://github.com/kubernetes/kubernetes/pull/48592
[We already know it's a doc change](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/docs-no-retest.go) :)

**Comment by xiangpengzhao** [comment]
:+1: good example!

**Comment by xiangpengzhao** [comment]
>@apelisse had this idea too. The idea is that if just one or two suites fail on a PR we should rerun them right away, once. Unfortunately, it's pretty tricky to do this properly.

Is there any way for the bots to know whether tests fail due to a know flake?

**Comment by xiangpengzhao** [comment]
>We already know it's a doc change

Since you mentioned doc change, I have another concern : do we need to run(not rerun) all tests for docs-only PRs? I assume some tests have nothing to do with these docs at all.

**Comment by spxtr** [comment]
> Is there any way for the bots to know whether tests fail due to a know flake?

Not really, no.

**Comment by apelisse** [comment]
> Is there any way for the bots to know whether tests fail due to a know flake?

One good way to know that it's not a flake, is to run the tests again :-)

> Unfortunately, it's pretty tricky to do this properly.

Why is it? I remember that we said "it's going to waste a lot of resources". To be honest, we do waste the resource anyway because I'd bet that 99% of the people will just say `/retest`.
if we can limit the number of time we re-run the tests, maybe re-run when the test-infra is more quiet/less overwhelmed and only when specific criteria are met (only approved/lgtm), then it might be good enough resource-wise?

**Comment by xiangpengzhao** [comment]
>To be honest, we do waste the resource anyway because I'd bet that 99% of the people will just say /retest.

60% agree:) Some of the people (40%? haha) might view the failure details to find out whether the flake is caused by their code.

>if we can limit the number of time we re-run the tests, maybe re-run when the test-infra is more quiet/less overwhelmed and only when specific criteria are met (only approved/lgtm), then it might be good enough resource-wise?

Maybe we can re-run the tests automatically for three times at most for the approved and lgtm'd PRs (i.e. which are ready to merge) only. If they still fail, bots can believe they are not just flake.

**Comment by xiangpengzhao** [comment]
This will be fixed by #3764. 

Thanks @fejta !

**Comment by xiangpengzhao** [comment]
#3764 already merged.
/close
