### ISSUE TITLE
Graceful shutdown for hook

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3396]
Today, hook is ignoring SIGTERM but it should be possible to handle it, wait until all existing events are handled, and exit (might be a lot faster than 180s that is added in https://github.com/kubernetes/test-infra/pull/3377 or even 30s which is the default termination grace period today).

It should be a similar fix to #6751

/area prow

**Comment by kargakis** [comment]
Interesting discussion in the following links:
https://github.com/kubernetes/kubernetes/issues/43576
https://github.com/kubernetes/ingress/issues/322
https://github.com/kubernetes/kubernetes/issues/20473
https://github.com/kubernetes/community/pull/483

**Comment by kargakis** [comment]
Similar fix to https://github.com/kubernetes/test-infra/pull/6751

/help

**Comment by paulangton** [comment]
Starting work on this issue, going to use a WaitGroup to ensure all events have been handled before shutdown.

**Comment by paulangton** [comment]
@kargakis can we close this since #8126 was merged?

**Comment by kargakis** [comment]
Thanks for working on this!

/close
