### ISSUE TITLE
Set owner references in pods owned by ProwJobs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3409]
This can help in offloading pod GC to the k8s garbage collector and/or constraining what pods sinker can delete, ie. only those owned by ProwJobs.

/area prow

**Comment by kargakis** [comment]
[This is not going to work if ProwJobs and Pods reside in different namespaces](https://github.com/kubernetes/apimachinery/blob/21de1bffe600f61f4873ae774a60f7a7d37ac9bf/pkg/apis/meta/v1/types.go#L273-L275) ...

**Comment by spxtr** [comment]
It also won't work if they are in different clusters.

**Comment by kargakis** [comment]
Why would we run them in separate clusters? Even the namespace separation doesn't make sense to me and it goes against core k8s api practices but I  guess there are reasons behind these decisions I am missing...

**Comment by spxtr** [comment]
We are running untrusted code in prow, so I added the ability to run the test pods in either a separate namespace or a separate cluster entirely. The GitHub access token is pretty powerful and I think it makes sense to keep it as far away from the untrusted code as possible. With RBAC namespaces it should be less important, although on G(C|K)E it's still possible to talk to the metadata server.

**Comment by kargakis** [comment]
@spxtr does PSP mitigate some/a lot of the risks with running untrusted code inside a pod? Coupled with locked-down NetworkPolicy?

https://kubernetes.io/docs/concepts/policy/pod-security-policy/
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by spxtr** [comment]
They certainly mitigate a lot of the risk, but I think there are still holes. In particular, I don't think NetworkPolicies allow you to block pods talking to the GCE metadata server, although I might be wrong.

**Comment by kargakis** [comment]
Egress policy is briefly discussed in https://github.com/kubernetes/kubernetes/issues/22469

**Comment by kargakis** [comment]
This separation of PJs and Pods makes sense to me.

**Comment by kargakis** [comment]
> They certainly mitigate a lot of the risk, but I think there are still holes. In particular, I don't think NetworkPolicies allow you to block pods talking to the GCE metadata server, although I might be wrong.

FWIW, https://github.com/kubernetes/kubernetes/pull/51351
