### ISSUE TITLE
Prow Feature Request: Fuzzy matcher for jobs drop-down

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/test-infra#3414]
There are a lot of jobs. A fuzzy text-search matcher for the drop-down on prow.k8s.io would help find specific jobs faster in the list.

**Comment by fejta** [comment]
What are you doing with prow that isn't met with testgrid?

**Comment by mtaufen** [comment]
It's mostly when I want to see if a PR job has had a streak of failures recently across many PRs.

**Comment by BenTheElder** [comment]
Oh, thanks @fejta-bot, this was implemented by @qhuynh96. http://prow.k8s.io/

/remove-lifecycle stale
/close

**Comment by mtaufen** [comment]
w00t!
