### ISSUE TITLE
Cluster logs missing for all kubemark tests

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#3416]
Since saturday cluster logs started missing for all kubemark tests. This is happening for all of them (except scale test).
For instance, all runs from 3517 of kubemark-100 show this problem -> https://k8s-testgrid.appspot.com/google-kubemark#100-gce

Seems like something around test setup changed. Also, metrics and resource usages are being printed in the build-log instead of being written to separate JSON files (like before).
Ref: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce/3517/build-log.txt

cc @kubernetes/test-infra-maintainers @fejta @gmarek @wojtek-t

**Comment by shyamjvs** [comment]
@fejta Assigning this to you. Feel free to reassign as apt :)

**Comment by fejta** [comment]
I suspect the issue is that `Kubemark()` needs to push E2E_REPORT_DIR` like `Test()` does

**Comment by shyamjvs** [comment]
Thanks a lot for spotting the issue. Sent the above PR to fix it, PTAL.

**Comment by shyamjvs** [comment]
This issue is fixed after merging the above PRs.
Ref: http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/6516/artifacts/
