### ISSUE TITLE
cadvisor-kubelet builds failing since 6/30

### ISSUE THREAD

**Issue by dashpole** [kubernetes/test-infra#3419]
[cadvisor-kubelet builds](https://k8s-testgrid.appspot.com/sig-node#cadvisor-kubelet)

example failure: 
`W0710 08:01:09.131] + build/assets.sh`
`W0710 08:01:09.794] go install runtime/internal/atomic: open /usr/local/go/pkg/linux_amd64/runtime/internal/atomic.a: permission denied`
`W0710 08:01:09.796] Traceback (most recent call last):`
`W0710 08:01:09.796]   File "/var/lib/jenkins/workspace/ci-cadvisor-node-kubelet/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>`
`W0710 08:01:09.796]     main(ARGS.env, ARGS.cmd + ARGS.args)`
`W0710 08:01:09.796]   File "/var/lib/jenkins/workspace/ci-cadvisor-node-kubelet/./test-infra/jenkins/../scenarios/execute.py", line 41, in main`
`W0710 08:01:09.796]     check(*cmd)`
`W0710 08:01:09.796]   File "/var/lib/jenkins/workspace/ci-cadvisor-node-kubelet/./test-infra/jenkins/../scenarios/execute.py", line 30, in check`
`W0710 08:01:09.796]     subprocess.check_call(cmd)`
`W0710 08:01:09.797]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call`
`W0710 08:01:09.797]     raise CalledProcessError(retcode, cmd)`
`W0710 08:01:09.797] subprocess.CalledProcessError: Command '('./build/jenkins_e2e.sh',)' returned non-zero exit status 1`
`E0710 08:01:09.800] Build failed`

**Comment by ixdy** [comment]
also correlates with #3276, but I don't understand what's happening here.

**Comment by dims** [comment]
@ixdy based on tips here - https://bugzilla.redhat.com/show_bug.cgi?id=973842 - could be a problem with timestamps. Maybe we could throw a `--touch` when we extract the files? other tips i found were around cleaning up the previous directory (https://www.google.com/search?q=%22atomic.a%3A+permission+denied%22)

```
dims@bigbox:~/Downloads$ tar -ztvf go1.8.3.linux-amd64.tar.gz | grep -e "sync\.a" -e "atomic\.a"
-rw-r--r-- 0/0            7074 2017-05-24 14:15 go/pkg/linux_amd64/runtime/internal/atomic.a
-rw-r--r-- 0/0           16006 2017-05-24 14:15 go/pkg/linux_amd64/sync/atomic.a
-rw-r--r-- 0/0           47664 2017-05-24 14:15 go/pkg/linux_amd64/sync.a
-rw-r--r-- 0/0            7074 2017-05-24 14:16 go/pkg/linux_amd64_race/runtime/internal/atomic.a
-rw-r--r-- 0/0           12202 2017-05-24 14:16 go/pkg/linux_amd64_race/sync/atomic.a
-rw-r--r-- 0/0           53968 2017-05-24 14:16 go/pkg/linux_amd64_race/sync.a
```

**Comment by dashpole** [comment]
is it possible go wasnt updated correctly?
https://www.reddit.com/r/golang/comments/6b419n/installed_181_now_go_install_fails/

**Comment by ixdy** [comment]
aha, ok, so in #3276 I removed this line:
```bash
sudo bash -c 'GOROOT=/usr/local/go PATH=\${GOROOT}/bin:\${PATH} CGO_ENABLED=0 go install -a -installsuffix cgo std'
```
because I thought we didn't need it anymore (the kubernetes builds all run inside docker), but cadvisor isn't running in a docker container.

I can probably update the Jenkins agents by running this command, but we should probably containerize the cadvisor builds so that they are immune to Jenkins environment changes. (This is also a prerequisite for getting them onto prow, which is far more maintainable than Jenkins.)

**Comment by ixdy** [comment]
actually, that might not be needed. I think @dashpole is right - the `/usr/local/go` directory seems to include other stuff, possibly because go was already installed in the image (somehow) and we didn't wipe it out before extracting the new version.

**Comment by ixdy** [comment]
(we should still try to isolate cadvisor from Jenkins.)

**Comment by ixdy** [comment]
OK, I think I finally figured out what's happening.

I recreated the CI Jenkins "heavy" VMs with `jenkins/agent-ctl.sh auto-image`, but without passing `--base-image`. Because I hadn't included `--base-image`, it used one of the existing images which already had go installed.

I'll recreate the "heavy" VMs with the correct base image. Note it's also going to bump them up to debian 9, which may or may not break things in other ways.

**Comment by ixdy** [comment]
I ran the build on one of my recreated Jenkins VMs, and it [failed differently](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-cadvisor-node-kubelet/10717):
```
W0731 23:27:39.197] Run: ('./build/jenkins_e2e.sh',)
W0731 23:27:39.199] + BUILDER=false
W0731 23:27:39.199] + export GO_FLAGS=-race
W0731 23:27:39.200] + GO_FLAGS=-race
W0731 23:27:39.200] + export GORACE=halt_on_error=1
W0731 23:27:39.200] + GORACE=halt_on_error=1
W0731 23:27:39.200] + FORCE=true
W0731 23:27:39.200] + build/assets.sh
W0731 23:27:46.354] ++ git diff --name-only pages
W0731 23:27:46.359] + [[ ! -z pages/static/assets.go
W0731 23:27:46.359] pages/templates.go ]]
W0731 23:27:46.359] + echo 'Found changes to UI assets:'
W0731 23:27:46.359] + git diff --name-only pages
W0731 23:27:46.364] ++ make assets FORCE=true
I0731 23:27:46.465] Found changes to UI assets:
I0731 23:27:46.465] pages/static/assets.go
I0731 23:27:46.465] pages/templates.go
I0731 23:27:47.080] Run: >> building assets
W0731 23:27:47.106] + echo 'Run: >> building assets'
W0731 23:27:47.106] + exit 1
```

I'm pretty sure this is an issue in cadvisor now, not Jenkins.

**Comment by dashpole** [comment]
build is green on https://github.com/google/cadvisor/pull/1710, so this is fixed.  Thanks for the help @ixdy!
