### ISSUE TITLE
cadvisor-push builds failing since 6/30

### ISSUE THREAD

**Issue by dashpole** [kubernetes/test-infra#3420]
[cadvisor-push builds](https://k8s-testgrid.appspot.com/sig-node#cadvisor-push)

Example Failure
`W0630 19:29:00.764] Run: ('docker', 'inspect', 'google/cadvisor:canary')`
`W0630 19:29:00.764] 0`
`W0630 19:29:00.764] Run: ('docker', 'version', "--format='{{.Client.Version}}'")`
`W0630 19:29:00.764] Logging in as 'cadvisorjenkinsbot'`
`W0630 19:29:00.764] docker: "login" requires a maximum of 1 argument.`
`W0630 19:29:00.765] See 'docker login --help'.`
`W0630 19:29:00.765] `
`W0630 19:29:00.765] Usage:	docker login [OPTIONS] [SERVER]`
`W0630 19:29:00.765] `
`W0630 19:29:00.765] Log in to a Docker registry.`
`W0630 19:29:00.766] If no server is specified, the default is defined by the daemon.`
`W0630 19:29:00.766] Traceback (most recent call last):`
`W0630 19:29:00.766]   File "/var/lib/jenkins/workspace/ci-cadvisor-canarypush/./test-infra/jenkins/../scenarios/canarypush.py", line 83, in <module>`
`W0630 19:29:00.766]     main(ARGS.target, ARGS.file)`
`W0630 19:29:00.766]   File "/var/lib/jenkins/workspace/ci-cadvisor-canarypush/./test-infra/jenkins/../scenarios/canarypush.py", line 60, in main`
`W0630 19:29:00.767]     check_no_log('docker', 'login', email or '', '--username=%s' % user, '--password=%s' % pwd)`
`W0630 19:29:00.767]   File "/var/lib/jenkins/workspace/ci-cadvisor-canarypush/./test-infra/jenkins/../scenarios/canarypush.py", line 37, in check_no_log`
`W0630 19:29:00.767]     raise subprocess.CalledProcessError(cmd='subprocess.check_call', returncode=1)`
`W0630 19:29:00.767] subprocess.CalledProcessError: Command 'subprocess.check_call' returned non-zero exit status 1`
`E0630 19:29:00.767] Build failed`

**Comment by ixdy** [comment]
This looks highly correlated to when I upgraded docker from 1.9.1 to 1.11.2 (https://github.com/kubernetes/test-infra/pull/3276).

We're not going to downgrade docker, so this probably needs to be fixed in the cadvisor scripts.

**Comment by ixdy** [comment]
not sure what's going on [here](https://github.com/kubernetes/test-infra/blob/f66ed8292d07e2fb641a7c3d3bbc317bd6e84ed0/scenarios/canarypush.py#L53-L60) but it doesn't seem to be doing the right thing for docker 1.11:

1.11:
```console
$ docker help login

Usage:  docker login [OPTIONS] [SERVER]

Log in to a Docker registry.
If no server is specified, the default is defined by the daemon.

  --help             Print usage
  -p, --password     Password
  -u, --username     Username
```

1.9:
```console
$ docker help login

Usage:  docker login [OPTIONS] [SERVER]

Register or log in to a Docker registry.
If no server is specified "https://index.docker.io/v1/" is the default.

  -e, --email=       Email
  --help=false       Print usage
  -p, --password=    Password
  -u, --username=    Username
```

it looks like email isn't used at all anymore?
cc @krzyzacy

**Comment by krzyzacy** [comment]
eh.. the scenario was translating what it used to do, and yes seems `--email` was only valid for before docker 1.9?

maybe we can just do `docker login user password`?

**Comment by krzyzacy** [comment]
nvm,  maybe https://stackoverflow.com/questions/32279790/docker-toolbox-windows-logging-into-quay-io?

**Comment by krzyzacy** [comment]
hummm, I'm not able to get the same error in python..

**Comment by dashpole** [comment]
I am pretty sure I know what is going on.  It turns out
`check_no_log('docker', 'login', '', '--username=None', '--password=None')` fails with the error, but
`check_no_log('docker', 'login', '--username=None', '--password=None')` succeeds (or at least gives me an authentication error)

**Comment by dashpole** [comment]
is it safe to rip out the email setting?  Or do we care that it wont work with version 1.9?

**Comment by krzyzacy** [comment]
yeah I think we are not going to downgrade docker... feel free
