### ISSUE TITLE
wrong config for kubectl skew tests

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/test-infra#3423]
2 issues with the config:
- Some config is missing for [ci-kubernetes-e2e-gke-new-master-cvm-kubectl-skew](https://github.com/kubernetes/test-infra/blob/5dc6dd918fc0c30e395fabe4ec3e507b0e4f3d57/jobs/config.json#L5317).
`"--test_args=--ginkgo.focus=Kubectl --kubectl-path=../kubernetes_skew/cluster/kubectl.sh"` this line of config is missing. See how we config [ci-kubernetes-e2e-gke-new-master-gci-kubectl-skew](https://github.com/kubernetes/test-infra/blob/5dc6dd918fc0c30e395fabe4ec3e507b0e4f3d57/jobs/config.json#L5332).
- `../kubernetes_skew/cluster/kubectl.sh` seems to be the wrong path for kubectl. It causes almost all skew test failing https://k8s-testgrid.appspot.com/master-kubectl-skew#gce-1.7-master-cvm.

/assign @krzyzacy

**Comment by krzyzacy** [comment]
probably https://github.com/kubernetes/test-infra/commit/1aedc7b48d027c789a84ed412ab8ed1e55fa6e15

not that hunky dory 🔥 😈 
/assign @fejta 
/unassign

**Comment by mengqiy** [comment]
@krzyzacy What is the correct path for `kubectl.sh`?

**Comment by krzyzacy** [comment]
maybe it should just be `./kubernetes_skew/cluster/kubectl.sh`, looking

**Comment by krzyzacy** [comment]
or we'd better use abs path here?

**Comment by fejta** [comment]
Investigating...

**Comment by pwittrock** [comment]
fwiw, things started failing between 7/6 13:20 (passed) and 14:20 (failed).  Looks like there were no changes to the tests between those times (both ran at bf2be8073).

**Comment by pwittrock** [comment]
Yes, PR #3309 looks like a likely candidate.

**Comment by fejta** [comment]
Yes, that's the cause. Need to figure out what to do about it

**Comment by fejta** [comment]
Odd... If I run kubetest without the --extract flag things seem to work...

**Comment by fejta** [comment]
Hmm... maybe locally the problem is kubectl is on my path

**Comment by fejta** [comment]
Aha! If I change the focus from out-of-range to kubectl I get the error

**Comment by fejta** [comment]
Apparently the path is relative to `./kubernetes/platforms/linux/amd64` not `./kubernetes`

**Comment by pwittrock** [comment]
@fejta I am seeing a failure for the upgrade tests that I think maybe the same issue.  Does this look like the same thing to you?

> '--test_args=--kubectl-path=../kubernetes_skew/cluster/kubectl.sh'

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-cvm-master-upgrade-cluster/48/build-log.txt

**Comment by pwittrock** [comment]
Also, this started failing sometime around PR #3444.  Do you think it is related?

https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster-new&show-stale-tests=

**Comment by ixdy** [comment]
Looks unrelated:
```
W0712 13:37:09.909] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W0712 13:37:09.909]  name: u'operation-1499866584496-99915925'
W0712 13:37:09.909]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W0712 13:37:09.909]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/973074400555/zones/us-central1-a/operations/operation-1499866584496-99915925'
W0712 13:37:09.909]  status: StatusValueValuesEnum(DONE, 3)
W0712 13:37:09.909]  statusMessage: u'Failed to create cluster'
W0712 13:37:09.910]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/973074400555/zones/us-central1-a/clusters/bootstrap-e2e'
W0712 13:37:09.910]  zone: u'us-central1-a'>] finished with error: Failed to create cluster
```

**Comment by pwittrock** [comment]
@ixdy Thanks.  Any idea who owns that failure?

**Comment by ixdy** [comment]
@pwittrock per https://go.k8s.io/oncall I think @krousey

**Comment by fejta** [comment]
Given the timeframe of failures starting, I suspect GKE pushed something around midnight that broke test
