### ISSUE TITLE
Need easier ways to learn what a CI job is about

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#3436]
From https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-master&width=20.

While looking into test failures, I found the upgrade CIs' names are so confusing --- we have `master-upgrade-cluster`, `master-upgrade-master`, `master-upgrade-cluster-new`. I have no idea what each CI is about and how are they different. The only way to figure out is digging into build logs and that introduces a lot of unnecessary overheads.

Is there a place I can learn on a high level about which CI is doing what, and could we expose such information in a more obvious way? For now I could only found comments like [this](https://github.com/kubernetes/test-infra/blob/master/jobs/ci-kubernetes-e2e-gke-cvm-new-gci-master-upgrade-master.env#L2).

**Comment by michelle192837** [comment]
If a short summary would be enough, someone should be able to add [descriptions](https://github.com/kubernetes/test-infra/tree/master/testgrid/config#tab-descriptions) for each tab to describe which tabs are testing what.

**Comment by krzyzacy** [comment]
it reads better as: gke - [gci-1.7] - [gci-master] - upgrade - [master/cluster/cluster-new(skew)]

there should be some doc at the env files, and yes agree we can add them to the description.

**Comment by MrHohn** [comment]
> If a short summary would be enough, someone should be able to add descriptions for each tab to describe which tabs are testing what.

That sounds great. Will that description be available on k8s-testgrid as well?

**Comment by krzyzacy** [comment]
yes, for example, http://k8s-testgrid.appspot.com/sig-storage#gce-1.6 has a hover text as description

**Comment by krzyzacy** [comment]
@MrHohn if the comment is enough then we can add that to testgrid, if not then maybe give some suggestion on what's a better way to summarize the upgrade test?

**Comment by MrHohn** [comment]
@krzyzacy Thanks, comments like that should be sufficient. Sent a PR for adding descriptions, though not all CIs have useful comments in their env files.

**Comment by kargakis** [comment]
@spiffxp can we get a kind/documentation label? Consistent with the main repo and there are a couple of more doc-related issues: https://github.com/kubernetes/test-infra/issues/3258 https://github.com/kubernetes/test-infra/issues/3229 https://github.com/kubernetes/test-infra/issues/3118 https://github.com/kubernetes/test-infra/issues/3117

**Comment by spiffxp** [comment]
/kind documentation

I'm not a fan of an explosion of kinds, but makes sense to me

**Comment by krzyzacy** [comment]
/unassign
we'd just ask people (maybe each sig) add description to their job

**Comment by fejta** [comment]
/close
All jobs now have testgrid descriptions
