### ISSUE TITLE
Why do we have both clean-projects and janitor?

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3446]
https://github.com/kubernetes/test-infra/blob/master/jobs/maintenance-pull-clean-projects.sh
https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_janitor.py

Any idea why we need both of these jobs running?
/assign @krzyzacy

**Comment by krzyzacy** [comment]
I think janitor is derived from clean-projects and should have pull jobs covered now. We probably can delete maintenance-pull-clean-projects.sh.
