### ISSUE TITLE
Filter by the release branch in gubernator/prow

### ISSUE THREAD

**Issue by crassirostris** [kubernetes/test-infra#3449]
Sometimes job fails 100% times in some specific release, but since you cannot filter by this, is seems like it only flakes

**Comment by spiffxp** [comment]
/close
I believe you can use release-specific dashboards for this?  eg: https://k8s-testgrid.appspot.com/sig-release-1.7-all for the release-1.7 jobs

Please reopen and clarify if I've misunderstood

**Comment by crassirostris** [comment]
Sorry I wasn't clear

I was talking about PR jobs that have some milestone assigned to them or PR is based on some release branch

**Comment by kargakis** [comment]
Closing as a dupe of https://github.com/kubernetes/test-infra/issues/6144 (this is an older issue but there is more discussion in the other thread)
