### ISSUE TITLE
Approval comment not updated after force push

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#3450]
In #48644, someone opened a PR that needed approval from three people. Then, they edited the PR such that it only needed approval for one file that they were an owner of. The munger added the "approved" label, but didn't switch the comment to indicate this.

Sorry if this is a dupe. @grodrigues3

**Comment by xiangpengzhao** [comment]
As the PR number in this issue is not linked, I give a link here for guys convenience: https://github.com/kubernetes/kubernetes/pull/48644

**Comment by xiangpengzhao** [comment]
OTOH, it's really confusing to see a PR has `approved` label and a `NOT APPROVED` comment. See: #3580

**Comment by spiffxp** [comment]
Repro'd with the newly linked PR, steps I took are in the PR description.

/assign @cjwagner 
since I think you're working on migrating approval-handler to prow, or maybe for now could gather logs related to the above PR to figure out what's going on?

**Comment by cjwagner** [comment]
To determine if a previous notification is stale, the munger just checks that there is not a `/lgtm` or `/approve` comment made after the previous notification was posted. In other words, the update logic for the notification message (not the label itself) does not consider updates that result from pull request synchronizations.
I'll fix this in the approve plugin.
/assign

**Comment by cjwagner** [comment]
/close
This is fixed now in the approve plugin. The plugin will be run on test-infra first, then other repos.
