### ISSUE TITLE
remove sig-api-machinery from "no sig label" message

### ISSUE THREAD

**Issue by mbohlool** [kubernetes/test-infra#3494]
Can we remove api machinery from this message: https://github.com/kubernetes/test-infra/blob/6f7432c18267d6e9bfd6732d30e2ea4725326a99/mungegithub/mungers/sig-mention-handler.go#L106

it should be a non-existing sig so copy/pasting fails or API Machinery team will get more and more unrelated issues/PRs.

**Comment by mbohlool** [comment]
@grodrigues3

**Comment by grodrigues3** [comment]
@mbohlool the current implementation does not a trigger a notification to api machinery nor would copy/paste trigger a notification.

**Comment by grodrigues3** [comment]
I'm fine with changing the example from api-machinery to contributor-experience-group-suffix

**Comment by grodrigues3** [comment]
@crimsonfaith91

**Comment by crimsonfaith91** [comment]
@mbohlool @grodrigues3 Current implementation should not trigger any notification anymore to api machinery. i will change it to  contributor-experience-group-suffix`.

**Comment by spiffxp** [comment]
no longer mentions api-machinery, latest eg: https://github.com/kubernetes/kubernetes/issues/49122
