### ISSUE TITLE
OWNERS: Add mechanism to label PRs

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#3498]
Add a `labels:` section to OWNERS files; when the bot munger sees a PR changes files to which the OWNERS file applies, it will add those labels to the PR.

Use case: I want to make sure that the sig/api-machinery label is applied to all PRs touching various directories. I imagine other SIGs could use this also.

I want this badly enough that I might be willing to actually write it, if there are no objections.

**Comment by lavalamp** [comment]
There's already a path-label munger, but it seems to work off of a config file, which isn't super useful.

**Comment by lavalamp** [comment]
See https://github.com/kubernetes/test-infra/blob/master/mungegithub/path-label.txt

I think both mechanisms would be useful-- it's better to keep labels local in OWNERS files for maintainability, but it's also nice to be able to match all types.go files via regexp.

**Comment by lavalamp** [comment]
I am 75% of the way towards having a PR ready for this.

**Comment by fejta** [comment]
Hmm... we would like this to be a prow plugin, not a munger

**Comment by spxtr** [comment]
We'll probably migrate the entire approvals system to prow, but probably this should be added onto the munger for now.

**Comment by lavalamp** [comment]
I don't care where it ends up but at the moment I think all OWNERS file implementation code should be in one place.

**Comment by spxtr** [comment]
This feels a little like feature creep for the approvers munger. Currently it handles adding the approved label properly, but it also handles checking for associated issues and now adding labels? These latter two features are mostly unrelated to approving PRs.

**Comment by lavalamp** [comment]
I need this feature. I am happy to put the source for it wherever, as long as it live with the directories or at least in the repo (e.g., not in the path-label munger input file).

**Comment by spxtr** [comment]
I think it makes sense to put it in the path label munger as @cjwagner suggests.
