### ISSUE TITLE
Should ignore strings other than empty or "@foo" after "/assign"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3508]
See: https://github.com/kubernetes/kubernetes/issues/48927#issuecomment-315408077

If I want to assign some issues to myself by `/assign`, it doesn't work due to I'm not an org member and gives me a comment telling me why. But if I comment `/assign any string`, nothing happens. It would be good to give the same comment to tell me that I can't assign myself instead of giving nothing.

I remember if I comment `/sig foo any string`, it works. The bot will label `sig/foo` no matter what I type after `/sig foo`.

**Comment by fejta** [comment]
I do not think we should fix this. `/assign will fix it` is ambiguous between wanting to assign to yourself with a comment and wanting to assign it to three people (will, fix and it).

**Comment by fejta** [comment]
User behavior is more flexible and can change their behavior.

It is better to keep our plugins simple rather than trying to distinguish between myriad edge cases like this (we already took a patch to accept /assign fejta in addition to /assign @fejta which I'm not crazy about

**Comment by spxtr** [comment]
Please put all commands isolated on their own lines with no non-argument text after the command. Possibly we should update commands.md to make this more clear.

**Comment by brahmaroutu** [comment]
@xiangpengzhao @fejta I think the code does handle random strings, it is probably some logic in the event handler that generate comment handler event. 
BTW I do agree(not fixing it) that the user can check to see assignees but is it possible to automate assignees? A proper error code should come out of this action if we want a script to run this for some reason.
If we are not fixing can we close the issue or document it as @spxtr suggested.

**Comment by xiangpengzhao** [comment]
>I do not think we should fix this. /assign will fix it is ambiguous between wanting to assign to yourself with a comment and wanting to assign it to three people (will, fix and it).

@fejta did you mean that `/assign will fix it` will think `will fix it` as three people even though there are no `@` before the three strings? Hmm...

Agree with not fixing it but it'd be good to document it more clear.

**Comment by spiffxp** [comment]
Assigning to the v1.9 milestone to make docs more clear (if they aren't already)

**Comment by spiffxp** [comment]
Docs still don't really explicitly mention that `/assign @foo please take a look` anti-pattern, and I've seen people stumble over it.  If we only interpreted `@foo` as assignable targets we could support this pattern.  Then again, I don't think any other plugins really support "comments" on the same line.

I'd sure be curious to see how often people are issuing `/assign @foo` vs. `/assign foo`
