### ISSUE TITLE
Approvers suggestion from a different file

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#3514]
For this PR the bot says we need an approver from test/e2e and then suggests lavalamp who is not in that OWNERS file.

https://github.com/kubernetes/kubernetes/pull/48890#issuecomment-315218321

**Comment by spiffxp** [comment]
The comment-deleter munger got to the linked comment, I don't suppose anyone has a copy of the logs to show the timestamp of how/why the (blunderbuss?) munger made this decision?

**Comment by spiffxp** [comment]
/close
not enough info to repro or diagnose here, please open another issue if you see OWNERS-related misbehavior
