### ISSUE TITLE
FederationTest does not set E2E_REPORT_DIR

### ISSUE THREAD

**Issue by csbell** [kubernetes/test-infra#3515]
Since #3394, the testgrid is not reporting pass/fail on any of the tests in federation-e2e despite the fact that they are running (and passing, most of the time).

This applies to the 1.7 tests: http://k8s-testgrid.appspot.com/release-1.7-all#gce-federation-release-1-7&show-stale-tests=
and to head tests: http://k8s-testgrid.appspot.com/sig-federation#gce&show-stale-tests=

/assign fejta

**Comment by fejta** [comment]
I'm pretty sure I know what this is as kubemark had the same problem.

**Comment by fejta** [comment]
Fix out, will update kubetest in these images after we merge.
