### ISSUE TITLE
prow dashboard no longer displays log output

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3522]
/assign @spxtr 
/area prow

**Comment by fejta** [comment]
http://prow.k8s.io/log?job=pull-kubernetes-e2e-gce-bazel&id=2370 is empty but kubectl logs for the job still shows output

Joe says this is a recent regression

**Comment by krzyzacy** [comment]
do we need https://github.com/kubernetes/test-infra/pull/3509?

**Comment by spxtr** [comment]
Fixed. #3509
