### ISSUE TITLE
Build queue for kops - Question

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#3534]
Hey all  

How do we get a build queue for kops, with automatic merges with an LGTM?  Do we have instructions on how to setup one?

The problem we have had multiple times is that a PR is merged into master, and after the merge, master is broken :(

Also, it would be awesome to have PRs just merged automatically.

**Comment by cjwagner** [comment]
@chrislovecnm If you make a config file with the options you want for the kops repo I can deploy a mungegithub instance for you.  The config should look something like the [contrib config](https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/contrib/configmap.yaml) or the [kubernetes config](https://github.com/kubernetes/test-infra/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml). Run the mungegithub binary with `--help` to print descriptions of the options.

**Comment by chrislovecnm** [comment]
BTW ... the binary does not build on mac.  Pushing a PR, my main question is how to integrate our e2e run.
