### ISSUE TITLE
Bot merged PR without approval

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#3544]
It looks like the bot merged https://github.com/kubernetes/kubernetes/pull/48562 via the submit queue even though it never got OWNERS approval. Either the bot did something weird, or GitHub has lost the record of the PR getting approved...

**Comment by krzyzacy** [comment]
I think this is fixed by https://github.com/kubernetes/test-infra/pull/3504?
/assign @cjwagner

**Comment by cjwagner** [comment]
Yes that issue was fixed.

**Comment by spxtr** [comment]
[These PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr%20-label%3Aapproved%20is%3Amerged%20merged%3A%3E2017-07-10) merged without approval during that window.

**Comment by enisoc** [comment]
I went through that list and it seems they all fall into one of two buckets:

* Docs/comment changes that are pretty trivial.
* Changes that were otherwise approved, except that the approvers didn't add `no-issue`.
