### ISSUE TITLE
kops build timed out on all 1.6 cherrypick PRs

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#3549]
The `pull-kubernetes-e2e-kops-aws` test is failing on all `release-1.6` PRs with a log like this:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/48875/pull-kubernetes-e2e-kops-aws/35232/
```
W0717 01:34:15.596] + make release
I0717 01:34:15.696] +++ [0717 01:34:15] Building Docker image kube-build:build-97651ea9c2-5-v1.7.6-k8s1.6-0
Build timed out (after 90 minutes). Marking the build as failed.
Build was aborted
W0717 03:03:39.609] build/../build/common.sh: line 377: 25241 Terminated              "${DOCKER[@]}" wait "$1" > /dev/null 2>&1
Finished: FAILURE
```

The continuous job seems to be ok, however:

https://k8s-testgrid.appspot.com/release-1.6-all#kops-aws-1.6&width=20

**Comment by enisoc** [comment]
ref:
https://github.com/kubernetes/kubernetes/pull/48875
https://github.com/kubernetes/kubernetes/pull/48823
https://github.com/kubernetes/kubernetes/pull/48312

**Comment by spiffxp** [comment]
this needs to get cherry-picked into release-1.6 https://github.com/kubernetes/kubernetes/pull/48762

**Comment by spiffxp** [comment]
cherry-pick PR https://github.com/kubernetes/kubernetes/pull/49214

**Comment by enisoc** [comment]
That seems to have fixed it. Thanks!
