### ISSUE TITLE
Publisher should be a postsubmit job split out of mungegithub.

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#3579]
It uses effectively none of mungegithub's framework (just command-line arguments), so it should be a standalone program.

**Comment by spiffxp** [comment]
/area mungegithub
just because this involves ripping code out of mungegithub

**Comment by fejta** [comment]
/assign @sttts 

Isn't this now in https://github.com/kubernetes/publishing-bot?

**Comment by sttts** [comment]
Yes, let's close this here.
