### ISSUE TITLE
PR which has a "approved" label still gets a "NOT APPROVED" comment

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3580]
See: https://github.com/kubernetes/kubernetes/pull/49110

This PR was labeled `approved` manually https://github.com/kubernetes/kubernetes/pull/49110#event-1169125755. But the `k8s-merge-robot` still told me that the PR is `NOT APPROVED` https://github.com/kubernetes/kubernetes/pull/49110#issuecomment-316228422. This is confusing.

Seems like the PR is indeed approved. All checks have passed and `Submit Queue` shows that:
`Submit Queue — Queued to run github e2e tests a second time.`

robot should be smarter in this case:)

/cc @crimsonfaith91

**Comment by spiffxp** [comment]
At some point we might want to disallow the "approved" label getting manually added as a circumvention of OWNERS, but I'm not sure OWNERS is healthy enough to mandate enforcement of that opinion

**Comment by luxas** [comment]
@spiffxp I definitely don't think OWNERS is healthy enough to do that.

**Comment by spiffxp** [comment]
fyi @cjwagner something else to consider around approval-handler

I think today it's still possible to manually add the `approved` label and circumvent the approval process entirely.

**Comment by cjwagner** [comment]
Yes manually adding the `approved` label will work, but the notification message will be wrong in that case.
I'll fix this in the approve plugin.
/assign

**Comment by cjwagner** [comment]
/close
This is fixed in the approve plugin now. The plugin will be run on test-infra first and then be expanded to other repos that use the approval process.
