### ISSUE TITLE
Mention approver in the "NOT APPROVED" comment

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3581]
In the comment which tells that the PR is not approved, e.g. `We suggest the following additional approver: dchen1107`, the approver's name is only listed there, without being mentioned. It'd be good to mention the approver here. This will be a notification to ping the approver.

```
[APPROVALNOTIFIER] This PR is NOT APPROVED

This pull-request has been approved by: ncdc, xiangpengzhao
We suggest the following additional approver: dchen1107
```
Example from: https://github.com/kubernetes/kubernetes/pull/48237#issuecomment-315750679

/cc @crimsonfaith91

**Comment by crimsonfaith91** [comment]
No, we should not ping the suggested approvers. They receive many emails every day.

**Comment by xiangpengzhao** [comment]
Hmm, I also worried about that this might generate spam notifications/emails. Agree with not ping.
Thanks!
/close
