### ISSUE TITLE
Propagate sig team notification for non-org members across all K8S repos 

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3582]
Since labels will be propagated across all repos (https://github.com/kubernetes/test-infra/issues/2504, https://github.com/kubernetes/test-infra/pull/2706), it'd be good to propagate sig team notification for non-org members across all K8S repos.

See: https://github.com/kubernetes/community/pull/778#issuecomment-315614907
It doesn't work in kubernetes/community for now.

/cc @crimsonfaith91 @grodrigues3 @spxtr

**Comment by spiffxp** [comment]
I have a theory that it'll start working as soon as `sig/foo` labels are added to the repo in question

This is also maybe a sign that we want to extract re-announcing org team names on half of non-org-members into a prow plugin not named 'label'

**Comment by spiffxp** [comment]
/assign @grodrigues3 
The work you're doing to propagate labels includes sig labels, which should resolve this.  I'm mentioning #4343 as a label sync umbrella issue.  Adding to v1.9 milestone as I expect this be done prior to kubecon.

**Comment by spiffxp** [comment]
/close
The `sig/foo` labels have since been propagated.  Please /reopen if this is still an issue
