### ISSUE TITLE
OWNERS_ALIAS Requires Root Approval

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#3584]
The OWNERS_ALIAS file in the root directory of kubernetes/kubernetes requires root approval to update.  Sig leads should be able to update their reviewers/approvers.

I'm not sure what the solution is for this yet, so please propose potential ideas.

**Comment by spxtr** [comment]
We solved this for build-related things by symlinking them into the build directory.

**Comment by spiffxp** [comment]
I still think we should address this.  We could symlink, we could point at a different file that's not at root.  I have also wondered about syncing from or using a global OWNERS_ALIAS file, the same way we are doing for github labels via labels.yaml.  ie: consistent set of sig aliases across repos
