### ISSUE TITLE
periodic-kubernetes-e2e-kubeadm-gce-1-6 can't ssh to master

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#3605]
```
W0720 11:19:03.723] + echo Trying to fetch kubeconfig from master... 1/60
W0720 11:19:03.723] + gcloud compute ssh --project k8s-jkns-e2e-kubeadm-per-1-6 --zone us-central1-c ubuntu@e2e-1015-master --command 'echo STARTFILE; sudo cat /etc/kubernetes/admin.conf'
W0720 11:19:11.431] Warning: Permanently added 'compute.864886268278681455' (ECDSA) to the list of known hosts.
W0720 11:19:11.674] Permission denied (publickey).
W0720 11:19:11.690] ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
W0720 11:19:11.730] + sleep 5
I0720 11:19:16.731] Trying to fetch kubeconfig from master... 2/60
W0720 11:19:16.832] + for tries in '{1..60}'
W0720 11:19:16.832] + echo Trying to fetch kubeconfig from master... 2/60
W0720 11:19:16.832] + gcloud compute ssh --project k8s-jkns-e2e-kubeadm-per-1-6 --zone us-central1-c ubuntu@e2e-1015-master --command 'echo STARTFILE; sudo cat /etc/kubernetes/admin.conf'
W0720 11:19:17.456] Permission denied (publickey).
W0720 11:19:17.459] ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
W0720 11:19:17.523] + sleep 5
W0720 11:19:22.524] + for tries in '{1..60}'
W0720 11:19:22.524] + echo Trying to fetch kubeconfig from master... 3/60
W0720 11:19:22.525] + gcloud compute ssh --project k8s-jkns-e2e-kubeadm-per-1-6 --zone us-central1-c ubuntu@e2e-1015-master --command 'echo STARTFILE; sudo cat /etc/kubernetes/admin.conf'
I0720 11:19:22.625] Trying to fetch kubeconfig from master... 3/60
W0720 11:19:23.329] Permission denied (publickey).
W0720 11:19:23.332] ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

cc @pipejakob @mikedanese @krzyzacy @fejta 
Seems like the job don't have the right ssh keys to get the kubeconfig file in order to run e2e tests...?

**Comment by luxas** [comment]
Worth mentioning is that this behavior is flaky, sometimes passes, sometimes fails: https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#periodic-kubeadm-gce-1.6

**Comment by krzyzacy** [comment]
It might because `USER` is ubuntu instead of prow.. But it should be constantly failing instead of flaky..

**Comment by pipejakob** [comment]
I was trying to look into this a few weeks ago, but was unable to find a pattern (@krzyzacy, this is why I was asking about figuring out which nodes were used for old e2e runs). We've seen problems in the past where the test-infra cluster just had a single node that was misbehaving, so I was hoping it was attributable to something like that. This job is definitely flaky, and in the times when it fails, it's not a timeout or a race condition, but the repeated rejection of ssh (permission denied) for the identity of the caller, which is really suspicious.

If we invest some time in https://github.com/kubernetes/kubeadm/issues/256, we could also upload any relevant ssh/auth logs from the master to see why the connection is being rejected.

**Comment by ixdy** [comment]
are we still cleaning up ssh metadata? that's caused problems for us on some jobs in the past.

**Comment by krzyzacy** [comment]
@ixdy we only clean ssh metadata for pr projects I think

**Comment by krzyzacy** [comment]
looks green for the last two runs, gonna close this.
