### ISSUE TITLE
The `gcr.io/k8s-testimages/e2e-kubeadm` image should automatically get updated

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#3606]
ref: https://github.com/kubernetes/test-infra/pull/3589#issuecomment-316485835 and https://github.com/kubernetes/test-infra/pull/3571#issuecomment-316479449

@fejta @krzyzacy @pipejakob @mikedanese

**Comment by luxas** [comment]
@krzyzacy @fejta Any movement on this one?
I think it's painful to see hand-made updates/bumps of the image tag for `kubekins-(e2e|test)`, can we do better?
For instance:
`make -C jenkins/test-image update-dependencies` would update consumer tags for `kubekins-e2e` and also run `make -C jenkins/e2e-image update-dependencies` in turn; which would bump consumer tags in `images/kubeadm` && `images/e2e-prow` etc; which would bump versions in `prow/config.yaml`.

There could be a `.imagetags` file or something that would look like this:
```
kubeadm: gcr.io/k8s-testimages/e2e-kubeadm:v20170817-95c7a07f
```
the value there would hold the current value in `config.yaml`. Whenever `update-dependencies` would be run for kubeadm; the value of the `kubeadm` key in `.imagetags` would be replaced with the updated value, and `.imagetags` would be updated as well to reflect that.

That would make it soo much easier to keep `e2e-kubeadm` and `kubekins-e2e` in sync.
It would be everyone's responsibility to run `update-dependencies` (should be part of `push`?), but the person don't have to know anything about kubeadm and/or other higher-level images.

WDYT?

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/master/experiment/bump_e2e_image.sh is working pretty well, I guess we can add kubeadm there as well.
