### ISSUE TITLE
Support command "/lgtm trivial" or something to make PR not need approval

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3608]
Currently a PR needs an associated issue. If no issue, it needs `/approve no-issue` to get approved. When it has both `lgtm` and `approved` labels, it's then allowed to be merged. lgtm-ers and approvers may be different people, so the PR should wait for `lgtm` from one people and `approved` from other one(s). However, it's definitely unnecessary for those trivial PRs, especially the PRs which fix typos, broken links, etc. See example: https://github.com/kubernetes/kubernetes/pull/49294, it has a `lgtm` and is waiting for `approval`.

So I suggest a command `/lgtm trivial` for those PRs. When an assignee comments this in a PR, it will get both `lgtm` and `approved` labels.

@crimsonfaith91 @grodrigues3 @spiffxp @spxtr WDYT?

**Comment by kargakis** [comment]
I am against this. We should not allow bypassing approvals as much trivial a PR can be.

**Comment by crimsonfaith91** [comment]
@kargakis Agreed too. A trivial PR can be dangerous. :)

**Comment by xiangpengzhao** [comment]
The lgtm-ers should be very sure that a PR is indeed trivial when they are ready to `/lgtm trivial`. OTOH, approvers might miss potential bugs even though we request approval from them.

**Comment by xiangpengzhao** [comment]
This is a balance between convenience and safety. I agree with that safety should be our first choice. The more steps (lgtm + approved), the safer it seems to be:)

**Comment by grodrigues3** [comment]
Yeah, I don't want to provide a mechanism to circumvent approvers (which is our primary source of gating since lgtm can be written by anyone in the org now).   Can we close?  Or are there other suggestions?

**Comment by xiangpengzhao** [comment]
Yeah, agreed.
/close
