### ISSUE TITLE
CONTRIBUTING.md link to maintainers cannot be opened by non-members

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#3609]
The contributing docs currently link to [kubernetes/test-infra-maintainers](https://github.com/orgs/kubernetes/teams/test-infra-maintainers/members) which is a dead link.

I'm not actually seeing a suitable replacement yet though.

/cc @ixdy

**Comment by BenTheElder** [comment]
From another issue, it seems that the link is not bad, just not visible to non-members.

<img width="255" alt="screen shot 2017-07-20 at 10 29 48 am" src="https://user-images.githubusercontent.com/917931/28430733-6c1ece7e-6d36-11e7-9016-b550b01b940d.png">

Not sure if this should be fixed or is as-intended.

**Comment by spxtr** [comment]
Oh right, I totally forgot that teams aren't visible to non-org-members. We should link to something more useful for new contributors.

**Comment by ixdy** [comment]
@spxtr maybe we should add OWNERS files to test-infra so the munger can assign reviewers automatically?

**Comment by spxtr** [comment]
We should add a CODEOWNERS file so that GitHub assigns reviewers automatically, no need for a munger :)

**Comment by ixdy** [comment]
I think we should strive to have the same developer experience for all of our repos. Having CODEOWNERS in some places and k8s OWNERS in other places is going to be very confusing for contributors.

The fact that test-infra doesn't have a SQ like other repos has already been problematic.

**Comment by spiffxp** [comment]
Agree with @ixdy

I keep hearing mention of eventually wanting to drive teams from files vs just leaning on githubs teams but I'm not sure if that's a roadmapped plan

**Comment by spxtr** [comment]
I'm conflicted about this particular case. I do agree that it's nice to have the same developer experience for all the repos, but I don't think we should wall ourselves off from using native GitHub tooling because we made our own a few months before they made theirs.

It's going off on a tangent from this PR though.

> I keep hearing mention of eventually wanting to drive teams from files vs just leaning on githubs teams but I'm not sure if that's a roadmapped plan

We'll still be using GitHub teams, we'll just keep the source of truth in files and sync them regularly.

**Comment by xiangpengzhao** [comment]
I wonder why we make such teams private. Any reasons?

**Comment by spxtr** [comment]
> I wonder why we make such teams private. Any reasons?

GitHub makes them private with no way to make them public, I think.

**Comment by BenTheElder** [comment]
Not sure what we want to do about this or close, at least we have CODEOWNERS/OWNERS now
