### ISSUE TITLE
ci-test-infra-bazel is failing

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#3617]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-test-infra-bazel/56785/

/assign @rmmh 
kettle?

**Comment by rmmh** [comment]
This was broken by #3447

/unassign
/assign fejta

**Comment by fejta** [comment]
Looks like a bug in kettle's build file, forked off that issue and assigned it to you Ryan
Will look into the verify-pylint issue

**Comment by spxtr** [comment]
kettle bug fixed, was just missing a dep.
