### ISSUE TITLE
Expand submit-queue CI results

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#3619]
Based on discussion with @fejta we'd like to add a section similar to the non-queue-blocking builds at https://submit-queue.k8s.io/#/e2e but for pre-submit batch checks (and later potentially others). This info exists in prow/deck but there is not a similar display specifically for most recent results.

See #3600 for previous attempt. Instead of this, the idea is to specifically show for batch jobs.

Edit: [Proposal Here](https://docs.google.com/document/d/1slcGFpLrrIc-zPV4j-gd_7LVwb18hlLyZfobOKWPtPw/)

**Comment by BenTheElder** [comment]
After tinkering on this a bit I think I'd like to refactor submit-queue to have a more generic CI dashboard where the E2E results page exists currently.

I'm thinking something *like this*, perhaps with more categories for non-batch presubmit jobs, post-submit jobs, and periodic jobs:
<img width="1313" alt="screen shot 2017-07-25 at 9 41 50 pm" src="https://user-images.githubusercontent.com/917931/28604777-24626e42-7182-11e7-8bd9-836ba0d04b43.png">

Under the hood I'd like to fix https://github.com/kubernetes/test-infra/issues/3661 and clean up the "google internal ci" methods / endpoints and more generically track recent CI results by job type.

/cc @rmmh @fejta @cjwagner @kargakis

**Comment by fejta** [comment]
Great suggestion and like the screenshot!

**Comment by cjwagner** [comment]
This would be a nice improvement.

**Comment by BenTheElder** [comment]
https://docs.google.com/document/d/1slcGFpLrrIc-zPV4j-gd_7LVwb18hlLyZfobOKWPtPw/edit#

**Comment by BenTheElder** [comment]
closed in #3765

**Comment by fejta** [comment]
Wooo!
