### ISSUE TITLE
Prow Data URL and batch merges are coupled

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#3624]
mungegithub / submit-queue has a flag `--batch-url` which is overloaded to both set the url for fetching batch results from prow/deck and to `!= ""` meaning batch merge handling is enabled.
The `batch-url` currently in use for kubernetes actually contains more than just batch jobs. @rmmh suggested using two flags instead.

I'll put up a PR shortly.

**Comment by kargakis** [comment]
Are you going to make deck expose just batch jobs under a different endpoint?

**Comment by BenTheElder** [comment]
I think this particular change is a good plan regardless but what I'd like
to do is have submit-queue expose more prow job types similar to what's in
the e2e tab now, ideally with more info (recent job pass rate?). I'll
expand more on that at https://github.com/kubernetes/test-infra/issues/3619
which ought to be rewritten a bit before implementing.

On Jul 21, 2017 03:11, "Michail Kargakis" <notifications@github.com> wrote:

Are you going to make deck expose just batch jobs under a different
endpoint?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/test-infra/issues/3624#issuecomment-316963251>,
or mute the thread
