### ISSUE TITLE
bazelbulid image is too opinionated

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3629]
There are also too many versions of the image running around.

/assign
/cc @spxtr @ixdy

**Comment by ixdy** [comment]
what do you mean by "too opinionated?"

**Comment by fejta** [comment]
It has a bunch of "helpful" defaults which in an attempt to save characters make it a) hard to understand how the image works b) hard to make it do something different and c) results in leaking a bunch of global state

I want prow's job definitions to explicitly state how it interacts with bootstrap.
