### ISSUE TITLE
Make minimum confidence in golint configurable

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3632]
linting while nice to have is not a hard requirement for merging code today and can be regarded as too opinionated. It can also get noisy w/o adding much value, eg. https://github.com/kubernetes/kubernetes/pull/49289#issuecomment-316815435. Also, I am not sure if I wouldn't get all those comments was there a doc.go in place ... It would be nice to dismiss those comments by having the bot removing them. I think the Review API has a dismiss review option but I am not sure what happens to those comments.. I don't feel strong, just wanted to bring this up.

@spxtr 

/area prow

**Comment by spxtr** [comment]
The review API's dismiss review option is for reviews that request changes. Anyone with write access can dismiss such a review, the idea being that if the reviewer is OOO you should still be able to merge. See [the docs](https://help.github.com/articles/dismissing-a-pull-request-review/).

There is one thing we can do to cut back on comments like the one you ran into in your PR. We can set a [minimum confidence](https://godoc.org/github.com/golang/lint#Problem) on the lint warnings. That particular warning has a confidence of [0.2](https://github.com/golang/lint/blob/c5fb716d6688a859aae56d26d3e6070808df29f7/lint.go#L416), which is quite low.

**Comment by kargakis** [comment]
Disregard my Review comment. Minimum confidence sgtm, we may also want to allow devs configuring it, eg. /lint 0.2 or /lint min_conf=0.2
