### ISSUE TITLE
Streaming log output

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3633]
When I click on one of the burger icons at http://prow.k8s.io/ it displays the latest `kubectl log` output for that pod.

I would like to switch this to use `kubectl -f log` with HTTP chunked transfer encoding, so that it continues streaming output until I close the page and/or the pod completes.

https://en.wikipedia.org/wiki/Chunked_transfer_encoding

**Comment by BenTheElder** [comment]
This is done in #4156 except for making deck etc use it. :tada:

**Comment by BenTheElder** [comment]
This went a bit stale, we have streaming log output in deck, though not by default (add `&follow=true` to log links) but somewhere along the line this times out after ~30s. I'd guess the ingress.
