### ISSUE TITLE
Impossible to debug lack of permissions on a github token

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3634]
hook sets a logger on the github client only in local mode so it's impossible to debug things when running in normal mode, eg. lack of permissions on the github oauth token.

/area prow

**Comment by kargakis** [comment]
[All errors from the handlers are ignored today](https://github.com/kubernetes/test-infra/blob/bf102b9799a224808bdcde5de29cc6f985ead268/prow/hook/server.go#L90-L126) ...

**Comment by spxtr** [comment]
I set the logger always in #3622.

**Comment by kargakis** [comment]
Awesome. There is another issue here which I am going to send a PR for shortly so I won;t forget.
