### ISSUE TITLE
Example in k8s-merge-robot comments about mentioning a sig is incorrect

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3646]
See in one of the newest issue: https://github.com/kubernetes/kubernetes/issues/49427#issuecomment-317142974

`e.g., @kubernetes/contributor-experience-<group-suffix> to notify the contributor experience sig`

It should be `@kubernetes/sig-contributor-experience-<group-suffix>`. Notice the lost `sig-`. Incorrect example can be misleading :)

/cc @crimsonfaith91

**Comment by crimsonfaith91** [comment]
@xiangpengzhao This has been fixed last week, but the change is not deployed yet.

**Comment by xiangpengzhao** [comment]
Oh, thanks! I didn't notice the patch :)
/close

**Comment by crimsonfaith91** [comment]
https://github.com/kubernetes/test-infra/pull/3510
