### ISSUE TITLE
Record/display cluster vital statistics at a glance for each run

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#366]
Request: After a cluster has been brought up, record:
- the actual cluster version the cluster thinks it's running (not the version we attempted to launch, these can be sometimes different if there's a bug/misconfiguration in a GKE test, for instance)
- the docker version
- the kernel uname string of the nodes
- ... etc.

and be able to show those at a glance. I suspect a lot of this could be done with log post-processing, but some of it is difficult to find at all.

cc @cjcullen

**Comment by spxtr** [comment]
Would it be worth just doing `kubectl describe no > _artifacts/nodes.txt` after turning up the cluster? I think that has docker version, kubelet version, and OS.

**Comment by zmerlynn** [comment]
That's probably sufficient. Or a `kubectl get -oyaml nodes` so we have it raw.

**Comment by ixdy** [comment]
`kubectl version` gives the client (i.e. test) version and api-server versions, and is already in the build log, but putting that in a separate file would probably be easy and a good idea, too.

**Comment by zmerlynn** [comment]
Yeah, I'm aware of the limited info in the build-log. That one is readable, and gets you the master version, certainly. You have to scrounge for it a bit, though.
