### ISSUE TITLE
Bot doesn't remove "lgtm" after the PR has changed in kubernetes/kubernetes.github.io

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3668]
See: https://github.com/kubernetes/kubernetes.github.io/pull/4430

I made some changes in this PR and pushed them. But bot didn't remove `lgtm` after that. It should, right?

/cc @crimsonfaith91

**Comment by spxtr** [comment]
That's done by a munger right now. @nlandolfi may be interested in redoing that munger in prow?

**Comment by krzyzacy** [comment]
do we even have a munger for that repo?

**Comment by spxtr** [comment]
No.

**Comment by nlandolfi** [comment]
Yes I am interested!

**Comment by nlandolfi** [comment]
Will likely create some sort of design document perhaps first, but looking to implement as prow plugin I think

**Comment by spiffxp** [comment]
can we close this as "works as intended" or is there something to be done here?

**Comment by nlandolfi** [comment]
no need to keep open on my account

**Comment by xiangpengzhao** [comment]
Thanks!
/close
