### ISSUE TITLE
SQ constantly comments approval-handler messages every loop

### ISSUE THREAD

**Issue by yutongz** [kubernetes/test-infra#3677]
I am deploying submit-queue for istio, everything looks fine except when I enable approval-handler, sq keeps commenting with the same message about approval notification [pr](https://github.com/istio/test-infra/pull/293)
foxish pointed me to [this issue](https://github.com/kubernetes/contrib/issues/1901), so I tried to replace the botName with our bot except test files, but still get the same problem. 
By the way, I can't build mungegithub binary with "make mungegithub"  so I use bazel build to get binary and build docker image, I guess it doesn't affect everything but just want you guys know.
Any idea?

**Comment by yutongz** [comment]
@foxish @apelisse

**Comment by foxish** [comment]
cc/ @cjwagner

**Comment by cjwagner** [comment]
The bot names should definitely be parameterized. Did you change https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/matchers/comment/interactions.go#L67?

**Comment by kargakis** [comment]
> The bot names should definitely be parameterized. Did you change https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/matchers/comment/interactions.go#L67?

Hrm, can we move those into the munger config?

**Comment by kargakis** [comment]
@stevekuznetsov fyi

**Comment by yutongz** [comment]
OK, I think I figured out how to teach mungegithub recognize our bot name. I am going to create a pr to make bot name configurable.

**Comment by stevekuznetsov** [comment]
@yutongz we've got a PR in the works as well -- if you have not yet started, it may save you time. We will try to deliver it soon

**Comment by yutongz** [comment]
@stevekuznetsov  that will be awesome, thanks!

**Comment by kargakis** [comment]
This is still an issue ...

**Comment by stevekuznetsov** [comment]
@kargakis were you able to determine why?

**Comment by kargakis** [comment]
Haven't looked yet, no. I want to setup a test cluster but won't get to it before Monday morning.

**Comment by stevekuznetsov** [comment]
I think [these](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/matchers/comment/interactions.go#L65-L73) also need to be configurable

**Comment by stevekuznetsov** [comment]
There's a couple of those:
```
mungegithub/mungers/matchers/comment/interactions.go:67:	return AuthorLogin("k8s-merge-robot")
mungegithub/mungers/matchers/event/event.go:110:	return Actor("k8s-merge-robot")
mungegithub/mungers/matchers/interactions.go:96:	return AuthorLogin("k8s-merge-robot")
```

**Comment by stevekuznetsov** [comment]
Hmm, it looks like there are two very different ways to match comments and my PR only addressed one of them. I'll work on that.
