### ISSUE TITLE
e2e-runner.sh no longer compatible with v1.2 and v1.3.4 hack/e2e.go 

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#368]
Those versions of hack/e2e.go do not recognize the --dump flag.

**Comment by fejta** [comment]
My plan here is to put everything the runner needs inside an image.

I'm going to start by:
* Creating a kubekins-e2e image which has a few utilities like e2e-runner, hack/e2e.go, upload-to-gcs, etc.
* Update dockerized-e2e-runner.sh over to call this image instead of pulling e2e-runner.sh
* Update e2e-runner.sh to try and find its dependencies like hack/e2e.go inside the image before pulling them from head.
* Change all jobs to pull dockerized-e2e-runner.sh from test-infra

**Comment by ixdy** [comment]
The GKE upgrade tests are all broken, too.
