### ISSUE TITLE
[sig-network dashboard] release tabs match nothing

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#3684]
In #3658 couple release specific tabs were added to [sig-network dashboard](https://k8s-testgrid.appspot.com/sig-network#). But I just realized that since we only added the keyword "[sig-network]" on upstream, those release branches will still match no tests...For instance, [gce-release-1-7 tab](https://k8s-testgrid.appspot.com/sig-network#gce-release-1-7) is empty.

Couple ideas in mind:
- Remove those release tabs to prevent confusion.
- Cherrypick the keyword into release branches.
- Use some other regex instead of that keyword.

cc @bowei @cmluciano @xiangpengzhao @krzyzacy

**Comment by krzyzacy** [comment]
I don't think it's a testgrid issue, it's probably sig-network and probably need to be in the main repo :-)

**Comment by MrHohn** [comment]
> I don't think it's a testgrid issue, it's probably sig-network and probably need to be in the main repo :-)

Agree...I think I'd remove those tabs first and bring the discussion into sig email thread or sig meeting.
