### ISSUE TITLE
submit-queue: How do we want to handle OWNERS in vendored projects?

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#3694]
We have enabled the submit queue in a repository that vendors repositories that contain OWNERS files. This is problematic as those files can contain developers that are not active in the downstream project, and therefore cannot be or should not be assigned for review/approval.

I can see two approaches:

 - ignore OWNERS inside of vendor directories
 - when failing to assign someone as a reviewer or approver, try someone else

The top approach is probably the simplest but may not be the best as developers that _are_ active in both repositories would be the best choice for review or approval on a pull request touching vendored files. If we ignore OWNERS in the vendored code entirely, we get very poor specificity on reviewers and approvers for the entire `vendor/` directory. 

/cc @kargakis @eparis

**Comment by eparis** [comment]
If we try to use OWNERS inside vendor'd projects for assignment OWNERS_ALIASES won't work correctly since that is hard coded to a single file.

**Comment by cblecker** [comment]
I'd suggest that it's best to filter vendor/ completely as you shouldn't make changes to vendored files directly. Make changes in upstream and then bump your dependency.

**Comment by stevekuznetsov** [comment]
@cblecker that may be a perfect world but is not something that most projects can do.

**Comment by spxtr** [comment]
> @cblecker that may be a perfect world but is not something that most projects can do.

I think we do that, don't we?

**Comment by stevekuznetsov** [comment]
Off of the top of my head I know there is a carry in the vendored `glog` code. I'm just saying, ignoring `vendor/` is less useful than _e.g._ #3766

**Comment by spiffxp** [comment]
Related: what should I be doing with vendored OWNERS files that are still using `assignees`? I'm opting to just search/replace everything for now.

**Comment by stevekuznetsov** [comment]
https://github.com/kubernetes/test-infra/issues/3766 merged, which fixed the most crucial issue with vendored OWNERS, at least for us -- but we can keep this issue open as that PR does not attempt to address `vendor/` specifically

**Comment by stevekuznetsov** [comment]
@cjwagner

**Comment by cjwagner** [comment]
Currently, we filter OWNERS files to only include repo collaborators. This means that only users who are repo collaborators will be considered in `vendor/` OWNERS files, if a user listed in such a file is not a kubernetes org member or a repo collaborator the user will be ignored.

**Comment by stevekuznetsov** [comment]
@cjwagner right, that was my patch that added that filtering as per above -- I kept this open since it only answered this question obliquely :)

**Comment by cjwagner** [comment]
I meant to indicate that Prow is doing this now as well, but I was unclear :stuck_out_tongue_closed_eyes: 
I agree that we should keep this open, skipping `vendor/` entirely might still be preferable.
