### ISSUE TITLE
Closing pull requests still doesn't work

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3697]
Tried both [downstream](https://github.com/openshift/origin/pull/15403#issuecomment-317963842) and [upstream](https://github.com/kubernetes/kubernetes/pull/48217#issuecomment-317964800) with the same result.

Log from our hook instance
```
{"author":"kargakis","level":"info","msg":"Issue comment created.","org":"openshift","pr":15403,"repo":"origin","time":"2017-07-26T06:45:53Z","url":"https://github.com/openshift/origin/pull/15403#issuecomment-317963842"}
{"author":"kargakis","level":"info","msg":"Closing PR.","org":"openshift","plugin":"close","pr":15403,"repo":"origin","time":"2017-07-26T06:45:53Z","url":"https://github.com/openshift/origin/pull/15403#issuecomment-317963842"}
{"client":"github","level":"info","msg":"ClosePR(openshift, origin, 15403)","time":"2017-07-26T06:45:53Z"}
{"author":"kargakis","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3\"}","level":"error","msg":"Error handling IssueCommentEvent.","org":"openshift","plugin":"close","pr":15403,"repo":"origin","time":"2017-07-26T06:46:00Z","url":"https://github.com/openshift/origin/pull/15403#issuecomment-317963842"}
```

/area prow
cc @stevekuznetsov

**Comment by kargakis** [comment]
Can we give the bug label a nice red color? :)

**Comment by xiangpengzhao** [comment]
Yeah https://github.com/kubernetes/test-infra/pull/3641 was merged but seems like it doesn't work as expected. 

See Christoph's testing PR: https://github.com/kubernetes/kubernetes/pull/49517#issuecomment-317931030

cc @cblecker

**Comment by xiangpengzhao** [comment]
xref: https://github.com/kubernetes/test-infra/issues/2839 https://github.com/kubernetes/test-infra/issues/2863

**Comment by cblecker** [comment]
/assign
Will look at this today.

**Comment by cblecker** [comment]
@spxtr can you confirm we're seeing the same thing on the kubernetes org prow?

**Comment by cblecker** [comment]
Found it. Typo in API apth. Fix in #3715

**Comment by spxtr** [comment]
Deployed. Try again?

**Comment by cblecker** [comment]
Fixed :)
https://github.com/kubernetes/kubernetes/pull/49517

**Comment by spxtr** [comment]
Thanks for the fix :)

**Comment by xiangpengzhao** [comment]
:+1:

**Comment by cblecker** [comment]
Full disclosure: This was a total self-serving fix to allow me to close PRs like https://github.com/kubernetes/kubernetes/pull/49086 🔥 😛
