### ISSUE TITLE
Prometheus Metrics for Robot Commands

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#3700]
It would be cool to see Prometheus metrics we could expose through Velodrome for robot commands like `/retest` to see how users (or a specific user) interact with the robots.

/cc @deads2k @eparis

**Comment by spxtr** [comment]
Right now that information is stored for a week or so in logs, but we should try to make it public somehow. I agree.

**Comment by kargakis** [comment]
Cardinality becomes unreasonably high if we include individual users as an axis in these metrics.

This issue is possibly a dupe of https://github.com/kubernetes/test-infra/issues/2699.

**Comment by stevekuznetsov** [comment]
We've got this in Velodrome now, right, @spiffxp ?
