### ISSUE TITLE
KUBE_GCE_ZONE not being set correctly inside kubetest for jobs using non-default zone

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#3710]
KUBE_GCE_ZONE is showing value "us-central1-f" (which is the default [set inside kubetest Dockerfile](https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/Dockerfile#L48)) even though some jobs are overriding it with a different value through `--gcp-project`. I verified it for a couple of jobs (from within the container).

These issues are happening a bit too frequently now. Also, this is another instance where a little more care would've prevented it :)

Multiple jobs seem affected:

```
ci-kubernetes-e2e-gci-gke-prod
ci-kubernetes-e2e-gci-gke-prod-parallel
ci-kubernetes-e2e-gke-prod
ci-kubernetes-e2e-gke-prod-parallel
ci-kubernetes-e2e-mlkube-gke
ci-kubernetes-kubemark-gce-scale
ci-kubernetes-e2e-gke-1-5-1-6-cvm-kubectl-skew
ci-kubernetes-e2e-gke-1-5-1-6-gci-kubectl-skew
ci-kubernetes-e2e-gke-1-6-1-5-cvm-kubectl-skew
ci-kubernetes-e2e-gke-1-6-1-5-gci-kubectl-skew
ci-kubernetes-e2e-gke-1-6-1-7-cvm-kubectl-skew
ci-kubernetes-e2e-gke-1-6-1-7-cvm-kubectl-skew-serial
ci-kubernetes-e2e-gke-1-6-1-7-gci-kubectl-skew
ci-kubernetes-e2e-gke-1-6-1-7-gci-kubectl-skew-serial
ci-kubernetes-e2e-gke-1-7-1-6-cvm-kubectl-skew
ci-kubernetes-e2e-gke-1-7-1-6-cvm-kubectl-skew-serial
ci-kubernetes-e2e-gke-1-7-1-6-gci-kubectl-skew
ci-kubernetes-e2e-gke-1-7-1-6-gci-kubectl-skew-serial
ci-kubernetes-e2e-gke-master-new-cvm-kubectl-skew
ci-kubernetes-e2e-gke-master-new-gci-kubectl-skew
ci-kubernetes-e2e-gke-new-master-cvm-kubectl-skew
ci-kubernetes-e2e-gke-new-master-gci-kubectl-skew
ci-kubernetes-e2e-gce-enormous-deploy
ci-kubernetes-e2e-gce-enormous-teardown
ci-kubernetes-e2e-gce-large-correctness
ci-kubernetes-e2e-gce-large-performance
ci-kubernetes-e2e-gce-scalability-release-1-6
ci-kubernetes-e2e-gce-scalability-release-1-7
ci-kubernetes-e2e-gce-scale-correctness
ci-kubernetes-e2e-gce-scale-performance
ci-kubernetes-e2e-gci-gce-scalability-release-1-6
ci-kubernetes-e2e-gci-gce-scalability-release-1-7
ci-kubernetes-e2e-gci-gke-prod-smoke
ci-kubernetes-e2e-gke-large-correctness
ci-kubernetes-e2e-gke-large-deploy
ci-kubernetes-e2e-gke-large-performance
ci-kubernetes-e2e-gke-large-teardown
ci-kubernetes-e2e-gke-prod-smoke
ci-kubernetes-e2e-gke-scale-correctness
(potentially more)
```

cc @fejta @krzyzacy

**Comment by krzyzacy** [comment]
Does gke job even care about this env? I thought this matches the previous behavior when we set `ZONE=some-zome` through env files for gke jobs.

I'll check the gce ones.

**Comment by shyamjvs** [comment]
fyi - @kubernetes/sig-scalability-misc @gmarek @wojtek-t 
(since scalability jobs are among the ones affected)

**Comment by shyamjvs** [comment]
@krzyzacy Like you said, this probably doesn't affect gke tests (luckily due to using a different env var), but note that we're setting this variable for gke jobs too due to Dockerfile (and it can potentially be misused).

**Comment by krzyzacy** [comment]
@shyamjvs I checked https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-release-1-7/137?log#log, it uses the right zone, what was the job you've seen?

**Comment by krzyzacy** [comment]
oh, if you mean the printed out KUBE_GCE_ZONE from the log, that will be overwritten in kubetest and will not actually be used. We'd remove the default from Dockerfile to reduce the confusion.

**Comment by shyamjvs** [comment]
How did you check? The logs ofc would show the right one in --gcp-zone flag. However it is not set as env var correctly within the container. I checked by `docker exec`ing into the container.

**Comment by krzyzacy** [comment]
`docker exec container printenv` seems not giving the right thing. (Does not even show `PROJECT`) But the jobs seems unaffected and using the right env. Will keep an eye here.
