### ISSUE TITLE
Refactor --json=true to --deprecated

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3711]
/assign @krzyzacy 

Use --json by default
Refactor any bootstrap.py commands without --json to add --deprecated and Remove --json from any commands.

**Comment by krzyzacy** [comment]
I figured I can delete the `--json` entirely rather than another round of refactor :-) Will handle this.

**Comment by fejta** [comment]
Sweet!

**Comment by krzyzacy** [comment]
dead
