### ISSUE TITLE
cmd/deck job "finished" field should contain date

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#3714]
Currently `prow/cmd/deck` has a `finished` field [that only contains `HH:MM:SS`](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/jobs.go#L192) which is ambigious. To construct the actual finished timestamp you currently need to add `duration` to `started`. As far as I can tell the `finished` field should either be removed or updated to contain a full timestamp similar to `started`.

/area prow

**Comment by BenTheElder** [comment]
@rmmh It looks like you first added this field, is there a reason behind the current format? What do you think? I'm currently just using duration and started but this seems unnecessary.

**Comment by rmmh** [comment]
If you want to use it programmatically, have it export the timestamp itself.

**Comment by rmmh** [comment]
I'm fine with removing it too if it's unused.

**Comment by BenTheElder** [comment]
I'd like to use it programmatically, so far I haven't found it being used anywhere. Deck only exposes start and duration on the web side. I will open a PR.

**Comment by spxtr** [comment]
It was a mistake to use strings for these. Times should be RFC 3339 and durations should be nanoseconds. The javascript handling them should covert to local times and pretty up the durations themselves.
