### ISSUE TITLE
Make a kubekins-e2e-prow:stable tag?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#3720]
Rather than every time s/kubekins-e2e-prow:.*/kubekins-e2e-prow:v2017-07-newimage? Or have some default somewhere?

On the other side this might be less explicit.

cc @yguo0905 @fejta @spxtr @zmerlynn Open this issue for more thoughts on this.

**Comment by fejta** [comment]
I thought we liked the idea of seeing a PR whenever we bump the image version?

**Comment by fejta** [comment]
AKA that way we can track changes to a commit in test-infra, rather than a random push happening by who knows who for who knows what reason

**Comment by zmerlynn** [comment]
I like the review nature, but I think some way to make these symbolic in the config would be nice.

**Comment by krzyzacy** [comment]
I guess we'd wait for podpreset - and agree that multiple people step on each other will be bad.

**Comment by fejta** [comment]
We could open the anchor bag of worms?
