### ISSUE TITLE
mungegithub: extract hardcoded list of CLA labels into configurable list

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3724]
[mungegithub currently looks for one of three CLA labels](https://github.com/kubernetes/test-infra/blob/d0ba6a08a8cbfd1ed00b7cbfc20f79a5e997ddd8/mungegithub/mungers/submit-queue.go#L969):
- `cla: human-approved`
- `cla: yes`
- `cncf-cla: yes`

a) do we still need to look for all three, or could we just use the `cncf-cla` label?
b) if not, would it be worth passing in the labels as a configurable list instead of hardcodes?

**Comment by spiffxp** [comment]
@kubernetes/sig-contributor-experience-misc

**Comment by cblecker** [comment]
The cla one is the old google bot which I think can go.

The human approved one.. I'm not quite sure what the use case would be for that, or if we permit exceptions to signing the CNCF-CLA. Nothing mentioned here about that: https://github.com/kubernetes/community/blob/master/CLA.md
cc: @sarahnovotny 

Either way, it should probably be configurable.

**Comment by xiangpengzhao** [comment]
If some guys want their PR merged when they are still in the progress of signing CLA but not finished, assignees can label `cla: human-approved` for them.

But this might lead to the PR has both `cla: human-approved` and `cncf-cla: yes` finally.

See: https://github.com/kubernetes/kubernetes/labels/cla%3A%20human-approved

**Comment by xiangpengzhao** [comment]
What if the author fails to sign CLA but the PR is merged with `cla: human-approved` finally?

**Comment by xiangpengzhao** [comment]
>do we still need to look for all three, or could we just use the cncf-cla label?

IMO, at least, we shouldn't look for `cla: yes` as it's no longer used. I'm curious about that can a PR be merged if the author only signs old cla but not cncf-cla?

```go
	// Must pass CLA checks
	if gateCLA {
		if !obj.HasLabel(claYesLabel) && !obj.HasLabel(claHumanLabel) && !obj.HasLabel(cncfClaYesLabel) {
			sq.SetMergeStatus(obj, noCLA)
			return false
		}
	}
```

**Comment by foxish** [comment]
/cc @yutongz 
Is the old CLA label still relevant for you guys?

**Comment by yutongz** [comment]
We are not in cncf right now, so still need old one. I agree we can make it configurable. TBH, I like "human-approved" as a hacker to get cla done quickly.

**Comment by sarahnovotny** [comment]
@yutongz, can you elaborate?  being "in the CNCF" is not a requirement of signing the CNCF CLA.  We *need* to standardize on tooling and the CNCF CLA or we run legal risks with contributions.

**Comment by foxish** [comment]
@sarahnovotny, Yutong works on Istio that's also using mungegithub, not K8s. The manual override label is still useful I think. Maybe what we need is parameterization here as well, to allow different bots to respect different sets of labels.

**Comment by spiffxp** [comment]
Making the set of labels configurable and not hardcoded seems like the path forward then.

@sarahnovotny re: legal risks, does this mean we should pull support for the `cla: human-approved` label? [PR's that have `cla: human-approved` but not `cncf-cla: yes`](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+label%3A%22cla%3A+human-approved%22+-label%3A%22cncf-cla%3A+yes%22+sort%3Aupdated-desc) looked to be not a thing for nearly a year, although we've merged two in the last month

pinging @eparis to ask what happened with https://github.com/kubernetes/kubernetes/pull/49447

**Comment by cblecker** [comment]
With mungegithub on the way out and tide being the way of the future, I don't think this is relevant anymore. Would you agree, @spiffxp?

**Comment by spiffxp** [comment]
/close
I guess we can close this.  I'm guessing we'll want some way of telling a user how to acquire the needed labels, in the same way that submit-queue occasionally updates its status with specific next steps.  But that's orthogonal
