### ISSUE TITLE
Associated issues with a full url aren't recongnizable

### ISSUE THREAD

**Issue by php-coder** [kubernetes/test-infra#3737]
The robot complains that the PR doesn't have associated issue while actually it has (see the comment `Fixes #13390` in the description) https://github.com/openshift/origin/pull/15481#issuecomment-318364654

Looks like the regexp that is used for checking for associated issues always implies that the repository belongs to the `kubernetes` user: https://github.com/kubernetes/test-infra/blob/105d1bd6b1a59ab7ea649e9424cd96d59b4f68d8/mungegithub/mungers/approval-handler.go#L42

Could we make it configurable? Otherwise this check is useless for non-kubernetes infrastructures.

CC @kargakis

**Comment by stevekuznetsov** [comment]
xref #3704

**Comment by kargakis** [comment]
> xref #3704

Yeah, we first want to make this configurable but eventually it would be nice to fix the regexp too.

**Comment by php-coder** [comment]
There is a workaround: don't specify a full url but use only an issue number. For example, this one wouldn't work `Fixes https://github.com/openshift/origin/issues/13390` while this one would: `Fixes #13390`
