### ISSUE TITLE
prow: add a test to blocker list per-PR when the test is triggered manually

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#3740]
It would be cool if, when a PR has a non-blocking test triggered for it manually, that either this test would automatically become part of the default trigger set and become blocking for the PR or if there were a bot command to add it to the list as well.

/area prow
/cc @kargakis @bparees

**Comment by kargakis** [comment]
Seems like a munger issue. The easiest way I can think of is the SQ blocks on the context if the context exists in the PR, otherwise it is not.

/area mungegithub

**Comment by spxtr** [comment]
@rmmh I think was interested in this.

**Comment by stevekuznetsov** [comment]
Also necessary if a test gets selected by touching changed paths

**Comment by kargakis** [comment]
Dupe of https://github.com/kubernetes/test-infra/issues/1351
