### ISSUE TITLE
mungegithub: availability metric incorect

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#3775]
When we were seeing an outage due to Jenkins, loop frequency dropped to 0 but the availability metric stayed at 100% as seen [on `velodrome`](http://velodrome.k8s.io/dashboard/db/monitoring?from=1501155575516&to=1501187969790):

![screenshot from 2017-07-28 11-48-16](https://user-images.githubusercontent.com/7328370/28731914-a8eb5890-738a-11e7-8536-27de4be40933.png)

**Comment by spiffxp** [comment]
Technically speaking this is working as intended.  The submit queue's dashboard was _available_ it just wasn't doing any meaningful work.

**Comment by spiffxp** [comment]
That said, this little bump show up at all on https://storage.googleapis.com/kubernetes-test-history/k8s-queue-health.svg and the availability metric has been at 100% for so long that I question whether it's worth paying any attention to now.

**Comment by stevekuznetsov** [comment]
Ah, I see -- that makes sense. Not really  a bug then.
