### ISSUE TITLE
End centralized jenkins support after 1.9

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3778]
Jobs should run on prow, or sigs should create and maintain their own jenkins instance.

Google's GKE EngProd team intends to continue supporting the sig-testing prow rotation and end the jenkins rotation.

@kubernetes/sig-testing-proposals

**Comment by BenTheElder** [comment]
[All Test on Prow Design Doc](https://docs.google.com/document/d/1ih0Pogkdyo8QwmJUkJd4pgqmXnPb6vZnUEyb8vhMjJg/edit#heading=h.x9snb54sjlu9).
/assign
cc @krzyzacy

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/issues/3356 is now closed, all presubmit-blocking jobs will be back off of jenkins after https://github.com/kubernetes/test-infra/pull/5866 xref: https://github.com/kubernetes/test-infra/issues/5859#issuecomment-350128126

**Comment by BenTheElder** [comment]
Kubernetes has been running all blocking presubmits on Jenkins for release-1.7+ for a while now just fine. A few satellite repos still use Jenkins for presubmit and a few more things (mainly builds) are still on CI Jenkins. 

Moving any remaining kubernetes jobs off of both Jenkins instances should be straight forward but charts / cadvisor / heapster look a bit different. I've pinged some more people about this.

**Comment by BenTheElder** [comment]
Heh, missed closing this. There are no more Jenkins jobs. There are no more Jenkins clusters. Everything runs on Kubernetes :-)
