### ISSUE TITLE
Migrate soak jobs to prow and off centralized jenkins before end of 1.9 timeframe

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3779]
The GKE engprod team will stop supporting sigs running their testing on shared jenkins infrastructure after 1.8

Please migrate your jobs to prow. If this is infeasible for some reason please let sig-testing know what we need to add to prow and/or plan to create and maintain your own jenkins instance if we cannot come up with a solution kubernetes/test-infra#3778

This impacts the following jobs:
```
  "ci-kubernetes-soak-cos-docker-validation-deploy": {
  "ci-kubernetes-soak-cos-docker-validation-test": {
  "ci-kubernetes-soak-gce-1-7-deploy": {
  "ci-kubernetes-soak-gce-1-7-test": {
  "ci-kubernetes-soak-gce-1.4-deploy": {
  "ci-kubernetes-soak-gce-1.4-test": {
  "ci-kubernetes-soak-gce-1.5-deploy": {
  "ci-kubernetes-soak-gce-1.5-test": {
  "ci-kubernetes-soak-gce-1.6-deploy": {
  "ci-kubernetes-soak-gce-1.6-test": {
  "ci-kubernetes-soak-gce-2-deploy": {
  "ci-kubernetes-soak-gce-2-test": {
  "ci-kubernetes-soak-gce-deploy": {
  "ci-kubernetes-soak-gce-federation-deploy": {
  "ci-kubernetes-soak-gce-federation-test": {
  "ci-kubernetes-soak-gce-gci-deploy": {
  "ci-kubernetes-soak-gce-gci-test": {
  "ci-kubernetes-soak-gce-test": {
  "ci-kubernetes-soak-gci-gce-1-7-deploy": {
  "ci-kubernetes-soak-gci-gce-1-7-test": {
  "ci-kubernetes-soak-gci-gce-1.4-deploy": {
  "ci-kubernetes-soak-gci-gce-1.4-test": {
  "ci-kubernetes-soak-gci-gce-1.5-deploy": {
  "ci-kubernetes-soak-gci-gce-1.5-test": {
  "ci-kubernetes-soak-gci-gce-1.6-deploy": {
  "ci-kubernetes-soak-gci-gce-1.6-test": {
  "ci-kubernetes-soak-gke-deploy": {
  "ci-kubernetes-soak-gke-gci-deploy": {
  "ci-kubernetes-soak-gke-gci-test": {
  "ci-kubernetes-soak-gke-test": {
```

https://github.com/kubernetes/test-infra/issues/3774

**Comment by krzyzacy** [comment]
the soak test has been failing for ages... I doubt it still produces useful signals...  https://github.com/kubernetes/kubernetes/issues/47255

**Comment by krzyzacy** [comment]
@spiffxp I would vote for deleting those soak jobs... I believe we never looked at the 1.8 soak jobs...

**Comment by krzyzacy** [comment]
(nvm, I'll make soak behavior work within kubetest)
/area kubetest

**Comment by krzyzacy** [comment]
the only thing left are the federation ones, which will be gone once federation can be built with bazel

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/pull/5187 wiped the federation soak job, gonna close this.
