### ISSUE TITLE
Ability to abort a job (hermetic tests) run when a new commit is added to a PR.

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3788]
Split from https://github.com/kubernetes/test-infra/issues/3209

/area prow

**Comment by kargakis** [comment]
I started working on this one but I quickly realized that it's better to split plank into two separate controllers first and then proceeding with adding cancellation for Jenkins ([pods seem to be deleted once a ProwJob is marked with a completionTimestamp](https://github.com/kubernetes/test-infra/blob/32d3e7ed5d028c91f83200b6928b1f321c893675/prow/plank/controller.go#L345-L350) but I haven't tested pod jobs yet to confirm).

**Comment by kargakis** [comment]
@spxtr will two or more separate controllers touching different github contexts in a single PR be a problem?

**Comment by spxtr** [comment]
Nope, that should be fine.
