### ISSUE TITLE
prow: print config on startup or when reloaded

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3789]
Similar to the munger, it would be nice to print the config in each prow component log during both startup and when the config is updated.

/area prow

**Comment by kargakis** [comment]
Printing all the config at start-up is probably untenable. Printing the diff of the previous config and the current config on a reload of the agent is still a good idea.

**Comment by stevekuznetsov** [comment]
Still would be nice

/remove-lifecycle stale
