### ISSUE TITLE
PR dashboard only works with kubernetes

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3793]
https://k8s-gubernator.appspot.com/pr/google_cadvisor/1707

The google/cadvisor repo != the kubernetes/google_cadvisor repo

Gubernator should allow me to type /pr/kubernetes/test-infra/1234
/area gubernator
@rmmh

**Comment by fejta** [comment]
It is also really obnoxious that there's no consistent way to refer to a PR,

I expect /pr/kubernetes/kubernetes/1234 to take me to pr 1234 on the k8s/k8s repo.
Having a shortcut is fine, but it is pretty absurd to make tools have to understand that:
if repo == kubernetes/kubernetes=> /pr/1234
elif org == kubernetes => /pr/REPO/1234
else => /pr/ORG_REPO/1234

There should be a context-free way to construct a gubernator PR URL: /pr/ORG/REPO/NUMBER

**Comment by spxtr** [comment]
Dupe of #920?
