### ISSUE TITLE
Prow postsubmit job does not have proper gubernator link

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#3798]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/test-infra/ci-test-infra-bazel/57131/

should be 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-test-infra-bazel/57131/

**Comment by fejta** [comment]
/area prow

What do you mean by "prow postsubmit job?" Where did you get the incorrect link?

**Comment by spxtr** [comment]
I clicked on one and it took me [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-bazel-build-1-7/105/) which was right...

**Comment by krzyzacy** [comment]
the test-infra one is not right :-)

**Comment by spxtr** [comment]
Feel free to submit a patch to fix [this template](https://github.com/kubernetes/test-infra/blob/04e42754a071378351b19a1279b39e73232c0f9d/prow/config.yaml#L2) :)

**Comment by krzyzacy** [comment]
ouch... I feel dizzy reading through the template... and presubmit/postsubmit works differently... ahhh :disappointed:

**Comment by fejta** [comment]
yeah that line in the config is intense

**Comment by spiffxp** [comment]
would the template be easier if there was a `/logs` equivalent of the `/pr/org/repo/1234` mapping added to gubernator in https://github.com/kubernetes/test-infra/pull/3797 ?

**Comment by sebastienvas** [comment]
It does not seem to be a template issue. The url is not right when the job is pending not when the job is complete.

**Comment by sebastienvas** [comment]
Nevermind - does not seem to be the same issue.

**Comment by krzyzacy** [comment]
@BenTheElder does your bootstrap hack also helped this one?

**Comment by BenTheElder** [comment]
I think it may have, not sure.

**Comment by spiffxp** [comment]
/reopen
/remove-lifecycle rotten
/help
this is still an issue and seems like it would be an easy fix for a new contributor

clicking through random jobs on http://prow.k8s.io/?type=postsubmit the problem doesn't happen for kubernetes/kubernetes nor kubeflow/*, but does happen for kuberentes/test-infra

**Comment by nikhita** [comment]
>  this is still an issue and seems like it would be an easy fix for a new contributor

can we call this good-first-issue? :)

**Comment by BenTheElder** [comment]
the pod-utils should help with this, cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Is this an issue with the report template that you guys have in your config?

**Comment by BenTheElder** [comment]
I think so, switching to decorating the upload location and then having a reporter component leverage that should fix this reliably instead of trying to keep "fixing" that horrible template.

**Comment by fejta** [comment]
Can we please simplify the path logic to be org/repo rather than a bunch of weirdness depending on whether the org is kubernetes?

**Comment by stevekuznetsov** [comment]
@fejta +10000 -- that intent is why I called that optional org/repo segment the "legacy" approach in the pod utilities, thinking we'd move to a more sane one in the future sometime...
