### ISSUE TITLE
kubelet-gce-e2e-ci doesn't upload JUnit test results

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#38]
@pwittrock

**Comment by pwittrock** [comment]
Waiting for #26101

**Comment by pwittrock** [comment]
Fixed in  #26101 (I don't have access to close this issue)

**Comment by spxtr** [comment]
Awesome, thanks for taking care of this. I added you to test-infra-maintainers so you should be able to close issues and merge PRs and the like.

Now the node results will show up on [the 24-hour report](http://storage.googleapis.com/kubernetes-test-history/static/index.html) and I can add a tab to the testgrid as well.

**Comment by pwittrock** [comment]
Cool.  Thanks.
