### ISSUE TITLE
prow: Github's API endpoint is not configurable

### ISSUE THREAD

**Issue by fen4o** [kubernetes/test-infra#3805]
Right now GitHub's API endpoint is [hardcoded](https://github.com/kubernetes/test-infra/blob/186c8c1a7e6f6c1eb056a94f71347ecd91cec0cf/prow/github/client.go#L49) to `https://api.github.com`. This works great for the public GitHub, but for the Enterprise GitHub offering, the endpoint is [custom](https://developer.github.com/v3/enterprise/#endpoint-urls). 

Mungegithub supports GitHub Endpoint configuration via [CLI flag](https://github.com/kubernetes/test-infra/blob/186c8c1a7e6f6c1eb056a94f71347ecd91cec0cf/mungegithub/github/github.go#L398).

Both `hook` and `plank` talk to GitHub's API. I guess that there are two options for configuration:
CLI flag to both binaries or Prow's config.yaml file.

I would go for the config.yaml, because later, more Github [client options](https://github.com/kubernetes/test-infra/blob/186c8c1a7e6f6c1eb056a94f71347ecd91cec0cf/prow/github/client.go#L50-L53) can be configured without the need to add CLI flags to the binaries.

It would be great if someone can provide some suggestions and ideas before I create a PR for this issue.

**Comment by spxtr** [comment]
I normally try to limit CLI flags, but for this case I would be okay with one. We can make the default `https://api.github.com` so that most users do not need to set it at all. I would suggest this.

A config option is also fine, although I'm not sure we ever want to allow configuring the other options you linked.

**Comment by caiwei-ebay** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/git/git.go#L85

This file is still referencing "github.com" as default base.

**Comment by HerrmannHinz** [comment]
any update? GHE would be super nice.
