### ISSUE TITLE
Retry mechanism in plank

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3808]
We are seeing sparse 405s today from Github in the plank log[0] that have resulted in github contexts getting stale (eg. https://github.com/openshift/origin/pull/15537). We should either 1)  retry the failed github calls on the spot for some time, or 2) something that would be useful in general eventually is to switch the controller to use an informer and retry prowjobs that have returned errors during a sync. 2 means that we need fine-grained error handling and retry the gtihub call for a successful prowjob. 1 is much simpler and is probably the right solution at least for now. 

[0]
```
{"error":"errors syncing: [], errors reporting: [error setting status: status code 405 not one of [201], body: \u003chtml\u003e\r\n\u003chead\u003e\u003ctitle\u003e405 Not Allowed\u003c/title\u003e\u003c/head\u003e\r\n\u003cbody bgcolor=\"white\"\u003e\r\n\u003ccenter\u003e\u003ch1\u003e405 Not Allowed\u003c/h1\u003e\u003c/center\u003e\r\n\u003chr\u003e\u003ccenter\u003enginx\u003c/center\u003e\r\n\u003c/body\u003e\r\n\u003c/html\u003e\r\n]","level":"error","msg":"Error syncing.","time":"2017-07-31T16:53:42Z"}
```

/area prow

cc: @deads2k @stevekuznetsov @spxtr

**Comment by spxtr** [comment]
> 1) retry the failed github calls on the spot for some time

We retry 500s and transport failures several times. I don't think we're supposed to ever retry 405s. It's just annoying that GitHub returned it.

> 2) something that would be useful in general eventually is to switch the controller to use an informer and retry prowjobs that have returned errors during a sync

This is a good basis for an eventual rewrite of plank.
