### ISSUE TITLE
Please port *-gke-ubuntustable-* jobs to correct format

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#3822]
Looking at blame, it looks like there have been a number of (mostly accidental) violations of the "DO NOT EDIT" on these jobs. However, more importantly, I believe on the GKE side all of these jobs can be ported to the GKE deployer. I don't have a lot of context with experiment/generate_tests.py, though. @yguo0905, can you help out?

c.f. #3818 for an example port (and #3819 for a follow-on to that).

In particular, for GKE:
* `--deployment=gke`
* There really shouldn't be a need for an env file, but it's fine for now if there is (for instance, the upgrade tests still use one)
* Give your GKE projects to Boskos, unless there's special whitelisting / quotas on them.

**Comment by yguo0905** [comment]
`experiment/generate_tests.py` generates configs from [experiment/test_config.yaml](https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml).

Looks like we should
- Add `--deployment=gke` to https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml#L559, change https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml#L597 to `-gcp-node-image=ubuntu`, and regenerate the configs.
- Add the projects to `boskos/resources.json`

Does this sound good?

**Comment by yguo0905** [comment]
Generally speaking, for any flag/env changes (adding/removing flag/env and converting between them), we could just change the corresponding ones in `experiment/test_config.yaml` and regenerate the tests.

**Comment by zmerlynn** [comment]
That sounds reasonable, yeah. I can see if I can do it myself, since I'm thick in the conversion (and have #3819 outstanding, which handles another bit).

**Comment by yguo0905** [comment]
Thanks! Let me know if there's any issues.

The command for generating the tests is at https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml#L18-L21.

**Comment by zmerlynn** [comment]
Will send it back if I have trouble, and send PRs to you. Thanks!

**Comment by zmerlynn** [comment]
This was fixed by #3957, closing!
