### ISSUE TITLE
Live log link is hardcoded to k8s prow

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#3829]
Istio has their own prow instance but gubernator doesn't show live logs from their jobs because they're not running on the k8s prow instance. [This line](https://github.com/kubernetes/test-infra/blob/f927186f10ea03cda20ae81c28e6d21a780135a6/gubernator/view_build.py#L69) reveals that it's hardcoded to look at our instance.

Is there a not-nasty way to fix this?

cc @sebastienvas 
/area prow
/area gubernator
/assign @rmmh

**Comment by sebastienvas** [comment]
Also as you can see in https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/517/istio-presubmit/146/, some of the fields are not populated properfly.

**Comment by nlandolfi** [comment]
as a follow up to Seb -- the fields you are referring to are the refs? i.e., the "master:sha,pr#:sha" link)

**Comment by kargakis** [comment]
cc @stevekuznetsov who made this work for us yesterday

https://openshift-gce-devel.appspot.com/

**Comment by stevekuznetsov** [comment]
Unfortunately that "work" is at the first phase of just hardcoding it in the other direction. There are a _lot_ of strings in Gubernator that are not friendly to other projects

**Comment by BenTheElder** [comment]
view_base seems to be loading some config for the jobs on import, can we also load a config for the URL there and plumb it through?
