### ISSUE TITLE
apps/v1beta2 is not enabled for submit queue pull-kubernetes-e2e-gce-etcd3 test

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#3841]
One of my PRs is adding a new apps/v1beta2 subresource. I am able to get the e2e test passed using local cluster by enabling apps/v1beta2: `RUNTIME_CONFIG="apps/v1beta2" hack/local-up-cluster.sh
`.

However, the test failed for `pull-kubernetes-e2e-gce-etcd3` test due to apps/v1beta2 is not enabled by default for the test. The test failure can be found [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49168/pull-kubernetes-e2e-gce-etcd3/44221/). The failure is the same when i ran `hack/local-up-cluster.sh` without specifying `RUNTIME_CONFIG="apps/v1beta2"`. Without the flag, apps/v1beta2 is disabled by default.

A way to resolve it is **appending** `apps/v1beta2` to kubetest `runtime-config` flag. For now, the default value for the flag is `batch/v2alpha1`. Refer [this](https://github.com/kubernetes/test-infra/blob/master/kubetest/main.go#L133).

**Comment by crimsonfaith91** [comment]
@ixdy I spent some time investigating it yesterday, but still came to a conclusion that the failure is due to v1beta2 is not enabled for submit queue `pull-kubernetes-e2e-gce-etcd3` test. I am not sure whether this can be resolved via kubetest image update, or there is a better way.

**Comment by krzyzacy** [comment]
Add the config to jobs/pull-kubernetes-e2e-gce-etcd3.env will fix it, no new image is needed :-)

**Comment by crimsonfaith91** [comment]
@krzyzacy Thanks! will do it asap :)

**Comment by crimsonfaith91** [comment]
@krzyzacy It looks like the test is still failing with the same failure message after adding `RUNTIME_CONFIG=apps/v1beta2` to `jobs/pull-kubernetes-e2e-gce-etcd3.env` file. 

It may due to:
(1) the env file is not updated yet 
(2) the failure is due to another reason

Will appending `apps/v1beta2` to kubetest [`runtime-config` flag](https://github.com/kubernetes/test-infra/blob/master/kubetest/main.go#L133) be a good idea? The default value for the flag is `batch/v2alpha1`. I am thinking `batch/v2alpha1, apps/v1beta2`

**Comment by krzyzacy** [comment]
pr test always uses latest env so that should be up-to-date.

From apiserver log:
```
W0801 20:56:39.522436       5 genericapiserver.go:321] Skipping API autoscaling/v2alpha1 because it has no resources.
W0801 20:56:39.586156       5 genericapiserver.go:321] Skipping API apps/v1beta2 because it has no resources.
```

can that be related to what you are looking at?

**Comment by crimsonfaith91** [comment]
Yes! I think both API versions should not be skipped. Do we need to add something to some config files when adding a subresource to a new version?

**Comment by krzyzacy** [comment]
ah I'm not super familiar with how api versions gets configured - cc @caesarxuchao who might have a better idea?

**Comment by crimsonfaith91** [comment]
Sure! Thanks! :)
