### ISSUE TITLE
Migrate event-based mungers to prow.

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#3843]
Some mungers should be prow plugins.

- [ ] ~~needs-rebase~~
- [ ] sig-mention-handler
- [ ] lgtm-after-commit

**Comment by spxtr** [comment]
needs-rebase is not event based, unfortunately.

**Comment by spiffxp** [comment]
/close

sig-mention-handler munger -> require-sig prow plugin
- https://github.com/kubernetes/test-infra/pull/5662
- https://github.com/kubernetes/test-infra/pull/5968

lgtm-after-commit
- https://github.com/kubernetes/test-infra/issues/3795
- possible impl https://github.com/kubernetes/test-infra/pull/3821
