### ISSUE TITLE
Deprecate and drop support for OWNERS assignees

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#3851]
I think it's now "eventually" https://github.com/kubernetes/contrib/pull/2076/files#r90728711

`assignees` are effectively `approvers` as far as mungegithub [is](https://github.com/kubernetes/test-infra/blob/a708cb0a3c3c36597eb2e5e1027e6e48c6d449b7/mungegithub/features/repo-updates.go#L122) [concerned](https://github.com/kubernetes/test-infra/blob/a708cb0a3c3c36597eb2e5e1027e6e48c6d449b7/mungegithub/features/repo-updates.go#L151), and I've been unable to find anything else that consumes OWNERS files

Repos that use `assignees` are doing so either out of legacy or because they don't care to have two-stage reviews.  Either way, the default setting for [use-reviewers](https://github.com/kubernetes/test-infra/blob/a708cb0a3c3c36597eb2e5e1027e6e48c6d449b7/mungegithub/features/repo-updates.go#L275) will have them covered if we just blanket rename `assignees` to `approvers` in the offending OWNERS files

@kubernetes/kops-maintainers @kubernetes/sig-docs-maintainers @kubernetes/sig-contributor-experience-misc

**Comment by chenopis** [comment]
@spiffxp Thanks for the heads up.

**Comment by spiffxp** [comment]
The above linked PR's are all of the offending repos currently munged by mungegithub, except for gengo which is vendored into kops.

This leaves mostly top-level and vendored OWNERS files for other kubernetes repos:
```
autoscaler/addon-resizer/vendor/k8s.io/kubernetes/pkg/api/OWNERS
autoscaler/addon-resizer/vendor/k8s.io/kubernetes/pkg/conversion/OWNERS
autoscaler/addon-resizer/vendor/k8s.io/kubernetes/pkg/runtime/OWNERS
dns/OWNERS
dns/vendor/k8s.io/kubernetes/pkg/api/OWNERS
dns/vendor/k8s.io/kubernetes/pkg/conversion/OWNERS
dns/vendor/k8s.io/kubernetes/pkg/runtime/OWNERS
features/OWNERS
frakti/OWNERS
ingress/OWNERS
k8s.io/OWNERS
kubeadm/OWNERS
kubectl/OWNERS
kubernetes-template-project/OWNERS
md-check/OWNERS
node-problem-detector/vendor/k8s.io/client-go/1.4/pkg/api/OWNERS
node-problem-detector/vendor/k8s.io/client-go/1.4/pkg/conversion/OWNERS
node-problem-detector/vendor/k8s.io/client-go/1.4/pkg/runtime/OWNERS
node-problem-detector/vendor/k8s.io/kubernetes/pkg/api/OWNERS
node-problem-detector/vendor/k8s.io/kubernetes/pkg/conversion/OWNERS
node-problem-detector/vendor/k8s.io/kubernetes/pkg/runtime/OWNERS
node-problem-detector/vendor/k8s.io/kubernetes/plugin/pkg/client/auth/oidc/OWNERS
perf-tests/network/vendor/k8s.io/client-go/pkg/conversion/OWNERS
perf-tests/network/vendor/k8s.io/client-go/pkg/runtime/OWNERS
perf-tests/network/vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/OWNERS
perf-tests/network/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/OWNERS
perf-tests/OWNERS
```

What's the right thing to do for the vendored files? ref: https://github.com/kubernetes/test-infra/issues/3694

**Comment by spiffxp** [comment]
Going to ignore vendored OWNERS files, and opt to modify mungegithub to (selectively?) ignore them

**Comment by spiffxp** [comment]
Opened PR's to get rid of this in all of the other kubernetes repos, and picked up a few that popped back up in kubernetes/website

**Comment by spiffxp** [comment]
And that's all the kubernetes-incubator repos I could find that used assignees.  

Let's see how long it takes for all these to merge

**Comment by spiffxp** [comment]
And that's all of them merged, can now remove the code that parses this field
