### ISSUE TITLE
'partially fixes' should not close the issue

### ISSUE THREAD

**Issue by k82cn** [kubernetes/test-infra#3857]
In https://github.com/kubernetes/kubernetes/pull/49870 , I marked it as partially fixes of 42001 which means it's only one of PRs for the whole project. Prefer not to close the issue when it's merged; I'll close it manually or by the latest PR of that project.

**Comment by xiangpengzhao** [comment]
I think it's because [mungegithub](https://github.com/kubernetes/test-infra/blob/2e98fc7ecdb45751a1f1d7ffdf23e94a34ddfb85/mungegithub/github/github.go#L61) doesn't recognize `partially`.

```
fixesIssueRE = regexp.MustCompile(`(?i)(?:close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)[\s]+#([\d]+)`)
```

**Comment by kargakis** [comment]
Not sure if this is a munger or github issue.

**Comment by ixdy** [comment]
The auto-closing is done by GitHub. I'm not sure there's anything we can do here.

**Comment by spxtr** [comment]
To be specific, this is done by [a github feature](https://help.github.com/articles/closing-issues-using-keywords/). It has a few other annoying edge cases as well, but there's nothing we can do about it.

**Comment by ixdy** [comment]
My workaround has usually been to write `part of #N` rather than `partially fixes #N`.

We could maybe formalize this and add it to the munger's RE, at least.

**Comment by k82cn** [comment]
got that, thanks very much :).

----
Da (Klaus), Ma (马达) | PMP® | Software Architect, IBM Cloud private
Development
IBM Spectrum Computing, IBM System
+86-10-8245 4084 | klaus1982.cn@gmail.com | http://k82.me

**Comment by k82cn** [comment]
I think adding it to readme is good!
