### ISSUE TITLE
Migrate federation cluster bringup method to k8s-anywhere

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes/test-infra#3858]
This issue is to discuss and track the migration of federation clusters bring-up in test-infra using k8s-anywhere,kubeadm.
Here is the issue which in general discuss about phasing out cluster scripts. https://github.com/kubernetes/kubernetes/issues/49213

Following are some of the tasks we envision towards this goal.
 - [x] 1. Configurable zone, ~~network~~ in k8s-anywhere deployer of kubetest - https://github.com/kubernetes/test-infra/pull/3859, https://github.com/kubernetes/test-infra/pull/3940
 - [x] 2. Configurable kubeconfig context. This needs to be implemented in kubernetes-anywhere itself. #https://github.com/kubernetes/kubernetes-anywhere/pull/429
 - [x] 3. Deploy multiple clusters in parallel using kubernetes-anywhere. #https://github.com/kubernetes/kubernetes-anywhere/pull/429
 - [x] 4. Bringup multiple clusters in single invocation of kubetest deploy Up(). Bringing up all clusters in parallel is desirable. https://github.com/kubernetes/test-infra/pull/4177
 - [x] 5. Enable cloud-provider in kubernetes-anywhere. https://github.com/kubernetes/kubernetes-anywhere/pull/449, https://github.com/kubernetes/test-infra/pull/4600
 - [ ] 6. Switch federation jobs to use `kubernetes-anywhere` deployment method.

/cc @luxas, @madhusudancs @irfanurrehman @kubernetes/sig-federation-misc

**Comment by madhusudancs** [comment]
> Configurable kubeconfig context. This needs to be implemented in kubernetes-anywhere itself.

We probably also need the ability to merge kubeconfigs. Right now, each invocation of kubernetes-anywhere generates a kubeconfig file, so there is one kubeconfig per cluster. These should be probably merged in kubetest.

> Bringup multiple clusters in single invocation of kubetest deploy Up(). Bringing up all clusters in parallel is desirable.

This should be probably implemented in kubernetes-anywhere to expedite the cluster bring up process and better debuggability via logging.

**Comment by madhusudancs** [comment]
@shashidharatd list looks good otherwise.

**Comment by luxas** [comment]
Thanks for putting this together @shashidharatd!
Can we set a timeline for this to happen?
Can we make net-new jobs/suites for this and gradually get things over?
Then when kube-up.sh federation jobs and kubeadm federation jobs have the same features, we can make the kubeadm federation jobs presubmit-blocking.

Happy to discuss this this Friday 9am PST

**Comment by shashidharatd** [comment]
Just realized that `kubernetes-anywhere` on GCE does not provision the network resource and just uses the `default` network. So configuring the network to non-existent network name will not get provisioned in phase1 of k8s-anywhere.
Also federation mostly uses `bootstrap-e2e` network name (set by kubernetes_e2e.py). So federation could as well use the `default` network and do not configure the network name. @madhusudancs, any issues?

**Comment by madhusudancs** [comment]
@shashidharatd `default` should be fine. How does `kubeadm` tests work? We should just follow that approach.

**Comment by luxas** [comment]
@madhusudancs What do you mean with `How does kubeadm tests work`?

**Comment by madhusudancs** [comment]
@luxas How do `kubeadm` tests setup GCE network? Do they use the `default` network? Do they use legacy networks or the new GCE VPC?

**Comment by luxas** [comment]
> legacy networks or the new GCE VPC

Ah. I don't know that detail, only that the network used is called `default` :wink:
Deferring to @pipejakob on that one

**Comment by shashidharatd** [comment]
Found out recently that `kubernetes-anywhere` deploys k8s cluster without `cloud-provider` enabled. federation jobs needs k8s clusters deployed with `cloud-provider` for persistent volume and load-balancer. We should probably add support to enable cloud-provider for gce in k8s-anywhere.

**Comment by luxas** [comment]
Does federation rely on gcePDs as well?

**Comment by shashidharatd** [comment]
There is no direct reliance of federation on gcePD, but the federation setup uses gcePD for federation etcd.

**Comment by luxas** [comment]
Can we use something else than gcePD? If so, it will be very easy to do with the cloud-controller-manager, and that would be a huge win.

**Comment by shashidharatd** [comment]
Actually kubefed uses PVC for etcd and PVC is bound by dynamically provisioned PV from the cloud-provider (In our case its gce, so gcePD). Is there anything against using gcePD?

Instead of dynamic PV's we could create a static PV, but the disk has to be cleaned/reclaimed every time by the CI job. But this would still use gcePD.

**Comment by luxas** [comment]
I'll check it up if gcePDs can be used with the cloud-controller-manager
cc @wlan0

**Comment by wlan0** [comment]
@luxas with @cheftako's PR, it can be used with CCM - https://github.com/kubernetes/kubernetes/pull/52371
