### ISSUE TITLE
PRs don't have "needs-ok-to-test", but author can't retest

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3862]
See:
https://github.com/kubernetes/kubernetes/pull/49361#issuecomment-317284144
https://github.com/kubernetes/kubernetes/pull/49942#issuecomment-319368513

The labels `needs-ok-to-test` of the above PSs were removed due to a member's comment `@k8s-bot ok to test` (note: not `/ok-to-test`). The tests were triggered. 

But when the tests failed, I couldn't retest by `/retest` (in 49361), or the tests weren't triggered again after I modified the code and pushed again (in 49942).

Not sure if it's because old bot comments are retired? ref: https://github.com/kubernetes/test-infra/pull/3845

/cc @crimsonfaith91 @fejta

**Comment by crimsonfaith91** [comment]
Is it working now?

**Comment by crimsonfaith91** [comment]
@xiangpengzhao The old bot comment format retired yesterday. Please ask someone to type `/ok-to-test` again if similar situation happens. It may due to deployment takes time to propagate.

**Comment by xiangpengzhao** [comment]
Thanks @crimsonfaith91 !
/close
this issue for now. Will reopen and ping you if it happens again.
