### ISSUE TITLE
Implement tide and replace the submit queue

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#3866]
Design doc [here](https://docs.google.com/a/google.com/document/d/1Z4UPEAFE7_36CKEYKPYGWKFjJyXxbodG26enakn2hMA/edit?usp=sharing), requires you to be a member of either kubernetes-dev or kubernetes-sig-testing. Please comment there with overall design decisions rather than on this issue.

Steps:

- [x] Implement tide's core loop for serial jobs. Start it up in dry run mode where it simply prints actions it would take. #4113
- [x] Implement batches. #4479
- [x] Turn it on in test-infra.
- [x] Implement the user interface in `cmd/deck`.
- [x] Use it in test-infra for a week or so. Demo with contribex and convince the world that it's a good idea to switch over the rest.
- [x] Turn down the submit queue everywhere in favor of tide.

🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊

**Comment by BenTheElder** [comment]
I expect plenty of 🌊🌊🌊 :smile:

**Comment by grodrigues3** [comment]
@kubernetes/sig-contributor-experience-feature-requests

**Comment by kargakis** [comment]
@spxtr seems like we also need to have in place the finer-grained management of PRs that the submit queue is doing today where specific status contexts are required as opposed to looking through all prowjobs, ie. all jobs that ever run for a PR.

Related: https://github.com/kubernetes/test-infra/issues/4387

**Comment by spxtr** [comment]
If we need to do that then we can add a config option. That's also necessary if the repo is using travis or something. We will definitely ignore jobs that are set to skip reporting.

**Comment by mml** [comment]
Can we make sure that this piece of configuration is global?  That is, you set it in one place, but the dashboard, tide, etc. all look at the same place?

**Comment by spxtr** [comment]
Yes, it will all live in prow/config.yaml.

**Comment by spiffxp** [comment]
Want to make sure we support https://github.com/kubernetes/sig-release/issues/26

Other blocks that came up during sig-testing meeting:
- ~A front end for tide that shows merge requirements and history~ (that's the web ui checklist item above, natch)
- We need to either stop reporting non-required contexts to github or make tide aware of which contexts are required.

**Comment by kargakis** [comment]
> We need to either stop reporting non-required contexts to github or make tide aware of which contexts are required.

ref: https://github.com/kubernetes/test-infra/issues/4932

**Comment by kargakis** [comment]
The issue with tide not being aware of which contexts are required is when leftover contexts that are not required are broken or when a new blocking job is added and its context is missing from all PRs. I think fixing #4932 and making sure tide knows what jobs are required will get us what we want.

**Comment by spxtr** [comment]
> We need to either stop reporting non-required contexts to github or make tide aware of which contexts are required.

I would like to live in a world where all green checkmarks on a PR means it will merge, and any red X means it will not. #4932 moves us there :)

> making sure tide knows what jobs are required will get us what we want.

One question is whether we want to build in a separate list of required contexts, or simply use always-run non-skip-reporting jobs from the config only.

**Comment by cjwagner** [comment]
> One question is whether we want to build in a separate list of required contexts, or simply use always-run non-skip-reporting jobs from the config only.

I like the idea of just using the config, but we have some contexts that are not controlled by Prow, but should still be required. Notably the CLA context.

**Comment by BenTheElder** [comment]
At some point I think we ought to block on run_if_changed + non-skip_report
as well (IE cross)

On Oct 24, 2017 14:43, "Joe Finney" <notifications@github.com> wrote:

We need to either stop reporting non-required contexts to github or make
tide aware of which contexts are required.

I would like to live in a world where all green checkmarks on a PR means it
will merge, and any red X means it will not. #4932
<https://github.com/kubernetes/test-infra/issues/4932> moves us there :)

making sure tide knows what jobs are required will get us what we want.

One question is whether we want to build in a separate list of required
contexts, or simply use always-run non-skip-reporting jobs from the config
only.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/test-infra/issues/3866#issuecomment-339141854>,
or mute the thread

**Comment by kargakis** [comment]
> simply use always-run non-skip-reporting jobs from the config only.

Should be enough but needs to be documented.

**Comment by cjwagner** [comment]
@kargakis What about contexts like the CLA context? It should still be required, but isn't in the config.

**Comment by kargakis** [comment]
Why does tide need to care about the cla context? I thought that it was checking for the cla label.

**Comment by BenTheElder** [comment]
> Why does tide need to care about the cla context? I thought that it was checking for the cla label.

The CLA bot bugs and people manually mark the CLA ok? If tide only pays attention to specific contexts this isn't a problem, if it expects all contexts to be green this becomes more annoying. 
I'd prefer all contexts to be green, but things like this might be worth considering.

**Comment by munnerz** [comment]
I think support additional contexts required to merge is a useful feature. I've used it in the past to require a travis context to pass for example, and it's a super convenient integration point for external tools to have a say in the merge process.

Could we automatically require all that have `skip_report: false`, as well as support an `additional_required_contexts` field or something?

**Comment by BenTheElder** [comment]
> Could we automatically require all that have skip_report: false, as well as support an additional_required_contexts field or something?

I'm not sure I understand why this is needed or what this would do exactly? Right now tide blocks on *all* contexts on GitHub being green regardless of source, in the future we might want to have a white or blacklist that can be configured in Tide for which contexts exactly should be green. Even then though the prow jobs shouldn't need to set anything themselves and there can be more than one prow job configuration per context (eg for different branches).

**Comment by munnerz** [comment]
Ah - that makes sense. I thought tide simply checks the prow config for jobs that have `skip_report: false` and merged when all of those were green. Checking the GitHub API and expecting all to be green makes a lot more sense!

**Comment by BenTheElder** [comment]
Yeah, you can see where it does that here with a TODO to look at the jobs, which we still seem to be coming to consensus on how to handle :-)
https://github.com/kubernetes/test-infra/blob/70f5bea97c31be846b999a58a9828dc4fda9568b/prow/tide/tide.go#L170-L188

**Comment by spiffxp** [comment]
We discussed during sig-testing yesterday, and are planning to wait until after the 1.9 release to roll out tide for kubernetes/kubernetes.  We will continue to canary it elsewhere, as it's been going fine in kubernetes/test-infra.  There was some question over whether we've done adequate load testing, which openshift might be willing to help us with.

**Comment by spiffxp** [comment]
Discussed during sig-testing yesterday, we're working on making the tide status less opaque, and would like to demo tide to the community before turning on for k/k.  In the meantime, I've been rolling tide out to more kubernetes repos.

**Comment by spiffxp** [comment]
The submit queue has been turned down everywhere except for kubernetes/kubernetes, #6417 tracks that effort

**Comment by spiffxp** [comment]
As I'm going through our labels it occurs to me that tide's not going to support the `retest-not-required` or `retest-not-required-docs-only` workflow that some contributors are used to https://github.com/kubernetes/test-infra/issues/5334

**Comment by ixdy** [comment]
@spiffxp OTOH, tide only triggers retests when the branch is out-of-date, whereas the submit queue always triggered retests.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/milestone 1.12
This didn't happen for 1.11.  Are we going to be able to make it happen for 1.12?

**Comment by spiffxp** [comment]
/milestone 1.12
... now that the milestone plugin is actually enabled for this repo

**Comment by spiffxp** [comment]
[Discussed this at sig-contribex yesterday](https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/edit), and [discussing during community meeting today](https://docs.google.com/document/d/1VQDIAB0OqiSjIHI8AWMvSdceWhnz56jNpZrLs6o7NJY/edit#).  Would like to notify kubernetes-dev afterward

**Comment by spiffxp** [comment]
PR to move k/k (to be revived) https://github.com/kubernetes/test-infra/pull/6417

**Comment by spiffxp** [comment]
PR that made the move: https://github.com/kubernetes/test-infra/pull/9303

**Comment by spiffxp** [comment]
@cblecker is using the `migratestatus` tool to retire the Submit Queue status with a note to look at the tide status instead, since GitHub doesn't allow us to delete existing statuses on PR's

**Comment by spiffxp** [comment]
https://submit-queue.k8s.io/ currently timing out, can we redirect this somehow

**Comment by ixdy** [comment]
@spiffxp we could probably make it redirect to tide, yes

**Comment by spiffxp** [comment]
The "Submit Queue" context sorted to the top, "tide" does not, maybe we should rename the tide context: https://github.com/kubernetes/test-infra/issues/9324

**Comment by spiffxp** [comment]
Tide's processing time has gone up: http://velodrome.k8s.io/dashboard/db/monitoring?panelId=9&fullscreen&orgId=1&from=now-2d&to=now

**Comment by ixdy** [comment]
https://submit-queue.k8s.io now redirects to the Tide status page.

**Comment by spiffxp** [comment]
Current status:
- kubernetes-misc-mungers is running with mungers: stale-green-ci,comment-deleter
- kubernetes-cherrypick is running with mungers: cherrypick-must-have-milestone,cherrypick-clear-after-merge,cherrypick-queue (cherrypick.k8s.io is up)

I implied we were going to turn all of those off in the k-dev e-mail, is this something we can get to today?  I'm going to survey cherrypick usage in the meantime.

**Comment by spiffxp** [comment]
Noticed tide's UI could stand to display more query info: https://github.com/kubernetes/test-infra/issues/9335

**Comment by cjwagner** [comment]
This is done!

**Comment by BenTheElder** [comment]
@qhuynh96 is also working on improving the query info :-) PRs are in flight

**Comment by spiffxp** [comment]
We missed the fact that a submit-queue badge was on k/k https://github.com/kubernetes/kubernetes/pull/68642

**Comment by spiffxp** [comment]
`retest-not-required-docs-only` labeling can be turned off since tide doesn't support this concept (TODO: pr/issue ref)

**Comment by spiffxp** [comment]
We needed to update tide to block merges on needs-kind and needs-sig labels for v1.12 https://github.com/kubernetes/test-infra/pull/9364

**Comment by spiffxp** [comment]
We need to redo the dashboard that was driven by MGH stats https://github.com/kubernetes/test-infra/issues/9458
