### ISSUE TITLE
k8s-merge-robot selects approvers from incorrect OWNERS file

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3882]
https://github.com/kubernetes/kubernetes/pull/50023 only change files in `pkg/kubectl/cmd/`. Bot should select approvers from `pkg/kubectl/OWNERS` (because there is no OWNERS file in `pkg/kubectl/cmd/`), but it selects approvers from `pkg/OWNERS`. See: https://github.com/kubernetes/kubernetes/pull/50023#issuecomment-319722580

See also: https://github.com/kubernetes/kubernetes/pull/49935#issuecomment-319766345

/cc @spiffxp @fabianofranz

**Comment by xiangpengzhao** [comment]
There is also another issue: the APPROVALNOTIFIER comment is not incorrect, or at least it should be enhanced.

See: https://github.com/kubernetes/kubernetes/pull/49945#issuecomment-319353564

```
Assign the PR to them by writing /assign @sig-cluster-lifecycle-maintainers @vishh in a comment when ready.
```

But when I comment `/assign @sig-cluster-lifecycle-maintainers`, nothing happens.
See: https://github.com/kubernetes/kubernetes/pull/49945#issuecomment-319914032

ping @crimsonfaith91

**Comment by xiangpengzhao** [comment]
Hmm, the bot told me this:
```
@xiangpengzhao: GitHub didn't allow me to assign the following users: sig-cluster-lifecycle-maintainers.

Note that only kubernetes members can be assigned.
```
See: https://github.com/kubernetes/kubernetes/pull/49945#issuecomment-319914034

**Comment by spiffxp** [comment]
pinging @apelisse @grodrigues3 since they're in the commit history for test-infra/mungegithub/mungers/approvers

I agree this seems unexpected

**Comment by apelisse** [comment]
There is obviously two issues here, and somehow I have the feeling that they are both related to the ALIAS feature. The first one because `pkg/kubectl/OWNERS` has no approvers beside the sig-cli-maintainers alias, and the second because it's telling you to assign an alias instead of a member of the alias.

I'll try to look into it.

**Comment by apelisse** [comment]
The issue with the second problem you mentioned, is that `sig-cluster-lifecycle-maintainers` is not a valid [OWNERS_ALIAS](https://github.com/kubernetes/kubernetes/blob/master/OWNERS_ALIASES)

**Comment by xiangpengzhao** [comment]
Which guys should be `sig-cluster-lifecycle-maintainers`? Maybe these ones in [lifecycle/bootstrap/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/lifecycle/bootstrap/OWNERS)?

**Comment by apelisse** [comment]
@mikedanese wrote this file, he must know?!

**Comment by apelisse** [comment]
@grodrigues3 any clue why it would not use `pkg/kubectl/OWNERS`?

**Comment by grodrigues3** [comment]
With a little bit of pain, we figured out the problem: 

Looks like [this PR](https://github.com/kubernetes/test-infra/pull/3766) introduced a change that filters such that only valid github handles are in our OWNERS files (which is behavior we want).  The implementation does not account for ALIASES.

**Comment by grodrigues3** [comment]
Looks like it might have been fixed by @stevekuznetsov's latest PR:

https://github.com/kubernetes/test-infra/pull/3898

@cjwagner can we redeploy SQ?

**Comment by stevekuznetsov** [comment]
@grodrigues3 yes sorry that first PR you noted did introduce a bug where `OWNERS_ALIASES` were being filtered out as the entries in those files were not valid GitHub assigness. The follow-up should have addressed the issue.

**Comment by cjwagner** [comment]
@grodrigues3 Yep, Ryan is doing that now.

**Comment by BenTheElder** [comment]
@stevekuznetsov @cjwagner should this be closed now?
