### ISSUE TITLE
Deploy gubernator without webhook_secret and secrets.json

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3884]
/area gubernator
/assign @rmmh 

Ideally we grab these values in some other way than uploading them with each version. This will make it easier/safer/possible for oncall to deploy this app.

**Comment by stevekuznetsov** [comment]
This would be really nice!

**Comment by fejta** [comment]
@rmmh please try and avoid referencing issues in commit messages

**Comment by rmmh** [comment]
Because it trashes history like this? Yeah, that makes sense.

Autoclosing through PR bodies is still ok, right?
