### ISSUE TITLE
Nudge people to file flakes

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#3886]
How about if we notice that an issue has 35 /retest commands and no kind/flake issue linked we drop a note asking people to file a flake issue and link it with each /retest command?

**Comment by cblecker** [comment]
Perhaps something fejta bot could do? Along with perhaps tracking how many times it has retested a specific commit and stop after some point. Or perhaps if it notices a specific tests is flaking/failing across a large number of approved PRs, it throttles?

**Comment by cblecker** [comment]
Still relevant.
/remove-lifecycle stale

**Comment by fejta** [comment]
Not perfect but mitigated... Let's see if the new wording helps at all.

/close
