### ISSUE TITLE
Rename Submit Queue 'Serial Builds'

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#3892]
Per discussion at [kubernetes-dev](https://groups.google.com/d/msgid/kubernetes-dev/CAMMDcuFWTAVeUjhts9uzLPS3WX3Pkvc_MDTTY_%2BN%2B7bEM44vkg%40mail.gmail.com?utm_medium=email&utm_source=footer) the suggestion  is 'Single'.

**Comment by kargakis** [comment]
SGTM
