### ISSUE TITLE
add Jenkins metadata to GCE VMs

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#39]
When trying to clean up old VMs or other resources, I'm often left wondering "where did this even come from?".

We could probably add metadata describing the Jenkins job and build number that spawned the VM, as well as the PR# on PR Jenkins. There's even an `add-instance-metadata` function in `cluster/gce/util.sh` we can use.

**Comment by fejta** [comment]
This is a cool idea that will help a lot with cleanup

**Comment by fejta** [comment]
I think we may have finished this? I believe multiple PRs have gone in related to this.

What kind of VMs are you talking about? e2e? Node e2e?

**Comment by ixdy** [comment]
AFAIK still not done. This is referring to the VMs that are spawned by tests, both for e2e and node e2e - right now I don't think you can clearly tell what build job created them.
