### ISSUE TITLE
No-sig-label bot message should be removed after adding sig labels

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#3906]
If the issue creator does not mention any sig group, the bot will leave the message, but the message will be there permanently. A recent example: https://github.com/kubernetes/kubernetes/issues/50122#issuecomment-320137992

@grodrigues3 WDYT?

**Comment by grodrigues3** [comment]
@kubernetes/sig-contributor-experience-bugs yeah this seems like something that should be fixed.

**Comment by crimsonfaith91** [comment]
I do not have bandwidth to work on this. Do you want to work on it?

**Comment by xiangpengzhao** [comment]
I'm not so familiar with the prow plugin, but I will try to investigate it when I'm free :)

**Comment by crimsonfaith91** [comment]
thank you very much!
