### ISSUE TITLE
Creation and deletion of GKE clusters failing

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#3911]
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gke&show-stale-tests=

cc @krzyzacy @pwittrock

**Comment by krzyzacy** [comment]
cc @zmerlynn

**Comment by pipejakob** [comment]
@kow3ns (buildcop)

**Comment by krzyzacy** [comment]
Attach the error message, anyone can give more context what is this about?

```
W0804 16:48:18.698] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W0804 16:48:18.699]  name: u'operation-1501864056179-2620bf6c'
W0804 16:48:18.699]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W0804 16:48:18.699]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/752718673218/zones/us-central1-f/operations/operation-1501864056179-2620bf6c'
W0804 16:48:18.699]  status: StatusValueValuesEnum(DONE, 3)
W0804 16:48:18.699]  statusMessage: u'Timed out waiting for cluster initialization. Cluster API may not be available.'
W0804 16:48:18.699]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/752718673218/zones/us-central1-f/clusters/e2e-13002'
W0804 16:48:18.699]  zone: u'us-central1-f'>] finished with error: Timed out waiting for cluster initialization. Cluster API may not be available.
```

**Comment by foxish** [comment]
Also borked: https://k8s-testgrid.appspot.com/google-gke-prod#gke-prod-parallel

**Comment by foxish** [comment]
@pipejakob, this is a bit different from [build-cop](https://github.com/kubernetes/community/blob/master/contributors/devel/on-call-build-cop.md) responsibilities I think

**Comment by krzyzacy** [comment]
`CommandException: No URLs matched: gs://cloud-sdk-testing/rc`

Cloud SDK borked I think

**Comment by crimsonfaith91** [comment]
@krzyzacy I created a buganizer issue and assigned you: https://buganizer.corp.google.com/issues/64393563

**Comment by crimsonfaith91** [comment]
Tell me if you need any help from my side :)

**Comment by pipejakob** [comment]
@foxish I'm not on the rotation, but thought I heard from @roberthbailey that this was a newer responsibility. I agree that it's missing from that document, so maybe we need to update the document, or  maybe I misunderstood Robert and there's a separate Google-internal rotation for debugging GKE e2e failures.

**Comment by roberthbailey** [comment]
@pwittrock and I have been discussing the extent of the build cop rotation (which is currently a bit unclear). 

I was under the impression that they were supposed to investigate these tests and escalate if they weren't able to fix them.

**Comment by zmerlynn** [comment]
At least right now, I don't think this is related to my GKE deployer changes. What I'm seeing is:
```
W0807 18:39:16.124] 2017/08/07 18:39:16 main.go:239: Something went wrong: failed to prepare test environment: rename /workspace/rc /workspace/repo: no such file or directory
W0807 18:39:16.124] Traceback (most recent call last):
W0807 18:39:16.125]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 653, in <module>
W0807 18:39:16.125]     main(parse_args())
W0807 18:39:16.125]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 521, in main
W0807 18:39:16.126]     mode.start(runner_args)
W0807 18:39:16.126]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 200, in start
W0807 18:39:16.127]     check_env(env, self.command, *args)
W0807 18:39:16.127]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 59, in check_env
W0807 18:39:16.128]     subprocess.check_call(cmd, env=env)
W0807 18:39:16.128]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0807 18:39:16.161]     raise CalledProcessError(retcode, cmd)
```

**Comment by zmerlynn** [comment]
Ah, yeah, @krzyzacy diagnosed it better above. `gs://cloud-sdk-testing/rc` isn't working.

**Comment by zmerlynn** [comment]
/assign
Talking to Cloud SDK folks.

**Comment by fejta** [comment]
Updtae?

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/release-master-blocking#gci-gke&show-stale-tests=
https://k8s-testgrid.appspot.com/google-gke-prod#gke-prod-parallel

looks fine after they fixed the /rc bucket

/close
