### ISSUE TITLE
We need a make release job

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/test-infra#393]
https://github.com/kubernetes/kubernetes/issues/30384 exposed the lack of a `make release` job.  We need one of those, post-submit if necessary.  @fejta @spxtr @ixdy

**Comment by ixdy** [comment]
Two separate PRs have broken Windows and Darwin builds. :(

https://github.com/kubernetes/kubernetes/pull/27970
https://github.com/kubernetes/kubernetes/pull/30087

**Comment by luxas** [comment]
Presubmit `make release` was a good thing after all, no one wants to deal with such a mess like this when releasing :/
These things happen, but when coverage is greatly reduced, more reverts and forward fixes like this are required.

Hopefully builds will be much faster in go1.7, so we might consider a presubmit jenkins job that just runs `make release` and is PR-blocking? Anyone agrees?

**Comment by spxtr** [comment]
I agree. We'll keep doing a quick-release for the e2e tests, but we will need a separate job for a full release.

**Comment by luxas** [comment]
Hmm, I don't think this should be closed yet... seems like the bots don't agree with me :smile:

**Comment by ixdy** [comment]
https://github.com/kubernetes/kubernetes/pull/31013 is the last blocker for this, assuming someone else doesn't try to fix it and collide with me.

**Comment by ixdy** [comment]
I'm glad I checked. https://github.com/kubernetes/kubernetes/pull/30802 is the one we want.

**Comment by ixdy** [comment]
Reopening until we have a `PR` make release job and the CI one is queue-blocking.

It'd be pretty trivial to add it to PR Jenkins, but I think we want to make sure we have enough Jenkins agents for the added compilation load, and we really need to address the exploding "ok to test" comments.

**Comment by luxas** [comment]
Yes, of course it requires machine power... you might have to go on a shopping tour :)

**Comment by ixdy** [comment]
stop it, github!

**Comment by spxtr** [comment]
We have a presubmit now. I don't think a postsubmit blocking job is a good idea.

**Comment by ixdy** [comment]
We have a presubmit, but I don't think SQ verifies that it's passing before attempting to merge, does it?

**Comment by spxtr** [comment]
No, since it only runs on PRs that are likely to break it. The submit queue needs to be extended to support optional jobs: merge if the status is not present or if it is passing. That should be a separate issue, though.
