### ISSUE TITLE
Not necessarily to comment about labeling size of PR

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#3933]
After creating a PR, one of the comments bot replies is about labeling size of the PR, e.g. `Labelling this PR as size/XS`. But seconds later, this comment will be deleted. Only something like https://github.com/kubernetes/kubernetes/pull/50198#event-1194248545 is left.

Seems like the appears-and-then-disappears comment is not necessary. Bot can label the size silently.

/cc @fejta @krzyzacy

**Comment by xiangpengzhao** [comment]
Tried to send a PR https://github.com/kubernetes/test-infra/pull/3936. Review welcome, I'm not sure if we really want it though :)

**Comment by cblecker** [comment]
It's worth noting removing the message will break certain notification/triage flows, specifically @thockin 's flow that's detailed here: https://groups.google.com/d/msg/kubernetes-dev/5qU8irU7_tE/aZov0LpCBwAJ

**Comment by xiangpengzhao** [comment]
It is just a minor enhancement (if any) for contributor experience. Didn't notice the potencial breaking. Feel free to close that PR if necessary :)
