### ISSUE TITLE
prow: unify all fake k8s clients under a single interface

### ISSUE THREAD

**Issue by nlandolfi** [kubernetes/test-infra#3934]
Reference: https://github.com/kubernetes/test-infra/pull/3876#discussion_r131509157

/area prow
/cc @kargakis

**Comment by kargakis** [comment]
We already have a constructor for a fake client [here](https://github.com/kubernetes/test-infra/blob/ed43beb2c64b6a03e607850482861915f594b787/prow/kube/client.go#L167) but it's only used in hook for its local mode and it lacks faking out any API call. 

What's needed here is introducing a client interface, switch all places that use kube.Client to use kube.Interface instead, implement that interface in the fake client, profit.

**Comment by kargakis** [comment]
It seems that there are fake k8s clients for every controller, this issue is about unifying them.

**Comment by spxtr** [comment]
What I would like the most is an actual fake API server, not just a fake interface. That way our tests can use a real `*kube.Client` and just talk to the fake server. This is nontrivial to do well, but would be really helpful.

**Comment by kargakis** [comment]
A fake client really gets us most of what we need.
