### ISSUE TITLE
commenter: do not run tests for broken PRs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#3944]
It would be nice if the [commenter](https://github.com/kubernetes/test-infra/tree/master/experiment/commenter) could recognize broken PRs and skip retesting them.

/area prow

/cc @stevekuznetsov @fejta

**Comment by kargakis** [comment]
Actually, we don't even need a k8s client, the retester can get the desired data from prow.

**Comment by stevekuznetsov** [comment]
How would you define broken versus flaking heavily? Does it matter?

**Comment by kargakis** [comment]
Broken is when no test has passed for a commit. I don't think we care about "flakying heavily", worst case scenario, a PR that is actually good to merge is not getting automatically retested.

**Comment by kargakis** [comment]
> Broken is when no test has passed for a commit.

Or more precisely, at least one job has never passed for a commit.

**Comment by stevekuznetsov** [comment]
Yeah, worst case we're not regressing anyway and the dev can `/retest` themselves. I'm not sure you really need the Prow client, either, since you can query GitHub for the itemized list of statuses

**Comment by kargakis** [comment]
> since you can query GitHub for the itemized list of statuses

We can't figure out if a PR flaked just by looking at Github unfortunately. We need to look into older runs, too, hence the need to look into prowjobs. The only thing that needs more thought at this point is prowjob GC.
