### ISSUE TITLE
log-dump shouldn't run twice in case of e2e test failure

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#3950]
There are 3 places form where log-dump currently can get called from:
- Inside ginkgo e2e-testing framework as an AfterSuite action (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L286)
- Inside kubetest if cluster-up failed (https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L127)
- Inside kubetest after all testing is done (but before down'ing the cluster) only if there was atleast one step that returned error on the way (https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L207)

The 2nd one is fine, but only one among the 1st and 3rd should happen, not both. As otherwise we're just duplicating all the work.
For e.g, look at this run -> https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-enormous-cluster/13/build-log.txt (where logdump had been called twice).
IMO, we should disable the first option in all our jobs and only do the 3rd (even if len(errs) == 0).

/cc @fejta @krzyzacy

**Comment by krzyzacy** [comment]
It sounds reasonable to me, I think @fejta was migrating the `--dump` behavior, see if he has more comments on this. 

/unassign
/assign @fejta

**Comment by shyamjvs** [comment]
I'm taking this up.
