### ISSUE TITLE
Gubernator not picking up results from junit_runner.xml

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#3951]
For e.g run 13 of gce-scale-performance (https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-performance) isn't showing the rows on the testgrid even though the junit_runner.xml file is present at the right place (http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/13/artifacts/?marker=logs%2fci-kubernetes-e2e-gce-scale-performance%2f13%2fartifacts%2fgce-scale-cluster-minion-group-zqrf%2f)

Note that the file was originally placed under artifacts/_artifacts dir due to the `gsutil cp` issue, but I manually moved it to the right place. However the change isn't reflected in the testgrid.

cc @fejta @krzyzacy

**Comment by krzyzacy** [comment]
I still think testgrid will ignore entries that it has already processed... I cleared the cache and see if it regenerates properly.

**Comment by shyamjvs** [comment]
Yup. It worked. However I do remember (doing it at least a couple of times) that moving the junit files to the right place does the trick. Not sure if something around it changed recently, but I did it for our scale test runs.

**Comment by shyamjvs** [comment]
It's a testable hypothesis. However we should make sure that gubernator does pick up the changes periodically (or quickly enough).
Feel free to close the issue if the current state is fine.

**Comment by fejta** [comment]
a) it takes a change in gcs roughly O(hour) to appear in testgrid
b) I'm not sure what gubernator loads on page load and what it loads from datastore
c) testgrid only reprocesses results from the last few hours (so updating a GCS file for a run 3 days ago will not do anything)

@michelle192837 @rmmh

**Comment by krzyzacy** [comment]
@fejta I think it will skip processed builds - move files around is not going to help

We pushed some testgrid changes that invalidates all the cache last Friday and the Friday before, that might cause it to become 'refreshed'

**Comment by rmmh** [comment]
Any changes after finished.json has been written might not be reflected in testgrid-- it assumes that all artifacts have been uploaded when that's present!

**Comment by fejta** [comment]
I would like to ignore this issue for now, as it is only relevant because of our debugging the logexporter

**Comment by shyamjvs** [comment]
Sure. Btw - the problem with logexporter has been solved by @krzyzacy by making gsutil copy differently if the artifacts dir preexists :)
