### ISSUE TITLE
[SQ-blocking] DumpClusterLogs failing in federation presubmit

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#3981]
For e.g - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/50310/pull-kubernetes-federation-e2e-gce/19456/build-log.txt

Failing due to the following reason:

```
I0808 15:18:39.593] Master not detected. Is the cluster up?
I0808 15:18:39.593] Dumping logs from nodes locally to '/workspace/_artifacts'
I0808 15:18:39.594] Detecting nodes in the cluster
W0808 15:18:40.350] ./cluster/log-dump/log-dump.sh: line 223: NODE_NAMES[@]: unbound variable
```

Seems like a bug which has gotten exposed by the recent change https://github.com/kubernetes/test-infra/pull/3974 which makes DumpClusterLogs happen only inside kubetest instead of also doing it in ginkgo.

cc @fejta @krzyzacy

**Comment by shyamjvs** [comment]
Another e.g - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/50290/pull-kubernetes-federation-e2e-gce/19460/build-log.txt (though this one failed due to the test itself failing)

**Comment by shyamjvs** [comment]
Seems likely to be something around testinfra config as the log-dump script is failing to find the master and nodes.
Strange it doesn't happen in non-federation tests.

cc @kubernetes/sig-federation-misc

**Comment by shyamjvs** [comment]
Reverting https://github.com/kubernetes/test-infra/pull/3975 would likely fix the SQ, but this needs to be debugged.

**Comment by shyamjvs** [comment]
Ok, so I just confirmed that this was a hidden bug which didn't come-up so far because previously log-dump was happening [within ginkgo](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L286) in case e2e tests succeed.
And if the e2e tests failed, we entered the [log-dump inside kubetest](https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L208), which like now was also failing back then, but that was neglected as the test failed anyway.
E.g of latter - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49112/pull-kubernetes-federation-e2e-gce/19404/

**Comment by fejta** [comment]
This is a bug in the kubernetes/kubernetes repo https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L223

/close

**Comment by krzyzacy** [comment]
We can pin federation deploy/pr job to the previous tag, until the script is fixed.

**Comment by fejta** [comment]
Here is an example of what that line needs to look like: https://github.com/kubernetes/kubernetes/blob/master/hack/ginkgo-e2e.sh#L133

**Comment by shyamjvs** [comment]
Please note that this is 'not' a bug in the kubernetes repo. Just because the logs mentioned that line failed, doesn't mean it's a bug there.
I've also explained the reason why it failed above and it was a previously uncaught bug which got exposed today.

**Comment by shyamjvs** [comment]
Besides, the SQ is blocked on this issue. So we shouldn't close it.
I can take up this issue if needed, though this almost surely seems to be a testinfra bug.

**Comment by krzyzacy** [comment]
cc @madhusudancs

**Comment by shyamjvs** [comment]
@fejta I guess that line in ginkgo-e2e.sh isn't the problem. It's the path to kubeconfig, which is set right in logexporter.

**Comment by fejta** [comment]
It looks like this is issue was about a NODE_NAMES unbound?

**Comment by shyamjvs** [comment]
It's an issue with `detect-master` and `detect-node-names` not working, most likely due to some misconfiguration. NODE_NAMES and MASTER_NAME being unbound is just a consequence.

**Comment by shyamjvs** [comment]
NODE_NAMES is computed by `detect-node-names` function by calling gcloud. So if things went fine it shouldn't have been unbound in the first place.

**Comment by krzyzacy** [comment]
sq is unblocked

**Comment by shashidharatd** [comment]
@krzyzacy, what was the fix. we have few more CI jobs in federation failing because of DumpClusterLogs
https://k8s-testgrid.appspot.com/sig-federation

**Comment by krzyzacy** [comment]
@shashidharatd I pin-ed the pr-federation job to an older e2e image, I guess if you want you can pin a few more important jobs as well, and have some job to give out signal until the real issue is fixed.

**Comment by shyamjvs** [comment]
So after I added extra logging it's clear why it's failing (ref: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-federation/5950/build-log.txt) -

```
W0809 14:32:50.556] Trying to find master named 'bootstrap-e2e-master'
W0809 14:32:50.556] Looking for address 'bootstrap-e2e-master-ip'
W0809 14:32:51.190] ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
W0809 14:32:51.190]  - The resource 'projects/k8s-jkns-e2e-gce-federation/regions/us-central1/addresses/bootstrap-e2e-master-ip' was not found
```

It is picking up the wrong master name, which is calculated as '${INSTANCE_PREFIX}-master' and INSTANCE_PREFIX=bootstrap-e2e.
The the real master names seem to be 'prow-us-central1-a-master' and 'prow-us-central1-f-master'.

**Comment by shyamjvs** [comment]
@krzyzacy Passing it to you from here on. Feel free to redirect it as apt.

**Comment by krzyzacy** [comment]
woot
/assign @madhusudancs 
Madhu can you help take a look here, I have no idea how federation set up and picks cluster/master names 😢 thanks!

**Comment by madhusudancs** [comment]
Are these jobs (Federation CI jobs) running on prow now?

**Comment by madhusudancs** [comment]
@shyamjvs @krzyzacy 

`INSTANCE_PREFIX=bootstrap-e2e` is coming from here - https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py#L585. I am not entirely sure why that is the default. We can probably override it here - https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L1918. But can someone explain to me why `bootstrap-e2e` is the default now given that almost all the CI jobs run on prow?

**Comment by krzyzacy** [comment]
@madhusudancs I think that's because most of ci jobs does not care about cluster names, which is different than federation.

**Comment by shyamjvs** [comment]
@shashidharatd Seems like your changes fixed this issue.
Closing it.
