### ISSUE TITLE
Bot assigned the PR author to be a reviewer

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/test-infra#3982]
https://github.com/kubernetes/kubernetes/pull/49178

See:
>  feiskyer was assigned by k8s-ci-robot 20 days ago

**Comment by fejta** [comment]
/assign @kargakis @cjwagner 

Aren't you two working on blunderbuss?

**Comment by cjwagner** [comment]
k8s-ci-robot is Prow not mungegithub so this probably isn't related to blunderbuss. I'll look into this.

**Comment by cjwagner** [comment]
feiskyer assigned themself in the original body of the PR and later edited the body to remove it.  The original body contained `/assign @feiskyer`.

**Comment by yujuhong** [comment]
I see. Thanks for looking into this!
