### ISSUE TITLE
Give up on a PR or batch as soon as one test fails

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#4015]
When test jobs have differing execution durations, it makes sense to give up on trying to merge a PR as soon as the first test in the suite fails. The tests should continue to run, but that PR or batch should not sit at the top of the queue while that happens.

/cc @deads2k

**Comment by fejta** [comment]
/assign @spxtr 

The challenge here is that we have a limited number of e2e runs we can do. It is probably better to just let them finish.

Close as tide will be subsuming this behavior?

**Comment by stevekuznetsov** [comment]
Yeah, makes sense to close this and incorporate the logic into `tide` if y'all think ti's appropriaet

**Comment by kargakis** [comment]
If once a test fails, the github status of the PR is failed, then this should be fixed by tide w/o adding any new logic to the current proposal.

**Comment by stevekuznetsov** [comment]
OK, sounds good.

**Comment by kargakis** [comment]
Let's keep this open until it's actually fixed.
