### ISSUE TITLE
Prow issue: CI ignoring needs-ok-to-test label

### ISSUE THREAD

**Issue by 007** [kubernetes/test-infra#4019]
Not sure if I am just misunderstanding the label/concept, but per https://github.com/kubernetes/heapster/pull/1753#event-1197638613 the k8s bot should be waiting to enable tests until `/ok-to-test`, but it's running Travis builds for commits.

**Comment by krzyzacy** [comment]
travis is not controlled by us :-)

**Comment by BenTheElder** [comment]
I think maybe we could have a script check for the label, the trick would probably be in avoiding the API rate limits.

EG I found that react has a `before_install` travis config that does this except it doesn't use a label:
https://github.com/facebook/react/issues/1768
https://github.com/facebook/react/pull/2000

I'm not sure if we *need* to do this though.

**Comment by fejta** [comment]
Please switch heapster test coverage to prow to receive better support https://github.com/kubernetes/heapster/issues/1771
