### ISSUE TITLE
mungegithub: k8s-merge-robot comments with dead-link when adding do-not-merge for release-note-label-needed PRs.

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubernetes/test-infra#4027]
When adding `do-not-merge` label for `release-note-label-needed` PRs, k8s-merge-robot comments with a link that is out of date (doc moved to kubernetes/community):
> Adding do-not-merge because the release note process has not been followed.
One of the following labels is required "release-note", "release-note-action-required", "release-note-experimental" or "release-note-none".
Please see: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes.

See the comments from k8s-merge-robot in PRs here: https://github.com/kubernetes/kubernetes/pulls?q=is%3Aopen+is%3Apr+label%3Arelease-note-label-needed+label%3Ado-not-merge

**Comment by m1093782566** [comment]
Hi @kevin-wangzefeng 

Thanks for reporting it. I find the link https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes is a dead link and the correct link is https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#write-release-notes-if-needed

I will fix it. Thanks!
