### ISSUE TITLE
kubeadm jobs failing with: `--provider=kubernetes-anywhere requires --gcp-project`

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#4032]
Occurs for https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#periodic-kubeadm-gce-1.7 and https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce.
Do we need to update the args for those jobs or should prow just be reloaded to catch up the newest config?
cc @pipejakob @fejta @krzyzacy 

Thanks!

**Comment by luxas** [comment]
Full logs: 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/periodic-kubernetes-e2e-kubeadm-gce-1-7/597
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/4868

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/issues/4012

working on it, will be fixed tomorrow

**Comment by luxas** [comment]
Thanks!

**Comment by krzyzacy** [comment]
Assume it does not need any special quota, any gce project should work for kubeadm right?

**Comment by luxas** [comment]
We need quota enough to run a master with 3 workers (IIRC) in as many replicas in parallell needed for postsubmit jobs (which may burst)

We've had problems with too limited quota before.

I'd VERY much perfer if we could make three different GCE projects: kubeadm-1.6, kubeadm-1.7, kubeadm-master
(I don't have access so I only have to ask kindly ;) )

**Comment by krzyzacy** [comment]
Okay I'll give back the projects if they need special quota - my original intend is for all the jobs to use a shared pool of projects.

**Comment by pipejakob** [comment]
If I understand the Boskos model, if a single run of the kubeadm e2e tests gets its own project that isn't being concurrently used by any other jobs, then it shouldn't have any quota issues. We were only hitting quota issues when the same job was being run 3 or 4 times concurrently using the same project.

**Comment by krzyzacy** [comment]
yeah, each run will grab a fresh project

**Comment by luxas** [comment]
This doesn't seem fixed yet @krzyzacy. All kubeadm jobs are currently failing with:
```
Something went wrong: error creating deployer: --provider=kubernetes-anywhere requires --gcp-project
```

Can you fix?

**Comment by krzyzacy** [comment]
/assign

watching, should be fixed with the latest image push

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#periodic-kubeadm-gce-1.7

recovered
