### ISSUE TITLE
Add screenshots in TestGrid README.md

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/test-infra#4040]
Some of the TestGrid documentation ought to have screenshots to better illustrate some of its features or configurable options.

**Comment by spiffxp** [comment]
/assign
/kind documentation
I'm arbitrarily adding to v1.9 milestone because I can probably help document the status quo, but if @michelle192837 has some more in depth in mind we can punt to 2018-goals

**Comment by spiffxp** [comment]
yeah totally didn't have time for this, I'm going to kick out of milestones entirely unless I or someone can sign up to do this
