### ISSUE TITLE
Comment "/release-note-action-required" doesn't work

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4057]
See: https://github.com/kubernetes/kubernetes/pull/50494#issuecomment-322090507

We now have four labels `release-note-action-required, release-note-none, release-note-label-needed, release-note"` associated with release note. But only `release-note-none` and `release-note` in comments work. Should we support the other two?

https://github.com/kubernetes/test-infra/blob/master/prow/plugins/releasenote/releasenote.go#L75-L83

```go
	// Which label does the comment want us to add?
	var nl string
	if releaseNoteRe.MatchString(ic.Comment.Body) {
		nl = releaseNote
	} else if releaseNoteNoneRe.MatchString(ic.Comment.Body) {
		nl = releaseNoteNone
	} else {
		return nil
	}
```

/cc @spxtr @cjwagner

**Comment by cjwagner** [comment]
`release-note-label-needed` should be added when needed by mungegithub and `release-note-action-required` will be added by mungegithub if the provided release note contains "action required". I think it makes sense to at least recognize `/release-note-action-required` as a prow command.

**Comment by fejta** [comment]
What is the difference between release-note and release-note-action-required?

**Comment by cjwagner** [comment]
`release-note-action-required` is used instead of `release-note` if the release note contains "action required". Besides that the release-note-label munger handles the two labels the same way.

**Comment by xiangpengzhao** [comment]
>release-note-action-required will be added by mungegithub if the provided release note contains "action required"

Is this documented anywhere?

**Comment by xiangpengzhao** [comment]
>Does it make sense to make the action required string not case sensitive?

For this comment of mine, I take another look at the code, it's already not case sensitive:)

**Comment by cjwagner** [comment]
> Another thing, mungegithub doesn't change the label after I edit the PR body to contain action required. See: kubernetes/kubernetes#50654. Should it respect the edittig?

Currently it is written to explicitly ignore the PR if a release-note label has already been applied. [See here](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/release-note-label.go#L128). I'm not sure why it is written that way, but modifying the label with a Prow command seems more intuitive to me anyways.

**Comment by cjwagner** [comment]
> > release-note-action-required will be added by mungegithub if the provided release note contains "action required"
> 
> Is this documented anywhere?

Not that I'm aware of, I found it by looking through the code. We should document it or switch to using only prow to manually adjust the release-note labels. I favor using Prow for this sort of thing since it is consistent with other bot commands and doesn't require users to be familiar with a special set of rules that determine which release note label gets applied.

**Comment by cjwagner** [comment]
I'm still not certain what the purpose of `release-note-action-required` is. It doesn't apply the `do-not-merge` label if the PR is lgtmed so it doesn't force the user to fix the release note before merging. I think if the release note requires work it should just be left blank or outside the release note section so that the `release-note-needed` label is used until the release note is finalized.

**Comment by xiangpengzhao** [comment]
>I'm still not certain what the purpose of release-note-action-required is. It doesn't apply the do-not-merge label if the PR is lgtmed so it doesn't force the user to fix the release note before merging. I think if the release note requires work it should just be left blank or outside the release note section so that the release-note-needed label is used until the release note is finalized.

`release-note-action-required` tells users what they should do when updating to this release. It is mostly used to label PRs which include feature graduation or replacement, e.g. graduate from annotations to field.

See example: 

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#action-required
https://github.com/kubernetes/kubernetes/pull/48353
```
The deprecated ThirdPartyResource (TPR) API has been removed. To avoid losing your TPR data, you must migrate to CustomResourceDefinition before upgrading.
```

https://github.com/kubernetes/kubernetes/pull/50224
```
Beta annotations `service.beta.kubernetes.io/external-traffic` and `service.beta.kubernetes.io/healthcheck-nodeport` have been removed. Please use fields `service.spec.externalTrafficPolicy` and `service.spec.healthCheckNodePort` instead.
```

**Comment by cjwagner** [comment]
Ah, that makes sense. I thought the label indicated that the release note itself required changes before being complete.

**Comment by xiangpengzhao** [comment]
So it's indeed necessary to document it here: https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#write-release-notes-if-needed

:smile:
