### ISSUE TITLE
404 on getting dockerized-e2e-runner.sh in all kubernetes builds

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/test-infra#406]
```
++ curl -fsS --retry 3 https://raw.githubusercontent.com/kubernetes/kubernetes/test-infra/jenkins/dockerized-e2e-runner.sh
curl: (22) The requested URL returned error: 404
```

The correct link should be `https://raw.githubusercontent.com/kubernetes/test-infra/master/jenkins/dockerized-e2e-runner.sh`(?)

/cc @k8s-oncall

**Comment by ixdy** [comment]
Should be fixed by https://github.com/kubernetes/test-infra/pull/408.
