### ISSUE TITLE
Consider getting project for node e2e tests using boskos

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#4067]
We currently need to hard code the project that will be used for running node e2e tests. We need to consider getting the test project using boskos. This can be done by adding the logic in node e2e test framework itself or by integrating node e2e tests into kubetest, which already supports this.

/assign

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-node-canary/224

it's possible now - I'll port over more jobs.
