### ISSUE TITLE
k8s-ci-bot doesn't label `cncf-cla: yes` for PR

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4069]
See: https://github.com/kubernetes/kubernetes/pull/50657

The check `cla/linuxfoundation — u2takey authorized` shows cla authorized, but the bot doesn't label  `cncf-cla: yes` for it.

**Comment by spiffxp** [comment]
/area prow
/close
seems like the label was added, please re-open if this occurs again

**Comment by xiangpengzhao** [comment]
yeah seems like the original issue was because the contributor's git config.
