### ISSUE TITLE
Consider removing "release-note-experimental" label

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4077]
We have a label `release-note-experimental` which was introduced by https://github.com/kubernetes/test-infra/commit/ce1d7561be754e5cc5b3f7df950f2de49d7c846a. But it is never used in any repo (at least K/K, test-infra, community). 

We'd better remove it to avoid confusion. If a PR in K/K has label `do-not-merge`, bot will comment as below. Note that `release-note-experimental` is listed in the comment. But actually, we don't have this label in K/K, see: https://github.com/kubernetes/kubernetes/labels. This is confusing...

```
Adding do-not-merge because the release note process has not been followed.
One of the following labels is required "release-note", "release-note-action-required", "release-note-experimental" or "release-note-none".
```

example from https://github.com/kubernetes/kubernetes/pull/50123#issuecomment-320644491

@david-mcmahon I see that you introduced this label in https://github.com/kubernetes/test-infra/commit/ce1d7561be754e5cc5b3f7df950f2de49d7c846a, could you please help explain what is this label for?

cc @cjwagner

**Comment by cjwagner** [comment]
Its not used anywhere in the kubernetes org. https://github.com/search?q=org%3Akubernetes+label%3Arelease-note-experimental

**Comment by xiangpengzhao** [comment]
Then it would be safe to remove it :)

**Comment by david-mcmahon** [comment]
This was added by request way back then.  Unfortunately there's no single canonical place to add a label like this and have it Just Work.   You need to add it to the munger code, then you have to physically add the label in github.  I suspect at some point someone removed it from github and now we have this dangling reference to it in the munger.   Cc'ing other folks who may have an opinion.

cc @dchen1107 @jdumars @grodrigues3
