### ISSUE TITLE
Sync Repo script is not working

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#4080]
Looking for clues on how the git repo sync'ing worked (prompted by email to -dev mailing list), found the instructions/details for the bot here:
https://github.com/kubernetes/test-infra/tree/master/mungegithub/publisher

So i checked the kubernetes-sha(s) in various repos Looks like the bot has not run for at least 2 weeks now. Last run i can see was on Aug 1st.

https://github.com/kubernetes/api/commits/master/kubernetes-sha
https://github.com/kubernetes/apiextensions-apiserver/commits/master/kubernetes-sha
https://github.com/kubernetes/apimachinery/commits/master/kubernetes-sha
https://github.com/kubernetes/apiserver/commits/master/kubernetes-sha
https://github.com/kubernetes/client-go/commits/master/kubernetes-sha

Can someone please look at why? Also can the daily logs be made available somewhere please?

Thanks,
Dims

**Comment by dims** [comment]
@caesarxuchao will you be able to help with this?

**Comment by jinzhejz** [comment]
Hi all, is there any update for this issue?

**Comment by sttts** [comment]
Only update is that I started working on this today to make progress.

**Comment by dims** [comment]
Thanks for the Manual effort in #51643 @sttts

**Comment by sttts** [comment]
Here are the updates for the bot, work in progress: https://github.com/kubernetes/test-infra/pull/4134

**Comment by dims** [comment]
@sttts `"k8s.io/apiextensions-apiserver/pkg/features"` is missing from https://github.com/kubernetes/apiextensions-apiserver/tree/master/pkg Looks like it was added in [1] as part of #47263 on the same day the repo was published i think.

[1] https://github.com/kubernetes/kubernetes/commit/6ba1523a8e36c3121a9e08bfac7b4f342bb8ccb3

**Comment by sttts** [comment]
@dims the manual sync snapshot was from Wednesday last week, before #47263 merged. https://github.com/sttts/apiextensions-apiserver is from yesterday and includes it. So this is expected.

**Comment by dims** [comment]
Looks like things are flowing again - https://github.com/kubernetes/kubernetes/issues/53808

**Comment by G-Harmon** [comment]
Looks like it's not sync'ing again. I was bit by this while revendoring a repo I'm working in. The last sync commit is from Oct 27 (https://github.com/kubernetes/api/commits/master)

**Comment by sttts** [comment]
@G-Harmon we are near to another push right now (and also full nightly synching again), please check https://github.com/kubernetes-nightly/client-go. If all tests pass (being run now), we will copy those branches to github.com/kubernetes/client-go again.
