### ISSUE TITLE
Testgrid not showing results on kubemark-small-1.5 dashbaord

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#4095]
Even though the test is passing - https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce-1.5
the dashboard isn't showing results - https://k8s-testgrid.appspot.com/sig-scalability#kubemark-small-1.5

/cc @fejta @krzyzacy

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce-1.5/17398/

WHAT... build 17398 has been triggered & unfinished?

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce-1.5/17397/ was finished, something happened around 2017-07-13 07:31 PDT?

**Comment by krzyzacy** [comment]
/unassign
/unassign @michelle192837 
/assign @shyamjvs 

see my comments in https://github.com/kubernetes/test-infra/pull/3480#issuecomment-323143596, feel free to self-serve

**Comment by krzyzacy** [comment]
/assign

simpler to wipe it, as it's not showing anything

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/sig-scalability#kubemark-small-1.5 it will start populate.

**Comment by shyamjvs** [comment]
Thanks for fixing.
