### ISSUE TITLE
Sinker: keep around periodic jobs

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#4099]
https://github.com/kubernetes/test-infra/issues/3977#issuecomment-321113759
> Although I believe a 1w interval right now is equivalent to daily (prow doesn't remember more than a day, or maybe we fixed that)

https://github.com/kubernetes/test-infra/issues/3977#issuecomment-321115445
> We could change Sinker's deletion rule to not delete the most recent run for a job if it's under a month old, which would allow long intervals without affecting higher-throughput jobs.

/area prow

**Comment by kargakis** [comment]
Another thing that I noticed in a periodic* job that we run outside of jenkins is that the pod is deleted after a while (not by sinker but by plank). Isn't pod GC something that should be handled by sinker as opposed to plank? Not being able to access logs from the latest job run seconds/minutes after the job finished is annoying.

* probably not related to the job type

**Comment by kargakis** [comment]
> Another thing that I noticed in a periodic* job that we run outside of jenkins is that the pod is deleted after a while (not by sinker but by plank). Isn't pod GC something that should be handled by sinker as opposed to plank? Not being able to access logs from the latest job run seconds/minutes after the job finished is annoying.
> 
> *probably not related to the job type

FWIW, this was fixed by https://github.com/kubernetes/test-infra/pull/4459

**Comment by kargakis** [comment]
I've got a branch working on this

/assign
