### ISSUE TITLE
Add `committee/foo` label support to prow label plugin

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#4106]
ref: https://github.com/kubernetes/community/issues/921
ref: https://github.com/kubernetes/test-infra/pull/4089

**Comment by spiffxp** [comment]
ping @cblecker since you've got context

**Comment by spiffxp** [comment]
It would be helpful to have this before removing direct write access to kubernetes/community https://github.com/kubernetes/community/issues/1511

**Comment by cblecker** [comment]
Sorry I missed this one!
