### ISSUE TITLE
"release-note-label-needed" is not always labeled when PR body is empty

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4128]
When PR body is empty, `release-note-label-needed` should be labeled as per https://github.com/kubernetes/test-infra/pull/3856. But sometimes bot doesn't label it in this case.

See in one PR: https://github.com/kubernetes/kubernetes/pull/50923
The label wasn't labeled at least in 10 minutes. I finally labeled it manually.

I send a PR https://github.com/kubernetes/kubernetes/pull/50955 to test this, but bot labels it in one minute.

Maybe there is a latency in https://github.com/kubernetes/kubernetes/pull/50923 ?

cc @cjwagner

**Comment by cjwagner** [comment]
I think that the deployment was out of date, I fixed that bug in #3856. I updated the deployment, please reopen this issue if you see that happen again.

**Comment by xiangpengzhao** [comment]
ok:)
