### ISSUE TITLE
Delete stale comment when fejta-bot triggers a new retest

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4132]
When a PR with both `approved` and `lgtm` fails CI, `fejta-bot` (cool icon!) will trigger retest after hours. But in some case, the CI may fail every time due to the same flake. `fejta-bot` will comment that it triggers the retest (and then the test fails) again and again. There may be many comments. See in https://github.com/kubernetes/kubernetes/pull/50678

How about deleting the stale comment when it triggers a new retest? @fejta WDYT?

**Comment by fejta** [comment]
So fix the tests to make them less flaky? And/or `/lgtm cancel` if it is clear the PR does not work.

I am not a fan of deleting `/retest` comments. This erases valuable information and signals about the health of our testing.

Note that the referenced PR eventually merged after 16 `/retest` attempts.

**Comment by xiangpengzhao** [comment]
>So fix the tests to make them less flaky?

Many comments with the same contents seem somewhat noisy before the flake is fixed.

>And/or /lgtm cancel if it is clear the PR does not work.

The assignees won't get notified when the flake is fixed. It's hard for them to determine when to lgtm again, so they may not want to cancel lgtm when there is flake not caused by the PR.

>This erases valuable information and signals about the health of our testing.

Maybe we can indicate the failure times in the new comment from your bot?

cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Sure, we could add a counter. @fejta given the API token pressure from the feature, do you expect you'd turn it on for k8s?

**Comment by kargakis** [comment]
Not going to move forward with this. Seems to add unnecessary complexity and hides the shame that comes with many retest comments (I like it).

**Comment by xiangpengzhao** [comment]
:smile: :man_shrugging: :smile:
