### ISSUE TITLE
verify test not completing

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#4143]
The verify test has been unable to finish for a while on the 1.6 branch, and there are no logs:

https://k8s-testgrid.appspot.com/google-unit#verify-1.6
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-release-1.6/8470

**Comment by krzyzacy** [comment]
looks recovered?

Might be related to few of our Jenkins vms ran out of memory?
