### ISSUE TITLE
Testgrid  presubmit page does not have correct gubernator link

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#4162]
i.e. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-bazel/37650 is not correct

/assign

**Comment by rmmh** [comment]
We could fix this on the Gubernator side if fixing it on testgrid is too annoying.

**Comment by krzyzacy** [comment]
@rmmh My thoughts:

From testgrid: 
- Inject pr number to metadata
- Make open_test_template to be something like guber/build/kubernetes-jenkins/pr-logs/pull/<pr>/<job>/<build>
- In testgrid expand it properly somehow

From gubernator:
(Seems https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kops-aws/ already has the right links) - If it can somehow translate the link it will surely be better, maybe you can point me to where the code lives.

**Comment by rmmh** [comment]
/assign

I'll do this in Gubernator.

**Comment by krzyzacy** [comment]
@rmmh thanks!
