### ISSUE TITLE
//mungegithub/mungers:go_default_test is flaky

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#4171]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4169/pull-test-infra-bazel/6082/

Spotted in the wild by @BenTheElder 
/area mungegithub
/kind bug

**Comment by BenTheElder** [comment]
I think this one has flaked on me once before as well.

**Comment by spxtr** [comment]
@marun just added this test a few hours ago. [This line](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/milestone-maintainer_test.go#L317) is converting to a map then back to a list, and map order is not guaranteed.

**Comment by BenTheElder** [comment]
The connection failures looked familiar: https
://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4002/pull-test-infra-bazel/5934/
<https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4002/pull-test-infra-bazel/5934/>

**Comment by spxtr** [comment]
The particular test failure I linked in the first post is fixed. Lets use a new issue for any other errors.
