### ISSUE TITLE
Prow failed to create _bazel_bootstrap dir

### ISSUE THREAD

**Issue by yutongz** [kubernetes/test-infra#4182]
Istio prow is suffering from a increasing severe issue.

`W0818 21:11:19.327] INFO: $TEST_TMPDIR defined: output root default is '/home/bootstrap/.cache/bazel'.
W0818 21:11:19.327] Error: mkdir('/home/bootstrap/.cache/bazel/_bazel_bootstrap'): (error: 13): Permission denied`
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_auth/242/auth-presubmit/140/

We have a issue with full context: https://github.com/istio/test-infra/issues/396 .
We are using prow config here: https://github.com/istio/test-infra/tree/master/prow

Can't figure out what's the reason behind this, one guess is like @nlandolfi said, the trick we are using pv port to make sure only one job can access to the cache disk at a time?

**Comment by yutongz** [comment]
cc @sebastienvas

**Comment by BenTheElder** [comment]
It looks like https://github.com/istio/test-infra/issues/396 was closed?

**Comment by sebastienvas** [comment]
Yes please close this.
