### ISSUE TITLE
kops flake: retry download of kube

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#4195]
Saw this; we should probably retry the kube download:

```
I0825 07:10:45.573] Unpacking kubernetes release v1.8.0-alpha.3.141+0cf928f6813741
W0825 07:10:45.674]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
W0825 07:10:45.674]                                  Dload  Upload   Total   Spent    Left  Speed
W0825 07:10:45.674] 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3913k  100 3913k    0     0  93.0M      0 --:--:-- --:--:-- --:--:-- 95.5M
W0825 07:10:45.770]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
W0825 07:10:45.770]                                  Dload  Upload   Total   Spent    Left  Speed
W0825 07:10:45.830] 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
W0825 07:10:45.832] 2017/08/25 07:10:45 util.go:110: Step './get-kube.sh' finished in 434.426368ms
W0825 07:10:45.833] 2017/08/25 07:10:45 main.go:153: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0825 07:10:45.834] 2017/08/25 07:10:45 main.go:187: Something went wrong: failed to acquire k8s binaries: U=https://storage.googleapis.com/kubernetes-release-dev/ci R=v1.8.0-alpha.3.141+0cf928f6813741 get-kube.sh failed: error during ./get-kube.sh: exit status 1
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kops/3240/pull-kops-e2e-kubernetes-aws/2690/

I'd like to have a look at this myself, so assigning to myself at least to understand where the fix would be.

Edit: so I can't assign it to myself, but I'll have a look anyway...

**Comment by justinsb** [comment]
This is in `cluster/get-kube.sh` in kubernetes.  We call `curl` with the retry option, but I believe curl does not retry on all errors, and this is one on which it does not retry.

Best fix is probably to move that download code to golang, or wrap the download in a bash retry loop.

**Comment by mml** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51480/pull-kubernetes-e2e-kops-aws/45639/

**Comment by krzyzacy** [comment]
seems there's already retry logic added to get-kube.sh, and get-kube.sh need to die
/shrug
