### ISSUE TITLE
/approve no-issue not working?

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#4245]
The PR https://github.com/kubernetes/kubernetes/pull/51466 has no associated issue. But it's not able to get approval when `/approve no-issue` is applied (https://github.com/kubernetes/kubernetes/pull/51466#issuecomment-325803981).

**Comment by yguo0905** [comment]
Manually added the approval label.

**Comment by shyamjvs** [comment]
@cjwagner Told ya so :)
Ref - https://github.com/kubernetes/kubernetes/pull/51282#issuecomment-325471091

**Comment by cjwagner** [comment]
That comment didn't work because the `no-issue` argument included a period (i.e. `no-issue.`). I will make a PR to make the check for a `no-issue` argument less strict. This doesn't apply to #51005 though, I'm still looking into what happened there.

**Comment by yguo0905** [comment]
> That comment didn't work because the no-issue argument included a period (i.e. no-issue.). I will make a PR to make the check for a no-issue argument less strict. This doesn't apply to #51005 though, I'm still looking into what happened there.

We tried twice. The first one has the extra dot, but the second does not. 

The second one is here: https://github.com/kubernetes/kubernetes/pull/51466#issuecomment-325803981.

**Comment by cjwagner** [comment]
Hmmm. I've spent a few hours trying to reproduce the error locally, but I haven't been able to. When I run an instance locally it correctly identifies the `no-issue` arguments and approves the PR. I'm using the same commit that is deployed and the same credentials so I'm not sure why the behavior differs. I'll take another look tomorrow.

**Comment by Cynerva** [comment]
I've hit this a few times. Here are some examples where `/approve no-issue` didn't work for me, in case it helps:

https://github.com/kubernetes/kubernetes/pull/52663#issuecomment-330296135
https://github.com/kubernetes/kubernetes/pull/52445#issuecomment-329293933
https://github.com/kubernetes/kubernetes/pull/50633#issuecomment-322287799

It seems like I was able to do this as recently as Jul 27, but haven't been able to since. Here's the last time it worked for me:

https://github.com/kubernetes/kubernetes/pull/49717#issuecomment-318396973

**Comment by shyamjvs** [comment]
cc @MaciekPytel @aleksandra-malinowska are seeing this too

**Comment by MaciekPytel** [comment]
@cjwagner It seems to just never work for me for the last month or so. It works for other people in sig-autoscaling.

Looking at history of this ticket it seems to impact people with uppercase letters in github id. With just 3 examples it may be an accident, but it seems rather suspicious...

**Comment by cjwagner** [comment]
@Cynerva Thanks for the examples. I was finally able to reproduce the error locally (still not sure why I couldn't reproduce it before) and, as @MaciekPytel guessed, it appears to be a case sensitivity problem. I'll make a PR with a fix.
