### ISSUE TITLE
prow: migrate github interaction to the graphql API

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#4247]
Moving forward, new interaction with the GitHub API should be using the v4 API.

ref: https://github.com/kubernetes/test-infra/issues/4240#issuecomment-325799176

/cc @spxtr 
/area prow

**Comment by BenTheElder** [comment]
I added a quick example of using the v4 API to fetch issues I had in #4248, but really only the query is particularly interesting. #4113 / #3866 should provide better (golang) examples.

It seems pretty clear that the GitHub API in general is moving towards v4 / GraphQL:
https://githubengineering.com/the-github-graphql-api/
https://developer.github.com/v4/#why-is-github-using-graphql

**Comment by marun** [comment]
So the plan is for prow to implement its own github client rather than trying to consume and contribute to a shared effort?

**Comment by BenTheElder** [comment]
We're using a shared GraphQL library, but fundamentally in GraphQL you
construct queries that return only the fields you want so a common GitHub
library for everyone doesn't make much sense.

**Comment by stevekuznetsov** [comment]
As I understand it the plan is to use https://github.com/shurcooL/githubql

**Comment by spxtr** [comment]
@BenTheElder you are correct in a sense. The library will look like a wrapper around `Query(...)` and `Mutate(...)` calls in that library with retries. We won't have individual methods for various queries, except maybe for a few regularly-used ones.

**Comment by BenTheElder** [comment]
Right, what I meant to say is that it makes sense for test-infra to share a
library but other projects will need their own queries so something like
go-github for the v4 API wouldn't do much. You mostly need a graphql
library and your specific queries.
Upstream issue here: https://github.com/google/go-github/issues/646

**Comment by stevekuznetsov** [comment]
The struct tag method of giving query parameters to that GraphQL API library is more than a little foreign and un-Go-like unfortunately.

**Comment by BenTheElder** [comment]
I thought so too at first, but having statically typed fields is nice, and
you can just tag your static query with all possible args as optional and
then only pass in the ones you need. For example with pagination you might
have an $after arg that is only passed after the first query. I'm not
really sure how GraphQL could be done more natively in go.

**Comment by spiffxp** [comment]
We're presently using githubql in prow/tide, at what point would we be satisfied enough with it to migrate the rest of prow over?  Is that something we want to accomplish this year?

**Comment by kargakis** [comment]
Unlike. The graphql api still lacks basic mutations like adding labels in issues/prs.

**Comment by kargakis** [comment]
https://platform.github.community/t/add-remove-labels-from-a-pull-request/3253

**Comment by spxtr** [comment]
Right, it's still a new API. For now I don't see much harm in keeping things the way they are.
