### ISSUE TITLE
do-not-merge/release-note-label-needed is repeatedly added

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4271]
https://github.com/kubernetes/kubernetes/pull/46662#issuecomment-326138615

The k8s-merge-robot has been sending the same comment about adding this label when the label already exists.

**Comment by BenTheElder** [comment]
There are now 6 large identical comments about adding this label which is already applied.

**Comment by BenTheElder** [comment]
See also https://github.com/kubernetes/kubernetes/pull/51661 with 16 comments and counting.

**Comment by fejta** [comment]
Exhibit R in why we want to migrate behavior from mungegithub to prow

**Comment by BenTheElder** [comment]
> Exhibit R in why we want to migrate behavior from mungegithub to prow

Maybe we should update the mungegithub docs to note this.

**Comment by stevekuznetsov** [comment]
#4273 makes it so no new comments are added

The pre-existing behavior of the munger will remove all of the comments as soon as a release note label is added. I think this is effectively closed.

/close
