### ISSUE TITLE
Don't suggest a reviewer I've already assigned.

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#4272]
```
[APPROVALNOTIFIER] This PR is NOT APPROVED

This pull-request has been approved by: ixdy, mml
We suggest the following additional approver: roberthbailey

Assign the PR to them by writing /assign @roberthbailey in a comment when ready.

```

roberthbailey was already assigned when the bot [said that](https://github.com/kubernetes/kubernetes/pull/51649#issuecomment-326140621)

**Comment by mml** [comment]
@kubernetes/sig-testing-bugs is this perhaps already fixed?

**Comment by cjwagner** [comment]
> is this perhaps already fixed?

It could be. This process is no longer managed by mungegithub, it is now handled by Prow and I made a bunch of fixes while migrating, so this might not be an issue anymore. Please reopen if this is still an issue.

**Comment by kargakis** [comment]
This is not fixed in prow. @tnozicka came across this in https://github.com/openshift/origin/pull/18513#issuecomment-363937250 and I would like to track it somewhere so we can potentially fix it.

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
I'm taking no action on this in ~2 years as a sign that it's no longer that important
