### ISSUE TITLE
24-hour test history is misleading when entire test suite fails

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/test-infra#428]
http://storage.googleapis.com/kubernetes-test-history/static/index.html

shows 78 tests passed, 0 failed, 0 unstable, 0 broken for this suite:

```
78  0   kubernetes-e2e-gke-1.2-1.3-upgrade-cluster-new 2    2   0   0
```

but only 2 tests.

In fact, the whole suite has been failing for weeks. The only thing working has been gcloud installation.

https://k8s-testgrid.appspot.com/google-upgrade#gke-1.2-1.3-upgrade-cluster-new&width=3

**Comment by spxtr** [comment]
It only calls it a failure if there is a test failure. We should probably fix that so that it looks at `finished.json`, although I think we might be trying to move away from the 24-hour view sometime soon. @rmmh might have an opinion.

**Comment by bgrant0607** [comment]
@spxtr I noticed this when looking at ways we could have noticed that the upgrade tests started failing back in June. Given the number of tests and test suites, some kind of summary seems like it would be useful, whether it's this current page or some other format.

**Comment by fejta** [comment]
The traige dashboard and testgrid deprecated this site.
