### ISSUE TITLE
Make "do-not-merge/*" label more noticable

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4284]
There are two concerns here:

1. change color of `do-not-merge/*` to be red as `do-not-merge` is. This will make authors/reviewers clearer that PRs are blocked by such labels. 

2. remove the existing `release-note-label-needed` when bot label it a `do-not-merge/release-note-label-needed`.

cc @stevekuznetsov

**Comment by xiangpengzhao** [comment]
These PRs have both the labels:
https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aopen+label%3Ado-not-merge%2Frelease-note-label-needed+label%3Arelease-note-label-needed

**Comment by xiangpengzhao** [comment]
I see the PR, the color will be fixed in https://github.com/kubernetes/kubernetes/pull/51663 :+1:

**Comment by stevekuznetsov** [comment]
Color should be fixed in https://github.com/kubernetes/kubernetes/pull/51663
Removal of existing labels should be fixed in #4275

**Comment by xiangpengzhao** [comment]
Thanks @stevekuznetsov !
/close
