### ISSUE TITLE
New added CI tests can not start on existed PRs

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/test-infra#4287]
Is this a BUG REPORT or FEATURE REQUEST?:
/kind bug

Uncomment only one, leave it on its own line:

/kind bug
/kind feature
What happened:
New added CI tests: pull-kubernetes-bazel-build and pull-kubernetes-bazel-test
can not start.

What you expected to happen:
those should start automatically.

How to reproduce it (as minimally and precisely as possible):
ref: https://github.com/kubernetes/kubernetes/pull/46341
it has ok-to-test label
![image](https://user-images.githubusercontent.com/5154334/29914314-a7f336f6-8e6a-11e7-82ff-f46a0dc17e6a.png)

but
![image](https://user-images.githubusercontent.com/5154334/29914325-b2945f36-8e6a-11e7-9f4c-89d33ba8c30a.png)

**Comment by zhangxiaoyu-zidif** [comment]
Moved from https://github.com/kubernetes/kubernetes/issues/51681
And also occur in  #46079.

**Comment by zhangxiaoyu-zidif** [comment]
cc: @kubernetes/test-infra-maintainers
/sig testing
/area test-infra

**Comment by spxtr** [comment]
Note that the ok-to-test was 20 days ago.  At that point in time, `pull-kubernetes-bazel-build` and `pull-kubernetes-bazel-test` didn't exist.

**Comment by BenTheElder** [comment]
I started them, you just need to request them with
```
/test pull-kubernetes-bazel-build
/test pull-kubernetes-bazel-test
```
@spxtr Maybe these should get automatically triggered though?

**Comment by zhangxiaoyu-zidif** [comment]
@kargakis If we can manully resolve this question,  should we cloese it?

**Comment by kargakis** [comment]
We could have a periodic job or something that kicks the new jobs automatically on an additive config update.

**Comment by zhangxiaoyu-zidif** [comment]
OK, let's keep it.
