### ISSUE TITLE
Incorrect actions of requesting a review

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4289]
See in: https://github.com/kubernetes/test-infra/pull/4288

I `/cc @cjwagner` to request a review. But the actions show as below. Interesting.
```
@xiangpengzhao requested a review from spxtr as a code owner 7 minutes ago
@k8s-ci-robot requested a review from cjwagner 7 minutes ago
```

/cc @cjwagner @spxtr :smile:

**Comment by kargakis** [comment]
> @xiangpengzhao requested a review from spxtr as a code owner 7 minutes ago

This one comes from Github. The test-infra repository uses Github CODEOWNERS
https://github.com/kubernetes/test-infra/blob/master/CODEOWNERS
https://github.com/blog/2392-introducing-code-owners

> @k8s-ci-robot requested a review from cjwagner 7 minutes ago

This one is your cc

Doesn't seem like an issue - closing

**Comment by xiangpengzhao** [comment]
@kargakis thanks for explanation! Seems like different from K/K :)

**Comment by cjwagner** [comment]
We're just trying out code owners in test-infra. Currently GH only supports a single CODEOWNERS file (not a hierarchy like OWNERS files) so unless that is changed we'll need to keep using OWNERS files.
