### ISSUE TITLE
Auto-file issues for all broken tests

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/test-infra#429]
We've had tests and even entire test suites broken for days, weeks, even months and nobody noticed. @lavalamp suggested that we could auto-file issues for all broken tests, as we do for flaky tests. That seems like a good idea to me.

**Comment by fejta** [comment]
We do this now, right?

**Comment by spxtr** [comment]
Yep.

**Comment by fejta** [comment]
Looks like we only do this for jobs listed here: http://submit-queue.k8s.io/#/e2e

This list is controlled by https://github.com/kubernetes/contrib/blob/master/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml

**Comment by fejta** [comment]
We should probably do something better here... For example we could ask users to specify whether they want auto-filing in the job yaml and then read this in the contrib repo... TBD

**Comment by lavalamp** [comment]
Yes, the point of this issue is to make sure that the list in the submit queue stays up to date.

**Comment by bprashanth** [comment]
Oh, can you also take labels/ccs/assignees from the yaml? we wouldn't even need the owners spreadsheet then.

**Comment by fejta** [comment]
The yaml defines the test job, but we define owners on a test case basis.

**Comment by fejta** [comment]
We now ensure the SQ blocking list is correct
