### ISSUE TITLE
mungegithub: release-note mislabeled

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/test-infra#4295]
kubernetes/kubernetes#50669
This PR is labeled with "release-note" by bot, but should be labeled with "release-note-none".

/area mungegithub
/kind bug

**Comment by stevekuznetsov** [comment]
That label got added on the 15th of August.

There doesn't seem to be any activity in the mungers or plugins for release notes before that:

```
$ git log --before 'Aug 15 2017' --pretty=$'%ad\t%h %s' -- mungegithub/mungers/release-note-label* prow/plugins/releasenote/
Thu Aug 3 15:12:25 2017 -0700   f9c54af Use buildozer to delete licenses() rules
Thu Aug 3 15:08:07 2017 -0700   0b1c4ec Use buildozer to remove deprecated automanaged tags
Wed Aug 2 17:18:26 2017 -0700   c9dd2c3 Autogenerate BUILD files for multi-vendor
Thu Aug 10 11:22:05 2017 +0800  3832a0f fix release notes deadlink
Tue Aug 1 13:38:15 2017 -0700   f9adde2 Fix log spam from adding empty labels in release note munger.
Thu Jul 27 08:25:42 2017 -0700  022f93d Determine the bot name using the GitHub API
Thu Jul 27 18:18:53 2017 -0700  ca98647 Fix go vet.
Thu Jul 13 11:22:15 2017 -0700  d994bc1 Make mungers handle a reloading config.
Wed Jul 12 16:06:59 2017 -0700  3c47d94 Make mungegithub read config from a mounted configmap instead of flags.
Wed Jun 28 17:31:56 2017 -0700  b1ef003 Rename StaleComment to StaleIssueComment.
Tue Jun 27 11:47:09 2017 -0700  bca7e6c Changed prow plugin regexps to allow trailing space. Also updated LGTM plugin to allow `/lgtm no-issue`.
Mon Apr 17 18:04:50 2017 -0600  86a853c lgtm and release note commands race #2336 Updated the validation to check for author and member instead of reviewer/author and updated tests for releasenote.go
Fri Apr 7 15:48:07 2017 -0700   7de5ff5 Make /assign and /unassign comment back when fails (#2374)
Fri Jan 20 16:46:52 2017 -0800  928e2d0 Fix imports to point to k8s.io/test-infra/
Fri Jan 20 16:09:54 2017 -0800  b48f4a4 Merge branch 'master' of mungegithub
Fri Jan 20 16:08:10 2017 -0800  4dba6ed Rewritten history and rename
Wed Jan 4 21:25:01 2017 -0800   46360b9 All all-srcs to test-infra. Add verify-boilerplate test target.
Tue Dec 20 17:42:30 2016 -0800  06c4927 First tests with bazel. (#1402)
Thu Dec 8 12:51:51 2016 -0800   4b289e6 Add /release-note and /release-note-none. (#1332)
```

**Comment by stevekuznetsov** [comment]
(and in the interim there has been a lot of changes) -- are there newer instances of this? Is this behavior consistent for other PRs?

**Comment by roycaihw** [comment]
kubernetes/kubernetes#50871 and kubernetes/kubernetes#51025 have similar situation. 

It could be because of k8s-merge-bot looking for exact match of the string in template: https://github.com/kubernetes/test-infra/blob/c60dfaf31aafa024225e5f8e07b86b5ff8bc825e/mungegithub/mungers/release-note-label.go#L183-L196

**Comment by stevekuznetsov** [comment]
Hmmm... we seem to parse it correctly as in [this playground](https://play.golang.org/p/yl7hAf9Lwd).

**Comment by cjwagner** [comment]
All of this behavior is expected as far as I can tell. 
For https://github.com/kubernetes/kubernetes/pull/51025: The release note is not "none", it is "none." with a period so the `release-note` label was applied.

For https://github.com/kubernetes/kubernetes/pull/50871: The release note started off as `Added lister expansions for DaemonSet, Deployment, ReplicaSet, and StatefulSet for apps/v1beta2.\r\n` which caused the `release-note` label to be applied. When the release note was updated to "none" the munger didn't react because there was already a valid release-note label set for the PR see [here](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/release-note-label.go#L138).

**Comment by cjwagner** [comment]
For https://github.com/kubernetes/kubernetes/pull/50669: The same thing happened as in https://github.com/kubernetes/kubernetes/pull/50871.  In this case, the release note was originally `\r\n    Modify the initialization of results in generic_scheduler.go\r\n`.

**Comment by roycaihw** [comment]
Thanks. I suggest the proper behavior when someone updates the release note to "none" to be updating the label as well, but that might be complicated with manually-added label and using-title-as-release-note case. 

It might be a feature request instead. Feel free to close the issue.

**Comment by cjwagner** [comment]
Yeah that seems like a reasonable change to me. I'll make an issue for it. 
Also note that you can use [Prow commands](https://github.com/kubernetes/test-infra/blob/master/commands.md) to control release note labels as well.
