### ISSUE TITLE
Prow should support maximum concurrent tests for certain jobs

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4303]
If we want to migrate everything to Prow (eg #3778) then the GPU jobs at least will need something like `/jenkins/job-configs/kubernetes-jenkins-pull/bootstrap-pull-json.yaml` so that tests don't exceed the quota.

**Comment by spxtr** [comment]
[Agreed](https://github.com/kubernetes/test-infra/blob/26576936fe6a7fe726ecbb2ef6a48d2e6037fb68/prow/config/jobs.go#L42-L43).

**Comment by krzyzacy** [comment]
oh neat I did not noticed that :-)

**Comment by BenTheElder** [comment]
Heh :-)

**Comment by kargakis** [comment]
Yeah, although it never actually worked: https://github.com/kubernetes/test-infra/issues/4109 :/

**Comment by krzyzacy** [comment]
(oh I cannot shrug against an issue...)

**Comment by kargakis** [comment]
> (oh I cannot shrug against an issue...)

P0
