### ISSUE TITLE
Submit Queue context url seems dropped

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4312]
For example in https://github.com/kubernetes/kubernetes/pull/51775 there is no link pointing back to the queue. We are also experiencing this in Origin. Looked briefly at the code but I didn't see any suspicious change that might have caused the regression.

@cjwagner can you have a look please?

/area mungegithub

**Comment by stevekuznetsov** [comment]
@smarterclayton @bparees FYI

**Comment by cjwagner** [comment]
Thanks for catching this.
