### ISSUE TITLE
kops PR builder running tests at ci/latest instead of merged PR

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#4315]
@liggitt  pointed out that kops appears to be running tests without merging the PR under consideration (or not building them).  So if a test is added in a PR, it won't be run when that PR is tested, for example.

**Comment by dims** [comment]
Looking at https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/51734/pull-kubernetes-e2e-kops-aws/45653/build-log.txt

There are 2 commits in https://github.com/kubernetes/kubernetes/pull/51734/commits

first one is 8c8dad0ffe6e60ca40e36f383ebc9fb7aee45cf8 and second one is cca6c52a9fa2779dff3a997f00e555fb9050ea20

The logs show just the second one picked up:
```
I0901 00:17:01.154] Checkout: /var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/go/src/k8s.io/kubernetes master:6597f1ed4af9b5f59d7c039f4e10bc68855ca442,51734:cca6c52a9fa2779dff3a997f00e555fb9050ea20
```

**Comment by stevekuznetsov** [comment]
The format for the `$PULL_REFS` there is correct @dims -- it's saying check out `cca6c52a9fa2779dff3a997f00e555fb9050ea20` in PR 51734. It's not cherry-picking the commit in question, just getting that version of the `pull/51734/head` ref.

**Comment by dims** [comment]
oops sorry i read it wrong then

**Comment by stevekuznetsov** [comment]
You can verify visually all the code is being merged in by looking at the diff:

```
I0901 00:17:38.803]  cmd/kube-apiserver/app/server.go                  |   6 +-
I0901 00:17:38.804]  cmd/kube-controller-manager/app/BUILD             |   1 -
I0901 00:17:38.804]  cmd/kube-controller-manager/app/batch.go          |   9 +-
I0901 00:17:38.804]  hack/make-rules/test-cmd-util.sh                  |  18 ++--
I0901 00:17:38.804]  pkg/apis/batch/v1beta1/defaults_test.go           |   2 +-
I0901 00:17:38.805]  pkg/controller/cronjob/BUILD                      |   4 +-
I0901 00:17:38.805]  pkg/controller/cronjob/cronjob_controller.go      |  18 ++--
I0901 00:17:38.805]  pkg/controller/cronjob/cronjob_controller_test.go |  38 ++++----
I0901 00:17:38.805]  pkg/controller/cronjob/injection.go               |  16 ++--
I0901 00:17:38.805]  pkg/controller/cronjob/utils.go                   |  10 +--
I0901 00:17:38.805]  pkg/controller/cronjob/utils_test.go              |  18 ++--
I0901 00:17:38.806]  pkg/kubectl/BUILD                                 |   2 +
I0901 00:17:38.806]  pkg/kubectl/cmd/BUILD                             |   1 +
I0901 00:17:38.806]  pkg/kubectl/cmd/run.go                            |   7 +-
I0901 00:17:38.806]  pkg/kubectl/cmd/util/factory_client_access.go     |   2 +
I0901 00:17:38.806]  pkg/kubectl/run.go                                | 102 ++++++++++++++++++++++
I0901 00:17:38.806]  pkg/kubectl/run_test.go                           | 101 ++++++++++++++++++++-
I0901 00:17:38.806]  pkg/master/BUILD                                  |   3 +-
I0901 00:17:38.807]  pkg/master/master.go                              |   5 +-
I0901 00:17:38.807]  pkg/master/master_test.go                         |   6 +-
I0901 00:17:38.807]  pkg/printers/internalversion/BUILD                |   2 +-
I0901 00:17:38.807]  pkg/printers/internalversion/printers.go          |  10 +--
I0901 00:17:38.807]  test/e2e/apimachinery/BUILD                       |   2 +-
I0901 00:17:38.807]  test/e2e/apimachinery/garbage_collector.go        |  18 ++--
I0901 00:17:38.807]  test/e2e/apimachinery/generated_clientset.go      |  38 +++-----
I0901 00:17:38.808]  test/e2e/apps/BUILD                               |   3 +-
I0901 00:17:38.808]  test/e2e/apps/cronjob.go                          |  44 +++++-----
I0901 00:17:38.808]  test/e2e/apps/types.go                            |   4 +-
I0901 00:17:38.808]  test/e2e/kubectl/BUILD                            |   1 -
I0901 00:17:38.808]  test/e2e/kubectl/kubectl.go                       |  49 +++++++++--
I0901 00:17:38.808]  test/integration/etcd/etcd_storage_path_test.go   |   3 +-
I0901 00:17:38.808]  test/integration/framework/master_utils.go        |   8 +-
```

Only the first PR touches `I0901 00:17:38.803]  cmd/kube-apiserver/app/server.go                  |   6 +-
I0901 00:17:38.804]  cmd/kube-controller-manager/app/BUILD             |   1 -
I0901 00:17:38.804]  cmd/kube-controller-manager/app/batch.go          |   9 +-
I0901 00:17:38.804]  hack/make-rules/test-cmd-util.sh                  |  18 ++--
I0901 00:17:38.804]  pkg/apis/batch/v1beta1/defaults_test.go           |   2 +-
I0901 00:17:38.805]  pkg/controller/cronjob/BUILD                      |   4 +-
I0901 00:17:38.805]  pkg/controller/cronjob/cronjob_controller.go      |  18 ++--
I0901 00:17:38.805]  pkg/controller/cronjob/cronjob_controller_test.go |  38 ++++----
I0901 00:17:38.805]  pkg/controller/cronjob/injection.go               |  16 ++--
I0901 00:17:38.805]  pkg/controller/cronjob/utils.go                   |  10 +--
I0901 00:17:38.805]  pkg/controller/cronjob/utils_test.go              |  18 ++--
I0901 00:17:38.806]  pkg/kubectl/BUILD                                 |   2 +
I0901 00:17:38.806]  pkg/kubectl/cmd/BUILD                             |   1 +
I0901 00:17:38.806]  pkg/kubectl/cmd/run.go                            |   7 +-
I0901 00:17:38.806]  pkg/kubectl/cmd/util/factory_client_access.go     |   2 +
I0901 00:17:38.806]  pkg/kubectl/run.go                                | 102 ++++++++++++++++++++++
I0901 00:17:38.806]  pkg/kubectl/run_test.go                           | 101 ++++++++++++++++++++-
I0901 00:17:38.806]  pkg/master/BUILD                                  |   3 +-
I0901 00:17:38.807]  pkg/master/master.go                              |   5 +-
I0901 00:17:38.807]  pkg/master/master_test.go                         |   6 +-
I0901 00:17:38.807]  pkg/printers/internalversion/BUILD                |   2 +-
I0901 00:17:38.807]  pkg/printers/internalversion/printers.go          |  10 +--
I0901 00:17:38.807]  test/e2e/apimachinery/BUILD                       |   2 +-
I0901 00:17:38.807]  test/e2e/apimachinery/garbage_collector.go        |  18 ++--
I0901 00:17:38.807]  test/e2e/apimachinery/generated_clientset.go      |  38 +++-----
I0901 00:17:38.808]  test/e2e/apps/BUILD                               |   3 +-
I0901 00:17:38.808]  test/e2e/apps/cronjob.go                          |  44 +++++-----
I0901 00:17:38.808]  test/e2e/apps/types.go                            |   4 +-
I0901 00:17:38.808]  test/e2e/kubectl/BUILD                            |   1 -
I0901 00:17:38.808]  test/e2e/kubectl/kubectl.go                       |  49 +++++++++--
I0901 00:17:38.808]  test/integration/etcd/etcd_storage_path_test.go   |   3 +-
I0901 00:17:38.808]  test/integration/framework/master_utils.go        |   8 +-
```

Only the first commit touches `cmd/kube-apiserver/app/server.go` and only the second touches `test/e2e/apimachinery/garbage_collector.go` but both are present.

**Comment by stevekuznetsov** [comment]
So either the e2e binary is not being built or one from master is being used -- @justinsb can you determine from that log which version is used to run the tests?

**Comment by justinsb** [comment]
Thanks @stevekuznetsov 

It's not 100% clear to me which version we're running (we don't print a SHA or version AFAICT), but here's what I think is happening:

* We merge the PR in `/var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/go/src/k8s.io/kubernetes`
* We bind mount that into the docker container at /go/src/k8s.io/kubernetes (`'-v', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes',`)
* We build the code in a docker container `make -C /go/src/k8s.io/kubernetes quick-release`
* We extract kubernetes-test `I0901 00:33:13.067] Will download and extract kubernetes-test.tar.gz from file:///go/src/k8s.io/kubernetes/_output/gcs-stage/v1.8.0-alpha.3.559+d8d9224869715a`
* We run the tests via `W0901 00:39:12.262] 2017/09/01 00:39:12 util.go:108: Running: ./hack/ginkgo-e2e.sh --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort`, so not clear which dir
* The tests do report this path while running e.g. `/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go`

I suspect something has gone wrong either in that extraction or that we aren't actually building.  But I _think_ that `d8d9224869715a` is the correct version.

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-e2e-kops-aws&width=80 - from that (1st row of column headers) each test looks like to have a different commit SHA

**Comment by ixdy** [comment]
The issue seems to be that the pull-kubernetes-e2e-kops-aws job is running a pretty old version of kubekins-e2e (`gcr.io/k8s-testimages/kubekins-e2e:v20170314-bb0669b0-pyopenssl`), which has this bit of logic controlled by environment variables:

https://github.com/kubernetes/test-infra/blob/bb0669b017507eb4a55e33cf73fa304f5211b6ce/jenkins/e2e-image/e2e-runner.sh#L78-L94

Since we've removed most of the environment variables from our test-infra configs, we're falling back on that last else clause:
```
W0901 00:18:24.614] + [[ -n '' ]]
W0901 00:18:24.614] + [[ '' =~ ^[yY]$ ]]
W0901 00:18:24.615] + [[ '' =~ ^[yY]$ ]]
W0901 00:18:24.615] + [[ '' =~ ^[yY]$ ]]
W0901 00:18:24.615] + [[ '' =~ ^[yY]$ ]]
W0901 00:18:24.615] + e2e_go_args+=(--extract="${JENKINS_PUBLISHED_VERSION:-ci/latest}")
```
and then the `--extract=ci/latest` is overriding the `--extract=local` arg in `kubetest`.

I think getting `JENKINS_USE_LOCAL_BINARIES=y` back into the pull-kubernetes-e2e-kops-aws environment should be enough to fix this issue.

**Comment by ixdy** [comment]
hm, closer: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-e2e-kops-aws/45954/?log#log

We're now using the correct kubectl and e2e tests, but we're still starting the cluster at the wrong version:

```
I0901 21:01:06.917] Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.3.665+c4040fb069aec0", GitCommit:"c4040fb069aec02a1431e43df59e30fc568b7889", GitTreeState:"clean", BuildDate:"2017-09-01T20:45:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
I0901 21:01:06.918] Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.3.663+44c5182187e6c3", GitCommit:"44c5182187e6c3d890ff0cd01d9b3ee667a0ebeb", GitTreeState:"clean", BuildDate:"2017-09-01T18:37:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Still investigating.

**Comment by ixdy** [comment]
Things have somehow gotten even worse. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-e2e-kops-aws/46002/?log#log
```
I0901 23:28:47.562] Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.3.665+a629ef28f674e7", GitCommit:"a629ef28f674e76a211ad690e76203c03f41db0d", GitTreeState:"clean", BuildDate:"2017-09-01T23:06:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
I0901 23:28:47.563] Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ixdy** [comment]
I think we need to set `--kops-kubernetes-version` in `scenarios/kubernetes_kops_aws.py`, but I'm not sure exactly how to do that in a maintainable way. The shell version of the job used to do it like
https://github.com/kubernetes/test-infra/blob/bb0669b017507eb4a55e33cf73fa304f5211b6ce/jobs/pull-kubernetes-e2e-kops-aws.sh#L75

**Comment by mml** [comment]
@ixdy I know these tests aren't blocking the merge right now, but as buildcop I'd feel a lot better knowing that we were really running them.  Can we find someone from @kubernetes/sig-testing-bugs to work with an appropriate someone from @kubernetes/sig-aws-misc and get this back on track?

**Comment by ixdy** [comment]
/assign

I'm working on trying to fix this.
