### ISSUE TITLE
Make kops-aws presubmit run against PRs or move it to post-submit

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#4316]
Currently it's running against the latest CI build which makes no sense for a pre-submit (ref https://github.com/kubernetes/test-infra/pull/4293#issuecomment-326617278)
Some discussion happened on issue - https://github.com/kubernetes/kubernetes/issues/51692

cc @justinsb @kargakis @soltysh @krzyzacy @kubernetes/test-infra-maintainers

**Comment by shyamjvs** [comment]
fyi - The above PR made it a non-blocking presubmit to mitigate the issue for now

**Comment by justinsb** [comment]
Dup of #4315?

**Comment by shyamjvs** [comment]
Seems so. Feel free to close this.
