### ISSUE TITLE
Feature Request: Label to disable testing for a PR

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/test-infra#4319]
Some WIP PRs are not ready to test, or simply does not need to be tested until further development work is done. Would be great if we can disable testing by labeling the PR to save testing resources and reduce notifications.

**Comment by spxtr** [comment]
Related to #1522

**Comment by kargakis** [comment]
Also related: https://github.com/kubernetes/test-infra/issues/3738

**Comment by stevekuznetsov** [comment]
Still relevant

/remove-lifecycle stale
