### ISSUE TITLE
ENABLE_HOLLOW_NODE_LOGS set in kubemark jobs, but logs for hollow-nodes missing

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#4321]
We're having the env var set to 'true' in some of our kubemark jobs:
- https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-kubemark-100-gce.env#L10
- https://github.com/kubernetes/test-infra/blob/master/jobs/env/ci-kubernetes-kubemark-5-gce.env#L10
...

 And also for the presubmit kubemark job:
- https://github.com/kubernetes/test-infra/blob/master/jobs/env/pull-kubernetes-kubemark-e2e-gce.env#L12

However, the [hollow-node logs](https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L46) are not being uploaded to the artifacts.
For e.g - http://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/51800/pull-kubernetes-kubemark-e2e-gce/49859/artifacts/e2e-49859-minion-group-d2s5/

Those logs are very important to debug the recent kubemark presubmit failures - https://github.com/kubernetes/kubernetes/issues/51799

**Comment by shyamjvs** [comment]
cc @krzyzacy @kubernetes/test-infra-maintainers 

They were being copied sometime ago, but now they aren't.

**Comment by krzyzacy** [comment]
can you tell when did that happen?

**Comment by shyamjvs** [comment]
Not recent enough that I can point out a particular run :)
Seems like the issue is with line - https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L145
It's checking that KUBERNETES_PROVIDER=="kubemark", while we're actually setting it to "--provider=gce" for kubemark jobs (ref https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L9152).

**Comment by krzyzacy** [comment]
what was wrong when you flip to `--provider=kubemark`? We can flip the canary job and debug from there.
