### ISSUE TITLE
queue: assignee: when a PR merges, remove assignees who didn't /lgtm or /approve

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#4340]
The purpose of this is to make github searches give meaningful stats. Right now it's super hard to data mine how many PRs you've actually reviewed.

**Comment by spxtr** [comment]
Try [`is:pr is:merged commenter:lavalamp -author:lavalamp assignee:lavalamp`](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20commenter%3Alavalamp%20-author%3Alavalamp%20assignee%3Alavalamp). That filters only those PRs that you commented on. Removing the `commenter:lavalamp` yields 988 PRs, about 250 more. Evidently you comment on many PRs.

**Comment by lavalamp** [comment]
Thanks for the query!

...I still think this is a reasonable feature request.

**Comment by spxtr** [comment]
Yeah, makes sense.
