### ISSUE TITLE
Changing release note block in PR body after release note is set does not update release note labels.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#4341]
Currently the release-note-label munger ignores PRs that already have a release note added (i.e. have one of `release-note`, `release-note-none`, or `release-note-action-required`). This prevents the munger from changing the label if the PR body's release note block is updated.

Discussed here: #4295

**Comment by xiangpengzhao** [comment]
Another concern:
#3295: k8s-merge-robot labels PR "release-note" even when the release note is "NONE"

**Comment by cjwagner** [comment]
@xiangpengzhao I looked into the first few cases you linked and they are all exactly what I'm describing above.

The author starts with a valid release note in the release note block of the PR which results in the `release-note` label being added. Then the author changes the block to `NONE`, but the label is not changed because the munger sees that the PR already has a release note label and considers its work to be done.

**Comment by xiangpengzhao** [comment]
@cjwagner yeah, exactly :)
