### ISSUE TITLE
Label Sync Umbrella Issue

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#4343]
Running the command as specified doesn't work
```
$ go run label_sync/main.go -labels-path label_sync/labels.yaml -local -repos label_sync/repos.yaml -repo-labels label_sync/repo_labels.yaml
vendor/github.com/shurcooL/graphql/graphql.go:11:2: no buildable Go source files in [my go path]/src/k8s.io/test-infra/vendor/github.com/shurcooL/go/ctxhttp
```
@lukaszgryglicki 
Were you able to build a docker image?

- The Dockerfile uses labelsync as an ENTRYPOINT which is the command specified to run in the image.  
- The Dockerfile never creates the label sync dir
- Dependencies are not resolved

**Comment by lukaszgryglicki** [comment]
entrypoint is just OK.
No label_sync directory is needed, statically compiled program "label_sync" is copied to the container "/" - which is OK.
Which dependencies? Docker image is supposed to be minimal, it has no dependencies, it is just a statically compiled "label_sync" binary and it requires only "/etc/config" dir with two files: `labels.yaml`, `repos.yaml`.

I've never seen that compilation error - maybe different go version? I cannot replicate it. I'm using:
```
iMac-Adm:label_sync lukasz$ go version
go version go1.8.1 darwin/amd64
```

**Comment by grodrigues3** [comment]
I fixed the compiler error, but I still don't understand how to get the -repo-labels.yaml file which I need in order to test locally.  Please update the readme with instructions for how to do this

**Comment by lukaszgryglicki** [comment]
You don't need that file.
Somebody requested to remove those test files from the task.
So they were removed.
Finally, [repos.yaml](https://github.com/kubernetes/test-infra/blob/master/label_sync/repos.yaml) was added again to allow running on a smaller number of repositories.
File `repo_labels.yaml` just contained a list of labels that exist in given repositories (to save GitHub token usage).
So to test this locally, You can just run in `-local` mode (no write), without mentioning `repo_labels.yaml` file (in this case label_sync will get a list of repository labels from GitHub):
`go run label_sync/main.go -labels-path label_sync/labels.yaml -local -repos label_sync/repos.yaml`

**Comment by stevekuznetsov** [comment]
I've used the program and it has since been changed substantially. This issue is no longer relevant.

/close
