### ISSUE TITLE
//scenarios:kubernetes_e2e_test takes 55 seconds.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#4344]
/assign @BenTheElder 

Looks like it's hitting [this code](https://github.com/kubernetes/test-infra/blob/456cb8b0bf0534cd5c5d5154268a20bc732392dc/scenarios/kubernetes_e2e.py#L513). Unit tests should never sleep.

**Comment by BenTheElder** [comment]
yeah, I just discussed this with sen. I'm going to have a patch before I head home :-)

**Comment by BenTheElder** [comment]
I'm planning on rewriting that code entirely, but for now I think I'll just patch out the sleep in the unit test until I have time to validate the rewrite a bit more.
