### ISSUE TITLE
pull-kubernetes-cross not being triggered on files it should be

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#4354]
It looks like pull-kubernetes-cross is supposed to run_if_changed on files matching a regex (such as `*_linux.go`):

https://github.com/kubernetes/test-infra/blob/3cd30c667da2b2ae76a8a838626b0dad256ca2d0/prow/config.yaml#L193-L198

However on https://github.com/kubernetes/kubernetes/pull/51209, which changed (among other files):
- `pkg/kubelet/cm/container_manager_linux.go`
- `pkg/kubelet/cm/container_manager_unsupported.go`
- `pkg/kubelet/cm/container_manager_windows.go`

The cross build presubmit however wasn't triggered, and as a result, the cross build broke on master (https://github.com/kubernetes/kubernetes/issues/51863). Is something not working right with prow?

---
/area prow
/kind bug
cc: @kubernetes/sig-testing-bugs @kubernetes/test-infra-maintainers

**Comment by kargakis** [comment]
The regexp is broken - opened https://github.com/kubernetes/test-infra/pull/4357

**Comment by cblecker** [comment]
Thanks @kargakis !

**Comment by dims** [comment]
@cblecker @kargakis - Looks like this is not yet fixed

example the cross build did not trigger on https://github.com/kubernetes/kubernetes/pull/51728 So @derekwaynecarr had to file another PR https://github.com/kubernetes/kubernetes/issues/52074 to fix the build

**Comment by kargakis** [comment]
Opened https://github.com/kubernetes/test-infra/pull/4436

**Comment by ixdy** [comment]
I think cross build didn't trigger on kubernetes/kubernetes#51728 because it ran tests before #4357 had merged, and it never ran tests again - https://k8s-gubernator.appspot.com/pr/51728.

**Comment by ixdy** [comment]
https://github.com/kubernetes/kubernetes/pull/51766 touches `hack/lib` and also triggered crossbuild.
