### ISSUE TITLE
Enable the milestonenotifier for other repos

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#4355]
Would be really cool if milestonenotifier would work across all our kubernetes repos that it makes sense to enable it for.

would make life easier for @kubernetes/kubernetes-release-managers; worth doing now?
cc @marun

**Comment by marun** [comment]
Isn't it required to create shadow issues in k/k for subprojects to ensure the release team can find all issues in one place?  If that's changed, then yes, automating milestone issue triage would be useful.

Likely rolling it out to other repos will need to wait until it is converted from a munger to a prow plugin.
