### ISSUE TITLE
Ensure sig-notifier also recognizes wg labels as valid

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#4356]
I'm not sure if this works already or not; does our sig-notifier bot recognize `wg/resource-management` for instance as a valid label state?
If not, it should be fixed.

**Comment by xiangpengzhao** [comment]
I sent a PR #4358 to fix it. But please note that we haven't had `wg/*` labels yet in any of our projects. We should add these labels first.

**Comment by luxas** [comment]
Oh, I thought we had those already, thanks.

Anyway, we should create labels for the WGs listed in kubernetes/community.
@bgrant0607 agree?

**Comment by bgrant0607** [comment]
We don't have any WG github teams, either.

Theoretically, SIGs should own all the code, tests, etc., so while I agree that WGs should have ways to identify issues related to them, I still want to require SIG labels.

**Comment by bgrant0607** [comment]
Ironically, this repo doesn't have any SIG labels.

**Comment by luxas** [comment]
@bgrant0607 I think we'll add WG Github teams soon, for instance for the cloudprovider effort.
Right now it's really painful to have to remember all the 10-ish persons by heart...

And for cross-cutting efforts like the cloud provider stuff, I can see a WG label "owning" the PR/issue make sense. Whether we want to enforce sigs everywhere anyway is up to debate I guess
