### ISSUE TITLE
Bot doesn't label or comment for PR which needs rebase

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4359]
See in https://github.com/kubernetes/kubernetes/pull/51762

Only below info is seen:
```
Submit Queue — PR is unable to be automatically merged. Needs rebase.
```

```
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
Conflicting files
Godeps/Godeps.json
pkg/kubectl/cmd/util/openapi/BUILD
pkg/kubectl/cmd/util/openapi/openapi_getter_test.go
```

**Comment by xiangpengzhao** [comment]
It commented and labeled after I sent a comment. Strange.

**Comment by spxtr** [comment]
It doesn't poll anymore, it only munges changed events.

**Comment by xiangpengzhao** [comment]
>It doesn't poll anymore, it only munges on events.

@spxtr I may miss something here. Can you explain a bit about what events? From my perspective, if no new comment to trigger it, no label and comment will be added, then how can the author get notified?

**Comment by kargakis** [comment]
We do both polling and events now - should be fixed by https://github.com/kubernetes/test-infra/pull/6121
