### ISSUE TITLE
Thoughts regarding the Jenkins operator

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4366]
* Today the controller is making a [Status](https://github.com/kubernetes/test-infra/blob/907a5d7980ae3b45a98802f641da47d7b2fa0d8c/prow/jenkins/jenkins.go#L170) or [Enqueued](https://github.com/kubernetes/test-infra/blob/907a5d7980ae3b45a98802f641da47d7b2fa0d8c/prow/jenkins/jenkins.go#L135) call for every prowjob separately. The Status call is really a List, [but the jenkins client is filtering through the results and returns in the controller what it needs on a per-test run basis](https://github.com/kubernetes/test-infra/blob/907a5d7980ae3b45a98802f641da47d7b2fa0d8c/prow/jenkins/jenkins.go#L200-L214). It will probably save a lot of load on Jenkins to switch the controller to do the Status and Enqueued calls (we can list all the builds in the queue) at the start of the loop before firing up any goroutines, bucket the prowjobs based on pj.spec.job, and start goroutines that handle each job separately with the cached results.
* If we are going to do the proposed change above, we also need to reduce the [backoff](https://github.com/kubernetes/test-infra/blob/907a5d7980ae3b45a98802f641da47d7b2fa0d8c/prow/jenkins/jenkins.go#L32) used which is probably too huge and the reason behind https://github.com/kubernetes/test-infra/issues/3742.

@spxtr thoughts?
/area prow

**Comment by spxtr** [comment]
Right, when I first wrote that client there was no plank controller, instead each job had to keep track of its own status. Now that model doesn't make sense, and your suggestion does make sense.

**Comment by kargakis** [comment]
Another thing I just figured out is that putting a proxy in front of Jenkins is not actually handling all requests from the jenkins-operator. When a build is [requested](https://github.com/kubernetes/test-infra/blob/b74ecde8723ee8a9daae91bd7cdfb3028b95c02c/prow/jenkins/jenkins.go#L111), assuming baseURL is pointing to the proxy, the [queue location](https://github.com/kubernetes/test-infra/blob/b74ecde8723ee8a9daae91bd7cdfb3028b95c02c/prow/jenkins/jenkins.go#L131) returned is pointing to the actual Jenkins instance.

curl example:
```
$ curl localhost:8080/job/test_pull_request_origin_verify/buildWithParameters -X POST -vvv -H "Authorization: Basic $(cat ./base | base64)"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /job/test_pull_request_origin_verify/buildWithParameters HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.53.1
> Accept: */*
> Authorization: Basic ***
> 
< HTTP/1.1 200 OK
< Content-Length: 0
< Date: Wed, 13 Sep 2017 13:08:50 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Location: http://ci.openshift.redhat.com/jenkins/queue/item/13922/
< Requested-Host: https://ci.openshift.redhat.com/jenkins
< Server: Jetty(9.2.z-SNAPSHOT)
< Set-Cookie: JSESSIONID.***;Path=/jenkins;HttpOnly
< X-Content-Type-Options: nosniff
< X-Jenkins-Proxy: JenkinsProxy
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
```
Assuming I run my proxy in front of Jenkins, prowjobs will still be tagged with the real Jenkins instance queue URL. @ixdy @spxtr who can share more information about your Jenkins proxy? Are you running a single Jenkins instance or demuxing to multiple? Will putting the queue URL behind the proxy work for you?

**Comment by spxtr** [comment]
We are running a single Jenkins instance. Our proxy is a simple VM with nginx doing a `proxy_pass`. Now that you point out this issue, I'm surprised that we don't run into it.

> Will putting the queue URL behind the proxy work for you?

Yes, that makes sense.
