### ISSUE TITLE
maintenance-pull-janitor job broken

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#4368]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/maintenance-pull-janitor/3994/

Failing with `ImportError: No module named requests`

**Comment by krzyzacy** [comment]
The cleaning up is actually fine, that's for the metadata call.

/assign

**Comment by justinsb** [comment]
Phew!  Thanks for looking at it @krzyzacy :-)

**Comment by krzyzacy** [comment]
```
W0920 10:55:20.523] ERROR: (gcloud.compute.instance-groups.managed.delete) Some requests did not succeed:
W0920 10:55:20.523]  - The resource 'projects/k8s-jkns-pr-gce-etcd3/zones/us-central1-f/instanceGroupManagers/e2e-53630-minion-group' is not ready
```

that instance group is busted (I cannot even manually delete it), asking help from gcloud team and the job should be green afterwards.
