### ISSUE TITLE
maintenance-ci-janitor job broken

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#4369]
Looks like a less catastrophic failure than the other maintenance jobs, but:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/maintenance-ci-janitor/211/

Examples:

```
W0904 00:32:56.887] Error try to delete resources: CalledProcessError()
W0904 00:32:56.887] ERROR: (gcloud.compute.networks.subnets.delete) Could not fetch resource:
W0904 00:32:56.888]  - Invalid resource usage: 'Cannot delete auto subnetwork from an auto subnet mode network.'.
```

```
W0904 01:22:31.946] ERROR: (gcloud.compute.forwarding-rules.delete) Could not fetch resource:
W0904 01:22:31.947]  - The resource 'projects/k8s-test-3e74ad8150/regions/us-central1/forwardingRules/a694129bf74a511e7bcc142010af0005' is not ready
W0904 01:22:31.948]  - The resource 'projects/k8s-test-3e74ad8150/regions/us-central1/forwardingRules/a699ebdb274a511e7bcc142010af0005' is not ready
```

**Comment by krzyzacy** [comment]
those errors are expected especially for the network one since seems we don't have a way to tell the mode of a subnetwork and we maybe switch that to manual mode - cc @MrHohn 
/assign

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/sig-testing-misc#ci-janitor start to have green runs after opt out federation projects. (it might still have failing runs but as long as it can catch up)

side note: ci-janitor is supposed to be kicked off once per day, but from the timestamp it also ran into https://github.com/kubernetes/test-infra/issues/5893
