### ISSUE TITLE
maintenance-ci-aws-janitor job broken

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#4370]
e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/maintenance-ci-aws-janitor/6499/

Failing with `Docker is not installed.`

**Comment by justinsb** [comment]
Probably related to #4361

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/maintenance-ci-aws-janitor/6529/

/close
