### ISSUE TITLE
Validate ProwJobs using CRD validation

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4373]
https://github.com/kubernetes/community/blob/31af349b1777e0fead2dd42eccca5799fb0375a2/contributors/design-proposals/api-machinery/customresources-validation.md

Things we need to validate:
- [ ] status.type and status.state are known values
- [ ] avoid validating the agent so we can support out of tree agent controllers
- [ ] completion time is set on a pj with status.state == {success, failure, error, aborted}
- [ ] children jobs have the same pull+sha as parents for presubmits
- [ ] max_concurrency is non-negative

I will keep this list updated as more things pop up.

1.8 thing
/area prow

**Comment by justinsb** [comment]
Why not just use a real API type?

**Comment by kargakis** [comment]
@justinsb that would require creating and running an API server for prowjobs on top of all the other services we already run. I don't think it's something we care about today, especially since we get stuff for free with CRDs but not unreasonable to do in the future.

**Comment by kargakis** [comment]
Also, we need to manage a separate instance of etcd with the new api server .... Unless we use the existing etcd write key?

**Comment by kargakis** [comment]
Things we need to validate:
- [ ] status.type and status.state is a known value
- [ ] avoid validating the agent so we can support out of tree agent controllers
- [ ] completion time is set on a pj with status.state == {success, failure, error, aborted}
- [ ] children jobs have the same pull+sha as parents for presubmits

I will keep this list updated as more things pop up.

**Comment by kargakis** [comment]
- [ ] validate that max_concurrency is non-negative

**Comment by spxtr** [comment]
> validate that max_concurrency is non-negative

In the meantime, we can add a check for this when we load a config file.

**Comment by kargakis** [comment]
Yeah, I meant to do it today but need to leave. Will open a PR tomorrow if nobody gets at it.
