### ISSUE TITLE
pull-kubernetes-bazel still list in PR CI dashboard

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/test-infra#4376]
ref: https://github.com/kubernetes/kubernetes/pull/45964
There is no pull-kubernetes-bazel any more.
but this failed info still existed in CI dashboard:

![image](https://user-images.githubusercontent.com/5154334/30052371-c88475ba-9257-11e7-9a89-80bd7d9dc85c.png)

**Comment by zhangxiaoyu-zidif** [comment]
/cc @kargakis 
Maybe this issue need to be focused too.

**Comment by kargakis** [comment]
There is no way to remove github contexts today

https://developer.github.com/v3/repos/statuses/
