### ISSUE TITLE
Prow issue: /assign and friends should be case-insensitive

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/test-infra#4388]
Currently, it appears that `/assign` is case-sensitive -- if I type

`/assign @directxman12`, prow complains (https://github.com/kubernetes/kubernetes/issues/44033#issuecomment-327276053), but if I use `/assign @DirectXMan12`, everything works.

This is made even more confusing by GitHub's rendering, which "corrects" the case when
it displays the rendered Markdown: if I type `@directxman12`, I get @directxman12

**Comment by fejta** [comment]
This is probably a limitation of the GitHub api

**Comment by spxtr** [comment]
Curiously, https://github.com/SPXTR works, but using the API to add SPXTR does not. Fortunately, when you say `/assign @spxtr` the tab completion will get it right.

**Comment by BenTheElder** [comment]
This is strange since most of github other than display is lowercase / case insensitive..
/assign @bentheelder

**Comment by BenTheElder** [comment]
This seems to be working correctly now, if I go to edit the comment above it shows `/assign @directxman12`.
I beleive I incidentally patched this at some point when I made Prow handle users case-insenstively in more places. It's possible that instead GitHub changed something, but either way it seems to be WAI now.
/close
