### ISSUE TITLE
Couple latest-upgrade CIs have no result on testgrid

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#4405]
They show up as tabs, but have not resutls. Ref:
- https://k8s-testgrid.appspot.com/latest-upgrades#gce-cluster
- https://k8s-testgrid.appspot.com/etcd-upgrades#gce-latest

From prow and gubernator, seems they are running (though failing):
- https://prow.k8s.io/?job=ci-kubernetes-e2e-gce-latest-upgrade-cluster
- https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-latest-upgrade-cluster

Shouldn't we at least show the passed units? (ref: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-latest-upgrade-cluster/900/)
```
Passed

Check APIReachability
Deferred TearDown
DumpClusterLogs
Extract
TearDown
TearDown Previous
Up
kubectl version
list nodes
listResources After
listResources Before
listResources Down
listResources Up
test setup
```

**Comment by krzyzacy** [comment]
I think it's dup https://github.com/kubernetes/test-infra/issues/4323

**Comment by MrHohn** [comment]
@krzyzacy Thanks, closing this one :)

**Comment by MrHohn** [comment]
Actually, maybe it is different. For instance, https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-latest-upgrade-cluster/899/ does have log artifacts but doesn't show up on tab as well.

**Comment by MrHohn** [comment]
> Shouldn't we at least show the passed units?

Actually, we should have the failed units as well.

**Comment by krzyzacy** [comment]
/assign

I'll take a look later - I think it messed up some build number counter from Jenkins

**Comment by krzyzacy** [comment]
I believe this job(s) has been deleted/readded back to Jenkins :disappointed: I'll flush the cache

**Comment by MrHohn** [comment]
@krzyzacy Awesome, thanks! I will verify and close this issue when the next build shows up.

**Comment by krzyzacy** [comment]
Grrrrrr https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-latest-upgrade-cluster/2573/ where's that coming from :-(((((((((((

**Comment by MrHohn** [comment]
Result shown up again :+1: 

Closing this.
