### ISSUE TITLE
1.8 release ci setup

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#4406]
@jdumars I will set it up base off 1.7 release for now, ref https://github.com/kubernetes/test-infra/issues/2965, feel free to add more here.

### Build / Verify
- [x] `ci-kubernetes-build-1.8` (Build)
- [x] `ci-kubernetes-verify-release-1.8` (Verify)
- [x] `ci-kubernetes-test-go-release-1.8` (Unit Test)
- [x] `ci-kubernetes-federation-build-1.8` (Federation Build)
 
### E2E
- [x] `ci-kubernetes-e2e-gci-gce-release-1.8` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gci-gke-release-1.8` (GCI-GKE)
- [x] `ci-kubernetes-e2e-kops-aws-release-1.8` (AWS)
 
### Slow
- [x] `ci-kubernetes-e2e-gci-gce-slow-release-1.8` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gci-gke-slow-release-1.8` (GCI-GKE)
 
### Serial
- [x] `ci-kubernetes-e2e-gci-gce-serial-release-1.8` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gci-gke-serial-release-1.8` (GCI-GKE)
 
### Federation
- [x] `ci-kubernetes-e2e-gce-federation-release-1.8` (GCE)
 
### Alpha
- [x] `ci-kubernetes-e2e-gci-gce-alpha-features-release-1.8` (GCI-GCE)
 
### Scalability
- [x] `ci-kubernetes-e2e-gci-gce-scalability-release-1.8` (GCI-GCE)
 
### Ingress
- [x] `ci-kubernetes-e2e-gci-gce-ingress-release-1.8` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gci-gke-ingress-release-1.8` (GCI-GKE)
 
### Reboot
- [x] `ci-kubernetes-e2e-gci-gce-reboot-release-1.8` (GCI-GCE)
- [x] `ci-kubernetes-e2e-gci-gke-reboot-release-1.8` (GCI-GKE)
 
### Soak
- [x] `ci-kubernetes-soak-gci-gce-1.8-deploy` (GCI-GCE)
- [x] `ci-kubernetes-soak-gci-gce-1.8-test` (GCI-GCE)
 
### Node
- [x] `ci-kubernetes-node-kubelet-1.8`

### Bazel & kubeadm
- [x] `ci-kubernetes-bazel-build-1.8`
- [x] `ci-kubernetes-bazel-test-1.8`
- [x] `ci-kubernetes-kubeadm-test-1.8`
- [x] `ci-kubernetes-kubeadm-test-1.7-on-1.8`
- [x] `periodic-kubernetes-bazel-build-1.8`
- [x] `periodic-kubernetes-bazel-test-1.8`
- [x] `periodic-kubernetes-kubeadm-test-1.8`
 
### Testgrid
- [x] Create new page for 1.8 release
- [x] Populate page with results from the tests above

**Comment by jdumars** [comment]
Thank you!

**Comment by luxas** [comment]
You can now add and fill in the checkbox for kubeadm :smile:

**Comment by krzyzacy** [comment]
cc @jdumars Talked with @yguo0905, we won't need cvm jobs anymore, I'll put up gci jobs only for release-1.8.

**Comment by jdumars** [comment]
Great, thank you for chasing that down.

**Comment by krzyzacy** [comment]
kubectl/upgrade jobs will be covered in https://github.com/kubernetes/test-infra/pull/4510
