### ISSUE TITLE
Submit queue behavior when the PR is the only PR in the test rerun

### ISSUE THREAD

**Issue by mindprince** [kubernetes/test-infra#4407]
I had a PR which was picked up by the submit queue. The submit queue started running tests on it a second time but instead of running them in batch, it ran them just for this PR. https://github.com/kubernetes/kubernetes/pull/51928#issuecomment-327306317
```
/test all [submit-queue is verifying that this PR is safe to merge]
```

One of the tests in this second run flaked and my PR was dropped from the submit queue. This behavior is pretty annoying.

This behavior (PR getting dropped from the submit queue) only happens when the second tests run for the PR takes place individually instead of in a batch. Can we fix the submit queue behavior to not drop PR from the queue in this case?

**Comment by krzyzacy** [comment]
cc @rmmh @cjwagner who can explain submit queue logic better here

**Comment by rmmh** [comment]
Any PR with failing tests is removed from the queue. Failures in batch tests aren't attributed to a single PR, so they don't eject PRs from the queue.

I don't see any great solutions for this at the queue level-- continuosly retesting a PR that is failing wouldn't be useful.

Identifying and retesting flakes would mean PRs would go back into the queue (after successes), which would ensure forward progress without human intervention.

**Comment by mindprince** [comment]
What do we do when there are failures in batch tests?

**Comment by fejta** [comment]
This queue behavior is WAI

If the batch fails the batch doesn't merge.

The same time the batch is running the first PR in the batch is also running in isolation. If the isolated test failed the PR is ejected from the queue. 

The next batch will have a different first PR either because a) batch passed and the PR merged b) single PR testing passed and it merged or c) single PR testing failed and it was booted.

**Comment by fejta** [comment]
Aka we always either merge or eject the top of the queue after both batch and single PR testing complete.

**Comment by mindprince** [comment]
There seems to be some inversion of priority here in terms of how many times a PR gets tested before getting ejected from the queue.

I am assuming the first PR in the batch is the one with highest priority (queue/critical-fix etc.).

So, now if both the single PR run and the batch failed because some flaking test, this hightest priority PR would get ejected from the queue. On the other hand, the other PRs in the batch will still remain in the batch. The PR which was fifth in the queue would get retested five times before getting ejected.
