### ISSUE TITLE
Prow job pods should have useful labels

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#4408]
This would make it easier to debug prow using kubectl.

    type={batch,periodic,postsubmit,presubmit}
    job={pull-cadvisor-e2e,...}

**Comment by kargakis** [comment]
Or make sure field selectors work in kubectl

Related: https://github.com/kubernetes/kubernetes/pull/50140

**Comment by kargakis** [comment]
> Or make sure field selectors work in kubectl
> 
> Related: kubernetes/kubernetes#50140

More related issues:

https://github.com/kubernetes/kubernetes/issues/49424
https://github.com/kubernetes/kubernetes/issues/51046

Seems like using labels in the short-term is the only solution for filtering.

**Comment by kargakis** [comment]
Oh, well. I thought this issue was about prowjobs and not pods. Field selectors are irrelevant in this case.
