### ISSUE TITLE
shrug doesn't label ¯\_(ツ)_/¯ when writing the command in PR (maybe issue also) body

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4416]
See in https://github.com/kubernetes/test-infra/pull/4415

/shrug

cc @kargakis

**Comment by xiangpengzhao** [comment]
Hmm, this issue self-proved.

**Comment by kargakis** [comment]
Well, even if it worked, your PR already had the label so we wouldn't know ... But yeah, review comments are not taken into account.

**Comment by xiangpengzhao** [comment]
But this issue can prove this anyway :)

I believe it didn't
/shrug
so far. I will see if it label it after this comment.

**Comment by xiangpengzhao** [comment]
Yeah it shrugged after my last comment :smiling_imp:

**Comment by BenTheElder** [comment]
This is clearly a P0 @krzyzacy :-)

**Comment by spiffxp** [comment]
/close
fixed by #4622, thanks for the P0 fix @cjwagner
