### ISSUE TITLE
Make it easy to kill or abort a running job.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#4425]
It's a pain to do this now, since pod and prowjob names are UUIDs. We just need to provide a kubectl command that deletes the appropriate pod. This will be restarted. We can provide another command that marks the prowjob as aborted, which will lead to it not restarting.

cc @rmmh @sebastienvas 
/area prow

**Comment by kargakis** [comment]
It would be really cool to see these commands + mkpj + https://github.com/kubernetes/test-infra/issues/4437 as part of a `prow`, `prowc`, or `prowctl` command that can also work as a kubectl plugin.

**Comment by BenTheElder** [comment]
/lifecycle-remove stale

This is still a bit frustrating to do, but I've done this manually by deleting the CRD in the services cluster first and then deleting the pod, which we could make less manual
/kind feature

**Comment by BenTheElder** [comment]
/reopen
/remove-lifecycle stale
This is still a pain point.

**Comment by BenTheElder** [comment]
@cjwagner this seems unhelpful. Surely someone else (repo maintainers at
least?) Should be able to reopen without using a /assign comment first...

**Comment by kargakis** [comment]
Agreed with Ben, let's open a separate issue to track

**Comment by stevekuznetsov** [comment]
With the pods labeled correctly in my recent PR we should be able to select a ProwJob and Pod more easily

**Comment by stevekuznetsov** [comment]
I think this is solved with

```
kubectl delete pod --selector prow.k8s.io/refs.repo=test-infra,prow.k8s.io/refs.pull=123,prow.k8s.io
/job=foo
```

@BenTheElder do you request something on top of that?

**Comment by BenTheElder** [comment]
technically I think you need to do:
```
get-access-to-prow-cluster
kubectl delete prowjob <pick some method to identify it>
get-access-to-prow-builds
kubectl delete pod <pick some method to identify the pod>
```

otherwise the pod will be recreated.

**Comment by sebastienvas** [comment]
Can we just be listening to delete on the CRD controller and delete the matching pods ?

**Comment by krzyzacy** [comment]
rewrite plank to become a real CRD controller first? :-)

**Comment by kargakis** [comment]
I think in this case you would want to rewrite sinker.

**Comment by sebastienvas** [comment]
I wish I did not asked :(. Do we have a label for tech debt ?

**Comment by BenTheElder** [comment]
we really should have such a label
/remove-lifecycle stale

**Comment by krzyzacy** [comment]
Delete a prowjob will also kill the pod now ^^
