### ISSUE TITLE
Use a tool to add webhook information.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#4437]
/area prow

The [getting started guide](https://github.com/kubernetes/test-infra/blob/f8e99feb208e388271d4b7f63a6933f161a03364/prow/getting_started.md#add-the-webhook-to-github) has a section on adding the webhook to GitHub. It's currently done manually, but it can be done with a tool. I think @jfelten started working on one, maybe we can use that?

**Comment by kargakis** [comment]
https://developer.github.com/v3/repos/hooks/#create-a-hook

**Comment by kargakis** [comment]
@jfelten are you working on this or can I pick it up?

**Comment by spxtr** [comment]
@jfelten made [this](https://github.com/jfelten/hook_manager) as a part of his helm chart.
