### ISSUE TITLE
Jobs should not use deprecated bootstrap flags

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4451]
Before https://github.com/kubernetes/test-infra/pull/4430 we should migrate all jobs using `--pull` and `--bare` to use `--repo` properly.

**Comment by BenTheElder** [comment]
Once things seem to be working fine the next step is making sure these flags are not used by future jobs.
@krzyzacy since you own config.yaml I'm counting on you too :-)

**Comment by krzyzacy** [comment]
just kill the flag :-)

**Comment by BenTheElder** [comment]
> just kill the flag :-)

Are we sure other projects aren't fetching bootstrap.py though? If so that's definitely my preferred route but I don't want to break anyone else. I'm pretty sure istio at least uses a fork..

**Comment by krzyzacy** [comment]
Then we should ask them to fix their flag - isn't it their fork was not super up-to-date? (still has bash scripts)

**Comment by BenTheElder** [comment]
Yes, I want to port them to the new bootstrap when it is ready. I'll kill
the flag and help fix any breakage if there's any. I'm pretty certain there
won't be now.

On Sep 8, 2017 13:22, "Sen Lu" <notifications@github.com> wrote:

Then we should ask them to fix their flag - isn't it their fork was not
super up-to-date? (still has bash scripts)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/test-infra/issues/4451#issuecomment-328204682>,
or mute the thread

**Comment by BenTheElder** [comment]
This should be fixed now :-)

**Comment by fejta** [comment]
Update?

**Comment by BenTheElder** [comment]
I think we can close this @krzyzacy. 
They were removed in https://github.com/kubernetes/test-infra/pull/4507 which was fixed by https://github.com/kubernetes/test-infra/pull/4569 and https://github.com/kubernetes/test-infra/pull/4570.
