### ISSUE TITLE
Create manual network instead of automatic network for PR jobs.

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#4472]
Ref quota issues on k/k:
https://github.com/kubernetes/kubernetes/issues/46713
https://github.com/kubernetes/kubernetes/issues/47362
https://github.com/kubernetes/kubernetes/issues/48688
https://github.com/kubernetes/kubernetes/issues/51646
https://github.com/kubernetes/kubernetes/issues/52140

Lately we've been hitting subnetwork quota issue periodically when GCP expands regions, as each PR job creates an autonetwork, which contains one subnetwork for each region. When quota issue occurs on PR jobs, it likely blocked the submit queue (by preventing PR from getting in SQ). This affects our development velocity in certain degree.

Per discussion on https://github.com/kubernetes/kubernetes/issues/51136#issuecomment-324140824 and https://github.com/kubernetes/kubernetes/issues/51646#issuecomment-326093725, I think we should figure out a way to use manual network for PR jobs to avoid hitting subnetwork quota issue again.

Not sure who is the right person to assign. I will try to take a look whether it is doable and how much work it will be.

/assign
cc @krzyzacy @yujuhong @nicksardo @cblecker  @xiangpengzhao FYI

**Comment by krzyzacy** [comment]
I'm happy to help this issue! (if I know what to do ❀◟(ó ̯ ò, ))

**Comment by cblecker** [comment]
Wholeheartedly support this. :)

**Comment by yujuhong** [comment]
> I will try to take a look whether it is doable and how much work it will be.

Thanks!

**Comment by nicksardo** [comment]
If everything uses a manual network, should we create a new suite of networking tests that continue to run on an automatic network (and limit the # of jobs in that project to something low)?

**Comment by yujuhong** [comment]
If this is only a problem for pre-submit jobs, maybe we can keep the post-submit jobs on auto networks? Ignore me if that's not the case.

**Comment by MrHohn** [comment]
> If this is only a problem for pre-submit jobs, maybe we can keep the post-submit jobs on auto networks? Ignore me if that's not the case.

Thanks, I was about to say the same thing, we could keep post-submit jobs on auto networks :)

**Comment by MrHohn** [comment]
Did a bit investigation, two high level tasks in my mind:
- Change gce kube-up scripts to support creating custom network.
- Change PR jobs to use that feature.

Sent https://github.com/kubernetes/kubernetes/pull/52377  for the first part.

cc @bowei

**Comment by krzyzacy** [comment]
any updates :-)

**Comment by MrHohn** [comment]
https://github.com/kubernetes/kubernetes/pull/52377 is still pending for review, sending a ping.

**Comment by MrHohn** [comment]
Finally kubernetes/kubernetes#52377  is merged. I'd like to work on the second part (see https://github.com/kubernetes/test-infra/issues/4472#issuecomment-329022742) and start making PR jobs create custom network.

For rolling out, what about four phases:
1. One non-blocking PR job.
2. All non-blocking PR jobs.
3. One blocking PR job.
4. All blocking PR jobs.

For phase one, I think [`pull-kubernetes-e2e-gce-gpu`](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-gpu) may be a good candidate. Or any suggestion?

cc @mindprince

**Comment by krzyzacy** [comment]
maybe `pull-kubernetes-e2e-gke-gpu` to start with, since that's manual triggered and can causes less damage if breaks.

**Comment by MrHohn** [comment]
> maybe pull-kubernetes-e2e-gke-gpu to start with, since that's manual triggered and can causes less damage if breaks.

Ack, sent #4988.
