### ISSUE TITLE
Prow: `always_run: true` should imply `/test all` trigger and handle `run_after_success`

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4475]
Right now `/retest` and `/ok-to-test` are handled in the `trigger` plugin, which is aware of Prow's config / job structure, however `/test all` is manually placed in jobs's `trigger:` regex. A quick scan of the config suggests that every `/test all` job is also `always_run: true` (which makes sense). Since they are triggered by this regex in a comment this means `/test all` naively triggers `run_after_success` jobs at the same time as their parent (I think?)

In order to make better usage of `run_after_success` I think `/test all` should be handled like `/retest` (in the trigger plugin) except that it should also test previously successful jobs (like the current behavior), and it should not be in the `trigger:` fields.

**Comment by spxtr** [comment]
> Since they are triggered by this regex in a comment this means `/test all` naively triggers `run_after_success` jobs at the same time as their parent (I think?)

I don't think so, we only run the top level of presubmits in [this function](https://github.com/kubernetes/test-infra/blob/9a3d8c62e0c15242aa490af3959d105b153d6d9c/prow/config/jobs.go#L149). `run_after_success` is pretty confusing, since `always_run` doesn't make sense for those jobs.

**Comment by BenTheElder** [comment]
Ah that makes sense. Perhaps we can provide a doc describing the behavior
of the job configs to go with your getting started guide? I can't seem to
find anything covering this other than the implementations.

**Comment by BenTheElder** [comment]
A better issue might be: We should clarify the interactions of these fields somewhere and probably make a note about how updating the config persists settings when re-running jobs.
