### ISSUE TITLE
PR has both "cherrypick-approved" and "do-not-merge/cherry-pick-not-approved"

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4492]
See in: https://github.com/kubernetes/kubernetes/pull/52199. This is strange.

cc @sebastienvas

**Comment by BenTheElder** [comment]
This is indeed strange :thinking:
Mungegithub so:
/shrug
/cc @cjwagner

**Comment by xiangpengzhao** [comment]
Hope #4517 can fix this.

**Comment by xiangpengzhao** [comment]
I think the cause of https://github.com/kubernetes/kubernetes/pull/52199 is that bot added `do-not-merge/cherry-pick-not-approved` first and then someone added `cherrypick-approved` manually. In this case, the bot couldn't detect and remove the stale label.
