### ISSUE TITLE
k8s-ci-robot adds and removes "cncf-cla" labels for several times 

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4494]
See in: https://github.com/kubernetes/kubernetes/pull/51931#issuecomment-328424955. There are three comments asking the author to sign CLA. It had some actions as below:

```
k8s-ci-robot added cncf-cla: no cncf-cla: yes and removed cncf-cla: yes cncf-cla: no cncf-cla: yes labels 15 minutes ago
```

Maybe the author was changing his CLA configuration at that time. cc @tengqm

**Comment by xiangpengzhao** [comment]
Also see a PR has both `cncf-cla: no` and `cncf-cla: yes` at the same time. https://github.com/kubernetes/kubernetes/pull/52262

**Comment by tengqm** [comment]
No. I didn't. The CI is doing some sports I suspect, :)

**Comment by xiangpengzhao** [comment]
That's interesting :smile_cat:

**Comment by xiangpengzhao** [comment]
Hmm... the bot is still playing... https://github.com/kubernetes/kubernetes/pull/51931#issuecomment-328428744

/assign @foxish

**Comment by foxish** [comment]
Both issues happened around the same time. 
Could be a transient github API issue. Will look into it if it recurs at a different time.

**Comment by xiangpengzhao** [comment]
@foxish thanks!

**Comment by BenTheElder** [comment]
Is this still an issue?

**Comment by foxish** [comment]
I don't think it happened again.
