### ISSUE TITLE
Manual push(es) of github pubisher bot results

### ISSUE THREAD

**Issue by sttts** [kubernetes/test-infra#4499]
This is basically a repetition of https://github.com/kubernetes/kubernetes/issues/51643, the same situation 2 weeks ago.

**Status Quo:** The github publisher bot https://github.com/kubernetes/test-infra/tree/master/mungegithub/publisher is **not** pushing the repos right now because it cannot cope with a number of commits (merges) and branch structures (fast-forward master merges) and falls over. Fixes are being reviewed https://github.com/kubernetes/test-infra/pull/4134, but it might take another 1-2 weeks until they are ready and maybe more days to build up the confidence again that we can let it push nightly automatically.

To unblock people with components depending on 1.8 another soon'ish push is necessary. For that the bot is run in a private GKE cluster now and pushes to private forks (https://github.com/sttts/client-go, https://github.com/sttts/apiserver, ...). The actual manual push is a sequence of fast-forward pushes. These are codified in

- https://gist.github.com/anonymous/2fd6e66e9364dd87e66b12cdb9bd92dc for the pushes, all fast-forward (**no force-pushes!**)
- https://gist.github.com/anonymous/62e661ea6dde3cb7615023f2e7fd69fb for the latest repo heads for a possible roll-back.

Only somebody with push permissions to the repos can execute them. Neither I nor @caesarxuchao have these permisssions. **PRs against the repos do not work** either because they linearize the branches and destroy the structure we need to consistently create tags.

These are the repos:

- k8s.io/code-generator 
- k8s.io/sample-apiserver
- k8s.io/kube-aggregator
- k8s.io/apiserver
- k8s.io/client-go
- k8s.io/api master
- k8s.io/apimachinery
- k8s.io/metrics
- k8s.io/apiextensions-apiserver

**What we need:**

1. somebody with the mercy (and time) to run https://gist.github.com/anonymous/2fd6e66e9364dd87e66b12cdb9bd92dc on our behalf
2. or somebody to give us (@sttts and @caesarxuchao) push permissions (or some special user for that we have access to) for those repos to do this push and maybe some more until the bot is running again.

As the situation can happen easily again that the bot falls over (or even pushes wrong content such that we have to react reasonably fast), I would feel much better with (2). Last time it took 3.5 days until we were able to do (1) after asking a number of people for help, not a good experience.

/cc @kubernetes/sig-api-machinery-misc @fejta @lavalamp @thockin @wojtek-t @smarterclayton @eparis

**Comment by lavalamp** [comment]
@rmmh @fejta FYI

**Comment by fejta** [comment]
/unassign @rmmh 
/assign @fejta

Agree with option (2), however we (GKE EngProd, sig-testing, test-infra) do not have write access to those repos. Looks like all these repos are apimachinery repos, so filing an issue there. The leads for that sig should be able to give you this write access.

**Comment by lavalamp** [comment]
@fejta and I came up with the compromise solution of putting @caesarxuchao in the "bots" team to do this push manually until test-infra feels like they are ready to "carry the pager" for the repo pusher. Any objections?

**Comment by fejta** [comment]
@kubernetes/sig-testing-feature-requests @rmmh 

At first blush this seems like a reasonable resolution to me. I asked Daniel to attend tomorrow's sig-testing meeting so we can run the idea by everyone else (we added the item to our agenda). Two questions I have are:
1) Is this something we want test-infra oncall to support? Given that we maintain all the other bots this seems reasonable to me.
2) Ryan, what needs to happen before we are ready to support outages in the repo publishing bot?

**Comment by sttts** [comment]
> Ryan, what needs to happen before we are ready to support outages in the repo publishing bot?

My expectation is that 90% of issues with the bot (next to github hickups) will need either bot fixes or manual intervention in broken repos. That's the experience. It's hardly about restarting the bot or updating some access tokens.

I don't care much who wears the pager, but I have a strong opinion that this kind of infrastructure must be openly visible and debuggable, also for non-Google people. We had an outage of the bot for six weeks (!!!) now because the people able to fix it were not available due to other tasks. With all the users of our published repos, this is becoming critical infrastructure for the project and having only one or two persons in one timezone and one company feels wrong.

Hence, my question: does "test-infra oncall to support" mean it's only visible within Google again? What are the plans to open this up?

**Comment by kargakis** [comment]
@sttts there is an issue for discussing what you are asking: https://github.com/kubernetes/test-infra/issues/3349
