### ISSUE TITLE
testgrid shows PASSING for tests that don't run

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#4501]
The testgrid summary seems to mark a test as PASSING if it can't find any results at all. This makes it hard to notice when a job stops working entirely, because it looks like everything is fine at a glance.

For example:

https://k8s-testgrid.appspot.com/release-1.6-all#Summary

```
kubeadm-gce-1.6: PASSING
No results in the past week

No passing build found
Tests have not run
Last update: 09-11 10:41
```

**Comment by pipejakob** [comment]
Just to cross-reference, the reason that the 1.6 kubeadm tests aren't running any more:
https://github.com/kubernetes/kubernetes/issues/51571

**Comment by krzyzacy** [comment]
(Also I think the pending state does not really work externally (?) )

**Comment by michelle192837** [comment]
Noted, will look at another status (I don't think FAILING or FLAKY works here either, but should have something for no results).

And will look into pending state, since that ought to be enabled.

**Comment by enisoc** [comment]
Related issue: We got the job to start running again, but it is now failing. However, the testgrid summary is showing this as FLAKY, rather than FAILING.

```
kubeadm-gce-1.6: FLAKY
2 of 6 tests (33.3%) and 1 of 1 runs (100.0%) failing in the past week

No passing build found
Tests last ran on: 09-25 15:50
Last update: 09-27 11:12
```

**Comment by michelle192837** [comment]
That one seems correct. There's only one run, and num_failures_to_alert is default 3. FLAKY is when there's failures, but no consistent ones that would constitute an alert. If one of the rows fails 3 or more times in a row, the status should switch to FAILING.

For the 'no results shows passing' bug, I have a fix that should be in this week.

**Comment by enisoc** [comment]
Ah, thanks for the explanation. Would it make sense to redefine FLAKY to mean "no consistent failures, AND at least one success"? It seems misleading to label a test with zero successes as flaky.

**Comment by michelle192837** [comment]
I believe that is the case here, since this tab has no consistent failures and has at least one success (though I may have a different perspective on what those terms mean here).

**Comment by enisoc** [comment]
Are you referring to this tab?

https://k8s-testgrid.appspot.com/release-1.6-all#kubeadm-gce-1.6&width=20

Currently I see only a single column there, and the Overall is red. I would expect that in order to qualify as flaky, there should be at least one column on the grid where Overall is green.

**Comment by michelle192837** [comment]
Ah. That's somewhat fair, but I don't think marking those kinds of tabs as 'FAILING' is as helpful as leaving them 'FLAKY'; a tab can have no consistent failures and also no green columns, and I think differentiating that from 'has consistent failures' is important.

That said, can revisit this later if this is confusing a lot of people.

**Comment by enisoc** [comment]
That's a good point; differentiating them makes sense. I would then request that we differentiate even further by using a new category like "INCONCLUSIVE" rather than "FLAKY".

As a patch release manager, I unfortunately have to treat FLAKY as "everything is fine" because everything is flaky all the time, and we don't have the resources to fix flakes on master, much less on all the release branches:

https://k8s-testgrid.appspot.com/release-1.6-all#Summary&width=20

That's why I'd like to see this condition called out separately from the rest of the "FLAKY" tests. If there has never been a column with a passing Overall, it's something I want to look into.

**Comment by michelle192837** [comment]
Ignoring FLAKY is fine. I think something like this is somewhat of an edge case, since a tab should rarely have only 1-2 runs.

On another note, the summary should have the last passing build on the right; for kubeadm-gce-1.6, it does have 'No passing build found'.

**Comment by michelle192837** [comment]
Update for the STALE status: TestGrid should support STALE as a new status, if 1) there are no results at all (i.e. no column headers), or 2) there's a 'stale' warning on the tab.

It looks like a lot of dashboards are still going to dodge STALE status because they have column headers but no actual results; I'll see about changing that, but what would probably be more useful for everyone is to set 'alert_stale_results_hours' on your test group to have the tab be considered stale if there are no results in X hours.
