### ISSUE TITLE
approval with issue didn't work

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4512]
https://github.com/kubernetes/kubernetes/pull/52178#issuecomment-328680323

/area mungegithub
/assign @apelisse @cjwagner

**Comment by cjwagner** [comment]
The issue should be specified in the body, see [here](https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/approval-handler.go#L87) for how the issue is found.

**Comment by kargakis** [comment]
What does the "body" mean? Is it the body of the initial comment? Is this documented somewhere? I was surprised that /approve #NO wasn't working.

**Comment by cjwagner** [comment]
The main PR description body. This is documented [here](https://github.com/kubernetes/community/blob/62cc2179fbb8536c69b2dfcb42122411732c79cb/contributors/devel/owners.md#quirks-of-the-process).
