### ISSUE TITLE
Job names don't make great labels

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#4550]
`errors syncing: [error starting pod: error creating pod: response has status "422 Unprocessable Entity" and body "{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"61026203-98a5-11e7-8981-0a580a6c0104\" is invalid: metadata.labels: Invalid value: \"ci-kubernetes-e2e-gke-gci-stable2-gci-stable1-upgrade-cluster-new\": must be no more than 63 characters","reason":"Invalid","details":{"name":"61026203-98a5-11e7-8981-0a580a6c0104","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"ci-kubernetes-e2e-gke-gci-stable2-gci-stable1-upgrade-cluster-new\": must be no more than 63 characters","field":"metadata.labels"}]},"code":422}`

/area prow
@rmmh @kargakis

**Comment by spxtr** [comment]
(Along with fixing this, we should maybe mark the prowjob as in an error state when we get 422 back from the API server)

**Comment by kargakis** [comment]
Oh, yeah ... It could still be an annotation if we want it.

**Comment by kargakis** [comment]
Handling the error type should be fine for now. Will submit a PR tomorrow.
