### ISSUE TITLE
Prow Issue: Links for certain prow jobs are missing the build number while job is running.

### ISSUE THREAD

**Issue by sebastienvas** [kubernetes/test-infra#4564]
One Example is https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51768/pull-kubernetes-e2e-gce-bazel//

We experience the same issue in istio  since we updated to the last version, ie plank 0.44

**Comment by stevekuznetsov** [comment]
@sebastienvas just to be clear -- you are seeing links on the k8s Gubernator page missing a build number while it's running? On what pages? Can you send a screenshot of the link you are clicking?

**Comment by sebastienvas** [comment]
I think it is more a Prow bug. It seems that kubernetes fixed it since yesterday night, I am not sure what they did. (I am from istio).

**Comment by stevekuznetsov** [comment]
I can take a look -- you are clicking on build info from a PR overview page for a build that's running?

**Comment by sebastienvas** [comment]
So the issues goes away when the job is complete so its hard to just provide a link. But basically go to https://prow.istio.io and look for pending job and click on the gubernator link

**Comment by sebastienvas** [comment]
Yes the link from the PR page is the same one that does not have the build number

**Comment by stevekuznetsov** [comment]
Oh, this is a link _to_ Gubernator from your Prow instance.

/area prow
/remove-area gubernator

**Comment by sebastienvas** [comment]
I think this is related to https://github.com/kubernetes/test-infra/pull/4565#issuecomment-329577235. 
I have a suspicion that https://github.com/kubernetes/test-infra/pull/4468 introduced this issue. FYI I'll be going back to 0.41 on prow.istio.io

**Comment by kargakis** [comment]
@sebastienvas you need to follow what's outlined in https://github.com/kubernetes/test-infra/pull/4565#issuecomment-329575012 for deploying 0.43 since there is a breaking change in prow (see https://github.com/kubernetes/test-infra/tree/master/prow#announcements). After you deploy 0.43, update the prow config to GC pods older than 1h in order to fast forward pod GC, and after 1h you should be good with deploying 0.44.

**Comment by sebastienvas** [comment]
I can also delete all my pods and prowjobs right ?
I don't see how this will fix the missing buildId in the link do you know ?

**Comment by kargakis** [comment]
I am not sure what's the exact issue you are seeing, I can't find any pending job currently. What version of deck are you running?

**Comment by kargakis** [comment]
Regarding the migration step, if you don't have any running jobs, you don't need to do it.

**Comment by kargakis** [comment]
Sorry, actually, you need the labeling step so that the pods will be eventually GC'd by the new version of sinker.

**Comment by sebastienvas** [comment]
I am running a custom version as I needed a fix until my PR is reviewed (not related to this issue), but once you update to the latest version of plank. you ll see it in kubernetes like I saw it yesterday night before you guys rolled back.

**Comment by BenTheElder** [comment]
Is this still a problem? I'm not finding any examples currently. /cc @ixdy

**Comment by sebastienvas** [comment]
This seems resolved on prow.k8s.io. I ll reopen if I see this after updating istio's.
