### ISSUE TITLE
Jenkins is broken due to maintenance job failure on bootstrap

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#4568]
/assign

**Comment by fejta** [comment]
We need to:

- [ ] Clean up the jenkins nodes
- [ ] Fix bootstrap
- [ ] Fix maintenance jobs
- [ ] Identify and retest effected PRs

**Comment by ixdy** [comment]
^ I believe all but #4 have been done.

**Comment by fejta** [comment]
Cleaning up nodes is in progress
