### ISSUE TITLE
kubetest README file needs to be revamped

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes/test-infra#4578]
I am new to kubetest. I wrote an upgrade test similar to [this](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/upgrades/apps/deployments.go), and wish to run the test using kubetest.

I am able to get kubetest installed and built, but when running `kubetest -up`, there is an error message running: `Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 1`

I peeked into `e2e-up.sh`, but could not deduce reason behind the error. My guess is `kubetest -up` requires some flags such as `-gcp-project` and `-federation` (as mentioned by the [README](https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md) file), but I am not sure what are the required flags.

An error message that states `something went wrong` does not help. I think there is a urgent need to update the README file, especially including a **step-by-step** section to run the tests on GCP.

**Comment by krzyzacy** [comment]
what's your kubetest args? can you paste your full command?

**Comment by crimsonfaith91** [comment]
Just `kubetest -up` initially.
Afterwards, i tried with `kubetest -up -upgrade-args=ginkgo-focus="ReplicaSet" -gcpproject="upgrade"`.
Upgrade GCP project is a cluster that i created using GCP console.

**Comment by crimsonfaith91** [comment]
I can observe that the error happens when running hack script `e2e-up.sh` for flag `-up`. It is before running any script involved for flag `-upgrade-args`.

**Comment by krzyzacy** [comment]
oh - it cannot find `./hack/e2e-internal/e2e-up.sh`, you probably want to run it from your kubernetes repo root

**Comment by crimsonfaith91** [comment]
I did ran it from my kubernetes repo root with command: `../test-infra/kubetest/kubetest -up -upgrade_args=ginkgo-focus="ReplicaSet" -gcp-project="upgrade"`

The reason i didn't indicate `../test-infra/kubetest/kubetest` in previous comment as i can do a symlink to kubetest binary.

**Comment by crimsonfaith91** [comment]
I will update the README file accordingly.
/assign

**Comment by fejta** [comment]
We should change the default value of `-v` to true

**Comment by crimsonfaith91** [comment]
I also found out that some flags used in CI test environment can't be used for `kubetest`. I think they are deprecated. I am still experimenting with various `kubetest` flags - should be able to have a PR out by end of this week / beginning of next week.

**Comment by krzyzacy** [comment]
@crimsonfaith91 has already updated the doc, let's close this for now
