### ISSUE TITLE
Prow logs should support multiple containers

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4581]
The new toy dind based job has two containers, so clicking [the deck link for logs](http://prow.k8s.io/log?job=pull-kubernetes-dind-build&id=1) gives:

`
Log not found: response has status "400 Bad Request" and body "{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod 2f81a0bf-99c0-11e7-89f9-0a580a6c0315, choose one of: [2f81a0bf-99c0-11e7-89f9-0a580a6c0315-0 2f81a0bf-99c0-11e7-89f9-0a580a6c0315-1]","reason":"BadRequest","code":400}
"
`

Though I suspect there may also be issues due to the fact that I named the containers in the PodSpec, which we normally don't do since there is usually only one.

**Comment by spxtr** [comment]
Currently prow [names your container for you](https://github.com/kubernetes/test-infra/blob/4bc31c844807754a861218b550999278b100a2dc/prow/pjutil/pjutil.go#L135). Why does the dind job need two containers?

**Comment by BenTheElder** [comment]
The second container hosts the docker daemon in docker using the official
docker dind image. We could probably replicate this as part of the other
images but that didn't seem ideal for experimentation.

**Comment by BenTheElder** [comment]
I don't think we need this currently, I'm avoiding the dind route anyhow :smile:
