### ISSUE TITLE
CD (daily release?) for prow

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#4584]
/area prow

We are having problems releasing prow. We should deploy first two a non-prod instance and make sure it works there before updating the real thing.

/cc @spxtr @cjwagner @krzyzacy

**Comment by krzyzacy** [comment]
yeah, have a prow-canary cluster, similar to testgrid, and maybe run a few canary jobs there, will be helpful. We can staging boskos there at the same time.

**Comment by spxtr** [comment]
It's a good idea, although it's pretty tricky to do well. How do we plan to make sure it works? Do we have it run tests against a fake PR in a test repo on GitHub? It seems like that's the only way to do it properly.

**Comment by kargakis** [comment]
FWIW, the problem is related to plank specifically. The rest of the components are easier to roll out. We don't need anything Github-related to test plank. Stand up a cluster, run `mkpj` in a loop to create load, monitor plank? I don't know exactly what "monitor" means in this case, ie. when do we fail the test? Prometheus metrics are likely to help but we would need to run prometheus too.

**Comment by krzyzacy** [comment]
Flaky tests are fine, that's part of kubetest staging.

**Comment by kargakis** [comment]
Another idea I have been contemplating lately is the ability to shard the workload  so we can run new and old controllers (plank, jenkins-operator) side by side. A controller may be configured to handle tests for specific repositories as opposed to all of them. For example, say `plank:latest-1` is stable, we could configure it to handle all but test-infra tests, and run a new deployment with `plank:latest` that handles only test-infra tests so we can canary `latest` in a real environment.

**Comment by spxtr** [comment]
That's pretty much doable today, but I think @fejta was against the idea of using test-infra as our canary. Maybe he can say more? I'm not sure of a better way.

**Comment by krzyzacy** [comment]
I tossed a barebone starter.yaml in k8s-prow-staging, and will put in some periodic deployment next

**Comment by BenTheElder** [comment]
@krzyzacy any more news on this? probably still worth looking at.

**Comment by krzyzacy** [comment]
/lifecycle stale
yeah probably - we probably want a release pipeline for prow someday

**Comment by mithrav** [comment]
/remove-lifecycle rotten
 /remove-lifecycle stale
We still need this

**Comment by matthyx** [comment]
@krzyzacy I think I will start working on that after my vacations... can you provide more details on the current status?

**Comment by stevekuznetsov** [comment]
The work here is of two parts:

 - some sort of deployment test to a staging environment with mirrored/forwarded webhooks and everything in dry-run mode
 - actual deployment bumps daily in production

Cluster admins need to be the ones to implement the second part, and FWIW on my end as soon as I bump the commit everything redeploys fine, it's more that we have outages due to breaks that mean HEAD isn't working every day anyway. Unclear if we could have caught the last break with an integration test but something that would automate a dry-run read-only prow deployment would be cool, maybe we register that hook as an external plugin for the real hook?

**Comment by BenTheElder** [comment]
I'm not sure just deploying it gets us much. "our binaries and images build and we can deploy to the cluster" is a fairly low bar... breakages seem to usually involve interactions with config, with events from github / data passed between components... 

Maybe we can automate a deployment against @fejtaverse with fake PRs

**Comment by stevekuznetsov** [comment]
Not sure what you mean, that is why I said...

> something that would automate a dry-run read-only prow deployment would be cool, maybe we register that hook as an external plugin for the real hook?

That way it gets production data and we can easily test a bunch of stuff that would come out on read-only interactions. Obviously not everything, but it would be a good start.

**Comment by matthyx** [comment]
Probably @BenTheElder or other googlers could tell us if [Kayenta](https://cloudplatform.googleblog.com/2018/04/introducing-Kayenta-an-open-automated-canary-analysis-tool-from-Google-and-Netflix.html) is a thing... although we don't use Spinnaker I guess.

**Comment by matthyx** [comment]
/remove-lifecycle rotten
I am very interested by this issue, since I will need to work on something similar on my daily job...
So what prevents us from going to continuous deployment?
Do we document somewhere the "smoke tests" that are manually/automatically run when bumping prow?
Can we leverage Kubernetes to do canary or A/B testing?

**Comment by fejta** [comment]
We do most of this today:
1) we build a prow RC at every commit https://testgrid.k8s.io/sig-testing-misc#deploy-prow 
  - See [post-test-infra-push-prow](https://github.com/kubernetes/test-infra/blob/abb4a516f92476e50bd190f3c30b980948874155/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L49-L66)
2) We deploy the configured version of prow at every commit https://testgrid.k8s.io/sig-testing-misc#push-prow
  - See [post-test-infra-deploy-prow](https://github.com/kubernetes/test-infra/blob/abb4a516f92476e50bd190f3c30b980948874155/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L26-L47)

However note that most of the time for (2) the prow/cluster/*.yaml files have no changes, so the deploy does nothing.

Someone still needs to manually run `prow/bump.sh --list` to select one of the versions created by (1) and create a PR to update the version. As soon as this PR merges ([example](https://github.com/kubernetes/test-infra/pull/10120)) it is deployed. This pattern is by design.

I'm working on adding a daily job which automatically runs `prow/bump.sh --latest` to create a PR that configures the [latest release](https://github.com/kubernetes/test-infra/pull/10154).

We will still want a human to LGTM the PR though.

> Can we leverage Kubernetes to do canary or A/B testing?

That isn't going to help. What we need is a way to canary a repo. We need to say "test-infra" should be handled by the canary version, and whenever that works, push to prod.

> So what prevents us from going to continuous deployment?

Little technically -- it would be easy to change all this to "build and deploy prow at every commit" however we need a place to canary the changes before auto-releasing them to whole k8s org

**Comment by fejta** [comment]
If you want to do CD, the best way is to write a postsubmit job that builds/deploys your code.

**Comment by fejta** [comment]
Also matthyx are you wanting to CD prow or use prow to CD something else?

**Comment by matthyx** [comment]
I wanted to CD prow because it's fun, and a good experience for my company.

Unfortunately we cannot use prow internally for the moment, but a migration to GitHub enterprise is on the way, and we could then move to it...

**Comment by fejta** [comment]
Take a look at https://github.com/kubernetes/test-infra/pull/10172

**Comment by krzyzacy** [comment]
I'll call this done?

/close
