### ISSUE TITLE
golint breaks when files are removed in a PR

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4599]
```
{"author":"kargakis","error":"open /tmp/git421202590/pkg/apps/controller/generictrigger/deploy_generictrigger_controller.go: no such file or directory","level":"error","msg":"Error handling IssueCommentEvent.","org":"openshift","plugin":"golint","pr":14910,"repo":"origin","time":"2017-09-17T20:22:37Z","url":"https://github.com/openshift/origin/pull/14910#issuecomment-330080590"}
```
https://github.com/openshift/origin/pull/14910

@spxtr 
/area prow
/kind bug

**Comment by spxtr** [comment]
Ooh, that's right. We can either change [`modifiedGoFiles`](https://github.com/kubernetes/test-infra/blob/4bc31c844807754a861218b550999278b100a2dc/prow/plugins/golint/golint.go#L61-L86) to handle the status of the [`PullRequestChange`](https://github.com/kubernetes/test-infra/blob/4bc31c844807754a861218b550999278b100a2dc/prow/github/types.go#L125-L134) object (btw I think that json tag is wrong), or else just silently ignore a file missing error when we try to load it. Both seem reasonable to me.
