### ISSUE TITLE
Bot's strange behavior in PR

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4629]
See in : https://github.com/kubernetes/kubernetes/pull/52706

* The PR has `needs-ok-to-test` label and no one commented `/ok-to-test` or `/lgtm`, but the tests are triggered.
* One of the tests failed, the bot didn't comment to tell what test failed.

**Comment by xiangpengzhao** [comment]
Also see `Error starting Jenkins job.` in https://github.com/kubernetes/kubernetes/pull/52702

Clicking the details will be redirected to https://github.com/kubernetes/test-infra/issues.

![image](https://user-images.githubusercontent.com/15881573/30591139-3654a692-9d74-11e7-9f7f-77d1303e8ee9.png)

**Comment by mrIncompetent** [comment]
Also happened in https://github.com/kubernetes/kubernetes/pull/52645

**Comment by xiangpengzhao** [comment]
See also in https://github.com/kubernetes/kubernetes/pull/52719

**Comment by kargakis** [comment]
Yeah, this seems a Jenkins-related issue aka infra issue thats' why you are redirected to test-infra. There is already https://github.com/kubernetes/test-infra/issues/4603

**Comment by fejta** [comment]
Please reactivate if you find another example of a PR that is triggering tests when it shouldn't.
