### ISSUE TITLE
PR jobs using jenkins should only be always_run if they are blocking

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4637]
We need to reduce pressure on jenkins right now in particular during the code freeze. There are a few `pull-kubernetes-*` jobs that are non-blocking but also `agent: jenkins` and `always_run: true`. We should flip these jobs to `always_run: false`.

This was discussed with the community in "sig-testing test-infra oncall standup" today.

/area jenkins
/assign

**Comment by kargakis** [comment]
https://github.com/kubernetes/test-infra/pull/4630 should help

**Comment by BenTheElder** [comment]
@kargakis thanks, I will look at #4630 soon :smile:
