### ISSUE TITLE
Search for test infra changes

### ISSUE THREAD

**Issue by krousey** [kubernetes/test-infra#4646]
Often when debugging issues on testgrid, I drag between two build and then click search for changes. That does me the convenience of finding all the changes between the 2 commits in the repo so I can see what changed. Occasionally, the issue I'm looking for is actually in the test infra structure. And I noticed that the second row of commits if for test infra.

It would be nice to have a context menu option of searching for changes in test-infra.

cc @rmmh @krzyzacy

**Comment by krzyzacy** [comment]
cc @michelle192837

**Comment by spiffxp** [comment]
/assign @krzyzacy 
per sig-testing v1.9 roadmap

**Comment by BenTheElder** [comment]
/remove-help
This is not something external contributors can help with yet...

**Comment by krzyzacy** [comment]
/remove-lifecycle rotten
/assign @michelle192837 
maybe we can append a different code search path for test-infra as well?

**Comment by michelle192837** [comment]
I don't think I have the bandwidth to add this anytime soon, but if another internal person wants to feel free.

(Alternatively, I couldn't find an easy way to search more than one repo on GitHub, but if there is one that'd be convenient ^^)

**Comment by krzyzacy** [comment]
allow multiple diff? I kinda already added test-infra commit into the column header.
definitely not high priority :-) just glancing through all the issues.

**Comment by michelle192837** [comment]
Fair ^^

It's mainly just that right now, a few places assume there's just one code_search_path string; I don't think it'd be too hard to allow more than one, it'd just be some non-trivial work. It'd be possible to hard-code a second one on Kubernetes dashboards as well, but less ideal (though a lot less work).

**Comment by BenTheElder** [comment]
when we switch to the pod-utils we won't be uploading the infra-commit anymore anyhow...

**Comment by krzyzacy** [comment]
@BenTheElder we probably still want to upload the SHA for config version, so people can still see if a test failure is caused by config change or k/k change

**Comment by fejta** [comment]
/remove-lifecycle stale

Michelle can we sneak this in before declaring testgrid code perfection and having achieved enlightenment?

**Comment by BenTheElder** [comment]
the test-infra commit metadata goes away when we switch to podutils and stop checking out test-infra in every job though FWIW

**Comment by michelle192837** [comment]
/reopen
/remove-lifecycle rotten

Keeping this around; test-infra isn't the only place this would be useful, and still want to keep it on the radar.

**Comment by michelle192837** [comment]
Filed a more general version of this at https://github.com/GoogleCloudPlatform/testgrid/issues/19
