### ISSUE TITLE
status updates for run_after_success jobs seem to be bugged

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4662]
Observed in the wild here:
https://github.com/kubernetes/kubernetes/pull/51064#issuecomment-330968747

[The kubeadm job failed](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51064/pull-kubernetes-e2e-kubeadm-gce/7151/) but was still marked as `"Parent Job Status Changed: Job triggered."`

/cc @luxas @kargakis

**Comment by kargakis** [comment]
The kubeadm job was never meant to trigger for the linked PR (see `run_if_changed` below; fixed by https://github.com/kubernetes/test-infra/pull/4586)
https://github.com/kubernetes/test-infra/blob/b4a4bd5a8c4f15c9cd4d40a371edf8242663e140/prow/config.yaml#L93-L98
Also, it was never meant to report (`skip_report: true`). Maybe https://github.com/kubernetes/test-infra/pull/4563 was deployed in the meantime?

**Comment by krzyzacy** [comment]
hummm, @kargakis we are still running 0.46

**Comment by kargakis** [comment]
Anything interesting in the plank log?

**Comment by krzyzacy** [comment]
nothing from plank
hook has bunch of
`
{"context":"pull-kubernetes-e2e-kubeadm-gce","id":1563938134,"level":"info","msg":"Status description Parent Job Status Changed: Job triggered..","org":"kubernetes","repo":"kubernetes","sha":"e0f11befdf1a5180678ba3853dc90c4a7de99164","state":"pending","time":"2017-09-20T19:27:22Z"}
`

**Comment by BenTheElder** [comment]
Hmm this still seems to be a problem: https://kubernetes.slack.com/archives/C09R23FHP/p1506049583000002

[The kubemark job also seems to be consistently failing](http://prow.k8s.io/?job=pull-kubernetes-e2e-kubeadm-gce). 😕

**Comment by BenTheElder** [comment]
see also: https://github.com/kubernetes/test-infra/issues/4564

**Comment by BenTheElder** [comment]
I think it may actually be possible that these are PRs that triggered `pull-kubernetes-e2e-kubeadm-gce` before it was changed to be `run_if_changed`. I'm testing this theory in https://github.com/kubernetes/kubernetes/pull/52755

**Comment by kargakis** [comment]
Can you test with the latest version of plank? We are running it w/o a problem but we don't use run_after_success jobs yet. I can test it tomorrow.

**Comment by krzyzacy** [comment]
cc @cjwagner - 
I think we can update plank tomorrow after 1.8 gets out

**Comment by BenTheElder** [comment]
@kargakis Unfortunately the bazel build is now failing on that dummy PR so it's not getting tested with anything yet while I look into that :disappointed:

**Comment by BenTheElder** [comment]
Oh hmm @luxas kubeadm is set to `skip_report: true` now. Should that still be the case?

**Comment by BenTheElder** [comment]
It doesn't seem to be reporting on PRs where it shouldn't anymore so I think we can close this now. I think this was just another issue with job configurations being in flight while PRs were open. @kargakis if you do test this and find a problem re-open, but I think we can close this now. I can't find this in the wild anymore.

@luxas now that it only runs on build changes, should we flip `skip_report` back off?

**Comment by luxas** [comment]
Great, now it doesn't report on unrelated PRs, thanks!
(example: https://k8s-gubernator.appspot.com/pr/53119)
But it now does on https://k8s-gubernator.appspot.com/pr/53114, which touched `cmd/kubeadm`.

Whohoo, I can now flip `skip_report: false` :tada: :tada:

**Comment by BenTheElder** [comment]
This is still possibly an issue, I think it's actually because of stale PRs, re-opening while I look around. If it's just stale PRs I'll migrate to a new issue about that.

**Comment by BenTheElder** [comment]
/close
this is a broader issue, see #4912
