### ISSUE TITLE
Kubelet Tests Not Listed in 1.8 Release Blocking

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#4664]
For [1.7](https://k8s-testgrid.appspot.com/release-1.7-blocking) we had the node tests listed but for [1.8](https://k8s-testgrid.appspot.com/release-1.8-blocking) we are missing them.

Can we update the dashboard?

@kubernetes/sig-release-feature-requests

**Comment by grodrigues3** [comment]
cc @jdumars

**Comment by jdumars** [comment]
cc @ericchiang

**Comment by krzyzacy** [comment]
whoops - that's in https://k8s-testgrid.appspot.com/sig-node#kubelet-1.8, forgot to toss into release dashboard
