### ISSUE TITLE
jenkins-operator: prowjob for job in jenkins with no builds crashes the operator

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#4683]
When we set up a new job in Jenkins with no builds and someone triggered it using `/test <name>` we saw the ProwJob get created, then the system ground to a halt as the `jenkins-operator` logs showed this:

```
{"error":"error listing jenkins builds: response not 2XX: 502 Bad Gateway","level":"error","msg":"Error syncing.","time":"2017-09-21T21:20:35Z"}
```

Until we manually triggered a build. 

Corollary: the thundering herd of builds to schedule once this got resolved is probably going to crash our master.

/area prow
/kind bug
/cc @kargakis @spxtr

**Comment by stevekuznetsov** [comment]
In a perfect world Jenkins would not collapse under the weight of a couple hundred or a thousand queued jobs, but this is not the case. Maybe we should internally buffer a queue and spoon-feed Jenkins?

**Comment by kargakis** [comment]
This seems like an issue with our proxy. I will look into it tomorrow.

**Comment by kargakis** [comment]
> Corollary: the thundering herd of builds to schedule once this got resolved is probably going to crash our master.

We can add slow starts in the controller similar to what was done recently for all workload controllers in https://github.com/kubernetes/kubernetes/pull/49142

**Comment by kargakis** [comment]
Or have a max_concurrency field that applies to all prowjobs globally.

**Comment by kargakis** [comment]
Opened https://github.com/kubernetes/test-infra/issues/4691

**Comment by kargakis** [comment]
@spxtr you are not using any boolean parameters inside your Jenkins jobs, is that correct?

**Comment by kargakis** [comment]
For clarity, here is the downstream issue: https://github.com/openshift/release/issues/169
