### ISSUE TITLE
Avoid hammering agent api (k8s/jenkins) on herd of triggered prowjobs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4691]
We could either implement slow starts (similar to https://github.com/kubernetes/kubernetes/pull/49142), or a global max_concurrency option that applies to all running jobs in the system.

@stevekuznetsov @spxtr 
/area prow

**Comment by stevekuznetsov** [comment]
Do we have the adequate feedback mechanism with Jenkins to know when to back off as we increase batch size? Agree that approach makes sense for Pods.

**Comment by stevekuznetsov** [comment]
Global maximum concurrency is probably easier though, and should be easy to set for Jenkins agents -- total number of executor slots + N.

**Comment by kargakis** [comment]
Yeah, I think a global option is easier to reason about. @spxtr thoughts? I will open a PR later today if I manage to get at it.

/assign

**Comment by spxtr** [comment]
I'm okay with a global max concurrency but we probably won't use it on our prow instance.

**Comment by stevekuznetsov** [comment]
You guys saw your Jenkins fall over for the same reason last week so perhaps per-agent it's useful?

**Comment by kargakis** [comment]
Yeah, this will only apply per-agent but I don't think we need separate fields.

**Comment by spxtr** [comment]
Our solution is to move the jobs that still run on Jenkins into k8s pods :)

Per-agent would be important since we're running all of our CI jobs on prow as k8s pods already, which is a couple hundred at a time at least. Jenkins will fall over with a couple hundred jobs in the queue.

```
$ curl -Ss https://prow.k8s.io/data.js | jq '[.[] | select(.agent == "kubernetes") | select(.state == "pending")] | length'
224
$ curl -Ss https://prow.k8s.io/data.js | jq '[.[] | select(.agent == "jenkins") | select(.state == "pending")] | length'
9
```
Evidently the west coast hasn't woken up yet.

**Comment by kargakis** [comment]
Hrm, yeah. Today jenkins-operator is using the [plank config](https://github.com/kubernetes/test-infra/blob/ffe9f34e952b1b6d388068b82f2a0fcb3ba4f799/prow/config.yaml#L1-L3). We should split it into a separate stanza so we can have per-agent fields (we should be able to extend config.Config inside prow/jenkins).
