### ISSUE TITLE
investigate docker-in-docker brokenness with kubekins-test and docker 1.11.1

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#47]
As part of the Jenkins VM rebuild today, some nodes were upgraded to docker 1.11.1, instead of 1.9.1, as we'd been using before.

It seems that this causes problems for docker-in-docker in our kubekins-test image:
```
Verifying ./hack/../hack/verify-api-reference-docs.sh
Note: This assumes that swagger spec has been updated. Please run hack/update-swagger-spec.sh to ensure that.
Generating api reference docs at /go/src/k8s.io/kubernetes/_output/generated_html
Reading swagger spec from: /var/lib/jenkins/workspace/kubernetes-pull-test-unit-integration@2/api/swagger-spec/
docker: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory
!!! Error in ./hack/update-api-reference-docs.sh:71
  'docker run ${user_flags} --rm -v "${TMP_IN_HOST}":/output:z -v "${SWAGGER_PATH}":/swagger-source:z gcr.io/google_containers/gen-swagger-docs:v5 "${SWAGGER_JSON_NAME}" "${REGISTER_FILE_URL}"' exited with status 127
Call stack:
  1: ./hack/update-api-reference-docs.sh:71 main(...)
Exiting with status 1
!!! Error in ./hack/../hack/verify-api-reference-docs.sh:34
  '"./hack/update-api-reference-docs.sh" "${OUTPUT_DIR}"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-api-reference-docs.sh:34 main(...)
Exiting with status 1
FAILED   ./hack/../hack/verify-api-reference-docs.sh	1s
```

@bprashanth

**Comment by ixdy** [comment]
Most likely `libltdl7` is missing from the `kubekins-test` image, and we need to add it.

Unfortunately, this means we may need to update the old release branches to the new `kubekins-test` image if we're ever going to upgrade docker on Jenkins, which also means we'll bump up the version of Go we use there. We probably should start versioning infra changes separately from Go verisons, like we now do for crossbuild.

**Comment by fejta** [comment]
@ixdy what is left to do here?

**Comment by ixdy** [comment]
My last comment describes what needs to be done. It hasn't been done yet.
