### ISSUE TITLE
federation e2e gce automated tests on Jenkins fail consistently with token auth attempt failed with status: 403 Forbidden

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/test-infra#470]
+++ [0829 21:48:48] Pushing gcr.io/k8s-jkns-pr-bldr-e2e-gce-fdrtn/hyperkube:v1.4.0-alpha.3.197_ef82f394a9e1ba
 -> GCR repository detected. Using gcloud
@nikhiljindal I think you know about this, but just so we don't lose track of it, here's an issue to track it.

See https://github.com/kubernetes/kubernetes/pull/31655#issuecomment-243330580 for an example...

@k8s-bot federation gce e2e test this

The push refers to a repository [gcr.io/k8s-jkns-pr-bldr-e2e-gce-fdrtn/hyperkube] (len: 1)
6864c6906300: Preparing
Post https://gcr.io/v2/k8s-jkns-pr-bldr-e2e-gce-fdrtn/hyperkube/blobs/uploads/: token auth attempt for registry: https://gcr.io/v2/token?account=oauth2accesstoken&scope=repository%3Ak8s-jkns-pr-bldr-e2e-gce-fdrtn%2Fhyperkube%3Apush%2Cpull&service=gcr.io request failed with status: 403 Forbidden
!!! Error in ./build/../build/../federation/cluster/common.sh:321
  'gcloud docker push "${docker_image_tag}"' exited with status 1
Call stack:
  1: ./build/../build/../federation/cluster/common.sh:321 push-federation-images(...)
  2: ./build/push-federation-images.sh:29 main(...)
Exiting with status 1
Build step 'Execute shell' marked build as failure

**Comment by ixdy** [comment]
Most likely ACLs for the `pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com` service account are missing somewhere.

**Comment by nikhiljindal** [comment]
I had created the project using the standard create project script which should have setup ACLs correctly.

The job is running in `k8s-jkns-pr-bldr-e2e-gce-fdrtn` project and we are running `gcloud docker push <image-name>` to the same project, so no extra credentials should be required.

@madhusudancs had suggested running gsutil acl to ensure the right ACL on the GCS bucket, but running:

```
gsutil acl ch -u pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com:R gs://artifacts.k8s-jkns-pr-bldr-e2e-gce-fdrtn.appspot.com
```
obviously fails with 
```
BucketNotFoundException: BucketNotFoundException: 404 gs://artifacts.k8s-jkns-pr-bldr-e2e-gce-fdrtn.appspot.com bucket does not exist.
```

Trying to create that bucket using the UI asks me to verify that I own appspot.com :)

cc @colhom How did you set up `artifacts.k8s-jkns-e2e-gce-federation.appspot.com` GCS?

**Comment by madhusudancs** [comment]
> @madhusudancs had suggested running gsutil acl to ensure the right ACL on the GCS bucket, but running:

If you are running in the same project, you don't need any of these ACL changes I suggested. You only need the ACL changes when the build artifacts and test VMs are in different projects.

> Trying to create that bucket using the UI asks me to verify that I own appspot.com :)

I don't think you can create appspot.com buckets. And also, you don't have to :) Then first time you run `gcloud docker push`, GCR automatically creates this bucket for you.

I think @ixdy is right. This is a credentials issue. And I think it is likely because (pure guess, zero evidence) the job that's running `gcloud docker push` doesn't have push access to `gcr.io/k8s-jkns-pr-bldr-e2e-gce-fdrtn/hyperkube`. 

I know this feels like a frustrating chicken & egg problem. I think the solution here is to add the service account of the project where you run `gcloud docker push` (`kubernetes-jenkins-pull` I think?) as an editor or some other role which has write access to your `k8s-jkns-pr-bldr-e2e-gce-fdrtn` project. Ping me on chat, I will point you to the right links/pages.

**Comment by nikhiljindal** [comment]
Ran the following command which should have been run anyway by the create_jenkins_project script if i had set the flags correctly while calling it (which I may or may not have :)):
```
gcloud projects add-iam-policy-binding "k8s-jkns-pr-bldr-e2e-gce-fdrtn" --member "serviceAccount:pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com" --role roles/editor
```
Will see if that fixes the problem.
Thanks!

**Comment by nikhiljindal** [comment]
That didnt fix it.
Still the same error.

**Comment by ixdy** [comment]
@nikhiljindal link to the log?

**Comment by nikhiljindal** [comment]
@ixdy https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/30458/kubernetes-pull-build-test-federation-e2e-gce/11/

**Comment by ixdy** [comment]
Argh! https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/build.sh#L56

I'm pretty sure we don't need this `git clean`. I'm going to test just removing it.

**Comment by ixdy** [comment]
Removing `git clean` appears to have worked: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32158/kubernetes-pull-build-test-federation-e2e-gce/16/

Next issue is a lack of resources. :)

**Comment by nikhiljindal** [comment]
The image push issue is fixed now.
The error now is:
```
ERROR: (gcloud.compute.networks.create) Some requests did not succeed:
 - Quota 'NETWORKS' exceeded. Limit: 5.0
```

I have submitted a request for increasing the network quota to 15.
