### ISSUE TITLE
k8sio-netlify-preview-bot info

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/test-infra#4711]
@k8sio-netlify-preview-bot is not linked to any issue tracker to help people track related issues, such as https://github.com/kubernetes/kubernetes.github.io/issues/4657

Does it belong here?

**Comment by BenTheElder** [comment]
I don't think so, I haven't seen anything related to it in this repo and it looks like this is something from netlify, not us. I would suggest that those issues probably _are_ best tracked at [kubernetes/kubernetes.github.io/](https://github.com/kubernetes/kubernetes.github.io/issues) or somewhere with Netlify per https://github.com/kubernetes/kubernetes.github.io/issues/4657#issuecomment-320803740

**Comment by abitrolly** [comment]
`test-infra` is an official [bots home](https://github.com/kubernetes/test-infra/tree/master/prow#bots-home), so it's somewhat related.

**Comment by BenTheElder** [comment]
Yes, but it is *actually* the home for those bots -- as far as I can tell that bot is Netflify's and we don't have any source code, configuration, or docs for it. It only appears to run against [kubernetes/kubernetes.github.io](https://github.com/kubernetes/kubernetes.github.io/) so  issues should have better visibility on the kubernetes.github.io tracker where EG @chenopis might notice and can escalate to someone from Netlify like the previous issue, though that doesn't seem to have a follow-up :confused:

**Comment by abitrolly** [comment]
The key issue is mapping of transformation from target documents to source. I guess that capability is out of Netlify domain, because it doesn't know anything about the documents transformation process. The only solution I see is catch the Netlify message, calculate and inject this info by separate handler.

**Comment by chenopis** [comment]
The @k8sio-netlify-preview-bot is only meant to run on https://github.com/kubernetes/kubernetes.github.io/ to add a comment to PRs w/ the Netlify preview link. I did setup the account for that bot so that their [pull request comments mechanism](https://www.netlify.com/docs/webhooks/#github-pull-request-comments) could use a GitHub token other than my own.

We do have support from them, and I did ask them about potentially improving the notifications to include direct links to the affected pages (re: https://github.com/kubernetes/kubernetes.github.io/issues/4657). However, currently, it seems low priority for them.

**Comment by abitrolly** [comment]
@chenopis if Netlify integrates with GitHub as [GitHub App](https://developer.github.com/apps/building-integrations/setting-up-a-new-integration/about-integrations/) then it should only ask permission for commenting on PRs and not use your token.

Can you clarify the workflow a little bit more? With a diagram perhaps. Is there a prow endpoint that Netlify webhook sends data to?

**Comment by chenopis** [comment]
@abitrolly Ok, thanks for the suggestion. It doesn't look like it's a GitHub App right now, but I'm asking Netlify if they can do that.

Here is their documentation on their GitHub Notifications: https://www.netlify.com/docs/webhooks/#outgoing-webhooks-and-notifications

Here are screenshots of the workflow in their interface:
<img width="941" alt="screen shot 2017-10-16 at 11 40 51 am" src="https://user-images.githubusercontent.com/24798125/31628962-0cb25e80-b267-11e7-8147-70eb1f1fbb48.png">
<img width="424" alt="screen shot 2017-10-16 at 11 41 09 am" src="https://user-images.githubusercontent.com/24798125/31628973-14540f62-b267-11e7-943c-6a1b48d4b865.png">
<img width="608" alt="screen shot 2017-10-16 at 11 41 40 am" src="https://user-images.githubusercontent.com/24798125/31628983-1abc8b86-b267-11e7-9f0d-065a03d0425d.png">

So, I just generate or enter an access token, which I currently get from the @k8sio-netlify-preview-bot.
