### ISSUE TITLE
kubeadm tests not running on release-1.6 branch

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#4716]
According to https://github.com/kubernetes/kubernetes/issues/51571, the kubeadm tests stopped running when the bazel build broke on the 1.6 branch. However, the kubeadm tests are still not running on the 1.6 branch, even after the bazel build was fixed.

https://k8s-testgrid.appspot.com/release-1.6-all#kubeadm-gce-1.6&width=20
https://k8s-testgrid.appspot.com/release-1.6-all#periodic-kubeadm-gce-1.6&width=20

cc @pipejakob

**Comment by krzyzacy** [comment]
http://prow.k8s.io/?job=periodic-kubernetes-bazel-test-1-6 is all busted

**Comment by enisoc** [comment]
@krzyzacy Are you saying that fixing periodic-bazel-test-1-6 should cause the kubeadm tests to start running again? Or is that just incidental?

**Comment by BenTheElder** [comment]
In release-1-6 and release-1-7 these kubeadm jobs are chained after bazel-build -> bazel-test -> kubeadm for some reason, so it looks like the test job is also borked.

**Comment by BenTheElder** [comment]
`//pkg/kubelet/config:go_default_test` has been failing for the bazel-test jobs

**Comment by luxas** [comment]
Thanks @BenTheElder!
Just noting that these ran fine before bazel was broken on the v1.6 branch.
Meanwhile it seems like stuff has changed in test-infra, which I think https://github.com/kubernetes/test-infra/pull/4717 now addresses. Let's see what happens after that PR is merged :100:

**Comment by enisoc** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/53016 for the kubelet/config test failure.

**Comment by BenTheElder** [comment]
This should be fixed in #4717 to not depend on bazel-test, I'll come back and close once we see some results :-)

**Comment by luxas** [comment]
Now it started running at least...

**Comment by BenTheElder** [comment]
These are definitely running now. They're still failing for unrelated issues though, which should probably be tracked somewhere else (k/k?)

**Comment by luxas** [comment]
We'll look into that, probably some test infra knob that we have to update that has changed since these were created. Thanks!
