### ISSUE TITLE
Some jobs are missing artifacts

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#4724]
for example, https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/periodic-kubernetes-e2e-kubeadm-gce-1-8/1246

probably https://github.com/kubernetes/test-infra/pull/4703

/assign @ixdy 

cc @BenTheElder @luxas

**Comment by BenTheElder** [comment]
also https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-test-infra-bazel/59488

**Comment by krzyzacy** [comment]
(maybe https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py#L578 ?)

**Comment by BenTheElder** [comment]
There's a mix of `/workspace.*` literals and `$WORKSPACE` usage throughout the various scripts (bootstrap, scenarios, etc) we should probably standardize on $WORKSPACE everywhere for now so this doesn't break next time.
¯\\\_(ツ)\_/¯

**Comment by ixdy** [comment]
I think bootstrap expects `_artifacts` to live in `$(cwd)/_artifacts`, but in kubetest we use `$WORKSPACE/_artifacts`. these are no longer the same place in all environments.

**Comment by BenTheElder** [comment]
> I think bootstrap expects _artifacts to live in $(cwd)/_artifacts, but in kubetest we use $WORKSPACE/_artifacts. these are no longer the same place in all environments.

Yeah, line 943:

```python
            finish(gsutil, paths, success, '_artifacts', build, version, repos, call)
```
Some of `scenarios/kubernetes_e2e.py` is similarly bugged with respect to assumptions about where workspace is, that just happens to work since `$WORKSPACE` *is* `/workspace` currently.

**Comment by ixdy** [comment]
bootstrap has basically no knowledge of `$WORKSPACE` (possibly by design), which makes this trickier.

**Comment by BenTheElder** [comment]
bootstrap should be able to know about `$WORKSPACE` after `setup_magic_environment` has been called :laughing:

**Comment by ixdy** [comment]
hm:
https://github.com/kubernetes/test-infra/blob/6244c9b8649d19c1016e572982cc2949e5a31ede/kubetest/e2e.go#L529

hmm:
https://github.com/kubernetes/test-infra/blob/6244c9b8649d19c1016e572982cc2949e5a31ede/kubetest/main.go#L43

hmmm:
https://github.com/kubernetes/test-infra/blob/6244c9b8649d19c1016e572982cc2949e5a31ede/images/pull_kubernetes_bazel/coalesce.py#L81

**Comment by BenTheElder** [comment]
I'm about to roll out a PR to fixup `kubernetes_e2e`, I guess those are next. ¯\\\_(ツ)\_/¯

**Comment by krzyzacy** [comment]
more: http://k8s-testgrid.appspot.com/sig-node#kubelet
cc @Random-Liu

**Comment by ixdy** [comment]
@krzyzacy yeah I think that one is due to https://github.com/kubernetes/test-infra/blob/6244c9b8649d19c1016e572982cc2949e5a31ede/kubetest/e2e.go#L529

**Comment by krzyzacy** [comment]
@ixdy I think that's used for node canary job only - the actual node job still runs from some k/k script

**Comment by krzyzacy** [comment]
(probably easier to finish https://github.com/kubernetes/test-infra/pull/4338)

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/jenkins/e2e-node-jenkins.sh#L39

the node job is actually using the right artifacts dir, but kubetest is not :-(

**Comment by ixdy** [comment]
It looks like the last node e2e job ran before #4725 was merged, so hopefully it's fixed, yeah.

**Comment by krzyzacy** [comment]
I think this is resolved, gonna close the issue for now.
