### ISSUE TITLE
Common interface for prow agent controllers

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4744]
Once https://github.com/kubernetes/test-infra/pull/4630 merges, reconciling jobs in the jenkins-operator will be almost identical to what plank is doing. Ideally, we can collapse all of the remaining common parts into a `prow/controller` library or something and provide an interface for abstracting agent-specific mutations.

More things to think about:
* how do we want to structure agent config inside the prow config file (https://github.com/kubernetes/test-infra/pull/4742)
* ~~logging in deck (https://github.com/kubernetes/test-infra/issues/3407)~~

/area prow

**Comment by kargakis** [comment]
It's going to be hard to have a common interface between plank and jenkins-operator or rather plank and any controller that controls an external CI system because of the nature of having to deal with resources external to k8s.

/kind feature

**Comment by stevekuznetsov** [comment]
I think if we boil out the boilerplate for the informer-driven controller we should do a lot to fix this issue, guess we could try to tease apart the specific `ProwJob` state transitions and create a controller factory that lets you register handlers for each?
