### ISSUE TITLE
Tide should skip merging PRs that are have the `mergeable` field set to `false` 

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#4752]
The current behavior works, but unnecessarily tries to merge PRs that need a rebase instead of ignoring them. 

/assign @spxtr

**Comment by spxtr** [comment]
Do you mean `false`?

**Comment by cjwagner** [comment]
@spxtr 😝  Fixed.

**Comment by spxtr** [comment]
[Pull requests](https://developer.github.com/v4/reference/object/pullrequest/) have a [mergeable](https://developer.github.com/v4/reference/enum/mergeablestate/) attribute that we can look at. Our GitHub client already exposes [the type](https://godoc.org/github.com/shurcooL/githubql#MergeableState). Should be a simple change :)

**Comment by BenTheElder** [comment]
Any progress on this?

**Comment by spxtr** [comment]
No, it's a very minor thing. P3 :)
