### ISSUE TITLE
Plank sets state to pending when pod creation fails.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#4753]
If plank fails to start a pod for a new prowjob starting in the 'triggered' state, it sets the job state to 'ErrorState' here: https://github.com/kubernetes/test-infra/blob/master/prow/plank/controller.go#L340
However the job's state will then be set to pending here: https://github.com/kubernetes/test-infra/blob/master/prow/plank/controller.go#L359
The next sync loop the job will be considered pending, but wont have a pod. If the pod creation fails again then the job will be set to 'ErrorState' for real. This isn't a critical problem because the incorrect state is remediated during the next sync loop, but it should still be corrected.
/assign

**Comment by kargakis** [comment]
We have a test case for 422 errors (when we move triggered jobs to error). Is the test broken? We should probably add a test case for errors other than 422 (we will retry in the next sync and the job stays triggered).
https://github.com/kubernetes/test-infra/blob/1d31c9b0defded29c5444210c98a755f18222725/prow/plank/controller_test.go#L345-L360

**Comment by cjwagner** [comment]
I was wrong, this isn't a problem. In my example the state isn't set to 'pending' because the conditional won't be entered. Thanks @kargakis , I'll add a test case for another error type.
