### ISSUE TITLE
handle PRs in alternate repos properly

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#476]
Gubernator seems to work correctly only on the main kubernetes repo.

For example,  https://k8s-gubernator.appspot.com/pr/1271 is a PR against the kubernetes/heapster repo, but the "view on GitHub" link takes you to kubernetes/kubernetes. And if there happened to be a kubernetes/kubernetes PR 1217 with results, it would be erroneously intermixed.

**Comment by spxtr** [comment]
I think this is a symptom of a bigger problem: jobs from different repos are writing their PR logs into `gs://kubernetes-jenkins/pr-logs/pull/#`. As we break kubernetes into separate repos we'll need to fix this, since the chance of PR # collisions will go up.

**Comment by ixdy** [comment]
yeah, I didn't really think about multiple repos when writing the upload-to-gcs script.

**Comment by ixdy** [comment]
We could put logs in `pr-logs/pull/$REPO/$PR`. Not sure how best to handle the switch-over in gubernator, though.

**Comment by rmmh** [comment]
If you fix the uploader script, I can fix Gubernator. The path for that might be "/pr/heapster/1271".

Whether `google/cadvisor` should go in `pr-logs/pull/cadvisor` or `pr-logs/pull/google/cadvisor` or whatever doesn't seem like as big of an issue.

**Comment by fejta** [comment]
What is next for this issue? Are you still working on it Joe?

**Comment by rmmh** [comment]
This is mostly complete, I'll fix any remaining issues as they come up.
