### ISSUE TITLE
Autoreload Prow secrets.

### ISSUE THREAD

**Issue by crunk1** [kubernetes/test-infra#4761]
While debugging, I autogenerated a new oauth token for my Prow cluster. This invalidated the previous token (which was working). I added the new token to the Prow cluster secrets, but hook jobs were getting Bad Credentials errors when trying to run presubmit on PRs.

Bouncing the Hook and Plank jobs fixed the issue.

**Comment by spxtr** [comment]
It's certainly possible. We can make the GitHub client regularly watch the secret file like the config agent. This might also tidy up some repeated secret reading code.

**Comment by kargakis** [comment]
unassign

**Comment by BenTheElder** [comment]
Heh, so it also reopened it for you while simulataneously commenting that you can't do that :|
@cjwagner

**Comment by cjwagner** [comment]
> Heh, so it also reopened it for you while simulataneously commenting that you can't do that :|
> @cjwagner

Nah, @kargakis deleted some other comments.
I agree that the ACLs for `/reopen` should be looser though.

**Comment by kargakis** [comment]
There is a different PR/issue where I managed to reopen on a single comment but I wasn't lucky enough on this one :(

**Comment by kargakis** [comment]
@droslean
