### ISSUE TITLE
The /sig foo should also tag @org/sig-foo

### ISSUE THREAD

**Issue by mfojtik** [kubernetes/test-infra#4765]
It would be nice if using `/sig foo` in addition to add the GitHub label also tag the `@org/sig-foo` team (if such team exists).

cc @kargakis

**Comment by kargakis** [comment]
/area prow

cc @cjwagner @grodrigues3 @spxtr

**Comment by cblecker** [comment]
two thoughts.. sometimes people want to add a sig label without pinging the team (they could just ping the team themselves if they wanted to). also, if a sig has multiple teams (-bugs, -pr-reviews, -misc, etc) which one would you tag if you just did /sig?

**Comment by cjwagner** [comment]
The `/sig` command intentionally avoids pinging the team and only adds the label. This is useful for categorizing issues without pinging teams unnecessarily.
If you want to notify a team *and* add a `sig/*` label, just directly ping the team with an @-mention. The bot will identify the `sig/*` label associated with the mentioned team and apply it. Additionally, if you don't have permission to trigger a github notification to the team with a mention, the bot reiterates the mention on the user's behalf to trigger a notification.
