### ISSUE TITLE
Can't reopen a PR in kubernetes/kubernetes.github.io

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4768]
See:

https://github.com/kubernetes/kubernetes.github.io/pull/3711#issuecomment-332614890

https://github.com/kubernetes/kubernetes.github.io/pull/3711#issuecomment-332615123

**Comment by mattmoor** [comment]
/assign @fejta 
demo

**Comment by BenTheElder** [comment]
I found the bug, it's very small :-) fixing...

**Comment by BenTheElder** [comment]
heh: https://github.com/kubernetes/kubernetes.github.io/pull/3711#issuecomment-332702465
