### ISSUE TITLE
prow: admin console user stories

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#4788]
As a Prow administrator, I need to:

- determine if an event got picked up by `hook`
- determine what action `hook` plugins took on that event
- determine the events in  the lifetime of a specific prowjob
- connect a prowjob or prowjobs to a trigger comment
- see when a controller (_e.g._ `jenkins-operator`) is having anomolous behavior

/cc @kargakis

**Comment by stevekuznetsov** [comment]
Since we've got structured logs, maybe we can get ELK down and use that to make this easier?

**Comment by spxtr** [comment]
I've been using stackdriver logging for this. It lets you do queries based on the JSON logs, such as `jsonPayload.pr=12345` to filter for all events related to PR 12345.

**Comment by stevekuznetsov** [comment]
That's available if you're on GKE only, right?

**Comment by spxtr** [comment]
I'm not sure TBH. I was assuming other cloud providers have their own logging systems that can do queries such as the one above. I don't think we should implement our own in prow.

**Comment by BenTheElder** [comment]
StackDriver itself is supposed to be usable even with AWS, but I'm not sure
about integrating it with k8s/prow. It looks like there are docs for this
at
https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver/

**Comment by BenTheElder** [comment]
> I don't think we should implement our own in prow.

+1, Prow should use native logging in Kubernetes.

**Comment by stevekuznetsov** [comment]
We shouldn't implement something ourselves, which is why I suggested ELK, but in general we should not also say "Prow is great! Stand it up! Oh, you want an interface that makes it easy to administer the cluster? Hahahaha"

**Comment by spxtr** [comment]
Perhaps some doc that describes basic maintenance and debugging patterns?

**Comment by kargakis** [comment]
@spxtr yeah, such a doc would be nice. prow should be giving us the necessary logs (eg.  https://github.com/kubernetes/test-infra/pull/4885), a logging stack is orthogonal to the system.

**Comment by kargakis** [comment]
Also, we need to start exposing metrics from the controllers if we want to be detecting anomalous behavior as we should. For example, we should expose a metric that records failed API calls to the underlying agent. Then, we could setup a prometheus alert that triggers if the percentage of failed API calls exceeds a percentage of the total calls over a period of time. If the jenkins-operator starts failing to trigger builds during the past hour, that's a problem we need to be notified about.

**Comment by stevekuznetsov** [comment]
A lot of these are being addressed by the tracer, some are exposed by metrics, we should mostly be OK here I think.

/close
