### ISSUE TITLE
Migrate all `*.json` config files to `*.yaml`

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#4794]
/assign
/assign @BenTheElder

**Comment by BenTheElder** [comment]
Also delete `*json.yaml` files :smiling_imp:

**Comment by BenTheElder** [comment]
Cross ref: https://github.com/kubernetes/test-infra/pull/4430

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/test-infra/issues/4871 instead of #4430

**Comment by G-Harmon** [comment]
I guess one reason for this is that you can add comments?

**Comment by BenTheElder** [comment]
> I guess one reason for this is that you can add comments?

Yes, which is super useful for explaining exceptional configurations. :+1:

**Comment by spiffxp** [comment]
Does this include `jobs/config.json`? Could use an `area/jobs` label if so

**Comment by BenTheElder** [comment]
> Does this include jobs/config.json? Could use an area/jobs label if so

Very much so, job configs don't really need to be two files if we are all-in on Prow in our shiny future.

**Comment by krzyzacy** [comment]
boskos config will be migrated to yaml in https://github.com/kubernetes/test-infra/pull/6676

**Comment by sebastienvas** [comment]
I have one issue left there. I did not update the python script that looks for existing projects and recreate the resources.yaml.

**Comment by krzyzacy** [comment]
config.json will be gone after we split up prow/config.yaml, and we can embed kubetest/scenario args there

**Comment by krzyzacy** [comment]
/remove-lifecycle stale
it's getting there!

**Comment by krzyzacy** [comment]
config.json has 4 ghost entry used by bootstrap_test.py... which probably not worth spend time to untangle and we can ditch the file when we switch to podutils. I'll declare victory here.
