### ISSUE TITLE
Assign Plugin says it cannot assign a user because they are not a member, then assigns them

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4804]
Spotted in the wild:
https://github.com/kubernetes/test-infra/pull/4673#issuecomment-333000197
https://github.com/kubernetes/test-infra/pull/4673#event-1270840440

I suspect this is another case-sensitivity issue, all github login comparisons and lookups should be made to force lowercase I think.
/cc @cjwagner

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blame/b4fe4eda5931ddb3c43ebfa67932b4303d7e532f/prow/github/client.go#L620

**Comment by BenTheElder** [comment]
yeah, I think more generally though we need to make sure comparisons etc are done lowercase, EG: https://github.com/kubernetes/test-infra/blob/master/prow/github/types.go#L220
