### ISSUE TITLE
prow: speed up initial cloning of git repositories

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4811]
This is mostly aspirational, a brain dump of mine, something to consider in the future. Approvals (and other things such as golint) require cloning a git repository locally and that can take some time depending on various factors. Thus, the deployment of the `approval-handler` munger (or `hook` in the future, once we migrate approvals to prow) ends up being really slow compared to the rest of the prow components. Golang plugins will be an improvment if we will be able to load plugins dynamically (https://github.com/kubernetes/test-infra/issues/3339) but we can still have redeployments/disruptions of `hook` for other reasons. Also, one of the things I am doing with the Openshift prow deployment today is to redeploy stuff on a short cadence so we can avoid situations like https://github.com/kubernetes/test-infra/pull/4565. It has worked great so far. In that spirit, I have been thinking about the rollout of `hook` and git cloning and I have come up with the following setup:

1. hook starts up and tries to clone from a local service inside the cluster.
2. if the service is down, `hook` falls back to cloning from the remote repo, similar to what happens today.
3. if the service is up, `hook` clones from a pod in the same machine.

The lifecycle of the git repo is effectively decoupled from the lifecycle of `hook`. We can achieve this with a combination of existing and non-existing features in k8s. Namely: 

1. deploy [git-sync](https://github.com/kubernetes/git-sync) as a daemon set for syncing a git repository (or set of repositories), 
1. limit the nodes this can run to the nodes prow can run, 
2. use pod affinity in `hook` so the scheduler can take into account where `git-sync` lives when it's about to schedule a hook pod, 
3. use [node-local](https://github.com/kubernetes/kubernetes/issues/28610) services for discovering the git-sync pod that resides locally for every hook pod.

The last step is something that does not exist in k8s, yet.

Things to investigate:
* how do we know that we clone the latest remote when we clone from git-sync. I haven't looked closely. We may need git-sync to sync with remotes on-demand.
* how is git-sync deciding what repos to clone? We may need to fork it and teach it to read the prow config.
* others I am sure

The above may sound complex to setup but it should be a minimal change in `hook` and the rest is a deployment preference really.

/area prow

**Comment by spxtr** [comment]
I did some experiments and found that cloning from a VM in the same GCP project over HTTP and SSH, cloning from an HTTP server running on localhost, cloning from a git daemon on localhost, and cloning from GitHub were all roughly the same speed. For k/k they all took about a minute +/- 10 seconds. I went with the simplest option: always clone from GitHub. Feel free to attempt to replicate my benchmark. I was pretty lazy about it so I probably missed some stuff.

I think I looked at git-sync but it doesn't work for multiple repos. You have to run one for every repo you want to follow. This should be fine, since most repos clone quickly. We would just run one for k/k.

**Comment by kargakis** [comment]
A clone from the [cache](https://github.com/kubernetes/test-infra/blob/6b02206ea351262811d992ee6af6e781b0450f96/prow/git/git.go#L137) takes >10s. Since the pods will run on the same node, they can possibly share a local volume and then we don't even need to change `hook`? Unclear but worth investigating.

**Comment by kargakis** [comment]
Thanks a lot for your input @spxtr, appreciated!
