### ISSUE TITLE
unified timeout for serial jobs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#4815]
ref: #4633 
>agree with @abgworrall we will want a unified timeout for all serial jobs, will look into that in 1.9 dev cycle

**Comment by krzyzacy** [comment]
My argument on this is each release might need a different timeout depend on the tests they are running - but I'll try to think out of a better system.

**Comment by spiffxp** [comment]
>each release might need a different timeout depend on the tests they are running

FWIW I agree with this as well... 

One idea might be an upper bound on timeout.  If we're hitting that, it's time to consider which tests should be removed or redone.  Otherwise continually adding tests means monotonically increasing job times.

**Comment by krzyzacy** [comment]
(it's always going to be the latter case)

**Comment by krzyzacy** [comment]
this should be unified in https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml#L1011 now
