### ISSUE TITLE
[Feature Request] WIP PRs do not auto assign reviewers/approvers.

### ISSUE THREAD

**Issue by dashpole** [kubernetes/test-infra#4818]
First off, I am a big fan of the new WIP labeling.
One thing I think would be useful is if reviewers/approvers are not assigned until the WIP title is removed.
That way, I can avoid spamming whatever poor person gets assigned each time I push something and a test fails.
This also makes assigning someone an implicit request for review, and avoids needing the "PR is ready PTAL" dialogue.
If I am not using the system correctly, let me know what I should be doing.

**Comment by xiangpengzhao** [comment]
cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@spxtr @fejta what do y'all think about this?

**Comment by stevekuznetsov** [comment]
I think in general I'd have to ask -- why create a WIP pull request if not for reviews? If nobody's looking at it, might as well just have it locally, or on your fork on GitHub, but not as a PR, right?

**Comment by spxtr** [comment]
I think we should have WIP PRs assigned to the author. When they remove WIP it unassigns them and picks reviewers.

> why create a WIP pull request if not for reviews?

To run presubmits.

**Comment by xiangpengzhao** [comment]
>I think we should have WIP PRs assigned to the author. When they remove WIP it unassigns them and picks reviewers.

Discussion here: https://github.com/kubernetes/test-infra/issues/2620

**Comment by fejta** [comment]
I think we should change blunderbuss to just tell people the /assign command to use, but not actually do any assigning. 

This would both support the scenario requested here, train people about the /assign command and signal that our community expects Independence and initiative (while showing them how to direct their initiative)

**Comment by stevekuznetsov** [comment]
I think I'm with @fejta here -- letting people know "hey, you  _can_ /assign people" would also make it annoying to be a top-level OWNER, having to /unassign myself and/or ignore PRs that someone else is handling.

In general I don't particularly like the practice of pushing WIP code up to trigger the full suite of presubmits -- not only is it much less efficient than just iterating on a select few tests locally, but it seems wasteful and if we're not giving devs the tools they need to test locally and be comfortable with their code before they push it, I feel like something's gone wrong.
