### ISSUE TITLE
Reduce test-infra to 294 open issues

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#4824]
/assign @spiffxp @fejta @timothysc

**Comment by stevekuznetsov** [comment]
Shouldn't we close this one to help?

🤔 🤔

**Comment by krzyzacy** [comment]
s/200/300? 😂

**Comment by ixdy** [comment]
/remove-lifecycle stale

we have 279 open issues currently.

**Comment by fejta** [comment]
250!

**Comment by mithrav** [comment]
Also adding Aish =)

**Comment by AishSundar** [comment]
@krzyzacy Thanks :)

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/milestone 1.12
Let's see what happens after some grooming...

**Comment by spiffxp** [comment]
/milestone v1.13
We are now at 303 open issues

**Comment by ixdy** [comment]
`/milestone v2.0` :)

**Comment by krzyzacy** [comment]
probably easier to rename the issue 😂

**Comment by BenTheElder** [comment]
`s/200 open //`

**Comment by fejta** [comment]
72 to go!

**Comment by BenTheElder** [comment]
@k8s-ci-robot hold my 🍺

**Comment by spiffxp** [comment]
/milestone 2019-goals
Not even going to try this quarter lol

**Comment by BenTheElder** [comment]
isn't this more like
`/milestone someday` ? :wink:

**Comment by BenTheElder** [comment]
Good bot :-)

**Comment by krzyzacy** [comment]
/woof

given now we only have 288 open issues, good bot :-)

**Comment by fejta** [comment]
We're now legitimately below both 294 and 200 issues!
