### ISSUE TITLE
Kettle test flake.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#4825]
Here is an example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4805/pull-test-infra-bazel/8177/
/cc @rmmh

**Comment by cjwagner** [comment]
another example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5147/pull-test-infra-bazel/9201/

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4993/pull-test-infra-bazel/9332/
🤷‍♂️

**Comment by BenTheElder** [comment]
Noting that it flakes when then "finished" or "started" keys contain a unix timestamp with "456" in them. 🙃

**Comment by cjwagner** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5289/pull-test-infra-bazel/9500/

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5706/pull-test-infra-bazel/10522/

I'm tempted to just put in a `.replace("456", "")` on the timestamp 🤷‍♂️
