### ISSUE TITLE
Mungegithub makes the master branch pushable by maintainers, not admins only

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#4829]
Manually merging PRs should be restricted to admins only (a very small set of people), not all maintainers (much larger set of people).

Mungegithub "unprotects" this branch in some sense occasionally. I've notified @bgrant0607 when I've seen this, and he has manually flipped things back to normal.

See: https://groups.google.com/forum/#!topic/kubernetes-maintainers/FvV7yYp4sTU

I've seen this happen quite a few times (three times the latest month I think). Last regression happened today-ish.

cc @stevekuznetsov  @spiffxp @bgrant0607

**Comment by stevekuznetsov** [comment]
Previously we attempted to address this with https://github.com/kubernetes/test-infra/pull/4542

We should confirm that the `k/k` `misc-mungers` deployment is running up-to-date code

**Comment by bgrant0607** [comment]
@luxas I don't see evidence that this should be possible in current settings, nor in the audit log.

**Comment by luxas** [comment]
Oh, now I see why. I didn't look closely enough this time; the PR was one of the first to be targeted at a feature branch!

https://github.com/kubernetes/kubernetes/pull/53223

Which made me think it had came back again (like the earlier two times) to master.

I'm very glad this was fixed properly then with the first time :smile:

I guess the state with maintainers being able to merge PRs to feature branches is ok, or should everything go via the SQ there as well? Might be hard to restrict this for all feature branches.

**Comment by fejta** [comment]
Can we just make the entire repo only mergeable by admins, rather than just particular branches?

**Comment by bgrant0607** [comment]
@fejta Github may eventually make that possible, but it doesn't appear to be yet.

**Comment by luxas** [comment]
I guess we can close this issue then as the main code protecting master seems to be working.
Protecting feature branches is an other thing...
