### ISSUE TITLE
PR auto-assigned to user not in any OWNERS files

### ISSUE THREAD

**Issue by tallclair** [kubernetes/test-infra#4831]
https://github.com/kubernetes/kubernetes/pull/53185 was auto-assigned to @timstclair , but that alias isn't in any OWNERS files. I switched from @timstclair to @tallclair a while ago. Is there another mechanism for auto-assigning outside of OWNERS files?

**Comment by BenTheElder** [comment]
I see a manual `/assign @liggitt @timstclair` in the PR's body text under "Special notes for your reviewer:".

**Comment by tallclair** [comment]
Oh, sorry, I missed that. WAI.
