### ISSUE TITLE
Deprecate and remove release-1.5 jobs and testgrid dashboard

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#4862]
Now that we've released kubernetes v1.8.0, I believe [we only support 1.6-1.8](https://github.com/kubernetes/community/blob/58b1c30d95719749068497ba35dfe4c64b21aa72/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew)?

The 1.5 jobs just had some attention paid to them in the past week though, so I'm not sure if there is disagreement in that regard, or if we'd like to keep the jobs around but tune them way down, or...?

WDYT @krzyzacy

**Comment by krzyzacy** [comment]
@mwielgus assume there will be no future 1.5 releases scheduled?

**Comment by krzyzacy** [comment]
(wanna make sure from @mwielgus )

**Comment by BenTheElder** [comment]
er ignore that. apologies

**Comment by krzyzacy** [comment]
I would say it's easier to keep 1.5 as stable-4, so when we are in 1.9 cycle, we can still have signal for 1.6 branch?
