### ISSUE TITLE
godep does not work with latest version of go?

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#4868]
I tried to `godep save` the repo in order to add a new dependency and it seems to require go1.7...
```
$ ~/Downloads/godep_linux_amd64 save ./...
godep: WARNING: Recorded major go version (go1.7) and in-use major go version (go1.9) differ.
godep: To record current major go version run `godep update -goversion`.
```
Getting the same error with latest (`godep v79 (linux/amd64/go1.6)`) and what I had (`godep v62 (linux/amd64/go1.7rc2)`). Should we switch to use `dep`?

cc @ixdy

**Comment by BenTheElder** [comment]
Hmm I definitely have manually edited `Godeps/Godeps.json` to update a dep before :man_shrugging:.
It looks like we have godep explicitly set to `go1.7`
https://github.com/kubernetes/test-infra/blob/8d1c5cf461bb0d71395b7b101c5db0794b32145d/Godeps/Godeps.json#L3
Maybe we can just update this to `go1.9`?

**Comment by cblecker** [comment]
Yes, it can safely be updated to go1.9 without issue. k/k uses godep v79, so I'd recommend that (although @kargakis, I'm interested in where you are getting a godep v79 that's compiled with go1.6).

**Comment by kargakis** [comment]
@cblecker https://github.com/tools/godep/releases/tag/v79

**Comment by cblecker** [comment]
Ohh.. I didn't realize they distributed binaries too. Their [installation instructions](https://github.com/tools/godep/tree/v79#install) just call for a `go get`.

**Comment by cblecker** [comment]
We are using dep now.
/close
