### ISSUE TITLE
Prow not redirects properly?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#4879]
http://prow.k8s.io/?type=periodic takes you to http://prow.k8s.io/ now

/assign @cjwagner

**Comment by cjwagner** [comment]
cc @rmmh

**Comment by BenTheElder** [comment]
fixed in https://github.com/kubernetes/test-infra/pull/4882/files ?

**Comment by BenTheElder** [comment]
Looks like this still needs to get deployed.

**Comment by kargakis** [comment]
Seems fixed now.
