### ISSUE TITLE
PR jobs still run with debian nodes

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#4883]
Ref: 
- pull-gce-etcd3:https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52028/pull-kubernetes-e2e-gce-etcd3/57501/
- pull-gce-bazel: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52028/pull-kubernetes-e2e-gce-bazel/33208/

Both have:
```
master_os_image | cos-stable-60-9592-90-0
node_os_image   | container-vm-v20170627
```

Is this as expected? Should we switch to COS as well regarding https://github.com/kubernetes/kubernetes/pull/52120?

@krzyzacy

**Comment by krzyzacy** [comment]
yeah, I'm doing some cleaning up
