### ISSUE TITLE
prow should have better introspection

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#4891]
@rmmh brought up some ideas for improving prow introspection today, writing down what I remember here:

- deck should serve config.yaml and plugins.yaml
  - possibly deck should also be able to serve selected subsets of these since they're huge and growing (seperate discussions about orthogonaly improving this)
- deck should serve recent events (trigger events etc?)
- it should be easier to view a specific job's configuration (possibly somewhat covered in https://github.com/kubernetes/test-infra/pull/4881, but we might be able to do better)

Possibly other things I'm forgetting...

**Comment by spxtr** [comment]
> deck should serve config.yaml and plugins.yaml

That could be useful, and it's pretty easy to do.

> possibly deck should also be able to serve selected subsets of these since they're huge and growing (seperate discussions about orthogonaly improving this)

They'll shrink eventually(TM).

> deck should serve recent events (trigger events etc?)

Not sure how useful that is. They're in the logs if you need to see them. Not only that but we wouldn't be able to provide any guarantees about this.

> it should be easier to view a specific job's configuration (possibly somewhat covered in #4881, but we might be able to do better)

That's not a bad idea, related sorta to the first one.

**Comment by BenTheElder** [comment]
We do serve the serialized config now, but I didn't get to plugins.yaml or anything more complex.

**Comment by nikhita** [comment]
/remove-lifecycle stale

stale and help-wanted don't go hand in hand :)

**Comment by BenTheElder** [comment]
Perhaps we should freeze help wanted?

**Comment by BenTheElder** [comment]
@rmmh since patched bootstrap to upload the pod .yaml dumped from the running job into artifacts/ which is pretty handy. we should consider something like this in the podutils... @cjwagner @paulangton
