### ISSUE TITLE
pull-test-infra-bazel does not produce artifacts anymore?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#4902]
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/test-infra/4898/pull-test-infra-bazel/8385/

**Comment by krzyzacy** [comment]
ci-test-infra-bazel still output junit_bazel.xml : http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-test-infra-bazel/59861/artifacts/

**Comment by krzyzacy** [comment]
I hit the similar error in https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-prow-canary/19133/build-log.txt, where I worked around by explicitly install `file`

**Comment by BenTheElder** [comment]
```
$ docker run -it --entrypoint=/bin/bash gcr.io/k8s-testimages/bazelbuild:v20170929-ed26bd34-0.6.0
root@cd5fe01ed640:/workspace# file
bash: file: command not found
root@cd5fe01ed640:/workspace# which file
root@cd5fe01ed640:/workspace#
```
yeah. hmm, we need to fix that. we should probably also bump to bazel 0.6.1

**Comment by BenTheElder** [comment]
PR up shortly.

**Comment by BenTheElder** [comment]
need to wait and make sure it's all good

**Comment by BenTheElder** [comment]
Testing at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4905/pull-test-infra-bazel/8401/
