### ISSUE TITLE
Prow issue: k8s-ci-robot and k8s-merge-robot disagree on kind/ labels

### ISSUE THREAD

**Issue by verb** [kubernetes/test-infra#4921]
Example: https://github.com/kubernetes/kubernetes/issues/53189

k8s-merge-robot says:

```
Action required: This issue requires label changes. If the required changes are not made within 2 days, the issue will be moved out of the v1.9 milestone.

kind: Must specify exactly one of kind/bug, kind/cleanup or kind/feature.
```

So I try `/remove-kind bug`, and k8s-ci-robot says:

```
@verb: Those labels are not set on the issue: kind/bug

Details
In response to this:

/remove-kind bug
Instructions for interacting with me using PR comments are available here. If you have questions or suggestions related to my behavior, please file an issue against the kubernetes/test-infra repository.
```

**Comment by xiangpengzhao** [comment]
So I try `/remove-kind bug`

**Comment by xiangpengzhao** [comment]
`/remove-kind bug`

**Comment by xiangpengzhao** [comment]
Another issue here, seems like k8s-ci-robot recognized a quoted `/remove-kind bug` in your issue body, but I didn't reproduced it in comments... Should it recognized a quoted command?

**Comment by xiangpengzhao** [comment]
```
try this way:
/remove-kind bug
```

**Comment by spxtr** [comment]
Well that's a bug :)

**Comment by xiangpengzhao** [comment]
PR #4946 sent.

**Comment by xiangpengzhao** [comment]
https://github.com/kubernetes/test-infra/pull/1#event-1285412609
https://github.com/kubernetes/test-infra/issues/4921#event-1285413081
When I add `kind/bug` for issue #1 and then `/remove-kind bug` here, the label can be removed. That means, all the add/remove label actions will check if #1 has the label.
/shrug
