### ISSUE TITLE
Expired days are too short for issues in the new 1.9 milestone

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#4922]
See example: https://github.com/kubernetes/kubernetes/issues/53189

```
dchen1107 added this to the v1.9 milestone 9 days ago
```

```
Action required: This issue requires label changes. If the required changes are not made within 1 day, the issue will be moved out of the v1.9 milestone.
```

It's only 10 days. Seems like it's too short.

cc @dchen1107 @fejta

**Comment by jdumars** [comment]
@marun for visibility

@xiangpengzhao this time frame is in some ways too short for regular coding periods, but also on the verge of too long for burndown.  This duration was to find a balance between the two.  What would you suggest to balance the two needs instead?  Ideally, we should not be constantly adjusting the frequency by hand.

**Comment by enisoc** [comment]
@xiangpengzhao Did you file a bug for the bot refusing to remove `kind/bug`? That seems to have been the real blocker in this case. I went ahead and fixed it manually for now.

**Comment by xiangpengzhao** [comment]
>What would you suggest to balance the two needs instead? 

@jdumars What I expect is that the time frame shouldn't be absolute but relative. I mean we make the issue be moved out of a milestone if the required changes are not made until some days (e.g., 7 days) before the date when that release will be published.

>Did you file a bug for the bot refusing to remove kind/bug? That seems to have been the real blocker in this case. I went ahead and fixed it manually for now.

@enisoc there is an issue https://github.com/kubernetes/test-infra/issues/4921 filed by @verb and I sent a patch to fix it. But I don't think it was the blocker in this case. The bug refused to remove a label but it didn't refuse to add a label such as `kind/bug` which is needed for an issue in a milestone.

**Comment by enisoc** [comment]
@xiangpengzhao It looked to me like the labels would have been ok, except that it had multiple `kind/*` labels. If it had let you remove the extra `kind/*` label, I think it would have been satisfied with the labels, and it would have moved on to `milestone/needs-approval`.

**Comment by enisoc** [comment]
That may be another area for improvement. Maybe `/kind ...` should remove other labels that the bot considers mutually exclusive?

**Comment by xiangpengzhao** [comment]
/kind bug
/kind feature
/kind cleanup
[test kind label]

**Comment by xiangpengzhao** [comment]
>Maybe /kind ... should remove other labels that the bot considers mutually exclusive?

makes sense :+1:

**Comment by marun** [comment]
The issue with `kind/bug` is an interaction between the prow mention plugin, which automatically adds the tag if a *-bugs team is mentioned.  This means that removing the `kind/bug` label requires scrubbing an issue of all mentions of such teams or the plugin will keep adding it back.  The milestone munger should probably be targeting a team other than *-bugs, and the mention plugin should be ignoring bot-created comments.

Regarding the timelines, the grade period is actually 7 days not 10, but the total grace period will be 10 days (3 days for labels, 7 days for sig approval = 10 days total from addition to milestone):

https://github.com/kubernetes/test-infra/blob/master/mungegithub/mungers/milestone-maintainer.go#L344

These periods are currently set the same for dev, slush and freeze.  @jdumars, would it make sense to have those configurable at least between dev and slush+freeze, and if so, what should the defaults be?

**Comment by jdumars** [comment]
@marun that would be ideal.  I would say during code slush/freeze keep 3 days for labels, but lower sig approval to 4 days, so it handles holiday weekends.
