### ISSUE TITLE
Should check GOPATH in kubetest/util.go

### ISSUE THREAD

**Issue by ScorpioCPH** [kubernetes/test-infra#4927]
If there is no `GOPATH` env configed, `k8s` func will return `src/k8s.io/...`,
so `Build` func will construct cmd such as:

```shell
$ make -C src/k8s.io/kubernetes quick-release
```

and `kubetest` will throw error `make[1]: *** src/k8s.io/kubernetes: No such file or directory.  Stop.`

**Comment by krzyzacy** [comment]
huh? how do you use go without `$GOPATH` set?

**Comment by ScorpioCPH** [comment]
@krzyzacy Hi, thanks for your reply!

I think `GOPATH` is not necessary, at least, for my local env, it works well without `GOPATH`.

I think it just depends on how you organize the sourcecode of your project int your workspace.

**Comment by krzyzacy** [comment]
@ScorpioCPH hummm how do you get/build/run kubetest without `GOPATH` then?

**Comment by ScorpioCPH** [comment]
@krzyzacy Hi, as i commented above, `kubetest` throw an error, but i don't know it is because `GOPATH` not set.

I must check the source code to figure out how to fix this error.

So i think maybe we can show more details about this error in error message.

**Comment by krzyzacy** [comment]
@ScorpioCPH so you manage to get a kubetest binary without `GOPATH` set? Try to understand your dev environment :-)

**Comment by ScorpioCPH** [comment]
@krzyzacy I can build `kubetest` bianry without `GOPATH` set, as show below:

```shell
# unset GOPATH first
root@cenph:~/go/src/k8s.io/kubernetes# unset GOPATH

# updating kubetest binary...
root@cenph:~/go/src/k8s.io/kubernetes# go run hack/e2e.go -- -v --build
2017/10/17 19:00:55 e2e.go:157: Updating kubetest binary...
2017/10/17 19:01:03 e2e.go:77: Calling kubetest -v --build...

# make quick release (error occur)
2017/10/17 19:01:03 util.go:154: Running: make -C src/k8s.io/kubernetes quick-release
make: *** src/k8s.io/kubernetes: No such file or directory.  Stop.
2017/10/17 19:01:03 util.go:156: Step 'make -C src/k8s.io/kubernetes quick-release' finished in 607.99µs
2017/10/17 19:01:03 main.go:260: Something went wrong: failed to acquire k8s binaries: error during make -C src/k8s.io/kubernetes quick-release: exit status 2
2017/10/17 19:01:03 e2e.go:79: err: exit status 1
exit status 1
```

After updating `kubetest` binary, it begin to `make quick-release`, but it failed because `GOPATH` not set (no error message showed).
