### ISSUE TITLE
Bazel build failing: no targets found

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#4938]
Example:

```
W1009 21:15:26.354] Run: ('bazel', 'query', '--keep_going', '--noshow_progress', 'kind(.*_binary, rdeps(set(//cmd/... //pkg/... //federation/... //plugin/... //third_party/... //examples/... //test/... //vendor/k8s.io/...), //...))')
W1009 21:15:26.364] INFO: $TEST_TMPDIR defined: output root default is '/root/.cache/bazel'.
W1009 21:15:28.025] ..............
W1009 21:15:35.566] ERROR: Skipping '//vendor/k8s.io/...': no targets found beneath 'vendor/k8s.io'.
W1009 21:16:32.415] WARNING: --keep_going specified, ignoring errors.  Results may be inaccurate.
W1009 21:16:33.033] Run: ('/workspace/./test-infra/jenkins/../scenarios/../images/bazelbuild/coalesce.py',)
I1009 21:16:33.147] Build passed, tests failed or timed out
E1009 21:16:33.153] Command failed
I1009 21:16:33.153] process 458 exited with code 3 after 1.4m
E1009 21:16:33.154] FAIL: pull-kubernetes-bazel-build
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/53544/pull-kubernetes-bazel-build/8500/

**Comment by BenTheElder** [comment]
release-1.6 does not build properly with bazel /cc @krzyzacy @ixdy

**Comment by krzyzacy** [comment]
yeah ignore that job for now (that's not required and was disabled, I enabled it to see if it will work with an older bazel version, but no luck :-( )

**Comment by enisoc** [comment]
It seems to be a required test though:

https://github.com/kubernetes/kubernetes/pull/53544

```
Submit Queue — Required Github CI test is not green: pull-kubernetes-bazel-build...
```

Can we remove it from the required list so I don't have to bypass the submit queue?

**Comment by BenTheElder** [comment]
It *should* be required on master, etc. We need to get it back to skipping 1.6 for now.

**Comment by krzyzacy** [comment]
arh right that's the bazel-build job, I meant gce-bazel. I'll try to toss in some workaround for now.

**Comment by ixdy** [comment]
Yeah, I think I broke this workflow last week when I added the bazel-build job for 1.6. I didn't realize at the time that we needed to also branch the scenario configuration for the jobs, which is a bit harder.

**Comment by BenTheElder** [comment]
bazel-build is fixed for 1.6 (https://github.com/kubernetes/kubernetes/pull/53017) but bazel-test [may be broken](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/53017/pull-kubernetes-bazel-test/9373/), I'm trying to figure out if it's just a flake or not.

**Comment by BenTheElder** [comment]
I can't tell if this is a legitimate failure or not but it *is* consistent.

**Comment by ixdy** [comment]
yeah, this is https://github.com/kubernetes/kubernetes/issues/53016. I can't get it to reproduce locally, but it consistently fails on prow.

**Comment by BenTheElder** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/53016
