### ISSUE TITLE
Have some other solution for sharing cache instead of use containerPort

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#4961]
ref https://github.com/kubernetes/test-infra/pull/4960#discussion_r143871843

**Comment by BenTheElder** [comment]
I'm pretty sure @spxtr mentioned that the git cache should be fine, it's the build cache that needs to have unique access (I *think*).

**Comment by krzyzacy** [comment]
/shrug
we complaint every so often
move discussion to https://github.com/kubernetes/test-infra/issues/5436
