### ISSUE TITLE
gubernator link for non-k8s presubmit is wrong

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#4976]
https://github.com/kubernetes-incubator/cri-containerd/pull/338

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubernetes-incubator_cri-containerd/338/pull-cri-containerd-build/2/

bootstrap indicates the url should be https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/cri-containerd/338/pull-cri-containerd-build/2

/assign @rmmh

**Comment by krzyzacy** [comment]
cc @Random-Liu

**Comment by krzyzacy** [comment]
hummm it fixed itself?

**Comment by krzyzacy** [comment]
nope... compare https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-cri-containerd-node-e2e and https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull-cri-containerd-node-e2e/

something's screwed?

**Comment by rmmh** [comment]
Something's messed up with that job. It's not putting logs where it should.
```$ gsutil ls gs://kubernetes-jenkins/pr-logs/
gs://kubernetes-jenkins/pr-logs/directory/
gs://kubernetes-jenkins/pr-logs/pull-cri-containerd-node-e2e/
gs://kubernetes-jenkins/pr-logs/pull/```

**Comment by Random-Liu** [comment]
@rmmh How could we fix it?

**Comment by Random-Liu** [comment]
`pull-cri-containerd-build` does work, but `pull-cri-containerd-node-e2e` is not. Is it related to `run_after_success`?

**Comment by spiffxp** [comment]
FWIW I bumped into this in the linked PR above

**Comment by BenTheElder** [comment]
This seems like a bootstrap bug, not gubernator or prow..
/assign
/assign @krzyzacy
