### ISSUE TITLE
`kubetest` requires application default credentials for gce

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/test-infra#4994]
For anyone with similar trouble, hopefully they'll find this:

I wasn't logged in with `gcloud auth application-default` so I was getting errors:

```
Oct 13 07:58:55.955: INFO: Fetching cloud provider for "gce"

I1013 07:58:55.956060   27686 gce.go:735] Using DefaultTokenSource &oauth2.reuseTokenSource{new:(*oauth2.tokenRefresher)(0xc420bea540), mu:sync.Mutex{state:0,
 sema:0x0}, t:(*oauth2.Token)(0xc420aa7e60)}
E1013 07:58:56.103977   27686 gce.go:745] error fetching initial token: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error" : "invalid_grant",
  "error_description" : "Token has been expired or revoked.",
```

Fixed with `gcloud auth application-default login`.

**Comment by krzyzacy** [comment]
@ihmccreery what kubetest command are you running? I'm using `gcloud auth login` most of the time and seems that worked fine?

**Comment by ihmccreery** [comment]
`gcloud auth login` doesn't install application default credentials anymore.

The e2e's are so hard to run as it is ... I'd love to see this documented somewhere.

**Comment by krzyzacy** [comment]
@ihmccreery we have some kubetest documentation at https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md

so what command did you run, what's your `gcloud auth list`? I'd like to reproduce this locally.

**Comment by ihmccreery** [comment]
To reproduce:

```
gcloud auth application-default revoke
kubetest --test
```

You'll see stuff like:

```
Jan 16 16:48:25.174: INFO: Fetching cloud provider for "gce"

I0116 16:48:25.503564   88263 gce.go:822] Using DefaultTokenSource <nil>
Jan 16 16:48:25.503: INFO: Failed to setup provider config: Error building GCE/GKE provider: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Failure [0.330 seconds]
[BeforeSuite] BeforeSuite 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:138

  Jan 16 16:48:25.503: Failed to setup provider config: Error building GCE/GKE provider: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:142
------------------------------
Jan 16 16:48:25.504: INFO: Running AfterSuite actions on all node
Jan 16 16:48:25.505: INFO: Running AfterSuite actions on node 1
```

Notice that when you run `gcloud auth login`, you'll see:

```
WARNING: `gcloud auth login` no longer writes application default credentials.
If you need to use ADC, see:
  gcloud auth application-default --help
```

**Comment by roycaihw** [comment]
thanks @ihmccreery! I ran into this issue today. `gcloud auth login` didn't work and `gcloud auth application-default login` solved the problem. Would like to see this getting documented in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md or https://github.com/kubernetes/test-infra/blob/master/kubetest/README.md
