### ISSUE TITLE
flake in //robots/issue-creator/testowner:go_default_test

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5002]
```
--- FAIL: TestOwnerListRandom (0.04s)
	owner_test.go:99: Too few assigments to d: only 191, expected > 200
E1013 20:56:30.294821      13 owner.go:177] Unable to load test owners at /tmp/ownertest122291400: could not parse owner list: line 2, column 0: wrong number of fields in line
E1013 20:56:30.298260      13 owner.go:187] Unable to reload test owners at /tmp/ownertest122291400: could not parse owner list: line 2, column 0: wrong number of fields in line
E1013 20:56:30.298497      13 owner.go:197] Unable to reload test owners at /tmp/ownertest122291400: could not parse owner list: line 2, column 0: wrong number of fields in line
FAIL
```
spotted here: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/4974/pull-test-infra-bazel/8722/

**Comment by BenTheElder** [comment]
It seems to me all this test found in this flake is that PRNGs do not necessarily have an even distribution for some sampling. Not sure what we should do here.
/cc @cjwagner for context on this code

**Comment by cjwagner** [comment]
I copied the testowners stuff from mungegithub when I split out the issue-creator.
I don't like the idea of non-deterministic tests, but this one might be appropriate? We could get rid of it entirely or minimize the chance of a flake to a low level by lowering the threshold of 200 down to something like 20.

**Comment by BenTheElder** [comment]
I'd be fine with removing the test entirely. I don't think unit testing the usage of a PRNG makes much sense and if we lower the threshold to 20 it isn't accomplishing much.
