### ISSUE TITLE
k8s-bot shouldn't create an issues for tests failing just after the fix is merged

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#501]
@kubernetes/test-infra-maintainers - the problem is the following:
- test X fails and there's an issue Y for it 
- PR Z fixes X and has "Fixes Y" in the comment
- PR Z is merged and github automatically closes Y
- it takes 30 minutes (or sth) to build a new release so all tests started before that fail (as X is not fixed yet)
- k8s bot opens an issue for failing X again.

Is it possible to mute the bot for some time after the merge (preferably until the fix is live)?

**Comment by fejta** [comment]
Antoine is this feasible?

**Comment by apelisse** [comment]
Might work, but I'm not super eager to work on this:
- I'd rather have the bot close issues that don't flake (not when the "fix" is committed)
- Worst case scenario isn't terrible (we have an extra issue to close)
- I'm a little bit worried that this would be flaky: "30 minutes (or sth)" already indicates that this might be a guessing game.

**Comment by fejta** [comment]
/unassign @apelisse 
/assign @cjwagner 

Fixed in the new issue filer (won't file an issue until a week after it is fixed)
