### ISSUE TITLE
Rename /verify directory to /hack or something

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5011]
There are a couple of scripts in the /verify directory that update stuff like bazel files or gofmt. It would be more intuitive to have a different name than `verify`.

cc: @cjwagner @spxtr

**Comment by BenTheElder** [comment]
I'm in favor of renaming this to `hack/` to match k/k.
cc @ixdy, we just discussed this offline in relation to  https://github.com/kubernetes/community/pull/1278, it would be nice to be consistent here.

**Comment by spxtr** [comment]
We went with `verify` because `hack` is an awful name. I'm fine with renaming for consistency though.

**Comment by BenTheElder** [comment]
Yeah, it's not the best name, but `verify/update*.sh` also feels kinda weird and it will be nice to be able to tell people to `hack/update-gofmt.sh`, `hack/update-bazel.sh` etc. for both repos.
