### ISSUE TITLE
pr-gpu-gce job is leaking custom sub-network

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#5019]
open the issue for tracking

/assign @MrHohn 
cc @mindprince @rmmh 

@MrHohn thinks https://github.com/kubernetes/kubernetes/pull/53751 might break the deletion of subnetwork

We might want to flip back to auto-network until the issue is resolved?

**Comment by mindprince** [comment]
Yeah, let's remove `CREATE_CUSTOM_NETWORK` till we fix this.
