### ISSUE TITLE
bizzare govet flake (prow bug?)

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5027]
on https://github.com/kubernetes/test-infra/pull/5026, this happened:
![image](https://user-images.githubusercontent.com/917931/31641316-9b4c2f46-b298-11e7-814b-1d418cc3af74.png)
with this dead link:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5026/pull-test-infra-verify-govet/4143/

#5026 only touches one python script, which makes this even weirder

**Comment by BenTheElder** [comment]
I think this happened because I force pushed a rewrite, you can only see one test result (green) here:
https://k8s-gubernator.appspot.com/pr/test-infra/5026

/cc @cjwagner @kargakis @spxtr

**Comment by BenTheElder** [comment]
I don't think there's anything else useful to this bug, force push can cause issues.

**Comment by spxtr** [comment]
We can probably provide more useful information, though.
