### ISSUE TITLE
PR Dashboard: instructions refer to an non-existent button

### ISSUE THREAD

**Issue by porridge** [kubernetes/test-infra#5033]
> Needs Attention is a heuristic grouping based on a simple state machine. Use the "ACK" button to remove a PR from "Needs Attention" until something new occurs.

There is no such button on https://k8s-gubernator.appspot.com/pr/porridge

**Comment by fejta** [comment]
Use https://k8s-gubernator.appspot.com/pr/ and authorize GitHub. 

@rmmh should we help people find this page?

**Comment by porridge** [comment]
That works, thanks. Adding such link on that page would help.

**Comment by mithrav** [comment]
Fixed in PR https://github.com/kubernetes/test-infra/pull/6127
