### ISSUE TITLE
How to test jobs locally without boskos?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#5037]
Splitting off from #5036 - the "create a new job" instructions https://github.com/kubernetes/test-infra#create-a-new-job suggest to run `$GOPATH/src/k8s.io/test-infra/jenkins/bootstrap.py`, but that now tries to talk to boskos.  Is it possible to test locally without boskos?

**Comment by krzyzacy** [comment]
@justinsb set `--gcp-project=your-own-project` locally
