### ISSUE TITLE
Tests using stale e2e-runner.sh

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/test-infra#504]
https://github.com/kubernetes/test-infra/pull/443 renamed an env var in `e2e-runner.sh` and job configs that used it. The most recent run failed because `e2e-runner.sh` was still expecting the old variable name.

```
09:52:10 ++ echo 'JENKINS_GCI_IMAGE_FAMILY and KUBE_GCE_MASTER_IMAGE must be set.'
09:52:10 ++ exit 1
09:52:10 + local -r 'gci_k8s_version=JENKINS_GCI_IMAGE_FAMILY and KUBE_GCE_MASTER_IMAGE must be set.'
09:52:10 + echo 'Using GCI builtin version: JENKINS_GCI_IMAGE_FAMILY and KUBE_GCE_MASTER_IMAGE must be set.'
09:52:10 Using GCI builtin version: JENKINS_GCI_IMAGE_FAMILY and KUBE_GCE_MASTER_IMAGE must be set.
09:52:10 + fetch_tars_from_gcs gs://kubernetes-release/release 'JENKINS_GCI_IMAGE_FAMILY and
```

_Note that `JENKINS_GCI_IMAGE_FAMILY` was changed to `JENKINS_GCI_HEAD_IMAGE_FAMILY` in that PR._

@fejta @spxtr Any idea?

@kubernetes/goog-image FYI

**Comment by ixdy** [comment]
Can you link to the result where you saw this?

**Comment by ixdy** [comment]
oh, actually, this is working as implemented.

you have to push a new e2e-image and update `dockerized-e2e-runner.sh` to use the new image after changes to e2e-runner.sh now. I'm not sure this has been documented anywhere, though. @fejta

**Comment by wonderfly** [comment]
The result is on an internal Jenkins instance so I'd rather not paste the link here. :)

> you have to push a new e2e-image and update dockerized-e2e-runner.sh to use the new image after changes to e2e-runner.sh now. I'm not sure this has been documented anywhere, though. @fejta

Do I have permission to push a new image? Any instructions @fejta ?

**Comment by ixdy** [comment]
Does the job not upload to GCS? Most builds have a k8s-gubernator link.

In any case, I can take care of pushing the new image.

**Comment by ixdy** [comment]
... eventually. I apparently can't ssh from my laptop right now.

**Comment by wonderfly** [comment]
I can't find a k8s-gubernator link, but this is the log in GCS: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-gci-qa-m52/1149

**Comment by fejta** [comment]
We plan to automate the test image release process next quarter. For now this is working as intended.
