### ISSUE TITLE
Allow creating presubmit job with restricted access to trigger it

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#5051]
We plan on adding kubemark-5000 and kubemark-2000 as optional presubmit jobs. But since they're resource-intensive and costly, we cannot afford to have them run for many PRs and they shouldn't be triggerable by everyone due to those concerns. Though we still need them for easy evaluation of performance effect of some PRs. So we need a mechanism by which the job can be triggered but only by few whitelisted github users.

Can we make munger do this?

cc @kubernetes/sig-scalability-misc @krzyzacy @cjwagner

**Comment by BenTheElder** [comment]
this would have to be done in the prow trigger plugin, I don't think it would be too hard to do
/area prow

**Comment by shyamjvs** [comment]
Ping @BenTheElder - we need this asap to allow scalability testing on PRs. It's blocking adding those presubmit jobs.

cc @porridge

**Comment by shyamjvs** [comment]
Could you (or someone else from sig-testing) look into this? I'd also be happy to take it up if you could give me some pointers on how to do it.

**Comment by BenTheElder** [comment]
cc @cjwagner @kargakis 

This would need to be some kind of extension to [the trigger plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/trigger) which is straight-forward enough but I'm not sure how we want to configure this.

Another option that might work in the meantime if you just want to have it only run on some PRs is to use a `run_if_changed` regex to only trigger for relevant PRs which is what the cross and kubeadm jobs do [example](https://github.com/kubernetes/test-infra/blob/c1944132e144671a0e0033bf9b3f13f171ba3e07/prow/config.yaml#L632).

**Comment by cjwagner** [comment]
Configuration is definitely the real question. The actual check would just ensure that the trigger comment was made by a member of the allowed user set.
To configure the set of allowed users by job I see 2 options, both of which involve adding a new field to each job type [here](https://github.com/kubernetes/test-infra/blob/master/prow/config/jobs.go#L27).
1. Add an `authorizedTeam` field to each job type that specifies the github team ID number whose members are the people authorized to run the job.
2. Add an `authorizedAlias` field to each job type that specifies an alias in an OWNERS_ALIASES file whose members are the people authorized to run the job. This option is coupled to non-github infrastructure which is a down side, but it could make it easier to manage team membership, and it creates an audit history (the git commits to the OWNERS_ALIASES file) which is something that has been requested [previously](https://kubernetes.slack.com/archives/C09QZ4DQB/p1503974540000157).

Both options should be equally easy to implement once #5017 merges.

**Comment by cjwagner** [comment]
@qhuynh96's work to add Github oauth and a job triggering page to Deck could make this possible.

**Comment by cjwagner** [comment]
This issue is about allowing certain users to trigger special jobs that other users are not allowed to trigger. `run_if_changed` is a mechanism for automatically triggering a job for PRs that change files that match a pattern.
If this specific use case can be satisfied by triggering the job when certain files are changed then `run_if_changed` can be used, but `run_if_changed` does not solve this problem in general.

Restricting job triggering access would probably be most easily implemented by updating the job config and `trigger` plugin as described above.

**Comment by mithrav** [comment]
SGTM, I think trigger plugin is the way to go. @amwat any chance you can take this up as part of the Scalability testing effort?

**Comment by amwat** [comment]
Yeah, I'll look into it.
/assign

**Comment by mithrav** [comment]
/remove-lifecycle stale, we were just discussing it this week with @shyamjvs

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-longterm
I'd like to try keeping the red priority for things that are breaking/blocking existing workflows
