### ISSUE TITLE
Result=SUCCESS despite `Tests 2 failed / 338 succeeded`

### ISSUE THREAD

**Issue by porridge** [kubernetes/test-infra#5052]
See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/54062/pull-kubernetes-e2e-gce/72/

If these tests are not meant to affect the outcome, then they should be skipped. Current behaviour is confusing.

Pasting in case the logs go away:

```
[sig-apps] CronJob should remove from active list jobs that have been deleted 1m9s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\[sig\-apps\]\sCronJob\sshould\sremove\sfrom\sactive\slist\sjobs\sthat\shave\sbeen\sdeleted$'
test/e2e/apps/cronjob.go:233
Expected an error to have occurred.  Got:
    <nil>: nil
test/e2e/apps/cronjob.go:228
```

```
[sig-storage] Downward API volume should update annotations on modification [Conformance] 2m57s
go run hack/e2e.go -v -test --test_args='--ginkgo.focus=\[sig\-storage\]\sDownward\sAPI\svolume\sshould\supdate\sannotations\son\smodification\s\[Conformance\]$'
test/e2e/common/downwardapi_volume.go:154
Timed out after 120.001s.
```

**Comment by fejta** [comment]
This is intended and expected. Presubmits rerun failing tests in case they are not failing but just flaky.

Please follow up by filing issues with sig-apps and sig-storage noting that those two tests are flaky. Refer to http://velodrome.k8s.io/dashboard/db/bigquery-metrics for more comprehensive flake info (or kubernetes/test-infra/metrics)

**Comment by porridge** [comment]
If they were flaky, then perhaps they should be marked as such, rather than "failed"?
How about:


Result | SUCCESS
-- | --
Tests | 2 flaky / 336 succeeded
