### ISSUE TITLE
[release-1.6] failed to acquire k8s binaries

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#5062]
I'm seeing pull tests fail on the `release-1.6` branch due to:

```
W1018 22:00:32.259] 2017/10/18 22:00:32 main.go:260: Something went wrong: failed to acquire k8s binaries: error during /go/src/k8s.io/release/push-build.sh --nomock --verbose --noupdatelatest --bucket=kubernetes-release-pull --ci --gcs-suffix=/pull-kubernetes-e2e-gce: exit status 1
```

Could this be related to the recent rename of some jobs? I tried `/retest` but it's persistent.

https://github.com/kubernetes/kubernetes/pull/54051

**Comment by krzyzacy** [comment]
cc @BenTheElder

**Comment by BenTheElder** [comment]
Agh, apparently push-build doesn't work for 1-6, will fork this job back to jenkins just on release-1.6 branch.

**Comment by BenTheElder** [comment]
Additionally the plan going forward is that release-1.6 will just use jenkins / dockerized builds unfortunately and that we will tie dropping jenkins back to dropping 1.6. I'm fixing this right now.

**Comment by BenTheElder** [comment]
this should be fixed in https://github.com/kubernetes/test-infra/pull/5063
