### ISSUE TITLE
"skipped" status is acting up

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5069]
I've observed today:

- PRs that should have `pull-kubernetes-cross` labeled as skipped (anything that doesn't touch build / the run_if_changed specifier) are sometimes showing "waiting on status"
- In https://github.com/kubernetes/kubernetes/pull/54051 I observed that upon `/test pull-kubernetes-bazel-test`, `pull-kubernetes-bazel-test` jumped down to green with "skipped" for ~30s (ish?) before it went to "job triggered"

**Comment by BenTheElder** [comment]
/cc @cjwagner @kargakis @spxtr 

This forced https://github.com/kubernetes/test-infra/pull/5058 because we couldn't make `pull-kubernetes-cross` blocking with PRs not getting labeled properly.

**Comment by cjwagner** [comment]
I have not noticed that behavior before.
