### ISSUE TITLE
Testgrid should have a header explaining what it does

### ISSUE THREAD

**Issue by castrojo** [kubernetes/test-infra#5078]
Assuming I'm a new user and I run into: https://k8s-testgrid.appspot.com/

It'd be nice to have things like "What is this testing." "Why this is important to you", "How to file a bug on this service", "get your stuff on here" and so on. Right now it's just a grid with a bunch of stuff and I feel like I have to ask someone to walk me through it.

**Comment by krzyzacy** [comment]
/assign @michelle192837 
/area documentation
maybe we can add some doc on how to operate testgrid?
