### ISSUE TITLE
document our clusters

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#5085]
There is interest in spinning up a cluster in a CNCF-funded non-google.com GCP org, such that we could put test-infra on there, and begin to open up support of this infra to non-google members of sig-testing.

What are the clusters we have today?  What runs where?  What would we want to migrate to a CNCF-owned cluster?

Initial sketch from asking in #sig-testing

Clusters
- prow
  - prow/cmd/*
- prow-builds
  - prowjobs (presubmits, postsubmits, periodics)
  - boskos
  - issue-creator
- mungegithub
- util?
  - velodrome?

**Comment by spxtr** [comment]
prow can presumably run in the same project or cluster as the others. prow-builds needs to be in its own project to isolate untrusted code from the secrets.

**Comment by spiffxp** [comment]
Here's what I understand to be running on clusters currently managed or accessible by google members of sig-testing.  First two clusters are based on a dump of pods/services/etc; the source is a total guess.

utilicluster:
- gcsweb (https://github.com/kubernetes/k8s.io/tree/master/gcsweb.k8s.io)
- k8s-io (https://github.com/kubernetes/k8s.io/tree/master/k8s.io)
- node-perf-dash (https://github.com/kubernetes/contrib/tree/master/node-perf-dash)
- kubernetes-publisher (???)
- reviewable (https://github.com/kubernetes/k8s.io/tree/master/reviewable.k8s.io)
- spartakus (https://github.com/kubernetes-incubator/spartakus)
- velodrome (https://github.com/kubernetes/test-infra/tree/master/velodrome)

mungegithub:
- submit-queue (https://github.com/kubernetes/test-infra/tree/master/mungegithub/submit-queue)
- misc-mungers (https://github.com/kubernetes/test-infra/tree/master/mungegithub/misc-mungers)
- cherrypick (https://github.com/kubernetes/test-infra/tree/master/mungegithub/cherrypick)
- perfdash (https://github.com/kubernetes/contrib/tree/master/perfdash)
- queue-health (https://github.com/kubernetes/test-infra/tree/master/queue_health)

prow:
- prow (https://github.com/kubernetes/test-infra/tree/master/prow)

prow-builds:
- prowjobs (presubmits, postsubmits, periodics) (https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml)
- robots/issue-creator (https://github.com/kubernetes/test-infra/tree/master/robots/issue-creator)
- boskos (https://github.com/kubernetes/test-infra/tree/master/boskos)

**Comment by BenTheElder** [comment]
a) tentatively that looks right, but one of the 3 I just assigned should check too  :-)
b) I think here since the deployment config is mostly in-tree here
c) sounds right, though I would think we would want to migrate gcsweb / k8s.io etc too?

**Comment by cjwagner** [comment]
It might be better to isolate velodrome from running prow jobs for security and to manage scaling the clusters separately. I'm not sure if either of those are real concerns though.

**Comment by BenTheElder** [comment]
This might not belong here, but just throwing out that our jobs are designed pretty heavily around a cache SSD mounted on the nodes in the build cluster, we will need to plan around that when we migrate. We also run a few associated services for things like the push gateway and `kube-lego` for https...

**Comment by spiffxp** [comment]
/lifecycle frozen
/unassign @Q-Lee @spxtr @krzyzacy @amwat @cjwagner 

@BenTheElder at this point I think we should call this the tracking issue for the one pager we're supposed to write for wg-k8s-infra

**Comment by spiffxp** [comment]
/milestone 2019-goals

I doubt I will have bandwidth for this.  It would be super help for k8s infra wg though

**Comment by spiffxp** [comment]
/wg k8s-infra
because yes, yes it would definitely be super helpful for this wg

**Comment by spiffxp** [comment]
/close
Did this in https://github.com/kubernetes/k8s.io/issues/240#issuecomment-488210434
