### ISSUE TITLE
gubernator exceeding soft memory limit

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5089]
`Exceeded soft private memory limit of 256 MB with 344 MB after servicing 0 requests total`
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/19

I'm guessing the logs are too large? /cc @rmmh

**Comment by porridge** [comment]
Duplicate of #2580 ?

**Comment by BenTheElder** [comment]
Closing in favor of #2580
