### ISSUE TITLE
GCS bucket for kops jobs?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#5120]
kops prefers to store cluster state (the k8s API objects for the cluster, along with the cluster level secrets like the CA keypair etc) in a GCS / S3 bucket.  We have an S3 bucket (`s3://k8s-kops-jenkins/`) that the test-infra AWS account can access.  For GCE clusters, it is much easier if this is a GCS bucket that the GCE service account has access to.  I know we set up a DNS name already, but I can't recall if we set up a GCS bucket?

In #5117 I put in a "placeholder name" of `gs://k8s-kops-gce-jenkins/`

**Comment by krzyzacy** [comment]
somewhere within gs://kubernetes-jenkins should be fine

**Comment by justinsb** [comment]
This does have the kubeconfig (or enough information to generate one), so it might be safer not to have it be in a world-readable bucket.  That said I believe we lock down API access by IP, so it wouldn't be catastrophic, but it would be one mistake away, instead of two mistakes away...

**Comment by krzyzacy** [comment]
@justinsb to clarify, so you want me to create a `k8s-kops-gce-jenkins` bucket with some restricted access (only by the gce service account)?

**Comment by justinsb** [comment]
Yes - that would be wonderful - thank you @krzyzacy .

I feel like we might already have one but if so I don't know what it is, and creating a new one is probably easiest.  The name doesn't really matter, so if you prefer a different name (e.g. getting rid of the word "jenkins" - that is fine with me :-) )

**Comment by krzyzacy** [comment]
ack, I'll to that Monday

/assign

**Comment by krzyzacy** [comment]
@justinsb I created `k8s-kops-gce`, can you just make sure yourself does not have access to the bucket?

**Comment by justinsb** [comment]
@krzyzacy - thanks - I have no access to that bucket :-)  Will switch the other PR to use it!
