### ISSUE TITLE
[prow] size plugin: add a comment when adding size label

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#5128]
It seems likely moving the size munger to a prow plugin affected some people's workflow.  The bot used to leave a comment indicating the size label it was adding, which some used for email filtering.  Can we add a comment back in for this?

/assign @cblecker 

/cc @thockin

**Comment by spxtr** [comment]
We can consider adding and then immediately removing the comment.

**Comment by BenTheElder** [comment]
How does this workflow handle PRs that change size? Can we point people to EG https://k8s-gubernator.appspot.com/pr ?

> We can consider adding and then immediately removing the comment.

Just discussed this at standup, this was the previous behavior with mungegithub right?

/area prow
/cc @cjwagner @kargakis

**Comment by cblecker** [comment]
Yeah, previous functionality was to comment and then clean it up. Does prow handle cleaning up stale comments?

**Comment by cjwagner** [comment]
@BenTheElder  Yes that was the previous behavior.
@cblecker Prow does offer stale comment deletion now, but I don't think that is exactly what is being suggested. Creating and then immediately deleting the comment wouldn't require any stale comment identification logic and more importantly wouldn't require listing the comments on the issue.

**Comment by kargakis** [comment]
FWIW I don't want the email about the size of my PR. Can't find any use to
it. If the bot starts commenting about every label it adds, our email
backlog ends up being a nightmare. And I really don't want to block the bot
because it also adds useful comments every now and then (eg. test failures).

**Comment by spxtr** [comment]
> FWIW I don't want the email about the size of my PR. Can't find any use to it.

Tim (and probably a few others) use the size comment to color their email threads so that they can prioritize small PRs.

**Comment by kargakis** [comment]
The same argument could be made about SIG labels. For example, I want to prioritize sig-apps API-changing PRs over sig-testing PRs over other sig-apps/sig-clusterlifecyle PRs. I don't want to tell people how to do their reviews but Github search using labels works like a charm.

https://help.github.com/articles/searching-code/

**Comment by kargakis** [comment]
Anyway I don't really mind about adding the comment if it breaks peoples' already existing work flows.

**Comment by thockin** [comment]
ping on this?

**Comment by cjwagner** [comment]
I'm not sure that bringing back the comment is a good idea.
Creating and immediately deleting GH comments for the purpose of generating an email that is solely used for email filtering seems like a bad pattern. The emails are just spam for anyone who isn't using them to auto-label email threads which I would assume is the majority of developers.
As @kargakis mentioned, we don't follow this pattern for any other label types and if we did it could quickly get out of hand. Creating and deleting comments for all (or many) label changes would use extra API tokens and spam the Github PR page itself until the page is refreshed (new comments appear without refreshing, but deleted comments are not removed).

Thoughts? If this is impacting productivity it might be a necessary evil. I'm not strongly against this, it just seems a little gross.
