### ISSUE TITLE
Common set of tags for Prow logging

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#5152]
As an administrator of a Prow cluster, I need the default logging level of all of the components to give me enough detail to follow:

 - a PR
 - a GitHub event
 - a ProwJob

From inception to completion. I would like to see annotations/JSON fields that let me use a tool like EFK to query across all components and see, for instance:

 - the initial webhook delivery into `hook`
 - which plugins act on the webhook
 - the prowjob that gets created as a result
 - what the controllers do in reaction to prowjob (starting job, finishing job, posting status)

/cc @spxtr  @kargakis @fejta 
/area prow

**Comment by stevekuznetsov** [comment]
This, in tandem with #2699 should make administration much easier. @spiffxp can we add this to the current milestone?

**Comment by spiffxp** [comment]
done, sorry for the delay

**Comment by stevekuznetsov** [comment]
@kargakis did we finish this?
/remove-lifecycle stale

**Comment by kargakis** [comment]
Needs triaging

/assign

**Comment by kargakis** [comment]
This is fine for the most part. Only thing missing is injecting fields on Github API calls but this requires re-architecturing the plugin client to make it generate github clients per plugin which has been made even more difficult after ratelimiting was introduced in the github client.

/close
