### ISSUE TITLE
Expose existence of references in build list and/or testgrid

### ISSUE THREAD

**Issue by porridge** [kubernetes/test-infra#5163]
We just noticed that [some job run pages in gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/49/)) show a "References" section with links to GitHub issues and PRs.

**This is a very valuable help in triaging test failures. Thank you for this.**

Can I ask that the presence of such references be exposed in the "[list of builds](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/)" pages and/or the [test grid](https://k8s-testgrid.appspot.com/sig-scalability-gce-scale#gce-scale-performance) itself? Whatever "link" icon or even just some unicode character such as 🔗 overlayed on the grid would be enough - just to let others on the team know that someone has already taken a look at the given failure.

@shyamjvs, FYI

**Comment by shyamjvs** [comment]
+1. That would be very useful to have.

cc @krzyzacy @cjwagner @BenTheElder

**Comment by BenTheElder** [comment]
This is definitely a very useful feature, cc @rmmh for Gubernator.
@michelle192837 I don't think testgrid has any GitHub hooks at the moment?
