### ISSUE TITLE
Only the last part of logs is stored in the GCS bucket

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#517]
I was trying to debug some failures in enormous cluster (2k Nodes) and I needed API server logs for that. Sadly it turns out that only the last hour of logs is stored, and all previous ones are dropped (probably because we compress logs after each hour if there're a lot of them and store them in .gz files).

cc @kubernetes/test-infra-maintainers

**Comment by ixdy** [comment]
Our log dumping scripts don't to any truncation: https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump.sh

It's probably something in the cluster itself (systemd?) which is truncating the logs.

**Comment by gmarek** [comment]
Yup - I'm not sure which of system daemons does that, but it certainly compresses the logs every hour.

**Comment by ixdy** [comment]
cc @kubernetes/goog-image

**Comment by gmarek** [comment]
I guess my request here is to store all parts of log files, not only the current one.

**Comment by adityakali** [comment]
You should be able see all logs in the cloud-logging, no?

The logs are rotated (moved to compressed archive) only if they exceed certain limit (>=100Mb) within an hour. The compressed logs are removed after 5 such rotations in a day. See https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L118. So you should still be able to see last 5 hours of logs on the host.

**Comment by zmerlynn** [comment]
We should consider just pulling logs from cloud-logging automatedly, but it's a little fidgety right now.

**Comment by fejta** [comment]
Sounds like the request here is to update [`save-logs()`](https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump.sh#L60) to handle rotated logs. 

@ixdy as our bash guru will you work on this and/or find another assignee from our team?

**Comment by ixdy** [comment]
Didn't someone open a PR to do that? Or am I imagining things?

**Comment by ixdy** [comment]
OK, I'm not imagining things: #32879

@gmarek / @wojtek-t can you confirm if it worked?

**Comment by wojtek-t** [comment]
Yes - I already fixed it. And it works now (since few days).
