### ISSUE TITLE
Question: Is there an OWNERS vs collaborators audit tool

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/test-infra#5175]
Prow looks at both a repos collaborators and those in the OWNERS file to determine ownership. Is there any tool that would let one audit a repo and diff who is in the OWNERS files vs who is a collaborator to look for any gaps? For example, to find someone listed in an OWNERS file who is not a collaborator.

**Comment by BenTheElder** [comment]
I'm not aware of one. It probably shouldn't be very difficult to do using the GitHub APIs though. You might want to bring this up with sig-contribex.

**Comment by kargakis** [comment]
Sounds like a useful tool to have. I think OWNERS are required to be collaborators but as people move between jobs/companies/projects, OWNERS can get stale.

**Comment by mattfarina** [comment]
The tools filter the OWNERS against the collaborators for, I believe, security purposes. Being able to do an audit would be useful for catching problems.

**Comment by kargakis** [comment]
cc @php-coder

**Comment by mattfarina** [comment]
FYI, I've written one. With a little cleanup and some tests I'll PR it to the test-infra repo.

**Comment by spiffxp** [comment]
any update on this?

**Comment by spiffxp** [comment]
The linked PR has been aged out.  I asked the author if they were going to pick it back up and they said it didn't seem like anyone wanted it.  Is there any reason for this issue to remain open @kargakis ?

**Comment by stevekuznetsov** [comment]
This would be nice, especially if we could get it automated in `verify-owners` or similar, so users get better feedback on why their OWNERS isn't working. 


/remove-lifecycle rotten

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/test-infra/pull/12297 to update the `verify-owners` plugin to ensure that all new users added to `OWNERS` and `OWNERS_ALIASES` files are org collaborators.

I'm happy to follow up on the original WIP PR https://github.com/kubernetes/test-infra/pull/6165, but wanted to double check if we still want to have this? I think it could be useful to audit old OWNERS files...but I'm not sure if this should live in test-infra or if this should be a one off tool?

cc @cblecker

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/1808 since this is about auditing OWNERS files, and that's the umbrella issue I keep linking to as I find related issues
