### ISSUE TITLE
batch merges should link to their batch run results

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#5183]
This may be obviated by tide, but I'm documenting how I just ran into it with mungegithub

This PR: https://github.com/kubernetes/kubernetes/pull/53760
- passed all presubmits
- submit queue tested it individually (/test all [submit-queue is verifying that this PR is safe to merge])
- it failed pull-kubernetes-bazel-test
- k8s-ci-robot (prow) commented as such, and linked me to https://k8s-gubernator.appspot.com/pr/53760 which also showed the test failure

At this point, I wouldn't expect the PR to merge.  It did:

- k8s-merge-robot commented that it merged the PR with a batch test
- the individual commit's status still shows a red X, and its submit-queue status shows a refusal to merge the commit
<img width="804" alt="screen shot 2017-10-25 at 6 16 52 pm" src="https://user-images.githubusercontent.com/49258/32030589-c8e510ca-b9b0-11e7-8570-1531ce18d20c.png">

- Using my knowledge of the infra, I knew to go look at http://prow.k8s.io/?type=batch and search the UI for #53760.  
- There, I could click through to the pull-kubernetes-bazel-test run for the batch: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-bazel-test/12337/

Problems with this:
- GitHub shows the commit as having merged despite it failing
- Audit trail for this PR isn't discoverable from the PR, I needed to know where to look
- If deck (or whichever components of prow) were restarted, I'm not sure I'd be able to find the right gubernator link for the batch run

What I would expect to happen:
- if the PR merges in batch, after having flaked/failed in single, the commit status contexts should update to point to the batch results
- ideally, there would be a more permanent landing page (maybe in gubernator?) for "all results for the batch run that included this PR" vs. me having to spelunk through prow.k8s.io
- alternatively, the results for the batch run that included this PR would show up in the PR's result history at https://k8s-gubernator.appspot.com/pr/53760

/area mungegithub
/area gubernator
since this is where I encountered it

/area prow
since this is where merge logic is heading

**Comment by spiffxp** [comment]
/remove-lifecycle stale
this is still a usability bug, removing stale to see if this is a thing we need to revisit when tide rolls through

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/lifecycle frozen
This is going to be a problem as long as we leave the submit queue untouched, and it's unclear to me whether tide solves this (I couldn't find a recent example of a tide-based batch merge.)

**Comment by stevekuznetsov** [comment]
@krzyzacy the reporter should handle this better

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/remove-area mungegithub

Unfortunately this is still a problem with tide

https://github.com/kubernetes/kubernetes/pull/68649 was merged after being tested in a batch
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce/52947/ is one of the batch jobs
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/68649/pull-kubernetes-e2e-gce/52946/ is what's linked off of the merge commit's context details
- https://k8s-gubernator.appspot.com/pr/68649 doesn't show the batch run
- https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes%2Fkubernetes+author%3Aneolit123+head%3Akubeadm-ver-bump doesn't show the batch run

The only way I found this was https://prow.k8s.io/?type=batch

FYI @cjwagner

**Comment by cjwagner** [comment]
Tide doesn't comment on the PR when it merges like the SQ did. That could be worth doing for batch merges.
Now we can link directly to the batch results as well thanks to: https://github.com/kubernetes/test-infra/pull/7562

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/milestone v1.14
/assign @cjwagner 

I think based on talking to @cjwagner offline that the tide action history may address the concerns here

**Comment by cjwagner** [comment]
Yes it should definitely help, but commenting directly on the PR with a link to the tide history for the PR might still be a good idea.

**Comment by spiffxp** [comment]
/milestone v1.15
FYI @fejta @cjwagner I feel like I ran across another contributor being confused by this recently, however this keeps falling stale. Are we going to address this?

**Comment by cjwagner** [comment]
I think this would make a good first issue (in particular for our summer intern starting at the end of this month).
/help
If that doesn't end up happening I'll make a PR myself next month.

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
ok, let's freshen this up one more time then

**Comment by stevekuznetsov** [comment]
Related to https://github.com/kubernetes/test-infra/issues/10402

**Comment by spiffxp** [comment]
Ran into this again.  I was trying to figure out which PR out of N batches was causing the `pull-kuberentes-verify` job to fail

**Comment by spiffxp** [comment]
/reopen
/remove-lifecycle rotten
/remove-area gubernator
/area prow/crier
/area prow/deck

Since I happened to be reviewing https://github.com/kubernetes/test-infra/pull/17142 for part of https://github.com/kubernetes/test-infra/issues/10402 (comment on PR on postsubmit failure)

The GitHub reporter explicitly does not report for a prowjob with N pulls in its refs
https://github.com/kubernetes/test-infra/blob/0214d73dd35b87730d5fa05d713c81c9404b51fa/prow/github/report/report.go#L141-L144

If it did, it would only report on the SHA of the "first" pull (whatever order that happens to be)
https://github.com/kubernetes/test-infra/blob/0214d73dd35b87730d5fa05d713c81c9404b51fa/prow/github/report/report.go#L93-L95

Running through the state of things today...

Tide history showing a batch merge (ref of `master` before merges pushed, PR number (SHA of PR's latest commit)
![Screen Shot 2021-02-20 at 5 40 02 PM](https://user-images.githubusercontent.com/49258/108610299-aaa88880-73a2-11eb-830d-2962ed32edcf.png)

The base commit + merge commits for each PR (base commit randomly has an X, not important, but proof postsubmits do fail)
![Screen Shot 2021-02-20 at 6 55 29 PM](https://user-images.githubusercontent.com/49258/108611509-358e8080-73ad-11eb-9d19-4d7b4938f329.png)

The postsubmits that posted to the first merge commit:
![Screen Shot 2021-02-20 at 6 58 11 PM](https://user-images.githubusercontent.com/49258/108611565-95852700-73ad-11eb-92af-53692e807d33.png)
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-bazel-build/1362678488816947200/
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-bazel-build/1362678488842113024

The status contexts for the first PR that merged when I click "view details" (note: the sha displayed is the merge commit)
![Screen Shot 2021-02-20 at 7 03 32 PM](https://user-images.githubusercontent.com/49258/108611631-54d9dd80-73ae-11eb-8f47-fa28b99cb019.png)
- some contexts stuck in "job triggered", tide's context in "not mergeable"
- details for a "job triggered" context link here https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/98358/pull-kubernetes-e2e-gce-ubuntu-containerd/1362666833311698944/
- clicking to PR details for that gets me here: https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=98358
- which also doesn't show green for the stuck jobs

(tbc)

**Comment by YuviGold** [comment]
I would like to pick this up
/assign

**Comment by BenTheElder** [comment]
I think we mostly did this? For any further needs, please file with https://github.com/kuberntes-sigs/prow
