### ISSUE TITLE
fix keyword should not close other PRs, only Issues

### ISSUE THREAD

**Issue by sjenning** [kubernetes/test-infra#5189]
This happened here https://github.com/kubernetes/kubernetes/pull/54593

Where the syntax "fix #54593" was used in another PR description and it closed the PR.

IMO, auto-closing should only happen if the target is an Issue.

@joelsmith @dashpole

**Comment by cblecker** [comment]
@sjenning This is a github feature, not related to kubernetes bots: https://help.github.com/articles/closing-issues-using-keywords/

If a PR author adds a keyword like that, and the account that does the merge has the ability to close the issue/PR (the bots have access to all k/ repos), then it will look as though the bot closed the issue/PR.

**Comment by sjenning** [comment]
@cblecker ah ok.  My thinking was that close was attributed to the bot, hence the confusion.
```
k8s-merge-robot closed this in #54597 8 hours ago
```

**Comment by BenTheElder** [comment]
Maybe we should raise an issue with GitHub about how they display this?  The wording is very misleading. *GitHub* closes the issue in response to the merge but they attribute it to the account that merged :confused:

**Comment by spxtr** [comment]
I've asked GitHub about this feature since it's pretty confusing. Didn't get much of a response. It's particularly annoying that it closes issues in other repos when you sync your fork.

![closed1](https://user-images.githubusercontent.com/7368979/32083882-d1c2c15e-ba7a-11e7-9fde-9a1ff5917a33.png)
