### ISSUE TITLE
wip command for bot - add label

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#5194]
How about a /wip command that marks the PR with the do-not-merge/work-in-progress label?  Does the merge bot respect that label and not merge code?

**Comment by dims** [comment]
Chris, there's a `/hold` https://github.com/kubernetes/test-infra/blob/master/commands.md

**Comment by chrislovecnm** [comment]
hrm.  `/hold` does not quite match the workflow we have been using in kops repo.  Let me ponder.

**Comment by kargakis** [comment]
Add `WIP` as a prefix in your PR title and the label should be added automatically.

**Comment by BenTheElder** [comment]
if you put `WIP` in the PR title it will add that label (which blocks), I don't think we have an equivalent command currently besides /hold.

**Comment by chrislovecnm** [comment]
@BenTheElder the bot may not be keying on that correctly :( https://github.com/kubernetes/kops/pull/3705

**Comment by chrislovecnm** [comment]
@BenTheElder you mind re-opening this ... SGTM

**Comment by BenTheElder** [comment]
Er what's not keying correctly?

**Comment by chrislovecnm** [comment]
Added WIP to the name of that PR, and the bot did not add the label, again please re-open this issue.  Another bot command we need :P

**Comment by BenTheElder** [comment]
The title does not contain WIP currently?

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/pull/3705 <- that does

**Comment by BenTheElder** [comment]
OH I see now, it only looks for WIP as a prefix, you put it as a suffix.
hmm @cjwagner @xiangpengzhao @stevekuznetsov thoughts on WIP as suffix?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/blob/ad19d04798049201a82c70639900bba593e740d6/prow/plugins/wip/wip-label.go#L40

**Comment by chrislovecnm** [comment]
Let me test prefix ...

**Comment by chrislovecnm** [comment]
Also, ALOT of people including @bgrant0607 do not like the WIP in the title.  Changing the title messes with notification via email.  At least it did with threading emails in the past.  The original request still stands.  I would like a bot command to add the WIP label.

**Comment by BenTheElder** [comment]
Ok, there was previous discussion in favor of the title though

**Comment by cjwagner** [comment]
I think it makes sense to change the regexp to accept "WIP" anywhere in the title. This regexp seems to work properly:
```
`(?i)(?:^|\W)WIP(?:$|\W)`
```

If we are going to use commands to manage the `do-not-merge/work-in-progess` label we may need to disable the current functionality that allows using "WIP" in the PR title. Otherwise PRs can get into confusing states like when the title contains WIP but the PR does not have the label.

**Comment by chrislovecnm** [comment]
@cjwagner having "hold" and WIP is kinda confusing admittedly.  I literally saw a 2nd-time committer use /wip on a PR.  This is what started me thinking about this.   This is a topic that contribx should probably weigh in on.

**Comment by kargakis** [comment]
It's the first time I am seeing WIP used as a suffix. Do we document how this works somewhere? I prefer using the prefix over the command, usually I am paying more attention into how I name my PR before I open it rather than the set of labels that it will have. In my experience most people don't pay attention to bot commands when they open PRs, too.

**Comment by xiangpengzhao** [comment]
IMO, any workable way to pend a PR is ok, what is a bit more important is to make contributors know how to. We have documented how to [mark unfinished PR](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#marking-unfinished-pull-requests). But I doubt if contributors can find the doc when they create PR. I just send a commit https://github.com/kubernetes/kubernetes/pull/54114/commits/1b0cd925a4bc689872726c3b8eaf456352f96f0b to add it to PR template.

**Comment by stevekuznetsov** [comment]
WIP is meant to be an entry-point to the k8s bots. It's supposed to support something that some developers do anyway and as soon as they have more complex questions -- that is where `/hold` comes in. We want developers to use bot commands in their comments and this was a way to give a learning curve to that. I'm not sure we should re-hash this discussion again, but we can see the older issues for the last time(s) we did:

https://github.com/kubernetes/test-infra/pull/4145
https://github.com/kubernetes/test-infra/pull/4572

fyi @fejta

**Comment by stevekuznetsov** [comment]
I'm not sure there is any future for a `/wip` command. There's not really any functional difference between it and `/hold` and as per my last comment this conversation has happened a couple times already.

/close
