### ISSUE TITLE
Prow GitHub Client test flakes

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5208]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5137/pull-test-infra-bazel-canary/24/#prowgithubgo_default_test

```
--- FAIL: TestRequestRateLimit (0.04s)
	client_test.go:63: Expected to sleep for at least a second, got 999.500002ms
FAIL
```

/shrug
/kind bug
/area prow

**Comment by krzyzacy** [comment]
😂 it probably should not be doing real sleep in the test

**Comment by BenTheElder** [comment]
> 😂 it probably should not be doing real sleep in the test

That was my first thought, I was all ready to write a bug about how sleep is not deterministic enough for this, but actually it swaps out a reference to time.Sleep stored in a private package var (`timeSleep`), this is actually flaking because some time.Duration math flaked slightly below 1000ms and the test is for `time.Second < slept`

**Comment by spxtr** [comment]
Oh whoops, that can flake. [This line](https://github.com/kubernetes/test-infra/blob/cb858afc6993fb22a167f0353d17715c9a8910d9/prow/github/client_test.go#L51) in the test and [this line](https://github.com/kubernetes/test-infra/blob/cc46a1e505ab724e568dcc01d4cdba4b0fc3eb35/prow/github/client.go#L193) in the code.

**Comment by BenTheElder** [comment]
We should probably fix this :joy:
/assign
FYI @cjwagner
