### ISSUE TITLE
Probable Gubernator Test Flake

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5210]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5209/pull-test-infra-gubernator/564/

Lots of errors similar to: `ERROR:root:unable to fetch 'http://testbed.example.com/_ah/gcs/foo/quux': status code 4`

/area gubernator
/kind bug
/cc @rmmh

**Comment by BenTheElder** [comment]
I haven't seen this since.
FYI @rmmh though

**Comment by MushuEE** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/18536/pull-test-infra-gubernator/1303399283109662724

Seen again here
