### ISSUE TITLE
prow updateconfig: only update on merge to default branch 

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5212]
Suggested by @fejta, we probably should fix the updateconfig plugin to only consider merges to master.
It looks like we should be able to check if the branch is the `default_branch` for the repo before updating the config.

/area prow

**Comment by BenTheElder** [comment]
@cjwagner do we still want this?
/shrug

**Comment by cjwagner** [comment]
Yes, thats a bug.
/assign
