### ISSUE TITLE
Use ProwJobs in deck

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5216]
deck is using its own format for exposing jobs that predates ProwJobs. We should get rid of the old format in favor of using ProwJobs.

TODO:
- [x] Expose ProwJobs in deck at `/prowjobs.js` or something. (https://github.com/kubernetes/test-infra/pull/5631)
- [ ] Switch the JS to look at those. (https://github.com/kubernetes/test-infra/pull/7301)
- [ ] Switch the flake detector stuff to look at those.
- [ ] (fwiw) Switch the [submit queue](https://github.com/kubernetes/test-infra/blob/b666c823028538796261104b1f074b5a76183002/mungegithub/mungers/submit-queue.go#L708) to use the new endpoint and a correct [timestamp format](https://github.com/kubernetes/test-infra/blob/b666c823028538796261104b1f074b5a76183002/mungegithub/mungers/submit-queue.go#L743).
- [ ] Delete `/data.js` and associated machinery.

/area prow

**Comment by kargakis** [comment]
For clarity and why I think this is important, here is the description I created in a Trello card that unfortunately is private.

> The prow frontend exposes a **[JSON blob of all tests in the system](https://deck-ci.svc.ci.openshift.org/data.js)** that can be used for programmatic access by tools without the need to reside inside our CI cluster. The problem with the exposed format is that it predates ProwJobs (canonical representation of tests in prow) thus any tools built on top of the prow frontend are incompatible with all existing prow utilities and furthermore the exposed format lacks necessary information included in ProwJobs (eg. year in timestamps).
>
> We should fix deck to expose ProwJobs instead of the old format before developers start building on top of the old format (I know one of our devs is already looking into building on top of prow). This is blocking the `refresh` plugin, too: https://github.com/kubernetes/test-infra/pull/5075
>
> The work required includes changes in deck: both frontend (Javascript) and backend (Go).
>
> https://github.com/kubernetes/test-infra/tree/master/prow/cmd/deck
>
> https://github.com/kubernetes/test-infra/issues/5216

**Comment by spxtr** [comment]
This is actually pretty important, because it lets me dry run a copy of tide or plank or something without needing access to the k8s api server.

**Comment by spxtr** [comment]
- [ ] Expose ProwJobs in deck at `/prowjobs.js` or something.
- [ ] Switch the JS and to look at those.
- [ ] Switch the flake detector stuff to look at those.
- [ ] Delete `/data.js` and associated machinery.

**Comment by katerinapat** [comment]
I'm working on  the sub task  _Switch the JS to look at those._

**Comment by rmmh** [comment]
data.js is 11MB (indented json, 820KB compressed). prowjobs.js is 33MB (unindented json, 1.93MB compressed).

You shouldn't have to load that much data to view jobs. If you drop pod_spec and metadata from prowjobs.json, it's only 730KB compressed.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
@kargakis what was the status here?

**Comment by ibzib** [comment]
/unasssign
![homer-bushes](https://user-images.githubusercontent.com/16039734/54570609-633a4600-499c-11e9-830b-f1025bd8854a.gif)

**Comment by spiffxp** [comment]
/assign @stevekuznetsov 
Removing the labels but doing nothing repeatedly is perhaps a sign that this issue isn't going to get done.  Is this still relevant?  What's your plan?

**Comment by clarketm** [comment]
@stevekuznetsov 
If this is still relevant and no one else is actively working on it then I can pick it up. It would appear that a large chunk of the implementation is already complete or in PR.

**Comment by stevekuznetsov** [comment]
Yes, it's still relevant. There's no great reason to use the intermediate representation for the front-end, it can just operate on the actual ProwJobs.

**Comment by stevekuznetsov** [comment]
(Coalescing the two reduces mental overhead for devs and reviewers)

**Comment by clarketm** [comment]
Even with the `pod_spec` omitted, for large instances, the `prowjobs` format is **twice** the size of the custom `job` format.

e.g. `https://prow.k8s.io` - `2019-08-28T22:46:13-07:00`
![image](https://user-images.githubusercontent.com/9957358/63913608-95d57980-c9e5-11e9-9cc0-2b2f470d3345.png)

**Comment by stevekuznetsov** [comment]
Why? What's the worry about size?

**Comment by Katharine** [comment]
55 MB of javascript to _load a webpage_ is truly absurd.

**Comment by clarketm** [comment]
@stevekuznetsov - I have not run any benchmarks, but my primary concern is *load time* and the fact that a most of the prowjob data is unused. *Pagination* is another option to reduce to reduce payload size but would require additional changes to FE.

**Comment by stevekuznetsov** [comment]
We have metrics on load time for the page, let's use them. https://monitoring.prow.k8s.io/d/c27162ae7ad9ce08d2dcfa2d5ce7fee8/deck-dashboard?orgId=1

If we transparently hide fields I guess that's fine, or render server-side ... I think I'd prefer to see server-side endpoints for digested data over weird quasi-filled objects with nullable fields

**Comment by Katharine** [comment]
The upshot is that the page will take about twice as long to load as it does today (having measured this on a very fast machine with a very fast internet connection, it adds an extra 1.5 seconds - if your machine parses JS slower or does not have gigabit internet, it will be worse), which I don't think is something I particularly want to ship.

**Comment by stevekuznetsov** [comment]
We also never display all ~40k prowjobs to the user, so why not ask the backend for the last 100?

**Comment by clarketm** [comment]
@stevekuznetsov - they do not get displayed in the table (without filters applied), but they get added to the job histogram and can be show if the a filter is applied and a job matched that filter (one that may have not been one of the most recent 500).

**Comment by clarketm** [comment]
@stevekuznetsov @Katharine 

By also omitting `metadata.annotations`, `metadata.labels`, `spec.decoration_config` I can reduced the size significantly.


![image](https://user-images.githubusercontent.com/9957358/63963355-b2a39880-ca49-11e9-8483-659cd11b12d9.png)
> Note: `prowjobs2.js` omits the additional fields above.

**Comment by stevekuznetsov** [comment]
I don't really know if it's _that_ useful to show the histogram and bar chart breakdown for _all_ jobs. Those are useful diagnostic tools once you filter but otherwise are just novel.

**Comment by clarketm** [comment]
@stevekuznetsov - I agree with you ... but my second point was that if we only return `500` jobs on load, then the remaining **n** amount of jobs will not be known to the front-end; since filtering in the UI does not make an API call, but rather uses the `allBuilds`  javascript requested onload, information will be lost on FE.

**Comment by stevekuznetsov** [comment]
Right. I guess we could also just make more pointed requests to the backend -- pass along the filter options and do the filtering server-side. If we want to have 55M of data to work with we can't also hold it all in the front-end and work on it there. Will be faster in Go anyway ;)

**Comment by clarketm** [comment]
I agree with you that the *filtering*, *sorting*, *punning* can be better (and more robustly) handled server-side. The implementation on FE should be trivial; most of the effort will be server-side to build the API to accept additional parameters and properly munge this information. I can start a design for this.

For now, if we want to move forward with `prowjobs.js` (https://github.com/kubernetes/test-infra/issues/5216#issuecomment-526289836) we can omit the fields I list above (https://github.com/kubernetes/test-infra/issues/5216#issuecomment-526289836) to get a comparable payload size to the original.

**Comment by clarketm** [comment]
@stevekuznetsov 

Once #14254 and #14258 go through, you can tick off the last remaining task checkboxes and close this issue.
