### ISSUE TITLE
Regional tests failing due to old gcloud

### ISSUE THREAD

**Issue by x13n** [kubernetes/test-infra#5218]
Clusters are not being created: https://k8s-testgrid.appspot.com/google-gke#gke-regional

/cc @wojtek-t

**Comment by wojtek-t** [comment]
Please revert the config file change then (temporarily)

**Comment by krzyzacy** [comment]
/assign
xref https://github.com/kubernetes/test-infra/pull/5226

**Comment by krzyzacy** [comment]
/unassign
/assign @x13n 
@x13n I've bump the image, can you verify and close if it works?

**Comment by wojtek-t** [comment]
@x13n - please bump the tests to use gcloud beta again and check.

**Comment by x13n** [comment]
Opened https://github.com/kubernetes/test-infra/pull/5247 to move to beta again, will close this issue if it works.

**Comment by x13n** [comment]
Tests passed with beta in the flag, closing.
