### ISSUE TITLE
Measure and increase kubernetes test coverage

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#5231]
We need tools that allow us measure unit, api, etc coverage.
The results from these tools need to be something that contributors can easily replicate on their workstation.

We need to define systems for measuring this data on a continuous basis, publishing it somewhere externally accessible.

We need a process that results in driving this data in a better direction over time.

/cc @oomichi 

Unit coverage will need https://github.com/bazelbuild/rules_go/issues/140

**Comment by oomichi** [comment]
Thanks, fejta. That works fine :)

**Comment by oomichi** [comment]
As the first step, I have written some design doc for measuring e2e test API coverage:

https://docs.google.com/document/d/1Upo8lTeR7gy4olD6hASTCdn8Vy7WuDwkO_o9Y5nrxhs/edit?usp=sharing

Happy to see feedback.

**Comment by oomichi** [comment]
This issue seems a little wider scope to manage API measuring thing.
I created another issue(https://github.com/kubernetes/test-infra/issues/5701) to manage that.

**Comment by mithrav** [comment]
/assign @mithrav
Assigning myself as I look through this more.

**Comment by spiffxp** [comment]
/milestone 1.12
I guess.  This seems more like an umbrella but oh well

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/milestone v1.14
/unassign @oomichi 
/assign @spiffxp @Katharine 

So this still feels like an umbrella issue that could be referring to api coverage, e2e coverage, unit coverage, etc.

Let's figure out what subset of this is feasible for this release cycle.  We're surfacing some subset of e2e test coverage, but I'm not sure we've reached the point where it's conveniently actionable.

**Comment by oomichi** [comment]
@spiffxp 
Can https://github.com/kubernetes/kubernetes/pull/72935 help for improving unit test coverage?
Or do we have already this kind of tool?

**Comment by spiffxp** [comment]
/unassign
in case someone else wants to give this a shot
/remove-lifecycle stale
/milestone v1.15
this is on my radar for v1.15
