### ISSUE TITLE
links testgrid test or job failures to triage clusters

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#5233]
An idea I dropped in slack, sounded like we didn't have an issue for it.

As a human, I look at a testgrid summary tab.  When I see there is a failing job, I see what the failing tests are for it.  I then plug that failing test into our triage report to see what other jobs that test is failing for.  From there, I use the triage cluster uid's to search github for existing issues, or create new issues in github.  Then I can tie issues to test failures, and figure out whether someone is working to address the test failure.

eg:
- https://k8s-testgrid.appspot.com/sig-release-master-blocking#Summary shows me gci-gce-serial is failing, so I use a link to https://go.k8s.io/triage?job=gci-gce-serial (bonus points if I link to the actual job, eg: https://go.k8s.io/triage?job=%5Eci-kubernetes-e2e-gci-gce-serial%24)
- "[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: CPU) [sig-autoscaling] [Serial] [Slow] Deployment Should scale from 1 pod to 3 pods and from 3 to 5" is one of the tests failing for that job, so I use a link to https://go.k8s.io/triage?test=%5C%5Bsig%5C-autoscaling%5C%5D%5C%20%5C%5BHPA%5C%5D%5C%20Horizontal%5C%20pod%5C%20autoscaling%5C%20%5C(scale%5C%20resource%3A%5C%20CPU%5C)%5C%20%5C%5Bsig%5C-autoscaling%5C%5D%5C%20%5C%5BSerial%5C%5D%5C%20%5C%5BSlow%5C%5D%5C%20Deployment%5C%20Should%5C%20scale%5C%20from%5C%201%5C%20pod%5C%20to%5C%203%5C%20pods%5C%20and%5C%20from%5C%203%5C%20to%5C%205
- [b75045e2cb613e12dca1](https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-autoscaling%5C%5D%5C%20%5C%5BHPA%5C%5D%5C%20Horizontal%5C%20pod%5C%20autoscaling%5C%20%5C(scale%5C%20resource%3A%5C%20CPU%5C)%5C%20%5C%5Bsig%5C-autoscaling%5C%5D%5C%20%5C%5BSerial%5C%5D%5C%20%5C%5BSlow%5C%5D%5C%20Deployment%5C%20Should%5C%20scale%5C%20from%5C%201%5C%20pod%5C%20to%5C%203%5C%20pods%5C%20and%5C%20from%5C%203%5C%20to%5C%205#b75045e2cb613e12dca1) is the top failure cluster, and it looks visually interesting... I click the github search link
- https://github.com/search?type=Issues&q=org:kubernetes%20b75045e2cb613e12dca1 shows me there are two github issues that mention this failure cluster
- Now I have links to some issues that I can tie back to one of the continuously failing tests for a continuously failing job on testgrid

Some of this might be able to be automated or facilitated by links auto-generated by testgrid?

Some of this might be able to happen externally with the json data testgrid provides today at https://testgrid.k8s.io/release-master-blocking/summary

FYI @michelle192837 @fejta 

/area testgrid

**Comment by michelle192837** [comment]
/reopen

Actually missed this. I think this is a thing that is not necessarily happening this quarter, but is worth discussing integration for (maybe for Q3 unless someone wants to tackle it sooner).
