### ISSUE TITLE
Latest kubekins-e2e doesn't correspond to repo?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#5240]
I'm trying to track down why https://k8s-testgrid.appspot.com/google-aws#kops-aws-newrunner isn't running the new log dumping code.  The latest-image doesn't seem to match anything I would expect:

https://console.cloud.google.com/gcr/images/k8s-testimages/GLOBAL/kubekins-e2e

I see latest-master as also being tagged `v20171027-cedaacb4-master`, but I can't find the git revision `cedaacb4`.  I can find the other git revisions though!

Is that middle hex string supposed to be a git sha?  And where is `cedaacb4` if so?

**Comment by BenTheElder** [comment]
/cc @krzyzacy 
I believe those are supposed to be git SHAs. not sure about that one.
/area images

**Comment by krzyzacy** [comment]
@justinsb I probably was experimenting something with my own kubetest. (I always sync to head btw). If you care about the image SHA you probably should pin it to a stable tag :-)

**Comment by BenTheElder** [comment]
Yeah but `git cat-file -t cedaacb4` vs `git cat-file -t 529d2fdac`, seems that commit doesn't exist? @krzyzacy

**Comment by krzyzacy** [comment]
```
senlu@senlu:~/work/src/k8s.io/test-infra$ git cat-file -t cedaacb4
commit
senlu@senlu:~/work/src/k8s.io/test-infra$ git cat-file -t 529d2fdac
commit

commit cedaacb460696a81baa85271ce8210076c51ddc6 (src-first)
Author: Sen Lu <senlu@google.com>
Date:   Fri Oct 27 15:52:25 2017 -0700

    Extract src before binary
```

It's from https://github.com/kubernetes/test-infra/pull/5232
