### ISSUE TITLE
Cache bot name on hook startup.

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#5248]
@kargakis wrote in https://github.com/kubernetes/test-infra/pull/5115#discussion_r147669428:

`botName, err := ghc.BotName()`

>There are a bunch of plugins that need this so we could potentially figure this out on hook startup once, cache, and then reuse it. Follow-up issue to discuss is better than fixing it here.

**Comment by kargakis** [comment]
Seems to be already what I wanted. Sorry for the noise

/close
