### ISSUE TITLE
PR Dashboard: Merged PR stuck in my "Outgoing" section

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#5251]
This PR merged: https://github.com/kubernetes/kops/pull/3621

But it is still showing in my "outgoing" section: https://k8s-gubernator.appspot.com/pr/justinsb

I can't figure out how to request a refresh of that PR...

**Comment by BenTheElder** [comment]
cc @rmmh 
/area gubernator
/kind bug

**Comment by rmmh** [comment]
The easiest way to fix this is to edit one of your comments on the PR.

**Comment by justinsb** [comment]
Will do, thanks.  As you can probably see, it doesn't add that much noise to my dashboard, if you'd rather I didn't touch it (if you wanted to use it to diagnose something)?  But not a big deal, just though I would report it...

**Comment by rmmh** [comment]
Dupe of #1576. I don't have logic to retry when hook processing fails for some reason, but it generally resolves itself on the next event.
