### ISSUE TITLE
/approve associatedIssueRegex hardcodes the kubernetes org

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5264]
Needs to be configurable

/area prow

**Comment by nikhita** [comment]
/assign
I'm leading a pair programming table at the diversity lunch today at KubeCon and I'll help someone work on this (and some other tasks) + give them a small codebase tour of other prow plugins.

If a PR does not end up stemming from the pair programming session, I'll follow up myself.

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/12042

/close
