### ISSUE TITLE
milestonestatus plugin spams github team in informational message

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/test-infra#5271]
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/milestonestatus/milestonestatus.go#L34

posts:
>You must be a member of the @kubernetes/kubernetes-milestone-maintainers github team to add status labels.

Which spams me. Not cool.

**Comment by grodrigues3** [comment]
@kubernetes/sig-contributor-experience-bugs
