### ISSUE TITLE
Milestonestatus Prow plugin should not hard code kubernetes-milestone-maintainers team.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#5276]
This should be configurable:
https://github.com/kubernetes/test-infra/blob/1582cf827ee8ba291ff0d5dbd68c6fd9da82f58f/prow/plugins/milestonestatus/milestonestatus.go#L34
/assign @marun @cjwagner

**Comment by BenTheElder** [comment]
it would be great if this were per-repo configurable, so we could use it for modifying the milestones in non-core repos with different groups as well...

**Comment by amwat** [comment]
Hasn't this been fixed when we [migrated from using milestonestatus to milestone instead](https://github.com/kubernetes/test-infra/commit/77ba0bb8e2b99754f4b8159a7efcdb293dbad947) as described [here](https://github.com/kubernetes/test-infra/blob/1027cba002af307fbbfef8da0e8a136fb084b2c0/prow/plugins/milestone/milestone.go#L57)? or is it not per repo yet.

**Comment by cjwagner** [comment]
@amwat Those plugins are distinct, there was no plugin migration, they just share some configuration. This is still a problem:
https://github.com/kubernetes/test-infra/blob/1027cba002af307fbbfef8da0e8a136fb084b2c0/prow/plugins/milestonestatus/milestonestatus.go#L37
