### ISSUE TITLE
Document how prow can be extended

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5278]
We need documentation for:
* how prow can support a new CI system (write a new controller, configure prow to use the new controller) - this includes exposing logs and making deck consume those logs
* how hook can be extended (write a new plugin, configure prow to use the new plugin)
* sharding

/area prow
/kind documentation
/assign

**Comment by stevekuznetsov** [comment]
/remove-lifecycle rotten

We need this but at this point it should be a simple kubebuilder controller over prowjobs and whatever target resources
