### ISSUE TITLE
Serve documentation in deck

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5279]
We should consider exposing prow docs in deck.

/area prow
/kind feature
/kind documentation

**Comment by BenTheElder** [comment]
@qhuynh96 interested in this?

I don't think anyone is working on this just yet but we seem to be headed in this direction with EG the plugin help. Serving a versioned copy of Prow docs in deck seems like a good enhancement.
/remove-lifecycle stale

**Comment by qhuynh96** [comment]
Do we have existing docs to be served?

**Comment by BenTheElder** [comment]
There's always https://github.com/kubernetes/test-infra/blob/master/prow/README.md, we could serve this from deck.

**Comment by qhuynh96** [comment]
Sweet! I will pull it to deck.

/assign

**Comment by kargakis** [comment]
I would love this to be as much generic as possible and not include Google-specific instructions like `gcloud`/`bazel` call-outs. Ideally, when I search through prow docs I want to learn how to configure jobs, where should I submit my changes, what each job type means, and potentially what each config knob means. For config documentation, we could potentially generate an openapi spec that uses godoc comments which are then served by prow.

**Comment by droslean** [comment]
There are no plans to serve the documentation in `deck`.
