### ISSUE TITLE
Prow should redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#5282]
Currently http://prow.k8s.io/ does not redirect to HTTPS. 
Mungegithub does this with an nginx proxy.  I'm not sure what the best option is for Prow or how important this really is.

/area prow

**Comment by spxtr** [comment]
We should add an nginx proxy as well.

**Comment by BenTheElder** [comment]
> We should add an nginx proxy as well.

I don't think this is necessary, it should be easy to optionally route this in deck. We can just insert all our routing behind an HTTPS check method before continuing on to the actual router in main if we detect that this has been enabled.

**Comment by cjwagner** [comment]
fixed in #6122 
/close
