### ISSUE TITLE
startTime in prowjobs should be set when a controller switches the pj to pending

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5292]
prowjobs already have a creationTimestamp set by the api server. Tests though may not start immediately after a prowjob is created.

/area prow

**Comment by spxtr** [comment]
Agreed. There are a couple times to track:

1. Time between trigger and pod (or Jenkins job) creation, and
1. Time between pod creation and completion.

The API server gives us prowjob creation time, so I'm fine with switching startTime to pod/job start time.

**Comment by stevekuznetsov** [comment]
@krzyzacy this bit you, right?

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

we could use this to clean up hung/dead "running" pods @krzyzacy @cjwagner 
this would be useful for periodics in particular where a hung pod means we won't schedule a new run and we have to manually clean it up. EG https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-local-e2e-containerized/206/ from the 6th is hung atm.

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
I'm taking no action on this in ~2 years as a sign that it's no longer that important
