### ISSUE TITLE
Enforcing sig labels on PR(s)

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#5293]
As an effort to increase sig ownership of things. 

- Can we please start marking PR(s) with the same sig(s) that the issues they fix are marked with? 
- Add needs-sig label if they don’t have any associated issue?

This will help SIG(s) know what they have to review easily and for release team to find the right owner when things need to get merged/rebased before release milestones.

Do we want to go the extra mile of not approving until there's a sig? or not allowing tests to run until a sig is specified? (I am not advocating for either one, i'd just start with the two things above).

**Comment by spiffxp** [comment]
Traversing issue links isn't something github's API supports.  It's gonna get messy if we start doing this.  But I agree it might help drive PR's down.

Other thought, this might be a good devstats dashboard request.  [prs-age](https://devstats.k8s.io/dashboard/db/prs-age?orgId=1) doesn't filter by sig, but it could ([issues-age](https://devstats.k8s.io/dashboard/db/issues-age?orgId=1) can)

@kubernetes/sig-contributor-experience-feature-requests @kubernetes/sig-testing-feature-requests

**Comment by BenTheElder** [comment]
> Traversing issue links isn't something github's API supports. It's gonna get messy if we start doing this. But I agree it might help drive PR's down.

Yeah, I really don't think the GitHub API helps us out too much here but it might still be possible :thinking: 

> Other thought, this might be a good devstats dashboard request. prs-age doesn't filter by sig, but it could (issues-age can)

Yes! :+1:
