### ISSUE TITLE
Idea : Gubernator for SIG(s)

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#5294]
https://k8s-gubernator.appspot.com/pr/ is AWESOME. Can we do a similar view/report for all things SIG? 

folks can select/mark which SIG(s) they are interested in and we can show similar information as we do for the single user.

Hoping such a tool will increase SIG owner(s) and participant(s) to quickly identify things that need attention instead of relying on github notifications overload.

**Comment by BenTheElder** [comment]
Agree that the PR dashboard is awesome :-)
A quick lofi solution would be to create dummy `@kubernetes-sig-foo` accounts and assign them to issues which should be viewable like https://k8s-gubernator.appspot.com/pr/dims (but not ACK-able).

cc @rmmh 
/area gubernator
/kind feature
