### ISSUE TITLE
vendor tests are running in test-infra (?)

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#5304]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/5284/pull-test-infra-bazel/9538/

**Comment by spxtr** [comment]
Err, godep is supposed to drop all `_test.go` files.

**Comment by krzyzacy** [comment]
ah - @spxtr I think you are right - since these days we are adding dependencies manually in test-infra

**Comment by dims** [comment]
hehe, i thought it was by design i saw it a few days ago.

**Comment by BenTheElder** [comment]
> Err, godep is supposed to drop all _test.go files.

We shouldn't be running them anyhow. k/k explicitly excludes vendor in bazel test/build for this reason.

**Comment by spxtr** [comment]
k/k excludes them because of the staging stuff I think. Could be wrong. We can exclude them as in this PR but we should also remove them at the same time.

**Comment by BenTheElder** [comment]
fixed in https://github.com/kubernetes/test-infra/pull/5308
we should still fix the vendor dir, see https://github.com/kubernetes/test-infra/pull/5301
