### ISSUE TITLE
testgrid for node e2e test is messed up.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/test-infra#5314]
See https://k8s-testgrid.appspot.com/sig-node-containerd#node-e2e
and https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet.

Test cases move around arbitrarily.

**Comment by krzyzacy** [comment]
we added sort by failures by default, but seems there are cases that dont want this behavior?
/assign @fejta

**Comment by krzyzacy** [comment]
I would say this is WAI to prioritize failure entries, closing

**Comment by michelle192837** [comment]
It's possible to change the sorting on a per-dashboard basis. You want to add:

base_options: 'sort-by-name='

**Comment by michelle192837** [comment]
That said, otherwise this is working as intended, yes.
