### ISSUE TITLE
Document stable1, stable2, stable3 convention used on release-branch jobs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#5316]
/area jobs
/assign @krzyzacy 

I mentioned this during a standup? sig-testing meeting? at one point.  It sounds like there is a desire to migrate from hardcoding release numbers in job names to suffixes that correspond to "latest release - N"

Can we document this convention, and track where we're at in its migration? It's a little confusing at the moment when attempting to jump from testgrid to triage.  eg: ci-kubernetes-e2e-gci-gce-ingress-release-1-6 vs. ci-kubernetes-e2e-gci-gce-ingress-stable1

I've added to v1.9 milestone assuming our intent is to wrap up this quarter.  Please punt into 2018-goals if that's not the case.

**Comment by krzyzacy** [comment]
yeah I still haven't finish the migration for release1.6 and 1.7 yet, will surely do this week or next before 1.9

/assign

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/pull/5560 :K

**Comment by BenTheElder** [comment]
for now we are calling 1.9 `ci/beta` and 1.8 `ci/stable1`, 1.7 `ci/stable2`... we can bikeshed more later

**Comment by krzyzacy** [comment]
I'll add a doc shortly

**Comment by spiffxp** [comment]
OK, I see the docs.  I also see some `release-1-6`, `release-1-7` and `release-1-8` jobs in `jobs/config.json`.  Keep this issue open as an umbrella for where we're at in finishing migration to the new bikeshed color?

**Comment by krzyzacy** [comment]
@spiffxp yeah there are certain jobs
- checks out release-1.8 branch explicitly, which we cannot use an alias there
- test against cvm which we want to get rid of them soon, rather than roll them into next release
the release-foo is for k8s tarball only. We'll further clean them up & better document them.

**Comment by spiffxp** [comment]
Is this the sort of thing we can actually clean up or are we just going to age out the release jobs? I notice we have no `release-1-9` jobs

**Comment by krzyzacy** [comment]
I'd hope this will be more clear when we retire 1.6 stuff from Jenkins. I'll see how much extra bikeshed we need to put in then, and probably add a few scripts to help this.

**Comment by krzyzacy** [comment]
okay, I've spent ~1h to bikeshed testgrid config for https://github.com/kubernetes/test-infra/pull/6538 - there are still a few jobs, like unit, verify, build, federation... not using the same pattern which makes advance those release dashboards super painful. Will give it another stab during 1.10 cycle.

**Comment by spiffxp** [comment]
ping on where we're at with this, since it came up during today's sig-testing meeting

**Comment by krzyzacy** [comment]
release-branch jobs are mostly following the convention now, plan to finalize it after https://github.com/kubernetes/test-infra/pull/6834 gets in

**Comment by krzyzacy** [comment]
also, given bazel configs are just different across each branches, I'd still name them after each branch, to reduce confusions cc @BenTheElder

**Comment by spiffxp** [comment]
/remove-lifecycle stale
@cjwagner (1.12 test infra) and @amwat @prwitt @ravisantoshgudimetla (1.12 test infra shadows) can you figure out what remains to be untangled and doc or untangle it?

**Comment by krzyzacy** [comment]
opened https://github.com/kubernetes/sig-release/pull/255 which covers this issue
