### ISSUE TITLE
needs-ok-to-test is not removed on reopening of a PR

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5318]
https://github.com/openshift/origin/pull/17148

The cherrypick robot wasn't a member of openshift at the time the PR was opened. Once it joined and the PR was reopened, tests started running but the label was not removed.

/kind bug
/area prow

cc @stevekuznetsov

**Comment by xiangpengzhao** [comment]
I send PR #5330.
Idea:
- remove "needs-ok-to-test" label if existing when a PR is opened and found trusted
- if a member's PR is labeled "needs-ok-to-test" accidentally (e.g., a maintainer adds it manually by mistake), just remove it.
