### ISSUE TITLE
bazel build failes locally

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#5331]
Checkout the HEAD code of test-infra, bazel build fails. It works on my former branch.

```
cloud@ubuntu:~/go/src/k8s.io/test-infra$ bazel build //...
ERROR: /home/cloud/go/src/k8s.io/test-infra/vendor/gopkg.in/yaml.v2/BUILD:24:1: no such package 'vendor/gopkg.in/check.v1': BUILD file not found on package path and referenced by '//vendor/gopkg.in/yaml.v2:go_default_xtest'.
ERROR: Analysis of target '//vendor/gopkg.in/yaml.v2:go_default_xtest' failed; build aborted: no such package 'vendor/gopkg.in/check.v1': BUILD file not found on package path.
INFO: Elapsed time: 4.287s
```

**Comment by BenTheElder** [comment]
hmm I think you need `bazel build //... -//vendor...` now [after the switch to `dep`](https://github.com/kubernetes/test-infra/pull/5301) which includes these tests. (that's what the presubmits are doing). I'm not sure what the best option for making this easier is at the moment.

/cc @ixdy

**Comment by xiangpengzhao** [comment]
@BenTheElder it throws another error:
```
cloud@ubuntu:~/go/src/k8s.io/test-infra$ bazel build //... -//vendor...
.................
ERROR: Invalid options syntax: -//vendor...
```

**Comment by BenTheElder** [comment]
@xiangpengzhao my bad, the correct way is `bazel build -- //... -//vendor...`, bazel allows you to place args after the build target list so you have to put `--` do disambiguate between flags and negative targets. :confused:

**Comment by xiangpengzhao** [comment]
```
cloud@ubuntu:~/go/src/k8s.io/test-infra$ bazel build -- //... -//vendor...
ERROR: no such package 'vendor...': BUILD file not found on package path.
INFO: Elapsed time: 0.423s
```

But I see the vendor package in code root dir. Sorry I'm not familiar with bazel rules...

**Comment by BenTheElder** [comment]
facepalm x2, don't bazel late at night :joy:: `bazel build -- //... -//vendor/...`
vendor... != vendor/...

**Comment by xiangpengzhao** [comment]
@BenTheElder No worries :)

The new command works! Awesome! Thanks!

BTW, should I run the new command every time when I want to build? The command is a bit hard to remember...

**Comment by BenTheElder** [comment]
@xiangpengzhao just for now, we should make it so that `bazel build //...` just works.

**Comment by xiangpengzhao** [comment]
@BenTheElder thanks!

**Comment by BenTheElder** [comment]
I can verify that `bazel build //...` and `bazel test //...` should work fine now without excluding vendor.
