### ISSUE TITLE
Suggestions around merging PRs w/o running tests

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5334]
We have a process in place today that ensures our web console ([separate project](https://github.com/openshift/origin-web-console) from the [main repo](https://github.com/openshift/origin)) is vendored back to the main repo. The main issue with the state of the world is that this process creates a bump commit with all changes since last time we vendored and pushes that commit directly to master. This is obviously problematic as it breaks the merge queue so we want to rearchitect the flow and make the bump commit go through the merge queue as a normal PR.

__The problem with making this a PR:__
PRs can get plagued by flakes. We need the bump PR to merge as quick as possible. I think we don't care about running tests at all (similarly to how we don't care about running tests for documentation fixes). In case a bump stays more than long enough in the queue, the next bump PR needs to invalidate the previous one. The logic to handle this sounds etoohairy.

My question:
How can we handle this with tide in place? I was thinking of a way to mark prowjobs as blessed that would force plank/jenkins-operator to clear all statuses and skip tests but it needs more thought. Any other ideas?

@stevekuznetsov @cjwagner @spxtr @rmmh @fejta @BenTheElder 

fyi @jwforres @spadgett

/area prow
/kind feature

**Comment by stevekuznetsov** [comment]
The similar situation upstream in `k/k` is the `docs-only-retest-not-required` -- I know I've helped to babysit a PR from a new contributor that found something wrong in a README and needed to have it explained why we were running tests on their PR for two days before it merged. We could think about approaching this as human approval + matching a set of file regex constraints to not require status contexts before being placed in the tide pool.

**Comment by cjwagner** [comment]
> The main issue with the state of the world is that this process creates a bump commit with all changes since last time we vendored and pushes that commit directly to master. This is obviously problematic as it breaks the merge queue

Why does this break the merge queue? It will restart testing on PRs because there will be a new master HEAD, but the merge queue should continue to merge properly? Pushing directly to master seems like the right way to merge a change that needs to be merged quickly and doesn't require testing.

I'd prefer to avoid adding special logic to make Tide ignore status contexts on some PRs if that is possible. I think its better if statuses that aren't required don't report to github or are marked as skipped.

**Comment by kargakis** [comment]
> Why does this break the merge queue? It will restart testing on PRs because there will be a new master HEAD, but the merge queue should continue to merge properly? Pushing directly to master seems like the right way to merge a change that needs to be merged quickly and doesn't require testing.

It breaks any batch/single PR that runs at that point.

> I'd prefer to avoid adding special logic to make Tide ignore status contexts on some PRs if that is possible. I think its better if statuses that aren't required don't report to github or are marked as skipped.

FWIW, nobody proposed that (yet). I was thinking of a way to mark all contexts as green inside plank/jenkins-operator. We want to avoid testing in other cases too like documentation fixes. I don't think that it's viable to merge directly to master every time such a PR comes up.

**Comment by kargakis** [comment]
> FWIW, nobody proposed that (yet)

Seems like @stevekuznetsov did. Nice.

**Comment by stevekuznetsov** [comment]
@cjwagner "breaking" a batch here just means the mungers will refuse to merge it since `master` `HEAD` changed. Not sure if that was clear before.

**Comment by cjwagner** [comment]
How often is a vendor bump done? If this is infrequent it doesn't seem like a big deal if 2 presubmit jobs have to restart.

**Comment by stevekuznetsov** [comment]
We would love to do them every time the other repo gets a commit, which used to mean ten, fifteen times a day. We're doing it now once a day in the night, but it will still mean the queue wastes a lot of time on it and when flakes are otherwise making it inefficient, it feels bad to see a batch job that could have merged five PRs fail due to this.

**Comment by BenTheElder** [comment]
FWIW I'm not a fan of anything merging into kubernetes at least without presubmits, how do we guarantee the change doesn't break the repo? I think we can *partially* solve this by making batching better in tide. 

Manual merging without the submit queue can be done by ...manually merging...?

**Comment by stevekuznetsov** [comment]
Yeah there's some disconnect with the "stigma" of pushing the button and anecdotally people use the `retest-not-required` label to get away from that. Agreed that efficient batching would effectively solve this as well as the real pain point is the time taken to merge.

**Comment by chrislovecnm** [comment]
Having this testing functionality is a big need.  When, for instance, spelling errors are being tested in non-go files, we should not be running e2e.

Is anyone working on this?

**Comment by BenTheElder** [comment]
> Having this testing functionality is a big need. When, for instance, spelling errors are being tested in non-go files, we should not be running e2e.

That exists with `run_if_changed`, you can set something like `run_if_changed: *.go` to regex only go files on individual jobs.

**Comment by kargakis** [comment]
> That exists with run_if_changed, you can set something like run_if_changed: *.go to regex only go files on individual jobs.

Setting all jobs to run as run_if_changed does not sound ideal but it can work. It would be nice to offer a per repo run_if_changed option (and potentially a run_if_not_changed option too since golang regexps do not support negative lookaheads).

**Comment by kargakis** [comment]
@stevekuznetsov has a proposal that would satisfy this if implemented

/assign stevekuznetsov

**Comment by fejta** [comment]
I would rather we fix batched merges to run all powers of 2 in parallel. So if there are 10 open PRs it runs a 1, 2, 4, and 8 PR batch. Merging the largest set that passes

**Comment by fejta** [comment]
Reprioritizing the queue has caused as much harm as good on mungegithub. I suspect overall project velocity would be higher if we eliminated all this functionality.

Whenever a higher priority PR gets approved we wind up throwing away the pending test results a) causing delays while we wait for these thrown away results to complete and b) not merging the batch run that would have merged 5 PRs (ideally all PRs) instead of 1.

A secondary problem is that once we start ordering or classifying mergeable PRs this naturally causes people to spend time and energy attempting to make the ordering/classification more correct.

**Comment by kargakis** [comment]
I think we can fix this w/o adding the concept of priority in tide.

**Comment by kargakis** [comment]
@stevekuznetsov is the `override` plugin enough for covering our use case?

**Comment by stevekuznetsov** [comment]
Not really, we'd have to `/override` every context and hope it gets chosen into the next batch, and that the batch would merge, if not we'd need to re-`/override` after the failed batch results get posted to the PR, etc.

**Comment by stevekuznetsov** [comment]
This is more like #7899
