### ISSUE TITLE
Monitor token usage in prow

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5338]
We need to expose prometheus metrics for token usage in hook and tide (assuming hook and plank are using the same token, and tide uses a separate token).

/area prow

**Comment by spxtr** [comment]
Currently I'm looking on [velodrome](http://velodrome.k8s.io/dashboard/db/monitoring?orgId=1).

**Comment by kargakis** [comment]
That metric is related to the munger and not any of the prow tokens (and we could potentially have 4 different tokens). Also, velodrome looks great but we are not using it today.

**Comment by stevekuznetsov** [comment]
Talking about this Slack right now... 
/cc @cjwagner @spxtr @BenTheElder 

/remove-lifecycle rotten

**Comment by kargakis** [comment]
xref: https://github.com/kubernetes/test-infra/issues/6720

**Comment by BenTheElder** [comment]
@cjwagner aren't we doing this now by monitoring against the github cache?
also @cjwagner @kargakis have you looked at adopting the github cache? I think it has been working quite well for us.

**Comment by BenTheElder** [comment]
http://velodrome.k8s.io/dashboard/db/github-cache?refresh=1m&orgId=1

**Comment by cjwagner** [comment]
@cjwagner aren't we doing this now by monitoring against the github cache?

Currently we only measure token usage for the entire cluster. The cache could be instrumented to measure requests per component, but it would be nice to break down token usage by sub component and API call which would require client instrumentation.

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
I'm taking no action on this in ~2 years as a sign that it's no longer that important

https://monitoring.prow.k8s.io/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1 breaks down by path, but still not by client
