### ISSUE TITLE
We should have the ability to run test suites not part of the pr-* set on PRs before merge

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/test-infra#5339]
While it's generally sufficient to run the `pr-` suites on PRs, sometimes we have bugs in the non-PR e2e tests (e.g. those marked `[slow]` or `[serial]`).  When we go to fix those bugs, it'd be useful to be able to request a run of the offending tests.

First, this helps ensure that the bug fix will fix the issue in the environment the tests run in.  It helps catch mistakes on the part of the PR author, and provides documentation that a given PR did, in fact, fix the issue (even if we trust that the submitter ran the e2e tests locally, it's still nice to have that confirmation, and helps in cases when the e2e tests are more difficult to run in a local setup).

Example: kubernetes/kubernetes#54586

**Comment by DirectXMan12** [comment]
cc @krzyzacy

**Comment by spiffxp** [comment]
Yeah I was trying to prompt this discussion in #sig-testing before an issue showed up :)

https://kubernetes.slack.com/archives/C09QZ4DQB/p1509572518000508

My takeaway is that you can maybe run the tests locally in such a way that we can still see the results of them in gubernator.  It still feels manual to me, and in the example case you linked, I'm OK taking your word for it.  But I agree it seems like we could do better here.

**Comment by BenTheElder** [comment]
Hmm, I think one of the problems here is preventing abuse. Many of the CI jobs are CI jobs because they are much more expensive than the presubmits and should only run against code that is merged. Only allowing manual triggering of presubmits from GitHub was an intentional choice because of this  AFAIK.

Maybe we can have a user whitelist (https://github.com/kubernetes/test-infra/issues/5051) ?

/area prow
/cc @cjwagner

**Comment by shyamjvs** [comment]
Earlier issues I filed for:
- allowing job to run only against PR before merging and not for every PR opened (https://github.com/kubernetes/test-infra/issues/4445)
- allowing only a restricted group of users to run some presubmit job (https://github.com/kubernetes/test-infra/issues/5051)
