### ISSUE TITLE
Want to use prow to add/remove a milestone to issues or PRs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#5344]
I'm the CI Signal Lead for release-1.9, and I'm a member of [kubernetes-milestone-maintainers](https://github.com/orgs/kubernetes/teams/kubernetes-milestone-maintainers/members) but not [kubernetes-maintainers](https://github.com/orgs/kubernetes/teams/kubernetes-maintainers/members).  This means I can `/status approved-for-milestone` but I can't actually add the milestone in the first place.  Is this something we could add to prow?  Maybe a new plugin, or maybe update milestonestatus?

@cjwagner @marun

**Comment by cjwagner** [comment]
How about giving `kubernetes-milestone-maintainers` permission to add/remove milestones? That seems reasonable to me based on the name of the team :smile: 
Maybe permissions are not granular enough?

**Comment by spiffxp** [comment]
AFAIK your choices are: read, write, admin.  For the entire repo.

<insert rant about GitHub ACL granularity>

**Comment by cjwagner** [comment]
/shrug
Sound like an addition to the milestonestatus plugin then like you suggested. A new `/milestone x.x` command that is usable by the same team that `/status` is usable by.

**Comment by spiffxp** [comment]
Discussed at sig-testing standup, I'm going to get by with kubernetes-pm github team membership for now

**Comment by dankohn** [comment]
@marun I am available to work on this starting Monday, 1/8. Could you please let me know if you have resolved it or have some partial work I could start from.

**Comment by spiffxp** [comment]
@dankohn any update on this?

**Comment by m1093782566** [comment]
@spiffxp 

Milestone maintainer is still unable to set milestone via `/milestone` command, please check: #7096

Can we re-open this issue for tracking?
