### ISSUE TITLE
Test-grid dashboard should have a grouping for tests belonging to a single release

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#535]
The test-grid at https://k8s-testgrid.appspot.com currently performs grouping based on whether it is gke, gce, etc
It would help keep track of release tests if we could have categorization based on the version (v1.3 tests, v1.4 tests and so on) as well.

Best case would possibly be allowing filtering by regular expression.

**Comment by krzyzacy** [comment]
I'm working on it, and I will allow user to modify regex to collect the tabs, so stay on tune :)

**Comment by spxtr** [comment]
It would also be super-useful to have something like an "overview" tab for each branch showing the Overall result from each job.

**Comment by krzyzacy** [comment]
The ultimate goal will be something like Nemesis

**Comment by foxish** [comment]
Also would be useful to group all jobs under the submit-queue, for build-cop.

**Comment by ixdy** [comment]
You can already get a listing of SQ jobs on the prow dashboard at http://prow.k8s.io/.

**Comment by krzyzacy** [comment]
From 1.4 we are creating version specific tabs, probably will add some search functionality later. I'll create a SQ blocking dashboard.
