### ISSUE TITLE
prow bugs

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5353]
After deploying Prow to the latest components I had to roll back each of them due to some tcp dial errors with jenkins-operator and http://tide/

Prow component deloyments are now at:
```
deck:0.54
hook:0.175
horologium:0.10
jenkins-operator:0.40
plank:0.52
sinker:0.21
splice:0.28
tide:0.8
tot:0.5
```
(I "only" rolled back deck, hook, horologium, jenkins-operator, and plank, but for completeness this is the current state of the Prow cluster)

Unfortunately I don't have a more detailed bug report on this ATM, as I noticed tests backing up and dove into rolling back to stop the bleeding. I'll follow up later.

**Comment by kargakis** [comment]
It would be helpful to post logs.

**Comment by kargakis** [comment]
FWIW, I just updated our prow cluster to https://github.com/openshift/test-infra/commit/a2b953e19f017b96a9f96484b9002d8d0a9250bb w/o any issue.

**Comment by kargakis** [comment]
You also need a service for the jenkins-operator because it exposes logs that get consumed by deck now.

https://github.com/kubernetes/test-infra/blob/master/prow/cluster/jenkins_service.yaml

**Comment by BenTheElder** [comment]
Yeah I think it's just a config issue. Apologies for not getting useful logs up here, I was focused on getting jobs scheduled again once I realized they weren't. I want to take another look at upgrading soon.

**Comment by kargakis** [comment]
Seems like both the jenkins-operator and tide are updated - is there anything else you have stumbled upon?

**Comment by BenTheElder** [comment]
We've been discussing some issues in #testing-ops on slack, pretty much the
whole prow cluster should be up to date now and it looks like the sync
loops have hung all within the same minute more than once. There isn't much
to see in the logs, they're syncing regularly and then they aren't without
error.
It can be "fixed" by killing the hung pos  and letting them e redeployed.
Still looking into that one.

**Comment by BenTheElder** [comment]
closing in favor of https://github.com/kubernetes/test-infra/issues/5400 for current issues. this one also includes just missing deploying the new services (aka our makefile doesn't have an accurate dependency graph...)

**Comment by BenTheElder** [comment]
closing in favor of https://github.com/kubernetes/test-infra/issues/5400 for current issues. this one also includes just missing deploying the new services (aka our makefile doesn't have an accurate dependency graph...)

**Comment by BenTheElder** [comment]
closing in favor of https://github.com/kubernetes/test-infra/issues/5400 for current issues. this one also includes just missing deploying the new services (aka our makefile doesn't have an accurate dependency graph...)
