### ISSUE TITLE
Bazel rules for static binaries don't compile on OSX

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/test-infra#5354]
The default rules for most of our binaries include static flags:

```
go_binary(
    name = "kubeadm",
    gc_linkopts = [
        "-linkmode",
        "external",
        "-extldflags",
        "-static",
    ],
    importpath = "k8s.io/kubernetes/cmd/kubeadm",
    library = ":go_default_library",
    x_defs = version_x_defs(),
)
```

which fail to compile on OSX because it's impossible to do static compilation with the OS GCC.  It might be friendlier to make those conditional, or when Bazel adds static features to make the static determination globally.

```
... -prefixes -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -headerpad_max_install_names -lc++ -no-canonical-prefixes -Wl,-rpath,$ORIGIN/../../ -static' 'bazel-out/darwin_x86_64-fastbuild/bin/cmd/kube-proxy/~race~kube-proxy~/k8s.io/kubernetes/cmd/kube-proxy.a')

Use --sandbox_debug to see verbose messages from the sandbox.
/private/var/tmp/_bazel_clayton/5d0ba53608021b87fa9bd88a3bdcf100/external/go_sdk/pkg/tool/darwin_amd64/link: running external/local_config_cc/cc_wrapper.sh failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

2017/11/03 22:34:53 error running linker: exit status 1
```

**Comment by BenTheElder** [comment]
I think we should be able to fix this particular problem with a `select()` over the target cpu and only enable static on `"k8"` (Linux/amd64).

**Comment by ixdy** [comment]
I think what we actually want to do is bump `rules_go` to 0.7.0 and use the new [pure](https://github.com/bazelbuild/rules_go/blob/0.7.0/go/modes.rst#pure) compilation mode, which properly matches what we do in the non-bazel build. (Right now in the bazel rules we are statically linking cgo deps, which is different.)

**Comment by ixdy** [comment]
/close

The pure go binaries all cross compile now using the `--platforms` flag, assuming bazel 0.10+.
