### ISSUE TITLE
Testgrid sometimes missing k/k commit ID.

### ISSUE THREAD

**Issue by porridge** [kubernetes/test-infra#5357]
Filing as a separate bug, as this was [mentioned earlier](https://github.com/kubernetes/test-infra/issues/5073#issuecomment-337870814) but received little attention.

For some jobs, most of the commit IDs are missing:

![xa1gjlvypaj](https://user-images.githubusercontent.com/489420/32437370-65c92996-c2e7-11e7-96d6-a3c119df0b10.png)

@BenTheElder [said that `started/finished.json` seem to be missing data](https://github.com/kubernetes/test-infra/issues/5073#issuecomment-338080693).

Example jobs:
- with ID: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/53
- without: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/56

For debugging regressions, having the commit ID consistently displayed would save us some effort.

**Comment by shyamjvs** [comment]
cc @krzyzacy @BenTheElder Could one of you PTAL into this? This is making it quite difficult to extract commit for such runs.

**Comment by shyamjvs** [comment]
Bumping priority as the release is coming closer - and this is quite important for debugging CI jobs.

**Comment by shyamjvs** [comment]
@BenTheElder assigning this to you - feel free to redirect as apt :)

**Comment by krzyzacy** [comment]
Note that if the cluster is teared down, we will be missing commit sha. Is scalability test tearing down cluster somewhat differently?

**Comment by shyamjvs** [comment]
Nope... Nothing that I know of. Also the commit is present sometimes.

**Comment by krzyzacy** [comment]
@shyamjvs seems your log-exporter does not takes in the generated metadata.json? The write call from https://github.com/kubernetes/test-infra/blob/bcf1a6a2bb42de99ada6a80626a0e01e36d9ceb1/kubetest/main.go#L328-L331 seems not take into effect anymore.

**Comment by shyamjvs** [comment]
Are you sure? Because we do have the commit for some runs. Also the metadata.json file I assume is written to some local directory in the job container which is then uploaded to GCS in bootstrap.py. This is independent of logexporter which separately makes node logs upload directly to GCS. It shouldn't affect these files.

**Comment by shyamjvs** [comment]
OTOH I do see a correlation b/w jobs with logexporter enabled and missing commit IDs.

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/sig-testing-canaries#scalability-canary is a simpler example, which uses logexporter, has metadata.json in artifacts, but does not show commit sha in testgrid. Looking into it now.

**Comment by krzyzacy** [comment]
I suspect https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py#L419-L427 might not be able to find the metadata.json, I'll add some logs to verify.

**Comment by BenTheElder** [comment]
Thanks @krzyzacy. At the bazel conference today / tomorrow so I don't think I can get to this until Wednesday.

**Comment by krzyzacy** [comment]
@BenTheElder 😂 I found day1 talks is 😒 so I'm hiding in the corner and 👨‍🚒

**Comment by krzyzacy** [comment]
@porridge @shyamjvs  in the meantime you can still manually get the k8s commit version from metadata.json, in case you need it for regress.

**Comment by shyamjvs** [comment]
Yup.. Been doing that.

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/sig-testing-canaries#scalability-canary the latest run shows k8s commit sha, the following runs should all have k8s sha now, I'll close this.

**Comment by shyamjvs** [comment]
Thanks a lot for fixing. Will check if it's fine now.
