### ISSUE TITLE
k8s.io/test-infra/prow/config unit test is slow

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5360]
Takes about half a minute to complete.
```
ok  	k8s.io/test-infra/prow/config	29.482s	coverage: 67.9% of statements
```
Haven't looked closely but we may be able to squeeze some time out of it.

/area prow

**Comment by spxtr** [comment]
Yes, it's loading and parsing config.yaml many times. It's easy to speed up, just add a testmain that loads it once.

**Comment by kargakis** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/5634
