### ISSUE TITLE
Jenkins live logs aren't working.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#5368]
```
Log not found: Get http://jenkins-operator/job/pull-kubernetes-kubemark-e2e-gce/60768/consoleText: dial tcp: lookup jenkins-operator on 10.111.240.10:53: no such host
```
cc @BenTheElder @rmmh @kargakis 
/area prow
/kind bug

**Comment by rmmh** [comment]
The service was missing for some reason. I redeployed it (kubectl apply -f cluster/jenkins_service.yaml), but now it won't connect.

**Comment by rmmh** [comment]
We're running an old jenkins-operator (0.40) instead of the latest after the latest deployment was broken.

**Comment by kargakis** [comment]
They do work now
