### ISSUE TITLE
Proposal: prevent merge commits via prow plugin

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#5376]
There's been a number of discussions around merge commits, and why they are bad. One of the more recent ones on kubernetes-dev@ is [here](https://groups.google.com/d/msg/kubernetes-dev/KmeNarMIyRU/5Z00p2WWCQAJ).

Right now it's up to the reviewers and approvers to notice that there are merge commits, and withhold lgtm/approve until the author squashes or rebases them away.

https://github.com/kubernetes/kubernetes/pull/51176 was opened to add a verify script to k/k to prevent them there, but I think this could be more easily done in a prow plugin (which would also let other repos easily turn it on).

For example, the GitHub API allows you to [list all the commits for a PR](https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request), and count the number of "parents" of the commit. If it's >1, then it's a merge commit.

Example:
```
curl -s -H "Authorization: token ${GITHUB_API_TOKEN}" https://api.github.com/repos/kubernetes/community/pulls/1355/commits | jq '.[] | {sha: .sha, commit_message: .commit.message, number_of_parents: .parents | length}'
{
  "sha": "e4e04b4f25eb767c1b4e8c316c2a2c8ab2e30b3b",
  "commit_message": "sepell error",
  "number_of_parents": 1
}
{
  "sha": "574094e67d7c23beb23edfca014f0fca3e482979",
  "commit_message": "Merge remote-tracking branch 'community/master'",
  "number_of_parents": 2
}
{
  "sha": "964f90233cbb4550bc9ed00f62157b342cd7e58f",
  "commit_message": "spell error",
  "number_of_parents": 1
}
{
  "sha": "3d45caa2c516ecbb6fc7e689620bc35c4017ca72",
  "commit_message": "spell error",
  "number_of_parents": 1
}
```

If we set this up with a `do-not-merge/*` class label, then we could prevent auto-merging a PR containing a merge commit. The only issue would be if there is a legitimate case for a merge commit in a PR -- if this was the case, a branch manager or build cop would need to manually merge it as the SQ would refuse.

cc: @kubernetes/sig-contributor-experience-proposals @kubernetes/sig-testing-proposals @lavalamp @sttts @ixdy 
/area prow

**Comment by sttts** [comment]
Prow is the right place to do this IMO 👍 

As side note: we don't fall over merges anymore while publishing, but we loose the commit history before the last merge on a feature branches.

**Comment by fejta** [comment]
/remove-lifecycle stale

IMO it would be good to either a) allow merge commits or b) make prow enforce their absence.

**Comment by lavalamp** [comment]
A very compelling reason to allow merge commits is for feature branches. E.g. https://github.com/kubernetes/kubernetes/pull/63558

**Comment by lavalamp** [comment]
@BenTheElder does the bot know the difference between master and a feature branch? Also, I probably shouldn't lose the history when I re-integrate this back into master.

I agree it's ordinarily a mistake for contributors to have a bunch of merge commits in a PR.

**Comment by BenTheElder** [comment]
@lavalamp we could always bypass the requirements for snowflake PRs anyhow, but this could definitely be configured by branch.

**Comment by BenTheElder** [comment]
@cblecker do we still need this? If so we should probably clean it up for help-wanted

**Comment by cblecker** [comment]
Yeah, I think this a good candidate for `help wanted`.

/remove-lifecycle stale
/help

**Comment by alisondy** [comment]
can I pick this up please?

**Comment by BenTheElder** [comment]
Sure :-)

**Comment by cblecker** [comment]
Please do!

/remove-help

**Comment by Huang-Wei** [comment]
/remove-lifecycle stale

I do hope this can be implemented. Those "merged" commits (due to lack of proper rebasing) generated by authors looks pretty ugly.

**Comment by alisondy** [comment]
if someone wants to take my remaining commits, and finish them off, feel free to otherwise , it's a whenever i can thing :\

**Comment by Huang-Wei** [comment]
If it's not that urgent, I'd like to volunteer on this.

/assign

(feel free to unassign me if it's critical and there is some experienced guy would like to take it)

**Comment by Huang-Wei** [comment]
cc/ @cblecker @BenTheElder PR #11937 is ready to be reviewed. PTAL. Thanks!
