### ISSUE TITLE
Reduce 'trigger' plugin token usage.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#5382]
Prow's trigger plugin uses more tokens than necessary to validate that a PR is trusted if the PR is a authored by an org member (the common case).
The plugin should be refactored to avoid listing issue comments in this case even though it means we may skip cleaning up a stale comment if an author **becomes** an org member while the PR is open. (That is a rare case and failing to remove a stale comment is not very important).
/assign

**Comment by stevekuznetsov** [comment]
One (hilarious, but functional) approach to this taken by our pre-Prow solution was to do the list with a probability (1/100, 1/10, whatever) so that you _usually_ do the cleanup but don't blast tokens.
