### ISSUE TITLE
testgrid summary "in the past week" is hardcoded, dashboard duration is not

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#5385]
All of the Summary tabs for all dashboards talk about tests/jobs "in the past week", but the dashboard itself may have more or less than a week's worth of results.  

This stands out most on https://k8s-testgrid.appspot.com/presubmits-kubernetes, where we use `days_of_results: 1`, but we've also got the `default_test_group.days_of_results: 14`

Is the summary text incorrect, or am I just being misled?

/area testgrid

**Comment by michelle192837** [comment]
You're correct, the summary text is super-hardcoded for one week, both text-wise and calculation-wise (in that we'll look back seven days and take as much data as we have for that). No configuration value affects this number.

**Comment by spiffxp** [comment]
/milestone v1.13
I'm fine if we address this by documenting, I suspect flexible range is tougher

**Comment by spiffxp** [comment]
/milestone 2019-goals

It sure would be nice if we could do this in v1.14, but I'm going to defer to @michelle192837 to add back in to v1.14 milestone

**Comment by michelle192837** [comment]
I am planning to fix this this month

**Comment by michelle192837** [comment]
/assign @maryyliu 

This should be fixed now. Thanks Mary! ^^
