### ISSUE TITLE
prow log link can give pod errors

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#5391]
@BenTheElder wrote a podspec with a typo that caused his test pod to not start. Clicking the job logs on the triggered job gives a useless
```
failed to open log file "/var/log/pods/31e03594-c410-11e7-ace2-42010a80011d/1dbe5dd8-c410-11e7-8c24-0a580a6c0118-0_0.log": open /var/log/pods/31e03594-c410-11e7-ace2-42010a80011d/1dbe5dd8-c410-11e7-8c24-0a580a6c0118-0_0.log: no such file or directory
```
message. He had to "kubectl describe pod" to see the event. We can do better by showing the actual pod events in this case.

/area prow

**Comment by kargakis** [comment]
What was the event about? Was the pod crashlooping?

**Comment by BenTheElder** [comment]
The pod wasn't able to start because one of the volumes was typo-ed.
