### ISSUE TITLE
prow stops syncing

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#5400]
Seems like all the PRs cannot be triggered to build now...

/cc @cjwagner @krzyzacy

**Comment by xiangpengzhao** [comment]
Take https://github.com/kubernetes/kubernetes/pull/55318 for example:

```
pull-kubernetes-e2e-kops-aws — Waiting for status to be reported
pull-kubernetes-bazel-test — Skipped
```

**Comment by munnerz** [comment]
Glad I'm not the only one - looks like no builds are running at all at the moment based on the Prow dashboard. I've had this PR waiting for a few hours: https://github.com/kubernetes/kubernetes/pull/54660

I guess this is a pretty urgent issue?

**Comment by xiangpengzhao** [comment]
Yeah I guess so. I want give this issue the below labels:
/priority critical-urgent
/priority failing-test

**Comment by kargakis** [comment]
@BenTheElder

**Comment by jdumars** [comment]
CC: @enisoc FYI as 1.9 release manager

**Comment by spiffxp** [comment]
/assign @fejta 
listed as testinfra oncall at go.k8s.io/oncall

**Comment by cjwagner** [comment]
A bunch of pods froze at the same time around 12:50AM last night. I just restarted them so things should be working again for now. Ill look into a more permanent workaround/fix for this problem today.

**Comment by BenTheElder** [comment]
xref https://github.com/kubernetes/test-infra/issues/5353#issuecomment-342904695

**Comment by BenTheElder** [comment]
xref https://github.com/kubernetes/test-infra/issues/5353#issuecomment-342904695

**Comment by kargakis** [comment]
Any info about why the pods froze?
