### ISSUE TITLE
External prow plugin that informs about conflicting PRs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5401]
This is an idea a colleague of mine had. In his own words
> [the bot] could show a message when 2 or more PRs modify the same files; probably it could be helpful to know that someone else doing something that could affect you. Here is the plugin for Danger that does it -- https://github.com/justice3120/danger-conflict_checker#danger-conflict_checker but it's possible to implement the similar approach without Danger

We would have to cache all PRs, otherwise token usage would skyrocket

@kubernetes/sig-contributor-experience-feature-requests 
/area prow

**Comment by cblecker** [comment]
love this idea in concept, although I have no clue how this would effectively work in k/k with ~900 open PRs, or in PRs that touch common things like BUILD files.

**Comment by spxtr** [comment]
That's an interesting idea, but I'm not sure how useful it'd actually be. Say I get some message on my PR saying "PR #bla conflicts with this in somepkg/zz_generated.welp.go". That doesn't really help me, since we just need to wait until one merges and then regenerate. There's nothing I can do when I first get the message.

**Comment by kargakis** [comment]
@php-coder if you want to make a case

**Comment by spxtr** [comment]
Actually if it is possible to do this with gubernator then that would be really neat. I would like it if my PR dashboard showed that my PR conflicts with some other PR. I think that would be rather hard to accomplish, though. cc @rmmh

**Comment by cblecker** [comment]
I can see this being useful not just for rebases, but for:
- Two PRs that are fixing the same issue/bug, in the same way (prevent duplication of effort)
- Two PRs that are fixing the same issue/bug, in different ways (and spur discussion)

**Comment by xiangpengzhao** [comment]
Totally agree with @cblecker on the use cases. For these cases, what I exactly want to see is sth like the git blame page shows, from where I can see which PR(s) touch the same code block with my PR. I can also jump to the PR to check for more details.

**Comment by php-coder** [comment]
> Say I get some message on my PR saying "PR #bla conflicts with this in somepkg/zz_generated.welp.go". That doesn't really help me, since we just need to wait until one merges and then regenerate. There's nothing I can do when I first get the message.

@spxtr this case could be easily solved by ignoring auto-generated files.

**Comment by kargakis** [comment]
This seems like it would be useful in cases like https://github.com/kubernetes/test-infra/pull/5445 where two PRs are changing the same lines but once one of them merges, the second is still mergeable because the conflicting diffs were the same.

**Comment by cblecker** [comment]
/remove-lifecycle stale
still a good idea

**Comment by kargakis** [comment]
FYI, I just stumbled across https://github.com/bitcoin/bitcoin/pull/13557#issuecomment-404986537
