### ISSUE TITLE
Kubemark presubmit times out with no logs on GCS and leaked resources

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#5407]
I've been noticing this happening quite frequently of late for kubemark-500 presubmit.
The e2e test is timing out, but what is undesirable is the run is shown as 'Running' forever and the GCS logs also don't exist.
Further the cluster is leaked and I need to clean up the project manually each time (as it's a PR job which runs with a different cluster name each time).

E.g - https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/54550/pull-kubernetes-kubemark-e2e-gce-big/

This needs to be fixed asap, as folks are running the kubemark-big presubmit from time to time.

/cc @krzyzacy @porridge @kubernetes/sig-scalability-misc

**Comment by krzyzacy** [comment]
/shrug
please bump https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/bootstrap-pull-json.yaml#L44

**Comment by krzyzacy** [comment]
meh... we don't have a `jenkins-timeout` for pr jenkins...
I'll just bump the timeout

**Comment by shyamjvs** [comment]
Not sure I understand how that's going to help. Is it sth like the job timeout (which I think is 140m) is greater than the pull-jenkins timeout (which seems 130m) - so basically there's no time left to grab the logs and cleanup the cluster?

**Comment by krzyzacy** [comment]
@shyamjvs what happens ideally:
kubetest timed out at 140m
after that:
kubetest has 15m buffer time to finish xml generation, tear down cluster, and other things that are not terminated immediately
bootstrap has 20m buffer time to upload logs/artifacts
Jenkins has (till 200m) to abort any unresponding process

In current case Jenkins bailed out running processes at 130m, where no further action can be scheduled

**Comment by krzyzacy** [comment]
plus this job is opted out from janitor, so we cannot automatically wipe the project

**Comment by shyamjvs** [comment]
Actually, we don't need that high timeout for our kubemark-500 jobs as it is currently. Sent out the above PR to reduce it.
