### ISSUE TITLE
[release-1.6] flag provided but not defined: -cluster-ip-range

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#5416]
Pull tests on the `release-1.6` branch have started to fail with this error:

```
util.go:155: Running: ./hack/ginkgo-e2e.sh --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true --cluster-ip-range=10.64.0.0/14
[...]
flag provided but not defined: -cluster-ip-range
Usage of /workspace/kubernetes/platforms/linux/amd64/e2e.test:
[...]
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55343/pull-kubernetes-e2e-gce/20/

**Comment by krzyzacy** [comment]
/shrug
/assign @shyamjvs 
and in 1.7 as well

I'll see if I can cherrypick back

**Comment by krzyzacy** [comment]
/assign
creating cherrypicks for https://github.com/kubernetes/kubernetes/pull/48271

**Comment by krzyzacy** [comment]
cherrypicks are in
/close
