### ISSUE TITLE
RFC: validate commit messages to avoid automatic closing of issues via Github

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5417]
Forked from https://github.com/kubernetes/features/issues/427#issuecomment-343012256

cc @spxtr

**Comment by spxtr** [comment]
> It's a GitHub ~~bug~~ feature. I asked them to change the behavior to stop closing when people update their forks, but there response was "if you don't want it to happen then stop saying 'fixes #soandso' in your commit messages."

> It's possible. It only causes a problem if you say "fixes someorg/repo#number" rather than "fixes #number", because in the latter case it tries to close the issue in your fork where it doesn't exist.

**Comment by BenTheElder** [comment]
Mentioning fixes `#xyz` in a PR body / follow up comment is useful within a repo though :-(
The broken behavior is forks :/
