### ISSUE TITLE
Kubetest crashes when prompting for downloading binaries

### ISSUE THREAD

**Issue by porridge** [kubernetes/test-infra#5426]
```
porridge@kielonek:~/projects/go/src/k8s.io/kubernetes$ kubetest --down -v
2017/11/09 14:01:33 util.go:154: Running: ./hack/e2e-internal/e2e-down.sh
Project: k8s-scale-testing
Network Project: k8s-scale-testing
Zone: us-east1-a
Shutting down test cluster in background.
Bringing down cluster using provider: gce
!!! kubectl appears to be broken or missing
!!! Cannot find kubernetes-server-linux-amd64.tar.gz
!!! Cannot find kubernetes-salt.tar.gz
!!! Cannot find kubernetes-manifests.tar.gz
Required binaries appear to be missing. Do you wish to download them? [Y/n]
2017/11/09 14:01:36 util.go:156: Step './hack/e2e-internal/e2e-down.sh' finished in 2.56047732s
2017/11/09 14:01:36 main.go:267: Something went wrong: encountered 1 errors: [error during ./hack/e2e-internal/e2e-down.sh: exit status 1]
porridge@kielonek:~/projects/go/src/k8s.io/kubernetes$ 
```

It does not give a chance to answer to the prompt. Running without `-v` is also a bit too shrouded in mystery. Perhaps `-v` should be the default?

```
porridge@kielonek:~/projects/go/src/k8s.io/kubernetes$ kubetest --down
2017/11/09 14:00:49 util.go:154: Running: ./hack/e2e-internal/e2e-down.sh
2017/11/09 14:01:10 util.go:156: Step './hack/e2e-internal/e2e-down.sh' finished in 21.076588848s
2017/11/09 14:01:10 main.go:267: Something went wrong: encountered 1 errors: [error during ./hack/e2e-internal/e2e-down.sh: exit status 1]
porridge@kielonek:~/projects/go/src/k8s.io/kubernetes$ 
```

**Comment by krzyzacy** [comment]
@porridge kubetest shells out to `./hack/e2e-internal/e2e-down.sh` though.. seems you don't have kubectl (?)

**Comment by porridge** [comment]
@krzyzacy It's possible that I didn't have the kubectl binary built at that moment, although I had one on my $PATH, installed from a release.

However I'm not sure I understand what kubectl has to do with this...  Are you saying that the fact that `./hack/e2e-internal/e2e-down.sh` prints `Required binaries appear to be missing. Do you wish to download them? [Y/n]` and then *does not wait* for input from terminal but instead exits 1 - is somehow related to lack of kubectl?

**Comment by BenTheElder** [comment]
> Are you saying that the fact that ./hack/e2e-internal/e2e-down.sh prints Required binaries appear to be missing. Do you wish to download them? [Y/n] and then does not wait for input from terminal but instead exits 1 - is somehow related to lack of kubectl?

That error and prompts are from [k8s.io/kubernetes/cluster/common.sh](https://github.com/kubernetes/kubernetes/blob/7a28aaffa706e87c5a15b56c0f33b08982e4b552/cluster/common.sh#L1342) which is part of calling the e2e-down script. 

You're not meant to be interacting with this script in this case, kubetest is, and this script requires kubectl. 

It's not waiting because it doesn't have any input pipe to wait on. We *could* plumb through stdin but I don't think kubetest intends to support usage without kubectl installed...

**Comment by BenTheElder** [comment]
I think we should consider outputting more verbose failures by default when a script gives a bad exit code, but `-v` as a whole should be a seperate, more generally verbose option.

I also think we probably shouldn't do much special when kubectl isn't detectable by the standard kubernetes scripts. I think kubetest is really just meant to add some light automation around managing a test cluster and running e2e tests against it. We should add a note about kubectl in the docs though, the README doesn't mention anything about the expected environment currently.

**Comment by krzyzacy** [comment]
we probably should flip `-v` on to default true..

**Comment by BenTheElder** [comment]
Should we close this now?

**Comment by krzyzacy** [comment]
yeah, I don't think we'll change the behavior
