### ISSUE TITLE
Add planter to CI

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5428]
We should run a CI periodic job with `planter` against k/k master at least to ensure everything still works. This should be feasible to do on Prow now that docker-in-docker works fine, as soon as I migrate the bootstrap image to provide docker-in-docker support I want to do this.

area/jobs
FYI @ixdy @krzyzacy

**Comment by BenTheElder** [comment]
I'm holding on doing this until #5436 is in, then I will add a low frequency job to verify that planter can do `make bazel-build && make bazel-test` against kubernetes/kubernetes master at the very least.

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
PRing this week.

**Comment by BenTheElder** [comment]
@ixdy do we know if people are still using it? if so I'll add a low frequency periodic this week.

**Comment by BenTheElder** [comment]
(otherwise I'm just closing this :-))

**Comment by ixdy** [comment]
I still use it periodically. I'm not sure if anyone else does. I'm not sure that we need CI for it, really.
