### ISSUE TITLE
some of the image maintainers are stale

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5431]
https://github.com/kubernetes/test-infra/blob/a436c8a85e660c95b384904ceac5ce8d1fdc9395/images/bazelbuild/Dockerfile#L17

FYI @spxtr

Probably should be ixdy or myself now (or a different email addr)

/cc @ixdy
/area images

**Comment by ixdy** [comment]
we should just remove it. [`MAINTAINER` is deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated).

**Comment by ixdy** [comment]
oh, we're not using `MAINTAINER`.

I still feel like this field is pretty useless, since it can get out of date easily. maybe it points to sig-testing or this repo or something instead of a specific person?

**Comment by BenTheElder** [comment]
Yeah, there is also a broader issue that some of our images still use `MAINTAINER` instead of the label.

I think it's still idiomatic to have _some_ maintainer in the dockerfiles, maybe it could be `kubernetes-sig-testing@googlegroups.com` :stuck_out_tongue: 

Right now it's been useful as "this is the person who is most familiar with the image, cc them when something is broken" though, which wouldn't be as useful if it just pointed to this repo or sig-testing.

**Comment by BenTheElder** [comment]
/assign
@krzyzacy and I are planning to clean up our image layering in Q1, we should fix the maintainer labels then.

**Comment by BenTheElder** [comment]
xref: #5434

**Comment by krzyzacy** [comment]
which ones are left?

**Comment by spiffxp** [comment]
/milestone v1.14

I vote we either kill the use of this, or we use kubernetes-sig-testing@googlegroups.com
