### ISSUE TITLE
clean up test images

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5434]
/cc @krzyzacy 
Let's document / plan our image layering a bit so we can move bootstrap into the image and sort out our test image layering a bit as we move off of Jenkins.

Tentatively we want to have:
- `bootstrap`: contains bootstrap & very common dependencies, docker-in-docker, as well as the runner
- go, bazel: add dependencies that tend to change per release / are independently upgraded
- kubetest, etc.: add binaries / artifacts from test-infra used for e2es etc.

/area images

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/5431
xref: https://github.com/kubernetes/test-infra/issues/5708

**Comment by BenTheElder** [comment]
This is in our 2018 plans

**Comment by BenTheElder** [comment]
We've done some work on the images, mostly migrating towards bootstrap, kubekins-e2e layered on top. Things needing just our runner and optionally DIND use bootstrap, things needing build tools like bazel, go, etc. use kubekins-e2e.

**Comment by spiffxp** [comment]
Do we still care about this?

**Comment by BenTheElder** [comment]
we did some cleanup, further cleanup will need to happen as part of the podutils migration and dealing with verify which can come later
