### ISSUE TITLE
Improve Conformance test coverage via data-driven e2e test

### ISSUE THREAD

**Issue by jagosan** [kubernetes/test-infra#5446]
Conformance test coverage is currently insufficient to provide a strong guarantee that a Kubernetes cluster exposes endpoints an end user would reasonably expect.  @erictune described an approach from another effort (auth) which seems reasonable to apply. 

Goal: Ensure that conforming Kubernetes implementations have all the expected Endpoints.  Cheaply increase coverage of the Conformance test without adding flaky or complex tests.

Mechanism: 
Write a new e2e test which is table driven, and takes a list of operations, and objects YAMLs to create/update/delete, and tries each one, using dynamic client for simplicity.

Example of approach here: 
https://github.com/kubernetes/kubernetes/blob/master/test/integration/auth/auth_test.go#L292

Possible alternative is to store the table in a go-bindata module that is compiled from text files.

**Comment by erictune** [comment]
Sounds about right.  

Just to restate the goal: the goal here is not to test the correct behavior of the controllers behind the resources resources.  It is just to ensure that  conformant Kubernetes implementations at least support all expected CRUD operations on all expected resources.

**Comment by spiffxp** [comment]
@timothysc may have some thoughts, and @kubernetes/sig-architecture-proposals owns conformance

I gather that an API server + etcd would be enough to pass these tests, ie: a cluster with no controller-manager, scheduler, nodes (kubelet+kube-proxy).  This seems like a good first step, but an end user might reasonably expect these endpoints to actually effect behavior.

**Comment by timothysc** [comment]
This needs to be more specific, broken down, traceable, and requires buy-in from @kubernetes/sig-architecture-proposals

**Comment by jbeda** [comment]
Yes! Please bring this by SIG-arch with a plan we can review and get lots of eyes on. Obviously this will impact a lot of people so we should make sure it is discussed and communicated well.

**Comment by bgrant0607** [comment]
I would like to see the test be driven via API discovery, at least optionally. A subset of results could be considered part of the conformance suite. One way to do that would be to make the set of tests configurable, or to specify the conformance profile each API is part of.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/assign
/priority important-longterm
I view this as much lower priority than conformance tests that exercise pod behavior.  There was consensus on this point at the most recent cncf-conformance-wg call.  Our CI gathers audit logs so we can use [cncf/apisnoop](https://github.com/cncf/apisnoop) to keep track of API coverage, and we can revisit whether this is still necessary the next time the bot tries aging this out.

**Comment by bgrant0607** [comment]
/remove-lifecycle rotten

I think we'd need to figure out what the main purpose(s) of such a test would be. Possibilities:
* apiserver behaviors, which are still evolving (e.g., server-side apply)
* enablement and authorization of required APIs
* lack of access to APIs that could be inaccessible for security reasons
etc.

**Comment by dims** [comment]
long-term-issue (note to self)
