### ISSUE TITLE
Switch kubetest to use logrus

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#5453]
xref #5452 

/area kubetest

**Comment by mariantalla** [comment]
@krzyzacy Is this still something you think is valuable to implement? If so, could we have a discussion of what you had in mind?

cc @hoegaarden

**Comment by krzyzacy** [comment]
/remove-lifecycle rotten
/help

so we already have glog in kubetest (unfortunately we only use that in dind), we can convert all logging message with that

**Comment by BenTheElder** [comment]
Maybe. Or logrus. Going to figure out if I can make those play nice.

**Comment by krzyzacy** [comment]
yeah I'd say let's use logrus and ditch glog...

**Comment by BenTheElder** [comment]
I'll rip out `dind/` soon and we can start switching in logrus, I think nothing else has direct or indirect dependencies on glog so far.

Though unless we use a very boring formatter, this will significantly change the output of go run hack/e2e.go, so we should perhaps consider that.
