### ISSUE TITLE
*-gke-* and *-gci-gke* jobs both test COS images

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/test-infra#5480]
I assume non-gci jobs should test CVM, but gubernator shows that the node OS image is COS. 
E.g.,
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-release-1-6/1854
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-release-1-6/1867

In addition, none of the 1.6 gke jobs above have node logs properly archived (artifacts do not have any logs)

/cc @abgworrall @yguo0905 
/cc @krzyzacy

**Comment by yguo0905** [comment]
Looks like this was set incorrectly in https://github.com/kubernetes/test-infra/commit/cf7a139562f180235f2db683a52342e9b94f488d#diff-5539d275f091e62154f51653bbe4fba0R7111.

@krzyzacy, do we want to instead auto-generate those jobs so that this kind of error won't happen anymore?

**Comment by krzyzacy** [comment]
I remember @zmerlynn switched all of them to gci?

**Comment by yguo0905** [comment]
It should be `--gcp-node-image=container_vm` for this job.

**Comment by krzyzacy** [comment]
@yguo0905 the current plan is to retire config.json and move job definition to prow/config.yaml, I'm not 100% sure about auto generate.

I'll patch up the configs for now

**Comment by yguo0905** [comment]
> @yguo0905 the current plan is to retire config.json and move job definition to prow/config.yaml, I'm not 100% sure about auto genera

I feel like no matter the job definitions live, they should be auto-generated.

**Comment by yujuhong** [comment]
> In addition, none of the 1.6 gke jobs above have node logs properly archived (artifacts do not have any logs)

Any idea about why the logs are missing in the artifacts? :-)

**Comment by krzyzacy** [comment]
probably some PR need to be cherry-picked back

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/kubernetes/pull/52361 is already merged to 1.6, so maybe something else
/shrug

**Comment by yujuhong** [comment]
The 1.6 "GCE" jobs are fine... http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-release-1-6/1520/
@krzyzacy should this also be cherry-picked to 1.6?: https://github.com/kubernetes/kubernetes/pull/52668

**Comment by yujuhong** [comment]
> @krzyzacy should this also be cherry-picked to 1.6?: kubernetes/kubernetes#52668

FYI, I submitted a PR: https://github.com/kubernetes/kubernetes/pull/55640

**Comment by yujuhong** [comment]
We are still testing COS in all *-gke-* jobs. I suspect that this is actually controlled by GKE apiserver's test image map now, and I'm not sure how to change it.
Not a serious issue since CVM is deprecated already (even though we still attempt to maintain test coverage in 1.6 and 1.7).

**Comment by krzyzacy** [comment]
@yujuhong I can flip 1.6 to cvm but we'll stop support 1.6 tests after 1.9. In gke latest-1.7 won't support cvm anymore. If you want I can flip 1.7 and pin version to v1.7.5.

**Comment by yujuhong** [comment]
There is no need to flip now. Just pointing out that we basically double the test jobs for now reason :-) 
Let's keep it the same until after 1.9, then we can remove/shut down some jobs.

**Comment by krzyzacy** [comment]
yeah, we'll definitely do more bikesheds along the way
