### ISSUE TITLE
issue checker is confused by PRs referencing other PRs

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#5483]
See https://github.com/kubernetes/kubernetes/pull/55533.

Note the "approved" comment has decided that the associated issue is 55127, which is not even an issue but a PR this one is rebased on top of. (note, I just edited to add the "Ref:" link, it wasn't there when the bot made that comment.)

Seems like whatever does that should at least check that the thing is an issue and not a PR.

This likely means that our release note generating stuff is going to be confused or generate wrong output, but I don't know how widespread this is.

**Comment by BenTheElder** [comment]
As far as GitHub is concerned PRs are still issues which is likely the cause of this bug.

/cc @cjwagner

**Comment by Bradamant3** [comment]
So many questions, here's just a start (I'm heading up the release note effort for 1.9, so bear with me):
- the example (#55533) looks as though it's a test? We don't and shouldn't provide release notes for tests, including e2e tests. If the script for generating the release notes is iterating over PRs for tests, then we should fix the script.
- we should also not be generating release notes at all for PRs that don't have release note content (which should take care of the issue the reporter noted).

**Comment by lavalamp** [comment]
Yeah, I'm sure that is the cause of the bug.

The test is part of a bigger feature which has a release note. The PR either needs to be associated with that issue, or say `NONE` for its release note to make the bot happy.

**Comment by BenTheElder** [comment]
> the example (#55533) looks as though it's a test? We don't and shouldn't provide release notes for tests, including e2e tests. If the script for generating the release notes is iterating over PRs for tests, then we should fix the script.

The reviewer should make sure PRs that shouldn't have release notes don't and that PRs that should, do. The GitHub bot just makes sure you've actually set these values as far as I know.

> we should also not be generating release notes at all for PRs that don't have release note content (which should take care of the issue the reporter noted).

`/release-note none` / putting `NONE` in the PR body should cover this (?), I don't think we are generating release note for PRs without release note content. If we are that definitely seems like a bug.

**Comment by enisoc** [comment]
I haven't verified this, but my impression has always been that the "Associated issue" is not used for anything except deciding whether to require `/approve no-issue`.

I'm not aware of any automation that follows "associated issue" links at this time. For release notes in particular, we don't look at non-PR issues at all. We list PRs with the `release-note` label, and get the text directly from the PR. We then link to the PR (not an issue) in the generated release notes.

**Comment by xiangpengzhao** [comment]
>We list PRs with the release-note label, and get the text directly from the PR. 

If we are going to adopt the new release note tool (https://github.com/kubernetes/release/pull/434, https://github.com/kubernetes/release/pull/435), there might be a corner case here. PR title may also be used as release note. See: https://github.com/kubernetes/release/pull/434#discussion_r145884721

As for the `associated issue`, the [Hierarchical release note feature functions](https://github.com/kubernetes/release/pull/435/files#diff-49d09fcbe05bad1f7da45fb5828f1c84R44) will try to extract sig/area info from PRs' associated issues.

**Comment by xiangpengzhao** [comment]
BTW, are we going to adopt the new release note tool(s) for 1.9, or still use the script one?
Seems like v1.9.0-alpha.2 changelog was updated by @dashpole (https://github.com/kubernetes/kubernetes/commit/e0cac2a2f0359f8908076ad92fcd33fb3bdfcb13), @dashpole which release tool were you using?

**Comment by dashpole** [comment]
I just used anago.

**Comment by xiangpengzhao** [comment]
>...but my impression has always been that the "Associated issue" is not used for anything except deciding whether to require /approve no-issue.

@enisoc the original discussion is here: [Each PR should have an associated issue ](https://github.com/kubernetes/test-infra/issues/2868)

**Comment by xiangpengzhao** [comment]
>I just used anago.

@dashpole then it will invoke the script version release notes tool: https://github.com/kubernetes/release/blob/master/anago#L425

**Comment by enisoc** [comment]
Thanks for the info @xiangpengzhao. So to summarize, our current tooling should not be impaired by this problem, but the new hierarchical release note function might get confused by it?

**Comment by xiangpengzhao** [comment]
>but the new hierarchical release note function might get confused by it?

I guess so. cc @roycaihw

**Comment by roycaihw** [comment]
@xiangpengzhao @enisoc The new hierarchical release note function assumes PR authors following the [PR template](https://github.com/kubernetes/kubernetes/blob/95b4312899b109a9f1c666687827541fac756910/.github/PULL_REQUEST_TEMPLATE.md) and looks for specific ["fixes #\<issue number\>"](https://github.com/kubernetes/release/pull/435/files#diff-49d09fcbe05bad1f7da45fb5828f1c84R92) in PR body. 

The tool doesn't use the `Associated issue`. In this case, the tool will see the PR as having no issue associated.

**Comment by cjwagner** [comment]
That tool will have the same problem the approval-handler has now if I say `fixes #5` and 5 is a PR.

**Comment by roycaihw** [comment]
> That tool will have the same problem the approval-handler has now if I say fixes #5 and 5 is a PR.

@cjwagner Ah I see. Yes you're right. I will add a check to that tool to make sure the "issue" is not a PR.

**Comment by lavalamp** [comment]
Just looking for "fixes" is not enough. It should also look for "ref" or
"references"; sometimes it takes many PRs to "fix" an issue, in fact that
is the only case where it is useful to have an associated issue: when you
want to be able to group multiple PRs.

**Comment by roycaihw** [comment]
@lavalamp Totally agree. One concern is that I see many PR referring other PRs. We can filter out the associated PRs and keep only the issues, but maybe we should provide some guideline in [PR template](https://raw.githubusercontent.com/kubernetes/kubernetes/95b4312899b109a9f1c666687827541fac756910/.github/PULL_REQUEST_TEMPLATE.md) about how to use "ref"?

**Comment by BenTheElder** [comment]
this is still a bit of a pain point. https://github.com/kubernetes/kubernetes/pull/57126#issuecomment-351283215
/cc @mindprince see above: https://github.com/kubernetes/test-infra/issues/5483#issuecomment-344335315

**Comment by spiffxp** [comment]
/close
@lavalamp The associated issue requirement for PR's was disabled in January ([thread](https://groups.google.com/d/msg/kubernetes-sig-contribex/sBqQuJBbMnA/psJ63pQFAAAJ)) so we're not inclined to work on this unless there's an urgent need.  I'll admit, I haven't kept up to date on how release notes are being generated these days, but it's not dependent on this.
