### ISSUE TITLE
Expose pod CPU/Memory usage in deck

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#5486]
/area prow

**Comment by spxtr** [comment]
It's possible, although we should probably avoid just cramming more info into the main UI.

**Comment by BenTheElder** [comment]
FYI @kargakis @cjwagner 
I've been discussing with @krzyzacy how it would be useful to basically expose `kubectl top pod` next to the running jobs so we can get a better idea how much resources they should allocate.
We also probably should add a graph somewhere and another for monitoring the pod states.

**Comment by BenTheElder** [comment]
> It's possible, although we should probably avoid just cramming more info into the main UI.

We can just put two new columns like:
```
CPU | MEM
2.1 | 6.5        
```
And show the units on hover or something. That shouldn't really cram things much

**Comment by spxtr** [comment]
Right, but then we might want to add number of restarts, node name, and so on. Plus, what we really want for memory and CPU usage is a graph, much like the k8s dashboard exposes.

...

On that note, can we just expose the k8s dashboard to the public? Is there a way to turn off edit power as well as secret viewing?

**Comment by BenTheElder** [comment]
> Right, but then we might want to add number of restarts, node name, and so on. Plus, what we really want for memory and CPU usage is a graph, much like the k8s dashboard exposes.

Maybe, or maybe we can do that in velodrome because. But some indication that the job is actually running is _actually_ running is useful, and we particularly need to know what their usage looks like and easily associate it _with the job name_ whereas the k8s dashboard does all of this with some UUID pod name...

> On that note, can we just expose the k8s dashboard to the public? Is there a way to turn off edit power as well as secret viewing?

I don't think so. This dashboard is also not terribly helpful for prow jobs since it surfaces everything as UUIDs.

**Comment by BenTheElder** [comment]
>  Plus, what we really want for memory and CPU usage is a graph, much like the k8s dashboard exposes.

Also if that's the route we decide to go, I definitely don't want to clutter the deck UI, but I think deck probably makes sense as the right component to collect and expose information like this. We just might need to only show it via a different URL / Interface. Deck pretty much *is* the Prow dashboard, and is actually aware of your job, to the standard k8s tooling our jobs are just gibberish one-off pods.

**Comment by kargakis** [comment]
> I've been discussing with @krzyzacy how it would be useful to basically expose kubectl top pod next to the running jobs so we can get a better idea how much resources they should allocate.

It sounds like you want to expose these as metrics rather than have them in deck. Also, I would try to avoid adding that info in public view.

> On that note, can we just expose the k8s dashboard to the public? Is there a way to turn off edit power as well as secret viewing?

I am not sure about the dashboard but it should be possible to restrict access in the cluster with RBAC.

**Comment by BenTheElder** [comment]
> It sounds like you want to expose these as metrics rather than have them in deck. Also, I would try to avoid adding that info in public view.

Why not have it in public view?

Also discussed this more with @spxtr offline tonight, a deck endpoint serving this data would be a suitable start, the UI can come later and potentially be seperate.

**Comment by kargakis** [comment]
> Why not have it in public view?

Info that gives away cluster information like how much CPU/memory is utilized at a given point in time are usually put behind authenticated endpoints.

**Comment by BenTheElder** [comment]
So are pod logs. Neither seem particularly private for something like Prow
though...

**Comment by kargakis** [comment]
A separate endpoint sounds fine.

**Comment by BenTheElder** [comment]
/shrug
This will be more relevant after we fix the caching paralellism / start using bigger nodes. @qhuynh96 any thoughts on this one?

**Comment by BenTheElder** [comment]
/shrug
maybe we will revisit this someday, this could still be useful. I think not in the main job view though..
