### ISSUE TITLE
Fix diff-job-config-patch.sh on revert branches.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#551]
Right now we get two travis results for reverts, one of which says this:

```
$ ./jenkins/diff-job-config-patch.sh
Saving output in /tmp/JJB-P53W7
Cloning into '/workspace'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
fatal: The remote end hung up unexpectedly
The command "./jenkins/diff-job-config-patch.sh" exited with 128.
```

It's confusing. The reason this happens is that GitHub creates the revert branch in the main repo, so travis tests both the PR and the branch. In the latter, I guess it doesn't fetch master.

**Comment by fejta** [comment]
Jeff will you look into this?
