### ISSUE TITLE
Allow node e2e test to use scripts in test-infra

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#5520]
The node e2e tests can use the cloud-init configurations in the main repo, like

https://github.com/kubernetes/test-infra/blob/57b57514ae85e59f23429a5910027e387f161145/jobs/e2e_node/benchmark-config.yaml#L7

It would be better to have the node e2e test to use configurations and scripts in test-infra, so that cherry picks like https://github.com/kubernetes/kubernetes/pull/55755 https://github.com/kubernetes/kubernetes/pull/55754 https://github.com/kubernetes/kubernetes/pull/55753 can be avoided.

This may involve changes in both the main repo and test-infra, but I created the issue here.

/cc @krzyzacy

**Comment by krzyzacy** [comment]
@yguo0905 I think you can use abs path in metadata to work around this
