### ISSUE TITLE
How to judge the e2e test Success in case of some test failed by chance

### ISSUE THREAD

**Issue by fisherxu** [kubernetes/test-infra#5524]
In my environment when I run e2e test, it will has some test-cases failed because of time out by chance. I config that as long as any one test-case failed, the CI failed.
But I find that  e2e-test in kubernetes/kubernetes alse has time out failed, and still SUCCESS, I want to know how to judge it, by some label?

![image](https://user-images.githubusercontent.com/28776356/32821366-ecac9aba-ca0d-11e7-8656-69edf841e9fd.png)

**Comment by krzyzacy** [comment]
some jobs have `GINKGO_TOLERATE_FLAKES=y` configured, like https://github.com/kubernetes/test-infra/blob/master/jobs/env/pull-kubernetes-e2e.env#L2, if that what you are asking.

**Comment by fisherxu** [comment]
> some jobs have GINKGO_TOLERATE_FLAKES=y configured

If set GINKGO_TOLERATE_FLAKES=y, the failed case will rerun, if any of the attempts succeed, the suite will not be failed. But any failures will still be recorded. It means that the case failed in above  finally success with rerun, but still record  as failed in the result?

**Comment by fisherxu** [comment]
GINKGO_TOLERATE_FLAKES works with FLAKE_ATTEMPTS?

FLAKE_ATTEMPTS=1
if [[ "${GINKGO_TOLERATE_FLAKES}" == "y" ]]; then
  FLAKE_ATTEMPTS=2
fi
.......
"${ginkgo}" "${ginkgo_args[@]:+${ginkgo_args[@]}}" "${e2e_test}" -- \
  "${auth_config[@]:+${auth_config[@]}}" \
  --ginkgo.flakeAttempts="${FLAKE_ATTEMPTS}" \

**Comment by krzyzacy** [comment]
well, seems `GINKGO_TOLERATE_FLAKES` hard-coded `FLAKE_ATTEMPTS` to 2, set `FLAKE_ATTEMPTS` locally would not have any effect from the snippet

**Comment by fisherxu** [comment]
Thanks @krzyzacy , now I set FLAKE_ATTEMPTS to 2 and the by chance failed test-cases wil rerun and finnally result SUCCESS :)

**Comment by krzyzacy** [comment]
sgtm, I'll close the issue.
