### ISSUE TITLE
Code analysis -> approvals needed

### ISSUE THREAD

**Issue by thockin** [kubernetes/test-infra#5536]
I wonder what the right place to put this would be.

I want to do some amount of static analysis of code as it comes through, and do something.  For example, any PR that adds or changes an `init()` function under vendor/, I want to flag for extra review.

What piece of the pipeline would be the right place for that?

@grodrigues3

**Comment by spxtr** [comment]
It's not too much trouble to write a prow plugin that does this sort of thing.
/area prow

**Comment by BenTheElder** [comment]
Prow is definitely the right place.

Right now Prow actually supports specifying `run_if_changed: '^vendor/*\.go'` as a job trigger*, though it sounds like that might not be enough.

/kind feature
/cc @cjwagner @kargakis 

\* actual usage: `pull-kubernetes-cross` sets: `run_if_changed: '^(build\/|hack\/lib\/)|(Makefile)|(.*_(windows|linux|osx|unsupported)(_test)?\.go)$'` and only runs against PRs that modify a matching path.

**Comment by cjwagner** [comment]
If this is to be implemented as a Prow plugin, the `blockade` plugin might be a good starting place.

**Comment by kargakis** [comment]
> For example, any PR that adds or changes an init() function under vendor/, I want to flag for extra review.

Sounds like a new prow plugin to me.

**Comment by thockin** [comment]
Is the expectation to write new plugins for every sort of analysis (this
being just one obvious one) or one plugin that loads rules and a rules file
that we can feed it?

On Fri, Nov 17, 2017 at 9:45 AM, Michalis Kargakis <notifications@github.com

**Comment by BenTheElder** [comment]
> Is the expectation to write new plugins for every sort of analysis (this
being just one obvious one) or one plugin that loads rules and a rules file
that we can feed it?

Currently each type of analysis is a plugin with rules configured in [prow/plugins.yaml](https://github.com/kubernetes/test-infra/blob/97e2da3395a759072561c3e7910db8355cc59c3e/prow/plugins.yaml#L21) EG `lint` (adds golint comments to PRs triggered by `/lint`) and `blockade` (adds a label to block merging PRs that touch certain paths).

We can implement a plugin with rules defining what to flag and who to involve configured in `plugins.yaml` similar to the blockade plugin pretty easily, and use common code for these types of plugins.

I would ask though:
- How do we want this to look on GitHub? Do we apply a label and ping someone from a list of reviewers or...? @thockin @grodrigues3 

- What other sort of rules exactly you envision? @thockin

**Comment by BenTheElder** [comment]
@mtaufen has mentioned similar functionality for changes to flags before, I'm not working on this at the moment but I want to keep this open.

/remove-lifecycle rotten
