### ISSUE TITLE
Make sure bazel build in CI matches local build

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5542]
xref: https://github.com/kubernetes/test-infra/issues/5429
RPMs aren't depended on by anything and get excluded from the query but are built locally.

/area bazel
/area jobs
/assign

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/sig-release/issues/10
We might try to publish from the bazel deb/rpm builds someday when bazel has multi-platform working solidly. This will need to be fixed first.

**Comment by BenTheElder** [comment]
This will hopefully happen after https://github.com/kubernetes/test-infra/issues/6808

**Comment by BenTheElder** [comment]
There's been some progress on this, I have a new scenario that doesn't involve our own querying magic which his now used in a few places.

**Comment by Q-Lee** [comment]
dind definitely depends on debs, so that should be touched in CI soon (albeit sub-optimally).

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

hmm @ixdy something for 1.13 maybe?
