### ISSUE TITLE
Please suggest users who are allowed to add status/approved-for-milestone

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#5543]
https://github.com/kubernetes/kubernetes/pull/52863#issuecomment-345027791 shows the bot asking me to get a "SIG maintainer" to add `status/approved-for-milestone`.  Unlike when I'm asked for an approver, it offers me no hints about who or how to find that person.  Can we add that?

**Comment by marun** [comment]
Being able to suggest someone to apply the label suggests adding a per-sig github group to point to.  The [current maintainer group](https://github.com/orgs/kubernetes/teams/kubernetes-milestone-maintainers/members) includes everyone on the project that can apply the label, and will not provide a good indication of who should be providing oversight for approval of a given issue/pr (should be limited to maintainers from labeled sigs).

cc: @kubernetes/sig-contributor-experience-feature-requests

**Comment by mml** [comment]
/remove-lifecycle stale

@kubernetes/sig-testing-feature-requests

**Comment by BenTheElder** [comment]
@kubernetes/sig-contributor-experience-feature-requests 
we'd need something to reference here

**Comment by spiffxp** [comment]
/close
The release team decided to shut the bot off (ref: https://github.com/kubernetes/sig-release/issues/243), and is revisiting its use of the status labels (ref: https://github.com/kubernetes/sig-release/pull/239#issuecomment-412697985)
