### ISSUE TITLE
When hack/verify-foo fails draw the user's attention to the fix

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#5550]
I'm not sure if this belongs in the logs we keep in GCS or in the github UI, but see https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52863/pull-kubernetes-verify/62997/ where verify-bazel is failing with a useless bunch of extra output.  What the user, especially a noob, really needs to know is that they didn't run update-bazel and they need to.

**Comment by stevekuznetsov** [comment]
Hopefully the recent jUnit work from @cblecker and friends has helped here.
/close
