### ISSUE TITLE
merge-bot accepts a merged PR as an "associated issue"

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#5553]
E.g. https://github.com/kubernetes/kubernetes/pull/55871#issuecomment-344895500

Also, any reason we can't make that a hyperlink?

**Comment by BenTheElder** [comment]
> Also, any reason we can't make that a hyperlink?

What do you mean?

Also this sounds like a dupe of https://github.com/kubernetes/test-infra/issues/5483

**Comment by mml** [comment]
> What do you mean?

The bot says "Associated issue: 51526", but 51526 is not linkified.

**Comment by mml** [comment]
But yes, the other part is a dup of #5483.

**Comment by BenTheElder** [comment]
> The bot says "Associated issue: 51526", but 51526 is not linkified.

Ah, that is probably an easy fix @cjwagner

**Comment by cjwagner** [comment]
Yeah thats a 1 character fix. 😄 
I'll make a PR.
