### ISSUE TITLE
setup release 1.9 branch

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5558]
The branch was cut tonight, I'm working on getting all the right configs updated and figured it would be useful to collect all the PRs involved against this issue for next time.

/area jobs
/area testgrid

**Comment by BenTheElder** [comment]
Derailed for the moment by looking into https://github.com/kubernetes/kubernetes/issues/55917, I suspect that one will not have a great simple fix, it looks like multiple PRs changing the versioning logic went in recently.

**Comment by enisoc** [comment]
ref https://github.com/kubernetes/sig-release/issues/30

**Comment by BenTheElder** [comment]
Moving the checklist here and breaking up the PR, we decided to do it piece-meal and put in the build job(s) first:

To setup `release-1.9`:

Testgrid:
- [x] create `sig-release-1.9-all` dashboard
- [x] create `sig-release-1.9-blocking` dashboard
- [ ] add GCS entries for all release-1.9 jobs
- [ ] add 1.9 jobs to any other appropriate dashboards

Jenkins:
- [x] add `ci-kubernetes-build-1.9`, bump stableN for build jobs
- [x] add `kubernetes-test-go-release-1.9`
- [x] add `kubernetes-verify-release-1.9`
- [x] add `kubernetes-build-1.9`
- [x] add `kubernetes-federation-build-1.9`
- [x] update `kubernetes-kubemark-5-gce-last-release` trigger job to `ci-kubernetes-build-1.9`
- [ ] take a second pass to check for any remaining jobs

Prow:
- [x] ensure presubmits will run against `release-1.9` branch the same as existing master
- [ ] add 1.9 versions of any 1.8 specific jobs already on Prow

Other TODO:
- [ ] move jobs to Prow where possible, xref #3778 
  - Need to add more resources to `prow-builds`, also https://github.com/kubernetes/test-infra/pull/5561
- [ ] make sure all jobs in Testgrid exist in Prow/Jenkins


/area jobs

**Comment by BenTheElder** [comment]
@shashidharatd @marun what's the deal with `kubernetes-federation-build-1.8` etc.?

**Comment by BenTheElder** [comment]
Complete list of *merged* PRs involved (will keep up to date):
- `Add release 1.9 build` (what it says)  https://github.com/kubernetes/test-infra/pull/5567
- `add relase-1.9 verify and test-go` (also fix dashboard grouping, but apparently not PR title spelling) https://github.com/kubernetes/test-infra/pull/5569
- `Branch bikeshed` (generate jobs) https://github.com/kubernetes/test-infra/pull/5573

**Comment by shashidharatd** [comment]
> @shashidharatd @marun what's the deal with kubernetes-federation-build-1.8 etc.?

now federation is moved to k/f repo and the ci build for head is here https://k8s-testgrid.appspot.com/sig-multicluster-federation-gce#build

To create a federation-build release against 1.9 we need to use the jobs which are running against the master branch. Also there are some specific requirements(like increased quota) for federation e2e jobs.

Definetely the federation build is a non-blocker for k8s 1.9 release. We still need to conclude the federation release timelines, whether it should be inline with k8s releases or should have independent release which works for the corresponding k8s release. We will discuss this in our SIG meeting on tuesday.

/cc @kubernetes/sig-multicluster-pr-reviews

**Comment by BenTheElder** [comment]
I think this is done minus the federation jobs.

**Comment by spiffxp** [comment]
A few nits while attempting to reconcile with diff.  In an ideal world, we'd have the some copy-pasta'ed or templated list of jobs in all of these dashboards.  Trying to understand why the differences exist.  I'm hoping there are some common explanations which we could add in comment form someplace, eg:
- was added as a release-blocker during v1.8
- can only be run against release-1.y branches
- etc.

@kubernetes/sig-gcp-test-failures The gci-{gce,gke} names in sig-release-{master,1.8} are now just {gce,gke} in sig-release-1.9-blocking, can we strip the gci- prefix from the other names?  There are both gce and gci-gce jobs in sig-release-1.7-blocking

@kubernetes/sig-testing-test-failures These jobs in sig-release-1.9-blocking have no equivalent in sig-release-{master,1.8,1.7}-blocking.  Should they be removed from release-1.9 or added to any of the others?
- bazel-build-1.9
- bazel-test-1.9

@kubernetes/sig-cluster-lifecycle-test-failures These jobs in sig-release-1.9-blocking have no equivalent in sig-release-{master,1.8}-blocking.  Should they be removed from release-1.9 or added to any of the others?
- gce-kubeadm-upgrade-1.8-1.9

@kubernetes/sig-multicluster-test-failures These jobs in sig-release-1.8-blocking have no equivalent in sig-release-{master,1.9,1.7}-blocking.  Should they be removed from release-1.8 or added to any of the others?
- federation-build-1.8
- federation-test-1.8

@kubernetes/sig-network-test-failures These jobs in sig-release-{master,1.9}-blocking have no equivalent in sig-release-{1.8,1.7}-blocking.  Should they be added to any of the others?
- gce-ingress-1.9
- gke-ingress-1.9

@kubernetes/sig-scalability-test-failures These jobs in sig-release-master-blocking have no equivalent in sig-release-{1.9,1.8,1.7}-blocking.  Should they be added to any of the others?
- gce-scale-correctness
- gce-scale-performance

(there are probably a few more but I'll stop here for now)

**Comment by krzyzacy** [comment]
For the ones I know:
- I have blown away all the 1.7-gke-'cvm' jobs
- @BenTheElder has added the bazel jobs, we'll need to add that to 1.9-blocking dash
- we don't create separate gce-scale jobs for release (they are expensive!) but we probably should have a gci-gce-100 for 1.9, I'll create it.
- I'll add a kubelet job
- Do we still want a soak job? I'll create one for sure.

**Comment by BenTheElder** [comment]
+1 to the comments on why something exists, I've at least tried to make sure all the changes we make for 1.9 show up https://github.com/kubernetes/test-infra/issues/5558#issuecomment-345392515

**Comment by yujuhong** [comment]
> @kubernetes/sig-node-test-failures These jobs in sig-release-master-blocking have no equivalent in sig-release-1.9-blocking. Should they be added to any of the others?
> 
> kubelet

Yes, we have kubelet-1.8, and kubelet 1.7 jobs.

**Comment by BenTheElder** [comment]
> Yes, we have kubelet-1.8, and kubelet 1.7 jobs.

I will add these once I am out of meetings :-)

**Comment by krzyzacy** [comment]
added kubelet ones from https://github.com/kubernetes/test-infra/pull/5649

**Comment by BenTheElder** [comment]
> @BenTheElder has added the bazel jobs, we'll need to add that to 1.9-blocking dash

These jobs block on presubmit, and are no more flaky than unit / non-bazel build. They're in the 1.9 blocking dash but we should have them in master blocking too.

**Comment by spiffxp** [comment]
> has added the bazel jobs, we'll need to add that to 1.9-blocking dash

Yeah, they're there, I guess my question to @BenTheElder is, is there any reason they're blocking 1.9 but not blocking master?

**Comment by BenTheElder** [comment]
I'm adding them to master. We have no reason to not block on these.

**Comment by BenTheElder** [comment]
Federation jobs for 1.9 have been punted to federation to sort out how they want them but "the federation build is a non-blocker for k8s 1.9 release" (since they moved out of k/k?) https://github.com/kubernetes/test-infra/issues/5558#issuecomment-345624723

**Comment by BenTheElder** [comment]
For sig questions about blocking tests in comment above (https://github.com/kubernetes/test-infra/issues/5558#issuecomment-346385580) I am asking the following sig members to respond with how they would like these issues handled :-)

- cc @enisoc @abgworrall for possible GCP job name bikeshed
- cc @luxas for kubeadm / sig-cluster-lifecycle jobs potentially missing from master and previous releases
- @shashidharatd discussed federation / sig-multicluster above though this isn't solved yet it shouldn't be a problem for now
- cc @MrHohn for sig-network jobs missing from previous releases
- not sure who to flag down for sig-auth, but the sigs have all been pinged at their test failures handle anyhow..
- cc @mindprince for sig-scheduling / GPU jobs only present in master blocking but not any of the release branches (including 1.9)

Please let us know what makes sense for these questions and I will make the necessary changes.

**Comment by mindprince** [comment]
> These jobs in sig-release-master-blocking have no equivalent in sig-release-{1.9,1.8,1.7}-blocking. Should they be added to any of the others?
gke-device-plugin-gpu-p100

Yes. Let's add them to release-1.9-blocking. When I added that job, release-1.9-blocking didn't exist, so I only added it to master-blocking.

**Comment by BenTheElder** [comment]
> Yes. Let's add them to release-1.9-blocking. When I added that job, release-1.9-blocking didn't exist, so I only added it to master-blocking.

Thanks, we'll do that :+1:

**Comment by MrHohn** [comment]
> kubernetes/sig-network-test-failures These jobs in sig-release-{master,1.9}-blocking have no equivalent in sig-release-{1.8,1.7}-blocking. Should they be added to any of the others?
>
> - gce-ingress-1.9
> - gke-ingress-1.9

@BenTheElder I think we do have equivalent jobs, just that the naming format changed?
- https://k8s-testgrid.appspot.com/sig-release-1.8-blocking#gci-gce-ingress-1.8
- https://k8s-testgrid.appspot.com/sig-release-1.8-blocking#gci-gke-ingress-1.8
- https://k8s-testgrid.appspot.com/sig-release-1.7-blocking#gci-gce-ingress-release-1.7
- https://k8s-testgrid.appspot.com/sig-release-1.7-blocking#gci-gke-ingress-release-1.7

**Comment by spiffxp** [comment]
@MrHohn you're right, that was my bad, not sure how I missed those

**Comment by BenTheElder** [comment]
Thanks @MrHohn, with all of the jobs I don't have full track of every job 🙃

**Comment by BenTheElder** [comment]
This https://github.com/kubernetes/test-infra/issues/5663 / the associated PR https://github.com/kubernetes/test-infra/pull/5664 will be relevant now that https://github.com/kubernetes/kubernetes/pull/55279 is in.

**Comment by crassirostris** [comment]
@spiffxp Audit tests will be added to the default suite in gce/gke env by https://github.com/kubernetes/kubernetes/pull/55953

**Comment by spiffxp** [comment]
@crassirostris does this mean we should remove the audit-specific job once that PR merges?

**Comment by crassirostris** [comment]
@spiffxp Yes

**Comment by BenTheElder** [comment]
There are a few unanswered questions above, but the branch has been set up and running for some time (with a few fixes since then), I think we should close this.
