### ISSUE TITLE
release dashboards have redundant jobs

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5579]
test-go and verify jobs per-release look to both be kubernetes_verify scenario running verify. we should remove the test-go job, and look for any other redundant jobs

/area jobs
/kind bug
/assign
/assign @krzyzacy

**Comment by krzyzacy** [comment]
no? the `--script` flags are different

**Comment by BenTheElder** [comment]
verify does:
`--script==./hack/jenkins/verify-dockerized.sh"`
test--go does not set that flag

They both use verify scenario which has:
```python
PARSER.add_argument(
        '--script',
        default='./hack/jenkins/test-dockerized.sh',
        help='Script in kubernetes/kubernetes that runs checks')
```

So verify is just explicitly setting the default while test--go uses the default...

**Comment by BenTheElder** [comment]
I vote we delete `test-go` jobs since the name is bad (no go testing is done, only analysis) and look for any other jobs like this.

**Comment by BenTheElder** [comment]
FYI @spiffxp @enisoc I'd actually like to remove `test-go` from all branches, AFAICT it's running the same thing as the verify job which is a better name since the ultimate test command is `make verify`

**Comment by BenTheElder** [comment]
🤦‍♂️ 

test-go is indeed different, and also broken currently.
