### ISSUE TITLE
cross should be blocking

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5584]
@cjwagner can we take another look at this?

PRs can still get through that break the cross build which is not ideal, cross building itself is not flakey and seems pretty important to being able to put out releases..

/area mungegithub
/kind bug

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/56002 for an example of why this should be blocking

**Comment by BenTheElder** [comment]
In fact it looks like the failures in the PR I found were ignored because there were already failures with the cross job 😕
I also suggested that sig-release should set up testgrid alerts for this job.

**Comment by spiffxp** [comment]
By blocking do we mean merge-blocking?  Alternatively, is there a reason we shouldn't have something like cross on sig-release-master-blocking?

@kubernetes/sig-release-test-failures since sig-release owns cross

**Comment by BenTheElder** [comment]
Yes, merge blocking

**Comment by BenTheElder** [comment]
> Alternatively, is there a reason we shouldn't have something like cross on sig-release-master-blocking?

I'm not sure if we have one off the top of my head, but we should, cross ensures that `make release` works...
We shouldn't do this alternatively though, cross is skipped on most PRs and PRs that it runs against are highly suspect. In this case there were recent failures so a PR that definitely broke it was ignored, which is not ideal..

**Comment by cjwagner** [comment]
`pull-kubernetes-cross` doesn't have a status on all k/k PRs so the context cannot be made blocking yet.
This PR should have a `Skipped` status right? kubernetes/kubernetes/pull/55811

**Comment by BenTheElder** [comment]
yeah I think this was an issue with jenkins though, if you look at a newer PR you will see skipped:
https://github.com/kubernetes/kubernetes/pull/56095

**Comment by BenTheElder** [comment]
My guess is something is wrong with the jenkins agent and statuses. I bet if we flip it to blocking now everything will be fine.
cc @kargakis

**Comment by BenTheElder** [comment]
actually tentatively it looks like it's the difference between the PR author being an org member or not.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pulls?q=is%3Aopen+is%3Apr+label%3Aneeds-ok-to-test
Everything in here is missing a contenxt for cross thus far.

**Comment by BenTheElder** [comment]
Cross broke again for the same reason but a different package :-(

**Comment by BenTheElder** [comment]
@cjwagner are we safe to try this again?

**Comment by cjwagner** [comment]
Steve and I had a discussion about the expected behavior for manually triggering a RunIfChanged job with a `/test job` or `/test all` command that you might want to take a look at: https://github.com/kubernetes/test-infra/pull/5655#discussion_r152688188
If that seems ok to you then we just need a hook bump to pick up the fix. I'll make a PR.
