### ISSUE TITLE
slackevents manual merge notifier noise

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#5603]
The slackevents plugin that warns about manual merges looks like it's mostly been firing for benign or known events.  It would be helpful if we could identify and ignore these.

I'm guessing this is related to creating the release-1.9 branch
>Warning: @dashpole manually merged https://github.com/kubernetes/kubernetes/commit/02128d6b5f9e
>Warning: @dashpole manually merged https://github.com/kubernetes/kubernetes/commit/550d1d0bf0bc
>Warning: @dashpole manually merged https://github.com/kubernetes/kubernetes/compare/release-1.9
>Warning: @dashpole manually merged https://github.com/kubernetes/kubernetes/compare/b79e3d14d180...a82460d772b9

Not sure what this is, but looks like a branch deletion and tag creation
>Warning: @enisoc manually merged https://github.com/kubernetes/kubernetes/compare/3297b54a78f8...000000000000
>Warning: @enisoc manually merged https://github.com/kubernetes/kubernetes/compare/v1.10.0-alpha.0

Not entirely sure what this is
>Warning: @david-mcmahon manually merged https://github.com/kubernetes/kubernetes/compare/e7258eecaa67...a0fb3baa71f1
>Warning: @david-mcmahon manually merged https://github.com/kubernetes/kubernetes/compare/f78896aab2f1...a0fb3baa71f1

Pretty sure this is a patch release happening
>Warning: @jpbetz manually merged https://github.com/kubernetes/kubernetes/compare/v1.8.4
>Warning: @jpbetz manually merged https://github.com/kubernetes/kubernetes/commit/5db1551cf500
>Warning: @jpbetz manually merged https://github.com/kubernetes/kubernetes/compare/9befc2b8928a...f130273be313
>Warning: @jpbetz manually merged https://github.com/kubernetes/kubernetes/compare/2cbb07a4394e...1ab3e7d40903

Another one I don't have an example of right now is when someone creates a revert through github's UI

---

The quickest and easiest fix for now might be to whitelist branch managers https://github.com/kubernetes/test-infra/blob/18e99bd24bafa3dee1257debc3755d1f84a944ff/prow/plugins.yaml#L55-L61 

WDYT?

**Comment by krzyzacy** [comment]
`Warning: @shyamjvs manually merged https://github.com/kubernetes/kubernetes/compare/db64d027efed...000000000000` this message doesn't make any sense though, and the link does not show anything :-)

**Comment by brahmaroutu** [comment]
Hmm, Is it some flavors of GitHub push events that we should skip? Logic so far is simple check on whitelist and not merged by bot.

**Comment by enisoc** [comment]
Here's another one, from running `branchff` (which we're going to start doing every business day):

https://github.com/kubernetes/kubernetes/compare/87dad50b0be0...622e0c1f0b4f

**Comment by BenTheElder** [comment]
new one: creating a revert PR using the GitHub button creates a warning.

**Comment by stevekuznetsov** [comment]
@BenTheElder that may be from the fact that the revert PR button creates a new branch on the repo?

**Comment by BenTheElder** [comment]
@stevekuznetsov perhaps, but it's not what the bot is intended to alert about IMHO and seems to fall under this.

/kind bug

**Comment by BenTheElder** [comment]
we now have a branch specific whitelist of users that should not activate alerts at least, so branch managers do not trigger notifications when they manage their branches..

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
/reopen
we keep talking about this a bunch in slack whenever these errant warning come up

**Comment by spiffxp** [comment]
>I wish we would make it say "fejta deleted the whatever branch" rather than "pushed 203948029842098....000000000000000000"

Would be a great place to start

**Comment by BenTheElder** [comment]
@cblecker tackled this already I think

**Comment by cblecker** [comment]
Yup. I think it's not deployed yet, but was fixed in https://github.com/kubernetes/test-infra/pull/10147

/remove-help

**Comment by cblecker** [comment]
<img width="639" alt="screenshot 2018-11-20 11 13 28" src="https://user-images.githubusercontent.com/1431969/48797262-8e46ae80-ecb6-11e8-8148-6b9f6b73ab6e.png">

It works!

/close
