### ISSUE TITLE
[release-1.6] DumpClusterLogs fails on GKE

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#5615]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-release-1-6/1887

```
error during bash -c 
function log_dump_custom_get_instances() {
  if [[ $1 == "master" ]]; then
    return 0
  fi

  gcloud compute instances list '--project=k8s-jkns-e2e-gci-gke-ci-flaky' '--filter=(metadata.created-by:*zones/us-central1-a/instanceGroupManagers/gke-err-e2e-default-pool-d499f1b0-grp)' '--format=get(name)'
}
export -f log_dump_custom_get_instances
# Set below vars that log-dump.sh expects in order to use scp with gcloud.
export PROJECT=k8s-jkns-e2e-gci-gke-ci-flaky
export ZONE='us-central1-a'
export KUBERNETES_PROVIDER=gke
./cluster/log-dump/log-dump.sh '/workspace/_artifacts'
: exit status 1
```

**Comment by krzyzacy** [comment]
I think there were certain PRs need to be cherry-picked back to 1.6 which @yujuhong has mentioned ? (I cannot find the original issue)

**Comment by enisoc** [comment]
It seems like the 1.6 jobs were replaced with `k8sstable3` jobs, and now they are passing?

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sstable3-default/24

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-release-1-6/1886 was passing though, maybe https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-release-1-6/1887 is a flake

**Comment by yujuhong** [comment]
> I think there were certain PRs need to be cherry-picked back to 1.6 which @yujuhong has mentioned ? (I cannot find the original issue)

Those PRs were merged quite a while a ago https://github.com/kubernetes/kubernetes/pull/55640
It was only for fixing the problem that logs were not archived, and should not cause test failures.

**Comment by enisoc** [comment]
I linked 1887 because it was the first failure, but DumpClusterLogs failed consistently after that. Anyway, since the new jobs are passing, I guess we can call this fixed.
