### ISSUE TITLE
Pain with timezone in prow cronjobs?

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#5624]
We moved 2k-node scale jobs to prow yesterday (https://github.com/kubernetes/test-infra/pull/5600).
Based on that gke-large-correctness should've been triggered on 22:00, but it instead seems to have been triggered around 14:00 (https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-large-correctness)
Similarly, gce-large-performance should've been triggered on 05:00, but it instead got triggered at 21:00 (https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-large-performance)

/assign @krzyzacy - Could you PTAL into this? This might affect our 5k-node release-blocking jobs by clashing with their runs.
/priority critical-urgent

cc @kubernetes/sig-scalability-misc @porridge

**Comment by shyamjvs** [comment]
Umbrella issue for prow migration - https://github.com/kubernetes/kubernetes/issues/49820

**Comment by krzyzacy** [comment]
what timezone were those jobs in? They are look correct in UTC, or the previous cron were in PST?

**Comment by shyamjvs** [comment]
Yeah... I guess they were in PST.

**Comment by shyamjvs** [comment]
Should be fixed by the above PR.
/close

**Comment by porridge** [comment]
Just for the record (adding a link here puts a cross-reference in the gubernator UI): jobs overlapping due to this issue caused gce-scale-cluster-master VM to be deleted mid-way through this job, causing it to fail:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/66

**Comment by krzyzacy** [comment]
yeah, the last run with the timezone change will cause an overlap. I'll keep an eye there since the gce-scale suites are still on Jenkins.
