### ISSUE TITLE
Feature request: /revert

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/test-infra#5642]
Which automatically does the right thing to revert a PR, and posts the revert PR for you.
So when I'm on my mobile phone I can still revert if I have to.

Guess it would have to only be no conflict reverts, but still potentially useful.

**Comment by spxtr** [comment]
I think GitHub already has this feature built-in, although I'm not sure who exactly can push the button.

**Comment by xiangpengzhao** [comment]
@spxtr yeah github already supports this feature, see below picture. The author of a merged PR can click the button and a new PR called `Revert "The original PR title."` with body `Reverts original PR link`.

![image](https://user-images.githubusercontent.com/15881573/33137899-1e4f3150-cfe4-11e7-8de4-c7a8d0c4f5b8.png)

**Comment by BenTheElder** [comment]
mtaufen is asking to make this possible on mobile via a command. Personally
I tend to use the desktop site from mobile, there is a button at the bottom
of the page to switch to the desktop UI.

**Comment by xiangpengzhao** [comment]
>Personally
I tend to use the desktop site from mobile, there is a button at the bottom
of the page to switch to the desktop UI.

yeah I always switch between mobile version and desktop version of GH on my mobile :)

**Comment by mtaufen** [comment]
Didn't realize GH already had this feature, closing :).
