### ISSUE TITLE
Notification emails are not sent

### ISSUE THREAD

**Issue by porridge** [kubernetes/test-infra#5645]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/66 did not trigger an email.
I did get the one about [an earlier test](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/65) though. That one was even duplicate in a way (the body was slightly different):
Message IDs:
- 001a113f2698e253e9055e388a63@google.com
- 001a113d9b5078aa40055e3926c2@google.com

**Comment by porridge** [comment]
Another failed run for which there was no notification: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/35

**Comment by porridge** [comment]
I have to admit that the usefulness of this notification service is greatly reduced by its unreliability, because it forces us to do manual history checks anyway. :-(

**Comment by BenTheElder** [comment]
IIRC testgrid only sends alerts about new failures by design (it's edge triggered).

**Comment by BenTheElder** [comment]
@michelle192837 maybe we could make this configurable?

**Comment by porridge** [comment]
@BenTheElder perhaps the subject was misleading. What I meant is that this issue happened many times (for jobs I care about, possibly many more for others), I did **not** mean "not sent for multiple failures in a row".

**Comment by BenTheElder** [comment]
Hmm not sure then, @michelle192837 can you take a look?

**Comment by porridge** [comment]
Any updates here? The notifications seem to have ceased completely.

**Comment by BenTheElder** [comment]
PING @michelle192837

**Comment by porridge** [comment]
I guess something must have happened, because I just received a handful of
failure notifications a few minutes ago.
