### ISSUE TITLE
Prow dry-run and local run improvements.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#5665]
- [ ] Ensure that all prow components have identical flags and flag semantics. Make the defaults work for running locally. (`cluster`, `build-cluster`, `config-path`, and so on).
- [ ] Allow components to hit public `deck` for testing against production data. `deck` needs to serve ProwJobs and Pods. Started in #5631 and #5644.
- [ ] Document how to run and test individual controllers locally.

/area prow

**Comment by BenTheElder** [comment]
Not sure if this is meant to be included above, but I've recently thought it would be cool to:
- [ ] allow deck to hit public deck for prowjobs, so you can test deck UI against real data

**Comment by spxtr** [comment]
It kindof can already, see [`cmd/deck/runlocal`](https://github.com/kubernetes/test-infra/blob/6468d9bbc6bfac61e59fac5c1ab0fecb36f4a668/prow/cmd/deck/runlocal)

**Comment by BenTheElder** [comment]
there's been a bit more work on runlocal, but we're not quite this good yet.
