### ISSUE TITLE
PR with `+55,245 −1,108` lines change gets size label `size/XS`

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#5667]
https://github.com/kubernetes/kubernetes/pull/56283

The PR has `+55,245 −1,108` lines change, but it was added a `size/XS` label. Maybe there is issue with size plugin?

Note: seems like it was created by mistake though.

cc @cjwagner

**Comment by php-coder** [comment]
Could it be related to some limitations in GitHub API?

**Comment by xiangpengzhao** [comment]
@php-coder maybe, I'm not sure.

**Comment by spiffxp** [comment]
/close
works as intended

The size plugin only looks at line count for files that pass a matcher from prow/genfiles, which takes the contents of the `.generated_files` in a repo's root into account, in this case https://github.com/kubernetes/kubernetes/blob/master/.generated_files which also pulls in https://github.com/kubernetes/kubernetes/blob/master/docs/.generated_docs, thus excluding all the docs changes from consideration.

**Comment by xiangpengzhao** [comment]
@spiffxp thanks for explanation!
