### ISSUE TITLE
cncf-cla:no although it was signed

### ISSUE THREAD

**Issue by llonchj** [kubernetes/test-infra#5687]
I signed the CLA as individual and submitted [this merge request](https://github.com/kubernetes/charts/pull/2859).

Label `cncf-cla:no` is there still and I was wondering if there is any action expected on my side?

Thanks

**Comment by BenTheElder** [comment]
The CNCF CLA bot is reporting it was not signed.

I will comment on your PR to re-trigger the CLA bot, but we don't have any access to it here (it's totally operated by the CNCF and [is not open source](https://github.com/cncf/foundation/issues/3)), please contact the CNCF for CLABot issues at helpdesk@rt.linuxfoundation.org or see: https://github.com/kubernetes/kubernetes/issues/27796
