### ISSUE TITLE
hack/update-bazel.sh incorrectly updates BUILD files in untouched directories.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#5699]
I haven't been able to reliably reproduce this error, but I got it after modifying only `prow/plugins/approve/approve.go` which shouldn't affect the repoowners package BUILD file. When i reverted the BUILD file changes made by `hack/update-bazel.sh` and reran it the BUILD files were updated correctly. I've hit the same error while working on the require-sig plugin which is unrelated to repoowners.
```
colew@colew:~/go/src/k8s.io/test-infra$ hack/update-bazel.sh && bazel test --test_output=errors -- //... -//vendor/...
wrote "vendor/BUILD"
ERROR: /usr/local/google/home/colew/go/src/k8s.io/test-infra/prow/repoowners/BUILD:3:1: no such package 'vendor/k8s.io/apimachinery/pkg/util/sets': BUILD file not found on package path and referenced by '//prow/repoowners:go_default_library'
ERROR: Analysis of target '//prow/repoowners:go_default_library' failed; build aborted: Loading failed
INFO: Elapsed time: 0.989s
FAILED: Build did NOT complete successfully (28 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
```

Also when `hack/update-bazel.sh` is run against master it says: `wrote "vendor/k8s.io/apimachinery/pkg/util/sets/BUILD"` but does not actually modify the file.

cc @BenTheElder @ixdy

**Comment by BenTheElder** [comment]
> Also when hack/update-bazel.sh is run against master it says: wrote "vendor/k8s.io/apimachinery/pkg/util/sets/BUILD" but does not actually modify the file.

probably https://github.com/kubernetes/test-infra/pull/5320

**Comment by cjwagner** [comment]
This time I changed just `lgtm.go`. The only import change was the addition of the pluginhelp package. 
```
colew@colew:~/go/src/k8s.io/test-infra/prow$ git status
On branch populate-help
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   plugins/lgtm/lgtm.go

no changes added to commit (use "git add" and/or "git commit -a")
colew@colew:~/go/src/k8s.io/test-infra/prow$ ../hack/update-bazel.sh 
git status
wrote "vendor/BUILD"
colew@colew:~/go/src/k8s.io/test-infra/prow$ git status
On branch populate-help
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   plugins/lgtm/BUILD
	modified:   plugins/lgtm/lgtm.go
	modified:   ../vendor/BUILD
	deleted:    ../vendor/k8s.io/apimachinery/pkg/util/sets/BUILD

no changes added to commit (use "git add" and/or "git commit -a")
```

After resetting my working tree to HEAD except for the changes to `lgtm.go` I reran `hack/update-bazel.sh` and it worked properly the second time:
```
colew@colew:~/go/src/k8s.io/test-infra$ git status
On branch populate-help
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   prow/plugins/lgtm/lgtm.go

no changes added to commit (use "git add" and/or "git commit -a")
colew@colew:~/go/src/k8s.io/test-infra$ hack/update-bazel.sh 
wrote "vendor/k8s.io/apimachinery/pkg/util/sets/BUILD"
colew@colew:~/go/src/k8s.io/test-infra$ git status
On branch populate-help
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   prow/plugins/lgtm/BUILD
	modified:   prow/plugins/lgtm/lgtm.go

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by BenTheElder** [comment]
cc @cblecker

**Comment by cblecker** [comment]
Probably more specifically: https://github.com/kubernetes/test-infra/pull/5320/commits/1310d6880250888abedc23ba6b3b02818d47cd98

**Comment by cjwagner** [comment]
I'm only encountering problems when I run `hack/update-bazel.sh` from a subdir of test-infra. If I run it from the root of the repo it incorrectly says `wrote "vendor/k8s.io/apimachinery/pkg/util/sets/BUILD"`, but seems to modify the BUILD files correctly.

**Comment by BenTheElder** [comment]
> I'm only encountering problems when I run hack/update-bazel.sh from a subdir of test-infra. If I run it from the root of the repo it incorrectly says wrote "vendor/k8s.io/apimachinery/pkg/util/sets/BUILD", but seems to modify the BUILD files correctly.

Sounds like we should add a cd to the test-infra root at the beginning :this_is_fine:

**Comment by BenTheElder** [comment]
I think this should be fine now @cjwagner @ixdy (?)

**Comment by cjwagner** [comment]
Seems fixed on my end. Thanks Ben!
