### ISSUE TITLE
kuberneretes_verify scenario is not maintainable

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5708]
- We apparently version golint via pinning each branch to an image that we stop updating.
- most of the actual scenario logic is in hack/jenkins bash scripts in k/k which are brittle and heavily dependent on the environment.
- we use DooD with an image per branch run from the scenario to provide the expected environment (see also the first point)

/kind bug
/area scenarios
/area images
/assign
/assign @krzyzacy

**Comment by BenTheElder** [comment]
This affects test--go, verify, and unit jobs.

**Comment by BenTheElder** [comment]
Discussed offline with @ixdy, we've since had some other repos try vendoring golint which works pretty well and has some nice properties:
- anyone can simply update it with a PR to the target repo
- easy to run locally with the same version
- can fix any breaking changes in the PR that updates it

@ixdy suggested we could leverage some bazel features to pin it in the workspace and run from there.

**Comment by krzyzacy** [comment]
(of course it's been a year... will try to take an actual stab 😂)

**Comment by krzyzacy** [comment]
I don't have bandwidth to cherrypick everything properly, but at least master works without this scenario now. (We can no-op and drop this after three releases 😂 )

**Comment by ixdy** [comment]
I don't remember which changes are needed, but I think I cherry-picked at least some of them.

**Comment by ixdy** [comment]
https://github.com/kubernetes/kubernetes/pull/72668
https://github.com/kubernetes/kubernetes/pull/72669
https://github.com/kubernetes/kubernetes/pull/72670

**Comment by BenTheElder** [comment]
@amwat finished moving us off of this going forward I think
