### ISSUE TITLE
CNI 0.6.0 Plugin Support

### ISSUE THREAD

**Issue by danehans** [kubernetes/test-infra#5713]
https://github.com/kubernetes/kubernetes/issues/49480 plans to bump CNI plugins to 0.6.0 in the 1.9 release. https://github.com/kubernetes/kubernetes/pull/56245 attempts to update the kubenet template for 0.6.0, but e2e tests are failing. I believe this may be due to the test-infra not supporting the 0.6.0 CNI plugins. Can someone confirm that test-infra currently supports 0.6.0 CNI plugins or will support 0.6.0 in 1.9?

**Comment by ixdy** [comment]
I don't see anything in the linked PR that suggests this is a test-infra issue. As far as I know, test-infra has no opinions about any CNI plugins used in kubernetes.
