### ISSUE TITLE
gke-ubuntustable1-k8sstable2-ingress misbehaving?

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#5715]
From http://k8s-testgrid.appspot.com/sig-network-gke#gke-ubuntustable1-k8sstable2-ingress&width=20, frequently one run stuck forever and led to all following runs failed while deleting network (in used by a firewall rule created by the stuck run).

Also curious why different runs in this CI use the same network name if they create&delete network anyway...

BTW I never know who owns this CI :) Probably @yguo0905 knows?

**Comment by yguo0905** [comment]
I can change the tests to use the project pool to mitigate the issue caused by the stuck run. @krzyzacy 

GKE tests should be owned by sig-gcp now.

**Comment by krzyzacy** [comment]
sure, we have enough resource for gke pool

**Comment by MrHohn** [comment]
Thanks for the quick replies.

Another thought is I don't actually see much value running these ubuntu-ingress CIs as we already have equivalent gke-ingress CIs AND ingress tests are really not OS sensitive...I'm leaning toward just nuke these CIs to save resource and reduce noise.

**Comment by MrHohn** [comment]
> I'm leaning toward just nuke these CIs to save resource and reduce noise.

Discussed offline and seems better to keep these CIs.

> I can change the tests to use the project pool to mitigate the issue caused by the stuck run.

@yguo0905 Let me know how I can help :)
