### ISSUE TITLE
[release-1.9] bazel building from master

### ISSUE THREAD

**Issue by enisoc** [kubernetes/test-infra#5727]
The bazel-build-1.9 job seems to be building from master rather than from the `release-1.9` branch:

https://k8s-testgrid.appspot.com/sig-release-1.9-blocking#bazel-build-1.9&width=20
https://k8s-testgrid.appspot.com/sig-release-1.9-blocking#bazel-test-1.9&width=20

/assign @BenTheElder

**Comment by BenTheElder** [comment]
/kind bug
/area jobs
Fixing, this is a dumb bug but an easy fix 😞

**Comment by BenTheElder** [comment]
should be fixed for future runs now.
