### ISSUE TITLE
ProwJob controllers are failing to push metrics.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#5764]
Both `plank` and `jenkins-operator` are throwing errors like this every minute since I updated the deployments while rolling out #5754 .
```
component:  "jenkins-operator"   
  error:  "pushed metric prowjobs (label:<name:"job" value:"pull-cadvisor-e2e" > label:<name:"state" value:"success" > label:<name:"type" value:"presubmit" > gauge:<value:3 > ) already contains a job label"   
  level:  "error"   
  msg:  "Failed to push metrics."   
```
```
component:  "plank"   
  error:  "pushed metric prowjobs (label:<name:"job" value:"ci-cri-containerd-build" > label:<name:"state" value:"failure" > label:<name:"type" value:"periodic" > gauge:<value:1 > ) already contains a job label"   
  level:  "error"   
  msg:  "Failed to push metrics."
```
/cc @kargakis @Q-Lee

**Comment by kargakis** [comment]
Prometheus adds a "job" metric by default and our [job](https://github.com/kubernetes/test-infra/blob/41c86bacf0f8931563bf24bd5e0274f08126fd6a/prow/kube/metrics.go#L29) metric collides with it. We need to rename ours into something else.

**Comment by kargakis** [comment]
I am surprised though that this is an issue with pushing. When pulling the metrics, prometheus performs the renaming by default so we don't have this problem downstream.

**Comment by krzyzacy** [comment]
fyi it's still happening
```
{"component":"plank","error":"pushed metric prowjobs (label:\u003cname:\"job\" value:\"ci-cri-containerd-build\" \u003e label:\u003cname:\"state\" value:\"failure\" \u003e label:\u003cname:\"type\" value:\"periodic\" \u003e gauge:\u003cvalue:1 \u003e ) already contains a job label","level":"error","msg":"Failed to push metrics.","time":"2017-12-11T07:22:25Z"}
```

**Comment by cjwagner** [comment]
My PR didn't stop the spam on its own because the metric pushing logic only reads the `push_gateway` config when initializing `plank` or `jenkins-operator`.  Killing the pods forced the config to be reloaded.

@Q-Lee We should change this behavior. Updating the push interval or endpoint in the config shouldn't require a restart of the entire controller.

**Comment by kargakis** [comment]
How was this issue resolved? It would be nice to fix this:

> Updating the push interval or endpoint in the config shouldn't require a restart of the entire controller.

**Comment by cjwagner** [comment]
Yes, it doesn't seem to be a problem any more. We're not sure why the name collision fix didn't work for us the first time. I'll open an issue for the config change.
