### ISSUE TITLE
A kube PR that introduces an e2e test should run that test as part of the test suite

### ISSUE THREAD

**Issue by gnufied** [kubernetes/test-infra#5794]
Often I have seen that a PR that introduces or changes an e2e test, never gets e2e test in question being ran as part of merge request.  This is problematic because - we have no idea if introduced e2e test works. 

I am wondering if there is a way we can make sure that, PR that introduces certain e2e test always has the e2e test in question ran as its build/test  process.

**Comment by BenTheElder** [comment]
This is non-trivial, which e2e job should it run in? How do we know for sure that a new e2e was added?

I agree the concept sounds good, but we'll need a more specific proposal to actually implement this.

**Comment by gnufied** [comment]
Can we not grab name of e2e test file being changed via `git diff` ? We still have to figure out which environment the test should be run in and which e2e job should run it. @BenTheElder can you point me to code that decides which e2e job will run which test?

**Comment by BenTheElder** [comment]
> Can we not grab name of e2e test file being changed via git diff ? We still have to figure out which environment the test should be run in and which e2e job should run it. @BenTheElder can you point me to code that decides which e2e job will run which test?

e2e jobs are statically configured in `jobs/config.json`

jobs are run based on the files changed, the branch etc, but not the file contents, this is in prow.

**Comment by BenTheElder** [comment]
> Can we not grab name of e2e test file being changed via git diff ? 

The trick is making this reliable, and then connecting that to actually running it. I don't think that's quite so simple, and we'd need a job to own having probably unreliable new tests regularly run in it, adding spurious failures. Ideally sigs should own jobs now and be monitoring their health...

**Comment by krzyzacy** [comment]
is e2e test refers to an individual test, or a specific e2e job?
