### ISSUE TITLE
Testgrid time display is screwed?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#5808]
http://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-small

for example, https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/27154 starts at `2017-12-04 19:10 PST` but testgrid displays as `16:59`

/area testgrid
/assign @michelle192837

**Comment by krzyzacy** [comment]
(seems not happening anymore)

**Comment by michelle192837** [comment]
Oh, I meant to update this earlier. From what I can tell, it looks like TestGrid was reporting the correct time as specified in started/finished.json, so for future we'd want to look at why the Gubernator page is reporting what it is?

**Comment by BenTheElder** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/27154/started.json
`"timestamp": 1512443459` -> `Monday, December 4, 2017 7:10:59 PM GMT-08:00`
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/27154/finished.json
`"timestamp": 1512444769` ->  `Monday, December 4, 2017 7:32:49 PM GMT-08:00`
?

**Comment by michelle192837** [comment]
Nvm, I don't know what I managed to check last time. ._.
