### ISSUE TITLE
support tagging test runs with additional properties/metadata

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#581]
Some tests have additional properties to tag to runs, e.g. what node image is being tested. We should support tagging runs with arbitrary properties/metadata so that we can improve visualization and analysis (e.g. on gubernator, testgrid, and bigquery).

I can think of at least three ways to achieve this:
1. add `<property>` tags to the JUnit XML (ref http://llg.cubic.org/docs/junit/).
2. allow test owners to add fields to the `started.json` or `finished.json` files. 
3. support arbitrary metadata JSON files, probably in the `artifacts/` directory.

The first option (adding to junit) seems like it best supports the way we run the same test multiple times in different configurations for unit/integration/node e2e, though it also requires the most upstream work. (I'd started investigating how to do this in `ginkgo` but never completed the work. `go-junit-report` would be fairly easy to extend.)

OTOH, we already read `started.json` and `finished.json`, so extending those (or adding new files) isn't too bad, either.

@kubernetes/sig-testing

**Comment by fejta** [comment]
Related: https://github.com/kubernetes/kubernetes/pull/32740

**Comment by spiffxp** [comment]
I'm fine with leaning on `.json` as a thing that doesn't blow up when new fields are added.  Upstream might eventually give us the most benefit, and too many fields might lead to a desire for a schema.  But I think we have tools that look at `.json` already so we'd get benefit sooner going that route for now

**Comment by spiffxp** [comment]
Discussed during sig-testing today, head nodding and agreement over the use of json, couldn't really find anyone willing to jump up and down in favor of JUnit instead.

**Comment by rmmh** [comment]
We're putting the GCI node versions into started.json metadata now.

See kubernetes/kubernetes#32740 for more details.
