### ISSUE TITLE
Bazel build does not do full build anymore?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#5824]
i.e. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-bazel-build/226390 finished within 1min and did not actually built anything, even though we do `bazel clean` there :-)

/area bazel
/assign @BenTheElder @ixdy

**Comment by BenTheElder** [comment]
Strange. Sometimes it is
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-bazel-build/226398/

**Comment by BenTheElder** [comment]
It's the periodic job that has a broken config, but the same name :/

**Comment by BenTheElder** [comment]
Thankfully this only affected the periodic job in the master branch, the identically-named post-submit is fine and the job is quite green since it's just build and we block on build in pre-submit.
