### ISSUE TITLE
Navigate from root of deck to the rest of its pages

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5839]
It should be possible to navigate 

from 
http://prow.k8s.io/ 

to
http://prow.k8s.io/tide.html
http://prow.k8s.io/plugin-help.html
...

w/o knowledge of the paths

Maybe via an index page or direct links.

/area prow
@cjwagner @rmmh @stevekuznetsov

**Comment by cjwagner** [comment]
I discussed this briefly with @rmmh. Adding some links to the header is probably sufficient given that there aren't many pages right now.
