### ISSUE TITLE
prow: dev-release-note functionality

### ISSUE THREAD

**Issue by munnerz** [kubernetes/test-infra#5843]
sig-api-machinery are trying to improve the developer experience when building Kubernetes. We currently have a list of >100 PRs that do not specify release notes as they are solely developer facing changes, however this has caused many problems resulting in end users needing to look through recently merged PRs in order to work out how to fix their own code.

Ideally, there'd be some way for users to specify a 'developer' release note when writing PRs. After some discussion, @sttts suggested something along the lines of a new `dev-release-note` tag that is *optional* for all PRs (in order to not require all users to specify a dev-release-note on existing PRs).

Ideally we'd then have some kind of regex that matches directories, and enforces a dev-release-note for PRs that touch files matching the regex. It'd be possible to specify `NONE` just like with release-note still (for cases where it does not make sense to include a dev-release-note).

Is this something that can be considered to be included in Prow, and have sig-testing got any thoughts on how this might/should look?

/cc @sttts @nikhita @BenTheElder @fejta @spiffxp

**Comment by munnerz** [comment]
Sure - I didn't want to be too intrusive to the existing process is all (we end out with something that looks like this comment everywhere)

```release-note
NONE
```

```dev-release-note
NONE
```

**Comment by cblecker** [comment]
A couple questions:
- When you say "developer" I assume you are talking about "Developers building atop the API (e.g., client libraries, CRDs)", as opposed to contributors to the k8s project directly, or "End users deploying and managing applications (application operators and developers)". Is this assumption correct?
- If so, I also assume that these "Dev Release Notes" would need to be published? How often (same release cycle)?

**Comment by sttts** [comment]
> "Developers building atop the API (e.g., client libraries, CRDs)"

This.


> If so, I also assume that these "Dev Release Notes" would need to be published? How often (same release cycle)?

In every release of Kubernetes which has a matching release of our published libraries, e.g. client-go, apimachinery, etc. We would put the release into the Github release/tag markdown.

**Comment by BenTheElder** [comment]
also FYI @cjwagner since this would touch on Tide / Prow

I think this is certainly possible, but before implementing we should have a specific proposal and loop in ContribEx, when you say enforcing do you mean not allowing merge without a value? If so we should probably just add it to all PRs and handle it the same as the existing release note process,.

**Comment by cblecker** [comment]
Based on @sttts's answers, I'd suggest this would be more a topic for @kubernetes/sig-release-feature-requests then for contribex.

I would also suggest that perhaps there is a way to flag a release note in the text as being applicable to devs (similar to action required), and use the same release note system we already have.

**Comment by caesarxuchao** [comment]
cc @roycaihw who wrote a doc for similar ideas: https://docs.google.com/document/d/1AlcDeTlX7JOLkC7DEVtT9LRZ8N1bK1hrp8LRuep5joQ/edit#heading=h.5irk4csrpu0y

**Comment by sttts** [comment]
@caesarxuchao @roycaihw awesome document. Fits perfectly here.

**Comment by BenTheElder** [comment]
@caesarxuchao @stts that looks pretty good to me, I think the problem is that this requires prow jobs to have GitHub API access.

Possibly we could do this the way @fejta-bot works, which is to just comment on the PR with `/command foo` with a token / account that has no special privileges and then have prow convert this to adding a label. The downside to this is that we wouldn't be restricting the ability to add these labels.

#5848 might be another option. /cc @cjwagner

**Comment by sttts** [comment]
> Possibly we could do this the way @fejta-bot works

Where is the current release-note logic? Can't we re-use that code?

**Comment by BenTheElder** [comment]
> Where is the current release-note logic? Can't we re-use that code?

It's in [prow/plugins/releasenote](https://github.com/kubernetes/test-infra/tree/748d9bcf726ebe21621633b46d7cb17cf76d634d/prow/plugins/releasenote), but it's not a prow job and I don't think it inspects the file contents so the above doc wouldn't quite match up. It would certainly be more straight forward to do a prow plugin / extend the releasenote plugin but the sticking point would probably be needing to grep godeps.

I'm pretty sure the existing logic doesn't even inspect the file names in the PR @cjwagner .

**Comment by sttts** [comment]
> I don't think it inspects the file contents

got it.

**Comment by nikhita** [comment]
/remove-lifecycle stale

> I'd suggest this would be more a topic for @kubernetes/sig-release-feature-requests then for contribex.

If we were to get this in, what should be the next step? Talk to sig-release and sig-contribex?

**Comment by BenTheElder** [comment]
An aside: I think now something like this would be a good target for [an external plugin](https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins).

**Comment by nikhita** [comment]
Reviving this again:

> If we were to get this in, what should be the next step? Talk to sig-release and sig-contribex?

**Comment by nikhita** [comment]
I'm happy to work on the automation bits for this if proper guidelines are first agreed upon. :)

Right now, we go through all PRs created against `client-go`, `apimachinery`, etc in staging in `k/k`, check if the code change is relevant enough for a release note, write the release note in a spreadsheet and then convert it to markdown. 

I just created the [spreadsheet](https://docs.google.com/spreadsheets/d/1jPexPgSohmD7zVmIeVvAFjjK_pqFu4MdjsmBXlINfvg/edit#gid=0) for release-8 for client-go. It has 201 PRs! :scream:

**Comment by BenTheElder** [comment]
Hi yes, talking to contribex and release about how this should work would be good. I should have commented the first time instead of +1ing 🙃

**Comment by nikhita** [comment]
> Hi yes, talking to contribex and release about how this should work would be good. I should have commented the first time instead of +1ing upside_down_face

:+1: :slightly_smiling_face:

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/pull/138351 enables maintaining the CHANGELOG.md file in k/k together with the code changes.
