### ISSUE TITLE
Split out publishing bot into its own repo

### ISSUE THREAD

**Issue by sttts** [kubernetes/test-infra#5846]
The publishing bot now lives within the deprecated github munger at https://github.com/kubernetes/test-infra/tree/master/mungegithub/mungers. The version in master is broken since August and we have been iteratively working on a fixed version in https://github.com/kubernetes/test-infra/pull/4134 (repairing the bot) and https://github.com/kubernetes/test-infra/pull/4888 (adding tagging). We use it successfully (the later one including tagging) since the 1.8 release to publish the staging repos (client-go, api, apimachinery, etc.), with a manual git-push steps from private forks to github.com/kubernetes.

Since 
- the github munger is deprecated in favor of prow 
- and working on a big PR like https://github.com/kubernetes/test-infra/pull/4134 over months while have it already running on that code base for the same time is not sustainable,

we want to move it into a separate repo (github.com/kubernetes/publishing-bot) to have a base-line for further work with proper reviews and iterative changes.

The code is exported and separated from the github munger at https://github.com/kubernetes-nightly/publishing-bot. This repo is supposed to move to github.com/kubernetes/publishing-bot.

**Comment by BenTheElder** [comment]
This SGTM at first blush, pinging some relevant parties:
/cc @cjwagner @kargakis @rmmh @stevekuznetsov :bat: :flashlight:

**Comment by kargakis** [comment]
sgtm

**Comment by sttts** [comment]
Of course, I will create a follow-up PR to remove the publisher from the repo here.

**Comment by caesarxuchao** [comment]
lgtm!

**Comment by apelisse** [comment]
@thockin, would you be ok if we move that code to `github.com/kubernetes/publishing-bot`? If yes, then would you mind creating the repo? Thanks!

**Comment by thockin** [comment]
She, but will not have a chance for a while

**Comment by rmmh** [comment]
/lgtm

It doesn't use other parts of mungegithub for anything, extraction should be trivial-- just need to port flag definitions and write main().

**Comment by sttts** [comment]
> just need to port flag definitions and write main().

all done.

**Comment by cjwagner** [comment]
SGTM as well.

**Comment by thockin** [comment]
Sgtm

**Comment by stevekuznetsov** [comment]
Seems reasonable

**Comment by sttts** [comment]
https://github.com/kubernetes/publishing-bot has been created, thanks @eparis
