### ISSUE TITLE
prow: blunderbuss requests reviews from OWNERS even if there are reviewers requested by the PR author

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#5854]
This seems like a breaking change for workflows -- if I open a PR and I know who should be reviewing it, I tag them in with `/cc`. Before, if I tagged in the appropriate number of people, the bots would not attempt to request reviews from anyone else. Today, two more people get chosen anyway. If I've already chosen people, I don't really want this (and as the people must be net-new, they end up being peripheral to the code I'm editing anyway).

/cc @kargakis @cjwagner 
/kind bug
/area prow

**Comment by kargakis** [comment]
Yeah, I noticed this, too. Is there a sane way to do this now that blunderbuss is event-based?

**Comment by cjwagner** [comment]
Blunderbuss could ignore new PRs that contain a `/cc` command, assuming that the command will successfully request a review from someone. However if the command failed for some reason no-one would be requested as a reviewer. This might not be that big of a deal though?

**Comment by kargakis** [comment]
sgtm

**Comment by stevekuznetsov** [comment]
Yeah, that seems reasonable to me as well
