### ISSUE TITLE
Feature request: display filter count in deck

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5879]
It would be great if we could update deck to show at minimum a count of the total number of jobs running (possibly this could be another page, but I think "Prow Status" would cover this).

I think we can do this purely in the static site content, but I'd love for users to be able to more easily grasp the scale of kubernetes testing. 

We could place this somewhere in the "filter" bar and show a count for the current filter which would also allow seeing how many presubmit, post-submit, etc. are currently known to deck.

/area prow
/cc @kargakis @cjwagner @spxtr 
/assign

I'll probably tinker with this later.
Also: I do not want to overly clutter our beautiful status page, I just would like to know how many jobs I've filtered down to without having to count them  :-)

**Comment by BenTheElder** [comment]
/cc @qhuynh96 
Not sure if we actually want this or not, if not perhaps just close this :-)

**Comment by BenTheElder** [comment]
ping @qhuynh96

**Comment by stevekuznetsov** [comment]
Do we want to drive this using Prometheus and Graphana?

**Comment by BenTheElder** [comment]
> Do we want to drive this using Prometheus and Grafana?

?? I'm just proposing to show the number of jobs matching the filtering on https://prow.k8s.io/ so when I select say http://prow.k8s.io/?type=batch the frontend tells me how many entries exist instead of counting them myself.

**Comment by qhuynh96** [comment]
oops, forgot this. I will be on this tmr

**Comment by kargakis** [comment]
We already have prometheus metrics for prowjobs exposed by the controllers (plank, jenkins-operator).

**Comment by BenTheElder** [comment]
Yes, and we have dashboards for total builds. I'm not asking to graph it
overtime or anything like that, but I'd like to know how many entries are
in Deck specifically when I filter them, which is related to how many
prowjobs we have not yet cleaned up with sinker.

It's pretty common to show how many results match a filter, eg in email
clients. It's minor but I don't think this will be very intrusive and I
will use it. We only need to calculate and display client side. No Prow
changes.

**Comment by stevekuznetsov** [comment]
> but I'd like to know how many entries are in Deck specifically when I filter them, which is related to how many prowjobs we have not yet cleaned up with sinker.

Ah, sorry -- totally misunderstood what you were looking for here.
