### ISSUE TITLE
considering moving boskos image to bazel

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5882]
boskos already builds with bazel and has a very simple image, we could use rules_docker to build this. 

/area bazel
/area boskos
/assign
/cc @krzyzacy

**Comment by krzyzacy** [comment]
yeah, it can just be a `image_go` as @mattmoor 's prow stuff
/assign

**Comment by BenTheElder** [comment]
I'll open a PR for this after https://github.com/kubernetes/test-infra/pull/5883

**Comment by BenTheElder** [comment]
I intend to do this still, but possibly after the mason rejiggering since we have a lot moving there.., this will let us validate the boskos image build in presubmit

cc @sebastienvas

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
/shrug
test-infra is bazel based now mostly, probably should do this.

**Comment by BenTheElder** [comment]
this happened in the move to mason
