### ISSUE TITLE
Ensure zombies don't take over our nodes

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5887]
Ok I got you with the title, but it's true, xref: https://github.com/kubernetes/test-infra/issues/5877

We should make sure all of our images at least have the shell as an entrypoint, this is a very cheap (in effort and runtime cost), zero-dependency way to help ensure that zombie processes are cleaned up. 

This is important because many of our images can exist in long-lived containers which call subprocesses, and as seen in the issue above when thee subprocesses abort badly we can fill the PID space on the node and things start to fail (unsuprisingly), which can then interrupt jobs. 

For some workloads this really isn't acceptable (IE scalability's twelve-hour-long, five-thousand-node e2es).

/area images
/assign

FYI @krzyzacy @porridge I'll do some more on this ~Monday to check if there are any more places we can guard against unintentional PID exhaustion. 

Intentional PID exhaustion is still possible, but we can't trivially do more about this until kubernetes gets support for limiting PID on containers (which docker seems to have now) and we probably don't actually need to worry about fork bombs in PRs at the moment.

**Comment by BenTheElder** [comment]
More specifically xref: https://github.com/kubernetes/test-infra/issues/5700#issuecomment-350255095 and below, https://github.com/kubernetes/test-infra/issues/5877#issuecomment-350522942, previous mitigation for the boskos janitor: https://github.com/kubernetes/test-infra/pull/5885

**Comment by BenTheElder** [comment]
I still need to audit this, but we haven't seen anything like this so it's slightly on the back burner. the majority of our images are not (intentionally) using process trees so we *should* be fine but I want to take a closer look.

**Comment by stevekuznetsov** [comment]
Do we know what the longer-term k8s vision is for this space? It seemed like the `pause` container was going to solve this issue but it was turned on by default at a time that it should not have been -- can we still enable it for the GKE clusters where the applications are running? In my opinion it would be cleaner to make use of an external platform feature over having to change the entrypoint for all of our applications.

**Comment by BenTheElder** [comment]
Longer term k8s should get PID tracking and a global limit in the kubelet
(lower than the host).

We don't need to change applications that aren't forking, and a single
process per container is already the recommended use of docker. If we are
forking though it's easy for us to put the entry point behind something
that reaps zombies. PID limits will be *much* better long term as we could
still exhaust the PID space with non-zombie processes.

**Comment by BenTheElder** [comment]
I just took another pass over the images and I think we're probably fine enough for now, but we should keep this in mind and definitely adopt any PID related features if/when they're implemented in kubernetes.
