### ISSUE TITLE
spontaneous Prow jobs triggers

### ISSUE THREAD

**Issue by porridge** [kubernetes/test-infra#5893]
According to schedule, that job should have started on 2017-12-09 13:00 UTC, and it did, as [run 26](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/26).
However after having ran for ~6.5h, right after it has completed at 19:25:27.287 UTC, it was started again as [run 27](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/27) at 19:25:51.422 UTC. (That run in turn did not have enough time to complete after it was stomped over by another job.)

**Comment by porridge** [comment]
Might be related to https://github.com/kubernetes/test-infra/issues/5700

**Comment by krzyzacy** [comment]
```
E  {"msg":"Vending ci-kubernetes-e2e-gce-large-performance number 27 to 10.108.0.40:51146.","level":"info"} 
E  {"msg":"Vending ci-kubernetes-e2e-gce-large-performance number 26 to 10.108.0.40:48670.","level":"info"} 
E  {"client":"cron","level":"info","msg":"Triggering cron job ci-kubernetes-e2e-gce-large-performance."} 
```

from the log cron only triggered the first run - I suspect someone manually triggered the job, digging deeper

**Comment by krzyzacy** [comment]
(we probably want to log when plank create pods as well? maybe optional, but might be useful)

**Comment by BenTheElder** [comment]
FYI I had to do a few other things (meetings) but I am digging into this, so far there's not anything suspicious in the logs and I suspect this was genuinely triggered twice somewhere in plank or kubernetes.

**Comment by BenTheElder** [comment]
> (we probably want to log when plank create pods as well? maybe optional, but might be useful)

:+1: I can see sinker logging the pod deletions but nothing about the pod creation in the prow logs. It is however possible to do some more tracing through the prow-builds logs. I've not been able to find anything useful enough to root-cause this yet though :(

**Comment by kargakis** [comment]
You can turn on debug `log_level`, all client calls (including to Kubernetes) are logged in that level. Adding pod creation as info is not unreasonable.

**Comment by BenTheElder** [comment]
@porridge I think we will have to punt on this until we see another one, hopefully we will get appropriate logging before this happens again if it does. I've taken another look through and I don't seem to have enough info on this. We should log the job start from plank and get that out O(soonish).

**Comment by porridge** [comment]
Retitling since we have another two occurences. These two runs happened when they should not have (the scale-performance jobs should only start at 8 am UTC):
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/80
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/81

**Comment by porridge** [comment]
I think this issue is now the number one reason for failed scalability job runs. I miss the stability of jenkins :worried: 
Umbrella bug: https://github.com/kubernetes/kubernetes/issues/56062

**Comment by BenTheElder** [comment]
Sorry, I missed this with some other things going on and Sen is still out of town. I don't know why this would happen, but ironically Jenkins actually completely collapsed recently 🤷‍♂️

**Comment by porridge** [comment]
Another one:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/84

**Comment by krzyzacy** [comment]
sorry @porridge I'm still mostly OOO, I believe it's some plank issue, I'll try to walk through the code and see if I can find anything.

**Comment by krzyzacy** [comment]
from plank log the job did not get a state transition properly
```
E  {"level":"info","name":"b76c91bf-e3a5-11e7-9214-0a580a6c0130","component":"plank","type":"periodic","from":"triggered","to":"pending","job":"maintenance-ci-janitor","msg":"Transitioning states."} 
E  {"level":"info","msg":"Vending maintenance-ci-janitor number 303 to 10.108.1.53:36382."} 
E  {"msg":"Vending maintenance-ci-janitor number 304 to 10.108.1.53:43402.","level":"info"} 
E  {"level":"info","msg":"Vending maintenance-ci-janitor number 305 to 10.108.1.53:48678."} 
E  {"to":"failure","job":"maintenance-ci-janitor","msg":"Transitioning states.","level":"info","name":"b76c91bf-e3a5-11e7-9214-0a580a6c0130","component":"plank","type":"periodic","from":"pending"} 
```

**Comment by krzyzacy** [comment]
@BenTheElder I think https://github.com/kubernetes/test-infra/blob/master/prow/cmd/sinker/main.go#L160-L161 is racing with plank

**Comment by BenTheElder** [comment]
> @BenTheElder I think https://github.com/kubernetes/test-infra/blob/master/prow/cmd/sinker/main.go#L160-L161 is racing with plank

Why? It won't delete a pod until 30 minutes after the pod reaches a terminal state..

**Comment by kargakis** [comment]
> Why? It won't delete a pod until 30 minutes after the pod reaches a terminal state..

Pods reach terminal state earlier than prowjobs, not the other way around. By reducing the sinker interval to a value that is less than a job duration (30m is less than most jobs actually), you exposed the race between plank and sinker.

**Comment by BenTheElder** [comment]
> Pods reach terminal state earlier than prowjobs, not the other way around. By reducing the sinker interval to a value that is less than a job duration (30m is less than most jobs actually), you exposed the race between plank and sinker.

Got it, I expected plank to find these more often, but if it is taking ~30s then having syncer run every 1 minute instead of every 1 hour is also why this was triggered. We should get https://github.com/kubernetes/test-infra/pull/6042 in.

**Comment by krzyzacy** [comment]
seems the plank trigger issue is fixed, still see some rescheduled jobs like https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-performance, probably still due to https://github.com/kubernetes/test-infra/issues/5449

**Comment by porridge** [comment]
/reopen
Still happening: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/88 launched at a strange time (and, FTR, caused failure of https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/35 as colateral damage).

**Comment by BenTheElder** [comment]
Unfortunately the stackdriver logs only go back to ci-kubernetes-e2e-gce-scale-performance/89 and I did not catch this over the holiday.

**Comment by porridge** [comment]
Perhaps consider exporting logs to BigQuery? Works really well and you can
set a TTL if you're concerned about cost.

**Comment by krzyzacy** [comment]
@porridge the run 88 is not the same cause though

**Comment by porridge** [comment]
@krzyzacy all I know is that testgrid says it started at 6:19pm, rather than 00:01 like it should have,  so it matches this bug subject.

**Comment by krzyzacy** [comment]
It looks stable since the 01/05 entry. It will probably still facing the same issue whenever k8s decide to kill the running pod, but with ample amount of resource request, things like OOM really should not happen.

Also something I can think of is maybe while we upgrading k8s versions, but it seems fine when we updating from 1.8.5 to 1.8.6 last week.

I'll close it for now, feel free to reopen whenever you spot another instance.
