### ISSUE TITLE
Test that does not have a status shows up in comment report

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#5895]
See https://github.com/openshift/origin/pull/17506#issuecomment-350840261

`ci/openshift-jenkins/extended_conformance_crio` does not show up in github contexts since it's configured with [`skip_report: true`](https://github.com/openshift/release/blob/be09f45c06a2cedd3fc4402470b83e7eadca3ff5/cluster/ci/config/prow/config.yaml#L274) but was included in the bot's report.

/area prow
/kind bug

@cjwagner @stevekuznetsov

**Comment by cjwagner** [comment]
The context appears in the report comment for an older commit because when it ran on that commit (13 days ago) `skip_report` was not yet set to true by this commit: https://github.com/openshift/release/commit/534d08b833b81ee41221285d52bf470be193cce6 (10 days ago)
