### ISSUE TITLE
Feature request: make testgrid summary widget embeddable on github

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5896]
Discussed this at standup today: something like [the summary widgets](https://k8s-testgrid.appspot.com/q/summary/presubmits-test-infra) would be great to embed in GitHub READMEs similar to travis-ci badges etc. Perhaps at a different endpoint in SVG or PNG (since we can't just `iframe` the existing widget).

As an aside: could we also brighten up the green in particular? People like their shiny badges 😄 (EG at https://github.com/kubernetes/test-infra#kubernetes-test-infrastructure)

---------

Typical GitHub Badges:

<img width="539" alt="screen shot 2017-12-11 at 12 56 01 pm" src="https://user-images.githubusercontent.com/917931/33853389-ac585656-de72-11e7-9deb-1e05eb031c0e.png">

[Testgrid Summary Widget](https://k8s-testgrid.appspot.com/q/summary/presubmits-test-infra) (for anyone unfamiliar):

<img width="333" alt="screen shot 2017-12-11 at 12 57 17 pm" src="https://user-images.githubusercontent.com/917931/33853449-d86aef92-de72-11e7-8ca9-b527fdfe8d4f.png">

----

/kind feature
/area testgrid
/cc @rmmh @michelle192837

**Comment by MrHohn** [comment]
+1, looking forward to this!

**Comment by BenTheElder** [comment]
I would mark this help wanted but it's still internal for now. Might investigate this later when I clear a few other things.

**Comment by michelle192837** [comment]
This is actually possible now as a tiny embeddable, but I didn't update the documentation. >< https://k8s-testgrid.appspot.com/q/summary/sig-testing-misc/bazel/tests_status for an example, general is https://k8s-testgrid.appspot.com/q/summary/<dashboard>/<tab>/tests_status

**Comment by BenTheElder** [comment]
Sweet! can we get this documented then? :-)

**Comment by michelle192837** [comment]
Yup, I'll add it this evening.

**Comment by michelle192837** [comment]
Ugh, I think this needs a small change first? The content type returned currently is text/html, and the image won't show on Github; think it needs to explicitly return as svg.

**Comment by BenTheElder** [comment]
ah yeah, probably needs to actually serve image/svg+xml

**Comment by michelle192837** [comment]
Mmk, README.md is updated now!

**Comment by BenTheElder** [comment]
this is fixed now, neglected to close previously. see https://github.com/kubernetes/test-infra/pull/8021
/close
