### ISSUE TITLE
AWS HA Testing with kops

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#5916]
Thanks, @nckturner this is the issue that I mentioned I would file, please take a look and let me know what questions you have.

This is an outline of the changes that need to occur in test-infra in order for HA testing with kops.   These test runs are a start at fulfilling https://github.com/kubernetes/kubernetes/issues/54511.

## Using regions with 3 AWS AZ

The typical kops setup for an HA control plane is to have each master in its own AZ.  Currently, the python wrapper does not check if the Region has three AZ and uses a single AZ.  We have two options.  Add a second helper method for HA or modify the current method.  We probably should just run in a random region with 3 AZ.  

Here is the code that selects a random region to run in:

https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_e2e.py#L446-L455

We will also need to pass in three zones with e2e test runner.  @justinsb thoughts on this?

## New e2e test for kops

Once the region code is running, we can create a new e2e test for kops.

Here is an example https://github.com/kubernetes/test-infra/pull/5776 where we setup e2e for the m5 instance type.

Create a brand new e2e test and add `--kops-args=--master-count=3`.  You can see here https://github.com/kubernetes/test-infra/pull/5776/files#diff-5539d275f091e62154f51653bbe4fba0R8126 that we added params for the m5 type, instead add parameters for the master count.

/cc @justinsb @nckturner @eswarbala

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/pull/5880#issuecomment-350933543

can you also take a look at this^ @chrislovecnm? there's some ongoing work to make sure all AWS testing is using the official account from / credited by AWS and we need to coordinate with them (@arun-gupta) on quotas and how much we test.

**Comment by chrislovecnm** [comment]
Another note, we need to get etcd3 enabled with this. @justinsb what is that hidden flag we can use to add stuff to the manifest dynamically?

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/test-infra/pull/6113 is in, but needs testing

**Comment by chrislovecnm** [comment]
This is up and running working on gce now
