### ISSUE TITLE
document tide

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5919]
Tide needs a README with a brief overview we can point anyone too (not just those who wish to develop it) and a quick description of key features like batch testing / merge. we should put some details on configuring it below or perhaps in a seperate (linked) doc.

/area prow
/kind documentation
/assign
/assign @cjwagner 
FYI @yutongz 
/cc @kargakis @stevekuznetsov

**Comment by BenTheElder** [comment]
also FYI @mattfarina 

side note: @kargakis @cjwagner I think we almost might need to start making the area/prow be `area/prow/tide`, `area/prow/deck`... :thinking:

**Comment by cblecker** [comment]
+1 to area/prow/*

**Comment by yutongz** [comment]
That would be super helpful!

**Comment by BenTheElder** [comment]
FYI @spiffxp

**Comment by stevekuznetsov** [comment]
Controllers for `tide` are written in [`tide/tide.go`](https://github.com/kubernetes/test-infra/blob/master/prow/tide/tide.go). Config for `tide` is declared [`config/tide.go`](https://github.com/kubernetes/test-infra/blob/master/prow/config/tide.go) and an example is at [`config.yaml`](https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L96-L192).

**Comment by ingvagabund** [comment]
Cooking some README atm. Noticing the `tide` controller also consumes the `presubmits` part. Feels like it should be in the README as well. I will push additional changes once I get through the code and then sweep it one to n-times to polish it. Any feedback at any point is welcome.

**Comment by kargakis** [comment]
A tide README is added in https://github.com/kubernetes/test-infra/pull/7457 - @ingvagabund please sync with the PR author to avoid duplicating any work.

**Comment by ingvagabund** [comment]
Thanks, it will take some time before I will be able to sync. Getting `This page is taking way too long to load.` error when opening #7457.

**Comment by kargakis** [comment]
Seeing this as well unfortunately but I remember a README was added last time I was able to access it :)

**Comment by ingvagabund** [comment]
https://api.github.com/repos/kubernetes/test-infra/pulls/7457 says the PR is based on https://github.com/sebastienvas/k8s-test-infra/commits/required-tests.

Found https://github.com/sebastienvas/k8s-test-infra/blob/required-tests/prow/cmd/tide/README.md

**Comment by sebastienvas** [comment]
Yes the PR is still alive, but right I will create another PR with the documentation.
