### ISSUE TITLE
make deck redirect to https

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5921]
previously: https://github.com/kubernetes/k8s.io/issues/95

/area prow
/assign
/cc @cjwagner

**Comment by BenTheElder** [comment]
We should have an optional HTTPS redirect for deck, also we need to update our kube-lego config to point to a working email address and we probably should update it. 

I'll check later but I'm pretty sure my personal kube-lego instance is two patch versions newer and hasn't been seeing all the restarts we're seeing.

**Comment by cjwagner** [comment]
dup https://github.com/kubernetes/test-infra/issues/5282

**Comment by BenTheElder** [comment]
closing as a dup :upside_down_face:
