### ISSUE TITLE
Keep starter.yaml valid

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#5923]
I'm trying to deploy a staging prow, but found images in starter.yaml are outdated after https://github.com/kubernetes/test-infra/pull/5913 (deck was even at 0.69, for instance).

We probably want to somehow auto publish the image after each bump, or else when someone want to try out prow it will not work.

I'll try to add a job to deploy starter.yaml everyday later.

/area prow
/assign @cjwagner

**Comment by BenTheElder** [comment]
@krzyzacy we could probably do this easily as a post submit after we get #5848

**Comment by spxtr** [comment]
bump.sh should also be bumping starter.yaml versions...

**Comment by krzyzacy** [comment]
@spxtr yes that is the case, however we don't push latest image right away so when someone try to use starter.yaml, the components image might not exist yet.

**Comment by spxtr** [comment]
Solved by using rules_k8s?

**Comment by krzyzacy** [comment]
I think this is solved by @fejta's work
