### ISSUE TITLE
Broken links in gubernator test failure

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#5927]
E.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-staging-default-latest-upgrade-cluster-new/155 links to https://github.com/None/blob/a56b70fc480cec/test/e2e/lifecycle/cluster_upgrade.go#L137

**Comment by mml** [comment]
@kubernetes/sig-testing-bugs

**Comment by rmmh** [comment]
This was fixed in #6209.

The links here now work: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-staging-default-latest-upgrade-cluster-new/307/

**Comment by rmmh** [comment]
Mostly-- there's still a few broken links because upgrade tests run code that isn't always the same as the version that's in the build metadata. ¯\_(ツ)_/¯
