### ISSUE TITLE
don't use yahooapis.com for CSS in gcsweb

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#5934]
this is causing gcsweb to not load for some users, we should host our own, it's only 4kb

/kind bug
/assign

**Comment by BenTheElder** [comment]
FYI @hklai who reported this.

**Comment by hklai** [comment]
Is this rolled out?Still hangs for me.
https://github.com/istio/istio/issues/1885

**Comment by BenTheElder** [comment]
It's not. I'm not sure who has access to publish that at the moment. I'll
look into it.

**Comment by BenTheElder** [comment]
@ixdy is publishing an updated build

**Comment by ixdy** [comment]
deployed for real now.

**Comment by hklai** [comment]
Still connection problem in chrome, but works in safari.

**Comment by ixdy** [comment]
Anything suspicious in the network tab of developer tools? Do you have an extension which might be blocking it?

**Comment by ixdy** [comment]
Oh, http://gcsweb.istio.io/ is a different deployment.

Not sure who's maintaining that, but you'll need to update to `k8s.gcr.io/gcsweb-amd64:v1.0.6` like in https://github.com/kubernetes/k8s.io/pull/102.

**Comment by ixdy** [comment]
https://github.com/istio/admin-sites/blob/1998be2ad5b2d6d4eae8d072e8585bbdc47857ef/gcsweb.istio.io/deployment.yaml#L23 needs to be updated/deployed.
