### ISSUE TITLE
`dep ensure` outputs WARNING which requres branch, version, revision, or source

### ISSUE THREAD

**Issue by oomichi** [kubernetes/test-infra#5947]
When trying to run `dep ensure` on a clean test-infra, the command outputs the following WARNING::

$ go get k8s.io/test-infra
$ cd $GOPATH/src/k8s.io/test-infra
$ dep ensure
dep: WARNING: branch, version, revision, or source should be provided for "github.com/NYTimes/gziphandler"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/bwmarrin/snowflake"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/ghodss/yaml"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/go-openapi/spec"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/golang/glog"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/golang/lint"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/golang/mock"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/golang/protobuf"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/google/go-github"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/google/gofuzz"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/gregjones/httpcache"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/influxdata/influxdb"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/jinzhu/gorm"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/peterbourgon/diskv"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/satori/go.uuid"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/shurcooL/githubql"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/sirupsen/logrus"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/spf13/cobra"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/spf13/pflag"
dep: WARNING: branch, version, revision, or source should be provided for "golang.org/x/crypto"
dep: WARNING: branch, version, revision, or source should be provided for "golang.org/x/oauth2"
dep: WARNING: branch, version, revision, or source should be provided for "gopkg.in/yaml.v2"
dep: WARNING: branch, version, revision, or source should be provided for "k8s.io/contrib"

**Comment by BenTheElder** [comment]
Did you remove the lock by any chance?

**Comment by cblecker** [comment]
@oomichi are you trying to use k8s.io/test-infra as an import? Or are you looking to add an import to use in a PR against test-infra?

**Comment by oomichi** [comment]
@cblecker 

> Or are you looking to add an import to use in a PR against test-infra?

My first purpose was I wanted to add an import to use in my PR on test-infra, but this issue can happen without any change like the following on my env::

 $ go get k8s.io/test-infra
 $ cd $GOPATH/src/k8s.io/test-infra
 $ dep ensure
 dep: WARNING: branch, version, revision, or source should be provided for "github.com/NYTimes/gziphandler"
 dep: WARNING: branch, version, revision, or source should be provided for "github.com/bwmarrin/snowflake"
 dep: WARNING: branch, version, revision, or source should be provided for "github.com/ghodss/yaml"
 dep: WARNING: branch, version, revision, or source should be provided for "github.com/golang/glog"
 [..]

**Comment by oomichi** [comment]
@BenTheElder 

> Did you remove the lock by any chance?

Even after removing Gopkg.lock, this issue is reproduced on my env::

$ go get k8s.io/test-infra
$ cd $GOPATH/src/k8s.io/test-infra
$ rm Gopkg.lock
$ dep ensure
dep: WARNING: branch, version, revision, or source should be provided for "github.com/NYTimes/gziphandler"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/bwmarrin/snowflake"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/ghodss/yaml"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/golang/glog"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/golang/lint"
[..]

**Comment by cblecker** [comment]
what version of dep are you running?

**Comment by oomichi** [comment]
@cblecker 

That seems `devel` like the following, which version should we use ?

$ dep version
dep:
 version     : devel
 build date  :
 git hash    :
 go version  : go1.8.3
 go compiler : gc
 platform    : linux/amd64

**Comment by cblecker** [comment]
oh, you're actually using something newer than I am. will review the toml file.

**Comment by oomichi** [comment]
@cblecker Thanks :-)
