### ISSUE TITLE
Bot adding bad label

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#5948]
I am guessing that changing OWNERS files should not get the `retest-not-required-docs-only` label see https://github.com/kubernetes/kubernetes/pull/57178

That is technically code, which should be retested.  Thoughts?

/cc @fejta 
/sig test
/area prow

**Comment by stevekuznetsov** [comment]
What is gained by running presubmits on such a PR?

**Comment by BenTheElder** [comment]
IIRC `retest-not-required-docs-only` means that it will merge once the presubmits pass once, IE the queue will just merge without re-running them. I'm not sure why an OWNERS change would warrant running all of the presubmits.. ?

**Comment by chrislovecnm** [comment]
Cool, just looked odd, you guys know better than I

**Comment by BenTheElder** [comment]
> Cool, just looked odd, you guys know better than I

Always good to check :-)
Perhaps the label needs renaming 🤔
