### ISSUE TITLE
New stale closer doesn't skip keep-open

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/test-infra#5954]
It looks like the "keep-open" label no longer keeps a PR/Issue open the way it did under mungegithub.

**Comment by stevekuznetsov** [comment]
Seems like we can use the [label migration](https://github.com/kubernetes/test-infra/blob/master/label_sync/main.go#L42-L43) to move from the old label to the new one?

**Comment by mattfarina** [comment]
If a different label should be used instead I can update as needed.

**Comment by mattfarina** [comment]
Note, the restoration of the "never close" functionality has come from folks like Brian Grant, Tim Hockin, and others on the mailing lists.

**Comment by mattfarina** [comment]
#5969 migrates keep-open to lifecycle/frozen. Once the tags are migrated this can be closed.

**Comment by mattfarina** [comment]
I think this is now handled. Closing.
