### ISSUE TITLE
Prow support for triggering jobs based on tag changes

### ISSUE THREAD

**Issue by perotinus** [kubernetes/test-infra#5962]
It would be useful to the cluster-registry if Prow could support triggering jobs based on GitHub `CreateEvent"`s.

Concrete use case: I would like to be able to do cluster-registry releases without having to run tools locally on my machine, based on tags created by a GitHub release. If Prow can respond to GitHub `CreateEvent`s, then creating the tag can run the release process/upload binaries/etc. without requiring the person. This allows releases to be done by people who may not have write access to the GCP project that hosts the binaries, simply by creating a 

Subnote: it might be useful to know if a tag is verified, and to only start a release based on a verified, signed tag. cf https://help.github.com/articles/signing-tags-using-gpg/

**Comment by BenTheElder** [comment]
Also CC @kargakis @stevekuznetsov @sebastienvas for potentially interested parties.

As discussed on slack probably the most tricky part to supporting tag-triggered-jobs is deciding how we want the config to look.

I'm not sure about the GPG checking details wit github but this also sounds potentially useful

/area prow
/kind feature

**Comment by stevekuznetsov** [comment]
If we want to use these jobs for building and pushing releases we should probably get a trusted build cluster up and running otherwise your ProwJob running on a new tag won't have the credentials to do anything meaningful with whatever it builds.

**Comment by BenTheElder** [comment]
Yeah, it would be preferable to have #5848 first. We definitely plan to implement that one though.

**Comment by BenTheElder** [comment]
this would be nice to have for github releases though to further automate publishing of tagged/named release versions, the main reason we can't implement this is how cludgey the triggering logic is now :( 

this should basically just be a post-submit triggered on tags being pushed.

/remove-lifecycle rotten

**Comment by BenTheElder** [comment]
see this thread: https://github.com/kubernetes/test-infra/pull/10802#discussion_r248715913

**Comment by cjwagner** [comment]
So we already (inadvertently) support triggering jobs based on tag changes by using a postsubmit job with a branch regexp matching `refs/tags/<tag-name>`?
That is an interesting find and a pleasant surprise. I think that means we can close this issue.

**Comment by zhouhaibing089** [comment]
> So we already (inadvertently) support triggering jobs based on tag changes by using a postsubmit job with a branch regexp matching refs/tags/<tag-name>?

I think `refs/tags/` is [trimmed][1]..

[1]: https://github.com/kubernetes/test-infra/blob/51d0bbcafb99de8df59fe44a3e999f7757c1c138/prow/github/types.go#L804-L809
