### ISSUE TITLE
Test results are invisible in both Jenkins and test-grid if test never finished

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#597]
Observed by @wojtek-t when debugging tests running in large cluster. @bprashanth added few networking tests that caused the test to time out (which is fine), but it was quite painful to actually see which ones were problematic, because the problematic ones were not listed in test result analyzer nor in our test grid (which is not fine).

@kubernetes/test-infra-maintainers

**Comment by spxtr** [comment]
dupe of #79, which I think I'll be fixing as a part of #76 soon.

**Comment by gmarek** [comment]
Great. Thanks!
