### ISSUE TITLE
Lock down write access to gs://kubernetes-release-dev/?

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/test-infra#599]
That bucket is used to store CI builds, but apparently it allows write access to people who don't need to, e.g., myself. :)

I was trying to download the test tarball to run the e2e tests manually, but I forgot to append a dot at the end of the `gsutil cp` command line, which resulted in the test barball being overwritten by the release tarball.

```
gsutil -m cp gs://kubernetes-release-dev/ci/xxx/kubernetes.tar.gz gs://kubernetes-release-dev/ci/xxx/kubernetes-test.tar.gz
```

If I were copying the latest green build, I could have caused a few Jenkins jobs to fail, unexpectedly.

**Comment by wonderfly** [comment]
@ixdy @fejta

**Comment by spxtr** [comment]
This actually did cause a few Jenkins jobs to fail, unexpectedly XD

I rebuilt 1.4, hopefully they'll go green soon.

**Comment by spxtr** [comment]
With regards to the point, we have discussed moving CI stuff to a separate bucket from dev stuff. @zmerlynn might be the right contact.

**Comment by ixdy** [comment]
Well, we moved CI stuff away from `kubernetes-release` into `kubernetes-release-dev`, I think. We probably want a separate one for CI vs. dev builds, though.

Looking at the console browser, I see we have a `kubernetes-release-dev-jenkins`, but I don't think it's used anywhere? I'm not sure who created it, or what the intent for it is.

**Comment by zmerlynn** [comment]
I think this is a non-issue. You're part of an internal group that has access to `kubernetes-release-dev` (the purpose of that write access is to be able to bring up GKE clusters with custom k8s builds). We've talked about creating yet a third group, but in general, "don't screw up" has worked for this for long enough.

**Comment by zmerlynn** [comment]
(And yes, I realize that as the number of humans with access to *that* group increases, we stand a chance of losing more and more CI builds, but this isn't a big issue on the CI side.)

**Comment by wonderfly** [comment]
I wonder how long it would have taken @spxtr to figure out the recent CI failures were due to a human error if I didn't log this issue before they happened. If it was easy and not painful at all, and constant CI build failure emails are fine, then it's not a _big issue_. :)

**Comment by spxtr** [comment]
Were it not for this issue, I would've been super confused and probably would've wasted a long time trying to find a bug in the code. I agree with zmerlynn that it's probably not necessary to duplicate the bucket. We just have to trust that people with write access know to let us know when they break something, as you did here :)
