### ISSUE TITLE
planter.sh should not mount user home

### ISSUE THREAD

**Issue by Tombar** [kubernetes/test-infra#5998]
Hello, i'm interested in contributing to test-infra, so while I familiarize myself with the repo itself, bazel and overall guidelines, I would like to solve some low hanging fruit issues. 

I've reach @BenTheElder through the sig-testing slack channel and agreed on looking at this issue, which is causing issues like #5607 and it's not ideal overall.

About the issue, today planter.sh mounts user home as a way to share and expose bazel build/logs/cache to the user outside of the docker container.

I've look at this issue and play around only passing the local cache into the container instead of the user home directory but bazel run would fail on a second run. 

With this changes: 

```
tombar@ww2 ~/c/k/s/k/test-infra (master) [1]> git diff planter/planter.sh
diff --git a/planter/planter.sh b/planter/planter.sh
index 95a712711..ecd9195ab 100755
--- a/planter/planter.sh
+++ b/planter/planter.sh
@@ -24,9 +24,9 @@ IMAGE="${IMAGE_NAME}:${TAG}"
 # run our docker image as the host user with bazel cache and current repo dir
 REPO=$(git rev-parse --show-toplevel 2>/dev/null || true)
 REPO=${REPO:-${PWD}}
-VOLUMES="-v ${REPO}:${REPO} -v ${HOME}:${HOME} --tmpfs /tmp:exec,mode=777"
+VOLUMES="-v ${REPO}:${REPO} -v ${HOME}/.cache:/workspace/.cache --tmpfs /tmp:exec,mode=777"
 GID="$(id -g ${USER})"
-ENV="-e USER=${USER} -e GID=${GID} -e UID=${UID} -e HOME=${HOME}"
+ENV="-e USER=${USER} -e GID=${GID} -e UID=${UID} -e HOME=/workspace/"
 # the final command to run
 CMD="docker pull ${IMAGE} && docker run --rm ${VOLUMES} --user ${UID} -w ${PWD} ${ENV} ${DOCKER_EXTRA:-} ${IMAGE} ${@}"
 if [ -n "${DRY_RUN+set}" ]; then
```

First  run of `export TAG="0.8.0" ; time ./planter/planter.sh bazel test //...`
```Executed 97 out of 97 tests: 97 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
     3094.06 real         0.10 user         0.11 sys
tombar@ww2 ~/c/k/s/k/test-infra (master)> set -x TAG "0.8.0
```

But second run of `export TAG="0.8.0" ; time ./planter/planter.sh bazel test //...` just get stuck at 
```
Loading: 204 packages loaded
    currently loading:
```

the `java.log` last line is:

```
171215 22:47:32.148:I 31 [com.google.devtools.build.lib.skyframe.ExternalFilesHelper.maybeHandleExternalFile] Encountered an external path [/]/[workspace/.cache/bazel/_bazel_tombar/install/8374ca305a4964993b70245bd4bb95cf/_embedded_binaries/embedded_tools/tools/osx/xcode_configure.bzl]
```
same thing happens if I either use `tmp` folder or a new `build` folder I create
All that said, any comment or tip?

**Comment by BenTheElder** [comment]
FYI @ixdy

**Comment by ixdy** [comment]
We've tried only mounting `$HOME/.cache/bazel` before, but it has problems - see https://github.com/kubernetes/test-infra/pull/5737.

I'm not quite sure what's happening here, though.

**Comment by Tombar** [comment]
Ok, so I run some more tests and this is what I understand so far:

If I mount host`$HOME/.cache/bazel` under something different than `$HOME/.cache/bazel` in the container, such as for example `/workspace/.cache/bazel` bazel would run the first time  successfully only and files under `$HOME/.cache/bazel` would be symlinked incorrectly

```
file /Users/tombar/.cache/bazel/_bazel_tombar/b568b410885587224322407150d7556e//execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_pure/src/cmp.bash
/Users/tombar/.cache/bazel/_bazel_tombar/b568b410885587224322407150d7556e//execroot/__main__/bazel-out/host/bin/external/go_stdlib_linux_amd64_pure/src/cmp.bash: 
broken symbolic link to /workspace/.cache/bazel/_bazel_tombar/b568b410885587224322407150d7556e/execroot/__main__/external/go_sdk/src/cmp.bash
```

So we need to mount `$HOME/.cache/bazel` into `$HOME/.cache/bazel` to get bazel to build successfully multiple times. Further research can be do to check if bazel option `$TEST_TMPDIR` and/or `--output_user_root` allows for a cleaner workaround.

Regarding NPM cache issues #5737, mounting also `${HOME}/.npm:/${HOME}/.npm` solves the build issues.

All that said, this would be the changes need to be applied:

```
diff --git a/planter/planter.sh b/planter/planter.sh
index 95a712711..1fb16dc6d 100755
--- a/planter/planter.sh
+++ b/planter/planter.sh
@@ -24,7 +24,7 @@ IMAGE="${IMAGE_NAME}:${TAG}"
 # run our docker image as the host user with bazel cache and current repo dir
 REPO=$(git rev-parse --show-toplevel 2>/dev/null || true)
 REPO=${REPO:-${PWD}}
-VOLUMES="-v ${REPO}:${REPO} -v ${HOME}:${HOME} --tmpfs /tmp:exec,mode=777"
+VOLUMES="-v ${REPO}:${REPO} -v ${HOME}/.cache/bazel:/${HOME}/.cache/bazel -v ${HOME}/.npm:/${HOME}/.npm --tmpfs /tmp:exec,mode=777"
 GID="$(id -g ${USER})"
 ENV="-e USER=${USER} -e GID=${GID} -e UID=${UID} -e HOME=${HOME}"
 # the final command to run
```

Let me know if you agree on the approach and I can submit a PR.

Regards

M

**Comment by ixdy** [comment]
Sounds good to me. Send over a PR and we can discuss any additional details there.
