### ISSUE TITLE
test-history/gen_json script should not depend on accessing Jenkins

### ISSUE THREAD

**Issue by euank** [kubernetes/test-infra#6]
It would be useful if, like the munger, the `test-history` scripts depended solely on GCS buckets as input. This would allow federating tests results on the dashboard, not just in PR statuses, via the familiar GCS bucket format.

Right now, accessing the jenkins server is used to list job names, their builds (with status), and the timestamp. These can be replaced with, respectively, a config file listing job name -> gcs path mappings, reading build numbers from the bucket, and parsing started.json + finished.json.

**Comment by spxtr** [comment]
Agreed. I think I wrote it before we had `started`/`finished.json`, so I had to go to Jenkins for the build result.
