### ISSUE TITLE
$IMAGE isn't set correctly in our images

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#6015]
per discussion on slack with @ixdy, it seems the existing env in the base image is being kept instead of the build arg.

/kind bug
/area images
/assign

**Comment by ixdy** [comment]
To give an explicit example, https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/56820/pull-kubernetes-e2e-gce/12279/?log#log shows
```
I1218 19:16:23.315] Bootstrap pull-kubernetes-e2e-gce...
I1218 19:16:23.315] Builder: dc48cd59-e427-11e7-aaee-0a580a6c0223
I1218 19:16:23.315] Image: gcr.io/k8s-testimages/bootstrap:v20171210-9bf1eccaf
```

where we would expect kubekins-e2e instead of bootstrap.
