### ISSUE TITLE
Migrate owner-label and path-label mungers out of mungegithub

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#6033]
This is being used in kubernetes/community, now that we've migrated OWNERS handling to prow this should be relatively easy to re-implement as a plugin, or maybe add'l functionality for the existing label plugin?

/area prow
/area mungegithub

xref #6019
xref #3331

**Comment by cjwagner** [comment]
/assign
I'm working on this. I want to combine the `owner-label` and `path-label` mungers' functionality into a single Prow plugin. I'll make a DD and link to it here.

**Comment by cjwagner** [comment]
Oops, I forgot to provide the link from this issue:
https://docs.google.com/document/d/1VfH8vIO22qzekM9nkIO_434p5e7J3Wrz0odaSHAkF40/edit
