### ISSUE TITLE
Cron Job to replace mungegithub's branch protection feature.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#6035]
Currently we use mungegithub's `branch-protection` feature to mark Github status contexts as required where ever the submit-queue is run.
https://github.com/kubernetes/test-infra/blob/c4c730a46fd176a8d161bf5ef0074067a8a12d94/mungegithub/features/branch-protection.go#L55-L65
As we deprecate the submit-queue in favor of Tide this feature will need to be moved to a cron-job that runs in the Prow cluster or a trusted periodic job running in a trusted build cluster (same implementation either way).

Currently we have to maintain a list (or lists) of the contexts that should be marked as required.
https://github.com/kubernetes/test-infra/blob/c4c730a46fd176a8d161bf5ef0074067a8a12d94/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L108
https://github.com/kubernetes/test-infra/blob/c4c730a46fd176a8d161bf5ef0074067a8a12d94/mungegithub/submit-queue/deployment/kubernetes/configmap.yaml#L15-L23

It would be nice if we could determine which contexts are provided by ProwJobs (by parsing the job config) and mark those as required automatically. We could then shorten the list of required contexts we need to maintain to just contexts that Prow doesn't control like the CNCF-CLA context or a Travis context.

ref #6019 
/area mungegithub
/area prow
/help

**Comment by fejta** [comment]
https://docs.google.com/document/d/1DmNEtHM8ocbmIknThpF9VoJVrueIixjQN49brVd_Zq0/edit

**Comment by cjwagner** [comment]
This is complete.
ref #6205
/close
