### ISSUE TITLE
Make it easy to link to specific Plugin Help entries.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#6050]
It is possible to link to a specific plugin help row by using a URL anchor/fragment to the element ID like http://prow.k8s.io/plugin-help.html?repo=kubernetes%2Ftest-infra#plugin-heart, but only if you are already on the page and add the fragment manually. The following improvements should be made:
- [x] Add a symbol ( ¶ ) next to each plugin name that links to the plugin row.
- [ ] Make the plugin row start as expanded if we linked to the plugin directly with a fragment reference.
- [x] Prevent page refreshes from throwing out fragment reference in the URL. (This prevents the above link from working because the page load overwrites the URL.)

**Comment by BenTheElder** [comment]
we should also:
- [ ] highlight plugins that are most relevant to end users (IE `config-updater` is not, but `hold` should have a star or something)
