### ISSUE TITLE
ci-kubernetes-e2enode-ubuntudev2-k8sbeta-gkespec not running?

### ISSUE THREAD

**Issue by yguo0905** [kubernetes/test-infra#6055]
https://k8s-testgrid.appspot.com/canonical-ubuntudev2-k8sbeta#e2enode-ubuntudev2-k8sbeta-default(gkespec)

The last run of this job is 15:10, but it's supposed to be running every 2 hours. I can't see any errors in prow.k8s.io.

This [test](https://k8s-testgrid.appspot.com/canonical-ubuntudev2-k8sbeta#e2enode-ubuntudev2-k8sbeta-serial) also has the same issue but others are OK. How should I debug this?

/assign @BenTheElder @krzyzacy

**Comment by krzyzacy** [comment]
http://prow.k8s.io/?type=periodic&job=ci-kubernetes-e2enode-ubuntudev2-k8sbeta-gkespec#

eh, is that the image you've pushed?
```
Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath				Type		Reason		Message
  ---------	--------	-----	----							-------------				--------	------		-------
  5h		6m		1452	kubelet, gke-prow-pool-n1-highmem-8-81ce4395-n2sj						Warning		FailedSync	Error syncing pod
  5h		2m		1406	kubelet, gke-prow-pool-n1-highmem-8-81ce4395-n2sj	spec.containers{d7c4a827-e5eb-11e7-9214-0a580a6c0130-0}	Normal		BackOff		Back-off pulling image "gcr.io/k8s-testimages/kubekins-e2e:v20171218-a18c352b4-1.9"
```

**Comment by krzyzacy** [comment]
@yguo0905 did someone removed the previous tag from the image registry? I've manually added tag `v20171218-a18c352b4-1.9` back, after the next run it should use `v20171220-29cb083c9-1.9` in current config.

**Comment by krzyzacy** [comment]
the job looks green now :-)
/close
