### ISSUE TITLE
Remove "lgtm" after PR changes?

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#6070]
In test-infra, after an approved and lgtm'd PR rebasing or changing, the `lgtm` is not removed. Then the PR will be merged. (example: #5904). Seems like it's not safe, right? Suppose that I add some ruinous code by mistake or intentionally (:smile:), something would be broken after the merge.

/cc @cjwagner @krzyzacy @BenTheElder -

**Comment by spxtr** [comment]
If it's *broken* broken then the presubmit should catch it :)

Dupe of #3795 I think.

**Comment by xiangpengzhao** [comment]
Oh cool! Didn't notice that :)
