### ISSUE TITLE
Lifecycle bot is too noisy

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#6084]
I would ask that we turn down how many issues the bot handles at once. Also how about three strikes then I close you? Two warnings then I close the issue?

**Comment by stevekuznetsov** [comment]
I have a feeling this will calm down once the backlog is worked through.

/cc @fejta

**Comment by fejta** [comment]
> Two warnings then I close the issue?

That's how it works: stale, rotten, close

Don't think there's anything left to do here?

**Comment by neolit123** [comment]
i do follow a lot of k8s repos and i do see the bot batch-handle multiple issues/prs at once.
but i think this is OK.
