### ISSUE TITLE
Vendor AWS api 

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#6085]
Anyone have a problem with me vendoring AWS api in this repo? I want to move more to the kops tester functionality into go and out of python.

**Comment by BenTheElder** [comment]
I think we've avoided actually vendoring it because it's huge IIRC:
https://github.com/kubernetes/test-infra/blob/40e8b22e3c37457c973c118b2aefa097b1d063ed/Gopkg.toml#L3-L4

**Comment by chrislovecnm** [comment]
I am not certain in the size, but does that matter? We are using python code, which is not tested ;( 

Another option is to move the go code into the kops repo ...

**Comment by chrislovecnm** [comment]
Python code does not have unti tests

**Comment by chrislovecnm** [comment]
Unit tests ... gawd phone

**Comment by chrislovecnm** [comment]
I am going to PR this, because I want to move testing logic into the test runner.

**Comment by chrislovecnm** [comment]
Completed, closing
