### ISSUE TITLE
Document how to build test-infra on a mac

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#6087]
How do I do this?  planter I am guessing ...

**Comment by BenTheElder** [comment]
Most of test infra should build with `bazel build //target_directory_you_wanted_to_build/...`. Planter helps with building linux binaries / switching bazel versions etc.

**Comment by BenTheElder** [comment]
bazel build //... should just work now, I don't think there's any part of test-infra that doesn't work on mac. Across all platforms you may need to install the python libs in requirements.txt files throughout the repo if you want to work on those.
