### ISSUE TITLE
Set up CI running builds and unit/integration tests on OS X

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#61]
We seem to break the build scripts on OS X not infrequently. It'd be nice to have some sort of CI to detect this before developers do.

**Comment by spxtr** [comment]
Also probably useful to run a smoke e2e test.

**Comment by fejta** [comment]
Unfortunately I don't see this happening any time soon.

**Comment by techtonik** [comment]
Is there at least place to redirect people who are interested to help with status of OS X build node?
https://github.com/kubernetes/kubernetes/issues/40099
https://github.com/kubernetes/community/issues/339
