### ISSUE TITLE
Migrate mungegithub to kubernetes-retired

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#6104]
Per comments in https://github.com/kubernetes/test-infra/pull/6071 and https://github.com/kubernetes/test-infra/pull/6065

I've been attempting to remove as much of mungegithub as we can as we replace its functionality with prow, to make absolutely clear that we no longer support it.  However, others may find it useful, and may not be able to migrate away as quickly as we have been.  We're not exactly dropping mungegithub tomorrow, but are actively trying to move away from it; see #3331 for our progress in implementing the same functionality elsewhere.

So, as long as we collectively promise never to make any bugfixes that we'd have to bother to backport, I am willing to try undertaking a migration of mungegithub with most of its mungers intact (eg: with the aforementioned PR's reverted), out of kuberentes/test-infra to someplace in kubernetes-retired.  

At worst, it'd just be a dump of the existing source code.  But presumably it should at least be buildable / deployable in some form.  I'm not sure how much time I'll be able to put toward making it minimally maintainable, but I can try.  Suggestions on repo / package? kubernetes-retired/mungegithub as retired.k8s.io/mungegithub?  kubernetes-retired/test-infra/mungegithub as retired.k8s.io/test-infra/mungegithub? etc.

FYI @BenTheElder @kargakis @yutongz @sebastienvas 
Open to suggestions on what to do, I agree with the intent of the idea but am not sure of the specifics

/assign
/area mungegithub

**Comment by kargakis** [comment]
>  `kubernetes-graveyard/mungegithub`

+1 on a standalone repo and a warning in the docs pointing back to prow

**Comment by sebastienvas** [comment]
istio is almost done. the last part if getting approval on https://github.com/kubernetes/test-infra/pull/7457

**Comment by spiffxp** [comment]
/close
Yeah, not a migration I'm going to be undertaking anytime soon. If someone else wants to, they're free to /reopen
