### ISSUE TITLE
k8s-ci-robot adds both a sig-* and needs-sig labels in response to the same comment

### ISSUE THREAD

**Issue by porridge** [kubernetes/test-infra#6109]
See https://github.com/kubernetes/kubernetes/issues/57706#event-1404425003 - the bot added a sig label and a needs-sig label, and removed it, all in response to a single (initial) comment.

**Comment by kargakis** [comment]
This is how labels show up by Github if they are added and removed at the same time (or even when there is no other event in between and the second label action is hours later). It seems that the labels are applied correctly.

/close

**Comment by porridge** [comment]
/reopen
My point is that the bot should not be adding the needs-sig label (and spamming the issue author) at the same time if the initial message does specify the sig.

**Comment by kargakis** [comment]
Fair point. Please reword the issue title to be more specific.

**Comment by porridge** [comment]
Similar case in k/k#57708

**Comment by kargakis** [comment]
We have this problem in other plugins, too. For example, blunderbuss will request reviews from OWNERS files even if you have `/cc`'d someone in the initial post.

cc @cjwagner

**Comment by cjwagner** [comment]
ref #5854

**Comment by stevekuznetsov** [comment]
See also https://github.com/kubernetes/test-infra/issues/3699
