### ISSUE TITLE
Cleanup v1.6 jobs

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#6111]
v1.6 is not supported anymore now with the new v1.9 release according to [our docs](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md), so we can remove our v1.6 jobs and reclaim resources.

cc @BenTheElder @krzyzacy @fejta @spiffxp

**Comment by BenTheElder** [comment]
I'm in favor of this but we need to clear it with @enisoc

**Comment by BenTheElder** [comment]
ping @enisoc are we ready to do this?

**Comment by krzyzacy** [comment]
done by #6538
