### ISSUE TITLE
Update kops to use etcd 3 with testing

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#6114]
Use the override flag once https://github.com/kubernetes/kops/pull/4179 is merged

**Comment by krzyzacy** [comment]
/assign @chrislovecnm 
this is probably should be in kops repo?

**Comment by chrislovecnm** [comment]
This is part of kubetest actually, etcd2 is default since h upgrade is a little complex still. We are working on that, but will send in a pr to enable etcd 3

**Comment by chrislovecnm** [comment]
We having this already. Already fixed
