### ISSUE TITLE
Testgrid should indicate which builds were started by SCM changes and which ones were started by timer 

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#612]
Indicating which ones were started by SCM changes would help us figure out at a glance if a new broken test is due to some change/flake/test infrastructure failures.

**Comment by spxtr** [comment]
We have the commit hash as a column header, which I'm hoping is enough. If that changes then there was a SCM change. The e2e jobs themselves don't actually know about SCM changes, which would make indicating it some other way difficult.

**Comment by foxish** [comment]
@spxtr @fejta 
Ah! just noticed that now. It's much easier to see in the "compact" view. Any thoughts on making that the default?

**Comment by spxtr** [comment]
I would actually be fine with that. @fejta thoughts?

**Comment by fejta** [comment]
@krzyzacy let's unreserve field 6 in `DashboardTab` and set default_dashboard_tab's `base_options` to `width=20`

```
message DashboardTab

  // Optional base options to apply to a tab. The base options apply to a tab
  // always. Explicitly specified options are appended to the base options to
  // form the complete list of options. There is no way to remove base options
  // when loading a tab.
  // The base options become part of the query string. For example, specify
  // "width=20&include-filter-by-regex=level_tests" to generate the tests in the
  // dashboard tab in compact view and filter out the tests containing the
  // regular expression 'level_tests'.
  // TODO: Use structured data to encode the options. The client can
  // use the same proto.
  optional string base_options = 6 [default = ''];
```

**Comment by fejta** [comment]
Any progress here?

**Comment by krzyzacy** [comment]
nope... muck with Jenkins is not a good idea, prow now label pods with `presubmit`, `postsubmit`, and `periodic`, maybe somehow we can use that information
