### ISSUE TITLE
Uploading build results is failing for kubernetes-e2e-gce-gci-ci-release-1.4

### ISSUE THREAD

**Issue by vishh** [kubernetes/test-infra#613]
cc @wonderfly 

<details>
12:57:47 [Current build status] check if current [FAILURE] is worse or equals then [SUCCESS] and better or equals then [SUCCESS]
12:57:47 Run condition [Current build status] preventing perform for step [Execute shell]
12:57:47 [Current build status] check if current [FAILURE] is worse or equals then [UNSTABLE] and better or equals then [UNSTABLE]
12:57:47 Run condition [Current build status] preventing perform for step [Execute shell]
12:57:47 [Current build status] check if current [FAILURE] is worse or equals then [FAILURE] and better or equals then [FAILURE]
12:57:47 Run condition [Current build status] enabling perform for step [Execute shell]
12:57:47 [kubernetes-e2e-gce-gci-ci-release-1.4] $ /bin/bash -xe /tmp/hudson2661855704545195673.sh
12:57:47 + JENKINS_BUILD_FINISHED=FAILURE
12:57:47 + ./_tmp/upload-to-gcs.sh
12:57:47 Run finished at Mon Sep 19 12:57:47 PDT 2016
12:57:47 Uploading to gs://kubernetes-jenkins/logs/kubernetes-e2e-gce-gci-ci-release-1.4/149 (attempt 1)
12:57:47 Uploading build result: FAILURE
</details>

**Comment by ixdy** [comment]
how is this failing?

**Comment by vishh** [comment]
The output from the upload failure is under `Details`.

**Comment by ixdy** [comment]
Are you talking about the line `Uploading build result: FAILURE`? it's misleading, but it's uploading the result "FAILURE" - it didn't fail itself.

**Comment by vishh** [comment]
The reason I looked at the test output is because test results are missing from test grid. Relevant link [here](https://k8s-testgrid.appspot.com/google-gci#gci-ci-release-1.4)

**Comment by ixdy** [comment]
That's probably a different issue. Assigning relevant folks.

**Comment by krzyzacy** [comment]
er, that test has no last success run

**Comment by wonderfly** [comment]
FYI. The tests were added last Friday and are failing due to a known reason.

**Comment by fejta** [comment]
What is the status here?

Is this because the server doesn't automatically load updates to the config?

**Comment by krzyzacy** [comment]
Can it be since the test has never succeeded, it would not even try to upload the result to testgrid?

**Comment by fejta** [comment]
No, given that it runs and produces results I would expect it to look like the build jobs: https://k8s-testgrid.appspot.com/google-unit

**Comment by krzyzacy** [comment]
I think this is fine now after all the testgrid and bootstrap fixes. Close for now.
