### ISSUE TITLE
Standardize on /remove-foo for /foo commands that need an undo variant

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#6136]
Pulling a nit out of #6003 

@cjwagner
>I wish our commands had a more standard format. We have `un` and `remove-` prefixes in addition to `cancel` parameters 👎

@fejta
>I think we should standardize on `/remove-foo`

---

FTR it looks like we currently have:
- cancel
  - `/approve [cancel]`
  - `/hold [cancel]`
  - `/lgtm [cancel]`
- remove
  - `/[remove-]help`
  - `/[remove-](area|committee|kind|priority|sig) <target>`
  - `/[remove-]lifecycle <frozen|stale|putrid|rotten>`
- un
  - `/[un]assign [[@]<username>...]`
  - `/[un]cc [[@]<username>...]`

I'm also in favor of `/remove-foo`, though for some strange human reason the "un" prefixes still make sense to me for those two commands.  Maybe keep the weird ones around as legacy aliases but move to make all of them have `/remove`

**Comment by stevekuznetsov** [comment]
`/remove-approve` sounds silly though as does `/remove-assign` so would we change those verbs to nouns? `/remove-approval`?

**Comment by cjwagner** [comment]
/remove-lifecycle stale

https://github.com/kubernetes/test-infra/pull/8131 will help with this.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/help
This isn't quite good-first-issue material but it's relatively doable without much context.  I would be happy if this was just adding `/remove-foo` for those commands that lack it, while leaving the older commands intact.  I would be happier if we dropped the older commands with some advanced notice.
