### ISSUE TITLE
Add branch filtering in deck/gubernator/testgrid

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6144]
@mfojtik wanted to know whether a job fails across a release branch but couldn't figure it out. We should probably have an extra filter for branches in deck.

cc: @cjwagner @stevekuznetsov @rmmh @BenTheElder 

/area prow

**Comment by BenTheElder** [comment]
Deck isn't really the right place to look for this for the kubernetes deployment at least, considering how often sinker runs, the best places are testgrid and gubernator. Deck is really best at recently run jobs.

More filtering options could be handy though.

**Comment by kargakis** [comment]
Gubernator was the first place that @mfojtik was looking at so I am fine with it too.

**Comment by kargakis** [comment]
I've made this a catch-all issue and need others to weigh in about what's the best place to do it.

cc: @stevekuznetsov @rmmh @michelle192837

**Comment by mfojtik** [comment]
Yeah, i'm fine with whatever tool I can use. It is very useful to see the runs of the same job per-branch, so I can see if the job is broken just for me or for other PR's into that branch.

**Comment by stevekuznetsov** [comment]
We're recording the Prow job configuration but I don't think k8s jobs are, so Gubernator would need more data to make that decision. One of the natural places for this is where the data is declared, and that's from Deck. We could probably add best-effort filtering in Gubernator as well.

**Comment by BenTheElder** [comment]
> We're recording the Prow job configuration but I don't think k8s jobs are, so Gubernator would need more data to make that decision. One of the natural places for this is where the data is declared, and that's from Deck. We could probably add best-effort filtering in Gubernator as well.

With ditching Jenkins I'd actually love to record these somewhere Gubernator could read them, it would be great to look back on a job and be able to completely recreate it.

**Comment by rmmh** [comment]
Could this be a periodic BigQuery job? That's the best source of all the test results.

**Comment by stevekuznetsov** [comment]
Would be nice to not need to bring in more (heavyweight) machinery to expose something in the views we currently use to look at job status and history (outside of TestGrid)

**Comment by kargakis** [comment]
Older request: https://github.com/kubernetes/test-infra/issues/3449

**Comment by BenTheElder** [comment]
/cc @qhuynh96 
who is currently looking at replacing some of the existing dropdowns with fuzzy-search / dropdown upgrades

**Comment by sebastienvas** [comment]
I think it would be pretty useful to show branch for PR like we do for postsubmit. Filtering per branch is also very useful when wanting to know if a job is failing on multiple PRs.

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
I'm taking no action on this in ~2 years as a sign that it's no longer that important
/remove-area gubernator
we're not doing new development for gubernator

/area prow/deck
I think this could make deck more useful.

Alternatively, maybe we could consider renaming all branch-specific presubmits something different.  Having jobs named the same makes it difficult to effectively triage in multiple places (testgrid, spyglass job history, triage.k8s.io)

**Comment by spiffxp** [comment]
/close
I'm going to close this in favor of https://github.com/kubernetes/test-infra/issues/18842
