### ISSUE TITLE
Use BUILD.bazel instead of BUILD

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#6157]
MacOS does not handle `./BUILD` and `./build/` existing in the same dir, such as:

```
vendor/golang.org/x/text/collate/BUILD
vendor/golang.org/x/text/collate/build/colelem.go
```

**Comment by ixdy** [comment]
This should be as easy as moving all existing `BUILD` files to `BUILD.bazel` and updating `hack/{update,verify}-bazel.sh` to tell gazelle to use `BUILD.bazel` instead of `BUILD`.

**Comment by fejta** [comment]
https://github.com/bazelbuild/bazel-gazelle/blob/master/cmd/gazelle/fix-update.go#L188

**Comment by ixdy** [comment]
yeah, just switch the order of the values in the flag here:
https://github.com/kubernetes/test-infra/blob/c9d58f244800f47c5dd97ae21d3f281151317cda/hack/update-bazel.sh#L49

and here:
https://github.com/kubernetes/test-infra/blob/c9d58f244800f47c5dd97ae21d3f281151317cda/hack/verify-bazel.sh#L36

**Comment by ixdy** [comment]
(or even just remove those flags, since the default does what we want)
