### ISSUE TITLE
aws go library is broken

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#6173]
https://github.com/kubernetes/test-infra/commit/1906d620bde1d4096fef17baf82bd4ed9b98fbec
as part of https://github.com/kubernetes/test-infra/pull/6141

Removed parts of the aws-go library.  This library was just added for https://github.com/kubernetes/test-infra/pull/6113.  

I am going to see if I can add it back, but I am not holding my breath.  I had a ton of problems adding the library myself, and @BenTheElder ended up doing it for me.

I am trying to get HA etcd testing up and running, how can we get the library back?  
/cc @fejta @BenTheElder 

Thanks

**Comment by chrislovecnm** [comment]
Nope, I tried to use dep to add the library and I am jammed again.  Sorry to bug you guys, but what options do I have?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/6101#issuecomment-355795491 for how I previously added it.

**Comment by chrislovecnm** [comment]
@BenTheElder maybe it is because my mac os is so old, but that is not working.  I am going to steal your SHA and apply it

**Comment by chrislovecnm** [comment]
/close

This is fixed
