### ISSUE TITLE
Too long master pd names:

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#619]
I saw a failure: `./hack/e2e-internal/../../cluster/../cluster/gce/../../cluster/gce/../../cluster/../cluster/../cluster/../cluster/gce/util.sh: line 1194: local: `replica-pd=k6k-e2e-agent-pr-30-0-master-pd': not a valid identifier
`
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/33090/kubernetes-pull-build-test-kubemark-e2e-gce/753/

My guess is that the name is just too long. @kubernetes/test-infra-maintainers @jszczepkowski

**Comment by quinton-hoole** [comment]
This bug is fixed in head.
See recent PR by colhom@
