### ISSUE TITLE
How can I add a new package in an existing dependency?

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6198]
I am trying to add `k8s.io/apimachinery/pkg/apis/meta/v1` in order to make `test-infra`able to use generated informers but I am stumbling across various issues when trying to add the new package with `dep`.

Initially, `dep` complains that I cannot add the package because it already exists.
```
dep ensure -add k8s.io/apimachinery
nothing to -add, k8s.io/apimachinery is already in Gopkg.toml and the project's direct imports or required list
```
At this point, it's unclear what's the right step. Remove the dependency from `Gopkg.toml`, retry `dep ensure`, and `dep ensure -add k8s.io/apimachinery`? What about `Gopkg.lock`? Also what's the case with all those `test` files imported by `dep`? I know that `dep` includes them, `godep` wasn't. Did we remove them manually?

@cblecker @BenTheElder @ixdy

**Comment by kargakis** [comment]
> Also what's the case with all those test files imported by dep? I know that dep includes them, godep wasn't. Did we remove them manually?

Now I see that there are removed during `hack/update-bazel.sh`.

**Comment by stevekuznetsov** [comment]
/cc @sttts @deads2k 

One of y'all has probably done this already in a different repo?

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/test-infra/issues/5488 for the tests, we're waiting on `dep` to fix this, but in the meantime `hack/update-bazel.sh` handles this since it was already in the workflow after updating deps.

**Comment by deads2k** [comment]
> /cc @sttts @deads2k
> 
> One of y'all has probably done this already in a different repo?

We use glide downstream.  @sttts has been experimenting with glide, but as I recall there used to be some pretty severe issues using it to vendor k8s libraries.
