### ISSUE TITLE
/release-note-none ignored if specified on PR description

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/test-infra#6208]
`/release-note-none` works only if it's specified on a comment, not the initial PR description.

Example: https://github.com/kubernetes/kubernetes/pull/58030

I submitted this PR with /release-note-none label, but it got ignored and k8s-ci-robot labeled the PR with `do-not-merge/release-note-label-needed`.

Once I left a comment with /release-note-none, things worked as expected.

**Comment by BenTheElder** [comment]
FWIW if you use the PR template when authoring a PR body you have a section at the end that prompts for:

**Release note:**

```
NONE
```

Which works as-intended AFAIK.

/assign @cjwagner

**Comment by cblecker** [comment]
Using the PR template is preferred for sure if you are the PR author.
