### ISSUE TITLE
Setup merge automation for all kubernetes repos

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#6227]
/assign
/area prow
/sig contributor-experience
I've been doing this organically, here's an umbrella issue to keep track

The general process I've been following lately is:
- File an issue with these steps
- Create/update an OWNERS_ALIAS file that names the existing teams that have write/admin access to the repo
- Create/update an OWNERS file with approvers based on the write/admin access teams
- Configure prow to turn on the "approval" plugin for this repo
- Configure prow/tide to include this repo in the tide query
- Hold off if there are any objections or special cases

---
Issues used to add repos in the past:
- https://github.com/kubernetes/website/issues/6906
- https://github.com/kubernetes/sig-release/issues/44
- https://github.com/kubernetes/kube-deploy/issues/480
- https://github.com/kubernetes/ingress-nginx/issues/1895
- https://github.com/helm/helm/issues/3333 (did not proceed)
- https://github.com/kubernetes/dashboard/issues/2747
---
EDIT: as of 2018-09-17

| org/repo | in sigs.yaml? | has owners? | has approve? | in tide? | branch protected? |
| -------- | ------------- | ----------- | ------------ | -------- | ----------------- |
| [kubernetes/kubelet](https://github.com/kubernetes/kubelet) | missing |  |  |  |  |
| [kubernetes/kube-scheduler](https://github.com/kubernetes/kube-scheduler) | missing |  |  |  |  |
| [kubernetes/kube-proxy](https://github.com/kubernetes/kube-proxy) | missing |  |  |  |  |
| [kubernetes/kube-controller-manager](https://github.com/kubernetes/kube-controller-manager) | missing |  |  |  |  |
| [kubernetes/cluster-bootstrap](https://github.com/kubernetes/cluster-bootstrap) | missing |  |  |  |  |
| [kubernetes/cloud-provider-alibaba-cloud](https://github.com/kubernetes/cloud-provider-alibaba-cloud) | missing |  |  |  |  |
| [kubernetes-sigs/aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) | missing |  |  |  |  |
| [kubernetes/website](https://github.com/kubernetes/website) |  |  |  |  |  |
| [kubernetes/utils](https://github.com/kubernetes/utils) |  |  |  |  |  |
| [kubernetes/test-infra](https://github.com/kubernetes/test-infra) |  |  |  |  |  |
| [kubernetes/steering](https://github.com/kubernetes/steering) |  |  |  |  |  |
| [kubernetes/sig-release](https://github.com/kubernetes/sig-release) |  |  |  |  |  |
| [kubernetes/sample-controller](https://github.com/kubernetes/sample-controller) |  |  |  |  |  |
| [kubernetes/sample-cli-plugin](https://github.com/kubernetes/sample-cli-plugin) |  |  |  |  |  |
| [kubernetes/sample-apiserver](https://github.com/kubernetes/sample-apiserver) |  |  |  |  |  |
| [kubernetes/repo-infra](https://github.com/kubernetes/repo-infra) |  |  |  |  |  |
| [kubernetes/release](https://github.com/kubernetes/release) |  |  |  |  |  |
| [kubernetes/publishing-bot](https://github.com/kubernetes/publishing-bot) |  |  |  |  |  |
| [kubernetes/perf-tests](https://github.com/kubernetes/perf-tests) |  |  |  |  |  |
| [kubernetes/org](https://github.com/kubernetes/org) |  |  |  |  |  |
| [kubernetes/node-problem-detector](https://github.com/kubernetes/node-problem-detector) |  |  |  |  |  |
| [kubernetes/minikube](https://github.com/kubernetes/minikube) |  |  |  |  |  |
| [kubernetes/metrics](https://github.com/kubernetes/metrics) |  |  |  |  |  |
| [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) |  |  |  |  |  |
| [kubernetes/kubernetes-template-project](https://github.com/kubernetes/kubernetes-template-project) |  |  |  |  |  |
| [kubernetes/kubernetes-anywhere](https://github.com/kubernetes/kubernetes-anywhere) |  |  |  |  |  |
| [kubernetes/kubectl](https://github.com/kubernetes/kubectl) |  |  |  |  |  |
| [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm) |  |  |  |  |  |
| [kubernetes/kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) |  |  |  |  |  |
| [kubernetes/kube-openapi](https://github.com/kubernetes/kube-openapi) |  |  |  |  |  |
| [kubernetes/kube-deploy](https://github.com/kubernetes/kube-deploy) |  |  |  |  |  |
| [kubernetes/kube-aggregator](https://github.com/kubernetes/kube-aggregator) |  |  |  |  |  |
| [kubernetes/kops](https://github.com/kubernetes/kops) |  |  |  |  |  |
| [kubernetes/kompose](https://github.com/kubernetes/kompose) |  |  |  |  |  |
| [kubernetes/k8s.io](https://github.com/kubernetes/k8s.io) |  |  |  |  |  |
| [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) |  |  |  |  |  |
| [kubernetes/ingress-gce](https://github.com/kubernetes/ingress-gce) |  |  |  |  |  |
| [kubernetes/heapster](https://github.com/kubernetes/heapster) |  |  |  |  |  |
| [kubernetes/git-sync](https://github.com/kubernetes/git-sync) |  |  |  |  |  |
| [kubernetes/gengo](https://github.com/kubernetes/gengo) |  |  |  |  |  |
| [kubernetes/frakti](https://github.com/kubernetes/frakti) |  |  |  |  |  |
| [kubernetes/federation](https://github.com/kubernetes/federation) |  |  |  |  |  |
| [kubernetes/features](https://github.com/kubernetes/features) |  |  |  |  |  |
| [kubernetes/examples](https://github.com/kubernetes/examples) |  |  |  |  |  |
| [kubernetes/dns](https://github.com/kubernetes/dns) |  |  |  |  |  |
| [kubernetes/dashboard](https://github.com/kubernetes/dashboard) |  |  |  |  |  |
| [kubernetes/csi-api](https://github.com/kubernetes/csi-api) |  |  |  |  |  |
| [kubernetes/contrib](https://github.com/kubernetes/contrib) |  |  |  |  |  |
| [kubernetes/community](https://github.com/kubernetes/community) |  |  |  |  |  |
| [kubernetes/code-generator](https://github.com/kubernetes/code-generator) |  |  |  |  |  |
| [kubernetes/cluster-registry](https://github.com/kubernetes/cluster-registry) |  |  |  |  |  |
| [kubernetes/cloud-provider](https://github.com/kubernetes/cloud-provider) |  |  |  |  |  |
| [kubernetes/cloud-provider-vsphere](https://github.com/kubernetes/cloud-provider-vsphere) |  |  |  |  |  |
| [kubernetes/cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) |  |  |  |  |  |
| [kubernetes/cloud-provider-gcp](https://github.com/kubernetes/cloud-provider-gcp) |  |  |  |  |  |
| [kubernetes/cloud-provider-azure](https://github.com/kubernetes/cloud-provider-azure) |  |  |  |  |  |
| [kubernetes/cloud-provider-aws](https://github.com/kubernetes/cloud-provider-aws) |  |  |  |  |  |
| [kubernetes/client-go](https://github.com/kubernetes/client-go) |  |  |  |  |  |
| [kubernetes/cli-runtime](https://github.com/kubernetes/cli-runtime) |  |  |  |  |  |
| [kubernetes/autoscaler](https://github.com/kubernetes/autoscaler) |  |  |  |  |  |
| [kubernetes/apiserver](https://github.com/kubernetes/apiserver) |  |  |  |  |  |
| [kubernetes/apimachinery](https://github.com/kubernetes/apimachinery) |  |  |  |  |  |
| [kubernetes/apiextensions-apiserver](https://github.com/kubernetes/apiextensions-apiserver) |  |  |  |  |  |
| [kubernetes/api](https://github.com/kubernetes/api) |  |  |  |  |  |
| [kubernetes-sigs/testing_frameworks](https://github.com/kubernetes-sigs/testing_frameworks) |  |  |  |  |  |
| [kubernetes-sigs/structured-merge-diff](https://github.com/kubernetes-sigs/structured-merge-diff) |  |  |  |  |  |
| [kubernetes-sigs/sig-storage-lib-external-provisioner](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner) |  |  |  |  |  |
| [kubernetes-sigs/poseidon](https://github.com/kubernetes-sigs/poseidon) |  |  |  |  |  |
| [kubernetes-sigs/kustomize](https://github.com/kubernetes-sigs/kustomize) |  |  |  |  |  |
| [kubernetes-sigs/kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) |  |  |  |  |  |
| [kubernetes-sigs/kubeadm-dind-cluster](https://github.com/kubernetes-sigs/kubeadm-dind-cluster) |  |  |  |  |  |
| [kubernetes-sigs/kube-storage-version-migrator](https://github.com/kubernetes-sigs/kube-storage-version-migrator) |  |  |  |  |  |
| [kubernetes-sigs/kube-batch](https://github.com/kubernetes-sigs/kube-batch) |  |  |  |  |  |
| [kubernetes-sigs/kind](https://github.com/kubernetes-sigs/kind) |  |  |  |  |  |
| [kubernetes-sigs/gcp-filestore-csi-driver](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver) |  |  |  |  |  |
| [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) |  |  |  |  |  |
| [kubernetes-sigs/federation-v2](https://github.com/kubernetes-sigs/federation-v2) |  |  |  |  |  |
| [kubernetes-sigs/cri-tools](https://github.com/kubernetes-sigs/cri-tools) |  |  |  |  |  |
| [kubernetes-sigs/cri-o](https://github.com/kubernetes-sigs/cri-o) |  |  |  |  |  |
| [kubernetes-sigs/controller-tools](https://github.com/kubernetes-sigs/controller-tools) |  |  |  |  |  |
| [kubernetes-sigs/controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) |  |  |  |  |  |
| [kubernetes-sigs/contributor-site](https://github.com/kubernetes-sigs/contributor-site) |  |  |  |  |  |
| [kubernetes-sigs/contributor-playground](https://github.com/kubernetes-sigs/contributor-playground) |  |  |  |  |  |
| [kubernetes-sigs/cluster-api](https://github.com/kubernetes-sigs/cluster-api) |  |  |  |  |  |
| [kubernetes-sigs/cluster-api-provider-vsphere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere) |  |  |  |  |  |
| [kubernetes-sigs/cluster-api-provider-openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack) |  |  |  |  |  |
| [kubernetes-sigs/cluster-api-provider-gcp](https://github.com/kubernetes-sigs/cluster-api-provider-gcp) |  |  |  |  |  |
| [kubernetes-sigs/cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws) |  |  |  |  |  |
| [kubernetes-sigs/aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator) |  |  |  |  |  |
| [kubernetes-sigs/aws-encryption-provider](https://github.com/kubernetes-sigs/aws-encryption-provider) |  |  |  |  |  |
| [kubernetes-sigs/aws-alb-ingress-controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller) |  |  |  |  |  |
| [kubernetes-sigs/architecture-tracking](https://github.com/kubernetes-sigs/architecture-tracking) |  |  |  |  |  |
| [kubernetes-sigs/application](https://github.com/kubernetes-sigs/application) |  |  |  |  |  |
| [kubernetes-incubator/spartakus](https://github.com/kubernetes-incubator/spartakus) |  |  |  |  |  |
| [kubernetes-incubator/service-catalog](https://github.com/kubernetes-incubator/service-catalog) |  |  |  |  |  |
| [kubernetes-incubator/rktlet](https://github.com/kubernetes-incubator/rktlet) |  |  |  |  |  |
| [kubernetes-incubator/reference-docs](https://github.com/kubernetes-incubator/reference-docs) |  |  |  |  |  |
| [kubernetes-incubator/node-feature-discovery](https://github.com/kubernetes-incubator/node-feature-discovery) |  |  |  |  |  |
| [kubernetes-incubator/nfs-provisioner](https://github.com/kubernetes-incubator/nfs-provisioner) |  |  |  |  |  |
| [kubernetes-incubator/metrics-server](https://github.com/kubernetes-incubator/metrics-server) |  |  |  |  |  |
| [kubernetes-incubator/kubespray](https://github.com/kubernetes-incubator/kubespray) |  |  |  |  |  |
| [kubernetes-incubator/kube-aws](https://github.com/kubernetes-incubator/kube-aws) |  |  |  |  |  |
| [kubernetes-incubator/ip-masq-agent](https://github.com/kubernetes-incubator/ip-masq-agent) |  |  |  |  |  |
| [kubernetes-incubator/external-storage](https://github.com/kubernetes-incubator/external-storage) |  |  |  |  |  |
| [kubernetes-incubator/external-dns](https://github.com/kubernetes-incubator/external-dns) |  |  |  |  |  |
| [kubernetes-incubator/descheduler](https://github.com/kubernetes-incubator/descheduler) |  |  |  |  |  |
| [kubernetes-incubator/custom-metrics-apiserver](https://github.com/kubernetes-incubator/custom-metrics-apiserver) |  |  |  |  |  |
| [kubernetes-incubator/cluster-proportional-vertical-autoscaler](https://github.com/kubernetes-incubator/cluster-proportional-vertical-autoscaler) |  |  |  |  |  |
| [kubernetes-incubator/cluster-proportional-autoscaler](https://github.com/kubernetes-incubator/cluster-proportional-autoscaler) |  |  |  |  |  |
| [kubernetes-incubator/cluster-capacity](https://github.com/kubernetes-incubator/cluster-capacity) |  |  |  |  |  |
| [kubernetes-incubator/bootkube](https://github.com/kubernetes-incubator/bootkube) |  |  |  |  |  |
| [kubernetes-incubator/apiserver-builder](https://github.com/kubernetes-incubator/apiserver-builder) |  |  |  |  |  |
| [kubernetes-csi/livenessprobe](https://github.com/kubernetes-csi/livenessprobe) |  |  |  |  |  |
| [kubernetes-csi/kubernetes-csi.github.io](https://github.com/kubernetes-csi/kubernetes-csi.github.io) |  |  |  |  |  |
| [kubernetes-csi/kubernetes-csi-migration-library](https://github.com/kubernetes-csi/kubernetes-csi-migration-library) |  |  |  |  |  |
| [kubernetes-csi/external-snapshotter](https://github.com/kubernetes-csi/external-snapshotter) |  |  |  |  |  |
| [kubernetes-csi/external-provisioner](https://github.com/kubernetes-csi/external-provisioner) |  |  |  |  |  |
| [kubernetes-csi/external-attacher](https://github.com/kubernetes-csi/external-attacher) |  |  |  |  |  |
| [kubernetes-csi/drivers](https://github.com/kubernetes-csi/drivers) |  |  |  |  |  |
| [kubernetes-csi/driver-registrar](https://github.com/kubernetes-csi/driver-registrar) |  |  |  |  |  |
| [kubernetes-csi/docs](https://github.com/kubernetes-csi/docs) |  |  |  |  |  |
| [kubernetes-csi/csi-test](https://github.com/kubernetes-csi/csi-test) |  |  |  |  |  |
| [kubernetes-csi/csi-lib-iscsi](https://github.com/kubernetes-csi/csi-lib-iscsi) |  |  |  |  |  |
| [kubernetes-csi/csi-lib-fc](https://github.com/kubernetes-csi/csi-lib-fc) |  |  |  |  |  |
| [kubernetes-csi/csi-lib-common](https://github.com/kubernetes-csi/csi-lib-common) |  |  |  |  |  |
| [kubernetes-csi/csi-driver-nfs](https://github.com/kubernetes-csi/csi-driver-nfs) |  |  |  |  |  |
| [kubernetes-csi/csi-driver-iscsi](https://github.com/kubernetes-csi/csi-driver-iscsi) |  |  |  |  |  |
| [kubernetes-csi/csi-driver-host-path](https://github.com/kubernetes-csi/csi-driver-host-path) |  |  |  |  |  |
| [kubernetes-csi/csi-driver-flex](https://github.com/kubernetes-csi/csi-driver-flex) |  |  |  |  |  |
| [kubernetes-csi/csi-driver-cinder](https://github.com/kubernetes-csi/csi-driver-cinder) |  |  |  |  |  |
| [kubernetes-client/ruby](https://github.com/kubernetes-client/ruby) |  |  |  |  |  |
| [kubernetes-client/python](https://github.com/kubernetes-client/python) |  |  |  |  |  |
| [kubernetes-client/python-base](https://github.com/kubernetes-client/python-base) |  |  |  |  |  |
| [kubernetes-client/javascript](https://github.com/kubernetes-client/javascript) |  |  |  |  |  |
| [kubernetes-client/java](https://github.com/kubernetes-client/java) |  |  |  |  |  |
| [kubernetes-client/haskell](https://github.com/kubernetes-client/haskell) |  |  |  |  |  |
| [kubernetes-client/go](https://github.com/kubernetes-client/go) |  |  |  |  |  |
| [kubernetes-client/go-base](https://github.com/kubernetes-client/go-base) |  |  |  |  |  |
| [kubernetes-client/gen](https://github.com/kubernetes-client/gen) |  |  |  |  |  |
| [kubernetes-client/csharp](https://github.com/kubernetes-client/csharp) |  |  |  |  |  |

---
[1] - staging repos live in [kubernetes/kubernetes/staging](https://git.k8s.io/kubernetes/staging) and so use whatever merge automation [kuberentes/kubernetes](https://github.com/kubernetes/kubernetes) has

**Comment by mattfarina** [comment]
Why should all the repos have or use merge automation? What's the benefit for those that aren't using it today?

**Comment by stevekuznetsov** [comment]
> Why should all the repos have or use merge automation?

@mattfarina this was a conclusion that the steering committee reached when trying to define what constituted Kubernetes repos. Not sure if that doc got sent to the dev list, but here is a link: https://docs.google.com/document/d/1yauW9zMtWgXN8xh4q6144B2xBTPuIOLGc0L6aQPMj1I/edit?usp=sharing

**Comment by fejta** [comment]
Benefit is a consistent experience between repos, which makes it easier to move around between them efficiently.

**Comment by jberkus** [comment]
The other benefit is that it means that all repos can be included in the general release process where required.  Realistically, the release team cannot manage or even monitor repos which use a completely different workflow and labels from everything else.  Now, some sub-projects will never have this concern, but a lot will.

**Comment by mattfarina** [comment]
@jberkus why would everything use the general release process? For example, there is talk of moving kubectl out of k8s and having an independent release process and timing from k8s. It would decouple them. What benefit would kubectl have to use the general release process meant for something different?

@fejta Three things come up for consistency.

1. We have issues with contributor experience. If we have a consistent experience that's hard that won't help.
1. How many people move from repo to repo? How much moving around is there? Is it a core group of people or most people? Have we looked at how much of a deal that is? Without knowing that how can we prioritize it.
1. Consistency doesn't allow for innovation. If everyone needs to use the same tooling how can someone go innovate a better way to do something? The first mover wins. Look at Netflix. They don't enforce tools. Instead it's self service. Someone can go their own route and those someones become the new self-service options.

@stevekuznetsov As I understand it, the tooling parts were added after the steering committee reached conclusions in that doc. That was an addition after the fact.

In any case, because some group concluded it is not a good justification. People should be able to answer my original questions in a positive way for people.

And, we should be able to go back and audit the conclusions and reasons for what the steering committee went with later. Things change and those things may not apply later.

**Comment by jberkus** [comment]
@mattfarina if the release process is completely decoupled *and* the subproject isn't interested in using the same release tools, then of course that doesn't apply.  However, right now we have the opposite: several repos who *do* participate in the general release process but not with the same labelling or automation.  That's why I'm saying that those two things need to be tied together.

**Comment by BenTheElder** [comment]
thanks @cblecker. for anyone following along, @spiffxp is still on this but is on extended OOO. I imagine he'll continue this when he gets back

**Comment by spiffxp** [comment]
/lifecycle frozen
Yeah I'll update this at some point, need to include all repos across all orgs.

**Comment by spiffxp** [comment]
Related, I'm making sure all repos have OWNERS files, which sets the stage for them to use /approve (and thus tide) https://github.com/kubernetes/community/issues/1721

**Comment by spiffxp** [comment]
Related, I'm making sure all repos live inside of sigs.yaml in one for or another.  I anticipate this can help us head towards a sig-driven peribolos config https://github.com/kubernetes/community/issues/2464

**Comment by stevekuznetsov** [comment]
`tide` doesn't require `/approve` FWIW, do all repos need it?

**Comment by spiffxp** [comment]
True, I guess the reason I use it as a precondition is that any org member can `/lgtm`, while the use of `/approve` ensures there aren't drive-by merges

**Comment by spiffxp** [comment]
/close
This is now done
