### ISSUE TITLE
Configurable stale timeframes

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/test-infra#6240]
This is a feature request.

Stale issue handing automation is quite useful. Especially with the number of stale issues there really are on some repos.

But, the timeframes aren't always optimal. For example, the charts repo has long had a stale policy with a different timefame. We were looking into different automation to handle our own stale issues.

What we would really like is the ability to set a custom stale timeframe.

**Comment by kargakis** [comment]
cc @fejta

**Comment by stevekuznetsov** [comment]
We'd need to re-architect the plugin config structure to have per-repo configurations

**Comment by bacongobbler** [comment]
> For example, the charts repo has long had a stale policy with a different timefame.

Or in another similar case (helm), we have design proposals in issues so we don't want a stale policy at all... Or at least a *much* longer time frame than 3 months.

It would've been better if this had been rolled out as an opt-in feature, tbh. :(

**Comment by mattfarina** [comment]
We'd wanted this for some Helm related projects. Since Helm has moved elsewhere I think we can close this unless someone else wants to open this back up and work on it.

/close
