### ISSUE TITLE
Issues should not go stale if they have been referenced.

### ISSUE THREAD

**Issue by dashpole** [kubernetes/test-infra#6267]
A common pattern is for issues to be created describing a problem, and then for many PRs to be created to solve them.
If possible, the bot should count an issue being referenced as "activity" for the purpose of measuring how long they have been inactive.

An example PR is here: https://github.com/kubernetes/kubernetes/issues/53902#issuecomment-357108623
The PR was created a long time ago, but since then has been referenced by a PR, and another issue.

**Comment by fejta** [comment]
The expectation is that issues receive an update once a quarter.

When you add a comment in issue A that links to issue B, github only considers issue A to have a new last modified time.

Please do something on issue B at least once a release -- such as summarizing the activity on the linked issues as it relates to this issue.

**Comment by dashpole** [comment]
Ahh, I didn't realize the "last modified time" came from github.  In that case, no need to make any changes!
