### ISSUE TITLE
kubernetes-cross is not running in batch

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#6277]
for example, https://github.com/kubernetes/kubernetes/pull/58113 is not merged after a day
cross build is required now but not triggered in batch mode
cc @bowei 

/assign @BenTheElder

**Comment by BenTheElder** [comment]
We've been debating how to handle this offline. Still reaching consensus.

**Comment by BenTheElder** [comment]
Looks like the most recent batch (#58089, #58113, #58187, #46245, #56509) kicked off pull-kubernetes-cross https://prow.k8s.io/?type=batch

This should be fine now.
