### ISSUE TITLE
Support adding arbitrary metadata as additional header rows

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#628]
Aka if my tests have a `gce_node_image` metadata key as in https://github.com/kubernetes/test-infra/pull/626 I should be able to setup my tab to have the following:

```
  column_header:
  - configuration_value: Commit
  - configuration_value: gce_node_image
```

So now each column has 4 header rows: start time, build number, commit id and the new gce_node_image

**Comment by krzyzacy** [comment]
so it did not work when you have multiple column_header?

**Comment by krzyzacy** [comment]
Okay it indeed did not work ( sad face
Maybe the proto was not set up properly, I will take a deeper look into it.

**Comment by fejta** [comment]
Dup of https://github.com/kubernetes/test-infra/issues/544
