### ISSUE TITLE
Create ingress project pool for ingress jobs

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#6284]
From https://github.com/kubernetes/test-infra/pull/6282, we will be adding many more test cases for ingress, which requires project to have lots more quota on backend service and others. As suggested in https://github.com/kubernetes/test-infra/pull/6282#issuecomment-357398050, we can create an ingress project pool specifically for ingress jobs instead of adding hardcoded project name.

/assign 
cc @rramkumar1

**Comment by krzyzacy** [comment]
done
