### ISSUE TITLE
blunderbuss requests reviews by too many folks

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6295]
```
{"author":"bparees","event-GUID":"b2d42880-fae6-11e7-93d7-e39713e58daa","event-type":"pull_request","level":"info","msg":"Requesting reviews from users [csrwng dinhxuanvu jcantrill jim-minter kargakis soltysh].","org":"openshift","plugin":"blunderbuss","pr":18130,"repo":"origin","time":"2018-01-16T17:57:26Z","url":"https://github.com/openshift/origin/pull/18130"},
```
Happened in https://github.com/openshift/origin/pull/18130

We haven't configured any specific # of people in the plugin config and IIRC the default is 2.

/area prow
/kind bug

@cjwagner

**Comment by cjwagner** [comment]
I think this is WAI.
Blunderbuss was recently changed to try to select a unique reviewer from the leaf OWNERS file for each changed file and only request additional reviewers if the minimum reviewer count (2) has not been met yet. This selection process is better because it favors leaf reviewers over root reviewers and allows more reviewers to be requested if a PR is affected by a large number of OWNERS files.

**Comment by cjwagner** [comment]
ref https://github.com/kubernetes/test-infra/pull/5960

**Comment by kargakis** [comment]
What's the use of [request_count](https://github.com/kubernetes/test-infra/blob/850b013acec11b8ae0826ee3914990105195333d/prow/plugins/plugins.go#L188) then if the algorithm does not respect it?

**Comment by kargakis** [comment]
Hrm, now I reread 

> only request additional reviewers if the minimum reviewer count (2) has not been met yet

We should probably document this. Also, I would like to explore an option that actually gates the number of review requests. We have been getting a lot of them downstream but they are mostly spamming people (I doubt we have a PR where all requested reviewers actually did a review).

**Comment by cjwagner** [comment]
> Also, I would like to explore an option that actually gates the number of review requests.

SGTM. The blunderbuss reviewer selection logic definitely needs to be more configurable, many of the repos we have enabled it on have requested customized behavior.

**Comment by kargakis** [comment]
Seems like an issue in the new algo

/reopen
/assign cjwagner
