### ISSUE TITLE
label_sync isn't setting labels on kubernetes/kubernetes-template-project

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#6296]
https://github.com/kubernetes/kubernetes-template-project/labels

I'm looking specifically for the `committee/steering` label

I'm guessing this is the cron job responsible for running label_sync: https://github.com/kubernetes/test-infra/blob/master/label_sync/cluster/label_sync_cron_job.yaml

Which leads me to believe it should be settings labels on all repos in the kubernetes org, and that this is the `labels.yaml` being used: https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml

Which contains the the `committee/steering` label: https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml#L23-L24

What's going wrong here?

**Comment by fejta** [comment]
Probably haven't pushed labels.yaml to the cluster since https://github.com/kubernetes/test-infra/commit/93344a5b1c51b836d6aa9a76fda853a4cfebd26a#diff-7f06d832469dae8ca707e5cbd52807f6 was merged

**Comment by spiffxp** [comment]
What's the process to get an updated labels.yaml pushed, should I be bugging a member of test-infra with access to the cluster anytime a relevant PR is merged?

**Comment by BenTheElder** [comment]
@spiffxp looks like it's `make -C label_sync update-config` to push the updated config map which depends on the credentials so.. yes? I'll push the config.

**Comment by BenTheElder** [comment]
pushed the configmap from `ce7f426c8020d5ac2b686493037a394de8a05e81`

**Comment by spiffxp** [comment]
/close
oh yeah this is definitely done, the `label-config` configmap is now auto-updated as of #6634
