### ISSUE TITLE
Update bazelbuild image to include GOPATH

### ISSUE THREAD

**Issue by font** [kubernetes/test-infra#6304]
The current [`bazelbuild` image](https://github.com/kubernetes/test-infra/blob/4850d1235187a4dfc312d766625dc1f1fb0cc175/images/bazelbuild/Dockerfile#L1) does not set up a `GOPATH` environment. Normally when using `bazel` commands inside the `bazelbuild` image there isn't any problems. But in the event you want to run an `execute` scenario to run a verify job that uses the `Go` toolchain such as `go list`, `go vet`, etc. without running any bazel commands, you have to setup a temporary directory or `GOPATH` within your verify job in order for it to work.

/cc @BenTheElder @ixdy

**Comment by ixdy** [comment]
Does the bazelbuild image even include the go toolchain?

**Comment by font** [comment]
@BenTheElder @ixdy It does not. That's why I was wondering if this is even the right image we should be using to test an `execute` scenario requiring the go toolchain when we're not requiring any `bazel` commands.

**Comment by font** [comment]
I've switched our one particular pull job to use the `kubekins-e2e` image per @BenTheElder . I'll leave our other pull jobs to continue using the `bazelbuild` image and if/when we get the go toolchain added to it, I'll revert back to `bazelbuild`.

**Comment by BenTheElder** [comment]
I think the go toolchain + bazel is really the kubekins image at the
moment. The bazebuild image is a bit more focused. I don't know that we
should be adding a go toolchain to it.

We probably should (will?) Move towards things always being in a valid
gopath for prow checkouts though. The bootstrap argument `--root=/go/src`
solves this for now with kubekins.
