### ISSUE TITLE
Some boskos projects have legacy networks

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#6308]
The kops GCE job is basically passing now (yay!): https://k8s-testgrid.appspot.com/google-kops-gce#kops-gce

But there are a few failures, and they seem to be because some projects have networks in legacy mode, which aren't supported by kops.  I'm also not sure I should be getting these at all, as they look like specialized boskos projects (e.g. presumably k8s-e2e-gce-scalability has higher limits?)  Is there a way I should be calling boskos specially?

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-gce/3895/build-log.txt :

```
W0116 21:01:30.755] 2018/01/16 21:01:30 main.go:744: provider gce, will acquire resource gce-project from boskos
W0116 21:01:30.755] 2018/01/16 21:01:30 util.go:155: Running: gcloud config set project k8s-jkns-e2e-gce-prl-flaky
```

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-gce/3881/build-log.txt :

```
W0116 13:47:32.331] 2018/01/16 13:47:32 main.go:744: provider gce, will acquire resource gce-project from boskos
W0116 13:47:32.331] 2018/01/16 13:47:32 util.go:155: Running: gcloud config set project k8s-e2e-gce-scalability
```

**Comment by krzyzacy** [comment]
the project picking is fine, the actual scalability job has their own designated projects.

I'm not sure about the legacy network though, maybe it's configurable? cc @MrHohn let be grab a network specialist here

**Comment by MrHohn** [comment]
> But there are a few failures, and they seem to be because some projects have networks in legacy mode

Projects those were created earlier on might have legacy network, quick thoughts for non-specialized projects:
- Replace them with other new projects.
- Or delete the legacy network and create a new "default" network.
