### ISSUE TITLE
Improve /test all logic.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#6346]
`/test all` needs a rework. AlwaysRun jobs shouldn't need to make sure their Trigger regexp matches `/test all`, it is repetitive and prevents us from distinguishing `/test all` from `/test foo` easily.  Instead `/test all` should be recognized as a command and trigger tests in the same way that an `/ok-to-test` command would. We can then simplify the configured job regexps to only match triggers specific to the job instead of matching both job specific and general triggers. The common case of a `/test foo` trigger for a job named `foo` can be defaulted to remove this field from most of the entries in the config.
/assign
/area prow

**Comment by BenTheElder** [comment]
+1 I had a thread with Joe about this at some point. I think he had some
arguments against it but I don't remember them FWIW 🤷‍♂️

**Comment by BenTheElder** [comment]
Ping @spxtr 😁

**Comment by spxtr** [comment]
I don't remember my argument. Are you thinking of my dislike of `/test all` vs `/test-all` (how do we know there's no job named "all"?!)?

**Comment by cjwagner** [comment]
I would prefer `/test-all` too, but I think we will still need to support `/test all` too given that users are already used to that. We could add a presubmit test that ensures there are no presubmit jobs named `all`.

**Comment by cjwagner** [comment]
Unintentional close. I was trying to use a word besides `fix` or `close` but apparently `resolve` is also a keyword.
/shrug

**Comment by BenTheElder** [comment]
@cjwagner assuming we still want this
/remove-lifecycle rotten

**Comment by cjwagner** [comment]
This is already done.
/close
