### ISSUE TITLE
[PR Dashboard] Remove `do-not-merge/hold` issues from attention set

### ISSUE THREAD

**Issue by tallclair** [kubernetes/test-infra#6350]
Items with the label `do-not-merge/hold` should be hidden from the the "Needs Attention" section. Also maybe the `do-not-merge/work-in-progress` label.

**Comment by stevekuznetsov** [comment]
Not entirely certain this always makes sense -- often someone will `/lgtm` and expressly add `/hold` to block merging until someone else looks -- in that case, everyone else _should_ see a PR with `do-not-merge/hold` in their `"Needs Attention"` block. Similarly, kind of the point of opening a WIP pull is to get feedback.

**Comment by fejta** [comment]
My 2c:
* WIP should always require the author's attention
* hold should follow the normal attention flow

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
@rmmh you want to weigh in?
