### ISSUE TITLE
Make it easier to rename status contexts

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6368]
When a status context is renamed in the prow config, everyone has to `/retest` in order to pick up the new context. Also, the old context is not cleaned up unless there is a new push in the PR. In terms of tide, all PRs are removed from the pool. We could potentially provide an option to link new to deprecated contexts and also enhance `/skip` to cleanup deprecated contexts.

/area prow

@spxtr @cjwagner @stevekuznetsov @BenTheElder

**Comment by kargakis** [comment]
cc @smarterclayton

**Comment by cjwagner** [comment]
We use this tool to migrate status contexts when needed: https://github.com/kubernetes/test-infra/tree/master/maintenance/migratestatus

**Comment by kargakis** [comment]
Thanks, migratestatus is what I was looking for
