### ISSUE TITLE
Improve 'repoowners' package and 'approve' plugin performance.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#6404]
The `repoowners` package and specifically the `approve` plugin seem slow right now compared to other plugins. It can take nearly 20 seconds for the `approve` plugin to react to an event. Given that most of the time it takes about 7 seconds for the plugin to respond, the longer delays are likely from the `repoowners` package reloading the OWNERS data for the repo after a cache miss.

- The `repoowners` package can be improved by skipping large directories that don't need to be scanned such as `vendor/`. This is related to #5156 
- The `approve` plugin can be improved by adding cacheing logic to some of the structs in the `approvers` package so that repeated method calls aren't expensive.

/assign
/area prow

**Comment by stevekuznetsov** [comment]
> The repoowners package can be improved by skipping large directories that don't need to be scanned such as vendor/.

One argument I remember hearing -- and why I think ultimately we added a check for org membership and didn't ignore vendor -- was that if someone is active in a repo as well as in a downstream repo that vendors the first, someone changes vendored code, that person is the most appropriate person to vet changes at that point. Skipping owners in `vendor/` effectively gets us back to the "ask Clayton for a review" situation whenever someone touches vendored code.
