### ISSUE TITLE
Possible shared builds Improve shared builds location improvement

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#6407]
- We can potentially run `bazel build //:save_git_version` to get `bazel-genfiles/version` *before* the rest of the build executes, and upload the shared-builds pointer file *before* the build finishes. This should make sure the storage.googleapis.com link is hot by the time the next job runs, but has the downside of pointing to a build that isn't uploaded yet 🤷‍♂️ 

I have a feeling this is worth it to cut down on needing to retry fetching that file in the next job.

thoughts @ixdy?

/area scenarios
FYI @dims @luxas

**Comment by BenTheElder** [comment]
For context the bazel build is essentially uploaded at `<prefix>/$(cat bazel-genfiles/version)` where `prefix` comes from the `--gcs=` scenario flag.

**Comment by BenTheElder** [comment]
cc @cjwagner xref #5922

**Comment by dims** [comment]
@BenTheElder sounds better then me running "/test all" and crossing my fingers :)

**Comment by BenTheElder** [comment]
@dims likely you'd see the same results without #5922, we seem to mostly not be hitting the retry logic unless we're running a test against a commit that the parent job hasn't run for.

**Comment by cjwagner** [comment]
> the downside of pointing to a build that isn't uploaded yet.

We can work around that limitation. SGTM.

**Comment by luxas** [comment]
@BenTheElder @cjwagner is this active anymore?

**Comment by BenTheElder** [comment]
Not at the moment, we've backed off from shared builds [in presubmit] in
favor of the Bazel remote cache, which has the benefit of working well
across unrelated jobs and being more generally useful in cutting build time.

**Comment by luxas** [comment]
Ok, then I guess we should close this...
