### ISSUE TITLE
Search jobs based on any part of the name

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6437]
It would be nice to return search results in deck based on any part of the name. Our jobs are prefixed with long prefixes like `test_pull_request_openshift_origin_JOB_ID` and I would really like to have to type only `JOB_ID` in order to get results for the job I am looking for.

@BenTheElder @qhuynh96 
/area prow
/kind enhancement

**Comment by qhuynh96** [comment]
With the new fuzzy search box, this should be achieve. The code was checked in yesterday but the deck seems not bumped yet.

**Comment by kargakis** [comment]
I have picked #6288 into our fork (https://github.com/openshift/test-infra/commit/d5c4d3977e451fac6208db51970572f65360d701) and deployed it yesterday.

https://deck-ci.svc.ci.openshift.org/

Doesn't work as I would expect though (:/) hence this issue.

**Comment by qhuynh96** [comment]
![kbfonnqwfxo](https://user-images.githubusercontent.com/24363693/35406980-3d9173f4-01bf-11e8-9677-2c41d1b5a5c0.png)

Is this what you meant or something else?

**Comment by kargakis** [comment]
Yeah, what you did does not work for me (I am on Firefox 57). Just tried Chrom and it seems to work fine there.

**Comment by qhuynh96** [comment]
can you hard reset your browser/ clear cache? We did test it on firefox but will re-test it again.

**Comment by kargakis** [comment]
No luck :( Wondering whether this breaks because of my prefs.js configuration 🤔

**Comment by qhuynh96** [comment]
I found a bug.

https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/static/script.js#L259

Missing event parameter. Cant believe it did not break in Chrome. I fix the bug now.

**Comment by stevekuznetsov** [comment]
Can confirm, broken in FF works in Chrome as well

```
$ rpm -q google-chrome-stable
google-chrome-stable-59.0.3071.115-1.x86_64
$ rpm -q firefox
firefox-54.0-2.fc25.x86_64
```
