### ISSUE TITLE
More sophisticated prow GC

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6476]
Everything in prow is GCed today based on a configured duration. We may want to add two more options and keep the last N succeeded and failed prowjobs around.

/area prow
/kind enhancement

**Comment by kargakis** [comment]
Not clear about presubmits, but I think this makes sense for postsubmits/periodics.

**Comment by krzyzacy** [comment]
we keep the last succeeded | failed pod around these days right? we can extended it to prowjobs as well I guess..

cc @cjwagner

**Comment by kargakis** [comment]
> we keep the last succeeded | failed pod around these days right?

No, I think pods are getting cleaned up on a even tighter interval than prowjobs. Since artifacts are persisted in GCS, I don't think we need to persist pods (assuming we redirect prowjob log to use gubernator for complete prowjobs) but it probably makes sense for prowjobs from a UX pov when somebody browses deck.

**Comment by krzyzacy** [comment]
ah, I was referring to something similar to https://github.com/kubernetes/test-infra/pull/4587

**Comment by kargakis** [comment]
Thanks for linking that PR, reminds me that we already do some sort of what I am asking here for making periodics work. Though, I am not sure whether we want to remove the interval-based approach in favor of cron. If we do that, we don't need the changes introduced by #4587, right?

**Comment by BenTheElder** [comment]
Keeping **pods** around is expensive-ish, keeping ProwJobs around is cheap and handy. 
We should also consider persisting these to GCS as an option (perhaps just in addition to tweaking job GC). I think @stevekuznetsov mentioned this recently.

**Comment by stevekuznetsov** [comment]
Working on a controller to push ProwJobs and Pod logs for infra to GCS
