### ISSUE TITLE
prow: deck: plugin help for LGTM/approve is unclear

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#6478]
Right now I see

| Example | Description | Who Can Use | Plugin | 
| - | - | - | - |
| `/approve` `/lgtm` | Approves a pull request | Users listed as 'approvers' in appropriate OWNERS files. | APPROVE |

Does this mean that:
 - `/lgtm` approves a PR?
 - I need to be listed as an `'approver'` in an `OWNER` file to `/lgtm`?

/cc @BenTheElder @cjwagner 
/area prow
/kind bug

**Comment by BenTheElder** [comment]
We should really improve the help text in general and probably put back the usage column as well.

**Comment by cjwagner** [comment]
Yeah, we definitely need to add the `Usage` column back, the examples don't show all the ways the command can be used so the `Usage` info is important. @qhuynh96 

As for `/lgtm` sometimes indicating approval, it shouldn't in my opinion. We should just require that users type 
```
/lgtm
/approve
```
if they really want to LGTM and approve the PR. @spiffxp 
Users currently using `/lgtm` to indicate both LGTM and approval will have to adjust, but I think that splitting up the commands will help reduce confusion a great deal which is probably more valuable.

**Comment by stevekuznetsov** [comment]
Unclear that we need the usage column, what we need is to communicate to the user how to use the commands. `/[un]assign [[@]username...]` is simply not useful at telling me as a user _what_ I can do and _how_ to do it unless I go into a PR an put all the permutations in there.

**Comment by spiffxp** [comment]
/assign @cblecker re: https://github.com/kubernetes/test-infra/pull/7504#discussion_r178626055

also dropping a link to https://github.com/kubernetes/test-infra/issues/6589 because there was lots of discussion on this there too

**Comment by cblecker** [comment]
My comments on this: https://github.com/kubernetes/test-infra/pull/7504#issuecomment-380896258

I don't think this is worth doing, unless we redesign the help page completely. The approve help has been changed to only display the `/approve` command.

**Comment by BenTheElder** [comment]
FWIW this sort of thing might be worth adding in the plugin details [which have a button on the command help page as well], which are normally used to surface configuration specific details per org/repo. (which also might need more emphasis...)
