### ISSUE TITLE
kubetest kops fails on Debian stretch

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#6498]
pip is failing to install aws cli, because it is missing setup tools.  I am wondering if we want to remove the dependency or just  set pip to install setuptools and aws cli.

**Comment by BenTheElder** [comment]
we're installing awscli on the kubekins-e2e image now FWIW (once we bump the images again)

**Comment by chrislovecnm** [comment]
Kubetest uses pip install and it is missing setuptools on the install call. This is probably because stretch is using python3 ... not certain. The call is called regardless of it is installed or not.

We really should get rid of having the cli. I will dig into where it is used once my ha or is in.

**Comment by chrislovecnm** [comment]
Closing this, as I am working on removing the requirement for the aws cli
