### ISSUE TITLE
Make bazel import requirements.txt

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#6502]
Consider using https://github.com/bazelbuild/rules_python for gubernator to make bazel testing work

/assign @rmmh 
/area gubernator

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/4849
/assign

**Comment by BenTheElder** [comment]
I took a stab at this, but only got so far as some of the code relies on appengine libraries internally. The pip rules are quite easy to work with though, might be worth converting our other python stuff at least.

**Comment by rmmh** [comment]
xref: #4301

**Comment by fejta** [comment]
Have you looked at https://github.com/bazelbuild/rules_appengine#py_appengine_binary and py_appengine_test?

**Comment by BenTheElder** [comment]
> Have you looked at https://github.com/bazelbuild/rules_appengine#py_appengine_binary and py_appengine_test?

I don't think I had, actually... That looks useful :man_shrugging:
