### ISSUE TITLE
hack/update-config.sh sometimes appends garbage

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#6550]
I think something goes wrong with the temp file and config_sort running after fixconfig (?)

Need to investigate and fix this. In the meantime if you see random changes at the end of the file just delete them and re-run it.

/kind bug
/assign

**Comment by BenTheElder** [comment]
I haven't seen this since, have you @krzyzacy?

**Comment by krzyzacy** [comment]
not anymore

**Comment by BenTheElder** [comment]
I think we can close this now.
/close
