### ISSUE TITLE
gcloud: command not found

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6561]
```
$ ./prow/bump.sh plank
program: plank
new version: v20180131-446bc46ec-dirty
./prow/bump.sh: line 41: gcloud: command not found
$ which gcloud
alias gcloud='/home/mkargaki/google-cloud-sdk/bin/gcloud'
	~/google-cloud-sdk/bin/gcloud
```
/shrug
@fejta

**Comment by kargakis** [comment]
I've missed discussion, why do we need to pull?

**Comment by BenTheElder** [comment]
@fejta's new bump process works like:

- check out the commit you'd like to bump from (HEAD?)
- push an image for each component you want to bump (automatic date + sha
tag)
- bump them at once (which verifies that the images are pushed for the
current date+sha)
- push the bump commit

Which means only those with access to image pushing can bump..

On Wed, Jan 31, 2018 at 9:24 AM, Michalis Kargakis <notifications@github.com

**Comment by kargakis** [comment]
I have a PR where I am supposed to bump everything (https://github.com/kubernetes/test-infra/pull/6562). What should I do?

**Comment by stevekuznetsov** [comment]
Would love for us to divorce Prow development from Google Prow deployment configuration management once and for all.... y'all should be able to very simply determine the diff from the last time a bump happened to current HEAD and bump as necessary. I wrote a script that did this before.

**Comment by stevekuznetsov** [comment]
The question someone that is managing the Prow deployment for k8s should be answering is:

 - since the last deployed version, what commits went into each component?
 - which of those commits do we want in the new deployment?

In the abstract sense it may not even be appropriate for an external contributor to do the bump as it is not necessarily true that if they make a change to a component that y'all will want to deploy it immediately.

**Comment by kargakis** [comment]
> y'all should be able to very simply determine the diff from the last time a bump happened to current HEAD and bump as necessary

Agreed about splitting prow to its own repo that furthermore does not affect the Google deployment. As someone who is doing rebases of test-infra on top of our fork in order to pick changes, trying to figure out what exactly should I review is a PITA today.

**Comment by BenTheElder** [comment]
> I have a PR where I am supposed to bump everything (#6562). What should I do?

I guess just have one of us bump it? I'm of the opinion that we should remove bumping altogether and always deploy all components from the same commit ...
