### ISSUE TITLE
prow: use options struct pattern for entrypoints

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#6575]
We should use a pattern like:

```go
type options struct {
    data string
}

func (o *options) Validate() error {
    if o.data == "" {
        return errors.New("need non-empty data")
    }
    return nil
}

func bindOptions() *options {
    opt := &options{}
    flag.StringVar(&opt.data, "whatever", ...)
    flag.Parse()
    return opt
}

func main() {
    opt := bindOptions()
    if err := opt.Validate(); err != nil {
        fmt.Printf("invalid options: %s\n", err)
        os.Exit(1)
    }

    ...
}
```

For all of our Prow entrypoints so we can simply unit-test the options validation logic we have in them.

/area prow
/kind enhancement
/assign
/cc @fejta @BenTheElder

**Comment by fejta** [comment]
Should we make this an interface?

**Comment by kargakis** [comment]
Worth cross-checking where kubectl has ended up today since I remember we came up with a similar set of common functions that is used across all commands.

**Comment by kargakis** [comment]
IIRC, there is a `Complete()` func that populates `options`, then a `Validate`, and a `Run` that contains most of the business logic. I remember wanting to put it behind an interface.

**Comment by stevekuznetsov** [comment]
Happy to incrementally improve on this as the changes are rolled out for the other entrypoints. Admittedly it's been a while but the `kubectl` pattern was what this was inspired by.

**Comment by stevekuznetsov** [comment]
I think we did them all?

/close
