### ISSUE TITLE
Shell Color Codes are not removed in the test log.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/test-infra#660]
I remember they didn't present in the log on gcs before.

I don't know what was changed, currently they are everywhere in the test log, which makes it a little inconvenient to debug issues.

Something like this: `[0;32mSUCCESS[0m`

**Comment by ixdy** [comment]
We removed the ANSI color plugin recently, which is probably why.

@spxtr

**Comment by spxtr** [comment]
It might be possible to make gubernator display them properly? @rmmh

**Comment by rmmh** [comment]
Can you give a link to an example where this is a problem?

**Comment by ixdy** [comment]
Any e2e test log. Ginkgo prints out ANSI colors.
