### ISSUE TITLE
Table is not displaying full width 

### ISSUE THREAD

**Issue by katerinapat** [kubernetes/test-infra#6638]
The table in https://prow.k8s.io/command-help.html is not displayed in full width. 

See screenshots below: 

![screenshot from 2018-02-04 14-03-17](https://user-images.githubusercontent.com/3369346/35777875-b6f82a96-09b5-11e8-86c1-826e3d09d612.png)

![screenshot from 2018-02-04 14-02-42](https://user-images.githubusercontent.com/3369346/35777881-be447232-09b5-11e8-9918-ef8ff11bbdce.png)

[link](https://prow.k8s.io/command-help.html?repo=GoogleCloudPlatform%2Fk8s-multicluster-ingress)

**Comment by kargakis** [comment]
/area prow

cc: @qhuynh96 @BenTheElder

**Comment by kargakis** [comment]
I think @katerinapat is already working on a fix

**Comment by qhuynh96** [comment]
It's probably because of setting width to auto:
 https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/static/style.css#L203

I would change it to `width: calc(100% - 16px)` . @BenTheElder  WDYT?

@katerinapat are you on it? if not I can be

**Comment by katerinapat** [comment]
@qhuynh96, I reported and I was thinking another solution.  I see you use `calc(100% - 16px)`  and the table looks great!!
