### ISSUE TITLE
agent: kubernetes should be default for prow jobs?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#6655]
aka, we don't have and won't have any `agent: jenkins` anymore

cc @cjwagner @BenTheElder

**Comment by BenTheElder** [comment]
this is 635 lines of config currently (and growing), OTOH our config is 13k lines still at the moment...

maybe we can make a config option for which agent is default? :man_shrugging:

**Comment by BenTheElder** [comment]
/area prow
/kind feature
Probably also worth mentioning to @munnerz @sebastienvas

**Comment by kargakis** [comment]
This is fine.

**Comment by fejta** [comment]
Yes please! Great change!

**Comment by krzyzacy** [comment]
/remove-lifecycle stale
@cjwagner is on this
