### ISSUE TITLE
Mocking framework for unit testing

### ISSUE THREAD

**Issue by qhuynh96** [kubernetes/test-infra#6665]
I would like to know if we are currently adopting to any mocking framework for unit tests in Go. I am writing unit tests for Deck and need to mock several methods that return key/token from Github OAuth API

**Comment by BenTheElder** [comment]
In go you can just use an interface with fake and real implementations for
pretty much all unit testing needs.

**Comment by qhuynh96** [comment]
Got it! Thanks
/close
