### ISSUE TITLE
Support requesting team reviews in the assign plugin

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#6670]
The assign plugin currently supports requesting reviews from users using the `/cc` command. We should also look into the ability to request a review from a github team with `/cc`.

Github Developer Blog Post: https://developer.github.com/changes/2017-07-26-team-review-request-thor-preview/
API Documentation: https://developer.github.com/v3/pulls/review_requests/
User Documentation: https://help.github.com/articles/requesting-a-pull-request-review/

The one complicated part of this, is you can only officially "request" a review from teams that explicitly have read access to the repo, rather than any team in the org. The upside though is that when someone who is a member of that team leaves a review, it reports that it's been done. So, for example, you could request a review from say sig-architecture-leads or something, and when someone from that github team leaves a review, it satisfies that requirement.

Something to look into if we are using review requests more. I could also see this being used to have a github team in a OWNERS file, and prow just assign that whole team to review a PR.

**Comment by cjwagner** [comment]
This functionality would be nice. Unfortunately the Github API requires that the caller specifies if the request target is a user or a team. This means that the `/cc` command would have to determine if it's arguments are users or teams before requesting a review. I'm not sure what the best way to implement this would be.

**Comment by cblecker** [comment]
@cjwagner Teams are only applicable to repos within the same org, and all team mentions would be prefixed with `@<org>/`. You should be able filter any mentions that start with `@kubernetes/` and identify them as teams, vs users.

**Comment by cjwagner** [comment]
Ah, good point. I forgot that teams are prefixed by org. In that case this should be an easy change to make.

**Comment by cblecker** [comment]
/remove-lifecycle stale
@hoegaarden are you still working on this?

**Comment by hoegaarden** [comment]
@cblecker I started looking into that but then got sidetracked by other things -- sorry about that!
I can see if I find time to address that in the coming weeks or I can step back and remove the assignment -- what would you prefer?

**Comment by matthyx** [comment]
Hi, I need more info for that one: as I understand, there should be teams [on the org page](https://github.com/kubernetes) but I don't'see them as I am not yet a member?

And the use cases are:
- `/cc @user1` assigns user1 for review
- `/cc @kubernetes/team1` assigns team2 for review

Do we care if we cc/assign a user that is already part of an assigned team? And vice-versa?
What about uncc/unassign?

**Comment by cjwagner** [comment]
> there should be teams on the org page but I don't'see them as I am not yet a member?

Correct, the teams are currently only visible to members. We are working to fix this by defining membership and teams in a publicly readable config file.

> Do we care if we cc/assign a user that is already part of an assigned team? And vice-versa?
What about uncc/unassign?

I'm not sure how GitHub handles these cases. We may need to experiment to determine the actual behavior.

**Comment by matthyx** [comment]
indeed :) cheers!
