### ISSUE TITLE
jenkins-operator is giving us warnings

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#6677]
{"level":"warning","msg":"jenkins_operator is deprecated, please switch to the jenkins_operators option!","time":"2018-02-06T23:33:38Z"}

/cc @cjwagner @kargakis

**Comment by cjwagner** [comment]
We shouldn't need the jenkins-operator in the very near future (we might not need it now?). @BenTheElder

**Comment by krzyzacy** [comment]
jenkins is officially dead after https://github.com/kubernetes/test-infra/pull/6662, we should take it down :-)

**Comment by kargakis** [comment]
This is just a config warning, nothing serious to worry about.

Based on https://github.com/kubernetes/test-infra/pull/6679 you wont need it soon so

/close
