### ISSUE TITLE
External plugin help is missing from the frontend?

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6692]
The needs-rebase plugin has its own help but does not show up under Command Help

https://deck-ci.svc.ci.openshift.org/plugin-help.js
https://deck-ci.svc.ci.openshift.org/command-help.html

/area prow
@BenTheElder @qhuynh96

**Comment by qhuynh96** [comment]
@kargakis From what I can see from the plugin-help.js, there is no commands registered for the plugin. The command page only shows plugins that have commands. To add the commands to plugins:
https://github.com/qhuynh96/test-infra/blob/master/prow/plugins/approve/approve.go#L111

**Comment by kargakis** [comment]
Cool, I will verify this once https://github.com/kubernetes/test-infra/pull/6691 merges.
