### ISSUE TITLE
Favicon needs to be configurable for non-html pages

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6693]
https://deck-ci.svc.ci.openshift.org/plugin-help.js
https://deck-ci.svc.ci.openshift.org/command-help.html

/shrug
/area prow

**Comment by matthyx** [comment]
Hi @kargakis could you give me more details on how prow is configured at OpenShift? It seems there is an option to specify a branding favicon in config.go:
https://github.com/kubernetes/test-infra/blob/master/prow/config/config.go#L255
And to me it seems that it should be taken into account... but I might be wrong.

**Comment by kargakis** [comment]
@matthyx right, we already use that [option](https://github.com/openshift/release/blob/673a615df17d8b0ac330dd0e1572927525ff733e/cluster/ci/config/prow/config.yaml#L54) but deck does not use it when returning logs.

**Comment by kargakis** [comment]
> when returning logs.

Or pure JSON in js files

**Comment by matthyx** [comment]
Alright, I will investigate !
/assign
/remove-help

**Comment by kargakis** [comment]
This is still not fixed :(

**Comment by matthyx** [comment]
@kargakis how did you test?

**Comment by matthyx** [comment]
@kargakis if you only tested locally, using the script `runlocal` it falls into the test `if o.runLocal {` and only serves static files... while the new code `mux.Handle("/favicon.ico"` is part of `func prodOnlyMain(o options, mux *http.ServeMux) *http.ServeMux {`.

**Comment by kargakis** [comment]
Sorry, this seems fixed in our deployment! Thanks a lot @matthyx
