### ISSUE TITLE
testgrid showing inconsistent status relative to results

### ISSUE THREAD

**Issue by caseydavenport** [kubernetes/test-infra#6700]
It seems to me that testgrid is showing some test groups as FLAKY when the group itself is entirely green.

Here is an example: https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-ip-alias

The tests are all green, [but in the summary page](https://k8s-testgrid.appspot.com/sig-network-gce) that set of tests is listed as FLAKY.

----------------------------------------------------------

[As discussed on Slack here](https://kubernetes.slack.com/archives/C09QZ4DQB/p1518032796000251?thread_ts=1517944356.000156&cid=C09QZ4DQB)

caseydavenport [12 minutes ago]
@amerai so, If I understand correctly the FLAKY designation is determined by looking at all tests in a given job, even if the subset selected by a given test group is all green?

For example these are all green: https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-ip-alias
But the "summary" page shows that as flaky.

caseydavenport [10 minutes ago]
Or is there a way to tell the dashboard to only look at the sig-network test subset?

amerai [8 minutes ago]
So technically it should just look at all test results in the last num_columns_recent runs (10 in this case). This _should_ include filtering from base_options correctly (which this dashboard has).

amerai [8 minutes ago]
So that looks like a bug or at least something weird going on.

amerai [7 minutes ago]
If there isn't an issue already, can you file one against me and I'll look into it?

caseydavenport [7 minutes ago]
Perhaps related is this snippet:

> 0 of 1577 tests (0.0%) and 58 of 83 runs (69.9%) failing in the past week

I assume that means 0% of the filtered-in sig-network tests are failing, though the job itself has failed about 70% of the time.

caseydavenport [7 minutes ago]
Yep, can do - thanks!

amerai [7 minutes ago]
Awesome. ^^

amerai [5 minutes ago]
(And yeah, runs is incorrect because it doesn't take filtered rows into account; tests ought to)

**Comment by michelle192837** [comment]
/remove-lifecycle stale

Nope, still an issue.

**Comment by BenTheElder** [comment]
@michelle192837 is this still an issue or should we close it?

**Comment by michelle192837** [comment]
I believe this is actually fixed, thanks to an internal contributor.

**Comment by BenTheElder** [comment]
ok, tenatively closing then, hopefully this is actually sorted. if not, feel free to re-open or file another bug :-)
/close
