### ISSUE TITLE
migrate bazel jobs to unified image

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#6702]
We have both the bazelbuild image and the kubekins-e2e image support versioned bazel build environments, bazelbuild is based on ubuntu while the rest of our test images are generally built on debian.

To allow better caching we should convert to supplying the same tool versions for all jobs in the same release branch. We can probably just migrate all jobs to kubekins which has go, bazel etc. versioned by kubernetes release.

As a follow up we can then start tuning bazel config for caching in these images.

/area images
/area jobs
/assign

**Comment by BenTheElder** [comment]
Discussed out of band with @ixdy and @krzyzacy (the other maintainers) this morning. I will start on this today.

**Comment by ixdy** [comment]
somewhat related (unmerged) PR: #2836

**Comment by BenTheElder** [comment]
Ha! That actually happened at some point, I think @krzyzacy did this.

**Comment by BenTheElder** [comment]
this is *mostly* done [master/1.10 branches], I think maybe we can just leave older branches as is since they also won't have the caching and retire this image once those branches are done.

**Comment by BenTheElder** [comment]
closing, we'll leave old branches alone for now. new branches are pretty well migrated everywhere.
