### ISSUE TITLE
bot comments bad OWNERS file paths in kubernetes/website repo

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#6710]
The bot shows bad OWNERS file path in its comment:

https://github.com/kubernetes/website/pull/7224#issuecomment-362875101

Please notice the below lines. The OWNERS files path are incorrect.

```
Needs approval from an approver in each of these OWNERS Files:
docs/concepts/cluster-administration/network-plugins.md/OWNERS
docs/getting-started-guides/rkt/index.md/OWNERS
```

xref: https://github.com/kubernetes/website/issues/7289#issuecomment-363978843

/assign @fejta @cjwagner

**Comment by cjwagner** [comment]
I know what is going on here. This is related to handling certain `*.md` file headers as OWNERS files. Support for this can now be provided with OWNERS file regexp filtering so we may want to deprecate the special handling of markdown files eventually.
I can make a quick fix to resolve this bug though.
