### ISSUE TITLE
Monitor prow token usage

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6720]
We need to expose prometheus metrics for token usage in hook and tide (assuming hook and plank are using the same token, and tide uses a separate token).

The SQ token usage monitor may be ugly but it is at least helpful in a sense that it shows whether a problem persists or is fixed. In the following example, our queues were getting ratelimited because of a tight resync interval that was fixed in https://github.com/openshift/release/pull/589.
![prom](https://user-images.githubusercontent.com/3900799/35973869-4a52d24a-0cd7-11e8-9bd2-b2669732917e.png)

I think it's good to spend time upfront designing this metric if the waves in the graph above are undesirable (IMO it doesn't matter since it's up to the alert to handle the metric). The metric needs to be treated as API (because alerts are built on top).

Related but not a dupe: https://github.com/kubernetes/test-infra/issues/2699

/area prow
@stevekuznetsov @cjwagner @BenTheElder

**Comment by cjwagner** [comment]
@Q-Lee has some work related to using prometheus to gather Prow metrics.

**Comment by kargakis** [comment]
Closing as a dupe of https://github.com/kubernetes/test-infra/issues/5338
