### ISSUE TITLE
Charts CI: Unable to see build log in gubernator

### ISSUE THREAD

**Issue by viglesiasce** [kubernetes/test-infra#676]
When trying to view build logs in Gubernator they cannot be found. 

Example here:
https://github.com/kubernetes/charts/pull/91
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/91/charts-pull-test-e2e/129/

It appears to be due to a path change.

https://github.com/kubernetes/charts/issues/94

**Comment by spxtr** [comment]
The new link is https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/charts/91/charts-pull-test-e2e/129/

https://github.com/kubernetes/kubernetes/pull/33338

**Comment by spxtr** [comment]
We needed to do it this way because multiple repos PRs would collide.
