### ISSUE TITLE
issue closer does not seem to label kubernetes/kubernetes PRs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6776]
See discussion in https://github.com/kubernetes/kubernetes/pull/31136#issuecomment-364686292

@fejta @cblecker

**Comment by fejta** [comment]
Do you have an example of a PR which GitHub says is unmodified for 90d?

**Comment by fejta** [comment]
(aka if you look at prow/config.yaml for the stale bot you'll see there's nothing to handle either PRs or k/k repo differently from everything else)

I suspect it is just that all the bots make it so that all the issues in k/k have been updated within the last 90d

**Comment by kargakis** [comment]
> I suspect it is just that all the bots make it so that all the issues in k/k have been updated within the last 90d

Yeah, seems like this is the case.

**Comment by cblecker** [comment]
But wouldn't that still be a problem? We don't want k/k PRs to stay open forever. Either we would need to change the bot logic that's refreshing the k/k PRs, or change the closer logic. Using last updated from the github API is very different logic then the previous stale close munger.

**Comment by fejta** [comment]
The stale job will mark as stale any PR that is unmodified for 90d and does not have a `lifecycle/frozen` label.

If you ask github to [sort issues by least recently modified](https://github.com/search?o=asc&q=repo%3Akubernetes%2Fkubernetes+is%3Apr+is%3Aopen+-label%3Alifecycle%2Ffrozen&s=updated&type=Issues&utf8=%E2%9C%93) (aka something sane), you will instantly discover that github considers https://github.com/kubernetes/kubernetes/pull/54737 the most stale PR in k/k, which is (30-14)+31+31+11 aka 89 days stale.

Assuming no one comments on it, I would expect the PR to go stale in the next day or two.
