### ISSUE TITLE
fejta-bot can't trigger retest now

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#6777]
See https://github.com/kubernetes/kubernetes/pull/58960#issuecomment-364722397
```
@fejta-bot: you can't request testing unless you are a kubernetes member.
```

I don't find fejta-bot in https://github.com/orgs/kubernetes/people. Seems like it's removed from the org.

/cc @fejta

**Comment by fejta** [comment]
This is intentional, `fejta-bot` should have no rights to anything
/close

**Comment by fejta** [comment]
The issue is that Timothy manually removed the needs-ok-to-test label

**Comment by xiangpengzhao** [comment]
@fejta thanks!
