### ISSUE TITLE
Unable to load build details

### ISSUE THREAD

**Issue by JulienBalestra** [kubernetes/test-infra#6781]
On the Kubernetes PR [#57106](https://github.com/kubernetes/kubernetes/pull/57106) I cannot get the detail of a failed build.

I currently have the test **pull-kubernetes-unit** in failure but the detail link give me the following ouput:
```
pull-kubernetes-unit #79327
Unable to load build details from gs://kubernetes-jenkins/pr-logs/pull/57106/pull-kubernetes-unit/79327
```

I need to go to the [summary](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/57106/pull-kubernetes-unit/) to reach the logs of my test.

**Comment by BenTheElder** [comment]
The history for your PR: https://k8s-gubernator.appspot.com/pr/57106
shows what looks like a flake for pull-kubernetes-unit. I've triggered another test.

It's possible the test pod was evicted. We run on kubernetes and have an existing issue that jobs which are evicted by the kubelet can lose results. Generally triggering the test again should work.

**Comment by JulienBalestra** [comment]
@BenTheElder thank you for the link and the explanation !

The new test is now ok for **pull-kubernetes-unit** but **pull-kubernetes-e2e-kops-aws** is failing now.
 I've triggered another test too.
