### ISSUE TITLE
hack/update-deps.sh reverts BUILD.bazel to BUILD

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#6789]
`hack/update-deps.sh -update github.com/some/dep` will introduce a lot of churn in vendor from BUILD to build.bazel I think I've found one bug in prune-libraries.sh with `BUILD` instead of `BUILD.bazel` but this was not enough to fix it...

/kind bug
/area bazel
/cc @ixdy

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/blob/ace3a6444d0ba84c7f40cc95f5496826965e7e0f/hack/prune-libraries.sh#L85-L90
should probably be:
```bash
# Convert //foo //bar to foo/BUILD.bazel bar/BUILD.bazel
builds() {
  for i in "${@}"; do
    echo ${i:2}/BUILD.bazel
  done
}
```

**Comment by ixdy** [comment]
oops, I think `hack/prune-libraries.sh` was added after I'd originally created #6250. Will fix.
