### ISSUE TITLE
Prow issue: k8s-ci-robot refers to old PR documentation

### ISSUE THREAD

**Issue by Capstan** [kubernetes/test-infra#6804]
`k8s-ci-robot` has a link:

> The pull request process is described [here](https://github.com/kubernetes/community/blob/master/contributors/devel/owners.md#the-code-review-process)

That link reports being moved to https://git.k8s.io/community/contributors/guide/owners.md as of https://github.com/kubernetes/community/commit/02a00faf534fea46af7629da1085bc01ae2aae04#diff-593739ef69af9f3d11686e9b0dd32de5

https://github.com/kubernetes/test-infra/search?utf8=%E2%9C%93&q=%22The+pull+request+process%22&type= shows remaining references which appear to have the old links.

/cc @castrojo

**Comment by cblecker** [comment]
The new link should be: https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process
/help
@kubernetes/sig-contributor-experience-bugs

**Comment by cblecker** [comment]
/remove-help
Thanks @guineveresaenger!
