### ISSUE TITLE
Deck Prow Status is now unusable on mobile

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#6841]
It now looks like:
![screenshot_20180214-195749](https://user-images.githubusercontent.com/917931/36239816-80477380-11c1-11e8-9da5-92a5ba1caf64.png)
Everything that runs off the page is impossible to see. Previously the experience was not *great* but it was possible to use.

/kind bug
/area prow
/assign @qhuynh96

**Comment by BenTheElder** [comment]
I suspect MDL isn't handling mobile and setting those meta tags to device width made this apparent. We should revert setting the viewport.

**Comment by qhuynh96** [comment]
Actually the Prow Job's table is not applied MDL. Only Command Help's table apply MDL. I just see this and will investigate what cause the problem.

**Comment by qhuynh96** [comment]
Pretty sure the meta view port scales up the table which does not fit the mobile screen anymore.

**Comment by qhuynh96** [comment]
Probably because of the view port setting. Until we figure out how to render on mobile, we should not use the viewport tag maybe?

**Comment by BenTheElder** [comment]
Yes, see previous comment.
