### ISSUE TITLE
Testgrid showing a tab red, even if the latest run of the job is green

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#6847]
E.g https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-scale-correctness

This seems to be misleading for someone looking at the job (and thinking that the job is failing). Moreover, it continues to be red even after 4 green runs (probably just because there are still some red runs in the visible past).

IMO we should change this - WDYT?

cc  @rmmh @krzyzacy

**Comment by michelle192837** [comment]
This is working as intended though; red status means there's an alert, and alerts are still active if there are failures without a more recent pass within num_recent_columns. I agree it's a bit misleading for a while in this case, but there are also plenty of cases where something is failing like this and it means there is still a consistent failure active.

To have this go away sooner, you can drop num_recent_columns down (currently 10) in the test group backing this dashboard tab, or the "BeforeSuite" targets need to show up when they pass as well as when they fail (unable to check the failed runs at the moment, so not sure whether that's possible).

**Comment by shyamjvs** [comment]
I see - thanks @michelle192837. In short you're saying that if we care less about old runs, we should reduce num_recent_columns for the tab?

**Comment by michelle192837** [comment]
Yup! `num_columns_recent` should be limited to a number that you'd consider recent, both for 'is this failure still relevant' and 'if this test hasn't run in the last X runs, should we show it'.

**Comment by shyamjvs** [comment]
Sounds good.. thanks. I'll change it for our jobs.

/assign
