### ISSUE TITLE
fejta-bot: should an issue be "inactive" if it was mentioned somewhere else?

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#6858]
https://github.com/kubernetes/kubernetes/issues/55621

Mentioned in an umbrella bug on Jan 10.
About 30d later, fejta-bot complains about "inactivity".

**Comment by mml** [comment]
@kubernetes/sig-testing-bugs @fejta

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/test-infra/issues/6267

**Comment by mml** [comment]
I see.  Can we ask for an API?  This sort of thing is a waste of time and I don't just want to filter all messages from fejta-bot.

**Comment by BenTheElder** [comment]
We've had limited success before asking on https://platform.github.community, specifically https://platform.github.community/t/some-prs-are-missing-head-refs/4586
