### ISSUE TITLE
Prow Feature Request: Make search fuzzy, rather than just matching substrings.

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/test-infra#6880]
Prow now has a really great feature that lets you search for jobs. Thanks @qhuynh96!
It would also be cool if it could do stuff like my editor's fuzzy matcher (substrings don't have to be contiguous):
![screenshot from 2018-02-16 17 23 49](https://user-images.githubusercontent.com/903617/36336670-b65e0f8c-133e-11e8-8350-ef90a5a220ad.png)

I saw a blog post investigating how to implement this kind of thing here: https://blog.forrestthewoods.com/reverse-engineering-sublime-text-s-fuzzy-match-4cffeed33fdb

**Comment by BenTheElder** [comment]
/kind enhancement
yes please
/assign @qhuynh96 
/assign

**Comment by qhuynh96** [comment]
@mtaufen @BenTheElder  Acknowledge. I will be on it soon.
