### ISSUE TITLE
Tests run against stale version of k8s

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/test-infra#6893]
Looks like for the past 3 days, all tests run against [v1.11.0-alpha.0.92+ada9400915e282](https://github.com/kubernetes/kubernetes/commit/ada9400915e282), even though a lot of changes has been merged to master since.

In particular, autoscaling tests are still failing despite the fact that PR causing the issue was reverted 2 days ago:
https://k8s-testgrid.appspot.com/sig-autoscaling#gci-gce-autoscaling

**Comment by aleksandra-malinowska** [comment]
cc @krzyzacy @BenTheElder

**Comment by krzyzacy** [comment]
cc @calebamiles @david-mcmahon @ixdy 
so now ci/latest somehow becomes 1.11.0-alpha? shouldn't that stay 1.10-beta?

**Comment by ixdy** [comment]
ci/latest points to whatever is on master, which is now v1.11-alpha since the release-1.10 branch has been created.

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build/10651
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build/10655/
Somehow these are triggering with 1.11 and 1.10 ??

**Comment by ixdy** [comment]
I think the `v1.10.0-beta.0` tag was deleted from upstream, but probably some of the prow build nodes have `v1.11-alpha.0` in their git cache, and are thus using that tag instead. (Both `v1.10.0-beta.0` and `v1.11-alpha.0` pointed at the same commit, but the latter was probably made last, and thus takes precedence if both exist?)

See also https://github.com/kubernetes/sig-release/issues/85

**Comment by aleksandra-malinowska** [comment]
Looks like this is resolved - tests are running against the lastest version now.

**Comment by david-mcmahon** [comment]
We need to get https://github.com/kubernetes/kubernetes/pull/59960 in so we can tag that branch-only change on the branch.
