### ISSUE TITLE
How can I generate release note with `releasenote` plugin?

### ISSUE THREAD

**Issue by bbbmj** [kubernetes/test-infra#6900]
**What happened**:

- I haven't found any code to generate release note in test-infra, maybe there is none?

**What you expected to happen**:

- Sincerely look forward to a reply

**Comment by supereagle** [comment]
It is in another repo: [kubernetes/release](https://github.com/kubernetes/release).

**Comment by stevekuznetsov** [comment]
`releasenote` plugin just ensures that the data is present on your pull request. As mentioned, the tool lives in `kubernetes/release`. Please re-open if you have more questions!

/close
