### ISSUE TITLE
prow: cherrypicker: add a milestone to cherry-pick PRs

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#6908]
A thought @derekwaynecarr had a thought that the `/cherrypick` robot could (if it has the rights to) add the appropriate milestone to the PR it creates.

/cc @cjwagner @marun @kargakis 
/kind feature
/area prow

**Comment by kargakis** [comment]
How can it infer the right milestone?

**Comment by stevekuznetsov** [comment]
We could make it best-effort for things like `release-1.x`?

**Comment by spiffxp** [comment]
I think this is something we'd want to do to make kubernetes release branch managers' lives easier.  The release team pays close attention to number of PR's in milestone during burndown.  Unclear to me how useful this is for patch release managers, but I'm assuming it is

**Comment by kargakis** [comment]
Needs to be implemented behind a flag.
