### ISSUE TITLE
prow: gcsupload: failed to fetch OAuth2 token

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#6909]
Seeing this error on some uploads:

```
time="2018-02-20T21:43:00Z" level=fatal msg="Failed to upload to GCS" error="failed to upload to GCS: encountered errors during upload: [Post https://www.googleapis.com/upload/storage/v1/b/origin-ci-test/o?alt=json&projection=full&uploadType=resumable: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp: lookup accounts.google.com on 172.18.12.235:53: read udp 172.17.0.2:50604->172.18.12.235:53: read: no route to host]" 
```

/area prow
/kind bug
/assign

**Comment by stevekuznetsov** [comment]
@rmmh @michelle192837 have you guys seen this at all with the code interacting with GCS using the `golang` clients? Do you just retry on interaction?

**Comment by smarterclayton** [comment]
This may be a networking thing on the box - possibly caused by the actual test being run.

**Comment by rmmh** [comment]
The library should retry for us, but I think that's buried deep in the vendored storage/grpc/oauth libraries.

**Comment by stevekuznetsov** [comment]
Yeah I was under the impression it would retry too. Hmm.

**Comment by stevekuznetsov** [comment]
Agreed Clayton, this looks like a real low level whoopsie

**Comment by rmmh** [comment]
File upstream with https://github.com/GoogleCloudPlatform/google-cloud-go ?

**Comment by stevekuznetsov** [comment]
Haven't seen it since
/close
