### ISSUE TITLE
Prow needs a way to force CLA rechecking

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#6939]
If Prow misses the CNCF CLA status update we can only manually approve PRs. Instead we should have some `/check-cla` to force checking the statuses for the CLA.

/area Prow
/kind bug

**Comment by BenTheElder** [comment]
/assign
See:https://github.com/kubernetes/kubernetes/pull/60131

**Comment by BenTheElder** [comment]
cc @cjwagner @kargakis

**Comment by BenTheElder** [comment]
looks like possibly close/reopen worked? https://github.com/kubernetes/sig-release/pull/97

**Comment by stevekuznetsov** [comment]
Alternatively, understanding how the CLA bot works would help.

**Comment by kargakis** [comment]
+1

**Comment by BenTheElder** [comment]
The CLABot seems to react to github events and then check the commit emails against a database, we  can prod the bot by commenting but we can't similarly prod prow if it misses the cla status event.

**Comment by stevekuznetsov** [comment]
Can we ask the maintainers of the bot to give us their SLA or API or whatever so we're not guessing? Who can see that code? (Also why is the CNCF bot code closed?)
