### ISSUE TITLE
migrate from kube-lego to cert-manager

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#6944]
kube-lego is now in maintenance mode, and it might stop working at some point in the future (per [this notice](https://github.com/jetstack/kube-lego)).

We should move to cert-manager. There's a [migration guide](https://github.com/jetstack/cert-manager/blob/master/docs/user-guides/migrating-from-kube-lego.md) available.

Fixing the SQ is probably not worth our time, but prow definitely needs to switch.

/area prow

**Comment by BenTheElder** [comment]
FWIW kube-lego *works* just fine for now, and is easier to work with :(
- debug via pod logs (which are also stored in stackdriver...) not the event api
- easily deployable without helm etc, can trivially check in our exact deployment
- automatic ingress certs via one annotation on the ingress + auto generated secrets, not CRDs, shims, etc.
...

**Comment by ixdy** [comment]
@colemickens is going to check out cert-manager, per https://github.com/kubernetes/test-infra/issues/2529#issuecomment-367828232

**Comment by colemickens** [comment]
Not a lot to report. `cert-manager` can be deployed with `ingress-shim` that causes it to act like `kube-lego`, in terms of automatic LE setup for Ingress objects.

How was the `marque` -> `kube-lego` transition? Was it done to reduce the code you were maintaining? More resilient?

As someone who originally wanted to switch from `marque` to `kube-lego`, I am of the opinion that there is a place for a sidecar or lightweight pod that can do simple cert retrieve for a single domain. `cert-manager` deploys a controller, multiple CRDs and CRs, etc.

Either way though, it doesn't seem appropriate to stay with `kube-lego` for too long if it is unmaintained.
