### ISSUE TITLE
prow: user-dashboard: don't show PRs to repos with unknown merge requirements

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#6958]
For any of us with PRs to orgs and repos that either do not use Prow or do not use the Prow instance that is serving the user dashboard, the majority of the dashboard ends up being PRs with no data that do nothing. We should just hide these.

/area prow
/kind enhancement
/assign @qhuynh96

**Comment by BenTheElder** [comment]
we should allow scoping to orgs or something, maybe black listing repos, but I don't think we should not show *all* PRs without data.

**Comment by BenTheElder** [comment]
test data could be loaded from querying github statuses in a future improvement

**Comment by qhuynh96** [comment]
we can have a config file that listing repos that we care about, the server should read that and query those repos only. How does it sound?

**Comment by BenTheElder** [comment]
> we can have a config file that listing repos that we care about, the server should read that and query those repos only. How does it sound?

this should probably be derived from prow's config

**Comment by stevekuznetsov** [comment]
What's the use of showing PRs for which `tide` isn't running? Are we going to be able to show any meaningful information when we have no reference to calculate missing & required labels and no record of the presubmits that matter?

**Comment by BenTheElder** [comment]
> and no record of the presubmits that matter?

repos can have prow without tide, we have this right now.

we can't show the tide part, but we can still show the rest of the state of the PR consistently (presubmits? labels?), and for our use case (repos in kubernetes/) if they aren't using tide we should probably nudge them that way. It's also possible that we failed to load the data properly. 

That way we have an alternate to github.com/pulls but with all of the data prow knows added

**Comment by BenTheElder** [comment]
I think it's reasonable to restrict it to repos for which prow is configured but these are a superset of tide enabled repos. We can derive the set of repos from prow config and serve this from deck.

**Comment by stevekuznetsov** [comment]
ACK to repos that are configured -- no `tide` but with presbumits that seems OK. For PRs to repos with neither the boxes are ... a little on the useless side of things :)

**Comment by BenTheElder** [comment]
Yeah. I think we should look at pulling the presubmit status from GitHub, prow doesn't keep jobs forever so I'm also seeing "no tests found" for kubernetes/kubernetes PRs (old dummy / testing PRs...) that definitely have loads of presubmits..
