### ISSUE TITLE
[PR dashboard] Proposal: "Waiting on"

### ISSUE THREAD

**Issue by timstclair** [kubernetes/test-infra#697]
**Problem:**
There are often a handful of PRs in my "needs attention" view that I know are waiting for something specific. They might be waiting on a dependency, need to add new features, or have just been deprioritized. PRs in this state clutter the dashboard, making it harder to find PRs that really do need attention (i.e. they make a zero-inbox workflow difficult). It is also not always obvious what a PR is waiting on.

**Proposed solution:**
1. Add a keyword / syntax that the PR building understands to indicate what the PR is waiting on. I propose: `Waiting on: <msg>`.
2. The PR dashboard should recognize the keyword, and display the message by the PR (or in a tooltip?), and remove the PR from the "needs attention" section.
3. Open question: when does the PR go back to needs atention? It could
   1. wait for the next state change (e.g. code push, etc., maybe ignore test failures)
   2. use a label to indicate the "waiting" state (needs more thought, maybe k8s-bot support)
4. (optional) Add a button to the PR dashboard to add a waiting message, which would post the properly formatted comment to GH to indicate the waiting state.

@rmmh

**Comment by rmmh** [comment]
I was planning to just add a button like "ack" that will forcibly suppress "needs attention" (transition it back into "waiting") until the next state change.
