### ISSUE TITLE
kubetest -v flag is not recognized correctly

### ISSUE THREAD

**Issue by verult** [kubernetes/test-infra#6992]
Setting `-v` no longer produces test logs. My e2e tests simply run to completion with no messages, or fail with just an error status and no other information.

Related to PR https://github.com/kubernetes/test-infra/pull/6966, `verbose` is not set correctly here:
https://github.com/kubernetes/test-infra/blob/a531c206da9247a6fa805bf5f238cd8617f1e8b6/kubetest/process/process.go#L50-L60

/area kubetest
/cc @Q-Lee @krzyzacy @BenTheElder 
/priority critical-urgent

**Comment by verult** [comment]
After this is fixed, is there a way for me to force a kubetest update through hack/e2e.go?

**Comment by krzyzacy** [comment]
@verult e2e.go always picks up latest kubetest - you can even make a local fix temporarily. we'll patch it up tomorrow.
