### ISSUE TITLE
Cleanup fallback to BUILD_ID

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#6996]
Regressed in https://github.com/kubernetes/test-infra/pull/6853

Basically, before https://github.com/kubernetes/test-infra/pull/6853 the controller used to set the name of the prowjob as the BUILD_ID parameter in every build and then it could use this relationship to do [map lookups](https://github.com/kubernetes/test-infra/blob/f260c9529346f0600f6ec4125710ec67c55a0776/prow/jenkins/controller.go#L344) and correlate Jenkins builds to prowjobs. https://github.com/kubernetes/test-infra/pull/6853 updated to set BUILD_ID to either whatever is returned from the snowflake library or tot if it's configured but didn't update the way the controller correlates builds to prowjobs.

/area prow
/kind bug

@stevekuznetsov

**Comment by kargakis** [comment]
I think for discovery the best option is that we still use the prowjob name since it's stable (aka already in etcd) and known at the time we request a build in Jenkins whereas whatever we get from snowflake/tot is only known but not stable (we need to persist it on the prowjob first).

**Comment by kargakis** [comment]
Hrm, this may also be an issue with our jobs lacking `PROW_JOB_ID`.

**Comment by kargakis** [comment]
Yeap, it was `PROW_JOB_ID` missing from our jobs. There is still some cleanup that needs to happen here.

/assign

**Comment by stevekuznetsov** [comment]
What is left here? The fallback should have just been the more specific `PROW_JOB_ID`

**Comment by stevekuznetsov** [comment]
That is _only_ true if we assume that `$PROW_JOB_ID` not being present is from something other an an older version of the `jenkins-operator`. If we infer that `$PROW_JOB_ID` being missing is due to an older `jenkins-operator`, using `$BUILD_ID` as the fallback is correct as that is the var that held the info in the past.

**Comment by kargakis** [comment]
Yeah, it makes sense for running jobs during the upgrade. I guess we can keep it until we migrate.
