### ISSUE TITLE
GCS upload path inconsistencies.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#7032]
The GCS paths linked to by Prow are not consistent with the actual upload paths used by bootstrap for postsubmit jobs in repos other than k/k. Specifically, it seems that Prow includes the repo name in the path while bootstrap does not. For example:

actual upload path:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-test-infra-bazel/64888/build-log.txt
expected gubernator link:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-test-infra-bazel/64888
prow provided gubernator link:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/test-infra/ci-test-infra-bazel/64888/

This appears to affect all postsubmit jobs except for those in k/k.
https://prow.k8s.io/?type=postsubmit 

cc @BenTheElder @rmmh @krzyzacy

**Comment by stevekuznetsov** [comment]
IIRC the rules are set up this way for `kubernetes` repository:

 - If the job is for `kubernetes/kubernetes`, use `build/<job_name>/<job_number>`
 - If the job is for some other repo under the `kubernetes` org, use `build/<repo_name>/<job_name>/<job_number>`
 - If the job is not under the `kubernetes` org, use `build/<org_name>_<repo_name>/<job_name>/<job_number>`

So the provided link in Prow is correct in your example and the "expected" link is not.

**Comment by stevekuznetsov** [comment]
Also if I may .... there are a large number of other places where it is assumed that jobs will have globally unique names, so it's also totally unclear to me why we even have this structure as it adds basically useless namespacing.

**Comment by BenTheElder** [comment]
We have this structure because we have this structure :grimacing: /s

Postsubmits should upload to a path with the repo name it it for now to be consistent, I'm not sure why they aren't right now.

**Comment by rmmh** [comment]
We have this structure because (at the time, and still?) jobs didn't embed their repo names in started or finished.json, so we couldn't link to PRs or commits properly.

**Comment by stevekuznetsov** [comment]
Yeah at this point we should move to publishing `$JOB_SPEC` JSON to the GCS bucket so we have the information we need.

**Comment by BenTheElder** [comment]
bootstrap.py dumps the podspec now which has been very useful occasionally
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/64560/pull-kubernetes-bazel-build/45263/artifacts/prow_podspec.yaml

**Comment by cjwagner** [comment]
^ That would be even more useful for the pod utilities to do.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
This may be addressed by #9211 but only for decorated jobs :|
