### ISSUE TITLE
prow: user dashboard: when no PRs are open, message is not very pretty

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7035]
![no-prs](https://user-images.githubusercontent.com/7328370/36754889-32de1254-1bbf-11e8-9a36-b5c1f44b926e.png)

The rest of the dashboard is really pretty, this part is not :)

/kind bug
/area prow
/p0
/cc @BenTheElder 
/assign @qhuynh96

**Comment by qhuynh96** [comment]
:rotating_light:

**Comment by BenTheElder** [comment]
that is not ideal. let's do something larger and centered with a little padding.
/priority important-soon
