### ISSUE TITLE
couldnt deploy the cassandra-operator 

### ISSUE THREAD

**Issue by arunkumar9050** [kubernetes/test-infra#7077]
[https://github.com/arunkumar9050/cassandra-operator]

**Comment by BenTheElder** [comment]
Can you be a bit more specific?

**Comment by arunkumar9050** [comment]
I am trying to deploy etcd in kubernetes and adapt cassandra to the operator pattern and deploy it. i have deployed etcd operator using [https://github.com/coreos/etcd-operator/blob/master/doc/user/install_guide.md]. while i start deploying the cassandra operator([https://github.com/arunkumar9050/cassandra-operator]) i am getting error.
$kubectl create -f example/example-cassandra-cluster.yaml
error: unable to recognize "example/example-cassandra-cluster.yaml": no matches for cassandra.database.instaclustr.com/, Kind=CassandraCluster

**Comment by BenTheElder** [comment]
How exactly does this relate to Prow?

**Comment by BenTheElder** [comment]
I think this should be an issue against https://github.com/benbromhead/cassandra-operator instead of this repo
