### ISSUE TITLE
Milestone maintainer is unable to set milestone via milestone command

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/test-infra#7096]
Per #6982, Milestone maintainers should be able to set a milestone. However, I tested it and found it does not work.

I tested both `/milestone v1.10` and `/milestone v1.11` it in PR: https://github.com/kubernetes/kubernetes/pull/59720 and didn't get a response.

I am a milestone maintainer(xref: https://github.com/orgs/kubernetes/teams/kubernetes-milestone-maintainers/members?utf8=%E2%9C%93&query=m1093782566) and can approve a milestone via command `/status approved-for-milestone`, but there is no response when I type a `/milestone` command.

Am I missing something?

/cc @spiffxp @grodrigues3 @BenTheElder @kargakis @cjwagner @stevekuznetsov

/kind bug
/area prow

**Comment by BenTheElder** [comment]
Hmm I don't see your `/milestone` comments, just the `/status approved-for-milestone`

**Comment by m1093782566** [comment]
I deleted the command. Let me try it again.

**Comment by m1093782566** [comment]
Please check: https://github.com/kubernetes/kubernetes/pull/59720#issuecomment-369842454

**Comment by m1093782566** [comment]
I can find my github ID in kubernetes-milestone-maintainers team.

```
# curl -H "Authorization: token <token>" https://api.github.com/orgs/kubernetes/teams 
maintainers_id: 2460384 
maintainers_team: kubernetes-milestone-maintainers 

curl -H "Authorization: token <my_token>" https://api.github.com/teams/2460384/members?per_page=100
{
    "login": "m1093782566",  # me
    "id": 4953962,
    "avatar_url": "https://avatars1.githubusercontent.com/u/4953962?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/m1093782566",
    "html_url": "https://github.com/m1093782566",
    "followers_url": "https://api.github.com/users/m1093782566/followers",
    "following_url": "https://api.github.com/users/m1093782566/following{/other_user}",
    "gists_url": "https://api.github.com/users/m1093782566/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/m1093782566/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/m1093782566/subscriptions",
    "organizations_url": "https://api.github.com/users/m1093782566/orgs",
    "repos_url": "https://api.github.com/users/m1093782566/repos",
    "events_url": "https://api.github.com/users/m1093782566/events{/privacy}",
    "received_events_url": "https://api.github.com/users/m1093782566/received_events",
    "type": "User",
    "site_admin": false
  }
```

**Comment by m1093782566** [comment]
@kargakis @cjwagner @stevekuznetsov

**Comment by kargakis** [comment]
@m1093782566 the code for the command merged yesterday but the command is yet to be enabled in the prow config.

**Comment by m1093782566** [comment]
@kargakis Thanks for your prompt reply.

So, should we update the command list in https://prow.k8s.io/command-help? I am unable to find the `/milestone` command. I am curious to learn when it would be fixed?

**Comment by kargakis** [comment]
> So, should we update the command list in https://prow.k8s.io/command-help?

This list is updated automatically based on what's enabled in the [plugin config](https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml). @cjwagner or somebody else with access to prow.k8s.io needs to update `hook` with the new code, then enable the plugin in the config.

**Comment by m1093782566** [comment]
Got it, thanks!

/assign @cjwagner :)

**Comment by m1093782566** [comment]
Also cc @dims for information

**Comment by BenTheElder** [comment]
fix is in https://github.com/kubernetes/test-infra/pull/7099

**Comment by m1093782566** [comment]
I still can not set a milestone via command, xref: https://github.com/kubernetes/kubernetes/pull/59720
