### ISSUE TITLE
prow: deck: time hover is backwards

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7098]
Right now you get the full timestamp in the UI and the "N minutes ago" on hover -- seems like that should be reversed. Show the nice human-focused time and hover to get the nitty gritty timestamp.

/kind bug
/area prow
/assign @qhuynh96 
/cc @BenTheElder

**Comment by BenTheElder** [comment]
You can't hover on mobile or copy the timestamp and "x minutes ago" goes
stale. 🤷‍♂️

**Comment by qhuynh96** [comment]
We reversed this after a discussion about people may want to interact with the time directly (copy/paste) also you cant see full time on mobile. WDYT

**Comment by BenTheElder** [comment]
What about making the timestamp format more concise and show a more detailed one / timezone etc on hover?

OTOH I could be OK with "x minutes ago" if we EG had some worker updating that every so often so it was accurate or something... As it stood "x minutes ago" didn't seem that helpful and it was difficult to make out the timestamp from hover even on fancy giant monitors 🤷‍♂️

**Comment by stevekuznetsov** [comment]
Hmmm. I guess in the majority of cases displays will have the "x minutes ago" and hover to get the real time, that was just most common in what I saw elsewhere and what I expected from that background. If it's a static thing that doesn't get refreshed that isn't the end of the world but agreed if it ticks up that would be better.

**Comment by stevekuznetsov** [comment]
Also agreed that the formatting could help -- right now I just want to know roughly when a job ran. Neither the old format (wrong timezone) nor the current one (huge block of text) is helping me there -- a concise version might help a lot there.

**Comment by BenTheElder** [comment]
right now we have `'MMM DD YYYY, HH:MM:SS [GMT]ZZ'`, perhaps use that one for hover and something like `'HH:MM:SS'` for display which is more concise even than "two minutes ago". We could also try to fix hover / mobile and make the hover larger instead.

**Comment by qhuynh96** [comment]
The time is already updated every 1 min so you dont need to refresh. I dont use this much so I could not tell which way is better, defer to you, @BenTheElder, @ixdy

**Comment by ixdy** [comment]
I agree that it seems a bit backwards right now, at least compared to most sites which show relative times. To solve the mobile issue, can we also add a tap target or something which reveals the real time?

Side note, every job is showing the exact same started time right now (Mar 02 2018, 10:03:00 GMT-0800), which seems like a bug.

**Comment by ixdy** [comment]
(bikeshed/soapbox: I personally do not like the "N minutes ago" timestamps, and much prefer absolute times always.)

**Comment by qhuynh96** [comment]
@ixdy @BenTheElder  the bug 10:03 is due to wrong time format, should be `HH:mm:ss` not `HH:MM:SS`
`MM` is month
