### ISSUE TITLE
milestone command does not work properly

### ISSUE THREAD

**Issue by m1093782566** [kubernetes/test-infra#7121]
I still can not set a milestone via command, xref: kubernetes/kubernetes#59720, though `/milestone` command is available in prow docs, see https://prow.k8s.io/command-help#milestone.

I create this issue for tracking.

/area prow
/kind bug

**Comment by m1093782566** [comment]
@BenTheElder @spiffxp @kargakis @cjwagner

**Comment by cjwagner** [comment]
It appears that an old version of hook without the fix to the `/milestone` command was redeployed yesterday afternoon. I've redeployed the correct version.

**Comment by m1093782566** [comment]
Thanks，I tested it and it works properly.
