### ISSUE TITLE
Figure out restricted access to the log tracer

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7123]
We need to restrict access to the log tracer so only prow admins can access it. There are two different endpoints: `/` gets to the dashboard and `/trace` implements the backend. Both endpoints need to be public and restricted. The most convenient flow is to use the dashboard so the first request (to the dashboard) can be easily put behind oauth with an oauth proxy, the challenge is to do oauth between the frontend and the backend. 

Evaluate whether the recent work with the PR dashboard oauth flow in deck makes sense or we can simply place an hmac token in the static directory that the dashboard uses to make requests to the backend (so the backend is not behind oauth but requires the hmac token). If we do the later, think about rotating the token.

**Comment by BenTheElder** [comment]
any reason to not just use kubectl proxy if this is admins only?

**Comment by kargakis** [comment]
Yeah, we could use `kubectl proxy` but it's more convenient to click a bookmark and let the cluster authorize you based on RBAC.

**Comment by kargakis** [comment]
It seems we just need to plumb the service account token into the frontend so that it can use that token to make requests.

https://github.com/openshift/oauth-proxy/issues/65

**Comment by kargakis** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/7391
