### ISSUE TITLE
Enable NoDaemonSetScheduler alpha features in separate CI

### ISSUE THREAD

**Issue by k82cn** [kubernetes/test-infra#7149]
In https://github.com/kubernetes/kubernetes/issues/59194 (Schedule DaemonSet Pods by default scheduler), we'd like to schedule DaemonSet's pod by default scheduler instead of daemonset controller. There's no behavior changed, so I'd like to re-run the DaemonSet e2e test with this alpha feature enabled.

BTW, this's a 1.10 alpha feature; that'll be great if we can enable it in 1.10 :)

/cc @BenTheElder @krzyzacy

**Comment by krzyzacy** [comment]
you can enable the feature in https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#gce-alpha-features-1.10

**Comment by k82cn** [comment]
@krzyzacy , any example (e.g. PR or configuration file) on how to enable it?

**Comment by BenTheElder** [comment]
@k82cn jobs/config.json and prow/config.yaml

Flipping the question though, what switches need to get enabled here? and What ginkgo focus?

**Comment by krzyzacy** [comment]
you can change https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml#L756

and regenerate config using the command linked in https://github.com/kubernetes/test-infra#release-branch-jobs--image-validation-jobs

**Comment by k82cn** [comment]
great, let me try it :)

**Comment by k82cn** [comment]
Alpha features are enabled and no behavior change to DaemonSet when `ScheduleDaemonSetPods` enabled, so we don-t need to highlight it; dependent DaemonSet's e2e test is enough.
