### ISSUE TITLE
Prowjob should have first class timeout

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#7152]
pod can be stuck in running state, we never know, sinker does not clean running prowjobs, so it might be necessary to give prowjob a timeout field/annotation/label?

/area prow

**Comment by krzyzacy** [comment]
cc @cjwagner @BenTheElder @kargakis @stevekuznetsov @dims

**Comment by stevekuznetsov** [comment]
Thought was that we could add this to the `entrypoint` wrapper.

**Comment by kargakis** [comment]
Sounds reasonable. Is this obsoleting pod_pending_timeout in plank?

**Comment by cjwagner** [comment]
> Is this obsoleting pod_pending_timeout in plank?

No, we will still want both config options. `pod_pending_timeout` limits the time pods spend in the `pending` state which is distinct from the actual duration of the entire job which is what the proposed field would limit.

**Comment by BenTheElder** [comment]
We'd also like to set this per-pod. Some jobs actually do take 12+ hours but most should terminate after say, 2.

**Comment by BenTheElder** [comment]
/open

this isn't exactly fixed yet

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
we've seen more pods stuck in a running state

**Comment by sipian** [comment]
I would like to take this issue up.
A way that I can think of is to also check for the prowjob's age when checking the condition [!prowJob.Complete()](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/sinker/main.go#L136) for presubmit/postsubmit & periodics in sinker.
If age is more than MaxPodRunningAge then mark it for deletion

**Comment by stevekuznetsov** [comment]
Sounds reasonable to me @sipian

**Comment by spiffxp** [comment]
@sipian any update on this?

**Comment by sipian** [comment]
@spiffxp 
Sorry. I got busy with some other things. 
If it is alright, I'll try to finish this up in the coming few weeks.

**Comment by krzyzacy** [comment]
we already have this with podutils?

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/kubetest-canaries.yaml#L146-L147 works after some fix.

/close

**Comment by cjwagner** [comment]
@krzyzacy That timeout is implemented at the wrapper process level whereas the timeout suggested by this issue would occur at the ProwJob level.  A PJ level timeout could help us abort jobs that fail to schedule or start the wrapper process for whatever reason. The pod utilities' timeout would not catch these issues.

**Comment by krzyzacy** [comment]
I think the original issue was pod can be stuck forever, is the podutil timeout wraps entrypoint? Maybe we should utilize that for aborting fail to start jobs, since I feel like add another timeout will be confusing.

**Comment by cjwagner** [comment]
I thought that we had intended to have multiple levels of timeouts, but I can't find the issue where that was discussed. (Maybe @stevekuznetsov knows or remembers discussing?)
The pod utils could share a timeout with the ProwJob so long as the pod utils retain the configuration for the grace period, but if we did that we would want to move the timeout field to become a first class ProwJob field rather than a decoration config field. The grace period needs to be a decoration config field, because the ProwJob level timeout won't have a concept of a graceful termination signal.

**Comment by stevekuznetsov** [comment]
> because the ProwJob level timeout won't have a concept of a graceful termination signal.

If `plank` or `sinker` or whatever does a `DELETE` on the `Pod`, the default behavior of the kubelet is to send graceful deletion if the client doesn't ask for force delete, so in a way, it will work anyway. But I agree that we need to have one a all levels -- one for ginkgo, one for the entrypoint, one for PJ -- all orchestrated. I can't remember where we had that conversation, may have been in a meeting

**Comment by krzyzacy** [comment]
agree that each part will need its own timeout, maybe prow should by default populate these timeouts base off the podutil timeouts in some manner, rather let user set four different timeouts in the config?

**Comment by fejta** [comment]
Also would like to see controllers enforce a timeout on the prowjob
