### ISSUE TITLE
ok-to-test needed even though I'm a member of GoogleCloudPlatform

### ISSUE THREAD

**Issue by G-Harmon** [kubernetes/test-infra#7153]
In https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/140 , the tests did not automatically run. The bot said:
"I'm waiting for a kubernetes or GoogleCloudPlatform member to verify that this patch is reasonable to test."
But I *am* a member of GoogleCloudPlatform. Is the bot really configured to check membership of GCP? Can it be? Or should the text be changed?
cc @nikhiljindal

**Comment by stevekuznetsov** [comment]
Your membership in that organization is not public, so I don't think the bots can determine that you are actually in there.

**Comment by G-Harmon** [comment]
okay, I changed the visibility. Next PR, I'll see if it automatically tests.

**Comment by BenTheElder** [comment]
I think technically it's possible for this to work with non-public membership but the bot needs elevated permissions IIRC.
