### ISSUE TITLE
prow should comment when removing LGTM

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7159]
From an offline discussion with @krzyzacy: right now the lgtm after commit support just removes LGTM without commenting, which can confuse some users. action needs to be taken after this so we probably ought to notify users.

/area prow
/kind feature

**Comment by krzyzacy** [comment]
@Q-Lee also got confused yesterday :-)

**Comment by cjwagner** [comment]
This is low hanging fruit.
/help

**Comment by qhuynh96** [comment]
I will pick this up. 
/assign
