### ISSUE TITLE
generated tests are out of sync

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7180]
https://github.com/kubernetes/test-infra/pull/7070
https://github.com/kubernetes/test-infra/pull/7179/files/2feaf66dce68a5555a3dee93b2e8aa0e18d1c2fe#r173068161

/kind bug
/area jobs
/assign
/assign @krzyzacy

**Comment by krzyzacy** [comment]
oh.... #7070 did not rerun generated tests :-\ this is WAI
