### ISSUE TITLE
config sort is unhelpful for prow config diffs

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7187]
we should stop sorting job entries in prow/config.yaml

Compare the original diff: https://github.com/kubernetes/test-infra/pull/7186/commits/a0b9066ee570b6c2e10710960e49e283e10e6a70

To the one after sorting: https://github.com/kubernetes/test-infra/pull/7186/commits/adc7a18cd73447cd3616d4011208845188fde5ef

since it's not version aware we also wind up with 1-10, 1-7, 1-8, 1-9 which is not a great ordering, compared to hand ordering where I most likely would have placed:
- build for master branch
- build for upcoming release
- build for current release
- build for N-1 release
- build for N-2 release
...

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
we are removing this once we have the config split
/assign @krzyzacy

**Comment by BenTheElder** [comment]
this is going away soon! I swear! almost there :-)

**Comment by krzyzacy** [comment]
☠️
