### ISSUE TITLE
velodrome deployment pattern is undocumented and not maintained

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7192]
https://github.com/kubernetes/test-infra/pull/7191#issuecomment-371668428

[I eventually figured out how to deploy this](https://github.com/kubernetes/test-infra/pull/6929#issuecomment-367542955) when I needed to make a change to the config once, but we don't have this documented other than that comment and the existing python | kubectl pattern is pretty gnarly. 

- we need to update the docs to reflect all steps necessary to deploy it
- we need to streamline the deployment eventually (lower priority, we're not deploying this often and shouldn't need to)

/kind bug
/priority important-longterm

**Comment by krzyzacy** [comment]
cc @apelisse

**Comment by BenTheElder** [comment]
I'm going to meet with @apelisse soonish to discuss velodrome, then I'll take a look at refreshing the docs and handling redeployment for #7350.

**Comment by spiffxp** [comment]
/assign
/remove-lifecycle rotten
I cringe doing this, but it's still undocumented, and I'm not going to get to it in the next little while.  But, I would like to understand how to set it up.  Let's see if I can get back here within 90d

**Comment by stevekuznetsov** [comment]
I looked into standing this up at some point and gave up when it was too hard. Whenever someone's ready to tackle this, we are probably ready to deploy it and help shape the doc :)

**Comment by spiffxp** [comment]
/unassign
aaaand I'm not going to get to it this release cycle

I swear all we want is a working influx + grafana + prometheus setup, I'm not really sure we rely on any of the actual "velodrome" code anymore

**Comment by apelisse** [comment]
:-)
