### ISSUE TITLE
retest-not-required-docs-only label

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#7195]
So a few questions:

1. Does prow add this automatically?  I thought it did in k/k, it is not in k/kops
2. Can we get a prow bot command for adding the label?  `/docs-no-retest` something like that.
3. I assume that tide / build queue still uses this label?  Basically do not want to re-run expensive e2e for a markdown file 😆

**Comment by BenTheElder** [comment]
1) is done via docs-no-retest https://prow.k8s.io/plugins 
2) there's no command for this IIRC, it's automatic on the PR diff
3) tide doesn't AFAIK... @cjwagner

**Comment by cjwagner** [comment]
Tide doesn't respect that label, but this is functionality that we are considering in this issue: https://github.com/kubernetes/test-infra/issues/5334

**Comment by nikhita** [comment]
/remove-lifecycle rotten

Enabling this would mean giving super powers to some people. :) Do we still want this?
