### ISSUE TITLE
Onboard kinflate on the test-infra

### ISSUE THREAD

**Issue by droot** [kubernetes/test-infra#7203]
Kinflate (https://github.com/kubernetes/kubectl/tree/master/cmd/kinflate) is CLI to manage YAML manifests for Kubernetes application. We want to leverage prow (test-infra) for integration testing of kinflate.

Key requirements:

- Be able to pull code from two separate repos (kinflate and kinflate-examples)
- Launch kubernetes cluster with provided version (say 1.9 as default for now)
- compile kinflate and run it against kinflate-examples to generate manifests
- run `kubectl apply` to deploy the manifests generated by kinflate in previous step
- verify the deployed app.
- terminate the cluster.

We want to run this job periodically to begin with and then later invoke it as a pre-submit check. Want to monitor the results in the test-grid somewhere.

**Comment by BenTheElder** [comment]
We should be able to do this starting with a job based on kubetest. 

Can you provide a script in kinflate to do this part:
- compile kinflate and run it against kinflate-examples to generate manifests
- run kubectl apply to deploy the manifests generated by kinflate in previous step
- verify the deployed app.

We have code / images / automation we can enable to do:
- [x] periodically run a job
- [x] Be able to pull code from two separate repos (kinflate and kinflate-examples)
- [x] Launch kubernetes cluster with provided version (say 1.9 as default for now)
  - also as part of this run some command against it with `$KUBECONFIG` configured, create JUnit entries for cluster up / down / the test command exit status
- [x] run your code, upload the logs, display in testgrid

**Comment by BenTheElder** [comment]
We met and discussed this offline, job setup will come ~ Monday once the kinflate script(s) are ready.

**Comment by BenTheElder** [comment]
I think this is done.
/close
