### ISSUE TITLE
make pull-kubernetes-typecheck blocking

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7206]
`pull-kubernetes-typecheck` is uses some awesome work by @rmmh to allow typechecking kubernetes's go code without actually building. we can typecheck for all (`GOOS`, `GOARCH`) we build for in ~4-5 minutes.
This is in contrast to a real cross build taking > 1 hour on a reasonably large VM. 

Specifically we should:
- make `pull-kubernetes-typecheck blocking`
- make `pull-kubernetes-cross` only run on PRs that touch the build scripts
- stop always running `pull-kubernetes-cross` against batch merges in favor of `pull-kubernetes-typecheck`

Branches older than master / 1.10 will continue to run `pull-kubernetes-cross` with the existing configuration until typecheck is ported for them.

**Comment by BenTheElder** [comment]
/area jobs
see:
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-typecheck

This job has been plenty "green" for a while now, and this idea has been discussed within #sig-release
https://kubernetes.slack.com/archives/C2C40FMNF/p1520283169000156

**Comment by cblecker** [comment]
+1. I explicitly support this change.

**Comment by BenTheElder** [comment]
Done in #7276
