### ISSUE TITLE
prow: trigger: why do we run postsubmits on merge children?

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7213]
Consider the case where `master` has at it's `HEAD` commit `A`, there exists a branch with `merge-base` `B` where the `HEAD` is `C`. A merge happens and creates commit `D`. We have this:

```
master: -- B -- A -- D
   dev:    `--- C ---'
```

Currently in this case we get a `PushEvent` for both `C` and `D` landing in `master`. However, `C` is _not_ ever a valid state of the `master` branch and therefore I do not think a postsubmit job configured for `master` branch should run with that ref. It's reachable, but ultimately not useful.

/area prow
/kind bug
/cc @cjwagner @BenTheElder @kargakis @fejta @spxtr @smarterclayton

**Comment by kargakis** [comment]
See https://github.com/kubernetes/test-infra/issues/3910, @spxtr's worry is that folks may push directly in master, in which case there is no merge commit.

**Comment by stevekuznetsov** [comment]
I'm not saying we should run only for merge commits. Just that we should _not_ run for merge children.

**Comment by spxtr** [comment]
Is it possible to tell from the push event for `C` that it is a child? If so, it makes sense to skip testing it.

**Comment by stevekuznetsov** [comment]
We have the full GitHub and `git` clients and it's possible to tell that `C` is the child of a merge commit in the branch, yes. I'll write something up today.

**Comment by stevekuznetsov** [comment]
@kargakis @smarterclayton so this is embarrassing ... I can't reproduce this behavior. None of the recent merges to any of our repos have sent a `push` webhook for anything other than the merge commit and I don't see postsubmits being triggered for anything other than the commit at `HEAD`. Do we have specific examples of where we saw this?

**Comment by cjwagner** [comment]
Closing until we see examples of this occurring.
/close
