### ISSUE TITLE
Kubeflow jobs cannot write to bucket kubernetes-jenkins/pr-logs

### ISSUE THREAD

**Issue by lluunn** [kubernetes/test-infra#7229]
Kubeflow is switching to a new testing project, kubeflow-ci, https://github.com/kubeflow/testing/issues/18.

kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com does not have storage.objects.create access to kubernetes-jenkins/pr-logs/directory/kubeflow-presubmit/591.txt.

Can we grant that service account kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com access to kubernetes-jenkins?

**Comment by BenTheElder** [comment]
Normally we have the test jobs use a service account we own/control for upload. In the future this service account won't even be passed through to the tests once we switch to steve's pod utils. why aren't these jobs using the standard service account?

**Comment by krzyzacy** [comment]
I guess alternatively, your job can write to your own bucket, and grant access to gubernator/testgrid to pull from your bucket. Depend on which way you want to go.

**Comment by lluunn** [comment]
I see, sorry I didn't understand the process.

**Comment by krzyzacy** [comment]
I'll grant your service account permission to kubernetes-jenkins bucket for now, as we are still using bootstrap. In the future we can revamp the upload behaviors.

**Comment by krzyzacy** [comment]
(commented in the other issue https://github.com/kubeflow/testing/issues/18#issuecomment-372830265)

**Comment by lluunn** [comment]
thanks!
