### ISSUE TITLE
Strange things happening with steps shown on testgrid

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#7242]
Starting from ~1 day ago, I'm seeing weird steps (i.e they're repeated twice) on testgrid:

- https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-1.9
- https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-1.8
- https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-1.7

This seems to be happening on our release-branch jobs, and not on the [master one](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce)

@kubernetes/test-infra-maintainers - Any idea what's up? :)

**Comment by shyamjvs** [comment]
Correction: I'm seeing it also on some jobs running against master. E.g:

- https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100
- https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100-high-density

**Comment by BenTheElder** [comment]
This is a known bug with the collector that was rolled back, a notice from
Michelle went out in #sig-testing and #testing-ops but not more widely.
Sorry about that.

**Comment by BenTheElder** [comment]
You'll still see these for a while since testgrid has caching.

**Comment by BenTheElder** [comment]
cc @amwat

**Comment by amwat** [comment]
This issue has been fixed. Closing it for now. 
/close
