### ISSUE TITLE
tide context is left to "Not mergeable" state

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7254]
Even though the PR is mergeable (and eventually merges)

eg. https://github.com/kargakis/acs-engine/pull/17

@cjwagner 

/area prow

**Comment by kargakis** [comment]
> This could have happened if the lgtm label was added in between the query for pool PRs and the query for all open PRs. The open PR query is more up to date and could have seen that the lgtm label was present and then not known why the PR didn't meet the merge requirements (hence the status).

That's what happened - once I `lgtm`ed the PR, the status changed from the expected "Not mergeable. Missing lgtm" message to "Not mergeable" and stayed liked that for ever. Unclear whether we were ratelimited, we really need metrics for this.

**Comment by Ark-kun** [comment]
> That's what happened - once I `lgtm`ed the PR, the status changed from the expected "Not mergeable. Missing lgtm" message to "Not mergeable" and stayed liked that for ever. Unclear whether we were ratelimited, we really need metrics for this.

/reopen

I just hist that in https://github.com/kubeflow/pipelines/pull/2646 
Tide's PR status says "Good to be merged" https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubeflow%2Fpipelines+author%3AArk-kun+head%3ASDK---Client---Fixed-Client-on-Windows---2
GitHub's Tide status is "Pending — Not mergeable." https://github.com/kubeflow/pipelines/pull/2646 
Tide status has nothing for the repo. https://prow.k8s.io/tide
