### ISSUE TITLE
Prow issue: cannot assign issue to me even I am Kubernetes member and SIG lead

### ISSUE THREAD

**Issue by adohe** [kubernetes/test-infra#7269]
FYI. I tried to assign an issue to me in `kubernetes/kubectl` repo, but the ci-robot said I am not allowed to do this, I am just confused since I am already kubernetes member and kubectl maintainer.

**Comment by adohe** [comment]
the related issue: https://github.com/kubernetes/kubectl/issues/346

**Comment by BenTheElder** [comment]
> /assign @aodhe

You swapped the `d` and `o` in your username :-)
I've assigned you to the issue.

/close
