### ISSUE TITLE
Change how Tide handles jobs with failing tests.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#7279]
Tide doesn't really handle PRs with failing tests very well:
- PRs can appear in Tide's "Passing" column if they have failing status contexts that are not controlled by Tide (e.g. code coverage statuses or reviewable statuses).
- PRs that meet all label requirements, but have failing tests are considered to be in the tide pool, but won't become mergeable because Tide won't automatically retest PRs with failing tests. This is confusing. It would be better if the PR's 'tide' context indicated that it was unmergeable due to a test failure and it should not appear on the Tide dashboard.

We can't just limit the tide query to PRs that have all statuses passing, because that would exclude PRs where all contexts are passing except the Tide context. However, we can filter out PRs with failing status contexts locally and ignore the 'tide' context (and any other contexts we want to ignore).

If we filter out failing PRs from the pool before syncing and setting statuses, the Tide dashboard won't show failing PRs and the 'tide' status context will show that failing PRs are not mergeable. We can also improve the status description to mention which contexts are failing if that is actually useful.

Please let me know if this seems reasonable.
/area prow
/kind bug
/assign
/cc @spxtr @kargakis @stevekuznetsov @BenTheElder

**Comment by cjwagner** [comment]
cc @rmmh

**Comment by BenTheElder** [comment]
> If we filter out failing PRs from the pool before syncing and setting statuses, the Tide dashboard won't show failing PRs and the 'tide' status context will show that failing PRs are not mergeable. We can also improve the status description to mention which contexts are failing if that is actually useful.

:+1:, I've been discussing with Quang that the user PR status page needs to reconcile with these third party statuses as well. xref https://github.com/kubernetes/test-infra/issues/7235

**Comment by stevekuznetsov** [comment]
Updating the transitions into the pool and into "passing" state SGTM
