### ISSUE TITLE
Prow dashboard does not allow me to filter errored jobs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7294]
But shows to me that they exist (just one in this case but the point still stands).
![error](https://user-images.githubusercontent.com/3900799/37458501-7daf2efc-2845-11e8-9f15-3550de96bee9.png)
I couldn't printscreen with the state filter open so you have to trust me on this :)

@BenTheElder @qhuynh96

**Comment by qhuynh96** [comment]
I trust you 👍 I investigated this and found that the state filter only take pre-submit jobs's state into account

https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/static/script.js#L35

I don't know what is the intention behind this. Maybe @cjwagner or @BenTheElder can confirm.

**Comment by kargakis** [comment]
I can confirm that this was a postsubmit job.

**Comment by qhuynh96** [comment]
Did you mean the error job was a post submit job?

**Comment by qhuynh96** [comment]
Yup, so that explained why there is no error job in the filter. I can have a quick fix for this if there is no special reason by the state filter should be pre-submit only.

**Comment by BenTheElder** [comment]
@rmmh also suggested that the displayed states below the filtering options ought to be clickable -> should go to that state being filtered.

**Comment by BenTheElder** [comment]
There shouldn't be any special reason for that code being only presubmit @qhuynh96
