### ISSUE TITLE
prow: deck: show overview page for a ProwJob

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7299]
Right now we can see the full list of jobs that ran, but it would be great to be able to open up a single job and see at the very least the job specification that was used to run it -- the refs involved, etc. 

/kind enhancement
/area prow
/cc @BenTheElder @qhuynh96

**Comment by stevekuznetsov** [comment]
FWIW `pjutil.JobSpec` describes the job's variables, so exposing that would be a great start.

https://github.com/kubernetes/test-infra/blob/37cdb7ce6625dffb1cf57ac31c1c15502a83be8b/prow/pjutil/jobspec.go#L35-L52

**Comment by qhuynh96** [comment]
Probably doing when I come back Australia :laughing:

**Comment by stevekuznetsov** [comment]
Yeah! Or I can take a stab at it, too!

**Comment by rmmh** [comment]
Do you want a linkable page on prow to show a job's details? If you click the rerun button and follow the link, you can see the pod spec.

**Comment by stevekuznetsov** [comment]
Yes, a nice table with good formatting showing me what the job was that ran -- a step up in UX from the `PodSpec`.

**Comment by stevekuznetsov** [comment]
I'm actively working on this.

**Comment by qhuynh96** [comment]
Thanks Steve

**Comment by qhuynh96** [comment]
I just have a quick look at the prototype. Is Job Status going to display all jobs as Prow Status does?

**Comment by stevekuznetsov** [comment]
Intent is for it to be searchable, right now supports by job/id or org/repo/author, etc.

**Comment by stevekuznetsov** [comment]
This is #9374 
/close
