### ISSUE TITLE
kubemark tests are failing in 1.7 and 1.8 branches

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/test-infra#7316]
They are all failing due to:
```
W0316 07:59:15.764] # k8s.io/test-infra/vendor/github.com/json-iterator/go
W0316 07:59:15.765] ../../test-infra/vendor/github.com/json-iterator/go/config.go:107: undefined: sync.Map
```

Example run: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/61122/pull-kubernetes-kubemark-e2e-gce/81652/build-log.txt

This seems to be because:
- 1.7 and 1.8 branches are using older version of Golang
- sync.Map was introduced in Go 1.9

I'm not sure how to solve this problem thought...

**Comment by wojtek-t** [comment]
@kubernetes/test-infra-maintainers @krzyzacy

**Comment by liggitt** [comment]
Kubemark rebuilds kubetest after 24 hours if stale. The go version in 1.7. and 1.8 won't build kubetest from master

**Comment by liggitt** [comment]
@krzyzacy build a new version of kubetest previously to buy us 24 hours, and added a `touch` call to make kubetest appear newer to prevent rebuild during the run, which looks like it didn't work

**Comment by krzyzacy** [comment]
@liggitt I did not merge https://github.com/kubernetes/test-infra/pull/7290 yet due to the cluster up issue in gce

**Comment by krzyzacy** [comment]
http://k8s-testgrid.appspot.com/sig-testing-canaries#gce-canary went back to green, I'll kick that in

**Comment by krzyzacy** [comment]
I retested on linked PRs and they were passing, closing this
