### ISSUE TITLE
Members should be able to add cherrypick-candidate label to PRs

### ISSUE THREAD

**Issue by jennybuckley** [kubernetes/test-infra#7332]
My understanding is that there is no command which allows any org member to add this label to their PR (at least according to [the list](https://prow.k8s.io/command-help)), despite [the guide](https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md) suggesting that the second step of cherry picking is putting that label on the PR.

Could be solved by the ```/cherrypick``` command supporting adding the ```cherrypick-candidate``` label to PRs.
Like, ```/cherrypick candidate```

**Comment by BenTheElder** [comment]
cc @kargakis who has an experimental external plugin for this IIRC
right now cherry picking functionality is not yet moved over to Prow, we should do this. 👍

**Comment by kargakis** [comment]
We have been using the cherrypick bot for some months now in openshift as an external prow plugin and it has been working great.

**Comment by kargakis** [comment]
https://github.com/kubernetes/test-infra/tree/master/experiment/cherrypicker

Should be moved under https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/

**Comment by spiffxp** [comment]
/close
We have since removed the cherrypick-candidate label.  But it would be nice if we could land /cherrypick
