### ISSUE TITLE
prow: sidecar: upload more metadata about the job in finished.json

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7364]
While we figure out a long-term plan for job metadata in GCS, we need to shim the `sidecar` to upload more data into `finished.json` for backwards compatibility.

/kind bug
/area prow
/assign @rmmh 

@rmmh as you're much more familiar with the fields and what they represent, can you either make the changes required or provide a JSON schema/struct definition for the data you'd like to see in `finished.json` so I can plumb it through?

**Comment by stevekuznetsov** [comment]
@rmmh

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/9510

**Comment by spiffxp** [comment]
/milestone v1.14
/unassign @rmmh 

FYI @cjwagner @stevekuznetsov @BenTheElder 

I thought someone was working on this but I'm not sure who?

**Comment by BenTheElder** [comment]
@krzyzacy was I think?

**Comment by krzyzacy** [comment]
We have incorporated metadata.json, and all other information are in clone-records.json

I think we can make gubernator & spyglass understand clone-records.json instead?

**Comment by spiffxp** [comment]
/close
Based on https://github.com/kubernetes/test-infra/issues/3412#issuecomment-465879038 I feel like we've agreed we're uploading enough.  Let's open specific issues if there are specific things missing
