### ISSUE TITLE
Install OpenLab Github app for kubernetes/cloud-provider-openstack

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#7371]
For just the kubernetes/cloud-provider-openstack repository, can you please install the the "openlab-ci" github app: https://github.com/apps/theopenlab-ci.

A few of us from OpenStack community are building test infra for running Kubernetes on several OpenStack providers including several versions of OpenStack and would like to 
- Report back on new PR(s) when unit/functional tests that need a real OpenStack cloud 
- Run periodic jobs to check health of the code against stable and master branches of k/k
etc...

cc @kiwik @animationzl @hogepodge @liu-sheng

**Comment by dims** [comment]
/assign @calebamiles 

Caleb, Please redirect as appropriate

**Comment by kiwik** [comment]
https://github.com/theopenlab/cicd-howto#connect-to-openlab

**Comment by kiwik** [comment]
This is a reference about how to access OpenLab.

**Comment by dims** [comment]
Counter proposal (after a chat with @fejta) - Is it possible to write a prow plugin similar to what we had with jenkins before? to interact with Zuul/OpenLab CI. code for jenkins plugin is https://github.com/kubernetes/test-infra/tree/master/prow.

```
fejta [2 hours ago]
What prevents us from writing a prow controller to interface with OpenLab CI and/or Zuul?

fejta [2 hours ago]
This would be better because a) other prow users would then have access to OpenLab CI and/or Zuul and b) it will interface better with the rest of our automation like tide (so /retest would work, for example)

dims [27 minutes ago]
@fejta do you have an example (pardon my lack of prow knowledge)


fejta [23 minutes ago]
If you check prow/config.yaml from like 6mo ago you'll see jobs with an `agent: jenkins` instead of `agent: kubernetes` but we don't have any active examples. Talk to @kargakis or @steve who both use jenkins still. Here's the controller: https://github.com/kubernetes/test-infra/tree/master/prow/jenkins
```

**Comment by kiwik** [comment]
OpenLab CI/CD system based on OpenStack Zuul, currently Zuul can connect to Github project by using Github APP or Webhook [1], both of that should be set in project side, Github APP is more easy way, so we create OpenLab APP [2] that require minimum privilege to report the test result in RP comments, you can see details in APP install page. Currently Zuul don't support prow yet, so if we want to test kubernetes/cloud-provider-openstack in OpenLab, we should install OpenLab APP into kubernetes/cloud-provider-openstack project.

[1]: https://docs.openstack.org/infra/zuul/admin/drivers/github.html#application
[2]: https://github.com/apps/theopenlab-ci

**Comment by dims** [comment]
@fejta had a discussion with the zuul team. http://eavesdrop.openstack.org/irclogs/%23zuul/%23zuul.2018-03-29.log.html#t2018-03-29T02:36:51 

So far it seems like the Webhook or App is what would work as Zuul needs better support for triggers. I can drop by sig-testing meeting and we can talk a bit more.

thanks,
Dims

**Comment by fejta** [comment]
Officially the rules for [core repositories](https://github.com/kubernetes/community/blob/master/kubernetes-repositories.md#rules-2) ask to adopt kubernetes automation, so that we have a consistent experience across the org.

The best way to do this is to integrate prow with openlab/zuul, just like it does with kubernetes and jenkins.

That way we ensure that we can define and configure when/whether jobs run in a single location, regardless of the CI system that ends up running the job.

On a technical level, there is nothing preventing an administrator configuring a repo to send webhooks to OpenLab, Travis, CircleCI, etc.

**Comment by kargakis** [comment]
Agreed with @fejta 

Ideally you should build a client to talk to the zuul api and a controller that handles prowjobs of `agent: zuul` type (see the [jenkins operator](https://github.com/kubernetes/test-infra/tree/master/prow/jenkins) as an example). The controller should be responsible for starting jobs in zuul based on prowjobs and report status back to github.

Then you can reuse all of the existing prow components: hook (for accepting webhooks from the github repo and creating prowjobs), horologium (for running periodic jobs), deck (for interfacing with those jobs), and tide is kept in the loop so you can also have automated merges.

**Comment by dims** [comment]
/close 

i have a following up issue in https://github.com/kubernetes/test-infra/issues/7475
