### ISSUE TITLE
gubernator: broken links for repos with underscore in name

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/test-infra#7389]
gubernator seems to replace the `/` which separates org/user and the repo name in a repo's full name (`github.com/some_org`**/**`some_repo`) with a `_`. When gubernator then renders links which should point back to the github repo it replaces the `_` again with `/`.

This is incorrect for repos with a name which already contains a `_`.
For example for the repo `github.com/kubernets-sigs/testing_frameworks` gubernator will render links to `github.com/kubernetes-sigs/testing/frameworks/...`

![screen shot 2018-03-23 at 14 12 49](https://user-images.githubusercontent.com/1401333/37833867-6054297e-2ea4-11e8-8e31-66f738e3f0ed.png)

See also at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_testing_frameworks/49/pull-frameworks-test/7/ -- here the links in the table point to a wrong location at `https://github.com/kubernetes-sigs/testing/frameworks/...`

**Comment by rmmh** [comment]
We can resolve this specific issue in favor of `org/name_repo`, but we need to start including (and preferring) base repo information in started.json and finished.json.
