### ISSUE TITLE
First time tests run on a project it cannot ssh to nodes

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#74]
per @spxtr we need to run `gcloud compute config-ssh` before running tests. Otherwise some raw ssh tests will fail the first time we run tests on this node, until we later run `gcloud compute ssh` to that node to collect logs

**Comment by fejta** [comment]
Plan is to store the public/private ssh key on the master.
Then when we create/attach jenkins instances we will copy the key from the master to right location on the agent.

**Comment by ixdy** [comment]
Is the issue new GCP projects or new Jenkins agents? The title of this issue sounds like the first, but your most recent comment sounds like the last.

**Comment by ixdy** [comment]
If the issue is new Jenkins agents, #66 will fix this.

**Comment by fejta** [comment]
The problem is both that new agents tend to have different keys and new projects don't have these credentials added to them by default, neither of which is necessary.

#66 addresses the former problem

**Comment by fejta** [comment]
https://github.com/kubernetes/kubernetes/pull/26333 fixed this
