### ISSUE TITLE
One gcp vpc has a legacy vpc

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#7400]
I will track down the region, but one of the gcp vpcs where e2e testing runs, has a legacy vpc. It probably should be deleted an recreated. This causes kops to not be happy since kops does not support legacy vpcs.

**Comment by krzyzacy** [comment]
cc @MrHohn do we still use these?

@chrislovecnm which project it is, can you attach a build log?

**Comment by MrHohn** [comment]
> cc @MrHohn do we still use these?

Not that I know of. And if a specific job requires legacy VPC, it should use explicit project (pool) I think.

**Comment by BenTheElder** [comment]
Can we clean these up then..?

**Comment by krzyzacy** [comment]
> Can we clean these up then..?

I think they should? that's why I was asking for an example
