### ISSUE TITLE
ginkgo erring with "Found no test suites"

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#7404]
I am trying to test kubetest and k/k changes with kops on gce.  I am getting this error from ginkgo:

```
chlove@build-01:~/Workspace/src/k8s.io/kubernetes$ /home/chlove/Workspace/src/k8s.io/kubernetes/bazel-bin/vendor/github.com/onsi/ginkgo/ginkgo/linux_amd64_stripped/ginkgo --nodes=25 '' -- --kubeconfig=/tmp/kops056724377/kubeconfig --ginkgo.flakeAttempts=1 --host=https://104.154.118.213 --provider=gce --gce-project=chlove-57705 --gce-zone=us-central1-a --gce-region= --gce-multizone=false --gke-cluster=chlove.k8s.local --kube-master= --cluster-tag= --cloud-config-file= --repo-root=/home/chlove/Workspace/src/k8s.io/kubernetes/cluster/.. --node-instance-group=a-nodes-chlove-k8s-local --prefix=e2e --network=e2e --node-tag= --master-tag= --cluster-monitoring-mode=influxdb --ginkgo.flakeAttempts=2 --ginkgo.skip='\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort' -v 10
Found no test suites
For usage instructions:
	ginkgo help
```

That is the command that is being run after all the setup by `kubetest` and `hack/ginkgo-e2e.sh`.  Ginkgo is failing with "Found no test suites".  The command I think is running from the root Kubernetes directory, but I have not idea how Ginkgo finds the test suites.  Looked through the Ginkgo code and it seems to be a section where it loads the test suites, but I would assume that it could do that from the `kubernetes` directory.

I do get the exact same error by running just `ginkgo` from the root kubernetes directory.

Here is the actual script that I am running to run kubetest;

```sh
export GOPATH=$HOME/Workspace
export PATH=$PATH:$GOPATH/bin
export KOPS_STATE_STORE=gs://chlove-state-store/
test-kubetest() {
	cd $GOPATH/src/k8s.io/kubernetes
        MYIP=$(curl ipinfo.io | jq -r .ip)
	WORKSPACE=/tmp
	LOG_DUMP_SSH_USER=admin
	KUBE_SSH_USER=admin
	RELEASE="ci/latest"
	VERSION=$(gsutil cat gs://kubernetes-release-dev/$RELEASE.txt)
	CLUSTER=chlove.k8s.local
	ETCD=3.1.10

	  #--up --down --test \
	$GOPATH/src/k8s.io/test-infra/bazel-bin/kubetest/linux_amd64_pure_stripped/kubetest \
	  --kops=$GOPATH/bin/kops \
	  --kops-ssh-key=$HOME/.ssh/google_compute_engine \
	  --deployment=kops \
	  --build=bazel \
	  --kops-admin-access ${MYIP}/32 \
	  --gcp-project=redacted \
	  --up --down --test \
	  --provider=gce \
	  --ginkgo-parallel '--test_args=--ginkgo.flakeAttempts=2  --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort' \
	  --cluster ${CLUSTER} \
	  --kops-state=${KOPS_STATE_STORE} \
	  --kops-nodes 3 \
	  --kops-ssh-user admin \
	  --kops-zones=us-central1-a \
	  --kops-etcd-version $ETCD
}
```

**Comment by fejta** [comment]
How are you invoking gingko? Ideally you do this through kubetest

**Comment by dims** [comment]
the `--test_args` looks bad @chrislovecnm here's what i usually use, can you try that? if that works then you can fiddle with the test_args to what you need

```
    --ginkgo-parallel=1 \
    --test_args="--ginkgo.focus=[Conformance] -v=8" \
```

**Comment by chrislovecnm** [comment]
@fejta 

> How are you invoking gingko? Ideally you do this through kubetest

I am executing kubetest and at the end of the day it runs ginkgo, and that is failing.

@dims the nutty thing is that I am copying the arguments from a test that runs.  We do not have a focus setting on the e2e test, we just pass in the skips.  I will try the focus, and also try not doing a local build.  My need is to test changes that I am working on for ginkgo-e2e.sh script in the main repo, so I was trying to get a local bazel build to work.

**Comment by dims** [comment]
@chrislovecnm show me the url for the job's logs please?

**Comment by chrislovecnm** [comment]
Here is one - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-gce/6891

```
./hack/ginkgo-e2e.sh --ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort --report-dir=/workspace/_artifacts --disable-log-dump=true
```

That was how ginkgo-e2e.sh was executed by kubetest.

**Comment by chrislovecnm** [comment]
Another example for aws test - https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-canary/8012/build-log.txt

here is the way it is being run
```
./hack/ginkgo-e2e.sh --ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort --report-dir=/workspace/_artifacts --disable-log-dump=true
```

All of this is being started by running kubetest.
