### ISSUE TITLE
Ubuntu e2e tests are failing with "Cannot operate on cluster using node os distro: custom"

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/test-infra#7415]
DumpClusterLogs step is failing across test suites, e.g.:
- https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gke-ubuntu1-k8sbeta-autoscaling
- https://k8s-testgrid.appspot.com/sig-network-gke#gke-ubuntu1-k8sstable3-ingress

with `W0326 10:51:41.165] Cannot operate on cluster using node os distro: custom`

**Comment by yguo0905** [comment]
Waiting https://github.com/kubernetes/kubernetes/pull/61429 to be merged into 1.8.
I will create a cherry pick for 1.10 as well.
