### ISSUE TITLE
tools: hack/update-bazel requires a network connection

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7416]
This was pretty frustrating on a 6h flight I expected to be productive on! We should not require a network connection for the most basic dev iteration flows.

/kind bug
/cc @BenTheElder @ixdy

**Comment by ixdy** [comment]
ack, sorry. we need to resolve the three-way dependency on bazelbuild/buildtools (test-infra uses an incompatible version with gazelle), but other than that this should be easy to vendor.

/assign

**Comment by BenTheElder** [comment]
/area bazel
/priority important-soon
definitely agree, we need to get these vendored in a few places

**Comment by ixdy** [comment]
first part of untangling dependency versions in https://github.com/kubernetes/repo-infra/pull/65
