### ISSUE TITLE
tools: a number of targets are not cached and make bazel test //... slow

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7437]
The majority of targets are cached without issue, but a couple (notably `pylint`) make `bazel test //...` really slow and annoying. Here's a run with one `BAZEL.build` file changed between this run and the last one:

```
$ bazel test //...
INFO: Analysed 2110 targets (538 packages loaded).
INFO: Found 1987 targets and 123 test targets...
INFO: Elapsed time: 87.446s, Critical Path: 68.61s
INFO: Build completed successfully, 121 total actions
//boskos:go_default_test                                        (cached) PASSED in 1.4s

...

//velodrome/transform/plugins:go_default_test                   (cached) PASSED in 1.2s
//hack:verify-pylint                                                     PASSED in 64.3s
//hack:verify-spelling                                                   PASSED in 14.6s
//hack:verify_boilerplate                                                PASSED in 3.8s

Executed 3 out of 123 tests: 123 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

We should figure out how to make `pylint` and `spelling` and `boilerplate` incremental or faster. 

/cc @ixdy @BenTheElder @rmmh

**Comment by BenTheElder** [comment]
they python targets are not really cacheable because they take in the whole repo and aren't properly hermetic, we've got lints in a separate job while we decide what to do with them.

not sure about the velodrome / boskos tests.

**Comment by stevekuznetsov** [comment]
Looks like `pylint` and `spelling` already parallelize, but `boilerplate` does not -- no super simple throughput wins that I can see. Maybe there is some `bazel` magic that can make `pylint` not run when no Python files have changed?

The `velodrome` and `boskos` got cached correctly, just didn't elide them from the output.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/7041 took care of all of that
short of making them manual. you can run bazel test ... with --config=unit
or --config=lint

**Comment by stevekuznetsov** [comment]
Yeah I guess I was hoping for one button that would do Go unit + Go lint + boilerplate + bazel verify, basically everything that I would generally hit if I were iterating on Prow, but not other targets. Maybe I'm just imagining a world where `prow` is in it's own repo :)

**Comment by rmmh** [comment]
It's possible to do incremental/cached pylint results too, but probably not inside of bazel.

**Comment by stevekuznetsov** [comment]
No action items on this

/close
