### ISSUE TITLE
prow: clonerefs: bound the number of parallel clones

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7438]
We should expose as a config option and a flag the maximum number of parallel clones that we want to happen.

/cc @fejta 
/assign

**Comment by stevekuznetsov** [comment]
/kind feature
???

**Comment by rmmh** [comment]
Why?

**Comment by stevekuznetsov** [comment]
@fejta requested it

**Comment by fejta** [comment]
Heh no longer remember why I suggested this, but thanks for fixing! 😁
