### ISSUE TITLE
Dropping CI support for 1.7

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#7459]
since 1.10 is out.
/assign

cc @wojtek-t I think I'm gonna wait until the last 1.7 release cut, sounds good to you?

**Comment by BenTheElder** [comment]
/cc
:+1:

**Comment by wojtek-t** [comment]
Yeah - let's wait couple more days - I would like to cut one more last 1.7 release and then we should drop the CI support.

**Comment by krzyzacy** [comment]
@wojtek-t great :-) I'll prepare the PR

**Comment by krzyzacy** [comment]
done from https://github.com/kubernetes/test-infra/pull/7620
