### ISSUE TITLE
tide status controller fails continuously with 502

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7466]
```
{"component":"tide","controller":"status-update","error":"unexpected status: 502 Bad Gateway","level":"error","msg":"Searching for open PRs.","time":"2018-03-29T08:21:54Z"}
```
@stevekuznetsov @bbguimaraes @cjwagner

**Comment by cjwagner** [comment]
/reopen

This is still an issue that we are encountering more and more often as the number of repos we are querying grows. GitHub is aware of a problem in which queries for large numbers of PRs time out: 
- https://platform.github.community/t/sporadic-502s-fetching-pr-data/3024/8
- https://platform.github.community/t/randomly-unable-to-fetch-commit-author-fields-author-authoreddate-authoredbycommitter-api-returns-502s/5217/3

Currently, the recommended work around is to request fewer PRs. I'm not sure if reducing the number or PRs per page will be sufficient or if we will need to stop looking up open PRs for *all* repos with a single query, but we should try to fix this. Reducing the page size is the simplest thing to try so I'll experiment with that first.

**Comment by BenTheElder** [comment]
What about automatically sharding the repos in the query to sub-queries
with a maximum number of repos?
We can only reduce the page size so much, and that only reduces bandwidth,
I'd guess on GitHub's end the expensive part is searching more repos.
