### ISSUE TITLE
[Feature request] Boskos can suggest gcp region/zones

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/test-infra#7477]
Boskos already suggests what (GCP) project to use for a test job if it's not specified in the job configuration. If Boskos can be extended to suggest what GCP region/zone to use when it's not set, we can further trim down the flags in the configuration.

/cc @krzyzacy

**Comment by krzyzacy** [comment]
this probably will be rolled into https://github.com/kubernetes/test-infra/issues/8427
