### ISSUE TITLE
Diffresources fails on gce due to resources from test running in parallel.

### ISSUE THREAD

**Issue by bskiba** [kubernetes/test-infra#7486]
In our autoscaling e2e test suits we have some dedicated projects that we run tests in. There can be two tests running in the same project simultaneously. 

The tests themselves are fine and they don't interfere with each other, but there are fails in diffresources (see for example: https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gce-autoscaling). The problem is that diffresources sees resources from the other test and incorrectly reports them as leaked.

For example in this run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling/6248
we have a job launched with cluster=ca, so all resources' names start with ca. However diffresources is reporting hpa-master-ip leaked, which belongs to the other test.
An example of the opposite case (hpa test reporting ca-master-ip leaked): https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-hpa/1078

The problem exists only on plain GCE (we have a similar setup with tests in GKE but it works fine).
The configs of tests that have a common project:
CA: https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L4587
HPA: https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L4607

**Comment by BenTheElder** [comment]
`ci-kubernetes-e2e-gci-gce-autoscaling` sets the following flag in its `jobs/config.json` entry:

> "--check-leaked-resources",

I suspect this flag is not meant to be safe with multiple jobs running in the same project. @krzyzacy

**Comment by krzyzacy** [comment]
yeah, @bskiba feel free to disable the flag for your job

**Comment by bskiba** [comment]
Thanks! Closing
