### ISSUE TITLE
gubernator/test-grid is unusable for anyone with red-green colorblindness

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#750]
e.g. https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gci-gke-slow/

Just adding a checkmark/X in addition to the coloring is probably enough? I'm not colorblind so I don't know what would be best to fix this.

**Comment by rmmh** [comment]
No, the colors have sufficient contrast to be easily distinguishable. Closing until someone with colorblindness finds the contrast level to be insufficient.

![image](https://cloud.githubusercontent.com/assets/211868/19097255/f7f22684-8a57-11e6-9475-03bba0cb10d8.png)
![image](https://cloud.githubusercontent.com/assets/211868/19097267/22004faa-8a58-11e6-9a65-c92a82514bfb.png)
![image](https://cloud.githubusercontent.com/assets/211868/19097275/30725f24-8a58-11e6-9784-acd0750023bc.png)

**Comment by lavalamp** [comment]
oh, awesome!
