### ISSUE TITLE
tide search cannot get back PRs for private repos

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7501]
How to reproduce:
* build https://github.com/kubernetes/test-infra/pull/7500
* reuse the tide token
* ensure that a PR satisfies a tide query for a private repo 
* run https://github.com/kubernetes/test-infra/pull/7500

No PRs are returned for private repos.

@stevekuznetsov seeing this with online-registration

**Comment by cjwagner** [comment]
Is the bot a member of the private organization/repo? Our Tide instance works properly on private repos.

**Comment by cjwagner** [comment]
If you log in as the bot can you view/search for the PRs?

**Comment by stevekuznetsov** [comment]
This was a dumb permissions error.
/close
