### ISSUE TITLE
k8s-ci-robot adds lgtm to PRs without reviewer's lgtm 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/test-infra#7510]
Does @k8s-ci-robot add `lgtm` to some PRs (such as cherrypicks) automatically? 

For example, in https://github.com/kubernetes/kubernetes/pull/61797 (a cherrypick), the bot adds `lgtm` even though no reviewers have commented "lgtm". 

IMO, the bot shouldn't do so although the original PR has been lgtm'd. Sometimes a cherrypick isn't exactly the same as the original fix, because the code was changed between releases. I've caught some bugs when reviewing cherrypicks before, so I think it's safer to have another round of review for cherrypicks. 

We should at least document the bot's behavior.

**Comment by rmmh** [comment]
No, it doesn't do that. @bowei made a comment "/lgtm /approve", and then deleted it 30 seconds later. `/lgtm cancel` should have been used to remove the lgtm-- the bot doesn't remove labels on when comments are deleted.

**Comment by janetkuo** [comment]
Thanks @rmmh. Closing as the bot is doing the right thing.
