### ISSUE TITLE
upgrade to go 1.10.1

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7513]
xref: https://github.com/kubernetes/kubernetes/pull/60597

/area images
/assign

**Comment by cblecker** [comment]
Note that https://github.com/kubernetes/kubernetes/pull/60599 will need to be merged shortly after CI is upgraded.

**Comment by BenTheElder** [comment]
This PR will update the e2e images, though for kubernetes we're generally not actually using the go installed with them [using it from the build images via dind, or from bazel] (other repos that stay in sync with kube do though). https://github.com/kubernetes/test-infra/pull/7515

Making another PR to upgrade the image used by verify, which will need to be in sync with your k/k PR @cblecker

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/7517
