### ISSUE TITLE
tide batches newest PRs instead of oldest

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#7561]
This means the same pool can be repeatedly tested and fail while the oldest PRs are tested and merged serially. Batches and serial tests should operate on the same queue, not different ends!

![image](https://user-images.githubusercontent.com/211868/38342987-4e55c9e4-3836-11e8-8ccf-d10942a9a644.png)

**Comment by cjwagner** [comment]
This problem was introduced when we switched from unbounded batches to bounded batches. I think that all we need to do is sort the PRs by increasing number before looping through them in `pickBatch()`.

**Comment by stevekuznetsov** [comment]
Why did we bound batches? Why not do log(N) batches of size 1,2,4,...log(N) ?

**Comment by BenTheElder** [comment]
> Why did we bound batches? Why not do log(N) batches of size 1,2,4,...log(N) ?

I would also like to know why we are bounding batches. This sounds more reasonable to me.

**Comment by cjwagner** [comment]
I agree that we shouldn't be bounding batches, their size should be dynamic. Either way the batch size won't be the entire pool though, so we will still need to sort the PRs.

Multiple batches sounds good to me, but will require a bit of a rework of Tide. Currently it is designed to work with one pending batch per subpool.

**Comment by stevekuznetsov** [comment]
We did it here: https://github.com/kubernetes/test-infra/pull/5953

Maybe we can just revert that?

**Comment by kargakis** [comment]
Unbounded batches is a separate issue although it caused this one. I am fine with reverting but we need to keep in mind that the bigger a batch is the higher chance of a test failure. Maybe a separate issue for enhancing the batch logic to trigger different sizes of batches?

This issue is fixed.

**Comment by fejta** [comment]
Which PR fixed the sorting issue?
