### ISSUE TITLE
Present build step failures in junit files?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#76]
e.g. resource leaks would be handy in a junit file: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/17595/consoleFull#-167188570730f50738-9bd5-4d49-9dda-6ce3409acae5

**Comment by spxtr** [comment]
Agreed. Maybe not JUnit, they could also go in JSON files next to started/finished.json. We'd like to have download/untar k8s, cluster up, test, down, and resource check as separate checks..

**Comment by lavalamp** [comment]
JUnit is important, because it lets the existing tooling in e.g. the merge queue read it.

**Comment by spxtr** [comment]
Sure, sounds reasonable. It would also let our other tools read it without trouble.

**Comment by lavalamp** [comment]
I think this is important, without this the merge queue might not know to stop merging if there is something consistently wrong, but not reported in JUnit output anywhere.

**Comment by fejta** [comment]
@spxtr will you please move this logic into hack/e2e.go?

**Comment by spxtr** [comment]
Yep. This is something I would like to do in the very near future.

**Comment by spxtr** [comment]
I think this is pretty much done. There are still improvements to be made, but we should make separate issues for those.
