### ISSUE TITLE
 master blocking jobs should probably be on etcd3

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7602]
```
$ cat jobs/env/ci-kubernetes-e2e-gci-gce.env
### job-env
# This list should match the list in kubernetes-pull-build-test-e2e-gce.
NUM_NODES=4
# For now explicitly test etcd v2 mode in this suite.
STORAGE_BACKEND=etcd2
TEST_ETCD_IMAGE=2.2.1
TEST_ETCD_VERSION=2.2.1

# Enable the PodSecurityPolicy in tests.
ENABLE_POD_SECURITY_POLICY=true
```

I'm not sure who decides this or exactly all which jobs should be running what, but other jobs appear to consume this env and my understanding is that kubernetes should be solidly on etcd3 now...

**Comment by BenTheElder** [comment]
/assign @krzyzacy 
please punt to whoever is appropriate to triage which version we should use

**Comment by ixdy** [comment]
https://github.com/kubernetes/kubernetes/issues/41422

cc @mml @wojtek-t @jpbetz

**Comment by krzyzacy** [comment]
given all other jobs are on default etcd I think we'd just remove this

**Comment by BenTheElder** [comment]
discussed some offline, this should probably be
/sig api-machinery

**Comment by wojtek-t** [comment]
Personally, I'm fine with removing those jobs.

But at least in theory, we still support etcd v2 (though we are in deprecation period).
So from that point of view we may be forced to still have these tests - so let's wait for @lavalamp and @jpbetz thoughts.

**Comment by BenTheElder** [comment]
I've discussed this some more in other venues and it sounds like we need to have some etcd2 testing until 1.12, but I think our primary CI and presubmit jobs blocking on otherwise-defaults GCE e2e should actually be completely-defaults with maybe some other dedicated etcd2 testing jobs.

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/6114#issuecomment-385608767

**Comment by BenTheElder** [comment]
Per discussion today in #sig-release we will hold on this until q4
/assign
/assign @spiffxp

**Comment by spiffxp** [comment]
Other issues related to etcd2's deprecation:
- https://github.com/kubernetes/kubernetes/issues/44156
- https://github.com/kubernetes/kubernetes/issues/57354

[We announced in v1.9](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md) that etcd2 is being deprecated "1.13 or 1.14"

I'm not planning to unpack which of those versions it is just yet. But I will gladly push for it to be 1.13 as we get closer to it.

**Comment by tpepper** [comment]
Is this important longterm only?

Or given https://groups.google.com/d/topic/kubernetes-dev/jMPA4JzKiY4/discussion is this something we should be doing NOW critical urgent?

**Comment by BenTheElder** [comment]
My understanding was that the most recent update from sig-arch stated we'd only be dropping etcd2 support fully by 1.13, at which point we'd want to drop it from testing.

**Comment by jpbetz** [comment]
That sounds right to me as well.

**Comment by tpepper** [comment]
sgtm then

**Comment by liggitt** [comment]
It's been at the top of the release notes as being deprecated and scheduled for removal in 1.13 in 1.10-1.12. 

https://github.com/kubernetes/kubernetes/issues/69310 is open to remove etcd2 support and cluster-lifecycle (specifically kops) is working through switching defaults to etcd3 as well.

**Comment by BenTheElder** [comment]
yeah I've been trying to watch that, @spiffxp was talking about tackling this from the test side the other day I think :^)

**Comment by spiffxp** [comment]
Yup, just opened a first pass, I'll see if I can give it some time tomorrow

**Comment by spiffxp** [comment]
/close
There are no more jobs that use etcd2
