### ISSUE TITLE
Janitor can be stuck

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#7612]
http://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-kubemark-e2e-gce

and it's not respecting bootstrap timeout ?!

/assign

**Comment by krzyzacy** [comment]
restarted the stuck pod - wonder why bootstrap did not terminate the subprocesses

**Comment by krzyzacy** [comment]
cc @shyamjvs it's stuck on `k8s-presubmit-scale` again, still looking into why

also cc @BenTheElder as oncall

**Comment by krzyzacy** [comment]
local run works fine, wonder what's the cause there, I suspect gcloud?

we'd need https://github.com/kubernetes/test-infra/issues/7152

**Comment by shyamjvs** [comment]
I'm seeing that there are a bunch of undeleted networks (that were leaked from old runs) in the k8s-presubmit-scale project.
And some of them are really old (i.e greater than a day) and I'd expect janitor to have cleaned them up long ago - but it didn't.
E.g:
- Network `e2e-981-c664bc` from run-981 of [kubemark-500 presubmit](https://k8s-testgrid.appspot.com/presubmits-kubernetes-scalability#pull-kubernetes-kubemark-e2e-gce-big)  which timed out

**Comment by krzyzacy** [comment]
@shyamjvs my question will be why there are so many leaked networks?

**Comment by krzyzacy** [comment]
I'll request more CPU/Memory for the janitor pod see if it can help with the issue

**Comment by krzyzacy** [comment]
it looks fine now after https://github.com/kubernetes/test-infra/pull/7677 and https://github.com/kubernetes/test-infra/pull/7678

**Comment by shyamjvs** [comment]
Thanks for working on this!

**Comment by krzyzacy** [comment]
locally it's stuck at
```
Call ['gcloud', 'compute', '-q', 'instances', 'delete', '--project=k8s-presubmit-scale', u'--zone=https://www.googleapis.com/compute/v1/projects/k8s-presubmit-scale/zones/us-east1-b', u'e2e-1835-435a3f-minion-group-x0x7', u'e2e-1835-435a3f-minion-group-xrlm', u'e2e-1835-435a3f-minion-group-xs1t', u'e2e-1835-435a3f-minion-group-z9lc', u'e2e-1835-435a3f-minion-group-zvvh', u'e2e-1887-6fa19d-master', u'e2e-1887-6fa19d-minion-group-1xmw', u'e2e-1887-6fa19d-minion-group-20zx', u'e2e-1887-6fa19d-minion-group-2243', u'e2e-1887-6fa19d-minion-group-286m', u'e2e-1887-6fa19d-minion-group-338p', u'e2e-1887-6fa19d-minion-group-3476', u'e2e-1887-6fa19d-minion-group-37lz', u'e2e-1887-6fa19d-minion-group-3q1q', u'e2e-1887-6fa19d-minion-group-4p36', u'e2e-1887-6fa19d-minion-group-4w8f', u'e2e-1887-6fa19d-minion-group-5c5c', u'e2e-1887-6fa19d-minion-group-5r4k', u'e2e-1887-6fa19d-minion-group-63f3', u'e2e-1887-6fa19d-minion-group-65vl', u'e2e-1887-6fa19d-minion-group-6grn', u'e2e-1887-6fa19d-minion-group-6n41', u'e2e-1887-6fa19d-minion-group-6qhv', u'e2e-1887-6fa19d-minion-group-72k0', u'e2e-1887-6fa19d-minion-group-7jv6', u'e2e-1887-6fa19d-minion-group-7p8n', u'e2e-1887-6fa19d-minion-group-8110', u'e2e-1887-6fa19d-minion-group-85bh', u'e2e-1887-6fa19d-minion-group-88jc', u'e2e-1887-6fa19d-minion-group-8qxc', u'e2e-1887-6fa19d-minion-group-8sj7', u'e2e-1887-6fa19d-minion-group-8wwg', u'e2e-1887-6fa19d-minion-group-99jd', u'e2e-1887-6fa19d-minion-group-9fn4', u'e2e-1887-6fa19d-minion-group-9jqn', u'e2e-1887-6fa19d-minion-group-9qqz', u'e2e-1887-6fa19d-minion-group-9v50', u'e2e-1887-6fa19d-minion-group-b0g0', u'e2e-1887-6fa19d-minion-group-bg9p', u'e2e-1887-6fa19d-minion-group-bqfj', u'e2e-1887-6fa19d-minion-group-c010', u'e2e-1887-6fa19d-minion-group-cbs5', u'e2e-1887-6fa19d-minion-group-cjc0', u'e2e-1887-6fa19d-minion-group-f729', u'e2e-1887-6fa19d-minion-group-f9x9', u'e2e-1887-6fa19d-minion-group-fqn3', u'e2e-1887-6fa19d-minion-group-g267', u'e2e-1887-6fa19d-minion-group-g46x', u'e2e-1887-6fa19d-minion-group-g6ld', u'e2e-1887-6fa19d-minion-group-grpz']
```

/shrug
trying with lower #resources per call

**Comment by krzyzacy** [comment]
hummmmmm, passed with `--ratelimit=5`

feel like more of a gcloud issue

**Comment by shyamjvs** [comment]
This is surprising. Is it possible to delete an instance-group first (if possible), instead of deleting individual instances?

**Comment by shyamjvs** [comment]
That should reduce no. of gcloud calls by orders of magnitude :)

**Comment by shyamjvs** [comment]
Agree - my change with cluster naming should ensure leaked presubmit clusters are GC'd in next run.
