### ISSUE TITLE
builds fail to stage in CI

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7633]
/priority failing-test

https://github.com/kubernetes/release/pull/515/files#r180541584

>New TestGrid alerts at testgrid/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce since commit/5c5d101dd.
> New Test Failures in pull-kubernetes-e2e-gce.
> Test Stage has failed 12 times since it last passed at commit/ebdac31bb. It started failing between commit/ebdac31bb (Tue Apr 10 11:04 PDT) and commit/5c5d101dd (Tue Apr 10 11:04 PDT).
> Test Overall has failed 13 times since it last passed at commit/ebdac31bb. It started failing between commit/ebdac31bb (Tue Apr 10 11:04 PDT) and commit/5c5d101dd (Tue Apr 10 11:04 PDT).
(edited)

also, only caught this alert to my own email, we should send these to engprod or maybe even sig-testing...

**Comment by ixdy** [comment]
We need to update to gcloud 196.0.0 (2018-04-04) or newer.

**Comment by david-mcmahon** [comment]
ref https://github.com/kubernetes/release/pull/546

**Comment by BenTheElder** [comment]
working on new images at the moment, should have latest gcloud

**Comment by BenTheElder** [comment]
```
Google Cloud SDK [197.0.0]

Platform: [Linux, x86_64] ('Linux', 'f2c60443b4ec', '4.9.0-6-amd64', '#1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02)', 'x86_64', '')
Python Version: [2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/google-cloud-sdk]
Installed Components:
  core: [2018.04.06]
  kubectl: []
  beta: [2017.09.15]
  gsutil: [4.30]
  bq: [2.0.31]
  alpha: [2017.09.15]
System PATH: [/google-cloud-sdk/bin:/workspace:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]
Python PATH: [/google-cloud-sdk/lib/third_party:/google-cloud-sdk/lib:/usr/lib/python2.7/:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload]
Cloud SDK on PATH: [True]
Kubectl on PATH: [/google-cloud-sdk/bin/kubectl]

Installation Properties: [/google-cloud-sdk/properties]
User Config Directory: [/root/.config/gcloud]
Active Configuration Name: [default]
Active Configuration Path: [/root/.config/gcloud/configurations/config_default]

Account: [None]
Project: [None]

Current Properties:
  [core]
    disable_prompts: [1]
    disable_usage_reporting: [True]

Logs Directory: [/root/.config/gcloud/logs]
Last Log File: [/root/.config/gcloud/logs/2018.04.10/20.47.04.508942.log]

git: [git version 2.1.4]
ssh: [OpenSSH_6.7p1 Debian-5+deb8u4, OpenSSL 1.0.1t  3 May 2016]
```

**Comment by BenTheElder** [comment]
so this is passing after a revert to the release repo earlier, but we will likely revert the revert now that the image bump is in, and we still need to improve the alerting for these jobs so I am not closing this yet to track those.

**Comment by BenTheElder** [comment]
this is fixed, and the release repo has a presubmit to stage a build and up a cluster from it to sanity check push-build.sh
