### ISSUE TITLE
all tests: we should get jUnit output for non-test tests (linters, boilerplate/other diffs)

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7650]
Every time I need to expand a log to see a bad diff from `gofmt` or the boilerplate check I cry inside. Is there a way to wrap that in jUnit XMl easily from `bazel` or do we need to do it in the shell scripts?

/cc @BenTheElder @cjwagner @ixdy 
/area prow
/kind bug

**Comment by ixdy** [comment]
The boilerplate check is already implemented as a bazel test in kubernetes/test-infra, so it should have its failures encoded in junit.

We removed the bazel `gofmt` test a while ago because rules_go didn't have a good way for us to access it. It might be possible to depend on it again, though I haven't checked.

**Comment by ixdy** [comment]
Running linters under bazel is kinda gross, though, since they generally require the `//:all-srcs` rule, which destroys any cacheability.

**Comment by stevekuznetsov** [comment]
I can literally 

```
cat <<EOF >results.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="k8s.io/test-infra/verify" tests="${NUM_TESTS}" skipped="${NUM_SKIPPED}" failures="${NUM_FAILURES}" time="${RUN_TIME}">
...
EOF
```

And shove output from the linter into there. Any objection? :)

Dumb but it gets the job done simply

**Comment by BenTheElder** [comment]
i'm open to all options, I've intentionally seperated out all of the lints from unit testing / build because they're "special" and have their own caching (= ~none) and failure modes.

**Comment by cjwagner** [comment]
We discussed a plugable artifact viewer framework today. This would be another good use case for it.
