### ISSUE TITLE
add smoke test for OWNERS files

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#7686]
I unintentionally broke the kubernetes top-level `OWNERS` file yesterday in kubernetes/kubernetes#62484, due to a parse error:
```console
$ yq '.' OWNERS
yq: Error running jq: ScannerError: while scanning a double-quoted scalar
  in "OWNERS", line 22, column 3
found unknown escape character '.'
  in "OWNERS", line 22, column 5.
```

It'd be great if we had some sort of testing/validation for `OWNERS` files that prevented merging bad ones.

**Comment by ixdy** [comment]
does the verify-owners plugin in prow handle this now? @matthyx @cjwagner

**Comment by matthyx** [comment]
@ixdy yes, but currently it's only enabled on test-infra AND the review comments will work only after prow has been refreshed, following #8511 merge.

**Comment by stevekuznetsov** [comment]
After we dial in the execution of the plugin, we will enable it on the rest of the org and this issue will be solved. I think we can

/close 

it since we're tracking roll-out of the plugin anyway
