### ISSUE TITLE
Display line numbers in the build log in gubernator

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/test-infra#769]
Display line numbers for the lines in the build log like the way source code browsers display them. Also, make it linkable (using # fragments) and scrollable using something like `jquery.scrollTo`

**Comment by fejta** [comment]
Is this still relevant?

**Comment by BenTheElder** [comment]
See also https://docs.google.com/document/d/18xKXUTKH8-XQb3lfz69nY3LfiF5c9tXPFcwwaraZdjs/edit# for a proposal to overhaul the build log in general. /cc @stevekuznetsov

**Comment by madhusudancs** [comment]
@fejta yeah, I think this is still relevant.

@BenTheElder where can I follow the progress of this project?

**Comment by BenTheElder** [comment]
@madhusudancs I've left a comment about that on the doc, I think Steve has started working on this but hasn't opened any issues or PRs yet. I'll follow here when that changes.

**Comment by madhusudancs** [comment]
Sure, thanks.

**Comment by stevekuznetsov** [comment]
Yeah we're still in the design proposal phase. No concrete work yet.

**Comment by stevekuznetsov** [comment]
Having link-able, scroll-able and numbered lines is definitely something that is useful though.
