### ISSUE TITLE
'blunderbuss' plugin doesn't work if reviewers are missing in OWNERS

### ISSUE THREAD

**Issue by rsdcastro** [kubernetes/test-infra#7691]
After investigating why 'blunderbuss' plugin wasn't working for the kube-deploy repo, we realized that the issue is that the OWNERS file had "approvers" but no "reviewers" section. After adding "reviewers", the issue got fixed.

This issue is to suggest that, in absence of "reviewers", "approvers" are used instead rather than failing to request reviews.

cc @spiffxp @kubernetes/kube-deploy-maintainers

**Comment by cjwagner** [comment]
@grantr Is working on this. It sounds like the plan is to either allow blunderbuss to be configured to use the approvers list as the reviewers list, or automatically detect that a file has no reviewers and assign approvers instead.
