### ISSUE TITLE
Clean up kubetest flags

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#7713]
- we have way too many kubetest flags
- many of those are doing things like, set a global env
- and many of those have (--provider=foo only), we don't really validate that

we can probably do it like prow style?
cc @shyamjvs @BenTheElder 

/area kubetest
/assign

**Comment by spiffxp** [comment]
/milestone v1.14

Since I think @krzyzacy is planning on a kubetest refactor this cycle

**Comment by BenTheElder** [comment]
[kubetest2](https://docs.google.com/document/d/1Dc7xg9lq4cxdDuz20YZjunuL5eju2WIXwO32praC5hs/) proposes a solution for this. I intend to start writing actual prototype code this week.

**Comment by BenTheElder** [comment]
we'll do kubetest2 instead
