### ISSUE TITLE
slackevents merge warnings whitelist should be locked by branch

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7714]
we should be able to check the ref of the pushevent to match on the branch pushed to, and then update the config to restrict branch managers to their respective branches when whitelisting them.

cc @cjwagner

**Comment by cblecker** [comment]
Relevant bits of code for someone looking at this:
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/slackevents/slackevents.go
https://github.com/kubernetes/test-infra/blob/8d7d1e4ec835080bc2dbfd3ee3bd4f1a6342c6d4/prow/plugins/plugins.go#L374-L384
https://github.com/kubernetes/test-infra/blob/8d7d1e4ec835080bc2dbfd3ee3bd4f1a6342c6d4/prow/plugins.yaml#L104-L129

**Comment by paulangton** [comment]
@BenTheElder can this be closed since #8107 was merged?

**Comment by BenTheElder** [comment]
Yep, thanks for that!
/close
