### ISSUE TITLE
Confusion with naming of release-jobs

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#7729]
The [README](https://github.com/kubernetes/test-infra/blob/master/README.md#release-branch-jobs--image-validation-jobs) is saying:

```
k8s-dev : master
k8s-beta : master (inactive)
k8s-stable1 : release-1.10
k8s-stable2 : release-1.9
k8s-stable3 : release-1.8
```

However, [this job](https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L4792) that's running against ci/k8s-beta seems to be running on 1.10-beta (which is violating the above convention). Here's an e.g run proving that it's running on 1.10-beta - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-beta/689

Is this a bug or am I understanding sth wrong?

/cc @krzyzacy @kubernetes/test-infra-maintainers

**Comment by shyamjvs** [comment]
fyi - @wojtek-t

**Comment by krzyzacy** [comment]
whoops sorry, it should run against 1.10 since there's no 1.11 branches yet at this point, I'll update the readme

basically this job does not provide any signals, I'll probably just give it an invalid cron till we have a 1.11 branch

**Comment by krzyzacy** [comment]
@shyamjvs we always only support scalability test for past two releases + active release branches - I can set up a new job for 1.8, is there still quota in the project?

**Comment by shyamjvs** [comment]
Is that so? I thought it was current release (which is 1.10) + 2 releases
behind it (i.e 1.9, 1.8). Regarding new job, I don't think you should need
to do that. We're already having 4 jobs (master, 1.10, 1.9, 1.8), we should
just fix the configs IIUC.

**Comment by krzyzacy** [comment]
@shyamjvs the scalability channel has three branched suites: `-beta`, `-stable1`, `-stable2`, while all other release jobs has four branches: `-beta`, `-stable1`, `-stable2`, `-stable3`

If we muck with the config, when 1.11 is cut, the config will be wrong again (that's the whole point why I added the `-stable-foo` conventions) I think we should just add `-stable3` to scalability suites, I'm just not sure which project it should run on.
