### ISSUE TITLE
Decouple reporter from plank

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#7741]
follow up https://github.com/kubernetes/test-infra/issues/7733

/area prow
/assign

**Comment by kargakis** [comment]
How difficult is making the reporter library generic/pluggable so it can support different platforms? I see the value in a separate service but we have to resist the urge until it's the only thing we can do.

**Comment by krzyzacy** [comment]
@kargakis yeah that's what I thought, my intention here is to define some sort of proto (gRPC?) that different reporter client can understand and react to it, but feel free to give inputs here if you have better ideas.

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

Sen is still looking at this hopefully

**Comment by krzyzacy** [comment]
yeah I'll do things after https://github.com/kubernetes/test-infra/pull/8669

**Comment by krzyzacy** [comment]
/remove-lifecycle stale
missed that hook ?!

**Comment by krzyzacy** [comment]
/remove-lifecycle stale
almost there

**Comment by krzyzacy** [comment]
So ref https://github.com/kubernetes/test-infra/pull/10973:

When switching from plank to crier, crier doesn't know the reporting state for existing prowjobs so it was trying to re-report each job which causes prow to use up all its github tokens. Plank need to set `pj.Status.PrevReportStates` in order for a seamless transition.

Will send a few follow-up PRs & docs.

**Comment by krzyzacy** [comment]
Will try again O(next week) :-)

**Comment by stevekuznetsov** [comment]
@krzyzacy what was the status here? fully done?

**Comment by krzyzacy** [comment]
all our other prows are on crier, except for prow.k8s.io

oh this is still assigned to me - let me make a PR

**Comment by krzyzacy** [comment]
didn't hear complaint so far, closing this.

Once (when?) everyone else moved to crier we should clean up plank code.
