### ISSUE TITLE
Job 'pull-poseidon-bazel' is not getting triggered 

### ISSUE THREAD

**Issue by shivramsrivastava** [kubernetes/test-infra#7747]
This is with reference to the PR #7697, which added a job to build and test Poseidon.
But this Job is currently not getting triggered.
We tried ```/retest``` and ```/test pull-poseidon-bazel```

Here are the links to the PR which have this issue. 
[PR-33](https://github.com/kubernetes-sigs/poseidon/pull/33),[PR-26](https://github.com/kubernetes-sigs/poseidon/pull/26),[PR-39](https://github.com/kubernetes-sigs/poseidon/pull/39)

@shashidharatd @deepak-vij @m1093782566

**Comment by shivramsrivastava** [comment]
/assign @BenTheElder 

Can you please take and look into this issue?

**Comment by BenTheElder** [comment]
it looks like the `trigger` plugin is no longer enabled for this repo, which means no tests can be triggered...
I will PR this.
