### ISSUE TITLE
port GIT_COMMITTER_DATE and SOURCE_DATE_EPOCH changes to prow/{entrypoint,pod-utils}

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#7760]
https://github.com/kubernetes/test-infra/pull/7480 was an experiment with bootstrap to see if we could improve the cacheability of bazel builds, and it's been working fairly well. We should port this functionality to the prow equivalents (pod-utils, entrypoint, and anything else I'm missing) to get similar improvements for jobs not using bootstrap.

cc @stevekuznetsov @BenTheElder

**Comment by stevekuznetsov** [comment]
Only changes would need to land here: https://github.com/kubernetes/test-infra/blob/master/prow/pod-utils/clone/clone.go#L82

**Comment by ixdy** [comment]
There are two pieces.

I agree that faking author/commit dates for git merges would go into `clone.go`.

Where would I put setting the `SOURCE_DATE_EPOCH` environment variable, based on the git commit date, before calling bazel (or other build/test commands)?

**Comment by stevekuznetsov** [comment]
Oh, that is set for `bazel` calls, I see -- that would go here: https://github.com/kubernetes/test-infra/blob/master/prow/entrypoint/run.go#L59

**Comment by BenTheElder** [comment]
SOURCE_DATE_EPOCH is a standard that bazel rules are following, but we
should use it more generally
https://reproducible-builds.org/specs/source-date-epoch/

**Comment by ixdy** [comment]
the non-bazel kubernetes build system also recognizes `SOURCE_DATE_EPOCH`.

**Comment by ixdy** [comment]
/remove-lifecycle stale

We should still do this, especially before migrating to these for kubernetes repos.

**Comment by BenTheElder** [comment]
we probably still want this? reproducible builds are very nice :-)
/remove-lifecycle rotten

**Comment by ixdy** [comment]
I'm not sure how to do this in a clean way.

I'd somehow need to inject a `git show` before https://github.com/kubernetes/test-infra/blob/92da5df3d53c42a484961b47129830862986e662/prow/pod-utils/clone/clone.go#L104-L117 and then use a modified value of its output as an environment variable in the `git merge` calls, but the way this is implemented, all of the commands are constructed before any of them is run.

**Comment by ixdy** [comment]
for setting `SOURCE_DATE_EPOCH`, would it be unreasonable to add that to `images/bootstrap/runner.sh` rather than `prow/entrypoint/run.go`? e.g. just add something like

```bash
export SOURCE_DATE_EPOCH=$(git show -s --format=format:%ct HEAD 2>/dev/null)
```

**Comment by ixdy** [comment]
(though I guess it wouldn't be too hard to add that to entrypoint, either.)

**Comment by BenTheElder** [comment]
`runner.sh` would be OK, I'd kinda hoped we could avoid layers as often as possible, especially ones that do magical environment :grimacing: 

It also requires using that image.

**Comment by ixdy** [comment]
I started sketching out an approach that might work to set `GIT_AUTHOR_DATE` and `GIT_COMMITTER_DATE` in `prow/pod-utils/clone`: https://github.com/ixdy/kubernetes-test-infra/commit/308c908f9221e28a3c280bd21035ed234c44953e, but fixing the unit tests is kinda frustrating, and I'm not sure how I'd actually test this for correctness.

**Comment by ixdy** [comment]
1. In `clonerefs`, should we fake merge dates always, or should it be configurable?
2. In `entrypoint`, should we set `SOURCE_DATE_EPOCH` always, or should that be configurable?

For comparison, `bootstrap.py` always uses fake merge dates, and it always sets `SOURCE_DATE_EPOCH`.

@stevekuznetsov @fejta @BenTheElder @cjwagner

**Comment by stevekuznetsov** [comment]
Changing them always seems fine to me. Changing them optionally and threading out the option would be safest -- what are the downsides with changing them always?

**Comment by fejta** [comment]
IMO waiting until someone needs to disable this behavior before we implement it seems the most efficient path forward.

**Comment by ixdy** [comment]
it's hard to identify any real downsides. it might be surprising if e.g. build timestamps don't match when the build actually ran, but that's also a feature.

enabling them always is easiest, so I'll just go that route.

**Comment by stevekuznetsov** [comment]
SGTM

**Comment by BenTheElder** [comment]
it's really [the go way](https://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/) -- break bad assumptions :^)
