### ISSUE TITLE
some kubekins-e2e image users probably shouldn't be on -experimental

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7784]
The `.*-experimental` tagged images contain the latest tool versions (go, bazel, etc..) currently used by test-infra that will someday be used by kubernetes. This tag has no strong guarantees about upgrade cycle. 
The other tags `.*-master`, `.*-release-1.X` all match the tools used by the [kubernetes](https://github.com/kubernetes/kubernetes) core repo to build / test. Most other repos want to sync against the kubernetes master tools.

kops has bazel jobs on this.
/cc @justinsb @chrislovecnm 

cri-containerd has jobs against this due to early opting in to go 1.10. I've spoken to @Random-Liu and will PR switching to the -master tag.

**Comment by BenTheElder** [comment]
My question to kops is what track do you want to be on? I suspect kops is only on -experimental to get on the caching train early, but master or 1.10 work for that as well now.

**Comment by justinsb** [comment]
I suspect you're right - we don't need to be on experimental.  @chrislovecnm I believe you set these jobs up?

**Comment by BenTheElder** [comment]
> I suspect you're right - we don't need to be on experimental. @chrislovecnm I believe you set these jobs up?

I set them up in discussion with @chrislovecnm, happy to make the changes, just want to verify with you all first. 
"experimental" really just means "we upgrade bazel / go a little faster than k/k" but those changes *can* be breaking. 
OTOH when k/k upgrades those can be too, but they tend to be *long* after developers have upgraded their machines so usually the bugs are fixed incrementally prior to upgrading.

**Comment by BenTheElder** [comment]
we should probably just go ahead and move anyone else off of it... though if nobody is complaining about problems I guess there's no rush...
/remove-lifecycle stale
/priority backlog

**Comment by BenTheElder** [comment]
Should be fixed
/close
