### ISSUE TITLE
docs/federated_testing.md is out of date.

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#780]
It describes how to use `hack/jenkins/e2e-runner.sh` and `hack/jenkins/upload-to-gcs.sh` but we've changed how that stuff behaves.

**Comment by techtonik** [comment]
Any hints what was changed? Or it could be inferred from the code?

**Comment by spxtr** [comment]
`e2e-runner.sh` is now in the test-infra repo and behaves differently, and `upload-to-gcs.sh` will soon follow suit. The environment inputs may or may not have changed, I'm not sure.

**Comment by chuckbutler** [comment]
@spxtr We're working this cycle on bringing our e2e testing results to the federated dashboard. I have the j-unit output of the e2e runners coming out fantastically.  As we work through the integration guide, we'll have some different process on our jobs vs what the scripts versioned in test-infra have. Namely our e2e runs are not done out of the `hack/` directory.  I think we can integrate quickly if we can just get a clear direction on whats expected from the munging/directory tree of the `gss://` path.

I see above that the upload script will be changing behavior. This blocks us until we have those changes detailed so we know how to integrate.

**Comment by spxtr** [comment]
@chuckbutler https://github.com/kubernetes/test-infra/pull/1013#issuecomment-261077157

> Question: Is there a chance we can de-couple the test-run and munge/upload steps? I'm evaluating using just the `upload-to-gce.sh` script, as we're running the e2e tests out of band of the jenkins job.

You can probably do that for now. I think we're moving some functionality to `bootstrap.py`, and I'm not sure how things will look in the future. Maybe @fejta has an idea?
