### ISSUE TITLE
tide: a PR with no configured ProwJobs should be able to enter the merge pool

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7804]
tide matches PRs with prowjobs and filters PRs with successful prowjobs which are considered mergeable. It then goes and checks HEAD's contexts. It would be desirable to avoid the prowjob checks altogether for repositories where prow does not run tests but we still want to automate merges. 

@stevekuznetsov @cjwagner 

/area prow
/kind enhancement

**Comment by stevekuznetsov** [comment]
A PR with no ProwJobs should be classified as mergeable.
