### ISSUE TITLE
improve sig-testing testgrid alert configuration

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7814]
we own a lot of jobs that don't really have good alerting but very much could. 
we should set up a sig-testing alerts alias and configure our testgrid entries to send email alerts there with reasonable num_failures etc.

/area testgrid
/sig testing
/cc @spiffxp

**Comment by BenTheElder** [comment]
similarly @AishSundar and I will work on GCP alerts, at least for conformance tests to ping GKE EngProd, and we should more broadly encourage subscribing to test failure alerts, especially for say, 10 tests in a row failing.. 
sig-owners really ought to have someone responding to these, or we should remove the tests

**Comment by BenTheElder** [comment]
@spiffxp WDYT?
/remove-lifecycle stale

**Comment by spiffxp** [comment]
/milestone v1.13
/unassign @AishSundar 

I would like to setup a kubernetes-sig-testing-alerts googlegroup and pilot this as a standard for all sigs.  The main question on my mind right now is whether we want to allow anyone to post, or attempt to restrict posting to keep it high-signal.

**Comment by BenTheElder** [comment]
I think you have to allow anyone to post in order to let testgrid in actually. cc @michelle192837

**Comment by BenTheElder** [comment]
Not true @k8s-ci-robot! I defy your power!

**Comment by spiffxp** [comment]
/milestone v1.15
I am creating kubernetes-sig-testing-alerts@ and will be configuring testgrid to send alerts there for release-blocking jobs that we own.

**Comment by spiffxp** [comment]
Looking at https://groups.google.com/forum/#!forum/kubernetes-github-managment-alerts as a model, where I'd like to allow testgrid to post, but everything else to hit moderation

- Created https://groups.google.com/forum/#!forum/kubernetes-sig-testing-alerts
- Added kuberentes-sig-testing-leads@ members as Owners

**Comment by spiffxp** [comment]
Sample alert: https://groups.google.com/forum/#!topic/kubernetes-sig-testing-alerts/ts-oo7uTBug
