### ISSUE TITLE
jenkins/bootstrap.py fails when --upload is not passed

### ISSUE THREAD

**Issue by brilee** [kubernetes/test-infra#7864]
https://github.com/kubernetes/test-infra/blob/14afd74a5a3e88d5f2b96bc04b7aec802d9d6607/jenkins/bootstrap.py#L1038

If this `if` branch is not taken, then the local variable `paths` is never defined; all subsequent uses of the `paths` variable should be guarded by an `if upload` clause. Otherwise I get 

```
E0425 14:49:31.821] unexpected error
Traceback (most recent call last):
  File "./test-infra/jenkins/bootstrap.py", line 1059, in bootstrap
    maybe_upload_podspec(call, paths.artifacts, gsutil, os.getenv)
UnboundLocalError: local variable 'paths' referenced before assignment
I0425 14:49:31.822] Will not upload results.
Traceback (most recent call last):
  File "./test-infra/jenkins/bootstrap.py", line 1163, in <module>
    bootstrap(ARGS)
  File "./test-infra/jenkins/bootstrap.py", line 1059, in bootstrap
    maybe_upload_podspec(call, paths.artifacts, gsutil, os.getenv)
UnboundLocalError: local variable 'paths' referenced before assignment
```

**Comment by krzyzacy** [comment]
how did you hit this? in a CI job?

**Comment by brilee** [comment]
I'd been running some local testing of the CI setup process as detailed in https://github.com/tensorflow/minigo/tree/master/testing . (The instructions were set up by @Kashomon who's a googler.).
