### ISSUE TITLE
Document k8s-bot behavior

### ISSUE THREAD

**Issue by techtonik** [kubernetes/test-infra#787]
In https://github.com/kubernetes/kubernetes/pull/34371#issuecomment-252564527 k8s-bot was ignoring me. I couldn't find any documented @k8s-bot behavior from its GitHub profile or its source code. Later I've been told that I just need to send him two separate messages.

The question asked:
- Does it need me to be in whitelist? (do both CLA is enough)
- Is it desirable that it could parse two lines in one message?
- How to check that it is not offline and received my message?

Anyway, the purpose of this issue is to add URL to bot docs into its profile and subscribe it to repository with its own sources. @k8s-bot

**Comment by techtonik** [comment]
Maybe there is a slack channel that receives all mentions of the bot?

**Comment by spxtr** [comment]
You need to be a kubernetes org member. I agree, currently it's not clear how it all works. @fejta suggested "@k8s-bot help" or something like that, and I can also make it so that if you say "@k8s-bot test this" or something when you're not a member it comments saying why it won't test.

**Comment by techtonik** [comment]
@spxtr I didn't think about typing "@k8s-bot help" which would also produce unnecessary noise for other people. If bot could have alternative interface in telegram or in slack, that could be obvious. Right now the primary obstacle is the absence of link to bot sources with README.md in bot profile description.

**Comment by techtonik** [comment]
And it still doesn't listen to me. ) https://github.com/kubernetes/kubernetes/pull/34370#issuecomment-253114438

**Comment by spxtr** [comment]
You need to be a member of the kubernetes org in order to trigger jobs with a comment.

**Comment by techtonik** [comment]
@spxtr yes, I know that. Now it needs to be documented somewhere.

**Comment by spxtr** [comment]
Agreed.

**Comment by techtonik** [comment]
@spxtr so where is the source code for the bot? I guess everything is here - https://github.com/kubernetes/test-infra/blob/master/prow/jobs.yaml ?

**Comment by spxtr** [comment]
Yep, the source is all under the `prow` folder right now.

**Comment by techtonik** [comment]
I see that bot is just a series of hardcoded handlers that respond to message content. Could the bot profile URL be pointed to https://github.com/kubernetes/test-infra/blob/master/prow/ for the start?

**Comment by spxtr** [comment]
[Done](https://github.com/k8s-ci-robot) :)

**Comment by techtonik** [comment]
I actually thought about https://github.com/k8s-bot but this one is also nice. =) So there are two bots in prow?

**Comment by spxtr** [comment]
I don't think k8s-bot does anything anymore.

**Comment by techtonik** [comment]
@k8s-ci-robot [asks to speak to him](https://github.com/kubernetes/test-infra/pull/882#issuecomment-254916147) so maybe he has a bright future (like an additional telegram/IRC interface)?

**Comment by techtonik** [comment]
@spxtr could you update links in @k8s-bot and @k8s-ci-robot profiles to point to https://github.com/kubernetes/test-infra/tree/master/prow#bots-home ? That should be enough to close this issue for now. At least my itch would be scratched and I don't have any questions now. =)

**Comment by spxtr** [comment]
Done. Feel free to make more suggestions or close this issue or whatever. The goal is for this system to be easy to understand for users, and I think right now it's not.
