### ISSUE TITLE
dind should scrub /etc/resolv.conf or allow internet access

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7875]
right now the dind cluster intentionally does not support internet access, but the host's DNS settings partially proprogate to the pods. we can prevent this by scrubbing /etc/resolv.conf when setting up the nodes, but we should not do this when we allow internet access (which probably should be optional)

as @Q-Lee pointed out not having internet access id desirable for some tests (can't have flaky internet probing code if you don't have any internet...), but we probably want to allow it for other uses of the dind cluster.

I think this will solve the DNS conformance test failures. Thanks @MrHohn for taking the time to probe kubedns with us :-)

/kind bug
/area kubetest
/assign @Q-Lee 
/assign

**Comment by Q-Lee** [comment]
DIND _nodes_ all have internet access. The pods themselves do not.

With most network providers, it's as simply as adding routes + NATs for the pod subnets in the top level container. But I'm worried it might not be the same for all network providers.

**Comment by BenTheElder** [comment]
I'll keep this in mind. Working in this area.

**Comment by BenTheElder** [comment]
/close
dind/ is deprecated, ongonig work is at [sigs.k8s.io/kind](https://sigs.k8s.io/kind)
