### ISSUE TITLE
prow/deck should show component versions

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#7890]
the images themselves are probably insufficient, since bazel does sha256-tagging/pushing: 

    gcr.io/k8s-prow/tide@sha256:2f3d179a5bfe38b6695b9c262bb248d7d116c534218da9b0ef11719dd0331cf4

maybe deck should poll each deployment's endpoint for version information?

**Comment by spiffxp** [comment]
@fejta @cjwagner @BenTheElder do we still want to do this?

**Comment by cjwagner** [comment]
It would be useful to have, but I don't think it is high priority.

> maybe deck should poll each deployment's endpoint for version information?

Currently, most Prow components don't handle HTTP requests so we would have to add that and a k8s service for every component. We'd also need to make the components discoverable to Deck or explicitly list the endpoint for each component in Deck's config.
That approach is certainly doable, but I don't think the value add is worth the complexity right now.
So long as we continue using `prow/bump.sh` to bump Prow, the image tags in the [`prow/cluster`](https://github.com/kubernetes/test-infra/tree/master/prow/cluster) directory will reflect what is deployed.

**Comment by BenTheElder** [comment]
> Currently, most Prow components don't handle HTTP requests so we would have to add that and a k8s service for every component. We'd also need to make the components discoverable to Deck or explicitly list the endpoint for each component in Deck's config.

Deck could list the prow deployments instead and look for an image label / tag

**Comment by cjwagner** [comment]
What about Ryan's point in the issue body?

**Comment by BenTheElder** [comment]
we have https://github.com/bazelbuild/rules_docker#stamping

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
this would still be really useful

**Comment by spiffxp** [comment]
since we just reverted / rolled out some things but not all things?
