### ISSUE TITLE
Add a /tbr command to prow

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#7899]
/area prow

It is sometimes necessary to merge first, review later.

Assuming I own all the files I am modifying, we should have an option to allow a `/tbr` to label the issue as needing review but still add lgtm and merge.

/cc @rmmh

**Comment by fejta** [comment]
Gubernator should be aware of this, and show these merged PRs as needing attention until someone /lgtm and causes the label to go away

**Comment by stevekuznetsov** [comment]
What does TBR stand for?

**Comment by BenTheElder** [comment]
To Be Reviewed (?)

**Comment by cpanato** [comment]
I can try this one if thisnis open for the community

**Comment by fejta** [comment]
Definitely, go for it!

**Comment by cpanato** [comment]
@fejta I'm releasing this issue, I did not have time and based on my experience in the test-infra repo I don't have enough knowledge to work on this issue 😢

**Comment by BenTheElder** [comment]
This would be really useful to avoid needing write permission for "I own all of this, let me merge now and we can go over it later", with a `to-be-reviewed` label applied we can easily check for yet-to-be-reviewed changes as well.

Strawman:
The `/tbr` command applies `lgtm` and `to-be-reviewed` if commented by the author, IFF the PR is already `approved` (IE they can approve everything and implicit approval is on, or they `/approve`d their own PR). 

The only edge case I can think of there, is if someone else `/approved` the PR but did not LGTM. I'm not really sure this case is important if the repo has enabled `tbr` and the code is approved.

Repos should think carefully before enabling this. It's probably most appropriate for small projects that do not want to need write access for the root owners.

/assign

**Comment by fejta** [comment]
/remove-lifecycle rotten
Still want this to exist

**Comment by fejta** [comment]
> The only edge case I can think of there, is if someone else /approved the PR but did not LGTM. I'm not really sure this case is important if the repo has enabled tbr and the code is approved.

IMO `/tbr` should only work when the PR author's PR only changes files that the PR author can approve. So in this situation (/tbr-ing an approved comment with no lgtm) I think the plugin should do nothing.

**Comment by BenTheElder** [comment]
Oh interesting, that's tighter than the current partial implementation, that one more or less allows LGTM-ing + adding a tbr label IFF:
- the author would have been allowed to LGTM the PR, except it's their own PR
- the repo has TBR enabled

It does not affect approval. 
I think /tbr only if you can self approve might make more sense, but uhh we probably need to refactor the approvers code first cc @cjwagner 🤔

**Comment by fejta** [comment]
(that is more similar to how it works inside Google btw)

**Comment by BenTheElder** [comment]
"that" being https://github.com/kubernetes/test-infra/issues/7899#issuecomment-453925781 ? 👍
