### ISSUE TITLE
cluster logs not collected from dockerized e2e on timeout

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#79]
The kubernetes tarball is extracted inside the container in dockerized e2e, which gives us `kubernetes/cluster/log-dump.sh`. On timeout, we try to call `log-dump.sh`, but do so outside the container, so it's no longer available.

We should probably move the timeout handling inside the dockerized e2e container.

**Comment by spxtr** [comment]
OK I'll start looking at this today.

**Comment by spxtr** [comment]
Two options, and it might be worth it to do both:

1. In `e2e-runner.sh`, `trap "cluster/log-dump.sh" SIGTERM` and change `dockerized-e2e-runner.sh` to use `timeout`.
1. In `e2e.go` add a timeout flag per-step. If up, test, or down timeout then dump logs.

**Comment by fejta** [comment]
Any progress here?

**Comment by spxtr** [comment]
No progress. I think the best option is 2.

**Comment by fejta** [comment]
I'm pretty sure kubetest handles this correctly now.
