### ISSUE TITLE
ci-kubernetes-local-e2e is stuck

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#7908]
Looks like this got stuck on 04-28 and has not run since.

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-local-e2e/
https://k8s-testgrid.appspot.com/conformance-all#local-up-cluster,%20master%20(dev)

**Comment by krzyzacy** [comment]
https://prow.k8s.io/log?job=ci-kubernetes-local-e2e&id=1075 - looks busted at cleanup

**Comment by krzyzacy** [comment]
cc @BenTheElder

**Comment by BenTheElder** [comment]
if you scroll up further it looks like it hung on some test creating a pod for a long time, then testing timed out  and we started trying to clean up the docker containers.

Ideally we should run cluster down after the test times out.

**Comment by BenTheElder** [comment]
It eventually unstuck-ed
