### ISSUE TITLE
ci-kubernetes-local-e2e-containerized is not displayed in test grid

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#7909]
The URL for the CI job has an error ( https://k8s-testgrid.appspot.com/conformance-all#local-up-cluster-containerized,%20master%20(dev) )
```
Internal Error: Please reload this page and file a bug if the problem persists.
```

The runs themselves are green:
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-local-e2e-containerized/

**Comment by BenTheElder** [comment]
Freshly created jobs are known to have this until the update has completed.
The UI surfaces them before actual data has been prepared IIRC

/assign @michelle192837
