### ISSUE TITLE
"always_run" jobs need to be run with "@k8s-bot test this"

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#791]
Otherwise we get into a bad state where the mungebot keeps trying to rerun the job every 10 minutes because the status is missing, but it's not actually rerunning the job.

I'll fix this and add a test case today.

**Comment by wojtek-t** [comment]
@spxtr - can you please clarify them what should I fix in https://github.com/kubernetes/contrib/pull/1849 to actually make it work?

@apelisse - FYI

**Comment by apelisse** [comment]
Yeah, because this is merged now, we can revert the revert and everything should be fine

Can you please confirm @spxtr ?

**Comment by spxtr** [comment]
That's right. The fix was in this PR, the kubemark presubmit is now run by the mergebot.

**Comment by apelisse** [comment]
Reverting the revert: https://github.com/kubernetes/contrib/pull/1869
