### ISSUE TITLE
prow: refactor GCS interaction to live outside of jobs

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#7915]
After conversations with @cjwagner and @BenTheElder we realized that the most robust approach to GCS uploading will be a standalone server that knows how to:

 - watch for `ProwJob`s being created and transitioning states and ensure that the following files are therefore created in GCS:
   - build index file ("the PR symlink")
   - `latest-build.txt`
   - `started.json`
   - `finished.json`
   - the `ProwJob` `Spec` (however we end up wanting to encode this in GCS)
 - watch for `Pod`s that belong to a `ProwJob` and catch finishing containers to upload their logs to GCS
 - expose a cluster service to stage artifacts from test pods and proxy through to GCS

/area prow
/kind enhancment
/assign

**Comment by stevekuznetsov** [comment]
To implement the controller that watches `Pod`s and uploads container logs, I have pulls open:

 - [ ] https://github.com/kubernetes/test-infra/pull/7914

**Comment by stevekuznetsov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CI][k8sCI] Drive simple container-based tests to maturity upstream](https://trello.com/c/cZNgebzm/612-cik8sci-drive-simple-container-based-tests-to-maturity-upstream)

**Comment by chaodaiG** [comment]
this is not fully implemented, and I think it's still relevant today.
/sig testing
