### ISSUE TITLE
Prow issue: Broken link to PR contributing docs

### ISSUE THREAD

**Issue by chancez** [kubernetes/test-infra#7932]
Ex: https://github.com/kubernetes/charts/pull/4675#issuecomment-381138432 the link "here" goes to  https://git.k8s.io/community/contributors/devel/pull-requests.md which was removed in https://github.com/kubernetes/community/pull/2080/

The link should go to https://git.k8s.io/community/contributors/guide/pull-requests.md or https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md

**Comment by BenTheElder** [comment]
/cc @cblecker 
@kubernetes/sig-contributor-experience-bugs 

Can we get some confirmation on what contribex would prefer here? happy to PR corrections.
/area prow
/kind bug

**Comment by cblecker** [comment]
https://git.k8s.io/community/contributors/guide/pull-requests.md would be great. Thanks @BenTheElder !
