### ISSUE TITLE
Run migratestatus automatically after a PR updates status contexts in prow config

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7940]
/area prow
/kind feature

@stevekuznetsov @cjwagner @BenTheElder @krzyzacy

**Comment by kargakis** [comment]
Eventually we could also automate running migratestatus.

**Comment by BenTheElder** [comment]
I would prefer we automated migratestatus, fwiw. it seems prow should be able to do this for us pretty easily, though we might want to gate it behind some human approval just because of the token cost?

**Comment by cjwagner** [comment]
I like the idea of watching for actionable config updates from merge commits.
We should keep in mind that we will likely have to either:
- rate limit the process so much that it has to run for hours
    or
- use a separate bot token

**Comment by BenTheElder** [comment]
One thought I had was that we could have the boot comment on the PR with an
intent to update requesting that a member of some admin team reply with an
approval / some command to trigger the actual migration. (Possibly combined
with some rate limit).
Another token could help too though...

**Comment by stevekuznetsov** [comment]
The rate limiting code would be useful too for e.g. the `label_sync` and branch protection jobs.

**Comment by BenTheElder** [comment]
yes, label_sync, branchprotector, needs-rebase are throttled

**Comment by kargakis** [comment]
Issue updated

**Comment by stevekuznetsov** [comment]
This is done with the `status-reconciler`

/close
