### ISSUE TITLE
starter.yaml is invalid

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#7945]
reported by @steuhs

 `error: error validating "cluster/starter.yaml": error validating data: unknown object type "nil" in ConfigMap.data.plugins; if you choose to ignore these errors, turn validation off with --validate=false`

/area prow
/kind bug

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/7945 (related, but not the same issue)

**Comment by kargakis** [comment]
We should probably have a job that validates these files.
