### ISSUE TITLE
'Recent Runs' page on test grid doesn't show the run currently in progress

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/test-infra#795]
For example, if you open

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gci-gke-pre-release/

The top of the list is build 840:

`840 2016-10-11 13:02 PDT`

But build 841 is the build that is currently running. If I click on 840 and hack the URL I can see a status page for build 841, but the recent runs doesn't have a link to it. 

https://k8s-testgrid.appspot.com/google-gke#gci-gke-pre-release does have a link to 841, which is nice.

**Comment by rmmh** [comment]
This is because latest-build.txt is updated after a build finishes. Listing the whole directory is prohibitively slow, but I might be able to hack something up.
