### ISSUE TITLE
[RFE] Make node e2e tests over containerized kubelet release blocking

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/test-infra#7952]
We have had the node e2e tests over containerized kubelet [1] running for a while. Anything against making the tests release blocking? Targeting v1.11.

The tests have been running successfully since December up to some failed runs that were recently caused by bumping the minimal required version of Go to 1.10.1, followed by bump to 1.10.2.

At the same time the tests run in Red Hat infrastructure, so let's allocate at leas two folks on our side who will be responsible for fixing the CI in case it breaks.

[1] https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-conformance-aws-e2e-rhel

**Comment by ingvagabund** [comment]
@derekwaynecarr @sjenning @kubernetes/test-infra-maintainers

**Comment by ingvagabund** [comment]
Is there any documentation describing what are the minimal requirements to make a job release blocking?

**Comment by dims** [comment]
cc @kubernetes/sig-release-members @jberkus

**Comment by BenTheElder** [comment]
cc @spiffxp 
@spiffxp has worked on some info for making tests *presubmit* blocking, release blocking is somewhat up to the release-team, but from the test-infra side it basically just needs to be in the release-blocking dashboard(s).

**Comment by ingvagabund** [comment]
> from the test-infra side it basically just needs to be in the release-blocking dashboard(s).

Which dashboard is it? Is it publicly available?

**Comment by dims** [comment]
@ingvagabund see https://k8s-testgrid.appspot.com/k8s#kubelet&width=20 (and click on "sig-release") you will see a bunch of `*-blocking`. test-infra has config files to build this dashboard.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/8106#issuecomment-399520072

The best way to add blocking tests is to discuss with sig-release and then PR testgrid. sig-testing and test-infra maintainers work with the release team on which tests are in the release dashboards but don't dictate them.

**Comment by jberkus** [comment]
I'm -1 on adding more blocking tests that aren't 100% under the control of test-infra.  The history of the 1.11 release has been riddled with delays around fixing tests that run on Google infra and need specific Google staff to fix; adding more external tests is not a way to get a release out on time.  We need fewer external blocking tests, not more.

Happy to have this included in -all or something non-blocking, though.
