### ISSUE TITLE
Is something wrong with the latest kubetest?

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#7957]
I'm trying to run some tests locally using:

```
go run hack/e2e.go --up --test --test_args=..bla..bla..
```

But I get this in the output:

```
2018/05/07 20:59:35 e2e.go:158: Updating kubetest binary...
# cd /usr/local/google/home/shyamjvs/go/src/github.com/golang/protobuf; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/golang/protobuf/ptypes/any: exit status 1
2018/05/07 21:00:05 e2e.go:77: err: go get -u k8s.io/test-infra/kubetest: exit status 1
exit status 1
```

Is something broken with the latest kubetest? Thanks!

cc @kubernetes/test-infra-maintainers @krzyzacy @BenTheElder

**Comment by BenTheElder** [comment]
the git pull output / error is from `go` (`go get` shelling out to git specifically), not kubetest, and the reason a go-get is happening is hack/e2e.go will pull kubetest if the binary is old (which is debateable...)

**Comment by BenTheElder** [comment]
you'll have to fix your `$GOPATH`, you can re-clone `$GOPATH/src/github.com/golang/protobuf`

**Comment by shyamjvs** [comment]
Thanks Ben. Managed to fix it by restoring that pkg (sth bad happened to it somehow).
