### ISSUE TITLE
'Recent Runs' page on test grid has confusing time stamps

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes/test-infra#796]
The timestamp for a run appears to be the time when the run ended (rather than started). If I click on build 840, which on the recent runs page shows:

`840 2016-10-11 13:02 PDT`

Then I see

```
Result	FAILURE
Started	2016-10-11 12:06 PDT
Elapsed	55m27s
Version	v1.5.0-alpha.0
Builder	agent-light-5
```

So the run started at 12:06 PDT, which is the time that I think would be much more useful to show. 

Just like in https://github.com/kubernetes/test-infra/issues/795, https://k8s-testgrid.appspot.com/google-gke#gci-gke-pre-release shows the start time for each run.

**Comment by rmmh** [comment]
Ha, I was wondering if anyone would notice.

Right now it's just reading from finished.json, but I can make it read
started.json as well.
