### ISSUE TITLE
testgrid should support non-GCS stores for test results

### ISSUE THREAD

**Issue by dims** [kubernetes/test-infra#7960]
Can we please add support for things other than GCS buckets?
- plain old browsable web directories (http/https)
- S3 style object stores
etc..

**Comment by dims** [comment]
cc @thockin @BenTheElder

**Comment by BenTheElder** [comment]
cc @michelle192837 @rmmh
I believe the plan is to open source testgrid including the update which @fejta has also worked on but I'm not sure where these efforts are at currently.

**Comment by fejta** [comment]
/area testgrid
/help

This sounds like a great task for someone outside of Google to take on!

**Comment by BenTheElder** [comment]
this would be the OSS [updater](https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/updater) which scrapes the results, though we're not migrated to this one yet.

**Comment by akutz** [comment]
/remove-lifecycle stale

Hi @BenTheElder,

Is the OSS updater still the appropriate location to which to add support for non-GCS storage? Or has Spyglass superseded that? I was thinking of taking on the task of adding S3 support to the updater either directly or via the [Go Cloud Project](https://github.com/google/go-cloud).

**Comment by BenTheElder** [comment]
Spyglass is unrelated to testgrid. (they consume the same data but do different things, sypglass is targeted more at what gubernator job viewing does). I'll defer to @michelle192837 @fejta for testgrid.

**Comment by midnightconman** [comment]
Can we have an update on this @michelle192837?

**Comment by michelle192837** [comment]
Yup, though not a clear one. This is still blocked on open sourcing, and I don't have a good ETA at the moment for it. :( You probably want to track #10409, #3323, and/or #3324 for when I've got better updates on this.

**Comment by spiffxp** [comment]
FWIW, we're moving on open sourcing. It'll take a bit before we're in a position to accept contributions and see those land in testgrid.k8s.io, but we're getting there https://github.com/kubernetes/test-infra/issues/10409#issuecomment-515220552

**Comment by spiffxp** [comment]
/remove-help
I'm going to remove help since this is blocked at the moment, we should add back when it's feasible for a new contributor to accomplish
