### ISSUE TITLE
Prow job status icons are not showing up correctly in Firefox for Android on Marshmallow

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7963]
Firefox version: 59.0.2
Android version: 6.0.1
![screenshot_20180508-132244](https://user-images.githubusercontent.com/3900799/39777015-ab733fd0-5302-11e8-9b5d-567f0914f966.png)

/area prow
/kind bug

@kubernetes/sig-testing-bugs

**Comment by BenTheElder** [comment]
![screenshot_20180508-121203](https://user-images.githubusercontent.com/917931/39777696-1459e70a-52b9-11e8-82f6-8ff7c177dfac.png)

**Comment by BenTheElder** [comment]
I can't replicate on Firefox 59.0.2 / Android 8.1.0, perhaps Firefox for Android bugs on older SDKs?
