### ISSUE TITLE
Prow issue: dead link in email template

### ISSUE THREAD

**Issue by sakarikl** [kubernetes/test-infra#7969]
in following sentence here is a link which leads to 404.
"Instructions for interacting with me using PR comments are available here."

https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md

Mail was about "There are no sig labels on this issue. Please add a sig label."

**Comment by stevekuznetsov** [comment]
@kubernetes/sig-contributor-experience-bugs

**Comment by BenTheElder** [comment]
IIRC I patched this last week we just haven't deployed the patch yet.

**Comment by nikhita** [comment]
> IIRC I patched this last week we just haven't deployed the patch yet.

This should have been fixed in the latest prow bump, right?

**Comment by BenTheElder** [comment]
Yeah. It would have been good to cross reference the fix but this should be
done.
/close
