### ISSUE TITLE
Prow config is mixing camelCase, _underscores _, and -hyphens-

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7971]
* camelCase, eg. `missingLabels` in the tide config
* underscores, mostly used eg. `push_gateway`
* hyphens, eg. `branch-protection`

We should probably converge to a single format and stick with it.

@fejta @stevekuznetsov @cjwagner @BenTheElder @krzyzacy 

/area prow

**Comment by stevekuznetsov** [comment]
+1 to `snake_case` IMO

**Comment by BenTheElder** [comment]
we should also document whatever we move to somewhere or have a config linter to prevent regressions.

**Comment by cjwagner** [comment]
I vote hyphens, but I don't care much as long as we are consistent.

**Comment by fejta** [comment]
pronounSubject_I verbPredicate_Think implicitConjunction_That pronounSubject_We verbAuxilliary_Should verbPredicate_Use adjective_Hungarian nounDirect_Notation

**Comment by fejta** [comment]
We should make label_sync randomly assign a new color to the area/bikeshed label whenever the tool runs

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

If we want to look like k8s we should go with `camelCase`. Generically, can we write a serializer that loads either from `field_name` if present or `fieldName` if not? then we can do this migration slowly.

**Comment by BenTheElder** [comment]
We can add a new type embedding the real type temporarily that exposes the alternate field and then fixup that type into the real type.

+1 for going k8s style with `camelCase` for consistency.

**Comment by spiffxp** [comment]
/lifecycle frozen
/remove-kind bug
/kind cleanup
/milestone 2019-goals

Consistency helps discoverability and adoption

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
all the inconsistencies remain
