### ISSUE TITLE
Document each and every prow component

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#7974]
We had this issue coming. @fejta @cjwagner @stevekuznetsov @BenTheElder @krzyzacy @spiffxp  who is up for some docs either by enhancing existing docs or on the remaining parts of prow? :)

- [ ] artifacts_uploader
- [x] [branchprotector](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/README.md)
- [x] [clonerefs](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/clonerefs/README.md)
- [ ] deck
- [x] [entrypoint](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/entrypoint/README.md)
- [x] [gcsupload](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/gcsupload/README.md)
- [ ] gerrit
- [ ] hook
- [ ] horologium
- [x] [initupload](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/initupload/README.md)
- [x] [jenkins-operator](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/jenkins-operator/README.md)
- [ ] plank
- [x] [sidecar](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/sidecar/README.md)
- [ ] sinker
- [x] [tide](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/tide/README.md)
- [ ] tot

/area prow
/kind documentation

**Comment by stevekuznetsov** [comment]
Hey, I did my best :)

**Comment by krzyzacy** [comment]
I'll probably add the diagram from the deep dive

**Comment by stevekuznetsov** [comment]
Would be great to add links to the Deep Dive recording, the next best thing has been the (really, really old) presentation given in `sig-testing` meeting about a year ago.

**Comment by sipian** [comment]
Hi,
I am looking at prow for Prometheus test & benchmarking environment. 
It will be really helpful if some documentation could be provided about all the various fields in [config.yaml](https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml) & [plugins.yaml](https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml)

**Comment by kargakis** [comment]
@sipian not ideal today but you can find some documentation about those in godoc

https://godoc.org/github.com/kubernetes/test-infra/prow/config#Config
https://godoc.org/github.com/kubernetes/test-infra/prow/plugins

**Comment by spiffxp** [comment]
/help
FYI @cjwagner
