### ISSUE TITLE
Some e2e jobs use unrelated service-account

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/test-infra#7993]
From [build log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-autoscaling/6092/build-log.txt) of one of the failed runs of https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gke-autoscaling&show-stale-tests= 

```
I0510 17:01:15.038] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0510 17:01:15.860] Activated service account credentials for: [regional-e2e-test@k8s-jkns-e2e-regional.iam.gserviceaccount.com]
```

Looks like this (and other autoscaling GKE jobs) fails at tearing down old cluster. Previously, it was using a different account:

```
I0510 06:19:13.044] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0510 06:19:13.695] Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
```

A new one looks like it may be intended for this job: https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gke-autoscaling-regional&show-stale-tests= 

Was there any change related to service accounts used recently? Can we check if this is causing test failures?

**Comment by krzyzacy** [comment]
Hi @aleksandra-malinowska - this change was introduced in https://github.com/kubernetes/test-infra/pull/5563

is there still a recent run uses pr-kubekins? can you provide a link?

**Comment by aleksandra-malinowska** [comment]
Thanks for finding this. Looks like tests running on 1.10 branch are using pr-kubekins, e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-ubuntu1-k8sstable1-autoscaling/184

```
I0511 03:36:14.165] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0511 03:36:14.956] Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
```
Taking another look, it doesn't seem to be causing test failure directly in this case.

On the other hand, it looks like testgrid is showing cluster up failure for suites which were terminated due to timeout. See run [6094](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-autoscaling/6094) on [testgrid](https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gke-autoscaling&show-stale-tests=) - it doesn't show result for any scenarios (as if they were never launched), but [log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-autoscaling/6094/build-log.txt) indicates most of them run and succeeded. Is this expected?

**Comment by aleksandra-malinowska** [comment]
The first log contains failures related to corrupted state (a node-pool couldn't be removed, which caused subsequent scenarios to fail in BeforeEach phase - we should probably fix this by retrying in test)

There are no failures in the second log (6094), and on testgrid all runs of gci-gke-autoscaling recently look more or less the same, making it harder to identify issues like the one above.

**Comment by krzyzacy** [comment]
the last green run https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-autoscaling/6077 took 6h59m 😂 

sounds like we should bump the timeout for the job?

**Comment by aleksandra-malinowska** [comment]
> sounds like we should bump the timeout for the job?

This is kind of depressing, but I'm already working on PR with it :(

**Comment by krzyzacy** [comment]
oh nope sorry, it should only take ~30min

if you look at https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gke-autoscaling&graph-metrics=test-duration-minutes

the regression point looks like https://github.com/kubernetes/kubernetes/compare/4558e419b...b5f61ac12 ?!

**Comment by aleksandra-malinowska** [comment]
Created #8010 - can you approve it? Looking at the diff now.

**Comment by krzyzacy** [comment]
that's probably not caused by k8s changes... might be a gke change involved?

**Comment by krzyzacy** [comment]
/unassign
/assign @aleksandra-malinowska 

IMO the issue is test duration increased from 30m to ~400m and this is not a test-infra issue, I'll reassign to you for now.

**Comment by aleksandra-malinowska** [comment]
Closing as this doesn't seem to be related to service-accounts after all. I'll add investigating test duration to autoscaling team's backlog.
