### ISSUE TITLE
allow retester to work with optional contexts

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#8008]
[Soon](https://github.com/kubernetes/test-infra/pull/7983) tide will be able to handle optional github contexts. We should also find a solution for having the commenter ignore optional contexts too.

@stevekuznetsov @fejta @cjwagner 

/area prow
/kind feature

**Comment by kargakis** [comment]
@sdodson fyi

**Comment by BenTheElder** [comment]
Maybe its first comment can have /skip?
/remove-lifecycle rotten

**Comment by kargakis** [comment]
> Maybe its first comment can have /skip?

Note that /skip works only with contexts owned by prow.

**Comment by BenTheElder** [comment]
Sure, but I don't know if we need to solve "PR is lgtm + approve but not merging and failing a non-prow presubmit while using fejta-bot", OTOH: "PR is lgtm + approve but not merging while failing a non-blocking prow presubmit while using fejta-bot" seems simple to fix.
