### ISSUE TITLE
Should lifecycle/frozen issues retain other lifecycle labels

### ISSUE THREAD

**Issue by jwforres** [kubernetes/test-infra#8017]
Currently when I freeze lifecycle for an issue it leaves the other lifecycle labels like lifecycle/stale and lifecycle/rotten. This is never what I actually want when marking an issue as lifecycle/frozen and I always have to perform two actions to both freeze it and then remove the current state.

**Comment by jwforres** [comment]
cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
/area prow
/kind question

I would expect the other labels to be removed.

**Comment by nikhita** [comment]
I'd like to work on this, if nobody else is.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/test-infra/pull/8283
