### ISSUE TITLE
Stop using global flags in all Prow binaries.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#8065]
Instead use something like option structs and bind flags at the beginning of `main`.

ref #8050 
/area prow

**Comment by kargakis** [comment]
@petr-muller ptal

**Comment by kargakis** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/plank/main.go
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/sinker/main.go
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/main.go

**Comment by kargakis** [comment]
You can refactor that too if you want - splice is a deprecated component.
