### ISSUE TITLE
Periodic runs for the needs-rebase plugin do not work

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#8070]
Moving from https://github.com/openshift/release/issues/764

/kind bug
/area prow

@cjwagner @stevekuznetsov @BenTheElder @tnozicka

**Comment by BenTheElder** [comment]
https://platform.github.community/t/sporadic-502s-fetching-pr-data/3024/4
https://platform.github.community/t/randomly-unable-to-fetch-commit-author-fields-author-authoreddate-authoredbycommitter-api-returns-502s/5217/5

This seems to be a common problem.
