### ISSUE TITLE
figure out shellcheck in CI (and locally)

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8090]
https://github.com/koalaman/shellcheck seems to be a pretty awesome tool for linting shellscripts.

we can probably use WORKSPACE dependencies on shellcheck binaries, but the linux builds seem to have a dodgy glibc linkage and there don't seem to be published macOS binaries. we could build ourselves and stick them in GCS or something, but until then we're just making a lot of fixes from @rmmh running it locally.

/kind enhancement
xref: https://github.com/kubernetes/test-infra/pull/8032

**Comment by BenTheElder** [comment]
/cc @ixdy @rmmh
/assign
No idea when I'll do this (now? someday?) but if you both don't get to it first I'd like to see this figured out, we have too much shell to not be linting it :-)

**Comment by ixdy** [comment]
I think I looked at enabling shellcheck on kubernetes/kubernetes at one point, but there were so many errors reported I gave up and ran away screaming.

**Comment by cblecker** [comment]
I had the same idea/experience as @ixdy :)
cc @stevekuznetsov

**Comment by BenTheElder** [comment]
> I think I looked at enabling shellcheck on kubernetes/kubernetes at one point, but there were so many errors reported I gave up and ran away screaming.

we could do what test-infra does with lints, which is to incrementally widen the set of sources that are actually linted, excluding directories nobody has had time to fix yet.

**Comment by cblecker** [comment]
Future thought: for linting jobs (golint, shellcheck, even misspell) if we could use the github Checks API. I think they'd all be good candidates for portable jobs, and then we can run them anywhere. A much bigger thing to bite off, but perhaps an interesting project.

**Comment by BenTheElder** [comment]
Yeah. We have a golint plugin with sort of a home rolled variant of the
checks now. I think we don't have access to the checks API currently (in
beta, and only for GitHub Apps)

**Comment by BenTheElder** [comment]
we're at least working on fixing shellcheck lints throughout test-infra, getting it in CI is a next step.

**Comment by alisondy** [comment]
```
for file in $(find . -type f -name "*.sh"); do shellcheck --format=gcc $file >> outs ; done;
```
[shellchecktestinfra.txt](https://github.com/kubernetes/test-infra/files/2357029/shellchecktestinfra.txt)
I added a little line between the vendor stuff and what's in test-infra
stuff in test-infra comes up to 234 lines so 234 fixes
if there needs to be an extra push in cleaning this up I would be interested in helping out.

**Comment by BenTheElder** [comment]
I added this in k/k now
/remove-lifecycle rotten
