### ISSUE TITLE
Pod Utilities should expose a way for jobs to supply custom metadata.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#8104]
Gubernator and Testgrid both expose metadata about job runs based on the contents of the `metadata` field in finished.json. Previously, bootstrap.py populated this field and would include additional custom fields specified by the job in a metadata.json file. The sidecar pod utility (and maybe initupload) should be updated to do the same or similar.

/area prow
/cc @stevekuznetsov @fejta 
/help

**Comment by stevekuznetsov** [comment]
So we would want to mount in a configmap to expose the info to whichever utility uploads it? Is it just static data?

**Comment by cjwagner** [comment]
Not necessarily. It could be static, but it could also be some metric about the job that is determined at runtime (memory usage, retry attempt count, code coverage percentage, etc.).
I was imagining that we could just expose the location of an empty (or non-existent) `metadata.json` file similar to how we expose $ARTIFACTS to jobs. When sidecar is preparing `finished.json` for upload it could consume the `metadata.json` file if it exists to populate the `metadata` field.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

I'm of the opinion we should do this with some other file like `metadata.json` or something.

**Comment by krzyzacy** [comment]
I would prefer keep the current format so we don't have to patch testgrid/gubernator, and I can PR that (parse artifacts/metadata.json and merge into finished.json, like what bootstrap was doing) so we can migrate more k8s e2e jobs off bootstrap.

@cjwagner @stevekuznetsov @fejta thoughts? alternative ideas?

**Comment by cjwagner** [comment]
@krzyzacy That SGTM. We should probably have a few metadata fields that we automatically add if they are not explicitly overridden in `artifacts/metadata.json` like the refs, and job spec.

**Comment by krzyzacy** [comment]
:+1: 

should jobspec be part of the metadata, or a separate file, like bootstrap does?

**Comment by cjwagner** [comment]
> should jobspec be part of the metadata, or a separate file, like bootstrap does?

I'm not sure. A separate file might make more sense for consumption by a Spyglass viewer and if that is what bootstrap already does that might be also be the most convenient. I don't feel strongly either way though.

**Comment by krzyzacy** [comment]
@stevekuznetsov can we access ProwJob via sidecar?
