### ISSUE TITLE
Entrypoint giving error when no command & arg is given in config.yaml

### ISSUE THREAD

**Issue by sipian** [kubernetes/test-infra#8122]
On running a k8s job, I am getting `Invalid options: no process to wrap specified"`.
Since my [Dockerfile](https://github.com/sipian/golang-builder/blob/master/1.10/base/Dockerfile) has a bash file as ENTRYPOINT,  no command & args  field have been given in [config.yaml](https://github.com/sipian/test-infra/blob/prometheus-test/prow/config.yaml#L39).

Therefore, my pod YAML file has `"args":null` in `ENTRYPOINT_OPTIONS` env. 

It seems [entrypoint](https://github.com/sipian/test-infra/blob/prometheus-test/prow/pod-utils/decorate/podspec.go#L247)  is throwing this error because no command & args was given in config.yaml.
/area prow

**Comment by BenTheElder** [comment]
if you set `decorate: true` I believe you need to set an entrypoint in config.yaml, because the way we wrap it.

**Comment by BenTheElder** [comment]
cc @stevekuznetsov @cjwagner

**Comment by cjwagner** [comment]
You need to specify the binary location in the containers `command` field in config.yaml. This is described in the docs here: https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#how-to-configure
