### ISSUE TITLE
Tide categorising passing PRs using run_if_changed and run_after_success as 'prs-missing'

### ISSUE THREAD

**Issue by munnerz** [kubernetes/test-infra#8133]
As discussed in Slack -

We have recently enabled Tide for a repo that makes heavy use of run_if_changed and run_after_success to only test certain parts of a codebase in a monorepo depending on what files path have changed. We also use run_after_success to, for example, only run e2e tests against *all* kube versions if e2e tests against a single kube version pass (to save running all tests for a trivial breakage that'd be picked up by 1 test).

The repo in question: https://github.com/jetstack/tarmak
Our test-infra repo: https://github.com/jetstack/test-infra

Since enabling Tide, we are unable to get PRs to merge unless *all* tests have *actually* been run (i.e. despite them being 'Skipped' and green on GitHub, Tide does not merge the PR unless there is a ProwJob for each presubmit (even presubmits that don't match run_if_changed) that is marked as `state: success`.

We are running all Prow components at version `gcr.io/k8s-prow/tide:v20180521-f8caf9625`

The presubmit config for this repo: https://github.com/jetstack/test-infra/blob/master/prow/config.yaml#L882-L1085

Here are some example PRs that are passing, but not being merged:
- https://github.com/jetstack/tarmak/pull/259
- https://github.com/jetstack/tarmak/pull/185

These two PRs only require the quick-verify and docs-verify jobs to pass in order to merge according to our config.

And an example of a PR that *was* merged, but only after all presubmits have been run (manually triggered using `/test`):
- https://github.com/jetstack/tarmak/pull/251
- https://github.com/jetstack/tarmak/pull/253

(note those last 2 got a bit messed up during my debugging, and have ended out with a load of extra 'green' status contexts due to a combination of rolling back to old versions of Tide that don't support run_if_changed triggering all presubmits, and me fat-fingering when running a manual override of the status contexts using 'curl' in my debug attempts).

Tide is currently outputting:
```
{"base-sha":"685a8f161b9b12cf5938aa8f5fc00e564dd878c0","batch-passing":null,"batch-pending":null,"branch":"master","component":"tide","controller":"sync","level":"info","msg":"Subpool accumulated.","org":"jetstack","prs-missing":[259,185],"prs-passing":null,"prs-pending":null,"repo":"tarmak","time":"2018-05-25T09:45:08Z"}
```

(note that 259 and 185 are categorised as 'prs-missing')

I'm going to try and write some form of test case to reproduce this - but thought it best to get the info into a GitHub issue to foster discussion.

/cc @cjwagner @BenTheElder @sebastienvas

**Comment by munnerz** [comment]
cc @simonswine

**Comment by cjwagner** [comment]
> Tide does not merge the PR unless there is a ProwJob for each presubmit (even presubmits that don't match run_if_changed) that is marked as state: success.

We are not seeing this behavior, the run_if_changed jobs on our Prow instance are being handled properly.
If this actually is the problem it must have been introduced since we last updated our Tide instance.

Might be a good place to start with the unit tests since that should be easy to prove or disprove.

**Comment by munnerz** [comment]
So we've just discovered that we have `always_run: true` set on these optional presubmits as well as `run_if_changed` being used.

This is causing tide to trigger the presubmits due to `presubmitsByPull` having a special case for AlwaysRun presubmits (which seems like expected behaviour to me).

So this was a mis-configuration in my opinion, however it would be great if there were some validation check or error message printed that informs the user of the mistake - from what I understand, AlwaysRun and RunIfChanged are mutually exclusive.

**Comment by cjwagner** [comment]
>  AlwaysRun and RunIfChanged are mutually exclusive.

Thats correct. We should be validating this when parsing the config, but we aren't.
It also looks like we aren't checking that `context == ""` => `skip_report == true`.

I'll add some validation. Thanks for tracking this down James!
