### ISSUE TITLE
Publishing bot cannot push

### ISSUE THREAD

**Issue by sttts** [kubernetes/test-infra#8141]
Our publishing bot https://github.com/k8s-publishing-bot cannot push due to a `cla/linuxfoundation` check:
```
[28 May 18 05:54 UTC]: /publish_scripts/push.sh /etc/secret-volume/token master
	remote: error: GH006: Protected branch update failed for refs/heads/master.        
	remote: error: Required status check "cla/linuxfoundation" is expected.        
	To https://github.com/kubernetes/client-go
	 ! [remote rejected] master -> master (protected branch hook declined)
	error: failed to push some refs to 'https://github.com/kubernetes/client-go'
```

**Comment by cblecker** [comment]
that context is required, which means that it requires a PR to be generated. The one way around this would be to give the bot admin on the repo, as opposed to just write. this would allow it to push anyways, even without the right status contexts.

**Comment by cblecker** [comment]
I don't think it's that they don't pass the CLA, it's that they don't have the CLA context set.. which will never get set if isn't pushed and the CLA bot isn't delivered a webhook. chicken and egg.

**Comment by BenTheElder** [comment]
yeah, this is tricky cross-repo, IIRC contexts are reported to a (repo,
commit sha) so even though the commits have been checked that status
doesn't exist in the synced repo...

one way to actually get the CLA check would be for the bot to push to a
fork first and then open a PR with the commits, instead of directly pushing
(which Erick mentioned), the other mentioned options are all probably
reasonable as well.

**Comment by sttts** [comment]
Have to check whether it happens on every commit.

I started to do the CLA process for the bot, but stopped when faking name and signature :)

**Comment by sttts** [comment]
> fork first and then open a PR with the commits, instead of directly pushing
> (which Erick mentioned), the other mentioned options are all probably
> reasonable as well.

Unfortuantely not possible as it does not preserve the exact commit structure via a PR.

**Comment by BenTheElder** [comment]
> Unfortuantely not possible as it does not preserve the exact commit structure via a PR.

well if you just *open* the commit then we can get the cla status(es) IIRC, without necessarily merging it, since the statuses are not PR specific.
probably not worth it though /shrug

**Comment by cblecker** [comment]
@sttts can you confirm this is the right list of repos for the publishing bot: https://github.com/orgs/kubernetes/teams/stage-bots/repositories ?

**Comment by dims** [comment]
@cblecker looks like it. it matches the list of directories under staging

```
dims@bigbox:~/go/src/k8s.io/kubernetes/staging/src/k8s.io$ ls -1
api
apiextensions-apiserver
apimachinery
apiserver
client-go
code-generator
kube-aggregator
metrics
sample-apiserver
sample-controller
```

**Comment by sttts** [comment]
It's right ^^

**Comment by cblecker** [comment]
I've updated the permissions to admin, as well as filed https://github.com/kubernetes/test-infra/pull/8204 to ensure that the bots are the only ones pushing to those repos.

**Comment by cblecker** [comment]
Looks like this is fixed now. Can you confirm, @sttts ?

**Comment by sttts** [comment]
> Can you confirm

Yes, looks good again: https://stats.uptimerobot.com/wm4Dyt8kY

**Comment by cblecker** [comment]
Fantastic! Closing.
