### ISSUE TITLE
Misleading k8s-ci-robot message about lgtm permissions

### ISSUE THREAD

**Issue by ivan4th** [kubernetes/test-infra#8156]
When a github user who is not a project collaborator tries to `/lgtm` a PR, the following comment is produced by k8s-ci-robot:

> changing LGTM is restricted to assignees, and only kubernetes-sigs org members may be assigned issues

Here's an example of such message: https://github.com/kubernetes-sigs/kubeadm-dind-cluster/pull/130#issuecomment-392928351

Whereas (at least in case of kubernetes-sigs repos) project collaborators can use `/lgtm`, too.
(In the above case, it was fixed by adding the user to collaborators)

**Comment by stevekuznetsov** [comment]
Is this an artifact of the API call we use to check membership?

/kind bug
/area prow
/cc @BenTheElder @cjwagner

**Comment by BenTheElder** [comment]
It's because we intentionally check for collaborators as well, which is
configurable, but we don't surface this in the message.

**Comment by fejta** [comment]
The message is wrong, and we should fix it. Anyone who can be assigned can lgtm
