### ISSUE TITLE
Feature Request: Turn TODO comments in the codebases into Github issues

### ISSUE THREAD

**Issue by ihoegen** [kubernetes/test-infra#8192]
I think it'd be cool if one of the existing bots (or a new one) went through the various Kubernetes codebases and took TODO comments and turned them into Github issues.

Obviously, this wouldn't be trivial, and it'd be important to prevent spamming, and duplicate issues, but it's something I'd be happy to work on if others find the idea worthwhile

**Comment by nikhita** [comment]
> important to prevent spamming, and duplicate issues

I am afraid this would lead to a lot of spamming. :(

/cc @kubernetes/sig-contributor-experience-feature-requests
