### ISSUE TITLE
Plugin config needs to use pointers to structs instead of structs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#8193]
https://github.com/kubernetes/test-infra/blob/2a0b9e25c079afda989b28f63eb0c903148bca80/prow/plugins/plugins.go#L162-L172

Otherwise there is no point in using `omitempty`

/shrug
/area prow
/help

**Comment by A-Hilaly** [comment]
Hello !

Im new to the community here, can i deal with this ?

**Comment by kargakis** [comment]
@A-Hilaly yeah, it should be fairly easy to fix this; just need to ensure access to these structs is handled correctly so we won't panic on a `nil`. I would start with refactoring the structs one by one to ease reviewing.

**Comment by A-Hilaly** [comment]
Alright thanks, i will open a PR starting the modifications soon. 
I took a little look in `prow/plugins` package and I found some functions (example: `helpProvider` in `prow/plugins/heart` package) that uses theses structs. I'm i getting into the right place ?
Does other packages than `prow/plugins` have access to these structs ?

**Comment by kargakis** [comment]
> Does other packages than prow/plugins have access to these structs ?

I would say no but I am not sure off the top of my head. Start with a refactoring a single struct and see where that goes.

**Comment by A-Hilaly** [comment]
I started with refactoring the structs at #8255 (started with `Heart`) 
Can you check if i'm doing it right ? before i move to other structs

**Comment by matthyx** [comment]
@A-Hilaly did you give up on that one?

**Comment by matthyx** [comment]
ok, I'll take that one next
/assign

**Comment by matthyx** [comment]
Alright, I need some clarification on how we want to proceed here:

1. If I move to using pointers to structs in Blunderbuss for example, I will have to handle a nil config with a function (pretty much like in size.go) rendering the code in plugins.setDefaults() obsolete. Is that what we want?
1. I also wonder how we will roll-out the migrated plugins, as the config will break in all orgs when they will bump prow...

**Comment by alvaroaleman** [comment]
Naive question as the initial reason for doing this is `Otherwise there is no point in using omitempty`: When do these configs get serialized?

**Comment by stevekuznetsov** [comment]
So having just had a couple NPE issues with this -- let's get rid of the `omitempty` from our serialization code, and not change anything to be a pointer. Let's get rid of pointers entirely. Our configuration structs should be fully functional in their empty/zero value state and we should be able to use those as-is. This makes it much less likely we continue to have NPE and has no downsides I can see.

**Comment by stevekuznetsov** [comment]
@alvaroaleman those are in `plugins.yaml`

**Comment by matthyx** [comment]
> So having just had a couple NPE issues with this -- let's get rid of the `omitempty` from our serialization code, and not change anything to be a pointer. Let's get rid of pointers entirely. Our configuration structs should be fully functional in their empty/zero value state and we should be able to use those as-is. This makes it much less likely we continue to have NPE and has no downsides I can see.

Alright, so I close this issue, and create a new one doing exactly the opposite?

What about the []struct, as technically these are pointers too?

And my question remains: how will we rollout to avoid config incompatibilities?

**Comment by stevekuznetsov** [comment]
> Alright, so I close this issue, and create a new one doing exactly the opposite?

That seems reasonable to me, but would like to hear @cjwagner opinion

> What about the []struct, as technically these are pointers too?

That should be fine, since a loop over a nil slice will do nothing

> And my question remains: how will we rollout to avoid config incompatibilities?

I don't think changing an internal type should make any? Which ones are you worried about

**Comment by matthyx** [comment]
Well, is the json different between a struct and a pointer to a struct?

**Comment by matthyx** [comment]
Alright, let's do the opposite then... #11517
/close
