### ISSUE TITLE
Gubernator: Server error when trying to view job results for a PR.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#8219]
The `tensorflow/minigo PR #251` link at the top of this page: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/tensorflow_minigo/251/pull-tf-minigo-cc/10/ links to https://k8s-gubernator.appspot.com/pr/tensorflow/minigo/251 which should show all job results for the PR, but is currently omitting a key error instead.

Interestingly https://k8s-gubernator.appspot.com/pr/tensorflow/minigo/249 works fine along with other PRs with lower number. I'm thinking this could be related to the pod utilities because we started running `pull-tf-minigo-cc` on PRs after that one.

/kind bug
/area gubernator
/assign @rmmh

**Comment by stevekuznetsov** [comment]
xref #6092
