### ISSUE TITLE
kops e2e on GCE broken

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#8220]
kops e2e on GCE has been broken since #7395

**Comment by justinsb** [comment]
There's a real fix in #7408, but going to propose a simple revert of #7395 as it looks like other things have broken while our testing has been known-broken

**Comment by justinsb** [comment]
Pretty sure it's still broken, and I am working through it

/reopen

**Comment by JohnTitor** [comment]
Hey @justinsb, is this still broken? The TODO says "remove me once #7408 has been merged" but you said "it's still broken" on 1 Nov 2018, while it was merged on 7 Jun 2018, so I'm confused with the current status.
