### ISSUE TITLE
Moving commits across release/feature branches makes CLA bot angry

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#8241]
It seems impractical/silly to make hundreds of people affirm it's OK for us to e.g. merge master back into a feature branch.

**Comment by lavalamp** [comment]
I think I filed another issue about this somewhere, but I can't find it.

**Comment by BenTheElder** [comment]
test-infra doesn't implement/manage the CLA bot, I'm not sure what the expectation is here from upstream. Perhaps @dankohn can weigh in or point us to someone who can?

**Comment by lavalamp** [comment]
Yeah, I couldn't find a place to file this.

**Comment by stevekuznetsov** [comment]
ping @dankohn 
/remove-lifecycle rotten

**Comment by stevekuznetsov** [comment]
Can it be rolled out to a specific repository, not an org? We frequently beta-test changes in `test-infra`

/cc @fejta
