### ISSUE TITLE
prow: tide: label merge commit with members who LGTM and approve the commits

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#8242]
We had an RFE to label the merge commit (in the body?) with data about who had left the LGTM and approve on a PR before `tide` merged it.

/cc @spadgett @jwforres @cjwagner @fejta @BenTheElder 
/area prow
/kind enhancement

**Comment by BenTheElder** [comment]
interesting, I think I like that idea :-)
worth noting: usernames etc are mutable, so for a perfect record you probably need to use something like GitHub UID as well.

**Comment by cjwagner** [comment]
As long as we don't tag the users in the commits (i.e. make sure there is no `@` symbol).
I have my username tagged in a test-infra commit somewhere and now GitHub auto-subscribes me to every single fork of test-infra that is made...

**Comment by BenTheElder** [comment]
yes, this x1000. I'm tagged in some test-infra and kubernetes commits, and
github loves to remind me :^)
