### ISSUE TITLE
Self approvals are not working when /approve is included in opening PR comment

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#8250]
I had to retry `/approve` in a separate comment: https://github.com/Azure/acs-engine/pull/3169#issue-192638340

/kind bug
/area prow

@cjwagner @stevekuznetsov

**Comment by nikhita** [comment]
@kargakis shouldn't the "approved" label apply automatically once the PR is created (which means you don't need to write `/approve` in a opening PR comment)? That's at least what I see in k/k.

**Comment by stevekuznetsov** [comment]
Looks like you had to add the `/label` command three times too, did you have webhooks dropped? Do you have logs from `hook` for that PR creation event?

**Comment by kargakis** [comment]
k/k is using implicit self-approvals, ie you don't need to /approve if you
are an approver and the PR author or you /lgtm and lgtm can act as approve.
