### ISSUE TITLE
There's no 1.11 bazel build/test jobs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8257]
kubeadm-1.11 is looking for gs://kubernetes-release-dev/ci/latest-bazel-1.11.txt

/assign @BenTheElder 
cc @roberthbailey

**Comment by dims** [comment]
i got started - https://github.com/kubernetes/test-infra/pull/8256

**Comment by krzyzacy** [comment]
ahh, thanks @dims !

**Comment by dims** [comment]
Fixed. will check the job output. Still need https://github.com/kubernetes/test-infra/pull/8260 to merge before the jobs work.
