### ISSUE TITLE
gubernator failed to highlight verify-check failure

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#826]
Failed run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31921/kubernetes-pull-verify-all/18057/

Expanding the build log, we can see the failure:
```
Verifying hack/make-rules/../../hack/verify-gofmt.sh
!!! 'gofmt -s -w' needs to be run on the following files: 
./pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
FAILED   hack/make-rules/../../hack/verify-gofmt.sh	11s
```

Ideally gubernator should be auto-expanding this. Are the ANSI codes confusing it?

**Comment by rmmh** [comment]
This is gross. What's actually happening is:

    re.search(r'\bFAILED\b', '\x1b[0;31mFAILED\x1b[0m')

Which doesn't match, because m isn't a word boundary.
