### ISSUE TITLE
Avoid running scalability presubmits on trivial PRs

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#8263]
Based off of the idea we discussed today in sig-testing and sig-release meetings. Though this isn't a blocker for https://github.com/kubernetes/test-infra/pull/7954.

cc @AishSundar @BenTheElder @jdumars @jberkus @kubernetes/sig-scalability-misc @kubernetes/test-infra-maintainers

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/issues/2547
