### ISSUE TITLE
mkpj needs to support split job config

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8264]
/kind bug
/area prow
/assign @krzyzacy

**Comment by krzyzacy** [comment]
what does this mean?

**Comment by BenTheElder** [comment]
`prow/cmd/mkpj` needs to work with multiple job config files, right now it only has a `--config-path=` file to specify monolithic `config.yaml`

**Comment by krzyzacy** [comment]
IMO you pass in one config file for one job, unless we want a batch mode for mkpj

**Comment by BenTheElder** [comment]
@krzyzacy I suspect right now it would fail to load it :-)

```
func main() {
	o := gatherOptions()
	if err := o.Validate(); err != nil {
		logrus.Fatalf("Invalid options: %v", err)
	}

	conf, err := config.Load(o.configPath, "")
	if err != nil {
		logrus.WithError(err).Fatal("Error loading config.")
	}
```

**Comment by krzyzacy** [comment]
why? it should not.

**Comment by BenTheElder** [comment]
@krzyzacy if the job is in another file we won't load it... we only load the main prowConfig file right now. It won't parse ...?

In any case it should also support reading in *all* of the files so you don't have to hunt down the right file to retrigger a job with the new config :-)

**Comment by krzyzacy** [comment]
sure, I'll add another flag, basically for all the controllers.

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/cmd/mkpj/main.go#L62

looks like it's supported now
