### ISSUE TITLE
PR status dashboard is not loading.

### ISSUE THREAD

**Issue by amwat** [kubernetes/test-infra#8267]
The PR status dashboard (https://prow.k8s.io/pr) is not loading any results.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/commit/33ea7f7a28381d8767aa3a0fb60ee2015c8224d4#r29256994

the tide page is also broken, but unrelated

**Comment by stevekuznetsov** [comment]
Oops. Should that be `typeof branding === 'undefined'` instead?

**Comment by BenTheElder** [comment]
I think, not a big deal since we haven't really advertised that page yet, but it's blowing up on null right now. Tide has a similar issue. Guess we just need to sprinkle null checks over our JS :-) /s

**Comment by qhuynh96** [comment]
I found the bugs.

The first one is null branding. Probably change the check to ```if (!branding)``` which covers all null and undefined. 

The second bug is doing with Tide Queries. It seems that there is a new Tide query for approve / lgmt label that applies on org ```kubeflow``` and does not have any repo listed. This causes the crash. I will update the script to handles this case.

**Comment by BenTheElder** [comment]
thanks Quang!
