### ISSUE TITLE
docs-no-retest regex should be configurable

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#8275]
The regex used for docs-no-retest should be configurable without updating the code

ref: https://github.com/kubernetes/test-infra/pull/8207

/area prow

**Comment by BenTheElder** [comment]
I don't think tide even has a concept of `docs-no-retest` @cjwagner

**Comment by cjwagner** [comment]
Thats correct, it does not.

**Comment by cblecker** [comment]
*Should* it though? Would that be advantageous to be able to skip retesting certain PRs?

**Comment by cjwagner** [comment]
We've discussed something similar here: https://github.com/kubernetes/test-infra/issues/5334

I'm not sure how advantageous it would be. It might be necessary for us to add it as a feature.

**Comment by nikhita** [comment]
Can we add `OWNER_ALIASES` explicitly for now and refactor when we make it configurable? ref: https://github.com/kubernetes/test-infra/pull/8207#discussion_r193465456

I think this is the second (maybe even third) PR I have seen recently which is changing `OWNER_ALIASES` and is running the complete test suite.

I'm happy to add `OWNER_ALIASES` to the file but don't have the bandwidth to send a PR to make it configurable atm. :)

**Comment by cjwagner** [comment]
> Can we add OWNER_ALIASES explicitly for now and refactor when we make it configurable?

SGTM

**Comment by nikhita** [comment]
created https://github.com/kubernetes/test-infra/pull/8482 to add OWNERS_ALIASES.

**Comment by spiffxp** [comment]
Could this be implemented via OWNERS files with labels?

**Comment by BenTheElder** [comment]
I think so, but the tide end still needs to exist for it to be useful outside of k/k running the submit-queue still.

**Comment by spiffxp** [comment]
Upon further reflection I don't think it could.  This sort of label can only be applied if _all_ files match the regex(es).  The owners-label approach would put on a label if _any_ file matched.  And yes, this isn't supported by tide.
