### ISSUE TITLE
Document How to Enable Prow/Tide on New Repos

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/test-infra#8286]
I was recently asked how to do this for new repos in the kubernetes-sigs org.   I *think* it's a simple change the the config file in the prow directory, but if there's more to it (regardless actually), we should write down the steps for enabling prow/tide on new repos (and which organizations are included).

/kind documentation
/area prow

**Comment by nikhita** [comment]
cc @munnerz because he's done it before :)

**Comment by stevekuznetsov** [comment]
We have sections in the Prow README for configuring plugins and adding new jobs, but I agree that there should be some "I am new and I want all the things to work for my new repo" document.

/cc @BenTheElder @cjwagner

**Comment by nikhita** [comment]
I'd like to help with this! 

> "I am new and I want all the things to work for my new repo" 

Does new repo here mean a repo in a kubernetes-related org (eg kubernetes-sigs) or does it mean my-personal-non-kubernetes-related-org?

**Comment by cjwagner** [comment]
> Does new repo here mean a repo in a kubernetes-related org (eg kubernetes-sigs) or does it mean my-personal-non-kubernetes-related-org?

Eventually we'll probably want both, but a general version is more important.

Just so we don't duplicate work. I have Tide documentation rooted [here](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/tide#tide) and am working on some other Prow docs in https://github.com/kubernetes/test-infra/pull/9414.

**Comment by spiffxp** [comment]
/milestone 2019-goals
/assign @cjwagner @fejta @nikhita 

I have a sneaking suspicion this can now be closed?  Or was there more simplification/docs to be done?

**Comment by cjwagner** [comment]
I think this has been pretty well addressed now.
If we find areas of the docs that are lacking we should open more specifically targeted issues.
/close
