### ISSUE TITLE
Make update-config plugin support update a directory

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8296]
cc @fejta 
/area prow
/assign

**Comment by krzyzacy** [comment]
looks like configmap does not support subdirectories for --from-file option, but you can still create subdir within a configmap

maybe we need to script it up

cc @BenTheElder

**Comment by krzyzacy** [comment]
hummm

```
error: "prow/internal/config.yaml" is not a valid key name for a ConfigMap: a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

probably need to do some pre-processing to flatten the path

**Comment by BenTheElder** [comment]
Or instead merge the files before upload?

**Comment by krzyzacy** [comment]
@BenTheElder you mean merge into one document, or multiple documents in one file?

**Comment by BenTheElder** [comment]
One document? The latter could also work though, and is probably simpler to
handle.

**Comment by krzyzacy** [comment]
(this is done)
