### ISSUE TITLE
Rotate prow service account

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8300]
/area prow

**Comment by BenTheElder** [comment]
/cc @amwat 
perhaps we can automate monitoring the age of the main GCP service account key file and reminding the maintainers to switch to rotate the credentials.

I think we just need to follow https://cloud.google.com/security/data-loss-prevention/revoking-user-access#rotate_project_credentials

**Comment by BenTheElder** [comment]
/assign @amwat @krzyzacy @bentheelder

discussing offline, this should be a key Q3 objective to fix

**Comment by krzyzacy** [comment]
(I'll remember to review Amit's change 😂)

**Comment by fejta** [comment]
Ideally we write a controller to do this for us.

**Comment by krzyzacy** [comment]
cc @michelle192837 

:joy: @amwat bring your awesome bash to the bright side?

**Comment by stevekuznetsov** [comment]
"awesome bash"
:fearful:
