### ISSUE TITLE
Make ConfigAgent support yaml file with multiple documents

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8301]
Let's go this route instead, will patch up config.go first

/area Prow
/assign

**Comment by BenTheElder** [comment]
SGTM, next step we can update the configmap updater to scoop up all of the jobs and concat them to the main config.

perhaps we need a `kind` field like kubernetes API blobs?

**Comment by krzyzacy** [comment]
(not needed)
