### ISSUE TITLE
Add `/stage` command for `k/features`

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/test-infra#8315]
Of the 108 [currently open Features issues](https://github.com/kubernetes/features/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen), [87 of them](https://github.com/kubernetes/features/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22%2Fstage%22) include an attempt to use `/stage`, which doesn't currently exist.

Could we roll this functionality into a current prow plugin?
It'd be helpful for people to be able to appropriately set the stage of a feature.

@kubernetes/sig-testing-feature-requests 
/help

**Comment by BenTheElder** [comment]
hmm, so a `(/stage (alpha|beta))|(/remove-stage)` command?

**Comment by nikhita** [comment]
> so a (/stage (alpha|beta))|(/remove-stage) command?

`/[remove-]stage (alpha|beta|stable)`

**Comment by nikhita** [comment]
And if it's decided that we'd like to have something like this, I'd like to work on it if that's fine. :)

**Comment by justaugustus** [comment]
@BenTheElder @nikhita yup, that's exactly what I'm looking for!

> And if it's decided that we'd like to have something like this, I'd like to work on it if that's fine. :)
Go for it!

/assign @nikhita
