### ISSUE TITLE
Teach Janitor script to clean up NEG in any zone

### ISSUE THREAD

**Issue by freehan** [kubernetes/test-infra#8327]
Currently it is hard coded in `boskos/janitor/janitor.py`

The zone parameter is in a subresource of NEG resource.

**Comment by freehan** [comment]
@krzyzacy 
The zone parameter has been moved to the root level of a NEG object. That will help right?

**Comment by krzyzacy** [comment]
which means we can drop https://github.com/kubernetes/test-infra/blob/master/boskos/janitor/janitor.py#L219-L222 now right?

**Comment by freehan** [comment]
```
gcloud beta compute network-endpoint-groups list --format='json(name,creationTimestamp.date(tz=UTC),zone,region,isManaged)'
```

is still not displaying the zone information
