### ISSUE TITLE
Prow issue:kube-dns getting CrashLoopBackOff

### ISSUE THREAD

**Issue by SHUFIL** [kubernetes/test-infra#8333]
Uncomment only one, leave it on its own line:

kind bug
/kind feature

What happened:

What you expected to happen:
I have installed kubernetes, and Docker, removed swap , disabled firewall, then i build up the kubernetes master using kubeadm init --pod-network-cidr 10.10.10.0/16
#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

#kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
Then added node system sudo kubeadm join --token a2d.. etc
currently showing server and node correctly using kubectl get nodes
But the same i getting error kube-dns CrashLoopBackOff - kubectl get pods --all-namespaces, i have chked the syslog , i got below error message
###"Jun 12 12:46:57 server kubelet[17532]: W0612 12:46:57.349698 17532 cni.go:171] Unable to update cni config: No valid networks found in /etc/cni/net.d
Jun 12 12:47:02 server kubelet[17532]: W0612 12:47:02.352133 17532 cni.go:113] Error loading CNI config list file /etc/cni/net.d/10-flannel.conflist: error parsing configuration list: no 'plugins' key"

**Comment by SHUFIL** [comment]
Kubernetes version (use kubectl version):v1.10.4

Cloud provider or hardware configuration:

OS (e.g. from /etc/os-release):"Ubuntu 16.04.3 LTS"

Kernel (e.g. uname -a):Linux server 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Install tools: kubernetes , Docker only

Others:nothing

**Comment by munnerz** [comment]
You may be better off asking this question over in #kubernetes-users on Slack, or opening an issue on kubernetes/kubernetes 😄. This does not seem like an issue related to Prow or test-infra? Could you clarify with some extra info if it is 😄

**Comment by kargakis** [comment]
Seems like a [`kubeadm`](https://github.com/kubernetes/kubeadm/issues) issue, please reopen in that repo.

**Comment by rafis** [comment]
Any solution?
