### ISSUE TITLE
Support repo-scoped labels

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#8342]
Would be nice to scope labels per repo in labels_sync. See https://github.com/kubernetes/test-infra/pull/8335#issuecomment-396681981 for more context.

/cc @fejta @cblecker

**Comment by fejta** [comment]
This can/should follow the pattern in https://github.com/kubernetes/test-infra/tree/master/prow/cmd/branchprotector (or prow/cmd/peribolos)

**Comment by nikhita** [comment]
one more reason why we should have this: k/k has `area/*` labels but it's not present in https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md. These labels are also, by virtue, highly specific to k/k.

**Comment by matthyx** [comment]
In PR #8335 @stevekuznetsov and @cjwagner write about a label framework... is it usable now for this issue?

**Comment by stevekuznetsov** [comment]
Not yet -- the PR for the framework is in #8131

**Comment by matthyx** [comment]
Alright, so it has little to do with labelsync... I will see if I can implement something with the same pattern matching as branchprotector, as @fejta suggests.

**Comment by matthyx** [comment]
Can we agree on this new format for [labels.yaml](https://github.com/matthyx/test-infra/blob/db79317bba502270580ba63b2925e9a7dd923e2f/label_sync/labels.yaml) ?

**Comment by stevekuznetsov** [comment]
Is there a design for the new format somewhere to review?

**Comment by matthyx** [comment]
Actually I did it a bit differently, it's more compact that way. I let you check the PR.

**Comment by spiffxp** [comment]
/cc
looking forward to the PR

I had a bunch of conceptual hangups that kept me from moving forward on repo-scoped stuff, but it's the next logical step.  Mainly centered around how we would DRY this up so that label docs are served on the fly per-org / per-repo, in much the same way we do today with prow commands and plugins.

**Comment by matthyx** [comment]
@nikhita you can safely start adding kubernetes/kubernetes specific labels to labels.yaml

**Comment by nikhita** [comment]
> @nikhita you can safely start adding kubernetes/kubernetes specific labels to labels.yaml

This is so cool! Thanks, @matthyx! :tada: 

Will do, added to my todo list.
