### ISSUE TITLE
Make kubemark-500 presubmit faster

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#8348]
Ref https://github.com/kubernetes/test-infra/pull/7954

Currently it takes somewhere around 1h20m to 1h30m to run it. We should speed it up and cut short the delay it introduces on top of our slowest presubmit (that takes ~1h5m).
This is even more important for batch runs (than PR runs, where this increase is negligible compared to the PR's lifetime) as it can affect merge throughput.

cc @kubernetes/sig-scalability-bugs @BenTheElder @AishSundar @krzyzacy @wojtek-t

**Comment by BenTheElder** [comment]
Thanks!
NB: The PR lifecycle is something of a bug for small PRs especially. Fixing that is a much larger discussion but keeping presubmit times down is helpful towards that, if not anywhere near as important right now.

**Comment by shyamjvs** [comment]
@krzysied @mborsz - In case one of you may be interested in looking into this

**Comment by wojtek-t** [comment]
I took a quick look into that. And this is how it currently looks like:
- 15m - build k8s
- 6-7m - down (previous) + up cluster
- 5m - up kubemark (+check it)
- ~20s - preparation for tests (find master, etc. - typical e2e framework stuff)
- 33m - tests [surprisingly, in regular kubemark-500, the exact same tests take 28m - so 5m less]
- 1m - dumping kubemark logs
- 5m - down kubemark
- 1m30s - dumping logs from base cluster
- 10m - down cluster
- 2-3m - other stuff


So things that we should do first are:
- understand why tests take longer here (I guess it's too few resources on test worker and cpu-starvation) and fix this 
- consider using log-exporter
- figure out if we can speed up (parallelize) kubemark up and down steps

Out tests themselves aren't very long (~25m of regular gce suite vs ~33m (should be ~28m)) - so the difference should be negligible. It's additional setup and tear down steps that make them that much longer mostly.

**Comment by shyamjvs** [comment]
Thanks for finding the time break-up of the job @wojtek-t.

> understand why tests take longer here (I guess it's too few resources on test worker and cpu-starvation) and fix this

Actually iirc, this part was variable (and sometimes it's indeed lower) - we need to check that (otherwise we maybe focusing on red herring). If it's varying, we should also try to understand why it is.

> consider using log-exporter

+1 - I think you sent such a change today morning?
(though the benefits here may not be much)

> figure out if we can speed up (parallelize) kubemark up and down steps

+10 (also what I was suggesting in sig-testing meeting).
Also - we should be able to parallelize kubemark-down with base-cluster-down (which should cut a good 5m based on the above).
Similarly, we can parallelize kubemark master creation with real cluster up.

**Comment by shyamjvs** [comment]
So the time for successful presubmit runs seems to actually vary quite a bit, between:

1h10m - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/64684/pull-kubernetes-kubemark-e2e-gce-big/11062/build-log.txt

1h30m - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/64812/pull-kubernetes-kubemark-e2e-gce-big/11064/build-log.txt

**Comment by BenTheElder** [comment]
15m to build k8s sounds very wrong...due to caching we can usually get a job that does "bazel build the entire tree" in well under 10m (closer to 5...7)

**Comment by BenTheElder** [comment]
Oh right kubemark image doesn't support Bazel....
If you all fix that `make bazel-release` with caching enabled is about 3 min instead of 15 for quick-release and is otherwise equivilant.
https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&graph-metrics=test-duration-minutes

**Comment by shyamjvs** [comment]
@krzyzacy I remember you were earlier trying to make bazel work for kubemark (we even checked in some code iirc). What issues do we have, if any?

**Comment by krzyzacy** [comment]
eh... I've never get back to that... 

last comment was about missing bazel workspace? 
https://github.com/kubernetes/kubernetes/pull/53904#issuecomment-336577099

**Comment by BenTheElder** [comment]
presubmits overall are still quite slow, I believe this is one of the barriers to getting fixes in quickly and draining the merge queue after code freeze, and even to a degree contributing. This is the slowest.

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
This is no longer a blocking presubmit

**Comment by wojtek-t** [comment]
We no longer run it on presubmit. At the same time, we're working on speeding up tests and these are tracked elsewhere.
Closing

/close
