### ISSUE TITLE
Fix velodrome lint errors

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#8355]
/good-first-issue

Run https://github.com/golang/lint on `./velodrome/...`

**Comment by matthyx** [comment]
@fejta can you assign it to me, pls? (I should really consider joining k8s org...)

**Comment by krzyzacy** [comment]
@matthyx you cannot be assigned unless you are a k8s org member, or a repo collaborator

but feel free to send PR that links to this issue :-)

**Comment by matthyx** [comment]
I will finish it tomorrow...
