### ISSUE TITLE
When is a new kubekins-e2e image built?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#8357]
I thought that a new kubekins-e2e image was built on every commit to test-infra, but that doesn't seem to be the case - it looks like the last one was built 8 days ago.

(At least from visiting https://gcr.io/k8s-testimages/kubekins-e2e in a browser)

When is the latest-master image built?

(I'm trying to get the (new) job https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kops#kops-gce-canary working, it's using an older kubetest AFAICT.)

Thanks!

**Comment by fejta** [comment]
They are created on demand. Ask oncall if you want one. 

Auto creation hasn't been implemented yet

**Comment by krzyzacy** [comment]
/assign
whoops we are in a summit, pushing one right now

**Comment by dims** [comment]
here's @krzyzacy 's PR for the new image @justinsb https://github.com/kubernetes/test-infra/pull/8358

**Comment by justinsb** [comment]
Thanks for pushing the image :-)
