### ISSUE TITLE
Prow issue: verify bazel failure -- cannot understand the error

### ISSUE THREAD

**Issue by minherz** [kubernetes/test-infra#8373]
Hello,
I have `verify bazel` test fail in `pull-kubernetes-verify` with the following details:
```
diff -Naupr -x _output /go/src/k8s.io/kubernetes/pkg/cloudprovider/BUILD /tmp/verify-bazel.dpWGCB/go/src/k8s.io/kubernetes/pkg/cloudprovider/BUILD
--- /go/src/k8s.io/kubernetes/pkg/cloudprovider/BUILD	2018-06-15 16:11:00.697555947 +0000
+++ /tmp/verify-bazel.dpWGCB/go/src/k8s.io/kubernetes/pkg/cloudprovider/BUILD	2018-06-15 16:15:04.462125284 +0000
@@ -3,6 +3,7 @@ package(default_visibility = ["//visibil
 load(
     "@io_bazel_rules_go//go:def.bzl",
     "go_library",
+    "go_test",
 )
 
 go_library(
@@ -37,3 +38,15 @@ filegroup(
     ],
     tags = ["automanaged"],
 )
+
+go_test(
+    name = "go_default_test",
+    srcs = ["cloud__test.go"],
+    embed = [":go_default_library"],
+    deps = [
+        "//pkg/api/testapi:go_default_library",
+        "//vendor/k8s.io/api/core/v1:go_default_library",
+        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
+        "//vendor/k8s.io/apimachinery/pkg/types:go_default_library",
+    ],
+)
diff -Naupr -x _output /go/src/k8s.io/kubernetes/pkg/controller/service/BUILD /tmp/verify-bazel.dpWGCB/go/src/k8s.io/kubernetes/pkg/controller/service/BUILD
--- /go/src/k8s.io/kubernetes/pkg/controller/service/BUILD	2018-06-15 16:11:00.749560762 +0000
+++ /tmp/verify-bazel.dpWGCB/go/src/k8s.io/kubernetes/pkg/controller/service/BUILD	2018-06-15 16:15:04.475126488 +0000
@@ -43,6 +43,7 @@ go_test(
     embed = [":go_default_library"],
     deps = [
         "//pkg/api/testapi:go_default_library",
+        "//pkg/cloudprovider:go_default_library",
         "//pkg/cloudprovider/providers/fake:go_default_library",
         "//pkg/controller:go_default_library",
         "//vendor/k8s.io/api/core/v1:go_default_library",

Run ./hack/update-bazel.sh
+++ exit code: 1
+++ error: 1
FAILED   verify-bazel.sh	13s
```

I cannot figure out what is an error or find a documentation that explains a way to investigate it. Any advise is appreciated.

**Comment by fejta** [comment]
This is showing you a diff
```
diff
``
of what you have in your enlistment
```
/go/src/k8s.io/kubernetes/pkg/cloudprovider/BUILD
```
compared to what you need to have
```
/tmp/verify-bazel.dpWGCB/go/src/k8s.io/kubernetes/pkg/cloudprovider/BUILD
```

The + lines are ones that are missing, and there are a bunch
```
+    "go_test",
...
+
+go_test(
+    name = "go_default_test",
+    srcs = ["cloud__test.go"],
+    embed = [":go_default_library"],
+    deps = [
+        "//pkg/api/testapi:go_default_library",
+        "//vendor/k8s.io/api/core/v1:go_default_library",
+        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
+        "//vendor/k8s.io/apimachinery/pkg/types:go_default_library",
+    ],
+)
...
+        "//pkg/cloudprovider:go_default_library",
```

It links to the formatter that will fix this for you and it tells you how to fix this:
```
Run ./hack/update-bazel.sh
```

/remove-good-first-issue

**Comment by minherz** [comment]
@fejta i just need to run `./hack/update-bazel.sh and it will fix my `cloud__test.go`, right?

**Comment by minherz** [comment]
thank you.

**Comment by guineveresaenger** [comment]
@minherz - welcome to the community! We hope you stick around and help us contribute!

I'm glad you got your question answered and wanted to mention that because Kubernetes is a pretty large project, we generally do not use Github for troubleshooting kinds of questions. We prefer that you [use Slack or Stackoverflow for that](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/#help-my-question-isn-t-covered-i-need-help-now).

The use of "help wanted" and especially "good-first-issue" labels are quite different in intent and their use is described [here](https://git.k8s.io/community/contributors/devel/help-wanted.md). I can see how the labels can be confusing - I will address this in the next contributor experience meeting.

Thank you @fejta. :)

**Comment by minherz** [comment]
@guineveresaenger I tried in `#sig-testing` community but people there discussed their own business and then i saw the link in the notification message. Next time I will not use this place for questions. I think that the documentation has to be edited to provide more guidelines about a way to interpret such test results. In opposite to "older" test outputs, bazel build isn't easy for understanding.

**Comment by guineveresaenger** [comment]
@minherz I hear you on that 100%! We have an [open issue](https://github.com/kubernetes/community/issues/1537) over in k/community on more pointers for debugging tests. It's been open for a while but I will make sure it gets included in the final publicized version of contrib guide 1.0. Yours is a good example use case on why we need this.

**Comment by minherz** [comment]
:) I can contribute to writing some. Let me know.
