### ISSUE TITLE
latest kubekins image uses wrong e2e binary for skewed tests

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8375]
https://github.com/kubernetes/kubernetes/issues/65129#issuecomment-397650527

the image is reverted for now, but we still need to find out the underlying issue.

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/3088/build-log.txt is green and uses e2e binary from 1.10

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/3089/build-log.txt is bad and uses e2e binary from master

/area kubetest
/assign
/assign @BenTheElder 

cc @liggitt @AishSundar @dims @justinsb

**Comment by BenTheElder** [comment]
this should be fixed by https://github.com/kubernetes/test-infra/pull/8376
/close
