### ISSUE TITLE
Page test-infra oncall (or buildcop) when kubernetes-build has not run in N hours and the last build was a failure

### ISSUE THREAD

**Issue by mml** [kubernetes/test-infra#840]
In this state, nothing will be merged automatically and the build will not be run again unless something is manually merged.

If the failed build is a flake (https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-build/12935/ might have been), then someone should kick it.

This should be a business-hours-only kind of page.

@spxtr

**Comment by fejta** [comment]
/assign @michelle192837 
/area testgrid

Won't testgrid have this ability in the near future? If so we should doc that and resolve this.

**Comment by spiffxp** [comment]
/close

we have e-mail based alerting https://github.com/kubernetes/test-infra/tree/master/testgrid/config#email-alerts

we're using it for presubmits at the moment

build-cop role is being retired https://groups.google.com/forum/#!topic/kubernetes-dev/7ItITLWsfNM
