### ISSUE TITLE
Some test jobs keep running on stale commit

### ISSUE THREAD

**Issue by MaciekPytel** [kubernetes/test-infra#8409]
gci-, gke- and kops-aws jobs on release-1.10 keep running on a21d351a9, even though 32ac1c9 was merged 23h ago. Other jobs (bazel, kubeadm) have picked up new commit as expected.

Links:
* Still running on old commit:
https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#gci-gce-1.10
https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#kops-aws-1.10
* Running on new commit as expected:
https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#periodic-bazel-test-1.10
https://k8s-testgrid.appspot.com/sig-release-1.10-blocking#ci-gce-kubeadm-1.10

Note: this is blocking 1.10.5 patch release.

**Comment by krzyzacy** [comment]
hummmm https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-stable1/5572 timed out

**Comment by krzyzacy** [comment]
ok it pushed the build, but tanked before updating the file pointer :-(
/assign

**Comment by krzyzacy** [comment]
let's bump the timeout a little bit, runs like https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-stable1/5347/ does took ~2h to finish :-(

**Comment by krzyzacy** [comment]
retriggered https://prow.k8s.io/log?job=ci-kubernetes-build-stable1&id=5616, CI should pick up the build after that run finishes

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable1-default/2635 picks up from latest commit-sha now, closing
