### ISSUE TITLE
Allow users to add labels to things from gubernator

### ISSUE THREAD

**Issue by rmmh** [kubernetes/test-infra#842]
Which will allow us to have more fine grained ACL.

Possibly including an lgtm button.

(from kubernetes/kubernetes#34870)

**Comment by rmmh** [comment]
@mikedanese can you expand on this? What do you want to label-- pr's assigned to yourself? Arbitrary issues?

**Comment by spxtr** [comment]
I think the idea is that we want to let people LGTM PRs that are assigned to them without giving them full write access to the repo. Gubernator would validate that they can LGTM the PR somehow, then use `k8s-merge-robot`'s API token to add the label, or something like that.

**Comment by mikedanese** [comment]
* all users should be able to add release note labels to PRs that they created.
* some users (acl label manipulator) should be able to add all labels to anything except maybe lgtm

cc @pipejakob

**Comment by rmmh** [comment]
If k8s-bot had fast (push-based) responses to commands, would you prefer a `/relnote none` (or equivalent) command?

**Comment by mikedanese** [comment]
Yes, maybe. That makes it easy to see who made the modification.

**Comment by spxtr** [comment]
It's probably worth considering adding this functionality to prow rather than gubernator.

**Comment by spxtr** [comment]
I think we're doing it from prow these days, plus the mungebot has gotten a lot faster.
