### ISSUE TITLE
Consider boskos project loaning wrapper utility

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8427]
/area boskos
/area prow

cc @sebastienvas @BenTheElder @cjwagner @stevekuznetsov 

@davidz627 has a need to load project to run some non-k8s test, and use kubetest for that is super painful, so I suggest him to use boskos client library instead. @BenTheElder talked that we might want have some wrapper tool to handle resource loaning instead of kubetest.

**Comment by BenTheElder** [comment]
yeah something like `gcplease $ACTUAL_TEST_COMMAND`
- requests a project from boskos
- makes it the default in gcloud
- heartbeats while running $ACTUAL_TEST_COMMAND

**Comment by stevekuznetsov** [comment]
Wrap test-command or just another sidecar?

**Comment by stevekuznetsov** [comment]
I'm for a utility that does the lease for you, 100%

**Comment by krzyzacy** [comment]
I think this is specific to k8s testing, we can build it into our runner, or a pre-kubetest layer when we bikeshed kubetest and scenarios.

**Comment by BenTheElder** [comment]
I think just a test-command wrapper makes sense.

entrypoint -> gcplease -> test commnand

**Comment by stevekuznetsov** [comment]
@fejta wants to kill off the wrapper entirely -- how does that fit in here?

**Comment by BenTheElder** [comment]
If we kipped of `entrypoint` the binary then project leasing tool could be invoked in `ENTRYPOINT` proper in e2e testing images.

**Comment by BenTheElder** [comment]
we haven't needed it. we can always reopen someday if we need it. xref #4824
