### ISSUE TITLE
prow with gitlab

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/test-infra#8435]
prow binding to gitlab rather then github would be useful.

Is anyone working on it?

**Comment by fejta** [comment]
No one is working on it.

The integrations with github are pretty deep.

The most likely path forward on this would be to create some sort of github->gitlab translator service that sits in between prow and gitlab. So prow talks github to the service, which then translates the request into something it sends gitlab. Gitlab then talks back to the service, which it translated into a github request and sent back to prow.

**Comment by kargakis** [comment]
> The most likely path forward on this would be to create some sort of github->gitlab translator service that sits in between prow and gitlab. So prow talks github to the service, which then translates the request into something it sends gitlab. Gitlab then talks back to the service, which it translated into a github request and sent back to prow.

What happens when there is something supported by gitlab but not github?

How is the work with splitting the reporters out of plank going on @krzyzacy ? If we have that in place then all you would need is to create a gitlab version of `hook` and a gitlab reporter that reports job statuses back to gitlab.

/area prow
/kind feature

**Comment by krzyzacy** [comment]
yeah I plan to sort out gerrit implementation first, and we can design out for other platforms

**Comment by fejta** [comment]
Every plugin assumes GitHub, not just reporting job status.

**Comment by kargakis** [comment]
All plugins are either in hook or hook is configured to demux to them.
That's why I think a separate hook impl for gitlab is required.

**Comment by RafalMaleska** [comment]
What is the status of this issue?

I was trying to use Lighthouse for Prow integration into Gitlab - it seams that it provides only basic prow functionality and requires JenkinsX installation.

Is there a RoadMap to develop Prow further to allow usage of Gitlab?
