### ISSUE TITLE
config updater reply formatting is broken

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#8439]
Example: https://github.com/openshift/release/pull/986#issuecomment-399630556

Should be:
  * `ci-operator-openshift-origin` configmap using the following files:
     - key `master.json` using file `ci-operator/config/openshift/origin/master.json`
  * `config` configmap using the following files:
    - key `config.yaml` using file `cluster/ci/config/prow/config.yaml`
  * `ci-operator-openshift-openshift-ansible` configmap using the following files:
    - key `master.json` using file `ci-operator/config/openshift/openshift-ansible/master.json`

/area prow
/kind bug

@stevekuznetsov @krzyzacy @cjwagner

**Comment by krzyzacy** [comment]
* foo
 - bar
