### ISSUE TITLE
Log collectors don't get logs from all masters

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/test-infra#845]
the *serial tests do things like kill the master and start a new one up, but the log collector at the end only seems to get logs from a single incarnation of the master. This is very problematic when trying to figure out if a flake is a release blocker or not.

**Comment by ixdy** [comment]
maybe call [`framework.Coredump`](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L4341) before killing the master?

**Comment by spxtr** [comment]
Will need to ensure that `log-dump.sh` doesn't clobber old logs when we do so.

**Comment by davidopp** [comment]
Can we get an assignee for this? It's very important for the reason @lavalamp mentioned above.

@kubernetes/sig-testing

**Comment by piosz** [comment]
Which particular test is this issue about? "reboot node ... "?

**Comment by lavalamp** [comment]
@piosz we don't know which test did this.

@fejta people keep getting this wrong and we always find this at the worst possible time. So I believe the testing infrastructure should really help us not get this wrong. That is why I filed this here.

**Comment by spxtr** [comment]
Which logs are deleted when the machines reboot?

**Comment by lavalamp** [comment]
I think the problem is that the machines are destroyed and don't come back,
new ones are created instead?

**Comment by fejta** [comment]
Update the function that deletes the master to collect logs. IMO this work does not require help from my team.

**Comment by spxtr** [comment]
This is pretty tricky. If a test just has a hard-coded `gcloud compute instances delete` or something then what can we do other than fix the test?

**Comment by lavalamp** [comment]
Right. @fejta, I can believe that fixing the tests is not part of your
mandate but can we at least get something to automatically fail tests when
authors fail to collect logs?

**Comment by fejta** [comment]
@lavalamp that seems heavy handed. How do we know if they fail to collect logs? And if we are smart enough to know that why not just collect the logs?

We already have a function to collect logs which Jeff mentioned earlier: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L4485

It looks like there are already methods to restart various services:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L3878

So it sounds like the request here is to put the coredump logic into the restart methods.

**Comment by lavalamp** [comment]
I don't know if that will take care of it or not. Do any of our tests shell
out to gcloud to do things? We have a lot of bash in random places. But I
will be happy with whatever I can get :)

I guess my point is just that this is a general problem and I don't trust
individual test authors to get it right (because historically, they have
not, and we never notice the absence until we *really* need to see some
logs), so we need to solve it at a level higher than individual test
authors.

**Comment by spxtr** [comment]
> Do any of our tests shell out to gcloud to do things?

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/restart.go#L165-L177 for example.

**Comment by fejta** [comment]
No progress here
