### ISSUE TITLE
Create prowjob admission controller

### ISSUE THREAD

**Issue by amwat** [kubernetes/test-infra#8468]
We should have some basic validator and/or invalid CRD rejector so that prow components like plank don't crash loop. Currently the `configAgent` heavily relies on specific `Spec` fields to exist; based on the CRD type.

/cc @BenTheElder @krzyzacy 

Was: Malformed CRDs shouldn't break prow.

**Comment by krzyzacy** [comment]
hummm, at `configAgent` stage the job is not a CRD yet

**Comment by krzyzacy** [comment]
though we have plan to move the configs to CRDs
/area prow

**Comment by BenTheElder** [comment]
Er in this case I believe it was an hand altered ProwJob CRD. The config agent should be pretty protected by our validation and we can easily update it to not panic and reject new bad configs during load, but ensuring the ProwJobs created by arbitrary tools / humans are valid without breaking any of the components is another thing entirely.

Not sure if we should at all, but I thought we should discuss @stevekuznetsov @cjwagner
IIRC we do have some native CRD validation now, but it can't quite cover everything since we essentially have a tagged union currently.

**Comment by stevekuznetsov** [comment]
Once we have autogenerated clients for the Prow CRDs I think this will be effectively fixed.

**Comment by kargakis** [comment]
> Er in this case I believe it was an hand altered ProwJob CRD. The config agent should be pretty protected by our validation and we can easily update it to not panic and reject new bad configs during load, but ensuring the ProwJobs created by arbitrary tools / humans are valid without breaking any of the components is another thing entirely.

Do you guys have enabled [CRD validation](https://github.com/kubernetes/test-infra/blob/87b5d963680a077339741464d9c36dbe1f36a1fd/prow/cluster/prowjob_customresourcedefinition.yaml#L13-L50)?

**Comment by kargakis** [comment]
> Er in this case I believe it was an hand altered ProwJob CRD. The config agent should be pretty protected by our validation and we can easily update it to not panic and reject new bad configs during load, but ensuring the ProwJobs created by arbitrary tools / humans are valid without breaking any of the components is another thing entirely.

Do you use [CRD validation](https://github.com/kubernetes/test-infra/blob/87b5d963680a077339741464d9c36dbe1f36a1fd/prow/cluster/prowjob_customresourcedefinition.yaml#L13-L50)?

**Comment by BenTheElder** [comment]
The validation we have is not sufficient. In this case some logging broke
on assuming that type Presubmit will have various spec ref fields.

**Comment by stevekuznetsov** [comment]
@deads2k is it possible at all to get CRD validation like you could for resources served with an aggregated api server?

**Comment by krzyzacy** [comment]
yeah we want to write some validator for that

/assign
/assign @cjwagner

**Comment by cjwagner** [comment]
We have a simple admission webhook handler here: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/build/admission.go
We should decouple it from the build controller making it a standalone Prow component, then add more validation checks.

**Comment by stevekuznetsov** [comment]
Also anyone hand-writing CRDs is doing a bad thing and we should minimize the amount of engineering effort we spend trying to support that. Just use `mkpj`.

**Comment by fejta** [comment]
This is mostly:
* Move https://github.com/kubernetes/test-infra/blob/master/prow/cmd/build/admission.go into its own package
* Add https://github.com/kubernetes/test-infra/blob/636984e3718736b55dd9feea716d0aa32e1520dc/prow/cmd/build/dev.yaml#L98-L119 into prow/cluster/
* Improve the experience of creating `caBundle`, `--tls-cert-file` and `tls-private-key`

**Comment by BenTheElder** [comment]
> Also anyone hand-writing CRDs is doing a bad thing and we should minimize the amount of engineering effort we spend trying to support that. Just use mkpj.

:-1: 
your CRD is bad and you should feel bad if I can't create it by hand :(

What actually happens usually is people hand edit the re-run link to try something

**Comment by stevekuznetsov** [comment]
I mean sure, but seems like a waste of time to me IMHO. Who writes YAML by hand? That's nuts. If someone feels this is more pressing than the other work we have, of course pick it up ...

**Comment by BenTheElder** [comment]
this issue isn't labeled priority/critical-urgent, we open issues for things we aspire to eventually fix as well :^)

**Comment by ccojocar** [comment]
@fejta I would be interested to move the admission webhook in a freestanding service. I'll prepare a PR in the next days. Do you have any additional considerations which I should take into account?

**Comment by stevekuznetsov** [comment]
Let's make sure we use the best practices from SIG api-machinery (libraries, etc) and document it for new users/setup
