### ISSUE TITLE
make sure build failures emit junit

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8471]
we can't leverage the excellent triage dashboard for things like "how many times have we hit a cache download timeout" since build failures leave behind no junit. we should fix this.

/cc @ixdy

**Comment by BenTheElder** [comment]
@rmmh any particular suggestions here? should we just wrap the test execution with a junit entry and shove the build log in if the build fails?

**Comment by rmmh** [comment]
The build log can be ridiculously huge, but if we could make a JUnit for specific bazel failures that would be good.

**Comment by rmmh** [comment]
Fixing Bazel to produce JUnit for these cases would also be useful.
