### ISSUE TITLE
How to run continuous testing of kubernetes on top of kubernetes

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#848]
Do you have any instructions for the community how they can run CI of kubernetes on top of kubernetes?

Ideally:

``` bash
kubectl apply -f k8s.io/ci-manifests/e2e-jenkins
kubectl apply -f k8s.io/ci-manifests/conformance-jenkins
```

What's the status of that?

**Comment by spxtr** [comment]
I'm working on it, but we're not quite to this point yet. What I have is under the `prow/` folder. Currently I listen for webhooks from GitHub and then trigger Jenkins builds based on those, but pretty soon we'll move the actual test running out of Jenkins and into kubernetes.

Building kubernetes currently requires docker, which means you have to map in the docker socket as a hostpath volume. Other than that, it should just work. To test kubernetes you can look at `jenkins/bootstrap.py`.

**Comment by spxtr** [comment]
Bazel runs nicely on kubernetes, and we build kubernetes on kubernetes with it.
