### ISSUE TITLE
Migrate jobs from prow/config.yaml to config/jobs/**/*.yaml

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8485]
Might write a helper script, but big things:
- generated jobs
- k-s/k jobs

/area jobs
/assign

**Comment by krzyzacy** [comment]
cc @BenTheElder

**Comment by stevekuznetsov** [comment]
@krzyzacy are you breaking this up into multiple pulls? Would be useful to track them here in a checklist

**Comment by krzyzacy** [comment]
@stevekuznetsov I'm sorta doing it sigs by sigs, I'll add a ref to this issue

**Comment by krzyzacy** [comment]
@BenTheElder how do we wanna split presubmits? per-sig, or per-branch under a different subdir? (or we should solve the root issue to make them easier to configure? :-) )

**Comment by krzyzacy** [comment]
also probably cc @spiffxp @fejta @cjwagner @stevekuznetsov ^^ any preferences

**Comment by BenTheElder** [comment]
`config/jobs/kubernetes/kubernetes/sig-foo-presubmits.yaml` ?

**Comment by krzyzacy** [comment]
I feel like it will be easier for us to configure if we do `config/jobs/kubernetes/kubernetes/release-1.x-presubmits.yaml`, since this will become a job for test-infra lead in release cycles...

**Comment by BenTheElder** [comment]
> I feel like it will be easier for us to configure if we do config/jobs/kubernetes/kubernetes/release-1.x-presubmits.yaml, since this will become a job for test-infra lead in release cycles...

Hmmm. I think these should be organized by sig still. We can grep for release-specific jobs or build some tooling to find them... other than when we go to set up a release these should be sorted by who owns them imho, and we should set up OWNERS

**Comment by spiffxp** [comment]
We don't have a `jobs/kubernetes/kubernetes` why would we start for presubmits?  eg: `jobs/kubernetes/sig-foo/kubernetes-presubmits.yaml`?

**Comment by krzyzacy** [comment]
yeah I'll put them into `kubernetes/sig-foo/sig-foo-presubmits.yaml`

**Comment by BenTheElder** [comment]
Hmm. Are sig-foo-presubmits only k/k? As long as they're seperate that's fine with me. I only said k/k in the path to avoid sig-foo-presubmits being a catch all across repos.

**Comment by krzyzacy** [comment]
yay
