### ISSUE TITLE
Pod (Utilities) racing

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#8509]
I'm pretty confident we've encountered a race in the Pod Utilities between `entrypoint` and `sidecar`.
Specifically, we saw a job whose test binary exited with status code 0, but was marked as a failure in `finished.json` because the sidecar failed to parse the marker file contents into an int (the marker file existed, but was empty). I think this is because we don't write the marker file atomically from `entrypoint` so `sidecar` is able to read the file contents before they are written.
Here is a demo:
https://play.golang.org/p/_XfPQLp42O-

The easiest way to get atomicity is probably to have `entrypoint` write to a temp file and then rename it to the marker file location.

/area prow
/kind bug
/cc @stevekuznetsov @kargakis 
cc @steuhs

**Comment by BenTheElder** [comment]
Also this is the best bug title so:
![image](https://user-images.githubusercontent.com/917931/42076978-2721349c-7b2c-11e8-9adb-3a27cc918ab8.png)

**Comment by BenTheElder** [comment]
should be fixed in #8510
/close
