### ISSUE TITLE
main.go:309: Something went wrong: encountered 1 errors

### ISSUE THREAD

**Issue by leeivan** [kubernetes/test-infra#8557]
**Command**:
`go run hack/e2e.go -- --test --provider=local`
**Output:**
```
2018/07/03 10:09:57 e2e.go:79: Calling kubetest --verbose-commands=true --test --provider=local...
2018/07/03 10:09:57 process.go:153: Running: ./hack/e2e-internal/e2e-status.sh
Local doesn't need special preparations for e2e tests
error: server version (&version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}) differs from client version (version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.1729+36815869ad0a4c", GitCommit:"36815869ad0a4c2c5b8e1104fe2b0c0d4db8e7a6", GitTreeState:"clean", BuildDate:"2018-07-03T06:10:30Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"})!
2018/07/03 10:09:57 process.go:155: Step './hack/e2e-internal/e2e-status.sh' finished in 99.655296ms
2018/07/03 10:09:57 main.go:309: Something went wrong: encountered 1 errors: [error during ./hack/e2e-internal/e2e-status.sh: exit status 1]
2018/07/03 10:09:57 e2e.go:81: err: exit status 1
exit status 1
```
**Local kubernetes configuration:**
```
kubectl get nodes
NAME       STATUS    ROLES     AGE       VERSION
master01   Ready     master    45m       v1.11.0
node01     Ready     <none>    30m       v1.11.0
node02     Ready     <none>    29m       v1.11.0
node03     Ready     <none>    29m       v1.11.0
node04     Ready     <none>    28m       v1.11.0
node05     Ready     <none>    27m       v1.11.0
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by leeivan** [comment]
with --check_version_skew=false to avoid comparison of version.

**Comment by OlegLoewen** [comment]
Hi @leeivan 
if I try the tag you proposed: 
`go run hack/e2e.go -- --provider=skeleton --test --check_version_skew=false --test_args="--ginkgo.dryRun=true --ginkgo.flakeAttempts=1"`
I get the following error:

> 2019/05/17 15:43:04 e2e.go:79: Calling kubetest --verbose-commands=true --provider=skeleton --check_version_skew=false --test_args=--ginkgo.dryRun=true --ginkgo.flakeAttempts=1  --dump=/Users/d061705/go/src/k8s-e2e-test/artifacts/1558092339...
> 2019/05/17 15:43:04 main.go:281: Flag parse failed: unknown flag: --check_version_skew
> 2019/05/17 15:43:04 e2e.go:81: err: exit status 1
> exit status 1

Do you have an idea, what I'm missing?

**Comment by OlegLoewen** [comment]
Okay, with check-version-skew it's now working.

**Comment by chenpfeisoo** [comment]
`kubetest --provider=skeleton --test --test_args="--host=https://XXXX --ginkgo.focus=\[Serial\].*\[Conformance\]"  --check-version-skew=false`
I get the following error:

**Comment by chenpfeisoo** [comment]
If you are running from a binary release tarball, something is wrong. 
Look at http://kubernetes.io/ for information on how to contact the 
development team for help.
2020/05/11 15:36:09 process.go:155: Step './hack/e2e-internal/e2e-status.sh' finished in 34.074144ms
2020/05/11 15:36:09 main.go:312: Something went wrong: encountered 1 errors: [error during ./hack/e2e-internal/e2e-status.sh: exit status 1]
