### ISSUE TITLE
Pushgateway serves metrics for dead instances forever.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#8567]
The pushgateway doesn't work particularly well with gauges that are provided by kubernetes deployments because the `instance` field (the pod name) changes whenever the pod restarts, but old metrics for completed pods are never pruned and are continually scraped by upstream.
This is problematic because prometheus doesn't attack timestamps when serving metrics so all instances are considered to be equally 'recent' and we can't easily tell which instance is the current instance.

I think our best bet might be to use something like: https://github.com/Haufe-Lexware/pushgateway-pruner#pushgateway-grouping-pruner

/area prow
/kind bug
/cc @BenTheElder @rmmh @fejta @krzyzacy

**Comment by BenTheElder** [comment]
Attack? 🙃
/me envisions a Prometheus pod viciously deleting timestamps from logs

**Comment by cjwagner** [comment]
Well it doesn't attack timestamps either, but I meant to say 'attach' 😛

**Comment by stevekuznetsov** [comment]
@smarterclayton did we have a solution for this at a higher level? Do we have similar issues on `DeploymentConfig`?

**Comment by smarterclayton** [comment]
Generally we don't use the push gateway and just report from the process, letting it scrape continuously and reporting metrics on current state from a cache (that's how kube-state-metrics performs a similar reporting action).

**Comment by cjwagner** [comment]
This will become more of an issue now that we are redeploying more often. 

/reopen
/remove-lifecycle rotten

**Comment by cjwagner** [comment]
Annnnnnnd now it is biting us.
Velodrome is failing to render graphs with "Request Failed" errors now (almost certainly timeouts). e.g. http://velodrome.k8s.io/dashboard/db/monitoring?orgId=1

**Comment by stevekuznetsov** [comment]
We should rename this issue to "Prow misuses the pushgateway" -- we should be fine to not use it all
