### ISSUE TITLE
configure prow github integration details

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8574]
- add oauth app details
- add an icon so we don't get a github equivilant of a "new user" icon.

https://github.com/kubernetes/test-infra/pull/8572#issuecomment-402343451

current look:
<img width="1627" alt="screen shot 2018-07-03 at 7 17 14 pm" src="https://user-images.githubusercontent.com/917931/42253419-9a7e81f6-7ef6-11e8-819c-50e0cf99adc7.png">

/area prow
/kind cleanup
/assign @cjwagner @krzyzacy @bentheelder
hopefully one of us can get around to reconfiguring this, we don't need to do much but especially after #8572 we should fill out the oauth app details a little more... right now it looks a bit sketchy even if it only asks for public data.

**Comment by rmmh** [comment]
It should definitely have the Prow logo somewhere. I think @qhuynh96 might be the one that created the OAuth App?

**Comment by qhuynh96** [comment]
The OAuth App ownership is transferred to k8s robot.

**Comment by BenTheElder** [comment]
it now looks like: 
![image](https://user-images.githubusercontent.com/917931/42397036-2957a80c-8119-11e8-8716-26c51a9c48e3.png)

unfortunately I think the description is only surfaced when you're managing your authorized apps, not when authorizing.
