### ISSUE TITLE
Many job actions still done using VM service account

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/test-infra#858]
c.f. https://github.com/kubernetes/kops/issues/664#issuecomment-254347125 .

I'm going to submit a point-fix for `kops-build`, but I can say that `kubernetes-build` is similarly broken, as is the `gcs-uploader` step and several other things. It's a problem that `activate-gce-service-account` hits a file in `$WORKSPACE`, but that config is only selected if you export `CLOUDSDK_CONFIG` correctly.

**Comment by zmerlynn** [comment]
cc @kubernetes/test-infra-maintainers

**Comment by rmmh** [comment]
I think @fejta's bootstrap.py will help fix this, because it eliminates the separate steps/shells that were causing many of the issues.

**Comment by zmerlynn** [comment]
I agree, but it's not there yet.

**Comment by spxtr** [comment]
Once this is fixed we can get rid of `clean_metadata.py`.

**Comment by krzyzacy** [comment]
@fejta done?

**Comment by fejta** [comment]
I believe this is fixed...

**Comment by ixdy** [comment]
Builds too? Are they using bootstrap yet?

**Comment by ixdy** [comment]
ah, looks like it. nice.
