### ISSUE TITLE
Split job configs based on SIGs

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#8594]
IMO it's easier to maintain and keep track of jobs if we can split them into different files instead of having a huge monolithic config.json file (personally I find it painful to edit/review it now). It'll also help manage approvers/reviewers more granularly

@AishSundar @krzyzacy @BenTheElder - Wdyt?

**Comment by BenTheElder** [comment]
This is already a work in progress. `configs/jobs/*`
config.json will be inlined into each ProwJob, and the prowjob will be split into many files.
xref: https://github.com/kubernetes/test-infra/issues/4794
@krzyzacy is working on this.

**Comment by krzyzacy** [comment]
yeah, see https://github.com/kubernetes/test-infra/issues/8485

@shyamjvs feel free to migrate all the scalability jobs, you can also inline config.json now, take https://github.com/kubernetes/test-infra/blob/master/config/jobs/gke/gke-staging.yaml as an reference

**Comment by krzyzacy** [comment]
fyi, I'm slowly populating https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes

**Comment by shyamjvs** [comment]
/unassign
/assign @krzyzacy 
Who has been working on this.
