### ISSUE TITLE
Write handlePR unit tests for trigger plugin

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#8602]
We have a bunch of great `TestHandleIssueComment` unit tests that validate that when someone creates a comment we do/do not start testing as appropriate:

https://github.com/kubernetes/test-infra/blob/46985131df79c502444e909756b012bc4b533760/prow/plugins/trigger/ic_test.go#L39-L55

which eventually calls this in `handleIC` in `ic.go`:

https://github.com/kubernetes/test-infra/blob/46985131df79c502444e909756b012bc4b533760/prow/plugins/trigger/ic.go#L31-L37

We have similar `handlePR` functionality in `pr.go`:

https://github.com/kubernetes/test-infra/blob/46985131df79c502444e909756b012bc4b533760/prow/plugins/trigger/pr.go#L33-L40

But `handlePR` has no corresponding unit tests yet (noticed by cjwagner). We should add this

/good-first-issue

Validate things by running `bazel test //prow/plugins/trigger/...` [getting started](https://docs.bazel.build/versions/master/getting-started.html) (or just use standard `go test blah`)

**Comment by aojea** [comment]
@fejta I was playing around with the code and I think that with a little help I will be able to do it, can you assign it to me?

**Comment by aojea** [comment]
@fejta can this issue be closed?

**Comment by spiffxp** [comment]
/close
I was able to run unit tests with coverage, and it looks like we have 84% line coverage for pr.go now.  There are a few `if err != nil` checks that aren't covered, but I think this is good enough to close.

**Comment by spiffxp** [comment]
Thanks for the help @aojea 🙇
