### ISSUE TITLE
trusted_org not working in trigger

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8613]
https://github.com/kubernetes-sigs/poseidon/pull/124#issuecomment-403383421

`kubernetes` should be a trusted org for `kubernetes-sigs`:

https://github.com/kubernetes/test-infra/blob/7109caeb16c79b1349a2e45ef6bf80453e11b920/prow/plugins.yaml#L5-L12

Yet when a Kubernetes member tries to trigger testing, they get a comment like:

> @m1093782566: you can't request testing unless you are a kubernetes-sigs member.

/kind bug
/area prow
/assign @cjwagner @fejta

**Comment by fejta** [comment]
Intersting, maybe my trigger changes will fix this?

**Comment by BenTheElder** [comment]
actually looking at it I only see a `trusted_org: kubernetes` for the section below. these should probably have that as well...

**Comment by fejta** [comment]
Thanks for fixing my regression in the config!
