### ISSUE TITLE
Latest Tide does not merge PRs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8618]
rolled back to `v20180627-ea5075d37` for now

/area prow
/assign @cjwagner

**Comment by stevekuznetsov** [comment]
@krzyzacy can you give more information please

**Comment by krzyzacy** [comment]
https://kubernetes.slack.com/archives/C7J9RP96G/p1531159143000061

it stays like
```
{"base-sha":"51f0f8f9dc6804f414b5cccece8860d6dbccbc26","batch-passing":null,"batch-pending":null,"branch":"master","component":"tide","controller":"sync","level":"info","msg":"Subpool accumulated.","org":"kubernetes","prs-missing":[8607],"prs-passing":[8617,8616,8608],"prs-pending":null,"repo":"test-infra","time":"2018-07-09T17:59:17Z"}
```

**Comment by stevekuznetsov** [comment]
We are seeing the same issue on our `tide`, which deployed from 381ecf20efac306cca340ce607c7a294c0b1695e.

Here's a log dump from before I rolled it back: https://gist.githubusercontent.com/stevekuznetsov/b3fcbdbc7b1bb4913f6c73ca0804bee6/raw/de8a0a6153e359af708a547b7321e51957498626/tide-log.txt

**Comment by stevekuznetsov** [comment]
Likely related to https://github.com/kubernetes/test-infra/pull/8550

**Comment by stevekuznetsov** [comment]
Should be easier to debug with #8634
