### ISSUE TITLE
Special approval for feature branch

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#8622]
Feature branches might have a different approval mechanism than master, as in every time you want to merge something, it shouldn't be required to ask top level approvers. One could add themselves as a top-level approver specifically in the branch (though you'll require top-level approval to merge that PR).

**Comment by BenTheElder** [comment]
/cc @cjwagner @stevekuznetsov 

One workaround we discussed for now is just getting a top level approver to approve a temporary approve in the feature branch, merge that, and then be top level in that branch... but that's sorta ugly and requires looping in an approve for each, as well as reverting the change before trying to merge the completed feature into the "real" branch..

**Comment by stevekuznetsov** [comment]
/area prow/hook

What's the general flow for feature branches? Branch off of master, then sync by merging master in a number of times (or rebasing?) then publish by merging back into master? Won't the approver revert just have to happen once at the very end of the cycle? That seems to be a low-effort high-output result

**Comment by BenTheElder** [comment]
See also the CLA issue, we can't fix that one as the CLA bot isn't ours (also which branches should it ignore? this seems bad). Someone with access to push to that branch can handle the rebase pushes or PRS

**Comment by stevekuznetsov** [comment]
Wait, we don't want to require CLA for feature branches?

**Comment by BenTheElder** [comment]
we do, but if you force push a rebased branch you can get back in sync with master, which is what the "branch maintainers" do for release branches, and also for ""feature branch managers""

**Comment by stevekuznetsov** [comment]
OK, so the larger issue is that rebasing continuously on `master` will create merge conflicts on the top-level `OWNERS`?

**Comment by BenTheElder** [comment]
Well I think also that if you're person A and you just want to do a PR that updates all the commits to be back in sync with master, the CLA won't match and the bot won't let you merge it via the normal PR process, so you actually _need_ someone to just force push an updated branch (If I remember correctly...)
