### ISSUE TITLE
assign plugin regression when a user is invalid

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8639]
- it no longer succeeds at assigning any of the users
- it no longer posts a comment regarding this

xref: https://github.com/kubernetes/test-infra/pull/8637#issuecomment-403978413

/area prow
/kind bug
/cc @cjwagner @stevekuznetsov

**Comment by BenTheElder** [comment]
I suspect something in https://github.com/kubernetes/test-infra/pull/8443 since it's the only change to that plugin newer than like 5 months. :thinking:

**Comment by krzyzacy** [comment]
ok the issue is... @robot is... not a user, but a github group...

/shrug

**Comment by cjwagner** [comment]
It is unclear to me if this is a good first issue if the problem is that GitHub is not returning an error when it should be. Do we have a clear solution to provide a new contributor here?

**Comment by wbrefvem** [comment]
Hey all, I'm interested in getting involved and wouldn't mind taking a crack at this if no one else is working on it. I've had a look at the assign code and have a rough guess at where the gremlins may be lurking.

**Comment by cjwagner** [comment]
No one is working on this currently, but we don't have a clear solution given that
> assigning with a user + github org seems to silently fail from the github users's POV.

If this failure is actually completely hidden by the API, then there may not be a work around that is suitable for Prow and the bug should be reported to GitHub support. If there is a way to detect this error case then we can update Prow to handle it (and maybe still report this to GitHub support).

We should agree on a solution before starting to write code.

**Comment by wbrefvem** [comment]
Hmm okay, @cjwagner  I see your point. This is a sticky wicket. It seems there's a spam filter that just 404's the whole request if you try to assign an org. It doesn't seem to filter out random other junk, like invalid users, emojis, etc.

We could retry using the [List assignees](https://developer.github.com/v3/issues/assignees/#list-assignees) endpoint, then compare that list against the list of users we're attempting to assign. This would mean a best case of 3 round trips to assign the users if there's an invalid name in the list, but best case of 1 without one. If we do the check before the initial request, that's a best case of 2 round trips regardless. 

Thoughts?

**Comment by nikhita** [comment]
Removing good first issue and help wanted until consensus on how to proceed with this is reached.

/remove-help
