### ISSUE TITLE
Handle empty state in prowjobs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#8645]
Prowjob controllers should be able to handle prowjobs that do not specify any state (by defaulting to `triggered`). Eventually this should happen in the API but I am not sure about CRD defaulting 

cc @sttts @nikhita

**Comment by nikhita** [comment]
>  Eventually this should happen in the API but I am not sure about CRD defaulting

Defaulting is currently not possible directly via the CRD (scheduled for 1.12).

**Comment by stevekuznetsov** [comment]
How did that happen?

**Comment by stevekuznetsov** [comment]
We should be able to better enforce it when we generate the CRD client too

**Comment by kargakis** [comment]
I handcrafted a prowjob because there is no good way to rerun postsubmits which is probably a separate issue.

**Comment by kargakis** [comment]
> there is no good way to rerun postsubmits which is probably a separate issue.

Postsubmits that have been garbage collected.

**Comment by stevekuznetsov** [comment]
Can't you `mkpj` with the correct refs? But yes re: this issue -- should be defaulted

**Comment by kargakis** [comment]
Doh, I totally forgot about `mkpj`.

**Comment by stevekuznetsov** [comment]
You wrote it ... :rofl:

**Comment by kargakis** [comment]
I think it's fine tabling this until we have CRD defaulting.

**Comment by spiffxp** [comment]
/milestone clear
Punted because it's unclear to me whether this is still a priority for the v1.13 release cycle
