### ISSUE TITLE
adding /label prefixes should be possible via config

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8648]
xref: https://github.com/kubernetes/test-infra/pull/8647#pullrequestreview-136408737

/area prow
/kind enhancement

/cc @cjwagner @stevekuznetsov

**Comment by Rustin-Liu** [comment]
@BenTheElder  I want to working on this. Could you please reopen this issue?

**Comment by BenTheElder** [comment]
@Rustin-Liu I will reopen it but it doesn't have to be open to send a PR
/reopen

**Comment by hi-rustin** [comment]
>  I will reopen it but it doesn't have to be open to send a PR

@BenTheElder 
It seems that the previous pr was closed because of a broken change to config. Do you have any suggestions for implementing this?

**Comment by BenTheElder** [comment]
I don't have context on this anymore. I think a lot has changed in two years.

@cjwager or @alvaroaleman would know the current state.
