### ISSUE TITLE
Automate Management of Organization Ownership and ACL Assignment

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#8649]
We need a tool that automates the members of organizations and teams, as well as permissions for those members and teams.

 - [x] https://github.com/kubernetes/test-infra/pull/7966 Add org configuration skeleton
 - [x] https://github.com/kubernetes/test-infra/pull/8187 Extend peribolos to manage org memberships
 - [x] https://github.com/kubernetes/test-infra/pull/8311 Support managing github teams via config
 - [x] https://github.com/kubernetes/test-infra/pull/8417 Extend peribolos to configure org metadata
 - [x] https://github.com/kubernetes/test-infra/pull/8436 Apply maximumRemovalDelta to team deletion
 - [x] https://github.com/kubernetes/test-infra/pull/8438 Add --dump=ORG option to peribolos
 - [x] https://github.com/kubernetes/test-infra/pull/8601 Improve peribolos around child teams, uppercase, invitations
 - [ ] ???
 - [ ] Roll out peribolos to kubernetes org

/area prow
/kind feature
/assign @fejta

**Comment by stevekuznetsov** [comment]
Tracking issue for the larger effort
/cc @cjwagner @BenTheElder @krzyzacy

**Comment by BenTheElder** [comment]
> Handle mixed-case GitHub usernames appropriately

This should be fixed in https://github.com/kubernetes/test-infra/pull/8601 which was merged (?)

**Comment by stevekuznetsov** [comment]
@fejta can you lay out what is left here? Just choosing somewhere to put the config and turning it on?

**Comment by stevekuznetsov** [comment]
ping @fejta @cblecker

**Comment by cblecker** [comment]
This is waiting on me to review https://github.com/kubernetes/org/pull/8

**Comment by spiffxp** [comment]
/milestone v1.13
We have rolled out peribolos-driven org membership, but have yet to move on to repo ACL's and teams

**Comment by fejta** [comment]
Done
