### ISSUE TITLE
Document Integration Points for Job Authors

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#8652]
As a job author, I want to have the integration points with Prow laid out for me so that I can appropriately write jobs. For instance, how do I write a job that:

 - simply runs a script in my repo? (pod-utils)
 - requires DinD?
 - uses cached build artifacts?

How do I integrate if I have:
 - a new cloud provider to add?
 - hardware I  want the jobs to run on?

When should I:
 - edit configuration in this repo?
 - set up my own plugins?
 - run my own instance of `prow`?

/kind documentation
/area prow
/cc @fejta @BenTheElder @krzyzacy @cjwagner

**Comment by MHBauer** [comment]
service-catalog is interested in this, and I think we can help out as new-users if that mindset is needed
/cc @carolynvs @jeremyrickard

**Comment by spiffxp** [comment]
/milestone clear
I decided to punt out of the next milestone because it's unclear what specifics we're now lacking here.  I leave it to @krzyzacy @cjwagner @stevekuznetsov to change my mind if there are specifics we want to work on this release cycle

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
It's still not clear to me what specifics are lacking here

https://github.com/kubernetes/test-infra/tree/master/config/jobs#job-cookbook

**Comment by cjwagner** [comment]
Prow (not ProwJob) integration points are described here: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_develop.md#prow-integration-points

How to configure new ProwJobs: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#how-to-configure-new-jobs

This section describes what jobs can expect from pod utilities: https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#what-the-test-container-can-expect

How to run jobs in separate build clusters: https://github.com/kubernetes/test-infra/blob/master/prow/scaling.md#separate-build-clusters

I think these docs plus Aaron's Job cookbook cover everything except using cached build artifacts?
