### ISSUE TITLE
`hack/update-generated-docs.sh` is not hermetic

### ISSUE THREAD

**Issue by apelisse** [kubernetes/test-infra#8659]
Related to https://github.com/kubernetes/kubernetes/pull/66098

When I run `hack/update-generated-docs.sh`, it lists all kubectl commands, including my personal plugins. Later, when `hack/verify-generated-docs.sh` runs in pre-submit, the list is obviously different.

/assign @ixdy

**Comment by ixdy** [comment]
/reopen

This would probably be good to fix still.
@apelisse Do you remember which docs in particular were non-hermetic?

**Comment by ixdy** [comment]
(this isn't really a test-infra issue though)

**Comment by apelisse** [comment]
I don't remember the specific details, but I had installed some kubectl plugin, and the doc generation script was also documenting the plugins I had installed, which led to a different result on the bot ...
