### ISSUE TITLE
Support sending emails in prow

### ISSUE THREAD

**Issue by kargakis** [kubernetes/test-infra#8668]
I know that this is supported in testgrid but we should consider supporting it in prow.

- [x] testgrid is not open-sourced
- [x] even if testgrid was open, we shouldn't force deployments to deploy testgrid just for emails (even though testgrid is likely to be used by everyone who is using prow in the event it's opensourced)

We use Jenkins heavily for receiving emails about failed jobs and we can't fully migrate to prow w/o this (otherwise it's going to be a big hit on our flows). 

Strawman implementation that does not require changes in the prowjob api:
* store emails in a prowjob label (`email-notify.prow.io`: `bob@company.com, alice@company.com`)
* write a controller that watches for state transitions to failed prowjobs labeled with `email-notify.prow.io`
* send those emails

/area prow
/kind feature

@stevekuznetsov @cjwagner @BenTheElder @krzyzacy @fejta

**Comment by stevekuznetsov** [comment]
Once we get generated CRD client this can be done entirely third-party if you want to use the labels

**Comment by kargakis** [comment]
> Once we get generated CRD client this can be done entirely third-party if you want to use the labels

Right, I would like to have such a controller checked in test-infra for deployments that want to use it, hence this issue.

**Comment by BenTheElder** [comment]
@krzyzacy this sounds at least tangential to a reporter controller.

having a separate controller handling this SGTM, but:
> store emails in a prowjob label (email-notify.prow.io: bob@company.com, alice@company.com)

I can see wanting to configure this on the jobs, but I don't think reading it from the CRDs is actually as good as reading it from the current config. If a job fails it should go to the currently configured emails, not what was configured on one of the jobs. I should be able to add/remove alert emails just in the config.

Also, with per-branch jobs, I'd rather not duplicate this if we can avoid it. What about having config for this component? If you look at the testgrid email config there are some useful features regarding EG how many failures should trigger an alert for a given job, which doesn't really make sense as an annotation anyhow.

**Comment by kargakis** [comment]
> I can see wanting to configure this on the jobs, but I don't think reading it from the CRDs is actually as good as reading it from the current config. If a job fails it should go to the currently configured emails, not what was configured on one of the jobs. I should be able to add/remove alert emails just in the config.

Prowjob labels are set in the config so it doesn't sound like this will buy us much? Most of our jobs are ~30m-1h long. 

> What about having config for this component?

I am fine with extra config fed into the controller, but for the MVP we probably don't need it and simply sending an email on every failure should suffice for most use cases.

**Comment by BenTheElder** [comment]
>  and simply sending an email on every failure should suffice for most use cases.

I strongly disagree with that. Jobs can fail for any number of reasons (something on the internet is down!) and prowjobs are supposed to be disposable...? An email after N failures where N >= 2 is far more useful, especially for say, presubmits.

**Comment by kargakis** [comment]
What does disposable mean in this context? We care mostly about receiving
emails for postsubmit jobs where it doesn't make sense to send an email
after N failures because supposedly we expect 0 failures.

**Comment by kargakis** [comment]
Also I don't think we would use email notifications for presubmits. The bot
is already too chatty about any failures.

**Comment by BenTheElder** [comment]
Except for postsubmits, jobs can be rerun again and an individual run can be lost etc.. they're more like a deployment than a pod.

Email for postsubmits sounds fine for an MVP but kubernetes at least can't and won't use that if that's all it can do. We mostly favor periodic and Presubmit and for those we really need "after N failures" with the alerting decoupled from the specific prowjob instantiation. I'd request if at all possible that we start with that decoupling so we can expand it to support this in the future without rewriting everything but the email code.

this has the side benefit of letting you define the email config once for branch sharded jobs

**Comment by BenTheElder** [comment]
> Also I don't think we would use email notifications for presubmits. The bot
is already too chatty about any failures. 

If a job is repeatedly failing, even in Presubmit, that's something we should alert on... The threshold is just higher.

**Comment by kargakis** [comment]
Keeping the controller extensible to allow more options in the future is
definitely something we want, I just wouldn't block on matching all
testgrid email related-features from day one.

**Comment by BenTheElder** [comment]
Totally agree. Building it around annotations on the jobs will make other
alerting totally disjoint  in the future though, not just something
testgrid like.

I think at some point we can surpass parity by being aware of things like
which branch the job ran on. Simply rewriting testgrid alerting wouldn't
really helpful for kubernetes, though it might be for others.

**Comment by BenTheElder** [comment]
If we get email functionality working some other notifications might be candidates, like `needs-rebase`...

**Comment by stevekuznetsov** [comment]
If we get per-job metrics for success/failure can't we get Prometheus alerts if jobs fail?

**Comment by krzyzacy** [comment]
orthogonally: there's some linux kernal folks want to support prow + mailing lists and want to put a mail server on prow, maybe this can also be rolled under that. Will open an issue to discuss that soon.

**Comment by ixdy** [comment]
We might also want to think about how to support batching up job results. E.g. if I request a bunch of presubmit tests, should it send a bunch of emails? Or should it wait for all jobs to complete and then send one summary email?

**Comment by BenTheElder** [comment]
Sen and I sketched out batching for the gerrit integration, where it is
particularly necessary because comments aren't mutable (at least not to the
bot).

**Comment by AviKndr** [comment]
I can start working on this as it is needed for our linux kernel mailing list feature here #9905 if the details are agreed upon. I briefly discuss this in the design doc for that issue: [link](https://docs.google.com/document/d/1FdzEvyDh8KnyAxrizIBQRt1uSvW5DyxEV1WEduQ_VNo/edit?usp=sharing). From my understanding of prow and smtp, this can be a crier reporter and we can do dns lookup directly and send using net.SendEmail. To summarize what seems to be the consensus so far: 
- Configure email in the config
- Support batching up job results

Additionally, I am in favor of configuring the subject header line (and others) through annotations for each job as it is required for our use case.

**Comment by stevekuznetsov** [comment]
Would be cool to get failure notifications via Slack for jobs that we know should have 100% success rate (like branch protector, etc)
