### ISSUE TITLE
Jobs can be triggered with old config files

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8670]
https://github.com/kubernetes/test-infra/pull/8666#issuecomment-404641518

seems only happening with tide? Gonna :eyes: that.
/area prow
/assign
cc @BenTheElder @cjwagner @stevekuznetsov

**Comment by BenTheElder** [comment]
/shrug

don't run stale components with older config agents?

**Comment by krzyzacy** [comment]
yeah, should be fine with https://github.com/kubernetes/test-infra/pull/8684
