### ISSUE TITLE
prow: cherrypicker: allow enumerating branches in one comment

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#8691]
We need to support 

```
/cherrypick foo bar baz
```

/area prow
/kind feature
/cc @cjwagner @kargakis

**Comment by kargakis** [comment]
Or fix the following to work since I have seen folks using it and there are problems with overloading the command arguments (see comments in https://github.com/kubernetes/test-infra/issues/7587)
```
/cherrypick foo
/cherrypick bar
/cherrypick baz
```

**Comment by stevekuznetsov** [comment]
If the plugin can find all N `/cherrypick` commands in one comment, then we are OK I think. Still possible to reply with one comment. If we can do that for all of our plugins (in the framework? @cjwagner ) the UX can be better across the board
