### ISSUE TITLE
kubemark-pr project metadata was full of ssh-keys

### ISSUE THREAD

**Issue by gmarek** [kubernetes/test-infra#870]
I wasn't able to ssh to a machine to debug the problem. IIRC we do have jobs that periodically clean metadata of ssh-keys, can we enable it for kubemark-pr project as well?

cc @wojtek-t @kubernetes/test-infra-maintainers

**Comment by spxtr** [comment]
Which project? We can add a new line to https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/jenkins-clean-ssh-keys.yaml

**Comment by gmarek** [comment]
k8s-jkns-pr-kubemark

**Comment by gmarek** [comment]
I guess that all presubmit-projects needs that.
