### ISSUE TITLE
tide status page details do not handle org queries

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8731]
<img width="1561" alt="screen shot 2018-07-18 at 9 31 06 pm" src="https://user-images.githubusercontent.com/917931/42921675-ea2d2496-8ad1-11e8-9c1d-cfffee477046.png">

/kind bug
/area prow
/assign

**Comment by spiffxp** [comment]
/close
Orgs show up correctly in queries, not sure when this got fixed

![screen shot 2018-10-22 at 9 58 24 pm](https://user-images.githubusercontent.com/49258/47336703-a7235c00-d645-11e8-9d07-0d82fa4fbd51.png)

**Comment by cjwagner** [comment]
I fixed this [here](https://github.com/kubernetes/test-infra/commit/426ac78e1d80f485471e9754b26bad39a3f46ecd#diff-b5586164c9099ccebed5ac03f969a883), but apparently forgot to document it in the commit message or PR...
