### ISSUE TITLE
prow pr status script error

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8733]
```
pr-script.js:283 Uncaught TypeError: Cannot read property 'state' of undefined
    at getFullPRContext (pr-script.js:283)
    at loadPrStatus (pr-script.js:341)
    at redraw (pr-script.js:105)
    at createXMLHTTPRequest (pr-script.js:175)
    at XMLHttpRequest.request.onreadystatechange (pr-script.js:63)
```
surrounding snippet:
```js
    if (builds) {
        for (let build of builds) {
            let discrepancy = "Github context not found";
            // If Github context exits, check if mismatch or not.
            if (contextMap.has(build.context)) {
                const githubContext = contextMap[build.context];
                // TODO (qhuynh96): ProwJob's states and Github contexts states
                // are not equivalent in some states.
                if (githubContext.state === build.state) {
                    discrepancy = null;
                } else {
                    discrepancy = "Github context and Prow Job states mismatch";
                }
            }
```
283 is `if (githubContext.state === build.state) {`

/kind bug
/area prow
/cc @qhuynh96

**Comment by BenTheElder** [comment]
This happens on my PR status page currently, but not on https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Aqhuynh96

I also don't think we need the alert icon if the prowjob is not found actually @stevekuznetsov @qhuynh96, since eg cla/linuxfoundation never has a prowjob. we just need an alert if the prowjob _is_ found and doesn't match.

**Comment by qhuynh96** [comment]
it failed due to ```githubContext``` is ```undefined``` which should not happen because there is a test to check if context exists or not.

**Comment by stevekuznetsov** [comment]
> I also don't think we need the alert icon if the prowjob is not found actually @stevekuznetsov @qhuynh96, since eg cla/linuxfoundation never has a prowjob. we just need an alert if the prowjob is found and doesn't match.

agreed

**Comment by BenTheElder** [comment]
can confirm this fixes it, we might still want to deal with the mismatched states a bit more though:
![image](https://user-images.githubusercontent.com/917931/42962395-5fafc876-8b46-11e8-9ce4-037cab2d63fb.png)
"job triggered" is also a bit of a special case
