### ISSUE TITLE
prow: Github Review State not being handled as expected

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/test-infra#8735]
It appears as though "Approve" on a GitHub review still does not trigger lgtm, as observed on this comment in k/community:

https://github.com/kubernetes/community/pull/2347#issuecomment-406360573

I am willing to look into this, but I'm also looking for hints on debugging.

/kind bug
/sig test-infra

**Comment by stevekuznetsov** [comment]
Wait did we make approval via GitHub UI --> `/approve`? I thought we just made it so that if you `/lgtm` or `/approve` in the review comment it works.

**Comment by BenTheElder** [comment]
I'm not fully up to date on the expected behavior besides `/lgtm`, `/approve` in comments

**Comment by guineveresaenger** [comment]
I was trying to get GitHubReviewState to trigger LGTM as well, as in the Approve button. I have no idea what I missed. :/

**Comment by guineveresaenger** [comment]
it's in this PR: #6738

**Comment by stevekuznetsov** [comment]
Might need some cluster logs to debug? @fejta

**Comment by cjwagner** [comment]
`review_acts_as_approve` is not enabled for k/community:
https://github.com/kubernetes/test-infra/blob/bc41683931b30662b4774d0cc0b18495ddf730f5/prow/plugins.yaml#L34-L74

**Comment by spiffxp** [comment]
/close
closing as "works as intended" then, if there is a desire to change this behavior, that would be the file and change to PR
