### ISSUE TITLE
pr status page should handle certain statuses specially

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8737]
previous discussion: https://github.com/kubernetes/test-infra/issues/8733

/area prow

**Comment by qhuynh96** [comment]
@BenTheElder I just forgot the context of this issue. Can you help me jog my memory?

**Comment by BenTheElder** [comment]
I think maybe https://github.com/kubernetes/test-infra/issues/8733#issuecomment-406351585 + we were (are?) showing the alert icon for "job triggered" ?

**Comment by qhuynh96** [comment]
Not all "job triggered". We currently show alert icons for Prowjob that does match Github contexts only

**Comment by BenTheElder** [comment]
> Not all "job triggered". We currently show alert icons for Prowjob that does match Github contexts only

Yeah but in this case at least, that's not really alert worthy.
