### ISSUE TITLE
Rewrite prow in a better language

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#8742]
Golang doesn't have good support for dependencies, generics or generated code.

Therefore we should migrate prow to https://www.emojicode.org/ during the 1.13 timeframe

**Comment by ixdy** [comment]
Go already supports unicode identifiers.

**Comment by droslean** [comment]
We should re-write it in whitespace language.
https://en.wikipedia.org/wiki/Whitespace_(programming_language)

**Comment by ixdy** [comment]
Enhancement freeze starts tomorrow. Is this still likely to target 1.13?
