### ISSUE TITLE
Setup alerts when Kettle Job stops/fails to collect and push metrics to BigQuery

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/test-infra#8743]
Once in a while our Kettle job, which collect Bigquery metrics and feeds Velodrome, stop and we end up not having data for weeks before someone notices it. While we debug and fix the root cause, we should atleast setup alerts if the metrics data is stale (more than a day old?) so it get surfaced and fixed sooner than later.

/area metrics
/area velodrome
/milestone 1.12
/sig testing
/kind feature
/priority important-soon

**Comment by spiffxp** [comment]
We have http://velodrome.k8s.io/dashboard/db/bigquery-metrics?panelId=12&fullscreen&orgId=1 but it is unclear to me whether that is alerted on, and if so, to where
