### ISSUE TITLE
Prow Feature Request: Debug a failed/stuck test with SSH

### ISSUE THREAD

**Issue by duderino** [kubernetes/test-infra#8760]
It would be pure awesome if Prow supported something along these lines: 
 https://circleci.com/docs/2.0/ssh-access-jobs/

**Comment by BenTheElder** [comment]
hmm that feature does look neat on the surface but I kinda don't think we want to do this

Prow admins can already `kubectl exec` to a running job etc. without any extra tooling, but I don't think that's meant to be used at any sort of scale or exposed to arbitrary users... This would complicate resource management and security. With `/ok-to-test` we in theory at least require a trusted user to inspect and approve code from arbitrary users before we test it using our test code. With this we'd be _explicitly_ handing some users the keys to run arbitrary code un-audited.

Jobs should post enough debugging info in cold storage, and we should do a good job exposing and processing that. 

We also upload the job's PodSpec, so it's possible to execute it elsewhere and exec to that.

**Comment by BenTheElder** [comment]
I think we're likely to support this via `kubectl exec`, and without any new features to prow. cc @cjwagner 

- you can already rerun jobs if you have `kubectl` access to prow.
- you can already `kubectl exec --namespace=test-pods $POD_ID -- /bin/sh` to get a terminal inside of a job's pod for jobs on prow / plank. this is roughly equivilant to SSHing to a job. perhaps we could document this, but `kubectl exec` is a core kubernetes feature anyhow (?)
