### ISSUE TITLE
prow: Leaving /approve doesn't alter GitHub Review status

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#8795]
I'm not sure that it's pressing but it can be annoying

1. I leave a PR review with changes requested, so github's UI shows a little red x next to my name
2. The author provides the necessary changes
3. I then (regularly) comment `/lgtm /approve` and the `lgtm` and `approved` labels appear, but the UI still shows that I have changes requested

Basically, once I start using a PR Review, I'm locked into using it for further updates.  It'd be nice if prow could change my review status when I use `/lgtm` (and/or `/approve`? Maybe this should be configurable and I'm not sure what the right default would be right now)

**Comment by fejta** [comment]
Prow cannot leave an approving review on your behalf.

What you can do is this:

https://github.com/kubernetes/test-infra/blob/09591c7544f1eec1128815ceefa04dc3f4af915d/prow/plugins.yaml#L67-L70

**Comment by stevekuznetsov** [comment]
As @fejta points out this is impossible to implement unless we ask for everyone's token
/close
