### ISSUE TITLE
prow: trigger additional tests based on PR title / body / commit

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#8796]
/kind feature
/area prow

The desire is to have different sets of required tests depending on what kind of change is being submitted.  One way `trigger` supports this today is via the `run_if_changed` regex, which triggers a job if certain paths or files are part of the PR.  We also allow PR authors to comment `/test foo` to trigger a presubmit that prow already knows about (I'm not sure if this then sticks as a requirement for merge).

What if we allowed trigger to regex against the change description? For example some sort of keyword in the PR title, the PR description, or commit messages.  Supporting all of these seems messy, and adding/dropping requirements based on things that can be edited retroactively also seems prone to tricky corner cases.  We have prior art for acting on PR titles with the wip plugin, so I would probably start there

But the happy path would be for changes that have impact across packages, eg: changes mentioning performance would have an additional scalability test presubmit, etc.

**Comment by stevekuznetsov** [comment]
> (I'm not sure if this then sticks as a requirement for merge).

Looks like we decided stickiness from external state was not worth it from a token point of view: https://github.com/kubernetes/test-infra/issues/1351

> But the happy path would be for changes that have impact across packages, eg: changes mentioning performance would have an additional scalability test presubmit, etc.

How is this different from having groups of tests and asking the user to `/test performance`, for instance? Would we want to surprise a user who happens to mention a keyword?
