### ISSUE TITLE
K8s Prow favicon isn't displaying properly.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#8817]
![screenshot from 2018-07-24 15-21-18](https://user-images.githubusercontent.com/5334145/43169280-5b622a1c-8f55-11e8-9901-078bdf6be110.png)
The first tab is the k8s Prow instance https://prow.k8s.io
The second tab is openshift's Prow instance https://deck-ci.svc.ci.openshift.org/

When I force refresh the page I see the correct favicon for an instant before it is replaced with the default page icon.
Since OpenShift's favicon is working this is probably an issue with using the default favicon?

/kind bug
/area prow
/cc @matthyx @stevekuznetsov @kargakis @BenTheElder

**Comment by BenTheElder** [comment]
https://prow.k8s.io/favicon.ico is 404 despite the file still being in /static/ ...

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/blob/1645b53e4e8e7a09761ae1253e42b431b8341c28/prow/cmd/deck/main.go#L587-L591

that probably needs to be:
`if config.Deck.Branding != nil && config.Deck.Branding.Favicon != "" {`

**Comment by stevekuznetsov** [comment]
Maybe it's just that our prow > your prow and we need #8742  ?

**Comment by matthyx** [comment]
Yes, I didn't expect to have branding without favicon... I will test @BenTheElder patch.
/assign

**Comment by matthyx** [comment]
@BenTheElder has already proposed #8818

**Comment by spiffxp** [comment]
/close
I am no longer able to reproduce this.  Please /reopen if this is still an issue.
