### ISSUE TITLE
Identifying where ProwJob artifacts are uploaded

### ISSUE THREAD

**Issue by paulangton** [kubernetes/test-infra#8831]
Currently we generate Gubernator links from `job_url_template` in `config.yaml`. It is possible to parse these links and extract some upload information like Spyglass does (#8385), but it would be better to have some standardized metadata for extracting the artifact upload location of a ProwJob.

We could potentially create a new template for Spyglass links or attach artifact upload information directly to ProwJobs, I dont have a strong opinion, but there should be a better way than what we have. 

/area prow
/cc @stevekuznetsov @krzyzacy @BenTheElder @kargakis

**Comment by stevekuznetsov** [comment]
If we have access to the spec for the job, the pod utilities have helpers for the GCS paths:

https://github.com/kubernetes/test-infra/blob/795cceb4ce411fa43933fb6534c208a6d470e1ab/prow/pod-utils/gcs/target.go#L30-L44

**Comment by BenTheElder** [comment]
The generated URL somewhat fixes this, but not for non-pod-utils jobs, it's still marking the view upload location, not the actual GCS location.

**Comment by ibzib** [comment]
I ended up reverting the commit that "fixed" this, good catch
