### ISSUE TITLE
Improve test coverage of verify-owners

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#8838]
Suggested in #8806 
- add tests with patch to check review line number
- factor out the parse/generate `messageWithLine` logic and unit-test it

**Comment by kentakozuka** [comment]
Is it still open? I would like to work on it.

**Comment by kentakozuka** [comment]
Thanks! Can you tell me a bit about where exactly `parse/generate` is?

**Comment by matthyx** [comment]
Sure, but today I am just with my phone at a workshop... I will provide pointers tomorrow if needed :-)

**Comment by kentakozuka** [comment]
OK. Thanks :)

**Comment by matthyx** [comment]
Alright, so basically it's in prow/plugins/verify-owners/verify-owners.go:
- extract what's between line 126 and 161 in a method
- write some unit-tests for it

**Comment by kentakozuka** [comment]
👍 
I'll be working on it!

**Comment by tallclair** [comment]
Other tests that I would like to see:

- approver & reviewer assignments correspond to either an alias, or a github account
- if the assignment resolves to a github account, that account should be a member of the kubernetes org

**Comment by matthyx** [comment]
> Other tests that I would like to see:
> 
> * approver & reviewer assignments correspond to either an alias, or a github account
> * if the assignment resolves to a github account, that account should be a member of the kubernetes org

@tallclair currently the verify-owners only checks the format of the file, not the meaning of it...
@cjwagner @stevekuznetsov does it make sense to check that here?

**Comment by cjwagner** [comment]
Yeah, if we fetch the list of organization members/collaborators we can validate the entries against it without too much API token cost.
