### ISSUE TITLE
Improve error parsing in github client

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#8839]
Suggested in #8806 
Avoid this kind of unmarshalling error:
`json: cannot unmarshal string into Go struct field ClientError.errors of type struct { Resource string "json:\"resource\""; Field string "json:\"field\""; Code string "json:\"code\""; Message string "json:\"message,omitempty\"" }`

**Comment by spiffxp** [comment]
/close
closing since linked PR has merged, please /reopen if this was incorrect

**Comment by matthyx** [comment]
Here is for the record, the latest answer from GitHub (9/12/18):

> Hi Matthias,
Our apologies for the wait, and thank you for following up with us. Due to a high volume of requests, we are currently experiencing much longer than average response times here in Support.
I have a better understanding of what you're reporting now! We've asked the team to investigate this in an internal issue. We can't promise an ETA for when this will be addressed, but we'll write back as soon as there's any news.
All the best,
Francis

I will follow up on this until done, but the PR solved our issue.
