### ISSUE TITLE
prow: deck: expose currently configured jobs

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#8852]
It would be cool if you could use a page on `deck` to look at the jobs configured for your repo, listed by branch or similar. Pointing people into a config directory tree is sometimes less than ideal.

/area prow
/kind feature
/cc @cjwagner @fejta

**Comment by BenTheElder** [comment]
related: there's a config endpoint that serves the entire serialized config but:
- a) that's huge, so to do this we should finally add filtering params to the endpoint
- b) serialized / loaded config doesn't match on disk-config.

**Comment by stevekuznetsov** [comment]
> a) that's huge, so to do this we should finally add filtering params to the endpoint

Can we grab a YAML viewer and jam that in a front-end? :)

> b) serialized / loaded config doesn't match on disk-config.

Often the question is more to do with the jobs that are currently configured and running on a repo, for which we want to see what is loaded and not necessarily a broken on-disk config, so at least for the use cases I was thinking of this is OK.

**Comment by BenTheElder** [comment]
> Can we grab a YAML viewer and jam that in a front-end? :)

I mean ideally we don't ship bytes we aren't displaying...

> Often the question is more to do with the jobs that are currently configured and running on a repo, for which we want to see what is loaded and not necessarily a broken on-disk config, so at least for the use cases I was thinking of this is OK.

Probably so, but it does mean there will be a mismatch if you go to update the config. It would also be nice if we could tag jobs with their source file while I'm dreaming :-)

**Comment by cjwagner** [comment]
/remove-lifecycle stale
This would be neat to have. It would be helpful to be able to link to a job's config whenever we reference a job across Deck's pages. Non-unique job names might prevent that from working well though. That might be worth addressing first.
