### ISSUE TITLE
jobs: remove jobs that have been continuously failing for over N days 

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#8861]
I'm going to suggest N=120 for now.  I'd like to do this one more time as a human to learn what the right detection methods are for straight-up-failing vs. seriously flaky, how/when to reach people in case there are some brave souls out there who want to save these jobs, etc.

Next step would be to automate at least some portion of this.

ref: https://github.com/kubernetes/test-infra/issues/2528#issuecomment-392936145

**Comment by BenTheElder** [comment]
This is an excellent issue. 👌 
/woof

**Comment by dims** [comment]
`remove` means delete the job or just disable it? (leave it in the prow config, but disabled)

**Comment by BenTheElder** [comment]
I'd say remove from everything and use git history, or create a seperate dir for dead jobs. Trimming the config is also desirable, besides saving on runtime resources, and on testgrid at least it doesn't make sense to keep showing jobs we aren't running.

**Comment by spiffxp** [comment]
Horrible bash + jq to get me the list and links to testgrid
https://gist.github.com/spiffxp/1e3ff608a92e8bfc0091a0b2918a11c6

**Comment by spiffxp** [comment]
/milestone v1.13
/priority important-soon
/sig testing
~/kind purge~
/kind cleanup

**Comment by spiffxp** [comment]
/milestone v1.14

For reals this time.  Document and then enforce rules.

**Comment by stevekuznetsov** [comment]
The grinch is here!

**Comment by spiffxp** [comment]
/milestone v1.16
Many of the `cos` jobs that come from generate_tests may be able to be removed, although there is some question from @tpepper over whether those are legitimate failures

https://github.com/kubernetes/test-infra/issues/13353#issuecomment-509379536

**Comment by tpepper** [comment]
Following up, if these can be green, they provide useful signal.  Looking at the testgrid `cos` set of k8sbeta aka 1.15 things in particular in the hope that we might make things more green ahead of merging https://github.com/kubernetes/kubernetes/pull/80134 I see:

- cos-cos1-k8sbeta  (this is 1.15)
  - gce-cos1-k8sbeta-default
    - storage issue likely fixed by cherry pick of https://github.com/kubernetes/kubernetes/pull/78459
    - may still have an additional storage issue
    - (same as gce-cos2-k8sbeta-default below)
  - cos1-k8sbeta-serial
    - misc. timeouts/flakes
    - (maybe same as cos2-k8sbeta-serial below?)
  - gke-cos1-k8sbeta-alphafeatures
  - gke-cos1-k8sbeta-gpu
  - gke-cos1-k8sbeta-default
  - gke-cos1-k8sbeta-reboot
  - gke-cos1-k8sbeta-autoscaling
  - gke-cos1-k8sbeta-updown
  - gke-cos1-k8sbeta-serial
  - gke-cos1-k8sbeta-slow
    - ^^^ all showing GKE kube-apiserver endpoint unhealthy
  - gce-cos1-k8sbeta-slow
    - flex volume timeouts
    - (same as gce-cos2-k8sbeta-slow below)
  - cos1-k8sbeta-gkespec
    - before suite system validation fails misc kernel CONFIG_ checks
    - (same as cos2-k8sbeta-gkespec below)
  - gce-cos1-k8sbeta-serial
    - probably also https://github.com/kubernetes/kubernetes/pull/78459
  - gke-cos1-k8sbeta-flaky
    - named "flaky" but 100% fails to bring up a cluster, less clear logs
        than other cases
- cos-cos2-k8sbeta (this is 1.15)
  - gke-cos2-k8sbeta-slow
  - gke-cos2-k8sbeta-autoscaling
  - gke-cos2-k8sbeta-serial
  - gke-cos2-k8sbeta-reboot
  - gke-cos2-k8sbeta-updown
  - gke-cos2-k8sbeta-default
  - gke-cos2-k8sbeta-gpu
  - gke-cos2-k8sbeta-flakyA
  - gke-cos2-k8sbeta-alphafeatures
    - ^^^ all showing GCE error: "A Shielded VM Config cannot be set when using a source
        image that is not UEFI-compatible."
  - gce-cos2-k8sbeta-serial
    - "FailedMount: MountVolume.SetUp" timeout: multiple cloud provider
      specific issues in this area of code opened this spring.
  - gce-cos2-k8sbeta-default
    - storage issue likely fixed by cherry pick of https://github.com/kubernetes/kubernetes/pull/78459
    - may still have an additional storage issue
    - (same as gce-cos1-k8sbeta-default above)
  - cos2-k8sbeta-gkespec
    - before suite system validation fails misc kernel CONFIG_ checks
    - (same as cos1-k8sbeta-gkespec above)
  - cos2-k8sbeta-serial
    - misc. timeouts/flakes storage
    - (maybe same as cos1-k8sbeta-serial above?)
  - gce-cos2-k8sbeta-slow
    - flex volume timeouts
    - (same as gce-cos1-k8sbeta-slow above)

There's a relatively limited set of symptoms there...

**Comment by spiffxp** [comment]
I confirmed the cosN jobs aren't really relevant to the community, and there are equivalents running inside of google, so think we should remove them https://github.com/kubernetes/test-infra/pull/13913

**Comment by BenTheElder** [comment]
this probably should still be open?

**Comment by spiffxp** [comment]
Well, I managed to remove an N=923 job https://github.com/kubernetes/test-infra/pull/17156

**Comment by BenTheElder** [comment]
👏👏

**Comment by spiffxp** [comment]
/close
closing this in favor of https://github.com/kubernetes/test-infra/issues/18600
