### ISSUE TITLE
milestone-maintainer: allow kind/failing-test as one of the required labels

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#8887]
When updating release docs as part of https://github.com/kubernetes/community/issues/1579 we decided that kind/bug was no longer required for ci-signal filed issues.  It turns out we were wrong.  The milestone-maintainer munger expects one of kind/cleanup, kind/bug or kind/feature

The workaround would be to update docs and say kind/cleanup + kind/failing-test are required failing test issues.  This is weird though.  Let's just update the munger.

I'd rather the milestone-maintainer munger was no more, but I don't have time to port it over

Example of where this is being encountered: https://github.com/kubernetes/kubernetes/issues/66771

/area mungegithub
/milestone 1.12
/assign

**Comment by AishSundar** [comment]
+1 on doing (a). Since the CI Signal handbook explicitly says we need either kind/flake or kind/failing-test, we should be good. 

Can you let us know what are you planning update in the bug-triage and ephemera docs?

**Comment by spiffxp** [comment]
When I take a course of action I'll /hold PR's with links back to this issue, and wouldn't plan on merging docs PR's until the change had been deployed.

**Comment by tpepper** [comment]
I agree on (a) being the near term way to go.

**Comment by guineveresaenger** [comment]
Agreeing with everyone, I look forward to not seeing these show up on my bug list

**Comment by spiffxp** [comment]
a) is going to require a redeploy of mungegithub

I will wait until we have a chance to [discuss milestone-maintainer's future](https://github.com/kubernetes/sig-release/issues/243) at today's sig-release meeting before deploying

**Comment by spiffxp** [comment]
So rather than (a), I'm going to recommend the previously unseen door (e), which is: disable the milestone-maintainer munger entirely, after discussing at today's sig-release meeting 

https://github.com/kubernetes/sig-release/issues/243#issuecomment-409391292

This _also_ requires a redeploy of mungegithub, which isn't something I can do today.  Hopefully tomorrow.

**Comment by spiffxp** [comment]
/close
I changed my mind about keeping this open for docs fixes.  If there are bugs or new doc updates that need to happen, I'll look for separate issues.  We disabled milestone-maintainer earlier today https://github.com/kubernetes/test-infra/pull/8909
