### ISSUE TITLE
updateconfig should have a tool to force re-uploading the entire config

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8892]
I don't think we have this currently, this would help clean up after things like https://github.com/kubernetes/test-infra/issues/8891 where we did not update the config properly after https://github.com/kubernetes/test-infra/pull/888

**Comment by BenTheElder** [comment]
the job config configmap is large enough that this tool will need to delete and create it, it's larger than apply will allow

**Comment by krzyzacy** [comment]
/shrug
I'll write a hack script that can delete/recreate the entire configmap

**Comment by stevekuznetsov** [comment]
Yeah we have scripts to bootstrap stuff, but that is not ideal.

**Comment by krzyzacy** [comment]
probably won't have much free cycles on this this quarter for the proper implementation...

/help
/unassign

**Comment by stevekuznetsov** [comment]
/assign
This is really key for disaster recovery, too -.-

**Comment by BenTheElder** [comment]
we have a script now but it's not that great, in experiment/ iirc

**Comment by stevekuznetsov** [comment]
Yeah the script is not amazing

**Comment by stevekuznetsov** [comment]
We have `config-bootstrapper` now, this is done

/close
