### ISSUE TITLE
Spyglass needs to handle authenticated GCS buckets

### ISSUE THREAD

**Issue by paulangton** [kubernetes/test-infra#8910]
Spyglass currently uses an unauthenticated client (#8830) for accessing GCS buckets, which is fine for the time being because the buckets we use need to be public. In the future, we should allow the client to be configured with GCS credentials provided by the Prow user.

/area prow

**Comment by stevekuznetsov** [comment]
I think this would necessarily land with some ACL check like asking for the user's OAuth logic so we can validate that they can see the repo for which they are requesting tests. Then, we can serve them artifacts from an authenticated bucket for that repo's jobs.

**Comment by krzyzacy** [comment]
/assign
I did the similar thing with gubernator (unfortunately with python), I'll poke at the go client when I have time
