### ISSUE TITLE
Move sig-network jobs to config/jobs/kubernetes/sig-network

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/test-infra#8914]
Ref https://github.com/kubernetes/test-infra/pull/8851#issuecomment-409717866. Technically change to config.json is not allowed anymore so we should do this sooner than later.

/assign
cc @krzyzacy

**Comment by krzyzacy** [comment]
there's config/jobs/kubernetes/kubernetes/sig-network

also you can choose to make subdirs like config/jobs/kubernetes/ingress for sub-repos
