### ISSUE TITLE
prow/sigmention: add support for committees and wgs

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#8919]
The sig mention plugin that auto adds labels when a team is mentioned only works for sigs, but not working groups or committees. We should add support for these as well.

Relevant bits:
https://github.com/kubernetes/test-infra/blob/eb4e4bfcf7c083b96fde0420cdff5b0238d2c6db/prow/plugins/sigmention/sigmention.go#L112-L134
https://github.com/kubernetes/test-infra/blob/dd12621d6178838097847abf5842ad8d08fc9308/prow/plugins/plugins.go#L517-L519

Dunno if it's best to just make a new regex, or if the plugin itself needs a refactor.

/area prow

**Comment by nikhita** [comment]
There does not seem to a naming convention for teams for working groups. For instance, only 2 working groups teams seem to exist `cncf-conformance-wg` and `cncf-wg`...and they aren't official working groups too.

**Comment by nikhita** [comment]
I think we should decide on how we want to proceed with this and then add the help label.

/remove-help
