### ISSUE TITLE
Plank: generate a shorter timestamp snowflake string without tot

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8939]
https://github.com/kubernetes/test-infra/blob/master/prow/plank/controller.go#L509

this is too long to be stored as an int... second precision is probably enough? open for discussion

/area prow
/assign

cc @wonderfly @cjwagner @stevekuznetsov @BenTheElder

**Comment by krzyzacy** [comment]
@wonderfly is switching to store it as uint64 for now, probably should solve the issue

**Comment by wonderfly** [comment]
Yeah this is a problem better to be solved at downstream.

**Comment by BenTheElder** [comment]
this is an int64:

https://github.com/kubernetes/test-infra/blob/af23d941eb0b6d615d3a1360376827db5b3f678a/vendor/github.com/bwmarrin/snowflake/snowflake.go#L56

I don't think we should change this in prow.
/close
