### ISSUE TITLE
cowsay plugin for hook

### ISSUE THREAD

**Issue by paulangton** [kubernetes/test-infra#8954]
```
/lgtm
/hold
/meow
```
is a classic.  
I'd like to also support the Unix `cowsay` command, which will take any following text and encapsulate it in a cow's speech bubble, like so:
```
/cowsay /lgtm /hold
```
```
 _______
< /lgtm >
< /hold >
 -------
         \   ^__^ 
          \  (oo)\_______
             (__)\       )\/\
                 ||----w |
                 ||     ||
```

/assign
/area prow

**Comment by BenTheElder** [comment]
Just be careful what if any templates we include :grimacing: 
Also consider whalesay: https://github.com/docker/whalesay https://hub.docker.com/r/docker/whalesay/

**Comment by krzyzacy** [comment]
:-) `< /lgtm >` won't match the plugin regex though, it need to be start on its own line

**Comment by krzyzacy** [comment]
`/hold` matches the same thing, aka https://github.com/kubernetes/test-infra/blob/master/prow/plugins/hold/hold.go#L38

**Comment by spiffxp** [comment]
/hold cancel
doesn't make much sense on an issue

**Comment by BenTheElder** [comment]
/priority backlog
/lifecycle frozen
this is clearly an "important" issue for
/milestone someday

**Comment by paulangton** [comment]
that seems reasonable 😹
