### ISSUE TITLE
test bazel build in CI

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/test-infra#897]
Good targets to hit that actually work:

``` console
$ TARGETS=("//pkg/..." "//federation/..." "//plugin/..." "//cmd/..." "//build/..." "//cluster/...") 
$ bazel build "${TARGETS[@]}"
$ bazel test --test_tag_filters '-skip' "${TARGETS[@]}"
```

**Comment by spxtr** [comment]
I have a working prototype but there's still a bit to do before it's fully integrated with our infra. I'll try to get it done in the next few days.

**Comment by rmmh** [comment]
This is happening now!
