### ISSUE TITLE
Spyglass view stretches too wide after expand

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#8970]
aka https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-ubuntu1-k8sbeta-slow/1615/ and expand the skipped tests

/area prow
/assign @paulangton

**Comment by paulangton** [comment]
Seems like a problem with the JUnit viewer, adding to tracking issue

**Comment by BenTheElder** [comment]
yep, we just need to make sure it has max-width and line-wraps the text.

we should also look into speeding up junit processing (is this parallel already?) 🤔

**Comment by paulangton** [comment]
I don't believe it is parallel, I know we can at least make it parallel over the number of Junit files, but further than that we may need to 
a) find a new parsing library 
b) upstream performance changes to the current one 
c) make our own

**Comment by paulangton** [comment]
Don't believe this is still an issue
/close
