### ISSUE TITLE
approve cancel does not work

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#8998]
https://prow.k8s.io/command-help#approve lists `/approve [no-issue|cancel]` but this does not seem to work. https://github.com/kubernetes/test-infra/pull/8807#issuecomment-411631416

/kind bug
/area prow
/cc @krzyzacy

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/plugins/approve/approve.go#L563

I think this is some sort of WAI since we will require multiple approvals?

**Comment by BenTheElder** [comment]
Hmm I guess so. I guess approvers can /hold? ... hmmm

**Comment by fejta** [comment]
You can only manage your approval. So `/approve cancel` will cancel your approval, not others'.
/close
