### ISSUE TITLE
Plugin that blocks automerge without /merge command

### ISSUE THREAD

**Issue by grantr** [kubernetes/test-infra#9012]
I'd like a plugin that can block Tide's auto-merge until a `/merge` command is issued. If this seems like a useful addition, I'm happy to start work on it.

The expected workflow for this plugin would be:

1. Contributor creates PR
2. PR gets approved, lgtm, etc labels from reviewers
3. Contributor issues `/merge` to have Tide do the merge

This allows the PR workflow to more closely resemble the standard GitHub flow of create PR, get approval, hit merge button, which is likely to be what new contributors expect.

The difference between `/merge` and an approval gate like `/approve` is that `/merge` is available to all collaborators, including the author of the PR (who may not otherwise be considered a collaborator)

### Specific use case

In Knative, we often run into situations where a reviewer wants to make optional suggestions, giving the contributor the option of implementing those suggestions now or ignoring them (possibly deferring to a future PR). The typical case for this is adding a hold to the approval, but reviewers sometimes forget to do this, or forget to remove the hold after the contributor has implemented their suggestions. Having a `/merge` command is effectively the same as adding a `/hold` to every PR by default, and making it a standard part of the workflow to remove that hold when a merge is desired.

We'd also like to experiment with this alternate workflow:

1. Contributor creates PR.
2. All reviewers submit reviews with approved state. There's no separate `/approve` or `/lgtm`. This is roughly equivalent to the `lgtm_acts_as_approve` option.
3. When the PR is approved and contributor is happy with it, contributor issues `/merge`. Alternately, any collaborator can expedite  by issuing `/merge` themselves.

`/merge` is useful in this case because it's difficult for a reviewer to know in advance whether their review will cause a PR to be considered approved by Tide. With `/merge` in place, reviewers can approve without accidentally implying intent to merge.

### Implementation details

I'd expect this to be composed of two pieces:
- A hook plugin, similar to `hold`, that listens for `/merge` commands from collaborators (including the PR author) and adds an `ok-to-merge` label. It could also listen for `/merge cancel` to do the opposite.
- A tide configuration that blocks merge until the `ok-to-merge` label is applied.

/cc @cjwagner @fejta

**Comment by cjwagner** [comment]
This is something we've discussed and would like to have. Once the command plugin framework merges (https://github.com/kubernetes/test-infra/pull/8131) this can be added very easily.

**Comment by grantr** [comment]
The major difference is that with `/hold`, the PR is by default not blocked. With `/merge`, the PR is by default blocked.

Minor difference is that anyone can issue a hold command, but only collaborators can issue a merge command.
