### ISSUE TITLE
view_build.py crashes when junit.xml does not have 'time' attribute

### ISSUE THREAD

**Issue by filmil** [kubernetes/test-infra#9055]
Crashes here: https://github.com/kubernetes/test-infra/blame/master/gubernator/view_build.py#L53

with:
```
 time = float(child.attrib['time'])
KeyError: 'time'
```

Not sure whether the `time` attribute is required or not.  XSD says it is: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd
but if you search teh Internets, you will see that many example `junit.xml` don't have it, for example here: https://stackoverflow.com/questions/4922867/junit-xml-format-specification-that-hudson-supports

**Comment by BenTheElder** [comment]
> Noted. To me this reads like an argument in favor of lenient parsing of the junit xml. (and thanks @krzyzacy for the quick fix!)

Yes, thanks @krzyzacy !

> Very noble indeed. It's worth considering that junit is a commonly supported and understood format, widely supported by various tooling. Introducing a new format, even if better, means redoing integrations all over again. Obligatory https://xkcd.com/927

Er right, but for Kubernetes etc we control most of the test output anyhow, and we can introduce an adapter between formats. Everyone sticking to an underspecified XML format because we sort of support it is not great. Go for example has multiple outputs of its own and no junit, some of our tests parse shell output to produce horrible junit :-)

Ideally if such a format existed, we'd work to get buy-in from other parties and hash out what a good format would look like.

**Comment by ixdy** [comment]
JUnit doesn't have an official spec, no, but lots of tools support it, so I think it's a reasonable common format.

The best reference I've found is http://llg.cubic.org/docs/junit/, which does indeed list `time` as an optional field. :)

**Comment by filmil** [comment]
> The best reference I've found is http://llg.cubic.org/docs/junit/, which does indeed list time as an optional field. :)

That one in particular I find confusing, since it doesn't say that `time` is an optional attribute on `<testsuites>`. In contrast to `time` on `testcase`, where it says "optional". And yet, it's defacto optional on `<testsuites>` too. I guess that's what you get for not having a spec.

**Comment by ixdy** [comment]
well, it marks it as optional in the XSD below that.
/shrug

**Comment by BenTheElder** [comment]
> JUnit doesn't have an official spec, no, but lots of tools support it, so I think it's a reasonable common format.

Agreed, and we use it heavily to good effect. Someday it might be nice to move a few things over to a better defined format though. With spyglass we can easily support more than one, and I'm sure we can extend testgrid as needed, especially once it's OSS :-)
