### ISSUE TITLE
tot_test takes ~50s to finish?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9056]
```
senlu@senlu:~/work/src/k8s.io/test-infra/prow/pjutil$ go test ./...
ok  	k8s.io/test-infra/prow/pjutil	51.312s
```

https://github.com/kubernetes/test-infra/blob/master/prow/pjutil/tot.go#L74 looks like it's doing real sleep in the test?

/area prow
cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
I swear I made an issue for this when I migrated those tests. Gotta love "unit" tests that start an HTTP server and communicate with it ...

**Comment by stevekuznetsov** [comment]
Not exactly what I was looking for but thanks @k8s-ci-robot

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/test-infra/9120/pull-test-infra-bazel/19073/

/shrug

**Comment by krzyzacy** [comment]
hummm that is different, but... also using real data... 😢

**Comment by krzyzacy** [comment]
fixed in https://github.com/kubernetes/test-infra/pull/9858
