### ISSUE TITLE
Add audit logging / policy to kubetest + dind

### ISSUE THREAD

**Issue by hh** [kubernetes/test-infra#9060]
Audit logging is quite useful.

kubetest dind / calls kubeadm without an audit-policy or logging in place.

I would like to enable kubetest / dind / audit-logging.

**Comment by hh** [comment]
Thanks for your help @Katharine !

**Comment by BenTheElder** [comment]
ref: https://github.com/kubernetes/test-infra/pull/9061

**Comment by hh** [comment]
This is the workflow I'm currently using

```shell
  go get -u k8s.io/test-infra/kubetest # kubetest will need to come from this patch
  cd ~/go/src/k8s.io/kubernetes/
  bazel build //cmd/kubeadm # we use kubeadm later
  kubetest --build=dind
  kubetest --up --deployment=dind
  # This is not set, and we probably want the most recent one:
  KUBECONFIG=$(ls -rt /tmp/k8s-dind-kubecfg-* | tail -1)
  kubectl get nodes
  DIND_DIR=$(ls -rdt /tmp/dind-k8s-* | tail -1)
  tail -F /tmp/$DIND_DIR/audit/audit.log #Yea! Local Audit logs from a 'real' cluster!
```

**Comment by hh** [comment]
@Katharine you may find this useful

**Comment by BenTheElder** [comment]
dind/ is broken -> removed, let's get strong audit logging support in [sigs.k8s.io/kind](https://sigs.k8s.io/kind)!
