### ISSUE TITLE
prow: deck: allow links that open single plugin description modals

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#9078]
I would love to be able to link to a specific plugin help entry in docs, etc.

/area prow
/area prow/deck
/kind feature
/cc @spiffxp @BenTheElder @amwat

**Comment by spiffxp** [comment]
Agree

We've got https://prow.k8s.io/command-help#assign, it'd be nice to have https://prow.k8s.io/plugins#assign (for bonus bikeshedding it would be nice to have https://prow.k8s.io/commands#assign)
