### ISSUE TITLE
prow: updateconfig: new ConfigMap is not created when one does not exist

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#9096]
When a file is registered to watch and then added for the first time after the fact, we do not create the `ConfigMap` if it does not exist. This makes it weird for bootstrapping. Is this a side-effect of the `Replace()` call?

/area prow
/kind bug
/cc @BenTheElder @krzyzacy

**Comment by stevekuznetsov** [comment]
This is more for non-standard cases where we're creating custom maps

**Comment by BenTheElder** [comment]
Seems like it would be straightforward to ensure the configmap exists first, we should do this 👍

**Comment by krzyzacy** [comment]
done by #9825 
/assign @stevekuznetsov
