### ISSUE TITLE
prow: add command to add release notes

### ISSUE THREAD

**Issue by nikhita** [kubernetes/test-infra#9098]
Currently, only a few members have write access to k/k (and rightly so). See https://github.com/kubernetes/community/issues/2465 for more details on this.

The only way to add release notes in k/k is to edit the PR body. If I create a cherry-pick today and the parent PR does not contain a release note, I will need to ping someone with write access or the author of the parent PR to add the release note to the PR body (release notes are generated using the release note on the parent PR body, not the cherry-pick PR body).

The number of people with write access is considerably low now, which means pinging people isn't feasible anymore. See https://github.com/kubernetes/kubernetes/pull/67393#issuecomment-413777550 for an example.

I had discussed about this on slack and @cblecker had mentioned:

> in general, we need to figure out a way to handle release notes that doesn't manually require editing PR bodies. I'm not sure what the best way to do that is.. but we do need to have a consistent, single source of truth way to know what release note we will apply. This is actually one of the reasons we haven't completely removed manual write access to k/k

I agree and honestly, I don't know the answer to the above problem. Happy to bikeshed over this though. :)

/cc @cblecker @cjwagner @BenTheElder @tpepper 
/sig contributor-experience
/sig release
/area prow

**Comment by dims** [comment]
So we implement a `/release-note "my pr does this"`?

**Comment by nikhita** [comment]
> So we implement a /release-note "my pr does this"?

Something like that, but we also need to make sure that multi-line release notes with code blocks, etc are possible. IIRC there was something like this before...

**Comment by nikhita** [comment]
> IIRC there was something like this before...

It was removed in https://github.com/kubernetes/test-infra/pull/4718.

**Comment by tpepper** [comment]
Especially with the changes to write permissions since a year ago, this feels like a useful feature to me.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/57667 for some discussion/context around current k/k use cases for release notes

**Comment by ehashman** [comment]
/remove-lifecycle rotten
/reopen

@BenTheElder was very kind to use his write access to fix a release note on a PR that was otherwise mergeable for me. I think this is still needed. Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1614722730117800

**Comment by kikisdeliveryservice** [comment]
+1 This would be super helpful bc sometimes authors don't add a release note and mistag the pr and when they do add a release note that somehow, is misformatted in the body of the PR description. Both would def be quick fixes with a `/release-note` tag but get kind of dragged out with back and forth.
