### ISSUE TITLE
add needs-kind and needs-sig label enforcing in tide

### ISSUE THREAD

**Issue by tpepper** [kubernetes/test-infra#9115]
Code Freeze for 1.12 will be implemented (pending proposal to drop status/approved-for-milestone) as requiring:

* priority/critical-urgent
* SIG label
* kind label
* lgtm and approved
* milestone v1.12
* status/approved-for-milestone

In the past this was a mix of milestone munger, prow, submit-queue enforcing.

For tide to be able to support the SIG and kind label requirements, we need:

* needs-kind label addition
* requirekind plugin like requiresig
* enable requiresig and requirekind for k/k master and release-1.12 branches

Tide would expose the problem to PR authors as something like `Not mergeable, should not have the 'needs-kind' label.`

**Comment by tpepper** [comment]
/cc @AishSundar 

Do we need configurability down to the specificity of "kind/failing-test" and "kind/bug" or is kind/* sufficient?

**Comment by tpepper** [comment]
@cjwagner did I miss anything here from our conversation?

**Comment by cjwagner** [comment]
I think thats everything.
I may not actually implement this as separate plugins for `kind/*` and `sig/*` though. Since the behavior is so similar it probably makes more sense to have a single configurable plugin.

**Comment by cjwagner** [comment]
This was closed prematurely.  It should be closed by https://github.com/kubernetes/test-infra/pull/9259
