### ISSUE TITLE
we have no alerts for label_sync failing to run

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9121]
/kind cleanup
/area label_sync

ref: https://github.com/kubernetes/test-infra/pull/9054

While trying to deploy a new copy of the label_sync cronjob, I noticed that it had hung a few days ago.  An invalid label description caused it to hang, and no more copies were run subsequently.  How could we alert on this kind of situation?

I'm thinking of a pattern where logs are uploaded to GCS and consumed by testgrid just like all of our other maintenance jobs, and an alert is setup to fire if we see failure (or no success within a certain time)

**Comment by stevekuznetsov** [comment]
Can we migrate it to a `periodic` job and give it an entry in a infrastructure TestGrid view along with the commenters, etc? I'd image `peribolos` and other tools would join it there.

**Comment by fejta** [comment]
We need to create a cluster key that targets a cluster with trusted credentials, and write automation to ensure that only sig-testing jobs can use it.

**Comment by spiffxp** [comment]
/milestone v1.13
We should be able to do this now, follow the model used by peribolos

**Comment by stevekuznetsov** [comment]
Unfortunately the test grid approach isn't useful for us and we have the same problem! Maybe we could have a Prometheus alert if we publish per-job failure metrics?

**Comment by spiffxp** [comment]
/milestone clear

I'm opting to punt this if the testgrid approach isn't good enough.  Feel free to add back in to v1.14 if you're inclined to take the approach you suggested @stevekuznetsov

**Comment by stevekuznetsov** [comment]
You guys have the background to run it as a periodic now, so I think that should work ...

**Comment by spiffxp** [comment]
/milestone v1.14

OK, let's see if we can get to this

**Comment by stevekuznetsov** [comment]
It's running as a periodic now after @cjwagner changed it so alerting on it in testgrid should not be hard?

**Comment by cjwagner** [comment]
> It's running as a periodic now after @cjwagner changed it so alerting on it in testgrid should not be hard?

Already done: https://github.com/kubernetes/test-infra/blob/ae2330f210f68aa28e14ac928b6b650e947bff00/testgrid/config.yaml#L2191-L2194

We could probably tighten the alert window now.
/shrug
