### ISSUE TITLE
prow: approval: allow for repo-scoped approval configuration overrides

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#9126]
As noticed in https://github.com/kubernetes/test-infra/pull/9041, we need a mechanism by which users can override approval configuration on a per-repo level.

/area prow
/kind bug
/cc @cjwagner @fejta @BenTheElder @krzyzacy

**Comment by cjwagner** [comment]
/help
More general version of this issue applying to all repo scoped Prow config: https://github.com/kubernetes/test-infra/issues/9757

**Comment by matthyx** [comment]
As Cole wrote, that one is related to #9757 
/remove-lifecycle stale
/remove-help
/assign

**Comment by matthyx** [comment]
/remove-lifecycle rotten
... have to finish what I start

**Comment by BenTheElder** [comment]
If we're still looking at this, we should file with https://github.com/kubernetes-sigs/prow

**Comment by matthyx** [comment]
Right I've imported the PR but not the issue
