### ISSUE TITLE
prow: dogs win the fighting

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/test-infra#9135]
When I call my cat, I can't find it. (https://github.com/kubernetes/kubernetes/pull/62582#issuecomment-415313522)

When I call my dog, it appears. (https://github.com/kubernetes/kubernetes/pull/62582#issuecomment-415313654)

Anyway, interesting plugins!

/cc @fejta

**Comment by ixdy** [comment]
> This is a new version as of August 2018 - now with added JSON support!

Maybe related?

**Comment by nikhita** [comment]
https://twitter.com/adenforshaw/status/1031485169448808448

**Comment by ixdy** [comment]
it looks like the cat api no longer returns a `source_url`, but we don't use that, so it's fine.

working on a fix now.
/assign

**Comment by ixdy** [comment]
actually, it seems like the API is completely different, and it no longer even has categories. :(

this is more involved, punting to someone else.
/unassign

**Comment by bobcatfish** [comment]
> actually, it seems like the API is completely different, and it no longer even has categories. :(

😭

**Comment by ixdy** [comment]
why is that button even there
/woof woof

**Comment by xiangpengzhao** [comment]
Thanks @ixdy for helping the cats be back! Guess they will be fighting with dogs again :) I like the plugins!
