### ISSUE TITLE
Allow test-infra team to schedule trusted prow jobs

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#9171]
Each prow job [chooses](https://github.com/kubernetes/test-infra/blob/1770971a343137ca00ebd420e081a984496b7c37/prow/getting_started.md) the cluster in which it runs ([example](https://github.com/kubernetes/test-infra/blob/1770971a343137ca00ebd420e081a984496b7c37/config/jobs/bazelbuild/rules_k8s/rules_k8s_config.yaml#L4)) .

We will create a new trusted cluster context. These jobs will run in the same cluster as the rest of the prow binaries. This will improve the usability of maintenance jobs like peribolos, branch protection, label sync.

Today these jobs run as cron jobs, which result in a day lag between between:
* merging the PR which declares a new label, enables protection and/or org member
* running the cronjob which creates the label, protects the branch and/or invites the org member

Since these are trusted jobs that have a higher level of access than untrusted jobs, we will restrict who can create them:
* The job must be defined in [test-infra](https://github.com/kubernetes/test-infra/tree/1770971a343137ca00ebd420e081a984496b7c37/config/jobs/kubernetes/test-infra)
* The job must be a postsubmit and/or periodic job (no presubmits, which can contain untrusted code).

/cc @spiffxp @cjwagner

**Comment by BenTheElder** [comment]
FWIW we have some similarish stuff with the `security` build context for k-s/k, we currently just restrict that:
- only k-s/k presubmits can use this
- k-s/k presubmits must use this
If we make any extensions to support this better we should use them to keep this one locked down as well.

**Comment by cjwagner** [comment]
It might make sense to restrict where the job is defined to a single file. That would make it really obvious which jobs we are allowing to run in the service cluster. Restricting to the test-infra leaf directory seems fine too though.
This functionality will be great to have! It will let us replace any k8s cronjobs like the branch-protector with periodic ProwJobs that run in the service cluster.

**Comment by spiffxp** [comment]
/priority important-soon
/kind design
/sig testing
/area prow
Yes please.

**Comment by spiffxp** [comment]
/close
I'm assuming this is now done since #9177 has merged and we now have some trusted jobs for things like running peribolos in response to kubernetes/org merges
