### ISSUE TITLE
[kind] weave-net pod evicted due to disk pressure

### ISSUE THREAD

**Issue by munnerz** [kubernetes/test-infra#9181]
When creating a cluster using `kind`, tmpfs is used for the `/var/lib/docker` directory.

By default, Docker creates a temporary filesystem of size 1GB when `--tmpfs` is used.

As a result, I have observed that the weave-net container has been evicted before any other pods have started due to running low on disk space:

```
kubectl get pods,nodes --all-namespaces
NAMESPACE     NAME                                                   READY     STATUS    RESTARTS   AGE
kube-system   pod/coredns-78fcdf6894-7grcq                           0/1       Pending   0          1m
kube-system   pod/coredns-78fcdf6894-z2sq8                           0/1       Pending   0          1m
kube-system   pod/etcd-kind-james-control-plane                      1/1       Running   0          31s
kube-system   pod/kube-apiserver-kind-james-control-plane            1/1       Running   0          14s
kube-system   pod/kube-controller-manager-kind-james-control-plane   0/1       Evicted   0          25s
kube-system   pod/kube-proxy-mzlpw                                   1/1       Running   0          1m
kube-system   pod/kube-scheduler-kind-james-control-plane            1/1       Running   0          14s
kube-system   pod/weave-net-k6n8x                                    0/2       Evicted   0          11s

NAMESPACE   NAME                            STATUS    ROLES     AGE       VERSION
            node/kind-james-control-plane   Ready     master    1m        v1.11.2
```

and corresponding events from the weave-net pod:

```
Events:
  Type     Reason   Age   From                               Message
  ----     ------   ----  ----                               -------
  Warning  Evicted  23s   kubelet, kind-james-control-plane  The node was low on resource: [DiskPressure].
```

We should probably set the `tmpfs-size` flag here to increase the /var/lib/docker partition from 1GB to something more sensible (https://docs.docker.com/v17.09/engine/admin/volumes/tmpfs/#use-a-tmpfs-mount-in-a-container). It'd be ideal if this were somehow configurable - maybe we need to begin thinking about the kind configuration surface.

Aside from that, we should probably set pod priorities etc. on things like the weave-net pod.

I'd be happy to pick this work up if we can decide on either what size it should be, or how we want to make it configurable 😄 

/cc @BenTheElder

**Comment by BenTheElder** [comment]
Thanks for reporting this!

Yeah I think setting that flag makes sense.

For advanced config I have a note in docs/todo.md about accepting a config file for customizing things like the kubeadm config template. I think this would probably go in there vs more flags 😅

**Comment by spiffxp** [comment]
@BenTheElder ping, I'm going to leave it to you to decide if this is still relevant; if so, probably deserves to be closed in favor of a kubernetes-sigs/kind issue

**Comment by BenTheElder** [comment]
This falls under things to document in a user guide. I currently aim to write one once I've cut a release (later this week?)
