### ISSUE TITLE
[prow] DCO sign-off checker

### ISSUE THREAD

**Issue by munnerz** [kubernetes/test-infra#9187]
We at Jetstack need to support DCO sign-off checks on our repo.

After configuring probot/dco for our repo (that previously used status checks to report the DCO status), it has since moved to using the GitHub Checks API (which is currently incompatible with tide from what I can see).

I was planning on implementing a full DCO checker external plugin for Prow as a result. @BenTheElder suggested that this may be better off as an *internal* plugin.

I am going to get started on this as we need it internally. I am basing the code off https://github.com/heptiolabs/sign-off-checker - as such, I need to use GitHub's 'ListCommits' endpoint to check each commit for sign-off. This will require an additional to Prow's GitHub client as this method is not currently implemented.

/assign
/area prow

**Comment by BenTheElder** [comment]
I really think Prow should support this first class, the CLA is optional for the CNCF now and only Kubernetes and GRPC require it. The DCO seems like it will be widespread.

/cc @stevekuznetsov @cjwagner 

also cc @mattfarina
