### ISSUE TITLE
I have signed the CNCF CLA. Why does this PR have no CNCF-CLA:YES label? 

### ISSUE THREAD

**Issue by Mr-Linus** [kubernetes/test-infra#9194]
The PR link:<https://github.com/kubernetes/kubernetes-docs-zh/pull/541>
I have signed the CNCF CLA. Why does this PR have no CNCF-CLA:YES label?

**Comment by BenTheElder** [comment]
You're good to go now, sometimes we seem to not get the event for the CLA status going green, `/check-cla` forces a re-check. https://prow.k8s.io/command-help#check_cla

**Comment by BenTheElder** [comment]
Sorry about that 😬

**Comment by Mr-Linus** [comment]
got it .thanks!
