### ISSUE TITLE
Gubernator PR page doesn't work for non-kubernetes orgs

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#920]
https://k8s-gubernator.appspot.com/pr/google_cadvisor/1508 is pretty confusing and certain links point to confusing places. Similarly, I really think that `pr/kubernetes_kubernetes/123`, `pr/kubernetes/123`, and `pr/123` should all be equivalent.

**Comment by fejta** [comment]
Seems to work just fine these days:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/google_cadvisor/1629/pull-cadvisor-e2e/193/?log#log

**Comment by ixdy** [comment]
The commit ref links on that page go to kubernetes/kubernetes, not google/cadvisor.
Similarly, the "view on GitHub" link on https://k8s-gubernator.appspot.com/pr/google_cadvisor/1629 is wrong.

**Comment by fejta** [comment]
/assign
Will try and take a swing at this

**Comment by kargakis** [comment]
cc @stevekuznetsov

**Comment by spxtr** [comment]
Now it does.
