### ISSUE TITLE
Refactor and better manage scale-testing infra

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#9223]
Following today's infra-team meeting, I'm creating this umbrella for things we'd need to do for sig-scalability (that I can think of atm):

- [x] Move smaller scale projects to boskos wherever possible (short-term)
- [ ] Move all scalability jobs to boskos (long-term, and needs more work)
- [x] Isolate GKE-testing from OSS ones project-wise
- [x] Delete deprecated projects or move to boskos. Few I could find:
  - [x] k8s-jkns-pr-kubemark
  - [x] k8s-jenkins-gci-kubemark (after moving kubemark-canary to boskos)
  - [x] k8s-jenkins-scalability (after moving 100-node scalability canary to boskos)
- [ ] Host [perf-dash.k8s.io](perf-dash.k8s.io) on CNCF project and probably change it's DNS entry
- [ ] Below are projects (roughly sorted from largest to smallest) in use by scalability jobs currently. We need to get their billing right.
  - kubernetes-scale (still being used for some GKE scale tests)
  - k8s-scale-testing (still being used for some GKE scale tests)
  - k8s-presubmit-scale
  - kubemark-scalability-testing
  - k8s-e2e-gce-scalability-1-1
  - k8s-e2e-gci-gce-scale-1-4
  - k8s-jenkins-gci-scalability
  - k8s-jenkins-scalability
  - k8s-jenkins-blocking-kubemark
  - k8s-jenkins-kubemark
  - k8s-jkns-clusterloader

cc @kubernetes/sig-testing @kubernetes/sig-scalability-misc @dims @BenTheElder @thockin @amwat

**Comment by shyamjvs** [comment]
/assign
I can drive this overall, and do some of the pieces. But if someone wants to take up any AIs, you're gladly welcome :)

**Comment by shyamjvs** [comment]
Some analysis on projects/jobs that can be moved to boskos:

1. k8s-jenkins-scalability (used by [scalability-canary](https://k8s-testgrid.appspot.com/sig-testing-canaries#scalability-canary) job - uses ~100 CPU in us-central1-f)
2. k8s-jenkins-gci-scalability (used by [gce-100](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce) job - uses ~100 CPU in us-central-f)
3. k8s-e2e-gce-scalability-1-1 (used by [gce-100-beta](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-1.11) job - uses ~100 CPU in us-east1-b)
4. k8s-e2e-gci-gce-scale-1-4 (used by [gce-100-stable1](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-1.10) and [gce-100-stable2](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-1.9) jobs - each uses ~100 CPU in us-east1-b)
5. k8s-jenkins-kubemark (used by following jobs:
  - [kubemark-100](https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100) - uses < 20 CPU (so this job can be moved to regular gce boskos pool)
  - [kubemark-small-last-release](https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-small-last-release) - uses < 10 CPU (so this job can be moved to regular gce boskos pool)
  - [kubemark-high-density](https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100-high-density) - uses ~100 CPU in us-central1-f
6. k8s-jenkins-blocking-kubemark (used by [kubemark-500](https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-500) job - uses ~80 CPU)

- [ ] So we can create a new boskos pool with all the above projects and use it for those jobs (as each of them needs about 100 CPU). Few blockers to clear before that:
  - [ ] Move CPU quota in projects 3 and 4 from us-east1-b to us-central1-f (as otherwise the pool would be inconsistent wrt the zone having the quota)
  - [ ] Increase quota for projects 5 and 6 from 100 CPU to a bit higher (sth like 110) so that other jobs using the pool would also be able to run on it

And now, some projects/jobs that can go to boskos right away:

- k8s-jenkins-gci-kubemark (used by [kubemark-canary](https://k8s-testgrid.appspot.com/sig-testing-canaries#kubemark-canary) - uses < 20 CPU)
- k8s-jkns-clusterloader (used by [clusterloader](https://k8s-testgrid.appspot.com/sig-scalability-perf-tests#cluster-loader) and [clusterloader2](https://k8s-testgrid.appspot.com/sig-scalability-perf-tests#cluster-loader2) jobs - each of which uses < 10 CPU)

**Comment by shyamjvs** [comment]
@amwat @krzysied - Would you be able/interested to pick up some of the AIs above? That'll be quite helpful for the CNCF migration.

**Comment by amwat** [comment]
I can create the boskos pool and update the jobs accordingly.

**Comment by shyamjvs** [comment]
That would be great, thanks. Note that the blockers mentioned above need to be fixed first before doing that.

**Comment by shyamjvs** [comment]
> Move CPU quota in projects 3 and 4 from us-east1-b to us-central1-f (as otherwise the pool would be inconsistent wrt the zone having the quota)

Actually, now that I think of it, it's probably better (for the long run) to move the remaining projects' quota in the opposite direction (us-central1-f -> us-east1-b) because:

- we have more slack in us-east1-b wrt resources available
- when we later split our large monolithic presubmit project into multiple smaller ones, they would all be in us-east1-b (where we've already been granted quota currently). So it'll be easier to achieve consistency. cc @BenTheElder

**Comment by shyamjvs** [comment]
@amwat Would you be able to cross out the checklist items that are done already? (especially those around boskos)

**Comment by cblecker** [comment]
Sorry for the comment spam. Bug in a new plugin.

**Comment by shyamjvs** [comment]
/reopen
/remove-lifecycle rotten

This is still pending I think.

**Comment by amwat** [comment]
I think we can mark this one as resolved.
1. https://github.com/kubernetes/test-infra/issues/9223#issuecomment-417777088 these tasks are done.
2. Small 100 node periodics have been moved in https://github.com/kubernetes/test-infra/pull/9567#issuecomment-425525626.
3. For presubmits sig-scalability is running their own prow instance now (@krzyzacy ?) and is tracked in https://github.com/kubernetes/test-infra/issues/7769#issuecomment-498861893

**Comment by shyamjvs** [comment]
Thanks for the leads. Could you mark off the ones done on the checklist? I think there are still some things left (like perfdash dns change, GKE/GCE tests billing seperation)

**Comment by krzyzacy** [comment]
(this issue is giving :unicorn:)

I think people are start moving jobs running on k8s-scale project onto a separated build cluster. Jobs like kubemark will stay in k8s-prow-build until there's a new boskos pool in that new build cluster.
