### ISSUE TITLE
[prow] Why is k8s-ci-bot automatically label certain sig when the OWNERs file has no sig label?

### ISSUE THREAD

**Issue by wenjiaswe** [kubernetes/test-infra#9230]
We were looking at some issues and PRs and was wondering why sometimes k8s-ci-bot automatically label certain sig when the OWNERs file has no sig label? 

For example, https://github.com/kubernetes/kubernetes/pull/68068, in this PR, k8s-ci-bot labeled it as sig/api-machinery, while the OWNERS file for none of the changed files has sig api-machinery label as below:
```
labels:
 - sig/api-machinery
```

And my understanding is that only if the OWNERS file contains sig label, that the robot will assign to the sig. Is my understand wrong?

I do see that some of the related OWNERS file on PR #68068 mentioned above contains kind/api-change label, https://github.com/kubernetes/kubernetes/blob/819253dd2d620cd9a877e97e4800252b9ed99b65/pkg/api/OWNERS#L15, is that why sig/api-machinery got labeled? But I could not find where kind/api-change and sig/api-machinery are correlated. 

Thanks in advance!

@BenTheElder @krzyzacy

**Comment by krzyzacy** [comment]
cc @cjwagner @cblecker @kargakis  who might know this better?

**Comment by cblecker** [comment]
https://github.com/kubernetes/kubernetes/blob/e1a270d6dcfd73e35db3970a042db9c704ec5a8f/cmd/kube-controller-manager/OWNERS#L66-L67

**Comment by cblecker** [comment]
`cmd/kube-controller-manager/app/autoscaling.go` was modified in this PR.

/close

**Comment by wenjiaswe** [comment]
@cblecker ah! It was added 11 days ago, thanks!
