### ISSUE TITLE
PR Updates With New OWNERS Changes Should Un-Approve the PR

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9238]
at the very least we should probably detect `OWNERS` file changes and yank approval

/area prow

**Comment by stevekuznetsov** [comment]
So on merge if a PR changes OWNERS, relist all approved PRs and recalculate ownership?

**Comment by BenTheElder** [comment]
I think if a PR pushes a change to OWNERS remove the `approve` label entirely. It'd be too easy to get a root level approval of a PR then add some random owners file changes. These in particular seem riskier than other changes, because you could EG add yourself to the root.

**Comment by stevekuznetsov** [comment]
Oh, this is on _the PR changing `OWNERS`_, I see.

**Comment by BenTheElder** [comment]
Yeah, you can get sticky approval on a PR that changes OWNERS which seems pretty bad. If you get approval from a root approver you're free to change any owners file after that and you only need to get an LGTM which is a very, very low bar.

**Comment by stevekuznetsov** [comment]
In a similar vein, if a PR changing `OWNERS` merges, should we re-calculate approved PRs?

**Comment by BenTheElder** [comment]
Maybe. I'm not sure if we can do that efficiently and if it is a likely scenario. If we strongly need to remove someone from approvers we can one-off go through approved PRs and un-approve them, the more common cases are adding a new approver (which shouldn't trigger recomputing) or someone voluntary removing themselves because they have moved on don't wish to review PRs.
