### ISSUE TITLE
Fix prow lint errors

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#9247]
Run https://github.com/golang/lint on ./prow/...

/good-first-issue

**Comment by alisondy** [comment]
Would like to help!

**Comment by matthyx** [comment]
Please go ahead, it's all yours @alisondy 
/remove-help

**Comment by matthyx** [comment]
You can only assign members of the organization.

**Comment by alisondy** [comment]
hello there just an update, need some feedback on what i need to progress forward with my pull request :) thanks in advance

**Comment by alisondy** [comment]
Just wanted to post an update in here about the status of this request
Just have a few more things to tidy up , then re review.
Action items from feedback on pull request
[ ] Will revert the naming of the artifactuploader, to avoid impacting downstream consumers
[ ] Will fix all TODO's as opposed to hiding lint errors

**Comment by idealhack** [comment]
/reopen
/remove-lifecycle stale
/lifecycle active

until it's done and maybe introduced some verify jobs
