### ISSUE TITLE
prow: hook: link to deck's per-repo command help page in comment

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#9256]
We should use the repo-specific command help page in Deck for the `I understand the commands that are listed here` comment from the bot.

/area prow
/area prow/hook
/kind feature
/cc @bbguimaraes @cjwagner @BenTheElder

**Comment by BenTheElder** [comment]
/help wanted

This would involve an update to:
https://github.com/kubernetes/test-infra/blob/d9324e36d37c3286e3f409094863afe08f6d75a1/prow/plugins/trigger/pr.go#L150

It should be pretty simple

**Comment by BenTheElder** [comment]
er
/help
🙃

**Comment by stevekuznetsov** [comment]
Threading through the config to every plugin that uses it (and then passing it to the reporter lib) seems a bit messy today, maybe we can do better on design?

**Comment by BenTheElder** [comment]
Huh? We already thread through the PR, why can't we build the URL from that?

**Comment by stevekuznetsov** [comment]
We need the `deck` URL to thread through

**Comment by BenTheElder** [comment]
I agree that we can probably do something better than threading the entire config to every plugin that uses it, but that seems completely orthogonal to what should be a pretty small patch to give better help links.

**Comment by idealhack** [comment]
While most places were addressed by https://github.com/kubernetes/test-infra/pull/10618 and https://github.com/kubernetes/test-infra/pull/10654, I couldn't find a nice way to fix the last ones:

https://github.com/kubernetes/test-infra/blob/2862878bf4e3aaca0d83e31e003ba004ac19d74b/prow/plugins/dco/dco_test.go#L95

@munnerz could you take a look?

/reopen
/unassign
/remove-lifecycle rotten
