### ISSUE TITLE
Support https cookiefiles for clonerefs

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#9270]
Right now we only support ssh for cloning. But various services like https://cloud.google.com/source-repositories/ require http cookies (and/or a gcloud credential helper, but the cookies seem a better path forward here).

Let's extend the clonerefs binary to include a `--cookiefile=/path/to/cookiefile` flag, and allow the user to configure plank to use a secret for this file. Plank will mount the secret into the clonerefs container and send it the flag.

We can then ensure we run commands like this 
`git -c http.cookiefile=$HOME/.gitcookies fetch https://whatever`

/cc @stevekuznetsov @krzyzacy 
/area prow

**Comment by fejta** [comment]
Plank will call decorate, and does similar things now for ssh keys: https://github.com/kubernetes/test-infra/blob/9d23d7abda73fb40ec87c3d10b6f0f0e8a04e527/prow/pod-utils/decorate/podspec.go#L168

**Comment by fejta** [comment]
```console
$ gcloud auth git-helper --account=someone@somewhere.tld get
protocol=https
host=googlesource.com
^D
username=git-account
password=ya29.c.yadayadayada

$ curl https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=ya29.yadayadayada
{
 "expires_in": 3127
}
 
$ cat cookies
.googlesource.com	TRUE	/	TRUE	1536227753	o	ya29.c.yadayadayada

$ git -c http.cookiefile=cookies ls-remote https://blahblah
```

**Comment by fejta** [comment]
/cc @krzyzacy 

Next we need a controller that has access to the refresh token and uses it to update a secret with a new access token every ~hour

**Comment by krzyzacy** [comment]
/close
grandmaaaaaatriaaaaaaarch!
