### ISSUE TITLE
prow: getting_started.md is out of date

### ISSUE THREAD

**Issue by ibzib** [kubernetes/test-infra#9274]
I was following Prow's [getting started instructions](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started.md). In two places the instructions say to use `bazel run //prow/cmd/config`, but it fails with the message `BUILD file not found on package path`. It looks like this is because the `config` binary has been deleted.

**Comment by stevekuznetsov** [comment]
Looks like we can change to `checkconfig`?

**Comment by BenTheElder** [comment]
Yeah this should probably be something like `bazel build //prow/cmd/checkconfig -- --config-path=/path/to/config.yaml --plugins-path=/path/to/plugins.yaml`  now
