### ISSUE TITLE
missing stable3 scalability job

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9282]
For existing releases, these are the 100 node gci-gce-scalability-1.y jobs on each release 1.y-blocking dashboard, eg:
- [ci-kubernetes-e2e-gci-gce-scalability-stable1](https://github.com/kubernetes/test-infra/blob/6797e889c57e53add6aee5cf51a925284fad6bba/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L63) for the most recently released version of kubernetes
- [ci-kubernetes-e2e-gci-gce-stability-stable2](https://github.com/kubernetes/test-infra/blob/6797e889c57e53add6aee5cf51a925284fad6bba/config/jobs/kubernetes/sig-scalability/sig-scalability-periodic-jobs.yaml#L93) for the previous released version of kubernetes
- we don't appear to have a stable3 equivalent, and we should, ref: https://github.com/kubernetes/community/pull/2623#discussion_r215203539

/area jobs
/priority important-soon
/kind cleanup
/sig scalability

FYI @wojtek-t

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/9363

**Comment by shyamjvs** [comment]
Thanks for pointing this Aaron. You're right, we should have a stable3 scale job too (I've always been confused by the naming convention).

@krzysied - would you be able to add such a job?
