### ISSUE TITLE
clarify release-blocking scalability jobs

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9283]
ref: https://github.com/kubernetes/community/pull/2623#discussion_r215084542

There's no single place we can link to as "this is the list of release blocking jobs that sig-scale owns"

Instead of saying that list is "the intersection of jobs defined in the sig-scalability dir and the jobs on the release-X-blocking dashboards" let's just put all the jobs in a single config file for now?

Possibly adjust names for consistency?

/area jobs
/priority important-soon
/kind cleanup
/sig scalability

FYI @wojtek-t

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/issues/9363

**Comment by shyamjvs** [comment]
Fixed this in https://github.com/kubernetes/test-infra/pull/10637 - PTAL.
