### ISSUE TITLE
[pod-utils] clonerefs does not properly support cloning using a SSH key

### ISSUE THREAD

**Issue by munnerz** [kubernetes/test-infra#9284]
We are enabling Prow for one of our private repositories and have ran into a few issues when trying to do this with decorated config.

I notice that bootstrap.py already supports this, however we'd prefer to use decorated config for this particular repo to save having the gcloud dependency etc.

Notably:

1) Specifying `decoration_config` on our presubmit spec does not seem to have any effect/does not seem to get propagated down into the ProwJob nor the pod's spec. I guess this will require a change to *hook* to support passing this configuration down.

2) Once I made the ssh_key a part of the default decoration config, it *does* then get added to the ProwJob spec (and consequently, the key *is* being mounted into the pod & clonerefs is adding the key to the default SSH agent) - the issue now, is that `clonerefs` itself hardcodes the use of `https` GitHub endpoints for cloning, meaning the ssh key is never actually used.
You can see where this is hardcoded here: https://github.com/kubernetes/test-infra/blob/183533ae6ba748b8b07f4af16a49797c1b4df6a5/prow/pod-utils/clone/clone.go#L35

I'm wonder what the best way to approach a fix for this is - I notice that the above method *will* allow overriding the CloneURI, however I'm not sure whether the fix should actually live in the above method (in `clone.go`).

Is anyone else using decorated config and ssh keys?

cc @stevekuznetsov @BenTheElder @wallrj @simonswine 
/area pod-utils

**Comment by stevekuznetsov** [comment]
Err -- we found the issue with specifying `decoration_config` on a per-job level and @krzyzacy has a PR for that. As for the other issue, you need to provide a clone URI override with `clone_uri`. Cole documented this [here](https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#how-to-configure)

**Comment by stevekuznetsov** [comment]
Seems like this is all fixed,

/close
