### ISSUE TITLE
Figure out where to put github commands

### ISSUE THREAD

**Issue by spxtr** [kubernetes/test-infra#930]
See https://github.com/kubernetes/contrib/issues/1908, comments in https://github.com/kubernetes/contrib/pull/1428, and comments in https://github.com/kubernetes/test-infra/pull/887 for background.

We want to add a small set of commands that contributors can make in GitHub comments to accomplish certain tasks that they otherwise can't. The obvious first step is `/lgtm`. We have some desires here:
1. They are quick. I would say from comment to action should be no longer than 10 seconds, which can be accomplished by an event-polling system or a push-based system.
2. They are transparent. If I write `/lgtm` and I'm not a reviewer then the bot should comment explaining why it is ignoring me. Similarly, the available commands need to be discoverable.
3. They are consistent. Either we go with `(/lgtm, /test gce)` or `(@k8s-bot lgtm, @k8s-bot test gce)`, but not `(/lgtm, @k8s-bot test gce)`. My preference is `@k8s-bot do something please` because I feel like I'm asking @k8s-bot to do something for me, and contributors are already familiar with the format. I'm happy either way, though.
4. They don't fight each other.
5. They are reliable.

I'm suggesting adding the commands to prow, as in #887. Also, we are moving certain mungers over to prow already. Things like removing LGTM after commit make sense to do here. The downside is that prow has only been alive for a few months, so developers aren't too familiar with it yet.

cc @apelisse @grodrigues3 @eparis

**Comment by apelisse** [comment]
I obviously agree with all five points. Let's use `prow` as the central place to implement these new/migrated mungers.

What I think is missing today from `prow` through is:
- More pluggable/configurable "mungers"
- Better isolation between plugins/mungers
- Replace homemade github layer with go-github
- Organization-wide hooks

**Comment by grodrigues3** [comment]
cc @bgrant0607

**Comment by grodrigues3** [comment]
I'm all for this!  And I do not have a strong opinion one way or another regarding command syntax (@k8s-bot or /<command> are equally comfortable for me).  Either way, all 5 of the above make sense.  I would also add improve documentation for commands (people need to know what they can ask the bot to do).

**Comment by bgrant0607** [comment]
@spxtr @apelisse @grodrigues3 @eparis @fejta 

I don't really care whether github commands are implemented in prow or in mungegithub. I do care that they are all implemented in one place, and that that place is easily discoverable by contributors. I am not happy with that place being either contrib or test-infra in the long run. 

Up to this point, we've been using the [contrib repo to propose improvements](https://github.com/kubernetes/contrib/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fvelocity-improvement), so work here isn't going to be discoverable by the set of people who've worked in this area in the past. 

How hard would it be to move prow to its own repo? We already created a pr-bot repo for mungegithub, but we could put prow there.

As for syntax, in addition to @spxtr's excellent list, I care that the syntax is simple, familiar, and unambiguous. Complicated phrases like `@k8s-bot do something please` fail the "simple" requirement. I'm not wedded to `/something`, but I want ideally a single string for a command that doesn't take parameters. I definitely do not want words non-essential to the meaning of the command, nor lots of variants accepted, which just makes remembering and documenting the required syntax harder.

**Comment by bgrant0607** [comment]
@spxtr And please label all PR-workflow-related issues with `kind/velocity-improvement`. I just created that label in this repo.

**Comment by spxtr** [comment]
> How hard would it be to move prow to its own repo? We already created a pr-bot repo for mungegithub, but we could put prow there.

It wouldn't be hard at all. The actual jobs that it currently triggers on "@k8s-bot test this" are configured under the `jenkins` folder, but they don't need to live in the same place. We would just need to make sure that the other repo is discoverable.

> And please label all PR-workflow-related issues with kind/velocity-improvement. I just created that label in this repo.

Sure.

**Comment by eparis** [comment]
the `@k8s-bot` syntax implies that is it "k8s-bot" which does the work. Something like `@k8s-bot lgtm` would be odd since it would be k8s-merge-robot who actually was doing the work. Should `@k8s-merge-robot` also work?

non-name prefixed commands (like /lgtm) don't suffer from the discontinuity.

something else to consider is where to document commands. Right now the submit-queue robot shows them (it's just /lgtm but still) on the webui. If we use the same command set across tools (good idea) where do we document them all?

**Comment by spxtr** [comment]
Lets go with `/lgtm`.

> something else to consider is where to document commands.

Some repos have a comment at the top of every new PR saying something along the lines of "thanks for the submission, here are some commands, a reviewer will be with you shortly."

**Comment by techtonik** [comment]
For me the logical way is to implement a bot as a webhook endpoint and some clients for it. This way message processing logic could be tested independently - send POST message to bot and read out what it is going to do.

If webhook is to be supplied to GitHub directly, then there should be some proxy that transforms the message from GitHub into JSON that makes sense for the bot and includes all necessary context for it to operate. Would be very nice to see all fields in message context documented.  Why context field is added. For example, some mechanisms can be used to take care not to respond to other bots. 

You can then log to bot channel and ask "my PRs, plz." and it may show you your backlog. =)

**Comment by ixdy** [comment]
> the @k8s-bot syntax implies that is it "k8s-bot" which does the work.the @k8s-bot syntax implies that is it "k8s-bot" which does the work.

FWIW with prow, @k8s-bot isn't even commenting on any PRs anymore - it's either @k8s-ci-robot or @k8s-merge-robot. Not sure if this is something we want to change or not.

**Comment by spxtr** [comment]
I've been meaning to switch it back to @k8s-bot for a while. Just been lazy.
