### ISSUE TITLE
unpin docker in bootstrap image

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9305]
we should really not use super old docker anymore, there should be many improvements if we upgrade

**Comment by BenTheElder** [comment]
xref also https://github.com/kubernetes/release/pull/622/files#r215250074

**Comment by BenTheElder** [comment]
upgrade (but not un-pinning) occuring in https://github.com/kubernetes/test-infra/pull/9379

**Comment by BenTheElder** [comment]
/shrug
this is debate-able, I believe cluster lifecycle is also suggesting specific docker releases still.
Happy to unpin if we think this is wise, but i'm not so sure now.
cc @neolit123 @dims

**Comment by neolit123** [comment]
> there should be many improvements if we upgrade

current pined version seems to be 18.06 for the image.
what are the improvements that we need and which version is sufficient to bump to?
would 18.09 suffice?

AFAIK, 18.09 should be fine at this point, but i don't think i've seen reports for anything newer.
@kubernetes/sig-cluster-lifecycle

**Comment by BenTheElder** [comment]
Originally the issue was to simply not pin to a version so whenever we
build the image we get the latest stable, like most of the tools.

For this... It seems maybe that's not really worth it.

**Comment by dims** [comment]
@neolit123 @BenTheElder i've filed a bump in https://github.com/kubernetes/kubernetes/pull/72823

**Comment by neolit123** [comment]
seems like only kubeadm (which sort of implies k/k nowadays) is at 18.09 ATM.
release and test-infra are still at 18.06.
