### ISSUE TITLE
tide status page does not indicate milestone requirements

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9335]
We use two k/k queries that have different milestone requirements, but they look as though they're the same query in the UI

<img width="1621" alt="screen shot 2018-09-11 at 10 04 05 am" src="https://user-images.githubusercontent.com/49258/45365245-1a976f80-b5aa-11e8-9197-734ea4e2c3c8.png">

/area prow
/kind bug
/priority important-soon

**Comment by BenTheElder** [comment]
This is a pretty easy fix. I can probably tackle it in the near future if nobody else does. Basically we should just need to update the javascript snippet that generates the rendered queries to handle that field and add something like:

**and in** one of the follow milestones:
 - milestone-v1.12

**Comment by BenTheElder** [comment]
We also need to surface this in the query info on the PR page, cc @amwat @qhuynh96 
Additionally, on the PR page, for the sets of missing labels, we need some way to make it clear which one relates to the milestone or not when we have multiple queries with and without milestones.
