### ISSUE TITLE
Spyglass: Add a UI to access spyglass from deck

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9339]
/area prow
/cc @paulangton @BenTheElder @AishSundar 
/assign @ibzib

**Comment by ibzib** [comment]
It looks like Spyglass URLs need to be generated somehow.

I see two ways we could do this:
1. Client side: replace the Gubernator link's prefix with Prow's in [script.js](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/static/script.js). This would require no changes whatsoever to any Go code, but it might not be the most robust long-term solution.
2. Server side: Assuming we want to keep Gubernator links, in Plank's config, a spyglass url template would need to be added, similar to `job_url_template` (#8831). This would probably also require changing the API ([ProwJobStatus](https://github.com/kubernetes/test-infra/blob/master/prow/apis/prowjobs/v1/types.go#L220)).

/cc @stevekuznetsov

**Comment by krzyzacy** [comment]
@ibzib there's https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/static/script.js#L768 you can use..

in the long run we need to resolve https://github.com/kubernetes/test-infra/issues/8831
