### ISSUE TITLE
planter should respect $HOME/.bazelrc

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9343]
we no longer bind mount `$HOME:$HOME`, but this means the users's global bazelrc is not respected.

current workaround should be `DOCKER_EXTRA="-v $HOME:$HOME"  planter.sh ...`

/area planter
/kind bug
/assign
cc @ixdy

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

this should be easy enough to fix
/priority backlog

**Comment by BenTheElder** [comment]
/assign @amwat 
to investigate this and/or close it

**Comment by amwat** [comment]
Bazel looks for `.bazelrc` in other locations as well: https://docs.bazel.build/versions/master/guide.html#bazelrc 

I would say, unless we want to natively support this complete ordering, it's fine to expect users to mount a specific `.bazelrc` and pass it as `--bazelrc`.
