### ISSUE TITLE
pr dashboard: bugged label diff

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9349]
one of my k/k PRs seems to not be showing one of the required labels as missing
<img width="1318" alt="screen shot 2018-09-11 at 9 16 14 pm" src="https://user-images.githubusercontent.com/917931/45401946-fb2f2f80-b607-11e8-9540-2723cd7c2dae.png">

/kind bug
/area prow
/area prow/deck

**Comment by qhuynh96** [comment]
I just read the issue again I found out the offline discussion with you was something else. What is wrong with this?

**Comment by BenTheElder** [comment]
`priority/critical-urgent` is not a label on the PR, but it's not listed in the missing labels, it's only listed in the required set, AFAICT.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/68438 is the PR

**Comment by qhuynh96** [comment]
> but it's not listed in the missing labels, it's only listed in the required set

you meant it should not be listed in the missing labels? as I see there is `priority/critical-urgent` in the `required labels (missing)`

**Comment by BenTheElder** [comment]
I forgot we have multiple queries, the real bug is that one of those sets of labels is for a different branch or milestone and we should make that clearer.

**Comment by BenTheElder** [comment]
we should probably also expand the "query details" bit

**Comment by qhuynh96** [comment]
Yeah, that's what I am guessing when I see there are two queries for k/k in Tide page. Tide page does not have further info neither

**Comment by BenTheElder** [comment]
yeah this is basically a dupe of https://github.com/kubernetes/test-infra/issues/9335 now, closing
