### ISSUE TITLE
kubernetes-verify-master jenkins job to use gradle

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#935]
The kubernetes-verify-master jenkins job could possibly be made faster with Gradle (or so it claims)

> This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.5/userguide/gradle_daemon.html

**Comment by spxtr** [comment]
Gradle suggests not using it for CI, plus it's only ~1 minute total on that step. Maybe we should turn on whatever the right environment variable is to suppress the warning?

> As it is not recommend to use the Daemon for Continuous Integration builds, Gradle will not emit the message if the CI environment variable is present.
