### ISSUE TITLE
Create a new command /remindme

### ISSUE THREAD

**Issue by akutz** [kubernetes/test-infra#9356]
I would like to propose creating a new command called `/remindme DURATION` where `DURATION` is a pattern `\d+[hdw]`. This new command would cause Prow to add a comment to an existing issue (or PR) after the specified duration of hours, days, or weeks. For example, if there is an issue that someone wants to be reminded to look at in eight hours, they could add a comment to the issue `/remindme 8h`. After eight hours Prow would add a new comment to the issue `reminder @akutz` (or the person who issued the `/remindme` command.

I am curious if others view this proposal in the scope of Prow, or if it's something better left to a broader Github enhancement.

cc @clintkitson

**Comment by BenTheElder** [comment]
This could be implemented in an external plugin with it's own state management. The core of prow is not well equipped to handle this, but an external plugin can handle incoming github events and do ~ anything.

**Comment by nikhita** [comment]
There is an issue for this already: https://github.com/kubernetes/test-infra/issues/8587

cc @cblecker

**Comment by stevekuznetsov** [comment]
Closing as dupe
/close
