### ISSUE TITLE
prow config: enforce presubmit ownership

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9358]
We should consider enforcing that presubmits for `orgfoo/repobar` are in `config/jobs/orgfoo/repobar/...` so we know that `OWNERS` for these jobs are manipulating them.

Currently `OWNERS` for `my-random-org/my-small-project` could theoretically add a blocking presubmit to `kubernetes/kubernetes` (accidentally due to bad copy paste, or intentionally for whatever reason). This is only prevented at the moment due to `testgrid/config.yaml` owners, which is more accidental than intentional.

Doing this would have the upside that finding the config for a presubmit becomes regular and predictable.

We might also want to consider this for postsubmits.

Previously discussed with @krzyzacy and @fejta.

cc @cjwagner @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Do we want this as third-party validation or enforced on config load?

**Comment by stevekuznetsov** [comment]
Pre- and Post-submit SGTM

**Comment by BenTheElder** [comment]
I'm not sure, initially I was thinking `.config/tests` or similar since I'm not sure everyone wants this, but it might be reasonable... @munnerz any thoughts?

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
ping @krzyzacy @fejta

**Comment by fejta** [comment]
Typically we wait until a hypothetical problem becomes an actual problem (or the threat justifies preemptively addressing it). 

I don't see this as a priority.

**Comment by BenTheElder** [comment]
in every other part of the project, the owners heirarchy is actually meaningful as far as what that code does, in test-infra the heirarchy is entirely cerimonial.

I don't see it as a priority either, but we should consider it eventually. I think it's more likely to happen by mistake than anything malicious, but someone hacking on like, kubeflow jobs should not need to worry about their bad copy paste putting a bad presubmit into k/k instead, and we could be enforcing that mechanically to avoid it.
