### ISSUE TITLE
plugin to block "fixes #123" in commit messages

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9360]
this causes issues to repeatedly close when people merge into their forks, we should build a plugin to add a `do-not-merge/*` label to PRs that contain these types of strings in their commit messages

per discussion with @liggitt 

/sig contributor-experience
/sig testing
/area prow
/kind feature
cc @cjwagner @stevekuznetsov 

This is similar to the merge commits blocker https://github.com/kubernetes/test-infra/issues/5376

**Comment by guineveresaenger** [comment]
Can we explicitly list which types of strings?

**Comment by nikhita** [comment]
> preventing nick mentions in commit descriptions would be a boon to anyone who gets a hundred emails when a commit mentioning them gets pulled into all the various forks of a repo

+100. Let’s please make this happen!

**Comment by nikhita** [comment]
@BenTheElder Re nick mentions: would this also mean that we would need to forbid @ mentions in the main PR body?

I think tide does not add the whole PR body in the merge commit message so this should not be needed but I'm not sure.

**Comment by BenTheElder** [comment]
We do not add the PR body anymore IIRC @cjwagner to confirm.

**Comment by spiffxp** [comment]
We do not
```
spiffxp@spiffxp-macbookpro:kubernetes (master %)$ git log --merges
commit 45c5ddd2fb8f10e097483257663fa6a7be59ffa9
Merge: 7bfd0d358c 55199a04be
Author: k8s-ci-robot <k8s-ci-robot@users.noreply.github.com>
Date:   Tue Sep 11 13:27:50 2018 -0700

    Merge pull request #68494 from k82cn/k8s_67606_2

    Added default tolerations for new pods.

```

**Comment by stevekuznetsov** [comment]
Both suggestions SGTM
/help

**Comment by nikhita** [comment]
I'll take a dab at this.

**Comment by nikhita** [comment]
Created a PR: https://github.com/kubernetes/test-infra/pull/9387

/remove-help

**Comment by jberkus** [comment]
Hey, looks like @nikhita is tackling the "invalid commit message", but NOT the "remove 'fixes'" issue.

Does anyone want to take on removing "fixes" statements?  I'm having to reopen failing test issues all over the place now ...

**Comment by cjwagner** [comment]
> I'm having to reopen failing test issues all over the place now ...

@jberkus Is that from "fixes" statements in commit messages or just in the PR body text?

**Comment by nikhita** [comment]
>  looks like @nikhita is tackling the "invalid commit message", but NOT the "remove 'fixes'" issue.

The PR also tackles the "fixes" issue in commit messages. But I probably won't have time to complete the PR this week. :(
