### ISSUE TITLE
Improve welcome message template

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes/test-infra#9367]
Test-infra repo has the beginning of a a welcome message rollout, as worked on in [this issue](https://github.com/kubernetes/test-infra/issues/3083). 

We want to make sure the template for the welcoming message is useable across k/repositories.

Some content should include:

- information on automation, specifically command strings
- useful, updated links to where to find help
- information from here: https://github.com/kubernetes/test-infra/issues/9360

- comments welcome!

**Comment by guineveresaenger** [comment]
/sig test-infra
/sig contribex
@shubheksha 
@BenTheElder 
@cblecker

**Comment by BenTheElder** [comment]
Yeah :-) we just need to figure out what to post and then we can start rolling it out to other repos 😄

**Comment by BenTheElder** [comment]
All of the above SGTM. Definitely links to contributor guides. If we could get repos to standardize on a location for a contributing doc we could even link to the repo's local doc (which can link upstream as necessary)

**Comment by nikhita** [comment]
> If we could get repos to standardize on a location for a contributing doc we could even link to the repo's local doc 

Should be possible in a few weeks when all PRs mentioned in https://github.com/kubernetes/steering/issues/28 get merged. :)

**Comment by guineveresaenger** [comment]
Okay, thanks everyone, I'll take a look at this. It might be tomorrow though, because I'm feeling sick today.

**Comment by nikhita** [comment]
> It might be tomorrow though, because I'm feeling sick today.

Take your time and get well soon! :heart:

**Comment by BenTheElder** [comment]
+1 feel better! We've taken plenty of time for getting this out already with no rush, it can wait for you to get better :-)

**Comment by BenTheElder** [comment]
Cc @carolynvs https://github.com/kubernetes-incubator/service-catalog/issues/1969#event-1852941315 reminded me

**Comment by carolynvs** [comment]
Ooh, thanks for @'ing me! 💖 I would love to have control over a reply to new contributors:

* My SIG's contributing needs a lot of work, but at least it's in the right place (root of repo). For example, we don't do a few key things:
  * Link to a PR that gets it right
  * Link to our dev guide, we have a done of in-depth info on how to build and test various things.
  * Explain better what needs to be in a PR, beyond "docs" or "tests". In most areas, we have common things we doc or test,
  * Say if we prefer people to merge or rebase after conflicts, respond to feedback in new commits, or squash for log history clarity, etc.
  *  Explain our preference for PR scope, and that we encourage follow-on PRs for certain types of feedback over getting a PR "perfect".
  * Encourage people to join our slack channel and SIG meetings.
* Link to how to "talk to prow", and link to the new contributor playground as a great place to practice where no one will see or care if you mess up. Say that it's okay if they mess up on this PR too, and that it's not possible to break it or accidentally ruin stuff.
* Say how to best get help, i.e. asking in a comment (no one ever sees these unless they were already on the issue), vs @'ing a specific person (gets lost in email), vs applying a label with prow (not sure if that's possible but that would be rad), asking in slack channels (ineffective), DMing a specific person (boo), etc. Each repo could decide how they would prefer people reach out to them.
* Explain how and when to "bump", if they need to hunt down an approver themselves, or it's okay to rely 100% on whatever the bot suggests. Suggest how long they should expect someone to do a review, and how long in general PRs take to get finished. Basically set expectations up-front so people don't wonder.
* Provide next steps for what they may want to do after the PR is closed/merged. Maybe just a link to how to find more help wanted issues (in case they came in through other means, and aren't aware of them).

**Comment by guineveresaenger** [comment]
thanks for your input @carolynvs!

**Comment by guineveresaenger** [comment]
I'm wondering, since we're moving towards a configurable welcome message in #9507 - should each repo have their own welcome template file? Currently the default message is just an inline string.

**Comment by cblecker** [comment]
I think we should have a default for the kubernetes project (all our active orgs), but then we can allow repos to customize it if they want something specific.

**Comment by guineveresaenger** [comment]
I completely agree. This is more a question of how we organize this configurability. Where do these templates live? In each repo, top level? Or here in prow? Should the default template live in the "welcome messages" folder as its own file? :)

**Comment by guineveresaenger** [comment]
@ shubheksha there is only `prow/plugins.yaml` and it's a short one-liner AFAIK

**Comment by BenTheElder** [comment]
I like having it in prow config because then I can trivially ensure someone like @cblecker (ok so someone _exactly_ like...) can verify these before Prow starts leaving comments with them.

**Comment by BenTheElder** [comment]
Alternatively a repo like k/org would make sense, but I think something like that for prow config is a longer (nearer?) term goal.

**Comment by shubheksha** [comment]
I think having it in the prow config makes sense from a long-term perspective, having it in a central place can get chaotic

**Comment by cblecker** [comment]
Since https://github.com/kubernetes/test-infra/pull/9507, we have the ability to write a default message for the org, and then repo-specific messages. We just need someone to write a default, and then communicate out to everyone about how they can write their own.

/help-wanted
cc: @parispittman @Phillels

**Comment by BenTheElder** [comment]
poke 🙃

**Comment by nikhita** [comment]
/assign

I'll try to shepherd this in the next couple of weeks.

**Comment by nikhita** [comment]
@guineveresaenger Yeah, the first thing I was going to do was ping you and @carolynvs about this. :)

Will follow up next week. :+1:

**Comment by nikhita** [comment]
Done in https://github.com/kubernetes/test-infra/pull/11325. Thanks a LOT, @guineveresaenger! :sparkling_heart:
