### ISSUE TITLE
testgrid sig-release-master-update descriptions incorrect

### ISSUE THREAD

**Issue by tpepper** [kubernetes/test-infra#9378]
In `testgrid/config.yaml' there is a section for "name: sig-release-master-upgrade".  A number of the "description:" sections here explicitly state version numbers such as "1.10".  For example:
```
   - name: gke-gci-new-gci-master-upgrade-cluster-new
     test_group_name: ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new
     description: Upgrade master and node, in gke(gci), from 1.10 to master, and run skewed e2e tests
```
This description shows for example in a mouse hover help text on testgrid's web ui and is misleading.

As of  https://github.com/kubernetes/sig-release/pull/292 we have a document describing the test naming scheme and referencing `ci/latest`, `ci/k8s-beta`, `ci/k8s-stable${N}` version strings.  I wonder if it would be more informative to have those strings used for the `from` and `to` version in the description?

**Comment by BenTheElder** [comment]
:100: the skew between test names and what they show up as on testgrid can be very confusing

I've also discovered is that testgrid can actually handle arbitrary strings for the test name, so you can write a short, human readable name in any format EG https://k8s-testgrid.appspot.com/conformance-all#GCE,%20master%20(dev) to go with the detailed description

**Comment by tpepper** [comment]
YES!!! 💯 having that tool tip on mouse hover actually be a paragraph describing the test could be hugely useful.

**Comment by krzyzacy** [comment]
hummm gahhh my [hack script](https://github.com/kubernetes/test-infra/blob/master/experiment/fix_testgrid_config.py) doesn't update comments
/shrug
/assign

**Comment by krzyzacy** [comment]
actually the name of the job is...
I'll untouch it to keep the job history during the release, and bikeshed afterwards...

**Comment by spiffxp** [comment]
Something to consider as we look to ensure release jobs are consistent ref: https://github.com/kubernetes/test-infra/issues/9363

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/milestone v1.14
ref: https://github.com/kubernetes/sig-release/issues/347

**Comment by spiffxp** [comment]
/milestone v1.15
ref: https://github.com/kubernetes/test-infra/issues/11977

**Comment by alexbrand** [comment]
I'd like to help out with this. 

Is the ask here to update the test descriptions to use `ci/latest`, `ci/k8s-beta`, `ci/k8s-stable${N}` version strings instead of hard-coded versions?

**Comment by spiffxp** [comment]
/close
AFAICT these dashboard tabs no longer exist
