### ISSUE TITLE
Alert for boskos pool

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9383]
we should alert when the main pool (gce, gke) volume is lower than ~25%, I'll poke around when I have time.

cc @BenTheElder 
/area boskos
/assign

**Comment by krzyzacy** [comment]
cc @cjwagner - do we ever set up other alerts from velodrome? They support email or slack, I'll probably hook it up with #testing-ops channel, and do we have a slack token stored somewhere?

**Comment by krzyzacy** [comment]
/remove-lifecycle stale
will get to that some day....

**Comment by krzyzacy** [comment]
AFAIK we'll move to prow's monitoring stack

**Comment by ixdy** [comment]
What's left to be done now that Boskos is using the Prow monitoring stack (#15344)?

**Comment by cjwagner** [comment]
> What's left to be done now that Boskos is using the Prow monitoring stack (#15344)?

Once we have some data from the new metrics we'll be able to pick an appropriate alert threshold and add prometheus alerts like the ones defined in this dir: https://github.com/kubernetes/test-infra/tree/master/prow/cluster/monitoring/mixins/prometheus

**Comment by BenTheElder** [comment]
isn't this done @cjwagner ?

**Comment by ixdy** [comment]
Yeah, I think we can call this done:
https://github.com/kubernetes/test-infra/blob/47050c4743c0381165543bcc587a3094c2c5c179/prow/cluster/monitoring/mixins/prometheus/boskos_alerts.libsonnet#L4-L28
We even had [an alert](https://kubernetes.slack.com/archives/C7J9RP96G/p1581614640143300) last week for a resource type we'd deleted but which was still being tracked by Boskos.

/close

**Comment by ixdy** [comment]
also x-ref #15412
