### ISSUE TITLE
gubernator triage: 0 clusters of 0 failures out of X builds

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/test-infra#9388]
We have failure on the gubernator triage where opening the page https://storage.googleapis.com/k8s-gubernator/triage/index.html results messgae along the lines of 

```
0 clusters of 0 failures out of 75248 builds from 02/09/2018, 14:56:54 to 11/09/2018, 06:10:46.
```

I started seeing this quite recently, and it basically makes a very useful tool, unavailable
As the CI Signal for 1.12, i use it quite regularly to triage test failures.

**Comment by BenTheElder** [comment]
triage is stuck. https://github.com/kubernetes/test-infra/issues/9271
closing as a dupe
