### ISSUE TITLE
kops wants the bots - or do we

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/test-infra#939]
Pretty please ... how do we get them?  How can kops use the bots to make kops better?

We are using travis ci btw, but not running e2e.

https://github.com/kubernetes/kops/issues/741

**Comment by spxtr** [comment]
Check out https://github.com/kubernetes/test-infra/blob/master/prow/jobs.yaml, https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/bootstrap-pull.yaml#L56-L59, and https://github.com/kubernetes/test-infra/blob/master/jobs/pull-charts-e2e.sh for examples.

The documentation isn't very thorough since it's a fairly new system, but we hope it's not too tough to use.

**Comment by chrislovecnm** [comment]
@balajismaniam can you assist with this?  What do we need for more bot / munger integration?  We have CLA's checked, but we probably need more usage.

**Comment by spxtr** [comment]
What would you like? We can currently run tests for you and run a couple commands, with more to come.

**Comment by chrislovecnm** [comment]
@spxtr you know more than me ... what would improve the developer experience??

**Comment by balajismaniam** [comment]
@chrislovecnm In https://github.com/kubernetes-incubator/node-feature-discovery, we run our own instance of the merge-bot/mungers. Since this repo is a part of Kubernetes org, can u check with Google folks whether they can run the merge-bot/mungers on this repo as well?

**Comment by chrislovecnm** [comment]
@spxtr / @zmerlynn can we get the auto LGTM merge into master automatically?  kops is only running a master branch, so we don't have to worry yet about backporting / cherry picking.  Also auto assign PRs :)

**Comment by zmerlynn** [comment]
I don't have a lot of experience setting up a separate submit queue instance, but that's what we would need for part of this request (presumably).

**Comment by zmerlynn** [comment]
We also at some point need to add the PR builder and Travis to the protected branch list for this repo (https://developer.github.com/v3/repos/branches/#update-required-status-checks-of-protected-branch)

**Comment by chrislovecnm** [comment]
@zmerlynn @spxtr how do we get the bots to merge PRs into master.  I just borked the master again, because a PR was not passing CI.  Would like where a bot does the merge, and not a human.

**Comment by zmerlynn** [comment]
I have no idea how to multi-instance the submit queue. Why did you merge a PR that wasn't passing CI? :)

**Comment by zmerlynn** [comment]
(the PR builder here should be working just fine now, it looks like)

**Comment by chrislovecnm** [comment]
@zmerlynn cause I messed up. Human <- last time I checked.  But admittedly I would like technological help to do that.

**Comment by zmerlynn** [comment]
Actually, as a dirt simple fix, I can figure out how to add Travis and the PR builder to the required checks and make this a ("protected" branch)[https://github.com/blog/2051-protected-branches-and-required-status-checks]. Then you have to override the protection to merge (if you're a maintainer), which is an in-your-face way to stop human error.

**Comment by chrislovecnm** [comment]
@zmerlynn how do we go to the next step? When we have a /LGTM and everything is green, for instance Travis, the bots can pick up the PR and merge it automatically?

**Comment by chrislovecnm** [comment]
@zmerlynn also can the bots auto-assign the PRs?

**Comment by zmerlynn** [comment]
We can add the auto-assign munger pretty easily, IIRC. With a somewhat slow volume, again, it's debatable how useful it is - in the k8s repo the bot assignments are pretty haphazard and there's some amount of hot-potato after initial assignment.

As for auto-merge, it is possible to multi-instance the submit queue, but someone has to do the work. It's an additional deployment in the SQ deployments dir, and fiddling with the options there.

**Comment by chrislovecnm** [comment]
I think it will work fine for kops, we need to start spreading the PR load around, as I have been handling most of it ... 🙊 

Let me know if I need to do anything @zmerlynn

**Comment by zmerlynn** [comment]
The munger that assigns PRs should be doable pretty easily. I can take a look later this week.

**Comment by fejta** [comment]
Feel free to reactivate https://github.com/kubernetes/kops/issues/741 if this is still needed/wanted.
