### ISSUE TITLE
Spyglass should handle pod log not available in a more graceful way

### ISSUE THREAD

**Issue by paulangton** [kubernetes/test-infra#9390]
Current behavior: Displays "Failed to read log, is it compressed?"
Should display something like "pod log no longer available, go to main page for this job?"

/kind feature
/area prow/spyglass
/cc @ibzib

**Comment by stevekuznetsov** [comment]
Can we gracefully expose a single URL that checks for both pod logs and GCS at the same time and chooses which to serve depending on which is available? Always favoring GCS.

**Comment by BenTheElder** [comment]
That was the original intention of the build-log.txt artifact IIRC...
I definitely think we should just have an access point that looks for both and prefers not-pod-logs.

**Comment by BenTheElder** [comment]
@ibzib mind updating? 🙃

**Comment by ibzib** [comment]
Current status on this is it behaves a bit better -- both the `view/gcs` and `view/prowjob` endpoints try to fetch logs from both pods and GCS, and errors are more helpful -- but we still want a more sophisticated way of dealing with `build-log.txt`. See https://github.com/kubernetes/test-infra/pull/10772
/close
