### ISSUE TITLE
Spyglass should be runnable locally

### ISSUE THREAD

**Issue by ibzib** [kubernetes/test-infra#9391]
Currently, Spyglass is initialized in [prodOnlyMain](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/main.go#L183). To make developing UI features easier, it should be possible to run Spyglass locally (with GCS but without the Prow client).

/cc @BenTheElder @paulangton @krzyzacy

**Comment by BenTheElder** [comment]
/assign @paulangton @ibzib 
/area prow/spyglass
/area prow/deck
/area prow
/kind enhancement
see also: https://github.com/kubernetes/test-infra/issues/6698

**Comment by paulangton** [comment]
Potentially related to running spyglass as a separate deployment (which I still have not created an issue for)
