### ISSUE TITLE
pr status seems to put "In Pool - Test failed/Missing Labels" when tide is retesting

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9413]
I'm pretty sure the PR didn't fail and isn't missing labels but it has "In Pool - Test failed/Missing Labels" as the status

![image](https://user-images.githubusercontent.com/917931/45581407-2907b480-b852-11e8-9598-40d3d2c3e3f7.png)

/kind bug
/area prow
/area prow/deck
cc @qhuynh96 @amwat

**Comment by BenTheElder** [comment]
it later switched to "In Pool - In Batch & Test Pending" fwiw

**Comment by stevekuznetsov** [comment]
Sounds like we could use some unit tests for that JS logic :grimace:

**Comment by BenTheElder** [comment]
@Katherine was planning to propose modernizing the JS hopefully

**Comment by qhuynh96** [comment]
The `In Pool - Test failed/Missing Labels` label appears when the PR falls into `pool.MissingPrs` category. Is there any reason, except test failed/ missing labels, that makes a PR falls into `pool.MissingPrs`?

**Comment by BenTheElder** [comment]
@cjwagner for tide ^

**Comment by cjwagner** [comment]
> The `In Pool - Test failed/Missing Labels` label appears when the PR falls into `pool.MissingPrs` category. Is there any other reason, except test failed/ missing labels, that makes a PR falls into `pool.MissingPrs`?

I think there is confusion about how Tide categorizes PRs. The category names are somewhat vestigial which doesn't help.
`pool.MissingPrs` contains PRs that are in the pool, but are missing up to date test results (i.e. the prowjobs were GCed or invalidated by another PR merging). It **never** contains PRs that fail tests or are missing labels.

In fact `Test failed` and `Missing Labels` don't make sense for *anything* in the pool including PRs in `MissingPrs`. If a PR fails required tests it is removed from the pool. If a PR does not meet label requirements it is removed from the pool.
`Test failed` and `Missing Labels` should only ever apply to PRs that are not in the pool.

**Comment by cjwagner** [comment]
> I would renamed it to In pool / Queued for retest to match tide page. WDYT?

SGTM, +1 for using consistent phrases across pages.
