### ISSUE TITLE
path_alias docs are misleading

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9415]
the prod podutils docs talk about `path_alias` as if you can configure an alternate `/go/src/...` path for the job, but really you can configure an alternate _go import path_ for the cloned repo, which will actually be in `/home/prow/go/src/${path_alias}`. 

Currently the docs read as if it will be in `$path_alias`, and they mention `/go/src` when it's now `/home/prow/go/src`

/area prow
/kind documentation
/assign

**Comment by stevekuznetsov** [comment]
The doc is 

```go

	// PathAlias is the location under <root-dir>/src
	// where the repository under test is cloned. If this
	// is not set, <root-dir>/src/github.com/org/repo will
	// be used as the default.
	PathAlias string `json:"path_alias,omitempty"`
```

I was hoping it would be obvious `<root-dir>/src` is not changed and this only affects the location under that -- how to improve that?

**Comment by BenTheElder** [comment]
(for anyone following along see discussion in https://github.com/kubernetes/test-infra/pull/9416, this meant to refer to the markdown docs, not the go docs)
