### ISSUE TITLE
Prow: lint shell file mode

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9417]
Shell scripts should be marked executable... 🤦‍♂️

**Comment by stevekuznetsov** [comment]
/area prow
/kind feature

Are you suggesting a plugin? Or a presubmit job?

**Comment by BenTheElder** [comment]
I'm not sure, I'd have to check how cheap it is to do via the API. A presubmit might be a little heavyweight for just "if a *.sh is created make sure the file-mode is at least exec for the user..." and currently at least plugins are easier to add to many repos.

If not, probably just another verify script that we copy all over /shrug

**Comment by anwaradil** [comment]
Is help still needed with this issue?

**Comment by BenTheElder** [comment]
Yes, nobody has taken this on yet.

We have a couple options here, but basically we should come up with something cheap that lets us verify that shell files are actually exec.

It's not super important, but it might help catch some bugs.

**Comment by anwaradil** [comment]
I can work on it. What files should I look at in the repo? if you can give me some more information that would be great :)

**Comment by BenTheElder** [comment]
so either we should:
- create a new re-usable prowjob (https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#writing-a-prowjob-that-uses-pod-utilities) that does this
- or create a plugin for prow/hook (https://github.com/kubernetes/test-infra/tree/master/prow/plugins#plugins) that can be enabled to do this, the [`golint`](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/golint) plugin might be a starting point for that route

**Comment by matthyx** [comment]
@anwaradil have you already worked on that issue? do you need help? should I do it?

**Comment by anwaradil** [comment]
@matthyx I have not started working on this. Please feel free to grab it. I appreciate your help.

**Comment by matthyx** [comment]
@BenTheElder how about using the [trees](https://developer.github.com/v3/git/trees/) API?
example: https://api.github.com/repos/kubernetes/test-infra/git/trees/83ada8bbc0f8a3cbd860037b6f5dc7e67a37afd6

If I can find the top dir sha, I could create a prow job that loads all files recursively and verify that all that are named like `*.sh` and `*.py` have a mode of `100755`?

**Comment by BenTheElder** [comment]
> I can find the top dir sha with [refs](https://api.github.com/repos/kubernetes/test-infra/git/refs), and then create a prow job that loads all files recursively and verify that all that are named like `*.sh` and `*.py` have a mode of `100755`?

Probably we could just skip to always creating a prow presubmit then? Not sure what the trees API is solving? 🤔

**Comment by matthyx** [comment]
> Not sure what the trees API is solving?

It allows to see all files from the repo, along with their mode:
```
    {
      "path": ".bazelrc",
      "mode": "100644",
      "type": "blob",
      "sha": "9ecf28fe4d8d3ac5da8104d79b787c09ad4f0fb9",
      "size": 511,
      "url": "https://api.github.com/repos/kubernetes/test-infra/git/blobs/9ecf28fe4d8d3ac5da8104d79b787c09ad4f0fb9"
    },
```

**Comment by BenTheElder** [comment]
Ah I see.
A ProwJob can also just checkout the repo and list the files though? A re-usable prowjob config might be simpler and avoid extra API token usage.

With the podutils the config for this could probably be just a few lines if we published the linter in an image.

**Comment by matthyx** [comment]
I can create a new hook, pretty much like I did with `verify-owners` but do we want one just for file permissions?

**Comment by matthyx** [comment]
Alright, lemme investigate your page (https://github.com/kubernetes/test-infra/blob/master/prow/pod-utilities.md#writing-a-prowjob-that-uses-pod-utilities)

**Comment by matthyx** [comment]
I can use the alpine image and simply find those files with a `find` shell-fu like that:
```
~/workspace/go/src/k8s.io/test-infra$ find . -name "*.sh" \! -perm /a+x -ls
  3015645      4 -rw-rw-r--   1 mbertsch mbertsch     1298 Jan  9 10:05 ./planter/install-bazel.sh
  3015081      4 -rw-rw-r--   1 mbertsch mbertsch     1858 Jan 28 08:15 ./experiment/kind-coverage-dump.sh
  3015440      4 -rw-rw-r--   1 mbertsch mbertsch     1312 Jan  9 10:05 ./images/kubekins-e2e/install-bazel.sh
```

**Comment by matthyx** [comment]
How do you report errors with prowjobs? Is it just a matter of returning a non-0 code?

**Comment by BenTheElder** [comment]
Non-zero return code and ideally some output in the log identifying what is
wrong.

Depending on the complexity it might be worth packaging a small program
into a tiny image so the prowjob can just be setting the image and command.

**Comment by matthyx** [comment]
Ok, ideally it would reside in `config/jobs/kubernetes/test-infra/test-infra-presubmits.yaml` ?

**Comment by BenTheElder** [comment]
yes :+1:, thanks!
