### ISSUE TITLE
DecorationConfig needs to be able to configure known_hosts

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#9440]
Not clear to me how pod-utils can actually use ssh to clone a repo. I am seeing everything fail along the following lines:

```console
$ git fetch git@some-git-server:wee --tags --prune
Host key verification failed.

fatal: Could not read from remote repository.
```

/area prow/pod-utils

**Comment by fejta** [comment]
Most likely this should be something like an `ssh_fingerprints` field to go along with `ssh_key_secrets`

https://github.com/kubernetes/test-infra/blob/c066e84da64cabe0af3fcb6877493c86dc767492/prow/apis/prowjobs/v1/types.go#L168-L170

and then wire this through everywhere

`ssh-keyscan -t rsa -H whatever` will generate the file, which can then be added to `~/.ssh/known_hosts`

https://superuser.com/questions/421074/ssh-the-authenticity-of-host-host-cant-be-established

**Comment by stevekuznetsov** [comment]
This was fixed in the linked PR 

/close
