### ISSUE TITLE
Add support for `-repo:foo/bar` to tide queries

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9451]
So we can set a less restrictive org-wide policy for kubernetes, but exclude kubernetes/kubernetes so that it can have a more restrictive query

We could do this via a new field, ie: specify `excludedRepos` similar to `excludedBranches`/`includedBranches`

We could try making tide do this itself, ie: scan other queries for repos, exclude them from the current query if it has an org that overlaps with that repo

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/pull/9342 we didn't have a check to prevent us from merging a PR with overlapping tide queries

if we implement the explicit approach, we should consider adding such a check; if we make tide's query generator smart, we could avoid it

**Comment by spiffxp** [comment]
WDYT @BenTheElder @cjwagner @stevekuznetsov 
/area tide
/sig testing
/priority important-soon
priority mostly because I want to stop having massive lists of repos in our queries

**Comment by cjwagner** [comment]
👍 We already do this for `branch:` and `-branch:` tags.  I tried some queries that include `org` and `-repo` in the front end search UI and they behaved as expected. This would be particularly nice for setting org wide merge requirements for the kubernetes org except for the k/k repo.

Disallowing overlapping queries would limit functionality. GitHub search doesn't have an `OR` for label requirements so unioning query results from potentially overlapping queries is necessary.

**Comment by stevekuznetsov** [comment]
>  priority mostly because I want to stop having massive lists of repos in our queries

What's the real issue with this? Looking at the trade-off of `tide` implementation complexity versus length of a config file ... I think I might want `tide` to be simple and stupid and the config to be hard.

**Comment by stevekuznetsov** [comment]
SGTM
