### ISSUE TITLE
clonerefs needs to require a non-empty clone_uri

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#9462]
Magically filling in this value with `https://github.com/{{.Org}}/{{.Repo}}.git` leaks potentially private and/or high value information to github on any misconfiguration. Therefore is an unsafe default.

Plank, Gerrit or whatever controller creates the prow job has a duty to furnish valid clone_uris. We should update plank to auto-populate this field (which will make this a noop for users/admins).

At this point we update clonerefs to blow up whenever any refs have an empty clone_uri field.

/cc @stevekuznetsov @cjwagner @munnerz 

/area prow

**Comment by cjwagner** [comment]
Just to be clear, you aren't suggesting getting rid of the `https://github.com/{{.Org}}/{{.Repo}}.git` default, you just want to move it into plank so that we only apply it to jobs with `agent: kubernetes` (or an omitted `agent` field since the value defaults to `kubernetes`)?

**Comment by stevekuznetsov** [comment]
Also unclear to me what the ask here is -- validation for the configuration that the field is non-nil? If you've added a `kube.Refs` with the org and repo, how is it unsafe to take those public values and use them in a template string?
