### ISSUE TITLE
Podutils: options to activate a service account for entrypoint?

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9471]
I can see it as a pretty common use case, like, I want to have a job that build & push a docker image. (it will break a few bootstrap jobs.) thoughts?

cc @cjwagner @BenTheElder @stevekuznetsov

**Comment by BenTheElder** [comment]
`runner.sh` ? /shrug

pod-utils is probably best kept focused and generic. GCP service accounts seem like a GCP thing :-)

not super strongly opinionated on this one though. if we all want to support this because we all use it, one less thing being done with bash-in-the-job is fine with me..

**Comment by krzyzacy** [comment]
not everyone is using boostrap image though...

**Comment by fejta** [comment]
I don't think entrypoint it should be entry points responsibility. This could just as easily be solved by mounting the creds and/or gcloud state from a secret.

**Comment by krzyzacy** [comment]
I guess if people need this behavior, they can borrow our bootstrap image, which has gcloud installed.

**Comment by stevekuznetsov** [comment]
Is this specifically for a Google Cloud service account? If it's for a k8s `ServiceAccount` in the k8s cluster you can just edit the `PodSpec`, right?

**Comment by BenTheElder** [comment]
GCP. https://github.com/kubernetes/test-infra/issues/9471#issuecomment-422582783

**Comment by stevekuznetsov** [comment]
For something specific like that for a cloud provider, agreed with @fejta and @BenTheElder it should be outside of the pod utilities.
/close

**Comment by krzyzacy** [comment]
I think I'm fine with activate it within our own entrypoint for now :+1:
