### ISSUE TITLE
Gubernator should display estimated time to completion of each test

### ISSUE THREAD

**Issue by foxish** [kubernetes/test-infra#948]
Kubekins appears to show the ETA for each test to finish running. 
Something similar in gubernator, showing how long a test run typically takes, and the timeout would be useful I think.

cc @gmarek @kubernetes/contributor-experience

**Comment by fejta** [comment]
You may now click the build log button for an in progress run to see streaming log info!

**Comment by ixdy** [comment]
@fejta that's not quite what @foxish was asking for; the build log and "estimated time to completion" are not the same thing.

Also IIRC we don't have in-progress build logs for most of our CI jobs yet, though eventually we will.

**Comment by fejta** [comment]
I agree streaming build logs and completion eta are not the same thing. They serve similar needs. And historical durations are also available in testgrid.

We are tracking the migration to prow in other issues. 

This seems more than sufficient to resolve this issue, which has gone unmodified for at least half a year (unknown how long it sat in the contribx repo)
