### ISSUE TITLE
Add a Alpha Enabled [Serial] Test Suite for k8s/k8s

### ISSUE THREAD

**Issue by davidz627** [kubernetes/test-infra#9485]
There is a gap in test suites in that there is no alpha enabled serial test suite that gets run on k8s/k8s.

Gap uncovered here:
https://github.com/kubernetes/kubernetes/issues/68260#issuecomment-422951424

/cc @msau42

**Comment by BenTheElder** [comment]
Assigning sen for general knowledge of these and amwat / cjwagner for 1.12 test-infra. We've had some alpha suites before but they've not really been monitored. is this request for a CI job or presubmit?

**Comment by msau42** [comment]
CI job.  We already have an alpha-enabled-default suite, but they skip serial/slow.  We have some serial tests we want to monitor in alpha env.

I think the alpha-enabled-default suite is useful for catching regressions caught by alpha features

**Comment by msau42** [comment]
I would suggest that once they are stabilized, we add them as a monitored job just like the alpha-features suite

**Comment by krzyzacy** [comment]
feel free add one next to https://github.com/kubernetes/test-infra/blob/master/experiment/test_config.yaml#L1249-L1252?
