### ISSUE TITLE
Spyglass viewer templates should be HTML, not Go source

### ISSUE THREAD

**Issue by ibzib** [kubernetes/test-infra#9488]
1. https://github.com/kubernetes/test-infra/blob/master/prow/spyglass/viewers/buildlog/buildlog_template.go
2. https://github.com/kubernetes/test-infra/blob/master/prow/spyglass/viewers/junit/junit_template.go
3. https://github.com/kubernetes/test-infra/blob/master/prow/spyglass/viewers/metadata/metadata_template.go

These .go files are actually 95% HTML, so they should probably be treated as such.

While I'm at it, I should move viewer-specific JS out of spyglass-template.html and into these new HTML files.

/cc @Katharine @paulangton

**Comment by stevekuznetsov** [comment]
/shrug
This was fairly contentious AFAIR

**Comment by BenTheElder** [comment]
we have first class support for templates in deck now. we might as well toss these in there now . /shrug

**Comment by paulangton** [comment]
Not sure what we want to do now, but the reason before was that we didnt want to serve viewer-specific files with Deck. Keeping them in Go files allowed them to be included in the binary, and allowed viewers to be more or less self-contained.

**Comment by BenTheElder** [comment]
That probably still makes some sense for external viewers once they exist, but with viewers baked into deck it's even more :shrug:

If nothing else we should consider aligning them better with deck's own template tooling and possibly break that out into some common tooling.
