### ISSUE TITLE
amusing spyglass metadata bug

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9494]
<img width="902" alt="screen shot 2018-09-19 at 6 44 51 pm" src="https://user-images.githubusercontent.com/917931/45790929-2cc57d80-bc3c-11e8-9222-a174b93b474e.png">
/kind bug
/shrug
/this-is-fine

/assign @ibzib @paulangton

**Comment by paulangton** [comment]
Working as intended, spyglass occasionally reports a very optimistic runtime as a morale boost to the programmer.

**Comment by paulangton** [comment]
Kidding, interesting bug though
/assign

**Comment by BenTheElder** [comment]
You should have seen the -9 exabytes / second tranfser imaging a laptop the other day 😂 

This is totally benign, but probably worth fixing before we start asking people to try switching all their viewing over :-)

**Comment by stevekuznetsov** [comment]
I think Gubernator had a similar one ... #8339

**Comment by stevekuznetsov** [comment]
(So this is backwards-compatible feature and good job not breaking users with an undocumented change @paulangton)

**Comment by BenTheElder** [comment]
Hah. Now we just need to OOM deck :^)
