### ISSUE TITLE
Spyglass doesn't handle Prow jobs

### ISSUE THREAD

**Issue by ibzib** [kubernetes/test-infra#9502]
1. The current deployment of Spyglass doesn't handle Prow jobs (via /view/prowjob/), which is a regression as it did work in some previous iteration. This seems to be because there's no ArtifactFetcher corresponding to Prow jobs.

2. After the /view/prowjob/ endpoint is fixed, the Spyglass link on Deck needs to be updated as well (I mistakenly hard coded it to /view/gcs/).

/cc @paulangton @krzyzacy @BenTheElder

**Comment by stevekuznetsov** [comment]
We should be a little more careful, we don't have any control over when people roll out changes to `deck`.

**Comment by BenTheElder** [comment]
We should be careful, but people also should **not** depend on spyglass yet, which is why it's still behind a "feature gate"

**Comment by stevekuznetsov** [comment]
Yep, just good habits starting early, all that jazz :)

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-soon
I'd like to try keeping the red priority for things that are breaking/blocking existing workflows
