### ISSUE TITLE
Make kubernetes-cross-build SQ-blocking

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#951]
Now it has been back in business for a while; let's make it queue-blocking.
For example, both https://github.com/kubernetes/kubernetes/pull/35136 and https://github.com/kubernetes/kubernetes/pull/35652 broke the cross-build.
Both was cherrypicked into v1.4, which makes it even more painful.

By having it as a queue-blocking build, it will hopefully be noticed faster and we will not cherrypick it until that has been fixed.
@kubernetes/sig-testing

**Comment by spxtr** [comment]
The first thing to do is to set `always_run` in [jobs.yaml](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.yaml). Once it looks consistently green then we can set it to required in the submit queue.

**Comment by fejta** [comment]
I assume we don't need to do this
