### ISSUE TITLE
jobs that use clonerefs don't provide SHA's in consumable .json files

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9510]
maybe there's a better issue for this, eg: https://github.com/kubernetes/test-infra/issues/7364 or https://github.com/kubernetes/test-infra/issues/3412

eg: https://k8s-testgrid.appspot.com/sig-testing-kind#ci%20build

- `started.json` and `finished.json` just have a `timestamp` field
-  `clone-records.json` at best has:
```
[
  {
    "refs": {
      "org": "kubernetes-sigs",
      "repo": "kind",
      "base_ref": "master",
      "path_alias": "sigs.k8s.io/kind"
    },
#...
      {
        "command": "git checkout FETCH_HEAD",
        "output": "[...]\n\nHEAD is now at 3346ccb... Merge pull request #19 from BenTheElder/patch-run\n"
      },
```
This leaves us with gubernator and testgrid not understanding what commit they should display

What should it be instead? I think at present they look in `metadata.json` for `repo` and `repo-commit`, but it might also be something from `finished.json`

/area prow/clonerefs

**Comment by stevekuznetsov** [comment]
We should just upload the `ProwJobSpec` (or the entire `ProwJob`, or the `Pod`) to GCS, yeah?

**Comment by spiffxp** [comment]
For gubernator/testgrid it is really helpful to know what the refs ultimately resolve to.  Consider the case of an upgrade test, the release team really needs to know what SHA we're upgrading from and to, not just which branches.
