### ISSUE TITLE
Prevent squashable commits from merging

### ISSUE THREAD

**Issue by tallclair** [kubernetes/test-infra#9514]
It's considered a best practice to respond to PR feedback in new commits, so my PRs often end up with a long list of "Address feedback" commit messages. However, I sometimes come into work in the morning to find that the whole PR merged when it was LGTM'd. I do not think the onus should be on the reviewer to catch this situation.

The simplest solution might be a `do-not-merge/needs-squash` label (and associated bot command `/needs-squash`). Ideally the bot would be able to recognize when the PR was squashed and retain the LGTM, but that might be a hard problem to solve, so a simple `/squashed` might suffice. Another optimization might be to add a keyword to the commit message itself. For instance, pushing a commit that starts with `squash:` could automatically add the label.

_aside: I'm disappointed that there isn't a squash emoji_

**Comment by BenTheElder** [comment]
For retaining LGTM on squash see: https://github.com/kubernetes/test-infra/pull/9138
There's a long running effort to enable this, we definitely want that.

I think a `/hold\nHolding so I can squash after review` comment would be functionally equivalent to the `/needs-squash` for the moment at least since both would be socially enforced merge blocking rather than automatically enforced.

Lack of squash emoji I don't have a solution for :-( We could at least add one on slack.

**Comment by tallclair** [comment]
Yeah, using `/hold` was my first thought. My concern is that over-burdened reviewers might see the hold and immediately dismiss the PR as not needing attention. Also, a squash-specific label would make it more clear what needs to happen for the hold to be removed.

**Comment by BenTheElder** [comment]
makes sense, WDYT @cjwagner @stevekuznetsov ?

This also reminded me to look at #9138 which looks almost ready to go now, @cjwagner should we poke that one again?

/area prow
/kind enhancement

`:jack_o_lantern:` = :jack_o_lantern:  appears to be the closest thing to a squash :^)

**Comment by tallclair** [comment]
> `:jack_o_lantern:` = :jack_o_lantern:￼ appears to be the closest thing to a squash :^)

Oh yeah! Good call. I looked up the phylogenetic tree of the :eggplant: to see if it was related to squash (the answer is no).

**Comment by stevekuznetsov** [comment]
Not clear why we would need that `/needs-squash` if we have sticky LGTM for squashes? The reviewer could just drop in the `/lgtm` and leave?

**Comment by tallclair** [comment]
The `/needs-squash` is to prevent the PR from automatically merging after `/lgtm`. Sticky LGTM is orthogonal.

**Comment by matthyx** [comment]
/remove-lifecycle rotten
might work on it once we have the command framework

**Comment by fejta** [comment]
How about if we block multiple commits by default, until an org member whitelists the multi PR for a multi commit merge?

**Comment by stevekuznetsov** [comment]
@tallclair repos can be configured to merge by squashing, and `tide` already supports squashing using the `tide/squash` [label](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml#L641).

**Comment by matthyx** [comment]
/remove-lifecycle stale
@cjwagner any chance you'll finish the command framework?

**Comment by cjwagner** [comment]
Probably not :disappointed:
I think it was a fun idea, but ultimately not something we really need. There have consistently been more useful things for me to work on.

**Comment by matthyx** [comment]
Do you need help on it? I could have a look after done with the configtree...

**Comment by matthyx** [comment]
@tallclair @stevekuznetsov @fejta  I have some time to work on this... so what should be the implementation?
- /needs-squash
- tide performing the squash
- prevent multi-commit PRs from merging

**Comment by tallclair** [comment]
I'm not sure how much more is needed here. We already have `tide/squash` for auto-squash. We could require approval or at least explicit ACK from the owner before merging something with multiple commits.

**Comment by sftim** [comment]
:thought_balloon: Maybe reviewers would like to be able to comment on a PR
```
/lgtm if-squashed
```
It's different to the original suggestion @tallclair; does it work as an approach do you think?

As an approver for the website, where people often contribute entirely within the GitHub web UI, I'd be happy to add:
```
/squash
/approve
```
to website PRs that were labelled `lgtm/if-squashed`.

I can make this its own issue if people like the idea.
