### ISSUE TITLE
Incorrect link in k8s-ci-robot for bot-commands

### ISSUE THREAD

**Issue by geojaz** [kubernetes/test-infra#9528]
![image](https://user-images.githubusercontent.com/9451328/45910399-7db0af80-bdbd-11e8-934f-8a6f8fbfd7b2.png)

It looks like this go.k8s.io link redirects to https://prow.k8s.io/command-help.html which 404s. I think the correct link is https://prow.k8s.io/command-help

**Comment by geojaz** [comment]
![image](https://user-images.githubusercontent.com/9451328/45910692-1a744c80-bdc0-11e8-87f5-de0994d19241.png)

**Comment by BenTheElder** [comment]
Ah, so prow recently switched to templated pages, we should update go.k8s.io to drop the .html from the redirect.

**Comment by BenTheElder** [comment]
/assign @spiffxp 
/remove-help

We're fixing the go link now, sorry about that! This just changed this afternoon, we didn't think anywhere was still linking to .html as we'd been using extensionless links for around a year now
