### ISSUE TITLE
Figure out a way to patch known k8s bugs in tests

### ISSUE THREAD

**Issue by wonderfly** [kubernetes/test-infra#953]
Many tests, notably GKE and GCI's release qual tests, use released versions of k8s instead of some CI build. If a particular k8s is broken, they would have to keep failing until the next release is out and picked up.

To mitigate the churns, GKE tests have been using some hacks like this: https://github.com/kubernetes/test-infra/blob/master/jenkins/e2e-image/e2e-runner.sh#L121, which basically tries to test against the branch head instead of a released version (what they actually what to test).

It would be great if the test-infra allows patch of a downloaded tarball, to fix things like https://github.com/kubernetes/kubernetes/issues/35654

**Comment by fejta** [comment]
Configure the test to call kubetest with `--extract=ci/latest-1.5` to the latest patched version of 1.5, including test fixes.
