### ISSUE TITLE
spyglass styling seems to be broken

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9531]
I'm going to hazard this is related to the deck template changes @Katharine 

current status: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel/705/
<img width="1264" alt="screen shot 2018-09-21 at 10 52 08 pm" src="https://user-images.githubusercontent.com/917931/45913893-0dbc1c80-bdf1-11e8-8ddd-2f45db4b3799.png">

/kind bug
/area prow/deck/spyglass

**Comment by Katharine** [comment]
This is… something.

/assign
