### ISSUE TITLE
Tide dashboard `Merge Requirements` section no longer expands properly.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/test-infra#9538]
The "Merge Requirements" section no longer expands fully and does not scroll: https://prow.k8s.io/tide
Could this have been a regression from the templating changes? I don't see any other problems like this on other Deck pages. 

/kind bug
/cc @BenTheElder @Katharine

**Comment by Katharine** [comment]
This is indeed a templating regression: apparently the tide dashboard's layout breaks if the main container has the ID `#main-container` (which all other pages expect to have). Ugh.

/assign
