### ISSUE TITLE
end DNS flakes

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9555]
Tests flake on connecting to external services. We should minimize how much we depend on these, but we should also deflake DNS. First step was using FQDN for in-cluster services https://github.com/kubernetes/test-infra/pull/9547

TODO:
- [x] investigate options with @MrHohn (and also read all of the k8s dns docs :-))
- [x] use fully qualified domain names for in-cluster services in the build clusters https://github.com/kubernetes/test-infra/pull/9547
- [x] upgrade prow to k8s 1.10.x so we can use `dnsConfig`
- [x] try lowering `ndots` using `dnsConfig` https://github.com/kubernetes/test-infra/pull/9556
- [ ] try rolling this out more broadly
- profit? less flakes? ❄️ 

/area prow
/area jobs
/kind bug
/priority important-soon

/assign
/assign @MrHohn

**Comment by BenTheElder** [comment]
now that we are on 1.10 for prow we can start to leverage `dnsConfig` on some pods :-)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/68932 :eyes:

**Comment by BenTheElder** [comment]
DNS changes in https://github.com/kubernetes/test-infra/pull/9556 look very promising so far -- no discernible network flakes. Will roll out to critical k/k jobs tomorrow.

We may need a better mechanism to set this on all jobs, perhaps extending presets ...? @cjwagner 
 @krzyzacy any ideas? Basically we will want to set [`dnsConfig`](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config) on ~all `agent: kubernetes` job specs. 

Kubernetes has no mechanism for this currently ... cluster level DNS config is only about name servers, which we do not need or want to change. We _could_ just add this to all ~800 jobs but ideally we'd have a preset or some other defaulting mechanism for this.

**Comment by krzyzacy** [comment]
add to defaults, like https://github.com/kubernetes/test-infra/blob/master/prow/config/config.go#L1134-L1169?

**Comment by BenTheElder** [comment]
@krzyzacy it's probably not preferable to hard code this for _all_ prow users.

Side note: there has been _one_ flake since.

**Comment by krzyzacy** [comment]
or once we move to podutils, we can put this to our default decoration config

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/area deflake
@BenTheElder what remains to be done here?

**Comment by BenTheElder** [comment]
it's unclear if our current attempts made a significant difference or not. we probably can't do much more ourselves besides the dnsConfig which also unfortunately makes the jobs more verbose :(

**Comment by MrHohn** [comment]
[NodeLocal DNS Cache](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0030-nodelocal-dns-cache.md) might help with this as well :)
cc @prameshj
