### ISSUE TITLE
scripts and configuration checked into git should not point to production resources by default

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#9572]
To prevent accidentally pushing over production resources (such as prow configuration), we should not point to the production resources by default, or at least should require confirmation before all manual pushes.

**Comment by BenTheElder** [comment]
imo the most useful changes would be:
- debug which cluster is being pushed to
- require manual confirmation of mutations
- consider unsetting any magical cluster options and require specifying which cluster, but also don't use the kubeconfig default..
