### ISSUE TITLE
Merge script to reload prow configuration from scratch and regularly test it

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#9573]
We should fix up and merge https://github.com/kubernetes/test-infra/issues/8892 and probably regularly test it so that we can easily reload all prow configuration if needed.

**Comment by krzyzacy** [comment]
yeah, will get to it when I find another personal hacking session :-)

**Comment by krzyzacy** [comment]
(will revisit https://github.com/kubernetes/test-infra/issues/8892, but the hack version is checked in)
