### ISSUE TITLE
Horologium should not trigger periodic jobs when they are added to the config if there is a ProwJob record for a run that occurred recently (within the job period)

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#9575]

**Comment by ixdy** [comment]
(someone with more knowledge about horologium should fill in the details here)

**Comment by krzyzacy** [comment]
I believe that's not the case? Do you have an example?

**Comment by krzyzacy** [comment]
(grab from the other thread:)

an example for a job that's not retriggered during the outage: https://prow.k8s.io/?type=periodic&job=ci-cri-containerd-e2e-gce-multizone
it's just plank wasn't scheduling anything, and suddenly re-scheduled all missed periodic jobs which looks like it retriggered everything.

**Comment by BenTheElder** [comment]
thanks for investigating :-)

/close
