### ISSUE TITLE
`/cherrypick <branch>` doesn't work in k/k

### ISSUE THREAD

**Issue by deads2k** [kubernetes/test-infra#9582]
Can we enable the cherrypick plugin for the CI infrastructure that allows `/cherrypick <branch>` to cause the bot to cherrypick the pull on top of the chosen branch, create a new pull, and assign it.  It's a really handy one to have for maintenance.

@kargakis @stevekuznetsov what's that plugin called?

/cc @dims

**Comment by dims** [comment]
i think it's this one https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/cherrypicker

**Comment by kargakis** [comment]
There is some back n forth in https://github.com/kubernetes/test-infra/pull/7393 but hasn't led to anywhere yet

**Comment by stevekuznetsov** [comment]
IIRC @cblecker had some reservations

**Comment by BenTheElder** [comment]
Yep, I'm open to PRs for this, but there's been so much back and forth I don't think anyone here has had bandwidth to set it up.

**Comment by stevekuznetsov** [comment]
I think #7393 has all the work -- if you want to use a separate bot, someone needs to make it, otherwise that is all?

**Comment by BenTheElder** [comment]
Yes that was the feedback, use fejta-bot or a new token. We don't need to
pile more things on k8s-ci-robot

**Comment by stevekuznetsov** [comment]
Having `k8s-cherrypick-bot` may be clearer, though - we have seen confusion about @fejta-bot before. Would also ensure we don't add any undue token pressure.

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale

What's the blocker here? Creating a new account is simple, right?

**Comment by cjwagner** [comment]
Yes creating a new account is easy.
The contributor experience concerns are the main blocker I think. Thread starts here: https://github.com/kubernetes/test-infra/pull/7393#issuecomment-412167489
