### ISSUE TITLE
Prow issue: Unable to assign issues to people in knative/pkg

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/test-infra#9583]
I believe I'm in this group https://github.com/orgs/knative/teams/knative-users

But prow told me the following

https://github.com/knative/pkg/issues/97#issuecomment-424705175

**Comment by BenTheElder** [comment]
it's referring to the user being assigned, not the person asking to assign someone.

the problem is actually that github will not allow us to assign, prow would be happy to assign anyone :(

if you have any suggestions for clarifying that, they'd be welcome.

**Comment by dprotaso** [comment]
Understood - thanks for the clarification. Also sorry this was meant to be opened against knative/test-infra
