### ISSUE TITLE
Prow's `make get-cluster-credentials` is dangerous

### ISSUE THREAD

**Issue by ixdy** [kubernetes/test-infra#9594]
`make get-cluster-credentials` is convenient if you're using `make` to deploy Prow, but it also silently changes your `kubectl` context to point to production prow, which can [cause outages](https://docs.google.com/document/d/1kwqU4sCycwxfTsV774lnrtFakCg90rMXNShmjSqyEJI/view).

We should see if there's some way to make this less dangerous, or at least make it more obvious that the context has switched.

/area prow

**Comment by BenTheElder** [comment]
I think the entire kubeconfig system is potentially risky when not monitored. one option is making tools print out which context you're using and then requiring confirmation. 

https://github.com/kubernetes/test-infra/blob/9085971b90d82f911f74fa6b6eda0dec81e5b139/experiment/maintenance/recreate_prow_configmaps.py#L103
