### ISSUE TITLE
Add Janitor method to clean up leaked gcr.io images

### ISSUE THREAD

**Issue by davidz627** [kubernetes/test-infra#9597]
Something like: https://github.com/kubernetes/test-infra/blob/master/boskos/janitor/janitor.py#L329

This is necessary because some tests (https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/114) push images to the CI's project. If the tests crash and they are unable to GC themselves the images may be leaked.

/assign

**Comment by BenTheElder** [comment]
Thanks David :-)
Image GC is a long standing issue.

**Comment by davidz627** [comment]
/reopen
still needed, still no time
