### ISSUE TITLE
Replace tot with snowflake IDs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9604]
ref https://github.com/kubernetes/test-infra/issues/9593#issuecomment-425325474

/area prow
cc @BenTheElder @cjwagner @spiffxp

**Comment by spiffxp** [comment]
/area gubernator
Might have some impact here?

/area kettle
We would definitely want to revisit kettle's impl

/area testgrid
I don't know if this would impact testgrid at all, maybe during transition?

**Comment by BenTheElder** [comment]
testgrid should be unimpacted unless we decide to go back, going back would be problematic. gubernator otoh reads latest-build.txt and would be fine.

**Comment by ixdy** [comment]
/assign @fejta @BenTheElder 
cc @Katharine to fix gubernator
cc @michelle192837 to fix testgrid and kettle

**Comment by BenTheElder** [comment]
I think testgrid already works fine? not sure about kettle cc @spiffxp 
Gubernator will need fixing or we'll need spyglass to be ready though

**Comment by michelle192837** [comment]
TestGrid's fine in its current implementation as long as the IDs monotonically increase. It'll need tweaks if not.

**Comment by BenTheElder** [comment]
they're monotonic, just with gaps. testgrid is already handling some timestamp IDs so we should be good 👍 
http://testgrid.k8s.io/conformance-cloud-provider-openstack#periodic-master

**Comment by BenTheElder** [comment]
so probably just check kettle and then we can look at deleting the service

**Comment by Katharine** [comment]
Looked into this briefly, we also need to set `sequential: false` as appropriate in [kettle/buckets.yaml](https://github.com/kubernetes/test-infra/blob/master/kettle/buckets.yaml) before we kill tot.

**Comment by Katharine** [comment]
/remove-lifecycle stale

There are no known (to me) blockers on this. We just need to pick a time we don't expect to matter an awful lot if things are on fire. After we work through the merge backlog at the beginning of the 1.15 cycle maybe?

We'll also have to loop in contribex and maybe kubernetes-dev because the numbers will be large and ugly.

**Comment by spiffxp** [comment]
I'm in favor of trying this out, and yes we should give kubernetes-dev@ a heads up.  My only ask is that we wait until v1.14 goes out the door.

**Comment by Katharine** [comment]
After 1.14 ships is my plan.

**Comment by Katharine** [comment]
We did it!

/pony cheering
/close

**Comment by krzysied** [comment]
Hi folks!
Currently we are having issue with perfdash - it doesn't work. https://github.com/kubernetes/perf-tests/issues/469
Assuming that you made changes to the other tools, can someone give hints on how to work with the new run id format? We are using k8s.io/contrib/test-utils/utils/utils.go for accessing the run logs.
