### ISSUE TITLE
Pre-build hook for Kubetest

### ISSUE THREAD

**Issue by davidz627** [kubernetes/test-infra#9620]
A pre-build hook for Kubetest might be useful. Maybe allowing the user to run a script or some commands before the Kubernetes binaries are built for cluster upping.

The use case is for external repos that want to build a slightly modified version of Kubernetes to run the tests with. 
For example the test run in this PR repo https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/114 needs to modify some manifest files that get built (IIUC) into the tests run on the cluster. 

However, this exact use case might disappear soon when Kubernetes tests are refactored to be more easily "consumed" from out of tree components (?)

/cc @krzyzacy 
/cc @msau42

**Comment by krzyzacy** [comment]
/assign

we probably want to provide pre/post build hooks, also pre/post test hooks, will consider in kubetest v2 design.

**Comment by krzyzacy** [comment]
@davidz627 we are moving towards kubetest2, see design doc https://docs.google.com/document/d/1Dc7xg9lq4cxdDuz20YZjunuL5eju2WIXwO32praC5hs/edit, and you can have your freedom of your deployer.

/priority important-longterm
/unassign
/help
