### ISSUE TITLE
Prow badge is red, should be green?

### ISSUE THREAD

**Issue by bobcatfish** [kubernetes/test-infra#9628]
# Expected
When using the prow badge (e.g. https://prow.knative.dev/badge.svg?jobs=pull-knative-build-pipeline-unit-tests) to display the status of a PR job, it should be green when the latest run is successful, and red if it is not successful.

# Observed
In https://github.com/knative/build-pipeline we are using badges to show the Prow CI status, unfortunately these are on PR (not continuous integration) workflows, so I can understand that a failing PR might make the badge turn red, but currently the badge is red and that doesn't seem to be the case:

![image](https://user-images.githubusercontent.com/432502/46237713-2e2d2f00-c33b-11e8-8f43-7d51b8ce6960.png)

When I look at the prow status for that job (https://prow.knative.dev/?job=pull-knative-build-pipeline-build-tests), the latest status is green (though there have been some reds):

![image](https://user-images.githubusercontent.com/432502/46237736-4ef58480-c33b-11e8-9ae9-3590c1d35285.png)

**Comment by BenTheElder** [comment]
/help

the code is here: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/badge.go

something needs fixing with that computation :^)

**Comment by anwaradil** [comment]
I can work on this. I have been staring at this code for a while and I think the issue is we are not checking if the recent job has been successful in line 124 of badge .go.  

The question is should we even check the length if the recent job is successful? Assuming we turn the badge to red or green only according to the latest job but not per the last 8 runs.

Also, Maybe I need to look some more but I am not seeing where we are using or calling the func pickLatestJobs?

**Comment by nzoueidi** [comment]
is this being looking into? otherwise I may want to take it :)

**Comment by stevekuznetsov** [comment]
Go ahead and take it!

**Comment by anwaradil** [comment]
Yes take it :)

**Comment by nzoueidi** [comment]
Sorry for the delay, I have been out in vacation. 🎉  
I would like to propose an approach here before doing all of the coding..
I am thinking about adding another function in the `badge.go` file to have a sort of struct including all the latest 8 jobs and their status. Based on these status the func will have a boolean output then I can add it in the if statement (L124) in the `renderBadge` func. WDYT?
I would be very happy to have your inputs and if there is any suggestion how we could do this in a better way.

**Comment by stevekuznetsov** [comment]
How do you propose to take the last eight jobs and determine the boolean output? The approach roughly sounds good to me!

**Comment by BenTheElder** [comment]
I hit this recently, it doesn't look like the results are ordered at all ...?

**Comment by morvencao** [comment]
@BenTheElder Is this issue fixed? If yes, I should upgrade to the latest build.

**Comment by BenTheElder** [comment]
I'm not sure, currently I'm not using badges.

**Comment by morvencao** [comment]
I'm using the build version of `v20190918-7672de02b`, look like the issue still exists.

**Comment by matthyx** [comment]
@nzoueidi ping?
