### ISSUE TITLE
check-cla bug

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9636]
https://kubernetes.slack.com/archives/C09QZ4DQB/p1538253303000100

check-cla is not doing anything https://github.com/kubernetes/kubernetes/pull/69135#issuecomment-425673423, the logs show that hook:
- received my comment
- listed the PR labels
- got the PR
- listed the statuses on the right commit

I see no further logs related to the PR :confused:

/kind bug
/area prow
/assign @amwat

**Comment by BenTheElder** [comment]
cc @nikhita

**Comment by BenTheElder** [comment]
Checking the API myself I don't see any status for the cla ??
https://gist.github.com/BenTheElder/e4db613e9e06d66a4857c2966a5f7870

**Comment by nikhita** [comment]
> Checking the API myself I don't see any status for the cla ??

Can't see the status for CLA for any of the PRs (not just the offending PR with no cncf-cla label). :confused: 

https://gist.github.com/nikhita/401b5b7b03fcbded631ff3bb446245bc

**Comment by BenTheElder** [comment]
soo... it exists in /status but not /statuses 🤦‍♂️
