### ISSUE TITLE
openshift issue

### ISSUE THREAD

**Issue by ghost** [kubernetes/test-infra#9637]
Reason: buildconfigs.build.openshift.io "tridion-deployer-pipeline" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update.

hi am getting above issue,what is the way to resolve this issue?

**Comment by BenTheElder** [comment]
can you provide more context? this does not sound like a prow issue, this sounds like an OpenShift issue.

/assign @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@ghost hello! It looks like you've got some issues with your `BuildConfig` definition. Could you please create an issue against [`openshift/origin`](https://github.com/openshift/origin/issues/new) repository or ask on StackOverflow? Unfortunately the `kubernetes/test-infra` forum is not the right place to get help with this issue.

/close
