### ISSUE TITLE
prow should ship github's fingerprint not skip key checking

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9638]
follow up to https://github.com/kubernetes/test-infra/issues/9440

github has a well known SSH fingerprint. we should ship it in prow as a default, and we should at least optionally enable host key checking

/area prow
/kind bug

/priority important-soon

/cc @fejta

**Comment by stevekuznetsov** [comment]
This is a much better approach than what I did in that `Dockerfile`, +100000

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

/help

Adding the known SSH keyprint should be pretty trivial, configuration for host key checking might be a little less trivial / more controversial.

**Comment by stevekuznetsov** [comment]
I could have sworn @fejta fixed this -.-

**Comment by stevekuznetsov** [comment]
@fejta you fixed this, right?

**Comment by matthyx** [comment]
I have poked @fejta on slack regarding this issue.

**Comment by BenTheElder** [comment]
/reopen
/remove-lifecycle rotten

as far as I know we still skip key checking

**Comment by BenTheElder** [comment]
https://help.github.com/en/github/authenticating-to-github/githubs-ssh-key-fingerprints

the question is just how we want to plumb this through.

**Comment by alvaroaleman** [comment]
> the question is just how we want to plumb this through.

By replacing this line https://github.com/kubernetes/test-infra/blob/16cb8d25c7a01d3ab90a8502e45ea6f26492cdba/prow/cmd/clonerefs/ssh_config#L4 ?

**Comment by stevekuznetsov** [comment]
@droslean @petr-muller what was the drawback to this approach?

**Comment by droslean** [comment]
If you remove this, you have to make sure that the default ssh dir exists and `clonerefs` have access to it. Also, you have to pass the actual value of the known_hosts to the `clonerefs` options, and you have to include all the Github IPs. I tried, but at some point it starts flaking because for some reason new IPs are coming into play.

**Comment by alvaroaleman** [comment]
Why IPs, shouldn't the hostname be enough?

**Comment by droslean** [comment]
This is what we thought... But it turns out that hostname is not enough. I really don't have any idea why.

**Comment by BenTheElder** [comment]
pretty sure we just need:
```
Host github.com
  HostName github.com
  User git
  UserKnownHostsFile /github_known_hosts
  StrictHostKeyChecking yes
  CheckHostIP no
```

**Comment by BenTheElder** [comment]
er, and a file with the fingerprints.

https://leighmcculloch.com/posts/ssh-pin-known_hosts-for-github/ :-)

**Comment by BenTheElder** [comment]
forgot about this, too many things going on :-/
I am pretty sure https://github.com/kubernetes/test-infra/issues/9638#issuecomment-549938258 will work though, if someone wants to try this out. I probably won't have time to switch gears to this for a while.

**Comment by matthyx** [comment]
@alvaroaleman do you want, or shall I?

**Comment by alvaroaleman** [comment]
Go ahead, I'll do the review :)
