### ISSUE TITLE
Prow hook endpoints returns HTTP 200 in case of errors

### ISSUE THREAD

**Issue by aszecowka** [kubernetes/test-infra#9639]
See test-infra/prow/hook/server.go method ServeHTTP function. 
```
eventType, eventGUID, payload, ok, resp := github.ValidateWebhook(w, r, s.TokenGenerator())
```
ValidateWebhook is documented in the following way:

```
It returns the event type, the event guid,
// the payload of the request, whether the webhook is valid or not,
// and finally the resultant HTTP status code
```

But then, in ServeHTTP we have:
```
if !ok {
  return
}
```
So in case of return we return HTTP 200, when we should return `resp` in my opinion.

Additionally, we should consider to change a little bit endpoint for health check:

test-infra/prow/cmd/hook/main.go
```
// Return 200 on / for health checks.
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {})
```
I followed "Getting started" guide, and I configured webhook which unfortunatelly pointed to above endpoint, whereas it should point to "/hook". In github, I got impression that everything is fine (return code 200), where it was incorrect. Simple solution for that, will be extended health endpoint and return HTTP 200 only in case of HTTP GET.
Additionally, "Getting Started" can be more precise:
```
Set the payload URL to http://<IP-FROM-INGRESS>/hook
```
where IMO it should be:
```
Set the payload URL to http://<IP-FROM-INGRESS>/hook/hook
```

**Comment by spiffxp** [comment]
/area prow
FYI @cjwagner

**Comment by cjwagner** [comment]
> Set the payload URL to http://<IP-FROM-INGRESS>/hook/hook

That wouldn't be correct currently? See the ingress here: https://github.com/kubernetes/test-infra/blob/1bbbbd6da26ba87f79c234c64320c6d0bb765748/prow/cluster/tls-ing_ingress.yaml#L37-L40

I would be open to changing how health checks work so that we can expose hook handling errors more clearly. I'm not sure what the best way to do that is though. Can we control which path Kubernetes uses for pod health checks?

**Comment by BenTheElder** [comment]
yes, usually you add some /healthz endpoint https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request

you can alternatively do a command probe or TCP.
