### ISSUE TITLE
/uncc not working in k/community

### ISSUE THREAD

**Issue by tallclair** [kubernetes/test-infra#9643]
See https://github.com/kubernetes/community/pull/2337#issuecomment-425575947

/cc @liggitt

**Comment by liggitt** [comment]
> /cc @liggitt

it's the new collaborative model: you can check out any time you like, but you can never leave!

**Comment by BenTheElder** [comment]
I think that is WAI, I don't think you can not be a reviewer once you've reviewed (per github) and to unsubscribe you have to do it yourself, there's no API for the bot to do this. uncc only works if you've not-yet reviewed AFAIK

**Comment by tallclair** [comment]
Ack, thanks.
