### ISSUE TITLE
Spyglass GCS artifact fetcher hangs

### ISSUE THREAD

**Issue by ibzib** [kubernetes/test-infra#9646]
There's a potentially infinite loop in Spyglass's GCS artifact fetcher: https://github.com/kubernetes/test-infra/blob/master/prow/spyglass/gcsartifact_fetcher.go#L110

This has been triggered for me both in tests and local runs, because it's possible in cases of malformed buckets that objIter.Next() returns a non-"Done" error indefinitely.

Fix ideas:
1. Break as soon as any error is encountered
2. Break after a certain number of failures
3. Break after a certain amount of time has elapsed

**Comment by cjwagner** [comment]
Using a limited number of retries and exponential backoff is usually the best solution.
