### ISSUE TITLE
label_sync allows duplicate repo blocks, last block wins

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9647]
ref: https://github.com/kubernetes/test-infra/pull/9627#issuecomment-425681165

We should update label_sync validate() to yell if it encounters duplicate repo entries

/kind bug

**Comment by qhuynh96** [comment]
I will take this issue
/assign

**Comment by stevekuznetsov** [comment]
I think this is a general issue with YAML unmarshalling?

**Comment by stevekuznetsov** [comment]
I found this in `plugins.yaml["plugins"]`

**Comment by stevekuznetsov** [comment]
@fejta @spiffxp @cjwagner @BenTheElder @krzyzacy looks like k8s moved to use https://github.com/kubernetes-sigs/yaml/ for strict parsing -- do we want to migrate?

**Comment by BenTheElder** [comment]
I don't htink k8s has yet. `kind` did for a bit (and then moved back, but only to use the k8s encoding machinery), I would recommend it except that it's a breaking change to prow. Was just discussing using this in the config validation tool with @cjwagner 

It works nicely, I'd recommend using it `sigs.k8s.io/yaml.UmarshalStrict`

**Comment by fejta** [comment]
Don't we check this now?

**Comment by stevekuznetsov** [comment]
No, we have not changed the YAML loading behavior
