### ISSUE TITLE
Grandmatriarch sometimes could not update token

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9652]
(happened again, so open an issue. we probably can add more logs to see which step it didn't go through)

/area prow/grandmatriarch
/assign @fejta

**Comment by stevekuznetsov** [comment]
Looks like we need a new label :)

**Comment by stevekuznetsov** [comment]
And perhaps a grandmatriarch emoji

**Comment by krzyzacy** [comment]
/shrug
/assign
bit us again... looking into it

**Comment by krzyzacy** [comment]
cc @AishSundar

**Comment by krzyzacy** [comment]
so we worked around by let grandmatriarch run more often which ... worked so far ...
/pony fine
/close
