### ISSUE TITLE
Kubespray w/kubeadm - periodic master job

### ISSUE THREAD

**Issue by timothysc** [kubernetes/test-infra#9655]
Per discussion on sig-cluster-lifecycle meeting, kubespray for 1.13 plans to set kubeadm as the default tool for deploying.  As a result, we would like to add a kubespray based deployment for gce-master to be very similar to the current deployers using kubernetes-anywhere: 

Requirements: 
- Use an Ubuntu 18.04 host 
- Default job ~= https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-master but using kubespray vs. k8s-anywhere 
- deploys using standard kubeadm defaults 
- CRI - TBD
... 

@kubernetes/sig-cluster-lifecycle for other requirement 
xunim - said he would help work on this one.

**Comment by riverzhang** [comment]
That's awesome!!!   I also want to join. @timothysc

**Comment by ltupin** [comment]
@timothysc It should be better to assign this issue to @riverzhang as he is a k8s member.
@riverzhang I wan to help on this so dont hesitate to share with me here or on slack ;-)

**Comment by timothysc** [comment]
/assign @riverzhang  

@riverzhang do you think we could sync sometime next week?

**Comment by neolit123** [comment]
@timothysc @riverzhang 
instead of creating a new kubetest deployer and hosting the jobs on prow we can pipe logs (federate) from an external CI process into testgrid.

example PR:
https://github.com/kubernetes/test-infra/pull/11231
