### ISSUE TITLE
upgrade/downgrade jobs reference kubernetes v1.8 version of etcd3

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9679]
```
      # TODO: This is pinned to the 1.8 version of etcd. 1.9 was changed to
      # 3.1.x. ETCD doesn't downgrade minor versions. So for downgrades, we
      # pin this to the lower version. The long term fix is to change
      # downgrade/upgrade to not upgrade/downgrade etcd.
      - --env=TEST_ETCD_VERSION=3.0.17
```

So this is a fun comment to find in the v1.13 release cycle
/milestone v1.13
/priority important-soon
/kind cleanup
/sig release
/sig cluster-lifecycle
/sig gcp

These jobs seem to be ownerless, and it's unclear to me what the solution here is, hence why I'm opening an issue.  Options:
- change TEST_ETCD_VERSION to the last 3.1.x release
- change TEST_ETCD_VERSION to whatever version was used by kubernetes v1.10
- change TEST_ETCD_VERSION to whatever version was used by kubernetes v1.11
- remove TEST_ETCD_VERSION entirely
- go see if the longterm fix is still valid, and/or how doable it is

**Comment by roberthbailey** [comment]
Which upgrade / downgrade versions are we testing? If all of the versions in the current test matrix can use the same minor version of etcd, then maybe we can just remove this TODO and the flag altogether.

**Comment by spiffxp** [comment]
/milestone v1.14

I question the viability of never upgrading minor versions of etcd again.  That said, perhaps this is a thing to be punted and revisited with etcdadm.  I'd like for us to decide one way or the other this release cycle

**Comment by spiffxp** [comment]
/assign @krousey @jpbetz 
to get your attention, ref: https://github.com/kubernetes/test-infra/pull/10225#issuecomment-441935814

**Comment by imkin** [comment]
I was wondering if the right strategy for upgrade/downgrade tests to pick the lower versions supported etcd version. This strategy would be more accurate and manageable then pinning the version in config file.

@wenjiaswe @spiffxp

**Comment by wenjiaswe** [comment]
Just talked to @imkin offline, I agree [this](https://github.com/kubernetes/test-infra/issues/9679#issuecomment-490292701) would be a better approach, if the upgrade/downgrade test could fetch the etcd version of the lower k8s version of the upgrade/downgrade pair, and use that in the test. Otherwise, there is no guarantee that the pinned old etcd version would work with all supported k8s version, right?

**Comment by justaugustus** [comment]
Looks like this is still true:
- https://github.com/kubernetes/test-infra/blob/dc70aede1650507b99c05146163343b1d4914d93/config/jobs/kubernetes/sig-cloud-provider/gcp/gpu/gcp-gpu-upgrade-downgrade.yaml#L198
- https://github.com/kubernetes/test-infra/blob/dc70aede1650507b99c05146163343b1d4914d93/config/jobs/kubernetes/sig-cloud-provider/gcp/gpu/gcp-gpu-upgrade-downgrade.yaml#L229
- https://github.com/kubernetes/test-infra/blob/dc70aede1650507b99c05146163343b1d4914d93/config/jobs/kubernetes/sig-cloud-provider/gcp/upgrade-gce.yaml#L334
- https://github.com/kubernetes/test-infra/blob/dc70aede1650507b99c05146163343b1d4914d93/config/jobs/kubernetes/sig-cloud-provider/gcp/upgrade-gce.yaml#L364

Do we have anyone to work on this?

/remove-lifecycle rotten
/milestone v1.18
/help
