### ISSUE TITLE
Pubsub reporter: need to take in a service account

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9686]
rather than use leaked service account from vm

cc @yutongz 
/area prow
/assign

**Comment by sebastienvas** [comment]
I believe only crier and sub are using the reporter, is it just a matter of creating a new service account / kubernetes secret and adding  GOOGLE_APPLICATION_CREDENTIALS to the crier deployment ?

**Comment by krzyzacy** [comment]
There's already a secret in the cluster, just mount it and add a flag or parse the env?

**Comment by sebastienvas** [comment]
I guess we can close this, this is already supported by the google api client.
