### ISSUE TITLE
Soooooo many comments from k8s-ci-robot

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/test-infra#969]
We should come up with a better way to manage the k8s-ci-robot's comments on PRs. Right now, if something causes all of the PR tests to fail, the bot will comment 7 times for the same test run, often right in the middle of a discussion. This is fairly annoying because:
- It puts a bunch of unnecessary scrolling in the middle of threads on GitHub.
- It puts the discussion thread 7 emails behind test information, when participating via email.

The information (e.g. how to re-run the failed test) and links in the comments are useful. Would it be possible to include this information e.g. on the k8s-gubernator page on the other side of the "Details" links in the "Checks" section on GitHub, rather than commenting directly on the PR? We could even have something like `Failed, comment "@k8s-bot gci gce e2e test this" to re-run` in the status of the checks for failed tests so that "how to re-run" is still adjacent to "failed".

Example: 7 comments from bot, and buried in the middle is an *actual* comment I would want to see https://github.com/kubernetes/kubernetes/pull/32530

WDYT?

/cc @ixdy @spxtr @fejta

**Comment by spxtr** [comment]
I agree with you. I suggested this a while ago but some people base their entire workflow around these sorts of emails.

@kubernetes/contributor-experience

**Comment by mtaufen** [comment]
Is there a way to block notifications from specific users? If there is I am going to block k8s-ci-robot *evil grin*

**Comment by ixdy** [comment]
Maybe it could at least update one comment to add additional failures, rather than 7 comments?

Works in the UI, though not as well in email (since GitHub won't send new emails for the updates). Feature/bug.

**Comment by spxtr** [comment]
I'd rather just stop making the comments. @kubernetes/contributor-experience thoughts?

**Comment by thockin** [comment]
I, for one, rely on email

**Comment by spxtr** [comment]
@apelisse suggests creating the comment and then immediately deleting it. That way you get emails if you want, but there's no spam on your PR.

**Comment by thockin** [comment]
We do this for some comments, but it's useful to leave the "magic
incantation to try again" comments, or at least teh most recent (complete)
one.

**Comment by mtaufen** [comment]
Would it be possible to put the "magic incantation" in the status message for the "checks" for failed tests?

**Comment by spxtr** [comment]
Yes, it's possible, but space is limited. We will be shortening these commands soon, so `@k8s-bot gce e2e test this` will become `/test gce`, which might make space less of an issue.

**Comment by spxtr** [comment]
OK, you'll still get email spam, but now it'll aggregate failures into one comment.

**Comment by fejta** [comment]
ci-kubernetes-e2e-gke-1.5-1.4-gci-kubectl-skew: broken test run
ci-kubernetes-e2e-gke-1.5-1.4-gci-kubectl-skew: broken test run
ci-kubernetes-e2e-gke-1.5-1.4-gci-kubectl-skew: broken test run
ci-kubernetes-e2e-gke-1.5-1.4-gci-kubectl-skew: broken test run
ci-kubernetes-e2e-gke-1.5-1.4-gci-kubectl-skew: broken test run
ci-kubernetes-e2e-gke-1.5-1.4-gci-kubectl-skew: broken test run
