### ISSUE TITLE
A prow cmd to move github issues between repos

### ISSUE THREAD

**Issue by jessiezcc** [kubernetes/test-infra#9690]
GIT doesn't have a nice way to move issues across repos, however the need of moving an issue between repos are pretty frequent. 

If Prow could provide a cmd (something like /move <targetrepo>) to do the following, it'll be a great time saver. 

- create a new issue in target repo
- copy issue title
- copy issue description
- add a link in new issue pointing to current issue in source repo
- close issue in source repo with a comment indicating that this issue is moved to target repo, and warn about its deprecation.

**Comment by cjwagner** [comment]
Would you expect conversation to continue on the old issue or the new issue? If the new issue is to be used in place of the old issue we may also want to have the plugin post a comment to the old issue, warning about the issue's deprecation.

**Comment by jessiezcc** [comment]
Once moved, the conversation should happen with the new issue. Great point, a comment to old issue would make the closure clear. Updated the description to reflect that.

**Comment by BenTheElder** [comment]
There are other tools to do this already, git doesn't know about issues but Git**Hub** tools can move it. EG https://github.com/google/github-issue-mover

**Comment by jessiezcc** [comment]
Great to know, @BenTheElder! My concern with adopting additional tooling is the additional setup/configuration/learning curve coming with it. 

With Prow command, at least in Knative case, it will be very inherent experience and intuitive to use.
