### ISSUE TITLE
A prow cmd to dup a github issue

### ISSUE THREAD

**Issue by jessiezcc** [kubernetes/test-infra#9693]
similar to #9690 , we need a cmd to duplicate an issue, i.e. /dup

**Comment by stevekuznetsov** [comment]
Why? Do you mean you would like a command to copy a GitHub issue into another, identical, GitHub issue against the same repo?

**Comment by jessiezcc** [comment]
I meant to resolve an issue as a duplicated issue. It happens there are 2(or more) separate issues tracking the similar problems/asks.

**Comment by spiffxp** [comment]
A human can do this today via
```
/triage duplicate
because #1234
/close
```
What behavior would you be looking for in this case?

**Comment by spiffxp** [comment]
/reopen
/remove-triage duplicate
THANKS PROW
TIL it'll interpret commands in ``` blocks

**Comment by spiffxp** [comment]
so yeah, uh, welcome to the live demo of what those commands would do
