### ISSUE TITLE
1.12+ should not exclude kubectl with skip regex for Conformance tests

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9697]
https://github.com/heptio/kube-conformance/commit/c4eb36ad07a5d7d7e0a47bb6535f787d589b729a

we need to:
- update master / 1.12 jobs
- update docs in test-infra, and the community developer guide, possibly elsewhere.

probably inform sig-cloud-provider members that publish continuous signal to testgrid with kubetest. cc @spiffxp @dims @Katharine

**Comment by spiffxp** [comment]
I would much rather complete "pulling the skiplist upstream", aka stripping the Conformance tag from any tests that are skipped by this regex, such that focusing on Conformance is all that's needed

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/67901 to drop a `[Flaky]` test

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/62161 the umbrella issue in k/k for Serial / Flaky / Slow... at present I am only interested in Flaky.  Serial and Slow may be necessary evils.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/test-infra/pull/9104 where we introduced the skiplist in the first place, this can be considered closed once we've eliminated it

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/milestone v1.14
Keeping this open as the "pulling the skiplist upstream" issue re: https://github.com/kubernetes/test-infra/issues/9697#issuecomment-427067895 unless I find a better issue for it

**Comment by spiffxp** [comment]
I stripped the skip regex from the conformance image we are hoping to publish as part of this release https://github.com/kubernetes/kubernetes/pull/74808#issuecomment-468860534

We'll compare the list of tests that runs to the list of tests our jobs run.  If they match, let's drop the regex from 1.14

**Comment by spiffxp** [comment]
/milestone v1.15
/assign
I'm pretty sure this is either done, or can be done, I need to verify list of tests

I would like to ensure conformance tests are prevented from using these tags ever again

**Comment by BenTheElder** [comment]
this bit me submitting the kind 1.14 results (they were accepted though! I amended the next day ❗️), we've removed the skip from kind everywhere (except the parallel / non-serial runs), there might still be something out there using them incorrectly, but those were the last ones I know about.

**Comment by spiffxp** [comment]
Verified the list of tests for v1.15 and v1.14 by using the kind and kind-image jobs, eg:
- https://testgrid.k8s.io/conformance-all#kind-image,%201.14%20(dev)&sort-by-name=
- https://testgrid.k8s.io/conformance-all#kind,%20v1.14%20(dev)&sort-by-name=

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/kubernetes/pull/78710 to enforce the regex as a gate to promotion to conformance

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/test-infra/pull/12887 to strip the regex from as many cargo cults as I could find

**Comment by spiffxp** [comment]
/close
No complaints since #12887 merged, meant to close this a few weeks ago but forgot
