### ISSUE TITLE
cats in space have gone missing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9707]
https://github.com/kubernetes/test-infra/pull/9625#issuecomment-427178893

/kind bug
/area prow
/priority critical-urgent
/assign @fejta

**Comment by BenTheElder** [comment]
I think the error handling may just be incorrect: https://github.com/kubernetes/test-infra/pull/9626#issuecomment-427181655

**Comment by stevekuznetsov** [comment]
:gasp:

**Comment by nikhita** [comment]
Looks like the cats are back :)

**Comment by BenTheElder** [comment]
yeah they show up but the error handling is probably still wrong because that CATegory definitely exists

**Comment by justaugustus** [comment]
Do we have dogs in space as well?
/woof space

**Comment by BenTheElder** [comment]
the doggo API has no CATegories
/woof

**Comment by krzyzacy** [comment]
time to pull in some ml model?

**Comment by BenTheElder** [comment]
The sink cats have gone missing!! https://github.com/kubernetes/test-infra/pull/10111#issuecomment-437469768

**Comment by krzyzacy** [comment]
there are other caregory gone missing too I think

**Comment by fejta** [comment]
Maybe it's working?

**Comment by krzyzacy** [comment]
really 😢

**Comment by justaugustus** [comment]
I want to play too!
/meow space
/pony party

**Comment by justaugustus** [comment]
@ixdy -- no one can hear you in space, which is probably why `/joke space` didn't work ;)

**Comment by randomvariable** [comment]
srs testing:
/meow space
