### ISSUE TITLE
kubekins-e2e jobs are not forked for 1.12

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9719]
the image exists, but no jobs are using it until https://github.com/kubernetes/test-infra/pull/9718

/kind bug
/assign @cjwagner @amwat

**Comment by BenTheElder** [comment]
/priority critical-urgent
we're bumping go in the master, we need to fork these.

**Comment by spiffxp** [comment]
@BenTheElder have we taken care of this?

**Comment by BenTheElder** [comment]
the critical jobs where this is immediately a concern, but not all of them.

**Comment by spiffxp** [comment]
/milestone v1.14

@BenTheElder is this still an issue?

**Comment by BenTheElder** [comment]
/shrug
everything seems juuuust fine. definitely won't bite us in the future. definitely.
/close

**Comment by BenTheElder** [comment]
xref: #4824
