### ISSUE TITLE
fast-fail batches in tide

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9724]
currently the batch results look like:
![image](https://user-images.githubusercontent.com/917931/46565372-7d3b0d00-c8c3-11e8-8592-92b175392f75.png)
yet the tide dashboard is:
![image](https://user-images.githubusercontent.com/917931/46565377-89bf6580-c8c3-11e8-9ae4-93ec3afcca76.png)

why are we not merging 69386 now that the batch has failed a required test? are we waiting for all of the jobs in the batch to complete ...?

/kind question
/area tide
probably:
/kind bug

/assign @cjwagner

**Comment by BenTheElder** [comment]
i'll have to dig into the logic but AFAICT the correct behavior here should be:

1) test a batch when possible
2) when any required test fails in a batch, quit considering that batch
3) if any PR has serially passed at this point, merge one
4) start a new batch after merging any serial PRs
5) repeat 1)

**Comment by cjwagner** [comment]
Good point. This shouldn't be hard to fix.
