### ISSUE TITLE
govet k8s.io/test-infra/testgrid 

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9749]
https://github.com/kubernetes/test-infra/pull/9747#discussion_r223889561

we can't run `govet` because there's a nonexistent (generated) package imported by the code.

**Comment by krzyzacy** [comment]
/assign @fejta @michelle192837 
we potentially can put a placeholder package file for go vet... but sounds unnecessary?
/shrug

**Comment by BenTheElder** [comment]
probably what we need to do is run vet over the codebase w/ generated code included. #9747 was already huge though given how old our fmt / vet go had gotten. it should not lag again in the future after the image switch
