### ISSUE TITLE
Implement KEP 028: New label for trusted PR identification

### ISSUE THREAD

**Issue by matthyx** [kubernetes/test-infra#9754]
Alright, I have started implementing stuff, and I am not sure where to discuss that, so here is an issue for it.

**Comment by cjwagner** [comment]
KEP: https://github.com/matthyx/community/blob/master/keps/sig-testing/0028-20180625-new-label-for-trusted-pr-identification.md

**Comment by matthyx** [comment]
@cjwagner do you think we can/should now remove the code that parses comments for PR trust?
(prow/plugins/trigger/pr.go)

**Comment by cjwagner** [comment]
> @cjwagner do you think we can/should now remove the code that parses comments for PR trust?
(prow/plugins/trigger/pr.go)

Sounds reasonable to me. In the worst case, PRs that haven't been touched since we added this feature may need another `/ok-to-test`, right?

**Comment by matthyx** [comment]
> Sounds reasonable to me. In the worst case, PRs that haven't been touched since we added this feature may need another `/ok-to-test`, right?

Yes.

**Comment by matthyx** [comment]
Last step here: #10991

**Comment by matthyx** [comment]
Everything is merged, I can close this, and will update the KEP.
