### ISSUE TITLE
prow: tide: config validation error messages not useful

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#9764]
I don't have enough information from this error to do anything with it

```
{"component":"branchprotector","error":"tide query (index 0) is invalid: 'repos' contains 1 duplicate entries","level":"fatal","msg":"Failed to load --config-path=/home/skuznets/releasego/src/github.com/openshift/release/cluster/ci/config/prow/config.yaml","time":"2018-10-11T09:19:19+02:00"}
```

/kind bug
/area prow/tide
/assign @cjwagner

**Comment by cjwagner** [comment]
It is indicating that the `repos` field of the first Tide query contains a duplicate entry. Is that part clear?
We definitely should include the values that are duplicated in the error message though.

**Comment by stevekuznetsov** [comment]
Yeah, the first one is clear but when that list is 100 repos long ... not super useful :)
