### ISSUE TITLE
Make k-s job generator handle decorated jobs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9783]
/shrug
cc @BenTheElder @cjwagner

**Comment by BenTheElder** [comment]
It does handle them?

**Comment by krzyzacy** [comment]
we need to change the default gcs stuff... or we can supply a different default decoration config?

**Comment by BenTheElder** [comment]
I see... That should be straightforward to handle. We should discuss this a bit out of band though, I have some other thoughts about the entire setup..

**Comment by krzyzacy** [comment]
/remove-lifecycle stale
still biting us
/pony shrug

**Comment by BenTheElder** [comment]
it _does_ handle them, the new problem is jobs that have partial decorated config, for those we don't strip the fields that are default. we could do this, but _effort_. jobs that have fully default decorated config drop the whole field.
