### ISSUE TITLE
timeouts for cluster upgrade tests, even at 20 hours

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#9802]
Opening an issue to track & discuss the timeouts on some of the upgrade tests, in particular:

* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-new
* https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster

As far as I can tell, the tests are simply taking too long, even with a 20 hour timeout raised from 15 hours in #9759.  This is because we're running all tests, and all tests includes serial & disruptive, which means we can't run them in parallel.  But we're also including slow tests, which means it takes a long time.

I'm going to try splitting off a separate test for `-parallel`, and then if that works we can skip the slow tests in the "non-parallel' tests.  (Very open to a better naming convention.  And we should probably see if we can find a test runner that doesn't make our lives so hard :-) )

**Comment by jberkus** [comment]
Also, reference issue #69475

**Comment by krzyzacy** [comment]
just an idea: what if within the same job we can trigger two ginkgo call, one parallel and one serial

**Comment by krzyzacy** [comment]
also @crimsonfaith91 @spiffxp shall we just do this for all gke upgrade jobs?

**Comment by crimsonfaith91** [comment]
@krzyzacy 
Some upgrade jobs are still manageable, especially those with low number of tests. I suggest having a quick manual inspection to identify those jobs with long test run duration (more than 12 hours). It is preferable to have at least 2 complete test runs per day.

**Comment by justinsb** [comment]
OK with #9803 these particular tests are no longer timing out (some flakes it looks like, but those we can deal with separately e.g. in https://github.com/kubernetes/kubernetes/issues/69475#issuecomment-431070378 )

So how do we want to proceed?  Roll this approach out across all the long tests?  Build it into kubetest (as per @krzyzacy's suggestion)?  Replace ginkgo?

The disruptive/serial tests do still take a lot longer to run (~6.5 hours vs ~1.5 hours).  Not sure if there's value in keeping them separate because we want the faster feedback.  Right now I think these tests are all set to run every 2 hours, but I suggest they could probably all be 24 hours (?)...

**Comment by krzyzacy** [comment]
> Right now I think these tests are all set to run every 2 hours, but I suggest they could probably all be 24 hours (?)...

only one periodic can be running at the same time... so set interval to 2h simply make them always running :-)

We can split all long upgrade test (cluster upgrade) to parallel + serial for now.. Replace ginkgo? That will need a larger discussion...

**Comment by spiffxp** [comment]
I think it'd be nice to continue the split into parallel jobs on the 1.12 and 1.11 dashboards.  We're trying to make sure all of the -blocking dashboards use the same set of jobs (https://github.com/kubernetes/test-infra/issues/9363) why not just do the same thing for -all dashboards

That said, it's not signal I'm personally going to be paying attention to, so I'm not milestoning this into v1.14

**Comment by spiffxp** [comment]
/kind cleanup
/priority important-longterm
/help
I think this is a relatively mechanical change if you follow https://github.com/kubernetes/test-infra/pull/9803 and https://github.com/kubernetes/test-infra/pull/9864, but it's probably not something for first-timers

**Comment by spiffxp** [comment]
/area deflake
(presumably this would help us see whether the same upgrade flakes persist across versions)
