### ISSUE TITLE
-new vs non-new jobs in k8s-upgrade-gce.yaml

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#9804]
We have upgrade jobs that are very similar except for a `-new` suffix:

https://github.com/kubernetes/test-infra/blob/2f8ba7c2d2461e45734782b1b220449b8dc37784/config/jobs/kubernetes/sig-cluster-lifecycle/k8s-upgrade-gce.yaml#L4

```
...
- --test_args=--kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
...
```

https://github.com/kubernetes/test-infra/blob/2f8ba7c2d2461e45734782b1b220449b8dc37784/config/jobs/kubernetes/sig-cluster-lifecycle/k8s-upgrade-gce.yaml#L29

```
...
- --skew
...
```

What is the effective difference between those two jobs?  Do we still want the not `-new` form?

(Other than the fact that we need to fix the jobs so that they aren't timing out!)

**Comment by krousey** [comment]
IIRC
upgrade = upgrade 1.X to 1.Y then run 1.X e2es
upgrade-new = upgrade 1.X to 1.Y then run 1.Y e2es

**Comment by krzyzacy** [comment]
:joy: naming is hard
