### ISSUE TITLE
Ginkgo hangs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/test-infra#9805]
I'm occasionally seeing what looks like a hang in ginkgo, where it seems to have finished running everything, but hangs until it is killed by kubetest:

e.g. https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/5922/pull-kops-e2e-kubernetes-aws/7781/build-log.txt

```
I1015 14:58:44.140] 
I1015 14:58:44.140] [32mâ€¢ [SLOW TEST:382.078 seconds][0m
I1015 14:58:44.141] [sig-apps] StatefulSet
I1015 14:58:44.141] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/framework.go:22[0m
I1015 14:58:44.141]   [k8s.io] Basic StatefulSet functionality [StatefulSetBasic]
I1015 14:58:44.141]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:704[0m
I1015 14:58:44.141]     Burst scaling should run to completion even with unhealthy pods [Conformance]
I1015 14:58:44.141]     [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:709[0m
I1015 14:58:44.141] [90m------------------------------[0m
I1015 14:58:44.141] Oct 15 14:58:44.077: INFO: Running AfterSuite actions on all nodes
I1015 14:58:44.141] 
W1015 15:27:10.552] 2018/10/15 15:27:10 process.go:199: Abort after 55m0s timeout during ./hack/ginkgo-e2e.sh --ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort --report-dir=/workspace/_artifacts --disable-log-dump=true. Will terminate in another 15m
W1015 15:27:10.554] SIGABRT: abort
W1015 15:27:10.554] PC=0x45b2e1 m=0 sigcode=0
W1015 15:27:10.554] 
W1015 15:27:10.554] goroutine 0 [idle]:
```

Note the 30 minutes "silence" from 14:58 - 15:27

Is this known?  Do we think this is likely to be ginkgo or something in our tests that is hanging but not logging?

**Comment by spiffxp** [comment]
/sig testing
/kind bug
Calling this a bug until we know more.  Maybe it's a dearth of logging at the right level?

**Comment by krzyzacy** [comment]
what is aftersuite doing there?

**Comment by jchauncey** [comment]
Im actually getting the same thing when running the tests (from master branch). There are no pods or namespaces stuck in terminating and nothing suspicious happening on the cluster.

**Comment by krzyzacy** [comment]
(suggest move this to k/k)

**Comment by spiffxp** [comment]
/close
It's not clear this is still happening.  If it does, I agree with @krzyzacy that an issue in kubernetes/kubernetes would be more appropriate to start with, until it's clear whether the issue is isolated just to tests running in prow.
