### ISSUE TITLE
kubetest: add "EKS" provider

### ISSUE THREAD

**Issue by gyuho** [kubernetes/test-infra#9814]
https://github.com/aws/awstester implements https://github.com/kubernetes/test-infra/blob/9a88e32c98e4897cdb7ada607d440d2323ad221a/kubetest/main.go#L223-L230

We have been running internal Prow cluster to test AWS ALB Ingress Controller. Please see https://github.com/gyuho/aws-alb-ingress-controller/pull/3 for example output.

Action items:
- [x] Create a PR to add EKS plugin to "kubetest" (done via https://github.com/kubernetes/test-infra/pull/9811)
- [x] Change `DumpClusterLogs` and `Publish` methods to use upstream Google Cloud Storage
- [x] Merge EKS plugin to "kubernetes/test-infra" (pending https://github.com/kubernetes/test-infra/pull/9811)
- [x] Add Prow job for [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) (Done via https://github.com/kubernetes/test-infra/pull/9872)
- [x] Add [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) tests to upstream [test grid](https://github.com/kubernetes/test-infra/tree/master/testgrid) (Done via https://github.com/kubernetes/test-infra/pull/9872)
- [x] Mount AWS test account credential to upstream Prow cluster
- [x] Add `ci-kubernetes-e2e-aws-eks` Prow job **(as a non-blocking post-submit job)** (pending https://github.com/kubernetes/test-infra/pull/9940)
- [x] Add [aws-alb-ingress-controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller) tests to upstream [test grid](https://github.com/kubernetes/test-infra/tree/master/testgrid)
  - https://github.com/kubernetes/test-infra/pull/9976
- [x] Add Prow job for [aws-alb-ingress-controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller)
  - https://github.com/kubernetes/test-infra/pull/9976
- [ ] Figure out how to use "dind" for building [aws-alb-ingress-controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller) images
  - Just like [containerd-cri-presubmit-jobs.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/containerd/cri/containerd-cri-presubmit-jobs.yaml)
- [ ] Add Prow job for [cloud-provider-aws](https://github.com/kubernetes/cloud-provider-aws)
- [ ] Add [cloud-provider-aws](https://github.com/kubernetes/cloud-provider-aws) tests to upstream [test grid](https://github.com/kubernetes/test-infra/tree/master/testgrid)

/cc @d-nishi @BenTheElder @krzyzacy

**Comment by BenTheElder** [comment]
>  Add pull-kubernetes-e2e-aws-eks Prow job

What's the intention with this job? NB we've been moving providers out of tree and we've moved away from having GKE in the blocking path generally. We're even looking at not having any providers in k/k presubmit someday ...

cc @spiffxp @fejta

**Comment by gyuho** [comment]
> we've been moving providers out of tree and we've moved away from having GKE in the blocking path generally.

Good to know. Yes, we are happy to follow the new pattern.

Do we have any issue to track this? Would each provider have its own repository to trigger Prow jobs?

**Comment by BenTheElder** [comment]
I'm not sure what the tracking issue is but yeah, each cloud provider has a repo and can have presubmits on that repo. We'll also need non-presubmits though to give more signal for Kubernetes releases. @dims might be a good person to talk to on that.

**Comment by d-nishi** [comment]
@BenTheElder this is not just for cloud provider code. this tool allows us to post CI signal for all the SIG AWS code that sits in k8s-sigs. Openstack decided to move all their code under cloud provider but that is not the norm for other folks.

**Comment by BenTheElder** [comment]
Right I get that the tool does this, I was specifically asking about `pull-kubernetes-e2e-aws-eks` which sounds like something we're getting away from. VS say a presubmit on the k8s-sigs repo, or continuous integration testing against k8s (postsubmit / periodic, not presubmit).

**Comment by krzyzacy** [comment]
cc @justinsb

**Comment by d-nishi** [comment]
@BenTheElder `pull-kubernetes-e2e-aws-eks` is not blocking k/k.
we reused a naming convention that might be causing the confusion but this tool is only providing CI signal for k8s-sigs repos related to sig-aws subprojects until we merge this work into cluster-api framework.  @gyuho can you confirm?

**Comment by gyuho** [comment]
@BenTheElder I was proposing EKS k/k e2e test suites equivalent to [`pull-kubernetes-e2e-gke`](https://raw.githubusercontent.com/kubernetes/test-infra/master/config/jobs/kubernetes/sig-gcp/sig-gcp-gke-config.yaml) (named `pull-kubernetes-e2e-aws-eks`), and agree that we should have provider-specific tests as a blocking presubmit job. We can start as a post-submit.

This tool will also be used for sub-project like ALB Ingress Controller, which requires EKS cluster.

**Comment by krzyzacy** [comment]
`pull-kubernetes-e2e-gke` only runs if `cluster/` changes because it's using underlying scripts.

I'll be able to make better suggestions after reading what your deployer is doing :-)

**Comment by BenTheElder** [comment]
SGTM, thanks! 

On a related note the naming conventions are probably worth reconsidering at some point, would love suggestions :-)

Also +1 to what @krzyzacy said, adding that:

We should definitely have blocking vendor presubmits in k8s-sigs! I'd start by introducing it as non blocking there too until we work out any necessary fixes but quickly transition it to blocking there 😅 

We might even want a _release_ blocking job (periodic) eventually for k/k, how that will work with the k-sigs providers is still tbd but eventually when there are no in-tree providers we'll need to make some decision about this.

I'd love to get this in the conformance dashboard once we have something working. (Note: nothing CNCF official, just signal for us to keep those tests and kubernetes core functionality healthy, similar TBD discussing more about how we should continue or not to block releases on some or all of those..)

**Comment by BenTheElder** [comment]
BTW: have you see the prowjob pod presets support? It seems like a lot of those `AWSTESTER_EKS*` env could go in one or more of those to make it easier for people to create prowjobs using it.

**Comment by gyuho** [comment]
> BTW: have you see the prowjob pod presets support.

Have not. Great idea to package them into a preset. Will look into it. Thanks!

**Comment by d-nishi** [comment]
Fantastic!

**Comment by dims** [comment]
/close

we don't need this right @gyuho ?
