### ISSUE TITLE
Make gerrit adapter support postsubmit jobs

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9826]
cc @fejta 

Looks like we can only retrieve the latest revision(commit) from a branch, but not the merge timestamp :-\ Since we are polling we can always store latest commit and trigger a run once the latest SHA changes... but it will be better if I can find the branch last updated time.

/area prow/gerrit
/assign

**Comment by krzyzacy** [comment]
alternative idea is to query all changes and check if there's a merge event happened, and we will be able to comment back to the change.

**Comment by ibzib** [comment]
fixed in #10184
/close
