### ISSUE TITLE
/lint should suggest changes

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/test-infra#9836]
how cool what that be?

/kind enhancement
/area prow
/area prow/plugins
/priority backlog
/help

if anyone wants to look at building something like this, it would make an awesome prow plugin

**Comment by taragu** [comment]
@BenTheElder what are the requirements for this issue? I was trying to see an example output of /lint and found this PR: #9644 and saw that /lint did suggest changes:
<img width="700" alt="screen shot 2018-10-21 at 07 01 29" src="https://user-images.githubusercontent.com/6353048/47266057-5c97c780-d4ff-11e8-9782-758555983ef5.png">

**Comment by BenTheElder** [comment]
Er this would be a bit more involved, github now allows suggesting what the code should be, which the user can accept and get a new commit with the changes applied.

https://blog.github.com/2018-10-16-future-of-software/#suggested-changes-public-beta

It would be cool if we automatically suggested code fixes using this :-)

**Comment by taragu** [comment]
@BenTheElder ah i see. Thanks for the clarification! I'd like to work on this item

**Comment by BenTheElder** [comment]
Have at it! I think it will be tricky to wire up something to make accurate suggestions, but this feature could be really nice :-)

**Comment by taragu** [comment]
@BenTheElder I created a test case and a rough implementation for one use case. Could you please take a look to see if I'm on the right track before I continue implementing the rest of the cases? Thank you so much in advance! 
https://github.com/kubernetes/test-infra/compare/master...taragu:lint-suggest-changes?expand=1

**Comment by nikhita** [comment]
@taragu :tada: thanks for sending a PR!

Just saw this and thought I'd mention it here: https://twitter.com/fatih/status/1059888289979813889 is a tool which does pretty much this using the "suggest changes" feature.

https://fixmie.com/ for more details.

**Comment by taragu** [comment]
@nikhita ahh thanks for the info! Looks like we shouldn't reinvent the wheel. Is there an internal approval process for using this tool?

**Comment by BenTheElder** [comment]
IMO this is still something nice to build into Prow, we have room to do other things with the suggestions functionality but this is the first obvious step to use it imo. Leveraging the new suggest changes functionality in Prow was the intention behind opening this issue.

**Comment by Katharine** [comment]
Does this make sense for e.g. rename-type issues? AFAIK, the linter is only going to suggest changes at the declaration, but not for any uses — so for the suggestions to be meaningful, you need to use GitHub to apply the changes, pull the results, fix your code, push the results, _and_ then later squash your commits.

I think to be useful this really needs to either be sufficiently smart to also fix usages, or only target changes that aren't going to require more changes elsewhere.

**Comment by taragu** [comment]
The last use case left is package comments. For these, the line number of `lint.Problem` is different than the actual line number of the problem location. An example problem would be "package comment should not have leading space" 
```
/*
    Package foo is pretty sweet.
*/
package foo
```
The line number `p.Problem.Line` and the line text `p.LineText` points to `/*`. So this doesn't really fit in with the existing implementation of [`golint_suggestion.go`](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/golint/suggestion/golint_suggestion.go), and I haven't thought of a good way to handle this. 

@cjwagner @stevekuznetsov @bentheelder @fejta any thoughts?

**Comment by stevekuznetsov** [comment]
If we're just pasting string suggestions and not using GItHub's beta review suggestion tool I think just pasting it to the line that the linter picks up is fine

**Comment by matthyx** [comment]
@taragu is this still being worked on? Should we close that?

**Comment by taragu** [comment]
@matthyx no this is not being worked on. If there's no objection we can close this issue

**Comment by matthyx** [comment]
I had the impression this was the umbrella issue for all your great changes regarding lint.
Thanks a lot :)
I will let @BenTheElder reopen it, if needed.
/close
