### ISSUE TITLE
Clean up Prow log spam

### ISSUE THREAD

**Issue by ibzib** [kubernetes/test-infra#9840]
Prow logs a lot of debugging info that probably isn't necessary or desirable at this point in its development.
/cc @BenTheElder @cjwagner

**Comment by cjwagner** [comment]
There may be excessive debug level logs, but my main concern is with the error logs. In particular `deck` generates a lot of GCS errors, sometimes even large bursts of the same error.
We should try to handle these errors more gracefully and/or consider downgrading some of the error messages to warnings.

**Comment by stevekuznetsov** [comment]
I think our error+warning levels are pretty quiet (since I watch mine religiously), but I'm not on a newer version yet ...

**Comment by stevekuznetsov** [comment]
I always run on `debug` level FWIW -- it's very useful after the fact. Whenever I see spammy warnings or errors, I squash them. Would love someone else to jump on that bandwagon as well :)

**Comment by cjwagner** [comment]
I'm on the bandwagon with you. We have logs set at the debug level and I monitor periodically at the warning level.
https://github.com/kubernetes/test-infra/blob/645ca4a6589104328a70dd242025beb76f060044/prow/config.yaml#L42

**Comment by cjwagner** [comment]
I'm checking the logs before updating Prow and seeing a lot of error level log spam from Deck:
```
{
  component:  "deck"   
  level:  "error"   
  msg:  "invalid JUnit test status string"   
  status:  "error"   
 }
```
```
{
  component:  "deck"   
  level:  "error"   
  msg:  "Failed to fetch artifact started.json: error getting gcs attributes for artifact: storage: object doesn't exist"   
 }
```
```
{
  component:  "deck"   
  level:  "error"   
  msg:  "Failed to fetch artifact artifacts/junit_runner.xml: error getting gcs attributes for artifact: storage: object doesn't exist"   
 }
```

I'm pretty confident that these shouldn't be error level at all, but in either case these messages do not provide enough context to be actionable.
/assign @Katharine 
Are these really unexpected errors?

**Comment by Katharine** [comment]
I think they are! By the time it decides it wants to fetch these, it must have previously had cause to believe they exist (generally as a result of a directory listing). I'm not aware of any legitimate context in which it would try to request these without being confident they actually exist.

**Comment by Katharine** [comment]
It would certainly be nice if the errors were more specific about what exactly it was trying to look up.

**Comment by stevekuznetsov** [comment]
I have been reporting those for a while...

**Comment by cjwagner** [comment]
Deck is still spamming the logs. In addition to the messages listed above I now also see a bunch of warnings like:
```
{
  component:  "deck"   
  error:  "error getting prowjob: prowjob not found"   
  id:  "1120889818327289862"   
  job:  "pull-kubernetes-e2e-gce-device-plugin-gpu"   
  level:  "warning"   
  msg:  "Log not found."   
 }
```

**Comment by stevekuznetsov** [comment]
Yep, noted [here](https://kubernetes.slack.com/archives/CDECRSC5U/p1557350652375300) and [here](https://kubernetes.slack.com/archives/CDECRSC5U/p1557350675375600). The two errors we see a load of are:

```
{"component":"deck","error":"error getting prowjob: prowjob not found","id":"2","job":"periodic-ci-azure-e2e-forceupdate","level":"warning","msg":"Log not found.","time":"2019-05-08T21:17:50Z"}
{"component":"deck","error":"pods \"e8614eba-710d-11e9-be42-0a58ac1066c7\" not found","id":"367","job":"pull-ci-openshift-hive-master-integration","level":"warning","msg":"Log not found.","time":"2019-05-08T21:23:11Z"}
```
