### ISSUE TITLE
As a contributor I'd like the instruct prow to run a test for a PR N times

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/test-infra#9855]
In this PR https://github.com/knative/build/pull/430 I'm trying to flush out a flakey test

I repeatedly need to invoke `/test pull-knative-build-integration-tests` in order to run the test numerous times in hopes of guaranteeing there is no flakiness

It'd be nice if I could type something along the lines of
```
/test pull-knative-build-integration-tests 10
```

This would run the integration test sequentially ten times and stop at any point if there is a failure

@adrcunha suggested I open this issue upstream
- downstream tracking issue https://github.com/knative/test-infra/issues/197

**Comment by BenTheElder** [comment]
hmm this seems pretty specific, though interesting...

seems like something we'd want to limit. Also, it introduces more state into a relatively stateless set of services. we could probably dodge this by annotating the original prowjob with a counter of remaining runs. and have a separate controller create new jobs whenever a job with a non-zero counter finishes, but this sort of thing would be a bit involved...

abuse seems like an issue as well, what if I say `/test pull-knative-build-integration-tests 10000` or do this on a dozen PRs?

**Comment by krzyzacy** [comment]
I think we don't want to spam our CI, if you want to test things like flakiness, you can trigger multiple parallel runs locally? :-)

**Comment by stevekuznetsov** [comment]
Agreed with the above, generally not super interested in giving people a big button to push N times.

**Comment by fejta** [comment]
This does not appear to be something we want upstream.
