### ISSUE TITLE
deploy all the rbac rules for prow.k8s.io

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9867]
we have them committed but not deployed, also deployers will need to get their own clusterrole first, so, clean up time :-)

cc maintainer of k8s-prow: @fejta @BenTheElder @cjwagner @amwat @ixdy

**Comment by krzyzacy** [comment]
/remove-lifecycle stale

we have rbac for newly-added controllers at least..

**Comment by cjwagner** [comment]
See https://github.com/kubernetes/test-infra/pull/12230#issue-271091036
I think that we'll need to recreate the cluster to disable legacy authentication. If that is the case then this is probably something we should change when switching to a CNCF owned Prow cluster.

**Comment by stevekuznetsov** [comment]
Oh I thought you had enabled RBAC when the migration happened between versions

**Comment by stevekuznetsov** [comment]
Do you imagine that will be hard to do in the current cluster? Why?

**Comment by cjwagner** [comment]
I thought we'd need to recreate the cluster to disable legacy authentication. It looks like that might not be true though.

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/milestone v1.16
/assign @cjwagner 
where do we stand with this?

**Comment by cjwagner** [comment]
It looks like we can enable legacy authorization without recreating a new cluster. If that's the case we just need to deploy all the RBAC rules and flip the switch.
It is possible that our RBAC rules will be missing some necessary permissions though since we haven't required RBAC thus far so we'll want to be ready to add any permissions we missed quickly after flipping the switch.

**Comment by stevekuznetsov** [comment]
If just do a review to make sure the rules are in sync with what OpenShift runs you should hit no issues

**Comment by cjwagner** [comment]
Lets follow this suggestion too: https://github.com/kubernetes/test-infra/pull/8288#discussion_r197955337

**Comment by fejta** [comment]
ref https://github.com/kubernetes/test-infra/issues/15806
