### ISSUE TITLE
Prow: Proposal: priority labels should be exclusive and replacing

### ISSUE THREAD

**Issue by jberkus** [kubernetes/test-infra#9875]
Now that failing-test & flake are Kinds, we should have prow enforce making priorities unique, since there is no longer any legitimate reason for an issue or PR to have more that one priority.

The simplest and most helpful version of this would be to simply replace the existing priority with the new one whenever a new priority is selected.  This would eliminate the need to use /remove-priority (in fact, we could eliminate remove-priority entirely, and instead instruct people to switch things to /priority backlog).

Feedback?

@spiffxp 

/kind cleanup
/priority important-longterm

**Comment by BenTheElder** [comment]
SGTM :+1: 
cc @cjwagner

**Comment by spiffxp** [comment]
This can be addressed via https://github.com/kubernetes/test-infra/issues/6095 but won't happen in Q4.  I sorta want to close this as a dupe and ask you to comment over there, but I leave that decision to you.

Alternatively if you want this sooner, you could try making a "priority" version of the [stage](/prow/plugins/stage) plugin which has this behavior hardcoded for one specific set of labels

**Comment by nikhita** [comment]
> Alternatively if you want this sooner, you could try making a "priority" version of the stage plugin which has this behavior hardcoded for one specific set of labels

This would be easy, but won't it lead to a breaking change since `label` won't handle the `priority/` labels anymore and I'd have to explicitly enable the `priority` plugin?

**Comment by jberkus** [comment]
closing as duplicate of #6095 

/close
