### ISSUE TITLE
Regression: PR Dashboard size sorting alphabetically

### ISSUE THREAD

**Issue by tallclair** [kubernetes/test-infra#9901]
Sorting by size on the PR dashboard no longer sorts XS -> XXL, but is instead sorting alphabetically by the size letter (e.g. L, S, XS, XXL)

**Comment by ibzib** [comment]
Looks like whitespace in `colname` messing up case matching https://github.com/kubernetes/test-infra/blob/master/gubernator/static/pr.js#L8
/assign @Katharine
