### ISSUE TITLE
Support kernel mailing lists in Prow

### ISSUE THREAD

**Issue by AviKndr** [kubernetes/test-infra#9905]
Our team (KUnit) is working on adding unit testing into the Linux kernel and, as such, is interested in a solution for running presubmit on patches sent to the mailing list and replying back. This would conceivably be easiest if we could run a mail server on prow to hold received patches and apply them to the upstream kernel during the cloning phase. The mail server should also send emails back to the mailing list, functionality which has been requested here: #8668 

/area prow
/kind feature

@krzyzacy

**Comment by krzyzacy** [comment]
cc @BenTheElder @kargakis @stevekuznetsov @cjwagner @fejta @spiffxp in case there are concerns.

**Comment by krzyzacy** [comment]
discussed offline with @BenTheElder and @Katharine, storing patches in CRD might not be a good idea, we might be able to bring up a git server, and somehow figure out mapping patches into git branches, and assign a subdomain so jobs can clone from the git server.

That part doesn't have to be part of prow, it can just be a k8s controller. We can still use existing `clone_refs` logic to handle testing. You can even trigger a prowjob via pubsub (@sebastienvas gonna take a stab there). Then the only thing you need will be a prow reporter :-)

**Comment by fejta** [comment]
Please make sure this has a reviewed design doc before any implementation begins

**Comment by krzyzacy** [comment]
yeah trying to throw out some initial ideas here, punt to @AviKndr to write a design doc and potentially present the idea in sig-testing

**Comment by stevekuznetsov** [comment]
This functionality could be achieved by running your own `git` server with pullable refs for each patch submitted, then creating ProwJob CRDs directly and requesting a decorated job that pulls from your server. None of the components would necessarily need to live with the other Prow components but the latter service would need RBAC to create ProwJob CRDs on the Prow cluster.

**Comment by stevekuznetsov** [comment]
True as @krzyzacy  mentioned this almost requires that we split out reporting from `plank`.

**Comment by AviKndr** [comment]
Hello everyone, here is an updated design doc for this functionality: [link](https://docs.google.com/document/d/1FdzEvyDh8KnyAxrizIBQRt1uSvW5DyxEV1WEduQ_VNo/edit?usp=sharing) 

In Summary:
- We plan to manage our own component for applying patches / triggering jobs. Would appreciate any feedback interested parties have on the current design.
- I can work on adding mail reporting for crier as per #8668.
