### ISSUE TITLE
Followup to contributor experience survey

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/test-infra#9910]
Let's take a look at the automation most hated / most liked and see if there are common themes we can address.  I'll consider this closed when I got a summary and some followup issues created.

/kind documentation
/sig testing
/sig contributor-experience
/assign

**Comment by stevekuznetsov** [comment]
Where's the data for this?

**Comment by nikhita** [comment]
> Where's the data for this?

@parispittman probably knows more.

**Comment by parispittman** [comment]
about the data -> https://github.com/kubernetes/community/blob/master/sig-contributor-experience/contribex-survey-2018.md
some charts -> https://docs.google.com/presentation/d/1Mdbx8OthahFzA7zg4L6vQ2WjdW8a-aUxE0ZXTugB1aA/edit?usp=sharing

this is my [fork](https://docs.google.com/spreadsheets/d/1TlvG5MhAYPGhWsmIhloHhe6qKmDIG9PzIa41qNIDLYI/edit?usp=sharing) of the data that has some of the qualitative questions drawn out in tabs with notes that may be useful to you

**Comment by spiffxp** [comment]
/milestone v1.15
Same criteria, see if there pain points we have issues to address, make some if they don't exist, bump them in priority if they do, if this falls stale again let's just close

**Comment by stevekuznetsov** [comment]
We need to put this on a meeting agenda.
