### ISSUE TITLE
secrets_agent and GetSecret() should use a RWMutex

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#9922]
https://golang.org/pkg/sync/#RWMutex

https://github.com/kubernetes/test-infra/blob/521f040d498f43a03ab80ce568bf61a642b92440/prow/config/secrets_agent.go#L30

https://github.com/kubernetes/test-infra/blob/521f040d498f43a03ab80ce568bf61a642b92440/prow/config/secrets_agent.go#L87-L91

/help
/good-first-issue

Entity A calling `GetSecret()` should not block Entity B from doing the same. We only need to prevent people from calling `GetSecret()` while we are inside `setSecret()`

**Comment by kkohtaka** [comment]
I opened a PR. Can you review #9944 ?
