### ISSUE TITLE
Future improvement on prow - gerrit/pubsub integration

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/test-infra#9923]
(open a tracking issue for future improvements)

[ x ] - Support postsubmit jobs
[ ] - Support parsing comments, and mux it to plugin handlers
[ ] - Integrate with gerrit labeling system with existing plugins
[ x ] - enhance pubsub messages to include more information
[ ] - support trigger prowjobs from pubsub (cc @sebastienvas)

**Comment by roufique7** [comment]
Hi

**Comment by krzyzacy** [comment]
/remove-lifecycle stale

made some progress on gerrit (thanks @ibzib), and @sebastienvas has sub controller mostly working now

**Comment by krzyzacy** [comment]
the only thing we'd still want to have is https://github.com/kubernetes/test-infra/issues/11162, punt to that instead :-)
