### ISSUE TITLE
Automatically add issues/PR to a project board based on a GitHub query

### ISSUE THREAD

**Issue by cblecker** [kubernetes/test-infra#9925]
One missing feature of GitHub's project boards is the ability to automatically add issues/PRs to a project board based on a GitHub search query.

Two examples of how this would be useful:
- KEP tracking
```
is:open org:kubernetes label:kind/kep
```
would automatically be added to https://github.com/kubernetes-sigs/architecture-tracking/projects/2

- API reviews
```
is:open org:kubernetes label:kind/api-change
```
would automatically be added to https://github.com/kubernetes-sigs/architecture-tracking/projects/3

We'd probably only want to respond to label add or issue/PR open events rather than poll on a cron, because we'd want the ability to manually remove from a project board if it doesn't apply. But the thought is if we add a framework that we can configure with query = project card create, then we could reuse it in a lot of different places.

GitHub API docs: https://developer.github.com/v3/projects/cards/#create-a-project-card

cc: @jdumars @bgrant0607 @spiffxp @dims 
also cc @idvoretskyi @guineveresaenger because this is something that IMO GitHub should do out of the box, considering the "Add a Card" button accepts a search query to find cards in the first place to add. 👀

**Comment by dims** [comment]
I like it @cblecker ! basically add things to Backlog right?

**Comment by wwwil** [comment]
Hi! I've started on a solution to this and have something working which I'm going to tidy up and submit a PR for.

I plan to store the projects and associated queries in the `plugins.yaml` in the format:
```
projects:
  - name: my-project
    org: my-org
    query:
      state: open
      labels:
        - my-label
```

I'm quite new to this project, Kubernetes and Go so any advice or feedback is appreciated! Thanks!

**Comment by stevekuznetsov** [comment]
Hello @wwwil!

I would suggest using `"org/repo"` as your keys as per other configurations. Look at the Tide configuration for query syntax exposed as configuration.

**Comment by stevekuznetsov** [comment]
Also, I would suggest writing a design document either as a pull request to test-infra or as a Google doc that you can share with kubernetes-sig-testing@googlegroups.com. I think there are a lot of potential open questions here:

 - is this a plugin? Does it react to Pull Request events to catch new PRs, or changed PRs?
 - is this a Prow component?
 - is it a standalone cli command for admins?
 - does it use GitHub queries verbatim? If so, how often does it sync? What are the implications for tokens use?

Often it's best to try to get answers to these questions before code is written so you don't have to re-write code in the future.

**Comment by stevekuznetsov** [comment]
Also would love to hear from @idvoretskyi @guineveresaenger  to see if this is something that GitHub might implement, we wouldn't want to duplicate work!

**Comment by cblecker** [comment]
also cc @jessfraz 👀

**Comment by stevekuznetsov** [comment]
@wwwil a markdown file could work - however if you have most of the code already written it may not make the most sense. Maybe open the PR when you're ready and we can hash out some ideas there, or comment on this issue and we could do it here.

My two largest questions are:

 - how are you determining if a pull request for which you've gotten an event matches a query? On the components where we expose queries, we use the query API to run them. Are you doing that, or parsing the data in the push event to determinine if it matches? 
  - in what cases does this new plugin use additional API tokens? Do we want to create a plugin that always enforces the condition or one that's best effort? Will this impact API rate limits greatly? Queries can reference pretty much any of the attributes of a pull request, so it would be interesting to see when we need to reach out to GitHub for additional metadata on a PR when determining if it fits a query

**Comment by wwwil** [comment]
I've submitted a pull request for what I have so far. I hope it make's sense, I'm quite new to this so any feedback is appreciated.

Currently the plugin uses the data in the pull request event so the fields that can be used in a query are limited to the ones the plugin can work with.

As it's responding to pull request events I think that makes it best effort, as it won't add existing pull requests that match the query unless they change.

**Comment by justaugustus** [comment]
Very interested in this!
@wwwil -- when you have a design proposal in mind, can you also share it with kubernetes-pm@googlegroups.com?

**Comment by wwwil** [comment]
@justaugustus I've updated the PR body to reflect the current design. How should I go about sharing it, I've not really used Google groups much.

**Comment by spiffxp** [comment]
/assign @hh @brahmaroutu 
/remove-lifecycle stale
this came up during the k8s-conformance meeting, there was discussion of a "project manager" plugin

**Comment by justaugustus** [comment]
What's the current status on this?
/milestone v1.18

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
/remove-priority important-soon
I still think this could be really cool but have no idea where it's at, and I don't think having it frozen has helped it move forward

**Comment by omerbensaadon** [comment]
Hey have y'all seen this: https://github.com/actions/add-to-project 

I think it would actually solve this problem quite nicely :D 

I know there were some permissions issues with that action when I've brought it up in the past... 🤔 we're working on native auto-add functionality right now but it won't be ready for awhile

**Comment by BenTheElder** [comment]
This and https://github.com/kubernetes/community/issues/5535 are sort of a dupe.

The implementation would most likely live in github.com/kubernetes-sigs/prow now, kubernetes/community is a more visible place to discuss workflow changes and kubernetes-sigs/prow is the best place to discuss implementation details / tooling feature requests.

We do have https://github.com/kubernetes-sigs/prow/tree/main/pkg/plugins/projectmanager after https://github.com/kubernetes/test-infra/pull/12326 but any expansion on this hasn't been discussed here for years now and should be discussed in kubernetes-sigs/prow going forward.
