### ISSUE TITLE
k8s-ci-robot don't update sig/area/kind on pr changes

### ISSUE THREAD

**Issue by yagonobre** [kubernetes/test-infra#9934]
## What happened?
I remove some code from my pr, and the `k8s-ci-robot` don't clean up the labels related to sig, area and kind.

I can send a pr to fix that.

/kind bug

**Comment by BenTheElder** [comment]
/area prow
cc @cjwagner

**Comment by yagonobre** [comment]
I'll close this issue, because make `k8s-ci-robot` remove this labels will remove manually added labels too.

**Comment by nikhita** [comment]
> I'll close this issue, because make k8s-ci-robot remove this labels will remove manually added labels too.

IMHO it would still be useful to remove the labels. Most manually added labels are `kind/*` labels and the bot does not add this label automatically. The bot only adds the `area/*` and `sig/*` labels automatically, which are rarely changed manually. In such cases, I think manually changing them again should be fine. Wdyt?

**Comment by yagonobre** [comment]
@nikhita make senses! I'll work on it tomorrow.

**Comment by cjwagner** [comment]
FWIW I think `sig/*` labels are added manually pretty often. Note that mentioning a sig is also used to add `sig/*` labels via the `sigmention` plugin.
e.g. @kubernetes/sig-testing 

This change wouldn't behave well with the `sigmention` plugin.

**Comment by nikhita** [comment]
> If a PR has a label that it shouldn't, the label can be removed with /remove-area or /remove-sig and it seems easier to notice an incorrectly applied label than a missing label.

:+1: 

> If this feature only makes sense for some labels we could add configuration to indicate which labels can be automatically removed?

I can't think of any such labels. :thinking:

**Comment by nikhita** [comment]
@yagonobre Do you think we need to add such configuration for some labels? If not, please feel free to close the issue. Sorry for the confusion. :)

**Comment by yagonobre** [comment]
I no have enough context to know if we have any labels that must be automatically removed.

**Comment by cjwagner** [comment]
Closing for now. Lets reopen if/when we find a use case for this.
