### ISSUE TITLE
Testgrid not displaying recent builds

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/test-infra#996]
This makes tracking test failures quite difficult.

**Comment by ixdy** [comment]
I think @krzyzacy is working on this

**Comment by krzyzacy** [comment]
I deployed a new server yesterday and it started to regenerate all the data all over again (currently it has run through till kubernetes-e2e-gke-1.3-*, in alphabetic order.. I'm monitoring it)

Will do deployment towards end of week next time, and also need to really speed it up.

**Comment by krzyzacy** [comment]
seems stable now.

**Comment by krzyzacy** [comment]
Just add a note here: Talked with deitz@ today and figured out it was due to an internal version change that invalidated all the cache which causes it to regenerate everything over again. Which should not happen again or if same thing happens again we will know where to look.
