### ISSUE TITLE
Better tool for Prow job debugging. 

### ISSUE THREAD

**Issue by erain** [kubernetes/test-infra#9970]
This is a feature request for better Prow debugging tooling / documents. 

Currently, the only way to debug a Prow job is to use the docker image, however some of the kubetest images, e.g. [kubekins-e2e](https://github.com/kubernetes/test-infra/tree/master/images/kubekins-e2e), have non-trivial setup (its entrypoint, $GOPATH, etc.). It is lack of clear guidance for Prow users on how to start debugging. 

It would be great to have tooling for such purpose. Just some ideas:

1. **local Prow**: to have a Prow job running locally inside a docker container. 
2. **debug image**: the image contains everything (minus security key), and could "just run".

Also many to have documents on how to debug Prow job in general. Currently I come up with something like the following to mount every dependent source repo into the image, but I guess there is something better: 

```bash
docker run -it --entrypoint "" --name kubetest-$RANDOM \
  -v $GOPATH/src/repo-1:/workspace/repo1 \
  -v $GOPATH/src/repo-2:/workspace/repo2 \
  -v $GOPATH/src/k8s.io/test-infra:/workspace/test-infra \
  -v $HOME/.ssh:/workspace/.ssh/ \
 kubekins-e2e:<version-tag> /bin/bash
...
scenarios/kubernetes_e2e.py --check-leaked-resources --env ...
```

Thanks!

**Comment by stevekuznetsov** [comment]
There was an issue tracking this somewhere -- a tool to output the `docker run` command to debug locally. @BenTheElder do you remember where that was?

**Comment by BenTheElder** [comment]
#6590
